include::./index.adoc[]

[[v58-4-0]]
=== Hebreus, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v58-4-1]]

^<<v58-4-1,1>>^ TEMAMOS, pois que, porventura, deixada a promessa de entrar no seu repouso, pareça que algum de vós fica para trás.

[[v58-4-2]]

^<<v58-4-2,2>>^ Porque também a nós foram pregadas as boas-novas, como a eles, mas a palavra da pregação nada lhes aproveitou, porquanto não estava misturada com a fé naqueles que a ouviram.

[[v58-4-3]]

^<<v58-4-3,3>>^ Porque nós, os que temos crido, entramos no repouso, tal como disse: Assim jurei na minha ira que não entrarão no meu repouso; embora as suas  obras estivessem acabadas desde a fundação do mundo.

[[v58-4-4]]

^<<v58-4-4,4>>^ Porque em certo lugar disse assim do dia  sétimo: E repousou Deus de todas as suas obras no sétimo dia.

[[v58-4-5]]

^<<v58-4-5,5>>^ E outra vez neste lugar : Não entrarão no meu repouso.

[[v58-4-6]]

^<<v58-4-6,6>>^ Visto, pois, que resta que alguns entrem nele, e que aqueles a quem primeiro foram pregadas as boas-novas, não entraram por causa da desobediência.

[[v58-4-7]]

^<<v58-4-7,7>>^ Determina outra vez um certo dia, Hoje, dizendo por Davi, muito tempo depois, como está dito: Hoje, se ouvirdes a sua voz, não endureçais os vossos corações.

[[v58-4-8]]

^<<v58-4-8,8>>^ Porque, se Josué lhes houvesse dado repouso, não falaria depois disso de outro dia.

[[v58-4-9]]

^<<v58-4-9,9>>^ Portanto resta ainda um repouso para o povo de Deus.

[[v58-4-10]]

^<<v58-4-10,10>>^ Porque aquele que entrou no seu repouso, ele próprio repousou de suas obras, como Deus das suas.

[[v58-4-11]]

^<<v58-4-11,11>>^ Procuremos pois entrar naquele repouso, para que ninguém caia no mesmo exemplo de desobediência.

[[v58-4-12]]

^<<v58-4-12,12>>^ Porque a palavra de Deus é  viva e eficaz, e mais penetrante do que espada alguma de dois gumes, e penetra até à divisão da alma e do espírito, e das juntas e medulas, e é apta para discernir os pensamentos e intenções do coração.

[[v58-4-13]]

^<<v58-4-13,13>>^ E não há criatura alguma encoberta diante dele; antes todas as coisas estão nuas e patentes aos olhos daquele com quem temos de tratar.

[[v58-4-14]]

^<<v58-4-14,14>>^ Visto que temos um grande sumo sacerdote, Jesus, Filho de Deus, que penetrou nos céus, retenhamos firmemente a nossa confissão.

[[v58-4-15]]

^<<v58-4-15,15>>^ Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um  que, como nós, em tudo foi tentado, mas sem pecado.

[[v58-4-16]]

^<<v58-4-16,16>>^ Cheguemos pois com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno.

'''

xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[&#60; Capítulo Anterior] | <<v58-4-0,Topo>> | xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[Próximo Capítulo &#62;]