include::./index.adoc[]

[[v58-6-0]]
=== Hebreus, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v58-6-1]]

^<<v58-6-1,1>>^ PELO que, deixando os rudimentos da doutrina de Cristo, prossigamos até a perfeição, não lançando de novo o fundamento do arrependimento de obras mortas e de fé em Deus.

[[v58-6-2]]

^<<v58-6-2,2>>^ E da doutrina dos batismos, e da imposição das mãos, e da ressurreição dos mortos, e do juízo eterno.

[[v58-6-3]]

^<<v58-6-3,3>>^ E isto faremos, se Deus o permitir.

[[v58-6-4]]

^<<v58-6-4,4>>^ Porque é  impossível que os que já  uma vez foram iluminados, e provaram o dom celestial, e se fizeram participantes do Espírito Santo,

[[v58-6-5]]

^<<v58-6-5,5>>^ E provaram a boa palavra de Deus, e as virtudes do século futuro,

[[v58-6-6]]

^<<v58-6-6,6>>^ E recaíram, sejam outra vez renovados para arrependimento; pois assim, quanto a eles, de novo crucificam o Filho de Deus, e o expõem ao vitupério.

[[v58-6-7]]

^<<v58-6-7,7>>^ Porque a terra que embebe a chuva, que muitas vezes cai sobre ela, e produz erva proveitosa para aqueles por quem é lavrada, recebe a bênção de Deus;

[[v58-6-8]]

^<<v58-6-8,8>>^ Mas a que produz espinhos e abrolhos, é  reprovada, e perto está  da maldição; o seu fim é  ser queimada.

[[v58-6-9]]

^<<v58-6-9,9>>^ Mas de vós, ó amados, esperamos coisas  melhores, e coisas que acompanham a salvação, ainda que assim falamos.

[[v58-6-10]]

^<<v58-6-10,10>>^ Porque Deus não é  injusto para se esquecer da vossa obra, e do trabalho da caridade que para com o seu nome mostrastes, enquanto servistes aos santos; e ainda servis.

[[v58-6-11]]

^<<v58-6-11,11>>^ Mas desejamos que cada um de vós mostre o mesmo cuidado até ao fim, para completa certeza da esperança;

[[v58-6-12]]

^<<v58-6-12,12>>^ Para que vos não façais negligentes, mas sejais imitadores dos que pela fé e paciência herdam as promessas.

[[v58-6-13]]

^<<v58-6-13,13>>^ Porque, quando Deus fez a promessa a Abraão, como não tinha outro maior por quem jurasse, jurou por si mesmo,

[[v58-6-14]]

^<<v58-6-14,14>>^ Dizendo: Certamente, abençoando te abençoarei, e multiplicando te multiplicarei.

[[v58-6-15]]

^<<v58-6-15,15>>^ E assim, esperando com paciência, alcançou a promessa.

[[v58-6-16]]

^<<v58-6-16,16>>^ Porque os homens certamente juram por alguém superior a eles, e o juramento para confirmação é , para eles, o fim de toda a contenda.

[[v58-6-17]]

^<<v58-6-17,17>>^ Pelo que, querendo Deus mostrar mais abundantemente a imutabilidade do seu conselho, aos herdeiros da promessa, se interpôs com juramento;

[[v58-6-18]]

^<<v58-6-18,18>>^ Para que por duas coisas imutáveis, nas quais é  impossível que Deus minta, tenhamos a firme consolação, nós, os que pomos o nosso refúgio em reter a esperança proposta;

[[v58-6-19]]

^<<v58-6-19,19>>^ A qual temos como âncora da alma segura e firme, e que penetra até ao interior do véu.

[[v58-6-20]]

^<<v58-6-20,20>>^ Onde Jesus, nosso  precursor, entrou por nós, feito eternamente sumo sacerdote, segundo a ordem de Melquisedeque.

'''

xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[&#60; Capítulo Anterior] | <<v58-6-0,Topo>> | xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[Próximo Capítulo &#62;]