include::./index.adoc[]

[[v58-12-0]]
=== Hebreus, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v58-12-1]]

^<<v58-12-1,1>>^ PORTANTO nós também, pois que estamos rodeados de uma tão grande nuvem de testemunhas, deixemos todo o embaraço, e o pecado que tão de perto nos rodeia, e corramos com paciência a carreira que nos está proposta:

[[v58-12-2]]

^<<v58-12-2,2>>^ Olhando para Jesus, autor e consumador da fé, o qual pelo gozo que lhe estava proposto suportou a cruz, desprezando a afronta e assentou-se à destra do trono de Deus.

[[v58-12-3]]

^<<v58-12-3,3>>^ Considerai pois aquele que suportou tais contradições dos pecadores contra si mesmo, para que não enfraqueçais, desfalecendo em vossos ânimos.

[[v58-12-4]]

^<<v58-12-4,4>>^ Ainda não resististes até ao sangue, combatendo contra o pecado.

[[v58-12-5]]

^<<v58-12-5,5>>^ E já vos esquecestes da exortação que argumenta convosco como filhos: Filho meu, não desprezes a correção do Senhor, e não desmaies quando por ele fores repreendido;

[[v58-12-6]]

^<<v58-12-6,6>>^ Porque o Senhor corrige o que ama, e açoita a qualquer que recebe por filho.

[[v58-12-7]]

^<<v58-12-7,7>>^ Se suportais a correção, Deus vos trata como filhos; porque, que filho há a quem o pai não corrija?

[[v58-12-8]]

^<<v58-12-8,8>>^ Mas, se estais sem disciplina, da qual todos são feitos participantes, sois então bastardos, e não filhos.

[[v58-12-9]]

^<<v58-12-9,9>>^ Além do que tivemos nossos pais segundo a carne, para nos corrigirem, e nós os reverenciamos: não nos sujeitaremos muito mais ao Pai dos espíritos, para vivermos?

[[v58-12-10]]

^<<v58-12-10,10>>^ Porque aqueles, na verdade, por um pouco de tempo, nos corrigiam como bem lhes parecia; mas este, para nosso  proveito, para sermos participantes da sua santidade.

[[v58-12-11]]

^<<v58-12-11,11>>^ E, na verdade, toda a correção, ao presente, não parece ser de gozo, senão de tristeza, mas depois produz um fruto pacífico de justiça nos exercitados por ela.

[[v58-12-12]]

^<<v58-12-12,12>>^ Portanto tornai a levantar as mãos cansadas, e os joelhos desconjuntados,

[[v58-12-13]]

^<<v58-12-13,13>>^ E fazei veredas direitas para os vossos pés, para que o que manqueja se não desvie inteiramente, antes seja sarado.

[[v58-12-14]]

^<<v58-12-14,14>>^ Segui a paz com todos, e a santificação, sem a qual ninguém verá o Senhor:

[[v58-12-15]]

^<<v58-12-15,15>>^ Tendo cuidado de que ninguém se prive da graça de Deus, e de que nenhuma raiz de amargura, brotando, vos  perturbe, e por ela muitos se contaminem.

[[v58-12-16]]

^<<v58-12-16,16>>^ E ninguém seja fornicário, ou profano, como Esaú, que por um manjar vendeu o seu direito de primogenitura.

[[v58-12-17]]

^<<v58-12-17,17>>^ Porque bem sabeis que, querendo ele ainda depois herdar a bênção, foi rejeitado, porque não achou lugar de arrependimento, ainda que com lágrimas o buscou.

[[v58-12-18]]

^<<v58-12-18,18>>^ Porque não chegastes ao monte palpável, aceso em fogo, e à escuridão, e às trevas, e à tempestade,

[[v58-12-19]]

^<<v58-12-19,19>>^ E ao sonido da trombeta, e à voz das palavras, a qual os que a ouviram pediram que se lhes não falasse mais;

[[v58-12-20]]

^<<v58-12-20,20>>^ Porque não podiam suportar o que se lhes  mandava: se até um animal tocar o monte, será apedrejado.

[[v58-12-21]]

^<<v58-12-21,21>>^ E tão terrível era a visão que  Moisés disse: Estou todo assombrado, e tremendo.

[[v58-12-22]]

^<<v58-12-22,22>>^ Mas chegastes ao monte de Sião, e à cidade do Deus vivo, à Jerusalém celestial, e aos muitos milhares de anjos;

[[v58-12-23]]

^<<v58-12-23,23>>^ À universal assembleia e igreja dos primogênitos, que estão inscritos nos céus, e a Deus, o juiz de todos, e aos espíritos dos justos aperfeiçoados;

[[v58-12-24]]

^<<v58-12-24,24>>^ E a Jesus, o Mediador duma Nova Aliança, e ao sangue da aspersão, que fala melhor do que o de  Abel.

[[v58-12-25]]

^<<v58-12-25,25>>^ Vede que não rejeiteis ao que fala; porque, se não escaparam aqueles que rejeitaram o que na terra os advertia, muito menos nós, se nos desviarmos daquele que é dos céus:

[[v58-12-26]]

^<<v58-12-26,26>>^ A voz do qual moveu então a terra, mas agora anunciou, dizendo: Ainda uma vez comoverei, não só a terra, senão também o céu.

[[v58-12-27]]

^<<v58-12-27,27>>^ E esta palavra: Ainda uma vez, mostra a mudança das coisas móveis, como coisas feitas, para que as imóveis permaneçam.

[[v58-12-28]]

^<<v58-12-28,28>>^ Pelo que, tendo recebido um reino que não pode ser abalado, retenhamos a graça, pela qual sirvamos a Deus agradavelmente com reverência e piedade;

[[v58-12-29]]

^<<v58-12-29,29>>^ Porque o nosso Deus é  um fogo consumidor.

'''

xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[&#60; Capítulo Anterior] | <<v58-12-0,Topo>> | xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[Próximo Capítulo &#62;]