include::./index.adoc[]

[[v58-10-0]]
=== Hebreus, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v58-10-1]]

^<<v58-10-1,1>>^ PORQUE, tendo a lei a sombra dos bens futuros, e não a imagem exata das coisas, nunca, pelos mesmos sacrifícios que continuamente se oferecem cada ano, pode aperfeiçoar os que a eles se chegam.

[[v58-10-2]]

^<<v58-10-2,2>>^ Doutra maneira, teriam deixado de se oferecer, porque, purificados uma vez os ministrantes, nunca mais teriam consciência de pecado.

[[v58-10-3]]

^<<v58-10-3,3>>^ Nesses sacrifícios, porém, cada ano se faz comemoração dos pecados,

[[v58-10-4]]

^<<v58-10-4,4>>^ Porque é impossível que o sangue dos touros e dos bodes tire os pecados.

[[v58-10-5]]

^<<v58-10-5,5>>^ Pelo que, entrando no mundo, diz: Sacrifício e oferta não quiseste, mas corpo me preparaste;

[[v58-10-6]]

^<<v58-10-6,6>>^ Holocaustos e oblações  pelo pecado não te agradaram.

[[v58-10-7]]

^<<v58-10-7,7>>^ Então disse: Eis aqui venho (no princípio do livro está escrito de mim), para fazer, ó Deus, a tua vontade.

[[v58-10-8]]

^<<v58-10-8,8>>^ Como acima diz, Sacrifício e oferta, e holocaustos e oblações  pelo pecado não quiseste, nem te agradaram (os quais se oferecem segundo a lei).

[[v58-10-9]]

^<<v58-10-9,9>>^ Então disse: Eis aqui venho, para fazer, ó Deus, a tua vontade. Tira o primeiro, para estabelecer o segundo.

[[v58-10-10]]

^<<v58-10-10,10>>^ Na qual vontade temos sido santificados pela oblação do corpo de Jesus Cristo, feita  uma vez.

[[v58-10-11]]

^<<v58-10-11,11>>^ E assim todo o sacerdote aparece cada dia, ministrando e oferecendo muitas vezes os mesmos sacrifícios, que nunca podem tirar os pecados;

[[v58-10-12]]

^<<v58-10-12,12>>^ Mas este, havendo oferecido um único sacrifício pelos pecados, está assentado para sempre à destra de Deus,

[[v58-10-13]]

^<<v58-10-13,13>>^ Daqui em diante esperando até que os seus inimigos sejam postos por escabelo de seus pés.

[[v58-10-14]]

^<<v58-10-14,14>>^ Porque com uma só oblação aperfeiçoou para sempre os que são santificados.

[[v58-10-15]]

^<<v58-10-15,15>>^ E também o Espírito Santo no-lo testifica, porque depois de haver dito:

[[v58-10-16]]

^<<v58-10-16,16>>^ Este é  o concerto que farei com eles depois daqueles dias, diz o Senhor: Porei as minhas leis em seus corações, e as escreverei em seus entendimentos; acrescenta :

[[v58-10-17]]

^<<v58-10-17,17>>^ E jamais me lembrarei de seus pecados e de suas iniquidades.

[[v58-10-18]]

^<<v58-10-18,18>>^ Ora, onde há  remissão destes, não há  mais oblação pelo pecado.

[[v58-10-19]]

^<<v58-10-19,19>>^ Tendo pois, irmãos, ousadia para entrar no santuário, pelo sangue de Jesus,

[[v58-10-20]]

^<<v58-10-20,20>>^ Pelo novo e vivo caminho que ele nos consagrou, pelo véu, isto é, pela  sua carne,

[[v58-10-21]]

^<<v58-10-21,21>>^ E tendo um grande sacerdote sobre a casa de Deus,

[[v58-10-22]]

^<<v58-10-22,22>>^ Cheguemo-nos com verdadeiro coração, em inteira certeza de fé; tendo os corações purificados da má consciência, e o corpo lavado com água limpa,

[[v58-10-23]]

^<<v58-10-23,23>>^ Retenhamos firmes a confissão da nossa esperança; porque fiel é o que prometeu.

[[v58-10-24]]

^<<v58-10-24,24>>^ E consideremo-nos uns aos outros, para nos  estimularmos à caridade e às boas obras.

[[v58-10-25]]

^<<v58-10-25,25>>^ Não deixando a nossa congregação, como é costume de alguns, antes admoestando-nos uns aos outros; e tanto mais, quanto vedes que se vai aproximando aquele dia.

[[v58-10-26]]

^<<v58-10-26,26>>^ Porque, se pecarmos voluntariamente, depois de termos recebido o conhecimento da verdade, já não resta mais sacrifício pelos pecados,

[[v58-10-27]]

^<<v58-10-27,27>>^ Mas uma certa expectação horrível de juízo, e ardor de fogo, que há de devorar os adversários.

[[v58-10-28]]

^<<v58-10-28,28>>^ Quebrantando alguém a lei de Moisés, morre sem misericórdia, só  pela palavra de duas ou três testemunhas.

[[v58-10-29]]

^<<v58-10-29,29>>^ De quanto maior castigo cuidais vós será julgado merecedor aquele que pisar o Filho de Deus, e tiver por profano o sangue do testamento, com que foi santificado, e fizer agravo ao Espírito da graça?

[[v58-10-30]]

^<<v58-10-30,30>>^ Porque bem conhecemos aquele que disse: Minha é  a vingança, eu darei a recompensa, diz o Senhor. E outra vez: O Senhor julgará o seu povo.

[[v58-10-31]]

^<<v58-10-31,31>>^ Horrenda coisa é cair nas mãos do Deus vivo.

[[v58-10-32]]

^<<v58-10-32,32>>^ Lembrai-vos, porém, dos dias passados, em que, depois de serdes iluminados, suportastes grande combate de aflições.

[[v58-10-33]]

^<<v58-10-33,33>>^ Em parte fostes feitos espetáculo com vitupérios e tribulações, e em parte fostes participantes com os que assim foram tratados.

[[v58-10-34]]

^<<v58-10-34,34>>^ Porque também vos compadecestes dos que estavam nas prisões, e com gozo permitistes a espoliação dos vossos bens, sabendo que em vós mesmos tendes nos céus uma possessão melhor e permanente.

[[v58-10-35]]

^<<v58-10-35,35>>^ Não rejeiteis pois a vossa confiança, que tem grande e avultado galardão.

[[v58-10-36]]

^<<v58-10-36,36>>^ Porque necessitais de paciência, para que, depois de haverdes feito a vontade de Deus, possais alcançar a promessa.

[[v58-10-37]]

^<<v58-10-37,37>>^ Porque ainda um poucochinho de tempo, e  o que há de vir virá, e não tardará.

[[v58-10-38]]

^<<v58-10-38,38>>^ Mas o justo viverá da fé; e, se ele recuar, a minha alma não tem prazer nele.

[[v58-10-39]]

^<<v58-10-39,39>>^ Nós, porém, não somos daqueles que se retiram para a perdição, mas daqueles que creem para a conservação da alma.

'''

xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[&#60; Capítulo Anterior] | <<v58-10-0,Topo>> | xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[Próximo Capítulo &#62;]