include::./index.adoc[]

[[v58-5-0]]
=== Hebreus, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v58-5-1]]

^<<v58-5-1,1>>^ PORQUE todo o sumo sacerdote, tomado dentre os homens, é constituído a favor dos homens nas coisas concernentes a Deus, para que ofereça dons e sacrifícios pelos pecados;

[[v58-5-2]]

^<<v58-5-2,2>>^ E possa compadecer-se ternamente dos ignorantes e errados; pois também ele mesmo está rodeado de fraqueza.

[[v58-5-3]]

^<<v58-5-3,3>>^ E por esta causa deve ele, tanto pelo povo, como também por si mesmo, fazer oferta pelos pecados.

[[v58-5-4]]

^<<v58-5-4,4>>^ E ninguém toma para si esta honra, senão o que é chamado por Deus, como Aarão.

[[v58-5-5]]

^<<v58-5-5,5>>^ Assim também Cristo se não glorificou a si mesmo, para se fazer sumo sacerdote, mas aquele que lhe disse: Tu és meu Filho, hoje te gerei.

[[v58-5-6]]

^<<v58-5-6,6>>^ Como também diz noutro lugar : Tu és  Sacerdote eternamente, segundo a ordem de Melquisedeque.

[[v58-5-7]]

^<<v58-5-7,7>>^ O qual, nos dias da sua carne, oferecendo, com grande clamor e lágrimas, orações e súplicas ao que o podia livrar da morte, foi ouvido quanto ao que temia.

[[v58-5-8]]

^<<v58-5-8,8>>^ Ainda que era Filho, aprendeu a obediência, por aquilo que padeceu.

[[v58-5-9]]

^<<v58-5-9,9>>^ E, sendo ele consumado, veio a ser a causa de eterna salvação para todos os que lhe obedecem;

[[v58-5-10]]

^<<v58-5-10,10>>^ Chamado por Deus sumo sacerdote, segundo a ordem de Melquisedeque.

[[v58-5-11]]

^<<v58-5-11,11>>^ Do qual muito temos que dizer, de difícil interpretação; porquanto vos fizestes negligentes para ouvir.

[[v58-5-12]]

^<<v58-5-12,12>>^ Porque, devendo já ser mestres pelo tempo, ainda necessitais de que se vos torne a ensinar quais sejam os primeiros rudimentos das palavras de Deus; e vos haveis feito tais  que necessitais de leite, e não de sólido mantimento.

[[v58-5-13]]

^<<v58-5-13,13>>^ Porque qualquer que ainda  se alimenta de leite não está experimentado na palavra da justiça, porque é menino.

[[v58-5-14]]

^<<v58-5-14,14>>^ Mas o mantimento sólido é para os perfeitos, os quais, em razão do costume, têm os sentidos exercitados para discernir tanto o bem como o mal.

'''

xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[&#60; Capítulo Anterior] | <<v58-5-0,Topo>> | xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[Próximo Capítulo &#62;]