include::./index.adoc[]

[[v58-7-0]]
=== Hebreus, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v58-7-1]]

^<<v58-7-1,1>>^ PORQUE este Melquisedeque, que era rei de Salém, sacerdote do Deus Altíssimo, e que saiu ao encontro de Abraão quando ele regressava da matança dos reis, e o abençoou;

[[v58-7-2]]

^<<v58-7-2,2>>^ A quem também Abraão deu o dízimo de tudo, e primeiramente é, por interpretação, rei de justiça, e depois também rei de Salém, que é rei de paz;

[[v58-7-3]]

^<<v58-7-3,3>>^ Sem pai, sem mãe, sem genealogia, não tendo princípio de dias nem fim de vida, mas sendo feito semelhante ao Filho de Deus, permanece sacerdote para sempre.

[[v58-7-4]]

^<<v58-7-4,4>>^ Considerai pois quão grande era  este, a quem até o patriarca Abraão deu os dízimos dos despojos.

[[v58-7-5]]

^<<v58-7-5,5>>^ E os que dentre os filhos de Levi recebem o sacerdócio têm ordem, segundo a lei, de tomar o dízimo do povo, isto é, de seus irmãos, ainda que tenham saído dos lombos de Abraão.

[[v58-7-6]]

^<<v58-7-6,6>>^ Mas aquele cuja genealogia não é contada entre eles tomou dízimos de Abraão, e abençoou o que tinha as promessas.

[[v58-7-7]]

^<<v58-7-7,7>>^ Ora sem contradição alguma, o menor é abençoado pelo maior.

[[v58-7-8]]

^<<v58-7-8,8>>^ E aqui certamente tomam dízimos homens que morrem: ali, porém, aquele de quem se testifica que vive.

[[v58-7-9]]

^<<v58-7-9,9>>^ E, para assim dizer, por meio de Abraão até Levi, que recebe dízimos, pagou dízimos.

[[v58-7-10]]

^<<v58-7-10,10>>^ Porque ainda ele estava nos lombos de seu pai quando Melquisedeque lhe saiu ao encontro.

[[v58-7-11]]

^<<v58-7-11,11>>^ De sorte que, se a perfeição fosse pelo sacerdócio levítico (porque sob ele o povo recebeu a lei), que necessidade havia logo de que outro sacerdote se levantasse, segundo a ordem de Melquisedeque, e não fosse chamado segundo a ordem de Aarão?

[[v58-7-12]]

^<<v58-7-12,12>>^ Porque, mudando-se o sacerdócio, necessariamente se faz também mudança da lei.

[[v58-7-13]]

^<<v58-7-13,13>>^ Porque aquele de quem estas coisas  se dizem pertence a outra tribo, da qual ninguém serviu ao altar.

[[v58-7-14]]

^<<v58-7-14,14>>^ Visto ser manifesto que nosso Senhor procedeu de Judá, e concernente a essa tribo nunca Moisés falou de sacerdócio.

[[v58-7-15]]

^<<v58-7-15,15>>^ E muito mais manifesto é ainda se à semelhança de Melquisedeque se levantar outro sacerdote,

[[v58-7-16]]

^<<v58-7-16,16>>^ Que não foi feito segundo a lei do mandamento carnal, mas segundo a virtude da vida incorruptível.

[[v58-7-17]]

^<<v58-7-17,17>>^ Porque dele assim se testifica: Tu és sacerdote eternamente, segundo a ordem de Melquisedeque.

[[v58-7-18]]

^<<v58-7-18,18>>^ Porque o precedente mandamento é ab-rogado por causa da sua fraqueza e inutilidade.

[[v58-7-19]]

^<<v58-7-19,19>>^ (Pois a lei nenhuma coisa aperfeiçoou) e desta sorte é introduzida uma melhor esperança, pela qual chegamos a Deus.

[[v58-7-20]]

^<<v58-7-20,20>>^ E visto como não é sem prestar juramento (porque certamente aqueles, sem juramento, foram feitos sacerdotes,

[[v58-7-21]]

^<<v58-7-21,21>>^ Mas este com juramento por aquele que lhe disse: Jurou o Senhor, e não se arrependerá: Tu és  sacerdote eternamente, segundo a ordem de Melquisedeque),

[[v58-7-22]]

^<<v58-7-22,22>>^ De tanto melhor concerto Jesus foi feito fiador,

[[v58-7-23]]

^<<v58-7-23,23>>^ E, na verdade, aqueles foram feitos sacerdotes em grande número, porque pela morte foram impedidos de permanecer,

[[v58-7-24]]

^<<v58-7-24,24>>^ Mas este, porque permanece eternamente, tem um sacerdócio perpétuo.

[[v58-7-25]]

^<<v58-7-25,25>>^ Portanto, pode também salvar perfeitamente os que por ele se chegam a Deus, vivendo sempre para interceder por eles.

[[v58-7-26]]

^<<v58-7-26,26>>^ Porque nos convinha tal sumo sacerdote, santo, inocente, imaculado, separado dos pecadores, e feito mais sublime do que os céus;

[[v58-7-27]]

^<<v58-7-27,27>>^ Que não necessitasse, como os sumos sacerdotes, de oferecer cada dia sacrifícios, primeiramente por seus próprios pecados, e depois pelos do povo; porque isto fez ele, uma vez, oferecendo-se a si mesmo.

[[v58-7-28]]

^<<v58-7-28,28>>^ Porque a lei constitui sumos sacerdotes a homens fracos, mas a palavra do juramento, que veio  depois da lei, constitui  ao Filho, perfeito para sempre.

'''

xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[Próximo Capítulo &#62;]