include::./index.adoc[]

[[v58-3-0]]
=== Hebreus, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v58-3-1]]

^<<v58-3-1,1>>^ PELO que, irmãos santos, participantes da vocação celestial, considerai a Jesus Cristo, apóstolo e sumo sacerdote da nossa confissão,

[[v58-3-2]]

^<<v58-3-2,2>>^ Sendo fiel ao que o constituiu, como também o foi Moisés em toda a sua casa.

[[v58-3-3]]

^<<v58-3-3,3>>^ Porque ele é tido por digno de tanto maior glória do que Moisés, quanto maior honra do que a casa tem aquele que a edificou.

[[v58-3-4]]

^<<v58-3-4,4>>^ Porque toda a casa é edificada por alguém, mas o que edificou todas as coisas é  Deus.

[[v58-3-5]]

^<<v58-3-5,5>>^ E na verdade, Moisés foi  fiel em toda a sua casa, como servo, para testemunho das coisas que se haviam de anunciar;

[[v58-3-6]]

^<<v58-3-6,6>>^ Mas Cristo, como Filho sobre a sua própria casa; a qual casa somos nós, se tão somente conservarmos firme a confiança e a glória da esperança até ao fim.

[[v58-3-7]]

^<<v58-3-7,7>>^ Portanto, como diz o Espírito Santo, se ouvirdes hoje a sua voz.

[[v58-3-8]]

^<<v58-3-8,8>>^ Não endureçais os vossos corações, como na provocação, no dia da tentação no deserto,

[[v58-3-9]]

^<<v58-3-9,9>>^ Onde vossos pais me tentaram, me provaram, e viram por quarenta anos as minhas obras.

[[v58-3-10]]

^<<v58-3-10,10>>^ Por isso me indignei contra esta geração, e disse: Estes sempre erram em seu coração, e não conheceram os meus caminhos.

[[v58-3-11]]

^<<v58-3-11,11>>^ Assim jurei na minha ira que não entrarão no meu repouso.

[[v58-3-12]]

^<<v58-3-12,12>>^ Vede, irmãos, que nunca haja em qualquer de vós um coração mau e infiel, para se apartar do Deus vivo.

[[v58-3-13]]

^<<v58-3-13,13>>^ Antes exortai-vos uns aos outros todos os dias, durante o tempo que se chama Hoje, para que nenhum de vós se endureça pelo engano do pecado;

[[v58-3-14]]

^<<v58-3-14,14>>^ Porque nos tornamos participantes de Cristo, se retivermos firmemente o princípio da nossa confiança até ao fim.

[[v58-3-15]]

^<<v58-3-15,15>>^ Enquanto se diz: Hoje, se ouvirdes a sua voz, não endureçais os vossos corações, como na provocação.

[[v58-3-16]]

^<<v58-3-16,16>>^ Porque, havendo-a alguns ouvido, o provocaram; mas não todos os que saíram do Egito por meio de Moisés.

[[v58-3-17]]

^<<v58-3-17,17>>^ Mas com quem se indignou por quarenta anos? Não foi  porventura com os que pecaram, cujos corpos caíram no deserto?

[[v58-3-18]]

^<<v58-3-18,18>>^ E a quem jurou que não entrariam no seu repouso, senão aos que foram desobedientes?

[[v58-3-19]]

^<<v58-3-19,19>>^ E vemos que não puderam entrar por causa da sua  incredulidade.

'''

xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[&#60; Capítulo Anterior] | <<v58-3-0,Topo>> | xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[Próximo Capítulo &#62;]