include::./index.adoc[]

[[v63-1-0]]
=== 2 João, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v63-1-1]]

^<<v63-1-1,1>>^ O ANCIÃO à senhora eleita, e a seus filhos, aos quais amo na verdade, e não somente eu, mas também todos os que têm conhecido a verdade,

[[v63-1-2]]

^<<v63-1-2,2>>^ Por amor da verdade que está em nós, e para sempre estará conosco:

[[v63-1-3]]

^<<v63-1-3,3>>^ Graça, misericórdia, paz, da parte de Deus Pai e da do Senhor Jesus Cristo, o Filho do Pai, seja convosco na verdade e caridade.

[[v63-1-4]]

^<<v63-1-4,4>>^ Muito me alegro por achar que alguns  de teus filhos andam na verdade, assim como temos recebido o mandamento do Pai.

[[v63-1-5]]

^<<v63-1-5,5>>^ E agora, senhora, rogo-te, não como escrevendo-te um novo mandamento, mas aquele mesmo que desde o princípio tivemos: que nos amemos uns aos outros.

[[v63-1-6]]

^<<v63-1-6,6>>^ E a caridade é esta: que andemos segundo os seus mandamentos. Este é o mandamento, como já  desde o princípio ouvistes: que andeis nele.

[[v63-1-7]]

^<<v63-1-7,7>>^ Porque já  muitos enganadores entraram no mundo, os quais não confessam que Jesus Cristo veio em carne. Este tal  é o enganador e o anticristo.

[[v63-1-8]]

^<<v63-1-8,8>>^ Olhai por vós mesmos, para que não percamos o que temos ganho, antes recebamos o inteiro galardão.

[[v63-1-9]]

^<<v63-1-9,9>>^ Todo aquele que prevarica, e não persevera na doutrina de Cristo, não tem a Deus: quem persevera na doutrina de Cristo, esse tem tanto ao Pai como ao Filho.

[[v63-1-10]]

^<<v63-1-10,10>>^ Se alguém vem ter convosco, e não traz esta doutrina, não o recebais em casa, nem tampouco o saudeis.

[[v63-1-11]]

^<<v63-1-11,11>>^ Porque quem o saúda tem parte nas suas más obras.

[[v63-1-12]]

^<<v63-1-12,12>>^ Tendo muito que escrever-vos, não quis fazê-lo com papel e tinta; mas espero ir ter convosco e falar de boca a boca, para que o nosso gozo seja cumprido.

[[v63-1-13]]

^<<v63-1-13,13>>^ Saúdam-te os filhos de tua irmã, a eleita. Amém.

'''

xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[&#60; Capítulo Anterior] | <<v63-1-0,Topo>> | xref:064-3-joao/064-3-joao-001.adoc#v64-1-0[Próximo Capítulo &#62;]