include::./index.adoc[]

[[v53-3-0]]
=== 2 Tessalonicenses, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v53-3-1]]

^<<v53-3-1,1>>^ NO demais, irmãos, rogai por nós, para que a palavra do Senhor tenha livre  curso e seja glorificada, como também o é entre vós;

[[v53-3-2]]

^<<v53-3-2,2>>^ E para que sejamos livres de homens dissolutos e maus; porque a fé não é de todos.

[[v53-3-3]]

^<<v53-3-3,3>>^ Mas fiel é o Senhor, que vos confortará, e guardará do maligno.

[[v53-3-4]]

^<<v53-3-4,4>>^ E confiamos de vós no Senhor que não só fazeis como fareis o que vos mandamos.

[[v53-3-5]]

^<<v53-3-5,5>>^ Ora o Senhor encaminhe os vossos corações na caridade de Deus, e na paciência de Cristo.

[[v53-3-6]]

^<<v53-3-6,6>>^ Mandamo-vos, porém, irmãos, em nome de nosso Senhor Jesus Cristo, que vos aparteis de todo o irmão que andar desordenadamente, e não segundo a tradição que de nós recebeu.

[[v53-3-7]]

^<<v53-3-7,7>>^ Porque vós mesmos sabeis como convém imitar-nos, pois que não nos houvemos desordenadamente entre vós,

[[v53-3-8]]

^<<v53-3-8,8>>^ Nem de graça comemos o pão de homem algum, mas com trabalho e fadiga, trabalhando noite e dia, para não sermos pesados a nenhum de vós.

[[v53-3-9]]

^<<v53-3-9,9>>^ Não porque não tivéssemos autoridade, mas para vos dar em nós mesmos exemplo, para nos imitardes.

[[v53-3-10]]

^<<v53-3-10,10>>^ Porque, quando ainda estávamos convosco, vos mandamos isto, que, se alguém não quiser trabalhar, não coma também.

[[v53-3-11]]

^<<v53-3-11,11>>^ Porquanto ouvimos que alguns entre vós andam desordenadamente, não trabalhando, antes fazendo coisas vãs.

[[v53-3-12]]

^<<v53-3-12,12>>^ A esses tais, porém mandamos, e exortamos por nosso Senhor Jesus Cristo, que, trabalhando com sossego, comam o seu próprio pão.

[[v53-3-13]]

^<<v53-3-13,13>>^ E vós, irmãos, não vos canseis de fazer bem.

[[v53-3-14]]

^<<v53-3-14,14>>^ Mas, se alguém não obedecer à nossa palavra por esta carta, notai o tal, e não vos mistureis com ele, para que se envergonhe.

[[v53-3-15]]

^<<v53-3-15,15>>^ Todavia não o  tenhais como inimigo, mas admoestai-o como irmão.

[[v53-3-16]]

^<<v53-3-16,16>>^ Ora o mesmo Senhor da paz vos dê sempre paz de toda a maneira. O Senhor seja com todos vós.

[[v53-3-17]]

^<<v53-3-17,17>>^ Saudação da minha própria mão, de mim, Paulo, que é o sinal em todas as epístolas: assim escrevo.

[[v53-3-18]]

^<<v53-3-18,18>>^ A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[Próximo Capítulo &#62;]