include::./index.adoc[]

[[v19-14-0]]
=== Salmos, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-14-1]]

^<<v19-14-1,1>>^ DISSE o néscio no seu coração: Não há  Deus. Têm-se corrompido, fazem-se abomináveis em suas obras, não há  ninguém que faça o bem.

[[v19-14-2]]

^<<v19-14-2,2>>^ O Senhor olhou desde os céus para os filhos dos homens, para ver se havia algum  que tivesse entendimento e  buscasse a Deus.

[[v19-14-3]]

^<<v19-14-3,3>>^ Desviaram-se todos e juntamente se fizeram imundos: não há  quem faça o bem, não há  sequer um.

[[v19-14-4]]

^<<v19-14-4,4>>^ Não terão conhecimento os obreiros da iniquidade, que comem o meu povo, como  se comessem pão? Eles não invocam ao Senhor.

[[v19-14-5]]

^<<v19-14-5,5>>^ Ali se acharam em grande pavor, porque Deus está  na geração dos justos.

[[v19-14-6]]

^<<v19-14-6,6>>^ Vós envergonhais o conselho dos pobres, porquanto o Senhor é  o seu refúgio.

[[v19-14-7]]

^<<v19-14-7,7>>^ Oh! se de Sião tivera já vindo  a redenção de Israel! quando o Senhor fizer voltar os cativos do seu povo, se regozijará Jacó e se  alegrará Israel.

'''

xref:019-salmos/019-salmos-013.adoc#v19-13-0[&#60; Capítulo Anterior] | <<v19-14-0,Topo>> | xref:019-salmos/019-salmos-015.adoc#v19-15-0[Próximo Capítulo &#62;]