include::./index.adoc[]

[[v19-112-0]]
=== Salmos, 112
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-112-1]]

^<<v19-112-1,1>>^ LOUVAI ao Senhor. Bem-aventurado o homem que teme ao Senhor, que  em seus mandamentos tem grande prazer.

[[v19-112-2]]

^<<v19-112-2,2>>^ A sua descendência será poderosa na terra: a geração dos justos será abençoada.

[[v19-112-3]]

^<<v19-112-3,3>>^ Fazenda e riquezas haverá  na sua casa, e a sua justiça permanece para sempre.

[[v19-112-4]]

^<<v19-112-4,4>>^ Aos justos nasce luz nas trevas: ele é  piedoso, misericordioso e justo.

[[v19-112-5]]

^<<v19-112-5,5>>^ Bem irá ao homem que se compadece, e empresta: disporá as suas cousas com juízo.

[[v19-112-6]]

^<<v19-112-6,6>>^ Na verdade que nunca será abalado: o justo ficará em memória eterna.

[[v19-112-7]]

^<<v19-112-7,7>>^ Não temerá maus rumores: o seu coração está firme, confiando no Senhor.

[[v19-112-8]]

^<<v19-112-8,8>>^ O seu coração, bem  firmado, não temerá, até que ele veja cumprido o seu desejo sobre os seus inimigos.

[[v19-112-9]]

^<<v19-112-9,9>>^ É liberal, dá aos necessitados: a sua justiça permanece para sempre, e a sua força se exaltará em glória.

[[v19-112-10]]

^<<v19-112-10,10>>^ O ímpio verá isto, e se enraivecerá; rangerá os dentes, e se consumirá; o desejo dos ímpios perecerá.

'''

xref:019-salmos/019-salmos-111.adoc#v19-111-0[&#60; Capítulo Anterior] | <<v19-112-0,Topo>> | xref:019-salmos/019-salmos-113.adoc#v19-113-0[Próximo Capítulo &#62;]