include::./index.adoc[]

[[v19-109-0]]
=== Salmos, 109
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-109-1]]

^<<v19-109-1,1>>^ Ó DEUS do meu louvor, não te cales;

[[v19-109-2]]

^<<v19-109-2,2>>^ Pois a boca do ímpio e a boca fraudulenta estão abertas contra mim: têm falado contra mim com uma língua mentirosa.

[[v19-109-3]]

^<<v19-109-3,3>>^ Eles me cercaram com palavras odiosas, e pelejaram contra mim sem causa.

[[v19-109-4]]

^<<v19-109-4,4>>^ Em  paga do meu amor são meus adversários: mas eu faço  oração.

[[v19-109-5]]

^<<v19-109-5,5>>^ Deram-me mal pelo bem, e ódio pelo meu amor.

[[v19-109-6]]

^<<v19-109-6,6>>^ Põe acima dele um ímpio, e Satanás esteja à sua direita.

[[v19-109-7]]

^<<v19-109-7,7>>^ Quando for julgado, saia condenado; e em pecado se lhe torne a sua oração.

[[v19-109-8]]

^<<v19-109-8,8>>^ Sejam poucos os seus dias, e  outro tome o seu ofício.

[[v19-109-9]]

^<<v19-109-9,9>>^ Sejam órfãos os seus filhos, e viúva sua mulher.

[[v19-109-10]]

^<<v19-109-10,10>>^ Sejam vagabundos e mendigos os seus filhos, e busquem o seu pão longe das suas habitações assoladas.

[[v19-109-11]]

^<<v19-109-11,11>>^ Lance o credor mão de tudo quanto tenha, e despojem-no os estranhos do seu trabalho.

[[v19-109-12]]

^<<v19-109-12,12>>^ Não haja ninguém que se compadeça dele, nem haja quem favoreça os seus órfãos.

[[v19-109-13]]

^<<v19-109-13,13>>^ Desapareça a sua posteridade, o seu nome seja apagado na seguinte geração.

[[v19-109-14]]

^<<v19-109-14,14>>^ Esteja na memória do Senhor a iniquidade de seus pais, e não se apague o pecado de sua mãe.

[[v19-109-15]]

^<<v19-109-15,15>>^ Antes estejam sempre perante o Senhor, para que faça desaparecer a sua memória da terra.

[[v19-109-16]]

^<<v19-109-16,16>>^ Porquanto se não lembrou de usar de misericórdia; antes perseguiu o varão aflito e o necessitado, como também o quebrantado de coração, para o matar.

[[v19-109-17]]

^<<v19-109-17,17>>^ Visto que amou a maldição, ela lhe sobrevenha, e pois que não desejou a bênção, ela se afaste dele.

[[v19-109-18]]

^<<v19-109-18,18>>^ Assim como se vestiu de maldição, como dum vestido, assim penetre ela nas suas entranhas, como água, e em seus ossos como azeite.

[[v19-109-19]]

^<<v19-109-19,19>>^ Seja para ele como o vestido que  o cobre, e como cinto que o cinja sempre.

[[v19-109-20]]

^<<v19-109-20,20>>^ Seja  este da parte do Senhor o galardão dos meus contrários, e dos que falam mal contra a minha alma.

[[v19-109-21]]

^<<v19-109-21,21>>^ Mas tu, ó Deus-Senhor, sê comigo por amor do teu nome; porque a tua misericórdia é  boa, livra-me.

[[v19-109-22]]

^<<v19-109-22,22>>^ Porque estou  aflito e necessitado, e dentro de mim está aflito o meu coração.

[[v19-109-23]]

^<<v19-109-23,23>>^ Eis que me vou como a sombra que declina; sou sacudido como o gafanhoto.

[[v19-109-24]]

^<<v19-109-24,24>>^ De jejuar estão enfraquecidos os meus joelhos, e a minha carne emagrece.

[[v19-109-25]]

^<<v19-109-25,25>>^ E ainda lhes sirvo de opróbrio; quando  me contemplam, movem as cabeças.

[[v19-109-26]]

^<<v19-109-26,26>>^ Ajuda-me, Senhor Deus meu: salva-me segundo a tua misericórdia.

[[v19-109-27]]

^<<v19-109-27,27>>^ Para que saibam que nisto está a tua mão, e que  tu, Senhor, o fizeste.

[[v19-109-28]]

^<<v19-109-28,28>>^ Amaldiçoem eles, mas abençoa tu: levantem-se, mas fiquem confundidos; e alegre-se o teu servo.

[[v19-109-29]]

^<<v19-109-29,29>>^ Vistam-se os meus adversários de vergonha, e cubra-os a sua própria confusão como uma  capa.

[[v19-109-30]]

^<<v19-109-30,30>>^ Louvarei grandemente ao Senhor com a minha boca: louvá-lo-ei entre a multidão.

[[v19-109-31]]

^<<v19-109-31,31>>^ Pois se porá à direita do pobre, para o  livrar dos que condenam a sua alma.

'''

xref:019-salmos/019-salmos-108.adoc#v19-108-0[&#60; Capítulo Anterior] | <<v19-109-0,Topo>> | xref:019-salmos/019-salmos-110.adoc#v19-110-0[Próximo Capítulo &#62;]