include::./index.adoc[]

[[v19-21-0]]
=== Salmos, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-21-1]]

^<<v19-21-1,1>>^ O REI se alegra em tua força, Senhor; e na tua salvação grandemente se regozija.

[[v19-21-2]]

^<<v19-21-2,2>>^ Cumpriste-lhe o desejo do seu coração, e não desatendeste as súplicas dos seus lábios. (Selá.)

[[v19-21-3]]

^<<v19-21-3,3>>^ Pois o provês das bênçãos de bondade; pões na sua cabeça uma  coroa de ouro fino.

[[v19-21-4]]

^<<v19-21-4,4>>^ Vida te pediu, e lha  deste, mesmo  longura de dias para sempre e eternamente.

[[v19-21-5]]

^<<v19-21-5,5>>^ Grande é  a sua glória pela tua salvação; de honra e de majestade o revestiste.

[[v19-21-6]]

^<<v19-21-6,6>>^ Pois o abençoaste para sempre: tu o enches de gozo com a tua face.

[[v19-21-7]]

^<<v19-21-7,7>>^ Porque o rei confia no Senhor, e pela misericórdia do Altíssimo nunca vacilará.

[[v19-21-8]]

^<<v19-21-8,8>>^ A tua mão alcançará todos os teus inimigos, a tua mão  direita alcançará aqueles que te aborrecem.

[[v19-21-9]]

^<<v19-21-9,9>>^ Tu os farás como um  forno aceso quando te manifestares; o Senhor os devorará na sua indignação, e o fogo os consumirá.

[[v19-21-10]]

^<<v19-21-10,10>>^ Seu fruto destruirás da terra, e a sua descendência dentre os filhos dos homens.

[[v19-21-11]]

^<<v19-21-11,11>>^ Porque intentaram o mal contra ti; maquinaram um  ardil, mas  não prevalecerão.

[[v19-21-12]]

^<<v19-21-12,12>>^ Portanto tu lhes farás voltar as costas; e com tuas frechas postas nas  cordas lhes apontarás ao rosto.

[[v19-21-13]]

^<<v19-21-13,13>>^ Exalta-te, Senhor, na tua força; então  cantaremos e louvaremos o teu poder.

'''

xref:019-salmos/019-salmos-020.adoc#v19-20-0[&#60; Capítulo Anterior] | <<v19-21-0,Topo>> | xref:019-salmos/019-salmos-022.adoc#v19-22-0[Próximo Capítulo &#62;]