include::./index.adoc[]

[[v19-25-0]]
=== Salmos, 25
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-25-1]]

^<<v19-25-1,1>>^ A TI, Senhor, levanto a minha alma.

[[v19-25-2]]

^<<v19-25-2,2>>^ Deus meu, em ti confio, não me deixes confundido, nem que os meus inimigos triunfem sobre mim.

[[v19-25-3]]

^<<v19-25-3,3>>^ Na verdade, não serão confundidos os que esperam em ti: confundidos serão os que transgridem sem causa.

[[v19-25-4]]

^<<v19-25-4,4>>^ Faze-me saber os teus caminhos, Senhor; ensina-me as tuas veredas.

[[v19-25-5]]

^<<v19-25-5,5>>^ Guia-me na tua verdade, e ensina-me, pois tu és  o Deus da minha salvação; por ti estou esperando todo o dia.

[[v19-25-6]]

^<<v19-25-6,6>>^ Lembra-te, Senhor, das tuas misericórdias e das tuas benignidades, porque são  desde a eternidade.

[[v19-25-7]]

^<<v19-25-7,7>>^ Não te lembres dos pecados da minha mocidade, nem das minhas transgressões: mas , segundo a tua misericórdia, lembra-te de mim, por tua bondade, Senhor.

[[v19-25-8]]

^<<v19-25-8,8>>^ Bom e reto é  o Senhor; pelo que ensinará o caminho aos pecadores.

[[v19-25-9]]

^<<v19-25-9,9>>^ Guiará os mansos retamente: e aos mansos ensinará o seu caminho.

[[v19-25-10]]

^<<v19-25-10,10>>^ Todas as veredas do Senhor são  misericórdia e verdade para aqueles que guardam o seu concerto e os seus testemunhos.

[[v19-25-11]]

^<<v19-25-11,11>>^ Por amor do teu nome Senhor, perdoa a minha iniquidade, pois é  grande.

[[v19-25-12]]

^<<v19-25-12,12>>^ Qual é  o homem que teme ao Senhor? ele o ensinará no caminho que  deve escolher.

[[v19-25-13]]

^<<v19-25-13,13>>^ A sua alma pousará no bem, e a sua descendência herdará a terra.

[[v19-25-14]]

^<<v19-25-14,14>>^ O segredo do Senhor é  para os que o temem; e ele lhes fará saber o seu concerto.

[[v19-25-15]]

^<<v19-25-15,15>>^ Os meus olhos estão  continuamente no Senhor, pois ele tirará os meus pés da rede.

[[v19-25-16]]

^<<v19-25-16,16>>^ Olha para mim, e tem piedade de mim, porque estou  solitário e aflito.

[[v19-25-17]]

^<<v19-25-17,17>>^ As ânsias do meu coração se têm multiplicado; tira-me dos meus apertos.

[[v19-25-18]]

^<<v19-25-18,18>>^ Olha para a minha aflição e para a minha dor, e perdoa todos os meus pecados.

[[v19-25-19]]

^<<v19-25-19,19>>^ Olha para os meus inimigos, pois se vão multiplicando e me aborrecem com ódio cruel.

[[v19-25-20]]

^<<v19-25-20,20>>^ Guarda a minha alma, e livra-me; não me deixes confundido, porquanto confio em ti.

[[v19-25-21]]

^<<v19-25-21,21>>^ Guardem-me a sinceridade e a retidão, porquanto espero em ti.

[[v19-25-22]]

^<<v19-25-22,22>>^ Redime, ó Deus, a Israel de todas as suas angústias.

'''

xref:019-salmos/019-salmos-024.adoc#v19-24-0[&#60; Capítulo Anterior] | <<v19-25-0,Topo>> | xref:019-salmos/019-salmos-026.adoc#v19-26-0[Próximo Capítulo &#62;]