include::./index.adoc[]

[[v19-47-0]]
=== Salmos, 47
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-47-1]]

^<<v19-47-1,1>>^ APLAUDI com as mãos, todos os povos; cantai a Deus com voz de triunfo.

[[v19-47-2]]

^<<v19-47-2,2>>^ Porque o Senhor Altíssimo é  tremendo, e Rei grande sobre toda a terra.

[[v19-47-3]]

^<<v19-47-3,3>>^ Ele nos submeterá os povos e porá as nações debaixo dos nossos pés.

[[v19-47-4]]

^<<v19-47-4,4>>^ Escolherá para nós a nossa herança, a glória de Jacó, a quem amou. (Selá.)

[[v19-47-5]]

^<<v19-47-5,5>>^ Deus subiu  com júbilo, o Senhor subiu  ao som da trombeta.

[[v19-47-6]]

^<<v19-47-6,6>>^ Cantai louvores a Deus, cantai louvores; cantai louvores ao nosso Rei, cantai louvores.

[[v19-47-7]]

^<<v19-47-7,7>>^ Pois Deus é  o Rei de toda a terra, cantai louvores com inteligência.

[[v19-47-8]]

^<<v19-47-8,8>>^ Deus reina sobre as nações: Deus se assenta sobre o trono da sua santidade.

[[v19-47-9]]

^<<v19-47-9,9>>^ Os príncipes dos povos se congregam para serem o povo do Deus de Abraão; porque os escudos da terra são  de Deus: ele está muito elevado!

'''

xref:019-salmos/019-salmos-046.adoc#v19-46-0[&#60; Capítulo Anterior] | <<v19-47-0,Topo>> | xref:019-salmos/019-salmos-048.adoc#v19-48-0[Próximo Capítulo &#62;]