include::./index.adoc[]

[[v19-36-0]]
=== Salmos, 36
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-36-1]]

^<<v19-36-1,1>>^ A PREVARICAÇÃO do ímpio diz no íntimo do seu coração: Não há  temor de Deus perante os seus olhos.

[[v19-36-2]]

^<<v19-36-2,2>>^ Porque em seus olhos se lisonjeia, até que a sua iniquidade se mostre detestável.

[[v19-36-3]]

^<<v19-36-3,3>>^ As palavras da sua boca são  malícia e engano: deixou de entender e  de fazer o bem.

[[v19-36-4]]

^<<v19-36-4,4>>^ Maquina o mal na sua cama; põe-se em caminho que  não é  bom: não aborrece o mal.

[[v19-36-5]]

^<<v19-36-5,5>>^ A tua misericórdia, Senhor, está  nos céus, e a tua fidelidade chega  até às mais excelsas  nuvens.

[[v19-36-6]]

^<<v19-36-6,6>>^ A tua justiça é  como as grandes montanhas; os teus juízos são um  grande abismo; Senhor, tu conservas os homens e os animais.

[[v19-36-7]]

^<<v19-36-7,7>>^ Quão preciosa, é , ó Deus, a tua benignidade, e por isso os filhos dos homens se abrigam à sombra das tuas asas.

[[v19-36-8]]

^<<v19-36-8,8>>^ Eles se fartarão da gordura da tua casa, e os farás beber da corrente das tuas delícias;

[[v19-36-9]]

^<<v19-36-9,9>>^ Porque em ti está  o manancial da vida; na tua luz veremos a luz.

[[v19-36-10]]

^<<v19-36-10,10>>^ Estende a tua benignidade sobre os que te conhecem, e a tua justiça sobre os retos de coração.

[[v19-36-11]]

^<<v19-36-11,11>>^ Não venha sobre mim o pé dos soberbos, e não me mova a mão dos ímpios.

[[v19-36-12]]

^<<v19-36-12,12>>^ Ali caem os obreiros da iniquidade; cairão, e não se poderão levantar.

'''

xref:019-salmos/019-salmos-035.adoc#v19-35-0[&#60; Capítulo Anterior] | <<v19-36-0,Topo>> | xref:019-salmos/019-salmos-037.adoc#v19-37-0[Próximo Capítulo &#62;]