include::./index.adoc[]

[[v19-26-0]]
=== Salmos, 26
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-26-1]]

^<<v19-26-1,1>>^ JULGA-ME, Senhor, pois tenho andado em minha sinceridade; tenho confiado também no Senhor; não vacilarei.

[[v19-26-2]]

^<<v19-26-2,2>>^ Examina-me, Senhor, e prova-me: esquadrinha os meus rins e o meu coração.

[[v19-26-3]]

^<<v19-26-3,3>>^ Porque a tua benignidade está  diante dos meus olhos; e tenho andado na tua verdade.

[[v19-26-4]]

^<<v19-26-4,4>>^ Não me tenho assentado com homens vãos, nem converso com os homens  dissimulados.

[[v19-26-5]]

^<<v19-26-5,5>>^ Tenho aborrecido a congregação de malfeitores; não me ajunto com os ímpios.

[[v19-26-6]]

^<<v19-26-6,6>>^ Lavo as minhas mãos na inocência; e assim andarei, Senhor, ao redor do teu altar,

[[v19-26-7]]

^<<v19-26-7,7>>^ Para publicar com voz de louvor, e contar todas as tuas maravilhas.

[[v19-26-8]]

^<<v19-26-8,8>>^ Senhor, eu tenho amado a habitação da tua casa e o lugar onde permanece a tua glória.

[[v19-26-9]]

^<<v19-26-9,9>>^ Não colhas a minha alma com a dos pecadores, nem a minha vida com a dos homens sanguinolentos,

[[v19-26-10]]

^<<v19-26-10,10>>^ Em cujas mãos há  malefício, e cuja mão  direita está  cheia de subornos.

[[v19-26-11]]

^<<v19-26-11,11>>^ Mas eu ando na minha sinceridade; livra-me e tem piedade de mim.

[[v19-26-12]]

^<<v19-26-12,12>>^ O meu pé está posto em caminho plano; nas congregações louvarei ao Senhor.

'''

xref:019-salmos/019-salmos-025.adoc#v19-25-0[&#60; Capítulo Anterior] | <<v19-26-0,Topo>> | xref:019-salmos/019-salmos-027.adoc#v19-27-0[Próximo Capítulo &#62;]