include::./index.adoc[]

[[v19-78-0]]
=== Salmos, 78
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-78-1]]

^<<v19-78-1,1>>^ ESCUTAI a minha lei, povo meu: inclinai os vossos ouvidos às palavras da minha boca.

[[v19-78-2]]

^<<v19-78-2,2>>^ Abrirei a minha boca numa  parábola: proporei enigmas da antiguidade.

[[v19-78-3]]

^<<v19-78-3,3>>^ Os quais temos ouvido e sabido, e nossos pais no-los têm contado.

[[v19-78-4]]

^<<v19-78-4,4>>^ Não os encobriremos aos seus filhos, mostrando à geração futura os louvores do Senhor, assim como a sua força e as maravilhas que fez.

[[v19-78-5]]

^<<v19-78-5,5>>^ Porque ele estabeleceu um  testemunho em Jacó, e pôs uma  lei em Israel, e ordenou aos nossos pais que a fizessem conhecer a seus filhos;

[[v19-78-6]]

^<<v19-78-6,6>>^ Para que a geração vindoura a  soubesse; os filhos que  nascessem se levantassem e a  contassem a seus filhos;

[[v19-78-7]]

^<<v19-78-7,7>>^ Para que pusessem em Deus a sua esperança, e se não esquecessem das obras de Deus, mas guardassem os seus mandamentos.

[[v19-78-8]]

^<<v19-78-8,8>>^ E não fossem como seus pais, geração contumaz e rebelde, geração que  não regeu o seu coração, e cujo espírito não foi fiel para com Deus.

[[v19-78-9]]

^<<v19-78-9,9>>^ Os filhos de Efraim, armados e trazendo arcos, retrocederam no dia da peleja.

[[v19-78-10]]

^<<v19-78-10,10>>^ Não guardaram o concerto de Deus, e recusaram andar na sua lei.

[[v19-78-11]]

^<<v19-78-11,11>>^ E esqueceram-se das suas obras e das maravilhas que lhes fizera ver.

[[v19-78-12]]

^<<v19-78-12,12>>^ Maravilhas que ele fez à vista de seus pais na terra do Egito, no  campo de Zoã.

[[v19-78-13]]

^<<v19-78-13,13>>^ Dividiu o mar, e os fez passar por ele; fez com que as águas parassem como num montão.

[[v19-78-14]]

^<<v19-78-14,14>>^ De dia os guiou com uma nuvem, e toda a noite com um clarão de fogo.

[[v19-78-15]]

^<<v19-78-15,15>>^ Fendeu as penhas no deserto; e deu- lhes  de beber como de grandes abismos.

[[v19-78-16]]

^<<v19-78-16,16>>^ Fez sair fontes da rocha, e fez correr as águas como rios.

[[v19-78-17]]

^<<v19-78-17,17>>^ E ainda  prosseguiram em pecar contra ele, provocando ao Altíssimo na solidão.

[[v19-78-18]]

^<<v19-78-18,18>>^ E tentaram a Deus nos seus corações, pedindo carne para satisfazerem o seu apetite.

[[v19-78-19]]

^<<v19-78-19,19>>^ E falaram contra Deus, e disseram: Poderá Deus porventura preparar- nos  uma mesa no deserto?

[[v19-78-20]]

^<<v19-78-20,20>>^ Eis que feriu a penha, e águas correram dela ; rebentaram ribeiros em abundância: poderá também dar- nos  pão, ou preparar carne para o seu povo?

[[v19-78-21]]

^<<v19-78-21,21>>^ Pelo que o Senhor os  ouviu, e se indignou: e acendeu um  fogo contra Jacó, e furor também subiu contra Israel;

[[v19-78-22]]

^<<v19-78-22,22>>^ Porquanto não creram em Deus, nem confiaram na sua salvação,

[[v19-78-23]]

^<<v19-78-23,23>>^ Posto que tivesse mandado às altas nuvens, e tivesse aberto as portas dos céus.

[[v19-78-24]]

^<<v19-78-24,24>>^ E fizesse chover sobre eles o maná para comerem, e lhes tivesse dado do trigo do céu.

[[v19-78-25]]

^<<v19-78-25,25>>^ Cada um comeu o pão dos poderosos; ele lhes mandou comida com abundância.

[[v19-78-26]]

^<<v19-78-26,26>>^ Fez soprar o vento do oriente nos céus, e trouxe o sul com a sua força.

[[v19-78-27]]

^<<v19-78-27,27>>^ E choveu sobre eles carne como pó, e aves de asas como a areia do mar.

[[v19-78-28]]

^<<v19-78-28,28>>^ E as  fez cair no meio do seu arraial, ao redor de suas habitações.

[[v19-78-29]]

^<<v19-78-29,29>>^ Então comeram e se fartaram bem; pois lhes satisfez o desejo.

[[v19-78-30]]

^<<v19-78-30,30>>^ Não refrearam o seu apetite. Ainda lhes estava  a comida na boca,

[[v19-78-31]]

^<<v19-78-31,31>>^ Quando a ira de Deus desceu sobre eles, e matou os mais fortes deles, e feriu os escolhidos de Israel.

[[v19-78-32]]

^<<v19-78-32,32>>^ Com tudo isto ainda pecaram, e não deram crédito às suas maravilhas.

[[v19-78-33]]

^<<v19-78-33,33>>^ Pelo que consumiu os seus dias na vaidade e os seus anos na angústia.

[[v19-78-34]]

^<<v19-78-34,34>>^ Pondo-os ele à morte, então o procuravam; e voltavam, e de madrugada buscavam a Deus.

[[v19-78-35]]

^<<v19-78-35,35>>^ E lembravam-se de que Deus era a sua rocha, e o Deus Altíssimo o seu Redentor.

[[v19-78-36]]

^<<v19-78-36,36>>^ Todavia lisonjeavam-no com a boca, e com a língua lhe mentiam.

[[v19-78-37]]

^<<v19-78-37,37>>^ Porque o seu coração não era  reto para com ele nem foram fiéis ao seu concerto.

[[v19-78-38]]

^<<v19-78-38,38>>^ Mas ele, que é misericordioso, perdoou a sua  iniquidade, e não os  destruiu; antes muitas vezes desviou deles  a sua cólera, e não deixou despertar toda a sua ira.

[[v19-78-39]]

^<<v19-78-39,39>>^ Porque se lembrou de que eram  carne, um vento que passa e não volta.

[[v19-78-40]]

^<<v19-78-40,40>>^ Quantas vezes o provocaram no deserto, e o ofenderam na solidão!

[[v19-78-41]]

^<<v19-78-41,41>>^ Voltaram atrás, e tentaram a Deus; e duvidaram do Santo de Israel.

[[v19-78-42]]

^<<v19-78-42,42>>^ Não se lembraram do poder  da sua mão, nem  do dia em que os livrou do adversário:

[[v19-78-43]]

^<<v19-78-43,43>>^ Como operou os seus sinais no Egito, e as suas maravilhas no campo de Zoã;

[[v19-78-44]]

^<<v19-78-44,44>>^ E converteu em sangue os seus rios e as suas correntes, para que não pudessem beber.

[[v19-78-45]]

^<<v19-78-45,45>>^ E lhes mandou enxames de moscas que os consumiram, e rãs que os destruíram.

[[v19-78-46]]

^<<v19-78-46,46>>^ Deu também ao pulgão a sua novidade, e o seu trabalho aos gafanhotos.

[[v19-78-47]]

^<<v19-78-47,47>>^ Destruiu as suas vinhas com saraiva, e os seus sicômoros com pedrisco.

[[v19-78-48]]

^<<v19-78-48,48>>^ Também entregou o seu gado à saraiva, e aos coriscos os seus rebanhos.

[[v19-78-49]]

^<<v19-78-49,49>>^ E atirou para o meio deles, quais mensageiros de males, o ardor da sua ira, furor, indignação, e angústia.

[[v19-78-50]]

^<<v19-78-50,50>>^ Abriu caminho à sua ira; não poupou a alma deles à morte, nem a vida deles à pestilência.

[[v19-78-51]]

^<<v19-78-51,51>>^ E feriu todo o primogênito no Egito, primícias da sua  força nas tendas de Cão.

[[v19-78-52]]

^<<v19-78-52,52>>^ Mas fez com  que o seu povo saísse como ovelhas, e os guiou pelo deserto como a um  rebanho.

[[v19-78-53]]

^<<v19-78-53,53>>^ E os guiou com segurança, e não temeram; mas o mar cobriu os seus inimigos.

[[v19-78-54]]

^<<v19-78-54,54>>^ E conduziu-os até ao limite do seu santuário, até este monte que a sua destra adquiriu.

[[v19-78-55]]

^<<v19-78-55,55>>^ E expulsou as nações de diante deles, e, dividindo suas terras, lhas deu por herança, e fez habitar em suas tendas as tribos de Israel.

[[v19-78-56]]

^<<v19-78-56,56>>^ Contudo tentaram e provocaram o Deus Altíssimo, e não guardaram os seus testemunhos.

[[v19-78-57]]

^<<v19-78-57,57>>^ Mas tornaram atrás, e portaram-se aleivosamente como seus pais: viraram-se como um  arco traiçoeiro.

[[v19-78-58]]

^<<v19-78-58,58>>^ Pois lhe provocaram a ira com os seus altos, e despertaram-lhe o zelo com as suas imagens de escultura.

[[v19-78-59]]

^<<v19-78-59,59>>^ Deus ouviu isto  e se indignou; e sobremodo aborreceu a Israel.

[[v19-78-60]]

^<<v19-78-60,60>>^ Pelo que desamparou o tabernáculo em Silo, a tenda que  estabelecera como sua morada entre os homens.

[[v19-78-61]]

^<<v19-78-61,61>>^ E deu a sua força ao cativeiro; e a sua glória à mão do inimigo.

[[v19-78-62]]

^<<v19-78-62,62>>^ E entregou o seu povo à espada; e encolerizou-se contra a sua herança.

[[v19-78-63]]

^<<v19-78-63,63>>^ Aos seus mancebos consumiu-os o fogo, e as suas donzelas não tiveram festa nupcial.

[[v19-78-64]]

^<<v19-78-64,64>>^ Os seus sacerdotes caíram à espada, e suas viúvas não se lamentaram.

[[v19-78-65]]

^<<v19-78-65,65>>^ Então o Senhor despertou como dum sono, como um valente que o vinho excitasse.

[[v19-78-66]]

^<<v19-78-66,66>>^ E feriu os seus adversários, que fugiram, e pô-los em perpétuo desprezo.

[[v19-78-67]]

^<<v19-78-67,67>>^ Além disto, rejeitou a tenda de José, e não elegeu a tribo de Efraim.

[[v19-78-68]]

^<<v19-78-68,68>>^ Antes elegeu a tribo de Judá: o monte de Sião, que ele amava.

[[v19-78-69]]

^<<v19-78-69,69>>^ E edificou o seu santuário como aos lugares elevados, como a terra que fundou para sempre.

[[v19-78-70]]

^<<v19-78-70,70>>^ Também elegeu a Davi, seu servo, e o tirou dos apriscos das ovelhas.

[[v19-78-71]]

^<<v19-78-71,71>>^ De após as ovelhas pejadas o trouxe, para apascentar a Jacó, seu povo, e a Israel, sua herança.

[[v19-78-72]]

^<<v19-78-72,72>>^ Assim os apascentou, segundo a integridade do seu coração, e os guiou com a perícia de suas mãos.

'''

xref:019-salmos/019-salmos-077.adoc#v19-77-0[&#60; Capítulo Anterior] | <<v19-78-0,Topo>> | xref:019-salmos/019-salmos-079.adoc#v19-79-0[Próximo Capítulo &#62;]