include::./index.adoc[]

[[v19-145-0]]
=== Salmos, 145
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-145-1]]

^<<v19-145-1,1>>^ EU te exaltarei, ó Deus, rei meu, e bendirei o teu nome pelos séculos dos séculos.

[[v19-145-2]]

^<<v19-145-2,2>>^ Cada dia te bendirei, e louvarei o teu nome pelos séculos dos séculos.

[[v19-145-3]]

^<<v19-145-3,3>>^ Grande é  o Senhor, e muito digno de louvor, e a sua grandeza inescrutável.

[[v19-145-4]]

^<<v19-145-4,4>>^ Uma geração louvará as tuas obras à outra geração, e anunciará as tuas proezas.

[[v19-145-5]]

^<<v19-145-5,5>>^ Falarei da magnificência gloriosa da tua majestade e das tuas obras maravilhosas.

[[v19-145-6]]

^<<v19-145-6,6>>^ E se falará da força dos teus feitos terríveis; e contarei a tua grandeza.

[[v19-145-7]]

^<<v19-145-7,7>>^ Publicarão abundantemente a memória da tua grande bondade, e cantarão a tua justiça.

[[v19-145-8]]

^<<v19-145-8,8>>^ Piedoso e benigno é o Senhor, sofredor e de grande misericórdia.

[[v19-145-9]]

^<<v19-145-9,9>>^ O Senhor é  bom para todos, e as suas misericórdias são  sobre todas as suas obras.

[[v19-145-10]]

^<<v19-145-10,10>>^ Todas as tuas obras te louvarão, ó Senhor, e os teus santos te bendirão.

[[v19-145-11]]

^<<v19-145-11,11>>^ Falarão da glória do teu reino, e relatarão o teu poder;

[[v19-145-12]]

^<<v19-145-12,12>>^ Para que façam saber aos filhos dos homens as tuas proezas e a glória da magnificência do teu reino.

[[v19-145-13]]

^<<v19-145-13,13>>^ O teu reino é um  reino eterno; o teu domínio estende-se a todas as gerações.

[[v19-145-14]]

^<<v19-145-14,14>>^ O Senhor sustenta a todos os que caem, e levanta a todos os abatidos.

[[v19-145-15]]

^<<v19-145-15,15>>^ Os olhos de todos esperam em ti, e tu lhes dás o seu mantimento a seu tempo.

[[v19-145-16]]

^<<v19-145-16,16>>^ Abres a tua mão, e satisfazes os desejos de todos os viventes.

[[v19-145-17]]

^<<v19-145-17,17>>^ Justo é  o Senhor em todos os seus caminhos, e santo em todas as suas obras.

[[v19-145-18]]

^<<v19-145-18,18>>^ Perto está  o Senhor de todos os que o invocam, de todos os que o invocam em verdade.

[[v19-145-19]]

^<<v19-145-19,19>>^ Ele cumprirá o desejo dos que o temem; ouvirá o seu clamor, e os salvará.

[[v19-145-20]]

^<<v19-145-20,20>>^ O Senhor guarda a todos os que o amam; mas todos os ímpios serão destruídos.

[[v19-145-21]]

^<<v19-145-21,21>>^ A minha boca entoará o louvor do Senhor, e toda a carne louvará o seu santo nome para todo o sempre.

'''

xref:019-salmos/019-salmos-144.adoc#v19-144-0[&#60; Capítulo Anterior] | <<v19-145-0,Topo>> | xref:019-salmos/019-salmos-146.adoc#v19-146-0[Próximo Capítulo &#62;]