include::./index.adoc[]

[[v19-108-0]]
=== Salmos, 108
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-108-1]]

^<<v19-108-1,1>>^ PREPARADO está o meu coração, ó Deus; cantarei e salmodiarei com toda a minha alma.

[[v19-108-2]]

^<<v19-108-2,2>>^ Despertai, saltério e harpa; eu despertarei ao romper da alva.

[[v19-108-3]]

^<<v19-108-3,3>>^ Louvar-te-ei entre os povos, Senhor, e a ti cantarei salmos entre as nações.

[[v19-108-4]]

^<<v19-108-4,4>>^ Porque a tua benignidade se eleva acima dos céus, e a tua verdade ultrapassa as mais altas nuvens.

[[v19-108-5]]

^<<v19-108-5,5>>^ Exalta-te sobre os céus, ó Deus, e a tua glória sobre toda a terra,

[[v19-108-6]]

^<<v19-108-6,6>>^ Para que sejam livres os teus amados: salva- nos  com a tua destra, e ouve-nos.

[[v19-108-7]]

^<<v19-108-7,7>>^ Deus falou no seu santuário: eu me regozijarei; repartirei a Siquém, e medirei o vale de Sucote.

[[v19-108-8]]

^<<v19-108-8,8>>^ Meu é Galaade, meu é Manassés; Efraim é  a força da minha cabeça, Judá o meu legislador.

[[v19-108-9]]

^<<v19-108-9,9>>^ Moabe a minha bacia de lavar: sobre Edom lançarei o meu sapato, sobre a Palestina jubilarei.

[[v19-108-10]]

^<<v19-108-10,10>>^ Quem me levará à cidade forte? Quem me guiará até Edom?

[[v19-108-11]]

^<<v19-108-11,11>>^ Porventura  não serás tu , ó Deus, que  nos rejeitaste? E não sairás, ó Deus, como os nossos exércitos?

[[v19-108-12]]

^<<v19-108-12,12>>^ Dá-nos auxílio para sairmos da angústia, porque vão é  o socorro da parte  do homem.

[[v19-108-13]]

^<<v19-108-13,13>>^ Em Deus faremos proezas, pois ele calcará aos pés os nossos inimigos.

'''

xref:019-salmos/019-salmos-107.adoc#v19-107-0[&#60; Capítulo Anterior] | <<v19-108-0,Topo>> | xref:019-salmos/019-salmos-109.adoc#v19-109-0[Próximo Capítulo &#62;]