include::./index.adoc[]

[[v19-55-0]]
=== Salmos, 55
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-55-1]]

^<<v19-55-1,1>>^ INCLINA, ó Deus, os teus  ouvidos à minha oração, e não te escondas da minha súplica.

[[v19-55-2]]

^<<v19-55-2,2>>^ Atende-me, e ouve-me: lamento-me e rujo.

[[v19-55-3]]

^<<v19-55-3,3>>^ Por causa do clamor do inimigo e da opressão do ímpio: pois lançam sobre mim iniquidade, e com furor me aborrecem.

[[v19-55-4]]

^<<v19-55-4,4>>^ O meu coração está dorido dentro de mim, e terrores de morte sobre mim caíram.

[[v19-55-5]]

^<<v19-55-5,5>>^ Temor e tremor me sobrevêm; e o horror me cobriu.

[[v19-55-6]]

^<<v19-55-6,6>>^ Pelo que disse: Ah! quem me dera asas como de pomba! voaria, e estaria em descanso.

[[v19-55-7]]

^<<v19-55-7,7>>^ Eis que fugiria para longe, e  pernoitaria no deserto. (Selá.)

[[v19-55-8]]

^<<v19-55-8,8>>^ Apressar-me-ia a escapar da fúria do vento e  da tempestade.

[[v19-55-9]]

^<<v19-55-9,9>>^ Despedaça, Senhor, e divide as suas línguas, pois tenho visto violência e contenda na cidade.

[[v19-55-10]]

^<<v19-55-10,10>>^ De dia e de noite andam ao redor dela, sobre os seus muros; iniquidade e malícia estão  no meio dela.

[[v19-55-11]]

^<<v19-55-11,11>>^ Maldade há  lá dentro: astúcia e engano não se apartam das suas ruas.

[[v19-55-12]]

^<<v19-55-12,12>>^ Pois não era um  inimigo que  me afrontava: então eu o  teria suportado; nem era  o que me aborrecia que se  engrandecia contra mim, porque dele me teria escondido.

[[v19-55-13]]

^<<v19-55-13,13>>^ Mas eras tu, homem meu igual, meu guia e meu íntimo amigo.

[[v19-55-14]]

^<<v19-55-14,14>>^ Praticávamos juntos suavemente, e  íamos com a multidão à casa de Deus.

[[v19-55-15]]

^<<v19-55-15,15>>^ A morte os assalte, e  vivos os engula a terra; porque há  maldade nas suas habitações e  no seu próprio interior.

[[v19-55-16]]

^<<v19-55-16,16>>^ Mas eu invocarei a Deus, e o Senhor me salvará.

[[v19-55-17]]

^<<v19-55-17,17>>^ De tarde e de manhã e ao meio-dia orarei; e clamarei, e ele ouvirá a minha voz.

[[v19-55-18]]

^<<v19-55-18,18>>^ Livrou em paz a minha alma da guerra que me moviam; pois eram muitos contra mim.

[[v19-55-19]]

^<<v19-55-19,19>>^ Deus ouvirá; e os afligirá Aquele que preside desde a antiguidade (Selá), porque não há neles nenhuma mudança, e  tão pouco temem a Deus.

[[v19-55-20]]

^<<v19-55-20,20>>^ Puseram suas mãos nos que tinham paz com ele: romperam a sua aliança.

[[v19-55-21]]

^<<v19-55-21,21>>^ A sua boca era mais macia do que a manteiga, mas no seu coração, guerra; as suas palavras eram  mais brandas do que o azeite: todavia, eram espadas nuas.

[[v19-55-22]]

^<<v19-55-22,22>>^ Lança o teu cuidado sobre o Senhor, e ele te susterá: nunca permitirá que o justo seja abalado.

[[v19-55-23]]

^<<v19-55-23,23>>^ Mas tu, ó Deus, os farás descer ao poço da perdição; homens de sangue e de fraude não viverão metade dos seus dias; mas eu em ti confiarei.

'''

xref:019-salmos/019-salmos-054.adoc#v19-54-0[&#60; Capítulo Anterior] | <<v19-55-0,Topo>> | xref:019-salmos/019-salmos-056.adoc#v19-56-0[Próximo Capítulo &#62;]