include::./index.adoc[]

[[v19-119-0]]
=== Salmos, 119
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-119-1]]

^<<v19-119-1,1>>^ BEM-AVENTURADOS os que trilham caminhos retos, e andam na lei do Senhor.

[[v19-119-2]]

^<<v19-119-2,2>>^ Bem-aventurados os que guardam os seus testemunhos, e  o buscam de todo o coração.

[[v19-119-3]]

^<<v19-119-3,3>>^ E não praticam iniquidade, mas andam em seus caminhos.

[[v19-119-4]]

^<<v19-119-4,4>>^ Tu ordenaste os teus mandamentos, para que diligentemente os observássemos.

[[v19-119-5]]

^<<v19-119-5,5>>^ Oxalá os meus caminhos fossem dirigidos de maneira a poder eu observar os teus estatutos.

[[v19-119-6]]

^<<v19-119-6,6>>^ Então não ficaria confundido, atentando eu para todos os teus mandamentos.

[[v19-119-7]]

^<<v19-119-7,7>>^ Louvar-te-ei com retidão de coração, quando tiver aprendido os teus justos juízos.

[[v19-119-8]]

^<<v19-119-8,8>>^ Observarei os teus estatutos: não me desampares totalmente. Bete

[[v19-119-9]]

^<<v19-119-9,9>>^ Como purificará o mancebo o seu caminho? observando- o  conforme a tua palavra.

[[v19-119-10]]

^<<v19-119-10,10>>^ De todo o meu coração te busquei: não me deixes desviar dos teus mandamentos.

[[v19-119-11]]

^<<v19-119-11,11>>^ Escondi a tua palavra no meu coração, para eu não pecar contra ti.

[[v19-119-12]]

^<<v19-119-12,12>>^ Bendito és  tu, ó Senhor; ensina-me os teus estatutos.

[[v19-119-13]]

^<<v19-119-13,13>>^ Com os meus lábios declarei todos os juízos da tua boca.

[[v19-119-14]]

^<<v19-119-14,14>>^ Folgo mais com o caminho dos teus testemunhos, do que todas as riquezas.

[[v19-119-15]]

^<<v19-119-15,15>>^ Em teus preceitos meditarei, e olharei para os teus caminhos.

[[v19-119-16]]

^<<v19-119-16,16>>^ Recrear-me-ei nos teus estatutos: não me esquecerei da tua palavra. Guímel

[[v19-119-17]]

^<<v19-119-17,17>>^ Faze bem ao teu servo para que  viva e observe a tua palavra.

[[v19-119-18]]

^<<v19-119-18,18>>^ Desvenda os meus olhos, para que veja as maravilhas da tua lei.

[[v19-119-19]]

^<<v19-119-19,19>>^ Sou  peregrino na terra: não escondas de mim, os teus mandamentos.

[[v19-119-20]]

^<<v19-119-20,20>>^ A minha alma está quebrantada de desejar os teus juízos em todo o tempo.

[[v19-119-21]]

^<<v19-119-21,21>>^ Tu repreendeste asperamente os soberbos, amaldiçoados, que se desviam dos teus mandamentos.

[[v19-119-22]]

^<<v19-119-22,22>>^ Tira de sobre mim o opróbrio e o desprezo, pois guardei os teus testemunhos.

[[v19-119-23]]

^<<v19-119-23,23>>^ Enquanto os príncipes se conluiavam e falavam contra mim, o teu servo meditava nos teus estatutos.

[[v19-119-24]]

^<<v19-119-24,24>>^ Também os teus testemunhos são o meu prazer e  os meus conselheiros. Dálete

[[v19-119-25]]

^<<v19-119-25,25>>^ A minha alma está pegada ao pó: vivifica-me segundo a tua palavra.

[[v19-119-26]]

^<<v19-119-26,26>>^ Meus caminhos te descrevi, e tu me ouviste: ensina-me os teus estatutos.

[[v19-119-27]]

^<<v19-119-27,27>>^ Faze-me entender o caminho dos teus preceitos: assim falarei das tuas maravilhas.

[[v19-119-28]]

^<<v19-119-28,28>>^ A minha alma consome-se de tristeza: fortalece-me segundo a tua palavra.

[[v19-119-29]]

^<<v19-119-29,29>>^ Desvia de mim o caminho da falsidade, e concede-me piedosamente a tua lei.

[[v19-119-30]]

^<<v19-119-30,30>>^ Escolhi o caminho da verdade: propus-me seguir os teus juízos.

[[v19-119-31]]

^<<v19-119-31,31>>^ Apego-me aos teus testemunhos: Ó Senhor, não me confundas.

[[v19-119-32]]

^<<v19-119-32,32>>^ Correrei pelo caminho dos teus mandamentos, quando dilatares o meu coração. Hê

[[v19-119-33]]

^<<v19-119-33,33>>^ Ensina-me, ó Senhor, o caminho dos teus estatutos, e guardá-lo-ei até o fim.

[[v19-119-34]]

^<<v19-119-34,34>>^ Dá-me entendimento, e guardarei a tua lei, e observá-la-ei de todo o coração.

[[v19-119-35]]

^<<v19-119-35,35>>^ Faze-me andar na vereda dos teus mandamentos, porque nela tenho prazer.

[[v19-119-36]]

^<<v19-119-36,36>>^ Inclina o meu coração a teus testemunhos, e não à cobiça.

[[v19-119-37]]

^<<v19-119-37,37>>^ Desvia os meus olhos de contemplarem a vaidade, e vivifica-me no teu caminho.

[[v19-119-38]]

^<<v19-119-38,38>>^ Confirma a tua promessa ao teu servo, que se inclina ao teu temor.

[[v19-119-39]]

^<<v19-119-39,39>>^ Desvia de mim o opróbrio que temo, pois os teus juízos são  bons.

[[v19-119-40]]

^<<v19-119-40,40>>^ Eis que tenho desejado os teus preceitos; vivifica-me por tua justiça. Vau

[[v19-119-41]]

^<<v19-119-41,41>>^ Venham também sobre mim as tuas misericórdias, ó Senhor, e  a tua salvação segundo a tua palavra.

[[v19-119-42]]

^<<v19-119-42,42>>^ Assim terei que responder ao que me afronta, pois confio na tua palavra.

[[v19-119-43]]

^<<v19-119-43,43>>^ E de minha boca não tires nunca de todo a palavra de verdade, pois me atenho aos teus juízos.

[[v19-119-44]]

^<<v19-119-44,44>>^ Assim observarei de contínuo a tua lei, para sempre e eternamente.

[[v19-119-45]]

^<<v19-119-45,45>>^ E andarei em liberdade; pois busquei os teus preceitos.

[[v19-119-46]]

^<<v19-119-46,46>>^ Também falarei dos teus testemunhos perante os reis, e não me envergonharei.

[[v19-119-47]]

^<<v19-119-47,47>>^ E recrear-me-ei em teus mandamentos, que eu amo.

[[v19-119-48]]

^<<v19-119-48,48>>^ Também levantarei as minhas mãos para os teus mandamentos, que amo, e meditarei nos teus estatutos. Zaine

[[v19-119-49]]

^<<v19-119-49,49>>^ Lembra-te da palavra dada  ao teu servo, na qual me fizeste esperar.

[[v19-119-50]]

^<<v19-119-50,50>>^ Isto é  a minha consolação na minha angústia, porque a tua palavra me vivificou.

[[v19-119-51]]

^<<v19-119-51,51>>^ Os soberbos zombaram grandemente de mim; apesar disso, não me desviei da tua lei.

[[v19-119-52]]

^<<v19-119-52,52>>^ Lembrei-me dos teus juízos antiquíssimos, ó Senhor, e assim  me consolei.

[[v19-119-53]]

^<<v19-119-53,53>>^ Grande indignação se apoderou de mim por causa dos ímpios que abandonam a tua lei.

[[v19-119-54]]

^<<v19-119-54,54>>^ Os teus estatutos têm sido os meus cânticos no lugar das minhas peregrinações.

[[v19-119-55]]

^<<v19-119-55,55>>^ De noite me lembrei do teu nome, ó Senhor, e observei a tua lei.

[[v19-119-56]]

^<<v19-119-56,56>>^ Isto fiz eu, porque guardei os teus mandamentos. Hete

[[v19-119-57]]

^<<v19-119-57,57>>^ O Senhor é  a minha porção: eu disse que observaria as tuas palavras.

[[v19-119-58]]

^<<v19-119-58,58>>^ Implorei deveras o teu favor de todo o meu  coração: tem piedade de mim, segundo a tua palavra.

[[v19-119-59]]

^<<v19-119-59,59>>^ Considerei os meus caminhos, e voltei os meus pés para os teus testemunhos.

[[v19-119-60]]

^<<v19-119-60,60>>^ Apressei-me, e não me detive, a observar os teus mandamentos.

[[v19-119-61]]

^<<v19-119-61,61>>^ Bandos de ímpios me despojaram; apesar disso, eu não me esqueci da tua lei.

[[v19-119-62]]

^<<v19-119-62,62>>^ À meia-noite me levantarei para te louvar, pelos teus justos juízos.

[[v19-119-63]]

^<<v19-119-63,63>>^ Companheiro sou  de todos os que te temem e dos que guardam os teus preceitos.

[[v19-119-64]]

^<<v19-119-64,64>>^ A terra, ó Senhor, está cheia da tua benignidade: ensina-me os teus estatutos. Tete

[[v19-119-65]]

^<<v19-119-65,65>>^ Fizeste bem ao teu servo, Senhor, segundo a tua palavra.

[[v19-119-66]]

^<<v19-119-66,66>>^ Ensina-me bom juízo e ciência, pois cri nos teus mandamentos.

[[v19-119-67]]

^<<v19-119-67,67>>^ Antes de ser afligido andava errado; mas agora guardo a tua palavra.

[[v19-119-68]]

^<<v19-119-68,68>>^ Tu és  bom e abençoador: ensina-me os teus estatutos.

[[v19-119-69]]

^<<v19-119-69,69>>^ Os soberbos forjaram mentiras contra mim; mas  eu de todo o coração guardarei os teus preceitos.

[[v19-119-70]]

^<<v19-119-70,70>>^ Engrossa-se-lhes o coração como gordura, mas  eu me recreio na tua lei.

[[v19-119-71]]

^<<v19-119-71,71>>^ Foi- me bom ter sido afligido, para que aprendesse os teus estatutos.

[[v19-119-72]]

^<<v19-119-72,72>>^ Melhor é  para mim a lei da tua boca do que inúmeras riquezas em ouro ou prata. Jode

[[v19-119-73]]

^<<v19-119-73,73>>^ As tuas mãos me fizeram e me afeiçoaram; dá-me inteligência para que aprenda os teus mandamentos.

[[v19-119-74]]

^<<v19-119-74,74>>^ Os que te temem alegraram-se quando me viram, porque tenho esperado na tua palavra.

[[v19-119-75]]

^<<v19-119-75,75>>^ Bem sei eu, ó Senhor, que os teus juízos são  justos, e que  em tua fidelidade me afligiste.

[[v19-119-76]]

^<<v19-119-76,76>>^ Sirva pois a tua benignidade para me consolar, segundo a palavra que deste  ao teu servo.

[[v19-119-77]]

^<<v19-119-77,77>>^ Venham sobre mim as tuas misericórdias, para que viva, pois a tua lei é  a minha delícia.

[[v19-119-78]]

^<<v19-119-78,78>>^ Confundam-se os soberbos, pois me trataram duma maneira perversa, sem causa; mas  eu meditarei nos teus preceitos.

[[v19-119-79]]

^<<v19-119-79,79>>^ Voltem-se para mim os que te temem, e aqueles que têm conhecido os teus testemunhos.

[[v19-119-80]]

^<<v19-119-80,80>>^ Seja reto o meu coração para com os teus estatutos, para que eu não seja confundido. Cafe

[[v19-119-81]]

^<<v19-119-81,81>>^ Desfaleceu a minha alma, esperando por tua salvação; mas  confiei na tua palavra.

[[v19-119-82]]

^<<v19-119-82,82>>^ Os meus olhos desfaleceram, esperando por tua promessa; entretanto  dizia: Quando me consolarás tu?

[[v19-119-83]]

^<<v19-119-83,83>>^ Pois fiquei como odre no fumo; mas não me esqueci dos teus estatutos.

[[v19-119-84]]

^<<v19-119-84,84>>^ Quantos serão  os dias do teu servo? Quando me  farás justiça contra os que me perseguem?

[[v19-119-85]]

^<<v19-119-85,85>>^ Os soberbos abriram covas para mim, o que não é  conforme à tua lei.

[[v19-119-86]]

^<<v19-119-86,86>>^ Todos os teus mandamentos são  verdade: com mentiras me perseguem; ajuda-me.

[[v19-119-87]]

^<<v19-119-87,87>>^ Quase que me têm consumido sobre a terra; mas eu não deixei os teus preceitos.

[[v19-119-88]]

^<<v19-119-88,88>>^ Vivifica-me segundo a tua benignidade; então guardarei o testemunho da tua boca. Lâmede

[[v19-119-89]]

^<<v19-119-89,89>>^ Para sempre, ó Senhor, a tua palavra permanece no céu.

[[v19-119-90]]

^<<v19-119-90,90>>^ A tua fidelidade estende-se de geração a geração: tu firmaste a terra, e firme permanece.

[[v19-119-91]]

^<<v19-119-91,91>>^ Conforme o que ordenaste, tudo se mantém até hoje; porque todas as cousas te obedecem.

[[v19-119-92]]

^<<v19-119-92,92>>^ Se a tua lei não fora  toda a minha recreação, há muito  que teria perecido na minha angústia.

[[v19-119-93]]

^<<v19-119-93,93>>^ Nunca me esquecerei dos teus preceitos; pois por eles me tens vivificado.

[[v19-119-94]]

^<<v19-119-94,94>>^ Sou  teu, salva-me; pois tenho buscado os teus preceitos.

[[v19-119-95]]

^<<v19-119-95,95>>^ Os ímpios me esperam para me destruírem, mas  eu atentarei para os teus testemunhos.

[[v19-119-96]]

^<<v19-119-96,96>>^ A toda a perfeição vi limite, mas  o teu mandamento é  amplíssimo. Meme

[[v19-119-97]]

^<<v19-119-97,97>>^ Oh! quanto amo a tua lei é  a minha meditação em todo o dia.

[[v19-119-98]]

^<<v19-119-98,98>>^ Tu, pelos teus mandamentos, me fazes mais sábio que meus inimigos; pois estão  sempre comigo.

[[v19-119-99]]

^<<v19-119-99,99>>^ Tenho mais entendimento do que todos os meus mestres, porque medito nos teus testemunhos.

[[v19-119-100]]

^<<v19-119-100,100>>^ Sou mais prudente do que os velhos; porque guardo os teus preceitos.

[[v19-119-101]]

^<<v19-119-101,101>>^ Desviei os meus pés de todo o caminho mau, para observar a tua palavra.

[[v19-119-102]]

^<<v19-119-102,102>>^ Não me apartei dos teus juízos, porque tu me ensinaste.

[[v19-119-103]]

^<<v19-119-103,103>>^ Oh! quão doces são as tuas palavras ao meu paladar! mais doces  do que o mel à minha boca.

[[v19-119-104]]

^<<v19-119-104,104>>^ Pelos teus mandamentos alcancei entendimento; pelo que aborreço todo o falso caminho. Num

[[v19-119-105]]

^<<v19-119-105,105>>^ Lâmpada para os meus pés é tua palavra, e luz para o meu caminho.

[[v19-119-106]]

^<<v19-119-106,106>>^ Jurei, e cumprirei, que hei de guardar os teus justos juízos.

[[v19-119-107]]

^<<v19-119-107,107>>^ Estou aflitíssimo; vivifica-me, ó Senhor, segundo a tua palavra.

[[v19-119-108]]

^<<v19-119-108,108>>^ Aceita, Senhor eu te rogo, as oferendas voluntárias da minha boca; ensina-me os teus juízos.

[[v19-119-109]]

^<<v19-119-109,109>>^ A minha alma está  de contínuo nas minhas mãos; todavia não me esqueço da tua lei.

[[v19-119-110]]

^<<v19-119-110,110>>^ Os ímpios me armaram laço; contudo não me desviei dos teus preceitos.

[[v19-119-111]]

^<<v19-119-111,111>>^ Os teus testemunhos tenho eu tomado por herança para sempre, pois são  o gozo do meu coração.

[[v19-119-112]]

^<<v19-119-112,112>>^ Inclinei o meu coração a guardar os teus estatutos, para sempre, até ao fim. Sâmeque

[[v19-119-113]]

^<<v19-119-113,113>>^ Aborreço a duplicidade, mas amo a tua lei.

[[v19-119-114]]

^<<v19-119-114,114>>^ Tu és  o meu refúgio e o meu escudo; espero na tua palavra.

[[v19-119-115]]

^<<v19-119-115,115>>^ Apartai-vos de mim, malfeitores, para que guarde os mandamentos do meu Deus.

[[v19-119-116]]

^<<v19-119-116,116>>^ Sustenta-me conforme a tua palavra, para que viva, e não me deixes envergonhado da minha esperança.

[[v19-119-117]]

^<<v19-119-117,117>>^ Sustenta-me, e serei salvo, e de contínuo me recrearei nos teus estatutos.

[[v19-119-118]]

^<<v19-119-118,118>>^ Tu desprezas a todos os que se desviam dos teus estatutos, pois o engano deles é  falsidade.

[[v19-119-119]]

^<<v19-119-119,119>>^ Tu tiraste da terra, como escórias, a todos os ímpios, pelo que amo os teus testemunhos.

[[v19-119-120]]

^<<v19-119-120,120>>^ O meu corpo se arrepiou com temor de ti, e temi os teus juízos. Aim

[[v19-119-121]]

^<<v19-119-121,121>>^ Fiz juízo e justiça: não me entregues aos meus opressores.

[[v19-119-122]]

^<<v19-119-122,122>>^ Fica por fiador do teu servo para o bem; não deixes que os soberbos me oprimam.

[[v19-119-123]]

^<<v19-119-123,123>>^ Os meus olhos desfaleceram, esperando por tua salvação e pela promessa da tua justiça.

[[v19-119-124]]

^<<v19-119-124,124>>^ Trata com o teu servo segundo a tua benignidade, e ensina-me os teus estatutos.

[[v19-119-125]]

^<<v19-119-125,125>>^ Sou  teu servo: dá-me inteligência, para entender os teus testemunhos.

[[v19-119-126]]

^<<v19-119-126,126>>^ Já é  tempo de operares ó Senhor, pois  eles têm quebrantado a tua lei.

[[v19-119-127]]

^<<v19-119-127,127>>^ Pelo que amo os teus mandamentos mais do que o ouro, e ainda  mais do que o ouro fino.

[[v19-119-128]]

^<<v19-119-128,128>>^ Por isso tenho em tudo como retos todos os teus  preceitos, e  aborreço toda a falsa vereda. Pê

[[v19-119-129]]

^<<v19-119-129,129>>^ Maravilhosos são  os teus testemunhos; por isso a minha alma os guarda.

[[v19-119-130]]

^<<v19-119-130,130>>^ A exposição das tuas palavras dá luz, dá entendimento aos símplices.

[[v19-119-131]]

^<<v19-119-131,131>>^ Abri a minha boca, e respirei, pois que desejei os teus mandamentos.

[[v19-119-132]]

^<<v19-119-132,132>>^ Olha para mim, e tem piedade de mim, conforme usas com os que amam o teu nome.

[[v19-119-133]]

^<<v19-119-133,133>>^ Ordena os meus passos na tua palavra, e não se apodere de mim iniquidade alguma.

[[v19-119-134]]

^<<v19-119-134,134>>^ Livra-me da opressão do homem; assim guardarei os teus preceitos.

[[v19-119-135]]

^<<v19-119-135,135>>^ Faze resplandecer o teu rosto sobre o teu servo, e ensina-me os teus estatutos.

[[v19-119-136]]

^<<v19-119-136,136>>^ Rios de águas correm dos meus olhos, porque não guardam a tua lei. Tsadê

[[v19-119-137]]

^<<v19-119-137,137>>^ Justo és, ó Senhor, e retos são  os teus juízos.

[[v19-119-138]]

^<<v19-119-138,138>>^ Os teus testemunhos que  ordenaste são  retos e muito fiéis.

[[v19-119-139]]

^<<v19-119-139,139>>^ O meu zelo me consumiu, porque os meus inimigos se esqueceram da tua palavra.

[[v19-119-140]]

^<<v19-119-140,140>>^ A tua palavra é  muito pura; por isso o teu servo a ama.

[[v19-119-141]]

^<<v19-119-141,141>>^ Pequeno sou  e desprezado, mas não me esqueço dos teus mandamentos.

[[v19-119-142]]

^<<v19-119-142,142>>^ A tua justiça é uma  justiça eterna, e a tua lei é  a verdade.

[[v19-119-143]]

^<<v19-119-143,143>>^ Aperto e angústia se apoderam de mim; não obstante, os teus mandamentos são  o meu prazer.

[[v19-119-144]]

^<<v19-119-144,144>>^ A justiça dos teus testemunhos é  eterna; dá-me inteligência, e viverei. Cofe

[[v19-119-145]]

^<<v19-119-145,145>>^ Clamei de todo o meu coração; escuta-me, Senhor, e  guardarei os teus estatutos.

[[v19-119-146]]

^<<v19-119-146,146>>^ A ti  te invoquei; salva-me, e guardarei os teus testemunhos.

[[v19-119-147]]

^<<v19-119-147,147>>^ Preveni a alva da manhã, e clamei: esperei na tua palavra.

[[v19-119-148]]

^<<v19-119-148,148>>^ Os meus olhos preveniram as vigílias da noite , para meditar na tua palavra.

[[v19-119-149]]

^<<v19-119-149,149>>^ Ouve a minha voz, segundo a tua benignidade: vivifica-me, ó  Senhor, segundo o teu juízo.

[[v19-119-150]]

^<<v19-119-150,150>>^ Aproximam-se os que seguem a malvados: afastam-se da tua lei.

[[v19-119-151]]

^<<v19-119-151,151>>^ Tu estás  perto ó Senhor, e todos os teus mandamentos são  a verdade.

[[v19-119-152]]

^<<v19-119-152,152>>^ Acerca dos teus testemunhos soube, desde a antiguidade, que tu os fundaste para sempre. Rexe

[[v19-119-153]]

^<<v19-119-153,153>>^ Olha para a minha aflição, e livra-me, pois não me esqueci da tua lei.

[[v19-119-154]]

^<<v19-119-154,154>>^ Pleiteia a minha causa, e livra-me: vivifica-me segundo a tua palavra.

[[v19-119-155]]

^<<v19-119-155,155>>^ A salvação está  longe dos ímpios, pois não buscam os teus estatutos.

[[v19-119-156]]

^<<v19-119-156,156>>^ Muitos são, ó  Senhor, as tuas misericórdias: vivifica-me segundo os teus juízos.

[[v19-119-157]]

^<<v19-119-157,157>>^ Muitos são  os meus perseguidores e os meus inimigos; mas não me desvio dos teus testemunhos.

[[v19-119-158]]

^<<v19-119-158,158>>^ Vi os transgressores, e me afligi, porque não observam a tua palavra.

[[v19-119-159]]

^<<v19-119-159,159>>^ Considera como amo os teus preceitos: vivifica-me, ó Senhor, segundo a tua benignidade.

[[v19-119-160]]

^<<v19-119-160,160>>^ A tua palavra é  a verdade desde o princípio, e cada um dos teus juízos dura  para sempre. Chim

[[v19-119-161]]

^<<v19-119-161,161>>^ Príncipes me perseguiram sem causa, mas o meu coração temeu a tua palavra.

[[v19-119-162]]

^<<v19-119-162,162>>^ Folgo com a tua palavra, como aquele que acha um  grande despojo.

[[v19-119-163]]

^<<v19-119-163,163>>^ Abomino e aborreço a falsidade; mas amo a tua lei.

[[v19-119-164]]

^<<v19-119-164,164>>^ Sete vezes no dia te louvo pelos juízos da tua justiça.

[[v19-119-165]]

^<<v19-119-165,165>>^ Muita paz tem os que amam a tua lei, e para eles não há  tropeço.

[[v19-119-166]]

^<<v19-119-166,166>>^ Senhor, tenho esperado na tua salvação, e tenho cumprido os teus mandamentos.

[[v19-119-167]]

^<<v19-119-167,167>>^ A minha alma tem observado os teus testemunhos; amo-os extremamente.

[[v19-119-168]]

^<<v19-119-168,168>>^ Tenho observado os teus preceitos e os teus testemunhos, porque todos os meus caminhos estão  diante de ti. Tau

[[v19-119-169]]

^<<v19-119-169,169>>^ Chegue a ti o meu clamor, ó Senhor: dá-me entendimento conforme a tua palavra.

[[v19-119-170]]

^<<v19-119-170,170>>^ Chegue a minha súplica perante a tua face: livra-me segundo a tua palavra.

[[v19-119-171]]

^<<v19-119-171,171>>^ Os meus lábios proferiram o louvor, quando me ensinaste os teus estatutos.

[[v19-119-172]]

^<<v19-119-172,172>>^ A minha língua falará da tua palavra, pois todos os teus mandamentos são  justiça.

[[v19-119-173]]

^<<v19-119-173,173>>^ Venha a tua mão socorrer-me, pois escolhi os teus preceitos.

[[v19-119-174]]

^<<v19-119-174,174>>^ Tenho desejado a tua salvação, ó Senhor; a tua lei é  todo o meu prazer.

[[v19-119-175]]

^<<v19-119-175,175>>^ Viva a minha alma, e louvar-te-á: ajudem-me os teus juízos.

[[v19-119-176]]

^<<v19-119-176,176>>^ Desgarrei-me como a ovelha perdida; busca o teu servo, pois não me esqueci dos teus mandamentos.

'''

xref:019-salmos/019-salmos-118.adoc#v19-118-0[&#60; Capítulo Anterior] | <<v19-119-0,Topo>> | xref:019-salmos/019-salmos-120.adoc#v19-120-0[Próximo Capítulo &#62;]