include::./index.adoc[]

[[v19-60-0]]
=== Salmos, 60
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-60-1]]

^<<v19-60-1,1>>^ Ó DEUS, tu nos rejeitaste, tu nos espalhaste, tu tens estado indignado: oh! volta-te para nós.

[[v19-60-2]]

^<<v19-60-2,2>>^ Abalaste a terra, e  a fendeste; sara as suas fendas, pois ela treme.

[[v19-60-3]]

^<<v19-60-3,3>>^ Fizeste ver ao teu povo duras cousas; fizeste-nos beber o vinho da perturbação.

[[v19-60-4]]

^<<v19-60-4,4>>^ Deste um estandarte aos que te temem, para o arvorarem no alto, pela causa da verdade. (Selá.)

[[v19-60-5]]

^<<v19-60-5,5>>^ Para que os teus amados sejam livres, salva- nos com  a tua destra, e ouve-nos;

[[v19-60-6]]

^<<v19-60-6,6>>^ Deus disse na sua santidade: Eu me regozijarei, repartirei a Siquém e medirei o vale de Sucote.

[[v19-60-7]]

^<<v19-60-7,7>>^ Meu é  Galaade, e meu é  Manassés; Efraim é  a força da minha cabeça; Judá é o meu legislador.

[[v19-60-8]]

^<<v19-60-8,8>>^ Moabe é  a minha bacia de lavar; sobre Edom lançarei o meu sapato; alegra-te, ó Palestina, por minha causa.

[[v19-60-9]]

^<<v19-60-9,9>>^ Quem me conduzirá à cidade forte? Quem me guiará até Edom?

[[v19-60-10]]

^<<v19-60-10,10>>^ Não serás  tu, ó Deus, que  nos tinhas rejeitado? tu , ó Deus, que  não saíste com os nossos exércitos?

[[v19-60-11]]

^<<v19-60-11,11>>^ Dá-nos auxílio na angústia, porque vão é  o socorro do homem.

[[v19-60-12]]

^<<v19-60-12,12>>^ Em Deus faremos proezas; porque ele é  que pisará os nossos inimigos.

'''

xref:019-salmos/019-salmos-059.adoc#v19-59-0[&#60; Capítulo Anterior] | <<v19-60-0,Topo>> | xref:019-salmos/019-salmos-061.adoc#v19-61-0[Próximo Capítulo &#62;]