include::./index.adoc[]

[[v19-53-0]]
=== Salmos, 53
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-53-1]]

^<<v19-53-1,1>>^ DISSE o néscio no seu coração: Não há  Deus. Têm-se corrompido, e têm cometido abominável iniquidade: não há  ninguém que faça o bem.

[[v19-53-2]]

^<<v19-53-2,2>>^ Deus olhou desde os céus para os filhos dos homens, para ver se havia algum  que tivesse entendimento e buscasse a Deus.

[[v19-53-3]]

^<<v19-53-3,3>>^ Desviaram-se todos, e juntamente se fizeram imundos; não há  quem faça o bem, não há sequer um.

[[v19-53-4]]

^<<v19-53-4,4>>^ Acaso não têm conhecimento estes obreiros da iniquidade, os quais comem o meu povo como se  comessem pão? eles não invocam a Deus.

[[v19-53-5]]

^<<v19-53-5,5>>^ Eis que se acharam em grande temor, onde  temor não havia, porque Deus espalhou os ossos daquele que te cercava; tu os  confundiste, porque Deus os rejeitou.

[[v19-53-6]]

^<<v19-53-6,6>>^ Oh! se de Sião já viesse a salvação de Israel! Quando Deus fizer voltar os cativos do seu povo, então  se regozijará Jacó e  se alegrará Israel.

'''

xref:019-salmos/019-salmos-052.adoc#v19-52-0[&#60; Capítulo Anterior] | <<v19-53-0,Topo>> | xref:019-salmos/019-salmos-054.adoc#v19-54-0[Próximo Capítulo &#62;]