include::./index.adoc[]

[[v19-103-0]]
=== Salmos, 103
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-103-1]]

^<<v19-103-1,1>>^ BENDIZE, ó minha alma, ao Senhor, e tudo o que há em mim bendiga  o seu santo nome.

[[v19-103-2]]

^<<v19-103-2,2>>^ Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios.

[[v19-103-3]]

^<<v19-103-3,3>>^ É ele que perdoa todas as tuas iniquidades, e sara todas as tuas enfermidades;

[[v19-103-4]]

^<<v19-103-4,4>>^ Quem redime a tua vida da perdição, e te coroa de benignidade e de misericórdia.

[[v19-103-5]]

^<<v19-103-5,5>>^ Quem enche a tua boca de bens, de sorte que  a tua mocidade se renova como a águia.

[[v19-103-6]]

^<<v19-103-6,6>>^ O Senhor faz justiça e juízo a todos os oprimidos.

[[v19-103-7]]

^<<v19-103-7,7>>^ Fez notórios os seus caminhos a Moisés, e os seus feitos aos filhos de Israel.

[[v19-103-8]]

^<<v19-103-8,8>>^ Misericordioso e piedoso é  o Senhor; longânimo e grande em benignidade.

[[v19-103-9]]

^<<v19-103-9,9>>^ Não repreenderá perpetuamente, nem para sempre conservará a sua ira.

[[v19-103-10]]

^<<v19-103-10,10>>^ Não nos tratou segundo os nossos pecados, nem nos retribuiu segundo as nossas iniquidades.

[[v19-103-11]]

^<<v19-103-11,11>>^ Pois quanto o céu está elevado acima da terra, assim  é grande a sua misericórdia para com os que o temem.

[[v19-103-12]]

^<<v19-103-12,12>>^ Quanto está longe o oriente do ocidente, assim  afasta de nós as nossas transgressões.

[[v19-103-13]]

^<<v19-103-13,13>>^ Como um pai se compadece de seus  filhos assim  o Senhor se compadece daqueles que o temem.

[[v19-103-14]]

^<<v19-103-14,14>>^ Pois ele conhece a nossa estrutura; lembra-se de que somos  pó.

[[v19-103-15]]

^<<v19-103-15,15>>^ Porque o homem, são seus dias como a erva; como a flor do campo, assim floresce;

[[v19-103-16]]

^<<v19-103-16,16>>^ Pois, passando por ela o vento, logo  se vai, e o seu lugar não conhece mais.

[[v19-103-17]]

^<<v19-103-17,17>>^ Mas a misericórdia do Senhor é  de eternidade a eternidade sobre aqueles que o temem, e a sua justiça sobre os filhos dos filhos;

[[v19-103-18]]

^<<v19-103-18,18>>^ Sobre aqueles que guardam o seu concerto, e sobre os que se lembram dos seus mandamentos para os cumprirem.

[[v19-103-19]]

^<<v19-103-19,19>>^ O Senhor tem estabelecido o seu trono nos céus, e o seu reino domina sobre tudo.

[[v19-103-20]]

^<<v19-103-20,20>>^ Bendizei ao Senhor, anjos seus, magníficos em poder, que cumpris as suas ordens, obedecendo à voz da sua palavra.

[[v19-103-21]]

^<<v19-103-21,21>>^ Bendizei ao Senhor, todos os seus exércitos, vós, ministros seus, que executais o seu beneplácito.

[[v19-103-22]]

^<<v19-103-22,22>>^ Bendizei ao Senhor, todas as suas obras, em todos os lugares do seu domínio; bendize, ó minha alma, ao Senhor.

'''

xref:019-salmos/019-salmos-102.adoc#v19-102-0[&#60; Capítulo Anterior] | <<v19-103-0,Topo>> | xref:019-salmos/019-salmos-104.adoc#v19-104-0[Próximo Capítulo &#62;]