include::./index.adoc[]

[[v19-62-0]]
=== Salmos, 62
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-62-1]]

^<<v19-62-1,1>>^ A MINHA alma espera somente em Deus: dele vem  a minha salvação.

[[v19-62-2]]

^<<v19-62-2,2>>^ Só ele é  a minha rocha e a minha salvação; é  a minha defesa; não serei grandemente abalado.

[[v19-62-3]]

^<<v19-62-3,3>>^ Até quando maquinareis o mal  contra um homem? sereis mortos todos vós, sereis  como uma parede encurvada e  uma sebe pouco segura.

[[v19-62-4]]

^<<v19-62-4,4>>^ Eles somente consultam como  o hão de derribar da sua excelência: deleitam-se em mentiras; com a boca bendizem, mas nas suas entranhas maldizem. (Selá.)

[[v19-62-5]]

^<<v19-62-5,5>>^ Ó minha alma, espera somente em Deus, porque dele vem  a minha esperança.

[[v19-62-6]]

^<<v19-62-6,6>>^ Só ele é  a minha rocha e a minha salvação; é  a minha defesa; não serei abalado.

[[v19-62-7]]

^<<v19-62-7,7>>^ Em Deus está  a minha salvação e a minha glória: a rocha da minha fortaleza, e  o meu refúgio estão  em Deus.

[[v19-62-8]]

^<<v19-62-8,8>>^ Confiai nele, ó povo, em todos os tempos; derramai perante ele o vosso coração; Deus é  o nosso refúgio. (Selá.)

[[v19-62-9]]

^<<v19-62-9,9>>^ Certamente que os homens de classe baixa são  vaidade, e os homens de ordem elevada são mentira; pesados em balanças, eles juntos são mais leves  do que a vaidade.

[[v19-62-10]]

^<<v19-62-10,10>>^ Não confieis na opressão, nem vos desvaneçais na rapina; se as vossas riquezas aumentam, não ponhais nelas  o coração.

[[v19-62-11]]

^<<v19-62-11,11>>^ Uma cousa disse Deus, duas vezes a ouvi: que o poder pertence  a Deus.

[[v19-62-12]]

^<<v19-62-12,12>>^ A ti também, Senhor, pertence  a misericórdia; pois retribuirás a cada um segundo a sua obra.

'''

xref:019-salmos/019-salmos-061.adoc#v19-61-0[&#60; Capítulo Anterior] | <<v19-62-0,Topo>> | xref:019-salmos/019-salmos-063.adoc#v19-63-0[Próximo Capítulo &#62;]