include::./index.adoc[]

[[v19-52-0]]
=== Salmos, 52
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-52-1]]

^<<v19-52-1,1>>^ PORQUE te glorias na malícia, ó homem poderoso? pois a bondade de Deus permanece  continuamente.

[[v19-52-2]]

^<<v19-52-2,2>>^ A tua língua intenta o mal, como uma navalha afiada, traçando enganos.

[[v19-52-3]]

^<<v19-52-3,3>>^ Tu amas mais o mal do que o bem, e  mais a mentira do que o falar conforme a retidão. (Selá.)

[[v19-52-4]]

^<<v19-52-4,4>>^ Amas todas as palavras devoradoras, ó língua fraudulenta.

[[v19-52-5]]

^<<v19-52-5,5>>^ Também Deus te destruirá para sempre; arrebatar-te-á e arrancar-te-á da tua  habitação; e desarraigar-te-á da terra dos viventes. (Selá.)

[[v19-52-6]]

^<<v19-52-6,6>>^ E os justos o verão, e temerão: e se rirão dele:

[[v19-52-7]]

^<<v19-52-7,7>>^ Eis aqui o homem que  não pôs a Deus por sua fortaleza; antes confiou na abundância das suas riquezas, e  se fortaleceu na sua maldade.

[[v19-52-8]]

^<<v19-52-8,8>>^ Mas eu sou  como a oliveira verde na casa de Deus; confio na misericórdia de Deus para sempre, eternamente.

[[v19-52-9]]

^<<v19-52-9,9>>^ Para sempre te louvarei, porque tu isso fizeste, e esperarei no teu nome, porque é  bom diante de teus santos.

'''

xref:019-salmos/019-salmos-051.adoc#v19-51-0[&#60; Capítulo Anterior] | <<v19-52-0,Topo>> | xref:019-salmos/019-salmos-053.adoc#v19-53-0[Próximo Capítulo &#62;]