include::./index.adoc[]

[[v19-22-0]]
=== Salmos, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-22-1]]

^<<v19-22-1,1>>^ DEUS meu, Deus meu, por que me desamparaste? por que  te alongas das palavras do meu bramido, e não me auxilias?

[[v19-22-2]]

^<<v19-22-2,2>>^ Deus meu, eu clamo de dia, e tu não me ouves; de noite, e não tenho sossego.

[[v19-22-3]]

^<<v19-22-3,3>>^ Porém tu és  Santo, o que habitas entre  os louvores de Israel.

[[v19-22-4]]

^<<v19-22-4,4>>^ Em ti confiaram nossos pais; confiaram, e tu os livraste.

[[v19-22-5]]

^<<v19-22-5,5>>^ A ti clamaram e escaparam: em ti confiaram, e não foram confundidos.

[[v19-22-6]]

^<<v19-22-6,6>>^ Mas eu sou  verme, e não homem, opróbrio dos homens e desprezado do povo.

[[v19-22-7]]

^<<v19-22-7,7>>^ Todos os que me veem zombam de mim, estendem os beiços e meneiam a cabeça, dizendo :

[[v19-22-8]]

^<<v19-22-8,8>>^ Confiou no Senhor, que o livre; livre-o, pois nele tem prazer.

[[v19-22-9]]

^<<v19-22-9,9>>^ Mas tu és  o que me tiraste do ventre: o que me preservaste estando  ainda aos seios de minha mãe.

[[v19-22-10]]

^<<v19-22-10,10>>^ Sobre ti fui lançado desde a madre; tu és  o meu Deus desde o ventre de minha mãe.

[[v19-22-11]]

^<<v19-22-11,11>>^ Não te alongues de mim, pois a angústia está  perto, e não há  quem ajude.

[[v19-22-12]]

^<<v19-22-12,12>>^ Muitos touros me cercaram; fortes touros  de Basã me rodearam.

[[v19-22-13]]

^<<v19-22-13,13>>^ Abriram contra mim suas bocas, como  um leão que despedaça e que ruge.

[[v19-22-14]]

^<<v19-22-14,14>>^ Como água me derramei, e todos os meus ossos se desconjuntaram; o meu coração é como cera, derreteu-se no meio das minhas entranhas.

[[v19-22-15]]

^<<v19-22-15,15>>^ A minha força se secou como um caco, e a língua se me pega ao paladar: e me puseste no pó da morte.

[[v19-22-16]]

^<<v19-22-16,16>>^ Pois me rodearam cães: o ajuntamento de malfeitores me cercou, traspassaram-me as mãos e os pés.

[[v19-22-17]]

^<<v19-22-17,17>>^ Poderia contar todos os meus ossos: eles veem e  me contemplam.

[[v19-22-18]]

^<<v19-22-18,18>>^ Repartem entre si os meus vestidos, e lançam sortes sobre a minha túnica,

[[v19-22-19]]

^<<v19-22-19,19>>^ Mas tu, Senhor, não te alongues de mim: força minha, apressa-te em socorrer-me.

[[v19-22-20]]

^<<v19-22-20,20>>^ Livra a minha alma  da espada, e  a minha predileta da força do cão.

[[v19-22-21]]

^<<v19-22-21,21>>^ Salva-me da boca do leão, sim, ouve-me, desde as pontas dos unicórnios.

[[v19-22-22]]

^<<v19-22-22,22>>^ Então declararei o teu nome aos meus irmãos: louvar-te-ei no meio da congregação.

[[v19-22-23]]

^<<v19-22-23,23>>^ Vós, que temeis ao Senhor, louvai-o; todos vós, descendência de Jacó, glorificai-o; e temei-o todos vós, descendência de Israel.

[[v19-22-24]]

^<<v19-22-24,24>>^ Porque não desprezou nem abominou a aflição do aflito, nem escondeu dele o seu rosto; antes, quando ele clamou, o ouviu.

[[v19-22-25]]

^<<v19-22-25,25>>^ O meu louvor virá  de ti na grande congregação: pagarei os meus votos perante os que o temem.

[[v19-22-26]]

^<<v19-22-26,26>>^ Os mansos comerão e se fartarão; louvarão ao Senhor os que o buscam: o vosso coração viverá eternamente.

[[v19-22-27]]

^<<v19-22-27,27>>^ Todos os limites da terra se lembrarão, e se converterão ao Senhor: e todas as gerações das nações adorarão perante a tua face.

[[v19-22-28]]

^<<v19-22-28,28>>^ Porque o reino é  do Senhor, e ele domina entre as nações.

[[v19-22-29]]

^<<v19-22-29,29>>^ Todos os grandes da terra comerão e adorarão, e todos os que descem ao pó se prostrarão perante ele: como também os que não podem reter a sua vida.

[[v19-22-30]]

^<<v19-22-30,30>>^ Uma semente o servirá: falará do Senhor de geração em geração.

[[v19-22-31]]

^<<v19-22-31,31>>^ Chegarão e anunciarão a sua justiça ao povo que nascer, porquanto ele o  fez.

'''

xref:019-salmos/019-salmos-021.adoc#v19-21-0[&#60; Capítulo Anterior] | <<v19-22-0,Topo>> | xref:019-salmos/019-salmos-023.adoc#v19-23-0[Próximo Capítulo &#62;]