include::./index.adoc[]

[[v19-4-0]]
=== Salmos, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-4-1]]

^<<v19-4-1,1>>^ OUVE-ME quando eu clamo, ó Deus da minha justiça; na angústia me deste largueza; tem misericórdia de mim e ouve a minha oração.

[[v19-4-2]]

^<<v19-4-2,2>>^ Filhos dos homens, até quando convertereis  a minha glória em infâmia? Até quando  amareis a vaidade e  buscareis a mentira? (Selá.)

[[v19-4-3]]

^<<v19-4-3,3>>^ Sabei pois que o Senhor separou para si aquele que lhe é querido; o Senhor ouvirá quando eu clamar a ele.

[[v19-4-4]]

^<<v19-4-4,4>>^ Perturbai-vos e não pequeis; falai com o vosso coração sobre a vossa cama, e calai-vos. (Selá.)

[[v19-4-5]]

^<<v19-4-5,5>>^ Oferecei sacrifícios de justiça, e confiai no Senhor.

[[v19-4-6]]

^<<v19-4-6,6>>^ Muitos dizem: Quem nos mostrará o bem? Senhor, exalta sobre nós a luz do teu rosto.

[[v19-4-7]]

^<<v19-4-7,7>>^ Puseste alegria no meu coração, mais do que no tempo em que se multiplicaram o seu trigo e o seu vinho.

[[v19-4-8]]

^<<v19-4-8,8>>^ Em paz também me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança.

'''

xref:019-salmos/019-salmos-003.adoc#v19-3-0[&#60; Capítulo Anterior] | <<v19-4-0,Topo>> | xref:019-salmos/019-salmos-005.adoc#v19-5-0[Próximo Capítulo &#62;]