include::./index.adoc[]

[[v19-10-0]]
=== Salmos, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-10-1]]

^<<v19-10-1,1>>^ POR QUE te conservas longe, Senhor? Por que  te escondes nos tempos de angústia?

[[v19-10-2]]

^<<v19-10-2,2>>^ Os ímpios, na sua  arrogância, perseguem furiosamente o pobre: sejam apanhados nas ciladas que maquinaram.

[[v19-10-3]]

^<<v19-10-3,3>>^ Porque o ímpio gloria-se do desejo da sua alma; bendiz ao avarento, e blasfema do Senhor.

[[v19-10-4]]

^<<v19-10-4,4>>^ Por causa do seu orgulho, o ímpio não investiga; todas as suas cogitações são: Não há  Deus.

[[v19-10-5]]

^<<v19-10-5,5>>^ Os seus caminhos são sempre atormentadores: os teus juízos estão  longe dele, em grande altura; trata com desprezo os seus adversários.

[[v19-10-6]]

^<<v19-10-6,6>>^ Diz em seu coração: Não serei abalado, porque nunca me verei  na adversidade.

[[v19-10-7]]

^<<v19-10-7,7>>^ A sua boca está cheia de imprecações, de enganos e de astúcia; debaixo da sua língua há  malícia e maldade.

[[v19-10-8]]

^<<v19-10-8,8>>^ Põe-se nos cerrados das aldeias; nos lugares ocultos mata o inocente; os seus olhos estão ocultamente fixos sobre o pobre.

[[v19-10-9]]

^<<v19-10-9,9>>^ Arma ciladas em esconderijos, como o leão no seu covil; arma ciladas para roubar o pobre; rouba-o colhendo-o na sua rede.

[[v19-10-10]]

^<<v19-10-10,10>>^ Encolhe-se, abaixa-se, para que os pobres caiam em suas fortes garras.

[[v19-10-11]]

^<<v19-10-11,11>>^ Diz em seu coração: Deus esqueceu-se; cobriu o seu rosto, e nunca verá isto.

[[v19-10-12]]

^<<v19-10-12,12>>^ Levanta-te, Senhor: oh! Deus, levanta a tua mão; não te esqueças dos necessitados.

[[v19-10-13]]

^<<v19-10-13,13>>^ Por que blasfema de Deus o ímpio, dizendo no seu coração que tu não inquirirás?

[[v19-10-14]]

^<<v19-10-14,14>>^ Tu o  viste, porque atentas para o trabalho e enfado, para os tomares sob tuas mãos; a ti o pobre se encomenda; tu és o auxílio do órfão.

[[v19-10-15]]

^<<v19-10-15,15>>^ Quebranta o braço do ímpio e malvado; busca a sua impiedade, até  nada mais achares dela.

[[v19-10-16]]

^<<v19-10-16,16>>^ O Senhor é  Rei eterno; da sua terra serão desarraigados os gentios.

[[v19-10-17]]

^<<v19-10-17,17>>^ Senhor, tu ouviste os desejos dos mansos; confortarás os seus corações; os teus ouvidos estarão abertos para eles ;

[[v19-10-18]]

^<<v19-10-18,18>>^ Para fazeres justiça ao órfão e ao oprimido, a fim de que o homem, que é da terra, não prossiga mais em usar da violência.

'''

xref:019-salmos/019-salmos-009.adoc#v19-9-0[&#60; Capítulo Anterior] | <<v19-10-0,Topo>> | xref:019-salmos/019-salmos-011.adoc#v19-11-0[Próximo Capítulo &#62;]