include::./index.adoc[]

[[v19-96-0]]
=== Salmos, 96
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-96-1]]

^<<v19-96-1,1>>^ CANTAI ao Senhor um  cântico novo, cantai ao Senhor, todos os moradores da terra.

[[v19-96-2]]

^<<v19-96-2,2>>^ Cantai ao Senhor, bendizei o seu nome: anunciai a sua salvação de dia em dia.

[[v19-96-3]]

^<<v19-96-3,3>>^ Anunciai entre as nações a sua glória; entre todos os povos as suas maravilhas.

[[v19-96-4]]

^<<v19-96-4,4>>^ Porque grande é  o Senhor e digno de louvor, mais tremendo do que todos os deuses.

[[v19-96-5]]

^<<v19-96-5,5>>^ Porque todos os deuses dos povos são  cousas vãs; mas o Senhor fez os céus.

[[v19-96-6]]

^<<v19-96-6,6>>^ Glória e majestade estão  ante a sua face, força e formosura no seu santuário.

[[v19-96-7]]

^<<v19-96-7,7>>^ Dai ao Senhor, ó famílias dos povos, dai ao Senhor glória e força.

[[v19-96-8]]

^<<v19-96-8,8>>^ Dai ao Senhor a glória devida ao  seu nome: trazei oferendas, e entrai nos seus átrios.

[[v19-96-9]]

^<<v19-96-9,9>>^ Adorai ao Senhor na beleza da santidade: tremei diante dele todos os moradores da terra.

[[v19-96-10]]

^<<v19-96-10,10>>^ Dizei entre as nações: O Senhor reina; o mundo também se firmará para que se não abale. Ele julgará os povos com retidão.

[[v19-96-11]]

^<<v19-96-11,11>>^ Alegrem-se os céus, e regozije-se a terra: brame o mar e a sua plenitude.

[[v19-96-12]]

^<<v19-96-12,12>>^ Alegre-se o campo com tudo o que há  nele; então se regozijarão todas as árvores do bosque,

[[v19-96-13]]

^<<v19-96-13,13>>^ Ante a face do Senhor, porque vem, porque vem a julgar a terra: julgará o mundo com justiça e os povos com a sua verdade.

'''

xref:019-salmos/019-salmos-095.adoc#v19-95-0[&#60; Capítulo Anterior] | <<v19-96-0,Topo>> | xref:019-salmos/019-salmos-097.adoc#v19-97-0[Próximo Capítulo &#62;]