include::./index.adoc[]

[[v19-90-0]]
=== Salmos, 90
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-90-1]]

^<<v19-90-1,1>>^ SENHOR, tu tens sido o nosso refúgio, de geração em geração.

[[v19-90-2]]

^<<v19-90-2,2>>^ Antes que os montes nascessem, ou que tu formasses a terra e o mundo, sim, de eternidade a eternidade, tu és  Deus.

[[v19-90-3]]

^<<v19-90-3,3>>^ Tu reduzes o homem à destruição; e dizes: Volvei, filhos dos homens.

[[v19-90-4]]

^<<v19-90-4,4>>^ Porque mil anos são  aos teus olhos como o dia de ontem que passou, e como  a vigília da noite.

[[v19-90-5]]

^<<v19-90-5,5>>^ Tu os levas como corrente de água: são como um  sono: são  como a erva que  cresce de madrugada,

[[v19-90-6]]

^<<v19-90-6,6>>^ De madrugada cresce e floresce: à tarde corta-se e seca.

[[v19-90-7]]

^<<v19-90-7,7>>^ Pois somos consumidos pela tua ira, e pelo teu furor somos angustiados.

[[v19-90-8]]

^<<v19-90-8,8>>^ Diante de ti puseste as nossas iniquidades: os nossos pecados  ocultos à luz do teu rosto.

[[v19-90-9]]

^<<v19-90-9,9>>^ Pois todos os nossos dias vão passando na tua indignação; acabam-se os nossos anos como um conto ligeiro.

[[v19-90-10]]

^<<v19-90-10,10>>^ A duração da nossa vida é de setenta anos, e se alguns, pela sua robustez, chegam a oitenta anos, o melhor deles é  canseira e enfado, pois passa rapidamente, e nós voamos.

[[v19-90-11]]

^<<v19-90-11,11>>^ Quem conhece o poder da tua ira? e a tua cólera, segundo o temor que te é devido?

[[v19-90-12]]

^<<v19-90-12,12>>^ Ensina-nos a contar os nossos dias, de tal maneira que alcancemos corações sábios.

[[v19-90-13]]

^<<v19-90-13,13>>^ Volta-te para nós, Senhor; até quando? e aplaca-te para com os teus servos.

[[v19-90-14]]

^<<v19-90-14,14>>^ Sacia-nos de madrugada com a tua benignidade, para que nos regozijemos, e nos alegremos todos os nossos dias.

[[v19-90-15]]

^<<v19-90-15,15>>^ Alegra-nos pelos dias em que  nos afligiste, e  pelos anos em que  vimos o mal.

[[v19-90-16]]

^<<v19-90-16,16>>^ Apareça a tua obra aos teus servos, e a tua glória sobre seus filhos.

[[v19-90-17]]

^<<v19-90-17,17>>^ E seja sobre nós a graça do Senhor, nosso Deus: e confirma sobre nós a obra das nossas mãos; sim, confirma a obra das nossas mãos.

'''

xref:019-salmos/019-salmos-089.adoc#v19-89-0[&#60; Capítulo Anterior] | <<v19-90-0,Topo>> | xref:019-salmos/019-salmos-091.adoc#v19-91-0[Próximo Capítulo &#62;]