include::./index.adoc[]

[[v19-50-0]]
=== Salmos, 50
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-50-1]]

^<<v19-50-1,1>>^ O DEUS poderoso, o Senhor, falou e chamou a terra desde o nascimento do sol até ao seu ocaso.

[[v19-50-2]]

^<<v19-50-2,2>>^ Desde Sião, a perfeição da formosura, resplandeceu Deus.

[[v19-50-3]]

^<<v19-50-3,3>>^ Virá o nosso Deus, e não se calará; adiante dele um  fogo irá consumindo, e haverá grande tormenta ao redor dele.

[[v19-50-4]]

^<<v19-50-4,4>>^ Chamará os céus, do alto, e a terra, para julgar o seu povo.

[[v19-50-5]]

^<<v19-50-5,5>>^ Congregai os meus santos, aqueles que fizeram comigo um  concerto com sacrifícios.

[[v19-50-6]]

^<<v19-50-6,6>>^ E os céus anunciarão a sua justiça; pois Deus mesmo é  o Juiz. (Selá.)

[[v19-50-7]]

^<<v19-50-7,7>>^ Ouve, povo meu, e eu falarei; ó Israel, e eu, Deus, o teu Deus, protestarei contra ti.

[[v19-50-8]]

^<<v19-50-8,8>>^ Não te repreenderei pelos teus sacrifícios, ou holocaustos, de contínuo perante mim.

[[v19-50-9]]

^<<v19-50-9,9>>^ Da tua casa não tirarei bezerro nem  bodes dos teus currais.

[[v19-50-10]]

^<<v19-50-10,10>>^ Porque meu é  todo o animal da selva, e  as alimárias sobre milhares de montanhas.

[[v19-50-11]]

^<<v19-50-11,11>>^ Conheço todas as aves dos montes; e minhas são  todas as feras do campo.

[[v19-50-12]]

^<<v19-50-12,12>>^ Se eu tivesse fome, não to diria, pois meu é  o mundo e a sua plenitude.

[[v19-50-13]]

^<<v19-50-13,13>>^ Comerei eu carne de touros? ou beberei sangue de bodes?

[[v19-50-14]]

^<<v19-50-14,14>>^ Oferece a Deus sacrifício de louvor, e paga ao Altíssimo os teus votos.

[[v19-50-15]]

^<<v19-50-15,15>>^ E invoca-me no dia da angústia: eu te livrarei, e tu me glorificarás.

[[v19-50-16]]

^<<v19-50-16,16>>^ Mas ao ímpio diz Deus: Que tens tu que recitar os meus estatutos, e que tomar o meu concerto na tua boca,

[[v19-50-17]]

^<<v19-50-17,17>>^ Pois aborreces a correção, e lanças as minhas palavras para detrás de ti?

[[v19-50-18]]

^<<v19-50-18,18>>^ Quando vês o ladrão, consentes com ele, e tens  a tua parte com adúlteros.

[[v19-50-19]]

^<<v19-50-19,19>>^ Soltas a tua boca para o mal, e a tua língua compõe o engano.

[[v19-50-20]]

^<<v19-50-20,20>>^ Assentas-te a falar contra teu irmão; falas mal contra o filho de tua mãe.

[[v19-50-21]]

^<<v19-50-21,21>>^ Estas cousas  tens feito, e eu me calei; pensavas que era como tu; mas  eu te arguirei, e, em sua ordem, tudo porei diante dos teus olhos.

[[v19-50-22]]

^<<v19-50-22,22>>^ Ouvi pois isto, vós que vos esqueceis de Deus; para que vos  não faça em pedaços, sem haver quem vos  livre.

[[v19-50-23]]

^<<v19-50-23,23>>^ Aquele que oferece sacrifício de louvor me glorificará; e àquele que bem  ordena o seu  caminho eu mostrarei a salvação de Deus.

'''

xref:019-salmos/019-salmos-049.adoc#v19-49-0[&#60; Capítulo Anterior] | <<v19-50-0,Topo>> | xref:019-salmos/019-salmos-051.adoc#v19-51-0[Próximo Capítulo &#62;]