include::./index.adoc[]

[[v19-41-0]]
=== Salmos, 41
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-41-1]]

^<<v19-41-1,1>>^ BEM-AVENTURADO é  aquele que atende ao pobre; o Senhor o livrará no dia do mal.

[[v19-41-2]]

^<<v19-41-2,2>>^ O Senhor o livrará, e o conservará em vida; será abençoado na terra, e tu não o entregarás à vontade de seus inimigos.

[[v19-41-3]]

^<<v19-41-3,3>>^ O Senhor o sustentará no leito da enfermidade; tu renovas a sua cama na doença.

[[v19-41-4]]

^<<v19-41-4,4>>^ Eu dizia: Senhor, tem piedade de mim; sara a minha alma, porque pequei contra ti.

[[v19-41-5]]

^<<v19-41-5,5>>^ Os meus inimigos falam mal de mim, dizendo : Quando morrerá ele, e perecerá o seu nome?

[[v19-41-6]]

^<<v19-41-6,6>>^ E, se algum deles  vem ver-me, diz cousas vãs; no seu coração amontoa a maldade; em saindo para fora, é disso que fala.

[[v19-41-7]]

^<<v19-41-7,7>>^ Todos os que me aborrecem murmuram à uma contra mim; contra mim imaginam o mal, dizendo :

[[v19-41-8]]

^<<v19-41-8,8>>^ Uma má doença se lhe pegou; e, pois que está deitado, não se levantará mais.

[[v19-41-9]]

^<<v19-41-9,9>>^ Até o meu próprio amigo íntimo, em quem eu tanto  confiava, que comia do meu pão, levantou contra mim o seu calcanhar.

[[v19-41-10]]

^<<v19-41-10,10>>^ Mas tu, Senhor, tem piedade de mim, e levanta-me, para que eu lhes dê o pago.

[[v19-41-11]]

^<<v19-41-11,11>>^ Por isto conheço eu que tu me favoreces: que o meu inimigo não triunfa de mim.

[[v19-41-12]]

^<<v19-41-12,12>>^ Quanto a mim, tu me sustentas na minha sinceridade, e me puseste diante da tua face para sempre.

[[v19-41-13]]

^<<v19-41-13,13>>^ Bendito seja  o Senhor Deus de Israel, de século em século: Amém e Amém.

'''

xref:019-salmos/019-salmos-040.adoc#v19-40-0[&#60; Capítulo Anterior] | <<v19-41-0,Topo>> | xref:019-salmos/019-salmos-042.adoc#v19-42-0[Próximo Capítulo &#62;]