include::./index.adoc[]

[[v19-49-0]]
=== Salmos, 49
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-49-1]]

^<<v19-49-1,1>>^ OUVI isto, vós  todos os povos; inclinai os ouvidos, todos os moradores do mundo.

[[v19-49-2]]

^<<v19-49-2,2>>^ Quer humildes quer grandes, tanto ricos como pobres.

[[v19-49-3]]

^<<v19-49-3,3>>^ A minha boca falará da sabedoria; e a meditação do meu coração será  de entendimento.

[[v19-49-4]]

^<<v19-49-4,4>>^ Inclinarei os meus ouvidos a uma  parábola: decifrarei o meu enigma na harpa:

[[v19-49-5]]

^<<v19-49-5,5>>^ Por que temerei eu nos dias maus, quando  me cercar a iniquidade dos que me armam ciladas?

[[v19-49-6]]

^<<v19-49-6,6>>^ Aqueles que confiam na sua fazenda, e se gloriam na multidão das suas riquezas,

[[v19-49-7]]

^<<v19-49-7,7>>^ Nenhum deles de modo algum pode remir a seu irmão, ou dar a Deus o resgate dele

[[v19-49-8]]

^<<v19-49-8,8>>^ (Pois a redenção da sua alma é caríssima, e seus recursos se esgotariam antes);

[[v19-49-9]]

^<<v19-49-9,9>>^ Por isso tão pouco viverá para sempre, ou deixará de ver a corrupção:

[[v19-49-10]]

^<<v19-49-10,10>>^ Porque vê que  os sábios morrem, que perecem igualmente o louco e o bruto, e deixam a outros os seus bens.

[[v19-49-11]]

^<<v19-49-11,11>>^ O seu pensamento  interior é que  as suas casas serão  perpétuas e  as suas habitações de geração em geração: dão às suas terras os seus próprios nomes.

[[v19-49-12]]

^<<v19-49-12,12>>^ Todavia o homem que está  em honra não permanece; antes  é como os animais que  perecem.

[[v19-49-13]]

^<<v19-49-13,13>>^ Este caminho deles é  a sua loucura; contudo a sua posteridade aprova as suas palavras. (Selá.)

[[v19-49-14]]

^<<v19-49-14,14>>^ Como ovelhas são enterrados; a morte se alimentará deles; e os retos terão domínio sobre eles na manhã; e a sua formosura na sepultura se consumirá, por não ter mais onde more.

[[v19-49-15]]

^<<v19-49-15,15>>^ Mas Deus remirá a minha alma do poder da sepultura, pois me receberá. (Selá.)

[[v19-49-16]]

^<<v19-49-16,16>>^ Não temas, quando alguém se enriquece, quando a glória da sua casa se engrandece.

[[v19-49-17]]

^<<v19-49-17,17>>^ Porque quando morrer, nada levará consigo , nem a sua glória o acompanhará.

[[v19-49-18]]

^<<v19-49-18,18>>^ Ainda que na sua vida ele bendisse a sua alma, e os homens  te louvem quando fazes bem a ti mesmo.

[[v19-49-19]]

^<<v19-49-19,19>>^ Irá para a geração dos seus pais; eles nunca verão a luz.

[[v19-49-20]]

^<<v19-49-20,20>>^ O homem que está  em honra, e não tem entendimento, é semelhante aos animais que perecem.

'''

xref:019-salmos/019-salmos-048.adoc#v19-48-0[&#60; Capítulo Anterior] | <<v19-49-0,Topo>> | xref:019-salmos/019-salmos-050.adoc#v19-50-0[Próximo Capítulo &#62;]