include::./index.adoc[]

[[v19-138-0]]
=== Salmos, 138
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-138-1]]

^<<v19-138-1,1>>^ EU te louvarei, Senhor , de todo o meu coração: na presença dos deuses a ti cantarei louvores.

[[v19-138-2]]

^<<v19-138-2,2>>^ Inclinar-me-ei para o teu santo templo, e louvarei o teu nome pela tua benignidade, e pela sua verdade: pois engrandeceste a tua palavra acima de todo o teu nome.

[[v19-138-3]]

^<<v19-138-3,3>>^ No dia em que eu clamei, me escutaste; alentaste-me, fortalecendo a minha alma.

[[v19-138-4]]

^<<v19-138-4,4>>^ Todos os reis da terra te louvarão, ó Senhor, quando ouvirem as palavras da tua boca;

[[v19-138-5]]

^<<v19-138-5,5>>^ E cantarão os caminhos do Senhor; pois grande é  a glória do Senhor.

[[v19-138-6]]

^<<v19-138-6,6>>^ Ainda que o Senhor é excelso, atenta para o humilde; mas ao soberbo conhece- o  de longe.

[[v19-138-7]]

^<<v19-138-7,7>>^ Andando eu no meio da angústia, tu me revivificarás: estenderás a tua mão contra a ira dos meus inimigos, e a tua destra me salvará.

[[v19-138-8]]

^<<v19-138-8,8>>^ O Senhor aperfeiçoará o que me concerne; a tua benignidade, ó Senhor, é  para sempre; não desampares as obras das tuas mãos.

'''

xref:019-salmos/019-salmos-137.adoc#v19-137-0[&#60; Capítulo Anterior] | <<v19-138-0,Topo>> | xref:019-salmos/019-salmos-139.adoc#v19-139-0[Próximo Capítulo &#62;]