include::./index.adoc[]

[[v19-84-0]]
=== Salmos, 84
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-84-1]]

^<<v19-84-1,1>>^ QUÃO amáveis são  os teus tabernáculos, Senhor dos Exércitos!

[[v19-84-2]]

^<<v19-84-2,2>>^ A minha alma está anelante, e desfalece pelos átrios do Senhor: o meu coração e a minha carne clamam pelo Deus vivo.

[[v19-84-3]]

^<<v19-84-3,3>>^ Até o pardal encontrou casa, e a andorinha ninho para si, e para a sua prole, junto dos teus altares, Senhor dos Exércitos, Rei meu e Deus meu.

[[v19-84-4]]

^<<v19-84-4,4>>^ Bem-aventurados os que habitam em tua casa: louvar-te-ão continuamente. (Selá.)

[[v19-84-5]]

^<<v19-84-5,5>>^ Bem-aventurado o homem cuja força está em ti, em cujo coração estão  os caminhos aplanados.

[[v19-84-6]]

^<<v19-84-6,6>>^ O qual passando pelo vale de Baca, faz dele uma fonte; a chuva também enche os tanques.

[[v19-84-7]]

^<<v19-84-7,7>>^ Vão indo de força em força; cada um deles  em Sião aparece perante Deus.

[[v19-84-8]]

^<<v19-84-8,8>>^ Senhor Deus dos Exércitos, escuta a minha oração: inclina os ouvidos, ó Deus de Jacó! (Selá.)

[[v19-84-9]]

^<<v19-84-9,9>>^ Olha, ó Deus, escudo nosso, e contempla o rosto do teu ungido.

[[v19-84-10]]

^<<v19-84-10,10>>^ Porque vale mais um dia nos teus átrios do que em outra parte mil. Preferiria estar à porta da casa do meu Deus, a habitar nas tendas da impiedade.

[[v19-84-11]]

^<<v19-84-11,11>>^ Porque o Senhor Deus é um  sol e escudo: o Senhor dará graça e glória; não negará bem algum  aos que andam na retidão.

[[v19-84-12]]

^<<v19-84-12,12>>^ Senhor dos Exércitos, bem-aventurado o homem que em ti põe a sua confiança.

'''

xref:019-salmos/019-salmos-083.adoc#v19-83-0[&#60; Capítulo Anterior] | <<v19-84-0,Topo>> | xref:019-salmos/019-salmos-085.adoc#v19-85-0[Próximo Capítulo &#62;]