include::./index.adoc[]

[[v19-24-0]]
=== Salmos, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-24-1]]

^<<v19-24-1,1>>^ DO Senhor é  a terra e a sua plenitude, o mundo e aqueles que nele habitam.

[[v19-24-2]]

^<<v19-24-2,2>>^ Porque ele a fundou sobre os mares, e a firmou sobre os rios.

[[v19-24-3]]

^<<v19-24-3,3>>^ Quem subirá ao monte do Senhor, ou quem estará no seu lugar santo?

[[v19-24-4]]

^<<v19-24-4,4>>^ Aquele que é limpo de mãos e puro de coração, que não entrega a sua alma à vaidade, nem jura enganosamente.

[[v19-24-5]]

^<<v19-24-5,5>>^ Este receberá a bênção do Senhor e a justiça do Deus da sua salvação.

[[v19-24-6]]

^<<v19-24-6,6>>^ Esta é  a geração daqueles que buscam, daqueles que buscam a tua face, ó  Deus de Jacó. (Selá.)

[[v19-24-7]]

^<<v19-24-7,7>>^ Levantai, ó  portas, as vossas cabeças; levantai-vos, ó entradas eternas, e entrará o Rei da Glória.

[[v19-24-8]]

^<<v19-24-8,8>>^ Quem é  este Rei da Glória? O Senhor forte e poderoso, o Senhor poderoso na guerra.

[[v19-24-9]]

^<<v19-24-9,9>>^ Levantai, ó portas, as vossas cabeças, levantai-vos, ó entradas eternas, e entrará o Rei da Glória.

[[v19-24-10]]

^<<v19-24-10,10>>^ Quem é este Rei da Glória? O Senhor dos Exércitos; ele é  o Rei da Glória. (Selá.)

'''

xref:019-salmos/019-salmos-023.adoc#v19-23-0[&#60; Capítulo Anterior] | <<v19-24-0,Topo>> | xref:019-salmos/019-salmos-025.adoc#v19-25-0[Próximo Capítulo &#62;]