include::./index.adoc[]

[[v19-140-0]]
=== Salmos, 140
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-140-1]]

^<<v19-140-1,1>>^ LIVRA-ME, ó Senhor, do homem mau: guarda-me do homem violento;

[[v19-140-2]]

^<<v19-140-2,2>>^ Os quais pensam o mal no coração: continuamente se ajuntam para a guerra.

[[v19-140-3]]

^<<v19-140-3,3>>^ Aguçaram as línguas como a serpente; o veneno das víboras está  debaixo dos seus lábios. (Selá.)

[[v19-140-4]]

^<<v19-140-4,4>>^ Guarda-me, ó Senhor, das mãos do ímpio; guarda-me do homem violento, os quais se propuseram desviar os meus passos.

[[v19-140-5]]

^<<v19-140-5,5>>^ Os soberbos armaram-me laços e cordas; estenderam a rede à beira do caminho: armaram-me laços corrediços. (Selá.)

[[v19-140-6]]

^<<v19-140-6,6>>^ Eu disse ao Senhor: Tu és  o meu Deus: ouve a voz das minhas súplicas, ó Senhor.

[[v19-140-7]]

^<<v19-140-7,7>>^ Senhor Deus, fortaleza da minha salvação, tu cobriste a minha cabeça no dia da batalha.

[[v19-140-8]]

^<<v19-140-8,8>>^ Não cumpras, ó Senhor, ao ímpio os seus desejos: não deixes ir por diante o seu mau propósito, para que não se exalte. (Selá.)

[[v19-140-9]]

^<<v19-140-9,9>>^ Quanto  aos que, cercando-me, levantam a cabeça, cubra-os a maldade dos seus lábios.

[[v19-140-10]]

^<<v19-140-10,10>>^ Caiam sobre eles brasas vivas: sejam lançados no fogo: em covas profundas, para que  se não tornem a levantar.

[[v19-140-11]]

^<<v19-140-11,11>>^ Não terá firmeza na terra o homem de má  língua: o mal perseguirá o homem violento até que seja desterrado.

[[v19-140-12]]

^<<v19-140-12,12>>^ Sei que o Senhor sustentará a causa do oprimido, e  o direito do necessitado.

[[v19-140-13]]

^<<v19-140-13,13>>^ Assim os justos louvarão o teu nome: os retos habitarão na tua presença.

'''

xref:019-salmos/019-salmos-139.adoc#v19-139-0[&#60; Capítulo Anterior] | <<v19-140-0,Topo>> | xref:019-salmos/019-salmos-141.adoc#v19-141-0[Próximo Capítulo &#62;]