include::./index.adoc[]

[[v19-11-0]]
=== Salmos, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-11-1]]

^<<v19-11-1,1>>^ NO Senhor confio; como dizeis, pois, à minha alma: Fugi para a vossa montanha como  pássaro?

[[v19-11-2]]

^<<v19-11-2,2>>^ Porque eis que os ímpios armam o arco, põem as frechas na corda, para com elas atirarem, a ocultas, aos retos de coração.

[[v19-11-3]]

^<<v19-11-3,3>>^ Na verdade que já  os fundamentos se transtornam: que pode fazer o justo?

[[v19-11-4]]

^<<v19-11-4,4>>^ O Senhor está  no seu santo templo: o trono do Senhor está  nos céus; os seus olhos estão atentos, e as suas pálpebras provam os filhos dos homens.

[[v19-11-5]]

^<<v19-11-5,5>>^ O Senhor prova o justo; mas a sua alma aborrece o ímpio e o que ama a violência.

[[v19-11-6]]

^<<v19-11-6,6>>^ Sobre os ímpios fará chover laços, fogo, enxofre e vento tempestuoso: eis a porção do seu copo.

[[v19-11-7]]

^<<v19-11-7,7>>^ Porque o Senhor é  justo e  ama a justiça; o seu rosto está voltado para os retos.

'''

xref:019-salmos/019-salmos-010.adoc#v19-10-0[&#60; Capítulo Anterior] | <<v19-11-0,Topo>> | xref:019-salmos/019-salmos-012.adoc#v19-12-0[Próximo Capítulo &#62;]