include::./index.adoc[]

[[v19-72-0]]
=== Salmos, 72
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-72-1]]

^<<v19-72-1,1>>^ Ó DEUS, dá ao rei os teus juízos, e a tua justiça ao filho do rei.

[[v19-72-2]]

^<<v19-72-2,2>>^ Ele julgará ao teu povo com justiça, e aos teus pobres com juízo.

[[v19-72-3]]

^<<v19-72-3,3>>^ Os montes trarão paz ao povo e os outeiros justiça.

[[v19-72-4]]

^<<v19-72-4,4>>^ Julgará os aflitos do povo, salvará os filhos do necessitado, e quebrantará o opressor.

[[v19-72-5]]

^<<v19-72-5,5>>^ Temer-te-ão enquanto durar o sol e a lua, de geração em geração.

[[v19-72-6]]

^<<v19-72-6,6>>^ Ele descerá como a chuva sobre a erva ceifada, como os chuveiros que umedecem a terra.

[[v19-72-7]]

^<<v19-72-7,7>>^ Nos seus dias florescerá o justo, e abundância de paz haverá enquanto durar a lua.

[[v19-72-8]]

^<<v19-72-8,8>>^ Dominará de mar a mar, e desde o rio até às extremidades da terra.

[[v19-72-9]]

^<<v19-72-9,9>>^ Aqueles que habitam no deserto se inclinarão ante ele, e os seus inimigos lamberão o pó.

[[v19-72-10]]

^<<v19-72-10,10>>^ Os reis de Tarsis e das ilhas trarão presentes; os reis de Seba e de Sabá oferecerão dons.

[[v19-72-11]]

^<<v19-72-11,11>>^ E todos os reis se prostrarão perante ele; todas as nações o servirão.

[[v19-72-12]]

^<<v19-72-12,12>>^ Porque ele livrará ao necessitado quando clamar, como também ao aflito e ao que não tem quem o ajude.

[[v19-72-13]]

^<<v19-72-13,13>>^ Compadecer-se-á do pobre e do aflito, e salvará as almas dos necessitados.

[[v19-72-14]]

^<<v19-72-14,14>>^ Libertará as suas almas do engano e da violência, e precioso será o seu sangue aos olhos dele.

[[v19-72-15]]

^<<v19-72-15,15>>^ E viverá, e se lhe dará do ouro de Seba; e continuamente se fará por ele oração; e todos os dias o bendirão.

[[v19-72-16]]

^<<v19-72-16,16>>^ Haverá um punhado de trigo na terra sobre os cumes dos montes; o seu fruto se moverá como o Líbano, e os  da cidade florescerão como a erva da terra.

[[v19-72-17]]

^<<v19-72-17,17>>^ O seu nome permanecerá eternamente; o seu nome se irá propagando de pais a filhos, enquanto o sol durar ; e os homens  serão abençoados nele: todas as nações lhe chamarão bem-aventurado.

[[v19-72-18]]

^<<v19-72-18,18>>^ Bendito seja  o Senhor Deus, o Deus de Israel, que só ele faz maravilhas.

[[v19-72-19]]

^<<v19-72-19,19>>^ E bendito seja  para sempre o seu nome glorioso: e encha-se toda a terra da sua glória. Amém e Amém.

[[v19-72-20]]

^<<v19-72-20,20>>^ Findam aqui as orações de Davi, filho de Jessé.

'''

xref:019-salmos/019-salmos-071.adoc#v19-71-0[&#60; Capítulo Anterior] | <<v19-72-0,Topo>> | xref:019-salmos/019-salmos-073.adoc#v19-73-0[Próximo Capítulo &#62;]