include::./index.adoc[]

[[v19-8-0]]
=== Salmos, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-8-1]]

^<<v19-8-1,1>>^ Ó SENHOR, Senhor nosso, quão admirável é  o teu nome em toda a terra, pois puseste a tua glória sobre os céus!

[[v19-8-2]]

^<<v19-8-2,2>>^ Da boca das crianças e dos que mamam tu suscitaste força, por causa dos teus adversários, para fazeres calar o inimigo e vingativo.

[[v19-8-3]]

^<<v19-8-3,3>>^ Quando vejo os teus céus, obra dos teus dedos, a lua e as estrelas que preparaste;

[[v19-8-4]]

^<<v19-8-4,4>>^ Que é  o homem mortal para que te lembres dele? e o filho do homem, para que o visites?

[[v19-8-5]]

^<<v19-8-5,5>>^ Contudo, pouco menor o fizeste do que os anjos, e de glória e de honra o coroaste.

[[v19-8-6]]

^<<v19-8-6,6>>^ Fazes com que ele tenha domínio sobre as obras das tuas mãos; tudo puseste debaixo de seus pés:

[[v19-8-7]]

^<<v19-8-7,7>>^ Todas as ovelhas e bois, assim como os animais do campo.

[[v19-8-8]]

^<<v19-8-8,8>>^ As aves dos céus, e os peixes do mar, e tudo o que  passa pelas veredas dos mares.

[[v19-8-9]]

^<<v19-8-9,9>>^ Ó Senhor, Senhor nosso, quão admirável é  o teu nome sobre toda a terra!

'''

xref:019-salmos/019-salmos-007.adoc#v19-7-0[&#60; Capítulo Anterior] | <<v19-8-0,Topo>> | xref:019-salmos/019-salmos-009.adoc#v19-9-0[Próximo Capítulo &#62;]