include::./index.adoc[]

[[v19-136-0]]
=== Salmos, 136
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-136-1]]

^<<v19-136-1,1>>^ LOUVAI ao Senhor, porque ele é  bom; porque a sua benignidade é  para sempre.

[[v19-136-2]]

^<<v19-136-2,2>>^ Louvai ao Deus dos deuses; porque a sua benignidade é  para sempre.

[[v19-136-3]]

^<<v19-136-3,3>>^ Louvai ao Senhor dos senhores; porque a sua benignidade é  para sempre.

[[v19-136-4]]

^<<v19-136-4,4>>^ Aquele que só faz maravilhas; porque a sua benignidade é  para sempre.

[[v19-136-5]]

^<<v19-136-5,5>>^ Aquele que com entendimento fez os céus; porque a sua benignidade é  para sempre.

[[v19-136-6]]

^<<v19-136-6,6>>^ Aquele que estendeu a terra sobre as águas; porque a sua benignidade é  para sempre.

[[v19-136-7]]

^<<v19-136-7,7>>^ Aquele que fez os grandes luminares; porque a sua benignidade é  para sempre.

[[v19-136-8]]

^<<v19-136-8,8>>^ O sol para governar de dia; porque a sua benignidade é  para sempre.

[[v19-136-9]]

^<<v19-136-9,9>>^ A lua e as estrelas para presidirem à noite; porque a sua benignidade é  para sempre.

[[v19-136-10]]

^<<v19-136-10,10>>^ Que feriu o Egito no seus primogênitos; porque a sua benignidade é  para sempre.

[[v19-136-11]]

^<<v19-136-11,11>>^ E tirou a Israel do meio deles; porque a sua benignidade é  para sempre.

[[v19-136-12]]

^<<v19-136-12,12>>^ Com mão forte, e com braço estendido; porque a sua benignidade é  para sempre.

[[v19-136-13]]

^<<v19-136-13,13>>^ Aquele que dividiu o Mar Vermelho em duas partes; porque a sua benignidade é  para sempre.

[[v19-136-14]]

^<<v19-136-14,14>>^ E fez passar Israel pelo meio dele; porque a sua benignidade é  para sempre.

[[v19-136-15]]

^<<v19-136-15,15>>^ Mas derribou a Faraó com o seu exército no Mar Vermelho; porque a sua benignidade é  para sempre.

[[v19-136-16]]

^<<v19-136-16,16>>^ Aquele que guiou o seu povo pelo deserto; porque a sua benignidade é  para sempre.

[[v19-136-17]]

^<<v19-136-17,17>>^ Aquele que feriu os grandes reis; porque a sua benignidade é  para sempre.

[[v19-136-18]]

^<<v19-136-18,18>>^ E deu a morte a reis famosos; porque a sua benignidade é  para sempre.

[[v19-136-19]]

^<<v19-136-19,19>>^ Seom, rei dos amorreus; porque a sua benignidade é  para sempre.

[[v19-136-20]]

^<<v19-136-20,20>>^ E Ogue, rei de Basã; porque a sua benignidade é  para sempre.

[[v19-136-21]]

^<<v19-136-21,21>>^ E deu a terra deles em herança; porque a sua benignidade é  para sempre.

[[v19-136-22]]

^<<v19-136-22,22>>^ Sim, em herança a Israel, seu servo; porque a sua benignidade é  para sempre.

[[v19-136-23]]

^<<v19-136-23,23>>^ Que se lembrou da nossa humilhação; porque a sua benignidade é  para sempre.

[[v19-136-24]]

^<<v19-136-24,24>>^ E nos remiu dos nossos inimigos; porque a sua benignidade é  para sempre.

[[v19-136-25]]

^<<v19-136-25,25>>^ Que dá mantimento a toda a carne; porque a sua benignidade é  para sempre.

[[v19-136-26]]

^<<v19-136-26,26>>^ Louvai ao Deus dos céus; porque a sua benignidade é  para sempre.

'''

xref:019-salmos/019-salmos-135.adoc#v19-135-0[&#60; Capítulo Anterior] | <<v19-136-0,Topo>> | xref:019-salmos/019-salmos-137.adoc#v19-137-0[Próximo Capítulo &#62;]