include::./index.adoc[]

[[v19-147-0]]
=== Salmos, 147
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-147-1]]

^<<v19-147-1,1>>^ LOUVAI ao Senhor, porque é bom cantar louvores ao nosso Deus; isto é  agradável; decoroso é  o louvor.

[[v19-147-2]]

^<<v19-147-2,2>>^ O Senhor edifica Jerusalém; congrega os dispersos de Israel;

[[v19-147-3]]

^<<v19-147-3,3>>^ Sara os quebrantados de coração, e liga-lhes as feridas;

[[v19-147-4]]

^<<v19-147-4,4>>^ Conta o número das estrelas, chamando-as a todas pelos seus  nomes.

[[v19-147-5]]

^<<v19-147-5,5>>^ Grande é  o nosso Senhor, e de grande poder; o seu entendimento é  infinito.

[[v19-147-6]]

^<<v19-147-6,6>>^ O Senhor eleva os humildes, e abate os ímpios até à terra.

[[v19-147-7]]

^<<v19-147-7,7>>^ Cantai ao Senhor em ação de graças; cantai louvores ao nosso Deus sobre a harpa.

[[v19-147-8]]

^<<v19-147-8,8>>^ Ele é  que cobre o céu de nuvens, que prepara a chuva para a terra, e  que faz produzir erva sobre os montes;

[[v19-147-9]]

^<<v19-147-9,9>>^ Que dá aos animais o seu sustento, e  aos filhos dos corvos, quando clamam.

[[v19-147-10]]

^<<v19-147-10,10>>^ Não se deleita na força do cavalo, nem se compraz na agilidade do varão.

[[v19-147-11]]

^<<v19-147-11,11>>^ O Senhor agrada-se dos que o temem e  dos que esperam na sua misericórdia.

[[v19-147-12]]

^<<v19-147-12,12>>^ Louva, ó Jerusalém, ao Senhor; louva, ó Sião, ao teu Deus.

[[v19-147-13]]

^<<v19-147-13,13>>^ Porque ele fortaleceu os ferrolhos das tuas portas; abençoa aos teus filhos dentro de ti.

[[v19-147-14]]

^<<v19-147-14,14>>^ Ele é  quem pacifica os teus termos, e  da flor da farinha te farta;

[[v19-147-15]]

^<<v19-147-15,15>>^ Quem envia o seu mandamento à terra; a sua palavra corre velozmente;

[[v19-147-16]]

^<<v19-147-16,16>>^ Quem dá a neve como lã, esparge a geada como cinza;

[[v19-147-17]]

^<<v19-147-17,17>>^ Quem lança o seu gelo em pedaços; quem pode resistir ao seu frio?

[[v19-147-18]]

^<<v19-147-18,18>>^ Manda a sua palavra, e os faz derreter; faz soprar o vento, e correm as águas.

[[v19-147-19]]

^<<v19-147-19,19>>^ Mostra a sua palavra a Jacó, os seus estatutos e os seus juízos a Israel.

[[v19-147-20]]

^<<v19-147-20,20>>^ Não fez assim a nenhuma outra nação; e, quanto aos seus juízos, não os conhecem. Louvai ao Senhor.

'''

xref:019-salmos/019-salmos-146.adoc#v19-146-0[&#60; Capítulo Anterior] | <<v19-147-0,Topo>> | xref:019-salmos/019-salmos-148.adoc#v19-148-0[Próximo Capítulo &#62;]