include::./index.adoc[]

[[v19-5-0]]
=== Salmos, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-5-1]]

^<<v19-5-1,1>>^ DÁ ouvidos às minhas palavras, ó Senhor; atende à minha meditação.

[[v19-5-2]]

^<<v19-5-2,2>>^ Atende à voz do meu clamor, Rei meu e Deus meu, pois a ti orarei.

[[v19-5-3]]

^<<v19-5-3,3>>^ Pela manhã ouvirás a minha voz, ó Senhor; pela manhã me  apresentarei a ti, e vigiarei.

[[v19-5-4]]

^<<v19-5-4,4>>^ Porque tu não és um  Deus que tenha prazer na iniquidade, nem contigo habitará o mal.

[[v19-5-5]]

^<<v19-5-5,5>>^ Os loucos não pararão à tua vista; aborreces a todos os que praticam a maldade.

[[v19-5-6]]

^<<v19-5-6,6>>^ Destruirás aqueles que proferem a mentira; o Senhor aborrecerá o homem sanguinário e fraudulento.

[[v19-5-7]]

^<<v19-5-7,7>>^ Mas eu entrarei em tua casa pela grandeza da tua benignidade; e  em teu temor me inclinarei para o teu santo templo.

[[v19-5-8]]

^<<v19-5-8,8>>^ Senhor, guia-me na tua justiça, por causa dos meus inimigos; aplana diante de mim o teu caminho.

[[v19-5-9]]

^<<v19-5-9,9>>^ Porque não há  retidão na boca deles; as suas entranhas são  verdadeiras maldades, a sua garganta é um sepulcro aberto; lisonjeiam com a sua língua.

[[v19-5-10]]

^<<v19-5-10,10>>^ Declara-os culpados, ó Deus; caiam por seus próprios conselhos; lança-os fora por causa da multidão de suas transgressões, pois se revoltaram contra ti.

[[v19-5-11]]

^<<v19-5-11,11>>^ Mas alegrem-se todos os que confiam em ti; exultem eternamente, porquanto tu os defendes; e em ti se gloriem os que amam o teu nome.

[[v19-5-12]]

^<<v19-5-12,12>>^ Pois tu, Senhor, abençoarás ao justo; circundá-lo-ás da tua benevolência, como de um escudo.

'''

xref:019-salmos/019-salmos-004.adoc#v19-4-0[&#60; Capítulo Anterior] | <<v19-5-0,Topo>> | xref:019-salmos/019-salmos-006.adoc#v19-6-0[Próximo Capítulo &#62;]