include::./index.adoc[]

[[v19-68-0]]
=== Salmos, 68
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-68-1]]

^<<v19-68-1,1>>^ LEVANTE-SE Deus, e sejam dissipados os seus inimigos; fugirão de diante dele os que o aborrecem.

[[v19-68-2]]

^<<v19-68-2,2>>^ Como se impele o fumo, assim  tu os  impeles; como a cera se derrete diante do fogo, assim  pereçam os ímpios diante de Deus.

[[v19-68-3]]

^<<v19-68-3,3>>^ Mas alegrem-se os justos, e se regozijem na presença de Deus, e folguem de alegria.

[[v19-68-4]]

^<<v19-68-4,4>>^ Cantai a Deus, cantai louvores ao seu nome; louvai aquele que vai sobre os céus, pois o seu nome é JÁ ; exultai diante dele.

[[v19-68-5]]

^<<v19-68-5,5>>^ Pai de órfãos e juiz de viúvas é  Deus no seu lugar santo.

[[v19-68-6]]

^<<v19-68-6,6>>^ Deus faz que o solitário viva em família: liberta aqueles que estão presos em grilhões; mas os rebeldes habitam em terra  seca.

[[v19-68-7]]

^<<v19-68-7,7>>^ Ó Deus! quando saías adiante do teu povo; quando caminhavas pelo deserto, (Selá.)

[[v19-68-8]]

^<<v19-68-8,8>>^ A terra abalava-se, e os céus destilavam perante a face de Deus; o próprio Sinai tremeu na presença de Deus, do Deus de Israel.

[[v19-68-9]]

^<<v19-68-9,9>>^ Tu, ó Deus, mandaste a chuva em abundância, confortaste a tua herança, quando estava cansada.

[[v19-68-10]]

^<<v19-68-10,10>>^ Nela habitava o teu rebanho; tu, ó Deus, proveste o pobre da tua bondade.

[[v19-68-11]]

^<<v19-68-11,11>>^ O Senhor deu a palavra; grande era  o exército dos que anunciavam as boas novas.

[[v19-68-12]]

^<<v19-68-12,12>>^ Reis de exércitos fugiram à pressa; e aquela que ficava em casa repartia os despojos.

[[v19-68-13]]

^<<v19-68-13,13>>^ Ainda que vos deiteis entre redis, sereis como  as asas duma  pomba, cobertas de prata, com as suas penas de ouro amarelo.

[[v19-68-14]]

^<<v19-68-14,14>>^ Quando o Onipotente ali espalhou os reis, foi como quando cai a neve em Salmom.

[[v19-68-15]]

^<<v19-68-15,15>>^ O monte de Deus é como  o monte de Basã, um  monte elevado como  o monte de Basã.

[[v19-68-16]]

^<<v19-68-16,16>>^ Por que saltais, ó montes elevados? este é o  monte que  Deus desejou para sua habitação, e o Senhor habitará nele  eternamente.

[[v19-68-17]]

^<<v19-68-17,17>>^ Os carros de Deus são  vinte milhares, milhares de milhares. O Senhor está  entre eles, como em  Sinai, no lugar  santo.

[[v19-68-18]]

^<<v19-68-18,18>>^ Tu subiste ao alto, levaste cativo o cativeiro, recebeste dons para os homens, e até para  os rebeldes, para que o Senhor Deus habitasse entre eles.

[[v19-68-19]]

^<<v19-68-19,19>>^ Bendito seja  o Senhor, que de dia em dia nos cumula de benefícios : o Deus que é  a nossa salvação. (Selá.)

[[v19-68-20]]

^<<v19-68-20,20>>^ O nosso Deus é  o Deus da salvação; e a Jeová , o Senhor, pertencem  as saídas da morte.

[[v19-68-21]]

^<<v19-68-21,21>>^ Mas Deus ferirá gravemente a cabeça de seus inimigos e  o crânio cabeludo do que anda em suas culpas.

[[v19-68-22]]

^<<v19-68-22,22>>^ Disse o Senhor: Eu os farei voltar de Basã; farei voltar o meu povo  das profundezas do mar;

[[v19-68-23]]

^<<v19-68-23,23>>^ Para que o teu pé mergulhe no sangue de teus  inimigos, e nele mergulhe até a língua dos teus cães.

[[v19-68-24]]

^<<v19-68-24,24>>^ Ó Deus, eles têm visto os teus caminhos; os caminhos do meu Deus, meu Rei, no santuário.

[[v19-68-25]]

^<<v19-68-25,25>>^ Os cantores iam adiante, os tocadores de instrumentos atrás; entre eles as donzelas tocando adufes.

[[v19-68-26]]

^<<v19-68-26,26>>^ Celebrai a Deus nas congregações; ao Senhor, desde a fonte de Israel.

[[v19-68-27]]

^<<v19-68-27,27>>^ Ali está  o pequeno Benjamim, que domina sobre eles, os príncipes de Judá com  o seu ajuntamento, os príncipes de Zebulom e os príncipes de Naftali.

[[v19-68-28]]

^<<v19-68-28,28>>^ O teu Deus ordenou a tua força: confirma, ó Deus, o que já  realizaste por nós.

[[v19-68-29]]

^<<v19-68-29,29>>^ Por amor do teu templo em Jerusalém, os reis te trarão presentes.

[[v19-68-30]]

^<<v19-68-30,30>>^ Repreende as feras dos canaviais, a multidão dos touros, com os novilhos dos povos, pisando com os pés as suas peças de prata; dissipa os povos que  desejam a guerra.

[[v19-68-31]]

^<<v19-68-31,31>>^ Embaixadores reais virão do Egito; a Etiópia cedo estenderá para Deus as suas mãos.

[[v19-68-32]]

^<<v19-68-32,32>>^ Reinos da terra, cantai a Deus, cantai louvores ao Senhor. (Selá.)

[[v19-68-33]]

^<<v19-68-33,33>>^ Aquele que vai montado sobre os céus dos céus, desde a antiguidade; eis que envia a sua voz, dá um  brado veemente.

[[v19-68-34]]

^<<v19-68-34,34>>^ Dai a Deus fortaleza: a sua excelência, está  sobre Israel e a sua fortaleza nas mais  altas nuvens.

[[v19-68-35]]

^<<v19-68-35,35>>^ Ó Deus, tu és  tremendo desde os teus santuários: o Deus de Israel é  o que dá fortaleza e poder ao seu povo. Bendito seja  Deus!

'''

xref:019-salmos/019-salmos-067.adoc#v19-67-0[&#60; Capítulo Anterior] | <<v19-68-0,Topo>> | xref:019-salmos/019-salmos-069.adoc#v19-69-0[Próximo Capítulo &#62;]