include::./index.adoc[]

[[v19-146-0]]
=== Salmos, 146
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-146-1]]

^<<v19-146-1,1>>^ LOUVAI ao Senhor. Ó minha alma, louva ao senhor.

[[v19-146-2]]

^<<v19-146-2,2>>^ Louvarei ao Senhor durante a minha vida; cantarei louvores ao meu Deus enquanto viver.

[[v19-146-3]]

^<<v19-146-3,3>>^ Não confieis em príncipes nem  em filhos de homens, em quem não há  salvação.

[[v19-146-4]]

^<<v19-146-4,4>>^ Sai-lhes o espírito, e eles tornam-se em sua terra: naquele mesmo dia perecem os seus pensamentos.

[[v19-146-5]]

^<<v19-146-5,5>>^ Bem-aventurado aquele que tem  o Deus de Jacó por seu auxílio, e  cuja esperança está posta  no Senhor seu Deus,

[[v19-146-6]]

^<<v19-146-6,6>>^ Que fez os céus e a terra, o mar e tudo quanto há  neles, e  que guarda a verdade para sempre;

[[v19-146-7]]

^<<v19-146-7,7>>^ Que faz justiça aos oprimidos; que dá pão aos famintos. O Senhor solta os encarcerados.

[[v19-146-8]]

^<<v19-146-8,8>>^ O Senhor abre os olhos  aos cegos: o Senhor levanta os abatidos: o Senhor ama os justos.

[[v19-146-9]]

^<<v19-146-9,9>>^ O Senhor guarda os estrangeiros: ampara o órfão e a viúva, mas transtorna o caminho dos ímpios.

[[v19-146-10]]

^<<v19-146-10,10>>^ O Senhor reinará eternamente; o teu Deus, ó Sião, é  de geração em geração. Louvai ao Senhor.

'''

xref:019-salmos/019-salmos-145.adoc#v19-145-0[&#60; Capítulo Anterior] | <<v19-146-0,Topo>> | xref:019-salmos/019-salmos-147.adoc#v19-147-0[Próximo Capítulo &#62;]