include::./index.adoc[]

[[v19-29-0]]
=== Salmos, 29
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-29-1]]

^<<v19-29-1,1>>^ DAI ao Senhor, ó filhos dos poderosos, dai ao Senhor glória e força.

[[v19-29-2]]

^<<v19-29-2,2>>^ Dai ao Senhor a glória devida ao  seu nome, adorai o Senhor na beleza da sua santidade.

[[v19-29-3]]

^<<v19-29-3,3>>^ A voz do Senhor ouve-se  sobre as águas; o Deus da glória troveja; o Senhor está  sobre as muitas águas.

[[v19-29-4]]

^<<v19-29-4,4>>^ A voz do Senhor é  poderosa; a voz do Senhor é  cheia de majestade.

[[v19-29-5]]

^<<v19-29-5,5>>^ A voz do Senhor quebra os cedros; sim, o Senhor quebra os cedros do Líbano.

[[v19-29-6]]

^<<v19-29-6,6>>^ Ele os faz saltar como a um bezerro; ao Líbano e Siriom, como novos unicórnios.

[[v19-29-7]]

^<<v19-29-7,7>>^ A voz do Senhor separa as labaredas do fogo.

[[v19-29-8]]

^<<v19-29-8,8>>^ A voz do Senhor faz tremer o deserto; o Senhor faz tremer o deserto de Cades.

[[v19-29-9]]

^<<v19-29-9,9>>^ A voz do Senhor faz parir as cervas, e desnuda as brenhas. E no seu templo cada um diz: Glória!

[[v19-29-10]]

^<<v19-29-10,10>>^ O Senhor se assentou sobre o dilúvio; o Senhor se assenta como Rei, perpetuamente.

[[v19-29-11]]

^<<v19-29-11,11>>^ O Senhor dará força ao seu povo; o Senhor abençoará o seu povo com paz.

'''

xref:019-salmos/019-salmos-028.adoc#v19-28-0[&#60; Capítulo Anterior] | <<v19-29-0,Topo>> | xref:019-salmos/019-salmos-030.adoc#v19-30-0[Próximo Capítulo &#62;]