include::./index.adoc[]

[[v19-106-0]]
=== Salmos, 106
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-106-1]]

^<<v19-106-1,1>>^ LOUVAI ao Senhor. Louvai ao Senhor, porque ele é bom, porque a sua benignidade é para sempre.

[[v19-106-2]]

^<<v19-106-2,2>>^ Quem pode referir as obras poderosas do Senhor? Quem  anunciará os seus louvores?

[[v19-106-3]]

^<<v19-106-3,3>>^ Bem-aventurados os que observam o direito, o que pratica a justiça em todos os tempos.

[[v19-106-4]]

^<<v19-106-4,4>>^ Lembra-te de mim, Senhor, segundo a tua  boa vontade para com o teu povo: visita-me com a tua salvação;

[[v19-106-5]]

^<<v19-106-5,5>>^ Para que eu veja os bens de teus escolhidos, para que eu me alegre com a alegria do teu povo, para que me regozije com a tua herança.

[[v19-106-6]]

^<<v19-106-6,6>>^ Nós pecamos e os nossos pais; cometemos a iniquidade, andamos perversamente.

[[v19-106-7]]

^<<v19-106-7,7>>^ Nossos pais não atentaram para as tuas maravilhas no Egito; não se lembraram da multidão das tuas misericórdias; antes foram rebeldes junto ao mar, sim , o Mar Vermelho.

[[v19-106-8]]

^<<v19-106-8,8>>^ Não obstante, ele os salvou por amor do seu nome, para fazer conhecido o seu poder.

[[v19-106-9]]

^<<v19-106-9,9>>^ Repreendeu o Mar Vermelho e este se secou, e os fez caminhar pelos abismos como pelo deserto.

[[v19-106-10]]

^<<v19-106-10,10>>^ E livrou-os da mão daquele que os aborrecia, e remiu-os da mão do inimigo.

[[v19-106-11]]

^<<v19-106-11,11>>^ E as águas cobriram os seus adversários: nem um só  deles ficou.

[[v19-106-12]]

^<<v19-106-12,12>>^ Então creram nas suas palavras, e cantaram os seus louvores.

[[v19-106-13]]

^<<v19-106-13,13>>^ Cedo, porém, se esqueceram das suas obras; não esperaram o seu conselho:

[[v19-106-14]]

^<<v19-106-14,14>>^ Mas deixaram-se levar da cobiça no deserto, e tentaram a Deus na solidão.

[[v19-106-15]]

^<<v19-106-15,15>>^ E ele satisfez-lhes o desejo, mas fez definhar as suas almas.

[[v19-106-16]]

^<<v19-106-16,16>>^ E tiveram inveja de Moisés no acampamento, e  de Aarão, o santo do Senhor.

[[v19-106-17]]

^<<v19-106-17,17>>^ Abriu-se a terra, e engoliu a Datã, e cobriu a gente de Abirã.

[[v19-106-18]]

^<<v19-106-18,18>>^ E lavrou um fogo na sua gente: a chama abrasou os ímpios.

[[v19-106-19]]

^<<v19-106-19,19>>^ Fizeram um bezerro em Horebe, e adoraram a imagem fundida.

[[v19-106-20]]

^<<v19-106-20,20>>^ E converteram a sua glória na figura de um boi que come erva.

[[v19-106-21]]

^<<v19-106-21,21>>^ Esqueceram-se de Deus, seu Salvador, que fizera grandes cousas no Egito,

[[v19-106-22]]

^<<v19-106-22,22>>^ Maravilhas na terra de Cão, cousas tremendas no Mar Vermelho.

[[v19-106-23]]

^<<v19-106-23,23>>^ Pelo que disse que os teria destruído, se Moisés, seu escolhido, se não pusera perante ele, naquele transe, para desviar a sua indignação, a fim de os  não destruir.

[[v19-106-24]]

^<<v19-106-24,24>>^ Também desprezaram a terra aprazível: não creram na sua palavra.

[[v19-106-25]]

^<<v19-106-25,25>>^ Antes murmuraram em suas tendas, e  não deram ouvidos à voz do Senhor.

[[v19-106-26]]

^<<v19-106-26,26>>^ Pelo que levantou a sua mão contra eles, afirmando que os faria cair no deserto;

[[v19-106-27]]

^<<v19-106-27,27>>^ Que humilharia também a sua descendência entre as nações, e os espalharia pelas terras.

[[v19-106-28]]

^<<v19-106-28,28>>^ Também se juntaram com Baal-Peor, e comeram os sacrifícios dos mortos.

[[v19-106-29]]

^<<v19-106-29,29>>^ Assim o provocaram à ira com as suas ações; e a peste rebentou entre eles.

[[v19-106-30]]

^<<v19-106-30,30>>^ Então se levantou Fineias, que executou o juízo, e cessou aquela peste,

[[v19-106-31]]

^<<v19-106-31,31>>^ E isto lhe foi imputado por justiça, de geração em geração, para sempre.

[[v19-106-32]]

^<<v19-106-32,32>>^ Indignaram-no também junto às águas da contenda, de sorte que sucedeu mal a Moisés, por causa deles;

[[v19-106-33]]

^<<v19-106-33,33>>^ Porque irritaram o seu espírito, de modo que falou imprudentemente com seus lábios.

[[v19-106-34]]

^<<v19-106-34,34>>^ Não destruíram os povos, como o Senhor lhes dissera.

[[v19-106-35]]

^<<v19-106-35,35>>^ Antes se misturaram com as nações, e aprenderam as suas obras.

[[v19-106-36]]

^<<v19-106-36,36>>^ E serviram os seus ídolos, que vieram a ser-lhes um laço.

[[v19-106-37]]

^<<v19-106-37,37>>^ Demais disto , sacrificaram seus filhos e suas filhas aos demônios;

[[v19-106-38]]

^<<v19-106-38,38>>^ E derramaram sangue inocente, o sangue de seus filhos e de suas filhas, que sacrificaram aos ídolos de Canaã, e a terra foi manchada com sangue.

[[v19-106-39]]

^<<v19-106-39,39>>^ Assim se contaminaram com as suas obras, e se corromperam com os seus feitos.

[[v19-106-40]]

^<<v19-106-40,40>>^ Pelo que se acendeu a ira do Senhor contra o seu povo, de modo que abominou a sua herança,

[[v19-106-41]]

^<<v19-106-41,41>>^ E os entregou nas mãos das nações; e aqueles que os aborreciam se assenhorearam deles.

[[v19-106-42]]

^<<v19-106-42,42>>^ E os seus inimigos os oprimiram, humilhando-os debaixo das suas mãos.

[[v19-106-43]]

^<<v19-106-43,43>>^ Muitas vezes os livrou; mas eles provocaram-no com o seu conselho, e foram abatidos pela sua iniquidade.

[[v19-106-44]]

^<<v19-106-44,44>>^ Contudo, atentou para a sua aflição, ouvindo o seu clamor.

[[v19-106-45]]

^<<v19-106-45,45>>^ E lembrou-se do seu concerto, e compadeceu-se, segundo a multidão das suas misericórdias.

[[v19-106-46]]

^<<v19-106-46,46>>^ Por isso fez com que deles tivessem misericórdia os que os levaram cativos.

[[v19-106-47]]

^<<v19-106-47,47>>^ Salva-nos, Senhor, nosso Deus, e congrega-nos dentre as nações, para que louvemos o teu nome santo, e nos gloriemos no teu louvor.

[[v19-106-48]]

^<<v19-106-48,48>>^ Bendito seja  o Senhor, Deus de Israel, de eternidade em eternidade, e todo o povo diga: Amém. Louvai ao Senhor.

'''

xref:019-salmos/019-salmos-105.adoc#v19-105-0[&#60; Capítulo Anterior] | <<v19-106-0,Topo>> | xref:019-salmos/019-salmos-107.adoc#v19-107-0[Próximo Capítulo &#62;]