include::./index.adoc[]

[[v19-94-0]]
=== Salmos, 94
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-94-1]]

^<<v19-94-1,1>>^ Ó SENHOR Deus, a quem a vingança pertence, ó Deus, a quem a vingança pertence, mostra-te resplandecente.

[[v19-94-2]]

^<<v19-94-2,2>>^ Exalta-te, tu, que és juiz da terra: dá o pago aos soberbos.

[[v19-94-3]]

^<<v19-94-3,3>>^ Até quando os ímpios, Senhor, até quando os ímpios saltarão de prazer.

[[v19-94-4]]

^<<v19-94-4,4>>^ Até quando  proferirão, e  dirão cousas duras, e  se gloriarão todos os que praticam a iniquidade?

[[v19-94-5]]

^<<v19-94-5,5>>^ Reduzem a pedaços o teu povo, e afligem a tua herança.

[[v19-94-6]]

^<<v19-94-6,6>>^ Matam a viúva e o estrangeiro, e ao órfão tiram a vida.

[[v19-94-7]]

^<<v19-94-7,7>>^ E dizem: O Senhor não o verá; nem para isso  atentará o Deus de Jacó.

[[v19-94-8]]

^<<v19-94-8,8>>^ Atendei, ó brutais dentre o povo; e vós , loucos, quando sereis sábios?

[[v19-94-9]]

^<<v19-94-9,9>>^ Aquele que fez o ouvido, não ouvirá? e o que formou o olho, não verá?

[[v19-94-10]]

^<<v19-94-10,10>>^ Aquele que argui as gentes, não  castigará? e o que dá ao homem o conhecimento, não saberá ?

[[v19-94-11]]

^<<v19-94-11,11>>^ O Senhor conhece os pensamentos do homem, que são vaidade.

[[v19-94-12]]

^<<v19-94-12,12>>^ Bem-aventurado é  o homem a quem tu repreendes, ó Senhor, e a quem ensinas a tua lei;

[[v19-94-13]]

^<<v19-94-13,13>>^ Para lhe dares descanso dos dias maus, até que se abra a cova para o ímpio.

[[v19-94-14]]

^<<v19-94-14,14>>^ Pois o Senhor não rejeitará o seu povo, nem desamparará a sua herança.

[[v19-94-15]]

^<<v19-94-15,15>>^ Mas o juízo voltará a ser justiça, e hão de segui-lo todos os retos de coração.

[[v19-94-16]]

^<<v19-94-16,16>>^ Quem será por mim contra os malfeitores? quem se porá ao meu lado contra os que praticam a iniquidade?

[[v19-94-17]]

^<<v19-94-17,17>>^ Se o Senhor não fora em meu auxílio já a minha alma habitaria no lugar do  silêncio.

[[v19-94-18]]

^<<v19-94-18,18>>^ Quando eu disse: O meu pé vacila; a tua benignidade, Senhor, me susteve.

[[v19-94-19]]

^<<v19-94-19,19>>^ Multiplicando-se dentro de mim os meus cuidados, as tuas consolações recrearam a minha alma.

[[v19-94-20]]

^<<v19-94-20,20>>^ Podia acaso associar-se contigo o trono de iniquidade, que forja o mal tendo por pretexto uma lei?

[[v19-94-21]]

^<<v19-94-21,21>>^ Acorrem em tropel contra a vida do justo, e condenam o sangue inocente.

[[v19-94-22]]

^<<v19-94-22,22>>^ Mas o Senhor foi o meu alto retiro; e o meu Deus a rocha em que me refugiei.

[[v19-94-23]]

^<<v19-94-23,23>>^ E fará recair sobre eles a sua própria iniquidade; e os destruirá na sua própria malícia: o Senhor nosso Deus os destruirá.

'''

xref:019-salmos/019-salmos-093.adoc#v19-93-0[&#60; Capítulo Anterior] | <<v19-94-0,Topo>> | xref:019-salmos/019-salmos-095.adoc#v19-95-0[Próximo Capítulo &#62;]