include::./index.adoc[]

[[v19-45-0]]
=== Salmos, 45
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-45-1]]

^<<v19-45-1,1>>^ O MEU coração ferve com palavras boas; falo do que tenho feito no tocante ao Rei: a minha língua é  a pena de um destro escritor.

[[v19-45-2]]

^<<v19-45-2,2>>^ Tu és mais formoso do que os filhos dos homens, a graça se derramou em teus lábios; por isso Deus te abençoou para sempre.

[[v19-45-3]]

^<<v19-45-3,3>>^ Cinge a tua espada à coxa, ó Valente, com a tua glória e a tua majestade.

[[v19-45-4]]

^<<v19-45-4,4>>^ E neste  teu esplendor cavalga prosperamente, pela causa da verdade, da mansidão e  da justiça; e a tua destra te ensinará cousas terríveis.

[[v19-45-5]]

^<<v19-45-5,5>>^ As tuas frechas são  agudas no coração dos inimigos do Rei, e por elas  os povos caíram debaixo de ti.

[[v19-45-6]]

^<<v19-45-6,6>>^ O teu trono, ó Deus, é eterno e perpétuo; o cetro do teu reino é  um cetro de equidade.

[[v19-45-7]]

^<<v19-45-7,7>>^ Tu amas a justiça e aborreces a impiedade; por isso Deus, o teu Deus te ungiu com óleo de alegria, mais do que a teus companheiros.

[[v19-45-8]]

^<<v19-45-8,8>>^ Todos os teus vestidos cheiram  a mirra, a aloés e a cássia, desde os palácios de marfim de onde te alegram.

[[v19-45-9]]

^<<v19-45-9,9>>^ As filhas dos reis estavam  entre as tuas ilustres donzelas ; à tua direita estava a rainha ornada  de finíssimo ouro de Ofir.

[[v19-45-10]]

^<<v19-45-10,10>>^ Ouve filha, e olha, e inclina teus ouvidos; esquece-te do teu povo e da casa de teu pai.

[[v19-45-11]]

^<<v19-45-11,11>>^ Então o rei se afeiçoará à tua formosura, pois ele é  teu Senhor; adora-o.

[[v19-45-12]]

^<<v19-45-12,12>>^ E a filha de Tiro estará ali  com presentes; os ricos do povo suplicarão o teu favor.

[[v19-45-13]]

^<<v19-45-13,13>>^ A filha do rei é  toda ilustre no seu palácio; as suas vestes são de ouro tecido.

[[v19-45-14]]

^<<v19-45-14,14>>^ Levá-la-ão ao rei com vestidos bordados; as virgens que a acompanham a trarão a ti.

[[v19-45-15]]

^<<v19-45-15,15>>^ Com alegria e regozijo serão trazidas: elas entrarão no palácio do rei.

[[v19-45-16]]

^<<v19-45-16,16>>^ Em lugar de teus pais será a teus filhos que farás príncipes sobre toda a terra.

[[v19-45-17]]

^<<v19-45-17,17>>^ Farei lembrado o teu nome de geração em geração; pelo que os povos te louvarão eternamente.

'''

xref:019-salmos/019-salmos-044.adoc#v19-44-0[&#60; Capítulo Anterior] | <<v19-45-0,Topo>> | xref:019-salmos/019-salmos-046.adoc#v19-46-0[Próximo Capítulo &#62;]