include::./index.adoc[]

[[v19-3-0]]
=== Salmos, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v19-3-1]]

^<<v19-3-1,1>>^ SENHOR, como se têm multiplicado os meus adversários! São  muitos os que se levantam contra mim.

[[v19-3-2]]

^<<v19-3-2,2>>^ Muitos dizem da minha alma: Não há  salvação para ele em Deus. (Selá.)

[[v19-3-3]]

^<<v19-3-3,3>>^ Mas tu, Senhor, és  um escudo para mim, a minha glória, e o que exalta a minha cabeça.

[[v19-3-4]]

^<<v19-3-4,4>>^ Com a minha voz clamei ao Senhor, ele ouviu-me desde o seu santo monte. (Selá.)

[[v19-3-5]]

^<<v19-3-5,5>>^ Eu me deitei e dormi; acordei, porque o Senhor me sustentou.

[[v19-3-6]]

^<<v19-3-6,6>>^ Não terei medo de dez milhares de pessoas que se  puseram contra mim ao meu redor.

[[v19-3-7]]

^<<v19-3-7,7>>^ Levanta-te, Senhor; salva-me, Deus meu, pois feriste a todos os meus inimigos nos queixos; quebraste os dentes aos ímpios.

[[v19-3-8]]

^<<v19-3-8,8>>^ A salvação vem  do Senhor; sobre o teu povo seja  a tua bênção. (Selá.)

'''

xref:019-salmos/019-salmos-002.adoc#v19-2-0[&#60; Capítulo Anterior] | <<v19-3-0,Topo>> | xref:019-salmos/019-salmos-004.adoc#v19-4-0[Próximo Capítulo &#62;]