include::./index.adoc[]

[[v55-4-0]]
=== 2 Timóteo, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v55-4-1]]

^<<v55-4-1,1>>^ CONJURO -TE  pois diante de Deus, e do Senhor Jesus Cristo, que há de julgar os vivos e os mortos, na sua vinda e no  seu reino,

[[v55-4-2]]

^<<v55-4-2,2>>^ Que pregues a palavra, instes a tempo e fora de tempo, redarguas, repreendas, exortes, com toda a longanimidade e doutrina.

[[v55-4-3]]

^<<v55-4-3,3>>^ Porque virá tempo em que não sofrerão a sã doutrina; mas, tendo comichão nos ouvidos, amontoarão para si doutores conforme as suas próprias concupiscências;

[[v55-4-4]]

^<<v55-4-4,4>>^ E desviarão os ouvidos da verdade, voltando às fábulas.

[[v55-4-5]]

^<<v55-4-5,5>>^ Mas tu sê sóbrio em tudo, sofre as aflições, faze a obra dum evangelista, cumpre o teu ministério.

[[v55-4-6]]

^<<v55-4-6,6>>^ Porque eu já estou sendo oferecido por aspersão de sacrifício, e o tempo da minha partida está próximo.

[[v55-4-7]]

^<<v55-4-7,7>>^ Combati o bom combate, acabei a carreira, guardei a fé.

[[v55-4-8]]

^<<v55-4-8,8>>^ Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele dia; e não somente a mim, mas também a todos os que amarem a sua vinda.

[[v55-4-9]]

^<<v55-4-9,9>>^ Procura vir ter comigo depressa.

[[v55-4-10]]

^<<v55-4-10,10>>^ Porque Demas me desamparou, amando o presente século, e foi para Tessalônica, Crescente para Galácia, Tito para Dalmácia.

[[v55-4-11]]

^<<v55-4-11,11>>^ Só Lucas está comigo. Toma Marcos, e traze-o contigo, porque me é muito útil para o ministério.

[[v55-4-12]]

^<<v55-4-12,12>>^ Também enviei Tíquico a Éfeso.

[[v55-4-13]]

^<<v55-4-13,13>>^ Quando vieres traze a capa que deixei em Trôade, em casa de Carpo, e os livros, principalmente os pergaminhos.

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexandre, o latoeiro, causou-me muitos males; o Senhor lhe pague segundo as suas obras.

[[v55-4-15]]

^<<v55-4-15,15>>^ Tu guarda-te também dele; porque resistiu muito às nossas palavras.

[[v55-4-16]]

^<<v55-4-16,16>>^ Ninguém me assistiu na minha primeira defesa, antes todos me desampararam. Que isto lhes não seja imputado.

[[v55-4-17]]

^<<v55-4-17,17>>^ Mas o Senhor assistiu-me e fortaleceu-me, para que por mim fosse cumprida a pregação, e todos os gentios, a  ouvissem: e fiquei livre da boca do leão.

[[v55-4-18]]

^<<v55-4-18,18>>^ E o Senhor me livrará de toda a má obra, e guardar-me-á para o seu reino celestial; a quem seja  glória para todo o sempre. Amém.

[[v55-4-19]]

^<<v55-4-19,19>>^ Saúda a Prisca e a Áquila, e à casa de Onesíforo.

[[v55-4-20]]

^<<v55-4-20,20>>^ Erasto ficou em Corinto, e deixei Trófimo doente em Mileto.

[[v55-4-21]]

^<<v55-4-21,21>>^ Procura vir antes do inverno. Êubulo, e Púdens, e Lino, e Cláudia, e todos os irmãos te saúdam.

[[v55-4-22]]

^<<v55-4-22,22>>^ O Senhor Jesus Cristo seja  com o teu espírito. A graça seja  convosco. Amém.

'''

xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-tito/056-tito-001.adoc#v56-1-0[Próximo Capítulo &#62;]