include::./index.adoc[]

[[v55-1-0]]
=== 2 Timóteo, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v55-1-1]]

^<<v55-1-1,1>>^ PAULO, apóstolo de Jesus Cristo, pela vontade de Deus, segundo a promessa da vida que está em Cristo Jesus,

[[v55-1-2]]

^<<v55-1-2,2>>^ A Timóteo, meu  amado filho: graça, misericórdia, e  paz da parte de Deus Pai, e da de Cristo Jesus, Senhor nosso.

[[v55-1-3]]

^<<v55-1-3,3>>^ Dou graças a Deus, a quem desde os meus antepassados sirvo com uma consciência pura, de que sem cessar faço memória de ti nas minhas orações noite e dia;

[[v55-1-4]]

^<<v55-1-4,4>>^ Desejando muito ver-te, lembrando-me das tuas lágrimas, para me encher de gozo;

[[v55-1-5]]

^<<v55-1-5,5>>^ Trazendo à memória a fé não fingida que em ti há, a qual habitou primeiro em tua avó Loide, e em tua mãe Eunice, e estou certo de que também habita  em ti.

[[v55-1-6]]

^<<v55-1-6,6>>^ Por cujo motivo te lembro que despertes o dom de Deus que existe em ti pela imposição das minhas mãos.

[[v55-1-7]]

^<<v55-1-7,7>>^ Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.

[[v55-1-8]]

^<<v55-1-8,8>>^ Portanto não te envergonhes do testemunho de nosso Senhor, nem de mim, que sou prisioneiro seu; antes participa das aflições do evangelho segundo o poder de Deus,

[[v55-1-9]]

^<<v55-1-9,9>>^ Que nos salvou, e chamou com uma santa vocação; não segundo as nossas obras, mas segundo o seu próprio propósito e graça que nos foi dada em Cristo Jesus antes dos tempos dos séculos;

[[v55-1-10]]

^<<v55-1-10,10>>^ E que é manifesta agora pela aparição de nosso Salvador Jesus Cristo, o qual aboliu a morte, e trouxe à luz a vida e a incorrupção pelo evangelho;

[[v55-1-11]]

^<<v55-1-11,11>>^ Para o que fui constituído pregador, e apóstolo, e doutor dos gentios.

[[v55-1-12]]

^<<v55-1-12,12>>^ Por cuja causa padeço também isto, mas não me envergonho; porque eu sei em quem tenho crido, e estou certo de que é  poderoso para guardar o meu depósito até àquele dia.

[[v55-1-13]]

^<<v55-1-13,13>>^ Conserva o modelo das sãs palavras que de mim tens ouvido, na fé e na caridade que há  em Cristo Jesus.

[[v55-1-14]]

^<<v55-1-14,14>>^ Guarda o bom depósito pelo Espírito Santo que habita em nós.

[[v55-1-15]]

^<<v55-1-15,15>>^ Bem  sabes isto, que os que estão na Ásia todos se apartaram de mim; entre os quais foram Figelo e Hermógenes.

[[v55-1-16]]

^<<v55-1-16,16>>^ O Senhor conceda misericórdia à casa de Onesíforo, porque muitas vezes me recreou, e não se envergonhou das minhas cadeias.

[[v55-1-17]]

^<<v55-1-17,17>>^ Antes, vindo ele a Roma, com muito cuidado me procurou e me achou.

[[v55-1-18]]

^<<v55-1-18,18>>^ O Senhor lhe conceda que naquele dia ache misericórdia diante do Senhor. E, quanto me  ajudou em Éfeso, melhor o sabes tu.

'''

xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[Próximo Capítulo &#62;]