include::./index.adoc[]

[[v55-2-0]]
=== 2 Timóteo, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v55-2-1]]

^<<v55-2-1,1>>^ TU, pois, meu filho, fortifica-te na graça que há em Cristo Jesus.

[[v55-2-2]]

^<<v55-2-2,2>>^ E o que de mim, entre muitas testemunhas, ouviste, confia-o a homens fiéis, que sejam idôneos para também ensinarem os outros.

[[v55-2-3]]

^<<v55-2-3,3>>^ Sofre, pois, comigo, as aflições como bom soldado de Jesus Cristo.

[[v55-2-4]]

^<<v55-2-4,4>>^ Ninguém que milita se embaraça com negócio d esta vida, a fim de agradar àquele que o alistou para a guerra.

[[v55-2-5]]

^<<v55-2-5,5>>^ E, se alguém também milita, não é coroado se não militar legitimamente.

[[v55-2-6]]

^<<v55-2-6,6>>^ O lavrador que trabalha deve ser o primeiro a gozar dos frutos.

[[v55-2-7]]

^<<v55-2-7,7>>^ Considera o que digo, porque o Senhor te dará entendimento em tudo.

[[v55-2-8]]

^<<v55-2-8,8>>^ Lembra-te de que Jesus Cristo, que  é da descendência de Davi, ressuscitou dos mortos, segundo o meu evangelho;

[[v55-2-9]]

^<<v55-2-9,9>>^ Pelo que sofro trabalhos e até prisões, como um  malfeitor; mas a palavra de Deus não está presa.

[[v55-2-10]]

^<<v55-2-10,10>>^ Portanto tudo sofro por amor dos escolhidos, para que também eles alcancem a salvação que está em Cristo Jesus com glória eterna.

[[v55-2-11]]

^<<v55-2-11,11>>^ Palavra fiel é esta : que, se morrermos com ele , também com ele  viveremos;

[[v55-2-12]]

^<<v55-2-12,12>>^ Se sofrermos, também com ele  reinaremos; se o negarmos, também ele nos negará;

[[v55-2-13]]

^<<v55-2-13,13>>^ Se formos infiéis, ele permanece fiel: não pode negar-se a si mesmo.

[[v55-2-14]]

^<<v55-2-14,14>>^ Traze estas coisas  à memória, ordenando-lhes diante do Senhor que não tenham contendas de palavras, que  para nada aproveitam e são para perversão dos ouvintes.

[[v55-2-15]]

^<<v55-2-15,15>>^ Procura apresentar-te a Deus aprovado, como  obreiro que não tem de que  se envergonhar, que maneja bem a palavra da verdade.

[[v55-2-16]]

^<<v55-2-16,16>>^ Mas evita os falatórios profanos, porque produzirão maior impiedade.

[[v55-2-17]]

^<<v55-2-17,17>>^ E a palavra desses roerá como gangrena; entre os quais são Himeneu e Fileto;

[[v55-2-18]]

^<<v55-2-18,18>>^ Os quais se desviaram da verdade, dizendo que a ressurreição era já feita, e perverteram a fé de alguns.

[[v55-2-19]]

^<<v55-2-19,19>>^ Todavia o fundamento de Deus fica firme, tendo este selo: O Senhor conhece os que são seus, e qualquer que profere o nome de Cristo aparte-se da iniquidade.

[[v55-2-20]]

^<<v55-2-20,20>>^ Ora numa grande casa não somente há vasos de ouro e de prata, mas também de pau e de barro; uns para honra, outros, porém, para desonra.

[[v55-2-21]]

^<<v55-2-21,21>>^ De sorte que, se alguém se purificar destas coisas, será vaso para honra, santificado e idôneo para uso do Senhor, e  preparado para toda a boa obra.

[[v55-2-22]]

^<<v55-2-22,22>>^ Foge também dos desejos da mocidade; e segue a justiça, a fé, a caridade, e  a paz com os que, com um  coração puro, invocam o Senhor.

[[v55-2-23]]

^<<v55-2-23,23>>^ E rejeita as questões loucas, e sem instrução, sabendo que produzem contendas.

[[v55-2-24]]

^<<v55-2-24,24>>^ E ao servo do Senhor não convém contender, mas sim ser manso para com todos, apto para ensinar, sofredor;

[[v55-2-25]]

^<<v55-2-25,25>>^ Instruindo com mansidão os que resistem, a ver  se porventura Deus lhes dará arrependimento para conhecerem a verdade,

[[v55-2-26]]

^<<v55-2-26,26>>^ E tornarem a despertar, desprendendo-se dos laços do diabo, em que à vontade dele estão presos.

'''

xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[&#60; Capítulo Anterior] | <<v55-2-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[Próximo Capítulo &#62;]