include::./index.adoc[]

[[v15-9-0]]
=== Esdras, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v15-9-1]]

^<<v15-9-1,1>>^ ACABADAS, pois, estas cousas, chegaram-se a mim os príncipes, dizendo: O povo de Israel, e os sacerdotes, e os levitas, não se têm separado dos povos destas terras, seguindo as abominações dos cananeus, dos heteus, dos ferezeus, dos jebuseus, dos amonitas, dos moabitas, dos egípcios, e dos amorreus;

[[v15-9-2]]

^<<v15-9-2,2>>^ Porque tomaram das suas filhas para si e para seus filhos, e assim  se misturou a semente santa com os povos destas terras: e até a mão dos príncipes e magistrados foi a primeira nesta transgressão.

[[v15-9-3]]

^<<v15-9-3,3>>^ E, ouvindo eu tal cousa, rasguei o meu vestido e o meu manto, e arranquei os cabelos da minha cabeça e da minha barba, e me assentei atônito.

[[v15-9-4]]

^<<v15-9-4,4>>^ Então se ajuntaram a mim todos os que tremiam das palavras do Deus de Israel por causa da transgressão dos  do cativeiro: porém eu me fiquei assentado atônito até ao sacrifício da tarde.

[[v15-9-5]]

^<<v15-9-5,5>>^ E perto do sacrifício da tarde me levantei da minha aflição, havendo já  rasgado o meu vestido e o meu manto, e me pus de joelhos, e estendi as minhas mãos para o Senhor meu Deus.

[[v15-9-6]]

^<<v15-9-6,6>>^ E disse: Meu Deus! Estou confuso e envergonhado, para levantar a ti a minha face, meu Deus: porque as nossas iniquidades se multiplicaram sobre a nossa  cabeça, e a nossa culpa tem crescido até aos céus.

[[v15-9-7]]

^<<v15-9-7,7>>^ Desde os dias de nossos pais até ao dia de  hoje estamos  em grande culpa, e por causa das nossas iniquidades fomos entregues, nós, os nossos reis, e os nossos sacerdotes, na mão dos reis das terras, à espada, ao cativeiro, e ao roubo, e à confusão do rosto, como hoje se vê.

[[v15-9-8]]

^<<v15-9-8,8>>^ E agora, como por um  pequeno momento, se nos  fez graça da parte do Senhor, nosso Deus, para nos deixar alguns que escapem, e para dar-nos uma  estaca no seu santo lugar; para nos alumiar os olhos; ó Deus nosso, e para nos dar uma pouca de vida na nossa servidão;

[[v15-9-9]]

^<<v15-9-9,9>>^ Porque servos somos ; porém na nossa servidão não nos desamparou o nosso Deus; antes estendeu sobre nós beneficência perante os reis da Pérsia, para revivermos, para levantarmos a casa do nosso Deus, e para restaurarmos as suas assolações; e para que nos desse uma  parede em Judá e em Jerusalém.

[[v15-9-10]]

^<<v15-9-10,10>>^ Agora, pois, ó nosso Deus, que diremos depois disto? Pois deixamos os teus mandamentos;

[[v15-9-11]]

^<<v15-9-11,11>>^ Os quais mandaste pelo ministério de teus servos, os profetas, dizendo: A terra em que entrais para a possuir, terra imunda é pelas imundícias dos seus povos, pelas abominações com que, na sua corrupção, a encheram, duma extremidade à outra.

[[v15-9-12]]

^<<v15-9-12,12>>^ Agora, pois, vossas filhas não dareis a seus filhos, e suas filhas não tomareis para vossos filhos, e nunca procurareis a sua paz e o seu bem; para que vos fortaleçais, e comais o bem da terra, e a façais possuir a vossos filhos para sempre.

[[v15-9-13]]

^<<v15-9-13,13>>^ E depois de tudo o que nos tem sucedido por causa das nossas más obras, e da nossa grande culpa, ainda assim tu, ó nosso Deus, estorvaste que fôssemos destruídos, por causa da nossa iniquidade, e ainda  nos deste livramento como este;

[[v15-9-14]]

^<<v15-9-14,14>>^ Tornaremos pois agora a violar os teus mandamentos, e a aparentar-nos com os povos destas abominações? Não te indignarias tu assim  contra nós até de todo nos  consumires, até que não ficasse  resto nem quem escapasse?

[[v15-9-15]]

^<<v15-9-15,15>>^ Ah! Senhor Deus de Israel, justo és , pois ficamos escapos, como hoje se vê ; eis que estamos  diante de ti no nosso delito; porque ninguém há  que possa estar na tua presença por causa disto.

'''

xref:015-esdras/015-esdras-008.adoc#v15-8-0[&#60; Capítulo Anterior] | <<v15-9-0,Topo>> | xref:015-esdras/015-esdras-010.adoc#v15-10-0[Próximo Capítulo &#62;]