include::./index.adoc[]

[[v15-1-0]]
=== Esdras, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v15-1-1]]

^<<v15-1-1,1>>^ NO primeiro ano de Ciro, rei da Pérsia (para que se cumprisse a palavra do Senhor, por boca de Jeremias) despertou o Senhor o espírito de Ciro, rei da Pérsia, o qual fez passar pregão por todo o seu reino, como também por escrito, dizendo:

[[v15-1-2]]

^<<v15-1-2,2>>^ Assim diz Ciro, rei da Pérsia: O Senhor Deus dos céus me deu todos os reinos da terra; e ele me encarregou de lhe edificar uma  casa em Jerusalém, que é  em Judá.

[[v15-1-3]]

^<<v15-1-3,3>>^ Quem há  entre vós, de todo o seu povo, seja seu Deus com ele, e suba a Jerusalém, que é  em Judá, e edifique a casa do Senhor, Deus de Israel; ele é  o Deus que habita  em Jerusalém.

[[v15-1-4]]

^<<v15-1-4,4>>^ E todo aquele que ficar em alguns lugares em que andar peregrinando, os homens do seu lugar o ajudarão com prata, e com ouro, e com fazenda e com gados, afora as dádivas voluntárias para a casa do Senhor, que habita  em Jerusalém.

[[v15-1-5]]

^<<v15-1-5,5>>^ Então se levantaram os chefes dos pais de Judá e Benjamim, e os sacerdotes e os levitas, com todos aqueles  cujo espírito Deus despertou, para subirem a edificar a casa do Senhor, que está  em Jerusalém.

[[v15-1-6]]

^<<v15-1-6,6>>^ E todos os que habitavam  nos arredores lhes confortaram as mãos com vasos de prata, com ouro, com fazenda, e com gados, e com cousas preciosas; afora tudo o que voluntariamente se deu.

[[v15-1-7]]

^<<v15-1-7,7>>^ Também o rei Ciro tirou os vasos da casa do Senhor, que Nabucodonosor tinha trazido de Jerusalém, e que tinha posto na casa de seus deuses.

[[v15-1-8]]

^<<v15-1-8,8>>^ Estes tirou Ciro, rei da Pérsia, pela mão de Mitredate, o tesoureiro, que os deu por conta a Sesbazar, príncipe de Judá.

[[v15-1-9]]

^<<v15-1-9,9>>^ E este é  o número deles: Trinta bacias de ouro, mil bacias de prata, vinte e nove facas.

[[v15-1-10]]

^<<v15-1-10,10>>^ Trinta taças de ouro, quatrocentas e dez taças de prata doutra espécie e  mil outros vasos.

[[v15-1-11]]

^<<v15-1-11,11>>^ Todos os vasos de ouro e de prata foram  cinco mil e quatrocentos: todos estes levou Sesbazar, quando os do cativeiro subiram de Babilônia para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[&#60; Capítulo Anterior] | <<v15-1-0,Topo>> | xref:015-esdras/015-esdras-002.adoc#v15-2-0[Próximo Capítulo &#62;]