include::./index.adoc[]

[[v15-6-0]]
=== Esdras, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v15-6-1]]

^<<v15-6-1,1>>^ ENTÃO o rei Dario deu ordem e buscaram na chancelaria, onde se metiam os tesouros em Babilônia.

[[v15-6-2]]

^<<v15-6-2,2>>^ E em Acmeta, no palácio, que está na província de Média, se achou um rolo e nele estava escrito um  memorial, que dizia  assim:

[[v15-6-3]]

^<<v15-6-3,3>>^ No ano primeiro do rei Ciro, o rei Ciro deu esta  ordem: Com respeito à casa de Deus em Jerusalém, esta  casa se edificará para lugar em que se ofereçam sacrifícios, e seus fundamentos serão firmes; a sua altura de sessenta côvados, e a sua largura de sessenta côvados.

[[v15-6-4]]

^<<v15-6-4,4>>^ Com  três carreiras de grandes pedras, e uma carreira de madeira nova: e a despesa se fará da casa do rei.

[[v15-6-5]]

^<<v15-6-5,5>>^ Demais disto, os vasos de ouro e de prata da casa de Deus, que Nabucodonosor transportou do templo que estava  em Jerusalém, e levou para Babilônia, se tornarão a dar, para que vão ao seu lugar, ao templo que está  em Jerusalém, e os levarão à casa de Deus.

[[v15-6-6]]

^<<v15-6-6,6>>^ Agora, pois , Tatenai, governador de além do rio, Setarboznai, e os seus companheiros, os afarsaquitas, que estais  de além do rio, apartai-vos dali.

[[v15-6-7]]

^<<v15-6-7,7>>^ Deixa- os  na obra desta casa de Deus: para que  o governador dos judeus e os judeus edifiquem esta casa de Deus no seu lugar.

[[v15-6-8]]

^<<v15-6-8,8>>^ Também por mim se decreta o que haveis de fazer com os anciãos dos judeus, para que edifiquem esta casa de Deus, a saber : Que da fazenda do rei, dos tributos dalém do rio, se pague prontamente a despesa a estes homens, para que não sejam impedidos.

[[v15-6-9]]

^<<v15-6-9,9>>^ E o que for  necessário, como bezerros, e carneiros, e cordeiros, para holocausto ao Deus dos céus, trigo, sal, vinho e azeite, segundo o rito dos sacerdotes que estão  em Jerusalém; e  dê-se-lhes de dia em dia, para que não haja  falta;

[[v15-6-10]]

^<<v15-6-10,10>>^ Para que ofereçam sacrifícios de cheiro suave ao Deus dos céus, e orem pela vida do rei e de seus filhos.

[[v15-6-11]]

^<<v15-6-11,11>>^ Também por mim se decreta que todo o homem que mudar este decreto, um madeiro se arrancará da sua casa e, levantado, o pendurarão nele, e da sua casa se fará por isso um monturo.

[[v15-6-12]]

^<<v15-6-12,12>>^ O Deus, pois, que fez habitar ali o seu nome derribe a todos os reis e povos que estenderem a sua mão para o  mudarem e  para destruírem esta casa de Deus, que está  em Jerusalém. Eu, Dario, dei o decreto; apressuradamente se execute.

[[v15-6-13]]

^<<v15-6-13,13>>^ Então Tatenai, o governador de além do rio, Setarboznai e os seus companheiros, assim fizeram apressuradamente, conforme ao que decretara o rei Dario.

[[v15-6-14]]

^<<v15-6-14,14>>^ E os anciãos dos judeus iam edificando e prosperando pela profecia do profeta Ageu, e de Zacarias, filho de Ido; e edificaram a casa  e a  aperfeiçoaram conforme ao mandado do Deus de Israel, e conforme ao mandado de Ciro e de Dario, e de Artaxerxes, rei da Pérsia.

[[v15-6-15]]

^<<v15-6-15,15>>^ E acabou-se esta casa no dia terceiro do mês de Adar, que era o sexto ano do reinado do rei Dario.

[[v15-6-16]]

^<<v15-6-16,16>>^ E os filhos de Israel, os sacerdotes, e os levitas, e o resto dos filhos do cativeiro, fizeram a consagração desta casa de Deus com alegria.

[[v15-6-17]]

^<<v15-6-17,17>>^ E ofereceram para a consagração desta casa de Deus cem novilhos, duzentos carneiros, quatrocentos cordeiros, e doze cabritos por expiação  do pecado de todo o Israel, segundo o número das tribos de Israel.

[[v15-6-18]]

^<<v15-6-18,18>>^ E puseram os sacerdotes nas suas turmas e os levitas nas suas divisões, para o ministério de Deus, que está  em Jerusalém; conforme ao escrito do livro de Moisés.

[[v15-6-19]]

^<<v15-6-19,19>>^ E os que vieram do cativeiro celebraram a páscoa no dia catorze do primeiro mês;

[[v15-6-20]]

^<<v15-6-20,20>>^ Porque os sacerdotes e levitas se tinham purificado como se fossem  um só homem , e todos estavam  limpos; e mataram o cordeiro da  páscoa para todos os filhos do cativeiro, e para seus irmãos, os sacerdotes, e para si mesmos.

[[v15-6-21]]

^<<v15-6-21,21>>^ Assim comeram a páscoa  os filhos de Israel que tinham voltado do cativeiro, com todos os que a eles se apartavam da imundícia das gentes da terra, para buscarem o Senhor, Deus de Israel;

[[v15-6-22]]

^<<v15-6-22,22>>^ E celebraram a festa dos pães asmos os sete dias com alegria, porque o Senhor os tinha alegrado e tinha mudado o coração do rei da Assíria a favor deles, para lhes fortalecer as mãos na obra da casa de Deus, o Deus de Israel.

'''

xref:015-esdras/015-esdras-005.adoc#v15-5-0[&#60; Capítulo Anterior] | <<v15-6-0,Topo>> | xref:015-esdras/015-esdras-007.adoc#v15-7-0[Próximo Capítulo &#62;]