include::./index.adoc[]

[[v15-3-0]]
=== Esdras, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v15-3-1]]

^<<v15-3-1,1>>^ CHEGANDO pois o sétimo mês, e estando  os filhos de Israel já  nas cidades, se ajuntou o povo, como um só homem, em Jerusalém.

[[v15-3-2]]

^<<v15-3-2,2>>^ E levantou-se Jesua filho de Josadaque, e seus irmãos, os sacerdotes, e Zorobabel, filho de Sealtiel, e seus irmãos, e edificaram o altar do Deus de Israel, para oferecerem sobre ele holocaustos, como está  escrito na lei de Moisés, o homem de Deus.

[[v15-3-3]]

^<<v15-3-3,3>>^ E firmaram o altar sobre as suas bases, porque o terror estava sobre eles, por causa dos povos das terras: e ofereceram sobre ele holocaustos ao Senhor, holocaustos de manhã e de tarde.

[[v15-3-4]]

^<<v15-3-4,4>>^ E celebraram a festa dos tabernáculos como está  escrito: ofereceram  holocaustos de dia em dia, por ordem, conforme ao rito, cada cousa no seu dia.

[[v15-3-5]]

^<<v15-3-5,5>>^ E depois disto o holocausto contínuo, e os das luas novas e de todas as solenidades consagradas ao Senhor; como também de qualquer que oferecia oferta voluntária ao Senhor:

[[v15-3-6]]

^<<v15-3-6,6>>^ Desde o primeiro dia do sétimo mês começaram a oferecer holocaustos ao Senhor: porém ainda  não estavam postos os fundamentos do templo do Senhor.

[[v15-3-7]]

^<<v15-3-7,7>>^ Deram pois o dinheiro aos cortadores e artífices, como também comida e bebida, e azeite aos sidônios, e aos tírios, para trazerem do Líbano madeira de cedro ao mar, para Jope, segundo a concessão que lhes tinha feito  Ciro, rei da Pérsia.

[[v15-3-8]]

^<<v15-3-8,8>>^ E no segundo ano da sua vinda à casa de Deus em Jerusalém, no segundo mês, começaram Zorobabel, filho de Sealtiel, e Jesua, filho de Josadaque, e os outros seus irmãos, os sacerdotes e os levitas, e todos os que vieram do cativeiro a Jerusalém, e constituíram levitas da idade de vinte anos e daí para cima, para que aviassem a obra da casa do Senhor.

[[v15-3-9]]

^<<v15-3-9,9>>^ Então se levantou Jesua, seus filhos, e seus irmãos, Cadmiel e seus filhos, os filhos de Judá, como um só homem, para vigiarem os que faziam a obra na casa de Deus, os filhos de Henadade, seus filhos e seus irmãos, os levitas.

[[v15-3-10]]

^<<v15-3-10,10>>^ Quando pois os edificadores lançaram os alicerces do templo do Senhor, então apresentaram-se os sacerdotes, já  revestidos e com trombetas, e os levitas, filhos de Asafe, com saltérios, para louvarem ao Senhor, conforme à instituição de Davi, rei de Israel.

[[v15-3-11]]

^<<v15-3-11,11>>^ E cantavam a revezes, louvando e celebrando ao Senhor; porque é  bom; porque a sua benignidade dura  para sempre sobre Israel. E todo o povo jubilou com grande júbilo, quando louvaram ao Senhor, pela fundação da casa do Senhor.

[[v15-3-12]]

^<<v15-3-12,12>>^ Porém muitos dos sacerdotes, e levitas e chefes dos pais, já  velhos, que viram a primeira casa, sobre o seu fundamento, vendo  perante os seus olhos esta casa, choraram em altas vozes; mas muitos levantaram as vozes com júbilo e  com alegria.

[[v15-3-13]]

^<<v15-3-13,13>>^ De maneira que não discernia o povo as vozes de alegria das vozes do choro do povo; porque o povo jubilava com tão  grande júbilo que as vozes se ouviam de mui longe.

'''

xref:015-esdras/015-esdras-002.adoc#v15-2-0[&#60; Capítulo Anterior] | <<v15-3-0,Topo>> | xref:015-esdras/015-esdras-004.adoc#v15-4-0[Próximo Capítulo &#62;]