include::./index.adoc[]

[[v15-5-0]]
=== Esdras, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v15-5-1]]

^<<v15-5-1,1>>^ E AGEU, profeta, e Zacarias, filho de Ido, profetas, profetizaram aos judeus que estavam  em Judá e em Jerusalém; em nome do Deus de Israel lhes profetizaram.

[[v15-5-2]]

^<<v15-5-2,2>>^ Então se levantaram Zorobabel, filho de Sealtiel, e Jesua, filho de Josadaque, e começaram a edificar a casa de Deus, que está  em Jerusalém; e com eles os profetas de Deus, que os ajudavam.

[[v15-5-3]]

^<<v15-5-3,3>>^ Naquele tempo veio a eles Tatenai, governador daquém do rio, e Setarboznai, e os seus companheiros, e disseram-lhes assim: Quem vos deu ordem para edificardes esta casa, e restaurardes este muro?

[[v15-5-4]]

^<<v15-5-4,4>>^ Então assim lhes dissemos: E  quais são os nomes dos homens que construíram este edifício?

[[v15-5-5]]

^<<v15-5-5,5>>^ Porém os olhos de Deus estavam sobre os anciãos dos judeus, e não os impediram, até que o negócio veio a Dario, e então responderam por carta sobre isso.

[[v15-5-6]]

^<<v15-5-6,6>>^ Cópia da carta que Tatenai, o governador daquém do rio, com Setarboznai e os seus companheiros, os afarsaquitas, que estavam  daquém do rio, enviaram ao rei Dario.

[[v15-5-7]]

^<<v15-5-7,7>>^ Enviaram-lhe uma relação; e assim estava escrito nela: Toda a paz ao rei Dario.

[[v15-5-8]]

^<<v15-5-8,8>>^ Seja notório ao rei que nós fomos à província de Judá, à casa do grande Deus, que se edifica com grandes pedras, e já  a madeira se está pondo sobre as paredes; e esta obra apressuradamente se faz, e se adianta em suas mãos.

[[v15-5-9]]

^<<v15-5-9,9>>^ Então perguntamos aos anciãos, e  assim lhes dissemos: Quem vos deu ordem para edificardes esta casa, e restaurardes este muro?

[[v15-5-10]]

^<<v15-5-10,10>>^ Demais disto, lhes perguntamos também pelos seus nomes, para tos declararmos, para que te pudéssemos escrever os nomes dos homens que são  entre eles os chefes.

[[v15-5-11]]

^<<v15-5-11,11>>^ E esta resposta nos deram, dizendo: Nós somos servos do Deus dos céus e da terra, e reedificamos a casa que foi edificada muitos anos antes; porque um grande rei de Israel a edificou e a aperfeiçoou.

[[v15-5-12]]

^<<v15-5-12,12>>^ Mas depois que nossos pais provocaram à ira o Deus dos céus, ele os entregou na mão de Nabucodonosor, rei de Babilônia, o caldeu, o qual destruiu esta casa, e transportou o seu povo para Babilônia.

[[v15-5-13]]

^<<v15-5-13,13>>^ Porém no primeiro ano de Ciro, rei de Babilônia, o rei Ciro deu ordem para que esta casa de Deus se edificasse.

[[v15-5-14]]

^<<v15-5-14,14>>^ E até os vasos de ouro e de prata, da casa de Deus, que Nabucodonosor tomou do templo que estava  em Jerusalém e os meteu no templo de Babilônia, o rei Ciro os tirou do templo de Babilônia, e foram dados a um homem cujo nome era  Sesbazar, a quem nomeou governador.

[[v15-5-15]]

^<<v15-5-15,15>>^ E disse-lhe: Toma estes vasos, vai, e  leva-os ao templo que está  em Jerusalém, e faze edificar a casa de Deus, no seu lugar.

[[v15-5-16]]

^<<v15-5-16,16>>^ Então veio o dito Sesbazar, e  pôs os fundamentos da casa de Deus, que está  em Jerusalém; e desde então para cá se está edificando, e ainda  não está acabada.

[[v15-5-17]]

^<<v15-5-17,17>>^ Agora, pois, se parece  bem ao rei, busque-se lá na casa dos tesouros do rei, que está  em Babilônia, se é verdade haver uma ordem do rei Ciro para edificar esta casa de Deus em Jerusalém; e sobre isto nos faça o rei saber a sua vontade.

'''

xref:015-esdras/015-esdras-004.adoc#v15-4-0[&#60; Capítulo Anterior] | <<v15-5-0,Topo>> | xref:015-esdras/015-esdras-006.adoc#v15-6-0[Próximo Capítulo &#62;]