include::./index.adoc[]

[[v57-1-0]]
=== Filemom, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v57-1-1]]

^<<v57-1-1,1>>^ PAULO, prisioneiro de Jesus Cristo, e o irmão Timóteo, ao amado Filemom, nosso cooperador,

[[v57-1-2]]

^<<v57-1-2,2>>^ E à nossa irmã Ápia, e a Arquipo, nosso camarada, e à igreja que está em tua casa;

[[v57-1-3]]

^<<v57-1-3,3>>^ Graça a vós e paz da parte de Deus nosso Pai, e da do Senhor Jesus Cristo.

[[v57-1-4]]

^<<v57-1-4,4>>^ Graças dou ao meu Deus, lembrando-me sempre de ti nas minhas orações;

[[v57-1-5]]

^<<v57-1-5,5>>^ Ouvindo a tua caridade e a fé que tens para com o Senhor Jesus Cristo, e para com todos os santos;

[[v57-1-6]]

^<<v57-1-6,6>>^ Para que a comunicação da tua fé seja eficaz no conhecimento de todo o bem que em vós há por Cristo Jesus.

[[v57-1-7]]

^<<v57-1-7,7>>^ Tive grande gozo e consolação da tua caridade, porque por ti, ó irmão, as entranhas dos santos foram recreadas.

[[v57-1-8]]

^<<v57-1-8,8>>^ Pelo que, ainda que tenha em Cristo grande confiança para te mandar o que te convém,

[[v57-1-9]]

^<<v57-1-9,9>>^ Todavia  peço- te  antes por caridade, sendo eu tal como sou, Paulo o velho, e também agora prisioneiro de Jesus Cristo.

[[v57-1-10]]

^<<v57-1-10,10>>^ Peço-te por meu filho Onésimo, que gerei nas minhas prisões;

[[v57-1-11]]

^<<v57-1-11,11>>^ O qual noutro tempo te foi inútil, mas agora a ti e a mim muito útil; eu to tornei a enviar.

[[v57-1-12]]

^<<v57-1-12,12>>^ E tu torna a recebê-lo como às minhas entranhas.

[[v57-1-13]]

^<<v57-1-13,13>>^ Eu bem o quisera conservar comigo, para que por ti me servisse nas prisões do evangelho;

[[v57-1-14]]

^<<v57-1-14,14>>^ Mas nada quis fazer sem o teu parecer, para que o teu benefício não fosse como por força, mas voluntário.

[[v57-1-15]]

^<<v57-1-15,15>>^ Porque bem pode ser que ele se tenha separado de ti  por algum tempo, para que o retivesses para sempre,

[[v57-1-16]]

^<<v57-1-16,16>>^ Não já como servo, antes, mais do que servo, como  irmão amado, particularmente de mim: e quanto mais de ti, assim na carne como no Senhor?

[[v57-1-17]]

^<<v57-1-17,17>>^ Assim pois, se me tens por companheiro, recebe-o como a mim mesmo.

[[v57-1-18]]

^<<v57-1-18,18>>^ E, se te fez algum dano, ou te deve alguma coisa , põe isso à minha conta.

[[v57-1-19]]

^<<v57-1-19,19>>^ Eu, Paulo, de minha própria mão o escrevi; eu o pagarei, para te não dizer que ainda mesmo a ti próprio a mim te deves.

[[v57-1-20]]

^<<v57-1-20,20>>^ Sim, irmão, eu me regozijarei de ti no Senhor: recreia as minhas entranhas no Senhor.

[[v57-1-21]]

^<<v57-1-21,21>>^ Escrevi-te confiado na tua obediência, sabendo que ainda farás mais do que digo.

[[v57-1-22]]

^<<v57-1-22,22>>^ E juntamente prepara-me também pousada, porque espero que pelas vossas orações vos hei de ser concedido.

[[v57-1-23]]

^<<v57-1-23,23>>^ Saúdam-te Epafras, meu companheiro de prisão por Cristo Jesus.

[[v57-1-24]]

^<<v57-1-24,24>>^ Marcos, Aristarco, Demas e Lucas, meus cooperadores.

[[v57-1-25]]

^<<v57-1-25,25>>^ A graça de nosso Senhor Jesus Cristo seja  com o vosso espírito. Amém.

'''

xref:056-tito/056-tito-003.adoc#v56-3-0[&#60; Capítulo Anterior] | <<v57-1-0,Topo>> | xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[Próximo Capítulo &#62;]