include::./index.adoc[]

[[v39-1-0]]
=== Malaquias, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v39-1-1]]

^<<v39-1-1,1>>^ PESO da palavra do Senhor contra Israel, pelo ministério de Malaquias.

[[v39-1-2]]

^<<v39-1-2,2>>^ Eu vos amei, diz o Senhor; mas vós dizeis: Em que nos amaste? Não foi Esaú irmão de Jacó? disse o Senhor; todavia amei a Jacó.

[[v39-1-3]]

^<<v39-1-3,3>>^ E aborreci a Esaú: e fiz dos seus montes uma assolação, e dei a sua herança aos dragões do deserto.

[[v39-1-4]]

^<<v39-1-4,4>>^ Ainda que Edom diga: Empobrecidos somos, porém tornaremos a edificar os lugares desertos, assim diz o Senhor dos Exércitos: eles edificarão, e eu destruirei: e lhes chamarão Termo de impiedade, e povo contra quem o Senhor está irado para sempre.

[[v39-1-5]]

^<<v39-1-5,5>>^ E os vossos olhos o verão, e direis: O Senhor seja engrandecido desde os termos de Israel.

[[v39-1-6]]

^<<v39-1-6,6>>^ O filho honrará o pai, e o servo ao seu senhor; e, se eu sou Pai, onde está a minha honra? e, se eu sou Senhor, onde está o meu temor? diz o Senhor dos Exércitos a vós, ó sacerdotes, que desprezais o meu nome e dissestes: Em que desprezamos nós o teu nome?

[[v39-1-7]]

^<<v39-1-7,7>>^ Ofereceis sobre o meu altar pão imundo, e dizeis: Em que te havemos profanado? Nisto que dizeis: A mesa do Senhor é desprezível.

[[v39-1-8]]

^<<v39-1-8,8>>^ Porque, quando trazeis animal  cego para o sacrificardes, não faz mal! e, quando ofereceis o coxo ou o enfermo, não faz mal! Ora apresenta-o ao teu príncipe: terá ele agrado em ti? ou aceitará ele a tua pessoa? diz o Senhor dos Exércitos.

[[v39-1-9]]

^<<v39-1-9,9>>^ Agora, pois, suplicai o favor de Deus, e ele terá piedade de nós: isto veio da vossa mão; aceitará ele a vossa pessoa? diz o Senhor dos Exércitos.

[[v39-1-10]]

^<<v39-1-10,10>>^ Quem há também entre vós que feche as portas e não acenda debalde o fogo do meu altar? Eu não tenho prazer em vós, diz o Senhor dos Exércitos, nem aceitarei da vossa mão a oblação.

[[v39-1-11]]

^<<v39-1-11,11>>^ Mas desde o nascente do sol até ao poente será grande entre as nações o meu nome; e em todo o lugar se oferecerá ao meu nome incenso e uma oblação pura; porque o meu nome será  grande entre as nações, diz o Senhor dos Exércitos.

[[v39-1-12]]

^<<v39-1-12,12>>^ Mas vós o profanais, quando dizeis: A mesa do Senhor é impura, e o seu produto, a sua comida, é desprezível.

[[v39-1-13]]

^<<v39-1-13,13>>^ E dizeis: Eis aqui, que canseira! e o lançastes ao desprezo, diz o Senhor dos Exércitos: vós ofereceis o roubado, e o coxo e o enfermo; assim fazeis a oferta: ser-me-á aceito isto de vossa mão? diz o Senhor.

[[v39-1-14]]

^<<v39-1-14,14>>^ Pois maldito seja o enganador que, tendo animal no seu rebanho, promete e oferece ao Senhor uma cousa vil; porque eu sou grande Rei, diz o Senhor dos Exércitos, o meu nome será tremendo entre as nações.

'''

xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[&#60; Capítulo Anterior] | <<v39-1-0,Topo>> | xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[Próximo Capítulo &#62;]