include::./index.adoc[]

[[v39-4-0]]
=== Malaquias, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v39-4-1]]

^<<v39-4-1,1>>^ PORQUE eis que aquele dia vem ardendo como forno: todos os soberbos, e todos os que cometem impiedade, serão como palha; e o dia que está para vir os abrasará, diz o Senhor dos Exércitos, de sorte que lhes não deixará nem raiz nem ramo.

[[v39-4-2]]

^<<v39-4-2,2>>^ Mas para vós, que temeis o meu nome nascerá o sol da justiça, e salvação trará debaixo das suas asas; e saireis, e crescereis como os bezerros do cevadouro.

[[v39-4-3]]

^<<v39-4-3,3>>^ E pisareis os ímpios, porque se farão cinza debaixo das plantas de vossos pés naquele dia que farei, diz o Senhor dos Exércitos.

[[v39-4-4]]

^<<v39-4-4,4>>^ Lembrai-vos da lei de Moisés, meu servo, a qual lhe mandei em Horebe para todo o Israel, e que são os estatutos e juízos.

[[v39-4-5]]

^<<v39-4-5,5>>^ Eis que eu vos envio o profeta Elias, antes que venha o dia grande e terrível do Senhor;

[[v39-4-6]]

^<<v39-4-6,6>>^ E converterá o coração dos pais aos filhos, e o coração dos filhos a seus pais; para que eu não venha, e fira a terra com maldição.

'''

xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[&#60; Capítulo Anterior] | <<v39-4-0,Topo>> | xref:040-mateus/040-mateus-001.adoc#v40-1-0[Próximo Capítulo &#62;]