include::./index.adoc[]

[[v5-22-0]]
=== Deuteronômio, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-22-1]]

^<<v5-22-1,1>>^ VENDO extraviado o boi ou ovelha de teu irmão, não te esconderás deles: restituí-los-ás sem falta a teu irmão.

[[v5-22-2]]

^<<v5-22-2,2>>^ E se teu irmão não estiver  perto de ti, ou tu o não conheceres, recolhê-los-ás na tua casa, para que fiquem contigo, até que teu irmão os busque, e tu lhos tornarás a dar.

[[v5-22-3]]

^<<v5-22-3,3>>^ Assim também farás com o seu jumento, e assim farás com os seus vestidos; assim farás também com toda a cousa perdida, que se perder de teu irmão, e tu a achares; não te poderás esconder.

[[v5-22-4]]

^<<v5-22-4,4>>^ O jumento de teu irmão, ou o seu boi, não verás caídos no caminho, e deles te esconderás: com ele os levantarás sem falta.

[[v5-22-5]]

^<<v5-22-5,5>>^ Não haverá trajo de homem na mulher, e não vestirá o homem vestido de mulher: porque, qualquer que faz isto abominação é  ao Senhor teu Deus.

[[v5-22-6]]

^<<v5-22-6,6>>^ Quando encontrares algum  ninho de ave no caminho em alguma árvore, ou no chão, com passarinhos, ou ovos, e a mãe posta sobre os passarinhos, ou sobre os ovos, não tomarás a mãe com os filhos;

[[v5-22-7]]

^<<v5-22-7,7>>^ Deixarás ir livremente a mãe, e os filhos tomarás para ti; para que bem te vá, e para que  prolongues os  dias.

[[v5-22-8]]

^<<v5-22-8,8>>^ Quando edificares uma  casa nova, farás no teu telhado um parapeito, para que não ponhas culpa de sangue na tua casa, se alguém dalguma maneira cair dela.

[[v5-22-9]]

^<<v5-22-9,9>>^ Não semearás a tua vinha de diferentes espécies de semente, para que se não profane o fruto da semente que semeares, e a novidade da vinha.

[[v5-22-10]]

^<<v5-22-10,10>>^ Com boi e com jumento juntamente não lavrarás.

[[v5-22-11]]

^<<v5-22-11,11>>^ Não te vestirás de diversos estofos de lã e linho juntamente.

[[v5-22-12]]

^<<v5-22-12,12>>^ Franjas porás nas quatro bordas da tua manta, com que te cobrires.

[[v5-22-13]]

^<<v5-22-13,13>>^ Quando um homem tomar mulher e, entrando a ela, a aborrecer,

[[v5-22-14]]

^<<v5-22-14,14>>^ E lhe imputar cousas escandalosas, e contra ela divulgar má fama, dizendo: Tomei esta mulher, e me cheguei a ela, porém não a achei virgem;

[[v5-22-15]]

^<<v5-22-15,15>>^ Então o pai da moça e sua mãe tomarão os sinais  da virgindade da moça, e levá-los-ão para fora aos anciãos da cidade, à porta:

[[v5-22-16]]

^<<v5-22-16,16>>^ E o pai da moça dirá aos anciãos: Eu dei minha filha por mulher a este homem, porém ele a aborreceu;

[[v5-22-17]]

^<<v5-22-17,17>>^ E eis que lhe imputou cousas escandalosas, dizendo: Não achei virgem tua filha; porém eis aqui os sinais da  virgindade de minha filha. E estenderão o lençol diante dos anciãos da cidade.

[[v5-22-18]]

^<<v5-22-18,18>>^ Então os anciãos da mesma cidade tomarão aquele homem, e o castigarão,

[[v5-22-19]]

^<<v5-22-19,19>>^ E o condenarão em cem siclos  de prata, e os darão ao pai da moça; porquanto divulgou má fama sobre uma virgem de Israel. E lhe será por mulher, em todos os seus dias não a poderá despedir.

[[v5-22-20]]

^<<v5-22-20,20>>^ Porém se este negócio for verdade, que a virgindade se não achou na moça,

[[v5-22-21]]

^<<v5-22-21,21>>^ Então levarão a moça à porta da casa de seu pai, e os homens da sua cidade a apedrejarão com pedras, até que morra; pois fez loucura em Israel, prostituindo-se na casa de seu pai: assim tirarás o mal do meio de ti.

[[v5-22-22]]

^<<v5-22-22,22>>^ Quando um homem for achado deitado com mulher casada com marido, então ambos morrerão, o homem que se deitou com a mulher, e a mulher: assim tirarás o mal de Israel.

[[v5-22-23]]

^<<v5-22-23,23>>^ Quando houver moça virgem, desposada com algum homem, e um homem a achar na cidade, e se deitar com ela,

[[v5-22-24]]

^<<v5-22-24,24>>^ Então trareis ambos à porta daquela cidade, e os apedrejareis com pedras, até que morram; a moça, porquanto não gritou na cidade, e o homem, porquanto humilhou a mulher do seu próximo: assim tirarás o mal do meio de ti.

[[v5-22-25]]

^<<v5-22-25,25>>^ E se algum homem no campo achar uma moça desposada, e o homem a forçar, e se deitar com ela, então morrerá só o homem que se deitou com ela;

[[v5-22-26]]

^<<v5-22-26,26>>^ Porém à moça não farás nada: a moça não tem culpa de morte; porque, como o homem que se levanta contra o seu próximo, e lhe tira a vida, assim é  este negócio.

[[v5-22-27]]

^<<v5-22-27,27>>^ Pois a achou no campo: a moça desposada gritou, e não houve quem a livrasse.

[[v5-22-28]]

^<<v5-22-28,28>>^ Quando um homem achar uma moça virgem, que não for desposada, e pegar nela, e se deitar com ela, e forem apanhados,

[[v5-22-29]]

^<<v5-22-29,29>>^ Então o homem que se deitou com ela dará ao pai da moça cinquenta siclos  de prata: e porquanto a humilhou, lhe será por mulher: não a poderá despedir em todos os seus dias.

[[v5-22-30]]

^<<v5-22-30,30>>^ Nenhum homem tomará a mulher de seu pai, nem descobrirá a ourela de seu pai.

'''

xref:005-deuteronomio/005-deuteronomio-021.adoc#v5-21-0[&#60; Capítulo Anterior] | <<v5-22-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[Próximo Capítulo &#62;]