include::./index.adoc[]

[[v5-15-0]]
=== Deuteronômio, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-15-1]]

^<<v5-15-1,1>>^ AO fim dos sete anos farás remissão.

[[v5-15-2]]

^<<v5-15-2,2>>^ Este pois é  o modo da remissão: Que  todo o credor, que emprestou ao seu próximo uma  cousa, o quite: não a  exigirá do seu próximo ou do seu irmão, pois a remissão do Senhor é apregoada.

[[v5-15-3]]

^<<v5-15-3,3>>^ Do estranho a  exigirás: mas o  que tiveres em poder de teu irmão a tua mão o quitará:

[[v5-15-4]]

^<<v5-15-4,4>>^ Somente para que entre ti não haja pobre: pois o Senhor abundantemente te abençoará na terra que o Senhor teu Deus te dará por herança, para possuí-la.

[[v5-15-5]]

^<<v5-15-5,5>>^ Se somente ouvires diligentemente a voz do Senhor teu Deus para cuidares em fazer todos estes mandamentos que hoje te ordeno:

[[v5-15-6]]

^<<v5-15-6,6>>^ Porque o Senhor teu Deus te abençoará, como te tem dito: assim, emprestarás a muitas nações, mas não tomarás empréstimos: e dominarás sobre muitas nações, mas elas não dominarão sobre ti.

[[v5-15-7]]

^<<v5-15-7,7>>^ Quando entre ti houver algum pobre de teus irmãos, em alguma das tuas portas, na tua terra que o Senhor teu Deus te dá, não endurecerás o teu coração, nem fecharás a tua mão a teu irmão que for  pobre.

[[v5-15-8]]

^<<v5-15-8,8>>^ Antes lhe abrirás de todo a tua mão, e livremente lhe emprestarás o que lhe falta, quanto baste para a sua necessidade.

[[v5-15-9]]

^<<v5-15-9,9>>^ Guarda-te, que não haja palavra de Belial no teu coração, dizendo: Vai-se aproximando o sétimo ano, o ano da remissão: e que o teu olho seja maligno para com teu irmão pobre, e não lhe dês nada; e que ele  clame contra ti ao Senhor, e que haja em ti pecado.

[[v5-15-10]]

^<<v5-15-10,10>>^ Livremente lhe darás, e que  o teu coração não seja maligno, quando lhe deres: pois por esta causa te abençoará o Senhor teu Deus em toda a tua obra, e em tudo no que puseres a tua mão.

[[v5-15-11]]

^<<v5-15-11,11>>^ Pois nunca cessará o pobre do meio da terra: pelo que te ordeno, dizendo: Livremente abrirás a tua mão para o teu irmão, para o teu necessitado, e para o teu pobre na tua terra.

[[v5-15-12]]

^<<v5-15-12,12>>^ Quando teu irmão hebreu ou irmã  hebreia se vender a ti, seis anos te servirá, mas no sétimo ano o despedirás forro de ti.

[[v5-15-13]]

^<<v5-15-13,13>>^ E, quando o despedires de ti forro, não o despedirás vazio.

[[v5-15-14]]

^<<v5-15-14,14>>^ Liberalmente o fornecerás do teu rebanho, e da tua eira, e do teu lagar: daquilo com que o Senhor teu Deus te tiver abençoado lhe darás.

[[v5-15-15]]

^<<v5-15-15,15>>^ E lembrar-te-ás de que foste servo na terra do Egito, e de que o Senhor teu Deus te resgatou: pelo que te ordeno hoje esta cousa.

[[v5-15-16]]

^<<v5-15-16,16>>^ Porém será que, dizendo-te ele: Não sairei de ti; porquanto te ama a ti e a tua casa, por estar bem contigo:

[[v5-15-17]]

^<<v5-15-17,17>>^ Então tomarás uma sovela, e lhe furarás a orelha, à porta, e teu servo será para sempre: e também assim farás à tua serva.

[[v5-15-18]]

^<<v5-15-18,18>>^ Não seja aos teus olhos cousa dura, quando o despedires forro de ti; pois seis anos te serviu em dobro do salário do jornaleiro: assim o Senhor teu Deus te abençoará em tudo o que fizeres.

[[v5-15-19]]

^<<v5-15-19,19>>^ Todo o primogênito que nascer entre as tuas vacas e entre as tuas ovelhas, o macho santificarás ao Senhor teu Deus: com o primogênito do teu boi não trabalharás, nem tosquiarás o primogênito das tuas ovelhas.

[[v5-15-20]]

^<<v5-15-20,20>>^ Perante o Senhor teu Deus os comerás de ano em ano, no lugar que o Senhor escolher, tu e a tua casa.

[[v5-15-21]]

^<<v5-15-21,21>>^ Porém, havendo nele algum  defeito, se for  coxo, ou cego, ou tiver  qualquer defeito, não sacrificarás ao Senhor teu Deus.

[[v5-15-22]]

^<<v5-15-22,22>>^ Nas tuas portas o comerás: o imundo e o limpo o comerão  juntamente, como da corça ou do veado.

[[v5-15-23]]

^<<v5-15-23,23>>^ Somente o seu sangue não comerás: sobre a terra o derramarás como água.

'''

xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[&#60; Capítulo Anterior] | <<v5-15-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[Próximo Capítulo &#62;]