include::./index.adoc[]

[[v5-10-0]]
=== Deuteronômio, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-10-1]]

^<<v5-10-1,1>>^ NAQUELE mesmo tempo me disse o Senhor: Alisa duas tábuas de pedra, como as primeiras, e sobe a mim a este monte, e faze uma arca de madeira:

[[v5-10-2]]

^<<v5-10-2,2>>^ E naquelas tábuas escreverei as palavras que estavam nas primeiras tábuas que quebraste, e as porás na arca.

[[v5-10-3]]

^<<v5-10-3,3>>^ Assim, fiz uma arca de madeira de  cetim, e alisei duas tábuas de pedra, como as primeiras: e subi ao monte com as duas tábuas na minha mão.

[[v5-10-4]]

^<<v5-10-4,4>>^ Então escreveu nas tábuas, conforme à primeira escritura, os dez mandamentos, que o Senhor vos falara no dia da congregação, no monte, do meio do fogo: e o Senhor mas deu a mim.

[[v5-10-5]]

^<<v5-10-5,5>>^ E virei-me, e desci do monte, e pus as tábuas na arca que fizera: e ali estão, como o Senhor me ordenou.

[[v5-10-6]]

^<<v5-10-6,6>>^ E partiram os filhos de Israel de Beerote-Bene-Jaacã a Moserá: ali faleceu Aarão, e ali foi sepultado, e Eleazar, seu filho, administrou o sacerdócio em seu lugar.

[[v5-10-7]]

^<<v5-10-7,7>>^ Dali partiram a Gudgode, e de Gudgode a Jotbá, terra de ribeiros de águas.

[[v5-10-8]]

^<<v5-10-8,8>>^ No mesmo tempo o Senhor separou a tribo de Levi, para levar a arca do concerto do Senhor, para estar diante do Senhor, para o servir, e para abençoar em seu nome até ao dia de  hoje.

[[v5-10-9]]

^<<v5-10-9,9>>^ Pelo que Levi com seus irmãos não tem parte na herança: o Senhor é a sua herança, como o Senhor teu Deus lhe tem dito.

[[v5-10-10]]

^<<v5-10-10,10>>^ E eu estive no monte, como nos dias primeiros, quarenta dias e quarenta noites: e o Senhor me ouviu ainda por  esta vez: não quis o Senhor destruir-te.

[[v5-10-11]]

^<<v5-10-11,11>>^ Porém o Senhor me disse: Levanta-te, põe-te a caminho diante do povo, para que entrem, e possuam a terra que jurei a seus pais dar-lhes.

[[v5-10-12]]

^<<v5-10-12,12>>^ Agora pois, ó Israel, que é o que  o Senhor teu Deus pede de ti, senão que temas o Senhor teu Deus, que andes em todos os seus caminhos, e o ames, e sirvas ao Senhor teu Deus com todo o teu coração e com toda a tua alma,

[[v5-10-13]]

^<<v5-10-13,13>>^ Para guardares os mandamentos do Senhor, e os seus estatutos, que hoje te ordeno, para o teu bem?

[[v5-10-14]]

^<<v5-10-14,14>>^ Eis que os céus e os céus dos céus são  do Senhor teu Deus, a terra e tudo o que nela há.

[[v5-10-15]]

^<<v5-10-15,15>>^ Tão somente o Senhor tomou prazer em teus pais para os amar: e a vós, semente deles, escolheu depois deles, de todos os povos, como neste dia se vê.

[[v5-10-16]]

^<<v5-10-16,16>>^ Circuncidai pois o prepúcio do vosso coração, e não mais endureçais a vossa cerviz.

[[v5-10-17]]

^<<v5-10-17,17>>^ Pois o Senhor vosso Deus é  o Deus dos deuses, e o Senhor dos senhores, o Deus grande, poderoso e terrível, que não faz acepção de pessoas, nem aceita recompensas:

[[v5-10-18]]

^<<v5-10-18,18>>^ Que faz justiça ao órfão e à viúva, e ama o estrangeiro, dando-lhe pão e vestido.

[[v5-10-19]]

^<<v5-10-19,19>>^ Pelo que amareis o estrangeiro, pois fostes estrangeiros na terra do Egito.

[[v5-10-20]]

^<<v5-10-20,20>>^ Ao Senhor teu Deus temerás, a ele servirás, e a ele te chegarás, e pelo seu nome jurarás.

[[v5-10-21]]

^<<v5-10-21,21>>^ Ele é  o teu louvor e o teu Deus, que te fez estas grandes e terríveis cousas que os teus olhos têm visto.

[[v5-10-22]]

^<<v5-10-22,22>>^ Com setenta almas teus pais desceram ao Egito; e agora o Senhor teu Deus te pôs como as estrelas dos céus em multidão.

'''

xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[&#60; Capítulo Anterior] | <<v5-10-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[Próximo Capítulo &#62;]