include::./index.adoc[]

[[v5-4-0]]
=== Deuteronômio, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-4-1]]

^<<v5-4-1,1>>^ AGORA, pois, ó Israel, ouve os estatutos e os juízos que eu vos ensino, para os cumprirdes: para que vivais, e entreis, e possuais a terra que o Senhor Deus de vossos pais vos dá.

[[v5-4-2]]

^<<v5-4-2,2>>^ Não acrescentareis à palavra que vos mando, nem diminuireis dela, para que guardeis os mandamentos do Senhor vosso Deus, que eu vos mando.

[[v5-4-3]]

^<<v5-4-3,3>>^ Os vossos olhos têm visto o que Deus fez por causa de Baal-Peor: pois a todo o homem que seguiu a Baal-Peor o Senhor teu Deus consumiu do meio de ti.

[[v5-4-4]]

^<<v5-4-4,4>>^ Porém vós, que vos chegastes ao Senhor vosso Deus, hoje todos estais  vivos.

[[v5-4-5]]

^<<v5-4-5,5>>^ Vedes aqui vos tenho ensinado estatutos e juízos, como me mandou o Senhor meu Deus: para que assim façais no meio da terra a qual ides a herdar.

[[v5-4-6]]

^<<v5-4-6,6>>^ Guardai-os pois, e fazei-os, porque esta será  a vossa sabedoria e o vosso entendimento perante os olhos dos povos, que ouvirão todos estes estatutos, e dirão: Este grande povo só é  gente sábia e entendida.

[[v5-4-7]]

^<<v5-4-7,7>>^ Porque, que gente há tão  grande, que tenha deuses tão  chegados como o Senhor nosso Deus, todas as vezes  que o chamamos?

[[v5-4-8]]

^<<v5-4-8,8>>^ E que gente há tão  grande, que tenha estatutos e juízos tão  justos como toda esta lei que hoje dou perante vós?

[[v5-4-9]]

^<<v5-4-9,9>>^ Tão somente guarda-te a ti mesmo, e guarda bem a tua alma, que te não esqueças daquelas cousas que os teus olhos têm visto, e se não apartem do teu coração todos os dias da tua vida: e as farás saber a teus filhos, e aos filhos de teus filhos:

[[v5-4-10]]

^<<v5-4-10,10>>^ O dia em que estiveste perante o Senhor teu Deus em Horebe, quando o Senhor me disse: Ajunta-me este povo, e os farei ouvir as minhas palavras, e aprendê-las-ão, para me temerem todos os dias que na terra viverem, e as  ensinarão a seus filhos;

[[v5-4-11]]

^<<v5-4-11,11>>^ E vós vos chegastes, e vos pusestes ao pé do monte: e o monte ardia em fogo até ao meio dos céus e havia  trevas, e nuvens e escuridão;

[[v5-4-12]]

^<<v5-4-12,12>>^ Então o Senhor vos falou do meio do fogo: a voz das palavras ouvistes; porém, além da voz, não vistes semelhança nenhuma.

[[v5-4-13]]

^<<v5-4-13,13>>^ Então vos anunciou ele o seu concerto que vos prescreveu, os dez mandamentos, e os escreveu em duas tábuas de pedra.

[[v5-4-14]]

^<<v5-4-14,14>>^ Também o Senhor me ordenou ao mesmo tempo que vos ensinasse estatutos e juízos, para que os fizésseis na terra a qual passais a possuir.

[[v5-4-15]]

^<<v5-4-15,15>>^ Guardai pois com diligência as vossas almas, pois semelhança nenhuma vistes no dia em que o Senhor vosso Deus em Horebe falou convosco do meio do fogo;

[[v5-4-16]]

^<<v5-4-16,16>>^ Para que não vos  corrompais, e vos façais alguma escultura, semelhança de imagem, figura de macho ou de fêmea;

[[v5-4-17]]

^<<v5-4-17,17>>^ Figura dalgum animal que haja  na terra: figura dalguma ave alígera que voa pelos céus;

[[v5-4-18]]

^<<v5-4-18,18>>^ Figura dalgum animal  que anda de rastos sobre a terra; figura dalgum peixe que esteja  nas águas debaixo da terra;

[[v5-4-19]]

^<<v5-4-19,19>>^ E não levantes os teus olhos aos céus e vejas o sol, e a lua, e as estrelas, todo o exército dos céus, e sejas impelido a que te inclines perante eles, e sirvas àqueles que o Senhor teu Deus repartiu a todos os povos debaixo de todos os céus.

[[v5-4-20]]

^<<v5-4-20,20>>^ Mas o Senhor vos tomou, e vos tirou do forno de ferro do Egito, para que lhe sejais por povo hereditário, como neste dia se vê.

[[v5-4-21]]

^<<v5-4-21,21>>^ Também o Senhor se indignou contra mim por  causa das vossas palavras, e jurou que eu não passaria o Jordão, e que não entraria na boa terra que o Senhor teu Deus te dará por herança.

[[v5-4-22]]

^<<v5-4-22,22>>^ Porque eu nesta terra morrerei, não passarei o Jordão: porém vós o  passareis, e possuireis aquela boa terra.

[[v5-4-23]]

^<<v5-4-23,23>>^ Guardai-vos de que vos esqueçais do concerto do Senhor vosso Deus, que tem feito convosco, e vos façais alguma escultura, imagem dalguma cousa  que o Senhor vosso Deus vos proibiu.

[[v5-4-24]]

^<<v5-4-24,24>>^ Porque o Senhor teu Deus é  um fogo que consome, um Deus zeloso.

[[v5-4-25]]

^<<v5-4-25,25>>^ Quando pois gerardes filhos, e filhos de filhos, e vos envelhecerdes na terra e vos  corromperdes, e fizerdes alguma  escultura, semelhança dalguma cousa, e fizerdes mal aos olhos do Senhor, para o provocar à ira:

[[v5-4-26]]

^<<v5-4-26,26>>^ Hoje tomo por testemunhas contra vós o céu e a terra, que certamente perecereis depressa da terra, a qual, passado o Jordão, ides possuir: não prolongareis os vossos  dias nela, antes sereis de todo destruídos.

[[v5-4-27]]

^<<v5-4-27,27>>^ E o Senhor vos espalhará entre os povos, e ficareis poucos em número entre as gentes, às quais o Senhor vos conduzirá.

[[v5-4-28]]

^<<v5-4-28,28>>^ E ali servireis a deuses que são obra de mãos de homens, madeira e pedra, que não veem nem ouvem, nem comem nem cheiram.

[[v5-4-29]]

^<<v5-4-29,29>>^ Então dali buscarás ao Senhor teu Deus, e o  acharás, quando o buscares de todo o teu coração e de toda a tua alma.

[[v5-4-30]]

^<<v5-4-30,30>>^ Quando estiveres  em angústia, e todas estas cousas te alcançarem, então no fim de dias te virarás para o Senhor teu Deus, e ouvirás a sua voz.

[[v5-4-31]]

^<<v5-4-31,31>>^ Porquanto o Senhor teu Deus é  Deus misericordioso; e não te desamparará, nem te destruirá, nem se esquecerá do concerto que jurou a teus pais.

[[v5-4-32]]

^<<v5-4-32,32>>^ Porque, pergunta agora aos tempos passados, que te precederam desde o dia em que Deus criou o homem sobre a terra, desde uma extremidade do céu até à outra, se sucedeu jamais cousa tão grande como esta, ou se se ouviu cousa  como esta?

[[v5-4-33]]

^<<v5-4-33,33>>^ Ou se algum  povo ouviu a voz de Deus falando do meio do fogo, como tu a ouviste, ficando vivo?

[[v5-4-34]]

^<<v5-4-34,34>>^ Ou se um Deus intentou ir tomar para si um povo do meio de outro  povo com provas, com sinais, e com milagres, e com peleja, e com mão forte, e com braço estendido e com grandes espantos, conforme a tudo quanto o Senhor vosso Deus vos fez no Egito aos vossos olhos?

[[v5-4-35]]

^<<v5-4-35,35>>^ A ti te foi mostrado para que soubesses que o Senhor é Deus: nenhum outro há  senão ele.

[[v5-4-36]]

^<<v5-4-36,36>>^ Desde os céus te fez ouvir a sua voz, para te ensinar e sobre a terra te mostrou o seu grande fogo, e ouviste as suas palavras do meio do fogo.

[[v5-4-37]]

^<<v5-4-37,37>>^ E, porquanto amava teus pais, e escolhera a sua semente depois, deles, te tirou do Egito diante de si, com a sua grande força;

[[v5-4-38]]

^<<v5-4-38,38>>^ Para lançar fora de diante de ti gentes maiores e mais poderosas do que tu, para te introduzir na terra e ta dar por  herança, como neste dia se vê.

[[v5-4-39]]

^<<v5-4-39,39>>^ Pelo que hoje saberás, e refletirás no teu coração, que só o Senhor é Deus em cima no céu, e em baixo na terra; nenhum outro há.

[[v5-4-40]]

^<<v5-4-40,40>>^ E guardarás os  seus estatutos e os seus mandamentos, que te ordeno hoje, para que bem te vá a ti, e a teus filhos depois de ti, e para que prolongues os dias na terra que o Senhor teu Deus te dá para todo o sempre.

[[v5-4-41]]

^<<v5-4-41,41>>^ Então Moisés separou três cidades daquém do Jordão, da banda do nascimento do sol;

[[v5-4-42]]

^<<v5-4-42,42>>^ Para que ali se acolhesse o homicida que por erro matasse o seu próximo a quem dantes não tivesse ódio algum: e se acolhesse a uma destas cidades, e vivesse;

[[v5-4-43]]

^<<v5-4-43,43>>^ A Bezer, no deserto, na terra plana, para os rubenitas; e a Ramote, em Gileade, para os gaditas; e a Golã em Basã, para os manassitas.

[[v5-4-44]]

^<<v5-4-44,44>>^ Esta é  pois a lei que Moisés propôs aos filhos de Israel.

[[v5-4-45]]

^<<v5-4-45,45>>^ Estes são  os testemunhos, e os estatutos, e os juízos, que Moisés falou aos filhos de Israel, havendo saído do Egito;

[[v5-4-46]]

^<<v5-4-46,46>>^ Daquém do Jordão, no vale defronte de Bete-Peor, na terra de Seom, rei dos amorreus, que habitava em Hesbom: a quem feriu Moisés e os filhos de Israel, havendo eles saído do Egito.

[[v5-4-47]]

^<<v5-4-47,47>>^ E tomaram a sua terra em possessão, como também a terra de Ogue, rei de Basã, dois reis dos amorreus, que estavam  daquém do Jordão, da banda do nascimento do sol;

[[v5-4-48]]

^<<v5-4-48,48>>^ Desde Aroer, que está  à borda do ribeiro de Arnom, até ao monte de Siom, que é  Hermom,

[[v5-4-49]]

^<<v5-4-49,49>>^ E toda a campina daquém do Jordão, da banda do oriente, até ao mar da campina, abaixo de Asdote-Pisga.

'''

xref:005-deuteronomio/005-deuteronomio-003.adoc#v5-3-0[&#60; Capítulo Anterior] | <<v5-4-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-005.adoc#v5-5-0[Próximo Capítulo &#62;]