include::./index.adoc[]

[[v5-11-0]]
=== Deuteronômio, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-11-1]]

^<<v5-11-1,1>>^ AMARÁS pois ao Senhor teu Deus, e guardarás a sua observância, e os seus estatutos, e os seus juízos, e os seus mandamentos, todos os dias.

[[v5-11-2]]

^<<v5-11-2,2>>^ E hoje sabereis que falo , não com vossos filhos, que o não sabem, e não viram a instrução do Senhor vosso Deus, a sua grandeza, a sua mão forte, e o seu braço estendido;

[[v5-11-3]]

^<<v5-11-3,3>>^ Nem tão pouco os seus sinais, nem os seus feitos, que fez no meio do Egito a Faraó, rei do Egito, e a toda a sua terra;

[[v5-11-4]]

^<<v5-11-4,4>>^ Nem o que fez ao exército dos egípcios, aos seus cavalos e aos seus carros, fazendo passar sobre eles as águas do Mar Vermelho quando vos perseguiam: e o Senhor os destruiu até ao dia de  hoje;

[[v5-11-5]]

^<<v5-11-5,5>>^ Nem o que vos fez no deserto, até que chegastes a este lugar;

[[v5-11-6]]

^<<v5-11-6,6>>^ E o que fez a Datã e a Abirão, filhos de Eliabe, filho de Rúben: como a terra abriu a sua boca e os tragou com as suas casas e com as suas tendas, como também tudo o que subsistia, e lhes pertencia, no meio de todo o Israel;

[[v5-11-7]]

^<<v5-11-7,7>>^ Porquanto os vossos olhos são  os que viram toda a grande obra que fez o Senhor.

[[v5-11-8]]

^<<v5-11-8,8>>^ Guardai pois todos os mandamentos que eu vos ordeno hoje, para que vos esforceis, e entreis, e possuais a terra que passais a possuir;

[[v5-11-9]]

^<<v5-11-9,9>>^ E para que prolongueis os dias na terra que o Senhor jurou a vossos pais dá-la a eles e à sua semente, terra que mana leite e mel.

[[v5-11-10]]

^<<v5-11-10,10>>^ Porque a terra que entras a possuir não é  como a terra do Egito, donde saístes, em que semeavas a tua semente, e a regavas com o teu pé, como a uma horta.

[[v5-11-11]]

^<<v5-11-11,11>>^ Mas a terra que passais a possuir é  terra de montes e de vales: da chuva dos céus beberá as águas:

[[v5-11-12]]

^<<v5-11-12,12>>^ Terra de que o Senhor teu Deus tem cuidado: os olhos do Senhor teu Deus estão  sobre ela continuamente, desde o princípio até ao fim do ano.

[[v5-11-13]]

^<<v5-11-13,13>>^ E será que, se diligentemente obedecerdes a meus mandamentos que hoje te ordeno, de amar ao Senhor teu Deus e de o servir de todo o teu coração e de toda a tua alma,

[[v5-11-14]]

^<<v5-11-14,14>>^ Então darei a chuva da vossa terra a seu tempo, a temporã e a serôdia, para que recolhas o teu grão, e o teu mosto e o teu azeite.

[[v5-11-15]]

^<<v5-11-15,15>>^ E darei erva no teu campo aos teus gados, e comerás, e fartar-te-ás.

[[v5-11-16]]

^<<v5-11-16,16>>^ Guardai-vos, que o vosso coração não se engane, e vos desvieis, e sirvais a outros deuses, e vos inclineis perante eles:

[[v5-11-17]]

^<<v5-11-17,17>>^ E a ira do Senhor se acenda contra vós, e feche ele os céus, e não haja água, e a terra não dê a sua novidade, e cedo pereçais da boa terra que o Senhor vos dá.

[[v5-11-18]]

^<<v5-11-18,18>>^ Ponde pois estas minhas palavras no vosso coração e na vossa alma e atai-as por sinal na vossa mão, para que estejam por testeiras entre os vossos olhos,

[[v5-11-19]]

^<<v5-11-19,19>>^ E ensinai-as a vossos filhos, falando delas assentado em tua casa, e andando pelo caminho, e deitando-te, e levantando-te;

[[v5-11-20]]

^<<v5-11-20,20>>^ E escreve-as nos umbrais de tua casa, e nas tuas portas:

[[v5-11-21]]

^<<v5-11-21,21>>^ Para que se multipliquem os vossos dias e os dias de vossos filhos na terra que o Senhor jurou a vossos pais dar-lhes, como os dias dos céus sobre a terra.

[[v5-11-22]]

^<<v5-11-22,22>>^ Porque, se diligentemente guardardes todos estes mandamentos que vos ordeno para os guardardes, amando ao Senhor vosso Deus, andando em todos os seus caminhos, e a ele vos achegardes.

[[v5-11-23]]

^<<v5-11-23,23>>^ Também o Senhor de diante de vós lançará fora todas estas nações, e possuireis nações maiores e mais poderosas do que vós.

[[v5-11-24]]

^<<v5-11-24,24>>^ Todo o lugar que pisar a planta do vosso pé será vosso: desde o deserto, e desde  o Líbano, desde o rio, o rio Eufrates, até ao mar ocidental, será o vosso termo.

[[v5-11-25]]

^<<v5-11-25,25>>^ Ninguém subsistirá diante de vós: o Senhor vosso Deus porá sobre toda a terra que pisardes o vosso terror e o vosso temor como já vos tem dito.

[[v5-11-26]]

^<<v5-11-26,26>>^ Eis que hoje eu ponho diante de vós a bênção e a maldição:

[[v5-11-27]]

^<<v5-11-27,27>>^ A bênção, quando ouvirdes os mandamentos do Senhor vosso Deus, que hoje vos mando;

[[v5-11-28]]

^<<v5-11-28,28>>^ Porém a maldição, se não ouvirdes os mandamentos do Senhor vosso Deus, e vos desviardes do caminho que hoje vos ordeno, para seguirdes outros deuses que não conhecestes.

[[v5-11-29]]

^<<v5-11-29,29>>^ E será que, havendo-te o Senhor teu Deus introduzido na terra, a que vais para possuí-la, então pronunciarás a bênção sobre o monte de Gerizim, e a maldição sobre o monte de Ebal.

[[v5-11-30]]

^<<v5-11-30,30>>^ Porventura  não estão  eles daquém do Jordão, junto ao caminho do pôr do sol, na terra dos cananeus, que habitam na campina defronte de Gilgal, junto aos carvalhais de Moré?

[[v5-11-31]]

^<<v5-11-31,31>>^ Porque passareis o Jordão para entrardes a possuir a terra, que vos dá o Senhor vosso Deus: e a possuireis, e nela habitareis.

[[v5-11-32]]

^<<v5-11-32,32>>^ Tende pois cuidado em fazer todos os estatutos e os juízos, que eu hoje vos proponho.

'''

xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[&#60; Capítulo Anterior] | <<v5-11-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[Próximo Capítulo &#62;]