include::./index.adoc[]

[[v5-12-0]]
=== Deuteronômio, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-12-1]]

^<<v5-12-1,1>>^ ESTES são  os estatutos e os juízos que tereis cuidado em fazer na terra que vos deu o Senhor Deus de vossos pais, para a possuir todos os dias que viverdes sobre a terra.

[[v5-12-2]]

^<<v5-12-2,2>>^ Totalmente destruireis todos os lugares, onde as nações que possuireis serviram os seus deuses, sobre as altas montanhas, e sobre os outeiros, e debaixo de toda a árvore verde;

[[v5-12-3]]

^<<v5-12-3,3>>^ E derribareis os seus altares, e quebrareis as suas estátuas, e os seus bosques queimareis a fogo, e abatereis as imagens esculpidas dos seus deuses, e apagareis o seu nome daquele lugar.

[[v5-12-4]]

^<<v5-12-4,4>>^ Assim não fareis para com o Senhor vosso Deus;

[[v5-12-5]]

^<<v5-12-5,5>>^ Mas o lugar que o Senhor vosso Deus escolher de todas as vossas tribos, para ali pôr o seu nome, buscareis para sua habitação, e ali vireis.

[[v5-12-6]]

^<<v5-12-6,6>>^ E ali trareis os vossos holocaustos, e os vossos sacrifícios, e os vossos dízimos, e a oferta alçada da vossa mão, e os vossos votos, e as vossas ofertas voluntárias, e os primogênitos das vossas vacas e das vossas ovelhas.

[[v5-12-7]]

^<<v5-12-7,7>>^ E ali comereis perante o Senhor vosso Deus, e vos alegrareis em tudo em que poreis a vossa mão, vós e as vossas casas, no que te abençoar o Senhor teu Deus.

[[v5-12-8]]

^<<v5-12-8,8>>^ Não fareis conforme a tudo o que hoje fazemos aqui, cada qual tudo o que bem parece  aos seus olhos.

[[v5-12-9]]

^<<v5-12-9,9>>^ Porque até agora não entrastes no descanso e na herança que vos dá o Senhor vosso Deus.

[[v5-12-10]]

^<<v5-12-10,10>>^ Mas passareis o Jordão, e habitareis na terra que vos fará herdar o Senhor vosso Deus: e vos dará repouso de todos os vossos inimigos em redor, e morareis seguros.

[[v5-12-11]]

^<<v5-12-11,11>>^ Então haverá um lugar que escolherá o Senhor vosso Deus para ali fazer habitar o seu nome; ali trareis tudo o que vos ordeno; os vossos holocaustos, e os vossos sacrifícios, e os vossos dízimos, e a oferta alçada da vossa mão, e toda a escolha dos vossos votos que votardes ao Senhor.

[[v5-12-12]]

^<<v5-12-12,12>>^ E vos alegrareis perante o Senhor vosso Deus, vós, e vossos filhos, e vossas filhas, e os vossos servos, e as vossas servas, e o levita que está  dentro das vossas portas; pois convosco não tem parte nem herança.

[[v5-12-13]]

^<<v5-12-13,13>>^ Guarda-te, que não ofereças os teus holocaustos em todo o lugar que vires;

[[v5-12-14]]

^<<v5-12-14,14>>^ Mas no lugar que o Senhor escolher numa das tuas tribos ali oferecerás os teus holocaustos, e ali farás tudo o que te ordeno.

[[v5-12-15]]

^<<v5-12-15,15>>^ Porém, conforme a todo o desejo da tua alma, degolarás e comerás carne segundo a bênção do Senhor teu Deus, que te dá dentro de todas as tuas portas: o imundo e o limpo dela comerá; como do corço e do veado:

[[v5-12-16]]

^<<v5-12-16,16>>^ Tão somente o sangue não comereis: sobre a terra o derramareis como água.

[[v5-12-17]]

^<<v5-12-17,17>>^ Nas tuas portas não poderás comer o dízimo do teu grão, nem do teu mosto, nem do teu azeite, nem as primogenituras das tuas vacas, nem das tuas ovelhas; nem nenhum dos teus votos, que houveres votado, nem as tuas ofertas voluntárias, nem a oferta alçada da tua mão;

[[v5-12-18]]

^<<v5-12-18,18>>^ Mas o comerás perante o Senhor teu Deus, no lugar que escolher o Senhor teu Deus, tu, e teu filho, e a tua filha, e o teu servo, e a tua serva, e o levita que está  dentro das tuas portas: e perante o Senhor teu Deus te alegrarás em tudo em que puseres a tua mão.

[[v5-12-19]]

^<<v5-12-19,19>>^ Guarda-te, que não desampares ao levita todos os teus dias na terra.

[[v5-12-20]]

^<<v5-12-20,20>>^ Quando o Senhor teu Deus dilatar os teus termos como te disse, e disseres: Comerei carne; porquanto a tua alma tem desejo de comer carne; conforme a todo desejo da tua alma, comerás carne.

[[v5-12-21]]

^<<v5-12-21,21>>^ Se estiver longe de ti o lugar que o Senhor teu Deus escolher para ali pôr o seu nome, então degolarás das tuas vacas e tuas ovelhas, que o Senhor te tiver dado, como te tenho ordenado; e comerás dentro das tuas portas, conforme a todo o desejo da tua alma.

[[v5-12-22]]

^<<v5-12-22,22>>^ Porém, como se come o corço e o veado, assim comerás: o imundo e o limpo juntamente comerão delas.

[[v5-12-23]]

^<<v5-12-23,23>>^ Somente esforça-te para que não comas o sangue: pois o sangue é  a vida: pelo que não comerás a vida com a carne:

[[v5-12-24]]

^<<v5-12-24,24>>^ Não o comerás: na terra o derramarás como água.

[[v5-12-25]]

^<<v5-12-25,25>>^ Não o comerás; para que bem te suceda a ti, e a teus filhos, depois de ti, quando fizeres o que for  reto aos olhos do Senhor.

[[v5-12-26]]

^<<v5-12-26,26>>^ Porém as tuas cousas santas que tiveres, e os teus votos tomarás, e virás ao lugar que o Senhor escolher.

[[v5-12-27]]

^<<v5-12-27,27>>^ E oferecerás os teus holocaustos, a carne e o sangue sobre o altar do Senhor teu Deus; e o sangue dos teus sacrifícios se derramará sobre o altar do Senhor teu Deus; porém a carne comerás.

[[v5-12-28]]

^<<v5-12-28,28>>^ Guarda e ouve todas estas palavras que te ordeno, para que bem te suceda a ti e a teus filhos depois de ti para sempre, quando fizeres o que for  bom e reto aos olhos do Senhor teu Deus.

[[v5-12-29]]

^<<v5-12-29,29>>^ Quando o Senhor teu Deus desarraigar de diante de ti as nações, aonde vais a possuí-las, e as possuíres e habitares na sua terra,

[[v5-12-30]]

^<<v5-12-30,30>>^ Guarda-te, que te não enlaces após elas, depois que forem destruídas diante de ti; e que não perguntes acerca dos seus deuses, dizendo: Assim  como serviram estas nações os seus deuses, do mesmo modo também farei eu.

[[v5-12-31]]

^<<v5-12-31,31>>^ Assim não farás ao Senhor teu Deus: porque tudo o que é abominável ao Senhor, e que ele aborrece, fizeram eles a seus deuses: pois até seus filhos e suas filhas queimaram com fogo aos seus deuses.

[[v5-12-32]]

^<<v5-12-32,32>>^ Tudo o que eu vos ordeno, observareis; nada lhe acrescentarás nem diminuirás.

'''

xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[&#60; Capítulo Anterior] | <<v5-12-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[Próximo Capítulo &#62;]