include::./index.adoc[]

[[v5-32-0]]
=== Deuteronômio, 32
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-32-1]]

^<<v5-32-1,1>>^ INCLINAI os ouvidos, ó céus, e falarei: e ouça a terra as palavras da minha boca.

[[v5-32-2]]

^<<v5-32-2,2>>^ Goteje a minha doutrina como a chuva, destile o meu dito como o orvalho, como chuvisco sobre a erva e como gotas de água sobre a relva.

[[v5-32-3]]

^<<v5-32-3,3>>^ Porque apregoarei o nome do Senhor: dai grandeza a nosso Deus.

[[v5-32-4]]

^<<v5-32-4,4>>^ Ele é  a Rocha, cuja obra é  perfeita, porque todos os seus caminhos juízo são : Deus é  a verdade, e não há nele injustiça; justo e reto é.

[[v5-32-5]]

^<<v5-32-5,5>>^ Corromperam-se contra ele, seus filhos eles  não são , a sua mancha é deles; geração perversa e torcida é.

[[v5-32-6]]

^<<v5-32-6,6>>^ Recompensais assim ao Senhor, povo louco e ignorante? não é  ele teu Pai, que te adquiriu, te fez e te estabeleceu?

[[v5-32-7]]

^<<v5-32-7,7>>^ Lembra-te dos dias da antiguidade, atenta para os anos de muitas gerações: pergunta a teu pai, e ele te informará, aos teus anciãos, e eles to dirão.

[[v5-32-8]]

^<<v5-32-8,8>>^ Quando o Altíssimo distribuía as heranças às nações, quando dividia os filhos de Adão uns dos outros, pôs os termos dos povos, conforme ao número dos filhos de Israel.

[[v5-32-9]]

^<<v5-32-9,9>>^ Porque a porção do Senhor é  o seu povo; Jacó é  a corda da sua herança.

[[v5-32-10]]

^<<v5-32-10,10>>^ Achou-o na terra do deserto, e num ermo solitário cheio de uivos; trouxe-o  ao redor, instruiu-o, guardou-o como a menina do seu olho.

[[v5-32-11]]

^<<v5-32-11,11>>^ Como a águia desperta o seu ninho, se move sobre os seus filhos, estende as suas asas, toma-os e os leva sobre as suas asas,

[[v5-32-12]]

^<<v5-32-12,12>>^ Assim  só o Senhor o guiou: e não havia com ele Deus estranho.

[[v5-32-13]]

^<<v5-32-13,13>>^ Ele o fez cavalgar sobre as alturas da terra, e comeu as novidades do campo, e o fez chupar mel da rocha e azeite da dura pederneira.

[[v5-32-14]]

^<<v5-32-14,14>>^ Manteiga de vacas, e leite do rebanho, com a gordura dos cordeiros e dos carneiros que pastam em Basã, e dos bodes, com gordura dos rins do trigo; e bebeste o sangue das uvas, o vinho puro.

[[v5-32-15]]

^<<v5-32-15,15>>^ E, engordando-se Jesurum, deu coices; engordaste-te, engrossaste-te, e de gordura  te cobriste: e deixou a Deus, que o fez, e desprezou a Rocha de sua salvação.

[[v5-32-16]]

^<<v5-32-16,16>>^ Com deuses  estranhos o provocaram a zelos; com abominações o irritaram.

[[v5-32-17]]

^<<v5-32-17,17>>^ Sacrifícios ofereceram aos diabos, não a Deus; aos deuses que não conheceram, novos deuses  que vieram há pouco, dos quais não se estremeceram vossos pais.

[[v5-32-18]]

^<<v5-32-18,18>>^ Esqueceste-te da Rocha que te gerou: e em esquecimento puseste o Deus que te formou.

[[v5-32-19]]

^<<v5-32-19,19>>^ O que vendo o Senhor, os  desprezou, provocado à ira contra seus filhos e suas filhas;

[[v5-32-20]]

^<<v5-32-20,20>>^ E disse: Esconderei o meu rosto deles, verei qual será  o seu fim; porque são  geração de perversidade, filhos em quem não há lealdade.

[[v5-32-21]]

^<<v5-32-21,21>>^ A zelos me provocaram com aquilo que  não é  Deus; com as suas vaidades me provocaram à ira; portanto eu os provocarei a zelos com os que  não são  povo; com nação louca os despertarei à ira.

[[v5-32-22]]

^<<v5-32-22,22>>^ Porque um fogo se acendeu na minha ira, e arderá até ao mais profundo do inferno, e consumirá a terra com a sua novidade, e abrasará os fundamentos dos montes.

[[v5-32-23]]

^<<v5-32-23,23>>^ Males amontoarei sobre eles; as minhas setas esgotarei contra eles.

[[v5-32-24]]

^<<v5-32-24,24>>^ Exaustos serão  de fome, comidos de carbúnculo e de peste amarga: e entre eles enviarei dentes de feras, com ardente peçonha de serpentes do pó.

[[v5-32-25]]

^<<v5-32-25,25>>^ Por fora devastará a espada, e por dentro o pavor: ao mancebo, juntamente com a virgem, assim à criança de mama, como ao homem de cãs.

[[v5-32-26]]

^<<v5-32-26,26>>^ Eu  disse: Por todos os cantos os espalharia; faria cessar a sua memória dentre os homens,

[[v5-32-27]]

^<<v5-32-27,27>>^ Se eu não receara a ira do inimigo, para que os seus adversários o não estranhem, e  para que não digam: A nossa mão está alta; o Senhor não fez tudo isto.

[[v5-32-28]]

^<<v5-32-28,28>>^ Porque são  gente falta de conselhos, e neles não há  entendimento.

[[v5-32-29]]

^<<v5-32-29,29>>^ Oxalá eles fossem sábios! que  isto entendessem, e  atentassem para o seu fim!

[[v5-32-30]]

^<<v5-32-30,30>>^ Como pode ser que  um só perseguisse mil, e dois fizessem fugir dez mil, se a sua Rocha os não vendera, e o Senhor os não entregara?

[[v5-32-31]]

^<<v5-32-31,31>>^ Porque a sua rocha não é  como a nossa Rocha; sendo  até os nossos inimigos juízes disto.

[[v5-32-32]]

^<<v5-32-32,32>>^ Porque a sua vinha é  a vinha de Sodoma e dos campos de Gomorra: as suas uvas são  uvas de fel, cachos amargosos têm.

[[v5-32-33]]

^<<v5-32-33,33>>^ O seu vinho é  ardente veneno de dragões, e peçonha cruel de víboras.

[[v5-32-34]]

^<<v5-32-34,34>>^ Não está isto encerrado comigo? selado nos meus tesouros?

[[v5-32-35]]

^<<v5-32-35,35>>^ Minha é  a vingança e a recompensa, ao tempo que resvalar o seu pé: porque o dia da sua ruína está  próximo, e as cousas que lhes hão de suceder, se apressam a chegar.

[[v5-32-36]]

^<<v5-32-36,36>>^ Porque o Senhor fará justiça ao seu povo, e se arrependerá pelos seus servos, quando vir que o seu poder se foi, e não há fechado nem desamparado.

[[v5-32-37]]

^<<v5-32-37,37>>^ Então dirá: Onde estão  os seus deuses? a rocha em quem confiavam,

[[v5-32-38]]

^<<v5-32-38,38>>^ De cujos sacrifícios comiam a gordura, e  de cujas libações bebiam o vinho? levantem-se, e vos ajudem, para que haja para vós escondedouro.

[[v5-32-39]]

^<<v5-32-39,39>>^ Vede agora que eu, eu o sou , e mais nenhum Deus comigo; eu mato, e eu faço viver; eu firo, e eu saro; e ninguém há  que escape da minha mão.

[[v5-32-40]]

^<<v5-32-40,40>>^ Porque levantarei a minha mão aos céus, e direi: Eu vivo para sempre.

[[v5-32-41]]

^<<v5-32-41,41>>^ Se eu afiar a minha espada reluzente, e travar do juízo a minha mão, farei tornar a vingança sobre os meus adversários, e recompensareis aos meus aborrecedores.

[[v5-32-42]]

^<<v5-32-42,42>>^ Embriagarei as minhas setas de sangue, e a minha espada comerá carne: do sangue dos mortos e dos prisioneiros, desde a cabeça, haverá vinganças do inimigo.

[[v5-32-43]]

^<<v5-32-43,43>>^ Jubilai, ó nações, com  o seu povo, porque vingará o sangue dos seus servos, e sobre os seus adversários fará tornar a vingança, e terá misericórdia da sua terra e  do seu povo.

[[v5-32-44]]

^<<v5-32-44,44>>^ E veio Moisés, e falou todas as palavras deste cântico aos ouvidos do povo, ele e Oseias, filho de Num.

[[v5-32-45]]

^<<v5-32-45,45>>^ E, acabando Moisés de falar todas estas palavras a todo o Israel,

[[v5-32-46]]

^<<v5-32-46,46>>^ Disse-lhes: Aplicai o vosso coração a todas as palavras que hoje testifico entre vós, para que as recomendeis a vossos filhos, para que tenham cuidado de cumprir todas as palavras desta lei.

[[v5-32-47]]

^<<v5-32-47,47>>^ Porque esta palavra não vos é  vã, antes é  a vossa vida; e por esta mesma palavra prolongareis os dias na terra a qual, passando o Jordão, ides a possuir.

[[v5-32-48]]

^<<v5-32-48,48>>^ Depois falou o Senhor a Moisés, naquele mesmo dia, dizendo:

[[v5-32-49]]

^<<v5-32-49,49>>^ Sobe ao monte de Abarim, ao monte Nebo, que está  na terra de Moabe, defronte de Jericó, e vê a terra de Canaã, que darei aos filhos de Israel por possessão,

[[v5-32-50]]

^<<v5-32-50,50>>^ E morre no monte, ao qual subirás; e recolhe-te aos teus povos, como Aarão teu irmão morreu no monte de Hor, e se recolheu aos seus povos.

[[v5-32-51]]

^<<v5-32-51,51>>^ Porquanto prevaricastes contra mim no meio dos filhos de Israel, nas águas da contenção em Cades, no deserto de Zim; pois me não santificastes no meio dos filhos de Israel.

[[v5-32-52]]

^<<v5-32-52,52>>^ Pelo que verás a terra diante de  ti, porém não entrarás nela, na terra que darei aos filhos de Israel.

'''

xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[&#60; Capítulo Anterior] | <<v5-32-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[Próximo Capítulo &#62;]