include::./index.adoc[]

[[v5-8-0]]
=== Deuteronômio, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-8-1]]

^<<v5-8-1,1>>^ TODOS os mandamentos que hoje vos ordeno guardareis para os  fazer: para que vivais, e vos multipliqueis, e entreis, e possuais a terra que o Senhor jurou a vossos pais.

[[v5-8-2]]

^<<v5-8-2,2>>^ E te lembrarás de todo o caminho pelo qual o Senhor teu Deus te guiou no deserto estes quarenta anos, para te humilhar, e te tentar, para saber o que estava  no teu coração, se guardarias os seus mandamentos, ou não.

[[v5-8-3]]

^<<v5-8-3,3>>^ E te humilhou, e te deixou ter fome, e te sustentou com o maná, que tu não conheceste, nem teus pais o conheceram: para te dar a entender que o homem não viverá só de pão, mas que de tudo o que sai da boca do Senhor viverá o homem.

[[v5-8-4]]

^<<v5-8-4,4>>^ Nunca se envelheceu o teu vestido sobre ti, nem se inchou o teu pé estes quarenta anos.

[[v5-8-5]]

^<<v5-8-5,5>>^ Confessa pois no teu coração que, como um homem castiga a seu filho, assim  te castiga o Senhor teu Deus.

[[v5-8-6]]

^<<v5-8-6,6>>^ E guarda os mandamentos do Senhor teu Deus, para o temer, e andar nos seus caminhos.

[[v5-8-7]]

^<<v5-8-7,7>>^ Porque o Senhor teu Deus te mete numa boa terra, terra de ribeiros de águas, de fontes, e de abismos, que saem dos vales e das montanhas;

[[v5-8-8]]

^<<v5-8-8,8>>^ Terra de trigo e cevada, e de vides, e figueiras, e romeiras; terra de oliveiras, abundante de azeite e mel;

[[v5-8-9]]

^<<v5-8-9,9>>^ Terra em que comerás o pão sem escassez, e nada te faltará nela: terra cujas pedras são  ferro, e de cujos montes tu cavarás o cobre.

[[v5-8-10]]

^<<v5-8-10,10>>^ Quando pois tiveres comido, e fores farto, louvarás ao Senhor teu Deus pela boa terra que te deu.

[[v5-8-11]]

^<<v5-8-11,11>>^ Guarda-te para que te não esqueças do Senhor teu Deus, não guardando os seus mandamentos, e os seus juízos, e os seus estatutos que hoje te ordeno:

[[v5-8-12]]

^<<v5-8-12,12>>^ Para que, porventura, havendo tu comido e estando farto, e havendo  edificado boas casas, e habitando-as,

[[v5-8-13]]

^<<v5-8-13,13>>^ E se tiverem aumentado as tuas vacas e as tuas ovelhas, e se acrescentar a prata e o ouro, e se multiplicar tudo quanto tens,

[[v5-8-14]]

^<<v5-8-14,14>>^ Se não eleve o teu coração e te esqueças do Senhor teu Deus, que te tirou da terra do Egito, da casa da servidão;

[[v5-8-15]]

^<<v5-8-15,15>>^ Que te guiou por aquele grande e terrível deserto de serpentes ardentes, e de escorpiões, e de secura, em que não havia  água; e tirou água para ti da rocha do seixal;

[[v5-8-16]]

^<<v5-8-16,16>>^ Que no deserto te sustentou com maná, que teus pais não conheceram; para te humilhar, e para te provar, para no teu fim te fazer bem;

[[v5-8-17]]

^<<v5-8-17,17>>^ E digas no teu coração: A minha força, e a fortaleza de meu braço, me adquiriu este poder.

[[v5-8-18]]

^<<v5-8-18,18>>^ Antes te lembrarás do Senhor teu Deus, que ele é  o que te dá força para adquirires poder; para confirmar o seu concerto, que jurou a teus pais; como se vê  neste dia.

[[v5-8-19]]

^<<v5-8-19,19>>^ Será porém que , se de qualquer sorte te esqueceres do Senhor teu Deus, e se ouvires outros deuses, e os servires, e te inclinares perante eles, hoje eu protesto contra vós que certamente perecereis.

[[v5-8-20]]

^<<v5-8-20,20>>^ Como as gentes que o Senhor destruiu diante de vós, assim vós perecereis: porquanto não quisestes obedecer à voz do Senhor vosso Deus.

'''

xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[&#60; Capítulo Anterior] | <<v5-8-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[Próximo Capítulo &#62;]