include::./index.adoc[]

[[v5-17-0]]
=== Deuteronômio, 17
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-17-1]]

^<<v5-17-1,1>>^ NÃO sacrificarás ao Senhor teu Deus, boi ou gado miúdo em que haja defeito ou alguma cousa má: pois abominação é ao Senhor teu Deus.

[[v5-17-2]]

^<<v5-17-2,2>>^ Quando no meio de ti, em alguma das tuas portas que te dá o Senhor teu Deus, se achar algum homem ou mulher que fizer mal aos olhos do Senhor teu Deus transpassando o seu concerto.

[[v5-17-3]]

^<<v5-17-3,3>>^ Que for, e servir a outros deuses, e se encurvar a eles, ou ao sol, ou à lua, ou a todo exército do céu; o que eu não ordenei;

[[v5-17-4]]

^<<v5-17-4,4>>^ E te for denunciado, e o  ouvires; então bem o  inquirirás: e eis que, sendo verdade, e certo que se fez tal abominação em Israel,

[[v5-17-5]]

^<<v5-17-5,5>>^ Então levarás o homem ou a mulher que fez este malefício, às tuas portas, sim, o tal homem ou mulher, e os apedrejarás com pedras até que morram.

[[v5-17-6]]

^<<v5-17-6,6>>^ Por boca de duas testemunhas, ou três testemunhas, será morto o que houver de morrer: por boca duma só testemunha não morrerá.

[[v5-17-7]]

^<<v5-17-7,7>>^ A mão das testemunhas será primeiro contra ele, para matá-lo; e depois a mão de todo o povo: assim tirarás o mal do meio de ti.

[[v5-17-8]]

^<<v5-17-8,8>>^ Quando alguma cousa te for dificultosa em juízo, entre sangue e sangue, entre demanda e demanda, entre ferida e ferida, em  negócios de pendências nas tuas portas, então te levantarás, e subirás ao lugar que escolher o Senhor teu Deus;

[[v5-17-9]]

^<<v5-17-9,9>>^ E virás aos sacerdotes levitas, e ao juiz que houver naqueles dias, e inquirirás, e te anunciarão a palavra que for  do juízo.

[[v5-17-10]]

^<<v5-17-10,10>>^ E farás conforme ao mandado da palavra que te anunciarão do lugar que escolher o Senhor; e terás cuidado de fazer conforme a tudo o que te ensinarem.

[[v5-17-11]]

^<<v5-17-11,11>>^ Conforme ao mandado da lei que te ensinarem, e conforme ao juízo que te disserem, farás: da palavra que te anunciarem te não desviarás, nem para a direita nem para a esquerda.

[[v5-17-12]]

^<<v5-17-12,12>>^ O homem pois que se houver soberbamente, não dando ouvidos ao sacerdote, que está ali para servir ao Senhor teu Deus, nem ao juiz, o tal homem morrerá: e tirarás o mal de Israel:

[[v5-17-13]]

^<<v5-17-13,13>>^ Para que todo o povo o ouça e tema, e nunca mais se ensoberbeça.

[[v5-17-14]]

^<<v5-17-14,14>>^ Quando entrares na terra, que te dá o Senhor teu Deus, e a possuíres, e nela habitares, e disseres: Porei sobre mim um rei, assim  como têm  todas as gentes que estão em redor de mim:

[[v5-17-15]]

^<<v5-17-15,15>>^ Porás certamente sobre ti como rei aquele que escolher o Senhor teu Deus: dentre teus irmãos porás rei sobre ti: não poderás pôr homem estranho sobre ti, que não seja  de teus irmãos.

[[v5-17-16]]

^<<v5-17-16,16>>^ Porém não multiplicará para si cavalos, nem fará voltar o povo ao Egito, para multiplicar cavalos: pois o Senhor vos tem dito: Nunca mais voltareis por este caminho.

[[v5-17-17]]

^<<v5-17-17,17>>^ Tão pouco para si multiplicará mulheres, para que o seu coração se não desvie: nem prata nem ouro multiplicará muito para si.

[[v5-17-18]]

^<<v5-17-18,18>>^ Será também que , quando se assentar sobre o trono do seu reino, então escreverá para si um  traslado desta lei num livro, do que está  diante dos sacerdotes levitas.

[[v5-17-19]]

^<<v5-17-19,19>>^ E o terá consigo, e nele lerá todos os dias da sua vida; para que aprenda a temer ao Senhor seu Deus, para guardar todas as palavras desta lei, e estes estatutos, para fazê-los;

[[v5-17-20]]

^<<v5-17-20,20>>^ Para que o seu coração não se levante sobre os seus irmãos, e não se aparte do mandamento, nem para a direita nem para a esquerda; para que prolongue os dias no seu reino, ele e seus filhos no meio de Israel.

'''

xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[&#60; Capítulo Anterior] | <<v5-17-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-018.adoc#v5-18-0[Próximo Capítulo &#62;]