include::./index.adoc[]

[[v5-13-0]]
=== Deuteronômio, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-13-1]]

^<<v5-13-1,1>>^ QUANDO profeta ou sonhador de sonhos se levantar no meio de ti, e te der um sinal ou prodígio,

[[v5-13-2]]

^<<v5-13-2,2>>^ E suceder o tal sinal ou prodígio, de que te houver falado, dizendo: Vamos após outros deuses, que não conheceste, e sirvamo-los;

[[v5-13-3]]

^<<v5-13-3,3>>^ Não ouvirás as palavras daquele profeta ou sonhador de sonhos: porquanto o Senhor vosso Deus vos prova, para saber se amais o Senhor vosso Deus com todo o vosso coração, e com toda a vossa alma.

[[v5-13-4]]

^<<v5-13-4,4>>^ Após o Senhor vosso Deus andareis, e a ele temereis, e os seus mandamentos guardareis, e a sua voz ouvireis, e a ele servireis, e a ele vos achegareis.

[[v5-13-5]]

^<<v5-13-5,5>>^ E aquele profeta ou sonhador de sonhos morrerá, pois falou rebeldia contra o Senhor vosso Deus, que vos tirou da terra do Egito, e vos resgatou da casa da servidão, para te apartar do caminho que te ordenou o Senhor teu Deus, para andares nele: assim tirarás o mal do meio de ti.

[[v5-13-6]]

^<<v5-13-6,6>>^ Quando te incitar teu irmão, filho da tua mãe, ou teu filho, ou tua filha, ou a mulher do teu seio, ou teu amigo, que te é  como a tua alma, dizendo-te em segredo: Vamos, e sirvamos a outros deuses que não conheceste, nem tu nem teus pais;

[[v5-13-7]]

^<<v5-13-7,7>>^ Dentre os deuses dos povos que estão  em redor de vós, perto ou longe de ti, desde uma extremidade da terra até à outra extremidade;

[[v5-13-8]]

^<<v5-13-8,8>>^ Não consentirás com ele, nem o ouvirás; nem o teu olho o poupará, nem terás piedade dele , nem o esconderás;

[[v5-13-9]]

^<<v5-13-9,9>>^ Mas certamente o matarás; a tua mão será a primeira contra ele, para o matar; e depois a mão de todo o povo.

[[v5-13-10]]

^<<v5-13-10,10>>^ E com pedras o apedrejarás, até que morra, pois te procurou apartar do Senhor teu Deus, que te tirou da terra do Egito, da casa da servidão:

[[v5-13-11]]

^<<v5-13-11,11>>^ Para que todo o Israel o ouça e o tema, e não torne a fazer segundo esta cousa má no meio de ti.

[[v5-13-12]]

^<<v5-13-12,12>>^ Quando ouvires dizer de alguma das tuas cidades que o Senhor teu Deus te dá, para ali habitar:

[[v5-13-13]]

^<<v5-13-13,13>>^ Uns homens, filhos de Belial, saíram do meio de ti, que incitaram os moradores da sua cidade, dizendo: Vamos, e sirvamos a outros deuses que não conhecestes;

[[v5-13-14]]

^<<v5-13-14,14>>^ Então inquirirás e informar-te-ás, e com diligência perguntarás; e eis que, sendo este negócio verdade, e certo que  se fez uma tal abominação no meio de ti;

[[v5-13-15]]

^<<v5-13-15,15>>^ Então  certamente ferirás ao fio da espada os moradores daquela cidade, destruindo ao fio da espada a ela e a tudo o que nela houver , até aos animais.

[[v5-13-16]]

^<<v5-13-16,16>>^ E ajuntarás todo o seu despojo no meio da sua praça; e a cidade e todo o seu despojo queimarás totalmente para o Senhor teu Deus, e será montão perpétuo, nunca mais se edificará.

[[v5-13-17]]

^<<v5-13-17,17>>^ Também nada se pegará à tua mão do anátema, para que o Senhor se aparte do ardor da sua ira, e te faça misericórdia, e tenha piedade de ti, e te multiplique, como jurou a teus pais;

[[v5-13-18]]

^<<v5-13-18,18>>^ Quando ouvires a voz do Senhor teu Deus, para guardares todos os seus mandamentos, que hoje te ordeno, para fazeres o que for  reto aos olhos do Senhor teu Deus.

'''

xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[&#60; Capítulo Anterior] | <<v5-13-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[Próximo Capítulo &#62;]