include::./index.adoc[]

[[v5-2-0]]
=== Deuteronômio, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-2-1]]

^<<v5-2-1,1>>^ DEPOIS viramo-nos, e caminhamos ao deserto, caminho do Mar Vermelho, como o Senhor me tinha dito, e muitos dias rodeamos a montanha de Seir.

[[v5-2-2]]

^<<v5-2-2,2>>^ Então o Senhor me falou, dizendo:

[[v5-2-3]]

^<<v5-2-3,3>>^ Assaz tendes rodeado esta montanha: virai-vos para o norte.

[[v5-2-4]]

^<<v5-2-4,4>>^ E dá ordem ao povo, dizendo: Passareis pelos termos de vossos irmãos, os filhos de Esaú, que habitam em Seir: e eles terão medo de vós; porém guardai-vos bem.

[[v5-2-5]]

^<<v5-2-5,5>>^ Não vos entremetais com eles, porque vos não darei da sua terra nem ainda a pisada da planta de um pé: porquanto a Esaú tenho dado a montanha de Seir por  herança.

[[v5-2-6]]

^<<v5-2-6,6>>^ Comprareis deles, por dinheiro, comida para comerdes: e também água para beber deles comprareis por dinheiro.

[[v5-2-7]]

^<<v5-2-7,7>>^ Pois o Senhor teu Deus te abençoou em toda a obra das tuas mãos; ele sabe que andas por este grande deserto: estes quarenta anos o Senhor teu Deus esteve  contigo, cousa nenhuma te faltou.

[[v5-2-8]]

^<<v5-2-8,8>>^ Passando pois por nossos irmãos, os filhos de Esaú, que habitavam em Seir, desde o caminho da planície de Elate e de Eziom-Geber, nos viramos e passamos o caminho do deserto de Moabe.

[[v5-2-9]]

^<<v5-2-9,9>>^ Então o Senhor me disse: Não molestes a Moabe, e não contendas com eles em peleja, porque te não darei herança da sua terra; porquanto tenho dado Ar aos filhos de Ló por  herança.

[[v5-2-10]]

^<<v5-2-10,10>>^ (Os emeus dantes habitaram nela: um povo grande e numeroso, e alto como os gigantes;

[[v5-2-11]]

^<<v5-2-11,11>>^ Também estes foram contados por gigantes como os enaquins: e os moabitas lhes chamavam emeus.

[[v5-2-12]]

^<<v5-2-12,12>>^ Dantes os horeus também habitaram em Seir: porém os filhos de Esaú os lançaram fora, e os destruíram de diante de si, e habitaram no seu lugar, assim  como Israel fez à terra da sua herança, que o Senhor lhes tinha dado.)

[[v5-2-13]]

^<<v5-2-13,13>>^ Levantai-vos agora, e passai o ribeiro de Zerede: assim passamos o ribeiro de Zerede.

[[v5-2-14]]

^<<v5-2-14,14>>^ E os dias que caminhamos, desde Cades-Barneia até que passamos o ribeiro de Zerede, foram  trinta e oito anos, até que toda aquela geração dos homens de guerra se consumiu do meio do arraial, como o Senhor lhes jurara.

[[v5-2-15]]

^<<v5-2-15,15>>^ Assim também foi contra eles a mão do Senhor, para os destruir do meio do arraial até os haver consumido.

[[v5-2-16]]

^<<v5-2-16,16>>^ E sucedeu que, sendo já consumidos todos os homens de guerra, pela morte, do meio do arraial.

[[v5-2-17]]

^<<v5-2-17,17>>^ O Senhor me falou, dizendo:

[[v5-2-18]]

^<<v5-2-18,18>>^ Hoje passarás por Ar, pelos termos de Moabe;

[[v5-2-19]]

^<<v5-2-19,19>>^ E chegarás até defronte dos filhos de Amom: não os molestes, e com eles não contendas: porque da terra dos filhos de Amom te não darei herança, porquanto aos filhos de Ló a tenho dado por  herança.

[[v5-2-20]]

^<<v5-2-20,20>>^ (Também esta foi contada por terra de gigantes; dantes nela habitavam gigantes, e os amonitas lhes chamavam zanzumeus:

[[v5-2-21]]

^<<v5-2-21,21>>^ Um povo grande, e numeroso, e alto, como os gigantes: e o Senhor os destruiu de diante de si, e eles os lançaram fora, e habitaram no seu lugar;

[[v5-2-22]]

^<<v5-2-22,22>>^ Assim como fez com os filhos de Esaú, que habitavam em Seir, de diante dos quais destruiu os horeus, e eles os lançaram fora, e habitaram no seu lugar até este dia;

[[v5-2-23]]

^<<v5-2-23,23>>^ Também os caftoreus, que saíram de Caftor, destruíram os aveus, que habitavam em Hazerim até Gaza, e habitaram no seu lugar.)

[[v5-2-24]]

^<<v5-2-24,24>>^ Levantai-vos, parti e passai o ribeiro de Arnom; eis aqui na tua mão tenho dado a Seom, amorreu, rei de Hesbom, e a sua terra; começa a possuí-la, e contende com eles em peleja.

[[v5-2-25]]

^<<v5-2-25,25>>^ Neste dia começarei a por um terror e um temor de ti diante dos povos que estão  debaixo de todo o céu: os que ouvirem a tua fama tremerão diante de ti e se angustiarão.

[[v5-2-26]]

^<<v5-2-26,26>>^ Então mandei mensageiros desde o deserto de Quedemote a Seom, rei de Hesbom, com palavras de paz, dizendo:

[[v5-2-27]]

^<<v5-2-27,27>>^ Deixa-me passar pela tua terra: somente pela estrada irei; não me desviarei para a direita nem para a esquerda.

[[v5-2-28]]

^<<v5-2-28,28>>^ A comida que eu coma vender-ma-ás por dinheiro, e dar-me-ás por dinheiro a água que beba: tão somente deixa-me passar a pé;

[[v5-2-29]]

^<<v5-2-29,29>>^ Como fizeram comigo os filhos de Esaú, que habitam em Seir, e os moabitas que habitam em Ar; até que eu passe o Jordão, a terra que o Senhor nosso Deus nos há de dar.

[[v5-2-30]]

^<<v5-2-30,30>>^ Mas Seom, rei de Hesbom, não nos quis deixar passar por ele, porquanto o Senhor teu Deus endurecera o seu espírito, e fizera obstinado o seu coração, para to dar na tua mão, como neste dia se vê.

[[v5-2-31]]

^<<v5-2-31,31>>^ E o Senhor me disse: Eis aqui, tenho começado a dar-te Seom, e a sua terra diante de ti: começa pois  a possuí-l a , para que herdes a sua terra.

[[v5-2-32]]

^<<v5-2-32,32>>^ E Seom saiu-nos ao encontro, ele e todo o seu povo, à peleja, a Jaaz:

[[v5-2-33]]

^<<v5-2-33,33>>^ E o Senhor nosso Deus no-lo deu diante de nós, e o ferimos a ele, e a seus filhos, e a todo o seu povo.

[[v5-2-34]]

^<<v5-2-34,34>>^ E naquele tempo tomamos todas as suas cidades, e destruímos todas as cidades, homens, e mulheres e crianças: não deixamos a ninguém.

[[v5-2-35]]

^<<v5-2-35,35>>^ Somente tomamos em presa o gado para nós, e o despojo das cidades que tínhamos tomado.

[[v5-2-36]]

^<<v5-2-36,36>>^ Desde Aroer, que está  à borda do ribeiro de Arnom, e a cidade que está  junto ao ribeiro, até Gileade, nenhuma cidade houve que de nós escapasse: tudo isto o Senhor nosso Deus nos  entregou diante de nós.

[[v5-2-37]]

^<<v5-2-37,37>>^ Somente à terra dos filhos de Amom não chegaste: nem a toda a borda do ribeiro de Jaboque, nem às cidades da montanha, nem a cousa alguma que nos proibira o Senhor nosso Deus.

'''

xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[&#60; Capítulo Anterior] | <<v5-2-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-003.adoc#v5-3-0[Próximo Capítulo &#62;]