include::./index.adoc[]

[[v5-3-0]]
=== Deuteronômio, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-3-1]]

^<<v5-3-1,1>>^ DEPOIS nos  viramos e subimos o caminho de Basã: e Ogue, rei de Basã, nos saiu ao encontro, ele e todo o seu povo, à peleja em Edrei.

[[v5-3-2]]

^<<v5-3-2,2>>^ Então o Senhor me disse: Não o temas, porque a ele e a todo o seu povo, e a sua terra, tenho dado na tua mão: e far-lhe-ás como fizeste a Seom, rei dos amorreus, que habitava em Hesbom.

[[v5-3-3]]

^<<v5-3-3,3>>^ E também o Senhor nosso Deus nos  deu na nossa mão a Ogue, rei de Basã, e a todo o seu povo: de maneira que o ferimos, até que ninguém lhe ficou de restante.

[[v5-3-4]]

^<<v5-3-4,4>>^ E naquele tempo tomamos todas as suas cidades; nenhuma cidade houve que lhes não tomássemos: sessenta cidades, toda a borda da terra de Argobe, e reino de Ogue em Basã.

[[v5-3-5]]

^<<v5-3-5,5>>^ Todas estas cidades eram  fortificadas com altos muros, portas e ferrolhos: além de outras muitas cidades sem muros.

[[v5-3-6]]

^<<v5-3-6,6>>^ E destruímo-las como fizemos a Seom, rei de Hesbom, destruindo todas as cidades, homens, mulheres e crianças.

[[v5-3-7]]

^<<v5-3-7,7>>^ Porém todo o gado, e o despojo das cidades, tomamos para nós por presa.

[[v5-3-8]]

^<<v5-3-8,8>>^ Assim naquele tempo tomamos a terra da mão daqueles dois reis dos amorreus, que estavam  dalém do Jordão: desde o rio de Arnom, até ao monte de Hermom;

[[v5-3-9]]

^<<v5-3-9,9>>^ (Os sidônios a Hermom chamam Siriom; porém os amorreus lhe chamam Senir;)

[[v5-3-10]]

^<<v5-3-10,10>>^ Todas as cidades da terra plana, e todo o Gileade, e todo o Basã até Salca e Edrei, cidades do reino de Ogue em Basã.

[[v5-3-11]]

^<<v5-3-11,11>>^ Porque só Ogue, o rei de Basã, ficou do resto dos gigantes; eis que o seu leito, um leito de ferro, não está porventura  em Rabá dos filhos de Amom? de nove côvados o seu comprimento, e de quatro côvados a sua largura, pelo côvado dum homem.

[[v5-3-12]]

^<<v5-3-12,12>>^ Tomamos pois esta terra em possessão naquele tempo: desde Aroer, que está  junto ao ribeiro de Arnom, e a metade da montanha de Gileade, com as suas cidades, tenho dado aos rubenitas e gaditas.

[[v5-3-13]]

^<<v5-3-13,13>>^ E o resto de Gileade, como também todo o Basã, o reino de Ogue, dei à meia tribo de Manassés; toda aquela borda da terra de Argobe, por todo o Basã, se chamava a terra dos gigantes.

[[v5-3-14]]

^<<v5-3-14,14>>^ Jair, filho de Manassés, alcançou toda a porção da terra de Argobe, até ao termo dos gesuritas, e maacatitas, e a chamou de seu nome, Basã-Havote-Jair, até este dia.

[[v5-3-15]]

^<<v5-3-15,15>>^ E a Maquir dei Gileade.

[[v5-3-16]]

^<<v5-3-16,16>>^ Mas aos rubenitas e gaditas dei desde Gileade até ao ribeiro de Arnom, o meio do ribeiro, e o termo: e até ao ribeiro de Jaboque, o termo dos filhos de Amom.

[[v5-3-17]]

^<<v5-3-17,17>>^ Como também a campina, e o Jordão com o termo: desde Quinerete até ao mar da campina, o Mar Salgado, abaixo de Asdote-Pisga para o oriente.

[[v5-3-18]]

^<<v5-3-18,18>>^ E vos mandei mais, no mesmo tempo, dizendo: O Senhor vosso Deus vos deu esta terra, para possuí-la: passai pois armados vós, todos os homens valentes, diante de vossos irmãos, os filhos de Israel.

[[v5-3-19]]

^<<v5-3-19,19>>^ Tão somente vossas mulheres, e vossas crianças, e vosso gado (porque  eu sei que tendes muito gado) ficarão nas vossas cidades, que já vos tenho dado.

[[v5-3-20]]

^<<v5-3-20,20>>^ Até que o Senhor dê descanso a vossos irmãos como a vós: para que eles herdem também a terra que o Senhor vosso Deus lhes há de dar dalém do Jordão: então voltareis cada qual à sua herança que já vos tenho dado.

[[v5-3-21]]

^<<v5-3-21,21>>^ Também dei ordem a Josué no mesmo tempo, dizendo: Os teus olhos veem tudo o que o Senhor vosso Deus tem feito a estes dois reis: assim fará o Senhor a todos os reinos, a que tu passarás.

[[v5-3-22]]

^<<v5-3-22,22>>^ Não os temais: porque o Senhor vosso Deus é o que peleja por vós.

[[v5-3-23]]

^<<v5-3-23,23>>^ Também eu  pedi graça ao Senhor no mesmo tempo, dizendo:

[[v5-3-24]]

^<<v5-3-24,24>>^ Senhor Jeová ! já começaste a mostrar ao teu servo a tua grandeza e a tua forte mão: porque, que Deus há  nos céus e na terra, que possa obrar segundo as tuas obras, e segundo a tua fortaleza?

[[v5-3-25]]

^<<v5-3-25,25>>^ Rogo-te que me deixes passar, para que veja esta  boa terra que está dalém do Jordão; esta boa montanha, e o Líbano!

[[v5-3-26]]

^<<v5-3-26,26>>^ Porém o Senhor indignou-se muito contra mim por causa de vós, e não me ouviu; antes me disse: Basta; não me fales mais neste negócio:

[[v5-3-27]]

^<<v5-3-27,27>>^ Sobe ao cume de Pisga, e levanta os teus olhos ao ocidente, e ao norte, e ao sul, e ao oriente, e vê com os teus olhos: porque não passarás este Jordão.

[[v5-3-28]]

^<<v5-3-28,28>>^ Manda pois a Josué, e esforça-o, e conforta-o; porque ele passará adiante deste povo, e o fará possuir a terra que vires.

[[v5-3-29]]

^<<v5-3-29,29>>^ Assim ficamos neste vale defronte de Bete-Peor.

'''

xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[&#60; Capítulo Anterior] | <<v5-3-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[Próximo Capítulo &#62;]