include::./index.adoc[]

[[v5-27-0]]
=== Deuteronômio, 27
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v5-27-1]]

^<<v5-27-1,1>>^ E DERAM ordem, Moisés e os anciãos, ao povo de Israel, dizendo: Guardai todos estes mandamentos que hoje vos ordeno:

[[v5-27-2]]

^<<v5-27-2,2>>^ Será pois que , no dia em que passares o Jordão à terra que te der o Senhor teu Deus, levantar-te-ás umas  pedras grandes, e as caiarás com cal.

[[v5-27-3]]

^<<v5-27-3,3>>^ E, havendo-o passado, escreverás nelas todas as palavras desta lei, para entrares na terra que te der o Senhor teu Deus, terra que mana leite e mel, como te disse o senhor Deus de teus pais.

[[v5-27-4]]

^<<v5-27-4,4>>^ Será pois que , quando houveres passado o Jordão, levantareis estas pedras, que hoje vos ordeno, no monte Ebal, e as caiarás com cal.

[[v5-27-5]]

^<<v5-27-5,5>>^ E ali edificarás um altar ao Senhor teu Deus, um altar de pedras; não alçarás ferro sobre elas.

[[v5-27-6]]

^<<v5-27-6,6>>^ De pedras inteiras edificarás o altar do Senhor teu Deus: e sobre ele oferecerás holocaustos ao Senhor teu Deus.

[[v5-27-7]]

^<<v5-27-7,7>>^ Também sacrificarás ofertas pacíficas, e ali comerás perante o Senhor teu Deus, e te alegrarás.

[[v5-27-8]]

^<<v5-27-8,8>>^ E nestas pedras escreverás todas as palavras desta lei, exprimindo-as bem.

[[v5-27-9]]

^<<v5-27-9,9>>^ Falou mais Moisés, juntamente com os sacerdotes levitas, a todo o Israel, dizendo: Escuta e ouve, ó Israel! neste dia vieste a ser por povo ao Senhor teu Deus.

[[v5-27-10]]

^<<v5-27-10,10>>^ Portanto obedecerás à voz do Senhor teu Deus, e farás os seus mandamentos e os seus estatutos que hoje te ordeno.

[[v5-27-11]]

^<<v5-27-11,11>>^ E Moisés deu ordem naquele dia ao povo, dizendo:

[[v5-27-12]]

^<<v5-27-12,12>>^ Quando houverdes passado o Jordão, estes estarão sobre o monte Gerizim, para abençoarem o povo: Simeão, e Levi, e Judá, e Issacar, e José e Benjamim;

[[v5-27-13]]

^<<v5-27-13,13>>^ E estes estarão para amaldiçoar sobre o monte Ebal: Rúben, Gade, e Aser, e Zebulom, Dã e Naftali.

[[v5-27-14]]

^<<v5-27-14,14>>^ E os levitas protestarão a todo o povo de Israel em alta voz, e dirão:

[[v5-27-15]]

^<<v5-27-15,15>>^ Maldito o homem que fizer imagem de escultura, ou de fundição, abominação ao Senhor, obra da mão do artífice, e a  puser em um lugar  escondido, E todo o povo responderá, e dirá: Amém.

[[v5-27-16]]

^<<v5-27-16,16>>^ Maltito aquele que desprezar a seu pai ou a sua mãe: E todo o povo dirá: Amém.

[[v5-27-17]]

^<<v5-27-17,17>>^ Maldito aquele que arrancar o termo do seu próximo. E todo o povo dirá: Amém.

[[v5-27-18]]

^<<v5-27-18,18>>^ Maldito aquele que fizer que o cego erre do caminho. E todo o povo dirá: Amém.

[[v5-27-19]]

^<<v5-27-19,19>>^ Maldito aquele que perverter o direito do estrangeiro, do órfão e da viúva. E todo o povo dirá: Amém.

[[v5-27-20]]

^<<v5-27-20,20>>^ Maldito aquele que se deitar com a mulher de seu pai, porquanto descobriu a ourela de seu pai. E todo o povo dirá: Amém.

[[v5-27-21]]

^<<v5-27-21,21>>^ Maldito aquele que se deitar com algum  animal. E todo o povo dirá: Amém.

[[v5-27-22]]

^<<v5-27-22,22>>^ Maldito aquele que se deitar com sua irmã, filha de seu pai, ou filha de sua mãe. E todo o povo dirá: Amém.

[[v5-27-23]]

^<<v5-27-23,23>>^ Maldito aquele que se deitar com sua sogra. E todo o povo dirá: Amém.

[[v5-27-24]]

^<<v5-27-24,24>>^ Maldito aquele que ferir ao seu próximo em oculto. E todo o povo dirá: Amém.

[[v5-27-25]]

^<<v5-27-25,25>>^ Maldito aquele que tomar peita para matar a alguma pessoa  inocente. E todo o povo dirá: Amém.

[[v5-27-26]]

^<<v5-27-26,26>>^ Maldito aquele que não confirmar as palavras desta lei, não as cumprindo. E todo o povo dirá: Amém.

'''

xref:005-deuteronomio/005-deuteronomio-026.adoc#v5-26-0[&#60; Capítulo Anterior] | <<v5-27-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-028.adoc#v5-28-0[Próximo Capítulo &#62;]