include::./index.adoc[]

[[v34-3-0]]
=== Naum, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v34-3-1]]

^<<v34-3-1,1>>^ AI da cidade ensanguentada! Ela está toda cheia de mentiras e de rapina! não se aparta dela o roubo.

[[v34-3-2]]

^<<v34-3-2,2>>^ Estrépito do açoite há , e o estrondo do ruído das rodas; e os cavalos atropelam, e carros vão saltando.

[[v34-3-3]]

^<<v34-3-3,3>>^ O cavaleiro levanta a espada flamejante, e a lança relampagueante, e haverá  uma multidão de mortos, e abundância de cadáveres, e não terão fim os defuntos; tropeçarão nos seus corpos;

[[v34-3-4]]

^<<v34-3-4,4>>^ Por causa da multidão dos pecados da mui graciosa meretriz, da mestra das feitiçarias, que vendeu os povos com os seus deleites, e as gerações com as suas feitiçarias.

[[v34-3-5]]

^<<v34-3-5,5>>^ Eis que eu estou contra ti, diz o Senhor dos Exércitos, e te descobrirei na tua face, e às nações mostrarei a tua nudez, e aos reinos a tua vergonha.

[[v34-3-6]]

^<<v34-3-6,6>>^ E lançarei sobre ti cousas abomináveis, e te envergonharei, e pôr-te-ei como espetáculo.

[[v34-3-7]]

^<<v34-3-7,7>>^ E há de ser que, todos os que te virem, fugirão de ti, e dirão: Nínive está destruída; quem terá compaixão dela? donde buscarei consoladores para ti?

[[v34-3-8]]

^<<v34-3-8,8>>^ És tu melhor do que Nó-Amom, que está situada entre os rios, cercada de águas, tendo por esplanada o mar, e ainda o mar por muralha?

[[v34-3-9]]

^<<v34-3-9,9>>^ Etiópia e Egito eram  a sua força, e não tinha fim: Pute e Líbia foram o teu socorro.

[[v34-3-10]]

^<<v34-3-10,10>>^ Todavia ela foi levada, foi para o cativeiro: também os seus filhos foram despedaçados no topo de todas as ruas, e sobre os seus nobres lançaram sortes, e todos os seus grandes foram presos com grilhões.

[[v34-3-11]]

^<<v34-3-11,11>>^ Tu também serás embriagada, e te esconderás; também buscarás força por causa do inimigo.

[[v34-3-12]]

^<<v34-3-12,12>>^ Todas as tuas fortalezas serão como  figueiras com figos temporãos; se se sacodem, caem na boca do que os há de comer.

[[v34-3-13]]

^<<v34-3-13,13>>^ Eis que o teu povo no meio de ti será como  mulheres: as portas da tua terra estarão de todo abertas aos teus inimigos: o fogo consumirá os teus ferrolhos.

[[v34-3-14]]

^<<v34-3-14,14>>^ Tira águas para o cerco, fortifica as tuas fortalezas, entra no lodo, e pisa o barro, repara o forno para os ladrilhos.

[[v34-3-15]]

^<<v34-3-15,15>>^ O fogo ali te consumirá, a espada te exterminará; consumir-te-á como a locusta; multiplica-te como a locusta, multiplica-te como os gafanhotos.

[[v34-3-16]]

^<<v34-3-16,16>>^ Multiplicaste os teus negociantes mais do que as estrelas do céu; a locusta se espalhará, e voará.

[[v34-3-17]]

^<<v34-3-17,17>>^ Os teus coroados são  como os gafanhotos, e os teus chefes como os gafanhotos grandes, que se acampam nas sebes nos dias de frio; em subindo o sol voam, e não se conhece o lugar onde estão.

[[v34-3-18]]

^<<v34-3-18,18>>^ Os teus pastores dormitarão, ó rei da Assíria; os teus ilustres deitar-se-ão, o teu povo se derramará pelos montes, sem que haja quem possa ajuntá-los.

[[v34-3-19]]

^<<v34-3-19,19>>^ Não há  cura para a tua ferida; a tua chaga é dolorosa: todos os que ouvirem a tua fama baterão as palmas sobre ti; porque, sobre quem não passou continuamente a tua malícia?

'''

xref:034-naum/034-naum-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[Próximo Capítulo &#62;]