include::./index.adoc[]

[[v34-2-0]]
=== Naum, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v34-2-1]]

^<<v34-2-1,1>>^ O DESTRUIDOR está já diante de ti: guarda tu a fortaleza, observa o caminho, esforça os lombos, fortalece muito o teu poder.

[[v34-2-2]]

^<<v34-2-2,2>>^ Porque o Senhor trará outra vez a excelência de Jacó, como a excelência de Israel; porque os que despejam os despejaram, e corromperam os seus sarmentos.

[[v34-2-3]]

^<<v34-2-3,3>>^ Os escudos dos seus valentes estarão vermelhos, os homens valorosos escarlates, os carros como fogo de tochas no dia da sua preparação, e as lanças se sacudirão terrivelmente.

[[v34-2-4]]

^<<v34-2-4,4>>^ Os carros se enfurecerão nas praças, chocar-se-ão pelas ruas: o seu parecer é  como o de tochas, correrão como relâmpagos.

[[v34-2-5]]

^<<v34-2-5,5>>^ Este se lembrará das suas riquezas: eles porém  tropeçarão na sua marcha: apresentar-se-ão no muro, quando o amparo for preparado.

[[v34-2-6]]

^<<v34-2-6,6>>^ As portas do rio se abrirão, e o palácio se derreterá.

[[v34-2-7]]

^<<v34-2-7,7>>^ E Huzabe está descoberta; será levada cativa, e as suas servas a acompanharão, gemendo como pombas, batendo em seus peitos.

[[v34-2-8]]

^<<v34-2-8,8>>^ Nínive desde que existe tem sido como um tanque de águas; elas porém fogem agora.  Parai, parai, clamar-se-á ; mas ninguém olhará para trás.

[[v34-2-9]]

^<<v34-2-9,9>>^ Saqueai a prata, saqueai o ouro, porque não tem termo o provimento, abastança há de todo o gênero de móveis apetecíveis.

[[v34-2-10]]

^<<v34-2-10,10>>^ Vazia, e esgotada e devastada ficará: e derrete-se o coração, e tremem os joelhos, e em todos os lombos há dor; e os rostos de todos eles empalidecem.

[[v34-2-11]]

^<<v34-2-11,11>>^ Onde está agora  o covil dos leões, e as pastagens dos leõezinhos, onde passeava o leão velho, e  o cachorro do leão, sem haver ninguém que os  espantasse?

[[v34-2-12]]

^<<v34-2-12,12>>^ O leão arrebatava o que bastava para os seus cachorros, e estrangulava a presa para as suas leoas, e enchia de presas as suas cavernas, e os seus covis de rapina.

[[v34-2-13]]

^<<v34-2-13,13>>^ Eis que eu estou contra ti, diz o Senhor dos exércitos, e queimarei no fumo os teus carros, e a espada devorará os teus leõezinhos, e arrancarei da terra a tua presa, e não se ouvirá mais a voz dos teus embaixadores.

'''

xref:034-naum/034-naum-001.adoc#v34-1-0[&#60; Capítulo Anterior] | <<v34-2-0,Topo>> | xref:034-naum/034-naum-003.adoc#v34-3-0[Próximo Capítulo &#62;]