include::./index.adoc[]

[[v48-5-0]]
=== Gálatas, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v48-5-1]]

^<<v48-5-1,1>>^ ESTAI pois firmes na liberdade com que Cristo nos libertou, e não torneis a meter-vos debaixo do jugo da servidão.

[[v48-5-2]]

^<<v48-5-2,2>>^ Eis que eu, Paulo, vos digo que, se vos deixardes circuncidar, Cristo de nada vos aproveitará.

[[v48-5-3]]

^<<v48-5-3,3>>^ E de novo protesto a todo o homem, que se deixa circuncidar, que está obrigado a guardar toda a lei.

[[v48-5-4]]

^<<v48-5-4,4>>^ Separados estais de Cristo, vós os que vos justificais pela lei: da graça tendes caído.

[[v48-5-5]]

^<<v48-5-5,5>>^ Porque nós pelo espírito da fé aguardamos a esperança da justiça.

[[v48-5-6]]

^<<v48-5-6,6>>^ Porque em Jesus Cristo nem a circuncisão nem a incircuncisão tem virtude alguma; mas sim a fé que opera por caridade.

[[v48-5-7]]

^<<v48-5-7,7>>^ Corríeis bem; quem vos impediu, para que não obedeçais à verdade?

[[v48-5-8]]

^<<v48-5-8,8>>^ Esta persuasão não vem  daquele que vos chamou.

[[v48-5-9]]

^<<v48-5-9,9>>^ Um pouco de fermento leveda toda a massa.

[[v48-5-10]]

^<<v48-5-10,10>>^ Confio de vós, no Senhor, que nenhuma outra coisa sentireis; mas aquele que vos inquieta, seja ele quem for, sofrerá a condenação.

[[v48-5-11]]

^<<v48-5-11,11>>^ Eu, porém, irmãos, se prego ainda a circuncisão, por que sou pois perseguido? logo o escândalo da cruz está aniquilado.

[[v48-5-12]]

^<<v48-5-12,12>>^ Eu quereria que fossem cortados aqueles que vos andam inquietando.

[[v48-5-13]]

^<<v48-5-13,13>>^ Porque vós, irmãos, fostes chamados à liberdade. Não useis  então da liberdade para dar  ocasião à carne, mas servi-vos uns aos outros pela caridade.

[[v48-5-14]]

^<<v48-5-14,14>>^ Porque toda a lei se cumpre numa só  palavra, nesta: Amarás ao teu próximo como a ti mesmo.

[[v48-5-15]]

^<<v48-5-15,15>>^ Se vós, porém, vos mordeis e devorais uns aos outros, vede não vos consumais também uns aos outros.

[[v48-5-16]]

^<<v48-5-16,16>>^ Digo, porém: Andai em Espírito, e não cumprireis a concupiscência da carne.

[[v48-5-17]]

^<<v48-5-17,17>>^ Porque a carne cobiça contra o Espírito, e o Espírito contra a carne; e estes opõem-se um ao outro: para que não façais o que quereis.

[[v48-5-18]]

^<<v48-5-18,18>>^ Mas, se sois guiados pelo Espírito, não estais debaixo da lei.

[[v48-5-19]]

^<<v48-5-19,19>>^ Porque as obras da carne são manifestas, as quais são: Prostituição, impureza, lascívia,

[[v48-5-20]]

^<<v48-5-20,20>>^ Idolatria, feitiçarias, inimizades, porfias, emulações, iras, pelejas, dissensões, heresias,

[[v48-5-21]]

^<<v48-5-21,21>>^ Invejas, homicídios, bebedices, glutonarias, e coisas semelhantes a estas, acerca das quais vos declaro, como já antes vos disse, que os que cometem tais coisas  não herdarão o reino de Deus.

[[v48-5-22]]

^<<v48-5-22,22>>^ Mas o fruto do Espírito é: caridade, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança.

[[v48-5-23]]

^<<v48-5-23,23>>^ Contra estas coisas  não há lei.

[[v48-5-24]]

^<<v48-5-24,24>>^ E os que são de Cristo crucificaram a carne com as suas paixões e concupiscências.

[[v48-5-25]]

^<<v48-5-25,25>>^ Se vivemos em Espírito, andemos também em Espírito.

[[v48-5-26]]

^<<v48-5-26,26>>^ Não sejamos cobiçosos de vanglórias, irritando-nos uns aos outros, invejando-nos uns aos outros.

'''

xref:048-galatas/048-galatas-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatas/048-galatas-006.adoc#v48-6-0[Próximo Capítulo &#62;]