include::./index.adoc[]

[[v48-2-0]]
=== Gálatas, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v48-2-1]]

^<<v48-2-1,1>>^ DEPOIS, passados quatorze anos, subi outra vez a Jerusalém com Barnabé, levando também comigo Tito.

[[v48-2-2]]

^<<v48-2-2,2>>^ E subi por uma revelação, e lhes expus o evangelho, que prego entre os gentios, e particularmente aos que estavam em estima; para que de maneira alguma não corresse ou não tivesse corrido em vão.

[[v48-2-3]]

^<<v48-2-3,3>>^ Mas nem ainda Tito, que estava comigo, sendo grego, foi constrangido a circuncidar-se;

[[v48-2-4]]

^<<v48-2-4,4>>^ E isto  por causa dos falsos irmãos que se tinham entremetido, e secretamente entraram a espiar a nossa liberdade, que temos em Cristo Jesus, para nos porem em servidão;

[[v48-2-5]]

^<<v48-2-5,5>>^ Aos quais nem ainda por uma hora cedemos com sujeição, para que a verdade do evangelho permanecesse entre vós.

[[v48-2-6]]

^<<v48-2-6,6>>^ E, quanto àqueles que pareciam ser alguma coisa (quais tenham sido noutro tempo, não se me dá; Deus não aceita a aparência do homem), esses, digo, que pareciam ser alguma coisa , nada me comunicaram;

[[v48-2-7]]

^<<v48-2-7,7>>^ Antes, pelo contrário, quando viram que o evangelho da incircuncisão me estava confiado, como a Pedro o da circuncisão

[[v48-2-8]]

^<<v48-2-8,8>>^ (Porque aquele que operou eficazmente em Pedro para o apostolado da circuncisão esse operou também em mim com eficácia para com os gentios),

[[v48-2-9]]

^<<v48-2-9,9>>^ E conhecendo Tiago, Cefas e João, que eram considerados como as colunas, a graça que se me havia dado, deram-nos as destras, em comunhão comigo e com Barnabé, para que nós fôssemos  aos gentios, e eles à circuncisão;

[[v48-2-10]]

^<<v48-2-10,10>>^ Recomendando-nos  somente que nos lembrássemos dos pobres: o que também procurei fazer com diligência.

[[v48-2-11]]

^<<v48-2-11,11>>^ E, chegando Pedro à Antioquia, lhe resisti na cara, porque era repreensível.

[[v48-2-12]]

^<<v48-2-12,12>>^ Porque, antes que alguns tivessem chegado da parte de Tiago, comia com os gentios; mas, depois que chegaram, se foi retirando, e, se apartou deles , temendo os que eram da circuncisão.

[[v48-2-13]]

^<<v48-2-13,13>>^ E os outros judeus também dissimulavam com ele, de maneira que até Barnabé se deixou levar pela sua dissimulação.

[[v48-2-14]]

^<<v48-2-14,14>>^ Mas, quando vi que não andavam bem e direitamente conforme a verdade do evangelho, disse a Pedro na presença de todos: Se tu, sendo judeu, vives como os gentios, e não como judeu, por que obrigas os gentios a viverem como judeus?

[[v48-2-15]]

^<<v48-2-15,15>>^ Nós somos  judeus por natureza e não pecadores dentre os gentios.

[[v48-2-16]]

^<<v48-2-16,16>>^ Sabendo que o homem não é justificado pelas obras da lei, mas pela fé em Jesus Cristo, temos também crido em Jesus Cristo, para sermos justificados pela fé de Cristo, e não pelas obras da lei; porquanto pelas obras da lei nenhuma carne será justificada.

[[v48-2-17]]

^<<v48-2-17,17>>^ Pois, se nós, que procuramos ser justificados em Cristo, nós mesmos também somos achados pecadores, é porventura Cristo ministro do pecado? De maneira nenhuma.

[[v48-2-18]]

^<<v48-2-18,18>>^ Porque, se torno a edificar aquilo que destruí, constituo-me a mim mesmo transgressor.

[[v48-2-19]]

^<<v48-2-19,19>>^ Porque eu pela lei estou morto para a lei, para viver para Deus.

[[v48-2-20]]

^<<v48-2-20,20>>^ Já  estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo na carne vivo-a na fé do Filho de Deus, o qual me amou, e se entregou a si mesmo por mim.

[[v48-2-21]]

^<<v48-2-21,21>>^ Não aniquilo a graça de Deus; porque, se a justiça provém  da lei, segue-se que Cristo morreu debalde.

'''

xref:048-galatas/048-galatas-001.adoc#v48-1-0[&#60; Capítulo Anterior] | <<v48-2-0,Topo>> | xref:048-galatas/048-galatas-003.adoc#v48-3-0[Próximo Capítulo &#62;]