include::./index.adoc[]

[[v48-6-0]]
=== Gálatas, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v48-6-1]]

^<<v48-6-1,1>>^ IRMÃOS, se algum homem chegar a ser surpreendido nalguma ofensa, vós, que sois espirituais, encaminhai o tal com espírito de mansidão; olhando por ti mesmo, para que não sejas também tentado.

[[v48-6-2]]

^<<v48-6-2,2>>^ Levai as cargas uns dos outros, e assim cumprireis a lei de Cristo.

[[v48-6-3]]

^<<v48-6-3,3>>^ Porque, se alguém cuida ser alguma coisa, não sendo nada, engana-se a si mesmo.

[[v48-6-4]]

^<<v48-6-4,4>>^ Mas prove cada um a sua própria obra, e terá glória só em si mesmo, e não noutro.

[[v48-6-5]]

^<<v48-6-5,5>>^ Porque cada qual levará a sua própria carga.

[[v48-6-6]]

^<<v48-6-6,6>>^ E o que é instruído na palavra reparta de todos os seus  bens com aquele que o instrui.

[[v48-6-7]]

^<<v48-6-7,7>>^ Não erreis: Deus não se deixa escarnecer; porque tudo o que o homem semear, isso também ceifará.

[[v48-6-8]]

^<<v48-6-8,8>>^ Porque o que semeia na sua carne, da carne ceifará a corrupção; mas o que semeia no Espírito, do Espírito ceifará a vida eterna.

[[v48-6-9]]

^<<v48-6-9,9>>^ E não nos cansemos de fazer bem, porque a seu tempo ceifaremos, se não houvermos desfalecido.

[[v48-6-10]]

^<<v48-6-10,10>>^ Então, enquanto temos tempo, façamos bem a todos, mas principalmente aos domésticos da fé.

[[v48-6-11]]

^<<v48-6-11,11>>^ Vede com que grandes letras vos escrevi por minha mão.

[[v48-6-12]]

^<<v48-6-12,12>>^ Todos os que querem mostrar boa aparência na carne, esses vos obrigam a circuncidar-vos, somente para não serem perseguidos por causa da cruz de Cristo.

[[v48-6-13]]

^<<v48-6-13,13>>^ Porque nem ainda esses mesmos que se circuncidam guardam a lei, mas querem que vos circuncideis, para se gloriarem na vossa carne.

[[v48-6-14]]

^<<v48-6-14,14>>^ Mas longe esteja de mim gloriar-me, a não ser na cruz de nosso Senhor Jesus Cristo, pela qual o mundo está crucificado para mim e eu para o mundo.

[[v48-6-15]]

^<<v48-6-15,15>>^ Porque em Cristo Jesus nem a circuncisão nem a incircuncisão tem virtude alguma, mas sim o ser uma nova criatura.

[[v48-6-16]]

^<<v48-6-16,16>>^ E a todos quantos andarem conforme esta regra, paz e misericórdia sobre eles e sobre o Israel de Deus.

[[v48-6-17]]

^<<v48-6-17,17>>^ Desde agora ninguém me inquiete; porque trago no meu corpo as marcas do Senhor Jesus.

[[v48-6-18]]

^<<v48-6-18,18>>^ A graça de nosso Senhor Jesus Cristo seja , irmãos, com o vosso espírito. Amém.

'''

xref:048-galatas/048-galatas-005.adoc#v48-5-0[&#60; Capítulo Anterior] | <<v48-6-0,Topo>> | xref:049-efesios/049-efesios-001.adoc#v49-1-0[Próximo Capítulo &#62;]