include::./index.adoc[]

[[v21-2-0]]
=== Eclesiastes, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v21-2-1]]

^<<v21-2-1,1>>^ DISSE eu no meu coração: Ora vem, eu te provarei com a alegria; portanto goza o prazer; mas eis que também isto era  vaidade.

[[v21-2-2]]

^<<v21-2-2,2>>^ Do riso disse: Está  doido; e da alegria: De que serve esta?

[[v21-2-3]]

^<<v21-2-3,3>>^ Busquei no meu coração como me daria ao vinho (regendo porém o meu coração com sabedoria), e como reterei a loucura, até ver o que seria melhor que os filhos dos homens fizessem debaixo do céu, durante  o número dos dias de sua vida.

[[v21-2-4]]

^<<v21-2-4,4>>^ Fiz para mim obras magníficas: edifiquei para mim casas: plantei para mim vinhas.

[[v21-2-5]]

^<<v21-2-5,5>>^ Fiz para mim hortas e jardins, e plantei neles árvores de toda a espécie  de fruto.

[[v21-2-6]]

^<<v21-2-6,6>>^ Fiz para mim tanques de águas, para regar com eles o bosque em que reverdeciam as árvores.

[[v21-2-7]]

^<<v21-2-7,7>>^ Adquiri servos e servas, e tive servos nascidos em casa; também tive grande possessão de vacas e ovelhas, mais do que todos os que houve antes de mim em Jerusalém.

[[v21-2-8]]

^<<v21-2-8,8>>^ Amontoei também para mim prata e ouro, e joias de reis e das províncias; provi-me de cantores e cantoras, e das delícias dos filhos dos homens, e de instrumentos de música de toda a sorte.

[[v21-2-9]]

^<<v21-2-9,9>>^ E engrandeci-me, e aumentei mais do que todos os que houve antes de mim em Jerusalém: perseverou também comigo a minha sabedoria.

[[v21-2-10]]

^<<v21-2-10,10>>^ E tudo quanto desejaram os meus olhos não lho neguei, nem privei o meu coração de alegria alguma; mas o meu coração se alegrou por todo o meu trabalho, e esta foi a minha porção de todo o meu trabalho.

[[v21-2-11]]

^<<v21-2-11,11>>^ E olhei eu para todas as obras que fizeram as minhas mãos, como também para o trabalho que eu, trabalhando, tinha feito, e  eis que tudo era  vaidade e aflição de espírito, e que  proveito nenhum havia  debaixo do sol.

[[v21-2-12]]

^<<v21-2-12,12>>^ Então passei à contemplação da sabedoria, e dos desvarios, e da doidice; porque, que fará o homem que seguir ao rei? o mesmo que outros já fizeram;

[[v21-2-13]]

^<<v21-2-13,13>>^ Então vi eu que a sabedoria é mais excelente do que a estultícia, quanto a luz é mais excelente do que as trevas.

[[v21-2-14]]

^<<v21-2-14,14>>^ Os olhos do sábio estão  na sua cabeça, mas o louco anda em trevas: também então entendi eu que o mesmo lhes sucede a todos.

[[v21-2-15]]

^<<v21-2-15,15>>^ Pelo que eu disse no meu coração: Como acontece ao tolo, assim me sucederá a mim; por que então busquei eu mais a sabedoria? Então disse no meu coração que também isto era  vaidade.

[[v21-2-16]]

^<<v21-2-16,16>>^ Porque nunca haverá  mais lembrança do sábio do que do tolo; porquanto de tudo nos dias futuros total esquecimento haverá. E como morre o sábio, assim morre o tolo!

[[v21-2-17]]

^<<v21-2-17,17>>^ Pelo que aborreci esta vida, porque a obra que se faz debaixo do sol me era penosa; sim, tudo é  vaidade e aflição de espírito.

[[v21-2-18]]

^<<v21-2-18,18>>^ Também eu aborreci todo o meu trabalho, em que trabalhei debaixo do sol, visto como eu havia de deixá-lo ao homem que viesse depois de mim.

[[v21-2-19]]

^<<v21-2-19,19>>^ E quem sabe se será sábio ou tolo? contudo, ele se assenhoreará de todo o meu trabalho em que trabalhei, e em que me houve sabiamente debaixo do sol; também isto é  vaidade.

[[v21-2-20]]

^<<v21-2-20,20>>^ Pelo que eu me apliquei a fazer que o meu coração perdesse a esperança de todo o trabalho, em que trabalhei debaixo do sol.

[[v21-2-21]]

^<<v21-2-21,21>>^ Porque há homem cujo trabalho é feito com sabedoria, e ciência, e destreza; contudo, a um  homem que não trabalhou nele, o deixará como porção sua; também isto é  vaidade e grande enfado.

[[v21-2-22]]

^<<v21-2-22,22>>^ Porque, que mais  tem o homem de todo o seu trabalho, e da fadiga do seu coração, em que ele anda trabalhando debaixo do sol?

[[v21-2-23]]

^<<v21-2-23,23>>^ Porque todos os seus dias são  dores, e a sua ocupação é  desgosto; até de noite não descansa o seu coração: também isto é vaidade.

[[v21-2-24]]

^<<v21-2-24,24>>^ Não é pois  bom para o homem que coma e beba, e que  faça gozar a sua alma do bem do seu trabalho? Isto também eu vi que vem  da mão de Deus.

[[v21-2-25]]

^<<v21-2-25,25>>^ (Porque quem pode comer, ou quem pode gozar melhor  do que eu?)

[[v21-2-26]]

^<<v21-2-26,26>>^ Porque ao homem que é  bom diante dele, dá Deus sabedoria e conhecimento e alegria; mas ao pecador dá trabalho, para que ele ajunte, e amontoe, e o dê ao bom perante a sua face. Também isto é  vaidade e aflição de espírito.

'''

xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[&#60; Capítulo Anterior] | <<v21-2-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[Próximo Capítulo &#62;]