include::./index.adoc[]

[[v21-7-0]]
=== Eclesiastes, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v21-7-1]]

^<<v21-7-1,1>>^ MELHOR é  a boa  fama do que o melhor unguento, e o dia da morte do que o dia do nascimento de alguém.

[[v21-7-2]]

^<<v21-7-2,2>>^ Melhor é  ir à casa onde há luto do que ir à casa onde há banquete, porque  ali se vê o fim de todos os homens; e os vivos o aplicam ao seu coração.

[[v21-7-3]]

^<<v21-7-3,3>>^ Melhor é  a tristeza do que o riso, porque com a tristeza do rosto se faz melhor o coração.

[[v21-7-4]]

^<<v21-7-4,4>>^ O coração dos sábios está  na casa do luto, mas o coração dos tolos na casa da alegria.

[[v21-7-5]]

^<<v21-7-5,5>>^ Melhor é  ouvir a repreensão do sábio, do que ouvir alguém a canção do tolo.

[[v21-7-6]]

^<<v21-7-6,6>>^ Porque qual o crepitar dos espinhos debaixo duma  panela, tal é o  riso do tolo: também isto é  vaidade.

[[v21-7-7]]

^<<v21-7-7,7>>^ Verdadeiramente a opressão faz endoidecer até  o sábio, e a peita corrompe o coração.

[[v21-7-8]]

^<<v21-7-8,8>>^ Melhor é  o fim das cousas do que o princípio delas: melhor é  o longânimo do que o altivo de coração.

[[v21-7-9]]

^<<v21-7-9,9>>^ Não te apresses no teu espírito a irar-te, porque a ira abriga-se no seio dos tolos.

[[v21-7-10]]

^<<v21-7-10,10>>^ Nunca digas: Por que foram os dias passados melhores do que estes? porque nunca com sabedoria isto perguntarias.

[[v21-7-11]]

^<<v21-7-11,11>>^ Tão boa é  a sabedoria como a herança, e dela tiram proveito os que veem o sol.

[[v21-7-12]]

^<<v21-7-12,12>>^ Porque a sabedoria serve de sombra, como de sombra serve o dinheiro; mas a excelência da sabedoria é  que ela dá vida ao seu possuidor.

[[v21-7-13]]

^<<v21-7-13,13>>^ Atenta para a obra de Deus; porque quem poderá endireitar o que ele fez torto?

[[v21-7-14]]

^<<v21-7-14,14>>^ No dia da prosperidade goza do bem, mas no dia da adversidade considera; porque  também Deus fez a este em oposição àquele, para que o homem nada ache que tenha de vir depois dele.

[[v21-7-15]]

^<<v21-7-15,15>>^ Tudo isto vi nos dias da minha vaidade; há um  justo que perece na sua justiça, e há um  ímpio que prolonga os seus dias  na sua maldade.

[[v21-7-16]]

^<<v21-7-16,16>>^ Não sejas demasiadamente justo, nem demasiadamente sábio: porque te destruirias a ti mesmo ?

[[v21-7-17]]

^<<v21-7-17,17>>^ Não sejas demasiadamente ímpio, nem sejas louco: por que morrerias fora de teu tempo?

[[v21-7-18]]

^<<v21-7-18,18>>^ Bom é  que retenhas isto, e também disto não retires a tua mão; porque quem teme a Deus escapa de tudo isto.

[[v21-7-19]]

^<<v21-7-19,19>>^ A sabedoria fortalece ao sábio, mais do que dez governadores que haja na cidade.

[[v21-7-20]]

^<<v21-7-20,20>>^ Na verdade que  não há  homem justo sobre a terra, que faça bem, e nunca peque.

[[v21-7-21]]

^<<v21-7-21,21>>^ Tão pouco apliques o teu coração a todas as palavras que se disserem, para que não venhas a ouvir que o teu servo te amaldiçoa.

[[v21-7-22]]

^<<v21-7-22,22>>^ Porque o teu coração também já  confessou muitas vezes que tu amaldiçoaste a outros.

[[v21-7-23]]

^<<v21-7-23,23>>^ Tudo isto inquiri com sabedoria; e disse: Sabedoria adquirirei; mas ela ainda  estava longe de mim.

[[v21-7-24]]

^<<v21-7-24,24>>^ Longe está o que foi, e profundíssimo; quem o achará?

[[v21-7-25]]

^<<v21-7-25,25>>^ Eu tornei a voltar-me, e determinei em meu coração saber, e inquirir, e buscar a sabedoria e a razão, e conhecer a loucura da impiedade e a doidice dos desvarios.

[[v21-7-26]]

^<<v21-7-26,26>>^ E eu achei uma cousa mais amarga do que a morte, a mulher cujo coração são redes e laços, e  cujas mãos são ataduras: quem for bom diante de Deus escapará dela, mas o pecador virá a ser preso por ela.

[[v21-7-27]]

^<<v21-7-27,27>>^ Vedes aqui, isto achei diz o pregador, conferindo uma cousa com a outra para achar a causa;

[[v21-7-28]]

^<<v21-7-28,28>>^ Causa que a minha alma ainda busca, mas não a achei; um homem entre mil achei eu , mas uma mulher entre todas estas não achei.

[[v21-7-29]]

^<<v21-7-29,29>>^ Vede, isto tão somente achei: que Deus fez ao homem reto, mas eles buscaram muitas invenções.

'''

xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[&#60; Capítulo Anterior] | <<v21-7-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-008.adoc#v21-8-0[Próximo Capítulo &#62;]