include::./index.adoc[]

[[v21-10-0]]
=== Eclesiastes, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v21-10-1]]

^<<v21-10-1,1>>^ ASSIM como a mosca morta faz exalar mau cheiro e inutilizar o unguento do perfumador, assim  é para o famoso em sabedoria e em honra uma  pouca de estultícia.

[[v21-10-2]]

^<<v21-10-2,2>>^ O coração do sábio está  à sua mão direita mas o coração do tolo está  à sua esquerda.

[[v21-10-3]]

^<<v21-10-3,3>>^ E, até quando o tolo vai pelo caminho, lhe falta entendimento e diz a todos que é  tolo.

[[v21-10-4]]

^<<v21-10-4,4>>^ Levantando-se contra ti o espírito do governador, não deixes o teu lugar, porque o acordo é um  remédio que  aquieta grandes pecados.

[[v21-10-5]]

^<<v21-10-5,5>>^ Ainda  há um mal que  vi debaixo do sol, como o erro que  procede do governador.

[[v21-10-6]]

^<<v21-10-6,6>>^ Ao tolo assentam-no em grandes alturas, mas os ricos estão assentados em lugar baixo.

[[v21-10-7]]

^<<v21-10-7,7>>^ Vi os servos a cavalo, e os príncipes que andavam a pé  como servos sobre a terra.

[[v21-10-8]]

^<<v21-10-8,8>>^ Quem fizer uma  cova cairá nela, e, quem romper um  muro, uma  cobra o morderá.

[[v21-10-9]]

^<<v21-10-9,9>>^ Quem acarretar pedras, será maltratado por elas, e o que rachar lenha expõe-se ao perigo.

[[v21-10-10]]

^<<v21-10-10,10>>^ Se estiver embotado o ferro, e não se afiar o corte, então se devem pôr mais forças; mas a sabedoria é  excelente para dirigir.

[[v21-10-11]]

^<<v21-10-11,11>>^ Se a cobra morder antes de estar encantada, então remédio nenhum haverá no mais hábil encantador.

[[v21-10-12]]

^<<v21-10-12,12>>^ Nas palavras da boca do sábio há  favor, mas os lábios do tolo o devoram.

[[v21-10-13]]

^<<v21-10-13,13>>^ O princípio das palavras da sua boca é  a estultícia, e o fim da sua boca um  desvario péssimo.

[[v21-10-14]]

^<<v21-10-14,14>>^ Bem que  o tolo multiplique as palavras, não sabe o homem o que será; e quem lhe fará saber o que será depois dele?

[[v21-10-15]]

^<<v21-10-15,15>>^ O trabalho dos tolos a cada um deles fatiga, pois não sabem como ir à cidade.

[[v21-10-16]]

^<<v21-10-16,16>>^ Ai de ti, ó terra, cujo rei é  criança, e cujos príncipes comem de manhã.

[[v21-10-17]]

^<<v21-10-17,17>>^ Bem-aventurada tu, ó terra, cujo rei é filho dos nobres, e cujos príncipes comem a tempo, para refazerem  as forças, e não para bebedice.

[[v21-10-18]]

^<<v21-10-18,18>>^ Pela muita preguiça se enfraquece o teto, e pela frouxidão das mãos goteja a casa.

[[v21-10-19]]

^<<v21-10-19,19>>^ Para rir se fazem convites, e o vinho alegra a vida, e por tudo o dinheiro responde.

[[v21-10-20]]

^<<v21-10-20,20>>^ Nem ainda no teu pensamento amaldiçoes ao rei, nem tão pouco no mais interior da tua recâmara amaldiçoes ao rico: porque as aves dos céus levariam a voz, e o que tem asas daria notícia da palavra.

'''

xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[&#60; Capítulo Anterior] | <<v21-10-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-011.adoc#v21-11-0[Próximo Capítulo &#62;]