include::./index.adoc[]

[[v21-3-0]]
=== Eclesiastes, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v21-3-1]]

^<<v21-3-1,1>>^ TUDO tem  o seu  tempo determinado, e há tempo para todo o propósito debaixo do céu:

[[v21-3-2]]

^<<v21-3-2,2>>^ Há  tempo de nascer, e tempo de morrer: tempo de plantar, e tempo de arrancar o que se plantou:

[[v21-3-3]]

^<<v21-3-3,3>>^ Tempo de matar, e tempo de curar: tempo de derribar, e tempo de edificar:

[[v21-3-4]]

^<<v21-3-4,4>>^ Tempo de chorar, e tempo de rir: tempo de prantear, e tempo de saltar:

[[v21-3-5]]

^<<v21-3-5,5>>^ Tempo de espalhar pedras, e tempo de ajuntar pedras: tempo de abraçar, e tempo de afastar-se de abraçar:

[[v21-3-6]]

^<<v21-3-6,6>>^ Tempo de buscar, e tempo de perder: tempo de guardar, e tempo de deitar fora:

[[v21-3-7]]

^<<v21-3-7,7>>^ Tempo de rasgar, e tempo de coser: tempo de estar calado, e tempo de falar:

[[v21-3-8]]

^<<v21-3-8,8>>^ Tempo de amar, e tempo de aborrecer: tempo de guerra, e tempo de paz.

[[v21-3-9]]

^<<v21-3-9,9>>^ Que vantagem tem o trabalhador naquilo em que trabalha?

[[v21-3-10]]

^<<v21-3-10,10>>^ Tenho visto o trabalho que Deus deu aos filhos dos homens, para com ele os afligir.

[[v21-3-11]]

^<<v21-3-11,11>>^ Tudo fez formoso em seu tempo: também pôs o mundo no coração deles, sem que o homem possa descobrir a obra que Deus fez desde o princípio até ao fim.

[[v21-3-12]]

^<<v21-3-12,12>>^ Já  tenho conhecido que não há cousa  melhor para eles do que alegrarem-se e fazerem bem na sua vida;

[[v21-3-13]]

^<<v21-3-13,13>>^ E também que todo o homem coma e beba, e goze do bem de todo o seu trabalho: isto é um  dom de Deus.

[[v21-3-14]]

^<<v21-3-14,14>>^ Eu sei que tudo quanto Deus faz durará eternamente: nada se lhe deve acrescentar, e  nada se lhe deve tirar; e isto  faz Deus para que haja temor diante dele.

[[v21-3-15]]

^<<v21-3-15,15>>^ O que é, já foi; e o que há de ser, também já foi; e Deus pede conta do que passou.

[[v21-3-16]]

^<<v21-3-16,16>>^ Vi mais debaixo do sol: no lugar do juízo, impiedade; e no lugar da justiça, impiedade ainda.

[[v21-3-17]]

^<<v21-3-17,17>>^ Eu disse no meu coração: Deus julgará o justo e o ímpio; porque há um tempo para  todo o intento e para toda a obra.

[[v21-3-18]]

^<<v21-3-18,18>>^ Disse eu no meu coração: é por causa dos filhos dos homens, para que Deus possa prová-los, e eles possam ver que são em si mesmos como os animais.

[[v21-3-19]]

^<<v21-3-19,19>>^ Porque o que sucede aos filhos dos homens, isso mesmo também sucede aos animais; a mesma cousa lhes sucede: como morre um, assim morre o outro, todos têm o mesmo fôlego; e a vantagem dos homens sobre os animais não é nenhuma, porque todos são  vaidade.

[[v21-3-20]]

^<<v21-3-20,20>>^ Todos vão para um lugar: todos são pó, e todos ao pó tornarão.

[[v21-3-21]]

^<<v21-3-21,21>>^ Quem adverte que o fôlego dos filhos dos homens sobe para cima, e que o fôlego dos animais desce para baixo da terra?

[[v21-3-22]]

^<<v21-3-22,22>>^ Assim que tenho visto que não há  cousa melhor do que alegrar-se o homem nas suas obras, porque essa é  a sua porção; porque quem o fará voltar para ver o que será depois dele?

'''

xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[&#60; Capítulo Anterior] | <<v21-3-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[Próximo Capítulo &#62;]