include::./index.adoc[]

[[v21-11-0]]
=== Eclesiastes, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v21-11-1]]

^<<v21-11-1,1>>^ LANÇA o teu pão sobre as águas, porque depois de muitos dias o acharás.

[[v21-11-2]]

^<<v21-11-2,2>>^ Reparte com sete, e ainda até  com oito, porque não sabes que mal haverá sobre a terra.

[[v21-11-3]]

^<<v21-11-3,3>>^ Estando as nuvens cheias, derramam a chuva sobre a terra, e caindo a árvore para o sul, ou para o norte, no lugar em que a árvore cair ali ficará.

[[v21-11-4]]

^<<v21-11-4,4>>^ Quem observa o vento, nunca semeará, e o que olha para as nuvens nunca segará.

[[v21-11-5]]

^<<v21-11-5,5>>^ Assim como tu não sabes qual o caminho do vento, nem como se formam  os ossos no ventre da que está grávida, assim também não sabes as obras de Deus, que faz todas as cousas.

[[v21-11-6]]

^<<v21-11-6,6>>^ Pela manhã semeia a tua semente, e à tarde não retires a tua mão, porque tu não sabes qual prosperará: se esta, se aquela, ou se ambas igualmente serão  boas.

[[v21-11-7]]

^<<v21-11-7,7>>^ Verdadeiramente suave é  a luz, e agradável é  aos olhos ver o sol.

[[v21-11-8]]

^<<v21-11-8,8>>^ Mas se o homem viver muitos anos, e  em todos eles se alegrar, também se deve lembrar dos dias das trevas, porque hão de ser muitos. Tudo quanto sucede é vaidade.

[[v21-11-9]]

^<<v21-11-9,9>>^ Alegra-te, mancebo, na tua mocidade, e recreie-se o teu coração nos dias da tua mocidade, e anda pelos caminhos do teu coração, e pela vista dos teus olhos: sabe, porém, que por todas estas cousas te trará Deus a juízo.

[[v21-11-10]]

^<<v21-11-10,10>>^ Afasta pois a ira do teu coração, e remove da tua carne o mal, porque a adolescência e a juventude são  vaidade.

'''

xref:021-eclesiastes/021-eclesiastes-010.adoc#v21-10-0[&#60; Capítulo Anterior] | <<v21-11-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-012.adoc#v21-12-0[Próximo Capítulo &#62;]