include::./index.adoc[]

[[v21-1-0]]
=== Eclesiastes, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v21-1-1]]

^<<v21-1-1,1>>^ PALAVRAS do pregador, filho de Davi, rei em Jerusalém:

[[v21-1-2]]

^<<v21-1-2,2>>^ Vaidade de vaidades! diz o pregador, vaidade de vaidades! é  tudo vaidade.

[[v21-1-3]]

^<<v21-1-3,3>>^ Que vantagem tem o homem, de todo o seu trabalho, que ele faz debaixo do sol?

[[v21-1-4]]

^<<v21-1-4,4>>^ Uma  geração vai, e outra  geração vem; mas a terra para sempre permanece.

[[v21-1-5]]

^<<v21-1-5,5>>^ E nasce o sol, e põe-se o sol, e volta ao seu lugar donde nasceu.

[[v21-1-6]]

^<<v21-1-6,6>>^ O vento vai para o sul, e faz o seu  giro para o norte; continuamente vai girando o vento, e volta fazendo os seus circuitos.

[[v21-1-7]]

^<<v21-1-7,7>>^ Todos os ribeiros vão para o mar, e contudo  o mar não se enche; para o lugar para onde os ribeiros vão, para aí tornam eles a ir.

[[v21-1-8]]

^<<v21-1-8,8>>^ Todas estas cousas se cansam tanto , que ninguém o pode declarar: os olhos não se fartam de ver, nem os ouvidos de ouvir.

[[v21-1-9]]

^<<v21-1-9,9>>^ O que foi, isso é o que  há de ser; e o que se fez, isso se tornará a fazer: de modo que nada há novo debaixo do sol.

[[v21-1-10]]

^<<v21-1-10,10>>^ Há alguma cousa de que se possa dizer: Vê, isto é  novo? já foi nos séculos passados, que foram antes de nós.

[[v21-1-11]]

^<<v21-1-11,11>>^ Já  não há  lembrança das cousas que precederam; e das cousas que hão de ser também delas não haverá lembrança, nos que hão de vir depois.

[[v21-1-12]]

^<<v21-1-12,12>>^ Eu, o pregador, fui rei sobre Israel em Jerusalém.

[[v21-1-13]]

^<<v21-1-13,13>>^ E apliquei o meu coração a esquadrinhar, e a informar-me com sabedoria de tudo quanto sucede debaixo do céu: esta enfadonha ocupação deu Deus aos filhos dos homens, para nela os exercitar.

[[v21-1-14]]

^<<v21-1-14,14>>^ Atentei para todas as obras que se fazem debaixo do sol, e eis que tudo era  vaidade e aflição de espírito.

[[v21-1-15]]

^<<v21-1-15,15>>^ Aquilo que é  torto não se pode endireitar; aquilo  que falta não pode ser calculado.

[[v21-1-16]]

^<<v21-1-16,16>>^ Falei eu com o meu coração, dizendo: Eis que eu me engrandeci, e sobrepujei em sabedoria a todos os que houve antes de mim em Jerusalém: na verdade, o meu coração contemplou abundantemente a sabedoria e a ciência.

[[v21-1-17]]

^<<v21-1-17,17>>^ E apliquei o meu coração a conhecer a sabedoria e a conhecer os desvarios e as loucuras, e vim a saber que também isto era aflição de espírito.

[[v21-1-18]]

^<<v21-1-18,18>>^ Porque na muita sabedoria há  muito enfado; e o que aumenta em  ciência, aumenta em trabalho.

'''

xref:020-proverbios/020-proverbios-031.adoc#v20-31-0[&#60; Capítulo Anterior] | <<v21-1-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[Próximo Capítulo &#62;]