include::./index.adoc[]

[[v21-6-0]]
=== Eclesiastes, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v21-6-1]]

^<<v21-6-1,1>>^ HÁ um mal que tenho visto debaixo do sol, e que mui frequente é  entre os homens:

[[v21-6-2]]

^<<v21-6-2,2>>^ Um  homem a quem Deus deu riquezas, fazenda e honra, e nada lhe falta de tudo quanto a sua alma deseja, mas Deus não lhe dá poder para daí comer, antes o estranho lho come: também  isto é  vaidade e má enfermidade.

[[v21-6-3]]

^<<v21-6-3,3>>^ Se o homem gerar cem filhos , e viver muitos anos, e os dias dos seus anos forem muitos e se a sua alma se não fartar do bem, e além disso não tiver um enterro, digo que um aborto é  melhor do que ele;

[[v21-6-4]]

^<<v21-6-4,4>>^ Porquanto debalde veio, e em trevas se vai, e de trevas se cobre o seu nome;

[[v21-6-5]]

^<<v21-6-5,5>>^ E ainda que  nunca viu o sol, nem o conheceu, mais descanso tem do que o tal.

[[v21-6-6]]

^<<v21-6-6,6>>^ E certamente, ainda que vivesse duas vezes mil anos, mas não gozasse o bem, não vão todos para um mesmo lugar?

[[v21-6-7]]

^<<v21-6-7,7>>^ Todo o trabalho do homem é para a sua boca, e contudo nunca se satisfaz a sua cobiça.

[[v21-6-8]]

^<<v21-6-8,8>>^ Porque, que mais tem o sábio do que o tolo? e que mais  tem o pobre que sabe andar perante os vivos?

[[v21-6-9]]

^<<v21-6-9,9>>^ Melhor é a vista dos olhos do que o vaguear da cobiça: também isto é  vaidade, e aflição de espírito.

[[v21-6-10]]

^<<v21-6-10,10>>^ Seja qualquer o que for, já o seu nome foi nomeado, e sabe-se que é  homem, e que não pode contender com o que é mais forte do que ele.

[[v21-6-11]]

^<<v21-6-11,11>>^ Sendo certo que há muitas cousas que aumentam a vaidade, que mais tem o homem de melhor?

[[v21-6-12]]

^<<v21-6-12,12>>^ Porque quem sabe o que é  bom nesta vida para o homem, por todos os dias da sua vaidade, os quais gasta como sombra? porque quem declarará ao homem o que será depois dele debaixo do sol?

'''

xref:021-eclesiastes/021-eclesiastes-005.adoc#v21-5-0[&#60; Capítulo Anterior] | <<v21-6-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-007.adoc#v21-7-0[Próximo Capítulo &#62;]