include::./index.adoc[]

[[v21-5-0]]
=== Eclesiastes, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v21-5-1]]

^<<v21-5-1,1>>^ GUARDA o teu pé, quando entrares na casa de Deus; e inclina-te mais a ouvir do que a oferecer sacrifícios de tolos, pois não sabem que fazem mal.

[[v21-5-2]]

^<<v21-5-2,2>>^ Não te precipites com a tua boca, nem o teu coração se apresse a pronunciar palavra alguma diante de Deus; porque Deus está  nos céus, e tu estás  sobre a terra; pelo que sejam poucas as tuas palavras.

[[v21-5-3]]

^<<v21-5-3,3>>^ Porque, da muita ocupação vêm os sonhos, e a voz do tolo da multidão das palavras.

[[v21-5-4]]

^<<v21-5-4,4>>^ Quando a Deus fizeres algum voto, não tardes em cumpri-lo; porque não se agrada de tolos: o que votares, paga-o.

[[v21-5-5]]

^<<v21-5-5,5>>^ Melhor é que não votes do que votes e não pagues.

[[v21-5-6]]

^<<v21-5-6,6>>^ Não consintas que a tua boca faça pecar a tua carne, nem digas diante do anjo que foi  erro: por que razão se iraria Deus contra a tua voz, de sorte que destruísse a obra das tuas mãos?

[[v21-5-7]]

^<<v21-5-7,7>>^ Porque, como na multidão dos sonhos há  vaidades, assim também nas muitas palavras: mas tu teme a Deus.

[[v21-5-8]]

^<<v21-5-8,8>>^ Se vires em alguma  província opressão de pobres, e a violência em lugar do juízo e da justiça, não te maravilhes de semelhante caso; porque o que mais alto é  do que os altos para isso atenta; e há  mais altos do que eles.

[[v21-5-9]]

^<<v21-5-9,9>>^ O proveito da terra é para todos; até o rei se serve do campo.

[[v21-5-10]]

^<<v21-5-10,10>>^ O que amar o dinheiro nunca se fartará de dinheiro; e quem amar a abundância nunca se fartará  da renda: também isto é vaidade.

[[v21-5-11]]

^<<v21-5-11,11>>^ Onde a fazenda se multiplica, aí se multiplicam também os que a comem: que mais proveito pois têm  os seus donos do que verem-na com os seus olhos?

[[v21-5-12]]

^<<v21-5-12,12>>^ Doce é  o sono do trabalhador, quer coma pouco quer muito; mas a fartura do rico não o deixa dormir.

[[v21-5-13]]

^<<v21-5-13,13>>^ Há mal que  vi debaixo do sol, e atrai enfermidades: as riquezas que os seus donos guardam para o seu próprio dano;

[[v21-5-14]]

^<<v21-5-14,14>>^ Porque as mesmas riquezas se perdem por qualquer má aventura; e havendo algum filho nada fica  na sua mão.

[[v21-5-15]]

^<<v21-5-15,15>>^ Como saiu do ventre de sua mãe, assim  nu voltará, indo-se como veio; e nada tomará do seu trabalho, que possa levar na sua mão.

[[v21-5-16]]

^<<v21-5-16,16>>^ Também isto é  um mal que causa enfermidades: que, infalivelmente, como veio, assim ele vai; e que proveito lhe vem  de trabalhar para o vento.

[[v21-5-17]]

^<<v21-5-17,17>>^ E de haver comido todos os seus dias nas trevas, e de haver padecido muito enfado, e enfermidades, e cruel furor?

[[v21-5-18]]

^<<v21-5-18,18>>^ Eis aqui o que eu vi, uma boa e bela cousa: comer e beber, e gozar cada um do bem de todo o seu trabalho, em que trabalhou debaixo do sol, todos os dias da sua vida que Deus lhe deu; porque esta é  a sua porção.

[[v21-5-19]]

^<<v21-5-19,19>>^ E quanto ao homem, a quem Deus deu riquezas e fazenda, e lhe deu poder para delas comer, e tomar a sua porção, e gozar do seu trabalho: isto é dom de Deus.

[[v21-5-20]]

^<<v21-5-20,20>>^ Porque não se lembrará muito dos dias da sua vida; porquanto Deus lhe responde na alegria do seu coração.

'''

xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[&#60; Capítulo Anterior] | <<v21-5-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[Próximo Capítulo &#62;]