include::./index.adoc[]

[[v6-1-0]]
=== Josué, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v6-1-1]]

^<<v6-1-1,1>>^ E SUCEDEU depois da morte de Moisés, servo do Senhor, que o Senhor falou a Josué, filho de Num, servo de Moisés, dizendo:

[[v6-1-2]]

^<<v6-1-2,2>>^ Moisés, meu servo, é morto: levanta-te pois agora, passa este Jordão, tu e todo este povo, à terra que eu dou aos filhos de Israel.

[[v6-1-3]]

^<<v6-1-3,3>>^ Todo o lugar que pisar a planta do vosso pé vo-lo tenho dado, como eu disse a Moisés.

[[v6-1-4]]

^<<v6-1-4,4>>^ Desde o deserto e desde este  Líbano, até ao grande rio, o rio Eufrates, toda a terra dos heteus, e até o grande mar para o poente do sol, será o vosso termo.

[[v6-1-5]]

^<<v6-1-5,5>>^ Nenhum se susterá diante de ti, todos os dias da tua vida: como fui com Moisés, assim  serei contigo: não te deixarei nem te desampararei.

[[v6-1-6]]

^<<v6-1-6,6>>^ Esforça-te, e tem bom ânimo: porque tu farás a este povo herdar a terra que jurei a seus pais lhes daria.

[[v6-1-7]]

^<<v6-1-7,7>>^ Tão somente esforça-te e tem mui bom ânimo, para teres o cuidado de fazer conforme a toda a lei que meu servo Moisés te ordenou; dela não te desvies, nem para a direita nem para a esquerda, para que prudentemente te conduzas por onde quer que andares.

[[v6-1-8]]

^<<v6-1-8,8>>^ Não se aparte da tua boca o livro desta lei; antes medita nele dia e noite, para que tenhas cuidado de fazer conforme a tudo quanto nele está escrito; porque então farás prosperar o teu caminho, e então prudentemente te conduzirás.

[[v6-1-9]]

^<<v6-1-9,9>>^ Não to mandei eu? Esforça-te, e tem bom ânimo; não pasmes, nem te espantes: porque o Senhor teu Deus é  contigo, por onde quer que andares.

[[v6-1-10]]

^<<v6-1-10,10>>^ Então deu ordem Josué aos príncipes do povo, dizendo:

[[v6-1-11]]

^<<v6-1-11,11>>^ Passai pelo meio do arraial, e ordenai ao povo, dizendo: Provede-vos de comida, porque dentro de três dias passareis este Jordão, para que entreis a possuir a terra que vos dá o Senhor vosso Deus, para que a possuais.

[[v6-1-12]]

^<<v6-1-12,12>>^ E falou Josué aos rubenitas, e aos gaditas, e à meia tribo de Manassés, dizendo:

[[v6-1-13]]

^<<v6-1-13,13>>^ Lembrai-vos da palavra que vos mandou Moisés, o servo do Senhor, dizendo: O Senhor vosso Deus vos dá descanso, e vos dá esta terra.

[[v6-1-14]]

^<<v6-1-14,14>>^ Vossas mulheres, vossos meninos e vosso gado fiquem na terra que Moisés vos deu desta banda do Jordão; porém vós passareis armados na frente de vossos irmãos, todos os valentes e valorosos, e ajudá-los-eis;

[[v6-1-15]]

^<<v6-1-15,15>>^ Até que o Senhor dê descanso a vossos irmãos, como a vós, e eles também possuam a terra que o Senhor vosso Deus lhes dá; então tornareis à terra da vossa herança, e possuireis a que vos deu Moisés, o servo do Senhor, desta banda do Jordão, para o nascente do sol.

[[v6-1-16]]

^<<v6-1-16,16>>^ Então responderam a Josué, dizendo: Tudo quanto nos ordenaste faremos, e aonde quer que nos enviares iremos.

[[v6-1-17]]

^<<v6-1-17,17>>^ Como em tudo ouvimos a Moisés, assim te ouviremos a ti: tão somente que  o Senhor teu Deus seja contigo, como foi com Moisés.

[[v6-1-18]]

^<<v6-1-18,18>>^ Todo o homem, que for rebelde à tua boca, e não ouvir as tuas palavras em tudo quanto lhe mandares, morrerá: tão somente esforça-te, e tem bom ânimo.

'''

xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[&#60; Capítulo Anterior] | <<v6-1-0,Topo>> | xref:006-josue/006-josue-002.adoc#v6-2-0[Próximo Capítulo &#62;]