include::./index.adoc[]

[[v6-22-0]]
=== Josué, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v6-22-1]]

^<<v6-22-1,1>>^ ENTÃO Josué chamou os rubenitas, e os gaditas, e a meia tribo de Manassés,

[[v6-22-2]]

^<<v6-22-2,2>>^ E disse-lhes: Tudo quanto Moisés, o servo do Senhor, vos ordenou, guardastes: e à minha voz obedecestes em tudo quanto vos ordenei.

[[v6-22-3]]

^<<v6-22-3,3>>^ A vossos irmãos por tanto tempo até ao dia de  hoje não desamparastes: antes tivestes cuidado da guarda do mandamento do Senhor vosso Deus.

[[v6-22-4]]

^<<v6-22-4,4>>^ E agora o Senhor vosso Deus deu repouso a vossos irmãos, como lhes tinha prometido: voltai-vos pois agora, e ide-vos a vossas tendas, à terra da vossa possessão, que Moisés, o servo do Senhor, vos deu dalém do Jordão.

[[v6-22-5]]

^<<v6-22-5,5>>^ Tão somente tende cuidado de guardar com diligência o mandamento e a lei que Moisés, o servo do Senhor, vos mandou: que ameis ao Senhor vosso Deus, e andeis em todos os seus caminhos, e guardeis os seus mandamentos, e vos achegueis a ele, e o sirvais com todo o vosso coração, e com toda a vossa alma.

[[v6-22-6]]

^<<v6-22-6,6>>^ Assim Josué os abençoou; e despediu-os, e foram para as suas tendas.

[[v6-22-7]]

^<<v6-22-7,7>>^ Porquanto Moisés dera herança  em Basã à meia tribo de Manassés; porém à outra metade deu Josué entre seus irmãos, daquém do Jordão para o ocidente; e enviando-os Josué também a suas tendas, os abençoou;

[[v6-22-8]]

^<<v6-22-8,8>>^ E falou-lhes, dizendo: Voltai-vos às vossas tendas com grandes riquezas, e com muitíssimo gado, com prata, e com ouro, e com metal, e com ferro, e com muitíssimos vestidos: e com vossos irmãos reparti o despojo dos vossos inimigos.

[[v6-22-9]]

^<<v6-22-9,9>>^ Assim os filhos de Rúben, e os filhos de Gade, e a meia tribo de Manassés, voltaram e partiram dos filhos de Israel, de Silo, que está  na terra de Canaã; para irem à terra de Gileade, à terra da sua possessão, de que foram feitos possuidores, conforme ao dito do Senhor pelo ministério de Moisés.

[[v6-22-10]]

^<<v6-22-10,10>>^ E, vindo eles aos limites do Jordão, que estão  na terra de Canaã, ali os filhos de Rúben, e os filhos de Gade, e a meia tribo de Manassés edificaram um  altar junto ao Jordão, um  altar de grande aparência.

[[v6-22-11]]

^<<v6-22-11,11>>^ E ouviram os filhos de Israel dizer: Eis que os filhos de Rúben, e os filhos de Gade, e a meia tribo de Manassés edificaram um  altar na frente da terra de Canaã, nos limites do Jordão, da banda dos filhos de Israel.

[[v6-22-12]]

^<<v6-22-12,12>>^ Ouvindo isto os filhos de Israel, ajuntou-se toda a congregação dos filhos de Israel em Silo, para saírem contra eles em exército.

[[v6-22-13]]

^<<v6-22-13,13>>^ E enviaram os filhos de Israel aos filhos de Rúben, e aos filhos de Gade, e à meia tribo de Manassés, para a terra de Gileade, Fineias, filho de Eleazar, o sacerdote;

[[v6-22-14]]

^<<v6-22-14,14>>^ E dez príncipes com ele, de cada casa paterna um príncipe, de todas as tribos de Israel: e cada um era  cabeça da casa de seus pais nos milhares de Israel.

[[v6-22-15]]

^<<v6-22-15,15>>^ E, vindo eles, aos filhos de Rúben, e aos filhos de Gade, e à meia tribo de Manassés, à terra de Gileade, falaram com eles, dizendo:

[[v6-22-16]]

^<<v6-22-16,16>>^ Assim diz toda a congregação do Senhor: Que transgressão é  esta, com que transgredistes contra o Deus de Israel, deixando hoje de seguir ao Senhor, edificando-vos um altar, para vos rebelardes contra o Senhor?

[[v6-22-17]]

^<<v6-22-17,17>>^ Foi- nos pouco a iniquidade de Peor, de que ainda até ao dia de  hoje não estamos purificados, ainda que houve castigo na congregação do Senhor?

[[v6-22-18]]

^<<v6-22-18,18>>^ E pois que hoje abandonais ao Senhor, será que , rebelando-vos hoje contra o Senhor, amanhã se irará contra toda a congregação de Israel.

[[v6-22-19]]

^<<v6-22-19,19>>^ Se é, porém, que a terra da vossa possessão é imunda, passai-vos para a terra da possessão do Senhor, onde habita o tabernáculo do Senhor, e tomai possessão entre nós: mas não vos rebeleis contra o Senhor, nem tão pouco  vos rebeleis contra nós, edificando-vos um  altar, afora do altar do Senhor nosso Deus.

[[v6-22-20]]

^<<v6-22-20,20>>^ Não cometeu Acã, filho de Zerá, transgressão no tocante ao anátema? e não veio ira sobre toda a congregação de Israel? assim que aquele homem não morreu só na sua iniquidade.

[[v6-22-21]]

^<<v6-22-21,21>>^ Então responderam os filhos de Rúben, e os filhos de Gade, e a meia tribo de Manassés, e disseram aos cabeças dos milhares de Israel:

[[v6-22-22]]

^<<v6-22-22,22>>^ O Deus dos deuses, o Senhor ele o  sabe, e Israel mesmo o  saberá; se foi em rebeldia, ou por transgressão contra o Senhor, hoje não nos preserveis;

[[v6-22-23]]

^<<v6-22-23,23>>^ Se nós edificamos altar para nos tornar de após o Senhor, ou para sobre ele oferecer holocausto e oferta de manjares, ou sobre ele fazer oferta pacífica, o Senhor mesmo de nós o  requeira.

[[v6-22-24]]

^<<v6-22-24,24>>^ E se antes o não fizemos em receio disto, dizendo: Amanhã vossos filhos virão a falar a nossos filhos, dizendo: Que tendes vós com o Senhor Deus de Israel?

[[v6-22-25]]

^<<v6-22-25,25>>^ Pois o Senhor pôs o Jordão por termo entre nós e vós, ó filhos de Rúben, e filhos de Gade; não tendes parte no Senhor: e assim  bem poderiam vossos filhos fazer desistir a nossos filhos de temer ao Senhor.

[[v6-22-26]]

^<<v6-22-26,26>>^ Pelo que dissemos: Façamos agora, e nos edifiquemos um  altar: não para holocausto, nem para sacrifício,

[[v6-22-27]]

^<<v6-22-27,27>>^ Mas para que entre nós e vós, e entre as nossas gerações depois de nós, nos seja  em testemunho, para podermos fazer o serviço do Senhor diante dele com os nossos holocaustos, e com os nossos sacrifícios, e com as nossas ofertas pacíficas: e para que  vossos filhos não digam amanhã a nossos filhos: Não tendes parte no Senhor.

[[v6-22-28]]

^<<v6-22-28,28>>^ Pelo que dissemos: Quando for que amanhã assim  nos digam a nós e às nossas gerações, então diremos: Vede o modelo do altar do Senhor que fizeram nossos pais, não para holocausto nem para sacrifício, porém para ser  testemunho entre nós e vós.

[[v6-22-29]]

^<<v6-22-29,29>>^ Nunca tal nos aconteça, que nos rebelássemos contra o Senhor, ou que hoje nós abandonássemos ao Senhor, edificando altar para holocausto, oferta de manjares ou sacrifício, fora do altar do Senhor nosso Deus, que está  perante o seu tabernáculo.

[[v6-22-30]]

^<<v6-22-30,30>>^ Ouvindo pois Fineias, o sacerdote, e os príncipes da congregação, e os cabeças dos milhares de Israel, que com ele estavam , as palavras que disseram os filhos de Rúben, e os filhos de Gade, e os filhos de Manassés, pareceu bem aos seus olhos.

[[v6-22-31]]

^<<v6-22-31,31>>^ E disse Fineias, filho de Eleazar, o sacerdote, aos filhos de Rúben, aos filhos de Gade, e aos filhos de Manassés: Hoje sabemos que o Senhor está  no meio de nós; porquanto não cometestes transgressão contra o Senhor: agora livrastes os filhos de Israel da mão do Senhor.

[[v6-22-32]]

^<<v6-22-32,32>>^ E tornou-se Fineias, filho de Eleazar, o sacerdote, com os príncipes, de com os filhos de Rúben, e de com os filhos de Gade, da terra de Gileade à terra de Canaã, aos filhos de Israel: e trouxeram-lhes a resposta.

[[v6-22-33]]

^<<v6-22-33,33>>^ E pareceu a resposta boa aos olhos dos filhos de Israel, e os filhos de Israel louvaram a Deus: e não falaram mais  de subir contra eles em exército, para destruírem a terra em que habitavam os filhos de Rúben e os filhos de Gade.

[[v6-22-34]]

^<<v6-22-34,34>>^ E os filhos de Rúben e os filhos de Gade puseram ao altar o nome Ede: para que seja  testemunho entre nós que o Senhor é  Deus.

'''

xref:006-josue/006-josue-021.adoc#v6-21-0[&#60; Capítulo Anterior] | <<v6-22-0,Topo>> | xref:006-josue/006-josue-023.adoc#v6-23-0[Próximo Capítulo &#62;]