include::./index.adoc[]

[[v6-15-0]]
=== Josué, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v6-15-1]]

^<<v6-15-1,1>>^ E FOI a sorte da tribo dos filhos de Judá, segundo as suas famílias, até ao termo de Edom, o deserto de Zim para o sul, até a extremidade da banda do sul.

[[v6-15-2]]

^<<v6-15-2,2>>^ E foi o seu termo para o sul, desde a ribeira do mar salgado, desde a baía que olha para o sul;

[[v6-15-3]]

^<<v6-15-3,3>>^ E sai para o sul, até à subida de Acrabim, e passa a Zim, e sobe do sul a Cades-Barneia, e passa por Hezrom, e sobe a Adar, e rodeia a Carca:

[[v6-15-4]]

^<<v6-15-4,4>>^ E passa Asmom, e sai ao ribeiro do Egito, e as saídas deste termo irão até ao mar: este será o vosso termo da banda do sul.

[[v6-15-5]]

^<<v6-15-5,5>>^ O termo porém para o oriente será  o mar salgado até à extremidade do Jordão: e o termo para o norte será  da baía do mar, desde a extremidade do Jordão.

[[v6-15-6]]

^<<v6-15-6,6>>^ E este termo subirá até Bete-Hoglá, e passará do norte a Bete-Arabá, e este termo subirá até à pedra de Boã, filho de Rúben.

[[v6-15-7]]

^<<v6-15-7,7>>^ Subirá mais este termo a Debir desde o vale de Acor, e olhará pelo norte para Gilgal, a qual está  à subida de Adumim, que está  para o sul do ribeiro: então este termo passará até às águas de Ensemes: e as suas saídas estarão  da banda de Enrogel.

[[v6-15-8]]

^<<v6-15-8,8>>^ E este termo passará pelo vale do filho de Hinom, da banda dos jebuseus do sul: esta é  Jerusalém: e subirá este termo até ao cume do monte que está  diante do vale de Hinom para o ocidente, que está  no fim do vale dos refains da banda do norte.

[[v6-15-9]]

^<<v6-15-9,9>>^ Então este termo irá desde a altura do monte até à fonte das águas de Neftoa; e sairá até às cidades do monte de Efrom; irá mais este termo até Baala; esta é  Quiriate-Jearim:

[[v6-15-10]]

^<<v6-15-10,10>>^ Então tornará este termo desde Baala para o ocidente, até às montanhas de Seir, e passará ao lado do monte de Jearim da banda do norte: esta é  Quesalom, e descerá a Bete-Semes, e passará por Timná.

[[v6-15-11]]

^<<v6-15-11,11>>^ Sairá este termo mais ao lado de Ecrom para o norte, e este termo irá a Sicrom, e passará o monte de Baala, e sairá em Jabneel: e as saídas deste termo eram no mar.

[[v6-15-12]]

^<<v6-15-12,12>>^ Será  porém o termo da banda do ocidente o mar grande, e o seu  termo: este é  o termo dos filhos de Judá ao redor, segundo as suas famílias.

[[v6-15-13]]

^<<v6-15-13,13>>^ Mas a Calebe, filho de Jefoné, deu uma  parte no meio dos filhos de Judá, conforme ao dito do Senhor a Josué: a saber , a cidade de Arba, pai de Enaque; este é  Hebrom.

[[v6-15-14]]

^<<v6-15-14,14>>^ E expeliu Calebe dali os três filhos de Enaque: Sesai, e Aimã, e Talmai, gerados de Enaque.

[[v6-15-15]]

^<<v6-15-15,15>>^ E dali subiu aos habitantes de Debir: e fora  dantes o nome de Debir Quiriate-Séfer.

[[v6-15-16]]

^<<v6-15-16,16>>^ E disse Calebe: Quem ferir a Quiriate-Séfer, e a tomar, lhe darei a minha filha Acsa por mulher.

[[v6-15-17]]

^<<v6-15-17,17>>^ Tomou-a pois Otniel, filho de Quenaz, irmão de Calebe: e deu-lhe a sua filha Acsa por mulher.

[[v6-15-18]]

^<<v6-15-18,18>>^ E sucedeu que , vindo ela a ele , o persuadiu que pedisse um campo a seu pai; e ela se apeou do jumento: então Calebe lhe disse: Que é o que  tens?

[[v6-15-19]]

^<<v6-15-19,19>>^ E ela disse: Dá-me uma  bênção: pois me deste terra seca, dá-me também fontes de águas. Então lhe deu as fontes superiores e as fontes inferiores.

[[v6-15-20]]

^<<v6-15-20,20>>^ Esta é  a herança da tribo dos filhos de Judá, segundo as suas famílias.

[[v6-15-21]]

^<<v6-15-21,21>>^ São pois as cidades da extremidade da tribo dos filhos de Judá até ao termo de Edom para o sul: Cabzeel, e Eder, e Jagur.

[[v6-15-22]]

^<<v6-15-22,22>>^ E Quiná, e Dimona, e Adada,

[[v6-15-23]]

^<<v6-15-23,23>>^ E Quedes, e Hazor, e Itnã,

[[v6-15-24]]

^<<v6-15-24,24>>^ Zife, e Telém, e Bealote,

[[v6-15-25]]

^<<v6-15-25,25>>^ E Hazor, Hadata, e Quiriote-Hesrom (que é  Hazor),

[[v6-15-26]]

^<<v6-15-26,26>>^ Amã, e Sema, e Molada,

[[v6-15-27]]

^<<v6-15-27,27>>^ E Hazargada, e Hesmone, e Bete-Palete,

[[v6-15-28]]

^<<v6-15-28,28>>^ E Hasarsual, e Beerseba, e Bizioteia,

[[v6-15-29]]

^<<v6-15-29,29>>^ Baala, e Jim, e Ezém,

[[v6-15-30]]

^<<v6-15-30,30>>^ E Eltolade, e Quesil, e Hormá,

[[v6-15-31]]

^<<v6-15-31,31>>^ E Siclague, e Madmana, e Sansana,

[[v6-15-32]]

^<<v6-15-32,32>>^ E Lebaote, e Silhim, e Aim, e Rimom: todas as cidades e as suas aldeias, vinte e nove.

[[v6-15-33]]

^<<v6-15-33,33>>^ Nas planícies: Estaol, e Zorá, e Asná,

[[v6-15-34]]

^<<v6-15-34,34>>^ E Zanoa, e Enganim, Tápua, e Enã,

[[v6-15-35]]

^<<v6-15-35,35>>^ Iarmute, e Adulão, Socó, e Azeca,

[[v6-15-36]]

^<<v6-15-36,36>>^ E Saaraim, e Aditaim, e Gedera, e Gederotaim, catorze cidades e as suas aldeias.

[[v6-15-37]]

^<<v6-15-37,37>>^ Zenã, e Hadasa, e Migdal-Gade,

[[v6-15-38]]

^<<v6-15-38,38>>^ E Dilã, e Mizpá, e Jocteel.

[[v6-15-39]]

^<<v6-15-39,39>>^ Laquis, e Boscate, e Eglom,

[[v6-15-40]]

^<<v6-15-40,40>>^ E Cabom, e Laamás, e Quitlis,

[[v6-15-41]]

^<<v6-15-41,41>>^ E Gederote, Bete-Dagom, e Naamá, e Maquedá: dezesseis cidades e as suas aldeias.

[[v6-15-42]]

^<<v6-15-42,42>>^ Libna, e Eter, e Asã,

[[v6-15-43]]

^<<v6-15-43,43>>^ E Iftá, e Asná, e Nezibe,

[[v6-15-44]]

^<<v6-15-44,44>>^ E Queila, e Aczibe, e Maresa: nove cidades e as suas aldeias.

[[v6-15-45]]

^<<v6-15-45,45>>^ Ecrom, e os lugares da sua jurisdição, e as suas aldeias:

[[v6-15-46]]

^<<v6-15-46,46>>^ Desde Ecrom, e até ao mar, todas as que estão  da banda de Asdode, e as suas aldeias.

[[v6-15-47]]

^<<v6-15-47,47>>^ Asdode, os lugares da sua jurisdição e as suas aldeias; Gaza, os lugares da sua jurisdição, e as suas aldeias, até ao rio do Egito: e o mar grande e o seu  termo.

[[v6-15-48]]

^<<v6-15-48,48>>^ E nas montanhas, Samir, Iatir, e Socó,

[[v6-15-49]]

^<<v6-15-49,49>>^ E Daná, e Quiriate-Saná, que é  Debir,

[[v6-15-50]]

^<<v6-15-50,50>>^ E Anabe, Estemó, e Anim,

[[v6-15-51]]

^<<v6-15-51,51>>^ E Gósen, e Holom, e Gilo: onze cidades e as suas aldeias.

[[v6-15-52]]

^<<v6-15-52,52>>^ Arabe, e Dumá, e Esã,

[[v6-15-53]]

^<<v6-15-53,53>>^ E Ianum, e Bete-Tápua, e Afeca,

[[v6-15-54]]

^<<v6-15-54,54>>^ E Hunta, e Quiriate-Arba (que é  Hebrom), e Zior: nove cidades e as suas aldeias.

[[v6-15-55]]

^<<v6-15-55,55>>^ Maom, Carmelo, e Zife, e Jutá,

[[v6-15-56]]

^<<v6-15-56,56>>^ E Jezreel, e Jocdeão, e Zanoa,

[[v6-15-57]]

^<<v6-15-57,57>>^ Caim, Gibeá, e Timná: dez cidades e as suas aldeias.

[[v6-15-58]]

^<<v6-15-58,58>>^ Halul, Bete-Zur, e Gedor,

[[v6-15-59]]

^<<v6-15-59,59>>^ E Maarate, e Bete-Anote, e Eltecom: seis cidades e as suas aldeias.

[[v6-15-60]]

^<<v6-15-60,60>>^ Quiriate-Baal (que é  Quiriate-Jearim), e Rabá: duas cidades e as suas aldeias.

[[v6-15-61]]

^<<v6-15-61,61>>^ No deserto: Bete-Arabá, Midim, e Secaca.

[[v6-15-62]]

^<<v6-15-62,62>>^ E Nibsã, e a cidade do sal, e Engedi: seis cidades e as suas aldeias.

[[v6-15-63]]

^<<v6-15-63,63>>^ Não puderam porém os filhos de Judá expelir os jebuseus que habitavam em Jerusalém: assim habitaram os jebuseus com os filhos de Judá em Jerusalém, até ao dia de  hoje.

'''

xref:006-josue/006-josue-014.adoc#v6-14-0[&#60; Capítulo Anterior] | <<v6-15-0,Topo>> | xref:006-josue/006-josue-016.adoc#v6-16-0[Próximo Capítulo &#62;]