include::./index.adoc[]

[[v6-7-0]]
=== Josué, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v6-7-1]]

^<<v6-7-1,1>>^ E PREVARICARAM os filhos de Israel no anátema: porque Acã, filho de Carmi, filho de Zabdi, filho de Zerá, da tribo de Judá, tomou do anátema, e a ira do Senhor se acendeu contra os filhos de Israel.

[[v6-7-2]]

^<<v6-7-2,2>>^ Enviando pois Josué, de Jericó, alguns  homens a Ai, que está  junto a Betáven, da banda do oriente de Betel, falou-lhes, dizendo: Subi, e espiai a terra. Subiram pois aqueles homens, e espiaram a Ai.

[[v6-7-3]]

^<<v6-7-3,3>>^ E voltaram a Josué, e disseram-lhe: Não suba todo o povo; subam alguns dois mil, ou três mil homens, a ferir a Ai: não fatigues ali a todo o povo, porque poucos são.

[[v6-7-4]]

^<<v6-7-4,4>>^ Assim, subiram lá do povo alguns três mil homens, os quais fugiram diante dos homens de Ai.

[[v6-7-5]]

^<<v6-7-5,5>>^ E os homens de Ai feriram deles alguns trinta e seis, e seguiram-nos desde a porta até Sebarim, e feriram-nos na descida; e o coração do povo se derreteu e se tornou como água.

[[v6-7-6]]

^<<v6-7-6,6>>^ Então Josué rasgou os seus vestidos, e se prostrou em terra sobre o seu rosto perante a arca do Senhor até à tarde, ele e os anciãos de Israel: e deitaram pó sobre as suas cabeças.

[[v6-7-7]]

^<<v6-7-7,7>>^ E disse Josué: Ah! Senhor Jeová! porque, com efeito, fizeste passar a este povo o Jordão, para nos dares nas mãos dos amorreus, para nos fazerem perecer? Oxalá nos contentáramos com ficarmos dalém do Jordão.

[[v6-7-8]]

^<<v6-7-8,8>>^ Ah! Senhor! que direi? pois Israel virou as costas diante dos seus inimigos!

[[v6-7-9]]

^<<v6-7-9,9>>^ Ouvindo isto , os cananeus, e todos os moradores da terra, nos cercarão e desarraigarão o nosso nome da terra: e então  que farás ao teu grande nome?

[[v6-7-10]]

^<<v6-7-10,10>>^ Então disse o Senhor a Josué: Levanta-te: por que estás prostrado assim sobre o teu rosto?

[[v6-7-11]]

^<<v6-7-11,11>>^ Israel pecou, e até transgrediram o meu concerto que lhes tinha ordenado, e até tomaram do anátema, e também furtaram, e também mentiram, e até debaixo da sua bagagem o puseram.

[[v6-7-12]]

^<<v6-7-12,12>>^ Pelo que os filhos de Israel não puderam subsistir perante os seus inimigos: viraram as costas diante dos seus inimigos; porquanto estão amaldiçoados: não serei mais convosco, se não desarraigardes o anátema do meio de vós.

[[v6-7-13]]

^<<v6-7-13,13>>^ Levanta-te, santifica o povo, e dize: Santificai-vos para amanhã, porque assim diz o Senhor, o Deus de Israel: Anátema há  no meio de ti, Israel: diante dos teus inimigos não poderás suster-te, até que tires o anátema do meio de vós.

[[v6-7-14]]

^<<v6-7-14,14>>^ Amanhã pois vos chegareis, segundo as vossas tribos: e será que  a tribo que o Senhor tomar se chegará, segundo as famílias; e a família que o Senhor tomar se chegará por casas; e a casa que o Senhor tomar se chegará homem por homem.

[[v6-7-15]]

^<<v6-7-15,15>>^ E será que  aquele que for tomado com o anátema será queimado a fogo, ele e tudo quanto tiver: porquanto transgrediu o concerto do Senhor, e fez uma  loucura em Israel.

[[v6-7-16]]

^<<v6-7-16,16>>^ Então Josué se levantou de madrugada, e fez chegar a Israel, segundo as suas tribos: e a tribo de Judá foi tomada:

[[v6-7-17]]

^<<v6-7-17,17>>^ E, fazendo chegar a tribo de Judá, tomou a família de Zarqui: e, fazendo chegar a família de Zarqui, homem por homem, foi tomado Zabdi:

[[v6-7-18]]

^<<v6-7-18,18>>^ E, fazendo chegar a sua casa, homem por homem, foi tomado Acã, filho de Carmi, filho de Zabdi, filho de Zerá, da tribo de Judá.

[[v6-7-19]]

^<<v6-7-19,19>>^ Então disse Josué a Acã: Filho meu, dá, peço-te, glória ao Senhor Deus de Israel, e faze confissão perante ele; e declara-me agora o que fizeste, não mo ocultes.

[[v6-7-20]]

^<<v6-7-20,20>>^ E respondeu Acã a Josué, e disse: Verdadeiramente pequei contra o Senhor Deus de Israel, e fiz assim e assim.

[[v6-7-21]]

^<<v6-7-21,21>>^ Quando vi entre os despojos uma boa capa babilônica, e duzentos siclos de prata e, uma cunha de ouro do peso de cinquenta siclos, cobicei-os e tomei-os: e eis que estão  escondidos na terra, no meio da minha tenda, e a prata debaixo dela.

[[v6-7-22]]

^<<v6-7-22,22>>^ Então Josué enviou mensageiros, que foram correndo à tenda: e eis que tudo  estava escondido na sua tenda, e a prata debaixo dela.

[[v6-7-23]]

^<<v6-7-23,23>>^ Tomaram pois aquelas cousas do meio da tenda, e as trouxeram a Josué e a todos os filhos de Israel: e as deitaram perante o Senhor.

[[v6-7-24]]

^<<v6-7-24,24>>^ Então Josué e todo o Israel com ele tomaram a Acã, filho de Zerá, e a prata, e a capa, e a cunha de ouro, e a seus filhos, e a suas filhas, e a seus bois, e a seus jumentos, e as suas ovelhas, e a sua tenda, e a tudo quanto tinha; e levaram-nos ao vale de Acor.

[[v6-7-25]]

^<<v6-7-25,25>>^ E disse Josué: Por que nos turbaste? o Senhor te turbará a ti este dia. E todo o Israel o apedrejou com pedras, e os queimaram a fogo, e os apedrejaram com pedras.

[[v6-7-26]]

^<<v6-7-26,26>>^ E levantaram sobre ele um grande montão de pedras, até ao dia de  hoje; assim o Senhor se tornou do ardor da sua ira: pelo que se chamou o nome daquele lugar o vale de Acor, até ao dia de  hoje.

'''

xref:006-josue/006-josue-006.adoc#v6-6-0[&#60; Capítulo Anterior] | <<v6-7-0,Topo>> | xref:006-josue/006-josue-008.adoc#v6-8-0[Próximo Capítulo &#62;]