include::./index.adoc[]

[[v6-24-0]]
=== Josué, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v6-24-1]]

^<<v6-24-1,1>>^ DEPOIS ajuntou Josué todas as tribos de Israel em Siquém: e chamou os anciãos de Israel, e os seus cabeças, e os seus juízes, e os seus oficiais: e eles se apresentaram diante de Deus.

[[v6-24-2]]

^<<v6-24-2,2>>^ Então Josué disse a todo o povo: Assim diz o Senhor Deus de Israel: Dalém do rio antigamente habitaram vossos pais, Terá, pai de Abraão e pai de Nacor: e serviram a outros deuses.

[[v6-24-3]]

^<<v6-24-3,3>>^ Eu porém tomei a vosso pai Abraão dalém do rio, e o fiz andar por toda a terra de Canaã: também multipliquei a sua semente, e dei-lhe a Isaque.

[[v6-24-4]]

^<<v6-24-4,4>>^ E a Isaque dei Jacó e Esaú: e a Esaú dei a montanha de Seir, para a possuir: porém Jacó e seus filhos desceram para o Egito.

[[v6-24-5]]

^<<v6-24-5,5>>^ Então enviei Moisés e Aarão, e feri ao Egito, como o fiz no meio dele; e depois vos tirei de lá.

[[v6-24-6]]

^<<v6-24-6,6>>^ E, tirando eu a vossos pais do Egito, viestes ao mar: e os egípcios perseguiram a vossos pais, com carros e com cavaleiros, até ao Mar Vermelho.

[[v6-24-7]]

^<<v6-24-7,7>>^ E clamaram ao Senhor, que pôs uma  escuridão entre vós e os egípcios, e trouxe o mar sobre eles, e os cobriu, e os vossos olhos viram o que eu fiz no Egito: depois habitastes no deserto muitos dias.

[[v6-24-8]]

^<<v6-24-8,8>>^ Então eu vos trouxe à terra dos amorreus, que habitavam dalém do Jordão, os quais pelejaram contra vós: porém os dei na vossa mão, e possuístes a sua terra, e os destruí diante de vós.

[[v6-24-9]]

^<<v6-24-9,9>>^ Levantou-se também Balaque, filho de Zipor, rei dos moabitas, e pelejou contra Israel: e enviou e chamou a Balaão, filho de Beor, para que vos amaldiçoasse.

[[v6-24-10]]

^<<v6-24-10,10>>^ Porém eu não quis ouvir a Balaão: pelo que, abençoando-vos ele, vos abençoou, e livrei-vos da sua mão.

[[v6-24-11]]

^<<v6-24-11,11>>^ E, passando vós o Jordão, e vindo a Jericó, os habitantes de Jericó pelejaram contra vós, os amorreus, e os ferezeus e os cananeus, e os heteus, e os girgaseus, e os heveus, e os jebuseus: porém os dei na vossa mão.

[[v6-24-12]]

^<<v6-24-12,12>>^ E enviei vespões diante de vós, que os expeliram de diante de vós, como  a ambos os reis dos amorreus: não com a tua espada, nem com o teu arco.

[[v6-24-13]]

^<<v6-24-13,13>>^ E eu vos dei a terra em que não trabalhastes, e cidades que não edificastes, e habitais nelas; e comeis das vinhas e dos olivais que não plantastes.

[[v6-24-14]]

^<<v6-24-14,14>>^ Agora pois temei ao Senhor, e servi-o com sinceridade e com verdade: e deitai fora os deuses aos quais serviram vossos pais dalém do rio e no Egito, e servi ao Senhor.

[[v6-24-15]]

^<<v6-24-15,15>>^ Porém, se vos parece mal aos vossos olhos  servir ao Senhor, escolhei hoje a quem sirvais: se os deuses a quem serviram vossos pais, que estavam  dalém do rio, ou os deuses dos amorreus, em cuja terra habitais: porém eu e a minha casa serviremos ao Senhor.

[[v6-24-16]]

^<<v6-24-16,16>>^ Então respondeu o povo, e disse: Nunca nos aconteça que deixemos ao Senhor para servirmos a outros deuses;

[[v6-24-17]]

^<<v6-24-17,17>>^ Porque o Senhor é o nosso Deus; ele é  o que nos fez subir, a nós e a nossos pais, da terra do Egito, da casa da servidão, e o que tem feito estes grandes sinais aos nossos olhos, e nos guardou por todo o caminho que andamos, e entre todos os povos pelo meio dos quais passamos.

[[v6-24-18]]

^<<v6-24-18,18>>^ E o Senhor expeliu de diante de nós a todas estas gentes, até ao amorreu, morador da terra: também nós serviremos ao Senhor, porquanto é  nosso Deus.

[[v6-24-19]]

^<<v6-24-19,19>>^ Então Josué disse ao povo: Não podereis servir ao Senhor, porquanto é  Deus santo é  Deus zeloso, que  não perdoará a vossa transgressão nem os vossos pecados.

[[v6-24-20]]

^<<v6-24-20,20>>^ Se deixardes ao Senhor, e servirdes a deuses estranhos, então se tornará, e vos fará mal, e vos consumirá, depois de vos fazer bem.

[[v6-24-21]]

^<<v6-24-21,21>>^ Então disse o povo a Josué: Não, antes ao Senhor serviremos.

[[v6-24-22]]

^<<v6-24-22,22>>^ E Josué disse ao povo: Sois  testemunhas contra vós mesmos de que vós escolhestes ao Senhor, para o servir. E disseram: Somos  testemunhas.

[[v6-24-23]]

^<<v6-24-23,23>>^ Deitai pois agora fora aos deuses estranhos que há  no meio de vós: e inclinai o vosso coração ao Senhor Deus de Israel.

[[v6-24-24]]

^<<v6-24-24,24>>^ E disse o povo a Josué: Serviremos ao Senhor nosso Deus, e obedeceremos à sua voz.

[[v6-24-25]]

^<<v6-24-25,25>>^ Assim fez Josué concerto naquele dia com o povo, e lho pôs por estatuto e direito em Siquém.

[[v6-24-26]]

^<<v6-24-26,26>>^ E Josué escreveu estas palavras no livro da lei de Deus: e tomou uma grande pedra, e a erigiu ali debaixo do carvalho que estava  junto ao santuário do Senhor.

[[v6-24-27]]

^<<v6-24-27,27>>^ E disse Josué a todo o povo: Eis que esta pedra nos será por testemunho; pois ela ouviu todas as palavras que o Senhor nos tem dito: e também será testemunho contra vós, para que não mintais a vosso Deus.

[[v6-24-28]]

^<<v6-24-28,28>>^ Então Josué despediu o povo, cada um para a sua herdade.

[[v6-24-29]]

^<<v6-24-29,29>>^ E depois destas cousas sucedeu que  Josué, filho de Num, o servo do Senhor, faleceu, sendo  da idade de cento e dez anos.

[[v6-24-30]]

^<<v6-24-30,30>>^ E sepultaram-no no termo da sua herdade, em Timnate-Sera, que está  no monte de Efraim, para o norte do monte de Gaás.

[[v6-24-31]]

^<<v6-24-31,31>>^ Serviu pois Israel ao Senhor todos os dias de Josué, e todos os dias dos anciãos que ainda  viveram muito  depois de Josué, e sabiam toda a obra que o Senhor tinha feito a Israel.

[[v6-24-32]]

^<<v6-24-32,32>>^ Também enterraram em Siquém os ossos de José, que os filhos de Israel trouxeram do Egito, naquela parte do campo que Jacó comprara aos filhos de Hemor, pai de Siquém, por cem peças de prata: porquanto foram em herança para os filhos de José.

[[v6-24-33]]

^<<v6-24-33,33>>^ Faleceu também Eleazar, filho de Aarão, e o sepultaram no outeiro de Fineias, seu filho, que lhe fora dado na montanha de Efraim.

'''

xref:006-josue/006-josue-023.adoc#v6-23-0[&#60; Capítulo Anterior] | <<v6-24-0,Topo>> | xref:007-juizes/007-juizes-001.adoc#v7-1-0[Próximo Capítulo &#62;]