include::./index.adoc[]

[[v6-6-0]]
=== Josué, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v6-6-1]]

^<<v6-6-1,1>>^ ORA Jericó cerrou-se, e estava cerrada por causa dos filhos de Israel: nenhum saía nem entrava.

[[v6-6-2]]

^<<v6-6-2,2>>^ Então disse o Senhor a Josué: Olha tenho dado na tua mão a Jericó e ao seu rei, os seus valentes e valorosos.

[[v6-6-3]]

^<<v6-6-3,3>>^ Vós pois, todos os homens de guerra, rodeareis a cidade, cercando a cidade uma vez; assim fareis por  seis dias.

[[v6-6-4]]

^<<v6-6-4,4>>^ E sete sacerdotes levarão sete buzinas de carneiros diante da arca, e no sétimo dia rodeareis a cidade sete vezes: e os sacerdotes tocarão as buzinas.

[[v6-6-5]]

^<<v6-6-5,5>>^ E será que, tocando-se longamente a buzina de carneiro, ouvindo vós o sonido da buzina, todo o povo gritará com grande grita: e o muro da cidade cairá abaixo, e o povo subirá nele, cada qual em frente de si.

[[v6-6-6]]

^<<v6-6-6,6>>^ Então chamou Josué, filho de Num, aos sacerdotes, e disse-lhes: Levai a arca do concerto; e sete sacerdotes levem sete buzinas de carneiros, diante da arca do Senhor.

[[v6-6-7]]

^<<v6-6-7,7>>^ E disse ao povo: Passai e rodeai a cidade; e quem estiver armado, passe diante da arca do Senhor.

[[v6-6-8]]

^<<v6-6-8,8>>^ E assim foi, como Josué dissera ao povo, que os sete sacerdotes, levando as sete buzinas de carneiros diante do Senhor, passaram, e tocaram as buzinas; e a arca do concerto do Senhor os seguia.

[[v6-6-9]]

^<<v6-6-9,9>>^ E os armados iam adiante dos sacerdotes, que tocavam as buzinas: e a retaguarda seguia após a arca, andando e tocando as buzinas.

[[v6-6-10]]

^<<v6-6-10,10>>^ Porém ao povo Josué tinha dado ordem, dizendo: Não gritareis, nem fareis ouvir a vossa voz, nem sairá palavra alguma da vossa boca, até ao dia que eu vos diga: Gritai. Então gritareis.

[[v6-6-11]]

^<<v6-6-11,11>>^ E fez a arca do Senhor rodear a cidade, rodeando- a  uma vez: e vieram ao arraial, e passaram a noite no arraial.

[[v6-6-12]]

^<<v6-6-12,12>>^ Depois Josué se levantou de madrugada, e os sacerdotes levaram a arca do Senhor.

[[v6-6-13]]

^<<v6-6-13,13>>^ E os sete sacerdotes, que levavam as sete buzinas de carneiros diante da arca do Senhor, iam andando, e tocavam as buzinas, e os armados iam adiante deles, e a retaguarda seguia da arca do Senhor; os sacerdotes iam  andando e tocando as buzinas.

[[v6-6-14]]

^<<v6-6-14,14>>^ Assim rodearam outra vez a cidade no segundo dia e tornaram para o arraial: e assim fizeram seis dias.

[[v6-6-15]]

^<<v6-6-15,15>>^ E sucedeu que  ao sétimo dia madrugaram ao subir da alva, e da mesma maneira rodearam a cidade sete vezes: naquele dia somente rodearam a cidade sete vezes.

[[v6-6-16]]

^<<v6-6-16,16>>^ E sucedeu que , tocando os sacerdotes a sétima vez as buzinas, disse Josué ao povo: Gritai; porque o Senhor vos tem dado a cidade.

[[v6-6-17]]

^<<v6-6-17,17>>^ Porém a cidade será anátema ao Senhor, ela e tudo quanto houver nela: somente a prostituta Raabe viverá, ela e todos os que com ela estiverem em casa; porquanto escondeu os mensageiros que enviamos.

[[v6-6-18]]

^<<v6-6-18,18>>^ Tão somente guardai-vos do anátema, para que não vos metais em anátema tomando dela, e assim façais maldito o arraial de Israel, e o turveis.

[[v6-6-19]]

^<<v6-6-19,19>>^ Porém toda a prata, e o ouro, e os vasos de metal, e de ferro, são consagrados ao Senhor: irão ao tesouro do Senhor.

[[v6-6-20]]

^<<v6-6-20,20>>^ Gritou pois o povo, tocando os sacerdotes as buzinas: e sucedeu que , ouvindo o povo o sonido da buzina, gritou o povo com grande grita; e o muro caiu abaixo, e o povo subiu à cidade, cada qual em frente de si, e tomaram a cidade.

[[v6-6-21]]

^<<v6-6-21,21>>^ E, tudo quanto na cidade havia , destruíram totalmente ao fio da espada, desde o homem até à mulher, desde o menino até ao velho, e até ao boi e gado miúdo, e ao jumento.

[[v6-6-22]]

^<<v6-6-22,22>>^ Josué, porém, disse aos dois homens que tinham espiado a terra: Entrai na casa da mulher prostituta, e tirai de lá a mulher com tudo quanto tiver, como lhe tendes jurado.

[[v6-6-23]]

^<<v6-6-23,23>>^ Então entraram os mancebos espias, e tiraram a Raabe, e a seu pai, e a sua mãe, e a seus irmãos, e a tudo quanto tinha: tiraram também a todas as suas famílias, e puseram-nos fora do arraial de Israel.

[[v6-6-24]]

^<<v6-6-24,24>>^ Porém a cidade e tudo quanto havia  nela queimaram-no a fogo: tão somente a prata, e o ouro, e os vasos de metal e de ferro, deram para o tesouro da casa do Senhor.

[[v6-6-25]]

^<<v6-6-25,25>>^ Assim deu Josué vida à prostituta Raabe, e à família de seu pai, e a tudo quanto tinha; e habitou no meio de Israel até ao dia de  hoje: porquanto escondera os mensageiros que Josué tinha enviado a espiar a Jericó.

[[v6-6-26]]

^<<v6-6-26,26>>^ E naquele tempo Josué os esconjurou, dizendo: Maldito diante do Senhor seja  o homem que se levantar e reedificar esta cidade de Jericó: perdendo o seu primogênito a fundará, e sobre o seu filho  mais novo lhe porá as portas.

[[v6-6-27]]

^<<v6-6-27,27>>^ Assim era o Senhor com Josué: e corria a sua fama por toda a terra.

'''

xref:006-josue/006-josue-005.adoc#v6-5-0[&#60; Capítulo Anterior] | <<v6-6-0,Topo>> | xref:006-josue/006-josue-007.adoc#v6-7-0[Próximo Capítulo &#62;]