include::./index.adoc[]

[[v50-2-0]]
=== Filipenses, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v50-2-1]]

^<<v50-2-1,1>>^ PORTANTO, se há  algum conforto em Cristo, se alguma consolação de amor, se alguma comunhão no Espírito, se alguns entranháveis afetos e compaixões,

[[v50-2-2]]

^<<v50-2-2,2>>^ Completai o meu gozo, para que sintais o mesmo, tendo o mesmo amor, o mesmo ânimo, sentindo uma mesma coisa.

[[v50-2-3]]

^<<v50-2-3,3>>^ Nada façais  por contenda ou por vanglória, mas por humildade; cada um considere os outros superiores a si mesmo.

[[v50-2-4]]

^<<v50-2-4,4>>^ Não atente cada um para o que é propriamente seu mas cada qual também para o que é dos outros.

[[v50-2-5]]

^<<v50-2-5,5>>^ De sorte que haja em vós o mesmo sentimento que houve  também em Cristo Jesus.

[[v50-2-6]]

^<<v50-2-6,6>>^ Que, sendo em forma de Deus, não teve por usurpação ser igual a Deus.

[[v50-2-7]]

^<<v50-2-7,7>>^ Mas aniquilou-se a si mesmo, tomando a forma de servo, fazendo-se semelhante aos homens;

[[v50-2-8]]

^<<v50-2-8,8>>^ E, achado na forma de homem, humilhou-se a si mesmo, sendo obediente até à morte, e morte de cruz.

[[v50-2-9]]

^<<v50-2-9,9>>^ Pelo que também Deus o exaltou soberanamente, e lhe deu um nome que é sobre todo o nome;

[[v50-2-10]]

^<<v50-2-10,10>>^ Para que ao nome de Jesus se dobre todo o joelho dos que estão nos céus, e na terra, e debaixo da terra,

[[v50-2-11]]

^<<v50-2-11,11>>^ E toda a língua confesse que Jesus Cristo é o Senhor, para glória de Deus Pai.

[[v50-2-12]]

^<<v50-2-12,12>>^ De sorte que, meus amados, assim como sempre obedecestes, não só na minha presença, mas muito mais agora na minha ausência, assim também operai a vossa salvação com temor e tremor;

[[v50-2-13]]

^<<v50-2-13,13>>^ Porque Deus é o que opera em vós tanto o querer como o efetuar, segundo a sua  boa vontade.

[[v50-2-14]]

^<<v50-2-14,14>>^ Fazei todas as coisas  sem murmurações nem contendas;

[[v50-2-15]]

^<<v50-2-15,15>>^ Para que sejais irrepreensíveis e sinceros, filhos de Deus inculpáveis no meio duma geração corrompida e perversa, entre a qual resplandeceis como astros no mundo;

[[v50-2-16]]

^<<v50-2-16,16>>^ Retendo a palavra da vida, para que no dia de Cristo possa gloriar-me de não ter corrido nem trabalhado em vão.

[[v50-2-17]]

^<<v50-2-17,17>>^ E, ainda que seja oferecido por libação sobre o sacrifício e serviço da vossa fé, folgo e me regozijo com todos vós.

[[v50-2-18]]

^<<v50-2-18,18>>^ E vós também regozijai-vos e alegrai-vos comigo por isto mesmo.

[[v50-2-19]]

^<<v50-2-19,19>>^ E espero no Senhor Jesus que em breve vos mandarei Timóteo, para que também eu esteja de bom ânimo, sabendo dos vossos negócios.

[[v50-2-20]]

^<<v50-2-20,20>>^ Porque a ninguém tenho de igual sentimento, que sinceramente cuide do vosso estado.

[[v50-2-21]]

^<<v50-2-21,21>>^ Porque todos buscam o que é seu, e não o que é de Cristo Jesus.

[[v50-2-22]]

^<<v50-2-22,22>>^ Mas bem sabeis qual a sua experiência, e que serviu comigo no evangelho, como filho ao pai.

[[v50-2-23]]

^<<v50-2-23,23>>^ De sorte que espero enviar-vo-lo logo que tenha provido a meus negócios.

[[v50-2-24]]

^<<v50-2-24,24>>^ Mas confio no Senhor, que também eu mesmo em breve irei ter convosco.

[[v50-2-25]]

^<<v50-2-25,25>>^ Julguei, contudo, necessário mandar-vos Epafrodito, meu irmão, e cooperador, e companheiro nos combates, e vosso enviado para prover às minhas necessidades.

[[v50-2-26]]

^<<v50-2-26,26>>^ Porquanto tinha muitas saudades de vós todos, e estava muito angustiado de que tivésseis ouvido que ele estivera doente.

[[v50-2-27]]

^<<v50-2-27,27>>^ E de fato esteve doente, e quase à morte, mas Deus se apiedou dele, e não somente dele, mas também de mim, para que eu não tivesse tristeza sobre tristeza.

[[v50-2-28]]

^<<v50-2-28,28>>^ Por isso vo-lo enviei mais depressa, para que, vendo-o outra vez, vos regozijeis, e eu tenha menos tristeza.

[[v50-2-29]]

^<<v50-2-29,29>>^ Recebei-o pois no Senhor com todo o gozo, e tende-o em honra.

[[v50-2-30]]

^<<v50-2-30,30>>^ Porque pela obra de Cristo chegou até bem próximo da morte, não fazendo caso da vida para suprir para comigo a falta do vosso serviço.

'''

xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[Próximo Capítulo &#62;]