include::./index.adoc[]

[[v50-1-0]]
=== Filipenses, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v50-1-1]]

^<<v50-1-1,1>>^ PAULO e Timóteo, servos de Jesus Cristo, a todos os santos em Cristo Jesus, que estão em Filipos, com os bispos e diáconos;

[[v50-1-2]]

^<<v50-1-2,2>>^ Graça a vós, e paz da parte de Deus nosso Pai e da do Senhor Jesus Cristo.

[[v50-1-3]]

^<<v50-1-3,3>>^ Dou graças ao meu Deus todas as vezes que me lembro de vós.

[[v50-1-4]]

^<<v50-1-4,4>>^ Fazendo sempre com alegria oração por vós em todas as minhas súplicas.

[[v50-1-5]]

^<<v50-1-5,5>>^ Pela vossa cooperação no evangelho desde o primeiro dia até agora.

[[v50-1-6]]

^<<v50-1-6,6>>^ Tendo por certo isto mesmo, que aquele que em vós começou a boa obra a aperfeiçoará até ao dia de Jesus Cristo;

[[v50-1-7]]

^<<v50-1-7,7>>^ Como tenho por justo sentir isto de vós todos, porque vos retenho em meu  coração, pois todos vós fostes participantes da minha graça, tanto nas minhas prisões como na minha  defesa e confirmação do evangelho.

[[v50-1-8]]

^<<v50-1-8,8>>^ Porque Deus me é testemunha das saudades que de todos vós tenho, em entranhável afeição de Jesus Cristo.

[[v50-1-9]]

^<<v50-1-9,9>>^ E peço isto: que a vossa caridade abunde mais e mais em ciência e em todo o conhecimento.

[[v50-1-10]]

^<<v50-1-10,10>>^ Para que aproveis as coisas excelentes, para que sejais sinceros, e sem escândalo algum até ao dia de Cristo;

[[v50-1-11]]

^<<v50-1-11,11>>^ Cheios de frutos de justiça, que são por Jesus Cristo, para glória e louvor de Deus.

[[v50-1-12]]

^<<v50-1-12,12>>^ E quero, irmãos, que saibais que as coisas  que me aconteceram  contribuíram para maior proveito do evangelho.

[[v50-1-13]]

^<<v50-1-13,13>>^ De maneira que as minhas prisões em Cristo foram manifestas por toda a guarda pretoriana, e por todos os demais lugares;

[[v50-1-14]]

^<<v50-1-14,14>>^ E muitos dos irmãos no Senhor, tomando ânimo com as minhas prisões, ousam falar a palavra mais confiadamente, sem temor.

[[v50-1-15]]

^<<v50-1-15,15>>^ Verdade é que também alguns pregam a Cristo por inveja e porfia, mas outros de boa mente;

[[v50-1-16]]

^<<v50-1-16,16>>^ Uns por amor, sabendo que fui posto para defesa do evangelho.

[[v50-1-17]]

^<<v50-1-17,17>>^ Mas outros, na verdade, anunciam a Cristo por contenção, não puramente, julgando acrescentar aflição às minhas prisões.

[[v50-1-18]]

^<<v50-1-18,18>>^ Mas que importa ? contanto que Cristo seja anunciado de toda a maneira, ou com fingimento ou em verdade, nisto me regozijo, e me regozijarei ainda.

[[v50-1-19]]

^<<v50-1-19,19>>^ Porque sei que disto me resultará salvação, pela vossa oração e pelo socorro do Espírito de Jesus Cristo.

[[v50-1-20]]

^<<v50-1-20,20>>^ Segundo a minha intensa expectação e esperança, de que em nada serei confundido; antes, com toda a confiança, Cristo será, tanto agora como sempre, engrandecido no meu corpo, seja pela vida, seja pela morte.

[[v50-1-21]]

^<<v50-1-21,21>>^ Porque para mim o viver é  Cristo, e o morrer é  ganho.

[[v50-1-22]]

^<<v50-1-22,22>>^ Mas, se o viver na carne me der fruto da minha obra, não sei então o que deva escolher.

[[v50-1-23]]

^<<v50-1-23,23>>^ Mas de ambos os lados  estou em aperto, tendo desejo de partir, e estar com Cristo, porque isto é ainda muito melhor.

[[v50-1-24]]

^<<v50-1-24,24>>^ Mas julgo  mais necessário, por amor de vós, ficar na carne.

[[v50-1-25]]

^<<v50-1-25,25>>^ E, tendo esta confiança, sei que ficarei, e permanecerei com todos vós para proveito vosso e gozo da fé.

[[v50-1-26]]

^<<v50-1-26,26>>^ Para que a vossa glória abunde por mim em Cristo Jesus, pela minha nova ida a vós.

[[v50-1-27]]

^<<v50-1-27,27>>^ Somente deveis portar-vos dignamente conforme o evangelho de Cristo, para que, quer vá e vos veja, quer esteja ausente, ouça acerca de vós que estais num mesmo  espírito, combatendo juntamente com o mesmo ânimo pela fé do evangelho.

[[v50-1-28]]

^<<v50-1-28,28>>^ E em nada vos espanteis dos que resistem, o que para eles, na verdade, é indício de perdição, mas para vós de salvação, e isto de Deus.

[[v50-1-29]]

^<<v50-1-29,29>>^ Porque a vós vos foi concedido, em relação a Cristo, não somente crer nele, como também padecer por ele.

[[v50-1-30]]

^<<v50-1-30,30>>^ Tendo o mesmo combate que já  em mim tendes visto e agora ouvis estar em mim.

'''

xref:049-efesios/049-efesios-006.adoc#v49-6-0[&#60; Capítulo Anterior] | <<v50-1-0,Topo>> | xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[Próximo Capítulo &#62;]