include::./index.adoc[]

[[v31-1-0]]
=== Obadias, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v31-1-1]]

^<<v31-1-1,1>>^ VISÃO de Obadias: Assim diz o Senhor Jeová  a respeito de Edom: Temos ouvido a pregação do Senhor, e foi enviado às nações um embaixador, dizendo: Levantai-vos, e levantemo-nos contra ela para a guerra.

[[v31-1-2]]

^<<v31-1-2,2>>^ Eis que te fiz pequeno entre as nações; tu és mui desprezado.

[[v31-1-3]]

^<<v31-1-3,3>>^ A soberba do teu coração te enganou, como  o que habita nas fendas das rochas, na  sua alta morada, que diz no seu coração: Quem me derribará em terra?

[[v31-1-4]]

^<<v31-1-4,4>>^ Se te elevares como águia, e puseres o teu ninho entre as estrelas, dali te derribarei, diz o Senhor.

[[v31-1-5]]

^<<v31-1-5,5>>^ Se viessem a ti ladrões, ou roubadores de noite (como estás destruído!), não furtariam o que lhes bastasse? se a ti viessem os vindimadores, não deixariam alguns cachos?

[[v31-1-6]]

^<<v31-1-6,6>>^ Como foram buscados os bens de Esaú! como foram esquadrinhados os seus esconderijos!

[[v31-1-7]]

^<<v31-1-7,7>>^ Todos os teus confederados te levaram para fora dos teus limites: os que gozam da tua paz te enganaram, prevaleceram contra ti; os que comem  o teu pão puseram debaixo de ti uma armadilha: não há em Edom entendimento.

[[v31-1-8]]

^<<v31-1-8,8>>^ E não acontecerá naquele dia, diz o Senhor, que farei perecer os sábios de Edom, e  o entendimento na montanha de Esaú?

[[v31-1-9]]

^<<v31-1-9,9>>^ E os teus valentes, ó Temã, estarão atemorizados, para que da montanha de Esaú seja cada um exterminado pela matança.

[[v31-1-10]]

^<<v31-1-10,10>>^ Por causa da violência feita a teu irmão Jacó, cobrir-te-á a confusão, e serás  exterminado para sempre.

[[v31-1-11]]

^<<v31-1-11,11>>^ No dia em que estiveste em frente dele, no dia em que os forasteiros levavam cativo o seu exército, e os estranhos entravam pelas suas portas, e lançavam sortes sobre Jerusalém, tu mesmo eras um deles.

[[v31-1-12]]

^<<v31-1-12,12>>^ Mas tu não devias olhar para o dia de teu irmão, no dia do seu desterro; nem alegrar-te sobre os filhos de Judá, no dia da sua ruína; nem alargar a tua boca, no dia da angústia;

[[v31-1-13]]

^<<v31-1-13,13>>^ Nem entrar pela porta do meu povo, no dia da sua calamidade; sim, tu não devias olhar, satisfeito , para o seu mal, no dia da sua calamidade; nem estender as tuas mãos  contra o seu exército, no dia da sua calamidade;

[[v31-1-14]]

^<<v31-1-14,14>>^ Nem parar nas encruzilhadas, para exterminares os que escapassem: nem entregar os que lhe restassem, no dia da angústia.

[[v31-1-15]]

^<<v31-1-15,15>>^ Porque o dia do Senhor está perto, sobre todas as nações: como tu fizeste, assim se fará contigo: a tua maldade cairá sobre a tua cabeça.

[[v31-1-16]]

^<<v31-1-16,16>>^ Porque, como vós bebestes no monte da minha santidade, assim beberão de contínuo todas as nações: beberão, e engolirão, e serão como se nunca tivessem sido.

[[v31-1-17]]

^<<v31-1-17,17>>^ Mas no monte de Sião haverá livramento; e ele será santo; e os da casa de Jacó possuirão as suas herdades.

[[v31-1-18]]

^<<v31-1-18,18>>^ E a casa de Jacó será fogo, e a casa de José chama, e a casa de Esaú palha; e se acenderão contra eles, e os consumirão; e ninguém mais restará da casa de Esaú, porque o Senhor o  disse.

[[v31-1-19]]

^<<v31-1-19,19>>^ E os do sul possuirão a montanha de Esaú, e os das planícies os filisteus; possuirão também os campos de Efraim, e os campos de Samaria; e Benjamim e Gileade.

[[v31-1-20]]

^<<v31-1-20,20>>^ E os cativos deste exército dos filhos de Israel, que estão entre os cananitas, possuirão  até Zarefate; e os cativos de Jerusalém, que estão em Sefarade, possuirão as cidades do Sul.

[[v31-1-21]]

^<<v31-1-21,21>>^ E levantar-se-ão salvadores no monte Sião, para julgarem a montanha de Esaú; e o reino será do Senhor.

'''

xref:030-amos/030-amos-009.adoc#v30-9-0[&#60; Capítulo Anterior] | <<v31-1-0,Topo>> | xref:032-jonas/032-jonas-001.adoc#v32-1-0[Próximo Capítulo &#62;]