include::./index.adoc[]

[[v64-1-0]]
=== 3 João, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v64-1-1]]

^<<v64-1-1,1>>^ O PRESBÍTERO ao amado Gaio, a quem em verdade eu amo.

[[v64-1-2]]

^<<v64-1-2,2>>^ Amado, desejo que te vá bem em todas as coisas, e que tenhas saúde, assim  como bem vai à tua alma.

[[v64-1-3]]

^<<v64-1-3,3>>^ Porque muito me alegrei quando os irmãos vieram, e testificaram da tua verdade, como tu andas na verdade.

[[v64-1-4]]

^<<v64-1-4,4>>^ Não tenho maior gozo do que este: o de ouvir que os meus filhos andam na verdade.

[[v64-1-5]]

^<<v64-1-5,5>>^ Amado, procedes fielmente em tudo o que fazes para com os irmãos, e para com os estranhos,

[[v64-1-6]]

^<<v64-1-6,6>>^ Que em presença da igreja testificaram da tua caridade: aos quais, se conduzires como é digno para com Deus, bem farás;

[[v64-1-7]]

^<<v64-1-7,7>>^ Porque pelo seu Nome saíram, nada tomando dos gentios.

[[v64-1-8]]

^<<v64-1-8,8>>^ Portanto aos tais devemos receber, para que sejamos cooperadores da verdade.

[[v64-1-9]]

^<<v64-1-9,9>>^ Tenho escrito à igreja; mas Diótrefes, que procura ter entre eles o primado, não nos recebe.

[[v64-1-10]]

^<<v64-1-10,10>>^ Pelo que, se eu for, trarei à memória as obras que ele faz, proferindo contra nós palavras maliciosas; e, não contente com isto, não recebe os irmãos, e impede os que querem recebê-los , e os lança fora da igreja.

[[v64-1-11]]

^<<v64-1-11,11>>^ Amado, não sigas o mal, mas o bem. Quem faz bem é de Deus; mas quem faz mal não tem visto a Deus.

[[v64-1-12]]

^<<v64-1-12,12>>^ Todos dão testemunho de Demétrio, até a mesma verdade; e também nós testemunhamos; e vós bem sabeis que o nosso testemunho é verdadeiro.

[[v64-1-13]]

^<<v64-1-13,13>>^ Tinha muito que escrever, mas não quero escrever-te com tinta e pena.

[[v64-1-14]]

^<<v64-1-14,14>>^ Espero, porém, ver-te brevemente, e falaremos de boca a boca.

[[v64-1-15]]

^<<v64-1-15,15>>^ Paz seja contigo. Os amigos te saúdam. Saúda os amigos pelo seu nome.

'''

xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[&#60; Capítulo Anterior] | <<v64-1-0,Topo>> | xref:065-judas/065-judas-001.adoc#v65-1-0[Próximo Capítulo &#62;]