include::./index.adoc[]

[[v26-43-0]]
=== Ezequiel, 43
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-43-1]]

^<<v26-43-1,1>>^ ENTÃO me levou à porta, à porta que olha para o caminho do oriente.

[[v26-43-2]]

^<<v26-43-2,2>>^ E eis que a glória do Deus de Israel vinha do caminho do oriente; e a sua voz era  como a voz de muitas águas, e a terra resplandeceu por causa da sua glória.

[[v26-43-3]]

^<<v26-43-3,3>>^ E o aspecto da visão que vi era  como o da visão que eu tinha visto quando vim destruir a cidade; e eram  as visões como a que vi junto ao rio Quebar; e caí sobre o meu rosto.

[[v26-43-4]]

^<<v26-43-4,4>>^ E a glória do Senhor entrou no templo pelo  caminho da porta, cuja face está para o lado do oriente.

[[v26-43-5]]

^<<v26-43-5,5>>^ E levantou-me o espírito, e me levou ao átrio interior: e eis que a glória do Senhor encheu o templo.

[[v26-43-6]]

^<<v26-43-6,6>>^ E ouvi uma voz que me foi dirigida de dentro do templo, e um homem se pôs junto de mim.

[[v26-43-7]]

^<<v26-43-7,7>>^ E me disse: Filho do homem, este é  o lugar do meu trono, e o lugar das plantas dos meus pés, onde habitarei no meio dos filhos de Israel para sempre; e os  da casa de Israel não contaminarão mais o meu nome santo, nem  eles nem os seus reis, com as suas prostituições e com os cadáveres dos seus reis, nos seus altos,

[[v26-43-8]]

^<<v26-43-8,8>>^ Pondo o seu umbral ao pé do meu umbral, e a sua ombreira junto à minha ombreira, e havendo uma parede entre mim e entre eles; e contaminaram o meu santo nome com as suas abominações que faziam; por isso eu  os consumi na minha ira.

[[v26-43-9]]

^<<v26-43-9,9>>^ Agora lancem eles para longe de mim a sua prostituição e os cadáveres dos seus reis, e habitarei no meio deles para sempre.

[[v26-43-10]]

^<<v26-43-10,10>>^ Tu pois , ó filho do homem, mostra à casa de Israel esta casa, para que se envergonhe das suas maldades: sirva-lhe ela de modelo.

[[v26-43-11]]

^<<v26-43-11,11>>^ E, envergonhando-se eles de tudo quanto fizeram, faze-lhes saber a forma desta casa, e a sua figura, e as suas saídas, e as suas entradas, e todas as suas formas, e todos os seus estatutos, todas as suas formas, e todas as suas leis; e escreve isto aos seus olhos, para que guardem toda a sua forma, e todos os seus estatutos, e os cumpram.

[[v26-43-12]]

^<<v26-43-12,12>>^ Esta é a lei da casa: Sobre o cume do monte todo o seu contorno em redor será santíssimo; eis que esta é  a lei da casa.

[[v26-43-13]]

^<<v26-43-13,13>>^ E estas são  as medidas do altar, por côvados (o côvado é um côvado e um palmo): a parte inferior será dum côvado de altura, e um côvado de largura, e a sua borda, em todo o seu contorno, dum palmo; e esta é  a base do altar.

[[v26-43-14]]

^<<v26-43-14,14>>^ É do fundo, desde a terra até à listra de baixo, dois côvados, e de largura um côvado; e desde a pequena listra até à listra grande, quatro côvados, e a largura um côvado.

[[v26-43-15]]

^<<v26-43-15,15>>^ E o Harel, de quatro côvados: e desde o Ariel até cima havia  quatro cornos.

[[v26-43-16]]

^<<v26-43-16,16>>^ E o Ariel terá doze côvados  de comprimento, e  doze de largura, quadrado nos quatro lados.

[[v26-43-17]]

^<<v26-43-17,17>>^ E a listra, catorze côvados  de comprimento, e  catorze de largura, nos seus quatro lados; e o contorno, ao redor dela, de meio côvado, e o fundo dela de um côvado, ao redor; e os seus degraus olhavam para o oriente.

[[v26-43-18]]

^<<v26-43-18,18>>^ E me disse: Filho do homem, assim diz o Senhor Jeová : Estes são  os estatutos do altar, no dia em que o farão, para oferecerem sobre ele holocausto e para espalharem sobre ele sangue.

[[v26-43-19]]

^<<v26-43-19,19>>^ E aos sacerdotes levitas, que são da semente de Zadoque, que se chegam a mim (diz o Senhor Jeová ) para me servirem, darás um  bezerro, para expiação do pecado.

[[v26-43-20]]

^<<v26-43-20,20>>^ E tomarás do seu sangue, e o  porás sobre os seus quatro ângulos, e nas quatro esquinas da listra, e no contorno ao redor assim farás a purificação e a expiação.

[[v26-43-21]]

^<<v26-43-21,21>>^ Então tomarás o bezerro da expiação do pecado, o qual será queimado no lugar da casa para isso ordenado, fora do santuário.

[[v26-43-22]]

^<<v26-43-22,22>>^ E no segundo dia oferecerás um  bode, sem mancha, para expiação do pecado: e purificarão o altar, como o purificaram com o bezerro.

[[v26-43-23]]

^<<v26-43-23,23>>^ E, acabando tu de o purificar, oferecerás um bezerro, sem mancha, e um carneiro do rebanho, sem mancha.

[[v26-43-24]]

^<<v26-43-24,24>>^ E os oferecerás perante a face do Senhor; e os sacerdotes deitarão sal sobre eles, e os oferecerão em holocausto ao Senhor.

[[v26-43-25]]

^<<v26-43-25,25>>^ Durante sete dias prepararás cada dia um  bode para expiação: também prepararão um bezerro, e um carneiro do rebanho, sem mancha.

[[v26-43-26]]

^<<v26-43-26,26>>^ Por sete dias expiarão o altar, e o  purificarão, e assim o consagrarão.

[[v26-43-27]]

^<<v26-43-27,27>>^ E, cumprindo eles estes dias, será que , ao oitavo dia, e dali em diante, prepararão os sacerdotes sobre o altar os vossos holocaustos e os vossos sacrifícios pacíficos; e eu me deleitarei em vós, diz o Senhor Jeová .

'''

xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[&#60; Capítulo Anterior] | <<v26-43-0,Topo>> | xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[Próximo Capítulo &#62;]