include::./index.adoc[]

[[v26-3-0]]
=== Ezequiel, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-3-1]]

^<<v26-3-1,1>>^ DEPOIS me disse: Filho do homem, come o que achares; come este rolo, e vai, fala à casa de Israel.

[[v26-3-2]]

^<<v26-3-2,2>>^ Então abri a minha boca, e me deu a comer o rolo.

[[v26-3-3]]

^<<v26-3-3,3>>^ E disse-me: Filho do homem, dá de comer ao teu ventre, e enche as tuas entranhas deste rolo que eu te dou. Então o comi, e era na minha boca doce como o mel.

[[v26-3-4]]

^<<v26-3-4,4>>^ E disse-me: Filho do homem, vai, entra na casa de Israel, e dize-lhe as minhas palavras.

[[v26-3-5]]

^<<v26-3-5,5>>^ Porque tu não és enviado a um povo de estranha fala, nem de língua difícil, mas à casa de Israel;

[[v26-3-6]]

^<<v26-3-6,6>>^ Nem a muitos povos de estranha fala, e de língua difícil, cujas palavras não possas entender: se eu aos tais te enviara, certamente te dariam ouvidos.

[[v26-3-7]]

^<<v26-3-7,7>>^ Mas a casa de Israel não te quererá dar ouvidos, porque não me querem dar ouvidos a mim; porque toda a casa de Israel é de rosto obstinado e dura de coração.

[[v26-3-8]]

^<<v26-3-8,8>>^ Eis que fiz duro o teu rosto contra os seus rostos, e forte a tua fronte contra a sua fronte.

[[v26-3-9]]

^<<v26-3-9,9>>^ Fiz como diamante a tua fronte, mais forte do que a pederneira; não os temas pois , nem te assombres com os seus rostos, porque casa rebelde são.

[[v26-3-10]]

^<<v26-3-10,10>>^ Disse-me mais: Filho do homem, mete no teu coração todas as minhas palavras que te hei de dizer, e ouve- as  com os teus ouvidos.

[[v26-3-11]]

^<<v26-3-11,11>>^ Eia pois, vai aos do cativeiro, aos filhos do teu povo, e lhes falarás, e lhes dirás: Assim diz o Senhor Jeová , quer ouçam quer deixem de ouvir.

[[v26-3-12]]

^<<v26-3-12,12>>^ E levantou-me o espírito, e ouvi por detrás de mim uma voz de grande estrondo, que dizia : Bendita seja a glória do Senhor, desde o seu lugar.

[[v26-3-13]]

^<<v26-3-13,13>>^ E ouvi  o barulho das asas dos animais, que tocavam umas nas outras, e o barulho das rodas defronte deles, e o sonido dum grande estrondo.

[[v26-3-14]]

^<<v26-3-14,14>>^ Então o espírito me levantou, e me levou; e eu me fui mui triste, no ardor do meu espírito; mas a mão do Senhor era forte sobre mim.

[[v26-3-15]]

^<<v26-3-15,15>>^ E vim aos do cativeiro, a Tel-Abibe, que moravam junto ao rio Quebar, e eu morava onde eles moravam; e fiquei ali sete dias, pasmado no meio deles.

[[v26-3-16]]

^<<v26-3-16,16>>^ E sucedeu que, ao fim de sete dias, veio a palavra do Senhor a mim, dizendo:

[[v26-3-17]]

^<<v26-3-17,17>>^ Filho do homem: Eu te dei por atalaia sobre a casa de Israel; e tu da minha boca ouvirás a palavra, e os avisarás da minha parte.

[[v26-3-18]]

^<<v26-3-18,18>>^ Quando eu disser ao ímpio: Certamente morrerás; não o avisando tu, não falando para avisar o ímpio acerca do seu caminho ímpio, para salvar a sua vida, aquele ímpio morrerá na sua maldade, mas o seu sangue da tua mão o  requererei.

[[v26-3-19]]

^<<v26-3-19,19>>^ Mas, se avisares o ímpio, e ele não se converter da sua impiedade e do seu caminho ímpio, ele morrerá na sua maldade, mas tu livraste a tua alma.

[[v26-3-20]]

^<<v26-3-20,20>>^ Semelhantemente, quando o justo se desviar da sua justiça, e fizer maldade, e eu puser diante dele um tropeço, ele morrerá; porque, não o avisando tu, no seu pecado morrerá, e suas justiças que praticara não virão em memória, mas o seu sangue da tua mão o requererei.

[[v26-3-21]]

^<<v26-3-21,21>>^ Mas, avisando tu o justo, para que o justo não peque, e ele não pecar, certamente viverá, porque foi avisado; e tu livraste a tua alma.

[[v26-3-22]]

^<<v26-3-22,22>>^ E a mão do Senhor estava sobre mim ali, e me disse: Levanta-te, e sai ao vale, e ali falarei contigo.

[[v26-3-23]]

^<<v26-3-23,23>>^ E levantei-me, e saí ao vale, e eis que a glória do Senhor estava ali, como a glória que vi junto ao rio Quebar; e caí sobre o meu rosto.

[[v26-3-24]]

^<<v26-3-24,24>>^ Então entrou em mim, o espírito, e me pôs em pé, e falou comigo, e me disse: Entra, encerra-te dentro da tua casa.

[[v26-3-25]]

^<<v26-3-25,25>>^ Porque, ó filho do homem, eis que porão cordas sobre ti, e te ligarão com elas; não sairás pois ao meio deles.

[[v26-3-26]]

^<<v26-3-26,26>>^ E eu farei que a tua língua se pegue ao teu paladar, e ficarás mudo, e não lhes servirás de varão que repreenda; porque casa rebelde são eles.

[[v26-3-27]]

^<<v26-3-27,27>>^ Mas quando eu falar contigo, abrirei a tua boca, e lhes dirás: Assim diz o Senhor: Quem ouvir ouça, e quem deixar de  ouvir, deixe: porque casa rebelde são eles.

'''

xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[&#60; Capítulo Anterior] | <<v26-3-0,Topo>> | xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[Próximo Capítulo &#62;]