include::./index.adoc[]

[[v26-41-0]]
=== Ezequiel, 41
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-41-1]]

^<<v26-41-1,1>>^ ENTÃO me levou ao templo, e mediu os pilares, seis côvados de largura de uma banda, e seis côvados de largura da outra, que era a largura do tabernáculo.

[[v26-41-2]]

^<<v26-41-2,2>>^ E a largura da entrada, dez côvados; e os lados da entrada, cinco côvados de uma banda e cinco côvados da outra: também mediu o seu comprimento, de quarenta côvados, e a largura, de vinte côvados.

[[v26-41-3]]

^<<v26-41-3,3>>^ E entrou dentro, e mediu o pilar da entrada, dois côvados, e a entrada, seis côvados, e a largura da entrada, sete côvados.

[[v26-41-4]]

^<<v26-41-4,4>>^ Também mediu o seu comprimento, vinte côvados, e a largura, vinte côvados, diante do templo, e me disse: Esta é  a Santidade das Santidades.

[[v26-41-5]]

^<<v26-41-5,5>>^ E mediu a parede do templo, seis côvados, e a largura das câmaras laterais, quatro côvados, por todo o redor do templo.

[[v26-41-6]]

^<<v26-41-6,6>>^ E as câmaras laterais, câmara sobre câmara, eram  trinta e três por ordem, e entravam na parede que  tocava no templo pelas câmaras laterais em redor, para se susterem nelas, porque não travavam da parede do templo.

[[v26-41-7]]

^<<v26-41-7,7>>^ E havia maior  largura e volta nas câmaras laterais para cima, porque o caracol do templo subia  mui alto por todo o redor do templo, por isso que o templo tinha mais  largura para cima; e assim da câmara baixa se subia à mais alta pelo meio.

[[v26-41-8]]

^<<v26-41-8,8>>^ E olhei para a altura do templo em redor: e eram  os fundamentos das câmaras laterais da medida  de uma cana inteira, seis côvados grandes.

[[v26-41-9]]

^<<v26-41-9,9>>^ A grossura da parede das câmaras laterais de fora era  de cinco côvados; e o que foi deixado vazio era  o lugar das câmaras laterais, que estavam  junto ao templo.

[[v26-41-10]]

^<<v26-41-10,10>>^ E entre as câmaras havia  a largura de vinte côvados por todo o redor do templo.

[[v26-41-11]]

^<<v26-41-11,11>>^ E as entradas das câmaras laterais estavam  voltadas para o lugar  vazio: uma entrada para o caminho do norte, e outra entrada para o  do sul: e a largura do lugar vazio era  de cinco côvados em redor.

[[v26-41-12]]

^<<v26-41-12,12>>^ Era também o edifício que estava  diante do lugar separado, à  esquina do caminho do ocidente, da largura de setenta côvados; e a parede do edifício de cinco côvados de largura em redor; e o seu comprimento era  de noventa côvados.

[[v26-41-13]]

^<<v26-41-13,13>>^ E mediu o templo, do comprimento de cem côvados, como também o lugar separado, e o edifício, e as suas paredes, cem côvados de comprimento.

[[v26-41-14]]

^<<v26-41-14,14>>^ E a largura da dianteira do templo, e do lugar separado para o oriente, de uma e de outra parte, cem côvados.

[[v26-41-15]]

^<<v26-41-15,15>>^ Também mediu o comprimento do edifício, diante do lugar separado, que estava  por detrás, e as suas galerias de uma e de outra parte, cem côvados, com o templo de dentro e os vestíbulos do átrio.

[[v26-41-16]]

^<<v26-41-16,16>>^ Os umbrais e as janelas estreitas, e as galerias em redor dos três, defronte do umbral, estavam  cobertas de madeira em redor; e isto desde  o chão até às janelas; e as janelas estavam cobertas;

[[v26-41-17]]

^<<v26-41-17,17>>^ Até ao  espaço em cima da porta, e até ao templo de dentro e de fora, e até toda a parede em redor, por dentro e por fora, tudo  com medidas.

[[v26-41-18]]

^<<v26-41-18,18>>^ E foi  feito com  querubins e palmeiras, de maneira que cada  palmeira estava  entre querubim e querubim, e cada  querubim tinha dois rostos,

[[v26-41-19]]

^<<v26-41-19,19>>^ A saber: um rosto de homem olhava  para a palmeira duma banda e um rosto de leãozinho para a palmeira da outra: assim  foi feito por toda a casa  em redor.

[[v26-41-20]]

^<<v26-41-20,20>>^ Desde o chão até acima da entrada estavam  feitos os querubins e as palmas, como também pela  parede do templo.

[[v26-41-21]]

^<<v26-41-21,21>>^ As ombreiras do templo eram  quadradas, e, no tocante à dianteira do santuário, a feição duma era  como a feição da outra.

[[v26-41-22]]

^<<v26-41-22,22>>^ O altar de madeira era  de três côvados de altura, e o seu comprimento de dois côvados, e tinha as suas esquinas; e o seu fundamento e as suas paredes eram  de madeira; e me disse: Esta é  a mesa que está  perante a face do Senhor.

[[v26-41-23]]

^<<v26-41-23,23>>^ E o templo e o santuário ambos  tinham duas portas.

[[v26-41-24]]

^<<v26-41-24,24>>^ E havia dois batentes para as portas: dois batentes volantes: dois para uma porta, e dois batentes para a outra.

[[v26-41-25]]

^<<v26-41-25,25>>^ E foram  feitos nelas, nas portas do templo, querubins e palmeiras, como estavam  feitos nas paredes, e havia  uma trave grossa de madeira na dianteira do vestíbulo por fora.

[[v26-41-26]]

^<<v26-41-26,26>>^ E havia  janelas estreitas, e palmeiras, duma e doutra banda nos lados do vestíbulo, como também nas câmaras do templo e nas  grossas traves.

'''

xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[&#60; Capítulo Anterior] | <<v26-41-0,Topo>> | xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[Próximo Capítulo &#62;]