include::./index.adoc[]

[[v26-17-0]]
=== Ezequiel, 17
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-17-1]]

^<<v26-17-1,1>>^ E VEIO a mim a palavra do Senhor, dizendo:

[[v26-17-2]]

^<<v26-17-2,2>>^ Filho do homem, propõe uma parábola, e usa duma comparação para com a casa de Israel.

[[v26-17-3]]

^<<v26-17-3,3>>^ E dize: Assim diz o Senhor Jeová : Uma grande águia, de grandes asas, de farta plumagem, cheia de penas de várias cores, veio ao Líbano e levou o mais alto ramo dum cedro.

[[v26-17-4]]

^<<v26-17-4,4>>^ E  arrancou a ponta mais alta dos seus ramos, e a trouxe a uma terra de mercancia, na cidade de mercadores a pôs.

[[v26-17-5]]

^<<v26-17-5,5>>^ Tomou da semente da terra, e a lançou num campo de semente: tomando-a, a pôs junto às grandes águas com grande prudência.

[[v26-17-6]]

^<<v26-17-6,6>>^ E brotou, e tornou-se numa videira mui larga, de pouca altura, virando-se para ela os seus ramos, porque as suas raízes estavam debaixo dela; e tornou-se numa videira, e produzia sarmentos, e lançava renovos.

[[v26-17-7]]

^<<v26-17-7,7>>^ E  houve mais uma grande águia, de grandes asas, e cheia de penas; e eis que esta videira lançou para ela as suas raízes, e estendeu para ela os seus ramos, desde as auréolas do seu plantio, para que a regasse.

[[v26-17-8]]

^<<v26-17-8,8>>^ Numa boa terra, à borda de muitas águas, estava ela plantada, para produzir ramos, e para dar fruto, para que fosse videira excelente.

[[v26-17-9]]

^<<v26-17-9,9>>^ Dize: Assim diz o Senhor Jeová : Ela prosperará? não lhe arrancará ele as suas raízes, e não cortará o seu fruto, para que se seque? em  todas as folhas de seus renovos se secará; e, não com braço grande, nem com muita gente, será arrancada pelas suas raízes.

[[v26-17-10]]

^<<v26-17-10,10>>^ Mas, estando  plantada, prosperará? porventura , tocando-lhe vento oriental, de todo não se secará? desde as auréolas do seu plantio se secará.

[[v26-17-11]]

^<<v26-17-11,11>>^ Então veio a mim a palavra do Senhor, dizendo:

[[v26-17-12]]

^<<v26-17-12,12>>^ Dize agora à casa rebelde: Não sabeis o que significam estas cousas? dize: Eis que veio o rei de Babilônia a  Jerusalém, e tomou o seu rei e os seus príncipes, e os levou consigo para Babilônia;

[[v26-17-13]]

^<<v26-17-13,13>>^ E tomou um  da semente real, e fez concerto com ele, e o trouxe sob juramento; e tomou os poderosos da terra;

[[v26-17-14]]

^<<v26-17-14,14>>^ Para que o reino ficasse humilhado, e não se levantasse: para que, guardando o seu concerto, pudesse subsistir.

[[v26-17-15]]

^<<v26-17-15,15>>^ Mas rebelou-se contra ele, enviando os seus mensageiros ao Egito, para que lhe mandassem cavalos e muita gente: prosperará ou escapará aquele que faz tais cousas? ou quebrantará o concerto, e escapará?

[[v26-17-16]]

^<<v26-17-16,16>>^ Como eu vivo, diz o Senhor Jeová , no lugar em que habita o rei que o fez reinar, cujo juramento desprezou, e cujo concerto quebrantou, sim, com ele no meio de Babilônia certamente morrerá.

[[v26-17-17]]

^<<v26-17-17,17>>^ E Faraó, nem com grande exército, nem com uma companhia numerosa, fará cousa alguma com ele em guerra, levantando tranqueiras e edificando baluartes, para destruir muitas vidas.

[[v26-17-18]]

^<<v26-17-18,18>>^ Pois que desprezou o juramento, quebrantando o concerto, e deu a sua mão; havendo feito todas estas cousas, não escapará.

[[v26-17-19]]

^<<v26-17-19,19>>^ Portanto, assim diz o Senhor Jeová : Vivo eu, que o meu juramento, que desprezou, e o meu concerto, que quebrantou, isto farei recair sobre a sua cabeça.

[[v26-17-20]]

^<<v26-17-20,20>>^ E estenderei sobre ele a minha rede, e ficará preso no meu laço; e o levarei a Babilônia, e ali entrarei em juízo com ele pela  rebeldia com que se rebelou contra mim.

[[v26-17-21]]

^<<v26-17-21,21>>^ E todos os seus fugitivos, com todas as suas tropas, cairão à espada, e os que restarem serão espalhados em todas as direções; e sabereis que eu, o Senhor, o disse.

[[v26-17-22]]

^<<v26-17-22,22>>^ Assim diz o Senhor Jeová : Também eu tomarei o topo do cedro, e o plantarei; do principal dos seus renovos cortarei o mais tenro, e o plantarei sobre um monte alto e sublime.

[[v26-17-23]]

^<<v26-17-23,23>>^ No monte alto de Israel o plantarei, e produzirá ramos, e dará fruto, e se fará um cedro excelente; e habitarão debaixo dele todas as aves de toda a sorte de  asas, e  à sombra dos seus ramos habitarão.

[[v26-17-24]]

^<<v26-17-24,24>>^ Assim saberão todas as árvores do campo que eu, o Senhor, abati a árvore alta, elevei a árvore baixa, sequei a árvore verde, e fiz reverdecer a árvore seca: eu, o Senhor, o disse, e o farei.

'''

xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[&#60; Capítulo Anterior] | <<v26-17-0,Topo>> | xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[Próximo Capítulo &#62;]