include::./index.adoc[]

[[v26-34-0]]
=== Ezequiel, 34
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-34-1]]

^<<v26-34-1,1>>^ E VEIO a mim a palavra do Senhor, dizendo:

[[v26-34-2]]

^<<v26-34-2,2>>^ Filho do homem, profetiza contra os pastores de Israel; profetiza, e dize aos pastores: Assim diz o Senhor Jeová : Ai dos pastores de Israel que se apascentam a si mesmos! Não apascentarão os pastores as ovelhas?

[[v26-34-3]]

^<<v26-34-3,3>>^ Comeis a gordura, e vos vestis da lã; degolais o cevado; mas não apascentais as ovelhas.

[[v26-34-4]]

^<<v26-34-4,4>>^ A fraca não fortalecestes, e a doente não curastes, e a quebrada não ligastes, e a desgarrada não tornastes a trazer, e a perdida não buscastes; mas dominais sobre elas com rigor e dureza.

[[v26-34-5]]

^<<v26-34-5,5>>^ Assim se espalharam, por não haver pastor, e ficaram para pasto de todas as feras do campo, porquanto se espalharam.

[[v26-34-6]]

^<<v26-34-6,6>>^ As minhas ovelhas andam desgarradas por todos os montes, e por todo o alto outeiro; sim, as minhas ovelhas andam espalhadas por toda a face da terra, sem haver quem as procure, nem quem as  busque.

[[v26-34-7]]

^<<v26-34-7,7>>^ Portanto, ó pastores, ouvi a palavra do Senhor:

[[v26-34-8]]

^<<v26-34-8,8>>^ Vivo eu, diz o Senhor Jeová , que visto como as minhas ovelhas foram entregues  à rapina, e as minhas ovelhas vieram a servir de pasto a todas as feras do campo, por falta de pastor, e os meus pastores não procuram as minhas ovelhas, pois se apascentam a si mesmos, e não apascentam as minhas ovelhas;

[[v26-34-9]]

^<<v26-34-9,9>>^ Portanto, ó pastores, ouvi a palavra do Senhor:

[[v26-34-10]]

^<<v26-34-10,10>>^ Assim diz o Senhor Jeová : Eis que eu estou contra os pastores, e demandarei as minhas ovelhas da sua mão, e eles deixarão de apascentar as ovelhas, e não se apascentarão mais a si mesmos; e livrarei as minhas ovelhas da sua boca, e lhes não servirão mais  de pasto.

[[v26-34-11]]

^<<v26-34-11,11>>^ Porque assim diz o Senhor Jeová : Eis que eu, eu mesmo, procurarei as minhas ovelhas, e as buscarei.

[[v26-34-12]]

^<<v26-34-12,12>>^ Como o pastor busca o seu rebanho, no dia em que está no meio das suas ovelhas dispersas, assim buscarei as minhas ovelhas; e as farei voltar de todos os lugares por onde andam espalhadas, no dia da nuvem e da escuridão.

[[v26-34-13]]

^<<v26-34-13,13>>^ E as tirarei dos povos, e as farei vir dos diversos países, e as trarei à sua terra, e as apascentarei nos montes de Israel, junto às correntes, e em todas as habitações da terra.

[[v26-34-14]]

^<<v26-34-14,14>>^ Em bons pastos as apascentarei, e nos altos montes de Israel será a sua malhada; ali se deitarão numa boa malhada, e pastarão em  pastos gordos nos montes de Israel.

[[v26-34-15]]

^<<v26-34-15,15>>^ Eu apascentarei as minhas ovelhas, e eu as farei repousar, diz o Senhor Jeová .

[[v26-34-16]]

^<<v26-34-16,16>>^ A perdida buscarei, e a desgarrada tornarei a trazer, e a quebrada ligarei, e a enferma fortalecerei; mas a gorda e a forte destruirei; apascentá-las-ei com juízo.

[[v26-34-17]]

^<<v26-34-17,17>>^ E quanto a vós, ó ovelhas minhas, assim diz o Senhor Jeová : Eis que eu julgarei entre gado pequeno e gado pequeno, entre carneiros e bodes.

[[v26-34-18]]

^<<v26-34-18,18>>^ Acaso não vos basta pastar o bom pasto, senão que pisais o resto de vossos pastos a vossos pés? e beber as profundas águas, senão que enlameais o resto com os vossos pés?

[[v26-34-19]]

^<<v26-34-19,19>>^ E quanto às minhas ovelhas elas pastam o que foi pisado com os vossos pés, e bebem o que tem sido turvado com os vossos pés.

[[v26-34-20]]

^<<v26-34-20,20>>^ Por isso o Senhor Jeová  assim lhes diz: Eis que eu, eu mesmo, julgarei entre o gado gordo e o gado magro.

[[v26-34-21]]

^<<v26-34-21,21>>^ Visto como com o lado e com o ombro dais empurrões, e com as vossas pontas escorneais todas as fracas, até que as espalhais para fora,

[[v26-34-22]]

^<<v26-34-22,22>>^ Eu livrarei as minhas ovelhas, para que não sirvam mais de rapina, e julgarei entre gado miúdo e gado miúdo.

[[v26-34-23]]

^<<v26-34-23,23>>^ E levantarei sobre elas um só pastor, e ele as apascentará: o meu servo Davi é que as há de apascentar; ele lhes servirá de pastor.

[[v26-34-24]]

^<<v26-34-24,24>>^ E eu, o Senhor, lhes serei por Deus, e o meu servo Davi será príncipe no meio delas: eu, o Senhor, o disse.

[[v26-34-25]]

^<<v26-34-25,25>>^ E farei com elas um concerto de paz, e acabarei com a besta ruim da terra e habitarão no deserto seguramente, e dormirão nos bosques.

[[v26-34-26]]

^<<v26-34-26,26>>^ E a elas, e aos lugares ao redor do meu outeiro, eu porei por  bênção; e farei descer a chuva a seu tempo; chuvas de bênção serão.

[[v26-34-27]]

^<<v26-34-27,27>>^ E as árvores do campo darão o seu fruto, e a terra dará a sua novidade, e estarão seguras na sua terra; e saberão que eu sou  o Senhor, quando eu quebrar as varas do seu jugo e as livrar da mão dos que se serviam delas.

[[v26-34-28]]

^<<v26-34-28,28>>^ E não servirão mais de rapina aos gentios e a besta- fera  da terra nunca mais  as comerá: e habitarão seguramente, e ninguém haverá que as espante.

[[v26-34-29]]

^<<v26-34-29,29>>^ E lhes levantarei uma  plantação de renome, e nunca mais serão consumidas pela fome na terra, nem mais levarão sobre si opróbrio dos gentios.

[[v26-34-30]]

^<<v26-34-30,30>>^ Saberão, porém, que eu, o Senhor seu Deus, estou  com elas, e que  elas são  o meu povo, a casa de Israel, diz o Senhor Jeová .

[[v26-34-31]]

^<<v26-34-31,31>>^ Vós pois, ó ovelhas minhas, ovelhas do meu pasto: homens sois, mas eu sou  o vosso Deus, diz o Senhor Jeová .

'''

xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[&#60; Capítulo Anterior] | <<v26-34-0,Topo>> | xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[Próximo Capítulo &#62;]