include::./index.adoc[]

[[v26-25-0]]
=== Ezequiel, 25
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-25-1]]

^<<v26-25-1,1>>^ E VEIO a mim a palavra do Senhor, dizendo:

[[v26-25-2]]

^<<v26-25-2,2>>^ Filho do homem, dirige o teu rosto contra os filhos de Amom, e profetiza contra eles.

[[v26-25-3]]

^<<v26-25-3,3>>^ E dize aos filhos de Amom: Ouvi a palavra do Senhor Jeová : Assim diz o Senhor Jeová : Visto que tu disseste: Ah! ah! acerca do meu santuário, quando foi profanado; e acerca da terra de Israel, quando foi assolada; e acerca da casa de Judá, quando foi para o cativeiro;

[[v26-25-4]]

^<<v26-25-4,4>>^ Eis que te entregarei em possessão aos do oriente, e estabelecerão os seus paços em ti, e porão em ti as suas moradas; eles comerão os teus frutos, e beberão o teu leite.

[[v26-25-5]]

^<<v26-25-5,5>>^ E farei de Rabá uma  estrebaria de camelos, e dos filhos de Amom um  curral de ovelhas: e sabereis que eu sou  o Senhor.

[[v26-25-6]]

^<<v26-25-6,6>>^ Porque assim diz o Senhor Jeová : Visto como bateste com as mãos, e pateaste com os pés, e te alegraste de coração em toda a tua maldade contra a terra de Israel,

[[v26-25-7]]

^<<v26-25-7,7>>^ Eis que eu estenderei a minha mão contra ti, e te darei por despojo às nações, e te arrancarei dentre os povos, e te destruirei dentre as terras, e acabarei de todo contigo; e saberás que eu sou  o Senhor.

[[v26-25-8]]

^<<v26-25-8,8>>^ Assim diz o Senhor Jeová : Visto como dizem Moabe e  Seir: Eis que a casa de Judá é como todas as nações;

[[v26-25-9]]

^<<v26-25-9,9>>^ Portanto, eis que eu abrirei o lado de Moabe desde as cidades, desde as suas cidades fora das fronteiras, a glória da terra, Bete-Jesimote, Baal-Meom, e até Quiriataim,

[[v26-25-10]]

^<<v26-25-10,10>>^ Até aos filhos do Oriente, à terra dos filhos de Amom, a qual entregarei em possessão, para que não haja memória dos filhos de Amom entre as nações.

[[v26-25-11]]

^<<v26-25-11,11>>^ Também executarei juízos em Moabe, e saberão que eu sou o Senhor.

[[v26-25-12]]

^<<v26-25-12,12>>^ Assim diz o Senhor Jeová : Pois que Edom se houve vingativamente para com a casa de Judá, e se fizeram culpadíssimos, quando se vingaram deles;

[[v26-25-13]]

^<<v26-25-13,13>>^ Portanto assim diz o Senhor Jeová : Também estenderei a minha mão contra Edom, e arrancarei dela homens e animais; e a tornarei em  deserto desde Temã, e até  Dedã cairão à espada.

[[v26-25-14]]

^<<v26-25-14,14>>^ E exercerei a minha vingança sobre Edom, pela mão do meu povo de Israel; e farão em Edom segundo a minha ira e segundo o meu furor; e conhecerão a minha vingança, diz o Senhor Jeová .

[[v26-25-15]]

^<<v26-25-15,15>>^ Assim diz o Senhor Jeová : Visto como os filisteus usaram de vingança, e executaram vingança de coração com malícia, para destruírem com  perpétua inimizade;

[[v26-25-16]]

^<<v26-25-16,16>>^ Portanto assim diz o Senhor Jeová : Eis que eu estendo a minha mão contra os filisteus, e arrancarei os quereteus, e destruirei o resto da costa do mar.

[[v26-25-17]]

^<<v26-25-17,17>>^ E executarei neles grandes vinganças, com castigos de furor, e saberão que eu sou o Senhor, quando eu tiver exercido a minha vingança sobre eles.

'''

xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[&#60; Capítulo Anterior] | <<v26-25-0,Topo>> | xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[Próximo Capítulo &#62;]