include::./index.adoc[]

[[v26-20-0]]
=== Ezequiel, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-20-1]]

^<<v26-20-1,1>>^ E ACONTECEU, no sétimo ano, no mês  quinto, aos dez do mês, que  vieram alguns dos anciãos de Israel, para consultarem o Senhor; e assentaram-se diante de mim.

[[v26-20-2]]

^<<v26-20-2,2>>^ Então veio a mim a palavra do Senhor, dizendo:

[[v26-20-3]]

^<<v26-20-3,3>>^ Filho do homem, fala aos anciãos de Israel, e dize-lhes: Assim diz o Senhor Jeová : Vós vindes consultar-me? vivo eu, que vós não me consultareis, diz o Senhor Jeová .

[[v26-20-4]]

^<<v26-20-4,4>>^ Julgá-los-ias tu, ó filho do homem, julgá-los-ias? faze-lhes saber as abominações de seus pais;

[[v26-20-5]]

^<<v26-20-5,5>>^ E dize-lhes: Assim diz o Senhor Jeová : No dia em que escolhi a Israel, levantei a minha mão para a descendência da casa de Jacó, e me dei a conhecer a eles na terra do Egito, e levantei a minha mão para eles, dizendo: Eu sou  o Senhor vosso Deus.

[[v26-20-6]]

^<<v26-20-6,6>>^ Naquele dia levantei a minha mão para eles, para os tirar da terra do Egito para uma  terra que tinha previsto para eles, a qual mana leite e mel, e é a glória de todas as terras.

[[v26-20-7]]

^<<v26-20-7,7>>^ Então lhes disse: Cada um lance de si as abominações dos seus olhos, e não vos contamineis com os ídolos do Egito: eu sou o Senhor vosso Deus.

[[v26-20-8]]

^<<v26-20-8,8>>^ Mas rebelaram-se contra mim, e não me quiseram ouvir; ninguém lançava de si as abominações dos seus olhos, nem deixava os ídolos do Egito: então eu disse que derramaria sobre eles o meu furor, para cumprir a minha ira contra eles no meio da terra do Egito.

[[v26-20-9]]

^<<v26-20-9,9>>^ O que fiz, porém, foi por amor do meu nome, para que não fosse profanado diante dos olhos das nações, no meio das quais eles estavam, a cujos olhos eu me dei a conhecer a eles, para os tirar da terra do Egito.

[[v26-20-10]]

^<<v26-20-10,10>>^ E os tirei da terra do Egito, e os levei ao deserto.

[[v26-20-11]]

^<<v26-20-11,11>>^ E dei-lhes os meus estatutos, e lhes mostrei os meus juízos, os quais, cumprindo-os o homem, viverá por eles.

[[v26-20-12]]

^<<v26-20-12,12>>^ E também lhes dei os meus sábados, para que servissem de sinal entre mim e eles: para que soubessem que eu sou  o Senhor que os santifica.

[[v26-20-13]]

^<<v26-20-13,13>>^ Mas a casa de Israel se rebelou contra mim no deserto, não andando nos meus estatutos, e rejeitando os meus juízos, os quais, cumprindo-os o homem, viverá por eles; e profanaram grandemente os meus sábados; e eu disse que derramaria sobre eles o meu furor no deserto, para os consumir.

[[v26-20-14]]

^<<v26-20-14,14>>^ O que fiz, porém, foi por amor do meu nome, para que não fosse profanado diante dos olhos das nações perante as quais os fiz sair.

[[v26-20-15]]

^<<v26-20-15,15>>^ E, contudo, eu levantei a minha mão para eles no deserto, para os não deixar entrar na terra que lhes  tinha dado, a qual mana leite e mel, e é a glória de todas as terras;

[[v26-20-16]]

^<<v26-20-16,16>>^ Porque rejeitaram os meus juízos, e não andaram nos meus estatutos, e profanaram os meus sábados; porque o seu coração andava após os seus ídolos.

[[v26-20-17]]

^<<v26-20-17,17>>^ Não obstante o meu olho lhes perdoou, para não os destruir nem os consumir no deserto.

[[v26-20-18]]

^<<v26-20-18,18>>^ Mas disse eu a seus filhos no deserto: Não andeis nos estatutos de vossos pais, nem guardeis os seus juízos, nem vos contamineis com os seus ídolos.

[[v26-20-19]]

^<<v26-20-19,19>>^ Eu sou  o Senhor vosso Deus; andai nos meus estatutos, e guardai os meus juízos, e executai-os.

[[v26-20-20]]

^<<v26-20-20,20>>^ E santificai os meus sábados, e servirão de sinal entre mim e vós, para que saibais que eu sou  o Senhor vosso Deus.

[[v26-20-21]]

^<<v26-20-21,21>>^ Mas também  os filhos se rebelaram contra mim, e não andaram nos meus estatutos, nem guardaram os meus juízos, os quais, cumprindo-os o homem, viverá por eles; eles profanaram os meus sábados, por isso eu disse que derramaria sobre eles o meu furor, para cumprir contra eles a minha ira no deserto.

[[v26-20-22]]

^<<v26-20-22,22>>^ Mas contive a minha mão, e o fiz por amor do meu nome, para que não fosse profanado aos olhos das nações, à vista das quais os fiz sair.

[[v26-20-23]]

^<<v26-20-23,23>>^ Também levantei a minha mão para eles no deserto, para os espalhar entre as nações, e os derramar pelas terras;

[[v26-20-24]]

^<<v26-20-24,24>>^ Porque não executaram os meus juízos, e rejeitaram os meus estatutos, e profanaram os meus sábados, e os seus olhos se iam após os ídolos de seus pais.

[[v26-20-25]]

^<<v26-20-25,25>>^ Pelo que também lhes dei estatutos que  não eram bons, e juízos pelos quais não haviam de viver;

[[v26-20-26]]

^<<v26-20-26,26>>^ E os contaminei em seus próprios dons, nos quais faziam passar pelo fogo  tudo o que abre a madre: para os assolar, para que soubessem que eu sou  o Senhor.

[[v26-20-27]]

^<<v26-20-27,27>>^ Portanto fala à casa de Israel, ó filho do homem, e dize-lhe: Assim diz o Senhor Jeová : Ainda nisto me blasfemaram vossos pais, e transgrediram contra mim.

[[v26-20-28]]

^<<v26-20-28,28>>^ Porque, havendo-os eu introduzido na terra sobre a qual eu levantara a minha mão, para lha dar, então olharam para todo o outeiro alto, e para toda a árvore frondosa, e sacrificaram ali os seus sacrifícios, e apresentaram ali a provocação das suas ofertas, puseram ali os seus cheiros suaves, e ali derramaram as suas libações.

[[v26-20-29]]

^<<v26-20-29,29>>^ E eu lhes disse: Que alto é  este, aonde vós ides? e seu nome tem sido Bamá, até ao dia de hoje.

[[v26-20-30]]

^<<v26-20-30,30>>^ Portanto dize à casa de Israel: Assim diz o Senhor Jeová : Contaminais-vos a vós mesmos, à maneira de vossos pais? e vos prostituís com as suas abominações?

[[v26-20-31]]

^<<v26-20-31,31>>^ E, quando ofereceis os vossos dons, e fazeis passar os vossos filhos pelo fogo, não é certo que estais contaminados com todos os vossos ídolos, até este dia? e vós me consultaríeis, ó casa de Israel? vivo eu, diz o Senhor Jeová , que vós me não consultareis.

[[v26-20-32]]

^<<v26-20-32,32>>^ E o que veio ao vosso espírito de maneira alguma sucederá, quando dizeis: Seremos como as nações, como as outras gerações da terra, servindo ao madeiro e à pedra.

[[v26-20-33]]

^<<v26-20-33,33>>^ Vivo eu, diz o Senhor Jeová , que com mão forte, e com braço estendido, e com indignação derramada, hei de reinar sobre vós,

[[v26-20-34]]

^<<v26-20-34,34>>^ E vos tirarei dentre os povos, e vos congregarei das terras nas quais andais espalhados, com mão forte, e com braço estendido, e com indignação derramada.

[[v26-20-35]]

^<<v26-20-35,35>>^ E vos levarei ao deserto dos povos; e ali entrarei em juízo convosco cara a cara.

[[v26-20-36]]

^<<v26-20-36,36>>^ Como entrei em juízo com vossos pais, no deserto da terra do Egito, assim entrarei em juízo convosco, diz o Senhor Jeová .

[[v26-20-37]]

^<<v26-20-37,37>>^ E vos farei passar debaixo da vara, e vos farei entrar no vínculo do concerto.

[[v26-20-38]]

^<<v26-20-38,38>>^ E separarei dentre vós os rebeldes, e os que prevaricaram contra mim; da terra das suas peregrinações os tirarei, mas à terra de Israel não voltarão: e sabereis que eu sou  o Senhor.

[[v26-20-39]]

^<<v26-20-39,39>>^ Quanto a vós, ó casa de Israel, assim diz o Senhor Jeová : Ide, sirva cada um os seus ídolos, pois que a mim me não quereis ouvir; mas não profaneis mais o meu santo nome com as vossas dádivas e com os vossos ídolos.

[[v26-20-40]]

^<<v26-20-40,40>>^ Porque no meu santo monte, no monte alto de Israel, diz o Senhor Jeová , ali me servirá toda a casa de Israel, toda ela naquela terra: ali me deleitarei neles, e ali demandarei as vossas ofertas alçadas, e as primícias das vossas dádivas, com todas as vossas cousas santas.

[[v26-20-41]]

^<<v26-20-41,41>>^ Com cheiro suave me deleitarei em vós, quando eu vos tirar dentre os povos e vos congregar das terras em que andais espalhados; e serei santificado em vós ante os olhos das nações.

[[v26-20-42]]

^<<v26-20-42,42>>^ E sabereis que eu sou  o Senhor, quando eu vos fizer voltar à terra de Israel, à terra para a qual levantei a minha mão, para a dar a vossos pais.

[[v26-20-43]]

^<<v26-20-43,43>>^ E ali vos lembrareis de vossos caminhos, e de todos os vossos atos com que vos contaminastes, e tereis nojo de vós mesmos, por todas as vossas maldades que tendes cometido.

[[v26-20-44]]

^<<v26-20-44,44>>^ E sabereis que eu sou  o Senhor, quando eu proceder para convosco por amor do meu nome, não conforme os vossos maus caminhos, nem conforme os vossos atos corrutos, ó casa de Israel, disse o Senhor Jeová .

[[v26-20-45]]

^<<v26-20-45,45>>^ E veio a mim a palavra do Senhor, dizendo:

[[v26-20-46]]

^<<v26-20-46,46>>^ Filho do homem, dirige o teu rosto para o caminho do Sul, e derrama as tuas palavras  contra o Sul, e profetiza contra o bosque do campo do Sul.

[[v26-20-47]]

^<<v26-20-47,47>>^ E dize ao bosque do Sul: Ouve a palavra do Senhor: Assim diz o Senhor Jeová : Eis que acenderei em ti um fogo que em ti consumirá toda a árvore verde e toda a árvore seca: não se apagará a chama flamejante, antes com ela se queimarão todos os rostos, desde o sul até ao norte.

[[v26-20-48]]

^<<v26-20-48,48>>^ E verá toda a carne que eu, o Senhor, o acendi: não se apagará.

[[v26-20-49]]

^<<v26-20-49,49>>^ Então disse eu: Ah! Senhor Jeová ! eles dizem de mim: Não é este um dizedor de parábolas?

'''

xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[&#60; Capítulo Anterior] | <<v26-20-0,Topo>> | xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[Próximo Capítulo &#62;]