include::./index.adoc[]

[[v26-36-0]]
=== Ezequiel, 36
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-36-1]]

^<<v26-36-1,1>>^ E TU, ó filho do homem, profetiza aos montes de Israel, e dize: Montes de Israel ouvi a palavra do Senhor.

[[v26-36-2]]

^<<v26-36-2,2>>^ Assim diz o Senhor Jeová : Pois que diz o inimigo sobre vós: Ah! ah! até as eternas alturas serão nossa herança;

[[v26-36-3]]

^<<v26-36-3,3>>^ Portanto, profetiza, e dize: Assim diz o Senhor Jeová : Visto que vos assolaram e devoraram em redor, para que ficásseis feitos herança do resto das nações, e andais arrastados por lábios paroleiros, e pela infâmia do povo.

[[v26-36-4]]

^<<v26-36-4,4>>^ Portanto, ouvi, ó montes de Israel, a palavra do Senhor Jeová : Assim diz o Senhor Jeová  aos montes e aos outeiros, às correntes e aos vales, aos lugares assolados e solitários, e às cidades desamparadas, que se tornaram rapina e escárnio para o resto das nações que estão ao redor delas;

[[v26-36-5]]

^<<v26-36-5,5>>^ Portanto, assim diz o Senhor Jeová : Certamente no fogo do meu zelo falei contra o resto das nações, e contra todo o Edom, que se apropriaram da minha terra, com alegria de todo o coração, e com menosprezo da alma, para ser lançada à rapina;

[[v26-36-6]]

^<<v26-36-6,6>>^ Portanto, profetiza sobre a terra de Israel, e dize aos montes e aos outeiros, às correntes e aos vales: Assim diz o Senhor Jeová : Eis que falei no meu zelo e no meu furor, porque levastes sobre vós o opróbrio dos gentios.

[[v26-36-7]]

^<<v26-36-7,7>>^ Portanto, assim diz o Senhor Jeová : Eu levantei a minha mão, para que os gentios, que estão ao redor de vós, levem o seu opróbrio sobre si mesmos.

[[v26-36-8]]

^<<v26-36-8,8>>^ Mas vós, ó montes de Israel, vós produzireis os vossos ramos, e dareis o vosso fruto para o meu povo de Israel; porque estão prestes a vir.

[[v26-36-9]]

^<<v26-36-9,9>>^ Porque eis que eu estou  convosco; e eu me voltarei para vós, e sereis lavrados e semeados.

[[v26-36-10]]

^<<v26-36-10,10>>^ E multiplicarei homens sobre vós, a toda a casa de Israel, a toda ela: e as cidades serão habitadas, e os lugares devastados serão edificados.

[[v26-36-11]]

^<<v26-36-11,11>>^ E multiplicarei homens e animais sobre vós, e eles se multiplicarão, e frutificarão: e vos farei habitar como dantes e farei vosso estado melhor que nos vossos princípios; e sabereis que eu sou  o Senhor.

[[v26-36-12]]

^<<v26-36-12,12>>^ E farei andar sobre vós os homens, o meu povo de Israel: eles te possuirão, e serás a sua herança, e nunca mais os desfilharás.

[[v26-36-13]]

^<<v26-36-13,13>>^ Assim diz o Senhor Jeová : Visto como vos dizem: Tu és uma terra  que devora os homens, e és uma terra  que desfilha os seus povos;

[[v26-36-14]]

^<<v26-36-14,14>>^ Por isso tu não devorarás mais os homens, nem desfilharás mais os teus povos, diz o Senhor Jeová .

[[v26-36-15]]

^<<v26-36-15,15>>^ E farei que nunca mais se ouça em ti a afronta dos gentios; e não levarás mais sobre ti o opróbrio das gentes, nem mais desfilharás a tua nação, diz o Senhor Jeová .

[[v26-36-16]]

^<<v26-36-16,16>>^ E veio a mim a palavra do Senhor, dizendo:

[[v26-36-17]]

^<<v26-36-17,17>>^ Filho do homem, quando a casa de Israel habitava na sua terra, então a contaminaram com os seus caminhos e com as suas ações: como a imundícia de uma mulher em sua separação, tal era o seu caminho perante o meu rosto.

[[v26-36-18]]

^<<v26-36-18,18>>^ Derramei pois o meu furor sobre eles, por causa do sangue que derramaram sobre a terra, e dos seus ídolos, com que  a contaminaram.

[[v26-36-19]]

^<<v26-36-19,19>>^ E os espalhei entre as nações, e foram espalhados pelas terras: conforme os seus caminhos e conforme os seus feitos, eu os julguei.

[[v26-36-20]]

^<<v26-36-20,20>>^ E, chegando às nações para onde foram, profanaram o meu santo nome, pois se dizia deles: Estes: são  o povo do Senhor, e saíram da sua terra.

[[v26-36-21]]

^<<v26-36-21,21>>^ Mas eu os poupei por amor do meu santo nome, que a casa de Israel profanou entre as nações para onde foi.

[[v26-36-22]]

^<<v26-36-22,22>>^ Dize portanto à casa de Israel: Assim diz o Senhor Jeová : Não é por vosso respeito que eu faço isto, ó casa de Israel, mas pelo meu santo nome, que profanaste entre as nações para onde vós fostes.

[[v26-36-23]]

^<<v26-36-23,23>>^ E eu santificarei o meu grande nome, que foi profanado entre as nações, o qual profanastes no meio delas; e as nações saberão que eu sou  o Senhor, diz o Senhor Jeová , quando eu for santificado aos seus olhos.

[[v26-36-24]]

^<<v26-36-24,24>>^ E vos tomarei dentre as nações, e vos congregarei de todos os países, e vos trarei para a vossa terra.

[[v26-36-25]]

^<<v26-36-25,25>>^ Então espalharei água pura sobre vós, e ficareis purificados: de todas as vossas imundícias e de todos os vossos ídolos vos purificarei.

[[v26-36-26]]

^<<v26-36-26,26>>^ E vos darei um coração novo, e porei dentro de vós um espírito novo; e tirarei o coração de pedra da vossa carne, e vos darei um coração de carne.

[[v26-36-27]]

^<<v26-36-27,27>>^ E porei dentro de vós o meu espírito, e farei que andeis nos meus estatutos, e guardeis os meus juízos, e os observeis.

[[v26-36-28]]

^<<v26-36-28,28>>^ E habitareis na terra que eu dei a vossos pais, e vós me sereis por povo, e eu vos serei por Senhor.

[[v26-36-29]]

^<<v26-36-29,29>>^ E vos livrarei de todas as vossas imundícias; e chamarei o trigo, e o multiplicarei, e não trarei fome sobre vós.

[[v26-36-30]]

^<<v26-36-30,30>>^ E multiplicarei o fruto das árvores, e a novidade do campo, para que nunca mais recebais o opróbrio da fome entre as nações.

[[v26-36-31]]

^<<v26-36-31,31>>^ Então vos lembrareis dos vossos maus caminhos, e dos vossos feitos, que não foram  bons: e tereis nojo em vós mesmos das vossas maldades e das vossas abominações.

[[v26-36-32]]

^<<v26-36-32,32>>^ Não é por amor de vós que eu faço isto, diz o Senhor Jeová ; notório vos seja: envergonhai-vos, e confundi-vos pelos vossos caminhos, ó casa de Israel.

[[v26-36-33]]

^<<v26-36-33,33>>^ Assim diz o Senhor Jeová : No dia em que eu vos purificar de todas as vossas maldades, então farei com que sejam habitadas as cidades e sejam edificados os lugares devastados.

[[v26-36-34]]

^<<v26-36-34,34>>^ E a terra assolada se lavrará, em vez de estar assolada aos olhos de todos os que passavam.

[[v26-36-35]]

^<<v26-36-35,35>>^ E dirão: Esta terra assolada ficou como jardim do Éden; e as cidades solitárias, e assoladas, e destruídas, estão fortalecidas e  habitadas.

[[v26-36-36]]

^<<v26-36-36,36>>^ Então saberão as nações, que ficarem de resto em redor de vós, que eu, o Senhor, tenho reedificado as cidades  destruídas, e  plantado o  que estava devastado: eu, o Senhor, o disse, e o farei.

[[v26-36-37]]

^<<v26-36-37,37>>^ Assim diz o Senhor Jeová : Ainda por isso me pedirá a casa de Israel, que lho faça: multiplicar-lhes-ei os homens, como a um rebanho.

[[v26-36-38]]

^<<v26-36-38,38>>^ Como o rebanho santificado, como o rebanho de Jerusalém nas suas solenidades, assim as cidades, desertas se encherão de famílias; e saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[&#60; Capítulo Anterior] | <<v26-36-0,Topo>> | xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[Próximo Capítulo &#62;]