include::./index.adoc[]

[[v26-40-0]]
=== Ezequiel, 40
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-40-1]]

^<<v26-40-1,1>>^ NO ano vinte e cinco do nosso cativeiro, no princípio do ano, no décimo dia  do mês, catorze anos depois que a cidade foi ferida, naquele mesmo dia veio sobre mim a mão do Senhor, e me levou para lá.

[[v26-40-2]]

^<<v26-40-2,2>>^ Em visões de Deus me levou à terra de Israel e me pôs sobre um  monte muito alto, e havia  sobre ele um como edifício de cidade para a banda do sul.

[[v26-40-3]]

^<<v26-40-3,3>>^ E, havendo-me levado ali, eis que um homem cuja aparência era  como a aparência do cobre, tendo um cordel de linho na sua mão e uma cana de medir, estava em pé na porta.

[[v26-40-4]]

^<<v26-40-4,4>>^ E disse-me o homem: Filho do homem, vê com os teus olhos, e ouve com os teus ouvidos, e põe no teu coração tudo quanto eu te fizer ver; porque, para t o  mostrar foste tu aqui trazido; anuncia pois  à casa de Israel tudo quanto tu vires.

[[v26-40-5]]

^<<v26-40-5,5>>^ E havia um muro fora da casa em redor, e na mão do homem uma  cana de medir, de seis côvados, dum côvado e um palmo cada um, e mediu a largura do edifício, uma cana, e a altura, uma cana.

[[v26-40-6]]

^<<v26-40-6,6>>^ Então veio à porta que olhava para o caminho do oriente, e subiu pelos seus degraus; mediu o umbral da porta, uma cana de largo, e o outro umbral, uma cana de largo.

[[v26-40-7]]

^<<v26-40-7,7>>^ E cada  câmara tinha uma cana de comprido, e uma cana de largo, e entre as câmaras havia  cinco côvados; e o umbral da porta, ao pé do vestíbulo da porta, tinha uma cana, por dentro.

[[v26-40-8]]

^<<v26-40-8,8>>^ Também mediu o vestíbulo da porta por dentro, uma cana.

[[v26-40-9]]

^<<v26-40-9,9>>^ Então mediu o outro  alpendre da porta, que tinha oito côvados, e os seus pilares, dois côvados, e o vestíbulo da porta, por dentro.

[[v26-40-10]]

^<<v26-40-10,10>>^ E as câmaras da porta para o lado do oriente eram  três deste lado, e três do outro, uma mesma medida era  a das três: também os pilares deste lado e do outro tinham  a mesma medida.

[[v26-40-11]]

^<<v26-40-11,11>>^ Mediu mais a largura da entrada da porta, que era de dez côvados; e  o comprimento da porta, treze côvados.

[[v26-40-12]]

^<<v26-40-12,12>>^ E o espaço em frente das câmaras era  de um côvado, e de um côvado o espaço da outra banda: e cada  câmara tinha  seis côvados dum lado, e seis côvados do outro.

[[v26-40-13]]

^<<v26-40-13,13>>^ Então mediu a porta desde o telhado duma câmara até ao telhado da outra, vinte e cinco côvados de largo, porta contra porta.

[[v26-40-14]]

^<<v26-40-14,14>>^ Também fez pilares de sessenta côvados, e o átrio até ao pilar em roda da porta.

[[v26-40-15]]

^<<v26-40-15,15>>^ E, desde a dianteira da porta da entrada até à dianteira do vestíbulo da porta interior, havia  cinquenta côvados.

[[v26-40-16]]

^<<v26-40-16,16>>^ Fez  também nas câmaras janelas de fechar e nos seus pilares, dentro da porta ao redor, e da mesma sorte nos vestíbulos: e as janelas estavam à roda pela parte de dentro, e nos pilares havia  palmeiras.

[[v26-40-17]]

^<<v26-40-17,17>>^ E ele me levou ao átrio exterior; e eis que havia  nele câmaras, e um solhado que estava  feito no átrio em redor: trinta câmaras havia  naquele solhado.

[[v26-40-18]]

^<<v26-40-18,18>>^ E o solhado da banda das portas era  a par do comprimento das portas: o solhado estava mais baixo.

[[v26-40-19]]

^<<v26-40-19,19>>^ E mediu a largura da dianteira do átrio interior, por fora, cem côvados, da banda do oriente e do norte.

[[v26-40-20]]

^<<v26-40-20,20>>^ E, quanto à porta que olhava para o caminho do norte, no átrio exterior, ele mediu o seu comprimento e a sua largura.

[[v26-40-21]]

^<<v26-40-21,21>>^ E as suas câmaras, três duma banda, e três da outra, e os seus pilares e os seus vestíbulos eram da medida da primeira porta: de cinquenta côvados era o seu comprimento, e a largura de vinte e cinco côvados.

[[v26-40-22]]

^<<v26-40-22,22>>^ E as suas janelas, e os seus vestíbulos, e as suas palmeiras eram da medida da porta que olhava para o caminho do oriente; e subia-se para ela por sete degraus, e o seu vestíbulo estava diante dela.

[[v26-40-23]]

^<<v26-40-23,23>>^ E estava  a porta do átrio interior defronte da porta do norte e do oriente; e mediu de porta a porta cem côvados.

[[v26-40-24]]

^<<v26-40-24,24>>^ Então ele me levou ao caminho do sul, e eis que havia ali uma porta que olhava para o caminho do sul, e mediu os seus pilares e os seus vestíbulos conforme estas medidas.

[[v26-40-25]]

^<<v26-40-25,25>>^ E havia também janelas em redor dos seus vestíbulos, como as outras janelas: cinquenta côvados o comprimento, e a largura vinte e cinco côvados.

[[v26-40-26]]

^<<v26-40-26,26>>^ E de sete degraus eram  as suas subidas, e os seus vestíbulos estavam diante deles; e tinha palmeiras, uma duma banda e outra da outra, nos seus pilares.

[[v26-40-27]]

^<<v26-40-27,27>>^ Também havia  uma porta no átrio interior para o caminho do sul; e mediu de porta a porta, para o caminho do sul, cem côvados.

[[v26-40-28]]

^<<v26-40-28,28>>^ Então me levou ao átrio interior pela porta do sul; e mediu a porta do sul, conforme estas medidas.

[[v26-40-29]]

^<<v26-40-29,29>>^ E as suas câmaras, e os seus pilares, e os seus vestíbulos eram  conforme estas medidas; e tinham também janelas ao redor dos seus vestíbulos: o comprimento era  de cinquenta côvados, e a largura de vinte e cinco côvados.

[[v26-40-30]]

^<<v26-40-30,30>>^ E havia  vestíbulos em redor: o comprimento era  de vinte e cinco côvados, e a largura de cinco côvados.

[[v26-40-31]]

^<<v26-40-31,31>>^ E os seus vestíbulos estavam  na direção do átrio exterior, e havia palmeiras nos seus pilares; e de oito degraus eram  as suas subidas.

[[v26-40-32]]

^<<v26-40-32,32>>^ Depois me levou ao átrio interior, para o caminho do oriente, e mediu a porta conforme estas medidas;

[[v26-40-33]]

^<<v26-40-33,33>>^ E também as suas câmaras, e os seus pilares e os seus vestíbulos, conforme estas medidas; e havia também janelas em redor dos seus vestíbulos: o comprimento de cinquenta côvados, e a largura de vinte e cinco côvados.

[[v26-40-34]]

^<<v26-40-34,34>>^ E os seus vestíbulos estavam  no átrio de fora: também havia  palmas nos seus pilares de uma e de outra banda; e eram  as suas subidas de oito degraus.

[[v26-40-35]]

^<<v26-40-35,35>>^ Então me levou à porta do norte, e mediu conforme estas medidas;

[[v26-40-36]]

^<<v26-40-36,36>>^ As suas camarinhas, os seus pilares, e os seus vestíbulos; também tinha janelas em redor; o comprimento era  de cinquenta côvados, e a largura de vinte e cinco côvados.

[[v26-40-37]]

^<<v26-40-37,37>>^ E os seus pilares estavam  no átrio exterior: também havia  palmeiras nos seus pilares de uma e de outra banda; e eram  as suas subidas de oito degraus.

[[v26-40-38]]

^<<v26-40-38,38>>^ E a sua câmara e a sua porta estavam  junto aos pilares das portas onde lavavam o holocausto.

[[v26-40-39]]

^<<v26-40-39,39>>^ E no vestíbulo da porta havia  duas mesas de uma banda, e duas mesas da outra, para nelas se degolar o holocausto e o sacrifício pelo pecado e pela culpa.

[[v26-40-40]]

^<<v26-40-40,40>>^ Também da banda de fora da subida para a entrada da porta do norte havia  duas mesas; e da outra banda, que estava  no vestíbulo da porta, havia  duas mesas.

[[v26-40-41]]

^<<v26-40-41,41>>^ Quatro mesas de uma, e quatro mesas da outra banda; aos lados da porta oito mesas, sobre as quais imolavam.

[[v26-40-42]]

^<<v26-40-42,42>>^ E as quatro mesas para o holocausto eram  de pedras lavradas: o comprimento era de um côvado e meio, e a largura de um côvado e meio, e a altura de um côvado: e sobre elas se punham os instrumentos com que imolavam o holocausto e o sacrifício.

[[v26-40-43]]

^<<v26-40-43,43>>^ E as suas bordas eram de um palmo, pela casa em redor, e sobre as mesas estava a carne da oferta.

[[v26-40-44]]

^<<v26-40-44,44>>^ E fora da porta interior estavam  as câmaras dos cantores, no átrio de dentro, que estava  da banda da porta do norte e olhava para o caminho do sul: uma estava  à banda da porta do oriente, a qual  olhava para o caminho do norte.

[[v26-40-45]]

^<<v26-40-45,45>>^ E ele me disse: Esta câmara que olha para o caminho do sul é  para os sacerdotes que têm a guarda do templo.

[[v26-40-46]]

^<<v26-40-46,46>>^ Mas a câmara que olha para o caminho do norte é  para os sacerdotes que têm a guarda do altar: estes são  os filhos de Zadoque, que se chegam ao Senhor, dentre os filhos de Levi, para o servir.

[[v26-40-47]]

^<<v26-40-47,47>>^ E mediu o átrio: o comprimento de cem côvados e a largura de cem côvados, um quadrado; e o altar estava  diante do templo.

[[v26-40-48]]

^<<v26-40-48,48>>^ Então me levou ao vestíbulo do templo, e mediu cada  pilar do vestíbulo, cinco côvados de uma banda, e cinco côvados da outra; e a largura da porta, três côvados de uma banda, e três côvados da outra.

[[v26-40-49]]

^<<v26-40-49,49>>^ O comprimento do vestíbulo era de vinte côvados, e a largura de onze côvados, e era por degraus, que se subia; e havia  colunas junto aos pilares, uma de uma banda e outra da outra.

'''

xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[&#60; Capítulo Anterior] | <<v26-40-0,Topo>> | xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[Próximo Capítulo &#62;]