include::./index.adoc[]

[[v26-32-0]]
=== Ezequiel, 32
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-32-1]]

^<<v26-32-1,1>>^ E SUCEDEU que, no ano duodécimo, no mês duodécimo, ao primeiro do mês, veio a mim a palavra do Senhor, dizendo:

[[v26-32-2]]

^<<v26-32-2,2>>^ Filho do homem, levanta uma  lamentação sobre Faraó, rei do Egito, e dize-lhe: Semelhante eras a um  filho de leão entre  as nações, e tu foste  como um  dragão nos mares, e ferias os teus rios, e turbavas as águas com os teus pés, e sujavas os teus rios.

[[v26-32-3]]

^<<v26-32-3,3>>^ Assim diz o Senhor Jeová : Portanto, estenderei sobre ti a minha rede com ajuntamento de muitos povos, e te farão subir na minha rede.

[[v26-32-4]]

^<<v26-32-4,4>>^ Então te deixarei em terra; sobre a face do campo te lançarei, e farei morar sobre ti todas as aves do céu; e se fartarão de ti os animais de toda a terra.

[[v26-32-5]]

^<<v26-32-5,5>>^ E porei as tuas carnes sobre os montes, e encherei os vales da tua altura.

[[v26-32-6]]

^<<v26-32-6,6>>^ E a terra onde nadas regarei com o teu sangue até aos montes, e as correntes se encherão de ti.

[[v26-32-7]]

^<<v26-32-7,7>>^ E, apagando-te eu, cobrirei os céus, e enegrecerei as suas estrelas: ao sol encobrirei com uma  nuvem, e a lua não deixará resplandecer a sua luz.

[[v26-32-8]]

^<<v26-32-8,8>>^ Todas as brilhantes luzes do céu enegrecerei sobre ti, e trarei trevas sobre a tua terra, diz o Senhor Jeová .

[[v26-32-9]]

^<<v26-32-9,9>>^ E afligirei o coração de muitos povos, quando eu levar a tua destruição entre as nações, às terras que não conheceste.

[[v26-32-10]]

^<<v26-32-10,10>>^ E farei com que muitos povos, fiquem pasmados a teu respeito, e os seus reis tremam em grande maneira, quando eu brandir a minha espada ante os seus rostos; e estremecerão a cada momento, cada um pela sua vida, no dia da tua queda.

[[v26-32-11]]

^<<v26-32-11,11>>^ Porque assim diz o Senhor Jeová : A espada do rei de Babilônia virá sobre ti.

[[v26-32-12]]

^<<v26-32-12,12>>^ Farei cair a tua multidão com as espadas dos valentes, que são  todos os mais terríveis das gentes; e eles destruirão a soberba do Egito, e toda a sua multidão será perdida.

[[v26-32-13]]

^<<v26-32-13,13>>^ E exterminarei todos os seus animais sobre as muitas águas; nem as turbará mais pé de homem, nem as turbarão unhas de animais.

[[v26-32-14]]

^<<v26-32-14,14>>^ Então farei assentar as suas águas, e farei correr os seus rios como o azeite, diz o Senhor Jeová .

[[v26-32-15]]

^<<v26-32-15,15>>^ Quando eu tornar a terra do Egito em  assolação, e a terra for assolada em sua plenitude, e quando ferir a todos os que nela habitam, então saberão que eu sou  o Senhor.

[[v26-32-16]]

^<<v26-32-16,16>>^ Esta é a lamentação com que lamentarão; as filhas das nações o lamentarão; sobre o Egito e sobre toda a sua multidão assim  se lamentará, diz o Senhor Jeová .

[[v26-32-17]]

^<<v26-32-17,17>>^ E sucedeu que, no ano duodécimo, aos quinze do mês, veio a mim a palavra do Senhor, dizendo:

[[v26-32-18]]

^<<v26-32-18,18>>^ Filho do homem, pranteia sobre a multidão do Egito, e faze-a descer, a ela e às filhas das nações magníficas, à terra mais baixa, aos que descem à cova.

[[v26-32-19]]

^<<v26-32-19,19>>^ A quem sobrepujas tu em beleza? Desce, e deita-te com os incircuncisos.

[[v26-32-20]]

^<<v26-32-20,20>>^ No meio daqueles que foram  traspassados à espada eles cairão; à espada ela está entregue; arrastai-a e a toda a sua multidão.

[[v26-32-21]]

^<<v26-32-21,21>>^ Os mais poderosos dos valentes lhe falarão desde o meio do inferno, com os que a socorrem: desceram, e estão, entre os incircuncisos, traspassados à espada.

[[v26-32-22]]

^<<v26-32-22,22>>^ Ali está Assur com todo o seu ajuntamento; em redor dele estão  os seus sepulcros; todos eles foram traspassados e caíram à espada.

[[v26-32-23]]

^<<v26-32-23,23>>^ Os seus sepulcros foram postos no mais interior da cova, e o seu ajuntamento está em redor do seu sepulcro: todos foram traspassados, e caíram à espada, os que tinham causado espanto na terra dos viventes.

[[v26-32-24]]

^<<v26-32-24,24>>^ Ali está Elã com toda a sua multidão em redor do seu sepulcro: todos eles foram  traspassados, e caíram à espada; eles desceram incircuncisos às mais baixas partes da terra; causaram terror na terra dos viventes, e levaram a sua vergonha com os que desceram à cova.

[[v26-32-25]]

^<<v26-32-25,25>>^ No meio dos traspassados lhe puseram uma  cama entre toda a sua multidão; ao redor dele estão  os seus sepulcros: todos eles são  incircuncisos, traspassados à espada; porque causaram terror na terra dos viventes, e levaram a sua vergonha com os que desceram à cova; no meio dos traspassados foi posto.

[[v26-32-26]]

^<<v26-32-26,26>>^ Ali está Meseque e  Tubal com toda a sua multidão; ao redor deles estão  os seus sepulcros: todos eles são incircuncisos, e  traspassados à espada, porquanto causaram terror na terra dos viventes.

[[v26-32-27]]

^<<v26-32-27,27>>^ E não se acharão com os valentes que caíram dos incircuncisos, os quais desceram ao sepulcro com as suas armas de guerra e puseram as suas espadas debaixo das suas cabeças, e a sua iniquidade está sobre os seus ossos, porque eram o terror dos heróis na terra dos viventes.

[[v26-32-28]]

^<<v26-32-28,28>>^ Também tu serás quebrado no meio dos incircuncisos, e jazerás com os que foram  traspassados à espada.

[[v26-32-29]]

^<<v26-32-29,29>>^ Ali está  Edom, os seus reis e todos os seus príncipes, que no seu poder foram postos com os que foram  traspassados à espada: estes jazem com os incircuncisos e com os que desceram à cova.

[[v26-32-30]]

^<<v26-32-30,30>>^ Ali estão  os príncipes do norte, todos eles, e todos os sidônios, que desceram com os traspassados, envergonhados com o terror causado pelo seu poder; e jazem incircuncisos com os que foram  traspassados à espada, e levam a sua vergonha com os que desceram à cova.

[[v26-32-31]]

^<<v26-32-31,31>>^ Faraó os verá, e se consolará com toda a sua multidão; sim, o próprio Faraó, e todo o seu exército, traspassados à espada, diz o Senhor Jeová .

[[v26-32-32]]

^<<v26-32-32,32>>^ Porque também  eu pus o meu espanto na terra dos viventes; pelo que jazerá no meio dos incircuncisos, com os traspassados à espada, Faraó e toda a sua multidão, diz o Senhor Jeová .

'''

xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[&#60; Capítulo Anterior] | <<v26-32-0,Topo>> | xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[Próximo Capítulo &#62;]