include::./index.adoc[]

[[v26-38-0]]
=== Ezequiel, 38
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-38-1]]

^<<v26-38-1,1>>^ VEIO mais a mim a palavra do Senhor, dizendo:

[[v26-38-2]]

^<<v26-38-2,2>>^ Filho do homem, dirige o teu rosto contra Gogue, terra de Magogue, príncipe e chefe de Meseque e de Tubal, e profetiza contra ele.

[[v26-38-3]]

^<<v26-38-3,3>>^ E dize: Assim diz o Senhor Jeová : Eis que eu sou contra ti, ó Gogue, príncipe e  chefe de Meseque e de Tubal;

[[v26-38-4]]

^<<v26-38-4,4>>^ E te farei voltar, e porei anzóis nos teus queixos, e te levarei a ti, com todo o teu exército, cavalos e cavaleiros todos vestidos bizarramente, congregação grande, com  escudo e rodela, manejando todos a espada:

[[v26-38-5]]

^<<v26-38-5,5>>^ Persas, etíopes, e os de Pute com eles, todos com  escudo e capacete;

[[v26-38-6]]

^<<v26-38-6,6>>^ Gômer e todas as suas tropas; a casa de Togarma, da  banda do norte, e todas as suas tropas, muitos povos contigo.

[[v26-38-7]]

^<<v26-38-7,7>>^ Prepara-te, sim, dispõe-te, tu e todas as tuas congregações que se reuniram a ti, e serve-lhes tu de guarda.

[[v26-38-8]]

^<<v26-38-8,8>>^ Depois de muitos dias serás visitado: no fim dos anos virás à terra que se retirou da espada, e que  veio dentre muitos povos aos montes de Israel, que sempre serviram de assolação; mas aquela terra  foi tirada dentre os povos, e todos eles habitarão seguramente.

[[v26-38-9]]

^<<v26-38-9,9>>^ Então subirás, virás como uma tempestade, far-te-ás como uma nuvem para cobrir a terra, tu e todas as tuas tropas, e muitos povos contigo.

[[v26-38-10]]

^<<v26-38-10,10>>^ Assim diz o Senhor Jeová : E acontecerá naquele dia que  terás imaginações no teu coração, e conceberás um mau desígnio.

[[v26-38-11]]

^<<v26-38-11,11>>^ E dirás: Subirei contra a terra das aldeias não muradas, virei contra os que estão em repouso, que habitam seguros; todos eles habitam sem muro, e não têm ferrolho nem portas;

[[v26-38-12]]

^<<v26-38-12,12>>^ A fim de tomar o despojo, e de arrebatar a presa, e tornar a tua mão contra as terras desertas que agora  se habitam, e contra o povo, que se ajuntou dentre as nações, o qual tem gado e possessões, e habita no meio da terra.

[[v26-38-13]]

^<<v26-38-13,13>>^ Seba, e Dedã, e os mercadores de Tarsis, e todos os seus leõezinhos te dirão: Vens tu para tomar o despojo? ajuntaste o teu bando para arrebatar a presa? para levar a prata e o ouro para tomar o gado e as possessões, para saquear grande despojo?

[[v26-38-14]]

^<<v26-38-14,14>>^ Portanto, profetiza, ó filho do homem, e dize a Gogue: Assim diz o Senhor Jeová : Não o saberás naquele dia, quando o meu povo Israel habitar com segurança?

[[v26-38-15]]

^<<v26-38-15,15>>^ Virás pois do teu lugar, das bandas do norte, tu e muitos povos contigo, montados todos a cavalo, grande ajuntamento, e exército numeroso;

[[v26-38-16]]

^<<v26-38-16,16>>^ E subirás contra o meu povo Israel, como uma nuvem, para cobrir a terra: no fim dos dias sucederá que hei de trazer-te contra a minha terra, para que as nações me conheçam a mim, quando eu me houver santificado em ti aos seus olhos, ó Gogue.

[[v26-38-17]]

^<<v26-38-17,17>>^ Assim diz o Senhor Jeová : Não és  tu aquele de quem eu disse nos dias antigos, pelo ministério de meus servos, os profetas de Israel, os quais naqueles dias profetizaram largos  anos, que te traria contra eles?

[[v26-38-18]]

^<<v26-38-18,18>>^ Sucederá, porém, naquele dia, no dia em que  vier Gogue contra a terra de Israel, diz o Senhor Jeová , que a minha indignação subirá a meus narizes.

[[v26-38-19]]

^<<v26-38-19,19>>^ Porque disse no meu zelo, no fogo do meu furor, que naquele dia haverá grande tremor sobre a terra de Israel;

[[v26-38-20]]

^<<v26-38-20,20>>^ De tal sorte que tremerão diante da minha face os peixes do mar, e as aves do céu, e os animais do campo, e todos os répteis que se arrastam sobre a terra, e todos os homens que estão  sobre a face da terra; e os montes cairão, e os precipícios se desfarão, e todos os muros desabarão por terra.

[[v26-38-21]]

^<<v26-38-21,21>>^ Porque chamarei contra ele a espada, sobre todos os meus montes, diz o Senhor Jeová : a espada de cada um se voltará contra seu irmão.

[[v26-38-22]]

^<<v26-38-22,22>>^ E contenderei com ele por meio da peste e do sangue; e uma  chuva inundante, e grandes pedras de saraiva, fogo e enxofre farei cair sobre ele, e sobre as suas tropas, e sobre os muitos povos que estiverem  com ele.

[[v26-38-23]]

^<<v26-38-23,23>>^ Assim eu me engrandecerei e me santificarei, e me farei conhecer aos olhos de muitas nações; e saberão que eu sou  o Senhor.

'''

xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[&#60; Capítulo Anterior] | <<v26-38-0,Topo>> | xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[Próximo Capítulo &#62;]