include::./index.adoc[]

[[v26-28-0]]
=== Ezequiel, 28
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-28-1]]

^<<v26-28-1,1>>^ E VEIO a mim a palavra do Senhor, dizendo:

[[v26-28-2]]

^<<v26-28-2,2>>^ Filho do homem, dize ao príncipe de Tiro: Assim diz o Senhor Jeová : Visto como se eleva o teu coração, e dizes: Eu sou  Deus, sobre a cadeira de Deus me assento no meio dos mares (sendo  tu homem, e não Deus), e estimas o teu coração como se fora  o coração de Deus;

[[v26-28-3]]

^<<v26-28-3,3>>^ Eis que mais sábio és  que Daniel: não há segredo algum que se possa esconder de ti.

[[v26-28-4]]

^<<v26-28-4,4>>^ Pela tua sabedoria e pelo teu entendimento alcançaste o teu poder, e adquiriste ouro e prata nos teus tesouros.

[[v26-28-5]]

^<<v26-28-5,5>>^ Pela extensão da tua sabedoria no teu comércio aumentaste o teu poder; e eleva-se o teu coração por causa do teu poder;

[[v26-28-6]]

^<<v26-28-6,6>>^ Portanto, assim diz o Senhor Jeová : Pois que estimas o teu coração, como se fora  o coração de Deus.

[[v26-28-7]]

^<<v26-28-7,7>>^ Eis que eu trarei sobre ti estranhos, os mais formidáveis dentre as nações, os quais desembainharão as suas espadas, contra a formosura da tua sabedoria, e mancharão o teu resplendor.

[[v26-28-8]]

^<<v26-28-8,8>>^ À cova te farão descer, e morrerás da morte dos traspassados no meio dos mares.

[[v26-28-9]]

^<<v26-28-9,9>>^ Dirás ainda diante daquele que te matar: Eu sou Deus? mas tu és homem, e não Deus, na mão do que te traspassa.

[[v26-28-10]]

^<<v26-28-10,10>>^ Da morte dos incircuncisos morrerás, por mãos dos estranhos; porque eu o  falei, diz o Senhor Jeová .

[[v26-28-11]]

^<<v26-28-11,11>>^ Veio mais a mim a palavra do Senhor, dizendo:

[[v26-28-12]]

^<<v26-28-12,12>>^ Filho do homem, levanta uma  lamentação sobre o rei de Tiro, e dize-lhe: Assim diz o Senhor Jeová : Tu és  o aferidor da medida, cheio de sabedoria e perfeito em  formosura.

[[v26-28-13]]

^<<v26-28-13,13>>^ Estavas no Éden, jardim de Deus: toda a pedra preciosa era  a tua cobertura, a sardônia, o topázio, o diamante, a turquesa, o ônix, o jaspe, a safira, o carbúnculo, a esmeralda e o ouro: a obra dos teus tambores e dos teus pífaros estava  em ti; no dia em que foste criado foram preparados.

[[v26-28-14]]

^<<v26-28-14,14>>^ Tu eras  querubim ungido para proteger, e te estabeleci: no monte santo de Deus estavas, no meio das pedras afogueadas andavas.

[[v26-28-15]]

^<<v26-28-15,15>>^ Perfeito eras  nos teus caminhos, desde o dia em que foste criado, até que se achou iniquidade em ti.

[[v26-28-16]]

^<<v26-28-16,16>>^ Na multiplicação do teu comércio se encheu o teu interior de violência, e pecaste; pelo que te lançarei profanado fora do monte de Deus, e te farei perecer, ó querubim protetor, entre pedras afogueadas.

[[v26-28-17]]

^<<v26-28-17,17>>^ Elevou-se o teu coração por causa da tua formosura, corrompeste a tua sabedoria por causa do teu resplendor; por terra te lancei, diante dos reis te pus, para que olhem para ti.

[[v26-28-18]]

^<<v26-28-18,18>>^ Pela multidão das tuas iniquidades, pela injustiça do teu comércio profanaste os teus santuários: eu pois fiz sair do meio de ti um  fogo, que te consumiu a ti, e te tornei em cinza sobre a terra, aos olhos de todos os que te veem.

[[v26-28-19]]

^<<v26-28-19,19>>^ Todos os que te conhecem entre os povos estão espantados de ti: em  grande espanto te tornaste, e nunca mais  serás para sempre.

[[v26-28-20]]

^<<v26-28-20,20>>^ E veio a mim a palavra do Senhor, dizendo:

[[v26-28-21]]

^<<v26-28-21,21>>^ Filho do homem, dirige o teu rosto contra Sidom, e profetiza contra ela,

[[v26-28-22]]

^<<v26-28-22,22>>^ E dize: Assim diz o Senhor Jeová : Eis-me contra ti, ó Sidom, e serei glorificado no meio de ti; e saberão que eu sou  o Senhor, quando nela executar juízos e nela me santificar.

[[v26-28-23]]

^<<v26-28-23,23>>^ Porque enviarei contra ela a peste, e o sangue nas suas ruas, e os traspassados cairão no meio dela, estando  a espada em roda contra ela; e saberão que eu sou  o Senhor.

[[v26-28-24]]

^<<v26-28-24,24>>^ E a casa de Israel nunca mais terá espinho que a pique, nem espinho que cause dor, de qualquer que ao redor deles os roubam e saberão que eu sou  o Senhor Jeová .

[[v26-28-25]]

^<<v26-28-25,25>>^ Assim diz o Senhor Jeová : Quando eu congregar a casa de Israel dentre os povos entre os quais estão espalhados, e eu me santificar entre eles, perante os olhos das nações, então habitarão na sua terra que dei a meu servo, a Jacó.

[[v26-28-26]]

^<<v26-28-26,26>>^ E habitarão nela seguros e edificarão casas, e plantarão vinhas; sim, habitarão seguros, quando eu executar juízos contra todos os que roubam nos seus contornos; e saberão que eu sou  o Senhor seu Deus.

'''

xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]