include::./index.adoc[]

[[v26-27-0]]
=== Ezequiel, 27
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-27-1]]

^<<v26-27-1,1>>^ E VEIO a mim a palavra do Senhor, dizendo:

[[v26-27-2]]

^<<v26-27-2,2>>^ Tu pois, ó filho do homem, levanta uma  lamentação sobre Tiro.

[[v26-27-3]]

^<<v26-27-3,3>>^ E dize a Tiro, que habita nas estradas do mar, e negocia com os povos em muitas ilhas: Assim diz o Senhor Jeová : Ó Tiro, tu dizes: Eu sou  perfeita em formosura.

[[v26-27-4]]

^<<v26-27-4,4>>^ No coração dos mares estão  os teus termos; os que te edificaram aperfeiçoaram a tua formosura.

[[v26-27-5]]

^<<v26-27-5,5>>^ Fabricaram todos os teus conveses de faias de Senir; trouxeram cedros do Líbano para fazerem mastros para ti.

[[v26-27-6]]

^<<v26-27-6,6>>^ Fizeram os teus remos de  carvalhos de Basã: a companhia dos assírios fez os teus bancos de marfim das ilhas dos quiteus.

[[v26-27-7]]

^<<v26-27-7,7>>^ Linho fino bordado do Egito era a tua cortina, para te servir de vela; azul e púrpura das ilhas de Elisa eram a tua cobertura.

[[v26-27-8]]

^<<v26-27-8,8>>^ Os moradores de Sidom e de Arvade foram os teus remeiros; os teus sábios, ó Tiro, que  se achavam em ti, esses foram os teus pilotos.

[[v26-27-9]]

^<<v26-27-9,9>>^ Os anciãos de Gebal e seus sábios foram em ti os que consertavam as tuas fendas; todos os navios do mar e os marinheiros se acharam em ti, para tratarem dos teus negócios.

[[v26-27-10]]

^<<v26-27-10,10>>^ Os persas, e os lídios, e os de Pute eram no teu exército os teus soldados: escudos e capacetes penduraram em ti: eles fizeram a tua beleza.

[[v26-27-11]]

^<<v26-27-11,11>>^ Os filhos de Arvade e o teu exército estavam  sobre os teus muros em redor, e os gamaditas sobre as tuas torres: penduravam os seus escudos nos teus muros em redor; eles aperfeiçoavam a tua formosura.

[[v26-27-12]]

^<<v26-27-12,12>>^ Tarsis negociava contigo, por causa da abundância de toda a casta de fazenda: com prata, ferro, estanho, e chumbo negociavam em tuas feiras.

[[v26-27-13]]

^<<v26-27-13,13>>^ Javã, Tubal e Meseque eram teus mercadores: com almas de homens e vasos de bronze fizeram negócios contigo.

[[v26-27-14]]

^<<v26-27-14,14>>^ Das casas de Togarma traziam às  tuas feiras cavalos e cavaleiros e machos;

[[v26-27-15]]

^<<v26-27-15,15>>^ Os filhos de Dedã eram os teus mercadores; muitas ilhas eram o mercado da tua mão: dentes de marfim e pau preto tornavam a dar-te em  presente.

[[v26-27-16]]

^<<v26-27-16,16>>^ A Síria negociava contigo por causa da multidão das tuas obras: esmeralda, púrpura, e obra bordada, e seda, e corais e cristais traziam às tuas feiras.

[[v26-27-17]]

^<<v26-27-17,17>>^ Judá e a terra de Israel, eram eles os teus mercadores: com trigo de Minite, e panague, e mel, e azeite e bálsamo fizeram negócios contigo.

[[v26-27-18]]

^<<v26-27-18,18>>^ Damasco negociava contigo, por causa da multidão das tuas obras, por causa da multidão de toda a sorte de fazenda, com vinho de Helbom e lã branca.

[[v26-27-19]]

^<<v26-27-19,19>>^ Também Dã, e Javã, o caminhante, traficavam nas tuas feiras: ferro polido, casca, e cana aromática entravam no teu negócio.

[[v26-27-20]]

^<<v26-27-20,20>>^ Dedã negociava contigo com panos preciosos para carros.

[[v26-27-21]]

^<<v26-27-21,21>>^ Arábia, e todos os príncipes de Quedar, eram eles os mercadores de tua mão, com cordeiros, e carneiros e bodes; nestas cousas negociavam contigo.

[[v26-27-22]]

^<<v26-27-22,22>>^ Os mercadores de Seba e Raamá eram eles os teus mercadores em todos os mais subidos aromas, e em toda a pedra preciosa e ouro negociavam nas tuas feiras.

[[v26-27-23]]

^<<v26-27-23,23>>^ Harã, e Cane e Éden, os mercadores de Seba, Assur e  Quilmade negociavam contigo.

[[v26-27-24]]

^<<v26-27-24,24>>^ Estes eram teus mercadores em toda a sorte de mercadorias, em fardos de jacinto e de bordados, e em cofres de roupas preciosas, amarrados com cordas e feitos de cedro.

[[v26-27-25]]

^<<v26-27-25,25>>^ Os navios de Tarsis eram as tuas caravanas, por causa do teu negócio; e te encheste, e te glorificaste muito no meio dos mares.

[[v26-27-26]]

^<<v26-27-26,26>>^ Os teus remeiros te conduziram sobre grandes águas: o vento oriental te quebrantou no meio dos mares.

[[v26-27-27]]

^<<v26-27-27,27>>^ As tuas fazendas e as tuas feiras, o teu negócio, os teus marinheiros, e os teus pilotos, os que consertavam as tuas fendas, e os que faziam os teus negócios, e todos os teus soldados, que estão em ti, juntamente com toda a tua congregação, que está no meio de ti, cairão no meio dos mares no dia da tua queda.

[[v26-27-28]]

^<<v26-27-28,28>>^ Ao estrondo da gritaria dos teus pilotos tremerão os arrabaldes.

[[v26-27-29]]

^<<v26-27-29,29>>^ E todos os que pegam no remo, os marinheiros, e todos os pilotos do mar descerão de seus navios, e na terra pararão.

[[v26-27-30]]

^<<v26-27-30,30>>^ E farão ouvir a sua voz sobre ti, e gritarão amargamente; e lançarão pó sobre as cabeças, e na cinza se revolverão.

[[v26-27-31]]

^<<v26-27-31,31>>^ E se farão inteiramente calvos por tua causa, e se cingirão de sacos, e chorarão sobre ti com amargura de alma, com amarga lamentação.

[[v26-27-32]]

^<<v26-27-32,32>>^ E levantarão uma lamentação sobre ti no seu pranto, e lamentarão sobre ti, dizendo : Quem foi como Tiro, como a que está reduzida ao silêncio no meio do mar?

[[v26-27-33]]

^<<v26-27-33,33>>^ Quando as tuas mercadorias eram exportadas pelos mares, fartaste a muitos povos com a multidão da tua fazenda e do teu negócio, enriqueceste os reis da terra.

[[v26-27-34]]

^<<v26-27-34,34>>^ No tempo em que foste quebrantada nos mares, nas profundezas das águas, caíram os teus negócios e toda a tua congregação no meio de ti.

[[v26-27-35]]

^<<v26-27-35,35>>^ Todos os moradores das ilhas foram cheios de espanto por tua causa; e os seus reis tremeram em grande maneira, e  foram perturbados nos seus  rostos.

[[v26-27-36]]

^<<v26-27-36,36>>^ Os mercadores dentre os povos assobiaram sobre ti; tu te tornaste em  grande espanto, e nunca mais serás para sempre.

'''

xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[&#60; Capítulo Anterior] | <<v26-27-0,Topo>> | xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[Próximo Capítulo &#62;]