include::./index.adoc[]

[[v26-42-0]]
=== Ezequiel, 42
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-42-1]]

^<<v26-42-1,1>>^ DEPOIS disto fez-me sair para fora, ao átrio exterior, para a banda do caminho do norte; e me levou às câmaras que estavam  defronte do largo vazio, e que estavam  defronte do edifício, da banda do norte.

[[v26-42-2]]

^<<v26-42-2,2>>^ Do comprimento de cem côvados era  a entrada do norte: e a largura era  de cinquenta côvados.

[[v26-42-3]]

^<<v26-42-3,3>>^ Em frente dos vinte côvados , que tinha  o átrio interior, e em frente do pavimento que tinha  o átrio exterior, havia  galeria contra galeria em três andares.

[[v26-42-4]]

^<<v26-42-4,4>>^ E diante das câmaras havia  um passeio de dez côvados de largo, da banda de dentro, e um caminho dum côvado: e as suas entradas eram para o lado do norte.

[[v26-42-5]]

^<<v26-42-5,5>>^ E as câmaras de cima eram mais  estreitas; porque as galerias tomavam aqui mais espaço do que nas de baixo e nas do meio do edifício.

[[v26-42-6]]

^<<v26-42-6,6>>^ Porque elas eram  de três andares , e não tinham colunas como as colunas dos átrios; por isso desde o chão se iam estreitando mais do que as de baixo e as do meio.

[[v26-42-7]]

^<<v26-42-7,7>>^ E o muro que estava  por fora, defronte das câmaras, no caminho do átrio exterior, diante das câmaras, tinha  cinquenta côvados de comprimento.

[[v26-42-8]]

^<<v26-42-8,8>>^ Porque o comprimento das câmaras, que estavam no átrio exterior, era de  cinquenta côvados; e eis que defronte do templo havia  cem côvados.

[[v26-42-9]]

^<<v26-42-9,9>>^ E da parte de baixo destas câmaras estava  a entrada do lado do oriente, quando se entra nelas pelo átrio exterior.

[[v26-42-10]]

^<<v26-42-10,10>>^ Na largura do muro do átrio para  o caminho do oriente, diante do lugar separado, e diante do edifício, havia  também câmaras.

[[v26-42-11]]

^<<v26-42-11,11>>^ E o caminho de diante delas era  da feição das câmaras, e olhava para  o caminho do norte; conforme o seu comprimento, assim era  a sua largura; e todas as suas saídas eram  também conforme as suas feições, e conforme as suas entradas.

[[v26-42-12]]

^<<v26-42-12,12>>^ E conforme as entradas das câmaras, que olhavam para  o caminho do sul, havia também  uma entrada do topo do caminho, do caminho diante do muro direito, para o caminho do oriente, quando se entra por elas.

[[v26-42-13]]

^<<v26-42-13,13>>^ Então me disse: As câmaras do norte, e  as câmaras do sul, que estão  diante do lugar separado, são  câmaras santas, em que os sacerdotes, que se chegam ao Senhor, comerão as cousas mais santas; ali porão as cousas mais santas, e as ofertas de comer, e a expiação pelo pecado, e a expiação pela culpa: porque o lugar é  santo.

[[v26-42-14]]

^<<v26-42-14,14>>^ Quando os sacerdotes entrarem, não sairão do santuário para o átrio exterior, mas porão ali as suas vestiduras com que ministraram, porque elas são  santidade: e vestir-se-ão doutras vestiduras, e assim  se aproximarão do lugar pertencente ao povo.

[[v26-42-15]]

^<<v26-42-15,15>>^ E, acabando ele de medir o templo interior, ele me fez sair pelo caminho da porta, cuja face olha para  o caminho do oriente; e mediu em redor.

[[v26-42-16]]

^<<v26-42-16,16>>^ Mediu a banda oriental com a cana de medir, quinhentas canas com a cana de medir ao redor.

[[v26-42-17]]

^<<v26-42-17,17>>^ Mediu a banda do norte, quinhentas canas com a cana de medir ao redor.

[[v26-42-18]]

^<<v26-42-18,18>>^ A banda do sul também  mediu, quinhentas canas com a cana de medir.

[[v26-42-19]]

^<<v26-42-19,19>>^ Deu uma volta para a banda do ocidente, e  mediu quinhentas canas com a cana de medir.

[[v26-42-20]]

^<<v26-42-20,20>>^ Mediu pelas quatro bandas; e  tinha um muro em redor, de quinhentas canas  de comprimento, e quinhentas de largura, para fazer separação entre o santo e o profano.

'''

xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[&#60; Capítulo Anterior] | <<v26-42-0,Topo>> | xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[Próximo Capítulo &#62;]