include::./index.adoc[]

[[v26-8-0]]
=== Ezequiel, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-8-1]]

^<<v26-8-1,1>>^ SUCEDEU pois, no sexto ano, no mês  sexto, no quinto dia  do mês, estando eu assentado na minha casa, e os anciãos de Judá assentados diante de mim, que ali a mão do Senhor Jeová  caiu sobre mim.

[[v26-8-2]]

^<<v26-8-2,2>>^ E olhei, e eis uma semelhança como aparência de fogo; desde a aparência dos seus lombos, e para baixo, era fogo; e dos seus lombos para cima como aspecto de um resplendor, como cor de âmbar;

[[v26-8-3]]

^<<v26-8-3,3>>^ E estendeu a forma duma mão, e me tomou pelos cabelos da minha cabeça; e o Espírito me levantou entre a terra e o céu, e me trouxe a Jerusalém em visões de Deus, até à entrada da porta do pátio  de dentro, que olha para o norte, onde estava colocada a imagem dos ciúmes, que provoca ciúmes.

[[v26-8-4]]

^<<v26-8-4,4>>^ E eis que a glória do Deus de Israel estava ali, conforme a semelhança que eu tinha visto no vale.

[[v26-8-5]]

^<<v26-8-5,5>>^ E disse-me: Filho do homem, levanta agora os teus olhos para o caminho do norte. E levantei os meus olhos para o caminho do norte, e eis que da banda do norte, à porta do altar, estava esta imagem de ciúmes, à entrada.

[[v26-8-6]]

^<<v26-8-6,6>>^ E disse-me: Filho do homem, vês tu o que eles estão fazendo? as grandes abominações que a casa de Israel faz aqui, para que me afaste do meu santuário? mas verás ainda maiores abominações.

[[v26-8-7]]

^<<v26-8-7,7>>^ E levou-me à porta do átrio: então olhei, e eis que havia um  buraco na parede.

[[v26-8-8]]

^<<v26-8-8,8>>^ E disse-me: Filho do homem, cava agora naquela parede. E cavei na parede, e eis que havia  uma porta.

[[v26-8-9]]

^<<v26-8-9,9>>^ Então me disse: entra, e vê as malignas abominações que eles fazem aqui.

[[v26-8-10]]

^<<v26-8-10,10>>^ E entrei, e olhei, e eis que toda a forma de répteis, e de animais abomináveis e de todos os ídolos da casa de Israel, estavam pintados na parede em todo o redor.

[[v26-8-11]]

^<<v26-8-11,11>>^ E setenta homens dos anciãos da casa de Israel, com Jaazanias, filho de Safã, que se achava no meio deles, estavam em pé diante das pinturas, e cada um tinha  na mão o seu incensário; e subia uma  espessa nuvem de incenso.

[[v26-8-12]]

^<<v26-8-12,12>>^ Então me disse: Viste, filho do homem, o que os anciãos da casa de Israel fazem nas trevas, cada um nas suas câmaras pintadas de imagens? e eles dizem: O Senhor não nos vê; o Senhor abandonou a terra.

[[v26-8-13]]

^<<v26-8-13,13>>^ E disse-me: Tornarás a ver ainda maiores abominações do que as que estes fazem.

[[v26-8-14]]

^<<v26-8-14,14>>^ E levou-me à entrada da porta da casa do Senhor, que está  da banda do norte, e eis que estavam ali mulheres assentadas chorando por Tamuz.

[[v26-8-15]]

^<<v26-8-15,15>>^ E disse-me: Viste, filho do homem? verás ainda abominações maiores do que estas.

[[v26-8-16]]

^<<v26-8-16,16>>^ E levou-me para o átrio interior da casa do Senhor, e eis que estavam  à entrada do templo do Senhor, entre o pórtico e o altar, cerca de vinte e cinco homens, de costas para o templo do Senhor, e com os rostos para o Oriente; e eles adoravam o sol virados para o Oriente.

[[v26-8-17]]

^<<v26-8-17,17>>^ Então me disse: Viste, filho do homem? há cousa mais leviana para a casa de Judá, do que essas abominações, que fazem aqui? havendo enchido a terra de violência, tornam a irritar-me; e, ei-los a chegar o ramo ao seu nariz.

[[v26-8-18]]

^<<v26-8-18,18>>^ Pelo que também eu procederei com furor; o meu olho não poupará, nem terei piedade: ainda que me gritem aos ouvidos com grande voz, eu não os ouvirei.

'''

xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[&#60; Capítulo Anterior] | <<v26-8-0,Topo>> | xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[Próximo Capítulo &#62;]