include::./index.adoc[]

[[v26-2-0]]
=== Ezequiel, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-2-1]]

^<<v26-2-1,1>>^ E DISSE-ME: Filho do homem, põe-te em pé, e falarei contigo.

[[v26-2-2]]

^<<v26-2-2,2>>^ Então entrou em mim o espírito, quando falava comigo, e me pôs em pé, e ouvi o que me falava.

[[v26-2-3]]

^<<v26-2-3,3>>^ E disse-me: Filho do homem, eu te envio aos filhos de Israel, às nações rebeldes que se rebelaram contra mim; eles e seus pais prevaricaram contra mim, até este mesmo dia.

[[v26-2-4]]

^<<v26-2-4,4>>^ E os filhos são de semblante duro, e obstinados de coração; eu te envio a eles, e lhes dirás: Assim diz o Senhor Jeová .

[[v26-2-5]]

^<<v26-2-5,5>>^ E eles, quer ouçam quer deixem de ouvir (porque eles são casa rebelde), hão de saber que esteve no meio deles um profeta.

[[v26-2-6]]

^<<v26-2-6,6>>^ E tu, ó filho do homem, não os temas, nem temas as suas palavras; ainda que sejam sarças e espinhos para contigo, e tu habites com escorpiões, não temas as suas palavras, nem te assustes com os seus rostos, porque são casa rebelde.

[[v26-2-7]]

^<<v26-2-7,7>>^ Mas tu lhes dirás as minhas palavras, quer ouçam quer deixem de ouvir, pois são rebeldes.

[[v26-2-8]]

^<<v26-2-8,8>>^ Mas tu, ó filho do homem, ouve o que eu te digo, não sejas rebelde como a casa rebelde; abre a tua boca, e come o  que eu te dou.

[[v26-2-9]]

^<<v26-2-9,9>>^ Então vi, e eis que uma mão se  estendia para mim, e eis que nela estava um  rolo de livro.

[[v26-2-10]]

^<<v26-2-10,10>>^ E estendeu-o diante de mim, e ele estava escrito por dentro e por fora; e nele se achavam escritas lamentações, e suspiros e ais.

'''

xref:026-ezequiel/026-ezequiel-001.adoc#v26-1-0[&#60; Capítulo Anterior] | <<v26-2-0,Topo>> | xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[Próximo Capítulo &#62;]