include::./index.adoc[]

[[v26-18-0]]
=== Ezequiel, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-18-1]]

^<<v26-18-1,1>>^ E VEIO a mim a palavra do Senhor, dizendo:

[[v26-18-2]]

^<<v26-18-2,2>>^ Que tendes vós, vós que dizeis esta parábola acerca da terra de Israel, dizendo: Os pais comeram uvas verdes, e os dentes dos filhos se embotaram?

[[v26-18-3]]

^<<v26-18-3,3>>^ Vivo eu, diz o Senhor Jeová , que nunca mais direis este provérbio em Israel.

[[v26-18-4]]

^<<v26-18-4,4>>^ Eis que todas as almas são minhas; como a alma do pai, também a alma do filho é minha: a alma que pecar, essa morrerá.

[[v26-18-5]]

^<<v26-18-5,5>>^ Sendo pois o homem justo, e fazendo juízo e justiça.

[[v26-18-6]]

^<<v26-18-6,6>>^ Não comendo sobre os montes, nem levantando os seus olhos para os ídolos da casa de Israel, nem contaminando a mulher do seu próximo, nem se chegando à mulher na sua separação;

[[v26-18-7]]

^<<v26-18-7,7>>^ Não oprimindo a ninguém, tornando ao devedor o seu penhor, e não roubando, dando o seu pão ao faminto, e cobrindo ao nu com vestido,

[[v26-18-8]]

^<<v26-18-8,8>>^ Não dando o seu dinheiro à usura, e não recebendo demais, desviando a sua mão da injustiça, e fazendo verdadeiro juízo entre homem e homem;

[[v26-18-9]]

^<<v26-18-9,9>>^ Andando nos meus estatutos, e guardando os meus juízos, para obrar segundo  a verdade, o tal justo certamente viverá, diz o Senhor Jeová .

[[v26-18-10]]

^<<v26-18-10,10>>^ E se  ele gerar um  filho ladrão, derramador de sangue, que fizer a seu irmão qualquer destas cousas;

[[v26-18-11]]

^<<v26-18-11,11>>^ E não cumprir todos aqueles deveres, mas antes comer sobre os montes, e contaminar a mulher de seu próximo;

[[v26-18-12]]

^<<v26-18-12,12>>^ E oprimir ao aflito e necessitado, praticar roubos, não tornar o penhor, e levantar os seus olhos para os ídolos, cometer abominação;

[[v26-18-13]]

^<<v26-18-13,13>>^ E emprestar com usura, e receber de mais, porventura  viverá? Não viverá: todas estas abominações ele fez, certamente morrerá; o seu sangue será sobre ele.

[[v26-18-14]]

^<<v26-18-14,14>>^ E eis que, se ele gerar um filho que veja todos os pecados que seu pai fez, e, vendo- os  não cometer cousas semelhantes;

[[v26-18-15]]

^<<v26-18-15,15>>^ Não comer sobre os montes, e não levantar os seus olhos para os ídolos da casa de Israel, e  não contaminar a mulher de seu próximo;

[[v26-18-16]]

^<<v26-18-16,16>>^ E não oprimir a ninguém, e  não retiver o penhor, e não roubar, der o seu pão ao faminto, e cobrir ao nu com vestido;

[[v26-18-17]]

^<<v26-18-17,17>>^ Desviar do aflito a sua mão, não receber usura em demasia, fizer os meus juízos, e  andar nos meus estatutos, o tal não morrerá pela maldade de seu pai; certamente viverá.

[[v26-18-18]]

^<<v26-18-18,18>>^ Seu pai, porque fez opressão, e roubou os bens do irmão, e fez o que não era  bom no meio de seu povo, eis que ele morrerá pela sua maldade.

[[v26-18-19]]

^<<v26-18-19,19>>^ Mas dizeis: Por que não levará o filho a maldade do pai? Porque o filho fez juízo e justiça, e  guardou todos os meus estatutos, e os praticou, por isso  certamente viverá.

[[v26-18-20]]

^<<v26-18-20,20>>^ A alma que pecar, essa morrerá: o filho não levará a maldade do pai, nem o pai levará a maldade do filho: a justiça do justo ficará sobre ele, e a impiedade do ímpio cairá sobre ele.

[[v26-18-21]]

^<<v26-18-21,21>>^ Mas se  o ímpio se converter de todos os seus pecados que cometeu, e guardar todos os meus estatutos, e fizer juízo e justiça, certamente viverá; não morrerá.

[[v26-18-22]]

^<<v26-18-22,22>>^ De todas suas transgressões que cometeu não haverá lembrança contra ele: pela sua justiça que praticou viverá.

[[v26-18-23]]

^<<v26-18-23,23>>^ Desejaria eu, de qualquer maneira, a morte do ímpio? diz o Senhor Jeová : não desejo antes que se converta dos seus caminhos e viva?

[[v26-18-24]]

^<<v26-18-24,24>>^ Mas, desviando-se o justo da sua justiça, e cometendo a iniquidade, fazendo conforme todas as abominações que faz o ímpio, porventura  viverá? De todas as suas justiças que tiver feito não se fará memória: na sua transgressão com que transgrediu, e no seu pecado com que pecou, neles morrerá.

[[v26-18-25]]

^<<v26-18-25,25>>^ Dizeis, porém: O caminho do Senhor não é direito. Ouvi agora, ó casa de Israel: Não é o meu caminho direito? não são os vossos caminhos torcidos?

[[v26-18-26]]

^<<v26-18-26,26>>^ Desviando-se o justo da sua justiça, e cometendo iniquidade, morrerá por ela; na sua iniquidade que cometeu morrerá.

[[v26-18-27]]

^<<v26-18-27,27>>^ Mas convertendo-se o ímpio da sua impiedade que cometeu, e praticando o juízo e a justiça, conservará este a sua alma em vida.

[[v26-18-28]]

^<<v26-18-28,28>>^ Pois que reconsidera, e se converte de todas as suas transgressões que cometeu, certamente viverá, não morrerá.

[[v26-18-29]]

^<<v26-18-29,29>>^ Contudo, diz a casa de Israel: O caminho do Senhor não é direito. Não são os meus caminhos direitos, ó casa de Israel? e não são os vossos caminhos torcidos?

[[v26-18-30]]

^<<v26-18-30,30>>^ Portanto, eu vos julgarei, a cada um conforme os seus caminhos, ó casa de Israel, diz o Senhor Jeová : vinde, e convertei-vos de todas as vossas transgressões, e a iniquidade não vos servirá de tropeço.

[[v26-18-31]]

^<<v26-18-31,31>>^ Lançai de vós todas as vossas transgressões com que transgredistes, e criai em vós um coração novo e um espírito novo; pois por que razão morreríeis, ó casa de Israel?

[[v26-18-32]]

^<<v26-18-32,32>>^ Porque não tomo prazer na morte do que morre, diz o Senhor Jeová : convertei-vos, pois, e vivei.

'''

xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[&#60; Capítulo Anterior] | <<v26-18-0,Topo>> | xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[Próximo Capítulo &#62;]