include::./index.adoc[]

[[v26-13-0]]
=== Ezequiel, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-13-1]]

^<<v26-13-1,1>>^ E VEIO a mim a palavra do Senhor, dizendo:

[[v26-13-2]]

^<<v26-13-2,2>>^ Filho do homem, profetiza contra os profetas de Israel que são profetizadores, e dize aos que só profetizam o que vê o seu coração: Ouvi a palavra do Senhor:

[[v26-13-3]]

^<<v26-13-3,3>>^ Assim diz o Senhor Jeová : Ai dos profetas loucos, que seguem o seu próprio  espírito e cousas que não viram!

[[v26-13-4]]

^<<v26-13-4,4>>^ Os teus profetas, ó Israel, são como raposas nos desertos.

[[v26-13-5]]

^<<v26-13-5,5>>^ Não subistes às brechas, nem reparastes a fenda da casa de Israel, para estardes na peleja no dia do Senhor.

[[v26-13-6]]

^<<v26-13-6,6>>^ Veem vaidade e adivinhação mentirosa os que dizem: O Senhor disse; quando o Senhor os não enviou; e fazem que se espere o cumprimento da palavra.

[[v26-13-7]]

^<<v26-13-7,7>>^ Não vedes visão de vaidade, e não falais adivinhação mentirosa, quando dizeis: O Senhor diz, sendo que eu tal  não falei?

[[v26-13-8]]

^<<v26-13-8,8>>^ Portanto assim diz o Senhor Jeová : Como falais vaidade, e vedes a mentira, portanto eis que eu sou  contra vós, diz o Senhor Jeová .

[[v26-13-9]]

^<<v26-13-9,9>>^ E a minha mão será contra os profetas que veem vaidade e que adivinham mentira; na congregação do meu povo não estarão, nem nos registros da casa de Israel se escreverão, nem entrarão na terra de Israel: e sabereis que eu sou  o Senhor Jeová .

[[v26-13-10]]

^<<v26-13-10,10>>^ Visto que, sim, visto que andam enganando o meu povo, dizendo: Paz, não havendo paz; e um edifica a parede de lodo, e outros a rebocam de cal não adubada;

[[v26-13-11]]

^<<v26-13-11,11>>^ Dize aos que rebocam de cal não adubada que ela cairá. Haverá uma  grande pancada de chuva, e vós, ó pedras grandes de saraiva, caireis, e um  vento tempestuoso a  fenderá.

[[v26-13-12]]

^<<v26-13-12,12>>^ Ora, eis que, caindo a parede, não vos dirão: Onde está  o reboco de que a rebocastes?

[[v26-13-13]]

^<<v26-13-13,13>>^ Portanto assim diz o Senhor Jeová : Um  vento tempestuoso a fenderá no meu furor, e uma  grande pancada de chuva haverá na minha ira, e grandes pedras de saraiva na minha  indignação, para a consumir.

[[v26-13-14]]

^<<v26-13-14,14>>^ E derribarei a parede que rebocastes de cal não adubada, e darei com ela por terra, e o seu fundamento se descobrirá; assim cairá, e perecereis no meio dela, e sabereis que eu sou  o Senhor.

[[v26-13-15]]

^<<v26-13-15,15>>^ Assim cumprirei o meu furor contra a parede, e contra os que a rebocam de cal não adubada; e vos direi: A parede já não existe, nem aqueles que a rebocaram;

[[v26-13-16]]

^<<v26-13-16,16>>^ Os profetas de Israel, que profetizam de Jerusalém, e veem para ela visão de paz, não havendo paz, diz o Senhor Jeová .

[[v26-13-17]]

^<<v26-13-17,17>>^ E tu, ó filho do homem, dirige o teu rosto contra as filhas do teu povo, que profetizam de seu coração, e profetiza contra elas.

[[v26-13-18]]

^<<v26-13-18,18>>^ E dize: Assim diz o Senhor Jeová : Ai das que cosem almofadas para todos os sovacos, e que fazem travesseiros para cabeças de toda estátua, para caçarem as almas! porventura  caçareis as almas do meu povo? e guardareis vivas as almas para vós?

[[v26-13-19]]

^<<v26-13-19,19>>^ Vós me profanastes entre o meu povo, por punhados de cevada, e por pedaços de pão, para matardes as almas que não haviam de morrer, e para guardardes vivas as almas que não haviam de viver, mentindo assim  ao meu povo que escuta a mentira.

[[v26-13-20]]

^<<v26-13-20,20>>^ Portanto assim diz o Senhor Jeová : Eis aí vou  eu contra as vossas almofadas, com que vós ali caçais as almas como aves, e as arrancarei de vossos braços; e soltarei as almas que vós caçais como aves.

[[v26-13-21]]

^<<v26-13-21,21>>^ E rasgarei os vossos toucadores, e livrarei o meu povo das vossas mãos, e nunca mais estarão em vossas mãos para serem caçadas; e sabereis que eu sou  o Senhor.

[[v26-13-22]]

^<<v26-13-22,22>>^ Visto que entristecestes o coração do justo com  falsidade, não o havendo eu entristecido; e esforçastes as mãos do ímpio, para que não se desviasse do seu mau caminho, e vivesse;

[[v26-13-23]]

^<<v26-13-23,23>>^ Portanto não vereis mais a vaidade, nem mais fareis adivinhações; mas livrarei o meu povo das vossas mãos, e sabereis que eu sou  o Senhor.

'''

xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[&#60; Capítulo Anterior] | <<v26-13-0,Topo>> | xref:026-ezequiel/026-ezequiel-014.adoc#v26-14-0[Próximo Capítulo &#62;]