include::./index.adoc[]

[[v26-16-0]]
=== Ezequiel, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-16-1]]

^<<v26-16-1,1>>^ E VEIO a mim a palavra do Senhor, dizendo:

[[v26-16-2]]

^<<v26-16-2,2>>^ Filho do homem, faze conhecer a Jerusalém as suas abominações.

[[v26-16-3]]

^<<v26-16-3,3>>^ E dize: Assim diz o Senhor Jeová  a Jerusalém: A tua origem e o teu nascimento procedem  da terra dos cananeus: teu pai era amorreu, e a tua mãe heteia.

[[v26-16-4]]

^<<v26-16-4,4>>^ E, quanto ao teu nascimento, no dia em que nasceste não te foi cortado o umbigo, nem foste lavada com água, para tua purificação; nem tão pouco foste esfregada, com sal, nem envolta em faixas.

[[v26-16-5]]

^<<v26-16-5,5>>^ Não se compadeceu de ti olho algum, para te fazer alguma destas cousas, compadecido de ti; antes foste lançada em pleno campo, pelo nojo da tua alma, no dia em que tu nasceste.

[[v26-16-6]]

^<<v26-16-6,6>>^ E, passando eu por ti, vi-te manchada do teu sangue, e disse-te: Ainda que estás  no teu sangue, vive; sim, disse-te: Ainda que estás  no teu sangue, vive.

[[v26-16-7]]

^<<v26-16-7,7>>^ Eu te fiz multiplicar como o renovo do campo, e cresceste e te engrandeceste, e alcançaste grande formosura: avultaram os seios e cresceu o teu cabelo; mas estavas  nua e descoberta.

[[v26-16-8]]

^<<v26-16-8,8>>^ E, passando eu por ti, vi-te, e eis que o teu tempo, era  tempo de amores; e estendi sobre ti a ourela do meu manto, e cobri a tua nudez; e dei-te juramento, e entrei em concerto contigo, diz o Senhor Jeová , e tu ficaste sendo  minha.

[[v26-16-9]]

^<<v26-16-9,9>>^ Então te lavei com água, e te enxuguei do teu sangue, e te ungi com óleo.

[[v26-16-10]]

^<<v26-16-10,10>>^ E te vesti de bordadura, e te calcei com pele  de texugo, e te cingi de linho fino, e te cobri de seda.

[[v26-16-11]]

^<<v26-16-11,11>>^ E te ornei de enfeites, e te pus braceletes nas mãos e um colar à roda do teu pescoço.

[[v26-16-12]]

^<<v26-16-12,12>>^ E te pus uma joia na testa, e pendentes nas orelhas, e uma  coroa de glória na cabeça.

[[v26-16-13]]

^<<v26-16-13,13>>^ E assim  foste ornada de ouro e prata, e o teu vestido foi  de linho fino, e de seda e bordadura: nutriste-te de flor de farinha, e de mel e óleo; e foste formosa em extremo, e foste próspera, até chegares a ser rainha.

[[v26-16-14]]

^<<v26-16-14,14>>^ E correu a tua fama entre as nações, por causa da tua formosura, pois era perfeita, por causa da minha glória que eu tinha posto sobre ti, diz o Senhor Jeová .

[[v26-16-15]]

^<<v26-16-15,15>>^ Mas confiaste na tua formosura, e te corrompeste por causa da tua fama; prostituías-te a todo o que passava, para seres sua.

[[v26-16-16]]

^<<v26-16-16,16>>^ E tomaste dos teus vestidos, e fizeste lugares altos adornados de diversas cores, e te prostituíste sobre eles: tais cousas  não vieram, nem hão de vir.

[[v26-16-17]]

^<<v26-16-17,17>>^ E tomaste as tuas joias de enfeite, que eu te dei do meu ouro e da minha prata, e fizeste imagens de homens, e te prostituíste com elas.

[[v26-16-18]]

^<<v26-16-18,18>>^ E tomaste os teus vestidos bordados, e os cobriste; e o meu óleo e o meu perfume puseste diante delas.

[[v26-16-19]]

^<<v26-16-19,19>>^ E o meu pão que te dei, a flor de farinha, e o óleo e o mel, com que eu te sustentava, também puseste diante delas em cheiro suave; e assim  foi, diz o Senhor Jeová .

[[v26-16-20]]

^<<v26-16-20,20>>^ Além disto, tomaste a teus filhos e tuas filhas, que por mim geraras, e os sacrificaste a elas, para serem consumidos: acaso é  pequena a tua prostituição?

[[v26-16-21]]

^<<v26-16-21,21>>^ E mataste a meus filhos e os entregaste a elas para os fazerem passar pelo fogo.

[[v26-16-22]]

^<<v26-16-22,22>>^ E em todas as tuas abominações, e nas tuas prostituições, não te lembraste dos dias da tua mocidade, quando tu estavas nua e descoberta, e manchada do teu sangue.

[[v26-16-23]]

^<<v26-16-23,23>>^ E sucedeu, depois de toda a tua maldade (ai! ai de ti! diz o Senhor Jeová ),

[[v26-16-24]]

^<<v26-16-24,24>>^ Que  edificaste uma abóbada, e fizeste lugares altos por todas as ruas.

[[v26-16-25]]

^<<v26-16-25,25>>^ A cada canto do caminho edificaste o teu lugar alto, e fizeste abominável a tua formosura, e alargaste os teus pés a todo o que passava: e multiplicaste as tuas prostituições.

[[v26-16-26]]

^<<v26-16-26,26>>^ Também te prostituíste com os filhos do Egito, teus vizinhos de grandes carnes, e multiplicaste a tua prostituição, para me provocares à ira.

[[v26-16-27]]

^<<v26-16-27,27>>^ Pelo que eis que estendi a minha mão sobre ti, e diminuí a tua porção; e te entreguei à vontade dos que te aborrecem, as filhas dos filisteus, as quais se envergonhavam do teu caminho depravado.

[[v26-16-28]]

^<<v26-16-28,28>>^ Também te prostituíste com os filhos da Assíria, porquanto eras insaciável; e, prostituindo-te com eles, nem ainda assim ficaste farta;

[[v26-16-29]]

^<<v26-16-29,29>>^ Antes multiplicaste as tuas prostituições na terra de Canaã até Caldeia, e nem ainda com isso te fartaste.

[[v26-16-30]]

^<<v26-16-30,30>>^ Quão fraco é teu coração, diz o Senhor Jeová , fazendo tu todas estas cousas, obra duma meretriz imperiosa!

[[v26-16-31]]

^<<v26-16-31,31>>^ Edificando tu a tua abóbada ao canto de cada caminho, e fazendo o teu lugar alto em cada rua, não foste sequer como a meretriz, pois desprezaste a paga:

[[v26-16-32]]

^<<v26-16-32,32>>^ Foste como  a mulher adúltera que, em lugar de seu marido, recebe os estranhos.

[[v26-16-33]]

^<<v26-16-33,33>>^ A todas as meretrizes dão paga, mas tu dás presentes a todos os teus amantes; e lhes dás presentes, para que venham a ti de todas as partes, pelas tuas prostituições.

[[v26-16-34]]

^<<v26-16-34,34>>^ Assim que contigo sucede o contrário doutras mulheres nas tuas prostituições, pois após ti não andam para prostituição; porque, dando tu a paga, e a ti não sendo dada a paga, fazes o contrário.

[[v26-16-35]]

^<<v26-16-35,35>>^ Portanto, ó meretriz, ouve a palavra do Senhor.

[[v26-16-36]]

^<<v26-16-36,36>>^ Assim diz o Senhor Jeová : Pois que se derramou o teu dinheiro, e se descobriu a tua nudez nas tuas prostituições com os teus amantes, como também com todos os ídolos das tuas abominações, e no sangue de teus filhos que lhes deste:

[[v26-16-37]]

^<<v26-16-37,37>>^ Eis que ajuntarei todos os teus amantes, com os quais te misturaste, como também todos os que amaste, com todos os que aborreceste, e ajuntá-los-ei contra ti em redor, e descobrirei a tua nudez diante deles, para que vejam toda a tua nudez.

[[v26-16-38]]

^<<v26-16-38,38>>^ E julgar-te-ei como são julgadas as adúlteras e as que derramam sangue; e entregar-te-ei ao sangue de furor e de ciúme.

[[v26-16-39]]

^<<v26-16-39,39>>^ E entregar-te-ei nas suas mãos, e derribarão a tua abóbada, e transtornarão os teus altos lugares, e te despirão os teus vestidos, e tomarão as tuas joias de enfeite, e te deixarão nua e descoberta.

[[v26-16-40]]

^<<v26-16-40,40>>^ Então farão subir contra ti um  ajuntamento, e te apedrejarão com pedra, e te traspassarão com as suas espadas.

[[v26-16-41]]

^<<v26-16-41,41>>^ E queimarão as tuas casas a fogo, e executarão juízos contra ti, aos olhos de muitas mulheres; e te farei cessar de ser meretriz, e paga não darás mais.

[[v26-16-42]]

^<<v26-16-42,42>>^ Assim farei descansar em ti o meu furor, e os meus ciúmes se desviarão de ti, e me aquietarei, e nunca mais me indignarei.

[[v26-16-43]]

^<<v26-16-43,43>>^ Pois que não te lembraste dos dias da tua mocidade, e me provocaste à ira com tudo isto, eis que também eu farei recair o teu caminho sobre a tua  cabeça, diz o Senhor Jeová , e não farás tal perversidade sobre todas as tuas abominações.

[[v26-16-44]]

^<<v26-16-44,44>>^ Eis que todo o que usa de provérbios usará contra ti este  provérbio, dizendo: Qual a mãe, tal é  a sua filha.

[[v26-16-45]]

^<<v26-16-45,45>>^ Tu és  a filha de tua mãe, que tinha nojo de seu marido e de seus filhos; e tu és  a irmã de tuas irmãs, que tinham nojo de seus maridos e de seus filhos: vossa mãe foi  heteia, e vosso pai amorreu.

[[v26-16-46]]

^<<v26-16-46,46>>^ E tua irmã maior é  Samaria, ela e suas filhas, a qual habita à tua esquerda: e tua irmã menor que tu, que habita à tua mão direita, é  Sodoma e suas filhas.

[[v26-16-47]]

^<<v26-16-47,47>>^ Todavia não andaste nos seus caminhos, nem fizeste conforme as suas abominações; mas, como se isto  mui pouco fora , ainda te corrompeste mais do que elas, em todos os teus caminhos.

[[v26-16-48]]

^<<v26-16-48,48>>^ Vivo eu, diz o Senhor Jeová , que  não fez Sodoma, tua irmã, ela e suas filhas, como fizeste tu e tuas filhas.

[[v26-16-49]]

^<<v26-16-49,49>>^ Eis que esta foi a maldade de Sodoma, tua irmã; soberba, fartura de pão, e abundância de ociosidade teve ela e suas filhas; mas nunca esforçou a mão do pobre e do necessitado.

[[v26-16-50]]

^<<v26-16-50,50>>^ E se ensoberbeceram, e fizeram abominação diante de mim; pelo que as tirei dali, vendo eu isto.

[[v26-16-51]]

^<<v26-16-51,51>>^ Também Samaria não cometeu metade de teus pecados: e multiplicaste as tuas abominações mais do que elas, e justificaste a tuas irmãs, com todas as abominações que fizeste.

[[v26-16-52]]

^<<v26-16-52,52>>^ Tu pois  sofre a tua vergonha, tu que julgaste a tuas irmãs, pelos teus pecados, que fizeste mais abomináveis do que elas; mais justas são do que tu: envergonha-te logo também, e sofre a tua vergonha, pois justificaste a tuas irmãs.

[[v26-16-53]]

^<<v26-16-53,53>>^ Eu pois farei voltar os cativos deles; os cativos de Sodoma e suas filhas, e os cativos de Samaria e suas filhas, e os cativos do teu cativeiro entre eles;

[[v26-16-54]]

^<<v26-16-54,54>>^ Para que sofras a tua vergonha, e sejas envergonhada por tudo o que fizeste, dando-lhes tu consolação.

[[v26-16-55]]

^<<v26-16-55,55>>^ Quando tuas irmãs, Sodoma e suas filhas, tornarem ao seu primeiro estado, e Samaria e suas filhas tornarem ao seu primeiro estado, também tu e tuas filhas tornareis ao vosso primeiro estado.

[[v26-16-56]]

^<<v26-16-56,56>>^ Nem mesmo Sodoma, tua irmã, foi mencionada pela tua boca, no dia das tuas soberbas,

[[v26-16-57]]

^<<v26-16-57,57>>^ Antes que se descobrisse a tua maldade, como no tempo do desprezo das filhas da Síria, e de todos os que estavam ao redor dela, as filhas dos filisteus, que te desprezavam em redor.

[[v26-16-58]]

^<<v26-16-58,58>>^ A tua perversidade e as tuas abominações tu levarás, diz o Senhor.

[[v26-16-59]]

^<<v26-16-59,59>>^ Porque assim diz o Senhor Jeová : Eu te farei como fizeste, que desprezaste o juramento, quebrantando o concerto.

[[v26-16-60]]

^<<v26-16-60,60>>^ Contudo eu me lembrarei do meu concerto, que contigo fiz nos dias da tua mocidade; e estabelecerei contigo um concerto eterno.

[[v26-16-61]]

^<<v26-16-61,61>>^ Então te lembrarás dos teus caminhos, e te confundirás, quando receberes tuas irmãs mais velhas do que tu, com as mais novas do que tu, porque tas darei por filhas, mas não pelo teu concerto.

[[v26-16-62]]

^<<v26-16-62,62>>^ Porque eu estabelecerei o meu concerto contigo, e saberás que eu sou o Senhor;

[[v26-16-63]]

^<<v26-16-63,63>>^ Para que te lembres, e te envergonhes, e nunca mais abras a tua boca, por causa da tua vergonha, quando me reconciliar contigo de tudo quanto fizeste, diz o Senhor Jeová .

'''

xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[&#60; Capítulo Anterior] | <<v26-16-0,Topo>> | xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[Próximo Capítulo &#62;]