include::./index.adoc[]

[[v26-47-0]]
=== Ezequiel, 47
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-47-1]]

^<<v26-47-1,1>>^ DEPOIS disto me fez voltar à entrada da casa, e eis que saíam umas águas debaixo do umbral da casa, para o oriente; porque a face da casa olhava para  o oriente, e as águas vinham debaixo, desde a banda direita da casa, da banda do sul do altar.

[[v26-47-2]]

^<<v26-47-2,2>>^ E ele me tirou pelo  caminho da porta do norte, e me fez dar uma volta pelo  caminho de fora, até a porta exterior, pelo caminho que olha para o oriente; e eis que corriam umas águas desde a banda direita.

[[v26-47-3]]

^<<v26-47-3,3>>^ E  saiu aquele homem para o oriente, tendo na mão um cordel de medir; e mediu mil côvados, e me fez passar pelas águas, águas que  me davam pelos artelhos.

[[v26-47-4]]

^<<v26-47-4,4>>^ E mediu mais mil, e me fez passar pelas águas, águas que me davam pelos joelhos; e mediu mais  mil, e me fez passar por águas que me davam pelos lombos.

[[v26-47-5]]

^<<v26-47-5,5>>^ E mediu mais  mil, e era um  ribeiro, que eu não podia atravessar, porque as águas eram profundas, águas que se deviam passar a nado, ribeiro pelo qual não se podia passar.

[[v26-47-6]]

^<<v26-47-6,6>>^ E me disse: Viste, filho do homem? Então me levou, e me tornou a trazer à margem do ribeiro.

[[v26-47-7]]

^<<v26-47-7,7>>^ E , tornando eu, eis que à margem do ribeiro havia  uma grande abundância de árvores, de uma e de outra banda.

[[v26-47-8]]

^<<v26-47-8,8>>^ Então me disse: Estas águas saem para a região oriental, e descem à campina, e entram no mar; e , sendo levadas ao mar, sararão as águas.

[[v26-47-9]]

^<<v26-47-9,9>>^ E será que  toda a criatura vivente que vier por onde quer que entrarem estes dois ribeiros, viverá, e haverá muitíssimo peixe; porque lá chegarão estas  águas, e sararão, e viverá tudo por onde quer que entrar este ribeiro.

[[v26-47-10]]

^<<v26-47-10,10>>^ Será também que os pescadores estarão junto dele; desde Engedi até En-Eglaim, haverá lugar para estender as redes; o seu peixe, segundo a sua espécie, será como o peixe do mar grande, em multidão excessiva.

[[v26-47-11]]

^<<v26-47-11,11>>^ Mas os seus charcos e os seus lamaceiros não sararão; serão deixados para sal.

[[v26-47-12]]

^<<v26-47-12,12>>^ E junto do ribeiro, à sua margem, de uma e de outra banda, subirá toda a sorte de árvore que dá fruto para se  comer: não cairá a sua folha, nem perecerá o seu fruto: nos seus meses produzirá novos frutos, porque as suas águas saem do santuário; e o seu fruto servirá de alimento e a sua folha de remédio.

[[v26-47-13]]

^<<v26-47-13,13>>^ Assim diz o Senhor Jeová : Este será  o termo conforme  o qual tomareis a terra em herança, segundo as doze tribos de Israel, José terá duas  partes.

[[v26-47-14]]

^<<v26-47-14,14>>^ E vós a herdareis, tanto um como o outro; pois sobre ela levantei a minha mão, para a dar a vossos pais: assim que esta mesma terra vos cairá a vós em herança.

[[v26-47-15]]

^<<v26-47-15,15>>^ E este será o termo da terra, da banda do norte: desde o mar grande, caminho de Hetlom, até à entrada de Zedade;

[[v26-47-16]]

^<<v26-47-16,16>>^ Hamate, Berota, Sibraim, que estão  entre o termo de Damasco e entre o termo de Hamate: Hazer-Haticom, que está  junto ao termo de Haurã.

[[v26-47-17]]

^<<v26-47-17,17>>^ E o termo desde o mar será Hazer-Enom, no termo de Damasco, e na direção do norte está o termo de Hamate; e este  será o termo do norte.

[[v26-47-18]]

^<<v26-47-18,18>>^ E o termo do oriente, entre Haurã, e Damasco, e Gileade, e a terra de Israel, será o Jordão; desde o termo do norte até ao mar do oriente medireis: este será o termo do oriente.

[[v26-47-19]]

^<<v26-47-19,19>>^ E o termo do sul será desde Tamar até às águas da contenda de Cades, junto ao ribeiro, até ao mar grande: este será o termo para o lado do sul.

[[v26-47-20]]

^<<v26-47-20,20>>^ E o termo do ocidente será  o mar grande, desde o termo do sul  até à entrada de Hamate: este será  o termo do ocidente.

[[v26-47-21]]

^<<v26-47-21,21>>^ Repartireis pois esta terra entre vós, segundo as tribos de Israel.

[[v26-47-22]]

^<<v26-47-22,22>>^ Será, porém, que a sorteareis para vossa herança, e para a  dos estrangeiros que peregrinam no meio de vós, que geraram filhos no meio de vós; e vos serão como naturais entre os filhos de Israel; convosco entrarão em herança, no meio das tribos de Israel.

[[v26-47-23]]

^<<v26-47-23,23>>^ E será que  na tribo em que peregrinar o estrangeiro ali lhe  dareis a sua herança, diz o Senhor Jeová .

'''

xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[&#60; Capítulo Anterior] | <<v26-47-0,Topo>> | xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[Próximo Capítulo &#62;]