include::./index.adoc[]

[[v26-46-0]]
=== Ezequiel, 46
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-46-1]]

^<<v26-46-1,1>>^ ASSIM diz o Senhor Jeová : A porta do átrio interior, que olha para o oriente, estará fechada durante os seis dias, que são  de trabalho; mas no dia de sábado ela se abrirá; também no dia da lua nova se abrirá.

[[v26-46-2]]

^<<v26-46-2,2>>^ E o príncipe entrará pelo  caminho do vestíbulo da porta, por fora, e permanecerá junto da ombreira da porta; e os sacerdotes prepararão o seu holocausto, e os seus sacrifícios, pacíficos, e ele se prostrará no umbral da porta, e sairá; mas a porta não se fechará até à tarde.

[[v26-46-3]]

^<<v26-46-3,3>>^ E o povo da terra se prostrará à entrada da mesma porta, nos sábados e nas luas novas, diante do Senhor.

[[v26-46-4]]

^<<v26-46-4,4>>^ E o holocausto, que o príncipe oferecer ao Senhor, será , no dia de sábado, seis cordeiros sem mancha e um carneiro sem mancha.

[[v26-46-5]]

^<<v26-46-5,5>>^ E a oferta de manjares será um efa pelo carneiro; e pelo cordeiro, a oferta de manjares será o que puder dar; e de azeite um him para cada  efa.

[[v26-46-6]]

^<<v26-46-6,6>>^ Mas no dia da lua nova será  um bezerro, sem mancha: e seis cordeiros e um carneiro, eles serão sem mancha.

[[v26-46-7]]

^<<v26-46-7,7>>^ E preparará por  oferta de manjares um efa pelo bezerro e um efa pelo carneiro, mas pelos cordeiros, conforme o que alcançar a sua mão; e um him de azeite para um efa.

[[v26-46-8]]

^<<v26-46-8,8>>^ E, quando entrar o príncipe, entrará pelo  caminho do vestíbulo da porta, e sairá pelo mesmo caminho.

[[v26-46-9]]

^<<v26-46-9,9>>^ Mas, quando vier o povo da terra perante a face do Senhor nas solenidades, aquele que entrar pelo  caminho da porta do norte, para adorar, sairá pelo  caminho da porta do sul; e aquele que entrar pelo  caminho da porta do sul, sairá pelo  caminho da porta do norte: não tornará pelo  caminho da porta por onde entrou, mas sairá pela que está em frente dele.

[[v26-46-10]]

^<<v26-46-10,10>>^ E o príncipe entrará no meio deles, quando eles entrarem, e, saindo eles sairão todos.

[[v26-46-11]]

^<<v26-46-11,11>>^ E nas festas e nas solenidades será a oferta de manjares um efa pelo bezerro, e um efa pelo carneiro, mas pelos cordeiros o que puder dar; e de azeite um him para um efa.

[[v26-46-12]]

^<<v26-46-12,12>>^ E, quando o príncipe fizer oferta voluntária de holocaustos, ou de sacrifício pacífico, uma oferta voluntária ao Senhor, então lhe abrirão a porta que olha para o oriente, e fará o seu holocausto e os seus sacrifícios pacíficos, como houver feito no dia de sábado, e sairá, e se fechará a porta depois dele sair.

[[v26-46-13]]

^<<v26-46-13,13>>^ E prepararás um cordeiro dum ano, sem mancha, em  holocausto ao Senhor, cada dia; todas as manhãs o prepararás.

[[v26-46-14]]

^<<v26-46-14,14>>^ E, juntamente com ele prepararás uma oferta de manjares todas as manhãs, a sexta parte dum efa, e de azeite a terça parte dum him, para misturar com a flor de farinha: por  oferta de manjares para o Senhor, em  estatutos perpétuos e  contínuos.

[[v26-46-15]]

^<<v26-46-15,15>>^ Assim prepararão o cordeiro e a oferta de manjares, e o azeite, todas as manhãs, em holocausto contínuo.

[[v26-46-16]]

^<<v26-46-16,16>>^ Assim diz o Senhor Jeová : Quando o príncipe der um presente a algum de seus filhos, é sua herança, pertencerá a seus filhos: será  possessão deles por herança.

[[v26-46-17]]

^<<v26-46-17,17>>^ Mas, dando ele um presente da sua herança a algum dos seus servos, será deste até ao ano da liberdade; então tornará para o príncipe, porque herança dele é; seus filhos, eles a herdarão.

[[v26-46-18]]

^<<v26-46-18,18>>^ E o príncipe, não tomará nada da herança do povo, não os esbulhará da sua possessão: da sua própria possessão, deixará herança a seus filhos, para que o meu povo não seja retirado, cada um da sua possessão.

[[v26-46-19]]

^<<v26-46-19,19>>^ Depois disto me trouxe pela entrada que estava  ao lado da porta, às câmaras santas dos sacerdotes, que olhavam para o norte; e eis que ali havia um lugar em ambos os lados, para a banda do ocidente.

[[v26-46-20]]

^<<v26-46-20,20>>^ E ele me disse: Este é  o lugar onde os sacerdotes cozerão o sacrifício pela culpa, e o sacrifício pelo pecado, e  onde cozerão a oferta de manjares, para que a  não tragam ao átrio exterior para santificarem o povo.

[[v26-46-21]]

^<<v26-46-21,21>>^ Então me levou para fora, para o átrio exterior, e me fez passar às quatro esquinas do átrio: e eis que em cada esquina do átrio havia outro átrio.

[[v26-46-22]]

^<<v26-46-22,22>>^ Nas quatro esquinas do átrio havia  átrios fechados, com chaminés de quarenta côvados de comprimento e de trinta de largura: estas quatro esquinas tinham  uma mesma medida.

[[v26-46-23]]

^<<v26-46-23,23>>^ E um muro havia  ao redor delas, ao redor das quatro; e havia  cozinhas feitas por baixo dos muros ao redor.

[[v26-46-24]]

^<<v26-46-24,24>>^ E me disse: Estas são  as casas dos cozinheiros, onde os ministros da casa cozerão o sacrifício do povo.

'''

xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[&#60; Capítulo Anterior] | <<v26-46-0,Topo>> | xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[Próximo Capítulo &#62;]