include::./index.adoc[]

[[v26-23-0]]
=== Ezequiel, 23
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-23-1]]

^<<v26-23-1,1>>^ VEIO mais a mim a palavra do Senhor, dizendo:

[[v26-23-2]]

^<<v26-23-2,2>>^ Filho do homem, houve duas mulheres, filhas de uma mesma mãe.

[[v26-23-3]]

^<<v26-23-3,3>>^ Estas prostituíram-se no Egito; prostituíram-se na sua mocidade; ali foram apertados os seus peitos, e ali foram apalpados os seios da sua virgindade.

[[v26-23-4]]

^<<v26-23-4,4>>^ E os seus nomes eram : Oola, a mais velha, e Oóliba, sua irmã; e foram minhas, e tiveram filhos e filhas; e, quanto aos seus nomes Samaria é  Oola, e Jerusalém é  Oóliba.

[[v26-23-5]]

^<<v26-23-5,5>>^ E prostituiu-se Oola, sendo minha; e enamorou-se dos seus amantes, dos assírios, seus  vizinhos.

[[v26-23-6]]

^<<v26-23-6,6>>^ Vestidos de azul, prefeitos e magistrados, todos mancebos de cobiçar, cavaleiros montados a cavalo.

[[v26-23-7]]

^<<v26-23-7,7>>^ Assim cometeu ela as suas devassidões com eles, que eram todos a flor dos filhos da Assíria, e com todos aqueles de quem se enamorava; com todos os seus ídolos se contaminou.

[[v26-23-8]]

^<<v26-23-8,8>>^ E as suas impudicícias, que trouxe  do Egito, não as deixou; porque com ela se deitaram na sua mocidade, e eles apalparam os seios da sua virgindade, e derramaram sobre ela a sua impudicícia.

[[v26-23-9]]

^<<v26-23-9,9>>^ Portanto a entreguei na mão dos seus amantes, na mão dos filhos da Assíria, de quem se enamorara.

[[v26-23-10]]

^<<v26-23-10,10>>^ Estes descobriram a sua vergonha, levaram seus filhos e suas filhas, mas a ela mataram-na à espada; e foi afamada entre as mulheres, e sobre ela executaram juízos.

[[v26-23-11]]

^<<v26-23-11,11>>^ Vendo isto sua irmã Oóliba, corrompeu o seu amor mais do que ela, e as suas devassidões foram maiores do que as de sua irmã.

[[v26-23-12]]

^<<v26-23-12,12>>^ Enamorou-se dos filhos da Assíria, dos prefeitos e dos magistrados seus vizinhos, vestidos com primor, cavaleiros que andam montados em cavalos, todos mancebos de cobiçar.

[[v26-23-13]]

^<<v26-23-13,13>>^ E vi que se tinha contaminado; o caminho de ambas era  o mesmo.

[[v26-23-14]]

^<<v26-23-14,14>>^ E aumentou as suas impudicícias, porque viu homens pintados na parede, imagens dos caldeus, pintadas de vermelho;

[[v26-23-15]]

^<<v26-23-15,15>>^ Com os seus lombos cingidos, e com tingidas tiaras largas nas suas cabeças, todos com o parecer de capitães, semelhantes aos filhos de Babilônia em Caldeia, terra do seu nascimento.

[[v26-23-16]]

^<<v26-23-16,16>>^ E se enamorou deles, vendo-os com os seus olhos: e lhes mandou mensageiros a Caldeia.

[[v26-23-17]]

^<<v26-23-17,17>>^ Então vieram a ela os filhos de Babilônia para o leito dos amores, e a contaminaram com as suas impudicícias: e ela se contaminou com eles; então apartou-se deles a alma dela.

[[v26-23-18]]

^<<v26-23-18,18>>^ Assim pôs a descoberto as suas devassidões, e descobriu a sua vergonha; então a minha alma se apartou dela, como já se tinha apartado a minha alma de sua irmã.

[[v26-23-19]]

^<<v26-23-19,19>>^ Ela multiplicou todavia as suas prostituições, lembrando-se dos dias da sua mocidade, em que se prostituíra na terra do Egito.

[[v26-23-20]]

^<<v26-23-20,20>>^ E enamorou-se dos seus amantes, cujas carnes são como carnes de jumentos, e cujo fluxo é como o fluxo de cavalos.

[[v26-23-21]]

^<<v26-23-21,21>>^ Assim trouxeste à memória a apostasia da tua mocidade, quando os  do Egito apalpavam os teus seios, os peitos da tua mocidade.

[[v26-23-22]]

^<<v26-23-22,22>>^ Por isso, ó Oóliba, assim diz o Senhor Jeová : Eis que eu suscitarei contra ti os teus amantes, dos quais se tinha apartado a tua alma; e os trarei contra ti de toda a parte em redor:

[[v26-23-23]]

^<<v26-23-23,23>>^ Os filhos de Babilônia, e todos os caldeus de Pécode e de Soa, e de Coa, e  todos os filhos da Assíria com eles, mancebos de cobiçar, prefeitos e magistrados todos eles, capitães e homens afamados, todos eles montados a cavalo.

[[v26-23-24]]

^<<v26-23-24,24>>^ E virão contra ti com  carros, carretas e rodas, e com ajuntamento de povos; e se porão contra ti em redor com rodelas, e escudos, e capacetes; e porei diante deles o juízo, e julgar-te-ão segundo os seus juízos.

[[v26-23-25]]

^<<v26-23-25,25>>^ E porei contra ti o meu zelo, e usarão de indignação contigo: o nariz e as orelhas te tirarão, e o que te ficar de resto cairá à espada: teus filhos e tuas filhas eles te tomarão, e o que ficar por último em ti será consumido pelo fogo.

[[v26-23-26]]

^<<v26-23-26,26>>^ Também te despirão os teus vestidos, e te tomarão as tuas joias de adorno.

[[v26-23-27]]

^<<v26-23-27,27>>^ Assim farei cessar em ti a tua malignidade e a tua corrupção da terra do Egito; e não levantarás os teus olhos para eles, nem te lembrarás mais do Egito.

[[v26-23-28]]

^<<v26-23-28,28>>^ Porque assim diz o Senhor Jeová : Eis que eu te entregarei na mão dos que aborreces, na mão daqueles de quem se tinha apartado a tua alma.

[[v26-23-29]]

^<<v26-23-29,29>>^ E te tratarão com ódio, e levarão todo o teu trabalho, e te deixarão nua e despida: e descobrir-se-á a vergonha da tua prostituição, e a tua malignidade, e as tuas devassidões.

[[v26-23-30]]

^<<v26-23-30,30>>^ Estas cousas se te farão, porque te prostituíste após os gentios, e  te contaminaste com os seus ídolos.

[[v26-23-31]]

^<<v26-23-31,31>>^ No caminho de tua irmã andaste; por isso entregarei o seu copo na tua mão.

[[v26-23-32]]

^<<v26-23-32,32>>^ Assim diz o Senhor Jeová : Beberás o copo de tua irmã, fundo e largo: servirás de riso e escárnio; ele leva muito.

[[v26-23-33]]

^<<v26-23-33,33>>^ De embriaguez e de dor te encherás: o copo de tua irmã Samaria é  copo de espanto e de assolação.

[[v26-23-34]]

^<<v26-23-34,34>>^ Bebê-lo-ás pois, e esgotá-lo-ás, e os seus cacos roerás, e os teus peitos arrancarás; porque eu o anunciei, diz o Senhor Jeová .

[[v26-23-35]]

^<<v26-23-35,35>>^ Portanto, assim diz o Senhor Jeová : Como te esqueceste de mim, e me lançaste para trás das tuas costas, também carregarás com a tua malignidade e as tuas devassidões.

[[v26-23-36]]

^<<v26-23-36,36>>^ E, disse-me o Senhor: Filho do homem, julgarias a Oola e a Oóliba? mostra-lhes pois as suas abominações.

[[v26-23-37]]

^<<v26-23-37,37>>^ Porque adulteraram, e sangue se acha  nas suas mãos; com os seus ídolos adulteraram, e até os seus filhos, que de mim geraram, fizeram passar pelo fogo , para os consumirem.

[[v26-23-38]]

^<<v26-23-38,38>>^ E ainda isto me fizeram: contaminaram o meu santuário no mesmo dia, e profanaram os meus sábados.

[[v26-23-39]]

^<<v26-23-39,39>>^ Porquanto, havendo sacrificado seus filhos aos seus ídolos, vinham ao meu santuário no mesmo dia para o profanarem; e eis que assim fizeram no meio da minha casa.

[[v26-23-40]]

^<<v26-23-40,40>>^ E, o que mais é , mandaram vir uns homens de longe; fora-lhes enviado um mensageiro, e eis que vieram; por amor deles te lavaste, coloriste os teus olhos, e te ornaste de enfeites.

[[v26-23-41]]

^<<v26-23-41,41>>^ E te assentaste sobre um leito de honra, diante do qual estava uma mesa preparada; e puseste sobre ela o meu incenso e o meu óleo.

[[v26-23-42]]

^<<v26-23-42,42>>^ Havia com ela a voz de uma  multidão satisfeita, e com homens de classe baixa foram trazidos beberrões do deserto; e puseram braceletes nas suas mãos, e coroas de esplendor nas suas cabeças,

[[v26-23-43]]

^<<v26-23-43,43>>^ Então disse à envelhecida em  adultérios: Agora deveras se contaminarão com ela e ela com eles.

[[v26-23-44]]

^<<v26-23-44,44>>^ E entraram a ela, como quem entra a uma prostituta: assim entraram a Oola e a Oóliba, mulheres infames.

[[v26-23-45]]

^<<v26-23-45,45>>^ De maneira que homens justos as julgarão como se julgam as adúlteras, e como se julgam as que derramam o sangue; porque adúlteras são, e sangue há nas suas mãos.

[[v26-23-46]]

^<<v26-23-46,46>>^ Porque assim diz o Senhor Jeová : Farei subir contra elas uma  congregação, e as entregarei ao desterro e ao roubo.

[[v26-23-47]]

^<<v26-23-47,47>>^ E a congregação as apedrejará com pedras e as acutilará com as suas espadas: a seus filhos e suas filhas matarão, e as suas casas queimarão a fogo.

[[v26-23-48]]

^<<v26-23-48,48>>^ Assim farei cessar a infâmia da terra, para que se escarmentem todas as mulheres, e não façam conforme a vossa infâmia.

[[v26-23-49]]

^<<v26-23-49,49>>^ E a vossa infâmia carregareis sobre vós, e levareis os pecados dos vossos ídolos; e sabereis que eu sou  o Senhor Jeová .

'''

xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[&#60; Capítulo Anterior] | <<v26-23-0,Topo>> | xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[Próximo Capítulo &#62;]