include::./index.adoc[]

[[v26-7-0]]
=== Ezequiel, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-7-1]]

^<<v26-7-1,1>>^ DEPOIS veio a palavra do Senhor a mim, dizendo:

[[v26-7-2]]

^<<v26-7-2,2>>^ E tu, ó filho do homem, dize; assim diz o Senhor Jeová  acerca da terra de Israel: Vem o fim, o fim vem  sobre os quatro cantos da terra.

[[v26-7-3]]

^<<v26-7-3,3>>^ Agora vem  o fim sobre ti, porque enviarei sobre ti a minha ira, e te julgarei conforme os teus caminhos, e trarei sobre ti todas as tuas abominações.

[[v26-7-4]]

^<<v26-7-4,4>>^ E não te poupará o meu olho, nem terei piedade de ti , mas porei sobre ti os teus caminhos, e as tuas abominações estarão no meio de ti; e sabereis que eu sou  o Senhor.

[[v26-7-5]]

^<<v26-7-5,5>>^ Assim diz o Senhor Jeová : Um mal eis que um só mal vem.

[[v26-7-6]]

^<<v26-7-6,6>>^ Vem o fim, o fim vem, despertou-se contra ti; eis que vem.

[[v26-7-7]]

^<<v26-7-7,7>>^ Vem a tua sentença, ó habitante da terra. Vem o tempo; chegado é  o dia da turbação, e não da alegria, sobre os montes.

[[v26-7-8]]

^<<v26-7-8,8>>^ Agora depressa derramarei o meu furor sobre ti, e cumprirei a minha ira contra ti, e te julgarei conforme os teus caminhos, e porei sobre ti todas as tuas abominações.

[[v26-7-9]]

^<<v26-7-9,9>>^ E não te poupará o meu olho, nem terei piedade; conforme os teus caminhos, assim carregarei sobre ti, e as tuas abominações estarão no meio de ti; e sabereis que eu, o Senhor, castigo.

[[v26-7-10]]

^<<v26-7-10,10>>^ Eis aqui o dia, eis que vem; veio a tua ruína; já floresceu a vara, reverdeceu a soberba.

[[v26-7-11]]

^<<v26-7-11,11>>^ A violência se levantou em vara de impiedade: nada restará  deles, nem da sua multidão, nem do seu arruído, nem haverá  lamentação por eles.

[[v26-7-12]]

^<<v26-7-12,12>>^ Vem o tempo, é chegado o dia; o que compra não se alegre, e o que vende não se entristeça: porque a ira ardente está sobre toda a multidão deles.

[[v26-7-13]]

^<<v26-7-13,13>>^ Porque o que vende não tornará a possuir  o que vendeu, ainda que esteja entre os viventes; porque a visão não tornará para trás sobre toda a sua multidão; nem ninguém fortalecerá a sua vida com a sua iniquidade.

[[v26-7-14]]

^<<v26-7-14,14>>^ Já  tocaram a trombeta, e tudo prepararam, mas não há  quem vá à peleja, porque sobre toda a sua multidão está  a minha ardente ira.

[[v26-7-15]]

^<<v26-7-15,15>>^ Fora está a espada, e dentro a peste e a fome: o que estiver  no campo morrerá à espada, e o que estiver na cidade a fome e a peste o consumirão.

[[v26-7-16]]

^<<v26-7-16,16>>^ E só escaparão os que deles se escaparem, mas estarão pelos montes, como pombas dos vales, todos gemendo, cada um por causa da sua maldade.

[[v26-7-17]]

^<<v26-7-17,17>>^ Todas as mãos se enfraquecerão, e todos os joelhos destilarão águas.

[[v26-7-18]]

^<<v26-7-18,18>>^ E se cingirão de sacos, e os cobrirá o tremor; e sobre todos os rostos haverá  vergonha, e sobre todas as suas cabeças calva.

[[v26-7-19]]

^<<v26-7-19,19>>^ A sua prata lançarão pelas ruas, e o seu ouro será como imundícia; nem a sua prata nem o seu ouro os poderá livrar no dia do furor do Senhor; eles não fartarão a sua alma, nem lhes encherão as entranhas, porque isto foi o tropeço da sua maldade.

[[v26-7-20]]

^<<v26-7-20,20>>^ E a glória do seu ornamento, ele a  pôs em magnificência; mas fizeram nela imagens das suas abominações e cousas detestáveis; por isso eu a tornei para eles como uma cousa imunda.

[[v26-7-21]]

^<<v26-7-21,21>>^ E será entregue na mão dos estranhos por presa, e aos ímpios da terra por despojo; e a profanarão.

[[v26-7-22]]

^<<v26-7-22,22>>^ E desviarei deles o meu rosto, e profanarão o meu lugar  oculto; porque entrarão nele saqueadores, e o profanarão.

[[v26-7-23]]

^<<v26-7-23,23>>^ Faze uma  cadeia, porque a terra está cheia de crimes de sangue, e a cidade está cheia de violência.

[[v26-7-24]]

^<<v26-7-24,24>>^ E farei vir os piores de entre as nações, e possuirão as suas casas; e farei cessar a arrogância dos valentes, e os seus lugares santos serão profanados.

[[v26-7-25]]

^<<v26-7-25,25>>^ Vem a destruição; e eles buscarão a paz, mas não há nenhuma.

[[v26-7-26]]

^<<v26-7-26,26>>^ Miséria sobre miséria virá, e se levantará rumor sobre rumor; então buscarão do profeta uma  visão, mas do sacerdote perecerá a lei e dos anciãos o conselho.

[[v26-7-27]]

^<<v26-7-27,27>>^ O rei se lamentará, e o príncipe se vestirá de amargura, e as mãos do povo da terra se molestarão: conforme o seu caminho lhes farei, e com os seus juízos os julgarei; e saberão que eu sou  o Senhor.

'''

xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[&#60; Capítulo Anterior] | <<v26-7-0,Topo>> | xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[Próximo Capítulo &#62;]