include::./index.adoc[]

[[v26-1-0]]
=== Ezequiel, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-1-1]]

^<<v26-1-1,1>>^ E ACONTECEU no trigésimo ano, no quarto mês , no dia  quinto do mês, que estando eu no meio dos cativos junto ao rio Quebar, se abriram os céus, e eu vi visões de Deus.

[[v26-1-2]]

^<<v26-1-2,2>>^ No quinto dia  do mês (no quinto ano do cativeiro do rei Joaquim),

[[v26-1-3]]

^<<v26-1-3,3>>^ Veio expressamente a palavra do Senhor a Ezequiel, filho de Buzi, o sacerdote, na terra dos caldeus, junto ao rio Quebar, e ali esteve sobre ele a mão do Senhor.

[[v26-1-4]]

^<<v26-1-4,4>>^ Olhei, e eis que um vento tempestuoso vinha do norte, e uma grande nuvem, com um fogo a revolver-se; e um resplendor ao redor dela, e no meio uma cousa como de cor de âmbar, que saía  dentre o fogo.

[[v26-1-5]]

^<<v26-1-5,5>>^ E do meio dela saía  a semelhança de quatro animais; e esta era a sua aparência: tinham a semelhança de um homem.

[[v26-1-6]]

^<<v26-1-6,6>>^ E cada um tinha quatro rostos, como também cada um deles quatro asas.

[[v26-1-7]]

^<<v26-1-7,7>>^ E os seus pés eram pés direitos; e as plantas dos seus pés como a planta do pé duma bezerra, e luziam como a cor de cobre polido.

[[v26-1-8]]

^<<v26-1-8,8>>^ E tinham mãos de homem debaixo das suas asas, aos quatro lados; e assim todos  quatro tinham seus rostos e suas asas.

[[v26-1-9]]

^<<v26-1-9,9>>^ Uniam-se as suas asas uma à outra; não se viravam quando andavam; cada qual andava diante do seu rosto.

[[v26-1-10]]

^<<v26-1-10,10>>^ E a semelhança dos seus rostos era como  o rosto de homem; e à mão direita todos os quatro tinham rosto de leão, e à mão esquerda todos os quatro tinham rosto de boi; e também rosto de águia todos os quatro.

[[v26-1-11]]

^<<v26-1-11,11>>^ E os seus rostos e as suas asas eram separados em cima; cada qual tinha duas asas  juntas uma à outra, e duas cobriam os corpos deles.

[[v26-1-12]]

^<<v26-1-12,12>>^ E cada qual andava diante do seu rosto; para onde o espírito havia de ir, iam; não se viravam quando andavam.

[[v26-1-13]]

^<<v26-1-13,13>>^ E, quanto à semelhança dos animais, o seu parecer era como brasas de fogo ardentes, como uma  aparência de tochas; o fogo  corria por entre os animais, e o fogo resplandecia, e do fogo saíam relâmpagos.

[[v26-1-14]]

^<<v26-1-14,14>>^ E os animais corriam, e tornavam, à semelhança dos relâmpagos.

[[v26-1-15]]

^<<v26-1-15,15>>^ E vi os animais: e eis que havia uma roda na terra junto aos animais, para cada um dos seus quatro rostos.

[[v26-1-16]]

^<<v26-1-16,16>>^ O aspecto das rodas, e a obra delas, era como cor de turquesa; e as quatro tinham uma mesma semelhança; e o seu aspecto, e a sua obra, era como se estivera uma roda no meio de outra  roda.

[[v26-1-17]]

^<<v26-1-17,17>>^ Andando elas, andavam pelos quatro lados deles; não se viravam quando andavam.

[[v26-1-18]]

^<<v26-1-18,18>>^ Estas rodas eram tão altas, que metiam medo; e as quatro tinham as suas cambas cheias de olhos ao redor.

[[v26-1-19]]

^<<v26-1-19,19>>^ E, andando os animais, andavam as rodas ao pé deles: e, elevando-se os animais da terra, elevavam-se também  as rodas.

[[v26-1-20]]

^<<v26-1-20,20>>^ Para onde o espírito queria ir, iam; para onde o espírito tinha de ir; e as rodas se elevavam defronte deles, porque o espírito da criatura vivente estava nas rodas.

[[v26-1-21]]

^<<v26-1-21,21>>^ Andando eles, andavam elas , e, parando eles, paravam elas  e, elevando-se eles da terra, elevavam-se também  as rodas defronte deles porque o espírito dos animais estava  nas rodas.

[[v26-1-22]]

^<<v26-1-22,22>>^ E sobre as cabeças dos animais havia uma  semelhança de firmamento, como um aspecto de cristal terrível, estendido por cima, sobre as suas cabeças.

[[v26-1-23]]

^<<v26-1-23,23>>^ E debaixo do firmamento estavam  as suas asas direitas, uma em direção à outra; cada um tinha duas que lhe cobriam o corpo de uma banda; e cada um tinha outras  duas, que os cobriam da outra banda.

[[v26-1-24]]

^<<v26-1-24,24>>^ E, andando eles, ouvi o ruído das suas asas, como o ruído de muitas águas, como a voz do Onipotente, a voz dum estrondo, como o estrépito de um exército; parando eles, abaixavam as suas asas.

[[v26-1-25]]

^<<v26-1-25,25>>^ E ouviu-se uma voz por cima do firmamento, que estava por cima das suas cabeças: parando eles, abaixavam as suas asas.

[[v26-1-26]]

^<<v26-1-26,26>>^ E por cima do firmamento, que estava por cima das suas cabeças, havia  uma semelhança de trono como duma safira; e sobre a semelhança do trono havia como que a semelhança dum homem, no alto, sobre ele.

[[v26-1-27]]

^<<v26-1-27,27>>^ E vi como a cor de âmbar, como o aspecto do fogo pelo interior dele, desde a semelhança dos seus lombos, e daí para cima; e, desde a semelhança dos seus lombos, e daí para baixo, vi como a semelhança de fogo, e um resplendor ao redor dele.

[[v26-1-28]]

^<<v26-1-28,28>>^ Como o aspecto do arco que aparece na nuvem no dia da chuva, assim era o aspecto do resplendor em redor. Este era o aspecto da semelhança da glória do Senhor; e, vendo isto, caí sobre o meu rosto, e ouvi a voz de quem falava.

'''

xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[&#60; Capítulo Anterior] | <<v26-1-0,Topo>> | xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[Próximo Capítulo &#62;]