include::./index.adoc[]

[[v26-31-0]]
=== Ezequiel, 31
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-31-1]]

^<<v26-31-1,1>>^ E SUCEDEU, no ano undécimo, no terceiro mês , ao primeiro do mês, que  veio a mim a palavra do Senhor, dizendo:

[[v26-31-2]]

^<<v26-31-2,2>>^ Filho do homem, dize a Faraó, rei do Egito, e à sua multidão: A quem és semelhante na tua grandeza?

[[v26-31-3]]

^<<v26-31-3,3>>^ Eis que a Assíria era um  cedro no Líbano, de ramos formosos, de sombrosa ramagem e de alta estatura, e o seu topo estava entre os ramos espessos.

[[v26-31-4]]

^<<v26-31-4,4>>^ As águas o fizeram crescer, o abismo o exalçou: as suas correntes corriam em torno da sua plantação, e ela enviava os regatos a todas as árvores do campo.

[[v26-31-5]]

^<<v26-31-5,5>>^ Por isso se elevou a sua estatura sobre todas as árvores do campo, e se multiplicaram os seus ramos, e se alongaram as suas varas, por causa das muitas águas que enviava.

[[v26-31-6]]

^<<v26-31-6,6>>^ Todas as aves do céu se aninhavam nos seus ramos, e todos os animais do campo geravam debaixo dos seus ramos, e todos os grandes povos se assentavam à sua sombra.

[[v26-31-7]]

^<<v26-31-7,7>>^ Assim era ele formoso na sua grandeza, na extensão dos seus ramos, porque a sua raiz estava junto às muitas águas.

[[v26-31-8]]

^<<v26-31-8,8>>^ Os cedros não o podiam escurecer no jardim de Deus; as faias não igualavam os seus ramos, e os castanheiros não eram como os seus renovos: nenhuma árvore no jardim de Deus se assemelhou a ele na sua formosura.

[[v26-31-9]]

^<<v26-31-9,9>>^ Formoso o fiz com a multidão dos seus ramos: e todas as árvores do Éden, que estavam  no jardim de Deus tiveram inveja dele.

[[v26-31-10]]

^<<v26-31-10,10>>^ Portanto assim diz o Senhor Jeová : Como te elevaste na tua  estatura, e se levantou o seu topo no meio dos espessos ramos, e o seu coração se exalçou na sua altura,

[[v26-31-11]]

^<<v26-31-11,11>>^ Eu o entregarei na mão da mais poderosa das nações, que  lhe dará o tratamento merecido ; pela sua impiedade o lançarei fora.

[[v26-31-12]]

^<<v26-31-12,12>>^ E estranhos, os mais formidáveis das nações, o cortaram, e o deixaram: caíram os seus ramos sobre os montes e por todos os vales, e os seus renovos foram quebrados por todas as correntes da terra; e todos os povos da terra se retiraram da sua sombra, e o deixaram.

[[v26-31-13]]

^<<v26-31-13,13>>^ Todas as aves do céu habitavam sobre a sua ruína, e todos os animais do campo se acolheram sob os seus ramos;

[[v26-31-14]]

^<<v26-31-14,14>>^ Para que todas as árvores junto às águas não se exaltem na sua estatura, nem levantem o seu topo no meio dos ramos espessos, nem as que bebem as águas venham a confiar em si, por causa da sua altura; porque todos estão entregues à morte, até à terra mais baixa, no meio dos filhos dos homens, com os que descem à cova.

[[v26-31-15]]

^<<v26-31-15,15>>^ Assim diz o Senhor Jeová : No dia em que ele desceu ao inferno, fiz eu que houvesse luto; fiz cobrir o abismo, por sua causa, e retive as suas correntes, e elas detiveram-se; e cobri o Líbano de preto por causa dele, e todas as árvores do campo por causa dele desfaleceram.

[[v26-31-16]]

^<<v26-31-16,16>>^ Ao som da sua queda fiz tremer as nações, quando o fiz descer ao inferno com os que descem à cova; e todas as árvores do Éden, a flor e o melhor do Líbano, todas as que bebem águas, se consolavam na terra mais baixa.

[[v26-31-17]]

^<<v26-31-17,17>>^ Também estes com ele descerão ao inferno, a juntar-se aos que foram  traspassados a espada: sim, aos que foram  seu braço, e que  estavam assentados à sombra no meio das nações.

[[v26-31-18]]

^<<v26-31-18,18>>^ A quem pois  és semelhante em glória e em grandeza entre as árvores do Éden? Todavia descerás com as árvores do Éden à terra mais baixa; no meio dos incircuncisos jazerás com os que foram  traspassados à espada: este é  Faraó e toda a sua multidão, diz o Senhor Jeová .

'''

xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[&#60; Capítulo Anterior] | <<v26-31-0,Topo>> | xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[Próximo Capítulo &#62;]