include::./index.adoc[]

[[v26-4-0]]
=== Ezequiel, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-4-1]]

^<<v26-4-1,1>>^ TU pois, ó filho do homem, toma um tijolo, e pô-lo-ás diante de ti, e grava nele a cidade de Jerusalém.

[[v26-4-2]]

^<<v26-4-2,2>>^ E põe contra ela um cerco, e edifica contra ela uma fortificação, e levanta contra ela uma tranqueira, e põe contra ela arraiais, e põe-lhe vaivéns em redor.

[[v26-4-3]]

^<<v26-4-3,3>>^ E tu toma uma sertã de ferro, e põe-na por muro de ferro entre ti e a cidade; e dirige para ela o teu rosto, e assim será cercada, e a cercarás; isto servirá  de sinal à casa de Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ Tu também deita-te sobre o teu lado esquerdo, e põe a maldade da casa de Israel sobre ele: conforme  o número dos dias que te deitares sobre ele, levarás as suas maldades.

[[v26-4-5]]

^<<v26-4-5,5>>^ Porque eu te tenho fixado os anos da sua maldade, conforme o número dos dias, trezentos e noventa dias: e levarás a maldade da casa de Israel.

[[v26-4-6]]

^<<v26-4-6,6>>^ E, quando cumprires estes, tornar-te-ás a deitar sobre o teu lado direito, e levarás a maldade da casa de Judá quarenta dias; um dia te dei por cada ano.

[[v26-4-7]]

^<<v26-4-7,7>>^ Dirigirás pois o teu rosto para o cerco de Jerusalém com o teu braço descoberto, e profetizarás contra ela.

[[v26-4-8]]

^<<v26-4-8,8>>^ E eis que porei sobre ti cordas: assim tu não te voltarás dum lado para outro, até que cumpras os dias do teu cerco.

[[v26-4-9]]

^<<v26-4-9,9>>^ E tu toma trigo, e cevada, e favas, e lentilhas, e milho, e aveia, e mete-os num vaso, e faze deles pão: conforme  o número dos dias que te deitares sobre o teu lado, trezentos e noventa dias, comerás disso.

[[v26-4-10]]

^<<v26-4-10,10>>^ E a tua comida, que hás de comer, será  do peso de vinte siclos cada dia; de tempo em tempo a comerás.

[[v26-4-11]]

^<<v26-4-11,11>>^ Também beberás a água por medida, a sexta parte dum him; de tempo em tempo beberás.

[[v26-4-12]]

^<<v26-4-12,12>>^ E o que comeres será como bolos de cevada, e o cozerás com o esterco que sai do homem, diante dos olhos deles.

[[v26-4-13]]

^<<v26-4-13,13>>^ E disse o Senhor: Assim comerão os filhos de Israel o seu pão imundo, entre as nações, para onde serão lançados.

[[v26-4-14]]

^<<v26-4-14,14>>^ Então disse eu: Ah! Senhor, Senhor! eis que a minha alma não foi contaminada, porque nunca comi cousa morta, nem despedaçada, desde a minha mocidade até agora: nem carne abominável entrou na minha boca.

[[v26-4-15]]

^<<v26-4-15,15>>^ E disse-me: Vê, tenho-te dado esterco de vacas, em lugar de esterco de homem; e com ele prepararás o teu pão.

[[v26-4-16]]

^<<v26-4-16,16>>^ Então me disse: Filho do homem, eis que eu torno instável o sustento de pão em Jerusalém, e comerão o pão por peso, e com desgosto; e a água beberão por medida, e com espanto;

[[v26-4-17]]

^<<v26-4-17,17>>^ Para que o pão e a água lhes faltem, e se espantem uns com os outros, e se consumam nas suas maldades.

'''

xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]