include::./index.adoc[]

[[v26-21-0]]
=== Ezequiel, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-21-1]]

^<<v26-21-1,1>>^ E VEIO a mim a palavra do Senhor, dizendo:

[[v26-21-2]]

^<<v26-21-2,2>>^ Filho do homem, dirige o teu rosto contra Jerusalém, e derrama as tuas palavras  contra os santuários, e profetiza contra a terra de Israel.

[[v26-21-3]]

^<<v26-21-3,3>>^ E dize à terra de Israel: Assim diz o Senhor: Eis que sou contra ti, e tirarei a minha espada da bainha, e exterminarei do meio  de ti o justo e o ímpio.

[[v26-21-4]]

^<<v26-21-4,4>>^ E, por isso que hei de exterminar do meio  de ti o justo e o ímpio, a minha espada sairá da bainha contra toda a carne, desde o sul até  ao norte.

[[v26-21-5]]

^<<v26-21-5,5>>^ E saberá toda a carne que eu, o Senhor, tirei a minha espada da bainha: nunca mais voltará a ela.

[[v26-21-6]]

^<<v26-21-6,6>>^ Tu, porém, ó filho do homem, suspira; suspira à vista deles, com quebrantamento dos teus lombos e com amargura.

[[v26-21-7]]

^<<v26-21-7,7>>^ E será que, quando eles te disserem: Por que suspiras tu? dirás: Por causa das novas, porque vêm; e todo o coração desmaiará, e todas as mãos se enfraquecerão, e todo o espírito se angustiará, e todos os joelhos se desfarão em águas; eis que vêm, e se realizarão, diz o Senhor Jeová .

[[v26-21-8]]

^<<v26-21-8,8>>^ E veio a mim a palavra do Senhor, dizendo:

[[v26-21-9]]

^<<v26-21-9,9>>^ Filho do homem, profetiza, e dize: Assim diz o Senhor: dize: A espada a espada está afiada, e também açacalada.

[[v26-21-10]]

^<<v26-21-10,10>>^ Para matar está afiada, para reluzir está açacalada: alegrar-nos-emos pois? a  vara do meu filho é que despreza todo o madeiro.

[[v26-21-11]]

^<<v26-21-11,11>>^ E foi dada a açacalar, para ser manejada: esta espada está afiada, e está açacalada, para ser posta na mão do matador.

[[v26-21-12]]

^<<v26-21-12,12>>^ Grita e geme, ó filho do homem, porque ela será contra o meu povo, contra todos os príncipes de Israel: espantos terá o meu povo por causa da espada; bate pois na tua coxa.

[[v26-21-13]]

^<<v26-21-13,13>>^ Porque se faz uma prova, e que seria se não existisse a própria vara desprezadora? diz o Senhor Jeová .

[[v26-21-14]]

^<<v26-21-14,14>>^ Tu pois, ó filho do homem, profetiza, e bate com as mãos uma na outra; porque a espada até à terceira vez se dobrará: a espada é  dos atravessados, dos mortalmente feridos, e entrará neles até às recâmaras.

[[v26-21-15]]

^<<v26-21-15,15>>^ Para que desmaie o coração, e se multipliquem os tropeços, contra todas as suas portas pus a ponta da espada, que foi feita como raio, e está reservada para matar!

[[v26-21-16]]

^<<v26-21-16,16>>^ Ó espada , une-te, vira-te para a direita, prepara-te, vira-te para a esquerda, para onde quer que o teu rosto se dirigir.

[[v26-21-17]]

^<<v26-21-17,17>>^ E também eu baterei com as minhas mãos uma na outra, e farei descansar a minha indignação: eu, o Senhor, falei.

[[v26-21-18]]

^<<v26-21-18,18>>^ E veio a mim a palavra do Senhor dizendo:

[[v26-21-19]]

^<<v26-21-19,19>>^ Tu pois, ó filho do homem, propõe dois caminhos, por onde venha a espada do rei de Babilônia: ambos procederão de uma mesma terra, e escolhe um lugar; no cimo do caminho da cidade e o escolhe.

[[v26-21-20]]

^<<v26-21-20,20>>^ Um caminho proporás, por onde virá a espada contra Rabá dos filhos de Amom, e contra Judá, em Jerusalém, a fortificada.

[[v26-21-21]]

^<<v26-21-21,21>>^ Porque o rei de Babilônia parará na encruzilhada, no cimo dos dois caminhos para fazer adivinhações: aguçará as suas  frechas, consultará os terafins, atentando nas entranhas.

[[v26-21-22]]

^<<v26-21-22,22>>^ À sua direita estará a adivinhação sobre Jerusalém, para ordenar os aríetes, para abrir a boca à matança, para levantar a voz com júbilo, para pôr os aríetes contra as portas, para levantar tranqueiras, para edificar baluartes.

[[v26-21-23]]

^<<v26-21-23,23>>^ Isto será aos olhos deles como adivinhação vã, pois foram ajuramentados com  juramentos entre eles; mas ele se lembrará da maldade, para que sejam apanhados.

[[v26-21-24]]

^<<v26-21-24,24>>^ Portanto assim diz o Senhor Jeová : Visto que me fazeis lembrar da vossa maldade, descobrindo-se as vossas prevaricações, aparecendo os vossos pecados em todos os vossos atos visto que viestes em memória, sereis apanhados na mão.

[[v26-21-25]]

^<<v26-21-25,25>>^ E tu, ó profano e ímpio príncipe de Israel, cujo dia virá no tempo da extrema maldade,

[[v26-21-26]]

^<<v26-21-26,26>>^ Assim diz o Senhor Jeová : Tira o diadema, e levanta a coroa; esta não será a mesma: exalta ao humilde, e humilha ao soberbo.

[[v26-21-27]]

^<<v26-21-27,27>>^ Ao revés, ao revés, ao revés a porei, e ela não será mais, até que venha aquele a quem pertence de direito, e a ele  a darei.

[[v26-21-28]]

^<<v26-21-28,28>>^ E tu, ó filho do homem, profetiza e dize: Assim diz o Senhor Jeová  acerca dos filhos de Amom, e acerca do seu desprezo: dize pois: A espada, a espada está  desembainhada, açacalada para a matança, para consumir, para reluzir;

[[v26-21-29]]

^<<v26-21-29,29>>^ Entretanto que te veem vaidade, entretanto que te adivinham mentiras para te porem no pescoço dos ímpios, mortalmente feridos, cujo dia virá no tempo da extrema maldade.

[[v26-21-30]]

^<<v26-21-30,30>>^ Torne a tua espada  à sua bainha: no lugar em que foste criado, na terra do teu nascimento, te julgarei.

[[v26-21-31]]

^<<v26-21-31,31>>^ E derramarei sobre ti a minha indignação, assoprarei contra ti o fogo do meu furor, entregar-te-ei nas mãos dos homens brutais, inventores de destruição.

[[v26-21-32]]

^<<v26-21-32,32>>^ Ao fogo servirás de pasto: o teu sangue estará no meio da terra: não virás em memória; porque eu, o Senhor, o disse.

'''

xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[&#60; Capítulo Anterior] | <<v26-21-0,Topo>> | xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[Próximo Capítulo &#62;]