include::./index.adoc[]

[[v26-45-0]]
=== Ezequiel, 45
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-45-1]]

^<<v26-45-1,1>>^ QUANDO pois repartirdes a terra por sortes em herança, oferecereis uma oferta ao Senhor, um lugar santo da terra: o comprimento será  de vinte e cinco mil canas , e a largura de dez mil: este será  santo em todo o seu contorno ao redor.

[[v26-45-2]]

^<<v26-45-2,2>>^ E será o santuário de quinhentas com mais quinhentas, em quadrado, e terá em redor um arrabalde de cinquenta côvados.

[[v26-45-3]]

^<<v26-45-3,3>>^ E desta medida medirás um comprimento de vinte e cinco mil côvados , e uma largura de dez mil: e ali estará o santuário e  o lugar santíssimo.

[[v26-45-4]]

^<<v26-45-4,4>>^ Este será  o lugar santo da terra; ele será para os sacerdotes, ministros do santuário, que dele se aproximam para servir ao Senhor; e lhes servirá de lugar para casas, e de lugar santo para o santuário.

[[v26-45-5]]

^<<v26-45-5,5>>^ E terão os levitas, ministros da casa, por possessão sua, vinte e cinco mil medidas  de comprimento, para  vinte câmaras.

[[v26-45-6]]

^<<v26-45-6,6>>^ E para  possessão da cidade, de largura dareis cinco mil canas , e de comprimento vinte e cinco mil, defronte da oferta santa: o que  será para toda a casa de Israel.

[[v26-45-7]]

^<<v26-45-7,7>>^ O príncipe porém terá  a sua parte  desta e da outra banda da santa oferta, e da possessão da cidade, diante da santa oferta, e diante da possessão da cidade, na esquina ocidental para o ocidente, e na esquina oriental para o oriente; e será  o comprimento, defronte duma das partes, desde o termo ocidental até ao termo oriental.

[[v26-45-8]]

^<<v26-45-8,8>>^ E esta terra será a sua possessão em Israel; e os meus príncipes nunca mais oprimirão o meu povo, antes deixarão a terra à casa de Israel, conforme as suas tribos.

[[v26-45-9]]

^<<v26-45-9,9>>^ Assim diz o Senhor Jeová : Basta já, ó príncipes de Israel; afastai a violência e a assolação, e praticai juízo e justiça: tirai as vossas imposições do meu povo, diz o Senhor Jeová .

[[v26-45-10]]

^<<v26-45-10,10>>^ Balanças justas, e efa justo, e bato justo tereis.

[[v26-45-11]]

^<<v26-45-11,11>>^ O efa e o bato serão duma mesma medida, de maneira  que o bato contenha a décima parte do ômer, e o efa a décima parte do ômer; conforme o ômer será a sua medida.

[[v26-45-12]]

^<<v26-45-12,12>>^ E o siclo será  de vinte geras: vinte siclos, vinte e cinco siclos, e  quinze siclos vos servirão dum arrátel.

[[v26-45-13]]

^<<v26-45-13,13>>^ Esta será  a oferta que haveis de fazer: a sexta parte dum efa de cada  ômer de trigo; também dareis a sexta parte dum efa de cada  ômer de cevada.

[[v26-45-14]]

^<<v26-45-14,14>>^ Quanto ao estatuto do azeite, de cada  bato de azeite oferecereis  a décima parte do bato tirado  dum coro, que é  um ômer de dez batos; porque dez batos fazem  um ômer.

[[v26-45-15]]

^<<v26-45-15,15>>^ E um cordeiro do rebanho, de cada duzentos, da mais regada terra de Israel, para oferta de manjares, e para holocausto, e para sacrifício pacífico; para que façam expiação por eles, diz o Senhor Jeová .

[[v26-45-16]]

^<<v26-45-16,16>>^ Todo o povo da terra concorrerá para esta oferta, pelo príncipe de Israel.

[[v26-45-17]]

^<<v26-45-17,17>>^ E estarão a cargo do príncipe os holocaustos, e as ofertas de manjares, e as libações, nas festas, e nas luas novas, e nos sábados, em todas as solenidades da casa de Israel: ele fará a expiação pelo pecado, e a oferta de manjares, e o holocausto, e os sacrifícios pacíficos, para fazer expiação pela casa de Israel.

[[v26-45-18]]

^<<v26-45-18,18>>^ Assim diz o Senhor Jeová : No primeiro mês , no primeiro dia  do mês, tomarás um bezerro sem mancha, e purificarás o santuário.

[[v26-45-19]]

^<<v26-45-19,19>>^ E o sacerdote tomará do sangue do sacrifício pela expiação, e porá dele  nas ombreiras da casa, e nas quatro esquinas da listra do altar, e nas ombreiras da porta do átrio interior.

[[v26-45-20]]

^<<v26-45-20,20>>^ Assim também farás no sétimo dia  do mês, por causa dos que erram, e por causa dos símplices: assim expiareis a casa.

[[v26-45-21]]

^<<v26-45-21,21>>^ No primeiro mês , no dia catorze do mês, tereis a páscoa, uma  festa de sete dias; pão asmo se comerá.

[[v26-45-22]]

^<<v26-45-22,22>>^ E o príncipe no mesmo dia, por si e por todo o povo da terra, preparará um bezerro de expiação pelo pecado.

[[v26-45-23]]

^<<v26-45-23,23>>^ E nos sete dias da festa preparará um holocausto ao Senhor, de  sete bezerros e sete carneiros sem mancha, cada dia durante  os sete dias; e o sacrifício de expiação dum bode cada dia.

[[v26-45-24]]

^<<v26-45-24,24>>^ Também preparará uma oferta de manjares: um efa por cada bezerro, e um efa por cada carneiro, e um him de azeite por cada efa.

[[v26-45-25]]

^<<v26-45-25,25>>^ No sétimo mês , no dia quinze do mês, na festa, fará o mesmo todos  os sete dias, tanto o sacrifício pela expiação, como o holocausto, e como a oferta de manjares, e como o azeite.

'''

xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[&#60; Capítulo Anterior] | <<v26-45-0,Topo>> | xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[Próximo Capítulo &#62;]