include::./index.adoc[]

[[v26-35-0]]
=== Ezequiel, 35
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v26-35-1]]

^<<v26-35-1,1>>^ E VEIO a mim a palavra do Senhor, dizendo:

[[v26-35-2]]

^<<v26-35-2,2>>^ Filho do homem, dirige o teu rosto contra o monte de Seir, e profetiza contra ele.

[[v26-35-3]]

^<<v26-35-3,3>>^ E dize-lhe: Assim diz o Senhor Jeová : Eis que eu estou contra ti, ó monte de Seir, e estenderei a minha mão contra ti, e te porei em  assolação e espanto.

[[v26-35-4]]

^<<v26-35-4,4>>^ As tuas cidades porei em  solidão, e tu te tornarás em  assolação; e saberás que eu sou  o Senhor.

[[v26-35-5]]

^<<v26-35-5,5>>^ Pois que guardas inimizade perpétua, e abandonaste os filhos de Israel à violência da espada no tempo da extrema iniquidade.

[[v26-35-6]]

^<<v26-35-6,6>>^ Por isso vivo eu, diz o Senhor Jeová , que te preparei para sangue, e o sangue te perseguirá; visto que não aborreceste o sangue, o sangue te perseguirá.

[[v26-35-7]]

^<<v26-35-7,7>>^ E farei do monte de Seir uma extrema assolação, e exterminarei dele o que por ele passa, e o que por ele volta.

[[v26-35-8]]

^<<v26-35-8,8>>^ E encherei os seus montes dos seus traspassados; nos teus outeiros, e nos teus vales, e em todas as tuas correntes cairão os traspassados à espada.

[[v26-35-9]]

^<<v26-35-9,9>>^ Em  assolações perpétuas te porei, e as tuas cidades nunca mais serão habitadas: assim sabereis que eu sou  o Senhor.

[[v26-35-10]]

^<<v26-35-10,10>>^ Visto como dizes: Os dois povos e as duas terras serão meus, e os possuiremos, sendo que o Senhor se achava ali.

[[v26-35-11]]

^<<v26-35-11,11>>^ Portanto, vivo eu, diz o Senhor Jeová , que usarei conforme a tua ira, e conforme a tua inveja, de que usaste, no teu ódio contra eles; e serei conhecido deles, quando te julgar.

[[v26-35-12]]

^<<v26-35-12,12>>^ E saberás que eu, o Senhor, ouvi todas as tuas blasfêmias, que proferiste contra os montes de Israel, dizendo: Já  estão assolados, a nós nos são entregues por pasto.

[[v26-35-13]]

^<<v26-35-13,13>>^ Vós vos engrandecestes contra mim com a vossa boca, e multiplicastes as vossas palavras contra mim: eu o ouvi.

[[v26-35-14]]

^<<v26-35-14,14>>^ Assim diz o Senhor Jeová : Enquanto se alegra toda a terra, a ti te porei em assolação.

[[v26-35-15]]

^<<v26-35-15,15>>^ Como te alegraste com a herança da casa de Israel, porque foi assolada, assim te farei a ti: assolado serás, ó monte de Seir, e todo o Edom, sim, todo; e saberão que eu sou  o Senhor.

'''

xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[&#60; Capítulo Anterior] | <<v26-35-0,Topo>> | xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[Próximo Capítulo &#62;]