include::./index.adoc[]

[[v61-2-0]]
=== 2 Pedro, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v61-2-1]]

^<<v61-2-1,1>>^ E TAMBÉM houve entre o povo falsos profetas, como entre vós haverá também falsos doutores, que introduzirão encobertamente heresias de perdição, e negarão o Senhor que os resgatou, trazendo sobre si mesmos repentina perdição.

[[v61-2-2]]

^<<v61-2-2,2>>^ E muitos seguirão as suas dissoluções, pelos quais será blasfemado o caminho da verdade.

[[v61-2-3]]

^<<v61-2-3,3>>^ E por avareza farão de vós negócio com palavras fingidas; sobre os quais já de largo tempo não será tardia a sentença, e a sua perdição não dormita.

[[v61-2-4]]

^<<v61-2-4,4>>^ Porque, se Deus não perdoou aos anjos que pecaram, mas, havendo-os lançado no inferno, os entregou às cadeias da escuridão, ficando reservados para o juízo;

[[v61-2-5]]

^<<v61-2-5,5>>^ E não perdoou ao mundo antigo, mas guardou a Noé, pregoeiro da justiça, com mais sete pessoas, ao trazer o dilúvio sobre o mundo dos ímpios;

[[v61-2-6]]

^<<v61-2-6,6>>^ E condenou à subversão as cidades de Sodoma e Gomorra, reduzindo-as a cinza, e pondo- as  para exemplo aos que vivessem impiamente;

[[v61-2-7]]

^<<v61-2-7,7>>^ E livrou o justo Ló, enfadado da vida dissoluta dos homens abomináveis.

[[v61-2-8]]

^<<v61-2-8,8>>^ (Porque este justo, habitando entre eles, afligia todos os dias a sua  alma justa, pelo que via e ouvia sobre as suas obras injustas);

[[v61-2-9]]

^<<v61-2-9,9>>^ Assim, sabe o Senhor livrar da tentação os piedosos, e reservar os injustos para o dia de juízo, para  serem castigados;

[[v61-2-10]]

^<<v61-2-10,10>>^ Mas principalmente aqueles que segundo a carne andam em concupiscências de imundícia, e desprezam as dominações; atrevidos, obstinados, não receando blasfemar das dignidades;

[[v61-2-11]]

^<<v61-2-11,11>>^ Enquanto os anjos, sendo maiores em força e poder não pronunciam contra eles juízo blasfemo diante do Senhor.

[[v61-2-12]]

^<<v61-2-12,12>>^ Mas estes, como animais irracionais, que seguem a natureza, feitos para serem presos e mortos, blasfemando do que não entendem, perecerão na sua corrupção,

[[v61-2-13]]

^<<v61-2-13,13>>^ Recebendo o galardão da injustiça; pois que tais homens  têm prazer nos deleites quotidianos; nódoas são eles e máculas, deleitando-se em seus enganos, quando se banqueteiam convosco;

[[v61-2-14]]

^<<v61-2-14,14>>^ Tendo os olhos cheios de adultério, e não cessando de pecar, engodando as almas inconstantes, tendo o coração exercitado na avareza, filhos de maldição;

[[v61-2-15]]

^<<v61-2-15,15>>^ Os quais, deixando o caminho direito, erraram seguindo o caminho de Balaão, filho  de Bosor, que amou o prêmio da injustiça;

[[v61-2-16]]

^<<v61-2-16,16>>^ Mas teve a repreensão da sua transgressão; o mudo jumento, falando com voz humana, impediu a loucura do profeta.

[[v61-2-17]]

^<<v61-2-17,17>>^ Estes são fontes sem água, nuvens levadas pela força do vento: para os quais a escuridão das trevas eternamente se reserva.

[[v61-2-18]]

^<<v61-2-18,18>>^ Porque, falando coisas  mui arrogantes de vaidades, engodam com as concupiscências da carne, e com dissoluções, aqueles que se estavam afastando dos que andam em erro:

[[v61-2-19]]

^<<v61-2-19,19>>^ Prometendo-lhes liberdade, sendo eles mesmos servos da corrupção. Porque de quem alguém é vencido, do tal faz-se também servo.

[[v61-2-20]]

^<<v61-2-20,20>>^ Porquanto se, depois de terem escapado das corrupções do mundo, pelo conhecimento do Senhor e Salvador Jesus Cristo, forem outra vez envolvidos nelas e vencidos, tornou-se-lhes o último estado pior do que o primeiro.

[[v61-2-21]]

^<<v61-2-21,21>>^ Porque melhor lhes fora não conhecerem o caminho da justiça, do que, conhecendo- o , desviarem-se do santo mandamento que lhes fora dado;

[[v61-2-22]]

^<<v61-2-22,22>>^ Deste modo sobreveio- lhes  o que por um verdadeiro provérbio se diz : O cão voltou ao seu próprio vômito, e a porca lavada ao espojadouro de lama.

'''

xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[&#60; Capítulo Anterior] | <<v61-2-0,Topo>> | xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[Próximo Capítulo &#62;]