include::./index.adoc[]

[[v38-6-0]]
=== Zacarias, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v38-6-1]]

^<<v38-6-1,1>>^ E OUTRA vez levantei os meus olhos, e olhei, e vi quatro carros que saíram dentre dois montes, e estes montes eram  montes de metal.

[[v38-6-2]]

^<<v38-6-2,2>>^ No primeiro carro eram os cavalos vermelhos, e no segundo carro cavalos pretos.

[[v38-6-3]]

^<<v38-6-3,3>>^ E no terceiro carro cavalos brancos, e no quarto carro cavalos grisalhos e fortes.

[[v38-6-4]]

^<<v38-6-4,4>>^ E respondi, e disse ao anjo que falava comigo: Que é  isto, Senhor meu?

[[v38-6-5]]

^<<v38-6-5,5>>^ E o anjo respondeu, e me disse: Estes são os quatro ventos do céu, saindo donde estavam perante o Senhor de toda a terra.

[[v38-6-6]]

^<<v38-6-6,6>>^ O carro  em que estão os cavalos pretos, sai para a terra do norte, e os brancos saem atrás deles, e os grisalhos saem para a terra do sul.

[[v38-6-7]]

^<<v38-6-7,7>>^ E os cavalos  fortes saíam, e procuravam ir por diante, para andarem pela terra. E ele disse: Ide, andai pela terra. E andavam pela terra.

[[v38-6-8]]

^<<v38-6-8,8>>^ E me chamou, e me falou, dizendo: Eis que aqueles que saíram para a terra do norte fizeram repousar o meu Espírito na terra do norte.

[[v38-6-9]]

^<<v38-6-9,9>>^ E a palavra do Senhor veio a mim, dizendo:

[[v38-6-10]]

^<<v38-6-10,10>>^ Recebe dos que foram levados cativos: de Heldai, de Tobias, e de Jedaías (e vem naquele dia, e entra na casa de Josias, filho de Sofonias), os quais vieram de Babilônia:

[[v38-6-11]]

^<<v38-6-11,11>>^ Recebe, digo, prata e ouro, e faze coroas, e põe-nas na cabeça de Josué, filho de Josadaque, sumo sacerdote.

[[v38-6-12]]

^<<v38-6-12,12>>^ E fala-lhe, dizendo: Assim fala e diz o Senhor dos Exércitos: Eis aqui o homem cujo nome é Renovo: ele brotará do seu lugar, e edificará o templo do Senhor.

[[v38-6-13]]

^<<v38-6-13,13>>^ Ele mesmo edificará o templo do Senhor, e levará a glória, e assentar-se-á, e dominará no seu trono, e será sacerdote no seu trono, e conselho de paz haverá entre eles ambos.

[[v38-6-14]]

^<<v38-6-14,14>>^ E estas coroas serão de Helém, e de Tobias, e de Jedaías, e de Hem, filho de Sofonias, como um memorial no templo do Senhor.

[[v38-6-15]]

^<<v38-6-15,15>>^ E aqueles que estão longe virão, e edificarão no templo do Senhor, e vós sabereis que o Senhor dos Exércitos me tem enviado a vós; e isto acontecerá, se ouvirdes mui atentos a voz do Senhor vosso Deus.

'''

xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[Próximo Capítulo &#62;]