include::./index.adoc[]

[[v38-7-0]]
=== Zacarias, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v38-7-1]]

^<<v38-7-1,1>>^ ACONTECEU pois, no ano quarto do rei Dario, que a palavra do Senhor veio a Zacarias, no dia  quarto do nono mês, em Chisleu.

[[v38-7-2]]

^<<v38-7-2,2>>^ Quando de Betel foram enviados Saresar, e Regem-Meleque, e os seus homens, para suplicarem o favor do Senhor,

[[v38-7-3]]

^<<v38-7-3,3>>^ Disseram aos sacerdotes, que estavam  na casa do Senhor dos Exércitos, e aos profetas: Chorarei eu no quinto mês, separando-me, como o tenho feito por tantos anos?

[[v38-7-4]]

^<<v38-7-4,4>>^ Então a palavra do Senhor dos Exércitos veio a mim, dizendo:

[[v38-7-5]]

^<<v38-7-5,5>>^ Fala a todo o povo desta terra, e aos sacerdotes, dizendo: Quando jejuastes, e pranteastes, no quinto e no sétimo mês , durante estes setenta anos, jejuastes vós para mim, mesmo para mim?

[[v38-7-6]]

^<<v38-7-6,6>>^ Ou quando comestes, e quando bebestes, não foi para vós mesmos que comestes e bebestes?

[[v38-7-7]]

^<<v38-7-7,7>>^ Não ouvistes  vós as palavras que o Senhor pregou pelo ministério dos profetas precedentes, quando Jerusalém estava habitada e quieta, com as suas cidades ao redor dela, e o sul e a campina eram habitados?

[[v38-7-8]]

^<<v38-7-8,8>>^ E a palavra do Senhor veio a Zacarias, dizendo:

[[v38-7-9]]

^<<v38-7-9,9>>^ Assim falou o Senhor dos Exércitos, dizendo: Executai juízo verdadeiro, mostrai piedade e misericórdia cada um a seu irmão;

[[v38-7-10]]

^<<v38-7-10,10>>^ E não oprimais a viúva, nem o órfão, nem o estrangeiro, nem o pobre, nem intente o mal cada um contra o seu irmão no seu coração.

[[v38-7-11]]

^<<v38-7-11,11>>^ Eles, porém, não quiseram escutar, e me deram o ombro rebelde, e ensurdeceram os seus ouvidos, para que não ouvissem.

[[v38-7-12]]

^<<v38-7-12,12>>^ Sim, fizeram os seus corações duros  como diamante, para que não ouvissem a lei, nem as palavras que o Senhor dos Exércitos enviara pelo seu Espírito mediante os profetas precedentes; donde veio a grande ira do Senhor dos Exércitos.

[[v38-7-13]]

^<<v38-7-13,13>>^ E aconteceu que , como ele clamou, e eles não ouviram, assim também eles clamarão, mas eu não ouvirei, diz o Senhor dos Exércitos.

[[v38-7-14]]

^<<v38-7-14,14>>^ E os espalharei com tempestade entre todas as nações, que eles não conheceram, e a terra será assolada atrás deles, de sorte que ninguém passará por ela, nem se voltará porque têm feito da terra desejada uma desolação.

'''

xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[&#60; Capítulo Anterior] | <<v38-7-0,Topo>> | xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[Próximo Capítulo &#62;]