include::./index.adoc[]

[[v38-12-0]]
=== Zacarias, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v38-12-1]]

^<<v38-12-1,1>>^ PESO da palavra do Senhor sobre Israel: Fala o Senhor, o que estende o céu, e que funda a terra, e que forma o espírito do homem dentro dele.

[[v38-12-2]]

^<<v38-12-2,2>>^ Eis que porei a Jerusalém como  um copo de tremor para todos os povos em redor, e também para Judá, quando do cerco contra Jerusalém.

[[v38-12-3]]

^<<v38-12-3,3>>^ E acontecerá naquele dia que farei de Jerusalém uma pedra pesada para todos os povos; todos os que carregarem com ela certamente serão despedaçados, e ajuntar-se-ão contra ela todas as nações da terra.

[[v38-12-4]]

^<<v38-12-4,4>>^ Naquele dia, diz o Senhor, ferirei de espanto a todos os cavalos, e de loucura os que montam neles; e sobre a casa de Judá abrirei os meus olhos, e ferirei de cegueira a todos os cavalos dos povos.

[[v38-12-5]]

^<<v38-12-5,5>>^ Então os chefes de Judá dirão no seu coração: A minha força são  os habitantes de Jerusalém e o Senhor dos Exércitos, seu Deus.

[[v38-12-6]]

^<<v38-12-6,6>>^ Naquele dia porei os chefes de Judá como uma brasa ardente debaixo da lenha, e como um facho entre gavelas; e à direita e à esquerda consumirão a todos os povos em redor, e Jerusalém será habitada outra vez no seu próprio lugar, mesmo em Jerusalém.

[[v38-12-7]]

^<<v38-12-7,7>>^ E o Senhor primeiramente salvará as tendas de Judá, para que a glória da casa de Davi e a glória dos habitantes de Jerusalém não seja exaltada acima de Judá.

[[v38-12-8]]

^<<v38-12-8,8>>^ Naquele dia o Senhor amparará os habitantes de Jerusalém; e o que dentre eles tropeçar naquele dia será como Davi, e a casa de Davi será  como Deus, como o anjo do Senhor diante deles.

[[v38-12-9]]

^<<v38-12-9,9>>^ E acontecerá, naquele dia, que procurarei destruir todas as nações que vierem contra Jerusalém;

[[v38-12-10]]

^<<v38-12-10,10>>^ E sobre a casa de Davi, e sobre os habitantes de Jerusalém, derramarei o Espírito de graça e de súplicas; e olharão para mim, a quem traspassaram; e o prantearão como quem pranteia por um unigênito; e chorarão amargamente por ele, como se chora amargamente pelo primogênito.

[[v38-12-11]]

^<<v38-12-11,11>>^ Naquele dia será grande o pranto em Jerusalém, como o pranto de Hadadrimom no vale de Megido.

[[v38-12-12]]

^<<v38-12-12,12>>^ E a terra pranteará, cada linhagem à parte: a linhagem da casa de Davi à parte, e suas mulheres à parte, e a linhagem da casa de Natã à parte, e suas mulheres à parte;

[[v38-12-13]]

^<<v38-12-13,13>>^ A linhagem da casa de Levi à parte, e suas mulheres à parte; a linhagem de Simei à parte, e suas mulheres à parte.

[[v38-12-14]]

^<<v38-12-14,14>>^ Todas as mais linhagens, cada linhagem à parte, e suas mulheres à parte.

'''

xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[&#60; Capítulo Anterior] | <<v38-12-0,Topo>> | xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[Próximo Capítulo &#62;]