include::./index.adoc[]

[[v38-14-0]]
=== Zacarias, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v38-14-1]]

^<<v38-14-1,1>>^ EIS que vem um dia do Senhor, em que os teus despojos se repartirão no meio de ti.

[[v38-14-2]]

^<<v38-14-2,2>>^ Porque eu ajuntarei todas as nações para a peleja contra Jerusalém; e a cidade será tomada, e as casas serão saqueadas, e as mulheres forçadas; e metade da cidade sairá para o cativeiro, mas o resto do povo não será expulso da cidade.

[[v38-14-3]]

^<<v38-14-3,3>>^ E o Senhor sairá, e pelejará contra estas nações, como no dia em que pelejou no dia da batalha.

[[v38-14-4]]

^<<v38-14-4,4>>^ E naquele dia estarão os seus pés sobre o monte das Oliveiras, que está defronte de Jerusalém para o oriente; e o monte das Oliveiras será fendido pelo meio, para o oriente e para o ocidente, e haverá um vale muito grande; e metade do monte se apartará para o norte, e a outra  metade dele para o sul.

[[v38-14-5]]

^<<v38-14-5,5>>^ E fugireis pelo vale dos meus montes (porque o vale dos montes chegará até Asel), e fugireis assim como fugistes do terremoto nos dias de Uzias, rei de Judá: então virá o Senhor meu Deus, e todos  os santos contigo, ó Senhor.

[[v38-14-6]]

^<<v38-14-6,6>>^ E acontecerá naquele dia, que não haverá preciosa luz nem espessa escuridão.

[[v38-14-7]]

^<<v38-14-7,7>>^ Mas será um dia conhecido do Senhor; nem dia nem noite será; e acontecerá que no tempo da tarde haverá luz.

[[v38-14-8]]

^<<v38-14-8,8>>^ Naquele dia também acontecerá que correrão de Jerusalém águas vivas, metade delas para o mar oriental, e metade delas até ao mar ocidental: no estio e no inverno sucederá isto.

[[v38-14-9]]

^<<v38-14-9,9>>^ E o Senhor será rei sobre toda a terra: naquele dia um será o Senhor, e um será o seu nome.

[[v38-14-10]]

^<<v38-14-10,10>>^ Toda a terra em redor se tornará em planície, desde Geba até Rimom, ao do sul de Jerusalém; ela será exalçada, e habitada no seu lugar, desde a porta de Benjamim até ao lugar da primeira porta, até à porta da esquina, e desde a torre de Hananeel até aos lagares do rei.

[[v38-14-11]]

^<<v38-14-11,11>>^ E habitarão nela, e não haverá mais anátema, porque Jerusalém habitará segura.

[[v38-14-12]]

^<<v38-14-12,12>>^ E esta será a praga com que o Senhor ferirá a todos os povos que guerrearam contra Jerusalém: a sua carne será consumida, estando eles de pé, e lhes apodrecerão os olhos nas suas órbitas, e lhes apodrecerá a língua na sua boca.

[[v38-14-13]]

^<<v38-14-13,13>>^ Naquele dia também acontecerá que haverá uma grande perturbação do Senhor entre eles; porque pegará cada um na mão do seu companheiro, e alçar-se-á a mão de cada um contra a mão do seu companheiro.

[[v38-14-14]]

^<<v38-14-14,14>>^ E também Judá pelejará em Jerusalém, e se ajuntarão em redor as riquezas de todas as nações, ouro e prata e vestidos em grande abundância.

[[v38-14-15]]

^<<v38-14-15,15>>^ E será a praga dos cavalos, dos machos, dos camelos e dos jumentos, e de todos os animais que estiverem naqueles exércitos, como foi a praga deles.

[[v38-14-16]]

^<<v38-14-16,16>>^ E acontecerá que, todos os que restarem de todas as nações que vieram contra Jerusalém, subirão de ano em ano para adorarem o Rei, o Senhor dos Exércitos, e celebrarem a festa das cabanas.

[[v38-14-17]]

^<<v38-14-17,17>>^ E acontecerá que  se alguma das famílias da terra não subir a Jerusalém, para adorar o Rei, o Senhor dos Exércitos, não virá sobre ela a chuva.

[[v38-14-18]]

^<<v38-14-18,18>>^ E, se a família dos egípcios não subir, nem vier, virá sobre eles  a praga com  que o Senhor ferirá as nações que não subirem a celebrar a festa das cabanas.

[[v38-14-19]]

^<<v38-14-19,19>>^ Este será o castigo dos egípcios e o castigo de todas as nações que não subirem a celebrar a festa das cabanas.

[[v38-14-20]]

^<<v38-14-20,20>>^ Naquele dia se gravará sobre as campainhas dos cavalos: Santidade ao Senhor : e as panelas na casa do Senhor serão como as bacias diante do altar.

[[v38-14-21]]

^<<v38-14-21,21>>^ E todas as panelas em Jerusalém e Judá serão consagradas ao Senhor dos Exércitos, e todos os que sacrificarem virão, e delas tomarão, e nelas cozerão: e não haverá mais cananita na casa do Senhor dos Exércitos naquele dia.

'''

xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[&#60; Capítulo Anterior] | <<v38-14-0,Topo>> | xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[Próximo Capítulo &#62;]