include::./index.adoc[]

[[v38-4-0]]
=== Zacarias, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v38-4-1]]

^<<v38-4-1,1>>^ E TORNOU o anjo que falava comigo, e me despertou, como a um  homem que é despertado do seu sono,

[[v38-4-2]]

^<<v38-4-2,2>>^ E me disse: Que vês? E eu disse: Olho, e eis um castiçal todo de ouro, e um vaso de azeite no cimo, com as suas sete lâmpadas; e cada lâmpada posta no cimo tinha sete canudos.

[[v38-4-3]]

^<<v38-4-3,3>>^ E, por cima dele, duas oliveiras, uma à direita do vaso de azeite, e outra à sua esquerda.

[[v38-4-4]]

^<<v38-4-4,4>>^ E falei, e disse ao anjo que falava comigo, dizendo: Senhor meu, que é  isto?

[[v38-4-5]]

^<<v38-4-5,5>>^ Então respondeu o anjo que falava comigo, e me disse: Não sabes tu o que isto é? E eu disse: Não, Senhor meu.

[[v38-4-6]]

^<<v38-4-6,6>>^ E respondeu, e me falou, dizendo: Esta é  a palavra do Senhor a Zorobabel, dizendo: Não por força nem por violência, mas pelo meu Espírito, diz o Senhor dos Exércitos.

[[v38-4-7]]

^<<v38-4-7,7>>^ Quem és  tu, ó monte grande? diante de Zorobabel serás uma  campina; porque ele trará a primeira pedra com aclamações: Graça, graça a ela.

[[v38-4-8]]

^<<v38-4-8,8>>^ E a palavra do Senhor veio de novo a mim dizendo:

[[v38-4-9]]

^<<v38-4-9,9>>^ As mãos de Zorobabel têm fundado esta casa, também as suas mãos a acabarão, para que saibais que o Senhor dos Exércitos me enviou a vós.

[[v38-4-10]]

^<<v38-4-10,10>>^ Porque, quem despreza o dia das cousas pequenas? pois esses se alegrarão, vendo o prumo na mão de Zorobabel: os sete olhos do Senhor, que discorrem por toda a terra.

[[v38-4-11]]

^<<v38-4-11,11>>^ Falei mais, e disse-lhe: Que são as duas oliveiras à direita do castiçal e à sua esquerda?

[[v38-4-12]]

^<<v38-4-12,12>>^ E, falando-lhe outra vez, disse: Que são  aqueles dois raminhos de oliveira, que estão junto aos dois tubos de ouro, e que vertem de si ouro?

[[v38-4-13]]

^<<v38-4-13,13>>^ E ele me respondeu, dizendo: Não sabes o que é isto? E eu disse: Não, Senhor meu.

[[v38-4-14]]

^<<v38-4-14,14>>^ Então ele disse: Estes são os dois filhos do óleo, que estão diante do Senhor de toda a terra.

'''

xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[Próximo Capítulo &#62;]