include::./index.adoc[]

[[v38-11-0]]
=== Zacarias, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v38-11-1]]

^<<v38-11-1,1>>^ ABRE, ó Líbano, as tuas portas para que o fogo consuma os cedros.

[[v38-11-2]]

^<<v38-11-2,2>>^ Gemei, faias, porque os cedros caíram, porque os mais excelentes são destruídos; gemei, ó carvalhos de Basã, porque o bosque forte é derribado.

[[v38-11-3]]

^<<v38-11-3,3>>^ Voz de uivo dos pastores! porque a sua glória é destruída: voz de bramido dos filhos de leões! porque foi destruída a soberba do Jordão!

[[v38-11-4]]

^<<v38-11-4,4>>^ Assim diz o Senhor meu Deus: Apascenta as ovelhas da matança,

[[v38-11-5]]

^<<v38-11-5,5>>^ Cujos possuidores as matam, e não se têm por culpados; e cujos vendedores dizem: Louvado seja o Senhor, porque hei enriquecido e os seus pastores não têm piedade delas.

[[v38-11-6]]

^<<v38-11-6,6>>^ Certamente não terei mais piedade dos moradores desta terra, diz o Senhor, mas, eis que entregarei os homens cada um na mão do seu companheiro e na mão do seu rei; eles ferirão a terra, e eu não os  livrarei da sua mão.

[[v38-11-7]]

^<<v38-11-7,7>>^ E eu apascentei as ovelhas da matança, as pobres ovelhas do rebanho; e tomei para mim duas varas: a uma chamei Suavidade, e à outra chamei Laços; e apascentei as ovelhas.

[[v38-11-8]]

^<<v38-11-8,8>>^ E destruí os três pastores num mês, porque se angustiou deles a minha alma, e também a sua alma teve fastio de mim.

[[v38-11-9]]

^<<v38-11-9,9>>^ E eu disse: Não vos apascentarei mais: o que morrer morra, e o que for destruído seja, e as que restarem comam cada uma a carne da sua companheira.

[[v38-11-10]]

^<<v38-11-10,10>>^ E tomei a minha vara Suavidade, e a quebrei, para desfazer o meu concerto, que tinha estabelecido com todos estes povos.

[[v38-11-11]]

^<<v38-11-11,11>>^ E foi quebrada naquele dia, e conheceram assim os pobres do rebanho que me aguardavam que isto era  palavra do Senhor.

[[v38-11-12]]

^<<v38-11-12,12>>^ E eu disse-lhes: Se parece  bem aos vossos olhos, dai-me o que me é devido, e, se não, deixai-o. E pesaram o meu salário, trinta moedas  de prata.

[[v38-11-13]]

^<<v38-11-13,13>>^ O Senhor pois me disse: Arroja isso ao oleiro, esse belo preço em que fui avaliado por eles. E tomei as trinta moedas  de prata, e as arrojei ao oleiro na casa do Senhor.

[[v38-11-14]]

^<<v38-11-14,14>>^ Então quebrei a minha segunda vara Laços, para romper a irmandade entre Judá e Israel.

[[v38-11-15]]

^<<v38-11-15,15>>^ E o Senhor me disse: Toma ainda para ti o instrumento de um pastor insensato.

[[v38-11-16]]

^<<v38-11-16,16>>^ Porque, eis que levantarei um pastor na terra, que  não visitará as que estão perecendo, não buscará a desgarrada, e não sarará a doente, nem apascentará a sã; mas comerá a carne da gorda, e lhe despedaçará as unhas.

[[v38-11-17]]

^<<v38-11-17,17>>^ Ai do pastor inútil que abandona o rebanho; a espada cairá  sobre o seu braço e sobre o seu olho direito; o seu braço completamente se secará, e o seu olho direito completamente se escurecerá.

'''

xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[&#60; Capítulo Anterior] | <<v38-11-0,Topo>> | xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[Próximo Capítulo &#62;]