include::./index.adoc[]

[[v38-5-0]]
=== Zacarias, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v38-5-1]]

^<<v38-5-1,1>>^ E OUTRA vez levantei os meus olhos e olhei, e vi um rolo voante.

[[v38-5-2]]

^<<v38-5-2,2>>^ E ele me disse: Que vês? E eu disse: Vejo um rolo voante, que tem vinte côvados de comprido e dez côvados de largo.

[[v38-5-3]]

^<<v38-5-3,3>>^ Então me disse: Esta é  a maldição que sairá pela face de toda a terra; porque qualquer que furtar, será desarraigado, conforme a maldição de um lado; e qualquer que jurar falsamente  será desarraigado, conforme a maldição do outro lado.

[[v38-5-4]]

^<<v38-5-4,4>>^ Eu a trarei, disse o Senhor dos Exércitos, e a farei entrar na casa do ladrão, e na casa do que jurar falsamente pelo meu nome; e pernoitará no meio da sua casa, e a consumirá a ela  com a sua madeira e com as suas pedras.

[[v38-5-5]]

^<<v38-5-5,5>>^ E saiu o anjo, que falava comigo, e me disse: Levanta agora os teus olhos, e vê que é  isto que sai.

[[v38-5-6]]

^<<v38-5-6,6>>^ E eu disse: Que é  isto? E ele disse: Isto é  um efa que sai. Mais disse: Esta é a semelhança deles em toda a terra.

[[v38-5-7]]

^<<v38-5-7,7>>^ E eis que foi levantado um talento de chumbo, e uma mulher estava  assentada no meio do efa.

[[v38-5-8]]

^<<v38-5-8,8>>^ E ele disse: Esta é  a impiedade. E a lançou dentro do efa; e pôs sobre a boca dele o peso de chumbo.

[[v38-5-9]]

^<<v38-5-9,9>>^ E levantei os meus olhos, e olhei, e eis que duas mulheres saíram, agitando o ar com as suas asas, pois tinham asas como as da cegonha; e levantaram o efa entre a terra e o céu.

[[v38-5-10]]

^<<v38-5-10,10>>^ Então eu disse ao anjo que falava comigo: Para onde levam estas o efa?

[[v38-5-11]]

^<<v38-5-11,11>>^ E ele me disse: Para lhe edificarem uma casa na terra de Sinear, e, estando ela acabada, ele será posto ali em seu próprio lugar.

'''

xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[&#60; Capítulo Anterior] | <<v38-5-0,Topo>> | xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[Próximo Capítulo &#62;]