include::./index.adoc[]

[[v38-9-0]]
=== Zacarias, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v38-9-1]]

^<<v38-9-1,1>>^ PESO da palavra do Senhor contra a terra de Haldraque, e Damasco, o seu repouso; porque o olhar do homem, e de todas as tribos de Israel se volta para o Senhor.

[[v38-9-2]]

^<<v38-9-2,2>>^ E também Hamate nela terá termo: e Tiro e Sidom, ainda que sejam mui sábias.

[[v38-9-3]]

^<<v38-9-3,3>>^ E Tiro edificou para si fortalezas, e amontoou prata como o pó, e ouro fino como a lama das ruas.

[[v38-9-4]]

^<<v38-9-4,4>>^ Eis que o Senhor a despojará, e ferirá no mar a sua força, e ela será consumida pelo fogo.

[[v38-9-5]]

^<<v38-9-5,5>>^ Ascalom o  verá e temerá, também Gaza, e terá grande dor: igualmente Ecrom, porque a sua esperança será iludida; e o rei de Gaza perecerá, e Ascalom não será habitada.

[[v38-9-6]]

^<<v38-9-6,6>>^ E um bastardo habitará em Asdode, e exterminarei a soberba dos filisteus.

[[v38-9-7]]

^<<v38-9-7,7>>^ E da sua boca tirarei o seu sangue, e dentre os seus dentes as suas abominações; e ele também ficará como um resto para o nosso Deus; e será como príncipe em Judá, e Ecrom como um jebuseu.

[[v38-9-8]]

^<<v38-9-8,8>>^ E me acamparei ao redor da minha casa, contra o exército, para que ninguém passe, e para que ninguém volte; para que não passe mais sobre eles o exator; porque agora vi com os meus olhos.

[[v38-9-9]]

^<<v38-9-9,9>>^ Alegra-te muito, ó filha de Sião; exulta, ó filha de Jerusalém: eis que o teu rei virá a ti, justo e Salvador, pobre, e montado sobre um jumento, sobre um asninho, filho de jumenta.

[[v38-9-10]]

^<<v38-9-10,10>>^ E destruirei os carros de Efraim e os cavalos de Jerusalém e o arco de guerra será destruído; e ele anunciará paz às nações: e o seu domínio se estenderá de um  mar a outro  mar, e desde o rio até às extremidades da terra.

[[v38-9-11]]

^<<v38-9-11,11>>^ Ainda quanto a ti, por causa do sangue do teu concerto, tirei os teus presos da cova em que não havia  água.

[[v38-9-12]]

^<<v38-9-12,12>>^ Voltai à fortaleza ó presos de esperança: também hoje vos anuncio que vos recompensarei em dobro.

[[v38-9-13]]

^<<v38-9-13,13>>^ Porque curvei Judá para mim, enchi com Efraim o arco: suscitarei a teus filhos, ó Sião, contra os teus filhos, ó Grécia! e pôr-te-ei como a espada de um valente.

[[v38-9-14]]

^<<v38-9-14,14>>^ E o Senhor será visto sobre eles, e as suas frechas sairão como o relâmpago; e o Senhor Jeová  fará soar a trombeta, e irá com os redemoinhos do sul.

[[v38-9-15]]

^<<v38-9-15,15>>^ O Senhor dos Exércitos os amparará: e comerão, depois que os tiverem sujeitado, as pedras da funda: também beberão e farão barulho como excitados pelo vinho; e encher-se-ão como taças como os cantos do altar.

[[v38-9-16]]

^<<v38-9-16,16>>^ E o Senhor seu Deus naquele dia os salvará, como ao rebanho do seu povo; porque como  as pedras de uma coroa eles serão exaltados na sua terra.

[[v38-9-17]]

^<<v38-9-17,17>>^ Porque, quão grande é a sua bondade! e quão grande é a sua formosura! o trigo fará florescer os mancebos e o mosto as donzelas.

'''

xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[&#60; Capítulo Anterior] | <<v38-9-0,Topo>> | xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[Próximo Capítulo &#62;]