include::./index.adoc[]

[[v38-1-0]]
=== Zacarias, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v38-1-1]]

^<<v38-1-1,1>>^ NO oitavo mês do segundo ano de Dario veio a palavra do Senhor ao profeta Zacarias, filho de Baraquias, filho de Ido, dizendo:

[[v38-1-2]]

^<<v38-1-2,2>>^ O Senhor tem estado em extremo desgostoso com vossos pais.

[[v38-1-3]]

^<<v38-1-3,3>>^ Portanto dize-lhes: Assim diz o Senhor dos Exércitos: Tornai para mim, diz o Senhor dos Exércitos, e eu tornarei para vós, diz o Senhor dos Exércitos.

[[v38-1-4]]

^<<v38-1-4,4>>^ E não sejais como vossos pais, aos quais clamavam os primeiros profetas, dizendo: Assim diz o Senhor dos Exércitos: Convertei-vos agora dos vossos maus caminhos e das vossas más obras; mas não ouviram, nem me escutaram, diz o Senhor.

[[v38-1-5]]

^<<v38-1-5,5>>^ Vossos pais, onde estão eles? e os profetas, viverão eles para sempre?

[[v38-1-6]]

^<<v38-1-6,6>>^ Contudo as minhas palavras e os meus estatutos, que eu mandei pelos profetas, meus servos, não alcançaram a vossos pais? E eles tornaram, e disseram: Assim como o Senhor dos Exércitos fez tenção de nos tratar, segundo os nossos caminhos, e segundo as nossas obras, assim ele nos tratou.

[[v38-1-7]]

^<<v38-1-7,7>>^ Aos vinte e quatro dias do mês undécimo (que é o mês de sebate), no segundo ano de Dario, veio a palavra do Senhor ao profeta Zacarias, filho de Baraquias, filho de Ido, dizendo:

[[v38-1-8]]

^<<v38-1-8,8>>^ Olhei de noite, e vi um homem montado num cavalo vermelho, e parava entre as murtas que estavam na profundeza, e atrás dele estavam cavalos vermelhos, morenos e brancos.

[[v38-1-9]]

^<<v38-1-9,9>>^ E eu disse: Senhor meu, quem são  estes? E disse-me o anjo que falava comigo: Eu te mostrarei quem estes são.

[[v38-1-10]]

^<<v38-1-10,10>>^ Então respondeu o homem que estava entre as murtas, e disse: Estes são os que o Senhor tem enviado para andarem pela terra.

[[v38-1-11]]

^<<v38-1-11,11>>^ E eles responderam ao anjo do Senhor, que estava entre as murtas, e disseram: Nós já  andamos pela terra, e eis que toda a terra está tranquila e em descanso.

[[v38-1-12]]

^<<v38-1-12,12>>^ Então o anjo do Senhor respondeu, e disse: Ó Senhor dos Exércitos, até quando não terás compaixão de Jerusalém, e das cidades de Judá, contra as quais estiveste irado estes setenta anos?

[[v38-1-13]]

^<<v38-1-13,13>>^ Respondeu o Senhor ao anjo que falava comigo, palavras boas, palavras consoladoras.

[[v38-1-14]]

^<<v38-1-14,14>>^ E o anjo que falava comigo me disse: Clama, dizendo: Assim diz o Senhor dos Exércitos: Com grande zelo estou zelando por Jerusalém e por Sião.

[[v38-1-15]]

^<<v38-1-15,15>>^ E com  grandíssima ira estou irado contra as nações em descanso; porque estando eu um pouco desgostoso, eles auxiliaram no mal.

[[v38-1-16]]

^<<v38-1-16,16>>^ Portanto, o Senhor diz assim: Voltei-me para Jerusalém com misericórdia; a minha casa nela será edificada, diz o Senhor dos Exércitos, e o cordel será estendido sobre Jerusalém.

[[v38-1-17]]

^<<v38-1-17,17>>^ Clama outra vez, dizendo: Assim diz o Senhor dos Exércitos: As minhas cidades ainda aumentarão e prosperarão; porque o Senhor ainda consolará a Sião e ainda escolherá a Jerusalém.

[[v38-1-18]]

^<<v38-1-18,18>>^ E levantei os meus olhos, e olhei, e vi quatro cornos.

[[v38-1-19]]

^<<v38-1-19,19>>^ E eu disse ao anjo que falava comigo: Que é isto? E ele me disse: Estes são  os poderes que dispersaram a Judá, a Israel e a Jerusalém.

[[v38-1-20]]

^<<v38-1-20,20>>^ E o Senhor me mostrou quatro ferreiros.

[[v38-1-21]]

^<<v38-1-21,21>>^ Então eu disse: Que vêm estes fazer? E ele falou, dizendo: Estes são  os poderes que dispersaram Judá, de maneira que ninguém pôde levantar a sua cabeça; estes pois vieram para os amedrontarem, para derribarem os poderes das nações que levantaram o seu poder contra a terra de Judá, para a espalharem.

'''

xref:037-ageu/037-ageu-002.adoc#v37-2-0[&#60; Capítulo Anterior] | <<v38-1-0,Topo>> | xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[Próximo Capítulo &#62;]