include::./index.adoc[]

[[v38-13-0]]
=== Zacarias, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v38-13-1]]

^<<v38-13-1,1>>^ NAQUELE dia haverá uma fonte aberta para a casa de Davi, e para os habitantes de Jerusalém, contra o pecado, e contra a impureza.

[[v38-13-2]]

^<<v38-13-2,2>>^ E acontecerá, naquele dia, diz o Senhor dos Exércitos, que tirarei da terra os nomes dos ídolos, e deles não haverá mais memória; e também farei sair da terra os profetas e o espírito da impureza.

[[v38-13-3]]

^<<v38-13-3,3>>^ E será que, quando alguém ainda profetizar, seu pai e sua mãe, que o geraram, lhe dirão: Não viverás, porque mentirosamente falaste em nome do Senhor; e seu pai e sua mãe, que o geraram, o traspassarão quando profetizar.

[[v38-13-4]]

^<<v38-13-4,4>>^ E acontecerá naquele dia que  os profetas se envergonharão, cada um da sua visão, quando profetizarem; nem mais se vestirão de manto de pelos, para mentirem.

[[v38-13-5]]

^<<v38-13-5,5>>^ Mas dirão: Não sou profeta, sou lavrador da terra; porque tenho sido servo desde a minha mocidade.

[[v38-13-6]]

^<<v38-13-6,6>>^ E se alguém lhe disser: Que feridas são essas nas tuas mãos? Dirá ele: São as feridas  com que fui ferido em  casa dos meus amigos.

[[v38-13-7]]

^<<v38-13-7,7>>^ Ó espada, ergue-te contra o meu Pastor e contra o varão que é  o meu companheiro, diz o Senhor dos Exércitos: fere o Pastor, e espalhar-se-ão as ovelhas; mas volverei a minha mão para os pequenos.

[[v38-13-8]]

^<<v38-13-8,8>>^ E acontecerá em toda a terra, diz o Senhor, que as duas partes dela serão extirpadas, e  expirarão; mas a terceira parte restará nela.

[[v38-13-9]]

^<<v38-13-9,9>>^ E farei passar esta terceira parte pelo fogo, e a purificarei, como se purifica a prata, e a provarei, como se prova o ouro: ela invocará o meu nome, e eu a ouvirei; direi: É meu povo, e ela dirá: O Senhor é meu Deus.

'''

xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[&#60; Capítulo Anterior] | <<v38-13-0,Topo>> | xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[Próximo Capítulo &#62;]