include::./index.adoc[]

[[v27-11-0]]
=== Daniel, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v27-11-1]]

^<<v27-11-1,1>>^ EU, pois, no primeiro ano de Dario, medo, levantei-me para o animar e fortalecer.

[[v27-11-2]]

^<<v27-11-2,2>>^ E agora te declararei a verdade: Eis que ainda três reis estarão na Pérsia, e o quarto será cumulado de grandes riquezas mais do que todos; e, esforçando-se com as suas riquezas, agitará todos contra o reino da Grécia.

[[v27-11-3]]

^<<v27-11-3,3>>^ Depois se levantará um rei valente, que reinará com grande domínio, e fará o que lhe aprouver.

[[v27-11-4]]

^<<v27-11-4,4>>^ Mas, estando ele em pé, o seu reino será quebrado, e será repartido para os quatro ventos do céu; mas não para a sua posteridade, nem tão pouco segundo o poder com que reinou, porque o seu reino será arrancado, e passará a outros.

[[v27-11-5]]

^<<v27-11-5,5>>^ E se fortalecerá o rei do Sul, e um  de seus príncipes; e este se fortalecerá, mais do que ele, e reinará, e domínio grande será  o seu domínio,

[[v27-11-6]]

^<<v27-11-6,6>>^ Mas, ao cabo de anos, eles se aliarão; e a filha do rei do Sul virá ao rei do Norte para fazer um tratado; mas não conservará a força de seu braço; nem ele persistirá, nem o seu braço, porque ela será entregue, e os que a tiverem trazido, e seu pai, e o que a fortalecia naqueles tempos.

[[v27-11-7]]

^<<v27-11-7,7>>^ Mas do renovo das suas raízes um  se levantará em seu lugar, e virá com o exército, e entrará nas fortalezas do rei do Norte, e operará contra elas, e prevalecerá.

[[v27-11-8]]

^<<v27-11-8,8>>^ E também os seus deuses com a multidão das suas imagens, com os seus vasos preciosos de prata e ouro, levará cativos para o Egito; e por alguns  anos ele persistirá contra o rei do Norte.

[[v27-11-9]]

^<<v27-11-9,9>>^ E entrará no reino do rei do Sul, e tornará para a sua terra.

[[v27-11-10]]

^<<v27-11-10,10>>^ Mas seus filhos intervirão e reunirão grande número de exércitos: e um deles  virá apressadamente, e inundará, e passará; e, voltando, levará a guerra até à sua fortaleza.

[[v27-11-11]]

^<<v27-11-11,11>>^ Então o rei do Sul se exasperará, e sairá, e pelejará contra ele, contra o rei do Norte: ele porá em campo grande multidão, e a multidão será entregue na sua mão.

[[v27-11-12]]

^<<v27-11-12,12>>^ E, aumentando a multidão, o seu coração se exaltará; mas, ainda que derribará muitos  milhares, não prevalecerá.

[[v27-11-13]]

^<<v27-11-13,13>>^ Porque o rei do Norte tornará, e porá em campo uma multidão maior do que a primeira, e ao cabo de tempos, isto é , de anos, virá à pressa com grande exército e com muita fazenda.

[[v27-11-14]]

^<<v27-11-14,14>>^ E, naqueles tempos, muitos se levantarão contra o rei do Sul; e os filhos dos prevaricadores do teu povo se levantarão para confirmar a visão; mas eles cairão.

[[v27-11-15]]

^<<v27-11-15,15>>^ E o rei do Norte virá, e levantará baluartes, e tomará a cidade forte; e os braços do Sul não poderão subsistir, nem o seu povo escolhido, pois não haverá força que possa subsistir.

[[v27-11-16]]

^<<v27-11-16,16>>^ O que pois há de vir contra ele fará segundo a sua vontade, e ninguém poderá permanecer diante dele; e estará na terra gloriosa, e por sua mão se fará destruição.

[[v27-11-17]]

^<<v27-11-17,17>>^ E porá o seu rosto, para vir com a força de todo o seu reino, e com ele os retos, e fará, o que lhe aprouver: e lhe dará uma filha das mulheres, para a corromper; mas ela não subsistirá, nem será para ele.

[[v27-11-18]]

^<<v27-11-18,18>>^ Depois virará o seu rosto para as ilhas, e tomará muitas; mas um príncipe fará cessar o seu opróbrio contra ele, e ainda fará tornar sobre ele o seu opróbrio.

[[v27-11-19]]

^<<v27-11-19,19>>^ Virará então o seu rosto para as fortalezas da sua própria terra, mas tropeçará, e cairá, e não será achado.

[[v27-11-20]]

^<<v27-11-20,20>>^ E em seu lugar se levantará quem fará passar um arrecadador pela glória real; mas em poucos dias será quebrantado, e isto  sem ira e sem batalha.

[[v27-11-21]]

^<<v27-11-21,21>>^ Depois se levantará em seu lugar um homem  vil, ao qual não tinham dado a dignidade real; mas ele virá caladamente, e tomará o reino com engano.

[[v27-11-22]]

^<<v27-11-22,22>>^ E com os braços de uma inundação serão arrancados de diante dele; e serão quebrantados, como também o príncipe do concerto.

[[v27-11-23]]

^<<v27-11-23,23>>^ E, depois do concerto com ele, usará de engano; e subirá, e será fortalecido com pouca gente.

[[v27-11-24]]

^<<v27-11-24,24>>^ Virá também caladamente aos lugares mais férteis da província, e fará o que nunca fizeram seus pais, nem os pais de seus pais; repartirá entre eles a presa e os despojos, e a riqueza, e formará os seus projetos contra as fortalezas, mas por certo tempo.

[[v27-11-25]]

^<<v27-11-25,25>>^ E suscitará a sua força, e o seu coração contra o rei do Sul com um grande exército, e o rei do Sul se envolverá na guerra com um grande e mui poderoso exército; mas não subsistirá, porque formarão projetos contra ele.

[[v27-11-26]]

^<<v27-11-26,26>>^ E os que comerem os seus manjares o quebrantarão; e o exército dele se derramará, e cairão muitos traspassados.

[[v27-11-27]]

^<<v27-11-27,27>>^ Também estes dois reis terão o coração atento para fazerem o mal, e a uma mesma mesa falarão a mentira; ela, porém, não prosperará, porque o fim há de ser no tempo determinado.

[[v27-11-28]]

^<<v27-11-28,28>>^ Então tornará para a sua terra com grande riqueza, e o seu coração será  contra o santo concerto; e fará o que lhe aprouver, e tornará para a sua terra.

[[v27-11-29]]

^<<v27-11-29,29>>^ No tempo determinado tornará a vir contra o Sul; mas não será na última vez como foi na primeira.

[[v27-11-30]]

^<<v27-11-30,30>>^ Porque virão contra ele navios de Quitim, que lhe causarão tristeza; e voltará, e se indignará contra o santo concerto, e fará como lhe apraz; e ainda voltará e atenderá aos que tiverem desamparado o santo concerto.

[[v27-11-31]]

^<<v27-11-31,31>>^ E sairão a ele uns  braços, que profanarão o santuário e  a fortaleza, e tirarão o contínuo sacrifício , estabelecendo a abominação desoladora.

[[v27-11-32]]

^<<v27-11-32,32>>^ E aos violadores do concerto ele com lisonjas perverterá, mas o povo que conhece ao seu Deus se esforçará e fará proezas.

[[v27-11-33]]

^<<v27-11-33,33>>^ E os entendidos entre o povo ensinarão a muitos; todavia cairão pela espada, e pelo fogo, e pelo cativeiro, e pelo roubo, por muitos  dias.

[[v27-11-34]]

^<<v27-11-34,34>>^ E, caindo eles, serão ajudados com pequeno socorro; mas muitos se ajuntarão a eles com lisonjas.

[[v27-11-35]]

^<<v27-11-35,35>>^ E alguns dos entendidos cairão para serem provados, e purificados, e embranquecidos, até ao fim do tempo, porque será  ainda no tempo determinado.

[[v27-11-36]]

^<<v27-11-36,36>>^ E este rei fará conforme a sua vontade, e se levantará, e se engrandecerá sobre todo o deus; e contra o Deus dos deuses falará cousas maravilhosas, e será próspero, até que a ira se complete; porque aquilo que está determinado será feito.

[[v27-11-37]]

^<<v27-11-37,37>>^ E não terá respeito aos deuses de seus pais, nem terá respeito ao amor das mulheres, nem a qualquer deus, porque sobre tudo se engrandecerá.

[[v27-11-38]]

^<<v27-11-38,38>>^ Mas ao deus das fortalezas honrará em seu lugar: e a um deus a quem seus pais não conheceram honrará com ouro, e com prata, e com pedras preciosas, e com cousas agradáveis.

[[v27-11-39]]

^<<v27-11-39,39>>^ E haver-se-á com os castelos fortes com o auxílio do deus estranho; aos que o reconhecerem multiplicará a honra, e os fará reinar sobre muitos, e repartirá a terra por preço.

[[v27-11-40]]

^<<v27-11-40,40>>^ E, no fim do tempo, o rei do Sul lutará com ele, e o rei do Norte o acometerá com carros, e com cavaleiros, e com muitos navios; e entrará nas terras, e as inundará, e passará.

[[v27-11-41]]

^<<v27-11-41,41>>^ E entrará também na terra gloriosa, e muitos países serão derribados, mas escaparão da sua mão estes: Edom e Moabe, e as primícias dos filhos de Amom.

[[v27-11-42]]

^<<v27-11-42,42>>^ E estenderá a sua mão às terras, e a terra do Egito não escapará.

[[v27-11-43]]

^<<v27-11-43,43>>^ E apoderar-se-á dos tesouros de ouro e de prata, e de todas as cousas desejáveis do Egito; e os líbios e os etíopes o seguirão.

[[v27-11-44]]

^<<v27-11-44,44>>^ Mas os rumores do Oriente e do Norte o espantarão; e sairá com grande furor, para destruir e extirpar a muitos.

[[v27-11-45]]

^<<v27-11-45,45>>^ E armará as tendas do seu palácio entre o mar grande e o monte santo e glorioso; mas virá ao seu fim, e não haverá quem o socorra.

'''

xref:027-daniel/027-daniel-010.adoc#v27-10-0[&#60; Capítulo Anterior] | <<v27-11-0,Topo>> | xref:027-daniel/027-daniel-012.adoc#v27-12-0[Próximo Capítulo &#62;]