include::./index.adoc[]

[[v27-6-0]]
=== Daniel, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v27-6-1]]

^<<v27-6-1,1>>^ E PARECEU bem a Dario constituir sobre o reino a cento e vinte presidentes, que estivessem sobre todo o reino;

[[v27-6-2]]

^<<v27-6-2,2>>^ E sobre eles três príncipes, dos quais Daniel era um, aos quais estes presidentes dessem conta, para que o rei não sofresse dano.

[[v27-6-3]]

^<<v27-6-3,3>>^ Então o mesmo Daniel se distinguiu destes príncipes e presidentes, porque nele havia  um espírito excelente; e o rei pensava constituí-lo sobre todo o reino.

[[v27-6-4]]

^<<v27-6-4,4>>^ Então os príncipes e os presidentes procuravam achar ocasião contra Daniel a respeito do reino; mas não podiam achar ocasião ou culpa alguma; porque ele era  fiel, e não se achava nele nenhum vício nem culpa.

[[v27-6-5]]

^<<v27-6-5,5>>^ Então estes homens disseram: Nunca acharemos ocasião alguma contra este Daniel, se não a procurarmos contra ele na lei do seu Deus.

[[v27-6-6]]

^<<v27-6-6,6>>^ Então estes príncipes e presidentes foram juntos ao rei, e disseram-lhe assim: Ó rei Dario, vive para sempre!

[[v27-6-7]]

^<<v27-6-7,7>>^ Todos os príncipes do reino, os prefeitos e presidentes, capitães e governadores, tomaram conselho a fim de estabelecerem um edito real e fazerem firme este mandamento: que qualquer que, por espaço de trinta dias, fizer uma petição a qualquer deus, ou a qualquer  homem, e não a ti, ó rei, seja lançado na cova dos leões.

[[v27-6-8]]

^<<v27-6-8,8>>^ Agora pois , ó rei, confirma o edito e assina a escritura, para que não seja mudada, conforme a lei dos medos e dos persas, que se não pode revogar.

[[v27-6-9]]

^<<v27-6-9,9>>^ Por esta causa o rei Dario assinou esta escritura e edito.

[[v27-6-10]]

^<<v27-6-10,10>>^ Daniel, pois, quando soube que a escritura estava assinada, entrou em sua casa (ora havia no seu quarto janelas abertas da banda de Jerusalém), e três vezes no dia se punha de joelhos, e orava, e dava graças, diante do seu Deus, como também antes costumava fazer.

[[v27-6-11]]

^<<v27-6-11,11>>^ Então aqueles homens foram juntos, e acharam a Daniel orando e suplicando diante do seu Deus.

[[v27-6-12]]

^<<v27-6-12,12>>^ Então se apresentaram, e disseram ao rei: No tocante ao mandamento real, porventura  não assinaste o edito, pelo qual todo o homem que fizesse uma petição a qualquer deus, ou a qualquer homem, por espaço de trinta dias, e não a ti, ó rei, seria lançado na cova dos leões? Respondeu o rei, e disse: Esta palavra é  certa, conforme a lei dos medos e dos persas, que se não pode revogar.

[[v27-6-13]]

^<<v27-6-13,13>>^ Então responderam, e disseram diante do rei: Daniel, que é  dos transportados de Judá, não tem feito caso de ti, ó rei, nem do edito que assinaste, antes três vezes por dia faz a sua oração.

[[v27-6-14]]

^<<v27-6-14,14>>^ Ouvindo então o rei o negócio, ficou muito penalizado, e a favor de Daniel propôs dentro do seu coração livrá-lo; e até ao pôr do sol trabalhou por o salvar.

[[v27-6-15]]

^<<v27-6-15,15>>^ Então aqueles homens foram juntos ao rei, e disseram ao rei: Sabe, ó rei, que é uma lei dos medos e dos persas que nenhum edito ou ordenança, que o rei determine, se pode mudar.

[[v27-6-16]]

^<<v27-6-16,16>>^ Então o rei ordenou que trouxessem a Daniel, e o lançaram na cova dos leões. E, falando o rei, disse a Daniel: O teu Deus, a quem tu continuamente serves, ele te livrará.

[[v27-6-17]]

^<<v27-6-17,17>>^ E foi trazida uma  pedra e foi posta sobre a boca da cova; e o rei a selou com o seu anel e com o anel dos seus grandes, para que se não mudasse a sentença acerca de Daniel.

[[v27-6-18]]

^<<v27-6-18,18>>^ Então o rei dirigiu-se para o seu palácio, e passou a noite em  jejum, e não deixou trazer à sua presença instrumentos de música; e fugiu dele o sono.

[[v27-6-19]]

^<<v27-6-19,19>>^ E pela manhã cedo se levantou, e foi com pressa à cova dos leões.

[[v27-6-20]]

^<<v27-6-20,20>>^ E, chegando-se à cova, chamou por Daniel com voz triste; e, falando o rei, disse a Daniel: Daniel, servo do Deus vivo! dar-se-ia o caso que o teu Deus, a quem tu continuamente serves, tenha podido livrar-te dos leões?

[[v27-6-21]]

^<<v27-6-21,21>>^ Então Daniel falou ao rei: Ó rei, vive para sempre!

[[v27-6-22]]

^<<v27-6-22,22>>^ O meu Deus enviou o seu anjo, e fechou a boca dos leões, para que não me fizessem dano, porque foi achada em mim inocência diante dele; e também contra ti, ó rei, não tenho cometido delito algum.

[[v27-6-23]]

^<<v27-6-23,23>>^ Então o rei muito se alegrou em si mesmo, e mandou tirar a Daniel da cova: assim foi tirado Daniel da cova, e nenhum dano se achou nele, porque crera no seu Deus.

[[v27-6-24]]

^<<v27-6-24,24>>^ E ordenou o rei, e foram trazidos aqueles homens que tinham acusado Daniel, e foram lançados na cova dos leões, eles, seus filhos e suas mulheres; e ainda  não tinham chegado ao fundo da cova quando os leões se apoderaram deles, e lhes esmigalharam todos os ossos.

[[v27-6-25]]

^<<v27-6-25,25>>^ Então o rei Dario escreveu a todos os povos, nações e gente de diferentes línguas, que moram em toda a terra: A paz vos seja multiplicada.

[[v27-6-26]]

^<<v27-6-26,26>>^ Da minha parte é feito um  decreto, pelo qual em todo o domínio do meu reino os homens tremam e temam perante o Deus de Daniel; porque ele é o Deus vivo e para sempre permanente, e o seu reino não se pode destruir; o seu domínio é até ao fim.

[[v27-6-27]]

^<<v27-6-27,27>>^ Ele livra e salva, e opera sinais e maravilhas no céu e na terra; ele livrou Daniel do poder dos leões.

[[v27-6-28]]

^<<v27-6-28,28>>^ Este Daniel, pois, prosperou no reinado de Dario, e no reinado de Ciro, o persa.

'''

xref:027-daniel/027-daniel-005.adoc#v27-5-0[&#60; Capítulo Anterior] | <<v27-6-0,Topo>> | xref:027-daniel/027-daniel-007.adoc#v27-7-0[Próximo Capítulo &#62;]