include::./index.adoc[]

[[v27-12-0]]
=== Daniel, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v27-12-1]]

^<<v27-12-1,1>>^ E NAQUELE tempo se levantará Miguel, o grande príncipe, que se levanta pelos filhos do teu povo, e haverá um tempo de angústia, qual nunca houve, desde que houve nação até àquele tempo; mas naquele tempo livrar-se-á o teu povo, todo aquele que se achar escrito no livro.

[[v27-12-2]]

^<<v27-12-2,2>>^ E muitos dos que dormem no pó da terra ressuscitarão uns para a vida eterna, e outros para vergonha e  desprezo eterno.

[[v27-12-3]]

^<<v27-12-3,3>>^ Os entendidos pois resplandecerão, como o resplendor do firmamento; e os que a muitos ensinam a justiça refulgirão como as estrelas sempre e eternamente.

[[v27-12-4]]

^<<v27-12-4,4>>^ E tu, Daniel, fecha estas palavras e sela este livro, até ao fim do tempo: muitos correrão de uma parte para outra, e a ciência se multiplicará.

[[v27-12-5]]

^<<v27-12-5,5>>^ E eu, Daniel, olhei, e eis que estavam outros dois, um desta banda, à beira do rio, e o outro da outra banda, à beira do rio.

[[v27-12-6]]

^<<v27-12-6,6>>^ E ele disse ao homem vestido de linho que estava  sobre as águas do rio: Que tempo haverá até ao fim das maravilhas?

[[v27-12-7]]

^<<v27-12-7,7>>^ E ouvi o homem vestido de linho, que estava  sobre as águas do rio, quando levantou a sua mão direita, e a sua mão esquerda ao céu, e jurou por aquele que vive eternamente que depois de um tempo, de tempos e metade de um tempo , e quando tiverem acabado de destruir o poder do povo santo, todas estas cousas serão cumpridas.

[[v27-12-8]]

^<<v27-12-8,8>>^ Eu pois ouvi, mas não entendi; por isso eu disse: Senhor meu, qual será  o fim destas cousas?

[[v27-12-9]]

^<<v27-12-9,9>>^ E ele disse: Vai, Daniel, porque estas palavras estão fechadas e seladas até ao tempo do fim.

[[v27-12-10]]

^<<v27-12-10,10>>^ Muitos serão purificados, e embranquecidos, e provados; mas os ímpios procederão impiamente, e nenhum dos ímpios entenderá, mas os sábios entenderão.

[[v27-12-11]]

^<<v27-12-11,11>>^ E desde o tempo em que o contínuo sacrifício  for tirado, e posta a abominação desoladora, haverá mil duzentos e noventa dias.

[[v27-12-12]]

^<<v27-12-12,12>>^ Bem-aventurado o que espera e chega até mil trezentos e trinta e cinco dias.

[[v27-12-13]]

^<<v27-12-13,13>>^ Tu, porém, vai até ao fim; porque repousarás, e estarás na tua sorte, no fim dos dias.

'''

xref:027-daniel/027-daniel-011.adoc#v27-11-0[&#60; Capítulo Anterior] | <<v27-12-0,Topo>> | xref:028-oseias/028-oseias-001.adoc#v28-1-0[Próximo Capítulo &#62;]