include::./index.adoc[]

[[v27-1-0]]
=== Daniel, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v27-1-1]]

^<<v27-1-1,1>>^ NO ano terceiro do reinado de Joaquim, rei de Judá, veio Nabucodonosor, rei de Babilônia, a Jerusalém, e a sitiou.

[[v27-1-2]]

^<<v27-1-2,2>>^ E o Senhor entregou nas suas mãos a Joaquim, rei de Judá, e uma  parte dos vasos da casa de Deus, e ele os levou para a terra de Sinar, para  a casa do seu deus, e pôs os vasos na casa do tesouro do seu deus.

[[v27-1-3]]

^<<v27-1-3,3>>^ E disse o rei a Aspenaz, chefe dos seus eunucos, que trouxesse alguns  dos filhos de Israel, e da linhagem real e dos nobres,

[[v27-1-4]]

^<<v27-1-4,4>>^ Mancebos em quem não houvesse  defeito algum, formosos de parecer, e instruídos em toda a sabedoria, sábios em  ciência, e entendidos no conhecimento, e que tivessem habilidade para viverem no palácio do rei, a fim de que fossem ensinados nas letras e na língua dos caldeus.

[[v27-1-5]]

^<<v27-1-5,5>>^ E o rei lhes determinou a ração de cada dia, da porção do manjar do rei, e do vinho que ele bebia, e que assim  fossem criados por três anos, para que no fim deles pudessem estar diante do rei.

[[v27-1-6]]

^<<v27-1-6,6>>^ E entre eles se achavam, dos filhos de Judá, Daniel, Hananias, Misael e Azarias.

[[v27-1-7]]

^<<v27-1-7,7>>^ E o chefe dos eunucos lhes pôs outros  nomes, a saber: a Daniel pôs o de  Beltessazar, e a Hananias, o de  Sadraque, e a Misael o de  Mesaque, e a Azarias o de  Abednego.

[[v27-1-8]]

^<<v27-1-8,8>>^ E Daniel assentou no seu coração não se contaminar com a porção do manjar do rei, nem com o vinho que ele bebia; portanto pediu ao chefe dos eunucos que lhe concedesse não se contaminar.

[[v27-1-9]]

^<<v27-1-9,9>>^ Ora deu Deus a Daniel graça e misericórdia diante do chefe dos eunucos.

[[v27-1-10]]

^<<v27-1-10,10>>^ E disse o chefe dos eunucos a Daniel: Tenho medo do meu senhor, o rei, que determinou a vossa comida e a vossa bebida: porque veria ele os vossos rostos mais tristes do que os  dos mancebos que são  vossos iguais? assim arriscareis a minha cabeça para com o rei.

[[v27-1-11]]

^<<v27-1-11,11>>^ Então disse Daniel ao despenseiro a quem o chefe dos eunucos havia constituído sobre Daniel, Hananias, Misael e Azarias:

[[v27-1-12]]

^<<v27-1-12,12>>^ Experimenta, peço-te, os teus servos dez dias, fazendo que se nos deem em legumes a comer, e água a beber.

[[v27-1-13]]

^<<v27-1-13,13>>^ Então se veja diante de ti o nosso parecer, e o parecer dos mancebos que comem a porção do manjar do rei, e, conforme vires, te hajas com os teus servos.

[[v27-1-14]]

^<<v27-1-14,14>>^ E ele conveio nisto, e os experimentou dez dias.

[[v27-1-15]]

^<<v27-1-15,15>>^ E, ao fim dos dez dias, apareceram os seus semblantes melhores; eles estavam mais gordos do que todos os mancebos que comiam porção do manjar do rei.

[[v27-1-16]]

^<<v27-1-16,16>>^ Desta sorte, o despenseiro tirou a porção do manjar deles, e o vinho que deviam beber, e lhes dava legumes.

[[v27-1-17]]

^<<v27-1-17,17>>^ Ora, a estes quatro mancebos Deus deu o conhecimento e a inteligência em todas as letras, e sabedoria; mas a Daniel deu entendimento em toda a visão e sonhos.

[[v27-1-18]]

^<<v27-1-18,18>>^ E ao fim dos dias, em que o rei tinha dito que os trouxessem, o chefe dos eunucos os trouxe diante de Nabucodonosor.

[[v27-1-19]]

^<<v27-1-19,19>>^ E o rei falou com eles; e entre todos eles não foram achados outros tais como Daniel, Hananias, Misael e Azarias; por isso permaneceram diante do rei.

[[v27-1-20]]

^<<v27-1-20,20>>^ E em  toda a matéria de sabedoria e de inteligência, sobre que o rei lhes fez perguntas, os achou dez vezes mais doutos  do que todos os magos ou astrólogos que havia  em todo o seu reino.

[[v27-1-21]]

^<<v27-1-21,21>>^ E Daniel esteve até ao primeiro ano do rei Ciro.

'''

xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[&#60; Capítulo Anterior] | <<v27-1-0,Topo>> | xref:027-daniel/027-daniel-002.adoc#v27-2-0[Próximo Capítulo &#62;]