include::./index.adoc[]

[[v27-7-0]]
=== Daniel, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v27-7-1]]

^<<v27-7-1,1>>^ NO primeiro ano de Belsazar, rei de Babilônia, teve Daniel, na sua cama, um sonho e visões da sua cabeça: escreveu logo o sonho, e relatou a suma das cousas.

[[v27-7-2]]

^<<v27-7-2,2>>^ Falou Daniel, e disse: Eu estava olhando, na minha visão da noite, e eis que os quatro ventos do céu combatiam no mar grande.

[[v27-7-3]]

^<<v27-7-3,3>>^ E quatro animais grandes, diferentes uns dos outros, subiam do mar.

[[v27-7-4]]

^<<v27-7-4,4>>^ O primeiro era  como leão, e tinha asas de águia: eu olhei até que lhe foram arrancadas as asas, e foi levantado da terra, e posto em pé como um homem; e foi-lhe dado um coração de homem.

[[v27-7-5]]

^<<v27-7-5,5>>^ Continuei olhando, e eis aqui o segundo animal, semelhante a um urso, o qual se levantou de um lado, tendo na boca três costelas entre os seus dentes; e foi-lhe dito assim: Levanta-te, devora muita carne.

[[v27-7-6]]

^<<v27-7-6,6>>^ Depois disto, eu continuei olhando, e eis aqui outro, semelhante a um leopardo, e tinha quatro asas de ave nas suas costas: tinha também este animal quatro cabeças, e foi-lhe dado domínio.

[[v27-7-7]]

^<<v27-7-7,7>>^ Depois disto, eu continuava olhando nas visões da noite, e eis aqui o quarto animal, terrível e espantoso, e muito forte, o qual tinha dentes grandes de ferro; ele devorava e fazia em pedaços, e pisava aos pés o que sobejava; era diferente de todos os animais que apareceram antes dele, e tinha dez pontas.

[[v27-7-8]]

^<<v27-7-8,8>>^ Estando eu considerando as pontas, eis que entre elas subiu outra ponta pequena, diante da qual três das pontas primeiras foram arrancadas; e eis que nesta ponta havia  olhos, como olhos de homem, e uma boca que falava grandiosamente.

[[v27-7-9]]

^<<v27-7-9,9>>^ Eu continuei olhando, até que foram postos uns tronos, e um ancião de dias se assentou: o seu vestido era  branco como a neve, e o cabelo da sua cabeça como a limpa lã; o seu trono chamas de fogo, e as rodas dele fogo ardente.

[[v27-7-10]]

^<<v27-7-10,10>>^ Um rio de fogo manava e saía de diante dele: milhares de milhares o serviam, e milhões de milhões estavam diante dele: assentou-se o juízo, e abriram-se os livros.

[[v27-7-11]]

^<<v27-7-11,11>>^ Então estive olhando, por causa da voz das grandes palavras que provinha da ponta: estive olhando até que o animal foi morto, e o seu corpo desfeito, e entregue para ser queimado pelo fogo.

[[v27-7-12]]

^<<v27-7-12,12>>^ E, quanto aos outros animais, foi-lhes tirado o domínio; todavia foi-lhes dada prolongação de vida até certo espaço de tempo.

[[v27-7-13]]

^<<v27-7-13,13>>^ Eu estava olhando nas minhas visões da noite, e eis que vinha nas nuvens do céu um  como o filho do homem: e dirigiu-se ao ancião de dias, e o fizeram chegar até ele.

[[v27-7-14]]

^<<v27-7-14,14>>^ E foi-lhe dado o domínio e a honra, e o reino, para que todos os povos, nações e línguas o servissem: o seu domínio é  um domínio eterno, que não passará, e o seu reino o único que não será destruído.

[[v27-7-15]]

^<<v27-7-15,15>>^ Quanto a mim, Daniel, o meu espírito foi abatido dentro do corpo, e as visões da minha cabeça me espantavam.

[[v27-7-16]]

^<<v27-7-16,16>>^ Cheguei-me a um dos que estavam perto, e pedi-lhe a verdade acerca de tudo isto. E ele me disse, e fez-me saber a interpretação das cousas.

[[v27-7-17]]

^<<v27-7-17,17>>^ Estes grandes animais, que são quatro, são  quatro reis, que  se levantarão da terra.

[[v27-7-18]]

^<<v27-7-18,18>>^ Mas os santos do Altíssimo receberão o reino, e possuirão o reino para todo o sempre, e de eternidade em eternidade.

[[v27-7-19]]

^<<v27-7-19,19>>^ Então tive desejo de conhecer a verdade a respeito do quarto animal, que era diferente de todos os outros, muito terrível, cujos dentes eram  de ferro, e as suas unhas de metal; que devorava, fazia em pedaços e pisava a pés o que sobrava.

[[v27-7-20]]

^<<v27-7-20,20>>^ E também das dez pontas que tinha na cabeça, e da outra que subia, de diante da qual caíram três, daquela ponta, digo, que tinha olhos, e uma boca que falava grandiosamente, e cujo parecer era mais firme do que o das suas companheiras.

[[v27-7-21]]

^<<v27-7-21,21>>^ Eu olhava, e eis que esta ponta fazia guerra contra os santos, e os vencia.

[[v27-7-22]]

^<<v27-7-22,22>>^ Até que veio o ancião de dias, e foi dado o juízo aos santos do Altíssimo; e chegou o tempo em que os santos possuíram o reino.

[[v27-7-23]]

^<<v27-7-23,23>>^ Disse assim: O quarto animal será o quarto reino na terra, o qual será diferente de todos os reinos; e devorará toda a terra, e a pisará aos pés, e a fará em pedaços.

[[v27-7-24]]

^<<v27-7-24,24>>^ E, quanto às dez pontas, daquele mesmo reino se levantarão dez reis; e depois deles se levantará outro, o qual será diferente dos primeiros, e abaterá a três reis.

[[v27-7-25]]

^<<v27-7-25,25>>^ E proferirá palavras contra o  Altíssimo, e destruirá os santos do Altíssimo, e cuidará em mudar os tempos, e a lei; e eles serão entregues na sua mão por um tempo, e tempos, e metade dum tempo.

[[v27-7-26]]

^<<v27-7-26,26>>^ Mas o juízo estabelecer-se-á, e eles tirarão o seu domínio, para o destruir e para o desfazer até ao fim.

[[v27-7-27]]

^<<v27-7-27,27>>^ E o reino, e o domínio, e a majestade dos reinos debaixo de todo o céu serão dados ao povo dos santos do Altíssimo: o seu reino será  um reino eterno, e todos os domínios o servirão, e lhe obedecerão.

[[v27-7-28]]

^<<v27-7-28,28>>^ Aqui findou a visão. Quanto a mim, Daniel, os meus pensamentos muito me espantavam, e mudou-se em mim o meu semblante; mas guardei estas cousas no meu coração.

'''

xref:027-daniel/027-daniel-006.adoc#v27-6-0[&#60; Capítulo Anterior] | <<v27-7-0,Topo>> | xref:027-daniel/027-daniel-008.adoc#v27-8-0[Próximo Capítulo &#62;]