include::./index.adoc[]

[[v27-9-0]]
=== Daniel, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v27-9-1]]

^<<v27-9-1,1>>^ NO ano primeiro de Dario, filho de Assuero, da nação dos medos, o qual foi constituído rei sobre o reino dos caldeus.

[[v27-9-2]]

^<<v27-9-2,2>>^ No ano primeiro do seu reinado, eu, Daniel entendi pelos livros que o número de anos, de que falou o Senhor ao profeta Jeremias, em que haviam de acabar as assolações de Jerusalém, era de setenta anos.

[[v27-9-3]]

^<<v27-9-3,3>>^ E eu dirigi o meu rosto ao Senhor Deus, para o buscar com  oração e rogos, com jejum, e saco e cinza.

[[v27-9-4]]

^<<v27-9-4,4>>^ E orei ao Senhor meu Deus, e confessei, e disse: Ah! Senhor! Deus grande e tremendo, que guardas o concerto e a misericórdia para com os que te amam e guardam os teus mandamentos;

[[v27-9-5]]

^<<v27-9-5,5>>^ Pecamos, e cometemos iniquidade, e procedemos impiamente, e fomos rebeldes, apartando-nos dos teus mandamentos e dos teus juízos;

[[v27-9-6]]

^<<v27-9-6,6>>^ E não demos ouvidos aos teus servos, os profetas, que em teu nome falaram aos nossos reis, nossos príncipes, e nossos pais, como também a todo o povo da terra.

[[v27-9-7]]

^<<v27-9-7,7>>^ A ti, ó Senhor, pertence a justiça, mas a nós a confusão de rosto, como se vê  neste dia; aos homens de Judá, e aos moradores de Jerusalém, e a todo o Israel; aos de perto e aos de longe, em todas as terras por onde os tens lançado, por causa da sua prevaricação, com que prevaricaram contra ti.

[[v27-9-8]]

^<<v27-9-8,8>>^ Ó Senhor, a nós pertence a confusão de rosto, aos nossos reis, aos nossos príncipes, e a nossos pais, porque pecamos contra ti.

[[v27-9-9]]

^<<v27-9-9,9>>^ Ao Senhor, nosso Deus, pertence a misericórdia e o perdão; pois nos rebelamos contra ele,

[[v27-9-10]]

^<<v27-9-10,10>>^ E não obedecemos à voz do Senhor, nosso Deus, para andarmos nas suas leis, que nos deu pela mão de seus servos, os profetas.

[[v27-9-11]]

^<<v27-9-11,11>>^ Sim, todo o Israel transgrediu a tua lei, desviando-se, para não obedecer à tua voz; por isso a maldição, o juramento que está  escrito na lei de Moisés, servo de Deus, se derramou sobre nós; porque pecamos contra ele.

[[v27-9-12]]

^<<v27-9-12,12>>^ E ele confirmou a sua palavra, que falou contra nós, e contra os nossos juízes que nos julgavam, trazendo sobre nós um  grande mal; porquanto nunca debaixo de todo o céu aconteceu como em Jerusalém.

[[v27-9-13]]

^<<v27-9-13,13>>^ Como está escrito na lei de Moisés, todo aquele mal nos sobreveio: apesar disso, não suplicamos à face do Senhor nosso Deus, para nos convertermos das nossas iniquidades, e para nos aplicarmos à tua verdade.

[[v27-9-14]]

^<<v27-9-14,14>>^ Por isso, o Senhor vigiou sobre o mal, e o trouxe sobre nós; porque justo é  o Senhor, nosso Deus, em todas as suas obras, que fez, pois não obedecemos à sua voz.

[[v27-9-15]]

^<<v27-9-15,15>>^ Na verdade, ó Senhor, nosso Deus, que tiraste o teu povo da terra do Egito com mão poderosa, e ganhaste para ti nome, como se vê  neste dia, pecamos; obramos impiamente.

[[v27-9-16]]

^<<v27-9-16,16>>^ Ó Senhor, segundo todas as tuas justiças, aparte-se a tua ira e o teu furor da tua cidade de Jerusalém, do teu santo monte; porquanto por causa dos nossos pecados, e por causa das iniquidades de nossos pais, tornou-se Jerusalém e o teu povo um opróbrio para todos os que estão em redor de nós.

[[v27-9-17]]

^<<v27-9-17,17>>^ Agora pois, ó Deus nosso, ouve a oração do teu servo, e as suas súplicas, e sobre o teu santuário assolado faze resplandecer o teu rosto, por amor do Senhor.

[[v27-9-18]]

^<<v27-9-18,18>>^ Inclina, ó Deus meu, os teus ouvidos; e ouve: abre os teus olhos, e olha para a nossa desolação, e para a cidade que é chamada pelo teu nome, porque não lançamos as nossas súplicas perante a tua face fiados em nossas justiças, mas em tuas muitas misericórdias.

[[v27-9-19]]

^<<v27-9-19,19>>^ Ó Senhor, ouve; ó Senhor, perdoa; ó Senhor, atende-nos e opera sem tardar; por amor de ti mesmo, ó Deus meu; porque a tua cidade e o teu povo se chamam pelo teu nome.

[[v27-9-20]]

^<<v27-9-20,20>>^ Estando eu ainda falando e orando, e confessando o meu pecado, e o pecado do meu povo Israel, e lançando a minha súplica perante a face do Senhor, meu Deus, pelo monte santo do meu Deus,

[[v27-9-21]]

^<<v27-9-21,21>>^ Estando eu, digo, ainda falando na oração, o varão Gabriel, que eu tinha visto na minha visão ao princípio, veio voando rapidamente, e tocou-me à hora do sacrifício da tarde.

[[v27-9-22]]

^<<v27-9-22,22>>^ E me  instruiu, e falou comigo, e disse: Daniel, agora saí para fazer-te entender o sentido.

[[v27-9-23]]

^<<v27-9-23,23>>^ No princípio das tuas súplicas, saiu a ordem, e eu vim, para to  declarar, porque és mui amado: toma pois bem sentido na palavra, e entende a visão.

[[v27-9-24]]

^<<v27-9-24,24>>^ Setenta semanas estão determinadas sobre o teu povo, e sobre a tua santa cidade, para extinguir a transgressão, e dar fim aos pecados, e para expiar a iniquidade, e trazer a justiça eterna, e selar a visão e a profecia, e para ungir o Santo dos santos.

[[v27-9-25]]

^<<v27-9-25,25>>^ Sabe e entende: desde a saída da ordem para restaurar e para edificar Jerusalém, até ao Messias, o Príncipe, sete semanas, e sessenta e duas semanas: as ruas e as tranqueiras se reedificarão, mas em tempos angustiosos.

[[v27-9-26]]

^<<v27-9-26,26>>^ E depois das sessenta e duas semanas será tirado o Messias, e não será mais: e o povo do príncipe, que há de vir, destruirá a cidade e o santuário, e o seu fim será com uma inundação; e até ao fim haverá guerra: estão determinadas assolações.

[[v27-9-27]]

^<<v27-9-27,27>>^ E ele firmará um concerto com muitos por uma semana: e na  metade da semana fará cessar o sacrifício e a oferta de manjares; e sobre a asa das abominações virá  o assolador, e isso  até à consumação; e o que está determinado será derramado sobre o assolador.

'''

xref:027-daniel/027-daniel-008.adoc#v27-8-0[&#60; Capítulo Anterior] | <<v27-9-0,Topo>> | xref:027-daniel/027-daniel-010.adoc#v27-10-0[Próximo Capítulo &#62;]