include::./index.adoc[]

[[v27-2-0]]
=== Daniel, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v27-2-1]]

^<<v27-2-1,1>>^ E NO segundo ano do reinado de Nabucodonosor teve Nabucodonosor uns sonhos; e o seu espírito se perturbou, e passou-se-lhe o seu sono.

[[v27-2-2]]

^<<v27-2-2,2>>^ E o rei mandou chamar os magos, e os astrólogos, e os encantadores, e os caldeus, para que declarassem ao rei qual tinha sido o seu sonho; e eles vieram e se apresentaram diante do rei.

[[v27-2-3]]

^<<v27-2-3,3>>^ E o rei lhes disse: Tive um  sonho; e para saber o sonho está perturbado o meu espírito.

[[v27-2-4]]

^<<v27-2-4,4>>^ E os caldeus disseram ao rei em siríaco: Ó rei, vive eternamente! dize o sonho a teus servos, e daremos a interpretação.

[[v27-2-5]]

^<<v27-2-5,5>>^ Respondeu o rei, e disse aos caldeus: O que foi me tem escapado; se me não fizerdes saber o sonho e a sua interpretação, sereis despedaçados, e as vossas casas serão feitas um  monturo;

[[v27-2-6]]

^<<v27-2-6,6>>^ Mas se vós me declarardes o sonho e a sua interpretação, recebereis de mim dons, e dádivas, e grande honra; portanto declarai-me o sonho e a sua interpretação.

[[v27-2-7]]

^<<v27-2-7,7>>^ Responderam segunda vez, e disseram: Diga o rei o sonho a seus servos, e daremos a sua interpretação.

[[v27-2-8]]

^<<v27-2-8,8>>^ Respondeu o rei, e disse: Percebo muito bem que vós quereis ganhar tempo; porque vedes que o que eu sonhei me tem escapado.

[[v27-2-9]]

^<<v27-2-9,9>>^ Por consequência, se me não fazeis saber o sonho, uma só sentença será a vossa: pois vós preparastes palavras mentirosas e perversas para as proferirdes na minha presença, até que se mude o tempo: portanto dizei-me o sonho, para que eu entenda que me podeis dar a sua interpretação.

[[v27-2-10]]

^<<v27-2-10,10>>^ Responderam os caldeus na presença do rei, e disseram: Não há ninguém sobre a terra que possa declarar a palavra ao rei; pois nenhum rei há, senhor ou dominador, que requeira cousa semelhante dalgum mago, ou astrólogo, ou caldeu.

[[v27-2-11]]

^<<v27-2-11,11>>^ Porquanto a cousa que o rei requer é  difícil, e ninguém há que a possa  declarar diante do rei, senão os deuses, cuja morada não é com a carne.

[[v27-2-12]]

^<<v27-2-12,12>>^ Então o rei muito se irou e enfureceu; e ordenou que matassem a todos os sábios de Babilônia.

[[v27-2-13]]

^<<v27-2-13,13>>^ E saiu o decreto, segundo o qual deviam ser mortos os sábios; e buscaram a Daniel e aos seus companheiros, para que fossem mortos.

[[v27-2-14]]

^<<v27-2-14,14>>^ Então Daniel falou avisada e prudentemente a Arioque, capitão da guarda do rei, que tinha saído para matar os sábios de Babilônia.

[[v27-2-15]]

^<<v27-2-15,15>>^ Respondeu, e disse a Arioque, prefeito do rei: Por que se apressa tanto  o mandado da parte do rei? Então Arioque explicou o caso a Daniel.

[[v27-2-16]]

^<<v27-2-16,16>>^ E Daniel entrou; e pediu ao rei que lhe desse tempo, para que pudesse dar a interpretação.

[[v27-2-17]]

^<<v27-2-17,17>>^ Então Daniel foi para a sua casa, e fez saber o caso a Hananias, Misael e Azarias, seus companheiros,

[[v27-2-18]]

^<<v27-2-18,18>>^ Para que pedissem misericórdia ao Deus do céu, sobre este segredo, a fim de que Daniel e seus companheiros não perecessem, com o resto dos sábios de Babilônia.

[[v27-2-19]]

^<<v27-2-19,19>>^ Então foi revelado o segredo a Daniel numa  visão de noite: então Daniel louvou o Deus do céu.

[[v27-2-20]]

^<<v27-2-20,20>>^ Falou Daniel, e disse: Seja bendito o nome de Deus para todo o sempre, porque dele é a sabedoria e a força;

[[v27-2-21]]

^<<v27-2-21,21>>^ Ele muda os tempos e as horas; ele remove os reis e estabelece os reis: ele dá sabedoria aos sábios e ciência aos entendidos.

[[v27-2-22]]

^<<v27-2-22,22>>^ Ele revela o profundo e o escondido: conhece o que está  em trevas, e com ele mora a luz.

[[v27-2-23]]

^<<v27-2-23,23>>^ Ó Deus de meus pais, eu te louvo e celebro porque me deste sabedoria e força; e agora me fizeste saber o que te pedimos, porque nos fizeste saber este assunto do rei.

[[v27-2-24]]

^<<v27-2-24,24>>^ Por isso Daniel foi ter com Arioque, ao qual o rei tinha constituído para matar os sábios de Babilônia: entrou, e disse-lhe assim: Não mates os  sábios de Babilônia; introduze-me na presença do rei, e darei ao rei a interpretação.

[[v27-2-25]]

^<<v27-2-25,25>>^ Então Arioque depressa introduziu Daniel na presença do rei, e disse-lhe assim: Achei um dentre os filhos dos cativos de Judá, o qual fará saber ao rei a interpretação.

[[v27-2-26]]

^<<v27-2-26,26>>^ Respondeu o rei, e disse a Daniel (cujo nome era  Beltessazar): Podes tu fazer-me saber o sonho que vi e a sua interpretação?

[[v27-2-27]]

^<<v27-2-27,27>>^ Respondeu Daniel na presença do rei, e disse: O segredo que o rei requer, nem  sábios, nem  astrólogos, nem  magos, nem  adivinhos o  podem descobrir ao rei;

[[v27-2-28]]

^<<v27-2-28,28>>^ Mas há um Deus nos céus, o qual revela os segredos; ele pois fez saber ao rei Nabucodonosor o que há de ser no fim dos dias; o teu sonho e as visões da tua cabeça na tua cama são estas:

[[v27-2-29]]

^<<v27-2-29,29>>^ Estando tu, ó rei, na tua cama, subiram os teus pensamentos ao que há de ser depois disto. Aquele pois que revela os segredos te fez saber o que há de ser.

[[v27-2-30]]

^<<v27-2-30,30>>^ E a mim me foi revelado este segredo, não porque haja em mim mais sabedoria do que em  todos os viventes, mas para que a interpretação se fizesse saber ao rei, e para que entendesses os pensamentos do teu coração.

[[v27-2-31]]

^<<v27-2-31,31>>^ Tu, ó rei, estavas vendo, e eis aqui uma grande estátua: esta estátua, que era grande e cujo esplendor era  excelente, estava em pé diante de ti; e a sua vista era  terrível.

[[v27-2-32]]

^<<v27-2-32,32>>^ A cabeça daquela estátua era  de ouro fino; o seu peito e os seus braços de prata; o seu ventre e as suas coxas de cobre;

[[v27-2-33]]

^<<v27-2-33,33>>^ As pernas de ferro; os seus pés em parte de ferro e em parte de barro.

[[v27-2-34]]

^<<v27-2-34,34>>^ Estavas vendo isto, quando uma pedra foi cortada, sem mão, a qual feriu a estátua nos pés de ferro e de barro, e os esmiuçou.

[[v27-2-35]]

^<<v27-2-35,35>>^ Então foi juntamente esmiuçado o ferro, o barro, o cobre, a prata e o ouro, os quais se fizeram como a pragana das eiras no estio, e o vento os levou, e não se achou lugar algum para eles; mas a pedra, que feriu a estátua, se fez um  grande monte, e encheu toda a terra.

[[v27-2-36]]

^<<v27-2-36,36>>^ Este é o sonho; também a interpretação dele diremos na presença do rei.

[[v27-2-37]]

^<<v27-2-37,37>>^ Tu, ó rei, és  rei de reis: pois o Deus do céu te tem dado o reino, o poder, e a força, e a majestade.

[[v27-2-38]]

^<<v27-2-38,38>>^ E onde quer que habitem filhos de homens, animais do campo, e aves do céu, ele tos entregou na tua mão, e fez que dominasses sobre todos eles; tu és a cabeça de ouro.

[[v27-2-39]]

^<<v27-2-39,39>>^ E depois de ti se levantará outro reino, inferior ao teu; e um terceiro reino, de metal, o qual terá domínio sobre toda a terra.

[[v27-2-40]]

^<<v27-2-40,40>>^ E o quarto reino será forte como ferro; pois, como o ferro esmiúça e quebra tudo, como o ferro quebra todas as cousas, ele esmiuçará e quebrantará.

[[v27-2-41]]

^<<v27-2-41,41>>^ E, quanto ao que viste dos pés e dos dedos, em parte de barro de oleiro, e em parte de ferro, isso será um  reino dividido; contudo haverá nele alguma cousa  da firmeza do ferro, pois que viste o ferro misturado com barro de lodo.

[[v27-2-42]]

^<<v27-2-42,42>>^ E como os dedos dos pés eram em parte de ferro e em parte de barro, assim por uma parte o reino será forte, e por outra será frágil.

[[v27-2-43]]

^<<v27-2-43,43>>^ Quanto ao que viste do ferro misturado com barro de lodo, misturar-se-ão com semente humana, mas não se ligarão um ao outro, assim como o ferro se não mistura com o barro.

[[v27-2-44]]

^<<v27-2-44,44>>^ Mas, nos dias destes reis, o Deus do céu levantará um reino que não será jamais destruído; e este reino não passará a outro povo: esmiuçará e consumirá todos estes reinos, e será estabelecido para sempre.

[[v27-2-45]]

^<<v27-2-45,45>>^ Da maneira como viste que do monte foi cortada uma pedra, sem mãos, e ela esmiuçou o ferro, o cobre, o barro, a prata e o ouro, o Deus grande fez saber ao rei o que há de ser depois disto; e certo é o sonho, e fiel a sua interpretação.

[[v27-2-46]]

^<<v27-2-46,46>>^ Então o rei Nabucodonosor caiu sobre o seu rosto, e adorou a Daniel, e ordenou que lhe fizessem oferta de manjares e perfumes suaves.

[[v27-2-47]]

^<<v27-2-47,47>>^ Respondeu o rei a Daniel, e disse: Certamente, o vosso Deus é  Deus dos deuses, e o Senhor dos reis, e o revelador dos segredos, pois pudeste revelar este segredo.

[[v27-2-48]]

^<<v27-2-48,48>>^ Então o rei engrandeceu a Daniel, e lhe deu muitos e  grandes dons e o pôs por governador de toda a província de Babilônia, como também por principal governador de todos os sábios de Babilônia.

[[v27-2-49]]

^<<v27-2-49,49>>^ E pediu Daniel ao rei, e constituiu ele sobre os negócios da província de Babilônia a Sadraque, Mesaque e Abednego; mas Daniel estava  às portas do rei.

'''

xref:027-daniel/027-daniel-001.adoc#v27-1-0[&#60; Capítulo Anterior] | <<v27-2-0,Topo>> | xref:027-daniel/027-daniel-003.adoc#v27-3-0[Próximo Capítulo &#62;]