include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v27-8-1]]

^<<v27-8-1,1>>^ NO ano terceiro do reinado do rei Belsazar apareceu-me uma visão, a mim, Daniel, depois daquela que me apareceu no princípio.

[[v27-8-2]]

^<<v27-8-2,2>>^ E vi na visão (acontecendo, quando vi, que eu estava  na cidadela de Susã, na província de Elão), vi pois, na visão, que eu estava junto ao rio Ulai.

[[v27-8-3]]

^<<v27-8-3,3>>^ E levantei os meus olhos, e vi, e eis que um carneiro estava diante do rio, o qual tinha duas pontas; e as duas pontas eram altas, mas uma era  mais alta do que a outra; e a mais alta subiu por último.

[[v27-8-4]]

^<<v27-8-4,4>>^ Vi que o carneiro dava marradas para o ocidente, e para o norte e para o meio-dia; e nenhuns animais podiam estar diante dele, nem havia  quem pudesse livrar-se da sua mão; e ele fazia conforme a sua vontade, e se engrandecia.

[[v27-8-5]]

^<<v27-8-5,5>>^ E, estando eu considerando, eis que um bode vinha do ocidente sobre toda a terra, mas sem tocar no chão; e aquele bode tinha uma ponta notável entre os olhos;

[[v27-8-6]]

^<<v27-8-6,6>>^ Dirigiu-se ao carneiro que tinha as duas pontas, ao qual eu tinha visto diante do rio; e correu contra ele com todo  o ímpeto da sua força.

[[v27-8-7]]

^<<v27-8-7,7>>^ E o vi chegar perto do carneiro, irritar-se contra ele; e feriu o carneiro, e lhe quebrou as duas pontas, pois não havia força no carneiro para parar diante dele; e o lançou por terra, e o pisou a pés; não houve quem pudesse livrar o carneiro da sua mão.

[[v27-8-8]]

^<<v27-8-8,8>>^ E o bode se engrandeceu em grande maneira; mas, estando na sua maior  força, aquela grande ponta foi quebrada: e subiram no seu lugar quatro também  notáveis, para os quatro ventos do céu.

[[v27-8-9]]

^<<v27-8-9,9>>^ E de uma delas saiu uma ponta mui pequena, a qual cresceu muito para o meio-dia, e para o oriente, e para a terra  formosa.

[[v27-8-10]]

^<<v27-8-10,10>>^ E se engrandeceu até ao exército do céu; e a alguns do exército, e das estrelas, deitou por terra, e as pisou.

[[v27-8-11]]

^<<v27-8-11,11>>^ E se engrandeceu até ao príncipe do exército: e por ele foi tirado o contínuo sacrifício , e o lugar do seu santuário foi lançado por terra.

[[v27-8-12]]

^<<v27-8-12,12>>^ E o exército lhe  foi entregue, com o sacrifício  contínuo, por causa das transgressões; e lançou a verdade por terra; fez isso, e prosperou.

[[v27-8-13]]

^<<v27-8-13,13>>^ Depois ouvi um santo que falava; e disse outro santo àquele que falava: Até quando durará a visão do contínuo sacrifício , e da transgressão assoladora para que seja entregue o santuário, e o exército, a fim de serem pisados?

[[v27-8-14]]

^<<v27-8-14,14>>^ E ele me disse: Até duas mil e trezentas tardes e manhãs; e o santuário será purificado.

[[v27-8-15]]

^<<v27-8-15,15>>^ E aconteceu que, havendo eu, Daniel, visto a visão, busquei entendê-la e eis que se me apresentou diante uma como semelhança de homem.

[[v27-8-16]]

^<<v27-8-16,16>>^ E ouvi uma voz de homem nas margens  do Ulai, a qual gritou, e disse: Gabriel, dá a entender a este a visão.

[[v27-8-17]]

^<<v27-8-17,17>>^ E veio perto donde eu estava; e vindo ele, fiquei assombrado, e caí sobre o meu rosto; mas ele me disse: Entende, filho do homem, porque esta visão se realizará no fim do tempo.

[[v27-8-18]]

^<<v27-8-18,18>>^ E, estando ele falando comigo, caí com o meu rosto em terra, adormecido; ele, pois, me tocou, e me fez estar em pé.

[[v27-8-19]]

^<<v27-8-19,19>>^ E disse: Eis que te farei saber o que há de acontecer no último tempo da ira; porque ela se exercerá no determinado tempo do fim.

[[v27-8-20]]

^<<v27-8-20,20>>^ Aquele carneiro que viste com duas pontas são  os reis da Média e da Pérsia,

[[v27-8-21]]

^<<v27-8-21,21>>^ Mas o bode peludo é o rei da Grécia; e a ponta grande que tinha  entre os olhos é  o rei primeiro;

[[v27-8-22]]

^<<v27-8-22,22>>^ O ter sido quebrada, levantando-se quatro em lugar dela, significa que  quatro reinos se levantarão da mesma  nação, mas não com a força dela.

[[v27-8-23]]

^<<v27-8-23,23>>^ Mas, no fim do seu reinado, quando os prevaricadores acabarem, se levantará um rei, feroz de cara, e será  entendido em adivinhações.

[[v27-8-24]]

^<<v27-8-24,24>>^ E se fortalecerá a sua força, mas não pelo seu próprio poder; e destruirá maravilhosamente, e prosperará, e fará o que lhe aprouver: e destruirá os fortes e o povo santo.

[[v27-8-25]]

^<<v27-8-25,25>>^ E pelo seu entendimento também fará prosperar o engano na sua mão; e no seu coração se engrandecerá, e por causa da tranquilidade destruirá muitos, e se levantará contra o príncipe dos príncipes, mas sem mão será quebrado.

[[v27-8-26]]

^<<v27-8-26,26>>^ E a visão da tarde e da manhã, que foi dita, é verdadeira: tu, porém, cerra a visão, porque só daqui a muitos dias se cumprirá.

[[v27-8-27]]

^<<v27-8-27,27>>^ E eu, Daniel, enfraqueci, e estive enfermo alguns  dias; então levantei-me e tratei do negócio do rei: e espantei-me acerca da visão, e não havia quem a entendesse.

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]