include::./index.adoc[]

[[v27-5-0]]
=== Daniel, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v27-5-1]]

^<<v27-5-1,1>>^ O REI Belsazar deu um grande banquete a mil dos seus grandes, e bebeu vinho na presença dos mil.

[[v27-5-2]]

^<<v27-5-2,2>>^ Havendo Belsazar provado o vinho, mandou trazer os vasos de ouro e de prata, que Nabucodonosor, seu pai, tinha tirado do templo que estava  em Jerusalém, para que bebessem por eles o rei, e os seus grandes, as suas mulheres e concubinas.

[[v27-5-3]]

^<<v27-5-3,3>>^ Então trouxeram os vasos de ouro, que foram tirados do templo da casa de Deus, que estava em Jerusalém, e beberam por eles o rei, os seus grandes, as suas mulheres e concubinas.

[[v27-5-4]]

^<<v27-5-4,4>>^ Beberam o vinho, e deram louvores aos deuses de ouro, e de prata, de cobre, de ferro, de madeira, e de pedra.

[[v27-5-5]]

^<<v27-5-5,5>>^ Na mesma hora apareceram uns dedos de mão de homem, e escreviam, defronte do castiçal, na estucada parede do palácio real; e o rei via a parte da mão que estava escrevendo.

[[v27-5-6]]

^<<v27-5-6,6>>^ Então se mudou o semblante do rei, e os seus pensamentos o turbaram: as juntas dos seus lombos se relaxaram, e os seus joelhos bateram um no outro.

[[v27-5-7]]

^<<v27-5-7,7>>^ E ordenou o rei com força, que se introduzissem os astrólogos, os caldeus e os adivinhadores: e  falou o rei, e disse aos sábios de Babilônia: Qualquer que ler esta escritura, e me declarar a sua interpretação, será vestido de púrpura, e trará uma cadeia de ouro ao pescoço, e será, no reino, o terceiro dominador.

[[v27-5-8]]

^<<v27-5-8,8>>^ Então entraram todos os sábios do rei; mas não puderam ler a escritura, nem fazer saber ao rei a sua interpretação.

[[v27-5-9]]

^<<v27-5-9,9>>^ Então o rei Belsazar perturbou-se muito, e mudou-se nele o seu semblante; e os seus grandes estavam sobressaltados.

[[v27-5-10]]

^<<v27-5-10,10>>^ A rainha, por causa das palavras do rei e dos seus grandes, entrou na casa do banquete: e falou a rainha, e disse: Ó rei, vive para sempre! não te turbem os teus pensamentos nem se mude o teu semblante.

[[v27-5-11]]

^<<v27-5-11,11>>^ Há no teu reino um homem, que tem o espírito dos deuses santos; e nos dias de teu pai se achou nele luz, e inteligência, e sabedoria, como a sabedoria dos deuses; e teu pai, o rei Nabucodonosor, sim, teu pai, ó rei, o constituiu chefe dos magos, dos astrólogos, dos caldeus, e  dos adivinhadores.

[[v27-5-12]]

^<<v27-5-12,12>>^ Porquanto se achou neste Daniel um espírito excelente, e ciência e entendimento, interpretando sonhos, e explicando enigmas, e solvendo dúvidas, ao qual o rei pôs o nome de Beltessazar: chame-se pois  agora Daniel, e ele dará interpretação.

[[v27-5-13]]

^<<v27-5-13,13>>^ Então Daniel foi introduzido à presença do rei. Falou o rei, e disse a Daniel: És tu aquele Daniel, dos cativos de Judá, que o rei, meu pai, trouxe de Judá?

[[v27-5-14]]

^<<v27-5-14,14>>^ Tenho ouvido dizer  a teu respeito que o espírito dos deuses está em ti, e que a luz, e o entendimento e a excelente sabedoria se acham em ti.

[[v27-5-15]]

^<<v27-5-15,15>>^ Acabam de ser introduzidos à minha presença os sábios e  os astrólogos, para lerem esta escritura, e me fazerem saber a sua interpretação; mas não puderam dar a interpretação destas palavras.

[[v27-5-16]]

^<<v27-5-16,16>>^ Eu porém tenho ouvido dizer de ti que podes dar interpretações e solver dúvidas: agora, se puderes ler esta escritura, e fazer-me saber a sua interpretação, serás vestido de púrpura, e terás  cadeia de ouro ao pescoço, e no reino serás o terceiro dominador.

[[v27-5-17]]

^<<v27-5-17,17>>^ Então respondeu Daniel, e disse na presença do rei: Os teus dons fiquem contigo, e dá os teus presentes a outro; todavia lerei ao rei a escritura, e lhe farei saber a interpretação.

[[v27-5-18]]

^<<v27-5-18,18>>^ Ó rei! Deus, o Altíssimo, deu a Nabucodonosor, teu pai, o reino, e a grandeza, e a glória, e a magnificência.

[[v27-5-19]]

^<<v27-5-19,19>>^ E por causa da grandeza, que lhe deu todos os povos, nações e línguas tremiam e temiam diante dele: a quem queria matava, e a quem queria dava a vida; e a quem queria engrandecia, e a quem queria abatia.

[[v27-5-20]]

^<<v27-5-20,20>>^ Mas quando o seu coração se exalçou, e o seu espírito se endureceu em soberba, foi derribado do seu trono real, e passou dele a sua  glória.

[[v27-5-21]]

^<<v27-5-21,21>>^ E foi tirado dentre os filhos dos homens, e o seu coração foi feito semelhante ao dos animais, e a sua morada foi com os jumentos monteses; fizeram-no comer erva como os bois, e pelo orvalho do céu foi molhado o seu corpo, até que conheceu que Deus, o Altíssimo, tem domínio sobre os reinos dos homens, e a quem quer constitui sobre eles.

[[v27-5-22]]

^<<v27-5-22,22>>^ E tu, seu filho Belsazar, não humilhaste o teu coração, ainda que soubeste de tudo isto.

[[v27-5-23]]

^<<v27-5-23,23>>^ E te levantaste contra o Senhor do céu, pois foram trazidos os vasos da casa dele perante ti, e tu, os teus grandes, as tuas mulheres e as tuas concubinas, bebestes vinho por eles; além disto, deste louvores aos deuses de prata, de ouro, de cobre, de ferro, de madeira e de pedra que não veem, não ouvem, nem sabem; mas a Deus, em cuja mão está  a tua vida, e todos os teus caminhos, a ele não glorificaste.

[[v27-5-24]]

^<<v27-5-24,24>>^ Então dele foi enviada aquela parte da mão, e escreveu-se esta escritura.

[[v27-5-25]]

^<<v27-5-25,25>>^ Esta pois é  a escritura que se escreveu: Mene , Mene , Tequel , Ufarsim .

[[v27-5-26]]

^<<v27-5-26,26>>^ Esta é  a interpretação daquilo: Mene : Contou Deus o teu reino e o acabou.

[[v27-5-27]]

^<<v27-5-27,27>>^ Tequel : Pesado foste na balança, e foste achado em falta.

[[v27-5-28]]

^<<v27-5-28,28>>^ Peres : Dividido foi o teu reino, e deu-se aos medos e aos persas.

[[v27-5-29]]

^<<v27-5-29,29>>^ Então mandou Belsazar que vestissem a Daniel de púrpura, e que lhe pusessem uma  cadeia de ouro ao pescoço, e proclamassem a respeito dele que havia de ser o terceiro dominador do reino.

[[v27-5-30]]

^<<v27-5-30,30>>^ Naquela mesma noite foi morto Belsazar, rei dos caldeus.

[[v27-5-31]]

^<<v27-5-31,31>>^ E Dario, o medo, ocupou o reino, na idade de sessenta e dois anos.

'''

xref:027-daniel/027-daniel-004.adoc#v27-4-0[&#60; Capítulo Anterior] | <<v27-5-0,Topo>> | xref:027-daniel/027-daniel-006.adoc#v27-6-0[Próximo Capítulo &#62;]