include::./index.adoc[]

[[v27-10-0]]
=== Daniel, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v27-10-1]]

^<<v27-10-1,1>>^ NO ano terceiro de Ciro, rei da Pérsia, foi revelada uma  palavra a Daniel, cujo nome se chama Beltessazar; e a palavra é  verdadeira, e trata duma guerra prolongada; e ele entendeu esta palavra, e teve entendimento da visão.

[[v27-10-2]]

^<<v27-10-2,2>>^ Naqueles dias eu, Daniel, estive triste por três semanas completas.

[[v27-10-3]]

^<<v27-10-3,3>>^ Manjar desejável não comi, nem carne nem vinho entraram na minha boca, nem me ungi com unguento, até que se cumpriram as três semanas.

[[v27-10-4]]

^<<v27-10-4,4>>^ E no dia vinte e quatro do primeiro mês eu estava à borda do grande rio Hidequel;

[[v27-10-5]]

^<<v27-10-5,5>>^ E levantei os meus olhos, e olhei, e vi um homem vestido de linho, e os seus lombos cingidos com ouro fino de Ufaz:

[[v27-10-6]]

^<<v27-10-6,6>>^ E o seu corpo era  como turquesa, e o seu rosto parecia um relâmpago, e os seus olhos como tochas de fogo, e os seus braços e os seus pés como cor de bronze açacalado; e a voz das suas palavras como a voz duma multidão.

[[v27-10-7]]

^<<v27-10-7,7>>^ E só eu, Daniel, vi aquela visão; os homens que estavam  comigo não a viram: não obstante, caiu sobre eles um grande temor, e fugiram, escondendo-se.

[[v27-10-8]]

^<<v27-10-8,8>>^ Fiquei pois eu só, e vi esta grande visão, e não ficou força em mim: e transmudou-se em mim a minha formosura em desmaio, e não retive força alguma.

[[v27-10-9]]

^<<v27-10-9,9>>^ Contudo, ouvi a voz das suas palavras; e, ouvindo a voz das suas palavras, eu caí com o meu rosto em terra, profundamente adormecido.

[[v27-10-10]]

^<<v27-10-10,10>>^ E eis que uma mão me tocou, e fez que me movesse sobre os meus joelhos e sobre as palmas das minhas mãos.

[[v27-10-11]]

^<<v27-10-11,11>>^ E me disse: Daniel, homem mui desejado, está atento às palavras que te vou dizer, e levanta-te sobre os teus pés; porque eis que te sou enviado. E, falando ele comigo esta palavra, eu estava tremendo.

[[v27-10-12]]

^<<v27-10-12,12>>^ Então me disse: Não temas, Daniel, porque desde o primeiro dia, em que aplicaste o teu coração a compreender e a humilhar-te perante o teu Deus, são ouvidas as tuas palavras; e eu vim por causa das tuas palavras.

[[v27-10-13]]

^<<v27-10-13,13>>^ Mas o príncipe do reino da Pérsia se pôs defronte de mim vinte e um dias, e eis que Miguel, um dos primeiros príncipes, veio para ajudar-me, e eu fiquei ali com os reis da Pérsia.

[[v27-10-14]]

^<<v27-10-14,14>>^ Agora vim, para fazer-te entender o que há de acontecer ao teu povo nos derradeiros dias; porque a visão é ainda para muitos  dias.

[[v27-10-15]]

^<<v27-10-15,15>>^ E, falando ele comigo estas palavras, abaixei o meu rosto, e emudeci.

[[v27-10-16]]

^<<v27-10-16,16>>^ E eis que uma como semelhança dos filhos dos homens me tocou os lábios: então abri a minha boca, e falei, e disse àquele que estava diante de mim: Senhor meu, por causa da visão sobrevieram-me dores, e não me ficou força alguma.

[[v27-10-17]]

^<<v27-10-17,17>>^ Como pois pode o servo deste meu Senhor falar com aquele meu Senhor? porque, quanto a mim, desde agora não resta força em mim, e não ficou em mim fôlego.

[[v27-10-18]]

^<<v27-10-18,18>>^ E uma como semelhança dum homem me tocou outra vez, e me confortou.

[[v27-10-19]]

^<<v27-10-19,19>>^ E disse: Não temas, homem mui desejado, paz seja  contigo; anima-te, sim, anima-te. E, falando ele comigo, esforcei-me, e disse: Fala, meu Senhor, porque me confortaste.

[[v27-10-20]]

^<<v27-10-20,20>>^ E disse: Sabes porque eu vim a ti? Eu tornarei a pelejar contra o príncipe dos persas; e, saindo eu, eis que virá o príncipe da Grécia.

[[v27-10-21]]

^<<v27-10-21,21>>^ Mas eu te declararei o que está escrito na escritura da verdade; e ninguém há  que se esforce comigo contra aqueles, a não ser Miguel, vosso príncipe.

'''

xref:027-daniel/027-daniel-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-daniel/027-daniel-011.adoc#v27-11-0[Próximo Capítulo &#62;]