include::./index.adoc[]

[[v13-27-0]]
=== 1 Crônicas, 27
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-27-1]]

^<<v13-27-1,1>>^ ESTES são  os filhos de Israel segundo o seu número, os chefes dos pais, e os capitães dos milhares e das centenas, com os seus oficiais, que serviam ao rei em todos os negócios das turmas entrando e saindo de mês em mês, em todos os meses do ano: cada turma de vinte e quatro mil.

[[v13-27-2]]

^<<v13-27-2,2>>^ Sobre a primeira turma do mês primeiro estava Jasobeão, filho de Zabdiel: e em sua turma havia  vinte e quatro mil.

[[v13-27-3]]

^<<v13-27-3,3>>^ Era  este dos filhos de Perez, chefe de todos os capitães dos exércitos, para o primeiro mês.

[[v13-27-4]]

^<<v13-27-4,4>>^ E sobre a turma do segundo mês era  Dodai, o aoíta, com a sua turma, cujo chefe era  Miclote: também em sua turma havia  vinte e quatro mil.

[[v13-27-5]]

^<<v13-27-5,5>>^ O terceiro capitão do exército do terceiro mês era  Benaia, filho de Joiada, oficial maior e  chefe: também em sua turma havia  vinte e quatro mil.

[[v13-27-6]]

^<<v13-27-6,6>>^ Era  este Benaia um  varão entre os trinta, e sobre os trinta: e sobre  a sua turma estava  Amizabade, seu filho.

[[v13-27-7]]

^<<v13-27-7,7>>^ O quarto do quarto mês Asael, irmão de Joabe, e depois dele Zebadias, seu filho: também em sua turma havia  vinte e quatro mil.

[[v13-27-8]]

^<<v13-27-8,8>>^ O quinto do quinto mês o maioral Samute, o israíta: também em sua turma havia  vinte e quatro mil.

[[v13-27-9]]

^<<v13-27-9,9>>^ O sexto do sexto mês Ira, filho de Iques, o tecoíta: também em sua turma havia  vinte e quatro mil.

[[v13-27-10]]

^<<v13-27-10,10>>^ O sétimo do sétimo mês Heles, o pelonita, dos filhos de Efraim: também em sua turma havia  vinte e quatro mil.

[[v13-27-11]]

^<<v13-27-11,11>>^ O oitavo do oitavo mês Sibecai, o husatita, dos zaritas: também em sua turma havia  vinte e quatro mil.

[[v13-27-12]]

^<<v13-27-12,12>>^ O nono do nono mês Abiezer, o anatotita, dos benjaminitas: também em sua turma havia  vinte e quatro mil.

[[v13-27-13]]

^<<v13-27-13,13>>^ O décimo do décimo mês Maarai, o netofatita, dos zaritas: também em sua turma havia  vinte e quatro mil.

[[v13-27-14]]

^<<v13-27-14,14>>^ O undécimo do undécimo mês Benaia, o piratonita, dos filhos de Efraim: também em sua turma havia  vinte e quatro mil.

[[v13-27-15]]

^<<v13-27-15,15>>^ O duodécimo do duodécimo mês, Heldia, o netofatita, de Otniel: também em sua turma havia  vinte quatro mil.

[[v13-27-16]]

^<<v13-27-16,16>>^ Porém sobre as tribos de Israel eram estes : sobre os rubenitas era  chefe Eliézer, filho de Zicri; sobre os simeonitas, Sefatias, filho de Maaca:

[[v13-27-17]]

^<<v13-27-17,17>>^ Sobre os levitas, Hasabias, filho de Quemuel: sobre os aaronitas, Zadoque;

[[v13-27-18]]

^<<v13-27-18,18>>^ Sobre Judá, Eliú, dos irmãos de Davi; sobre Issacar, Onri, filho de Micael;

[[v13-27-19]]

^<<v13-27-19,19>>^ Sobre Zebulom, Irmaías, filho de Obadias; sobre Naftali, Jerimote, filho de Azriel;

[[v13-27-20]]

^<<v13-27-20,20>>^ Sobre os filhos de Efraim, Oseias, filho de Azazias; sobre a meia tribo de Manassés, Joel, filho de Pedaías;

[[v13-27-21]]

^<<v13-27-21,21>>^ Sobre a outra  meia tribo de Manassés em Gileade, Ido, filho de Zacarias; sobre Benjamim, Jaasiel, filho de Abner;

[[v13-27-22]]

^<<v13-27-22,22>>^ Sobre Dã, Azarel, filho de Jeroão; estes eram  os capitães das tribos de Israel.

[[v13-27-23]]

^<<v13-27-23,23>>^ Não tomou porém Davi o número dos de vinte anos e daí  para baixo, porquanto o Senhor tinha dito que havia de multiplicar a Israel como as estrelas do céu.

[[v13-27-24]]

^<<v13-27-24,24>>^ Joabe, filho de Zeruia, tinha começado a numerá- los , porém não acabou, porquanto viera por isso grande ira sobre Israel: pelo que o número se não pôs na conta das crônicas do rei Davi.

[[v13-27-25]]

^<<v13-27-25,25>>^ E sobre os tesouros do rei estava  Azmavete, filho de Adiel; e sobre os tesouros da terra, das cidades, e das aldeias, e das torres, Jônatas, filho de Uzias.

[[v13-27-26]]

^<<v13-27-26,26>>^ E sobre os que faziam a obra do campo, na lavoura da terra, Ezri, filho de Quelube.

[[v13-27-27]]

^<<v13-27-27,27>>^ E sobre as vinhas, Simei, o ramatita; porém sobre o que das vides entrava nos tesouros do vinho, Zabdi o sifmita.

[[v13-27-28]]

^<<v13-27-28,28>>^ E sobre os olivais e figueiras bravas que havia  nas campinas, Baal-Hanã, o gederita: porém Joás sobre os tesouros do azeite.

[[v13-27-29]]

^<<v13-27-29,29>>^ E sobre os gados que pasciam em Sarom, Sitrai, o saronita: porém sobre os gados dos vales, Safate, filho de Adlai.

[[v13-27-30]]

^<<v13-27-30,30>>^ E sobre os camelos, Obil, o ismaelita: e sobre as jumentas, Jedias, o meronotita.

[[v13-27-31]]

^<<v13-27-31,31>>^ E sobre o gado miúdo, Jaziz, o hagarita: todos estes eram  maiorais da fazenda que tinha o rei Davi.

[[v13-27-32]]

^<<v13-27-32,32>>^ E Jônatas, tio de Davi, era  do conselho, homem entendido, e também escriba: e Jeiel, filho de Hacmoni, estava  com os filhos do rei.

[[v13-27-33]]

^<<v13-27-33,33>>^ E Aquitófel era do conselho do rei: e Husai, o arquita, amigo do rei.

[[v13-27-34]]

^<<v13-27-34,34>>^ E depois de Aquitófel, Joiada, filho de Benaia, e Abiatar; porém Joabe era  chefe do exército do rei.

'''

xref:013-1-cronicas/013-1-cronicas-026.adoc#v13-26-0[&#60; Capítulo Anterior] | <<v13-27-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[Próximo Capítulo &#62;]