include::./index.adoc[]

[[v13-4-0]]
=== 1 Crônicas, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-4-1]]

^<<v13-4-1,1>>^ OS filhos de Judá foram : Perez, e Hezrom, e Carmi, e Hur, e Sobal.

[[v13-4-2]]

^<<v13-4-2,2>>^ E Reaías, filho de Sobal, gerou a Jaate, e Jaate gerou a Aumai e a Laade: estas são  as famílias dos zoratitas.

[[v13-4-3]]

^<<v13-4-3,3>>^ E estes foram os filhos do pai de Etão: Jezreel, e Isma, e Idbas: e era  o nome de sua irmã Hazelelpôni.

[[v13-4-4]]

^<<v13-4-4,4>>^ E mais Penuel, pai de Gedor, e Ezer, pai de Husa: estes foram  os filhos de Hur, o primogênito de Efrata, pai de Belém.

[[v13-4-5]]

^<<v13-4-5,5>>^ E tinha Assur, pai de Técoa, duas mulheres: Hela e Naara.

[[v13-4-6]]

^<<v13-4-6,6>>^ E Naara deu à luz a Auzão, e a Hefer, e a Temeni, e a Haastari; estes foram  os filhos de Naara.

[[v13-4-7]]

^<<v13-4-7,7>>^ E os filhos de Hela: Zerete, Jesoar, e Etnã.

[[v13-4-8]]

^<<v13-4-8,8>>^ E Cós gerou a Anube e a Zobeba: e as famílias de Aarel, filho de Harum.

[[v13-4-9]]

^<<v13-4-9,9>>^ E foi Jabes mais ilustre do que seus irmãos: e sua mãe chamou o seu nome Jabes, dizendo: Porquanto com dores o dei à luz.

[[v13-4-10]]

^<<v13-4-10,10>>^ Porque Jabes invocou o Deus de Israel, dizendo: Se me abençoares muitíssimo, e meus termos amplificares, e a tua mão for comigo, e fizeres que do mal não seja aflito!... E Deus lhe concedeu o que lhe tinha pedido.

[[v13-4-11]]

^<<v13-4-11,11>>^ E Quelube, irmão de Suá, gerou a Meir: este é  o pai de Estom.

[[v13-4-12]]

^<<v13-4-12,12>>^ E Estom gerou a Betrafa, e a Peseia, e a Teina, pai de Ir-Naás; estes foram  os homens de Reca.

[[v13-4-13]]

^<<v13-4-13,13>>^ E foram os filhos de Canas: Otniel e Seraías; e filhos de Otniel: Hatate.

[[v13-4-14]]

^<<v13-4-14,14>>^ E Meonotai gerou a Ofra, e Seraías gerou a Joabe, pai dos do vale dos artífices; porque foram artífices.

[[v13-4-15]]

^<<v13-4-15,15>>^ E foram  os filhos de Calebe, filho de Jefoné: Iru, Elá, e Naã: e os filhos de Elá, a saber, Quenaz.

[[v13-4-16]]

^<<v13-4-16,16>>^ E os filhos de Jealelel: Zife, e Zifa, e Tíria e Asareel.

[[v13-4-17]]

^<<v13-4-17,17>>^ E os filhos de Ezra: Jéter, e Merede, e Efer e Jalom: e teve mais a Miriã, e Samai, e Isbá, pai de Estemo.

[[v13-4-18]]

^<<v13-4-18,18>>^ E sua mulher, judia, gerou a Jerede, pai de Gedor, e a Héber, pai de Socó, e a Jecutiel, pai de Zanoa; e estes foram  os filhos de Bitia, filha de Faraó, que Merede tomou.

[[v13-4-19]]

^<<v13-4-19,19>>^ E foram  os filhos da mulher de Hodias, irmã de Naã: Abiqueila, o garmita, e Estemo, o maacatita.

[[v13-4-20]]

^<<v13-4-20,20>>^ E os filhos de Simeão: Amom, e Rina, e Benanã, e Tilom: e os filhos de Isi: Zoete e Benzoete.

[[v13-4-21]]

^<<v13-4-21,21>>^ Os filhos de Sela, filho de Judá: Er, pai de Leca, e Lada, pai de Maresa, e as famílias da casa dos obreiros de linho, em casa de Asbeia.

[[v13-4-22]]

^<<v13-4-22,22>>^ Como também Joquim, e os homens de Cozeba, e Joás, e Sarafe (que dominaram sobre os moabitas), e Jasubilém; porém estas  cousas já são  antigas.

[[v13-4-23]]

^<<v13-4-23,23>>^ Estes foram  oleiros, e habitavam nas hortas e nos cerrados; estes ficaram ali com o rei na sua obra.

[[v13-4-24]]

^<<v13-4-24,24>>^ Os filhos de Simeão foram : Nemuel, e Jamim, e Jaribe, e Zerá, e Saul,

[[v13-4-25]]

^<<v13-4-25,25>>^ Cujo filho foi  Salum, e seu filho Mibsão, e seu filho Misma.

[[v13-4-26]]

^<<v13-4-26,26>>^ E os filhos de Misma foram : Hamuel, seu filho, seu filho Zacur, e seu filho Simei.

[[v13-4-27]]

^<<v13-4-27,27>>^ E Simei teve dezesseis filhos, e seis filhas, porém seus irmãos não tiveram muitos filhos: e toda a sua família não se multiplicou tanto como as dos filhos de Judá.

[[v13-4-28]]

^<<v13-4-28,28>>^ E habitaram em Berseba, e em  Moluda, e em  Hazar-Sual,

[[v13-4-29]]

^<<v13-4-29,29>>^ E em Bilha, e em Ezém, e em Tolade,

[[v13-4-30]]

^<<v13-4-30,30>>^ E em Betuel, e em Hormá, e em Ziclague,

[[v13-4-31]]

^<<v13-4-31,31>>^ E em Bete-Marcabote, e em Hazar-Susim, e Bete-Biri, em Saaraim: estas foram  as suas cidades, até que Davi reinou.

[[v13-4-32]]

^<<v13-4-32,32>>^ E foram  as suas aldeias: Etã, e Aim, e Rimom, e Toquém, e Asã: cinco cidades,

[[v13-4-33]]

^<<v13-4-33,33>>^ E todas as suas aldeias, que estavam  em redor destas cidades, até Baal. Estas foram  as suas habitações e suas genealogias.

[[v13-4-34]]

^<<v13-4-34,34>>^ Porém Mesobabe, a Janleque e Josa, filho de Amazias.

[[v13-4-35]]

^<<v13-4-35,35>>^ E Joel, e Jeú, filho de Josibias, filho de Seraías, filho de Asiel.

[[v13-4-36]]

^<<v13-4-36,36>>^ E Elionai, e Jaacoba, e Jesoaías, e Asaías, e Adiel, e Jesimiel, e Benaia.

[[v13-4-37]]

^<<v13-4-37,37>>^ E Ziza, filho de Sifi, filho de Alom, filho de Jedaías, filho de Sinri, filho de Semaías:

[[v13-4-38]]

^<<v13-4-38,38>>^ Estes, registrados por seus  nomes, foram  príncipes nas suas famílias: e as famílias de seus pais se multiplicaram abundantemente.

[[v13-4-39]]

^<<v13-4-39,39>>^ E chegaram até à entrada de Gedor, ao oriente do vale, a buscar pasto para as suas ovelhas.

[[v13-4-40]]

^<<v13-4-40,40>>^ E acharam pasto fértil e terra espaçosa, e quieta, e descansada; porque os  de Cão habitavam ali dantes.

[[v13-4-41]]

^<<v13-4-41,41>>^ Estes pois, que estão descritos por seus nomes, vieram nos dias de Ezequias, rei de Judá, e feriram as tendas e habitações dos que se acharam ali, e as destruíram totalmente até ao dia de  hoje, e habitaram em seu lugar: porque ali havia  pasto para as suas ovelhas.

[[v13-4-42]]

^<<v13-4-42,42>>^ Também deles, dos filhos de Simeão, quinhentos homens foram às montanhas de Seir; e a Pelatias, e a Nearias, e a Refaías, e a Uziel, filhos de Isi, levaram por cabeças.

[[v13-4-43]]

^<<v13-4-43,43>>^ E feriram o restante dos que escaparam dos amalequitas, e habitaram ali até ao dia de hoje.

'''

xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[&#60; Capítulo Anterior] | <<v13-4-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-005.adoc#v13-5-0[Próximo Capítulo &#62;]