include::./index.adoc[]

[[v13-17-0]]
=== 1 Crônicas, 17
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-17-1]]

^<<v13-17-1,1>>^ SUCEDEU pois que, morando Davi já em sua casa, disse Davi ao profeta Natã: Eis que moro em casa de cedros, mas a arca do concerto do Senhor está  debaixo de cortinas.

[[v13-17-2]]

^<<v13-17-2,2>>^ Então Natã disse a Davi: Tudo quanto tens  no teu coração, faze, porque Deus é  contigo.

[[v13-17-3]]

^<<v13-17-3,3>>^ Mas sucedeu, na mesma noite, que a palavra do Senhor veio a Natã, dizendo:

[[v13-17-4]]

^<<v13-17-4,4>>^ Vai e dize a Davi meu servo: Assim diz o Senhor: Tu me não edificarás uma  casa para morar,

[[v13-17-5]]

^<<v13-17-5,5>>^ Porque em casa nenhuma morei, desde o dia em que fiz subir a Israel, até ao dia de  hoje; mas fui de tenda em tenda, e de tabernáculo em tabernáculo.

[[v13-17-6]]

^<<v13-17-6,6>>^ Por todas as partes  por onde andei com todo o Israel, porventura  falei alguma palavra a algum dos juízes de Israel, a quem ordenei que apascentasse o meu povo, dizendo: Por que me não edificais uma  casa de cedros?

[[v13-17-7]]

^<<v13-17-7,7>>^ Agora pois assim dirás a meu servo, a Davi: Assim diz o Senhor dos Exércitos: Eu te tirei do curral, de detrás das ovelhas, para que fosses chefe do meu povo Israel.

[[v13-17-8]]

^<<v13-17-8,8>>^ E estive contigo por toda a parte , por onde foste, e de diante de ti exterminei todos os teus inimigos, e te fiz um  nome como o nome dos grandes que estão  na terra.

[[v13-17-9]]

^<<v13-17-9,9>>^ E ordenarei um lugar para o meu povo Israel, e o plantarei, para que habite no seu lugar, e nunca mais seja removido duma para outra parte; e nunca mais os debilitarão os filhos da perversidade, como ao princípio.

[[v13-17-10]]

^<<v13-17-10,10>>^ E desde os dias em que ordenei juízes sobre o meu povo Israel; porém abati a todos os teus inimigos: também te fiz saber que o Senhor te edificaria uma  casa.

[[v13-17-11]]

^<<v13-17-11,11>>^ E há de ser que, quando forem cumpridos os teus dias, para ires a teus pais, suscitarei a tua semente depois de ti, a qual será dos teus filhos, e confirmarei o seu reino.

[[v13-17-12]]

^<<v13-17-12,12>>^ Este me edificará casa; e eu confirmarei o seu trono para sempre.

[[v13-17-13]]

^<<v13-17-13,13>>^ Eu lhe serei por pai, e ele me será por filho: e a minha benignidade não desviarei dele, como a  tirei daquele, que foi antes de ti.

[[v13-17-14]]

^<<v13-17-14,14>>^ Mas o confirmarei na minha casa e no meu reino para sempre, e o seu trono será firme para sempre.

[[v13-17-15]]

^<<v13-17-15,15>>^ Conforme todas estas palavras, e conforme toda esta visão, assim falou Natã a Davi.

[[v13-17-16]]

^<<v13-17-16,16>>^ Então entrou o rei Davi, e ficou perante o Senhor, e disse: Quem sou  eu, Senhor Deus? e qual é  a minha casa, que me trouxeste até aqui?

[[v13-17-17]]

^<<v13-17-17,17>>^ E ainda  isto, ó Deus, foi pouco aos teus olhos; pelo que falaste da casa de teu servo para tempos distantes: e proveste-me, segundo o costume dos homens, com esta exaltação, ó Senhor Deus.

[[v13-17-18]]

^<<v13-17-18,18>>^ Que mais te dirá  Davi, acerca da honra feita a teu servo? Porém tu bem conheces a teu servo.

[[v13-17-19]]

^<<v13-17-19,19>>^ Ó Senhor, por amor de teu servo, e segundo o teu coração, fizeste todas estas  grandezas, para fazer notórias todas estas grandes cousas.

[[v13-17-20]]

^<<v13-17-20,20>>^ Senhor, ninguém há  como tu, e não há  Deus fora de ti, conforme tudo quanto ouvimos com os nossos ouvidos.

[[v13-17-21]]

^<<v13-17-21,21>>^ E quem há  como o teu povo Israel, única gente na terra, a quem Deus foi remir para seu povo, fazendo-te nome com cousas grandes e temerosas, lançando as nações de diante do teu povo, que remiste do Egito?

[[v13-17-22]]

^<<v13-17-22,22>>^ E tomaste o teu povo Israel para ser teu povo para sempre: e tu, Senhor, lhe foste por Deus.

[[v13-17-23]]

^<<v13-17-23,23>>^ Agora pois, Senhor, a palavra que falaste de teu servo, e acerca da sua casa, seja certa para sempre: e faze como falaste.

[[v13-17-24]]

^<<v13-17-24,24>>^ Confirme-se com efeito, e que o teu nome se engrandeça para sempre, e  diga-se: O Senhor dos Exércitos é o Deus de Israel, é  Deus para Israel: e fique  firme diante de ti a casa de Davi teu servo.

[[v13-17-25]]

^<<v13-17-25,25>>^ Porque tu, Deus meu, revelaste ao ouvido de teu servo que lhe edificarias casa; pelo que o teu servo achou confiança  para orar em tua presença.

[[v13-17-26]]

^<<v13-17-26,26>>^ Agora, pois, Senhor, tu és o mesmo Deus, e falaste este bem acerca de teu servo.

[[v13-17-27]]

^<<v13-17-27,27>>^ Agora pois foste servido abençoares a casa de teu servo, para que esteja perpetuamente diante de ti; porque tu, Senhor, a abençoaste, e ficará  abençoada para sempre.

'''

xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[&#60; Capítulo Anterior] | <<v13-17-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[Próximo Capítulo &#62;]