include::./index.adoc[]

[[v13-5-0]]
=== 1 Crônicas, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-5-1]]

^<<v13-5-1,1>>^ QUANTO aos filhos de Rúben, o primogênito de Israel; — porque ele era  o primogênito, mas porque profanara a cama de seu pai, deu-se a sua primogenitura aos filhos de José, filho de Israel; para assim não ser contado na genealogia da primogenitura.

[[v13-5-2]]

^<<v13-5-2,2>>^ Porque Judá foi poderoso entre seus irmãos, e dele provém  o príncipe; porém a primogenitura foi de José; —

[[v13-5-3]]

^<<v13-5-3,3>>^ Foram  pois os filhos de Rúben, o primogênito de Israel: Enoque, e Palu, e Hezrom, e Carmi.

[[v13-5-4]]

^<<v13-5-4,4>>^ Os filhos de Joel: Semaías, seu filho, Gogue, seu filho, Simei, seu filho,

[[v13-5-5]]

^<<v13-5-5,5>>^ Mica, seu filho, Reaías, seu filho, Baal, seu filho.

[[v13-5-6]]

^<<v13-5-6,6>>^ Beera, seu filho, o qual Tilgate-Pilneser, rei da Assíria, levou preso: este foi  príncipe dos rubenitas.

[[v13-5-7]]

^<<v13-5-7,7>>^ Quanto a seus irmãos pelas suas famílias, quando foram postos nas genealogias segundo as suas descendências, tinham por  chefes Jeiel e Zacarias.

[[v13-5-8]]

^<<v13-5-8,8>>^ E Bela, filho de Azaz, filho de Sema, filho de Joel, que habitou em Aroer até Nebo e Baal-Meom,

[[v13-5-9]]

^<<v13-5-9,9>>^ Também habitou da banda do oriente, até à entrada do deserto, desde o rio Eufrates: porque seu gado se tinha multiplicado na terra de Gileade.

[[v13-5-10]]

^<<v13-5-10,10>>^ E nos dias de Saul fizeram guerra aos hagarenos, que caíram pela sua mão: e eles habitaram nas suas tendas defronte de toda a banda oriental de Gileade.

[[v13-5-11]]

^<<v13-5-11,11>>^ E os filhos de Gade habitaram defronte deles, na terra de Basã, até Salcá.

[[v13-5-12]]

^<<v13-5-12,12>>^ Joel foi  chefe, e Safã o segundo: porém Jaanai e Safate ficaram  em Basã.

[[v13-5-13]]

^<<v13-5-13,13>>^ E seus irmãos, segundo as suas casas paternas, foram : Micael, e Mesulão, e Seba, e Jorai, e Jacã, e Zia, e Éber, sete.

[[v13-5-14]]

^<<v13-5-14,14>>^ Estes foram  os filhos de Abiail, filho de Huri, filho de Jaroa, filho de Gileade, filho de Micael, filho de Jesisai, filho de Jado, filho de Buz;

[[v13-5-15]]

^<<v13-5-15,15>>^ Ai, filho de Abdiel, filho de Guni, foi  chefe da casa de seus pais.

[[v13-5-16]]

^<<v13-5-16,16>>^ E habitaram em Gileade, em Basã, e nos lugares da sua jurisdição como também em todos os arrabaldes de Sarom, até às suas saídas.

[[v13-5-17]]

^<<v13-5-17,17>>^ Todos estes foram registrados, segundo as suas genealogias, nos dias de Jotão, rei de Judá, e nos dias de Jeroboão, rei de Israel.

[[v13-5-18]]

^<<v13-5-18,18>>^ Dos filhos de Rúben, e dos gaditas, e da meia tribo de Manassés, homens muito belicosos, que traziam escudo e espada, e entesavam o arco, e eram  destros na guerra, houve quarenta e quatro mil e setecentos e sessenta, que saíam à peleja.

[[v13-5-19]]

^<<v13-5-19,19>>^ E fizeram guerra aos hagarenos, como a Jetur, e a Nafis e a Nodabe.

[[v13-5-20]]

^<<v13-5-20,20>>^ E foram ajudados contra eles, e os hagarenos e todos quantos estavam  com eles foram entregues em sua mão; porque clamaram a Deus na peleja, e lhes deu ouvidos, porquanto confiaram nele.

[[v13-5-21]]

^<<v13-5-21,21>>^ E levaram preso o seu gado: seus camelos, cinquenta mil, e duzentas e cinquenta mil ovelhas, e dois mil jumentos; e cem mil almas de homens.

[[v13-5-22]]

^<<v13-5-22,22>>^ Porque muitos feridos caíram porque de Deus era  a peleja; e habitaram em seu lugar, até ao cativeiro.

[[v13-5-23]]

^<<v13-5-23,23>>^ E os filhos da meia tribo de Manassés habitaram naquela terra: de Basã até Baal-Hermom, e Senir, e o monte de Hermom, eles se multiplicaram.

[[v13-5-24]]

^<<v13-5-24,24>>^ E estes foram  cabeças de suas casas paternas, a saber: Hefer, e Isi, e Eliel, e Azriel, e Jeremias, e Hodavias, e Jadiel, homens valentes, homens de nome, e chefes das casas de seus pais.

[[v13-5-25]]

^<<v13-5-25,25>>^ Porém transgrediram contra o Deus de seus pais: e foram após os deuses dos povos da terra, os quais Deus destruíra de diante deles.

[[v13-5-26]]

^<<v13-5-26,26>>^ Pelo que o Deus de Israel suscitou o espírito de Pul, rei da Assíria, e o espírito de Tilgate-Pilneser, rei da Assíria, que os levaram presos, a saber : os rubenitas e gaditas, e a meia tribo de Manassés; e os trouxeram a Hala, e a Habor, e a Hara, e ao rio de Gozã, até ao dia de  hoje.

'''

xref:013-1-cronicas/013-1-cronicas-004.adoc#v13-4-0[&#60; Capítulo Anterior] | <<v13-5-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[Próximo Capítulo &#62;]