include::./index.adoc[]

[[v13-11-0]]
=== 1 Crônicas, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-11-1]]

^<<v13-11-1,1>>^ ENTÃO todo o Israel se ajuntou a Davi em Hebrom, dizendo: Eis que somos  teus ossos e tua carne.

[[v13-11-2]]

^<<v13-11-2,2>>^ E também já dantes, sendo Saul ainda rei, eras  tu o que fazias sair e entrar a Israel: também o Senhor teu Deus te disse: Tu apascentarás o meu povo Israel, e tu serás chefe sobre o meu povo Israel.

[[v13-11-3]]

^<<v13-11-3,3>>^ Também vieram todos os anciãos de Israel ao rei, a Hebrom, e Davi fez com eles aliança em Hebrom, perante o Senhor: e ungiram a Davi rei sobre Israel, conforme a palavra do Senhor pelo ministério de Samuel.

[[v13-11-4]]

^<<v13-11-4,4>>^ E partiu Davi e todo o Israel para Jerusalém, que é  Jebus: porque ali estavam  os jebuseus, moradores da terra.

[[v13-11-5]]

^<<v13-11-5,5>>^ E disseram os moradores de Jebus a Davi: Tu não entrarás aqui. Porém Davi ganhou a fortaleza de Sião, que é  a cidade de Davi.

[[v13-11-6]]

^<<v13-11-6,6>>^ Porque disse Davi: Qualquer que primeiro ferir os jebuseus será chefe e maioral. Então Joabe, filho de Zeruia, subiu primeiro a ela; pelo que foi feito  chefe.

[[v13-11-7]]

^<<v13-11-7,7>>^ E Davi habitou na fortaleza; pelo que se chamou a cidade de Davi.

[[v13-11-8]]

^<<v13-11-8,8>>^ E edificou a cidade ao redor, desde Milo até ao circuito: e Joabe renovou o resto da cidade.

[[v13-11-9]]

^<<v13-11-9,9>>^ E ia Davi cada vez mais aumentando e crescendo; porque o Senhor dos Exércitos era  com ele.

[[v13-11-10]]

^<<v13-11-10,10>>^ E estes foram  os chefes dos heróis que Davi tinha, e que o apoiaram fortemente no seu reino, com todo o Israel, para o fazerem rei, conforme a palavra do Senhor, tocante a Israel.

[[v13-11-11]]

^<<v13-11-11,11>>^ E estes foram  do número dos heróis que Davi tinha: Jasobeão, hacmonita, o principal dos capitães, o qual brandindo a sua lança contra trezentos, duma vez os matou.

[[v13-11-12]]

^<<v13-11-12,12>>^ E, depois dele, Eleazar, filho de Dodó, o aoíta: ele estava entre os três varões.

[[v13-11-13]]

^<<v13-11-13,13>>^ Este esteve com Davi em Pasdamim, quando os filisteus ali se ajuntaram à peleja, e o pedaço de campo estava cheio de cevada: e o povo fugiu de  diante dos filisteus.

[[v13-11-14]]

^<<v13-11-14,14>>^ E puseram-se no meio daquele  pedaço, e o defenderam, e feriram os filisteus; e obrou o Senhor um grande livramento.

[[v13-11-15]]

^<<v13-11-15,15>>^ E três dos trinta chefes desceram à penha, a Davi, na caverna de Adulão: e o arraial dos filisteus estava acampado no vale de Refaim.

[[v13-11-16]]

^<<v13-11-16,16>>^ E Davi estava  então no lugar forte: e o alojamento dos filisteus estava então em Belém.

[[v13-11-17]]

^<<v13-11-17,17>>^ E desejou Davi, e disse: Quem me dará a beber da água do poço de Belém, que está junto  à porta?

[[v13-11-18]]

^<<v13-11-18,18>>^ Então aqueles três romperam pelo arraial dos filisteus, e tiraram água do poço de Belém, que estava  à porta; e tomaram dela , e a trouxeram a Davi, porém Davi não a quis beber, mas a derramou perante o Senhor.

[[v13-11-19]]

^<<v13-11-19,19>>^ E disse: Nunca meu Deus permita que faça tal! Beberia eu o sangue destes varões com as suas vidas? Pois com perigo das  suas vidas a trouxeram. E ele não a quis beber: isto fizeram aqueles três valentes.

[[v13-11-20]]

^<<v13-11-20,20>>^ E também Abisai, irmão de Joabe, foi chefe de três, o qual, brandindo a sua lança contra trezentos, os feriu: e teve nome entre os três.

[[v13-11-21]]

^<<v13-11-21,21>>^ Dos três foi mais ilustre do que os outros  dois, pelo que foi chefe deles; porém não chegou aos primeiros  três.

[[v13-11-22]]

^<<v13-11-22,22>>^ Também  Benaia, filho de Joiada, filho de um  valente varão, grande em obras, de Cabseel: ele feriu a dois fortes leões de Moabe; e também desceu, e feriu um leão dentro de uma cova, no tempo da neve.

[[v13-11-23]]

^<<v13-11-23,23>>^ Também feriu ele a um homem  egípcio, homem de grande  altura, de cinco côvados: e trazia  o egípcio uma lança na mão, como o órgão do tecelão; mas desceu contra ele com uma vara, e arrancou a lança da mão do egípcio, e o matou com a sua própria lança.

[[v13-11-24]]

^<<v13-11-24,24>>^ Estas cousas fez Benaia, filho de Joiada; pelo que teve nome entre aqueles três varões.

[[v13-11-25]]

^<<v13-11-25,25>>^ Eis que dos trinta foi ele  o mais ilustre; contudo não chegou aos três: e Davi o pôs sobre os da sua guarda.

[[v13-11-26]]

^<<v13-11-26,26>>^ E foram  os heróis dos exércitos: Asael, irmão de Joabe, Elanã filho de Dodó, de Belém.

[[v13-11-27]]

^<<v13-11-27,27>>^ Samote, o harodita, Heles, o pelonita,

[[v13-11-28]]

^<<v13-11-28,28>>^ Ira, filho de Iques, o tecoíta, Abiezer, o anatotita,

[[v13-11-29]]

^<<v13-11-29,29>>^ Sibecai, o husatita, Ilai, o aoíta,

[[v13-11-30]]

^<<v13-11-30,30>>^ Maarai, o netofatita, Helede, filho de Baena, o netofatita,

[[v13-11-31]]

^<<v13-11-31,31>>^ Itai, filho de Ribai, de Gibeá, dos filhos de Benjamim, Benaia, o piratonita,

[[v13-11-32]]

^<<v13-11-32,32>>^ Hurai, do ribeiro de Gaás, Abiel, o arbatita,

[[v13-11-33]]

^<<v13-11-33,33>>^ Asmavete, o baarumita, Eliaba, o saalbonita.

[[v13-11-34]]

^<<v13-11-34,34>>^ Dos filhos de Hasém, o gizonita: Jônatas, filho de Sage, o hararita,

[[v13-11-35]]

^<<v13-11-35,35>>^ Aião, filho de Sacar, o hararita, Elifal, filho de Ur,

[[v13-11-36]]

^<<v13-11-36,36>>^ Hefer, o mequeratita, Aías, o pelonita,

[[v13-11-37]]

^<<v13-11-37,37>>^ Hesro, o carmelita, Naari, filho de Esbai,

[[v13-11-38]]

^<<v13-11-38,38>>^ Joel, irmão de Natã, Mibar, filho de Geri,

[[v13-11-39]]

^<<v13-11-39,39>>^ Zeleque, o amonita, Narai, o berotita, escudeiro de Joabe, filho de Zeruia,

[[v13-11-40]]

^<<v13-11-40,40>>^ Ira, o itrita, Garebe, o itrita,

[[v13-11-41]]

^<<v13-11-41,41>>^ Urias, o hetita, Zabade, filho de Alai,

[[v13-11-42]]

^<<v13-11-42,42>>^ Adina, filho de Siza, o rubenita, chefe dos rubenitas; todavia sobre ele havia  trinta;

[[v13-11-43]]

^<<v13-11-43,43>>^ Hanã, filho de Maaca, e Josafá, o mitnita,

[[v13-11-44]]

^<<v13-11-44,44>>^ Uzias, o astaratita, Sama e Jeiel, filhos de Hotão, o aroerita,

[[v13-11-45]]

^<<v13-11-45,45>>^ Jediael, filho de Sinri, e Joá, seu irmão, o tisita,

[[v13-11-46]]

^<<v13-11-46,46>>^ Eliel, o maavita, e Jeribai, e Josavias, filhos de Elnaão, e Itma, o moabita,

[[v13-11-47]]

^<<v13-11-47,47>>^ Eliel, e Obede, e Jaasiel, e Mesobaia.

'''

xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[&#60; Capítulo Anterior] | <<v13-11-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-012.adoc#v13-12-0[Próximo Capítulo &#62;]