include::./index.adoc[]

[[v13-26-0]]
=== 1 Crônicas, 26
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-26-1]]

^<<v13-26-1,1>>^ QUANTO às divisões dos porteiros, dos coraítas foi  Meselemias, filho de Coré, dos filhos de Asafe.

[[v13-26-2]]

^<<v13-26-2,2>>^ E foram  os filhos de Meselemias: Zacarias o primogênito, Jediael o segundo, Zebedias o terceiro, Jatniel o quarto.

[[v13-26-3]]

^<<v13-26-3,3>>^ Elão o quinto, Joanã o sexto, Elioenai o sétimo.

[[v13-26-4]]

^<<v13-26-4,4>>^ E os filhos de Obede-Edom foram : Semaías o primogênito, Jozabade o segundo, Joá o terceiro, e Sacar o quarto, e Natanael o quinto,

[[v13-26-5]]

^<<v13-26-5,5>>^ Amiel o sexto, Issacar o sétimo, Peuletai o oitavo: porque Deus o tinha abençoado.

[[v13-26-6]]

^<<v13-26-6,6>>^ Também a seu filho Semaías nasceram filhos, que dominaram sobre a casa de seu pai; porque foram  varões valentes.

[[v13-26-7]]

^<<v13-26-7,7>>^ Os filhos de Semaías: Otni, e Rafael, e Obede, e  Elzabade, com seus irmãos, homens valentes, Eliú e Semaquias.

[[v13-26-8]]

^<<v13-26-8,8>>^ Todos estes foram  dos filhos de Obede-Edom; eles e seus filhos, e seus irmãos, homens valentes de força para o ministério: por todos  sessenta e dois, de Obede-Edom.

[[v13-26-9]]

^<<v13-26-9,9>>^ E os filhos e os irmãos de Meselemias, homens valentes, foram  dezoito.

[[v13-26-10]]

^<<v13-26-10,10>>^ E de Hosa, dentre os filhos de Merari, foram seus filhos: Sinri o chefe (ainda que não era o primogênito, contudo seu pai o constituiu chefe),

[[v13-26-11]]

^<<v13-26-11,11>>^ Hilquias o segundo, Tebalias o terceiro, Zacarias o quarto: todos os filhos e irmãos de Hosa foram  treze.

[[v13-26-12]]

^<<v13-26-12,12>>^ Destes se fizeram  as turmas dos porteiros, entre os chefes dos homens da guarda, igualmente com os seus irmãos, para ministrarem na casa do Senhor.

[[v13-26-13]]

^<<v13-26-13,13>>^ E lançaram sortes, assim os pequenos como os grandes, segundo as casas de seus pais, para cada porta.

[[v13-26-14]]

^<<v13-26-14,14>>^ E caiu a sorte do oriente a Selemias: e lançou-se a sorte por seu filho Zacarias, conselheiro entendido, e saiu-lhe a sorte do norte.

[[v13-26-15]]

^<<v13-26-15,15>>^ E a Obede-Edom a do sul: e a seus filhos a casa das tesourarias.

[[v13-26-16]]

^<<v13-26-16,16>>^ A Supim e Hosa a do ocidente, com a porta Salequete, junto ao caminho da subida: uma guarda defronte doutra guarda.

[[v13-26-17]]

^<<v13-26-17,17>>^ Ao oriente estavam seis levitas; ao norte quatro por dia, ao sul quatro por dia, porém às tesourarias de dois em dois.

[[v13-26-18]]

^<<v13-26-18,18>>^ Em Parbar ao ocidente, quatro junto ao caminho, dois junto a Parbar.

[[v13-26-19]]

^<<v13-26-19,19>>^ Estas são  as turmas dos porteiros dentre os filhos dos coraítas, e dentre os filhos de Merari.

[[v13-26-20]]

^<<v13-26-20,20>>^ E  quanto aos levitas: Aías tinha  cargo dos tesouros da casa de Deus e dos tesouros das cousas sagradas.

[[v13-26-21]]

^<<v13-26-21,21>>^ Quanto  aos filhos de Ladã, filhos de Ladã gersonita: de Ladã gersonita foi  chefe dos pais Jeieli.

[[v13-26-22]]

^<<v13-26-22,22>>^ Os filhos de Jeieli: Zetão e Joel, seu irmão; estes tinham  cargo dos tesouros da casa do Senhor.

[[v13-26-23]]

^<<v13-26-23,23>>^ Para os anramitas, para os isaritas, para os hebronitas, para os ozielitas;

[[v13-26-24]]

^<<v13-26-24,24>>^ E Sebuel, filho de Gérson, o filho de Moisés era  maioral dos tesouros.

[[v13-26-25]]

^<<v13-26-25,25>>^ E seus irmãos foram , da banda de Eliézer, Reabias seu filho, e Isaías seu filho, e Jorão seu filho, e Zicri seu filho, e Selomite seu filho.

[[v13-26-26]]

^<<v13-26-26,26>>^ Este Selomite e seus irmãos tinham  cargo de todos os tesouros das cousas sagradas que o rei Davi e os chefes dos pais, capitães de milhares, e de centenas, e capitães do exército tinham consagrado;

[[v13-26-27]]

^<<v13-26-27,27>>^ Dos despojos das guerras as  consagraram, para repararem a casa do Senhor.

[[v13-26-28]]

^<<v13-26-28,28>>^ Como também tudo quanto tinha consagrado Samuel o vidente, e Saul filho de Quis, e Abner filho de Ner, e Joabe filho de Zeruia: tudo quanto qualquer tinha consagrado estava  debaixo da mão de Selomite e seus irmãos.

[[v13-26-29]]

^<<v13-26-29,29>>^ Dos isaritas, Quenanias e seus filhos foram  postos sobre Israel para a obra de fora, por oficiais e por juízes.

[[v13-26-30]]

^<<v13-26-30,30>>^ Dos hebronitas foram  Hesabias e seus irmãos, homens valentes, mil e setecentos, que tinham cargo dos ofícios em Israel, de aquém do Jordão para o ocidente, em toda a obra do Senhor, e para o serviço do rei.

[[v13-26-31]]

^<<v13-26-31,31>>^ Dos hebronitas era  Jerias o chefe dos hebronitas, de suas gerações entre os pais: no ano quarenta do reino de Davi se buscaram e acharam entre eles varões valentes em Jaezer de Gileade.

[[v13-26-32]]

^<<v13-26-32,32>>^ E seus irmãos, homens valentes, dois mil e setecentos, chefes dos pais: e o rei Davi os constituiu sobre os rubenitas e os gaditas, e a meia tribo dos manassitas, para todos os negócios de Deus, e para todos os negócios do rei.

'''

xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[&#60; Capítulo Anterior] | <<v13-26-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[Próximo Capítulo &#62;]