include::./index.adoc[]

[[v13-23-0]]
=== 1 Crônicas, 23
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-23-1]]

^<<v13-23-1,1>>^ SENDO pois Davi já velho, e cheio de dias, fez a Salomão seu filho rei sobre Israel.

[[v13-23-2]]

^<<v13-23-2,2>>^ E ajuntou a todos os príncipes de Israel, como também aos sacerdotes e levitas.

[[v13-23-3]]

^<<v13-23-3,3>>^ E foram contados os levitas de trinta anos e daí para cima: e foi o número deles, segundo as suas cabeças, trinta e oito mil homens.

[[v13-23-4]]

^<<v13-23-4,4>>^ Destes havia  vinte e quatro mil, para promoverem a obra da casa do Senhor, e seis mil oficiais e juízes.

[[v13-23-5]]

^<<v13-23-5,5>>^ E quatro mil porteiros, e quatro mil para louvarem ao Senhor com os instrumentos, que eu fiz para o  louvar, disse Davi.

[[v13-23-6]]

^<<v13-23-6,6>>^ E Davi os repartiu por turnos, segundo os filhos de Levi, Gérson, Coate e Merari.

[[v13-23-7]]

^<<v13-23-7,7>>^ Dos gersonitas: Ladã e Simei.

[[v13-23-8]]

^<<v13-23-8,8>>^ Os filhos de Ladã; Jeiel o chefe, e Zetão, e Joel, três.

[[v13-23-9]]

^<<v13-23-9,9>>^ Os filhos de Simei: Selomite, e Haziel, e Harã, três: estes foram  os chefes dos pais de Ladã.

[[v13-23-10]]

^<<v13-23-10,10>>^ E os filhos de Simei: Jaate, Ziza, e Jeús, e Berias: Estes foram  os filhos de Simei, quatro.

[[v13-23-11]]

^<<v13-23-11,11>>^ E Jaate era o chefe, e Ziza, o segundo, mas Jeús e Berias não tiveram muitos filhos; pelo que foram contados em casa de seus  pais por uma só  família.

[[v13-23-12]]

^<<v13-23-12,12>>^ Os filhos de Coate: Anrão, Isar, Hebrom, e Uziel, quatro.

[[v13-23-13]]

^<<v13-23-13,13>>^ Os filhos de Anrão: Aarão e Moisés; e Aarão foi separado para santificar a santidade das santidades, ele e seus filhos, eternamente; para incensar diante do Senhor, para o servirem, e para darem a bênção em seu nome eternamente.

[[v13-23-14]]

^<<v13-23-14,14>>^ E quanto a  Moisés, homem de Deus, seus filhos foram contados entre a tribo de Levi.

[[v13-23-15]]

^<<v13-23-15,15>>^ Foram  pois os filhos de Moisés, Gérson e Eliézer.

[[v13-23-16]]

^<<v13-23-16,16>>^ Dos filhos de Gérson foi  Sebuel o chefe.

[[v13-23-17]]

^<<v13-23-17,17>>^ E quanto aos filhos de Eliézer, foi  Reabias o chefe; e Eliézer não teve outros filhos; porém os filhos de Reabias se multiplicaram grandemente.

[[v13-23-18]]

^<<v13-23-18,18>>^ Dos filhos de Isar foi  Selomite o chefe.

[[v13-23-19]]

^<<v13-23-19,19>>^ Quanto aos filhos de Hebrom, foi  Jerias o chefe, Amarias o segundo, Jaaziel o terceiro, e Jecameão o quarto.

[[v13-23-20]]

^<<v13-23-20,20>>^ Quanto aos filhos de Uziel, Mica o chefe, e Issias o segundo.

[[v13-23-21]]

^<<v13-23-21,21>>^ Os filhos de Merari: Maeli e Musi; os filhos de Maeli: Eleazar e Quis.

[[v13-23-22]]

^<<v13-23-22,22>>^ E morreu Eleazar, e não teve filhos, porém filhas; e os filhos de Quís, seus irmãos, as tomaram por mulheres.

[[v13-23-23]]

^<<v13-23-23,23>>^ Os filhos de Musi: Maeli, e Eder, e Jerimote, três.

[[v13-23-24]]

^<<v13-23-24,24>>^ Estes são  os filhos de Levi, segundo a casa de seus pais, chefes dos pais, segundo foram contados pelo número dos nomes, segundo os seus chefes, que faziam a obra do ministério da casa do Senhor, da idade de vinte anos e daí  para cima.

[[v13-23-25]]

^<<v13-23-25,25>>^ Porque disse Davi: O Senhor Deus de Israel deu repouso ao seu povo, e habitará em Jerusalém para sempre.

[[v13-23-26]]

^<<v13-23-26,26>>^ E também, quanto aos levitas, que nunca mais  levassem o tabernáculo, nem algum de seus objetos pertencentes  ao seu ministério.

[[v13-23-27]]

^<<v13-23-27,27>>^ Porque, segundo as últimas palavras de Davi, foram  contados os filhos de Levi da idade de vinte anos e daí  para cima.

[[v13-23-28]]

^<<v13-23-28,28>>^ Porque o seu cargo era  de estar ao mandado dos filhos de Aarão no ministério da casa do Senhor, nos átrios, e nas câmaras, e na purificação de todas as cousas sagradas, e na obra do ministério da casa de Deus,

[[v13-23-29]]

^<<v13-23-29,29>>^ A saber : para os pães da proposição, e para a flor de farinha, para a oferta de manjares, e para os coscorões asmos, e para as sertãs, e para o tostado, e para toda a medida e mensura;

[[v13-23-30]]

^<<v13-23-30,30>>^ E para estarem cada manhã em pé para louvarem e celebrarem ao Senhor; e semelhantemente à tarde;

[[v13-23-31]]

^<<v13-23-31,31>>^ E para cada oferecimento dos holocaustos do Senhor, nos sábados, nas luas novas, e nas solenidades, por conta, segundo o seu costume, continuamente perante o Senhor:

[[v13-23-32]]

^<<v13-23-32,32>>^ E para que tivessem cuidado da guarda da tenda da congregação, e da guarda do santuário, e da guarda dos filhos de Aarão, seus irmãos, no ministério da casa do Senhor.

'''

xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[&#60; Capítulo Anterior] | <<v13-23-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-024.adoc#v13-24-0[Próximo Capítulo &#62;]