include::./index.adoc[]

[[v13-29-0]]
=== 1 Crônicas, 29
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-29-1]]

^<<v13-29-1,1>>^ DISSE mais o rei Davi a toda a congregação: Salomão, meu filho, a quem só Deus escolheu, é ainda  moço e tenro, e esta obra é  grande; porque não é  palácio para homem, senão para o Senhor Deus.

[[v13-29-2]]

^<<v13-29-2,2>>^ Eu pois com todas as minhas forças já  tenho preparado para a casa do meu Deus ouro para as obras  de ouro, e prata para as  de prata, e cobre para as  de cobre, ferro para as  de ferro e madeira para as  de madeira, pedras sardônicas, e as de engaste, e pedras de ornato, e obra de embutido, e toda a sorte de pedras preciosas, e pedras marmóreas em abundância.

[[v13-29-3]]

^<<v13-29-3,3>>^ E ainda, de minha própria vontade para a casa de meu Deus, o ouro e prata particular que tenho demais eu dou para a casa do meu Deus, afora tudo quanto tenho preparado para a casa do santuário;

[[v13-29-4]]

^<<v13-29-4,4>>^ Três mil talentos de ouro, do ouro de Ofir: e sete mil talentos de prata purificada, para cobrir as paredes das casas:

[[v13-29-5]]

^<<v13-29-5,5>>^ Ouro para os vasos  de ouro, e prata para os  de prata; e para toda a obra de mãos dos artífices. Quem pois está disposto a encher a sua mão, para oferecer hoje voluntariamente  ao Senhor?

[[v13-29-6]]

^<<v13-29-6,6>>^ Então os chefes dos pais, e os príncipes das tribos de Israel, e os capitães dos milhares e das centenas, até os capitães da obra do rei, voluntariamente contribuíram.

[[v13-29-7]]

^<<v13-29-7,7>>^ E deram para o serviço da casa de Deus cinco mil talentos de ouro, e dez mil dracmas, e dez mil talentos de prata, e dezoito mil talentos de cobre, e cem mil talentos de ferro.

[[v13-29-8]]

^<<v13-29-8,8>>^ E os que se acharam com pedras preciosas , as deram para o tesouro da casa do Senhor, na mão de Jeiel o gersonita.

[[v13-29-9]]

^<<v13-29-9,9>>^ E o povo se alegrou do que deram voluntariamente; porque com coração perfeito voluntariamente deram ao Senhor: e também o rei Davi se alegrou com grande alegria.

[[v13-29-10]]

^<<v13-29-10,10>>^ Pelo que Davi louvou ao Senhor perante os olhos de toda a congregação; e disse Davi: Bendito és  tu, Senhor, Deus de nosso pai Israel, de eternidade em eternidade.

[[v13-29-11]]

^<<v13-29-11,11>>^ Tua é , Senhor, a magnificência, e o poder, e a honra, e a vitória, e a majestade; porque teu é  tudo quanto há  nos céus e na terra; teu é  Senhor, o reino, e tu te exaltaste sobre todos como chefe.

[[v13-29-12]]

^<<v13-29-12,12>>^ E riquezas e glória vêm de diante de ti, e tu dominas, sobre tudo, e na tua mão há  força e poder; e na tua mão está  o engrandecer e dar força a tudo.

[[v13-29-13]]

^<<v13-29-13,13>>^ Agora pois, ó Deus nosso, graças te damos, e louvamos o nome da tua glória.

[[v13-29-14]]

^<<v13-29-14,14>>^ Porque quem sou  eu, e quem é  o meu povo, que tivéssemos poder para tão voluntariamente dar semelhantes cousas? Porque tudo vem  de ti, e da tua mão to damos.

[[v13-29-15]]

^<<v13-29-15,15>>^ Porque somos estranhos diante de ti, e peregrinos como todos os nossos pais: como a sombra são  os nossos dias sobre a terra e não há outra  esperança.

[[v13-29-16]]

^<<v13-29-16,16>>^ Senhor, Deus nosso, toda esta abundância que preparamos, para te edificar uma  casa ao teu santo nome, vem  da tua mão, e toda é  tua.

[[v13-29-17]]

^<<v13-29-17,17>>^ E bem sei eu, Deus meu, que tu provas os corações, e que da sinceridade te agradas: eu também na sinceridade de meu coração voluntariamente dei todas estas cousas: e agora vi com alegria que o teu povo, que se acha aqui, voluntariamente te deu.

[[v13-29-18]]

^<<v13-29-18,18>>^ Senhor, Deus de nossos pais Abraão, Isaque, e Israel, conserva isto para sempre no intento dos pensamentos do coração de teu povo; e encaminha o seu coração para ti.

[[v13-29-19]]

^<<v13-29-19,19>>^ E a Salomão, meu filho dá um coração perfeito, para guardar os teus mandamentos, os teus testemunhos, e os teus estatutos; e para fazer tudo, e para edificar este palácio que tenho preparado.

[[v13-29-20]]

^<<v13-29-20,20>>^ Então disse Davi a toda a congregação: Agora louvai ao Senhor vosso Deus. Então toda a congregação louvou ao Senhor Deus de seus pais, e inclinaram-se, e prostraram-se perante o Senhor, e perante o rei.

[[v13-29-21]]

^<<v13-29-21,21>>^ E ao outro dia sacrificaram ao Senhor sacrifícios, e ofereceram holocaustos ao Senhor, mil bezerros, mil carneiros, mil cordeiros, com as suas libações; e sacrifícios em abundância por todo o Israel.

[[v13-29-22]]

^<<v13-29-22,22>>^ E comeram e beberam naquele dia perante o Senhor, com grande gozo: e segunda vez fizeram rei a Salomão filho de Davi, e o ungiram ao Senhor por guia, e a Zadoque por sacerdote.

[[v13-29-23]]

^<<v13-29-23,23>>^ Assim Salomão se assentou no trono do Senhor, rei, em lugar de Davi seu pai, e prosperou: e todo o Israel lhe deu ouvidos.

[[v13-29-24]]

^<<v13-29-24,24>>^ E todos os príncipes, e os grandes, e até todos os filhos do rei Davi, se submeteram ao rei Salomão.

[[v13-29-25]]

^<<v13-29-25,25>>^ E o Senhor magnificou a Salomão grandissimamente, perante os olhos de todo o Israel: e deu-lhe majestade real, qual antes dele não teve nenhum rei em Israel.

[[v13-29-26]]

^<<v13-29-26,26>>^ Assim Davi, filho de Jessé, reinou sobre todo o Israel.

[[v13-29-27]]

^<<v13-29-27,27>>^ E foram  os dias que reinou sobre Israel, quarenta anos: em Hebrom reinou sete anos, e em Jerusalém reinou trinta e três.

[[v13-29-28]]

^<<v13-29-28,28>>^ E morreu numa boa velhice, cheio de dias, riquezas e glória: e Salomão, seu filho, reinou em seu lugar.

[[v13-29-29]]

^<<v13-29-29,29>>^ Os sucessos pois do rei Davi, assim os primeiros como os últimos, eis que estão escritos nas crônicas de Samuel, o vidente, e nas crônicas do profeta Natã, e nas crônicas de Gade, o vidente;

[[v13-29-30]]

^<<v13-29-30,30>>^ Juntamente com todo o seu reino e o seu poder; e os tempos que passaram sobre ele, e sobre Israel, e sobre todos os reinos daquelas terras.

'''

xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[&#60; Capítulo Anterior] | <<v13-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[Próximo Capítulo &#62;]