include::./index.adoc[]

[[v13-21-0]]
=== 1 Crônicas, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-21-1]]

^<<v13-21-1,1>>^ ENTÃO Satanás se levantou contra Israel, e incitou Davi a numerar a Israel.

[[v13-21-2]]

^<<v13-21-2,2>>^ E disse Davi a Joabe e aos maiorais do povo: Ide, contai a Israel desde Berseba até Dã; e trazei-me a conta, para que saiba o número deles.

[[v13-21-3]]

^<<v13-21-3,3>>^ Então disse Joabe: O Senhor acrescente ao seu povo cem vezes tanto como é; porventura , ó rei meu senhor, não são  todos servos de meu senhor? Por que procura isto o meu senhor? Porque seria isso causa de  delito para com Israel.

[[v13-21-4]]

^<<v13-21-4,4>>^ Porém a palavra do rei prevaleceu contra Joabe; e pelo que saiu Joabe, e passou por todo o Israel; então voltou para Jerusalém.

[[v13-21-5]]

^<<v13-21-5,5>>^ E Joabe deu a Davi a soma do número do povo: e era todo o Israel um milhão e cem mil homens, dos que arrancavam espada; e de Judá quatrocentos e setenta mil homens, dos que arrancavam espada.

[[v13-21-6]]

^<<v13-21-6,6>>^ Porém os de Levi e Benjamim não contou entre eles, porque a palavra do rei foi abominável a Joabe.

[[v13-21-7]]

^<<v13-21-7,7>>^ E este negócio também  pareceu mal aos olhos de Deus, pelo que feriu a Israel.

[[v13-21-8]]

^<<v13-21-8,8>>^ Então disse Davi a Deus: Gravemente pequei em fazer tal cousa; porém agora sê servido tirar a iniquidade de teu servo, porque obrei mui loucamente.

[[v13-21-9]]

^<<v13-21-9,9>>^ Falou pois o Senhor a Gade, o vidente de Davi, dizendo:

[[v13-21-10]]

^<<v13-21-10,10>>^ Vai, e fala a Davi, dizendo: Assim diz o Senhor: Três cousas  te proponho: escolhe uma delas, para que eu ta  faça.

[[v13-21-11]]

^<<v13-21-11,11>>^ E Gade veio a Davi, e lhe disse: Assim diz o Senhor: Escolhe para ti,

[[v13-21-12]]

^<<v13-21-12,12>>^ Ou três anos de fome, ou que três meses te consumas diante de teus adversários, e a espada de teus inimigos te  alcance, ou que três dias a espada do Senhor, isto é, a peste na terra, e o anjo do Senhor destruam todos os termos de Israel: vê pois agora que resposta hei de levar a quem me enviou.

[[v13-21-13]]

^<<v13-21-13,13>>^ Então disse Davi a Gade: Estou em grande angústia; caia eu pois nas mãos do Senhor, porque são  muitíssimas as suas misericórdias; mas que eu não caia nas mãos dos homens.

[[v13-21-14]]

^<<v13-21-14,14>>^ Mandou pois o Senhor a peste a Israel; e caíram de Israel setenta mil homens.

[[v13-21-15]]

^<<v13-21-15,15>>^ E o Senhor mandou um  anjo a Jerusalém para a destruir; e, ao destruí-la ele , o Senhor o  viu, e se arrependeu daquele mal, e disse ao anjo destruidor: Basta, agora retira a tua mão. E o anjo do Senhor estava junto à eira de Ornã jebuseu.

[[v13-21-16]]

^<<v13-21-16,16>>^ E, levantando Davi os seus olhos, viu o anjo do Senhor, que estava entre a terra e o céu, com a espada desembainhada na sua mão estendida contra Jerusalém: então Davi e os anciãos, cobertos de sacos, se prostraram sobre os seus rostos.

[[v13-21-17]]

^<<v13-21-17,17>>^ E disse Davi a Deus: Não sou  eu o que  disse que se contasse o povo? E eu mesmo sou o  que pequei, e fiz muito mal; mas estas ovelhas que fizeram? Ah! Senhor, meu Deus, seja a tua mão contra mim, e contra a casa de meu pai, e não para castigo de teu povo.

[[v13-21-18]]

^<<v13-21-18,18>>^ Então o anjo do Senhor disse a Gade que dissesse a Davi que subisse Davi para levantar um altar ao Senhor na eira de Ornã, jebuseu.

[[v13-21-19]]

^<<v13-21-19,19>>^ Subiu pois Davi, conforme a palavra de Gade, que falara em nome do Senhor.

[[v13-21-20]]

^<<v13-21-20,20>>^ E, virando-se Ornã, viu o anjo, e se esconderam com ele seus quatro filhos: e Ornã estava trilhando o trigo.

[[v13-21-21]]

^<<v13-21-21,21>>^ E Davi veio a Ornã: e olhou Ornã, e viu a Davi, e saiu da eira, e se prostrou perante Davi com o rosto em terra.

[[v13-21-22]]

^<<v13-21-22,22>>^ E disse Davi a Ornã: Dá-me este  lugar da eira, para edificar nele um altar ao Senhor; dá-mo pelo seu valor, para que cesse este castigo sobre o povo.

[[v13-21-23]]

^<<v13-21-23,23>>^ Então disse Ornã a Davi: Toma- a  para ti, e faça o rei meu Senhor dela  o que parecer  bem aos seus olhos: eis que dou os bois para holocaustos, e os trilhos para lenha, e o trigo para oferta de manjares; tudo dou.

[[v13-21-24]]

^<<v13-21-24,24>>^ E disse o rei Davi a Ornã: Não, antes pelo seu valor a quero comprar: porque não tomarei o que é  teu, para o Senhor; para que não ofereça holocausto sem custo.

[[v13-21-25]]

^<<v13-21-25,25>>^ E Davi deu a Ornã por aquele lugar o peso de seiscentos siclos de ouro.

[[v13-21-26]]

^<<v13-21-26,26>>^ Então Davi edificou ali um altar ao Senhor, e ofereceu nele holocaustos e sacrifícios pacíficos: e invocou o Senhor, o qual lhe respondeu com fogo do céu sobre o altar do holocausto.

[[v13-21-27]]

^<<v13-21-27,27>>^ E o Senhor deu ordem ao anjo, e ele meteu a sua espada na bainha.

[[v13-21-28]]

^<<v13-21-28,28>>^ Vendo Davi, no mesmo tempo, que o Senhor lhe respondera na eira de Ornã, jebuseu, sacrificou ali.

[[v13-21-29]]

^<<v13-21-29,29>>^ Porque o tabernáculo do Senhor, que Moisés fizera no deserto, e o altar do holocausto, estavam  naquele tempo no alto de Gibeom

[[v13-21-30]]

^<<v13-21-30,30>>^ E não podia Davi ir ali consultar ao Senhor; porque estava aterrorizado por causa da espada do anjo do Senhor.

'''

xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[Próximo Capítulo &#62;]