include::./index.adoc[]

[[v13-28-0]]
=== 1 Crônicas, 28
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-28-1]]

^<<v13-28-1,1>>^ ENTÃO Davi convocou em Jerusalém todos os príncipes de Israel, os príncipes das tribos, e os capitães das turmas, que serviam o rei, e os capitães, dos milhares, e os capitães das centenas, e os maiorais de toda a fazenda e possessão do rei, e de seus filhos, como também os eunucos e varões, e todo o varão valente.

[[v13-28-2]]

^<<v13-28-2,2>>^ E pôs-se o rei Davi em pé, e disse: Ouvi-me, irmãos meus, e povo meu: Em meu coração propus  eu edificar uma  casa de repouso para a arca do concerto do Senhor e para o escabelo dos pés do nosso Deus, e eu tinha feito o preparo para a edificar.

[[v13-28-3]]

^<<v13-28-3,3>>^ Porém Deus me disse: Não edificarás casa ao meu nome, porque és homem de guerra, e derramaste muito sangue.

[[v13-28-4]]

^<<v13-28-4,4>>^ E o Senhor Deus de Israel escolheu-me de toda a casa de meu pai, para que eternamente fosse rei sobre Israel; porque a Judá escolheu por príncipe, e a casa de meu pai na casa de Judá: e entre os filhos de meu pai se agradou de mim para me fazer rei sobre todo o Israel.

[[v13-28-5]]

^<<v13-28-5,5>>^ E, de todos os meus filhos (porque muitos filhos me deu o Senhor), escolheu ele o meu filho Salomão para se assentar no trono do reino do Senhor sobre Israel.

[[v13-28-6]]

^<<v13-28-6,6>>^ E me disse: Teu filho Salomão, ele edificará a minha casa e os meus átrios, porque o escolhi para filho, e eu lhe serei por pai.

[[v13-28-7]]

^<<v13-28-7,7>>^ E estabelecerei o seu reino para sempre, se perseverar em cumprir os meus mandamentos e os meus juízos, como até  ao dia de hoje.

[[v13-28-8]]

^<<v13-28-8,8>>^ Agora, pois, perante os olhos de todo o Israel, a congregação do Senhor, e perante os ouvidos do nosso Deus, guardai e buscai todos os mandamentos do Senhor vosso Deus, para que possuais esta boa terra, e a façais herdar a vossos filhos depois de vós, para sempre.

[[v13-28-9]]

^<<v13-28-9,9>>^ E tu, meu filho Salomão, conhece o Deus de teu pai, e serve-o com um  coração perfeito e com uma  alma voluntária; porque esquadrinha o Senhor todos os corações, e entende todas as imaginações dos pensamentos: se o buscares, será achado de ti; porém, se o deixares, rejeitar-te-á para sempre.

[[v13-28-10]]

^<<v13-28-10,10>>^ Olha pois  agora, porque o Senhor te escolheu para edificares uma  casa para o santuário; esforça-te e faze a obra.

[[v13-28-11]]

^<<v13-28-11,11>>^ E deu Davi a Salomão, seu filho, o risco do alpendre com as suas casarias, e as suas tesourarias, e os seus cenáculos, e as suas recâmaras de dentro, como também da casa do propiciatório.

[[v13-28-12]]

^<<v13-28-12,12>>^ E também  o risco de tudo quanto tinha no seu ânimo, a saber : Dos átrios da casa do Senhor, e de todas as câmaras em redor, e para os tesouros da casa de Deus, e para os tesouros das cousas sagradas:

[[v13-28-13]]

^<<v13-28-13,13>>^ E das turmas dos sacerdotes, e dos levitas, e de toda a obra do ministério da casa do Senhor, e de todos os vasos do ministério da casa do Senhor.

[[v13-28-14]]

^<<v13-28-14,14>>^ O ouro deu , segundo o peso do ouro, para todos os vasos de cada ministério: também a prata , por peso, para todos os vasos de prata, para todos os vasos de cada espécie de serviço;

[[v13-28-15]]

^<<v13-28-15,15>>^ E o peso para os castiçais de ouro, e suas candeias de ouro, segundo o peso de cada castiçal e as suas candeias: também para os castiçais de prata, segundo o peso do castiçal e as suas candeias, segundo o uso de cada castiçal.

[[v13-28-16]]

^<<v13-28-16,16>>^ Também deu  o ouro por peso para as mesas da proposição, para cada mesa: como também a prata para as mesas de prata.

[[v13-28-17]]

^<<v13-28-17,17>>^ E ouro puro para os garfos, e para as bacias, e para as escudelas, e para as taças de ouro, para cada taça seu  peso; como também para as taças de prata, para cada taça seu  peso.

[[v13-28-18]]

^<<v13-28-18,18>>^ E para o altar do incenso, ouro purificado, por seu  peso: como também o ouro para o modelo do carro, a saber , dos querubins, que haviam de estender as asas , e cobrir a arca do concerto do Senhor.

[[v13-28-19]]

^<<v13-28-19,19>>^ Tudo isso, disse Davi , por escrito me deram a entender por mandado do Senhor, a saber , todas as obras deste risco.

[[v13-28-20]]

^<<v13-28-20,20>>^ E disse Davi a Salomão seu filho: Esforça-te e tem bom ânimo, e obra; não temas, nem te apavores; porque o Senhor Deus, meu Deus, há de ser  contigo; não te deixará, nem te desamparará, até que acabes toda a obra do serviço da casa do Senhor.

[[v13-28-21]]

^<<v13-28-21,21>>^ E eis que aí tens as turmas dos sacerdotes e dos levitas para todo o ministério da casa de Deus: estão  também contigo, para toda a obra, voluntários com sabedoria de toda a espécie para todo o ministério; como também todos os príncipes, e todo o povo, para todos os teus  mandados.

'''

xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[&#60; Capítulo Anterior] | <<v13-28-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-029.adoc#v13-29-0[Próximo Capítulo &#62;]