include::./index.adoc[]

[[v13-19-0]]
=== 1 Crônicas, 19
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-19-1]]

^<<v13-19-1,1>>^ E ACONTECEU, depois disto, que Naás, rei dos filhos de Amom, morreu: e seu filho reinou em seu lugar.

[[v13-19-2]]

^<<v13-19-2,2>>^ Então disse Davi: Usarei de beneficência com Hanum, filho de Naás, porque seu pai usou de beneficência comigo. Pelo que Davi enviou mensageiros para o consolarem acerca de seu pai. E, vindo os servos de Davi à terra dos filhos de Amom, a Hanum, para o consolarem,

[[v13-19-3]]

^<<v13-19-3,3>>^ Disseram os príncipes dos filhos de Amom a Hanum: Porventura  honra Davi a teu pai aos teus olhos, porque te mandou consoladores? Não vieram seus servos a ti, a esquadrinhar, e a transtornar, e a espiar a terra?

[[v13-19-4]]

^<<v13-19-4,4>>^ Pelo que Hanum tomou os servos de Davi, e os rapou, e lhes cortou os vestidos pelo meio até à coxa da perna, e os despediu.

[[v13-19-5]]

^<<v13-19-5,5>>^ E foram-se, e avisaram a Davi acerca destes homens, e mandou ao encontro deles; porque aqueles homens estavam sobremaneira envergonhados. Disse pois o rei: Deixai-vos ficar em Jericó, até que vos torne a crescer a barba, e então  tornai.

[[v13-19-6]]

^<<v13-19-6,6>>^ Vendo pois os filhos de Amom que se tinham feito odiosos para com Davi, então enviou Hanum, e os filhos de Amom, mil talentos de prata, para alugarem para si carros e cavaleiros de Mesopotâmia, e da Síria de Maaca, e de Zobá.

[[v13-19-7]]

^<<v13-19-7,7>>^ E alugaram para si trinta e dois mil carros, e o rei de Maaca e a sua gente, e eles vieram e se acamparam diante de Medeba: também os filhos de Amom se ajuntaram das suas cidades, e vieram para a guerra.

[[v13-19-8]]

^<<v13-19-8,8>>^ O que ouvindo Davi, enviou Joabe e todo o exército dos homens valorosos.

[[v13-19-9]]

^<<v13-19-9,9>>^ E, saindo os filhos de Amom, ordenaram a batalha à porta da cidade; porém os reis que vieram se puseram  à parte no campo.

[[v13-19-10]]

^<<v13-19-10,10>>^ E, vendo Joabe que a frente da batalha estava contra ele por diante e por detrás, fez escolha dentre os mais escolhidos de Israel, e os ordenou contra os siros:

[[v13-19-11]]

^<<v13-19-11,11>>^ E o resto do povo entregou na mão de Abisai, seu irmão; e puseram-se em ordem de batalha contra os filhos de Amom.

[[v13-19-12]]

^<<v13-19-12,12>>^ E disse: Se os siros forem mais fortes do que eu, tu virás socorrer-me; e, se os filhos de Amom forem mais fortes do que tu, então  eu te socorrerei a ti.

[[v13-19-13]]

^<<v13-19-13,13>>^ Esforça-te, e esforcemo-nos pelo nosso povo, e pelas cidades do nosso Deus, e faça o Senhor o que parecer  bem aos seus olhos.

[[v13-19-14]]

^<<v13-19-14,14>>^ Então se chegou Joabe, e o povo que tinha consigo diante dos siros, para a batalha; e fugiram de diante dele.

[[v13-19-15]]

^<<v13-19-15,15>>^ Vendo pois os filhos de Amom que os siros fugiram, também eles fugiram de diante de Abisai, seu irmão, e entraram na cidade: e veio Joabe para Jerusalém.

[[v13-19-16]]

^<<v13-19-16,16>>^ E, vendo os siros que foram derrotados diante de Israel, enviaram mensageiros, e fizeram sair os siros que habitavam  da banda dalém do rio; e Sofaque, capitão do exército de Hadar-Ezer, marchava  diante deles.

[[v13-19-17]]

^<<v13-19-17,17>>^ Do que avisado Davi, ajuntou a todo o Israel, e passou o Jordão, e veio ter com eles, e ordenou contra eles a batalha : e, tendo Davi ordenado a batalha contra os siros, pelejaram estes contra ele.

[[v13-19-18]]

^<<v13-19-18,18>>^ Porém os siros fugiram de diante de Israel, e feriu Davi, dos siros, sete mil cavalos de  carros, e quarenta mil homens de pé: e a Sofaque, capitão do exército, matou.

[[v13-19-19]]

^<<v13-19-19,19>>^ Vendo pois os servos de Hadar-Ezer que tinham sido feridos diante de Israel, fizeram paz com Davi, e o serviram: e os siros nunca mais quiseram socorrer os filhos de Amom.

'''

xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[&#60; Capítulo Anterior] | <<v13-19-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[Próximo Capítulo &#62;]