include::./index.adoc[]

[[v13-8-0]]
=== 1 Crônicas, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-8-1]]

^<<v13-8-1,1>>^ E BENJAMIM gerou a Bela, seu primogênito, a Asbel o segundo, e a Aará o terceiro.

[[v13-8-2]]

^<<v13-8-2,2>>^ A Noá o quarto, e a Rafa o quinto,

[[v13-8-3]]

^<<v13-8-3,3>>^ E Bela teve estes  filhos: Adar, e Gera, e Abiúde.

[[v13-8-4]]

^<<v13-8-4,4>>^ E Abisua, e Naamã, e Aoá,

[[v13-8-5]]

^<<v13-8-5,5>>^ E Gera, e Sefufã, e Hurão.

[[v13-8-6]]

^<<v13-8-6,6>>^ E estes foram  os filhos de Eude: estes foram chefes dos pais dos moradores de Geba, e os transportaram a Manaate;

[[v13-8-7]]

^<<v13-8-7,7>>^ E Naamã, e Aías, e Gera; a estes transportou, e gerou a Uzá e a Aiude.

[[v13-8-8]]

^<<v13-8-8,8>>^ E Saaraim (depois de os enviar), na terra de Moabe, gerou, filhos de  Husim e Baara, suas mulheres.

[[v13-8-9]]

^<<v13-8-9,9>>^ E de Hodes, sua mulher, gerou a Jobabe, e a Zíbia, e a Messa, e a Malcã,

[[v13-8-10]]

^<<v13-8-10,10>>^ E a Jeús, e a Saquias, e a Mirma: estes foram  seus filhos, chefes dos pais.

[[v13-8-11]]

^<<v13-8-11,11>>^ E de Husim gerou a Abitude e a Elpaal.

[[v13-8-12]]

^<<v13-8-12,12>>^ E foram  os filhos de Elpaal: Éber, e Misã, e Sêmer: este edificou a Ono e a Lode e os lugares da sua jurisdição.

[[v13-8-13]]

^<<v13-8-13,13>>^ E Beria e Sema foram  cabeças dos pais dos moradores de Aijalom; estes afugentaram os moradores de Gate.

[[v13-8-14]]

^<<v13-8-14,14>>^ E Aío, e Sasaque, e Jerimote,

[[v13-8-15]]

^<<v13-8-15,15>>^ E Zebadias, e Arade, e Eder,

[[v13-8-16]]

^<<v13-8-16,16>>^ E Micael, e Ispá, e Joá, foram  filhos de Beria:

[[v13-8-17]]

^<<v13-8-17,17>>^ E Zebadias, e Mesulão, e Hizqui, e Héber,

[[v13-8-18]]

^<<v13-8-18,18>>^ E Ismerai, e Izlias, e Jobabe, filhos de Elpaal:

[[v13-8-19]]

^<<v13-8-19,19>>^ E Jaquim, e Zicri, e Zabdi,

[[v13-8-20]]

^<<v13-8-20,20>>^ E Elienai, e Ziletai, e Eliel,

[[v13-8-21]]

^<<v13-8-21,21>>^ E Adaías e Beraías, e Sinrate, filhos de Simei:

[[v13-8-22]]

^<<v13-8-22,22>>^ E Ispã, e Éber, e Eliel.

[[v13-8-23]]

^<<v13-8-23,23>>^ E Abdom, e Zicri, e Hanã,

[[v13-8-24]]

^<<v13-8-24,24>>^ E Hananias, e Elão, e Antotija,

[[v13-8-25]]

^<<v13-8-25,25>>^ E Ifdias, e Penuel, filhos de Sasaque:

[[v13-8-26]]

^<<v13-8-26,26>>^ E Sanserai, e Searias, e Atalias,

[[v13-8-27]]

^<<v13-8-27,27>>^ E Jaaresias, e Elias, e Zicri, filhos de Jeroão.

[[v13-8-28]]

^<<v13-8-28,28>>^ Estes foram  chefes dos pais, segundo as suas gerações, e  estes habitaram em Jerusalém.

[[v13-8-29]]

^<<v13-8-29,29>>^ E em Gibeom habitou o pai de Gibeom: e era  o nome de sua mulher Maaca;

[[v13-8-30]]

^<<v13-8-30,30>>^ E seu filho primogênito Abdom; depois Zur, e Quis, e Baal, e Nadabe,

[[v13-8-31]]

^<<v13-8-31,31>>^ E Gedor, e Aío e Zequer.

[[v13-8-32]]

^<<v13-8-32,32>>^ E Miclote gerou a Simeia: e também estes, defronte de seus irmãos, habitaram em Jerusalém com seus irmãos.

[[v13-8-33]]

^<<v13-8-33,33>>^ E Ner gerou a Quis, e Quis gerou a Saul; e Saul gerou a Jônatas, e a Malquisua, e a Abinadabe, e a Esbaal.

[[v13-8-34]]

^<<v13-8-34,34>>^ E filho de Jônatas foi Meribaal: e Meribaal gerou a Mica.

[[v13-8-35]]

^<<v13-8-35,35>>^ E os filhos de Mica foram : Pitom, e Meleque, e Tarea, e Acaz.

[[v13-8-36]]

^<<v13-8-36,36>>^ E Acaz gerou a Joada, e Joada gerou a Aelemete, e a Azmavete, e a Zinri; e Zinri gerou a Mosa,

[[v13-8-37]]

^<<v13-8-37,37>>^ E Mosa gerou a Bina, cujo filho foi Rafa, cujo filho foi Elasa, cujo filho foi Asel.

[[v13-8-38]]

^<<v13-8-38,38>>^ E teve Asel seis filhos, e estes foram  os seus nomes: Azricão, e Bocru, e Ismael, e Searias, e Obadias, e Hanã: todos estes foram  filhos de Asel.

[[v13-8-39]]

^<<v13-8-39,39>>^ E os filhos de Eseque, seu irmão: Ulão, seu primogênito, Jeús o segundo, e Elifelete o terceiro.

[[v13-8-40]]

^<<v13-8-40,40>>^ E foram  os filhos de Ulão varões heróis, valentes, e frecheiros destros; e tiveram muitos filhos, e filhos de filhos, cento e cinquenta: todos estes foram dos filhos de Benjamim.

'''

xref:013-1-cronicas/013-1-cronicas-007.adoc#v13-7-0[&#60; Capítulo Anterior] | <<v13-8-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-009.adoc#v13-9-0[Próximo Capítulo &#62;]