include::./index.adoc[]

[[v13-20-0]]
=== 1 Crônicas, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-20-1]]

^<<v13-20-1,1>>^ ACONTECEU pois que, no decurso de um  ano, no tempo em que os reis costumam sair para a guerra , Joabe levou o exército e destruiu a terra dos filhos de Amom e veio e cercou a Rabá, porém, Davi ficou em Jerusalém: e Joabe feriu a Rabá, e a destruiu.

[[v13-20-2]]

^<<v13-20-2,2>>^ E Davi tirou da cabeça do rei a coroa deste, e achou nela o peso dum talento de ouro, e havia  nela pedras preciosas; e foi posta sobre a cabeça de Davi: e levou da cidade mui grande despojo.

[[v13-20-3]]

^<<v13-20-3,3>>^ Também o povo que estava  nela levou e os  fez serrar com a serra, e cortar  com talhadeiras de ferro e com machados; e assim fez Davi com todas as cidades dos filhos de Amom: então voltou Davi, com todo o povo, para Jerusalém.

[[v13-20-4]]

^<<v13-20-4,4>>^ E depois disto aconteceu que, levantando-se guerra em Gazer com os filisteus, então Sibecai, o husatita, feriu a Sipai, dos filhos de Rafa; e ficaram abatidos.

[[v13-20-5]]

^<<v13-20-5,5>>^ E tornou a haver guerra com os filisteus: e Elanã, filho de Jair, feriu a Lami, irmão de Golias, o geteu, cuja haste da lança era  como órgão de tecelão.

[[v13-20-6]]

^<<v13-20-6,6>>^ E tornou a haver guerra em Gate; e havia ali um homem de grande  estatura, e tinha vinte e quatro dedos, seis em cada mão, e seis em cada pé, e também era da raça de Rafa.

[[v13-20-7]]

^<<v13-20-7,7>>^ E injuriou a Israel: porém Jônatas, filho de Simeia, irmão de Davi, o feriu.

[[v13-20-8]]

^<<v13-20-8,8>>^ Estes nasceram a Rafa em Gate: e caíram pela mão de Davi e pela mão dos seus servos.

'''

xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[&#60; Capítulo Anterior] | <<v13-20-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[Próximo Capítulo &#62;]