include::./index.adoc[]

[[v13-2-0]]
=== 1 Crônicas, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v13-2-1]]

^<<v13-2-1,1>>^ ESTES são  os filhos de Israel: Rúben, Simeão, Levi, Judá, Issacar e Zebulom;

[[v13-2-2]]

^<<v13-2-2,2>>^ Dã, José e Benjamim, Naftali, Gade e Aser.

[[v13-2-3]]

^<<v13-2-3,3>>^ Os filhos de Judá foram  Er, e Onã, e Selá: estes  três lhe nasceram da filha de Suá, a cananeia: e Er, o primogênito de Judá, foi mau aos olhos do Senhor, pelo que o matou.

[[v13-2-4]]

^<<v13-2-4,4>>^ Porém Tamar, sua nora lhe deu à luz a Perez e a Será: todos os filhos de Judá foram  cinco.

[[v13-2-5]]

^<<v13-2-5,5>>^ Os filhos de Perez foram  Hezrom e Hamul.

[[v13-2-6]]

^<<v13-2-6,6>>^ E os filhos de Será: Zinri, e Etã, e Hemã, e Calcol, e Dara: cinco ao todo.

[[v13-2-7]]

^<<v13-2-7,7>>^ E os filhos de Carmi foram  Acar, o perturbador de Israel, que pecou no anátema.

[[v13-2-8]]

^<<v13-2-8,8>>^ E os filhos de Etã foram  Azarias.

[[v13-2-9]]

^<<v13-2-9,9>>^ E os filhos de Hezrom, que lhe nasceram, foram  Jerameel, e Rão, e Quelubai.

[[v13-2-10]]

^<<v13-2-10,10>>^ E Rão gerou a Aminadabe, e Aminadabe gerou a Naassom, príncipe dos filhos de Judá.

[[v13-2-11]]

^<<v13-2-11,11>>^ E Naassom gerou a Salma, e Salma gerou a Booz.

[[v13-2-12]]

^<<v13-2-12,12>>^ E Booz gerou a Obede, e Obede gerou a Jessé.

[[v13-2-13]]

^<<v13-2-13,13>>^ E Jessé gerou a Elia, seu primogênito, e Abinadabe, o segundo, e Simeia, o terceiro.

[[v13-2-14]]

^<<v13-2-14,14>>^ Natanael, o quarto, Radai, o quinto,

[[v13-2-15]]

^<<v13-2-15,15>>^ Ozém, o sexto, Davi, o sétimo.

[[v13-2-16]]

^<<v13-2-16,16>>^ E foram  suas irmãs Zeruia e Abigail: e foram  os filhos de Zeruia: Abisai, e Joabe, e Asael, três.

[[v13-2-17]]

^<<v13-2-17,17>>^ E Abigail teve a Amasa: e o pai de Amasa foi  Jéter, o ismaelita.

[[v13-2-18]]

^<<v13-2-18,18>>^ E Calebe, filho de Hezrom, gerou filhos  de Azuba, sua mulher, e de Jeriote: e os filhos desta foram  estes: Jeser, e Sobabe, e Ardom.

[[v13-2-19]]

^<<v13-2-19,19>>^ E morreu Azuba; e Calebe tomou para si a Efrate, a qual teve a Hur.

[[v13-2-20]]

^<<v13-2-20,20>>^ E Hur gerou a Uri, e Uri gerou a Bezaleel.

[[v13-2-21]]

^<<v13-2-21,21>>^ Então Hezrom entrou à filha de Maquir, pai de Gileade, e, sendo  ele de sessenta anos, a tomou: e ela deu à luz a Segube.

[[v13-2-22]]

^<<v13-2-22,22>>^ E Segube gerou a Jair: e este tinha vinte e três cidades na terra de Gileade.

[[v13-2-23]]

^<<v13-2-23,23>>^ E Gesur e Arã tomaram deles as aldeias de Jair, e Quenate, e seus lugares, sessenta cidades: todos estes foram  filhos de Maquir, pai de Gileade.

[[v13-2-24]]

^<<v13-2-24,24>>^ E, depois da morte de Hezrom, em Calebe de Efrata, Abia, mulher de Hezrom, lhe deu a Assur, pai de Técoa.

[[v13-2-25]]

^<<v13-2-25,25>>^ E os filhos de Jerameel, primogênito de Hezrom, foram  Rão, o primogênito, e Buna, e Orém, e Ozém, e  Aía.

[[v13-2-26]]

^<<v13-2-26,26>>^ Teve também Jerameel ainda  outra mulher, cujo nome era  Átara; esta foi a mãe de Onã.

[[v13-2-27]]

^<<v13-2-27,27>>^ E foram os filhos de Rão, primogênito de Jerameel: Maaz, e Jamim, e Equer.

[[v13-2-28]]

^<<v13-2-28,28>>^ E foram os filhos de Onã: Samai e Jada; e os filhos de Samai: Nadabe e Abisur.

[[v13-2-29]]

^<<v13-2-29,29>>^ E era  o nome da mulher de Abisur Abiail, que lhe deu a Abã e a Molide.

[[v13-2-30]]

^<<v13-2-30,30>>^ E foram  os filhos de Nadabe Selede e Apaim: e Selede morreu sem filhos.

[[v13-2-31]]

^<<v13-2-31,31>>^ E os filhos de Apaim foram  Isi; e os filhos de Isi: Sesã. E os filhos de Sesã: Álai.

[[v13-2-32]]

^<<v13-2-32,32>>^ E os filhos de Jada, irmão de Samai, foram : Jéter e Jônatas: e Jéter morreu sem filhos.

[[v13-2-33]]

^<<v13-2-33,33>>^ E os filhos de Jônatas foram  Pelete e Zaza: estes foram os filhos de Jerameel.

[[v13-2-34]]

^<<v13-2-34,34>>^ E Sesã não teve filhos, mas filhas: e tinha Sesã um servo egípcio cujo nome era  Jara.

[[v13-2-35]]

^<<v13-2-35,35>>^ Deu pois Sesã sua filha por mulher a Jara, seu servo: e lhe deu a Atai.

[[v13-2-36]]

^<<v13-2-36,36>>^ E Atai gerou a Natã, e Natã, gerou a Zabade.

[[v13-2-37]]

^<<v13-2-37,37>>^ E Zabade gerou a Eflal, e Eflal gerou a Obede.

[[v13-2-38]]

^<<v13-2-38,38>>^ E Obede gerou a Jeú, e Jeú gerou a Azarias.

[[v13-2-39]]

^<<v13-2-39,39>>^ E Azarias gerou a Heles, e Heles gerou a Eleasá.

[[v13-2-40]]

^<<v13-2-40,40>>^ E Eleasá gerou a Sismai, e Sismai gerou a Salum.

[[v13-2-41]]

^<<v13-2-41,41>>^ E Salum gerou a Jecamias, e Jecamias gerou a Elisama.

[[v13-2-42]]

^<<v13-2-42,42>>^ E foram  os filhos de Calebe, irmão de Jerameel, Messa, seu primogênito (este foi  o pai de Zife), e os filhos de Maresa, pai de Hebrom.

[[v13-2-43]]

^<<v13-2-43,43>>^ E foram  os filhos de Hebrom: Cora, e Tápua, e Requém, e Sema.

[[v13-2-44]]

^<<v13-2-44,44>>^ E Sema gerou a Raão, pai de Jorqueão: e Requém gerou a Samai.

[[v13-2-45]]

^<<v13-2-45,45>>^ E foi  o filho de Samai Maom; e Maom foi  pai de Bete-Zur.

[[v13-2-46]]

^<<v13-2-46,46>>^ E Efa, a concubina de Calebe, teve a Harã, e a Mosa, e a Gazez: e Harã gerou a Gazez.

[[v13-2-47]]

^<<v13-2-47,47>>^ E foram  os filhos de Jodai: Regem, e Jotão, e Gesã, e Pelete, e Efa, e Saafe.

[[v13-2-48]]

^<<v13-2-48,48>>^ De Maaca, concubina, gerou Calebe a Séber e a Tiraná.

[[v13-2-49]]

^<<v13-2-49,49>>^ E a mulher de Saafe, pai de Madmana, teve a Seva, pai de Macbena e pai de Gibeá: e foi  a filha de Calebe Acsa.

[[v13-2-50]]

^<<v13-2-50,50>>^ Estes foram os filhos de Calebe, filho de Ur, o primogênito de Efrata: Sobal, pai do Quiriate-Jearim,

[[v13-2-51]]

^<<v13-2-51,51>>^ Salma, pai dos belemitas, Harefe, pai de Bete-Gader.

[[v13-2-52]]

^<<v13-2-52,52>>^ E foram os filhos de Sobal, pai de Quiriate-Jearim: Haroé e  metade dos menuítas.

[[v13-2-53]]

^<<v13-2-53,53>>^ E as famílias de Quiriate-Jearim foram  os jetreus, e os puteus, e os sumateus, e os misraeus; destes saíram os zorateus, e os estaoleus.

[[v13-2-54]]

^<<v13-2-54,54>>^ Os filhos de Salma foram  Belém e os netofatitas, Atrote, e  Bete-Joabe, e metade dos manatitas, e  os zoritas.

[[v13-2-55]]

^<<v13-2-55,55>>^ E as famílias dos escribas que habitavam em Jabez foram  os tiratitas, os simatitas e os sucatitas: estes são  os quineus, que vieram de Hamate, pai da casa de Recabe.

'''

xref:013-1-cronicas/013-1-cronicas-001.adoc#v13-1-0[&#60; Capítulo Anterior] | <<v13-2-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[Próximo Capítulo &#62;]