include::./index.adoc[]

[[v59-1-0]]
=== Tiago, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v59-1-1]]

^<<v59-1-1,1>>^ TIAGO, servo de Deus, e do Senhor Jesus Cristo, às doze tribos que andam dispersas, saúde.

[[v59-1-2]]

^<<v59-1-2,2>>^ Meus irmãos, tende grande gozo quando cairdes em várias tentações:

[[v59-1-3]]

^<<v59-1-3,3>>^ Sabendo que a prova da vossa fé obra a paciência.

[[v59-1-4]]

^<<v59-1-4,4>>^ Tenha, porém, a paciência a sua obra perfeita, para que sejais perfeitos e completos, sem faltar em coisa alguma.

[[v59-1-5]]

^<<v59-1-5,5>>^ E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente, e o  não lança em rosto, e ser-lhe-á dada.

[[v59-1-6]]

^<<v59-1-6,6>>^ Peça-a, porém, com fé, não duvidando; porque o que duvida é semelhante à onda do mar, que é levada pelo vento e lançada de uma para outra parte.

[[v59-1-7]]

^<<v59-1-7,7>>^ Não pense tal homem que receberá do Senhor alguma coisa.

[[v59-1-8]]

^<<v59-1-8,8>>^ O homem de coração dobre é inconstante em todos os seus caminhos.

[[v59-1-9]]

^<<v59-1-9,9>>^ Mas glorie-se o irmão abatido na sua exaltação,

[[v59-1-10]]

^<<v59-1-10,10>>^ E o rico em seu abatimento; porque ele passará como a flor da erva.

[[v59-1-11]]

^<<v59-1-11,11>>^ Porque sai o sol com ardor, e a erva seca, e a sua flor cai, e a formosa aparência do seu aspecto perece: assim se murchará também o rico em seus caminhos.

[[v59-1-12]]

^<<v59-1-12,12>>^ Bem-aventurado o varão que sofre a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam.

[[v59-1-13]]

^<<v59-1-13,13>>^ Ninguém, sendo tentado, diga: De Deus sou tentado; porque Deus não pode ser tentado pelo mal, e a ninguém tenta.

[[v59-1-14]]

^<<v59-1-14,14>>^ Mas cada um é tentado, quando atraído e engodado pela sua própria concupiscência.

[[v59-1-15]]

^<<v59-1-15,15>>^ Depois, havendo a concupiscência concebido, dá à luz o pecado; e o pecado, sendo consumado, gera a morte.

[[v59-1-16]]

^<<v59-1-16,16>>^ Não erreis, meus amados irmãos.

[[v59-1-17]]

^<<v59-1-17,17>>^ Toda a boa dádiva e todo o dom perfeito vêm do alto, descendo do Pai das luzes, em quem não há mudança nem sombra de variação.

[[v59-1-18]]

^<<v59-1-18,18>>^ Segundo a sua vontade, ele nos gerou pela palavra da verdade, para que fôssemos como  primícias das suas criaturas.

[[v59-1-19]]

^<<v59-1-19,19>>^ Sabeis isto, meus amados irmãos; mas todo o homem seja pronto para ouvir, tardio para falar, tardio para se irar.

[[v59-1-20]]

^<<v59-1-20,20>>^ Porque a ira do homem não opera a justiça de Deus.

[[v59-1-21]]

^<<v59-1-21,21>>^ Pelo que, rejeitando toda a imundícia e superfluidade de malícia, recebei com mansidão a palavra em vós enxertada, a qual pode salvar as vossas almas.

[[v59-1-22]]

^<<v59-1-22,22>>^ E sede cumpridores da palavra, e não somente ouvintes, enganando-vos com falsos discursos.

[[v59-1-23]]

^<<v59-1-23,23>>^ Porque, se alguém é ouvinte da palavra, e não cumpridor, é semelhante ao varão que contempla ao espelho o seu rosto natural;

[[v59-1-24]]

^<<v59-1-24,24>>^ Porque se contempla a si mesmo, e foi-se, e logo se esqueceu de que tal era.

[[v59-1-25]]

^<<v59-1-25,25>>^ Aquele, porém, que atenta bem para a lei perfeita da liberdade, e nisso persevera, não sendo ouvinte esquecido, mas fazedor da obra, este tal será bem-aventurado no seu feito.

[[v59-1-26]]

^<<v59-1-26,26>>^ Se alguém entre vós cuida ser religioso, e não refreia a sua língua, antes engana o seu coração, a religião desse é vã.

[[v59-1-27]]

^<<v59-1-27,27>>^ A religião pura e imaculada para com Deus, o Pai, é esta: Visitar os órfãos e as viúvas nas suas tribulações, e guardar-se da corrupção do mundo.

'''

xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[&#60; Capítulo Anterior] | <<v59-1-0,Topo>> | xref:059-tiago/059-tiago-002.adoc#v59-2-0[Próximo Capítulo &#62;]