include::./index.adoc[]

[[v59-5-0]]
=== Tiago, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v59-5-1]]

^<<v59-5-1,1>>^ EIA pois agora vós, ricos, chorai, e pranteai, por vossas misérias, que sobre vós hão de vir.

[[v59-5-2]]

^<<v59-5-2,2>>^ As vossas riquezas estão apodrecidas, e os vossos vestidos estão comidos da traça.

[[v59-5-3]]

^<<v59-5-3,3>>^ O vosso ouro e a vossa prata se enferrujaram; e a sua ferrugem dará testemunho contra vós, e comerá como fogo a vossa carne. Entesourastes para os últimos dias.

[[v59-5-4]]

^<<v59-5-4,4>>^ Eis que o jornal dos trabalhadores que ceifaram as vossas terras, e que por vós foi diminuído, clama; e os clamores dos que ceifaram entraram nos ouvidos do Senhor dos exércitos.

[[v59-5-5]]

^<<v59-5-5,5>>^ Deliciosamente, vivestes sobre a terra, e vos deleitastes: cevastes os vossos corações, como num dia de matança.

[[v59-5-6]]

^<<v59-5-6,6>>^ Condenastes e matastes o justo; ele não vos resistiu.

[[v59-5-7]]

^<<v59-5-7,7>>^ Sede pois irmãos, pacientes até a vinda do Senhor. Eis que o lavrador espera o precioso fruto da terra, aguardando-o com paciência, até que receba a chuva temporã e serôdia.

[[v59-5-8]]

^<<v59-5-8,8>>^ Sede vós também pacientes, fortalecei os vossos corações; porque já  a vinda do Senhor está próxima.

[[v59-5-9]]

^<<v59-5-9,9>>^ Irmãos, não vos queixeis uns contra os outros, para que não sejais condenados. Eis que o juiz está à porta.

[[v59-5-10]]

^<<v59-5-10,10>>^ Meus irmãos, tomai por exemplo de aflição e paciência os profetas que falaram em nome do Senhor.

[[v59-5-11]]

^<<v59-5-11,11>>^ Eis que temos por bem-aventurados os que sofreram. Ouvistes qual foi a paciência de Jó, e vistes o fim que o Senhor lhe deu ; porque o Senhor é muito misericordioso e piedoso.

[[v59-5-12]]

^<<v59-5-12,12>>^ Mas, sobretudo, meus irmãos, não jureis, nem pelo céu, nem pela terra nem façais  qualquer outro juramento; mas que a vossa palavra seja sim, sim, e não, não; para que não caiais em condenação.

[[v59-5-13]]

^<<v59-5-13,13>>^ Está alguém entre vós aflito? Ore. Está alguém contente? Cante louvores.

[[v59-5-14]]

^<<v59-5-14,14>>^ Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor;

[[v59-5-15]]

^<<v59-5-15,15>>^ E a oração da fé salvará o doente, e o Senhor o levantará; e, se houver cometido pecados, ser-lhe-ão perdoados.

[[v59-5-16]]

^<<v59-5-16,16>>^ Confessai as vossas culpas uns aos outros, e orai uns pelos outros, para que sareis: a oração feita por um justo pode muito em seus efeitos.

[[v59-5-17]]

^<<v59-5-17,17>>^ Elias era homem sujeito às mesmas paixões que nós, e, orando, pediu que não chovesse, e, por três anos e seis meses, não choveu sobre a terra.

[[v59-5-18]]

^<<v59-5-18,18>>^ E orou outra vez, e o céu deu chuva, e a terra produziu o seu fruto.

[[v59-5-19]]

^<<v59-5-19,19>>^ Irmãos, se algum de entre vós se tem desviado da verdade, e alguém o converter,

[[v59-5-20]]

^<<v59-5-20,20>>^ Saiba que aquele que fizer converter do erro do seu caminho um pecador salvará da morte uma alma, e cobrirá uma multidão de pecados.

'''

xref:059-tiago/059-tiago-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[Próximo Capítulo &#62;]