include::./index.adoc[]

[[v59-4-0]]
=== Tiago, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v59-4-1]]

^<<v59-4-1,1>>^ DONDE vêm  as guerras e pelejas entre vós? Porventura não vêm  disto, a saber , dos vossos deleites, que nos vossos membros guerreiam?

[[v59-4-2]]

^<<v59-4-2,2>>^ Cobiçais, e nada tendes: sois invejosos e cobiçosos, e não podeis alcançar: combateis e guerreais, e nada tendes, porque não pedis.

[[v59-4-3]]

^<<v59-4-3,3>>^ Pedis, e não recebeis, porque pedis mal, para o gastardes em vossos deleites.

[[v59-4-4]]

^<<v59-4-4,4>>^ Adúlteros e adúlteras, não sabeis vós que a amizade do mundo é inimizade contra Deus? Portanto qualquer que quiser ser amigo do mundo constitui-se inimigo de Deus.

[[v59-4-5]]

^<<v59-4-5,5>>^ Ou cuidais vós que em vão diz a Escritura: O espírito que em nós habita tem ciúmes?

[[v59-4-6]]

^<<v59-4-6,6>>^ Antes dá maior graça. Portanto diz: Deus resiste aos soberbos, dá, porém, graça aos humildes.

[[v59-4-7]]

^<<v59-4-7,7>>^ Sujeitai-vos pois a Deus, resisti ao diabo, e ele fugirá de vós.

[[v59-4-8]]

^<<v59-4-8,8>>^ Chegai-vos a Deus, e ele se chegará a vós. Alimpai as mãos, pecadores; e, vós de duplo ânimo, purificai os corações.

[[v59-4-9]]

^<<v59-4-9,9>>^ Senti as vossas misérias, e lamentai e chorai: converta-se o vosso riso em pranto, e o vosso  gozo em tristeza.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humilhai-vos perante o Senhor, e ele vos exaltará.

[[v59-4-11]]

^<<v59-4-11,11>>^ Irmãos, não faleis mal uns dos outros. Quem fala mal de um irmão, e julga a seu irmão, fala mal da lei, e julga a lei; e, se tu julgas a lei já  não és observador da lei, mas juiz.

[[v59-4-12]]

^<<v59-4-12,12>>^ Há só um legislador e um juiz que pode salvar e destruir. Tu, porém, quem és, que julgas a outrem?

[[v59-4-13]]

^<<v59-4-13,13>>^ Eia agora vós, que dizeis: Hoje, ou amanhã, iremos a tal cidade, e lá passaremos um ano, e contrataremos, e ganharemos;

[[v59-4-14]]

^<<v59-4-14,14>>^ Digo-vos que não sabeis o que acontecerá  amanhã. Porque, que é a vossa vida? É um vapor que aparece por um pouco, e depois se desvanece.

[[v59-4-15]]

^<<v59-4-15,15>>^ Em lugar do que devíeis dizer: Se o Senhor quiser, e se vivermos, faremos isto ou aquilo.

[[v59-4-16]]

^<<v59-4-16,16>>^ Mas agora vos gloriais em vossas presunções: toda a glória tal como esta é maligna.

[[v59-4-17]]

^<<v59-4-17,17>>^ Aquele pois que sabe fazer o bem e o não faz, comete pecado.

'''

xref:059-tiago/059-tiago-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-tiago/059-tiago-005.adoc#v59-5-0[Próximo Capítulo &#62;]