include::./index.adoc[]

[[v56-1-0]]
=== Tito, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v56-1-1]]

^<<v56-1-1,1>>^ PAULO, servo de Deus, e apóstolo de Jesus Cristo, segundo a fé dos eleitos de Deus, e o conhecimento da verdade, que é segundo a piedade,

[[v56-1-2]]

^<<v56-1-2,2>>^ Em esperança da vida eterna, a qual Deus, que não pode mentir, prometeu antes dos tempos dos séculos:

[[v56-1-3]]

^<<v56-1-3,3>>^ Mas a seu tempo manifestou a sua palavra pela pregação que me foi confiada segundo o mandamento de Deus, nosso Salvador;

[[v56-1-4]]

^<<v56-1-4,4>>^ A Tito, meu verdadeiro filho, segundo a fé comum, graça, misericórdia, e  paz da parte de Deus Pai, e da do Senhor Jesus Cristo, nosso Salvador.

[[v56-1-5]]

^<<v56-1-5,5>>^ Por esta causa te deixei em Creta, para que pusesses em boa ordem as coisas que ainda  restam, e de cidade em cidade estabelecesses presbíteros, como já te mandei:

[[v56-1-6]]

^<<v56-1-6,6>>^ Aquele que for irrepreensível, marido de uma mulher, que tenha filhos fiéis, que não possam ser acusados de dissolução nem são desobedientes.

[[v56-1-7]]

^<<v56-1-7,7>>^ Porque convém que o bispo seja irrepreensível, como despenseiro da casa de Deus, não soberbo, nem iracundo, nem dado ao vinho, nem espancador, nem cobiçoso de torpe ganância;

[[v56-1-8]]

^<<v56-1-8,8>>^ Mas dado à hospitalidade, amigo do bem, moderado, justo, santo, temperante;

[[v56-1-9]]

^<<v56-1-9,9>>^ Retendo firme a fiel palavra, que é conforme a doutrina, para que seja poderoso, tanto para admoestar com a sã doutrina, como para convencer os contradizentes.

[[v56-1-10]]

^<<v56-1-10,10>>^ Porque há muitos desordenados, faladores, vãos e enganadores, principalmente os da circuncisão,

[[v56-1-11]]

^<<v56-1-11,11>>^ Aos quais convém tapar a boca; homens que transtornam casas inteiras ensinando o que não convém, por torpe ganância.

[[v56-1-12]]

^<<v56-1-12,12>>^ Um deles, seu próprio profeta, disse: Os cretenses são  sempre mentirosos, bestas ruins, ventres preguiçosos.

[[v56-1-13]]

^<<v56-1-13,13>>^ Este testemunho é verdadeiro. Portanto repreende-os severamente, para que sejam sãos na fé,

[[v56-1-14]]

^<<v56-1-14,14>>^ Não dando ouvidos às fábulas judaicas, nem aos mandamentos de homens que se desviam da verdade.

[[v56-1-15]]

^<<v56-1-15,15>>^ Todas as coisas são  puras para os puros, mas nada é  puro para os contaminados e infiéis: antes o seu entendimento e consciência estão contaminados.

[[v56-1-16]]

^<<v56-1-16,16>>^ Confessam que conhecem a Deus, mas negam-no com as obras, sendo abomináveis, e desobedientes, e reprovados para toda a boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[&#60; Capítulo Anterior] | <<v56-1-0,Topo>> | xref:056-tito/056-tito-002.adoc#v56-2-0[Próximo Capítulo &#62;]