include::./index.adoc[]

[[v62-3-0]]
=== 1 João, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v62-3-1]]

^<<v62-3-1,1>>^ VEDE quão grande caridade nos tem concedido o Pai: que fôssemos chamados filhos de Deus. Por isso o mundo nos não conhece; porque o não conhece a ele.

[[v62-3-2]]

^<<v62-3-2,2>>^ Amados, agora somos filhos de Deus, e ainda não é manifestado o que havemos de ser. Mas sabemos que, quando ele se manifestar, seremos semelhantes a ele; porque assim como é o veremos.

[[v62-3-3]]

^<<v62-3-3,3>>^ E qualquer que nele tem esta esperança purifica-se a si mesmo, como também ele é puro.

[[v62-3-4]]

^<<v62-3-4,4>>^ Qualquer que comete pecado, também comete iniquidade; porque o pecado é iniquidade.

[[v62-3-5]]

^<<v62-3-5,5>>^ E bem sabeis que ele se manifestou para tirar os nossos pecados; e nele não há pecado.

[[v62-3-6]]

^<<v62-3-6,6>>^ Qualquer que permanece nele não peca: qualquer que peca não o viu nem o conheceu.

[[v62-3-7]]

^<<v62-3-7,7>>^ Filhinhos, ninguém vos engane. Quem pratica justiça é justo, assim como ele é justo.

[[v62-3-8]]

^<<v62-3-8,8>>^ Quem comete o pecado é do diabo; porque o diabo peca desde o princípio. Para isto o Filho de Deus se manifestou: para desfazer as obras do diabo.

[[v62-3-9]]

^<<v62-3-9,9>>^ Qualquer que é nascido de Deus não comete pecado; porque a sua semente permanece nele; e não pode pecar, porque é nascido de Deus.

[[v62-3-10]]

^<<v62-3-10,10>>^ Nisto são manifestos os filhos de Deus, e os filhos do diabo. Qualquer que não pratica a justiça, e não ama a seu irmão, não é de Deus.

[[v62-3-11]]

^<<v62-3-11,11>>^ Porque esta é a mensagem que ouvistes desde o princípio: que nos amemos uns aos outros.

[[v62-3-12]]

^<<v62-3-12,12>>^ Não como Caim, que  era do maligno, e matou a seu irmão. E por que causa o matou? Porque as suas obras eram más e as de seu irmão justas.

[[v62-3-13]]

^<<v62-3-13,13>>^ Meus irmãos, não vos maravilheis, se o mundo vos aborrece.

[[v62-3-14]]

^<<v62-3-14,14>>^ Nós sabemos que passamos da morte para a vida, porque amamos os irmãos: Quem não ama a seu  irmão permanece na morte.

[[v62-3-15]]

^<<v62-3-15,15>>^ Qualquer que aborrece a seu irmão é homicida. E vós sabeis que nenhum homicida tem permanecente nele a vida eterna.

[[v62-3-16]]

^<<v62-3-16,16>>^ Conhecemos a caridade nisto: que ele deu a sua vida por nós, e nós devemos dar a vida pelos irmãos.

[[v62-3-17]]

^<<v62-3-17,17>>^ Quem pois tiver bens do mundo, e, vendo o seu irmão necessitado, lhe cerrar as suas entranhas, como estará nele caridade de Deus?

[[v62-3-18]]

^<<v62-3-18,18>>^ Meus filhinhos não amemos de palavra, nem de língua, mas por obra e em verdade.

[[v62-3-19]]

^<<v62-3-19,19>>^ E nisto conhecemos que somos da verdade, e diante dele asseguraremos nossos corações;

[[v62-3-20]]

^<<v62-3-20,20>>^ Sabendo que, se o nosso coração nos  condena, maior é Deus do que os nossos corações, e conhece todas as coisas.

[[v62-3-21]]

^<<v62-3-21,21>>^ Amados, se o nosso coração nos não condena, temos confiança para com Deus;

[[v62-3-22]]

^<<v62-3-22,22>>^ E qualquer coisa que lhe pedirmos, dele a receberemos; porque guardamos os seus mandamentos, e fazemos o que é agradável à sua vista.

[[v62-3-23]]

^<<v62-3-23,23>>^ E o seu mandamento é este: que creiamos no nome de seu Filho Jesus Cristo, e nos amemos uns aos outros, segundo o seu mandamento.

[[v62-3-24]]

^<<v62-3-24,24>>^ E aquele que guarda os seus mandamentos nele está, e ele nele. E nisto conhecemos que ele está em nós: pelo Espírito que nos tem dado.

'''

xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[&#60; Capítulo Anterior] | <<v62-3-0,Topo>> | xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[Próximo Capítulo &#62;]