include::./index.adoc[]

[[v62-4-0]]
=== 1 João, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v62-4-1]]

^<<v62-4-1,1>>^ AMADOS, não creiais a todo o espírito, mas provai se os espíritos são de Deus; porque já  muitos falsos profetas se têm levantado no mundo.

[[v62-4-2]]

^<<v62-4-2,2>>^ Nisto conhecereis o Espírito de Deus: Todo o espírito que confessa que Jesus Cristo veio em carne é de Deus;

[[v62-4-3]]

^<<v62-4-3,3>>^ E todo o espírito que não confessa que Jesus Cristo veio em carne não é de Deus; mas este é o espírito  do anticristo, do qual já  ouvistes que há de vir, e eis que está já no mundo.

[[v62-4-4]]

^<<v62-4-4,4>>^ Filhinhos, sois de Deus, e já  os tendes vencido; porque maior é o que está em vós do que o que está no mundo.

[[v62-4-5]]

^<<v62-4-5,5>>^ Do mundo são, por isso falam do mundo, e o mundo os ouve.

[[v62-4-6]]

^<<v62-4-6,6>>^ Nós somos de Deus; aquele que conhece a Deus ouve-nos; aquele que não é de Deus não nos ouve. Nisto conhecemos nós o espírito da verdade e o espírito do erro.

[[v62-4-7]]

^<<v62-4-7,7>>^ Amados, amemo-nos uns aos outros; porque a caridade é de Deus; e qualquer que ama é nascido de Deus e conhece a Deus.

[[v62-4-8]]

^<<v62-4-8,8>>^ Aquele que não ama não conhece a Deus; porque Deus é caridade.

[[v62-4-9]]

^<<v62-4-9,9>>^ Nisto se manifestou a caridade de Deus para conosco: que Deus enviou seu Filho unigênito ao mundo, para que por ele vivamos.

[[v62-4-10]]

^<<v62-4-10,10>>^ Nisto está a caridade, não em que nós tenhamos amado a Deus, mas em que ele nos  amou a nós, e enviou seu Filho para  propiciação pelos nossos pecados.

[[v62-4-11]]

^<<v62-4-11,11>>^ Amados, se Deus assim, nos amou, também nos devemos amar uns aos outros.

[[v62-4-12]]

^<<v62-4-12,12>>^ Ninguém jamais viu a Deus; se nos amamos uns aos outros, Deus está em nós, e em nós é perfeita a sua caridade.

[[v62-4-13]]

^<<v62-4-13,13>>^ Nisto conhecemos que estamos nele, e ele em nós, pois que nos deu do seu Espírito,

[[v62-4-14]]

^<<v62-4-14,14>>^ E vimos, e testificamos que o Pai enviou seu Filho para  Salvador do mundo.

[[v62-4-15]]

^<<v62-4-15,15>>^ Qualquer que confessar que Jesus é o Filho de Deus, Deus está nele, e ele em Deus.

[[v62-4-16]]

^<<v62-4-16,16>>^ E nós conhecemos, e cremos no amor que Deus nos tem. Deus é caridade; e quem está em caridade está em Deus, e Deus nele.

[[v62-4-17]]

^<<v62-4-17,17>>^ Nisto é perfeita a caridade para conosco, para que no dia do juízo tenhamos confiança; porque, qual ele é, somos nós também neste mundo.

[[v62-4-18]]

^<<v62-4-18,18>>^ Na caridade não há temor, antes a perfeita caridade lança fora o temor; porque o temor tem consigo a pena, e o que teme não é perfeito em caridade.

[[v62-4-19]]

^<<v62-4-19,19>>^ Nós o amamos a ele porque ele nos amou primeiro.

[[v62-4-20]]

^<<v62-4-20,20>>^ Se alguém diz: Eu amo a Deus, e aborrece a seu irmão, é mentiroso. Pois quem não ama a seu irmão, ao qual viu, como pode amar a Deus, a quem não viu?

[[v62-4-21]]

^<<v62-4-21,21>>^ E dele temos este mandamento: que quem ama a Deus, ame também a seu irmão.

'''

xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[&#60; Capítulo Anterior] | <<v62-4-0,Topo>> | xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[Próximo Capítulo &#62;]