include::./index.adoc[]

[[v62-5-0]]
=== 1 João, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v62-5-1]]

^<<v62-5-1,1>>^ TODO aquele que crê que Jesus é o Cristo, é nascido de Deus; e todo aquele que ama ao que o gerou também ama ao que dele é nascido.

[[v62-5-2]]

^<<v62-5-2,2>>^ Nisto conhecemos que amamos os filhos de Deus, quando amamos a Deus e guardamos os seus mandamentos.

[[v62-5-3]]

^<<v62-5-3,3>>^ Porque esta é a caridade de Deus que guardemos os seus mandamentos; e os seus mandamentos não são pesados.

[[v62-5-4]]

^<<v62-5-4,4>>^ Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo, a nossa fé.

[[v62-5-5]]

^<<v62-5-5,5>>^ Quem é que vence o mundo, senão aquele que crê que Jesus é o Filho de Deus?

[[v62-5-6]]

^<<v62-5-6,6>>^ Este é aquele que veio por água e sangue, isto é, Jesus Cristo: não só por água, mas por água e por  sangue. E o Espírito é o que testifica, porque o Espírito é a verdade.

[[v62-5-7]]

^<<v62-5-7,7>>^ Porque três são os que testificam no céu: o Pai, a Palavra, e o Espírito Santo; e estes três são um.

[[v62-5-8]]

^<<v62-5-8,8>>^ E três são os que testificam na terra: o Espírito, e a água e o sangue; e estes três concordam num.

[[v62-5-9]]

^<<v62-5-9,9>>^ Se recebemos o testemunho dos homens, o testemunho de Deus é maior; porque o testemunho de Deus é este, que de seu Filho testificou.

[[v62-5-10]]

^<<v62-5-10,10>>^ Quem crê no Filho de Deus, em si mesmo tem o testemunho: quem a Deus não crê mentiroso o fez: porquanto não creu no testemunho que Deus de seu Filho deu.

[[v62-5-11]]

^<<v62-5-11,11>>^ E o testemunho é este: que Deus nos deu a vida eterna; e esta vida está em seu Filho.

[[v62-5-12]]

^<<v62-5-12,12>>^ Quem tem o Filho tem a vida: quem não tem o Filho de Deus não tem a vida.

[[v62-5-13]]

^<<v62-5-13,13>>^ Estas coisas vos escrevi, para que saibais que tendes a vida eterna, e para que creiais no nome do Filho de Deus.

[[v62-5-14]]

^<<v62-5-14,14>>^ E esta é a confiança que temos nele, que, se pedirmos alguma coisa, segundo a sua vontade, ele nos ouve.

[[v62-5-15]]

^<<v62-5-15,15>>^ E, se sabemos que nos ouve em tudo o que pedimos, sabemos que alcançamos as petições que lhe fizemos.

[[v62-5-16]]

^<<v62-5-16,16>>^ Se alguém vir pecar seu irmão pecado que  não é para morte, orará, e Deus dará a vida àqueles que não pecarem para morte. Há pecado para morte, e por esse não digo que ore.

[[v62-5-17]]

^<<v62-5-17,17>>^ Toda a iniquidade é pecado: e há pecado que  não é  para morte.

[[v62-5-18]]

^<<v62-5-18,18>>^ Sabemos que todo aquele que é nascido de Deus não peca; mas o que de Deus é gerado conserva-se a si mesmo, e o maligno não lhe toca.

[[v62-5-19]]

^<<v62-5-19,19>>^ Sabemos que somos de Deus, e que todo o mundo está no maligno.

[[v62-5-20]]

^<<v62-5-20,20>>^ E sabemos que já  o Filho de Deus é vindo, e nos deu entendimento para conhecermos o que é verdadeiro; e no que é verdadeiro estamos, isto é , em seu Filho Jesus Cristo. Este é o verdadeiro Deus e a vida eterna.

[[v62-5-21]]

^<<v62-5-21,21>>^ Filhinhos, guardai-vos dos ídolos. Amém.

'''

xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[&#60; Capítulo Anterior] | <<v62-5-0,Topo>> | xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[Próximo Capítulo &#62;]