include::./index.adoc[]

[[v16-1-0]]
=== Neemias, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v16-1-1]]

^<<v16-1-1,1>>^ AS palavras de Neemias, filho de Hacalias. E sucedeu no mês de quisleu, no ano vigésimo, estando eu em Susã, a fortaleza,

[[v16-1-2]]

^<<v16-1-2,2>>^ Que veio Hanani, um de meus irmãos, ele e alguns de Judá; e perguntei-lhes pelos judeus que escaparam, e que restaram do cativeiro, e acerca de Jerusalém.

[[v16-1-3]]

^<<v16-1-3,3>>^ E disseram-me: Os restantes, que restaram do cativeiro, lá na província estão  em grande miséria e desprezo, e o muro de Jerusalém fendido, e as suas portas queimadas a fogo.

[[v16-1-4]]

^<<v16-1-4,4>>^ E sucedeu que, ouvindo eu estas palavras, assentei-me e chorei, e lamentei por alguns  dias; e estive jejuando e orando perante o Deus dos céus.

[[v16-1-5]]

^<<v16-1-5,5>>^ E disse: Ah! Senhor, Deus dos céus, Deus grande e terrível! que guardas o concerto e a benignidade para com aqueles que te amam e guardam os teus mandamentos;

[[v16-1-6]]

^<<v16-1-6,6>>^ Estejam pois atentos os teus ouvidos, e os teus olhos abertos, para ouvires a oração do teu servo, que eu hoje faço perante ti, de dia e de noite, pelos filhos de Israel, teus servos: e faço confissão pelos pecados dos filhos de Israel, que pecamos contra ti; também eu e a casa de meu pai pecamos.

[[v16-1-7]]

^<<v16-1-7,7>>^ De todo nos corrompemos contra ti, e não guardamos os mandamentos, nem os estatutos, nem os juízos, que ordenaste a Moisés teu servo.

[[v16-1-8]]

^<<v16-1-8,8>>^ Lembra-te, pois, da palavra que ordenaste a Moisés teu servo, dizendo: Vós transgredireis, e eu vos espalharei entre os povos.

[[v16-1-9]]

^<<v16-1-9,9>>^ E vós vos convertereis a mim, e guardareis os meus mandamentos, e os fareis: então, ainda que os vossos rejeitados estejam no cabo do céu, de lá os ajuntarei e os trarei ao lugar que tenho escolhido para ali fazer habitar o meu nome.

[[v16-1-10]]

^<<v16-1-10,10>>^ Estes ainda são  teus servos e o teu povo que resgataste com a tua grande força e com a tua forte mão.

[[v16-1-11]]

^<<v16-1-11,11>>^ Ah! Senhor, estejam pois, atentos os teus ouvidos à oração do teu servo, e à oração dos teus servos que desejam temer o teu nome; e faze prosperar hoje o teu servo, e dá-lhe graça perante este homem. Então era eu copeiro do rei.

'''

xref:015-esdras/015-esdras-010.adoc#v15-10-0[&#60; Capítulo Anterior] | <<v16-1-0,Topo>> | xref:016-neemias/016-neemias-002.adoc#v16-2-0[Próximo Capítulo &#62;]