include::./index.adoc[]

[[v16-13-0]]
=== Neemias, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v16-13-1]]

^<<v16-13-1,1>>^ NAQUELE dia leu-se no livro de Moisés, aos ouvidos do povo; e achou-se escrito nele que os amonitas e os moabitas não entrassem jamais na congregação de Deus,

[[v16-13-2]]

^<<v16-13-2,2>>^ Porquanto não tinham saído ao encontro dos filhos de Israel com pão e água; antes assalariaram contra eles a Balaão para os amaldiçoar; ainda que o nosso Deus converteu a maldição em bênção.

[[v16-13-3]]

^<<v16-13-3,3>>^ Sucedeu pois que, ouvindo eles esta lei, apartaram de Israel, toda a mistura.

[[v16-13-4]]

^<<v16-13-4,4>>^ Ora antes disto, Eliasibe, sacerdote, que presidia sobre a câmara da casa do nosso Deus, se tinha  aparentado com Tobias;

[[v16-13-5]]

^<<v16-13-5,5>>^ E fizera-lhe uma câmara grande, onde dantes se metiam as ofertas de manjares, o incenso, e os vasos, e os dízimos do grão, do mosto, e do azeite, que se ordenaram para os levitas, e cantores, e porteiros, como também a oferta alçada para os sacerdotes.

[[v16-13-6]]

^<<v16-13-6,6>>^ Mas durante tudo isto não estava eu em Jerusalém; porque no ano trinta e dois de Artaxerxes, rei de Babilônia, vim eu ter com o rei; mas ao cabo de alguns  dias tornei  a alcançar licença do rei.

[[v16-13-7]]

^<<v16-13-7,7>>^ E vim a Jerusalém, e compreendi o mal que Eliasibe fizera para beneficiar  a Tobias, fazendo-lhe uma câmara nos pátios da casa de Deus,

[[v16-13-8]]

^<<v16-13-8,8>>^ O que muito me desagradou; de sorte que lancei todos os móveis da casa de Tobias fora da câmara.

[[v16-13-9]]

^<<v16-13-9,9>>^ E, ordenando-o eu purificaram as câmaras; e tornei a trazer ali os vasos da casa de Deus, com as ofertas de manjares, e o incenso.

[[v16-13-10]]

^<<v16-13-10,10>>^ Também entendi que o quinhão dos levitas se lhes  não dava; de maneira que os levitas e os cantores, que faziam a obra, tinham fugido cada um para a sua terra.

[[v16-13-11]]

^<<v16-13-11,11>>^ Então contendi com os magistrados, e disse: Por que se desamparou a casa de Deus? Porém eu os ajuntei, e os restaurei no seu posto.

[[v16-13-12]]

^<<v16-13-12,12>>^ Então todo o Judá trouxe os dízimos do grão, e do mosto, e do azeite aos celeiros.

[[v16-13-13]]

^<<v16-13-13,13>>^ E por tesoureiros pus sobre os celeiros a Selemias, o sacerdote, e a Zadoque, o escrivão e a Pedaías, dentre os levitas; e com eles Hanã, filho de Zacur, o filho de Matanias; porque se tinham achado fiéis; e se lhes encarregou a eles  a distribuição para seus irmãos.

[[v16-13-14]]

^<<v16-13-14,14>>^ (Por isto, Deus meu, lembra-te de mim; e não risques as beneficências que eu fiz à casa de meu Deus e às suas guardas.)

[[v16-13-15]]

^<<v16-13-15,15>>^ Naqueles dias vi em Judá os que pisavam lagares ao sábado e traziam feixes que carregavam sobre os  jumentos; como também vinho, uvas e figos, e toda a casta de  cargas, que traziam a Jerusalém no dia de sábado; e protestei contra eles  no dia em que vendiam mantimentos.

[[v16-13-16]]

^<<v16-13-16,16>>^ Também tírios habitavam dentro, que traziam peixe, e toda a mercadoria, que no sábado vendiam aos filhos de Judá e em Jerusalém.

[[v16-13-17]]

^<<v16-13-17,17>>^ E contendi com os nobres de Judá, e lhes disse: Que mal é  este que fazeis, profanando o dia de sábado?

[[v16-13-18]]

^<<v16-13-18,18>>^ Porventura  não fizeram vossos pais assim, e nosso Deus não trouxe todo este mal sobre nós e sobre esta cidade? E vós ainda mais acrescentais o ardor de sua  ira sobre Israel, profanando o sábado.

[[v16-13-19]]

^<<v16-13-19,19>>^ Sucedeu pois que, dando as portas de Jerusalém já sombra antes do sábado, ordenando-o eu, as portas se fecharam; e mandei que as não abrissem até passado o sábado; e pus às portas alguns  de meus moços, para que nenhuma carga entrasse no dia de sábado.

[[v16-13-20]]

^<<v16-13-20,20>>^ Então os negociantes e os vendedores de toda a mercadoria passaram a noite fora de Jerusalém, uma ou duas vezes.

[[v16-13-21]]

^<<v16-13-21,21>>^ Protestei pois contra eles, e lhes disse: Por que passais a noite defronte do muro? Se outra vez o fizerdes, hei de lançar mão de vós. Daquele tempo em diante não vieram no sábado.

[[v16-13-22]]

^<<v16-13-22,22>>^ Também disse aos levitas que se purificassem, e viessem guardar as portas, para santificar o sábado. (Nisto também, Deus meu, lembra-te de mim; e perdoa-me segundo a abundância da tua benignidade.)

[[v16-13-23]]

^<<v16-13-23,23>>^ Vi também naqueles dias judeus que tinham casado com mulheres asdoditas, amonitas, e  moabitas.

[[v16-13-24]]

^<<v16-13-24,24>>^ E seus filhos falavam meio asdodita, e não podiam falar judaico, senão segundo a língua de cada povo.

[[v16-13-25]]

^<<v16-13-25,25>>^ E contendi com eles, e os amaldiçoei, e espanquei alguns  deles, e lhes arranquei os cabelos, e os fiz jurar por Deus, dizendo : Não dareis mais vossas filhas a seus filhos, e não tomareis mais suas filhas, nem  para vossos filhos nem para vós mesmos.

[[v16-13-26]]

^<<v16-13-26,26>>^ Porventura  não pecou nisto Salomão, rei de Israel, não havendo entre muitas gentes rei semelhante a ele, e sendo amado de seu Deus, e pondo-o Deus rei sobre todo o Israel? E contudo  as mulheres estranhas o fizeram pecar.

[[v16-13-27]]

^<<v16-13-27,27>>^ E dar-vos-íamos nós  ouvidos, para fazermos todo este grande mal, prevaricando contra o nosso Deus, casando com mulheres estranhas?

[[v16-13-28]]

^<<v16-13-28,28>>^ Também um  dos filhos de Joiada, filho de Eliasibe, o sumo sacerdote, era genro de Sambalate, o horonita, pelo que o afugentei de mim.

[[v16-13-29]]

^<<v16-13-29,29>>^ Lembra-te deles, Deus meu, pois contaminaram o sacerdócio, como também o concerto do sacerdócio e dos levitas.

[[v16-13-30]]

^<<v16-13-30,30>>^ Assim os alimpei de todos os estranhos, e designei os cargos dos sacerdotes e dos levitas, cada um na sua obra;

[[v16-13-31]]

^<<v16-13-31,31>>^ Como também para as ofertas da lenha em tempos determinados, e para as primícias. Lembra-te de mim, Deus meu, para bem.

'''

xref:016-neemias/016-neemias-012.adoc#v16-12-0[&#60; Capítulo Anterior] | <<v16-13-0,Topo>> | xref:017-ester/017-ester-001.adoc#v17-1-0[Próximo Capítulo &#62;]