include::./index.adoc[]

[[v16-4-0]]
=== Neemias, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v16-4-1]]

^<<v16-4-1,1>>^ E SUCEDEU que, ouvindo Sambalate que edificávamos o muro, ardeu em ira, e se indignou muito; e escarneceu dos judeus.

[[v16-4-2]]

^<<v16-4-2,2>>^ E falou na presença de seus irmãos, e do exército de Samaria, e disse: Que fazem estes fracos judeus? Permitir-se-lhes-á isto? Sacrificarão? Acabá-lo-ão num só  dia? Vivificarão dos montões do pó as pedras que foram queimadas?

[[v16-4-3]]

^<<v16-4-3,3>>^ E estava com ele Tobias, o amonita, e disse: Ainda que edifiquem, vindo uma raposa derrubará facilmente o seu muro de pedra.

[[v16-4-4]]

^<<v16-4-4,4>>^ Ouve, ó nosso Deus, que somos tão desprezados, e caia o seu opróbrio sobre a sua cabeça, e faze com que sejam um despojo, numa terra de cativeiro.

[[v16-4-5]]

^<<v16-4-5,5>>^ E não cubras a sua iniquidade, e não se risque diante de ti o seu pecado, pois que te  irritaram defronte dos edificadores.

[[v16-4-6]]

^<<v16-4-6,6>>^ Assim edificamos o muro, e todo o muro se cerrou até sua metade: porque o coração do povo se inclinava a trabalhar.

[[v16-4-7]]

^<<v16-4-7,7>>^ E sucedeu que, ouvindo Sambalate e Tobias, e os arábios, e os amonitas, e os asdoditas, que tanto  ia crescendo a reparação dos muros de Jerusalém que já as roturas se começavam a tapar, iraram-se sobremodo.

[[v16-4-8]]

^<<v16-4-8,8>>^ E ligaram-se entre si todos, para virem guerrear Jerusalém, e para os desviarem do seu intento.

[[v16-4-9]]

^<<v16-4-9,9>>^ Porém nós oramos ao nosso Deus, e pusemos uma guarda contra eles, de dia e de noite, por causa deles.

[[v16-4-10]]

^<<v16-4-10,10>>^ Então disse Judá: já desfaleceram as forças dos acarretadores, e o pó é  muito e nós não poderemos edificar o muro.

[[v16-4-11]]

^<<v16-4-11,11>>^ Disseram, porém, os nossos inimigos: Nada saberão disto, nem verão, até que entremos no meio deles, e os matemos; assim faremos cessar a obra.

[[v16-4-12]]

^<<v16-4-12,12>>^ E sucedeu que, vindo os judeus que habitavam entre eles, dez vezes nos disseram, de todos os lugares, que tornavam a nós.

[[v16-4-13]]

^<<v16-4-13,13>>^ Pelo que pus guardas  nos lugares baixos por detrás do muro e  nos altos: e pus ao povo pelas suas  famílias com as suas espadas, com  as suas lanças, e com  os seus arcos.

[[v16-4-14]]

^<<v16-4-14,14>>^ E olhei, e levantei-me, e disse aos nobres, e aos magistrados, e ao resto do povo: Não os temais: lembrai-vos do Senhor, grande e terrível, e pelejai pelos vossos irmãos, vossos filhos, vossas mulheres e vossas casas.

[[v16-4-15]]

^<<v16-4-15,15>>^ E sucedeu que, ouvindo os nossos inimigos que já o sabíamos, e que Deus tinha dissipado o conselho deles, todos voltamos ao muro, cada um à sua obra.

[[v16-4-16]]

^<<v16-4-16,16>>^ E sucedeu que desde aquele dia metade dos meus moços trabalhava na obra, e a outra metade deles tinha as lanças, os escudos, os arcos, e as couraças; e os chefes estavam  por detrás de toda a casa de Judá.

[[v16-4-17]]

^<<v16-4-17,17>>^ Os que edificavam o muro, e os que traziam as cargas, e  os que carregavam, cada um  com uma mão fazia a obra e na outra tinha as armas.

[[v16-4-18]]

^<<v16-4-18,18>>^ E os edificadores cada um trazia a sua espada cingida aos lombos, e edificavam; e o que tocava a trombeta estava  junto comigo.

[[v16-4-19]]

^<<v16-4-19,19>>^ E disse eu aos nobres, e aos magistrados, e ao resto do povo: Grande e extensa é  a obra, e nós estamos apartados do muro, longe uns dos outros.

[[v16-4-20]]

^<<v16-4-20,20>>^ No lugar onde ouvirdes o som da buzina ali vos ajuntareis conosco; o nosso Deus pelejará por nós.

[[v16-4-21]]

^<<v16-4-21,21>>^ Assim trabalhávamos na obra; e metade deles tinha as lanças desde a subida da alva até ao sair das estrelas.

[[v16-4-22]]

^<<v16-4-22,22>>^ Também naquele tempo disse ao povo: Cada um com o seu moço fique em Jerusalém, para que de noite nos sirvam de guarda, e de dia na obra.

[[v16-4-23]]

^<<v16-4-23,23>>^ E nem eu, nem meus irmãos, nem meus moços, nem os homens da guarda que me seguiam largávamos os nossos vestidos; cada um ia com suas armas à água.

'''

xref:016-neemias/016-neemias-003.adoc#v16-3-0[&#60; Capítulo Anterior] | <<v16-4-0,Topo>> | xref:016-neemias/016-neemias-005.adoc#v16-5-0[Próximo Capítulo &#62;]