include::./index.adoc[]

[[v16-6-0]]
=== Neemias, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v16-6-1]]

^<<v16-6-1,1>>^ SUCEDEU mais que, ouvindo Sambalate, Tobias, Gesém, o arábio, e o resto dos nossos inimigos que eu tinha edificado o muro; e que nele já  não havia brecha alguma; ainda que até este tempo não tinha posto as portas nos portais;

[[v16-6-2]]

^<<v16-6-2,2>>^ Sambalate e Gesém enviaram a dizer: Vem, e congreguemo-nos juntamente nas aldeias, no vale de Ono. Porém intentavam fazer-me mal.

[[v16-6-3]]

^<<v16-6-3,3>>^ E enviei-lhes mensageiros a dizer: Estou fazendo uma grande obra, de modo que não poderei descer: por que cessaria esta obra, enquanto eu a deixasse e fosse ter convosco?

[[v16-6-4]]

^<<v16-6-4,4>>^ E da mesma maneira enviaram a mim quatro vezes; e da mesma maneira lhes respondi.

[[v16-6-5]]

^<<v16-6-5,5>>^ Então Sambalate da mesma maneira pela quinta vez me enviou o seu moço com uma carta aberta na sua mão;

[[v16-6-6]]

^<<v16-6-6,6>>^ E na qual estava  escrito: Entre as gentes se ouviu, e Gusmu diz, que tu e os judeus intentais revoltar-vos, pelo que edificais o muro; e que tu te farás rei deles segundo estas palavras;

[[v16-6-7]]

^<<v16-6-7,7>>^ E que puseste profetas, para pregarem de ti em Jerusalém, dizendo: Este é  rei em Judá. Ora o rei o ouvirá, segundo estas palavras; vem pois agora e consultemos juntamente.

[[v16-6-8]]

^<<v16-6-8,8>>^ Porém eu enviei a dizer-lhe: De tudo o que dizes cousa nenhuma sucedeu; mas tu do teu coração o inventas.

[[v16-6-9]]

^<<v16-6-9,9>>^ Porque todos eles nos procuravam atemorizar, dizendo: As suas mãos largarão a obra, e não se efetuará. Agora pois, ó Deus , esforça as minhas mãos.

[[v16-6-10]]

^<<v16-6-10,10>>^ E, entrando eu em casa de Semaías, filho de Delaías, o filho de Meetabel (que estava encerrado), disse ele: Vamos juntamente à casa de Deus, ao meio do templo, e fechemos as portas do templo; porque virão matar-te: sim, de noite virão matar-te.

[[v16-6-11]]

^<<v16-6-11,11>>^ Porém eu disse: Um  homem como eu fugiria? e quem há , como eu, que entre no templo e viva? de maneira nenhuma entrarei.

[[v16-6-12]]

^<<v16-6-12,12>>^ E conheci que eis que não era  Deus quem o enviara; mas esta profecia falou contra mim, porquanto Tobias e Sambalate o subornaram.

[[v16-6-13]]

^<<v16-6-13,13>>^ Para isto o subornaram, para me atemorizar, e para que eu assim fizesse, e pecasse, para que tivessem alguma  causa a fim de me infamarem, e assim me vituperarem.

[[v16-6-14]]

^<<v16-6-14,14>>^ Lembra-te, meu Deus, de Tobias e de Sambalate, conforme a estas suas obras, e também da profetisa Noadia, e dos mais profetas que procuraram atemorizar-me.

[[v16-6-15]]

^<<v16-6-15,15>>^ Acabou-se pois o muro aos vinte e cinco de Elul, em cinquenta e dois dias.

[[v16-6-16]]

^<<v16-6-16,16>>^ E sucedeu que, ouvindo- o  todos os nossos inimigos, temeram, todos os gentios que havia  em roda de nós, e abateram-se muito em seus próprios  olhos; porque reconheceram que o nosso Deus fizera esta obra.

[[v16-6-17]]

^<<v16-6-17,17>>^ Também naqueles dias alguns  nobres de Judá escreveram muitas cartas, que iam para Tobias: e as cartas  de Tobias vinham para eles.

[[v16-6-18]]

^<<v16-6-18,18>>^ Porque muitos em Judá se lhe ajuramentaram, porque era  genro de Secanias, filho de Ará; e seu filho Joanã tomara a filha de Mesulão, filho de Berequias.

[[v16-6-19]]

^<<v16-6-19,19>>^ Também as suas bondades contavam perante mim, e as minhas palavras lhe levavam a ele; portanto  Tobias escrevia cartas para me atemorizar.

'''

xref:016-neemias/016-neemias-005.adoc#v16-5-0[&#60; Capítulo Anterior] | <<v16-6-0,Topo>> | xref:016-neemias/016-neemias-007.adoc#v16-7-0[Próximo Capítulo &#62;]