include::./index.adoc[]

[[v16-5-0]]
=== Neemias, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v16-5-1]]

^<<v16-5-1,1>>^ FOI porém grande o clamor do povo e de suas mulheres, contra os judeus, seus irmãos.

[[v16-5-2]]

^<<v16-5-2,2>>^ Porque havia quem dizia: Com  nossos filhos, e nossas filhas, nós somos  muitos; pelo que tomemos trigo, para que comamos e vivamos.

[[v16-5-3]]

^<<v16-5-3,3>>^ Também havia quem dizia: As nossas terras, as nossas vinhas, e as nossas casas empenhamos, para tomarmos trigo nesta fome.

[[v16-5-4]]

^<<v16-5-4,4>>^ Também havia quem dizia: Tomamos dinheiro emprestado até para o tributo do rei, sobre  as nossas terras e as nossas vinhas.

[[v16-5-5]]

^<<v16-5-5,5>>^ Agora, pois, a nossa carne é como a carne de nossos irmãos, e  nossos filhos como seus filhos; e eis que sujeitamos nossos filhos e nossas filhas para serem  servos: e até algumas  de nossas filhas são tão  sujeitas que já  não estão no poder de nossas mãos; e outros têm as nossas terras e as nossas vinhas.

[[v16-5-6]]

^<<v16-5-6,6>>^ Ouvindo eu, pois, o seu clamor, e estas palavras, muito me enfadei.

[[v16-5-7]]

^<<v16-5-7,7>>^ E considerei comigo mesmo no meu coração; depois pelejei com os nobres e com os magistrados, e disse-lhes: Usura tomais cada um de seu irmão. E ajuntei contra eles um  grande ajuntamento.

[[v16-5-8]]

^<<v16-5-8,8>>^ E disse-lhes: Nós resgatamos os judeus, nossos irmãos, que foram vendidos às gentes, segundo nossas posses; e vós outra vez venderíeis a vossos irmãos, ou vender-se-iam a nós? Então se calaram, e não acharam que responder.

[[v16-5-9]]

^<<v16-5-9,9>>^ Disse mais: Não é  bom o que fazeis: Porventura  não devíeis andar no temor do nosso Deus, por causa do opróbrio dos gentios, os nossos inimigos?

[[v16-5-10]]

^<<v16-5-10,10>>^ Também eu, meus irmãos e meus moços, a juro lhes temos dado dinheiro e trigo. Deixemos este ganho.

[[v16-5-11]]

^<<v16-5-11,11>>^ Restituí-lhes hoje, vos peço, as suas terras, as suas vinhas, os seus olivais, e as suas casas; como também o centésimo do dinheiro, do trigo, do mosto, e do azeite, que vós exigis deles.

[[v16-5-12]]

^<<v16-5-12,12>>^ Então disseram: Restituir- lho- emos, e nada procuraremos deles; faremos assim como dizes. Então chamei os sacerdotes, e os fiz jurar que fariam conforme a esta palavra.

[[v16-5-13]]

^<<v16-5-13,13>>^ Também o meu regaço sacudi, e disse: Assim sacuda Deus todo o homem da sua casa e do seu trabalho que não cumprir esta palavra, e assim seja sacudido e vazio. E toda a congregação disse: Amém! E louvaram ao Senhor; e o povo fez conforme a esta palavra.

[[v16-5-14]]

^<<v16-5-14,14>>^ Também desde o dia em que fui nomeado seu governador na terra de Judá, desde o ano vinte, até ao ano trinta e dois do rei Artaxerxes, doze anos, nem eu nem meus irmãos comemos o pão do governador.

[[v16-5-15]]

^<<v16-5-15,15>>^ Mas os primeiros governadores, que foram  antes de mim, oprimiram o povo, e tomaram-lhe pão e vinho, e  além disso, quarenta siclos de prata; ainda também os seus moços dominavam sobre o povo; porém eu assim não fiz, por causa do temor de Deus.

[[v16-5-16]]

^<<v16-5-16,16>>^ Antes também na obra deste muro fiz reparação, e terra nenhuma compramos: e todos os meus moços se ajuntaram ali à obra.

[[v16-5-17]]

^<<v16-5-17,17>>^ Também cento e cinquenta homens dos judeus e dos magistrados, e os que vinham a nós, dentre as gentes, que estão  à roda de nós, se punham à minha mesa.

[[v16-5-18]]

^<<v16-5-18,18>>^ E o que se preparava para cada dia era  um boi e  seis ovelhas escolhidas; também aves se me preparavam, e de dez em dez dias de todo o vinho muitíssimo: e nem por isso exigi o pão do governador, porquanto a servidão deste povo era grande.

[[v16-5-19]]

^<<v16-5-19,19>>^ Lembra-te de mim para bem, ó meu Deus, e de  tudo quanto fiz a este povo.

'''

xref:016-neemias/016-neemias-004.adoc#v16-4-0[&#60; Capítulo Anterior] | <<v16-5-0,Topo>> | xref:016-neemias/016-neemias-006.adoc#v16-6-0[Próximo Capítulo &#62;]