include::./index.adoc[]

[[v16-11-0]]
=== Neemias, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v16-11-1]]

^<<v16-11-1,1>>^ E OS príncipes do povo habitaram em Jerusalém, mas o resto do povo lançou sortes, para tirar um de dez, que habitasse na santa cidade de Jerusalém, e as nove partes nas outras  cidades.

[[v16-11-2]]

^<<v16-11-2,2>>^ E o povo bendisse a todos os homens que voluntariamente se ofereciam para habitar em Jerusalém.

[[v16-11-3]]

^<<v16-11-3,3>>^ E estes são  os chefes da província, que habitaram em Jerusalém (porém nas cidades de Judá habitou cada um na sua possessão, nas suas cidades a saber , Israel, os sacerdotes, e os levitas e os netineus, e os filhos dos servos de Salomão):

[[v16-11-4]]

^<<v16-11-4,4>>^ Habitaram pois em Jerusalém alguns  dos filhos de Judá e dos filhos de Benjamim: Dos filhos de Judá, Ataias, filho de Uzias, filho de Zacarias, filho de Amarias, filho de Sefatias, filho de Maalalel, dos filhos de Perez;

[[v16-11-5]]

^<<v16-11-5,5>>^ E Maaseias filho de Baruque, filho de Colhoze, filho de Hazaías, filho de Adaías, filho de Joiaribe, filho de Zacarias, filho de Siloni.

[[v16-11-6]]

^<<v16-11-6,6>>^ Todos os filhos de Perez que habitaram em Jerusalém, foram  quatrocentos e  sessenta e oito homens valentes.

[[v16-11-7]]

^<<v16-11-7,7>>^ E estes são  os filhos de Benjamim: Salu, filho de Mesulão, filho de Joede, filho de Pedaías, filho de Colaias, filho de Maaseias, filho de Itiel, filho de Jesaías.

[[v16-11-8]]

^<<v16-11-8,8>>^ E depois dele Gabai, Salai: novecentos e  vinte e oito.

[[v16-11-9]]

^<<v16-11-9,9>>^ E Joel, filho de Zicri, superintendente sobre eles; e Judá, filho de Senua, segundo sobre a cidade.

[[v16-11-10]]

^<<v16-11-10,10>>^ Dos sacerdotes: Jedaías, filho de Joaribe, Jaquim.

[[v16-11-11]]

^<<v16-11-11,11>>^ Seraías, filho de Hilquias, filho de Mesulão, filho de Zadoque, filho de Meraiote, filho de Aitube, maioral da casa de Deus.

[[v16-11-12]]

^<<v16-11-12,12>>^ E seus irmãos, que faziam a obra da casa, oitocentos e  vinte e dois; e Adaías, filho de Jeroão, filho de Pelalias, filho de Ansi, filho de Zacarias, filho de Pasur, filho de Malquias.

[[v16-11-13]]

^<<v16-11-13,13>>^ E seus irmãos, cabeças dos pais, duzentos e  quarenta e dois; e Amasai, filho de Azareel, filho de Aazai, filho de Mesilemote, filho de Imer.

[[v16-11-14]]

^<<v16-11-14,14>>^ E os irmãos deles, varões valentes, cento e  vinte e oito, e superintendente sobre eles Zabdiel, filho de Gedolim.

[[v16-11-15]]

^<<v16-11-15,15>>^ E dos levitas: Semaías, filho de Hassube, filho de Azricão, filho de Hasabias, filho de Buni;

[[v16-11-16]]

^<<v16-11-16,16>>^ E Sabetai, e Jozabade, dos cabeças dos levitas, presidiam  sobre a obra de fora da casa de Deus.

[[v16-11-17]]

^<<v16-11-17,17>>^ E Matanias, filho de Mica, filho de Zabdi, filho de Asafe, o chefe, que era quem  começava a dar graças na oração, e Bacbuquias, o segundo de seus irmãos; depois Abda, filho de Samua, filho de Galal, filho de Jedutum.

[[v16-11-18]]

^<<v16-11-18,18>>^ Todos os levitas na santa cidade foram  duzentos e  oitenta e quatro.

[[v16-11-19]]

^<<v16-11-19,19>>^ E os porteiros, Acube, Talmom, com seus irmãos, os guardas das portas, cento e  setenta e dois.

[[v16-11-20]]

^<<v16-11-20,20>>^ E o resto de Israel dos sacerdotes e  levitas, esteve  em todas as cidades de Judá, cada um na sua herdade.

[[v16-11-21]]

^<<v16-11-21,21>>^ E os netineus habitaram em Ofel; e Zia e Gispa presidiam sobre os netineus.

[[v16-11-22]]

^<<v16-11-22,22>>^ E o superintendente dos levitas em Jerusalém foi  Uzi, filho de Bani, filho de Hasabias, filho de Matanias, filho de Mica, dos filhos de Asafe, os cantores, ao serviço da casa de Deus.

[[v16-11-23]]

^<<v16-11-23,23>>^ Porque havia um  mandado do rei acerca deles, a saber, uma  certa porção para os cantores, cada qual  no seu  dia.

[[v16-11-24]]

^<<v16-11-24,24>>^ E Petaías, filho de Mesezabel, dos filhos de Zerá filho de Judá, estava  à mão do rei, em todos os negócios do povo.

[[v16-11-25]]

^<<v16-11-25,25>>^ E quanto às aldeias, com as suas terras, alguns  dos filhos de Judá habitaram em Quiriate-Arba, e nos lugares da sua jurisdição; e em Dibom, e nos lugares da sua jurisdição; e em Jecabsel, e nas suas aldeias.

[[v16-11-26]]

^<<v16-11-26,26>>^ E em Jesua, e em Molada, e em Bete-Pelete.

[[v16-11-27]]

^<<v16-11-27,27>>^ E em Hasarsual, e em Berseba, e nos lugares da sua jurisdição;

[[v16-11-28]]

^<<v16-11-28,28>>^ E em Siclague e em Mecona, e nos lugares da sua jurisdição;

[[v16-11-29]]

^<<v16-11-29,29>>^ E em En-Rimom, e em Zorá, e em Jarmute;

[[v16-11-30]]

^<<v16-11-30,30>>^ Em Zanoa, Adulão, e nas suas aldeias; em Laquis, e nas suas terras; em Azaca, e nos  lugares da sua jurisdição. E acamparam-se desde Berseba até ao vale de Hinom.

[[v16-11-31]]

^<<v16-11-31,31>>^ E os filhos de Benjamim, de Geba, habitaram em  Micmas e Aía, e Betel, e nos lugares da sua jurisdição;

[[v16-11-32]]

^<<v16-11-32,32>>^ E em  Anatote, em Nobe, em Anania,

[[v16-11-33]]

^<<v16-11-33,33>>^ Em Hasor, em Ramá, em Gitaim,

[[v16-11-34]]

^<<v16-11-34,34>>^ Em Hadide, em Zeboim, em Nebalate,

[[v16-11-35]]

^<<v16-11-35,35>>^ Em Lode, e em Ono, no vale dos artífices.

[[v16-11-36]]

^<<v16-11-36,36>>^ E alguns  dos levitas habitaram nos repartimentos de Judá e  de Benjamim.

'''

xref:016-neemias/016-neemias-010.adoc#v16-10-0[&#60; Capítulo Anterior] | <<v16-11-0,Topo>> | xref:016-neemias/016-neemias-012.adoc#v16-12-0[Próximo Capítulo &#62;]