include::./index.adoc[]

[[v4-24-0]]
=== Números, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-24-1]]

^<<v4-24-1,1>>^ VENDO Balaão que bem parecia aos olhos do Senhor que abençoasse a Israel, não foi esta vez como dantes ao encontro dos encantamentos: mas pôs o seu rosto para o deserto.

[[v4-24-2]]

^<<v4-24-2,2>>^ E, levantando Balaão os seus olhos, e vendo a Israel que habitava segundo as suas tribos, veio sobre ele o Espírito de Deus.

[[v4-24-3]]

^<<v4-24-3,3>>^ E alçou a sua parábola, e disse: Fala Balaão, filho de Beor, e fala o homem de olhos abertos;

[[v4-24-4]]

^<<v4-24-4,4>>^ Fala aquele que ouviu os ditos de Deus, o que vê a visão do Todo-poderoso, caindo em êxtase  e de olhos abertos:

[[v4-24-5]]

^<<v4-24-5,5>>^ Que boas são as tuas tendas, ó Jacó! as tuas moradas, ó Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ Como ribeiros se estendem, como jardins ao pé dos rios: como árvores de sândalo o Senhor os plantou, como cedros junto às águas.

[[v4-24-7]]

^<<v4-24-7,7>>^ De seus baldes manarão águas, e a sua semente estará  em muitas águas: e o seu rei se exalçará mais do que Agague, e o seu reino será levantado.

[[v4-24-8]]

^<<v4-24-8,8>>^ Deus o tirou do Egito; as suas forças são  como as do unicórnio: consumirá as gentes, seus inimigos, e quebrará seus ossos, e com as suas setas os atravessará.

[[v4-24-9]]

^<<v4-24-9,9>>^ Encurvou-se, deitou-se como leão, e como leoa: quem o despertará? benditos os que te abençoarem, e malditos os que te amaldiçoarem.

[[v4-24-10]]

^<<v4-24-10,10>>^ Então a ira de Balaque se acendeu contra Balaão, e bateu ele as suas palmas: e Balaque disse a Balaão. Para amaldiçoar os meus inimigos te tenho chamado; porém agora já três vezes os  abençoaste inteiramente.

[[v4-24-11]]

^<<v4-24-11,11>>^ Agora pois foge para o teu lugar: eu tinha dito que  te honraria grandemente; mas eis que o Senhor te privou desta honra.

[[v4-24-12]]

^<<v4-24-12,12>>^ Então Balaão disse a Balaque: Não falei eu  também aos teus mensageiros, que me enviaste, dizendo:

[[v4-24-13]]

^<<v4-24-13,13>>^ Ainda que Balaque me desse a sua casa cheia de prata e ouro, não posso traspassar o mandado do Senhor, fazendo bem ou mal de meu próprio  coração: o que o Senhor falar, isso falarei eu.

[[v4-24-14]]

^<<v4-24-14,14>>^ Agora pois eis que me vou ao meu povo: vem, avisar-te-ei do que este povo fará ao teu povo nos últimos dias.

[[v4-24-15]]

^<<v4-24-15,15>>^ Então alçou a sua parábola, e disse: Fala Balaão, filho de Beor, e fala o homem de olhos abertos;

[[v4-24-16]]

^<<v4-24-16,16>>^ Fala aquele que ouviu os ditos de Deus, e o que sabe a ciência do Altíssimo: o que viu a visão do Todo-poderoso, caído em êxtase , e de olhos abertos.

[[v4-24-17]]

^<<v4-24-17,17>>^ Vê-lo-ei, mas não agora; contemplá-lo-ei, mas não de perto: uma estrela procederá de Jacó, e um cetro subirá de Israel, que ferirá os termos dos moabitas, e destruirá todos os filhos de Sete.

[[v4-24-18]]

^<<v4-24-18,18>>^ E Edom será uma possessão, e Seir também será uma possessão hereditária para os seus inimigos: pois Israel fará proezas.

[[v4-24-19]]

^<<v4-24-19,19>>^ E dominará um  de Jacó, e matará os que restam das cidades.

[[v4-24-20]]

^<<v4-24-20,20>>^ E vendo os amalequitas, alçou a sua parábola, e disse: Amaleque é  o primeiro das gentes: porém o seu fim será  para perdição.

[[v4-24-21]]

^<<v4-24-21,21>>^ E vendo os quenitas, alçou a sua parábola, e disse: Firme está  a tua habitação, e puseste o teu ninho na penha.

[[v4-24-22]]

^<<v4-24-22,22>>^ Todavia o quenita será consumido, até que Assur te leve por prisioneiro.

[[v4-24-23]]

^<<v4-24-23,23>>^ E, alçando ainda a sua parábola, disse: Ai, quem viverá, quando Deus fizer isto?

[[v4-24-24]]

^<<v4-24-24,24>>^ E as naus das costas de Quitim afligirão a Assur; também afligirão a Héber; e também ele será  para perdição.

[[v4-24-25]]

^<<v4-24-25,25>>^ Então Balaão levantou-se, e foi-se, e voltou ao seu lugar, e também Balaque se foi pelo seu caminho.

'''

xref:004-numeros/004-numeros-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numeros/004-numeros-025.adoc#v4-25-0[Próximo Capítulo &#62;]