include::./index.adoc[]

[[v4-10-0]]
=== Números, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-10-1]]

^<<v4-10-1,1>>^ FALOU mais o Senhor a Moisés, dizendo:

[[v4-10-2]]

^<<v4-10-2,2>>^ Faze duas trombetas de prata: de  obra batida as farás: e te serão para a convocação da congregação, e para a partida dos arraiais.

[[v4-10-3]]

^<<v4-10-3,3>>^ E, quando as tocarem ambas , então toda a congregação se congregará a ti à porta da tenda da congregação.

[[v4-10-4]]

^<<v4-10-4,4>>^ Mas, quando tocar uma só , então a ti se congregarão os príncipes, os cabeças dos milhares de Israel.

[[v4-10-5]]

^<<v4-10-5,5>>^ Quando, retinindo, as tocardes, então partirão os arraiais que alojados estão da banda do oriente.

[[v4-10-6]]

^<<v4-10-6,6>>^ Mas, quando a segunda vez, retinindo, as tocardes, então partirão os arraiais que se alojam da banda do sul: retinindo, as  tocarão para as suas partidas.

[[v4-10-7]]

^<<v4-10-7,7>>^ Porém, ajuntando a congregação, as  tocareis; mas sem retinir.

[[v4-10-8]]

^<<v4-10-8,8>>^ E os filhos de Aarão, sacerdotes, tocarão as trombetas: e a vós serão por estatuto perpétuo nas vossas gerações.

[[v4-10-9]]

^<<v4-10-9,9>>^ E, quando na vossa terra sairdes a pelejar contra o inimigo, que vos aperta, também tocareis as trombetas retinindo, e perante o Senhor vosso Deus haverá lembrança de vós, e sereis salvos de vossos inimigos.

[[v4-10-10]]

^<<v4-10-10,10>>^ Semelhantemente, no dia da vossa alegria, e nas vossas solenidades, e nos princípios dos vossos meses, também tocareis as trombetas sobre os vossos holocaustos, sobre os vossos sacrifícios pacíficos, e vos serão por lembrança perante vosso Deus: Eu sou  o Senhor vosso Deus.

[[v4-10-11]]

^<<v4-10-11,11>>^ E aconteceu, no ano segundo, no segundo mês, aos vinte do mês, que a nuvem se alçou de sobre o tabernáculo da congregação.

[[v4-10-12]]

^<<v4-10-12,12>>^ E os filhos de Israel partiram segundo as suas jornadas do deserto de Sinai: e a nuvem parou no deserto de Parã.

[[v4-10-13]]

^<<v4-10-13,13>>^ Assim partiram pela primeira vez segundo o dito do Senhor, pela mão de Moisés.

[[v4-10-14]]

^<<v4-10-14,14>>^ Porque primeiramente partiu a bandeira do arraial dos filhos de Judá segundo os seus exércitos: e sobre o seu exército estava  Naassom, filho de Aminadabe.

[[v4-10-15]]

^<<v4-10-15,15>>^ E sobre o exército da tribo dos filhos de Issacar, Natanael, filho de Suar.

[[v4-10-16]]

^<<v4-10-16,16>>^ E sobre o exército da tribo dos filhos de Zebulom, Eliabe, filho de Helom.

[[v4-10-17]]

^<<v4-10-17,17>>^ Então desarmaram o tabernáculo, e os filhos de Gérson e os filhos de Merari partiram, levando o tabernáculo.

[[v4-10-18]]

^<<v4-10-18,18>>^ Depois partiu a bandeira do arraial de Rúben segundo os seus exércitos: e sobre o seu exército estava  Elizur, filho de Sedeur.

[[v4-10-19]]

^<<v4-10-19,19>>^ E sobre o exército da tribo dos filhos de Simeão, Selumiel, filho de Surisadai.

[[v4-10-20]]

^<<v4-10-20,20>>^ E sobre o exército da tribo dos filhos de Gade, Eliasafe, filho de Deuel.

[[v4-10-21]]

^<<v4-10-21,21>>^ Então partiram os coatitas, levando o santuário; e os outros  levantaram o tabernáculo, entretanto que estes vinham.

[[v4-10-22]]

^<<v4-10-22,22>>^ Depois partiu a bandeira do arraial dos filhos de Efraim segundo os seus exércitos: e sobre o seu exército estava  Elisama, filho de Amiúde.

[[v4-10-23]]

^<<v4-10-23,23>>^ E sobre o exército da tribo dos filhos de Manassés, Gamaliel, filho de Pedazur.

[[v4-10-24]]

^<<v4-10-24,24>>^ E sobre o exército da tribo dos filhos de Benjamim, Abidã, filho de Gideôni.

[[v4-10-25]]

^<<v4-10-25,25>>^ Então partiu a bandeira do arraial dos filhos de Dã, fechando todos os arraiais segundo os seus exércitos: e sobre o seu exército estava  Aiezer, filho de Amisadai.

[[v4-10-26]]

^<<v4-10-26,26>>^ E sobre o exército da tribo dos filhos de Aser, Pagiel, filho de Ocrã.

[[v4-10-27]]

^<<v4-10-27,27>>^ E sobre o exército da tribo dos filhos de Naftali, Aíra, filho de Enã.

[[v4-10-28]]

^<<v4-10-28,28>>^ Estas eram  as partidas dos filhos de Israel segundo os seus exércitos, quando partiam.

[[v4-10-29]]

^<<v4-10-29,29>>^ Disse então Moisés a Hobabe, filho de Reuel, o midianita, sogro de Moisés: Nós caminhamos para aquele lugar, de que o Senhor disse: Vo-lo darei: vai conosco, e te faremos bem; porque o Senhor falou bem sobre Israel.

[[v4-10-30]]

^<<v4-10-30,30>>^ Porém ele lhe disse: Não irei; antes irei à minha terra e à minha parentela.

[[v4-10-31]]

^<<v4-10-31,31>>^ E ele disse: Ora não nos deixes: porque tu sabes que nós nos alojamos no deserto; de olhos nos servirás.

[[v4-10-32]]

^<<v4-10-32,32>>^ E será que, vindo tu conosco, e sucedendo o bem que o Senhor nos fizer, também nós te faremos bem.

[[v4-10-33]]

^<<v4-10-33,33>>^ Assim partiram do monte do Senhor caminho de três dias: e a arca do concerto do Senhor caminhou diante deles caminho de três dias, para lhes buscar lugar de descanso.

[[v4-10-34]]

^<<v4-10-34,34>>^ E a nuvem do Senhor ia sobre eles de dia, quando partiam do arraial.

[[v4-10-35]]

^<<v4-10-35,35>>^ Era pois que, partindo a arca, Moisés dizia: Levanta-te, Senhor, e dissipados sejam os teus inimigos, e fujam diante de ti os aborrecedores.

[[v4-10-36]]

^<<v4-10-36,36>>^ E, pousando ela, dizia: Volta, ó Senhor, para os muitos milhares de Israel.

'''

xref:004-numeros/004-numeros-009.adoc#v4-9-0[&#60; Capítulo Anterior] | <<v4-10-0,Topo>> | xref:004-numeros/004-numeros-011.adoc#v4-11-0[Próximo Capítulo &#62;]