include::./index.adoc[]

[[v4-13-0]]
=== Números, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-13-1]]

^<<v4-13-1,1>>^ E FALOU o Senhor a Moisés, dizendo:

[[v4-13-2]]

^<<v4-13-2,2>>^ Envia homens que espiem a terra de Canaã, que eu hei de dar aos filhos de Israel; de cada tribo de seus pais enviareis um homem, sendo  cada qual maioral entre eles.

[[v4-13-3]]

^<<v4-13-3,3>>^ E enviou-os Moisés do deserto de Parã, segundo o dito do Senhor; todos aqueles homens eram cabeças dos filhos de Israel.

[[v4-13-4]]

^<<v4-13-4,4>>^ E estes são  os seus nomes: Da tribo de Rúben, Sâmua, filho de Sacur;

[[v4-13-5]]

^<<v4-13-5,5>>^ Da tribo de Simeão, Safate, filho de Hori;

[[v4-13-6]]

^<<v4-13-6,6>>^ Da tribo de Judá, Calebe, filho de Jefoné;

[[v4-13-7]]

^<<v4-13-7,7>>^ Da tribo de Issacar, Jigeal, filho de José;

[[v4-13-8]]

^<<v4-13-8,8>>^ Da tribo de Efraim, Oseias, filho de Num;

[[v4-13-9]]

^<<v4-13-9,9>>^ Da tribo de Benjamim, Palti, filho de Rafu;

[[v4-13-10]]

^<<v4-13-10,10>>^ Da tribo de Zebulom, Gadiel, filho de Sodi;

[[v4-13-11]]

^<<v4-13-11,11>>^ Da tribo de José, pela tribo de Manassés, Gadi, filho de Susi;

[[v4-13-12]]

^<<v4-13-12,12>>^ Da tribo de Dã, Amiel, filho de Gemali;

[[v4-13-13]]

^<<v4-13-13,13>>^ Da tribo de Aser, Setur, filho de Micael;

[[v4-13-14]]

^<<v4-13-14,14>>^ Da tribo de Naftali, Nábi, filho de Vofsi;

[[v4-13-15]]

^<<v4-13-15,15>>^ Da tribo de Gade, Guel, filho de Maqui.

[[v4-13-16]]

^<<v4-13-16,16>>^ Estes são  os nomes dos homens que Moisés enviou a espiar aquela terra: e a Oseias, filho de Num, Moisés chamou Josué.

[[v4-13-17]]

^<<v4-13-17,17>>^ Enviou-os pois Moisés a espiar a terra de Canaã: e disse-lhes: Subi por aqui para a banda do sul, e subi à montanha:

[[v4-13-18]]

^<<v4-13-18,18>>^ E vede que terra é, e o povo que nela habita; se é  forte ou fraco; se pouco ou muito;

[[v4-13-19]]

^<<v4-13-19,19>>^ E qual é  a terra em que habita, se boa ou má: e quais são  as cidades em que habita, se em arraiais, se em fortalezas.

[[v4-13-20]]

^<<v4-13-20,20>>^ Também qual é a terra, se grossa ou magra: se nela há árvores, ou não: e esforçai-vos, e tomai do fruto da terra. E eram  aqueles dias os dias das primícias das uvas.

[[v4-13-21]]

^<<v4-13-21,21>>^ Assim subiram, e espiaram a terra desde o deserto de Zim, até Reobe, à entrada de Hamate.

[[v4-13-22]]

^<<v4-13-22,22>>^ E subiram para a banda do sul, e vieram até Hebrom; e estavam  ali Aimã, Sesai, e Talmai, filhos de Enaque: e Hebrom foi edificada sete anos antes de Zoã no Egito.

[[v4-13-23]]

^<<v4-13-23,23>>^ Depois vieram até ao vale de Escol, e dali cortaram um  ramo de vide com um cacho de uvas, o qual trouxeram dois homens  sobre uma verga: como também romãs e figos.

[[v4-13-24]]

^<<v4-13-24,24>>^ Chamaram àquele lugar o vale de Escol, por causa do cacho que dali cortaram os filhos de Israel.

[[v4-13-25]]

^<<v4-13-25,25>>^ Depois voltaram de espiar a terra, ao fim de quarenta dias.

[[v4-13-26]]

^<<v4-13-26,26>>^ E caminharam, e vieram a Moisés e a Aarão, e a toda a congregação dos filhos de Israel no deserto de Parã, a Cades, e, tornando, deram-lhes conta a eles, e a toda a congregação, e mostraram-lhes o fruto da terra.

[[v4-13-27]]

^<<v4-13-27,27>>^ E contaram-lhe, e disseram: Fomos à terra a que nos enviaste; e verdadeiramente mana leite e mel, e este é o fruto.

[[v4-13-28]]

^<<v4-13-28,28>>^ O povo porém que habita nessa terra é poderoso, e as cidades fortes e mui grandes; e também ali vimos os filhos de Enaque.

[[v4-13-29]]

^<<v4-13-29,29>>^ Os amalequitas habitam na terra do sul; e os heteus, e os jebuseus, e os amorreus habitam na montanha: e os cananeus habitam ao pé do mar, e pela ribeira do Jordão.

[[v4-13-30]]

^<<v4-13-30,30>>^ Então Calebe fez calar o povo perante Moisés, e disse: Subamos animosamente, e possuamo-la em herança: porque certamente prevaleceremos contra ela.

[[v4-13-31]]

^<<v4-13-31,31>>^ Porém os homens que com ele subiram disseram: Não poderemos subir contra aquele povo, porque é  mais forte do que nós.

[[v4-13-32]]

^<<v4-13-32,32>>^ E infamaram a terra, que tinham espiado, perante os filhos de Israel, dizendo: A terra, pelo meio da qual passamos a espiar, é  terra que consome os seus moradores; e todo o povo que vimos no meio dela são  homens de grande estatura.

[[v4-13-33]]

^<<v4-13-33,33>>^ Também vimos ali gigantes, filhos de Enaque, descendentes  dos gigantes: e éramos aos nossos olhos como gafanhotos, assim também  éramos aos seus olhos.

'''

xref:004-numeros/004-numeros-012.adoc#v4-12-0[&#60; Capítulo Anterior] | <<v4-13-0,Topo>> | xref:004-numeros/004-numeros-014.adoc#v4-14-0[Próximo Capítulo &#62;]