include::./index.adoc[]

[[v4-22-0]]
=== Números, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-22-1]]

^<<v4-22-1,1>>^ DEPOIS partiram os filhos de Israel, e acamparam-se nas campinas de Moabe, desta banda do Jordão de  Jericó.

[[v4-22-2]]

^<<v4-22-2,2>>^ Viu pois Balaque, filho de Zipor, tudo o que Israel fizera aos amorreus.

[[v4-22-3]]

^<<v4-22-3,3>>^ E Moabe temeu muito diante deste povo, porque era muito: e Moabe andava angustiado por causa dos filhos de Israel.

[[v4-22-4]]

^<<v4-22-4,4>>^ Pelo que Moabe disse aos anciãos dos midianitas: Agora lamberá esta congregação tudo quanto houver  ao redor de nós, como o boi lambe a erva do campo. Naquele tempo Balaque, filho de Zipor, era  rei dos moabitas.

[[v4-22-5]]

^<<v4-22-5,5>>^ Este enviou mensageiros a Balaão, filho de Beor, a Petor, que está  junto ao rio, na terra dos filhos do seu povo, a chamá-lo, dizendo: Eis que um povo saiu do Egito: eis que cobre a face da terra, e parado está defronte de mim.

[[v4-22-6]]

^<<v4-22-6,6>>^ Vem pois agora, rogo-te, amaldiçoa-me este povo, pois mais poderoso é do que eu; para ver se o poderei ferir, e o lançarei fora da terra: porque eu sei que, a quem tu abençoares será abençoado, e a quem tu amaldiçoares será amaldiçoado.

[[v4-22-7]]

^<<v4-22-7,7>>^ Então foram-se os anciãos dos moabitas e os anciãos dos midianitas com o preço  dos encantamentos nas suas mãos: e chegaram a Balaão, e lhe disseram as palavras de Balaque.

[[v4-22-8]]

^<<v4-22-8,8>>^ E ele  lhes disse: Passai aqui esta noite, e vos trarei a resposta, como o Senhor me falar: então os príncipes dos moabitas ficaram com Balaão.

[[v4-22-9]]

^<<v4-22-9,9>>^ E veio Deus a Balaão, e disse: Quem são  estes homens que estão  contigo?

[[v4-22-10]]

^<<v4-22-10,10>>^ E Balaão disse a Deus: Balaque, filho de Zipor, rei dos moabitas, m os  enviou dizendo :

[[v4-22-11]]

^<<v4-22-11,11>>^ Eis que o povo que saiu do Egito cobriu a face da terra: vem agora, amaldiçoa-mo; porventura poderei pelejar contra ele, e o lançarei fora.

[[v4-22-12]]

^<<v4-22-12,12>>^ Então disse Deus a Balaão: Não irás com eles, nem amaldiçoarás a este povo, porquanto bendito é.

[[v4-22-13]]

^<<v4-22-13,13>>^ Então Balaão levantou-se pela manhã, e disse aos príncipes de Balaque: Ide à vossa terra, porque o Senhor recusa deixar-me ir convosco.

[[v4-22-14]]

^<<v4-22-14,14>>^ E levantaram-se os príncipes dos moabitas, e vieram a Balaque, e disseram: Balaão recusou vir conosco.

[[v4-22-15]]

^<<v4-22-15,15>>^ Porém Balaque prosseguiu ainda em enviar mais príncipes, e mais honrados do que aqueles.

[[v4-22-16]]

^<<v4-22-16,16>>^ Os quais vieram a Balaão, e lhe disseram: Assim diz Balaque, filho de Zipor: Rogo-te que não te demores em vir a mim,

[[v4-22-17]]

^<<v4-22-17,17>>^ Porque grandemente te honrarei, e farei tudo o que me disseres: vem pois, rogo-te, amaldiçoa-me este povo.

[[v4-22-18]]

^<<v4-22-18,18>>^ Então Balaão respondeu, e disse aos servos de Balaque: Ainda que Balaque me desse a sua casa cheia de prata e de ouro, eu não poderia traspassar o mandado do Senhor meu Deus, para fazer cousa pequena ou grande;

[[v4-22-19]]

^<<v4-22-19,19>>^ Agora, pois, rogo-vos que também aqui fiqueis esta noite, para que eu saiba o que o Senhor me dirá mais.

[[v4-22-20]]

^<<v4-22-20,20>>^ Veio pois o Senhor a Balaão, de noite, e disse-lhe: Se aqueles homens te vieram chamar, levanta-te, vai com eles; todavia, farás o que eu te disser.

[[v4-22-21]]

^<<v4-22-21,21>>^ Então Balaão levantou-se pela manhã, e albardou a sua jumenta, e foi-se com os príncipes de Moabe.

[[v4-22-22]]

^<<v4-22-22,22>>^ E a ira de Deus acendeu-se, porque ele se ia: e o anjo do Senhor pôs-se-lhe no caminho por adversário: e ele ia caminhando, montado na sua jumenta, e dois de seus moços com ele.

[[v4-22-23]]

^<<v4-22-23,23>>^ Viu pois a jumenta o anjo do Senhor, que estava no caminho, com a sua espada desembainhada na mão; pelo que desviou-se a jumenta do caminho e foi-se pelo campo: então Balaão espancou a jumenta para fazê-la tornar ao caminho.

[[v4-22-24]]

^<<v4-22-24,24>>^ Mas o anjo do Senhor pôs-se numa vereda de vinhas, havendo  uma parede desta banda e uma parede da outra.

[[v4-22-25]]

^<<v4-22-25,25>>^ Vendo pois a jumenta o anjo do Senhor, apertou-se contra a parede, e apertou contra a parede o pé de Balaão; pelo que tornou a espancá-la.

[[v4-22-26]]

^<<v4-22-26,26>>^ Então o anjo do Senhor passou mais adiante e pôs-se num lugar estreito, onde não havia  caminho para se desviar nem para a direita nem para a esquerda.

[[v4-22-27]]

^<<v4-22-27,27>>^ E, vendo a jumenta o anjo do Senhor, deitou-se debaixo de Balaão: e a ira de Balaão acendeu-se, e espancou a jumenta com o bordão.

[[v4-22-28]]

^<<v4-22-28,28>>^ Então o Senhor abriu a boca da jumenta, a qual disse a Balaão: Que te fiz eu, que me espancaste estas três vezes?

[[v4-22-29]]

^<<v4-22-29,29>>^ E Balaão disse à jumenta: Por que zombaste de mim: oxalá tivera eu uma espada na mão, porque agora te matara.

[[v4-22-30]]

^<<v4-22-30,30>>^ E a jumenta disse a Balaão: Porventura  não sou  a tua jumenta, em que cavalgaste desde o tempo que eu fui  tua até hoje? Costumei eu alguma vez fazer assim contigo? E ele  respondeu: Não.

[[v4-22-31]]

^<<v4-22-31,31>>^ Então o Senhor abriu os olhos a Balaão, e ele viu o anjo do Senhor, que estava no caminho, e a sua espada desembainhada na mão: pelo que inclinou a cabeça, e prostrou-se sobre a sua face.

[[v4-22-32]]

^<<v4-22-32,32>>^ Então o anjo do Senhor lhe disse: Por que já três vezes espancaste a tua jumenta? Eis que eu saí para ser teu  adversário, porquanto o teu  caminho é perverso diante de mim:

[[v4-22-33]]

^<<v4-22-33,33>>^ Porém a jumenta me viu, e já três vezes se desviou de diante de mim: se ela se não desviara de diante de mim, na verdade que eu  agora te tivera matado, e a ela deixara com vida.

[[v4-22-34]]

^<<v4-22-34,34>>^ Então Balaão disse ao anjo do Senhor: Pequei, que não soube que estavas neste caminho para te opores a mim; e agora, se parece  mal aos teus olhos, tornar-me-ei.

[[v4-22-35]]

^<<v4-22-35,35>>^ E disse o anjo do Senhor a Balaão: Vai-te com estes homens, mas somente a palavra que eu falar a ti esta falarás. Assim Balaão foi-se com os príncipes de Balaque.

[[v4-22-36]]

^<<v4-22-36,36>>^ Ouvindo pois Balaque que Balaão vinha, saiu-lhe ao encontro até à cidade de Moabe, que está  no termo de Arnom, na extremidade do termo dele.

[[v4-22-37]]

^<<v4-22-37,37>>^ E Balaque disse a Balaão: Porventura  não enviei diligentemente a chamar-te? por que não vieste a mim? não posso eu na verdade honrar-te?

[[v4-22-38]]

^<<v4-22-38,38>>^ Então Balaão disse a Balaque: Eis que eu tenho vindo a ti: porventura poderei eu agora de alguma forma falar alguma cousa? a palavra que Deus puser na minha boca essa falarei.

[[v4-22-39]]

^<<v4-22-39,39>>^ E Balaão foi com Balaque, e vieram a Quiriate-Huzote.

[[v4-22-40]]

^<<v4-22-40,40>>^ Então Balaque matou bois e ovelhas; e deles  enviou a Balaão e aos príncipes que estavam  com ele.

[[v4-22-41]]

^<<v4-22-41,41>>^ E sucedeu que, pela manhã, Balaque tomou a Balaão, e o fez subir aos altos de Baal, e viu ele dali a última parte  do povo.

'''

xref:004-numeros/004-numeros-021.adoc#v4-21-0[&#60; Capítulo Anterior] | <<v4-22-0,Topo>> | xref:004-numeros/004-numeros-023.adoc#v4-23-0[Próximo Capítulo &#62;]