include::./index.adoc[]

[[v4-27-0]]
=== Números, 27
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-27-1]]

^<<v4-27-1,1>>^ E CHEGARAM as filhas de Selofade, filho de Hefer, filho de Gileade, filho de Maquir, filho de Manassés, entre as famílias de Manassés, filho de José: (e estes são  os nomes de suas filhas: Macla, Noa, Hogla, Milca, e Tirzá);

[[v4-27-2]]

^<<v4-27-2,2>>^ E puseram-se diante de Moisés, e diante de Eleazar, o sacerdote, e diante dos príncipes e de toda a congregação, à porta da tenda da congregação, dizendo:

[[v4-27-3]]

^<<v4-27-3,3>>^ Nosso pai morreu no deserto, e não estava entre a congregação dos que se congregaram contra o Senhor na congregação de Coré: mas morreu no seu próprio pecado, e não teve filhos.

[[v4-27-4]]

^<<v4-27-4,4>>^ Por que se tiraria o nome de nosso pai do meio da sua família, porquanto não teve filhos? Dá-nos possessão entre os irmãos de nosso pai.

[[v4-27-5]]

^<<v4-27-5,5>>^ E Moisés levou a sua causa perante o Senhor.

[[v4-27-6]]

^<<v4-27-6,6>>^ E falou o Senhor a Moisés, dizendo:

[[v4-27-7]]

^<<v4-27-7,7>>^ As filhas de Selofade falam retamente: certamente lhes darás possessão de herança entre os irmãos de seu pai; e a herança de seu pai farás passar a elas.

[[v4-27-8]]

^<<v4-27-8,8>>^ E falarás aos filhos de Israel, dizendo: Quando alguém morrer, e não tiver filho, então fareis passar a sua herança a sua filha.

[[v4-27-9]]

^<<v4-27-9,9>>^ E, se não tiver filha, então a sua herança dareis a seus irmãos.

[[v4-27-10]]

^<<v4-27-10,10>>^ Porém, se não tiver irmãos, então dareis a sua herança aos irmãos de seu pai.

[[v4-27-11]]

^<<v4-27-11,11>>^ Se também seu pai não tiver irmãos, então a sua herança dareis a seu parente, àquele que  lhe for  o mais chegado da sua família, para que a possua: isto aos filhos de Israel será por estatuto de direito, como o Senhor ordenou a Moisés.

[[v4-27-12]]

^<<v4-27-12,12>>^ Depois disse o Senhor a Moisés: Sobe a este monte de Abarim, e vê a terra que tenho dado aos filhos de Israel.

[[v4-27-13]]

^<<v4-27-13,13>>^ E, havendo-a visto, então serás recolhido aos teus povos, assim como foi recolhido teu irmão Aarão:

[[v4-27-14]]

^<<v4-27-14,14>>^ Porquanto rebeldes fostes no deserto de Zim, na contenda da congregação, ao meu mandado de me santificar nas águas diante dos seus olhos: (estas são  as águas de Meribá de Cades, no deserto de Zim.)

[[v4-27-15]]

^<<v4-27-15,15>>^ Então falou Moisés ao Senhor, dizendo:

[[v4-27-16]]

^<<v4-27-16,16>>^ O Senhor, Deus dos espíritos de toda a carne, ponha um homem sobre esta congregação.

[[v4-27-17]]

^<<v4-27-17,17>>^ Que saia diante deles, e que entre diante deles, e que os faça sair, e que os faça entrar: para que a congregação do Senhor não seja como ovelhas que não têm pastor.

[[v4-27-18]]

^<<v4-27-18,18>>^ Então disse o Senhor a Moisés: Toma para ti a Josué, filho de Num, homem em quem há  o espírito, e põe a tua mão sobre ele.

[[v4-27-19]]

^<<v4-27-19,19>>^ E apresenta-o perante Eleazar, o sacerdote, e perante toda a congregação, e dá-lhe mandamentos aos olhos deles,

[[v4-27-20]]

^<<v4-27-20,20>>^ E põe sobre ele da tua glória, para que obedeça toda a congregação dos filhos de Israel.

[[v4-27-21]]

^<<v4-27-21,21>>^ E se porá perante Eleazar, o sacerdote, o qual por ele consultará, segundo o juízo de Urim, perante o Senhor: conforme ao seu dito sairão, e conforme ao seu dito entrarão, ele e todos os filhos de Israel com ele, e toda a congregação.

[[v4-27-22]]

^<<v4-27-22,22>>^ E fez Moisés como o Senhor lhe ordenara: porque tomou a Josué, e apresentou-o perante Eleazar, o sacerdote, e perante toda a congregação:

[[v4-27-23]]

^<<v4-27-23,23>>^ E sobre ele pôs as suas mãos, e lhe deu mandamentos, como o Senhor ordenara pela mão de Moisés.

'''

xref:004-numeros/004-numeros-026.adoc#v4-26-0[&#60; Capítulo Anterior] | <<v4-27-0,Topo>> | xref:004-numeros/004-numeros-028.adoc#v4-28-0[Próximo Capítulo &#62;]