include::./index.adoc[]

[[v4-23-0]]
=== Números, 23
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-23-1]]

^<<v4-23-1,1>>^ ENTÃO Balaão disse a Balaque: Edifica-me aqui sete altares, e prepara-me aqui sete bezerros e sete carneiros.

[[v4-23-2]]

^<<v4-23-2,2>>^ Fez pois Balaque como Balaão dissera: e Balaque e Balaão ofereceram um bezerro e um carneiro sobre cada  altar.

[[v4-23-3]]

^<<v4-23-3,3>>^ Então Balaão disse a Balaque: Fica-te ao pé do teu holocausto, e eu irei; porventura o Senhor me sairá ao encontro, e o que me mostrar te notificarei. Então foi a um alto.

[[v4-23-4]]

^<<v4-23-4,4>>^ E, encontrando-se Deus, com Balaão, lhe disse este : Preparei sete altares, e ofereci um bezerro e um carneiro sobre cada  altar.

[[v4-23-5]]

^<<v4-23-5,5>>^ Então o Senhor pôs a palavra na boca de Balaão, e disse: Torna para Balaque, e fala assim.

[[v4-23-6]]

^<<v4-23-6,6>>^ E, tornando para ele, eis que estava ao pé do seu holocausto, ele e todos os príncipes dos moabitas.

[[v4-23-7]]

^<<v4-23-7,7>>^ Então alçou a sua parábola, e disse: De Arão me mandou trazer Balaque, rei dos moabitas, das montanhas do oriente, dizendo : Vem, amaldiçoa-me a Jacó; e vem, detesta a Israel.

[[v4-23-8]]

^<<v4-23-8,8>>^ Como amaldiçoarei o que Deus não amaldiçoa? e como detestarei, quando  o Senhor não detesta?

[[v4-23-9]]

^<<v4-23-9,9>>^ Porque do cume das penhas o vejo, e dos outeiros o contemplo: eis que este povo habitará só, e entre as gentes não será contado.

[[v4-23-10]]

^<<v4-23-10,10>>^ Quem contará o pó de Jacó e o número da quarta parte  de Israel? a minha alma morra da morte dos justos, e seja o meu fim como o seu.

[[v4-23-11]]

^<<v4-23-11,11>>^ Então disse Balaque a Balaão: Que me fizeste? chamei-te para amaldiçoar os meus inimigos, mas eis que inteiramente os  abençoaste.

[[v4-23-12]]

^<<v4-23-12,12>>^ E ele respondeu, e disse: Porventura  não terei cuidado de falar o que o Senhor pôs na minha boca?

[[v4-23-13]]

^<<v4-23-13,13>>^ Então Balaque lhe disse: Rogo-te que venhas comigo a outro lugar, donde o verás; verás somente a última parte  dele, mas a todo ele não verás: e amaldiçoa-mo dali.

[[v4-23-14]]

^<<v4-23-14,14>>^ Assim o tomou consigo ao campo de Zofim, ao cume de Pisga: e edificou sete altares, e ofereceu um bezerro e um carneiro sobre cada  altar.

[[v4-23-15]]

^<<v4-23-15,15>>^ Então disse a Balaque: Fica aqui ao pé do teu holocausto, e eu irei ali ao seu  encontro.

[[v4-23-16]]

^<<v4-23-16,16>>^ E, encontrando-se o Senhor com Balaão, pôs uma palavra na sua boca, e disse: Torna para Balaque, e fala assim.

[[v4-23-17]]

^<<v4-23-17,17>>^ E, vindo a ele, eis que estava ao pé do holocausto, e os príncipes dos moabitas com ele: disse-lhe pois Balaque: Que cousa falou o Senhor?

[[v4-23-18]]

^<<v4-23-18,18>>^ Então alçou a sua parábola, e disse: Levanta-te, Balaque, e ouve: inclina os teus ouvidos a mim, filho de Zipor.

[[v4-23-19]]

^<<v4-23-19,19>>^ Deus não é  homem, para que minta; nem filho do homem, para que se arrependa: porventura  diria ele , e não o  faria? ou falaria, e não o confirmaria?

[[v4-23-20]]

^<<v4-23-20,20>>^ Eis que recebi mandado  de abençoar: pois ele tem abençoado, e eu não o posso revogar.

[[v4-23-21]]

^<<v4-23-21,21>>^ Não viu iniquidade em Israel, nem contemplou maldade em Jacó: o Senhor seu Deus é  com ele, e nele, e entre eles se ouve  o alarido dum rei.

[[v4-23-22]]

^<<v4-23-22,22>>^ Deus os tirou do Egito; as suas forças são  como as do unicórnio.

[[v4-23-23]]

^<<v4-23-23,23>>^ Pois contra Jacó não vale encantamento, nem adivinhação contra Israel: neste tempo se dirá de Jacó e de Israel: Que cousas Deus tem obrado!

[[v4-23-24]]

^<<v4-23-24,24>>^ Eis que o povo se levantará como leoa, e se exalçará como leão: não se deitará até que coma a presa, e beba o sangue de mortos.

[[v4-23-25]]

^<<v4-23-25,25>>^ Então Balaque disse a Balaão: Nem totalmente o amaldiçoarás, nem totalmente o abençoarás.

[[v4-23-26]]

^<<v4-23-26,26>>^ Porém Balaão respondeu, e disse a Balaque: Não te falei eu, dizendo: Tudo o que o Senhor falar aquilo farei?

[[v4-23-27]]

^<<v4-23-27,27>>^ Disse mais Balaque a Balaão: Ora vem, e te levarei a outro lugar: porventura bem parecerá aos olhos de Deus que dali mo amaldiçoes.

[[v4-23-28]]

^<<v4-23-28,28>>^ Então Balaque levou Balaão consigo ao cume de Peor, que olha para a banda do deserto.

[[v4-23-29]]

^<<v4-23-29,29>>^ Balaão disse a Balaque: Edifica-me aqui sete altares, e prepara-me aqui sete bezerros e sete carneiros.

[[v4-23-30]]

^<<v4-23-30,30>>^ Balaque pois fez como dissera Balaão; e ofereceu um bezerro e um carneiro sobre cada  altar.

'''

xref:004-numeros/004-numeros-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numeros/004-numeros-024.adoc#v4-24-0[Próximo Capítulo &#62;]