include::./index.adoc[]

[[v4-11-0]]
=== Números, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-11-1]]

^<<v4-11-1,1>>^ E ACONTECEU que, queixando-se o povo, era mal aos ouvidos do Senhor; porque o Senhor ouviu-o, e a sua ira se acendeu, e o fogo do Senhor ardeu entre eles, e consumiu os que estavam  na última parte do arraial.

[[v4-11-2]]

^<<v4-11-2,2>>^ Então o povo clamou a Moisés, e Moisés orou ao Senhor, e o fogo se apagou.

[[v4-11-3]]

^<<v4-11-3,3>>^ Pelo que chamou aquele lugar Tabera, porquanto o fogo do Senhor se acendera entre eles.

[[v4-11-4]]

^<<v4-11-4,4>>^ E o vulgo, que estava  no meio deles, veio a ter grande desejo: pelo que os filhos de Israel tornaram a chorar, e disseram: Quem nos dará carne a comer?

[[v4-11-5]]

^<<v4-11-5,5>>^ Lembramo-nos dos peixes que no Egito comíamos de graça; e  dos pepinos, e dos melões, e dos porros, e das cebolas, e dos alhos.

[[v4-11-6]]

^<<v4-11-6,6>>^ Mas agora a nossa alma se seca; cousa nenhuma há  senão este maná diante dos  nossos olhos.

[[v4-11-7]]

^<<v4-11-7,7>>^ E era o maná como semente de coentro, e a sua cor como a cor de bdélio.

[[v4-11-8]]

^<<v4-11-8,8>>^ Espalhava-se o povo, e o  colhia, e em moinhos o  moía, ou num gral o  pisava, e em panelas o  cozia, e dele fazia bolos: e o seu sabor era como o sabor de azeite fresco.

[[v4-11-9]]

^<<v4-11-9,9>>^ E, quando o orvalho descia de noite sobre o arraial, o maná descia sobre ele.

[[v4-11-10]]

^<<v4-11-10,10>>^ Então Moisés ouviu chorar o povo pelas suas famílias, cada qual à porta da sua tenda: e a ira do Senhor grandemente se acendeu, e pareceu mal aos olhos de Moisés.

[[v4-11-11]]

^<<v4-11-11,11>>^ E disse Moisés ao Senhor: Por que fizeste mal a teu servo, e por que não achei graça aos teus olhos, que pusesses sobre mim o cargo de todo este povo?

[[v4-11-12]]

^<<v4-11-12,12>>^ Concebi eu porventura todo este povo? Gerei-o eu para que me dissesses: leva-o ao teu colo, como o aio leva o que cria, à terra que juraste a seus pais?

[[v4-11-13]]

^<<v4-11-13,13>>^ Donde teria eu carne para dar a todo este povo? porquanto contra mim choram, dizendo: Dá-nos carne a comer:

[[v4-11-14]]

^<<v4-11-14,14>>^ Eu só não posso levar a todo este povo, porque muito pesado é  para mim.

[[v4-11-15]]

^<<v4-11-15,15>>^ E se assim fazes comigo, mata-me, eu to peço, se tenho achado graça aos teus olhos; e não me deixes ver o meu mal.

[[v4-11-16]]

^<<v4-11-16,16>>^ E disse o Senhor a Moisés: Ajunta-me setenta homens dos anciãos de Israel, de quem sabes que são anciãos do povo, e seus oficiais: e os trarás perante a tenda da congregação, e ali se porão contigo.

[[v4-11-17]]

^<<v4-11-17,17>>^ Então eu descerei e ali falarei contigo, e tirarei do espírito que está  sobre ti, e o  porei sobre eles: e contigo levarão o cargo do povo, para que tu só o  não leves.

[[v4-11-18]]

^<<v4-11-18,18>>^ E dirás ao povo: Santificai-vos para amanhã, e comereis carne: porquanto chorastes aos ouvidos do Senhor, dizendo: Quem nos dará carne a comer, pois bem nos ia no Egito? Pelo que o Senhor vos dará carne, e comereis:

[[v4-11-19]]

^<<v4-11-19,19>>^ Não comereis um dia, nem dois dias, nem cinco dias, nem dez dias, nem vinte dias:

[[v4-11-20]]

^<<v4-11-20,20>>^ Mas um mês inteiro, até vos sair pelos narizes, até que vos enfastieis dela porquanto rejeitastes ao Senhor, que está  no meio de vós, e chorastes diante dele dizendo: Por que saímos do Egito?

[[v4-11-21]]

^<<v4-11-21,21>>^ E disse Moisés: Seiscentos mil homens de pé é  este povo, no meio do qual estou : e tu tens dito: Dar-lhes-ei carne, e comerão um mês inteiro.

[[v4-11-22]]

^<<v4-11-22,22>>^ Degolar-se-ão para eles ovelhas e vacas, que lhes bastem? ou ajuntar-se-ão para eles todos os peixes do mar, que lhes bastem?

[[v4-11-23]]

^<<v4-11-23,23>>^ Porém o Senhor disse a Moisés: Seria pois encurtada a mão do Senhor? agora verás se a minha palavra te acontecerá ou não.

[[v4-11-24]]

^<<v4-11-24,24>>^ E saiu Moisés, e falou as palavras do Senhor ao povo, e ajuntou setenta homens dos anciãos do povo e os pôs de roda da tenda.

[[v4-11-25]]

^<<v4-11-25,25>>^ Então o Senhor desceu na nuvem, e lhe falou; e, tirando do espírito, que estava  sobre ele, o  pôs sobre aqueles setenta anciãos: e aconteceu que, quando o espírito repousou sobre eles, profetizaram; mas depois nunca mais.

[[v4-11-26]]

^<<v4-11-26,26>>^ Porém no arraial ficaram dois homens; o nome dum era  Eldade, e o nome do outro Medade; e repousou sobre eles o espírito (porquanto estavam entre os inscritos, ainda que não saíram à tenda), e profetizavam no arraial.

[[v4-11-27]]

^<<v4-11-27,27>>^ Então correu um moço, e o anunciou a Moisés, e disse: Eldade e Medade profetizam no arraial.

[[v4-11-28]]

^<<v4-11-28,28>>^ E Josué, filho de Num, servidor de Moisés, um dos seus mancebos escolhidos, respondeu, e disse: Senhor meu, Moisés, proíbe-lho.

[[v4-11-29]]

^<<v4-11-29,29>>^ Porém Moisés lhe disse: Tens tu ciúmes por mim? Oxalá que todo o povo do Senhor fosse profeta, que o Senhor lhes desse o seu espírito!

[[v4-11-30]]

^<<v4-11-30,30>>^ Depois Moisés se recolheu ao arraial, ele e os anciãos de Israel.

[[v4-11-31]]

^<<v4-11-31,31>>^ Então soprou um vento do Senhor, e trouxe codornizes do mar, e as espalhou pelo arraial quase caminho dum dia duma banda, e quase caminho dum dia da outra banda, à roda do arraial, e a quase dois côvados sobre a terra.

[[v4-11-32]]

^<<v4-11-32,32>>^ Então o povo se levantou todo aquele dia e toda aquela noite, e todo o dia seguinte, e colheram as codornizes; o que menos tinha, colhera dez ômeres; e as estenderam para si ao redor do arraial.

[[v4-11-33]]

^<<v4-11-33,33>>^ Quando a carne estava  entre os seus dentes, antes que fosse mastigada, se acendeu a ira do Senhor contra o povo, e feriu o Senhor o povo com uma praga muito grande.

[[v4-11-34]]

^<<v4-11-34,34>>^ Pelo que o nome daquele lugar se chamou Quibrote-Ataavá, porquanto ali enterraram o povo que teve o desejo.

[[v4-11-35]]

^<<v4-11-35,35>>^ De Quibrote-Ataavá caminhou o povo para Hazerote, e pararam em Hazerote.

'''

xref:004-numeros/004-numeros-010.adoc#v4-10-0[&#60; Capítulo Anterior] | <<v4-11-0,Topo>> | xref:004-numeros/004-numeros-012.adoc#v4-12-0[Próximo Capítulo &#62;]