include::./index.adoc[]

[[v4-18-0]]
=== Números, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-18-1]]

^<<v4-18-1,1>>^ ENTÃO disse o Senhor a Aarão: Tu, e teus filhos, e a casa de teu pai contigo, levareis sobre vós a iniquidade do santuário: e tu e teus filhos contigo levareis sobre vós  a iniquidade do vosso sacerdócio.

[[v4-18-2]]

^<<v4-18-2,2>>^ E também farás chegar contigo a teus irmãos, a tribo de Levi, a tribo de teu pai, para que se ajuntem a ti, e te sirvam; mas tu e teus filhos contigo estareis  perante a tenda do testemunho.

[[v4-18-3]]

^<<v4-18-3,3>>^ E eles farão a tua guarda, a guarda de toda a tenda: mas não se chegarão aos vasos do santuário, e ao altar, para que não morram, tanto eles como vós.

[[v4-18-4]]

^<<v4-18-4,4>>^ Mas se ajuntarão a ti, e farão a guarda da tenda da congregação em todo o ministério da tenda; e o estranho não se chegará a vós.

[[v4-18-5]]

^<<v4-18-5,5>>^ Vós pois fareis a guarda do santuário e a guarda do altar; para que não haja outra vez furor sobre os filhos de Israel.

[[v4-18-6]]

^<<v4-18-6,6>>^ E eu, eis que tenho tomado vossos irmãos, os levitas, do meio dos filhos de Israel: a vós são dados em dádiva pelo Senhor, para administrar o ministério da tenda da congregação.

[[v4-18-7]]

^<<v4-18-7,7>>^ Mas tu e teus filhos contigo guardareis o vosso sacerdócio em todo o negócio do altar, e no que estiver  dentro do véu, isto  administrareis: eu vos  tenho dado o vosso sacerdócio em dádiva ministerial, e o estranho que se chegar morrerá.

[[v4-18-8]]

^<<v4-18-8,8>>^ Disse mais o Senhor a Aarão: E eu, eis que te tenho dado a guarda das minhas ofertas alçadas, com todas as cousas santas dos filhos de Israel; por causa da unção as tenho dado a ti e a teus filhos por estatuto perpétuo.

[[v4-18-9]]

^<<v4-18-9,9>>^ Isto terás das cousas  santíssimas do fogo: todas as suas ofertas, com todas as suas ofertas de manjares, e com todas as suas expiações do pecado, e com todas as suas expiações da culpa, que me restituírem, serão cousas  santíssimas para ti e para teus filhos.

[[v4-18-10]]

^<<v4-18-10,10>>^ No lugar  santíssimo o comerás: todo o varão o comerá; santidade será para ti.

[[v4-18-11]]

^<<v4-18-11,11>>^ Também isto será  teu; a oferta alçada dos seus dons com todas as ofertas movidas dos filhos de Israel; a ti, a teus filhos, e a tuas filhas contigo, as tenho dado por estatuto perpétuo; todo o que estiver  limpo na tua casa as comerá.

[[v4-18-12]]

^<<v4-18-12,12>>^ Todo o melhor do azeite, e todo o melhor do mosto e do grão, as suas primícias que derem ao Senhor as tenho dado a ti.

[[v4-18-13]]

^<<v4-18-13,13>>^ Os primeiros frutos de tudo que houver na terra, que trouxerem ao Senhor, serão teus; todo o que estiver  limpo na tua casa os comerá.

[[v4-18-14]]

^<<v4-18-14,14>>^ Toda a cousa consagrada em Israel será tua.

[[v4-18-15]]

^<<v4-18-15,15>>^ Tudo o que abrir a madre, de toda a carne que trouxerem ao Senhor, tanto de homens como de animais, será teu; porém os primogênitos dos homens resgatarás; também os primogênitos dos animais imundos resgatarás.

[[v4-18-16]]

^<<v4-18-16,16>>^ Os que pois deles se houverem de resgatar resgatarás, da idade dum mês, segundo a tua avaliação, por cinco siclos de dinheiro, segundo o siclo do santuário, que é de vinte geras.

[[v4-18-17]]

^<<v4-18-17,17>>^ Mas o primogênito de vaca, ou primogênito de ovelha, ou primogênito de cabra, não resgatarás, santos são: o seu sangue espargirás sobre o altar, e a sua gordura queimarás em  oferta queimada de cheiro suave ao Senhor.

[[v4-18-18]]

^<<v4-18-18,18>>^ E a carne deles será tua: assim  como será teu o peito do movimento, e o ombro direito.

[[v4-18-19]]

^<<v4-18-19,19>>^ Todas as ofertas alçadas das santidades, que os filhos de Israel oferecerem ao Senhor, tenho dado a ti, e a teus filhos e a tuas filhas contigo, por estatuto perpétuo: concerto perpétuo de sal perante o Senhor é, para ti e para a tua semente contigo.

[[v4-18-20]]

^<<v4-18-20,20>>^ Disse também o Senhor a Aarão: Na sua terra possessão nenhuma terás, e no meio deles, nenhuma parte terás: eu sou  a tua parte e a tua herança no meio dos filhos de Israel.

[[v4-18-21]]

^<<v4-18-21,21>>^ E eis que aos filhos de Levi tenho dado todos os dízimos em Israel por herança, pelo seu ministério que exerce, o ministério da tenda da congregação.

[[v4-18-22]]

^<<v4-18-22,22>>^ E nunca mais os filhos de Israel se chegarão a tenda da congregação, para que não levem sobre si  o pecado, e morram.

[[v4-18-23]]

^<<v4-18-23,23>>^ Mas os levitas administrarão o ministério da tenda da congregação, e eles levarão sobre si a sua iniquidade: pelas vossas gerações estatuto perpétuo será; e no meio dos filhos de Israel nenhuma herança herdarão.

[[v4-18-24]]

^<<v4-18-24,24>>^ Porque os dízimos dos filhos de Israel, que oferecerem ao Senhor em oferta alçada, tenho dado por herança aos levitas: porquanto eu lhes disse: No meio dos filhos de Israel nenhuma herança herdarão.

[[v4-18-25]]

^<<v4-18-25,25>>^ E falou o Senhor a Moisés, dizendo:

[[v4-18-26]]

^<<v4-18-26,26>>^ Também falarás aos levitas, e dir-lhes-ás: Quando receberdes os dízimos dos filhos de Israel, que eu deles vos tenho dado em vossa herança, deles oferecereis uma oferta alçada ao Senhor; os dízimos dos dízimos.

[[v4-18-27]]

^<<v4-18-27,27>>^ E contar-se-vos-á a vossa oferta alçada, como grão da eira, e como plenitude do lagar.

[[v4-18-28]]

^<<v4-18-28,28>>^ Assim também oferecereis ao Senhor uma oferta alçada de todos os vossos dízimos, que receberdes dos filhos de Israel, e deles dareis a oferta alçada do Senhor a Aarão, o sacerdote.

[[v4-18-29]]

^<<v4-18-29,29>>^ De todos os vossos dons oferecereis toda a oferta alçada do Senhor: do melhor deles, a sua santa parte.

[[v4-18-30]]

^<<v4-18-30,30>>^ Dir-lhes-ás pois: Quando oferecerdes o melhor deles, como novidade da eira, e como novidade do lagar, se contará aos levitas.

[[v4-18-31]]

^<<v4-18-31,31>>^ E o comereis em todo o lugar, vós e a vossa casa, porque vosso galardão é  pelo vosso ministério na tenda da congregação.

[[v4-18-32]]

^<<v4-18-32,32>>^ Pelo que não levareis sobre vós  o pecado, quando deles oferecerdes o melhor: e não profanareis as cousas santas dos filhos de Israel, para que não morrais.

'''

xref:004-numeros/004-numeros-017.adoc#v4-17-0[&#60; Capítulo Anterior] | <<v4-18-0,Topo>> | xref:004-numeros/004-numeros-019.adoc#v4-19-0[Próximo Capítulo &#62;]