include::./index.adoc[]

[[v4-4-0]]
=== Números, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-4-1]]

^<<v4-4-1,1>>^ E FALOU o Senhor a Moisés e a Aarão, dizendo:

[[v4-4-2]]

^<<v4-4-2,2>>^ Toma a soma dos filhos de Coate, do meio dos filhos de Levi, pelas suas gerações, segundo a casa de seus pais;

[[v4-4-3]]

^<<v4-4-3,3>>^ Da idade de trinta anos e para cima até aos cinquenta anos será  todo aquele que entrar neste exército, para fazer obra na tenda da congregação.

[[v4-4-4]]

^<<v4-4-4,4>>^ Este será  o ministério dos filhos de Coate na tenda da congregação, nas cousas  santíssimas.

[[v4-4-5]]

^<<v4-4-5,5>>^ Quando partir o arraial, Aarão e seus filhos virão, e tirarão o véu da coberta, e com ele cobrirão a arca do testemunho;

[[v4-4-6]]

^<<v4-4-6,6>>^ E pôr-lhe-ão por cima uma coberta de peles de texugos, e sobre ela estenderão um pano, todo de azul, e lhe meterão os varais.

[[v4-4-7]]

^<<v4-4-7,7>>^ Também sobre a mesa da proposição estenderão um pano de azul: e sobre ela porão os pratos, os seus incensários, e as taças e escudelas; também o pão contínuo estará sobre ela.

[[v4-4-8]]

^<<v4-4-8,8>>^ Depois estenderão em cima deles um pano de carmesim, e com a coberta de peles de texugos o cobrirão, e lhe  porão os seus varais.

[[v4-4-9]]

^<<v4-4-9,9>>^ Então tomarão um pano de azul, e cobrirão o castiçal da luminária, e as suas lâmpadas, e os seus espevitadores, e os seus apagadores, e todos os seus vasos de azeite, com que o servem.

[[v4-4-10]]

^<<v4-4-10,10>>^ E meterão, a ele e a todos os seus vasos, na coberta de peles de texugos: e o  porão sobre os varais.

[[v4-4-11]]

^<<v4-4-11,11>>^ E sobre o altar de ouro estenderão um pano de azul, e com a coberta de peles de texugos o cobrirão, e lhe  porão os seus varais.

[[v4-4-12]]

^<<v4-4-12,12>>^ Também tomarão todos os vasos do ministério, com que servem no santuário: e os porão num pano de azul, e os cobrirão com uma coberta de peles de texugos, e os  porão sobre os varais.

[[v4-4-13]]

^<<v4-4-13,13>>^ E tirarão as cinzas do altar, e por cima dele estenderão um pano de púrpura.

[[v4-4-14]]

^<<v4-4-14,14>>^ E sobre ele porão todos os seus instrumentos com que o servem: os seus braseiros, os garfos, e as pás, e as bacias; todos os vasos do altar: e por cima dele estenderão uma coberta de peles de texugos, e lhe  porão os seus varais.

[[v4-4-15]]

^<<v4-4-15,15>>^ Havendo pois Aarão e seus filhos, ao partir do arraial, acabado de cobrir o santuário, e todos os instrumentos do santuário, então os filhos de Coate virão para levá-lo; mas no santuário não tocarão para que não morram: este é  o cargo dos filhos de Coate na tenda da congregação.

[[v4-4-16]]

^<<v4-4-16,16>>^ Porém o cargo de Eleazar, filho de Aarão, o sacerdote, será  o azeite da luminária, e o incenso aromático , e a contínua oferta dos manjares, e o azeite da unção, o cargo de todo o tabernáculo, e de tudo que nele há , no santuário e nos seus vasos.

[[v4-4-17]]

^<<v4-4-17,17>>^ E falou o Senhor a Moisés e a Aarão, dizendo:

[[v4-4-18]]

^<<v4-4-18,18>>^ Não deixareis extirpar a tribo das gerações dos coatitas do meio dos levitas.

[[v4-4-19]]

^<<v4-4-19,19>>^ Mas isto lhes fareis, para que vivam e não morram, quando chegarem à santidade das santidades: Aarão e seus filhos virão, e a cada um porão no seu ministério e no seu cargo.

[[v4-4-20]]

^<<v4-4-20,20>>^ Porém não entrarão a ver, quando cobrirem o santuário, para que não morram.

[[v4-4-21]]

^<<v4-4-21,21>>^ Falou mais o Senhor a Moisés, dizendo:

[[v4-4-22]]

^<<v4-4-22,22>>^ Toma também a soma dos filhos de Gérson, segundo a casa de seus pais, segundo as suas gerações;

[[v4-4-23]]

^<<v4-4-23,23>>^ Da idade de trinta anos e para cima, até aos cinquenta, contarás a todo aquele que entrar a servir no seu serviço, para exercer o ministério na tenda da congregação.

[[v4-4-24]]

^<<v4-4-24,24>>^ Este será  o ministério das gerações dos gersonitas, no serviço e na carga:

[[v4-4-25]]

^<<v4-4-25,25>>^ Levarão pois as cortinas do tabernáculo, e a tenda da congregação, e a sua coberta, e a coberta de peles de texugos, que está  em cima, sobre ele, e o véu da porta da tenda da congregação,

[[v4-4-26]]

^<<v4-4-26,26>>^ E as cortinas do pátio, e o véu da porta do pátio, que está  junto ao tabernáculo, e junto ao altar em redor, e as suas cordas, e todos os instrumentos do seu ministério, com tudo o que se adereçar para eles, para que ministrem.

[[v4-4-27]]

^<<v4-4-27,27>>^ Todo o ministério dos filhos dos gersonitas, em todo o seu cargo, e em todo o seu ministério, será segundo o mandado de Aarão e de seus filhos: e lhes encomendareis em guarda todo o seu cargo.

[[v4-4-28]]

^<<v4-4-28,28>>^ Este é  o ministério das gerações dos filhos dos gersonitas na tenda da congregação: e a sua guarda será  debaixo da mão de Itamar, filho de Aarão, o sacerdote.

[[v4-4-29]]

^<<v4-4-29,29>>^ Quanto aos filhos de Merari, segundo as suas gerações e segundo a casa de seus pais os contarás;

[[v4-4-30]]

^<<v4-4-30,30>>^ Da idade de trinta anos e para cima, até aos cinquenta, contarás a todo aquele que entrar neste serviço, para exercer o ministério da tenda da congregação.

[[v4-4-31]]

^<<v4-4-31,31>>^ Esta pois será  a guarda do seu cargo, segundo todo o seu ministério, na tenda da congregação: as tábuas do tabernáculo, e os seus varais, e as suas colunas, e as suas bases;

[[v4-4-32]]

^<<v4-4-32,32>>^ Como também as colunas do pátio em redor, e as suas bases, e as suas estacas, e as suas cordas, com todos os seus instrumentos, com todo o seu ministério; e contareis os vasos da guarda do seu cargo, nome por nome.

[[v4-4-33]]

^<<v4-4-33,33>>^ Este é  o ministério das gerações dos filhos de Merari, segundo todo o seu ministério, na tenda da congregação, debaixo da mão de Itamar, filho de Aarão, o sacerdote.

[[v4-4-34]]

^<<v4-4-34,34>>^ Moisés, pois e Aarão e os príncipes da congregação contaram os filhos dos coatitas, segundo as suas gerações e segundo a casa de seus pais;

[[v4-4-35]]

^<<v4-4-35,35>>^ Da idade de trinta anos e para cima, até aos cinquenta, todo aquele que entrou neste serviço, para o ministério da tenda da congregação.

[[v4-4-36]]

^<<v4-4-36,36>>^ Os que  deles foram  contados, pois, segundo as suas gerações, foram dois mil e setecentos e cinquenta.

[[v4-4-37]]

^<<v4-4-37,37>>^ Estes são  os que foram  contados das gerações dos coatitas, de todo aquele que ministrava na tenda da congregação, os quais contaram Moisés e Aarão, conforme ao mandado do Senhor pela mão de Moisés.

[[v4-4-38]]

^<<v4-4-38,38>>^ Semelhantemente os que foram  contados dos filhos de Gérson, segundo as suas gerações, e segundo a casa de seus pais,

[[v4-4-39]]

^<<v4-4-39,39>>^ Da idade de trinta anos e para cima, até aos cinquenta, todo aquele que entrou neste serviço, para o ministério na tenda da congregação,

[[v4-4-40]]

^<<v4-4-40,40>>^ Os que  deles foram  contados, segundo as suas gerações, segundo a casa de seus pais, foram  dois mil e seiscentos e trinta.

[[v4-4-41]]

^<<v4-4-41,41>>^ Estes são  os contados das gerações dos filhos de Gérson, de todo aquele que ministrava na tenda da congregação: os quais contaram Moisés e Aarão, conforme ao mandado do Senhor.

[[v4-4-42]]

^<<v4-4-42,42>>^ E os que foram  contados das gerações dos filhos de Merari, segundo as suas gerações, segundo a casa de seus pais;

[[v4-4-43]]

^<<v4-4-43,43>>^ Da idade de trinta anos e para cima, até aos cinquenta, todo aquele que entrou neste serviço, para o ministério na tenda da congregação,

[[v4-4-44]]

^<<v4-4-44,44>>^ Foram pois os que foram  deles contados, segundo as suas gerações, três mil e duzentos.

[[v4-4-45]]

^<<v4-4-45,45>>^ Estes são  os contados das gerações dos filhos de Merari: os quais contaram Moisés e Aarão, conforme ao mandado do Senhor, pela mão de Moisés.

[[v4-4-46]]

^<<v4-4-46,46>>^ Todos os que  deles foram  contados, que contaram Moisés e Aarão, e os príncipes de Israel, dos levitas, segundo as suas gerações, segundo a casa de seus pais;

[[v4-4-47]]

^<<v4-4-47,47>>^ Da idade de trinta anos e para cima, até aos cinquenta, todo aquele que entrava a executar o ministério da administração, e o ministério da carga na tenda da congregação,

[[v4-4-48]]

^<<v4-4-48,48>>^ Os que  deles foram  contados foram oito mil quinhentos e oitenta.

[[v4-4-49]]

^<<v4-4-49,49>>^ Conforme ao mandado do Senhor, pela mão de Moisés, foram contados, cada qual segundo o seu ministério, e segundo o seu cargo: e foram, os que  deles foram  contados, aqueles que o Senhor ordenara a Moisés.

'''

xref:004-numeros/004-numeros-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numeros/004-numeros-005.adoc#v4-5-0[Próximo Capítulo &#62;]