include::./index.adoc[]

[[v4-26-0]]
=== Números, 26
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-26-1]]

^<<v4-26-1,1>>^ ACONTECEU pois que, depois daquela praga, falou o Senhor a Moisés e a Eleazar, filho de Aarão o sacerdote, dizendo:

[[v4-26-2]]

^<<v4-26-2,2>>^ Tomai a soma de toda a congregação dos filhos de Israel, da idade de vinte anos e para cima, segundo as casas de seus pais: todo o que em Israel vai para o exército.

[[v4-26-3]]

^<<v4-26-3,3>>^ Falou-lhe pois Moisés e Eleazar o sacerdote, nas campinas de Moabe, ao pé do Jordão de  Jericó, dizendo:

[[v4-26-4]]

^<<v4-26-4,4>>^ Conta  o povo da idade de vinte anos e para cima, como o Senhor ordenara a Moisés e aos filhos de Israel, que saíram do Egito.

[[v4-26-5]]

^<<v4-26-5,5>>^ Rúben, o primogênito de Israel; os filhos de Rúben foram  Enoque, do qual  era a família dos enoquitas: de Palu, a família dos paluítas;

[[v4-26-6]]

^<<v4-26-6,6>>^ De Hezrom, a família dos hezronitas; de Carmi, a família dos carmitas:

[[v4-26-7]]

^<<v4-26-7,7>>^ Estas são  as famílias dos rubenitas: e os que foram  deles contados, foram quarenta e três mil e setecentos e trinta.

[[v4-26-8]]

^<<v4-26-8,8>>^ E os filhos de Palu, Eliabe:

[[v4-26-9]]

^<<v4-26-9,9>>^ E os filhos de Eliabe, Nemuel, e Datã, e Abirão; estes, Datã e Abirão, foram  os chamados da congregação, que moveram a contenda contra Moisés e contra Aarão na congregação de Coré, quando moveram a contenda contra o Senhor;

[[v4-26-10]]

^<<v4-26-10,10>>^ E a terra abriu a sua boca, e os tragou com Coré, quando morreu a congregação: quando o fogo consumiu duzentos e cinquenta homens, e foram por sinal.

[[v4-26-11]]

^<<v4-26-11,11>>^ Mas os filhos de Coré não morreram.

[[v4-26-12]]

^<<v4-26-12,12>>^ Os filhos de Simeão, segundo as suas famílias: de Nemuel, a família dos nemuelitas: de Jamim, a família dos jaminitas; de Jaquim, a família dos jaquinitas.

[[v4-26-13]]

^<<v4-26-13,13>>^ De Zerá, a família dos zeraítas: de Saul, a família dos saulitas.

[[v4-26-14]]

^<<v4-26-14,14>>^ Estas são  as famílias dos simeonitas vinte e dois mil e duzentos.

[[v4-26-15]]

^<<v4-26-15,15>>^ Os filhos de Gade, segundo as suas gerações: de Zefom, a família dos zefonitas: de Hagi, a família dos hagitas: de Suni, a família dos sunitas:

[[v4-26-16]]

^<<v4-26-16,16>>^ De Ozni, a família dos oznitas: de Heri, a família dos heritas:

[[v4-26-17]]

^<<v4-26-17,17>>^ De Arode, a família dos aroditas: de Areli, a família dos arelitas.

[[v4-26-18]]

^<<v4-26-18,18>>^ Estas são  as famílias dos filhos de Gade, segundo os que foram  deles contados, quarenta mil e quinhentos.

[[v4-26-19]]

^<<v4-26-19,19>>^ Os filhos de Judá, Er e Onã mas Er e Onã morreram na terra de Canaã.

[[v4-26-20]]

^<<v4-26-20,20>>^ Assim os filhos de Judá foram segundo as suas famílias: de Selá a família dos selanitas: de Perez, a família dos Perezitas: de Zerá, a família dos zeraítas.

[[v4-26-21]]

^<<v4-26-21,21>>^ E os filhos de Perez foram: de Hezrom, a família dos hezronitas: de Hamul, a família dos hamulitas.

[[v4-26-22]]

^<<v4-26-22,22>>^ Estas são  as famílias de Judá, segundo os que foram  deles contados, setenta e seis mil e quinhentos.

[[v4-26-23]]

^<<v4-26-23,23>>^ Os filhos de Issacar, segundo as suas famílias, foram : de Tola, a família dos tolaítas: de Puva, a família dos puvitas,

[[v4-26-24]]

^<<v4-26-24,24>>^ De Jasube a família dos jasubitas: de Sinrom, a família dos sinronitas.

[[v4-26-25]]

^<<v4-26-25,25>>^ Estas são  as famílias de Issacar, segundo os que foram  deles contados, sessenta e quatro mil e trezentos.

[[v4-26-26]]

^<<v4-26-26,26>>^ Os filhos de Zebulom, segundo as suas famílias, foram : de Serede, a família dos sereditas: de Elom, a família dos elonitas: de Jaleel, a família dos jaleelitas.

[[v4-26-27]]

^<<v4-26-27,27>>^ Estas são  as famílias dos zebulonitas, segundo os que foram  deles contados, sessenta mil e quinhentos.

[[v4-26-28]]

^<<v4-26-28,28>>^ Os filhos de José segundo as suas famílias, foram  Manassés e Efraim.

[[v4-26-29]]

^<<v4-26-29,29>>^ Os filhos de Manassés foram : de Maquir, a família dos maquiritas: e Maquir gerou a Gileade: de Gileade, a família dos gileaditas.

[[v4-26-30]]

^<<v4-26-30,30>>^ Estes são  os filhos de Gileade: de  Jezer, a família dos jezeritas: de Heleque, a família dos helequitas:

[[v4-26-31]]

^<<v4-26-31,31>>^ E de Asriel, a família dos asrielitas: e de Sequém, a família dos sequenitas:

[[v4-26-32]]

^<<v4-26-32,32>>^ E de  Semida, a família dos semidaítas: e de Hefer, a família dos heferitas.

[[v4-26-33]]

^<<v4-26-33,33>>^ Porém Selofade, filho de Hefer não tinha filhos, senão filhas: e os nomes das filhas de Selofade foram  Macla, Noa, Hogla, Milca e Tirzá.

[[v4-26-34]]

^<<v4-26-34,34>>^ Estas são  as famílias de Manassés: e os que foram  deles contados, foram  cinquenta e dois mil e setecentos.

[[v4-26-35]]

^<<v4-26-35,35>>^ Estes são  os filhos de Efraim, segundo as suas famílias: de Sutela, a família dos sutelaítas: de Bequer, a família dos bequeritas: de Taã, a família dos taanitas.

[[v4-26-36]]

^<<v4-26-36,36>>^ E estes são  os filhos de Sutela: de Erã, a família dos eranitas.

[[v4-26-37]]

^<<v4-26-37,37>>^ Estas são  as famílias dos filhos de Efraim, segundo os que foram  deles contados, trinta e dois mil e quinhentos: estes são  os filhos de José, segundo as suas famílias.

[[v4-26-38]]

^<<v4-26-38,38>>^ Os filhos de Benjamim, segundo as suas famílias: de Bela, a família dos belaítas: de Asbel, a família dos asbelitas: de Airão, a família dos airamitas;

[[v4-26-39]]

^<<v4-26-39,39>>^ De Sufão, a família dos sufamitas: de Hufão, a família dos hufamitas.

[[v4-26-40]]

^<<v4-26-40,40>>^ E os filhos de Bela foram Arde e Naamã: de Arde  a família dos arditas: de Naamã a família dos naamanitas.

[[v4-26-41]]

^<<v4-26-41,41>>^ Estes são  os filhos de Benjamim, segundo as suas famílias: e os que foram  deles contados, foram  quarenta e cinco mil e seiscentos.

[[v4-26-42]]

^<<v4-26-42,42>>^ Estes são  os filhos de Dã, segundo as suas famílias: de Suão a família dos suamitas: estas são  as famílias de Dã, segundo as suas famílias.

[[v4-26-43]]

^<<v4-26-43,43>>^ Todas as famílias dos suamitas, segundo os que foram  deles contados, foram  sessenta e quatro mil e quatrocentos.

[[v4-26-44]]

^<<v4-26-44,44>>^ Os filhos de Aser, segundo as suas famílias, foram : de Imná, a família dos imnaítas: de Isvi, a família dos isvitas, de Beria, a família dos beriítas.

[[v4-26-45]]

^<<v4-26-45,45>>^ Dos filhos de Beria, foram : de Héber, a família dos heberitas; de Malquiel, a família dos malquielitas.

[[v4-26-46]]

^<<v4-26-46,46>>^ E o nome da filha de Aser foi  Sera.

[[v4-26-47]]

^<<v4-26-47,47>>^ Estas são  as famílias dos filhos de Aser, segundo os que foram  deles contados, cinquenta e três mil e quatrocentos.

[[v4-26-48]]

^<<v4-26-48,48>>^ Os filhos de Naftali, segundo as suas famílias: de Jazeel, a família dos jazeelitas: de Guni, a família dos gunitas:

[[v4-26-49]]

^<<v4-26-49,49>>^ De Jezer, a família dos jezeritas: de Silém, a família dos silemitas.

[[v4-26-50]]

^<<v4-26-50,50>>^ Estas são  as famílias de Naftali, segundo as suas famílias e os que foram  deles contados, foram  quarenta e cinco mil e quatrocentos.

[[v4-26-51]]

^<<v4-26-51,51>>^ Estes são  os contados dos filhos de Israel, seiscentos e um mil e setecentos e trinta.

[[v4-26-52]]

^<<v4-26-52,52>>^ E falou o Senhor a Moisés, dizendo:

[[v4-26-53]]

^<<v4-26-53,53>>^ A estes se repartirá a terra em herança, segundo o número dos nomes.

[[v4-26-54]]

^<<v4-26-54,54>>^ Aos muitos multiplicarás a sua herança, e aos poucos diminuirás a sua herança: a cada qual se dará a sua herança, segundo os que foram  deles contados.

[[v4-26-55]]

^<<v4-26-55,55>>^ Todavia a terra se repartirá por sortes: segundo os nomes das tribos de seus pais a herdarão.

[[v4-26-56]]

^<<v4-26-56,56>>^ Segundo sair  a sorte, se repartirá a herança deles entre os muitos e poucos.

[[v4-26-57]]

^<<v4-26-57,57>>^ E estes são  os que foram  contados de Levi, segundo as suas famílias: de Gérson, a família dos gersonitas: de Coate, a família dos coatitas; de Merari, a família dos meraritas.

[[v4-26-58]]

^<<v4-26-58,58>>^ Estas são  as famílias de Levi: a família dos libnitas, a família dos hebronitas, a família dos malitas, a família dos musitas, a família dos coreítas: e Coate gerou a Anrão.

[[v4-26-59]]

^<<v4-26-59,59>>^ E o nome da mulher de Anrão foi  Joquebede, filha de Levi, a qual nasceu a Levi no Egito; e esta a Anrão gerou Aarão, e Moisés, e Miriã, sua irmã.

[[v4-26-60]]

^<<v4-26-60,60>>^ E a Aarão nasceram Nadabe, Abiú, Eleazar e Itamar.

[[v4-26-61]]

^<<v4-26-61,61>>^ Porém Nadabe e Abiú morreram quando trouxeram fogo estranho perante o Senhor.

[[v4-26-62]]

^<<v4-26-62,62>>^ E os que foram  deles contados foram vinte e três mil, todo o varão da idade de um mês e para cima: porque estes não foram contados entre os filhos de Israel, porquanto lhes não foi dada herança entre os filhos de Israel.

[[v4-26-63]]

^<<v4-26-63,63>>^ Estes são  os que foram  contados por Moisés e Eleazar, o sacerdote, que contaram os filhos de Israel nas campinas de Moabe, ao pé do Jordão de  Jericó.

[[v4-26-64]]

^<<v4-26-64,64>>^ E entre estes nenhum houve dos que foram  contados por Moisés e Aarão, o sacerdote, quando contaram aos filhos de Israel no deserto de Sinai.

[[v4-26-65]]

^<<v4-26-65,65>>^ Porque o Senhor dissera deles que certamente morreriam no deserto: e nenhum deles ficou, senão Calebe, filho de Jefoné, e Josué, filho de Num.

'''

xref:004-numeros/004-numeros-025.adoc#v4-25-0[&#60; Capítulo Anterior] | <<v4-26-0,Topo>> | xref:004-numeros/004-numeros-027.adoc#v4-27-0[Próximo Capítulo &#62;]