include::./index.adoc[]

[[v4-6-0]]
=== Números, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-6-1]]

^<<v4-6-1,1>>^ E FALOU o Senhor a Moisés, dizendo:

[[v4-6-2]]

^<<v4-6-2,2>>^ Fala aos filhos de Israel, e dize-lhes: Quando um homem ou mulher se tiver separado, fazendo voto de nazireu, para se separar para o Senhor,

[[v4-6-3]]

^<<v4-6-3,3>>^ de vinho e de bebida forte se apartará: vinagre de vinho, ou vinagre de bebida forte não beberá; nem beberá alguma beberagem de uvas; nem uvas frescas nem secas comerá.

[[v4-6-4]]

^<<v4-6-4,4>>^ Todos os dias do seu nazireado não comerá de cousa alguma, que se faz da vinha, desde os caroços até às cascas.

[[v4-6-5]]

^<<v4-6-5,5>>^ Todos os dias do voto do seu nazireado sobre a sua cabeça não passará navalha: até que se cumpram os dias, que se separou para o Senhor, santo será, deixando crescer as guedelhas do cabelo da sua cabeça.

[[v4-6-6]]

^<<v4-6-6,6>>^ Todos os dias que se separar para o Senhor não se chegará a corpo dum morto.

[[v4-6-7]]

^<<v4-6-7,7>>^ Por seu pai, ou por sua mãe, por seu irmão, ou por sua irmã, por eles se não contaminará, quando forem mortos; porquanto o nazireado do seu Deus está  sobre a sua cabeça.

[[v4-6-8]]

^<<v4-6-8,8>>^ Todos os dias do seu nazireado santo será ao Senhor.

[[v4-6-9]]

^<<v4-6-9,9>>^ E se alguém vier a morrer junto a ele por acaso, subitamente, e contaminar a cabeça do seu nazireado, então no dia da sua purificação rapará a sua cabeça, e ao sétimo dia a rapará.

[[v4-6-10]]

^<<v4-6-10,10>>^ E ao oitavo dia trará duas rolas, ou dois pombinhos, ao sacerdote, à porta da tenda da congregação:

[[v4-6-11]]

^<<v4-6-11,11>>^ E o sacerdote oferecerá um para expiação do pecado, e o outro para holocausto; e fará propiciação por esse que pecou no corpo morto: assim naquele mesmo dia santificará a sua cabeça.

[[v4-6-12]]

^<<v4-6-12,12>>^ Então separará os dias do seu nazireado ao Senhor, e para expiação da culpa trará um cordeiro dum ano: e os dias antecedentes serão perdidos, porquanto o seu nazireado foi contaminado.

[[v4-6-13]]

^<<v4-6-13,13>>^ E esta é  a lei do nazireu: no dia em que se cumprirem os dias do seu nazireado, trá-lo-ão à porta da tenda da congregação:

[[v4-6-14]]

^<<v4-6-14,14>>^ E ele oferecerá a sua oferta ao Senhor, um cordeiro sem mancha dum ano em holocausto, e uma cordeira sem mancha de um ano para expiação da culpa, e um carneiro sem mancha por oferta pacífica;

[[v4-6-15]]

^<<v4-6-15,15>>^ E um cesto de bolos  asmos, bolos de  flor de farinha com azeite, amassados, e coscorões asmos untados com azeite, como também a sua oferta de manjares, e as suas libações.

[[v4-6-16]]

^<<v4-6-16,16>>^ E o sacerdote os trará perante o Senhor, e sacrificará a sua expiação do pecado, e o seu holocausto:

[[v4-6-17]]

^<<v4-6-17,17>>^ Também sacrificará o carneiro em sacrifício pacífico ao Senhor, com o cesto dos bolos  asmos: e o sacerdote oferecerá a sua oferta de manjares, e a sua libação.

[[v4-6-18]]

^<<v4-6-18,18>>^ Então o nazireu à porta da tenda da congregação rapará a cabeça do seu nazireado, e tomará o cabelo da cabeça do seu nazireado, e o porá sobre o fogo que está  debaixo do sacrifício pacífico.

[[v4-6-19]]

^<<v4-6-19,19>>^ Depois o sacerdote tomará a espádua cozida do carneiro, e um bolo asmo do cesto, e um coscorão asmo, e os porá nas mãos do nazireu, depois de haver rapado a cabeça do seu nazireado.

[[v4-6-20]]

^<<v4-6-20,20>>^ E o sacerdote os moverá em  oferta de movimento perante o Senhor; isto é santo para o sacerdote, juntamente com o peito da oferta de movimento, e com a espádua da oferta alçada; e depois o nazireu pode beber vinho.

[[v4-6-21]]

^<<v4-6-21,21>>^ Esta é  a lei do nazireu, que fizer voto da sua oferta ao Senhor pelo seu nazireado, além do que alcançar a sua mão: segundo o seu voto, que fizer, assim fará conforme à lei do seu nazireado.

[[v4-6-22]]

^<<v4-6-22,22>>^ E falou o Senhor a Moisés, dizendo:

[[v4-6-23]]

^<<v4-6-23,23>>^ Fala a Aarão, e a seus filhos, dizendo: Assim abençoareis os filhos de Israel, dizendo-lhes:

[[v4-6-24]]

^<<v4-6-24,24>>^ O Senhor te abençoe e te guarde:

[[v4-6-25]]

^<<v4-6-25,25>>^ O Senhor faça resplandecer o seu rosto sobre ti, e tenha misericórdia de ti.

[[v4-6-26]]

^<<v4-6-26,26>>^ O Senhor sobre ti levante o seu rosto, e te dê a paz.

[[v4-6-27]]

^<<v4-6-27,27>>^ Assim porão o meu nome sobre os filhos de Israel, e eu os abençoarei.

'''

xref:004-numeros/004-numeros-005.adoc#v4-5-0[&#60; Capítulo Anterior] | <<v4-6-0,Topo>> | xref:004-numeros/004-numeros-007.adoc#v4-7-0[Próximo Capítulo &#62;]