include::./index.adoc[]

[[v4-16-0]]
=== Números, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v4-16-1]]

^<<v4-16-1,1>>^ E CORÉ, filho de Jizar, filho de Coate, filho de Levi, tomou consigo a Datã e a Abirão, filhos de Eliabe, e a Om, filho de Pelete, filhos de Rúben,

[[v4-16-2]]

^<<v4-16-2,2>>^ E levantaram-se perante Moisés com duzentos e cinquenta homens dos filhos de Israel, maiorais da congregação, chamados ao ajuntamento, varões de nome.

[[v4-16-3]]

^<<v4-16-3,3>>^ E se congregaram contra Moisés e contra Aarão, e lhes disseram: Demais é já, pois que toda a congregação é santa, todos eles são  santos, e o Senhor está  no meio deles: por que pois vos elevais sobre a congregação do Senhor?

[[v4-16-4]]

^<<v4-16-4,4>>^ Como Moisés isto ouviu, caiu sobre o seu rosto,

[[v4-16-5]]

^<<v4-16-5,5>>^ E falou a Coré e a toda a sua congregação, dizendo: Amanhã  pela manhã o Senhor fará saber quem é  seu, e quem  o santo que ele fará chegar a si: e aquele a quem escolher fará chegar a si.

[[v4-16-6]]

^<<v4-16-6,6>>^ Fazei isto: Tomai vós incensários, Coré e toda a sua congregação;

[[v4-16-7]]

^<<v4-16-7,7>>^ E, pondo fogo neles amanhã, sobre eles deitai incenso perante o Senhor: e será que  o homem a quem o Senhor escolher este será  o santo: baste-vos, filhos de Levi.

[[v4-16-8]]

^<<v4-16-8,8>>^ Disse mais Moisés a Coré: Ouvi agora, filhos de Levi:

[[v4-16-9]]

^<<v4-16-9,9>>^ Porventura  pouco para vós é  que o Deus de Israel vos separou da congregação de Israel, para vos fazer chegar a si, a administrar o ministério do tabernáculo do Senhor e estar perante a congregação para ministrar-lhe:

[[v4-16-10]]

^<<v4-16-10,10>>^ E te fez chegar, e todos os teus irmãos, os filhos de Levi, contigo; ainda também procurais o sacerdócio?

[[v4-16-11]]

^<<v4-16-11,11>>^ Pelo que tu e toda a tua congregação congregados estais  contra o Senhor; e Aarão que é  ele, que murmurais contra ele?

[[v4-16-12]]

^<<v4-16-12,12>>^ E Moisés enviou a chamar a Datã e a Abirão, filhos de Eliabe: porém eles disseram: Não subiremos;

[[v4-16-13]]

^<<v4-16-13,13>>^ Porventura  pouco é  que nos fizeste subir de uma terra que mana leite e mel, para nos matares neste deserto, senão que também totalmente te assenhoreias de nós?

[[v4-16-14]]

^<<v4-16-14,14>>^ Nem tão pouco nos trouxeste a uma terra que mana leite e mel, nem nos deste campos e vinhas em herança; porventura  arrancarás os olhos a estes homens? não subiremos.

[[v4-16-15]]

^<<v4-16-15,15>>^ Então Moisés irou-se muito, e disse ao Senhor: Não atentes para a sua oferta; nem um só jumento tomei deles nem a nenhum deles fiz mal.

[[v4-16-16]]

^<<v4-16-16,16>>^ Disse mais Moisés a Coré: Tu e toda a tua congregação ponde-vos perante o Senhor, tu, e eles, e Aarão, amanhã.

[[v4-16-17]]

^<<v4-16-17,17>>^ E tomai cada um o seu incensário, e neles ponde incenso; e trazei cada um o seu incensário perante o Senhor, duzentos e cinquenta incensários; também tu e Aarão, cada qual o seu incensário.

[[v4-16-18]]

^<<v4-16-18,18>>^ Tomaram pois cada qual o seu incensário, e neles puseram fogo, e neles deitaram incenso, e se puseram perante a porta da tenda da congregação com Moisés e Aarão.

[[v4-16-19]]

^<<v4-16-19,19>>^ E Coré fez ajuntar contra eles toda a congregação à porta da tenda da congregação: então a glória do Senhor apareceu a toda a congregação.

[[v4-16-20]]

^<<v4-16-20,20>>^ E falou o Senhor a Moisés e a Aarão, dizendo:

[[v4-16-21]]

^<<v4-16-21,21>>^ Apartai-vos do meio desta congregação, e os consumirei como num momento.

[[v4-16-22]]

^<<v4-16-22,22>>^ Mas eles se prostraram sobre os seus rostos, e disseram: Ó Deus, Deus dos espíritos de toda a carne, pecará um só homem, e indignar-te-ás tu tanto contra toda esta congregação?

[[v4-16-23]]

^<<v4-16-23,23>>^ E falou o Senhor a Moisés, dizendo:

[[v4-16-24]]

^<<v4-16-24,24>>^ Fala a toda esta congregação, dizendo: Levantai-vos do redor da habitação de Coré, Datã e Abirão.

[[v4-16-25]]

^<<v4-16-25,25>>^ Então Moisés levantou-se, e foi a Datã e a Abirão: e após ele foram os anciãos de Israel.

[[v4-16-26]]

^<<v4-16-26,26>>^ E falou à congregação, dizendo: Desviai-vos, peço-vos, das tendas destes ímpios homens, e não toqueis nada do que é seu, para que porventura  não pereçais em todos os seus pecados.

[[v4-16-27]]

^<<v4-16-27,27>>^ Levantaram-se pois do redor da habitação de Coré, Datã e Abirão. E Datã e Abirão saíram, e se puseram à porta das suas tendas, juntamente com as suas mulheres, e seus filhos, e suas crianças.

[[v4-16-28]]

^<<v4-16-28,28>>^ Então disse Moisés: Nisto conhecereis que o Senhor me enviou a fazer todos estes feitos, que de meu coração não procedem.

[[v4-16-29]]

^<<v4-16-29,29>>^ Se estes morrerem como morrem todos os homens, e se forem visitados como se visitam todos os homens, então  o Senhor me não enviou.

[[v4-16-30]]

^<<v4-16-30,30>>^ Mas, se o Senhor criar alguma cousa nova, e a terra abrir a sua boca e os tragar com tudo o que é  seu, e vivos descerem ao sepulcro, então conhecereis que estes homens irritaram ao Senhor.

[[v4-16-31]]

^<<v4-16-31,31>>^ E aconteceu que, acabando ele de falar todas estas palavras, a terra que estava  debaixo deles se fendeu.

[[v4-16-32]]

^<<v4-16-32,32>>^ E a terra abriu a sua boca, e os tragou com as suas casas, como também a todos os homens que pertenciam  a Coré, e a toda a sua fazenda.

[[v4-16-33]]

^<<v4-16-33,33>>^ E eles e tudo o que era  seu desceram vivos ao sepulcro, e a terra os cobriu, e pereceram do meio da congregação.

[[v4-16-34]]

^<<v4-16-34,34>>^ E todo o Israel, que estava ao  redor deles, fugiu do clamor deles; porque diziam: Para que porventura também  nos não trague a terra a nós.

[[v4-16-35]]

^<<v4-16-35,35>>^ Então saiu fogo do Senhor, e consumiu os duzentos e cinquenta homens que ofereciam o incenso.

[[v4-16-36]]

^<<v4-16-36,36>>^ E falou o Senhor a Moisés, dizendo:

[[v4-16-37]]

^<<v4-16-37,37>>^ Dize a Eleazar, filho de Aarão, o sacerdote, que tome os incensários do meio do incêndio, e espalhe o fogo longe, porque santos são;

[[v4-16-38]]

^<<v4-16-38,38>>^ Quanto aos incensários daqueles que pecaram contra as suas almas, deles se façam folhas estendidas para  cobertura do altar; porquanto os trouxeram perante o Senhor; pelo que santos são: e serão por sinal aos filhos de Israel.

[[v4-16-39]]

^<<v4-16-39,39>>^ E Eleazar, o sacerdote, tomou os incensários de metal, que trouxeram aqueles que foram  queimados, e os estenderam para  cobertura do altar,

[[v4-16-40]]

^<<v4-16-40,40>>^ Por  memorial para os filhos de Israel, para que nenhum estranho, que não for da semente de Aarão, se chegue para acender incenso perante o Senhor; para que não seja como Coré e a sua congregação como o Senhor lhe tinha dito pela boca de Moisés.

[[v4-16-41]]

^<<v4-16-41,41>>^ Mas no dia seguinte toda a congregação dos filhos de Israel murmurou contra Moisés e contra Aarão, dizendo: Vós matastes o povo do Senhor.

[[v4-16-42]]

^<<v4-16-42,42>>^ E aconteceu que, ajuntando-se a congregação contra Moisés e Aarão, e virando-se para a tenda da congregação, eis que a nuvem a cobriu, e a glória do Senhor apareceu.

[[v4-16-43]]

^<<v4-16-43,43>>^ Vieram pois Moisés e Aarão perante a tenda da congregação.

[[v4-16-44]]

^<<v4-16-44,44>>^ Então falou o Senhor a Moisés, dizendo:

[[v4-16-45]]

^<<v4-16-45,45>>^ Levantai-vos do meio desta congregação, e a consumirei como num momento: então se prostraram sobre os seus rostos,

[[v4-16-46]]

^<<v4-16-46,46>>^ E disse Moisés a Aarão: Toma o teu incensário, e põe nele fogo do altar, e deita incenso sobre ele, e vai depressa à congregação, e faze expiação por eles: porque grande indignação saiu de diante do Senhor; já começou a praga.

[[v4-16-47]]

^<<v4-16-47,47>>^ E tomou-o Aarão, como Moisés tinha falado, e correu ao meio da congregação; e eis que já a praga havia começado entre o povo; e deitou incenso nele, e fez expiação pelo povo.

[[v4-16-48]]

^<<v4-16-48,48>>^ E estava em pé entre os mortos e os vivos; e cessou a praga.

[[v4-16-49]]

^<<v4-16-49,49>>^ E os que morreram daquela praga foram catorze mil e setecentos, fora os que morreram por causa de Coré.

[[v4-16-50]]

^<<v4-16-50,50>>^ E voltou Aarão a Moisés à porta da tenda da congregação: e cessou a praga.

'''

xref:004-numeros/004-numeros-015.adoc#v4-15-0[&#60; Capítulo Anterior] | <<v4-16-0,Topo>> | xref:004-numeros/004-numeros-017.adoc#v4-17-0[Próximo Capítulo &#62;]