include::./index.adoc[]

[[v11-15-0]]
=== 1 Reis, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v11-15-1]]

^<<v11-15-1,1>>^ E NO décimo oitavo ano do rei Jeroboão, filho de Nebate, Abião começou a reinar sobre Judá.

[[v11-15-2]]

^<<v11-15-2,2>>^ E três anos reinou em Jerusalém: e era  o nome de sua mãe Maaca, filha de Abisalom.

[[v11-15-3]]

^<<v11-15-3,3>>^ E andou em todos os pecados que seu pai tinha cometido antes dele: e seu coração não foi perfeito para com o Senhor seu Deus como o coração de Davi, seu pai.

[[v11-15-4]]

^<<v11-15-4,4>>^ Mas por amor de Davi o Senhor lhe deu uma lâmpada em Jerusalém, levantando a seu filho depois dele, e confirmando a Jerusalém.

[[v11-15-5]]

^<<v11-15-5,5>>^ Porquanto Davi tinha feito o que parecia  reto aos olhos do Senhor, e não se tinha desviado de tudo o que lhe ordenara em  todos os dias da sua vida, senão só no negócio de Urias, o heteu.

[[v11-15-6]]

^<<v11-15-6,6>>^ E houve guerra entre Roboão e Jeroboão todos os dias da sua vida.

[[v11-15-7]]

^<<v11-15-7,7>>^ Quanto ao mais dos sucessos de Abião, e a tudo quanto fez, porventura  não está  escrito no livro das crônicas dos reis de Judá? Também houve guerra entre Abião e Jeroboão.

[[v11-15-8]]

^<<v11-15-8,8>>^ E Abião dormiu com seus pais, e o sepultaram na cidade de Davi: e Asa, seu filho, reinou em seu lugar.

[[v11-15-9]]

^<<v11-15-9,9>>^ E no vigésimo ano de Jeroboão, rei de Israel, começou Asa a reinar em Judá.

[[v11-15-10]]

^<<v11-15-10,10>>^ E quarenta e um anos reinou em Jerusalém: e era  o nome de sua mãe Maaca, filha de Abisalom.

[[v11-15-11]]

^<<v11-15-11,11>>^ E Asa fez o que parecia  reto aos olhos do Senhor, como Davi, seu pai.

[[v11-15-12]]

^<<v11-15-12,12>>^ Porque tirou da terra os rapazes escandalosos, e tirou todos os ídolos que seus pais fizeram.

[[v11-15-13]]

^<<v11-15-13,13>>^ E até a Maaca, sua mãe, removeu para que não fosse  rainha, porquanto tinha feito um horrível ídolo a Asera: também Asa desfez o seu ídolo horrível, e o queimou junto ao ribeiro de Cedrom.

[[v11-15-14]]

^<<v11-15-14,14>>^ Os altos porém se não tiraram: todavia foi o coração de Asa reto para com o Senhor todos os seus dias.

[[v11-15-15]]

^<<v11-15-15,15>>^ E à casa do Senhor trouxe as cousas consagradas de seu pai, e as cousas que ele mesmo consagrara: prata e ouro e vasos.

[[v11-15-16]]

^<<v11-15-16,16>>^ E houve guerra entre Asa e Baasa, rei de Israel, todos os seus dias.

[[v11-15-17]]

^<<v11-15-17,17>>^ Porque Baasa, rei de Israel, subiu contra Judá, e edificou a Ramá, para que a ninguém fosse permitido sair nem entrar junto a Asa, rei de Judá.

[[v11-15-18]]

^<<v11-15-18,18>>^ Então Asa tomou toda a prata e ouro que ficara  nos tesouros da casa do Senhor, e os tesouros da casa do rei, e os entregou nas mãos de seus servos: e o rei Asa os enviou a Benadade, filho de Tabrimom, filho de Heziom, rei da Síria, que habitava em Damasco, dizendo:

[[v11-15-19]]

^<<v11-15-19,19>>^ Aliança há  entre mim e ti, entre meu pai e teu pai: vês aqui que te mando um  presente, prata e ouro; vai, e  anula a tua aliança com Baasa, rei de Israel, para que se retire de sobre mim.

[[v11-15-20]]

^<<v11-15-20,20>>^ E Benadade deu ouvidos ao rei Asa, e enviou aos capitães dos exércitos que tinha contra as cidades de Israel: e feriu a Ijom, e a Dã, e a Abel, de Bete-Maaca e a toda a Quinerote, com toda a terra de Naftali.

[[v11-15-21]]

^<<v11-15-21,21>>^ E sucedeu que, ouvindo-o Baasa, deixou de edificar a Ramá: e ficou em Tirzá.

[[v11-15-22]]

^<<v11-15-22,22>>^ Então o rei Asa fez apregoar por toda a Judá que todos , sem exceção, trouxessem as pedras de Ramá, e a sua madeira com  que Baasa edificara: e com elas edificou o rei Asa a Geba de Benjamim e a Mizpá.

[[v11-15-23]]

^<<v11-15-23,23>>^ Quanto ao mais de todos os sucessos de Asa, e a todo o seu poder, e a tudo quanto fez, e as cidades que edificou, porventura  não está  escrito no livro das crônicas dos reis de Judá? Porém, no tempo da sua velhice, padeceu dos pés.

[[v11-15-24]]

^<<v11-15-24,24>>^ E Asa dormiu com seus pais, e foi sepultado com seus pais na cidade de Davi, seu pai; e Josafá, seu filho reinou em seu lugar.

[[v11-15-25]]

^<<v11-15-25,25>>^ E Nadabe, filho de Jeroboão, começou a reinar sobre Israel no ano segundo de Asa, rei de Judá; e reinou sobre Israel dois anos.

[[v11-15-26]]

^<<v11-15-26,26>>^ E fez o que parecia  mal aos olhos do Senhor: e andou nos caminhos de seu pai, e no seu pecado com que tinha feito pecar a Israel.

[[v11-15-27]]

^<<v11-15-27,27>>^ E conspirou contra ele Baasa, filho de Aías, da casa de Issacar, e feriu-o Baasa em Gibetom, que era  dos filisteus, quando Nadabe e todo o Israel cercavam a Gibetom.

[[v11-15-28]]

^<<v11-15-28,28>>^ E matou-o Baasa no ano terceiro de Asa, rei de Judá, e reinou em seu lugar.

[[v11-15-29]]

^<<v11-15-29,29>>^ E sucedeu pois que , reinando ele feriu a toda a casa de Jeroboão: nada de Jeroboão deixou que tivesse fôlego, até o destruir, conforme à palavra do Senhor que dissera pelo ministério de seu servo Aías, o silonita.

[[v11-15-30]]

^<<v11-15-30,30>>^ Por causa dos pecados de Jeroboão, o qual pecou, e fez pecar a Israel, e por causa da provocação com que provocara ao Senhor Deus de Israel.

[[v11-15-31]]

^<<v11-15-31,31>>^ Quanto ao mais dos sucessos de Nadabe, e a tudo quanto fez, porventura  não está  escrito no livro das crônicas dos reis de Israel?

[[v11-15-32]]

^<<v11-15-32,32>>^ E houve guerra entre Asa e Baasa, rei de Israel, todos os seus dias.

[[v11-15-33]]

^<<v11-15-33,33>>^ No ano terceiro de Asa, rei de Judá, Baasa, filho de Aías, começou a reinar sobre todo o Israel em Tirzá, e reinou  vinte e quatro anos.

[[v11-15-34]]

^<<v11-15-34,34>>^ E fez o que parecia  mal aos olhos do Senhor: e andou no caminho de Jeroboão e no seu pecado com que tinha feito pecar a Israel.

'''

xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[&#60; Capítulo Anterior] | <<v11-15-0,Topo>> | xref:011-1-reis/011-1-reis-016.adoc#v11-16-0[Próximo Capítulo &#62;]