include::./index.adoc[]

[[v11-18-0]]
=== 1 Reis, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v11-18-1]]

^<<v11-18-1,1>>^ E SUCEDEU que, depois  de muitos dias a palavra do Senhor veio a Elias no terceiro ano, dizendo: Vai, mostra-te a Acabe; porque darei chuva sobre a terra.

[[v11-18-2]]

^<<v11-18-2,2>>^ E foi Elias mostrar-se a Acabe: e a fome era  extrema em Samaria.

[[v11-18-3]]

^<<v11-18-3,3>>^ E Acabe chamou a Obadias, o mordomo: e Obadias temia muito ao Senhor,

[[v11-18-4]]

^<<v11-18-4,4>>^ Porque sucedeu que, destruindo Jezabel os profetas do Senhor, Obadias tomou cem profetas, e de cinquenta em cinquenta os escondeu, numa cova, e os sustentou com pão e água.

[[v11-18-5]]

^<<v11-18-5,5>>^ E dissera Acabe a Obadias: Vai pela terra a todas as fontes de água, e a todos os rios: pode ser que achemos erva, para que em vida conservemos os cavalos e mulas, e não estejamos privados dos animais.

[[v11-18-6]]

^<<v11-18-6,6>>^ E repartiram entre si a terra, para passarem por ela: Acabe foi à parte por um caminho, e Obadias também foi à parte por outro caminho.

[[v11-18-7]]

^<<v11-18-7,7>>^ Estando pois Obadias já em caminho, eis que Elias o encontrou; e, conhecendo-o ele, prostrou-se sobre o seu rosto e disse: És  tu o meu senhor Elias?

[[v11-18-8]]

^<<v11-18-8,8>>^ E disse-lhe ele : Eu sou : vai, e dize a teu senhor: Eis que aqui está  Elias.

[[v11-18-9]]

^<<v11-18-9,9>>^ Porém ele disse: Em  que pequei, para que entregues teu servo na mão de Acabe, para que me mate?

[[v11-18-10]]

^<<v11-18-10,10>>^ Vive o Senhor teu Deus, que não houve nação nem reino aonde o meu senhor não mandasse em busca de ti; e dizendo eles: Aqui  não está , então ajuramentava os reinos e as nações, se eles te não tinham achado.

[[v11-18-11]]

^<<v11-18-11,11>>^ E agora dizes tu: Vai, dize a teu senhor: Eis que aqui está  Elias.

[[v11-18-12]]

^<<v11-18-12,12>>^ E poderia ser que, apartando-me eu de ti, o Espírito do Senhor te tomasse, não sei para onde, e, vindo eu a dar as novas a Acabe, e não te achando ele, me mataria: porém eu, teu servo, temo ao Senhor desde a minha mocidade.

[[v11-18-13]]

^<<v11-18-13,13>>^ Porventura  não disseram a meu senhor o que fiz, quando Jezabel matava os profetas do Senhor, como escondi a cem homens dos profetas do Senhor, de cinquenta em cinquenta, numas covas, e os sustentei com pão e água?

[[v11-18-14]]

^<<v11-18-14,14>>^ E agora dizes tu: Vai, dize a teu senhor: Eis que aqui  está Elias: e me mataria.

[[v11-18-15]]

^<<v11-18-15,15>>^ E disse Elias: Vive o Senhor dos Exércitos, perante cuja face estou, que deveras hoje me mostrarei a ele.

[[v11-18-16]]

^<<v11-18-16,16>>^ Então foi Obadias encontrar-se com Acabe, e lho anunciou: e foi Acabe encontrar-se com Elias.

[[v11-18-17]]

^<<v11-18-17,17>>^ E sucedeu que, vendo Acabe a Elias, disse-lhe Acabe: És  tu o perturbador de Israel?

[[v11-18-18]]

^<<v11-18-18,18>>^ Então disse ele: Eu não tenho perturbado a Israel, mas tu e a casa de teu pai, porque deixastes os mandamentos do Senhor, e seguistes a Baalim.

[[v11-18-19]]

^<<v11-18-19,19>>^ Agora pois envia, ajunta a mim todo o Israel no monte Carmelo; como também os quatrocentos e cinquenta profetas de Baal e os quatrocentos profetas de Asera, que comem da mesa de Jezabel.

[[v11-18-20]]

^<<v11-18-20,20>>^ Então enviou Acabe a todos os filhos de Israel: e ajuntou os profetas no monte Carmelo.

[[v11-18-21]]

^<<v11-18-21,21>>^ Então Elias se chegou a todo o povo, e disse: Até quando coxeareis entre dois pensamentos? Se o Senhor é  Deus, segui-o; e se Baal, segui-o. Porém o povo lhe não respondeu nada.

[[v11-18-22]]

^<<v11-18-22,22>>^ Então disse Elias ao povo: Eu só fiquei por profeta do Senhor e os profetas de Baal são quatrocentos e cinquenta homens.

[[v11-18-23]]

^<<v11-18-23,23>>^ Deem-se-nos pois dois bezerros, e eles escolham para si um dos bezerros, e o dividam em pedaços, e o ponham sobre a lenha, porém não lhe  metam fogo, e eu prepararei o outro bezerro, e o porei sobre a lenha, e não lhe  meterei fogo.

[[v11-18-24]]

^<<v11-18-24,24>>^ Então invocai o nome do vosso deus, e eu invocarei o nome do Senhor: e há de ser que  o deus que responder por fogo esse será Deus. E todo o povo respondeu, e disseram: É  boa esta palavra.

[[v11-18-25]]

^<<v11-18-25,25>>^ E disse Elias aos profetas de Baal: Escolhei para vós um dos bezerros, e preparai-o primeiro, porque sois muitos, e invocai o nome do vosso deus, e não lhe  metais fogo.

[[v11-18-26]]

^<<v11-18-26,26>>^ E tomaram o bezerro que lhes dera, e o prepararam; e invocaram o nome de Baal, desde a manhã até ao meio-dia, dizendo: Ah! Baal, responde-nos! Porém nem havia  voz, nem quem respondesse: e saltavam sobre o altar que se tinha feito.

[[v11-18-27]]

^<<v11-18-27,27>>^ E sucedeu que ao meio-dia Elias zombava deles, e dizia: Clamai em altas vozes, porque ele é um  deus; pode ser  que esteja falando, ou que tenha alguma  cousa que fazer, ou que intente alguma  viagem; porventura dorme, e despertará.

[[v11-18-28]]

^<<v11-18-28,28>>^ E eles clamavam a grandes vozes, e se retalhavam com facas e com lancetas, conforme ao seu costume, até derramarem sangue sobre si.

[[v11-18-29]]

^<<v11-18-29,29>>^ E sucedeu que, passado o meio-dia, profetizaram eles, até que a oferta de manjares se oferecesse: porém não houve  voz, nem resposta, nem atenção alguma,

[[v11-18-30]]

^<<v11-18-30,30>>^ Então Elias disse a todo o povo: Chegai-vos a mim. E todo o povo se chegou a ele; e reparou o altar do Senhor, que estava  quebrado.

[[v11-18-31]]

^<<v11-18-31,31>>^ E Elias tomou doze pedras, conforme ao número das tribos dos filhos de Jacó, ao qual veio a palavra do Senhor, dizendo: Israel será o teu nome.

[[v11-18-32]]

^<<v11-18-32,32>>^ E com aquelas pedras edificou o altar em nome do Senhor: depois fez um rego em redor do altar, segundo a largura de duas medidas de semente.

[[v11-18-33]]

^<<v11-18-33,33>>^ Então armou a lenha, e dividiu o bezerro em pedaços, e o pôs sobre a lenha,

[[v11-18-34]]

^<<v11-18-34,34>>^ E disse: Enchei de água quatro cântaros, e derramai-a sobre o holocausto e sobre a lenha. E disse: Fazei-o segunda vez: e o fizeram segunda vez. Disse ainda: Fazei-o terceira vez: e o fizeram terceira vez:

[[v11-18-35]]

^<<v11-18-35,35>>^ De maneira que a água corria ao redor do altar: e ainda até o rego encheu de água.

[[v11-18-36]]

^<<v11-18-36,36>>^ Sucedeu pois que, oferecendo-se a oferta de manjares, o profeta Elias se chegou, e disse: Ó Senhor, Deus de Abraão, de Isaque e de Israel, manifeste-se hoje que tu és  Deus em Israel, e que  eu sou  teu servo, e que  conforme à tua palavra fiz todas estas cousas.

[[v11-18-37]]

^<<v11-18-37,37>>^ Responde-me, Senhor, responde-me, para que este povo conheça que tu, Senhor, és  Deus, e que  tu fizeste tornar o seu coração para trás.

[[v11-18-38]]

^<<v11-18-38,38>>^ Então caiu fogo do Senhor, e consumiu o holocausto, e a lenha, e as pedras, e o pó, e ainda  lambeu a água que estava  no rego.

[[v11-18-39]]

^<<v11-18-39,39>>^ O que vendo todo o povo, caíram sobre os seus rostos, e disseram: Só  o Senhor é  Deus! Só  o Senhor é  Deus!

[[v11-18-40]]

^<<v11-18-40,40>>^ E Elias lhes disse: Lançai mão dos profetas de Baal, que nenhum deles escape. E lançaram mão deles: e Elias os fez descer ao ribeiro de Quisom, e ali os matou.

[[v11-18-41]]

^<<v11-18-41,41>>^ Então disse Elias a Acabe: Sobe, come e bebe, porque ruído há duma  abundante chuva.

[[v11-18-42]]

^<<v11-18-42,42>>^ E Acabe subiu a comer e a beber: mas Elias subiu ao cume do Carmelo, e se inclinou por terra, e meteu o seu rosto entre os seus joelhos.

[[v11-18-43]]

^<<v11-18-43,43>>^ E disse ao seu moço: sobe agora, e olha para a banda do mar. E subiu, e olhou, e disse: Não há  nada. Então disse ele: Torna lá  sete vezes.

[[v11-18-44]]

^<<v11-18-44,44>>^ E sucedeu que, à sétima vez, disse: Eis aqui uma pequena nuvem, como a mão dum homem, subindo do mar. Então disse ele: Sobe, e dize a Acabe: Aparelha o teu  carro, e desce, para que a chuva te não apanhe.

[[v11-18-45]]

^<<v11-18-45,45>>^ E sucedeu que, entretanto, os céus se enegreceram com nuvens e vento, e veio uma grande chuva: e Acabe subiu ao carro, e foi para Jezreel.

[[v11-18-46]]

^<<v11-18-46,46>>^ E a mão do Senhor estava sobre Elias, o qual cingiu os lombos, e veio correndo perante Acabe, até à entrada de Jezreel.

'''

xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[Próximo Capítulo &#62;]