include::./index.adoc[]

[[v11-3-0]]
=== 1 Reis, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v11-3-1]]

^<<v11-3-1,1>>^ E SALOMÃO se aparentou com Faraó, rei do Egito: e tomou a filha de Faraó, e a trouxe à cidade de Davi, até que acabasse de edificar a sua casa, e a casa do Senhor, e a muralha de Jerusalém em roda.

[[v11-3-2]]

^<<v11-3-2,2>>^ Somente que  o povo sacrificava sobre os altos: porque até àqueles dias ainda  se não tinha edificado casa ao nome do Senhor.

[[v11-3-3]]

^<<v11-3-3,3>>^ E Salomão amava ao Senhor, andando nos estatutos de Davi seu pai; somente que  nos altos sacrificava, e queimava incenso.

[[v11-3-4]]

^<<v11-3-4,4>>^ E foi o rei a Gibeom para lá sacrificar, porque aquele era o alto grande; mil holocaustos sacrificou Salomão naquele altar.

[[v11-3-5]]

^<<v11-3-5,5>>^ E em Gibeom apareceu o Senhor a Salomão de noite em sonhos: e diz-lhe Deus: Pede o que quiseres  que te dê.

[[v11-3-6]]

^<<v11-3-6,6>>^ E disse Salomão: De grande beneficência usaste tu com teu servo Davi meu pai, como também  ele andou contigo em verdade, e em justiça, e em retidão de coração, perante a tua face: e guardaste-lhe esta grande beneficência, e lhe deste um  filho que se assentasse no seu trono, como se vê  neste dia.

[[v11-3-7]]

^<<v11-3-7,7>>^ Agora pois, ó Senhor meu Deus, tu fizeste reinar a teu servo em lugar de Davi meu pai: e sou ainda  menino pequeno; nem sei como sair, nem como entrar.

[[v11-3-8]]

^<<v11-3-8,8>>^ E teu servo está no meio do teu povo que elegeste: povo grande, que nem se pode contar, nem numerar, pela sua multidão.

[[v11-3-9]]

^<<v11-3-9,9>>^ A teu servo pois dá um coração entendido para julgar a teu povo, para que prudentemente discirna entre o bem e o mal: porque quem poderia julgar a este teu tão  grande povo?

[[v11-3-10]]

^<<v11-3-10,10>>^ E esta palavra pareceu  boa aos olhos do Senhor, que Salomão pedisse esta cousa.

[[v11-3-11]]

^<<v11-3-11,11>>^ E disse-lhe Deus: Porquanto pediste esta cousa, e não pediste para ti riquezas, nem pediste a vida de teus inimigos: mas pediste para ti entendimento, para ouvir causas de  juízo;

[[v11-3-12]]

^<<v11-3-12,12>>^ Eis que fiz segundo as tuas palavras: eis que te dei um coração tão  sábio e entendido, que antes de ti teu igual não houve, e depois de ti teu igual se não levantará.

[[v11-3-13]]

^<<v11-3-13,13>>^ E também até o que não pediste te dei, assim riquezas como glória: que não haja teu igual entre os reis, por todos os teus dias.

[[v11-3-14]]

^<<v11-3-14,14>>^ E, se andares nos meus caminhos guardando os meus estatutos, e os meus mandamentos, como andou Davi teu pai, também prolongarei os teus dias.

[[v11-3-15]]

^<<v11-3-15,15>>^ E acordou Salomão, e eis que era  sonho. E veio a Jerusalém, e pôs-se perante a arca do concerto do Senhor, e, sacrificou holocaustos, e preparou sacrifícios pacíficos, e fez um banquete a todos os seus servos.

[[v11-3-16]]

^<<v11-3-16,16>>^ Então vieram duas mulheres prostitutas ao rei, e se puseram perante ele.

[[v11-3-17]]

^<<v11-3-17,17>>^ E disse-lhe uma das mulheres: Ah! senhor meu, eu e esta mulher moramos numa casa; e tive um filho, morando  com ela naquela casa.

[[v11-3-18]]

^<<v11-3-18,18>>^ E sucedeu que, ao terceiro dia depois do meu parto, também esta mulher teve um filho: estávamos juntas, estranho nenhum estava  conosco na casa, senão nós ambas naquela casa.

[[v11-3-19]]

^<<v11-3-19,19>>^ E de noite morreu o filho desta mulher, porquanto se deitara sobre ele.

[[v11-3-20]]

^<<v11-3-20,20>>^ E levantou-se à meia-noite e me tirou a meu filho do meu lado, dormindo a tua serva, e o deitou no seu seio: e a seu filho morto deitou no meu seio.

[[v11-3-21]]

^<<v11-3-21,21>>^ E, levantando-me eu pela manhã, para dar de mamar a meu filho, eis que estava morto: mas, atentando pela manhã para ele, eis que não era o filho, que eu havia tido.

[[v11-3-22]]

^<<v11-3-22,22>>^ Então disse a outra mulher: Não, mas o vivo é  meu filho, e teu filho o morto. Porém esta disse: Não, por certo, o morto é  teu filho, e meu filho o vivo. Assim falaram perante o rei.

[[v11-3-23]]

^<<v11-3-23,23>>^ Então disse o rei: Esta diz: Este que vive é  meu filho, e teu filho o morto; e esta outra diz: Não, por certo; o morto é teu filho e meu filho o vivo.

[[v11-3-24]]

^<<v11-3-24,24>>^ Disse mais o rei: Trazei-me uma espada. E trouxeram uma espada diante do rei.

[[v11-3-25]]

^<<v11-3-25,25>>^ E disse o rei: Dividi em duas partes o menino vivo: e dai metade a uma e metade a outra.

[[v11-3-26]]

^<<v11-3-26,26>>^ Mas a mulher, cujo filho era  o vivo, falou ao rei (porque as suas entranhas se lhe enterneceram por seu filho), e disse: Ah! senhor meu, dai-lhe o menino vivo, e por modo nenhum o mateis. Porém a outra dizia: Nem teu nem meu seja; dividi-o antes.

[[v11-3-27]]

^<<v11-3-27,27>>^ Então respondeu o rei, e disse: Dai a esta o menino vivo, e de maneira nenhuma o mateis, porque  esta é  sua mãe.

[[v11-3-28]]

^<<v11-3-28,28>>^ E todo o Israel ouviu a sentença que dera o rei, e temeu ao rei: porque viram que havia  nele a sabedoria de Deus, para fazer justiça.

'''

xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[&#60; Capítulo Anterior] | <<v11-3-0,Topo>> | xref:011-1-reis/011-1-reis-004.adoc#v11-4-0[Próximo Capítulo &#62;]