include::./index.adoc[]

[[v11-7-0]]
=== 1 Reis, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v11-7-1]]

^<<v11-7-1,1>>^ PORÉM a sua casa edificou Salomão em treze anos: e acabou toda a sua casa.

[[v11-7-2]]

^<<v11-7-2,2>>^ Também edificou a casa do bosque do Líbano de cem côvados de comprimento, e de cinquenta côvados de largura, e de trinta côvados de altura, sobre quatro ordens de colunas de cedro, e vigas de cedro sobre as colunas.

[[v11-7-3]]

^<<v11-7-3,3>>^ E por cima estava  coberta de cedro sobre as vigas, que estavam sobre quarenta e cinco colunas, quinze em cada ordem.

[[v11-7-4]]

^<<v11-7-4,4>>^ E havia  três ordens de janelas: e uma janela estava defronte da outra janela, em três ordens.

[[v11-7-5]]

^<<v11-7-5,5>>^ Também todas as portas e ombreiras eram  quadradas duma mesma vista; e uma janela estava  defronte da outra, em três ordens.

[[v11-7-6]]

^<<v11-7-6,6>>^ Depois fez um pórtico de colunas de cinquenta côvados de comprimento e de trinta côvados de largura; e o pórtico estava  defronte delas, e as colunas com as grossas vigas defronte delas.

[[v11-7-7]]

^<<v11-7-7,7>>^ Também fez o pórtico para o trono onde julgava, para pórtico de juízo, que estava  coberto de cedro de soalho a soalho.

[[v11-7-8]]

^<<v11-7-8,8>>^ E em  sua casa, em que morava, havia  outro pátio por dentro do pórtico, de obra semelhante a este: também para a filha de Faraó, que Salomão tomara por mulher , fez uma casa semelhante àquele pórtico.

[[v11-7-9]]

^<<v11-7-9,9>>^ Todas estas cousas eram  de pedras finíssimas, cortadas à medida, serradas à serra por dentro e por fora; e  isto desde o fundamento até às beiras do teto, e por fora até ao grande pátio.

[[v11-7-10]]

^<<v11-7-10,10>>^ Também estava  fundado sobre pedras finas, pedras grandes; sobre pedras de dez côvados e pedras de oito côvados.

[[v11-7-11]]

^<<v11-7-11,11>>^ E em cima sobre pedras finas, lavradas segundo as medidas, e cedros.

[[v11-7-12]]

^<<v11-7-12,12>>^ E era  o pátio grande em redor de três ordens de pedras lavradas, com uma ordem de vigas de cedro: assim era também  o pátio interior da casa do Senhor e o pórtico daquela casa.

[[v11-7-13]]

^<<v11-7-13,13>>^ E enviou o rei Salomão, e mandou trazer a Hirão de Tiro.

[[v11-7-14]]

^<<v11-7-14,14>>^ Era  este filho duma mulher viúva, da tribo de Naftali e fora  seu pai um homem de Tiro que trabalhava em cobre; e era cheio de sabedoria, e de entendimento, e de ciência para fazer toda a obra de cobre: este veio ao rei Salomão, e fez toda a sua obra.

[[v11-7-15]]

^<<v11-7-15,15>>^ Porque formou duas colunas de cobre: a altura de cada coluna era de dezoito côvados, e um fio de doze côvados cercava cada uma das colunas.

[[v11-7-16]]

^<<v11-7-16,16>>^ Também fez dois capitéis de fundição de cobre para pôr sobre as cabeças das colunas: de cinco côvados era  a altura dum capitel, e de cinco côvados a altura do outro capitel.

[[v11-7-17]]

^<<v11-7-17,17>>^ As redes eram  de obra de rede, as cintas de obra de cadeia para os capitéis que estavam  sobre a cabeça das colunas; sete para um capitel e sete para o outro capitel.

[[v11-7-18]]

^<<v11-7-18,18>>^ Assim fez as colunas juntamente com duas fileiras em redor sobre uma rede, para cobrir os capitéis que estavam  sobre a cabeça das romãs; assim também fez com o outro capitel.

[[v11-7-19]]

^<<v11-7-19,19>>^ E os capitéis que estavam  sobre a cabeça das colunas eram de obra de lírios no pórtico, de quatro côvados.

[[v11-7-20]]

^<<v11-7-20,20>>^ Os capitéis pois sobre as duas colunas estavam  também defronte, em cima do bojo que estava junto à rede; e duzentas romãs, em fileiras em redor, estavam também  sobre o outro capitel.

[[v11-7-21]]

^<<v11-7-21,21>>^ Depois levantou as colunas no pórtico do templo; e levantando a coluna direita, chamou o seu nome Jaquim; e levantando a coluna esquerda, chamou o seu nome Boaz.

[[v11-7-22]]

^<<v11-7-22,22>>^ E sobre a cabeça das colunas estava  a obra de lírios. E assim se acabou a obra das colunas.

[[v11-7-23]]

^<<v11-7-23,23>>^ Fez mais o mar de fundição, de dez côvados duma borda até à outra borda, redondo ao redor, e de cinco côvados de alto; e um cordão de trinta côvados o cingia em redor.

[[v11-7-24]]

^<<v11-7-24,24>>^ E por baixo da sua borda em redor havia  botões que o cingiam; por dez côvados cercavam aquele mar em redor; duas ordens destes botões foram  fundidas na sua fundição.

[[v11-7-25]]

^<<v11-7-25,25>>^ E firmava-se sobre doze bois, três que olhavam para o norte, e três que olhavam para o ocidente, e três que olhavam para o sul, e três que olhavam para o oriente: e o mar em cima estava  sobre eles, e todas as suas partes posteriores para a banda de dentro.

[[v11-7-26]]

^<<v11-7-26,26>>^ E a grossura era  dum palmo, e a sua borda como a obra da borda dum copo, ou  de flor de lírios; ele levava dois mil batos.

[[v11-7-27]]

^<<v11-7-27,27>>^ Fez também as dez bases de cobre: o comprimento duma base de quatro côvados, e de quatro côvados a sua largura, e de três côvados a sua altura.

[[v11-7-28]]

^<<v11-7-28,28>>^ E esta era  a obra das bases: tinham cintas, e as cintas estavam  entre as molduras.

[[v11-7-29]]

^<<v11-7-29,29>>^ E sobre as cintas que, estavam  entre as molduras havia  leões, bois, e querubins, e sobre as molduras uma base por cima: e debaixo dos leões e dos bois junturas de obra estendida.

[[v11-7-30]]

^<<v11-7-30,30>>^ E uma base tinha quatro rodas de metal, e lâminas de cobre; e os seus quatro cantos tinham ombros: debaixo da pia estavam  estes ombros fundidos, da banda de cada uma das junturas.

[[v11-7-31]]

^<<v11-7-31,31>>^ E a sua boca estava  dentro da coroa, e dum côvado por cima: e era  a sua boca redonda segundo a obra da base, de côvado e meio: e também sobre a sua boca havia  entalhes, e as suas cintas eram  quadradas, não redondas.

[[v11-7-32]]

^<<v11-7-32,32>>^ E as quatro rodas estavam  debaixo das cintas, e os eixos das rodas na base: e era  a altura de cada roda de côvado e meio.

[[v11-7-33]]

^<<v11-7-33,33>>^ E era  a obra das rodas como a obra da roda de carro: seus eixos, e suas cambas, e seus cubos, e seus raios, todos eram  fundidos.

[[v11-7-34]]

^<<v11-7-34,34>>^ E havia  quatro ombros aos quatro cantos de cada base: seus ombros saíam  da base.

[[v11-7-35]]

^<<v11-7-35,35>>^ E no alto de cada base havia uma  altura redonda de meio côvado ao redor: também sobre o alto de cada base havia  asas e cintas, que saíam  delas.

[[v11-7-36]]

^<<v11-7-36,36>>^ E nas pranchas das suas asas e nas suas cintas lavrou querubins, leões, e palmas, segundo o vazio de cada uma, e junturas em redor.

[[v11-7-37]]

^<<v11-7-37,37>>^ Conforme a esta fez as dez bases: todas tinham uma mesma fundição, uma mesma medida, e  um mesmo entalhe.

[[v11-7-38]]

^<<v11-7-38,38>>^ Também fez dez pias de cobre: em cada pia cabiam quarenta batos, e cada pia era de quatro côvados, e  sobre cada uma das dez bases estava  uma pia.

[[v11-7-39]]

^<<v11-7-39,39>>^ E pôs cinco bases à direita da casa, e cinco à esquerda da casa: porém o mar pôs ao lado direito da casa para a banda do oriente, da parte do sul.

[[v11-7-40]]

^<<v11-7-40,40>>^ Depois fez Hirão as pias, e as pás, e as bacias: e acabou Hirão de fazer toda a obra que fez para o rei Salomão, para a casa do Senhor.

[[v11-7-41]]

^<<v11-7-41,41>>^ A saber : as duas colunas, e os globos dos capitéis que estavam  sobre a cabeça das duas colunas: e as duas redes, para cobrir os dois globos dos capitéis que estavam  sobre a cabeça das colunas.

[[v11-7-42]]

^<<v11-7-42,42>>^ E as quatrocentas romãs para as duas redes, a saber , duas carreiras de romãs para cada rede, para cobrirem os dois globos dos capitéis que estavam  em cima das colunas;

[[v11-7-43]]

^<<v11-7-43,43>>^ Juntamente com as dez bases e as dez pias sobre as bases;

[[v11-7-44]]

^<<v11-7-44,44>>^ Como também um mar, e os doze bois debaixo daquele mar;

[[v11-7-45]]

^<<v11-7-45,45>>^ E os caldeirões, e as pás, e as bacias, e todos estes vasos que fez Hirão para o rei Salomão, para a casa do Senhor, todos eram  de cobre brunido.

[[v11-7-46]]

^<<v11-7-46,46>>^ Na planície do Jordão, o rei os fundiu em terra barrenta: entre Sucote e Zartã.

[[v11-7-47]]

^<<v11-7-47,47>>^ E deixou Salomão de pesar  todos os vasos, pelo seu excessivo número, nem se averiguou o peso do cobre.

[[v11-7-48]]

^<<v11-7-48,48>>^ Também fez Salomão todos os vasos que convinham  à casa do Senhor: o altar de ouro, e a mesa de ouro, sobre a qual estavam  os pães da proposição.

[[v11-7-49]]

^<<v11-7-49,49>>^ E os castiçais, cinco à direita e cinco à esquerda, diante do oráculo, de ouro finíssimo e as flores, e as lâmpadas e os espevitadores, também  de ouro.

[[v11-7-50]]

^<<v11-7-50,50>>^ Como  também as taças, e os apagadores, e as bacias, e os perfumadores, e os braseiros, de ouro finíssimo: e as couceiras para as portas da casa interior para o lugar santíssimo, e  as das portas da casa do templo, também  de ouro.

[[v11-7-51]]

^<<v11-7-51,51>>^ Assim se acabou toda a obra que fez o rei Salomão para a casa do Senhor: então trouxe Salomão as cousas santas de seu pai Davi; a prata, e o ouro, e os vasos pôs entre os tesouros da casa do Senhor.

'''

xref:011-1-reis/011-1-reis-006.adoc#v11-6-0[&#60; Capítulo Anterior] | <<v11-7-0,Topo>> | xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[Próximo Capítulo &#62;]