include::./index.adoc[]

[[v11-16-0]]
=== 1 Reis, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v11-16-1]]

^<<v11-16-1,1>>^ ENTÃO veio a palavra do Senhor a Jeú, filho de Hanani, contra Baasa, dizendo:

[[v11-16-2]]

^<<v11-16-2,2>>^ Porquanto te levantei do pó, e te pus por chefe sobre o meu povo Israel, e tu andaste no caminho de Jeroboão, e fizeste pecar a meu povo Israel, irritando-me com os seus pecados,

[[v11-16-3]]

^<<v11-16-3,3>>^ Eis que tirarei os descendentes de Baasa, e os descendentes da sua casa, e farei à tua casa como à casa de Jeroboão, filho de Nebate.

[[v11-16-4]]

^<<v11-16-4,4>>^ Quem morrer a Baasa na cidade os cães o comerão; e o que dele morrer no campo as aves do céu o comerão.

[[v11-16-5]]

^<<v11-16-5,5>>^ Quanto ao mais dos sucessos de Baasa, e ao que fez, e ao seu poder, porventura  não está  escrito no livro das crônicas dos reis de Israel?

[[v11-16-6]]

^<<v11-16-6,6>>^ E Baasa dormiu com seus pais, e foi sepultado em Tirzá: e Ela, seu filho, reinou em seu lugar.

[[v11-16-7]]

^<<v11-16-7,7>>^ Assim veio também a palavra do Senhor, pelo ministério do profeta Jeú, filho de Hanani, contra Baasa e contra a sua casa; e isso  por todo o mal que fizera aos olhos do Senhor, irritando-o com a obra de suas mãos, para ser como a casa de Jeroboão; e por isso o ferira.

[[v11-16-8]]

^<<v11-16-8,8>>^ No ano vinte e seis de Asa, rei de Judá, Ela, filho de Baasa, começou a reinar em Tirzá sobre Israel: e reinou  dois anos.

[[v11-16-9]]

^<<v11-16-9,9>>^ E Zinri, seu servo, chefe de metade dos carros, conspirou contra ele, estando ele em Tirzá bebendo e embriagando-se em casa de Arsa, mordomo em Tirzá.

[[v11-16-10]]

^<<v11-16-10,10>>^ Entrou pois Zinri, e o feriu, e o matou, no ano vigésimo sétimo de Asa, rei de Judá: e reinou em seu lugar.

[[v11-16-11]]

^<<v11-16-11,11>>^ E sucedeu que, reinando ele, e  estando assentado no seu trono feriu a toda a casa de Baasa; não lhe deixou homem algum, nem a seus parentes, nem a seus amigos.

[[v11-16-12]]

^<<v11-16-12,12>>^ Assim destruiu Zinri toda a casa de Baasa, conforme à palavra do Senhor que falara pelo ministério do profeta Jeú, sobre Baasa,

[[v11-16-13]]

^<<v11-16-13,13>>^ Por todos os pecados de Baasa, e os pecados de Ela, seu filho, com que pecaram, e com que fizeram pecar a Israel, irritando ao Senhor Deus de Israel com as suas vaidades.

[[v11-16-14]]

^<<v11-16-14,14>>^ Quanto ao mais dos sucessos de Ela, e a tudo quanto fez, não está  escrito no livro das crônicas dos reis de Israel?

[[v11-16-15]]

^<<v11-16-15,15>>^ No ano vigésimo sétimo de Asa, rei de Judá, reinou Zinri sete dias em Tirzá: e o povo estava acampado contra Gibetom, que era  dos filisteus.

[[v11-16-16]]

^<<v11-16-16,16>>^ E ouviu dizer o povo que estava acampado: Zinri tem conspirado, e até feriu o rei. Todo o Israel pois no mesmo dia fez rei sobre Israel a Onri, chefe do exército no arraial.

[[v11-16-17]]

^<<v11-16-17,17>>^ E subiu Onri, e todo o Israel com ele, de Gibetom, e cercaram a Tirzá.

[[v11-16-18]]

^<<v11-16-18,18>>^ E sucedeu, que  Zinri, vendo que a cidade era tomada, se foi ao paço da casa do rei: e queimou sobre si a casa do rei a fogo, e morreu,

[[v11-16-19]]

^<<v11-16-19,19>>^ Por causa dos  seus pecados que cometera, fazendo o que parecia  mal aos olhos do Senhor, andando no caminho de Jeroboão, e no seu pecado que fizera, fazendo pecar a Israel.

[[v11-16-20]]

^<<v11-16-20,20>>^ Quanto ao mais dos sucessos de Zinri, e à conspiração que fez porventura  não está  escrito no livro das crônicas dos reis de Israel?

[[v11-16-21]]

^<<v11-16-21,21>>^ Então o povo de Israel se dividiu em dois partidos: metade do povo seguia a Tibni, filho de Ginate para o fazer rei, e a outra  metade seguia a Onri.

[[v11-16-22]]

^<<v11-16-22,22>>^ Mas o povo que seguia a Onri foi mais forte do  que o povo que seguia a Tibni, filho de Ginate: e Tibni morreu, e Onri reinou.

[[v11-16-23]]

^<<v11-16-23,23>>^ No ano trinta e um de Asa, rei de Judá, Onri começou a reinar sobre Israel, e reinou  doze anos: e em Tirzá reinou seis anos.

[[v11-16-24]]

^<<v11-16-24,24>>^ E de Sêmer comprou o monte de Samaria por dois talentos de prata: e edificou em o monte, e chamou o nome da cidade que edificou do nome de Sêmer, senhor do monte de Samaria.

[[v11-16-25]]

^<<v11-16-25,25>>^ E fez Onri o que parecia  mal aos olhos do Senhor; e fez pior do que todos quantos foram  antes dele.

[[v11-16-26]]

^<<v11-16-26,26>>^ E andou em todos os caminhos de Jeroboão, filho de Nebate, como também nos seus pecados com que tinha feito pecar a Israel, irritando ao Senhor Deus de Israel com as suas vaidades.

[[v11-16-27]]

^<<v11-16-27,27>>^ Quanto ao mais dos sucessos de Onri, ao que fez, e ao seu poder que manifestou, porventura  não está  escrito no livro das crônicas dos reis de Israel?

[[v11-16-28]]

^<<v11-16-28,28>>^ E Onri dormiu com seus pais, e foi sepultado em Samaria: e Acabe, seu filho, reinou em seu lugar.

[[v11-16-29]]

^<<v11-16-29,29>>^ E Acabe, filho de Onri, começou a reinar sobre Israel no ano trigésimo oitavo de Asa, rei de Judá: e reinou Acabe, filho de Onri, sobre Israel em Samaria, vinte e dois anos.

[[v11-16-30]]

^<<v11-16-30,30>>^ E fez Acabe, filho de Onri, o que parecia  mal aos olhos do Senhor, mais do que todos os que foram  antes dele.

[[v11-16-31]]

^<<v11-16-31,31>>^ E sucedeu que (como se fora cousa leve andar nos pecados de Jeroboão, filho de Nebate), ainda tomou por mulher a Jezabel, filha de Etbaal, rei dos sidônios: e foi e serviu a Baal, e se encurvou diante dele.

[[v11-16-32]]

^<<v11-16-32,32>>^ E levantou um altar a Baal, na casa de Baal que edificara em Samaria.

[[v11-16-33]]

^<<v11-16-33,33>>^ Também Acabe fez um  bosque: de maneira que Acabe fez muito mais para irritar ao Senhor Deus de Israel do que todos os reis de Israel que foram antes dele.

[[v11-16-34]]

^<<v11-16-34,34>>^ Em seus dias Hiel, o betelita, edificou a Jericó: morrendo Abirão, seu primogênito, a fundou, e morrendo Segube, seu último, pôs as suas portas: conforme à palavra do Senhor, que falara pelo ministério de Josué, filho de Num.

'''

xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[&#60; Capítulo Anterior] | <<v11-16-0,Topo>> | xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[Próximo Capítulo &#62;]