include::./index.adoc[]

[[v11-9-0]]
=== 1 Reis, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v11-9-1]]

^<<v11-9-1,1>>^ SUCEDEU pois que, acabando Salomão de edificar a casa do Senhor, e a casa do rei, e todo o desejo de Salomão, que lhe veio à vontade fazer,

[[v11-9-2]]

^<<v11-9-2,2>>^ O Senhor tornou a aparecer a Salomão, como lhe tinha aparecido em Gibeom.

[[v11-9-3]]

^<<v11-9-3,3>>^ E o Senhor lhe disse: Ouvi a tua oração, e a tua súplica que suplicando fizeste perante mim; santifiquei a casa que edificaste, a fim de pôr ali o meu nome para sempre: e os meus olhos e o meu coração estarão ali todos os dias.

[[v11-9-4]]

^<<v11-9-4,4>>^ E se tu andares perante mim como andou Davi teu pai, com inteireza de coração e com sinceridade, para fazeres segundo tudo o que te mandei, e  guardares os meus estatutos e os meus juízos,

[[v11-9-5]]

^<<v11-9-5,5>>^ Então confirmarei o trono de teu reino sobre Israel para sempre, como falei acerca de teu pai Davi, dizendo: Não te faltará varão sobre o trono de Israel.

[[v11-9-6]]

^<<v11-9-6,6>>^ Porém  se vós e vossos filhos de qualquer maneira vos apartardes de mim, e não guardardes os meus mandamentos, e  os meus estatutos, que vos tenho proposto, mas fordes, e servirdes a outros deuses, e vos curvardes perante eles,

[[v11-9-7]]

^<<v11-9-7,7>>^ Então destruirei a Israel da terra que lhes dei; e a esta casa, que santifiquei a meu nome, lançarei longe da minha presença: e Israel será por ditado e mote, entre todos os povos.

[[v11-9-8]]

^<<v11-9-8,8>>^ E desta casa, que é tão exaltada, todo aquele que por ela passar pasmará e assobiará e dirá: Por que fez o Senhor assim a esta terra e a esta casa?

[[v11-9-9]]

^<<v11-9-9,9>>^ E dirão: Porque deixaram ao Senhor seu Deus, que tirou da terra do Egito a seus pais, e se apegaram a deuses alheios, e se encurvaram perante eles, e os serviram: por isso trouxe o Senhor sobre eles todo este mal.

[[v11-9-10]]

^<<v11-9-10,10>>^ E sucedeu, ao fim de vinte anos, que Salomão edificara as duas casas; a casa do Senhor e a casa do rei.

[[v11-9-11]]

^<<v11-9-11,11>>^ ( Para o que  Hirão, rei de Tiro, trouxera a Salomão madeira de cedro e de faia, e ouro, segundo todo o seu desejo:) Então deu o rei Salomão a Hirão vinte cidades na terra de Galileia.

[[v11-9-12]]

^<<v11-9-12,12>>^ E saiu Hirão de Tiro a ver as cidades que Salomão lhe dera, porém não foram boas aos seus olhos.

[[v11-9-13]]

^<<v11-9-13,13>>^ Pelo que disse: Que cidades são  estas que me deste, irmão meu? E chamaram-nas: Terra de Cabuli, até hoje.

[[v11-9-14]]

^<<v11-9-14,14>>^ E enviara Hirão ao rei cento e vinte talentos de ouro.

[[v11-9-15]]

^<<v11-9-15,15>>^ E esta é  a causa do tributo, que impôs o rei Salomão, para edificar a casa do Senhor e a sua casa, e Milo, e o muro de Jerusalém, como também a Hasor, e a Megido, e a Gezer.

[[v11-9-16]]

^<<v11-9-16,16>>^ Porque  Faraó, rei do Egito, subiu e tomou a Gezer, e a queimou a fogo, e matou os cananeus que moravam na cidade, e a deu em dote a sua filha, mulher de Salomão.

[[v11-9-17]]

^<<v11-9-17,17>>^ Assim edificou Salomão a Gezer, e Betorom, a baixa,

[[v11-9-18]]

^<<v11-9-18,18>>^ E a Baalate, e a Tadmor, no deserto daquela terra.

[[v11-9-19]]

^<<v11-9-19,19>>^ E a todas as cidades das munições que Salomão tinha e as cidades dos carros, e as cidades dos cavaleiros, e o que o desejo de Salomão quis edificar em Jerusalém, e no Líbano, e em toda a terra do seu domínio.

[[v11-9-20]]

^<<v11-9-20,20>>^ Quanto  a todo o povo que  restou dos amorreus, heteus, ferezeus, heveus, e jebuseus, e  que não eram dos filhos de Israel,

[[v11-9-21]]

^<<v11-9-21,21>>^ A seus filhos, que restaram depois deles na terra, os quais os filhos de Israel não puderam destruir totalmente, Salomão os reduziu a tributo servil, até hoje.

[[v11-9-22]]

^<<v11-9-22,22>>^ Porém dos filhos de Israel não fez Salomão escravo algum: porém eram  homens de guerra, e seus criados, e seus príncipes, e seus capitães e chefes dos seus carros e dos seus cavaleiros.

[[v11-9-23]]

^<<v11-9-23,23>>^ Estes eram  os chefes dos oficiais que estavam  sobre a obra de Salomão, quinhentos e cinquenta, que davam ordens ao povo que trabalhava na obra.

[[v11-9-24]]

^<<v11-9-24,24>>^ Subiu porém a filha de Faraó da cidade de Davi à sua casa, que Salomão lhe edificara; então edificou a Milo.

[[v11-9-25]]

^<<v11-9-25,25>>^ E oferecia Salomão três vezes cada ano holocaustos e sacrifícios pacíficos sobre o altar que edificaram ao Senhor, e queimava incenso sobre o que estava  perante o Senhor: e assim acabou a casa.

[[v11-9-26]]

^<<v11-9-26,26>>^ Também o rei Salomão fez naus em Esiom-Geber, que está  junto a Elote, na praia do mar de Sufe, na terra de Edom.

[[v11-9-27]]

^<<v11-9-27,27>>^ E mandou Hirão com aquelas naus os seus servos, marinheiros, que sabiam do mar, com os servos de Salomão.

[[v11-9-28]]

^<<v11-9-28,28>>^ E vieram a Ofir, e tomaram de lá quatrocentos e vinte talentos de ouro, e o  trouxeram ao rei Salomão.

'''

xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[&#60; Capítulo Anterior] | <<v11-9-0,Topo>> | xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[Próximo Capítulo &#62;]