include::./index.adoc[]

[[v11-20-0]]
=== 1 Reis, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v11-20-1]]

^<<v11-20-1,1>>^ E BENADADE, rei da Síria, ajuntou todas as suas forças: e trinta e dois reis, e cavalos e carros havia  com ele: e subiu, e cercou a Samaria, e pelejou contra ela.

[[v11-20-2]]

^<<v11-20-2,2>>^ E enviou à cidade mensageiros, a Acabe, rei de Israel.

[[v11-20-3]]

^<<v11-20-3,3>>^ E disse-lhe: Assim diz Benadade: A tua prata e o teu ouro são  meus; e tuas mulheres e os melhores de teus filhos são meus.

[[v11-20-4]]

^<<v11-20-4,4>>^ E respondeu o rei de Israel, e disse: Conforme a tua palavra, ó rei meu senhor, teu sou  eu, e tudo quanto tenho.

[[v11-20-5]]

^<<v11-20-5,5>>^ E tornaram a vir  os mensageiros, e disseram: Assim fala Benadade, dizendo: Ainda que eu te mandei dizer: Tu me hás de dar a tua prata, e o teu ouro, e as tuas mulheres e os teus filhos;

[[v11-20-6]]

^<<v11-20-6,6>>^ Todavia amanhã a estas horas enviarei os meus servos a ti, e esquadrinharão a tua casa e as casas dos teus servos: e há de ser que  tudo o que for  aprazível aos teus olhos o meterão nas suas mãos, e o levarão.

[[v11-20-7]]

^<<v11-20-7,7>>^ Então o rei de Israel chamou a todos os anciãos da terra, e disse: Notai agora, e vede como este busca mal; pois enviara a mim por minhas mulheres, e por meus filhos, e pela minha prata, e pelo meu ouro, e não lho neguei.

[[v11-20-8]]

^<<v11-20-8,8>>^ E todos os anciãos e todo o povo lhe disseram: Não lhe  dês ouvidos, nem consintas.

[[v11-20-9]]

^<<v11-20-9,9>>^ Pelo que disse aos mensageiros de Benadade: Dizei ao rei, meu senhor: Tudo o que primeiro mandaste pedir  a teu servo, farei, porém isto não posso fazer. E foram os mensageiros, e lhe tornaram com esta  resposta.

[[v11-20-10]]

^<<v11-20-10,10>>^ E Benadade enviou a ele, e disse: Assim me façam os deuses, e outro tanto, que o pó de Samaria não bastará para encher  as mãos de todo o povo que me segue.

[[v11-20-11]]

^<<v11-20-11,11>>^ Porém o rei de Israel respondeu, e disse: Dizei- lhe : Não se gabe quem se cinge como aquele que se descinge.

[[v11-20-12]]

^<<v11-20-12,12>>^ E sucedeu que, ouvindo ele esta palavra, estando bebendo ele e os reis nas tendas, disse aos seus servos: Ponde-vos em ordem  contra a cidade.

[[v11-20-13]]

^<<v11-20-13,13>>^ E eis que um profeta se chegou a Acabe rei de Israel, e lhe  disse: Assim diz o Senhor: Viste toda esta grande multidão? eis que hoje ta entregarei nas tuas mãos, para que saibas que eu sou  o Senhor.

[[v11-20-14]]

^<<v11-20-14,14>>^ E disse Acabe: Por quem? E ele disse: Assim diz o Senhor: Pelos moços dos príncipes das províncias. E disse: Quem começará a peleja? E disse: Tu.

[[v11-20-15]]

^<<v11-20-15,15>>^ Então contou os moços dos príncipes das províncias, e foram duzentos e trinta e dois: e depois deles contou a todo o povo, todos os filhos de Israel, sete mil.

[[v11-20-16]]

^<<v11-20-16,16>>^ E saíram ao meio-dia: e Benadade estava  bebendo e  embriagando-se nas tendas, ele e os reis, os trinta e dois reis, que o ajudavam.

[[v11-20-17]]

^<<v11-20-17,17>>^ E os moços dos príncipes das províncias saíram primeiro: e Benadade enviou a alguns , que lhe deram avisos, dizendo: Saíram de Samaria uns homens.

[[v11-20-18]]

^<<v11-20-18,18>>^ E ele disse: Ainda que para paz saíssem, tomai-os vivos: e ainda que à peleja saíssem, vivos os tomai.

[[v11-20-19]]

^<<v11-20-19,19>>^ Saíram pois da cidade os moços dos príncipes das províncias, e o exército que os seguia.

[[v11-20-20]]

^<<v11-20-20,20>>^ E eles feriram cada um o seu homem, e os siros fugiram, e Israel os perseguiu: porém Benadade, rei da Síria, escapou a cavalo, com alguns  cavaleiros.

[[v11-20-21]]

^<<v11-20-21,21>>^ E saiu o rei de Israel, e feriu os cavalos e os carros: e feriu os siros com grande estrago.

[[v11-20-22]]

^<<v11-20-22,22>>^ Então o profeta chegou-se ao rei de Israel e lhe disse: Vai, esforça-te, e atenta, e olha o que hás de fazer; porque no decurso dum ano o rei da Síria subirá contra ti.

[[v11-20-23]]

^<<v11-20-23,23>>^ Porque os servos do rei da Síria lhe disseram: Seus deuses são  deuses dos montes, por isso foram mais fortes do que nós: mas pelejemos com eles em campo raso, e  por certo veremos  se não somos mais fortes do que eles!

[[v11-20-24]]

^<<v11-20-24,24>>^ Faze pois isto: tira os reis, cada um do seu lugar, e põe capitães em seu lugar.

[[v11-20-25]]

^<<v11-20-25,25>>^ E numera outro  exército, como o exército que caiu de ti, e cavalos como aqueles cavalos, e carros como aqueles carros, e pelejemos com eles em campo raso, e veremos  se não somos mais fortes do que eles! E deu ouvidos à sua voz, e assim fez.

[[v11-20-26]]

^<<v11-20-26,26>>^ E sucedeu que, passado um ano, Benadade fez revista dos siros, e subiu a Afeque, para pelejar contra Israel.

[[v11-20-27]]

^<<v11-20-27,27>>^ Também dos filhos de Israel se fez revista, e providos de víveres marcharam contra eles; e os filhos de Israel acamparam-se defronte deles, como dois pequenos rebanhos de cabras; mas os siros enchiam a terra.

[[v11-20-28]]

^<<v11-20-28,28>>^ E chegou o homem de Deus, e falou ao rei de Israel, e disse: Assim diz o Senhor: Porquanto os siros disseram: O Senhor é Deus dos montes, e não Deus dos vales, toda esta grande multidão entregarei nas tuas mãos, para que saibas que eu sou  o Senhor.

[[v11-20-29]]

^<<v11-20-29,29>>^ E sete dias estiveram estes acampados defronte dos outros: e sucedeu ao sétimo dia que a peleja começou, e os filhos de Israel feriram dos siros cem mil homens de pé, num dia.

[[v11-20-30]]

^<<v11-20-30,30>>^ E os restantes fugiram para Afeque, à cidade; e caiu o muro sobre vinte e sete mil homens, que restaram: Benadade porém fugiu, e veio à cidade, andando de  câmara em câmara.

[[v11-20-31]]

^<<v11-20-31,31>>^ Então lhe disseram os seus servos: Eis que já temos ouvido que os reis da casa de Israel são reis clementes: ponhamos pois sacos aos lombos e cordas às cabeças, e saiamos ao rei de Israel; pode ser que guarde em vida a tua alma.

[[v11-20-32]]

^<<v11-20-32,32>>^ Então cingiram sacos aos lombos e cordas às cabeças, e vieram ao rei de Israel, e disseram: Diz o teu servo Benadade: Deixa-me viver. E disse ele: Pois ainda vive? É meu irmão.

[[v11-20-33]]

^<<v11-20-33,33>>^ E aqueles homens tomaram isto  por bom presságio, e apressaram-se em apanhar a sua palavra, e disseram: Teu irmão Benadade vive.  E ele disse: Vinde, trazei-mo. Então Benadade saiu a eles e ele o fez subir ao carro.

[[v11-20-34]]

^<<v11-20-34,34>>^ E disse ele: As cidades que meu pai tomou de teu pai tas restituirei, e faze para ti ruas em Damasco, como meu pai as fez em Samaria. E eu, respondeu Acabe , te deixarei ir com esta aliança. E fez com ele aliança e o deixou ir.

[[v11-20-35]]

^<<v11-20-35,35>>^ Então um dos homens dos filhos dos profetas disse ao seu companheiro, pela palavra do Senhor: Ora fere-me. E o homem recusou feri-lo.

[[v11-20-36]]

^<<v11-20-36,36>>^ E ele lhe disse: Porque não obedeceste à voz do Senhor, eis que, em te apartando de mim, um leão te ferirá. E, como dele se apartou, um leão o encontrou e o feriu.

[[v11-20-37]]

^<<v11-20-37,37>>^ Depois encontrou outro homem, e disse- lhe: Ora  fere-me. E feriu-o aquele homem, ferindo-o e vulnerando-o.

[[v11-20-38]]

^<<v11-20-38,38>>^ Então foi o profeta, e pôs-se perante o rei no caminho: e disfarçou-se com cinza sobre os seus olhos.

[[v11-20-39]]

^<<v11-20-39,39>>^ E sucedeu que, passando o rei, clamou ele ao rei, e disse: Teu servo saiu ao meio da peleja e eis que, desviando-se um homem, me trouxe outro  homem, e disse: Guarda-me este homem; se vier a faltar, será a tua vida em lugar da vida dele, ou pagarás um talento de prata.

[[v11-20-40]]

^<<v11-20-40,40>>^ Sucedeu pois que, estando o teu servo ocupado duma e doutra parte, entretanto desapareceu. Então o rei de Israel lhe disse: Esta é  a tua sentença; tu mesmo a pronunciaste.

[[v11-20-41]]

^<<v11-20-41,41>>^ Então ele se apressou, e tirou a cinza de sobre os seus olhos: e o rei de Israel o reconheceu que era um  dos profetas.

[[v11-20-42]]

^<<v11-20-42,42>>^ E disse-lhe: Assim diz o Senhor: Porquanto soltaste da mão o homem que eu havia posto para destruição, a tua vida será em lugar de sua vida, e o teu povo em lugar do seu povo.

[[v11-20-43]]

^<<v11-20-43,43>>^ E foi-se o rei de Israel para sua casa, desgostoso e indignado, e veio a Samaria.

'''

xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[Próximo Capítulo &#62;]