include::./index.adoc[]

[[v11-6-0]]
=== 1 Reis, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v11-6-1]]

^<<v11-6-1,1>>^ E SUCEDEU que no ano de quatrocentos e oitenta, depois de saírem os filhos de Israel do Egito, no ano quarto do reinado de Salomão sobre Israel, no mês de Zive (este é o mês segundo), começou a  edificar a casa do Senhor.

[[v11-6-2]]

^<<v11-6-2,2>>^ E a casa que o rei Salomão edificou ao Senhor era de sessenta côvados de comprimento, e de vinte côvados de largura, e de trinta côvados de altura.

[[v11-6-3]]

^<<v11-6-3,3>>^ E o pórtico diante do templo da casa era de vinte côvados de comprimento, segundo a largura da casa, e de dez côvados de largura diante da casa.

[[v11-6-4]]

^<<v11-6-4,4>>^ E fez à casa janelas de vista estreita.

[[v11-6-5]]

^<<v11-6-5,5>>^ Edificou em redor da parede da casa câmaras, em redor das paredes da casa, tanto  do templo como do oráculo: e assim  lhe fez câmaras colaterais em redor.

[[v11-6-6]]

^<<v11-6-6,6>>^ A câmara de baixo era  de cinco côvados de largura, e a do meio de seis côvados de largura, e a terceira de sete côvados de largura; porque pela parte de fora da casa em redor fizera encostos, para não travarem das paredes da casa.

[[v11-6-7]]

^<<v11-6-7,7>>^ E edificava-se a casa com pedras preparadas, como as traziam se edificava; de maneira que nem martelo, nem machado, nem  nenhum outro  instrumento de ferro se ouviu na casa quando a edificavam.

[[v11-6-8]]

^<<v11-6-8,8>>^ A porta da câmara do meio estava à banda direita da casa, e por caracóis se subia à do meio, e da do meio à  terceira.

[[v11-6-9]]

^<<v11-6-9,9>>^ Assim pois  edificou a casa, e a aperfeiçoou: e cobriu a casa com pranchões e tabuados de cedro.

[[v11-6-10]]

^<<v11-6-10,10>>^ Também edificou as câmaras a toda a casa de cinco côvados de altura, e as travou com a casa com madeira de cedro.

[[v11-6-11]]

^<<v11-6-11,11>>^ Então veio a palavra do Senhor a Salomão, dizendo:

[[v11-6-12]]

^<<v11-6-12,12>>^ Quanto  a esta casa que tu edificas, se andares nos meus estatutos, e fizeres os meus juízos, e guardares todos os meus mandamentos, andando neles, confirmarei para contigo a minha palavra, a qual falei a Davi, teu pai:

[[v11-6-13]]

^<<v11-6-13,13>>^ E habitarei no meio dos filhos de Israel, e não desampararei o meu povo de Israel.

[[v11-6-14]]

^<<v11-6-14,14>>^ Assim edificou Salomão aquela casa, e a aperfeiçoou.

[[v11-6-15]]

^<<v11-6-15,15>>^ Também cobriu as paredes da casa por dentro com tábuas de cedro; desde o soalho da casa até ao teto tudo  cobriu com madeira por dentro: e cobriu o soalho da casa com tábuas de faia.

[[v11-6-16]]

^<<v11-6-16,16>>^ Edificou mais vinte côvados de tábuas de cedro nos lados da casa, desde o soalho até às paredes: e por dentro lhas edificou para o oráculo, para o Santo dos Santos.

[[v11-6-17]]

^<<v11-6-17,17>>^ Era pois a casa de quarenta côvados, a saber : o templo interior.

[[v11-6-18]]

^<<v11-6-18,18>>^ E o cedro da casa por dentro era lavrado de botões e flores abertas: tudo era  cedro, pedra nenhuma se via.

[[v11-6-19]]

^<<v11-6-19,19>>^ E por dentro da casa interior preparou o oráculo, para pôr ali a arca do concerto do Senhor.

[[v11-6-20]]

^<<v11-6-20,20>>^ E o oráculo no interior era de vinte côvados de comprimento, e de vinte côvados de largura, e de vinte côvados de altura: e o cobriu de ouro puro: também cobriu de cedro o altar.

[[v11-6-21]]

^<<v11-6-21,21>>^ E cobriu Salomão a casa por dentro de ouro puro: e com cadeias de ouro pôs um véu  diante do oráculo, e o cobriu com ouro.

[[v11-6-22]]

^<<v11-6-22,22>>^ Assim toda a casa cobriu de ouro, até acabar toda a casa: também todo o altar que estava  diante do oráculo cobriu de ouro.

[[v11-6-23]]

^<<v11-6-23,23>>^ E no oráculo fez dois querubins de madeira de oliveira, cada um  da altura de dez côvados.

[[v11-6-24]]

^<<v11-6-24,24>>^ E uma asa dum querubim era  de cinco côvados, e a outra asa do querubim de outros  cinco côvados; dez côvados havia desde a extremidade duma das suas asas até à extremidade da outra  das suas asas.

[[v11-6-25]]

^<<v11-6-25,25>>^ Assim era também  de dez côvados o outro querubim: ambos os querubins eram duma mesma medida e dum mesmo talhe.

[[v11-6-26]]

^<<v11-6-26,26>>^ A altura dum querubim de dez côvados, e assim a do outro querubim.

[[v11-6-27]]

^<<v11-6-27,27>>^ E pôs a estes querubins no meio da casa de dentro; e os querubins estendiam as asas, de maneira  que a asa dum tocava na parede, e a asa do outro querubim tocava na outra parede: e as suas asas no meio da casa tocavam uma na outra.

[[v11-6-28]]

^<<v11-6-28,28>>^ E cobriu de ouro os querubins.

[[v11-6-29]]

^<<v11-6-29,29>>^ E todas as paredes da casa em redor lavrou de esculturas e de entalhes de querubins, e de palmas e de flores abertas, por dentro e por fora.

[[v11-6-30]]

^<<v11-6-30,30>>^ Também cobriu de ouro o soalho da casa, por dentro e por fora.

[[v11-6-31]]

^<<v11-6-31,31>>^ E à entrada do oráculo fez portas de madeira de oliveira: a verga com  as ombreiras faziam  a quinta parte da parede.

[[v11-6-32]]

^<<v11-6-32,32>>^ Também as duas portas eram da madeira olearia; e lavrou nelas entalhes de querubins, e de palmas, e de flores abertas, os quais cobriu de ouro: também estendeu ouro sobre os querubins e sobre as palmas.

[[v11-6-33]]

^<<v11-6-33,33>>^ E assim fez à porta do templo ombreiras de madeira olearia, da quarta parte da parede.

[[v11-6-34]]

^<<v11-6-34,34>>^ E eram  as duas portas de madeira de faia: e  as duas folhas duma porta eram  dobradiças, assim como eram também  dobradiças as  duas folhas  entalhadas das outras portas.

[[v11-6-35]]

^<<v11-6-35,35>>^ E as lavrou de querubins, e de palmas, e de flores abertas, e as cobriu de ouro acomodado ao lavor.

[[v11-6-36]]

^<<v11-6-36,36>>^ Também edificou o pátio interior de três ordens de pedras lavradas e duma ordem de vigas de cedro.

[[v11-6-37]]

^<<v11-6-37,37>>^ No ano quarto se pôs o fundamento da casa do Senhor, no mês de Zive.

[[v11-6-38]]

^<<v11-6-38,38>>^ E no ano undécimo, no mês de Bul, que é o mês oitavo, se acabou esta casa com todas as suas dependências, e com tudo o que lhe convinha: e a edificou em  sete anos.

'''

xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[&#60; Capítulo Anterior] | <<v11-6-0,Topo>> | xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[Próximo Capítulo &#62;]