include::./index.adoc[]

[[v11-11-0]]
=== 1 Reis, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v11-11-1]]

^<<v11-11-1,1>>^ E O rei Salomão amou muitas mulheres estranhas, e isso além da filha de Faraó, moabitas, amonitas, idumeias, sidônias e  heteias.

[[v11-11-2]]

^<<v11-11-2,2>>^ Das nações de  que o Senhor tinha dito aos filhos de Israel: Não entrareis a elas, e elas não entrarão a vós; doutra maneira perverterão o vosso coração para seguirdes os seus deuses. A estas se uniu Salomão com amor.

[[v11-11-3]]

^<<v11-11-3,3>>^ E tinha setecentas mulheres, princesas, e trezentas concubinas: e suas mulheres lhe perverteram o seu coração.

[[v11-11-4]]

^<<v11-11-4,4>>^ Porque sucedeu que , no tempo da velhice de Salomão, suas mulheres lhe perverteram o seu coração para seguir outros deuses: e o seu coração não era perfeito para com o Senhor seu Deus, como o coração de Davi, seu pai,

[[v11-11-5]]

^<<v11-11-5,5>>^ Porque Salomão, andou em seguimento de Astarote, deusa dos sidônios, e em seguimento de Milcom, a abominação dos amonitas.

[[v11-11-6]]

^<<v11-11-6,6>>^ Assim fez Salomão o que parecia  mal aos olhos do Senhor; e não perseverou em seguir ao Senhor, como Davi seu pai.

[[v11-11-7]]

^<<v11-11-7,7>>^ Então edificou Salomão um alto a Camós, a abominação dos moabitas, sobre o monte que está  diante de Jerusalém, e a Moloque, a abominação dos filhos de Amom.

[[v11-11-8]]

^<<v11-11-8,8>>^ E assim fez para com todas as suas mulheres estranhas; as quais queimavam incenso e sacrificavam a seus deuses.

[[v11-11-9]]

^<<v11-11-9,9>>^ Pelo que o Senhor se indignou contra Salomão: porquanto desviara o seu coração do Senhor Deus de Israel, o qual duas vezes lhe aparecera.

[[v11-11-10]]

^<<v11-11-10,10>>^ E acerca desta matéria lhe tinha dado ordem que não andasse em seguimento de outros deuses: porém não guardou o que o Senhor lhe ordenara.

[[v11-11-11]]

^<<v11-11-11,11>>^ Pelo que disse o Senhor a Salomão: Pois que houve isto em ti, que não guardaste o meu concerto e os meus estatutos que te mandei, certamente rasgarei de ti este reino, e o darei a teu servo.

[[v11-11-12]]

^<<v11-11-12,12>>^ Todavia nos teus dias não o farei, por amor de Davi teu pai: da mão de teu filho o rasgarei:

[[v11-11-13]]

^<<v11-11-13,13>>^ Porém todo o reino não rasgarei: uma tribo darei a teu filho, por amor de meu servo Davi, e por amor de Jerusalém, que tenho elegido.

[[v11-11-14]]

^<<v11-11-14,14>>^ Levantou pois o Senhor a Salomão um adversário, a Hadade, o idumeu: ele era  da semente do rei em Edom.

[[v11-11-15]]

^<<v11-11-15,15>>^ Porque sucedeu que, estando Davi em Edom, e subindo Joabe, o chefe do exército, a enterrar os mortos, feriu a todo o varão em Edom.

[[v11-11-16]]

^<<v11-11-16,16>>^ (Porque Joabe ficou ali seis meses com todo o Israel, até que destruiu a todo o varão em Edom.)

[[v11-11-17]]

^<<v11-11-17,17>>^ Hadade, porém, fugiu, ele e alguns homens idumeus, dos servos de seu pai, com ele, para ir ao Egito: era  porém Hadade um  rapaz pequeno.

[[v11-11-18]]

^<<v11-11-18,18>>^ E levantaram-se de Midiã e vieram a Parã, e tomaram consigo homens de Parã, e vieram ao Egito a Faraó, rei do Egito, o qual lhe deu uma casa, e lhe prometeu sustento, e lhe deu uma terra.

[[v11-11-19]]

^<<v11-11-19,19>>^ E achou Hadade grande graça aos olhos de Faraó: de maneira que lhe deu por mulher, a irmã de sua mulher a irmã de Tacpenes, a rainha.

[[v11-11-20]]

^<<v11-11-20,20>>^ E a irmã de Tacpenes lhe deu seu filho Genubate, o qual Tacpenes criou na casa de Faraó: e Genubate estava na casa de Faraó, entre os filhos de Faraó.

[[v11-11-21]]

^<<v11-11-21,21>>^ Ouvindo pois Hadade no Egito que Davi adormecera com seus pais, e que Joabe, chefe do exército, era morto, disse Hadade a Faraó: Despede-me, para que vá à minha terra.

[[v11-11-22]]

^<<v11-11-22,22>>^ Porém Faraó lhe disse: Pois que te falta comigo, que eis que procuras partir para a tua terra? E disse ele: Nada, mas todavia despede-me.

[[v11-11-23]]

^<<v11-11-23,23>>^ Também Deus lhe levantou outro  adversário, a Rezom, filho de Eliada, que tinha fugido de seu senhor Hadadezer, rei de Zobá,

[[v11-11-24]]

^<<v11-11-24,24>>^ Contra quem também ajuntou homens, e foi capitão dum esquadrão, quando Davi os matou: e indo-se para Damasco, habitaram ali, e reinaram em Damasco.

[[v11-11-25]]

^<<v11-11-25,25>>^ E foi adversário de Israel por todos os dias de Salomão, e isto além do mal que Hadade fazia : porque detestava a Israel, e reinava sobre a Síria.

[[v11-11-26]]

^<<v11-11-26,26>>^ Até Jeroboão, filho de Nebate, efrateu de Zereda, servo de Salomão (cuja mãe era mulher viúva, por nome Zerua), também levantou a mão contra o rei.

[[v11-11-27]]

^<<v11-11-27,27>>^ E esta foi  a causa, por que levantou a mão contra o rei: Salomão tinha edificado a Milo, e  cerrou as aberturas da cidade de Davi, seu pai.

[[v11-11-28]]

^<<v11-11-28,28>>^ E o homem Jeroboão era  varão valente; e, vendo Salomão a este mancebo, que era laborioso, ele o pôs sobre todo o cargo da casa de José.

[[v11-11-29]]

^<<v11-11-29,29>>^ Sucedeu pois naquele tempo que, saindo Jeroboão de Jerusalém, o encontrou o profeta Aías, o silonita, no caminho, e ele se tinha vestido dum vestido novo, e sós estavam  os dois no campo.

[[v11-11-30]]

^<<v11-11-30,30>>^ E Aías pegou no vestido novo que sobre si tinha , e o rasgou em doze pedaços.

[[v11-11-31]]

^<<v11-11-31,31>>^ E disse a Jeroboão: Toma para ti os dez pedaços, porque assim diz o Senhor Deus de Israel: Eis que rasgarei o reino da mão de Salomão, e a ti darei as dez tribos.

[[v11-11-32]]

^<<v11-11-32,32>>^ Porém ele terá uma tribo, por amor de Davi, meu servo, e por amor de Jerusalém, a cidade que elegi de todas as tribos de Israel.

[[v11-11-33]]

^<<v11-11-33,33>>^ Porque me deixaram, e se encurvaram a Astarote, deusa dos sidônios, a Camós, deus dos moabitas, e a Milcom, deus dos filhos de Amom; e não andaram pelos meus caminhos, para fazerem o que parece  reto aos meus olhos, a saber , os meus estatutos e os meus juízos, como Davi, seu pai.

[[v11-11-34]]

^<<v11-11-34,34>>^ Porém não tomarei nada deste reino da sua mão: mas por príncipe o ponho por todos os dias da sua vida, por amor de Davi, meu servo, a quem elegi, o qual guardou os meus mandamentos e os meus estatutos.

[[v11-11-35]]

^<<v11-11-35,35>>^ Mas da mão de seu filho tomarei o reino, e to darei a ti, as dez tribos dele.

[[v11-11-36]]

^<<v11-11-36,36>>^ E a seu filho darei uma tribo; para que Davi, meu servo, sempre tenha uma lâmpada diante de mim em Jerusalém, a cidade que elegi para pôr ali o meu nome.

[[v11-11-37]]

^<<v11-11-37,37>>^ E te tomarei, e reinarás sobre tudo o que desejar a tua alma; e serás rei sobre Israel.

[[v11-11-38]]

^<<v11-11-38,38>>^ E há de ser que , se ouvires tudo o que eu te mandar, e andares pelos meus caminhos, e fizeres o que  é reto aos meus olhos, guardando os meus estatutos e os meus mandamentos, como fez Davi, meu servo, eu serei contigo, e te edificarei uma  casa firme, como edifiquei a Davi e te darei Israel.

[[v11-11-39]]

^<<v11-11-39,39>>^ E por isso afligirei a semente de Davi; todavia não para sempre.

[[v11-11-40]]

^<<v11-11-40,40>>^ Pelo que Salomão procurou matar Jeroboão; porém Jeroboão se levantou, e fugiu para o Egito, para Sisaque, rei do Egito: e esteve no Egito até que Salomão morreu.

[[v11-11-41]]

^<<v11-11-41,41>>^ Quanto ao mais dos sucessos de Salomão, e a tudo quanto fez, e à sua sabedoria porventura  não está  escrito no livro dos sucessos de Salomão?

[[v11-11-42]]

^<<v11-11-42,42>>^ E o tempo que reinou Salomão em Jerusalém sobre todo o Israel foram  quarenta anos.

[[v11-11-43]]

^<<v11-11-43,43>>^ E adormeceu Salomão com seus pais, e foi sepultado na cidade de Davi, seu pai: E Roboão, seu filho, reinou em seu lugar.

'''

xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[&#60; Capítulo Anterior] | <<v11-11-0,Topo>> | xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[Próximo Capítulo &#62;]