include::./index.adoc[]

[[v42-24-0]]
=== Lucas, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-24-1]]

^<<v42-24-1,1>>^ E NO primeiro dia  da semana, muito de madrugada, foram elas ao sepulcro, levando as especiarias que tinham preparado.

[[v42-24-2]]

^<<v42-24-2,2>>^ E acharam a pedra revolvida do sepulcro.

[[v42-24-3]]

^<<v42-24-3,3>>^ E, entrando, não acharam o corpo do Senhor Jesus.

[[v42-24-4]]

^<<v42-24-4,4>>^ E aconteceu que, estando elas perplexas a esse respeito, eis que pararam junto delas dois varões, com vestidos resplandecentes.

[[v42-24-5]]

^<<v42-24-5,5>>^ E, estando elas muito atemorizadas, e abaixando o rosto para o chão, eles lhe disseram: Por que buscais o vivente entre os mortos?

[[v42-24-6]]

^<<v42-24-6,6>>^ Não está aqui, mas ressuscitou. Lembrai-vos como vos falou, estando ainda na Galileia,

[[v42-24-7]]

^<<v42-24-7,7>>^ Dizendo: Convém que o Filho do homem seja entregue nas mãos de homens pecadores e seja crucificado, e ao terceiro dia ressuscite.

[[v42-24-8]]

^<<v42-24-8,8>>^ E lembraram-se das suas palavras.

[[v42-24-9]]

^<<v42-24-9,9>>^ E, voltando do sepulcro, anunciaram todas estas coisas aos onze e a todos os demais.

[[v42-24-10]]

^<<v42-24-10,10>>^ E eram Maria Madalena, e Joana, e Maria, mãe  de Tiago, e as outras que  com elas estavam , as que diziam estas coisas  aos apóstolos.

[[v42-24-11]]

^<<v42-24-11,11>>^ E as suas palavras lhes pareciam como desvario, e não as creram.

[[v42-24-12]]

^<<v42-24-12,12>>^ Pedro, porém, levantando-se, correu ao sepulcro, e, abaixando-se, viu só os lenços ali  postos; e retirou-se admirando consigo aquele caso.

[[v42-24-13]]

^<<v42-24-13,13>>^ E eis que no mesmo dia iam dois deles para uma aldeia, que distava de Jerusalém sessenta estádios, cujo nome era  Emaús;

[[v42-24-14]]

^<<v42-24-14,14>>^ E iam falando entre si de tudo aquilo que havia sucedido.

[[v42-24-15]]

^<<v42-24-15,15>>^ E aconteceu que, indo eles falando entre si, e fazendo perguntas um ao outro, o mesmo Jesus se aproximou, e ia com eles.

[[v42-24-16]]

^<<v42-24-16,16>>^ Mas os olhos deles estavam como que fechados, para que o não conhecessem.

[[v42-24-17]]

^<<v42-24-17,17>>^ E ele lhes disse: Que palavras são  essas que, caminhando, trocais entre vós, e por que estais tristes?

[[v42-24-18]]

^<<v42-24-18,18>>^ E, respondendo um, cujo nome era  Cléofas, disse-lhe: És tu só peregrino em Jerusalém, e não sabes as coisas  que nela têm sucedido nestes dias?

[[v42-24-19]]

^<<v42-24-19,19>>^ E ele lhes perguntou: Quais? E eles lhe disseram: As que dizem respeito a Jesus Nazareno, que foi varão profeta, poderoso em obras e palavras diante de Deus e de todo o povo:

[[v42-24-20]]

^<<v42-24-20,20>>^ E como os principais dos sacerdotes e os nossos príncipes o entregaram à condenação de morte, e o crucificaram.

[[v42-24-21]]

^<<v42-24-21,21>>^ E nós esperávamos que fosse ele o que remisse Israel; mas agora, sobre tudo isso, é já hoje o terceiro dia desde que essas coisas aconteceram.

[[v42-24-22]]

^<<v42-24-22,22>>^ É verdade que também algumas mulheres dentre nós nos maravilharam, as quais de madrugada foram ao sepulcro;

[[v42-24-23]]

^<<v42-24-23,23>>^ E, não achando o seu corpo, voltaram, dizendo que também tinham visto uma  visão de anjos, que dizem que ele vive:

[[v42-24-24]]

^<<v42-24-24,24>>^ E alguns dos que estavam conosco foram ao sepulcro, e acharam ser  assim como as mulheres haviam dito; porém a ele não o  viram.

[[v42-24-25]]

^<<v42-24-25,25>>^ E ele lhes disse: Ó néscios, e tardos de coração para crer tudo o que os profetas disseram!

[[v42-24-26]]

^<<v42-24-26,26>>^ Porventura não convinha que o Cristo padecesse estas coisas  e entrasse na sua glória?

[[v42-24-27]]

^<<v42-24-27,27>>^ E, começando por Moisés, e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras.

[[v42-24-28]]

^<<v42-24-28,28>>^ E chegaram à aldeia para onde iam, e ele fez como quem ia para mais longe.

[[v42-24-29]]

^<<v42-24-29,29>>^ E eles o constrangeram, dizendo: Fica conosco, porque já é tarde, e já declinou o dia. E entrou para ficar com eles.

[[v42-24-30]]

^<<v42-24-30,30>>^ E aconteceu que, estando com eles à mesa , tomando o pão, o abençoou e partiu-o, e lho deu.

[[v42-24-31]]

^<<v42-24-31,31>>^ Abriram-se-lhes então os olhos, e o conheceram, e ele desapareceu-lhes.

[[v42-24-32]]

^<<v42-24-32,32>>^ E disseram um para o outro: Porventura não ardia em nós o nosso coração quando, pelo caminho, nos falava, e quando nos abria as Escrituras?

[[v42-24-33]]

^<<v42-24-33,33>>^ E na mesma hora, levantando-se, tornaram para Jerusalém, e acharam congregados os onze, e os que estavam com eles;

[[v42-24-34]]

^<<v42-24-34,34>>^ Os quais diziam: Ressuscitou verdadeiramente o Senhor, e já  apareceu a Simão.

[[v42-24-35]]

^<<v42-24-35,35>>^ E eles lhes contaram o que lhes acontecera no caminho, e como deles foi conhecido no partir do pão.

[[v42-24-36]]

^<<v42-24-36,36>>^ E, falando ele destas coisas , o mesmo Jesus se apresentou no meio deles, e disse-lhes: Paz seja  convosco.

[[v42-24-37]]

^<<v42-24-37,37>>^ E eles, espantados e atemorizados, pensavam que viam algum espírito.

[[v42-24-38]]

^<<v42-24-38,38>>^ E ele lhes disse: Por que estais perturbados, e por que sobem tais  pensamentos aos vossos corações?

[[v42-24-39]]

^<<v42-24-39,39>>^ Vede as minhas mãos e os meus pés, que sou eu mesmo: apalpai-me e vede; pois um espírito não tem carne nem ossos, como vedes que eu tenho.

[[v42-24-40]]

^<<v42-24-40,40>>^ E, dizendo isto, mostrou-lhes as mãos e os pés.

[[v42-24-41]]

^<<v42-24-41,41>>^ E, não o crendo eles ainda por causa da alegria, e estando  maravilhados, disse-lhes: Tendes aqui alguma coisa que comer?

[[v42-24-42]]

^<<v42-24-42,42>>^ Então eles apresentaram-lhes parte de um peixe assado, e um favo de mel.

[[v42-24-43]]

^<<v42-24-43,43>>^ O que ele tomou, e comeu diante deles.

[[v42-24-44]]

^<<v42-24-44,44>>^ E disse-lhes: São  estas as palavras que vos disse estando ainda convosco: Que convinha que se cumprisse tudo o que de mim estava escrito na lei de Moisés, e nos  profetas, e nos  salmos.

[[v42-24-45]]

^<<v42-24-45,45>>^ Então abriu-lhes o entendimento para compreenderem as Escrituras.

[[v42-24-46]]

^<<v42-24-46,46>>^ E disse-lhes: Assim está escrito, e assim convinha que o Cristo padecesse, e ao terceiro dia ressuscitasse dos mortos;

[[v42-24-47]]

^<<v42-24-47,47>>^ E em seu nome se pregasse o arrependimento e a remissão dos pecados, em todas as nações, começando por Jerusalém.

[[v42-24-48]]

^<<v42-24-48,48>>^ E destas coisas  sois vós testemunhas.

[[v42-24-49]]

^<<v42-24-49,49>>^ E eis que sobre vós envio a promessa de meu Pai: ficai, porém, na cidade de Jerusalém, até que do alto sejais revestidos de poder.

[[v42-24-50]]

^<<v42-24-50,50>>^ E levou-os fora, até Betânia; e, levantando as suas mãos, os abençoou.

[[v42-24-51]]

^<<v42-24-51,51>>^ E aconteceu que, abençoando-os ele, se apartou deles e foi elevado ao céu.

[[v42-24-52]]

^<<v42-24-52,52>>^ E, adorando-o eles, tornaram com grande júbilo para Jerusalém.

[[v42-24-53]]

^<<v42-24-53,53>>^ E estavam sempre no templo, louvando e bendizendo a Deus. Amém.

'''

xref:042-lucas/042-lucas-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-joao/043-joao-001.adoc#v43-1-0[Próximo Capítulo &#62;]