include::./index.adoc[]

[[v42-4-0]]
=== Lucas, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-4-1]]

^<<v42-4-1,1>>^ E JESUS, cheio do Espírito Santo, voltou do Jordão e foi levado pelo Espírito ao deserto;

[[v42-4-2]]

^<<v42-4-2,2>>^ E quarenta dias foi tentado pelo diabo, e naqueles dias não comeu coisa alguma; e, terminados eles, teve fome.

[[v42-4-3]]

^<<v42-4-3,3>>^ E disse-lhe o diabo: Se tu és o Filho de Deus, dize a esta pedra que se transforme em pão.

[[v42-4-4]]

^<<v42-4-4,4>>^ E Jesus lhe respondeu, dizendo: Escrito está que nem só de pão viverá o homem, mas de toda a palavra de Deus.

[[v42-4-5]]

^<<v42-4-5,5>>^ E o diabo, levando-o a um alto monte, mostrou-lhe num momento de tempo todos os reinos do mundo.

[[v42-4-6]]

^<<v42-4-6,6>>^ E disse-lhe o diabo: Dar-te-ei a ti todo este poder e a sua glória; porque a mim me foi entregue, e dou-o a quem quero;

[[v42-4-7]]

^<<v42-4-7,7>>^ Portanto, se tu me adorares, tudo será teu.

[[v42-4-8]]

^<<v42-4-8,8>>^ E Jesus, respondendo, disse-lhe: Vai-te, Satanás; porque está escrito: Adorarás o Senhor teu Deus, e só a Ele servirás.

[[v42-4-9]]

^<<v42-4-9,9>>^ Levou-o também a Jerusalém, e pô-lo sobre o pináculo do templo, e disse-lhe: Se tu és o Filho de Deus, lança-te daqui abaixo;

[[v42-4-10]]

^<<v42-4-10,10>>^ Porque está escrito: Mandará aos seus anjos, acerca de ti, que te guardem,

[[v42-4-11]]

^<<v42-4-11,11>>^ E que te sustenham nas mãos, para que nunca tropeces com o teu pé em alguma pedra.

[[v42-4-12]]

^<<v42-4-12,12>>^ E Jesus, respondendo, disse-lhe: Dito está: Não tentarás ao Senhor teu Deus.

[[v42-4-13]]

^<<v42-4-13,13>>^ E, acabando o diabo toda a tentação, ausentou-se dele por algum tempo.

[[v42-4-14]]

^<<v42-4-14,14>>^ Então, pela virtude do Espírito, voltou Jesus para a Galileia, e a sua fama correu por todas as terras em derredor.

[[v42-4-15]]

^<<v42-4-15,15>>^ E ensinava nas suas sinagogas, e por todos era louvado.

[[v42-4-16]]

^<<v42-4-16,16>>^ E, chegando a Nazaré, onde fora criado, entrou num dia de sábado, segundo o seu costume, na sinagoga, e levantou-se para ler.

[[v42-4-17]]

^<<v42-4-17,17>>^ E foi-lhe dado o livro do profeta Isaías; e, quando abriu o livro, achou o lugar em que estava escrito:

[[v42-4-18]]

^<<v42-4-18,18>>^ O Espírito do Senhor é sobre mim, pois que me ungiu para evangelizar os pobres, enviou-me a curar os quebrantados do coração,

[[v42-4-19]]

^<<v42-4-19,19>>^ A apregoar liberdade aos cativos, e dar vista aos cegos; a pôr em liberdade os oprimidos; a anunciar o ano aceitável do Senhor.

[[v42-4-20]]

^<<v42-4-20,20>>^ E, cerrando o livro, e tornando- o  a dar ao ministro, assentou-se; e os olhos de todos na sinagoga estavam fitos nele.

[[v42-4-21]]

^<<v42-4-21,21>>^ Então começou a dizer-lhes: Hoje se cumpriu esta Escritura em vossos ouvidos.

[[v42-4-22]]

^<<v42-4-22,22>>^ E todos lhe davam testemunho, e se maravilhavam das palavras de graça que saíam da sua boca; e diziam: Não é este o filho de José?

[[v42-4-23]]

^<<v42-4-23,23>>^ E ele lhes disse: Sem dúvida me direis este provérbio: Médico, cura-te a ti mesmo: faze também aqui na tua pátria tudo que ouvimos ter sido feito em Capernaum.

[[v42-4-24]]

^<<v42-4-24,24>>^ E disse: Em verdade vos digo que nenhum profeta é bem-recebido na sua pátria.

[[v42-4-25]]

^<<v42-4-25,25>>^ Em verdade vos digo que muitas viúvas existiam em Israel nos dias de Elias, quando o céu se cerrou por três anos e seis meses, de sorte que em toda a terra houve grande fome;

[[v42-4-26]]

^<<v42-4-26,26>>^ E a nenhuma delas foi enviado Elias, senão a Serepta de Sidom, a uma mulher viúva.

[[v42-4-27]]

^<<v42-4-27,27>>^ E muitos leprosos havia em Israel no tempo do profeta Eliseu, e nenhum deles foi purificado, senão Naamã, o siro.

[[v42-4-28]]

^<<v42-4-28,28>>^ E todos, na sinagoga, ouvindo estas coisas, se encheram de ira.

[[v42-4-29]]

^<<v42-4-29,29>>^ E, levantando-se, o expulsaram da cidade, e o levaram até ao cume do monte em que a cidade deles estava edificada, para dali o precipitarem.

[[v42-4-30]]

^<<v42-4-30,30>>^ Ele, porém, passando pelo meio deles, retirou-se.

[[v42-4-31]]

^<<v42-4-31,31>>^ E desceu a Capernaum, cidade da Galileia, e os ensinava nos sábados.

[[v42-4-32]]

^<<v42-4-32,32>>^ E admiravam a sua doutrina porque a sua palavra era com autoridade.

[[v42-4-33]]

^<<v42-4-33,33>>^ E estava na sinagoga um homem que tinha um espírito de um demônio imundo, e exclamou em alta voz,

[[v42-4-34]]

^<<v42-4-34,34>>^ Dizendo: Ah! que temos nós contigo, Jesus Nazareno? vieste a destruir-nos? Bem sei quem és: o Santo de Deus.

[[v42-4-35]]

^<<v42-4-35,35>>^ E Jesus o repreendeu, dizendo: Cala-te, e sai dele. E o demônio, lançando-o por terra no meio do povo, saiu dele sem lhe fazer mal.

[[v42-4-36]]

^<<v42-4-36,36>>^ E veio espanto sobre todos, e falavam entre si uns e outros dizendo: Que palavra é  esta que até aos espíritos imundos manda com autoridade e poder e eles saem?

[[v42-4-37]]

^<<v42-4-37,37>>^ E a sua fama divulgava-se por todos os lugares, em redor daquela comarca.

[[v42-4-38]]

^<<v42-4-38,38>>^ Ora, levantando-se Jesus da sinagoga, entrou em casa de Simão; e a sogra de Simão estava enferma com muita febre, e rogaram-lhe por ela.

[[v42-4-39]]

^<<v42-4-39,39>>^ E, inclinando-se para ela, repreendeu a febre, e esta  a deixou. E ela, levantando-se logo, servia-os.

[[v42-4-40]]

^<<v42-4-40,40>>^ E, ao pôr do sol, todos os que tinham enfermos de várias doenças lhos traziam; e, pondo as mãos sobre cada um deles, os curava.

[[v42-4-41]]

^<<v42-4-41,41>>^ E também de muitos saíam demônios, clamando e dizendo: Tu és o Cristo, o Filho de Deus. E ele, repreendendo- os , não os deixava falar, pois sabiam que ele era o Cristo.

[[v42-4-42]]

^<<v42-4-42,42>>^ E, sendo já dia, saiu, e foi para um lugar deserto; e a multidão o procurava, e chegou junto dele; e o detinham, para que não se ausentasse deles.

[[v42-4-43]]

^<<v42-4-43,43>>^ Ele, porém, lhes disse: Também é necessário que eu anuncie a outras cidades o evangelho do reino de Deus; porque para isso fui enviado.

[[v42-4-44]]

^<<v42-4-44,44>>^ E pregava nas sinagogas da Galileia.

'''

xref:042-lucas/042-lucas-003.adoc#v42-3-0[&#60; Capítulo Anterior] | <<v42-4-0,Topo>> | xref:042-lucas/042-lucas-005.adoc#v42-5-0[Próximo Capítulo &#62;]