include::./index.adoc[]

[[v42-11-0]]
=== Lucas, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-11-1]]

^<<v42-11-1,1>>^ E ACONTECEU que, estando ele a orar num certo lugar, quando acabou lhe disse um dos seus discípulos: Senhor, ensina-nos a orar, como também João ensinou aos seus discípulos.

[[v42-11-2]]

^<<v42-11-2,2>>^ E ele lhes disse: Quando orardes, dizei: Pai, santificado seja o teu nome; venha o teu reino;

[[v42-11-3]]

^<<v42-11-3,3>>^ Dá-nos cada dia o nosso pão cotidiano;

[[v42-11-4]]

^<<v42-11-4,4>>^ E perdoa-nos os nossos pecados, pois também nós perdoamos a qualquer que nos deve; e não nos conduzas em tentação, mas livra-nos do mal.

[[v42-11-5]]

^<<v42-11-5,5>>^ Disse-lhes também: Qual de vós terá um amigo, e, se for procurá-lo à meia-noite, e lhe disser: Amigo, empresta-me três pães,

[[v42-11-6]]

^<<v42-11-6,6>>^ Pois que um amigo meu chegou a minha casa, vindo  de caminho, e não tenho que apresentar-lhe;

[[v42-11-7]]

^<<v42-11-7,7>>^ Se ele, respondendo de dentro, disser: Não me importunes; já está a porta fechada, e os meus filhos estão comigo na cama: não posso levantar-me para t os  dar;

[[v42-11-8]]

^<<v42-11-8,8>>^ Digo-vos que, ainda que se não levante a dar-lh os , por ser seu amigo, levantar-se-á, todavia, por causa da sua importunação, e lhe dará tudo o que houver mister.

[[v42-11-9]]

^<<v42-11-9,9>>^ E eu vos digo a vós: Pedi e dar-se-vos-á: buscai, e achareis: batei, e abrir-se-vos-á;

[[v42-11-10]]

^<<v42-11-10,10>>^ Porque qualquer que pede recebe; e quem busca acha; e a quem bate abrir-se-lhe-á.

[[v42-11-11]]

^<<v42-11-11,11>>^ E qual o pai dentre vós que, se o filho lhe pedir pão, lhe dará uma pedra? Ou também, se lhe pedir  peixe, lhe dará por peixe uma serpente?

[[v42-11-12]]

^<<v42-11-12,12>>^ Ou também, se lhe pedir um ovo, lhe dará um escorpião?

[[v42-11-13]]

^<<v42-11-13,13>>^ Pois se vós, sendo maus, sabeis dar boas dádivas aos vossos filhos, quanto mais dará o Pai celestial o Espírito Santo àqueles que lho pedirem?

[[v42-11-14]]

^<<v42-11-14,14>>^ E estava ele expulsando um demônio, o qual era mudo. E aconteceu que, saindo o demônio, o mudo falou; e maravilhou-se a multidão.

[[v42-11-15]]

^<<v42-11-15,15>>^ Mas alguns deles diziam: Ele expulsa os demônios por Belzebu, príncipe dos demônios.

[[v42-11-16]]

^<<v42-11-16,16>>^ E outros, tentando- o , pediam-lhe um sinal do céu.

[[v42-11-17]]

^<<v42-11-17,17>>^ Mas, conhecendo ele os seus pensamentos, disse-lhes: Todo o reino, dividido contra si mesmo, será assolado; e a casa, dividida  contra si mesma, cairá.

[[v42-11-18]]

^<<v42-11-18,18>>^ E, se também Satanás está dividido contra si mesmo, como subsistirá o seu reino? Pois dizeis que eu expulso os demônios por Belzebu.

[[v42-11-19]]

^<<v42-11-19,19>>^ E, se eu expulso os demônios por Belzebu, por quem os  expulsam vossos filhos? Eles pois serão os vossos juízes.

[[v42-11-20]]

^<<v42-11-20,20>>^ Mas, se eu expulso os demônios pelo dedo de Deus, certamente a vós é chegado o reino de Deus.

[[v42-11-21]]

^<<v42-11-21,21>>^ Quando o valente guarda, armado, a sua casa, em segurança está tudo quanto tem;

[[v42-11-22]]

^<<v42-11-22,22>>^ Mas, sobrevindo outro mais valente do que ele, e vencendo-o, tira- lhe  toda a sua armadura em que confiava, e reparte os seus despojos.

[[v42-11-23]]

^<<v42-11-23,23>>^ Quem não é comigo é contra mim; e quem comigo não ajunta espalha.

[[v42-11-24]]

^<<v42-11-24,24>>^ Quando o espírito imundo tem saído do homem, anda por lugares secos, buscando repouso; e, não o  achando, diz: Tornarei para minha casa, donde saí.

[[v42-11-25]]

^<<v42-11-25,25>>^ E, chegando, acha- a  varrida e adornada.

[[v42-11-26]]

^<<v42-11-26,26>>^ Então vai, e leva consigo outros sete espíritos piores do que ele, e, entrando, habitam ali; e o último estado desse homem é pior do que o primeiro.

[[v42-11-27]]

^<<v42-11-27,27>>^ E aconteceu que, dizendo ele estas coisas , uma mulher dentre a multidão, levantando a voz, lhe disse: Bem-aventurado o ventre que te trouxe e os peitos em que mamaste.

[[v42-11-28]]

^<<v42-11-28,28>>^ Mas ele disse: Antes bem-aventurados os que ouvem a palavra de Deus e a guardam.

[[v42-11-29]]

^<<v42-11-29,29>>^ E, ajuntando-se a multidão, começou a dizer: Maligna é esta geração; ela pede um sinal; e não lhe será dado outro sinal, senão o sinal do profeta Jonas;

[[v42-11-30]]

^<<v42-11-30,30>>^ Porquanto assim como Jonas foi sinal para os ninivitas, assim o Filho do homem o  será também para esta geração.

[[v42-11-31]]

^<<v42-11-31,31>>^ A rainha do sul se levantará no juízo com os homens desta geração, e os condenará; pois até dos confins da terra veio ouvir a sabedoria de Salomão; e eis aqui está quem é maior do que Salomão.

[[v42-11-32]]

^<<v42-11-32,32>>^ Os homens de Nínive se levantarão no juízo com esta geração, e a condenarão; pois se converteram com pregação de Jonas; e eis aqui está quem é maior do que Jonas.

[[v42-11-33]]

^<<v42-11-33,33>>^ E ninguém, acendendo uma candeia, a põe em oculto, nem debaixo do alqueire, mas no velador, para que os que entram vejam a luz.

[[v42-11-34]]

^<<v42-11-34,34>>^ A candeia do corpo é o olho. Sendo pois o teu olho simples, também todo o teu corpo será luminoso; mas, se for mau, também o teu corpo será tenebroso.

[[v42-11-35]]

^<<v42-11-35,35>>^ Vê pois que a luz que em ti há não sejam trevas.

[[v42-11-36]]

^<<v42-11-36,36>>^ Se, pois, todo o teu corpo é luminoso, não tendo em trevas parte alguma, todo será luminoso, como quando a candeia te alumia com o seu resplendor.

[[v42-11-37]]

^<<v42-11-37,37>>^ E, estando ele ainda  falando, rogou-lhe um fariseu que fosse jantar com ele; e, entrando, assentou-se à mesa.

[[v42-11-38]]

^<<v42-11-38,38>>^ Mas o fariseu admirou-se, vendo que se não lavara antes do jantar.

[[v42-11-39]]

^<<v42-11-39,39>>^ E o Senhor lhe disse: Agora vós, os fariseus, limpais o exterior do copo e do prato; mas o vosso interior está cheio de rapina e maldade.

[[v42-11-40]]

^<<v42-11-40,40>>^ Loucos! o que fez o exterior não fez também o interior?

[[v42-11-41]]

^<<v42-11-41,41>>^ Dai antes esmola do que tiverdes, e eis que tudo vos será limpo.

[[v42-11-42]]

^<<v42-11-42,42>>^ Mas ai de vós, fariseus, que dizimais a hortelã, e a arruda, e toda a hortaliça, e desprezais o juízo e o amor de Deus. Importava fazer estas coisas, e não deixar as outras.

[[v42-11-43]]

^<<v42-11-43,43>>^ Ai de vós, fariseus, que amais os primeiros assentos nas sinagogas, e as saudações nas praças.

[[v42-11-44]]

^<<v42-11-44,44>>^ Ai de vós, escribas e fariseus hipócritas, que sois como as sepulturas que não aparecem, e os homens que sobre elas  andam não o  sabem.

[[v42-11-45]]

^<<v42-11-45,45>>^ E, respondendo um dos doutores da lei, disse-lhe: Mestre, quando dizes isso também nos afrontas a nós.

[[v42-11-46]]

^<<v42-11-46,46>>^ E ele lhe disse: Ai de vós também, doutores da lei, que carregais os homens com cargas difíceis de transportar, e vós mesmos nem ainda com um dos vossos dedos tocais essas cargas.

[[v42-11-47]]

^<<v42-11-47,47>>^ Ai de vós que edificais os sepulcros dos profetas, e vossos pais os mataram.

[[v42-11-48]]

^<<v42-11-48,48>>^ Bem testificais, pois, que consentis nas obras de vossos pais; porque eles os mataram, e vós edificais os seus sepulcros.

[[v42-11-49]]

^<<v42-11-49,49>>^ Por isso diz também a sabedoria de Deus: Profetas e apóstolos lhes mandarei; e eles matarão uns , e perseguirão outros ;

[[v42-11-50]]

^<<v42-11-50,50>>^ Para que desta geração seja requerido o sangue de todos os profetas que, desde a fundação do mundo, foi derramado;

[[v42-11-51]]

^<<v42-11-51,51>>^ Desde o sangue de Abel, até ao sangue de Zacarias, que foi morto entre o altar e o templo; assim, vos digo, será requerido desta geração.

[[v42-11-52]]

^<<v42-11-52,52>>^ Ai de vós, doutores da lei, que tirastes a chave da ciência; vós mesmos não entrastes, e impedistes os que entravam.

[[v42-11-53]]

^<<v42-11-53,53>>^ E, dizendo-lhes ele isto, começaram os escribas e os fariseus a apertá-lo fortemente, e a fazê-lo falar acerca de muitas coisas.

[[v42-11-54]]

^<<v42-11-54,54>>^ Armando-lhe ciladas, a fim de apanharem da sua boca alguma coisa para o acusarem.

'''

xref:042-lucas/042-lucas-010.adoc#v42-10-0[&#60; Capítulo Anterior] | <<v42-11-0,Topo>> | xref:042-lucas/042-lucas-012.adoc#v42-12-0[Próximo Capítulo &#62;]