include::./index.adoc[]

[[v42-7-0]]
=== Lucas, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-7-1]]

^<<v42-7-1,1>>^ E, DEPOIS de concluir todos estes discursos perante o povo, entrou em Capernaum.

[[v42-7-2]]

^<<v42-7-2,2>>^ E o servo de um certo centurião, a quem muito estimava, estava doente, e moribundo.

[[v42-7-3]]

^<<v42-7-3,3>>^ E, quando ouviu falar  de Jesus, enviou-lhe uns anciãos dos judeus, rogando-lhe que viesse curar o seu servo.

[[v42-7-4]]

^<<v42-7-4,4>>^ E, chegando eles junto de Jesus, rogaram-lhe muito, dizendo: É digno de que lhe concedas isto.

[[v42-7-5]]

^<<v42-7-5,5>>^ Porque ama a nossa nação, e ele mesmo nos edificou a sinagoga.

[[v42-7-6]]

^<<v42-7-6,6>>^ E foi Jesus com eles; mas, quando já estava perto da casa, enviou-lhe o centurião uns amigos, dizendo-lhe: Senhor, não te incomodes, porque não sou digno de que entres debaixo do meu telhado;

[[v42-7-7]]

^<<v42-7-7,7>>^ E por isso nem ainda me julguei digno de ir ter contigo; dize, porém, uma palavra, e o meu criado sarará.

[[v42-7-8]]

^<<v42-7-8,8>>^ Porque também eu sou homem sujeito à autoridade, e tenho soldados sob o meu poder, e digo a este: Vai; e ele vai; e a outro: Vem; e ele vem; e ao meu servo: Faze isto; e ele o faz.

[[v42-7-9]]

^<<v42-7-9,9>>^ E, ouvindo isto Jesus, maravilhou-se dele, e, voltando-se, disse à multidão que o seguia: Digo-vos que  nem ainda em Israel tenho achado tanta fé.

[[v42-7-10]]

^<<v42-7-10,10>>^ E, voltando para casa os que foram enviados, acharam são o servo enfermo.

[[v42-7-11]]

^<<v42-7-11,11>>^ E aconteceu pouco depois ir ele à cidade chamada Naim, e com ele iam muitos dos seus discípulos, e uma grande multidão;

[[v42-7-12]]

^<<v42-7-12,12>>^ E quando chegou perto da porta da cidade, eis que levavam um defunto, filho único de sua mãe, que era  viúva; e com ela ia uma grande multidão da cidade.

[[v42-7-13]]

^<<v42-7-13,13>>^ E, vendo-a, o Senhor moveu-se de íntima compaixão por ela, e disse-lhe: Não chores.

[[v42-7-14]]

^<<v42-7-14,14>>^ E, chegando-se, tocou o esquife (e os que o  levavam pararam), e disse: Mancebo, a ti te digo: Levanta-te.

[[v42-7-15]]

^<<v42-7-15,15>>^ E o defunto assentou-se, e começou a falar. E entregou-o a sua mãe.

[[v42-7-16]]

^<<v42-7-16,16>>^ E de todos se apoderou o temor, e glorificavam a Deus, dizendo: Um grande profeta se levantou entre nós, e Deus visitou o seu povo.

[[v42-7-17]]

^<<v42-7-17,17>>^ E correu dele esta fama por toda a Judeia e por toda a terra circunvizinha.

[[v42-7-18]]

^<<v42-7-18,18>>^ E os discípulos de João anunciaram-lhe todas estas coisas.

[[v42-7-19]]

^<<v42-7-19,19>>^ E João, chamando dois dos seus discípulos, enviou- os  a Jesus, dizendo: És tu aquele que havia de vir, ou esperamos outro?

[[v42-7-20]]

^<<v42-7-20,20>>^ E, quando aqueles homens chegaram junto dele, disseram: João Batista enviou-nos a perguntar-te: És tu aquele que havia de vir, ou esperamos outro?

[[v42-7-21]]

^<<v42-7-21,21>>^ E, na mesma hora, curou muitos de enfermidades, e males, e espíritos maus, e deu vista a muitos cegos.

[[v42-7-22]]

^<<v42-7-22,22>>^ Respondendo então Jesus, disse-lhes: Ide, e anunciai a João o que tendes visto e ouvido: que os cegos veem, os coxos andam, os leprosos são purificados, os surdos ouvem, os mortos ressuscitam e aos pobres anuncia-se o Evangelho.

[[v42-7-23]]

^<<v42-7-23,23>>^ E bem-aventurado aquele que em mim se não escandalizar.

[[v42-7-24]]

^<<v42-7-24,24>>^ E, tendo-se retirado os mensageiros de João, começou a dizer à multidão acerca de João: Que saístes a ver no deserto? uma cana abalada pelo vento?

[[v42-7-25]]

^<<v42-7-25,25>>^ Mas que saístes a ver? um homem trajado de vestidos delicados? Eis que os que andam com preciosos vestidos, e em delícias, estão nos paços reais.

[[v42-7-26]]

^<<v42-7-26,26>>^ Mas que saístes a ver? um profeta? sim, vos digo, e muito mais do que profeta.

[[v42-7-27]]

^<<v42-7-27,27>>^ Este é aquele de quem está escrito: Eis que envio o meu anjo diante da tua face, o qual preparará diante de ti o teu caminho.

[[v42-7-28]]

^<<v42-7-28,28>>^ E eu vos digo que, entre os nascidos de mulheres, não há maior profeta do que João Batista; mas o menor no reino de Deus é maior do que ele.

[[v42-7-29]]

^<<v42-7-29,29>>^ E todo o povo que o ouviu e os publicanos, tendo sido batizados com o batismo de João, justificaram a Deus.

[[v42-7-30]]

^<<v42-7-30,30>>^ Mas os fariseus e os doutores da lei rejeitaram o conselho de Deus contra si mesmos, não tendo sido batizados por ele.

[[v42-7-31]]

^<<v42-7-31,31>>^ E disse o Senhor: A quem pois compararei os homens desta geração, e a quem são semelhantes?

[[v42-7-32]]

^<<v42-7-32,32>>^ São semelhantes aos meninos que, assentados nas praças, clamam uns aos outros, e dizem: Tocamos-vos flauta, e não dançastes; cantamos-vos lamentações, e não chorastes.

[[v42-7-33]]

^<<v42-7-33,33>>^ Porque veio João Batista, que não comia pão nem bebia vinho, e dizeis: Tem demônio;

[[v42-7-34]]

^<<v42-7-34,34>>^ Veio o Filho do homem, que come e bebe, e dizeis: Eis aí um homem comilão, e bebedor de vinho, amigo dos publicanos e dos pecadores.

[[v42-7-35]]

^<<v42-7-35,35>>^ Mas a sabedoria é justificada por todos os seus filhos.

[[v42-7-36]]

^<<v42-7-36,36>>^ E rogou-lhe um dos fariseus que comesse com ele; e, entrando em casa do fariseu, assentou-se à mesa.

[[v42-7-37]]

^<<v42-7-37,37>>^ E eis que uma mulher da cidade, uma pecadora, sabendo que ele estava à mesa em casa do fariseu, levou um vaso de alabastro com unguento;

[[v42-7-38]]

^<<v42-7-38,38>>^ E, estando por detrás, aos seus pés, chorando, começou a regar-lhe os pés com lágrimas, e enxugava-lhos com os cabelos da sua cabeça; e beijava-lhe os pés, e ungia-lhos com o unguento.

[[v42-7-39]]

^<<v42-7-39,39>>^ Quando isto  viu o fariseu que o tinha convidado, falava consigo, dizendo: Se este fora profeta, bem saberia quem e qual é  a mulher que lhe tocou, pois é uma pecadora.

[[v42-7-40]]

^<<v42-7-40,40>>^ E respondendo, Jesus, disse-lhe: Simão, uma coisa tenho a dizer-te. E ele disse: Dize-a, Mestre.

[[v42-7-41]]

^<<v42-7-41,41>>^ Um certo credor tinha dois devedores; um devia- lhe  quinhentos dinheiros, e outro cinquenta.

[[v42-7-42]]

^<<v42-7-42,42>>^ E, não tendo eles com que pagar, perdoou-lhes a ambos. Dize pois: qual deles o amará mais?

[[v42-7-43]]

^<<v42-7-43,43>>^ E Simão, respondendo, disse: Tenho para mim que é aquele a quem mais perdoou. E ele lhe disse: Julgaste bem.

[[v42-7-44]]

^<<v42-7-44,44>>^ E, voltando-se para a mulher, disse a Simão: Vês tu esta mulher? Entrei em tua casa, e não me deste água para os pés; mas esta regou-me os pés com lágrimas, e mos enxugou com os seus cabelos.

[[v42-7-45]]

^<<v42-7-45,45>>^ Não me deste ósculo, mas esta, desde que entrou, não tem cessado de me beijar os pés.

[[v42-7-46]]

^<<v42-7-46,46>>^ Não me ungiste a cabeça com óleo, mas esta ungiu-me os pés com unguento.

[[v42-7-47]]

^<<v42-7-47,47>>^ Por isso te digo que os seus muitos pecados lhe  são perdoados, porque muito amou; mas aquele a quem pouco é perdoado pouco ama.

[[v42-7-48]]

^<<v42-7-48,48>>^ E disse-lhe a ela: Os teus pecados te  são perdoados.

[[v42-7-49]]

^<<v42-7-49,49>>^ E os que estavam à mesa  começaram a dizer entre si: Quem é este, que até perdoa pecados?

[[v42-7-50]]

^<<v42-7-50,50>>^ E disse à mulher: A tua fé te salvou: vai-te em paz.

'''

xref:042-lucas/042-lucas-006.adoc#v42-6-0[&#60; Capítulo Anterior] | <<v42-7-0,Topo>> | xref:042-lucas/042-lucas-008.adoc#v42-8-0[Próximo Capítulo &#62;]