include::./index.adoc[]

[[v42-16-0]]
=== Lucas, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-16-1]]

^<<v42-16-1,1>>^ E DIZIA também aos seus discípulos: Havia um certo homem rico, o qual tinha um mordomo; e este foi acusado perante ele de dissipar os seus bens.

[[v42-16-2]]

^<<v42-16-2,2>>^ E ele, chamando-o, disse-lhe: Que é isto que ouço de ti? Dá contas da tua mordomia, porque já não poderás ser mais meu mordomo.

[[v42-16-3]]

^<<v42-16-3,3>>^ E o mordomo disse consigo: Que farei, pois que o meu senhor me tira a mordomia? Cavar, não posso; de mendigar, tenho vergonha.

[[v42-16-4]]

^<<v42-16-4,4>>^ Eu sei o que hei de fazer, para que, quando for desapossado da mordomia, me recebam em suas casas.

[[v42-16-5]]

^<<v42-16-5,5>>^ E, chamando a si  cada um dos devedores do seu senhor, disse ao primeiro: Quanto deves ao meu senhor?

[[v42-16-6]]

^<<v42-16-6,6>>^ E ele respondeu: Cem medidas de azeite. E disse-lhe: Toma a tua obrigação, e, assentando-te já, escreve cinquenta.

[[v42-16-7]]

^<<v42-16-7,7>>^ Disse depois a outro: E tu quanto deves? E ele respondeu: Cem alqueires de trigo. E disse-lhe: Toma a tua obrigação, e escreve oitenta.

[[v42-16-8]]

^<<v42-16-8,8>>^ E louvou aquele senhor o injusto mordomo por haver procedido prudentemente, porque os filhos deste mundo são mais prudentes na sua geração do que os filhos da luz.

[[v42-16-9]]

^<<v42-16-9,9>>^ E eu vos digo: Granjeai amigos com as riquezas da injustiça; para que, quando estas vos faltarem, vos recebam eles nos tabernáculos eternos.

[[v42-16-10]]

^<<v42-16-10,10>>^ Quem é fiel no mínimo, também é fiel no muito; quem é injusto no mínimo, também é injusto no muito.

[[v42-16-11]]

^<<v42-16-11,11>>^ Pois, se nas riquezas injustas não fostes fiéis, quem vos confiará as verdadeiras?

[[v42-16-12]]

^<<v42-16-12,12>>^ E, se no alheio não fostes fiéis, quem vos dará o que é vosso?

[[v42-16-13]]

^<<v42-16-13,13>>^ Nenhum servo pode servir dois senhores; porque, ou há de aborrecer um e amar o outro, ou se há de chegar a um e desprezar o outro. Não podeis servir a Deus e a Mamom.

[[v42-16-14]]

^<<v42-16-14,14>>^ E os fariseus, que eram avarentos, ouviam todas estas coisas , e zombavam dele.

[[v42-16-15]]

^<<v42-16-15,15>>^ E disse-lhes: Vós sois os que vos justificais a vós mesmos diante dos homens, mas Deus conhece os vossos corações, porque, o que entre os homens é elevado, perante Deus é abominação.

[[v42-16-16]]

^<<v42-16-16,16>>^ A lei e os profetas duraram  até João: desde então é anunciado o reino de Deus, e todo o homem emprega força para entrar nele.

[[v42-16-17]]

^<<v42-16-17,17>>^ E é mais fácil passar o céu e a terra do que cair um til da lei.

[[v42-16-18]]

^<<v42-16-18,18>>^ Qualquer que deixa sua mulher, e casa com outra, adultera; e aquele que casa com a repudiada pelo marido adultera também.

[[v42-16-19]]

^<<v42-16-19,19>>^ Ora, havia um homem rico, e vestia-se de púrpura e de linho finíssimo, e vivia todos os dias regalada e esplendidamente.

[[v42-16-20]]

^<<v42-16-20,20>>^ Havia também um  certo mendigo, chamado Lázaro, que jazia cheio de chagas à porta daquele.

[[v42-16-21]]

^<<v42-16-21,21>>^ E desejava alimentar-se com as migalhas que caíam da mesa do rico; e os próprios cães vinham lamber-lhe as chagas.

[[v42-16-22]]

^<<v42-16-22,22>>^ E aconteceu que o mendigo morreu, e foi levado pelos anjos para o seio d’Abraão; e morreu também o rico, e foi sepultado.

[[v42-16-23]]

^<<v42-16-23,23>>^ E no Hades, ergueu os olhos, estando em tormentos, e viu ao longe Abraão, e Lázaro no seu seio.

[[v42-16-24]]

^<<v42-16-24,24>>^ E, clamando, disse: Pai Abraão, tem misericórdia de mim, e manda a Lázaro que molhe na água a ponta do seu dedo e me refresque a língua, porque estou atormentado nesta chama.

[[v42-16-25]]

^<<v42-16-25,25>>^ Disse, porém, Abraão: Filho, lembra-te de que recebeste os teus bens em tua vida, e Lázaro somente males; e agora este é consolado e tu atormentado;

[[v42-16-26]]

^<<v42-16-26,26>>^ E, além disso, está posto um grande abismo entre nós e vós, de sorte que os que quisessem passar daqui para vós não poderiam, nem tão pouco os de lá passar para cá.

[[v42-16-27]]

^<<v42-16-27,27>>^ E disse ele: Rogo-te pois, ó pai, que o mandes a casa de meu pai.

[[v42-16-28]]

^<<v42-16-28,28>>^ Pois tenho cinco irmãos; para que lhes dê testemunho, a fim de que não venham também para este lugar de tormento.

[[v42-16-29]]

^<<v42-16-29,29>>^ Disse-lhe Abraão: Têm Moisés e os profetas; ouçam-nos.

[[v42-16-30]]

^<<v42-16-30,30>>^ E disse ele: Não, pai Abraão; mas, se algum dos mortos fosse ter com eles, arrepender-se-iam.

[[v42-16-31]]

^<<v42-16-31,31>>^ Porém Abraão lhe disse: Se não ouvem a Moisés e aos profetas, tão pouco acreditarão, ainda que algum dos mortos ressuscite.

'''

xref:042-lucas/042-lucas-015.adoc#v42-15-0[&#60; Capítulo Anterior] | <<v42-16-0,Topo>> | xref:042-lucas/042-lucas-017.adoc#v42-17-0[Próximo Capítulo &#62;]