include::./index.adoc[]

[[v42-5-0]]
=== Lucas, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-5-1]]

^<<v42-5-1,1>>^ E ACONTECEU que, apertando-o a multidão, para ouvir a palavra de Deus, estava ele junto ao lago de Genesaré;

[[v42-5-2]]

^<<v42-5-2,2>>^ E viu estar dois barcos junto à praia  do lago; e os pescadores, havendo descido deles, estavam lavando as redes.

[[v42-5-3]]

^<<v42-5-3,3>>^ E, entrando num dos barcos, que era o de Simão, pediu-lhe que o afastasse um pouco da terra; e, assentando-se, ensinava do barco a multidão.

[[v42-5-4]]

^<<v42-5-4,4>>^ E, quando acabou de falar, disse a Simão: Faze-te ao mar alto, e lançai as vossas redes para pescar.

[[v42-5-5]]

^<<v42-5-5,5>>^ E, respondendo Simão, disse-lhe: Mestre, havendo trabalhado toda a noite, nada apanhamos; mas, sobre tua palavra, lançarei a rede.

[[v42-5-6]]

^<<v42-5-6,6>>^ E, fazendo assim, colheram uma grande quantidade de peixes, e rompia-se-lhes a rede.

[[v42-5-7]]

^<<v42-5-7,7>>^ E fizeram sinal aos companheiros que estavam no outro barco, para que os fossem ajudar. E foram, e encheram ambos os barcos, de maneira tal que quase iam a pique.

[[v42-5-8]]

^<<v42-5-8,8>>^ E, vendo isto Simão Pedro, prostrou-se aos pés de Jesus, dizendo: Senhor, ausenta-te de mim, que sou um homem pecador.

[[v42-5-9]]

^<<v42-5-9,9>>^ Pois que o espanto se apoderara dele, e de todos os que com ele estavam, por causa da pesca de peixe que haviam feito;

[[v42-5-10]]

^<<v42-5-10,10>>^ E, de igual modo, também de Tiago e João, filhos de Zebedeu, que eram companheiros de Simão. E disse Jesus a Simão: Não temas: de agora em diante serás pescador de homens.

[[v42-5-11]]

^<<v42-5-11,11>>^ E, levando os barcos para terra, deixaram tudo, e o seguiram.

[[v42-5-12]]

^<<v42-5-12,12>>^ E aconteceu que, quando estava numa daquelas cidades, eis que um homem cheio de lepra, vendo a Jesus, prostrou-se sobre o rosto, e rogou-lhe, dizendo: Senhor, se quiseres, bem podes limpar-me.

[[v42-5-13]]

^<<v42-5-13,13>>^ E ele, estendendo a mão, tocou-lhe, dizendo: Quero; sê limpo. E logo a lepra desapareceu dele,

[[v42-5-14]]

^<<v42-5-14,14>>^ E ordenou-lhe que a ninguém o dissesse. Mas vai, disse , mostra-te ao sacerdote, e oferece, pela tua purificação, o que Moisés determinou, para que lhes sirva de testemunho.

[[v42-5-15]]

^<<v42-5-15,15>>^ Porém a sua fama se propagava ainda mais, e ajuntava-se muita gente para o ouvir e para ser por ele curada das suas enfermidades.

[[v42-5-16]]

^<<v42-5-16,16>>^ Porém ele retirava-se para os desertos, e ali  orava.

[[v42-5-17]]

^<<v42-5-17,17>>^ E aconteceu que, num daqueles dias, estava ensinando, e estavam ali  assentados fariseus e doutores da lei, que tinham vindo de todas as aldeias da Galileia, e da Judeia, e de Jerusalém. E a virtude do Senhor estava com ele para curar.

[[v42-5-18]]

^<<v42-5-18,18>>^ E eis que uns  homens transportaram numa cama um homem que estava paralítico, e procuravam fazê-lo entrar e pô-lo diante dele;

[[v42-5-19]]

^<<v42-5-19,19>>^ E, não achando por onde o pudessem levar, por causa da multidão, subiram ao telhado, e por entre as telhas o baixaram com a cama, até ao meio, diante de Jesus.

[[v42-5-20]]

^<<v42-5-20,20>>^ E, vendo ele a fé deles, disse-lhe: Homem, os teus pecados te são perdoados.

[[v42-5-21]]

^<<v42-5-21,21>>^ E os escribas e os fariseus começaram a arrazoar, dizendo: Quem é este que diz blasfêmias? Quem pode perdoar pecados, senão só Deus?

[[v42-5-22]]

^<<v42-5-22,22>>^ Jesus, porém, conhecendo os seus pensamentos, respondeu, e disse-lhes: Que arrazoais em vossos corações?

[[v42-5-23]]

^<<v42-5-23,23>>^ Qual é mais fácil? dizer: Os teus pecados te são perdoados; ou dizer: Levanta-te, e anda?

[[v42-5-24]]

^<<v42-5-24,24>>^ Ora, para que saibais que o Filho do homem tem sobre a terra poder de perdoar pecados (disse ao paralítico), a ti te digo: Levanta-te, toma a tua cama, e vai para tua casa.

[[v42-5-25]]

^<<v42-5-25,25>>^ E, levantando-se logo diante deles, e tomando a cama em que estava deitado, foi para sua casa, glorificando a Deus.

[[v42-5-26]]

^<<v42-5-26,26>>^ E todos ficaram maravilhados, e glorificaram a Deus; e ficaram cheios de temor, dizendo: Hoje vimos prodígios.

[[v42-5-27]]

^<<v42-5-27,27>>^ E, depois disto, saiu, e viu um publicano, chamado Levi, assentado na recebedoria, e disse-lhe: Segue-me.

[[v42-5-28]]

^<<v42-5-28,28>>^ E ele, deixando tudo, levantou-se e o seguiu.

[[v42-5-29]]

^<<v42-5-29,29>>^ E fez-lhe Levi um grande banquete em sua casa; e havia ali  uma multidão de publicanos e outros que estavam com eles à mesa.

[[v42-5-30]]

^<<v42-5-30,30>>^ E os escribas deles, e os fariseus, murmuravam contra os seus discípulos, dizendo: Por que comeis e bebeis com publicanos e pecadores?

[[v42-5-31]]

^<<v42-5-31,31>>^ E Jesus, respondendo, disse-lhes: Não necessitam de médico os que estão sãos, mas, sim, os que estão enfermos;

[[v42-5-32]]

^<<v42-5-32,32>>^ Eu não vim chamar os justos, mas, sim, os pecadores, ao arrependimento.

[[v42-5-33]]

^<<v42-5-33,33>>^ Disseram-lhe então eles: Por que jejuam os discípulos de João muitas vezes, e fazem orações, como também os  dos fariseus, mas os teus comem e bebem?

[[v42-5-34]]

^<<v42-5-34,34>>^ E ele lhes disse: Podeis vós fazer jejuar os filhos das bodas, enquanto o esposo está com eles?

[[v42-5-35]]

^<<v42-5-35,35>>^ Dias virão, porém, em que o esposo lhes será tirado, e  então, naqueles dias, jejuarão.

[[v42-5-36]]

^<<v42-5-36,36>>^ E disse-lhes também uma parábola: Ninguém tira um pedaço dum vestido novo para o coser em vestido velho, pois que romperá o novo e o remendo não condiz com o velho.

[[v42-5-37]]

^<<v42-5-37,37>>^ E ninguém deita vinho novo em odres velhos; doutra sorte o vinho novo romperá os odres, e entornar-se-á o vinho, e os odres se estragarão;

[[v42-5-38]]

^<<v42-5-38,38>>^ Mas o vinho novo deve deitar-se em odres novos, e ambos juntamente se conservarão.

[[v42-5-39]]

^<<v42-5-39,39>>^ E ninguém tendo bebido o velho quer logo o novo, porque diz: Melhor é o velho.

'''

xref:042-lucas/042-lucas-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-lucas/042-lucas-006.adoc#v42-6-0[Próximo Capítulo &#62;]