include::./index.adoc[]

[[v42-22-0]]
=== Lucas, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-22-1]]

^<<v42-22-1,1>>^ ESTAVA pois perto a festa dos asmos, chamada a páscoa.

[[v42-22-2]]

^<<v42-22-2,2>>^ E os principais dos sacerdotes, e os escribas, andavam procurando como o matariam; porque temiam o povo.

[[v42-22-3]]

^<<v42-22-3,3>>^ Entrou, porém, Satanás em Judas, que tinha por sobrenome Iscariotes, o qual era do número dos doze;

[[v42-22-4]]

^<<v42-22-4,4>>^ E foi, e falou com os principais dos sacerdotes, e com os capitães, de como lho entregaria;

[[v42-22-5]]

^<<v42-22-5,5>>^ Os quais se alegraram, e convieram em lhe dar dinheiro.

[[v42-22-6]]

^<<v42-22-6,6>>^ E ele concordou; e buscava oportunidade para lho entregar sem alvoroço.

[[v42-22-7]]

^<<v42-22-7,7>>^ Chegou, porém, o dia dos asmos, em que importava sacrificar a páscoa.

[[v42-22-8]]

^<<v42-22-8,8>>^ E mandou a Pedro e a João, dizendo: Ide, preparai-nos a páscoa, para que a  comamos.

[[v42-22-9]]

^<<v42-22-9,9>>^ E eles lhe perguntaram: Onde queres que a  preparemos?

[[v42-22-10]]

^<<v42-22-10,10>>^ E ele lhes disse: Eis que, quando entrardes na cidade, encontrareis um homem, levando um cântaro d’água; segui-o até à casa em que ele entrar.

[[v42-22-11]]

^<<v42-22-11,11>>^ E direis ao pai de família da casa: O mestre te diz: Onde está o aposento em que hei de comer a páscoa com os meus discípulos?

[[v42-22-12]]

^<<v42-22-12,12>>^ Então ele vos mostrará um grande cenáculo mobilado; aí fazei preparativos.

[[v42-22-13]]

^<<v42-22-13,13>>^ E, indo eles, acharam como lhes havia sido dito; e prepararam a páscoa.

[[v42-22-14]]

^<<v42-22-14,14>>^ E, chegada a hora, pôs-se à mesa , e com ele os doze apóstolos.

[[v42-22-15]]

^<<v42-22-15,15>>^ E disse-lhes: Desejei muito comer convosco esta páscoa, antes que padeça;

[[v42-22-16]]

^<<v42-22-16,16>>^ Porque vos digo que não a comerei mais até que ela se cumpra no reino de Deus.

[[v42-22-17]]

^<<v42-22-17,17>>^ E, tomando o cálix, e havendo dado graças, disse: Tomai-o, e reparti- o  entre vós;

[[v42-22-18]]

^<<v42-22-18,18>>^ Porque vos digo que já não beberei do fruto da vide, até que venha o reino de Deus.

[[v42-22-19]]

^<<v42-22-19,19>>^ E, tomando o pão, e havendo dado graças, partiu- o , e deu-lho, dizendo: Isto é o meu corpo, que por vós é dado; fazei isto em memória de mim.

[[v42-22-20]]

^<<v42-22-20,20>>^ Semelhantemente tomou  o cálix, depois da ceia, dizendo: Este cálix é o Novo Testamento no meu sangue, que é derramado por vós.

[[v42-22-21]]

^<<v42-22-21,21>>^ Mas eis que a mão do que me trai está  comigo à mesa.

[[v42-22-22]]

^<<v42-22-22,22>>^ E, na verdade, o Filho do homem vai segundo o que está determinado; mas ai daquele homem por quem é traído!

[[v42-22-23]]

^<<v42-22-23,23>>^ E começaram a perguntar entre si qual deles seria o que havia de fazer isto.

[[v42-22-24]]

^<<v42-22-24,24>>^ E houve também entre eles contenda, sobre qual deles parecia ser o maior.

[[v42-22-25]]

^<<v42-22-25,25>>^ E ele lhes disse: Os reis dos gentios dominam sobre eles, e os que têm autoridade sobre eles são chamados benfeitores.

[[v42-22-26]]

^<<v42-22-26,26>>^ Mas não sereis  vós assim; antes o maior entre vós seja como o menor; e quem governa como quem serve.

[[v42-22-27]]

^<<v42-22-27,27>>^ Pois qual é maior: quem está à mesa , ou quem serve? Porventura, não é  quem está à mesa ? Eu porém, entre vós sou como aquele que serve.

[[v42-22-28]]

^<<v42-22-28,28>>^ E vós sois os que tendes permanecido comigo nas minhas tentações.

[[v42-22-29]]

^<<v42-22-29,29>>^ E eu vos destino o reino, como meu Pai mo destinou;

[[v42-22-30]]

^<<v42-22-30,30>>^ Para que comais e bebais à minha mesa no meu reino, e vos assenteis sobre tronos, julgando as doze tribos d’Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ Disse também o Senhor: Simão, Simão, eis que Satanás vos pediu para vos cirandar como trigo;

[[v42-22-32]]

^<<v42-22-32,32>>^ Mas eu roguei por ti, para que a tua fé não desfaleça; e tu, quando te converteres, confirma teus irmãos.

[[v42-22-33]]

^<<v42-22-33,33>>^ E ele lhe disse: Senhor, estou pronto a ir contigo até à prisão e à morte.

[[v42-22-34]]

^<<v42-22-34,34>>^ Mas ele disse: Digo-te, Pedro, que não cantará hoje o galo antes que três vezes negues que me conheces.

[[v42-22-35]]

^<<v42-22-35,35>>^ E disse-lhes: Quando vos mandei sem bolsa, alforje, ou alparcas, faltou-vos porventura alguma coisa? Eles responderam: Nada.

[[v42-22-36]]

^<<v42-22-36,36>>^ Disse-lhes pois: Mas agora, aquele que tiver bolsa, tome- a , como também o alforje; e, o que não tem espada, venda o seu vestido e compre-a;

[[v42-22-37]]

^<<v42-22-37,37>>^ Porquanto vos digo que importa que em mim se cumpra aquilo que está escrito: E com os malfeitores foi contado. Porque o que está escrito  de mim terá cumprimento.

[[v42-22-38]]

^<<v42-22-38,38>>^ E eles disseram: Senhor, eis aqui duas espadas. E ele lhes disse: Basta.

[[v42-22-39]]

^<<v42-22-39,39>>^ E, saindo, foi, como costumava para o Monte das Oliveiras; e também os seus discípulos o seguiram.

[[v42-22-40]]

^<<v42-22-40,40>>^ E, quando chegou àquele lugar, disse-lhes: Orai, para que não entreis em tentação.

[[v42-22-41]]

^<<v42-22-41,41>>^ E apartou-se deles cerca de um tiro de pedra; e pondo-se de joelhos, orava.

[[v42-22-42]]

^<<v42-22-42,42>>^ Dizendo: Pai, se queres, passa de mim este cálix, todavia não se faça a minha vontade, mas a tua.

[[v42-22-43]]

^<<v42-22-43,43>>^ E apareceu-lhe um anjo do céu, que o confortava.

[[v42-22-44]]

^<<v42-22-44,44>>^ E, posto em agonia, orava mais intensamente. E o seu suor tornou-se em grandes gotas de sangue, que corriam até ao chão.

[[v42-22-45]]

^<<v42-22-45,45>>^ E, levantando-se da oração, veio para os seus discípulos, e achou-os dormindo de tristeza.

[[v42-22-46]]

^<<v42-22-46,46>>^ E disse-lhes: Por que estais dormindo? Levantai-vos, e orai, para que não entreis em tentação.

[[v42-22-47]]

^<<v42-22-47,47>>^ E, estando ele ainda a falar, surgiu uma multidão; e um dos doze, que se chamava Judas, ia adiante dela, e chegou-se a Jesus para o beijar.

[[v42-22-48]]

^<<v42-22-48,48>>^ E Jesus lhe disse: Judas, com um beijo trais o Filho do homem?

[[v42-22-49]]

^<<v42-22-49,49>>^ E, vendo os que estavam com ele o que ia suceder, disseram-lhe: Senhor, feriremos à espada?

[[v42-22-50]]

^<<v42-22-50,50>>^ E um deles feriu o servo do sumo sacerdote, e cortou-lhe a orelha direita.

[[v42-22-51]]

^<<v42-22-51,51>>^ E, respondendo Jesus, disse: Deixai-os; basta. E, tocando-lhe a orelha, o curou.

[[v42-22-52]]

^<<v42-22-52,52>>^ E disse Jesus aos principais dos sacerdotes, e capitães do templo, e anciãos, que tinham ido contra ele: Saístes, como a um salteador, com espadas e varapaus?

[[v42-22-53]]

^<<v42-22-53,53>>^ Tenho estado todos os dias convosco no templo, e não estendestes as mãos contra mim, mas esta é a vossa hora e o poder das trevas.

[[v42-22-54]]

^<<v42-22-54,54>>^ Então, prendendo-o, o levaram, e o meteram em casa do sumo sacerdote. E Pedro seguia-o de longe.

[[v42-22-55]]

^<<v42-22-55,55>>^ E, havendo-se acendido fogo no meio do pátio, estando todos sentados, assentou-se Pedro entre eles.

[[v42-22-56]]

^<<v42-22-56,56>>^ E como certa criada, vendo-o estar assentado ao fogo, pusesse os olhos nele, disse: Este também estava com ele.

[[v42-22-57]]

^<<v42-22-57,57>>^ Porém ele negou-o, dizendo: Mulher, não o conheço.

[[v42-22-58]]

^<<v42-22-58,58>>^ E, um pouco depois, vendo-o outro, disse: Tu és também deles. Mas Pedro disse: Homem, não sou.

[[v42-22-59]]

^<<v42-22-59,59>>^ E, passada quase uma hora, um outro afirmava, dizendo: Também este verdadeiramente estava com ele, pois também é galileu.

[[v42-22-60]]

^<<v42-22-60,60>>^ E Pedro disse: Homem, não sei o que dizes. E logo, estando ele ainda a falar, cantou o galo.

[[v42-22-61]]

^<<v42-22-61,61>>^ E, virando-se o Senhor, olhou para Pedro, e Pedro lembrou-se da palavra do Senhor, como lhe havia dito: Antes que o galo cante hoje, me negarás três vezes.

[[v42-22-62]]

^<<v42-22-62,62>>^ E, saindo Pedro para fora, chorou amargamente.

[[v42-22-63]]

^<<v42-22-63,63>>^ E os homens que detinham Jesus zombavam dele, ferindo-o.

[[v42-22-64]]

^<<v42-22-64,64>>^ E, vendando-lhe os olhos, feriam-no no rosto, e perguntavam-lhe, dizendo: Profetiza, quem é que te feriu?

[[v42-22-65]]

^<<v42-22-65,65>>^ E outras muitas coisas diziam contra ele, blasfemando.

[[v42-22-66]]

^<<v42-22-66,66>>^ E logo que foi dia ajuntaram-se os anciãos do povo, e os principais dos sacerdotes e os escribas, e o conduziram ao seu concílio;

[[v42-22-67]]

^<<v42-22-67,67>>^ E lhe perguntaram: És tu o Cristo? dize-no-lo. Ele replicou: Se vo-lo disser, não o crereis:

[[v42-22-68]]

^<<v42-22-68,68>>^ E também, se vos perguntar, não me respondereis, nem me soltareis.

[[v42-22-69]]

^<<v42-22-69,69>>^ Desde agora o Filho do homem se assentará à direita do poder de Deus.

[[v42-22-70]]

^<<v42-22-70,70>>^ E disseram todos: Logo, és tu o Filho de Deus? E ele lhes disse: Vós dizeis que eu sou.

[[v42-22-71]]

^<<v42-22-71,71>>^ Então disseram: De que mais testemunho necessitamos? pois nós mesmos o ouvimos da sua boca.

'''

xref:042-lucas/042-lucas-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-lucas/042-lucas-023.adoc#v42-23-0[Próximo Capítulo &#62;]