include::./index.adoc[]

[[v42-13-0]]
=== Lucas, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-13-1]]

^<<v42-13-1,1>>^ E NAQUELE mesmo tempo estavam presentes ali alguns que lhe falavam dos galileus cujo sangue Pilatos misturara com os seus sacrifícios.

[[v42-13-2]]

^<<v42-13-2,2>>^ E, respondendo Jesus, disse-lhes: Cuidais vós que esses galileus foram mais pecadores do que todos os galileus, por terem padecido tais coisas?

[[v42-13-3]]

^<<v42-13-3,3>>^ Não, vos digo; antes, se vos não arrependerdes, todos de igual modo perecereis.

[[v42-13-4]]

^<<v42-13-4,4>>^ E aqueles dezoito, sobre os quais caiu a torre de Siloé e os matou, cuidais que foram mais culpados do que todos quantos homens habitam em Jerusalém?

[[v42-13-5]]

^<<v42-13-5,5>>^ Não, vos digo; antes, se vos não arrependerdes, todos de igual modo perecereis.

[[v42-13-6]]

^<<v42-13-6,6>>^ E dizia esta parábola: Um certo homem  tinha uma figueira plantada na sua vinha, e foi procurar nela fruto, não o achando;

[[v42-13-7]]

^<<v42-13-7,7>>^ E disse ao vinhateiro: Eis que há três anos venho procurar fruto nesta figueira, e não o  acho; corta-a; por que ocupa ainda a terra inutilmente?

[[v42-13-8]]

^<<v42-13-8,8>>^ E, respondendo ele, disse-lhe: Senhor, deixa-a este ano, até que eu a escave e a esterque;

[[v42-13-9]]

^<<v42-13-9,9>>^ E, se der fruto, ficará , e, se não, depois a mandarás cortar.

[[v42-13-10]]

^<<v42-13-10,10>>^ E ensinava no sábado, numa das sinagogas.

[[v42-13-11]]

^<<v42-13-11,11>>^ E eis que estava ali uma mulher que tinha um  espírito de enfermidade, havia  já dezoito anos; e andava curvada, e não podia de modo algum endireitar-se.

[[v42-13-12]]

^<<v42-13-12,12>>^ E, vendo-a Jesus, chamou-a a si, e disse-lhe: Mulher, estás livre da tua enfermidade.

[[v42-13-13]]

^<<v42-13-13,13>>^ E pôs as mãos sobre ela, e logo se endireitou, e glorificava a Deus.

[[v42-13-14]]

^<<v42-13-14,14>>^ E, tomando a palavra o príncipe da sinagoga, indignado porque Jesus curava no sábado, disse à multidão: Seis dias há em que é mister trabalhar: nestes pois vinde para serdes curados, e não no dia de sábado.

[[v42-13-15]]

^<<v42-13-15,15>>^ Respondeu-lhe, porém, o Senhor, e disse: Hipócrita, no sábado não desprende da manjedoura cada um de vós o seu boi, ou jumento, e não o leva a beber?

[[v42-13-16]]

^<<v42-13-16,16>>^ E não convinha soltar desta prisão, no dia de sábado, esta filha de Abraão, a qual há  dezoito anos Satanás tinha presa?

[[v42-13-17]]

^<<v42-13-17,17>>^ E, dizendo ele isto, todos os seus adversários ficaram envergonhados, e todo o povo se alegrava por todas as coisas  gloriosas que eram feitas por ele.

[[v42-13-18]]

^<<v42-13-18,18>>^ E dizia: A que é semelhante o reino de Deus, e a que o compararei?

[[v42-13-19]]

^<<v42-13-19,19>>^ É semelhante ao grão de mostarda que um homem, tomando-o, lançou na sua horta; e cresceu, e fez-se grande árvore, e em seus ramos se aninharam as aves do céu.

[[v42-13-20]]

^<<v42-13-20,20>>^ E disse outra vez: A que compararei o reino de Deus?

[[v42-13-21]]

^<<v42-13-21,21>>^ É semelhante ao fermento que uma mulher, tomando-o, escondeu em três medidas de farinha, até que tudo levedou.

[[v42-13-22]]

^<<v42-13-22,22>>^ E percorria as cidades e as aldeias, ensinando, e caminhando para Jerusalém.

[[v42-13-23]]

^<<v42-13-23,23>>^ E disse-lhe um: Senhor, são poucos os que se salvam? E ele lhe respondeu:

[[v42-13-24]]

^<<v42-13-24,24>>^ Porfiai por entrar pela porta estreita; porque eu vos digo que  muitos procurarão entrar, e não poderão.

[[v42-13-25]]

^<<v42-13-25,25>>^ Quando o pai de família se levantar e cerrar a porta, e começardes a estar de fora, e a bater à porta, dizendo: Senhor, Senhor, abre-nos; e, respondendo ele, vos disser: Não sei donde vós sois;

[[v42-13-26]]

^<<v42-13-26,26>>^ Então começareis a dizer: Temos comido e bebido na tua presença, e tu tens ensinado nas nossas ruas.

[[v42-13-27]]

^<<v42-13-27,27>>^ E ele vos responderá: Digo-vos que não sei donde vós sois; apartai-vos de mim, vós todos os que praticais a iniquidade.

[[v42-13-28]]

^<<v42-13-28,28>>^ Ali haverá choro e ranger de dentes, quando virdes Abraão, e Isaque, e Jacó, e todos os profetas, no reino de Deus, e vós lançados fora.

[[v42-13-29]]

^<<v42-13-29,29>>^ E virão do oriente, e do ocidente, e do norte, e do sul, e assentar-se-ão à mesa  no reino de Deus.

[[v42-13-30]]

^<<v42-13-30,30>>^ E eis que derradeiros há que serão os primeiros; e primeiros há que serão os derradeiros.

[[v42-13-31]]

^<<v42-13-31,31>>^ Naquele mesmo dia chegaram uns fariseus, dizendo-lhe: Sai, e retira-te daqui, porque Herodes quer matar-te.

[[v42-13-32]]

^<<v42-13-32,32>>^ E lhes respondeu: Ide, e dizei àquela raposa: Eis que eu expulso demônios, e efetuo curas, hoje e amanhã, e no terceiro dia sou consumado.

[[v42-13-33]]

^<<v42-13-33,33>>^ Importa, porém, caminhar hoje, amanhã, e no dia  seguinte, para que não suceda que morra um profeta fora de Jerusalém.

[[v42-13-34]]

^<<v42-13-34,34>>^ Jerusalém, Jerusalém, que matas os profetas, e apedrejas os que te são enviados! Quantas vezes quis eu ajuntar os teus filhos, como a galinha os seus pintos debaixo das asas, e não quiseste?

[[v42-13-35]]

^<<v42-13-35,35>>^ Eis que a vossa casa se vos deixará deserta. E em verdade vos digo que não me vereis até que venha o tempo  em que digais: Bendito aquele que vem em nome do Senhor.

'''

xref:042-lucas/042-lucas-012.adoc#v42-12-0[&#60; Capítulo Anterior] | <<v42-13-0,Topo>> | xref:042-lucas/042-lucas-014.adoc#v42-14-0[Próximo Capítulo &#62;]