include::./index.adoc[]

[[v42-19-0]]
=== Lucas, 19
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-19-1]]

^<<v42-19-1,1>>^ E, TENDO Jesus  entrado em Jericó, ia passando.

[[v42-19-2]]

^<<v42-19-2,2>>^ E eis que havia  ali um varão chamado Zaqueu; e era este um chefe dos publicanos, e era rico.

[[v42-19-3]]

^<<v42-19-3,3>>^ E procurava ver quem era Jesus, e não podia, por causa da multidão, pois era de pequena estatura.

[[v42-19-4]]

^<<v42-19-4,4>>^ E, correndo adiante, subiu a uma figueira brava para o ver; porque havia de passar por ali.

[[v42-19-5]]

^<<v42-19-5,5>>^ E, quando Jesus chegou àquele lugar, olhando para cima, viu-o e disse-lhe: Zaqueu, desce depressa, porque hoje me convém pousar em tua casa.

[[v42-19-6]]

^<<v42-19-6,6>>^ E, apressando-se, desceu, e recebeu-o gostoso.

[[v42-19-7]]

^<<v42-19-7,7>>^ E, vendo todos isto , murmuravam, dizendo que entrara para ser hóspede de um homem pecador.

[[v42-19-8]]

^<<v42-19-8,8>>^ E, levantando-se Zaqueu, disse ao Senhor: Senhor, eis que eu dou aos pobres metade dos meus bens; e, se nalguma coisa tenho defraudado alguém, o restituo quadruplicado.

[[v42-19-9]]

^<<v42-19-9,9>>^ E disse-lhe Jesus: Hoje veio a salvação a esta casa, pois também este é filho de Abraão.

[[v42-19-10]]

^<<v42-19-10,10>>^ Porque o Filho do homem veio buscar e salvar o que se havia perdido.

[[v42-19-11]]

^<<v42-19-11,11>>^ E, ouvindo eles estas coisas , ele prosseguiu, e contou uma parábola; porquanto estava perto de Jerusalém, e cuidavam que logo se havia de manifestar o reino de Deus.

[[v42-19-12]]

^<<v42-19-12,12>>^ Disse pois: Certo homem nobre partiu para uma terra remota, a fim de tomar para si um reino e voltar depois.

[[v42-19-13]]

^<<v42-19-13,13>>^ E, chamando dez servos seus, deu-lhes dez minas, e disse-lhes: Negociai até que eu venha.

[[v42-19-14]]

^<<v42-19-14,14>>^ Mas os seus concidadãos aborreciam-no, e mandaram após ele embaixadores, dizendo: Não queremos que este reine sobre nós.

[[v42-19-15]]

^<<v42-19-15,15>>^ E aconteceu que, voltando ele, depois de ter tomado o reino, disse que lhe chamassem aqueles servos, a quem tinha dado o dinheiro, para saber o que cada um tinha ganhado, negociando.

[[v42-19-16]]

^<<v42-19-16,16>>^ E veio o primeiro dizendo: Senhor, a tua mina rendeu dez minas.

[[v42-19-17]]

^<<v42-19-17,17>>^ E ele lhe disse: Bem está , servo bom, porque no mínimo foste fiel, sobre dez cidades terás a autoridade.

[[v42-19-18]]

^<<v42-19-18,18>>^ E veio o segundo, dizendo: Senhor, a tua mina rendeu cinco minas.

[[v42-19-19]]

^<<v42-19-19,19>>^ E a este disse também: Sê tu também sobre cinco cidades.

[[v42-19-20]]

^<<v42-19-20,20>>^ E veio outro, dizendo: Senhor, aqui está  a tua mina, que guardei num lenço;

[[v42-19-21]]

^<<v42-19-21,21>>^ Porque tive medo de ti, que és homem rigoroso, que tomas o que não puseste, e segas o que não semeaste.

[[v42-19-22]]

^<<v42-19-22,22>>^ Porém ele lhe disse: Mau servo, pela tua boca te julgarei; sabias que eu sou homem rigoroso, que tomo o que não pus, e sego o que não semeei;

[[v42-19-23]]

^<<v42-19-23,23>>^ Por que não meteste pois o meu dinheiro no banco, para que eu, vindo, o exigisse com os juros?

[[v42-19-24]]

^<<v42-19-24,24>>^ E disse aos que estavam com ele: Tirai-lhe a mina, e dai- a  ao que tem dez minas.

[[v42-19-25]]

^<<v42-19-25,25>>^ (E disseram-lhe eles: Senhor, ele tem dez minas).

[[v42-19-26]]

^<<v42-19-26,26>>^ Pois eu vos digo que a qualquer que tiver ser-lhe-á dado, mas ao que não tiver até o que tem lhe será tirado.

[[v42-19-27]]

^<<v42-19-27,27>>^ E, quanto àqueles meus inimigos que não quiseram que eu reinasse sobre eles, trazei-os aqui e matai- os  diante de mim.

[[v42-19-28]]

^<<v42-19-28,28>>^ E, dito isto, ia caminhando adiante, subindo para Jerusalém.

[[v42-19-29]]

^<<v42-19-29,29>>^ E aconteceu que, chegando perto de Betfagé, e de Betânia, ao monte chamado das Oliveiras, mandou dois dos seus discípulos,

[[v42-19-30]]

^<<v42-19-30,30>>^ Dizendo: Ide à aldeia que está defronte, e aí, ao entrar, achareis preso um jumentinho em que nenhum homem ainda se assentou; soltai-o e trazei- o ;

[[v42-19-31]]

^<<v42-19-31,31>>^ E, se alguém vos perguntar: Por que o  soltais? assim lhe direis: Porque o Senhor o há de mister.

[[v42-19-32]]

^<<v42-19-32,32>>^ E, indo os que haviam sido mandados, acharam como lhes dissera.

[[v42-19-33]]

^<<v42-19-33,33>>^ E, quando soltaram o jumentinho, seus donos lhes disseram: Por que soltais o jumentinho?

[[v42-19-34]]

^<<v42-19-34,34>>^ E eles responderam: O Senhor o há de mister.

[[v42-19-35]]

^<<v42-19-35,35>>^ E trouxeram-no a Jesus: e, lançando sobre o jumentinho os seus vestidos, puseram Jesus em cima.

[[v42-19-36]]

^<<v42-19-36,36>>^ E, indo ele, estendiam no caminho os seus vestidos.

[[v42-19-37]]

^<<v42-19-37,37>>^ E, quando já chegava perto da descida do monte das Oliveiras, toda a multidão dos discípulos, regozijando-se, começou a dar louvores a Deus em alta voz, por todas as maravilhas que tinham visto.

[[v42-19-38]]

^<<v42-19-38,38>>^ Dizendo: Bendito o Rei que vem em nome do Senhor; paz no céu, e glória nas alturas.

[[v42-19-39]]

^<<v42-19-39,39>>^ E disseram-lhe dentre a multidão alguns dos fariseus: Mestre, repreende os teus discípulos.

[[v42-19-40]]

^<<v42-19-40,40>>^ E, respondendo ele, disse-lhes: Digo-vos que, se estes se calarem, as próprias pedras clamarão.

[[v42-19-41]]

^<<v42-19-41,41>>^ E, quando ia chegando, vendo a cidade, chorou sobre ela,

[[v42-19-42]]

^<<v42-19-42,42>>^ Dizendo: Ah! se tu conhecesses também, ao menos neste teu dia, o que  à tua paz pertence ! mas agora isto  está encoberto aos teus olhos.

[[v42-19-43]]

^<<v42-19-43,43>>^ Porque dias virão sobre ti, em que os teus inimigos te cercarão de trincheiras, e te sitiarão, e te estreitarão de todas as bandas;

[[v42-19-44]]

^<<v42-19-44,44>>^ E te derribarão, a ti e a teus filhos que  dentro de ti estiverem ; e não deixarão em ti pedra sobre pedra, pois que não conheceste o tempo da tua visitação.

[[v42-19-45]]

^<<v42-19-45,45>>^ E, entrando no templo, começou a expulsar todos os que nele vendiam e compravam,

[[v42-19-46]]

^<<v42-19-46,46>>^ Dizendo-lhes: Está escrito: A minha casa é casa de oração; mas vós fizestes dela covil de salteadores.

[[v42-19-47]]

^<<v42-19-47,47>>^ E todos os dias ensinava no templo; mas os principais dos sacerdotes, e os escribas, e os principais do povo procuravam matá-lo.

[[v42-19-48]]

^<<v42-19-48,48>>^ E não achavam meio de o fazer, porque todo o povo pendia para ele, escutando-o.

'''

xref:042-lucas/042-lucas-018.adoc#v42-18-0[&#60; Capítulo Anterior] | <<v42-19-0,Topo>> | xref:042-lucas/042-lucas-020.adoc#v42-20-0[Próximo Capítulo &#62;]