include::./index.adoc[]

[[v42-3-0]]
=== Lucas, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-3-1]]

^<<v42-3-1,1>>^ E NO ano quinze do império de Tibério César, sendo Pôncio Pilatos presidente da Judeia, e Herodes tetrarca da Galileia, e seu irmão Filipe tetrarca da Itureia, e da província de Traconites, e Lisâneas tetrarca da Abilínia.

[[v42-3-2]]

^<<v42-3-2,2>>^ Sendo Anás e Caifás sumos sacerdotes, veio no deserto a palavra de Deus a João, filho de Zacarias.

[[v42-3-3]]

^<<v42-3-3,3>>^ E  percorreu toda a terra ao redor do Jordão, pregando o batismo de arrependimento, para o perdão dos pecados;

[[v42-3-4]]

^<<v42-3-4,4>>^ Segundo o que está escrito no livro das palavras do profeta Isaías, que diz: Voz do que clama no deserto: Preparai o caminho do Senhor; endireitai as suas veredas.

[[v42-3-5]]

^<<v42-3-5,5>>^ Todo o vale se encherá, e se abaixará todo o monte e outeiro; e o que é tortuoso se endireitará, e os caminhos escabrosos se aplanarão;

[[v42-3-6]]

^<<v42-3-6,6>>^ E toda a carne verá a salvação de Deus.

[[v42-3-7]]

^<<v42-3-7,7>>^ Dizia pois João à multidão que saía para ser batizada por ele: Raça de víboras, quem vos ensinou a fugir da ira que está para vir?

[[v42-3-8]]

^<<v42-3-8,8>>^ Produzi pois frutos dignos de arrependimento, e não comeceis a dizer em vós mesmos: Temos Abraão por pai; porque eu vos digo que até destas pedras pode Deus suscitar filhos a Abraão.

[[v42-3-9]]

^<<v42-3-9,9>>^ E também já está posto o machado à raiz das árvores; toda a árvore, pois, que não dá bom fruto, corta-se e lança-se no fogo.

[[v42-3-10]]

^<<v42-3-10,10>>^ E a multidão o interrogava, dizendo: Que faremos pois?

[[v42-3-11]]

^<<v42-3-11,11>>^ E, respondendo ele, disse-lhes: Quem tiver duas túnicas, reparta com o que não tem, e quem tiver alimentos faça da mesma maneira.

[[v42-3-12]]

^<<v42-3-12,12>>^ E chegaram também uns publicanos, para serem batizados, e disseram-lhe: Mestre, que devemos fazer?

[[v42-3-13]]

^<<v42-3-13,13>>^ E ele lhes disse: Não peçais mais do que o que vos está ordenado.

[[v42-3-14]]

^<<v42-3-14,14>>^ E uns soldados o interrogaram também, dizendo: E nós que faremos? E ele lhes disse: A ninguém trateis mal nem defraudeis, e contentai-vos com o vosso soldo.

[[v42-3-15]]

^<<v42-3-15,15>>^ E, estando o povo em expectação, e pensando todos de João, em seus corações, se porventura seria o Cristo,

[[v42-3-16]]

^<<v42-3-16,16>>^ Respondeu João a todos, dizendo: Eu, na verdade, batizo-vos com água, mas eis que vem aquele que é mais poderoso do que eu, a quem eu não sou digno de desatar a correia das alparcas; esse vos batizará com o Espírito Santo e com fogo.

[[v42-3-17]]

^<<v42-3-17,17>>^ Ele tem a pá na sua mão; e limpará a sua eira, e ajuntará o trigo no seu celeiro, mas queimará a palha com fogo que nunca se apaga.

[[v42-3-18]]

^<<v42-3-18,18>>^ E assim admoestando-os, muitas outras coisas  também anunciava ao povo.

[[v42-3-19]]

^<<v42-3-19,19>>^ Sendo, porém, o tetrarca Herodes repreendido por ele por causa de Herodias, mulher de seu irmão Filipe, e por todas as maldades que Herodes tinha feito.

[[v42-3-20]]

^<<v42-3-20,20>>^ Acrescentou a todas as outras ainda esta, a de encerrar João num cárcere.

[[v42-3-21]]

^<<v42-3-21,21>>^ E aconteceu que, como todo o povo se batizava, sendo batizado também  Jesus, orando ele, o céu se abriu;

[[v42-3-22]]

^<<v42-3-22,22>>^ E o Espírito Santo desceu sobre ele em forma corpórea, como uma  pomba; e ouviu-se uma voz do céu, que dizia: Tu és meu filho amado, em ti me tenho comprazido.

[[v42-3-23]]

^<<v42-3-23,23>>^ E o mesmo Jesus começava a ser de quase trinta anos, sendo (como se cuidava) filho de José, e José  de Heli,

[[v42-3-24]]

^<<v42-3-24,24>>^ e Heli  de Matá, e Matá  de Levi, e Levi  de Melqui, e Melqui  de Joana e Joana  de José,

[[v42-3-25]]

^<<v42-3-25,25>>^ e José  de Matatias, e Matatias  de Amós, e Amós  de Naum, e Naum  de Essi, e Essi  de Nagai,

[[v42-3-26]]

^<<v42-3-26,26>>^ e Nagai  de Máate, e Máate  de Matatias, e Matatias  de Semei, e Semei  de José, e José  de Judá,

[[v42-3-27]]

^<<v42-3-27,27>>^ e Judá  de Joana e Joana  de Resá, e Resá  de Zorobabel, e Zorobabel  de Salatiel, e Salatiel  de Neri,

[[v42-3-28]]

^<<v42-3-28,28>>^ e Neri  de Melqui, e Melqui  de Adi, e Adi  de Cozam, e Cozam  de Elmodam, e Elmodam  de Er,

[[v42-3-29]]

^<<v42-3-29,29>>^ e Er  de José, e José  de Eliézer, e Eliézer  de Jorim, e Jorim  de Matá, e Matá  de Levi,

[[v42-3-30]]

^<<v42-3-30,30>>^ e Levi  de Simeão, e Simeão  de Judá, e Judá  de José, e José  de Jonã, e Jonã  de Eliaquim,

[[v42-3-31]]

^<<v42-3-31,31>>^ e Eliaquim  de Meleia, e Meleia  de Mainã, e Mainã  de Matatá, e Matatá  de Natã, e Natã  de Davi,

[[v42-3-32]]

^<<v42-3-32,32>>^ e Davi  de Jessé, e Jessé  de Obede, e Obede  de Booz, e Booz  de Salmom, e Salmom  de Naassom,

[[v42-3-33]]

^<<v42-3-33,33>>^ e Naassom  de Aminadabe, e Aminadabe  de Arão, e Arão  de Esrom, e Esrom  de Fares, e Fares  de Judá,

[[v42-3-34]]

^<<v42-3-34,34>>^ e Judá  de Jacó, e Jacó  de Isaque, e Isaque  de Abraão, e Abraão  de Tare, e Tare  de Nacor,

[[v42-3-35]]

^<<v42-3-35,35>>^ e Nacor  de Saruque, e Saruque  de Ragaú, e Ragaú  de Fáleque, e Fáleque  de Heber, e Heber  de Sala,

[[v42-3-36]]

^<<v42-3-36,36>>^ e Sala  de Cainã, e Cainã  de Arfaxade, e Arfaxade  de Sem, e Sem  de Noé, e Noé  de Lameque,

[[v42-3-37]]

^<<v42-3-37,37>>^ e Lameque  de Matusala, e Matusala  de Enoque, e Enoque  de Járede, e Járede  de Maleleel e Maleleel  de Cainã,

[[v42-3-38]]

^<<v42-3-38,38>>^ e Cainã  de Henos, e Henos  de Sete, e Sete  de Adão, e Adão  de Deus.

'''

xref:042-lucas/042-lucas-002.adoc#v42-2-0[&#60; Capítulo Anterior] | <<v42-3-0,Topo>> | xref:042-lucas/042-lucas-004.adoc#v42-4-0[Próximo Capítulo &#62;]