include::./index.adoc[]

[[v42-1-0]]
=== Lucas, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-1-1]]

^<<v42-1-1,1>>^ TENDO pois muitos empreendido pôr em ordem a narração dos fatos que entre nós se cumpriram,

[[v42-1-2]]

^<<v42-1-2,2>>^ Segundo nos transmitiram os mesmos que os presenciaram desde o princípio, e foram ministros da palavra,

[[v42-1-3]]

^<<v42-1-3,3>>^ Pareceu-me também a mim conveniente descrevê-los a ti, ó excelente Teófilo, por sua ordem, havendo-me já informado minuciosamente de tudo desde o princípio;

[[v42-1-4]]

^<<v42-1-4,4>>^ Para que conheças a certeza das coisas de que já  estás informado.

[[v42-1-5]]

^<<v42-1-5,5>>^ Existiu, no tempo de Herodes, rei da Judeia, um sacerdote chamado Zacarias, da ordem de Abias, e cuja mulher era das filhas d’Aarão; e o seu nome era  Isabel.

[[v42-1-6]]

^<<v42-1-6,6>>^ E eram ambos justos perante Deus, andando sem repreensão em todos os mandamentos e preceitos do Senhor.

[[v42-1-7]]

^<<v42-1-7,7>>^ E não tinham filhos, porque Isabel era estéril, e ambos eram avançados em idade.

[[v42-1-8]]

^<<v42-1-8,8>>^ E aconteceu que, exercendo ele o sacerdócio diante de Deus, na ordem da sua turma,

[[v42-1-9]]

^<<v42-1-9,9>>^ Segundo o costume sacerdotal, coube-lhe em sorte entrar no templo do Senhor para oferecer o incenso.

[[v42-1-10]]

^<<v42-1-10,10>>^ E toda a multidão do povo estava fora, orando, à hora do incenso;

[[v42-1-11]]

^<<v42-1-11,11>>^ E um anjo do Senhor lhe apareceu, posto em pé, à direita do altar do incenso.

[[v42-1-12]]

^<<v42-1-12,12>>^ E Zacarias, vendo- o , turbou-se, e caiu temor sobre ele.

[[v42-1-13]]

^<<v42-1-13,13>>^ Mas o anjo lhe disse: Zacarias, não temas, porque a tua oração foi ouvida, e Isabel, tua mulher, dará à luz um filho, e lhe porás o nome de João;

[[v42-1-14]]

^<<v42-1-14,14>>^ E terás prazer e alegria, e muitos se alegrarão no seu nascimento,

[[v42-1-15]]

^<<v42-1-15,15>>^ Porque será grande diante do Senhor, e não beberá vinho, nem bebida forte, e será cheio do Espírito Santo, já desde o ventre de sua mãe;

[[v42-1-16]]

^<<v42-1-16,16>>^ E converterá muitos dos filhos de Israel ao Senhor seu Deus,

[[v42-1-17]]

^<<v42-1-17,17>>^ E irá adiante dele no espírito e virtude de Elias, para converter os corações dos pais aos filhos, e os rebeldes à prudência dos justos; com o fim de preparar ao Senhor um povo bem  disposto.

[[v42-1-18]]

^<<v42-1-18,18>>^ Disse então Zacarias ao anjo: Como saberei isto? pois eu já  sou velho, e minha mulher avançada em idade.

[[v42-1-19]]

^<<v42-1-19,19>>^ E, respondendo o anjo, disse-lhe: Eu sou Gabriel, que assisto diante de Deus, e fui enviado a falar-te e dar-te estas alegres novas;

[[v42-1-20]]

^<<v42-1-20,20>>^ E eis que ficarás mudo, e não poderás falar até ao dia em que estas coisas  aconteçam; porquanto não creste nas minhas palavras, que a seu tempo se hão de cumprir.

[[v42-1-21]]

^<<v42-1-21,21>>^ E o povo estava esperando a Zacarias, e maravilhava-se de que tanto se demorasse no templo.

[[v42-1-22]]

^<<v42-1-22,22>>^ E, saindo ele, não lhes podia falar; e entenderam que tinha visto alguma  visão no templo. E falava por acenos, e ficou mudo.

[[v42-1-23]]

^<<v42-1-23,23>>^ E sucedeu que, terminados os dias de seu ministério, voltou para sua casa.

[[v42-1-24]]

^<<v42-1-24,24>>^ E depois daqueles dias Isabel, sua mulher, concebeu, e por cinco meses se ocultou, dizendo:

[[v42-1-25]]

^<<v42-1-25,25>>^ Assim me fez o Senhor, nos dias em que atentou em mim , para destruir o meu opróbrio entre os homens.

[[v42-1-26]]

^<<v42-1-26,26>>^ E, no sexto mês, foi o anjo Gabriel enviado por Deus a uma cidade da Galileia, chamada Nazaré,

[[v42-1-27]]

^<<v42-1-27,27>>^ A uma virgem desposada com um varão, cujo nome era José, da casa de Davi; e o nome da virgem era  Maria.

[[v42-1-28]]

^<<v42-1-28,28>>^ E, entrando o anjo aonde ela estava, disse: Salve, agraciada; o Senhor é  contigo: bendita tu entre as mulheres.

[[v42-1-29]]

^<<v42-1-29,29>>^ E, vendo- o  ela, turbou-se muito com aquelas palavras, e considerava que saudação seria esta.

[[v42-1-30]]

^<<v42-1-30,30>>^ Disse-lhe então o anjo: Maria, não temas, porque achaste graça diante de Deus;

[[v42-1-31]]

^<<v42-1-31,31>>^ E eis que em teu ventre conceberás e darás à luz um filho, e pôr-lhe-ás o nome de Jesus.

[[v42-1-32]]

^<<v42-1-32,32>>^ Este será grande, e será chamado filho do Altíssimo; e o Senhor Deus lhe dará o trono de Davi, seu pai;

[[v42-1-33]]

^<<v42-1-33,33>>^ E reinará eternamente na casa de Jacó, e o seu reino não terá fim.

[[v42-1-34]]

^<<v42-1-34,34>>^ E disse Maria ao anjo: Como se fará isto, visto que não conheço varão?

[[v42-1-35]]

^<<v42-1-35,35>>^ E, respondendo o anjo, disse-lhe: Descerá sobre ti o Espírito Santo, e a virtude do Altíssimo te cobrirá com a sua sombra; pelo que também o Santo, que de ti há de nascer, será chamado Filho de Deus.

[[v42-1-36]]

^<<v42-1-36,36>>^ E eis que também Isabel, tua prima, concebeu um filho em sua velhice; e é este o sexto mês para aquela que era chamada estéril;

[[v42-1-37]]

^<<v42-1-37,37>>^ Porque para Deus nada é impossível.

[[v42-1-38]]

^<<v42-1-38,38>>^ Disse então Maria: Eis aqui a serva do Senhor; cumpra-se em mim segundo a tua palavra. E o anjo ausentou-se dela.

[[v42-1-39]]

^<<v42-1-39,39>>^ E naqueles dias, levantando-se Maria, foi apressada às montanhas, a uma cidade de Judá,

[[v42-1-40]]

^<<v42-1-40,40>>^ E entrou em casa de Zacarias, e saudou a Isabel.

[[v42-1-41]]

^<<v42-1-41,41>>^ E aconteceu que, ao ouvir Isabel a saudação de Maria, a criancinha saltou no seu ventre; e Isabel foi cheia do Espírito Santo;

[[v42-1-42]]

^<<v42-1-42,42>>^ E exclamou com grande voz, e disse: Bendita tu entre as mulheres, e bendito o fruto do teu ventre.

[[v42-1-43]]

^<<v42-1-43,43>>^ E donde me provém  isto a mim, que venha visitar-me a mãe do meu Senhor?

[[v42-1-44]]

^<<v42-1-44,44>>^ Pois eis que, ao chegar aos meus ouvidos a voz da tua saudação, a criancinha saltou de alegria no meu ventre.

[[v42-1-45]]

^<<v42-1-45,45>>^ Bem-aventurada a que creu, pois hão de cumprir-se as coisas  que da parte do Senhor lhe foram ditas.

[[v42-1-46]]

^<<v42-1-46,46>>^ Disse então Maria: A minha alma engrandece ao Senhor,

[[v42-1-47]]

^<<v42-1-47,47>>^ E o meu espírito se alegra em Deus meu Salvador;

[[v42-1-48]]

^<<v42-1-48,48>>^ Porque atentou na baixeza de sua serva; pois eis que desde agora todas as gerações me chamarão bem-aventurada:

[[v42-1-49]]

^<<v42-1-49,49>>^ Porque me fez grandes coisas o Poderoso; e santo é  o seu nome.

[[v42-1-50]]

^<<v42-1-50,50>>^ E a sua misericórdia é  de geração em geração sobre os que o temem.

[[v42-1-51]]

^<<v42-1-51,51>>^ Com o seu braço obrou valorosamente; dissipou os soberbos no pensamento de seus corações.

[[v42-1-52]]

^<<v42-1-52,52>>^ Depôs dos tronos os poderosos, e elevou os humildes.

[[v42-1-53]]

^<<v42-1-53,53>>^ Encheu de bens os famintos, e despediu vazios os ricos.

[[v42-1-54]]

^<<v42-1-54,54>>^ Auxiliou a Israel seu servo, recordando-se da sua  misericórdia,

[[v42-1-55]]

^<<v42-1-55,55>>^ (Como falou a nossos pais) para com Abraão e sua posteridade, para sempre.

[[v42-1-56]]

^<<v42-1-56,56>>^ E Maria ficou com ela quase três meses, e depois voltou para sua casa.

[[v42-1-57]]

^<<v42-1-57,57>>^ E completou-se para Isabel o tempo de dar à luz e teve um filho.

[[v42-1-58]]

^<<v42-1-58,58>>^ E os seus vizinhos e parentes ouviram que tinha Deus usado para com ela de grande misericórdia, e alegraram-se com ela.

[[v42-1-59]]

^<<v42-1-59,59>>^ E aconteceu que, ao oitavo dia, vieram circuncidar o menino, e lhe chamavam Zacarias, o nome de seu pai.

[[v42-1-60]]

^<<v42-1-60,60>>^ E, respondendo sua mãe, disse: Não, porém será chamado João.

[[v42-1-61]]

^<<v42-1-61,61>>^ E disseram-lhe: Ninguém há na tua parentela que se chame por este nome.

[[v42-1-62]]

^<<v42-1-62,62>>^ E perguntaram por acenos ao pai como queria que lhe chamassem.

[[v42-1-63]]

^<<v42-1-63,63>>^ E, pedindo ele uma tabuinha de escrever, escreveu, dizendo: O seu nome é João. E todos se maravilharam.

[[v42-1-64]]

^<<v42-1-64,64>>^ E logo a boca se lhe abriu, e a língua se lhe soltou ; e falava, louvando a Deus.

[[v42-1-65]]

^<<v42-1-65,65>>^ E veio temor sobre todos os seus vizinhos, e em todas as montanhas da Judeia foram divulgadas todas estas coisas.

[[v42-1-66]]

^<<v42-1-66,66>>^ E todos os que as  ouviam as  conservavam em seus corações, dizendo: Quem será pois este menino? E a mão do Senhor estava com ele.

[[v42-1-67]]

^<<v42-1-67,67>>^ E Zacarias, seu pai, foi cheio do Espírito Santo, e profetizou, dizendo:

[[v42-1-68]]

^<<v42-1-68,68>>^ Bendito o Senhor Deus d’Israel, porque visitou e remiu o seu povo.

[[v42-1-69]]

^<<v42-1-69,69>>^ E nos levantou uma salvação poderosa na casa de Davi seu servo.

[[v42-1-70]]

^<<v42-1-70,70>>^ Como falou pela boca dos seus santos profetas, desde o princípio do mundo;

[[v42-1-71]]

^<<v42-1-71,71>>^ Para nos livrar dos nossos inimigos e da mão de todos os que nos aborrecem;

[[v42-1-72]]

^<<v42-1-72,72>>^ Para manifestar misericórdia a nossos pais, e lembrar-se do seu santo concerto,

[[v42-1-73]]

^<<v42-1-73,73>>^ E do juramento que jurou a Abraão nosso pai,

[[v42-1-74]]

^<<v42-1-74,74>>^ De conceder-nos que, libertados da mão de nossos inimigos, o serviríamos sem temor,

[[v42-1-75]]

^<<v42-1-75,75>>^ Em santidade e justiça perante ele, todos os dias da nossa vida.

[[v42-1-76]]

^<<v42-1-76,76>>^ E tu, ó menino, serás chamado profeta do Altíssimo, porque hás de ir ante a face do Senhor, a preparar os seus caminhos;

[[v42-1-77]]

^<<v42-1-77,77>>^ Para dar ao seu povo conhecimento da salvação, na remissão dos seus pecados;

[[v42-1-78]]

^<<v42-1-78,78>>^ Pelas entranhas da misericórdia do nosso Deus, com que o Oriente do alto nos visitou;

[[v42-1-79]]

^<<v42-1-79,79>>^ Para alumiar aos que estão assentados em trevas e sombra de morte; a fim de dirigir os nossos pés pelo caminho da paz.

[[v42-1-80]]

^<<v42-1-80,80>>^ E o menino crescia, e se robustecia em espírito. E esteve nos desertos até ao dia em que havia de mostrar-se a Israel.

'''

xref:041-marcos/041-marcos-016.adoc#v41-16-0[&#60; Capítulo Anterior] | <<v42-1-0,Topo>> | xref:042-lucas/042-lucas-002.adoc#v42-2-0[Próximo Capítulo &#62;]