include::./index.adoc[]

[[v42-18-0]]
=== Lucas, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-18-1]]

^<<v42-18-1,1>>^ E CONTOU-LHES também uma parábola sobre o dever de orar sempre, e nunca desfalecer,

[[v42-18-2]]

^<<v42-18-2,2>>^ Dizendo: Havia numa cidade um  certo juiz, que nem a Deus temia nem respeitava o homem.

[[v42-18-3]]

^<<v42-18-3,3>>^ Havia também naquela mesma cidade uma  certa viúva, e ia ter com ele, dizendo: Faze-me justiça contra o meu adversário.

[[v42-18-4]]

^<<v42-18-4,4>>^ E por algum tempo não quis; mas depois disse consigo: Ainda que não temo a Deus, nem respeito os homens,

[[v42-18-5]]

^<<v42-18-5,5>>^ Todavia, como esta viúva me molesta, hei de fazer-lhe justiça, para que enfim não volte, e me importune muito.

[[v42-18-6]]

^<<v42-18-6,6>>^ E disse o Senhor: Ouvi o que diz o injusto juiz.

[[v42-18-7]]

^<<v42-18-7,7>>^ E Deus não fará justiça aos seus escolhidos, que clamam a ele de dia e de noite, ainda que tardio para com eles?

[[v42-18-8]]

^<<v42-18-8,8>>^ Digo-vos que depressa lhes fará justiça. Quando porém vier o Filho do homem, porventura achará fé na terra?

[[v42-18-9]]

^<<v42-18-9,9>>^ E disse também esta parábola a uns que confiavam em si mesmos, crendo que eram justos, e desprezavam os outros:

[[v42-18-10]]

^<<v42-18-10,10>>^ Dois homens subiram ao templo, a orar; um fariseu, e o outro publicano.

[[v42-18-11]]

^<<v42-18-11,11>>^ O fariseu, estando em pé, orava consigo desta maneira: Ó Deus, graças te dou, porque não sou como os demais homens, roubadores, injustos e adúlteros; nem ainda como este publicano.

[[v42-18-12]]

^<<v42-18-12,12>>^ Jejuo duas vezes na semana, e  dou os dízimos de tudo quanto possuo.

[[v42-18-13]]

^<<v42-18-13,13>>^ O publicano, porém, estando em pé, de longe, nem ainda queria levantar os olhos ao céu, mas batia no peito, dizendo: Ó Deus, tem misericórdia de mim, pecador!

[[v42-18-14]]

^<<v42-18-14,14>>^ Digo-vos que este desceu justificado para sua casa, e não aquele; porque qualquer que a si mesmo se exalta será humilhado, e qualquer que a si mesmo se humilha será exaltado.

[[v42-18-15]]

^<<v42-18-15,15>>^ E traziam-lhe também meninos, para que ele lhes tocasse; e os discípulos, vendo isto , repreendiam-nos.

[[v42-18-16]]

^<<v42-18-16,16>>^ Mas Jesus, chamando-os para si, disse: Deixai vir a mim os meninos, e não os impeçais, porque dos tais é o reino de Deus.

[[v42-18-17]]

^<<v42-18-17,17>>^ Em verdade vos digo que, qualquer que não receber o reino de Deus como menino, não entrará nele.

[[v42-18-18]]

^<<v42-18-18,18>>^ E perguntou-lhe um  certo príncipe, dizendo: Bom Mestre, que hei de fazer para herdar a vida eterna?

[[v42-18-19]]

^<<v42-18-19,19>>^ Jesus lhe disse: Por que me chamas bom? Ninguém há bom, senão um, que é  Deus.

[[v42-18-20]]

^<<v42-18-20,20>>^ Sabes os mandamentos: Não adulterarás, não matarás, não furtarás, não dirás falso testemunho, honra a teu pai e a tua mãe.

[[v42-18-21]]

^<<v42-18-21,21>>^ E disse ele: Todas essas coisas tenho observado desde a minha mocidade.

[[v42-18-22]]

^<<v42-18-22,22>>^ E quando Jesus ouviu isto, disse-lhe: Ainda te falta uma coisa: vende tudo quanto tens, reparte- o  pelos pobres, e terás um  tesouro no céu; vem, e segue-me.

[[v42-18-23]]

^<<v42-18-23,23>>^ Mas, ouvindo ele isto, ficou muito triste, porque era muito rico.

[[v42-18-24]]

^<<v42-18-24,24>>^ E, vendo Jesus que ele ficara muito triste, disse: Quão dificilmente entrarão no reino de Deus os que têm riquezas!

[[v42-18-25]]

^<<v42-18-25,25>>^ Porque é mais fácil entrar um camelo pelo fundo duma agulha do que entrar um rico no reino de Deus.

[[v42-18-26]]

^<<v42-18-26,26>>^ E os que ouviram isto  disseram: Logo quem pode salvar-se?

[[v42-18-27]]

^<<v42-18-27,27>>^ Mas ele respondeu: As coisas  que são impossíveis aos homens são possíveis a Deus.

[[v42-18-28]]

^<<v42-18-28,28>>^ E disse Pedro: Eis que nós deixamos tudo e te seguimos.

[[v42-18-29]]

^<<v42-18-29,29>>^ E ele lhes disse: Na verdade vos digo que ninguém há, que tenha deixado casa, ou pais, ou irmãos, ou mulher, ou filhos, pelo reino de Deus,

[[v42-18-30]]

^<<v42-18-30,30>>^ E não haja de receber muito mais neste mundo e na idade vindoura a vida eterna.

[[v42-18-31]]

^<<v42-18-31,31>>^ E, tomando consigo os doze, disse-lhes: Eis que subimos a Jerusalém, e se cumprirá no Filho do homem tudo o que pelos profetas foi escrito;

[[v42-18-32]]

^<<v42-18-32,32>>^ Pois há de ser entregue às gentes, e escarnecido, injuriado e cuspido;

[[v42-18-33]]

^<<v42-18-33,33>>^ E, havendo- o  açoitado, o matarão; e ao terceiro dia ressuscitará.

[[v42-18-34]]

^<<v42-18-34,34>>^ E eles nada disto entendiam, e esta palavra lhes era encoberta, não percebendo o  que se lhes  dizia.

[[v42-18-35]]

^<<v42-18-35,35>>^ E aconteceu que, chegando ele perto de Jericó, estava um cego assentado junto do caminho, mendigando.

[[v42-18-36]]

^<<v42-18-36,36>>^ E, ouvindo passar a multidão, perguntou que era aquilo.

[[v42-18-37]]

^<<v42-18-37,37>>^ E disseram-lhe que Jesus Nazareno passava.

[[v42-18-38]]

^<<v42-18-38,38>>^ Então clamou, dizendo: Jesus, Filho de Davi, tem misericórdia de mim.

[[v42-18-39]]

^<<v42-18-39,39>>^ E os que iam passando repreendiam-no para que se calasse; mas ele clamava ainda mais: Filho de Davi, tem misericórdia de mim.

[[v42-18-40]]

^<<v42-18-40,40>>^ Então Jesus, parando, mandou que lho trouxessem; e, chegando ele, perguntou-lhe,

[[v42-18-41]]

^<<v42-18-41,41>>^ Dizendo: Que queres que te faça? E ele disse: Senhor, que eu veja.

[[v42-18-42]]

^<<v42-18-42,42>>^ E Jesus lhe disse: Vê: a tua fé te salvou.

[[v42-18-43]]

^<<v42-18-43,43>>^ E logo viu, e seguia-o, glorificando a Deus. E todo o povo, vendo isto , dava louvores a Deus.

'''

xref:042-lucas/042-lucas-017.adoc#v42-17-0[&#60; Capítulo Anterior] | <<v42-18-0,Topo>> | xref:042-lucas/042-lucas-019.adoc#v42-19-0[Próximo Capítulo &#62;]