include::./index.adoc[]

[[v42-10-0]]
=== Lucas, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-10-1]]

^<<v42-10-1,1>>^ E DEPOIS disto designou o Senhor ainda outros setenta, e mandou-os adiante da sua face, de dois em dois, a todas as cidades e lugares aonde ele havia de ir.

[[v42-10-2]]

^<<v42-10-2,2>>^ E dizia-lhes: Grande é , em verdade, a seara, mas os obreiros são  poucos; rogai pois ao Senhor da seara que envie obreiros para a sua seara.

[[v42-10-3]]

^<<v42-10-3,3>>^ Ide; eis que vos mando como cordeiros ao meio de lobos.

[[v42-10-4]]

^<<v42-10-4,4>>^ E não leveis bolsa, nem alforje, nem alparcas; e a ninguém saudeis pelo caminho.

[[v42-10-5]]

^<<v42-10-5,5>>^ E, em qualquer casa onde entrardes, dizei primeiro: Paz seja  nesta casa.

[[v42-10-6]]

^<<v42-10-6,6>>^ E, se ali houver algum filho de paz, repousará sobre ele a vossa paz; e, se não, voltará para vós.

[[v42-10-7]]

^<<v42-10-7,7>>^ E ficai na mesma casa, comendo e bebendo do que eles tiverem, pois digno é o obreiro de seu salário. Não andeis de casa em casa.

[[v42-10-8]]

^<<v42-10-8,8>>^ E, em qualquer cidade em que entrardes, e vos receberem, comei do que vos puserem diante.

[[v42-10-9]]

^<<v42-10-9,9>>^ E curai os enfermos que nela houver, e dizei-lhes: É chegado a vós o reino de Deus.

[[v42-10-10]]

^<<v42-10-10,10>>^ Mas em qualquer cidade, em que entrardes e vos não receberem, saindo por suas ruas, dizei:

[[v42-10-11]]

^<<v42-10-11,11>>^ Até o pó, que da vossa cidade se nos pegou, sacudimos sobre vós. Sabei, contudo, isto, que já  o reino de Deus é chegado a vós.

[[v42-10-12]]

^<<v42-10-12,12>>^ E digo-vos que mais tolerância haverá naquele dia para Sodoma do que para aquela cidade.

[[v42-10-13]]

^<<v42-10-13,13>>^ Ai de ti, Corazim, ai de ti Betsaida! que, se em Tiro e em Sidom se fizessem as maravilhas que em vós foram feitas, já há muito, assentadas em saco e cinza, se teriam arrependido.

[[v42-10-14]]

^<<v42-10-14,14>>^ Portanto, para Tiro e Sidom haverá menos rigor no juízo, do que para vós.

[[v42-10-15]]

^<<v42-10-15,15>>^ E tu, Capernaum, serás levantada até ao céu? até ao inferno serás abatida.

[[v42-10-16]]

^<<v42-10-16,16>>^ Quem vos ouve a vós, a mim me ouve; e, quem vos rejeita a vós, a mim me rejeita; e, quem a mim me rejeita, rejeita aquele que me enviou.

[[v42-10-17]]

^<<v42-10-17,17>>^ E voltaram os setenta com alegria, dizendo: Senhor, pelo teu nome, até os demônios se nos sujeitam.

[[v42-10-18]]

^<<v42-10-18,18>>^ E disse-lhes: Eu via Satanás, como raio, cair do céu.

[[v42-10-19]]

^<<v42-10-19,19>>^ Eis que vos dou poder para pisar serpentes e escorpiões, e toda a força do inimigo, e nada vos fará dano algum.

[[v42-10-20]]

^<<v42-10-20,20>>^ Mas não vos alegreis por que se vos sujeitem os espíritos; alegrai-vos antes por estarem os vossos nomes escritos nos céus.

[[v42-10-21]]

^<<v42-10-21,21>>^ Naquela mesma hora se alegrou Jesus no Espírito Santo, e disse: Graças te dou, ó Pai, Senhor do céu e da terra, que escondeste estas coisas  aos sábios e inteligentes, e as revelaste às criancinhas; assim é, ó Pai, porque assim te aprouve.

[[v42-10-22]]

^<<v42-10-22,22>>^ Tudo por meu Pai me foi entregue; e ninguém conhece quem é o Filho senão o Pai, nem quem é o Pai senão o Filho, e aquele a quem o Filho o quiser revelar.

[[v42-10-23]]

^<<v42-10-23,23>>^ E, voltando-se para os discípulos, disse- lhes  em particular: Bem-aventurados os olhos que veem o que vós vedes;

[[v42-10-24]]

^<<v42-10-24,24>>^ Pois vos digo que muitos profetas e reis desejaram ver o que vós vedes, e não o viram; e ouvir o que ouvis, e não o ouviram.

[[v42-10-25]]

^<<v42-10-25,25>>^ E eis que se levantou um certo doutor da lei, tentando-o, e dizendo: Mestre, que farei para herdar a vida eterna?

[[v42-10-26]]

^<<v42-10-26,26>>^ E ele lhe disse: Que está escrito na lei? Como lês?

[[v42-10-27]]

^<<v42-10-27,27>>^ E, respondendo ele, disse: Amarás ao Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todas as tuas forças, e de todo o teu entendimento, e ao teu próximo como a ti mesmo.

[[v42-10-28]]

^<<v42-10-28,28>>^ E disse-lhe: Respondeste bem; faze isso, e viverás.

[[v42-10-29]]

^<<v42-10-29,29>>^ Ele, porém, querendo justificar-se a si mesmo, disse a Jesus: E quem é o meu próximo?

[[v42-10-30]]

^<<v42-10-30,30>>^ E, respondendo Jesus, disse: Descia um homem de Jerusalém para Jericó, e caiu nas mãos dos salteadores, os quais o despojaram, e, espancando-o, se retiraram, deixando- o  meio morto.

[[v42-10-31]]

^<<v42-10-31,31>>^ E ocasionalmente descia pelo mesmo caminho certo sacerdote; e, vendo-o, passou de largo.

[[v42-10-32]]

^<<v42-10-32,32>>^ E d’igual modo também um levita, chegando àquele lugar, e vendo- o , passou de largo.

[[v42-10-33]]

^<<v42-10-33,33>>^ Mas um samaritano, que ia de viagem, chegou ao pé dele, e, vendo-o, moveu-se de íntima compaixão;

[[v42-10-34]]

^<<v42-10-34,34>>^ E, aproximando-se, atou-lhe as feridas, deitando-lhes azeite e vinho; e, pondo-o sobre a sua cavalgadura, levou-o para uma estalagem, e cuidou dele;

[[v42-10-35]]

^<<v42-10-35,35>>^ E, partindo ao outro dia, tirou dois dinheiros, e deu- os  ao hospedeiro, e disse-lhe: Cuida dele; e tudo o que de mais gastares eu to pagarei quando voltar.

[[v42-10-36]]

^<<v42-10-36,36>>^ Qual, pois, destes três te parece que foi o próximo daquele que caiu nas mãos dos salteadores?

[[v42-10-37]]

^<<v42-10-37,37>>^ E ele disse: O que usou de misericórdia para com ele. Disse, pois, Jesus: Vai, e faze da mesma maneira.

[[v42-10-38]]

^<<v42-10-38,38>>^ E aconteceu que, indo eles de caminho, entrou numa aldeia; e certa mulher, por nome Marta, o recebeu em sua casa;

[[v42-10-39]]

^<<v42-10-39,39>>^ E tinha esta uma irmã chamada Maria, a qual, assentando-se também aos pés de Jesus, ouvia a sua palavra.

[[v42-10-40]]

^<<v42-10-40,40>>^ Marta, porém, andava distraída em muitos serviços, e, aproximando-se, disse: Senhor, não se te dá de que minha irmã me deixe servir só? Dize-lhe pois que me ajude.

[[v42-10-41]]

^<<v42-10-41,41>>^ E, respondendo Jesus, disse-lhe: Marta, Marta, estás ansiosa e afadigada com muitas coisas.

[[v42-10-42]]

^<<v42-10-42,42>>^ Mas uma só é necessária; e Maria escolheu a boa parte, a qual não lhe será tirada.

'''

xref:042-lucas/042-lucas-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-lucas/042-lucas-011.adoc#v42-11-0[Próximo Capítulo &#62;]