include::./index.adoc[]

[[v42-6-0]]
=== Lucas, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-6-1]]

^<<v42-6-1,1>>^ E ACONTECEU que, no sábado segundo-primeiro, passou pelas searas, e os seus discípulos iam arrancando espigas, e, esfregando-as com as mãos, as  comiam.

[[v42-6-2]]

^<<v42-6-2,2>>^ E alguns dos fariseus lhes disseram: Por que fazeis o que não é lícito fazer nos sábados?

[[v42-6-3]]

^<<v42-6-3,3>>^ E Jesus, respondendo-lhes, disse: Nunca lestes o que fez Davi quando teve fome, ele e os que com ele estavam?

[[v42-6-4]]

^<<v42-6-4,4>>^ Como entrou na casa de Deus, e tomou os pães da proposição, e os comeu, e deu também aos que estavam com ele, os quais não é lícito comer senão só aos sacerdotes?

[[v42-6-5]]

^<<v42-6-5,5>>^ E dizia-lhes: O Filho do homem é Senhor até do sábado.

[[v42-6-6]]

^<<v42-6-6,6>>^ E aconteceu também noutro sábado que entrou na sinagoga, e estava ensinando; e havia ali um homem que tinha a mão direita mirrada.

[[v42-6-7]]

^<<v42-6-7,7>>^ E os escribas e fariseus atentavam nele, se o  curaria no sábado, para acharem de que o acusar.

[[v42-6-8]]

^<<v42-6-8,8>>^ Mas ele bem conhecia os seus pensamentos; e disse ao homem que tinha a mão mirrada: Levanta-te, e fica em pé no meio. E, levantando-se ele ficou em pé.

[[v42-6-9]]

^<<v42-6-9,9>>^ Então Jesus lhes disse: Uma coisa  vos hei de perguntar: É lícito nos sábados fazer bem, ou fazer mal? salvar a vida, ou matar?

[[v42-6-10]]

^<<v42-6-10,10>>^ E, olhando para todos em redor, disse ao homem: Estende a tua mão. E ele assim o fez, e a mão lhe foi restituída sã como a outra.

[[v42-6-11]]

^<<v42-6-11,11>>^ E ficaram cheios de furor, e uns com os outros conferenciavam sobre o que fariam a Jesus.

[[v42-6-12]]

^<<v42-6-12,12>>^ E aconteceu que naqueles dias subiu ao monte a orar, e passou a noite em oração a Deus.

[[v42-6-13]]

^<<v42-6-13,13>>^ E, quando já  era dia, chamou a si os seus discípulos, e escolheu doze deles, a quem também deu o nome de apóstolos:

[[v42-6-14]]

^<<v42-6-14,14>>^ Simão, ao qual também chamou Pedro, e André, seu irmão; Tiago e João; Filipe e Bartolomeu;

[[v42-6-15]]

^<<v42-6-15,15>>^ E Mateus e Tomé; Tiago, filho  d’Alfeu, e Simão, chamado o zelador;

[[v42-6-16]]

^<<v42-6-16,16>>^ E Judas, filho de Tiago; e Judas Iscariotes, que foi o traidor.

[[v42-6-17]]

^<<v42-6-17,17>>^ E, descendo com eles, parou num lugar plano, e também um grande número de seus discípulos, e grande multidão de povo de toda a Judeia, e de Jerusalém, e da costa marítima de Tiro e de Sidom;

[[v42-6-18]]

^<<v42-6-18,18>>^ Os quais tinham vindo para o ouvir, e serem curados das suas enfermidades, como também os atormentados dos espíritos imundos: e eram curados.

[[v42-6-19]]

^<<v42-6-19,19>>^ E toda a multidão procurava tocar-lhe; porque saía dele virtude, e curava a todos.

[[v42-6-20]]

^<<v42-6-20,20>>^ E, levantando ele os olhos para os seus discípulos, dizia: Bem-aventurados vós, os pobres, porque vosso é o reino de Deus.

[[v42-6-21]]

^<<v42-6-21,21>>^ Bem-aventurados vós, que agora tendes fome, porque sereis fartos. Bem-aventurados vós, que agora chorais, porque haveis de rir.

[[v42-6-22]]

^<<v42-6-22,22>>^ Bem-aventurados sereis quando os homens vos aborrecerem e quando vos separarem, e vos injuriarem, e rejeitarem o vosso nome como mau, por causa do Filho do homem.

[[v42-6-23]]

^<<v42-6-23,23>>^ Folgai nesse dia, exultai; porque, eis que é grande o vosso galardão no céu, pois assim faziam os seus pais aos profetas.

[[v42-6-24]]

^<<v42-6-24,24>>^ Mas ai de vós ricos! porque já  tendes a vossa consolação.

[[v42-6-25]]

^<<v42-6-25,25>>^ Ai de vós, os que estais fartos, porque tereis fome. Ai de vós, os que agora rides, porque vos lamentareis e chorareis.

[[v42-6-26]]

^<<v42-6-26,26>>^ Ai de vós quando todos os homens de vós disserem bem, porque assim faziam seus pais aos falsos profetas.

[[v42-6-27]]

^<<v42-6-27,27>>^ Mas a vós, que ouvis, digo: Amai a vossos inimigos, fazei bem aos que vos aborrecem;

[[v42-6-28]]

^<<v42-6-28,28>>^ Bendizei os que vos maldizem, e orai pelos que vos caluniam.

[[v42-6-29]]

^<<v42-6-29,29>>^ Ao que te ferir numa face, oferece-lhe também a outra; e, ao que te houver tirado a capa, nem a túnica recuses;

[[v42-6-30]]

^<<v42-6-30,30>>^ E dá a qualquer que te pedir; e, ao que tomar o que é  teu, não lho tornes a pedir.

[[v42-6-31]]

^<<v42-6-31,31>>^ E, como vós quereis que os homens vos façam, da mesma maneira lhes fazei vós também.

[[v42-6-32]]

^<<v42-6-32,32>>^ E, se amardes aos que vos amam, que recompensa tereis? Também os pecadores amam aos que os amam.

[[v42-6-33]]

^<<v42-6-33,33>>^ E, se fizerdes bem aos que vos fazem bem, que recompensa tereis? Também os pecadores fazem o mesmo.

[[v42-6-34]]

^<<v42-6-34,34>>^ E, se emprestardes àqueles  de quem esperais tornar a receber, que recompensa tereis? Também os pecadores emprestam aos pecadores, para tornarem a receber outro tanto.

[[v42-6-35]]

^<<v42-6-35,35>>^ Amai pois a vossos inimigos, e fazei bem, e emprestai, sem nada esperardes, e será grande o vosso galardão, e sereis filhos do Altíssimo; porque Ele é benigno até  para com os ingratos e maus.

[[v42-6-36]]

^<<v42-6-36,36>>^ Sede pois misericordiosos, como também vosso Pai é misericordioso.

[[v42-6-37]]

^<<v42-6-37,37>>^ Não julgueis, e não sereis julgados; não condeneis, e não sereis condenados; soltai, e soltar-vos-ão.

[[v42-6-38]]

^<<v42-6-38,38>>^ Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordando, vos deitarão no vosso regaço; porque com a mesma medida com que medirdes também vos medirão de novo.

[[v42-6-39]]

^<<v42-6-39,39>>^ E dizia-lhes uma parábola: Pode porventura o cego guiar o cego? não cairão ambos na cova?

[[v42-6-40]]

^<<v42-6-40,40>>^ O discípulo não é superior a seu mestre, mas todo o que for perfeito será como o seu mestre.

[[v42-6-41]]

^<<v42-6-41,41>>^ E porque atentas tu no argueiro que está no olho do teu irmão, e não reparas na trave que está no teu próprio olho?

[[v42-6-42]]

^<<v42-6-42,42>>^ Ou como podes dizer a teu irmão: Irmão, deixa-me tirar o argueiro que está no teu olho, não atentando tu mesmo na trave que está no teu olho? Hipócrita, tira primeiro a trave do teu olho, e então verás bem para tirar o argueiro que está no olho de teu irmão.

[[v42-6-43]]

^<<v42-6-43,43>>^ Porque não há boa árvore que dê mau fruto, nem má árvore que dê bom fruto.

[[v42-6-44]]

^<<v42-6-44,44>>^ Porque cada árvore se conhece pelo seu próprio fruto; pois não se colhem figos dos espinheiros, nem se vindimam uvas dos abrolhos.

[[v42-6-45]]

^<<v42-6-45,45>>^ O homem bom, do bom tesouro do seu coração tira o bem, e o homem mau, do mau tesouro do seu coração tira o mal, porque da abundância do seu coração fala a boca.

[[v42-6-46]]

^<<v42-6-46,46>>^ E por que me chamais, Senhor, Senhor, e não fazeis o que eu digo?

[[v42-6-47]]

^<<v42-6-47,47>>^ Qualquer que vem a mim e ouve as minhas palavras, e as observa, eu vos mostrarei a quem é semelhante:

[[v42-6-48]]

^<<v42-6-48,48>>^ É semelhante ao homem que edificou uma casa, e cavou, e abriu bem fundo, e pôs os alicerces sobre rocha; e, vindo a enchente, bateu com ímpeto a corrente naquela casa, e não a pôde abalar, porque estava fundada sobre rocha.

[[v42-6-49]]

^<<v42-6-49,49>>^ Mas o que ouve e não pratica é semelhante ao homem que edificou uma casa sobre terra, sem alicerces, na qual bateu com ímpeto a corrente, e logo caiu; e foi grande a ruína daquela casa.

'''

xref:042-lucas/042-lucas-005.adoc#v42-5-0[&#60; Capítulo Anterior] | <<v42-6-0,Topo>> | xref:042-lucas/042-lucas-007.adoc#v42-7-0[Próximo Capítulo &#62;]