include::./index.adoc[]

[[v42-15-0]]
=== Lucas, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-15-1]]

^<<v42-15-1,1>>^ E CHEGAVAM-SE a ele todos os publicanos e pecadores para o ouvir.

[[v42-15-2]]

^<<v42-15-2,2>>^ E os fariseus e os escribas murmuravam, dizendo: Este recebe pecadores, e come com eles.

[[v42-15-3]]

^<<v42-15-3,3>>^ E ele lhes propôs esta parábola, dizendo:

[[v42-15-4]]

^<<v42-15-4,4>>^ Que homem dentre vós, tendo cem ovelhas, e perdendo uma delas, não deixa no deserto as noventa e nove e não vai após a perdida até que venha a achá-la?

[[v42-15-5]]

^<<v42-15-5,5>>^ E, achando-a, a põe sobre seus ombros, gostoso;

[[v42-15-6]]

^<<v42-15-6,6>>^ E, chegando a casa, convoca os amigos e vizinhos, dizendo-lhes: Alegrai-vos comigo, porque já  achei a minha ovelha perdida.

[[v42-15-7]]

^<<v42-15-7,7>>^ Digo-vos que assim haverá alegria no céu por um pecador que se arrepende, mais do que por noventa e nove justos que não necessitam de arrependimento.

[[v42-15-8]]

^<<v42-15-8,8>>^ Ou qual a mulher que, tendo dez dracmas, se perder uma dracma, não acende a candeia, e varre a casa, e busca com diligência até a  achar?

[[v42-15-9]]

^<<v42-15-9,9>>^ E, achando-a, convoca as amigas e vizinhas, dizendo: Alegrai-vos comigo, porque já achei a dracma perdida.

[[v42-15-10]]

^<<v42-15-10,10>>^ Assim vos digo que há alegria diante dos anjos de Deus por um pecador que se arrepende.

[[v42-15-11]]

^<<v42-15-11,11>>^ E disse: Um  certo homem tinha dois filhos;

[[v42-15-12]]

^<<v42-15-12,12>>^ E o mais moço deles disse ao pai: Pai, dá-me a parte da fazenda que me  pertence. E ele repartiu por eles a fazenda.

[[v42-15-13]]

^<<v42-15-13,13>>^ E, poucos dias depois, o filho mais novo, ajuntando tudo, partiu para uma terra longínqua e ali desperdiçou a sua fazenda, vivendo dissolutamente.

[[v42-15-14]]

^<<v42-15-14,14>>^ E, havendo ele gastado tudo, houve naquela terra uma grande fome, e começou a padecer necessidades.

[[v42-15-15]]

^<<v42-15-15,15>>^ E foi, e chegou-se a um dos cidadãos daquela terra, o qual o mandou para os seus campos a apascentar porcos.

[[v42-15-16]]

^<<v42-15-16,16>>^ E desejava encher o seu estômago com as bolotas que os porcos comiam, e ninguém lhe dava nada.

[[v42-15-17]]

^<<v42-15-17,17>>^ E, tornando em si, disse: Quantos jornaleiros de meu pai têm abundância de pão, e eu aqui pereço de fome!

[[v42-15-18]]

^<<v42-15-18,18>>^ Levantar-me-ei, e irei ter com meu pai, e dir-lhe-ei: Pai, pequei contra o céu e perante ti;

[[v42-15-19]]

^<<v42-15-19,19>>^ Já não sou digno de ser chamado teu filho; faze-me como um dos teus jornaleiros.

[[v42-15-20]]

^<<v42-15-20,20>>^ E, levantando-se, foi para seu pai; e, quando ainda estava longe, viu-o seu pai, e se moveu de íntima compaixão, e, correndo, lançou-se-lhe ao pescoço e o beijou.

[[v42-15-21]]

^<<v42-15-21,21>>^ E o filho lhe disse: Pai, pequei contra o céu e perante ti, e já não sou digno de ser chamado teu filho.

[[v42-15-22]]

^<<v42-15-22,22>>^ Mas o pai disse aos seus servos: Trazei depressa o melhor vestido, e vesti-lho, e ponde-lhe um anel na mão, e alparcas nos pés;

[[v42-15-23]]

^<<v42-15-23,23>>^ E trazei o bezerro cevado, e matai- o ; e comamos, e alegremo-nos;

[[v42-15-24]]

^<<v42-15-24,24>>^ Porque este meu filho estava morto, e reviveu, tinha-se perdido, e foi achado. E começaram a alegrar-se.

[[v42-15-25]]

^<<v42-15-25,25>>^ E o seu filho mais velho estava no campo; e quando veio, e chegou perto de casa, ouviu a música e as danças.

[[v42-15-26]]

^<<v42-15-26,26>>^ E, chamando um dos servos, perguntou-lhe que era aquilo.

[[v42-15-27]]

^<<v42-15-27,27>>^ E ele lhe disse: Veio teu irmão; e teu pai matou o bezerro cevado, porque o recebeu são e salvo.

[[v42-15-28]]

^<<v42-15-28,28>>^ Mas ele se indignou, e não queria entrar. E, saindo o pai, instava com ele.

[[v42-15-29]]

^<<v42-15-29,29>>^ Mas, respondendo ele, disse ao pai: Eis que te sirvo há  tantos anos, sem nunca transgredir o teu mandamento, e nunca me deste um cabrito para alegrar-me com os meus amigos;

[[v42-15-30]]

^<<v42-15-30,30>>^ Vindo, porém, este teu filho, que desperdiçou a tua fazenda com as meretrizes, mataste-lhe o bezerro cevado.

[[v42-15-31]]

^<<v42-15-31,31>>^ E ele lhe disse: Filho, tu sempre estás comigo, e todas as minhas coisas  são tuas;

[[v42-15-32]]

^<<v42-15-32,32>>^ Mas era justo alegrarmo- nos  e folgarmos, porque este teu irmão estava morto, e reviveu; e tinha-se perdido, e achou-se.

'''

xref:042-lucas/042-lucas-014.adoc#v42-14-0[&#60; Capítulo Anterior] | <<v42-15-0,Topo>> | xref:042-lucas/042-lucas-016.adoc#v42-16-0[Próximo Capítulo &#62;]