include::./index.adoc[]

[[v42-21-0]]
=== Lucas, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v42-21-1]]

^<<v42-21-1,1>>^ E, OLHANDO ele, viu os ricos lançarem as suas ofertas na arca do tesouro;

[[v42-21-2]]

^<<v42-21-2,2>>^ E viu também uma pobre viúva lançar ali duas pequenas moedas ;

[[v42-21-3]]

^<<v42-21-3,3>>^ E disse: Em verdade vos digo que lançou mais do que todos, esta pobre viúva;

[[v42-21-4]]

^<<v42-21-4,4>>^ Porque todos aqueles deitaram para as ofertas de Deus, do que lhes sobeja; mas esta, da sua pobreza, deitou todo o sustento que tinha.

[[v42-21-5]]

^<<v42-21-5,5>>^ E, dizendo alguns a respeito do templo, que estava ornado de formosas pedras e dádivas, disse:

[[v42-21-6]]

^<<v42-21-6,6>>^ Quanto a estas coisas  que vedes, dias virão em que se não deixará pedra sobre pedra, que não seja derribada.

[[v42-21-7]]

^<<v42-21-7,7>>^ E perguntaram-lhe, dizendo: Mestre, quando serão pois estas coisas ? E que sinal haverá  quando isto estiver para acontecer?

[[v42-21-8]]

^<<v42-21-8,8>>^ Disse então ele: Vede não vos enganem, porque virão muitos em meu nome, dizendo: Sou eu, e o tempo está próximo; não vades portanto após eles.

[[v42-21-9]]

^<<v42-21-9,9>>^ E, quando ouvirdes de guerras e sedições, não vos assusteis. Porque é necessário que isto aconteça primeiro, mas o fim não será  logo.

[[v42-21-10]]

^<<v42-21-10,10>>^ Então lhes disse: Levantar-se-á nação contra nação, e reino contra reino;

[[v42-21-11]]

^<<v42-21-11,11>>^ E haverá em vários lugares grandes terremotos, e fomes e pestilências; haverá também coisas espantosas, e grandes sinais do céu.

[[v42-21-12]]

^<<v42-21-12,12>>^ Mas antes de todas estas coisas lançarão mão de vós, e vos  perseguirão, entregando- vos  às sinagogas e às prisões, e conduzindo-vos à presença de reis e presidentes, por amor do meu nome.

[[v42-21-13]]

^<<v42-21-13,13>>^ E vos acontecerá isto  para testemunho.

[[v42-21-14]]

^<<v42-21-14,14>>^ Proponde pois em vossos corações não premeditar como haveis de responder;

[[v42-21-15]]

^<<v42-21-15,15>>^ Porque eu vos darei boca e sabedoria a que não poderão resistir nem contradizer todos quantos se vos opuserem.

[[v42-21-16]]

^<<v42-21-16,16>>^ E até pelos pais, e irmãos, e parentes, e amigos sereis entregues; e matarão alguns  de vós.

[[v42-21-17]]

^<<v42-21-17,17>>^ E de todos sereis odiados por causa do meu nome.

[[v42-21-18]]

^<<v42-21-18,18>>^ Mas não perecerá um único cabelo da vossa cabeça.

[[v42-21-19]]

^<<v42-21-19,19>>^ Na vossa paciência possuí as vossas almas.

[[v42-21-20]]

^<<v42-21-20,20>>^ Mas, quando virdes Jerusalém cercada de exércitos, sabei então que é chegada a sua desolação.

[[v42-21-21]]

^<<v42-21-21,21>>^ Então, os que estiverem na Judeia, fujam para os montes; os que estiverem no meio da cidade , saiam; e, os que nos campos, não entrem nela.

[[v42-21-22]]

^<<v42-21-22,22>>^ Porque dias de vingança são estes, para que se cumpram todas as coisas  que estão escritas.

[[v42-21-23]]

^<<v42-21-23,23>>^ Mas ai das grávidas, e das que criarem naqueles dias! porque haverá grande aperto na terra, e ira sobre este povo.

[[v42-21-24]]

^<<v42-21-24,24>>^ E cairão ao fio da espada, e para todas as nações serão levados cativos; e Jerusalém será pisada pelos gentios, até que os tempos dos gentios se completem.

[[v42-21-25]]

^<<v42-21-25,25>>^ E haverá sinais no sol e na  lua e nas  estrelas; e na terra angústia das nações, em perplexidade pelo bramido do mar e das ondas;

[[v42-21-26]]

^<<v42-21-26,26>>^ Homens desmaiando de terror, na expectação das coisas que sobrevirão ao mundo. Porquanto as virtudes do céu serão abaladas.

[[v42-21-27]]

^<<v42-21-27,27>>^ E então verão vir o Filho do homem numa nuvem, com poder e grande glória.

[[v42-21-28]]

^<<v42-21-28,28>>^ Ora, quando estas coisas  começarem a acontecer, olhai para cima e levantai as vossas cabeças, porque a vossa redenção está próxima.

[[v42-21-29]]

^<<v42-21-29,29>>^ E disse-lhes uma parábola: Olhai para a figueira, e para todas as árvores;

[[v42-21-30]]

^<<v42-21-30,30>>^ Quando já têm rebentado, vós sabeis por vós mesmos, vendo-as, que perto está já o verão.

[[v42-21-31]]

^<<v42-21-31,31>>^ Assim também vós, quando virdes acontecer estas coisas , sabei que o reino de Deus está perto.

[[v42-21-32]]

^<<v42-21-32,32>>^ Em verdade vos digo que não passará esta geração até que tudo aconteça.

[[v42-21-33]]

^<<v42-21-33,33>>^ Passará o céu e a terra, mas as minhas palavras não hão de passar.

[[v42-21-34]]

^<<v42-21-34,34>>^ E olhai por vós, não aconteça que os vossos corações se carreguem de glutonaria, de embriaguez, e dos cuidados da vida, e venha sobre vós de improviso aquele dia.

[[v42-21-35]]

^<<v42-21-35,35>>^ Porque virá como um laço sobre todos os que habitam na face de toda a terra.

[[v42-21-36]]

^<<v42-21-36,36>>^ Vigiai pois em todo o tempo, orando, para que sejais havidos por dignos de evitar todas estas coisas  que hão de acontecer e de estar em pé diante do Filho do homem.

[[v42-21-37]]

^<<v42-21-37,37>>^ E de dia ensinava no templo, e à noite, saindo, ficava no monte chamado das Oliveiras.

[[v42-21-38]]

^<<v42-21-38,38>>^ E todo o povo ia ter com ele ao templo, de manhã cedo, para o ouvir.

'''

xref:042-lucas/042-lucas-020.adoc#v42-20-0[&#60; Capítulo Anterior] | <<v42-21-0,Topo>> | xref:042-lucas/042-lucas-022.adoc#v42-22-0[Próximo Capítulo &#62;]