include::./index.adoc[]

[[v20-24-0]]
=== Provérbios, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v20-24-1]]

^<<v20-24-1,1>>^ NÃO tenhas inveja dos homens malignos, nem desejes estar com eles,

[[v20-24-2]]

^<<v20-24-2,2>>^ Porque o seu coração medita a rapina, e os seus lábios falam maliciosamente.

[[v20-24-3]]

^<<v20-24-3,3>>^ Com a sabedoria se edifica a casa, e com a inteligência ela se firma:

[[v20-24-4]]

^<<v20-24-4,4>>^ E pelo conhecimento se encherão as câmaras de todas as substâncias preciosas e deleitáveis.

[[v20-24-5]]

^<<v20-24-5,5>>^ Um varão sábio é  forte, e o varão de conhecimento consolida a força.

[[v20-24-6]]

^<<v20-24-6,6>>^ Porque com conselhos prudentes tu farás a guerra; e há vitória na multidão dos conselheiros.

[[v20-24-7]]

^<<v20-24-7,7>>^ É demasiadamente alta para o tolo toda  a sabedoria; na porta não abrirá a sua boca.

[[v20-24-8]]

^<<v20-24-8,8>>^ Aquele que cuida em fazer mal, mestre de maus intentos o chamarão.

[[v20-24-9]]

^<<v20-24-9,9>>^ O pensamento do tolo é  pecado, e é abominável aos homens o escarnecedor.

[[v20-24-10]]

^<<v20-24-10,10>>^ Se  te mostrares frouxo no dia da angústia, a tua força será  pequena.

[[v20-24-11]]

^<<v20-24-11,11>>^ Livra os que estão destinados à morte, e os que são levados para a matança, se os  puderes retirar.

[[v20-24-12]]

^<<v20-24-12,12>>^ Se disseres: Eis que o não sabemos: porventura  aquele que pondera os corações não o  considerará? e aquele que atenta para a tua alma não o saberá? não pagará ele ao homem conforme a sua obra?

[[v20-24-13]]

^<<v20-24-13,13>>^ Come mel, meu filho, porque é  bom, e o favo de mel, que é  doce ao teu paladar.

[[v20-24-14]]

^<<v20-24-14,14>>^ Tal será  o conhecimento da sabedoria para a tua alma: se a achares, haverá para ti  galardão, e não será cortada a tua expectação.

[[v20-24-15]]

^<<v20-24-15,15>>^ Não espies a habitação do justo, ó ímpio, nem assoles a sua câmara.

[[v20-24-16]]

^<<v20-24-16,16>>^ Porque sete vezes cairá o justo, e se levantará; mas os ímpios tropeçarão no mal.

[[v20-24-17]]

^<<v20-24-17,17>>^ Quando cair o teu inimigo, não te alegres, nem quando tropeçar se regozije o teu coração.

[[v20-24-18]]

^<<v20-24-18,18>>^ Para que o Senhor isso não veja, e seja mau aos seus olhos, e desvie dele a sua ira.

[[v20-24-19]]

^<<v20-24-19,19>>^ Não te aflijas por causa dos malfeitores, nem tenhas inveja dos ímpios.

[[v20-24-20]]

^<<v20-24-20,20>>^ Porque o maligno não terá galardão algum, e  a lâmpada dos ímpios se apagará.

[[v20-24-21]]

^<<v20-24-21,21>>^ Teme ao Senhor, filho meu, e ao rei, e não te entremetas com os que buscam mudanças.

[[v20-24-22]]

^<<v20-24-22,22>>^ Porque de repente se levantará a sua perdição, e a ruína deles quem a conhecerá?

[[v20-24-23]]

^<<v20-24-23,23>>^ Também estes são provérbios  dos sábios: Ter respeito a pessoas no juízo não é bom.

[[v20-24-24]]

^<<v20-24-24,24>>^ O que disser ao ímpio: Justo és : os povos o amaldiçoarão, as nações o detestarão.

[[v20-24-25]]

^<<v20-24-25,25>>^ Mas para os que o repreenderem haverá delícias, e sobre eles virá a bênção do bem.

[[v20-24-26]]

^<<v20-24-26,26>>^ Beija com os lábios o que responde com palavras retas.

[[v20-24-27]]

^<<v20-24-27,27>>^ Prepara fora a tua obra, e apronta-a no campo, e então edifica a tua casa.

[[v20-24-28]]

^<<v20-24-28,28>>^ Não sejas testemunha sem causa contra o teu próximo; por que enganarias com os teus lábios?

[[v20-24-29]]

^<<v20-24-29,29>>^ Não digas: Como ele me fez a mim, assim lhe farei a ele; pagarei a cada um segundo a sua obra.

[[v20-24-30]]

^<<v20-24-30,30>>^ Passei pelo campo do preguiçoso, e junto à vinha do homem falto de entendimento;

[[v20-24-31]]

^<<v20-24-31,31>>^ E eis que toda estava cheia de cardos, e  a sua superfície coberta de urtigas, e a sua parede de pedra estava derribada.

[[v20-24-32]]

^<<v20-24-32,32>>^ O que tendo eu visto, o considerei; e , vendo- o , recebi instrução.

[[v20-24-33]]

^<<v20-24-33,33>>^ Um pouco de sono, adormecendo um pouco, encruzando as mãos outro pouco, para estar deitado;

[[v20-24-34]]

^<<v20-24-34,34>>^ Assim sobreviverá a tua pobreza como um  ladrão, e a tua necessidade como um  homem armado.

'''

xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[&#60; Capítulo Anterior] | <<v20-24-0,Topo>> | xref:020-proverbios/020-proverbios-025.adoc#v20-25-0[Próximo Capítulo &#62;]