include::./index.adoc[]

[[v20-23-0]]
=== Provérbios, 23
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v20-23-1]]

^<<v20-23-1,1>>^ QUANDO te assentares a comer com um  governador, atenta bem para o que se  te pôs  diante.

[[v20-23-2]]

^<<v20-23-2,2>>^ E põe uma faca à tua garganta, se és  homem glutão.

[[v20-23-3]]

^<<v20-23-3,3>>^ Não cobices os seus manjares gostosos, porque são  pão de mentiras.

[[v20-23-4]]

^<<v20-23-4,4>>^ Não te canses para enriqueceres; dá de mão à tua própria sabedoria.

[[v20-23-5]]

^<<v20-23-5,5>>^ Porventura  fitarás os teus olhos naquilo que não é nada? porque certamente isso se fará asas e voará ao céu como a águia.

[[v20-23-6]]

^<<v20-23-6,6>>^ Não comas o pão daquele que tem  os olhos malignos, nem cobices os seus manjares gostosos.

[[v20-23-7]]

^<<v20-23-7,7>>^ Porque, como imaginou na sua alma, assim é; ele te dirá: Come e bebe: mas o seu coração não estará  contigo.

[[v20-23-8]]

^<<v20-23-8,8>>^ Vomitarias o bocado que  comeste, e perderias as tuas suaves palavras.

[[v20-23-9]]

^<<v20-23-9,9>>^ Não fales aos ouvidos do tolo, porque desprezará a sabedoria das tuas palavras.

[[v20-23-10]]

^<<v20-23-10,10>>^ Não removas os limites antigos, nem entres nas herdades dos órfãos

[[v20-23-11]]

^<<v20-23-11,11>>^ Porque o seu redentor é  forte; ele pleiteará a sua causa contra ti.

[[v20-23-12]]

^<<v20-23-12,12>>^ Aplica à disciplina o teu coração e os teus ouvidos às palavras do conhecimento.

[[v20-23-13]]

^<<v20-23-13,13>>^ Não retires a disciplina da criança, porque, fustigando-a com a vara, nem por isso  morrerá.

[[v20-23-14]]

^<<v20-23-14,14>>^ Tu a fustigarás com a vara e livrarás a sua alma do inferno.

[[v20-23-15]]

^<<v20-23-15,15>>^ Filho meu, se o teu coração for sábio, alegrar-se-á o meu coração, sim, o meu próprio.

[[v20-23-16]]

^<<v20-23-16,16>>^ E exultarão os meus rins, quando os teus lábios falarem cousas retas.

[[v20-23-17]]

^<<v20-23-17,17>>^ Não tenha o teu coração inveja dos pecadores; antes sê no temor do Senhor todo o dia.

[[v20-23-18]]

^<<v20-23-18,18>>^ Porque deveras há um  fim bom : não será malograda a tua esperança.

[[v20-23-19]]

^<<v20-23-19,19>>^ Ouve tu, filho meu, e sê sábio, e dirige no caminho o teu coração.

[[v20-23-20]]

^<<v20-23-20,20>>^ Não estejas entre os beberrões de vinho, nem  entre os comilões de carne.

[[v20-23-21]]

^<<v20-23-21,21>>^ Porque o beberrão e o comilão cairão em pobreza; e a sonolência faz trazer os vestidos rotos.

[[v20-23-22]]

^<<v20-23-22,22>>^ Ouve a teu pai, que te gerou, e não desprezes a tua mãe, quando vier a envelhecer.

[[v20-23-23]]

^<<v20-23-23,23>>^ Compra a verdade, e não a vendas: sim, a sabedoria, e a disciplina, e a prudência.

[[v20-23-24]]

^<<v20-23-24,24>>^ Grandemente se regozijará o pai do justo, e  o que gerar a um  sábio se alegrará nele.

[[v20-23-25]]

^<<v20-23-25,25>>^ Alegrem-se teu pai e tua mãe, e regozije-se a que te gerou.

[[v20-23-26]]

^<<v20-23-26,26>>^ Dá-me, filho meu, o teu coração, e os teus olhos observem os meus caminhos.

[[v20-23-27]]

^<<v20-23-27,27>>^ Porque cova profunda é  a prostituta, e poço estreito a estranha.

[[v20-23-28]]

^<<v20-23-28,28>>^ Também ela, como um salteador, se põe a espreitar, e multiplica entre os homens os iníquos.

[[v20-23-29]]

^<<v20-23-29,29>>^ Para quem são os ais? para quem os pesares? para quem as pelejas? para quem as queixas? para quem as feridas sem causa? e  para quem os olhos vermelhos?

[[v20-23-30]]

^<<v20-23-30,30>>^ Para os que se demoram perto do vinho, para os que andam buscando bebida misturada.

[[v20-23-31]]

^<<v20-23-31,31>>^ Não olhes para o vinho, quando se mostra vermelho, quando resplandece no copo, e  se escoa suavemente.

[[v20-23-32]]

^<<v20-23-32,32>>^ No seu fim morderá como a cobra, e como o basilisco picará.

[[v20-23-33]]

^<<v20-23-33,33>>^ Os teus olhos olharão para as mulheres  estranhas, e o teu coração falará perversidades.

[[v20-23-34]]

^<<v20-23-34,34>>^ E serás como o que dorme no meio do mar, e como o que dorme no topo do mastro.

[[v20-23-35]]

^<<v20-23-35,35>>^ E dirás : Espancaram-me, e  não me doeu; bateram-me, e  não o senti; quando virei a despertar? ainda tornarei a buscá-la outra vez.

'''

xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[&#60; Capítulo Anterior] | <<v20-23-0,Topo>> | xref:020-proverbios/020-proverbios-024.adoc#v20-24-0[Próximo Capítulo &#62;]