include::./index.adoc[]

[[v20-18-0]]
=== Provérbios, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v20-18-1]]

^<<v20-18-1,1>>^ BUSCA seu próprio desejo aquele que se separa; ele insurge-se contra a verdadeira sabedoria.

[[v20-18-2]]

^<<v20-18-2,2>>^ Não toma prazer o tolo no entendimento; senão em que se descubra o seu coração.

[[v20-18-3]]

^<<v20-18-3,3>>^ Vindo o ímpio, vem também o desprezo, e com a ignomínia a vergonha.

[[v20-18-4]]

^<<v20-18-4,4>>^ Águas profundas são as palavras da boca do homem, e  ribeiro transbordante é a fonte da sabedoria.

[[v20-18-5]]

^<<v20-18-5,5>>^ Não é bom ter respeito à pessoa do ímpio para derribar o justo em juízo.

[[v20-18-6]]

^<<v20-18-6,6>>^ Os lábios do tolo entram na contenda, e a sua boca brada por açoites.

[[v20-18-7]]

^<<v20-18-7,7>>^ A boca do tolo é a sua própria destruição, e os seus lábios um laço para a sua alma.

[[v20-18-8]]

^<<v20-18-8,8>>^ As palavras do linguareiro são  como doces bocados; e elas descem ao íntimo do ventre.

[[v20-18-9]]

^<<v20-18-9,9>>^ Também o negligente na sua obra é irmão do desperdiçador.

[[v20-18-10]]

^<<v20-18-10,10>>^ Torre forte é  o nome do Senhor; para ela correrá o justo, e estará em alto retiro.

[[v20-18-11]]

^<<v20-18-11,11>>^ A fazenda do rico é  sua cidade forte, e como um muro alto na sua imaginação.

[[v20-18-12]]

^<<v20-18-12,12>>^ Antes de ser  quebrantado eleva-se o coração do homem; e diante da honra vai a humildade.

[[v20-18-13]]

^<<v20-18-13,13>>^ Responder antes de ouvir, estultícia é , e vergonha.

[[v20-18-14]]

^<<v20-18-14,14>>^ O espírito do homem aliviará a sua enfermidade, mas ao espírito abatido quem o levantará?

[[v20-18-15]]

^<<v20-18-15,15>>^ O coração do entendido adquire o conhecimento, e o ouvido dos sábios busca a ciência.

[[v20-18-16]]

^<<v20-18-16,16>>^ O presente do homem alarga-lhe o caminho  e leva-o à presença dos grandes.

[[v20-18-17]]

^<<v20-18-17,17>>^ O que primeiro começa o seu pleito justo parece; mas vem o seu companheiro, e o examina.

[[v20-18-18]]

^<<v20-18-18,18>>^ A sorte faz cessar os pleitos, e faz separação entre os poderosos.

[[v20-18-19]]

^<<v20-18-19,19>>^ O irmão ofendido é mais difícil de conquistar do que uma cidade forte; e as contendas são  como ferrolhos dum  palácio.

[[v20-18-20]]

^<<v20-18-20,20>>^ Do fruto da boca de cada um se fartará o seu ventre: dos renovos dos seus lábios se fartará.

[[v20-18-21]]

^<<v20-18-21,21>>^ A morte e a vida estão  no poder da língua; e aquele que a ama comerá do seu fruto.

[[v20-18-22]]

^<<v20-18-22,22>>^ O que acha uma mulher acha uma cousa boa e alcançou a benevolência do Senhor.

[[v20-18-23]]

^<<v20-18-23,23>>^ O pobre fala com rogos, mas o rico responde com durezas.

[[v20-18-24]]

^<<v20-18-24,24>>^ O homem que tem muitos amigos pode congratular-se, mas há amigo mais chegado do que um irmão.

'''

xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[&#60; Capítulo Anterior] | <<v20-18-0,Topo>> | xref:020-proverbios/020-proverbios-019.adoc#v20-19-0[Próximo Capítulo &#62;]