include::./index.adoc[]

[[v20-14-0]]
=== Provérbios, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v20-14-1]]

^<<v20-14-1,1>>^ TODA a mulher sábia edifica a sua casa: mas a tola derruba-a com as suas mãos.

[[v20-14-2]]

^<<v20-14-2,2>>^ O que anda na sua sinceridade teme ao Senhor, mas o que se desvia de seus caminhos despreza-o.

[[v20-14-3]]

^<<v20-14-3,3>>^ Na boca do tolo está  a vara da soberba, mas os lábios do sábio preservá-lo-ão.

[[v20-14-4]]

^<<v20-14-4,4>>^ Não havendo bois, o celeiro fica limpo, mas pela força do boi há  abundância de colheitas.

[[v20-14-5]]

^<<v20-14-5,5>>^ A testemunha verdadeira não mentirá, mas a testemunha falsa se desboca em  mentiras.

[[v20-14-6]]

^<<v20-14-6,6>>^ O escarnecedor busca sabedoria, e não a acha , mas para o prudente o conhecimento é fácil.

[[v20-14-7]]

^<<v20-14-7,7>>^ Vai-te à presença do homem insensato, e nele não divisarás os lábios do conhecimento.

[[v20-14-8]]

^<<v20-14-8,8>>^ A sabedoria do prudente é  entender o seu caminho, mas a estultícia dos tolos é  enganar.

[[v20-14-9]]

^<<v20-14-9,9>>^ Os loucos zombam do pecado, mas entre os retos há  boa vontade.

[[v20-14-10]]

^<<v20-14-10,10>>^ O coração conhece a sua própria amargura, e o estranho não se entremeterá na sua alegria.

[[v20-14-11]]

^<<v20-14-11,11>>^ A casa dos ímpios se desfará, mas a tenda dos retos florescerá.

[[v20-14-12]]

^<<v20-14-12,12>>^ Há caminho que  ao homem parece  direito, mas o fim dele são  os caminhos da morte.

[[v20-14-13]]

^<<v20-14-13,13>>^ Até no riso terá dor o coração, e o fim da alegria é  tristeza.

[[v20-14-14]]

^<<v20-14-14,14>>^ Dos seus caminhos se fartará o infiel de coração, mas o homem bom se fartará de si mesmo.

[[v20-14-15]]

^<<v20-14-15,15>>^ O simples dá crédito a cada palavra, mas o prudente atenta para os seus passos.

[[v20-14-16]]

^<<v20-14-16,16>>^ O sábio teme, e desvia-se do mal, mas o tolo encoleriza-se, e dá-se por seguro.

[[v20-14-17]]

^<<v20-14-17,17>>^ O que presto se ira fará doidices, e o homem de más imaginações será aborrecido.

[[v20-14-18]]

^<<v20-14-18,18>>^ Os simples herdarão a estultícia, mas os prudentes se  coroarão de conhecimento.

[[v20-14-19]]

^<<v20-14-19,19>>^ Os maus inclinam-se perante a face dos bons, e os ímpios diante das portas do justo.

[[v20-14-20]]

^<<v20-14-20,20>>^ O pobre é aborrecido até do companheiro, mas os amigos dos ricos são  muitos.

[[v20-14-21]]

^<<v20-14-21,21>>^ O que despreza ao seu companheiro peca, mas o que se compadece dos humildes é  bem-aventurado.

[[v20-14-22]]

^<<v20-14-22,22>>^ Porventura  não erram os que praticam o mal? mas beneficência e fidelidade haverá  para os que praticam o bem.

[[v20-14-23]]

^<<v20-14-23,23>>^ Em todo o trabalho há proveito, mas a palavra dos lábios só encaminha  para a pobreza.

[[v20-14-24]]

^<<v20-14-24,24>>^ A coroa dos sábios é  a sua riqueza, a estultícia dos tolos é só estultícia.

[[v20-14-25]]

^<<v20-14-25,25>>^ A testemunha verdadeira livra as almas, mas o que se desboca em  mentiras é  enganador.

[[v20-14-26]]

^<<v20-14-26,26>>^ No temor do Senhor há  firme confiança e ele  será um  refúgio para seus filhos.

[[v20-14-27]]

^<<v20-14-27,27>>^ O temor do Senhor é uma  fonte de vida, para preservar dos laços da morte.

[[v20-14-28]]

^<<v20-14-28,28>>^ Na multidão do povo está  a magnificência do rei, mas na falta de povo a perturbação do príncipe.

[[v20-14-29]]

^<<v20-14-29,29>>^ O longânimo é grande em entendimento, mas o de ânimo precipitado exalta a loucura.

[[v20-14-30]]

^<<v20-14-30,30>>^ O coração com saúde é  a vida da carne, mas a inveja é  a podridão dos ossos.

[[v20-14-31]]

^<<v20-14-31,31>>^ O que oprime ao pobre insulta àquele que o criou, mas o que se compadece do necessitado honra-o.

[[v20-14-32]]

^<<v20-14-32,32>>^ Pela sua malícia será lançado fora o ímpio, mas o justo até  na sua morte tem esperança.

[[v20-14-33]]

^<<v20-14-33,33>>^ No coração do prudente repousa a sabedoria, mas o que há  no interior dos tolos se conhece.

[[v20-14-34]]

^<<v20-14-34,34>>^ A justiça exalta as nações, mas o pecado é  o opróbrio dos povos.

[[v20-14-35]]

^<<v20-14-35,35>>^ O rei tem seu contentamento no servo prudente, mas sobre o que procede indignamente cairá o seu furor.

'''

xref:020-proverbios/020-proverbios-013.adoc#v20-13-0[&#60; Capítulo Anterior] | <<v20-14-0,Topo>> | xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[Próximo Capítulo &#62;]