include::./index.adoc[]

[[v20-12-0]]
=== Provérbios, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v20-12-1]]

^<<v20-12-1,1>>^ O QUE ama a correção ama o conhecimento, mas o que aborrece a repreensão é  um bruto.

[[v20-12-2]]

^<<v20-12-2,2>>^ O homem de bem alcançará o favor do Senhor, mas ao homem de perversas imaginações ele condenará.

[[v20-12-3]]

^<<v20-12-3,3>>^ O homem não se estabelecerá pela impiedade, mas a raiz dos justos não será removida.

[[v20-12-4]]

^<<v20-12-4,4>>^ A mulher virtuosa é  a coroa do seu marido, mas a que procede vergonhosamente é  como apodrecimento nos seus ossos.

[[v20-12-5]]

^<<v20-12-5,5>>^ Os pensamentos do justo são  retos, mas  os conselhos do ímpio engano.

[[v20-12-6]]

^<<v20-12-6,6>>^ As palavras dos ímpios são  para armarem ciladas ao sangue, mas a boca dos retos os livrará.

[[v20-12-7]]

^<<v20-12-7,7>>^ Transtornados serão os ímpios, e não serão mais , mas a casa dos justos permanecerá.

[[v20-12-8]]

^<<v20-12-8,8>>^ Segundo o seu entendimento, será louvado cada qual, mas o perverso de coração estará em desprezo.

[[v20-12-9]]

^<<v20-12-9,9>>^ Melhor é  o que se estima em pouco, e tem servos, do que o que se honra a si mesmo  e tem falta de pão.

[[v20-12-10]]

^<<v20-12-10,10>>^ O justo olha pela vida dos seus animais, mas as misericórdias dos ímpios são  cruéis.

[[v20-12-11]]

^<<v20-12-11,11>>^ O que lavra a sua terra se fartará de pão, mas o que segue os ociosos está  falto de juízo.

[[v20-12-12]]

^<<v20-12-12,12>>^ Deseja o ímpio a rede dos maus, mas a raiz dos justos produz o seu  fruto.

[[v20-12-13]]

^<<v20-12-13,13>>^ O laço do ímpio está na transgressão dos lábios, mas o justo sairá da angústia.

[[v20-12-14]]

^<<v20-12-14,14>>^ Cada um se farta de bem pelo fruto da sua boca, e o que as mãos do homem fizerem isso ele receberá.

[[v20-12-15]]

^<<v20-12-15,15>>^ O caminho do tolo é  reto aos seus olhos, mas o que dá ouvidos ao conselho é  sábio.

[[v20-12-16]]

^<<v20-12-16,16>>^ A ira do louco se conhece no mesmo dia, mas o avisado encobre a afronta.

[[v20-12-17]]

^<<v20-12-17,17>>^ O que diz a verdade manifesta a justiça, mas a testemunha falsa engana.

[[v20-12-18]]

^<<v20-12-18,18>>^ Há alguns  cujas palavras  são como pontas de espada, mas a língua dos sábios é  saúde.

[[v20-12-19]]

^<<v20-12-19,19>>^ O lábio de verdade ficará para sempre, mas a língua mentirosa dura só  um momento.

[[v20-12-20]]

^<<v20-12-20,20>>^ Engano há  no coração dos que maquinam mal, mas alegria têm  os que aconselham a paz.

[[v20-12-21]]

^<<v20-12-21,21>>^ Nenhum agravo sobrevirá ao justo, mas os ímpios ficam cheios de mal.

[[v20-12-22]]

^<<v20-12-22,22>>^ Os lábios mentirosos são  abomináveis ao Senhor, mas os que obram fielmente são  o seu deleite.

[[v20-12-23]]

^<<v20-12-23,23>>^ O homem avisado encobre o conhecimento, mas o coração dos tolos proclama a estultícia.

[[v20-12-24]]

^<<v20-12-24,24>>^ A mão dos diligentes dominará, mas os enganadores serão tributários.

[[v20-12-25]]

^<<v20-12-25,25>>^ A solicitude no coração do homem o abate, mas uma  boa palavra o alegra.

[[v20-12-26]]

^<<v20-12-26,26>>^ O justo é um guia para o seu companheiro, mas o caminho dos ímpios os faz errar.

[[v20-12-27]]

^<<v20-12-27,27>>^ O preguiçoso não assará a sua caça, mas o bem precioso do homem é  ser diligente.

[[v20-12-28]]

^<<v20-12-28,28>>^ Na vereda da justiça está  a vida, e no  caminho da sua carreira não há  morte.

'''

xref:020-proverbios/020-proverbios-011.adoc#v20-11-0[&#60; Capítulo Anterior] | <<v20-12-0,Topo>> | xref:020-proverbios/020-proverbios-013.adoc#v20-13-0[Próximo Capítulo &#62;]