include::./index.adoc[]

[[v20-16-0]]
=== Provérbios, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v20-16-1]]

^<<v20-16-1,1>>^ DO homem são  as preparações do coração, mas do Senhor a resposta da boca.

[[v20-16-2]]

^<<v20-16-2,2>>^ Todos os caminhos do homem são  limpos aos seus olhos, mas o Senhor pesa os espíritos.

[[v20-16-3]]

^<<v20-16-3,3>>^ Confia ao Senhor as tuas obras, e teus pensamentos serão estabelecidos.

[[v20-16-4]]

^<<v20-16-4,4>>^ O Senhor fez todas as cousas para os seus próprios fins, e até ao ímpio para o dia do mal.

[[v20-16-5]]

^<<v20-16-5,5>>^ Abominação é para o Senhor todo o altivo de coração: ainda que ele junte  mão à mão, não ficará impune.

[[v20-16-6]]

^<<v20-16-6,6>>^ Pela misericórdia e pela verdade se purifica a iniquidade, e pelo temor do Senhor os homens se desviam do mal.

[[v20-16-7]]

^<<v20-16-7,7>>^ Sendo os caminhos do homem agradáveis ao Senhor, até a seus inimigos faz que tenham paz com ele.

[[v20-16-8]]

^<<v20-16-8,8>>^ Melhor é o pouco com justiça, do que a abundância de colheita com injustiça.

[[v20-16-9]]

^<<v20-16-9,9>>^ O coração do homem considera o seu caminho, mas o Senhor lhe dirige os passos.

[[v20-16-10]]

^<<v20-16-10,10>>^ Adivinhação se acha  nos lábios do rei: em juízo não prevaricará a sua boca.

[[v20-16-11]]

^<<v20-16-11,11>>^ O peso e a balança justa são  do Senhor; obra sua são  todas as pedras da bolsa.

[[v20-16-12]]

^<<v20-16-12,12>>^ Abominação é para os reis o praticarem a impiedade, porque com justiça se estabelece o trono.

[[v20-16-13]]

^<<v20-16-13,13>>^ Os lábios de justiça são  o contentamento dos reis, e eles amarão o que fala cousas retas.

[[v20-16-14]]

^<<v20-16-14,14>>^ O furor do rei é como  um mensageiro da morte, mas o homem sábio o apaziguará.

[[v20-16-15]]

^<<v20-16-15,15>>^ Na luz do rosto do rei está  a vida, e a sua benevolência é  como a nuvem de chuva serôdia.

[[v20-16-16]]

^<<v20-16-16,16>>^ Quanto melhor é  adquirir a sabedoria do que o ouro! e quanto mais excelente adquirir a prudência do que a prata!

[[v20-16-17]]

^<<v20-16-17,17>>^ O alto caminho dos retos é  desviar-se do mal; o que guarda o seu caminho preserva a sua alma.

[[v20-16-18]]

^<<v20-16-18,18>>^ A soberba precede a ruína, e a altivez do espírito precede a queda.

[[v20-16-19]]

^<<v20-16-19,19>>^ Melhor é  ser humilde de espírito com os mansos, do que repartir o despojo com os soberbos.

[[v20-16-20]]

^<<v20-16-20,20>>^ O que atenta prudentemente para a palavra achará o bem, e o que confia no Senhor será  bem-aventurado.

[[v20-16-21]]

^<<v20-16-21,21>>^ O sábio de coração será chamado prudente, e a doçura dos lábios aumentará o ensino.

[[v20-16-22]]

^<<v20-16-22,22>>^ O entendimento, para aqueles que o possuem, é uma  fonte de vida, mas a instrução dos tolos é  a sua estultícia.

[[v20-16-23]]

^<<v20-16-23,23>>^ O coração do sábio instrui a sua boca, e acrescenta doutrina aos seus lábios.

[[v20-16-24]]

^<<v20-16-24,24>>^ Favo de mel são  as palavras suaves, doces para a alma, e saúde para os ossos.

[[v20-16-25]]

^<<v20-16-25,25>>^ Há caminho que parece direito ao homem, mas o seu fim são  os caminhos da morte.

[[v20-16-26]]

^<<v20-16-26,26>>^ O trabalhador trabalha para si mesmo, porque a sua boca o instiga.

[[v20-16-27]]

^<<v20-16-27,27>>^ O homem vão cava o mal, e nos seus lábios se acha  como que um  fogo ardente.

[[v20-16-28]]

^<<v20-16-28,28>>^ O homem perverso levanta a contenda, e o difamador separa os maiores amigos.

[[v20-16-29]]

^<<v20-16-29,29>>^ O homem violento persuade o seu companheiro, e guia-o por caminho não bom.

[[v20-16-30]]

^<<v20-16-30,30>>^ Fecha os olhos para imaginar perversidades; mordendo os lábios, efetua o mal.

[[v20-16-31]]

^<<v20-16-31,31>>^ Coroa de honra são  as cãs, achando-se elas no caminho da justiça.

[[v20-16-32]]

^<<v20-16-32,32>>^ Melhor é o longânimo do que o valente, e o que governa o seu espírito do que o que toma uma  cidade.

[[v20-16-33]]

^<<v20-16-33,33>>^ A sorte se lança no regaço, mas do Senhor procede  toda a sua disposição.

'''

xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[&#60; Capítulo Anterior] | <<v20-16-0,Topo>> | xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[Próximo Capítulo &#62;]