include::./index.adoc[]

[[v20-26-0]]
=== Provérbios, 26
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v20-26-1]]

^<<v20-26-1,1>>^ COMO a neve no verão, e como a chuva na sega, assim não é conveniente ao louco a honra.

[[v20-26-2]]

^<<v20-26-2,2>>^ Como o pássaro no seu vaguear, como a andorinha no seu voo, assim a maldição sem causa não virá.

[[v20-26-3]]

^<<v20-26-3,3>>^ O açoite é para o cavalo, o freio para o jumento, e a vara para as costas dos tolos.

[[v20-26-4]]

^<<v20-26-4,4>>^ Não respondas ao tolo segundo a sua estultícia; para que também te não faças semelhante a ele.

[[v20-26-5]]

^<<v20-26-5,5>>^ Responde ao tolo segundo a sua estultícia, para que não seja sábio aos seus olhos.

[[v20-26-6]]

^<<v20-26-6,6>>^ Os pés corta, e  o dano bebe, quem manda mensagens pelas mãos dum  tolo.

[[v20-26-7]]

^<<v20-26-7,7>>^ Como as pernas do coxo, que pendem frouxas, assim é  o provérbio na boca dos tolos.

[[v20-26-8]]

^<<v20-26-8,8>>^ Como o que prende a pedra preciosa  na funda, assim é  aquele que dá honra ao tolo.

[[v20-26-9]]

^<<v20-26-9,9>>^ Como o espinho que entra na mão do ébrio, assim é  o provérbio na boca dos tolos.

[[v20-26-10]]

^<<v20-26-10,10>>^ Como um besteiro que a todos espanta, assim é o que assalaria os tolos e os transgressores.

[[v20-26-11]]

^<<v20-26-11,11>>^ Como o cão que  torna ao seu vômito, assim é  o tolo que reitera a sua estultícia.

[[v20-26-12]]

^<<v20-26-12,12>>^ Tens visto a um  homem que é  sábio a seus próprios  olhos? maior esperança há  no tolo do que nele.

[[v20-26-13]]

^<<v20-26-13,13>>^ Diz o preguiçoso: Um  leão está  no caminho; um  leão está  nas ruas.

[[v20-26-14]]

^<<v20-26-14,14>>^ Como  a porta se revolve nos seus gonzos, assim o preguiçoso na sua cama.

[[v20-26-15]]

^<<v20-26-15,15>>^ O preguiçoso esconde a sua mão no seio: enfada-se de a levar à sua boca.

[[v20-26-16]]

^<<v20-26-16,16>>^ Mais sábio é o preguiçoso a seus olhos do que sete homens  que bem respondem.

[[v20-26-17]]

^<<v20-26-17,17>>^ O que, passando, se mete  em questão  alheia é como  aquele que toma um cão  pelas orelhas.

[[v20-26-18]]

^<<v20-26-18,18>>^ Como o louco que lança de si  faíscas, frechas, e mortandades,

[[v20-26-19]]

^<<v20-26-19,19>>^ Assim é  o homem que engana o seu próximo, e diz: Fiz isso por brincadeira.

[[v20-26-20]]

^<<v20-26-20,20>>^ Sem lenha, o fogo se apagará; e, não havendo  maldizente, cessará a contenda.

[[v20-26-21]]

^<<v20-26-21,21>>^ Como o carvão é  para o borralho, e a lenha para o fogo, assim é  o homem contencioso para acender rixas.

[[v20-26-22]]

^<<v20-26-22,22>>^ As palavras do maldizente são como deliciosos bocados, que descem ao íntimo do ventre.

[[v20-26-23]]

^<<v20-26-23,23>>^ Como  o caco coberto de escórias de prata, assim são  os lábios ardentes e o coração maligno.

[[v20-26-24]]

^<<v20-26-24,24>>^ Aquele que aborrece dissimula com os seus beiços, mas no seu interior encobre o engano.

[[v20-26-25]]

^<<v20-26-25,25>>^ Quando te  suplicar com a sua voz, não te  fies nele, porque sete abominações há  no seu coração.

[[v20-26-26]]

^<<v20-26-26,26>>^ Ainda que o seu ódio se encobre com engano, a sua malícia se descobrirá na congregação.

[[v20-26-27]]

^<<v20-26-27,27>>^ O que faz uma  cova nela cairá; e o que revolve a pedra, esta  sobre ele rolará.

[[v20-26-28]]

^<<v20-26-28,28>>^ A língua falsa aborrece aquele a quem ela tem maravilhado, e a boca lisonjeira obra a ruína.

'''

xref:020-proverbios/020-proverbios-025.adoc#v20-25-0[&#60; Capítulo Anterior] | <<v20-26-0,Topo>> | xref:020-proverbios/020-proverbios-027.adoc#v20-27-0[Próximo Capítulo &#62;]