include::./index.adoc[]

[[v20-11-0]]
=== Provérbios, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v20-11-1]]

^<<v20-11-1,1>>^ BALANÇA enganosa é  abominação para o Senhor, mas o peso justo é o seu prazer.

[[v20-11-2]]

^<<v20-11-2,2>>^ Vindo a soberba, virá também a afronta; mas com os humildes está a sabedoria.

[[v20-11-3]]

^<<v20-11-3,3>>^ A sinceridade dos sinceros os encaminhará, mas a perversidade dos desleais os destruirá.

[[v20-11-4]]

^<<v20-11-4,4>>^ Não aproveitam as riquezas no dia da ira, mas a justiça livra da morte.

[[v20-11-5]]

^<<v20-11-5,5>>^ A justiça do sincero endireitará o seu caminho, mas o ímpio pela sua impiedade cairá.

[[v20-11-6]]

^<<v20-11-6,6>>^ A justiça dos virtuosos os livrará, mas na sua perversidade serão apanhados os iníquos.

[[v20-11-7]]

^<<v20-11-7,7>>^ Morrendo o homem ímpio perece a sua  expectação, e a esperança da iniquidade perde-se.

[[v20-11-8]]

^<<v20-11-8,8>>^ O justo é libertado da angústia, e o ímpio fica em seu lugar.

[[v20-11-9]]

^<<v20-11-9,9>>^ O hipócrita com a boca danifica o seu próximo; mas os justos são libertados pelo conhecimento.

[[v20-11-10]]

^<<v20-11-10,10>>^ No bem dos justos exulta a cidade, e, perecendo os ímpios, há júbilo.

[[v20-11-11]]

^<<v20-11-11,11>>^ Pela bênção dos sinceros se exalta a cidade, mas pela boca dos ímpios é  derribada.

[[v20-11-12]]

^<<v20-11-12,12>>^ O que despreza o seu próximo é falto de sabedoria; mas o homem de entendimento cala-se.

[[v20-11-13]]

^<<v20-11-13,13>>^ O que anda praguejando descobre o segredo, mas o fiel de espírito encobre o negócio.

[[v20-11-14]]

^<<v20-11-14,14>>^ Não havendo sábia direção, o povo cai; mas na multidão de conselheiros há segurança.

[[v20-11-15]]

^<<v20-11-15,15>>^ Decerto sofrerá severamente aquele que fica por fiador do estranho, mas o que aborrece a fiança estará seguro.

[[v20-11-16]]

^<<v20-11-16,16>>^ A mulher aprazível guarda a honra, como os violentos guardam as riquezas.

[[v20-11-17]]

^<<v20-11-17,17>>^ O homem benigno faz bem à sua própria alma, mas o cruel perturba a sua própria  carne.

[[v20-11-18]]

^<<v20-11-18,18>>^ O ímpio recebe um salário enganoso, mas para  o que semeia justiça haverá  galardão certo.

[[v20-11-19]]

^<<v20-11-19,19>>^ Como a justiça encaminha  para a vida, assim o que segue o mal faz isso para sua morte.

[[v20-11-20]]

^<<v20-11-20,20>>^ Abominação para o Senhor são os perversos de coração, mas os que são perfeitos em seu caminho são o seu deleite.

[[v20-11-21]]

^<<v20-11-21,21>>^ Ainda que  o mau junte  mão à mão, não ficará sem castigo, mas a semente dos justos escapará.

[[v20-11-22]]

^<<v20-11-22,22>>^ Como joia de ouro em focinho de porca, assim  é a mulher formosa, que se aparta da razão.

[[v20-11-23]]

^<<v20-11-23,23>>^ O desejo dos justos é somente o bem, mas a esperança dos ímpios é  a ira.

[[v20-11-24]]

^<<v20-11-24,24>>^ Alguns  há que espalham, e ainda  se lhes  acrescenta mais; e outros  que retêm mais do que é  justo, mas é  para a sua  perda.

[[v20-11-25]]

^<<v20-11-25,25>>^ A alma generosa engordará, e o que regar também será regado.

[[v20-11-26]]

^<<v20-11-26,26>>^ Ao que retém o trigo o povo o amaldiçoa, mas bênção haverá  sobre a cabeça do vendedor.

[[v20-11-27]]

^<<v20-11-27,27>>^ O que busca cedo o bem, busca favor, mas ao que procura o mal, ele lhe sobrevirá.

[[v20-11-28]]

^<<v20-11-28,28>>^ Aquele que confia nas suas riquezas cairá, mas os justos reverdecerão como a rama.

[[v20-11-29]]

^<<v20-11-29,29>>^ O que perturba a sua casa herdará o vento, e o tolo será  servo do entendido de coração.

[[v20-11-30]]

^<<v20-11-30,30>>^ O fruto do justo é  árvore de vida, e o que ganha almas sábio é.

[[v20-11-31]]

^<<v20-11-31,31>>^ Eis que o justo é punido na terra; quanto mais o ímpio e o pecador!

'''

xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[&#60; Capítulo Anterior] | <<v20-11-0,Topo>> | xref:020-proverbios/020-proverbios-012.adoc#v20-12-0[Próximo Capítulo &#62;]