include::./index.adoc[]

[[v40-8-0]]
=== Mateus, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-8-1]]

^<<v40-8-1,1>>^ E DESCENDO ele do monte, seguiu-o uma grande multidão.

[[v40-8-2]]

^<<v40-8-2,2>>^ E, eis que veio um leproso, e o adorou, dizendo: Senhor, se quiseres, podes tornar-me limpo.

[[v40-8-3]]

^<<v40-8-3,3>>^ E Jesus, estendendo a mão, tocou-o dizendo: Quero: sê limpo. E logo ficou purificado da lepra.

[[v40-8-4]]

^<<v40-8-4,4>>^ Disse-lhe então Jesus: Olha não o digas a alguém, mas vai, mostra-te ao sacerdote, e apresenta a oferta que Moisés determinou, para lhes servir de testemunho.

[[v40-8-5]]

^<<v40-8-5,5>>^ E, entrando Jesus em Capernaum, chegou junto dele  um centurião, rogando-lhe,

[[v40-8-6]]

^<<v40-8-6,6>>^ E dizendo: Senhor, o meu criado jaz em casa paralítico, e violentamente atormentado.

[[v40-8-7]]

^<<v40-8-7,7>>^ E Jesus lhe disse: Eu irei, e lhe darei saúde.

[[v40-8-8]]

^<<v40-8-8,8>>^ E o centurião, respondendo, disse: Senhor, não sou digno de que entres debaixo do meu telhado, mas dize somente uma palavra, e o meu criado sarará;

[[v40-8-9]]

^<<v40-8-9,9>>^ Pois também eu sou homem sob autoridade, e tenho soldados às minhas ordens; e digo a este: Vai, e ele vai; e a outro: Vem, e ele vem; e ao meu criado: Faze isto, e ele o faz.

[[v40-8-10]]

^<<v40-8-10,10>>^ E maravilhou-se Jesus, ouvindo isto , e disse aos que o seguiam: Em verdade vos digo que nem mesmo em Israel encontrei tanta fé.

[[v40-8-11]]

^<<v40-8-11,11>>^ Mas eu vos digo que muitos virão do oriente e do ocidente, e assentar-se-ão à mesa com Abraão, e Isaque, e Jacó, no reino dos céus;

[[v40-8-12]]

^<<v40-8-12,12>>^ E os filhos do reino serão lançados nas trevas exteriores: ali haverá pranto e ranger de dentes.

[[v40-8-13]]

^<<v40-8-13,13>>^ Então disse Jesus ao centurião: Vai e como creste te seja feito. E naquela mesma hora o seu criado sarou.

[[v40-8-14]]

^<<v40-8-14,14>>^ E Jesus, entrando em casa de Pedro, viu a sogra deste jazendo com febre.

[[v40-8-15]]

^<<v40-8-15,15>>^ E tocou-lhe na mão, e a febre a deixou; e levantou-se, e serviu-os.

[[v40-8-16]]

^<<v40-8-16,16>>^ E, chegada a tarde, trouxeram-lhe muitos endemoninhados e ele com a sua palavra expulsou deles  os espíritos, e curou todos os que estavam enfermos;

[[v40-8-17]]

^<<v40-8-17,17>>^ Para que se cumprisse o que fora dito pelo profeta Isaías, que diz: Ele tomou sobre si  as nossas enfermidades, e levou as nossas  doenças.

[[v40-8-18]]

^<<v40-8-18,18>>^ E Jesus, vendo em torno de si uma  grande multidão, ordenou que passassem para a banda d’além;

[[v40-8-19]]

^<<v40-8-19,19>>^ E, aproximando-se dele  um escriba, disse: Mestre, aonde quer que fores, eu te seguirei.

[[v40-8-20]]

^<<v40-8-20,20>>^ E disse Jesus: As raposas têm covis, e as aves do céu têm  ninhos, mas o Filho do homem não tem onde reclinar a cabeça.

[[v40-8-21]]

^<<v40-8-21,21>>^ E outro de seus discípulos lhe disse: Senhor, permite-me que primeiramente vá sepultar meu pai.

[[v40-8-22]]

^<<v40-8-22,22>>^ Jesus, porém, disse-lhe: Segue-me, e deixa aos mortos sepultar os seus mortos.

[[v40-8-23]]

^<<v40-8-23,23>>^ E, entrando ele no barco, seus discípulos o seguiram;

[[v40-8-24]]

^<<v40-8-24,24>>^ E eis que no mar se levantou uma  tempestade, tão grande que o barco era coberto pelas ondas; ele, porém, estava dormindo.

[[v40-8-25]]

^<<v40-8-25,25>>^ E os seus discípulos, aproximando-se o despertaram, dizendo: Senhor, salva-nos, que perecemos.

[[v40-8-26]]

^<<v40-8-26,26>>^ E ele disse-lhes: Por que temeis, homens  de pouca fé? Então, levantando-se, repreendeu os ventos e o mar, e seguiu-se uma grande bonança.

[[v40-8-27]]

^<<v40-8-27,27>>^ E aqueles homens se maravilharam, dizendo: Que homem é este, que até os ventos e o mar lhe obedecem?

[[v40-8-28]]

^<<v40-8-28,28>>^ E, tendo chegado à outra banda, à província dos gergesenos, saíram-lhe ao encontro dois endemoninhados, vindos dos sepulcros; tão ferozes eram que ninguém podia passar por aquele caminho.

[[v40-8-29]]

^<<v40-8-29,29>>^ E eis que clamaram, dizendo: Que temos nós contigo, Jesus Filho de Deus? Vieste aqui atormentar-nos antes de tempo?

[[v40-8-30]]

^<<v40-8-30,30>>^ E andava pastando distante deles uma manada de muitos porcos.

[[v40-8-31]]

^<<v40-8-31,31>>^ E os demônios rogaram-lhe, dizendo: Se nos expulsas, permite-nos que entremos naquela manada de porcos.

[[v40-8-32]]

^<<v40-8-32,32>>^ E ele lhes disse: Ide. E, saindo eles, se introduziram na manada dos porcos; e eis que toda aquela manada de porcos se precipitou no mar por um despenhadeiro, e morreram nas águas.

[[v40-8-33]]

^<<v40-8-33,33>>^ Os porqueiros fugiram, e, chegando à cidade, divulgaram tudo o que acontecera  aos endemoninhados.

[[v40-8-34]]

^<<v40-8-34,34>>^ E eis que toda aquela cidade saiu ao encontro de Jesus, e, vendo-o, rogaram-lhe que se retirasse dos seus termos.

'''

xref:040-mateus/040-mateus-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v40-8-0,Topo>> | xref:040-mateus/040-mateus-009.adoc#v40-9-0[Próximo Capítulo &#62;]