include::./index.adoc[]

[[v40-14-0]]
=== Mateus, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-14-1]]

^<<v40-14-1,1>>^ NAQUELE tempo ouviu Herodes, o tetrarca, a fama de Jesus.

[[v40-14-2]]

^<<v40-14-2,2>>^ E disse aos seus criados: Este é João Batista; ressuscitou dos mortos, e por isso estas maravilhas operam nele.

[[v40-14-3]]

^<<v40-14-3,3>>^ Porque Herodes tinha prendido João, e tinha-o manietado e encerrado no cárcere por causa de Herodias, mulher de seu irmão Filipe;

[[v40-14-4]]

^<<v40-14-4,4>>^ Porque João lhe dissera: Não te é lícito possuí-la.

[[v40-14-5]]

^<<v40-14-5,5>>^ E, querendo matá-lo, temia o povo; porque o tinham como profeta.

[[v40-14-6]]

^<<v40-14-6,6>>^ Festejando-se, porém, o dia natalício de Herodes, dançou a filha de Herodias diante dele, e agradou a Herodes.

[[v40-14-7]]

^<<v40-14-7,7>>^ Pelo que prometeu com juramento dar-lhe tudo o que pedisse;

[[v40-14-8]]

^<<v40-14-8,8>>^ E ela, instruída previamente por sua mãe, disse: Dá-me aqui num prato a cabeça de João Batista.

[[v40-14-9]]

^<<v40-14-9,9>>^ E o rei afligiu-se, mas, por causa do juramento, e dos que estavam à mesa com ele, ordenou que se lhe  desse.

[[v40-14-10]]

^<<v40-14-10,10>>^ E mandou degolar João no cárcere,

[[v40-14-11]]

^<<v40-14-11,11>>^ E a sua cabeça foi trazida num prato, e dada à jovem, e ela a  levou a sua mãe.

[[v40-14-12]]

^<<v40-14-12,12>>^ E chegaram os seus discípulos, e levaram o corpo, e o sepultaram; e foram anunciá-lo a Jesus.

[[v40-14-13]]

^<<v40-14-13,13>>^ E Jesus, ouvindo isto , retirou-se dali num barco, para um lugar deserto, apartado; e, sabendo- o  o povo, seguiu-o a pé desde as cidades.

[[v40-14-14]]

^<<v40-14-14,14>>^ E Jesus, saindo, viu uma grande multidão, e possuído de íntima compaixão para com ela, curou os seus enfermos.

[[v40-14-15]]

^<<v40-14-15,15>>^ E, sendo chegada a tarde, os seus discípulos aproximaram-se dele, dizendo: O lugar é deserto, e a hora é já avançada; despede a multidão, para que vão pelas aldeias, e comprem comida para si.

[[v40-14-16]]

^<<v40-14-16,16>>^ Jesus, porém, lhes disse: Não é mister que vão: dai-lhes vós de comer.

[[v40-14-17]]

^<<v40-14-17,17>>^ Então eles lhe disseram: Não temos aqui senão cinco pães e dois peixes.

[[v40-14-18]]

^<<v40-14-18,18>>^ E ele disse: Trazei-mos aqui.

[[v40-14-19]]

^<<v40-14-19,19>>^ E, tendo mandado que a multidão se assentasse sobre a erva, tomou os cinco pães e os dois peixes, e erguendo os olhos ao céu, os abençoou, e, partindo os pães, deu-os aos discípulos, e os discípulos à multidão.

[[v40-14-20]]

^<<v40-14-20,20>>^ E comeram todos, e saciaram-se; e levantaram dos pedaços, que sobejaram, doze alcofas cheias.

[[v40-14-21]]

^<<v40-14-21,21>>^ E os que comeram foram quase cinco mil homens, além das mulheres e crianças.

[[v40-14-22]]

^<<v40-14-22,22>>^ E logo ordenou Jesus que os seus discípulos entrassem no barco, e fossem adiante para a outra banda, enquanto despedia a multidão.

[[v40-14-23]]

^<<v40-14-23,23>>^ E, despedida a multidão, subiu ao monte para orar à parte. E, chegada já  a tarde, estava ali só.

[[v40-14-24]]

^<<v40-14-24,24>>^ E o barco estava já no meio do mar, açoitado pelas ondas; porque o vento era contrário;

[[v40-14-25]]

^<<v40-14-25,25>>^ Mas, à quarta vigília da noite, dirigiu-se Jesus para eles, caminhando por cima do mar.

[[v40-14-26]]

^<<v40-14-26,26>>^ E os discípulos, vendo-o caminhar sobre o mar, assustaram-se, dizendo: É um  fantasma. E gritaram, com medo.

[[v40-14-27]]

^<<v40-14-27,27>>^ Jesus, porém, lhes falou logo, dizendo: Tende bom ânimo, sou eu, não temais.

[[v40-14-28]]

^<<v40-14-28,28>>^ E respondeu-lhe Pedro, e disse: Senhor, se és tu, manda-me ir ter contigo por cima das águas.

[[v40-14-29]]

^<<v40-14-29,29>>^ E ele disse: Vem. E Pedro, descendo do barco, andou sobre as águas para ir ter com Jesus.

[[v40-14-30]]

^<<v40-14-30,30>>^ Mas, sentindo o vento forte, teve medo; e, começando a ir para o fundo, clamou, dizendo: Senhor, salva-me.

[[v40-14-31]]

^<<v40-14-31,31>>^ E logo Jesus, estendendo a mão, segurou-o, e disse-lhe: Homem  de pouca fé, por que duvidaste?

[[v40-14-32]]

^<<v40-14-32,32>>^ E, quando subiram para o barco, acalmou o vento.

[[v40-14-33]]

^<<v40-14-33,33>>^ Então aproximaram-se os que estavam no barco, e adoraram-no, dizendo: És verdadeiramente o Filho de Deus.

[[v40-14-34]]

^<<v40-14-34,34>>^ E, tendo passado para a outra banda, chegaram à terra de Genesaré.

[[v40-14-35]]

^<<v40-14-35,35>>^ E, quando os homens daquele lugar o conheceram, mandaram por todas aquelas terras em redor, e trouxeram-lhe todos os que estavam enfermos.

[[v40-14-36]]

^<<v40-14-36,36>>^ E rogavam-lhe que ao menos eles pudessem tocar a orla do seu vestido; e todos os que a  tocavam ficavam sãos.

'''

xref:040-mateus/040-mateus-013.adoc#v40-13-0[&#60; Capítulo Anterior] | <<v40-14-0,Topo>> | xref:040-mateus/040-mateus-015.adoc#v40-15-0[Próximo Capítulo &#62;]