include::./index.adoc[]

[[v40-1-0]]
=== Mateus, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-1-1]]

^<<v40-1-1,1>>^ LIVRO da geração de Jesus Cristo, filho de Davi, filho d’Abraão.

[[v40-1-2]]

^<<v40-1-2,2>>^ Abraão gerou a Isaque; e Isaque gerou a Jacó; e Jacó gerou a Judas e a seus irmãos;

[[v40-1-3]]

^<<v40-1-3,3>>^ E Judas gerou de Tamar a Farés e a Zará; e Farés gerou a Esrom; e Esrom gerou a Arão;

[[v40-1-4]]

^<<v40-1-4,4>>^ E Arão gerou a Aminadabe; e Aminadabe gerou a Naasom; e Naasom gerou a Salmom;

[[v40-1-5]]

^<<v40-1-5,5>>^ E Salmom gerou de Racabe a Booz, e Booz gerou de Rute a Obede; e Obede gerou a Jessé;

[[v40-1-6]]

^<<v40-1-6,6>>^ E Jessé gerou ao rei Davi; e o rei Davi gerou a Salomão da que foi mulher  de Urias;

[[v40-1-7]]

^<<v40-1-7,7>>^ E Salomão gerou a Roboão; e Roboão gerou a Abia: e Abia gerou a Asa;

[[v40-1-8]]

^<<v40-1-8,8>>^ E Asa gerou a Josafá; e Josafá gerou a Jorão; e Jorão gerou a Ozias;

[[v40-1-9]]

^<<v40-1-9,9>>^ E Ozias gerou a Joatão; e Joatão gerou a Acaz; e Acaz gerou a Ezequias;

[[v40-1-10]]

^<<v40-1-10,10>>^ E Ezequias gerou a Manassés; e Manassés gerou a Amom; e Amom gerou a Josias;

[[v40-1-11]]

^<<v40-1-11,11>>^ E Josias gerou a Jeconias e a seus irmãos na deportação para a Babilônia.

[[v40-1-12]]

^<<v40-1-12,12>>^ E, depois da deportação para a Babilônia, Jeconias gerou a Salatiel; e Salatiel gerou a Zorobabel;

[[v40-1-13]]

^<<v40-1-13,13>>^ E Zorobabel gerou a Abiúde; e Abiúde gerou a Eliaquim; e Eliaquim gerou a Azor;

[[v40-1-14]]

^<<v40-1-14,14>>^ E Azor gerou a Sadoque; e Sadoque gerou a Aquim; e Aquim gerou a Eliúde;

[[v40-1-15]]

^<<v40-1-15,15>>^ E Eliúde gerou a Eleazar; e Eleazar gerou a Matã; e Matã gerou a Jacó;

[[v40-1-16]]

^<<v40-1-16,16>>^ E Jacó gerou a José, marido de Maria, da qual nasceu Jesus , que se chama o Cristo.

[[v40-1-17]]

^<<v40-1-17,17>>^ De sorte que todas as gerações, desde Abraão até Davi, são  catorze gerações; e desde Davi até a deportação para a Babilônia, catorze gerações; e desde a deportação para a Babilônia até Cristo, catorze gerações.

[[v40-1-18]]

^<<v40-1-18,18>>^ Ora o nascimento de Jesus Cristo foi assim: Estando Maria, sua mãe, desposada com José, antes de se ajuntarem, achou-se ter concebido do Espírito Santo.

[[v40-1-19]]

^<<v40-1-19,19>>^ Então José, seu marido, como era justo, e a não queria infamar, intentou deixá-la secretamente.

[[v40-1-20]]

^<<v40-1-20,20>>^ E, projetando ele isto, eis que em sonho lhe apareceu um anjo do Senhor, dizendo: José, filho de Davi, não temas receber a Maria tua mulher, porque o que nela está gerado é do Espírito Santo;

[[v40-1-21]]

^<<v40-1-21,21>>^ E dará à luz um  filho e chamarás o seu nome Jesus ; porque ele salvará o seu povo dos seus pecados.

[[v40-1-22]]

^<<v40-1-22,22>>^ Tudo isto, aconteceu para que se cumprisse o que foi dito da parte do Senhor, pelo profeta, que diz:

[[v40-1-23]]

^<<v40-1-23,23>>^ Eis que a virgem conceberá e dará à luz um  filho, e chamá-lo-ão pelo nome de Emanuel , que traduzido é: Deus conosco.

[[v40-1-24]]

^<<v40-1-24,24>>^ E José, despertando do sonho, fez como o anjo do Senhor lhe ordenara, e recebeu a sua mulher;

[[v40-1-25]]

^<<v40-1-25,25>>^ E não a conheceu até que deu à luz seu filho, o primogênito; e pôs-lhe por nome Jesus .

'''

xref:039-malaquias/039-malaquias-004.adoc#v39-4-0[&#60; Capítulo Anterior] | <<v40-1-0,Topo>> | xref:040-mateus/040-mateus-002.adoc#v40-2-0[Próximo Capítulo &#62;]