include::./index.adoc[]

[[v40-10-0]]
=== Mateus, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-10-1]]

^<<v40-10-1,1>>^ E, CHAMANDO os seus doze discípulos, deu-lhes poder sobre os espíritos imundos, para os expulsarem, e para curarem toda a enfermidade e todo o mal.

[[v40-10-2]]

^<<v40-10-2,2>>^ Ora os nomes dos doze apóstolos são estes: O primeiro, Simão, chamado Pedro, e André, seu irmão; Tiago, filho  de Zebedeu, e João, seu irmão;

[[v40-10-3]]

^<<v40-10-3,3>>^ Filipe e Bartolomeu; Tomé e Mateus, o publicano; Tiago, filho  de Alfeu, e Lebeu, apelidado Tadeu;

[[v40-10-4]]

^<<v40-10-4,4>>^ Simão Cananita, e Judas Iscariotes, aquele que o traiu.

[[v40-10-5]]

^<<v40-10-5,5>>^ Jesus enviou estes doze, e lhes ordenou, dizendo: Não ireis pelo caminho das gentes, nem entrareis em cidade de samaritanos;

[[v40-10-6]]

^<<v40-10-6,6>>^ Mas ide antes às ovelhas perdidas da casa d’Israel;

[[v40-10-7]]

^<<v40-10-7,7>>^ E, indo, pregai, dizendo: É chegado o reino dos céus.

[[v40-10-8]]

^<<v40-10-8,8>>^ Curai os enfermos, limpai os leprosos, ressuscitai os mortos, expulsai os demônios: de graça recebestes, de graça dai.

[[v40-10-9]]

^<<v40-10-9,9>>^ Não possuais ouro, nem prata, nem cobre, em vossos cintos;

[[v40-10-10]]

^<<v40-10-10,10>>^ Nem alforjes para o caminho, nem duas túnicas, nem alparcas, nem bordão; porque digno é o operário do seu alimento.

[[v40-10-11]]

^<<v40-10-11,11>>^ E, em qualquer cidade ou aldeia em que entrardes, procurai saber quem nela seja digno, e hospedai-vos aí até que vos retireis.

[[v40-10-12]]

^<<v40-10-12,12>>^ E, quando entrardes nalguma casa, saudai-a;

[[v40-10-13]]

^<<v40-10-13,13>>^ E, se a casa for digna, desça sobre ela a vossa paz; mas, se não for digna, torne para vós a vossa paz.

[[v40-10-14]]

^<<v40-10-14,14>>^ E, se ninguém vos receber, nem escutar as vossas palavras, saindo daquela casa ou cidade, sacudi o pó dos vossos pés.

[[v40-10-15]]

^<<v40-10-15,15>>^ Em verdade vos digo que, no dia do juízo, haverá menos rigor para o país de Sodoma e Gomorra do que para aquela cidade.

[[v40-10-16]]

^<<v40-10-16,16>>^ Eis que vos envio como ovelhas ao meio de lobos; portanto sede prudentes como as serpentes e símplices como as pombas.

[[v40-10-17]]

^<<v40-10-17,17>>^ Acautelai-vos, porém, dos homens; porque eles vos entregarão aos sinédrios, e vos açoitarão nas suas sinagogas;

[[v40-10-18]]

^<<v40-10-18,18>>^ E sereis até conduzidos à presença dos governadores e dos reis por causa de mim, para lhes servir  de testemunho a eles e aos gentios.

[[v40-10-19]]

^<<v40-10-19,19>>^ Mas, quando vos entregarem, não vos dê cuidado como, ou o que haveis de falar, porque naquela mesma  hora vos será ministrado o que haveis de dizer.

[[v40-10-20]]

^<<v40-10-20,20>>^ Porque não sois vós quem falará, mas o Espírito de vosso Pai é que fala em vós.

[[v40-10-21]]

^<<v40-10-21,21>>^ E o irmão entregará à morte o irmão, e o pai o filho; e os filhos se levantarão contra os pais, e os matarão.

[[v40-10-22]]

^<<v40-10-22,22>>^ E odiados de todos sereis por causa do meu nome: mas aquele que perseverar até ao fim será salvo.

[[v40-10-23]]

^<<v40-10-23,23>>^ Quando pois vos perseguirem nesta cidade, fugi para outra; porque em verdade vos digo que não acabareis de percorrer  as cidades d’Israel sem que venha o Filho do homem.

[[v40-10-24]]

^<<v40-10-24,24>>^ Não é o discípulo mais do que o mestre, nem o servo mais do que o seu senhor.

[[v40-10-25]]

^<<v40-10-25,25>>^ Basta ao discípulo ser como seu mestre, e ao servo como seu senhor. Se chamaram Belzebu ao pai de família, quanto mais aos seus domésticos?

[[v40-10-26]]

^<<v40-10-26,26>>^ Portanto, não os temais; porque nada há encoberto que não haja de revelar-se, nem oculto que não haja de saber-se.

[[v40-10-27]]

^<<v40-10-27,27>>^ O que vos digo em trevas dizei-o em luz; e o que escutais ao ouvido pregai- o  sobre os telhados.

[[v40-10-28]]

^<<v40-10-28,28>>^ E não temais os que matam o corpo, e não podem matar a alma; temei antes aquele que pode fazer perecer no inferno a alma e o corpo.

[[v40-10-29]]

^<<v40-10-29,29>>^ Não se vendem dois passarinhos por um ceitil? e nenhum deles cairá em terra sem a vontade de  vosso Pai.

[[v40-10-30]]

^<<v40-10-30,30>>^ E até mesmo os cabelos da vossa cabeça estão todos contados.

[[v40-10-31]]

^<<v40-10-31,31>>^ Não temais pois: mais valeis vós do que muitos passarinhos.

[[v40-10-32]]

^<<v40-10-32,32>>^ Portanto, qualquer que me confessar diante dos homens, eu o confessarei diante de meu Pai, que está  nos céus.

[[v40-10-33]]

^<<v40-10-33,33>>^ Mas qualquer que me negar diante dos homens, eu o negarei também diante de meu Pai, que está  nos céus.

[[v40-10-34]]

^<<v40-10-34,34>>^ Não cuideis que vim trazer a paz à terra; não vim trazer paz, mas espada;

[[v40-10-35]]

^<<v40-10-35,35>>^ Porque eu vim pôr em dissensão o homem contra seu pai, e a filha contra sua mãe, e a nora contra sua sogra;

[[v40-10-36]]

^<<v40-10-36,36>>^ E assim os inimigos do homem serão os seus familiares.

[[v40-10-37]]

^<<v40-10-37,37>>^ Quem ama o pai ou a mãe mais do que a mim não é digno de mim; e quem ama o filho ou a filha mais do que a mim não é digno de mim.

[[v40-10-38]]

^<<v40-10-38,38>>^ E quem não toma a sua cruz, e não segue após mim, não é digno de mim.

[[v40-10-39]]

^<<v40-10-39,39>>^ Quem achar a sua vida perdê-la-á; e quem perder a sua vida por amor de mim achá-la-á.

[[v40-10-40]]

^<<v40-10-40,40>>^ Quem vos recebe, a mim me recebe; e quem me recebe a mim, recebe aquele que me enviou.

[[v40-10-41]]

^<<v40-10-41,41>>^ Quem recebe um  profeta em qualidade de profeta, receberá galardão de profeta; e quem recebe um  justo em qualidade de justo, receberá galardão de justo.

[[v40-10-42]]

^<<v40-10-42,42>>^ E qualquer que tiver dado só que seja um copo d’ água  fria a um destes pequenos, em nome de discípulo, em verdade vos digo que de modo algum perderá o seu galardão.

'''

xref:040-mateus/040-mateus-009.adoc#v40-9-0[&#60; Capítulo Anterior] | <<v40-10-0,Topo>> | xref:040-mateus/040-mateus-011.adoc#v40-11-0[Próximo Capítulo &#62;]