include::./index.adoc[]

[[v40-23-0]]
=== Mateus, 23
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-23-1]]

^<<v40-23-1,1>>^ ENTÃO falou Jesus à multidão, e aos seus discípulos,

[[v40-23-2]]

^<<v40-23-2,2>>^ Dizendo: Na cadeira de Moisés, estão assentados os escribas e fariseus.

[[v40-23-3]]

^<<v40-23-3,3>>^ Observai, pois, e praticai tudo o que vos disserem; mas não procedais em conformidade com as suas obras, porque dizem e não praticam;

[[v40-23-4]]

^<<v40-23-4,4>>^ Pois atam fardos pesados e difíceis de suportar, e os põem aos ombros dos homens; eles, porém, nem com o dedo querem movê-los;

[[v40-23-5]]

^<<v40-23-5,5>>^ E fazem todas as obras a fim de serem vistos pelos homens; pois trazem largos filactérios, e alargam as franjas dos seus vestidos,

[[v40-23-6]]

^<<v40-23-6,6>>^ E amam os primeiros lugares nas ceias e as primeiras cadeiras nas sinagogas,

[[v40-23-7]]

^<<v40-23-7,7>>^ E as saudações, nas praças, e o serem  chamados pelos homens — Rabi, Rabi.

[[v40-23-8]]

^<<v40-23-8,8>>^ Vós, porém, não queirais ser chamados Rabi, porque um só é o vosso Mestre a saber , o Cristo, e todos vós sois irmãos.

[[v40-23-9]]

^<<v40-23-9,9>>^ E a ninguém na terra chameis vosso pai, porque um só é o vosso Pai, o qual está  nos céus.

[[v40-23-10]]

^<<v40-23-10,10>>^ Nem vos chameis mestres, porque um só é o vosso Mestre, que é  o Cristo.

[[v40-23-11]]

^<<v40-23-11,11>>^ Porém o maior dentre vós será vosso servo.

[[v40-23-12]]

^<<v40-23-12,12>>^ E o que a si mesmo se exaltar será humilhado; e o que a si mesmo se humilhar será exaltado.

[[v40-23-13]]

^<<v40-23-13,13>>^ Mas ai de vós, escribas e fariseus, hipócritas! pois que fechais aos homens o reino dos céus; e nem vós entrais nem deixais entrar aos que estão entrando.

[[v40-23-14]]

^<<v40-23-14,14>>^ Ai de vós, escribas e fariseus, hipócritas! pois que devorais as casas das viúvas, sob pretexto de prolongadas orações; por isso sofrereis mais rigoroso juízo.

[[v40-23-15]]

^<<v40-23-15,15>>^ Ai de vós, escribas e fariseus, hipócritas! pois que percorreis o mar e a terra para fazer um prosélito; e, depois de o terdes feito, o fazeis filho do inferno duas vezes mais do que vós.

[[v40-23-16]]

^<<v40-23-16,16>>^ Ai de vós, condutores cegos! pois que dizeis: Qualquer que jurar pelo templo, isso nada é; mas o que jurar pelo ouro do templo, esse é devedor.

[[v40-23-17]]

^<<v40-23-17,17>>^ Insensatos e cegos! Pois qual é maior: o ouro, ou o templo, que santifica o ouro?

[[v40-23-18]]

^<<v40-23-18,18>>^ E aquele que jurar pelo altar isso  nada é; mas aquele que jurar pela oferta que está sobre o altar, esse é devedor.

[[v40-23-19]]

^<<v40-23-19,19>>^ Insensatos e cegos! Pois qual é maior: a oferta, ou o altar, que santifica a oferta?

[[v40-23-20]]

^<<v40-23-20,20>>^ Portanto, o que jurar pelo altar jura por ele e por tudo o que sobre ele está :

[[v40-23-21]]

^<<v40-23-21,21>>^ E o que jurar pelo templo jura por ele e por aquele que nele habita;

[[v40-23-22]]

^<<v40-23-22,22>>^ E o que jurar pelo céu jura pelo trono de Deus e por aquele que está assentado nele.

[[v40-23-23]]

^<<v40-23-23,23>>^ Ai de vós, escribas e fariseus, hipócritas! pois que dizimais a hortelã, o endro e o cominho, e desprezais o mais importante da lei, o juízo, a misericórdia e a fé; deveis, porém, fazer estas coisas, e não omitir aquelas.

[[v40-23-24]]

^<<v40-23-24,24>>^ Condutores cegos! que coais um mosquito e engolis um camelo.

[[v40-23-25]]

^<<v40-23-25,25>>^ Ai de vós, escribas e fariseus, hipócritas! pois que limpais o exterior do copo e do prato, mas o interior está cheio de rapina e de iniquidade.

[[v40-23-26]]

^<<v40-23-26,26>>^ Fariseu cego! limpa primeiro o interior do copo e do prato, para que também o exterior fique limpo.

[[v40-23-27]]

^<<v40-23-27,27>>^ Ai de vós, escribas e fariseus, hipócritas! pois que sois semelhantes aos sepulcros caiados, que por fora realmente parecem formosos, mas interiormente estão cheios de ossos de mortos e de toda a imundícia.

[[v40-23-28]]

^<<v40-23-28,28>>^ Assim também vós exteriormente pareceis justos aos homens, mas interiormente estais cheios de hipocrisia e de iniquidade.

[[v40-23-29]]

^<<v40-23-29,29>>^ Ai de vós, escribas e fariseus, hipócritas! pois que edificais os sepulcros dos profetas e adornais os monumentos dos justos.

[[v40-23-30]]

^<<v40-23-30,30>>^ E dizeis: Se existíssemos no tempo de nossos pais, nunca nos associaríamos com eles para derramar  o sangue dos profetas.

[[v40-23-31]]

^<<v40-23-31,31>>^ Assim, vós mesmos testificais que sois filhos dos que mataram os profetas.

[[v40-23-32]]

^<<v40-23-32,32>>^ Enchei vós pois a medida de vossos pais.

[[v40-23-33]]

^<<v40-23-33,33>>^ Serpentes, raça de víboras! como escapareis da condenação do inferno?

[[v40-23-34]]

^<<v40-23-34,34>>^ Portanto, eis que eu vos envio profetas, sábios e escribas; e a uns  deles matareis e crucificareis; e a outros  deles açoitareis nas vossas sinagogas e os perseguireis de cidade em cidade;

[[v40-23-35]]

^<<v40-23-35,35>>^ Para que sobre vós caia todo o sangue justo, que foi derramado sobre a terra, desde o sangue de Abel, o justo, até ao sangue de Zacarias, filho de Baraquias, que matastes entre o santuário e o altar.

[[v40-23-36]]

^<<v40-23-36,36>>^ Em verdade vos digo que todas estas coisas  hão de vir sobre esta geração.

[[v40-23-37]]

^<<v40-23-37,37>>^ Jerusalém, Jerusalém, que matas os profetas, e apedrejas os que te são enviados! quantas vezes quis eu ajuntar os teus filhos, como a galinha ajunta os seus pintos debaixo das asas, e tu não quiseste!

[[v40-23-38]]

^<<v40-23-38,38>>^ Eis que a vossa casa vai ficar-vos deserta;

[[v40-23-39]]

^<<v40-23-39,39>>^ Porque eu vos digo que desde agora me não vereis mais , até que digais: Bendito o que vem em nome do Senhor.

'''

xref:040-mateus/040-mateus-022.adoc#v40-22-0[&#60; Capítulo Anterior] | <<v40-23-0,Topo>> | xref:040-mateus/040-mateus-024.adoc#v40-24-0[Próximo Capítulo &#62;]