include::./index.adoc[]

[[v40-19-0]]
=== Mateus, 19
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-19-1]]

^<<v40-19-1,1>>^ E ACONTECEU que , concluindo Jesus estes discursos, saiu da Galileia, e dirigiu-se aos confins da Judeia, além do Jordão.

[[v40-19-2]]

^<<v40-19-2,2>>^ E seguiram-no muitas gentes e curou-as ali.

[[v40-19-3]]

^<<v40-19-3,3>>^ Então chegaram ao pé dele os fariseus, tentando-o, e dizendo-lhe: É lícito ao homem repudiar sua mulher por qualquer motivo?

[[v40-19-4]]

^<<v40-19-4,4>>^ Ele, porém, respondendo, disse-lhes: Não tendes lido que aquele que os  fez no princípio macho e fêmea os fez,

[[v40-19-5]]

^<<v40-19-5,5>>^ E disse: Portanto deixará o homem pai e mãe, e se unirá a sua mulher, e serão dois numa só carne?

[[v40-19-6]]

^<<v40-19-6,6>>^ Assim não são mais dois, mas uma só carne. Portanto o que Deus ajuntou não o separe o homem.

[[v40-19-7]]

^<<v40-19-7,7>>^ Disseram-lhe eles: Então por que mandou Moisés dar-lhe carta de divórcio, e repudiá-la?

[[v40-19-8]]

^<<v40-19-8,8>>^ Disse-lhes ele: Moisés por causa da dureza dos vossos corações vos permitiu repudiar vossas mulheres; mas ao princípio não foi assim.

[[v40-19-9]]

^<<v40-19-9,9>>^ Eu vos digo, porém, que qualquer que repudiar sua mulher, não sendo por causa de prostituição, e casar com outra, comete adultério; e o que casar com a repudiada também  comete adultério.

[[v40-19-10]]

^<<v40-19-10,10>>^ Disseram-lhe seus discípulos: Se assim é a condição do homem relativamente à mulher, não convém casar.

[[v40-19-11]]

^<<v40-19-11,11>>^ Ele, porém, lhes disse: Nem todos podem receber esta palavra, mas só aqueles  a quem foi concedido.

[[v40-19-12]]

^<<v40-19-12,12>>^ Porque há eunucos que assim nasceram do ventre da mãe; e há eunucos que foram castrados pelos homens; e há eunucos que se castraram a si mesmos por causa do reino dos céus. Quem pode receber isto, receba-o.

[[v40-19-13]]

^<<v40-19-13,13>>^ Trouxeram-lhe então alguns  meninos, para que sobre eles pusesse as mãos, e orasse; mas os discípulos os repreendiam.

[[v40-19-14]]

^<<v40-19-14,14>>^ Jesus, porém, disse: Deixai os meninos, e não os estorveis de vir a mim; porque dos tais é o reino dos céus.

[[v40-19-15]]

^<<v40-19-15,15>>^ E, tendo-lhes imposto as mãos, partiu dali.

[[v40-19-16]]

^<<v40-19-16,16>>^ E eis que aproximando-se dele um mancebo, disse-lhe: Bom Mestre, que bem farei, para conseguir a vida eterna?

[[v40-19-17]]

^<<v40-19-17,17>>^ E ele disse-lhe: Por que me chamas bom? Não há  bom senão um só que é Deus.  Se queres, porém, entrar na vida, guarda os mandamentos.

[[v40-19-18]]

^<<v40-19-18,18>>^ Disse-lhe ele: Quais? E Jesus disse: Não matarás, não cometerás adultério, não furtarás, não dirás falso testemunho;

[[v40-19-19]]

^<<v40-19-19,19>>^ Honra teu pai e tua mãe, e amarás o teu próximo como a ti mesmo.

[[v40-19-20]]

^<<v40-19-20,20>>^ Disse-lhe o mancebo: Tudo isso tenho guardado desde a minha mocidade; que me falta ainda?

[[v40-19-21]]

^<<v40-19-21,21>>^ Disse-lhe Jesus: Se queres ser perfeito, vai, vende tudo o que tens e dá-o aos pobres, e terás um  tesouro no céu; e vem, e  segue-me.

[[v40-19-22]]

^<<v40-19-22,22>>^ E o mancebo, ouvindo esta palavra, retirou-se triste, porque possuía muitas propriedades.

[[v40-19-23]]

^<<v40-19-23,23>>^ Disse então Jesus aos seus discípulos: Em verdade vos digo que é difícil entrar um rico no reino dos céus.

[[v40-19-24]]

^<<v40-19-24,24>>^ E outra vez vos digo que é mais fácil passar um camelo pelo fundo duma agulha do que entrar um rico no reino de Deus.

[[v40-19-25]]

^<<v40-19-25,25>>^ Os seus discípulos, ouvindo isto , admiraram-se muito, dizendo: Quem poderá pois salvar-se?

[[v40-19-26]]

^<<v40-19-26,26>>^ E Jesus, olhando para eles , disse-lhes: Aos homens é isso impossível, mas a Deus tudo é possível.

[[v40-19-27]]

^<<v40-19-27,27>>^ Então Pedro, tomando a palavra, disse-lhe: Eis que nós deixamos tudo, e te seguimos; que receberemos?

[[v40-19-28]]

^<<v40-19-28,28>>^ E Jesus disse-lhes: Em verdade vos digo que vós, que me seguistes, quando, na regeneração, o Filho do homem se assentar no trono da sua glória, também vos assentareis sobre doze tronos, para julgar as doze tribos d’Israel.

[[v40-19-29]]

^<<v40-19-29,29>>^ E todo aquele que tiver deixado casas, ou irmãos, ou irmãs, ou pai, ou mãe, ou mulher, ou filhos, ou terras, por amor do meu nome, receberá cem vezes tanto, e herdará a vida eterna.

[[v40-19-30]]

^<<v40-19-30,30>>^ Porém muitos primeiros serão os derradeiros, e muitos  derradeiros serão  os primeiros.

'''

xref:040-mateus/040-mateus-018.adoc#v40-18-0[&#60; Capítulo Anterior] | <<v40-19-0,Topo>> | xref:040-mateus/040-mateus-020.adoc#v40-20-0[Próximo Capítulo &#62;]