include::./index.adoc[]

[[v40-16-0]]
=== Mateus, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-16-1]]

^<<v40-16-1,1>>^ E, CHEGANDO-SE os fariseus e os saduceus, para o tentarem, pediram-lhe que lhes mostrasse algum sinal do céu.

[[v40-16-2]]

^<<v40-16-2,2>>^ Mas ele, respondendo, disse-lhes: Quando é chegada a tarde, dizeis: Haverá  bom tempo, porque o céu está rubro.

[[v40-16-3]]

^<<v40-16-3,3>>^ E pela manhã: Hoje haverá  tempestade, porque o céu está de  um vermelho sombrio. Hipócritas, sabeis diferençar a face do céu, e não conheceis os sinais dos tempos?

[[v40-16-4]]

^<<v40-16-4,4>>^ Uma geração má e adúltera pede um sinal, e nenhum sinal lhe será dado, senão o sinal do profeta Jonas. E, deixando-os, retirou-se.

[[v40-16-5]]

^<<v40-16-5,5>>^ E, passando seus discípulos para a outra banda, tinham-se esquecido de fornecer-se de pão.

[[v40-16-6]]

^<<v40-16-6,6>>^ E Jesus disse-lhes: Adverti, e acautelai-vos do fermento dos fariseus e saduceus.

[[v40-16-7]]

^<<v40-16-7,7>>^ E eles arrazoavam entre si, dizendo: É porque não nos fornecemos de pão.

[[v40-16-8]]

^<<v40-16-8,8>>^ E Jesus, percebendo isso, disse: Por que arrazoais entre vós, homens  de pouca fé, sobre o não vos terdes fornecido de pão?

[[v40-16-9]]

^<<v40-16-9,9>>^ Não compreendeis ainda, nem vos lembrais dos cinco pães para cinco mil homens , e de quantas alcofas levantastes?

[[v40-16-10]]

^<<v40-16-10,10>>^ Nem dos sete pães para quatro mil e de quantos cestos levantastes?

[[v40-16-11]]

^<<v40-16-11,11>>^ Como não compreendestes que não vos falei a respeito do pão, mas que vos guardásseis do fermento dos fariseus e saduceus?

[[v40-16-12]]

^<<v40-16-12,12>>^ Então compreenderam que não dissera que se guardassem do fermento do pão, mas da doutrina dos fariseus.

[[v40-16-13]]

^<<v40-16-13,13>>^ E, chegando Jesus às partes de Cesareia de Filipo, interrogou os seus discípulos, dizendo: Quem dizem os homens ser o Filho do homem?

[[v40-16-14]]

^<<v40-16-14,14>>^ E eles disseram: Uns João Batista, outros Elias, e outros Jeremias ou um dos profetas.

[[v40-16-15]]

^<<v40-16-15,15>>^ Disse-lhes ele: E vós, quem dizeis que eu sou?

[[v40-16-16]]

^<<v40-16-16,16>>^ E Simão Pedro, respondendo, disse: Tu és o Cristo, o Filho de Deus vivo.

[[v40-16-17]]

^<<v40-16-17,17>>^ E Jesus, respondendo, disse-lhe: Bem-aventurado és tu, Simão Barjonas, porque to não revelou a carne e o sangue, mas meu Pai, que está  nos céus.

[[v40-16-18]]

^<<v40-16-18,18>>^ Pois também eu te digo que tu és Pedro, e sobre esta pedra edificarei a minha igreja, e as portas do inferno não prevalecerão contra ela;

[[v40-16-19]]

^<<v40-16-19,19>>^ E eu te darei as chaves do reino dos céus; e tudo o que ligares na terra será ligado nos céus, e tudo o que desligares na terra será desligado nos céus.

[[v40-16-20]]

^<<v40-16-20,20>>^ Então mandou aos seus discípulos que a ninguém dissessem que ele era o Cristo.

[[v40-16-21]]

^<<v40-16-21,21>>^ Desde então começou Jesus a mostrar aos seus discípulos que convinha ir a Jerusalém, e padecer muito dos anciãos, e dos principais dos sacerdotes, e dos escribas, e ser morto e ressuscitar ao terceiro dia.

[[v40-16-22]]

^<<v40-16-22,22>>^ E Pedro, tomando-o de parte, começou a repreendê-lo, dizendo: Senhor, tem  compaixão de ti; de modo nenhum te acontecerá isso.

[[v40-16-23]]

^<<v40-16-23,23>>^ Ele, porém, voltando-se, disse a Pedro: Para trás de mim Satanás, que  me serves de escândalo; porque não compreendes as coisas  que são  de Deus, mas só  as que são  dos homens.

[[v40-16-24]]

^<<v40-16-24,24>>^ Então disse Jesus aos seus discípulos: Se alguém quiser vir após mim, renuncie-se a si mesmo, tome sobre si a sua cruz, e siga-me;

[[v40-16-25]]

^<<v40-16-25,25>>^ Porque aquele que quiser salvar a sua vida, perdê-la-á, e quem perder a sua vida por amor de mim, achá-la-á.

[[v40-16-26]]

^<<v40-16-26,26>>^ Pois que aproveita ao homem ganhar o mundo inteiro, se perder a sua alma? ou que dará o homem em recompensa da sua alma?

[[v40-16-27]]

^<<v40-16-27,27>>^ Porque o Filho do homem virá na glória de seu Pai, com os seus anjos; e então dará a cada um segundo as suas obras.

[[v40-16-28]]

^<<v40-16-28,28>>^ Em verdade vos digo que  alguns há, dos que aqui estão, que não provarão a morte até que vejam vir o Filho do homem no seu reino.

'''

xref:040-mateus/040-mateus-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-mateus/040-mateus-017.adoc#v40-17-0[Próximo Capítulo &#62;]