include::./index.adoc[]

[[v40-17-0]]
=== Mateus, 17
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-17-1]]

^<<v40-17-1,1>>^ SEIS dias depois, tomou Jesus consigo a Pedro, e a Tiago, e a João, seu irmão, e os conduziu em particular a um alto monte.

[[v40-17-2]]

^<<v40-17-2,2>>^ E transfigurou-se diante deles; e o seu rosto resplandeceu como o sol, e os seus vestidos se tornaram brancos como a luz.

[[v40-17-3]]

^<<v40-17-3,3>>^ E eis que lhes apareceram Moisés e Elias, falando com ele.

[[v40-17-4]]

^<<v40-17-4,4>>^ E Pedro, tomando a palavra, disse a Jesus: Senhor, bom é estarmos aqui; se queres, façamos aqui três tabernáculos, um para ti, um para Moisés, e um para Elias.

[[v40-17-5]]

^<<v40-17-5,5>>^ E, estando ele ainda a falar, eis que uma nuvem luminosa os cobriu. E da nuvem saiu uma voz que dizia: Este é o meu amado Filho, em quem me comprazo: escutai-o.

[[v40-17-6]]

^<<v40-17-6,6>>^ E os discípulos, ouvindo isto , caíram sobre seus rostos, e tiveram grande medo.

[[v40-17-7]]

^<<v40-17-7,7>>^ E aproximando-se Jesus, tocou-lhes, e disse: Levantai-vos; e não tenhais medo.

[[v40-17-8]]

^<<v40-17-8,8>>^ E, erguendo eles os olhos, ninguém viram senão unicamente a Jesus.

[[v40-17-9]]

^<<v40-17-9,9>>^ E, descendo eles do monte, Jesus lhes ordenou, dizendo: A ninguém conteis a visão, até que o Filho do homem seja ressuscitado dos mortos.

[[v40-17-10]]

^<<v40-17-10,10>>^ E os seus discípulos o interrogaram, dizendo: Por que dizem então os escribas que é mister que Elias venha primeiro?

[[v40-17-11]]

^<<v40-17-11,11>>^ E Jesus, respondendo, disse-lhes: Em verdade Elias virá primeiro, e restaurará todas as coisas ;

[[v40-17-12]]

^<<v40-17-12,12>>^ Mas digo-vos que Elias já veio, e não o conheceram, mas fizeram-lhe tudo o que quiseram. Assim farão eles também padecer o Filho do Homem.

[[v40-17-13]]

^<<v40-17-13,13>>^ Então entenderam os discípulos que lhes falara de João Batista.

[[v40-17-14]]

^<<v40-17-14,14>>^ E, quando chegaram à multidão, aproximou-se-lhe um homem, pondo-se de joelhos diante dele, e dizendo:

[[v40-17-15]]

^<<v40-17-15,15>>^ Senhor, tem misericórdia de meu filho, que é lunático e sofre muito; pois muitas vezes cai no fogo e muitas vezes na água;

[[v40-17-16]]

^<<v40-17-16,16>>^ E trouxe-o aos teus discípulos; e, não puderam curá-lo.

[[v40-17-17]]

^<<v40-17-17,17>>^ E Jesus, respondendo, disse: Ó geração incrédula e perversa! até quando estarei eu convosco, e até quando vos sofrerei? Trazei-mo aqui.

[[v40-17-18]]

^<<v40-17-18,18>>^ E repreendeu Jesus o demônio, que saiu dele, e desde aquela hora o menino sarou.

[[v40-17-19]]

^<<v40-17-19,19>>^ Então os discípulos, aproximando-se de Jesus em particular, disseram: Porque não pudemos nós expulsá-lo?

[[v40-17-20]]

^<<v40-17-20,20>>^ E Jesus lhes disse: Por causa da vossa pouca fé; porque em verdade vos digo que, se tiverdes fé como um grão de mostarda, direis a este monte: Passa daqui para acolá — e há de passar; e nada vos será impossível.

[[v40-17-21]]

^<<v40-17-21,21>>^ Mas esta casta de demônios  não se expulsa senão pela oração e pelo jejum.

[[v40-17-22]]

^<<v40-17-22,22>>^ Ora, achando-se eles na Galileia, disse-lhes Jesus: O Filho do homem será entregue nas mãos dos homens;

[[v40-17-23]]

^<<v40-17-23,23>>^ E matá-lo-ão, e ao terceiro dia ressuscitará. E eles se entristeceram muito.

[[v40-17-24]]

^<<v40-17-24,24>>^ E, chegando eles a Capernaum, aproximaram-se de Pedro os que cobravam as didracmas, e disseram: O vosso mestre não paga as didracmas?

[[v40-17-25]]

^<<v40-17-25,25>>^ Disse ele: Sim. E, entrando em casa, Jesus se lhe antecipou, dizendo: Que te parece, Simão? De quem cobram os reis da terra os tributos, ou o censo? Dos seus filhos, ou dos alheios?

[[v40-17-26]]

^<<v40-17-26,26>>^ Disse-lhe Pedro: Dos alheios. Disse-lhe Jesus: Logo, estão livres os filhos;

[[v40-17-27]]

^<<v40-17-27,27>>^ Mas, para que os não escandalizemos, vai ao mar, lança o anzol, tira o primeiro peixe que subir, e, abrindo-lhe a boca, encontrarás um estáter; toma-o, e dá-o por mim e por ti.

'''

xref:040-mateus/040-mateus-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-mateus/040-mateus-018.adoc#v40-18-0[Próximo Capítulo &#62;]