include::./index.adoc[]

[[v40-25-0]]
=== Mateus, 25
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-25-1]]

^<<v40-25-1,1>>^ ENTÃO o reino dos céus será semelhante a dez virgens que, tomando as suas lâmpadas, saíram ao encontro do esposo.

[[v40-25-2]]

^<<v40-25-2,2>>^ E cinco delas eram prudentes, e cinco loucas.

[[v40-25-3]]

^<<v40-25-3,3>>^ As loucas, tomando as suas lâmpadas, não levaram azeite consigo.

[[v40-25-4]]

^<<v40-25-4,4>>^ Mas as prudentes levaram azeite em suas vasilhas, com as suas lâmpadas.

[[v40-25-5]]

^<<v40-25-5,5>>^ E, tardando o esposo, tosquenejaram todas, e adormeceram,

[[v40-25-6]]

^<<v40-25-6,6>>^ Mas à meia-noite ouviu-se um clamor; aí vem o esposo, saí-lhe ao encontro.

[[v40-25-7]]

^<<v40-25-7,7>>^ Então todas aquelas virgens se levantaram, e prepararam as suas lâmpadas.

[[v40-25-8]]

^<<v40-25-8,8>>^ E as loucas disseram às prudentes: Dai-nos do vosso azeite, porque as nossas lâmpadas se apagam.

[[v40-25-9]]

^<<v40-25-9,9>>^ Mas as prudentes responderam, dizendo: Não  seja caso que nos falte a nós e a vós, ide antes aos que o vendem, e comprai- o  para vós.

[[v40-25-10]]

^<<v40-25-10,10>>^ E, tendo elas ido comprá-lo, chegou o esposo, e as que estavam preparadas entraram com ele para as bodas, e fechou-se a porta.

[[v40-25-11]]

^<<v40-25-11,11>>^ E depois chegaram também as outras virgens, dizendo: Senhor, Senhor, abre-nos.

[[v40-25-12]]

^<<v40-25-12,12>>^ E ele, respondendo, disse: Em verdade vos digo que vos não conheço.

[[v40-25-13]]

^<<v40-25-13,13>>^ Vigiai pois, porque não sabeis o dia nem a hora em que o Filho do homem há de vir.

[[v40-25-14]]

^<<v40-25-14,14>>^ Porque isto é também como um homem que, partindo para fora da terra, chamou os seus servos, e entregou-lhes os seus bens;

[[v40-25-15]]

^<<v40-25-15,15>>^ E a um deu cinco talentos, e a outro dois, e a outro um, a cada um segundo a sua capacidade, e ausentou-se logo para longe.

[[v40-25-16]]

^<<v40-25-16,16>>^ E, tendo ele partido, o que recebera cinco talentos negociou com eles, e granjeou outros cinco talentos.

[[v40-25-17]]

^<<v40-25-17,17>>^ Da mesma sorte, o que recebera  dois, granjeou também outros dois;

[[v40-25-18]]

^<<v40-25-18,18>>^ Mas o que recebera um, foi e cavou na terra e escondeu o dinheiro do seu senhor.

[[v40-25-19]]

^<<v40-25-19,19>>^ E muito tempo depois veio o senhor daqueles servos, e fez contas com eles.

[[v40-25-20]]

^<<v40-25-20,20>>^ Então aproximou-se o que recebera cinco talentos, e trouxe-lhe outros cinco talentos, dizendo: Senhor, entregaste-me cinco talentos; eis aqui outros cinco talentos que granjeei com eles.

[[v40-25-21]]

^<<v40-25-21,21>>^ E o seu senhor lhe disse: Bem está , servo bom e fiel. Sobre o pouco foste fiel, sobre muito te colocarei; entra no gozo do teu senhor.

[[v40-25-22]]

^<<v40-25-22,22>>^ E, chegando também o que tinha recebido dois talentos, disse: Senhor, entregaste-me dois talentos; eis que com eles granjeei outros dois talentos.

[[v40-25-23]]

^<<v40-25-23,23>>^ Disse-lhe o seu senhor: Bem está , bom e fiel servo. Sobre o pouco foste fiel, sobre muito te colocarei; entra no gozo do teu senhor.

[[v40-25-24]]

^<<v40-25-24,24>>^ Mas, chegando também o que recebera um talento disse: Senhor, eu conhecia-te, que és um homem duro, que ceifas onde não semeaste e ajuntas onde não espalhaste;

[[v40-25-25]]

^<<v40-25-25,25>>^ E, atemorizado, escondi na terra o teu talento; aqui tens o que é  teu.

[[v40-25-26]]

^<<v40-25-26,26>>^ Respondendo, porém, o seu senhor, disse-lhe: Mau e negligente servo; sabes que ceifo onde não semeei e ajunto onde não espalhei;

[[v40-25-27]]

^<<v40-25-27,27>>^ Devias então ter dado o meu dinheiro aos banqueiros, e, quando eu viesse, receberia o meu com os juros.

[[v40-25-28]]

^<<v40-25-28,28>>^ Tirai-lhe pois o talento, e dai-o ao que tem os dez talentos.

[[v40-25-29]]

^<<v40-25-29,29>>^ Porque a qualquer que tiver será dado, e terá em abundância; mas ao que não tiver até o que tem ser-lhe-á tirado.

[[v40-25-30]]

^<<v40-25-30,30>>^ Lançai pois o servo inútil nas trevas exteriores; ali haverá pranto e ranger de dentes.

[[v40-25-31]]

^<<v40-25-31,31>>^ E quando o Filho do homem vier em sua glória, e todos os santos anjos com ele, então se assentará no trono da sua glória;

[[v40-25-32]]

^<<v40-25-32,32>>^ E todas as nações serão reunidas diante dele, e apartará uns dos outros, como o pastor aparta dos bodes as ovelhas;

[[v40-25-33]]

^<<v40-25-33,33>>^ E porá as ovelhas à sua direita, mas os bodes à esquerda.

[[v40-25-34]]

^<<v40-25-34,34>>^ Então dirá o Rei aos que estiverem  à sua direita: Vinde, benditos de meu Pai, possuí por herança o reino que vos está preparado desde a fundação do mundo;

[[v40-25-35]]

^<<v40-25-35,35>>^ Porque tive fome, e destes-me de comer; tive sede e destes-me de beber; era estrangeiro, e hospedastes-me;

[[v40-25-36]]

^<<v40-25-36,36>>^ Estava  nu, e vestistes-me; adoeci, e visitastes-me; estive na prisão, e fostes ver-me.

[[v40-25-37]]

^<<v40-25-37,37>>^ Então os justos lhe responderão, dizendo: Senhor, quando te vimos com fome, e te  demos de comer? ou com sede, e te  demos de beber?

[[v40-25-38]]

^<<v40-25-38,38>>^ E quando te vimos estrangeiro, e te  hospedamos? ou nu, e te  vestimos?

[[v40-25-39]]

^<<v40-25-39,39>>^ E quando te vimos enfermo, ou na prisão, e fomos ver-te?

[[v40-25-40]]

^<<v40-25-40,40>>^ E, respondendo o Rei, lhes dirá: Em verdade vos digo que, quando o fizestes a um destes meus pequeninos irmãos, a mim o  fizestes.

[[v40-25-41]]

^<<v40-25-41,41>>^ Então dirá também aos que estiverem  à sua esquerda: Apartai-vos de mim, malditos, para o fogo eterno, preparado para o diabo e seus anjos;

[[v40-25-42]]

^<<v40-25-42,42>>^ Porque tive fome, e não me destes de comer, tive sede, e não me destes de beber;

[[v40-25-43]]

^<<v40-25-43,43>>^ Sendo estrangeiro, não me recolhestes; estando  nu, não me vestistes; e enfermo, e na prisão, não me visitastes.

[[v40-25-44]]

^<<v40-25-44,44>>^ Então eles também lhe responderão, dizendo: Senhor, quando te vimos com fome, ou com sede, ou estrangeiro, ou nu, ou enfermo, ou na prisão, e não te servimos?

[[v40-25-45]]

^<<v40-25-45,45>>^ Então lhes responderá, dizendo: Em verdade vos digo que, quando a um destes pequeninos o  não fizestes não o fizestes a mim.

[[v40-25-46]]

^<<v40-25-46,46>>^ E irão estes para o tormento eterno, mas os justos para a vida eterna.

'''

xref:040-mateus/040-mateus-024.adoc#v40-24-0[&#60; Capítulo Anterior] | <<v40-25-0,Topo>> | xref:040-mateus/040-mateus-026.adoc#v40-26-0[Próximo Capítulo &#62;]