include::./index.adoc[]

[[v40-13-0]]
=== Mateus, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-13-1]]

^<<v40-13-1,1>>^ TENDO Jesus saído de casa naquele dia, estava assentado junto ao mar;

[[v40-13-2]]

^<<v40-13-2,2>>^ E ajuntou-se muita gente ao pé dele, de sorte que, entrando num barco, se assentou; e toda a multidão estava em pé na praia.

[[v40-13-3]]

^<<v40-13-3,3>>^ E falou-lhe de muitas coisas  por parábolas, dizendo: Eis que o semeador saiu a semear.

[[v40-13-4]]

^<<v40-13-4,4>>^ E, quando semeava, uma  parte da semente  caiu ao pé do caminho, e vieram as aves, e comeram-na;

[[v40-13-5]]

^<<v40-13-5,5>>^ E outra parte  caiu em pedregais, onde não havia terra bastante, e logo nasceu, porque não tinha terra funda;

[[v40-13-6]]

^<<v40-13-6,6>>^ Mas, vindo o sol, queimou-se, e secou-se, porque não tinha raiz.

[[v40-13-7]]

^<<v40-13-7,7>>^ E outra caiu entre espinhos, e os espinhos cresceram, e sufocaram-na.

[[v40-13-8]]

^<<v40-13-8,8>>^ E outra caiu em boa terra, e deu fruto: um a cem, outro a sessenta e outro a trinta.

[[v40-13-9]]

^<<v40-13-9,9>>^ Quem tem ouvidos para ouvir, ouça.

[[v40-13-10]]

^<<v40-13-10,10>>^ E, acercando-se dele os discípulos, disseram-lhe: Por que lhes falas por parábolas?

[[v40-13-11]]

^<<v40-13-11,11>>^ Ele, respondendo, disse-lhes: Porque a vós é dado conhecer os mistérios do reino dos céus, mas a eles não lhes é dado;

[[v40-13-12]]

^<<v40-13-12,12>>^ Porque àquele que tem, se dará, e terá em abundância; mas aquele que não tem, até aquilo que tem lhe será tirado.

[[v40-13-13]]

^<<v40-13-13,13>>^ Por isso lhes falo por parábolas; porque eles, vendo, não veem; e, ouvindo, não ouvem nem compreendem.

[[v40-13-14]]

^<<v40-13-14,14>>^ E neles se cumpre a profecia d’Isaías, que diz: Ouvindo, ouvireis, mas não compreendereis, e, vendo, vereis, mas não percebereis.

[[v40-13-15]]

^<<v40-13-15,15>>^ Porque o coração deste povo está endurecido, e ouviram de mau grado com seus ouvidos, e fecharam seus olhos; para que não vejam com os olhos, e ouçam com os ouvidos, e compreendam com o coração, e se convertam, e eu os cure.

[[v40-13-16]]

^<<v40-13-16,16>>^ Mas bem-aventurados os vossos olhos, porque veem, e os vossos ouvidos, porque ouvem.

[[v40-13-17]]

^<<v40-13-17,17>>^ Porque em verdade vos digo que muitos profetas e justos desejaram ver o que vós vedes, e não o  viram; e ouvir o que vós ouvis, e não o  ouviram.

[[v40-13-18]]

^<<v40-13-18,18>>^ Escutai vós, pois, a parábola do semeador.

[[v40-13-19]]

^<<v40-13-19,19>>^ Ouvindo alguém a palavra do reino, e não a entendendo, vem o maligno, e arrebata o que foi semeado no seu coração; este é o que foi semeado ao pé do caminho;

[[v40-13-20]]

^<<v40-13-20,20>>^ Porém o que foi semeado em pedregais é o que ouve a palavra, e logo a recebe com alegria;

[[v40-13-21]]

^<<v40-13-21,21>>^ Mas não tem raiz em si mesmo, antes é de pouca duração; e, chegada a angústia e a perseguição por causa da palavra, logo se ofende;

[[v40-13-22]]

^<<v40-13-22,22>>^ E o que foi semeado entre espinhos é o que ouve a palavra, mas os cuidados deste mundo, e a sedução das riquezas, sufocam a palavra, e fica infrutífera;

[[v40-13-23]]

^<<v40-13-23,23>>^ Mas o que foi semeado em boa terra é o que ouve e compreende a palavra; e dá fruto, e um produz cem, outro sessenta, e outro trinta.

[[v40-13-24]]

^<<v40-13-24,24>>^ Propôs-lhes outra parábola, dizendo: O reino dos céus é semelhante ao homem que semeia boa semente no seu campo;

[[v40-13-25]]

^<<v40-13-25,25>>^ Mas, dormindo os homens, veio o seu inimigo, e semeou o joio no meio do trigo, e retirou-se.

[[v40-13-26]]

^<<v40-13-26,26>>^ E, quando a erva cresceu e frutificou, apareceu também o joio.

[[v40-13-27]]

^<<v40-13-27,27>>^ E os servos do pai de família, indo ter com ele , disseram-lhe: Senhor, não semeaste tu no teu campo boa semente? Por que tem então joio?

[[v40-13-28]]

^<<v40-13-28,28>>^ E ele lhes disse: Um inimigo é quem fez isso. E os servos lhe disseram: Queres pois que vamos arrancá-lo?

[[v40-13-29]]

^<<v40-13-29,29>>^ Porém ele lhes disse: Não; para que ao colher o joio não arranqueis também o trigo com ele.

[[v40-13-30]]

^<<v40-13-30,30>>^ Deixai crescer ambos juntos até à ceifa; e, por ocasião da ceifa, direi aos ceifeiros: Colhei primeiro o joio, e atai-o em molhos para o queimar; mas o trigo ajuntai-o no meu celeiro.

[[v40-13-31]]

^<<v40-13-31,31>>^ Outra parábola lhes propôs, dizendo: O reino dos céus é semelhante ao grão de mostarda que o homem, pegando dele, semeou no seu campo;

[[v40-13-32]]

^<<v40-13-32,32>>^ O qual é realmente a mais pequena de todas as sementes; mas, crescendo, é a maior das plantas, e faz-se uma árvore, de sorte que vêm as aves do céu, e se aninham nos seus ramos.

[[v40-13-33]]

^<<v40-13-33,33>>^ Outra parábola lhes disse: O reino dos céus é semelhante ao fermento que uma mulher toma e introduz em três medidas de farinha, até que tudo esteja levedado.

[[v40-13-34]]

^<<v40-13-34,34>>^ Tudo isto disse Jesus por parábolas à multidão, e nada lhes falava sem parábolas;

[[v40-13-35]]

^<<v40-13-35,35>>^ Para que se cumprisse o que fora dito pelo profeta, que disse: Abrirei em parábolas a minha boca; publicarei coisas  ocultas desde a criação do mundo.

[[v40-13-36]]

^<<v40-13-36,36>>^ Então, tendo despedido a multidão, foi Jesus para casa. E chegaram ao pé dele os seus discípulos, dizendo: Explica-nos a parábola do joio do campo.

[[v40-13-37]]

^<<v40-13-37,37>>^ E ele, respondendo, disse-lhes: O que semeia a boa semente, é o Filho do homem;

[[v40-13-38]]

^<<v40-13-38,38>>^ O campo é o mundo; e a boa semente são os filhos do reino; e o joio são os filhos do maligno;

[[v40-13-39]]

^<<v40-13-39,39>>^ O inimigo, que o semeou, é o diabo; e a ceifa é o fim do mundo; e os ceifeiros são os anjos.

[[v40-13-40]]

^<<v40-13-40,40>>^ Assim como o joio é colhido e queimado no fogo, assim será na consumação deste mundo.

[[v40-13-41]]

^<<v40-13-41,41>>^ Mandará o Filho do homem os seus anjos, e eles colherão do seu reino tudo o que causa escândalo, e os que cometem iniquidade.

[[v40-13-42]]

^<<v40-13-42,42>>^ E lançá-los-ão na fornalha de fogo; ali haverá pranto e ranger de dentes.

[[v40-13-43]]

^<<v40-13-43,43>>^ Então os justos resplandecerão como o sol, no reino de seu Pai. Quem tem ouvidos para ouvir, ouça.

[[v40-13-44]]

^<<v40-13-44,44>>^ Também o reino dos céus é semelhante a um tesouro escondido num  campo que um homem achou e escondeu; e, pelo gozo dele, vai, vende tudo quanto tem, e compra aquele campo.

[[v40-13-45]]

^<<v40-13-45,45>>^ Outrossim o reino dos céus é semelhante ao homem, negociante, que busca boas pérolas;

[[v40-13-46]]

^<<v40-13-46,46>>^ E, encontrando uma pérola de grande valor, foi, vendeu tudo quanto tinha, e comprou-a.

[[v40-13-47]]

^<<v40-13-47,47>>^ Igualmente o reino dos céus é semelhante a uma rede lançada ao mar, e que apanha toda qualidade de peixes.

[[v40-13-48]]

^<<v40-13-48,48>>^ E, estando cheia, a puxam para a praia; e, assentando-se, apanham para os cestos os bons; os ruins, porém, lançam fora.

[[v40-13-49]]

^<<v40-13-49,49>>^ Assim será na consumação dos séculos: virão os anjos, e separarão os maus dentre os justos.

[[v40-13-50]]

^<<v40-13-50,50>>^ E lançá-los-ão na fornalha de fogo: ali haverá pranto e ranger de dentes.

[[v40-13-51]]

^<<v40-13-51,51>>^ E disse-lhes Jesus: Entendestes todas estas coisas ? Disseram-lhe eles: Sim, Senhor.

[[v40-13-52]]

^<<v40-13-52,52>>^ E ele disse-lhes: Por isso, todo o escriba instruído acerca do reino dos céus é semelhante a um pai de família, que tira do seu tesouro coisas  novas e velhas.

[[v40-13-53]]

^<<v40-13-53,53>>^ E aconteceu que Jesus, concluindo estas parábolas, se retirou dali.

[[v40-13-54]]

^<<v40-13-54,54>>^ E, chegando à sua pátria, ensinava-os na sinagoga deles, de sorte que se maravilhavam, e diziam: Donde veio  a este a sabedoria, e estas maravilhas?

[[v40-13-55]]

^<<v40-13-55,55>>^ Não é este o filho do carpinteiro? e não se chama sua mãe Maria, e seus irmãos Tiago, e José, e Simão, e Judas?

[[v40-13-56]]

^<<v40-13-56,56>>^ E não estão entre nós todas as suas irmãs? Donde lhe veio  pois tudo isto?

[[v40-13-57]]

^<<v40-13-57,57>>^ E escandalizavam-se nele. Jesus, porém, lhes disse: Não há profeta sem honra, a não ser na sua pátria e na sua casa.

[[v40-13-58]]

^<<v40-13-58,58>>^ E não fez ali muitas maravilhas, por causa da incredulidade deles.

'''

xref:040-mateus/040-mateus-012.adoc#v40-12-0[&#60; Capítulo Anterior] | <<v40-13-0,Topo>> | xref:040-mateus/040-mateus-014.adoc#v40-14-0[Próximo Capítulo &#62;]