include::./index.adoc[]

[[v40-26-0]]
=== Mateus, 26
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-26-1]]

^<<v40-26-1,1>>^ E ACONTECEU que, quando Jesus concluiu todos estes discursos, disse aos seus discípulos:

[[v40-26-2]]

^<<v40-26-2,2>>^ Bem sabeis que daqui a dois dias é a páscoa; e o Filho do homem será entregue para ser crucificado.

[[v40-26-3]]

^<<v40-26-3,3>>^ Depois os príncipes dos sacerdotes, e os escribas, e os anciãos do povo reuniram-se na sala do sumo sacerdote, o qual se chamava Caifás,

[[v40-26-4]]

^<<v40-26-4,4>>^ E consultaram-se mutuamente para prenderem Jesus com dolo e o matarem.

[[v40-26-5]]

^<<v40-26-5,5>>^ Mas diziam: Não durante a festa, para que não haja alvoroço entre o povo.

[[v40-26-6]]

^<<v40-26-6,6>>^ E, estando Jesus em Betânia, em casa de Simão, o leproso,

[[v40-26-7]]

^<<v40-26-7,7>>^ Aproximou-se dele uma mulher com um vaso de alabastro, com unguento de grande valor, e derramou-lho sobre a cabeça, quando ele estava assentado à mesa.

[[v40-26-8]]

^<<v40-26-8,8>>^ E os seus discípulos, vendo isto , indignaram-se, dizendo: Por que este desperdício?

[[v40-26-9]]

^<<v40-26-9,9>>^ Pois este unguento podia vender-se por grande preço, e dar-se o dinheiro aos pobres.

[[v40-26-10]]

^<<v40-26-10,10>>^ Jesus, porém, conhecendo isto , disse-lhes: Por que afligis esta mulher? pois praticou uma  boa ação para comigo.

[[v40-26-11]]

^<<v40-26-11,11>>^ Porquanto sempre tendes convosco os pobres, mas a mim não me haveis de ter sempre.

[[v40-26-12]]

^<<v40-26-12,12>>^ Ora, derramando ela este unguento sobre o meu corpo, fê-lo preparando-me para o meu enterramento.

[[v40-26-13]]

^<<v40-26-13,13>>^ Em verdade vos digo que, onde quer que este Evangelho for pregado, em todo o mundo, também será referido o que ela fez para memória sua.

[[v40-26-14]]

^<<v40-26-14,14>>^ Então um dos doze, chamado Judas Iscariotes, foi ter com os príncipes dos sacerdotes,

[[v40-26-15]]

^<<v40-26-15,15>>^ E disse: Que me quereis dar e eu vo-lo entregarei? E eles lhe pesaram trinta moedas  de prata,

[[v40-26-16]]

^<<v40-26-16,16>>^ E desde então buscava oportunidade para o entregar.

[[v40-26-17]]

^<<v40-26-17,17>>^ E, no primeiro dia da festa  dos pães asmos, chegaram os discípulos junto de Jesus, dizendo: Onde queres que façamos os preparativos para comeres a páscoa?

[[v40-26-18]]

^<<v40-26-18,18>>^ E ele disse: Ide à cidade a um  certo homem, e dizei-lhe: O Mestre diz: O meu tempo está próximo; em tua casa celebrarei a páscoa com os meus discípulos.

[[v40-26-19]]

^<<v40-26-19,19>>^ E os discípulos fizeram como Jesus lhes ordenara, e prepararam a páscoa.

[[v40-26-20]]

^<<v40-26-20,20>>^ E, chegada a tarde, assentou-se à mesa  com os doze.

[[v40-26-21]]

^<<v40-26-21,21>>^ E, comendo eles, disse: Em verdade vos digo que um de vós me há de trair.

[[v40-26-22]]

^<<v40-26-22,22>>^ E eles, entristecendo-se muito, começaram cada um a dizer-lhe: Porventura  sou eu, Senhor?

[[v40-26-23]]

^<<v40-26-23,23>>^ E ele, respondendo, disse: O que mete comigo a mão no prato, esse me há de trair.

[[v40-26-24]]

^<<v40-26-24,24>>^ Em verdade o Filho do homem vai, como acerca dele está escrito, mas ai daquele homem por quem o Filho do homem é traído! bom seria para esse homem se não houvera nascido.

[[v40-26-25]]

^<<v40-26-25,25>>^ E, respondendo Judas, o que o traía, disse: Porventura  sou eu, Rabi? Ele disse: Tu o disseste.

[[v40-26-26]]

^<<v40-26-26,26>>^ E, quando comiam, Jesus tomou o pão, e, abençoando- o , o partiu, e o deu aos discípulos, e disse: Tomai, comei, isto é o meu corpo.

[[v40-26-27]]

^<<v40-26-27,27>>^ E, tomando o cálice, e dando graças, deu-lho, dizendo: Bebei dele todos;

[[v40-26-28]]

^<<v40-26-28,28>>^ Porque isto é o meu sangue, o sangue  do Novo Testamento, que é derramado por muitos, para remissão dos pecados.

[[v40-26-29]]

^<<v40-26-29,29>>^ E digo-vos que, desde agora, não beberei deste fruto da vide até àquele dia em que o beba de novo convosco no reino de meu Pai.

[[v40-26-30]]

^<<v40-26-30,30>>^ E, tendo cantado o hino, saíram para o monte das Oliveiras.

[[v40-26-31]]

^<<v40-26-31,31>>^ Então Jesus lhes disse: Todos vós esta noite vos escandalizareis em mim; porque está escrito: Ferirei o pastor, e as ovelhas do rebanho se dispersarão.

[[v40-26-32]]

^<<v40-26-32,32>>^ Mas, depois de eu ressuscitar, irei adiante de vós para a Galileia.

[[v40-26-33]]

^<<v40-26-33,33>>^ Mas Pedro, respondendo, disse-lhe: Ainda que todos se escandalizem em ti, eu nunca me escandalizarei.

[[v40-26-34]]

^<<v40-26-34,34>>^ Disse-lhe Jesus: Em verdade te digo que, nesta mesma noite, antes que o galo cante, três vezes me negarás.

[[v40-26-35]]

^<<v40-26-35,35>>^ Disse-lhe Pedro: Ainda que me seja mister morrer contigo, não te negarei. E todos os discípulos disseram o mesmo.

[[v40-26-36]]

^<<v40-26-36,36>>^ Então chegou Jesus com eles a um lugar chamado Getsêmani, e disse a seus discípulos: Assentai-vos aqui, enquanto vou além orar.

[[v40-26-37]]

^<<v40-26-37,37>>^ E, levando consigo Pedro e os dois filhos de Zebedeu, começou a entristecer-se e a angustiar-se muito.

[[v40-26-38]]

^<<v40-26-38,38>>^ Então lhes disse: A minha alma está cheia de tristeza até à morte; ficai aqui, e velai comigo.

[[v40-26-39]]

^<<v40-26-39,39>>^ E, indo um pouco mais para diante, prostrou-se sobre o seu rosto, orando e dizendo: Meu Pai, se é possível, passe de mim este cálice; todavia, não seja como eu quero, mas como tu queres.

[[v40-26-40]]

^<<v40-26-40,40>>^ E voltando para os seus discípulos, achou-os adormecidos; e disse a Pedro: Então nem uma hora pudeste velar comigo?

[[v40-26-41]]

^<<v40-26-41,41>>^ Vigiai e orai, para que não entreis em tentação: na verdade, o espírito está  pronto, mas a carne é  fraca.

[[v40-26-42]]

^<<v40-26-42,42>>^ E, indo segunda vez, orou, dizendo: Pai Meu, se este cálice não pode passar de mim sem eu o beber, faça-se a tua vontade.

[[v40-26-43]]

^<<v40-26-43,43>>^ E, voltando, achou-os outra vez adormecidos; porque os seus olhos estavam carregados.

[[v40-26-44]]

^<<v40-26-44,44>>^ E, deixando-os de novo, foi orar pela terceira vez, dizendo as mesmas palavras.

[[v40-26-45]]

^<<v40-26-45,45>>^ Então chegou junto dos seus discípulos, e disse-lhes: Dormi agora, e repousai; eis que é chegada a hora, e o Filho do homem será entregue nas mãos dos pecadores.

[[v40-26-46]]

^<<v40-26-46,46>>^ Levantai-vos, partamos; eis que é chegado o que me trai.

[[v40-26-47]]

^<<v40-26-47,47>>^ E, estando ele ainda a falar, eis que chegou Judas, um dos doze, e com ele grande multidão com espadas e varapaus, enviada  pelos príncipes dos sacerdotes e pelos anciãos do povo.

[[v40-26-48]]

^<<v40-26-48,48>>^ E o que traía tinha-lhes dado um sinal, dizendo: O que eu beijar é esse; prendei-o.

[[v40-26-49]]

^<<v40-26-49,49>>^ E logo, aproximando-se de Jesus, disse: Eu te saúdo Rabi. E beijou-o.

[[v40-26-50]]

^<<v40-26-50,50>>^ Jesus, porém, lhe disse: Amigo, a que vieste? Então, aproximando-se eles, lançaram mão de Jesus, e o prenderam.

[[v40-26-51]]

^<<v40-26-51,51>>^ E eis que um dos que estavam  com Jesus, estendendo a mão, puxou da espada e, ferindo o servo do sumo sacerdote, cortou-lhe uma orelha.

[[v40-26-52]]

^<<v40-26-52,52>>^ Então Jesus disse-lhe: Mete no seu lugar a tua espada; porque todos os que lançarem mão da espada à espada morrerão.

[[v40-26-53]]

^<<v40-26-53,53>>^ Ou pensas tu que eu não poderia agora orar a meu Pai, e que ele não me daria mais de doze legiões de anjos?

[[v40-26-54]]

^<<v40-26-54,54>>^ Como pois  se cumpririam as Escrituras, que dizem  que assim convém que aconteça?

[[v40-26-55]]

^<<v40-26-55,55>>^ Então disse Jesus à multidão: Saístes, como para um salteador, com espadas e varapaus para me prender? todos os dias me assentava junto de vós, ensinando no templo, e não me prendestes.

[[v40-26-56]]

^<<v40-26-56,56>>^ Mas tudo isto aconteceu para que se cumpram as escrituras dos profetas. Então todos os discípulos, deixando-o, fugiram.

[[v40-26-57]]

^<<v40-26-57,57>>^ E, os que prenderam a Jesus, o conduziram à casa do sumo sacerdote Caifás, onde os escribas e os anciãos estavam reunidos.

[[v40-26-58]]

^<<v40-26-58,58>>^ E Pedro o seguiu de longe até ao pátio do sumo sacerdote e, entrando, assentou-se entre os criados, para ver o fim.

[[v40-26-59]]

^<<v40-26-59,59>>^ Ora os príncipes dos sacerdotes, e os anciãos, e todo o conselho, buscavam falso testemunho contra Jesus, para poderem dar-lhe a morte;

[[v40-26-60]]

^<<v40-26-60,60>>^ E não o achavam, apesar de se apresentarem muitas testemunhas falsas; mas por fim chegaram duas,

[[v40-26-61]]

^<<v40-26-61,61>>^ E disseram: Este disse: Eu posso derribar o templo de Deus, e reedificá-lo em três dias.

[[v40-26-62]]

^<<v40-26-62,62>>^ E, levantando-se o sumo sacerdote disse-lhe: Não respondes coisa alguma ao que estes depõem contra ti?

[[v40-26-63]]

^<<v40-26-63,63>>^ E Jesus, porém, guardava silêncio. E, insistindo o sumo sacerdote, disse-lhe: Conjuro-te pelo Deus vivo que nos digas se tu és o Cristo, o Filho de Deus.

[[v40-26-64]]

^<<v40-26-64,64>>^ Disse-lhes Jesus: Tu o  disseste; digo-vos, porém, que vereis em breve o Filho do homem assentado à direita do Poder, e vindo sobre as nuvens do céu.

[[v40-26-65]]

^<<v40-26-65,65>>^ Então o sumo sacerdote rasgou os seus vestidos, dizendo: Blasfemou; para que precisamos ainda de testemunhas? Eis que bem ouvistes agora a sua blasfêmia.

[[v40-26-66]]

^<<v40-26-66,66>>^ Que vos parece? E eles, respondendo, disseram: É réu de morte.

[[v40-26-67]]

^<<v40-26-67,67>>^ Então cuspiram-lhe no rosto e lhe davam punhadas, e outros o  esbofeteavam,

[[v40-26-68]]

^<<v40-26-68,68>>^ Dizendo: Profetiza-nos, Cristo, quem é o que te bateu?

[[v40-26-69]]

^<<v40-26-69,69>>^ Ora Pedro estava assentado fora, no pátio; e, aproximando-se dele uma criada, disse: Tu também estavas com Jesus, o galileu.

[[v40-26-70]]

^<<v40-26-70,70>>^ Mas ele negou diante de todos, dizendo: Não sei o que dizes.

[[v40-26-71]]

^<<v40-26-71,71>>^ E, saindo para o vestíbulo, outra criada o viu, e disse aos que ali estavam: Este também estava com Jesus, o nazareno.

[[v40-26-72]]

^<<v40-26-72,72>>^ E ele negou outra vez com juramento: Não conheço tal  homem.

[[v40-26-73]]

^<<v40-26-73,73>>^ E, daí a pouco, aproximando-se os que ali estavam, disseram a Pedro: Verdadeiramente também tu és deles, pois a tua fala te denuncia.

[[v40-26-74]]

^<<v40-26-74,74>>^ Então começou ele a praguejar e a jurar, dizendo : Não conheço esse  homem. E imediatamente o galo cantou.

[[v40-26-75]]

^<<v40-26-75,75>>^ E lembrou-se Pedro das palavras de Jesus, que lhe dissera: Antes que o galo cante, três vezes me negarás. E, saindo dali, chorou amargamente.

'''

xref:040-mateus/040-mateus-025.adoc#v40-25-0[&#60; Capítulo Anterior] | <<v40-26-0,Topo>> | xref:040-mateus/040-mateus-027.adoc#v40-27-0[Próximo Capítulo &#62;]