include::./index.adoc[]

[[v40-9-0]]
=== Mateus, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-9-1]]

^<<v40-9-1,1>>^ E, ENTRANDO no barco, passou para a outra banda, e chegou à sua cidade. E eis que lhe trouxeram um paralítico deitado numa  cama.

[[v40-9-2]]

^<<v40-9-2,2>>^ E Jesus, vendo a fé deles, disse ao paralítico: Filho, tem bom ânimo; perdoados te são os teus pecados.

[[v40-9-3]]

^<<v40-9-3,3>>^ E eis que alguns dos escribas diziam entre si: Ele blasfema.

[[v40-9-4]]

^<<v40-9-4,4>>^ Mas Jesus, conhecendo os seus pensamentos, disse: Por que pensais mal em vossos corações?

[[v40-9-5]]

^<<v40-9-5,5>>^ Pois qual é mais fácil? dizer: Perdoados te são os teus  pecados: ou dizer: Levanta-te e anda?

[[v40-9-6]]

^<<v40-9-6,6>>^ Ora, para que saibais que o Filho do homem tem na terra autoridade para perdoar pecados (disse então ao paralítico): Levanta-te; toma a tua cama, e vai para tua casa.

[[v40-9-7]]

^<<v40-9-7,7>>^ E, levantando-se, foi para sua casa.

[[v40-9-8]]

^<<v40-9-8,8>>^ E a multidão, vendo isto , maravilhou-se, e glorificou a Deus, que dera tal poder aos homens.

[[v40-9-9]]

^<<v40-9-9,9>>^ E Jesus, passando adiante  dali, viu assentado na alfândega um homem, chamado Mateus, e disse-lhe: Segue-me. E ele, levantando-se, o seguiu.

[[v40-9-10]]

^<<v40-9-10,10>>^ E aconteceu que, estando ele em casa sentado à mesa , chegaram muitos publicanos e pecadores, e sentaram-se juntamente com Jesus e seus discípulos.

[[v40-9-11]]

^<<v40-9-11,11>>^ E os fariseus, vendo isto , disseram aos seus discípulos: Por que come o vosso Mestre com os publicanos e pecadores?

[[v40-9-12]]

^<<v40-9-12,12>>^ Jesus, porém, ouvindo, disse-lhes: Não necessitam de médico os sãos, mas sim os doentes.

[[v40-9-13]]

^<<v40-9-13,13>>^ Ide, porém, e aprendei o que significa: Misericórdia quero, e não sacrifício. Porque eu não vim a chamar os justos, mas os pecadores, ao arrependimento.

[[v40-9-14]]

^<<v40-9-14,14>>^ Então chegaram ao pé dele os discípulos de João, dizendo: Por que jejuamos nós e os fariseus muitas vezes, e os teus discípulos não jejuam?

[[v40-9-15]]

^<<v40-9-15,15>>^ E disse-lhes Jesus: Podem porventura  andar tristes os filhos das bodas, enquanto o esposo está com eles? Dias, porém, virão em que lhes será tirado o esposo e então jejuarão.

[[v40-9-16]]

^<<v40-9-16,16>>^ Ninguém deita remendo de pano novo em vestido velho, porque semelhante remendo rompe o vestido, e faz-se maior a rotura.

[[v40-9-17]]

^<<v40-9-17,17>>^ Nem se deita vinho novo em odres velhos; aliás rompem-se os odres, e entorna-se o vinho, e os odres estragam-se; mas deita-se vinho novo em odres novos, e assim ambos se conservam.

[[v40-9-18]]

^<<v40-9-18,18>>^ Dizendo-lhes ele estas coisas , eis que chegou um chefe, e o adorou, dizendo: Minha filha faleceu agora mesmo; mas vem, impõe-lhe a tua mão, e ela viverá.

[[v40-9-19]]

^<<v40-9-19,19>>^ E Jesus, levantando-se, seguiu- o ele  e os seus discípulos.

[[v40-9-20]]

^<<v40-9-20,20>>^ E eis que uma mulher que havia já doze anos padecia de um fluxo de sangue, chegando por detrás dele , tocou a orla do seu vestido;

[[v40-9-21]]

^<<v40-9-21,21>>^ Porque dizia consigo: Se eu tão somente tocar o seu vestido, ficarei sã.

[[v40-9-22]]

^<<v40-9-22,22>>^ E Jesus, voltando-se, e vendo-a, disse: Tem ânimo, filha, a tua fé te salvou. E imediatamente a mulher ficou sã.

[[v40-9-23]]

^<<v40-9-23,23>>^ E Jesus, chegando à casa daquele chefe, e vendo os instrumentistas, e o povo em alvoroço,

[[v40-9-24]]

^<<v40-9-24,24>>^ Disse-lhes: Retirai-vos, que a menina não está morta, mas dorme. E riram-se dele.

[[v40-9-25]]

^<<v40-9-25,25>>^ E, logo que o povo foi posto fora, entrou Jesus, e pegou-lhe na mão, e a menina levantou-se.

[[v40-9-26]]

^<<v40-9-26,26>>^ E espalhou-se aquela notícia por todo aquele país.

[[v40-9-27]]

^<<v40-9-27,27>>^ E, partindo Jesus dali, seguiram-no dois cegos, clamando, e dizendo: Tem compaixão de nós, filho de Davi.

[[v40-9-28]]

^<<v40-9-28,28>>^ E, quando chegou à casa, os cegos se aproximaram dele; e Jesus disse-lhes: Credes vós que eu possa fazer isto? Disseram-lhe eles: Sim, Senhor.

[[v40-9-29]]

^<<v40-9-29,29>>^ Tocou então os olhos deles, dizendo: Seja-vos feito segundo a vossa fé.

[[v40-9-30]]

^<<v40-9-30,30>>^ E os olhos se lhes abriram. E Jesus ameaçou-os, dizendo: Olhai que ninguém o  saiba.

[[v40-9-31]]

^<<v40-9-31,31>>^ Mas, tendo ele saído, divulgaram a sua fama por toda aquela terra.

[[v40-9-32]]

^<<v40-9-32,32>>^ E, havendo-se eles retirado, trouxeram-lhe um homem mudo e endemoninhado.

[[v40-9-33]]

^<<v40-9-33,33>>^ E, expulso o demônio, falou o mudo; e a multidão se maravilhou, dizendo: Nunca tal se viu em Israel.

[[v40-9-34]]

^<<v40-9-34,34>>^ Mas os fariseus diziam: Ele expulsa os demônios pelo príncipe dos demônios.

[[v40-9-35]]

^<<v40-9-35,35>>^ E percorria Jesus todas as cidades e aldeias, ensinando nas sinagogas deles, e pregando o evangelho do reino, e curando todas as enfermidades e moléstias entre o povo.

[[v40-9-36]]

^<<v40-9-36,36>>^ E, vendo a multidão, teve grande compaixão deles, porque andavam desgarrados e errantes, como ovelhas que não têm pastor.

[[v40-9-37]]

^<<v40-9-37,37>>^ Então disse aos seus discípulos: A seara é  realmente grande, mas poucos os ceifeiros.

[[v40-9-38]]

^<<v40-9-38,38>>^ Rogai pois ao Senhor da seara que mande ceifeiros para a sua seara .

'''

xref:040-mateus/040-mateus-008.adoc#v40-8-0[&#60; Capítulo Anterior] | <<v40-9-0,Topo>> | xref:040-mateus/040-mateus-010.adoc#v40-10-0[Próximo Capítulo &#62;]