include::./index.adoc[]

[[v40-12-0]]
=== Mateus, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-12-1]]

^<<v40-12-1,1>>^ NAQUELE tempo passou Jesus pelas searas, em um sábado; e os seus discípulos, tendo fome, começaram a colher espigas, e a comer.

[[v40-12-2]]

^<<v40-12-2,2>>^ E os fariseus, vendo isto , disseram-lhe: Eis que os teus discípulos fazem o que não é lícito fazer num sábado.

[[v40-12-3]]

^<<v40-12-3,3>>^ Ele porém, lhes disse: Não tendes lido o que fez Davi, quando teve fome, ele e os que com ele estavam ?

[[v40-12-4]]

^<<v40-12-4,4>>^ Como entrou na casa de Deus, e comeu os pães da proposição, que não lhe era lícito comer, nem aos que com ele estavam , mas só aos sacerdotes?

[[v40-12-5]]

^<<v40-12-5,5>>^ Ou não tendes lido na lei que, aos sábados, os sacerdotes no templo violam o sábado, e ficam sem culpa?

[[v40-12-6]]

^<<v40-12-6,6>>^ Pois eu vos digo que está aqui quem é maior do que o templo.

[[v40-12-7]]

^<<v40-12-7,7>>^ Mas, se vós soubésseis o que significa: Misericórdia quero, e não sacrifício, não condenaríeis os inocentes.

[[v40-12-8]]

^<<v40-12-8,8>>^ Porque o Filho do homem até do sábado é Senhor.

[[v40-12-9]]

^<<v40-12-9,9>>^ E, partindo dali, chegou à sinagoga deles.

[[v40-12-10]]

^<<v40-12-10,10>>^ E, estava ali um homem que tinha uma das mãos mirrada; e eles, para o acusarem, o interrogaram, dizendo: É lícito curar nos sábados?

[[v40-12-11]]

^<<v40-12-11,11>>^ E ele lhes disse: Qual dentre vós será o homem que tendo uma ovelha, se num sábado ela cair numa cova, não lançará mão dela, e a levantará?

[[v40-12-12]]

^<<v40-12-12,12>>^ Pois quanto mais vale um homem do que uma ovelha? É, por consequência, lícito fazer bem nos sábados.

[[v40-12-13]]

^<<v40-12-13,13>>^ Então disse àquele homem: Estende a tua mão. E ele a estendeu, e ficou sã como a outra.

[[v40-12-14]]

^<<v40-12-14,14>>^ E os fariseus, tendo saído, formaram conselho contra ele, para o matarem.

[[v40-12-15]]

^<<v40-12-15,15>>^ Jesus, sabendo isso, retirou-se dali, e acompanhou-o uma grande multidão de gente, e ele curou a todos.

[[v40-12-16]]

^<<v40-12-16,16>>^ E recomendava-lhes rigorosamente que o não descobrissem.

[[v40-12-17]]

^<<v40-12-17,17>>^ Para que se cumprisse o que fora dito pelo profeta Isaías, que diz:

[[v40-12-18]]

^<<v40-12-18,18>>^ Eis aqui o meu servo, que escolhi, o meu amado, em quem a minha alma se compraz: porei sobre ele o meu espírito, e anunciará aos gentios o juízo.

[[v40-12-19]]

^<<v40-12-19,19>>^ Não contenderá, nem clamará, nem alguém ouvirá pelas ruas a sua voz;

[[v40-12-20]]

^<<v40-12-20,20>>^ Não esmagará a cana quebrada e não apagará o morrão que fumega, até que faça triunfar o juízo;

[[v40-12-21]]

^<<v40-12-21,21>>^ E no seu nome os gentios esperarão.

[[v40-12-22]]

^<<v40-12-22,22>>^ Trouxeram-lhe então um endemoninhado cego e mudo; e, de tal modo o curou, que o cego e mudo falava e via.

[[v40-12-23]]

^<<v40-12-23,23>>^ E toda a multidão se admirava e dizia: Não é este o Filho de Davi?

[[v40-12-24]]

^<<v40-12-24,24>>^ Mas os fariseus, ouvindo isto , diziam: Este não expulsa os demônios senão por Belzebu, príncipe dos demônios.

[[v40-12-25]]

^<<v40-12-25,25>>^ Jesus, porém, conhecendo os seus pensamentos, disse-lhes: Todo reino dividido contra si mesmo é devastado; e toda cidade, ou casa, dividida contra si mesma não subsistirá.

[[v40-12-26]]

^<<v40-12-26,26>>^ E, se Satanás expulsa a Satanás, está dividido contra si mesmo; como subsistirá pois o seu reino?

[[v40-12-27]]

^<<v40-12-27,27>>^ E, se eu expulso os demônios por Belzebu, por quem os expulsam então os vossos filhos? Portanto eles mesmos serão os vossos juízes.

[[v40-12-28]]

^<<v40-12-28,28>>^ Mas, se eu expulso os demônios pelo Espírito de Deus, é conseguintemente chegado a vós o reino de Deus.

[[v40-12-29]]

^<<v40-12-29,29>>^ Ou, como pode alguém entrar em casa do homem  valente, e furtar os seus bens, se primeiro não manietar o valente, saqueando então a sua casa?

[[v40-12-30]]

^<<v40-12-30,30>>^ Quem não é comigo é contra mim; e quem comigo não ajunta espalha.

[[v40-12-31]]

^<<v40-12-31,31>>^ Portanto eu vos digo: Todo pecado e blasfêmia se perdoará aos homens; mas a blasfêmia contra o Espírito não será perdoada aos homens.

[[v40-12-32]]

^<<v40-12-32,32>>^ E, se qualquer disser alguma  palavra contra o Filho do homem, ser-lhe-á perdoado, mas, se alguém falar contra o Espírito Santo, não lhe será perdoado, nem neste século nem no futuro.

[[v40-12-33]]

^<<v40-12-33,33>>^ Ou fazei a árvore boa, e o seu fruto bom, ou fazei a árvore má, e o seu fruto mau; porque pelo fruto se conhece a árvore.

[[v40-12-34]]

^<<v40-12-34,34>>^ Raça de víboras, como podeis vós dizer boas coisas , sendo maus? pois do que há em abundância no coração, disso fala a boca.

[[v40-12-35]]

^<<v40-12-35,35>>^ O homem bom tira boas coisas  do seu bom tesouro, e o homem mau do mau tesouro tira coisas  más.

[[v40-12-36]]

^<<v40-12-36,36>>^ Mas eu vos digo que de toda a palavra ociosa que os homens disserem hão de dar conta no dia do juízo.

[[v40-12-37]]

^<<v40-12-37,37>>^ Porque por tuas palavras serás justificado e por tuas palavras serás condenado.

[[v40-12-38]]

^<<v40-12-38,38>>^ Então alguns dos escribas e dos fariseus tomaram a palavra, dizendo: Mestre, quiséramos ver da tua parte algum  sinal,

[[v40-12-39]]

^<<v40-12-39,39>>^ Mas ele lhes respondeu, e disse: Uma geração má e adúltera pede um  sinal, porém não se lhe dará outro sinal senão o do profeta Jonas;

[[v40-12-40]]

^<<v40-12-40,40>>^ Pois, como Jonas esteve três dias e três noites no ventre da baleia, assim estará o Filho do homem três dias e três noites no seio da terra.

[[v40-12-41]]

^<<v40-12-41,41>>^ Os ninivitas ressurgirão no juízo com esta geração, e a condenarão, porque se arrependeram com a pregação de Jonas. E eis que está  aqui quem é mais do que Jonas.

[[v40-12-42]]

^<<v40-12-42,42>>^ A rainha do meio-dia se levantará no dia  do juízo com esta geração, e a condenará; porque veio dos confins da terra para ouvir a sabedoria de Salomão. E eis que está  aqui quem é mais do que Salomão.

[[v40-12-43]]

^<<v40-12-43,43>>^ E, quando o espírito imundo tem saído do homem, anda por lugares áridos, buscando repouso, e não o encontra.

[[v40-12-44]]

^<<v40-12-44,44>>^ Então diz: Voltarei para a minha casa donde saí. E, voltando, acha- a  desocupada, varrida e adornada.

[[v40-12-45]]

^<<v40-12-45,45>>^ Então vai, e leva consigo outros sete espíritos piores do que ele, e, entrando, habitam ali: e são os últimos atos  desse homem piores do que os primeiros. Assim acontecerá também a esta geração má.

[[v40-12-46]]

^<<v40-12-46,46>>^ E, falando ele ainda à multidão, eis que estavam fora sua mãe e seus irmãos, pretendendo falar-lhe.

[[v40-12-47]]

^<<v40-12-47,47>>^ E disse-lhe alguém: Eis que estão ali fora tua mãe e teus irmãos, que querem falar-te.

[[v40-12-48]]

^<<v40-12-48,48>>^ Porém ele, respondendo, disse ao que lhe falara: Quem é minha mãe? e quem são meus irmãos?

[[v40-12-49]]

^<<v40-12-49,49>>^ E, estendendo a sua mão para os seus discípulos, disse: Eis aqui minha mãe e meus irmãos;

[[v40-12-50]]

^<<v40-12-50,50>>^ Porque, qualquer que fizer a vontade de meu Pai que está  nos céus, este é meu irmão, e irmã e mãe.

'''

xref:040-mateus/040-mateus-011.adoc#v40-11-0[&#60; Capítulo Anterior] | <<v40-12-0,Topo>> | xref:040-mateus/040-mateus-013.adoc#v40-13-0[Próximo Capítulo &#62;]