include::./index.adoc[]

[[v40-20-0]]
=== Mateus, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-20-1]]

^<<v40-20-1,1>>^ PORQUE o reino dos céus é semelhante a um homem, pai de família, que saiu de madrugada a assalariar trabalhadores para a sua vinha.

[[v40-20-2]]

^<<v40-20-2,2>>^ E, ajustando com os trabalhadores a um dinheiro por dia, mandou-os para a sua vinha.

[[v40-20-3]]

^<<v40-20-3,3>>^ E, saindo perto da hora terceira, viu outros que estavam ociosos na praça.

[[v40-20-4]]

^<<v40-20-4,4>>^ E disse-lhes: Ide vós também para a vinha, e dar-vos-ei o que for justo. E eles foram.

[[v40-20-5]]

^<<v40-20-5,5>>^ Saindo outra vez, perto da hora sexta e nona, fez o mesmo.

[[v40-20-6]]

^<<v40-20-6,6>>^ E, saindo perto da hora undécima, encontrou outros que estavam ociosos, e perguntou-lhes: Por que estais ociosos todo o dia?

[[v40-20-7]]

^<<v40-20-7,7>>^ Disseram-lhe eles: Porque ninguém nos assalariou. Diz-lhes ele: Ide vós também para a vinha, e recebereis o que for justo.

[[v40-20-8]]

^<<v40-20-8,8>>^ E, aproximando-se a noite, diz o senhor da vinha ao seu mordomo: Chama os trabalhadores, e paga-lhes o jornal, começando pelos derradeiros até aos primeiros.

[[v40-20-9]]

^<<v40-20-9,9>>^ E, chegando os que tinham ido  perto da hora undécima, receberam um dinheiro cada um;

[[v40-20-10]]

^<<v40-20-10,10>>^ Vindo, porém, os primeiros, cuidaram que haviam de receber mais; mas do mesmo modo receberam um dinheiro cada um.

[[v40-20-11]]

^<<v40-20-11,11>>^ E, recebendo- o , murmuravam contra o pai de família,

[[v40-20-12]]

^<<v40-20-12,12>>^ Dizendo: Estes derradeiros trabalharam só  uma hora, e tu os igualaste conosco, que suportamos a fadiga e a calma do dia.

[[v40-20-13]]

^<<v40-20-13,13>>^ Mas ele, respondendo, disse a um deles: Amigo, não te faço agravo; não ajustaste tu comigo um dinheiro?

[[v40-20-14]]

^<<v40-20-14,14>>^ Toma o que é  teu, e retira-te; eu quero dar a este derradeiro tanto  como a ti.

[[v40-20-15]]

^<<v40-20-15,15>>^ Ou não me é lícito fazer o que quiser do que é  meu? Ou é mau o teu olho porque eu sou bom?

[[v40-20-16]]

^<<v40-20-16,16>>^ Assim os derradeiros serão primeiros, e os primeiros derradeiros; porque muitos são chamados, mas poucos escolhidos.

[[v40-20-17]]

^<<v40-20-17,17>>^ E, subindo Jesus a Jerusalém, chamou de parte os seus doze discípulos, e no caminho disse-lhes:

[[v40-20-18]]

^<<v40-20-18,18>>^ Eis que vamos para Jerusalém, e o Filho do homem será entregue aos príncipes dos sacerdotes, e aos escribas, e condená-lo-ão à morte.

[[v40-20-19]]

^<<v40-20-19,19>>^ E o entregarão aos gentios para que dele  escarneçam, e o açoitem e crucifiquem, e ao terceiro dia ressuscitará.

[[v40-20-20]]

^<<v40-20-20,20>>^ Então se aproximou dele a mãe dos filhos de Zebedeu, com seus filhos, adorando- o , e fazendo-lhe um pedido.

[[v40-20-21]]

^<<v40-20-21,21>>^ E ele diz-lhe: Que queres? Ela respondeu: Dize que estes meus dois filhos se assentem, um à tua direita e outro à tua esquerda, no teu reino.

[[v40-20-22]]

^<<v40-20-22,22>>^ Jesus, porém, respondendo, disse: Não sabeis o que pedis; podeis vós beber o cálice que eu hei de beber, e ser batizados com o batismo com que eu sou batizado? Dizem-lhe eles: Podemos.

[[v40-20-23]]

^<<v40-20-23,23>>^ E diz-lhes ele: Na verdade bebereis o meu cálice, mas o assentar-se à minha direita ou à minha esquerda não me pertence dá-lo, mas é para aqueles para quem meu Pai o tem preparado.

[[v40-20-24]]

^<<v40-20-24,24>>^ E, quando os dez ouviram isto , indignaram-se contra os dois irmãos.

[[v40-20-25]]

^<<v40-20-25,25>>^ Então Jesus, chamando-os para junto de si, disse: Bem sabeis que pelos príncipes dos gentios são estes dominados, e que os grandes exercem autoridade sobre eles.

[[v40-20-26]]

^<<v40-20-26,26>>^ Não será assim entre vós; mas todo aquele que quiser entre vós fazer-se grande seja vosso serviçal;

[[v40-20-27]]

^<<v40-20-27,27>>^ E qualquer que entre vós quiser ser o primeiro seja vosso servo;

[[v40-20-28]]

^<<v40-20-28,28>>^ Bem como o Filho do homem não veio para ser servido, mas para servir, e para dar a sua vida em  resgate de muitos.

[[v40-20-29]]

^<<v40-20-29,29>>^ E, saindo eles de Jericó, seguiu-o grande multidão.

[[v40-20-30]]

^<<v40-20-30,30>>^ E eis que dois cegos, assentados junto do caminho, ouvindo que Jesus passava, clamaram, dizendo: Senhor, Filho de Davi, tem misericórdia de nós.

[[v40-20-31]]

^<<v40-20-31,31>>^ E a multidão os repreendia, para que se calassem; eles, porém, cada vez clamavam mais, dizendo: Senhor, Filho de Davi, tem misericórdia de nós.

[[v40-20-32]]

^<<v40-20-32,32>>^ E Jesus, parando, chamou-os, e disse: Que quereis que vos faça?

[[v40-20-33]]

^<<v40-20-33,33>>^ Disseram-lhe eles: Senhor, que os nossos olhos sejam abertos.

[[v40-20-34]]

^<<v40-20-34,34>>^ Então Jesus, movido de íntima compaixão tocou-lhes nos olhos, e logo viram; e eles o seguiram.

'''

xref:040-mateus/040-mateus-019.adoc#v40-19-0[&#60; Capítulo Anterior] | <<v40-20-0,Topo>> | xref:040-mateus/040-mateus-021.adoc#v40-21-0[Próximo Capítulo &#62;]