include::./index.adoc[]

[[v40-24-0]]
=== Mateus, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-24-1]]

^<<v40-24-1,1>>^ E, QUANDO Jesus ia saindo do templo, aproximaram-se dele  os seus discípulos para lhe mostrarem a estrutura do templo.

[[v40-24-2]]

^<<v40-24-2,2>>^ Jesus, porém, lhes disse: Não vedes tudo isto? Em verdade vos digo que não ficará aqui pedra sobre pedra que não seja derribada.

[[v40-24-3]]

^<<v40-24-3,3>>^ E, estando assentado no monte das Oliveiras, chegaram-se a ele os seus discípulos, em particular, dizendo: Dize-nos quando serão essas coisas , e que sinal haverá  da tua vinda e do fim do mundo?

[[v40-24-4]]

^<<v40-24-4,4>>^ E Jesus, respondendo, disse-lhes: Acautelai-vos, que ninguém vos engane;

[[v40-24-5]]

^<<v40-24-5,5>>^ Porque muitos virão em meu nome, dizendo: Eu sou o Cristo; e enganarão a muitos.

[[v40-24-6]]

^<<v40-24-6,6>>^ E ouvireis de guerras e de rumores de guerras; olhai não vos assusteis, porque é mister que isso  tudo aconteça, mas ainda não é o fim.

[[v40-24-7]]

^<<v40-24-7,7>>^ Porquanto se levantará nação contra nação, e reino contra reino, e haverá fomes, e pestes, e terremotos, em vários lugares.

[[v40-24-8]]

^<<v40-24-8,8>>^ Mas todas estas coisas são  o princípio de dores.

[[v40-24-9]]

^<<v40-24-9,9>>^ Então vos hão de entregar para serdes atormentados, e matar-vos-ão; e sereis odiados de todas as gentes por causa do meu nome.

[[v40-24-10]]

^<<v40-24-10,10>>^ Nesse tempo muitos serão escandalizados, e trair-se-ão uns aos outros, e uns aos outros se aborrecerão.

[[v40-24-11]]

^<<v40-24-11,11>>^ E surgirão muitos falsos profetas, e enganarão a muitos.

[[v40-24-12]]

^<<v40-24-12,12>>^ E, por se multiplicar a iniquidade, o amor de muitos esfriará.

[[v40-24-13]]

^<<v40-24-13,13>>^ Mas aquele que perseverar até ao fim será salvo.

[[v40-24-14]]

^<<v40-24-14,14>>^ E este evangelho do reino será pregado em todo o mundo, em testemunho a todas as gentes, e então virá o fim.

[[v40-24-15]]

^<<v40-24-15,15>>^ Quando pois virdes que a abominação da desolação, de que falou o profeta Daniel, está no lugar santo; quem lê, atenda;

[[v40-24-16]]

^<<v40-24-16,16>>^ Então, os que estiverem  na Judeia, fujam para os montes;

[[v40-24-17]]

^<<v40-24-17,17>>^ E quem estiver  sobre o telhado não desça a tirar alguma coisa de sua casa;

[[v40-24-18]]

^<<v40-24-18,18>>^ E quem estiver no campo não volte atrás a buscar os seus vestidos.

[[v40-24-19]]

^<<v40-24-19,19>>^ Mas ai das grávidas e das que amamentarem naqueles dias!

[[v40-24-20]]

^<<v40-24-20,20>>^ E orai para que a vossa fuga não aconteça no inverno nem no sábado;

[[v40-24-21]]

^<<v40-24-21,21>>^ Porque haverá então grande aflição, como nunca houve desde o princípio do mundo até agora, nem tão pouco há de haver.

[[v40-24-22]]

^<<v40-24-22,22>>^ E, se aqueles dias não fossem abreviados, nenhuma carne se salvaria; mas por causa dos escolhidos serão abreviados aqueles dias.

[[v40-24-23]]

^<<v40-24-23,23>>^ Então, se alguém vos disser: Eis que o Cristo está  aqui, ou ali, não lhe deis crédito;

[[v40-24-24]]

^<<v40-24-24,24>>^ Porque surgirão falsos cristos e falsos profetas, e farão tão grandes sinais e prodígios que, se possível fora, enganariam até os escolhidos.

[[v40-24-25]]

^<<v40-24-25,25>>^ Eis que eu vo-lo tenho predito.

[[v40-24-26]]

^<<v40-24-26,26>>^ Portanto, se vos disserem: Eis que ele está no deserto, não saiais; eis que ele está no interior da casa, não acrediteis.

[[v40-24-27]]

^<<v40-24-27,27>>^ Porque, assim como o relâmpago sai do oriente e se mostra até ao ocidente, assim será também a vinda do Filho do homem.

[[v40-24-28]]

^<<v40-24-28,28>>^ Pois onde estiver o cadáver, aí se ajuntarão as águias.

[[v40-24-29]]

^<<v40-24-29,29>>^ E, logo depois da aflição daqueles dias, o sol escurecerá, e a lua não dará a sua luz, e as estrelas cairão do céu, e as potências dos céus serão abaladas.

[[v40-24-30]]

^<<v40-24-30,30>>^ Então aparecerá no céu o sinal do Filho do homem; e todas as tribos da terra se lamentarão, e verão o Filho do homem, vindo sobre as nuvens do céu, com poder e grande glória.

[[v40-24-31]]

^<<v40-24-31,31>>^ E ele enviará os seus anjos com rijo clamor de trombeta, os quais ajuntarão os seus escolhidos desde os quatro ventos, de uma à outra extremidade dos céus.

[[v40-24-32]]

^<<v40-24-32,32>>^ Aprendei pois esta  parábola da figueira: Quando já os seus ramos se tornam tenros e brotam folhas, sabeis que está próximo o verão.

[[v40-24-33]]

^<<v40-24-33,33>>^ Igualmente, quando virdes todas estas coisas , sabei que ele está próximo às portas.

[[v40-24-34]]

^<<v40-24-34,34>>^ Em verdade vos digo que não passará esta geração sem que todas estas coisas  aconteçam.

[[v40-24-35]]

^<<v40-24-35,35>>^ O céu e a terra passarão, mas as minhas palavras não hão de passar.

[[v40-24-36]]

^<<v40-24-36,36>>^ Porém daquele dia e hora ninguém sabe, nem os anjos do céu, nem o Filho, mas unicamente meu Pai.

[[v40-24-37]]

^<<v40-24-37,37>>^ E, como foi nos dias de Noé, assim será também a vinda do Filho do homem.

[[v40-24-38]]

^<<v40-24-38,38>>^ Porquanto, assim como, nos dias anteriores ao dilúvio, comiam, bebiam, casavam e davam-se em casamento, até ao dia em que Noé entrou na arca,

[[v40-24-39]]

^<<v40-24-39,39>>^ E não o perceberam, até que veio o dilúvio, e os levou a todos — assim será também a vinda do Filho do homem.

[[v40-24-40]]

^<<v40-24-40,40>>^ Então, estando dois no campo, será levado um, e deixado o outro;

[[v40-24-41]]

^<<v40-24-41,41>>^ Estando duas moendo no moinho será levada uma, e deixada outra.

[[v40-24-42]]

^<<v40-24-42,42>>^ Vigiai, pois, porque não sabeis a que hora há de vir o vosso Senhor;

[[v40-24-43]]

^<<v40-24-43,43>>^ Mas considerai isto: se o pai de família soubesse a que vigília da noite havia de vir o ladrão, vigiaria e não deixaria minar a sua casa.

[[v40-24-44]]

^<<v40-24-44,44>>^ Por isso, estai vós apercebidos também; porque o Filho do homem há de vir à hora em que não penseis.

[[v40-24-45]]

^<<v40-24-45,45>>^ Quem é pois o servo fiel e prudente, que o Senhor constituiu sobre a sua casa, para dar o sustento a seu tempo?

[[v40-24-46]]

^<<v40-24-46,46>>^ Bem-aventurado aquele servo que o Senhor, quando vier, achar servindo assim.

[[v40-24-47]]

^<<v40-24-47,47>>^ Em verdade vos digo que o porá sobre todos os seus bens.

[[v40-24-48]]

^<<v40-24-48,48>>^ Porém, se aquele mau servo disser consigo: O meu senhor tarde virá;

[[v40-24-49]]

^<<v40-24-49,49>>^ E começar a espancar os seus  conservos, e a comer e a beber com os temulentos,

[[v40-24-50]]

^<<v40-24-50,50>>^ Virá o senhor daquele servo num  dia em que o não espera, e à hora em que ele não sabe,

[[v40-24-51]]

^<<v40-24-51,51>>^ E separá-lo-á, e destinará a sua parte com os hipócritas; ali haverá pranto e ranger de dentes.

'''

xref:040-mateus/040-mateus-023.adoc#v40-23-0[&#60; Capítulo Anterior] | <<v40-24-0,Topo>> | xref:040-mateus/040-mateus-025.adoc#v40-25-0[Próximo Capítulo &#62;]