include::./index.adoc[]

[[v40-18-0]]
=== Mateus, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-18-1]]

^<<v40-18-1,1>>^ NAQUELA mesma hora chegaram os discípulos ao pé de Jesus, dizendo: Quem é o maior no reino dos céus?

[[v40-18-2]]

^<<v40-18-2,2>>^ E Jesus, chamando um menino, o pôs no meio deles,

[[v40-18-3]]

^<<v40-18-3,3>>^ E disse: Em verdade vos digo que, se não vos converterdes e não vos fizerdes como meninos, de modo algum entrareis no reino dos céus.

[[v40-18-4]]

^<<v40-18-4,4>>^ Portanto, aquele que se tornar humilde como este menino, esse é o maior no reino dos céus.

[[v40-18-5]]

^<<v40-18-5,5>>^ E qualquer que receber em meu nome um menino tal como este, a mim me recebe.

[[v40-18-6]]

^<<v40-18-6,6>>^ Mas qualquer que escandalizar um destes pequeninos, que creem em mim, melhor lhe fora que se lhe pendurasse ao pescoço uma mó de azenha, e se submergisse na profundeza do mar.

[[v40-18-7]]

^<<v40-18-7,7>>^ Ai do mundo, por causa dos escândalos; porque é mister que venham escândalos, mas ai daquele homem por quem o escândalo vem!

[[v40-18-8]]

^<<v40-18-8,8>>^ Portanto, se a tua mão ou o teu pé te escandalizar, corta-o, e atira-o para longe de ti: melhor te é entrar na vida coxo, ou aleijado, do que, tendo duas mãos ou dois pés, seres lançado no fogo eterno.

[[v40-18-9]]

^<<v40-18-9,9>>^ E, se o teu olho te escandalizar, arranca- o , e atira- o  para longe de ti. Melhor te é entrar na vida com um só olho, do que, tendo dois olhos, seres lançado no fogo do inferno.

[[v40-18-10]]

^<<v40-18-10,10>>^ Vede, não desprezeis algum destes pequeninos, porque eu vos digo que os seus anjos nos céus sempre veem a face de meu Pai que está  nos céus.

[[v40-18-11]]

^<<v40-18-11,11>>^ Porque o Filho do homem veio salvar o que se tinha perdido.

[[v40-18-12]]

^<<v40-18-12,12>>^ Que vos parece? Se algum homem tiver cem ovelhas, e uma delas se desgarrar, não irá pelos montes, deixando as noventa e nove, em busca da que se desgarrou?

[[v40-18-13]]

^<<v40-18-13,13>>^ E, se porventura a acha, em verdade vos digo que maior prazer tem por aquela do que pelas noventa e nove que se não desgarraram.

[[v40-18-14]]

^<<v40-18-14,14>>^ Assim também não é vontade de vosso Pai, que está  nos céus, que um destes pequeninos se perca.

[[v40-18-15]]

^<<v40-18-15,15>>^ Ora, se teu irmão pecar contra ti, vai, e repreende-o entre ti e ele só; se te ouvir, ganhaste a teu irmão;

[[v40-18-16]]

^<<v40-18-16,16>>^ Mas se não te ouvir, leva ainda contigo um ou dois, para que pela boca de duas ou três testemunhas toda a palavra seja confirmada.

[[v40-18-17]]

^<<v40-18-17,17>>^ E, se não as escutar, dize- o  à igreja; e, se também não escutar a igreja, considera o como um gentio e publicano.

[[v40-18-18]]

^<<v40-18-18,18>>^ Em verdade vos digo que tudo o que ligardes na terra será ligado no céu, e tudo o que desligardes na terra será desligado no céu.

[[v40-18-19]]

^<<v40-18-19,19>>^ Também vos digo que, se dois de vós concordarem na terra acerca de qualquer coisa que pedirem, isso lhes será feito por meu Pai, que está  nos céus.

[[v40-18-20]]

^<<v40-18-20,20>>^ Porque onde estiverem dois ou três reunidos em meu nome, aí, estou eu no meio deles.

[[v40-18-21]]

^<<v40-18-21,21>>^ Então Pedro, aproximando-se dele, disse: Senhor, até quantas vezes pecará meu irmão contra mim, e eu lhe perdoarei? Até sete?

[[v40-18-22]]

^<<v40-18-22,22>>^ Jesus lhe disse: Não te digo que até sete, mas, até setenta vezes sete.

[[v40-18-23]]

^<<v40-18-23,23>>^ Por isso o reino dos céus pode comparar-se a um certo rei que quis fazer contas com os seus servos;

[[v40-18-24]]

^<<v40-18-24,24>>^ E, começando a fazer contas, foi-lhe apresentado um que lhe devia dez mil talentos;

[[v40-18-25]]

^<<v40-18-25,25>>^ E, não tendo ele com que pagar, o seu senhor mandou que ele, e sua mulher e seus filhos fossem vendidos, com tudo quanto tinha, para que a dívida  se lhe pagasse.

[[v40-18-26]]

^<<v40-18-26,26>>^ Então aquele servo, prostrando-se, o reverenciava, dizendo: Senhor, sê generoso para comigo, e tudo te pagarei.

[[v40-18-27]]

^<<v40-18-27,27>>^ Então o senhor daquele servo, movido de íntima compaixão, soltou-o e perdoou-lhe a dívida.

[[v40-18-28]]

^<<v40-18-28,28>>^ Saindo, porém, aquele servo, encontrou um dos seus conservos, que lhe devia cem dinheiros, e, lançando mão dele sufocava o, dizendo: Paga-me o que me deves.

[[v40-18-29]]

^<<v40-18-29,29>>^ Então o seu companheiro, prostrando-se a seus pés, rogava-lhe, dizendo: Sê generoso para comigo, e tudo te pagarei.

[[v40-18-30]]

^<<v40-18-30,30>>^ Ele, porém, não quis, antes foi encerrá-lo na prisão, até que pagasse a dívida.

[[v40-18-31]]

^<<v40-18-31,31>>^ Vendo pois os seus conservos o que acontecia, contristaram-se muito, e foram declarar ao seu senhor tudo o que se passara.

[[v40-18-32]]

^<<v40-18-32,32>>^ Então o seu senhor, chamando-o à sua presença, disse-lhe: Servo malvado, perdoei-te toda aquela dívida, porque me suplicaste,

[[v40-18-33]]

^<<v40-18-33,33>>^ Não devias tu igualmente ter compaixão do teu companheiro, como eu também tive misericórdia de ti?

[[v40-18-34]]

^<<v40-18-34,34>>^ E, indignado, o seu senhor o entregou aos atormentadores, até que pagasse tudo o que devia.

[[v40-18-35]]

^<<v40-18-35,35>>^ Assim vos fará também meu Pai celestial, se do coração não perdoardes, cada um a seu irmão, as suas ofensas.

'''

xref:040-mateus/040-mateus-017.adoc#v40-17-0[&#60; Capítulo Anterior] | <<v40-18-0,Topo>> | xref:040-mateus/040-mateus-019.adoc#v40-19-0[Próximo Capítulo &#62;]