include::./index.adoc[]

[[v40-15-0]]
=== Mateus, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-15-1]]

^<<v40-15-1,1>>^ ENTÃO chegaram ao pé de Jesus uns escribas e fariseus de Jerusalém, dizendo:

[[v40-15-2]]

^<<v40-15-2,2>>^ Por que transgridem os teus discípulos a tradição dos anciãos? pois não lavam as mãos quando comem pão.

[[v40-15-3]]

^<<v40-15-3,3>>^ Ele, porém, respondendo, disse-lhes: Por que transgredis vós também o mandamento de Deus pela vossa tradição?

[[v40-15-4]]

^<<v40-15-4,4>>^ Porque Deus ordenou, dizendo: Honra a teu pai e a tua  mãe; e: Quem maldisser ao pai ou à mãe, morra de morte.

[[v40-15-5]]

^<<v40-15-5,5>>^ Mas vós dizeis: Qualquer que disser ao pai ou à mãe: É oferta ao Senhor o que poderias aproveitar de mim; esse não precisa honrar nem a seu pai nem a sua mãe,

[[v40-15-6]]

^<<v40-15-6,6>>^ E assim  invalidastes, pela vossa tradição, o mandamento de Deus.

[[v40-15-7]]

^<<v40-15-7,7>>^ Hipócritas, bem profetizou Isaías a vosso respeito, dizendo:

[[v40-15-8]]

^<<v40-15-8,8>>^ Este povo honra-me com os seus lábios, mas o seu coração está longe de mim.

[[v40-15-9]]

^<<v40-15-9,9>>^ Mas em vão me adoram, ensinando doutrinas que são  preceitos dos homens.

[[v40-15-10]]

^<<v40-15-10,10>>^ E, chamando a si a multidão, disse-lhes: Ouvi, e entendei:

[[v40-15-11]]

^<<v40-15-11,11>>^ O que contamina o homem não é o que entra na boca, mas o que sai da boca isso é o que contamina o homem.

[[v40-15-12]]

^<<v40-15-12,12>>^ Então, acercando-se dele os seus discípulos, disseram-lhe: Sabes que os fariseus, ouvindo essas palavras, se escandalizaram?

[[v40-15-13]]

^<<v40-15-13,13>>^ Ele, porém, respondendo, disse: Toda a planta, que meu Pai celestial não plantou, será arrancada.

[[v40-15-14]]

^<<v40-15-14,14>>^ Deixai-os: são condutores cegos: ora, se um cego guiar outro  cego, ambos cairão na cova.

[[v40-15-15]]

^<<v40-15-15,15>>^ E Pedro, tomando a palavra, disse-lhe: Explica-nos essa parábola.

[[v40-15-16]]

^<<v40-15-16,16>>^ Jesus, porém, disse: Até vós mesmos estais ainda sem entender?

[[v40-15-17]]

^<<v40-15-17,17>>^ Ainda não compreendeis que tudo o que entra pela boca desce para o ventre, e é lançado fora?

[[v40-15-18]]

^<<v40-15-18,18>>^ Mas o que sai da boca, procede do coração, e isso contamina o homem.

[[v40-15-19]]

^<<v40-15-19,19>>^ Porque do coração procedem os maus pensamentos, mortes, adultérios, prostituição, furtos, falsos testemunhos e blasfêmias.

[[v40-15-20]]

^<<v40-15-20,20>>^ São estas coisas  que contaminam o homem; mas comer sem lavar as mãos, isso não contamina o homem.

[[v40-15-21]]

^<<v40-15-21,21>>^ E, partindo Jesus dali, foi para as partes de Tiro e de Sidom.

[[v40-15-22]]

^<<v40-15-22,22>>^ E eis que uma mulher cananeia, que saíra daquelas cercanias, clamou, dizendo: Senhor, Filho de Davi, tem misericórdia de mim, que minha filha está miseravelmente endemoninhada.

[[v40-15-23]]

^<<v40-15-23,23>>^ Mas ele não lhe respondeu palavra. E os seus discípulos, chegando ao pé dele, rogaram-lhe, dizendo: Despede-a, que vem gritando atrás de nós.

[[v40-15-24]]

^<<v40-15-24,24>>^ E ele, respondendo, disse: Eu não fui enviado senão às ovelhas perdidas da casa d’Israel.

[[v40-15-25]]

^<<v40-15-25,25>>^ Então chegou ela, e adorou-o, dizendo: Senhor, socorre-me.

[[v40-15-26]]

^<<v40-15-26,26>>^ Ele, porém respondendo, disse: Não é bom pegar no pão dos filhos e deitá-l o  aos cachorrinhos.

[[v40-15-27]]

^<<v40-15-27,27>>^ E ela disse: Sim, Senhor, mas também os cachorrinhos comem das migalhas que caem da mesa dos seus senhores.

[[v40-15-28]]

^<<v40-15-28,28>>^ Então respondeu Jesus, e disse-lhe: Ó mulher! grande é  a tua fé: seja isso feito para contigo como tu desejas. E desde aquela hora a sua filha ficou sã.

[[v40-15-29]]

^<<v40-15-29,29>>^ Partindo Jesus dali, chegou ao pé do mar da Galileia, e, subindo a um  monte, assentou-se lá.

[[v40-15-30]]

^<<v40-15-30,30>>^ E veio ter com ele muito povo, que trazia coxos, cegos, mudos, aleijados, e outros muitos: e os puseram aos pés de Jesus, e ele os sarou;

[[v40-15-31]]

^<<v40-15-31,31>>^ De tal sorte, que a multidão se maravilhou vendo os mudos a falar, os aleijados sãos, os coxos a andar, e os cegos a ver; e glorificava o Deus d’Israel.

[[v40-15-32]]

^<<v40-15-32,32>>^ E Jesus, chamando os seus discípulos, disse: Tenho compaixão da multidão, porque já está comigo há três dias, e não tem que comer; e não quero despedi-la em jejum, para que não desfaleça no caminho.

[[v40-15-33]]

^<<v40-15-33,33>>^ E os seus discípulos disseram-lhe: Donde nos viriam  num deserto tantos pães, para saciar tal multidão?

[[v40-15-34]]

^<<v40-15-34,34>>^ E Jesus disse-lhes: Quantos pães tendes? E eles disseram: Sete, e uns poucos peixinhos.

[[v40-15-35]]

^<<v40-15-35,35>>^ Então mandou à multidão que se assentasse no chão.

[[v40-15-36]]

^<<v40-15-36,36>>^ E, tomando os sete pães e os peixes, e dando graças, partiu-os, e deu-os aos seus discípulos, e os discípulos à multidão.

[[v40-15-37]]

^<<v40-15-37,37>>^ E todos comeram e se saciaram: e levantaram, do que sobejou, sete cestos cheios de pedaços.

[[v40-15-38]]

^<<v40-15-38,38>>^ Ora os que tinham comido eram quatro mil homens, além de mulheres e crianças.

[[v40-15-39]]

^<<v40-15-39,39>>^ E, tendo despedido a multidão, entrou no  barco, e dirigiu-se ao território de Magdala.

'''

xref:040-mateus/040-mateus-014.adoc#v40-14-0[&#60; Capítulo Anterior] | <<v40-15-0,Topo>> | xref:040-mateus/040-mateus-016.adoc#v40-16-0[Próximo Capítulo &#62;]