include::./index.adoc[]

[[v40-21-0]]
=== Mateus, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-21-1]]

^<<v40-21-1,1>>^ E QUANDO se aproximaram de Jerusalém, e chegaram a Betfagé, ao monte das Oliveiras, enviou então Jesus dois discípulos, dizendo-lhes:

[[v40-21-2]]

^<<v40-21-2,2>>^ Ide à aldeia que está  defronte de vós, e logo encontrareis uma jumenta presa, e um jumentinho com ela; desprendei- a , e trazei- mos.

[[v40-21-3]]

^<<v40-21-3,3>>^ E, se alguém vos disser alguma coisa , direis que o Senhor os há de mister: e logo os enviará.

[[v40-21-4]]

^<<v40-21-4,4>>^ Ora tudo isto aconteceu para que se cumprisse o que foi dito pelo profeta, que diz:

[[v40-21-5]]

^<<v40-21-5,5>>^ Dizei à filha de Sião: Eis que o teu Rei aí te vem, manso, e assentado sobre uma jumenta, e sobre um jumentinho, filho de animal de carga.

[[v40-21-6]]

^<<v40-21-6,6>>^ E, indo os discípulos, e fazendo como Jesus lhes ordenara,

[[v40-21-7]]

^<<v40-21-7,7>>^ Trouxeram a jumenta e o jumentinho, e sobre eles puseram os seus vestidos e fizeram-no assentar em cima.

[[v40-21-8]]

^<<v40-21-8,8>>^ E muitíssima gente estendia os seus vestidos pelo caminho, e outros cortavam ramos de árvores e os  espalhavam pelo caminho.

[[v40-21-9]]

^<<v40-21-9,9>>^ E a multidão que ia adiante, e a que seguia, clamava, dizendo: Hosana ao Filho de Davi; bendito o que vem em nome do Senhor. Hosana nas alturas.

[[v40-21-10]]

^<<v40-21-10,10>>^ E, entrando ele em Jerusalém, toda a cidade se alvoroçou, dizendo: Quem é este?

[[v40-21-11]]

^<<v40-21-11,11>>^ E a multidão dizia: Este é Jesus, o Profeta de Nazaré da Galileia.

[[v40-21-12]]

^<<v40-21-12,12>>^ E entrou Jesus no templo de Deus, e expulsou todos os que vendiam e compravam no templo, e derribou as mesas dos cambistas e as cadeiras dos que vendiam pombas.

[[v40-21-13]]

^<<v40-21-13,13>>^ E disse-lhes: Está escrito: A minha casa será chamada casa de oração — mas vós a tendes convertido em covil de ladrões.

[[v40-21-14]]

^<<v40-21-14,14>>^ E foram ter com ele ao templo cegos e coxos, e curou-os.

[[v40-21-15]]

^<<v40-21-15,15>>^ Vendo então os principais dos sacerdotes e os escribas as maravilhas que fazia, e os meninos clamando no templo, Hosana ao Filho de Davi, indignaram-se,

[[v40-21-16]]

^<<v40-21-16,16>>^ E disseram-lhe: Ouves o que estes dizem? E Jesus lhes disse: Sim; nunca lestes: Pela boca dos meninos e das criancinhas de peito tiraste o perfeito louvor?

[[v40-21-17]]

^<<v40-21-17,17>>^ E, deixando-os, saiu da cidade para Betânia, e ali passou a noite.

[[v40-21-18]]

^<<v40-21-18,18>>^ E, de manhã, voltando para a cidade, teve fome;

[[v40-21-19]]

^<<v40-21-19,19>>^ E, avistando uma figueira perto do caminho, dirigiu-se a ela, e não achou nela senão folhas. E disse-lhe: Nunca mais nasça fruto de ti. E a figueira secou imediatamente.

[[v40-21-20]]

^<<v40-21-20,20>>^ E os discípulos, vendo isto , maravilharam-se, dizendo: Como secou imediatamente a figueira?

[[v40-21-21]]

^<<v40-21-21,21>>^ Jesus, porém, respondendo, disse-lhes: Em verdade vos digo que , se tiverdes fé e não duvidardes, não só fareis o que foi feito à figueira, mas até, se a este monte disserdes: Ergue-te e precipita-te no mar, assim  será feito;

[[v40-21-22]]

^<<v40-21-22,22>>^ E tudo o que pedirdes na oração, crendo, o  recebereis.

[[v40-21-23]]

^<<v40-21-23,23>>^ E, chegando ao templo, acercaram-se dele, estando já  ensinando, os príncipes dos sacerdotes e os anciãos do povo, dizendo: Com que autoridade fazes isto? e quem te deu tal autoridade?

[[v40-21-24]]

^<<v40-21-24,24>>^ E Jesus, respondendo, disse-lhes: Eu também vos perguntarei uma coisa: se ma disserdes, também eu vos direi com que autoridade faço isto.

[[v40-21-25]]

^<<v40-21-25,25>>^ O batismo de João donde era? Do céu, ou dos homens? E pensavam entre si, dizendo: Se dissermos: Do céu, ele nos dirá: Então por que não o crestes?

[[v40-21-26]]

^<<v40-21-26,26>>^ E, se dissermos: Dos homens, tememos o povo, porque todos consideram João como profeta.

[[v40-21-27]]

^<<v40-21-27,27>>^ E, respondendo a Jesus, disseram: Não sabemos. Ele disse-lhes: Nem eu vos digo com que autoridade faço isto.

[[v40-21-28]]

^<<v40-21-28,28>>^ Mas que vos parece? Um homem tinha dois filhos, e, dirigindo-se ao primeiro, disse: Filho, vai trabalhar hoje na minha vinha.

[[v40-21-29]]

^<<v40-21-29,29>>^ Ele, porém, respondendo, disse: Não quero. Mas depois, arrependendo-se, foi.

[[v40-21-30]]

^<<v40-21-30,30>>^ E, dirigindo-se ao segundo, falou-lhe de igual modo; e, respondendo ele, disse: Eu vou , senhor; e não foi.

[[v40-21-31]]

^<<v40-21-31,31>>^ Qual dos dois fez a vontade do pai? Disseram-lhe eles: O primeiro. Disse-lhes Jesus: Em verdade vos digo que os publicanos e as meretrizes entram adiante de vós no reino de Deus.

[[v40-21-32]]

^<<v40-21-32,32>>^ Porque João veio a vós no caminho de justiça, e não o crestes, mas os publicanos e as meretrizes o creram; vós, porém, vendo isto , nem depois vos arrependestes para o crer.

[[v40-21-33]]

^<<v40-21-33,33>>^ Ouvi ainda, outra parábola: Houve um homem, pai de família, que plantou uma vinha, e circundou-a de um valado, e construiu nela um  lagar, e edificou uma torre, e arrendou-a a uns lavradores, e ausentou-se para longe.

[[v40-21-34]]

^<<v40-21-34,34>>^ E, chegando o tempo dos frutos, enviou os seus servos aos lavradores, para receber os seus frutos.

[[v40-21-35]]

^<<v40-21-35,35>>^ E os lavradores, apoderando-se dos servos, feriram um, mataram outro, e apedrejaram outro.

[[v40-21-36]]

^<<v40-21-36,36>>^ Depois enviou outros servos, em maior número do que os primeiros; e eles fizeram-lhes o mesmo;

[[v40-21-37]]

^<<v40-21-37,37>>^ E por último enviou-lhes seu filho, dizendo: Terão respeito a meu filho.

[[v40-21-38]]

^<<v40-21-38,38>>^ Mas os lavradores, vendo o filho, disseram entre si: Este é o herdeiro; vinde, matemo-lo, e apoderemo-nos da sua herança.

[[v40-21-39]]

^<<v40-21-39,39>>^ E, lançando mão dele, o arrastaram para fora da vinha, e o  mataram.

[[v40-21-40]]

^<<v40-21-40,40>>^ Quando pois vier o Senhor da vinha, que fará àqueles lavradores?

[[v40-21-41]]

^<<v40-21-41,41>>^ Dizem-lhe eles: Dará afrontosa morte aos maus, e arrendará a vinha a outros lavradores, que a seu tempo lhe deem os frutos.

[[v40-21-42]]

^<<v40-21-42,42>>^ Diz-lhes Jesus: Nunca lestes nas Escrituras: A pedra, que os edificadores rejeitaram, essa foi posta por cabeça do ângulo; pelo Senhor foi feito isto, e é maravilhoso aos nossos olhos?

[[v40-21-43]]

^<<v40-21-43,43>>^ Portanto eu vos digo que o reino de Deus vos será tirado, e será dado a uma nação que dê os seus frutos.

[[v40-21-44]]

^<<v40-21-44,44>>^ E quem cair sobre esta pedra despedaçar-se-á; e aquele sobre quem ela cair ficará reduzido a pó.

[[v40-21-45]]

^<<v40-21-45,45>>^ E os príncipes dos sacerdotes e os fariseus, ouvindo estas palavras, entenderam que falava deles;

[[v40-21-46]]

^<<v40-21-46,46>>^ E, pretendendo prendê-lo, recearam o povo, porquanto o tinham por profeta.

'''

xref:040-mateus/040-mateus-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-mateus/040-mateus-022.adoc#v40-22-0[Próximo Capítulo &#62;]