include::./index.adoc[]

[[v40-27-0]]
=== Mateus, 27
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-27-1]]

^<<v40-27-1,1>>^ E, CHEGANDO a manhã, todos os príncipes dos sacerdotes, e os anciãos do povo, formavam juntamente conselho contra Jesus, para o matarem;

[[v40-27-2]]

^<<v40-27-2,2>>^ E manietando-o, o levaram e entregaram ao presidente Pôncio Pilatos.

[[v40-27-3]]

^<<v40-27-3,3>>^ Então Judas, o que o traíra, vendo que fora condenado, trouxe, arrependido, as trinta moedas  de prata aos príncipes dos sacerdotes e aos anciãos,

[[v40-27-4]]

^<<v40-27-4,4>>^ Dizendo: Pequei, traindo o sangue inocente. Eles, porém, disseram: Que nos importa? Isso é contigo.

[[v40-27-5]]

^<<v40-27-5,5>>^ E ele, atirando para o templo as moedas  de prata, retirou-se e foi-se enforcar.

[[v40-27-6]]

^<<v40-27-6,6>>^ E os príncipes dos sacerdotes, tomando as moedas  de prata, disseram: Não é lícito metê-las no cofre das ofertas, porque são preço de sangue.

[[v40-27-7]]

^<<v40-27-7,7>>^ E, tendo deliberado em conselho, compraram com elas o campo dum oleiro, para sepultura dos estrangeiros.

[[v40-27-8]]

^<<v40-27-8,8>>^ Por isso foi chamado aquele campo, até ao dia de  hoje, Campo de sangue.

[[v40-27-9]]

^<<v40-27-9,9>>^ Então se realizou o que vaticinara o profeta Jeremias: Tomaram as trinta moedas  de prata preço do que foi avaliado, que certos filhos d’Israel avaliaram.

[[v40-27-10]]

^<<v40-27-10,10>>^ E deram-nas pelo campo do oleiro, segundo o que o Senhor determinou.

[[v40-27-11]]

^<<v40-27-11,11>>^ E foi Jesus apresentado ao presidente, e o presidente o interrogou, dizendo: És tu o Rei dos judeus? E disse-lhe Jesus: Tu o  dizes.

[[v40-27-12]]

^<<v40-27-12,12>>^ E, sendo acusado pelos príncipes dos sacerdotes e pelos anciãos, nada respondeu.

[[v40-27-13]]

^<<v40-27-13,13>>^ Disse-lhe então Pilatos: Não ouves quanto testificam contra ti?

[[v40-27-14]]

^<<v40-27-14,14>>^ E nem uma palavra lhe respondeu, de sorte que o presidente estava muito maravilhado.

[[v40-27-15]]

^<<v40-27-15,15>>^ Ora, por ocasião  da festa, costumava o presidente soltar um preso, escolhendo o povo aquele que quisesse.

[[v40-27-16]]

^<<v40-27-16,16>>^ E tinham então um preso bem-conhecido, chamado Barrabás.

[[v40-27-17]]

^<<v40-27-17,17>>^ Portanto, estando eles reunidos, disse-lhes Pilatos: Qual quereis que vos solte? Barrabás, ou Jesus, chamado Cristo?

[[v40-27-18]]

^<<v40-27-18,18>>^ Porque sabia que por inveja o haviam entregado.

[[v40-27-19]]

^<<v40-27-19,19>>^ E, estando ele assentado no tribunal, sua mulher mandou-lhe dizer: Não entres na questão desse justo, porque num sonho muito sofri por causa dele.

[[v40-27-20]]

^<<v40-27-20,20>>^ Mas os príncipes dos sacerdotes e os anciãos persuadiram à multidão que pedisse Barrabás e matasse Jesus.

[[v40-27-21]]

^<<v40-27-21,21>>^ E, respondendo o presidente, disse-lhes: Qual desses dois quereis vós que eu solte? E eles disseram: Barrabás.

[[v40-27-22]]

^<<v40-27-22,22>>^ Disse-lhes Pilatos: Que farei então de Jesus, chamado Cristo? Disseram-lhe todos: Seja crucificado.

[[v40-27-23]]

^<<v40-27-23,23>>^ O presidente, porém, disse: Mas que mal fez ele? E eles mais clamavam, dizendo: Seja crucificado.

[[v40-27-24]]

^<<v40-27-24,24>>^ Então Pilatos, vendo que nada aproveitava, antes o tumulto crescia, tomando água, lavou as mãos diante da multidão, dizendo: Estou inocente do sangue deste justo: considerai isso.

[[v40-27-25]]

^<<v40-27-25,25>>^ E, respondendo todo o povo, disse: O seu sangue caia sobre nós e sobre nossos filhos.

[[v40-27-26]]

^<<v40-27-26,26>>^ Então soltou-lhes Barrabás, e, tendo mandado  açoitar a Jesus, entregou-o para ser crucificado.

[[v40-27-27]]

^<<v40-27-27,27>>^ E logo os soldados do presidente, conduzindo Jesus à audiência, reuniram junto dele toda a coorte.

[[v40-27-28]]

^<<v40-27-28,28>>^ E, despindo-o, o cobriram com uma capa de escarlate;

[[v40-27-29]]

^<<v40-27-29,29>>^ E, tecendo uma coroa de espinhos, puseram-lha na cabeça, e em sua mão  direita uma cana; e, ajoelhando diante dele, o escarneciam, dizendo: Salve, Rei dos judeus.

[[v40-27-30]]

^<<v40-27-30,30>>^ E, cuspindo nele, tiraram-lhe a cana, e batiam-lhe com  ela na cabeça.

[[v40-27-31]]

^<<v40-27-31,31>>^ E, depois de o haverem escarnecido, tiraram-lhe a capa, vestiram-lhe as suas vestes e o levaram para ser crucificado.

[[v40-27-32]]

^<<v40-27-32,32>>^ E, quando saíam, encontraram um homem cireneu, chamado Simão, a quem constrangeram a levar a sua cruz.

[[v40-27-33]]

^<<v40-27-33,33>>^ E, chegando ao lugar chamado Gólgota, que se diz: Lugar da Caveira,

[[v40-27-34]]

^<<v40-27-34,34>>^ Deram-lhe a beber vinho misturado com fel; mas ele, provando-o, não quis beber.

[[v40-27-35]]

^<<v40-27-35,35>>^ E, havendo- o  crucificado, repartiram os seus vestidos, lançando sortes, para que se cumprisse o que foi dito pelo profeta: Repartiram entre si os meus vestidos, e sobre a minha túnica lançaram sortes.

[[v40-27-36]]

^<<v40-27-36,36>>^ E, assentados, o guardavam ali.

[[v40-27-37]]

^<<v40-27-37,37>>^ E por cima da sua cabeça puseram escrita a sua acusação: Este É Jesus, O Rei dos Judeus .

[[v40-27-38]]

^<<v40-27-38,38>>^ E foram crucificados com ele dois salteadores, um à direita, e outro à esquerda.

[[v40-27-39]]

^<<v40-27-39,39>>^ E os que passavam blasfemavam dele, meneando as cabeças,

[[v40-27-40]]

^<<v40-27-40,40>>^ E dizendo: Tu, que destróis o templo, e em três dias o reedificas, salva-te a ti mesmo; se és Filho de Deus, desce da cruz.

[[v40-27-41]]

^<<v40-27-41,41>>^ E da mesma maneira também os príncipes dos sacerdotes, com os escribas, e anciãos, e fariseus, escarnecendo, diziam:

[[v40-27-42]]

^<<v40-27-42,42>>^ Salvou os outros, e a si mesmo não pode salvar-se. Se é o Rei d’Israel, desça agora da cruz, e creremos nele;

[[v40-27-43]]

^<<v40-27-43,43>>^ Confiou em Deus; livre-o agora, se o ama; porque disse: Sou Filho de Deus.

[[v40-27-44]]

^<<v40-27-44,44>>^ E o mesmo lhe lançaram também em rosto os salteadores que com ele estavam crucificados.

[[v40-27-45]]

^<<v40-27-45,45>>^ E desde a hora sexta houve trevas sobre toda a terra, até à hora nona.

[[v40-27-46]]

^<<v40-27-46,46>>^ E perto da hora nona exclamou Jesus em alta voz, dizendo: Eli, Eli, lama sabactâni, isto é, Deus meu, Deus meu, por que me desamparaste?

[[v40-27-47]]

^<<v40-27-47,47>>^ E alguns dos que ali estavam, ouvindo isto , diziam: Este chama por Elias.

[[v40-27-48]]

^<<v40-27-48,48>>^ E logo um deles, correndo, tomou uma esponja, e embebeu-a em vinagre, e, pondo- a  numa cana, dava-lhe de beber.

[[v40-27-49]]

^<<v40-27-49,49>>^ Os outros, porém, diziam: Deixa, vejamos se Elias vem livrá-lo.

[[v40-27-50]]

^<<v40-27-50,50>>^ E Jesus, clamando outra vez com grande voz, rendeu o espírito.

[[v40-27-51]]

^<<v40-27-51,51>>^ E eis que o véu do templo se rasgou em dois, de alto a baixo; e tremeu a terra, e fenderam-se as pedras.

[[v40-27-52]]

^<<v40-27-52,52>>^ E abriram-se os sepulcros, e muitos corpos de santos que dormiam foram ressuscitados;

[[v40-27-53]]

^<<v40-27-53,53>>^ E, saindo dos sepulcros, depois da ressurreição dele, entraram na cidade santa, e apareceram a muitos.

[[v40-27-54]]

^<<v40-27-54,54>>^ E o centurião e os que com ele guardavam a Jesus, vendo o terremoto, e as coisas  que haviam sucedido, tiveram grande temor, e  disseram: Verdadeiramente este era Filho de Deus.

[[v40-27-55]]

^<<v40-27-55,55>>^ E estavam ali, olhando de longe, muitas mulheres que tinham seguido Jesus desde a Galileia, para o servir;

[[v40-27-56]]

^<<v40-27-56,56>>^ Entre as quais estavam Maria Madalena, e Maria, mãe de Tiago e de José, e a mãe dos filhos de Zebedeu.

[[v40-27-57]]

^<<v40-27-57,57>>^ E, vinda já a tarde, chegou um homem rico de Arimateia, por nome José, que também era discípulo de Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ Este foi ter com Pilatos, e pediu-lhe o corpo de Jesus. Então Pilatos mandou que o corpo lhe  fosse dado.

[[v40-27-59]]

^<<v40-27-59,59>>^ E José, tomando o corpo, envolveu-o num fino e limpo lençol,

[[v40-27-60]]

^<<v40-27-60,60>>^ E o pôs no seu sepulcro novo, que havia aberto em rocha, e, rodando uma grande pedra para a porta do sepulcro, foi-se.

[[v40-27-61]]

^<<v40-27-61,61>>^ E estavam ali Maria Madalena e a outra Maria, assentadas defronte do sepulcro.

[[v40-27-62]]

^<<v40-27-62,62>>^ E no dia seguinte, que é o dia depois da Preparação, reuniram-se os príncipes dos sacerdotes e os fariseus em casa de Pilatos.

[[v40-27-63]]

^<<v40-27-63,63>>^ Dizendo: Senhor, lembramo-nos de que aquele enganador, vivendo ainda, disse: Depois de três dias ressuscitarei.

[[v40-27-64]]

^<<v40-27-64,64>>^ Manda pois que o sepulcro seja guardado com segurança até o terceiro dia, não se dê o caso que os seus discípulos vão de noite, e o furtem, e digam ao povo: Ressuscitou dos mortos; e assim  o último erro será pior do que o primeiro.

[[v40-27-65]]

^<<v40-27-65,65>>^ E disse-lhes Pilatos: Tendes a guarda; ide, guardai- o  como entenderdes.

[[v40-27-66]]

^<<v40-27-66,66>>^ E, indo eles, seguraram o sepulcro com a guarda, selando a pedra.

'''

xref:040-mateus/040-mateus-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-mateus/040-mateus-028.adoc#v40-28-0[Próximo Capítulo &#62;]