include::./index.adoc[]

[[v40-22-0]]
=== Mateus, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v40-22-1]]

^<<v40-22-1,1>>^ ENTÃO Jesus, tomando a palavra, tornou a falar-lhes em parábolas, dizendo:

[[v40-22-2]]

^<<v40-22-2,2>>^ O reino dos céus é semelhante a um certo rei que celebrou as bodas de seu filho;

[[v40-22-3]]

^<<v40-22-3,3>>^ E enviou os seus servos a chamar os convidados para as bodas; e estes não quiseram vir.

[[v40-22-4]]

^<<v40-22-4,4>>^ Depois enviou outros servos, dizendo: Dizei aos convidados: Eis que tenho o meu jantar preparado, os meus bois e cevados já  mortos, e tudo já  pronto; vinde às bodas.

[[v40-22-5]]

^<<v40-22-5,5>>^ Porém eles, não fazendo caso, foram, um para o seu campo, outro para o seu tráfico;

[[v40-22-6]]

^<<v40-22-6,6>>^ E os outros, apoderando-se dos servos, os ultrajaram e mataram.

[[v40-22-7]]

^<<v40-22-7,7>>^ E o rei, tendo notícias disto , encolerizou-se e, enviando os seus exércitos, destruiu aqueles homicidas, e incendiou a sua cidade.

[[v40-22-8]]

^<<v40-22-8,8>>^ Então diz aos servos: As bodas, na verdade, estão preparadas, mas os convidados não eram dignos.

[[v40-22-9]]

^<<v40-22-9,9>>^ Ide pois às saídas dos caminhos, e convidai para as bodas a todos os que encontrardes.

[[v40-22-10]]

^<<v40-22-10,10>>^ E os servos, saindo pelos caminhos, ajuntaram todos quantos encontraram, tanto maus como bons; e a festa nupcial foi cheia de convidados.

[[v40-22-11]]

^<<v40-22-11,11>>^ E o rei, entrando para ver os convidados, viu ali um homem que  não estava  trajado com vestido de núpcias.

[[v40-22-12]]

^<<v40-22-12,12>>^ E disse-lhe: Amigo, como entraste aqui, não tendo vestido nupcial? E ele emudeceu.

[[v40-22-13]]

^<<v40-22-13,13>>^ Disse então o rei aos servos: Amarrai-o de pés e mãos, levai-o, e lançai- o  nas trevas exteriores: ali haverá pranto e ranger de dentes.

[[v40-22-14]]

^<<v40-22-14,14>>^ Porque muitos são chamados, mas poucos escolhidos.

[[v40-22-15]]

^<<v40-22-15,15>>^ Então, retirando-se os fariseus, consultaram entre si como o surpreenderiam nalguma  palavra;

[[v40-22-16]]

^<<v40-22-16,16>>^ E enviaram-lhe os seus discípulos, com os herodianos, dizendo: Mestre, bem sabemos que és verdadeiro, e ensinas o caminho de Deus, segundo a verdade, e de ninguém se te dá, porque não olhas à aparência dos homens.

[[v40-22-17]]

^<<v40-22-17,17>>^ Dize-nos, pois, que te parece? É lícito pagar o tributo a César, ou não?

[[v40-22-18]]

^<<v40-22-18,18>>^ Jesus, porém, conhecendo a sua malícia, disse: Por que me experimentais, hipócritas?

[[v40-22-19]]

^<<v40-22-19,19>>^ Mostrai-me a moeda do tributo. E eles lhe apresentaram um dinheiro.

[[v40-22-20]]

^<<v40-22-20,20>>^ E ele diz-lhes: De quem é esta efígie e esta  inscrição?

[[v40-22-21]]

^<<v40-22-21,21>>^ Dizem-lhe eles: De César. Então ele lhes diz: Dai pois a César o que é  de César, e a Deus o que é  de Deus.

[[v40-22-22]]

^<<v40-22-22,22>>^ E eles, ouvindo isto , maravilharam-se, e, deixando-o, se retiraram.

[[v40-22-23]]

^<<v40-22-23,23>>^ No mesmo dia chegaram junto dele os saduceus, que dizem não haver ressurreição, e o interrogaram,

[[v40-22-24]]

^<<v40-22-24,24>>^ Dizendo: Mestre, Moisés disse: Se morrer alguém, não tendo filhos, casará o seu irmão com a mulher dele e suscitará descendência a seu irmão.

[[v40-22-25]]

^<<v40-22-25,25>>^ Ora houve entre nós sete irmãos; e o primeiro, tendo casado, morreu, e, não tendo descendência, deixou sua mulher a seu irmão.

[[v40-22-26]]

^<<v40-22-26,26>>^ Da mesma sorte o segundo, e o terceiro, até ao sétimo;

[[v40-22-27]]

^<<v40-22-27,27>>^ Por fim, depois de todos, morreu também a mulher.

[[v40-22-28]]

^<<v40-22-28,28>>^ Portanto, na ressurreição, de qual dos sete será a mulher, visto que todos a possuíram?

[[v40-22-29]]

^<<v40-22-29,29>>^ Jesus, porém, respondendo, disse-lhes: Errais, não conhecendo as Escrituras, nem o poder de Deus;

[[v40-22-30]]

^<<v40-22-30,30>>^ Porque na ressurreição nem casam nem são dados em casamento; mas serão como os anjos de Deus no céu.

[[v40-22-31]]

^<<v40-22-31,31>>^ E, acerca da ressurreição dos mortos, não tendes lido o que Deus vos declarou, dizendo:

[[v40-22-32]]

^<<v40-22-32,32>>^ Eu sou o Deus d’Abraão, o Deus d’Isaque e o Deus de Jacó? Ora Deus não é Deus dos mortos, mas dos vivos.

[[v40-22-33]]

^<<v40-22-33,33>>^ E, as turbas, ouvindo isto , ficaram maravilhadas da sua doutrina.

[[v40-22-34]]

^<<v40-22-34,34>>^ E os fariseus, ouvindo que ele fizera emudecer os saduceus, reuniram-se no mesmo lugar;

[[v40-22-35]]

^<<v40-22-35,35>>^ E um deles, doutor da lei, interrogou-o para o experimentar, dizendo:

[[v40-22-36]]

^<<v40-22-36,36>>^ Mestre, qual é  o grande mandamento na lei?

[[v40-22-37]]

^<<v40-22-37,37>>^ E Jesus disse-lhe: Amarás o Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todo o teu pensamento.

[[v40-22-38]]

^<<v40-22-38,38>>^ Este é o primeiro e grande mandamento.

[[v40-22-39]]

^<<v40-22-39,39>>^ E o segundo semelhante a este, é : Amarás o teu próximo como a ti mesmo.

[[v40-22-40]]

^<<v40-22-40,40>>^ Destes dois mandamentos depende toda a lei e os profetas.

[[v40-22-41]]

^<<v40-22-41,41>>^ E, estando reunidos os fariseus, interrogou-os Jesus,

[[v40-22-42]]

^<<v40-22-42,42>>^ Dizendo: Que pensais vós do Cristo? De quem é filho? Eles disseram-lhe: De Davi.

[[v40-22-43]]

^<<v40-22-43,43>>^ Disse-lhes ele: Como é então que Davi, em espírito, lhe chama Senhor, dizendo:

[[v40-22-44]]

^<<v40-22-44,44>>^ Disse o Senhor ao meu Senhor: Assenta-te à minha direita até que eu ponha os teus inimigos por escabelo de teus pés.

[[v40-22-45]]

^<<v40-22-45,45>>^ Se Davi pois lhe chama Senhor, como é seu filho?

[[v40-22-46]]

^<<v40-22-46,46>>^ E ninguém podia responder-lhe uma  palavra: nem desde aquele dia ousou mais alguém interrogá-lo.

'''

xref:040-mateus/040-mateus-021.adoc#v40-21-0[&#60; Capítulo Anterior] | <<v40-22-0,Topo>> | xref:040-mateus/040-mateus-023.adoc#v40-23-0[Próximo Capítulo &#62;]