include::./index.adoc[]

[[v22-5-0]]
=== Cânticos, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v22-5-1]]

^<<v22-5-1,1>>^ JÁ vim para o meu jardim, irmã minha, minha esposa: colhi a minha mirra com a minha especiaria, comi o meu favo com o meu mel, bebi o meu vinho com o meu leite: comei, amigos, bebei abundantemente, ó amados.

[[v22-5-2]]

^<<v22-5-2,2>>^ Eu dormia, mas o meu coração velava: eis  a voz do meu amado, que estava batendo: abre-me, irmã minha, amiga minha, pomba minha, minha imaculada, porque a minha cabeça está  cheia de orvalho, os meus cabelos das gotas da noite:

[[v22-5-3]]

^<<v22-5-3,3>>^ Já  despi os meus vestidos; como os tornarei a vestir? já  lavei os meus pés; como os tornarei a sujar?

[[v22-5-4]]

^<<v22-5-4,4>>^ O meu amado meteu a sua mão pela fresta da porta , e as minhas entranhas estremeceram por amor dele.

[[v22-5-5]]

^<<v22-5-5,5>>^ Eu me levantei para abrir ao meu amado, e as minhas mãos destilavam mirra, e os meus dedos gotejavam  mirra sobre as aldravas da fechadura.

[[v22-5-6]]

^<<v22-5-6,6>>^ Eu abri ao meu amado, mas já o meu amado se tinha retirado, e  se tinha ido: a minha alma tinha-se derretido quando ele falara; busquei-o e não o achei; chamei-o, e não me respondeu.

[[v22-5-7]]

^<<v22-5-7,7>>^ Acharam-me os guardas que rondavam pela cidade: espancaram-me, feriram-me; tiraram-me o meu manto os guardas dos muros.

[[v22-5-8]]

^<<v22-5-8,8>>^ Conjuro-vos, ó filhas de Jerusalém, que, se achardes o meu amado, lhe digais que estou  enferma de amor.

[[v22-5-9]]

^<<v22-5-9,9>>^ Que é  o teu amado mais do que outro  amado, ó tu, a mais formosa entre as mulheres? que é o teu amado mais do que outro  amado, que tanto nos conjuraste.

[[v22-5-10]]

^<<v22-5-10,10>>^ O meu amado é  cândido e rubicundo; ele traz a bandeira entre dez mil.

[[v22-5-11]]

^<<v22-5-11,11>>^ A sua cabeça é como  o ouro mais apurado, os seus cabelos são crespos, pretos como o corvo.

[[v22-5-12]]

^<<v22-5-12,12>>^ Os seus olhos são  como os das pombas junto às correntes das águas, lavados em leite, postos em engaste.

[[v22-5-13]]

^<<v22-5-13,13>>^ As suas faces são  como um  canteiro de bálsamo, como  colinas de ervas aromáticas; os seus lábios são como lírios que gotejam mirra.

[[v22-5-14]]

^<<v22-5-14,14>>^ As suas mãos são como  anéis de ouro que têm engastadas as turquesas; o seu ventre como  alvo marfim, coberto de safiras.

[[v22-5-15]]

^<<v22-5-15,15>>^ As suas pernas como  colunas de mármore, fundadas sobre bases de ouro puro; o seu parecer como o Líbano, excelente como os cedros.

[[v22-5-16]]

^<<v22-5-16,16>>^ O seu falar é muitíssimo suave; sim, ele é totalmente desejável. Tal é o meu amado, e tal o meu amigo, ó filhas de Jerusalém.

'''

xref:022-canticos/022-canticos-004.adoc#v22-4-0[&#60; Capítulo Anterior] | <<v22-5-0,Topo>> | xref:022-canticos/022-canticos-006.adoc#v22-6-0[Próximo Capítulo &#62;]