include::./index.adoc[]

[[v22-2-0]]
=== Cânticos, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v22-2-1]]

^<<v22-2-1,1>>^ EU sou  a rosa de Sarom, o lírio dos vales.

[[v22-2-2]]

^<<v22-2-2,2>>^ Qual o lírio entre os espinhos, tal é a minha amiga entre as filhas.

[[v22-2-3]]

^<<v22-2-3,3>>^ Qual a macieira entre as árvores do bosque tal é  o meu amado entre os filhos: desejo muito a sua sombra, e debaixo dela  me assento; e o seu fruto é  doce ao meu paladar.

[[v22-2-4]]

^<<v22-2-4,4>>^ Levou-me à sala do banquete, e o seu estandarte em mim era o amor.

[[v22-2-5]]

^<<v22-2-5,5>>^ Sustentai-me com passas, confortai-me com maçãs, porque desfaleço de amor.

[[v22-2-6]]

^<<v22-2-6,6>>^ A sua mão  esquerda esteja  debaixo da minha cabeça, e a sua mão  direita me abrace.

[[v22-2-7]]

^<<v22-2-7,7>>^ Conjuro-vos, ó filhas de Jerusalém, pelas gazelas e cervas do campo, que não acordeis nem desperteis o meu  amor, até que queira.

[[v22-2-8]]

^<<v22-2-8,8>>^ Esta  é a voz do meu amado: ei-lo aí, que já  vem saltando sobre os montes, pulando sobre os outeiros.

[[v22-2-9]]

^<<v22-2-9,9>>^ O meu amado é  semelhante ao gamo, ou ao filho do veado: eis que está detrás da nossa parede, olhando pelas janelas, reluzindo pelas grades.

[[v22-2-10]]

^<<v22-2-10,10>>^ O meu amado fala e me diz: Levanta-te, amiga minha, formosa minha, e vem.

[[v22-2-11]]

^<<v22-2-11,11>>^ Porque eis que passou o inverno: a chuva cessou, e  se foi:

[[v22-2-12]]

^<<v22-2-12,12>>^ Aparecem as flores na terra, o tempo de cantar chega, e a voz da rola ouve-se em nossa terra:

[[v22-2-13]]

^<<v22-2-13,13>>^ A figueira já deu os seus figuinhos, e as vides em flor exalam o seu aroma: levanta-te, amiga minha, formosa minha, e vem.

[[v22-2-14]]

^<<v22-2-14,14>>^ Pomba minha, que andas pelas fendas das penhas, no oculto das ladeiras, mostra-me a tua face, faze-me ouvir a tua voz, porque a tua voz é  doce e a tua face aprazível.

[[v22-2-15]]

^<<v22-2-15,15>>^ Apanhai-me as raposas, as raposinhas, que fazem mal às vinhas, porque as nossas vinhas estão  em flor.

[[v22-2-16]]

^<<v22-2-16,16>>^ O meu amado é  meu, e eu sou  dele: ele apascenta o seu rebanho entre os lírios.

[[v22-2-17]]

^<<v22-2-17,17>>^ Antes que refresque o dia, e caiam as sombras, volta, amado meu: faze-te semelhante ao gamo ou ao filho dos veados sobre os montes de Beter.

'''

xref:022-canticos/022-canticos-001.adoc#v22-1-0[&#60; Capítulo Anterior] | <<v22-2-0,Topo>> | xref:022-canticos/022-canticos-003.adoc#v22-3-0[Próximo Capítulo &#62;]