include::./index.adoc[]

[[v17-9-0]]
=== Ester, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v17-9-1]]

^<<v17-9-1,1>>^ E NO mês duodécimo, que é  o mês de adar, no dia treze do mesmo mês  em que chegou a palavra do rei e a sua ordem para se executar, no dia em que os inimigos dos judeus esperavam assenhorear-se deles, sucedeu o contrário, porque os judeus foram os que se assenhorearam dos seus aborrecedores.

[[v17-9-2]]

^<<v17-9-2,2>>^ Porque  os judeus nas suas cidades, em todas as províncias do rei Assuero, se ajuntaram para pôr as mãos naqueles que procuravam o seu mal; e nenhum podia resistir-lhes, porque o seu terror caiu sobre todos aqueles povos.

[[v17-9-3]]

^<<v17-9-3,3>>^ E todos os maiorais das províncias, e os sátrapas, e os governadores, e os que faziam a obra do rei, auxiliavam os judeus porque tinha caído sobre eles o temor de Mardoqueu.

[[v17-9-4]]

^<<v17-9-4,4>>^ Porque Mardoqueu era  grande na casa do rei, e a sua fama saía por todas as províncias; porque o homem Mardoqueu se ia engrandecendo.

[[v17-9-5]]

^<<v17-9-5,5>>^ Feriram pois os judeus a todos os seus inimigos, a golpes de espada, e com matança e com destruição; e fizeram dos seus aborrecedores o que quiseram.

[[v17-9-6]]

^<<v17-9-6,6>>^ E na fortaleza de Susã mataram e destruíram os judeus quinhentos homens;

[[v17-9-7]]

^<<v17-9-7,7>>^ Como também a Parsandata, e a Dalfom, e a Aspata,

[[v17-9-8]]

^<<v17-9-8,8>>^ E a Porata, e a Adália, e a Aridata,

[[v17-9-9]]

^<<v17-9-9,9>>^ E a Farmasta, e a Arisai, e a Aridai, e a Vaizata:

[[v17-9-10]]

^<<v17-9-10,10>>^ Os dez filhos de Hamã, filho de Hamedata, inimigo dos judeus, foram mortos; porém ao despojo não estenderam a sua mão.

[[v17-9-11]]

^<<v17-9-11,11>>^ No mesmo dia veio perante o rei o número dos mortos na fortaleza de Susã.

[[v17-9-12]]

^<<v17-9-12,12>>^ E disse o rei à rainha Ester: Na fortaleza de Susã mataram e destruíram os judeus quinhentos homens, e os dez filhos de Hamã; nas mais províncias do rei que fariam? Qual é pois a tua petição? E dar-se-te-á. Ou qual é ainda o teu requerimento? E far-se-á.

[[v17-9-13]]

^<<v17-9-13,13>>^ Então disse Ester: Se bem parecer ao rei, conceda-se também amanhã aos judeus que se acham  em Susã que façam conforme ao mandado de hoje; e enforquem os dez filhos de Hamã numa  forca.

[[v17-9-14]]

^<<v17-9-14,14>>^ Então disse o rei que assim se fizesse: e publicou-se um  edito em Susã, e enforcaram os dez filhos de Hamã.

[[v17-9-15]]

^<<v17-9-15,15>>^ E reuniram-se os judeus que se achavam  em Susã também no dia catorze do mês de adar, e mataram em Susã a trezentos homens; porém ao despojo não estenderam a sua mão.

[[v17-9-16]]

^<<v17-9-16,16>>^ Também os demais judeus que se achavam nas províncias do rei se reuniram para se porem em defesa da sua vida, e tiveram repouso dos seus inimigos; e mataram dos seus aborrecedores setenta e cinco mil; porém ao despojo não estenderam a sua mão.

[[v17-9-17]]

^<<v17-9-17,17>>^ Sucedeu  isto no dia treze do mês de adar; e repousaram no dia catorze do mesmo, e fizeram daquele dia  dia de banquetes e de alegria.

[[v17-9-18]]

^<<v17-9-18,18>>^ Também os judeus, que se achavam  em Susã se ajuntaram nos dias treze e catorze do mesmo; e repousaram no dia quinze do mesmo, e fizeram daquele dia  dia de banquetes e de alegria.

[[v17-9-19]]

^<<v17-9-19,19>>^ E também os judeus das aldeias, que habitavam nas vilas, fizeram do dia  catorze do mês de adar dia de alegria e de banquetes, e dia de folguedo, e de mandarem presentes uns aos outros.

[[v17-9-20]]

^<<v17-9-20,20>>^ E Mardoqueu escreveu estas cousas, e enviou cartas a todos os judeus que se achavam  em todas as províncias do rei Assuero, aos de perto, e aos de longe,

[[v17-9-21]]

^<<v17-9-21,21>>^ Ordenando-lhes que guardassem o dia catorze do mês de adar, e o dia quinze do mesmo, todos os anos.

[[v17-9-22]]

^<<v17-9-22,22>>^ Como os dias em que os judeus tiveram repouso dos seus inimigos; e o mês que se lhes mudou de tristeza em alegria, e de luto em dia de folguedo; para que os fizessem dias de banquetes e de alegria, e de mandarem presentes uns aos outros, e dádivas aos pobres.

[[v17-9-23]]

^<<v17-9-23,23>>^ E se encarregaram os judeus de fazerem o que já  tinham começado, como também o que Mardoqueu lhes tinha escrito.

[[v17-9-24]]

^<<v17-9-24,24>>^ Porque Hamã, filho de Hamedata, o agagita, inimigo de todos os judeus, tinha intentado destruir os judeus; e tinha lançado Pur, isto é a sorte para os assolar e destruir.

[[v17-9-25]]

^<<v17-9-25,25>>^ Mas, vindo isto perante o rei, mandou ele por cartas que o seu mau intento, que intentara contra os judeus, se tornasse sobre a sua cabeça; pelo que o enforcaram a ele e a seus filhos numa forca.

[[v17-9-26]]

^<<v17-9-26,26>>^ Por isso àqueles dias chamam purim, do nome Pur; pelo que também  por causa de  todas as palavras daquela carta, e do que viram sobre isso, e do que lhes tinha sucedido,

[[v17-9-27]]

^<<v17-9-27,27>>^ Confirmaram os judeus, e tomaram sobre si, e sobre a sua semente, e sobre todos os que se achegassem a eles, que não se deixaria de guardar estes dois dias conforme ao que se escrevera deles, segundo o seu tempo determinado, todos os anos.

[[v17-9-28]]

^<<v17-9-28,28>>^ E que estes dias seriam lembrados e guardados por cada geração, família, província, e cidade, e que estes dias de purim se celebrariam entre os judeus, e que a memória deles nunca teria fim entre os de sua semente.

[[v17-9-29]]

^<<v17-9-29,29>>^ Depois disto, escreveu a rainha Ester, filha de Abigail, e Mardoqueu o judeu, com toda a força, para confirmarem segunda vez esta carta de purim.

[[v17-9-30]]

^<<v17-9-30,30>>^ E mandaram cartas a todos os judeus, às cento e vinte e sete províncias do reino de Assuero, com palavras de paz e fidelidade.

[[v17-9-31]]

^<<v17-9-31,31>>^ Para confirmarem estes dias de purim nos seus tempos determinados , como Mardoqueu, o judeu, e a rainha Ester lhes tinham estabelecido, e como eles mesmos já  o tinham estabelecido sobre si e sobre a sua semente, acerca do jejum e do seu clamor.

[[v17-9-32]]

^<<v17-9-32,32>>^ E o mandado de Ester estabeleceu o que respeitava ao purim; e escreveu-se n um  livro.

'''

xref:017-ester/017-ester-008.adoc#v17-8-0[&#60; Capítulo Anterior] | <<v17-9-0,Topo>> | xref:017-ester/017-ester-010.adoc#v17-10-0[Próximo Capítulo &#62;]