include::./index.adoc[]

[[v17-8-0]]
=== Ester, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v17-8-1]]

^<<v17-8-1,1>>^ NAQUELE mesmo dia deu o rei Assuero à rainha Ester a casa de Hamã, inimigo dos judeus; e Mardoqueu veio perante o rei; porque Ester tinha declarado o que lhe era.

[[v17-8-2]]

^<<v17-8-2,2>>^ E tirou o rei o seu anel, que tinha tomado a Hamã, e o deu a Mardoqueu. E Ester pôs a Mardoqueu sobre a casa de Hamã.

[[v17-8-3]]

^<<v17-8-3,3>>^ Falou mais Ester perante o rei, e se lhe lançou aos pés; e chorou, e lhe suplicou que revogasse a maldade de Hamã, o agagita, e o seu intento que tinha intentado contra os judeus.

[[v17-8-4]]

^<<v17-8-4,4>>^ E estendeu o rei para Ester o cetro de ouro. Então Ester se levantou, e se pôs em pé perante o rei,

[[v17-8-5]]

^<<v17-8-5,5>>^ E disse: Se bem parecer ao rei, e se eu achei graça perante ele, e se  este negócio é reto diante do rei, e se  eu lhe agrado aos seus olhos, escreva-se que se revoguem as cartas e o intento de Hamã filho de Hamedata, o agagita, as quais ele escreveu para lançar a perder os judeus, que há  em todas as províncias do rei.

[[v17-8-6]]

^<<v17-8-6,6>>^ Por que como poderei ver o mal que sobrevirá ao meu povo? E como poderei ver a perdição da minha geração?

[[v17-8-7]]

^<<v17-8-7,7>>^ Então disse o rei Assuero à rainha Ester e ao judeu Mardoqueu: Eis que dei a Ester a casa de Hamã, e a ele enforcaram numa forca, porquanto quisera  pôr as mãos nos judeus.

[[v17-8-8]]

^<<v17-8-8,8>>^ Escrevei pois aos judeus, como parecer  bem aos vossos olhos, e em nome do rei, e selai-o com o anel do rei; porque a escritura que se escreve em nome do rei, e se sela com o anel do rei, não é para revogar.

[[v17-8-9]]

^<<v17-8-9,9>>^ Então foram chamados os escrivães do rei, naquele mesmo tempo, e no mês terceiro (que é o mês de sivã), aos vinte e três do mesmo, e se escreveu conforme a tudo quanto ordenou Mardoqueu aos judeus, como também aos sátrapas, e aos governadores, e aos maiorais das províncias que se estendem  da Índia até à Etiópia, cento e vinte e sete províncias, a cada província segundo a sua escritura, e a cada povo conforme a sua língua; como também aos judeus segundo a sua escritura, e conforme a sua língua.

[[v17-8-10]]

^<<v17-8-10,10>>^ E se escreveu em nome do rei Assuero, e se selou com o anel do rei: e se enviaram as cartas pela mão de correios a cavalo, e que cavalgavam sobre ginetes, que eram das cavalariças do rei.

[[v17-8-11]]

^<<v17-8-11,11>>^ Nelas o rei concedia aos judeus, que havia em cada cidade, que se reunissem, e se dispusessem para defenderem as suas vidas, e para destruírem, matarem e assolarem a todas as forças do povo e província que com eles apertassem, crianças e mulheres, e que se saqueassem os seus despojos,

[[v17-8-12]]

^<<v17-8-12,12>>^ Num mesmo dia, em todas as províncias do rei Assuero, no dia  treze do duodécimo mês, que é o mês de adar.

[[v17-8-13]]

^<<v17-8-13,13>>^ E uma cópia da carta, que uma ordem se anunciaria em todas as províncias, foi enviada a todos os povos, para que os judeus estivessem preparados para aquele dia, para se vingarem dos seus inimigos.

[[v17-8-14]]

^<<v17-8-14,14>>^ Os correios sobre ginetes das cavalariças do rei apressuradamente saíram, impelidos pela palavra do rei: e foi publicada esta ordem na fortaleza de Susã.

[[v17-8-15]]

^<<v17-8-15,15>>^ Então Mardoqueu saiu da presença do rei com um vestido real azul celeste e branco, como também com uma grande coroa de ouro, e com uma capa de linho fino e púrpura, e a cidade de Susã exultou e se alegrou.

[[v17-8-16]]

^<<v17-8-16,16>>^ E  para os judeus houve luz, e alegria, e gozo, e honra.

[[v17-8-17]]

^<<v17-8-17,17>>^ Também em toda a província, e em toda a cidade, aonde chegava a palavra do rei e a sua ordem, havia entre os judeus alegria, e gozo, banquetes e dias de folguedo; e muitos, entre os povos da terra, se fizeram judeus; porque o temor dos judeus tinha caído sobre eles.

'''

xref:017-ester/017-ester-007.adoc#v17-7-0[&#60; Capítulo Anterior] | <<v17-8-0,Topo>> | xref:017-ester/017-ester-009.adoc#v17-9-0[Próximo Capítulo &#62;]