include::./index.adoc[]

[[v3-2-0]]
=== Levítico, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v3-2-1]]

^<<v3-2-1,1>>^ E QUANDO alguma  pessoa oferecer oferta de manjares ao Senhor, a sua oferta será de  flor de farinha, e nela deitará azeite, e porá o incenso sobre ela;

[[v3-2-2]]

^<<v3-2-2,2>>^ E a trará aos filhos de Aarão, os sacerdotes, um  dos quais tomará dela um punhado da flor de farinha, e do seu azeite com todo o seu incenso: e o sacerdote queimará este memorial sobre o altar: oferta queimada é de cheiro suave ao Senhor.

[[v3-2-3]]

^<<v3-2-3,3>>^ E o que sobejar da oferta de manjares, será  de Aarão, e de seus filhos: cousa santíssima é, de ofertas queimadas ao Senhor.

[[v3-2-4]]

^<<v3-2-4,4>>^ E, quando ofereceres oferta de manjares, cozida no forno, será  de bolos asmos de flor de farinha, amassados com azeite, e coscorões asmos untados com azeite.

[[v3-2-5]]

^<<v3-2-5,5>>^ E se a tua oferta for  oferta de manjares, cozida  na caçoula, será da flor de farinha sem fermento, amassada com azeite.

[[v3-2-6]]

^<<v3-2-6,6>>^ Em pedaços a partirás, e sobre ela deitarás azeite; oferta é  de manjares.

[[v3-2-7]]

^<<v3-2-7,7>>^ E se a tua oferta for  oferta de manjares da sertã, far-se-á da flor de farinha com azeite.

[[v3-2-8]]

^<<v3-2-8,8>>^ Então trarás a oferta de manjares, que se fará daquilo, ao Senhor; e se apresentará ao sacerdote, o qual a levará ao altar.

[[v3-2-9]]

^<<v3-2-9,9>>^ E o sacerdote tomará daquela oferta de manjares o seu memorial, e a queimará sobre o altar; oferta queimada é  de cheiro suave ao Senhor.

[[v3-2-10]]

^<<v3-2-10,10>>^ E o que sobejar da oferta de manjares será  de Aarão e de seus filhos: cousa santíssima é  de ofertas queimadas ao Senhor.

[[v3-2-11]]

^<<v3-2-11,11>>^ Nenhuma oferta de manjares, que oferecerdes ao Senhor, se fará com fermento; porque de nenhum fermento, nem de mel algum, oferecereis oferta queimada ao Senhor.

[[v3-2-12]]

^<<v3-2-12,12>>^ Deles oferecereis ao Senhor por oferta das primícias; porém sobre o altar não subirão por cheiro suave.

[[v3-2-13]]

^<<v3-2-13,13>>^ E toda a oferta dos teus manjares salgarás com sal; e não deixarás faltar à tua oferta de manjares o sal do concerto do teu Deus: em toda a tua oferta oferecerás sal.

[[v3-2-14]]

^<<v3-2-14,14>>^ E se ofereceres ao Senhor oferta de manjares das primícias, oferecerás a oferta de manjares das tuas primícias de espigas verdes tostadas ao fogo; isto é , do grão trilhado de espigas verdes cheias.

[[v3-2-15]]

^<<v3-2-15,15>>^ E sobre ela deitarás azeite, e porás sobre ela incenso; oferta é de manjares.

[[v3-2-16]]

^<<v3-2-16,16>>^ Assim o sacerdote queimará o seu memorial do seu grão trilhado, e do seu azeite, com todo o seu incenso: oferta queimada é  ao Senhor.

'''

xref:003-levitico/003-levitico-001.adoc#v3-1-0[&#60; Capítulo Anterior] | <<v3-2-0,Topo>> | xref:003-levitico/003-levitico-003.adoc#v3-3-0[Próximo Capítulo &#62;]