include::./index.adoc[]

[[v3-26-0]]
=== Levítico, 26
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v3-26-1]]

^<<v3-26-1,1>>^ NÃO fareis para vós ídolos, nem vos levantareis imagem de escultura nem estátua, nem poreis figura de pedra na vossa terra, para inclinar-vos a ela: porque eu sou  o Senhor vosso Deus.

[[v3-26-2]]

^<<v3-26-2,2>>^ Guardareis os meus sábados, e reverenciareis o meu santuário: eu sou  o Senhor.

[[v3-26-3]]

^<<v3-26-3,3>>^ Se andardes nos meus estatutos e guardardes os meus mandamentos, e os fizerdes,

[[v3-26-4]]

^<<v3-26-4,4>>^ Então eu vos darei as vossas chuvas a seu tempo; e a terra dará a sua novidade, e a árvore do campo dará o seu fruto:

[[v3-26-5]]

^<<v3-26-5,5>>^ E a debulha se vos chegará à vindima, e a vindima se chegará à sementeira: e comereis o vosso pão a fartar, e habitareis seguros na vossa terra.

[[v3-26-6]]

^<<v3-26-6,6>>^ Também darei paz na terra, e dormireis seguros , e não haverá quem vos  espante: e farei cessar os animais nocivos da terra, e pela vossa terra não passará espada.

[[v3-26-7]]

^<<v3-26-7,7>>^ E perseguireis os vossos inimigos, e cairão à espada diante de vós.

[[v3-26-8]]

^<<v3-26-8,8>>^ Cinco de vós perseguirão um cento, e cem de vós perseguirão dez mil; e os vossos inimigos cairão à espada diante de vós.

[[v3-26-9]]

^<<v3-26-9,9>>^ E para vós olharei, e vos farei frutificar, e vos multiplicarei, e confirmarei o meu concerto convosco.

[[v3-26-10]]

^<<v3-26-10,10>>^ E comereis o depósito velho, depois de envelhecido; e tirareis fora o velho por causa do novo.

[[v3-26-11]]

^<<v3-26-11,11>>^ E porei o meu tabernáculo no meio de vós, e a minha alma de vós não se enfadará.

[[v3-26-12]]

^<<v3-26-12,12>>^ E andarei no meio de vós, e eu vos serei por Deus, e vós me sereis por povo.

[[v3-26-13]]

^<<v3-26-13,13>>^ Eu sou  o Senhor vosso Deus, que vos tirei da terra dos egípcios, para que não fôsseis seus escravos: e quebrei os timões do vosso jugo, e vos fiz andar direitos.

[[v3-26-14]]

^<<v3-26-14,14>>^ Mas, se me não ouvirdes, e não fizerdes todos estes mandamentos,

[[v3-26-15]]

^<<v3-26-15,15>>^ E se rejeitardes os meus estatutos, e a vossa alma se enfadar dos meus juízos, não cumprindo todos os meus mandamentos, para invalidar o meu concerto,

[[v3-26-16]]

^<<v3-26-16,16>>^ Então eu também vos farei isto: Porei sobre vós terror, a tísica e a febre ardente, que consumam os olhos e atormentem a alma: e semeareis debalde a vossa semente, e os vossos inimigos a comerão.

[[v3-26-17]]

^<<v3-26-17,17>>^ E porei a minha face contra vós, e sereis feridos diante de vossos inimigos; e os que vos aborrecerem de vós se assenhorearão, e fugireis, sem ninguém vos perseguir.

[[v3-26-18]]

^<<v3-26-18,18>>^ E, se ainda com estas cousas não me ouvirdes, então eu prosseguirei em castigar-vos sete vezes mais  por causa dos  vossos pecados.

[[v3-26-19]]

^<<v3-26-19,19>>^ Porque quebrantarei a soberba da vossa força; e farei que os vossos céus sejam  como ferro e a vossa terra como cobre.

[[v3-26-20]]

^<<v3-26-20,20>>^ E debalde se gastará a vossa força: a vossa terra não dará a sua novidade, e as árvores da terra não darão o seu fruto.

[[v3-26-21]]

^<<v3-26-21,21>>^ E se andardes contrariamente para comigo, e não me quiserdes ouvir, trazer-vos-ei praga sete vezes mais , conforme aos vossos pecados.

[[v3-26-22]]

^<<v3-26-22,22>>^ Porque enviarei entre vós as feras do campo, as quais vos desfilharão, e desfarão o vosso gado, e vos apoucarão; e os vossos caminhos serão desertos.

[[v3-26-23]]

^<<v3-26-23,23>>^ Se ainda com estas cousas não fordes restaurados por mim, mas ainda  andardes contrariamente comigo,

[[v3-26-24]]

^<<v3-26-24,24>>^ Eu também convosco andarei contrariamente, e eu, mesmo eu, vos ferirei sete vezes mais  por causa dos vossos pecados.

[[v3-26-25]]

^<<v3-26-25,25>>^ Porque trarei sobre vós a espada, que executará a vingança do concerto; e ajuntados estareis nas vossas cidades: então enviarei a peste entre vós, e sereis entregues na mão do inimigo.

[[v3-26-26]]

^<<v3-26-26,26>>^ Quando eu vos quebrantar o sustento do pão, então dez mulheres cozerão o vosso pão num forno, e tornar-vos-ão o vosso pão por peso e comereis, mas não vos fartareis.

[[v3-26-27]]

^<<v3-26-27,27>>^ E se com isto me não ouvirdes, mas ainda  andardes contrariamente comigo,

[[v3-26-28]]

^<<v3-26-28,28>>^ Também eu convosco andarei contrariamente em furor; e vos castigarei sete vezes mais  por causa dos  vossos pecados.

[[v3-26-29]]

^<<v3-26-29,29>>^ Porque comereis a carne de vossos filhos, e a carne de vossas filhas comereis.

[[v3-26-30]]

^<<v3-26-30,30>>^ E destruirei os vossos altos, e desfarei as vossas imagens do sol, e lançarei os vossos cadáveres sobre os cadáveres dos vossos deuses; a minha alma se enfadará de vós.

[[v3-26-31]]

^<<v3-26-31,31>>^ E porei as vossas cidades por deserto, e assolarei os vossos santuários, e não cheirarei o vosso cheiro suave.

[[v3-26-32]]

^<<v3-26-32,32>>^ E assolarei a terra, e se espantarão disso os vossos inimigos que nela morarem.

[[v3-26-33]]

^<<v3-26-33,33>>^ E vos espalharei entre as nações, e desembainharei a espada atrás de vós; e a vossa terra será assolada, e as vossas cidades serão desertas.

[[v3-26-34]]

^<<v3-26-34,34>>^ Então a terra folgará nos seus sábados, todos os dias da sua assolação, e vós estareis  na terra dos vossos inimigos; então a terra descansará, e folgará nos seus sábados.

[[v3-26-35]]

^<<v3-26-35,35>>^ Todos os dias da assolação descansará, porque não descansou nos vossos sábados, quando habitáveis nela.

[[v3-26-36]]

^<<v3-26-36,36>>^ E, quanto aos que de vós ficarem, eu meterei tal pavor nos seus corações, nas terras dos seus inimigos, que o sonido duma folha movida os perseguirá; e fugirão como  quem foge da espada; e cairão sem ninguém os perseguir.

[[v3-26-37]]

^<<v3-26-37,37>>^ E cairão uns sobre os outros como diante da espada, sem ninguém os perseguir; e não podereis parar diante dos vossos inimigos.

[[v3-26-38]]

^<<v3-26-38,38>>^ E perecereis entre as gentes, e a terra dos vossos inimigos vos consumirá.

[[v3-26-39]]

^<<v3-26-39,39>>^ E aqueles que entre vós ficarem se derreterão pela sua iniquidade nas terras dos vossos inimigos, e pela iniquidade de seus pais com eles se derreterão.

[[v3-26-40]]

^<<v3-26-40,40>>^ Então confessarão a sua iniquidade, e a iniquidade de seus pais, com as suas transgressões, com que transgrediram contra mim; como também que andaram contrariamente para comigo.

[[v3-26-41]]

^<<v3-26-41,41>>^ Eu também andei com eles contrariamente, e os fiz entrar na terra dos seus inimigos; se então o seu coração incircunciso se humilhar, e então tomarem por bem o castigo da sua iniquidade,

[[v3-26-42]]

^<<v3-26-42,42>>^ Também eu me lembrarei do meu concerto com  Jacó, e também do meu concerto com  Isaque, e também do meu concerto com  Abraão me lembrarei, e da terra me lembrarei.

[[v3-26-43]]

^<<v3-26-43,43>>^ E a terra será desamparada deles, e folgará nos seus sábados, sendo assolada por causa deles; e tomarão por bem o castigo da sua iniquidade, em razão mesma de que rejeitaram os meus juízos e a sua alma se enfastiou dos meus estatutos.

[[v3-26-44]]

^<<v3-26-44,44>>^ E, demais disto também, estando eles na terra dos seus inimigos não os rejeitarei nem me enfadarei deles, para consumi-los e invalidar o meu concerto com eles, porque eu sou  o Senhor seu Deus.

[[v3-26-45]]

^<<v3-26-45,45>>^ Antes por amor deles me lembrarei do concerto com os seus antepassados, que tirei da terra do Egito perante os olhos das nações, para lhes ser por Deus: eu sou  o Senhor.

[[v3-26-46]]

^<<v3-26-46,46>>^ Estes são  os estatutos, e os juízos, e as leis que deu o Senhor entre si e os filhos de Israel, no monte Sinai, pela mão de Moisés.

'''

xref:003-levitico/003-levitico-025.adoc#v3-25-0[&#60; Capítulo Anterior] | <<v3-26-0,Topo>> | xref:003-levitico/003-levitico-027.adoc#v3-27-0[Próximo Capítulo &#62;]