include::./index.adoc[]

[[v3-14-0]]
=== Levítico, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v3-14-1]]

^<<v3-14-1,1>>^ DEPOIS falou o Senhor a Moisés, dizendo:

[[v3-14-2]]

^<<v3-14-2,2>>^ Esta será a lei do leproso no dia da sua purificação: será levado ao sacerdote,

[[v3-14-3]]

^<<v3-14-3,3>>^ E o sacerdote sairá fora do arraial, e o sacerdote, examinando, eis que, se a praga da lepra do leproso for sarada,

[[v3-14-4]]

^<<v3-14-4,4>>^ Então o sacerdote ordenará que por  aquele que se houver de purificar se tomem duas aves vivas e limpas, e pau de cedro, e carmesim e hissopo.

[[v3-14-5]]

^<<v3-14-5,5>>^ Mandará também o sacerdote que se degole uma ave num vaso de barro sobre águas vivas,

[[v3-14-6]]

^<<v3-14-6,6>>^ E tomará a ave viva, e o pau de cedro, e o carmesim, e o hissopo, e os molhará com a ave viva no sangue da ave que foi degolada sobre as águas vivas.

[[v3-14-7]]

^<<v3-14-7,7>>^ E sobre aquele que há de purificar-se da lepra espargirá sete vezes; então o declarará por limpo, e soltará a ave viva sobre a face do campo.

[[v3-14-8]]

^<<v3-14-8,8>>^ E aquele que tem de purificar-se lavará os seus vestidos, e rapará todo o seu pelo, e se lavará com água; assim será limpo: e depois entrará no arraial, porém ficará fora da sua tenda por sete dias;

[[v3-14-9]]

^<<v3-14-9,9>>^ E será que ao sétimo dia rapará todo o seu pelo a sua cabeça, e a sua barba, e as sobrancelhas dos seus olhos; e rapará todo o seu outro  pelo, e lavará os seus vestidos, e lavará a sua carne com água, e será limpo.

[[v3-14-10]]

^<<v3-14-10,10>>^ E ao dia oitavo tomará dois cordeiros sem mancha, e uma cordeira sem mancha, de um ano, e três dízimas de flor de farinha para  oferta de manjares, amassada com azeite, e um logue de azeite;

[[v3-14-11]]

^<<v3-14-11,11>>^ E o sacerdote que faz a purificação apresentará o homem que houver de purificar-se com aquelas cousas perante o Senhor à porta da tenda da congregação.

[[v3-14-12]]

^<<v3-14-12,12>>^ E o sacerdote tomará um dos cordeiros, e o oferecerá por expiação da culpa, e o logue de azeite; e os moverá por  oferta movida perante o Senhor.

[[v3-14-13]]

^<<v3-14-13,13>>^ Então degolará o cordeiro no lugar em que se degola a expiação do pecado e o holocausto, no lugar santo; porque assim a expiação da culpa como a expiação do pecado é para o sacerdote; cousa santíssima é.

[[v3-14-14]]

^<<v3-14-14,14>>^ E o sacerdote tomará do sangue da expiação da culpa, e o sacerdote o porá sobre a ponta da orelha direita daquele que tem de purificar-se, e sobre o dedo polegar da sua mão direita, e no dedo polegar do seu pé direito.

[[v3-14-15]]

^<<v3-14-15,15>>^ Também o sacerdote tomará do logue de azeite, e o derramará na palma da sua própria mão esquerda.

[[v3-14-16]]

^<<v3-14-16,16>>^ Então o sacerdote molhará o seu dedo direito no azeite que está na sua mão esquerda, e daquele azeite com o seu dedo espargirá sete vezes perante o Senhor;

[[v3-14-17]]

^<<v3-14-17,17>>^ E o restante do azeite, que está  na sua mão, o sacerdote porá sobre a ponta da orelha direita daquele que tem de purificar-se, e sobre o dedo polegar da sua mão direita, e sobre o dedo polegar do seu pé direito, em cima do sangue da expiação da culpa;

[[v3-14-18]]

^<<v3-14-18,18>>^ E o restante do azeite que está  na mão do sacerdote, o porá sobre a cabeça daquele que tem de purificar-se: assim o sacerdote fará expiação por ele perante o Senhor.

[[v3-14-19]]

^<<v3-14-19,19>>^ Também o sacerdote fará a expiação do pecado, e fará expiação por aquele que tem de purificar-se da sua imundícia: e depois degolará o holocausto;

[[v3-14-20]]

^<<v3-14-20,20>>^ E o sacerdote oferecerá o holocausto e a oferta de manjares sobre o altar: assim o sacerdote fará expiação por ele, e será limpo.

[[v3-14-21]]

^<<v3-14-21,21>>^ Porém se for  pobre, e a sua mão não alcançar tanto , tomará um cordeiro para  expiação da culpa em oferta de movimento, para fazer expiação por ele, e a dízima de  flor de farinha, amassada com azeite, para  oferta de manjares, e um logue de azeite,

[[v3-14-22]]

^<<v3-14-22,22>>^ E duas rolas, ou dois pombinhos, conforme alcançar a sua mão, dos quais  um será para expiação do pecado, e o outro para  holocausto.

[[v3-14-23]]

^<<v3-14-23,23>>^ E ao oitavo dia da sua purificação os trará ao sacerdote, à porta da tenda da congregação, perante o Senhor,

[[v3-14-24]]

^<<v3-14-24,24>>^ E o sacerdote tomará o cordeiro da expiação da culpa, e o logue de azeite, e o sacerdote os moverá por  oferta movida perante o Senhor.

[[v3-14-25]]

^<<v3-14-25,25>>^ Então degolará o cordeiro da expiação da culpa, e o sacerdote tomará do sangue da expiação da culpa, e o  porá sobre a ponta da orelha direita daquele que tem de purificar-se, e sobre o dedo polegar da sua mão direita, e sobre o dedo polegar do seu pé direito.

[[v3-14-26]]

^<<v3-14-26,26>>^ Também o sacerdote derramará do azeite na palma da sua própria mão esquerda;

[[v3-14-27]]

^<<v3-14-27,27>>^ Depois o sacerdote com o seu dedo direito espargirá do azeite que está  na sua mão esquerda, sete vezes perante o Senhor,

[[v3-14-28]]

^<<v3-14-28,28>>^ E o sacerdote porá do azeite que está  na sua mão na ponta da orelha direita daquele que tem de purificar-se, e no dedo polegar da sua mão direita, e no dedo polegar do seu pé direito; no lugar do sangue da expiação da culpa;

[[v3-14-29]]

^<<v3-14-29,29>>^ E o que sobejar do azeite que está  na mão do sacerdote porá sobre a cabeça do que tem de purificar-se, para fazer expiação por ele perante o Senhor.

[[v3-14-30]]

^<<v3-14-30,30>>^ Depois oferecerá uma das rolas ou dos pombinhos, conforme alcançar a sua mão.

[[v3-14-31]]

^<<v3-14-31,31>>^ Do que alcançar a sua mão, será um para  expiação do pecado e o outro para  holocausto com a oferta de manjares; e assim  o sacerdote fará expiação por aquele que tem de purificar-se perante o Senhor.

[[v3-14-32]]

^<<v3-14-32,32>>^ Esta é  a lei daquele  em quem estiver a praga da lepra, cuja mão não pode alcançar o preciso para a sua purificação.

[[v3-14-33]]

^<<v3-14-33,33>>^ Falou mais o Senhor a Moisés e Aarão, dizendo:

[[v3-14-34]]

^<<v3-14-34,34>>^ Quando tiverdes entrado na terra de Canaã, que vos hei de dar por possessão, e eu enviar a praga da lepra a alguma casa da terra da vossa possessão,

[[v3-14-35]]

^<<v3-14-35,35>>^ Então virá aquele, de quem for a casa, e o fará saber ao sacerdote, dizendo: Parece-me que há como que praga em minha casa.

[[v3-14-36]]

^<<v3-14-36,36>>^ E o sacerdote ordenará que despejem a casa, antes que venha o sacerdote para examinar a praga, para que tudo o que está  na casa não seja contaminado: e depois virá o sacerdote, para examinar a casa:

[[v3-14-37]]

^<<v3-14-37,37>>^ E, vendo a praga, e eis que se a praga nas paredes da casa tem covinhas verdes ou vermelhas, e parecem mais fundas do que a parede,

[[v3-14-38]]

^<<v3-14-38,38>>^ Então o sacerdote sairá daquela casa para fora da porta da casa, e cerrará a casa por sete dias.

[[v3-14-39]]

^<<v3-14-39,39>>^ Depois tornará o sacerdote ao sétimo dia, e examinará; e se vir  que a praga nas paredes da casa se tem estendido,

[[v3-14-40]]

^<<v3-14-40,40>>^ Então o sacerdote ordenará que arranquem as pedras, em que estiver  a praga, e que as lancem fora da cidade num lugar imundo:

[[v3-14-41]]

^<<v3-14-41,41>>^ E fará raspar a casa por dentro ao redor, e o pó que houverem raspado lançarão fora da cidade num lugar imundo.

[[v3-14-42]]

^<<v3-14-42,42>>^ Depois tomarão outras pedras, e as porão no lugar das primeiras pedras; e outro barro se tomará, e a casa se rebocará.

[[v3-14-43]]

^<<v3-14-43,43>>^ Porém, se a praga tornar, e brotar na casa, depois de se arrancarem as pedras, e depois de a casa ser raspada, e depois de ser rebocada,

[[v3-14-44]]

^<<v3-14-44,44>>^ Então o sacerdote entrará, e, examinando, eis  que, se a praga na casa se tem estendido, lepra roedora há na casa: imunda está.

[[v3-14-45]]

^<<v3-14-45,45>>^ Portanto se derribará a casa, as suas pedras, e a sua madeira, como também todo o barro da casa; e se levará tudo para fora da cidade a um lugar imundo.

[[v3-14-46]]

^<<v3-14-46,46>>^ E o que entrar naquela casa, em qualquer dia em que estiver fechada, será imundo até à tarde.

[[v3-14-47]]

^<<v3-14-47,47>>^ Também o que se deitar a dormir em tal  casa, lavará os seus vestidos: e o que comer em tal  casa lavará os seus vestidos.

[[v3-14-48]]

^<<v3-14-48,48>>^ Porém, tornando o sacerdote a entrar, e, examinando, eis que, se a praga na casa se não tem estendido, depois que a casa foi rebocada, o sacerdote declarará a casa por limpa, porque a praga está curada.

[[v3-14-49]]

^<<v3-14-49,49>>^ Depois tomará para expiar a casa duas aves, e pau de cedro, e carmesim e hissopo:

[[v3-14-50]]

^<<v3-14-50,50>>^ E degolará uma ave num vaso de barro sobre águas vivas:

[[v3-14-51]]

^<<v3-14-51,51>>^ Então tomará pau de cedro, e o hissopo, e o carmesim, e a ave viva, e os molhará na ave degolada e nas águas vivas, e espargirá a casa sete vezes:

[[v3-14-52]]

^<<v3-14-52,52>>^ Assim expiará aquela casa com o sangue da avezinha, e com as águas vivas, e com a avezinha viva, e com o pau de cedro, e com o hissopo, e com o carmesim.

[[v3-14-53]]

^<<v3-14-53,53>>^ Então soltará a ave viva para fora da cidade sobre a face do campo: assim fará expiação pela casa, e será limpa.

[[v3-14-54]]

^<<v3-14-54,54>>^ Esta é a lei de toda a praga da lepra, e da tinha,

[[v3-14-55]]

^<<v3-14-55,55>>^ E da lepra dos vestidos, e das casas,

[[v3-14-56]]

^<<v3-14-56,56>>^ E da inchação, e do apostema, e das empolas;

[[v3-14-57]]

^<<v3-14-57,57>>^ Para ensinar em que dia alguma cousa será  imunda, e em que dia será  limpa. Esta é  a lei da lepra.

'''

xref:003-levitico/003-levitico-013.adoc#v3-13-0[&#60; Capítulo Anterior] | <<v3-14-0,Topo>> | xref:003-levitico/003-levitico-015.adoc#v3-15-0[Próximo Capítulo &#62;]