include::./index.adoc[]

[[v3-4-0]]
=== Levítico, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v3-4-1]]

^<<v3-4-1,1>>^ FALOU mais o Senhor a Moisés, dizendo:

[[v3-4-2]]

^<<v3-4-2,2>>^ Fala aos filhos de Israel, dizendo: Quando uma alma pecar por erro contra alguns dos mandamentos do Senhor, acerca do  que se não deve fazer, e obrar contra  algum deles:

[[v3-4-3]]

^<<v3-4-3,3>>^ Se o sacerdote ungido pecar para escândalo do povo, oferecerá pelo seu pecado, que pecou, um novilho sem mancha, ao Senhor, por expiação do pecado.

[[v3-4-4]]

^<<v3-4-4,4>>^ E trará o novilho à porta da tenda da congregação, perante o Senhor, e porá a sua mão sobre a cabeça do novilho, e degolará o novilho perante o Senhor.

[[v3-4-5]]

^<<v3-4-5,5>>^ Então o sacerdote ungido tomará do sangue do novilho e o trará à tenda da congregação:

[[v3-4-6]]

^<<v3-4-6,6>>^ E o sacerdote molhará o seu dedo no sangue, e daquele sangue espargirá sete vezes perante o Senhor, diante do véu do santuário.

[[v3-4-7]]

^<<v3-4-7,7>>^ Também porá o sacerdote daquele sangue sobre as pontas do altar do incenso aromático , perante o Senhor que está  na tenda da congregação: e todo o resto do  sangue do novilho derramará à base do altar do holocausto, que está  à porta da tenda da congregação.

[[v3-4-8]]

^<<v3-4-8,8>>^ E toda a gordura do novilho da expiação tirará dele: a gordura que cobre a fressura, e toda a gordura que está  sobre a fressura,

[[v3-4-9]]

^<<v3-4-9,9>>^ E os dois rins, e a gordura que está  sobre eles, que está  sobre as tripas, e o redenho de sobre o fígado, com os rins, tirará,

[[v3-4-10]]

^<<v3-4-10,10>>^ Como se tira do boi do sacrifício pacífico: e o sacerdote a queimará sobre o altar do holocausto.

[[v3-4-11]]

^<<v3-4-11,11>>^ Mas o couro do novilho, e toda a sua carne, com a sua cabeça e as suas pernas, e as suas entranhas, e o seu esterco,

[[v3-4-12]]

^<<v3-4-12,12>>^ Todo aquele novilho levará fora do arraial a um lugar limpo, onde se lança a cinza, e o queimará com fogo sobre a lenha: onde se lança a cinza se queimará.

[[v3-4-13]]

^<<v3-4-13,13>>^ Mas, se toda a congregação de Israel errar, e o negócio for oculto aos olhos da congregação, e se fizerem, contra  algum dos mandamentos do Senhor, aquilo  que se não deve fazer, e forem culpados;

[[v3-4-14]]

^<<v3-4-14,14>>^ E o pecado em que pecarem for notório, então a congregação oferecerá um novilho, por expiação do pecado, e o trará diante da tenda da congregação.

[[v3-4-15]]

^<<v3-4-15,15>>^ E os anciãos da congregação porão as suas mãos sobre a cabeça do novilho perante o Senhor: e degolar-se-á o novilho perante o Senhor.

[[v3-4-16]]

^<<v3-4-16,16>>^ Então o sacerdote ungido trará do sangue do novilho à tenda da congregação.

[[v3-4-17]]

^<<v3-4-17,17>>^ E o sacerdote molhará o seu dedo naquele sangue, e o espargirá sete vezes perante o Senhor, diante do véu.

[[v3-4-18]]

^<<v3-4-18,18>>^ E daquele sangue porá sobre as pontas do altar, que está  perante a face do Senhor, na tenda da congregação: e todo o resto do  sangue derramará à base do altar do holocausto, que está diante  da porta da tenda da congregação.

[[v3-4-19]]

^<<v3-4-19,19>>^ E tirará dele toda a sua gordura, e queimá-la-á sobre o altar;

[[v3-4-20]]

^<<v3-4-20,20>>^ E fará a este novilho como fez ao novilho da expiação; assim lhe fará, e o sacerdote por eles fará propiciação, e lhes será perdoado o pecado.

[[v3-4-21]]

^<<v3-4-21,21>>^ Depois levará o novilho fora do arraial, e o queimará como queimou o primeiro novilho: é  expiação do pecado da congregação.

[[v3-4-22]]

^<<v3-4-22,22>>^ Quando um príncipe pecar, e por erro obrar contra  algum de todos os mandamentos do Senhor seu Deus, naquilo  que se não deve fazer, e assim  for culpado;

[[v3-4-23]]

^<<v3-4-23,23>>^ Ou se  o seu pecado, no qual pecou, lhe for notificado, então trará por sua oferta um bode tirado  de entre as cabras, macho sem mancha,

[[v3-4-24]]

^<<v3-4-24,24>>^ E porá a sua mão sobre a cabeça do bode, e o degolará no lugar onde se degola o holocausto, perante a face do Senhor: expiação do pecado é.

[[v3-4-25]]

^<<v3-4-25,25>>^ Depois o sacerdote com o seu dedo tomará do sangue da expiação, e o porá sobre as pontas do altar do holocausto: então o resto do seu  sangue derramará à base do altar do holocausto.

[[v3-4-26]]

^<<v3-4-26,26>>^ Também queimará sobre o altar toda a sua gordura como gordura do sacrifício pacífico: assim o sacerdote por ele fará expiação do seu pecado e lhe será perdoado.

[[v3-4-27]]

^<<v3-4-27,27>>^ E se qualquer outra  pessoa do povo da terra pecar por erro, fazendo contra  algum dos mandamentos do Senhor, aquilo  que se não deve fazer, e assim  for culpada;

[[v3-4-28]]

^<<v3-4-28,28>>^ Ou se  o seu pecado, no qual pecou, lhe for notificado, então trará por sua oferta uma cabra fêmea sem mancha, pelo seu pecado que pecou.

[[v3-4-29]]

^<<v3-4-29,29>>^ E porá a sua mão sobre a cabeça da expiação do pecado, e degolará a expiação do pecado no lugar do holocausto.

[[v3-4-30]]

^<<v3-4-30,30>>^ Depois o sacerdote com o seu dedo tomará do seu sangue, e o porá sobre as pontas do altar do holocausto: e todo o resto do seu  sangue derramará à base do altar;

[[v3-4-31]]

^<<v3-4-31,31>>^ E tirará toda a gordura, como se tira a gordura do sacrifício pacífico; e o sacerdote a queimará sobre o altar por cheiro suave ao Senhor: e o sacerdote fará propiciação por ela, e lhe será perdoado o pecado.

[[v3-4-32]]

^<<v3-4-32,32>>^ Mas, se pela sua oferta trouxer uma cordeira para expiação do pecado, sem mancha a trará.

[[v3-4-33]]

^<<v3-4-33,33>>^ E porá a sua mão sobre a cabeça da expiação do pecado, e a degolará por expiação do pecado, no lugar onde se degola o holocausto.

[[v3-4-34]]

^<<v3-4-34,34>>^ Depois o sacerdote com o seu dedo tomará do sangue da expiação do pecado, e o  porá sobre as pontas do altar do holocausto: então todo o resto do  seu sangue derramará na base do altar,

[[v3-4-35]]

^<<v3-4-35,35>>^ E tirará toda a sua gordura, como se tira a gordura do cordeiro do sacrifício pacífico: e o sacerdote a queimará sobre o altar, em cima das ofertas queimadas do Senhor: assim o sacerdote por ela fará expiação dos seus pecados, que pecou, e lhe será perdoado o pecado.

'''

xref:003-levitico/003-levitico-003.adoc#v3-3-0[&#60; Capítulo Anterior] | <<v3-4-0,Topo>> | xref:003-levitico/003-levitico-005.adoc#v3-5-0[Próximo Capítulo &#62;]