include::./index.adoc[]

[[v3-18-0]]
=== Levítico, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v3-18-1]]

^<<v3-18-1,1>>^ FALOU mais o Senhor a Moisés, dizendo:

[[v3-18-2]]

^<<v3-18-2,2>>^ Fala aos filhos de Israel, e dize-lhes: Eu sou o Senhor vosso Deus.

[[v3-18-3]]

^<<v3-18-3,3>>^ Não fareis segundo as obras da terra do Egito, em que habitastes, nem fareis segundo as obras da terra de Canaã, para a qual eu vos levo, nem andareis nos seus estatutos.

[[v3-18-4]]

^<<v3-18-4,4>>^ Fareis conforme  aos meus juízos, e os meus estatutos guardareis, para andardes neles: Eu sou  o Senhor vosso Deus.

[[v3-18-5]]

^<<v3-18-5,5>>^ Portanto os meus estatutos e os meus juízos guardareis; os quais, fazendo-os o homem, viverá por eles: Eu sou  o Senhor.

[[v3-18-6]]

^<<v3-18-6,6>>^ Nenhum homem se chegará a qualquer parenta da sua carne, para descobrir a sua nudez; Eu sou  o Senhor.

[[v3-18-7]]

^<<v3-18-7,7>>^ Não descobrirás a nudez de teu pai e de tua mãe; ela  é tua mãe; não descobrirás a sua nudez.

[[v3-18-8]]

^<<v3-18-8,8>>^ Não descobrirás a nudez da mulher de teu pai.

[[v3-18-9]]

^<<v3-18-9,9>>^ A nudez de tua irmã, filha de teu pai, ou filha de tua mãe, nascida em casa, ou fora da casa, a sua nudez não descobrirás.

[[v3-18-10]]

^<<v3-18-10,10>>^ A nudez da filha do teu filho, ou da filha da tua filha, a sua nudez não descobrirás: porque é tua nudez.

[[v3-18-11]]

^<<v3-18-11,11>>^ A nudez da filha da mulher de teu pai, gerada de teu pai ( ela  é tua irmã), a sua nudez não descobrirás.

[[v3-18-12]]

^<<v3-18-12,12>>^ A nudez da irmã de teu pai não descobrirás; ela  é parenta de teu pai.

[[v3-18-13]]

^<<v3-18-13,13>>^ A nudez da irmã de tua mãe não descobrirás; pois ela  é parenta de tua mãe.

[[v3-18-14]]

^<<v3-18-14,14>>^ A nudez do irmão de teu pai não descobrirás; não te chegarás à sua mulher; ela  é tua tia.

[[v3-18-15]]

^<<v3-18-15,15>>^ A nudez de tua nora não descobrirás: ela  é mulher de teu filho: não descobrirás a sua nudez.

[[v3-18-16]]

^<<v3-18-16,16>>^ A nudez da mulher de teu irmão não descobrirás; é a nudez de teu irmão.

[[v3-18-17]]

^<<v3-18-17,17>>^ A nudez duma mulher e de sua filha não descobrirás: não tomarás a filha de seu filho, nem a filha de sua filha, para descobrir a sua nudez; parentas são: maldade é.

[[v3-18-18]]

^<<v3-18-18,18>>^ E não tomarás uma mulher com sua irmã, para afligi-la, descobrindo a sua nudez com ela na sua vida.

[[v3-18-19]]

^<<v3-18-19,19>>^ E não te chegarás à mulher durante a separação da sua imundícia, para descobrir a sua nudez,

[[v3-18-20]]

^<<v3-18-20,20>>^ Nem te deitarás com a mulher de teu próximo para cópula, para te contaminares com ela.

[[v3-18-21]]

^<<v3-18-21,21>>^ E da tua semente não darás para a fazer passar pelo fogo  perante Moloque: e não profanarás o nome de teu Deus: Eu sou  o Senhor.

[[v3-18-22]]

^<<v3-18-22,22>>^ Com varão te não deitarás, como se fosse mulher: abominação é;

[[v3-18-23]]

^<<v3-18-23,23>>^ Nem te deitarás com um animal, para te contaminares com ele: nem a mulher se porá perante um animal, para ajuntar-se com ele; confusão é.

[[v3-18-24]]

^<<v3-18-24,24>>^ Com nenhuma destas cousas vos contamineis: porque em todas estas cousas se contaminaram as gentes que eu lanço fora de diante da vossa face.

[[v3-18-25]]

^<<v3-18-25,25>>^ Pelo que a terra está contaminada; e eu visitarei sobre ela a sua iniquidade, e a terra vomitará os seus moradores.

[[v3-18-26]]

^<<v3-18-26,26>>^ Porém vós guardareis os meus estatutos e os meus juízos, e nenhuma  destas abominações fareis, nem  o natural, nem o estrangeiro que peregrina entre vós;

[[v3-18-27]]

^<<v3-18-27,27>>^ Porque todas estas abominações fizeram os homens desta terra, que nela estavam  antes de vós; e a terra foi contaminada.

[[v3-18-28]]

^<<v3-18-28,28>>^ Para que a terra vos não vomite, havendo-a contaminado, como vomitou a gente, que nela estava  antes de vós.

[[v3-18-29]]

^<<v3-18-29,29>>^ Porém, qualquer que fizer alguma destas abominações, as almas que as  fizerem serão extirpadas do seu povo.

[[v3-18-30]]

^<<v3-18-30,30>>^ Portanto guardareis o meu mandado, não fazendo nenhum dos estatutos abomináveis que se fizeram antes de vós, e não vos contamineis com eles: Eu sou  o Senhor vosso Deus.

'''

xref:003-levitico/003-levitico-017.adoc#v3-17-0[&#60; Capítulo Anterior] | <<v3-18-0,Topo>> | xref:003-levitico/003-levitico-019.adoc#v3-19-0[Próximo Capítulo &#62;]