include::./index.adoc[]

[[v3-20-0]]
=== Levítico, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v3-20-1]]

^<<v3-20-1,1>>^ FALOU mais o Senhor a Moisés, dizendo:

[[v3-20-2]]

^<<v3-20-2,2>>^ Também dirás aos filhos de Israel: Qualquer que, dos filhos de Israel, ou dos estrangeiros que peregrinam em Israel, der da sua semente a Moloque, certamente morrerá; o povo da terra o apedrejará com pedras.

[[v3-20-3]]

^<<v3-20-3,3>>^ E eu porei a minha face contra esse homem, e o extirparei do meio do seu povo, porquanto deu da sua semente a Moloque, para contaminar o meu santuário e profanar o meu santo nome.

[[v3-20-4]]

^<<v3-20-4,4>>^ E, se o povo da terra de alguma maneira esconder os seus olhos daquele homem que houver dado da sua semente a Moloque, e o não matar,

[[v3-20-5]]

^<<v3-20-5,5>>^ Então eu porei a minha face contra aquele homem, e contra a sua família, e o extirparei do meio do seu povo, com todos os que se prostituem após dele, prostituindo-se após de Moloque.

[[v3-20-6]]

^<<v3-20-6,6>>^ Quando uma alma se virar para os adivinhadores e encantadores, para se prostituir após deles, eu porei a minha face contra aquela alma, e a extirparei do meio do seu povo.

[[v3-20-7]]

^<<v3-20-7,7>>^ Portanto, santificai-vos, e sede santos, pois eu sou  o Senhor vosso Deus.

[[v3-20-8]]

^<<v3-20-8,8>>^ E guardai os meus estatutos, e cumpri-os: Eu sou  o Senhor que vos santifica.

[[v3-20-9]]

^<<v3-20-9,9>>^ Quando um homem amaldiçoar a seu pai ou a sua mãe, certamente morrerá: amaldiçoou a seu pai ou a sua mãe; o seu sangue é  sobre ele.

[[v3-20-10]]

^<<v3-20-10,10>>^ Também o homem que adulterar com a mulher de outro, havendo adulterado com a mulher do seu próximo, certamente morrerá o adúltero e a adúltera.

[[v3-20-11]]

^<<v3-20-11,11>>^ E o homem que se deitar com a mulher de seu pai descobriu a nudez de seu pai; ambos certamente morrerão: o seu sangue é  sobre eles.

[[v3-20-12]]

^<<v3-20-12,12>>^ Semelhantemente, quando um homem se deitar com a sua nora, ambos certamente morrerão: fizeram confusão; o seu sangue é  sobre eles.

[[v3-20-13]]

^<<v3-20-13,13>>^ Quando também um homem se deitar com outro  homem como com mulher, ambos fizeram abominação; certamente morrerão; o seu sangue é  sobre eles.

[[v3-20-14]]

^<<v3-20-14,14>>^ E, quando um homem tomar uma mulher e a sua mãe, maldade é: a ele e a elas queimarão com fogo, para que não haja maldade no meio de vós.

[[v3-20-15]]

^<<v3-20-15,15>>^ Quando também um homem se deitar com um animal, certamente morrerá; e matareis o animal.

[[v3-20-16]]

^<<v3-20-16,16>>^ Também a mulher que se chegar a algum animal, para ter ajuntamento com ele, aquela mulher matarás com o animal; certamente morrerão; o seu sangue é  sobre eles.

[[v3-20-17]]

^<<v3-20-17,17>>^ E, quando um homem tomar a sua irmã, filha de seu pai, ou filha de sua mãe, e ele vir a nudez dela, e ela vir a sua, torpeza é: portanto serão extirpados aos olhos dos filhos do seu povo: descobriu a nudez de sua irmã, levarão sobre si  a sua iniquidade.

[[v3-20-18]]

^<<v3-20-18,18>>^ E, quando um homem se deitar com uma mulher que tem a sua enfermidade, e descobrir a sua nudez, descobrindo a sua fonte, e ela descobrir a fonte do seu sangue, ambos serão extirpados do meio do seu povo.

[[v3-20-19]]

^<<v3-20-19,19>>^ Também a nudez da irmã de tua mãe, ou da irmã de teu pai não descobrirás: porquanto descobriu a sua parenta, sobre si levarão a sua iniquidade.

[[v3-20-20]]

^<<v3-20-20,20>>^ Quando também um homem se deitar com a sua tia descobriu a nudez de seu tio: seu pecado sobre si levarão; sem filhos morrerão.

[[v3-20-21]]

^<<v3-20-21,21>>^ E quando um homem tomar a mulher de seu irmão, imundícia é : a nudez de seu irmão descobriu: sem filhos ficarão.

[[v3-20-22]]

^<<v3-20-22,22>>^ Guardai pois todos os meus estatutos, e todos os meus juízos, e cumpri-os, para que vos não vomite a terra, para a qual eu vos levo para habitar nela.

[[v3-20-23]]

^<<v3-20-23,23>>^ E não andeis nos estatutos da gente que eu lanço fora diante da vossa face, porque fizeram todas estas cousas: portanto fui enfadado deles.

[[v3-20-24]]

^<<v3-20-24,24>>^ E a vós vos tenho dito: Em herança possuireis a sua terra, e eu a darei a vós para possuí-la em herança, terra que mana leite e mel: Eu sou  o Senhor vosso Deus, que vos separei dos povos.

[[v3-20-25]]

^<<v3-20-25,25>>^ Fareis pois diferença entre os animais limpos e imundos, e entre as aves imundas e as limpas; e as vossas almas não fareis abomináveis por causa  dos animais, ou das aves, ou de tudo o que se arrasta sobre a terra; as quais cousas apartei de vós para tê-las por imundas.

[[v3-20-26]]

^<<v3-20-26,26>>^ E ser-me-eis santos, porque eu, o Senhor, sou  santo, e separei-vos dos povos, para serdes meus.

[[v3-20-27]]

^<<v3-20-27,27>>^ Quando pois algum homem ou mulher em si tiver um espírito adivinho, ou for encantador, certamente morrerão: com pedras se apedrejarão; o seu sangue é  sobre eles.

'''

xref:003-levitico/003-levitico-019.adoc#v3-19-0[&#60; Capítulo Anterior] | <<v3-20-0,Topo>> | xref:003-levitico/003-levitico-021.adoc#v3-21-0[Próximo Capítulo &#62;]