include::./index.adoc[]

[[v3-1-0]]
=== Levítico, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v3-1-1]]

^<<v3-1-1,1>>^ E CHAMOU o Senhor a Moisés, e falou com ele da tenda da congregação, dizendo:

[[v3-1-2]]

^<<v3-1-2,2>>^ Fala aos filhos de Israel, e dize-lhes: Quando algum de vós oferecer oferta ao Senhor, oferecereis as vossas ofertas de gado, de vacas e de ovelhas.

[[v3-1-3]]

^<<v3-1-3,3>>^ Se a sua oferta for  holocausto de gado, oferecerá macho sem mancha: à porta da tenda da congregação a oferecerá, de sua própria vontade, perante o Senhor.

[[v3-1-4]]

^<<v3-1-4,4>>^ E porá a sua mão sobre a cabeça do holocausto, para que seja aceito por ele, para a sua expiação.

[[v3-1-5]]

^<<v3-1-5,5>>^ Depois degolará o bezerro perante o Senhor; e os filhos de Aarão, os sacerdotes, oferecerão o sangue, e espargirão o sangue à roda sobre o altar que está diante  da porta da tenda da congregação.

[[v3-1-6]]

^<<v3-1-6,6>>^ Então esfolará o holocausto, e o partirá nos seus pedaços.

[[v3-1-7]]

^<<v3-1-7,7>>^ E os filhos de Aarão, os sacerdotes, porão fogo sobre o altar, pondo em ordem a lenha sobre o fogo.

[[v3-1-8]]

^<<v3-1-8,8>>^ Também os filhos de Aarão, os sacerdotes, porão em ordem os pedaços, a cabeça e o redenho sobre a lenha que está  no fogo em cima do altar;

[[v3-1-9]]

^<<v3-1-9,9>>^ Porém a sua fressura e as suas pernas lavar-se-ão com água; e o sacerdote tudo isto  queimará sobre o altar: holocausto é , oferta queimada, de cheiro suave ao Senhor.

[[v3-1-10]]

^<<v3-1-10,10>>^ E se a sua oferta for  de gado miúdo, de ovelhas ou de cabras, para holocausto, oferecerá macho sem mancha,

[[v3-1-11]]

^<<v3-1-11,11>>^ E a degolará ao lado do altar, para a banda do norte perante o Senhor; e os filhos de Aarão, os sacerdotes, espargirão o seu sangue à roda sobre o altar.

[[v3-1-12]]

^<<v3-1-12,12>>^ Depois a partirá nos seus pedaços, como também a sua cabeça e o seu redenho: e o sacerdote os porá em ordem sobre a lenha que está  no fogo sobre o altar.

[[v3-1-13]]

^<<v3-1-13,13>>^ Porém a fressura e as pernas lavar-se-ão com água; e o sacerdote tudo oferecerá, e o queimará sobre o altar; holocausto é , oferta queimada, de cheiro suave ao Senhor.

[[v3-1-14]]

^<<v3-1-14,14>>^ E se a sua oferta ao Senhor for  holocausto de aves, oferecerá a sua oferta de rola ou de pombinhos;

[[v3-1-15]]

^<<v3-1-15,15>>^ E o sacerdote a oferecerá sobre o altar, e lhe torcerá o pescoço com a sua unha, e a  queimará sobre o altar; e o seu sangue será espremido na parede do altar;

[[v3-1-16]]

^<<v3-1-16,16>>^ E o seu papo com as suas penas tirará e o lançará junto ao altar, para a banda do oriente, no lugar da cinza;

[[v3-1-17]]

^<<v3-1-17,17>>^ E fendê-la-á com as suas asas, porém  não a  partirá; e o sacerdote a queimará em cima do altar sobre a lenha que está  no fogo: holocausto é , oferta queimada de cheiro suave ao Senhor.

'''

xref:002-exodo/002-exodo-040.adoc#v2-40-0[&#60; Capítulo Anterior] | <<v3-1-0,Topo>> | xref:003-levitico/003-levitico-002.adoc#v3-2-0[Próximo Capítulo &#62;]