include::./index.adoc[]

[[v28-6-0]]
=== Oséias, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v28-6-1]]

^<<v28-6-1,1>>^ VINDE, e tornemos para o Senhor, porque ele despedaçou, e nos sarará, fez a ferida, e a ligará.

[[v28-6-2]]

^<<v28-6-2,2>>^ Depois de dois dias nos dará a vida: ao terceiro dia nos ressuscitará, e viveremos diante dele.

[[v28-6-3]]

^<<v28-6-3,3>>^ Conheçamos, e  prossigamos em conhecer ao Senhor: como a alva será a sua saída: e ele a nós virá como a chuva, como chuva serôdia que rega a terra.

[[v28-6-4]]

^<<v28-6-4,4>>^ Que te farei, ó Efraim? que te farei, ó Judá? porque a vossa beneficência é  como a nuvem da manhã, e como o orvalho da madrugada, que cedo passa.

[[v28-6-5]]

^<<v28-6-5,5>>^ Por isso os abati pelos profetas: pela palavra da minha boca os matei; e os teus juízos sairão como  a luz.

[[v28-6-6]]

^<<v28-6-6,6>>^ Porque eu quero misericórdia, e não o sacrifício; e o conhecimento de Deus, mais do que os holocaustos.

[[v28-6-7]]

^<<v28-6-7,7>>^ Mas eles traspassaram o concerto, como Adão; eles se portaram aleivosamente contra mim.

[[v28-6-8]]

^<<v28-6-8,8>>^ Gileade é a cidade dos que praticam a iniquidade, calcada de sangue.

[[v28-6-9]]

^<<v28-6-9,9>>^ Como hordas de salteadores que espreitam alguém, assim é a companhia dos sacerdotes que matam no caminho para Siquém; sim, eles têm praticado abominações.

[[v28-6-10]]

^<<v28-6-10,10>>^ Vejo uma cousa horrenda na casa de Israel: ali está a prostituição de Efraim; Israel é contaminado.

[[v28-6-11]]

^<<v28-6-11,11>>^ Também para ti, ó Judá, foi assinada uma ceifa, quando eu remover o cativeiro do meu povo.

'''

xref:028-oseias/028-oseias-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-oseias/028-oseias-007.adoc#v28-7-0[Próximo Capítulo &#62;]