include::./index.adoc[]

[[v28-4-0]]
=== Oséias, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v28-4-1]]

^<<v28-4-1,1>>^ OUVI a palavra do Senhor, vós, filhos de Israel, porque o Senhor tem uma contenda com os habitantes da terra, porque não há verdade, nem benignidade, nem conhecimento de Deus na terra.

[[v28-4-2]]

^<<v28-4-2,2>>^ Só prevalecem o perjurar, e o mentir, e o matar, e o furtar, e o adulterar, e há homicídios sobre homicídios.

[[v28-4-3]]

^<<v28-4-3,3>>^ Por isso a terra se lamentará, e qualquer que morar nela desfalecerá com os animais do campo e com as aves do céu; e até os peixes do mar serão tirados.

[[v28-4-4]]

^<<v28-4-4,4>>^ Todavia, ninguém contenda, nem qualquer repreenda; porque o teu povo é  como os que contendem com o sacerdote.

[[v28-4-5]]

^<<v28-4-5,5>>^ Por isso cairás de dia, e o profeta contigo cairá de noite; e destruirei a tua mãe.

[[v28-4-6]]

^<<v28-4-6,6>>^ O meu povo foi destruído, porque lhe  faltou o conhecimento; porque tu rejeitaste o conhecimento, também eu te rejeitarei, para que não sejas sacerdote diante de mim; visto que te esqueceste da lei do teu Deus, também eu me esquecerei de teus filhos.

[[v28-4-7]]

^<<v28-4-7,7>>^ Como eles se multiplicaram, assim contra mim pecaram: eu mudarei a sua honra em vergonha.

[[v28-4-8]]

^<<v28-4-8,8>>^ Alimentam-se do pecado do meu povo, e da maldade dele têm desejo ardente.

[[v28-4-9]]

^<<v28-4-9,9>>^ Por isso, como é o povo, assim será o sacerdote; e visitarei sobre ele os seus caminhos, e lhe darei a recompensa das suas obras.

[[v28-4-10]]

^<<v28-4-10,10>>^ Comerão, mas não se fartarão; entregar-se-ão à luxúria, mas não se multiplicarão; porque deixaram de olhar para o Senhor.

[[v28-4-11]]

^<<v28-4-11,11>>^ A incontinência, e o vinho, e o mosto tiram a inteligência.

[[v28-4-12]]

^<<v28-4-12,12>>^ O meu povo consulta a sua madeira, e a sua vara lhe responde, porque o espírito de luxúria os engana, e eles se corrompem, apartando-se da sujeição do seu Deus.

[[v28-4-13]]

^<<v28-4-13,13>>^ Sacrificam sobre os cumes dos montes, e queimam incenso sobre os outeiros, debaixo do carvalho, e do álamo, e do olmeiro, porque é  boa a sua sombra; por isso vossas filhas se prostituem, e as vossas noras adulteram.

[[v28-4-14]]

^<<v28-4-14,14>>^ Eu não castigarei vossas filhas, que se prostituem, nem vossas noras, quando adulteram; porque eles mesmos com as prostitutas se desviam e com as meretrizes sacrificam: pois o povo que  não tem entendimento será transtornado.

[[v28-4-15]]

^<<v28-4-15,15>>^ Se tu, ó Israel, queres corromper-te, não se faça culpado Judá; não venhais a Gilgal, e não subais a Bete-Áven, e não jureis, dizendo : Vive o Senhor.

[[v28-4-16]]

^<<v28-4-16,16>>^ Porque como uma vaca rebelde se rebelou Israel: agora o Senhor os apascentará como a um cordeiro num lugar espaçoso.

[[v28-4-17]]

^<<v28-4-17,17>>^ Efraim está entregue aos ídolos; deixa-o.

[[v28-4-18]]

^<<v28-4-18,18>>^ A sua bebida se foi: eles corrompem-se cada vez mais; certamente amaram a vergonha os seus príncipes.

[[v28-4-19]]

^<<v28-4-19,19>>^ Um vento os envolveu nas suas asas, e envergonhar-se-ão por causa dos seus sacrifícios.

'''

xref:028-oseias/028-oseias-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-oseias/028-oseias-005.adoc#v28-5-0[Próximo Capítulo &#62;]