include::./index.adoc[]

[[v28-8-0]]
=== Oséias, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v28-8-1]]

^<<v28-8-1,1>>^ PÕE a trombeta à tua boca. Ele vem  como águia contra a casa do Senhor, porque traspassaram o meu concerto, e se rebelaram contra a minha lei.

[[v28-8-2]]

^<<v28-8-2,2>>^ E a mim clamarão: Deus meu! nós, Israel, te conhecemos.

[[v28-8-3]]

^<<v28-8-3,3>>^ Israel rejeitou o bem: o inimigo persegui-lo-á.

[[v28-8-4]]

^<<v28-8-4,4>>^ Eles fizeram reis, mas não por mim: constituíram príncipes, mas eu não o soube: da sua prata e do seu ouro fizeram ídolos para si, para serem destruídos.

[[v28-8-5]]

^<<v28-8-5,5>>^ O teu bezerro, ó Samaria, foi rejeitado: a minha ira se acendeu contra eles; até quando serão  eles incapazes de alcançar a inocência?

[[v28-8-6]]

^<<v28-8-6,6>>^ Porque isso é mesmo de Israel; um artífice o fez, e não é  Deus; mas em  pedaços será  desfeito o bezerro de Samaria.

[[v28-8-7]]

^<<v28-8-7,7>>^ Porque semearam ventos, e segarão tormentas: não há seara; a erva não dará farinha: se a der, tragá-la-ão os estrangeiros.

[[v28-8-8]]

^<<v28-8-8,8>>^ Israel foi devorado: agora está entre as nações como um vaso em que ninguém tem prazer.

[[v28-8-9]]

^<<v28-8-9,9>>^ Porque subiram à Assíria, como  um jumento montês, por si só: mercou Efraim amores.

[[v28-8-10]]

^<<v28-8-10,10>>^ Todavia, ainda que eles merquem entre as nações, eu as congregarei: já começaram a ser diminuídos por causa da carga do rei dos príncipes.

[[v28-8-11]]

^<<v28-8-11,11>>^ Porquanto Efraim multiplicou os altares para pecar; teve altares para pecar.

[[v28-8-12]]

^<<v28-8-12,12>>^ Escrevi para eles as grandezas da minha lei; mas isso é para ele como cousa estranha.

[[v28-8-13]]

^<<v28-8-13,13>>^ Quanto  aos sacrifícios dos meus dons, sacrificam carne, e a  comem, mas o Senhor não a aceitou: agora se lembrará da sua injustiça, e visitará os seus pecados: eles voltarão para o Egito.

[[v28-8-14]]

^<<v28-8-14,14>>^ Porque Israel se esqueceu do seu Criador, e edificou palácios, e Judá multiplicou cidades fortes; mas eu enviarei um fogo contra as suas cidades, e ele consumirá os seus palácios.

'''

xref:028-oseias/028-oseias-007.adoc#v28-7-0[&#60; Capítulo Anterior] | <<v28-8-0,Topo>> | xref:028-oseias/028-oseias-009.adoc#v28-9-0[Próximo Capítulo &#62;]