include::./index.adoc[]

[[v28-10-0]]
=== Oséias, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v28-10-1]]

^<<v28-10-1,1>>^ ISRAEL é  uma vide frondosa; dá fruto para si mesmo: conforme a abundância do seu fruto, assim multiplicou os altares; conforme a bondade da terra, assim fizeram boas estátuas.

[[v28-10-2]]

^<<v28-10-2,2>>^ O seu coração está dividido; por isso serão culpados: cortará os seus altares, e destruirá as estátuas.

[[v28-10-3]]

^<<v28-10-3,3>>^ Certamente agora dirão: Não temos rei, porque não tememos ao Senhor: que, pois, nos faria o rei?

[[v28-10-4]]

^<<v28-10-4,4>>^ Multiplicaram palavras, jurando falsamente, fazendo um concerto: por isso florescerá o juízo como erva peçonhenta nos regos dos campos.

[[v28-10-5]]

^<<v28-10-5,5>>^ Os moradores de Samaria serão atemorizados pelo bezerro de Bete-Áven, porquanto o seu povo se lamentará por causa dele, como também os seus sacerdotes ( que  nele se alegravam), e por causa da sua glória, que se apartou dela.

[[v28-10-6]]

^<<v28-10-6,6>>^ Também a Assíria será levada como  um presente ao rei Jarebe: Efraim ficará confuso, e Israel se envergonhará por causa do seu próprio conselho.

[[v28-10-7]]

^<<v28-10-7,7>>^ O rei de Samaria será desfeito como a espuma sobre a face da água.

[[v28-10-8]]

^<<v28-10-8,8>>^ E os altos de Áven, pecado de Israel, serão destruídos: espinhos e cardos crescerão sobre os seus altares; e dirão aos montes: Cobri-nos! e aos outeiros: Caí sobre nós!

[[v28-10-9]]

^<<v28-10-9,9>>^ Desde os dias de Gibeá pecaste, ó Israel; ali permaneceram: a peleja em Gibeá contra os filhos da perversidade não os surpreenderá.

[[v28-10-10]]

^<<v28-10-10,10>>^ Eu os castigarei na medida do meu desejo; e congregar-se-ão contra eles os povos, quando os atar às suas transgressões.

[[v28-10-11]]

^<<v28-10-11,11>>^ Porque Efraim é  uma bezerra domada, que gosta de trilhar; passei sobre a formosura do seu pescoço: farei cavalgar Efraim. Judá lavrará, Jacó lhe desfará os torrões.

[[v28-10-12]]

^<<v28-10-12,12>>^ Semeai para vós em justiça, ceifai segundo a misericórdia; lavrai o campo de lavoura; porque é tempo de buscar ao Senhor, até que venha e chova a justiça sobre vós.

[[v28-10-13]]

^<<v28-10-13,13>>^ Lavrastes a impiedade, segastes a perversidade, e  comestes o fruto da mentira; porque confiaste no teu caminho, na multidão dos teus valentes.

[[v28-10-14]]

^<<v28-10-14,14>>^ Portanto, entre o teu povo se levantará um grande tumulto, e todas as tuas fortalezas serão destruídas, como Salmã destruiu a Bete-Arbel no dia da guerra: a mãe ali foi despedaçada com os filhos.

[[v28-10-15]]

^<<v28-10-15,15>>^ Assim vos fará Betel, por causa da malícia da vossa malícia; o rei de Israel de madrugada será totalmente destruído.

'''

xref:028-oseias/028-oseias-009.adoc#v28-9-0[&#60; Capítulo Anterior] | <<v28-10-0,Topo>> | xref:028-oseias/028-oseias-011.adoc#v28-11-0[Próximo Capítulo &#62;]