include::./index.adoc[]

[[v28-12-0]]
=== Oséias, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v28-12-1]]

^<<v28-12-1,1>>^ EFRAIM se apascenta de vento, e segue o vento leste: todo o dia multiplica a mentira e a destruição e fazem aliança com a Assíria, e o azeite se leva ao Egito.

[[v28-12-2]]

^<<v28-12-2,2>>^ O Senhor também com Judá tem contenda, e castigará Jacó segundo os seus caminhos; segundo as suas obras o recompensará.

[[v28-12-3]]

^<<v28-12-3,3>>^ No ventre pegou do calcanhar de seu irmão, e pela sua força como príncipe se houve com Deus.

[[v28-12-4]]

^<<v28-12-4,4>>^ Como príncipe lutou com o anjo, e prevaleceu; chorou, e lhe suplicou: em Betel o achou, e ali falou conosco;

[[v28-12-5]]

^<<v28-12-5,5>>^ Sim, com o Senhor, o Deus dos Exércitos: o Senhor é  o seu memorial.

[[v28-12-6]]

^<<v28-12-6,6>>^ Tu, pois, converte-te a teu Deus: guarda a beneficência e o juízo, e em teu Deus espera sempre.

[[v28-12-7]]

^<<v28-12-7,7>>^ É um  mercador; tem balança enganadora em sua mão; ele ama a opressão.

[[v28-12-8]]

^<<v28-12-8,8>>^ E diz Efraim: Contudo eu tenho-me enriquecido, tenho adquirido para mim grandes bens: em  todo o meu trabalho não acharão em mim iniquidade alguma que seja  pecado.

[[v28-12-9]]

^<<v28-12-9,9>>^ Mas eu sou  o Senhor teu Deus desde a terra do Egito: eu ainda te farei habitar em tendas, como nos dias da reunião solene.

[[v28-12-10]]

^<<v28-12-10,10>>^ E falarei aos profetas, e multiplicarei a visão; e pelo ministério dos profetas proporei símiles.

[[v28-12-11]]

^<<v28-12-11,11>>^ Não é Gileade iniquidade? pura vaidade eles são: em Gilgal sacrificam bois: os seus altares são como montões de pedras  nos regos dos campos.

[[v28-12-12]]

^<<v28-12-12,12>>^ Jacó fugiu para o campo da Síria, e Israel serviu por uma mulher, e por uma mulher guardou o gado.

[[v28-12-13]]

^<<v28-12-13,13>>^ Mas o Senhor por meio dum profeta fez subir a Israel do Egito, e por um profeta foi ele guardado.

[[v28-12-14]]

^<<v28-12-14,14>>^ Efraim mui amargosamente provocou a sua ira: portanto deixará ficar sobre ele o seu sangue, e o seu Senhor fará cair sobre ele o seu opróbrio.

'''

xref:028-oseias/028-oseias-011.adoc#v28-11-0[&#60; Capítulo Anterior] | <<v28-12-0,Topo>> | xref:028-oseias/028-oseias-013.adoc#v28-13-0[Próximo Capítulo &#62;]