include::./index.adoc[]

[[v28-9-0]]
=== Oséias, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v28-9-1]]

^<<v28-9-1,1>>^ NÃO te alegres, ó Israel, até saltar, como os povos; porque te foste do teu Deus como uma meretriz: amaste a paga sobre todas as eiras de trigo.

[[v28-9-2]]

^<<v28-9-2,2>>^ A eira e o lagar não os manterão; e o mosto lhes faltará.

[[v28-9-3]]

^<<v28-9-3,3>>^ Na terra do Senhor não permanecerão; mas Efraim tornará ao Egito, e na Assíria comerão comida imunda.

[[v28-9-4]]

^<<v28-9-4,4>>^ Não derramarão vinho perante o Senhor, nem as suas ofertas  serão para ele suaves: os seus sacrifícios para eles serão como pão de pranteadores; todos os que dele comessem seriam imundos, porque o seu pão será para o seu apetite; não entrará na casa do Senhor.

[[v28-9-5]]

^<<v28-9-5,5>>^ Que fareis vós no dia da solenidade, e no dia da festa do Senhor?

[[v28-9-6]]

^<<v28-9-6,6>>^ Porque, eis que eles  se foram por causa da destruição, mas o Egito os recolherá, Mênfis os sepultará: o desejável da sua prata as urtigas o  possuirão por herança; espinhos haverá nas suas moradas.

[[v28-9-7]]

^<<v28-9-7,7>>^ Chegaram os dias da visitação, chegaram os dias da retribuição; Israel o saberá: o profeta é um insensato, o homem de espírito é um louco; por causa da abundância da tua iniquidade também abundará o ódio.

[[v28-9-8]]

^<<v28-9-8,8>>^ Efraim era vigia com o meu Deus, mas  o profeta é como  um laço de caçador de aves em todos os seus caminhos, um inimigo na casa do seu Deus.

[[v28-9-9]]

^<<v28-9-9,9>>^ Mui profundamente se  corromperam, como nos dias de Gibeá: Ele lembrar-se-á das suas injustiças, visitará os pecados deles.

[[v28-9-10]]

^<<v28-9-10,10>>^ Achei a Israel como uvas no deserto, vi a vossos pais como a fruta temporã da figueira no seu princípio; mas eles foram para Baal-Peor, e se consagraram a essa cousa vergonhosa, e se tornaram abomináveis como aquilo que amaram.

[[v28-9-11]]

^<<v28-9-11,11>>^ Quanto a Efraim, a sua glória como ave voará; não haverá nascimento, não haverá filho, nem concepção.

[[v28-9-12]]

^<<v28-9-12,12>>^ Ainda que venham a criar seus filhos, eu os privarei deles , para que não fique nenhum homem; porque também, ai deles! quando deles me apartar.

[[v28-9-13]]

^<<v28-9-13,13>>^ Efraim, assim como vi a Tiro, está plantado num lugar deleitoso; mas Efraim levará seus filhos ao matador.

[[v28-9-14]]

^<<v28-9-14,14>>^ Dá-lhes, ó Senhor; mas que lhes  darás? dá-lhes uma madre que aborte e seios secos.

[[v28-9-15]]

^<<v28-9-15,15>>^ Toda a sua malícia se acha  em Gilgal, porque ali os aborreci; por causa da maldade das suas obras os lançarei fora de minha casa; não os amarei mais: todos os seus príncipes são  rebeldes.

[[v28-9-16]]

^<<v28-9-16,16>>^ Efraim foi ferido, secou-se a sua raiz; não darão fruto: sim, ainda que gerem, eu matarei os frutos desejáveis do seu ventre.

[[v28-9-17]]

^<<v28-9-17,17>>^ O meu Deus os rejeitará, porque não o ouvem, e vagabundos andarão entre as nações.

'''

xref:028-oseias/028-oseias-008.adoc#v28-8-0[&#60; Capítulo Anterior] | <<v28-9-0,Topo>> | xref:028-oseias/028-oseias-010.adoc#v28-10-0[Próximo Capítulo &#62;]