include::./index.adoc[]

[[v41-16-0]]
=== Marcos, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v41-16-1]]

^<<v41-16-1,1>>^ E, PASSADO o sábado, Maria Madalena, e Maria, mãe  de Tiago, e Salomé, compraram aromas para irem ungi-lo.

[[v41-16-2]]

^<<v41-16-2,2>>^ E, no primeiro dia da semana, foram ao sepulcro, de manhã cedo, ao nascer do sol;

[[v41-16-3]]

^<<v41-16-3,3>>^ E diziam umas às outras: Quem nos revolverá a pedra da porta do sepulcro?

[[v41-16-4]]

^<<v41-16-4,4>>^ E, olhando, viram que já  a pedra estava revolvida; e era ela muito grande.

[[v41-16-5]]

^<<v41-16-5,5>>^ E, entrando no sepulcro, viram um mancebo assentado à direita, vestido de uma  roupa comprida, branca; e ficaram espantadas.

[[v41-16-6]]

^<<v41-16-6,6>>^ Porém ele disse-lhes: Não vos assusteis; buscais a Jesus Nazareno, que foi crucificado; já  ressuscitou, não está aqui; eis aqui o lugar onde o puseram.

[[v41-16-7]]

^<<v41-16-7,7>>^ Mas ide, dizei a seus discípulos, e a Pedro, que ele vai adiante de vós para a Galileia; ali o vereis, como ele vos disse.

[[v41-16-8]]

^<<v41-16-8,8>>^ E, saindo elas apressadamente, fugiram do sepulcro, porque estavam possuídas de temor e assombro; e nada diziam a ninguém, porque temiam.

[[v41-16-9]]

^<<v41-16-9,9>>^ E Jesus , tendo ressuscitado na manhã do primeiro dia da semana, apareceu primeiramente a Maria Madalena, da qual tinha expulsado sete demônios.

[[v41-16-10]]

^<<v41-16-10,10>>^ E , partindo ela, anunciou-o aqueles que tinham estado com ele, os quais estavam tristes, e chorando.

[[v41-16-11]]

^<<v41-16-11,11>>^ E, ouvindo eles que vivia, e que tinha sido visto por ela, não o creram.

[[v41-16-12]]

^<<v41-16-12,12>>^ E depois manifestou-se noutra forma a dois deles, que iam de caminho para o campo.

[[v41-16-13]]

^<<v41-16-13,13>>^ E, indo estes, anunciaram-no aos outros, mas nem ainda estes creram.

[[v41-16-14]]

^<<v41-16-14,14>>^ Finalmente apareceu aos onze, estando eles assentados juntamente, e lançou-lhes em rosto a sua incredulidade e dureza de coração, por não haverem crido nos que o tinham visto já ressuscitado.

[[v41-16-15]]

^<<v41-16-15,15>>^ E disse-lhes: Ide por todo o mundo, pregai o evangelho a toda a criatura.

[[v41-16-16]]

^<<v41-16-16,16>>^ Quem crer e for batizado será salvo; mas quem não crer será condenado.

[[v41-16-17]]

^<<v41-16-17,17>>^ E estes sinais seguirão aos que crerem: Em meu nome expulsarão os demônios; falarão novas línguas;

[[v41-16-18]]

^<<v41-16-18,18>>^ Pegarão nas serpentes; e, se beberem alguma coisa mortífera, não lhes fará dano algum; e porão as mãos sobre os enfermos, e os curarão.

[[v41-16-19]]

^<<v41-16-19,19>>^ Ora o Senhor, depois de lhes ter falado, foi recebido no céu, e assentou-se à direita de Deus.

[[v41-16-20]]

^<<v41-16-20,20>>^ E eles, tendo partido, pregaram por todas as partes, cooperando com eles  o Senhor, e confirmando a palavra com os sinais que se seguiram. Amém.

'''

xref:041-marcos/041-marcos-015.adoc#v41-15-0[&#60; Capítulo Anterior] | <<v41-16-0,Topo>> | xref:042-lucas/042-lucas-001.adoc#v42-1-0[Próximo Capítulo &#62;]