include::./index.adoc[]

[[v41-4-0]]
=== Marcos, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v41-4-1]]

^<<v41-4-1,1>>^ E OUTRA vez começou a ensinar junto do mar, e ajuntou-se a ele grande multidão, de sorte que ele entrou e assentou-se num barco, sobre o mar; e toda a multidão estava em terra junto do mar.

[[v41-4-2]]

^<<v41-4-2,2>>^ E ensinava-lhes muitas coisas  por parábolas e lhes dizia na sua doutrina:

[[v41-4-3]]

^<<v41-4-3,3>>^ Ouvi: Eis que saiu o semeador a semear;

[[v41-4-4]]

^<<v41-4-4,4>>^ E aconteceu que, semeando ele, uma parte da semente  caiu junto do caminho, e vieram as aves do céu, e a comeram;

[[v41-4-5]]

^<<v41-4-5,5>>^ E outra caiu sobre pedregais, onde não havia muita terra, e nasceu logo, porque não tinha terra profunda;

[[v41-4-6]]

^<<v41-4-6,6>>^ Mas, saindo o sol, queimou-se; e, porque não tinha raiz, secou-se.

[[v41-4-7]]

^<<v41-4-7,7>>^ E outra caiu entre espinhos, e, crescendo os espinhos, a sufocaram e não deu fruto.

[[v41-4-8]]

^<<v41-4-8,8>>^ E outra caiu em boa terra e deu fruto, que vingou e cresceu; e um produziu trinta, outro sessenta, e outro cem.

[[v41-4-9]]

^<<v41-4-9,9>>^ E disse-lhes: Quem tem ouvidos para ouvir, ouça.

[[v41-4-10]]

^<<v41-4-10,10>>^ E, quando se achou só, os que estavam junto dele com os doze interrogaram-no acerca da parábola.

[[v41-4-11]]

^<<v41-4-11,11>>^ E ele disse-lhes: A vós vos é dado saber os mistérios do reino de Deus, mas aos que estão de fora todas estas coisas  se dizem por parábolas.

[[v41-4-12]]

^<<v41-4-12,12>>^ Para que, vendo, vejam, e não percebam; e, ouvindo, ouçam, e não entendam; para que se não convertam, e lhes sejam perdoados os pecados.

[[v41-4-13]]

^<<v41-4-13,13>>^ E disse-lhes: Não percebeis esta parábola? como pois entendereis todas as parábolas?

[[v41-4-14]]

^<<v41-4-14,14>>^ O que semeia, semeia a palavra;

[[v41-4-15]]

^<<v41-4-15,15>>^ E os que estão junto do caminho são aqueles em quem a palavra é semeada; mas, tendo-a eles ouvido, vem logo Satanás e tira a palavra que foi semeada nos seus corações.

[[v41-4-16]]

^<<v41-4-16,16>>^ E da mesma sorte os que recebem a semente sobre pedregais; os quais, ouvindo a palavra, logo com prazer a recebem;

[[v41-4-17]]

^<<v41-4-17,17>>^ Mas não têm raiz em si mesmos, antes são temporãos; depois, sobrevindo tribulação ou perseguição por causa da palavra, logo se escandalizam.

[[v41-4-18]]

^<<v41-4-18,18>>^ E outros são os que recebem a semente entre espinhos, os quais ouvem a palavra;

[[v41-4-19]]

^<<v41-4-19,19>>^ Mas os cuidados deste mundo, e os enganos das riquezas e as ambições doutras coisas, entrando, sufocam a palavra, e fica infrutífera.

[[v41-4-20]]

^<<v41-4-20,20>>^ E os que recebem a semente em boa terra são os que ouvem a palavra e a  recebem, e dão fruto, um a trinta, outro a sessenta, outro a cem, por um.

[[v41-4-21]]

^<<v41-4-21,21>>^ E disse-lhes: Vem porventura  a candeia para se meter debaixo do alqueire, ou debaixo da cama? não vem antes  para se colocar no velador?

[[v41-4-22]]

^<<v41-4-22,22>>^ Porque nada há encoberto que não haja de ser manifesto; e nada se faz para ficar  oculto, mas para ser descoberto.

[[v41-4-23]]

^<<v41-4-23,23>>^ Se alguém tem ouvidos para ouvir, ouça.

[[v41-4-24]]

^<<v41-4-24,24>>^ E disse-lhes: Atendei ao que ides ouvir. Com a medida com que medirdes vos medirão a vós, e ser-vos-á ainda acrescentada.

[[v41-4-25]]

^<<v41-4-25,25>>^ Porque ao que tem, ser-lhe-á dado; e, ao que não tem, até o que tem lhe será tirado.

[[v41-4-26]]

^<<v41-4-26,26>>^ E dizia: O reino de Deus é assim como se um homem lançasse semente à terra,

[[v41-4-27]]

^<<v41-4-27,27>>^ E dormisse, e se levantasse de noite ou de dia, e a semente brotasse e crescesse, não sabendo ele como.

[[v41-4-28]]

^<<v41-4-28,28>>^ Porque a terra por si mesma frutifica, primeiro a erva, depois a espiga, por último o grão cheio na espiga.

[[v41-4-29]]

^<<v41-4-29,29>>^ E, quando já  o fruto se mostra, mete-lhe logo a foice, porque está chegada a ceifa.

[[v41-4-30]]

^<<v41-4-30,30>>^ E dizia: A que assemelharemos o reino de Deus? ou com que parábola o representaremos?

[[v41-4-31]]

^<<v41-4-31,31>>^ É como um grão de mostarda, que, quando se semeia na terra, é a mais pequena de todas as sementes que há na terra;

[[v41-4-32]]

^<<v41-4-32,32>>^ Mas, tendo sido semeado, cresce; e faz-se a maior de todas as hortaliças, e cria grandes ramos, de tal maneira que as aves do céu podem aninhar-se debaixo da sua sombra.

[[v41-4-33]]

^<<v41-4-33,33>>^ E com muitas parábolas tais lhes dirigia a palavra, segundo o que podiam compreender.

[[v41-4-34]]

^<<v41-4-34,34>>^ E sem parábolas nunca lhes falava; porém tudo declarava em particular aos seus discípulos.

[[v41-4-35]]

^<<v41-4-35,35>>^ E, naquele dia, sendo já tarde, disse-lhes: Passemos para a outra banda.

[[v41-4-36]]

^<<v41-4-36,36>>^ E eles, deixando a multidão, o levaram consigo, assim como estava, no barco; e havia também com ele outros barquinhos.

[[v41-4-37]]

^<<v41-4-37,37>>^ E levantou-se grande temporal de vento, e subiam as ondas por cima do barco, de maneira que já se enchia.

[[v41-4-38]]

^<<v41-4-38,38>>^ E ele estava na popa dormindo sobre uma almofada, e despertaram-no, dizendo-lhe: Mestre, não se te dá que pereçamos?

[[v41-4-39]]

^<<v41-4-39,39>>^ E ele, despertando, repreendeu o vento, e disse ao mar: Cala-te, aquieta-te. E o vento se aquietou, e houve grande bonança.

[[v41-4-40]]

^<<v41-4-40,40>>^ E disse-lhes: Por que sois tão tímidos? Ainda não tendes fé?

[[v41-4-41]]

^<<v41-4-41,41>>^ E sentiram um grande temor, e diziam uns aos outros: Mas quem é este, que até o vento e o mar lhe obedecem?

'''

xref:041-marcos/041-marcos-003.adoc#v41-3-0[&#60; Capítulo Anterior] | <<v41-4-0,Topo>> | xref:041-marcos/041-marcos-005.adoc#v41-5-0[Próximo Capítulo &#62;]