include::./index.adoc[]

[[v41-9-0]]
=== Marcos, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v41-9-1]]

^<<v41-9-1,1>>^ DIZIA-LHES também: Em verdade vos digo que, dos que aqui estão, alguns há que não provarão a morte sem que vejam chegado o reino de Deus com poder.

[[v41-9-2]]

^<<v41-9-2,2>>^ E seis dias depois Jesus tomou consigo a Pedro, a Tiago, e a João, e os levou sós, em particular, a um alto monte; e transfigurou-se diante deles;

[[v41-9-3]]

^<<v41-9-3,3>>^ E os seus vestidos tornaram-se resplandecentes, em extremo brancos como a neve, tais como nenhum lavadeiro sobre a terra os poderia branquear.

[[v41-9-4]]

^<<v41-9-4,4>>^ E apareceu-lhes Elias com Moisés, e falavam com Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ E Pedro, tomando a palavra, disse a Jesus: Mestre, bom é que nós estejamos aqui, e façamos três cabanas, uma para ti, outra para Moisés, e outra para Elias.

[[v41-9-6]]

^<<v41-9-6,6>>^ Pois não sabia o que dizia, porque estavam assombrados.

[[v41-9-7]]

^<<v41-9-7,7>>^ E desceu uma nuvem que os cobriu com a sua sombra, e saiu da nuvem uma voz que dizia: Este é o meu filho amado; a ele ouvi.

[[v41-9-8]]

^<<v41-9-8,8>>^ E, tendo olhado em roda, ninguém mais viram, senão só Jesus com eles.

[[v41-9-9]]

^<<v41-9-9,9>>^ E, descendo eles do monte, ordenou-lhes que a ninguém contassem o que tinham visto, até que o Filho do homem ressuscitasse dos mortos.

[[v41-9-10]]

^<<v41-9-10,10>>^ E eles retiveram o caso entre si, perguntando uns aos outros que seria aquilo, ressuscitar dos mortos.

[[v41-9-11]]

^<<v41-9-11,11>>^ E interrogaram-no, dizendo: Por que dizem os escribas que é necessário que Elias venha primeiro?

[[v41-9-12]]

^<<v41-9-12,12>>^ E, respondendo ele, disse-lhes: Em verdade Elias virá primeiro, e todas as coisas  restaurará; e, como está escrito do Filho do homem, que ele deva padecer muito e ser aviltado.

[[v41-9-13]]

^<<v41-9-13,13>>^ Digo-vos, porém, que Elias já veio, e fizeram-lhe tudo o que quiseram, como dele está escrito.

[[v41-9-14]]

^<<v41-9-14,14>>^ E, quando se aproximou dos discípulos, viu ao redor deles grande multidão, e alguns  escribas que disputavam com eles.

[[v41-9-15]]

^<<v41-9-15,15>>^ E logo toda a multidão, vendo-o, ficou espantada, e, correndo para ele, o saudaram.

[[v41-9-16]]

^<<v41-9-16,16>>^ E perguntou aos escribas: Que é que discutis com eles?

[[v41-9-17]]

^<<v41-9-17,17>>^ E um da multidão, respondendo, disse: Mestre, trouxe-te o meu filho, que tem um espírito mudo;

[[v41-9-18]]

^<<v41-9-18,18>>^ E este, onde quer que o apanha, despedaça-o, e ele escuma, e range os dentes, e vai-se secando; e eu disse aos teus discípulos que o expulsassem, e não puderam.

[[v41-9-19]]

^<<v41-9-19,19>>^ E ele, respondendo-lhes, disse: Ó geração incrédula! até quando estarei convosco? até quando vos sofrerei ainda? Trazei-mo.

[[v41-9-20]]

^<<v41-9-20,20>>^ E trouxeram-lho; e quando ele o viu, logo o espírito o agitou com violência, e, caindo o endemoninhado  por terra, revolvia-se, escumando.

[[v41-9-21]]

^<<v41-9-21,21>>^ E perguntou ao pai dele: Quanto tempo há que lhe sucede isto? E ele disse-lhe: Desde a infância.

[[v41-9-22]]

^<<v41-9-22,22>>^ E muitas vezes o tem lançado no fogo, e na água, para o destruir; mas, se tu podes fazer alguma coisa , tem compaixão de nós, e ajuda-nos.

[[v41-9-23]]

^<<v41-9-23,23>>^ E Jesus disse-lhe: Se tu podes crer; tudo é  possível ao que crê.

[[v41-9-24]]

^<<v41-9-24,24>>^ E logo o pai do menino, clamando, com lágrimas, disse: Eu creio, Senhor! ajuda a minha incredulidade.

[[v41-9-25]]

^<<v41-9-25,25>>^ E Jesus, vendo que a multidão concorria, repreendeu o espírito imundo, dizendo-lhe: Espírito mudo e surdo, eu te ordeno: Sai dele, e não entres mais nele.

[[v41-9-26]]

^<<v41-9-26,26>>^ E ele, clamando, e agitando-o com violência, saiu; e ficou o menino  como morto, de tal maneira que muitos diziam que estava morto.

[[v41-9-27]]

^<<v41-9-27,27>>^ Mas Jesus, tomando-o pela mão, o ergueu, e ele se levantou.

[[v41-9-28]]

^<<v41-9-28,28>>^ E, quando entrou em casa, os seus discípulos lhe perguntaram à parte: Por que o não pudemos nós expulsar?

[[v41-9-29]]

^<<v41-9-29,29>>^ E disse-lhes: Esta casta não pode sair com coisa alguma, a não ser com oração e jejum.

[[v41-9-30]]

^<<v41-9-30,30>>^ E, tendo partido dali, caminharam pela Galileia, e não queria que alguém o  soubesse;

[[v41-9-31]]

^<<v41-9-31,31>>^ Porque ensinava os seus discípulos, e lhes dizia: O Filho do homem será entregue nas mãos dos homens e matá-lo-ão; e, morto ele ressuscitará ao terceiro dia.

[[v41-9-32]]

^<<v41-9-32,32>>^ Mas eles não entendiam esta palavra, e receavam interrogá-lo.

[[v41-9-33]]

^<<v41-9-33,33>>^ E chegou a Capernaum, e, entrando em casa, perguntou-lhes: Que estáveis vós discutindo pelo caminho?

[[v41-9-34]]

^<<v41-9-34,34>>^ Mas eles calaram-se; porque pelo caminho tinham disputado entre si qual era o maior.

[[v41-9-35]]

^<<v41-9-35,35>>^ E ele, assentando-se, chamou os doze, e disse-lhes: Se alguém quiser ser o primeiro, será o derradeiro de todos e o servo de todos.

[[v41-9-36]]

^<<v41-9-36,36>>^ E, lançando mão de um menino, pô-lo no meio deles, e, tomando-o nos seus braços, disse-lhes:

[[v41-9-37]]

^<<v41-9-37,37>>^ Qualquer que receber um destes meninos em meu nome a mim me recebe; e qualquer que a mim me receber, recebe, não a mim, mas ao que me enviou.

[[v41-9-38]]

^<<v41-9-38,38>>^ E João lhe respondeu, dizendo: Mestre, vimos um que em teu nome expulsava demônios, o qual não nos segue; e nós lho proibimos, porque não nos segue.

[[v41-9-39]]

^<<v41-9-39,39>>^ Jesus, porém, disse: Não lho proibais; porque ninguém há que faça milagre em meu nome e possa logo falar mal de mim.

[[v41-9-40]]

^<<v41-9-40,40>>^ Porque quem não é contra nós é por nós.

[[v41-9-41]]

^<<v41-9-41,41>>^ Porquanto qualquer que vos der a beber um copo d’água em meu nome, porque sois discípulos  de Cristo, em verdade vos digo que não perderá o seu galardão.

[[v41-9-42]]

^<<v41-9-42,42>>^ E qualquer que escandalizar um destes  pequeninos que creem em mim melhor lhe fora que lhe pusessem ao pescoço uma mó de atafona, e que fosse lançado no mar.

[[v41-9-43]]

^<<v41-9-43,43>>^ E, se a tua mão te escandalizar, corta-a: melhor é para ti entrares na vida aleijado do que, tendo duas mãos, ires para o inferno, para o fogo que nunca se apaga;

[[v41-9-44]]

^<<v41-9-44,44>>^ Onde o seu bicho não morre, e o fogo nunca se apaga.

[[v41-9-45]]

^<<v41-9-45,45>>^ E, se o teu pé te escandalizar, corta-o; melhor é para ti entrares coxo na vida do que, tendo dois pés, seres lançado no inferno, no fogo que nunca se apaga;

[[v41-9-46]]

^<<v41-9-46,46>>^ Onde o seu bicho não morre, e o fogo nunca se apaga.

[[v41-9-47]]

^<<v41-9-47,47>>^ E, se o teu olho te escandalizar, lança-o fora; melhor é para ti entrares no reino de Deus com um só olho do que, tendo dois olhos, ser lançado no fogo do inferno;

[[v41-9-48]]

^<<v41-9-48,48>>^ Onde o seu bicho não morre, e o fogo nunca se apaga.

[[v41-9-49]]

^<<v41-9-49,49>>^ Porque cada um será salgado com fogo, e cada sacrifício será salgado com sal.

[[v41-9-50]]

^<<v41-9-50,50>>^ Bom é  o sal; mas, se o sal se tornar insulso, com que o adubareis? tende sal em vós mesmos, e paz uns com os outros.

'''

xref:041-marcos/041-marcos-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-marcos/041-marcos-010.adoc#v41-10-0[Próximo Capítulo &#62;]