include::./index.adoc[]

[[v41-7-0]]
=== Marcos, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v41-7-1]]

^<<v41-7-1,1>>^ E AJUNTARAM-SE a ele os fariseus, e alguns dos escribas que tinham vindo de Jerusalém.

[[v41-7-2]]

^<<v41-7-2,2>>^ E, vendo que alguns dos seus discípulos comiam pão com as mãos impuras, isto é, por lavar, os repreendiam.

[[v41-7-3]]

^<<v41-7-3,3>>^ Porque os fariseus, e todos os judeus, conservando a tradição dos antigos, não comem sem lavar as mãos muitas vezes;

[[v41-7-4]]

^<<v41-7-4,4>>^ E, quando voltam  do mercado, se não se lavarem, não comem. E muitas outras coisas  há que receberam para observar, como  lavar os copos, e os jarros, e os vasos de metal e as camas.

[[v41-7-5]]

^<<v41-7-5,5>>^ Depois perguntaram-lhe os fariseus e os escribas: Por que não andam os teus discípulos conforme a tradição dos antigos, mas comem o pão com as mãos por lavar?

[[v41-7-6]]

^<<v41-7-6,6>>^ E ele, respondendo, disse-lhes: Bem profetizou Isaías acerca de vós, hipócritas, como está escrito: Este povo honra-me com os lábios, mas o seu coração está longe de mim.

[[v41-7-7]]

^<<v41-7-7,7>>^ Em vão, porém, me honram, ensinando doutrinas que são mandamentos de homens.

[[v41-7-8]]

^<<v41-7-8,8>>^ Porque, deixando o mandamento de Deus, retendes a tradição dos homens; como  o lavar dos jarros e dos copos; e fazeis muitas outras coisas  semelhantes a estas.

[[v41-7-9]]

^<<v41-7-9,9>>^ E dizia-lhes: Bem invalidais o mandamento de Deus para guardardes a vossa tradição.

[[v41-7-10]]

^<<v41-7-10,10>>^ Porque Moisés disse: Honra a teu pai e a tua mãe; e quem maldisser, ou o pai ou a mãe, morrerá de morte.

[[v41-7-11]]

^<<v41-7-11,11>>^ Porém vós dizeis: Se um homem disser ao pai ou à mãe: Aquilo que poderias aproveitar de mim é Corbã, isto é, oferta ao Senhor;

[[v41-7-12]]

^<<v41-7-12,12>>^ Nada mais lhe deixais fazer por seu pai ou por sua mãe,

[[v41-7-13]]

^<<v41-7-13,13>>^ Invalidando assim a palavra de Deus pela vossa tradição, que vós ordenastes. E muitas coisas  fazeis semelhantes a estas.

[[v41-7-14]]

^<<v41-7-14,14>>^ E, chamando outra vez a multidão, e disse-lhes: Ouvi-me vós todos, e compreendei.

[[v41-7-15]]

^<<v41-7-15,15>>^ Nada há, fora do homem, que, entrando nele, o possa contaminar; mas o que sai dele isso é que contamina o homem.

[[v41-7-16]]

^<<v41-7-16,16>>^ Se alguém tem ouvidos para ouvir, ouça.

[[v41-7-17]]

^<<v41-7-17,17>>^ Depois, quando deixou a multidão, e entrou em casa, os seus discípulos o interrogavam acerca desta parábola.

[[v41-7-18]]

^<<v41-7-18,18>>^ E ele disse-lhes: Assim também vós estais sem entendimento? Não compreendeis que tudo o que de fora entra no homem não o pode contaminar,

[[v41-7-19]]

^<<v41-7-19,19>>^ Porque não entra no seu coração, mas no ventre, e é lançado fora, ficando puras todas as comidas?

[[v41-7-20]]

^<<v41-7-20,20>>^ E dizia: O que sai do homem isso contamina o homem.

[[v41-7-21]]

^<<v41-7-21,21>>^ Porque do interior do coração dos homens saem os maus pensamentos, os adultérios, as prostituições, os homicídios,

[[v41-7-22]]

^<<v41-7-22,22>>^ Os furtos, a avareza, as maldades, o engano, a dissolução, a inveja, a blasfêmia, a soberba, a loucura.

[[v41-7-23]]

^<<v41-7-23,23>>^ Todos estes males procedem de dentro e contaminam o homem.

[[v41-7-24]]

^<<v41-7-24,24>>^ E, levantando-se dali, foi para os termos de Tiro e de Sidom. E, entrando numa casa, não queria que alguém o soubesse, mas não pôde esconder-se;

[[v41-7-25]]

^<<v41-7-25,25>>^ Porque uma mulher, cuja filha tinha um espírito imundo, ouvindo falar  dele, foi, e lançou-se aos seus pés.

[[v41-7-26]]

^<<v41-7-26,26>>^ E esta mulher era grega, siro-fenícia de nação, e rogava-lhe que expulsasse de sua filha o demônio.

[[v41-7-27]]

^<<v41-7-27,27>>^ Mas Jesus disse-lhe: Deixa primeiro saciar os filhos; porque não convém tomar o pão dos filhos e lançá- lo  aos cachorrinhos.

[[v41-7-28]]

^<<v41-7-28,28>>^ Ela, porém, respondeu, e disse-lhe: Sim, Senhor; mas também os cachorrinhos comem, debaixo da mesa, as migalhas dos filhos.

[[v41-7-29]]

^<<v41-7-29,29>>^ Então ele disse-lhe: Por essa palavra, vai; o demônio já  saiu de tua filha.

[[v41-7-30]]

^<<v41-7-30,30>>^ E, indo ela para sua casa, achou a filha deitada sobre a cama, e que o demônio já tinha saído.

[[v41-7-31]]

^<<v41-7-31,31>>^ E ele, tornando a sair dos termos de Tiro e de Sidom, foi até ao mar da Galileia, pelos confins de Decápolis.

[[v41-7-32]]

^<<v41-7-32,32>>^ E trouxeram-lhe um surdo, que falava dificilmente; e rogaram-lhe que pusesse a mão sobre ele.

[[v41-7-33]]

^<<v41-7-33,33>>^ E, tirando-o à parte de entre a multidão, meteu-lhe os dedos nos ouvidos; e, cuspindo, tocou-lhe na língua.

[[v41-7-34]]

^<<v41-7-34,34>>^ E, levantando os olhos ao céu, suspirou, e disse: Efatá; isto é, Abre-te.

[[v41-7-35]]

^<<v41-7-35,35>>^ E logo se abriram os seus ouvidos, e a prisão da língua se desfez, e falava perfeitamente.

[[v41-7-36]]

^<<v41-7-36,36>>^ E ordenou-lhes que a ninguém o dissessem; mas, quanto mais lho proibia, tanto mais o divulgavam.

[[v41-7-37]]

^<<v41-7-37,37>>^ E, admirando-se sobremaneira, diziam: Tudo faz bem: faz ouvir os surdos e falar os mudos.

'''

xref:041-marcos/041-marcos-006.adoc#v41-6-0[&#60; Capítulo Anterior] | <<v41-7-0,Topo>> | xref:041-marcos/041-marcos-008.adoc#v41-8-0[Próximo Capítulo &#62;]