include::./index.adoc[]

[[v41-11-0]]
=== Marcos, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v41-11-1]]

^<<v41-11-1,1>>^ E, LOGO que se aproximaram de Jerusalém, de Betfagé e de Betânia, junto do monte das Oliveiras, enviou dois dos seus discípulos,

[[v41-11-2]]

^<<v41-11-2,2>>^ E disse-lhes: Ide à aldeia que está defronte de vós; e, logo que ali entrardes, encontrareis preso um jumentinho, sobre o qual ainda não montou homem algum; soltai-o, e trazei- mo.

[[v41-11-3]]

^<<v41-11-3,3>>^ E, se alguém vos disser: Por que fazeis isso? dizei-lhe que o Senhor precisa dele, e logo o deixará trazer para aqui.

[[v41-11-4]]

^<<v41-11-4,4>>^ E foram, e encontraram o jumentinho preso fora da porta, entre dois caminhos, e o soltaram.

[[v41-11-5]]

^<<v41-11-5,5>>^ E alguns dos que ali estavam lhes disseram: Que fazeis, soltando o jumentinho?

[[v41-11-6]]

^<<v41-11-6,6>>^ Eles, porém, disseram-lhes como Jesus lhes tinha mandado; e deixaram-nos ir.

[[v41-11-7]]

^<<v41-11-7,7>>^ E levaram o jumentinho a Jesus, e lançaram, sobre ele os seus vestidos, e assentou-se sobre ele.

[[v41-11-8]]

^<<v41-11-8,8>>^ E muitos estendiam os seus vestidos pelo caminho, e outros cortavam ramos das árvores, e os  espalhavam pelo caminho.

[[v41-11-9]]

^<<v41-11-9,9>>^ E aqueles que iam adiante, e os que seguiam, clamavam, dizendo: Hosana, bendito o que vem em nome do Senhor;

[[v41-11-10]]

^<<v41-11-10,10>>^ Bendito o reino do nosso pai Davi, que vem em nome do Senhor; Hosana nas alturas.

[[v41-11-11]]

^<<v41-11-11,11>>^ E Jesus entrou em Jerusalém, no templo, e, tendo visto tudo em redor, como fosse já tarde, saiu para Betânia com os doze.

[[v41-11-12]]

^<<v41-11-12,12>>^ E, no dia seguinte, quando saíram de Betânia, teve fome,

[[v41-11-13]]

^<<v41-11-13,13>>^ E, vendo de longe uma figueira que tinha folhas, foi ver  se nela acharia alguma coisa; e, chegando a ela, não achou senão folhas, porque não era tempo de figos.

[[v41-11-14]]

^<<v41-11-14,14>>^ E Jesus, falando, disse à figueira: Nunca mais coma alguém fruto de ti. E os seus discípulos ouviram isto.

[[v41-11-15]]

^<<v41-11-15,15>>^ E vieram a Jerusalém; e Jesus, entrando no templo, começou a expulsar os que vendiam e compravam no templo; e derribou as mesas dos cambiadores e as cadeiras dos que vendiam pombas.

[[v41-11-16]]

^<<v41-11-16,16>>^ E não consentia que alguém levasse algum  vaso pelo templo.

[[v41-11-17]]

^<<v41-11-17,17>>^ E os ensinava dizendo: Não está escrito — A minha casa será chamada por todas as nações casa de oração? Mas vós a tendes feito covil de ladrões.

[[v41-11-18]]

^<<v41-11-18,18>>^ E os escribas e príncipes dos sacerdotes, tendo ouvido isto , buscavam ocasião para o matar; pois eles o temiam, porque toda a multidão estava admirada acerca da sua doutrina.

[[v41-11-19]]

^<<v41-11-19,19>>^ E, sendo já tarde, saiu para fora da cidade.

[[v41-11-20]]

^<<v41-11-20,20>>^ E eles, passando pela manhã, viram que a figueira se tinha secado desde as raízes.

[[v41-11-21]]

^<<v41-11-21,21>>^ E Pedro, lembrando-se, disse-lhe: Mestre, eis que a figueira, que tu amaldiçoaste, se secou.

[[v41-11-22]]

^<<v41-11-22,22>>^ E Jesus, respondendo, disse-lhes: Tende fé em Deus;

[[v41-11-23]]

^<<v41-11-23,23>>^ Porque em verdade vos digo que qualquer que disser a este monte: Ergue-te e lança-te no mar; e não duvidar em seu coração, mas crer que se fará aquilo que diz, tudo o que disser lhe será feito.

[[v41-11-24]]

^<<v41-11-24,24>>^ Por isso vos digo que tudo o que pedirdes, orando, crede que o  recebereis, e tê-lo-eis;

[[v41-11-25]]

^<<v41-11-25,25>>^ E, quando estiverdes orando, perdoai, se tendes alguma coisa contra alguém, para que vosso Pai, que está  nos céus, vos perdoe as vossas ofensas;

[[v41-11-26]]

^<<v41-11-26,26>>^ Mas, se vós não perdoardes, também vosso Pai, que está  nos céus, vos não perdoará as vossas ofensas.

[[v41-11-27]]

^<<v41-11-27,27>>^ E tornaram a Jerusalém, e, andando ele pelo templo, os principais dos sacerdotes, e os escribas, e os anciãos se aproximaram dele,

[[v41-11-28]]

^<<v41-11-28,28>>^ E lhe disseram: Com que autoridade fazes tu estas coisas ? ou quem te deu tal autoridade para fazer estas coisas ?

[[v41-11-29]]

^<<v41-11-29,29>>^ Mas Jesus, respondendo, disse-lhes: Também eu vos perguntarei uma coisa, e respondei-me; e então vos direi com que autoridade faço estas coisas :

[[v41-11-30]]

^<<v41-11-30,30>>^ O batismo de João era do céu ou dos homens? respondei-me.

[[v41-11-31]]

^<<v41-11-31,31>>^ E eles arrazoavam entre si, dizendo: Se dissermos: Do céu; ele nos  dirá: Então porque o não crestes?

[[v41-11-32]]

^<<v41-11-32,32>>^ Se, porém dissermos: Dos homens, tememos o povo, porque todos sustentavam que João verdadeiramente era profeta.

[[v41-11-33]]

^<<v41-11-33,33>>^ E, respondendo, disseram a Jesus: Não sabemos. E Jesus lhes replicou: Também eu vos não direi com que autoridade faço estas coisas.

'''

xref:041-marcos/041-marcos-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-marcos/041-marcos-012.adoc#v41-12-0[Próximo Capítulo &#62;]