include::./index.adoc[]

[[v41-13-0]]
=== Marcos, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v41-13-1]]

^<<v41-13-1,1>>^ E, SAINDO ele do templo, disse-lhe um dos seus discípulos: Mestre, olha que pedras, e que edifícios!

[[v41-13-2]]

^<<v41-13-2,2>>^ E, respondendo Jesus, disse-lhe: Vês estes grandes edifícios? Não ficará pedra sobre pedra que não seja derribada.

[[v41-13-3]]

^<<v41-13-3,3>>^ E, assentando-se ele no monte das Oliveiras, defronte do templo, Pedro, e Tiago, e João e André lhe perguntaram em particular:

[[v41-13-4]]

^<<v41-13-4,4>>^ Dize-nos, quando serão essas coisas , e que sinal haverá  quando todas elas estiverem para se cumprir.

[[v41-13-5]]

^<<v41-13-5,5>>^ E Jesus, respondendo-lhes, começou a dizer: Olhai que ninguém vos engane;

[[v41-13-6]]

^<<v41-13-6,6>>^ Porque muitos virão em meu nome, dizendo: Eu sou o Cristo ; e enganarão a muitos.

[[v41-13-7]]

^<<v41-13-7,7>>^ E, quando ouvirdes de guerras e de rumores de guerras, não vos perturbeis; porque assim  deve acontecer; mas ainda não será  o fim.

[[v41-13-8]]

^<<v41-13-8,8>>^ Porque se levantará nação contra nação, e reino contra reino, e haverá terremotos em diversos lugares, e haverá fomes. Isto será o princípio de dores.

[[v41-13-9]]

^<<v41-13-9,9>>^ Mas olhai por vós mesmos, porque vos entregarão aos concílios e às sinagogas; sereis açoitados, e sereis apresentados ante presidentes e reis, por amor de mim, para lhes servir de testemunho.

[[v41-13-10]]

^<<v41-13-10,10>>^ Mas importa que o evangelho seja primeiramente pregado entre todas as gentes.

[[v41-13-11]]

^<<v41-13-11,11>>^ Quando pois vos conduzirem para vos entregarem, não estejais solícitos d’antemão pelo que haveis de dizer; mas, o que vos for dado naquela hora, isso falai; porque não sois vós os que falais, mas o Espírito Santo.

[[v41-13-12]]

^<<v41-13-12,12>>^ E o irmão entregará à morte o irmão, e o pai o filho; e levantar-se-ão os filhos contra os pais, e os farão morrer.

[[v41-13-13]]

^<<v41-13-13,13>>^ E sereis aborrecidos por todos por amor do meu nome; mas quem perseverar até ao fim esse será salvo.

[[v41-13-14]]

^<<v41-13-14,14>>^ Ora, quando vós virdes a abominação do assolamento, que foi predito, estar onde não deve estar (quem lê, entenda), então os que estiverem na Judeia fujam para os montes.

[[v41-13-15]]

^<<v41-13-15,15>>^ E o que estiver sobre o telhado não desça para casa, nem entre a tomar coisa alguma de sua casa;

[[v41-13-16]]

^<<v41-13-16,16>>^ E o que estiver no campo não volte atrás, para tomar o seu vestido.

[[v41-13-17]]

^<<v41-13-17,17>>^ Mas ai das grávidas, e das que criarem naqueles dias!

[[v41-13-18]]

^<<v41-13-18,18>>^ Orai pois, para que a vossa fugida não suceda no inverno;

[[v41-13-19]]

^<<v41-13-19,19>>^ Porque naqueles dias haverá uma  aflição tal, qual nunca houve desde o princípio da criação, que Deus criou, até agora, nem jamais haverá.

[[v41-13-20]]

^<<v41-13-20,20>>^ E, se o Senhor não abreviasse aqueles dias, nenhuma carne se salvaria; mas, por causa dos escolhidos que escolheu, abreviou aqueles dias.

[[v41-13-21]]

^<<v41-13-21,21>>^ E então, se alguém vos disser: Eis aqui o Cristo; ou: Ei-lo ali; não acrediteis.

[[v41-13-22]]

^<<v41-13-22,22>>^ Porque se levantarão falsos cristos, e falsos profetas, e farão sinais e prodígios, para enganarem, se for  possível, até os escolhidos.

[[v41-13-23]]

^<<v41-13-23,23>>^ Mas vós vede; eis que d’antemão vos tenho dito tudo.

[[v41-13-24]]

^<<v41-13-24,24>>^ Ora, naqueles dias, depois daquela aflição, o sol se escurecerá, e a lua não dará a sua luz.

[[v41-13-25]]

^<<v41-13-25,25>>^ E as estrelas cairão do céu, e as forças que estão  nos céus serão abaladas.

[[v41-13-26]]

^<<v41-13-26,26>>^ E então verão vir o Filho do homem nas nuvens, com grande poder e glória.

[[v41-13-27]]

^<<v41-13-27,27>>^ E ele enviará os seus anjos, e ajuntará os seus escolhidos, desde os quatro ventos, da extremidade da terra até a extremidade do céu.

[[v41-13-28]]

^<<v41-13-28,28>>^ Aprendei pois a parábola da figueira: Quando já o seu ramo se torna tenro, e brota folhas, bem sabeis que já  está próximo o verão.

[[v41-13-29]]

^<<v41-13-29,29>>^ Assim também vós, quando virdes sucederem estas coisas , sabei que já  está perto, às portas.

[[v41-13-30]]

^<<v41-13-30,30>>^ Na verdade vos digo que não passará esta geração, sem que todas estas coisas aconteçam.

[[v41-13-31]]

^<<v41-13-31,31>>^ Passará o céu e a terra, mas as minhas palavras não passarão.

[[v41-13-32]]

^<<v41-13-32,32>>^ Mas daquele dia e hora ninguém sabe, nem os anjos que estão  no céu, nem o Filho, senão o Pai.

[[v41-13-33]]

^<<v41-13-33,33>>^ Olhai, vigiai e orai; porque não sabeis quando chegará o tempo.

[[v41-13-34]]

^<<v41-13-34,34>>^ É como se um homem, partindo para fora da terra, deixasse a sua casa, e desse autoridade aos seus servos, e a cada um a sua obra, e mandasse ao porteiro que vigiasse.

[[v41-13-35]]

^<<v41-13-35,35>>^ Vigiai pois, porque não sabeis quando virá o senhor da casa; se à tarde, se à meia-noite, se ao cantar do galo, se pela manhã,

[[v41-13-36]]

^<<v41-13-36,36>>^ Para que, vindo de improviso, não vos ache dormindo.

[[v41-13-37]]

^<<v41-13-37,37>>^ E as coisas que vos digo digo- as  a todos: Vigiai.

'''

xref:041-marcos/041-marcos-012.adoc#v41-12-0[&#60; Capítulo Anterior] | <<v41-13-0,Topo>> | xref:041-marcos/041-marcos-014.adoc#v41-14-0[Próximo Capítulo &#62;]