include::./index.adoc[]

[[v41-14-0]]
=== Marcos, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v41-14-1]]

^<<v41-14-1,1>>^ E DALI a dois dias era a páscoa, e a festa dos pães  asmos; e os principais dos sacerdotes e os escribas buscavam como o prenderiam com dolo, e o matariam.

[[v41-14-2]]

^<<v41-14-2,2>>^ Mas eles diziam: Não na festa, para que porventura se não faça alvoroço entre o povo.

[[v41-14-3]]

^<<v41-14-3,3>>^ E, estando ele em Betânia assentado à mesa , em casa de Simão, o leproso, veio uma mulher, que trazia um vaso de alabastro, com unguento de nardo puro, de muito preço, e, quebrando o vaso, lho derramou sobre a cabeça.

[[v41-14-4]]

^<<v41-14-4,4>>^ E alguns houve que em si mesmos se indignaram, e disseram: Para que se fez este desperdício de unguento?

[[v41-14-5]]

^<<v41-14-5,5>>^ Porque podia vender-se por mais de trezentos dinheiros, e dá-lo aos pobres. E bramavam contra ela.

[[v41-14-6]]

^<<v41-14-6,6>>^ Jesus, porém, disse: Deixai-a, para que a molestais? Ela fez-me boa obra.

[[v41-14-7]]

^<<v41-14-7,7>>^ Porque sempre tendes os pobres convosco, e podeis fazer-lhes bem, quando quiserdes; mas a mim nem sempre me tendes.

[[v41-14-8]]

^<<v41-14-8,8>>^ Esta fez o que podia; antecipou-se a ungir o meu corpo para a sepultura.

[[v41-14-9]]

^<<v41-14-9,9>>^ Em verdade vos digo que, em todas as partes do mundo onde este evangelho for pregado, também o que ela fez será contado para sua memória.

[[v41-14-10]]

^<<v41-14-10,10>>^ E Judas Iscariotes, um dos doze, foi ter com os principais dos sacerdotes para lho entregar.

[[v41-14-11]]

^<<v41-14-11,11>>^ E eles, ouvindo- o , folgaram e prometeram dar-lhe dinheiro; e buscava como o entregaria em ocasião oportuna.

[[v41-14-12]]

^<<v41-14-12,12>>^ E, no primeiro dia dos pães  asmos, quando sacrificavam a páscoa, disseram-lhe os discípulos: Aonde queres que vamos fazer os preparativos para comer a páscoa?

[[v41-14-13]]

^<<v41-14-13,13>>^ E enviou dois dos seus discípulos, e disse-lhes: Ide à cidade, e um homem, que leva um cântaro d’água, vos encontrará; segui-o;

[[v41-14-14]]

^<<v41-14-14,14>>^ E, onde quer que entrar, dizei ao senhor da casa: O Mestre diz: Onde está o aposento em que hei de comer a páscoa com os meus discípulos?

[[v41-14-15]]

^<<v41-14-15,15>>^ E ele vos mostrará um grande cenáculo mobilado e  preparado; preparai-a ali.

[[v41-14-16]]

^<<v41-14-16,16>>^ E, saindo os seus discípulos, foram à cidade, e acharam como lhes tinha dito, e prepararam a páscoa.

[[v41-14-17]]

^<<v41-14-17,17>>^ E, chegada a tarde, foi com os doze,

[[v41-14-18]]

^<<v41-14-18,18>>^ E, quando estavam assentados a comer, disse Jesus: Em verdade vos digo que um de vós, que comigo come, há de trair-me.

[[v41-14-19]]

^<<v41-14-19,19>>^ E eles começaram a entristecer-se e a dizer-lhe um após outro: Porventura  sou eu, Senhor? e outro: Porventura  sou eu, Senhor?

[[v41-14-20]]

^<<v41-14-20,20>>^ Mas ele, respondendo, disse-lhes: É um dos doze, que mete comigo a mão no prato.

[[v41-14-21]]

^<<v41-14-21,21>>^ Na verdade o Filho do homem vai, como dele está escrito, mas ai daquele homem por quem o Filho do homem é traído! bom seria para o tal homem não haver nascido.

[[v41-14-22]]

^<<v41-14-22,22>>^ E, comendo eles, tomou Jesus pão, e, abençoando-o, o partiu e deu- lho , e disse: Tomai, comei, isto é o meu corpo.

[[v41-14-23]]

^<<v41-14-23,23>>^ E, tomando o cálice, e dando graças, deu- lho ; e todos beberam dele.

[[v41-14-24]]

^<<v41-14-24,24>>^ E disse-lhes: Isto é o meu sangue, o sangue  do Novo Testamento, que por muitos é derramado.

[[v41-14-25]]

^<<v41-14-25,25>>^ Em verdade vos digo que não beberei mais do fruto da vide, até àquele dia em que o beber novo, no reino de Deus.

[[v41-14-26]]

^<<v41-14-26,26>>^ E, tendo cantado o hino, saíram para o monte das Oliveiras.

[[v41-14-27]]

^<<v41-14-27,27>>^ E disse-lhes Jesus: Todos vós esta noite vos escandalizareis em mim; porque escrito está: Ferirei o pastor, e as ovelhas se dispersarão.

[[v41-14-28]]

^<<v41-14-28,28>>^ Mas, depois que eu houver ressuscitado, irei adiante de vós para a Galileia.

[[v41-14-29]]

^<<v41-14-29,29>>^ E disse-lhe Pedro: Ainda que todos se escandalizem, nunca, porém, eu.

[[v41-14-30]]

^<<v41-14-30,30>>^ E disse-lhe Jesus: Em verdade te digo que hoje, nesta noite, antes que o galo cante duas vezes, três vezes me negarás.

[[v41-14-31]]

^<<v41-14-31,31>>^ Mas ele disse com mais veemência: Ainda que me seja necessário morrer contigo, de modo nenhum te negarei. E da mesma maneira diziam todos também.

[[v41-14-32]]

^<<v41-14-32,32>>^ E foram a um lugar chamado Getsêmani, e disse aos seus discípulos: Assentai-vos aqui, enquanto eu oro.

[[v41-14-33]]

^<<v41-14-33,33>>^ E tomou consigo a Pedro, e a Tiago, e a João, e começou a ter pavor, e a angustiar-se.

[[v41-14-34]]

^<<v41-14-34,34>>^ E disse-lhes: A minha alma está profundamente triste até a morte: ficai aqui e vigiai.

[[v41-14-35]]

^<<v41-14-35,35>>^ E, tendo ido um pouco mais adiante, prostrou-se em terra; e orou para que, se fosse possível, passasse dele aquela hora.

[[v41-14-36]]

^<<v41-14-36,36>>^ E disse: Aba, Pai, todas as coisas  te são  possíveis; afasta de mim este cálice; não seja, porém, o que eu quero, mas o que tu queres.

[[v41-14-37]]

^<<v41-14-37,37>>^ E, chegando, achou-os dormindo; e disse a Pedro: Simão, dormes? não podes vigiar uma hora?

[[v41-14-38]]

^<<v41-14-38,38>>^ Vigiai e orai, para que não entreis em tentação; o espírito, na verdade, está  pronto, mas a carne é  fraca.

[[v41-14-39]]

^<<v41-14-39,39>>^ E foi outra vez e orou, dizendo as mesmas palavras.

[[v41-14-40]]

^<<v41-14-40,40>>^ E, voltando, achou-os outra vez dormindo, porque os seus olhos estavam carregados, e não sabiam que responder-lhe.

[[v41-14-41]]

^<<v41-14-41,41>>^ E voltou terceira vez, e disse-lhes: Dormi agora, e descansai. Basta; é chegada a hora. Eis que o Filho do homem vai ser entregue nas mãos dos pecadores.

[[v41-14-42]]

^<<v41-14-42,42>>^ Levantai-vos, vamos; eis que está perto o que me trai.

[[v41-14-43]]

^<<v41-14-43,43>>^ E logo, falando ele ainda, veio Judas, que era um dos doze, da parte dos principais dos sacerdotes, e dos escribas e dos anciãos, e com ele uma  grande multidão com espadas e varapaus.

[[v41-14-44]]

^<<v41-14-44,44>>^ Ora, o que o traía, tinha-lhes dado um  sinal, dizendo: Aquele que eu beijar, esse é; prendei-o, e levai- o  com segurança.

[[v41-14-45]]

^<<v41-14-45,45>>^ E, logo que chegou, aproximou-se dele, e disse-lhe: Rabi, Rabi. E beijou-o.

[[v41-14-46]]

^<<v41-14-46,46>>^ E lançaram-lhe as mãos, e o prenderam.

[[v41-14-47]]

^<<v41-14-47,47>>^ E um dos que ali estavam presentes, puxando da espada, feriu o servo do sumo sacerdote, e cortou-lhe uma orelha.

[[v41-14-48]]

^<<v41-14-48,48>>^ E, respondendo Jesus, disse-lhes: Saístes com espadas e varapaus a prender-me, como a um salteador?

[[v41-14-49]]

^<<v41-14-49,49>>^ Todos os dias estava convosco ensinando no templo, e não me prendestes; mas isto é para que as Escrituras se cumpram.

[[v41-14-50]]

^<<v41-14-50,50>>^ Então, deixando-o, todos fugiram.

[[v41-14-51]]

^<<v41-14-51,51>>^ E um  certo mancebo o seguia, envolto em um lençol sobre o corpo  nu. E lançaram-lhe a mão.

[[v41-14-52]]

^<<v41-14-52,52>>^ Mas ele, largando o lençol, fugiu nu.

[[v41-14-53]]

^<<v41-14-53,53>>^ E levaram Jesus ao sumo sacerdote, e ajuntaram-se todos os principais dos sacerdotes, e os anciãos e os escribas.

[[v41-14-54]]

^<<v41-14-54,54>>^ E Pedro o seguiu de longe até dentro do pátio do sumo sacerdote, e estava assentado com os servidores, aquentando-se ao lume.

[[v41-14-55]]

^<<v41-14-55,55>>^ E os principais dos sacerdotes e todo o concílio buscavam algum  testemunho contra Jesus, para o matar, e não o achavam.

[[v41-14-56]]

^<<v41-14-56,56>>^ Porque muitos testificavam falsamente contra ele, mas os testemunhos não eram conformes.

[[v41-14-57]]

^<<v41-14-57,57>>^ E, levantando-se alguns, testificavam falsamente contra ele, dizendo:

[[v41-14-58]]

^<<v41-14-58,58>>^ Nós ouvimos-lhe dizer: Eu derribarei este templo, construído por mãos de homens, e em três dias edificarei outro, não feito por mãos de homens.

[[v41-14-59]]

^<<v41-14-59,59>>^ E nem assim o seu testemunho era conforme.

[[v41-14-60]]

^<<v41-14-60,60>>^ E, levantando-se o sumo sacerdote no sinédrio, perguntou a Jesus, dizendo: Nada respondes? Que testificam estes contra ti?

[[v41-14-61]]

^<<v41-14-61,61>>^ Mas ele calou-se, e nada respondeu. O sumo sacerdote lhe tornou a perguntar, e disse-lhe: És tu o Cristo, Filho do Deus  Bendito?

[[v41-14-62]]

^<<v41-14-62,62>>^ E Jesus disse-lhe: Eu o sou, e vereis o Filho do homem assentado à direita do poder de Deus , e vindo sobre as nuvens do céu.

[[v41-14-63]]

^<<v41-14-63,63>>^ E o sumo sacerdote, rasgando os seus vestidos, disse: Para que necessitamos de mais testemunhas?

[[v41-14-64]]

^<<v41-14-64,64>>^ Vós ouvistes a blasfêmia; que vos parece? E todos o consideraram culpado de morte.

[[v41-14-65]]

^<<v41-14-65,65>>^ E alguns começaram a cuspir nele, e a cobrir-lhe o rosto, e a dar-lhe punhadas, e a dizer-lhe: Profetiza. E os servidores davam-lhe bofetadas.

[[v41-14-66]]

^<<v41-14-66,66>>^ E, estando Pedro embaixo, no átrio, chegou uma das criadas do sumo sacerdote;

[[v41-14-67]]

^<<v41-14-67,67>>^ E, vendo a Pedro, que se estava aquentando, olhou para ele, e disse: Tu também estavas com Jesus Nazareno.

[[v41-14-68]]

^<<v41-14-68,68>>^ Mas ele negou-o dizendo: Não o conheço, nem sei o que dizes. E saiu fora ao alpendre, e o galo cantou.

[[v41-14-69]]

^<<v41-14-69,69>>^ E a criada, vendo-o outra vez, começou a dizer aos que ali estavam: Este é um dos tais.

[[v41-14-70]]

^<<v41-14-70,70>>^ Mas ele o negou outra vez. E pouco depois os que ali estavam disseram outra vez a Pedro: Verdadeiramente tu és um deles, porque és também galileu.

[[v41-14-71]]

^<<v41-14-71,71>>^ E ele começou a imprecar, e a jurar: Não conheço esse homem de quem falais.

[[v41-14-72]]

^<<v41-14-72,72>>^ E o galo cantou segunda vez. E Pedro lembrou-se da palavra que Jesus lhe tinha dito: Antes que o galo cante duas vezes, três vezes me negarás tu. E, retirando-se dali, chorou.

'''

xref:041-marcos/041-marcos-013.adoc#v41-13-0[&#60; Capítulo Anterior] | <<v41-14-0,Topo>> | xref:041-marcos/041-marcos-015.adoc#v41-15-0[Próximo Capítulo &#62;]