include::./index.adoc[]

[[v41-6-0]]
=== Marcos, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v41-6-1]]

^<<v41-6-1,1>>^ E PARTINDO dali, chegou à sua pátria, e os seus discípulos o seguiram.

[[v41-6-2]]

^<<v41-6-2,2>>^ E, chegando o sábado, começou a ensinar na sinagoga; e muitos, ouvindo- o , se admiravam, dizendo: Donde lhe vêm estas coisas ? e que sabedoria é  esta que lhe foi dada? e como se fazem tais maravilhas por suas mãos?

[[v41-6-3]]

^<<v41-6-3,3>>^ Não é este o carpinteiro, filho de Maria, e irmão de Tiago, e de José, e de Judas e de Simão? e não estão aqui conosco suas irmãs? E escandalizavam-se nele.

[[v41-6-4]]

^<<v41-6-4,4>>^ E Jesus lhes dizia: Não há profeta sem honra senão na sua pátria, entre os seus parentes, e na sua casa.

[[v41-6-5]]

^<<v41-6-5,5>>^ E não podia fazer ali obras maravilhosas; somente curou alguns poucos enfermos, impondo-lhes as mãos.

[[v41-6-6]]

^<<v41-6-6,6>>^ E estava admirado da incredulidade deles. E percorreu as aldeias vizinhas, ensinando.

[[v41-6-7]]

^<<v41-6-7,7>>^ Chamou a si  os doze, e começou a enviá-los a dois e dois, e deu-lhes poder sobre os espíritos imundos;

[[v41-6-8]]

^<<v41-6-8,8>>^ E ordenou-lhes que nada tomassem para o caminho, senão somente um bordão; nem alforje, nem pão, nem dinheiro no cinto;

[[v41-6-9]]

^<<v41-6-9,9>>^ Mas que calçassem alparcas, e que não vestissem duas túnicas.

[[v41-6-10]]

^<<v41-6-10,10>>^ E dizia-lhes: Na casa em que entrardes, ficai nela até partirdes de ali.

[[v41-6-11]]

^<<v41-6-11,11>>^ E, quando alguns vos não receberem, nem vos ouvirem, saindo dali, sacudi o pó que estiver debaixo dos vossos pés, em testemunho contra eles. Em verdade vos digo que haverá mais tolerância no dia de juízo para Sodoma e Gomorra do que para os daquela cidade.

[[v41-6-12]]

^<<v41-6-12,12>>^ E, saindo eles, pregavam que se arrependessem.

[[v41-6-13]]

^<<v41-6-13,13>>^ E expulsavam muitos demônios, e ungiam muitos enfermos com óleo, e os curavam.

[[v41-6-14]]

^<<v41-6-14,14>>^ E ouviu isto  o rei Herodes (porque o nome de Jesus se tornara notório), e disse: João, o que batizava, ressuscitou dos mortos, e por isso estas maravilhas operam nele.

[[v41-6-15]]

^<<v41-6-15,15>>^ Outros diziam: É Elias. E diziam outros: É um profeta, ou como um dos profetas.

[[v41-6-16]]

^<<v41-6-16,16>>^ Herodes, porém, ouvindo isto , disse: Este é João, que mandei degolar; ressuscitou dos mortos.

[[v41-6-17]]

^<<v41-6-17,17>>^ Porquanto o mesmo Herodes mandara prender a João, e encerrá-lo manietado no cárcere, por causa de Herodias, mulher de Filipe, seu irmão, porquanto tinha casado com ela.

[[v41-6-18]]

^<<v41-6-18,18>>^ Pois João dizia a Herodes: Não te é lícito possuir a mulher de teu irmão.

[[v41-6-19]]

^<<v41-6-19,19>>^ E Herodias o espiava, e queria matá-lo, mas não podia;

[[v41-6-20]]

^<<v41-6-20,20>>^ Porque Herodes temia a João, sabendo que era  varão justo e santo; e guardava-o com segurança, e fazia muitas coisas , atendendo-o, e de boa vontade o ouvia.

[[v41-6-21]]

^<<v41-6-21,21>>^ E, chegando uma ocasião favorável em que Herodes, no dia dos seus anos, dava uma  ceia aos grandes, e tribunos, e príncipes da Galileia.

[[v41-6-22]]

^<<v41-6-22,22>>^ Entrou a filha da mesma Herodias, e dançou, e agradou a Herodes e aos que estavam com ele à mesa; disse então o rei à menina: Pede-me o que quiseres, e eu to  darei.

[[v41-6-23]]

^<<v41-6-23,23>>^ E jurou-lhe, dizendo: Tudo o que me pedires te darei, até metade do meu reino.

[[v41-6-24]]

^<<v41-6-24,24>>^ E, saindo ela, perguntou à sua mãe: Que pedirei? E ela disse: A cabeça de João Batista.

[[v41-6-25]]

^<<v41-6-25,25>>^ E, entrando logo apressadamente, pediu ao rei, dizendo: Quero que imediatamente me dês num prato a cabeça de João Batista.

[[v41-6-26]]

^<<v41-6-26,26>>^ E o rei entristeceu-se muito; todavia , por causa do juramento e dos que estavam com ele à mesa, não lha quis negar.

[[v41-6-27]]

^<<v41-6-27,27>>^ E, enviando logo o rei o executor, mandou que lhe trouxessem ali a cabeça de João.  E ele foi, e degolou-o na prisão.

[[v41-6-28]]

^<<v41-6-28,28>>^ E trouxe a cabeça num prato, e deu-a à menina, e a menina a deu à sua mãe.

[[v41-6-29]]

^<<v41-6-29,29>>^ E os seus discípulos, tendo ouvido isto , foram, tomaram o seu corpo, e o puseram num sepulcro.

[[v41-6-30]]

^<<v41-6-30,30>>^ E os apóstolos ajuntaram-se a Jesus, e contaram-lhe tudo, tanto o que tinham feito como o que tinham ensinado.

[[v41-6-31]]

^<<v41-6-31,31>>^ E ele disse-lhes: Vinde vós, aqui à parte, a um lugar deserto, e repousai um pouco. Porque havia muitos que iam e vinham, e não tinham tempo para comer.

[[v41-6-32]]

^<<v41-6-32,32>>^ E foram sós num barco para um lugar deserto.

[[v41-6-33]]

^<<v41-6-33,33>>^ E a multidão viu-os partir, e muitos o conheceram; e correram para lá a pé de todas as cidades, e ali chegaram primeiro do que eles, e aproximavam-se dele.

[[v41-6-34]]

^<<v41-6-34,34>>^ E Jesus, saindo, viu uma  grande multidão, e teve compaixão deles, porque eram como ovelhas que não têm pastor; e começou a ensinar-lhes muitas coisas.

[[v41-6-35]]

^<<v41-6-35,35>>^ E, como o dia fosse já muito adiantado, os seus discípulos se aproximaram dele, e lhe disseram: O lugar é deserto, e o dia está  já muito adiantado;

[[v41-6-36]]

^<<v41-6-36,36>>^ Despede-os, para que vão aos lugares e aldeias circunvizinhas, e comprem pão para si; porque não têm que comer.

[[v41-6-37]]

^<<v41-6-37,37>>^ Ele, porém, respondendo, lhes disse: Dai-lhes vós de comer. E eles disseram-lhe: Iremos nós, e compraremos duzentos dinheiros de pão para lhes darmos de comer?

[[v41-6-38]]

^<<v41-6-38,38>>^ E ele disse-lhes: Quantos pães tendes? Ide ver. E, sabendo-o eles, disseram: Cinco pães e dois peixes.

[[v41-6-39]]

^<<v41-6-39,39>>^ E ordenou-lhes que fizessem assentar a todos, em ranchos, sobre a erva verde.

[[v41-6-40]]

^<<v41-6-40,40>>^ E assentaram-se repartidos de cem em cem, e de cinquenta em cinquenta.

[[v41-6-41]]

^<<v41-6-41,41>>^ E, tomando ele os cinco pães e os dois peixes, levantou os olhos ao céu, abençoou e partiu os pães, e deu- os  aos seus discípulos para que os pusessem diante deles. E repartiu os dois peixes por todos;

[[v41-6-42]]

^<<v41-6-42,42>>^ E todos comeram, e ficaram fartos;

[[v41-6-43]]

^<<v41-6-43,43>>^ E levantaram doze cestos cheios de pedaços de pão  e de peixe.

[[v41-6-44]]

^<<v41-6-44,44>>^ E os que comeram os pães eram quase cinco mil homens.

[[v41-6-45]]

^<<v41-6-45,45>>^ E logo obrigou os seus discípulos a subir para o barco, e passar adiante, para a outra banda, a Betsaida, enquanto ele despedia a multidão.

[[v41-6-46]]

^<<v41-6-46,46>>^ E, tendo-os despedido, foi ao monte a orar.

[[v41-6-47]]

^<<v41-6-47,47>>^ E, sobrevindo a tarde, estava o barco no meio do mar e ele sozinho em terra.

[[v41-6-48]]

^<<v41-6-48,48>>^ E vendo que se fatigavam a remar, porque o vento lhes era contrário, perto da quarta vigília da noite aproximou-se deles, andando sobre o mar, e queria passar-lhes adiante,

[[v41-6-49]]

^<<v41-6-49,49>>^ Mas, quando eles o viram andar sobre o mar, cuidaram que era um fantasma, e deram grandes gritos.

[[v41-6-50]]

^<<v41-6-50,50>>^ Porque todos o viam, e perturbaram-se; mas logo falou com eles, e disse-lhes: Tende bom ânimo, sou eu, não temais.

[[v41-6-51]]

^<<v41-6-51,51>>^ E subiu para o barco para estar  com eles, e o vento se aquietou; e entre si ficaram muito assombrados e maravilhados;

[[v41-6-52]]

^<<v41-6-52,52>>^ Pois não tinham compreendido o milagre  dos pães; antes o seu coração estava endurecido.

[[v41-6-53]]

^<<v41-6-53,53>>^ E, quando já estavam na outra banda, dirigiram-se à terra de Genesaré, e ali atracaram.

[[v41-6-54]]

^<<v41-6-54,54>>^ E, saindo eles do barco, logo o conheceram;

[[v41-6-55]]

^<<v41-6-55,55>>^ E, correndo toda a terra em redor, começaram a trazer em leitos, aonde quer que sabiam que ele estava, os que se achavam enfermos.

[[v41-6-56]]

^<<v41-6-56,56>>^ E, onde quer que entrava, ou em cidade, ou aldeias, ou no campo, apresentavam os enfermos nas praças, e rogavam-lhe que os deixasse tocar ao menos na orla do seu vestido, e todos os que lhe tocavam saravam.

'''

xref:041-marcos/041-marcos-005.adoc#v41-5-0[&#60; Capítulo Anterior] | <<v41-6-0,Topo>> | xref:041-marcos/041-marcos-007.adoc#v41-7-0[Próximo Capítulo &#62;]