include::./index.adoc[]

[[v41-3-0]]
=== Marcos, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v41-3-1]]

^<<v41-3-1,1>>^ E OUTRA vez entrou na sinagoga, e estava ali um homem que tinha uma das mãos mirrada.

[[v41-3-2]]

^<<v41-3-2,2>>^ E estavam observando-o se curaria no sábado, para o acusarem.

[[v41-3-3]]

^<<v41-3-3,3>>^ E disse ao homem que tinha a mão mirrada: Levanta-te e vem para o meio.

[[v41-3-4]]

^<<v41-3-4,4>>^ E perguntou-lhes: É lícito no sábado fazer bem, ou fazer mal? salvar a vida, ou matar? E eles calaram-se.

[[v41-3-5]]

^<<v41-3-5,5>>^ E, olhando para eles em redor com indignação, condoendo-se da dureza do seu coração, disse ao homem: Estende a tua mão. E ele a  estendeu, e foi-lhe restituída a sua mão, sã como a outra.

[[v41-3-6]]

^<<v41-3-6,6>>^ E, tendo saído os fariseus, tomaram logo conselho com os herodianos contra ele, procurando ver como o matariam.

[[v41-3-7]]

^<<v41-3-7,7>>^ E retirou-se Jesus com os seus discípulos para o mar, e seguia-o uma grande multidão da Galileia e da Judeia,

[[v41-3-8]]

^<<v41-3-8,8>>^ E de Jerusalém, e da Idumeia, e d’além  do Jordão, e de perto de Tiro e de Sidom; uma grande multidão, que ouvindo quão grandes coisas  fazia, vinha ter com ele.

[[v41-3-9]]

^<<v41-3-9,9>>^ E ele disse aos seus discípulos que lhe tivessem sempre pronto um barquinho junto dele, por causa da multidão, para que o não oprimisse,

[[v41-3-10]]

^<<v41-3-10,10>>^ Porque tinha curado a muitos, de tal maneira que todos quantos tinham algum  mal se arrojavam sobre ele, para lhe tocarem.

[[v41-3-11]]

^<<v41-3-11,11>>^ E os espíritos imundos, vendo-o, prostravam-se diante dele, e clamavam, dizendo: Tu és o Filho de Deus.

[[v41-3-12]]

^<<v41-3-12,12>>^ E ele os ameaçava muito, para que não o manifestassem.

[[v41-3-13]]

^<<v41-3-13,13>>^ E subiu ao monte, e chamou para si  os que ele quis; e vieram a ele.

[[v41-3-14]]

^<<v41-3-14,14>>^ E nomeou doze para que estivessem com ele e os mandasse a pregar;

[[v41-3-15]]

^<<v41-3-15,15>>^ E para que tivessem o poder de curar as enfermidades e expulsar os demônios:

[[v41-3-16]]

^<<v41-3-16,16>>^ A Simão, a quem pôs o nome de Pedro,

[[v41-3-17]]

^<<v41-3-17,17>>^ E a Tiago, filho  de Zebedeu, e a João, irmão de Tiago, aos quais pôs o nome de Boanerges, que significa: Filhos do trovão;

[[v41-3-18]]

^<<v41-3-18,18>>^ E a André, e a Filipe, e a Bartolomeu, e a Mateus, e a Tomé, e a Tiago, filho  de Alfeu, e a Tadeu, e a Simão, o cananeu.

[[v41-3-19]]

^<<v41-3-19,19>>^ E a Judas Iscariotes, o que o entregou.

[[v41-3-20]]

^<<v41-3-20,20>>^ E foram para uma casa. E afluiu outra vez a multidão, de tal maneira que nem sequer podiam comer pão.

[[v41-3-21]]

^<<v41-3-21,21>>^ E, quando os seus ouviram isto , saíram para o prender; porque diziam: Está fora de si.

[[v41-3-22]]

^<<v41-3-22,22>>^ E os escribas, que tinham descido de Jerusalém, diziam: Tem Belzebu, e pelo príncipe dos demônios expulsa os demônios.

[[v41-3-23]]

^<<v41-3-23,23>>^ E, chamando-os a si, disse-lhes por parábolas: Como pode Satanás expulsar Satanás?

[[v41-3-24]]

^<<v41-3-24,24>>^ E, se um reino se dividir contra si mesmo, tal reino não pode subsistir;

[[v41-3-25]]

^<<v41-3-25,25>>^ E, se uma casa se dividir contra si mesma, tal casa não pode subsistir;

[[v41-3-26]]

^<<v41-3-26,26>>^ E, se Satanás se levantar contra si mesmo, e for dividido, não pode subsistir; antes tem fim.

[[v41-3-27]]

^<<v41-3-27,27>>^ Ninguém pode roubar os bens do valente, entrando-lhe em sua casa, se primeiro não manietar o valente; e então roubará a sua casa.

[[v41-3-28]]

^<<v41-3-28,28>>^ Na verdade vos digo que todos os pecados serão perdoados aos filhos dos homens, e toda a sorte de blasfêmias, com que blasfemarem;

[[v41-3-29]]

^<<v41-3-29,29>>^ Qualquer, porém, que blasfemar contra o Espírito Santo, nunca obterá perdão, mas será réu do eterno juízo.

[[v41-3-30]]

^<<v41-3-30,30>>^ (Porque diziam: Tem espírito imundo.)

[[v41-3-31]]

^<<v41-3-31,31>>^ Chegaram então seus  irmãos e sua mãe; e, estando de fora, mandaram-no chamar.

[[v41-3-32]]

^<<v41-3-32,32>>^ E a multidão estava assentada ao redor dele, e disseram-lhe: Eis que tua mãe e teus irmãos te procuram, e estão lá fora.

[[v41-3-33]]

^<<v41-3-33,33>>^ E ele lhes respondeu, dizendo: Quem é minha mãe e meus irmãos?

[[v41-3-34]]

^<<v41-3-34,34>>^ E, olhando em redor para os que estavam assentados junto dele disse: Eis aqui minha mãe e meus irmãos.

[[v41-3-35]]

^<<v41-3-35,35>>^ Porquanto qualquer que fizer a vontade de Deus esse é meu irmão, e minha irmã, e minha mãe.

'''

xref:041-marcos/041-marcos-002.adoc#v41-2-0[&#60; Capítulo Anterior] | <<v41-3-0,Topo>> | xref:041-marcos/041-marcos-004.adoc#v41-4-0[Próximo Capítulo &#62;]