include::./index.adoc[]

[[v43-10-0]]
=== João, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-10-1]]

^<<v43-10-1,1>>^ NA VERDADE, na verdade vos digo que aquele que não entra pela porta no curral das ovelhas, mas sobe por outra parte, é ladrão e salteador.

[[v43-10-2]]

^<<v43-10-2,2>>^ Aquele, porém, que entra pela porta é o pastor das ovelhas.

[[v43-10-3]]

^<<v43-10-3,3>>^ A este o porteiro abre, e as ovelhas ouvem a sua voz, e chama pelo nome às suas ovelhas, e as traz para fora.

[[v43-10-4]]

^<<v43-10-4,4>>^ E, quando tira para fora as suas ovelhas, vai adiante delas, e as ovelhas o seguem, porque conhecem a sua voz;

[[v43-10-5]]

^<<v43-10-5,5>>^ Mas de modo nenhum seguirão o estranho, antes fugirão dele, porque não conhecem a voz dos estranhos.

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus disse-lhes esta parábola; mas eles não entenderam o que era que lhes dizia.

[[v43-10-7]]

^<<v43-10-7,7>>^ Tornou pois Jesus a dizer-lhes: Em verdade vos digo que eu sou a porta das ovelhas.

[[v43-10-8]]

^<<v43-10-8,8>>^ Todos quantos vieram antes de mim são ladrões e salteadores; mas as ovelhas não os ouviram.

[[v43-10-9]]

^<<v43-10-9,9>>^ Eu sou a porta; se alguém entrar por mim, salvar-se-á, e entrará, e sairá, e achará pastagens.

[[v43-10-10]]

^<<v43-10-10,10>>^ O ladrão não vem senão a roubar, a matar, e a destruir: eu vim para que tenham vida, e a tenham com abundância.

[[v43-10-11]]

^<<v43-10-11,11>>^ Eu sou o bom Pastor: o bom Pastor dá a sua vida pelas ovelhas.

[[v43-10-12]]

^<<v43-10-12,12>>^ Mas o mercenário, e o que não é pastor, de quem não são as ovelhas, vê vir o lobo, e deixa as ovelhas, e foge; e o lobo as arrebata e dispersa.

[[v43-10-13]]

^<<v43-10-13,13>>^ Ora o mercenário foge, porque é mercenário, e não tem cuidado das ovelhas.

[[v43-10-14]]

^<<v43-10-14,14>>^ Eu sou o bom Pastor, e conheço as minhas ovelhas, e das minhas sou conhecido.

[[v43-10-15]]

^<<v43-10-15,15>>^ Assim como o Pai me conhece a mim, também eu conheço o Pai, e dou a minha vida pelas ovelhas.

[[v43-10-16]]

^<<v43-10-16,16>>^ Ainda tenho outras ovelhas que não são deste aprisco; também me convém agregar estas, e elas ouvirão a minha voz, e haverá um rebanho e  um Pastor.

[[v43-10-17]]

^<<v43-10-17,17>>^ Por isto o Pai me ama, porque dou a minha vida para tornar a tomá-la.

[[v43-10-18]]

^<<v43-10-18,18>>^ Ninguém ma tira de mim, mas eu de mim mesmo a dou; tenho poder para a dar, e poder para tornar a tomá-la. Este mandamento recebi de meu Pai.

[[v43-10-19]]

^<<v43-10-19,19>>^ Tornou pois a haver divisão entre os judeus por causa destas palavras.

[[v43-10-20]]

^<<v43-10-20,20>>^ E muitos deles diziam: Tem demônio, e está fora de si: porque o ouvis?

[[v43-10-21]]

^<<v43-10-21,21>>^ Diziam outros: Estas palavras não são de endemoninhado; pode porventura um demônio abrir os olhos aos cegos?

[[v43-10-22]]

^<<v43-10-22,22>>^ E em Jerusalém havia a festa da  dedicação, e era inverno.

[[v43-10-23]]

^<<v43-10-23,23>>^ E Jesus andava passeando no templo, no alpendre de Salomão.

[[v43-10-24]]

^<<v43-10-24,24>>^ Rodearam-no pois os judeus, e disseram-lhe: Até quando terás a nossa alma suspensa? Se tu és o Cristo, dize-no-lo abertamente.

[[v43-10-25]]

^<<v43-10-25,25>>^ Respondeu-lhes Jesus: Já vo- lo  tenho dito, e não o  credes. As obras que eu faço, em nome de meu Pai, essas testificam de mim.

[[v43-10-26]]

^<<v43-10-26,26>>^ Mas vós não credes porque não sois das minhas ovelhas, como já  vo-lo tenho dito.

[[v43-10-27]]

^<<v43-10-27,27>>^ As minhas ovelhas ouvem a minha voz, e eu conheço-as, e elas me seguem;

[[v43-10-28]]

^<<v43-10-28,28>>^ E dou-lhes a vida eterna, e nunca hão de perecer, e ninguém as arrebatará da minha mão.

[[v43-10-29]]

^<<v43-10-29,29>>^ Meu Pai, que mas  deu, é maior do que todos; e ninguém pode arrebatá-las da mão de meu Pai.

[[v43-10-30]]

^<<v43-10-30,30>>^ Eu e o Pai somos um.

[[v43-10-31]]

^<<v43-10-31,31>>^ Os judeus pegaram então outra vez em pedras para o apedrejar.

[[v43-10-32]]

^<<v43-10-32,32>>^ Respondeu-lhes Jesus: Tenho-vos mostrado muitas obras boas procedentes de meu Pai; por qual destas obras me apedrejais?

[[v43-10-33]]

^<<v43-10-33,33>>^ Os judeus responderam, dizendo-lhe: Não te apedrejamos por alguma obra boa, mas pela blasfêmia; porque, sendo tu homem, te fazes Deus a ti mesmo.

[[v43-10-34]]

^<<v43-10-34,34>>^ Respondeu-lhes Jesus: Não está escrito na vossa lei: Eu disse: Sois deuses?

[[v43-10-35]]

^<<v43-10-35,35>>^ Pois, se a lei chamou deuses àqueles a quem a palavra de Deus foi dirigida (e a Escritura não pode ser anulada),

[[v43-10-36]]

^<<v43-10-36,36>>^ Àquele a quem o Pai santificou, e enviou ao mundo, vós dizeis: Blasfemas, porque disse: Sou Filho de Deus?

[[v43-10-37]]

^<<v43-10-37,37>>^ Se não faço as obras de meu Pai, não me acrediteis.

[[v43-10-38]]

^<<v43-10-38,38>>^ Mas, se as faço e não credes em mim, crede nas obras: para que conheçais e acrediteis que o Pai está em mim e eu nele.

[[v43-10-39]]

^<<v43-10-39,39>>^ Procuravam pois prendê-lo outra vez, mas ele escapou-se de suas mãos,

[[v43-10-40]]

^<<v43-10-40,40>>^ E retirou-se outra vez para além do Jordão, para o lugar onde João tinha primeiramente batizado; e ali ficou.

[[v43-10-41]]

^<<v43-10-41,41>>^ E muitos iam ter com ele, e diziam: Na verdade João não fez sinal algum, mas tudo quanto João disse deste era verdade.

[[v43-10-42]]

^<<v43-10-42,42>>^ E muitos ali creram nele.

'''

xref:043-joao/043-joao-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-joao/043-joao-011.adoc#v43-11-0[Próximo Capítulo &#62;]