include::./index.adoc[]

[[v43-13-0]]
=== João, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-13-1]]

^<<v43-13-1,1>>^ ORA, antes da festa da páscoa, sabendo Jesus que já  era chegada a sua hora de passar deste mundo para o Pai, como havia amado os seus, que estavam no mundo, amou-os até ao fim.

[[v43-13-2]]

^<<v43-13-2,2>>^ E, acabada a ceia, tendo já o diabo posto no coração de Judas Iscariotes, filho  de Simão, que o traísse,

[[v43-13-3]]

^<<v43-13-3,3>>^ Jesus, sabendo que o Pai tinha depositado nas suas mãos todas as coisas, e que havia saído de Deus e ia para Deus,

[[v43-13-4]]

^<<v43-13-4,4>>^ Levantou-se da ceia, tirou os vestidos, e, tomando uma toalha, cingiu-se.

[[v43-13-5]]

^<<v43-13-5,5>>^ Depois deitou água numa  bacia, e começou a lavar os pés aos discípulos, e a enxugar- lhos  com a toalha com que estava cingido.

[[v43-13-6]]

^<<v43-13-6,6>>^ Aproximou-se pois de Simão Pedro, que lhe disse: Senhor, tu lavas-me os pés a mim?

[[v43-13-7]]

^<<v43-13-7,7>>^ Respondeu Jesus, e disse-lhe: O que eu faço não o sabes tu agora, mas tu o saberás depois.

[[v43-13-8]]

^<<v43-13-8,8>>^ Disse-lhe Pedro: Nunca me lavarás os pés. Respondeu-lhe Jesus: Se eu te não lavar, não tens parte comigo.

[[v43-13-9]]

^<<v43-13-9,9>>^ Disse-lhe Simão Pedro: Senhor, não só os meus pés, mas também as mãos e a cabeça.

[[v43-13-10]]

^<<v43-13-10,10>>^ Disse-lhe Jesus: Aquele que está lavado não necessita de lavar senão os pés, pois no mais todo está limpo. Ora vós estais limpos, mas não todos.

[[v43-13-11]]

^<<v43-13-11,11>>^ Porque bem sabia ele quem o havia de trair; por isso disse: Nem todos estais limpos.

[[v43-13-12]]

^<<v43-13-12,12>>^ Depois que lhes levou os pés, e tomou os seus vestidos, e se assentou outra vez à mesa , disse-lhes: Entendeis o que vos tenho feito?

[[v43-13-13]]

^<<v43-13-13,13>>^ Vós me chamais Mestre e Senhor, e dizeis bem, porque eu o sou.

[[v43-13-14]]

^<<v43-13-14,14>>^ Ora se eu, Senhor e Mestre, vos lavei os pés, vós deveis também lavar os pés uns aos outros.

[[v43-13-15]]

^<<v43-13-15,15>>^ Porque eu vos dei o exemplo, para que, como eu vos fiz, façais vós também.

[[v43-13-16]]

^<<v43-13-16,16>>^ Na verdade, na verdade vos digo que  não é o servo maior do que o seu senhor, nem o enviado maior do que aquele que o enviou.

[[v43-13-17]]

^<<v43-13-17,17>>^ Se sabeis estas coisas , bem-aventurados sois se as fizerdes.

[[v43-13-18]]

^<<v43-13-18,18>>^ Não falo de todos vós; eu bem sei os que tenho escolhido; mas para que se cumpra a Escritura: O que come o  pão comigo, levantou contra mim o seu calcanhar.

[[v43-13-19]]

^<<v43-13-19,19>>^ Desde agora vo-lo digo, antes que aconteça, para que, quando acontecer, acrediteis que eu sou.

[[v43-13-20]]

^<<v43-13-20,20>>^ Na verdade, na verdade vos digo: se alguém receber o que eu enviar, me recebe a mim, e quem me recebe a mim recebe aquele que me enviou.

[[v43-13-21]]

^<<v43-13-21,21>>^ Tendo Jesus dito isto, turbou-se em espírito, e afirmou, dizendo: Na verdade, na verdade vos digo que um de vós me há de trair.

[[v43-13-22]]

^<<v43-13-22,22>>^ Então os discípulos olhavam uns para os outros, duvidando de quem ele falava.

[[v43-13-23]]

^<<v43-13-23,23>>^ Ora um de seus discípulos, aquele a quem Jesus amava, estava reclinado no seio de Jesus.

[[v43-13-24]]

^<<v43-13-24,24>>^ Então Simão Pedro fez sinal a este, para que perguntasse quem era aquele de quem ele falava.

[[v43-13-25]]

^<<v43-13-25,25>>^ E, inclinando-se ele sobre o peito de Jesus, disse-lhe: Senhor, quem é?

[[v43-13-26]]

^<<v43-13-26,26>>^ Jesus respondeu: É aquele a quem eu der o bocado molhado. E, molhando o bocado, o deu a Judas Iscariotes, filho  de Simão.

[[v43-13-27]]

^<<v43-13-27,27>>^ E após o bocado entrou nele Satanás. Disse pois Jesus: O que fazes, faze-o depressa.

[[v43-13-28]]

^<<v43-13-28,28>>^ E nenhum dos que estavam assentados à mesa  compreendeu a que propósito lhe dissera isto ;

[[v43-13-29]]

^<<v43-13-29,29>>^ Porque, como Judas tinha a bolsa, pensavam alguns que Jesus lhe tinha dito: Compra o que nos é necessário para a festa; ou que desse alguma coisa aos pobres.

[[v43-13-30]]

^<<v43-13-30,30>>^ E, tendo Judas tomado o bocado, saiu logo. E era já noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Tendo ele pois saído, disse Jesus: Agora é glorificado o Filho do homem, e Deus é glorificado nele.

[[v43-13-32]]

^<<v43-13-32,32>>^ Se Deus é glorificado nele, também Deus o glorificará em si mesmo, e logo o há de glorificar.

[[v43-13-33]]

^<<v43-13-33,33>>^ Filhinhos, ainda por um pouco estou convosco. Vós me buscareis, e, como tinha dito aos judeus: para onde eu vou não podeis vós ir: eu vo-lo digo também agora.

[[v43-13-34]]

^<<v43-13-34,34>>^ Um novo mandamento vos dou: Que vos ameis uns aos outros: como eu vos amei a vós, que também vós uns aos outros vos ameis.

[[v43-13-35]]

^<<v43-13-35,35>>^ Nisto todos conhecerão que sois meus discípulos, se vos amardes uns aos outros.

[[v43-13-36]]

^<<v43-13-36,36>>^ Disse-lhe Simão Pedro: Senhor, para onde vais? Jesus lhe respondeu: Para onde eu vou não podes agora seguir-me, mas depois me seguirás.

[[v43-13-37]]

^<<v43-13-37,37>>^ Disse-lhe Pedro: Por que não posso seguir-te agora? Por ti darei a minha vida.

[[v43-13-38]]

^<<v43-13-38,38>>^ Respondeu-lhe Jesus: Tu darás a tua vida por mim? Na verdade, na verdade te digo: não cantará o galo enquanto me não tiveres negado três vezes.

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]