include::./index.adoc[]

[[v43-20-0]]
=== João, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-20-1]]

^<<v43-20-1,1>>^ E NO primeiro dia  da semana Maria Madalena foi ao sepulcro de madrugada, sendo ainda escuro, e viu a pedra tirada do sepulcro.

[[v43-20-2]]

^<<v43-20-2,2>>^ Correu pois, e foi a Simão Pedro, e ao outro discípulo, a quem Jesus amava, e disse-lhes: Levaram o Senhor do sepulcro, e não sabemos onde o puseram.

[[v43-20-3]]

^<<v43-20-3,3>>^ Então Pedro saiu com o outro discípulo, e foram ao sepulcro.

[[v43-20-4]]

^<<v43-20-4,4>>^ E os dois corriam juntos, mas o outro discípulo correu mais apressadamente do que Pedro, e chegou primeiro ao sepulcro.

[[v43-20-5]]

^<<v43-20-5,5>>^ E, abaixando-se, viu no chão os lençóis; todavia não entrou.

[[v43-20-6]]

^<<v43-20-6,6>>^ Chegou pois Simão Pedro, que o seguia, e entrou no sepulcro, e viu no chão os lençóis,

[[v43-20-7]]

^<<v43-20-7,7>>^ E que o lenço, que tinha estado sobre a sua cabeça, não estava com os lençóis, mas enrolado num lugar à parte.

[[v43-20-8]]

^<<v43-20-8,8>>^ Então entrou também o outro discípulo, que chegara primeiro ao sepulcro, e viu, e creu.

[[v43-20-9]]

^<<v43-20-9,9>>^ Porque ainda não sabiam a Escritura: que era necessário que ressuscitasse dos mortos.

[[v43-20-10]]

^<<v43-20-10,10>>^ Tornaram pois os discípulos para casa.

[[v43-20-11]]

^<<v43-20-11,11>>^ E Maria estava chorando fora, junto ao sepulcro. Estando ela pois chorando, abaixou-se para o sepulcro;

[[v43-20-12]]

^<<v43-20-12,12>>^ E viu dois anjos vestidos  de branco, assentados onde jazera o corpo de Jesus, um à cabeceira e outro aos pés.

[[v43-20-13]]

^<<v43-20-13,13>>^ E disseram-lhe eles: Mulher, porque choras? Ela lhes disse: Porque levaram o meu Senhor, e não sei onde o puseram.

[[v43-20-14]]

^<<v43-20-14,14>>^ E, tendo dito isto, voltou-se para trás, e viu Jesus em pé, mas não sabia que era Jesus.

[[v43-20-15]]

^<<v43-20-15,15>>^ Disse-lhe Jesus: Mulher, porque choras? Quem buscas? Ela, cuidando que era o hortelão, disse-lhe: Senhor, se tu o levaste, dize-me onde o puseste, e eu o levarei.

[[v43-20-16]]

^<<v43-20-16,16>>^ Disse-lhe Jesus: Maria! Ela voltando-se, disse-lhe: Raboni (que quer dizer, Mestre).

[[v43-20-17]]

^<<v43-20-17,17>>^ Disse-lhe Jesus: Não me detenhas, porque ainda não subi para meu Pai, mas vai para meus irmãos, e dize-lhes que eu subo para meu Pai e vosso Pai, meu Deus e vosso Deus.

[[v43-20-18]]

^<<v43-20-18,18>>^ Maria Madalena foi e anunciou aos discípulos que vira o Senhor, e que ele lhe dissera isto.

[[v43-20-19]]

^<<v43-20-19,19>>^ Chegada pois a tarde de aquele dia, o primeiro da semana, e cerradas as portas onde os discípulos, com medo dos judeus, se tinham ajuntado, chegou Jesus, e pôs-se no meio, e disse-lhes: Paz seja convosco.

[[v43-20-20]]

^<<v43-20-20,20>>^ E, dizendo isto, mostrou-lhes as suas mãos e o lado. De sorte que os discípulos se alegraram, vendo o Senhor.

[[v43-20-21]]

^<<v43-20-21,21>>^ Disse-lhes pois Jesus outra vez: Paz seja convosco, assim como o Pai me enviou, também eu vos envio a vós.

[[v43-20-22]]

^<<v43-20-22,22>>^ E, havendo dito isto, assoprou sobre eles  e disse-lhes: Recebei o Espírito Santo.

[[v43-20-23]]

^<<v43-20-23,23>>^ Àqueles a quem perdoardes os pecados lhe são perdoados: e  àqueles a quem os retiverdes lhes  são retidos.

[[v43-20-24]]

^<<v43-20-24,24>>^ Ora Tomé, um dos doze, chamado Dídimo, não estava com eles quando veio Jesus.

[[v43-20-25]]

^<<v43-20-25,25>>^ Disseram-lhe pois os outros discípulos: Vimos o Senhor. Mas ele disse-lhes: Se eu não vir o sinal dos cravos em suas mãos e não meter o dedo no lugar dos cravos, e não meter a minha mão no seu lado, de maneira nenhuma o crerei.

[[v43-20-26]]

^<<v43-20-26,26>>^ E oito dias depois estavam outra vez o seus discípulos dentro, e com eles Tomé. Chegou Jesus, estando as portas fechadas, e apresentou-se no meio, e disse: Paz seja convosco.

[[v43-20-27]]

^<<v43-20-27,27>>^ Depois disse a Tomé: Põe aqui o teu dedo, e vê as minhas mãos; e chega a tua mão, e mete-a no meu lado; e não sejas incrédulo, mas crente.

[[v43-20-28]]

^<<v43-20-28,28>>^ Tomé respondeu, e disse-lhe: Senhor meu, e Deus meu!

[[v43-20-29]]

^<<v43-20-29,29>>^ Disse-lhe Jesus: Porque me viste, Tomé, creste; bem-aventurados os que não viram e creram.

[[v43-20-30]]

^<<v43-20-30,30>>^ Jesus pois operou também em presença de seus discípulos muitos outros sinais, que não estão escritos neste livro.

[[v43-20-31]]

^<<v43-20-31,31>>^ Estes, porém, foram escritos para que creiais que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenhais vida em seu nome.

'''

xref:043-joao/043-joao-019.adoc#v43-19-0[&#60; Capítulo Anterior] | <<v43-20-0,Topo>> | xref:043-joao/043-joao-021.adoc#v43-21-0[Próximo Capítulo &#62;]