include::./index.adoc[]

[[v43-14-0]]
=== João, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-14-1]]

^<<v43-14-1,1>>^ NÃO se turbe o vosso coração; credes em Deus, crede também em mim.

[[v43-14-2]]

^<<v43-14-2,2>>^ Na casa de meu Pai há muitas moradas; se não fosse assim, eu vo-lo teria dito: vou preparar-vos lugar.

[[v43-14-3]]

^<<v43-14-3,3>>^ E, se eu for, e vos preparar lugar, virei outra vez e vos levarei para mim mesmo, para que onde eu estiver estejais vós também.

[[v43-14-4]]

^<<v43-14-4,4>>^ Mesmo vós sabeis para onde vou, e conheceis o caminho.

[[v43-14-5]]

^<<v43-14-5,5>>^ Disse-lhe Tomé: Senhor, nós não sabemos para onde vais; e como podemos saber o caminho?

[[v43-14-6]]

^<<v43-14-6,6>>^ Disse-lhe Jesus: Eu sou o caminho, e a verdade e a vida. Ninguém vem ao Pai, senão por mim.

[[v43-14-7]]

^<<v43-14-7,7>>^ Se vós me conhecêsseis a mim, também conheceríeis a meu Pai; e já  desde agora o conheceis, e o tendes visto.

[[v43-14-8]]

^<<v43-14-8,8>>^ Disse-lhe Filipe: Senhor, mostra-nos o Pai, o que nos basta.

[[v43-14-9]]

^<<v43-14-9,9>>^ Disse-lhe Jesus: Estou há tanto tempo convosco, e não me tendes conhecido, Filipe? quem me vê a mim vê o Pai: e como dizes tu: Mostra-nos o Pai?

[[v43-14-10]]

^<<v43-14-10,10>>^ Não crês tu que eu estou  no Pai, e que o Pai está em mim? As palavras que eu vos digo não as  digo de mim mesmo, mas o Pai, que está em mim, é quem faz as obras.

[[v43-14-11]]

^<<v43-14-11,11>>^ Crede-me que estou no Pai, e o Pai em mim: crede-me, ao menos, por causa das mesmas obras.

[[v43-14-12]]

^<<v43-14-12,12>>^ Na verdade, na verdade vos digo que aquele que crê em mim também fará as obras que eu faço, e as  fará maiores do que estas; porque eu vou para meu Pai.

[[v43-14-13]]

^<<v43-14-13,13>>^ E tudo quanto pedirdes em meu nome eu o farei, para que o Pai seja glorificado no Filho.

[[v43-14-14]]

^<<v43-14-14,14>>^ Se pedirdes alguma coisa  em meu nome, eu o farei.

[[v43-14-15]]

^<<v43-14-15,15>>^ Se me amardes, guardareis os meus mandamentos.

[[v43-14-16]]

^<<v43-14-16,16>>^ E eu rogarei ao Pai, e ele vos dará outro Consolador, para que fique convosco para sempre;

[[v43-14-17]]

^<<v43-14-17,17>>^ O Espírito de verdade, que o mundo não pode receber, porque não o vê nem o conhece: mas vós o conheceis, porque habita convosco, e estará em vós.

[[v43-14-18]]

^<<v43-14-18,18>>^ Não vos deixarei órfãos; voltarei para vós.

[[v43-14-19]]

^<<v43-14-19,19>>^ Ainda um pouco, e o mundo não me verá mais, mas vós me vereis; porque eu vivo, e vós vivereis.

[[v43-14-20]]

^<<v43-14-20,20>>^ Naquele dia conhecereis que estou  em meu Pai, e vós em mim, e eu em vós.

[[v43-14-21]]

^<<v43-14-21,21>>^ Aquele que tem os meus mandamentos e os guarda esse é o que me ama; e aquele que me ama será amado de meu Pai, e eu o amarei, e me manifestarei a ele.

[[v43-14-22]]

^<<v43-14-22,22>>^ Disse-lhe Judas (não o Iscariotes): Senhor, donde vem que te hás de manifestar a nós, e não ao mundo?

[[v43-14-23]]

^<<v43-14-23,23>>^ Jesus respondeu, e disse-lhe: Se alguém me ama, guardará a minha palavra, e meu Pai o amará, e viremos para ele, e faremos nele morada.

[[v43-14-24]]

^<<v43-14-24,24>>^ Quem me não ama não guarda as minhas palavras; ora a palavra que ouvistes não é minha, mas do Pai que me enviou.

[[v43-14-25]]

^<<v43-14-25,25>>^ Tenho-vos dito isto, estando convosco.

[[v43-14-26]]

^<<v43-14-26,26>>^ Mas aquele Consolador, o Espírito Santo, que o Pai enviará em meu nome, esse vos ensinará todas as coisas, e vos fará lembrar de tudo quanto vos tenho dito.

[[v43-14-27]]

^<<v43-14-27,27>>^ Deixo-vos a paz, a minha paz vos dou: não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.

[[v43-14-28]]

^<<v43-14-28,28>>^ Ouvistes que eu vos disse: Vou, e venho para vós. Se me amásseis, certamente exultaríeis por ter dito: Vou para o Pai; porque o Pai é maior do que eu.

[[v43-14-29]]

^<<v43-14-29,29>>^ Eu vo-lo disse agora antes que aconteça, para que, quando acontecer, vós acrediteis.

[[v43-14-30]]

^<<v43-14-30,30>>^ Já não falarei muito convosco; porque se aproxima o príncipe deste mundo, e nada tem em mim;

[[v43-14-31]]

^<<v43-14-31,31>>^ Mas é para que o mundo saiba que eu amo o Pai, e que faço como o Pai me mandou. Levantai-vos, vamo-nos daqui.

'''

xref:043-joao/043-joao-013.adoc#v43-13-0[&#60; Capítulo Anterior] | <<v43-14-0,Topo>> | xref:043-joao/043-joao-015.adoc#v43-15-0[Próximo Capítulo &#62;]