include::./index.adoc[]

[[v43-17-0]]
=== João, 17
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-17-1]]

^<<v43-17-1,1>>^ JESUS falou assim, e, levantando seus olhos ao céu, disse: Pai, é chegada a hora; glorifica a teu Filho, para que também o teu Filho te glorifique a ti;

[[v43-17-2]]

^<<v43-17-2,2>>^ Assim como lhe deste poder sobre toda a carne, para que dê a vida eterna a todos quantos lhe deste.

[[v43-17-3]]

^<<v43-17-3,3>>^ E a vida eterna é esta: que te conheçam, a ti só, por único Deus verdadeiro, e a Jesus Cristo, a quem enviaste.

[[v43-17-4]]

^<<v43-17-4,4>>^ Eu glorifiquei-te na terra, tendo consumado a obra que me deste a fazer.

[[v43-17-5]]

^<<v43-17-5,5>>^ E agora glorifica-me tu, ó Pai, junto de ti mesmo, com aquela glória que tinha contigo antes que o mundo existisse.

[[v43-17-6]]

^<<v43-17-6,6>>^ Manifestei o teu nome aos homens que do mundo me deste: eram teus, e tu mos deste, e guardaram a tua palavra.

[[v43-17-7]]

^<<v43-17-7,7>>^ Agora já  têm conhecido que tudo quanto me deste provém de ti;

[[v43-17-8]]

^<<v43-17-8,8>>^ Porque lhes dei as palavras que tu me deste; e eles as  receberam, e têm verdadeiramente conhecido que saí de ti; e creram que me enviaste.

[[v43-17-9]]

^<<v43-17-9,9>>^ Eu rogo por eles: não rogo pelo mundo, mas por aqueles que me deste, porque são teus.

[[v43-17-10]]

^<<v43-17-10,10>>^ E todas as minhas coisas são tuas, e as tuas coisas são minhas; e nisso sou glorificado.

[[v43-17-11]]

^<<v43-17-11,11>>^ E eu já não estou mais no mundo; mas eles estão no mundo, e eu vou para ti. Pai santo, guarda em teu nome aqueles que me deste, para que sejam um, assim como nós.

[[v43-17-12]]

^<<v43-17-12,12>>^ Estando eu com eles no mundo, guardava-os em teu nome. Tenho guardado aqueles que tu me deste, e nenhum deles se perdeu, senão o filho da perdição, para que a Escritura se cumprisse.

[[v43-17-13]]

^<<v43-17-13,13>>^ Mas agora vou para ti, e digo isto no mundo, para que tenham a minha alegria completa em si mesmos.

[[v43-17-14]]

^<<v43-17-14,14>>^ Dei-lhes a tua palavra, e o mundo os aborreceu, porque não são do mundo, assim como eu não sou do mundo.

[[v43-17-15]]

^<<v43-17-15,15>>^ Não peço que os tires do mundo, mas que os livres do mal.

[[v43-17-16]]

^<<v43-17-16,16>>^ Não são do mundo, como eu do mundo não sou.

[[v43-17-17]]

^<<v43-17-17,17>>^ Santifica-os na verdade: a tua palavra é a verdade.

[[v43-17-18]]

^<<v43-17-18,18>>^ Assim como tu me enviaste ao mundo, também eu os enviei ao mundo.

[[v43-17-19]]

^<<v43-17-19,19>>^ E por eles me santifico a mim mesmo, para que também eles sejam santificados na verdade.

[[v43-17-20]]

^<<v43-17-20,20>>^ Eu não rogo somente por estes, mas também por aqueles que pela sua palavra hão de crer em mim;

[[v43-17-21]]

^<<v43-17-21,21>>^ Para que todos sejam um, como tu, ó Pai, o és em mim, e eu em ti; que também eles sejam um em nós, para que o mundo creia que tu me enviaste.

[[v43-17-22]]

^<<v43-17-22,22>>^ E eu dei-lhes a glória que a mim me deste, para que sejam um, como nós somos um.

[[v43-17-23]]

^<<v43-17-23,23>>^ Eu neles, e tu em mim, para que eles sejam perfeitos em unidade, e para que o mundo conheça que tu me enviaste a mim, e que os tens amado a eles como me tens amado a mim.

[[v43-17-24]]

^<<v43-17-24,24>>^ Pai, aqueles que me deste quero que, onde eu estiver, também eles estejam comigo, para que vejam a minha glória que me deste: porque tu me hás amado antes da criação do mundo.

[[v43-17-25]]

^<<v43-17-25,25>>^ Pai justo, o mundo não te conheceu; mas eu te conheci, e estes conheceram que tu me enviaste a mim.

[[v43-17-26]]

^<<v43-17-26,26>>^ E eu lhes fiz conhecer o teu nome, e lho  farei conhecer mais, para que o amor com que me tens amado esteja neles, e eu neles esteja.

'''

xref:043-joao/043-joao-016.adoc#v43-16-0[&#60; Capítulo Anterior] | <<v43-17-0,Topo>> | xref:043-joao/043-joao-018.adoc#v43-18-0[Próximo Capítulo &#62;]