include::./index.adoc[]

[[v43-9-0]]
=== João, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-9-1]]

^<<v43-9-1,1>>^ E, PASSANDO Jesus , viu um homem cego de nascença.

[[v43-9-2]]

^<<v43-9-2,2>>^ E os seus discípulos lhe perguntaram, dizendo: Rabi, quem pecou, este ou seus pais, para que nascesse cego?

[[v43-9-3]]

^<<v43-9-3,3>>^ Jesus respondeu: Nem ele pecou nem seus pais; mas foi assim para que se manifestem nele as obras de Deus.

[[v43-9-4]]

^<<v43-9-4,4>>^ Convém que eu faça as obras daquele que me enviou, enquanto é dia: a noite vem, quando ninguém pode trabalhar.

[[v43-9-5]]

^<<v43-9-5,5>>^ Enquanto estou no mundo, sou a luz do mundo.

[[v43-9-6]]

^<<v43-9-6,6>>^ Tendo dito isto, cuspiu na terra, e com a saliva fez lodo, e untou com o lodo os olhos do cego.

[[v43-9-7]]

^<<v43-9-7,7>>^ E disse-lhe: Vai, lava-te no tanque de Siloé (que significa o Enviado). Foi pois, e lavou-se, e voltou vendo.

[[v43-9-8]]

^<<v43-9-8,8>>^ Então os vizinhos, e aqueles que dantes tinham visto que era cego, diziam: Não é este aquele que estava assentado e mendigava?

[[v43-9-9]]

^<<v43-9-9,9>>^ Uns diziam: É este. E  outros: Parece-se com ele. Ele dizia: Sou eu.

[[v43-9-10]]

^<<v43-9-10,10>>^ Diziam-lhe pois: Como se te abriram os olhos?

[[v43-9-11]]

^<<v43-9-11,11>>^ Ele respondeu, e disse: O homem, chamado Jesus, fez lodo, e untou-me os olhos, e disse-me: Vai ao tanque de Siloé, e lava-te. Então fui, e lavei-me, e vi.

[[v43-9-12]]

^<<v43-9-12,12>>^ Disseram-lhe pois: Onde está ele? Respondeu: Não sei.

[[v43-9-13]]

^<<v43-9-13,13>>^ Levaram pois  aos fariseus o que dantes era  cego.

[[v43-9-14]]

^<<v43-9-14,14>>^ E era sábado, quando Jesus fez o lodo e lhe abriu os olhos.

[[v43-9-15]]

^<<v43-9-15,15>>^ Tornaram pois também os fariseus a perguntar-lhe como vira, e ele lhes disse: Pôs-me lodo sobre os olhos, lavei-me, e vejo.

[[v43-9-16]]

^<<v43-9-16,16>>^ Então alguns dos fariseus diziam: Este homem não é de Deus; pois não guarda o sábado. Diziam outros: Como pode um homem pecador fazer tais sinais? E havia dissensão entre eles.

[[v43-9-17]]

^<<v43-9-17,17>>^ Tornaram pois  a dizer ao cego: Tu que dizes daquele que te abriu os olhos? E ele respondeu: Que é profeta.

[[v43-9-18]]

^<<v43-9-18,18>>^ Os judeus, porém, não creram que ele tivesse sido cego, e que agora  visse, enquanto não chamaram os pais do que agora via.

[[v43-9-19]]

^<<v43-9-19,19>>^ E perguntaram-lhes, dizendo: É este o vosso filho, que vós dizeis ter nascido cego? Como pois vê agora?

[[v43-9-20]]

^<<v43-9-20,20>>^ Seus pais lhes responderam, e disseram: Sabemos que este é nosso filho, e que nasceu cego;

[[v43-9-21]]

^<<v43-9-21,21>>^ Mas como agora vê, não sabemos; ou quem lhe tenha aberto os olhos, não sabemos: tem idade, perguntai-lho a ele mesmo; e ele falará por si mesmo.

[[v43-9-22]]

^<<v43-9-22,22>>^ Seus pais disseram isto, porque temiam os judeus. Porquanto já os judeus tinham resolvido que, se alguém confessasse ser ele o Cristo, fosse expulso da sinagoga.

[[v43-9-23]]

^<<v43-9-23,23>>^ Por isso é que seus pais disseram: Tem idade, perguntai-lho a ele mesmo.

[[v43-9-24]]

^<<v43-9-24,24>>^ Chamaram pois pela segunda vez o homem que tinha sido cego, e disseram-lhe: Dá glória a Deus; nós sabemos que esse homem é pecador.

[[v43-9-25]]

^<<v43-9-25,25>>^ Respondeu ele pois, e disse: Se é pecador, não sei: uma coisa sei, e é que, havendo eu sido cego, agora vejo.

[[v43-9-26]]

^<<v43-9-26,26>>^ E tornaram a dizer-lhe: Que te fez ele? Como te abriu os olhos?

[[v43-9-27]]

^<<v43-9-27,27>>^ Respondeu-lhes: Já vo-lo disse, e não ouvistes; para que o quereis tornar a ouvir? Quereis vós porventura fazer-vos também seus discípulos?

[[v43-9-28]]

^<<v43-9-28,28>>^ Então o injuriaram, e disseram: Discípulo dele sejas tu: nós, porém, somos discípulos de Moisés.

[[v43-9-29]]

^<<v43-9-29,29>>^ Nós bem sabemos que Deus falou a Moisés, mas este não sabemos donde é.

[[v43-9-30]]

^<<v43-9-30,30>>^ O homem respondeu, e disse-lhes: Nisto pois está a maravilha, que vós não saibais donde ele é, e me abrisse os olhos;

[[v43-9-31]]

^<<v43-9-31,31>>^ Ora nós sabemos que Deus não ouve a pecadores; mas, se alguém é temente a Deus, e faz a sua vontade, a esse ouve.

[[v43-9-32]]

^<<v43-9-32,32>>^ Desde o princípio do mundo nunca se ouviu que alguém abrisse os olhos a um cego de nascença.

[[v43-9-33]]

^<<v43-9-33,33>>^ Se este não fosse de Deus, nada poderia fazer.

[[v43-9-34]]

^<<v43-9-34,34>>^ Responderam eles, e disseram-lhe: Tu és nascido todo em pecados, e nos ensinas a nós? E expulsaram-no.

[[v43-9-35]]

^<<v43-9-35,35>>^ Jesus ouviu que o tinham expulsado, e, encontrando-o, disse-lhe: Crês tu no Filho de Deus?

[[v43-9-36]]

^<<v43-9-36,36>>^ Ele respondeu, e disse: Quem é ele, Senhor, para que nele creia?

[[v43-9-37]]

^<<v43-9-37,37>>^ E Jesus lhe disse: Tu já o tens visto, e é aquele que fala contigo.

[[v43-9-38]]

^<<v43-9-38,38>>^ Ele disse: Creio, Senhor. E o adorou.

[[v43-9-39]]

^<<v43-9-39,39>>^ E disse-lhe Jesus: Eu vim a este mundo para juízo, a fim de que os que não veem vejam, e os que veem sejam cegos.

[[v43-9-40]]

^<<v43-9-40,40>>^ Aqueles dos fariseus, que estavam com ele, ouvindo isto, disseram-lhe: Também nós somos cegos?

[[v43-9-41]]

^<<v43-9-41,41>>^ Disse-lhes Jesus: Se fôsseis cegos, não teríeis pecado; mas como agora dizeis: Vemos; por isso o vosso pecado permanece.

'''

xref:043-joao/043-joao-008.adoc#v43-8-0[&#60; Capítulo Anterior] | <<v43-9-0,Topo>> | xref:043-joao/043-joao-010.adoc#v43-10-0[Próximo Capítulo &#62;]