include::./index.adoc[]

[[v43-2-0]]
=== João, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-2-1]]

^<<v43-2-1,1>>^ E, AO terceiro dia, fizeram-se umas bodas em Caná da Galileia: e estava ali a mãe de Jesus.

[[v43-2-2]]

^<<v43-2-2,2>>^ E foi também convidado Jesus e os seus discípulos para as bodas.

[[v43-2-3]]

^<<v43-2-3,3>>^ E, faltando o vinho, a mãe de Jesus lhe disse: Não têm vinho.

[[v43-2-4]]

^<<v43-2-4,4>>^ Disse-lhe Jesus: Mulher, que tenho eu contigo? ainda não é chegada a minha hora.

[[v43-2-5]]

^<<v43-2-5,5>>^ Sua mãe disse aos serventes: Fazei tudo quanto ele vos disser.

[[v43-2-6]]

^<<v43-2-6,6>>^ E estavam ali postas seis talhas de pedra, para as purificações dos judeus, e em cada uma cabiam dois ou três almudes.

[[v43-2-7]]

^<<v43-2-7,7>>^ Disse-lhes Jesus: Enchei d’água essas talhas. E encheram-nas até em cima.

[[v43-2-8]]

^<<v43-2-8,8>>^ E disse-lhes: Tirai agora, e levai ao mestre-sala. E levaram.

[[v43-2-9]]

^<<v43-2-9,9>>^ E, logo que o mestre-sala provou a água feita vinho (não sabendo donde viera, se bem que o sabiam os serventes que tinham tirado a água), chamou o mestre-sala ao esposo.

[[v43-2-10]]

^<<v43-2-10,10>>^ E disse-lhe: Todo o homem põe primeiro o vinho bom, e, quando já  têm bebido bem, então o inferior; mas  tu guardaste até agora o bom vinho.

[[v43-2-11]]

^<<v43-2-11,11>>^ Jesus principiou assim os seus sinais em Caná da Galileia, e manifestou a sua glória; e os seus discípulos creram nele.

[[v43-2-12]]

^<<v43-2-12,12>>^ Depois disto desceu a Capernaum, ele, e sua mãe, e seus irmãos, e seus discípulos, e ficaram ali não muitos dias.

[[v43-2-13]]

^<<v43-2-13,13>>^ E estava próxima a páscoa dos judeus, e Jesus subiu a Jerusalém.

[[v43-2-14]]

^<<v43-2-14,14>>^ E achou no templo os que vendiam bois, e ovelhas, e pombos e os cambiadores assentados.

[[v43-2-15]]

^<<v43-2-15,15>>^ E, tendo feito um azorrague de cordéis, lançou todos fora do templo, também os bois e ovelhas; e espalhou o dinheiro dos cambiadores, e derribou as mesas;

[[v43-2-16]]

^<<v43-2-16,16>>^ E disse aos que vendiam pombos: Tirai daqui estes, e não façais da casa de meu Pai casa de venda.

[[v43-2-17]]

^<<v43-2-17,17>>^ E os seus discípulos lembraram-se do que está escrito: O zelo da tua casa me devorará.

[[v43-2-18]]

^<<v43-2-18,18>>^ Responderam pois os judeus, e disseram-lhe: Que sinal nos mostras para fazeres isto?

[[v43-2-19]]

^<<v43-2-19,19>>^ Jesus respondeu, e disse-lhes: Derribai este templo, e em três dias o levantarei.

[[v43-2-20]]

^<<v43-2-20,20>>^ Disseram pois os judeus: Em quarenta e seis anos foi edificado este templo, e tu o levantarás em três dias?

[[v43-2-21]]

^<<v43-2-21,21>>^ Mas ele falava do templo do seu corpo.

[[v43-2-22]]

^<<v43-2-22,22>>^ Quando, pois, ressuscitou dos mortos, os seus discípulos lembraram-se de que lhes dissera isto; e creram na Escritura, e na palavra que Jesus tinha dito.

[[v43-2-23]]

^<<v43-2-23,23>>^ E, estando ele em Jerusalém pela páscoa, durante a festa, muitos, vendo os sinais que fazia, creram no seu nome.

[[v43-2-24]]

^<<v43-2-24,24>>^ Mas o mesmo Jesus não confiava neles, porque a todos conhecia;

[[v43-2-25]]

^<<v43-2-25,25>>^ E não necessitava de que alguém testificasse do homem, porque ele bem sabia o que havia no homem.

'''

xref:043-joao/043-joao-001.adoc#v43-1-0[&#60; Capítulo Anterior] | <<v43-2-0,Topo>> | xref:043-joao/043-joao-003.adoc#v43-3-0[Próximo Capítulo &#62;]