include::./index.adoc[]

[[v43-8-0]]
=== João, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-8-1]]

^<<v43-8-1,1>>^ PORÉM Jesus foi para o monte das Oliveiras;

[[v43-8-2]]

^<<v43-8-2,2>>^ E pela manhã cedo tornou para o templo, e todo o povo vinha ter com ele, e, assentando-se, os ensinava.

[[v43-8-3]]

^<<v43-8-3,3>>^ E os escribas e fariseus trouxeram-lhe uma mulher apanhada em adultério;

[[v43-8-4]]

^<<v43-8-4,4>>^ E, pondo-a no meio, disseram-lhe: Mestre, esta mulher foi apanhada, no próprio ato, adulterando,

[[v43-8-5]]

^<<v43-8-5,5>>^ E na lei nos mandou Moisés que as tais sejam apedrejadas. Tu pois que dizes?

[[v43-8-6]]

^<<v43-8-6,6>>^ Isto diziam eles, tentando-o, para que tivessem de que o acusar. Mas Jesus, inclinando-se, escrevia com o dedo na terra.

[[v43-8-7]]

^<<v43-8-7,7>>^ E, como insistissem, perguntando-lhe, endireitou-se, e disse-lhes: Aquele que dentre vós está sem pecado seja o primeiro que atire pedra contra ela.

[[v43-8-8]]

^<<v43-8-8,8>>^ E, tornando a inclinar-se, escrevia na terra.

[[v43-8-9]]

^<<v43-8-9,9>>^ Quando ouviram isto, saíram um a um, a começar pelos mais velhos até aos últimos; ficou só Jesus e a mulher que estava no meio.

[[v43-8-10]]

^<<v43-8-10,10>>^ E, endireitando-se Jesus e não vendo ninguém mais do que a mulher, disse-lhe: Mulher, onde estão aqueles teus acusadores? Ninguém te condenou?

[[v43-8-11]]

^<<v43-8-11,11>>^ E ela disse: Ninguém, Senhor. E disse-lhe Jesus: Nem eu também te condeno: vai-te, e não peques mais.

[[v43-8-12]]

^<<v43-8-12,12>>^ Falou-lhes pois Jesus outra vez, dizendo: Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida.

[[v43-8-13]]

^<<v43-8-13,13>>^ Disseram-lhe pois os fariseus: Tu testificas de ti mesmo: o teu testemunho não é verdadeiro.

[[v43-8-14]]

^<<v43-8-14,14>>^ Respondeu Jesus, e disse-lhes: Ainda que eu testifico de mim mesmo, o meu testemunho é verdadeiro, porque sei donde vim, e para onde vou; mas vós não sabeis donde venho, nem para onde vou.

[[v43-8-15]]

^<<v43-8-15,15>>^ Vós julgais segundo a carne, eu a ninguém julgo.

[[v43-8-16]]

^<<v43-8-16,16>>^ E, se na verdade julgo, o meu juízo é verdadeiro, porque não sou eu só, mas eu e o Pai que me enviou.

[[v43-8-17]]

^<<v43-8-17,17>>^ E na vossa lei está também escrito que o testemunho de dois homens é verdadeiro.

[[v43-8-18]]

^<<v43-8-18,18>>^ Eu sou o que testifico de mim mesmo, e de mim testifica também  o Pai que me enviou.

[[v43-8-19]]

^<<v43-8-19,19>>^ Disseram-lhe pois: Onde está teu Pai? Jesus respondeu: Não me conheceis a mim, nem a meu Pai: se vós me conhecêsseis a mim, também conheceríeis a meu Pai.

[[v43-8-20]]

^<<v43-8-20,20>>^ Estas palavras disse Jesus no lugar do tesouro, ensinando no templo, e ninguém o prendeu, porque ainda não era chegada a sua hora.

[[v43-8-21]]

^<<v43-8-21,21>>^ Disse-lhes pois Jesus outra vez: Eu retiro-me, e buscar-me-eis, e morrereis no vosso pecado. Para onde eu vou não podeis vós vir.

[[v43-8-22]]

^<<v43-8-22,22>>^ Diziam pois os judeus: Porventura quererá matar-se a si mesmo, pois diz: Para onde eu vou não podeis vós vir?

[[v43-8-23]]

^<<v43-8-23,23>>^ E dizia-lhes: Vós sois de baixo, eu sou de cima; vós sois deste mundo, eu não sou deste mundo.

[[v43-8-24]]

^<<v43-8-24,24>>^ Por isso vos disse que morrereis em vossos pecados, porque, se não crerdes que eu sou, morrereis em vossos pecados.

[[v43-8-25]]

^<<v43-8-25,25>>^ Disseram-lhe pois: Quem és tu? Jesus lhes disse: Isso mesmo que já desde o princípio vos disse.

[[v43-8-26]]

^<<v43-8-26,26>>^ Muito tenho que dizer e julgar de vós, mas aquele que me enviou é verdadeiro; e o que dele tenho ouvido isso falo ao mundo.

[[v43-8-27]]

^<<v43-8-27,27>>^ Mas  não entenderam que ele lhes falava do Pai.

[[v43-8-28]]

^<<v43-8-28,28>>^ Disse-lhes pois Jesus: Quando levantardes o Filho do homem, então conhecereis quem eu sou, e que  nada faço por mim mesmo; mas falo como o Pai me ensinou.

[[v43-8-29]]

^<<v43-8-29,29>>^ E aquele que me enviou está comigo; o Pai não me tem deixado só, porque eu faço sempre o que lhe agrada.

[[v43-8-30]]

^<<v43-8-30,30>>^ Dizendo ele estas coisas , muitos creram nele.

[[v43-8-31]]

^<<v43-8-31,31>>^ Jesus dizia pois aos judeus que criam nele: Se vós permanecerdes na minha palavra, verdadeiramente sereis meus discípulos;

[[v43-8-32]]

^<<v43-8-32,32>>^ E conhecereis a verdade, e a verdade vos libertará.

[[v43-8-33]]

^<<v43-8-33,33>>^ Responderam-lhe: Somos descendência de Abraão, e nunca servimos a ninguém; como dizes tu: Sereis livres?

[[v43-8-34]]

^<<v43-8-34,34>>^ Respondeu-lhes Jesus: Em verdade, em verdade vos digo que todo aquele que comete pecado é servo do pecado.

[[v43-8-35]]

^<<v43-8-35,35>>^ Ora o servo não fica para sempre em casa; o Filho fica para sempre.

[[v43-8-36]]

^<<v43-8-36,36>>^ Se pois o Filho vos libertar, verdadeiramente sereis livres.

[[v43-8-37]]

^<<v43-8-37,37>>^ Bem sei que sois descendência de Abraão; contudo, procurais matar-me, porque a minha palavra não entra em vós.

[[v43-8-38]]

^<<v43-8-38,38>>^ Eu falo do que vi junto de meu Pai, e vós fazeis o que também vistes junto de vosso pai.

[[v43-8-39]]

^<<v43-8-39,39>>^ Responderam, e disseram-lhe: Nosso pai é Abraão. Jesus disse-lhes: Se fôsseis filhos de Abraão, faríeis as obras de Abraão.

[[v43-8-40]]

^<<v43-8-40,40>>^ Mas agora procurais matar-me, a mim, homem que vos tem dito a verdade que de Deus tem ouvido; Abraão não fez isto.

[[v43-8-41]]

^<<v43-8-41,41>>^ Vós fazeis as obras de vosso pai. Disseram-lhe pois: Nós não somos nascidos de prostituição; temos um Pai, que é  Deus.

[[v43-8-42]]

^<<v43-8-42,42>>^ Disse-lhes pois Jesus: Se Deus fosse o vosso Pai, certamente me amaríeis, pois que eu saí, e vim de Deus; não vim de mim mesmo, mas ele me enviou.

[[v43-8-43]]

^<<v43-8-43,43>>^ Por que não entendeis a minha linguagem? por não poderdes ouvir a minha palavra.

[[v43-8-44]]

^<<v43-8-44,44>>^ Vós tendes por pai ao diabo, e quereis satisfazer os desejos de vosso pai: ele foi homicida desde o princípio, e não se firmou na verdade, porque não há verdade nele; quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso, e pai da mentira.

[[v43-8-45]]

^<<v43-8-45,45>>^ Mas, porque vos  digo a verdade, não me  credes.

[[v43-8-46]]

^<<v43-8-46,46>>^ Quem dentre vós me convence de pecado? E se vos digo a verdade, por que não credes?

[[v43-8-47]]

^<<v43-8-47,47>>^ Quem é de Deus escuta as palavras de Deus; por isso vós não as  escutais, porque não sois de Deus.

[[v43-8-48]]

^<<v43-8-48,48>>^ Responderam pois os judeus, e disseram-lhe: Não dizemos nós bem que és samaritano, e que tens demônio?

[[v43-8-49]]

^<<v43-8-49,49>>^ Jesus respondeu: Eu não tenho demônio, antes honro a meu Pai, e vós me desonrais.

[[v43-8-50]]

^<<v43-8-50,50>>^ Eu não busco a minha glória; há quem a  busque, e julgue.

[[v43-8-51]]

^<<v43-8-51,51>>^ Em verdade, em verdade vos digo que, se alguém guardar a minha palavra, nunca verá a morte.

[[v43-8-52]]

^<<v43-8-52,52>>^ Disseram-lhe pois os judeus: Agora conhecemos que tens demônio. Morreu Abraão e os profetas; e tu dizes: Se alguém guardar a minha palavra, nunca provará a morte.

[[v43-8-53]]

^<<v43-8-53,53>>^ És tu maior do que o nosso pai Abraão, que morreu? E também os profetas morreram: quem te fazes tu ser?

[[v43-8-54]]

^<<v43-8-54,54>>^ Jesus respondeu: Se eu me glorifico a mim mesmo, a minha glória não é nada; quem me glorifica é meu Pai, o qual dizeis que é vosso Deus.

[[v43-8-55]]

^<<v43-8-55,55>>^ E vós não o conheceis, mas eu conheço-o: e, se disser que não o conheço, serei mentiroso como vós; mas conheço-o e guardo a sua palavra.

[[v43-8-56]]

^<<v43-8-56,56>>^ Abraão, vosso pai, exultou por ver o meu dia, e viu- o , e alegrou-se.

[[v43-8-57]]

^<<v43-8-57,57>>^ Disseram-lhe pois os judeus: Ainda não tens cinquenta anos, e viste Abraão?

[[v43-8-58]]

^<<v43-8-58,58>>^ Disse-lhes Jesus: Em verdade, em verdade vos digo que antes que Abraão existisse eu sou.

[[v43-8-59]]

^<<v43-8-59,59>>^ Então pegaram em pedras para lhe atirarem; mas Jesus ocultou-se, e saiu do templo, passando pelo meio deles, e assim se retirou.

'''

xref:043-joao/043-joao-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-joao/043-joao-009.adoc#v43-9-0[Próximo Capítulo &#62;]