include::./index.adoc[]

[[v43-1-0]]
=== João, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-1-1]]

^<<v43-1-1,1>>^ NO PRINCÍPIO era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.

[[v43-1-2]]

^<<v43-1-2,2>>^ Ele estava no princípio com Deus.

[[v43-1-3]]

^<<v43-1-3,3>>^ Todas as coisas  foram feitas por ele, e sem ele nada do que foi feito se fez.

[[v43-1-4]]

^<<v43-1-4,4>>^ Nele estava a vida, e a vida era a luz dos homens;

[[v43-1-5]]

^<<v43-1-5,5>>^ E a luz resplandece nas trevas, e as trevas não a compreenderam.

[[v43-1-6]]

^<<v43-1-6,6>>^ Houve um homem enviado de Deus, cujo nome era  João.

[[v43-1-7]]

^<<v43-1-7,7>>^ Este veio para testemunho para que testificasse da luz; para que todos cressem por ele.

[[v43-1-8]]

^<<v43-1-8,8>>^ Não era ele a luz; mas para que testificasse da luz,

[[v43-1-9]]

^<<v43-1-9,9>>^ Ali estava a luz verdadeira, que alumia a todo o homem que vem ao mundo,

[[v43-1-10]]

^<<v43-1-10,10>>^ Estava no mundo, e o mundo foi feito por ele, e o mundo não o conheceu.

[[v43-1-11]]

^<<v43-1-11,11>>^ Veio para o que era seu, e os seus não o receberam.

[[v43-1-12]]

^<<v43-1-12,12>>^ Mas, a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus; aos que creem no seu nome;

[[v43-1-13]]

^<<v43-1-13,13>>^ Os quais não nasceram do sangue, nem da vontade da carne, nem da vontade do varão, mas de Deus.

[[v43-1-14]]

^<<v43-1-14,14>>^ E o Verbo se fez carne, e habitou entre nós, e vimos a sua glória, como a glória do unigênito do Pai, cheio de graça e de verdade.

[[v43-1-15]]

^<<v43-1-15,15>>^ João testificou dele; e clamou, dizendo: Este era aquele de quem eu dizia: O que vem depois de mim é antes de mim, porque foi primeiro do que eu.

[[v43-1-16]]

^<<v43-1-16,16>>^ E todos nós recebemos também da sua plenitude, e graça por graça.

[[v43-1-17]]

^<<v43-1-17,17>>^ Porque a lei foi dada por Moisés; a graça e a verdade vieram por Jesus Cristo.

[[v43-1-18]]

^<<v43-1-18,18>>^ Deus nunca foi visto por alguém. O Filho unigênito, que está no seio do Pai, este o fez conhecer.

[[v43-1-19]]

^<<v43-1-19,19>>^ E este é o testemunho de João, quando os judeus mandaram de Jerusalém sacerdotes e levitas para que lhe perguntassem: quem és tu?

[[v43-1-20]]

^<<v43-1-20,20>>^ E confessou, e não negou; confessou: Eu não sou o Cristo.

[[v43-1-21]]

^<<v43-1-21,21>>^ E perguntaram-lhe: Então quê? És tu Elias? E disse: Não sou. És tu profeta? E respondeu: Não.

[[v43-1-22]]

^<<v43-1-22,22>>^ Disseram-lhe pois: quem és? para que demos resposta àqueles que nos enviaram; que dizes de ti mesmo?

[[v43-1-23]]

^<<v43-1-23,23>>^ Disse: Eu sou  a voz do que clama no deserto: Endireitai o caminho do Senhor, como disse o profeta Isaías.

[[v43-1-24]]

^<<v43-1-24,24>>^ E os que tinham sido enviados eram dos fariseus;

[[v43-1-25]]

^<<v43-1-25,25>>^ E perguntaram-lhe, e disseram-lhe: Por que batizas pois, se tu não és o Cristo, nem Elias, nem o profeta?

[[v43-1-26]]

^<<v43-1-26,26>>^ João respondeu-lhes, dizendo: Eu batizo com água; mas no meio de vós está um a quem vós não conheceis.

[[v43-1-27]]

^<<v43-1-27,27>>^ Este é aquele que vem após mim, que foi antes de mim, do qual eu não sou digno de desatar a correia da alparca,

[[v43-1-28]]

^<<v43-1-28,28>>^ Estas coisas  aconteceram em Betânia, da outra banda do Jordão, onde João estava batizando.

[[v43-1-29]]

^<<v43-1-29,29>>^ No dia seguinte João viu a Jesus, que vinha para ele, e disse: Eis o Cordeiro de Deus, que tira o pecado do mundo.

[[v43-1-30]]

^<<v43-1-30,30>>^ Este é aquele do qual eu disse: Após mim vem um varão que foi antes de mim; porque já  era primeiro do que eu.

[[v43-1-31]]

^<<v43-1-31,31>>^ E eu não o conhecia; mas, para que ele fosse manifestado a Israel, vim eu, por isso, batizando com água.

[[v43-1-32]]

^<<v43-1-32,32>>^ E João testificou, dizendo: Eu vi o Espírito descer do céu como uma  pomba, e repousar sobre ele.

[[v43-1-33]]

^<<v43-1-33,33>>^ E eu não o conhecia, mas o que me mandou a batizar com água, esse me disse: Sobre aquele que vires descer o Espírito, e sobre ele repousar, esse é o que batiza com o Espírito Santo.

[[v43-1-34]]

^<<v43-1-34,34>>^ E eu vi, e tenho testificado que este é o Filho de Deus.

[[v43-1-35]]

^<<v43-1-35,35>>^ No dia seguinte João estava outra vez ali , e dois dos seus discípulos;

[[v43-1-36]]

^<<v43-1-36,36>>^ E, vendo passar a Jesus, disse: Eis aqui o Cordeiro de Deus.

[[v43-1-37]]

^<<v43-1-37,37>>^ E os dois discípulos ouviram-no dizer isto , e seguiram a Jesus.

[[v43-1-38]]

^<<v43-1-38,38>>^ E Jesus, voltando-se e vendo que eles o seguiam, disse-lhes: Que buscais? E eles disseram: Rabi, (que, traduzido, quer dizer Mestre) onde moras?

[[v43-1-39]]

^<<v43-1-39,39>>^ Ele lhes disse: Vinde, e vede. Foram, e viram onde morava, e ficaram com ele aquele dia: e era já quase a hora décima.

[[v43-1-40]]

^<<v43-1-40,40>>^ Era André, irmão de Simão Pedro, um dos dois que ouviram aquilo de João, e o haviam seguido.

[[v43-1-41]]

^<<v43-1-41,41>>^ Este achou primeiro a seu irmão Simão, e disse-lhe: Achamos o Messias (que, traduzido, é o Cristo).

[[v43-1-42]]

^<<v43-1-42,42>>^ E levou-o a Jesus. E, olhando Jesus para ele, disse: Tu és Simão, filho de Jonas; tu serás chamado Cefas (que quer dizer Pedro).

[[v43-1-43]]

^<<v43-1-43,43>>^ No dia seguinte quis Jesus ir à Galileia, e achou a Filipe, e disse-lhe: Segue-me.

[[v43-1-44]]

^<<v43-1-44,44>>^ E Filipe era de Betsaida, cidade de André e de Pedro.

[[v43-1-45]]

^<<v43-1-45,45>>^ Filipe achou Natanael, e disse-lhe: Havemos achado aquele  de quem Moisés escreveu na lei, e os profetas: Jesus de Nazaré, filho de José.

[[v43-1-46]]

^<<v43-1-46,46>>^ Disse-lhe Natanael: Pode vir alguma coisa  boa de Nazaré? Disse-lhe Filipe: Vem, e vê.

[[v43-1-47]]

^<<v43-1-47,47>>^ Jesus viu Natanael vir ter com ele, e disse dele: Eis aqui um verdadeiro israelita, em quem não há dolo.

[[v43-1-48]]

^<<v43-1-48,48>>^ Disse-lhe Natanael: Donde me conheces tu? Jesus respondeu, e disse-lhe: Antes que Filipe te chamasse, te vi eu estando tu debaixo da figueira.

[[v43-1-49]]

^<<v43-1-49,49>>^ Natanael respondeu, e disse-lhe: Rabi, tu és o Filho de Deus, tu és o Rei d’Israel.

[[v43-1-50]]

^<<v43-1-50,50>>^ Jesus respondeu, e disse-lhe: Porque te disse: Vi-te debaixo da figueira, crês? coisas  maiores do que estas verás.

[[v43-1-51]]

^<<v43-1-51,51>>^ E disse-lhe: Na verdade, na verdade vos digo que daqui em diante vereis o céu aberto, e os anjos de Deus subirem e descerem sobre o Filho do homem.

'''

xref:042-lucas/042-lucas-024.adoc#v42-24-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-joao/043-joao-002.adoc#v43-2-0[Próximo Capítulo &#62;]