include::./index.adoc[]

[[v43-15-0]]
=== João, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-15-1]]

^<<v43-15-1,1>>^ EU SOU a videira verdadeira, e meu Pai é o lavrador.

[[v43-15-2]]

^<<v43-15-2,2>>^ Toda a vara em mim, que não dá fruto, a tira; e limpa toda aquela que dá fruto, para que dê mais fruto.

[[v43-15-3]]

^<<v43-15-3,3>>^ Vós já  estais limpos, pela palavra que vos tenho falado.

[[v43-15-4]]

^<<v43-15-4,4>>^ Estai em mim, e eu em vós: como a vara de si mesma não pode dar fruto, se não estiver na videira, assim também vós, se não estiverdes em mim.

[[v43-15-5]]

^<<v43-15-5,5>>^ Eu sou a videira, vós as varas: quem está em mim, e eu nele, esse dá muito fruto; porque sem mim nada podeis fazer.

[[v43-15-6]]

^<<v43-15-6,6>>^ Se alguém não estiver em mim, será lançado fora, como a vara, e secará; e os colhem e lançam no fogo, e ardem.

[[v43-15-7]]

^<<v43-15-7,7>>^ Se vós estiverdes em mim, e as minhas palavras estiverem em vós, pedireis tudo o que quiserdes, e vos será feito.

[[v43-15-8]]

^<<v43-15-8,8>>^ Nisto é glorificado meu Pai, que deis muito fruto; e assim sereis meus discípulos.

[[v43-15-9]]

^<<v43-15-9,9>>^ Como o Pai me amou, também eu vos amei a vós; permanecei no meu amor.

[[v43-15-10]]

^<<v43-15-10,10>>^ Se guardardes os meus mandamentos, permanecereis no meu amor; do mesmo modo que eu tenho guardado os mandamentos de meu Pai, e permaneço no seu amor.

[[v43-15-11]]

^<<v43-15-11,11>>^ Tenho-vos dito isto, para que o meu gozo permaneça em vós, e o vosso gozo seja completo.

[[v43-15-12]]

^<<v43-15-12,12>>^ O meu mandamento é este: Que vos ameis uns aos outros, assim como eu vos amei.

[[v43-15-13]]

^<<v43-15-13,13>>^ Ninguém tem maior amor do que este: de dar alguém a sua vida pelos seus amigos.

[[v43-15-14]]

^<<v43-15-14,14>>^ Vós sereis meus amigos, se fizerdes o que eu vos mando.

[[v43-15-15]]

^<<v43-15-15,15>>^ Já vos não chamarei servos, porque o servo não sabe o que faz o seu senhor, mas tenho-vos chamado amigos, porque tudo quanto ouvi de meu Pai vos tenho feito conhecer.

[[v43-15-16]]

^<<v43-15-16,16>>^ Não me escolhestes vós a mim, mas eu vos escolhi a vós, e vos nomeei, para que vades e deis fruto, e o vosso fruto permaneça; a fim de que tudo quanto em meu nome pedirdes ao Pai ele vo-lo conceda.

[[v43-15-17]]

^<<v43-15-17,17>>^ Isto vos mando: que vos ameis uns aos outros.

[[v43-15-18]]

^<<v43-15-18,18>>^ Se o mundo vos aborrece, sabei que, primeiro do que a vós, me aborreceu a mim.

[[v43-15-19]]

^<<v43-15-19,19>>^ Se vós fôsseis do mundo, o mundo amaria o que era seu, mas, porque não sois do mundo, antes eu vos escolhi do mundo, por isso é que o mundo vos aborrece.

[[v43-15-20]]

^<<v43-15-20,20>>^ Lembrai-vos da palavra que vos disse: Não é o servo maior do que o seu senhor. Se a mim me perseguiram, também vos perseguirão a vós; se guardarem a minha palavra, também guardarão a vossa.

[[v43-15-21]]

^<<v43-15-21,21>>^ Mas tudo isto vos farão por causa do meu nome; porque não conhecem aquele que me enviou.

[[v43-15-22]]

^<<v43-15-22,22>>^ Se eu não viera, nem lhes houvera falado, não teriam pecado, mas agora não têm desculpa do seu pecado.

[[v43-15-23]]

^<<v43-15-23,23>>^ Aquele que me aborrece, aborrece também a meu Pai.

[[v43-15-24]]

^<<v43-15-24,24>>^ Se eu entre eles não fizesse tais obras, quais nenhum outro têm feito, não teriam pecado; mas agora, viram-nas e me aborreceram a mim e a meu Pai.

[[v43-15-25]]

^<<v43-15-25,25>>^ Mas é para que se cumpra a palavra que está escrita na sua lei: Aborreceram-me sem causa.

[[v43-15-26]]

^<<v43-15-26,26>>^ Mas, quando vier o Consolador, que eu da parte do Pai vos hei de enviar, aquele Espírito de verdade, que procede do Pai, ele testificará de mim.

[[v43-15-27]]

^<<v43-15-27,27>>^ E vós também testificareis, pois estivestes comigo desde o princípio.

'''

xref:043-joao/043-joao-014.adoc#v43-14-0[&#60; Capítulo Anterior] | <<v43-15-0,Topo>> | xref:043-joao/043-joao-016.adoc#v43-16-0[Próximo Capítulo &#62;]