include::./index.adoc[]

[[v43-21-0]]
=== João, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-21-1]]

^<<v43-21-1,1>>^ DEPOIS disto manifestou-se Jesus outra vez aos discípulos junto do mar de Tiberíades; e manifestou-se assim:

[[v43-21-2]]

^<<v43-21-2,2>>^ Estavam juntos Simão Pedro, e Tomé, chamado Dídimo, e Natanael, que era de Caná da Galileia, os filhos  de Zebedeu, e outros dois dos seus discípulos.

[[v43-21-3]]

^<<v43-21-3,3>>^ Disse-lhes Simão Pedro: Vou pescar. Dizem-lhes ele: Também nós vamos contigo. Foram, e subiram logo para o barco, e naquela noite nada apanharam.

[[v43-21-4]]

^<<v43-21-4,4>>^ E, sendo já manhã, Jesus se apresentou na praia, mas os discípulos não conheceram que era Jesus.

[[v43-21-5]]

^<<v43-21-5,5>>^ Disse-lhes pois Jesus: Filhos, tendes alguma coisa de comer? Responderam-lhe: Não.

[[v43-21-6]]

^<<v43-21-6,6>>^ E ele lhes disse: Lançai a rede para a banda direita do barco, e achareis. Lançaram-na, pois, e já não a podiam tirar, pela multidão dos peixes.

[[v43-21-7]]

^<<v43-21-7,7>>^ Então aquele discípulo a quem Jesus amava disse a Pedro: É o Senhor. E, quando Simão Pedro ouviu que era o Senhor, cingiu-se com a túnica (porque estava nu) e lançou-se ao mar.

[[v43-21-8]]

^<<v43-21-8,8>>^ E os outros discípulos foram com o barco (porque não estavam distantes da terra senão quase duzentos côvados), levando a rede cheia de peixes.

[[v43-21-9]]

^<<v43-21-9,9>>^ Logo que desceram para terra, viram ali brasas, e um peixe posto em cima, e pão.

[[v43-21-10]]

^<<v43-21-10,10>>^ Disse-lhes Jesus: Trazei dos peixes que agora apanhastes.

[[v43-21-11]]

^<<v43-21-11,11>>^ Simão Pedro subiu e puxou a rede para terra, cheia de cento e cinquenta e três grandes peixes, e, sendo tantos, não se rompeu a rede.

[[v43-21-12]]

^<<v43-21-12,12>>^ Disse-lhes Jesus: Vinde, jantai. E nenhum dos discípulos ousava perguntar-lhe: Quem és tu? sabendo que era o Senhor.

[[v43-21-13]]

^<<v43-21-13,13>>^ Chegou pois Jesus, e tomou o pão, e deu-lho, e, semelhantemente o peixe.

[[v43-21-14]]

^<<v43-21-14,14>>^ E já era a terceira vez que  Jesus se manifestava aos seus discípulos depois de ter ressuscitado dos mortos.

[[v43-21-15]]

^<<v43-21-15,15>>^ E, depois de terem jantado, disse Jesus a Simão Pedro: Simão, filho  de Jonas, amas-me mais do que estes? E ele respondeu: Sim, Senhor; tu sabes que te amo. Disse-lhe: Apascenta os meus cordeiros.

[[v43-21-16]]

^<<v43-21-16,16>>^ Tornou a dizer-lhe segunda vez: Simão, filho  de Jonas, amas-me? Disse-lhe: Sim, Senhor; tu sabes que te amo. Disse-lhe: Apascenta as minhas ovelhas.

[[v43-21-17]]

^<<v43-21-17,17>>^ Disse-lhe terceira vez: Simão, filho  de Jonas, amas-me? Simão entristeceu-se por lhe ter dito terceira vez: Amas-me? e disse-lhe: Senhor, tu sabes tudo; tu sabes que eu te amo. Jesus disse-lhe: Apascenta as minhas ovelhas.

[[v43-21-18]]

^<<v43-21-18,18>>^ Na verdade, na verdade te digo, que , quando eras mais moço, te cingias a ti mesmo, e andavas por onde querias: mas, quando já fores velho, estenderás as tuas mãos; e outro te cingirá, e te levará para onde tu não queiras.

[[v43-21-19]]

^<<v43-21-19,19>>^ E disse isto, significando com que morte havia ele de glorificar a Deus. E, dito isto, disse-lhe: Segue-me.

[[v43-21-20]]

^<<v43-21-20,20>>^ E Pedro, voltando-se, viu que o seguia aquele discípulo a quem Jesus amava, e que na ceia se recostara também sobre o seu peito, e que dissera: Senhor, quem é que te há de trair?

[[v43-21-21]]

^<<v43-21-21,21>>^ Vendo Pedro a este, disse a Jesus: Senhor, e deste que será ?

[[v43-21-22]]

^<<v43-21-22,22>>^ Disse-lhe Jesus: Se eu quero que ele fique até que eu venha, que te importa a ti? Segue-me tu.

[[v43-21-23]]

^<<v43-21-23,23>>^ Divulgou-se pois entre os irmãos este dito, que aquele discípulo não havia de morrer. Jesus, porém, não lhe disse que não morreria; mas: Se eu quero que ele fique até que eu venha, que te importa a ti?

[[v43-21-24]]

^<<v43-21-24,24>>^ Este é o discípulo que testifica destas coisas  e as escreveu: e sabemos que o seu testemunho é verdadeiro.

[[v43-21-25]]

^<<v43-21-25,25>>^ Há, porém, ainda muitas outras coisas  que Jesus fez; e se cada uma das quais fosse escrita, cuido que nem ainda o mundo todo poderia conter os livros que se escrevessem. Amém.

'''

xref:043-joao/043-joao-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-atos/044-atos-001.adoc#v44-1-0[Próximo Capítulo &#62;]