include::./index.adoc[]

[[v43-19-0]]
=== João, 19
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-19-1]]

^<<v43-19-1,1>>^ PILATOS pois tomou então a Jesus, e o  açoitou.

[[v43-19-2]]

^<<v43-19-2,2>>^ E os soldados, tecendo uma coroa de espinhos, lha  puseram sobre a cabeça, e lhe vestiram uma veste de púrpura.

[[v43-19-3]]

^<<v43-19-3,3>>^ E diziam: Salve, Rei dos Judeus. E davam-lhe bofetadas.

[[v43-19-4]]

^<<v43-19-4,4>>^ Então Pilatos saiu outra vez fora, e disse-lhes: Eis aqui vo-lo trago fora; para que saibais que não acho nele crime algum.

[[v43-19-5]]

^<<v43-19-5,5>>^ Saiu pois Jesus fora, levando a coroa de espinhos e o vestido de púrpura. E disse-lhes Pilatos : Eis aqui o homem.

[[v43-19-6]]

^<<v43-19-6,6>>^ Vendo-o pois os principais dos sacerdotes e os servos, clamaram, dizendo: Crucifica- o , crucifica- o.  Disse-lhes Pilatos: Tomai- o  vós, e crucificai- o ; porque eu nenhum crime acho nele.

[[v43-19-7]]

^<<v43-19-7,7>>^ Responderam-lhe os judeus: Nós temos uma lei, e, segundo a nossa lei, deve morrer, porque se fez Filho de Deus.

[[v43-19-8]]

^<<v43-19-8,8>>^ E Pilatos, quando ouviu esta palavra, mais atemorizado ficou.

[[v43-19-9]]

^<<v43-19-9,9>>^ E entrou outra vez na audiência, e disse a Jesus: Donde és tu? Mas Jesus não lhe deu resposta.

[[v43-19-10]]

^<<v43-19-10,10>>^ Disse-lhe pois Pilatos: Não me falas a mim? não sabes tu que tenho poder para te crucificar e tenho poder para te soltar?

[[v43-19-11]]

^<<v43-19-11,11>>^ Respondeu Jesus: Nenhum poder terias contra mim, se de cima te não fosse dado; mas aquele que me entregou a ti maior pecado tem.

[[v43-19-12]]

^<<v43-19-12,12>>^ Desde então Pilatos procurava soltá-lo; mas os judeus clamavam, dizendo: Se soltas este, não és amigo do César: qualquer que se faz rei é contra o César.

[[v43-19-13]]

^<<v43-19-13,13>>^ Ouvindo pois Pilatos este dito, levou Jesus para fora, e assentou-se no tribunal, no lugar chamado Litostrotos, e em hebraico Gábata.

[[v43-19-14]]

^<<v43-19-14,14>>^ E era a preparação da páscoa, e quase à hora sexta; e disse aos judeus: Eis aqui o vosso rei.

[[v43-19-15]]

^<<v43-19-15,15>>^ Mas eles bradaram: Tira, tira, crucifica-o. Disse-lhes Pilatos: Hei de crucificar o vosso Rei? Responderam os principais dos sacerdotes: Não temos rei, senão o César.

[[v43-19-16]]

^<<v43-19-16,16>>^ Então entregou-lho, para que fosse crucificado. E tomaram a Jesus, e o levaram.

[[v43-19-17]]

^<<v43-19-17,17>>^ E, levando ele às costas a sua cruz, saiu para o lugar chamado Caveira, que em hebraico se chama Gólgota.

[[v43-19-18]]

^<<v43-19-18,18>>^ Onde o crucificaram, e com ele outros dois, um de cada lado, e Jesus no meio.

[[v43-19-19]]

^<<v43-19-19,19>>^ E Pilatos escreveu também um título, e pô-lo em cima da cruz; e nele  estava escrito: Jesus Nazareno, Rei dos Judeus .

[[v43-19-20]]

^<<v43-19-20,20>>^ E muitos dos judeus leram este título; porque o lugar onde Jesus estava crucificado era próximo da cidade; e estava escrito em hebraico, grego e  latim.

[[v43-19-21]]

^<<v43-19-21,21>>^ Diziam pois os principais sacerdotes dos judeus a Pilatos: Não escrevas, Rei dos Judeus; mas que ele disse: Sou Rei dos Judeus.

[[v43-19-22]]

^<<v43-19-22,22>>^ Respondeu Pilatos: O que escrevi, escrevi.

[[v43-19-23]]

^<<v43-19-23,23>>^ Tendo pois os soldados crucificado a Jesus, tomaram os seus vestidos, e fizeram quatro partes para cada soldado uma parte; e também a túnica. A túnica, porém, tecida toda d’alto a baixo , não tinha costura.

[[v43-19-24]]

^<<v43-19-24,24>>^ Disseram pois uns aos outros: Não a rasguemos, mas lancemos sortes sobre ela, para ver  de quem será. Para que se cumprisse a Escritura que diz: Dividiram entre si os meus vestidos, e sobre a minha vestidura lançaram sortes. Os soldados, pois, fizeram estas coisas.

[[v43-19-25]]

^<<v43-19-25,25>>^ E junto à cruz de Jesus estava sua mãe, e a irmã de sua mãe, Maria de Cléofas, e Maria Madalena.

[[v43-19-26]]

^<<v43-19-26,26>>^ Ora Jesus, vendo ali sua  mãe, e que o discípulo a quem ele amava estava presente, disse a sua mãe: Mulher, eis aí o teu filho.

[[v43-19-27]]

^<<v43-19-27,27>>^ Depois disse ao discípulo: Eis aí tua mãe. E desde aquela hora o discípulo a recebeu em sua casa.

[[v43-19-28]]

^<<v43-19-28,28>>^ Depois, sabendo Jesus que já todas as coisas  estavam terminadas, para que a Escritura se cumprisse, disse: Tenho sede.

[[v43-19-29]]

^<<v43-19-29,29>>^ Estava pois ali um vaso cheio de vinagre. E encheram de vinagre uma esponja, e, pondo- a  num hissope, lha  chegaram à boca.

[[v43-19-30]]

^<<v43-19-30,30>>^ E, quando Jesus tomou o vinagre, disse: Está consumado. E, inclinando a cabeça, entregou o espírito.

[[v43-19-31]]

^<<v43-19-31,31>>^ Os judeus, pois, para que no sábado não ficassem os corpos na cruz, visto como era a preparação (pois era grande o dia de sábado), rogaram a Pilatos que se lhes quebrassem as pernas, e fossem tirados.

[[v43-19-32]]

^<<v43-19-32,32>>^ Foram pois os soldados, e, na verdade, quebraram as pernas ao primeiro, e ao outro que com ele fora crucificado;

[[v43-19-33]]

^<<v43-19-33,33>>^ Mas, vindo a Jesus, e vendo-o já morto, não lhe quebraram as pernas.

[[v43-19-34]]

^<<v43-19-34,34>>^ Contudo um dos soldados lhe furou o lado com uma lança, e logo saiu sangue e água.

[[v43-19-35]]

^<<v43-19-35,35>>^ E aquele que o viu testificou, e o seu testemunho é verdadeiro; e sabe que é verdade o que diz, para que também vós o creiais.

[[v43-19-36]]

^<<v43-19-36,36>>^ Porque isto aconteceu para que se cumprisse a Escritura, que diz: Nenhum dos seus ossos será quebrado.

[[v43-19-37]]

^<<v43-19-37,37>>^ E outra vez diz a Escritura: Verão aquele que traspassaram.

[[v43-19-38]]

^<<v43-19-38,38>>^ Depois disto, José de Arimateia (o que era discípulo de Jesus, mas oculto, por medo dos judeus) rogou a Pilatos que lhe permitisse tirar o corpo de Jesus. E Pilatos lho  permitiu. Então foi e tirou o corpo de Jesus.

[[v43-19-39]]

^<<v43-19-39,39>>^ E foi também Nicodemos (aquele que anteriormente se dirigira de noite a Jesus), levando quase cem arráteis dum composto de mirra e aloés.

[[v43-19-40]]

^<<v43-19-40,40>>^ Tomaram pois o corpo de Jesus e o envolveram em lençóis com as especiarias, como os judeus costumam fazer, na preparação para o sepulcro.

[[v43-19-41]]

^<<v43-19-41,41>>^ E havia um horto naquele lugar onde fora crucificado, e no horto um sepulcro novo, em que ainda ninguém havia sido posto.

[[v43-19-42]]

^<<v43-19-42,42>>^ Ali pois (por causa da preparação dos judeus, e por estar perto aquele sepulcro), puseram a Jesus.

'''

xref:043-joao/043-joao-018.adoc#v43-18-0[&#60; Capítulo Anterior] | <<v43-19-0,Topo>> | xref:043-joao/043-joao-020.adoc#v43-20-0[Próximo Capítulo &#62;]