include::./index.adoc[]

[[v43-5-0]]
=== João, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-5-1]]

^<<v43-5-1,1>>^ DEPOIS disto havia uma  festa entre os judeus, e Jesus subiu a Jerusalém.

[[v43-5-2]]

^<<v43-5-2,2>>^ Ora em Jerusalém há, próximo à porta  das ovelhas, um tanque, chamado em hebreu Betesda, o qual tem cinco alpendres.

[[v43-5-3]]

^<<v43-5-3,3>>^ Nestes jazia grande multidão de enfermos; cegos, mancos e  ressicados, esperando o movimento das águas.

[[v43-5-4]]

^<<v43-5-4,4>>^ Porquanto um anjo descia em certo tempo ao tanque, e agitava a água; e o primeiro que ali descia, depois do movimento da água, sarava de qualquer enfermidade que tivesse.

[[v43-5-5]]

^<<v43-5-5,5>>^ E estava ali um homem que, havia trinta e oito anos, se achava enfermo.

[[v43-5-6]]

^<<v43-5-6,6>>^ E Jesus, vendo este deitado, e sabendo que estava neste estado havia muito tempo, disse-lhe: Queres ficar são?

[[v43-5-7]]

^<<v43-5-7,7>>^ O enfermo respondeu-lhe: Senhor, não tenho homem algum que, quando a água é agitada, me meta no tanque; mas, enquanto eu vou, desce outro antes de mim.

[[v43-5-8]]

^<<v43-5-8,8>>^ Jesus disse-lhe: Levanta-te, toma tua cama, e anda.

[[v43-5-9]]

^<<v43-5-9,9>>^ Logo aquele homem ficou são; e tomou a sua cama, e partiu. E aquele dia era sábado.

[[v43-5-10]]

^<<v43-5-10,10>>^ Então os judeus disseram àquele que tinha sido curado: É sábado, não te é lícito levar a cama.

[[v43-5-11]]

^<<v43-5-11,11>>^ Ele respondeu-lhes: Aquele que me curou, ele próprio disse: Toma a tua cama, e anda.

[[v43-5-12]]

^<<v43-5-12,12>>^ Perguntaram-lhe pois: Quem é o homem que te disse: Toma a tua cama, e anda?

[[v43-5-13]]

^<<v43-5-13,13>>^ E o que fora curado não sabia quem era; porque Jesus se havia retirado, em razão de naquele lugar haver grande multidão.

[[v43-5-14]]

^<<v43-5-14,14>>^ Depois Jesus encontrou-o no templo, e disse-lhe: Eis que já estás são; não peques mais, para que te não suceda alguma coisa pior.

[[v43-5-15]]

^<<v43-5-15,15>>^ E aquele homem foi, e anunciou aos judeus que Jesus era o que o curara.

[[v43-5-16]]

^<<v43-5-16,16>>^ E por esta causa os judeus perseguiram a Jesus, e procuravam matá-lo; porque fazia estas coisas no sábado.

[[v43-5-17]]

^<<v43-5-17,17>>^ E Jesus lhes respondeu: Meu Pai trabalha até agora, e eu trabalho também.

[[v43-5-18]]

^<<v43-5-18,18>>^ Por isso pois os judeus ainda mais procuravam matá-lo, porque não só quebrantava o sábado, mas também dizia que Deus era seu próprio Pai, fazendo-se igual a Deus.

[[v43-5-19]]

^<<v43-5-19,19>>^ Mas Jesus respondeu, e disse-lhes: Na verdade, na verdade vos digo que o Filho por si mesmo não pode fazer coisa alguma, se o não vir fazer ao Pai; porque tudo quanto ele faz, o Filho o faz igualmente.

[[v43-5-20]]

^<<v43-5-20,20>>^ Porque o Pai ama o Filho, e mostra-lhe tudo o que faz; e ele lhe mostrará maiores obras do que estas, para que vos maravilheis.

[[v43-5-21]]

^<<v43-5-21,21>>^ Pois, assim como o Pai ressuscita os mortos, e os vivifica, assim também o Filho vivifica aqueles que quer.

[[v43-5-22]]

^<<v43-5-22,22>>^ E também o Pai a ninguém julga, mas deu ao Filho todo o juízo;

[[v43-5-23]]

^<<v43-5-23,23>>^ Para que todos honrem o Filho, como honram o Pai. Quem não honra o Filho, não honra o Pai que o enviou.

[[v43-5-24]]

^<<v43-5-24,24>>^ Na verdade, na verdade vos digo que quem ouve a minha palavra, e crê naquele que me enviou, tem a vida eterna, e não entrará em condenação, mas, passou da morte para a vida.

[[v43-5-25]]

^<<v43-5-25,25>>^ Em verdade, em verdade vos digo que vem a hora, e agora é, em que os mortos ouvirão a voz do Filho de Deus, e os que a ouvirem viverão.

[[v43-5-26]]

^<<v43-5-26,26>>^ Porque, como o Pai tem a vida em si mesmo, assim deu também ao Filho ter a vida em si mesmo.

[[v43-5-27]]

^<<v43-5-27,27>>^ E deu-lhe o poder de exercer o juízo, porque é o Filho do homem.

[[v43-5-28]]

^<<v43-5-28,28>>^ Não vos maravilheis disto; porque vem a hora em que todos os que estão nos sepulcros ouvirão a sua voz.

[[v43-5-29]]

^<<v43-5-29,29>>^ E os que fizeram o bem sairão para a ressurreição da vida; e os que fizeram o mal para a ressurreição da condenação.

[[v43-5-30]]

^<<v43-5-30,30>>^ Eu não posso de mim mesmo fazer coisa alguma: como ouço, assim julgo; e o meu juízo é justo, porque não busco a minha vontade, mas a vontade do Pai que me enviou.

[[v43-5-31]]

^<<v43-5-31,31>>^ Se eu testifico de mim mesmo, o meu testemunho não é verdadeiro.

[[v43-5-32]]

^<<v43-5-32,32>>^ Há outro que testifica de mim, e sei que o testemunho que ele dá de mim é verdadeiro.

[[v43-5-33]]

^<<v43-5-33,33>>^ Vós mandastes a João, e ele deu testemunho da verdade.

[[v43-5-34]]

^<<v43-5-34,34>>^ Eu, porém, não recebo testemunho de homem; mas digo isto, para que vos salveis.

[[v43-5-35]]

^<<v43-5-35,35>>^ Ele era a candeia que ardia e alumiava; e vós quisestes alegrar-vos por um pouco de tempo com a sua luz.

[[v43-5-36]]

^<<v43-5-36,36>>^ Mas eu tenho maior testemunho do que o de João; porque as obras que o Pai me deu para realizar, as mesmas obras que eu faço, testificam de mim, que o Pai me enviou.

[[v43-5-37]]

^<<v43-5-37,37>>^ E o Pai, que me enviou, ele mesmo testificou de mim. Vós nunca ouvistes a sua voz, nem vistes o seu parecer;

[[v43-5-38]]

^<<v43-5-38,38>>^ E a sua palavra não permanece em vós, porque naquele que ele enviou não credes vós.

[[v43-5-39]]

^<<v43-5-39,39>>^ Examinais as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam.

[[v43-5-40]]

^<<v43-5-40,40>>^ E não quereis vir a mim para terdes vida.

[[v43-5-41]]

^<<v43-5-41,41>>^ Eu não recebo glória dos homens;

[[v43-5-42]]

^<<v43-5-42,42>>^ Mas bem vos conheço, que não tendes em vós o amor de Deus.

[[v43-5-43]]

^<<v43-5-43,43>>^ Eu vim em nome de meu Pai, e não me aceitais; se outro vier em seu próprio nome, a esse aceitareis.

[[v43-5-44]]

^<<v43-5-44,44>>^ Como podeis vós crer, recebendo honra uns dos outros, e não buscando a honra que vem só de Deus?

[[v43-5-45]]

^<<v43-5-45,45>>^ Não cuideis que eu vos hei de acusar para com o Pai. Há um que vos acusa, Moisés, em quem vós esperais.

[[v43-5-46]]

^<<v43-5-46,46>>^ Porque, se vós crêsseis em Moisés, creríeis em mim; porque de mim escreveu ele.

[[v43-5-47]]

^<<v43-5-47,47>>^ Mas, se não credes nos seus escritos, como credes nas minhas palavras?

'''

xref:043-joao/043-joao-004.adoc#v43-4-0[&#60; Capítulo Anterior] | <<v43-5-0,Topo>> | xref:043-joao/043-joao-006.adoc#v43-6-0[Próximo Capítulo &#62;]