include::./index.adoc[]

[[v43-18-0]]
=== João, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-18-1]]

^<<v43-18-1,1>>^ TENDO Jesus dito isto, saiu com os seus discípulos para além do ribeiro de Cedrom, onde havia um horto, no qual ele entrou e seus discípulos.

[[v43-18-2]]

^<<v43-18-2,2>>^ E Judas, que o traía, também conhecia aquele lugar, porque Jesus muitas vezes se ajuntava ali com os seus discípulos.

[[v43-18-3]]

^<<v43-18-3,3>>^ Tendo pois Judas recebido a coorte e oficiais dos principais sacerdotes e fariseus, veio para ali com lanternas, e archotes e armas.

[[v43-18-4]]

^<<v43-18-4,4>>^ Sabendo pois Jesus todas as coisas que sobre ele haviam de vir, adiantou-se, e disse-lhes: A quem buscais?

[[v43-18-5]]

^<<v43-18-5,5>>^ Responderam-lhe: A Jesus Nazareno. Disse-lhes Jesus: Sou eu. E Judas, que o traía, estava também com eles.

[[v43-18-6]]

^<<v43-18-6,6>>^ Quando pois lhes disse: Sou eu, recuaram, e caíram por terra.

[[v43-18-7]]

^<<v43-18-7,7>>^ Tornou-lhes pois a perguntar: A quem buscais? E eles disseram: A Jesus Nazareno.

[[v43-18-8]]

^<<v43-18-8,8>>^ Jesus respondeu: Já  vos disse que sou eu: se pois me buscais a mim, deixai ir estes.

[[v43-18-9]]

^<<v43-18-9,9>>^ Para que se cumprisse a palavra que tinha dito: dos que me deste nenhum deles perdi.

[[v43-18-10]]

^<<v43-18-10,10>>^ Então Simão Pedro, que tinha espada, desembainhou-a, e feriu o servo do sumo sacerdote, cortando-lhe a orelha direita. E o nome do servo era Malco.

[[v43-18-11]]

^<<v43-18-11,11>>^ Mas Jesus disse a Pedro: Mete a tua espada na bainha; não beberei eu o cálice que o Pai me deu?

[[v43-18-12]]

^<<v43-18-12,12>>^ Então a coorte, e o tribuno, e os servos dos judeus prenderam a Jesus e o manietaram.

[[v43-18-13]]

^<<v43-18-13,13>>^ E conduziram-no primeiramente a Anás, por ser sogro de Caifás, que era o sumo sacerdote daquele ano.

[[v43-18-14]]

^<<v43-18-14,14>>^ Ora Caifás era quem tinha aconselhado aos judeus que convinha que um homem morresse pelo povo.

[[v43-18-15]]

^<<v43-18-15,15>>^ E Simão Pedro e outro discípulo seguiam a Jesus. E este discípulo era conhecido do sumo sacerdote, e entrou com Jesus na sala do sumo sacerdote.

[[v43-18-16]]

^<<v43-18-16,16>>^ E Pedro estava da parte de fora, à porta. Saiu então o outro discípulo que era conhecido do sumo sacerdote, e falou à porteira, levando Pedro para dentro.

[[v43-18-17]]

^<<v43-18-17,17>>^ Então a porteira disse a Pedro: Não és tu também dos discípulos deste homem? Disse ele: Não sou.

[[v43-18-18]]

^<<v43-18-18,18>>^ Ora estavam ali os servos e os criados, que tinham feito brasas, e se aquentavam, porque fazia frio; e com eles estava Pedro, aquentando-se também.

[[v43-18-19]]

^<<v43-18-19,19>>^ E o sumo sacerdote interrogou Jesus acerca dos seus discípulos e da sua doutrina.

[[v43-18-20]]

^<<v43-18-20,20>>^ Jesus lhe respondeu: Eu falei abertamente ao mundo; eu sempre ensinei na sinagoga e no templo, onde todos os judeus se ajuntam, e nada disse em oculto.

[[v43-18-21]]

^<<v43-18-21,21>>^ Para que me perguntas a mim? pergunta aos que ouviram o que é que lhes ensinei; eis que eles sabem o que eu lhes tenho dito.

[[v43-18-22]]

^<<v43-18-22,22>>^ E, tendo dito isto, um dos criados que ali estavam deu uma bofetada em Jesus, dizendo: Assim respondes ao sumo sacerdote?

[[v43-18-23]]

^<<v43-18-23,23>>^ Respondeu-lhe Jesus: Se falei mal, dá testemunho do mal; e, se bem, porque me feres?

[[v43-18-24]]

^<<v43-18-24,24>>^ Anás mandou-o manietado, ao sumo sacerdote Caifás.

[[v43-18-25]]

^<<v43-18-25,25>>^ E Simão Pedro estava ali, e aquentava-se. Disseram-lhe pois: Não és também tu um dos seus discípulos? Ele negou, e disse: Não sou.

[[v43-18-26]]

^<<v43-18-26,26>>^ E um dos servos do sumo sacerdote, parente daquele  a quem Pedro cortara a orelha, disse: Não te vi eu no horto com ele?

[[v43-18-27]]

^<<v43-18-27,27>>^ E Pedro negou outra vez, e logo o galo cantou.

[[v43-18-28]]

^<<v43-18-28,28>>^ Depois levaram Jesus da casa de Caifás para a audiência. E era pela manhã cedo. E não entraram na audiência, para não se contaminarem, mas poderem comer a páscoa.

[[v43-18-29]]

^<<v43-18-29,29>>^ Então Pilatos saiu fora e disse-lhes: Que acusação trazeis contra este homem?

[[v43-18-30]]

^<<v43-18-30,30>>^ Responderam, e disseram-lhe: Se este não fosse malfeitor, não to entregaríamos.

[[v43-18-31]]

^<<v43-18-31,31>>^ Disse-lhes pois Pilatos: Levai-o vós, e julgai-o segundo a vossa lei. Disseram-lhe então os judeus: A nós não nos é lícito matar pessoa alguma.

[[v43-18-32]]

^<<v43-18-32,32>>^ (Para que se cumprisse a palavra que Jesus tinha dito, significando de que morte havia de morrer).

[[v43-18-33]]

^<<v43-18-33,33>>^ Tornou pois a entrar Pilatos na audiência, e chamou a Jesus, e disse-lhe: Tu és o rei dos Judeus?

[[v43-18-34]]

^<<v43-18-34,34>>^ Respondeu-lhe Jesus: Tu dizes isso de ti mesmo, ou disseram-to outros de mim?

[[v43-18-35]]

^<<v43-18-35,35>>^ Pilatos respondeu: Porventura sou eu judeu? a tua nação e os principais dos sacerdotes entregaram-te a mim: que fizeste?

[[v43-18-36]]

^<<v43-18-36,36>>^ Respondeu Jesus: O meu reino não é deste mundo: se o meu reino fosse deste mundo, pelejariam os meus servos, para que eu não fosse entregue aos judeus: mas agora o meu reino não é daqui.

[[v43-18-37]]

^<<v43-18-37,37>>^ Disse-lhe pois Pilatos: Logo tu és rei? Jesus respondeu: Tu dizes que eu sou rei. Eu para isso nasci, e para isso vim ao mundo, a fim de dar testemunho da verdade. Todo aquele que é da verdade ouve a minha voz.

[[v43-18-38]]

^<<v43-18-38,38>>^ Disse-lhe Pilatos: Que é a verdade? E, dizendo isto, tornou a ir ter com os judeus, e disse-lhes. Não acho nele crime algum;

[[v43-18-39]]

^<<v43-18-39,39>>^ Mas vós tendes por costume que eu vos solte alguém pela páscoa. Quereis pois que vos solte o Rei dos Judeus?

[[v43-18-40]]

^<<v43-18-40,40>>^ Então todos tornaram a clamar, dizendo: Este não, mas Barrabás. E Barrabás era um salteador.

'''

xref:043-joao/043-joao-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-joao/043-joao-019.adoc#v43-19-0[Próximo Capítulo &#62;]