include::./index.adoc[]

[[v43-6-0]]
=== João, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-6-1]]

^<<v43-6-1,1>>^ DEPOIS disto partiu Jesus para a outra banda do mar da Galileia, que é o  de Tiberíades.

[[v43-6-2]]

^<<v43-6-2,2>>^ E grande multidão o seguia; porque via os sinais que operava sobre os enfermos.

[[v43-6-3]]

^<<v43-6-3,3>>^ E Jesus subiu ao monte, e assentou-se ali com os seus discípulos.

[[v43-6-4]]

^<<v43-6-4,4>>^ E a páscoa, a festa dos judeus, estava próxima.

[[v43-6-5]]

^<<v43-6-5,5>>^ Então Jesus, levantando os olhos, e vendo que uma  grande multidão vinha ter com ele, disse a Filipe: Onde compraremos pão, para estes comerem?

[[v43-6-6]]

^<<v43-6-6,6>>^ Mas dizia isto para o experimentar; porque ele bem sabia o que havia de fazer.

[[v43-6-7]]

^<<v43-6-7,7>>^ Filipe respondeu-lhe: Duzentos dinheiros de pão não lhes bastarão, para que cada um deles tome um pouco.

[[v43-6-8]]

^<<v43-6-8,8>>^ E um dos seus discípulos, André, irmão de Simão Pedro, disse-lhe:

[[v43-6-9]]

^<<v43-6-9,9>>^ Está aqui um rapaz que tem cinco pães de cevada e dois peixinhos: mas que é isto para tantos?

[[v43-6-10]]

^<<v43-6-10,10>>^ E disse Jesus: Mandai assentar os homens. E havia muita relva naquele lugar. Assentaram-se pois os homens em número de quase cinco mil.

[[v43-6-11]]

^<<v43-6-11,11>>^ E Jesus tomou os pães e, havendo dado graças, repartiu-os pelos discípulos, e os discípulos pelos que estavam assentados; e igualmente também dos peixes, quanto eles queriam.

[[v43-6-12]]

^<<v43-6-12,12>>^ E, quando estavam saciados, disse aos seus discípulos: Recolhei os pedaços que sobejaram, para que nada se perca.

[[v43-6-13]]

^<<v43-6-13,13>>^ Recolheram-nos pois, e encheram doze cestos de pedaços dos cinco pães de cevada, que sobejaram aos que haviam comido.

[[v43-6-14]]

^<<v43-6-14,14>>^ Vendo pois aqueles homens o milagre que Jesus tinha feito, diziam: Este é verdadeiramente o profeta que devia vir ao mundo.

[[v43-6-15]]

^<<v43-6-15,15>>^ Sabendo pois Jesus que haviam de vir arrebatá-lo, para o fazerem rei, tornou a retirar-se, ele só, para o monte.

[[v43-6-16]]

^<<v43-6-16,16>>^ E, quando veio a tarde, os seus discípulos desceram para o mar.

[[v43-6-17]]

^<<v43-6-17,17>>^ E, entrando no barco, passaram o mar em direção a Capernaum; e era já escuro, e ainda  Jesus não tinha chegado ao pé deles.

[[v43-6-18]]

^<<v43-6-18,18>>^ E o mar se levantou, porque um grande vento assoprava.

[[v43-6-19]]

^<<v43-6-19,19>>^ E, tendo navegado uns vinte e cinco ou trinta estádios, viram a Jesus, andando sobre o mar e aproximando-se do barco; e temeram.

[[v43-6-20]]

^<<v43-6-20,20>>^ Porém ele lhes disse: Sou eu, não temais.

[[v43-6-21]]

^<<v43-6-21,21>>^ Então eles de boa mente o receberam no barco; e logo o barco chegou à terra para onde iam.

[[v43-6-22]]

^<<v43-6-22,22>>^ No dia seguinte, a multidão, que estava da outra banda do mar, vendo que não havia ali mais do que um barquinho, e que Jesus não entrara com seus discípulos naquele barquinho, mas que  os seus discípulos tinham ido sós.

[[v43-6-23]]

^<<v43-6-23,23>>^ (Contudo, outros barquinhos tinham chegado de Tiberíades, perto do lugar onde comeram o pão, havendo o Senhor dado graças);

[[v43-6-24]]

^<<v43-6-24,24>>^ Vendo pois a multidão que Jesus não estava ali nem os seus discípulos, entraram eles também nos barcos, e foram a Capernaum, em busca de Jesus.

[[v43-6-25]]

^<<v43-6-25,25>>^ E, achando-o na outra banda do mar, disseram-lhe: Rabi, quando chegaste aqui?

[[v43-6-26]]

^<<v43-6-26,26>>^ Jesus respondeu-lhes, e disse: Na verdade, na verdade vos digo que me buscais, não pelos sinais que vistes, mas porque comestes do pão e vos saciastes.

[[v43-6-27]]

^<<v43-6-27,27>>^ Trabalhai, não pela comida que perece, mas pela comida que permanece para a vida eterna, a qual o Filho do homem vos dará; porque a este o Pai, Deus, o selou.

[[v43-6-28]]

^<<v43-6-28,28>>^ Disseram-lhe pois: que faremos, para executarmos as obras de Deus?

[[v43-6-29]]

^<<v43-6-29,29>>^ Jesus respondeu, e disse-lhes: A obra de Deus é esta: Que creiais naquele que ele enviou.

[[v43-6-30]]

^<<v43-6-30,30>>^ Disseram-lhe pois: Que sinal pois fazes tu, para que o vejamos, e creiamos em ti? Que operas tu?

[[v43-6-31]]

^<<v43-6-31,31>>^ Nossos pais comeram o maná no deserto, como está escrito: Deu-lhes a comer o pão do céu.

[[v43-6-32]]

^<<v43-6-32,32>>^ Disse-lhes pois Jesus: Na verdade, na verdade vos digo: Moisés não vos deu o pão do céu; mas meu Pai vos dá o verdadeiro pão do céu.

[[v43-6-33]]

^<<v43-6-33,33>>^ Porque o pão de Deus é aquele que desce do céu e dá vida ao mundo.

[[v43-6-34]]

^<<v43-6-34,34>>^ Disseram-lhe pois: Senhor, dá-nos sempre desse pão.

[[v43-6-35]]

^<<v43-6-35,35>>^ E Jesus lhes disse: Eu sou o pão da vida; aquele que vem a mim não terá fome; e quem crê em mim nunca terá sede.

[[v43-6-36]]

^<<v43-6-36,36>>^ Mas já  vos disse que também vós me vistes, e contudo não credes.

[[v43-6-37]]

^<<v43-6-37,37>>^ Tudo o que o Pai me dá virá a mim; e o que vem a mim de maneira nenhuma o lançarei fora.

[[v43-6-38]]

^<<v43-6-38,38>>^ Porque eu desci do céu, não para fazer a minha vontade, mas a vontade daquele que me enviou.

[[v43-6-39]]

^<<v43-6-39,39>>^ E a vontade do Pai que me enviou é esta: que nenhum de todos aqueles que me deu se perca, mas que o ressuscite no último dia.

[[v43-6-40]]

^<<v43-6-40,40>>^ Porquanto a vontade daquele que me enviou é esta: que todo aquele que vê o Filho, e crê nele tenha a vida eterna; e eu o ressuscitarei no último dia.

[[v43-6-41]]

^<<v43-6-41,41>>^ Murmuravam pois dele os judeus, porque dissera: Eu sou o pão que desceu do céu.

[[v43-6-42]]

^<<v43-6-42,42>>^ E diziam: Não é este Jesus, o filho de José, cujo pai e mãe nós conhecemos? Como pois diz ele: Desci do céu?

[[v43-6-43]]

^<<v43-6-43,43>>^ Respondeu pois Jesus, e disse-lhes: Não murmureis entre vós.

[[v43-6-44]]

^<<v43-6-44,44>>^ Ninguém pode vir a mim, se o Pai que me enviou o não trouxer: e eu o ressuscitarei no último dia.

[[v43-6-45]]

^<<v43-6-45,45>>^ Está escrito nos profetas: E serão todos ensinados por Deus. Portanto todo aquele que do Pai ouviu e aprendeu vem a mim.

[[v43-6-46]]

^<<v43-6-46,46>>^ Não que alguém visse ao Pai, a não ser aquele que é de Deus: este tem visto ao Pai.

[[v43-6-47]]

^<<v43-6-47,47>>^ Na verdade, na verdade vos digo que aquele que crê em mim tem a vida eterna.

[[v43-6-48]]

^<<v43-6-48,48>>^ Eu sou o pão da vida.

[[v43-6-49]]

^<<v43-6-49,49>>^ Vossos pais comeram o maná no deserto, e morreram.

[[v43-6-50]]

^<<v43-6-50,50>>^ Este é o pão que desce do céu, para que o que dele comer não morra.

[[v43-6-51]]

^<<v43-6-51,51>>^ Eu sou o pão vivo que desceu do céu; se alguém comer deste pão, viverá para sempre; e o pão que eu der é a minha carne, que eu darei pela vida do mundo.

[[v43-6-52]]

^<<v43-6-52,52>>^ Disputavam pois os judeus entre si, dizendo: Como nos pode dar este a sua carne a comer?

[[v43-6-53]]

^<<v43-6-53,53>>^ Jesus pois lhes disse: Na verdade, na verdade vos digo que, se não comerdes a carne do Filho do homem, e não  beberdes o seu sangue, não tereis vida em vós mesmos.

[[v43-6-54]]

^<<v43-6-54,54>>^ Quem come a minha carne e bebe o meu sangue tem a vida eterna, e eu o ressuscitarei no último dia.

[[v43-6-55]]

^<<v43-6-55,55>>^ Porque a minha carne verdadeiramente é comida, e o meu sangue verdadeiramente é bebida.

[[v43-6-56]]

^<<v43-6-56,56>>^ Quem come a minha carne e bebe o meu sangue permanece em mim e eu nele.

[[v43-6-57]]

^<<v43-6-57,57>>^ Assim como o Pai, que vive, me enviou, e eu vivo pelo Pai, assim, quem de mim se alimenta, também viverá por mim.

[[v43-6-58]]

^<<v43-6-58,58>>^ Este é o pão que desceu do céu: não é o caso de vossos pais, que comeram o maná e morreram: quem comer este pão viverá para sempre.

[[v43-6-59]]

^<<v43-6-59,59>>^ Ele disse estas coisas  na sinagoga, ensinando em Capernaum.

[[v43-6-60]]

^<<v43-6-60,60>>^ Muitos pois dos seus discípulos, ouvindo isto , disseram: Duro é este discurso; quem o pode ouvir?

[[v43-6-61]]

^<<v43-6-61,61>>^ Sabendo pois Jesus em si mesmo que os seus discípulos murmuravam disto, disse-lhes: Isto escandaliza-vos?

[[v43-6-62]]

^<<v43-6-62,62>>^ Que seria , pois, se vísseis subir o Filho do homem para onde primeiro estava?

[[v43-6-63]]

^<<v43-6-63,63>>^ O espírito é o que vivifica, a carne para nada aproveita; as palavras que eu vos disse são espírito e vida.

[[v43-6-64]]

^<<v43-6-64,64>>^ Mas há alguns de vós que não creem. Porque bem sabia Jesus, desde o princípio, quem eram os que não criam, e quem era o que o havia de entregar.

[[v43-6-65]]

^<<v43-6-65,65>>^ E dizia: Por isso eu vos disse que ninguém pode vir a mim, se por meu Pai lhe não for concedido.

[[v43-6-66]]

^<<v43-6-66,66>>^ Desde então muitos dos seus discípulos tornaram para trás, e já não andavam com ele.

[[v43-6-67]]

^<<v43-6-67,67>>^ Então disse Jesus aos doze: Quereis vós também retirar-vos?

[[v43-6-68]]

^<<v43-6-68,68>>^ Respondeu-lhe pois Simão Pedro: Senhor, para quem iremos nós? Tu tens as palavras da vida eterna.

[[v43-6-69]]

^<<v43-6-69,69>>^ E nós temos crido e conhecido que tu és o Cristo, o Filho de Deus.

[[v43-6-70]]

^<<v43-6-70,70>>^ Respondeu-lhe Jesus: Não vos escolhi a vós os doze? e um de vós é um diabo.

[[v43-6-71]]

^<<v43-6-71,71>>^ E isto dizia ele de Judas Iscariotes, filho  de Simão; porque este o havia de entregar, sendo um dos doze.

'''

xref:043-joao/043-joao-005.adoc#v43-5-0[&#60; Capítulo Anterior] | <<v43-6-0,Topo>> | xref:043-joao/043-joao-007.adoc#v43-7-0[Próximo Capítulo &#62;]