include::./index.adoc[]

[[v43-3-0]]
=== João, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-3-1]]

^<<v43-3-1,1>>^ E HAVIA entre os fariseus um homem, chamado Nicodemos, príncipe dos judeus.

[[v43-3-2]]

^<<v43-3-2,2>>^ Este foi ter de noite com Jesus, e disse-lhe: Rabi, bem sabemos que és Mestre, vindo de Deus: porque ninguém pode fazer estes sinais que tu fazes, se Deus não for com ele.

[[v43-3-3]]

^<<v43-3-3,3>>^ Jesus respondeu, e disse-lhe: Na verdade, na verdade te digo que aquele que não nascer de novo, não pode ver o reino de Deus.

[[v43-3-4]]

^<<v43-3-4,4>>^ Disse-lhe Nicodemos: Como pode um homem nascer, sendo velho? porventura pode tornar a entrar no ventre de sua mãe, e nascer?

[[v43-3-5]]

^<<v43-3-5,5>>^ Jesus respondeu: Na verdade, na verdade, te digo que aquele que não nascer da água e do Espírito, não pode entrar no reino de Deus.

[[v43-3-6]]

^<<v43-3-6,6>>^ O que é nascido da carne é carne, e o que é nascido do Espírito é espírito.

[[v43-3-7]]

^<<v43-3-7,7>>^ Não te maravilhes de te ter dito: Necessário vos é nascer de novo.

[[v43-3-8]]

^<<v43-3-8,8>>^ O vento assopra onde quer, e ouves a sua voz; mas não sabes donde vem, nem para onde vai; assim é todo aquele que é nascido do Espírito.

[[v43-3-9]]

^<<v43-3-9,9>>^ Nicodemos respondeu, e disse-lhe: Como pode ser isso?

[[v43-3-10]]

^<<v43-3-10,10>>^ Jesus respondeu, e disse-lhe: Tu és mestre de Israel, e não sabes isto?

[[v43-3-11]]

^<<v43-3-11,11>>^ Na verdade, na verdade te digo que nós dizemos o que sabemos e testificamos o que vimos; e não aceitais o nosso testemunho.

[[v43-3-12]]

^<<v43-3-12,12>>^ Se vos falei de coisas  terrestres, e não crestes, como crereis, se vos falar das celestiais?

[[v43-3-13]]

^<<v43-3-13,13>>^ Ora ninguém subiu ao céu, senão o que desceu do céu, o Filho do homem, que está no céu.

[[v43-3-14]]

^<<v43-3-14,14>>^ E, como Moisés levantou a serpente no deserto, assim importa que o Filho do homem seja levantado;

[[v43-3-15]]

^<<v43-3-15,15>>^ Para que todo aquele que nele crê não pereça, mas tenha a vida eterna.

[[v43-3-16]]

^<<v43-3-16,16>>^ Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.

[[v43-3-17]]

^<<v43-3-17,17>>^ Porque Deus enviou o seu Filho ao mundo, não para que condenasse o mundo, mas para que o mundo fosse salvo por ele.

[[v43-3-18]]

^<<v43-3-18,18>>^ Quem crê nele não é condenado; mas quem não crê já está condenado; porquanto não crê no nome do Unigênito Filho de Deus.

[[v43-3-19]]

^<<v43-3-19,19>>^ E a condenação é esta: Que a luz veio ao mundo, e os homens amaram mais as trevas do que a luz, porque as suas obras eram más.

[[v43-3-20]]

^<<v43-3-20,20>>^ Porque todo aquele que faz o mal aborrece a luz, e não vem para a luz para que as suas obras não sejam reprovadas.

[[v43-3-21]]

^<<v43-3-21,21>>^ Mas quem pratica a verdade vem para a luz, a fim de que as suas obras sejam manifestas, porque são feitas em Deus.

[[v43-3-22]]

^<<v43-3-22,22>>^ Depois disto foi Jesus com os seus discípulos para a terra da Judeia; e estava ali com eles, e batizava.

[[v43-3-23]]

^<<v43-3-23,23>>^ Ora João batizava também em Enom, junto a Salim, porque havia ali muitas águas; e vinham ali , e eram batizados.

[[v43-3-24]]

^<<v43-3-24,24>>^ Porque ainda João não tinha sido lançado na prisão.

[[v43-3-25]]

^<<v43-3-25,25>>^ Houve então uma questão entre os discípulos de João e um judeu acerca da purificação.

[[v43-3-26]]

^<<v43-3-26,26>>^ E foram ter com João, e disseram-lhe: Rabi, aquele que estava contigo além do Jordão, do qual tu deste testemunho, ei-lo batizando, e todos vão ter com ele.

[[v43-3-27]]

^<<v43-3-27,27>>^ João respondeu, e disse: O homem não pode receber coisa alguma, se lhe não for dada do céu.

[[v43-3-28]]

^<<v43-3-28,28>>^ Vós mesmos me sois testemunhas de que disse: Eu não sou o Cristo, mas sou enviado adiante dele.

[[v43-3-29]]

^<<v43-3-29,29>>^ Aquele que tem a esposa é o esposo; mas o amigo do esposo, que lhe  assiste e o ouve, alegra-se muito com a voz do esposo. Assim pois já  esse meu gozo está cumprido.

[[v43-3-30]]

^<<v43-3-30,30>>^ É necessário que ele cresça e que eu diminua.

[[v43-3-31]]

^<<v43-3-31,31>>^ Aquele que vem de cima é sobre todos: aquele que vem  da terra é da terra e fala da terra. Aquele que vem do céu é sobre todos.

[[v43-3-32]]

^<<v43-3-32,32>>^ E aquilo que ele viu e ouviu isso testifica; e ninguém aceita o seu testemunho.

[[v43-3-33]]

^<<v43-3-33,33>>^ Aquele que aceitou o seu testemunho, esse confirmou que Deus é verdadeiro.

[[v43-3-34]]

^<<v43-3-34,34>>^ Porque aquele que Deus enviou fala as palavras de Deus; pois não lhe  dá Deus o Espírito por medida.

[[v43-3-35]]

^<<v43-3-35,35>>^ O Pai ama o Filho, e todas as coisas  entregou nas suas mãos.

[[v43-3-36]]

^<<v43-3-36,36>>^ Aquele que crê no Filho tem a vida eterna; mas aquele que não crê no Filho não verá a vida; mas a ira de Deus sobre ele permanece.

'''

xref:043-joao/043-joao-002.adoc#v43-2-0[&#60; Capítulo Anterior] | <<v43-3-0,Topo>> | xref:043-joao/043-joao-004.adoc#v43-4-0[Próximo Capítulo &#62;]