include::./index.adoc[]

[[v43-4-0]]
=== João, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v43-4-1]]

^<<v43-4-1,1>>^ E QUANDO o Senhor entendeu que os fariseus tinham ouvido que Jesus fazia e batizava mais discípulos do que João

[[v43-4-2]]

^<<v43-4-2,2>>^ (Ainda que Jesus mesmo não batizava, mas os seus discípulos),

[[v43-4-3]]

^<<v43-4-3,3>>^ Deixou a Judeia, e foi outra vez para a Galileia.

[[v43-4-4]]

^<<v43-4-4,4>>^ E era-lhe necessário passar por Samaria.

[[v43-4-5]]

^<<v43-4-5,5>>^ Foi pois a uma cidade, de Samaria, chamada Sicar, junto da herdade que Jacó tinha dado a seu filho José.

[[v43-4-6]]

^<<v43-4-6,6>>^ E estava ali a fonte de Jacó. Jesus, pois, cansado do caminho, assentou-se assim junto da fonte. Era isto quase à hora sexta.

[[v43-4-7]]

^<<v43-4-7,7>>^ Veio uma mulher de Samaria tirar água; disse-lhe Jesus: Dá-me de beber.

[[v43-4-8]]

^<<v43-4-8,8>>^ Porque os seus discípulos tinham ido à cidade comprar comida.

[[v43-4-9]]

^<<v43-4-9,9>>^ Disse-lhe pois a mulher samaritana: Como, sendo tu judeu, me pedes de beber a mim, que sou mulher samaritana? (porque os judeus não se comunicam com os samaritanos).

[[v43-4-10]]

^<<v43-4-10,10>>^ Jesus respondeu, e disse-lhe: Se tu conheceras o dom de Deus, e quem é o que te diz — Dá-me de beber, tu lhe pedirias, e ele te daria água viva.

[[v43-4-11]]

^<<v43-4-11,11>>^ Disse-lhe a mulher: Senhor, tu não tens com que a tirar, e o poço é fundo; onde pois tens a água viva?

[[v43-4-12]]

^<<v43-4-12,12>>^ És tu maior do que o nosso Pai Jacó, que nos deu o poço, bebendo ele próprio dele, e os seus filhos, e o seu gado?

[[v43-4-13]]

^<<v43-4-13,13>>^ Jesus respondeu, e disse-lhe: Qualquer que beber desta água tornará a ter sede;

[[v43-4-14]]

^<<v43-4-14,14>>^ Mas aquele que beber da água que eu lhe der nunca terá sede, porque a água que eu lhe der se fará nele uma fonte d’água que salte para a vida eterna.

[[v43-4-15]]

^<<v43-4-15,15>>^ Disse-lhe a mulher: Senhor, dá-me dessa água, para que não mais tenha sede, e não venha aqui tirá-la.

[[v43-4-16]]

^<<v43-4-16,16>>^ Disse-lhe Jesus: Vai, chama o teu marido, e vem cá.

[[v43-4-17]]

^<<v43-4-17,17>>^ A mulher respondeu, e disse: Não tenho marido. Disse-lhe Jesus: Disseste bem: Não tenho marido;

[[v43-4-18]]

^<<v43-4-18,18>>^ Porque tiveste cinco maridos, e o que agora tens não é teu marido; isto disseste com verdade.

[[v43-4-19]]

^<<v43-4-19,19>>^ Disse-lhe a mulher: Senhor, vejo que és profeta.

[[v43-4-20]]

^<<v43-4-20,20>>^ Nossos pais adoraram neste monte, e vós dizeis que é em Jerusalém o lugar onde se deve adorar.

[[v43-4-21]]

^<<v43-4-21,21>>^ Disse-lhe Jesus: Mulher, crê-me que a hora vem, em que nem neste monte nem em Jerusalém adorareis o Pai.

[[v43-4-22]]

^<<v43-4-22,22>>^ Vós adorais o que não sabeis; nós adoramos o que sabemos porque a salvação vem dos judeus.

[[v43-4-23]]

^<<v43-4-23,23>>^ Mas a hora vem, e agora é, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade; porque o Pai procura a tais que assim o adorem.

[[v43-4-24]]

^<<v43-4-24,24>>^ Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade.

[[v43-4-25]]

^<<v43-4-25,25>>^ A mulher disse-lhe: Eu sei que o Messias (que se chama o Cristo) vem; quando ele vier, nos anunciará tudo.

[[v43-4-26]]

^<<v43-4-26,26>>^ Jesus disse-lhe: Eu o sou, eu que falo contigo.

[[v43-4-27]]

^<<v43-4-27,27>>^ E nisto vieram os seus discípulos, e maravilharam-se de que estivesse falando com uma  mulher; todavia nenhum lhe  disse: Que perguntas? ou: Por que falas com ela?

[[v43-4-28]]

^<<v43-4-28,28>>^ Deixou pois a mulher o seu cântaro, e foi à cidade, e disse àqueles homens:

[[v43-4-29]]

^<<v43-4-29,29>>^ Vinde, vede um homem que me disse tudo quanto tenho feito: porventura não é este o Cristo?

[[v43-4-30]]

^<<v43-4-30,30>>^ Saíram pois da cidade, e foram ter com ele.

[[v43-4-31]]

^<<v43-4-31,31>>^ E entretanto os seus discípulos lhe rogaram, dizendo: Rabi, come.

[[v43-4-32]]

^<<v43-4-32,32>>^ Porém ele lhes disse: Uma comida tenho para comer, que vós não conheceis.

[[v43-4-33]]

^<<v43-4-33,33>>^ Então os discípulos diziam uns aos outros: Trouxe-lhe porventura alguém de comer?

[[v43-4-34]]

^<<v43-4-34,34>>^ Jesus disse-lhes: A minha comida é fazer a vontade daquele que me enviou, e realizar a sua obra.

[[v43-4-35]]

^<<v43-4-35,35>>^ Não dizeis vós que ainda há quatro meses até que venha a ceifa? Eis que eu vos digo: Levantai os vossos olhos, e vede as terras, que já estão brancas para a ceifa.

[[v43-4-36]]

^<<v43-4-36,36>>^ E o que ceifa recebe galardão, e ajunta fruto para a vida eterna; para que, assim o que semeia como o que ceifa, ambos se regozijem.

[[v43-4-37]]

^<<v43-4-37,37>>^ Porque nisto é verdadeiro o ditado, que um é o que semeia, e outro o que ceifa.

[[v43-4-38]]

^<<v43-4-38,38>>^ Eu vos enviei a ceifar onde vós não trabalhastes; outros trabalharam, e vós entrastes no seu trabalho.

[[v43-4-39]]

^<<v43-4-39,39>>^ E muitos dos samaritanos daquela cidade creram nele, pela palavra da mulher, que testificou: Disse-me tudo quanto tenho feito.

[[v43-4-40]]

^<<v43-4-40,40>>^ Indo pois ter com ele os samaritanos, rogaram-lhe que ficasse com eles; e ficou ali dois dias.

[[v43-4-41]]

^<<v43-4-41,41>>^ E muitos mais creram nele, por causa da sua palavra.

[[v43-4-42]]

^<<v43-4-42,42>>^ E diziam à mulher: já não é  pelo teu dito que nós cremos; porque nós mesmos o temos ouvido, e sabemos que este é verdadeiramente o Cristo, o Salvador do mundo.

[[v43-4-43]]

^<<v43-4-43,43>>^ E dois dias depois partiu dali, e foi para a Galileia.

[[v43-4-44]]

^<<v43-4-44,44>>^ Porque Jesus mesmo testificou que um profeta não tem honra na sua própria pátria.

[[v43-4-45]]

^<<v43-4-45,45>>^ Chegando pois à Galileia os galileus o receberam, vistas todas as coisas que fizera em Jerusalém no dia  da festa; porque também eles tinham ido à festa.

[[v43-4-46]]

^<<v43-4-46,46>>^ Segunda vez foi Jesus a Caná da Galileia, onde da água fizera vinho. E havia ali um régulo, cujo filho estava enfermo em Capernaum.

[[v43-4-47]]

^<<v43-4-47,47>>^ Ouvindo este que Jesus vinha da Judeia para a Galileia, foi ter com ele, e rogou-lhe que descesse, e curasse o seu filho, porque já  estava à morte.

[[v43-4-48]]

^<<v43-4-48,48>>^ Então Jesus lhe disse: Se não virdes sinais e milagres, não crereis.

[[v43-4-49]]

^<<v43-4-49,49>>^ Disse-lhe o régulo: Senhor, desce, antes que meu filho morra.

[[v43-4-50]]

^<<v43-4-50,50>>^ Disse-lhe Jesus: Vai, o teu filho vive. E o homem creu na palavra que Jesus lhe disse, e foi-se.

[[v43-4-51]]

^<<v43-4-51,51>>^ E, descendo ele logo, saíram- lhe  ao encontro os seus servos, e lhe anunciaram, dizendo: O teu filho vive.

[[v43-4-52]]

^<<v43-4-52,52>>^ Perguntou-lhes pois a que hora se achara melhor; e disseram-lhe: Ontem às sete horas a febre o deixou.

[[v43-4-53]]

^<<v43-4-53,53>>^ Entendeu pois o pai que era  aquela hora a mesma em que Jesus lhe disse: O teu filho vive; e creu ele, e toda a sua casa.

[[v43-4-54]]

^<<v43-4-54,54>>^ Jesus fez este segundo milagre, quando ia da Judeia para a Galileia.

'''

xref:043-joao/043-joao-003.adoc#v43-3-0[&#60; Capítulo Anterior] | <<v43-4-0,Topo>> | xref:043-joao/043-joao-005.adoc#v43-5-0[Próximo Capítulo &#62;]