include::./index.adoc[]

[[v36-1-0]]
=== Sofonias, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v36-1-1]]

^<<v36-1-1,1>>^ PALAVRA do Senhor vinda a Sofonias, filho de Cusi, filho de Gedalias, filho de Amarias, filho de Hezequias, nos dias de Josias, filho de Amom, rei de Judá.

[[v36-1-2]]

^<<v36-1-2,2>>^ Inteiramente consumirei tudo sobre a face da terra, diz o Senhor.

[[v36-1-3]]

^<<v36-1-3,3>>^ Arrebatarei os homens e os animais, consumirei as aves do céu, e os peixes do mar, e os tropeços com os ímpios; e exterminarei os homens de cima da terra, disse o Senhor.

[[v36-1-4]]

^<<v36-1-4,4>>^ E estenderei a minha mão contra Judá, e contra todos os habitantes de Jerusalém, e exterminarei deste lugar o resto de Baal, e  o nome dos quemarins com os sacerdotes;

[[v36-1-5]]

^<<v36-1-5,5>>^ E os que sobre os telhados se curvam ao exército do céu; e  os que se inclinam jurando ao Senhor, e juram por Malcã;

[[v36-1-6]]

^<<v36-1-6,6>>^ E os que deixam de andar em seguimento do Senhor, e os que não buscam ao Senhor, nem perguntam por ele.

[[v36-1-7]]

^<<v36-1-7,7>>^ Cala-te diante do Senhor Jeová , porque o dia do Senhor está  perto, porque o Senhor preparou o sacrifício, e  santificou os seus convidados.

[[v36-1-8]]

^<<v36-1-8,8>>^ E acontecerá que, no dia do sacrifício do Senhor, hei de castigar os príncipes, e os filhos do rei, e todos os que se vestem de vestidura estranha.

[[v36-1-9]]

^<<v36-1-9,9>>^ Castigarei também naquele dia todos aqueles que saltam sobre o umbral, que enchem de violência e engano a casa dos seus senhores.

[[v36-1-10]]

^<<v36-1-10,10>>^ E naquele dia, diz o Senhor, far-se-á ouvir uma voz de clamor desde a porta do peixe e um uivo desde a segunda parte, e grande quebranto desde os outeiros.

[[v36-1-11]]

^<<v36-1-11,11>>^ Uivai vós, moradores de Mactés, porque todo o povo de Canaã está arruinado, todos os carregados de dinheiro são destruídos.

[[v36-1-12]]

^<<v36-1-12,12>>^ E há de ser que, naquele tempo, esquadrinharei a Jerusalém com lanternas, e castigarei os homens que estão assentados sobre as suas fezes, que dizem no seu coração: O Senhor não faz bem nem faz mal.

[[v36-1-13]]

^<<v36-1-13,13>>^ Por isso será saqueada a sua fazenda, e assoladas as suas casas: e edificarão casas, mas não habitarão nelas, e plantarão vinhas, mas não lhes beberão o vinho.

[[v36-1-14]]

^<<v36-1-14,14>>^ O grande dia do Senhor está perto, está perto, e se apressa muito a voz do dia do Senhor: amargamente clamará ali o homem poderoso.

[[v36-1-15]]

^<<v36-1-15,15>>^ Aquele dia é um dia de indignação, dia de angústia e de ânsia, dia de alvoroço e de desolação, dia de trevas e de escuridão, dia de nuvens e de densas trevas.

[[v36-1-16]]

^<<v36-1-16,16>>^ Dia de trombeta e de alarido contra as cidades fortes e contra as torres altas.

[[v36-1-17]]

^<<v36-1-17,17>>^ E angustiarei os homens, e eles andarão como cegos, porque pecaram contra o Senhor; e o seu sangue se derramará como pó e a sua carne como esterco.

[[v36-1-18]]

^<<v36-1-18,18>>^ Nem a sua prata nem o seu ouro os poderá livrar no dia do furor do Senhor, mas pelo fogo do seu zelo toda esta terra será consumida, porque certamente fará de todos os moradores da terra uma destruição total e apressada.

'''

xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[&#60; Capítulo Anterior] | <<v36-1-0,Topo>> | xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[Próximo Capítulo &#62;]