include::./index.adoc[]

[[v36-2-0]]
=== Sofonias, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v36-2-1]]

^<<v36-2-1,1>>^ CONGREGA-TE, sim, congrega-te ó nação que não tens desejo,

[[v36-2-2]]

^<<v36-2-2,2>>^ Antes que saia o decreto, e o dia passe como a pragana; antes que venha sobre vós a ira do Senhor; sim, antes que venha sobre vós o dia da ira do Senhor.

[[v36-2-3]]

^<<v36-2-3,3>>^ Buscai ao Senhor, vós todos os mansos da terra, que pondes por obra o seu juízo: buscai a justiça, buscai a mansidão; porventura sereis escondidos no dia da ira do Senhor.

[[v36-2-4]]

^<<v36-2-4,4>>^ Porque Gaza será desamparada, e Ascalom assolada: Asdode ao meio-dia será expelida, e Ecrom desarraigada.

[[v36-2-5]]

^<<v36-2-5,5>>^ Ai dos habitantes da borda do mar, do povo dos quereteus! a palavra do Senhor será contra vós, ó Canaã, terra dos filisteus, e eu vos farei destruir, até que não haja morador.

[[v36-2-6]]

^<<v36-2-6,6>>^ E a borda do mar será de pastagens, com cabanas para os pastores, e currais para os rebanhos.

[[v36-2-7]]

^<<v36-2-7,7>>^ E será a costa para o resto da casa de Judá para que nela apascentem: à tarde se assentarão nas casas de Ascalom, porque o Senhor seu Deus os visitará, e reconduzirá os seus cativos.

[[v36-2-8]]

^<<v36-2-8,8>>^ Eu ouvi o escárnio de Moabe, e as injuriosas palavras dos filhos de Amom, com que escarneceram do meu povo, e se engrandeceram contra o seu termo.

[[v36-2-9]]

^<<v36-2-9,9>>^ Portanto, tão certo como eu vivo, diz o Senhor dos Exércitos, o Deus de Israel, Moabe será como Sodoma, e os filhos de Amom como Gomorra, campo de urtigas e poços de sal, e assolação perpétua; o resto do meu povo os saqueará, e o restante do meu povo os possuirá.

[[v36-2-10]]

^<<v36-2-10,10>>^ Isto terão em recompensa da sua soberba, porque escarneceram, e se engrandeceram contra o povo do Senhor dos Exércitos.

[[v36-2-11]]

^<<v36-2-11,11>>^ O Senhor será terrível para eles, porque aniquilará todos os deuses da terra; e todos virão adorá-lo, cada um desde o seu lugar; todas as ilhas das nações.

[[v36-2-12]]

^<<v36-2-12,12>>^ Também vós, ó etíopes, sereis mortos com a minha espada.

[[v36-2-13]]

^<<v36-2-13,13>>^ Estenderá também a sua mão contra o norte, e destruirá a Assíria; e fará de Nínive uma assolação, terra seca como o deserto.

[[v36-2-14]]

^<<v36-2-14,14>>^ E no meio dela repousarão os rebanhos, todos os animais dos povos; e alojar-se-ão nos seus capitéis assim o pelicano como o ouriço; a voz do seu  canto retinirá nas janelas, a assolação estará  no umbral, quando tiver descoberto a sua obra de cedro.

[[v36-2-15]]

^<<v36-2-15,15>>^ Esta é  a cidade alegre e descuidada, que dizia no seu coração: Eu sou, e não há outra além de mim: como se tornou em assolação, em  pousada de animais! qualquer que passar por ela assobiará, e  meneará a sua mão.

'''

xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[&#60; Capítulo Anterior] | <<v36-2-0,Topo>> | xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[Próximo Capítulo &#62;]