include::./index.adoc[]

[[v36-3-0]]
=== Sofonias, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v36-3-1]]

^<<v36-3-1,1>>^ AI da rebelde e manchada, da cidade opressora!

[[v36-3-2]]

^<<v36-3-2,2>>^ Não ouve a voz, não aceita o castigo: não confia no Senhor; nem se aproximou do seu Deus.

[[v36-3-3]]

^<<v36-3-3,3>>^ Os seus príncipes são leões rugidores no meio dela: os seus juízes são lobos da tarde, que  não deixam os ossos para o outro dia.

[[v36-3-4]]

^<<v36-3-4,4>>^ Os seus profetas são  levianos, e criaturas aleivosas: os seus sacerdotes profanaram o santuário, e fizeram violência à lei.

[[v36-3-5]]

^<<v36-3-5,5>>^ O Senhor é justo, no meio dela; ele não comete iniquidade: cada manhã traz o seu juízo à luz; nunca falta; mas o perverso não conhece a vergonha.

[[v36-3-6]]

^<<v36-3-6,6>>^ Exterminei as nações, as suas torres estão assoladas: fiz desertas as suas praças, a ponto de não ficar quem passe por elas: as suas cidades foram destruídas, até não ficar ninguém, até não haver quem as habite.

[[v36-3-7]]

^<<v36-3-7,7>>^ Eu dizia: Certamente me temerás, e aceitarás a correção; e assim a sua morada não seria destruída, conforme o que havia determinado; mas eles se levantaram de madrugada, corromperam todas as suas obras.

[[v36-3-8]]

^<<v36-3-8,8>>^ Portanto esperai-me a mim, diz o Senhor, no dia em que eu me levantar para o despojo; porque o meu juízo é  ajuntar as nações e congregar os reinos, para sobre eles derramar a minha indignação, e todo o ardor da minha ira; porque toda esta terra será consumida pelo fogo do meu zelo.

[[v36-3-9]]

^<<v36-3-9,9>>^ Porque então darei lábios puros aos povos, para que todos invoquem o nome do Senhor, para que o sirvam com um mesmo espírito.

[[v36-3-10]]

^<<v36-3-10,10>>^ Dalém dos rios da Etiópia os meus zelosos adoradores, a filha da minha dispersa, me trarão sacrifício.

[[v36-3-11]]

^<<v36-3-11,11>>^ Naquele dia não te envergonharás de nenhuma das tuas obras, com que te rebelaste contra mim; porque então tirarei do meio de ti os que exultam na sua soberba, e tu nunca mais te ensoberbecerás no meu monte santo.

[[v36-3-12]]

^<<v36-3-12,12>>^ Mas deixarei no meio de ti um povo humilde e pobre; e eles confiarão no nome do Senhor.

[[v36-3-13]]

^<<v36-3-13,13>>^ O remanescente de Israel não cometerá iniquidade, nem proferirá mentira, e na sua boca não se achará língua enganosa; porque serão apascentados, deitar-se-ão, e não haverá quem os  espante.

[[v36-3-14]]

^<<v36-3-14,14>>^ Canta alegremente, ó filha de Sião: rejubila, ó Israel: regozija-te, e exulta de todo o coração, ó filha de Jerusalém.

[[v36-3-15]]

^<<v36-3-15,15>>^ O Senhor afastou os teus juízos, exterminou o teu inimigo: o Senhor, o rei de Israel, está no meio de ti; tu não verás mais mal algum.

[[v36-3-16]]

^<<v36-3-16,16>>^ Naquele dia se dirá a Jerusalém: Não temas, ó Sião, não se enfraqueçam as tuas mãos.

[[v36-3-17]]

^<<v36-3-17,17>>^ O Senhor teu Deus está  no meio de ti, poderoso para te salvar; ele se deleitará em ti com alegria; calar-se-á por seu amor, regozijar-se-á em ti com júbilo.

[[v36-3-18]]

^<<v36-3-18,18>>^ Os que em ti se entristeceram, por causa da reunião solene, eu os congregarei; esses para os quais o peso foi uma afronta.

[[v36-3-19]]

^<<v36-3-19,19>>^ Eis que naquele tempo procederei contra todos os que te afligem, e salvarei a que coxeia, e recolherei a que foi expulsa; e lhes darei um louvor e um nome em toda a terra em que foram envergonhados.

[[v36-3-20]]

^<<v36-3-20,20>>^ Naquele tempo vos trarei, naquele tempo vos recolherei: certamente vos darei um nome e um louvor entre todos os povos da terra, quando reconduzir os vossos cativos diante dos vossos olhos, diz o Senhor.

'''

xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[&#60; Capítulo Anterior] | <<v36-3-0,Topo>> | xref:037-ageu/037-ageu-001.adoc#v37-1-0[Próximo Capítulo &#62;]