include::./index.adoc[]

[[v32-1-0]]
=== Jonas, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v32-1-1]]

^<<v32-1-1,1>>^ E VEIO a palavra do Senhor a Jonas, filho de Amitai, dizendo:

[[v32-1-2]]

^<<v32-1-2,2>>^ Levanta-te, vai à grande cidade de Nínive, e clama contra ela, porque a sua malícia subiu até mim.

[[v32-1-3]]

^<<v32-1-3,3>>^ E Jonas se levantou para fugir de diante da face do Senhor para Tarsis; e, descendo a Jope, achou que um navio ia para Tarsis; pagou pois, a sua passagem, e desceu para dentro dele, para ir com eles para Tarsis, de diante da face do Senhor.

[[v32-1-4]]

^<<v32-1-4,4>>^ Mas o Senhor mandou ao mar um grande vento, e fez-se no mar uma grande tempestade, e o navio estava para quebrar-se.

[[v32-1-5]]

^<<v32-1-5,5>>^ Então temeram os marinheiros, e clamava cada um ao seu deus, e lançavam no mar as fazendas, que estavam  no navio, para o aliviarem do seu peso ; Jonas porém desceu aos lugares do porão e se deitou, e dormia um profundo sono.

[[v32-1-6]]

^<<v32-1-6,6>>^ E o mestre do navio chegou-se a ele, e disse-lhe: Que tens, dormente? levanta-te, invoca o teu Deus; talvez assim Deus se lembre de nós para que não pereçamos.

[[v32-1-7]]

^<<v32-1-7,7>>^ E dizia cada um ao seu companheiro: Vinde, e lancemos sortes, para que saibamos por que causa nos sobreveio este mal. E lançaram sortes, e a sorte caiu sobre Jonas.

[[v32-1-8]]

^<<v32-1-8,8>>^ Então lhe disseram: Declara-nos tu agora, por que razão nos sobreveio este mal. Que ocupação é a tua? e donde vens? Qual é a tua terra? e de que povo és  tu?

[[v32-1-9]]

^<<v32-1-9,9>>^ E ele lhes disse: Eu sou hebreu, e temo ao Senhor, o Deus do céu, que fez o mar e a terra seca.

[[v32-1-10]]

^<<v32-1-10,10>>^ Então estes homens se encheram de grande temor, e lhe disseram: Por que fizeste tu isto? Pois sabiam os homens que fugia de diante do Senhor, porque ele lho tinha declarado.

[[v32-1-11]]

^<<v32-1-11,11>>^ E disseram-lhe: Que te faremos nós, para que o mar se acalme? Por que o mar se elevava e engrossava cada vez mais.

[[v32-1-12]]

^<<v32-1-12,12>>^ E ele lhes disse: Levantai-me, e lançai-me ao mar, e o mar se aquietará; porque eu sei que por minha causa vos sobreveio esta grande tempestade.

[[v32-1-13]]

^<<v32-1-13,13>>^ Entretanto os homens remavam, esforçando-se por alcançar a terra, mas não podiam: porquanto o mar se ia embravecendo cada vez mais contra eles.

[[v32-1-14]]

^<<v32-1-14,14>>^ Então clamaram ao Senhor, e disseram: Ah! Senhor! nós te rogamos! não pereçamos por causa da vida deste homem, e não ponhas sobre nós o sangue inocente; porque tu, Senhor, fizeste como te aprouve.

[[v32-1-15]]

^<<v32-1-15,15>>^ E levantaram a Jonas, e o lançaram ao mar, e cessou o mar da sua fúria.

[[v32-1-16]]

^<<v32-1-16,16>>^ Temeram pois estes homens ao Senhor com grande temor; e ofereceram sacrifícios ao Senhor, e fizeram votos.

[[v32-1-17]]

^<<v32-1-17,17>>^ Deparou pois o Senhor um  grande peixe, para que tragasse a Jonas; e esteve Jonas três dias e três noites nas entranhas do peixe.

'''

xref:031-obadias/031-obadias-001.adoc#v31-1-0[&#60; Capítulo Anterior] | <<v32-1-0,Topo>> | xref:032-jonas/032-jonas-002.adoc#v32-2-0[Próximo Capítulo &#62;]