include::./index.adoc[]

[[v32-3-0]]
=== Jonas, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v32-3-1]]

^<<v32-3-1,1>>^ E VEIO a palavra do Senhor segunda vez a Jonas, dizendo:

[[v32-3-2]]

^<<v32-3-2,2>>^ Levanta-te, e vai à grande cidade de Nínive, e prega contra ela a pregação que eu te disse.

[[v32-3-3]]

^<<v32-3-3,3>>^ E levantou-se Jonas, e foi a Nínive, segundo a palavra do Senhor: era pois Nínive uma grande cidade, de três dias de caminho.

[[v32-3-4]]

^<<v32-3-4,4>>^ E começou Jonas a entrar pela cidade caminho dum dia, e pregava, e dizia: Ainda quarenta dias, e Nínive será subvertida.

[[v32-3-5]]

^<<v32-3-5,5>>^ E os homens de Nínive creram em Deus; e proclamaram um  jejum, e vestiram-se de saco, desde o maior até ao menor.

[[v32-3-6]]

^<<v32-3-6,6>>^ Porque esta palavra chegou ao rei de Nínive, e levantou-se do seu trono, e tirou de si os seus vestidos, e cobriu-se de saco, e assentou-se sobre a cinza.

[[v32-3-7]]

^<<v32-3-7,7>>^ E fez uma proclamação, que se divulgou em Nínive, por mandado do rei e dos seus grandes, dizendo: Nem homens, nem animais, nem bois, nem ovelhas provem cousa alguma, nem se lhes dê pasto, nem bebam água.

[[v32-3-8]]

^<<v32-3-8,8>>^ Mas os homens e os animais estarão cobertos de sacos, e clamarão fortemente a Deus, e se converterão, cada um do seu mau caminho, e da violência que há  nas suas mãos.

[[v32-3-9]]

^<<v32-3-9,9>>^ Quem sabe se se voltará Deus, e se arrependerá, e se apartará do furor da sua ira, de sorte que não pereçamos?

[[v32-3-10]]

^<<v32-3-10,10>>^ E Deus viu as obras deles, como se converteram do seu mau caminho: e Deus se arrependeu do mal que tinha dito lhes faria, e não o fez.

'''

xref:032-jonas/032-jonas-002.adoc#v32-2-0[&#60; Capítulo Anterior] | <<v32-3-0,Topo>> | xref:032-jonas/032-jonas-004.adoc#v32-4-0[Próximo Capítulo &#62;]