include::./index.adoc[]

[[v47-9-0]]
=== 2 Coríntios, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v47-9-1]]

^<<v47-9-1,1>>^ QUANTO à administração que se faz  a favor dos santos, não necessito escrever-vos;

[[v47-9-2]]

^<<v47-9-2,2>>^ Porque bem sei a prontidão do vosso ânimo, da qual me glorio de vós para com os macedônios; que a Acaia está pronta desde o ano passado, e o vosso zelo tem estimulado muitos.

[[v47-9-3]]

^<<v47-9-3,3>>^ Mas enviei estes irmãos, para que a nossa glória, acerca de vós, não seja vã nesta parte; para que (como já disse) possais estar prontos,

[[v47-9-4]]

^<<v47-9-4,4>>^ A fim de, se acaso, os macedônios vierem comigo, e vos acharem desapercebidos, não nos envergonharmos nós (para não dizermos vós) deste firme fundamento de glória.

[[v47-9-5]]

^<<v47-9-5,5>>^ Portanto, tive por coisa necessária exortar estes irmãos, para que primeiro fossem ter convosco, e preparassem de antemão a vossa bênção, já antes anunciada, para que esteja pronta como bênção, e não como avareza.

[[v47-9-6]]

^<<v47-9-6,6>>^ E digo  isto: Que o que semeia pouco, pouco também ceifará; e o que semeia em abundância, em abundância também ceifará.

[[v47-9-7]]

^<<v47-9-7,7>>^ Cada um contribua  segundo propôs no seu coração; não com tristeza ou por necessidade; porque Deus ama ao que dá com alegria.

[[v47-9-8]]

^<<v47-9-8,8>>^ E Deus é  poderoso para fazer abundar em vós toda a graça, a fim de que tendo sempre, em tudo, toda a suficiência, abundeis em toda a boa obra;

[[v47-9-9]]

^<<v47-9-9,9>>^ Conforme está escrito: Espalhou, deu aos pobres: a sua justiça permanece para sempre.

[[v47-9-10]]

^<<v47-9-10,10>>^ Ora, aquele que dá a semente ao que semeia, e pão para comer, também multiplicará a vossa sementeira, e aumentará os frutos da vossa justiça;

[[v47-9-11]]

^<<v47-9-11,11>>^ Para que em tudo enriqueçais para toda a beneficência, a qual faz que  por nós se deem  graças a Deus.

[[v47-9-12]]

^<<v47-9-12,12>>^ Porque a administração deste serviço, não só supre as necessidades dos santos, mas também abunda em muitas graças, que se dão  a Deus.

[[v47-9-13]]

^<<v47-9-13,13>>^ Visto como, na prova desta administração, glorificam a Deus pela submissão que confessais quanto ao evangelho de Cristo, e pela liberalidade de vossos dons para com eles, e para com todos;

[[v47-9-14]]

^<<v47-9-14,14>>^ E pela sua oração por vós, tendo de vós saudades, por causa da excelente graça de Deus que em vós há.

[[v47-9-15]]

^<<v47-9-15,15>>^ Graças a Deus pois pelo seu dom inefável.

'''

xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[Próximo Capítulo &#62;]