include::./index.adoc[]

[[v47-10-0]]
=== 2 Coríntios, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v47-10-1]]

^<<v47-10-1,1>>^ ALÉM disto, eu, Paulo, vos rogo, pela mansidão e benignidade de Cristo, eu que, na verdade, quando presente entre vós, sou  humilde, mas ausente, ousado para convosco;

[[v47-10-2]]

^<<v47-10-2,2>>^ Rogo- vos  pois que, quando estiver presente, não me veja obrigado a usar com confiança da ousadia que espero ter com alguns, que nos julgam, como se andássemos segundo a carne.

[[v47-10-3]]

^<<v47-10-3,3>>^ Porque, andando na carne, não militamos segundo a carne.

[[v47-10-4]]

^<<v47-10-4,4>>^ Porque as armas da nossa milícia não são carnais, mas sim poderosas em Deus, para destruição das fortalezas;

[[v47-10-5]]

^<<v47-10-5,5>>^ Destruindo os conselhos, e toda a altivez que se levanta contra o conhecimento de Deus, e levando cativo todo o entendimento à obediência de Cristo;

[[v47-10-6]]

^<<v47-10-6,6>>^ E estando prontos para vingar toda a desobediência, quando for cumprida a vossa obediência.

[[v47-10-7]]

^<<v47-10-7,7>>^ Olhais para as coisas segundo a aparência? Se alguém confia de si mesmo que é de Cristo, pense outra vez isto consigo, que, assim como ele é  de Cristo, também nós de Cristo somos.

[[v47-10-8]]

^<<v47-10-8,8>>^ Porque, ainda que eu me glorie mais alguma coisa do nosso poder, o qual o Senhor nos deu para edificação, e não para vossa destruição, não me envergonharei.

[[v47-10-9]]

^<<v47-10-9,9>>^ Para que não pareça como se quisera intimidar-vos por cartas.

[[v47-10-10]]

^<<v47-10-10,10>>^ Porque as suas cartas, dizem, são  graves e fortes, mas a presença do corpo é  fraca, e a palavra desprezível.

[[v47-10-11]]

^<<v47-10-11,11>>^ Pense o tal isto, que, quais somos na palavra por cartas, estando  ausentes, tais seremos também por obra, estando presentes.

[[v47-10-12]]

^<<v47-10-12,12>>^ Porque não ousamos classificar-nos, ou comparar-nos com alguns, que se louvam a si mesmos; mas estes que se medem a si mesmos, e se comparam consigo mesmos, estão sem entendimento.

[[v47-10-13]]

^<<v47-10-13,13>>^ Porém não nos gloriaremos fora de medida, mas conforme a reta medida que Deus nos deu, para chegarmos até vós;

[[v47-10-14]]

^<<v47-10-14,14>>^ Porque não nos estendemos além do que convém, como se não houvéssemos de chegar até vós, pois já  chegamos também até vós no evangelho de Cristo,

[[v47-10-15]]

^<<v47-10-15,15>>^ Não nos gloriando fora de medida nos trabalhos alheios; antes tendo esperança de que, crescendo a vossa fé, seremos abundantemente engrandecidos entre vós, conforme a nossa regra.

[[v47-10-16]]

^<<v47-10-16,16>>^ Para anunciar o evangelho nos lugares  que estão além de vós, e  não em campo de outrem, para nos não gloriarmos no que estava já preparado.

[[v47-10-17]]

^<<v47-10-17,17>>^ Aquele, porém, que se gloria, glorie-se no Senhor.

[[v47-10-18]]

^<<v47-10-18,18>>^ Porque não é aprovado quem a si mesmo se louva, mas sim aquele a quem o Senhor louva.

'''

xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[Próximo Capítulo &#62;]