include::./index.adoc[]

[[v47-7-0]]
=== 2 Coríntios, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v47-7-1]]

^<<v47-7-1,1>>^ ORA, amados, pois que temos tais promessas, purifiquemo-nos de toda a imundícia da carne e do espírito, aperfeiçoando a santificação no temor de Deus.

[[v47-7-2]]

^<<v47-7-2,2>>^ Recebei-nos em vossos corações: a ninguém agravamos, a ninguém corrompemos, de ninguém buscamos o nosso proveito.

[[v47-7-3]]

^<<v47-7-3,3>>^ Não digo isto  para vossa  condenação; pois já antes tinha dito que estais em nossos corações para juntamente morrer e viver.

[[v47-7-4]]

^<<v47-7-4,4>>^ Grande é a ousadia da minha fala para convosco, e grande a minha jactância a respeito de vós; estou cheio de consolação: superabundo de gozo em todas as nossas tribulações.

[[v47-7-5]]

^<<v47-7-5,5>>^ Porque, mesmo quando chegamos à Macedônia, a nossa carne não teve repouso algum; antes em tudo fomos atribulados: por fora combates, temores por dentro.

[[v47-7-6]]

^<<v47-7-6,6>>^ Mas Deus, que consola os abatidos, nos consolou com vinda de Tito.

[[v47-7-7]]

^<<v47-7-7,7>>^ E não somente com a sua vinda, mas também pela consolação com que foi consolado de vós, contando-nos as vossas saudades, o vosso choro, o vosso zelo por mim, de maneira que muito me regozijei.

[[v47-7-8]]

^<<v47-7-8,8>>^ Porquanto, ainda que vos contristei com a minha carta, não me arrependo, embora já me tivesse arrependido por ver que aquela carta vos contristou, ainda que por pouco tempo.

[[v47-7-9]]

^<<v47-7-9,9>>^ Agora folgo, não porque fostes contristados, mas porque fostes contristados para o arrependimento; pois fostes contristados segundo Deus; de maneira que por nós não padecestes dano em coisa alguma.

[[v47-7-10]]

^<<v47-7-10,10>>^ Porque a tristeza segundo Deus opera arrependimento para a salvação, da qual ninguém se arrepende; mas a tristeza do mundo opera a morte.

[[v47-7-11]]

^<<v47-7-11,11>>^ Porque, quanto cuidado não produziu isto mesmo em vós, que segundo Deus fostes contristados! que apologia, que indignação, que temor, que saudades, que zelo, que vingança! em tudo mostrastes estar puros neste  negócio.

[[v47-7-12]]

^<<v47-7-12,12>>^ Portanto, ainda que vos escrevi, não foi  por causa do que fez o agravo, nem por causa do que sofreu o agravo, mas para que o vosso grande cuidado por nós fosse manifesto diante de Deus.

[[v47-7-13]]

^<<v47-7-13,13>>^ Por isso fomos consolados pela vossa consolação, e muito mais nos alegramos pela alegria de Tito, porque o seu espírito foi recreado por vós todos.

[[v47-7-14]]

^<<v47-7-14,14>>^ Porque, se nalguma coisa me gloriei de vós para com ele, não fiquei envergonhado; mas, como vos dissemos tudo com verdade, também a nossa glória para com Tito se achou verdadeira.

[[v47-7-15]]

^<<v47-7-15,15>>^ E o seu entranhável afeto para convosco é mais abundante, lembrando-se da obediência de vós todos, e  de como o recebestes com temor e tremor.

[[v47-7-16]]

^<<v47-7-16,16>>^ Regozijo-me de em tudo poder confiar em vós.

'''

xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[&#60; Capítulo Anterior] | <<v47-7-0,Topo>> | xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[Próximo Capítulo &#62;]