include::./index.adoc[]

[[v47-6-0]]
=== 2 Coríntios, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v47-6-1]]

^<<v47-6-1,1>>^ E NÓS, cooperando também com ele, vos exortamos a que não recebais a graça de Deus em vão;

[[v47-6-2]]

^<<v47-6-2,2>>^ (Porque diz: Ouvi-te em tempo aceitável e socorri-te no dia da salvação: eis aqui agora o tempo aceitável, eis aqui agora o dia da salvação.)

[[v47-6-3]]

^<<v47-6-3,3>>^ Não dando nós escândalo em coisa  alguma, para que o nosso ministério não seja censurado;

[[v47-6-4]]

^<<v47-6-4,4>>^ Antes, como ministros de Deus, tornando-nos recomendáveis em tudo: na muita paciência, nas aflições, nas necessidades, nas angústias,

[[v47-6-5]]

^<<v47-6-5,5>>^ Nos açoites, nas prisões, nos tumultos, nos trabalhos, nas vigílias, nos jejuns.

[[v47-6-6]]

^<<v47-6-6,6>>^ Na pureza, na ciência, na longanimidade, na benignidade, no Espírito Santo, no amor não fingido.

[[v47-6-7]]

^<<v47-6-7,7>>^ Na palavra da verdade, no poder de Deus, pelas armas da justiça, à direita e à esquerda,

[[v47-6-8]]

^<<v47-6-8,8>>^ Por honra e por desonra, por infâmia e por boa fama: como enganadores, e sendo  verdadeiros;

[[v47-6-9]]

^<<v47-6-9,9>>^ Como desconhecidos, mas sendo bem-conhecidos: como morrendo, e eis que vivemos: como castigados, e não mortos;

[[v47-6-10]]

^<<v47-6-10,10>>^ Como contristados, mas sempre alegres: como pobres, mas enriquecendo a muitos: como nada tendo, e possuindo tudo.

[[v47-6-11]]

^<<v47-6-11,11>>^ Ó coríntios, a nossa boca está aberta para vós, o nosso coração está dilatado.

[[v47-6-12]]

^<<v47-6-12,12>>^ Não estais estreitados em nós; mas estais estreitados nos vossos próprios afetos.

[[v47-6-13]]

^<<v47-6-13,13>>^ Ora, em recompensa disto (falo como a filhos), dilatai-vos também vós.

[[v47-6-14]]

^<<v47-6-14,14>>^ Não vos prendais a um jugo desigual com os infiéis; porque, que sociedade tem a justiça com a injustiça? E que comunhão tem a luz com as trevas?

[[v47-6-15]]

^<<v47-6-15,15>>^ E que concórdia há entre Cristo e Belial? Ou que parte tem o fiel com o infiel?

[[v47-6-16]]

^<<v47-6-16,16>>^ E que consenso tem o templo de Deus com os ídolos? Porque vós sois o templo do Deus vivente, como Deus disse: Neles habitarei, e entre eles andarei: e eu serei o seu Deus e eles serão o meu povo.

[[v47-6-17]]

^<<v47-6-17,17>>^ Pelo que saí do meio deles, e apartai-vos, diz o Senhor; e não toqueis nada imundo, e eu vos receberei;

[[v47-6-18]]

^<<v47-6-18,18>>^ E eu serei para vós Pai e vós sereis para mim filhos e filhas, diz o Senhor todo-poderoso.

'''

xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[Próximo Capítulo &#62;]