include::./index.adoc[]

[[v47-4-0]]
=== 2 Coríntios, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v47-4-1]]

^<<v47-4-1,1>>^ PELO que, tendo este ministério, segundo a misericórdia que nos foi feita, não desfalecemos;

[[v47-4-2]]

^<<v47-4-2,2>>^ Antes, rejeitamos as coisas  que por vergonha se ocultam, não andando com astúcia nem falsificando a palavra de Deus; e assim nos recomendamos à consciência de todo o homem, na presença de Deus, pela manifestação da verdade.

[[v47-4-3]]

^<<v47-4-3,3>>^ Mas, se ainda o nosso evangelho está encoberto, para os que se perdem está encoberto.

[[v47-4-4]]

^<<v47-4-4,4>>^ Nos quais o deus deste século cegou os entendimentos dos incrédulos, para que lhes não resplandeça a luz do evangelho da glória de Cristo, que é a imagem de Deus.

[[v47-4-5]]

^<<v47-4-5,5>>^ Porque não nos pregamos a nós mesmos, mas a Cristo Jesus, o Senhor; e nós mesmos somos  vossos servos por amor de Jesus.

[[v47-4-6]]

^<<v47-4-6,6>>^ Porque Deus, que disse que das trevas resplandecesse a luz, é quem resplandeceu em nossos corações, para iluminação do conhecimento da glória de Deus, na face de Jesus Cristo.

[[v47-4-7]]

^<<v47-4-7,7>>^ Temos, porém, este tesouro em vasos de barro, para que a excelência do poder seja de Deus, e não de nós.

[[v47-4-8]]

^<<v47-4-8,8>>^ Em tudo somos  atribulados, mas não angustiados: perplexos, mas não desanimados;

[[v47-4-9]]

^<<v47-4-9,9>>^ Perseguidos, mas não desamparados; abatidos, mas não destruídos;

[[v47-4-10]]

^<<v47-4-10,10>>^ Trazendo sempre por toda a parte a mortificação do Senhor Jesus no nosso corpo, para que a vida de Jesus se manifeste também em nossos corpos;

[[v47-4-11]]

^<<v47-4-11,11>>^ E assim nós, que vivemos, estamos sempre entregues à morte por amor de Jesus, para que a vida de Jesus se manifeste também em a nossa carne mortal.

[[v47-4-12]]

^<<v47-4-12,12>>^ De maneira que em nós opera a morte, mas em vós a vida.

[[v47-4-13]]

^<<v47-4-13,13>>^ E temos portanto o mesmo espírito de fé, como está escrito: Cri, por isso falei: nós cremos também, por isso também falamos.

[[v47-4-14]]

^<<v47-4-14,14>>^ Sabendo que o que ressuscitou o Senhor Jesus nos ressuscitará também por Jesus, e nos apresentará convosco.

[[v47-4-15]]

^<<v47-4-15,15>>^ Porque tudo isto é por amor de vós, para que a graça, multiplicada por meio de muitos, faça abundar a ação de graças para glória de Deus.

[[v47-4-16]]

^<<v47-4-16,16>>^ Por isso não desfalecemos: mas, ainda que o nosso homem exterior se corrompa, o interior, contudo, se renova de dia em dia,

[[v47-4-17]]

^<<v47-4-17,17>>^ Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente;

[[v47-4-18]]

^<<v47-4-18,18>>^ Não atentando nós nas coisas  que se veem mas nas que se não veem; porque as que se veem são temporais, e as que se não veem são  eternas.

'''

xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[&#60; Capítulo Anterior] | <<v47-4-0,Topo>> | xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[Próximo Capítulo &#62;]