include::./index.adoc[]

[[v47-12-0]]
=== 2 Coríntios, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v47-12-1]]

^<<v47-12-1,1>>^ EM verdade que não convém gloriar-me; mas passarei às visões e revelações do Senhor.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um homem em Cristo que há quatorze anos (se no corpo não sei, se fora do corpo não sei: Deus o sabe) foi arrebatado até ao terceiro céu.

[[v47-12-3]]

^<<v47-12-3,3>>^ E sei que o tal homem (se no corpo, se fora do corpo, não sei; Deus o sabe).

[[v47-12-4]]

^<<v47-12-4,4>>^ Foi arrebatado ao paraíso; e ouviu palavras inefáveis, de que ao homem não é lícito falar.

[[v47-12-5]]

^<<v47-12-5,5>>^ De um assim me gloriarei eu, mas de mim mesmo não me gloriarei, senão nas minhas fraquezas.

[[v47-12-6]]

^<<v47-12-6,6>>^ Porque, se quiser gloriar-me, não serei néscio, porque direi a verdade; mas deixo isto , para que ninguém cuide de mim mais do que em mim vê ou de mim ouve.

[[v47-12-7]]

^<<v47-12-7,7>>^ E, para que me não exaltasse pelas excelências das revelações, foi-me dado um espinho na carne, a saber , um mensageiro de Satanás para me esbofetear, a fim de me não exaltar.

[[v47-12-8]]

^<<v47-12-8,8>>^ Acerca do qual três vezes orei ao Senhor para que se desviasse de mim.

[[v47-12-9]]

^<<v47-12-9,9>>^ E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. De boa vontade pois me gloriarei nas minhas fraquezas, para que em mim habite o poder de Cristo.

[[v47-12-10]]

^<<v47-12-10,10>>^ Pelo que sinto prazer nas fraquezas, nas injúrias, nas necessidades, nas perseguições, nas angústias por amor de Cristo. Porque quando estou fraco então sou forte.

[[v47-12-11]]

^<<v47-12-11,11>>^ Fui néscio em gloriar-me: vós me constrangestes; porque eu devia ser louvado por vós, visto que em nada fui inferior aos mais excelentes apóstolos; ainda que nada sou.

[[v47-12-12]]

^<<v47-12-12,12>>^ Os sinais do meu apostolado foram manifestados entre vós com toda a paciência, por sinais, prodígios e maravilhas.

[[v47-12-13]]

^<<v47-12-13,13>>^ Porque, em que tendes vós sido inferiores às outras igrejas, a não ser que eu mesmo vos não fui pesado? Perdoai-me este agravo.

[[v47-12-14]]

^<<v47-12-14,14>>^ Eis aqui estou pronto para pela terceira vez ir ter convosco, e não vos serei pesado, pois que não busco o que é vosso, mas sim a vós; porque não devem os filhos entesourar para os pais mas os pais para os filhos.

[[v47-12-15]]

^<<v47-12-15,15>>^ Eu de muito boa vontade gastarei, e me deixarei gastar pelas vossas almas, ainda que, amando-vos cada vez mais, seja menos amado.

[[v47-12-16]]

^<<v47-12-16,16>>^ Mas seja assim; eu não vos fui pesado, mas, sendo astuto, vos tomei com dolo.

[[v47-12-17]]

^<<v47-12-17,17>>^ Porventura aproveitei-me de vós por algum daqueles que vos enviei?

[[v47-12-18]]

^<<v47-12-18,18>>^ Roguei a Tito, e enviei com ele  um irmão. Porventura Tito se aproveitou de vós? Não andamos porventura no mesmo espírito, sobre as mesmas pisadas?

[[v47-12-19]]

^<<v47-12-19,19>>^ Cuidais que ainda nos desculpamos convosco? Falamos em Cristo perante Deus, e tudo isto, ó amados, para vossa edificação.

[[v47-12-20]]

^<<v47-12-20,20>>^ Porque receio que, quando chegar, vos não ache como eu quereria, e eu seja achado de vós como não quereríeis: que de alguma maneira haja  pendências, invejas, iras, porfias, detrações, mexericos, orgulhos, tumultos;

[[v47-12-21]]

^<<v47-12-21,21>>^ Que, quando for outra vez, o meu Deus me humilhe para convosco, e chore por muitos daqueles que dantes pecaram, e não se arrependeram da imundícia, e prostituição, e desonestidade que cometeram.

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]