include::./index.adoc[]

[[v47-11-0]]
=== 2 Coríntios, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v47-11-1]]

^<<v47-11-1,1>>^ OXALÁ me suportásseis um pouco na minha  loucura! Suportai-me, porém, ainda.

[[v47-11-2]]

^<<v47-11-2,2>>^ Porque estou zeloso de vós com zelo de Deus; porque vos tenho preparado para vos  apresentar como  uma virgem pura a um marido, a saber, a Cristo.

[[v47-11-3]]

^<<v47-11-3,3>>^ Mas temo que, assim como a serpente enganou Eva com a sua astúcia, assim também sejam de alguma sorte corrompidos os vossos sentidos, e se apartem  da simplicidade que há em Cristo.

[[v47-11-4]]

^<<v47-11-4,4>>^ Porque, se alguém for pregar-vos outro Jesus que nós não temos pregado, ou se recebeis outro espírito que não recebestes, ou outro evangelho que não abraçastes, com razão o sofrereis.

[[v47-11-5]]

^<<v47-11-5,5>>^ Porque penso que em nada fui inferior aos mais excelentes apóstolos.

[[v47-11-6]]

^<<v47-11-6,6>>^ E, se sou rude na palavra, não o sou  contudo na ciência; mas já em tudo nos temos feito conhecer totalmente entre vós.

[[v47-11-7]]

^<<v47-11-7,7>>^ Pequei porventura, humilhando-me a mim mesmo, para que vós fôsseis exaltados, porque de graça vos anunciei o evangelho de Deus?

[[v47-11-8]]

^<<v47-11-8,8>>^ Outras igrejas despojei eu para vos servir, recebendo delas  salário; e quando estava presente convosco, e tinha necessidade, a ninguém fui pesado.

[[v47-11-9]]

^<<v47-11-9,9>>^ Porque os irmãos que vieram da Macedônia supriram a minha necessidade; e em tudo me guardei de vos ser pesado, e ainda  me guardarei.

[[v47-11-10]]

^<<v47-11-10,10>>^ Como a verdade de Cristo está em mim, esta glória não me será impedida nas regiões da Acaia.

[[v47-11-11]]

^<<v47-11-11,11>>^ Por quê? Por que vos não amo? Deus o sabe.

[[v47-11-12]]

^<<v47-11-12,12>>^ Mas o que eu faço o farei, para cortar ocasião aos que buscam ocasião, a fim de que, naquilo em que se gloriam, sejam achados assim como nós.

[[v47-11-13]]

^<<v47-11-13,13>>^ Porque tais falsos apóstolos são  obreiros fraudulentos, transfigurando-se em apóstolos de Cristo.

[[v47-11-14]]

^<<v47-11-14,14>>^ E não é maravilha, porque o próprio Satanás se transfigura em anjo de luz.

[[v47-11-15]]

^<<v47-11-15,15>>^ Não é  muito pois que os seus ministros se transfigurem em ministros da justiça: o fim dos quais será conforme as suas obras.

[[v47-11-16]]

^<<v47-11-16,16>>^ Outra vez digo: ninguém me julgue insensato, ou então recebei-me como insensato, para que também me glorie um pouco.

[[v47-11-17]]

^<<v47-11-17,17>>^ O que digo, não o digo segundo o Senhor, mas como por loucura, nesta confiança de gloriar-me.

[[v47-11-18]]

^<<v47-11-18,18>>^ Pois que muitos se gloriam segundo a carne, eu também me gloriarei.

[[v47-11-19]]

^<<v47-11-19,19>>^ Porque, sendo vós sensatos, de boa mente tolerais os insensatos.

[[v47-11-20]]

^<<v47-11-20,20>>^ Pois sois sofredores, se alguém vos põe em servidão, se alguém vos  devora, se alguém vos  apanha, se alguém se exalta, se alguém vos fere no rosto.

[[v47-11-21]]

^<<v47-11-21,21>>^ Envergonhado o digo, como se nós fôssemos fracos, mas no que qualquer tem ousadia (com insensatez falo) também eu tenho ousadia.

[[v47-11-22]]

^<<v47-11-22,22>>^ São hebreus? também eu; são israelitas? também eu; são descendência de Abraão? também eu.

[[v47-11-23]]

^<<v47-11-23,23>>^ São ministros de Cristo? (falo como fora de mim) eu ainda mais: em trabalhos, muito mais; em açoites, mais do que eles; em prisões, muito mais; em perigo de  morte muitas vezes.

[[v47-11-24]]

^<<v47-11-24,24>>^ Recebi dos judeus cinco quarentenas de açoites  menos um.

[[v47-11-25]]

^<<v47-11-25,25>>^ Três vezes fui açoitado com varas, uma vez fui apedrejado, três vezes sofri naufrágio, uma noite e um dia passei no abismo;

[[v47-11-26]]

^<<v47-11-26,26>>^ Em viagens muitas vezes, em perigos de rios, em perigos de salteadores, em perigos dos da minha  nação, em perigos dos gentios, em perigos na cidade, em perigos no deserto, em perigos no mar, em perigos entre os falsos irmãos;

[[v47-11-27]]

^<<v47-11-27,27>>^ Em trabalhos e fadiga, em vigílias muitas vezes, em fome e sede, em jejum muitas vezes, em frio e nudez.

[[v47-11-28]]

^<<v47-11-28,28>>^ Além das coisas exteriores, me oprime cada dia o cuidado de todas as igrejas.

[[v47-11-29]]

^<<v47-11-29,29>>^ Quem enfraquece, que eu também não enfraqueça? Quem se escandaliza, que eu me não abrase?

[[v47-11-30]]

^<<v47-11-30,30>>^ Se convém gloriar-me, gloriar-me-ei no que diz respeito à minha fraqueza.

[[v47-11-31]]

^<<v47-11-31,31>>^ O Deus e Pai de Nosso Senhor Jesus Cristo, que é eternamente bendito, sabe que não minto.

[[v47-11-32]]

^<<v47-11-32,32>>^ Em Damasco, o que governava sob o rei Aretas pôs guardas às portas da cidade dos damascenos, para me prenderem.

[[v47-11-33]]

^<<v47-11-33,33>>^ E fui descido num cesto por uma janela da muralha; e assim  escapei das suas mãos.

'''

xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[Próximo Capítulo &#62;]