include::./index.adoc[]

[[v47-13-0]]
=== 2 Coríntios, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v47-13-1]]

^<<v47-13-1,1>>^ É ESTA a terceira vez que  vou ter convosco. Por boca de duas ou três testemunhas será confirmada toda a palavra.

[[v47-13-2]]

^<<v47-13-2,2>>^ Já anteriormente o  disse: e segunda vez o digo como quando estava presente; mas agora, estando ausente, o digo aos que antes pecaram e a todos os mais, que, se outra vez for, não lhes  perdoarei;

[[v47-13-3]]

^<<v47-13-3,3>>^ Visto que buscais uma  prova de Cristo que fala em mim, o qual não é fraco para convosco, antes é poderoso entre vós.

[[v47-13-4]]

^<<v47-13-4,4>>^ Porque, ainda que foi crucificado por fraqueza, vive contudo pelo poder de Deus. Porque nós também somos fracos nele, mas viveremos com ele pelo poder de Deus em vós.

[[v47-13-5]]

^<<v47-13-5,5>>^ Examinai-vos a vós mesmos, se permaneceis na fé; provai-vos a vós mesmos. Ou não sabeis quanto a vós mesmos, que Jesus Cristo está em vós? Se não é que já estais reprovados.

[[v47-13-6]]

^<<v47-13-6,6>>^ Mas espero que entendereis que nós não somos reprovados.

[[v47-13-7]]

^<<v47-13-7,7>>^ Ora eu rogo a Deus que não façais mal algum, não para que sejamos achados aprovados, mas para que vós façais o bem, embora nós sejamos como reprovados.

[[v47-13-8]]

^<<v47-13-8,8>>^ Porque nada podemos contra a verdade, senão pela verdade.

[[v47-13-9]]

^<<v47-13-9,9>>^ Porque nos regozijamos de estar fracos, quando vós estais fortes; e o que desejamos é a vossa perfeição.

[[v47-13-10]]

^<<v47-13-10,10>>^ Portanto, escrevo estas coisas  estando ausente, para que, estando presente, não use de rigor, segundo o poder que o Senhor me deu para edificação e não para destruição.

[[v47-13-11]]

^<<v47-13-11,11>>^ Quanto ao mais, irmãos, regozijai-vos, sede perfeitos, sede consolados, sede de um mesmo  parecer, vivei em paz; e o Deus de amor e de paz será convosco.

[[v47-13-12]]

^<<v47-13-12,12>>^ Saudai-vos uns aos outros com ósculo santo. Todos os santos vos saúdam.

[[v47-13-13]]

^<<v47-13-13,13>>^ A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo seja  com vós todos. Amém.

'''

xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[&#60; Capítulo Anterior] | <<v47-13-0,Topo>> | xref:048-galatas/048-galatas-001.adoc#v48-1-0[Próximo Capítulo &#62;]