include::./index.adoc[]

[[v10-17-0]]
=== 2 Samuel, 17
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-17-1]]

^<<v10-17-1,1>>^ DISSE mais Aquitófel a Absalão: Deixa-me escolher doze mil homens, e me levantarei e seguirei após Davi esta noite.

[[v10-17-2]]

^<<v10-17-2,2>>^ E irei sobre ele, pois está cansado e fraco das mãos: e o espantarei, e fugirá todo o povo que está  com ele; e então  ferirei o rei só.

[[v10-17-3]]

^<<v10-17-3,3>>^ E farei tornar a ti todo o povo: pois  o homem a quem tu buscas é como se tornassem todos; assim  todo o povo estará em paz.

[[v10-17-4]]

^<<v10-17-4,4>>^ E esta palavra pareceu boa aos olhos de Absalão, e aos olhos de todos os anciãos de Israel.

[[v10-17-5]]

^<<v10-17-5,5>>^ Disse porém Absalão: Chamai agora também a Husai, o arquita: e ouçamos também o que ele dirá.

[[v10-17-6]]

^<<v10-17-6,6>>^ E, chegando Husai a Absalão, lhe falou Absalão, dizendo: Desta maneira falou Aquitófel: faremos conforme  à sua palavra? Se não, fala tu.

[[v10-17-7]]

^<<v10-17-7,7>>^ Então disse Husai a Absalão: O conselho que Aquitófel esta vez aconselhou não é bom.

[[v10-17-8]]

^<<v10-17-8,8>>^ Disse mais Husai: Bem  conheces tu a teu pai, e a seus homens, que são valorosos e que estão  com o espírito amargurado, como a ursa no campo, roubada dos cachorros: também teu pai é  homem de guerra, e não passará a noite com o povo.

[[v10-17-9]]

^<<v10-17-9,9>>^ Eis que agora estará escondido nalguma cova, ou em qualquer outro lugar: e será que caindo no princípio alguns  dentre eles, cada um que ouvir então dirá: Houve derrota no povo que segue Absalão.

[[v10-17-10]]

^<<v10-17-10,10>>^ Então até o homem valente, cujo coração é como o coração de leão, sem dúvida desmaiará; porque todo o Israel sabe que teu pai é valoroso, e homens valentes os que estão  com ele.

[[v10-17-11]]

^<<v10-17-11,11>>^ Eu porém aconselho que com toda a pressa se ajunte a ti todo o Israel desde Dã até Berseba, em multidão como a areia do mar: e que tu em pessoa vás à peleja.

[[v10-17-12]]

^<<v10-17-12,12>>^ Então iremos a ele, em qualquer lugar que se achar, e facilmente viremos sobre ele, como o orvalho cai sobre a terra; e não ficará dele e de todos os homens que estão com ele nem ainda  um só.

[[v10-17-13]]

^<<v10-17-13,13>>^ E, se ele se retirar para alguma  cidade, todo o Israel trará cordas àquela cidade: e arrastá-la-emos até ao ribeiro, até que não se ache ali nem uma só pedrinha.

[[v10-17-14]]

^<<v10-17-14,14>>^ Então disse Absalão e todos os homens de Israel: Melhor é  o conselho de Husai, o arquita, do que o conselho de Aquitófel (porém assim  o Senhor o ordenara, para aniquilar o bom conselho de Aquitófel, para que o Senhor trouxesse o mal sobre Absalão).

[[v10-17-15]]

^<<v10-17-15,15>>^ E disse Husai a Zadoque e a Abiatar, sacerdotes: Assim e assim aconselhou Aquitófel a Absalão e aos anciãos de Israel; porém assim e assim aconselhei eu.

[[v10-17-16]]

^<<v10-17-16,16>>^ Agora, pois, enviai apressadamente, e avisai a Davi, dizendo: Não passes esta noite nas campinas do deserto, mas passa depressa à outra banda, para que o rei e todo o povo que com ele está  não seja devorado.

[[v10-17-17]]

^<<v10-17-17,17>>^ Estavam pois Jônatas e Aimaás junto à fonte de Rogel: e foi uma criada, e lho disse, e eles foram, e disseram ao rei Davi, porque não podiam ser vistos entrar na cidade.

[[v10-17-18]]

^<<v10-17-18,18>>^ Mas viu-os todavia um moço, e avisou a Absalão; porém ambos logo  partiram apressadamente, e entraram em casa de um  homem, em Baurim, o qual tinha um  poço no seu pátio, e para ali desceram.

[[v10-17-19]]

^<<v10-17-19,19>>^ E tomou a mulher a tampa, e a estendeu sobre a boca do poço, e espalhou grão descascado sobre ela: assim nada se soube.

[[v10-17-20]]

^<<v10-17-20,20>>^ Chegando pois os servos de Absalão à mulher, àquela casa, disseram: Onde estão  Aimaás e Jônatas? E a mulher lhes disse: Já passaram o vau das águas. E, havendo-os buscado, e não os  achando, voltaram para Jerusalém.

[[v10-17-21]]

^<<v10-17-21,21>>^ E sucedeu que, depois que partiram, saíram do poço, e foram, e anunciaram a Davi; e disseram a Davi: Levantai-vos, e passai depressa as águas, porque assim aconselhou contra vós Aquitófel.

[[v10-17-22]]

^<<v10-17-22,22>>^ Então Davi e todo o povo que com ele estava  se levantou, e passaram o Jordão: e já  pela luz da manhã nem ainda faltava um só que não passasse o Jordão.

[[v10-17-23]]

^<<v10-17-23,23>>^ Vendo pois Aquitófel que se não tinha seguido o seu conselho, albardou o jumento e levantou-se, e foi para sua casa e para a sua cidade, e pôs em ordem a sua casa, e se enforcou: e morreu, e foi sepultado na sepultura de seu pai.

[[v10-17-24]]

^<<v10-17-24,24>>^ E Davi veio a Maanaim; e Absalão passou o Jordão, ele e todo o homem de Israel com ele.

[[v10-17-25]]

^<<v10-17-25,25>>^ E Absalão constituiu a Amasa em lugar de Joabe sobre o arraial: e era  Amasa filho de um homem cujo nome era  Jetra, o israelita, o qual entrara a Abigail, filha de Naás, irmã de Zeruia, mãe de Joabe.

[[v10-17-26]]

^<<v10-17-26,26>>^ Israel, pois, e Absalão acamparam na terra de Gileade.

[[v10-17-27]]

^<<v10-17-27,27>>^ E sucedeu que, chegando Davi a Maanaim, Sobi, filho de Naás, de Rabá, dos filhos de Amom, e Maquir, filho de Amiel, de Lo-Debar, e Barzilai, o gileadita, de Rogelim,

[[v10-17-28]]

^<<v10-17-28,28>>^ Tomaram camas e bacias, e vasilhas de barro, e trigo, e cevada, e farinha, e grão  torrado, e favas, e lentilhas, também torradas,

[[v10-17-29]]

^<<v10-17-29,29>>^ E mel, e manteiga, e ovelhas, e queijos de vacas, e  os trouxeram a Davi e ao povo que com ele estava , para comerem, porque disseram: Este povo no deserto está faminto, e cansado, e sedento.

'''

xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[&#60; Capítulo Anterior] | <<v10-17-0,Topo>> | xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[Próximo Capítulo &#62;]