include::./index.adoc[]

[[v10-20-0]]
=== 2 Samuel, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-20-1]]

^<<v10-20-1,1>>^ ENTÃO se achou ali por acaso um homem de Belial, cujo nome era Seba, filho de Bicri, homem de Benjamim, o qual tocou a buzina, e disse: Não temos parte em Davi, nem herança no filho de Jessé; cada um às suas tendas, ó Israel.

[[v10-20-2]]

^<<v10-20-2,2>>^ Então todos os homens de Israel deixaram de seguir Davi, e seguiram Seba, filho de Bicri; porém os homens de Judá se uniram ao seu rei desde o Jordão até Jerusalém.

[[v10-20-3]]

^<<v10-20-3,3>>^ Vindo pois Davi para sua casa, a Jerusalém, tomou o rei as dez mulheres, suas  concubinas, que deixara para guardarem a casa, e as pôs numa casa em guarda, e as sustentava; porém não entrou a elas: e estiveram encerradas até ao dia da sua morte, vivendo como  viúvas.

[[v10-20-4]]

^<<v10-20-4,4>>^ Disse mais o rei a Amasa: Convoca-me os homens de Judá para o terceiro dia: e tu então  apresenta-te aqui.

[[v10-20-5]]

^<<v10-20-5,5>>^ E foi Amasa para convocar a Judá: porém demorou-se além do tempo que lhe tinha designado.

[[v10-20-6]]

^<<v10-20-6,6>>^ Então disse Davi a Abisai: Mais mal agora nos fará Seba, o filho de Bicri, do  que Absalão: pelo que  toma tu os servos de teu senhor, e persegue-o, para que porventura  não ache para si cidades fortes, e escape dos nossos olhos.

[[v10-20-7]]

^<<v10-20-7,7>>^ Então saíram atrás dele os homens de Joabe, e os quereteus, e os peleteus, e todos os valentes: estes saíram de Jerusalém para irem atrás de Seba, filho de Bicri.

[[v10-20-8]]

^<<v10-20-8,8>>^ Chegando eles pois  à pedra grande que está  junto a Gibeom, Amasa veio perante eles: e estava  Joabe cingido da sua roupa que vestiu, e sobre ela um cinto com a espada, em seus lombos, na sua bainha: e, adiantando-se ele, lhe  caiu.

[[v10-20-9]]

^<<v10-20-9,9>>^ E disse Joabe a Amasa: Vai contigo bem, meu irmão? E Joabe, com a mão direita, pegou da barba de Amasa, para o beijar.

[[v10-20-10]]

^<<v10-20-10,10>>^ E Amasa não se resguardou da espada que estava  na mão de Joabe, de sorte que este o feriu com ela na quinta costela , e lhe derramou por terra as entranhas; e não o feriu segunda vez, e morreu: então Joabe e Abisai, seu irmão, foram atrás de Seba, filho de Bicri.

[[v10-20-11]]

^<<v10-20-11,11>>^ Mas um dentre os moços de Joabe parou junto a ele, e disse: Quem há que bem queira a Joabe, e quem seja por Davi, siga a Joabe.

[[v10-20-12]]

^<<v10-20-12,12>>^ E Amasa estava envolto no seu sangue no meio do caminho: e, vendo aquele homem que todo o povo parava, desviou a Amasa do caminho para o campo, e lançou sobre ele um manto; porque via que todo aquele que chegava a ele parava.

[[v10-20-13]]

^<<v10-20-13,13>>^ E, como estava apartado do caminho, todos os homens seguiram a Joabe, para perseguirem a Seba filho de Bicri.

[[v10-20-14]]

^<<v10-20-14,14>>^ E passou por todas as tribos de Israel até Abel, a saber, a Bete-Maaca e a todos os beritas: e ajuntaram-se todos, e também o seguiram.

[[v10-20-15]]

^<<v10-20-15,15>>^ E vieram, e o cercaram em Abel de Bete-Maaca, e levantaram uma  tranqueira contra a cidade, assim que já  estava em frente do  antemuro: e todo o povo que estava  com Joabe batia o muro, para o derribar.

[[v10-20-16]]

^<<v10-20-16,16>>^ Então uma mulher sábia gritou de dentro da cidade: Ouvi, ouvi, peço- vos que  digais a Joabe: Chega-te cá, para que eu te fale.

[[v10-20-17]]

^<<v10-20-17,17>>^ Chegou-se a ela, e disse a mulher: Tu és Joabe? E disse ele: Eu sou.  E ela lhe disse: Ouve as palavras de tua serva. E disse ele: Ouço.

[[v10-20-18]]

^<<v10-20-18,18>>^ Então falou ela, dizendo: Antigamente costumava-se falar, dizendo: Certamente pediram conselho a Abel; e assim o cumpriam.

[[v10-20-19]]

^<<v10-20-19,19>>^ Eu sou uma  das pacíficas e das fiéis em Israel: e tu procuras matar uma cidade que é madre em Israel: por que pois  devorarias a herança do Senhor?

[[v10-20-20]]

^<<v10-20-20,20>>^ Então respondeu Joabe, e disse: Longe, longe de mim que eu tal faça, que eu devore ou arruíne!

[[v10-20-21]]

^<<v10-20-21,21>>^ A cousa não é assim: porém um só  homem do monte de Efraim, cujo nome é Seba, filho de Bicri, levantou a mão contra o rei, contra Davi; entregai-me só este, e retirar-me-ei da cidade. Então disse a mulher a Joabe: Eis que te será lançada a sua cabeça pelo muro.

[[v10-20-22]]

^<<v10-20-22,22>>^ E a mulher, na sua sabedoria, entrou a todo o povo, e cortaram a cabeça de Seba, filho de Bicri, e a lançaram a Joabe: então tocou a buzina, e se retiraram da cidade, cada um para as suas tendas, e Joabe voltou a Jerusalém, ao rei.

[[v10-20-23]]

^<<v10-20-23,23>>^ E Joabe estava  sobre todo o exército de Israel; e Benaia, filho de Joiada, sobre os quereteus e sobre os peleteus;

[[v10-20-24]]

^<<v10-20-24,24>>^ E Adorão sobre os tributos; e Josafá, filho de Ailude, era  o chanceler;

[[v10-20-25]]

^<<v10-20-25,25>>^ E Seva o escrivão; e Zadoque e Abiatar os sacerdotes;

[[v10-20-26]]

^<<v10-20-26,26>>^ E também Ira, o jairita, era o oficial-mor de Davi.

'''

xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[&#60; Capítulo Anterior] | <<v10-20-0,Topo>> | xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[Próximo Capítulo &#62;]