include::./index.adoc[]

[[v10-9-0]]
=== 2 Samuel, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-9-1]]

^<<v10-9-1,1>>^ E DISSE Davi: Há ainda alguém que ficasse da casa de Saul, para que lhe faça bem por amor de Jônatas?

[[v10-9-2]]

^<<v10-9-2,2>>^ E havia  um servo na casa de Saul cujo nome era  Ziba: e o chamaram que viesse  a Davi, e disse-lhe o rei: És  tu Ziba? E ele disse: Servo teu.

[[v10-9-3]]

^<<v10-9-3,3>>^ E disse o rei: Não há  ainda algum da casa de Saul para que use com ele de beneficência de Deus? Então disse Ziba ao rei: Ainda há um filho de Jônatas, aleijado de ambos os pés.

[[v10-9-4]]

^<<v10-9-4,4>>^ E disse-lhe o rei: Onde está? E disse Ziba ao rei: Eis que está  em casa de Maquir, filho de Amiel, em Lo-Debar.

[[v10-9-5]]

^<<v10-9-5,5>>^ Então mandou o rei Davi, e o tomou da casa de Maquir, filho de Amiel, de Lo-Debar.

[[v10-9-6]]

^<<v10-9-6,6>>^ E vindo Mefibosete, filho de Jônatas, o filho de Saul, a Davi, se prostrou com o rosto por  terra e se inclinou; e disse Davi: Mefibosete! E ele disse: Eis aqui teu servo.

[[v10-9-7]]

^<<v10-9-7,7>>^ E disse-lhe Davi: Não temas, porque decerto usarei contigo de beneficência por amor de Jônatas, teu pai, e te restituirei todas as terras de Saul, teu pai, e tu de contínuo comerás pão à minha mesa.

[[v10-9-8]]

^<<v10-9-8,8>>^ Então se inclinou, e disse: Quem é  teu servo, para tu teres olhado para um cão morto tal  como eu?

[[v10-9-9]]

^<<v10-9-9,9>>^ Então chamou Davi a Ziba, moço de Saul, e disse-lhe: Tudo o que pertencia a Saul, e de toda a sua casa, tenho dado ao filho de teu senhor.

[[v10-9-10]]

^<<v10-9-10,10>>^ Trabalhar-lhe-eis pois a terra, tu e teus filhos, e teus servos, e recolherás os frutos , para que o filho de teu senhor tenha pão que coma; e Mefibosete, filho de teu senhor, de contínuo comerá pão à minha mesa. E tinha Ziba quinze filhos e vinte servos.

[[v10-9-11]]

^<<v10-9-11,11>>^ E disse Ziba ao rei: Conforme a tudo quanto meu senhor, o rei, manda a seu servo, assim fará teu servo; porém Mefibosete comerá à minha mesa como um dos filhos do rei.

[[v10-9-12]]

^<<v10-9-12,12>>^ E tinha Mefibosete um filho pequeno, cujo nome era Mica: e todos quantos moravam em casa de Ziba eram servos de Mefibosete.

[[v10-9-13]]

^<<v10-9-13,13>>^ Morava pois Mefibosete em Jerusalém, porquanto de contínuo comia à mesa do rei, e era coxo de ambos os pés.

'''

xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[&#60; Capítulo Anterior] | <<v10-9-0,Topo>> | xref:010-2-samuel/010-2-samuel-010.adoc#v10-10-0[Próximo Capítulo &#62;]