include::./index.adoc[]

[[v10-2-0]]
=== 2 Samuel, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-2-1]]

^<<v10-2-1,1>>^ E SUCEDEU depois disto que Davi consultou ao Senhor, dizendo: Subirei a alguma das cidades de Judá? E disse-lhe o Senhor: Sobe. E disse Davi: Para onde subirei? E disse: Para Hebrom.

[[v10-2-2]]

^<<v10-2-2,2>>^ E subiu Davi para lá, e também a suas duas mulheres, Aquinoã, a jezreelita, e Abigail, a mulher de Nabal, o carmelita.

[[v10-2-3]]

^<<v10-2-3,3>>^ Fez também Davi subir os homens que estavam com ele, cada um com a sua família: e habitaram nas cidades de Hebrom.

[[v10-2-4]]

^<<v10-2-4,4>>^ Então vieram os homens de Judá, e ungiram ali a Davi rei sobre a casa de Judá. E deram avisos a Davi, dizendo: Os homens de Jabes-Gileade são  os que sepultaram a Saul.

[[v10-2-5]]

^<<v10-2-5,5>>^ Então enviou Davi mensageiros aos homens de Jabes-Gileade, e disse-lhes: Benditos sejais  vós do Senhor, que fizestes tal beneficência a vosso senhor, a Saul, e o sepultastes!

[[v10-2-6]]

^<<v10-2-6,6>>^ Agora, pois, o Senhor use convosco de beneficência e fidelidade: e também eu vos farei este bem, porquanto fizestes isto.

[[v10-2-7]]

^<<v10-2-7,7>>^ Esforcem-se pois agora as vossas mãos, e sede homens valentes, pois Saul, vosso senhor, é morto, mas também os da casa de Judá já me  ungiram a mim rei sobre si.

[[v10-2-8]]

^<<v10-2-8,8>>^ Porém Abner, filho de Ner, capitão do exército de Saul, tomou a Isbosete, filho de Saul, e o fez passar a Maanaim.

[[v10-2-9]]

^<<v10-2-9,9>>^ E o constituiu rei sobre Gileade e sobre os assuritas, e sobre Jezreel, e sobre Efraim, e sobre Benjamim, e sobre todo o Israel.

[[v10-2-10]]

^<<v10-2-10,10>>^ Da idade de quarenta anos era  Isbosete, filho de Saul, quando começou a  reinar sobre Israel, e reinou dois anos: mas os da casa de Judá seguiam a Davi.

[[v10-2-11]]

^<<v10-2-11,11>>^ E foi o número dos dias que Davi reinou em Hebrom, sobre a casa de Judá, sete anos e seis meses.

[[v10-2-12]]

^<<v10-2-12,12>>^ Então saiu Abner, filho de Ner, com os servos de Isbosete, filho de Saul, de Maanaim a Gibeom.

[[v10-2-13]]

^<<v10-2-13,13>>^ Saíram também Joabe, filho de Zeruia, e os servos de Davi, e se encontraram uns com os outros perto do tanque de Gibeom: e pararam estes desta banda do tanque e os outros daquela banda do tanque.

[[v10-2-14]]

^<<v10-2-14,14>>^ E  disse Abner a Joabe: Deixa levantar os mancebos, e joguem diante de nós. E disse Joabe: Levantem-se.

[[v10-2-15]]

^<<v10-2-15,15>>^ Então se levantaram e passaram, por conta, doze de Benjamim, da parte de Isbosete, filho de Saul, e doze dos servos de Davi.

[[v10-2-16]]

^<<v10-2-16,16>>^ E cada um lançou mão da cabeça do outro, meteu-lhe  a espada pela ilharga, e caíram juntamente: donde se chamou àquele lugar Helcate-Hazurim que está  junto a Gibeom.

[[v10-2-17]]

^<<v10-2-17,17>>^ E seguiu-se naquele dia uma crua peleja: porém Abner e os homens de Israel foram feridos diante dos servos de Davi.

[[v10-2-18]]

^<<v10-2-18,18>>^ E estavam ali os três filhos de Zeruia, Joabe, Abisai, e Asael; e Asael era  ligeiro de pés, como uma das cabras monteses  que há no campo.

[[v10-2-19]]

^<<v10-2-19,19>>^ E Asael seguiu após Abner: e não declinou de detrás de Abner, nem para a direita nem para a esquerda.

[[v10-2-20]]

^<<v10-2-20,20>>^ E Abner, olhando para trás, disse: És tu Asael? E disse ele: Eu sou.

[[v10-2-21]]

^<<v10-2-21,21>>^ Então lhe disse Abner: Desvia-te para a direita, ou para a esquerda e lança mão dum dos mancebos, e toma os seus despojos. Porém Asael não quis desviar-se de detrás dele.

[[v10-2-22]]

^<<v10-2-22,22>>^ Então Abner tornou a dizer a Asael: Desvia-te de detrás de mim; por que hei de eu ferir-te e dar contigo em terra? e como levantaria eu o meu rosto diante de Joabe teu irmão?

[[v10-2-23]]

^<<v10-2-23,23>>^ Porém, não se querendo ele desviar, Abner o feriu com o conto da lança pela quinta costela , e a lança lhe saiu por detrás, e caiu ali, e morreu naquele mesmo lugar; e sucedeu que todos os que chegavam ao lugar onde Asael caiu e morreu, paravam.

[[v10-2-24]]

^<<v10-2-24,24>>^ Porém Joabe e Abisai seguiram após Abner: e pôs-se o sol, chegando eles ao outeiro de Amá, que está  diante de Giá, junto ao caminho do deserto de Gibeom.

[[v10-2-25]]

^<<v10-2-25,25>>^ E os filhos de Benjamim se ajuntaram detrás de Abner, e fizeram um batalhão, e puseram-se no cume dum outeiro.

[[v10-2-26]]

^<<v10-2-26,26>>^ Então Abner gritou a Joabe, e disse: Consumirá a espada para sempre? não sabes tu  que por fim haverá amargura? e até quando não hás de dizer ao povo que deixe de seguir a seus irmãos?

[[v10-2-27]]

^<<v10-2-27,27>>^ E disse Joabe: Vive Deus, que, se não tivesses falado já desde pela manhã o povo teria cessado cada um de seguir a seu irmão.

[[v10-2-28]]

^<<v10-2-28,28>>^ Então Joabe tocou a buzina, e todo o povo parou, e não perseguiram mais a Israel: e tão pouco pelejaram mais.

[[v10-2-29]]

^<<v10-2-29,29>>^ E caminharam Abner e os seus homens toda aquela noite pela planície; e, passando o Jordão, caminharam por todo o Bitrom, e vieram a Maanaim.

[[v10-2-30]]

^<<v10-2-30,30>>^ Também Joabe se tornou de seguir a Abner, e ajuntou todo o povo: e dos servos de Davi faltaram dezenove homens e Asael.

[[v10-2-31]]

^<<v10-2-31,31>>^ Porém os servos de Davi feriram dentre os de Benjamim, e dentre os homens de Abner, a trezentos e sessenta homens, que ali  ficaram mortos.

[[v10-2-32]]

^<<v10-2-32,32>>^ E levantaram a Asael, e sepultaram-no na sepultura de seu pai, que estava  em Belém; e Joabe e seus homens caminharam toda aquela noite, e amanheceu-lhes em Hebrom.

'''

xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[&#60; Capítulo Anterior] | <<v10-2-0,Topo>> | xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[Próximo Capítulo &#62;]