include::./index.adoc[]

[[v10-4-0]]
=== 2 Samuel, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-4-1]]

^<<v10-4-1,1>>^ OUVINDO pois o filho de Saul que Abner morrera em Hebrom, as mãos se lhe afrouxaram: e todo o Israel pasmou.

[[v10-4-2]]

^<<v10-4-2,2>>^ E tinha o filho de Saul dois homens capitães de tropas: e era  o nome dum Baena, e o nome do outro Recabe, filhos de Rimom, o beerotita, dos filhos de Benjamim, porque também Beerote se reputava de Benjamim.

[[v10-4-3]]

^<<v10-4-3,3>>^ E tinham fugido os beerotitas para Gitaim, e ali têm peregrinado até ao dia de  hoje.

[[v10-4-4]]

^<<v10-4-4,4>>^ E Jônatas, filho de Saul, tinha um filho aleijado de ambos  os pés: era da idade de cinco anos quando as novas de Saul e Jônatas vieram de Jezreel, e sua ama o tomou, e fugiu: e sucedeu que, apressando-se ela a fugir, ele caiu e ficou coxo; e o seu nome era Mefibosete.

[[v10-4-5]]

^<<v10-4-5,5>>^ E foram os filhos de Rimom, o beerotita, Recabe e Baena, e entraram em casa de Isbosete no maior calor do dia, estando ele deitado a dormir, ao meio-dia.

[[v10-4-6]]

^<<v10-4-6,6>>^ E ali entraram até o meio da casa, como que vindo  tomar trigo, e o feriram na quinta costela : e Recabe e Baena, seu irmão, escaparam.

[[v10-4-7]]

^<<v10-4-7,7>>^ Porque entraram na sua  casa, estando ele na cama deitado na sua recâmara, e o feriram, e o mataram, e lhe cortaram a cabeça; e, tomando a sua cabeça, andaram toda a noite caminhando pela planície.

[[v10-4-8]]

^<<v10-4-8,8>>^ E trouxeram a cabeça de Isbosete a Davi, a Hebrom, e disseram ao rei: Eis aqui a cabeça de Isbosete, filho de Saul, teu inimigo, que te procurava a morte: assim o Senhor vingou hoje ao rei meu senhor de Saul e da sua semente.

[[v10-4-9]]

^<<v10-4-9,9>>^ Porém Davi, respondendo a Recabe e a Baena, seu irmão, filhos de Rimom, o beerotita, disse-lhes: Vive o Senhor que remiu a minha alma de toda a angústia,

[[v10-4-10]]

^<<v10-4-10,10>>^ Pois se àquele que me trouxe novas, dizendo: Eis que Saul morto é, parecendo-lhe porém  aos seus olhos que era como quem trazia boas novas, eu logo lancei mão dele, e o matei em Siclague, cuidando  ele que eu por isso  lhe desse alvíssaras;

[[v10-4-11]]

^<<v10-4-11,11>>^ Quanto mais a ímpios homens, que  mataram um homem justo em sua casa, sobre a sua cama: agora, pois, não requereria eu o seu sangue de vossas mãos, e não vos exterminaria da terra?

[[v10-4-12]]

^<<v10-4-12,12>>^ E deu Davi ordem aos seus mancebos que os matassem: e cortaram-lhes os pés e as mãos, e os penduraram sobre o tanque de Hebrom: tomaram porém a cabeça de Isbosete, e a sepultaram na sepultura de Abner, em Hebrom.

'''

xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[&#60; Capítulo Anterior] | <<v10-4-0,Topo>> | xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[Próximo Capítulo &#62;]