include::./index.adoc[]

[[v10-11-0]]
=== 2 Samuel, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-11-1]]

^<<v10-11-1,1>>^ E ACONTECEU que, tendo decorrido um ano, no tempo em que os reis saem, enviou Davi a Joabe e a seus servos com ele e a todo o Israel, para que destruíssem os filhos de Amom e cercassem a Rabá; porém Davi ficou em Jerusalém.

[[v10-11-2]]

^<<v10-11-2,2>>^ E aconteceu à hora da tarde que Davi se levantou do seu leito, e andava passeando no terraço da casa real, e viu do terraço a uma mulher que  se estava lavando: e era  esta mulher mui formosa à vista.

[[v10-11-3]]

^<<v10-11-3,3>>^ E enviou Davi, e perguntou por aquela mulher: e disseram: Porventura  não é  esta Batseba, filha de Eliã, mulher de Urias, o heteu?

[[v10-11-4]]

^<<v10-11-4,4>>^ Então enviou Davi mensageiros, e a mandou trazer: e entrando ela a ele, se deitou com ela (e já  ela se tinha purificado da sua imundície): então voltou ela para sua casa.

[[v10-11-5]]

^<<v10-11-5,5>>^ E a mulher concebeu; e enviou, e fê-lo saber a Davi, e disse: Pejada estou.

[[v10-11-6]]

^<<v10-11-6,6>>^ Então enviou Davi a Joabe, dizendo : Envia-me Urias o heteu. E Joabe enviou Urias a Davi.

[[v10-11-7]]

^<<v10-11-7,7>>^ Vindo pois Urias a ele, perguntou Davi como ficava Joabe, e como ficava o povo e como ia a guerra.

[[v10-11-8]]

^<<v10-11-8,8>>^ Depois disse Davi a Urias: Desce a tua casa, e lava os teus pés. E, saindo Urias da casa real, logo  saiu atrás dele iguaria do rei.

[[v10-11-9]]

^<<v10-11-9,9>>^ Porém Urias se deitou à porta da casa real, com todos os servos do seu senhor: e não desceu à sua casa.

[[v10-11-10]]

^<<v10-11-10,10>>^ E o fizeram saber a Davi, dizendo: Urias não desceu à sua casa. Então disse Davi a Urias: Não vens tu duma  jornada? Por que não desceste à tua casa?

[[v10-11-11]]

^<<v10-11-11,11>>^ E disse Urias a Davi: A arca, e Israel, e Judá ficam em tendas; e Joabe meu Senhor e os servos de meu senhor estão acampados no campo; e hei de eu entrar na minha casa, para comer e beber, e para me deitar com minha mulher? Pela tua vida, e pela vida da tua alma, não farei tal cousa.

[[v10-11-12]]

^<<v10-11-12,12>>^ Então disse Davi a Urias: Fica cá ainda hoje, e amanhã te despedirei. Urias pois ficou em Jerusalém aquele dia e o seguinte.

[[v10-11-13]]

^<<v10-11-13,13>>^ E Davi o convidou, e comeu e bebeu diante dele, e o embebedou: e à tarde saiu a deitar-se na sua cama como os servos de seu senhor; porém não desceu à sua casa.

[[v10-11-14]]

^<<v10-11-14,14>>^ E sucedeu que pela manhã Davi escreveu uma carta a Joabe: e mandou-lha por mão de Urias.

[[v10-11-15]]

^<<v10-11-15,15>>^ Escreveu na carta dizendo: Ponde a Urias na frente da maior força da peleja; e retirai-vos de detrás dele para que seja ferido e morra.

[[v10-11-16]]

^<<v10-11-16,16>>^ Aconteceu, pois, que, tendo Joabe observado bem a cidade, pôs a Urias no lugar onde sabia que havia  homens valentes.

[[v10-11-17]]

^<<v10-11-17,17>>^ E, saindo os homens da cidade, e pelejando com Joabe, caíram alguns  do povo, dos servos de Davi: e morreu também Urias, o heteu.

[[v10-11-18]]

^<<v10-11-18,18>>^ Então enviou Joabe, fez saber a Davi todo o sucesso daquela peleja.

[[v10-11-19]]

^<<v10-11-19,19>>^ E deu ordem ao mensageiro dizendo: Acabando tu de contar ao rei todo o sucesso desta peleja;

[[v10-11-20]]

^<<v10-11-20,20>>^ E sucedendo que o rei se encolerize, e te diga: Por que vos chegastes tão perto  da cidade a pelejar? Não sabíeis vós que haviam de atirar do muro?

[[v10-11-21]]

^<<v10-11-21,21>>^ Quem feriu a Abimeleque, filho de Jerubesete? Não lançou uma mulher sobre ele do muro um pedaço duma mó corredora, de que morreu em Tebes? Por que vos chegastes ao muro? Então dirás: Também morreu teu servo Urias, o heteu.

[[v10-11-22]]

^<<v10-11-22,22>>^ E foi o mensageiro, e entrou e fez saber a Davi, tudo, para que Joabe o enviara.

[[v10-11-23]]

^<<v10-11-23,23>>^ E disse o mensageiro a Davi: Na verdade  que mais poderosos foram aqueles homens do que nós, e saíram a nós ao campo: porém nós fomos contra eles, até à entrada da porta.

[[v10-11-24]]

^<<v10-11-24,24>>^ Então os frecheiros atiraram contra os teus servos desde o alto do muro, e morreram alguns  dos servos do rei: e também morreu o teu servo Urias, o heteu.

[[v10-11-25]]

^<<v10-11-25,25>>^ E disse Davi ao mensageiro: Assim dirás a Joabe: Não te pareça isto mal aos teus olhos; pois a espada tanto consome este como aquele: esforça a tua peleja contra a cidade, e a derrota: esforça-o tu assim.

[[v10-11-26]]

^<<v10-11-26,26>>^ Ouvindo pois a mulher de Urias que Urias seu marido era morto, lamentou a seu senhor.

[[v10-11-27]]

^<<v10-11-27,27>>^ E, passado o nojo, enviou Davi, e a recolheu em sua casa, e lhe foi por mulher, e ela lhe deu um filho. Porém esta cousa que Davi fez pareceu mal aos olhos do Senhor.

'''

xref:010-2-samuel/010-2-samuel-010.adoc#v10-10-0[&#60; Capítulo Anterior] | <<v10-11-0,Topo>> | xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[Próximo Capítulo &#62;]