include::./index.adoc[]

[[v10-22-0]]
=== 2 Samuel, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-22-1]]

^<<v10-22-1,1>>^ E FALOU Davi ao Senhor as palavras deste cântico, no dia em que o Senhor o livrou das mãos de todos os seus inimigos e das mãos de Saul.

[[v10-22-2]]

^<<v10-22-2,2>>^ Disse pois: O Senhor é  o meu rochedo, e o meu lugar forte, e o meu libertador.

[[v10-22-3]]

^<<v10-22-3,3>>^ Deus é  o meu rochedo nele confiarei: o meu escudo, e a força de minha salvação, o meu alto retiro, e o meu refúgio. Ó meu Salvador, de violência me salvaste.

[[v10-22-4]]

^<<v10-22-4,4>>^ O Senhor, digno de louvor, invoquei, e de meus inimigos fiquei livre.

[[v10-22-5]]

^<<v10-22-5,5>>^ Porque me cercaram as ondas de morte: as torrentes de Belial me assombraram.

[[v10-22-6]]

^<<v10-22-6,6>>^ Cordas do inferno me cingiram; encontraram-me laços de morte.

[[v10-22-7]]

^<<v10-22-7,7>>^ Estando em angústia invoquei ao Senhor, e a meu Deus clamei: do seu templo ouviu ele a minha voz, e o meu clamor chegou  aos seus ouvidos.

[[v10-22-8]]

^<<v10-22-8,8>>^ Então se abalou e tremeu a terra, os fundamentos dos céus se moveram e abalaram, porque ele se irou.

[[v10-22-9]]

^<<v10-22-9,9>>^ Subiu o fumo de seus narizes, e da sua boca um fogo devorador: carvões se incenderam dele.

[[v10-22-10]]

^<<v10-22-10,10>>^ E abaixou os céus, e desceu: e uma escuridão havia debaixo de seus pés.

[[v10-22-11]]

^<<v10-22-11,11>>^ E subiu um querubim, e voou: e foi visto sobre as asas do vento.

[[v10-22-12]]

^<<v10-22-12,12>>^ E por tendas pôs as trevas ao redor de si: ajuntamento de águas, nuvens dos céus.

[[v10-22-13]]

^<<v10-22-13,13>>^ Pelo resplendor da sua presença brasas de fogo se acendem.

[[v10-22-14]]

^<<v10-22-14,14>>^ Trovejou desde os céus o Senhor e o Altíssimo fez soar a sua voz.

[[v10-22-15]]

^<<v10-22-15,15>>^ E disparou frechas, e os dissipou: raios, e os perturbou.

[[v10-22-16]]

^<<v10-22-16,16>>^ E apareceram as profundezas do mar, os fundamentos do mundo se descobriram: pela repreensão do Senhor; pelo sopro do vento dos seus narizes.

[[v10-22-17]]

^<<v10-22-17,17>>^ Desde o alto enviou, e  me tomou; tirou-me das muitas águas.

[[v10-22-18]]

^<<v10-22-18,18>>^ Livrou-me do meu possante inimigo, e  daqueles que me tinham ódio, porque eram mais fortes do que eu.

[[v10-22-19]]

^<<v10-22-19,19>>^ Encontraram-me no dia da minha calamidade: porém o Senhor se fez o meu esteio.

[[v10-22-20]]

^<<v10-22-20,20>>^ E tirou-me para o largo, e arrebatou-me dali ; porque tinha prazer em mim.

[[v10-22-21]]

^<<v10-22-21,21>>^ Recompensou-me o Senhor conforme à minha justiça: conforme à pureza de minhas mãos me retribuiu.

[[v10-22-22]]

^<<v10-22-22,22>>^ Porque guardei os caminhos do Senhor: e não me apartei impiamente do meu Deus.

[[v10-22-23]]

^<<v10-22-23,23>>^ Porque todos os seus juízos estavam  diante de mim: e de seus estatutos me não desviei.

[[v10-22-24]]

^<<v10-22-24,24>>^ Porém fui sincero perante ele: e guardei-me da minha iniquidade.

[[v10-22-25]]

^<<v10-22-25,25>>^ E me retribuiu o Senhor conforme à minha justiça, conforme à minha pureza diante dos seus olhos.

[[v10-22-26]]

^<<v10-22-26,26>>^ Com o benigno te mostras benigno: com o varão sincero te mostras sincero.

[[v10-22-27]]

^<<v10-22-27,27>>^ Com o puro te mostras puro: mas com o perverso te mostras avesso.

[[v10-22-28]]

^<<v10-22-28,28>>^ E o povo aflito te livras: mas teus olhos são contra os altivos, e  tu os  abaterás.

[[v10-22-29]]

^<<v10-22-29,29>>^ Porque tu, Senhor, és  a minha candeia: e o Senhor esclarece as minhas trevas.

[[v10-22-30]]

^<<v10-22-30,30>>^ Porque contigo passo pelo meio dum esquadrão: pelo meu Deus salto um muro.

[[v10-22-31]]

^<<v10-22-31,31>>^ O caminho de Deus é  perfeito e a palavra do Senhor refinada; e é o escudo de todos os que nele confiam.

[[v10-22-32]]

^<<v10-22-32,32>>^ Porque, quem é  Deus, senão o Senhor? e quem é rochedo, senão o nosso Deus?

[[v10-22-33]]

^<<v10-22-33,33>>^ Deus é a minha fortaleza e  a minha  força, e ele perfeitamente desembaraça o meu caminho.

[[v10-22-34]]

^<<v10-22-34,34>>^ Faz ele os meus pés como os das cervas, e me põe sobre as minhas alturas.

[[v10-22-35]]

^<<v10-22-35,35>>^ Instrui as minhas mãos para a peleja, de maneira que um arco de cobre se quebra pelos meus braços.

[[v10-22-36]]

^<<v10-22-36,36>>^ Também me deste o escudo da tua salvação, e pela tua brandura me vieste a engrandecer.

[[v10-22-37]]

^<<v10-22-37,37>>^ Alargaste os meus passos debaixo de mim, e não vacilaram os meus artelhos.

[[v10-22-38]]

^<<v10-22-38,38>>^ Persegui os meus inimigos, e os derrotei, e nunca me tornei até que os consumisse.

[[v10-22-39]]

^<<v10-22-39,39>>^ E os consumi, e os atravessei, de modo que nunca mais se levantaram, mas caíram debaixo dos meus pés.

[[v10-22-40]]

^<<v10-22-40,40>>^ Porque me cingiste de força para a peleja, fizeste abater debaixo de mim os que se levantaram contra mim.

[[v10-22-41]]

^<<v10-22-41,41>>^ E deste-me o pescoço de meus inimigos, daqueles que me tinham ódio, e os destruí.

[[v10-22-42]]

^<<v10-22-42,42>>^ Olharam, porém, não houve  libertador: sim, para o Senhor, porém não lhes respondeu.

[[v10-22-43]]

^<<v10-22-43,43>>^ Então os moí como o pó da terra; como a lama das ruas os trilhei e dissipei.

[[v10-22-44]]

^<<v10-22-44,44>>^ Também me livraste das contendas do meu povo; guardaste-me para cabeça das nações; o povo que  não conhecia, me servirá.

[[v10-22-45]]

^<<v10-22-45,45>>^ Os filhos de estranhos se me sujeitaram; ouvindo a minha voz , me obedeceram.

[[v10-22-46]]

^<<v10-22-46,46>>^ Os filhos de estranhos descaíram; e, cingindo-se, saíram  dos seus encerramentos.

[[v10-22-47]]

^<<v10-22-47,47>>^ Vive o Senhor, e bendito seja  o meu rochedo; e exaltado seja Deus, a rocha da minha salvação:

[[v10-22-48]]

^<<v10-22-48,48>>^ O Deus que me dá inteira vingança e sujeita os povos debaixo de mim.

[[v10-22-49]]

^<<v10-22-49,49>>^ E o que me tira dentre os meus inimigos: e tu me exaltas sobre os que contra mim se levantam; do homem violento me livras.

[[v10-22-50]]

^<<v10-22-50,50>>^ Por isso, ó Senhor, te louvarei entre as gentes, e entoarei louvores ao teu nome.

[[v10-22-51]]

^<<v10-22-51,51>>^ Ele é  a torre das salvações do seu rei, e usa de benignidade com o seu ungido, com Davi, e com a sua semente para sempre.

'''

xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[&#60; Capítulo Anterior] | <<v10-22-0,Topo>> | xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[Próximo Capítulo &#62;]