include::./index.adoc[]

[[v10-21-0]]
=== 2 Samuel, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-21-1]]

^<<v10-21-1,1>>^ E HOUVE em dias de Davi uma fome de três anos, de ano em ano; e Davi consultou o Senhor, e o Senhor lhe disse: É por causa de Saul e da sua casa sanguinária, porque matou os gibeonitas.

[[v10-21-2]]

^<<v10-21-2,2>>^ Então chamou o rei aos gibeonitas, e lhes falou (ora os gibeonitas não eram  dos filhos de Israel, mas do resto dos amorreus, e os filhos de Israel lhes tinham jurado, porém Saul procurou feri-los no seu zelo pelos filhos de Israel e de Judá).

[[v10-21-3]]

^<<v10-21-3,3>>^ Disse pois Davi aos gibeonitas: Que quereis que  eu vos faça? e que satisfação vos darei, para que abençoeis a herança do Senhor?

[[v10-21-4]]

^<<v10-21-4,4>>^ Então os gibeonitas lhe disseram: Não é por  prata nem ouro que  temos questão com Saul e com sua casa; nem tão pouco pretendemos matar pessoa alguma em Israel. E disse ele: Que é pois que  quereis que vos faça?

[[v10-21-5]]

^<<v10-21-5,5>>^ E disseram ao rei: Quanto ao homem que nos destruiu, e procurou que  fôssemos assolados, sem que pudéssemos subsistir em termo algum de Israel.

[[v10-21-6]]

^<<v10-21-6,6>>^ De seus filhos se nos deem sete homens, para que os enforquemos ao Senhor em Gibeá de Saul, o eleito do Senhor. E disse o rei: Eu os  darei.

[[v10-21-7]]

^<<v10-21-7,7>>^ Porém o rei poupou a Mefibosete, filho de Jônatas, filho de Saul, por causa do juramento do Senhor, que entre eles houvera , entre Davi e Jônatas, filho de Saul.

[[v10-21-8]]

^<<v10-21-8,8>>^ Porém tomou o rei os dois filhos de Rispa, filha de Aia, que tinha tido de Saul, a saber  a Armoni e a Mefibosete; como também os cinco filhos da irmã  de Mical, filha de Saul, que tivera de Adriel, filho de Barzilai, meolatita.

[[v10-21-9]]

^<<v10-21-9,9>>^ E os entregou na mão dos gibeonitas, os quais os enforcaram no monte, perante o Senhor; e caíram estes sete juntamente: e foram mortos nos dias da sega, nos dias  primeiros, no princípio da sega das cevadas.

[[v10-21-10]]

^<<v10-21-10,10>>^ Então Rispa, filha de Aia, tomou um pano de cilício, e estendeu-lho sobre uma penha, desde o princípio da sega, até que destilou a água sobre eles do céu: e não deixou as aves do céu pousar sobre eles de dia, nem os animais do campo de noite.

[[v10-21-11]]

^<<v10-21-11,11>>^ E foi dito a Davi o que fizera Rispa, filha de Aia, concubina de Saul.

[[v10-21-12]]

^<<v10-21-12,12>>^ Então foi Davi, e tomou os ossos de Saul, e os ossos de Jônatas seu filho, dos moradores de Jabes-Gileade os quais os furtaram da rua de Bete-Sã, onde os filisteus os tinham pendurado, quando os filisteus feriram a Saul em Gilboa.

[[v10-21-13]]

^<<v10-21-13,13>>^ E fez subir dali os ossos de Saul, e os ossos de Jônatas seu filho: e ajuntaram também  os ossos dos enforcados.

[[v10-21-14]]

^<<v10-21-14,14>>^ Enterraram os ossos de Saul, e de Jônatas seu filho na terra de Benjamim, em Zela, na sepultura de seu pai Quis, e fizeram tudo o que o rei ordenara; e depois disto Deus se aplacou para com a terra.

[[v10-21-15]]

^<<v10-21-15,15>>^ Tiveram mais os filisteus uma peleja contra Israel: e desceu Davi, e com ele os seus servos: e tanto  pelejaram contra os filisteus, que Davi se cansou.

[[v10-21-16]]

^<<v10-21-16,16>>^ E Isbi-Benobe, que era  dos filhos do gigante, e o peso de cuja lança tinha  trezentos siclos  de cobre, e que cingia uma espada  nova, este intentou ferir Davi.

[[v10-21-17]]

^<<v10-21-17,17>>^ Porém Abisai, filho de Zeruia, o socorreu, e feriu o filisteu, e o matou: então os homens de Davi lhe juraram, dizendo: Nunca mais sairás conosco à peleja, para que não apagues a lâmpada de Israel.

[[v10-21-18]]

^<<v10-21-18,18>>^ E aconteceu depois disto que houve em Gobe ainda outra peleja contra os filisteus: então Sibecai, o husatita, feriu a Safe, que era  dos filhos do gigante.

[[v10-21-19]]

^<<v10-21-19,19>>^ Houve mais outra peleja contra os filisteus em Gobe: e Elanã, filho de Jaaré-Oregim, o belemita feriu Golias, o geteu, de cuja lança era a haste como órgão de tecelão.

[[v10-21-20]]

^<<v10-21-20,20>>^ Houve ainda também outra peleja em Gate, onde estava um  homem de alta estatura, que tinha em cada mão seis dedos, e em cada pé outros seis, vinte e quatro por todos, e também este nascera do gigante.

[[v10-21-21]]

^<<v10-21-21,21>>^ E injuriava a Israel: porém Jônatas, filho de Simeia, irmão de Davi, o feriu.

[[v10-21-22]]

^<<v10-21-22,22>>^ Estes quatro nasceram ao gigante em Gate: e caíram pela mão de Davi e pela mão de seus servos.

'''

xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[&#60; Capítulo Anterior] | <<v10-21-0,Topo>> | xref:010-2-samuel/010-2-samuel-022.adoc#v10-22-0[Próximo Capítulo &#62;]