include::./index.adoc[]

[[v10-24-0]]
=== 2 Samuel, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-24-1]]

^<<v10-24-1,1>>^ E A ira do Senhor se tornou a acender contra Israel: e incitou a Davi contra eles, dizendo: Vai, numera a Israel e a Judá.

[[v10-24-2]]

^<<v10-24-2,2>>^ Disse pois o rei a Joabe, chefe do exército, o qual tinha  consigo: agora rodeia por todas as tribos de Israel, desde Dã até Berseba, e numera o povo: para que eu saiba o número do povo.

[[v10-24-3]]

^<<v10-24-3,3>>^ Então disse Joabe ao rei: Ora, multiplique o Senhor teu Deus a este povo cem vezes tanto quanto agora  é, e os olhos do rei meu senhor o vejam: mas por que deseja o rei meu senhor este negócio?

[[v10-24-4]]

^<<v10-24-4,4>>^ Porém a palavra do rei prevaleceu contra Joabe, e contra os chefes do exército: Joabe pois saiu com os chefes do exército diante da face do rei, a numerar o povo de Israel.

[[v10-24-5]]

^<<v10-24-5,5>>^ E passaram o Jordão: e puseram-se em campo junto a Aroer, à direita da cidade que está  no meio do ribeiro de Gade, e junto a Jazer.

[[v10-24-6]]

^<<v10-24-6,6>>^ E vieram a Gileade, e à terra baixa de Hodsi: também vieram até Danjaã e ao redor de Sidom.

[[v10-24-7]]

^<<v10-24-7,7>>^ E vieram à fortaleza de Tiro, e a todas as cidades dos heveus e dos cananeus: e saíram para a banda do sul de Judá, a Berseba.

[[v10-24-8]]

^<<v10-24-8,8>>^ Assim rodearam por toda a terra: e ao cabo de nove meses e vinte dias voltaram a Jerusalém.

[[v10-24-9]]

^<<v10-24-9,9>>^ E Joabe deu ao rei a soma do número do povo contado: e havia em Israel oitocentos mil homens de guerra, que arrancaram espada; e os homens de Judá eram  quinhentos mil homens.

[[v10-24-10]]

^<<v10-24-10,10>>^ E o coração doeu a Davi, depois de haver numerado o povo: e disse Davi ao Senhor: Muito pequei no  que fiz: porém agora, ó Senhor, peço-te que  traspasses a iniquidade do teu servo; porque tenho procedido mui loucamente.

[[v10-24-11]]

^<<v10-24-11,11>>^ Levantando-se pois Davi pela manhã, veio a palavra do Senhor ao profeta Gade, vidente de Davi, dizendo:

[[v10-24-12]]

^<<v10-24-12,12>>^ Vai, e dize a Davi: Assim diz o Senhor: três cousas te ofereço; escolhe uma delas, para que ta faça.

[[v10-24-13]]

^<<v10-24-13,13>>^ Veio pois Gade a Davi, e fez-lho saber; e disse-lhe: Queres  que sete anos de fome te venham à tua terra; ou que por três meses fujas diante de teus inimigos, e eles te persigam; ou que por três dias haja peste na tua terra? Delibera agora, e vê que resposta hei de dar ao que me enviou.

[[v10-24-14]]

^<<v10-24-14,14>>^ Então disse Davi a Gade: Estou em grande angústia: porém caiamos nas mãos do Senhor, porque muitas são  as suas misericórdias; mas nas mãos dos homens não caia eu.

[[v10-24-15]]

^<<v10-24-15,15>>^ Então enviou o Senhor a peste a Israel, desde pela manhã até ao tempo determinado: e desde Dã até Berseba, morreram setenta mil homens do povo.

[[v10-24-16]]

^<<v10-24-16,16>>^ Estendendo pois o anjo a sua mão sobre Jerusalém, para a destruir, o Senhor se arrependeu daquele mal; e disse ao anjo que fazia a destruição entre o povo: Basta, agora retira a tua mão. E o anjo do Senhor estava junto à eira de Araúna jebuseu.

[[v10-24-17]]

^<<v10-24-17,17>>^ E, vendo Davi ao anjo que feria o povo falou ao Senhor, e disse: Eis que eu sou o que  pequei, e eu o que  iniquamente obrei; porém estas ovelhas que fizeram? seja pois a tua mão contra mim, e contra a casa de meu pai.

[[v10-24-18]]

^<<v10-24-18,18>>^ E Gade veio naquele mesmo dia a Davi; e disse-lhe: Sobe, levanta ao Senhor um altar na eira de Araúna, o jebuseu.

[[v10-24-19]]

^<<v10-24-19,19>>^ Davi subiu conforme à palavra de Gade, como o Senhor lhe tinha ordenado.

[[v10-24-20]]

^<<v10-24-20,20>>^ E olhou Araúna, e viu que vinham para ele o rei e os seus servos: saiu pois Araúna, e inclinou-se diante do rei com o rosto em terra.

[[v10-24-21]]

^<<v10-24-21,21>>^ E disse Araúna: Por que vem o rei meu Senhor ao seu servo? E disse Davi: Para comprar de ti esta  eira, a fim de edificar nela  um altar ao Senhor, para que este castigo cesse de sobre o povo.

[[v10-24-22]]

^<<v10-24-22,22>>^ Então disse Araúna a Davi: Tome e ofereça o rei meu senhor o que bem parecer  aos seus olhos: eis ai bois para o holocausto, e os trilhos, e o aparelho dos bois para a lenha.

[[v10-24-23]]

^<<v10-24-23,23>>^ Tudo isto deu Araúna ao rei: disse mais Araúna ao rei: O Senhor teu Deus tome prazer em ti.

[[v10-24-24]]

^<<v10-24-24,24>>^ Porém o rei disse a Araúna: Não, porém por certo preço to comprarei, porque não oferecerei ao Senhor meu Deus holocaustos que me não custem nada. Assim Davi comprou a eira e os bois por cinquenta siclos de prata.

[[v10-24-25]]

^<<v10-24-25,25>>^ E edificou ali Davi ao Senhor um altar, e ofereceu holocaustos, e ofertas pacíficas. Assim o Senhor se aplacou para com a terra, e cessou aquele castigo de sobre Israel.

'''

xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[&#60; Capítulo Anterior] | <<v10-24-0,Topo>> | xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[Próximo Capítulo &#62;]