include::./index.adoc[]

[[v10-13-0]]
=== 2 Samuel, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-13-1]]

^<<v10-13-1,1>>^ E ACONTECEU depois disto que, tendo Absalão, filho de Davi, uma irmã formosa, cujo nome era Tamar, Amnom, filho de Davi, amou-a.

[[v10-13-2]]

^<<v10-13-2,2>>^ E angustiou-se Amnom, até adoecer, por Tamar, sua irmã, porque era virgem: e parecia aos olhos de Amnom dificultoso fazer-lhe cousa alguma.

[[v10-13-3]]

^<<v10-13-3,3>>^ Tinha porém Amnom um amigo, cujo nome era Jonadabe, filho de Simeia, irmão de Davi: e era Jonadabe homem mui sagaz.

[[v10-13-4]]

^<<v10-13-4,4>>^ O qual lhe disse: Por que tu de manhã em manhã tanto emagreces, sendo filho do rei? não mo farás saber a mim? Então lhe disse Amnom: Amo a Tamar, irmã de Absalão, meu irmão,

[[v10-13-5]]

^<<v10-13-5,5>>^ E Jonadabe lhe disse: Deita-te na tua cama, e finge-te doente: e, quando teu pai te vier visitar, dize-lhe: Peço- te que minha irmã Tamar venha, e me dê de comer pão, e prepare a comida diante dos meus olhos, para que eu a veja e coma da sua mão.

[[v10-13-6]]

^<<v10-13-6,6>>^ Deitou-se pois Amnom, e fingiu-se doente; e, vindo o rei visitá-lo, disse Amnon ao rei: Peço-te que  minha irmã Tamar venha, e prepare dois bolos diante dos meus olhos, para que eu coma de sua mão.

[[v10-13-7]]

^<<v10-13-7,7>>^ Mandou então Davi a casa, a Tamar, dizendo: Vai a casa de Amnom, teu irmão, e faze-lhe alguma comida.

[[v10-13-8]]

^<<v10-13-8,8>>^ E foi Tamar a casa de Amnom, seu irmão (ele porém estava  deitado), e tomou massa, e a amassou, e fez bolos diante dos seus olhos, e cozeu os bolos.

[[v10-13-9]]

^<<v10-13-9,9>>^ E tomou a sertã, e os tirou diante dele; porém ele recusou comer. E disse Amnom: Fazei retirar a todos da minha presença. E todos se retiraram dele.

[[v10-13-10]]

^<<v10-13-10,10>>^ Então disse Amnom a Tamar: Traze a comida à câmara e comerei da tua mão. E tomou Tamar os bolos que fizera, e os trouxe a Amnom, seu irmão, à câmara.

[[v10-13-11]]

^<<v10-13-11,11>>^ E chegando-lhos, para que comesse, pegou dela, e disse-lhe: Vem, deita-te comigo, irmã minha.

[[v10-13-12]]

^<<v10-13-12,12>>^ Porém ela lhe disse: Não, irmão meu, não me forces, porque não se faz assim em Israel; não faças tal loucura.

[[v10-13-13]]

^<<v10-13-13,13>>^ Porque, aonde iria eu com a minha vergonha? E tu serias como um dos loucos de Israel. Agora, pois, peço- te  que fales ao rei, porque não me negará a ti.

[[v10-13-14]]

^<<v10-13-14,14>>^ Porém ele não quis dar ouvidos à sua voz; antes, sendo mais forte do que ela, a forçou, e se deitou com ela.

[[v10-13-15]]

^<<v10-13-15,15>>^ Depois Amnom a aborreceu com grandíssimo aborrecimento, porque maior era o aborrecimento com que a aborrecia do que o amor com que a amara. E disse-lhe Amnom: Levanta-te, e vai-te.

[[v10-13-16]]

^<<v10-13-16,16>>^ Então ela lhe disse: Não há razão de me despedires assim ; maior seria este mal do que o outro que já me tens feito. Porém não lhe quis dar ouvidos.

[[v10-13-17]]

^<<v10-13-17,17>>^ E chamou a seu moço que o servia, e disse: Deita a esta fora, e fecha a porta após ela.

[[v10-13-18]]

^<<v10-13-18,18>>^ E trazia ela uma roupa de muitas cores (porque assim se vestiam as filhas virgens dos reis, com capas), e seu criado a deitou fora, e fechou a porta após ela.

[[v10-13-19]]

^<<v10-13-19,19>>^ Então Tamar tomou cinza sobre a sua cabeça, e a roupa de muitas cores que trazia rasgou: e pôs as mãos sobre a cabeça, e foi-se andando e clamando.

[[v10-13-20]]

^<<v10-13-20,20>>^ E Absalão, seu irmão, lhe disse: Esteve Amnom, teu irmão, contigo? Ora pois; irmã minha, cala-te; é teu irmão. Não se angustie o teu coração por isto. Assim ficou Tamar, e esteve solitária em casa de Absalão seu irmão.

[[v10-13-21]]

^<<v10-13-21,21>>^ E, ouvindo o rei Davi todas estas cousas, muito se acendeu em ira.

[[v10-13-22]]

^<<v10-13-22,22>>^ Porém Absalão não falou com Amnom, nem mal nem bem; porque Absalão aborrecia a Amnom, por ter forçado a Tamar sua irmã.

[[v10-13-23]]

^<<v10-13-23,23>>^ E aconteceu que, passados dois anos inteiros, Absalão tinha tosquiadores em Balazor, que está junto a Efraim: e convidou Absalão a todos os filhos do rei.

[[v10-13-24]]

^<<v10-13-24,24>>^ E veio Absalão ao rei, e disse: Eis que teu servo tem tosquiadores: peço que  o rei e os seus servos venham com o teu servo.

[[v10-13-25]]

^<<v10-13-25,25>>^ O rei porém disse a Absalão: Não, filho meu, não vamos todos juntos, para não te sermos pesados. E instou com ele; porém ele não quis ir, mas o abençoou.

[[v10-13-26]]

^<<v10-13-26,26>>^ Então disse Absalão: Quando não, deixa ir conosco Amnom, meu irmão. Porém o rei lhe disse: Para que iria contigo?

[[v10-13-27]]

^<<v10-13-27,27>>^ E, instando Absalão com ele, deixou ir com ele a Amnom, e a todos os filhos do rei.

[[v10-13-28]]

^<<v10-13-28,28>>^ E Absalão deu ordem aos seus moços, dizendo: Tomai sentido; quando o coração de Amnom estiver alegre do vinho e eu vos disser: Feri a Amnom, então o matareis; não temais; porventura  não sou eu quem vo-lo ordenou? Esforçai-vos, e sede valentes.

[[v10-13-29]]

^<<v10-13-29,29>>^ E os moços de Absalão fizeram a Amnom como Absalão lho havia ordenado. Então todos os filhos do rei se levantaram, e montaram cada um no seu mulo, e fugiram.

[[v10-13-30]]

^<<v10-13-30,30>>^ E aconteceu que, estando eles ainda  no caminho, veio a nova de Davi, de que se  dizia: Absalão feriu a todos os filhos do rei, e nenhum deles ficou.

[[v10-13-31]]

^<<v10-13-31,31>>^ Então o rei se levantou, e rasgou os seus vestidos, e se lançou por terra: da mesma maneira todos os seus servos estavam com vestidos rotos.

[[v10-13-32]]

^<<v10-13-32,32>>^ Mas Jonadabe, filho de Simeia, irmão de Davi, respondeu, e disse: Não diga o meu senhor que  mataram a todos os mancebos filhos do rei, porque só morreu Amnom: porque assim o tinha resolvido fazer Absalão, desde o dia em que ele forçou a Tamar sua irmã.

[[v10-13-33]]

^<<v10-13-33,33>>^ Não se lhe meta pois agora no coração do rei meu senhor tal cousa, dizendo: Morreram todos os filhos do rei: porque só morreu Amnom.

[[v10-13-34]]

^<<v10-13-34,34>>^ E Absalão fugiu: e o mancebo que estava de guarda, levantou os seus olhos, e olhou; e eis que muito povo vinha pelo caminho por detrás dele, pela banda do monte.

[[v10-13-35]]

^<<v10-13-35,35>>^ Então disse Jonadabe ao rei: Eis aqui vêm os filhos do rei: conforme à palavra de teu servo, assim sucedeu.

[[v10-13-36]]

^<<v10-13-36,36>>^ E aconteceu que, quando acabou de falar, os filhos do rei vieram, e levantaram a sua voz, e choraram: e também o rei e todos os seus servos choraram com mui grande choro.

[[v10-13-37]]

^<<v10-13-37,37>>^ Assim Absalão fugiu, e se foi a Talmai filho de Amiur, rei de Gesur. E Davi  trouxe dó por seu filho todos aqueles dias.

[[v10-13-38]]

^<<v10-13-38,38>>^ Assim Absalão fugiu, e foi para Gesur: esteve ali três anos.

[[v10-13-39]]

^<<v10-13-39,39>>^ Então tinha o rei Davi saudades de Absalão: porque já se tinha consolado acerca de Amnom, que era morto.

'''

xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[&#60; Capítulo Anterior] | <<v10-13-0,Topo>> | xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[Próximo Capítulo &#62;]