include::./index.adoc[]

[[v10-10-0]]
=== 2 Samuel, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-10-1]]

^<<v10-10-1,1>>^ E ACONTECEU depois disto que morreu o rei dos filhos de Amom, e seu filho Hanum reinou em seu lugar.

[[v10-10-2]]

^<<v10-10-2,2>>^ Então disse Davi: Usarei de beneficência com Hanum, filho de Naás, como seu pai usou de beneficência comigo. E enviou Davi a consolá-lo, pelo ministério de seus servos, acerca de seu pai: e vieram os servos de Davi à terra dos filhos de Amom.

[[v10-10-3]]

^<<v10-10-3,3>>^ Então disseram os príncipes dos filhos de Amom a seu senhor, Hanum: Porventura  honra Davi a teu pai aos teus olhos, porque te enviou consoladores? porventura  não te enviou Davi os seus servos para reconhecerem esta cidade, e para espiá-la, e para transtorná-la?

[[v10-10-4]]

^<<v10-10-4,4>>^ Então tomou Hanum os servos de Davi, e lhes raspou metade da barba, e lhes cortou metade dos vestidos, até às nádegas, e os despediu.

[[v10-10-5]]

^<<v10-10-5,5>>^ O que fazendo saber a Davi enviou a encontrá-los; porque estavam estes homens sobremaneira envergonhados; e disse o rei: Deixai-vos estar em Jericó, até que vos torne a crescer a barba; e então  vinde.

[[v10-10-6]]

^<<v10-10-6,6>>^ Vendo pois os filhos de Amom, que se tinham feito abomináveis para Davi, enviaram os filhos de Amom, e alugaram dos siros de Bete-Recobe e dos siros de Zobá vinte mil homens de pé, e do rei de Maaca mil homens e dos homens de Tobe doze mil homens.

[[v10-10-7]]

^<<v10-10-7,7>>^ O que ouvindo Davi, enviou a Joabe e a todo o exército dos valentes.

[[v10-10-8]]

^<<v10-10-8,8>>^ E saíram os filhos de Amom, e ordenaram a batalha à entrada da porta: mas os siros de Zobá e Recobe e os homens de Tobe e Maaca estavam  à parte no campo.

[[v10-10-9]]

^<<v10-10-9,9>>^ Vendo pois Joabe que estava preparada contra ele a frente da batalha, por diante e por detrás escolheu dentre todos os escolhidos de Israel, e formou-os em linha contra os siros.

[[v10-10-10]]

^<<v10-10-10,10>>^ E o resto do povo entregou na mão de Abisai seu irmão, o qual formou em linha contra os filhos de Amom.

[[v10-10-11]]

^<<v10-10-11,11>>^ E disse: Se os siros forem mais fortes do que eu, tu me virás em socorro; e se os filhos de Amom forem mais fortes que tu, irei a socorrer-te a ti.

[[v10-10-12]]

^<<v10-10-12,12>>^ Esforça-te, pois , e esforcemo-nos pelo nosso povo, e pelas cidades de nosso Deus: e faça o Senhor então  o que bem parecer  aos seus olhos.

[[v10-10-13]]

^<<v10-10-13,13>>^ Então se achegou Joabe, e o povo que estava  com ele, à peleja contra os siros; e fugiram de diante dele.

[[v10-10-14]]

^<<v10-10-14,14>>^ E, vendo os filhos de Amom que os siros fugiam, também eles fugiram de diante de Abisai e entraram na cidade: e voltou Joabe dos filhos de Amom e veio para Jerusalém.

[[v10-10-15]]

^<<v10-10-15,15>>^ Vendo pois os siros que tinham sido feridos diante de Israel tornaram a refazer-se.

[[v10-10-16]]

^<<v10-10-16,16>>^ E enviou Hadadezer e fez sair os siros que estavam  da outra banda do rio, e vieram a Helão: e Sobaque, chefe do exército de Hadadezer, marchava  diante deles.

[[v10-10-17]]

^<<v10-10-17,17>>^ Do que informado Davi, ajuntou a todo Israel, e passou o Jordão, e veio a Helã: e os siros se puseram em ordem contra Davi, e pelejaram com ele.

[[v10-10-18]]

^<<v10-10-18,18>>^ Porém os siros fugiram de diante de Israel, e Davi feriu dentre os siros aos homens de setecentos carros e quarenta mil homens de cavalo: também ao mesmo  Sobaque, general do exército, feriu, e morreu ali.

[[v10-10-19]]

^<<v10-10-19,19>>^ Vendo pois todos os reis, servos de Hadadezer, que haviam ficado mal diante de Israel, fizeram paz com Israel, e o serviram: e temeram os siros de socorrer mais aos filhos de Amom.

'''

xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[&#60; Capítulo Anterior] | <<v10-10-0,Topo>> | xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[Próximo Capítulo &#62;]