include::./index.adoc[]

[[v10-3-0]]
=== 2 Samuel, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-3-1]]

^<<v10-3-1,1>>^ E HOUVE uma longa guerra entre a casa de Saul e a casa de Davi: porém Davi se ia fortalecendo, mas os da casa de Saul se iam enfraquecendo.

[[v10-3-2]]

^<<v10-3-2,2>>^ E a Davi nasceram filhos em Hebrom: e foi o seu primogênito Amom, de Aquinoã a Jezreelita:

[[v10-3-3]]

^<<v10-3-3,3>>^ E seu segundo Quileabe, de Abigail, mulher de Nabal, o Carmelita; e o terceiro Absalão, filho de Maaca, filha de Talmai, rei de Gesur;

[[v10-3-4]]

^<<v10-3-4,4>>^ E o quarto Adonias, filho de Hagite; e o quinto Sefatias, filho de Abital;

[[v10-3-5]]

^<<v10-3-5,5>>^ E o sexto Jitreão, de Egla, também  mulher de Davi: estes nasceram a Davi em Hebrom.

[[v10-3-6]]

^<<v10-3-6,6>>^ E, havendo guerra entre a casa de Saul e a casa de Davi; sucedeu que Abner se esforçava na casa de Saul.

[[v10-3-7]]

^<<v10-3-7,7>>^ E tinha tido Saul uma concubina, cujo nome era Rispa, filha de Aia: e disse Isbosete  a Abner: Por que entraste à concubina de meu pai?

[[v10-3-8]]

^<<v10-3-8,8>>^ Então se irou muito Abner pelas palavras de Isbosete, e disse: Sou eu  cabeça de cão, que pertença  a Judá? ainda  hoje faço beneficência à casa de Saul, teu pai, a seus irmãos e a seus amigos, e te não entreguei nas mãos de Davi, e tu hoje buscas motivo para me arguires por causa da maldade duma  mulher.

[[v10-3-9]]

^<<v10-3-9,9>>^ Assim faça Deus a Abner, e outro tanto, que como o Senhor jurou a Davi assim lhe hei de fazer.

[[v10-3-10]]

^<<v10-3-10,10>>^ Transferindo o reino da casa de Saul, e levantando o trono de Davi sobre Israel, e sobre Judá, desde Dã até Berseba.

[[v10-3-11]]

^<<v10-3-11,11>>^ E nem ainda uma palavra podia responder a Abner: porque o temia.

[[v10-3-12]]

^<<v10-3-12,12>>^ Então ordenou Abner da sua parte mensageiros a Davi, dizendo: De quem é  a terra? E  disse: Comigo faze a tua aliança, e eis que a minha mão será contigo, para tornar a ti todo o Israel.

[[v10-3-13]]

^<<v10-3-13,13>>^ E disse Davi : Bem, eu farei contigo aliança, porém uma cousa te peço, que é: não verás a minha face se primeiro me  não trouxeres a Mical, filha de Saul, quando vieres ver a minha face.

[[v10-3-14]]

^<<v10-3-14,14>>^ Também enviou Davi mensageiros a Isbosete, filho de Saul, dizendo: Dá- me  minha mulher Mical, que eu desposei por cem prepúcios de filisteus.

[[v10-3-15]]

^<<v10-3-15,15>>^ E enviou Isbosete, e a tirou a seu marido, a Faltiel, filho de Laís.

[[v10-3-16]]

^<<v10-3-16,16>>^ E ia com ela seu marido, caminhando, e chorando detrás dela, até Baurim. Então lhe disse Abner: Vai-te agora , volta. E ele voltou.

[[v10-3-17]]

^<<v10-3-17,17>>^ E praticava Abner com os anciãos de Israel, dizendo: Muito tempo há que procuráveis que Davi reinasse sobre vós;

[[v10-3-18]]

^<<v10-3-18,18>>^ Fazei- o  pois agora, porque o Senhor falou a Davi, dizendo: Pela mão de Davi meu servo livrarei o meu povo das mãos dos filisteus e das mãos de todos os seus inimigos.

[[v10-3-19]]

^<<v10-3-19,19>>^ E falou também Abner o mesmo  aos ouvidos de Benjamim: e foi também Abner dizer aos ouvidos de Davi, em Hebrom, tudo o que era  bom aos olhos de Israel e aos olhos de toda casa de Benjamim.

[[v10-3-20]]

^<<v10-3-20,20>>^ E veio Abner a Davi, a Hebrom e vinte homens com ele: e Davi fez um banquete a Abner e aos homens que com ele vinham.

[[v10-3-21]]

^<<v10-3-21,21>>^ Então disse Abner a Davi: Eu me levantarei, e irei, e ajuntarei ao rei meu senhor todo o Israel, para fazerem aliança contigo; e tu reinarás sobre tudo o que desejar a tua alma. Assim despediu Davi a Abner, e foi-se ele em paz.

[[v10-3-22]]

^<<v10-3-22,22>>^ E eis que os servos de Davi e Joabe vieram duma sortida, e traziam consigo grande despojo; e já  Abner não estava com Davi em Hebrom, porque o tinha despedido, e se tinha ido em paz.

[[v10-3-23]]

^<<v10-3-23,23>>^ Chegando pois Joabe, e todo o exército que vinha  com ele, deram aviso a Joabe, dizendo: Abner, filho de Ner, veio ao rei; e o despediu, e foi-se em paz.

[[v10-3-24]]

^<<v10-3-24,24>>^ Então Joabe entrou ao rei, e disse: Que fizeste? eis que Abner veio ter contigo; por que pois o despediste de maneira que se fosse assim livremente?

[[v10-3-25]]

^<<v10-3-25,25>>^ Bem  conheces a Abner, filho de Ner, que te veio enganar, e saber a tua saída e a tua entrada, e entender tudo quanto fazes.

[[v10-3-26]]

^<<v10-3-26,26>>^ E Joabe, retirando-se de Davi, enviou mensageiros atrás de Abner, e o fizeram voltar desde o poço de Sira, sem que Davi o  soubesse.

[[v10-3-27]]

^<<v10-3-27,27>>^ Tornando pois Abner a Hebrom, Joabe o tomou à parte, à entrada da porta, para lhe falar em segredo, e feriu-o ali pela quinta costela , e morreu, por causa do sangue de Asael seu irmão.

[[v10-3-28]]

^<<v10-3-28,28>>^ O que Davi depois ouvindo, disse: Inocente sou  eu, e o meu reino, para com o Senhor, para sempre, do sangue de Abner, filho de Ner.

[[v10-3-29]]

^<<v10-3-29,29>>^ Fique-se sobre a cabeça de Joabe e sobre toda a casa de seu pai, e nunca da casa de Joabe falte quem tenha fluxo, nem quem seja  leproso, nem quem se atenha a bordão, nem quem caia à espada, nem quem necessite de pão.

[[v10-3-30]]

^<<v10-3-30,30>>^ Joabe pois e Abisai, seu irmão, mataram a Abner, por ter morto a Asael, seu irmão na peleja em Gibeom.

[[v10-3-31]]

^<<v10-3-31,31>>^ Disse pois Davi a Joabe, e a todo o povo que com ele estava : Rasgai os vossos vestidos; e cingi-vos de sacos e ide pranteando diante de Abner. E o rei Davi ia seguindo o féretro.

[[v10-3-32]]

^<<v10-3-32,32>>^ E, sepultando a Abner em Hebrom, o rei levantou a sua voz, e chorou junto da sepultura de Abner; e chorou todo o povo.

[[v10-3-33]]

^<<v10-3-33,33>>^ E o rei, pranteando a Abner, disse: Não  morreu Abner como morre o vilão?

[[v10-3-34]]

^<<v10-3-34,34>>^ As tuas mãos não estavam  atadas, nem os teus pés carregados de grilhões de bronze, mas  caíste como os que caem diante dos filhos da maldade! Então todo o povo chorou muito mais por ele.

[[v10-3-35]]

^<<v10-3-35,35>>^ Então todo o povo veio fazer que Davi comesse pão, sendo ainda dia, porém Davi jurou, dizendo: Assim Deus me faça, e outro tanto, se, antes que o sol se ponha, eu provar pão ou alguma coisa.

[[v10-3-36]]

^<<v10-3-36,36>>^ O que todo o povo entendendo, pareceu bem aos seus olhos, assim como tudo quanto o rei fez pareceu bem aos olhos de todo o povo.

[[v10-3-37]]

^<<v10-3-37,37>>^ E todo o povo e todo o Israel entenderam naquele mesmo dia que não procedera do rei que matassem a Abner, filho de Ner.

[[v10-3-38]]

^<<v10-3-38,38>>^ Então disse o rei aos seus servos: Não sabeis que hoje caiu em Israel um príncipe e um grande?

[[v10-3-39]]

^<<v10-3-39,39>>^ Que eu ainda sou  tenro, ainda que  ungido rei; estes homens, filhos de Zeruia, são  mais duros do que eu: o Senhor pagará ao malfeitor, conforme a sua maldade.

'''

xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[&#60; Capítulo Anterior] | <<v10-3-0,Topo>> | xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[Próximo Capítulo &#62;]