include::./index.adoc[]

[[v10-7-0]]
=== 2 Samuel, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-7-1]]

^<<v10-7-1,1>>^ E SUCEDEU que, estando o rei Davi  em sua casa, e que  o Senhor lhe tinha dado descanso de todos os seus inimigos em redor:

[[v10-7-2]]

^<<v10-7-2,2>>^ Disse o rei ao profeta Natã: Ora olha, eu moro em casa de cedros e a arca de Deus mora dentro de cortinas.

[[v10-7-3]]

^<<v10-7-3,3>>^ E disse Natã ao rei: Vai, e  faze tudo quanto está  no teu coração; porque o Senhor é  contigo.

[[v10-7-4]]

^<<v10-7-4,4>>^ Porém sucedeu naquela mesma noite, que a palavra do Senhor veio a Natã dizendo:

[[v10-7-5]]

^<<v10-7-5,5>>^ Vai e dize a meu servo, a Davi: Assim diz o Senhor: Edificar-me-ias tu casa para minha habitação?

[[v10-7-6]]

^<<v10-7-6,6>>^ Porque em casa nenhuma habitei desde o dia  em que fiz subir os filhos de Israel do Egito até ao dia de  hoje: mas andei em tenda e em tabernáculo.

[[v10-7-7]]

^<<v10-7-7,7>>^ E em todo o lugar  em que andei com todos os filhos de Israel, falei porventura alguma  palavra com qualquer das tribos de Israel, a quem mandei apascentar o meu povo de Israel, dizendo: Por que me não edificais uma  casa de cedros?

[[v10-7-8]]

^<<v10-7-8,8>>^ Agora, pois, assim dirás ao meu servo, a Davi: Assim diz o Senhor dos exércitos: Eu te tomei da malhada, de detrás das ovelhas, para que fosses o chefe sobre o meu povo, sobre Israel.

[[v10-7-9]]

^<<v10-7-9,9>>^ E fui contigo, por onde quer que foste, e destruí a teus inimigos diante de ti: e fiz para ti um grande nome, como o nome dos grandes que há  na terra.

[[v10-7-10]]

^<<v10-7-10,10>>^ E prepararei lugar para o meu povo, para Israel, e o plantarei, para que habite no seu lugar, e não mais seja movido e nunca mais os filhos da perversidade o aflijam como dantes,

[[v10-7-11]]

^<<v10-7-11,11>>^ E desde o dia em que mandei que houvesse  juízes sobre o meu povo Israel: a ti porém te dei descanso de todos os teus inimigos: também o Senhor te faz saber que o Senhor te fará casa.

[[v10-7-12]]

^<<v10-7-12,12>>^ Quando teus dias forem completos, e vieres a dormir com teus pais, então farei levantar depois de ti a tua semente, que sair das tuas entranhas, e estabelecerei o seu reino.

[[v10-7-13]]

^<<v10-7-13,13>>^ Este edificará uma casa ao meu nome, e confirmarei o trono do seu reino para sempre.

[[v10-7-14]]

^<<v10-7-14,14>>^ Eu lhe serei por pai, e ele me será por filho: e, se vier a transgredir, castigá-lo-ei com vara de homens, e com açoites de filhos de homens.

[[v10-7-15]]

^<<v10-7-15,15>>^ Mas a minha benignidade se não apartará dele; como a  tirei de Saul, a quem tirei de diante de ti.

[[v10-7-16]]

^<<v10-7-16,16>>^ Porém a tua casa e o teu reino serão firmados para sempre diante de ti: teu trono será firme para sempre.

[[v10-7-17]]

^<<v10-7-17,17>>^ Conforme a todas estas palavras, e conforme a toda esta visão, assim falou Natã a Davi.

[[v10-7-18]]

^<<v10-7-18,18>>^ Então entrou o rei Davi, e ficou perante o Senhor, e disse: Quem sou  eu, Senhor Jeová , e qual é a minha casa, que me trouxeste até aqui?

[[v10-7-19]]

^<<v10-7-19,19>>^ E ainda foi isto pouco aos teus olhos, Senhor Jeová , senão que também falaste da casa de teu servo para tempos distantes: é isto o costume dos homens, ó Senhor Jeová ?

[[v10-7-20]]

^<<v10-7-20,20>>^ E que mais te falará ainda Davi? pois tu conheces bem  a teu servo, ó Senhor Jeová .

[[v10-7-21]]

^<<v10-7-21,21>>^ Por causa da tua palavra, e segundo o teu coração, fizeste toda esta grandeza: fazendo-a saber a teu servo.

[[v10-7-22]]

^<<v10-7-22,22>>^ Portanto, grandioso és, ó Senhor Jeová , porque não há  semelhante a ti, e não há outro  Deus senão tu só, segundo tudo o que temos ouvido com os nossos ouvidos.

[[v10-7-23]]

^<<v10-7-23,23>>^ E quem há  como o teu povo, como Israel, gente única na terra? a quem Deus foi resgatar para seu povo; e a fazer-se um nome, e a fazer-vos estas grandes e terríveis cousas, para a tua terra, diante do teu povo, que tu resgataste do Egito desterrando  as nações e a seus deuses.

[[v10-7-24]]

^<<v10-7-24,24>>^ E confirmaste a teu povo Israel por teu povo para sempre, e tu, Senhor, te fizeste o seu Deus.

[[v10-7-25]]

^<<v10-7-25,25>>^ Agora, pois, ó Senhor Jeová , esta palavra que falaste acerca de teu servo e acerca da sua casa, confirma-a para sempre, e faze como tens falado.

[[v10-7-26]]

^<<v10-7-26,26>>^ E engrandeça-se o teu nome para sempre, para que se diga: O Senhor dos exércitos é  Deus sobre Israel; e a casa de teu servo será confirmada diante de ti.

[[v10-7-27]]

^<<v10-7-27,27>>^ Pois tu, Senhor dos exércitos, Deus de Israel, revelaste aos ouvidos de teu servo, dizendo: Edificar-te-ei casa. Portanto o teu servo achou no seu coração o fazer-te esta oração.

[[v10-7-28]]

^<<v10-7-28,28>>^ Agora, pois, Senhor Jeová , tu és o mesmo  Deus, e as tuas palavras são verdade, e tens falado a teu servo este bem.

[[v10-7-29]]

^<<v10-7-29,29>>^ Sê pois agora servido de abençoar a casa de teu servo, para permanecer para sempre diante de ti, pois tu, ó Senhor Jeová , o disseste; e com a tua bênção será para sempre bendita a casa de teu servo.

'''

xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[&#60; Capítulo Anterior] | <<v10-7-0,Topo>> | xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[Próximo Capítulo &#62;]