include::./index.adoc[]

[[v10-14-0]]
=== 2 Samuel, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v10-14-1]]

^<<v10-14-1,1>>^ CONHECENDO pois Joabe, filho de Zeruia que o coração do rei era inclinado para Absalão,

[[v10-14-2]]

^<<v10-14-2,2>>^ Enviou Joabe a Técoa, e tomou de lá uma mulher sábia, e disse-lhe: Ora finge que estás de nojo; veste vestidos de luto, e não te unjas com óleo, e sejas como uma mulher que há já  muitos dias está de nojo por algum  morto.

[[v10-14-3]]

^<<v10-14-3,3>>^ E entra ao rei, e fala-lhe conforme a esta palavra. E Joabe lhe pôs as palavras na boca.

[[v10-14-4]]

^<<v10-14-4,4>>^ E a mulher tecoíta falou ao rei, e deitando-se com o rosto em terra, se prostrou e disse: Salva-me, ó rei.

[[v10-14-5]]

^<<v10-14-5,5>>^ E disse-lhe o rei: Que tens? E disse ela: Na verdade que sou uma mulher viúva, e morreu meu marido.

[[v10-14-6]]

^<<v10-14-6,6>>^ Tinha pois a tua serva dois filhos, e ambos estes brigaram no campo, e não houve  quem os apartasse: assim um feriu ao outro, e o matou.

[[v10-14-7]]

^<<v10-14-7,7>>^ E eis que toda a linhagem se levantou contra a tua serva, e disseram: Dá- nos  aquele que feriu a seu irmão para que o matemos, por causa da vida de seu irmão, a quem matou, e para que destruamos também ao herdeiro. Assim apagarão a brasa que me ficou, de sorte que não deixam a meu marido nome, nem resto sobre a terra.

[[v10-14-8]]

^<<v10-14-8,8>>^ E disse o rei à mulher: Vai para tua casa: e eu mandarei ordem acerca de ti.

[[v10-14-9]]

^<<v10-14-9,9>>^ E disse a mulher tecoíta ao rei: A injustiça, rei meu senhor, venha  sobre mim e sobre a casa de meu pai: e o rei e o seu trono fique inculpável.

[[v10-14-10]]

^<<v10-14-10,10>>^ E disse o rei: Quem falar contra ti, traze-mo a mim; e nunca mais te tocará.

[[v10-14-11]]

^<<v10-14-11,11>>^ E disse ela: Ora lembre-se o rei do Senhor seu Deus, para que os vingadores do sangue se não multipliquem a deitar-nos a perder, e não destruam a meu filho. Então disse ele: Vive o Senhor, que não há de cair no chão nem um dos cabelos de teu filho.

[[v10-14-12]]

^<<v10-14-12,12>>^ Então disse a mulher: Peço- te que  a tua serva fale uma palavra ao rei meu senhor. E disse ele: Fala.

[[v10-14-13]]

^<<v10-14-13,13>>^ E disse a mulher: Por que pois pensaste tu uma tal cousa contra o povo de Deus? Porque, falando o rei tal palavra, fica como culpado; visto que o rei não torna a trazer o seu desterrado.

[[v10-14-14]]

^<<v10-14-14,14>>^ Porque certamente morreremos, e seremos  como águas derramadas na terra, que não se ajuntam mais : Deus pois lhe não tirará a vida mas ideará pensamentos, para que se não desterre dele o seu desterrado.

[[v10-14-15]]

^<<v10-14-15,15>>^ E se eu agora vim falar esta palavra ao rei, meu senhor, é  porque o povo me atemorizou: dizia pois a tua serva: Falarei pois ao rei; porventura fará o rei segundo  a palavra da sua serva.

[[v10-14-16]]

^<<v10-14-16,16>>^ Porque o rei ouvirá, para livrar a sua serva da mão do homem que intenta  destruir juntamente a mim e a meu filho da herança de Deus.

[[v10-14-17]]

^<<v10-14-17,17>>^ Dizia mais a tua serva: Seja agora a palavra do rei meu senhor para descanso: porque como um anjo de Deus, assim é o rei, meu senhor, para ouvir o bem e o mal; e o Senhor teu Deus será contigo.

[[v10-14-18]]

^<<v10-14-18,18>>^ Então respondeu o rei, e disse à mulher: Peço-te que não me encubras o que eu te perguntar. E disse a mulher: Ora fale o rei, meu senhor.

[[v10-14-19]]

^<<v10-14-19,19>>^ E disse o rei: Não é verdade  que a mão de Joabe anda contigo em tudo isto? E respondeu a mulher, e disse: Vive a tua alma, ó rei meu senhor, que ninguém se poderá desviar, nem para a direita nem para a esquerda, de tudo quanto o rei, meu senhor, tem dito; porque Joabe, teu servo, é quem me deu ordem, e foi  ele que pôs na boca da tua serva todas estas palavras:

[[v10-14-20]]

^<<v10-14-20,20>>^ Que eu  virasse a forma deste negócio; Joabe, teu servo, fez isto; porém sábio é meu senhor, conforme à sabedoria dum anjo de Deus, para entender tudo o que há  na terra.

[[v10-14-21]]

^<<v10-14-21,21>>^ Então o rei disse a Joabe: Eis que fiz isto: vai pois, e  torna a trazer o mancebo Absalão.

[[v10-14-22]]

^<<v10-14-22,22>>^ Então Joabe se prostrou sobre o seu rosto em terra, e se inclinou, e o agradeceu ao rei; e disse Joabe: Hoje conheceu o teu servo que achei graça aos teus olhos, ó rei meu senhor, porque o rei fez segundo  a palavra do teu servo.

[[v10-14-23]]

^<<v10-14-23,23>>^ Levantou-se pois Joabe, e foi a Gesur, e trouxe Absalão a Jerusalém.

[[v10-14-24]]

^<<v10-14-24,24>>^ E disse o rei: Torne para a sua casa, e não veja a minha face. Tornou pois Absalão para a sua casa e não viu a face do rei.

[[v10-14-25]]

^<<v10-14-25,25>>^ Não havia porém em todo o Israel homem tão belo e  tão aprazível como Absalão; desde a planta do pé até à cabeça não havia nele defeito algum.

[[v10-14-26]]

^<<v10-14-26,26>>^ E, quando tosquiava a sua cabeça (e sucedia que no fim de cada ano a tosquiava, porquanto muito lhe pesava, e por isso  a tosquiava), pesava o cabelo na sua cabeça duzentos siclos, segundo o peso real.

[[v10-14-27]]

^<<v10-14-27,27>>^ Também nasceram a Absalão três filhos e uma filha, cujo nome era  Tamar; e  esta era mulher formosa à vista.

[[v10-14-28]]

^<<v10-14-28,28>>^ Assim ficou Absalão dois anos inteiros em Jerusalém, e não viu a face do rei.

[[v10-14-29]]

^<<v10-14-29,29>>^ Mandou pois Absalão chamar  a Joabe, para o enviar ao rei; porém não quis vir a ele; e enviou ainda segunda vez, e, contudo , não quis vir.

[[v10-14-30]]

^<<v10-14-30,30>>^ Então disse aos seus servos: Vedes ali  o pedaço de campo de Joabe pegado ao meu, e tem cevada nele; ide, e ponde-lhe fogo. E os servos de Absalão puseram fogo ao pedaço de campo.

[[v10-14-31]]

^<<v10-14-31,31>>^ Então Joabe se levantou e veio a Absalão, em casa, e disse-lhe: Por que puseram os teus servos fogo ao pedaço de campo que é meu?

[[v10-14-32]]

^<<v10-14-32,32>>^ E disse Absalão a Joabe: Eis que enviei a ti, dizendo: Vem cá, para que te envie ao rei, a dizer-lhe: Para que vim de Gesur? Melhor me fora  estar ainda lá. Agora, pois, veja eu a face do rei: e, se há ainda  em mim alguma culpa, que me mate.

[[v10-14-33]]

^<<v10-14-33,33>>^ Então entrou Joabe ao rei, e assim  lho disse. Então chamou a Absalão, e ele entrou ao rei, e se inclinou sobre o seu rosto em terra diante do rei: e o rei beijou a Absalão.

'''

xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[&#60; Capítulo Anterior] | <<v10-14-0,Topo>> | xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[Próximo Capítulo &#62;]