include::./index.adoc[]

[[v30-1-0]]
=== Amós, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v30-1-1]]

^<<v30-1-1,1>>^ AS palavras de Amós, que estava entre os pastores de Técoa, o que ele viu a respeito de Israel, nos dias de Uzias, rei de Judá, e nos dias de Jeroboão, filho de Joás, rei de Israel, dois anos antes do terremoto.

[[v30-1-2]]

^<<v30-1-2,2>>^ E disse: O Senhor bramará de Sião e de Jerusalém dará a sua voz; nas habitações dos pastores haverá pranto, e secar-se-á o cume do Carmelo.

[[v30-1-3]]

^<<v30-1-3,3>>^ Assim diz o Senhor: Por três transgressões de Damasco, e por quatro, não retirarei o castigo, porque trilharam a Gileade com trilhos de ferro.

[[v30-1-4]]

^<<v30-1-4,4>>^ Por isso porei fogo à casa de Azael, e ele consumirá os palácios de Benadade.

[[v30-1-5]]

^<<v30-1-5,5>>^ E quebrarei o ferrolho de Damasco, e exterminarei o morador de Biqueate-Áven, e ao que tem o cetro de Bete-Éden; e o povo da Síria será levado em cativeiro a Quir, diz o Senhor.

[[v30-1-6]]

^<<v30-1-6,6>>^ Assim diz o Senhor: Por três transgressões de Gaza, e por quatro, não retirarei o castigo, porque levaram em cativeiro todos os cativos para os  entregarem a Edom.

[[v30-1-7]]

^<<v30-1-7,7>>^ Por isso porei fogo ao muro de Gaza, e ele consumirá os seus palácios.

[[v30-1-8]]

^<<v30-1-8,8>>^ E exterminarei o morador de Asdode, e o que tem o cetro de Ascalom, e tornarei a minha mão contra Ecrom; e o resto dos filisteus perecerá, diz o Senhor Jeová .

[[v30-1-9]]

^<<v30-1-9,9>>^ Assim diz o Senhor: Por três transgressões de Tiro, e por quatro, não retirarei o castigo, porque entregaram todos os cativos a Edom, e não se lembraram da aliança dos irmãos.

[[v30-1-10]]

^<<v30-1-10,10>>^ Por isso porei fogo ao muro de Tiro, e ele consumirá os seus palácios.

[[v30-1-11]]

^<<v30-1-11,11>>^ Assim diz o Senhor: Por três transgressões de Edom, e por quatro, não retirarei o castigo, porque perseguiu a seu irmão à espada, e baniu toda a misericórdia; e a sua ira despedaça eternamente, e retém a sua indignação para sempre.

[[v30-1-12]]

^<<v30-1-12,12>>^ Por isso porei fogo a Temã, e ele consumirá os palácios de Bozra.

[[v30-1-13]]

^<<v30-1-13,13>>^ Assim diz o Senhor: Por três transgressões dos filhos de Amom, e por quatro, não retirarei o castigo, porque fenderam as grávidas de Gileade, para dilatarem os seus termos.

[[v30-1-14]]

^<<v30-1-14,14>>^ Por isso porei fogo ao muro de Rabá, e ele consumirá os seus palácios, com alarido no dia da batalha, com tempestade no dia da tormenta.

[[v30-1-15]]

^<<v30-1-15,15>>^ E o seu rei irá para o cativeiro, ele e os seus príncipes juntamente, diz o Senhor.

'''

xref:029-joel/029-joel-003.adoc#v29-3-0[&#60; Capítulo Anterior] | <<v30-1-0,Topo>> | xref:030-amos/030-amos-002.adoc#v30-2-0[Próximo Capítulo &#62;]