include::./index.adoc[]

[[v30-2-0]]
=== Amós, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v30-2-1]]

^<<v30-2-1,1>>^ ASSIM diz o Senhor: Por três transgressões de Moabe, e por quatro, não retirarei o castigo, porque queimou os ossos do rei de Edom, até os reduzir a  cal.

[[v30-2-2]]

^<<v30-2-2,2>>^ Por isso porei fogo a Moabe, e ele consumirá os palácios de Queriote; e Moabe morrerá com grande estrondo, com alarido, com som de buzina.

[[v30-2-3]]

^<<v30-2-3,3>>^ E tirarei o juiz do meio dele, e a todos os seus príncipes com ele matarei, diz o Senhor.

[[v30-2-4]]

^<<v30-2-4,4>>^ Assim diz o Senhor: Por três transgressões de Judá, e por quatro, não retirarei o castigo, porque rejeitaram a lei do Senhor, e não guardaram os seus estatutos, antes se deixaram enganar por suas próprias mentiras, após as quais andaram seus pais.

[[v30-2-5]]

^<<v30-2-5,5>>^ Por isso porei fogo a Judá, e ele consumirá os palácios de Jerusalém.

[[v30-2-6]]

^<<v30-2-6,6>>^ Assim diz o Senhor: Por três transgressões de Israel, e por quatro, não retirarei o castigo, porque vendem o justo por dinheiro, e o necessitado por um par de sapatos;

[[v30-2-7]]

^<<v30-2-7,7>>^ Suspirando pelo pó da terra sobre a cabeça dos pobres, eles pervertem o caminho dos mansos; e um homem e seu pai entram à mesma  moça, para profanarem o  meu santo nome.

[[v30-2-8]]

^<<v30-2-8,8>>^ E se deitam junto a qualquer altar sobre roupas empenhadas, e na  casa de seus deuses bebem o vinho dos que tinham multado.

[[v30-2-9]]

^<<v30-2-9,9>>^ Não obstante eu ter destruído o amorreu diante deles, a altura do qual era como a altura dos cedros, e cuja força era como a dos carvalhos; mas destruí o seu fruto por cima, e as suas raízes por baixo.

[[v30-2-10]]

^<<v30-2-10,10>>^ Também vos fiz subir da terra do Egito, e quarenta anos vos guiei no deserto, para que possuísseis a terra do amorreu.

[[v30-2-11]]

^<<v30-2-11,11>>^ E dentre vossos filhos levantei profetas, e dentre os vossos mancebos nazireus. Não é  isto assim, filhos de Israel? diz o Senhor.

[[v30-2-12]]

^<<v30-2-12,12>>^ Mas vós aos nazireus destes vinho a beber, e aos profetas ordenastes, dizendo: Não profetizeis.

[[v30-2-13]]

^<<v30-2-13,13>>^ Eis que eu vos apertarei no vosso lugar como se aperta um carro cheio de manolhos.

[[v30-2-14]]

^<<v30-2-14,14>>^ Assim que de nada valerá a fuga ao ágil; nem o forte corroborará a sua força, nem o valente livrará a sua vida.

[[v30-2-15]]

^<<v30-2-15,15>>^ E não ficará em pé o que leva o arco, nem o ligeiro de pés se livrará, nem tão pouco o que vai montado a cavalo livrará a sua alma.

[[v30-2-16]]

^<<v30-2-16,16>>^ E o mais animoso entre os valentes fugirá nu naquele dia, disse o Senhor.

'''

xref:030-amos/030-amos-001.adoc#v30-1-0[&#60; Capítulo Anterior] | <<v30-2-0,Topo>> | xref:030-amos/030-amos-003.adoc#v30-3-0[Próximo Capítulo &#62;]