include::./index.adoc[]

[[v66-12-0]]
=== Apocalipse, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-12-1]]

^<<v66-12-1,1>>^ E VIU-SE um grande sinal no céu: uma mulher vestida do sol, tendo a lua debaixo dos seus pés, e uma coroa de doze estrelas sobre a sua cabeça.

[[v66-12-2]]

^<<v66-12-2,2>>^ E estava grávida, e com dores de parto, e gritava com ânsias de dar à luz.

[[v66-12-3]]

^<<v66-12-3,3>>^ E viu-se outro sinal no céu; e eis que era um grande dragão vermelho, que tinha sete cabeças e dez chifres, e sobre as suas cabeças sete diademas.

[[v66-12-4]]

^<<v66-12-4,4>>^ E a sua cauda levou após si a terça parte das estrelas do céu, e lançou-as sobre a terra; e o dragão parou diante da mulher que havia de dar à luz, para que, dando ela à luz, lhe tragasse o filho.

[[v66-12-5]]

^<<v66-12-5,5>>^ E deu à luz um filho, um varão que há de reger todas as nações com vara de ferro; e o seu filho foi arrebatado para Deus e para  o seu trono.

[[v66-12-6]]

^<<v66-12-6,6>>^ E a mulher fugiu para o deserto, onde já  tinha lugar preparado por Deus para que ali fosse alimentada durante mil duzentos e sessenta dias.

[[v66-12-7]]

^<<v66-12-7,7>>^ E houve batalha no céu: Miguel e os seus anjos batalhavam contra o dragão, e batalhava o dragão e os seus anjos;

[[v66-12-8]]

^<<v66-12-8,8>>^ Mas não prevaleceram, nem mais o seu lugar se achou nos céus.

[[v66-12-9]]

^<<v66-12-9,9>>^ E foi precipitado o grande dragão, a antiga serpente, chamada o Diabo, e Satanás, que engana todo o mundo; ele foi precipitado na terra, e os seus anjos foram lançados com ele.

[[v66-12-10]]

^<<v66-12-10,10>>^ E ouvi uma grande voz no céu, que dizia: Agora chegada está a salvação, e a força, e o reino do nosso Deus, e o poder do seu Cristo; porque já o acusador de nossos irmãos é derribado, o qual diante do nosso Deus os acusava de dia e de noite.

[[v66-12-11]]

^<<v66-12-11,11>>^ E eles o venceram pelo sangue do Cordeiro e pela palavra do seu testemunho; e não amaram as suas vidas até à morte.

[[v66-12-12]]

^<<v66-12-12,12>>^ Pelo que alegrai-vos, ó céus, e vós que neles habitais. Ai dos que habitam na terra e no mar; porque o diabo desceu a vós, e tem grande ira, sabendo que já  tem pouco tempo.

[[v66-12-13]]

^<<v66-12-13,13>>^ E, quando o dragão viu que fora lançado na terra, perseguiu a mulher que dera à luz o varão.

[[v66-12-14]]

^<<v66-12-14,14>>^ E foram dadas à mulher duas asas de grande águia, para que voasse para o deserto, ao seu lugar, onde é sustentada por um tempo, e tempos, e metade de um tempo, fora da vista da serpente.

[[v66-12-15]]

^<<v66-12-15,15>>^ E a serpente lançou da sua boca, atrás da mulher água como um rio, para que pela corrente a fizesse arrebatar.

[[v66-12-16]]

^<<v66-12-16,16>>^ E a terra ajudou a mulher; e a terra abriu a sua boca e tragou o rio que o dragão lançara da sua boca.

[[v66-12-17]]

^<<v66-12-17,17>>^ E o dragão irou-se contra a mulher, e foi fazer guerra ao resto da sua semente, os que guardam os mandamentos de Deus, e têm o testemunho de Jesus Cristo.

'''

xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[Próximo Capítulo &#62;]