include::./index.adoc[]

[[v66-20-0]]
=== Apocalipse, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-20-1]]

^<<v66-20-1,1>>^ E VI descer do céu um anjo, que tinha a chave do abismo, e uma grande cadeia na sua mão.

[[v66-20-2]]

^<<v66-20-2,2>>^ Ele prendeu o dragão, a antiga serpente, que é o Diabo e Satanás, e amarrou-o por mil anos.

[[v66-20-3]]

^<<v66-20-3,3>>^ E lançou-o no abismo, e ali o encerrou, e pôs selo sobre ele, para que mais não engane as nações, até que os mil anos se acabem. E depois importa que seja solto, por um pouco de tempo.

[[v66-20-4]]

^<<v66-20-4,4>>^ E vi tronos; e assentaram-se sobre eles, e foi-lhes dado o poder de julgar; e vi as almas daqueles que foram degolados pelo testemunho de Jesus, e pela palavra de Deus e que não adoraram a besta, nem a sua imagem, e não receberam o sinal em suas testas nem em suas mãos; e viveram, e reinaram com Cristo durante mil anos.

[[v66-20-5]]

^<<v66-20-5,5>>^ Mas os outros mortos não reviveram, até que os mil anos se acabaram. Esta é  a primeira ressurreição.

[[v66-20-6]]

^<<v66-20-6,6>>^ Bem-aventurado e santo aquele que tem parte na primeira ressurreição: sobre estes não tem poder a segunda morte; mas serão sacerdotes de Deus e de Cristo, e reinarão com ele mil anos.

[[v66-20-7]]

^<<v66-20-7,7>>^ E, acabando-se os mil anos, Satanás será solto da sua prisão,

[[v66-20-8]]

^<<v66-20-8,8>>^ E sairá a enganar as nações que estão sobre os quatro cantos da terra, Gogue e Magogue, cujo número é  como a areia do mar, para as ajuntar em batalha.

[[v66-20-9]]

^<<v66-20-9,9>>^ E subiram sobre a largura da terra, e cercaram o arraial dos santos e a cidade amada; mas desceu fogo do céu, e os devorou.

[[v66-20-10]]

^<<v66-20-10,10>>^ E o diabo, que os enganava, foi lançado no lago de fogo e enxofre, onde está a besta e o falso profeta; e de dia e de noite serão atormentados para todo o sempre.

[[v66-20-11]]

^<<v66-20-11,11>>^ E vi um grande trono branco, e o que estava assentado sobre ele, de cuja presença fugiu a terra e o céu; e não se achou lugar para eles.

[[v66-20-12]]

^<<v66-20-12,12>>^ E vi os mortos, grandes e pequenos, que estavam diante do trono, e abriram-se os livros; e abriu-se outro livro, que é o da vida: e os mortos foram julgados pelas coisas que estavam escritas nos livros, segundo as suas obras.

[[v66-20-13]]

^<<v66-20-13,13>>^ E deu o mar os mortos que nele havia; e a morte e o inferno deram os mortos que neles havia; e foram julgados cada um segundo as suas obras.

[[v66-20-14]]

^<<v66-20-14,14>>^ E a morte e o inferno foram lançados no lago de fogo: esta é a segunda morte.

[[v66-20-15]]

^<<v66-20-15,15>>^ E aquele que não foi achado escrito no livro da vida foi lançado no lago de fogo.

'''

xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[&#60; Capítulo Anterior] | <<v66-20-0,Topo>> | xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[Próximo Capítulo &#62;]