include::./index.adoc[]

[[v66-7-0]]
=== Apocalipse, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-7-1]]

^<<v66-7-1,1>>^ E DEPOIS destas coisas vi quatro anjos que estavam sobre os quatro cantos da terra, retendo os quatro ventos da terra, para que nenhum vento soprasse sobre a terra, nem sobre o mar, nem contra árvore alguma.

[[v66-7-2]]

^<<v66-7-2,2>>^ E vi outro anjo subir da banda do sol nascente, e que tinha o selo do Deus vivo; e clamou com grande voz aos quatro anjos, a quem fora dado o poder de danificar a terra e o mar,

[[v66-7-3]]

^<<v66-7-3,3>>^ Dizendo: Não danifiqueis a terra, nem o mar, nem as árvores, até que hajamos assinalado nas suas testas os servos do nosso Deus.

[[v66-7-4]]

^<<v66-7-4,4>>^ E ouvi o número dos assinalados, e eram cento e quarenta e quatro mil assinalados, de todas as tribos dos filhos de Israel.

[[v66-7-5]]

^<<v66-7-5,5>>^ Da tribo de Judá, havia doze mil assinalados: da tribo de Rubem, doze mil: da tribo de Gade, doze mil:

[[v66-7-6]]

^<<v66-7-6,6>>^ Da tribo de Aser, doze mil: da tribo de Naftali, doze mil: da tribo de Manassés, doze mil:

[[v66-7-7]]

^<<v66-7-7,7>>^ Da tribo de Simeão, doze mil: da tribo de Levi, doze mil: da tribo de Issacar, doze mil:

[[v66-7-8]]

^<<v66-7-8,8>>^ Da tribo de Zabulom, doze mil: da tribo de José, doze mil: da tribo de Benjamim, doze mil.

[[v66-7-9]]

^<<v66-7-9,9>>^ Depois destas coisas olhei, e eis aqui uma multidão, a qual ninguém podia contar, de todas as nações, e tribos, e povos, e línguas, que estavam diante do trono, e perante o Cordeiro, trajando vestidos brancos e com palmas nas suas mãos:

[[v66-7-10]]

^<<v66-7-10,10>>^ E clamavam com grande voz, dizendo: Salvação ao nosso Deus, que está assentado no trono, e ao Cordeiro.

[[v66-7-11]]

^<<v66-7-11,11>>^ E todos os anjos estavam ao redor do trono, e dos anciãos, e dos quatro animais: e prostraram-se diante do trono sobre seus rostos, e adoraram a Deus,

[[v66-7-12]]

^<<v66-7-12,12>>^ Dizendo: Amém. Louvor, e glória, e sabedoria, e ação de graças, e honra, e poder, e força ao nosso Deus, para todo o sempre. Amém.

[[v66-7-13]]

^<<v66-7-13,13>>^ E um dos anciãos me falou, dizendo: Estes que estão vestidos de vestidos brancos, quem são, e donde vieram?

[[v66-7-14]]

^<<v66-7-14,14>>^ E eu disse-lhe: Senhor, tu sabes. E ele disse-me: Estes são os que vieram de grande tribulação, e lavaram os seus vestidos e os branquearam no sangue do Cordeiro.

[[v66-7-15]]

^<<v66-7-15,15>>^ Por isso estão diante do trono de Deus, e o servem de dia e de noite no seu templo; e aquele que está assentado sobre o trono os cobrirá com a sua sombra.

[[v66-7-16]]

^<<v66-7-16,16>>^ Nunca mais terão fome, nunca mais terão sede; nem sol nem calma alguma cairá sobre eles.

[[v66-7-17]]

^<<v66-7-17,17>>^ Porque o Cordeiro que está no meio do trono os apascentará, e lhes servirá de guia para as fontes das águas da vida; e Deus limpará de seus olhos toda a lágrima.

'''

xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[&#60; Capítulo Anterior] | <<v66-7-0,Topo>> | xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[Próximo Capítulo &#62;]