include::./index.adoc[]

[[v66-2-0]]
=== Apocalipse, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-2-1]]

^<<v66-2-1,1>>^ ESCREVE ao anjo da igreja que está em Éfeso: Isto diz aquele que tem na sua destra as sete estrelas, que anda no meio dos sete castiçais de ouro:

[[v66-2-2]]

^<<v66-2-2,2>>^ Eu sei as tuas obras, e o teu trabalho, e a tua paciência, e que não podes sofrer os maus; e puseste à prova os que dizem ser apóstolos e o não são, e tu os achaste mentirosos.

[[v66-2-3]]

^<<v66-2-3,3>>^ E sofreste, e tens paciência; e trabalhaste pelo meu nome, e não te cansaste.

[[v66-2-4]]

^<<v66-2-4,4>>^ Tenho, porém, contra ti que deixaste a tua primeira caridade.

[[v66-2-5]]

^<<v66-2-5,5>>^ Lembra-te pois donde caíste, e arrepende-te, e pratica as primeiras obras; quando não, brevemente a ti virei, e tirarei do seu lugar o teu castiçal, se não te arrependeres.

[[v66-2-6]]

^<<v66-2-6,6>>^ Tens, porém, isto: que aborreces as obras dos nicolaítas, as quais eu também aborreço.

[[v66-2-7]]

^<<v66-2-7,7>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas: Ao que vencer, dar-lhe-ei a comer da árvore da vida, que está no meio do paraíso de Deus.

[[v66-2-8]]

^<<v66-2-8,8>>^ E ao anjo da igreja que está em Smirna, escreve: Isto diz o primeiro e o último, que foi morto, e reviveu:

[[v66-2-9]]

^<<v66-2-9,9>>^ Eu sei as tuas obras, e tribulação, e pobreza ( mas tu és rico), e a blasfêmia dos que se dizem judeus, e não o são, mas são a sinagoga de Satanás.

[[v66-2-10]]

^<<v66-2-10,10>>^ Nada temas das coisas  que hás de padecer. Eis que o diabo lançará alguns  de vós na prisão, para que sejais tentados; e tereis uma tribulação de dez dias. Sê fiel até a morte, e dar-te-ei a coroa da vida.

[[v66-2-11]]

^<<v66-2-11,11>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas: O que vencer não receberá o dano da segunda morte.

[[v66-2-12]]

^<<v66-2-12,12>>^ E ao anjo da igreja que está em Pérgamo escreve: Isto diz aquele que tem a espada aguda de dois fios:

[[v66-2-13]]

^<<v66-2-13,13>>^ Eu sei as tuas obras, e onde habitas, que é  onde está o trono de Satanás; e reténs o meu nome, e não negaste a minha fé, ainda nos dias de Antipas, minha fiel testemunha, o qual foi morto entre vós, onde Satanás habita.

[[v66-2-14]]

^<<v66-2-14,14>>^ Mas umas poucas de coisas tenho contra ti: porque tens lá os que seguem a doutrina de Balaão, o qual ensinava Balaque a lançar tropeços diante dos filhos de Israel, para que comessem dos sacrifícios da idolatria, e se prostituíssem.

[[v66-2-15]]

^<<v66-2-15,15>>^ Assim tens também os que seguem a doutrina dos nicolaítas: o que eu aborreço.

[[v66-2-16]]

^<<v66-2-16,16>>^ Arrepende-te, pois, quando não em breve virei a ti, e contra eles batalharei com a espada da minha boca.

[[v66-2-17]]

^<<v66-2-17,17>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas: Ao que vencer darei eu a comer do maná escondido, e dar-lhe-ei uma pedra branca, e na pedra um novo nome escrito, o qual ninguém conhece senão aquele que o recebe.

[[v66-2-18]]

^<<v66-2-18,18>>^ E ao anjo da igreja de Tiatira escreve: Isto diz o Filho de Deus, que tem seus olhos como chama de fogo, e os pés semelhantes ao latão reluzente:

[[v66-2-19]]

^<<v66-2-19,19>>^ Eu conheço as tuas obras, e a tua caridade, e o teu serviço, e a tua fé, e a tua paciência, e que as tuas últimas obras são  mais do que as primeiras.

[[v66-2-20]]

^<<v66-2-20,20>>^ Mas tenho contra ti que toleras Jezabel, mulher que se diz profetisa, ensinar e enganar os meus servos, para que se prostituam e comam dos sacrifícios da idolatria.

[[v66-2-21]]

^<<v66-2-21,21>>^ E dei-lhe tempo para que se arrependesse da sua prostituição; e não se arrependeu.

[[v66-2-22]]

^<<v66-2-22,22>>^ Eis que a porei numa cama, e sobre os que adulteram com ela virá grande tribulação, se não se arrependerem das suas obras.

[[v66-2-23]]

^<<v66-2-23,23>>^ E ferirei de morte a seus filhos, e todas as igrejas saberão que eu sou aquele que sonda os rins e os corações. E darei a cada um de vós segundo as vossas obras.

[[v66-2-24]]

^<<v66-2-24,24>>^ Mas eu vos digo a vós, e aos restantes que estão  em Tiatira, a todos quantos não têm esta doutrina, e não conheceram, como dizem, as profundezas de Satanás, que  outra carga vos não porei.

[[v66-2-25]]

^<<v66-2-25,25>>^ Mas o que tendes retende-o até que eu venha.

[[v66-2-26]]

^<<v66-2-26,26>>^ E ao que vencer, e guardar até ao fim as minhas obras, eu lhe darei poder sobre as nações,

[[v66-2-27]]

^<<v66-2-27,27>>^ E com vara de ferro as regerá: e serão quebradas como vasos de oleiro; como também recebi de meu Pai.

[[v66-2-28]]

^<<v66-2-28,28>>^ E dar-lhe-ei a estrela da manhã.

[[v66-2-29]]

^<<v66-2-29,29>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas.

'''

xref:066-apocalipse/066-apocalipse-001.adoc#v66-1-0[&#60; Capítulo Anterior] | <<v66-2-0,Topo>> | xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[Próximo Capítulo &#62;]