include::./index.adoc[]

[[v66-14-0]]
=== Apocalipse, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-14-1]]

^<<v66-14-1,1>>^ E OLHEI, e eis que estava o Cordeiro sobre o monte de Sião, e com ele cento e quarenta e quatro mil, que em suas testas tinham escrito o nome dele e o de seu Pai.

[[v66-14-2]]

^<<v66-14-2,2>>^ E ouvi uma voz do céu, como a voz de muitas águas, e como a voz de um grande trovão; e uma voz de harpistas, que tocavam com as suas harpas.

[[v66-14-3]]

^<<v66-14-3,3>>^ E cantavam um como cântico novo diante do trono, e diante dos quatro animais e dos anciãos; e ninguém podia aprender aquele cântico, senão os cento e quarenta e quatro mil que foram comprados da terra.

[[v66-14-4]]

^<<v66-14-4,4>>^ Estes são os que não estão contaminados com mulheres: porque são virgens. Estes são os que seguem o Cordeiro para onde quer que vai. Estes são os que dentre os homens foram comprados como primícias para Deus e para o Cordeiro.

[[v66-14-5]]

^<<v66-14-5,5>>^ E na sua boca não se achou engano; porque são irrepreensíveis diante do trono de Deus.

[[v66-14-6]]

^<<v66-14-6,6>>^ E vi outro anjo voar pelo meio do céu, e tinha o evangelho eterno, para o proclamar aos que habitam sobre a terra, e a toda a nação, e tribo, e língua, e povo.

[[v66-14-7]]

^<<v66-14-7,7>>^ Dizendo com grande voz: Temei a Deus, e dai-lhe glória; porque vinda é a hora do seu juízo. E adorai aquele que fez o céu, e a terra, e o mar, e as fontes das águas.

[[v66-14-8]]

^<<v66-14-8,8>>^ E outro anjo seguiu dizendo: Caiu, caiu Babilônia, aquela grande cidade que a todas as nações deu a beber do vinho da ira da sua prostituição.

[[v66-14-9]]

^<<v66-14-9,9>>^ E seguiu-os o terceiro anjo, dizendo com grande voz: Se alguém adorar a besta, e a sua imagem, e receber o sinal na sua testa, ou na sua mão.

[[v66-14-10]]

^<<v66-14-10,10>>^ Também o tal beberá do vinho da ira de Deus, que se deitou, não misturado, no cálice da sua ira; e será atormentado com fogo e enxofre diante dos santos anjos e diante do Cordeiro.

[[v66-14-11]]

^<<v66-14-11,11>>^ E o fumo do seu tormento sobe para todo o sempre; e não têm repouso nem de dia nem de noite os que adoram a besta e a sua imagem, e aquele que receber o sinal do seu nome.

[[v66-14-12]]

^<<v66-14-12,12>>^ Aqui está a paciência dos santos: aqui estão  os que guardam os mandamentos de Deus e a fé de Jesus.

[[v66-14-13]]

^<<v66-14-13,13>>^ E ouvi uma voz do céu, que me dizia: Escreve: Bem-aventurados os mortos que desde agora morrem no Senhor. Sim, diz o Espírito para que descansem dos seus trabalhos, e as suas obras os sigam.

[[v66-14-14]]

^<<v66-14-14,14>>^ E olhei, e eis uma nuvem branca, e assentado sobre a nuvem um  semelhante ao Filho do homem, que tinha sobre a sua cabeça uma coroa de ouro, e na sua mão uma foice aguda.

[[v66-14-15]]

^<<v66-14-15,15>>^ E outro anjo saiu do templo, clamando com grande voz ao que estava assentado sobre a nuvem: Lança a tua foice, e sega; é já vinda a hora de segar, porque já a seara da terra está madura.

[[v66-14-16]]

^<<v66-14-16,16>>^ E aquele que estava assentado sobre a nuvem meteu a sua foice à terra, e a terra foi segada.

[[v66-14-17]]

^<<v66-14-17,17>>^ E saiu do templo, que está no céu, outro anjo, o qual também tinha uma foice aguda.

[[v66-14-18]]

^<<v66-14-18,18>>^ E saiu do altar outro anjo, que tinha poder sobre o fogo, e clamou com grande voz ao que tinha a foice aguda, dizendo: Lança a tua foice aguda, e vindima os cachos da vinha da terra, porque já  as suas uvas estão maduras.

[[v66-14-19]]

^<<v66-14-19,19>>^ E o anjo meteu a sua foice à terra e vindimou as uvas  da vinha da terra, e lançou-as no grande lagar da ira de Deus.

[[v66-14-20]]

^<<v66-14-20,20>>^ E o lagar foi pisado fora da cidade, e saiu sangue do lagar até aos freios dos cavalos, pelo espaço de mil e seiscentos estádios.

'''

xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[&#60; Capítulo Anterior] | <<v66-14-0,Topo>> | xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[Próximo Capítulo &#62;]