include::./index.adoc[]

[[v66-5-0]]
=== Apocalipse, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-5-1]]

^<<v66-5-1,1>>^ E VI na destra do que estava assentado sobre o trono um livro escrito por dentro e por fora, selado com sete selos.

[[v66-5-2]]

^<<v66-5-2,2>>^ E vi um anjo forte, bradando com grande voz: Quem é digno de abrir o livro e de desatar os seus selos?

[[v66-5-3]]

^<<v66-5-3,3>>^ E ninguém no céu, nem na terra, nem debaixo da terra, podia abrir o livro, nem olhar para  ele.

[[v66-5-4]]

^<<v66-5-4,4>>^ E eu chorava muito, porque ninguém fora achado digno de abrir o livro, nem de o ler, nem de olhar para  ele.

[[v66-5-5]]

^<<v66-5-5,5>>^ E disse-me um dos anciãos: Não chores: eis aqui o Leão da tribo de Judá, a raiz de Davi, que venceu, para abrir o livro e desatar os seus sete selos.

[[v66-5-6]]

^<<v66-5-6,6>>^ E olhei, e eis que estava no meio do trono e dos quatro animais viventes e entre os anciãos um Cordeiro, como havendo sido morto, e tinha sete pontas e sete olhos, que são os sete Espíritos de Deus enviados a toda a terra.

[[v66-5-7]]

^<<v66-5-7,7>>^ E veio, e tomou o livro da destra do que estava assentado no trono.

[[v66-5-8]]

^<<v66-5-8,8>>^ E, havendo tomado o livro, os quatro animais e os vinte e quatro anciãos prostraram-se diante do Cordeiro, tendo todos eles harpas e salvas de ouro cheias de incenso, que são as orações dos santos.

[[v66-5-9]]

^<<v66-5-9,9>>^ E cantavam um novo cântico, dizendo: Digno és de tomar o livro, e de abrir os seus selos; porque foste morto, e com o teu sangue compraste para Deus homens de toda a tribo, e língua, e povo, e nação;

[[v66-5-10]]

^<<v66-5-10,10>>^ E para o nosso Deus os fizeste reis e sacerdotes; e eles reinarão sobre a terra.

[[v66-5-11]]

^<<v66-5-11,11>>^ E olhei, e ouvi a voz de muitos anjos ao redor do trono, e dos animais, e dos anciãos; e era o número deles milhões de milhões e milhares de milhares.

[[v66-5-12]]

^<<v66-5-12,12>>^ Que com grande voz diziam: Digno é o Cordeiro, que foi morto, de receber o poder, e riquezas, e sabedoria, e força, e honra, e glória, e ações de graças.

[[v66-5-13]]

^<<v66-5-13,13>>^ E ouvi a toda a criatura que está no céu, e na terra, e debaixo da terra, e que está no mar, e a todas as coisas que neles há, dizer: Ao que está assentado sobre o trono, e ao Cordeiro, sejam dadas ações de graças, e honra, e glória, e poder para todo o sempre.

[[v66-5-14]]

^<<v66-5-14,14>>^ E os quatro animais diziam: Amém. E os vinte e quatro anciãos prostraram-se, e adoraram ao que vive para todo o sempre.

'''

xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[&#60; Capítulo Anterior] | <<v66-5-0,Topo>> | xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[Próximo Capítulo &#62;]