include::./index.adoc[]

[[v66-11-0]]
=== Apocalipse, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-11-1]]

^<<v66-11-1,1>>^ E FOI-ME dada uma cana semelhante a uma vara: e chegou o anjo, e disse: Levanta-te, e mede o templo de Deus, e o altar, e os que nele adoram.

[[v66-11-2]]

^<<v66-11-2,2>>^ E deixa o átrio que está fora do templo, e não o meças; porque foi dado às nações, e pisarão a cidade santa por quarenta e dois meses.

[[v66-11-3]]

^<<v66-11-3,3>>^ E darei poder  às minhas duas testemunhas, e profetizarão por mil duzentos e sessenta dias, vestidas de saco.

[[v66-11-4]]

^<<v66-11-4,4>>^ Estas são as duas oliveiras e os dois castiçais que estão diante do Deus da terra.

[[v66-11-5]]

^<<v66-11-5,5>>^ E, se alguém lhes quiser fazer mal, fogo sairá da sua boca, e devorará os seus inimigos; e, se alguém lhes quiser fazer mal, importa que assim seja morto.

[[v66-11-6]]

^<<v66-11-6,6>>^ Estes têm poder para fechar o céu, para que não chova, nos dias da sua profecia; e têm poder sobre as águas para convertê-las em sangue, e para ferir a terra com toda a sorte de pragas, todas quantas vezes quiserem.

[[v66-11-7]]

^<<v66-11-7,7>>^ E, quando acabarem o seu testemunho, a besta que sobe do abismo lhes fará guerra, e os vencerá, e os matará.

[[v66-11-8]]

^<<v66-11-8,8>>^ E jazerão os seus corpos mortos na praça da grande cidade que espiritualmente se chama Sodoma e Egito, onde o seu Senhor também foi crucificado.

[[v66-11-9]]

^<<v66-11-9,9>>^ E homens de vários povos, e tribos, e línguas, e nações verão seus corpos mortos por três dias e meio, e não permitirão que os seus corpos mortos sejam postos em sepulcros.

[[v66-11-10]]

^<<v66-11-10,10>>^ E os que habitam na terra se regozijarão sobre eles, e se alegrarão, e mandarão presentes uns aos outros; porquanto estes dois profetas tinham atormentado os que habitam sobre a terra.

[[v66-11-11]]

^<<v66-11-11,11>>^ E depois daqueles três dias e meio o espírito de vida, vindo  de Deus, entrou neles; e puseram-se sobre seus pés, e caiu grande temor sobre os que os viram.

[[v66-11-12]]

^<<v66-11-12,12>>^ E ouviram uma grande voz do céu, que lhes dizia: Subi cá. E subiram ao céu em uma nuvem: e os seus inimigos os viram.

[[v66-11-13]]

^<<v66-11-13,13>>^ E naquela mesma hora houve um grande terremoto, e caiu a décima parte da cidade, e no terremoto foram mortos sete mil homens; e os demais ficaram muito atemorizados, e deram glória ao Deus do céu.

[[v66-11-14]]

^<<v66-11-14,14>>^ É passado o segundo ai; eis que o terceiro ai cedo virá.

[[v66-11-15]]

^<<v66-11-15,15>>^ E tocou o sétimo anjo a sua trombeta, e houve no céu grandes vozes, que diziam: Os reinos do mundo vieram a ser de nosso Senhor e do seu Cristo, e ele reinará para todo o sempre.

[[v66-11-16]]

^<<v66-11-16,16>>^ E os vinte e quatro anciãos, que estão assentados em seus tronos diante de Deus prostraram-se sobre seus rostos e adoraram a Deus,

[[v66-11-17]]

^<<v66-11-17,17>>^ Dizendo: Graças te damos, Senhor Deus Todo-poderoso, que és, e que eras, e que hás de vir, que tomaste o teu grande poder, e reinaste.

[[v66-11-18]]

^<<v66-11-18,18>>^ E iraram-se as nações, e veio a tua ira, e o tempo dos mortos, para que sejam julgados, e o tempo de dares o galardão aos profetas, teus servos, e aos santos, e aos que temem o teu nome, a pequenos e a grandes, e o tempo de destruíres os que destroem a terra.

[[v66-11-19]]

^<<v66-11-19,19>>^ E abriu-se no céu o templo de Deus, e a arca do seu concerto foi vista no seu templo: e houve relâmpagos, e vozes, e trovões, e terremotos e grande saraiva.

'''

xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[&#60; Capítulo Anterior] | <<v66-11-0,Topo>> | xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[Próximo Capítulo &#62;]