include::./index.adoc[]

[[v66-15-0]]
=== Apocalipse, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-15-1]]

^<<v66-15-1,1>>^ E VI outro grande e admirável sinal no céu: sete anjos, que tinham as sete últimas pragas; porque nelas é consumada a ira de Deus.

[[v66-15-2]]

^<<v66-15-2,2>>^ E vi um como mar de vidro misturado com fogo; e também os que saíram vitoriosos da besta, e da sua imagem, e do seu sinal, e  do número do seu nome, que estavam junto ao mar de vidro, e tinham as harpas de Deus.

[[v66-15-3]]

^<<v66-15-3,3>>^ E cantavam o cântico de Moisés, servo de Deus, e o cântico do Cordeiro, dizendo: Grandes e maravilhosas são  as tuas obras, Senhor Deus Todo-poderoso! Justos e verdadeiros são  os teus caminhos, ó Rei dos santos.

[[v66-15-4]]

^<<v66-15-4,4>>^ Quem te não temerá, ó Senhor, e não magnificará o teu nome? Porque só tu és  santo; por isso todas as nações virão, e se prostrarão diante de ti, porque os teus juízos são manifestos.

[[v66-15-5]]

^<<v66-15-5,5>>^ E depois disto olhei, e eis que o templo do tabernáculo do testemunho se abriu no céu.

[[v66-15-6]]

^<<v66-15-6,6>>^ E os sete anjos que tinham as sete pragas saíram do templo, vestidos de linho puro e resplandecente, e cingidos com cintos de ouro pelos peitos.

[[v66-15-7]]

^<<v66-15-7,7>>^ E um dos quatro animais deu aos sete anjos sete salvas de ouro, cheias da ira de Deus, que vive todo o sempre.

[[v66-15-8]]

^<<v66-15-8,8>>^ E o tempo encheu- se  com o fumo da glória de Deus e do seu poder; e ninguém podia entrar no templo, até que se consumassem as sete pragas dos sete anjos.

'''

xref:066-apocalipse/066-apocalipse-014.adoc#v66-14-0[&#60; Capítulo Anterior] | <<v66-15-0,Topo>> | xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[Próximo Capítulo &#62;]