include::./index.adoc[]

[[v66-17-0]]
=== Apocalipse, 17
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-17-1]]

^<<v66-17-1,1>>^ E VEIO um dos sete anjos que tinham as sete taças, e falou comigo, dizendo-me: Vem, mostrar-te-ei a condenação da grande prostituta que está assentada sobre muitas águas;

[[v66-17-2]]

^<<v66-17-2,2>>^ Com a qual se prostituíram os reis da terra; e os que habitam na terra se embebedaram com o vinho da sua prostituição.

[[v66-17-3]]

^<<v66-17-3,3>>^ E levou-me em espírito a um deserto, e vi uma mulher assentada sobre uma besta de cor de escarlata, que estava cheia de nomes de blasfêmia, e tinha sete cabeças e dez chifres.

[[v66-17-4]]

^<<v66-17-4,4>>^ E a mulher estava vestida de púrpura e de escarlata, e adornada com ouro, e pedras preciosas e pérolas; e tinha na sua mão um cálice de ouro cheio das abominações e da imundícia da sua prostituição;

[[v66-17-5]]

^<<v66-17-5,5>>^ E na sua testa estava escrito o nome: Mistério, a grande Babilônia, a mãe das prostituições e abominações da terra.

[[v66-17-6]]

^<<v66-17-6,6>>^ E vi que a mulher estava embriagada do sangue dos santos, e do sangue das testemunhas de Jesus. E, vendo-a eu, maravilhei-me com grande admiração.

[[v66-17-7]]

^<<v66-17-7,7>>^ E o anjo me disse: Por que te admiras? Eu te direi o mistério da mulher, e da besta que a traz, a qual tem sete cabeças e dez chifres.

[[v66-17-8]]

^<<v66-17-8,8>>^ A besta que viste foi e já  não é, e há de subir do abismo, e irá à perdição; e os que habitam na terra (cujos nomes não estão escritos no livro da vida, desde a fundação do mundo) se admirarão vendo a besta que era e já  não é, mas que virá.

[[v66-17-9]]

^<<v66-17-9,9>>^ Aqui há sentido, que tem sabedoria. As sete cabeças são sete montes, sobre os quais a mulher está assentada.

[[v66-17-10]]

^<<v66-17-10,10>>^ E são também  sete reis: cinco já caíram, e um existe; outro ainda não é vindo; e, quando vier, convém que dure um pouco de tempo.

[[v66-17-11]]

^<<v66-17-11,11>>^ E a besta que era e já  não é, é ela também o oitavo, e é dos sete, e vai à perdição.

[[v66-17-12]]

^<<v66-17-12,12>>^ E os dez chifres que viste são dez reis, que ainda não receberam o reino, mas receberão o poder como reis por uma hora, juntamente  com a besta.

[[v66-17-13]]

^<<v66-17-13,13>>^ Estes têm um mesmo intento, e entregarão o seu poder e autoridade à besta.

[[v66-17-14]]

^<<v66-17-14,14>>^ Estes combaterão contra o Cordeiro, e o Cordeiro os vencerá, porque é o Senhor dos senhores e o Rei dos reis; vencerão os que estão com ele, chamados, eleitos, e fiéis.

[[v66-17-15]]

^<<v66-17-15,15>>^ E disse-me: As águas que viste, onde se assenta a prostituta, são povos, e multidões, e nações, e línguas.

[[v66-17-16]]

^<<v66-17-16,16>>^ E os dez chifres que viste na besta são os que aborrecerão a prostituta, e a porão desolada e nua, e comerão a sua carne, e a queimarão no fogo.

[[v66-17-17]]

^<<v66-17-17,17>>^ Porque Deus tem posto em seus corações que cumpram o seu intento, e tenham uma mesma ideia, e que deem à besta o seu reino, até que se cumpram as palavras de Deus.

[[v66-17-18]]

^<<v66-17-18,18>>^ E a mulher que viste é a grande cidade que reina sobre os reis da terra.

'''

xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[Próximo Capítulo &#62;]