include::./index.adoc[]

[[v66-21-0]]
=== Apocalipse, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-21-1]]

^<<v66-21-1,1>>^ E VI um novo céu, e uma nova terra. Porque já o primeiro céu e a primeira terra passaram, e o mar já não existe.

[[v66-21-2]]

^<<v66-21-2,2>>^ E eu, João, vi a santa cidade, a nova Jerusalém, que de Deus descia do céu, adereçada como uma esposa ataviada para o seu marido.

[[v66-21-3]]

^<<v66-21-3,3>>^ E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles, e será  o seu Deus.

[[v66-21-4]]

^<<v66-21-4,4>>^ E Deus limpará de seus olhos toda a lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor; porque já  as primeiras coisas são passadas.

[[v66-21-5]]

^<<v66-21-5,5>>^ E o que estava assentado sobre o trono disse: Eis que faço novas todas as coisas. E disse-me: Escreve; porque estas palavras são verdadeiras e fiéis.

[[v66-21-6]]

^<<v66-21-6,6>>^ E disse-me mais: Está cumprido: Eu sou o Alfa e o Ômega, o princípio e o fim. A quem quer que tiver sede, de graça lhe darei da fonte da água da vida.

[[v66-21-7]]

^<<v66-21-7,7>>^ Quem vencer, herdará todas as coisas; e eu serei seu Deus, e ele será meu filho.

[[v66-21-8]]

^<<v66-21-8,8>>^ Mas, quanto aos tímidos, e aos incrédulos, e aos abomináveis, e aos homicidas, e aos fornicários, e aos feiticeiros, e aos idólatras e a todos os mentirosos, a sua parte será no lago que arde com fogo e enxofre; o que é a segunda morte.

[[v66-21-9]]

^<<v66-21-9,9>>^ E veio um dos sete anjos que tinham as sete taças cheias das últimas sete pragas, e falou comigo, dizendo: Vem, mostrar-te-ei a esposa, a mulher do Cordeiro.

[[v66-21-10]]

^<<v66-21-10,10>>^ E levou-me em espírito a um grande e alto monte, e mostrou-me a grande cidade, a santa Jerusalém, que de Deus descia do céu.

[[v66-21-11]]

^<<v66-21-11,11>>^ E tinha a glória de Deus; e a sua luz era semelhante a uma pedra preciosíssima, como a pedra de jaspe, como o cristal resplandecente.

[[v66-21-12]]

^<<v66-21-12,12>>^ E tinha um grande e alto muro com doze portas, e nas portas doze anjos, e nomes escritos sobre elas, que são os nomes  das doze tribos de Israel.

[[v66-21-13]]

^<<v66-21-13,13>>^ Da banda do levante tinha três portas, da banda do norte três portas, da banda do sul três portas, da banda do poente três portas.

[[v66-21-14]]

^<<v66-21-14,14>>^ E o muro da cidade tinha doze fundamentos, e neles os nomes  dos doze apóstolos do Cordeiro.

[[v66-21-15]]

^<<v66-21-15,15>>^ E aquele que falava comigo tinha uma cana de ouro, para medir a cidade, e as suas portas, e o seu muro.

[[v66-21-16]]

^<<v66-21-16,16>>^ E a cidade estava situada em quadrado; e o seu comprimento era tanto como a sua  largura. E mediu a cidade com a cana até doze mil estádios: e o seu comprimento, largura e altura eram iguais.

[[v66-21-17]]

^<<v66-21-17,17>>^ E mediu o seu muro, de cento e quarenta e quatro côvados, conforme à medida de homem, que é a dum anjo.

[[v66-21-18]]

^<<v66-21-18,18>>^ E a fábrica do seu muro era de jaspe, e a cidade de ouro puro, semelhante a vidro puro.

[[v66-21-19]]

^<<v66-21-19,19>>^ E os fundamentos do muro da cidade estavam  adornados de toda a pedra preciosa. O primeiro fundamento era  jaspe; o segundo, safira; o terceiro, calcedônia; o quarto, esmeralda;

[[v66-21-20]]

^<<v66-21-20,20>>^ O quinto sardônica; o sexto, sárdio; o sétimo, crisólito; o oitavo, berilo; o nono, topázio; o décimo, crisópraso; o undécimo, jacinto; o duodécimo, ametista.

[[v66-21-21]]

^<<v66-21-21,21>>^ E as doze portas eram  doze pérolas: cada uma das portas era uma pérola; e a praça da cidade de ouro puro, como vidro transparente.

[[v66-21-22]]

^<<v66-21-22,22>>^ E nela não vi templo, porque o seu templo é o Senhor Deus Todo-poderoso, e o Cordeiro.

[[v66-21-23]]

^<<v66-21-23,23>>^ E a cidade não necessita de sol nem de lua, para que nela resplandeçam, porque a glória de Deus a tem alumiado, e o Cordeiro é  a sua lâmpada.

[[v66-21-24]]

^<<v66-21-24,24>>^ E as nações andarão à sua luz; e os reis da terra trarão para ela a sua glória e honra.

[[v66-21-25]]

^<<v66-21-25,25>>^ E as suas portas não se fecharão de dia, porque ali não haverá noite.

[[v66-21-26]]

^<<v66-21-26,26>>^ E a ela trarão a glória e honra das nações.

[[v66-21-27]]

^<<v66-21-27,27>>^ E não entrará nela coisa alguma que contamine, e cometa abominação e mentira; mas só os que estão inscritos no livro da vida do Cordeiro.

'''

xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[&#60; Capítulo Anterior] | <<v66-21-0,Topo>> | xref:066-apocalipse/066-apocalipse-022.adoc#v66-22-0[Próximo Capítulo &#62;]