include::./index.adoc[]

[[v66-16-0]]
=== Apocalipse, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-16-1]]

^<<v66-16-1,1>>^ E OUVI, vinda do templo, uma grande voz, que dizia aos sete anjos: Ide e derramai sobre a terra as sete  salvas da ira de Deus.

[[v66-16-2]]

^<<v66-16-2,2>>^ E foi o primeiro, e derramou a sua salva sobre a terra, e fez-se uma chaga má e maligna nos homens que tinham o sinal da besta e que adoravam a sua imagem.

[[v66-16-3]]

^<<v66-16-3,3>>^ E o segundo anjo derramou a sua salva no mar, que se tornou em sangue como de um morto, e morreu no mar toda a alma vivente.

[[v66-16-4]]

^<<v66-16-4,4>>^ E o terceiro anjo derramou a sua taça nos rios e nas fontes das águas, e se tornaram em sangue.

[[v66-16-5]]

^<<v66-16-5,5>>^ E ouvi o anjo das águas que dizia: Justo és tu, ó Senhor, que és, e que eras, e santo és, porque julgaste estas coisas.

[[v66-16-6]]

^<<v66-16-6,6>>^ Visto como derramaram o sangue dos santos e dos profetas, também tu lhes deste o sangue a beber; porque disto são merecedores.

[[v66-16-7]]

^<<v66-16-7,7>>^ E ouvi outro do altar, que dizia: Na verdade, ó Senhor Deus Todo-poderoso, verdadeiros e justos são os teus juízos.

[[v66-16-8]]

^<<v66-16-8,8>>^ E o quarto anjo derramou a sua taça sobre o sol, e foi-lhe permitido que abrasasse os homens com fogo.

[[v66-16-9]]

^<<v66-16-9,9>>^ E os homens foram abrasados com grandes calores, e blasfemaram o nome de Deus, que tem poder sobre estas pragas; e não se arrependeram para lhe darem glória.

[[v66-16-10]]

^<<v66-16-10,10>>^ E o quinto anjo derramou a sua taça sobre o trono da besta, e o seu reino se fez tenebroso; e eles mordiam as suas línguas de dor.

[[v66-16-11]]

^<<v66-16-11,11>>^ E por causa das suas dores, e por causa das suas chagas, blasfemaram do Deus do céu; e não se arrependeram das suas obras.

[[v66-16-12]]

^<<v66-16-12,12>>^ E o sexto anjo derramou a sua taça sobre o grande rio Eufrates; e a sua água secou-se, para que se preparasse o caminho dos reis do Oriente.

[[v66-16-13]]

^<<v66-16-13,13>>^ E da boca do dragão, e da boca da besta, e da boca do falso profeta vi sair três espíritos imundos, semelhantes a rãs.

[[v66-16-14]]

^<<v66-16-14,14>>^ Porque são espíritos de demônios, que fazem prodígios; os quais vão ao encontro dos reis de todo o mundo, para os congregar para a batalha, naquele grande dia do Deus Todo-poderoso.

[[v66-16-15]]

^<<v66-16-15,15>>^ Eis que venho como ladrão. Bem-aventurado aquele que vigia, e guarda os seus vestidos, para que não ande nu, e não se vejam as suas vergonhas.

[[v66-16-16]]

^<<v66-16-16,16>>^ E os congregaram no lugar que em hebreu se chama Armagedom.

[[v66-16-17]]

^<<v66-16-17,17>>^ E o sétimo anjo derramou a sua taça no ar, e saiu grande voz do templo do céu, do trono, dizendo: Está feito.

[[v66-16-18]]

^<<v66-16-18,18>>^ E houve vozes, e trovões, e relâmpagos, e um grande terremoto, como nunca tinha havido desde que há homens sobre a terra: tal foi este  tão grande terremoto.

[[v66-16-19]]

^<<v66-16-19,19>>^ E a grande cidade fendeu-se em três partes, e as cidades das nações caíram; e da grande Babilônia se lembrou Deus, para lhe dar o cálice do vinho da indignação da sua ira.

[[v66-16-20]]

^<<v66-16-20,20>>^ E toda a ilha fugiu; e os montes não se acharam.

[[v66-16-21]]

^<<v66-16-21,21>>^ E sobre os homens caiu do céu uma grande saraiva, pedras do peso de um talento; e os homens blasfemaram de Deus por causa da praga da saraiva: porque a sua praga era mui grande.

'''

xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[&#60; Capítulo Anterior] | <<v66-16-0,Topo>> | xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[Próximo Capítulo &#62;]