include::./index.adoc[]

[[v66-22-0]]
=== Apocalipse, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-22-1]]

^<<v66-22-1,1>>^ E MOSTROU-ME o rio puro da água da vida, claro como cristal, que procedia do trono de Deus e do Cordeiro.

[[v66-22-2]]

^<<v66-22-2,2>>^ No meio da sua praça, e de uma e da outra banda do rio, estava  a árvore da vida, que produz doze frutos, dando seu fruto de mês em mês; e as folhas da árvore são  para a saúde das nações.

[[v66-22-3]]

^<<v66-22-3,3>>^ E ali  nunca mais haverá maldição contra alguém ; e nela estará o trono de Deus e do Cordeiro, e os seus servos o servirão.

[[v66-22-4]]

^<<v66-22-4,4>>^ E verão o seu rosto, e nas suas testas estará  o seu nome.

[[v66-22-5]]

^<<v66-22-5,5>>^ E ali não haverá mais noite, e não necessitarão de lâmpada nem de luz do sol, porque o Senhor Deus os alumia; e reinarão para todo o sempre.

[[v66-22-6]]

^<<v66-22-6,6>>^ E disse-me: Estas palavras são  fiéis e verdadeiras; e o Senhor, o Deus dos santos profetas, enviou o seu anjo, para mostrar aos seus servos as coisas que em breve hão de acontecer.

[[v66-22-7]]

^<<v66-22-7,7>>^ Eis que presto venho: Bem-aventurado aquele que guarda as palavras da profecia deste livro.

[[v66-22-8]]

^<<v66-22-8,8>>^ E eu, João, sou  aquele que vi e ouvi estas coisas. E, havendo- as  ouvido e visto, prostrei-me aos pés do anjo que mas mostrava para o adorar.

[[v66-22-9]]

^<<v66-22-9,9>>^ E disse-me: Olha não faças  tal; porque eu sou conservo teu e de teus irmãos, os profetas, e dos que guardam as palavras deste livro. Adora a Deus.

[[v66-22-10]]

^<<v66-22-10,10>>^ E disse-me: Não seles as palavras da profecia deste livro; porque próximo está o tempo.

[[v66-22-11]]

^<<v66-22-11,11>>^ Quem é injusto, faça injustiça ainda; e quem está sujo, suje-se ainda; e quem é justo, faça justiça ainda; e quem é santo, seja santificado ainda.

[[v66-22-12]]

^<<v66-22-12,12>>^ E eis que cedo venho, e o meu galardão está comigo, para dar a cada um segundo a sua obra.

[[v66-22-13]]

^<<v66-22-13,13>>^ Eu sou o Alfa e o Ômega, o princípio e o fim, o primeiro e o derradeiro.

[[v66-22-14]]

^<<v66-22-14,14>>^ Bem-aventurados aqueles que lavam as suas vestiduras no sangue do Cordeiro, para que tenham direito à árvore da vida, e possam entrar na cidade pelas portas.

[[v66-22-15]]

^<<v66-22-15,15>>^ Ficarão de fora os cães e os feiticeiros, e os que se prostituem, e os homicidas, e os idólatras, e qualquer que ama e comete a mentira.

[[v66-22-16]]

^<<v66-22-16,16>>^ Eu, Jesus, enviei o meu anjo, para vos testificar estas coisas nas igrejas: eu sou a raiz e a geração de Davi, a resplandecente estrela da manhã.

[[v66-22-17]]

^<<v66-22-17,17>>^ E o Espírito e a esposa dizem: Vem. E quem ouve, diga: Vem. E quem tem sede, venha; e quem quiser, tome de graça da água da vida.

[[v66-22-18]]

^<<v66-22-18,18>>^ Porque eu testifico a todo aquele que ouvir as palavras da profecia deste livro que  se alguém lhes acrescentar alguma coisa , Deus fará vir sobre ele as pragas que estão  escritas neste livro;

[[v66-22-19]]

^<<v66-22-19,19>>^ E, se alguém tirar quaisquer palavras do livro desta profecia, Deus tirará a sua parte da árvore da vida, e da cidade santa, que estão escritas neste livro.

[[v66-22-20]]

^<<v66-22-20,20>>^ Aquele que testifica estas coisas  diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus.

[[v66-22-21]]

^<<v66-22-21,21>>^ A graça de nosso Senhor Jesus Cristo seja  com todos vós. Amém.

'''

xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[&#60; Capítulo Anterior] | <<v66-22-0,Topo>> | **Próximo Capítulo &#62;**