include::./index.adoc[]

[[v66-9-0]]
=== Apocalipse, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-9-1]]

^<<v66-9-1,1>>^ E O QUINTO anjo tocou a sua trombeta, e vi uma estrela que do céu caiu na terra; e foi-lhe dada a chave do poço do abismo.

[[v66-9-2]]

^<<v66-9-2,2>>^ E abriu o poço do abismo, e subiu fumo do poço, como o fumo de uma grande fornalha, e com o fumo do poço escureceu-se o sol e o ar.

[[v66-9-3]]

^<<v66-9-3,3>>^ E do fumo vieram gafanhotos sobre a terra; e foi-lhes dado poder, como o poder que têm os escorpiões da terra.

[[v66-9-4]]

^<<v66-9-4,4>>^ E foi-lhes dito que não fizessem dano à erva da terra, nem a verdura alguma, nem a árvore alguma, mas somente aos homens que não têm nas suas testas o sinal de Deus.

[[v66-9-5]]

^<<v66-9-5,5>>^ E foi-lhes permitido, não que os matassem, mas que por cinco meses os atormentassem; e o seu tormento era  semelhante ao tormento do escorpião, quando fere o homem.

[[v66-9-6]]

^<<v66-9-6,6>>^ E naqueles dias os homens buscarão a morte, e não a acharão; e desejarão morrer, e a morte fugirá deles.

[[v66-9-7]]

^<<v66-9-7,7>>^ E o parecer dos gafanhotos era  semelhante ao de cavalos aparelhados para a guerra; e sobre as suas cabeças havia umas como coroas semelhantes ao ouro; e os seus rostos eram  como rostos de homens.

[[v66-9-8]]

^<<v66-9-8,8>>^ E tinham cabelos como cabelos de mulheres, e os seus dentes eram como de leões.

[[v66-9-9]]

^<<v66-9-9,9>>^ E tinham couraças como couraças de ferro; e o ruído das suas asas era  como o ruído de carros, quando muitos cavalos correm ao combate.

[[v66-9-10]]

^<<v66-9-10,10>>^ E tinham caudas semelhantes às dos escorpiões, e aguilhões nas suas caudas; e o seu poder era  para danificar os homens por cinco meses.

[[v66-9-11]]

^<<v66-9-11,11>>^ E tinham sobre si rei, o anjo do abismo; em hebreu era o seu nome Abadom, e em grego Apoliom.

[[v66-9-12]]

^<<v66-9-12,12>>^ Passado é já um ai; eis que depois disso vêm ainda dois ais.

[[v66-9-13]]

^<<v66-9-13,13>>^ E tocou o sexto anjo a sua trombeta, e ouvi uma voz que vinha  das quatro pontas do altar de ouro, que estava diante de Deus.

[[v66-9-14]]

^<<v66-9-14,14>>^ A qual dizia ao sexto anjo, que tinha a trombeta: Solta os quatro anjos, que estão presos junto ao grande rio Eufrates.

[[v66-9-15]]

^<<v66-9-15,15>>^ E foram soltos os quatro anjos, que estavam preparados para a hora, e dia, e mês, e ano, a fim de matarem a terça parte dos homens.

[[v66-9-16]]

^<<v66-9-16,16>>^ E o número dos exércitos dos cavaleiros era de duzentos milhões; e ouvi o número deles.

[[v66-9-17]]

^<<v66-9-17,17>>^ E assim vi os cavalos nesta visão; e os que sobre eles cavalgavam tinham couraças de fogo, e de jacinto, e de enxofre; e as cabeças dos cavalos eram  como cabeças de leões; e de suas bocas saía fogo e fumo e enxofre.

[[v66-9-18]]

^<<v66-9-18,18>>^ Por estas três pragas foi morta a terça parte dos homens, isto é pelo fogo, pelo fumo, e pelo enxofre, que saía das suas bocas.

[[v66-9-19]]

^<<v66-9-19,19>>^ Porque o poder dos cavalos está na sua boca e nas suas caudas. Porquanto as suas caudas são  semelhantes a serpentes, e têm cabeças, e com elas danificam.

[[v66-9-20]]

^<<v66-9-20,20>>^ E os outros homens, que não foram mortos por estas pragas, não se arrependeram das obras de suas mãos, para não adorarem os demônios, e os ídolos de ouro, e de prata, e de bronze, e de pedra, e de madeira, que nem podem ver, nem ouvir, nem andar.

[[v66-9-21]]

^<<v66-9-21,21>>^ E não se arrependeram dos seus homicídios, nem das suas feitiçarias, nem da sua prostituição, nem das suas ladroíces.

'''

xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[&#60; Capítulo Anterior] | <<v66-9-0,Topo>> | xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[Próximo Capítulo &#62;]