include::./index.adoc[]

[[v66-18-0]]
=== Apocalipse, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-18-1]]

^<<v66-18-1,1>>^ E DEPOIS destas coisas  vi descer do céu outro anjo, que tinha grande poder, e a terra foi iluminada com a sua glória.

[[v66-18-2]]

^<<v66-18-2,2>>^ E clamou fortemente com grande voz, dizendo: Caiu, caiu a grande Babilônia, e se tornou morada de demônios, e coito de todo espírito imundo, e coito de toda ave imunda e aborrecível.

[[v66-18-3]]

^<<v66-18-3,3>>^ Porque todas as nações beberam do vinho da ira da sua prostituição, e  os reis da terra se prostituíram com ela; e os mercadores da terra se enriqueceram com a abundância de suas delícias.

[[v66-18-4]]

^<<v66-18-4,4>>^ E ouvi outra voz do céu que dizia: Sai dela, povo meu, para que não sejas participante dos seus pecados, e para que não incorras nas suas pragas.

[[v66-18-5]]

^<<v66-18-5,5>>^ Porque já  os seus pecados se acumularam até ao céu, e Deus se lembrou das iniquidades dela.

[[v66-18-6]]

^<<v66-18-6,6>>^ Tornai-lhe a dar como ela vos tem dado, e retribuí-lhe em dobro conforme as suas obras: no cálice em que vos  deu de beber dai-lhe a ela em dobro.

[[v66-18-7]]

^<<v66-18-7,7>>^ Quanto ela se glorificou, e em delícias esteve, foi-lhe outro tanto de tormento e pranto; porque diz em seu coração: Estou assentada como  rainha, e não sou viúva, e não verei o pranto.

[[v66-18-8]]

^<<v66-18-8,8>>^ Portanto, num dia virão as suas pragas, a morte, e o pranto, e a fome; e será queimada no fogo; porque é  forte o Senhor Deus que a julga.

[[v66-18-9]]

^<<v66-18-9,9>>^ E os reis da terra, que se prostituíram com ela, e viveram em delícias, a chorarão, e sobre ela prantearão, quando virem o fumo do seu incêndio;

[[v66-18-10]]

^<<v66-18-10,10>>^ Estando de longe pelo temor do seu tormento, dizendo: Ai! ai daquela grande Babilônia, aquela forte cidade! pois numa hora veio o seu juízo.

[[v66-18-11]]

^<<v66-18-11,11>>^ E sobre ela choram e lamentam os mercadores da terra; porque ninguém mais compra as suas mercadorias:

[[v66-18-12]]

^<<v66-18-12,12>>^ Mercadorias de ouro, e de prata, e de pedras preciosas, e de pérolas, e de linho fino, e de púrpura, e de seda, e de escarlata; e toda a madeira odorífera, e todo o vaso de marfim, e todo o vaso de madeira preciosíssima, de bronze e de ferro, e de mármore;

[[v66-18-13]]

^<<v66-18-13,13>>^ E cinamomo, e amomo, e perfume, e mirra, e incenso, e vinho, e azeite, e flor de farinha, e trigo, e cavalgaduras, e ovelhas; e mercadorias de cavalos, e de carros, e de corpos e de almas de homens.

[[v66-18-14]]

^<<v66-18-14,14>>^ E o fruto do desejo da tua alma foi-se de ti; e todas as coisas gostosas e excelentes se foram de ti, e não mais as acharás.

[[v66-18-15]]

^<<v66-18-15,15>>^ Os mercadores destas coisas, que com elas se enriqueceram, estarão de longe, pelo temor do seu tormento, chorando e lamentando,

[[v66-18-16]]

^<<v66-18-16,16>>^ E dizendo: Ai, ai daquela grande cidade! que estava vestida de linho fino, de púrpura, de escarlata; e adornada com ouro e pedras preciosas e pérolas! Porque numa hora foram assoladas tantas riquezas.

[[v66-18-17]]

^<<v66-18-17,17>>^ E todo o piloto, e todo o que navega em naus, e todo o marinheiro, e todos os que negociam no mar se puseram de longe;

[[v66-18-18]]

^<<v66-18-18,18>>^ E, vendo o fumo do seu incêndio, clamaram, dizendo: Que cidade é  semelhante a esta grande cidade?

[[v66-18-19]]

^<<v66-18-19,19>>^ E lançaram pó sobre as suas cabeças, e clamaram, chorando, e lamentando, e dizendo: Ai, ai daquela grande cidade! na qual todos os que tinham naus no mar se enriqueceram em razão da sua opulência; porque numa hora foi assolada.

[[v66-18-20]]

^<<v66-18-20,20>>^ Alegra-te sobre ela, ó céu, e vós, santos apóstolos e profetas; porque já  Deus julgou a vossa causa quanto a ela.

[[v66-18-21]]

^<<v66-18-21,21>>^ E um forte anjo levantou uma pedra como uma grande mó, e lançou- a  no mar, dizendo: Com igual ímpeto será lançada Babilônia, aquela grande cidade, e não será jamais achada.

[[v66-18-22]]

^<<v66-18-22,22>>^ E em ti não se ouvirá mais a voz de harpistas, e de músicos, e de frauteiros, e de trombeteiros, e nenhum artífice de arte alguma se achará mais em ti; e ruído de mó em ti se não ouvirá mais;

[[v66-18-23]]

^<<v66-18-23,23>>^ E luz de candeia não mais luzirá em ti, e voz de esposo e de esposa não mais em ti se ouvirá; porque os teus mercadores eram os grandes da terra; porque todas as nações foram enganadas pelas tuas feitiçarias.

[[v66-18-24]]

^<<v66-18-24,24>>^ E nela se achou o sangue dos profetas, e dos santos, e de todos os que foram mortos na terra.

'''

xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[&#60; Capítulo Anterior] | <<v66-18-0,Topo>> | xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[Próximo Capítulo &#62;]