include::./index.adoc[]

[[v66-4-0]]
=== Apocalipse, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-4-1]]

^<<v66-4-1,1>>^ DEPOIS destas coisas, olhei, e eis que estava  uma porta aberta no céu: e a primeira voz, que como de trombeta ouvira falar comigo, disse: Sobe aqui, e mostrar-te-ei as coisas que depois destas devem acontecer.

[[v66-4-2]]

^<<v66-4-2,2>>^ E logo fui arrebatado  em espírito, e eis que um trono estava posto no céu, e um  assentado sobre o trono.

[[v66-4-3]]

^<<v66-4-3,3>>^ E o que estava assentado era, na aparência, semelhante à pedra jaspe e sardônica; e o arco celeste estava ao redor do trono, e parecia semelhante à esmeralda.

[[v66-4-4]]

^<<v66-4-4,4>>^ E ao redor do trono havia  vinte e quatro tronos; e vi assentados sobre os tronos vinte e quatro anciãos vestidos de vestidos brancos; e tinham sobre suas cabeças coroas de ouro.

[[v66-4-5]]

^<<v66-4-5,5>>^ E do trono saíam relâmpagos, e trovões, e vozes; e diante do trono ardiam sete lâmpadas de fogo, as quais são os sete Espíritos de Deus.

[[v66-4-6]]

^<<v66-4-6,6>>^ E havia  diante do trono um como mar de vidro, semelhante ao cristal. E no meio do trono, e ao redor do trono, quatro animais cheios de olhos, por diante e por detrás.

[[v66-4-7]]

^<<v66-4-7,7>>^ E o primeiro animal era  semelhante a um leão, e o segundo animal semelhante a um bezerro, e tinha o terceiro animal o rosto como de homem, e o quarto animal era  semelhante a uma águia voando.

[[v66-4-8]]

^<<v66-4-8,8>>^ E os quatro animais tinham, cada um de per si, seis asas, e ao redor, e por dentro, estavam cheios de olhos; e não descansam nem de dia nem de noite, dizendo: Santo, Santo, Santo é o Senhor Deus, o Todo-poderoso, que era, e que é, e que há de vir.

[[v66-4-9]]

^<<v66-4-9,9>>^ E, quando os animais davam glória, e honra, e ações de graças ao que estava assentado sobre o trono, ao que vive para todo o sempre,

[[v66-4-10]]

^<<v66-4-10,10>>^ Os vinte e quatro anciãos prostravam-se diante do que estava assentado sobre o trono, e adoravam o que vive para todo o sempre; e lançavam as suas coroas diante do trono, dizendo:

[[v66-4-11]]

^<<v66-4-11,11>>^ Digno és, Senhor, de receber glória, e honra, e poder; porque tu criaste todas as coisas, e por tua vontade são e foram criadas.

'''

xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[&#60; Capítulo Anterior] | <<v66-4-0,Topo>> | xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[Próximo Capítulo &#62;]