include::./index.adoc[]

[[v66-1-0]]
=== Apocalipse, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-1-1]]

^<<v66-1-1,1>>^ REVELAÇÃO de Jesus Cristo, a qual Deus lhe deu, para mostrar aos seus servos as coisas  que brevemente devem acontecer; e pelo seu anjo as enviou, e as notificou a João seu servo;

[[v66-1-2]]

^<<v66-1-2,2>>^ O qual testificou da palavra de Deus, e do testemunho de Jesus Cristo, e de tudo o que tem visto.

[[v66-1-3]]

^<<v66-1-3,3>>^ Bem-aventurado aquele que lê, e os que ouvem as palavras desta profecia, e guardam as coisas  que nela estão escritas; porque o tempo está próximo.

[[v66-1-4]]

^<<v66-1-4,4>>^ João, às sete igrejas que estão na Ásia: Graça e paz seja  convosco da parte daquele que é, e que era, e que há de vir, e da dos sete espíritos que estão diante do seu trono;

[[v66-1-5]]

^<<v66-1-5,5>>^ E da parte de Jesus Cristo, que é a fiel testemunha, o primogênito dos mortos e o príncipe dos reis da terra. Àquele que nos ama, e em seu sangue nos lavou dos nossos pecados,

[[v66-1-6]]

^<<v66-1-6,6>>^ E nos fez reis e sacerdotes para Deus e seu Pai: a ele glória e poder para todo o sempre. Amém.

[[v66-1-7]]

^<<v66-1-7,7>>^ Eis que vem com as nuvens e todo o olho o verá, até os mesmos que o traspassaram; e todas as tribos da terra se lamentarão sobre ele. Sim. Amém.

[[v66-1-8]]

^<<v66-1-8,8>>^ Eu sou o Alfa e o Ômega, o princípio e o fim, diz o Senhor, que é, e que era, e que há de vir, o Todo-poderoso.

[[v66-1-9]]

^<<v66-1-9,9>>^ Eu, João, que também sou vosso irmão, e companheiro na aflição, e no reino, e paciência de Jesus Cristo, estava na ilha chamada Patmos, por causa da palavra de Deus, e pelo testemunho de Jesus Cristo.

[[v66-1-10]]

^<<v66-1-10,10>>^ Eu fui arrebatado em espírito no dia do Senhor, e ouvi detrás de mim uma grande voz, como de trombeta,

[[v66-1-11]]

^<<v66-1-11,11>>^ Que dizia: O que vês, escreve-o num livro, e envia- o  às sete igrejas que estão na Ásia: a Éfeso, e a Smirna, e a Pérgamo, e a Tiatira, e a Sardo, e a Filadélfia, e a Laodiceia.

[[v66-1-12]]

^<<v66-1-12,12>>^ E virei-me para ver quem falava comigo. E, virando-me, vi sete castiçais de ouro;

[[v66-1-13]]

^<<v66-1-13,13>>^ E no meio dos sete castiçais um  semelhante ao Filho do homem, vestido até aos pés de um vestido comprido, e cingido pelos peitos com um cinto de ouro.

[[v66-1-14]]

^<<v66-1-14,14>>^ E a sua cabeça e cabelos eram  brancos como lã branca, como a neve, e os seus olhos como chama de fogo;

[[v66-1-15]]

^<<v66-1-15,15>>^ E os seus pés, semelhantes a latão reluzente, como se tivessem sido refinados numa fornalha, e a sua voz como a voz de muitas águas.

[[v66-1-16]]

^<<v66-1-16,16>>^ E ele tinha na sua destra sete estrelas; e da sua boca saía uma aguda espada de dois fios; e o seu rosto era  como o  sol, quando  na sua força resplandece.

[[v66-1-17]]

^<<v66-1-17,17>>^ E eu, quando o vi, caí a seus pés como morto; e ele pôs sobre mim a sua destra, dizendo-me: Não temas; Eu sou o primeiro e o último;

[[v66-1-18]]

^<<v66-1-18,18>>^ E o que vivo e fui morto, mas eis aqui estou vivo para todo o sempre. Amém. E tenho as chaves da morte e do inferno.

[[v66-1-19]]

^<<v66-1-19,19>>^ Escreve as coisas que tens visto, e as que são, e as que depois destas hão de acontecer:

[[v66-1-20]]

^<<v66-1-20,20>>^ O mistério das sete estrelas, que viste na minha destra, e dos sete castiçais de ouro. As sete estrelas são os anjos das sete igrejas, e os sete castiçais, que viste, são as sete igrejas.

'''

xref:065-judas/065-judas-001.adoc#v65-1-0[&#60; Capítulo Anterior] | <<v66-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[Próximo Capítulo &#62;]