include::./index.adoc[]

[[v66-3-0]]
=== Apocalipse, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v66-3-1]]

^<<v66-3-1,1>>^ E AO ANJO da igreja que está em Sardo escreve: Isto diz o que tem os sete Espíritos de Deus, e as sete estrelas: Eu sei as tuas obras, que tens nome de que vives, e estás morto.

[[v66-3-2]]

^<<v66-3-2,2>>^ Sê vigilante, e confirma os restantes, que estavam para morrer; porque não achei as tuas obras perfeitas diante de Deus.

[[v66-3-3]]

^<<v66-3-3,3>>^ Lembra-te pois do que tens recebido e ouvido, e guarda-o, e arrepende-te. E, se não vigiares, virei sobre ti como um ladrão, e não saberás a que hora sobre ti virei.

[[v66-3-4]]

^<<v66-3-4,4>>^ Mas também tens em Sardo algumas pessoas que não contaminaram seus vestidos, e comigo andarão de branco; porquanto são dignas disso.

[[v66-3-5]]

^<<v66-3-5,5>>^ O que vencer será vestido de vestes brancas, e de maneira nenhuma riscarei o seu nome do livro da vida; e confessarei o seu nome diante de meu Pai e diante dos seus anjos.

[[v66-3-6]]

^<<v66-3-6,6>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas.

[[v66-3-7]]

^<<v66-3-7,7>>^ E ao anjo da igreja que está em Filadélfia escreve: Isto diz o que é santo, o que é verdadeiro, o que tem a chave de Davi; o que abre, e ninguém fecha; e fecha, e ninguém abre:

[[v66-3-8]]

^<<v66-3-8,8>>^ Eu sei as tuas obras: eis que diante de ti pus uma porta aberta, e ninguém a pode fechar: tendo pouca força, guardaste a minha palavra, e não negaste o meu nome.

[[v66-3-9]]

^<<v66-3-9,9>>^ Eis que eu farei aos da sinagoga de Satanás, aos que se dizem judeus, e não são, mas mentem: eis que eu farei que venham, e adorem prostrados a teus pés, e saibam que eu te amo.

[[v66-3-10]]

^<<v66-3-10,10>>^ Como guardaste a palavra da minha paciência, também eu te guardarei da hora da tentação que há de vir sobre todo o mundo, para tentar os que habitam na terra.

[[v66-3-11]]

^<<v66-3-11,11>>^ Eis que venho sem demora; guarda o que tens, para que ninguém tome a tua coroa.

[[v66-3-12]]

^<<v66-3-12,12>>^ A quem vencer, eu o farei coluna no templo do meu Deus, e dele nunca sairá; e escreverei sobre ele o nome do meu Deus, e o nome da cidade do meu Deus, a nova Jerusalém, que desce do céu, do meu Deus, e também o meu novo nome.

[[v66-3-13]]

^<<v66-3-13,13>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas.

[[v66-3-14]]

^<<v66-3-14,14>>^ E ao anjo da igreja que está em Laodiceia escreve: Isto diz o Amém, a testemunha fiel e verdadeira, o princípio da criação de Deus.

[[v66-3-15]]

^<<v66-3-15,15>>^ Eu sei as tuas obras, que nem és frio nem quente: oxalá foras frio ou quente!

[[v66-3-16]]

^<<v66-3-16,16>>^ Assim, porque és morno, e não és frio nem quente, vomitar-te-ei da minha boca.

[[v66-3-17]]

^<<v66-3-17,17>>^ Como dizes: Rico sou, e estou enriquecido, e de nada tenho falta; e não sabes que és um desgraçado, e miserável, e pobre, e cego, e nu;

[[v66-3-18]]

^<<v66-3-18,18>>^ Aconselho-te que de mim compres ouro provado no fogo, para que te enriqueças; e vestidos brancos, para que te vistas, e não apareça a vergonha da tua nudez; e que unjas os teus olhos com colírio, para que vejas;

[[v66-3-19]]

^<<v66-3-19,19>>^ Eu repreendo e castigo a todos quantos amo: sê pois zeloso, e arrepende-te.

[[v66-3-20]]

^<<v66-3-20,20>>^ Eis que estou à porta, e bato: se alguém ouvir a minha voz, e abrir a porta, entrarei em sua casa, e com ele cearei, e ele comigo.

[[v66-3-21]]

^<<v66-3-21,21>>^ Ao que vencer lhe concederei que se assente comigo no meu trono; assim como eu venci, e me assentei com meu Pai no seu trono.

[[v66-3-22]]

^<<v66-3-22,22>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas.

'''

xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[&#60; Capítulo Anterior] | <<v66-3-0,Topo>> | xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[Próximo Capítulo &#62;]