include::./index.adoc[]

[[v46-7-0]]
=== 1 Coríntios, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v46-7-1]]

^<<v46-7-1,1>>^ ORA, quanto às coisas , que me escrevestes, bom seria  que o homem não tocasse em mulher;

[[v46-7-2]]

^<<v46-7-2,2>>^ Mas, por causa da prostituição, cada um tenha a sua própria mulher, e cada uma tenha o seu próprio marido.

[[v46-7-3]]

^<<v46-7-3,3>>^ O marido pague à mulher a devida benevolência, e da mesma sorte a mulher ao marido.

[[v46-7-4]]

^<<v46-7-4,4>>^ A mulher não tem poder sobre o seu próprio corpo, mas tem-no o marido: e também da mesma maneira o marido não tem poder sobre o seu próprio corpo, mas tem-no a mulher.

[[v46-7-5]]

^<<v46-7-5,5>>^ Não vos defraudeis um ao outro, senão por consentimento mútuo por algum tempo, para vos aplicardes à oração: e depois ajuntai-vos outra vez, para que Satanás vos não tente pela vossa incontinência.

[[v46-7-6]]

^<<v46-7-6,6>>^ Digo, porém, isto como que por permissão e não por mandamento.

[[v46-7-7]]

^<<v46-7-7,7>>^ Porque quereria que todos os homens fossem como eu mesmo: mas cada um tem de Deus o seu próprio dom, um duma maneira e outro doutra.

[[v46-7-8]]

^<<v46-7-8,8>>^ Digo, porém, aos solteiros e às viúvas, que lhes é bom se ficarem como eu.

[[v46-7-9]]

^<<v46-7-9,9>>^ Mas, se não podem conter-se, casem-se. Porque é melhor casar do que abrasar-se.

[[v46-7-10]]

^<<v46-7-10,10>>^ Todavia, aos casados, mando, não eu mas o Senhor, que a mulher se não aparte do marido.

[[v46-7-11]]

^<<v46-7-11,11>>^ Se porém, se apartar, que fique sem casar, ou que se reconcilie com o marido; e que o marido não deixe a mulher.

[[v46-7-12]]

^<<v46-7-12,12>>^ Mas aos outros digo eu, não o Senhor: Se algum irmão tem mulher descrente, e ela consente em habitar com ele, não a deixe.

[[v46-7-13]]

^<<v46-7-13,13>>^ E se alguma mulher tem marido descrente, e ele consente em habitar com ela, não o deixe.

[[v46-7-14]]

^<<v46-7-14,14>>^ Porque o marido descrente é santificado pela mulher: e a mulher descrente é santificada pelo marido; doutra sorte os vossos filhos seriam imundos; mas agora são santos.

[[v46-7-15]]

^<<v46-7-15,15>>^ Mas, se o descrente se apartar, aparte-se; porque neste caso  o irmão, ou irmã, não está sujeito à servidão: mas Deus chamou-nos para a paz.

[[v46-7-16]]

^<<v46-7-16,16>>^ Porque, donde sabes, ó mulher, se salvarás teu marido? ou, donde sabes, ó marido, se salvarás tua mulher?

[[v46-7-17]]

^<<v46-7-17,17>>^ E assim cada um ande como Deus lhe repartiu, cada um como o Senhor o chamou. É o que ordeno em todas as igrejas.

[[v46-7-18]]

^<<v46-7-18,18>>^ É alguém chamado, estando circuncidado? fique circuncidado. É alguém chamado estando incircuncidado? não se circuncide.

[[v46-7-19]]

^<<v46-7-19,19>>^ A circuncisão é nada e a incircuncisão nada é, mas sim a observância dos mandamentos de Deus.

[[v46-7-20]]

^<<v46-7-20,20>>^ Cada um fique na vocação em que foi chamado.

[[v46-7-21]]

^<<v46-7-21,21>>^ Foste chamado sendo  servo? não te dê cuidado; e, se ainda podes ser livre, aproveita a ocasião.

[[v46-7-22]]

^<<v46-7-22,22>>^ Porque o que é chamado pelo Senhor, sendo  servo, é liberto do Senhor; e da mesma maneira também o que é chamado sendo  livre, servo é de Cristo.

[[v46-7-23]]

^<<v46-7-23,23>>^ Fostes comprados por bom preço; não vos façais servos dos homens.

[[v46-7-24]]

^<<v46-7-24,24>>^ Irmãos, cada um fique diante de Deus no estado em que foi chamado.

[[v46-7-25]]

^<<v46-7-25,25>>^ Ora, quanto às virgens, não tenho mandamento do Senhor; dou, porém, o meu  parecer, como quem tem alcançado misericórdia do Senhor para ser fiel.

[[v46-7-26]]

^<<v46-7-26,26>>^ Tenho pois por bom, por causa da instante necessidade, que é bom para o homem o estar assim.

[[v46-7-27]]

^<<v46-7-27,27>>^ Estás ligado à mulher? não busques separar-te. Estás livre de mulher? não busques mulher.

[[v46-7-28]]

^<<v46-7-28,28>>^ Mas, se te casares, não pecas; e, se a virgem se casar, não peca. Todavia os tais terão tribulações na carne, e eu quereria poupar-vos.

[[v46-7-29]]

^<<v46-7-29,29>>^ Isto, porém, vos digo, irmãos, que o tempo se abrevia; o que resta é que também os que têm mulheres sejam como se as não tivessem;

[[v46-7-30]]

^<<v46-7-30,30>>^ E os que choram, como se não chorassem: e os que folgam, como se não folgassem; e os que compram, como se não possuíssem;

[[v46-7-31]]

^<<v46-7-31,31>>^ E os que usam deste mundo, como se dele  não abusassem, porque a aparência deste mundo passa.

[[v46-7-32]]

^<<v46-7-32,32>>^ E bem quisera eu que estivésseis sem cuidado. O solteiro cuida nas coisas  do Senhor, em como há de agradar ao Senhor:

[[v46-7-33]]

^<<v46-7-33,33>>^ Mas o que é casado cuida nas coisas  do mundo, em como há de agradar à mulher.

[[v46-7-34]]

^<<v46-7-34,34>>^ Há diferença entre a mulher casada e a virgem: a solteira cuida nas coisas  do Senhor para ser santa, tanto no corpo como no espírito; porém a casada cuida nas coisas  do mundo, em como há de agradar ao marido.

[[v46-7-35]]

^<<v46-7-35,35>>^ E digo isto para proveito vosso; não para vos enlaçar, mas para o que é decente e conveniente, para vos unirdes ao Senhor sem distração alguma.

[[v46-7-36]]

^<<v46-7-36,36>>^ Mas, se alguém julga que trata dignamente a sua virgem, se tiver passado a flor da idade, e se for necessário, que faça o tal o que quiser; não peca; casem-se.

[[v46-7-37]]

^<<v46-7-37,37>>^ Todavia o que está firme em seu  coração, não tendo necessidade, mas com poder sobre a sua própria vontade, se resolveu no seu coração guardar a sua virgem, faz bem.

[[v46-7-38]]

^<<v46-7-38,38>>^ De sorte que, o que a  dá em casamento, faz bem; mas o que a  não dá em casamento faz melhor.

[[v46-7-39]]

^<<v46-7-39,39>>^ A mulher casada está ligada pela lei todo o tempo que o seu marido vive; mas, se falecer o seu marido fica livre para casar com quem quiser, contanto que seja  no Senhor.

[[v46-7-40]]

^<<v46-7-40,40>>^ Será, porém, mais bem-aventurada se ficar assim, segundo o meu parecer, e também eu cuido que tenho o Espírito de Deus.

'''

xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[&#60; Capítulo Anterior] | <<v46-7-0,Topo>> | xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[Próximo Capítulo &#62;]