include::./index.adoc[]

[[v46-8-0]]
=== 1 Coríntios, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v46-8-1]]

^<<v46-8-1,1>>^ ORA, no tocante às coisas sacrificadas aos ídolos, sabemos que todos temos ciência. A ciência incha, mas o amor edifica.

[[v46-8-2]]

^<<v46-8-2,2>>^ E, se alguém cuida saber alguma coisa , ainda não sabe como convém saber.

[[v46-8-3]]

^<<v46-8-3,3>>^ Mas, se alguém ama a Deus, esse é conhecido dele.

[[v46-8-4]]

^<<v46-8-4,4>>^ Assim que, quanto ao comer das coisas  sacrificadas aos ídolos, sabemos que o ídolo nada é  no mundo, e que não há outro Deus, senão um só.

[[v46-8-5]]

^<<v46-8-5,5>>^ Porque, ainda que haja também alguns  que se chamem deuses, quer no céu quer na terra (como há muitos deuses e muitos senhores),

[[v46-8-6]]

^<<v46-8-6,6>>^ Todavia para nós há um só Deus, o Pai, de quem é tudo e para quem nós vivemos; e um só Senhor, Jesus Cristo, pelo qual são todas as coisas , e nós por Ele.

[[v46-8-7]]

^<<v46-8-7,7>>^ Mas nem em todos há conhecimento; porque alguns até agora comem, no seu costume para com o ídolo, coisas  sacrificadas ao ídolo; e a sua consciência, sendo fraca fica contaminada.

[[v46-8-8]]

^<<v46-8-8,8>>^ Ora o manjar não nos faz agradáveis a Deus, porque, se comemos, nada temos de mais, e, se não comemos, nada nos falta.

[[v46-8-9]]

^<<v46-8-9,9>>^ Mas vede que essa liberdade não seja dalguma maneira escândalo para os fracos.

[[v46-8-10]]

^<<v46-8-10,10>>^ Porque, se alguém te vir a ti, que tens ciência, sentado à mesa no templo dos ídolos, não será a consciência do que é fraco induzida a comer das coisas  sacrificadas aos ídolos?

[[v46-8-11]]

^<<v46-8-11,11>>^ E pela tua ciência perecerá o irmão fraco, pelo qual Cristo morreu.

[[v46-8-12]]

^<<v46-8-12,12>>^ Ora, pecando assim contra os irmãos, e ferindo a sua fraca consciência, pecais contra Cristo.

[[v46-8-13]]

^<<v46-8-13,13>>^ Pelo que, se o manjar escandalizar a meu irmão, nunca mais comerei carne, para que meu irmão se não escandalize.

'''

xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[&#60; Capítulo Anterior] | <<v46-8-0,Topo>> | xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[Próximo Capítulo &#62;]