include::./index.adoc[]

[[v46-14-0]]
=== 1 Coríntios, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v46-14-1]]

^<<v46-14-1,1>>^ SEGUI a caridade, e procurai com zelo os dons  espirituais, mas principalmente o de profetizar.

[[v46-14-2]]

^<<v46-14-2,2>>^ Porque o que fala língua estranha  não fala aos homens, senão a Deus; porque ninguém o  entende, e em espírito fala de mistérios.

[[v46-14-3]]

^<<v46-14-3,3>>^ Mas o que profetiza fala aos homens para  edificação, exortação e consolação.

[[v46-14-4]]

^<<v46-14-4,4>>^ O que fala língua estranha  edifica-se a si mesmo, mas o que profetiza edifica a igreja.

[[v46-14-5]]

^<<v46-14-5,5>>^ E eu quero que todos vós faleis línguas estranhas , mas muito  mais que profetizeis, porque o que profetiza é maior do que o que fala línguas estranhas , a não ser que também interprete para que a igreja receba edificação.

[[v46-14-6]]

^<<v46-14-6,6>>^ E agora, irmãos, se eu for ter convosco falando línguas estranhas , que vos aproveitaria, se vos não falasse ou por meio da revelação, ou da ciência, ou da profecia, ou da doutrina?

[[v46-14-7]]

^<<v46-14-7,7>>^ Da mesma sorte, se as coisas  inanimadas, que fazem som, seja flauta, seja cítara, não formarem sons distintos, como se conhecerá o que se toca com a flauta ou com a cítara?

[[v46-14-8]]

^<<v46-14-8,8>>^ Porque, se a trombeta der sonido incerto, quem se preparará para a batalha?

[[v46-14-9]]

^<<v46-14-9,9>>^ Assim também vós, se com a língua não pronunciardes palavras bem inteligíveis, como se entenderá o que se diz? porque estareis como  que falando ao ar.

[[v46-14-10]]

^<<v46-14-10,10>>^ Há, por exemplo, tanta espécie de vozes no mundo, e nenhuma delas é  sem significação.

[[v46-14-11]]

^<<v46-14-11,11>>^ Mas, se eu ignorar o sentido da voz, serei bárbaro para aquele a quem falo, e o que fala será  bárbaro para mim.

[[v46-14-12]]

^<<v46-14-12,12>>^ Assim também vós, como desejais dons  espirituais, procurai abundar neles , para edificação da igreja.

[[v46-14-13]]

^<<v46-14-13,13>>^ Pelo que, o que fala língua estranha , ore para que a possa interpretar.

[[v46-14-14]]

^<<v46-14-14,14>>^ Porque, se eu orar em língua estranha , o meu espírito ora bem , mas o meu entendimento fica sem fruto.

[[v46-14-15]]

^<<v46-14-15,15>>^ Que farei pois? Orarei com o espírito, mas também orarei com o entendimento; cantarei com o espírito, mas também cantarei com o entendimento.

[[v46-14-16]]

^<<v46-14-16,16>>^ Doutra maneira, se tu bendisseres com o espírito, como dirá o que ocupa o lugar de indouto, o Amém, sobre a tua ação de graças, visto que não sabe o que dizes?

[[v46-14-17]]

^<<v46-14-17,17>>^ Porque realmente tu dás bem as graças, mas o outro não é edificado.

[[v46-14-18]]

^<<v46-14-18,18>>^ Dou graças ao meu Deus, porque falo mais línguas do que vós todos.

[[v46-14-19]]

^<<v46-14-19,19>>^ Todavia eu antes quero falar na igreja cinco palavras na minha própria inteligência, para que possa também instruir os outros, do que dez mil palavras em língua desconhecida.

[[v46-14-20]]

^<<v46-14-20,20>>^ Irmãos, não sejais meninos no entendimento, mas sede meninos na malícia, e adultos no entendimento.

[[v46-14-21]]

^<<v46-14-21,21>>^ Está escrito na lei: Por gente doutras línguas, e por outros lábios, falarei a este povo; e ainda assim me não ouvirão, diz o Senhor.

[[v46-14-22]]

^<<v46-14-22,22>>^ De sorte que as línguas são um sinal, não para os fiéis, mas para os infiéis; e a profecia não é sinal para os infiéis, mas para os fiéis.

[[v46-14-23]]

^<<v46-14-23,23>>^ Se pois toda a igreja se congregar num lugar, e todos falarem línguas estranhas , e entrarem indoutos ou infiéis, não dirão porventura que estais loucos?

[[v46-14-24]]

^<<v46-14-24,24>>^ Mas, se todos profetizarem, e algum indouto ou infiel entrar, de todos é convencido, de todos é julgado.

[[v46-14-25]]

^<<v46-14-25,25>>^ Os segredos do seu coração ficarão manifestos, e assim, lançando-se sobre o seu  rosto, adorará a Deus, publicando que Deus está verdadeiramente entre vós.

[[v46-14-26]]

^<<v46-14-26,26>>^ Que fareis pois, irmãos? Quando vos ajuntais, cada um de vós tem salmo, tem doutrina, tem revelação, tem língua, tem interpretação. Faça-se tudo para edificação.

[[v46-14-27]]

^<<v46-14-27,27>>^ E se alguém falar língua estranha, faça-se isso  por dois, ou quando muito três, e por sua vez, e haja intérprete.

[[v46-14-28]]

^<<v46-14-28,28>>^ Mas, se não houver intérprete, esteja calado na igreja, e fale consigo mesmo, e com Deus.

[[v46-14-29]]

^<<v46-14-29,29>>^ E falem dois ou três profetas, e os outros julguem.

[[v46-14-30]]

^<<v46-14-30,30>>^ Mas se a outro, que estiver assentado, for revelada alguma coisa , cale-se o primeiro.

[[v46-14-31]]

^<<v46-14-31,31>>^ Porque todos podereis profetizar, uns depois dos outros; para que todos aprendam, e todos sejam consolados.

[[v46-14-32]]

^<<v46-14-32,32>>^ E os espíritos dos profetas estão sujeitos aos profetas.

[[v46-14-33]]

^<<v46-14-33,33>>^ Porque Deus não é Deus  de confusão, senão de paz, como em todas as igrejas dos santos.

[[v46-14-34]]

^<<v46-14-34,34>>^ As mulheres estejam caladas nas igrejas; porque lhes não é permitido falar; mas estejam sujeitas, como também ordena a lei.

[[v46-14-35]]

^<<v46-14-35,35>>^ E, se querem aprender alguma coisa , interroguem em casa a seus próprios maridos; porque é indecente que as mulheres falem na igreja.

[[v46-14-36]]

^<<v46-14-36,36>>^ Porventura saiu dentre vós a palavra de Deus? Ou veio ela somente para vós?

[[v46-14-37]]

^<<v46-14-37,37>>^ Se alguém cuida ser profeta, ou espiritual, reconheça que as coisas  que vos escrevo são mandamentos do Senhor.

[[v46-14-38]]

^<<v46-14-38,38>>^ Mas, se alguém ignora isto, que ignore.

[[v46-14-39]]

^<<v46-14-39,39>>^ Portanto, irmãos, procurai, com zelo, profetizar, e não proibais falar línguas.

[[v46-14-40]]

^<<v46-14-40,40>>^ Mas  faça-se tudo decentemente e com ordem.

'''

xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[Próximo Capítulo &#62;]