include::./index.adoc[]

[[v46-2-0]]
=== 1 Coríntios, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v46-2-1]]

^<<v46-2-1,1>>^ E EU, irmãos, quando fui ter convosco, anunciando-vos o testemunho de Deus, não fui com sublimidade de palavras ou de sabedoria.

[[v46-2-2]]

^<<v46-2-2,2>>^ Porque nada me propus saber entre vós, senão a Jesus Cristo, e este crucificado.

[[v46-2-3]]

^<<v46-2-3,3>>^ E eu estive convosco em fraqueza, e em temor, e em grande tremor.

[[v46-2-4]]

^<<v46-2-4,4>>^ A minha palavra, e a minha pregação, não consistiu em palavras persuasivas de sabedoria humana, mas em demonstração de Espírito e de poder;

[[v46-2-5]]

^<<v46-2-5,5>>^ Para que a vossa fé não se apoiasse em sabedoria dos homens, mas no poder de Deus.

[[v46-2-6]]

^<<v46-2-6,6>>^ Todavia falamos sabedoria entre os perfeitos; não porém a sabedoria deste mundo, nem dos príncipes deste mundo que se aniquilam;

[[v46-2-7]]

^<<v46-2-7,7>>^ Mas falamos a sabedoria de Deus oculta em mistério, a qual Deus ordenou antes dos séculos para nossa glória;

[[v46-2-8]]

^<<v46-2-8,8>>^ A qual nenhum dos príncipes deste mundo conheceu; porque, se a conhecessem, nunca crucificariam ao Senhor da glória.

[[v46-2-9]]

^<<v46-2-9,9>>^ Mas, como está escrito: As coisas  que o olho não viu, e o ouvido não ouviu, e não subiram ao coração do homem, são  as que Deus preparou para os que o amam.

[[v46-2-10]]

^<<v46-2-10,10>>^ Mas Deus no-las revelou pelo seu Espírito; porque o Espírito penetra todas as coisas, ainda as profundezas de Deus.

[[v46-2-11]]

^<<v46-2-11,11>>^ Porque, qual dos homens sabe as coisas  do homem, senão o espírito do homem, que nele está? assim também ninguém sabe as coisas  de Deus, senão o Espírito de Deus.

[[v46-2-12]]

^<<v46-2-12,12>>^ Mas nós não recebemos o espírito do mundo, mas o Espírito que provém de Deus, para que pudéssemos conhecer o que nos é dado gratuitamente por Deus.

[[v46-2-13]]

^<<v46-2-13,13>>^ As quais também falamos, não com palavras de sabedoria humana, mas com as que o Espírito Santo ensina, comparando as coisas  espirituais com as espirituais.

[[v46-2-14]]

^<<v46-2-14,14>>^ Ora o homem natural não compreende as coisas  do Espírito de Deus, porque lhe parecem loucura; e não pode entendê-las, porque elas se discernem espiritualmente.

[[v46-2-15]]

^<<v46-2-15,15>>^ Mas o que é espiritual discerne bem tudo, e ele de ninguém é discernido.

[[v46-2-16]]

^<<v46-2-16,16>>^ Porque, quem conheceu a mente do Senhor, para que possa instruí-lo? Mas nós temos a mente de Cristo.

'''

xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[&#60; Capítulo Anterior] | <<v46-2-0,Topo>> | xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[Próximo Capítulo &#62;]