include::./index.adoc[]

[[v46-9-0]]
=== 1 Coríntios, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v46-9-1]]

^<<v46-9-1,1>>^ NÃO sou eu apóstolo? Não sou livre? Não vi eu a Jesus Cristo Senhor nosso? Não sois vós a minha obra no Senhor?

[[v46-9-2]]

^<<v46-9-2,2>>^ Se eu não sou apóstolo para os outros, ao menos o sou para vós; porque vós sois o selo do meu apostolado no Senhor.

[[v46-9-3]]

^<<v46-9-3,3>>^ Esta é a minha defesa para com os que me condenam.

[[v46-9-4]]

^<<v46-9-4,4>>^ Não temos nós direito de comer e de beber?

[[v46-9-5]]

^<<v46-9-5,5>>^ Não temos nós direito de levar conosco  uma mulher irmã, como também os demais apóstolos, e os irmãos do Senhor, e Cefas?

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou só eu e Barnabé não temos direito de deixar de trabalhar?

[[v46-9-7]]

^<<v46-9-7,7>>^ Quem jamais milita à sua própria custa? Quem planta a vinha e não come do seu fruto? Ou quem apascenta o gado e não come do leite do gado?

[[v46-9-8]]

^<<v46-9-8,8>>^ Digo eu isto segundo os homens? Ou não diz a lei também o mesmo?

[[v46-9-9]]

^<<v46-9-9,9>>^ Porque na lei de Moisés está escrito: Não atarás a boca ao boi que trilha o grão. Porventura tem Deus cuidado dos bois?

[[v46-9-10]]

^<<v46-9-10,10>>^ Ou não o diz certamente por nós? Certamente que por nós está escrito; porque o que lavra deve lavrar com esperança, e o que debulha deve debulhar com esperança de ser participante.

[[v46-9-11]]

^<<v46-9-11,11>>^ Se nós vos semeamos as coisas  espirituais, será muito que de vós recolhamos as carnais?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se outros participam deste poder sobre vós, por que  não, mais justamente, nós? Mas nós não usamos deste direito; antes suportamos tudo, para não pormos impedimento algum ao evangelho de Cristo.

[[v46-9-13]]

^<<v46-9-13,13>>^ Não sabeis vós que os que administram o que é sagrado comem do que é do templo? E que os que de contínuo estão junto ao altar, participam do altar?

[[v46-9-14]]

^<<v46-9-14,14>>^ Assim ordenou também o Senhor aos que anunciam o evangelho, que vivam do evangelho.

[[v46-9-15]]

^<<v46-9-15,15>>^ Mas eu de nenhuma destas coisas  usei, e não escrevi isto para que assim se faça comigo; porque melhor me fora  morrer, do que alguém fazer vã esta minha glória.

[[v46-9-16]]

^<<v46-9-16,16>>^ Porque, se anuncio o evangelho, não tenho de que me gloriar, pois me é imposta essa obrigação; e ai de mim, se não anunciar o evangelho!

[[v46-9-17]]

^<<v46-9-17,17>>^ E por isso, se o faço de boa mente, terei prêmio; mas, se de má vontade, apenas uma dispensação me é confiada.

[[v46-9-18]]

^<<v46-9-18,18>>^ Logo, que prêmio tenho? Que evangelizando, proponha de graça o evangelho de Cristo para não abusar do meu poder no evangelho.

[[v46-9-19]]

^<<v46-9-19,19>>^ Porque, sendo livre para com todos, fiz-me servo de todos para ganhar ainda mais.

[[v46-9-20]]

^<<v46-9-20,20>>^ E fiz-me como judeu para os judeus, para ganhar os judeus: para os que estão debaixo da lei, como se estivera debaixo da lei, para ganhar os que estão debaixo da lei.

[[v46-9-21]]

^<<v46-9-21,21>>^ Para os que estão sem lei, como se estivera sem lei (não estando sem lei para com Deus, mas debaixo da lei de Cristo), para ganhar os que estão sem lei.

[[v46-9-22]]

^<<v46-9-22,22>>^ Fiz-me como fraco para os fracos, para ganhar os fracos. Fiz-me tudo para todos, para por todos os meios chegar a salvar alguns.

[[v46-9-23]]

^<<v46-9-23,23>>^ E eu faço isto por causa do evangelho, para ser também participante dele.

[[v46-9-24]]

^<<v46-9-24,24>>^ Não sabeis vós que os que correm no estádio, todos, na verdade, correm, mas um só leva o prêmio? Correi de tal maneira que o alcanceis.

[[v46-9-25]]

^<<v46-9-25,25>>^ E todo aquele que luta de tudo se abstém; eles o fazem  para alcançar uma coroa corruptível, nós, porém, uma  incorruptível.

[[v46-9-26]]

^<<v46-9-26,26>>^ Pois eu assim corro, não como a coisa incerta: assim combato, não como batendo no ar.

[[v46-9-27]]

^<<v46-9-27,27>>^ Antes subjugo o meu corpo, e o reduzo à servidão, para que, pregando aos outros, eu mesmo não venha dalguma maneira a ficar reprovado.

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]