include::./index.adoc[]

[[v46-15-0]]
=== 1 Coríntios, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v46-15-1]]

^<<v46-15-1,1>>^ TAMBÉM vos notifico, irmãos, o evangelho que já  vos tenho anunciado; o qual também recebestes, e no qual também permaneceis.

[[v46-15-2]]

^<<v46-15-2,2>>^ Pelo qual também sois salvos se o retiverdes tal como vo-lo tenho anunciado; se não é que crestes em vão.

[[v46-15-3]]

^<<v46-15-3,3>>^ Porque primeiramente vos entreguei o que também recebi: que Cristo morreu por nossos pecados, segundo as Escrituras,

[[v46-15-4]]

^<<v46-15-4,4>>^ E que foi sepultado, e que ressuscitou ao terceiro dia, segundo as Escrituras,

[[v46-15-5]]

^<<v46-15-5,5>>^ E que foi visto por Cefas, e depois pelos doze.

[[v46-15-6]]

^<<v46-15-6,6>>^ Depois foi visto, uma vez, por mais de quinhentos irmãos, dos quais vive ainda a maior parte, mas alguns já dormem também.

[[v46-15-7]]

^<<v46-15-7,7>>^ Depois foi visto por Tiago, depois por todos os apóstolos.

[[v46-15-8]]

^<<v46-15-8,8>>^ E por derradeiro de todos me apareceu também a mim, como a um abortivo.

[[v46-15-9]]

^<<v46-15-9,9>>^ Porque eu sou o menor dos apóstolos, que não sou digno de ser chamado apóstolo, pois que persegui a igreja de Deus.

[[v46-15-10]]

^<<v46-15-10,10>>^ Mas pela graça de Deus sou o que sou; e a sua graça para comigo não foi vã, antes trabalhei muito mais do que todos eles; todavia não eu, mas a graça de Deus, que está comigo.

[[v46-15-11]]

^<<v46-15-11,11>>^ Então, ou seja eu ou sejam eles, assim pregamos e assim haveis crido.

[[v46-15-12]]

^<<v46-15-12,12>>^ Ora, se se prega que Cristo ressuscitou dos mortos, como dizem alguns dentre vós que não há ressurreição de mortos?

[[v46-15-13]]

^<<v46-15-13,13>>^ E, se não há ressurreição de mortos, também Cristo não ressuscitou.

[[v46-15-14]]

^<<v46-15-14,14>>^ E, se Cristo não ressuscitou logo é vã a nossa pregação, e também é vã a vossa fé.

[[v46-15-15]]

^<<v46-15-15,15>>^ E assim somos também considerados como falsas testemunhas de Deus, pois testificamos de Deus, que ressuscitou a Cristo, ao qual, porém, não ressuscitou, se, na verdade, os mortos não ressuscitam.

[[v46-15-16]]

^<<v46-15-16,16>>^ Porque, se os mortos não ressuscitam, também Cristo não ressuscitou.

[[v46-15-17]]

^<<v46-15-17,17>>^ E, se Cristo não ressuscitou, é  vã a vossa fé, e  ainda permaneceis nos vossos pecados.

[[v46-15-18]]

^<<v46-15-18,18>>^ E também os que dormiram em Cristo estão perdidos.

[[v46-15-19]]

^<<v46-15-19,19>>^ Se esperamos em Cristo só nesta vida, somos os mais miseráveis de todos os homens.

[[v46-15-20]]

^<<v46-15-20,20>>^ Mas agora Cristo ressuscitou dos mortos, e  foi feito as primícias dos que dormem.

[[v46-15-21]]

^<<v46-15-21,21>>^ Porque assim como a morte veio  por um homem, também a ressurreição dos mortos veio  por um homem.

[[v46-15-22]]

^<<v46-15-22,22>>^ Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo.

[[v46-15-23]]

^<<v46-15-23,23>>^ Mas cada um por sua ordem: Cristo as primícias, depois os que são de Cristo, na sua vinda.

[[v46-15-24]]

^<<v46-15-24,24>>^ Depois virá  o fim, quando tiver entregado o reino a Deus, ao Pai, e  quando houver aniquilado todo o império, e toda a potestade e força.

[[v46-15-25]]

^<<v46-15-25,25>>^ Porque convém que reine até que haja posto a todos os inimigos debaixo de seus pés.

[[v46-15-26]]

^<<v46-15-26,26>>^ Ora o último inimigo que  há de ser aniquilado é  a morte.

[[v46-15-27]]

^<<v46-15-27,27>>^ Porque todas as coisas  sujeitou debaixo de seus pés. Mas, quando diz que todas as coisas lhe  estão sujeitas, claro está que se excetua aquele que sujeitou todas as coisas.

[[v46-15-28]]

^<<v46-15-28,28>>^ E, quando todas as coisas  lhe estiverem sujeitas, então também o mesmo Filho se sujeitará àquele que todas as coisas  lhe sujeitou, para que Deus seja tudo em todos.

[[v46-15-29]]

^<<v46-15-29,29>>^ Doutra maneira, que farão os que se batizam pelos mortos, se absolutamente os mortos não ressuscitam? Por que se batizam eles então pelos mortos?

[[v46-15-30]]

^<<v46-15-30,30>>^ Por que estamos nós também a toda a hora em perigo?

[[v46-15-31]]

^<<v46-15-31,31>>^ Eu protesto que cada dia morro gloriando-me em vós, irmãos, por Cristo Jesus nosso Senhor.

[[v46-15-32]]

^<<v46-15-32,32>>^ Se, como homem, combati em Éfeso contra as bestas, que me aproveita isso, se os mortos não ressuscitam? Comamos e bebamos, que amanhã morreremos.

[[v46-15-33]]

^<<v46-15-33,33>>^ Não vos enganeis: as más conversações corrompem os bons costumes.

[[v46-15-34]]

^<<v46-15-34,34>>^ Vigiai justamente e não pequeis; porque alguns ainda não têm o conhecimento de Deus: digo- o  para vergonha vossa.

[[v46-15-35]]

^<<v46-15-35,35>>^ Mas alguém dirá: Como ressuscitarão os mortos? E com que corpo virão?

[[v46-15-36]]

^<<v46-15-36,36>>^ Insensato! o que tu semeias não é vivificado, se primeiro  não morrer.

[[v46-15-37]]

^<<v46-15-37,37>>^ E, quando semeias, não semeias o corpo que há de nascer, mas o simples grão, como de trigo, ou doutra qualquer semente.

[[v46-15-38]]

^<<v46-15-38,38>>^ Mas Deus dá-lhe o corpo como quer, e a cada semente o seu próprio corpo.

[[v46-15-39]]

^<<v46-15-39,39>>^ Nem toda a carne é uma mesma carne, mas uma é  a carne dos homens, e outra a carne dos animais, e outra a dos peixes, e outra a das aves.

[[v46-15-40]]

^<<v46-15-40,40>>^ E há  corpos celestes e corpos terrestres, mas uma é  a glória dos celestes e outra a dos terrestres.

[[v46-15-41]]

^<<v46-15-41,41>>^ Uma é  a glória do sol, e outra a glória da lua, e outra a glória das estrelas; porque uma  estrela difere em glória outra  estrela.

[[v46-15-42]]

^<<v46-15-42,42>>^ Assim também a ressurreição dos mortos. Semeia-se o corpo  em corrupção; ressuscitará em incorrupção.

[[v46-15-43]]

^<<v46-15-43,43>>^ Semeia-se em ignomínia, ressuscitará em glória. Semeia-se em fraqueza, ressuscitará com vigor.

[[v46-15-44]]

^<<v46-15-44,44>>^ Semeia-se corpo animal, ressuscitará corpo espiritual. Se há corpo animal, há também corpo espiritual.

[[v46-15-45]]

^<<v46-15-45,45>>^ Assim está também escrito: O primeiro homem, Adão, foi feito em alma vivente: o último Adão em espírito vivificante.

[[v46-15-46]]

^<<v46-15-46,46>>^ Mas não é  primeiro o espiritual, senão o animal; depois o espiritual.

[[v46-15-47]]

^<<v46-15-47,47>>^ O primeiro homem, da terra, é terreno; o segundo homem, o Senhor é do céu.

[[v46-15-48]]

^<<v46-15-48,48>>^ Qual o terreno, tais são também os terrenos; e, qual o celestial, tais também os celestiais.

[[v46-15-49]]

^<<v46-15-49,49>>^ E, assim como trouxemos a imagem do terreno, assim traremos também a imagem do celestial.

[[v46-15-50]]

^<<v46-15-50,50>>^ E agora digo isto, irmãos: que a carne e o sangue não podem herdar o reino de Deus, nem a corrupção herda a incorrupção.

[[v46-15-51]]

^<<v46-15-51,51>>^ Eis aqui vos digo um mistério: Na verdade, nem todos dormiremos, mas todos seremos transformados,

[[v46-15-52]]

^<<v46-15-52,52>>^ Num momento, num abrir e fechar de olhos, ante a última trombeta; porque a trombeta soará, e os mortos ressuscitarão incorruptíveis, e nós seremos transformados.

[[v46-15-53]]

^<<v46-15-53,53>>^ Porque convém que isto que é corruptível se revista da incorruptibilidade, e que isto que é mortal se revista da imortalidade.

[[v46-15-54]]

^<<v46-15-54,54>>^ E, quando isto que é corruptível se revestir da incorruptibilidade, e isto que é mortal se revestir da imortalidade, então cumprir-se-á a palavra que está escrita: Tragada foi a morte na vitória.

[[v46-15-55]]

^<<v46-15-55,55>>^ Onde está, ó morte, o teu aguilhão? Onde está, ó inferno, a tua vitória?

[[v46-15-56]]

^<<v46-15-56,56>>^ Ora o aguilhão da morte é o pecado, e a força do pecado é a lei.

[[v46-15-57]]

^<<v46-15-57,57>>^ Mas graças a Deus que nos dá a vitória por nosso Senhor Jesus Cristo.

[[v46-15-58]]

^<<v46-15-58,58>>^ Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.

'''

xref:046-1-corintios/046-1-corintios-014.adoc#v46-14-0[&#60; Capítulo Anterior] | <<v46-15-0,Topo>> | xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[Próximo Capítulo &#62;]