include::./index.adoc[]

[[v46-5-0]]
=== 1 Coríntios, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v46-5-1]]

^<<v46-5-1,1>>^ GERALMENTE se ouve que há  entre vós fornicação, e fornicação tal, qual nem ainda entre os gentios, como é haver quem abuse da mulher de seu pai.

[[v46-5-2]]

^<<v46-5-2,2>>^ Estais inchados, e nem ao menos vos entristecestes por não ter sido dentre vós tirado quem cometeu tal ação.

[[v46-5-3]]

^<<v46-5-3,3>>^ Eu na verdade, ainda que ausente no corpo, mas presente no espírito, já determinei, como se estivesse  presente que o que tal ato praticou,

[[v46-5-4]]

^<<v46-5-4,4>>^ Em nome de nosso Senhor Jesus Cristo, juntos vós e o meu espírito, pelo poder de nosso Senhor Jesus Cristo,

[[v46-5-5]]

^<<v46-5-5,5>>^ Seja entregue a Satanás para destruição da carne, para que o espírito seja salvo no dia do Senhor Jesus.

[[v46-5-6]]

^<<v46-5-6,6>>^ Não é boa a vossa jactância. Não sabeis que um pouco de fermento faz levedar toda a massa?

[[v46-5-7]]

^<<v46-5-7,7>>^ Alimpai-vos pois do fermento velho, para que sejais uma  nova massa, assim como estais sem fermento. Porque Cristo, nossa páscoa, foi sacrificado por nós.

[[v46-5-8]]

^<<v46-5-8,8>>^ Pelo que façamos festa, não com o fermento velho, nem com o fermento da maldade e da malícia, mas com os asmos da sinceridade e da verdade.

[[v46-5-9]]

^<<v46-5-9,9>>^ Já  por carta vos tenho escrito, que não vos associeis com os que se prostituem;

[[v46-5-10]]

^<<v46-5-10,10>>^ Isto não quer dizer absolutamente com os devassos deste mundo, ou com os avarentos, ou com os roubadores, ou com os idólatras; porque então vos seria necessário sair do mundo.

[[v46-5-11]]

^<<v46-5-11,11>>^ Mas agora vos escrevi que não vos associeis com aquele que, dizendo-se irmão, for devasso, ou avarento, ou idólatra, ou maldizente, ou beberrão, ou roubador; com o tal nem ainda comais.

[[v46-5-12]]

^<<v46-5-12,12>>^ Porque, que tenho eu em julgar também os que estão de fora? Não julgais vós os que estão dentro?

[[v46-5-13]]

^<<v46-5-13,13>>^ Mas Deus julga os que estão de fora. Tirai pois dentre vós a esse iníquo.

'''

xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[&#60; Capítulo Anterior] | <<v46-5-0,Topo>> | xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[Próximo Capítulo &#62;]