include::./index.adoc[]

[[v46-11-0]]
=== 1 Coríntios, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v46-11-1]]

^<<v46-11-1,1>>^ SEDE meus imitadores, como também eu de Cristo.

[[v46-11-2]]

^<<v46-11-2,2>>^ E louvo-vos irmãos, porque em tudo vos lembrais de mim, e retendes os preceitos como vo-los entreguei.

[[v46-11-3]]

^<<v46-11-3,3>>^ Mas quero que saibais que Cristo é a cabeça de todo o varão, e o varão a cabeça da mulher; e Deus a cabeça de Cristo.

[[v46-11-4]]

^<<v46-11-4,4>>^ Todo o homem que ora ou profetiza, tendo a cabeça coberta, desonra a sua própria cabeça.

[[v46-11-5]]

^<<v46-11-5,5>>^ Mas toda a mulher que ora ou profetiza com a cabeça descoberta, desonra a sua própria cabeça, porque é como se estivesse rapada.

[[v46-11-6]]

^<<v46-11-6,6>>^ Portanto, se a mulher não se cobre com véu, tosquie-se também. Mas, se para a mulher é coisa indecente tosquiar-se ou rapar-se, que ponha o véu.

[[v46-11-7]]

^<<v46-11-7,7>>^ O varão pois não deve cobrir a cabeça, porque é a imagem e glória de Deus, mas a mulher é a glória do varão.

[[v46-11-8]]

^<<v46-11-8,8>>^ Porque o varão não provém da mulher, mas a mulher do varão.

[[v46-11-9]]

^<<v46-11-9,9>>^ Porque também o varão não foi criado por causa da mulher, mas a mulher por causa do varão.

[[v46-11-10]]

^<<v46-11-10,10>>^ Portanto, a mulher deve ter sobre a cabeça sinal de  poderio, por causa dos anjos.

[[v46-11-11]]

^<<v46-11-11,11>>^ Todavia, nem o varão é  sem a mulher, nem a mulher sem o varão, no Senhor.

[[v46-11-12]]

^<<v46-11-12,12>>^ Porque, como a mulher provém  do varão, assim também o varão provém  da mulher, mas tudo vem de Deus.

[[v46-11-13]]

^<<v46-11-13,13>>^ Julgai entre vós mesmos: é decente que a mulher ore a Deus descoberta?

[[v46-11-14]]

^<<v46-11-14,14>>^ Ou não vos ensina a mesma natureza que é desonra para o varão ter cabelo crescido?

[[v46-11-15]]

^<<v46-11-15,15>>^ Mas ter a mulher cabelo crescido lhe é honroso, porque o cabelo lhe foi dado em lugar de véu.

[[v46-11-16]]

^<<v46-11-16,16>>^ Mas, se alguém quiser ser contencioso, nós não temos tal costume, nem as igrejas de Deus.

[[v46-11-17]]

^<<v46-11-17,17>>^ Nisto, porém, que vou dizer-vos não vos  louvo; porquanto vos ajuntais, não para melhor, senão para pior.

[[v46-11-18]]

^<<v46-11-18,18>>^ Porque antes de tudo ouço que, quando vos ajuntais na igreja, há entre vós dissensões; e em parte o creio.

[[v46-11-19]]

^<<v46-11-19,19>>^ E até importa que haja entre vós heresias, para que os que são sinceros se manifestem entre vós.

[[v46-11-20]]

^<<v46-11-20,20>>^ De sorte que, quando vos ajuntais num lugar, não é para comer a ceia do Senhor.

[[v46-11-21]]

^<<v46-11-21,21>>^ Porque, comendo, cada um toma antecipadamente a sua própria ceia; e assim um tem fome e outro embriaga-se.

[[v46-11-22]]

^<<v46-11-22,22>>^ Não tendes porventura casas para comer e para beber? Ou desprezais a igreja de Deus, e envergonhais os que nada têm? Que vos direi? Louvar-vos-ei? Nisto não vos  louvo.

[[v46-11-23]]

^<<v46-11-23,23>>^ Porque eu recebi do Senhor o que também vos ensinei: que o Senhor Jesus, na noite em que foi traído, tomou o pão;

[[v46-11-24]]

^<<v46-11-24,24>>^ E, tendo dado graças, o partiu e disse: Tomai, comei: isto é o meu corpo que é partido por vós; fazei isto em memória de mim.

[[v46-11-25]]

^<<v46-11-25,25>>^ Semelhantemente também, depois de cear, tomou  o cálice, dizendo: Este cálice é o Novo Testamento no meu sangue: fazei isto, todas as vezes que beberdes, em memória de mim.

[[v46-11-26]]

^<<v46-11-26,26>>^ Porque todas as vezes que comerdes este pão e beberdes este cálice anunciais a morte do Senhor, até que venha.

[[v46-11-27]]

^<<v46-11-27,27>>^ Portanto, qualquer que comer este  pão, ou beber o cálice do Senhor indignamente, será culpado do corpo e do sangue do Senhor.

[[v46-11-28]]

^<<v46-11-28,28>>^ Examine-se pois o homem a si mesmo, e assim coma deste pão e beba deste cálice.

[[v46-11-29]]

^<<v46-11-29,29>>^ Porque o que come e bebe indignamente, come e bebe para sua própria condenação, não discernindo o corpo do Senhor.

[[v46-11-30]]

^<<v46-11-30,30>>^ Por causa disto, há entre vós muitos fracos e doentes, e muitos que dormem.

[[v46-11-31]]

^<<v46-11-31,31>>^ Porque, se nós nos julgássemos a nós mesmos, não seríamos julgados.

[[v46-11-32]]

^<<v46-11-32,32>>^ Mas, quando somos julgados, somos repreendidos pelo Senhor, para não sermos condenados com o mundo.

[[v46-11-33]]

^<<v46-11-33,33>>^ Portanto, meus irmãos, quando vos ajuntais para comer, esperai uns pelos outros.

[[v46-11-34]]

^<<v46-11-34,34>>^ Mas, se algum tiver fome, coma em casa, para que vos não ajunteis para condenação. Quanto às demais coisas, ordená-las-ei quando for ter convosco.

'''

xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[Próximo Capítulo &#62;]