include::./index.adoc[]

[[v46-1-0]]
=== 1 Coríntios, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v46-1-1]]

^<<v46-1-1,1>>^ PAULO (chamado apóstolo de Jesus Cristo, pela vontade de Deus), e o irmão Sóstenes,

[[v46-1-2]]

^<<v46-1-2,2>>^ À igreja de Deus que está em Corinto, aos santificados em Cristo Jesus, chamados santos, com todos os que em todo o lugar invocam o nome de nosso Senhor Jesus Cristo, Senhor  deles e nosso:

[[v46-1-3]]

^<<v46-1-3,3>>^ Graça e paz da parte de Deus nosso Pai, e do Senhor Jesus Cristo.

[[v46-1-4]]

^<<v46-1-4,4>>^ Sempre dou graças ao meu Deus por vós pela graça de Deus que vos foi dada em Jesus Cristo.

[[v46-1-5]]

^<<v46-1-5,5>>^ Porque em tudo fostes enriquecidos nele, em toda a palavra e em todo o conhecimento.

[[v46-1-6]]

^<<v46-1-6,6>>^ (Como foi mesmo o testemunho de Cristo confirmado entre vós).

[[v46-1-7]]

^<<v46-1-7,7>>^ De maneira que nenhum dom vos falta, esperando a manifestação de nosso Senhor Jesus Cristo,

[[v46-1-8]]

^<<v46-1-8,8>>^ O qual vos confirmará também até ao fim, para serdes  irrepreensíveis no dia de nosso Senhor Jesus Cristo.

[[v46-1-9]]

^<<v46-1-9,9>>^ Fiel é  Deus, pelo qual fostes chamados para a comunhão de seu Filho Jesus Cristo nosso Senhor.

[[v46-1-10]]

^<<v46-1-10,10>>^ Rogo-vos, porém, irmãos, pelo nome de nosso Senhor Jesus Cristo, que digais todos uma mesma coisa , e que  não haja entre vós dissensões; antes sejais unidos em um mesmo sentido e em um mesmo parecer.

[[v46-1-11]]

^<<v46-1-11,11>>^ Porque a respeito de vós, irmãos meus, me foi comunicado pelos da família de Cloe que há contendas entre vós.

[[v46-1-12]]

^<<v46-1-12,12>>^ Quero dizer com isto, que cada um de vós diz: Eu sou de Paulo, e eu de Apolos, e eu de Cefas, e eu de Cristo.

[[v46-1-13]]

^<<v46-1-13,13>>^ Está Cristo dividido? foi Paulo crucificado por vós? ou fostes vós batizados em nome de Paulo?

[[v46-1-14]]

^<<v46-1-14,14>>^ Dou graças a Deus, porque a nenhum de vós batizei, senão a Crispo e a Gaio.

[[v46-1-15]]

^<<v46-1-15,15>>^ Para que ninguém diga que fostes batizados em meu nome.

[[v46-1-16]]

^<<v46-1-16,16>>^ E batizei também a família de Estéfanas; além destes, não sei se batizei algum outro.

[[v46-1-17]]

^<<v46-1-17,17>>^ Porque Cristo enviou-me, não para batizar, mas para evangelizar; não em sabedoria de palavras, para que a cruz de Cristo se não faça vã.

[[v46-1-18]]

^<<v46-1-18,18>>^ Porque a palavra da cruz é loucura para os que perecem; mas para nós, que somos salvos, é o poder de Deus.

[[v46-1-19]]

^<<v46-1-19,19>>^ Porque está escrito: Destruirei a sabedoria dos sábios, e aniquilarei a inteligência dos inteligentes.

[[v46-1-20]]

^<<v46-1-20,20>>^ Onde está o sábio? Onde está o escriba? Onde está o inquiridor deste século? Porventura não tornou Deus louca a sabedoria deste mundo?

[[v46-1-21]]

^<<v46-1-21,21>>^ Visto como na sabedoria de Deus o mundo não conheceu a Deus pela sua sabedoria, aprouve a Deus salvar os crentes pela loucura da pregação.

[[v46-1-22]]

^<<v46-1-22,22>>^ Porque os judeus pedem sinal, e os gregos buscam sabedoria;

[[v46-1-23]]

^<<v46-1-23,23>>^ Mas nós pregamos a Cristo crucificado, que é escândalo para os judeus, e loucura para os gregos.

[[v46-1-24]]

^<<v46-1-24,24>>^ Mas para os que são chamados, tanto judeus como gregos, lhes pregamos  a Cristo, poder de Deus, e sabedoria de Deus.

[[v46-1-25]]

^<<v46-1-25,25>>^ Porque a loucura de Deus é mais sábia do que os homens; e a fraqueza de Deus é mais forte do que os homens.

[[v46-1-26]]

^<<v46-1-26,26>>^ Porque, vede, irmãos, a vossa vocação, que não são muitos os sábios segundo a carne, nem muitos os poderosos, nem muitos os nobres que são chamados.

[[v46-1-27]]

^<<v46-1-27,27>>^ Mas Deus escolheu as coisas  loucas deste mundo para confundir as sábias; e Deus escolheu as coisas  fracas deste mundo para confundir as fortes.

[[v46-1-28]]

^<<v46-1-28,28>>^ E Deus escolheu as coisas  vis deste mundo, e as desprezíveis, e as que não são, para aniquilar as que são;

[[v46-1-29]]

^<<v46-1-29,29>>^ Para que nenhuma carne se glorie perante Ele.

[[v46-1-30]]

^<<v46-1-30,30>>^ Mas vós sois dele, em Jesus Cristo, o qual para nós foi feito por Deus sabedoria, e justiça, e santificação, e redenção;

[[v46-1-31]]

^<<v46-1-31,31>>^ Para que, como está escrito: Aquele que se gloria, glorie-se no Senhor.

'''

xref:045-romanos/045-romanos-016.adoc#v45-16-0[&#60; Capítulo Anterior] | <<v46-1-0,Topo>> | xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[Próximo Capítulo &#62;]