include::./index.adoc[]

[[v46-6-0]]
=== 1 Coríntios, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v46-6-1]]

^<<v46-6-1,1>>^ OUSA algum de vós, tendo algum  negócio contra outro, ir a juízo perante os injustos, e não perante os santos?

[[v46-6-2]]

^<<v46-6-2,2>>^ Não sabeis vós que os santos hão de julgar o mundo? Ora, se o mundo deve ser julgado por vós, sois porventura indignos de julgar as coisas mínimas?

[[v46-6-3]]

^<<v46-6-3,3>>^ Não sabeis vós que havemos de julgar os anjos? Quanto mais as coisas pertencentes a esta vida?

[[v46-6-4]]

^<<v46-6-4,4>>^ Então, se tiverdes negócios em juízo, pertencentes a esta vida, pondes na cadeira aos que são de menos estima na igreja?

[[v46-6-5]]

^<<v46-6-5,5>>^ Para vos envergonhar o digo: Não há pois entre vós sábios, nem mesmo um, que possa julgar entre seus irmãos?

[[v46-6-6]]

^<<v46-6-6,6>>^ Mas o irmão vai a juízo com o irmão, e isto perante infiéis.

[[v46-6-7]]

^<<v46-6-7,7>>^ Na verdade é já realmente uma  falta entre vós, terdes demandas uns contra os outros. Por que não sofreis antes a injustiça? Por que não sofreis antes o dano?

[[v46-6-8]]

^<<v46-6-8,8>>^ Mas vós mesmos  fazeis a injustiça e fazeis o dano: e isto aos irmãos.

[[v46-6-9]]

^<<v46-6-9,9>>^ Não sabeis que os injustos não hão de herdar o reino de Deus?

[[v46-6-10]]

^<<v46-6-10,10>>^ Não erreis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas, nem os ladrões, nem os avarentos, nem os bêbedos, nem os maldizentes, nem os roubadores herdarão o reino de Deus.

[[v46-6-11]]

^<<v46-6-11,11>>^ E é o que alguns têm sido, mas haveis sido lavados, mas haveis sido santificados, mas haveis sido justificados em nome do Senhor Jesus, e pelo Espírito do nosso Deus.

[[v46-6-12]]

^<<v46-6-12,12>>^ Todas as coisas  me são lícitas, mas nem todas as coisas convêm : todas as coisas  me são lícitas; mas eu não me deixarei dominar por nenhuma.

[[v46-6-13]]

^<<v46-6-13,13>>^ Os manjares são para o ventre e o ventre para os manjares; Deus porém, aniquilará, tanto um como os outros. Mas o corpo não é  para a prostituição, senão para o Senhor, e o Senhor para o corpo.

[[v46-6-14]]

^<<v46-6-14,14>>^ Ora Deus, que também ressuscitou o Senhor, nos ressuscitará a nós pelo seu poder.

[[v46-6-15]]

^<<v46-6-15,15>>^ Não sabeis vós que os vossos corpos são membros de Cristo? Tomarei pois os membros de Cristo, e fá-los-ei membros de uma meretriz? Não, por certo.

[[v46-6-16]]

^<<v46-6-16,16>>^ Ou não sabeis que o que se ajunta com a meretriz, faz-se um corpo com ela? Porque serão, disse, dois numa só carne.

[[v46-6-17]]

^<<v46-6-17,17>>^ Mas o que se ajunta com o Senhor é um mesmo  espírito.

[[v46-6-18]]

^<<v46-6-18,18>>^ Fugi da prostituição. Todo o pecado que o homem comete é fora do corpo; mas o que se prostitui peca contra o seu próprio corpo.

[[v46-6-19]]

^<<v46-6-19,19>>^ Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita  em vós, proveniente de Deus, e que não sois de vós mesmos?

[[v46-6-20]]

^<<v46-6-20,20>>^ Porque fostes comprados por bom preço; glorificai pois a Deus no vosso corpo, e no vosso espírito, os quais pertencem a Deus.

'''

xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[Próximo Capítulo &#62;]