include::./index.adoc[]

[[v9-18-0]]
=== 1 Samuel, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v9-18-1]]

^<<v9-18-1,1>>^ E SUCEDEU que, acabando ele de falar com Saul, a alma de Jônatas se ligou com a alma de Davi: e Jônatas o amou, como à sua própria  alma.

[[v9-18-2]]

^<<v9-18-2,2>>^ E Saul naquele dia o tomou, e não lhe permitiu que tornasse para casa de seu pai.

[[v9-18-3]]

^<<v9-18-3,3>>^ E Jônatas e Davi fizeram aliança: porque Jônatas  o amava como à sua própria  alma.

[[v9-18-4]]

^<<v9-18-4,4>>^ E Jônatas se despojou da capa que trazia  sobre si, e a deu a Davi, como  também os seus vestidos, até a sua espada, e o seu arco, e o seu cinto,

[[v9-18-5]]

^<<v9-18-5,5>>^ E saía Davi aonde quer que Saul o enviava, e conduzia-se com prudência, e Saul o pôs sobre a gente de guerra: e era aceito aos olhos de todo o povo, e até aos olhos dos servos de Saul.

[[v9-18-6]]

^<<v9-18-6,6>>^ Sucedeu porém que, vindo eles, quando Davi voltava de ferir os filisteus, as mulheres de todas as cidades de Israel saíram ao encontro do rei Saul, cantando, e em danças, com adufes, com alegria, e com instrumentos de música.

[[v9-18-7]]

^<<v9-18-7,7>>^ E as mulheres tangendo, se respondiam umas às outras , e diziam: Saul feriu os seus milhares, porém Davi os seus dez milhares.

[[v9-18-8]]

^<<v9-18-8,8>>^ Então Saul se indignou muito, e aquela palavra pareceu mal aos seus olhos, e disse: Dez milhares deram a Davi, e a mim somente  milhares: na verdade, que lhe falta, senão só o reino?

[[v9-18-9]]

^<<v9-18-9,9>>^ E, desde aquele dia em diante, Saul tinha Davi em suspeita.

[[v9-18-10]]

^<<v9-18-10,10>>^ E aconteceu ao outro dia que o mau espírito da parte  de Deus se apoderou de Saul, e profetizava no meio da casa: e Davi tangia a harpa com a sua mão, como de dia em dia: Saul porém, tinha  na mão uma  lança.

[[v9-18-11]]

^<<v9-18-11,11>>^ E Saul atirou com a lança, dizendo: Encravarei a Davi na parede. Porém Davi se desviou dele por  duas vezes.

[[v9-18-12]]

^<<v9-18-12,12>>^ E temia Saul a Davi, porque o Senhor era com ele e se tinha retirado de Saul.

[[v9-18-13]]

^<<v9-18-13,13>>^ Pelo que Saul o desviou de si, e o pôs por chefe de mil: e saía e entrava diante do povo.

[[v9-18-14]]

^<<v9-18-14,14>>^ E Davi se conduzia com prudência em todos os seus caminhos, e o Senhor era  com ele.

[[v9-18-15]]

^<<v9-18-15,15>>^ Vendo então Saul que tão prudentemente se conduzia, tinha receio dele.

[[v9-18-16]]

^<<v9-18-16,16>>^ Porém todo o Israel e Judá amava a Davi, porquanto saía e entrava diante deles.

[[v9-18-17]]

^<<v9-18-17,17>>^ Pelo que Saul disse a Davi: Eis que Merabe, minha filha mais velha, te darei por mulher; sê-me somente filho valoroso, e guerreia as guerras do Senhor (porque Saul dizia consigo : Não seja contra ele a minha mão, mas sim a dos filisteus).

[[v9-18-18]]

^<<v9-18-18,18>>^ Mas Davi disse a Saul: Quem sou  eu, e qual é  a minha vida e a família de meu pai em Israel, para vir a  ser genro do rei?

[[v9-18-19]]

^<<v9-18-19,19>>^ Sucedeu, porém, que ao tempo que Merabe, filha de Saul, devia ser dada a Davi, ela foi dada por mulher a Adriel, meolatita.

[[v9-18-20]]

^<<v9-18-20,20>>^ Mas Mical, a outra  filha de Saul amava a Davi: o que, sendo anunciado a Saul, pareceu isto bom aos seus olhos.

[[v9-18-21]]

^<<v9-18-21,21>>^ E Saul disse: Eu lha darei, para que lhe sirva de laço, e para que  a mão dos filisteus venha a ser  contra ele. Pelo que Saul disse a Davi: Com a outra serás hoje meu genro.

[[v9-18-22]]

^<<v9-18-22,22>>^ E Saul deu ordem aos seus servos: Falai em segredo a Davi, dizendo: Eis que o rei te está mui  afeiçoado, e todos os seus servos te amam; agora, pois, consente em  ser genro do rei.

[[v9-18-23]]

^<<v9-18-23,23>>^ E os servos de Saul falaram todas estas palavras aos ouvidos de Davi. Então disse Davi: Parece-vos pouco aos vossos olhos  ser genro do rei, sendo eu homem pobre e desprezível?

[[v9-18-24]]

^<<v9-18-24,24>>^ E os servos de Saul lhe anunciaram isto, dizendo: Foram  tais as palavras que falou Davi.

[[v9-18-25]]

^<<v9-18-25,25>>^ Então disse Saul: Assim direis a Davi: O rei não tem necessidade de dote, senão de cem prepúcios de filisteus, para se tomar vingança dos inimigos do rei. Porquanto Saul tentava fazer cair a Davi pela mão dos filisteus.

[[v9-18-26]]

^<<v9-18-26,26>>^ E anunciaram os seus servos estas palavras a Davi, e este negócio pareceu bem aos olhos de  Davi, de que fosse genro do rei: porém ainda  os dias se não haviam cumprido.

[[v9-18-27]]

^<<v9-18-27,27>>^ Então Davi se levantou, e partiu ele com os seus homens, e feriram dentre os filisteus duzentos homens, e Davi trouxe os seus prepúcios, e os entregaram todos ao rei para que fosse genro do rei: então Saul lhe deu por mulher a sua filha.

[[v9-18-28]]

^<<v9-18-28,28>>^ E viu Saul e notou que o Senhor era  com Davi: e Mical, filha de Saul, o amava.

[[v9-18-29]]

^<<v9-18-29,29>>^ Então Saul temeu muito mais a Davi: e Saul foi todos os seus  dias inimigo de Davi.

[[v9-18-30]]

^<<v9-18-30,30>>^ E, saindo os príncipes dos filisteus, sucedeu que, saindo eles, Davi se conduziu mais prudentemente do que todos os servos de Saul: portanto o seu nome era mui estimado.

'''

xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[&#60; Capítulo Anterior] | <<v9-18-0,Topo>> | xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[Próximo Capítulo &#62;]