include::./index.adoc[]

[[v9-29-0]]
=== 1 Samuel, 29
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v9-29-1]]

^<<v9-29-1,1>>^ E AJUNTARAM os filisteus todos os seus exércitos em Afeque: e acamparam-se os israelitas junto à fonte que está  em Jezreel.

[[v9-29-2]]

^<<v9-29-2,2>>^ E os príncipes dos filisteus se foram para lá com centenas e com milhares: porém Davi e os seus homens iam com Áquis na retaguarda.

[[v9-29-3]]

^<<v9-29-3,3>>^ Disseram então os príncipes dos filisteus: Que fazem  aqui estes hebreus? E disse Áquis aos príncipes dos filisteus: Não é  este Davi, o criado de Saul, rei de Israel, que esteve comigo há alguns dias ou anos? e cousa nenhuma achei nele desde o dia em que se revoltou, até ao dia de  hoje.

[[v9-29-4]]

^<<v9-29-4,4>>^ Porém os príncipes dos filisteus muito se indignaram contra ele; e disseram-lhe os príncipes dos filisteus: Faze voltar a este homem, e torne ao seu lugar em que tu o puseste, e não desça conosco à batalha, para que não se nos torne na batalha em adversário: porque com que aplacaria este a seu senhor? porventura  não seria  com as cabeças destes homens?

[[v9-29-5]]

^<<v9-29-5,5>>^ Não é  este aquele Davi, de quem uns aos outros  respondiam nas danças, dizendo: Saul feriu os seus milhares, porém Davi as suas dezenas de milhares?

[[v9-29-6]]

^<<v9-29-6,6>>^ Então Áquis chamou a Davi e disse-lhe: Vive o Senhor, que tu és reto, e que a tua entrada e a tua saída comigo no arraial é  boa aos meus olhos; porque nenhum mal em ti achei, desde o dia em que a mim vieste, até ao dia de  hoje; porém aos olhos dos príncipes não agradas.

[[v9-29-7]]

^<<v9-29-7,7>>^ Volta pois agora, e volta em paz: para que não faças mal aos olhos dos príncipes dos filisteus.

[[v9-29-8]]

^<<v9-29-8,8>>^ Então Davi disse a Áquis: Por quê? que fiz? ou que achaste no teu servo, desde o dia em que estive diante de ti, até ao dia de hoje, para que não vá e peleje contra os inimigos do rei meu senhor?

[[v9-29-9]]

^<<v9-29-9,9>>^ Respondeu porém Áquis, e disse a Davi: Bem  o sei: e  que na verdade  aos meus olhos és bom como um anjo de Deus: porém disseram os príncipes dos filisteus: Não suba este  conosco à batalha.

[[v9-29-10]]

^<<v9-29-10,10>>^ Agora pois amanhã de madrugada levanta-te com os criados de teu senhor, que têm vindo contigo: e, levantando-vos pela manhã de madrugada, e havendo luz, parti.

[[v9-29-11]]

^<<v9-29-11,11>>^ Então Davi de madrugada se levantou, ele e os seus homens, para partirem pela manhã, e voltarem à terra dos filisteus: e os filisteus subiram a Jezreel.

'''

xref:009-1-samuel/009-1-samuel-028.adoc#v9-28-0[&#60; Capítulo Anterior] | <<v9-29-0,Topo>> | xref:009-1-samuel/009-1-samuel-030.adoc#v9-30-0[Próximo Capítulo &#62;]