include::./index.adoc[]

[[v9-11-0]]
=== 1 Samuel, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v9-11-1]]

^<<v9-11-1,1>>^ ENTÃO subiu Naás, amonita, e sitiou a Jabes-Gileade: e disseram todos os homens de Jabes a Naás: Faze aliança conosco, e te serviremos.

[[v9-11-2]]

^<<v9-11-2,2>>^ Porém Naás, amonita, lhes disse: Com esta condição  farei aliança  convosco: que a todos vos arranque o olho direito, e assim  ponha esta afronta sobre todo o Israel.

[[v9-11-3]]

^<<v9-11-3,3>>^ Então os anciãos de Jabes lhe disseram: Deixa-nos por sete dias, para que enviemos mensageiros por todos os termos de Israel, e, não havendo ninguém que nos livre, então sairemos a ti.

[[v9-11-4]]

^<<v9-11-4,4>>^ E, vindo os mensageiros a Gibeá de Saul, falaram estas palavras aos  ouvidos do povo. Então todo o povo levantou a sua voz, e chorou.

[[v9-11-5]]

^<<v9-11-5,5>>^ E eis que Saul vinha do campo, atrás dos bois; e disse Saul: Que tem  o povo, que chora? E contaram-lhe as palavras dos homens de Jabes.

[[v9-11-6]]

^<<v9-11-6,6>>^ Então o espírito de Deus se apoderou de Saul, ouvindo estas palavras: e acendeu-se em grande maneira a sua ira.

[[v9-11-7]]

^<<v9-11-7,7>>^ E tomou um par de bois, e cortou-os em pedaços, e os  enviou a todos os termos de Israel pelas mãos dos mensageiros, dizendo: Qualquer que não sair atrás de Saul e atrás de Samuel, assim se fará aos seus bois. Então caiu o temor do Senhor sobre o povo, e saíram como um só  homem.

[[v9-11-8]]

^<<v9-11-8,8>>^ E contou-os em Bezeque: e houve dos filhos de Israel trezentos mil, e dos homens de Judá trinta mil.

[[v9-11-9]]

^<<v9-11-9,9>>^ Então disseram aos mensageiros que vieram: Assim direis aos homens de Jabes-Gileade: Amanhã em aquecendo o sol, vos virá livramento. Vindo pois os mensageiros, e anunciando- o  aos homens de Jabes, se alegraram.

[[v9-11-10]]

^<<v9-11-10,10>>^ E os homens de Jabes disseram: Amanhã sairemos a vós; então nos fareis conforme a tudo o que parece  bem aos vossos olhos.

[[v9-11-11]]

^<<v9-11-11,11>>^ E sucedeu que ao outro dia Saul pôs o povo em três companhias, e vieram ao meio do arraial pela vela da manhã, e feriram a Amom, até que o dia aqueceu: e sucedeu que os restantes se espalharam, que não ficaram dois deles juntos.

[[v9-11-12]]

^<<v9-11-12,12>>^ Então disse o povo a Samuel: Quem é  aquele que dizia que Saul não reinaria sobre nós? Dai cá  aqueles homens, e os mataremos.

[[v9-11-13]]

^<<v9-11-13,13>>^ Porém Saul disse: Hoje não morrerá nenhum, pois hoje tem obrado o Senhor um  livramento em Israel.

[[v9-11-14]]

^<<v9-11-14,14>>^ E disse Samuel ao povo: Vinde, vamos nós a Gilgal e renovemos ali o reino.

[[v9-11-15]]

^<<v9-11-15,15>>^ E todo o povo partiu para Gilgal, e levantaram ali rei a Saul perante o Senhor em Gilgal, e ofereceram ali ofertas pacíficas perante o Senhor: e Saul se alegrou muito ali com todos os homens de Israel.

'''

xref:009-1-samuel/009-1-samuel-010.adoc#v9-10-0[&#60; Capítulo Anterior] | <<v9-11-0,Topo>> | xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[Próximo Capítulo &#62;]