include::./index.adoc[]

[[v9-15-0]]
=== 1 Samuel, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v9-15-1]]

^<<v9-15-1,1>>^ ENTÃO disse Samuel a Saul: Enviou-me o Senhor a ungir-te rei sobre o seu povo, sobre Israel: ouve pois agora a voz das palavras do Senhor.

[[v9-15-2]]

^<<v9-15-2,2>>^ Assim diz o Senhor dos exércitos: Eu me recordei do que fez Amaleque a Israel; como se lhe opôs no caminho, quando subia do Egito.

[[v9-15-3]]

^<<v9-15-3,3>>^ Vai pois agora e fere a Amaleque; e destrói totalmente a tudo o que tiver, e não lhe perdoes; porém matarás desde o homem até à mulher, desde os meninos até aos de mama, desde os bois até às ovelhas, e  desde os camelos até aos jumentos.

[[v9-15-4]]

^<<v9-15-4,4>>^ E Saul convocou ao povo, e os contou em Teilaim, duzentos mil homens de pé, e dez mil homens de Judá.

[[v9-15-5]]

^<<v9-15-5,5>>^ Chegando pois Saul à cidade de Amaleque, pôs emboscada no vale.

[[v9-15-6]]

^<<v9-15-6,6>>^ E disse Saul aos queneus: Ide-vos, retirai-vos e  saí do meio dos amalequitas, para que vos não destrua juntamente com eles, porque vós usastes de misericórdia com todos os filhos de Israel, quando subiram do Egito. Assim os queneus se retiraram do meio dos amalequitas.

[[v9-15-7]]

^<<v9-15-7,7>>^ Então feriu Saul aos amalequitas desde Havilá até chegar a Sur que está  defronte do Egito.

[[v9-15-8]]

^<<v9-15-8,8>>^ E tomou vivo a Agague, rei dos amalequitas; porém a todo o povo destruiu ao fio da espada.

[[v9-15-9]]

^<<v9-15-9,9>>^ E Saul e o povo perdoaram a Agague, e ao melhor das ovelhas e das vacas, e às da segunda sorte, e aos cordeiros e ao melhor que havia, e não os quiseram destruir totalmente: porém a toda a cousa vil e desprezível destruíram totalmente.

[[v9-15-10]]

^<<v9-15-10,10>>^ Então veio a palavra do Senhor a Samuel, dizendo:

[[v9-15-11]]

^<<v9-15-11,11>>^ Arrependo-me de haver posto a Saul como rei; porquanto deixou de me seguir, e não executou as minhas palavras. Então Samuel se contristou, e toda a noite clamou ao Senhor.

[[v9-15-12]]

^<<v9-15-12,12>>^ E madrugou Samuel para encontrar a Saul pela manhã: e anunciou-se a Samuel, dizendo: Já chegou Saul ao Carmelo, e eis que levantou para si uma coluna. Então fez volta, e passou e desceu a Gilgal.

[[v9-15-13]]

^<<v9-15-13,13>>^ Veio pois Samuel a Saul; e Saul lhe disse: Bendito tu do Senhor; executei a palavra do Senhor.

[[v9-15-14]]

^<<v9-15-14,14>>^ Então disse Samuel: Que balido pois de ovelhas é  este nos meus ouvidos, e o mugido de vacas que ouço?

[[v9-15-15]]

^<<v9-15-15,15>>^ E disse Saul: De Amaleque as trouxeram; porque o povo perdoou ao melhor das ovelhas e das vacas, para as oferecer ao Senhor teu Deus: o resto porém temos destruído totalmente.

[[v9-15-16]]

^<<v9-15-16,16>>^ Então disse Samuel a Saul: Espera, e te declararei o que o Senhor me disse esta noite. E ele disse-lhe: Fala.

[[v9-15-17]]

^<<v9-15-17,17>>^ E disse Samuel: Porventura , sendo tu pequeno aos teus olhos, não foste  por cabeça das tribos de Israel? e o Senhor te ungiu rei sobre Israel.

[[v9-15-18]]

^<<v9-15-18,18>>^ E enviou-te o Senhor a este  caminho, e disse: Vai, e destrói totalmente a estes pecadores, os amalequitas, e peleja contra eles, até que os aniquiles.

[[v9-15-19]]

^<<v9-15-19,19>>^ Por que pois não deste ouvidos à voz do Senhor, antes voaste ao despojo, e fizeste o que parecia  mal aos olhos do Senhor?

[[v9-15-20]]

^<<v9-15-20,20>>^ Então disse Saul a Samuel: Antes dei ouvidos à voz do Senhor, e caminhei no caminho pelo qual o Senhor me enviou; e trouxe a Agague, rei de Amaleque, e os amalequitas destruí totalmente;

[[v9-15-21]]

^<<v9-15-21,21>>^ Mas o povo tomou do despojo ovelhas e vacas, o melhor do interdito, para oferecer ao Senhor teu Deus em Gilgal.

[[v9-15-22]]

^<<v9-15-22,22>>^ Porém Samuel disse: Tem porventura  o Senhor tanto  prazer em holocaustos e sacrifícios, como em que se obedeça à palavra do Senhor? eis que o obedecer é  melhor do que o sacrificar; e o atender melhor é  do que a gordura de carneiros.

[[v9-15-23]]

^<<v9-15-23,23>>^ Porque a rebelião é como  o pecado de feitiçaria, e o porfiar é como  iniquidade e idolatria. Porquanto tu rejeitaste a palavra do Senhor, ele também te rejeitou a ti, para que não sejas rei.

[[v9-15-24]]

^<<v9-15-24,24>>^ Então disse Saul a Samuel: Pequei porquanto tenho traspassado o dito do Senhor e as tuas palavras: porque temi ao povo e dei ouvidos à sua voz.

[[v9-15-25]]

^<<v9-15-25,25>>^ Agora pois, te  rogo, perdoa- me  o meu pecado: e volta comigo, para que adore ao Senhor.

[[v9-15-26]]

^<<v9-15-26,26>>^ Porém Samuel disse a Saul: Não tornarei contigo: porquanto rejeitaste a palavra do Senhor, já te rejeitou o Senhor, para que não sejas rei sobre Israel.

[[v9-15-27]]

^<<v9-15-27,27>>^ E virando-se Samuel para se ir, ele lhe pegou pela borda da capa, e a rasgou.

[[v9-15-28]]

^<<v9-15-28,28>>^ Então Samuel lhe disse: O Senhor tem rasgado de ti hoje o reino de Israel, e o tem dado ao teu próximo, melhor do que tu.

[[v9-15-29]]

^<<v9-15-29,29>>^ E também aquele que é a Força de Israel não mente nem se arrepende: porquanto não é um  homem para que se arrependa.

[[v9-15-30]]

^<<v9-15-30,30>>^ Disse ele então: Pequei; honra-me porém agora diante dos anciãos do meu povo, e diante de Israel: e volta comigo, para que adore ao Senhor teu Deus.

[[v9-15-31]]

^<<v9-15-31,31>>^ Então Samuel se tornou atrás de Saul: e Saul adorou ao Senhor.

[[v9-15-32]]

^<<v9-15-32,32>>^ Então disse Samuel: Trazei-me aqui a Agague, rei dos amalequitas. E Agague veio a ele animosamente; e disse Agague: Na verdade já passou a amargura da morte.

[[v9-15-33]]

^<<v9-15-33,33>>^ Disse porém Samuel: Assim  como a tua espada desfilhou as mulheres, assim ficará desfilhada a tua mãe entre as mulheres. Então Samuel despedaçou Agague perante o Senhor em Gilgal.

[[v9-15-34]]

^<<v9-15-34,34>>^ Então Samuel se foi a Ramá: e Saul subiu a sua casa, a Gibeá de Saul.

[[v9-15-35]]

^<<v9-15-35,35>>^ E nunca mais viu Samuel a Saul até ao dia da sua morte; porque Samuel teve dó de Saul. E o Senhor se arrependeu de que pusera a Saul rei sobre Israel.

'''

xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[&#60; Capítulo Anterior] | <<v9-15-0,Topo>> | xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[Próximo Capítulo &#62;]