include::./index.adoc[]

[[v9-1-0]]
=== 1 Samuel, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v9-1-1]]

^<<v9-1-1,1>>^ HOUVE um homem de Ramataim de Zofim, da montanha de Efraim, cujo nome era  Elcana, filho de Jeroão, filho de Eliú, filho de Toú, filho de Sufe, efrateu.

[[v9-1-2]]

^<<v9-1-2,2>>^ E este tinha duas mulheres: o nome duma era  Ana, e o nome da outra Penina: e Penina tinha filhos, porém Ana não tinha filhos.

[[v9-1-3]]

^<<v9-1-3,3>>^ Subia pois este homem da sua cidade de ano em ano a adorar e a sacrificar ao Senhor dos Exércitos em Silo: e estavam  ali os sacerdotes em Silo: e estavam ali os sacerdotes do Senhor, Hofni e Fineias, os dois filhos de Eli.

[[v9-1-4]]

^<<v9-1-4,4>>^ E sucedeu que  no dia em que Elcana sacrificava dava ele porções a Penina, sua mulher, e a todos os seus filhos, e a todas as suas filhas.

[[v9-1-5]]

^<<v9-1-5,5>>^ Porém a Ana dava uma parte excelente; porquanto ele amava Ana, porém o Senhor lhe tinha cerrado a madre.

[[v9-1-6]]

^<<v9-1-6,6>>^ E a sua competidora excessivamente a irritava para a embravecer: porquanto o Senhor lhe tinha cerrado a madre.

[[v9-1-7]]

^<<v9-1-7,7>>^ E assim o fazia ele  de ano em ano: quando ela subia à casa do Senhor, assim a outra  a irritava: pelo que chorava, e não comia.

[[v9-1-8]]

^<<v9-1-8,8>>^ Então Elcana, seu marido, lhe disse: Ana por que choras? e por que não comes? e por que está mal o teu coração? não te sou  eu melhor do que dez filhos?

[[v9-1-9]]

^<<v9-1-9,9>>^ Então Ana se levantou, depois que comeram e beberam em Silo; e Eli, sacerdote, estava assentado numa  cadeira, junto a um pilar do templo do Senhor.

[[v9-1-10]]

^<<v9-1-10,10>>^ Ela pois, com amargura de alma, orou ao Senhor, e chorou abundantemente.

[[v9-1-11]]

^<<v9-1-11,11>>^ E votou um  voto, dizendo: Senhor dos exércitos! se benignamente atenderes para a aflição da tua serva, e de mim te lembrares, e da tua serva te não esqueceres, mas à tua serva deres um  filho varão, ao Senhor o darei por todos os dias da sua vida, e sobre a sua cabeça não passará navalha.

[[v9-1-12]]

^<<v9-1-12,12>>^ E sucedeu que, perseverando ela em orar perante o Senhor, Eli fez atenção à sua boca.

[[v9-1-13]]

^<<v9-1-13,13>>^ Porquanto Ana no seu coração falava, só se moviam os seus beiços, porém não se ouvia a sua voz: pelo que Eli a teve por embriagada.

[[v9-1-14]]

^<<v9-1-14,14>>^ E disse-lhe Eli: Até quando estarás tu embriagada? Aparta de ti o teu vinho.

[[v9-1-15]]

^<<v9-1-15,15>>^ Porém Ana respondeu, e disse: Não, senhor meu, eu sou uma  mulher atribulada de espírito; nem vinho nem bebida forte tenho bebido: porém tenho derramado a minha alma perante o Senhor.

[[v9-1-16]]

^<<v9-1-16,16>>^ Não tenhas pois  a tua serva por filha de Belial: porque da multidão dos meus cuidados e do meu desgosto tenho falado até agora.

[[v9-1-17]]

^<<v9-1-17,17>>^ Então respondeu Eli, e disse: Vai em paz: e o Deus de Israel te  conceda a tua petição que lhe pediste.

[[v9-1-18]]

^<<v9-1-18,18>>^ E disse ela: Ache a tua serva graça em teus olhos. Assim a mulher se foi seu caminho, e comeu, e o seu semblante já não era triste.

[[v9-1-19]]

^<<v9-1-19,19>>^ E levantaram-se de madrugada, e adoraram perante o Senhor, e voltaram, e vieram à sua casa, a Ramá, e Elcana conheceu a Ana, sua mulher, e o Senhor se lembrou dela.

[[v9-1-20]]

^<<v9-1-20,20>>^ E sucedeu que, passado algum  tempo, Ana concebeu, e teve um  filho, e chamou o seu nome Samuel; porque dizia ela , o tenho pedido ao Senhor.

[[v9-1-21]]

^<<v9-1-21,21>>^ E subiu aquele homem Elcana com toda a sua casa, a sacrificar ao Senhor o sacrifício anual e a cumprir  o seu voto.

[[v9-1-22]]

^<<v9-1-22,22>>^ Porém Ana não subiu; mas disse a seu marido: Quando o menino for desmamado, então  o levarei, para que apareça perante o Senhor, e lá fique para sempre.

[[v9-1-23]]

^<<v9-1-23,23>>^ E Elcana, seu marido, lhe disse: Faze o que bem te parecer  em teus olhos, fica até que o desmames; tão somente confirme o Senhor a sua palavra: assim ficou a mulher, e deu leite a seu filho, até que o desmamou.

[[v9-1-24]]

^<<v9-1-24,24>>^ E, havendo-o desmamado, o levou consigo, com três bezerros, e um efa de farinha, e um odre de vinho, e o trouxe à casa do Senhor, a Silo, e era  o menino ainda muito  criança.

[[v9-1-25]]

^<<v9-1-25,25>>^ E degolaram um bezerro: e assim  trouxeram o menino a Eli.

[[v9-1-26]]

^<<v9-1-26,26>>^ E disse ela: Ah! meu senhor, viva a tua alma, meu senhor; eu sou aquela mulher que aqui esteve contigo, para orar ao Senhor.

[[v9-1-27]]

^<<v9-1-27,27>>^ Por este menino orava eu; e o Senhor me concedeu a minha petição, que eu lhe tinha pedido.

[[v9-1-28]]

^<<v9-1-28,28>>^ Pelo que também ao Senhor eu o entreguei, por todos os dias que viver: pois  ao Senhor foi pedido. E ele adorou ali ao Senhor.

'''

xref:008-rute/008-rute-004.adoc#v8-4-0[&#60; Capítulo Anterior] | <<v9-1-0,Topo>> | xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[Próximo Capítulo &#62;]