include::./index.adoc[]

[[v9-5-0]]
=== 1 Samuel, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v9-5-1]]

^<<v9-5-1,1>>^ OS filisteus pois tomaram a arca de Deus, e a trouxeram de Ebenézer, a Asdode.

[[v9-5-2]]

^<<v9-5-2,2>>^ E tomaram os filisteus a arca de Deus, e a meteram na casa de Dagom, e a puseram junto a Dagom.

[[v9-5-3]]

^<<v9-5-3,3>>^ Levantando-se porém de madrugada os de Asdode, no dia seguinte, eis que Dagom estava  caído com o rosto em terra diante da arca do Senhor: e tomaram a Dagom, e tornaram a pô-lo no seu lugar.

[[v9-5-4]]

^<<v9-5-4,4>>^ E, levantando-se de madrugada no dia seguinte pela manhã, eis que Dagom jazia caído com o rosto em terra diante da arca do Senhor; e a cabeça de Dagom e ambas as palmas das suas mãos cortadas sobre o limiar; somente o tronco  ficou a Dagom.

[[v9-5-5]]

^<<v9-5-5,5>>^ Pelo que nem os sacerdotes de Dagom, nem nenhum de  todos os que entram na casa de Dagom pisam o limiar de Dagom em Asdode, até ao dia de  hoje.

[[v9-5-6]]

^<<v9-5-6,6>>^ Porém a mão do Senhor se agravou sobre os de Asdode, e os assolou: e os feriu com hemorroidas, a Asdode e aos seus termos.

[[v9-5-7]]

^<<v9-5-7,7>>^ Vendo então os homens de Asdode que assim era, disseram: Não fique conosco a arca do Deus de Israel; pois a sua mão é dura sobre nós, e sobre Dagom, nosso deus.

[[v9-5-8]]

^<<v9-5-8,8>>^ Pelo que enviaram e congregaram a si todos os príncipes dos filisteus, e disseram: Que faremos nós da arca do Deus de Israel? E responderam: A arca do Deus de Israel dará volta a Gate. Assim a rodearam com  a arca do Deus de Israel.

[[v9-5-9]]

^<<v9-5-9,9>>^ E sucedeu que , desde que a rodearam com ela, a mão do Senhor veio contra aquela cidade, com mui grande vexação: pois feriu aos homens daquela cidade, desde o pequeno até ao grande: e tinham hemorroidas nas partes secretas.

[[v9-5-10]]

^<<v9-5-10,10>>^ Então enviaram a arca de Deus a Ecrom. Sucedeu porém que, vindo a arca de Deus a Ecrom, os de Ecrom exclamaram, dizendo: Transportaram para mim a arca do Deus de Israel, para me matarem, a mim e ao meu povo.

[[v9-5-11]]

^<<v9-5-11,11>>^ E enviaram, e congregaram a todos os príncipes dos filisteus, e disseram: Enviai a arca do Deus de Israel, e torne para o seu lugar, para que não mate nem a mim nem ao meu povo. Porque havia mortal vexação em toda a cidade, e  a mão de Deus muito se agravara ali.

[[v9-5-12]]

^<<v9-5-12,12>>^ E os homens que não morriam eram tão  feridos com hemorroidas que o clamor da cidade subia até o céu.

'''

xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[&#60; Capítulo Anterior] | <<v9-5-0,Topo>> | xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[Próximo Capítulo &#62;]