include::./index.adoc[]

[[v9-28-0]]
=== 1 Samuel, 28
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v9-28-1]]

^<<v9-28-1,1>>^ E SUCEDEU naqueles dias que, juntando os filisteus os seus exércitos para a peleja, para fazer guerra contra Israel, disse Áquis a Davi: Sabe de certo que comigo sairás ao arraial, tu e os teus homens.

[[v9-28-2]]

^<<v9-28-2,2>>^ Então disse Davi a Áquis: Assim saberás tu o que fará o teu servo. E disse Áquis a Davi: Por isso te terei por guarda da minha cabeça para sempre.

[[v9-28-3]]

^<<v9-28-3,3>>^ E já Samuel era morto, e todo o Israel o tinha chorado, e o tinha sepultado em Ramá, que era  a sua cidade; e Saul tinha desterrado os adivinhos e os encantadores.

[[v9-28-4]]

^<<v9-28-4,4>>^ E ajuntaram-se os filisteus, e vieram, e acamparam-se em Suném: e ajuntou Saul a todo o Israel, e se acamparam em Gilboa.

[[v9-28-5]]

^<<v9-28-5,5>>^ E, vendo Saul o arraial dos filisteus, temeu, e estremeceu muito o seu coração.

[[v9-28-6]]

^<<v9-28-6,6>>^ E perguntou Saul ao Senhor, porém o Senhor lhe não respondeu, nem por sonhos, nem por Urim, nem por profetas.

[[v9-28-7]]

^<<v9-28-7,7>>^ Então disse Saul aos seus criados: Buscai-me uma mulher que tenha o espírito de feiticeira, para que vá a ela e a consulte. E os seus criados lhe disseram: Eis que em Endor há  uma mulher que tem o espírito de adivinhar.

[[v9-28-8]]

^<<v9-28-8,8>>^ E Saul se disfarçou e vestiu outros vestidos, e foi ele e com ele dois homens, e de noite vieram à mulher; e disse: Peço- te  que me adivinhes pelo espírito de feiticeira, e me faças subir a quem eu te disser.

[[v9-28-9]]

^<<v9-28-9,9>>^ Então a mulher lhe disse: Eis aqui tu sabes o que Saul fez, como tem destruído da terra os adivinhos e os encantadores: por que, pois, me armas um laço à minha vida, para me fazer matar?

[[v9-28-10]]

^<<v9-28-10,10>>^ Então Saul lhe jurou pelo Senhor, dizendo: Vive o Senhor, que nenhum mal te sobrevirá por isso.

[[v9-28-11]]

^<<v9-28-11,11>>^ A mulher então lhe disse: A quem te farei subir? E disse ele: Faze-me subir a Samuel.

[[v9-28-12]]

^<<v9-28-12,12>>^ Vendo pois a mulher a Samuel, gritou em alta voz; e a mulher falou a Saul, dizendo: Por que me tens enganado? pois tu mesmo és  Saul.

[[v9-28-13]]

^<<v9-28-13,13>>^ E o rei lhe disse: Não temas: porém que é  o que vês? Então a mulher disse a Saul: Vejo deuses que sobem da terra.

[[v9-28-14]]

^<<v9-28-14,14>>^ E lhe disse: Como é  a sua figura? E disse ela: Vem subindo um homem ancião, e está envolto numa capa. Entendendo Saul que era Samuel, inclinou-se com o rosto em terra, e se prostrou.

[[v9-28-15]]

^<<v9-28-15,15>>^ Samuel disse a Saul: Por que me desinquietaste, fazendo-me subir? Então disse Saul: Mui angustiado estou, porque os filisteus guerreiam contra mim, e Deus se tem desviado de mim, e não me responde mais, nem pelo ministério dos profetas, nem por sonhos; por isso te chamei a ti, para que me faças saber o que hei de fazer.

[[v9-28-16]]

^<<v9-28-16,16>>^ Então disse Samuel: Por que pois a mim me perguntas, visto que o Senhor te tem desamparado, e se tem feito teu inimigo?

[[v9-28-17]]

^<<v9-28-17,17>>^ Porque o Senhor tem feito para contigo como pela minha boca te disse, e tem rasgado o reino da tua mão, e o tem dado ao teu companheiro Davi.

[[v9-28-18]]

^<<v9-28-18,18>>^ Como tu não deste ouvidos à voz do Senhor, e não executaste o fervor da sua ira contra Amaleque, por isso o Senhor te fez hoje isto.

[[v9-28-19]]

^<<v9-28-19,19>>^ E o Senhor entregará também a Israel contigo na mão dos filisteus, e amanhã tu e teus filhos estareis  comigo; e o arraial de Israel o Senhor entregará na mão dos filisteus.

[[v9-28-20]]

^<<v9-28-20,20>>^ E imediatamente Saul caiu estendido por terra, e grandemente temeu por causa daquelas palavras de Samuel: e não houve força nele; porque não tinha comido pão todo aquele dia e toda aquela noite.

[[v9-28-21]]

^<<v9-28-21,21>>^ Então veio a mulher a Saul, e vendo que estava tão perturbado, disse-lhe: Eis que deu ouvidos a tua criada à tua voz, e pus a minha vida na minha mão, e ouvi as palavras que disseste.

[[v9-28-22]]

^<<v9-28-22,22>>^ Agora pois ouve também tu as palavras da tua serva, e porei um bocado de pão diante de ti, e come, para que tenhas forças para te pores a caminho.

[[v9-28-23]]

^<<v9-28-23,23>>^ Porém ele o  recusou, e disse: Não comerei. Porém os seus criados e a mulher o constrangeram; e deu ouvidos à sua voz: e levantou-se do chão, e se assentou sobre uma cama.

[[v9-28-24]]

^<<v9-28-24,24>>^ E tinha a mulher em casa uma bezerra cevada, e se apressou, e a degolou, e tomou farinha, e a amassou, e a cozeu em bolos  asmos.

[[v9-28-25]]

^<<v9-28-25,25>>^ E os trouxe diante de Saul e de seus criados, e comeram: depois levantaram-se e se foram naquela mesma noite.

'''

xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[&#60; Capítulo Anterior] | <<v9-28-0,Topo>> | xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[Próximo Capítulo &#62;]