include::./index.adoc[]

[[v9-20-0]]
=== 1 Samuel, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v9-20-1]]

^<<v9-20-1,1>>^ ENTÃO fugiu Davi de Naiote, em Ramá: e veio, e disse perante Jônatas: Que fiz eu? qual é  o meu crime? e qual é  o meu pecado diante de teu pai, que procura tirar-me a vida?

[[v9-20-2]]

^<<v9-20-2,2>>^ E ele  lhe disse: Tal não seja: não morrerás; eis que meu pai não faz cousa nenhuma grande, nem pequena, sem primeiro me dar parte; porque pois meu pai me encobriria este negócio? não é assim.

[[v9-20-3]]

^<<v9-20-3,3>>^ Então Davi tornou a jurar, e disse: Mui bem sabe teu pai que achei graça em teus olhos; pelo que disse: Não saiba isto Jônatas, para que se não magoe; e, na verdade, vive o Senhor, e vive a tua alma, que apenas há  um passo entre mim e a morte.

[[v9-20-4]]

^<<v9-20-4,4>>^ E disse Jônatas a Davi: O que disser a tua alma, eu te farei.

[[v9-20-5]]

^<<v9-20-5,5>>^ Disse Davi a Jônatas: Eis que amanhã é  a lua nova, em que costumo assentar-me com o rei para comer: deixa-me tu ir, porém, e esconder-me-ei no campo, até à terceira tarde.

[[v9-20-6]]

^<<v9-20-6,6>>^ Se teu pai notar a minha ausência, dirás: Davi me pediu muito que o deixasse ir correndo a Belém, sua cidade: porquanto se faz  lá o sacrifício anual para toda a linhagem.

[[v9-20-7]]

^<<v9-20-7,7>>^ Se disser assim: Está  bem, então  teu servo tem paz: porém se muito se indignar, sabe que já está inteiramente determinado no mal.

[[v9-20-8]]

^<<v9-20-8,8>>^ Usa pois de misericórdia com o teu servo, porque fizeste a teu servo entrar contigo em aliança do Senhor: se porém há em mim crime, mata-me tu mesmo: porque me levarias a teu pai?

[[v9-20-9]]

^<<v9-20-9,9>>^ Então disse Jônatas: Longe de ti tal cousa: porém se dalguma maneira soubesse que já este mal está inteiramente determinado por meu pai, para que viesse sobre ti, não to descobriria eu?

[[v9-20-10]]

^<<v9-20-10,10>>^ E disse Davi a Jônatas: Quem tal me fará saber, se por acaso teu pai te responder asperamente?

[[v9-20-11]]

^<<v9-20-11,11>>^ Então disse Jônatas a Davi: Vem e saiamos ao campo. E saíram ambos ao campo.

[[v9-20-12]]

^<<v9-20-12,12>>^ E disse Jônatas a Davi: O Senhor Deus de Israel, sondando eu a meu pai amanhã a estas horas, ou  depois de amanhã, e eis que houver cousa  favorável para Davi, e eu então não enviar a ti, e não to fizer saber,

[[v9-20-13]]

^<<v9-20-13,13>>^ O Senhor faça assim com Jônatas outro tanto; mas se aprouver a meu pai fazer-te mal, também to farei saber, e te deixarei partir, e irás em paz: e o Senhor seja contigo, assim  como foi com meu pai.

[[v9-20-14]]

^<<v9-20-14,14>>^ E, se eu então ainda viver, porventura  não usarás comigo da beneficência do Senhor, para que não morra?

[[v9-20-15]]

^<<v9-20-15,15>>^ Nem tão pouco cortarás da minha casa a tua beneficência eternamente: nem ainda quando o Senhor desarraigar da terra a cada um dos inimigos de Davi.

[[v9-20-16]]

^<<v9-20-16,16>>^ Assim fez Jônatas aliança  com a casa de Davi, dizendo : O Senhor o requeira da mão dos inimigos de Davi.

[[v9-20-17]]

^<<v9-20-17,17>>^ E Jônatas fez jurar a Davi de novo, porquanto o amava; porque o amava com todo  o amor da sua alma.

[[v9-20-18]]

^<<v9-20-18,18>>^ E disse-lhe Jônatas: Amanhã é a lua nova, e não te acharão no teu lugar, pois o teu assento se achará vazio.

[[v9-20-19]]

^<<v9-20-19,19>>^ E, ausentando-te tu três dias, desce apressadamente, e vai àquele lugar onde te escondeste no dia do negócio: e fica-te junto à pedra de Ezel.

[[v9-20-20]]

^<<v9-20-20,20>>^ E eu atirarei três frechas para aquela banda, como se atirara ao alvo.

[[v9-20-21]]

^<<v9-20-21,21>>^ E eis que mandarei o moço dizendo : Anda, busca as frechas: se eu expressamente disser ao moço: Olha que as frechas estão  para cá de ti; toma-o contigo , e vem; porque há paz para ti, e não há nada, vive o Senhor.

[[v9-20-22]]

^<<v9-20-22,22>>^ Porém se disser ao moço assim: Olha que as frechas estão  para lá de ti: vai-te embora ; porque o Senhor te deixa ir.

[[v9-20-23]]

^<<v9-20-23,23>>^ E quanto  ao negócio de que eu e tu falamos, eis que o Senhor está  entre mim e ti eternamente.

[[v9-20-24]]

^<<v9-20-24,24>>^ Escondeu-se pois Davi no campo: e, sendo a lua nova, assentou-se o rei para comer pão.

[[v9-20-25]]

^<<v9-20-25,25>>^ E, assentando-se o rei no seu assento, como as outras vezes, no lugar junto à parede, Jônatas se levantou, e assentou-se Abner ao lado de Saul: e o lugar de Davi apareceu vazio.

[[v9-20-26]]

^<<v9-20-26,26>>^ Porém naquele dia não disse Saul nada, porque dizia: Aconteceu-lhe alguma cousa, pela qual não está limpo; certamente não está limpo.

[[v9-20-27]]

^<<v9-20-27,27>>^ Sucedeu também ao outro dia, o segundo da lua nova, que o lugar de Davi apareceu vazio: disse pois Saul a Jônatas, seu filho: Por que não veio o filho de Jessé nem ontem nem hoje a comer  pão?

[[v9-20-28]]

^<<v9-20-28,28>>^ E respondeu Jônatas a Saul: Davi me pediu encarecidamente que o deixasse ir  a Belém.

[[v9-20-29]]

^<<v9-20-29,29>>^ Dizendo: Peço- te que  me deixes ir, porquanto a nossa linhagem tem um sacrifício na cidade, e meu irmão mesmo me mandou ir: se pois agora tenho achado graça em teus olhos, peço- te que  me deixes partir, para que veja a meus irmãos: por isso não veio à mesa do rei.

[[v9-20-30]]

^<<v9-20-30,30>>^ Então se acendeu a ira de Saul contra Jônatas, e disse-lhe: Filho da perversa em rebeldia; não sei eu  que tens elegido o filho de Jessé para vergonha tua e para vergonha da nudez de tua mãe?

[[v9-20-31]]

^<<v9-20-31,31>>^ Porque todos os dias que o filho de Jessé viver sobre a terra nem tu serás firme, nem o teu reino: pelo que, envia, e traze-mo nesta hora; porque é digno de morte.

[[v9-20-32]]

^<<v9-20-32,32>>^ Então respondeu Jônatas a Saul, seu pai, e lhe disse: Por que há de ele morrer? Que tem feito?

[[v9-20-33]]

^<<v9-20-33,33>>^ Então Saul atirou-lhe com a lança, para o ferir: assim entendeu Jônatas que já seu pai tinha determinado matar a Davi.

[[v9-20-34]]

^<<v9-20-34,34>>^ Pelo que Jônatas, todo encolerizado, se levantou da mesa: e no segundo dia da lua nova não comeu pão; porque se magoava por causa de Davi, pois seu pai o tinha maltratado.

[[v9-20-35]]

^<<v9-20-35,35>>^ E aconteceu, pela manhã, que Jônatas saiu ao campo, ao tempo que tinha  ajustado com Davi, e um moço pequeno com ele.

[[v9-20-36]]

^<<v9-20-36,36>>^ Então disse ao seu moço: Corre a buscar as frechas que eu atirar. Correu pois  o moço, e ele atirou uma frecha, que fez passar além dele.

[[v9-20-37]]

^<<v9-20-37,37>>^ E, chegando o moço ao lugar da frecha que Jônatas tinha atirado, gritou Jônatas atrás do moço, e disse: Não está porventura  a frecha mais para lá de ti?

[[v9-20-38]]

^<<v9-20-38,38>>^ E tornou Jônatas a gritar atrás do moço: Apressa-te, avia-te, não te demores. E o moço de Jônatas apanhou as frechas e veio a seu senhor.

[[v9-20-39]]

^<<v9-20-39,39>>^ E o moço não entendeu cousa alguma: só Jônatas e Davi sabiam deste negócio.

[[v9-20-40]]

^<<v9-20-40,40>>^ Então Jônatas deu as suas armas ao moço que trazia, e disse-lhe: Anda, e  leva-as à cidade.

[[v9-20-41]]

^<<v9-20-41,41>>^ E, indo-se o moço, levantou-se Davi da banda do sul, e lançou-se sobre o seu rosto em terra, e inclinou-se três vezes: e beijaram-se um ao outro, e choraram juntos, até que Davi chorou muito mais.

[[v9-20-42]]

^<<v9-20-42,42>>^ E disse Jônatas a Davi: Vai-te em paz: o que nós temos jurado ambos em nome do Senhor, dizendo: O Senhor seja entre mim e ti, e entre minha semente e a tua semente, seja  perpetuamente.

[[v9-20-43]]

^<<v9-20-43,43>>^ Então se levantou Davi , e se foi; e Jônatas entrou na cidade.

'''

xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[&#60; Capítulo Anterior] | <<v9-20-0,Topo>> | xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[Próximo Capítulo &#62;]