include::./index.adoc[]

[[v9-25-0]]
=== 1 Samuel, 25
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v9-25-1]]

^<<v9-25-1,1>>^ E FALECEU Samuel, e todo o Israel se ajuntou, e o prantearam, e o sepultaram na sua casa, em Ramá. E Davi se levantou e desceu ao deserto de Parã.

[[v9-25-2]]

^<<v9-25-2,2>>^ E havia um  homem em Maom, que tinha as suas possessões no Carmelo; e era  este homem mui poderoso, e tinha três mil ovelhas e mil cabras: e estava tosquiando as suas ovelhas no Carmelo.

[[v9-25-3]]

^<<v9-25-3,3>>^ E era  o nome deste homem Nabal, e o nome de sua mulher Abigail; e era  a mulher de bom entendimento e formosa, porém o homem era  duro e maligno nas obras, e era da casa de Calebe.

[[v9-25-4]]

^<<v9-25-4,4>>^ E ouviu Davi no deserto que Nabal tosquiava as suas ovelhas,

[[v9-25-5]]

^<<v9-25-5,5>>^ E enviou Davi dez mancebos, e disse aos mancebos: Subi ao Carmelo, e, indo a Nabal, perguntai-lhe, em meu nome, como está.

[[v9-25-6]]

^<<v9-25-6,6>>^ E assim direis àquele próspero: Paz tenhas, e que a tua casa tenha paz, e tudo o que tens tenha paz!

[[v9-25-7]]

^<<v9-25-7,7>>^ Agora, pois, tenho ouvido que tens tosquiadores: ora os pastores que tens estiveram conosco; agravo nenhum lhes fizemos, nem cousa alguma lhes faltou todos os dias que estiveram no Carmelo.

[[v9-25-8]]

^<<v9-25-8,8>>^ Pergunta-o aos teus mancebos, e eles to dirão; estes mancebos pois achem graça em teus olhos, porque viemos em bom dia: dá pois a teus servos e a Davi, teu filho, o que achares à mão.

[[v9-25-9]]

^<<v9-25-9,9>>^ Chegando pois os mancebos de Davi, e tendo falado a Nabal todas aquelas palavras em nome de Davi, se calaram.

[[v9-25-10]]

^<<v9-25-10,10>>^ E Nabal respondeu aos criados de Davi, e disse: Quem é  Davi, e quem o filho de Jessé? muitos servos há hoje, e cada um foge a seu senhor.

[[v9-25-11]]

^<<v9-25-11,11>>^ Tomaria eu pois o meu pão, e a minha água, e a carne das minhas reses que degolei para os meus tosquiadores, e o daria a homens que eu não sei donde vêm?

[[v9-25-12]]

^<<v9-25-12,12>>^ Então os mancebos de Davi se tornaram para o seu caminho: e voltaram, e vieram, e lhe anunciaram tudo conforme a  todas estas palavras.

[[v9-25-13]]

^<<v9-25-13,13>>^ Pelo que disse Davi aos seus homens: Cada um cinja a sua espada. E cada um cingiu a sua espada, e cingiu também Davi a sua: e subiram após Davi uns quatrocentos homens, e duzentos ficaram com a bagagem.

[[v9-25-14]]

^<<v9-25-14,14>>^ Porém um dentre os mancebos o anunciou a Abigail, mulher de Nabal, dizendo: Eis que Davi enviou mensageiros desde o deserto a saudar o nosso amo; porém ele se lançou a eles.

[[v9-25-15]]

^<<v9-25-15,15>>^ Todavia, aqueles homens têm-nos sido  muito bons, e nunca fomos agravados deles , e nada nos faltou em todos os dias que conversamos com eles quando estávamos no campo.

[[v9-25-16]]

^<<v9-25-16,16>>^ De muro em redor nos serviram, assim de dia como de noite, todos os dias que andamos com eles apascentando as ovelhas.

[[v9-25-17]]

^<<v9-25-17,17>>^ Olha pois, agora, e vê o que hás de fazer porque já  de todo determinado está o mal contra o nosso amo e contra toda a sua casa, e ele é  um tal filho de Belial, que não há quem lhe possa falar.

[[v9-25-18]]

^<<v9-25-18,18>>^ Então Abigail se apressou, e tomou duzentos pães, e dois odres de vinho, e cinco ovelhas guisadas, e cinco medidas de trigo  tostado, e cem cachos de passas, e duzentas pastas de figos passados, e os  pôs sobre jumentos.

[[v9-25-19]]

^<<v9-25-19,19>>^ E disse aos seus mancebos: Ide adiante de mim, eis que vos seguirei de perto. O que, porém, não declarou a seu marido Nabal.

[[v9-25-20]]

^<<v9-25-20,20>>^ E sucedeu que, andando ela montada num jumento, desceu pelo encoberto do monte, e eis que Davi e os seus homens lhe vinham ao encontro, e encontrou-se com eles.

[[v9-25-21]]

^<<v9-25-21,21>>^ E disse Davi: Na verdade que em vão tenho guardado tudo quanto este tem  no deserto, e nada lhe  faltou de tudo quanto tem, e ele me pagou mal por bem.

[[v9-25-22]]

^<<v9-25-22,22>>^ Assim faça Deus aos inimigos de Davi, e outro tanto, se eu deixar até à manhã de tudo o que tem, mesmo até um menino.

[[v9-25-23]]

^<<v9-25-23,23>>^ Vendo pois Abigail a Davi, apressou-se, e desceu do jumento, e prostrou-se sobre o seu rosto diante de Davi, e se inclinou à terra.

[[v9-25-24]]

^<<v9-25-24,24>>^ E lançou-se a seus pés, e disse: Ah! senhor meu, minha seja  a transgressão; deixa pois falar a tua serva aos teus ouvidos, e ouve as palavras da tua serva.

[[v9-25-25]]

^<<v9-25-25,25>>^ Meu senhor, agora não faça este  homem de Belial, a saber , Nabal, impressão no seu coração, porque tal é ele qual é o seu nome. Nabal é  o seu nome, e a loucura está  com ele, e eu, tua serva, não vi os mancebos de meu senhor, que enviaste.

[[v9-25-26]]

^<<v9-25-26,26>>^ Agora, pois, meu senhor, vive o Senhor, e vive a tua alma, que o Senhor te impediu de vires com sangue, e de que a tua mão te salvasse: e, agora, tais quais Nabal sejam os teus inimigos e os que procuram mal contra o meu senhor.

[[v9-25-27]]

^<<v9-25-27,27>>^ E agora esta é a bênção que trouxe a tua serva a meu senhor: dê-se aos mancebos que andam após das pisadas de meu senhor.

[[v9-25-28]]

^<<v9-25-28,28>>^ Perdoa pois à tua serva esta  transgressão, porque certamente fará o Senhor casa firme a meu senhor, porque meu senhor guerreia as guerras do Senhor, e não se tem achado mal em ti por todos os  teus dias.

[[v9-25-29]]

^<<v9-25-29,29>>^ E, levantando-se algum homem para te perseguir, e para procurar a tua morte, então a vida de meu senhor será atada no feixe dos que vivem com o Senhor teu Deus; porém a vida de teus inimigos se arrojará ao longe, como do meio do côncavo de uma funda.

[[v9-25-30]]

^<<v9-25-30,30>>^ E há de ser que, usando o Senhor com o meu senhor conforme a todo o bem que já tem dito de ti, e te tiver estabelecido chefe sobre Israel,

[[v9-25-31]]

^<<v9-25-31,31>>^ Então, meu senhor, não te será por tropeço, nem por pesar no coração, o sangue que sem causa derramaste, nem tão pouco o haver-se salvado meu senhor a si mesmo: e quando o Senhor fizer bem a meu senhor, lembra-te então da tua serva.

[[v9-25-32]]

^<<v9-25-32,32>>^ Então Davi disse a Abigail: Bendito o Senhor Deus de Israel, que hoje te enviou ao meu encontro.

[[v9-25-33]]

^<<v9-25-33,33>>^ E bendito o teu conselho, e bendita tu, que hoje me estorvaste de vir com sangue, e de que a minha mão me salvasse.

[[v9-25-34]]

^<<v9-25-34,34>>^ Porque, na verdade, vive o Senhor Deus de Israel, que me impediu de que te fizesse mal, que se tu não te apressaras, e me não vieras ao encontro, não ficaria a Nabal até à luz da manhã nem mesmo um menino.

[[v9-25-35]]

^<<v9-25-35,35>>^ Então Davi tomou da sua mão o que tinha trazido, e lhe disse: Sobe em paz à tua casa; vês aqui  que tenho dado ouvidos à tua voz, e tenho aceitado a tua face.

[[v9-25-36]]

^<<v9-25-36,36>>^ E, vindo Abigail a Nabal, eis que tinha em sua casa um  banquete, como banquete de rei; e o coração de Nabal estava  alegre nele e ele já  mui embriagado, pelo que não lhe deu a entender palavra alguma, pequena nem grande, até à luz da manhã.

[[v9-25-37]]

^<<v9-25-37,37>>^ Sucedeu pois que pela manhã, havendo já  saído de Nabal o vinho, sua mulher lhe deu a entender aquelas palavras: e se amorteceu nele, o seu coração, e ficou ele como pedra.

[[v9-25-38]]

^<<v9-25-38,38>>^ E aconteceu que, passados  quase dez dias, feriu o Senhor a Nabal, e este  morreu.

[[v9-25-39]]

^<<v9-25-39,39>>^ E, ouvindo Davi que Nabal morrera, disse: Bendito seja  o Senhor, que pleiteou o pleito da minha afronta da mão de Nabal, e deteve a seu servo do mal, fazendo o Senhor tornar o mal de Nabal sobre a sua cabeça. E mandou Davi falar a Abigail, para tomá-la por sua mulher.

[[v9-25-40]]

^<<v9-25-40,40>>^ Vindo pois os criados de Davi a Abigail, no Carmelo, lhe falaram, dizendo: Davi nos tem mandado a ti, para te tomar por sua mulher.

[[v9-25-41]]

^<<v9-25-41,41>>^ Então ela se levantou, e se inclinou com o rosto em terra, e disse: Eis aqui a tua serva servirá de criada para lavar os pés dos criados de meu senhor.

[[v9-25-42]]

^<<v9-25-42,42>>^ E Abigail se apressou, e se levantou, e montou num jumento com as suas cinco moças que seguiam as suas pisadas: e ela seguiu os mensageiros de Davi, e foi sua mulher.

[[v9-25-43]]

^<<v9-25-43,43>>^ Também tomou Davi a Aquinoã de Jezreel: e também ambas foram suas mulheres.

[[v9-25-44]]

^<<v9-25-44,44>>^ Porque Saul tinha dado sua filha Mical, mulher de Davi, a Palti, filho de Laís, o qual era  de Galim.

'''

xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[&#60; Capítulo Anterior] | <<v9-25-0,Topo>> | xref:009-1-samuel/009-1-samuel-026.adoc#v9-26-0[Próximo Capítulo &#62;]