include::./index.adoc[]

[[v8-4-0]]
=== Rute, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v8-4-1]]

^<<v8-4-1,1>>^ E BOAZ subiu à porta, e assentou-se ali: e eis que o remidor de que Boaz tinha falado ia passando, e disse-lhe: Ó fulano, desvia-te para cá , assenta-te aqui. E desviou-se para ali , e assentou-se.

[[v8-4-2]]

^<<v8-4-2,2>>^ Então tomou dez homens dos anciãos da cidade, e disse: Assentai-vos aqui. E assentaram-se.

[[v8-4-3]]

^<<v8-4-3,3>>^ Então disse ao remidor: Aquela parte da terra que foi  de Elimeleque, nosso irmão, Noemi, que tornou da terra dos moabitas, a vendeu.

[[v8-4-4]]

^<<v8-4-4,4>>^ E disse eu: Manifestá-lo-ei em  teus ouvidos, dizendo: Toma- a  diante dos habitantes, e diante dos anciãos do meu povo; se a  hás de redimir, redime- a , e, se não se houver de redimir, declara-mo, para que o saiba, pois outro não há  senão tu que a  redima, e eu depois de ti. Então disse ele: Eu a  redimirei.

[[v8-4-5]]

^<<v8-4-5,5>>^ Disse porém Boaz: No dia em que tomares a terra da mão de Noemi, também a tomarás da mão de Rute, a moabita, mulher do defunto, para suscitar o nome do defunto sobre a sua herdade.

[[v8-4-6]]

^<<v8-4-6,6>>^ Então disse o remidor: Para mim não a  poderei redimir, para que não dane a minha herdade: redime tu a minha remissão para ti, porque eu não a  poderei redimir.

[[v8-4-7]]

^<<v8-4-7,7>>^ Havia, pois, já de muito tempo este costume  em Israel, quanto a remissão e contrato, para confirmar todo o negócio, que o  homem descalçava o sapato e o  dava ao seu próximo: e isto era  por testemunho em Israel.

[[v8-4-8]]

^<<v8-4-8,8>>^ Disse pois o remidor a Boaz: Toma-a para ti. E descalçou o sapato.

[[v8-4-9]]

^<<v8-4-9,9>>^ Então Boaz disse aos anciãos e a todo o povo: Sois  hoje testemunhas de que tomei tudo quanto foi  de Elimeleque, e de Quiliom, e de Malom, da mão de Noemi,

[[v8-4-10]]

^<<v8-4-10,10>>^ E de que também tomo por mulher a Rute, a moabita, que foi  mulher de Malom, para suscitar o nome do defunto sobre a sua herdade, para que o nome do defunto não seja desarraigado dentre seus irmãos e da porta do seu lugar: disto sois  hoje testemunhas.

[[v8-4-11]]

^<<v8-4-11,11>>^ E todo o povo que estava  na porta, e os anciãos, disseram: Somos  testemunhas: o Senhor faça a esta mulher, que entra na tua casa, como a Raquel e como a Leia, que ambas edificaram a casa de Israel; e há-te já valorosamente em Efrata, e faze- te  nome afamado em Belém.

[[v8-4-12]]

^<<v8-4-12,12>>^ E seja a tua casa como a casa de Perez (que Tamar teve de Judá), da semente que o Senhor te der desta moça.

[[v8-4-13]]

^<<v8-4-13,13>>^ Assim tomou Boaz a Rute, e ela lhe foi por mulher; e ele entrou a ela, e o Senhor lhe deu conceição, e teve um  filho.

[[v8-4-14]]

^<<v8-4-14,14>>^ Então as mulheres disseram a Noemi: Bendito seja  o Senhor, que não deixou hoje de te dar remidor, e seja o seu nome afamado em Israel.

[[v8-4-15]]

^<<v8-4-15,15>>^ Ele te será recriador da alma, e conservará a tua velhice, pois tua nora, que te ama, o teve, e ela te é melhor do que sete filhos.

[[v8-4-16]]

^<<v8-4-16,16>>^ E Noemi tomou o filho, e o pôs no seu regaço, e foi sua ama.

[[v8-4-17]]

^<<v8-4-17,17>>^ E as vizinhas lhe deram um  nome dizendo: A Noemi nasceu um  filho. E chamaram o seu nome Obede. Este é  o pai de Jessé, pai de Davi.

[[v8-4-18]]

^<<v8-4-18,18>>^ Estas são  pois as gerações de Perez: Perez gerou a Esrom.

[[v8-4-19]]

^<<v8-4-19,19>>^ E Esrom gerou a Arão, e Arão gerou a Aminadabe,

[[v8-4-20]]

^<<v8-4-20,20>>^ E Aminadabe gerou a Naassom, e Naassom gerou a Salmom,

[[v8-4-21]]

^<<v8-4-21,21>>^ E Salmom gerou a Boaz, e Boaz gerou a Obede,

[[v8-4-22]]

^<<v8-4-22,22>>^ E Obede gerou a Jessé, e Jessé gerou a Davi.

'''

xref:008-rute/008-rute-003.adoc#v8-3-0[&#60; Capítulo Anterior] | <<v8-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[Próximo Capítulo &#62;]