include::./index.adoc[]

[[v12-12-0]]
=== 2 Reis, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-12-1]]

^<<v12-12-1,1>>^ NO ano sétimo de Jeú começou a reinar Joás, e quarenta anos reinou em Jerusalém; e era  o nome de sua mãe Zibia, de Berseba.

[[v12-12-2]]

^<<v12-12-2,2>>^ E fez Joás o que era  reto aos olhos do Senhor todos os dias em que o sacerdote Joiada o dirigia.

[[v12-12-3]]

^<<v12-12-3,3>>^ Tão somente os altos se não tiraram: porque  ainda o povo sacrificava e queimava incenso nos altos.

[[v12-12-4]]

^<<v12-12-4,4>>^ E disse Joás aos sacerdotes: Todo o dinheiro das cousas santas que se trouxer à casa do Senhor, a saber , o dinheiro daquele que passa o arrolamento , o dinheiro de cada uma das pessoas, segundo  a sua avaliação, e  todo o dinheiro que trouxer cada um voluntariamente para a casa do Senhor,

[[v12-12-5]]

^<<v12-12-5,5>>^ Os sacerdotes o recebam, cada um dos seus conhecidos; e eles reparem as fendas da casa, segundo toda a fenda que se achar nela.

[[v12-12-6]]

^<<v12-12-6,6>>^ Sucedeu porém que, no ano vinte e três do rei Joás, os sacerdotes ainda  não tinham reparado as fendas da casa.

[[v12-12-7]]

^<<v12-12-7,7>>^ Então o rei Joás chamou o sacerdote Joiada e os mais  sacerdotes, e lhes disse: Por que não reparais as fendas da casa? Agora, pois, não tomeis mais  dinheiro de vossos conhecidos, mas dai-o pelas fendas da casa.

[[v12-12-8]]

^<<v12-12-8,8>>^ E consentiram os sacerdotes em não tomarem mais  dinheiro do povo, nem em repararem as fendas da casa.

[[v12-12-9]]

^<<v12-12-9,9>>^ Porém o sacerdote Joiada tomou uma arca, e fez um buraco na tampa; e a pôs ao pé do altar, à mão direita dos que entravam na casa do Senhor: e os sacerdotes que guardavam a entrada da porta metiam ali todo o dinheiro que se trazia à casa do Senhor.

[[v12-12-10]]

^<<v12-12-10,10>>^ Sucedeu pois que, vendo eles que já havia muito dinheiro na arca, o escrivão do rei subia com o sumo sacerdote, e contavam e ensacavam o dinheiro que se achava na casa do Senhor.

[[v12-12-11]]

^<<v12-12-11,11>>^ E o dinheiro, depois de pesado, davam nas mãos dos que faziam a obra, que tinham a seu cargo a casa do Senhor: e eles os distribuíam aos carpinteiros, e aos edificadores que reparavam a casa do Senhor;

[[v12-12-12]]

^<<v12-12-12,12>>^ Como também aos pedreiros e aos cabouqueiros, e para se comprar madeira e pedras de cantaria para repararem as fendas da casa do Senhor, e para tudo quanto para a casa se dava para a  repararem.

[[v12-12-13]]

^<<v12-12-13,13>>^ Todavia, do dinheiro que se trazia à casa do Senhor não se faziam nem  taças de prata, nem  garfos, nem  bacias, nem  trombetas, nem  nenhum vaso de ouro ou vaso de prata para a casa do Senhor.

[[v12-12-14]]

^<<v12-12-14,14>>^ Porque o davam aos que faziam a obra, e reparavam com ele a casa do Senhor.

[[v12-12-15]]

^<<v12-12-15,15>>^ Também não pediam contas aos homens em cujas mãos entregavam aquele dinheiro, para o dar aos que faziam a obra, porque obravam com fidelidade.

[[v12-12-16]]

^<<v12-12-16,16>>^ Mas  o dinheiro de sacrifício por delitos, e o dinheiro por sacrifício de pecados, se não trazia à casa do Senhor; porém  era para os sacerdotes.

[[v12-12-17]]

^<<v12-12-17,17>>^ Então subiu Hazael, rei da Síria, e pelejou contra Gate, e a tomou: depois Hazael fez rosto a marchar contra Jerusalém.

[[v12-12-18]]

^<<v12-12-18,18>>^ Porém, Joás, rei de Judá, tomou todas as cousas santas que Josafá, e Jorão, e Acazias, seus pais, reis de Judá, consagraram, como também todo o ouro que se achou nos tesouros da casa do Senhor e na casa do rei: e o mandou a Hazael, rei da Síria; e ele então  se retirou de Jerusalém.

[[v12-12-19]]

^<<v12-12-19,19>>^ Ora o mais dos sucessos de Joás, e tudo quanto fez mais, porventura  não está  escrito no livro das crônicas dos reis de Judá?

[[v12-12-20]]

^<<v12-12-20,20>>^ E levantaram-se os seus servos, e conspiraram contra ele : e feriram a Joás na casa de Milo, que desce para Sila.

[[v12-12-21]]

^<<v12-12-21,21>>^ Porque Jozacar, filho de Simeate, e Jozabade, filho de Somer, seus servos, o feriram, e morreu, e o sepultaram com seus pais na cidade de Davi: e Amasias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[&#60; Capítulo Anterior] | <<v12-12-0,Topo>> | xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[Próximo Capítulo &#62;]