include::./index.adoc[]

[[v12-9-0]]
=== 2 Reis, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-9-1]]

^<<v12-9-1,1>>^ ENTÃO o profeta Eliseu chamou um dos filhos dos profetas, e lhe disse: Cinge os teus lombos, e toma esta almotolia de azeite na tua mão, e vai-te a Ramote de Gileade.

[[v12-9-2]]

^<<v12-9-2,2>>^ E, chegando lá, vê onde está Jeú, filho de Josafá, filho de Ninsi: e entra, e faze que ele se levante do meio de seus irmãos, e leva-o à câmara interior.

[[v12-9-3]]

^<<v12-9-3,3>>^ E toma a almotolia de azeite, e derrama-o sobre a sua cabeça, e dize: Assim diz o Senhor: Ungi-te rei sobre Israel. Então abre a porta, e foge, e não te detenhas.

[[v12-9-4]]

^<<v12-9-4,4>>^ Foi pois o mancebo, o jovem profeta, a Ramote de Gileade.

[[v12-9-5]]

^<<v12-9-5,5>>^ E, entrando ele, eis que os capitães do exército estavam  assentados ali; e disse: Capitão, tenho uma  palavra que te dizer. E disse Jeú. A qual de todos nós? E disse: A ti, capitão!

[[v12-9-6]]

^<<v12-9-6,6>>^ Então se levantou, e entrou na casa, e derramou o azeite sobre a sua cabeça, e lhe disse: Assim diz o Senhor Deus de Israel: Ungi-te rei sobre o povo do Senhor, sobre Israel.

[[v12-9-7]]

^<<v12-9-7,7>>^ E ferirás a casa de Acabe, teu senhor, para que eu vingue o sangue de meus servos, os profetas, e o sangue de todos os servos do Senhor da mão de Jezabel.

[[v12-9-8]]

^<<v12-9-8,8>>^ E toda a casa de Acabe perecerá; e destruirei de Acabe todo o varão, tanto o encerrado como o desamparado em Israel.

[[v12-9-9]]

^<<v12-9-9,9>>^ Porque à casa de Acabe hei de fazer como à casa de Jeroboão, filho de Nebate, e como à casa de Baasa, filho de Aías.

[[v12-9-10]]

^<<v12-9-10,10>>^ E os cães comerão a Jezabel no pedaço de campo de Jezreel; não haverá  quem a  enterre. Então abriu a porta, e fugiu.

[[v12-9-11]]

^<<v12-9-11,11>>^ E, saindo Jeú aos servos de seu senhor, disseram-lhe: Vai tudo bem? Por que veio a ti este louco? E ele lhes disse: Bem conheceis o homem e o seu falar.

[[v12-9-12]]

^<<v12-9-12,12>>^ Mas eles  disseram: É mentira: agora faze-no-lo saber. E disse: Assim e assim me falou, dizendo: Assim diz o Senhor: Ungi-te rei sobre Israel.

[[v12-9-13]]

^<<v12-9-13,13>>^ Então se apressaram, e tomou cada um o seu vestido e o pôs debaixo dele, no mais alto degrau: e tocaram a buzina, e disseram: Jeú reina.

[[v12-9-14]]

^<<v12-9-14,14>>^ Assim Jeú, filho de Josafá, filho de Ninsi, conspirou contra Jorão. Tinha porém Jorão cercado a Ramote de Gileade, ele e todo o Israel, por causa de Hazael, rei da Síria.

[[v12-9-15]]

^<<v12-9-15,15>>^ Porém o rei Jorão voltou para se curar em Jezreel das feridas que os siros lhe fizeram, quando pelejou contra Hazael, rei da Síria. E disse Jeú: Se é da vossa vontade, ninguém saia da cidade, nem escape, para ir anunciar isto  em Jezreel.

[[v12-9-16]]

^<<v12-9-16,16>>^ Então Jeú subiu a um carro, e foi-se a Jezreel, porque Jorão estava deitado ali; e também  Acazias rei de Judá, descera para ver a Jorão.

[[v12-9-17]]

^<<v12-9-17,17>>^ E o atalaia estava na torre de Jezreel, e viu a tropa de Jeú, que vinha, e disse: Vejo uma tropa. Então disse Jorão: Toma um cavaleiro e envia-lho ao encontro; e diga. Há paz?

[[v12-9-18]]

^<<v12-9-18,18>>^ E o cavaleiro lhe foi ao encontro, e disse: Assim diz o rei: Há paz? E disse Jeú: Que tens tu que fazer com a paz? Passa para trás de mim. E o atalaia o fez saber dizendo: Chegou a eles o mensageiro, porém não volta.

[[v12-9-19]]

^<<v12-9-19,19>>^ Então enviou outro cavaleiro; e, chegando este a eles, disse: Assim diz o rei: Há paz? E disse Jeú: Que tens tu que fazer com a paz? Passa para trás de mim.

[[v12-9-20]]

^<<v12-9-20,20>>^ E o atalaia o fez saber, dizendo: Também  este chegou a eles porém não volta; e o andar parece como o andar de Jeú, filho de Ninsi, porque anda furiosamente.

[[v12-9-21]]

^<<v12-9-21,21>>^ Então disse Jorão: Aparelha o carro. E aparelharam o seu carro. E saiu Jorão, rei de Israel, e Acazias, rei de Judá, cada um em seu carro, e saíram ao encontro de Jeú, e o acharam no pedaço de campo  de Nabote, o jezreelita.

[[v12-9-22]]

^<<v12-9-22,22>>^ E sucedeu que, vendo Jorão a Jeú, disse: Há paz, Jeú? E disse ele: Que paz, enquanto as prostituições da tua mãe Jezabel e as suas feitiçarias são  tantas?

[[v12-9-23]]

^<<v12-9-23,23>>^ Então Jorão voltou as mãos, e fugiu; e disse a Acazias: Traição há , Acazias.

[[v12-9-24]]

^<<v12-9-24,24>>^ Mas Jeú entesou o seu arco com toda a força, e feriu a Jorão entre os braços, e a frecha lhe saiu pelo coração; e caiu no seu carro.

[[v12-9-25]]

^<<v12-9-25,25>>^ Então Jeú  disse a Bidcar, seu capitão: Toma-o, lança-o no pedaço do campo de Nabote, o jezreelita; pois, lembra-te de que, indo eu e tu juntos a cavalo após seu pai Acabe, o Senhor pôs sobre ele esta carga, dizendo :

[[v12-9-26]]

^<<v12-9-26,26>>^ Por certo que  se eu não visse ontem à tarde o sangue de Nabote e o sangue de seus filhos, diz o Senhor, também não to pagaria neste pedaço de campo , diz o Senhor. Agora, pois, toma-o, e lança-o neste pedaço de campo , conforme a palavra do Senhor.

[[v12-9-27]]

^<<v12-9-27,27>>^ O que  vendo Acazias, rei de Judá, fugiu pelo caminho da casa do jardim, porém Jeú seguiu após ele, e disse: Feri também a este no carro à subida de Gur, que está  junto a Jibleão. E fugiu para Megido, e morreu ali.

[[v12-9-28]]

^<<v12-9-28,28>>^ E seus servos o levaram num carro a Jerusalém, e o sepultaram na sua sepultura, junto a seus pais, na cidade de Davi.

[[v12-9-29]]

^<<v12-9-29,29>>^ E no ano undécimo de Jorão, filho de Acabe, começou Acazias a reinar sobre Judá.

[[v12-9-30]]

^<<v12-9-30,30>>^ E Jeú veio a Jezreel, o que ouvindo Jezabel, se pintou em volta dos olhos, e enfeitou a sua cabeça e olhou pela janela.

[[v12-9-31]]

^<<v12-9-31,31>>^ E, entrando Jeú pelas portas, disse ela: Teve paz Zinri, que matou a seu senhor?

[[v12-9-32]]

^<<v12-9-32,32>>^ E levantou ele o rosto para a janela e disse: Quem é  comigo? quem? E dois ou três eunucos olharam para ele.

[[v12-9-33]]

^<<v12-9-33,33>>^ Então disse ele: Lançai-a de alto  abaixo. E lançaram-na de alto  abaixo: e foram salpicados com o seu sangue a parede e os cavalos, e ele a atropelou.

[[v12-9-34]]

^<<v12-9-34,34>>^ Entrando ele pois, e havendo comido e bebido, disse: Olhai por aquela maldita, e sepultai-a, porque é  filha de rei.

[[v12-9-35]]

^<<v12-9-35,35>>^ E foram para a sepultar; porém não acharam dela senão somente  a caveira, e os pés, e as palmas das mãos.

[[v12-9-36]]

^<<v12-9-36,36>>^ Então voltaram, e lho fizeram saber; e ele disse: Esta é  a palavra do Senhor, a qual falou pelo ministério de Elias, o tesbita, seu servo, dizendo: No pedaço do campo  de Jezreel os cães comerão a carne de Jezabel.

[[v12-9-37]]

^<<v12-9-37,37>>^ E o cadáver de Jezabel será como esterco sobre o campo, no pedaço de Jezreel: que se não possa dizer: Esta é  Jezabel.

'''

xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[&#60; Capítulo Anterior] | <<v12-9-0,Topo>> | xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[Próximo Capítulo &#62;]