include::./index.adoc[]

[[v12-14-0]]
=== 2 Reis, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-14-1]]

^<<v12-14-1,1>>^ NO segundo ano de Jeoás, filho de Joacaz, rei de Israel, começou a reinar Amazias, filho de Joás, rei de Judá.

[[v12-14-2]]

^<<v12-14-2,2>>^ Tinha vinte e cinco anos quando começou a reinar, e vinte e nove anos reinou em Jerusalém. E era o nome de sua mãe Joadã, de Jerusalém.

[[v12-14-3]]

^<<v12-14-3,3>>^ E fez o que  era reto aos olhos do Senhor, ainda que não como seu pai Davi: fez porém  conforme tudo o que fizera Joás seu pai.

[[v12-14-4]]

^<<v12-14-4,4>>^ Tão somente os altos se não tiraram; porque  ainda o povo sacrificava e queimava incenso nos altos.

[[v12-14-5]]

^<<v12-14-5,5>>^ Sucedeu pois que, sendo já o reino confirmado na sua mão, matou os seus servos que tinham morto o rei seu pai.

[[v12-14-6]]

^<<v12-14-6,6>>^ Porém os filhos dos matadores não matou, como está escrito no livro da lei de Moisés, no qual o Senhor deu ordem, dizendo: Não matarão os pais por causa dos filhos, e os filhos não matarão por causa dos pais; mas cada um será morto pelo seu pecado.

[[v12-14-7]]

^<<v12-14-7,7>>^ Este feriu a dez mil edomitas no vale do Sal, e tomou a Sela na Guerra: e chamou o seu nome Jocteel, até ao dia de  hoje.

[[v12-14-8]]

^<<v12-14-8,8>>^ Então Amazias enviou mensageiros a Jeoás, filho de Joacaz, filho de Jeú, rei de Israel, dizendo: Vem vejamo-nos cara a cara.

[[v12-14-9]]

^<<v12-14-9,9>>^ Porém Jeoás, rei de Israel, enviou a Amazias, rei de Judá, dizendo: O cardo que está  no Líbano enviou ao cedro que está  no Líbano, dizendo: Dá tua filha por mulher a meu filho: mas os animais do campo, que estavam no Líbano, passaram e pisaram o cardo.

[[v12-14-10]]

^<<v12-14-10,10>>^ Na verdade feriste os edomitas, e o teu coração se ensoberbeceu: gloria-te disso , e fica em tua casa; e porque te entremeterias no mal, para caíres tu, e Judá contigo?

[[v12-14-11]]

^<<v12-14-11,11>>^ Mas Amazias não o ouviu: e subiu Jeoás, rei de Israel, e Amazias, rei de Judá, e viram-se cara a cara em Bete-Semes, que está  em Judá.

[[v12-14-12]]

^<<v12-14-12,12>>^ E Judá foi ferido diante de Israel, e fugiu cada um para as suas tendas.

[[v12-14-13]]

^<<v12-14-13,13>>^ E Jeoás, rei de Israel, tomou a Amazias, rei de Judá, filho de Joás, filho de Acazias, em Bete-Semes, e veio a Jerusalém, e rompeu o muro de Jerusalém, desde a porta de Efraim até à porta da esquina, quatrocentos côvados.

[[v12-14-14]]

^<<v12-14-14,14>>^ E tomou todo o ouro e a prata, e todos os vasos que se acharam na casa do Senhor e nos tesouros da casa do rei, como também os reféns: e voltou para Samaria.

[[v12-14-15]]

^<<v12-14-15,15>>^ Ora o mais dos sucessos de Jeoás, o que fez, e o seu poder, e como pelejou contra Amazias, rei de Judá, porventura  não está  escrito no livro das crônicas dos reis de Israel?

[[v12-14-16]]

^<<v12-14-16,16>>^ E dormiu Jeoás com seus pais, e foi sepultado em Samaria, junto aos reis de Israel: e Jeroboão, seu filho, reinou em seu lugar.

[[v12-14-17]]

^<<v12-14-17,17>>^ E viveu Amazias, filho de Jeoás, rei de Judá, depois da morte de Jeoás, filho de Joacaz, rei de Israel, quinze anos.

[[v12-14-18]]

^<<v12-14-18,18>>^ Ora o mais dos sucessos de Amazias, porventura  não está  escrito no livro das crônicas dos reis de Judá?

[[v12-14-19]]

^<<v12-14-19,19>>^ E conspiraram contra ele em Jerusalém, e fugiu para Laquis; porém enviaram após ele até Laquis, e o mataram ali.

[[v12-14-20]]

^<<v12-14-20,20>>^ E o trouxeram em cima de cavalos: e o sepultaram em Jerusalém, junto a seus pais, na cidade de Davi.

[[v12-14-21]]

^<<v12-14-21,21>>^ E todo o povo de Judá tomou a Azarias, que já era  de dezesseis anos, e o fizeram rei em lugar de Amazias, seu pai.

[[v12-14-22]]

^<<v12-14-22,22>>^ Este edificou a Elate, e a restituiu a Judá, depois que o rei dormiu com seus pais.

[[v12-14-23]]

^<<v12-14-23,23>>^ No décimo quinto ano de Amazias, filho de Joás, rei de Judá, começou a reinar em Samaria Jeroboão, filho de Jeoás, rei de Israel, e reinou  quarenta e um anos.

[[v12-14-24]]

^<<v12-14-24,24>>^ E fez o que parecia  mal aos olhos do Senhor; nunca se apartou de nenhum dos pecados de Jeroboão, filho de Nebate, que fez pecar a Israel.

[[v12-14-25]]

^<<v12-14-25,25>>^ Também este restabeleceu os termos de Israel, desde a entrada de Hamate até ao mar da planície: conforme a palavra do Senhor, Deus de Israel, a qual falara pelo ministério de seu servo Jonas, filho do profeta Amitai, o qual era  de Gate-Efer.

[[v12-14-26]]

^<<v12-14-26,26>>^ Porque viu o Senhor que  a miséria de Israel era  mui amarga, e que  nem havia encerrado, nem desamparado, nem quem ajudasse a Israel.

[[v12-14-27]]

^<<v12-14-27,27>>^ E ainda  não falara o Senhor em apagar o nome de Israel de debaixo do céu; porém os livrou por mão de Jeroboão, filho de Joás.

[[v12-14-28]]

^<<v12-14-28,28>>^ Ora o mais dos sucessos de Jeroboão, tudo quanto fez, e seu poder, como pelejou, e como reconquistou Damasco e Hamate, pertencentes  a Judá, sendo  rei de Israel, porventura  não está  escrito no livro das crônicas de Israel?

[[v12-14-29]]

^<<v12-14-29,29>>^ E Jeroboão dormiu com seus pais, com os reis de Israel: e Zacarias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[&#60; Capítulo Anterior] | <<v12-14-0,Topo>> | xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[Próximo Capítulo &#62;]