include::./index.adoc[]

[[v12-21-0]]
=== 2 Reis, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-21-1]]

^<<v12-21-1,1>>^ TINHA Manassés doze anos de idade quando começou a reinar, e cinquenta e cinco anos reinou em Jerusalém: e era  o nome de sua mãe Hefsibá.

[[v12-21-2]]

^<<v12-21-2,2>>^ E fez o que parecia  mal aos olhos do Senhor, conforme as abominações dos gentios que o Senhor desterrara de suas  possessões de diante dos filhos de Israel.

[[v12-21-3]]

^<<v12-21-3,3>>^ Porque tornou a edificar os altos que Ezequias, seu pai, tinha destruído, e levantou altares a Baal, e fez um  bosque como o que fizera Acabe, rei de Israel, e se inclinou diante de todo o exército dos céus, e os serviu.

[[v12-21-4]]

^<<v12-21-4,4>>^ E edificou altares na casa do Senhor, de que o Senhor tinha dito: Em Jerusalém porei o meu nome.

[[v12-21-5]]

^<<v12-21-5,5>>^ Também edificou altares a todo o exército dos céus em ambos os átrios da casa do Senhor.

[[v12-21-6]]

^<<v12-21-6,6>>^ E até fez passar a seu filho pelo fogo, e adivinhava pelas nuvens, e era agoureiro, e instituiu adivinhos e feiticeiros: e  prosseguiu em fazer mal aos olhos do Senhor, para o provocar à ira.

[[v12-21-7]]

^<<v12-21-7,7>>^ Também pôs uma  imagem de escultura, do bosque que tinha feito, na casa de que o Senhor dissera a Davi e a Salomão, seu filho: Nesta casa e em Jerusalém, que escolhi de todas as tribos de Israel, porei o meu nome para sempre.

[[v12-21-8]]

^<<v12-21-8,8>>^ E mais não farei mover o pé de Israel desta terra que tenho dado a seus pais; contanto somente que tenham cuidado de fazer conforme tudo o que lhes tenho ordenado, e conforme toda a lei que Moisés, meu servo, lhes ordenou.

[[v12-21-9]]

^<<v12-21-9,9>>^ Porém não ouviram; porque Manassés de tal modo  os fez errar, que fizeram pior do que as nações, que o Senhor tinha destruído de diante dos filhos de Israel.

[[v12-21-10]]

^<<v12-21-10,10>>^ Então o Senhor falou pelo ministério de seus servos, os profetas, dizendo:

[[v12-21-11]]

^<<v12-21-11,11>>^ Porquanto Manassés, rei de Judá, fez estas abominações, fazendo pior do que quanto fizeram os amorreus, que antes dele foram , e até também a Judá fez pecar com os seus ídolos;

[[v12-21-12]]

^<<v12-21-12,12>>^ Por isso assim diz o Senhor Deus de Israel: Eis que hei de trazer tal  mal sobre Jerusalém e Judá que qualquer que ouvir, lhe ficarão retinindo ambas as orelhas.

[[v12-21-13]]

^<<v12-21-13,13>>^ E estenderei sobre Jerusalém o cordel de Samaria e o prumo da casa de Acabe: e limparei a Jerusalém, como quem limpa a escudela a  limpa e a vira sobre a sua face.

[[v12-21-14]]

^<<v12-21-14,14>>^ E desampararei o resto da minha herança, entregá-los-ei na mão de seus inimigos; e far-se-ão roubo e despojo para todos os seus inimigos.

[[v12-21-15]]

^<<v12-21-15,15>>^ Porquanto fizeram o que parecia  mal aos meus olhos, e me provocaram à ira, desde o dia em que seus pais saíram do Egito até hoje.

[[v12-21-16]]

^<<v12-21-16,16>>^ De mais disto, também Manassés derramou muitíssimo sangue inocente, até que encheu a Jerusalém de um ao outro extremo, afora o seu pecado, com que fez pecar a Judá, fazendo o que parecia  mal aos olhos do Senhor.

[[v12-21-17]]

^<<v12-21-17,17>>^ Quanto ao mais dos atos de Manassés, e a tudo quanto fez mais , e ao seu pecado, que pecou, porventura  não está  escrito no livro das crônicas dos reis de Judá?

[[v12-21-18]]

^<<v12-21-18,18>>^ E Manassés dormiu com seus pais, e foi sepultado no jardim da sua casa, no jardim de Uzá: e Amom, seu filho, reinou em seu lugar.

[[v12-21-19]]

^<<v12-21-19,19>>^ Tinha Amom vinte e dois anos de idade, quando começou a reinar, e dois anos reinou em Jerusalém: e era  o nome de sua mãe Mesulemete, filha de Haruz, de Jotbá.

[[v12-21-20]]

^<<v12-21-20,20>>^ E fez o que parecia  mal aos olhos do Senhor, como fizera Manassés, seu pai.

[[v12-21-21]]

^<<v12-21-21,21>>^ Porque andou em todo o caminho em  que andara seu pai: e serviu os ídolos, a que seu pai tinha servido, e se inclinou diante deles.

[[v12-21-22]]

^<<v12-21-22,22>>^ Assim deixou ao Senhor, Deus de seus pais, e não andou no caminho do Senhor.

[[v12-21-23]]

^<<v12-21-23,23>>^ E os servos de Amom conspiraram contra ele, e mataram o rei em sua casa.

[[v12-21-24]]

^<<v12-21-24,24>>^ Porém o povo da terra feriu a todos os que conspiraram contra o rei Amom: e o povo da terra pôs a Josias, seu filho, rei em seu lugar.

[[v12-21-25]]

^<<v12-21-25,25>>^ Quanto ao mais dos sucessos de Amom, que fez, porventura  não está  escrito no livro das crônicas dos reis de Judá?

[[v12-21-26]]

^<<v12-21-26,26>>^ E o sepultaram na sua sepultura, no jardim de Uzá: e Josias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[&#60; Capítulo Anterior] | <<v12-21-0,Topo>> | xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[Próximo Capítulo &#62;]