include::./index.adoc[]

[[v12-16-0]]
=== 2 Reis, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-16-1]]

^<<v12-16-1,1>>^ NO ano dezessete de Peca, filho de Remalias, começou a reinar Acaz, filho de Jotão, rei de Judá.

[[v12-16-2]]

^<<v12-16-2,2>>^ Tinha Acaz vinte anos de idade quando começou a reinar, e reinou dezesseis anos em Jerusalém, e não fez o que era  reto aos olhos do Senhor seu Deus, como Davi, seu pai.

[[v12-16-3]]

^<<v12-16-3,3>>^ Porque andou no caminho dos reis de Israel: e até a seu filho fez passar pelo fogo, segundo as abominações dos gentios que o Senhor lançara fora de diante dos filhos de Israel.

[[v12-16-4]]

^<<v12-16-4,4>>^ Também sacrificou, e queimou incenso nos altos e nos outeiros, como também debaixo de todo o arvoredo.

[[v12-16-5]]

^<<v12-16-5,5>>^ Então subiu Resim, rei da Síria, com Peca, filho de Remalias, rei de Israel, a Jerusalém, à peleja; e cercaram a Acaz, porém não o puderam vencer.

[[v12-16-6]]

^<<v12-16-6,6>>^ Naquele mesmo tempo Resim, rei da Síria, restituiu Elate à Síria, e lançou fora de Elate os judeus: e os siros vieram a Elate, e habitaram ali até ao dia de  hoje.

[[v12-16-7]]

^<<v12-16-7,7>>^ E Acaz enviou mensageiros a Tiglate-Pileser, rei da Assíria, dizendo: Eu sou  teu servo e teu filho; sobe, e livra-me das mãos do rei da Síria, e das mãos do rei de Israel, que se levantam contra mim.

[[v12-16-8]]

^<<v12-16-8,8>>^ E tomou Acaz a prata e o ouro que se achou na casa do Senhor e nos tesouros da casa do rei, e mandou um  presente ao rei da Assíria.

[[v12-16-9]]

^<<v12-16-9,9>>^ E o rei da Assíria lhe deu ouvidos; pois o rei da Assíria subiu contra Damasco, e tomou-a, e levou o povo  para Quir, e matou a Resim.

[[v12-16-10]]

^<<v12-16-10,10>>^ Então o rei Acaz foi a Damasco, a encontrar-se com Tiglate-Pileser, rei da Assíria; e, vendo um altar que estava  em Damasco, o rei Acaz enviou ao sacerdote Urias a semelhança do altar, e o modelo conforme toda a sua obra.

[[v12-16-11]]

^<<v12-16-11,11>>^ E Urias, o sacerdote, edificou um altar conforme tudo o que o rei Acaz tinha ordenado de Damasco; assim o fez o sacerdote Urias, antes que o rei Acaz viesse de Damasco.

[[v12-16-12]]

^<<v12-16-12,12>>^ Vindo pois o rei de Damasco, o rei viu o altar; e o rei se chegou ao altar, e sacrificou nele.

[[v12-16-13]]

^<<v12-16-13,13>>^ E queimou o seu holocausto, e a sua oferta de manjares, e derramou a sua libação; e espargiu o sangue dos seus sacrifícios pacíficos naquele altar.

[[v12-16-14]]

^<<v12-16-14,14>>^ Porém o altar de cobre, que estava  perante o Senhor, tirou de diante da casa, de entre o seu altar e a casa do Senhor, e pô-lo ao lado do seu  altar, da banda do norte.

[[v12-16-15]]

^<<v12-16-15,15>>^ E o rei Acaz mandou a Urias o sacerdote, dizendo: No grande altar queima o holocausto da manhã, como também a oferta de manjares da noite, e o holocausto do rei, e a sua oferta de manjares e o holocausto de todo o povo da terra, a sua oferta de manjares, e as suas ofertas de bebida; e todo o sangue dos holocaustos, e todo o sangue dos sacrifícios espargirás nele; porém o altar de cobre será para mim, para inquirir dele.

[[v12-16-16]]

^<<v12-16-16,16>>^ E fez Urias, o sacerdote, conforme tudo quanto o rei Acaz lhe ordenara.

[[v12-16-17]]

^<<v12-16-17,17>>^ E o rei Acaz cortou as cintas das bases, e de cima delas tomou a pia, e o mar tirou-o de sobre os bois de cobre que estavam  debaixo dele, e pô-lo sobre um pavimento de pedra.

[[v12-16-18]]

^<<v12-16-18,18>>^ Também a coberta do sábado, que edificaram na casa, e a entrada de fora do rei retirou da casa do Senhor, por causa do rei da Assíria.

[[v12-16-19]]

^<<v12-16-19,19>>^ Ora o mais dos sucessos de Acaz, e o que fez, porventura  não está  escrito no livro das crônicas dos reis de Judá?

[[v12-16-20]]

^<<v12-16-20,20>>^ E dormiu Acaz com seus pais, e foi sepultado junto a seus pais, na cidade de Davi; e Ezequias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[&#60; Capítulo Anterior] | <<v12-16-0,Topo>> | xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[Próximo Capítulo &#62;]