include::./index.adoc[]

[[v12-6-0]]
=== 2 Reis, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-6-1]]

^<<v12-6-1,1>>^ E DISSERAM os filhos dos profetas a Eliseu: Eis que o lugar em que habitamos diante da tua face, nos é estreito.

[[v12-6-2]]

^<<v12-6-2,2>>^ Vamos pois até ao Jordão, e tomemos de lá, cada um de nós, uma viga, e façamo-nos ali um lugar, para habitar ali. E disse ele : Ide.

[[v12-6-3]]

^<<v12-6-3,3>>^ E disse um: Serve-te de ires com os teus servos. E disse: Eu irei.

[[v12-6-4]]

^<<v12-6-4,4>>^ E foi com eles; e, chegando eles ao Jordão, cortaram madeira.

[[v12-6-5]]

^<<v12-6-5,5>>^ E sucedeu que, derribando um deles  uma viga, o ferro caiu na água: e clamou, e disse: Ai, meu senhor! porque era emprestado.

[[v12-6-6]]

^<<v12-6-6,6>>^ E disse o homem de Deus: Onde caiu? E mostrando-lhe ele  o lugar, cortou um  pau, e o lançou ali, e fez nadar o ferro.

[[v12-6-7]]

^<<v12-6-7,7>>^ E disse: Levanta-o. Então ele estendeu a sua mão e o tomou.

[[v12-6-8]]

^<<v12-6-8,8>>^ E o rei da Síria fazia guerra a Israel; e consultou com os seus servos dizendo: Em tal e em tal lugar estará  o meu acampamento.

[[v12-6-9]]

^<<v12-6-9,9>>^ Mas o homem de Deus enviou ao rei de Israel, dizendo: Guarda-te de passares por tal lugar; porque os siros desceram ali.

[[v12-6-10]]

^<<v12-6-10,10>>^ Pelo que o rei de Israel enviou àquele lugar de que o homem de Deus lhe falara, e de que  o tinha avisado, e se guardou ali, não uma nem duas vezes.

[[v12-6-11]]

^<<v12-6-11,11>>^ Então se turbou com este incidente o coração do rei da Síria, e chamou os seus servos e lhes disse: Não me fareis saber quem dos nossos é  pelo rei de Israel?

[[v12-6-12]]

^<<v12-6-12,12>>^ E disse um dos seus servos: Não, ó rei meu senhor; mas o profeta Eliseu, que está  em Israel, faz saber ao rei de Israel as palavras que tu falas na tua câmara de dormir.

[[v12-6-13]]

^<<v12-6-13,13>>^ E ele disse: Vai, e vê onde ele  está, para que envie, e mande trazê-lo. E fizeram-lhe saber, dizendo: Eis que está  em Dotã.

[[v12-6-14]]

^<<v12-6-14,14>>^ Então enviou para lá cavalos, e carros e um grande exército, os quais vieram de noite, e cercaram a cidade.

[[v12-6-15]]

^<<v12-6-15,15>>^ E o moço do homem de Deus se levantou mui cedo, e saiu, e eis que um exército tinha cercado a cidade com cavalos e carros; então o seu moço lhe disse: Ai, meu senhor! que faremos?

[[v12-6-16]]

^<<v12-6-16,16>>^ E ele disse: Não temas; porque mais são os que estão conosco do que os que estão  com eles.

[[v12-6-17]]

^<<v12-6-17,17>>^ E orou Eliseu, e disse: Senhor, peço-te que lhe abras os olhos, para que veja. E o Senhor abriu os olhos do moço, e viu; e eis que o monte estava  cheio de cavalos e carros de fogo, em redor de Eliseu.

[[v12-6-18]]

^<<v12-6-18,18>>^ E, como desceram a ele, Eliseu orou ao Senhor, e disse: Fere, peço-te, esta gente de cegueira. E feriu-a de cegueira, conforme a palavra de Eliseu.

[[v12-6-19]]

^<<v12-6-19,19>>^ Então Eliseu lhes disse: Não é este o caminho, nem  é esta a cidade; segui-me, e guiar-vos-ei ao homem que buscais. E os guiou a Samaria.

[[v12-6-20]]

^<<v12-6-20,20>>^ E sucedeu que, chegando eles a Samaria, disse Eliseu: Ó Senhor, abre a estes os olhos para que vejam. O Senhor lhes abriu os olhos, para que vissem, e eis que estavam  no meio de Samaria.

[[v12-6-21]]

^<<v12-6-21,21>>^ E, quando o rei de Israel os viu, disse a Eliseu: Feri- los- ei, feri- los- ei, meu pai?

[[v12-6-22]]

^<<v12-6-22,22>>^ Mas ele disse: Não os  ferirás; feririas tu os que tomasses prisioneiros com a tua espada e com o teu arco? Põe-lhes diante pão e água, para que comam e bebam, e se vão para seu senhor.

[[v12-6-23]]

^<<v12-6-23,23>>^ E apresentou-lhes um grande banquete, e comeram e beberam: e os despediu e foram para seu senhor: e não entraram mais tropas de siros na terra de Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ E sucedeu, depois disto, que Benadade, rei da Síria, ajuntou todo o seu exército: e subiu, e cercou a Samaria.

[[v12-6-25]]

^<<v12-6-25,25>>^ E houve grande fome em Samaria, porque eis que a cercaram, até que se vendeu uma cabeça dum jumento por oitenta peças de prata, e a quarta parte dum  cabo de esterco de pombas por cinco peças  de prata.

[[v12-6-26]]

^<<v12-6-26,26>>^ E sucedeu que, passando o rei pelo muro uma mulher lhe bradou, dizendo: Acode- me , ó rei meu senhor.

[[v12-6-27]]

^<<v12-6-27,27>>^ E ele lhe disse: Se  o Senhor te não acode, donde te acudirei eu , da eira ou do lagar?

[[v12-6-28]]

^<<v12-6-28,28>>^ Disse-lhe mais o rei: Que tens? E disse ela: Esta mulher me disse: Dá cá  o teu filho, para que hoje o comamos e amanhã comeremos o meu filho.

[[v12-6-29]]

^<<v12-6-29,29>>^ Cozemos pois o meu filho, e o comemos; mas dizendo-lhe eu ao outro dia: Dá cá  o teu filho para que o comamos; escondeu o seu filho.

[[v12-6-30]]

^<<v12-6-30,30>>^ E sucedeu que, ouvindo o rei as palavras desta mulher, rasgou os seus vestidos, e ia passando pelo muro; e o povo viu que trazia  cilício por dentro, sobre a sua carne.

[[v12-6-31]]

^<<v12-6-31,31>>^ E disse: Assim me faça Deus, e outro tanto, se a cabeça de Eliseu, filho de Safate, hoje ficar sobre ele.

[[v12-6-32]]

^<<v12-6-32,32>>^ Estava então Eliseu assentado em sua casa, e também  os anciãos estavam assentados com ele. E enviou o rei um homem de diante de si; mas, antes que o mensageiro viesse a ele, disse ele aos anciãos: Vistes como o filho do homicida mandou tirar-me a cabeça? Olhai, quando vier o mensageiro, fechai-lhe a porta, e empurrai-o para fora  com a porta; porventura  não vem  o ruído dos pés de seu senhor após ele?

[[v12-6-33]]

^<<v12-6-33,33>>^ E, estando ele ainda falando com eles, eis que o mensageiro descia a ele; e disse: Eis que este mal vem  do Senhor, que mais pois  esperaria do Senhor?

'''

xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[Próximo Capítulo &#62;]