include::./index.adoc[]

[[v12-18-0]]
=== 2 Reis, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-18-1]]

^<<v12-18-1,1>>^ E SUCEDEU que , no terceiro ano de Oseias, filho de Ela, rei de Israel, começou a reinar Ezequias, filho de Acaz, rei de Judá.

[[v12-18-2]]

^<<v12-18-2,2>>^ Tinha vinte e cinco anos de idade quando começou a reinar, e vinte e nove anos reinou em Jerusalém: e era  o nome de sua mãe Abi, filha de Zacarias.

[[v12-18-3]]

^<<v12-18-3,3>>^ E fez o que era  reto aos olhos do Senhor, conforme tudo o que fizera Davi, seu pai.

[[v12-18-4]]

^<<v12-18-4,4>>^ Este tirou os altos, e quebrou as estátuas, e deitou abaixo os bosques, e fez em pedaços a serpente de metal que Moisés fizera: porquanto até àquele dia os filhos de Israel lhe queimavam incenso, e lhe chamaram Neustã.

[[v12-18-5]]

^<<v12-18-5,5>>^ No Senhor Deus de Israel confiou, de maneira que depois dele não houve seu semelhante entre todos os reis de Judá, nem entre  os que foram antes dele.

[[v12-18-6]]

^<<v12-18-6,6>>^ Porque se chegou ao Senhor, não se apartou de após ele, e guardou os mandamentos que o Senhor tinha dado a Moisés.

[[v12-18-7]]

^<<v12-18-7,7>>^ Assim foi o Senhor com ele; para onde quer que saía se conduzia com prudência: e se revoltou contra o rei da Assíria, e não o serviu.

[[v12-18-8]]

^<<v12-18-8,8>>^ Ele feriu os filisteus até Gaza, como também os termos dela, desde a torre dos atalaias até à cidade forte.

[[v12-18-9]]

^<<v12-18-9,9>>^ E sucedeu, no quarto ano do rei Ezequias (que era o sétimo ano de Oseias, filho de Ela, rei de Israel), que Salmanasar, rei da Assíria, subiu contra Samaria, e a cercou.

[[v12-18-10]]

^<<v12-18-10,10>>^ E a tomaram ao fim de três anos, no ano sexto de Ezequias, que era o ano nono de Oseias, rei de Israel, quando tomaram Samaria.

[[v12-18-11]]

^<<v12-18-11,11>>^ E o rei da Assíria transportou a Israel para a Assíria: e os fez levar para Hala e para Habor, junto ao  rio de Gozã, e às cidades dos medos;

[[v12-18-12]]

^<<v12-18-12,12>>^ Porquanto não obedeceram à voz do Senhor seu Deus, antes traspassaram o seu concerto: e  tudo quanto Moisés, servo do Senhor, tinha ordenado, nem o ouviram nem o  fizeram.

[[v12-18-13]]

^<<v12-18-13,13>>^ Porém no ano décimo quarto do rei Ezequias subiu Senaqueribe, rei da Assíria, contra todas as cidades fortes de Judá, e as tomou.

[[v12-18-14]]

^<<v12-18-14,14>>^ Então Ezequias, rei de Judá, enviou ao rei da Assíria, a Laquis, dizendo: Pequei; retira-te de mim; tudo o que me impuseres levarei. Então o rei da Assíria impôs a Ezequias, rei de Judá, trezentos talentos de prata e trinta talentos de ouro.

[[v12-18-15]]

^<<v12-18-15,15>>^ Assim deu Ezequias toda a prata que se achou na casa do Senhor e nos tesouros da casa do rei.

[[v12-18-16]]

^<<v12-18-16,16>>^ Naquele tempo cortou Ezequias o ouro  das portas do templo do Senhor, e das ombreiras, de que Ezequias, rei de Judá, as cobrira, e o deu ao rei da Assíria.

[[v12-18-17]]

^<<v12-18-17,17>>^ Contudo enviou o rei da Assíria a Tartã, e a Rabsaris e a Rabsaqué, de Laquis, com um grande exército, ao rei Ezequias, a Jerusalém: e subiram, e vieram a Jerusalém; e, subindo e vindo eles, pararam ao pé do aqueduto da piscina superior, que está junto ao caminho do campo do lavandeiro.

[[v12-18-18]]

^<<v12-18-18,18>>^ E chamaram o rei, e saiu a eles Eliaquim, filho de Hilquias, o mordomo, e Sebna, o escrivão, e Joá, filho de Asafe, o chanceler.

[[v12-18-19]]

^<<v12-18-19,19>>^ E Rabsaqué lhes disse: Ora dizei a Ezequias: Assim diz o grande rei, o rei da Assíria: Que confiança é esta em que confias?

[[v12-18-20]]

^<<v12-18-20,20>>^ Dizes tu  (porém palavra de lábios é) : Há conselho e poder para a guerra. Em que pois  agora confias, que contra mim te revoltas?

[[v12-18-21]]

^<<v12-18-21,21>>^ Eis que agora tu confias naquele bordão de cana quebrada, no Egito, no qual, se alguém se encostar, entrar-lhe-á pela mão e lha furará; assim é Faraó, rei do Egito, para com todos os que nele confiam.

[[v12-18-22]]

^<<v12-18-22,22>>^ Se porém me disserdes: No Senhor nosso Deus confiamos: porventura  não é  este aquele cujos os altos e cujos altares Ezequias tirou, dizendo a Judá e a Jerusalém: Perante este altar vos inclinareis em Jerusalém?

[[v12-18-23]]

^<<v12-18-23,23>>^ Ora pois dá agora reféns ao meu senhor, o rei da Assíria, e dar-te-ei dois mil cavalos, se tu puderes dar cavaleiros para eles.

[[v12-18-24]]

^<<v12-18-24,24>>^ Como pois farias virar o rosto dum só príncipe dos menores servos de meu senhor? Porém tu confias no Egito, por causa dos carros e cavaleiros.

[[v12-18-25]]

^<<v12-18-25,25>>^ Agora pois  subi eu porventura  sem o Senhor contra este lugar, para o destruir? O Senhor me disse: Sobe contra esta terra, e destrói-a.

[[v12-18-26]]

^<<v12-18-26,26>>^ Então disse Eliaquim, filho de Hilquias, e Sebna, e Joá, a Rabsaqué: Rogamos- te que  fales aos teus servos em siríaco; porque bem o entendemos; e não nos fales em judaico, aos ouvidos do povo que está  em cima do muro.

[[v12-18-27]]

^<<v12-18-27,27>>^ Porém Rabsaqué lhes disse: Porventura  mandou-me meu senhor só  a teu senhor e a ti, para falar estas palavras? e  não antes aos homens, que estão sentados em cima do muro, para que juntamente convosco comam o seu esterco e bebam a sua urina?

[[v12-18-28]]

^<<v12-18-28,28>>^ Rabsaqué pois se pôs em pé, e clamou em alta voz em judaico, e falou, e disse: Ouvi a palavra do grande rei, do rei da Assíria.

[[v12-18-29]]

^<<v12-18-29,29>>^ Assim diz o rei: Não vos engane Ezequias; porque não vos poderá livrar da sua mão;

[[v12-18-30]]

^<<v12-18-30,30>>^ Nem tão pouco vos faça Ezequias confiar no Senhor, dizendo: Certamente nos livrará o Senhor, e esta cidade não será entregue na mão do rei da Assíria.

[[v12-18-31]]

^<<v12-18-31,31>>^ Não deis ouvidos a Ezequias; porque assim diz o rei da Assíria: Contratai comigo por presentes, e saí a mim, e coma cada um da sua vide, e da sua figueira, e beba cada um a água da sua cisterna.

[[v12-18-32]]

^<<v12-18-32,32>>^ Até que eu venha, e vos leve para uma terra como a vossa, terra de trigo e de mosto, terra de pão e de vinhas, terra de oliveiras, de azeite, e de mel: e assim  vivereis, e não morrereis: e não deis ouvidos a Ezequias; porque vos incita, dizendo: O Senhor nos livrará.

[[v12-18-33]]

^<<v12-18-33,33>>^ Porventura  os deuses das nações puderam livrar, cada um a sua terra, das mãos do rei da Assíria?

[[v12-18-34]]

^<<v12-18-34,34>>^ Que é feito  dos deuses de Hamate e de Arpade? Que é feito  dos deuses de Sefarvaim, Hena e Iva? porventura  livraram a Samaria da minha mão?

[[v12-18-35]]

^<<v12-18-35,35>>^ Quais são  eles dentre todos os deuses das terras, os que livraram a sua terra da minha mão, para que o Senhor livrasse a Jerusalém da minha mão?

[[v12-18-36]]

^<<v12-18-36,36>>^ Porém calou-se o povo, e não lhe respondeu uma só palavra; porque mandado do rei havia, dizendo: Não lhe respondereis.

[[v12-18-37]]

^<<v12-18-37,37>>^ Então Eliaquim, filho de Hilquias, o mordomo, e Sebna, o escrivão, e Joá, filho de Asafe, o chanceler, vieram a Ezequias com os vestidos rasgados, e lhe fizeram saber as palavras de Rabsaqué.

'''

xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[&#60; Capítulo Anterior] | <<v12-18-0,Topo>> | xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[Próximo Capítulo &#62;]