include::./index.adoc[]

[[v12-8-0]]
=== 2 Reis, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-8-1]]

^<<v12-8-1,1>>^ E FALOU Eliseu àquela mulher cujo filho vivificara, dizendo: Levanta-te, e vai-te, tu e a tua família, e peregrina onde puderes peregrinar; porque o Senhor chamou a fome, a qual também virá à terra por  sete anos.

[[v12-8-2]]

^<<v12-8-2,2>>^ E levantou-se a mulher e fez conforme a palavra do homem de Deus: porque foi ela com a sua família, e peregrinou na terra dos filisteus sete anos.

[[v12-8-3]]

^<<v12-8-3,3>>^ E sucedeu que, ao cabo dos sete anos, a mulher voltou da terra dos filisteus, e saiu a clamar ao rei pela sua casa e pelas suas terras.

[[v12-8-4]]

^<<v12-8-4,4>>^ Ora o rei falava a Geazi, moço do homem de Deus, dizendo: Conta-me, peço-te, todas as grandes obras que Eliseu tem feito.

[[v12-8-5]]

^<<v12-8-5,5>>^ E sucedeu que, contando ele ao rei como vivificara a um morto, eis que a mulher cujo filho vivificara clamou ao rei pela sua casa e pelas suas terras: então disse Geazi: Ó rei meu senhor, esta é  a mulher, e este o seu filho a quem Eliseu vivificou.

[[v12-8-6]]

^<<v12-8-6,6>>^ E o rei perguntou à mulher e ela lho contou: então o rei lhe deu um eunuco, dizendo: Faze- lhe  restituir tudo quanto era  seu, e todas as rendas das terras desde o dia em que deixou a terra até agora.

[[v12-8-7]]

^<<v12-8-7,7>>^ Depois veio Eliseu a Damasco, estando Benadade, rei da Síria, doente; e lho anunciaram, dizendo: O homem de Deus é chegado aqui.

[[v12-8-8]]

^<<v12-8-8,8>>^ Então o rei disse a Hazael: Toma um  presente na tua mão, e vai a encontrar-te com o homem de Deus: e pergunta por ele ao Senhor, dizendo: Hei de eu sarar desta doença?

[[v12-8-9]]

^<<v12-8-9,9>>^ Foi pois Hazael a encontrar-se com ele, e tomou um  presente na sua mão, a saber: de  tudo que era  bom de Damasco, quarenta camelos carregados; e veio, e se pôs diante dele, e disse: Teu filho Benadade, rei da Síria, me enviou a ti, a dizer: Sararei eu desta doença?

[[v12-8-10]]

^<<v12-8-10,10>>^ E Eliseu lhe disse: Vai, e dize-lhe: Certamente não sararás. Porque o Senhor me tem mostrado que certamente morrerá.

[[v12-8-11]]

^<<v12-8-11,11>>^ E afirmou a sua vista, e fitou os olhos  nele até se envergonhar: e chorou o homem de Deus.

[[v12-8-12]]

^<<v12-8-12,12>>^ Então disse Hazael: Por que chora meu senhor? E ele disse: Porque sei o mal que hás de fazer aos filhos de Israel: porás fogo às suas fortalezas, e os seus mancebos matarás à espada, e os seus meninos despedaçarás, e as suas pejadas fenderás.

[[v12-8-13]]

^<<v12-8-13,13>>^ E disse Hazael: Pois que é teu servo, que não é mais do que um cão, para fazer tão grande cousa? E disse Eliseu: O Senhor me tem mostrado que tu hás de ser  rei da Síria.

[[v12-8-14]]

^<<v12-8-14,14>>^ Então partiu de Eliseu, e veio a seu senhor, o qual lhe disse: Que te disse Eliseu? E disse ele: Disse-me que  certamente sararás.

[[v12-8-15]]

^<<v12-8-15,15>>^ E sucedeu ao outro dia que tomou um cobertor, e o molhou na água, e o estendeu sobre o seu rosto, e morreu. E Hazael reinou em seu lugar.

[[v12-8-16]]

^<<v12-8-16,16>>^ E no ano quinto de Jorão, filho de Acabe, rei de Israel, reinando ainda  Josafá em Judá, começou a reinar Jeorão, filho de Josafá, rei de Judá.

[[v12-8-17]]

^<<v12-8-17,17>>^ Era ele da idade de trinta e dois anos quando começou a reinar, e oito anos reinou em Jerusalém.

[[v12-8-18]]

^<<v12-8-18,18>>^ E andou no caminho dos reis de Israel, como também  fizeram os da casa de Acabe, porque tinha por mulher a filha de Acabe, e fez o que parecia  mal aos olhos do Senhor.

[[v12-8-19]]

^<<v12-8-19,19>>^ Porém o Senhor não quis destruir a Judá por amor de Davi, seu servo, como lhe tinha dito que lhe daria para sempre uma lâmpada a seus filhos.

[[v12-8-20]]

^<<v12-8-20,20>>^ Nos seus dias se revoltaram os edomitas contra o mando de Judá e puseram sobre si um  rei.

[[v12-8-21]]

^<<v12-8-21,21>>^ Pelo que Jeorão passou a Zair, e todos os carros com ele: e ele se levantou de noite, e feriu os edomitas que estavam ao redor dele, e os capitães dos carros; e o povo foi para as suas tendas.

[[v12-8-22]]

^<<v12-8-22,22>>^ Todavia os edomitas ficaram revoltados contra o mando de Judá até ao dia de  hoje: então também , se revoltou Libna no mesmo tempo.

[[v12-8-23]]

^<<v12-8-23,23>>^ O mais dos sucessos de Jeorão, e tudo quanto fez porventura  não está  escrito no livro das crônicas de Judá?

[[v12-8-24]]

^<<v12-8-24,24>>^ E Jeorão dormiu com seus pais, e foi sepultado com seus pais na cidade de Davi: e Acazias, seu filho, reinou em seu lugar.

[[v12-8-25]]

^<<v12-8-25,25>>^ No ano doze de Jorão filho de Acabe, rei de Israel, começou a reinar Acazias, filho de Jeorão, rei de Judá.

[[v12-8-26]]

^<<v12-8-26,26>>^ Era  Acazias de vinte e dois anos de idade quando começou a reinar, e reinou um ano em Jerusalém; e era  o nome de sua mãe Atália, filha de Onri, rei de Israel.

[[v12-8-27]]

^<<v12-8-27,27>>^ E andou no caminho da casa de Acabe, e fez mal aos olhos do Senhor, como a casa de Acabe, porque era  genro da casa de Acabe.

[[v12-8-28]]

^<<v12-8-28,28>>^ E foi com Jorão, filho de Acabe, a Ramote, de Gileade, à peleja contra Hazael, rei da Síria; e os siros feriram a Jorão.

[[v12-8-29]]

^<<v12-8-29,29>>^ Então voltou o rei Jorão para se curar em Jezreel das feridas que os siros lhe fizeram em Ramá, quando pelejou contra Hazael, rei da Síria: e desceu Acazias, filho de Jeorão, rei de Judá para ver a Jorão, filho de Acabe em Jezreel, porquanto estava doente.

'''

xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[Próximo Capítulo &#62;]