include::./index.adoc[]

[[v12-7-0]]
=== 2 Reis, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-7-1]]

^<<v12-7-1,1>>^ ENTÃO disse Eliseu: Ouvi a palavra do Senhor: assim diz o Senhor: Amanhã, quase a este tempo, uma medida de farinha haverá  por um siclo, e duas medidas de cevada por um siclo, à porta de Samaria.

[[v12-7-2]]

^<<v12-7-2,2>>^ Porém um capitão, em cuja mão o rei se encostava, respondeu ao homem de Deus e disse: Eis que ainda que o Senhor fizesse janelas no céu, poder-se-ia fazer isso? E ele disse: Eis que o  verás com os teus olhos, porém daí não comerás.

[[v12-7-3]]

^<<v12-7-3,3>>^ E quatro homens leprosos estavam à entrada da porta, os quais disseram uns aos outros: Para que estaremos nós aqui até morrermos?

[[v12-7-4]]

^<<v12-7-4,4>>^ Se dissermos: Entremos na cidade, há fome na cidade, e morreremos aí; e se ficarmos aqui, também morreremos: vamos nós pois agora, e demos conosco no arraial dos siros: se nos deixarem viver; viveremos, e se nos matarem, tão somente morreremos.

[[v12-7-5]]

^<<v12-7-5,5>>^ E levantaram-se ao crepúsculo, para irem ao arraial dos siros; e, chegando à entrada do arraial dos siros, eis que não havia  ali ninguém.

[[v12-7-6]]

^<<v12-7-6,6>>^ Porque o Senhor fizera ouvir no arraial dos siros ruído de carros e ruído de cavalos, como  o ruído dum grande exército; de maneira que disseram uns aos outros: Eis que o rei de Israel alugou contra nós os reis dos heteus e os reis dos egípcios, para virem contra nós.

[[v12-7-7]]

^<<v12-7-7,7>>^ Pelo que se levantaram, e fugiram no crepúsculo, e deixaram as suas tendas, e os seus cavalos, e os seus jumentos, e  o arraial como estava: e fugiram para salvarem  a sua vida.

[[v12-7-8]]

^<<v12-7-8,8>>^ Chegando pois estes leprosos à entrada do arraial, entraram numa tenda, e comeram e beberam e tomaram dali prata, e ouro, e vestidos, e foram, e os  esconderam: então voltaram, e entraram em outra tenda, e  dali também tomaram alguma cousa , e a esconderam.

[[v12-7-9]]

^<<v12-7-9,9>>^ Então disseram uns para os outros: Não fazemos bem: este dia é  dia de boas novas, e nos calamos; se esperarmos até à luz da manhã, algum mal nos sobrevirá; pelo que agora vamos e o anunciemos à casa do rei.

[[v12-7-10]]

^<<v12-7-10,10>>^ Vieram pois, e bradaram aos porteiros da cidade, e lhes anunciaram, dizendo: Fomos ao arraial dos siros e eis que lá não havia  ninguém, nem voz de homem, porém, só cavalos atados, e jumentos atados, e as tendas como estavam dantes.

[[v12-7-11]]

^<<v12-7-11,11>>^ E chamaram os porteiros, e estes  o anunciaram dentro da casa do rei.

[[v12-7-12]]

^<<v12-7-12,12>>^ E o rei se levantou de noite, e disse aos seus servos: Agora vos farei saber o que é que os siros nos fizeram: bem  sabem eles que esfaimados estamos ; pelo que saíram do arraial, a esconder-se pelo campo, dizendo: Quando saírem da cidade, então os tomaremos vivos, e entraremos na cidade.

[[v12-7-13]]

^<<v12-7-13,13>>^ Então um dos seus servos respondeu e disse: Tomem-se pois cinco dos cavalos do resto que ficou aqui dentro  (eis que são  como toda a multidão dos israelitas que ficaram aqui de resto, e eis que são  como toda a multidão dos israelitas que já  pereceram) e enviemo-los, e vejamos.

[[v12-7-14]]

^<<v12-7-14,14>>^ Tomaram pois dois cavalos de carro; e o rei os enviou após o exército dos siros, dizendo: Ide, e vede.

[[v12-7-15]]

^<<v12-7-15,15>>^ E foram após eles até ao Jordão, e eis que todo o caminho estava  cheio de vestidos e de aviamentos, que os siros, apressando-se, lançaram fora: e voltaram os mensageiros, e o anunciaram ao rei.

[[v12-7-16]]

^<<v12-7-16,16>>^ Então saiu o povo e saqueou o arraial dos siros: e havia uma medida de farinha por um siclo, e duas medidas de cevada por um siclo, conforme a palavra do Senhor.

[[v12-7-17]]

^<<v12-7-17,17>>^ E pusera o rei à porta o capitão em cuja mão se encostava: e o povo o atropelou na porta, e ele morreu, como falara o homem de Deus, o que falou quando o rei descera a ele.

[[v12-7-18]]

^<<v12-7-18,18>>^ Porque assim  sucedeu como o homem de Deus falara ao rei, dizendo: Amanhã, quase a este tempo, haverá duas medidas de cevada por um siclo, e uma medida de farinha por um siclo, à porta de Samaria.

[[v12-7-19]]

^<<v12-7-19,19>>^ E aquele capitão respondeu ao homem de Deus, e disse: Eis que ainda que o Senhor fizesse janelas no céu, poder-se-ia isso fazer conforme essa palavra? E ele disse: Eis que o verás com os teus olhos, porém daí não comerás.

[[v12-7-20]]

^<<v12-7-20,20>>^ E assim lhe sucedeu, porque o povo o atropelou à porta, e ele morreu.

'''

xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[Próximo Capítulo &#62;]