include::./index.adoc[]

[[v12-4-0]]
=== 2 Reis, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-4-1]]

^<<v12-4-1,1>>^ E UMA mulher das mulheres dos filhos dos profetas, clamou a Eliseu, dizendo: Meu marido, teu servo, morreu; e tu sabes que o teu servo temia ao Senhor; e veio o credor, a levar-me os meus dois filhos para serem servos.

[[v12-4-2]]

^<<v12-4-2,2>>^ E Eliseu lhe disse: Que te hei de eu fazer? Declara-me que é o que  tens em casa. E ela disse: Tua serva não tem nada em casa, senão uma botija de azeite.

[[v12-4-3]]

^<<v12-4-3,3>>^ Então disse ele: Vai, pede para ti vasos emprestados a todos os teus vizinhos, vasos vazios, não poucos.

[[v12-4-4]]

^<<v12-4-4,4>>^ Então entra, e fecha a porta sobre ti, e sobre teus filhos, e deita o azeite em todos aqueles vasos, e põe à parte o que estiver cheio.

[[v12-4-5]]

^<<v12-4-5,5>>^ Partiu pois dele, e fechou a porta sobre si e sobre seus filhos; e eles lhe traziam os vasos , e ela os  enchia.

[[v12-4-6]]

^<<v12-4-6,6>>^ E sucedeu que, cheios que foram os vasos, disse a seu filho: Traze-me ainda um vaso. Porém ele lhe disse: Não há  mais vaso nenhum. Então o azeite parou.

[[v12-4-7]]

^<<v12-4-7,7>>^ Então veio ela, e o  fez saber ao homem de Deus; e disse ele: Vai, vende o azeite, e paga a tua dívida; e tu e teus filhos vivei do resto.

[[v12-4-8]]

^<<v12-4-8,8>>^ Sucedeu também um dia que, indo Eliseu a Suném, havia ali  uma mulher grave, a qual o reteve a comer pão: e sucedeu que todas as vezes que passava, ali se dirigia a comer pão.

[[v12-4-9]]

^<<v12-4-9,9>>^ E ela disse a seu marido: Eis que tenho observado, que este que passa sempre por nós é um santo homem de Deus.

[[v12-4-10]]

^<<v12-4-10,10>>^ Façamos- lhe  pois um pequeno quarto junto ao muro, e ali lhe ponhamos uma cama, e uma mesa, e uma cadeira e um candeeiro: e há de ser que, vindo ele a nós, para ali se retirará.

[[v12-4-11]]

^<<v12-4-11,11>>^ E sucedeu um dia que veio ali, e retirou-se àquele quarto, e se deitou ali.

[[v12-4-12]]

^<<v12-4-12,12>>^ Então disse ao seu moço Geazi: Chama esta sunamita. E chamando-a ele, ela se pôs diante dele.

[[v12-4-13]]

^<<v12-4-13,13>>^ Porque lhe tinha dito: Dize-lhe: Eis que tu nos tens tratado com todo o desvelo; que se há de fazer por ti? haverá alguma cousa de que se fale por ti ao rei, ou ao chefe do exército? E dissera ela: Eu habito no meio do meu povo.

[[v12-4-14]]

^<<v12-4-14,14>>^ Então disse ele: Que se há de fazer pois por ela? E Geazi disse: Ora ela não tem filho, e seu marido é velho.

[[v12-4-15]]

^<<v12-4-15,15>>^ Pelo que disse ele: Chama-a. E, chamando-a ele, ela se pôs à porta.

[[v12-4-16]]

^<<v12-4-16,16>>^ E ele  disse: A este tempo determinado, segundo o tempo da vida, abraçarás um filho. E disse ela: Não, meu senhor, homem de Deus, não mintas à tua serva.

[[v12-4-17]]

^<<v12-4-17,17>>^ E concebeu a mulher, e deu à luz um filho, no tal tempo determinado, segundo o tempo da vida que Eliseu lhe dissera.

[[v12-4-18]]

^<<v12-4-18,18>>^ E, crescendo o filho, sucedeu que um dia saiu para seu pai, que estava  com os segadores.

[[v12-4-19]]

^<<v12-4-19,19>>^ E disse a seu pai: Ai, a minha cabeça! ai, a minha cabeça! Então disse a um moço: Leva-o a sua mãe.

[[v12-4-20]]

^<<v12-4-20,20>>^ E ele o tomou e o levou a sua mãe: e esteve sobre os seus joelhos até ao meio-dia, e morreu.

[[v12-4-21]]

^<<v12-4-21,21>>^ E subiu ela, e o deitou sobre a cama do homem de Deus; e fechou sobre ele a porta , e saiu.

[[v12-4-22]]

^<<v12-4-22,22>>^ E chamou a seu marido, e disse: Manda-me já um dos moços, e uma das jumentas, para que corra ao homem de Deus, e para que volte.

[[v12-4-23]]

^<<v12-4-23,23>>^ E disse ele: Por que vais a ele hoje? não é lua nova nem sábado. E ela disse: Tudo  vai bem.

[[v12-4-24]]

^<<v12-4-24,24>>^ Então albardou a jumenta, e disse ao seu moço: Guia e anda, e não te detenhas no caminhar, senão quando eu to disser.

[[v12-4-25]]

^<<v12-4-25,25>>^ Partiu ela pois e veio ao homem de Deus, ao monte Carmelo: e sucedeu que, vendo-a o homem de Deus de longe, disse a Geazi, seu moço: Eis aí a sunamita.

[[v12-4-26]]

^<<v12-4-26,26>>^ Agora pois corre-lhe ao encontro e dize-lhe: Vai bem contigo? Vai bem com teu marido? Vai bem com teu filho? E ela disse: Vai bem.

[[v12-4-27]]

^<<v12-4-27,27>>^ Chegando ela pois ao homem de Deus, ao monte, pegou nos seus pés; mas chegou Geazi para a retirar: disse porém o homem de Deus: Deixa-a, porque a sua alma nela está triste de amargura, e o Senhor mo encobriu, e não mo manifestou.

[[v12-4-28]]

^<<v12-4-28,28>>^ E disse ela: Pedi eu a meu senhor algum  filho? Não disse eu: Não me enganes?

[[v12-4-29]]

^<<v12-4-29,29>>^ E ele disse a Geazi: cinge os teus lombos, e toma o meu bordão na tua mão, e vai; se encontrares alguém, não o saúdes, e se alguém te saudar, não lhe respondas: e põe o meu bordão sobre o rosto do menino.

[[v12-4-30]]

^<<v12-4-30,30>>^ Porém disse a mãe do menino: Vive o Senhor, e vive a tua alma, que não te hei de deixar. Então ele se levantou, e a seguiu.

[[v12-4-31]]

^<<v12-4-31,31>>^ E Geazi passou adiante deles, e pôs o bordão sobre o rosto do menino; porém não havia nele  voz nem sentido: e voltou a encontrar-se com ele, e lhe trouxe aviso, dizendo: Não despertou o menino.

[[v12-4-32]]

^<<v12-4-32,32>>^ E, chegando Eliseu àquela casa, eis que o menino jazia morto sobre a sua cama.

[[v12-4-33]]

^<<v12-4-33,33>>^ Então entrou ele, e fechou a porta sobre eles ambos, e orou ao Senhor.

[[v12-4-34]]

^<<v12-4-34,34>>^ E subiu, e deitou-se sobre o menino, e, pondo a sua boca sobre a boca dele, e os seus olhos sobre os olhos dele, e as suas mãos sobre as mãos dele, se estendeu sobre ele: e a carne do menino aqueceu.

[[v12-4-35]]

^<<v12-4-35,35>>^ Depois voltou, e passeou naquela casa duma parte para a outra, e tornou  a subir, e se estendeu sobre ele: então o menino espirrou sete vezes, e o menino abriu os olhos.

[[v12-4-36]]

^<<v12-4-36,36>>^ Então chamou a Geazi, e disse: Chama essa sunamita. E chamou-a, e veio a ele. E disse ele: Toma o teu filho.

[[v12-4-37]]

^<<v12-4-37,37>>^ E veio ela, e se prostrou a seus pés, e se inclinou à terra; e tomou o seu filho, e saiu.

[[v12-4-38]]

^<<v12-4-38,38>>^ E voltando Eliseu a Gilgal, havia  fome naquela terra, e os filhos dos profetas estavam  assentados na sua presença: e disse ao seu moço: Põe a panela grande ao lume , e faze um caldo de ervas para os filhos dos profetas.

[[v12-4-39]]

^<<v12-4-39,39>>^ Então um saiu ao campo a apanhar ervas, e achou uma parra brava, e colheu dela a sua capa cheia de coloquíntidas: e veio, e as cortou na panela do caldo; porque as  não conheciam.

[[v12-4-40]]

^<<v12-4-40,40>>^ Assim tiraram de comer para os homens. E sucedeu que, comendo eles daquele caldo, clamaram e disseram: Homem de Deus, há  morte na panela. Não puderam comer.

[[v12-4-41]]

^<<v12-4-41,41>>^ Porém ele disse: Trazei pois farinha. E deitou- a  na panela, e disse: Tirai de comer para o povo. Então não havia mal nenhum na panela.

[[v12-4-42]]

^<<v12-4-42,42>>^ E um homem veio de Baal-Salisa, e trouxe ao homem de Deus pães das primícias, vinte pães de cevada, e espigas verdes na sua palha, e disse: Dá ao povo, para que coma.

[[v12-4-43]]

^<<v12-4-43,43>>^ Porém seu servo disse: Como hei de eu pôr isto diante de cem homens? E disse ele: Dá-o ao povo, para que coma; porque assim diz o Senhor: Comer-se-á, e sobejará.

[[v12-4-44]]

^<<v12-4-44,44>>^ Então lhos pôs diante, e comeram, e deixaram sobejos, conforme a palavra do Senhor.

'''

xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[&#60; Capítulo Anterior] | <<v12-4-0,Topo>> | xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[Próximo Capítulo &#62;]