include::./index.adoc[]

[[v12-2-0]]
=== 2 Reis, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-2-1]]

^<<v12-2-1,1>>^ SUCEDEU pois que, havendo o Senhor de elevar a Elias num redemoinho ao céu, Elias partiu com Eliseu de Gilgal.

[[v12-2-2]]

^<<v12-2-2,2>>^ E disse Elias a Eliseu: Fica-te aqui, porque o Senhor me enviou a Betel. Porém Eliseu disse: Vive o Senhor, e vive a tua alma, que te não deixarei. E assim foram a Betel.

[[v12-2-3]]

^<<v12-2-3,3>>^ Então os filhos dos profetas que estavam  em Betel saíram a Eliseu, e lhe disseram: Sabes que o Senhor hoje tomará o teu senhor por de cima da tua cabeça? E ele disse: Também eu bem o  sei; calai-vos.

[[v12-2-4]]

^<<v12-2-4,4>>^ E Elias lhe disse: Eliseu, fica-te aqui, porque o Senhor me enviou a Jericó. Porém ele disse: Vive o Senhor, e vive a tua alma, que te não deixarei. E assim  vieram a Jericó.

[[v12-2-5]]

^<<v12-2-5,5>>^ Então os filhos dos profetas que estavam em Jericó se chegaram a Eliseu, e lhe disseram: Sabes que o Senhor hoje tomará o teu senhor por de cima da tua cabeça? E ele disse: Também eu bem o  sei; calai-vos.

[[v12-2-6]]

^<<v12-2-6,6>>^ E Elias disse: Fica-te aqui, porque o Senhor me enviou ao Jordão. Mas ele disse: Vive o Senhor, e vive a tua alma, que te não deixarei. E assim  ambos foram juntos.

[[v12-2-7]]

^<<v12-2-7,7>>^ E foram cinquenta homens dos filhos dos profetas, e de longe pararam defronte: e eles ambos pararam junto ao Jordão.

[[v12-2-8]]

^<<v12-2-8,8>>^ Então Elias tomou a sua capa, e a dobrou, e feriu as águas, as quais se dividiram para as duas bandas: e passaram ambos em seco.

[[v12-2-9]]

^<<v12-2-9,9>>^ Sucedeu pois que, havendo eles passado, Elias disse a Eliseu: Pede- me  o que queres que  te faça, antes que seja tomado de ti. E disse Eliseu: Peço-te que haja porção dobrada de teu espírito sobre mim.

[[v12-2-10]]

^<<v12-2-10,10>>^ E disse: Cousa dura pediste; se me vires quando for  tomado de ti, assim se te fará, porém, se não, não se fará.

[[v12-2-11]]

^<<v12-2-11,11>>^ E sucedeu que, indo eles andando e falando, eis que um carro de fogo, com cavalos de fogo, os separou um do outro: e Elias subiu ao céu num redemoinho.

[[v12-2-12]]

^<<v12-2-12,12>>^ O que vendo Eliseu, clamou: Meu pai, meu pai, carros de Israel, e seus cavaleiros! E nunca mais o viu: e, travando dos seus vestidos, os rasgou em duas partes.

[[v12-2-13]]

^<<v12-2-13,13>>^ Também levantou a capa de Elias, que lhe caíra: e voltou-se, e parou à borda do Jordão.

[[v12-2-14]]

^<<v12-2-14,14>>^ E tomou a capa de Elias, que lhe caíra, e feriu as águas, e disse: Onde está  o Senhor, Deus de Elias? Então feriu as águas, e se dividiram elas para uma e outra banda: e Eliseu passou.

[[v12-2-15]]

^<<v12-2-15,15>>^ Vendo-o pois os filhos dos profetas que estavam defronte em Jericó, disseram: O espírito de Elias repousa sobre Eliseu. E vieram-lhe ao encontro, e se prostraram diante dele em terra.

[[v12-2-16]]

^<<v12-2-16,16>>^ E disseram-lhe: Eis que com teus servos há cinquenta homens valentes: ora deixa-os ir para buscar a teu senhor; pode ser que o elevasse o Espírito do Senhor, e o lançasse nalgum dos montes, ou nalgum dos vales. Porém ele disse: Não os envieis.

[[v12-2-17]]

^<<v12-2-17,17>>^ Mas eles apertaram com ele, até se enfastiar; e disse- lhes : Enviai. E enviaram cinquenta homens, que o buscaram três dias, porém não o acharam.

[[v12-2-18]]

^<<v12-2-18,18>>^ Então voltaram para ele, tendo ele ficado em Jericó: e disse-lhes: Eu não vos disse que não fôsseis?

[[v12-2-19]]

^<<v12-2-19,19>>^ E os homens da cidade disseram a Eliseu: Eis que boa é  a habitação desta cidade, como o meu senhor vê; porém as águas são  más, e a terra é estéril.

[[v12-2-20]]

^<<v12-2-20,20>>^ E ele disse: Trazei-me uma salva nova, e ponde nela sal. E lha trouxeram.

[[v12-2-21]]

^<<v12-2-21,21>>^ Então saiu ele ao manancial das águas, e deitou sal nele; e disse: Assim diz o Senhor: Sararei a estas águas; não haverá mais nelas morte nem esterilidade.

[[v12-2-22]]

^<<v12-2-22,22>>^ Ficaram pois sãs aquelas águas até ao dia de  hoje, conforme à palavra que Eliseu tinha dito.

[[v12-2-23]]

^<<v12-2-23,23>>^ Então subiu dali a Betel; e, subindo ele pelo caminho, uns rapazes pequenos saíram da cidade, e zombavam dele, e diziam-lhe: Sobe, calvo, sobe, calvo!

[[v12-2-24]]

^<<v12-2-24,24>>^ E, virando-se ele para trás, os viu, e os amaldiçoou no nome do Senhor: então duas ursas saíram do bosque, e despedaçaram quarenta e dois daqueles pequenos.

[[v12-2-25]]

^<<v12-2-25,25>>^ E foi-se dali para o monte Carmelo: e dali voltou para Samaria.

'''

xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[&#60; Capítulo Anterior] | <<v12-2-0,Topo>> | xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[Próximo Capítulo &#62;]