include::./index.adoc[]

[[v12-3-0]]
=== 2 Reis, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-3-1]]

^<<v12-3-1,1>>^ E JORÃO, filho de Acabe, começou a reinar sobre Israel, em Samaria, no décimo oitavo ano de Josafá, rei de Judá: e reinou doze anos.

[[v12-3-2]]

^<<v12-3-2,2>>^ E fez o que era  mau aos olhos do Senhor; porém não como seu pai, nem como sua mãe; porque tirou a estátua de Baal, que seu pai fizera.

[[v12-3-3]]

^<<v12-3-3,3>>^ Contudo aderiu aos pecados de Jeroboão, filho de Nebate, que fizera pecar a Israel; não se apartou deles.

[[v12-3-4]]

^<<v12-3-4,4>>^ Então Mesa, rei dos moabitas, era contratador de gado, e pagava ao rei de Israel cem mil cordeiros, e cem mil carneiros com a sua  lã.

[[v12-3-5]]

^<<v12-3-5,5>>^ Sucedeu porém que, morrendo Acabe, se revoltou o rei dos moabitas contra o rei de Israel.

[[v12-3-6]]

^<<v12-3-6,6>>^ Por isso Jorão ao mesmo tempo saiu de Samaria, e fez revista de todo o Israel.

[[v12-3-7]]

^<<v12-3-7,7>>^ E foi, e enviou a Josafá, rei de Judá, dizendo: O rei dos moabitas se revoltou contra mim; irás tu comigo à guerra contra os moabitas? E disse ele: Subirei; e  eu serei  como tu, o meu povo como o teu povo, e  os meus cavalos como os teus cavalos.

[[v12-3-8]]

^<<v12-3-8,8>>^ E ele disse: Por que caminho subiremos? Então disse ele: Pelo caminho do deserto de Edom.

[[v12-3-9]]

^<<v12-3-9,9>>^ E partiu o rei de Israel, e o rei de Judá e o rei de Edom; e andaram rodeando com uma marcha de sete dias, e o exército e o gado que os seguia não tinham água.

[[v12-3-10]]

^<<v12-3-10,10>>^ Então disse o rei de Israel: Ah! que o Senhor chamou a estes três reis, para os entregar nas mãos dos moabitas.

[[v12-3-11]]

^<<v12-3-11,11>>^ E disse Josafá: Não há  aqui algum  profeta do Senhor, para que consultemos ao Senhor por ele? Então respondeu um dos servos do rei de Israel, e disse: Aqui está  Eliseu, filho de Safate, que deitava água sobre as mãos de Elias.

[[v12-3-12]]

^<<v12-3-12,12>>^ E disse Josafá: Está com ele a palavra do Senhor. Então o rei de Israel, e Josafá e o rei de Edom desceram a ele.

[[v12-3-13]]

^<<v12-3-13,13>>^ Mas Eliseu disse ao rei de Israel: Que tenho eu contigo? Vai aos profetas de teu pai e aos profetas de tua mãe. Porém o rei de Israel lhe disse: Não, porque o Senhor chamou a estes três reis para os entregar nas mãos dos moabitas.

[[v12-3-14]]

^<<v12-3-14,14>>^ E disse Eliseu: Vive o Senhor dos Exércitos, em cuja presença estou, que  se eu não respeitasse a presença de Josafá, rei de Judá, não olharia para ti nem te veria.

[[v12-3-15]]

^<<v12-3-15,15>>^ Ora, pois, trazei-me um tangedor. E sucedeu que, tangendo o tangedor, veio sobre ele a mão do Senhor.

[[v12-3-16]]

^<<v12-3-16,16>>^ E disse: Assim diz o Senhor: Fazei neste vale muitas covas;

[[v12-3-17]]

^<<v12-3-17,17>>^ Porque assim diz o Senhor: Não vereis vento, e não vereis chuva: todavia este vale se encherá de tanta  água, que bebereis vós, e o vosso gado e os vossos animais.

[[v12-3-18]]

^<<v12-3-18,18>>^ E ainda  isto é  pouco aos olhos do Senhor: também entregará ele os moabitas nas vossas mãos.

[[v12-3-19]]

^<<v12-3-19,19>>^ E ferireis a todas as cidades fortes, e a todas as cidades escolhidas, e todas as boas árvores cortareis, e tapareis todas as fontes de água, e danificareis com pedras todos os bons campos.

[[v12-3-20]]

^<<v12-3-20,20>>^ E sucedeu que pela manhã, oferecendo-se a oferta de manjares, eis que vinham as  águas pelo caminho de Edom: e a terra se encheu de água.

[[v12-3-21]]

^<<v12-3-21,21>>^ Ouvindo pois todos os moabitas que os reis tinham subido para pelejarem contra eles, convocaram a todos os que cingiam cinto e daí para cima, e puseram-se às fronteiras.

[[v12-3-22]]

^<<v12-3-22,22>>^ E, levantando-se de madrugada, e saindo o sol sobre as águas, viram os moabitas defronte deles  as águas vermelhas como sangue.

[[v12-3-23]]

^<<v12-3-23,23>>^ E disseram: Isto é  sangue; certamente que os reis se destruíram à espada e se mataram um ao outro! Agora pois à presa, moabitas!

[[v12-3-24]]

^<<v12-3-24,24>>^ Porém, chegando eles ao arraial de Israel, os israelitas se levantaram, e feriram os moabitas, os quais fugiram diante deles: e ainda os  feriram nas suas terras , ferindo ali  também os moabitas.

[[v12-3-25]]

^<<v12-3-25,25>>^ E arrasaram as cidades, e cada um lançou a sua pedra em todos os bons campos, e os entulharam, e taparam todas as fontes de águas, e cortaram todas as boas árvores, até que só  em Quir-Haresete deixaram ficar as pedras, mas os fundeiros a cercaram e a feriram.

[[v12-3-26]]

^<<v12-3-26,26>>^ Mas, vendo o rei dos moabitas que a peleja prevalecia contra ele, tomou consigo setecentos homens que arrancavam espada, para romperem contra o rei de Edom, porém não puderam.

[[v12-3-27]]

^<<v12-3-27,27>>^ Então tomou a seu filho primogênito, que havia de reinar em seu lugar, e o ofereceu em holocausto sobre o muro; pelo que houve grande indignação em Israel: por isso retiraram-se dele, e voltaram para a sua  terra.

'''

xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[&#60; Capítulo Anterior] | <<v12-3-0,Topo>> | xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[Próximo Capítulo &#62;]