include::./index.adoc[]

[[v12-23-0]]
=== 2 Reis, 23
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v12-23-1]]

^<<v12-23-1,1>>^ ENTÃO o rei ordenou, e todos os anciãos de Judá e de Jerusalém se ajuntaram a ele.

[[v12-23-2]]

^<<v12-23-2,2>>^ E o rei subiu à casa do Senhor, e com ele todos os homens de Judá, e todos os moradores de Jerusalém, e os sacerdotes, e os profetas, e todo o povo, desde o mais pequeno até ao maior: e leu aos ouvidos deles todas as palavras do livro do concerto, que se achou na casa do Senhor.

[[v12-23-3]]

^<<v12-23-3,3>>^ E o rei se pôs em pé junto à coluna, e fez o concerto perante o Senhor, para andarem com o Senhor, e guardarem os seus mandamentos, e os seus testemunhos, e os seus estatutos, com todo o coração, e com toda a alma, confirmando as palavras deste concerto, que estavam escritas naquele livro; e todo o povo esteve por este concerto.

[[v12-23-4]]

^<<v12-23-4,4>>^ E o rei mandou ao sumo sacerdote Hilquias, e aos sacerdotes da segunda ordem, e aos guardas do umbral da porta , que se tirassem do templo do Senhor todos os vasos que se tinham feito para Baal, e para o bosque, e para todo o exército dos céus: e os queimou fora de Jerusalém, nos campos de Cedrom, e levou as cinzas deles a Betel.

[[v12-23-5]]

^<<v12-23-5,5>>^ Também destituiu os sacerdotes que os reis de Judá estabeleceram para incensarem sobre os altos nas cidades de Judá, e ao redor de Jerusalém, como também os que incensavam a Baal, ao sol, e à lua, e aos mais  planetas, e a todo o exército dos céus.

[[v12-23-6]]

^<<v12-23-6,6>>^ Também tirou da casa do Senhor o ídolo do  bosque para fora de Jerusalém até o ribeiro de Cedrom, e o queimou junto ao ribeiro de Cedrom, e o desfez em pó, e lançou o seu pó sobre as sepulturas dos filhos do povo.

[[v12-23-7]]

^<<v12-23-7,7>>^ Também derribou as casas dos rapazes escandalosos que estavam  na casa do Senhor, em que as mulheres teciam casinhas para o ídolo do  bosque.

[[v12-23-8]]

^<<v12-23-8,8>>^ E a todos os sacerdotes trouxe das cidades de Judá, e profanou os altos em que os sacerdotes incensavam, desde Geba até Berseba: e derribou os altos das portas, que estavam  à entrada da porta de Josué, o chefe da cidade, e que estavam  à mão  esquerda daquele que entrava  pela porta da cidade.

[[v12-23-9]]

^<<v12-23-9,9>>^ Mas os sacerdotes dos altos não sacrificavam sobre o altar do Senhor em Jerusalém; porém comiam pães  asmos no meio de seus irmãos.

[[v12-23-10]]

^<<v12-23-10,10>>^ Também profanou a Tofete, que está  no vale dos filhos de Hinom: para que ninguém fizesse passar a seu filho, ou sua filha, pelo fogo a Moloque.

[[v12-23-11]]

^<<v12-23-11,11>>^ Também tirou os cavalos que os reis de Judá tinham destinado ao sol, à entrada da casa do Senhor, perto da câmara de Natã-Meleque, o eunuco, que estava  no recinto: e os carros do sol queimou a fogo.

[[v12-23-12]]

^<<v12-23-12,12>>^ Também o rei derribou os altares que estavam  sobre o terraço do cenáculo de Acaz, os quais fizeram os reis de Judá; como também o rei derribou os altares que fizera Manassés nos dois átrios da casa do Senhor; e esmigalhados os tirou dali, e lançou o pó deles no ribeiro de Cedrom.

[[v12-23-13]]

^<<v12-23-13,13>>^ O rei profanou também  os altos que estavam  defronte de Jerusalém, à mão direita do monte de Masite, os quais edificara Salomão, rei de Israel, a Astarote, a abominação dos sidônios, e a Camós, a abominação dos moabitas, e a Milcom, a abominação dos filhos de Amom.

[[v12-23-14]]

^<<v12-23-14,14>>^ Semelhantemente quebrou as estátuas, e cortou os bosques, e encheu o seu lugar com ossos de homens.

[[v12-23-15]]

^<<v12-23-15,15>>^ E também o altar que estava em Betel, e  o alto que fez Jeroboão, filho de Nebate, que tinha feito pecar a Israel, juntamente com aquele altar também o alto derribou; queimando o alto, em pó o desfez e queimou o ídolo do  bosque.

[[v12-23-16]]

^<<v12-23-16,16>>^ E, virando-se Josias, viu as sepulturas que estavam  ali no monte, e enviou, e tomou os ossos das sepulturas, e os queimou sobre aquele altar, e assim  o profanou, conforme a palavra do Senhor, que apregoara o homem de Deus, quando apregoou estas palavras.

[[v12-23-17]]

^<<v12-23-17,17>>^ Então disse: Que é  este monumento que vejo? E os homens da cidade lhe disseram: É a sepultura do homem de Deus que veio de Judá, e apregoou estas cousas que fizeste contra este altar de Betel.

[[v12-23-18]]

^<<v12-23-18,18>>^ E disse: Deixai-o estar; ninguém mexa nos seus ossos. Assim deixaram estar os seus ossos com os ossos do profeta que viera de Samaria.

[[v12-23-19]]

^<<v12-23-19,19>>^ De mais disto também Josias tirou todas as casas dos altos que havia  nas cidades de Samaria, e que os reis de Israel tinham feito para provocarem o Senhor  à ira; e lhes fez conforme todos os atos que tinha praticado em Betel.

[[v12-23-20]]

^<<v12-23-20,20>>^ E sacrificou todos os sacerdotes dos altos, que havia  ali, sobre os altares, e queimou ossos de homens sobre eles: depois voltou a Jerusalém.

[[v12-23-21]]

^<<v12-23-21,21>>^ E o rei deu ordem a todo o povo, dizendo: Celebrai a páscoa ao Senhor vosso Deus, como está escrito no livro do concerto.

[[v12-23-22]]

^<<v12-23-22,22>>^ Porque nunca se celebrou tal páscoa como esta desde os dias dos juízes que julgaram a Israel, nem em todos os dias dos reis de Israel, nem tão pouco  dos reis de Judá.

[[v12-23-23]]

^<<v12-23-23,23>>^ Porém no ano décimo oitavo do rei Josias esta páscoa se celebrou ao Senhor em Jerusalém.

[[v12-23-24]]

^<<v12-23-24,24>>^ E também os adivinhos, e os feiticeiros, e os terafins, e os ídolos, e todas as abominações que se viam na terra de Judá e em Jerusalém, os extirpou Josias, para confirmar as palavras da lei, que estavam escritas no livro que o sacerdote Hilquias achara na casa do Senhor.

[[v12-23-25]]

^<<v12-23-25,25>>^ E antes dele não houve rei semelhante, que se convertesse ao Senhor com todo o seu coração, e com toda a sua alma, e com todas as suas forças, conforme toda a lei de Moisés: e depois dele nunca se levantou outro tal.

[[v12-23-26]]

^<<v12-23-26,26>>^ Todavia o Senhor se não demoveu do ardor da sua grande ira, ira com que ardia contra Judá, por todas as provocações com que Manassés o tinha provocado.

[[v12-23-27]]

^<<v12-23-27,27>>^ E disse o Senhor: Também a Judá hei de tirar de diante da minha face, como tirei a Israel, e rejeitarei esta cidade de Jerusalém que elegi, como também a casa de que disse: Estará ali o meu nome.

[[v12-23-28]]

^<<v12-23-28,28>>^ Ora o mais dos sucessos de Josias, e tudo quanto fez, porventura  não está  escrito no livro das crônicas dos reis de Judá?

[[v12-23-29]]

^<<v12-23-29,29>>^ Nos seus dias subiu Faraó Neco, rei do Egito, contra o rei da Assíria, ao rio Eufrates: e o rei Josias lhe foi ao encontro: e, vendo-o ele o matou em Megido.

[[v12-23-30]]

^<<v12-23-30,30>>^ E seus servos o levaram morto de Megido, e o trouxeram a Jerusalém, e o sepultaram na sua sepultura: e o povo da terra tomou a Joacaz, filho de Josias, e o ungiram, e o fizeram rei em lugar de seu pai.

[[v12-23-31]]

^<<v12-23-31,31>>^ Tinha Joacaz vinte e três anos de idade quando começou a reinar, e três meses reinou em Jerusalém: e era  o nome de sua mãe Hamutal, filha de Jeremias, de Libna.

[[v12-23-32]]

^<<v12-23-32,32>>^ E fez o que parecia  mal aos olhos do Senhor, conforme tudo o que fizeram seus pais.

[[v12-23-33]]

^<<v12-23-33,33>>^ Porém Faraó Neco o mandou prender em Ribla, em terra de Hamate, para que não reinasse em Jerusalém: e à terra impôs a pena de cem talentos de prata e um talento de ouro.

[[v12-23-34]]

^<<v12-23-34,34>>^ Também Faraó Neco estabeleceu rei a Eliaquim, filho de Josias, em lugar de seu pai Josias, e lhe mudou o nome em  Joaquim: porém a Joacaz tomou consigo, e veio ao Egito e morreu ali.

[[v12-23-35]]

^<<v12-23-35,35>>^ E Joaquim deu aquela prata e aquele ouro a Faraó; porém fintou a terra, para dar esse dinheiro conforme o mandado de Faraó: a cada um segundo a sua avaliação demandou a prata e o ouro do povo da terra, para o  dar a Faraó Neco.

[[v12-23-36]]

^<<v12-23-36,36>>^ Tinha Joaquim vinte e cinco anos de idade quando começou a reinar, e reinou onze anos em Jerusalém; e era  o nome de sua mãe Zebuda, filha de Pedaías, de Ruma.

[[v12-23-37]]

^<<v12-23-37,37>>^ E fez o que parecia  mal aos olhos do Senhor, conforme tudo quanto fizeram seus pais.

'''

xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[&#60; Capítulo Anterior] | <<v12-23-0,Topo>> | xref:012-2-reis/012-2-reis-024.adoc#v12-24-0[Próximo Capítulo &#62;]