include::./index.adoc[]

[[v1-45-0]]
=== Gênesis, 45
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-45-1]]

^<<v1-45-1,1>>^ ENTÃO José não se podia conter diante de todos os que estavam com ele; e clamou: Fazei sair daqui a todo o varão; e ninguém ficou com ele, quando José se deu a conhecer a seus irmãos.

[[v1-45-2]]

^<<v1-45-2,2>>^ E levantou a sua voz com choro, de maneira que os egípcios o ouviam, e a casa de Faraó o ouviu.

[[v1-45-3]]

^<<v1-45-3,3>>^ E disse José a seus irmãos: Eu sou  José; vive ainda meu pai? E seus irmãos não lhe puderam responder, porque estavam pasmados diante da sua face.

[[v1-45-4]]

^<<v1-45-4,4>>^ E disse José a seus irmãos: Peço-vos, chegai-vos a mim. E chegaram-se. Então disse ele: Eu sou  José, vosso irmão, a quem vendestes para o Egito.

[[v1-45-5]]

^<<v1-45-5,5>>^ Agora, pois, não vos entristeçais, nem vos pese aos vossos olhos por me haverdes vendido para cá; porque para conservação da vida, Deus me enviou diante da vossa face.

[[v1-45-6]]

^<<v1-45-6,6>>^ Porque já houve dois anos de fome no meio da terra, e ainda restam  cinco anos em que não haverá lavoura nem sega.

[[v1-45-7]]

^<<v1-45-7,7>>^ Pelo que Deus me enviou diante da vossa face, para conservar vossa sucessão na terra, e para guardar-vos em vida por um grande livramento.

[[v1-45-8]]

^<<v1-45-8,8>>^ Assim não fostes  vós que  me enviastes para cá, senão Deus, que me tem posto por pai de Faraó, e por senhor de toda a sua casa, e como regente em toda a terra do Egito.

[[v1-45-9]]

^<<v1-45-9,9>>^ Apressai-vos, e subi a meu pai, e dizei-lhe. Assim tem dito o teu filho José: Deus me tem posto por senhor em toda a terra do Egito; desce a mim, e não te demores;

[[v1-45-10]]

^<<v1-45-10,10>>^ E habitarás na terra de Gósen, e estarás perto de mim, tu e os teus filhos, e os filhos dos teus filhos, e as tuas ovelhas, e as tuas vacas, e tudo o que tens.

[[v1-45-11]]

^<<v1-45-11,11>>^ E ali te sustentarei, porque ainda haverá  cinco anos de fome, para que não pereças de pobreza, tu e tua casa, e tudo o que tens.

[[v1-45-12]]

^<<v1-45-12,12>>^ E eis que vossos olhos veem, e os olhos de meu irmão Benjamim, que é  minha boca que vos fala.

[[v1-45-13]]

^<<v1-45-13,13>>^ E fazei saber a meu pai toda a minha glória no Egito, e tudo o que tendes visto, e apressai-vos a fazer descer meu pai para cá.

[[v1-45-14]]

^<<v1-45-14,14>>^ E lançou-se ao pescoço de Benjamim seu irmão, e chorou; e Benjamim chorou também  ao seu pescoço.

[[v1-45-15]]

^<<v1-45-15,15>>^ E beijou a todos os seus irmãos, e chorou sobre eles; e depois seus irmãos falaram com ele.

[[v1-45-16]]

^<<v1-45-16,16>>^ E a nova ouviu-se na casa de Faraó, dizendo: Os irmãos de José são vindos; e pareceu bem aos olhos de Faraó, e aos olhos de seus servos.

[[v1-45-17]]

^<<v1-45-17,17>>^ E disse Faraó a José: Dize a teus irmãos: Fazei isto, carregai os vossos animais e parti, tornai à terra de Canaã,

[[v1-45-18]]

^<<v1-45-18,18>>^ E tornai a vosso pai, e a vossas famílias, e vinde a mim; e eu vos darei o melhor da terra do Egito, e comereis a fartura da terra.

[[v1-45-19]]

^<<v1-45-19,19>>^ A ti pois é ordenado; fazei isto, tomai vós da terra do Egito carros para vossos meninos, para vossas mulheres, e para vosso pai, e vinde.

[[v1-45-20]]

^<<v1-45-20,20>>^ E não vos pese cousa alguma  das vossas alfaias; porque o melhor de toda a terra do Egito será  vosso.

[[v1-45-21]]

^<<v1-45-21,21>>^ E os filhos de Israel fizeram assim. E José deu-lhes carros, conforme o mandado de Faraó; também lhes deu comida para o caminho.

[[v1-45-22]]

^<<v1-45-22,22>>^ A todos lhes deu, a cada um, mudas de vestidos; mas a Benjamim deu trezentas peças de prata, e cinco mudas de vestidos.

[[v1-45-23]]

^<<v1-45-23,23>>^ E a seu pai enviou semelhantemente dez jumentos carregados do melhor do Egito, e dez jumentos carregados de trigo, e pão, e comida para seu pai, para o caminho.

[[v1-45-24]]

^<<v1-45-24,24>>^ E despediu os seus irmãos, e partiram; e disse-lhes: Não contendais pelo caminho.

[[v1-45-25]]

^<<v1-45-25,25>>^ E subiram do Egito, e vieram à terra de Canãa, a Jacó seu pai.

[[v1-45-26]]

^<<v1-45-26,26>>^ Então lhe anunciaram, dizendo: José ainda vive, e ele também é regente em toda a terra do Egito. E o seu coração desmaiou, porque não os acreditava.

[[v1-45-27]]

^<<v1-45-27,27>>^ Porém, havendo-lhe eles contado todas as palavras de José, que ele lhes falara e vendo ele os carros que José enviara para levá-lo, reviveu o espírito de Jacó seu pai.

[[v1-45-28]]

^<<v1-45-28,28>>^ E disse Israel: Basta; ainda vive meu filho José; eu irei, e o verei antes que morra.

'''

xref:001-genesis/001-genesis-044.adoc#v1-44-0[&#60; Capítulo Anterior] | <<v1-45-0,Topo>> | xref:001-genesis/001-genesis-046.adoc#v1-46-0[Próximo Capítulo &#62;]