include::./index.adoc[]

[[v1-7-0]]
=== Gênesis, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-7-1]]

^<<v1-7-1,1>>^ DEPOIS disse o Senhor a Noé: Entra tu e toda a tua casa na arca, porque te hei visto justo diante de mim nesta geração.

[[v1-7-2]]

^<<v1-7-2,2>>^ De todo o animal limpo tomarás para ti sete e  sete, macho e sua fêmea; mas dos animais que não são limpos, dois, o macho e sua fêmea.

[[v1-7-3]]

^<<v1-7-3,3>>^ Também das aves dos céus sete e  sete, macho e fêmea, para se conservar em vida a semente sobre a face de toda a terra.

[[v1-7-4]]

^<<v1-7-4,4>>^ Porque, passados ainda sete dias, farei chover sobre a terra quarenta dias e quarenta noites; e desfarei de sobre a face da terra toda a substância que fiz.

[[v1-7-5]]

^<<v1-7-5,5>>^ E fez Noé conforme a tudo o que o Senhor lhe ordenara.

[[v1-7-6]]

^<<v1-7-6,6>>^ E era  Noé da idade de seiscentos anos, quando o dilúvio das águas veio sobre a terra.

[[v1-7-7]]

^<<v1-7-7,7>>^ E entrou Noé, e seus filhos, e sua mulher, e as mulheres de seus filhos com ele na arca, por causa das águas do dilúvio.

[[v1-7-8]]

^<<v1-7-8,8>>^ Dos animais limpos, e dos animais que não são  limpos, e das aves e de todo o réptil sobre a terra,

[[v1-7-9]]

^<<v1-7-9,9>>^ Entraram de dois em dois para Noé na arca, macho e fêmea, como Deus ordenara a Noé.

[[v1-7-10]]

^<<v1-7-10,10>>^ E aconteceu que, passados sete dias, vieram sobre a terra as águas do dilúvio.

[[v1-7-11]]

^<<v1-7-11,11>>^ No ano seiscentos da vida de Noé, no mês segundo, aos dezessete dias do mês, naquele mesmo dia se romperam todas as fontes do grande abismo, e as janelas dos céus se abriram,

[[v1-7-12]]

^<<v1-7-12,12>>^ E houve chuva sobre a terra quarenta dias e quarenta noites.

[[v1-7-13]]

^<<v1-7-13,13>>^ E no mesmo dia entrou Noé, e Sem, e Cão, e Jafé, os filhos de Noé, como também a mulher de Noé, e as três mulheres de seus filhos com ele na arca,

[[v1-7-14]]

^<<v1-7-14,14>>^ Eles, e todo o animal conforme a sua espécie, e todo o gado conforme a sua espécie, e todo o réptil que se roja sobre a terra conforme a sua espécie, e toda a ave conforme a sua espécie, todo o pássaro de toda a qualidade.

[[v1-7-15]]

^<<v1-7-15,15>>^ E de toda a carne, em que havia espírito de vida, entraram de dois em dois para Noé na arca.

[[v1-7-16]]

^<<v1-7-16,16>>^ E os que entraram, macho e fêmea de toda a carne entraram, como Deus lhe tinha ordenado: e o Senhor o fechou por fora.

[[v1-7-17]]

^<<v1-7-17,17>>^ E esteve o dilúvio quarenta dias sobre a terra, e cresceram as águas, e levantaram a arca, e ela se elevou sobre a terra.

[[v1-7-18]]

^<<v1-7-18,18>>^ E prevaleceram as águas, e cresceram grandemente sobre a terra; e a arca andava sobre as águas.

[[v1-7-19]]

^<<v1-7-19,19>>^ E as águas prevaleceram excessivamente sobre a terra; e todos os altos montes, que havia  debaixo de todo o céu, foram cobertos.

[[v1-7-20]]

^<<v1-7-20,20>>^ Quinze côvados acima prevaleceram as águas; e os montes foram cobertos.

[[v1-7-21]]

^<<v1-7-21,21>>^ E expirou toda a carne que se movia sobre a terra, tanto de ave como de gado e de feras, e de todo o réptil que se roja sobre a terra, e todo o homem.

[[v1-7-22]]

^<<v1-7-22,22>>^ Tudo o que tinha  fôlego de espírito de vida em seus narizes, tudo o que havia  no seco, morreu.

[[v1-7-23]]

^<<v1-7-23,23>>^ Assim foi desfeita toda a substância que havia  sobre a face da terra, desde o homem até ao animal, até ao réptil, e até à ave dos céus; e foram extintos da terra: e ficou somente Noé, e os que com ele estavam  na arca.

[[v1-7-24]]

^<<v1-7-24,24>>^ E prevaleceram as águas sobre a terra cento e cinquenta dias.

'''

xref:001-genesis/001-genesis-006.adoc#v1-6-0[&#60; Capítulo Anterior] | <<v1-7-0,Topo>> | xref:001-genesis/001-genesis-008.adoc#v1-8-0[Próximo Capítulo &#62;]