include::./index.adoc[]

[[v1-13-0]]
=== Gênesis, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-13-1]]

^<<v1-13-1,1>>^ SUBIU, pois, Abrão do Egito para a banda do Sul, ele e sua mulher, e tudo o que tinha, e com ele Ló.

[[v1-13-2]]

^<<v1-13-2,2>>^ E ia  Abrão muito rico em gado, em prata, e em ouro.

[[v1-13-3]]

^<<v1-13-3,3>>^ E fez as suas jornadas do Sul até Betel, até ao lugar onde ao princípio estivera a sua tenda, entre Betel e Ai:

[[v1-13-4]]

^<<v1-13-4,4>>^ Até ao lugar do altar que dantes ali tinha feito; e Abrão invocou ali o nome do Senhor.

[[v1-13-5]]

^<<v1-13-5,5>>^ E também Ló, que ia com Abrão, tinha rebanhos, e vacas, e tendas.

[[v1-13-6]]

^<<v1-13-6,6>>^ E não tinha capacidade a terra para poderem  habitar juntos; porque a sua fazenda era muita; de maneira que não podiam habitar juntos.

[[v1-13-7]]

^<<v1-13-7,7>>^ E houve contenda entre os pastores do gado de Abrão, e os pastores do gado de Ló; e os cananeus e os ferezeus habitavam então na terra.

[[v1-13-8]]

^<<v1-13-8,8>>^ E disse Abrão a Ló: Ora não haja contenda entre mim e ti, e entre os meus pastores e os teus pastores, porque irmãos somos.

[[v1-13-9]]

^<<v1-13-9,9>>^ Não está toda a terra diante de ti? Eia, pois, aparta-te de mim; se escolheres  a esquerda, irei para a direita; e se a direita escolheres , eu irei para a esquerda.

[[v1-13-10]]

^<<v1-13-10,10>>^ E levantou Ló os seus olhos, e viu toda a campina do Jordão, que era  toda bem regada, antes do Senhor ter destruído Sodoma e Gomorra, e era  como o jardim do Senhor, como a terra do Egito, quando se entra em Zoar.

[[v1-13-11]]

^<<v1-13-11,11>>^ Então Ló escolheu para si toda a campina do Jordão, e partiu Ló para o Oriente, e apartaram-se um do outro.

[[v1-13-12]]

^<<v1-13-12,12>>^ Habitou Abrão na terra de Canaã, e Ló habitou nas cidades da campina, e armou as suas tendas até Sodoma.

[[v1-13-13]]

^<<v1-13-13,13>>^ Ora eram  maus os varões de Sodoma, e grandes pecadores contra o Senhor.

[[v1-13-14]]

^<<v1-13-14,14>>^ E disse o Senhor a Abrão, depois que Ló se apartou dele: Levanta agora os teus olhos, e olha desde o lugar onde estás, para a banda do Norte, e do Sul, e do Oriente, e do Ocidente;

[[v1-13-15]]

^<<v1-13-15,15>>^ Porque toda esta terra que vês, te hei de dar a ti, e à tua semente, para sempre.

[[v1-13-16]]

^<<v1-13-16,16>>^ E farei a tua semente como o pó da terra; de maneira que se alguém puder contar o pó da terra, também a tua semente será contada.

[[v1-13-17]]

^<<v1-13-17,17>>^ Levanta-te, percorre essa terra, no seu comprimento e na sua largura; porque a ti a darei.

[[v1-13-18]]

^<<v1-13-18,18>>^ E Abrão armou as suas tendas, e veio e habitou nos carvalhais de Manre, que estão junto a Hebrom; e edificou ali um altar ao Senhor.

'''

xref:001-genesis/001-genesis-012.adoc#v1-12-0[&#60; Capítulo Anterior] | <<v1-13-0,Topo>> | xref:001-genesis/001-genesis-014.adoc#v1-14-0[Próximo Capítulo &#62;]