include::./index.adoc[]

[[v1-8-0]]
=== Gênesis, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-8-1]]

^<<v1-8-1,1>>^ E LEMBROU-SE Deus de Noé e de todo o animal, e de toda a rês que com ele estava  na arca; e Deus fez passar um vento sobre a terra, e aquietaram-se as águas.

[[v1-8-2]]

^<<v1-8-2,2>>^ Cerraram-se também as fontes do abismo, e as janelas dos céus, e a chuva dos céus deteve-se.

[[v1-8-3]]

^<<v1-8-3,3>>^ E as águas tornaram de sobre a terra continuamente, e ao cabo de cento e cinquenta dias as águas minguaram.

[[v1-8-4]]

^<<v1-8-4,4>>^ E a arca repousou, no sétimo mês, no dia dezessete do mês, sobre os montes de Arará.

[[v1-8-5]]

^<<v1-8-5,5>>^ E foram as águas indo e minguando até ao décimo mês; no décimo mês, no primeiro dia do mês, apareceram os cumes dos montes.

[[v1-8-6]]

^<<v1-8-6,6>>^ E aconteceu que, ao cabo de quarenta dias, abriu Noé a janela da arca que tinha feito.

[[v1-8-7]]

^<<v1-8-7,7>>^ E soltou um corvo, que saiu, indo e voltando, até que as águas se secaram de sobre a terra.

[[v1-8-8]]

^<<v1-8-8,8>>^ Depois soltou uma pomba, a ver se as águas tinham minguado de sobre a face da terra.

[[v1-8-9]]

^<<v1-8-9,9>>^ A pomba porém não achou repouso para a planta de seu pé, e voltou a ele para a arca; porque as águas estavam  sobre a face de toda a terra; e ele estendeu a sua mão, e tomou-a, e meteu-a consigo na arca.

[[v1-8-10]]

^<<v1-8-10,10>>^ E esperou ainda outros sete dias, e tornou a enviar a pomba fora da arca.

[[v1-8-11]]

^<<v1-8-11,11>>^ E a pomba voltou a ele sobre a tarde; e eis, arrancada, uma folha de oliveira no seu bico; e conheceu Noé que as águas tinham minguado sobre a terra.

[[v1-8-12]]

^<<v1-8-12,12>>^ Então esperou ainda outros sete dias; e enviou fora a pomba, mas não tornou mais a ele.

[[v1-8-13]]

^<<v1-8-13,13>>^ E aconteceu que  no ano seiscentos e um, no mês  primeiro, no primeiro dia  do mês, as águas se secaram de sobre a terra. Então Noé tirou a cobertura da arca, e olhou, e eis que a face da terra estava enxuta.

[[v1-8-14]]

^<<v1-8-14,14>>^ E no segundo mês, aos vinte e sete dias do mês, a terra estava seca.

[[v1-8-15]]

^<<v1-8-15,15>>^ Então falou Deus a Noé, dizendo:

[[v1-8-16]]

^<<v1-8-16,16>>^ Sai da arca, tu, e tua mulher, e teus filhos, e as mulheres de teus filhos contigo.

[[v1-8-17]]

^<<v1-8-17,17>>^ Todo o animal que está  contigo, de toda a carne, de ave, e de gado, e de todo o réptil que se roja sobre a terra traze fora contigo; e povoem abundantemente a terra, e frutifiquem, e se multipliquem sobre a terra.

[[v1-8-18]]

^<<v1-8-18,18>>^ Então saiu Noé, e seus filhos, e sua mulher, e as mulheres de seus filhos com ele,

[[v1-8-19]]

^<<v1-8-19,19>>^ Todo o animal, todo o réptil, e toda a ave, e tudo o que se move sobre a terra, conforme as suas famílias, saiu para fora da arca.

[[v1-8-20]]

^<<v1-8-20,20>>^ E edificou Noé um altar ao Senhor; e tomou de todo o animal limpo, e de toda a ave limpa, e ofereceu holocaustos sobre o altar.

[[v1-8-21]]

^<<v1-8-21,21>>^ E o Senhor cheirou o suave cheiro e disse o Senhor em seu coração: Não tornarei mais a amaldiçoar a terra por causa do homem; porque a imaginação do coração do homem é  má desde a sua meninice, nem tornarei mais a ferir todo o vivente, como fiz.

[[v1-8-22]]

^<<v1-8-22,22>>^ Enquanto a terra durar, sementeira e sega, e frio e calor, e verão e inverno, e dia e noite, não cessarão.

'''

xref:001-genesis/001-genesis-007.adoc#v1-7-0[&#60; Capítulo Anterior] | <<v1-8-0,Topo>> | xref:001-genesis/001-genesis-009.adoc#v1-9-0[Próximo Capítulo &#62;]