include::./index.adoc[]

[[v1-19-0]]
=== Gênesis, 19
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-19-1]]

^<<v1-19-1,1>>^ E VIERAM os dois anjos a Sodoma à tarde e estava Ló assentado à porta de Sodoma; e vendo- os  Ló, levantou-se ao seu encontro, e inclinou-se com o rosto à terra;

[[v1-19-2]]

^<<v1-19-2,2>>^ E disse: Eis agora, meus senhores, entrai, peço-vos, em casa de vosso servo, e passai nela  a noite, e lavai os vossos pés; e de madrugada vos levantareis e ireis vosso caminho. E eles disseram: Não, antes na rua passaremos a noite.

[[v1-19-3]]

^<<v1-19-3,3>>^ E porfiou com eles muito, e vieram com ele, e entraram em sua casa; e fez-lhes banquete, e cozeu bolos sem levedura, e comeram.

[[v1-19-4]]

^<<v1-19-4,4>>^ E antes que se deitassem, cercaram a casa os varões daquela cidade, os varões de Sodoma, desde o moço até ao velho; todo o povo de todos os bairros.

[[v1-19-5]]

^<<v1-19-5,5>>^ E chamaram a Ló, e disseram-lhe: Onde estão  os varões que a ti vieram nesta noite? Traze-os fora a nós, para que os conheçamos.

[[v1-19-6]]

^<<v1-19-6,6>>^ Então saiu Ló a eles à porta, e fechou a porta atrás de si,

[[v1-19-7]]

^<<v1-19-7,7>>^ E disse: Meus irmãos, rogo-vos que não façais mal;

[[v1-19-8]]

^<<v1-19-8,8>>^ Eis aqui, duas filhas tenho, que ainda  não conheceram varão; fora vo-las trarei, e fareis delas como bom for  nos vossos olhos; somente nada façais a estes varões, porque por isso vieram à sombra do meu telhado.

[[v1-19-9]]

^<<v1-19-9,9>>^ Eles porém disseram: Sai daí. Disseram mais: Como estrangeiro este indivíduo veio aqui  habitar, e quereria ser juiz em tudo? Agora te faremos mais mal a ti do que a eles. E arremessaram-se sobre o varão, sobre  Ló, e aproximaram-se para arrombar a porta.

[[v1-19-10]]

^<<v1-19-10,10>>^ Aqueles varões porém estenderam a sua mão, e fizeram entrar a Ló consigo na casa, e fecharam a porta;

[[v1-19-11]]

^<<v1-19-11,11>>^ E feriram de cegueira os varões que estavam  à porta da casa, desde o menor até ao maior, de maneira que se cansaram para achar a porta.

[[v1-19-12]]

^<<v1-19-12,12>>^ Então disseram aqueles varões a Ló: Tens alguém mais aqui? Teu genro, e teus filhos, e tuas filhas, e todos quantos tens nesta cidade, tira-os fora deste lugar;

[[v1-19-13]]

^<<v1-19-13,13>>^ Porque nós vamos destruir este lugar, porque o seu clamor tem engrossado diante da face do Senhor, e o Senhor nos enviou a destruí-lo.

[[v1-19-14]]

^<<v1-19-14,14>>^ Então saiu Ló, e falou a seus genros, aos que haviam de tomar as suas filhas e disse: Levantai-vos saí deste lugar: porque o Senhor há de destruir a cidade. Foi tido porém por zombador aos olhos de seus genros.

[[v1-19-15]]

^<<v1-19-15,15>>^ E ao amanhecer os anjos apertaram com Ló, dizendo: Levanta-te, toma tua mulher, e tuas duas filhas que aqui estão, para que não pereças na injustiça desta cidade.

[[v1-19-16]]

^<<v1-19-16,16>>^ Ele porém demorava-se, e aqueles varões lhe pegaram pela mão, e pela mão de sua mulher, e pela mão de suas duas filhas, sendo-lhe o Senhor misericordioso, e tiraram-no, e puseram-no fora da cidade.

[[v1-19-17]]

^<<v1-19-17,17>>^ E aconteceu que, tirando-os fora, disse: Escapa-te por tua vida; não olhes para trás de ti, e não pares em toda esta campina; escapa lá para o monte, para que não pereças.

[[v1-19-18]]

^<<v1-19-18,18>>^ E Ló disse-lhe: Assim não, Senhor!

[[v1-19-19]]

^<<v1-19-19,19>>^ Eis que agora o teu servo tem achado graça aos teus olhos, e engrandeceste a tua misericórdia que a mim me fizeste, para guardar a minha alma em vida: mas não posso escapar no monte, pois que tenho medo que me apanhe este mal, e eu morra.

[[v1-19-20]]

^<<v1-19-20,20>>^ Eis agora aquela cidade está  perto, para fugir para lá, e é  pequena: ora para  ali me escaparei (não é  pequena?), para que minha alma viva.

[[v1-19-21]]

^<<v1-19-21,21>>^ E disse-lhe: Eis aqui, tenho-te aceitado também neste negócio, para não derribar esta cidade, de que falaste.

[[v1-19-22]]

^<<v1-19-22,22>>^ Apressa-te, escapa-te para ali; porque nada poderei fazer, enquanto não tiveres ali chegado. Por isso se chamou o nome da cidade Zoar.

[[v1-19-23]]

^<<v1-19-23,23>>^ Saiu o sol sobre a terra, quando Ló entrou em Zoar.

[[v1-19-24]]

^<<v1-19-24,24>>^ Então o Senhor fez chover enxofre e fogo, do Senhor desde os céus, sobre Sodoma e Gomorra.

[[v1-19-25]]

^<<v1-19-25,25>>^ E derribou aquelas cidades, e toda aquela campina, e todos os moradores daquelas cidades, e o que nascia da terra.

[[v1-19-26]]

^<<v1-19-26,26>>^ E a mulher de Ló olhou para trás e ficou convertida numa estátua de sal.

[[v1-19-27]]

^<<v1-19-27,27>>^ E Abraão levantou-se aquela mesma manhã de madrugada, e foi para aquele lugar onde estivera diante da face do Senhor;

[[v1-19-28]]

^<<v1-19-28,28>>^ E olhou para Sodoma e Gomorra, e para toda a terra da campina; e viu, e eis que o fumo da terra subia, como o fumo duma fornalha.

[[v1-19-29]]

^<<v1-19-29,29>>^ E aconteceu que, destruindo Deus as cidades da campina, Deus se lembrou de Abraão, e tirou a Ló do meio da destruição, derribando aquelas cidades em que Ló habitara.

[[v1-19-30]]

^<<v1-19-30,30>>^ E subiu Ló de Zoar, e habitou no monte, e as suas duas filhas com ele; porque temia habitar em Zoar; e habitou numa caverna, ele e as suas duas filhas.

[[v1-19-31]]

^<<v1-19-31,31>>^ Então a primogênita disse à menor: Nosso pai é  já velho, e não há  varão na terra que entre a nós, segundo o costume de toda a terra;

[[v1-19-32]]

^<<v1-19-32,32>>^ Vem, demos a beber vinho a nosso pai, e deitemo-nos com ele, para que em vida conservemos semente de nosso pai.

[[v1-19-33]]

^<<v1-19-33,33>>^ E deram a beber vinho a seu pai naquela noite; e veio a primogênita, e deitou-se com seu pai, e não sentiu ele quando ela se deitou, nem quando se levantou.

[[v1-19-34]]

^<<v1-19-34,34>>^ E sucedeu, no outro dia, que a primogênita disse à menor: Vês aqui, eu já ontem à noite me deitei com meu pai; demos-lhe a beber vinho também esta noite, e então entra tu, deita-te com ele, para que em vida conservemos semente de nosso pai.

[[v1-19-35]]

^<<v1-19-35,35>>^ E deram de beber vinho a seu pai, também naquela noite; e levantou-se a menor, e deitou-se com ele; e não sentiu ele quando ela se deitou, nem quando se levantou.

[[v1-19-36]]

^<<v1-19-36,36>>^ E conceberam as duas filhas de Ló de seu pai.

[[v1-19-37]]

^<<v1-19-37,37>>^ E teve a primogênita um filho, e chamou o seu nome Moabe; este é  o pai dos moabitas, até ao dia de hoje.

[[v1-19-38]]

^<<v1-19-38,38>>^ E a menor também teve um filho, e chamou o seu nome Benami, este é  o pai dos filhos de Amom, até o dia de hoje.

'''

xref:001-genesis/001-genesis-018.adoc#v1-18-0[&#60; Capítulo Anterior] | <<v1-19-0,Topo>> | xref:001-genesis/001-genesis-020.adoc#v1-20-0[Próximo Capítulo &#62;]