include::./index.adoc[]

[[v1-47-0]]
=== Gênesis, 47
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-47-1]]

^<<v1-47-1,1>>^ ENTÃO veio José, e anunciou a Faraó, e disse: Meu pai, e os meus irmãos, e as suas ovelhas, e as suas vacas, com tudo o que têm, chegaram da terra de Canaã, e eis que estão  na terra de Gósen.

[[v1-47-2]]

^<<v1-47-2,2>>^ E tomou uma parte de seus irmãos, a saber , cinco varões, e os pôs diante de Faraó.

[[v1-47-3]]

^<<v1-47-3,3>>^ Então disse Faraó a seus irmãos: Qual é o vosso negócio? E eles disseram a Faraó: Teus servos são  pastores de ovelhas, tanto nós como nossos pais.

[[v1-47-4]]

^<<v1-47-4,4>>^ Disseram mais a Faraó: Viemos para peregrinar nesta terra; porque não há pasto para as ovelhas de teus servos porquanto a fome é  grave na terra de Canaã; agora pois rogamos-te que teus servos habitem na terra de Gósen.

[[v1-47-5]]

^<<v1-47-5,5>>^ Então falou Faraó a José, dizendo: Teu pai e teus irmãos vieram a ti;

[[v1-47-6]]

^<<v1-47-6,6>>^ A terra do Egito está diante da tua face, no melhor da terra faze habitar teu pai e teus irmãos; habitem na terra de Gósen; e se sabes que entre eles há homens valentes, os porás por maiorais do gado, sobre o que eu tenho.

[[v1-47-7]]

^<<v1-47-7,7>>^ E trouxe José a Jacó, seu pai, e o pôs diante de Faraó; e Jacó abençoou a Faraó.

[[v1-47-8]]

^<<v1-47-8,8>>^ E Faraó disse a Jacó: Quantos são  os dias dos anos de tua vida?

[[v1-47-9]]

^<<v1-47-9,9>>^ E Jacó disse a Faraó: Os dias dos anos das minhas peregrinações são  cento e trinta anos; poucos e maus foram os dias dos anos da minha vida, e não chegaram aos dias dos anos da vida de meus pais nos dias das suas peregrinações.

[[v1-47-10]]

^<<v1-47-10,10>>^ E Jacó abençoou a Faraó, e saiu de diante da face de Faraó.

[[v1-47-11]]

^<<v1-47-11,11>>^ E José fez habitar a seu pai e seus irmãos, e deu-lhes possessão na terra do Egito, no melhor da terra, na terra de Ramessés, como Faraó ordenara.

[[v1-47-12]]

^<<v1-47-12,12>>^ E José sustentou de pão a seu pai, e a seus irmãos, e a toda a casa de seu pai, segundo as suas famílias.

[[v1-47-13]]

^<<v1-47-13,13>>^ E não havia  pão em toda a terra, porque a fome era  mui grave; de maneira que a terra do Egito e a terra de Canaã desfaleciam por causa da fome.

[[v1-47-14]]

^<<v1-47-14,14>>^ Então José recolheu todo o dinheiro que se achou na terra do Egito, e na terra de Canaã, pelo trigo que compravam; e José trouxe o dinheiro à casa de Faraó.

[[v1-47-15]]

^<<v1-47-15,15>>^ Acabando-se pois o dinheiro na terra do Egito, e na terra de Canaã, vieram todos os egípcios a José, dizendo: Dá-nos pão; por que morreremos em tua presença? porquanto o dinheiro nos falta.

[[v1-47-16]]

^<<v1-47-16,16>>^ E José disse: Dai o vosso gado, e eu vo-lo darei por vosso gado, se falta o dinheiro.

[[v1-47-17]]

^<<v1-47-17,17>>^ Então trouxeram o seu gado a José; e José deu-lhes pão em troca  de cavalos, e das ovelhas, e das vacas e dos jumentos; e os sustentou de pão aquele ano por todo o seu gado.

[[v1-47-18]]

^<<v1-47-18,18>>^ E acabado aquele ano, vieram a ele no segundo ano, e disseram-lhe: Não ocultaremos ao meu senhor que o dinheiro é acabado, e meu senhor possui os animais, e nenhuma outra cousa nos  ficou diante da face de meu senhor, senão o nosso corpo e a nossa terra;

[[v1-47-19]]

^<<v1-47-19,19>>^ Por que morreremos diante dos teus olhos, tanto nós como a nossa terra? Compra-nos a nós e à nossa terra por pão e nós e a nossa terra seremos servos de Faraó, e dá semente para que vivamos, e não morramos, e a terra não se desole.

[[v1-47-20]]

^<<v1-47-20,20>>^ Assim José comprou toda a terra do Egito para Faraó, porque os egípcios venderam cada um o seu campo, porquanto a fome era extrema sobre eles; e a terra ficou sendo  de Faraó.

[[v1-47-21]]

^<<v1-47-21,21>>^ E quanto ao povo, fê-lo passar às cidades, desde uma  extremidade da terra do Egito até à outra  extremidade.

[[v1-47-22]]

^<<v1-47-22,22>>^ Somente a terra dos sacerdotes não a comprou, porquanto os sacerdotes tinham porção de Faraó, e eles comiam a sua porção que Faraó lhes tinha dado; por isso não venderam a sua terra.

[[v1-47-23]]

^<<v1-47-23,23>>^ Então disse José ao povo: Eis que hoje vos tenho comprado a vós e a vossa terra para Faraó; eis aí tendes semente para vós, para que semeeis a terra.

[[v1-47-24]]

^<<v1-47-24,24>>^ Há de ser, porém, que das colheitas dareis o quinto a Faraó, e as quatro partes serão vossas, para semente do campo, e para o vosso mantimento, e dos que estão  nas vossas casas, e para que comam vossos meninos.

[[v1-47-25]]

^<<v1-47-25,25>>^ E disseram: A vida nos tens dado; achemos graça nos olhos de meu senhor, e seremos servos de Faraó.

[[v1-47-26]]

^<<v1-47-26,26>>^ José pois pôs isto por estatuto até ao dia de hoje, sobre a terra do Egito, que Faraó tirasse o quinto: só a terra dos sacerdotes não ficou sendo  de Faraó.

[[v1-47-27]]

^<<v1-47-27,27>>^ Assim habitou Israel na terra do Egito, na terra de Gósen, e nela tomaram possessão e frutificaram, e multiplicaram-se muito.

[[v1-47-28]]

^<<v1-47-28,28>>^ E Jacó viveu na terra do Egito dezessete anos; de sorte que os dias de Jacó, os anos da sua vida, foram cento e quarenta e sete anos.

[[v1-47-29]]

^<<v1-47-29,29>>^ Chegando-se pois o tempo da morte de Israel, chamou a José seu filho, e disse-lhe: Se agora tenho achado graça em teus olhos, rogo-te que ponhas a tua mão debaixo da minha coxa, e usa comigo de beneficência e verdade; rogo-te que me não enterres no Egito,

[[v1-47-30]]

^<<v1-47-30,30>>^ Mas que eu  jaza com os meus pais; por isso me levarás do Egito, e me sepultarás na sepultura deles. E ele disse: Farei conforme a tua palavra.

[[v1-47-31]]

^<<v1-47-31,31>>^ E disse ele: Jura-me. E ele jurou-lhe; e Israel inclinou-se sobre a cabeceira da cama.

'''

xref:001-genesis/001-genesis-046.adoc#v1-46-0[&#60; Capítulo Anterior] | <<v1-47-0,Topo>> | xref:001-genesis/001-genesis-048.adoc#v1-48-0[Próximo Capítulo &#62;]