include::./index.adoc[]

[[v1-1-0]]
=== Gênesis, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-1-1]]

^<<v1-1-1,1>>^ NO princípio criou Deus os céus e a terra.

[[v1-1-2]]

^<<v1-1-2,2>>^ E a terra era sem forma e vazia; e havia  trevas sobre a face do abismo; e o Espírito de Deus se movia sobre a face das águas.

[[v1-1-3]]

^<<v1-1-3,3>>^ E disse Deus: Haja luz. E houve luz.

[[v1-1-4]]

^<<v1-1-4,4>>^ E viu Deus que era boa a luz; e fez Deus separação entre a luz e as trevas.

[[v1-1-5]]

^<<v1-1-5,5>>^ E Deus chamou à luz Dia; e às trevas chamou Noite. E foi a tarde e a manhã o dia primeiro.

[[v1-1-6]]

^<<v1-1-6,6>>^ E disse Deus: Haja uma expansão no meio das águas, e haja separação entre águas e águas.

[[v1-1-7]]

^<<v1-1-7,7>>^ E fez Deus a expansão, e fez separação entre as águas que estavam  debaixo da expansão e as águas que estavam  sobre a expansão. E assim foi.

[[v1-1-8]]

^<<v1-1-8,8>>^ E chamou Deus à expansão Céus, e foi a tarde e a manhã o dia segundo.

[[v1-1-9]]

^<<v1-1-9,9>>^ E disse Deus: Ajuntem-se as águas debaixo dos céus num lugar; e apareça a porção  seca. E assim foi.

[[v1-1-10]]

^<<v1-1-10,10>>^ E chamou Deus à porção  seca Terra; e ao ajuntamento das águas chamou Mares. E viu Deus que era bom.

[[v1-1-11]]

^<<v1-1-11,11>>^ E disse Deus: Produza a terra erva verde, erva que dê semente, árvore frutífera que dê fruto segundo a sua espécie, cuja semente esteja nela sobre a terra. E assim foi.

[[v1-1-12]]

^<<v1-1-12,12>>^ E a terra produziu erva, erva dando semente conforme a sua espécie, e a árvore frutífera, cuja semente está  nela conforme a sua espécie. E viu Deus que era bom.

[[v1-1-13]]

^<<v1-1-13,13>>^ E foi a tarde e a manhã o dia terceiro.

[[v1-1-14]]

^<<v1-1-14,14>>^ E disse Deus: Haja luminares na expansão dos céus, para haver separação entre o dia e a noite; e sejam eles para sinais e para tempos determinados e para dias e anos.

[[v1-1-15]]

^<<v1-1-15,15>>^ E sejam para luminares na expansão dos céus, para alumiar a terra. E assim foi.

[[v1-1-16]]

^<<v1-1-16,16>>^ E fez Deus os dois grandes luminares: o luminar maior para governar o dia, e o luminar menor para governar a noite; e fez as estrelas.

[[v1-1-17]]

^<<v1-1-17,17>>^ E Deus os pôs na expansão dos céus para alumiar a terra,

[[v1-1-18]]

^<<v1-1-18,18>>^ E para governar o dia e a noite, e para fazer separação entre a luz e as trevas. E viu Deus que era bom.

[[v1-1-19]]

^<<v1-1-19,19>>^ E foi a tarde e a manhã o dia quarto.

[[v1-1-20]]

^<<v1-1-20,20>>^ E disse Deus: Produzam as águas abundantemente répteis de alma vivente; e voem as aves sobre a face da expansão dos céus.

[[v1-1-21]]

^<<v1-1-21,21>>^ E Deus criou as grandes baleias, e todo o réptil de alma vivente que as águas abundantemente produziram conforme as suas espécies; e toda a ave de asas conforme a sua espécie. E viu Deus que era bom.

[[v1-1-22]]

^<<v1-1-22,22>>^ E Deus os abençoou, dizendo: Frutificai e multiplicai-vos, e enchei as águas nos mares; e as aves se multipliquem na terra.

[[v1-1-23]]

^<<v1-1-23,23>>^ E foi a tarde e a manhã o dia quinto.

[[v1-1-24]]

^<<v1-1-24,24>>^ E disse Deus: Produza a terra alma vivente conforme a sua espécie; gado e répteis, e bestas-feras da terra conforme a sua espécie. E assim foi.

[[v1-1-25]]

^<<v1-1-25,25>>^ E fez Deus as bestas-feras da terra conforme a sua espécie, e o gado conforme a sua espécie, e todo o réptil da terra conforme a sua espécie. E viu Deus que era bom.

[[v1-1-26]]

^<<v1-1-26,26>>^ E disse Deus: Façamos o homem à nossa imagem, conforme à nossa semelhança; e domine sobre os peixes do mar, e sobre as aves dos céus, e sobre o gado, e sobre toda a terra, e sobre todo o réptil que se move sobre a terra.

[[v1-1-27]]

^<<v1-1-27,27>>^ E criou Deus o homem à sua imagem; à imagem de Deus o criou; macho e fêmea os criou.

[[v1-1-28]]

^<<v1-1-28,28>>^ E Deus os abençoou, e Deus lhes disse: Frutificai e multiplicai-vos, e enchei a terra, e sujeitai-a; e dominai sobre os peixes do mar, e sobre as aves dos céus, e sobre todo o animal que se move sobre a terra.

[[v1-1-29]]

^<<v1-1-29,29>>^ E disse Deus: Eis que vos tenho dado toda a erva que dá semente, que está  sobre a face de toda a terra; e toda a árvore, em que há fruto de árvore que dá semente, ser-vos-á para mantimento.

[[v1-1-30]]

^<<v1-1-30,30>>^ E a todo o animal da terra, e a toda a ave dos céus, e a todo o réptil da terra, em que há alma vivente, toda a erva verde será  para mantimento. E assim foi.

[[v1-1-31]]

^<<v1-1-31,31>>^ E viu Deus tudo quanto tinha feito, e eis que era muito bom: e foi a tarde e a manhã o dia sexto.

'''

**&#60; Capítulo Anterior** | <<v1-1-0,Topo>> | xref:001-genesis/001-genesis-002.adoc#v1-2-0[Próximo Capítulo &#62;]