include::./index.adoc[]

[[v1-23-0]]
=== Gênesis, 23
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-23-1]]

^<<v1-23-1,1>>^ E FOI a vida de Sara cento e vinte e sete anos; estes foram  os anos da vida de Sara.

[[v1-23-2]]

^<<v1-23-2,2>>^ E morreu Sara em Quiriate-Arba, que é Hebrom, na terra de Canaã; e veio Abraão lamentar a Sara e chorar por ela.

[[v1-23-3]]

^<<v1-23-3,3>>^ Depois se levantou Abraão de diante do seu morto, e falou aos filhos de Hete, dizendo:

[[v1-23-4]]

^<<v1-23-4,4>>^ Estrangeiro e peregrino sou entre vós; dai-me possessão de sepultura convosco, para que eu sepulte o meu morto de diante da minha face.

[[v1-23-5]]

^<<v1-23-5,5>>^ E responderam os filhos de Hete a Abraão, dizendo-lhe:

[[v1-23-6]]

^<<v1-23-6,6>>^ Ouve-nos, meu senhor; príncipe de Deus és  no meio de nós; enterra o teu morto na mais  escolhida de nossas sepulturas; nenhum de nós te vedará a sua sepultura, para enterrares o teu morto.

[[v1-23-7]]

^<<v1-23-7,7>>^ Então se levantou Abraão, e inclinou-se diante do povo da terra, diante dos filhos de Hete.

[[v1-23-8]]

^<<v1-23-8,8>>^ E falou com eles, dizendo: Se é de vossa vontade que eu sepulte o meu morto de diante de minha face, ouvi-me e falai por mim a Efrom, filho de Zoar,

[[v1-23-9]]

^<<v1-23-9,9>>^ Que ele me dê a cova de Macpela, que tem  no fim do seu campo; que ma dê pelo devido preço em posse de sepulcro no meio de vós.

[[v1-23-10]]

^<<v1-23-10,10>>^ Ora Efrom estava no meio dos filhos de Hete; e respondeu Efrom heteu a Abraão, aos ouvidos dos filhos de Hete, de todos os que entravam pela porta da sua cidade, dizendo:

[[v1-23-11]]

^<<v1-23-11,11>>^ Não, meu senhor; ouve-me, o campo te dou, também te dou a cova que nele está , diante dos olhos dos filhos do meu povo ta dou; sepulta o teu morto.

[[v1-23-12]]

^<<v1-23-12,12>>^ Então Abraão se inclinou diante da face do povo da terra,

[[v1-23-13]]

^<<v1-23-13,13>>^ E falou a Efrom, aos ouvidos do povo da terra, dizendo: Mas se tu estás por isto , ouve-me, peço-te; o preço do campo o  darei; toma-o de mim, e sepultarei ali o meu morto.

[[v1-23-14]]

^<<v1-23-14,14>>^ E respondeu Efrom a Abraão, dizendo-lhe:

[[v1-23-15]]

^<<v1-23-15,15>>^ Meu senhor, ouve-me, a terra é  de quatrocentos siclos de prata; que é isto entre mim e ti? sepulta o teu morto.

[[v1-23-16]]

^<<v1-23-16,16>>^ E Abraão deu ouvidos a Efrom, e Abraão pesou a Efrom a prata de que tinha falado aos ouvidos dos filhos de Hete, quatrocentos siclos de prata, correntes entre mercadores.

[[v1-23-17]]

^<<v1-23-17,17>>^ Assim o campo de Efrom, que estava  em Macpela, em frente de Manre, o campo e a cova que nele estava , e todo o arvoredo que no campo havia , que estava  em todo o seu contorno ao redor,

[[v1-23-18]]

^<<v1-23-18,18>>^ Se confirmou a Abraão em possessão diante dos olhos dos filhos de Hete, de todos os que entravam pela porta da sua cidade.

[[v1-23-19]]

^<<v1-23-19,19>>^ E depois sepultou Abraão a Sara sua mulher na cova do campo de Macpela, em frente de Manre, que é Hebrom, na terra de Canaã.

[[v1-23-20]]

^<<v1-23-20,20>>^ Assim o campo e a cova que nele estava  se confirmou a Abraão em possessão de sepultura pelos filhos de Hete.

'''

xref:001-genesis/001-genesis-022.adoc#v1-22-0[&#60; Capítulo Anterior] | <<v1-23-0,Topo>> | xref:001-genesis/001-genesis-024.adoc#v1-24-0[Próximo Capítulo &#62;]