include::./index.adoc[]

[[v1-27-0]]
=== Gênesis, 27
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-27-1]]

^<<v1-27-1,1>>^ E ACONTECEU que, como Isaque envelheceu, e os seus olhos se escureceram, de maneira que não podia ver, chamou a Esaú, seu filho mais velho, e disse-lhe: Meu filho. E ele lhe disse: Eis-me aqui.

[[v1-27-2]]

^<<v1-27-2,2>>^ E ele disse: Eis que já agora estou velho, e não sei o dia da minha morte;

[[v1-27-3]]

^<<v1-27-3,3>>^ Agora pois, toma as tuas armas, a tua aljava e o teu arco, e sai ao campo, e apanha para mim alguma  caça.

[[v1-27-4]]

^<<v1-27-4,4>>^ E faze-me um guisado saboroso, como eu gosto, e traze-m o , para que eu coma; para que minha alma te abençoe, antes que morra.

[[v1-27-5]]

^<<v1-27-5,5>>^ E Rebeca escutou quando Isaque falava ao seu filho Esaú: e foi-se Esaú ao campo, para apanhar caça que havia de trazer.

[[v1-27-6]]

^<<v1-27-6,6>>^ Então falou Rebeca a Jacó seu filho, dizendo: Eis que tenho ouvido o teu pai que falava com Esaú teu irmão, dizendo:

[[v1-27-7]]

^<<v1-27-7,7>>^ Traze-me caça, e faze-me um guisado saboroso, para que eu coma, e te abençoe diante da face do Senhor, antes da minha morte.

[[v1-27-8]]

^<<v1-27-8,8>>^ Agora pois, filho meu, ouve a minha voz naquilo que eu te mando:

[[v1-27-9]]

^<<v1-27-9,9>>^ Vai agora ao rebanho, e traze-me de lá dois bons cabritos das cabras, e eu farei deles um guisado saboroso para teu pai, como ele gosta,

[[v1-27-10]]

^<<v1-27-10,10>>^ E levá-lo-ás a teu pai, para que o coma; para que te abençoe antes da sua morte.

[[v1-27-11]]

^<<v1-27-11,11>>^ Então disse Jacó a Rebeca, sua mãe: Eis que Esaú meu irmão é  varão cabeludo, e eu varão liso.

[[v1-27-12]]

^<<v1-27-12,12>>^ Porventura me apalpará o meu pai, e serei em seus olhos enganador: assim trarei eu sobre mim maldição, e não bênção.

[[v1-27-13]]

^<<v1-27-13,13>>^ E disse-lhe sua mãe: Meu filho, sobre mim seja  a tua maldição; somente obedece à minha voz, e vai traze-m os.

[[v1-27-14]]

^<<v1-27-14,14>>^ E foi, e tomou-os, e trouxe-os a sua mãe; e sua mãe fez um guisado saboroso, como seu pai gostava.

[[v1-27-15]]

^<<v1-27-15,15>>^ Depois tomou Rebeca os vestidos de gala de Esaú, seu filho mais velho, que tinha  consigo em casa, e vestiu a Jacó, seu filho menor;

[[v1-27-16]]

^<<v1-27-16,16>>^ E com as peles dos cabritos das cabras cobriu as suas mãos e a lisura do seu pescoço;

[[v1-27-17]]

^<<v1-27-17,17>>^ E deu o guisado saboroso, e o pão que tinha preparado, na mão de Jacó seu filho.

[[v1-27-18]]

^<<v1-27-18,18>>^ E veio ele a seu pai, e disse: Meu pai! E ele disse: Eis-me aqui ; quem és  tu, meu filho?

[[v1-27-19]]

^<<v1-27-19,19>>^ E Jacó disse a seu pai: Eu sou  Esaú, teu primogênito; tenho feito como me disseste: levanta-te agora, assenta-te, e come da minha caça, para que a tua alma me abençoe.

[[v1-27-20]]

^<<v1-27-20,20>>^ Então disse Isaque a seu filho: Como é isto, que  tão cedo a  achaste, filho meu? E ele disse: Porque o Senhor teu Deus a  mandou ao meu encontro.

[[v1-27-21]]

^<<v1-27-21,21>>^ E disse Isaque a Jacó: Chega-te agora, para que te apalpe, meu filho, se és  meu filho Esaú mesmo, ou não.

[[v1-27-22]]

^<<v1-27-22,22>>^ Então se chegou Jacó a Isaque seu pai, que o apalpou, e disse: A voz é  a voz de Jacó, porém as mãos são  as mãos de Esaú.

[[v1-27-23]]

^<<v1-27-23,23>>^ E não o conheceu, porquanto as suas mãos estavam cabeludas, como as mãos de Esaú seu irmão; e abençoou-o.

[[v1-27-24]]

^<<v1-27-24,24>>^ E disse: És  tu meu filho Esaú mesmo? E ele disse: Eu sou.

[[v1-27-25]]

^<<v1-27-25,25>>^ Então disse: Faze chegar isso perto de mim, para que coma da caça de meu filho; para que a minha alma te abençoe. E chegou-lho, e comeu; trouxe-lhe também vinho, e bebeu.

[[v1-27-26]]

^<<v1-27-26,26>>^ E disse-lhe Isaque seu pai: Ora chega-te, e beija-me, filho meu.

[[v1-27-27]]

^<<v1-27-27,27>>^ E chegou-se, e beijou-o; então cheirou o cheiro dos seus vestidos, e abençoou-o, e disse: Eis que o cheiro do meu filho é  como o cheiro do campo, que o Senhor abençoou:

[[v1-27-28]]

^<<v1-27-28,28>>^ Assim pois te dê Deus do orvalho dos céus, e das gorduras da terra, e abundância de trigo e de mosto:

[[v1-27-29]]

^<<v1-27-29,29>>^ Sirvam-te povos, e nações se encurvem a ti: sê senhor de teus irmãos, e os filhos da tua mãe se encurvem a ti: malditos sejam  os que te amaldiçoarem, e benditos sejam  os que te abençoarem.

[[v1-27-30]]

^<<v1-27-30,30>>^ E aconteceu que, acabando Isaque de abençoar a Jacó, apenas Jacó acabava de sair da face de Isaque seu pai, veio Esaú, seu irmão, da sua caça;

[[v1-27-31]]

^<<v1-27-31,31>>^ E fez também ele um guisado saboroso, e trouxe-o a seu pai e disse a seu pai: Levanta-te, meu pai, e come da caça de teu filho, para que me abençoe a tua alma.

[[v1-27-32]]

^<<v1-27-32,32>>^ E disse-lhe Isaque seu pai: Quem és  tu? E ele disse: Eu sou teu filho, o teu primogênito, Esaú.

[[v1-27-33]]

^<<v1-27-33,33>>^ Então estremeceu Isaque de um estremecimento muito grande; e disse: Quem, pois, é  aquele que apanhou a caça, e ma  trouxe? Eu comi de tudo, antes que tu viesses, e abençoei-o: também será bendito.

[[v1-27-34]]

^<<v1-27-34,34>>^ Esaú, ouvindo as palavras de seu pai, bradou com grande e mui amargo brado, e disse a seu pai: Abençoa-me também a mim, meu pai.

[[v1-27-35]]

^<<v1-27-35,35>>^ E ele disse: Veio o teu irmão com sutileza, e tomou a tua bênção.

[[v1-27-36]]

^<<v1-27-36,36>>^ Então disse ele: Não foi o seu nome justamente  chamado Jacó, por isso que já duas vezes me enganou? A minha primogenitura me  tomou, e eis que agora me  tomou a minha bênção. Mais disse: Não reservaste pois para mim bênção alguma?

[[v1-27-37]]

^<<v1-27-37,37>>^ Então respondeu Isaque, e disse a Esaú: Eis que o tenho posto por senhor sobre ti, e todos os seus irmãos lhe tenho dado por servos: e de trigo e de mosto o tenho fortalecido; — que te farei pois agora a ti , meu filho?

[[v1-27-38]]

^<<v1-27-38,38>>^ E disse Esaú a seu pai: Tens uma só bênção, meu pai? Abençoa-me também a mim, meu pai. E levantou Esaú a sua voz, e chorou.

[[v1-27-39]]

^<<v1-27-39,39>>^ Então respondeu Isaque seu pai, e disse-lhe: Eis que a tua habitação será nas gorduras da terra e no orvalho dos céus do alto.

[[v1-27-40]]

^<<v1-27-40,40>>^ E pela tua espada viverás, e ao teu irmão servirás. Acontecerá, porém, que quando te libertares, então sacudirás o seu jugo do teu pescoço.

[[v1-27-41]]

^<<v1-27-41,41>>^ E aborreceu Esaú a Jacó por causa daquela bênção, com que seu pai o tinha abençoado; e Esaú disse no seu coração: Chegar-se-ão os dias de luto de meu pai: e matarei a Jacó meu irmão.

[[v1-27-42]]

^<<v1-27-42,42>>^ E foram denunciadas a Rebeca estas palavras de Esaú, seu filho mais velho; e ela enviou, e chamou a Jacó, seu filho menor, e disse-lhe: Eis que Esaú teu irmão se consola a teu respeito, propondo-se  matar-te.

[[v1-27-43]]

^<<v1-27-43,43>>^ Agora pois, meu filho, ouve a minha voz, e levanta-te; acolhe-te a Labão meu irmão, em Harã,

[[v1-27-44]]

^<<v1-27-44,44>>^ E mora com ele alguns dias, até que passe o furor de teu irmão;

[[v1-27-45]]

^<<v1-27-45,45>>^ Até que se desvie de ti a ira de teu irmão, e se esqueça do que lhe fizeste: então enviarei, e te farei vir de lá; por que seria eu desfilhada também de vós ambos num mesmo dia?

[[v1-27-46]]

^<<v1-27-46,46>>^ E disse Rebeca a Isaque: Enfadada estou da minha vida, por causa das filhas de Hete; se Jacó tomar mulher das filhas de Hete, como estas são  das filhas desta terra, para que me será  a vida?

'''

xref:001-genesis/001-genesis-026.adoc#v1-26-0[&#60; Capítulo Anterior] | <<v1-27-0,Topo>> | xref:001-genesis/001-genesis-028.adoc#v1-28-0[Próximo Capítulo &#62;]