include::./index.adoc[]

[[v1-28-0]]
=== Gênesis, 28
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-28-1]]

^<<v1-28-1,1>>^ E ISAQUE chamou a Jacó, e abençoou-o, e ordenou-lhe, e disse-lhe: Não tomes mulher de entre as filhas de Canaã:

[[v1-28-2]]

^<<v1-28-2,2>>^ Levanta-te, vai a Padã-Arã, à casa de Betuel, pai de tua mãe, e toma de lá uma mulher das filhas de Labão, irmão de tua mãe;

[[v1-28-3]]

^<<v1-28-3,3>>^ E Deus Todo-poderoso te abençoe, e te faça frutificar, e te multiplique, para que sejas uma multidão de povos;

[[v1-28-4]]

^<<v1-28-4,4>>^ E te dê a bênção de Abraão, a ti e à tua semente contigo, para que em herança possuas a terra de tuas peregrinações que Deus deu a Abraão.

[[v1-28-5]]

^<<v1-28-5,5>>^ Assim enviou Isaque a Jacó, o qual se foi a Padã-Arã, a Labão, filho de Betuel arameu, irmão de Rebeca, mãe de Jacó e de Esaú.

[[v1-28-6]]

^<<v1-28-6,6>>^ Vendo pois Esaú que Isaque abençoara a Jacó, e o enviara a Padã-Arã, para tomar mulher para si dali, e  que, abençoando-o, lhe ordenara, dizendo: Não tomes mulher das filhas de Canaã;

[[v1-28-7]]

^<<v1-28-7,7>>^ E que Jacó obedecera a seu pai e a sua mãe, e se fora a Padã-Arã;

[[v1-28-8]]

^<<v1-28-8,8>>^ Vendo também Esaú que as filhas de Canaã eram más aos olhos de Isaque seu pai,

[[v1-28-9]]

^<<v1-28-9,9>>^ Foi-se Esaú a Ismael, e tomou para si por mulher, além das suas mulheres, a Maalate filha de Ismael, filho de Abraão, irmã de Nebaiote.

[[v1-28-10]]

^<<v1-28-10,10>>^ Partiu pois Jacó de Berseba, e foi-se a Harã;

[[v1-28-11]]

^<<v1-28-11,11>>^ E chegou a um lugar onde passou a noite, porque já o sol era posto; e tomou uma das pedras daquele lugar, e a  pôs por sua cabeceira, e deitou-se naquele lugar,

[[v1-28-12]]

^<<v1-28-12,12>>^ E sonhou: e eis uma escada era  posta na terra, cujo topo tocava nos céus: e eis que os anjos de Deus subiam e desciam por ela;

[[v1-28-13]]

^<<v1-28-13,13>>^ E eis que o Senhor estava em cima dela, e disse: Eu sou  o Senhor, o Deus de Abraão teu pai, e o Deus de Isaque: esta terra, em que estás  deitado, ta darei a ti e à tua semente:

[[v1-28-14]]

^<<v1-28-14,14>>^ E a tua semente será como o pó da terra, e estender-se-á ao ocidente, e ao oriente, e ao norte, e ao sul, e em ti e na tua semente serão benditas todas as famílias da terra:

[[v1-28-15]]

^<<v1-28-15,15>>^ E eis que estou  contigo, e te guardarei por onde quer que fores, e te farei tornar a esta terra: porque te não deixarei, até que te haja feito o que te tenho dito.

[[v1-28-16]]

^<<v1-28-16,16>>^ Acordado pois Jacó do seu sono, disse: Na verdade o Senhor está neste lugar; e eu não o sabia.

[[v1-28-17]]

^<<v1-28-17,17>>^ E temeu, e disse: Quão terrível é  este lugar! Este não é outro lugar  senão a casa de Deus; e esta é  a porta dos céus.

[[v1-28-18]]

^<<v1-28-18,18>>^ Então levantou-se Jacó pela manhã de madrugada, e tomou a pedra que tinha posto por sua cabeceira, e a pôs por coluna, e derramou azeite em cima dela.

[[v1-28-19]]

^<<v1-28-19,19>>^ E chamou o nome daquele lugar Betel: o nome porém daquela cidade dantes era  Luz.

[[v1-28-20]]

^<<v1-28-20,20>>^ E Jacó votou um voto dizendo: Se Deus for comigo, e me guardar nesta viagem que faço, e me der pão para comer, e vestidos para vestir;

[[v1-28-21]]

^<<v1-28-21,21>>^ E eu em paz tornar à casa de meu pai, o Senhor será o meu Deus;

[[v1-28-22]]

^<<v1-28-22,22>>^ E esta pedra que tenho posto por coluna será casa de Deus; e de tudo quanto me deres, certamente te darei o dízimo.

'''

xref:001-genesis/001-genesis-027.adoc#v1-27-0[&#60; Capítulo Anterior] | <<v1-28-0,Topo>> | xref:001-genesis/001-genesis-029.adoc#v1-29-0[Próximo Capítulo &#62;]