include::./index.adoc[]

[[v1-17-0]]
=== Gênesis, 17
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-17-1]]

^<<v1-17-1,1>>^ SENDO pois Abrão da idade de noventa e nove anos, apareceu o Senhor  a Abrão, e disse-lhe: Eu sou  o Deus Todo-poderoso, anda em minha presença e sê perfeito;

[[v1-17-2]]

^<<v1-17-2,2>>^ E porei o meu concerto entre mim e ti, e te multiplicarei grandissimamente.

[[v1-17-3]]

^<<v1-17-3,3>>^ Então caiu Abrão sobre o seu rosto, e falou Deus com ele, dizendo:

[[v1-17-4]]

^<<v1-17-4,4>>^ Quanto a mim, eis o meu concerto contigo é, e serás o pai de uma multidão de nações;

[[v1-17-5]]

^<<v1-17-5,5>>^ E não se chamará mais o teu nome Abrão, mas Abraão será o teu nome; porque por pai da multidão de nações te tenho posto;

[[v1-17-6]]

^<<v1-17-6,6>>^ E te farei frutificar grandissimamente, e de ti farei nações, e reis sairão de ti;

[[v1-17-7]]

^<<v1-17-7,7>>^ E estabelecerei o meu concerto entre mim e ti e a tua semente depois de ti em suas gerações, por concerto perpétuo, para te ser a ti por Deus, e à tua semente depois de ti.

[[v1-17-8]]

^<<v1-17-8,8>>^ E te darei a ti, e à tua semente depois de ti, a terra de tuas peregrinações, toda a terra de Canaã em perpétua possessão, e ser-lhes-ei o seu Deus.

[[v1-17-9]]

^<<v1-17-9,9>>^ Disse mais Deus a Abraão: Tu, porém, guardarás o meu concerto, tu, e a tua semente depois de ti, nas suas gerações.

[[v1-17-10]]

^<<v1-17-10,10>>^ Este é  o meu concerto, que guardareis entre mim e vós, e a tua semente depois de ti: Que  todo o macho será circuncidado.

[[v1-17-11]]

^<<v1-17-11,11>>^ E circuncidareis a carne do vosso prepúcio; e isto  será por sinal do concerto entre mim e vós.

[[v1-17-12]]

^<<v1-17-12,12>>^ O filho de oito dias, pois, será circuncidado, todo o macho nas vossas gerações; o nascido na casa, e o comprado por dinheiro a qualquer estrangeiro, que não for  da tua semente.

[[v1-17-13]]

^<<v1-17-13,13>>^ Com efeito será circuncidado o nascido em tua casa, e o comprado por teu dinheiro; e estará o meu concerto na vossa carne por concerto perpétuo.

[[v1-17-14]]

^<<v1-17-14,14>>^ E o macho com prepúcio, cuja carne do prepúcio não estiver circuncidada, aquela alma será extirpada dos seus povos; quebrantou o meu concerto.

[[v1-17-15]]

^<<v1-17-15,15>>^ Disse Deus mais a Abraão: a Sarai tua mulher não chamarás mais  pelo nome de Sarai, mas Sara será  o seu nome.

[[v1-17-16]]

^<<v1-17-16,16>>^ Porque eu a hei de abençoar, e te hei de dar a ti dela um filho; e a abençoarei, e será mãe  das nações; reis de povos sairão dela.

[[v1-17-17]]

^<<v1-17-17,17>>^ Então caiu Abraão sobre o seu rosto, e riu-se e disse no seu coração: A um homem de cem anos há de nascer um filho ? E conceberá Sara na idade de noventa anos?

[[v1-17-18]]

^<<v1-17-18,18>>^ E disse Abraão a Deus: Oxalá que viva Ismael diante de teu rosto!

[[v1-17-19]]

^<<v1-17-19,19>>^ E disse Deus: Na verdade, Sara tua mulher te dará um filho, e chamarás o seu nome Isaque, e com ele estabelecerei o meu concerto, por concerto perpétuo para a sua semente depois dele.

[[v1-17-20]]

^<<v1-17-20,20>>^ E enquanto a Ismael, também  te tenho ouvido; eis aqui o tenho abençoado, e fá-lo-ei frutificar, e fá-lo-ei multiplicar grandissimamente; doze príncipes gerará, e dele farei uma grande nação.

[[v1-17-21]]

^<<v1-17-21,21>>^ O meu concerto, porém, estabelecerei com Isaque, o qual Sara te dará neste tempo determinado, no ano seguinte.

[[v1-17-22]]

^<<v1-17-22,22>>^ E acabou de falar com ele, e subiu Deus de Abraão.

[[v1-17-23]]

^<<v1-17-23,23>>^ Então tomou Abraão a seu filho Ismael, e a todos os nascidos na sua casa, e a todos os comprados por seu dinheiro, todo o macho entre os homens da casa de Abraão; e circuncidou a carne do seu prepúcio, naquele mesmo dia, como Deus falara com ele.

[[v1-17-24]]

^<<v1-17-24,24>>^ E era  Abraão da idade de noventa e nove anos, quando lhe foi circuncidada a carne do seu prepúcio.

[[v1-17-25]]

^<<v1-17-25,25>>^ E Ismael, seu filho, era  da idade de treze anos, quando lhe foi circuncidada a carne do seu prepúcio.

[[v1-17-26]]

^<<v1-17-26,26>>^ Neste mesmo dia foi circuncidado Abraão e Ismael seu filho.

[[v1-17-27]]

^<<v1-17-27,27>>^ E todos os homens da sua casa, o nascido em casa, e o comprado por dinheiro do estrangeiro, foram circuncidados com ele.

'''

xref:001-genesis/001-genesis-016.adoc#v1-16-0[&#60; Capítulo Anterior] | <<v1-17-0,Topo>> | xref:001-genesis/001-genesis-018.adoc#v1-18-0[Próximo Capítulo &#62;]