include::./index.adoc[]

[[v1-4-0]]
=== Gênesis, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-4-1]]

^<<v1-4-1,1>>^ E CONHECEU Adão a Eva, sua mulher, e ela concebeu e teve a Caim, e disse: Alcancei do Senhor um varão.

[[v1-4-2]]

^<<v1-4-2,2>>^ E teve mais a seu irmão Abel: e Abel foi pastor de ovelhas, e Caim foi lavrador da terra.

[[v1-4-3]]

^<<v1-4-3,3>>^ E aconteceu ao cabo de dias que Caim trouxe do fruto da terra uma oferta ao Senhor.

[[v1-4-4]]

^<<v1-4-4,4>>^ E Abel também trouxe dos primogênitos das suas ovelhas, e da sua gordura: e atentou o Senhor para Abel e para a sua oferta,

[[v1-4-5]]

^<<v1-4-5,5>>^ Mas para Caim e para a sua oferta não atentou. E irou-se Caim fortemente, e descaiu-lhe o seu semblante.

[[v1-4-6]]

^<<v1-4-6,6>>^ E o Senhor disse a Caim: Por que te iraste? E por que descaiu o teu semblante?

[[v1-4-7]]

^<<v1-4-7,7>>^ Se bem fizeres, não haverá aceitação para ti? E se não fizeres bem, o pecado jaz à porta, e para ti será o seu desejo, e sobre ele dominarás.

[[v1-4-8]]

^<<v1-4-8,8>>^ E falou Caim com o seu irmão Abel: e sucedeu que, estando eles no campo, se levantou Caim contra o seu irmão Abel, e o matou.

[[v1-4-9]]

^<<v1-4-9,9>>^ E disse o Senhor a Caim: Onde está Abel, teu irmão? E ele disse: Não sei: sou eu guardador do meu irmão?

[[v1-4-10]]

^<<v1-4-10,10>>^ E disse Deus: Que fizeste? A voz do sangue do teu irmão clama a mim desde a terra.

[[v1-4-11]]

^<<v1-4-11,11>>^ E agora maldito és  tu desde a terra, que abriu a sua boca para receber da tua mão o sangue do teu irmão.

[[v1-4-12]]

^<<v1-4-12,12>>^ Quando lavrares a terra, não te dará mais a sua força; fugitivo e vagabundo serás na terra.

[[v1-4-13]]

^<<v1-4-13,13>>^ Então disse Caim ao Senhor: É maior a minha maldade que a que possa ser perdoada.

[[v1-4-14]]

^<<v1-4-14,14>>^ Eis que hoje me lanças da face da terra, e da tua face me esconderei; e serei fugitivo e vagabundo na terra, e será que todo aquele que me achar me matará.

[[v1-4-15]]

^<<v1-4-15,15>>^ O Senhor porém disse-lhe: Portanto qualquer que matar a Caim, sete vezes será castigado. E pôs o Senhor um sinal em Caim, para que não o ferisse qualquer que o achasse.

[[v1-4-16]]

^<<v1-4-16,16>>^ E saiu Caim de diante da face do Senhor, e habitou na terra de Node, da banda do oriente do Éden.

[[v1-4-17]]

^<<v1-4-17,17>>^ E conheceu Caim a sua mulher, e ela concebeu, e teve a Enoque: e ele edificou uma cidade, e chamou o nome da cidade pelo nome de seu filho Enoque.

[[v1-4-18]]

^<<v1-4-18,18>>^ E a Enoque nasceu Irade, e Irade gerou a Meujael, e Meujael gerou a Metusael, e Metusael gerou a Lameque.

[[v1-4-19]]

^<<v1-4-19,19>>^ E tomou Lameque para si duas mulheres: o nome duma era Ada, e o nome da outra Zila.

[[v1-4-20]]

^<<v1-4-20,20>>^ E Ada teve a Jabal: este foi o pai dos que habitam em tendas, e têm  gado.

[[v1-4-21]]

^<<v1-4-21,21>>^ E o nome do seu irmão era Jubal: este foi o pai de todos os que tocam harpa e órgão.

[[v1-4-22]]

^<<v1-4-22,22>>^ E Zila também teve a Tubalcaim, mestre de toda a obra de cobre e de ferro: e a irmã de Tubalcaim foi  Naama.

[[v1-4-23]]

^<<v1-4-23,23>>^ E disse Lameque a suas mulheres: Ada e Zila, ouvi a minha voz; vós, mulheres de Lameque, escutai o meu dito: porque eu matei um varão por me ferir, e um mancebo por me pisar.

[[v1-4-24]]

^<<v1-4-24,24>>^ Porque sete vezes Caim será vingado; mas Lameque setenta vezes sete.

[[v1-4-25]]

^<<v1-4-25,25>>^ E tornou Adão a conhecer a sua mulher; e ela teve um filho, e chamou o seu nome Sete; porque, disse ela, Deus me deu outra semente em lugar de Abel; porquanto Caim o matou.

[[v1-4-26]]

^<<v1-4-26,26>>^ E a Sete mesmo também nasceu um filho; e chamou o seu nome Enos: então se começou a invocar o nome do Senhor.

'''

xref:001-genesis/001-genesis-003.adoc#v1-3-0[&#60; Capítulo Anterior] | <<v1-4-0,Topo>> | xref:001-genesis/001-genesis-005.adoc#v1-5-0[Próximo Capítulo &#62;]