include::./index.adoc[]

[[v1-37-0]]
=== Gênesis, 37
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-37-1]]

^<<v1-37-1,1>>^ E JACÓ habitou na terra das peregrinações de seu pai, na terra de Canaã.

[[v1-37-2]]

^<<v1-37-2,2>>^ Estas são  as gerações de Jacó: Sendo  José de dezessete anos, apascentava as ovelhas com seus irmãos, e estava  este mancebo com os filhos de Bilha, e com os filhos de Zilpa, mulheres de seu pai; e José trazia uma má fama deles a seu pai.

[[v1-37-3]]

^<<v1-37-3,3>>^ E Israel amava a José mais do que a todos os seus filhos, porque era  filho da sua velhice; e fez-lhe uma túnica de várias  cores.

[[v1-37-4]]

^<<v1-37-4,4>>^ Vendo pois seus irmãos que seu pai o amava mais do que a todos os seus irmãos, aborreceram-no, e não podiam falar com ele pacificamente.

[[v1-37-5]]

^<<v1-37-5,5>>^ Sonhou também José um sonho, que contou a seus irmãos: por isso o aborreciam ainda mais.

[[v1-37-6]]

^<<v1-37-6,6>>^ E disse-lhes: Ouvi, peço-vos, este sonho, que tenho sonhado:

[[v1-37-7]]

^<<v1-37-7,7>>^ Eis que estávamos  atando molhos no meio do campo, e eis que o meu molho se levantava, e também ficava em pé, e eis que os vossos molhos o rodeavam, e se inclinavam ao meu molho.

[[v1-37-8]]

^<<v1-37-8,8>>^ Então lhe disseram seus irmãos: Tu pois deveras reinarás sobre nós? Tu deveras terás domínio sobre nós? Por isso tanto mais o aborreciam por seus sonhos e por suas palavras.

[[v1-37-9]]

^<<v1-37-9,9>>^ E sonhou ainda outro sonho, e o contou a seus irmãos, e disse: Eis que ainda sonhei um sonho: e eis que o sol, e a lua, e onze estrelas se inclinavam a mim.

[[v1-37-10]]

^<<v1-37-10,10>>^ E contando-o a seu pai e a seus irmãos, repreendeu-o seu pai, e disse-lhe: Que sonho é  este que sonhaste? Porventura viremos, eu e tua mãe, e teus irmãos, a inclinar-nos perante ti em terra?

[[v1-37-11]]

^<<v1-37-11,11>>^ Seus irmãos pois o invejavam: seu pai porém guardava este negócio no seu coração.

[[v1-37-12]]

^<<v1-37-12,12>>^ E seus irmãos foram apascentar o rebanho de seu pai, junto de Siquém.

[[v1-37-13]]

^<<v1-37-13,13>>^ Disse pois Israel a José: Não apascentam os teus irmãos junto de Siquém? Vem, e enviar-te-ei a eles. E ele lhe disse: Eis-me aqui.

[[v1-37-14]]

^<<v1-37-14,14>>^ E ele lhe disse: Ora vai e vê como estão teus irmãos, e como está o rebanho, e traze-me resposta. Assim o enviou do vale de Hebrom, e José veio a Siquém.

[[v1-37-15]]

^<<v1-37-15,15>>^ E achou-o um varão, porque ele andava errado pelo campo, e perguntou-lhe o varão, dizendo: Que procuras?

[[v1-37-16]]

^<<v1-37-16,16>>^ E ele disse: Procuro meus irmãos; dize-me, peço-te, onde eles apascentam.

[[v1-37-17]]

^<<v1-37-17,17>>^ E disse aquele varão: Foram-se daqui; porque ouvi-lhes dizer: Vamos a Dotã. José pois seguiu seus irmãos, e achou-os em Dotã.

[[v1-37-18]]

^<<v1-37-18,18>>^ E viram-no de longe, e, antes que chegasse a eles, conspiraram contra ele, para o matarem.

[[v1-37-19]]

^<<v1-37-19,19>>^ E disseram uns aos outros: Eis lá vem o sonhador-mor!

[[v1-37-20]]

^<<v1-37-20,20>>^ Vinde pois agora, e matemo-lo, e lancemo-lo numa destas covas, e diremos: Uma besta-fera o comeu; e veremos que será dos seus sonhos.

[[v1-37-21]]

^<<v1-37-21,21>>^ E ouvindo-o Rúben, livrou-o das suas mãos, e disse: Não lhe tiremos a vida.

[[v1-37-22]]

^<<v1-37-22,22>>^ Também lhes disse Rúben: Não derrameis sangue; lançai-o nesta cova, que está  no deserto, e não lanceis mãos nele; para livrá-lo das suas mãos, e para torná-lo a seu pai.

[[v1-37-23]]

^<<v1-37-23,23>>^ E aconteceu que, chegando José a seus irmãos, tiraram a José a sua túnica, a túnica de várias  cores, que trazia.

[[v1-37-24]]

^<<v1-37-24,24>>^ E tomaram-no, e lançaram-no na cova; porém a cova estava  vazia, não havia  água nela.

[[v1-37-25]]

^<<v1-37-25,25>>^ Depois assentaram-se a comer pão: e levantaram os seus olhos, e olharam, e eis que uma companhia de ismaelitas vinha de Gileade; e seus camelos traziam especiarias, e bálsamo, e mirra, e iam levar isso ao Egito.

[[v1-37-26]]

^<<v1-37-26,26>>^ Então Judá disse aos seus irmãos: Que proveito haverá  em que matemos a nosso irmão, e escondamos a sua morte?

[[v1-37-27]]

^<<v1-37-27,27>>^ Vinde, e vendamo-lo a estes ismaelitas, e não seja nossa mão sobre ele: porque ele é nosso irmão, nossa carne. E seus irmãos obedeceram.

[[v1-37-28]]

^<<v1-37-28,28>>^ Passando pois os mercadores midianitas, tiraram, e alçaram a José da cova, e venderam José por vinte moedas  de prata aos ismaelitas, os quais levaram José ao Egito.

[[v1-37-29]]

^<<v1-37-29,29>>^ Tornando pois Rúben à cova, eis que José não estava  na cova; então rasgou os seus vestidos,

[[v1-37-30]]

^<<v1-37-30,30>>^ E tornou a seus irmãos, e disse: O moço não aparece ; e eu aonde irei?

[[v1-37-31]]

^<<v1-37-31,31>>^ Então tomaram a túnica de José, e mataram um cabrito, e tingiram a túnica no sangue.

[[v1-37-32]]

^<<v1-37-32,32>>^ E enviaram a túnica de várias  cores, e fizeram levá-la a seu pai, e disseram: Temos achado esta túnica ; conhece agora se esta será  ou não a túnica de teu filho.

[[v1-37-33]]

^<<v1-37-33,33>>^ E conheceu-a, e disse: É a túnica de meu filho; uma besta-fera o comeu, certamente foi despedaçado José.

[[v1-37-34]]

^<<v1-37-34,34>>^ Então Jacó rasgou os seus vestidos, e pôs saco sobre os seus lombos, e lamentou a seu filho muitos dias.

[[v1-37-35]]

^<<v1-37-35,35>>^ E levantaram-se todos os seus filhos e todas as suas filhas, para o consolarem; recusou porém ser consolado, e disse: Na verdade com choro hei de descer ao meu filho até à sepultura. Assim o chorou seu pai.

[[v1-37-36]]

^<<v1-37-36,36>>^ E os midianitas venderam-no no Egito a Potifar, eunuco de Faraó, capitão da guarda.

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]