include::./index.adoc[]

[[v1-18-0]]
=== Gênesis, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-18-1]]

^<<v1-18-1,1>>^ DEPOIS apareceu-lhe o Senhor  nos carvalhais de Manre, estando ele assentado à porta da tenda, quando tinha aquecido o dia.

[[v1-18-2]]

^<<v1-18-2,2>>^ E levantou os seus olhos, e olhou, e eis três varões estavam em pé junto a ele. E vendo- os , correu da porta da tenda ao seu encontro, e inclinou-se à terra,

[[v1-18-3]]

^<<v1-18-3,3>>^ E disse: Meu Senhor, se agora tenho achado graça nos teus olhos, rogo-te que não passes de teu servo.

[[v1-18-4]]

^<<v1-18-4,4>>^ Traga-se agora uma pouca de água e lavai os vossos pés, e recostai-vos debaixo desta árvore;

[[v1-18-5]]

^<<v1-18-5,5>>^ E trarei um bocado de pão, para que esforceis o vosso coração; depois passareis adiante, porquanto por isso chegastes até vosso servo. E disseram: Assim faze como tens dito.

[[v1-18-6]]

^<<v1-18-6,6>>^ E Abraão apressou-se em ir ter com Sara à tenda, e disse-lhe: Amassa depressa três medidas de flor de farinha, e faze bolos.

[[v1-18-7]]

^<<v1-18-7,7>>^ E correu Abraão às vacas, e tomou uma vitela tenra e boa, e deu- a  ao moço, que se apressou em prepará-la.

[[v1-18-8]]

^<<v1-18-8,8>>^ E tomou manteiga e leite, e a vitela que tinha preparado, e pôs tudo  diante deles, e ele estava em pé junto a eles debaixo da árvore; e comeram.

[[v1-18-9]]

^<<v1-18-9,9>>^ E disseram-lhe: Onde está  Sara, tua mulher? E ele disse: Ei-la aí está  na tenda.

[[v1-18-10]]

^<<v1-18-10,10>>^ E disse: Certamente tornarei a ti por este  tempo da vida; e eis que Sara tua mulher terá um filho. E ouviu- o  Sara à porta da tenda, que estava  atrás dele.

[[v1-18-11]]

^<<v1-18-11,11>>^ E eram  Abraão e Sara já velhos, e  adiantados em idade; já a Sara havia cessado o costume das mulheres.

[[v1-18-12]]

^<<v1-18-12,12>>^ Assim pois riu-se Sara consigo, dizendo: Terei ainda  deleite depois de haver envelhecido, sendo também o meu senhor já velho?

[[v1-18-13]]

^<<v1-18-13,13>>^ E disse o Senhor a Abraão: Porque se riu Sara, dizendo: Na verdade gerarei eu ainda, havendo já envelhecido?

[[v1-18-14]]

^<<v1-18-14,14>>^ Haveria cousa alguma difícil ao Senhor ? Ao tempo determinado tornarei a ti por este  tempo da vida, e Sara terá um filho.

[[v1-18-15]]

^<<v1-18-15,15>>^ E Sara negou, dizendo: Não me ri: porquanto temeu. E ele  disse: Não digas isso , porque te riste.

[[v1-18-16]]

^<<v1-18-16,16>>^ E levantaram-se aqueles varões dali; e olharam para a banda de Sodoma; e Abraão ia com eles, acompanhando-os.

[[v1-18-17]]

^<<v1-18-17,17>>^ E disse o Senhor : Ocultarei eu a Abraão o que faço,

[[v1-18-18]]

^<<v1-18-18,18>>^ Visto que Abraão certamente virá a ser uma grande e poderosa nação, e nele serão benditas todas as nações da terra?

[[v1-18-19]]

^<<v1-18-19,19>>^ Porque eu o tenho conhecido, que ele há de ordenar a seus filhos e a sua casa depois dele, para que guardem o caminho do Senhor , para obrarem com  justiça e juízo; para que o Senhor  faça vir sobre Abraão o que acerca dele tem falado.

[[v1-18-20]]

^<<v1-18-20,20>>^ Disse mais o Senhor : Porquanto o clamor de Sodoma e Gomorra se tem multiplicado, e porquanto o seu pecado se tem agravado muito,

[[v1-18-21]]

^<<v1-18-21,21>>^ Descerei agora, e verei se com efeito têm praticado segundo este clamor, que é vindo até mim; e se não, sabê-lo-ei.

[[v1-18-22]]

^<<v1-18-22,22>>^ Então viraram aqueles varões o rosto dali, e foram-se para Sodoma; mas Abraão ficou ainda em pé diante da face do Senhor.

[[v1-18-23]]

^<<v1-18-23,23>>^ E chegou-se Abraão, dizendo: Destruirás também o justo com o ímpio?

[[v1-18-24]]

^<<v1-18-24,24>>^ Se porventura houver cinquenta justos na cidade, destruí-los-ás também, e não pouparás o lugar por causa dos cinquenta justos que estão  dentro dela?

[[v1-18-25]]

^<<v1-18-25,25>>^ Longe de ti que faças tal coisa, que mates o justo com o ímpio; que o justo seja como o ímpio, longe de ti seja.  Não faria justiça o Juiz de toda a terra?

[[v1-18-26]]

^<<v1-18-26,26>>^ Então disse o Senhor: Se eu em Sodoma achar cinquenta justos dentro da cidade, pouparei a todo o lugar por amor deles.

[[v1-18-27]]

^<<v1-18-27,27>>^ E respondeu Abraão, dizendo: Eis que agora me atrevi a falar ao Senhor, ainda que sou  pó e cinza:

[[v1-18-28]]

^<<v1-18-28,28>>^ Se porventura faltarem de cinquenta justos cinco, destruirás por aqueles cinco toda a cidade? E disse: Não a  destruirei, se eu achar ali quarenta e cinco.

[[v1-18-29]]

^<<v1-18-29,29>>^ E continuou ainda a falar-lhe, e disse: Se porventura acharem ali quarenta? E disse: Não o  farei por amor dos quarenta.

[[v1-18-30]]

^<<v1-18-30,30>>^ Disse mais: Ora não se ire o Senhor, se eu ainda  falar: Se porventura se acharem ali trinta? E disse: Não o  farei se achar ali trinta.

[[v1-18-31]]

^<<v1-18-31,31>>^ E disse: Eis que agora me atrevi a falar ao Senhor: Se porventura se acharem ali vinte? E disse: Não a  destruirei por amor dos vinte.

[[v1-18-32]]

^<<v1-18-32,32>>^ Disse mais: Ora não se ire o Senhor que ainda  só mais esta vez falo: Se porventura se acharem ali dez? E disse: Não a  destruirei por amor dos dez.

[[v1-18-33]]

^<<v1-18-33,33>>^ E foi-se o Senhor, quando acabou de falar a Abraão; e Abraão tornou ao seu lugar.

'''

xref:001-genesis/001-genesis-017.adoc#v1-17-0[&#60; Capítulo Anterior] | <<v1-18-0,Topo>> | xref:001-genesis/001-genesis-019.adoc#v1-19-0[Próximo Capítulo &#62;]