include::./index.adoc[]

[[v1-39-0]]
=== Gênesis, 39
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-39-1]]

^<<v1-39-1,1>>^ E JOSÉ foi levado ao Egito, e Potifar, eunuco de Faraó, capitão da guarda, varão egípcio, comprou-o da mão dos ismaelitas que o tinham levado lá.

[[v1-39-2]]

^<<v1-39-2,2>>^ E o Senhor estava com José, e foi varão próspero; e estava na casa de seu senhor egípcio.

[[v1-39-3]]

^<<v1-39-3,3>>^ Vendo pois o seu senhor que o Senhor estava  com ele, e que tudo o que ele fazia o Senhor prosperava em sua mão,

[[v1-39-4]]

^<<v1-39-4,4>>^ José achou graça em seus olhos, e servia-o; e ele o pôs sobre a sua casa, e entregou na sua mão tudo o que tinha.

[[v1-39-5]]

^<<v1-39-5,5>>^ E aconteceu que, desde que o pusera sobre a sua casa, e sobre tudo o que tinha, o Senhor abençoou a casa do egípcio por amor de José; e a bênção do Senhor foi sobre tudo o que tinha, na casa e no campo.

[[v1-39-6]]

^<<v1-39-6,6>>^ E deixou tudo o que tinha na mão de José, de maneira que de nada sabia do que estava  com ele, a não ser do pão que comia. E José era formoso de parecer, e formoso à vista.

[[v1-39-7]]

^<<v1-39-7,7>>^ E aconteceu depois destas cousas que a mulher de seu senhor pôs os seus olhos em José, e disse: Deita-te comigo.

[[v1-39-8]]

^<<v1-39-8,8>>^ Porém ele recusou, e disse à mulher do seu senhor: Eis que o meu senhor não sabe do que há em casa comigo, e entregou em minha mão tudo o que tem;

[[v1-39-9]]

^<<v1-39-9,9>>^ Ninguém há  maior do que eu nesta casa, e nenhuma cousa me vedou, senão a ti, porquanto tu és  sua mulher; como pois faria eu este tamanho mal, e pecaria contra Deus?

[[v1-39-10]]

^<<v1-39-10,10>>^ E aconteceu que, falando ela cada dia a José, e não lhe dando ele ouvidos para deitar-se com ela, e  estar com ela,

[[v1-39-11]]

^<<v1-39-11,11>>^ Sucedeu num certo dia que veio à casa para fazer o seu serviço; e nenhum dos da casa estava  ali;

[[v1-39-12]]

^<<v1-39-12,12>>^ E ela lhe pegou pelo seu vestido, dizendo: Deita-te comigo. E ele deixou o seu vestido na mão dela, e fugiu, e saiu para fora.

[[v1-39-13]]

^<<v1-39-13,13>>^ E aconteceu que, vendo ela que deixara o seu vestido em sua mão, e fugira para fora,

[[v1-39-14]]

^<<v1-39-14,14>>^ Chamou aos homens de sua casa, e falou-lhes, dizendo: Vede, trouxe-nos o varão hebreu, para escarnecer de nós; entrou até mim para deitar-se comigo, e eu gritei com grande voz,

[[v1-39-15]]

^<<v1-39-15,15>>^ E aconteceu que, ouvindo ele que eu levantava a minha voz e gritava, deixou o seu vestido comigo, e fugiu, e saiu para fora.

[[v1-39-16]]

^<<v1-39-16,16>>^ E ela pôs o seu vestido perto de si, até que o seu senhor veio à sua casa.

[[v1-39-17]]

^<<v1-39-17,17>>^ Então falou-lhe conforme as mesmas palavras, dizendo: Veio a mim o servo hebreu, que nos trouxeste para escarnecer de mim;

[[v1-39-18]]

^<<v1-39-18,18>>^ E aconteceu que, levantando eu a minha voz e gritando, ele deixou o seu vestido comigo, e fugiu para fora.

[[v1-39-19]]

^<<v1-39-19,19>>^ E aconteceu que, ouvindo o seu senhor as palavras de sua mulher, que lhe falava, dizendo: Conforme a estas mesmas palavras me fez teu servo, a sua ira se acendeu.

[[v1-39-20]]

^<<v1-39-20,20>>^ E o senhor de José o tomou, e o entregou na casa do cárcere, no lugar onde os presos do rei estavam  presos; assim esteve ali na casa do cárcere.

[[v1-39-21]]

^<<v1-39-21,21>>^ O Senhor, porém, estava com José, e estendeu sobre ele a sua benignidade, e deu-lhe graça aos olhos do carcereiro-mor.

[[v1-39-22]]

^<<v1-39-22,22>>^ E o carcereiro-mor entregou na mão de José todos os presos que estavam  na casa do cárcere, e ele fazia tudo o que se fazia ali.

[[v1-39-23]]

^<<v1-39-23,23>>^ E o carcereiro-mor não teve cuidado de nenhuma cousa que estava  na mão dele; porquanto o Senhor estava com ele, e tudo  o que ele fazia o Senhor prosperava.

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]