include::./index.adoc[]

[[v1-43-0]]
=== Gênesis, 43
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-43-1]]

^<<v1-43-1,1>>^ E A fome era  gravíssima na terra.

[[v1-43-2]]

^<<v1-43-2,2>>^ E aconteceu que, como acabaram de comer o mantimento que trouxeram do Egito, disse-lhes seu pai: Tornai, comprai-nos um pouco de alimento.

[[v1-43-3]]

^<<v1-43-3,3>>^ Mas Judá respondeu-lhe, dizendo: Fortemente nos protestou aquele varão, dizendo: Não vereis a minha face, se o vosso irmão não vier  convosco.

[[v1-43-4]]

^<<v1-43-4,4>>^ Se enviares conosco o nosso irmão, desceremos, e te compraremos alimento;

[[v1-43-5]]

^<<v1-43-5,5>>^ Mas se não o  enviares, não desceremos; porquanto aquele varão nos disse: Não vereis a minha face, se o vosso irmão não vier  convosco.

[[v1-43-6]]

^<<v1-43-6,6>>^ E disse Israel: Por que me fizestes tal  mal, fazendo saber àquele varão que tínheis ainda outro  irmão?

[[v1-43-7]]

^<<v1-43-7,7>>^ E eles disseram: Aquele varão particularmente nos perguntou por nós, e pela nossa parentela, dizendo: Vive ainda vosso pai? tendes mais um irmão? e respondemos-lhe conforme as mesmas palavras. Podíamos nós saber que diria: Trazei vosso irmão?

[[v1-43-8]]

^<<v1-43-8,8>>^ Então disse Judá a Israel, seu pai: Envia o mancebo comigo, e levantar-nos-emos, e iremos, para que vivamos, e não morramos, nem nós, nem tu, nem os nossos filhos.

[[v1-43-9]]

^<<v1-43-9,9>>^ Eu serei fiador por ele, da minha mão o requererás; se eu não to trouxer, e não o puser perante a tua face, serei réu de crime para contigo para sempre.

[[v1-43-10]]

^<<v1-43-10,10>>^ E se nós não nos tivéssemos detido, certamente já estaríamos segunda vez de volta.

[[v1-43-11]]

^<<v1-43-11,11>>^ Então disse-lhes Israel, seu pai: Pois que assim é , fazei isso; tomai do mais precioso desta terra em vossos vasos, e levai ao varão um presente: um pouco de bálsamo, e um pouco de mel, especiarias, e mirra, terebinto e amêndoas;

[[v1-43-12]]

^<<v1-43-12,12>>^ E tomai em vossas mãos dinheiro dobrado; e o dinheiro que tornou na boca dos vossos sacos tornai a levar em vossas mãos; bem pode ser que fosse erro.

[[v1-43-13]]

^<<v1-43-13,13>>^ Tomai também a vosso irmão, e levantai-vos, e voltai àquele varão;

[[v1-43-14]]

^<<v1-43-14,14>>^ E Deus Todo-poderoso vos dê misericórdia diante do varão, para que deixe vir convosco vosso outro irmão, e Benjamim; e eu, se for  desfilhado, desfilhado ficarei.

[[v1-43-15]]

^<<v1-43-15,15>>^ E os varões tomaram aquele presente, e tomaram dinheiro dobrado em suas mãos, e a Benjamim; e levantaram-se, e desceram ao Egito, e apresentaram-se diante da face de José.

[[v1-43-16]]

^<<v1-43-16,16>>^ Vendo pois José a Benjamim com eles, disse ao que estava  sobre a sua casa: Leva estes  varões à casa, e mata reses, e prepara tudo; porque estes  varões comerão comigo ao meio-dia.

[[v1-43-17]]

^<<v1-43-17,17>>^ E o varão fez como José dissera, e o varão levou aqueles varões à casa de José.

[[v1-43-18]]

^<<v1-43-18,18>>^ Então temeram aqueles varões, porquanto foram levados à casa de José, e diziam: Por causa do dinheiro que da outra vez voltou nos nossos sacos, fomos trazidos aqui , para nos criminar e cair sobre nós, para que nos tome por servos, e a nossos jumentos.

[[v1-43-19]]

^<<v1-43-19,19>>^ Por isso chegaram-se ao varão que estava  sobre a casa de José, e falaram com ele à porta da casa.

[[v1-43-20]]

^<<v1-43-20,20>>^ E disseram: Ai! senhor meu, certamente descemos dantes a comprar mantimento;

[[v1-43-21]]

^<<v1-43-21,21>>^ E aconteceu que, chegando nós à venda, e abrindo os nossos sacos, eis que o dinheiro de cada varão estava  na boca do seu saco, nosso dinheiro por seu peso; e tornamos a trazê-lo em nossas mãos;

[[v1-43-22]]

^<<v1-43-22,22>>^ Também trouxemos outro dinheiro em nossas mãos, para comprar mantimento; não sabemos quem tenha posto o nosso dinheiro nos nossos sacos.

[[v1-43-23]]

^<<v1-43-23,23>>^ E ele disse: Paz seja  convosco, não temais; o vosso Deus, e o Deus de vosso pai, vos tem dado um tesouro nos vossos sacos; o vosso dinheiro me chegou a mim. E trouxe-lhes fora a Simeão.

[[v1-43-24]]

^<<v1-43-24,24>>^ Depois levou o varão aqueles varões à casa de José, e deu- lhes  água, e lavaram os seus pés; também deu pasto aos seus jumentos.

[[v1-43-25]]

^<<v1-43-25,25>>^ E prepararam o presente, para quando José viesse ao meio-dia; porque tinham ouvido que ali haviam de comer pão.

[[v1-43-26]]

^<<v1-43-26,26>>^ Vindo pois José à casa, trouxeram-lhe ali o presente que estava na sua mão; e inclinaram-se a ele até à terra.

[[v1-43-27]]

^<<v1-43-27,27>>^ E ele lhes perguntou como estavam, e disse: Vosso pai, o velho de quem falastes está bem? ainda vive?

[[v1-43-28]]

^<<v1-43-28,28>>^ E eles disseram: Bem está o teu servo, nosso pai vive ainda. E abaixaram a cabeça, e inclinaram-se.

[[v1-43-29]]

^<<v1-43-29,29>>^ E ele levantou os seus olhos, e viu a Benjamim, seu irmão filho de sua mãe, e disse: Este é  o vosso irmão mais novo de quem me falastes? Depois ele disse: Deus te abençoe, meu filho.

[[v1-43-30]]

^<<v1-43-30,30>>^ E José apressou-se, porque as suas entranhas moveram-se para o seu irmão, e procurou onde  chorar; e entrou na câmara, e chorou ali.

[[v1-43-31]]

^<<v1-43-31,31>>^ Depois lavou o seu rosto, e saiu; e conteve-se, e disse: Ponde pão.

[[v1-43-32]]

^<<v1-43-32,32>>^ E puseram-lhe a ele  à parte, e a eles à parte, e aos egípcios, que comiam com ele, à parte; porque os egípcios não podem comer pão com os hebreus, porquanto é abominação para os egípcios.

[[v1-43-33]]

^<<v1-43-33,33>>^ E assentaram-se diante dele, o primogênito segundo a sua primogenitura, e o menor segundo a sua menoridade; do que os varões se maravilhavam entre si.

[[v1-43-34]]

^<<v1-43-34,34>>^ E apresentou-lhe as porções que estavam  diante dele; porém a porção de Benjamim era cinco vezes maior do que a de qualquer deles. E eles beberam, e se regalaram com ele.

'''

xref:001-genesis/001-genesis-042.adoc#v1-42-0[&#60; Capítulo Anterior] | <<v1-43-0,Topo>> | xref:001-genesis/001-genesis-044.adoc#v1-44-0[Próximo Capítulo &#62;]