include::./index.adoc[]

[[v1-41-0]]
=== Gênesis, 41
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-41-1]]

^<<v1-41-1,1>>^ E ACONTECEU que, ao fim de dois anos inteiros, Faraó sonhou, e eis que estava em pé junto ao rio,

[[v1-41-2]]

^<<v1-41-2,2>>^ E eis que subiam do rio sete vacas, formosas à vista e gordas de carne, e pastavam no prado.

[[v1-41-3]]

^<<v1-41-3,3>>^ E eis que subiam do rio após elas outras sete vacas, feias à vista e magras de carne; e paravam junto às outras  vacas na praia do rio.

[[v1-41-4]]

^<<v1-41-4,4>>^ E as vacas feias à vista, e magras de carne, comiam as sete vacas formosas à vista e gordas. Então acordou Faraó.

[[v1-41-5]]

^<<v1-41-5,5>>^ Depois dormiu, e sonhou outra vez, e eis que brotavam dum mesmo pé sete espigas cheias e boas.

[[v1-41-6]]

^<<v1-41-6,6>>^ E eis que sete espigas miúdas, e queimadas do vento oriental, brotavam após elas.

[[v1-41-7]]

^<<v1-41-7,7>>^ E as espigas miúdas devoravam as sete espigas grandes e cheias. Então acordou Faraó, e eis que era um  sonho.

[[v1-41-8]]

^<<v1-41-8,8>>^ E aconteceu que pela manhã o seu espírito perturbou-se, e enviou e chamou todos os adivinhadores do Egito, e todos os seus sábios; e Faraó contou-lhes os seus sonhos, mas ninguém havia  que os interpretasse a Faraó.

[[v1-41-9]]

^<<v1-41-9,9>>^ Então falou o copeiro-mor a Faraó, dizendo: Dos meus pecados me lembro hoje:

[[v1-41-10]]

^<<v1-41-10,10>>^ Estando Faraó mui indignado contra os seus servos, e pondo-me sob prisão na casa da guarda, a mim e ao padeiro-mor,

[[v1-41-11]]

^<<v1-41-11,11>>^ Então sonhamos um sonho na mesma noite, eu e ele, cada um conforme a interpretação do seu sonho sonhamos.

[[v1-41-12]]

^<<v1-41-12,12>>^ E estava  ali conosco um mancebo hebreu, servo do capitão da guarda, e contamos-lhos, e interpretou-nos os nossos sonhos, a cada um interpretou conforme o seu sonho.

[[v1-41-13]]

^<<v1-41-13,13>>^ E como ele nos interpretou, assim mesmo  foi feito: a mim me fez tornar ao meu estado, e a ele fez enforcar.

[[v1-41-14]]

^<<v1-41-14,14>>^ Então enviou Faraó, e chamou a José, e o fizeram sair logo da cova; e barbeou-se e mudou os seus vestidos, e veio a Faraó.

[[v1-41-15]]

^<<v1-41-15,15>>^ E Faraó disse a José: Eu sonhei um sonho, e ninguém há  que o interprete; mas de ti ouvi dizer que quando  ouves um sonho o interpretas.

[[v1-41-16]]

^<<v1-41-16,16>>^ E respondeu José a Faraó, dizendo: Isso não está em mim; Deus dará resposta de paz a Faraó.

[[v1-41-17]]

^<<v1-41-17,17>>^ Então disse Faraó a José: Eis que em meu sonho estava eu em pé na praia do rio,

[[v1-41-18]]

^<<v1-41-18,18>>^ E eis que subiam do rio sete vacas gordas de carne e formosas à vista, e pastavam no prado.

[[v1-41-19]]

^<<v1-41-19,19>>^ E eis que outras sete vacas subiam após estas, muito feias à vista, e magras de carne; não tenho visto outras tais, quanto à fealdade, em toda a terra do Egito.

[[v1-41-20]]

^<<v1-41-20,20>>^ E as vacas magras e feias comiam as primeiras sete vacas gordas;

[[v1-41-21]]

^<<v1-41-21,21>>^ E entravam em suas entranhas, mas não se conhecia que houvessem entrado em suas entranhas; porque o seu parecer era  feio como no princípio. Então acordei.

[[v1-41-22]]

^<<v1-41-22,22>>^ Depois vi em meu sonho, e eis que dum mesmo pé subiam sete espigas cheias e boas;

[[v1-41-23]]

^<<v1-41-23,23>>^ E eis que sete espigas secas, miúdas e  queimadas do vento oriental brotavam após elas.

[[v1-41-24]]

^<<v1-41-24,24>>^ E as sete espigas miúdas devoravam as sete espigas boas. E eu disse-o aos magos, mas ninguém houve  que mo interpretasse.

[[v1-41-25]]

^<<v1-41-25,25>>^ Então disse José a Faraó: O sonho de Faraó é  um só; o que Deus há de fazer, notificou-o a Faraó.

[[v1-41-26]]

^<<v1-41-26,26>>^ As sete vacas formosas são  sete anos; as sete espigas formosas também são  sete anos; o sonho é um só.

[[v1-41-27]]

^<<v1-41-27,27>>^ E as sete vacas magras e feias à vista, que subiam depois delas, são  sete anos, como as sete espigas miúdas e queimadas do vento oriental; serão sete anos de fome.

[[v1-41-28]]

^<<v1-41-28,28>>^ Esta é  a palavra que tenho dito a Faraó; o que Deus há de fazer, mostrou-o a Faraó.

[[v1-41-29]]

^<<v1-41-29,29>>^ E eis que vêm sete anos, e haverá grande fartura em toda a terra do Egito.

[[v1-41-30]]

^<<v1-41-30,30>>^ E depois deles levantar-se-ão sete anos de fome, e toda aquela fartura será esquecida na terra do Egito, e a fome consumirá a terra;

[[v1-41-31]]

^<<v1-41-31,31>>^ E não será conhecida a abundância na terra, por causa daquela fome que haverá  depois; porquanto será gravíssima.

[[v1-41-32]]

^<<v1-41-32,32>>^ E que o sonho foi duplicado duas vezes a Faraó, é porque esta cousa é determinada de Deus, e Deus se apressa a fazê-la.

[[v1-41-33]]

^<<v1-41-33,33>>^ Portanto Faraó se proveja agora dum varão entendido e sábio, e o ponha sobre a terra do Egito.

[[v1-41-34]]

^<<v1-41-34,34>>^ Faça isso  Faraó, e ponha governadores sobre a terra, e tome a quinta parte da terra do Egito nos sete anos de fartura,

[[v1-41-35]]

^<<v1-41-35,35>>^ E ajuntem toda a comida destes bons anos, que vêm, e amontoem trigo debaixo da mão de Faraó, para mantimento nas cidades, e o guardem;

[[v1-41-36]]

^<<v1-41-36,36>>^ Assim será o mantimento para provimento da terra, para os sete anos de fome, que haverá na terra do Egito; para que a terra não pereça de fome.

[[v1-41-37]]

^<<v1-41-37,37>>^ E esta palavra foi boa aos olhos de Faraó, e aos olhos de todos os seus servos.

[[v1-41-38]]

^<<v1-41-38,38>>^ E disse Faraó a seus servos: Acharíamos um varão como este, em quem haja  o espírito de Deus?

[[v1-41-39]]

^<<v1-41-39,39>>^ Depois disse Faraó a José: Pois que Deus te fez saber tudo isto, ninguém há tão  entendido e sábio como tu.

[[v1-41-40]]

^<<v1-41-40,40>>^ Tu estarás sobre a minha casa, e por tua boca se governará todo o meu povo; somente no trono eu serei maior que tu.

[[v1-41-41]]

^<<v1-41-41,41>>^ Disse mais Faraó a José: Vês aqui te tenho posto sobre toda a terra do Egito.

[[v1-41-42]]

^<<v1-41-42,42>>^ E tirou Faraó o anel da sua mão, e o pôs na mão de José, e o fez vestir de vestidos de linho fino, e pôs um colar de ouro no seu pescoço,

[[v1-41-43]]

^<<v1-41-43,43>>^ E o fez subir no segundo carro que tinha, e clamavam diante dele: Ajoelhai. Assim o pôs sobre toda a terra do Egito.

[[v1-41-44]]

^<<v1-41-44,44>>^ E disse Faraó a José: Eu sou  Faraó; porém sem ti ninguém levantará a sua mão ou o seu pé em toda a terra do Egito.

[[v1-41-45]]

^<<v1-41-45,45>>^ E chamou Faraó o nome de José Zafnate-Paneá, e deu-lhe por mulher a Asenate, filha de Potífera, sacerdote de On; e saiu José por toda  a terra do Egito.

[[v1-41-46]]

^<<v1-41-46,46>>^ E José era  da idade de trinta anos quando esteve diante da face de Faraó, rei do Egito. E saiu José da face de Faraó, e passou por toda a terra do Egito.

[[v1-41-47]]

^<<v1-41-47,47>>^ E a terra produziu nos sete anos de fartura a mãos cheias.

[[v1-41-48]]

^<<v1-41-48,48>>^ E ajuntou todo o mantimento dos sete anos, que houve na terra do Egito, e guardou o mantimento nas cidades, pondo nas cidades o mantimento do campo que estava  ao redor de cada cidade.

[[v1-41-49]]

^<<v1-41-49,49>>^ Assim ajuntou José muitíssimo trigo, como a areia do mar, até que cessou de contar; porquanto não havia  numeração.

[[v1-41-50]]

^<<v1-41-50,50>>^ E nasceram a José dois filhos (antes que viesse o ano de fome), que lhe deu Asenate, filha de Potífera, sacerdote de On.

[[v1-41-51]]

^<<v1-41-51,51>>^ E chamou José o nome do primogênito Manassés; porque disse : Deus me fez esquecer de todo o meu trabalho, e de toda a casa de meu pai.

[[v1-41-52]]

^<<v1-41-52,52>>^ E o nome do segundo chamou Efraim; porque disse : Deus me fez crescer na terra da minha aflição.

[[v1-41-53]]

^<<v1-41-53,53>>^ Então acabaram-se os sete anos de fartura que havia na terra do Egito,

[[v1-41-54]]

^<<v1-41-54,54>>^ E começaram a vir os sete anos de fome, como José tinha dito; e havia fome em todas as terras, mas em toda a terra do Egito havia pão.

[[v1-41-55]]

^<<v1-41-55,55>>^ E tendo toda a terra do Egito fome, clamou o povo a Faraó por pão; e Faraó disse a todos os egípcios: Ide a José; o que ele vos disser, fazei.

[[v1-41-56]]

^<<v1-41-56,56>>^ Havendo pois fome sobre toda a terra, abriu José tudo em que havia mantimento , e vendeu aos egípcios; porque a fome prevaleceu na terra do Egito.

[[v1-41-57]]

^<<v1-41-57,57>>^ E todas as terras vinham ao Egito, para comprar de José; porquanto a fome prevaleceu em todas as terras.

'''

xref:001-genesis/001-genesis-040.adoc#v1-40-0[&#60; Capítulo Anterior] | <<v1-41-0,Topo>> | xref:001-genesis/001-genesis-042.adoc#v1-42-0[Próximo Capítulo &#62;]