include::./index.adoc[]

[[v1-44-0]]
=== Gênesis, 44
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-44-1]]

^<<v1-44-1,1>>^ E DEU ordem ao que estava sobre a sua casa, dizendo: Enche os sacos destes varões de mantimento, quanto puderem levar, e põe o dinheiro de cada varão na boca do seu saco.

[[v1-44-2]]

^<<v1-44-2,2>>^ E o meu copo, o copo de prata, porás na boca do saco do mais novo, com o dinheiro do seu trigo. E fez conforme a palavra de José, que tinha dito.

[[v1-44-3]]

^<<v1-44-3,3>>^ Vinda a luz da manhã, despediram-se estes varões, eles com os seus jumentos.

[[v1-44-4]]

^<<v1-44-4,4>>^ Saindo eles da cidade, e  não se havendo ainda distanciado, disse José ao que estava  sobre a sua casa: Levanta-te, e persegue aqueles varões; e, alcançando-os, lhes dirás: Por que pagastes mal por bem?

[[v1-44-5]]

^<<v1-44-5,5>>^ Não é  este o copo  por que bebe meu senhor? e em que ele bem adivinha? Fizestes mal no que fizestes.

[[v1-44-6]]

^<<v1-44-6,6>>^ E alcançou-os, e falou-lhes as mesmas palavras.

[[v1-44-7]]

^<<v1-44-7,7>>^ E eles disseram-lhe: Por que diz meu senhor tais palavras? Longe estejam teus servos de fazerem semelhante cousa.

[[v1-44-8]]

^<<v1-44-8,8>>^ Eis que o dinheiro, que temos achado nas bocas dos nossos sacos, te tornamos a trazer desde a terra de Canaã; como pois furtaríamos da casa do teu senhor prata ou ouro?

[[v1-44-9]]

^<<v1-44-9,9>>^ Aquele dos teus servos em quem for achado, morra; e ainda nós seremos escravos do meu senhor.

[[v1-44-10]]

^<<v1-44-10,10>>^ E ele disse: Ora seja também assim conforme as vossas palavras; aquele em quem se achar será meu escravo, porém vós sereis desculpados.

[[v1-44-11]]

^<<v1-44-11,11>>^ E eles apressaram-se, e cada um pôs em terra o seu saco, e cada um abriu o seu saco.

[[v1-44-12]]

^<<v1-44-12,12>>^ E buscou, começando no maior, e acabando no mais novo; e achou-se o copo no saco de Benjamim.

[[v1-44-13]]

^<<v1-44-13,13>>^ Então rasgaram os seus vestidos, e carregou cada um o seu jumento, e tornaram à cidade.

[[v1-44-14]]

^<<v1-44-14,14>>^ E veio Judá com os seus irmãos à casa de José, porque ele ainda estava ali; e prostraram-se diante dele na terra.

[[v1-44-15]]

^<<v1-44-15,15>>^ E disse-lhes José: Que é  isto que fizestes? não sabeis vós que tal homem como eu bem adivinha?

[[v1-44-16]]

^<<v1-44-16,16>>^ Então disse Judá: Que diremos a meu senhor? que falaremos? e como nos justificaremos? Achou Deus a iniquidade de teus servos; eis que somos  escravos de meu senhor, tanto nós como aquele em cuja mão foi achado o copo.

[[v1-44-17]]

^<<v1-44-17,17>>^ Mas ele disse: Longe de mim que eu tal faça; o varão em cuja mão o copo foi achado, aquele será meu servo; porém vós subi em paz para vosso pai.

[[v1-44-18]]

^<<v1-44-18,18>>^ Então Judá se chegou a ele, e disse: Ai! senhor meu, deixa, peço-te, o teu servo dizer uma palavra aos ouvidos de meu senhor, e não se acenda a tua ira contra o teu servo; porque tu és  como Faraó.

[[v1-44-19]]

^<<v1-44-19,19>>^ Meu senhor perguntou a seus servos, dizendo: Tendes vós pai, ou irmão?

[[v1-44-20]]

^<<v1-44-20,20>>^ E dissemos a meu senhor: Temos um velho pai e um moço da sua velhice, o mais novo, cujo irmão é morto; e ele ficou só de sua mãe, e seu pai o ama.

[[v1-44-21]]

^<<v1-44-21,21>>^ Então tu disseste a teus servos: Trazei-mo a mim, e porei os meus olhos sobre ele.

[[v1-44-22]]

^<<v1-44-22,22>>^ E nós dissemos a meu senhor: Aquele moço não poderá deixar a seu pai; se deixar a seu pai, este  morrerá.

[[v1-44-23]]

^<<v1-44-23,23>>^ Então tu disseste a teus servos: Se vosso irmão mais novo não descer convosco, nunca mais vereis a minha face.

[[v1-44-24]]

^<<v1-44-24,24>>^ E aconteceu que, subindo nós a teu servo meu pai, e contando-lhe as palavras de meu senhor,

[[v1-44-25]]

^<<v1-44-25,25>>^ Disse nosso pai: Tornai, comprai-nos um pouco de mantimento.

[[v1-44-26]]

^<<v1-44-26,26>>^ E nós dissemos: Não poderemos descer; mas, se nosso irmão menor for conosco, desceremos; pois não poderemos ver a face do varão, se este nosso irmão menor não estiver  conosco.

[[v1-44-27]]

^<<v1-44-27,27>>^ Então disse-nos teu servo, meu pai: Vós sabeis que minha mulher me deu dois filhos;

[[v1-44-28]]

^<<v1-44-28,28>>^ E um ausentou-se de mim, e eu disse: Certamente foi despedaçado, e não o tenho visto até agora;

[[v1-44-29]]

^<<v1-44-29,29>>^ Se agora também tirardes a este da minha face, e lhe, acontecer algum desastre, fareis descer as minhas cãs com dor à sepultura.

[[v1-44-30]]

^<<v1-44-30,30>>^ Agora pois, indo eu a teu servo meu pai, e o moço não indo conosco, como a sua alma está atada com a alma dele,

[[v1-44-31]]

^<<v1-44-31,31>>^ Acontecerá que, vendo ele que o moço ali não está , morrerá; e teus servos farão descer as cãs de teu servo, nosso pai, com tristeza à sepultura.

[[v1-44-32]]

^<<v1-44-32,32>>^ Porque teu servo se deu por fiador por este moço para com meu pai, dizendo: Se não to tornar, eu serei culpado a meu pai todos os dias.

[[v1-44-33]]

^<<v1-44-33,33>>^ Agora, pois, fique teu servo em lugar deste moço por escravo de meu senhor, e que suba o moço com os seus irmãos.

[[v1-44-34]]

^<<v1-44-34,34>>^ Porque como subirei eu a meu pai, se o moço não for  comigo? para que não veja eu o mal que sobrevirá a meu pai.

'''

xref:001-genesis/001-genesis-043.adoc#v1-43-0[&#60; Capítulo Anterior] | <<v1-44-0,Topo>> | xref:001-genesis/001-genesis-045.adoc#v1-45-0[Próximo Capítulo &#62;]