include::./index.adoc[]

[[v1-32-0]]
=== Gênesis, 32
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-32-1]]

^<<v1-32-1,1>>^ E FOI também  Jacó o seu caminho, e encontraram-no os anjos de Deus.

[[v1-32-2]]

^<<v1-32-2,2>>^ E Jacó disse, quando os viu: Este é  o exército de Deus. E chamou o nome daquele lugar Maanaim.

[[v1-32-3]]

^<<v1-32-3,3>>^ E enviou Jacó mensageiros diante da sua face a Esaú, seu irmão, à terra de Seir, território de Edom.

[[v1-32-4]]

^<<v1-32-4,4>>^ E ordenou-lhes, dizendo: Assim direis a meu senhor Esaú: Assim diz Jacó, teu servo: Como peregrino morei com Labão, e me detive lá  até agora;

[[v1-32-5]]

^<<v1-32-5,5>>^ E tendo bois e jumentos, ovelhas, e servos e servas; e enviei para o anunciar a meu senhor, para que ache graça em teus olhos.

[[v1-32-6]]

^<<v1-32-6,6>>^ E os mensageiros tornaram a Jacó, dizendo: Fomos a teu irmão Esaú; e também ele vem a encontrar-te, e quatrocentos varões com ele.

[[v1-32-7]]

^<<v1-32-7,7>>^ Então Jacó temeu muito, e angustiou-se; e repartiu o povo que com ele estava, e as ovelhas, e as vacas, e os camelos, em dois bandos.

[[v1-32-8]]

^<<v1-32-8,8>>^ Porque dizia: Se Esaú vier a um bando, e o ferir, o outro bando escapará.

[[v1-32-9]]

^<<v1-32-9,9>>^ Disse mais Jacó: Deus de meu pai Abraão, e Deus de meu pai Isaque, ó Senhor, que me disseste: Torna à tua terra, e à tua parentela, e far-te-ei bem;

[[v1-32-10]]

^<<v1-32-10,10>>^ Menor sou eu que todas as beneficências, e que toda a fidelidade que tiveste com teu servo; porque com meu cajado passei este Jordão, e agora me tornei em dois bandos:

[[v1-32-11]]

^<<v1-32-11,11>>^ Livra-me, peço-te, da mão de meu irmão, da mão de Esaú: porque o temo, que porventura não venha, e me fira, e  a mãe com os filhos.

[[v1-32-12]]

^<<v1-32-12,12>>^ E tu o disseste: Certamente te farei bem e farei a tua semente como a areia do mar, que pela multidão não se pode contar.

[[v1-32-13]]

^<<v1-32-13,13>>^ E passou ali aquela noite; e tomou, do que lhe veio à sua mão, um presente para seu irmão Esaú:

[[v1-32-14]]

^<<v1-32-14,14>>^ Duzentas cabras, e vinte bodes; duzentas ovelhas, e vinte carneiros;

[[v1-32-15]]

^<<v1-32-15,15>>^ Trinta camelas de leite com suas crias, quarenta vacas, e dez novilhos; vinte jumentas, e dez jumentinhos;

[[v1-32-16]]

^<<v1-32-16,16>>^ E deu-o na mão dos seus servos, cada rebanho à parte, e disse a seus servos: Passai adiante da minha face, e ponde espaço entre rebanho e rebanho.

[[v1-32-17]]

^<<v1-32-17,17>>^ E ordenou ao primeiro, dizendo: Quando Esaú, meu irmão, te encontrar, e te perguntar, dizendo: De quem és , e para onde vais, e de quem são  estes diante da tua face?

[[v1-32-18]]

^<<v1-32-18,18>>^ Então dirás: São de teu servo Jacó, presente que envia a meu senhor, a Esaú; e eis que ele mesmo vem também atrás de nós.

[[v1-32-19]]

^<<v1-32-19,19>>^ E ordenou também ao segundo, e ao terceiro, e a todos os que vinham atrás dos rebanhos, dizendo: Conforme a esta mesma palavra, falareis a Esaú, quando o achardes.

[[v1-32-20]]

^<<v1-32-20,20>>^ E direis também: Eis que o teu servo Jacó vem  atrás de nós. Porque dizia: Eu  o aplacarei com o presente que vai diante de mim, e depois verei a sua face; porventura aceitará a minha face.

[[v1-32-21]]

^<<v1-32-21,21>>^ Assim passou o presente diante da sua face; ele porém passou aquela noite no arraial.

[[v1-32-22]]

^<<v1-32-22,22>>^ E levantou-se aquela mesma noite, e tomou as suas duas mulheres, e as suas duas servas, e os seus onze filhos, e passou o vau de Jaboque.

[[v1-32-23]]

^<<v1-32-23,23>>^ E tomou-os, e fê-los passar o ribeiro; e fez passar tudo  o que tinha.

[[v1-32-24]]

^<<v1-32-24,24>>^ Jacó porém ficou só; e lutou com ele um varão, até que a alva subia.

[[v1-32-25]]

^<<v1-32-25,25>>^ E vendo que não prevalecia contra ele, tocou a juntura de sua coxa, e se deslocou a juntura da coxa de Jacó, lutando com ele.

[[v1-32-26]]

^<<v1-32-26,26>>^ E disse: Deixa-me ir, porque já a alva subiu. Porém ele disse: Não te deixarei ir, se me não abençoares.

[[v1-32-27]]

^<<v1-32-27,27>>^ E disse-lhe: Qual é  o teu nome? E ele disse: Jacó.

[[v1-32-28]]

^<<v1-32-28,28>>^ Então disse: Não se chamará mais o teu nome Jacó, mas Israel: pois como príncipe lutaste com Deus e com os homens, e prevaleceste.

[[v1-32-29]]

^<<v1-32-29,29>>^ E Jacó lhe perguntou, e disse: Dá-me, peço-te, a saber o teu nome. E disse: Por que perguntas pelo meu nome? E abençoou-o ali.

[[v1-32-30]]

^<<v1-32-30,30>>^ E chamou Jacó o nome daquele lugar Peniel, porque dizia : Tenho visto a Deus face a face, e a minha alma foi salva.

[[v1-32-31]]

^<<v1-32-31,31>>^ E saiu-lhe o sol, quando passou a Peniel; e manquejava da sua coxa.

[[v1-32-32]]

^<<v1-32-32,32>>^ Por isso os filhos de Israel não comem o nervo encolhido, que está  sobre a juntura da coxa, até o dia de hoje; porquanto ele tocara a juntura da coxa de Jacó no nervo encolhido.

'''

xref:001-genesis/001-genesis-031.adoc#v1-31-0[&#60; Capítulo Anterior] | <<v1-32-0,Topo>> | xref:001-genesis/001-genesis-033.adoc#v1-33-0[Próximo Capítulo &#62;]