include::./index.adoc[]

[[v1-6-0]]
=== Gênesis, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-6-1]]

^<<v1-6-1,1>>^ E ACONTECEU que, como os homens se começaram a multiplicar sobre a face da terra, e lhes nasceram filhas;

[[v1-6-2]]

^<<v1-6-2,2>>^ Viram os filhos de Deus que as filhas dos homens eram formosas; e tomaram para si mulheres de todas as que escolheram.

[[v1-6-3]]

^<<v1-6-3,3>>^ Então disse o Senhor: Não contenderá o meu Espírito para sempre com o homem; porque ele também é  carne: porém os seus dias serão cento e vinte anos.

[[v1-6-4]]

^<<v1-6-4,4>>^ Havia naqueles dias gigantes na terra; e também depois, quando os filhos de Deus entraram às filhas dos homens, e delas  geraram filhos : estes eram  os valentes que houve na antiguidade, os varões de fama.

[[v1-6-5]]

^<<v1-6-5,5>>^ E viu o Senhor que a maldade do homem se multiplicara sobre a terra, e que toda a imaginação dos pensamentos de seu coração era só má continuamente.

[[v1-6-6]]

^<<v1-6-6,6>>^ Então arrependeu-se o Senhor de haver feito o homem sobre a terra, e pesou-lhe em seu coração.

[[v1-6-7]]

^<<v1-6-7,7>>^ E disse o Senhor: Destruirei, de sobre a face da terra, o homem que criei, desde o homem até ao animal, até ao réptil, e até à ave dos céus; porque me arrependo de os haver feito.

[[v1-6-8]]

^<<v1-6-8,8>>^ Noé porém achou graça aos olhos do Senhor.

[[v1-6-9]]

^<<v1-6-9,9>>^ Estas são  as gerações de Noé: Noé era varão justo e reto em suas gerações: Noé andava com Deus.

[[v1-6-10]]

^<<v1-6-10,10>>^ E gerou Noé três filhos: Sem, Cão, e Jafé.

[[v1-6-11]]

^<<v1-6-11,11>>^ A terra porém estava corrompida diante da face de Deus: e encheu-se a terra de violência.

[[v1-6-12]]

^<<v1-6-12,12>>^ E viu Deus a terra, e eis que estava corrompida; porque toda a carne havia corrompido o seu caminho sobre a terra.

[[v1-6-13]]

^<<v1-6-13,13>>^ Então disse Deus a Noé: O fim de toda a carne é vindo perante a minha face; porque a terra está cheia de violência; e eis que os desfarei com a terra.

[[v1-6-14]]

^<<v1-6-14,14>>^ Faze para ti uma arca da madeira de Gofer: farás compartimentos na arca, e a betumarás por dentro e por fora com betume.

[[v1-6-15]]

^<<v1-6-15,15>>^ E desta maneira farás: De trezentos côvados o comprimento da arca, e de cinquenta côvados a sua largura, e de trinta côvados a sua altura.

[[v1-6-16]]

^<<v1-6-16,16>>^ Farás na arca uma janela, e de um côvado a acabarás em cima; e a porta da arca porás ao seu lado; far-lhe-ás andares  baixos, segundos e terceiros.

[[v1-6-17]]

^<<v1-6-17,17>>^ Porque eis que eu trago um dilúvio de águas sobre a terra, para desfazer toda a carne em que há  espírito de vida debaixo dos céus: tudo o que há na terra expirará.

[[v1-6-18]]

^<<v1-6-18,18>>^ Mas contigo estabelecerei o meu pacto; e entrarás na arca tu e os teus filhos, e a tua mulher, e as mulheres de teus filhos contigo.

[[v1-6-19]]

^<<v1-6-19,19>>^ E de tudo o que vive, de toda a carne, dois de cada espécie, meterás na arca, para os conservares vivos contigo; macho e fêmea serão.

[[v1-6-20]]

^<<v1-6-20,20>>^ Das aves conforme a sua espécie, e dos animais conforme a sua espécie, de todo o réptil da terra conforme a sua espécie, dois de cada espécie  virão a ti, para os conservares em vida.

[[v1-6-21]]

^<<v1-6-21,21>>^ E tu toma para ti de toda a comida que se come, e ajunta-a para ti; e te será para mantimento para ti e para eles.

[[v1-6-22]]

^<<v1-6-22,22>>^ Assim fez Noé: conforme a tudo o que Deus lhe mandou, assim o fez.

'''

xref:001-genesis/001-genesis-005.adoc#v1-5-0[&#60; Capítulo Anterior] | <<v1-6-0,Topo>> | xref:001-genesis/001-genesis-007.adoc#v1-7-0[Próximo Capítulo &#62;]