include::./index.adoc[]

[[v1-21-0]]
=== Gênesis, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-21-1]]

^<<v1-21-1,1>>^ E O Senhor  visitou a Sara, como tinha dito; e fez o Senhor a Sara como tinha falado.

[[v1-21-2]]

^<<v1-21-2,2>>^ E concebeu Sara, e deu a Abraão um filho na sua velhice, ao tempo determinado, que Deus lhe tinha dito.

[[v1-21-3]]

^<<v1-21-3,3>>^ E chamou Abraão o nome de seu filho que lhe nascera, que Sara lhe dera, Isaque.

[[v1-21-4]]

^<<v1-21-4,4>>^ E Abraão circuncidou o seu filho Isaque, quando era da idade de oito dias, como Deus lhe tinha ordenado.

[[v1-21-5]]

^<<v1-21-5,5>>^ E era  Abraão da idade de cem anos, quando lhe nasceu Isaque seu filho.

[[v1-21-6]]

^<<v1-21-6,6>>^ E disse Sara: Deus me tem feito riso; todo aquele que o ouvir, se rirá comigo.

[[v1-21-7]]

^<<v1-21-7,7>>^ Disse mais: Quem diria a Abraão, que Sara daria de mamar a filhos? porque lhe dei um filho na sua velhice.

[[v1-21-8]]

^<<v1-21-8,8>>^ E cresceu o menino, e foi desmamado; então Abraão fez um grande banquete no dia em que Isaque foi desmamado.

[[v1-21-9]]

^<<v1-21-9,9>>^ E viu Sara que o filho de Hagar a egípcia, que esta tinha dado a Abraão, zombava.

[[v1-21-10]]

^<<v1-21-10,10>>^ E disse a Abraão: Deita fora esta serva e o seu filho; porque o filho desta serva não herdará com meu filho, com Isaque.

[[v1-21-11]]

^<<v1-21-11,11>>^ E pareceu esta palavra mui má aos olhos de Abraão, por causa de seu filho.

[[v1-21-12]]

^<<v1-21-12,12>>^ Porém Deus disse a Abraão: Não te pareça mal aos teus olhos acerca do moço, e acerca da tua serva; em tudo o que Sara te diz, ouve a sua voz; porque em Isaque será chamada a tua semente.

[[v1-21-13]]

^<<v1-21-13,13>>^ Mas também do filho desta serva farei uma nação, porquanto é  tua semente.

[[v1-21-14]]

^<<v1-21-14,14>>^ Então se levantou Abraão pela manhã de madrugada, e tomou pão, e um odre de água, e os deu a Hagar, pondo-os sobre o seu ombro; também lhe deu  o menino, e despediu-a; e ela foi-se, andando errante no deserto de Berseba.

[[v1-21-15]]

^<<v1-21-15,15>>^ E consumida a água do odre, lançou o menino debaixo de uma das árvores.

[[v1-21-16]]

^<<v1-21-16,16>>^ E foi-se, e assentou-se em frente, afastando-se a distância de um tiro de arco; porque dizia: Que não veja eu morrer o menino. E assentou-se em frente, e levantou a sua voz, e chorou.

[[v1-21-17]]

^<<v1-21-17,17>>^ E ouviu Deus a voz do menino, e bradou o anjo de Deus a Hagar desde os céus, e disse-lhe: Que tens, Hagar? não temas, porque Deus ouviu a voz do rapaz desde o lugar onde está.

[[v1-21-18]]

^<<v1-21-18,18>>^ Ergue-te, levanta o moço, e pega-lhe pela mão, porque dele farei uma grande nação.

[[v1-21-19]]

^<<v1-21-19,19>>^ E abriu-lhe Deus os olhos, e viu um poço d’água, e foi-se, e encheu o odre de água, e deu de beber ao moço.

[[v1-21-20]]

^<<v1-21-20,20>>^ E era Deus com o moço, que cresceu; e habitou no deserto, e foi frecheiro.

[[v1-21-21]]

^<<v1-21-21,21>>^ E habitou no deserto de Parã; e sua mãe tomou-lhe mulher da terra do Egito.

[[v1-21-22]]

^<<v1-21-22,22>>^ E aconteceu naquele mesmo tempo que Abimeleque, com Ficol, príncipe do seu exército, falou com Abraão, dizendo: Deus é  contigo em tudo o que fazes;

[[v1-21-23]]

^<<v1-21-23,23>>^ Agora pois, jura-me aqui por Deus que me não mentirás a mim, nem a meu filho, nem a meu neto; segundo a beneficência que te fiz, me farás a mim, e à terra onde peregrinaste.

[[v1-21-24]]

^<<v1-21-24,24>>^ E disse Abraão: Eu jurarei.

[[v1-21-25]]

^<<v1-21-25,25>>^ Abraão, porém, repreendeu a Abimeleque por causa de um poço de água, que os servos de Abimeleque haviam tomado por força.

[[v1-21-26]]

^<<v1-21-26,26>>^ Então disse Abimeleque: Eu não sei quem fez isto; e também tu mo não fizeste saber, nem eu o ouvi senão hoje.

[[v1-21-27]]

^<<v1-21-27,27>>^ E tomou Abraão ovelhas e vacas, e deu-as a Abimeleque; e fizeram ambos concerto.

[[v1-21-28]]

^<<v1-21-28,28>>^ Pôs Abraão, porém, à parte sete cordeiras do rebanho.

[[v1-21-29]]

^<<v1-21-29,29>>^ E Abimeleque disse a Abraão: Para que estão aqui estas sete cordeiras, que puseste à parte?

[[v1-21-30]]

^<<v1-21-30,30>>^ E disse: Tomarás estas  sete cordeiras de minha mão, para que sejam em testemunho que eu cavei este poço.

[[v1-21-31]]

^<<v1-21-31,31>>^ Por isso se chamou aquele lugar Berseba, porquanto ambos juraram ali.

[[v1-21-32]]

^<<v1-21-32,32>>^ Assim fizeram concerto em Berseba. Depois se levantou Abimeleque e Ficol, príncipe do seu exército, e tornaram para a terra dos filisteus.

[[v1-21-33]]

^<<v1-21-33,33>>^ E plantou um bosque em Berseba, e invocou lá o nome do Senhor, Deus eterno.

[[v1-21-34]]

^<<v1-21-34,34>>^ E peregrinou Abraão na terra dos filisteus muitos dias.

'''

xref:001-genesis/001-genesis-020.adoc#v1-20-0[&#60; Capítulo Anterior] | <<v1-21-0,Topo>> | xref:001-genesis/001-genesis-022.adoc#v1-22-0[Próximo Capítulo &#62;]