include::./index.adoc[]

[[v1-26-0]]
=== Gênesis, 26
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-26-1]]

^<<v1-26-1,1>>^ E HAVIA fome na terra, além da primeira fome, que foi nos dias de Abraão: por isso foi-se Isaque a Abimeleque, rei dos filisteus, em Gerar.

[[v1-26-2]]

^<<v1-26-2,2>>^ E apareceu-lhe o Senhor, e disse: Não desças ao Egito; habita na terra que eu te disser:

[[v1-26-3]]

^<<v1-26-3,3>>^ Peregrina nesta terra, e serei contigo, e te abençoarei; porque a ti e à tua semente darei todas estas terras, e confirmarei o juramento que tenho jurado a Abraão teu pai;

[[v1-26-4]]

^<<v1-26-4,4>>^ E multiplicarei a tua semente como as estrelas dos céus, e darei à tua semente todas estas terras; e em tua semente serão benditas todas as nações da terra;

[[v1-26-5]]

^<<v1-26-5,5>>^ Porquanto Abraão obedeceu à minha voz, e guardou o meu mandado, os meus preceitos, os meus estatutos, e as minhas leis.

[[v1-26-6]]

^<<v1-26-6,6>>^ Assim habitou Isaque em Gerar.

[[v1-26-7]]

^<<v1-26-7,7>>^ E perguntando-lhe os varões daquele lugar acerca de sua mulher, disse: É  minha irmã; porque temia dizer: É  minha mulher; para que porventura (dizia ele)  me não matem os varões daquele lugar por amor de Rebeca; porque era  formosa à vista.

[[v1-26-8]]

^<<v1-26-8,8>>^ E aconteceu que, como ele esteve ali muito tempo, Abimeleque rei dos filisteus olhou por uma janela, e viu, e eis que Isaque estava  brincando com Rebeca sua mulher.

[[v1-26-9]]

^<<v1-26-9,9>>^ Então chamou Abimeleque a Isaque, e disse: Eis que na verdade é  tua mulher; como pois disseste: É  minha irmã? E disse-lhe Isaque: Porque eu dizia: Para que eu porventura não morra por causa dela.

[[v1-26-10]]

^<<v1-26-10,10>>^ E disse Abimeleque: Que é  isto que  nos fizeste? Facilmente se teria deitado alguém deste povo com a tua mulher, e tu terias trazido sobre nós um delito.

[[v1-26-11]]

^<<v1-26-11,11>>^ E mandou Abimeleque a todo o povo, dizendo: Qualquer que tocar neste varão ou em sua mulher, certamente morrerá.

[[v1-26-12]]

^<<v1-26-12,12>>^ E semeou Isaque naquela mesma terra, e colheu naquele mesmo ano cem medidas, porque o Senhor o abençoava.

[[v1-26-13]]

^<<v1-26-13,13>>^ E engrandeceu-se o varão, e ia-se engrandecendo, até que se tornou mui grande;

[[v1-26-14]]

^<<v1-26-14,14>>^ E tinha possessão de ovelhas, e possessão de vacas, e muita gente de serviço, de maneira que os filisteus o invejavam.

[[v1-26-15]]

^<<v1-26-15,15>>^ E todos os poços, que os servos de seu pai tinham cavado nos dias de seu pai Abraão, os filisteus entulharam e encheram de terra.

[[v1-26-16]]

^<<v1-26-16,16>>^ Disse também Abimeleque a Isaque: Aparta-te de nós; porque muito mais poderoso te tens feito do que nós.

[[v1-26-17]]

^<<v1-26-17,17>>^ Então Isaque foi-se dali e fez o seu assento no vale de Gerar, e habitou lá.

[[v1-26-18]]

^<<v1-26-18,18>>^ E tornou Isaque, e cavou os poços de água que cavaram nos dias de Abraão seu pai, e que os filisteus taparam depois da morte de Abraão, e chamou-os pelos nomes que os chamara seu pai.

[[v1-26-19]]

^<<v1-26-19,19>>^ Cavaram pois os servos de Isaque naquele vale, e acharam ali um poço de águas vivas.

[[v1-26-20]]

^<<v1-26-20,20>>^ E os pastores de Gerar porfiaram com os pastores de Isaque, dizendo: Esta água é  nossa. Por isso chamou o nome daquele poço Eseque, porque contenderam com ele.

[[v1-26-21]]

^<<v1-26-21,21>>^ Então cavaram outro poço, e também porfiaram sobre ele: por isso chamou o seu nome Sitna.

[[v1-26-22]]

^<<v1-26-22,22>>^ E partiu dali, e cavou outro poço, e não porfiaram sobre ele: por isso chamou o seu nome Reobote, e disse: Porque agora nos alargou o Senhor, e crescemos nesta terra.

[[v1-26-23]]

^<<v1-26-23,23>>^ Depois subiu dali a Berseba,

[[v1-26-24]]

^<<v1-26-24,24>>^ E apareceu-lhe o Senhor naquela mesma noite, e disse: Eu sou  o Deus de Abraão teu pai: não temas, porque eu sou  contigo, e abençoar-te-ei, e multiplicarei a tua semente por amor de Abraão meu servo.

[[v1-26-25]]

^<<v1-26-25,25>>^ Então edificou ali um altar, e invocou o nome do Senhor, e armou ali a sua tenda; e os servos de Isaque cavaram ali um poço.

[[v1-26-26]]

^<<v1-26-26,26>>^ E Abimeleque veio a ele de Gerar, com Ausate seu amigo, e Ficol, príncipe do seu exército.

[[v1-26-27]]

^<<v1-26-27,27>>^ E disse-lhe Isaque: Por que viestes a mim, pois que vós me aborreceis, e me enviastes de vós?

[[v1-26-28]]

^<<v1-26-28,28>>^ E eles disseram: Havemos visto, na verdade, que o Senhor é contigo, pelo que dissemos: Haja agora juramento entre nós, entre nós e ti; e façamos concerto contigo,

[[v1-26-29]]

^<<v1-26-29,29>>^ Que nos não faças mal, como nós te não temos tocado, e como te fizemos somente bem, e te deixamos ir em paz. Agora tu és  o bendito do Senhor.

[[v1-26-30]]

^<<v1-26-30,30>>^ Então lhes fez um banquete, e comeram e beberam;

[[v1-26-31]]

^<<v1-26-31,31>>^ E levantaram-se de madrugada, e juraram um ao outro; depois os despediu Isaque, e despediram-se dele em paz.

[[v1-26-32]]

^<<v1-26-32,32>>^ E aconteceu naquele mesmo dia que vieram os servos de Isaque, e anunciaram-lhe acerca do negócio do poço, que tinham cavado; e disseram-lhe: Temos achado água.

[[v1-26-33]]

^<<v1-26-33,33>>^ E chamou-o Seba: por isso é  o nome daquela cidade Berseba até o dia de hoje.

[[v1-26-34]]

^<<v1-26-34,34>>^ Ora sendo Esaú da idade de quarenta anos, tomou por mulher a Judite, filha de Beeri, heteu, e a Basmate filha de Elom, heteu.

[[v1-26-35]]

^<<v1-26-35,35>>^ E estas  foram para Isaque e Rebeca uma amargura de espírito.

'''

xref:001-genesis/001-genesis-025.adoc#v1-25-0[&#60; Capítulo Anterior] | <<v1-26-0,Topo>> | xref:001-genesis/001-genesis-027.adoc#v1-27-0[Próximo Capítulo &#62;]