include::./index.adoc[]

[[v1-24-0]]
=== Gênesis, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-24-1]]

^<<v1-24-1,1>>^ E ERA Abraão já velho e  adiantado em idade, e o Senhor havia abençoado a Abraão em tudo.

[[v1-24-2]]

^<<v1-24-2,2>>^ E disse Abraão ao seu servo, o mais velho da casa, que tinha o governo sobre tudo o que possuía: Põe agora a tua mão debaixo da minha coxa,

[[v1-24-3]]

^<<v1-24-3,3>>^ Para que eu te faça jurar pelo Senhor Deus dos céus e Deus da terra, que não tomarás para meu filho mulher das filhas dos cananeus no meio dos quais eu habito.

[[v1-24-4]]

^<<v1-24-4,4>>^ Mas que irás à minha terra e à minha parentela, e daí  tomarás mulher para meu filho Isaque.

[[v1-24-5]]

^<<v1-24-5,5>>^ E disse-lhe o servo: Porventura não quererá seguir-me a mulher a esta terra. Farei pois tornar o teu filho à terra donde saíste?

[[v1-24-6]]

^<<v1-24-6,6>>^ E Abraão lhe disse: Guarda-te, que não faças lá tornar o meu filho.

[[v1-24-7]]

^<<v1-24-7,7>>^ O Senhor, Deus dos céus, que me tomou da casa de meu pai e da terra da minha parentela, e que me falou, e que me jurou, dizendo: À tua semente darei esta terra: Ele enviará o seu anjo adiante da tua face, para que tomes mulher de lá para meu filho.

[[v1-24-8]]

^<<v1-24-8,8>>^ Se a mulher, porém, não quiser seguir-te, serás livre deste meu juramento; somente não faças lá tornar a meu filho.

[[v1-24-9]]

^<<v1-24-9,9>>^ Então pôs o servo a sua mão debaixo da coxa de Abraão seu senhor, e jurou-lhe sobre este negócio.

[[v1-24-10]]

^<<v1-24-10,10>>^ E o servo tomou dez camelos, dos camelos do seu senhor, e partiu, pois que toda a fazenda de seu senhor estava  em sua mão, e levantou-se e partiu para Mesopotâmia, para a cidade de Naor,

[[v1-24-11]]

^<<v1-24-11,11>>^ E fez ajoelhar os camelos fora da cidade, junto a um poço de água, pela tarde ao tempo que as moças saíam a tirar água.

[[v1-24-12]]

^<<v1-24-12,12>>^ E disse: Ó Senhor, Deus de meu senhor Abraão! dá-me hoje bom encontro e faze beneficência ao meu senhor Abraão!

[[v1-24-13]]

^<<v1-24-13,13>>^ Eis que eu estou em pé junto à fonte de água, e as filhas dos varões desta cidade saem para tirar água;

[[v1-24-14]]

^<<v1-24-14,14>>^ Seja pois que a donzela, a quem eu disser: Abaixa agora o teu cântaro para que eu beba, e ela disser: Bebe, e também darei de beber aos teus camelos; esta seja  a quem designaste ao teu servo Isaque, e que eu conheça nisso que fizeste beneficência a meu senhor.

[[v1-24-15]]

^<<v1-24-15,15>>^ E sucedeu que, antes que ele acabasse de falar, eis que Rebeca, que havia nascido a Betuel, filho de Milca, mulher de Naor, irmão de Abraão, saía com o seu cântaro sobre o seu ombro.

[[v1-24-16]]

^<<v1-24-16,16>>^ E a donzela era  mui formosa à vista, virgem, a quem varão não havia conhecido; e desceu à fonte, e encheu o seu cântaro, e subiu.

[[v1-24-17]]

^<<v1-24-17,17>>^ Então o servo correu-lhe ao encontro, e disse: Ora deixa-me beber uma pouca de água do teu cântaro.

[[v1-24-18]]

^<<v1-24-18,18>>^ E ela disse: Bebe, meu senhor. E apressou-se, e abaixou o seu cântaro sobre a sua mão, e deu-lhe de beber.

[[v1-24-19]]

^<<v1-24-19,19>>^ E, acabando ela de lhe dar de beber, disse: Tirarei também água  para os teus camelos, até que acabem de beber.

[[v1-24-20]]

^<<v1-24-20,20>>^ E apressou-se, e vazou o seu cântaro na pia, e correu outra vez ao poço para tirar água , e tirou para todos os seus camelos.

[[v1-24-21]]

^<<v1-24-21,21>>^ E o varão estava admirado de vê-la, calando-se, para saber se o Senhor havia prosperado a sua jornada, ou não.

[[v1-24-22]]

^<<v1-24-22,22>>^ E aconteceu que, acabando os camelos de beber, tomou o varão um pendente de ouro de meio siclo de peso, e duas pulseiras para as suas mãos, do peso de dez siclos  de ouro,

[[v1-24-23]]

^<<v1-24-23,23>>^ E disse: De quem és  filha? faze-mo saber, peço-te; há também em casa de teu pai lugar para nós pousarmos?

[[v1-24-24]]

^<<v1-24-24,24>>^ E ela disse: Eu sou  a filha de Betuel, filho de Milca, o qual ela deu a Naor.

[[v1-24-25]]

^<<v1-24-25,25>>^ Disse-lhe mais: Também temos palha e muito pasto, e lugar para passar a noite.

[[v1-24-26]]

^<<v1-24-26,26>>^ Então inclinou-se aquele varão, e adorou ao Senhor,

[[v1-24-27]]

^<<v1-24-27,27>>^ E disse: Bendito seja  o Senhor Deus de meu senhor Abraão, que não retirou a sua beneficência e a sua verdade de meu senhor: quanto a mim, o Senhor me guiou no caminho à casa dos irmãos de meu senhor.

[[v1-24-28]]

^<<v1-24-28,28>>^ E a donzela correu, e fez saber estas cousas na casa de sua mãe.

[[v1-24-29]]

^<<v1-24-29,29>>^ E Rebeca tinha um irmão, cujo nome era  Labão; e Labão correu ao encontro daquele varão à fonte.

[[v1-24-30]]

^<<v1-24-30,30>>^ E aconteceu que, quando ele viu o pendente, e as pulseiras sobre as mãos de sua irmã, e quando ouviu as palavras de sua irmã Rebeca, que dizia: Assim me falou aquele varão; veio ao varão, e eis que estava em pé junto aos camelos à fonte.

[[v1-24-31]]

^<<v1-24-31,31>>^ E disse: Entra, bendito do Senhor, porque estarás fora? pois eu já preparei a casa e o lugar para os camelos.

[[v1-24-32]]

^<<v1-24-32,32>>^ Então veio aquele varão à casa, e desataram os camelos, e deram palha e pasto aos camelos, e água para lavar os pés dele e os pés dos varões que estavam  com ele.

[[v1-24-33]]

^<<v1-24-33,33>>^ Depois puseram de comer diante dele. Ele porém disse: Não comerei, até que tenha dito as minhas palavras. E ele disse: Fala.

[[v1-24-34]]

^<<v1-24-34,34>>^ Então disse: Eu sou  o servo de Abraão.

[[v1-24-35]]

^<<v1-24-35,35>>^ E o Senhor abençoou muito o meu senhor, de maneira que foi engrandecido, e deu-lhe ovelhas e vacas, e prata e ouro, e servos e servas, e camelos e jumentos.

[[v1-24-36]]

^<<v1-24-36,36>>^ E Sara, a mulher do meu senhor, gerou um filho a meu senhor depois da sua velhice, e ele deu-lhe tudo quanto tem.

[[v1-24-37]]

^<<v1-24-37,37>>^ E meu senhor me fez jurar, dizendo: Não tomarás mulher para meu filho das filhas dos cananeus, em cuja terra habito:

[[v1-24-38]]

^<<v1-24-38,38>>^ Irás porém à casa de meu pai, e à minha família, e tomarás mulher para meu filho.

[[v1-24-39]]

^<<v1-24-39,39>>^ Então disse eu ao meu senhor: Porventura não me seguirá a mulher.

[[v1-24-40]]

^<<v1-24-40,40>>^ E ele  me disse: O Senhor, em cuja presença tenho andado, enviará o seu anjo contigo, e prosperará o teu caminho para que tomes mulher para meu filho da minha família e da casa de meu pai:

[[v1-24-41]]

^<<v1-24-41,41>>^ Então serás livre do meu juramento, quando fores à minha família; e se não ta derem, livre serás do meu juramento.

[[v1-24-42]]

^<<v1-24-42,42>>^ E hoje cheguei à fonte, e disse: Ó Senhor, Deus de meu senhor Abraão! se tu agora prosperas o meu caminho, no qual eu ando,

[[v1-24-43]]

^<<v1-24-43,43>>^ Eis que estou junto à fonte de água: seja pois que a donzela que sair para tirar água  e à qual eu disser: Ora dá-me uma pouca de água do teu cântaro;

[[v1-24-44]]

^<<v1-24-44,44>>^ E ela me disser: Bebe tu também, e também tirarei água para os teus camelos; esta seja  a mulher que o Senhor designou ao filho de meu senhor.

[[v1-24-45]]

^<<v1-24-45,45>>^ E antes que eu acabasse de falar no meu coração, eis que Rebeca saía com seu cântaro sobre o seu ombro, e desceu à fonte, e tirou água ; e eu lhe disse: Ora dá-me de beber.

[[v1-24-46]]

^<<v1-24-46,46>>^ E ela se apressou, e abaixou o seu cântaro de sobre si, e disse: Bebe, e também darei de beber aos teus camelos: e bebi, e ela deu também de beber aos camelos.

[[v1-24-47]]

^<<v1-24-47,47>>^ Então lhe perguntei, e disse: De quem és  filha? E ela disse: Filha de Betuel, filho de Naor, que lhe gerou Milca. Então eu pus o pendente no seu rosto, e as pulseiras sobre as suas mãos;

[[v1-24-48]]

^<<v1-24-48,48>>^ E inclinando-me adorei ao Senhor, e bendisse ao Senhor, Deus do meu senhor Abraão que me havia encaminhado pelo caminho da verdade, para tomar a filha do irmão de meu senhor para seu filho.

[[v1-24-49]]

^<<v1-24-49,49>>^ Agora pois, se vós haveis de mostrar beneficência e verdade a meu senhor, fazei-mo saber; e se não, também  mo fazei saber, para que eu olhe à mão direita, ou à esquerda.

[[v1-24-50]]

^<<v1-24-50,50>>^ Então responderam Labão e Betuel, e disseram: Do Senhor procedeu este negócio; não podemos falar-te mal ou bem.

[[v1-24-51]]

^<<v1-24-51,51>>^ Eis que, Rebeca está  diante da tua face; toma-a, e vai-te; seja a mulher do filho de teu senhor, como tem dito o Senhor.

[[v1-24-52]]

^<<v1-24-52,52>>^ E aconteceu que o servo de Abraão, ouvindo as suas palavras, inclinou-se à terra diante do Senhor.

[[v1-24-53]]

^<<v1-24-53,53>>^ E tirou o servo vasos de prata e vasos de ouro, e vestidos, e deu-os a Rebeca; também deu cousas preciosas a seu irmão e a sua mãe.

[[v1-24-54]]

^<<v1-24-54,54>>^ Então comeram e beberam, ele e os varões que com ele estavam, e passaram a noite. E levantaram-se pela manhã, e disse: Deixai-me ir a meu senhor.

[[v1-24-55]]

^<<v1-24-55,55>>^ Então disseram seu irmão e sua mãe: Fique a donzela conosco alguns  dias, ou pelo menos dez dias, e depois irá.

[[v1-24-56]]

^<<v1-24-56,56>>^ Ele porém lhes disse: Não me detenhais, pois o Senhor tem prosperado o meu caminho; deixai-me partir, para que eu volte a meu senhor.

[[v1-24-57]]

^<<v1-24-57,57>>^ E disseram: Chamemos a donzela, e perguntemos-lho.

[[v1-24-58]]

^<<v1-24-58,58>>^ E chamaram a Rebeca, e disseram-lhe: Irás tu com este varão? Ela respondeu: Irei.

[[v1-24-59]]

^<<v1-24-59,59>>^ Então despediram a Rebeca sua irmã, e a sua ama, e ao servo de Abraão e a seus varões,

[[v1-24-60]]

^<<v1-24-60,60>>^ E abençoaram a Rebeca e disseram-lhe: Ó nossa irmã, sejas tu em milhares de milhares, e que a tua semente possua a porta de seus aborrecedores!

[[v1-24-61]]

^<<v1-24-61,61>>^ E Rebeca se levantou com as suas moças, e subiram sobre os camelos, e seguiram o varão: e tomou aquele servo a Rebeca, e partiu.

[[v1-24-62]]

^<<v1-24-62,62>>^ Ora Isaque vinha do caminho do poço de Laai-Roi; porque habitava na terra do sul.

[[v1-24-63]]

^<<v1-24-63,63>>^ E Isaque saíra a orar no campo, sobre a tarde: e levantou seus olhos, e olhou, e eis que os camelos vinham.

[[v1-24-64]]

^<<v1-24-64,64>>^ Rebeca também levantou seus olhos, e viu a Isaque, e lançou-se do camelo.

[[v1-24-65]]

^<<v1-24-65,65>>^ E disse ao servo: Quem é  aquele varão que vem pelo campo ao nosso encontro? E o servo disse: Este é  meu senhor. Então tomou ela o véu, e cobriu-se.

[[v1-24-66]]

^<<v1-24-66,66>>^ E o servo contou a Isaque todas as cousas que fizera.

[[v1-24-67]]

^<<v1-24-67,67>>^ E Isaque trouxe-a para a tenda de sua mãe Sara, e tomou a Rebeca, e foi-lhe por mulher, e amou-a. Assim Isaque foi consolado depois da morte  de sua mãe.

'''

xref:001-genesis/001-genesis-023.adoc#v1-23-0[&#60; Capítulo Anterior] | <<v1-24-0,Topo>> | xref:001-genesis/001-genesis-025.adoc#v1-25-0[Próximo Capítulo &#62;]