include::./index.adoc[]

[[v1-50-0]]
=== Gênesis, 50
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-50-1]]

^<<v1-50-1,1>>^ ENTÃO José se lançou sobre o rosto de seu pai; e chorou sobre ele, e o beijou.

[[v1-50-2]]

^<<v1-50-2,2>>^ E José ordenou aos seus servos, os médicos, que embalsamassem a seu pai; e os médicos embalsamaram a Israel.

[[v1-50-3]]

^<<v1-50-3,3>>^ E cumpriram-se-lhe quarenta dias; porque assim se cumprem os dias daqueles que se embalsamam; e os egípcios o choraram setenta dias.

[[v1-50-4]]

^<<v1-50-4,4>>^ Passados pois os dias de seu choro, falou José à casa de Faraó, dizendo: Se agora tenho achado graça aos vossos olhos, rogo-vos que faleis aos ouvidos de Faraó, dizendo:

[[v1-50-5]]

^<<v1-50-5,5>>^ Meu pai me fez jurar, dizendo: Eis que eu morro; em meu sepulcro, que cavei para mim na terra de Canaã, ali me sepultarás. Agora pois, te peço, que eu suba, para que sepulte a meu pai; então voltarei.

[[v1-50-6]]

^<<v1-50-6,6>>^ E Faraó disse: Sobe, e sepulta a teu pai como ele te fez jurar.

[[v1-50-7]]

^<<v1-50-7,7>>^ E José subiu para sepultar a seu pai; e subiram com ele todos os servos de Faraó, os anciãos da sua casa, e todos os anciãos da terra do Egito,

[[v1-50-8]]

^<<v1-50-8,8>>^ Como também toda a casa de José, e seus irmãos, e a casa de seu pai; somente deixaram na terra de Gósen os seus meninos, e as suas ovelhas, e as suas vacas.

[[v1-50-9]]

^<<v1-50-9,9>>^ E subiram também com ele, tanto carros como gente a cavalo; e o concurso foi grandíssimo.

[[v1-50-10]]

^<<v1-50-10,10>>^ Chegando eles pois à eira do espinhal, que está  além do Jordão, fizeram um grande e gravíssimo pranto, e fez a seu pai um grande pranto por sete dias.

[[v1-50-11]]

^<<v1-50-11,11>>^ E vendo os moradores da terra, os cananeus, o luto na eira do espinhal, disseram: É este o pranto grande dos egípcios. Por isso chamou-se o seu nome Abelmizraim, que está  além do Jordão.

[[v1-50-12]]

^<<v1-50-12,12>>^ E fizeram-lhe os seus filhos assim como ele lhes ordenara,

[[v1-50-13]]

^<<v1-50-13,13>>^ Pois os seus filhos o levaram à terra de Canaã, e o sepultaram na cova do campo de Macpela, que Abraão tinha comprado com o campo, por herança de sepultura, a Efrom, o heteu, em frente de Manre.

[[v1-50-14]]

^<<v1-50-14,14>>^ Depois tornou José para o Egito, ele e seus irmãos, e todos os que com ele subiram a sepultar seu pai, depois de haver sepultado seu pai.

[[v1-50-15]]

^<<v1-50-15,15>>^ Vendo então os irmãos de José que seu pai já estava morto, disseram: Porventura nos aborrecerá José, e nos pagará certamente todo o mal que lhe fizemos.

[[v1-50-16]]

^<<v1-50-16,16>>^ Portanto enviaram a José, dizendo: Teu pai mandou, antes da sua morte dizendo:

[[v1-50-17]]

^<<v1-50-17,17>>^ Assim direis a José: Perdoa, rogo-te, a transgressão de teus irmãos, e o seu pecado, porque te fizeram mal; agora pois rogamos-te que perdoes a transgressão dos servos do Deus de teu pai. E José chorou quando eles lhe falavam.

[[v1-50-18]]

^<<v1-50-18,18>>^ Depois vieram também seus irmãos, e prostraram-se diante dele, e disseram: Eis-nos aqui por teus servos.

[[v1-50-19]]

^<<v1-50-19,19>>^ E José lhes disse: Não temais, porque porventura estou  eu em lugar de Deus?

[[v1-50-20]]

^<<v1-50-20,20>>^ Vós bem intentastes mal contra mim, porém  Deus o tornou em bem, para fazer como se vê neste dia, para conservar em vida a um povo grande;

[[v1-50-21]]

^<<v1-50-21,21>>^ Agora pois não temais; eu vos sustentarei a vós e a vossos meninos. Assim os consolou, e falou segundo o coração deles.

[[v1-50-22]]

^<<v1-50-22,22>>^ José pois habitou no Egito, ele e a casa de seu pai; e viveu José cento e dez anos.

[[v1-50-23]]

^<<v1-50-23,23>>^ E viu José os filhos de Efraim, da terceira geração ; também os filhos de Maquir, filho de Manassés, nasceram sobre os joelhos de José.

[[v1-50-24]]

^<<v1-50-24,24>>^ E disse José a seus irmãos: Eu morro; mas Deus certamente vos visitará, e vos fará subir desta terra para a terra que jurou a Abraão, a Isaque e a Jacó.

[[v1-50-25]]

^<<v1-50-25,25>>^ E José fez jurar os filhos de Israel, dizendo: Certamente vos visitará Deus, e fareis transportar os meus ossos daqui.

[[v1-50-26]]

^<<v1-50-26,26>>^ E morreu José da idade de cento e dez anos; e o embalsamaram, e o puseram num caixão no Egito.

'''

xref:001-genesis/001-genesis-049.adoc#v1-49-0[&#60; Capítulo Anterior] | <<v1-50-0,Topo>> | xref:002-exodo/002-exodo-001.adoc#v2-1-0[Próximo Capítulo &#62;]