include::./index.adoc[]

[[v1-40-0]]
=== Gênesis, 40
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-40-1]]

^<<v1-40-1,1>>^ E ACONTECEU depois destas cousas que pecaram o copeiro do rei do Egito, e o padeiro, contra o seu senhor, o rei do Egito.

[[v1-40-2]]

^<<v1-40-2,2>>^ E indignou-se Faraó muito contra os seus dois eunucos, contra o copeiro-mor e contra o padeiro-mor.

[[v1-40-3]]

^<<v1-40-3,3>>^ E entregou-os à prisão, na casa do capitão da guarda, na casa do cárcere, no lugar onde José estava preso.

[[v1-40-4]]

^<<v1-40-4,4>>^ E o capitão da guarda pô-los a cargo de José, para que os servisse; e estiveram muitos  dias na prisão.

[[v1-40-5]]

^<<v1-40-5,5>>^ E ambos sonharam um sonho, cada um seu sonho na mesma noite, cada um conforme a interpretação do seu sonho, o copeiro e o padeiro do rei do Egito, que estavam  presos na casa do cárcere.

[[v1-40-6]]

^<<v1-40-6,6>>^ E veio José a eles pela manhã, e olhou para eles, e eis que estavam  turbados.

[[v1-40-7]]

^<<v1-40-7,7>>^ Então perguntou aos eunucos de Faraó, que com ele estavam  no cárcere da casa de seu senhor, dizendo: Por que estão  hoje tristes os vossos semblantes?

[[v1-40-8]]

^<<v1-40-8,8>>^ E eles lhe disseram: Temos sonhado um sonho, e ninguém há  que o interprete. E José disse-lhes: Não são  de Deus as interpretações? Contai-mo, peço-vos.

[[v1-40-9]]

^<<v1-40-9,9>>^ Então contou o copeiro-mor o seu sonho a José, e disse-lhe: Eis que em meu sonho havia  uma vide diante da minha face,

[[v1-40-10]]

^<<v1-40-10,10>>^ E na vide três sarmentos, e estava como brotando; a sua flor saía, os seus cachos amadureciam em uvas;

[[v1-40-11]]

^<<v1-40-11,11>>^ E o copo de Faraó estava  na minha mão, e eu tomava as uvas, e as espremia no copo de Faraó, e dava o copo na mão de Faraó.

[[v1-40-12]]

^<<v1-40-12,12>>^ Então disse-lhe José: Está é  a sua interpretação: Os três sarmentos são  três dias;

[[v1-40-13]]

^<<v1-40-13,13>>^ Dentro ainda de três dias Faraó levantará a tua cabeça, e te restaurará ao teu estado, e darás o copo de Faraó na sua mão, conforme o costume antigo, quando eras seu copeiro.

[[v1-40-14]]

^<<v1-40-14,14>>^ Porém lembra-te de mim, quando te for bem; e rogo-te que uses comigo de compaixão, e que faças menção de mim a Faraó, e faze-me sair desta casa;

[[v1-40-15]]

^<<v1-40-15,15>>^ Porque, de fato, fui roubado da terra dos hebreus; e tão pouco aqui nada tenho feito para que me pusessem nesta cova.

[[v1-40-16]]

^<<v1-40-16,16>>^ Vendo então o padeiro-mor que tinha interpretado bem, disse a José: Eu também sonhava, e eis que três cestos brancos estavam sobre a minha cabeça;

[[v1-40-17]]

^<<v1-40-17,17>>^ E no cesto mais alto havia  de todos os manjares de Faraó, obra de padeiro; e as aves os comiam do cesto de sobre a minha cabeça.

[[v1-40-18]]

^<<v1-40-18,18>>^ Então respondeu José, e disse: Esta é a  sua interpretação: Os três cestos são três dias;

[[v1-40-19]]

^<<v1-40-19,19>>^ Dentro ainda de três dias Faraó levantará a tua cabeça sobre ti, e te pendurará num pau, e as aves comerão a tua carne de sobre ti.

[[v1-40-20]]

^<<v1-40-20,20>>^ E aconteceu ao terceiro dia, o dia do nascimento de Faraó, que fez um banquete a todos os seus servos; e levantou a cabeça do copeiro-mor, e a cabeça do padeiro-mor, no meio dos seus servos.

[[v1-40-21]]

^<<v1-40-21,21>>^ E fez tornar o copeiro-mor ao seu ofício de copeiro, e este deu o copo na mão de Faraó,

[[v1-40-22]]

^<<v1-40-22,22>>^ Mas ao padeiro-mor enforcou, como José havia interpretado.

[[v1-40-23]]

^<<v1-40-23,23>>^ O copeiro-mor, porém, não se lembrou de José, antes se esqueceu dele.

'''

xref:001-genesis/001-genesis-039.adoc#v1-39-0[&#60; Capítulo Anterior] | <<v1-40-0,Topo>> | xref:001-genesis/001-genesis-041.adoc#v1-41-0[Próximo Capítulo &#62;]