include::./index.adoc[]

[[v1-49-0]]
=== Gênesis, 49
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-49-1]]

^<<v1-49-1,1>>^ DEPOIS chamou Jacó a seus filhos, e disse: Ajuntai-vos, e anunciar-vos-ei o que vos há de acontecer nos derradeiros dias;

[[v1-49-2]]

^<<v1-49-2,2>>^ Ajuntai-vos, e ouvi, filhos de Jacó; e ouvi a Israel vosso pai:

[[v1-49-3]]

^<<v1-49-3,3>>^ Rúben, tu és  meu primogênito, minha força, e o princípio de meu vigor, o mais  excelente em alteza, e o mais  excelente em poder.

[[v1-49-4]]

^<<v1-49-4,4>>^ Inconstante como a água, não serás o mais  excelente; porquanto subiste ao leito de teu pai. Então o  contaminaste; subiu à minha cama.

[[v1-49-5]]

^<<v1-49-5,5>>^ Simeão e Levi são  irmãos; as suas espadas são  instrumentos de violência.

[[v1-49-6]]

^<<v1-49-6,6>>^ No seu secreto conselho não entre minha alma, com a sua congregação minha glória não se ajunte; porque no seu furor mataram varões, e na sua teima arrebataram bois.

[[v1-49-7]]

^<<v1-49-7,7>>^ Maldito seja  o seu furor, pois era forte, e a sua ira, pois era dura; eu os dividirei em Jacó, e os espalharei em Israel.

[[v1-49-8]]

^<<v1-49-8,8>>^ Judá, a ti te louvarão os teus irmãos; a tua mão será  sobre o pescoço de seus inimigos; os filhos de teu pai a ti se inclinarão.

[[v1-49-9]]

^<<v1-49-9,9>>^ Judá é  um leãozinho, da presa subiste, filho meu. Encurva-se, e deita-se como um leão, e como um leão velho quem o despertará?

[[v1-49-10]]

^<<v1-49-10,10>>^ O Cetro não se arredará de Judá, nem o legislador dentre seus pés, até que venha Siló; e a ele se congregarão os povos.

[[v1-49-11]]

^<<v1-49-11,11>>^ Ele amarrará o seu jumentinho à vide, e o filho da sua jumenta à cepa mais excelente; ele lavará o seu vestido no vinho, e a sua capa em sangue de uvas.

[[v1-49-12]]

^<<v1-49-12,12>>^ Os olhos serão vermelhos de vinho, e os dentes brancos de leite.

[[v1-49-13]]

^<<v1-49-13,13>>^ Zebulom habitará no porto dos mares, e será como porto dos navios, e o seu termo será  em Sidom.

[[v1-49-14]]

^<<v1-49-14,14>>^ Issacar é  jumento de fortes ossos, deitado entre dois fardos.

[[v1-49-15]]

^<<v1-49-15,15>>^ E viu ele que o descanso era  bom, e que a terra era deliciosa e abaixou o seu ombro para acarretar, e serviu debaixo de tributo.

[[v1-49-16]]

^<<v1-49-16,16>>^ Dã julgará o seu povo, como uma das tribos de Israel.

[[v1-49-17]]

^<<v1-49-17,17>>^ Dã será serpente junto ao caminho, uma víbora junto à vereda, que morde os calcanhares do cavalo, e faz cair o seu cavaleiro por detrás.

[[v1-49-18]]

^<<v1-49-18,18>>^ A tua salvação espero, ó Senhor!

[[v1-49-19]]

^<<v1-49-19,19>>^ Quanto  a Gade, uma tropa o acometerá; mas ele a  acometerá por fim.

[[v1-49-20]]

^<<v1-49-20,20>>^ De Aser, o seu pão será  abundante, e ele dará delícias reais.

[[v1-49-21]]

^<<v1-49-21,21>>^ Naftali é  uma cerva solta; ele dá palavras formosas.

[[v1-49-22]]

^<<v1-49-22,22>>^ José é  um ramo frutífero, ramo frutífero junto à fonte; seus ramos correm sobre o muro.

[[v1-49-23]]

^<<v1-49-23,23>>^ Os frecheiros lhe deram amargura, e o frecharam e aborreceram.

[[v1-49-24]]

^<<v1-49-24,24>>^ O seu arco, porém, susteve-se no forte e os braços de suas mãos foram fortalecidos pelas mãos do Valente de Jacó (donde é  o pastor e a pedra de Israel),

[[v1-49-25]]

^<<v1-49-25,25>>^ Pelo Deus de teu pai, o qual te ajudará, e pelo Todo-poderoso, o qual te abençoará com bênçãos dos céus de cima, com bênçãos do abismo que está debaixo, com bênçãos dos peitos e da madre.

[[v1-49-26]]

^<<v1-49-26,26>>^ As bênçãos de teu pai excederão as bênçãos de meus pais, até à extremidade dos outeiros eternos; elas estarão sobre a cabeça de José, e sobre o alto da cabeça do que foi separado de seus irmãos.

[[v1-49-27]]

^<<v1-49-27,27>>^ Benjamim é  lobo que  despedaça; pela manhã comerá a presa, e à tarde repartirá o despojo.

[[v1-49-28]]

^<<v1-49-28,28>>^ Todas estas são  as doze tribos de Israel; e isto é  o que lhes falou seu pai quando os abençoou; a cada um deles abençoou segundo a sua bênção.

[[v1-49-29]]

^<<v1-49-29,29>>^ Depois ordenou-lhes, e disse-lhes: Eu me congrego ao meu povo; sepultai-me com meus pais, na cova que está  no campo de Efrom, o heteu,

[[v1-49-30]]

^<<v1-49-30,30>>^ Na cova que está  no campo de Macpela, que está em frente de Manre, na terra de Canaã, a qual Abraão comprou com aquele campo de Efrom, o heteu por herança de sepultura.

[[v1-49-31]]

^<<v1-49-31,31>>^ Ali sepultaram a Abraão, e a Sara sua mulher; ali sepultaram a Isaque, e a Rebeca sua mulher; e ali eu sepultei a Leia.

[[v1-49-32]]

^<<v1-49-32,32>>^ O campo, e a cova que está  nele, foi  comprado aos filhos de Hete.

[[v1-49-33]]

^<<v1-49-33,33>>^ Acabando pois Jacó de dar mandamentos a seus filhos, encolheu os seus pés na cama, e expirou, e foi congregado ao seu povo.

'''

xref:001-genesis/001-genesis-048.adoc#v1-48-0[&#60; Capítulo Anterior] | <<v1-49-0,Topo>> | xref:001-genesis/001-genesis-050.adoc#v1-50-0[Próximo Capítulo &#62;]