include::./index.adoc[]

[[v1-42-0]]
=== Gênesis, 42
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v1-42-1]]

^<<v1-42-1,1>>^ VENDO então Jacó que havia mantimento no Egito, disse Jacó a seus filhos: Por que estais olhando uns para os outros?

[[v1-42-2]]

^<<v1-42-2,2>>^ Disse mais: Eis que tenho ouvido que há mantimento no Egito; descei até lá, e comprai-nos trigo, para que vivamos e não morramos.

[[v1-42-3]]

^<<v1-42-3,3>>^ Então desceram os dez irmãos de José, para comprarem trigo do Egito.

[[v1-42-4]]

^<<v1-42-4,4>>^ A Benjamim, porém, irmão de José, não enviou Jacó com os seus irmãos, porque dizia: Para que lhe não suceda porventura algum desastre.

[[v1-42-5]]

^<<v1-42-5,5>>^ Assim vieram os filhos de Israel para comprar, entre os que vinham lá ; porque havia fome na terra de Canaã.

[[v1-42-6]]

^<<v1-42-6,6>>^ José, pois, era o governador daquela terra; ele vendia a todo o povo da terra; e os irmãos de José vieram, e inclinaram-se ante ele com a face na terra.

[[v1-42-7]]

^<<v1-42-7,7>>^ E José, vendo os seus irmãos, conheceu-os; porém mostrou-se estranho para com eles, e falou com eles asperamente, e disse-lhes: Donde vindes? E eles disseram: Da terra de Canaã, para comprarmos mantimento.

[[v1-42-8]]

^<<v1-42-8,8>>^ José, pois, conheceu os seus irmãos; mas eles não o conheceram.

[[v1-42-9]]

^<<v1-42-9,9>>^ Então José lembrou-se dos sonhos, que havia sonhado deles, e disse-lhes: Vós sois espias, e  viestes para ver a nudez da terra.

[[v1-42-10]]

^<<v1-42-10,10>>^ E eles lhe disseram: Não, senhor meu; mas teus servos vieram a comprar mantimento.

[[v1-42-11]]

^<<v1-42-11,11>>^ Todos nós somos filhos de um varão; somos homens de retidão; os teus servos não são espias.

[[v1-42-12]]

^<<v1-42-12,12>>^ E ele lhes disse: Não; antes viestes para ver a nudez da terra.

[[v1-42-13]]

^<<v1-42-13,13>>^ E eles disseram: Nós, teus servos, somos  doze irmãos, filhos de um varão da terra de Canaã; e eis que o mais novo está com nosso pai hoje; mas um já não existe.

[[v1-42-14]]

^<<v1-42-14,14>>^ Então lhes disse José: Isso é  o que vos tenho dito, dizendo que sois  espias;

[[v1-42-15]]

^<<v1-42-15,15>>^ Nisto sereis provados: Pela vida de Faraó, não saireis daqui senão quando vosso irmão mais novo vier aqui.

[[v1-42-16]]

^<<v1-42-16,16>>^ Enviai um dentre vós, que traga vosso irmão, mas vós ficareis presos, e vossas palavras serão provadas, se há  verdade convosco; e se não, pela vida de Faraó, vós sois espias.

[[v1-42-17]]

^<<v1-42-17,17>>^ E pô-los juntos em guarda três dias.

[[v1-42-18]]

^<<v1-42-18,18>>^ E ao terceiro dia disse-lhes José: Fazei isso, e vivereis; porque  eu temo a Deus.

[[v1-42-19]]

^<<v1-42-19,19>>^ Se sois homens de retidão, que fique um de vossos irmãos preso na casa de vossa prisão; e vós ide, levai trigo para a fome de vossa casa.

[[v1-42-20]]

^<<v1-42-20,20>>^ E trazei-me o vosso irmão mais novo, e serão verificadas vossas palavras, e não morrereis. E eles assim fizeram.

[[v1-42-21]]

^<<v1-42-21,21>>^ Então disseram uns aos outros: Na verdade, somos  culpados acerca de nosso irmão, pois vimos a angústia de sua alma, quando nos rogava; nós porém não ouvimos; por isso vem sobre nós esta angústia.

[[v1-42-22]]

^<<v1-42-22,22>>^ E Rúben respondeu-lhes dizendo: Não vo-lo dizia eu, dizendo: Não pequeis contra o moço? Mas não ouvistes; e vedes aqui, o seu sangue também é requerido.

[[v1-42-23]]

^<<v1-42-23,23>>^ E eles não sabiam que José os entendia, porque havia  intérprete entre eles.

[[v1-42-24]]

^<<v1-42-24,24>>^ E retirou-se deles, e chorou. Depois tornou a eles, falou-lhes, e tomou a Simeão dentre eles, e amarrou-o perante os seus olhos.

[[v1-42-25]]

^<<v1-42-25,25>>^ E ordenou José que enchessem os seus sacos de trigo, e que lhes  restituíssem o seu dinheiro a cada um no seu saco, e lhes dessem comida para o caminho; e fizeram-lhes assim.

[[v1-42-26]]

^<<v1-42-26,26>>^ E carregaram o seu trigo sobre os seus jumentos, e partiram dali.

[[v1-42-27]]

^<<v1-42-27,27>>^ E, abrindo um deles  o seu saco, para dar pasto ao seu jumento na venda, viu o seu dinheiro; porque eis que estava na boca do seu saco.

[[v1-42-28]]

^<<v1-42-28,28>>^ E disse a seus irmãos: Devolveram o meu dinheiro, e ei-lo mesmo aqui no meu saco. Então lhes desfaleceu o coração, e pasmavam, dizendo um ao outro: Que é isto que Deus nos tem feito?

[[v1-42-29]]

^<<v1-42-29,29>>^ E vieram para Jacó, seu pai, na terra de Canaã; e contaram-lhe tudo o que lhes aconteceu, dizendo:

[[v1-42-30]]

^<<v1-42-30,30>>^ O varão, o senhor da terra, falou conosco asperamente, e tratou-nos como espias da terra;

[[v1-42-31]]

^<<v1-42-31,31>>^ Mas dissemos-lhe: Somos homens  de retidão; não somos espias;

[[v1-42-32]]

^<<v1-42-32,32>>^ Somos  doze irmãos, filhos de nosso pai; um não é mais , e o mais novo está  hoje com nosso pai na terra de Canaã.

[[v1-42-33]]

^<<v1-42-33,33>>^ E aquele varão, o senhor da terra, nos disse: Nisto conhecerei que vós sois homens  de retidão: Deixai comigo um de vossos irmãos, e tomai para a fome de vossas casas, e parti,

[[v1-42-34]]

^<<v1-42-34,34>>^ E trazei-me vosso irmão mais novo; assim saberei que não sois espias, mas homens  de retidão; então  vos darei o vosso irmão e negociareis na terra.

[[v1-42-35]]

^<<v1-42-35,35>>^ E aconteceu que, despejando eles os seus sacos, eis que cada um tinha a trouxinha com seu dinheiro no seu saco; e viram as trouxinhas com seu dinheiro, eles e seu pai, e temeram.

[[v1-42-36]]

^<<v1-42-36,36>>^ Então Jacó, seu pai, disse-lhes: Tendes-me desfilhado; José já não existe, e Simeão não está  aqui; agora levareis a Benjamim. Todas estas cousas vieram sobre mim.

[[v1-42-37]]

^<<v1-42-37,37>>^ Mas Rúben falou a seu pai, dizendo: Mata os meus dois filhos, se to não tornar a trazer; dá-mo em minha mão, e to tornarei a trazer.

[[v1-42-38]]

^<<v1-42-38,38>>^ Ele porém disse: Não descerá meu filho convosco; porquanto o seu irmão é morto, e só ele ficou. Se lhe sucede algum desastre no caminho por onde fordes, fareis descer minhas cãs com tristeza à sepultura.

'''

xref:001-genesis/001-genesis-041.adoc#v1-41-0[&#60; Capítulo Anterior] | <<v1-42-0,Topo>> | xref:001-genesis/001-genesis-043.adoc#v1-43-0[Próximo Capítulo &#62;]