include::./index.adoc[]

[[v51-4-0]]
=== Colossenses, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v51-4-1]]

^<<v51-4-1,1>>^ VÓS, senhores, fazei o que for de justiça e equidade a vossos  servos, sabendo que também tendes um Senhor nos céus.

[[v51-4-2]]

^<<v51-4-2,2>>^ Perseverai em oração, velando nela com ação de graças;

[[v51-4-3]]

^<<v51-4-3,3>>^ Orando também juntamente por nós, para que Deus nos abra a porta da palavra, a fim de falarmos do mistério de Cristo, pelo qual estou também preso;

[[v51-4-4]]

^<<v51-4-4,4>>^ Para que o manifeste, como me convém falar.

[[v51-4-5]]

^<<v51-4-5,5>>^ Andai com sabedoria para com os que estão de fora, remindo o tempo.

[[v51-4-6]]

^<<v51-4-6,6>>^ A vossa palavra seja sempre agradável, temperada com sal, para que saibais como vos convém responder a cada um.

[[v51-4-7]]

^<<v51-4-7,7>>^ Tíquico, irmão amado e fiel ministro, e conservo no Senhor, vos fará saber o meu estado;

[[v51-4-8]]

^<<v51-4-8,8>>^ O qual vos enviei para o mesmo fim, para que saiba do vosso estado e console os vossos corações;

[[v51-4-9]]

^<<v51-4-9,9>>^ Juntamente  com Onésimo, amado e fiel irmão, que é dos vossos; eles vos farão saber tudo o que por aqui se passa.

[[v51-4-10]]

^<<v51-4-10,10>>^ Aristarco, que está preso comigo, vos saúda, e Marcos, o sobrinho de Barnabé, acerca do qual já  recebestes mandamentos; se ele for ter convosco, recebei-o;

[[v51-4-11]]

^<<v51-4-11,11>>^ E Jesus, chamado Justo: os quais são da circuncisão; são estes unicamente os meus  cooperadores no reino de Deus; e para mim têm sido consolação.

[[v51-4-12]]

^<<v51-4-12,12>>^ Saúda-vos Epafras, que é dos vossos, servo de Cristo, combatendo sempre por vós em orações, para que vos conserveis firmes, perfeitos e consumados em toda a vontade de Deus.

[[v51-4-13]]

^<<v51-4-13,13>>^ Pois eu lhe dou testemunho de que tem grande zelo por vós, e pelos que estão  em Laodiceia, e pelos que estão  em Hierápolis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Saúda-vos Lucas, o médico amado, e Demas.

[[v51-4-15]]

^<<v51-4-15,15>>^ Saudai aos irmãos que estão em Laodiceia, e a Ninfa e à igreja que está em sua casa.

[[v51-4-16]]

^<<v51-4-16,16>>^ E, quando esta  epístola tiver sido lida entre vós, fazei que também o seja na igreja dos laodicenses, e a que veio  de Laodiceia lede-a vós também.

[[v51-4-17]]

^<<v51-4-17,17>>^ E dizei a Arquipo: Atenta para o ministério que recebeste no Senhor: para que o cumpras.

[[v51-4-18]]

^<<v51-4-18,18>>^ Saudação de minha mão, de Paulo. Lembrai-vos das minhas prisões. A graça seja  convosco. Amém.

'''

xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[Próximo Capítulo &#62;]