include::./index.adoc[]

[[v35-1-0]]
=== Habacuque, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v35-1-1]]

^<<v35-1-1,1>>^ O PESO que viu o profeta Habacuque.

[[v35-1-2]]

^<<v35-1-2,2>>^ Até quando, Senhor, clamarei eu, e tu não me escutarás? gritarei: Violência! e não salvarás?

[[v35-1-3]]

^<<v35-1-3,3>>^ Por que razão me fazes ver a iniquidade, e ver a vexação? porque a destruição e a violência estão diante de mim; há também quem suscite a contenda e o litígio.

[[v35-1-4]]

^<<v35-1-4,4>>^ Por esta causa a lei se afrouxa, e a sentença nunca sai; porque o ímpio cerca o justo, e sai o juízo pervertido.

[[v35-1-5]]

^<<v35-1-5,5>>^ Vede entre as nações, e olhai, e maravilhai-vos, e admirai-vos: porque realizo em vossos dias uma obra, que vós não crereis, quando vos for contada.

[[v35-1-6]]

^<<v35-1-6,6>>^ Porque eis que suscito os caldeus, nação amarga e apressada, que marcha sobre a largura da terra, para possuir moradas não suas.

[[v35-1-7]]

^<<v35-1-7,7>>^ Horrível e terrível é; dela mesma sairá o seu juízo e a sua grandeza.

[[v35-1-8]]

^<<v35-1-8,8>>^ Os seus cavalos são mais ligeiros do que os leopardos, e mais perspicazes do que os lobos à tarde; os seus cavaleiros espalham-se por toda a parte; sim, os seus cavaleiros virão de longe, voarão como águias que se apressam à comida.

[[v35-1-9]]

^<<v35-1-9,9>>^ Eles todos virão com violência: os seus rostos buscarão o oriente, e eles congregarão os cativos como areia.

[[v35-1-10]]

^<<v35-1-10,10>>^ E escarnecerão dos reis, e dos príncipes farão zombarias: eles se rirão de todas as fortalezas, porque, amontoando terra, as tomarão.

[[v35-1-11]]

^<<v35-1-11,11>>^ Então passará como  um vento e pisará, e se fará culpada, atribuindo  este poder ao seu deus.

[[v35-1-12]]

^<<v35-1-12,12>>^ Não és  tu desde sempre, ó Senhor meu Deus, meu Santo? nós não morreremos: ó Senhor, para juízo o puseste, e tu, ó Rocha, o fundaste para castigar.

[[v35-1-13]]

^<<v35-1-13,13>>^ Tu és tão puro de olhos, que não podes ver o mal, e a vexação não podes contemplar: por que pois olhas para os que procedem aleivosamente, e te calas quando o ímpio devora aquele que é  mais justo do que ele?

[[v35-1-14]]

^<<v35-1-14,14>>^ E farias os homens como os peixes do mar, como os répteis, que não têm quem os governe?

[[v35-1-15]]

^<<v35-1-15,15>>^ Ele a todos levanta com o anzol, apanha-os com a sua rede, e os ajunta na sua rede varredoura: por isso ele se alegra e se regozija.

[[v35-1-16]]

^<<v35-1-16,16>>^ Por isso sacrifica à sua rede, e queima incenso à sua draga; porque com elas se engordou a sua porção, e se engrossou a sua comida.

[[v35-1-17]]

^<<v35-1-17,17>>^ Porventura por isso esvaziará a sua rede, e não deixaria de matar os povos continuamente?

'''

xref:034-naum/034-naum-003.adoc#v34-3-0[&#60; Capítulo Anterior] | <<v35-1-0,Topo>> | xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[Próximo Capítulo &#62;]