include::./index.adoc[]

[[v35-3-0]]
=== Habacuque, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v35-3-1]]

^<<v35-3-1,1>>^ ORAÇÃO do profeta Habacuque sobre Sigionote.

[[v35-3-2]]

^<<v35-3-2,2>>^ Ouvi, Senhor, a tua palavra, e  temi: aviva, ó Senhor, a tua obra no meio dos anos, no meio dos anos a notifica: na ira lembra-te da misericórdia.

[[v35-3-3]]

^<<v35-3-3,3>>^ Deus veio de Temã, e o Santo do monte de Parã. (Selá.) A sua glória cobriu os céus, e a terra encheu-se do seu louvor.

[[v35-3-4]]

^<<v35-3-4,4>>^ E o seu resplendor era como a luz, raios brilhantes saíam  da sua mão, e ali estava o esconderijo da sua força.

[[v35-3-5]]

^<<v35-3-5,5>>^ Adiante dele ia a peste, e raios de fogo sob os seus pés.

[[v35-3-6]]

^<<v35-3-6,6>>^ Parou, e mediu a terra: olhou, e separou as nações: e os montes perpétuos foram esmiuçados, os outeiros eternos se encurvaram: o andar eterno é  seu.

[[v35-3-7]]

^<<v35-3-7,7>>^ Vi as tendas de Cusã em aflição; as cortinas da terra de Midiã tremiam.

[[v35-3-8]]

^<<v35-3-8,8>>^ Acaso é contra os rios, Senhor, que estás irado? contra os ribeiros foi a tua ira ou contra o mar foi o teu furor, para que andasses montado sobre os teus cavalos, sobre os teus carros de salvação?

[[v35-3-9]]

^<<v35-3-9,9>>^ Descoberto se fez o teu arco: os juramentos feitos às tribos foram uma palavra segura. (Selá.) Tu fendeste a terra com rios.

[[v35-3-10]]

^<<v35-3-10,10>>^ Os montes te viram, e tremeram: a inundação das águas passou; deu o abismo a sua voz, levantou as suas mãos ao  alto.

[[v35-3-11]]

^<<v35-3-11,11>>^ O sol e a lua pararam nas suas moradas; andaram à luz das tuas frechas, ao resplendor do relâmpago da tua lança.

[[v35-3-12]]

^<<v35-3-12,12>>^ Com indignação marchaste pela terra, com ira trilhaste as nações.

[[v35-3-13]]

^<<v35-3-13,13>>^ Tu saíste para salvamento do teu povo, para salvamento do teu ungido; tu feriste a cabeça da casa do ímpio, descobrindo os fundamentos até ao pescoço. (Selá.)

[[v35-3-14]]

^<<v35-3-14,14>>^ Tu abriste com os seus próprios cajados a cabeça dos seus guerreiros; eles me acometeram tempestuosos para me espalharem: alegravam-se, como se estivessem  para devorar o pobre em segredo.

[[v35-3-15]]

^<<v35-3-15,15>>^ Tu com  os teus cavalos marchaste pelo mar, pela massa de grandes águas.

[[v35-3-16]]

^<<v35-3-16,16>>^ Ouvindo-o eu, o meu ventre se comoveu, à sua voz tremeram os meus lábios; entrou a podridão nos meus ossos, e estremeci dentro de mim; descanse eu no dia da angústia, quando ele vier contra o povo que  nos destruirá.

[[v35-3-17]]

^<<v35-3-17,17>>^ Porquanto, ainda que a figueira não floresça, nem haja fruto na vide; o produto da oliveira minta, e os campos não produzam mantimento; as ovelhas da malhada sejam arrebatadas, e nos currais não haja vacas:

[[v35-3-18]]

^<<v35-3-18,18>>^ Todavia eu me alegrarei no Senhor: exultarei no Deus da minha salvação.

[[v35-3-19]]

^<<v35-3-19,19>>^ Jeová , o Senhor é  minha força, e fará os meus pés como os das cervas, e me fará andar sobre as minhas alturas. (Para o cantor-mor sobre os meus instrumentos de música.)

'''

xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[&#60; Capítulo Anterior] | <<v35-3-0,Topo>> | xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[Próximo Capítulo &#62;]