include::./index.adoc[]

[[v33-7-0]]
=== Miquéias, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v33-7-1]]

^<<v33-7-1,1>>^ AI de mim! porque estou feito como quando são colhidas as frutas do verão, como os rabiscos da vindima; não há  cacho de uvas para comer, nem figos temporãos que a minha alma desejou.

[[v33-7-2]]

^<<v33-7-2,2>>^ Pereceu o benigno da terra, e não há entre os homens um que  seja reto: todos armam ciladas para sangue; caça cada um a seu irmão com  uma rede.

[[v33-7-3]]

^<<v33-7-3,3>>^ As suas mãos fazem diligentemente o mal; o príncipe inquire, e o juiz se apressa à recompensa, e o grande fala da corrupção da sua alma, e assim todos eles são perturbadores.

[[v33-7-4]]

^<<v33-7-4,4>>^ O melhor deles é  como um  espinho; o mais reto é  pior do que o espinhal: veio o dia dos teus vigias, veio a tua visitação; agora será a sua confusão.

[[v33-7-5]]

^<<v33-7-5,5>>^ Não creiais no amigo, nem confieis no vosso guia; daquela que repousa no teu seio guarda as portas da tua boca.

[[v33-7-6]]

^<<v33-7-6,6>>^ Porque o filho despreza o pai, a filha se levanta contra sua mãe, a nora contra sua sogra, os inimigos do homem são os da sua própria casa.

[[v33-7-7]]

^<<v33-7-7,7>>^ Eu, porém, esperarei no Senhor; esperei no Deus da minha salvação: o meu Deus me ouvirá.

[[v33-7-8]]

^<<v33-7-8,8>>^ Ó inimiga minha, não te alegres a meu respeito; ainda que eu tenha caído, levantar-me-ei: se morar nas trevas, o Senhor será a minha luz.

[[v33-7-9]]

^<<v33-7-9,9>>^ Sofrerei a ira do Senhor, porque pequei contra ele, até que julgue a minha causa e execute o meu direito: ele me trará a luz, e eu verei a sua justiça.

[[v33-7-10]]

^<<v33-7-10,10>>^ E a minha inimiga verá isso, e cobri-la-á a confusão; e aquela que me diz: Onde está o teu Deus? os meus olhos a verão, sendo pisada como a lama das ruas.

[[v33-7-11]]

^<<v33-7-11,11>>^ No dia em que  reedificar os teus muros, nesse dia longe estará ainda o estatuto.

[[v33-7-12]]

^<<v33-7-12,12>>^ Naquele dia virão a ti, desde a Assíria até  às cidades fortes, e das fortalezas até ao rio, e do mar até  ao mar e da  montanha até à montanha.

[[v33-7-13]]

^<<v33-7-13,13>>^ Mas esta terra será posta em desolação, por causa dos seus moradores, por causa do fruto das suas obras.

[[v33-7-14]]

^<<v33-7-14,14>>^ Apascenta o teu povo com a tua vara, o rebanho da tua herança, que mora só no bosque, no meio da terra fértil; apascentem-se em  Basã e Gileade, como nos dias da antiguidade.

[[v33-7-15]]

^<<v33-7-15,15>>^ Eu lhes mostrarei maravilhas, como nos dias da tua saída da terra do Egito.

[[v33-7-16]]

^<<v33-7-16,16>>^ As nações o verão, e envergonhar-se-ão, por causa de todo o seu poder: porão a mão sobre a boca, e  os seus ouvidos ficarão surdos.

[[v33-7-17]]

^<<v33-7-17,17>>^ Lamberão o pó como serpentes; como uns  répteis da terra, tremendo, sairão dos seus encerramentos; com pavor virão ao Senhor nosso Deus, e terão medo de ti.

[[v33-7-18]]

^<<v33-7-18,18>>^ Quem, ó Deus, é semelhante a ti, que perdoas a iniquidade, e que te esqueces da rebelião do restante da tua herança? O Senhor não retém a sua ira para sempre, porque tem prazer na benignidade.

[[v33-7-19]]

^<<v33-7-19,19>>^ Tornará a apiedar-se de nós: subjugará as nossas iniquidades, e lançará todos os nossos pecados nas profundezas do mar.

[[v33-7-20]]

^<<v33-7-20,20>>^ Darás a Jacó a fidelidade, e a Abraão a benignidade, que juraste a nossos pais desde os dias antigos.

'''

xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[&#60; Capítulo Anterior] | <<v33-7-0,Topo>> | xref:034-naum/034-naum-001.adoc#v34-1-0[Próximo Capítulo &#62;]