include::./index.adoc[]

[[v33-5-0]]
=== Miquéias, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v33-5-1]]

^<<v33-5-1,1>>^ AGORA ajunta-te em esquadrões, ó filha de esquadrões; pôr-se-á cerco contra nós: ferirão com a vara no queixo ao juiz de Israel.

[[v33-5-2]]

^<<v33-5-2,2>>^ E tu, Belém Efrata, posto que pequena entre milhares de Judá, de ti me sairá o que será Senhor em Israel, e cujas saídas são desde os tempos antigos, desde os dias da eternidade.

[[v33-5-3]]

^<<v33-5-3,3>>^ Portanto os entregará até ao tempo em que a que está de parto tiver dado à luz: então o resto de seus irmãos voltará com os filhos de Israel.

[[v33-5-4]]

^<<v33-5-4,4>>^ E ele permanecerá, e apascentará o povo  na força do Senhor, na excelência do nome do Senhor seu Deus: e eles permanecerão, porque agora será ele engrandecido até aos fins da terra.

[[v33-5-5]]

^<<v33-5-5,5>>^ E este será a nossa  paz: quando a Assíria vier à nossa terra, e quando passar sobre os nossos palácios, levantaremos contra ela sete pastores e oito príncipes dentre os homens.

[[v33-5-6]]

^<<v33-5-6,6>>^ Esses consumirão a terra da Assíria à espada, e a terra de Ninrode nas suas entradas. Assim nos  livrará da Assíria, quando vier à nossa terra, e quando calcar os nossos termos.

[[v33-5-7]]

^<<v33-5-7,7>>^ E estará o resto de Jacó no meio de muitos povos, como orvalho do Senhor, como chuvisco sobre a erva, que não espera pelo homem, nem aguarda filhos de homens.

[[v33-5-8]]

^<<v33-5-8,8>>^ E o resto de Jacó estará entre as nações, no meio de muitos povos, como um leão entre os animais do bosque, como um leãozinho entre os rebanhos de ovelhas, o qual quando passar as pisará e despedaçará, sem que haja quem as  livre.

[[v33-5-9]]

^<<v33-5-9,9>>^ A tua mão se exaltará sobre os teus adversários; e todos os teus inimigos serão exterminados.

[[v33-5-10]]

^<<v33-5-10,10>>^ E sucederá naquele dia, diz o Senhor, que eu exterminarei no meio de ti os teus cavalos, e destruirei os teus carros;

[[v33-5-11]]

^<<v33-5-11,11>>^ E destruirei as cidades da tua terra, e derribarei todas as tuas fortalezas;

[[v33-5-12]]

^<<v33-5-12,12>>^ E tirarei as feitiçarias da tua mão: e não terás agoureiros;

[[v33-5-13]]

^<<v33-5-13,13>>^ E arrancarei do meio de ti as tuas imagens de escultura e as tuas estátuas; e tu não te inclinarás mais diante da obra das tuas mãos.

[[v33-5-14]]

^<<v33-5-14,14>>^ E arrancarei os teus bosques do meio de ti; e destruirei as tuas cidades.

[[v33-5-15]]

^<<v33-5-15,15>>^ E com ira e com furor exercerei vingança sobre as nações que não ouvem.

'''

xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[&#60; Capítulo Anterior] | <<v33-5-0,Topo>> | xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[Próximo Capítulo &#62;]