include::./index.adoc[]

[[v33-4-0]]
=== Miquéias, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v33-4-1]]

^<<v33-4-1,1>>^ MAS nos últimos dias acontecerá que o monte da casa do Senhor será estabelecido no cume dos montes, e se elevará sobre os outeiros, e concorrerão a ele os povos.

[[v33-4-2]]

^<<v33-4-2,2>>^ E irão muitas nações, e dirão: Vinde, e subamos ao monte do Senhor, e à casa do Deus de Jacó, para que nos ensine os seus caminhos, e nós andemos pelas suas veredas; porque de Sião sairá a lei, e a palavra do Senhor de Jerusalém.

[[v33-4-3]]

^<<v33-4-3,3>>^ E julgará entre muitos povos, e castigará poderosas nações até mui longe, e converterão as suas espadas em enxadas, e as suas lanças em foices: uma nação não levantará a espada contra outra nação, nem aprenderão mais a guerra.

[[v33-4-4]]

^<<v33-4-4,4>>^ Mas assentar-se-á cada um debaixo da sua videira, e debaixo da sua figueira, e não haverá quem os espante, porque a boca do Senhor dos Exércitos o disse.

[[v33-4-5]]

^<<v33-4-5,5>>^ Porque todos os povos andarão, cada um em nome do seu deus; mas nós andaremos no nome do Senhor nosso Deus, eternamente e para sempre.

[[v33-4-6]]

^<<v33-4-6,6>>^ Naquele dia, diz o Senhor, congregarei a que coxeava, e recolherei a que eu tinha expulsado, e a que eu tinha maltratado.

[[v33-4-7]]

^<<v33-4-7,7>>^ E da que coxeava farei a parte restante, e da que tinha sido arrojada para longe uma nação poderosa; e o Senhor reinará sobre eles no monte de Sião, desde agora e para sempre.

[[v33-4-8]]

^<<v33-4-8,8>>^ E a ti, ó torre do rebanho, monte da filha de Sião, a ti virá; sim, a ti virá o primeiro domínio, o reino da filha de Jerusalém.

[[v33-4-9]]

^<<v33-4-9,9>>^ E agora, porque farás tão grande pranto? não há  em ti rei? pereceu o teu conselheiro? apoderou-se de ti dor, como da que está de parto?

[[v33-4-10]]

^<<v33-4-10,10>>^ Sofre dores, e trabalhos, ó filha de Sião, como a que está de parto, porque agora sairás da cidade, e morarás no campo, e virás até Babilônia: ali, porém , serás livrada; ali te remirá o Senhor da mão de teus inimigos.

[[v33-4-11]]

^<<v33-4-11,11>>^ Agora se congregaram muitas nações contra ti, que dizem: Seja profanada, e os nossos olhos verão seus desejos sobre Sião.

[[v33-4-12]]

^<<v33-4-12,12>>^ Mas não sabem os pensamentos do Senhor, nem entendem o seu conselho: porque as ajuntou como gavelas numa eira.

[[v33-4-13]]

^<<v33-4-13,13>>^ Levanta-te, e trilha, ó filha de Sião; porque eu farei de ferro a tua ponta, e de cobre as tuas unhas, e esmiuçarás a muitos povos, e o seu ganho será consagrado ao Senhor, e a sua fazenda ao Senhor de toda a terra.

'''

xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[&#60; Capítulo Anterior] | <<v33-4-0,Topo>> | xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[Próximo Capítulo &#62;]