include::./index.adoc[]

[[v33-3-0]]
=== Miquéias, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v33-3-1]]

^<<v33-3-1,1>>^ MAIS disse eu: Ouvi agora vós, chefes de Jacó, e vós, príncipes da casa de Israel: não é  a vós que pertence  saber o direito?

[[v33-3-2]]

^<<v33-3-2,2>>^ A vós que aborreceis o bem, e amais o mal, que arrancais a pele de cima deles, e a sua carne de cima dos seus ossos,

[[v33-3-3]]

^<<v33-3-3,3>>^ E que comeis a carne do meu povo, e lhes arrancais a pele, e lhes esmiuçais os ossos, e os repartis como para a panela e como carne do meio do caldeirão.

[[v33-3-4]]

^<<v33-3-4,4>>^ Então clamarão ao Senhor, mas  não os ouvirá, antes esconderá deles a sua face naquele tempo, visto que eles fizeram mal nas suas obras.

[[v33-3-5]]

^<<v33-3-5,5>>^ Assim diz o Senhor contra os profetas que fazem errar o meu povo, que mordem com os seus dentes, e clamam: Paz! mas contra aquele que nada lhes mete na boca preparam guerra.

[[v33-3-6]]

^<<v33-3-6,6>>^ Portanto, se vos fará noite, para que não haja profecia, e haverá trevas, para que não haja adivinhação, e se porá o sol sobre estes profetas, e o dia sobre eles se enegrecerá.

[[v33-3-7]]

^<<v33-3-7,7>>^ E os videntes se envergonharão, e os adivinhadores se confundirão, sim, todos eles cobrirão os seus lábios, porque não haverá resposta de Deus.

[[v33-3-8]]

^<<v33-3-8,8>>^ Mas decerto eu sou cheio da força do Espírito do Senhor, e cheio  de juízo e de ânimo, para anunciar a Jacó a sua transgressão e a Israel o seu pecado.

[[v33-3-9]]

^<<v33-3-9,9>>^ Ouvi agora isto, vós, chefes da casa de Jacó, e vós, maiorais da casa de Israel, que abominais o juízo e perverteis tudo o que é direito.

[[v33-3-10]]

^<<v33-3-10,10>>^ Edificando a Sião com sangue, e a Jerusalém com injustiça.

[[v33-3-11]]

^<<v33-3-11,11>>^ Os seus chefes dão as sentenças por presentes, e os seus sacerdotes ensinam por interesse, e os seus profetas adivinham por dinheiro; e ainda se encostam ao Senhor, dizendo: Não está o Senhor no meio de nós? nenhum mal nos sobrevirá.

[[v33-3-12]]

^<<v33-3-12,12>>^ Portanto, por causa de vós, Sião será lavrado como  um campo, e Jerusalém se tornará em montões de pedras, e o monte desta casa em lugares altos dum bosque.

'''

xref:033-miqueias/033-miqueias-002.adoc#v33-2-0[&#60; Capítulo Anterior] | <<v33-3-0,Topo>> | xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[Próximo Capítulo &#62;]