include::./index.adoc[]

[[v33-1-0]]
=== Miquéias, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v33-1-1]]

^<<v33-1-1,1>>^ PALAVRA do Senhor, que veio a Miqueias, morastita, nos dias de Jotão, Acaz e  Ezequias, reis de Judá: a qual ele viu sobre Samaria e Jerusalém.

[[v33-1-2]]

^<<v33-1-2,2>>^ Ouvi, todos os povos, presta atenção, ó terra, em tua plenitude, e seja o Senhor Jeová  testemunha contra vós, o Senhor, desde o templo da sua santidade.

[[v33-1-3]]

^<<v33-1-3,3>>^ Porque eis que o Senhor sai do seu lugar, e descerá, e andará sobre as alturas da terra.

[[v33-1-4]]

^<<v33-1-4,4>>^ E os montes debaixo dele se derreterão, e os vales se fenderão, como a cera diante do fogo, como as águas que se precipitam num abismo.

[[v33-1-5]]

^<<v33-1-5,5>>^ Tudo isto por causa da prevaricação de Jacó, e dos pecados da casa de Israel: qual é a transgressão de Jacó? não é  Samaria? e quais os altos de Judá? não é  Jerusalém?

[[v33-1-6]]

^<<v33-1-6,6>>^ Por isso farei de Samaria um montão de pedras do campo, uma terra de plantar vinhas, e farei rebolar as suas pedras no vale, e descobrirei os seus fundamentos.

[[v33-1-7]]

^<<v33-1-7,7>>^ E todas as suas imagens de escultura serão despedaçadas, e todos os seus salários serão queimados pelo fogo, e de todos os seus ídolos eu farei uma assolação, porque do preço de sua prostituição os ajuntou, e em recompensa de prostituta se volverão.

[[v33-1-8]]

^<<v33-1-8,8>>^ Por isso lamentarei, e uivarei, andarei despojado e nu; farei lamentação como de dragões, e pranto como de avestruzes.

[[v33-1-9]]

^<<v33-1-9,9>>^ Porque a sua chaga é  incurável, porque chegou até Judá; estendeu-se até à porta do meu povo, até Jerusalém.

[[v33-1-10]]

^<<v33-1-10,10>>^ Não o anuncieis em Gate, nem choreis muito: revolve-te no pó, na casa de Afra.

[[v33-1-11]]

^<<v33-1-11,11>>^ Passa, ó moradora de Safir, com nudez vergonhosa; a moradora de Zaanã não saiu; o pranto de Bete-Ezel receberá de vós a sua morada.

[[v33-1-12]]

^<<v33-1-12,12>>^ Porque a moradora de Marote teve dor pelo bem; porque desceu do Senhor o mal até à porta de Jerusalém.

[[v33-1-13]]

^<<v33-1-13,13>>^ Ata os animais ligeiros ao carro, ó moradora de Laquis (esta foi o princípio do pecado para a filha de Sião), porque em ti se acharam as transgressões de Israel.

[[v33-1-14]]

^<<v33-1-14,14>>^ Por isso darás presentes a Moresete-Gate: as casas de Aczibe serão  uma mentira para os reis de Israel.

[[v33-1-15]]

^<<v33-1-15,15>>^ Ainda te trarei um herdeiro, ó moradora de Maresa: chegará até Adulão a glória de Israel.

[[v33-1-16]]

^<<v33-1-16,16>>^ Faze-te calva, e tosquia-te, por causa dos filhos das tuas delícias: alarga a tua calva como a águia, porque de ti foram levados para o cativeiro.

'''

xref:032-jonas/032-jonas-004.adoc#v32-4-0[&#60; Capítulo Anterior] | <<v33-1-0,Topo>> | xref:033-miqueias/033-miqueias-002.adoc#v33-2-0[Próximo Capítulo &#62;]