include::./index.adoc[]

[[v49-5-0]]
=== Efésios, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v49-5-1]]

^<<v49-5-1,1>>^ SEDE pois imitadores de Deus, como filhos amados;

[[v49-5-2]]

^<<v49-5-2,2>>^ E andai em amor, como também Cristo vos amou, e se entregou a si mesmo por nós, em oferta e sacrifício a Deus, em cheiro suave.

[[v49-5-3]]

^<<v49-5-3,3>>^ Mas a prostituição, e toda a impureza ou avareza, nem ainda se nomeie entre vós, como convém a santos;

[[v49-5-4]]

^<<v49-5-4,4>>^ Nem torpezas, nem parvoíces, nem chocarrices, que não convém; mas antes ações de graças.

[[v49-5-5]]

^<<v49-5-5,5>>^ Porque bem sabeis isto: que nenhum fornicário, ou impuro, ou avarento, o qual é idólatra, tem herança no reino de Cristo e de Deus.

[[v49-5-6]]

^<<v49-5-6,6>>^ Ninguém vos engane com palavras vãs; porque por estas coisas  vem a ira de Deus sobre os filhos da desobediência.

[[v49-5-7]]

^<<v49-5-7,7>>^ Portanto não sejais seus companheiros.

[[v49-5-8]]

^<<v49-5-8,8>>^ Porque noutro tempo éreis trevas, mas agora sois luz no Senhor: andai como filhos da luz.

[[v49-5-9]]

^<<v49-5-9,9>>^ (Porque o fruto do Espírito está em toda a bondade, e justiça e verdade);

[[v49-5-10]]

^<<v49-5-10,10>>^ Aprovando o que é agradável ao Senhor.

[[v49-5-11]]

^<<v49-5-11,11>>^ E não comuniqueis com as obras infrutuosas das trevas, mas antes condenai-as.

[[v49-5-12]]

^<<v49-5-12,12>>^ Porque o que eles fazem em oculto até dizê-lo é torpe.

[[v49-5-13]]

^<<v49-5-13,13>>^ Mas todas estas coisas  se manifestam, sendo condenadas, pela luz, porque a luz tudo manifesta.

[[v49-5-14]]

^<<v49-5-14,14>>^ Pelo que diz: Desperta, tu que dormes, e levanta-te dentre os mortos, e Cristo te esclarecerá.

[[v49-5-15]]

^<<v49-5-15,15>>^ Portanto, vede prudentemente como andais, não como néscios, mas como sábios,

[[v49-5-16]]

^<<v49-5-16,16>>^ Remindo o tempo; porquanto os dias são maus.

[[v49-5-17]]

^<<v49-5-17,17>>^ Pelo que não sejais insensatos, mas entendei qual seja a vontade do Senhor.

[[v49-5-18]]

^<<v49-5-18,18>>^ E não vos embriagueis com vinho, em que há contenda, mas enchei-vos do Espírito;

[[v49-5-19]]

^<<v49-5-19,19>>^ Falando entre vós em salmos, e hinos, e cânticos espirituais: cantando e salmodiando ao Senhor no vosso coração;

[[v49-5-20]]

^<<v49-5-20,20>>^ Dando sempre graças por tudo a nosso Deus e Pai, em nome de nosso Senhor Jesus Cristo:

[[v49-5-21]]

^<<v49-5-21,21>>^ Sujeitando-vos uns aos outros no temor de Deus.

[[v49-5-22]]

^<<v49-5-22,22>>^ Vós, mulheres, sujeitai-vos a vossos maridos, como ao Senhor;

[[v49-5-23]]

^<<v49-5-23,23>>^ Porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja: sendo ele próprio o salvador do corpo.

[[v49-5-24]]

^<<v49-5-24,24>>^ De sorte que, assim como a igreja está sujeita a Cristo, assim também as mulheres sejam em tudo sujeitas a seus maridos.

[[v49-5-25]]

^<<v49-5-25,25>>^ Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja, e a si mesmo se entregou por ela,

[[v49-5-26]]

^<<v49-5-26,26>>^ Para a santificar, purificando-a com a lavagem da água, pela palavra,

[[v49-5-27]]

^<<v49-5-27,27>>^ Para a apresentar a si mesmo igreja gloriosa, sem mácula, nem ruga, nem coisa  semelhante, mas santa e irrepreensível.

[[v49-5-28]]

^<<v49-5-28,28>>^ Assim devem os maridos amar a suas próprias mulheres, como a seus próprios corpos. Quem ama a sua mulher, ama-se a si mesmo.

[[v49-5-29]]

^<<v49-5-29,29>>^ Porque nunca ninguém aborreceu a sua própria carne; antes a alimenta e sustenta, como também o Senhor à igreja;

[[v49-5-30]]

^<<v49-5-30,30>>^ Porque somos membros do seu corpo.

[[v49-5-31]]

^<<v49-5-31,31>>^ Por isso deixará o homem seu pai e sua  mãe, e se unirá a sua mulher; e serão dois numa carne.

[[v49-5-32]]

^<<v49-5-32,32>>^ Grande é este mistério: digo-o, porém, a respeito de Cristo e da igreja.

[[v49-5-33]]

^<<v49-5-33,33>>^ Assim também vós cada um em particular ame a sua própria mulher como a si mesmo, e a mulher reverencie o marido.

'''

xref:049-efesios/049-efesios-004.adoc#v49-4-0[&#60; Capítulo Anterior] | <<v49-5-0,Topo>> | xref:049-efesios/049-efesios-006.adoc#v49-6-0[Próximo Capítulo &#62;]