include::./index.adoc[]

[[v49-3-0]]
=== Efésios, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v49-3-1]]

^<<v49-3-1,1>>^ POR esta causa eu, Paulo, sou  o prisioneiro de Jesus Cristo por vós, os gentios;

[[v49-3-2]]

^<<v49-3-2,2>>^ Se é que tendes ouvido a dispensação da graça de Deus, que para convosco me foi dada;

[[v49-3-3]]

^<<v49-3-3,3>>^ Como me foi este mistério manifestado pela revelação como acima em pouco vos escrevi;

[[v49-3-4]]

^<<v49-3-4,4>>^ Pelo que, quando ledes, podeis perceber a minha compreensão do mistério de Cristo,

[[v49-3-5]]

^<<v49-3-5,5>>^ O qual noutros séculos não foi manifestado aos filhos dos homens, como agora tem sido revelado pelo Espírito aos seus santos apóstolos e profetas;

[[v49-3-6]]

^<<v49-3-6,6>>^ A saber , que os gentios são coerdeiros, e de um mesmo corpo, e participantes da promessa em Cristo pelo evangelho;

[[v49-3-7]]

^<<v49-3-7,7>>^ Do qual fui feito ministro, pelo dom da graça de Deus, que me foi dado segundo a operação do seu poder.

[[v49-3-8]]

^<<v49-3-8,8>>^ A mim, o mínimo de todos os santos, me foi dada esta graça de anunciar entre os gentios, por meio do evangelho, as riquezas incompreensíveis de Cristo.

[[v49-3-9]]

^<<v49-3-9,9>>^ E demonstrar a todos qual seja a dispensação do mistério, que desde os séculos esteve oculto em Deus, que tudo criou;

[[v49-3-10]]

^<<v49-3-10,10>>^ Para que agora, pela igreja, a multiforme sabedoria de Deus seja conhecida dos principados e potestades nos céus,

[[v49-3-11]]

^<<v49-3-11,11>>^ Segundo o eterno propósito que fez em Cristo Jesus nosso Senhor,

[[v49-3-12]]

^<<v49-3-12,12>>^ No qual temos ousadia e acesso com confiança, pela nossa fé nele.

[[v49-3-13]]

^<<v49-3-13,13>>^ Portanto vos  peço que não desfaleçais nas minhas tribulações por vós, que são a vossa glória.

[[v49-3-14]]

^<<v49-3-14,14>>^ Por causa disto me ponho de joelhos perante o Pai de nosso Senhor Jesus Cristo,

[[v49-3-15]]

^<<v49-3-15,15>>^ Do qual toda a família nos céus e na terra toma o nome,

[[v49-3-16]]

^<<v49-3-16,16>>^ Para que, segundo as riquezas da sua glória, vos conceda que sejais corroborados com poder pelo seu Espírito no homem interior;

[[v49-3-17]]

^<<v49-3-17,17>>^ Para que Cristo habite pela fé nos vossos corações; a fim de, estando arraigados e fundados em amor,

[[v49-3-18]]

^<<v49-3-18,18>>^ Poderdes perfeitamente compreender, com todos os santos, qual seja a largura, e o comprimento, e a altura, e a profundidade,

[[v49-3-19]]

^<<v49-3-19,19>>^ E conhecer o amor de Cristo, que excede todo  o entendimento, para que sejais cheios de toda a plenitude de Deus.

[[v49-3-20]]

^<<v49-3-20,20>>^ Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera,

[[v49-3-21]]

^<<v49-3-21,21>>^ A esse glória na igreja, por Jesus Cristo, em todas as gerações, para todo o sempre. Amém.

'''

xref:049-efesios/049-efesios-002.adoc#v49-2-0[&#60; Capítulo Anterior] | <<v49-3-0,Topo>> | xref:049-efesios/049-efesios-004.adoc#v49-4-0[Próximo Capítulo &#62;]