include::./index.adoc[]

[[v49-4-0]]
=== Efésios, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v49-4-1]]

^<<v49-4-1,1>>^ ROGO-VOS, pois, eu, o preso do Senhor, que andeis como é digno da vocação com que fostes chamados,

[[v49-4-2]]

^<<v49-4-2,2>>^ Com toda a humildade e mansidão, com longanimidade, suportando-vos uns aos outros em amor,

[[v49-4-3]]

^<<v49-4-3,3>>^ Procurando guardar a unidade do Espírito pelo vínculo da paz.

[[v49-4-4]]

^<<v49-4-4,4>>^ Há  um só corpo e um só Espírito, como também fostes chamados em uma só esperança da vossa vocação;

[[v49-4-5]]

^<<v49-4-5,5>>^ Um só Senhor, uma só fé, um só batismo;

[[v49-4-6]]

^<<v49-4-6,6>>^ Um só Deus e Pai de todos, o qual é  sobre todos, e por todos e em todos.

[[v49-4-7]]

^<<v49-4-7,7>>^ Mas a graça foi dada a cada um de nós segundo a medida do dom de Cristo.

[[v49-4-8]]

^<<v49-4-8,8>>^ Pelo que diz: Subindo ao alto, levou cativo o cativeiro, e deu dons aos homens.

[[v49-4-9]]

^<<v49-4-9,9>>^ Ora, isto — ele subiu — que é, senão que também antes tinha descido às partes mais baixas da terra?

[[v49-4-10]]

^<<v49-4-10,10>>^ Aquele que desceu é também o mesmo que subiu acima de todos os céus, para cumprir todas as coisas.

[[v49-4-11]]

^<<v49-4-11,11>>^ E ele mesmo deu uns para apóstolos, e outros para profetas, e outros para evangelistas, e outros para pastores e doutores,

[[v49-4-12]]

^<<v49-4-12,12>>^ Querendo o aperfeiçoamento dos santos, para a obra do ministério, para edificação do corpo de Cristo;

[[v49-4-13]]

^<<v49-4-13,13>>^ Até que todos cheguemos à unidade da fé, e ao conhecimento do Filho de Deus, a varão perfeito, à medida da estatura completa de Cristo.

[[v49-4-14]]

^<<v49-4-14,14>>^ Para que não sejamos mais meninos inconstantes, levados em roda por todo o vento de doutrina, pelo engano dos homens que com astúcia enganam fraudulosamente.

[[v49-4-15]]

^<<v49-4-15,15>>^ Antes, seguindo a verdade em caridade, cresçamos em tudo naquele que é a cabeça, Cristo.

[[v49-4-16]]

^<<v49-4-16,16>>^ Do qual todo o corpo, bem-ajustado, e ligado pelo auxílio de todas as juntas, segundo a justa operação de cada parte, faz o aumento do corpo, para sua edificação em amor.

[[v49-4-17]]

^<<v49-4-17,17>>^ E digo isto, e testifico no Senhor, para que não andeis mais como andam também os outros gentios, na vaidade do seu sentido.

[[v49-4-18]]

^<<v49-4-18,18>>^ Entenebrecidos no entendimento, separados da vida de Deus pela ignorância que há neles, pela dureza do seu coração;

[[v49-4-19]]

^<<v49-4-19,19>>^ Os quais, havendo perdido todo o sentimento, se entregaram à dissolução, para com avidez cometerem toda a impureza.

[[v49-4-20]]

^<<v49-4-20,20>>^ Mas vós não aprendestes assim a Cristo,

[[v49-4-21]]

^<<v49-4-21,21>>^ Se é que o tendes ouvido, e nele fostes ensinados, como está a verdade em Jesus;

[[v49-4-22]]

^<<v49-4-22,22>>^ Que, quanto ao trato passado, vos despojeis do velho homem, que se corrompe pelas concupiscências do engano;

[[v49-4-23]]

^<<v49-4-23,23>>^ E vos renoveis no espírito do vosso sentido;

[[v49-4-24]]

^<<v49-4-24,24>>^ E vos revistais do novo homem, que segundo Deus é criado em verdadeira justiça e santidade.

[[v49-4-25]]

^<<v49-4-25,25>>^ Pelo que deixai a mentira, e falai a verdade cada um com o seu próximo; porque somos membros uns dos outros.

[[v49-4-26]]

^<<v49-4-26,26>>^ Irai-vos, e não pequeis; não se ponha o sol sobre a vossa ira.

[[v49-4-27]]

^<<v49-4-27,27>>^ Não deis lugar ao diabo.

[[v49-4-28]]

^<<v49-4-28,28>>^ Aquele que furtava, não furte mais; antes trabalhe, fazendo com as mãos o que é  bom, para que tenha que repartir com o que tiver necessidade.

[[v49-4-29]]

^<<v49-4-29,29>>^ Não saia da vossa boca nenhuma palavra torpe, mas só a que for boa para promover a edificação, para que dê graça aos que a ouvem.

[[v49-4-30]]

^<<v49-4-30,30>>^ E não entristeçais o Espírito Santo de Deus, no qual estais selados para o dia da redenção.

[[v49-4-31]]

^<<v49-4-31,31>>^ Toda a amargura, e ira, e cólera, e gritaria, e blasfêmias e toda a malícia seja tirada de entre vós.

[[v49-4-32]]

^<<v49-4-32,32>>^ Antes sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.

'''

xref:049-efesios/049-efesios-003.adoc#v49-3-0[&#60; Capítulo Anterior] | <<v49-4-0,Topo>> | xref:049-efesios/049-efesios-005.adoc#v49-5-0[Próximo Capítulo &#62;]