include::./index.adoc[]

[[v37-2-0]]
=== Ageu, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v37-2-1]]

^<<v37-2-1,1>>^ NO sétimo mês , ao vigésimo primeiro do mês, veio a palavra do Senhor pelo ministério do profeta Ageu, dizendo:

[[v37-2-2]]

^<<v37-2-2,2>>^ Fala agora a Zorobabel, filho de Sealtiel, príncipe de Judá, e a Josué, filho de Josadaque, sumo sacerdote, e ao resto do povo, dizendo:

[[v37-2-3]]

^<<v37-2-3,3>>^ Quem há  entre vós que, tendo ficado, viu esta casa na sua primeira glória? e como a vedes agora? não é  esta como nada em vossos olhos, comparada com aquela?

[[v37-2-4]]

^<<v37-2-4,4>>^ Ora, pois, esforça-te, Zorobabel, diz o Senhor, e esforça-te, Josué, filho de Josadaque, sumo sacerdote, e esforçai-vos, todo o povo da terra, diz o Senhor, e trabalhai; porque eu sou  convosco, diz o Senhor dos Exércitos,

[[v37-2-5]]

^<<v37-2-5,5>>^ Segundo a palavra que concertei convosco, quando saístes do Egito, e o meu Espírito habitava no meio de vós: não temais.

[[v37-2-6]]

^<<v37-2-6,6>>^ Porque assim diz o Senhor dos Exércitos: Ainda uma vez, daqui a pouco, e farei tremer os céus, e a terra, e o mar, e a terra seca;

[[v37-2-7]]

^<<v37-2-7,7>>^ E farei tremer todas as nações, e virá o Desejado de todas as nações, e encherei esta casa de glória, diz o Senhor dos Exércitos.

[[v37-2-8]]

^<<v37-2-8,8>>^ Minha é  a prata, e meu é o ouro, disse o Senhor dos Exércitos.

[[v37-2-9]]

^<<v37-2-9,9>>^ A glória desta última casa será maior do que a da primeira, diz o Senhor dos Exércitos, e neste lugar darei a paz, diz o Senhor dos Exércitos.

[[v37-2-10]]

^<<v37-2-10,10>>^ Ao vigésimo quarto dia do mês  nono, no segundo ano de Dario, veio a palavra do Senhor pelo ministério do profeta Ageu, dizendo:

[[v37-2-11]]

^<<v37-2-11,11>>^ Assim diz o Senhor dos Exércitos: Pergunta agora aos sacerdotes, acerca da lei, dizendo:

[[v37-2-12]]

^<<v37-2-12,12>>^ Se alguém leva carne santa na aba do seu vestido, e com a sua aba tocar no pão, ou no guisado, ou no vinho, ou no azeite, ou em qualquer outro mantimento, ficará este santificado? E os sacerdotes, respondendo, diziam: Não.

[[v37-2-13]]

^<<v37-2-13,13>>^ E disse Ageu: Se alguém, que se tinha tornado impuro pelo contato com um corpo morto, tocar nalguma destas cousas, ficará isso imundo? E os sacerdotes, respondendo, diziam: Ficará imunda.

[[v37-2-14]]

^<<v37-2-14,14>>^ Então respondeu Ageu e disse: Assim é este povo, e assim é esta nação diante do meu rosto, disse o Senhor; e assim é  toda a obra das suas mãos: e tudo o que ali oferecem imundo é.

[[v37-2-15]]

^<<v37-2-15,15>>^ Agora pois, aplicai o vosso coração a isto, desde este dia em diante, antes de pordes pedra sobre pedra no templo do Senhor.

[[v37-2-16]]

^<<v37-2-16,16>>^ Depois daquele tempo, veio alguém a um monte de vinte medidas , e havia somente dez: vindo ao lagar para tirar cinquenta, havia somente vinte.

[[v37-2-17]]

^<<v37-2-17,17>>^ Feri-vos com queimadura, e com ferrugem, e com saraiva, em toda a obra das vossas mãos; e não houve entre vós quem voltasse para mim, diz o Senhor.

[[v37-2-18]]

^<<v37-2-18,18>>^ Ponde pois, eu vos rogo, desde este dia em diante, desde o vigésimo quarto dia do mês  nono, desde o dia em que se fundou o templo do Senhor, ponde o vosso coração nestas cousas.

[[v37-2-19]]

^<<v37-2-19,19>>^ Há ainda semente no celeiro? nem a videira, nem a figueira, nem a romeira, nem a oliveira, têm dado os seus frutos; mas desde este dia vos abençoarei.

[[v37-2-20]]

^<<v37-2-20,20>>^ E veio a palavra do Senhor segunda vez a Ageu, aos vinte e quatro do mês, dizendo:

[[v37-2-21]]

^<<v37-2-21,21>>^ Fala a Zorobabel, príncipe de Judá, dizendo: Farei tremer os céus e a terra:

[[v37-2-22]]

^<<v37-2-22,22>>^ E derrubarei o trono dos reinos, e destruirei a força dos reinos das nações; e destruirei o carro e os que nele se assentam; e os cavalos e os que andam montados neles cairão, cada um pela espada do seu irmão.

[[v37-2-23]]

^<<v37-2-23,23>>^ Naquele dia, diz o Senhor dos Exércitos, te tomarei, ó Zorobabel, filho de Sealtiel, servo meu, diz o Senhor, e te farei como um anel de selar; porque te escolhi, diz o Senhor dos Exércitos.

'''

xref:037-ageu/037-ageu-001.adoc#v37-1-0[&#60; Capítulo Anterior] | <<v37-2-0,Topo>> | xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[Próximo Capítulo &#62;]