include::./index.adoc[]

[[v37-1-0]]
=== Ageu, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v37-1-1]]

^<<v37-1-1,1>>^ NO ano segundo do rei Dario, no sexto mês, no primeiro dia do mês, veio a palavra do Senhor, pelo ministério do profeta Ageu, a Zorobabel, filho de Sealtiel, príncipe de Judá, e a Josué, filho de Josadaque, o sumo sacerdote, dizendo:

[[v37-1-2]]

^<<v37-1-2,2>>^ Assim fala o Senhor dos Exércitos, dizendo: Este povo diz: Não veio ainda o tempo, o tempo em que a casa do Senhor deve ser edificada.

[[v37-1-3]]

^<<v37-1-3,3>>^ Veio pois a palavra do Senhor, pelo ministério do profeta Ageu, dizendo:

[[v37-1-4]]

^<<v37-1-4,4>>^ É para vós tempo de habitardes nas vossas casas estucadas, e esta casa há de ficar deserta?

[[v37-1-5]]

^<<v37-1-5,5>>^ Ora pois, assim diz o Senhor dos Exércitos: Aplicai os vossos corações aos vossos caminhos.

[[v37-1-6]]

^<<v37-1-6,6>>^ Semeais muito, e recolheis pouco; comeis, mas não vos fartais; bebeis, mas não vos saciais; vestis-vos, mas ninguém se aquece; e o que recebe salário, recebe salário num saco furado.

[[v37-1-7]]

^<<v37-1-7,7>>^ Assim diz o Senhor dos Exércitos: Aplicai os vossos corações aos vossos caminhos.

[[v37-1-8]]

^<<v37-1-8,8>>^ Subi ao monte, e trazei madeira, e edificai a casa, e dela me agradarei; e eu serei glorificado, diz o Senhor.

[[v37-1-9]]

^<<v37-1-9,9>>^ Olhastes para muito, mas eis que alcançastes pouco; e esse pouco, quando o trouxestes para casa, eu lhe assoprei. Por que causa? disse o Senhor dos Exércitos: por causa da minha casa, que está deserta, e cada um de vós corre à sua própria casa.

[[v37-1-10]]

^<<v37-1-10,10>>^ Por isso retêm os céus o seu orvalho, e a terra retém os seus frutos.

[[v37-1-11]]

^<<v37-1-11,11>>^ E fiz vir a seca sobre a terra, e sobre os montes, e sobre o trigo e sobre o mosto; e sobre o azeite, e sobre o que a terra produz: como também sobre os homens, e sobre os animais, e sobre todo o trabalho das mãos.

[[v37-1-12]]

^<<v37-1-12,12>>^ Então ouviu Zorobabel, filho de Sealtiel, e Josué, filho de Josadaque, sumo sacerdote, e todo o resto do povo a voz do Senhor seu Deus, e as palavras do profeta Ageu, como o Senhor seu Deus o tinha enviado; e temeu o povo diante do Senhor.

[[v37-1-13]]

^<<v37-1-13,13>>^ Então Ageu, o embaixador do Senhor, falou ao povo, conforme a mensagem do Senhor, dizendo: Eu sou  convosco, diz o Senhor.

[[v37-1-14]]

^<<v37-1-14,14>>^ E o Senhor levantou o espírito de Zorobabel, filho de Sealtiel, príncipe de Judá, e o espírito de Josué, filho de Josadaque, sumo sacerdote, e o espírito do resto de todo o povo, e vieram, e trabalharam na casa do Senhor dos Exércitos, seu Deus,

[[v37-1-15]]

^<<v37-1-15,15>>^ Ao vigésimo quarto dia do sexto mês , no segundo ano do rei Dario.

'''

xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[&#60; Capítulo Anterior] | <<v37-1-0,Topo>> | xref:037-ageu/037-ageu-002.adoc#v37-2-0[Próximo Capítulo &#62;]