include::./index.adoc[]

[[v60-4-0]]
=== 1 Pedro, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v60-4-1]]

^<<v60-4-1,1>>^ ORA, pois, já  que Cristo padeceu por nós na carne, armai-vos também vós com este pensamento, que aquele que padeceu na carne já  cessou do pecado;

[[v60-4-2]]

^<<v60-4-2,2>>^ Para que, no tempo que vos resta na carne, não vivais mais segundo as concupiscências dos homens, mas segundo a vontade de Deus.

[[v60-4-3]]

^<<v60-4-3,3>>^ Porque é bastante que no tempo passado da vida fizéssemos a vontade dos gentios, andando em dissoluções, concupiscências, borrachices, glutonarias, bebedices e abomináveis idolatrias;

[[v60-4-4]]

^<<v60-4-4,4>>^ E acham estranho não correrdes com eles no mesmo desenfreamento de dissolução, blasfemando de vós.

[[v60-4-5]]

^<<v60-4-5,5>>^ Os quais hão de dar conta ao que está preparado para julgar os vivos e os mortos.

[[v60-4-6]]

^<<v60-4-6,6>>^ Porque por isto foi pregado o evangelho também aos mortos, para que, na verdade, fossem julgados segundo os homens na carne, mas vivessem segundo Deus em espírito;

[[v60-4-7]]

^<<v60-4-7,7>>^ E já está próximo o fim de todas as coisas ; portanto sede sóbrios e vigiai em oração.

[[v60-4-8]]

^<<v60-4-8,8>>^ Mas, sobretudo, tende ardente caridade uns para com os outros; porque a caridade cobrirá a multidão de pecados.

[[v60-4-9]]

^<<v60-4-9,9>>^ Sendo hospitaleiros uns para os outros, sem murmurações.

[[v60-4-10]]

^<<v60-4-10,10>>^ Cada um administre aos outros o dom como o recebeu como bons despenseiros da multiforme graça de Deus.

[[v60-4-11]]

^<<v60-4-11,11>>^ Se alguém falar, fale  segundo as palavras de Deus: se alguém administrar, administre  segundo o poder que Deus dá; para que em tudo Deus seja glorificado por Jesus Cristo, a quem pertence a glória e poder para todo o sempre. Amém.

[[v60-4-12]]

^<<v60-4-12,12>>^ Amados, não estranheis a ardente prova que vem sobre vós para vos tentar, como se coisa estranha vos acontecesse;

[[v60-4-13]]

^<<v60-4-13,13>>^ Mas alegrai-vos no fato de serdes participantes das aflições de Cristo: para que também na revelação da sua glória vos regozijeis e alegreis.

[[v60-4-14]]

^<<v60-4-14,14>>^ Se pelo nome de Cristo sois vituperados, bem-aventurados sois, porque sobre vós repousa o Espírito da glória de Deus.

[[v60-4-15]]

^<<v60-4-15,15>>^ Que nenhum de vós padeça como homicida, ou ladrão, ou malfeitor, ou como o que se entremete em negócios alheios;

[[v60-4-16]]

^<<v60-4-16,16>>^ Mas, se padece  como cristão, não se envergonhe, antes glorifique a Deus nesta parte.

[[v60-4-17]]

^<<v60-4-17,17>>^ Porque já é  tempo que comece o julgamento pela casa de Deus; e, se primeiro começa  por nós, qual será o fim daqueles que são desobedientes ao evangelho de Deus?

[[v60-4-18]]

^<<v60-4-18,18>>^ E, se o justo apenas se salva, onde aparecerá o ímpio e o pecador?

[[v60-4-19]]

^<<v60-4-19,19>>^ Portanto também os que padecem segundo a vontade de Deus encomendem- lhe  as suas almas, como ao fiel Criador, fazendo o bem.

'''

xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[&#60; Capítulo Anterior] | <<v60-4-0,Topo>> | xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[Próximo Capítulo &#62;]