include::./index.adoc[]

[[v60-2-0]]
=== 1 Pedro, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v60-2-1]]

^<<v60-2-1,1>>^ DEIXANDO pois toda a malícia, e todo o engano, e fingimentos, e invejas, e todas as murmurações,

[[v60-2-2]]

^<<v60-2-2,2>>^ Desejai afetuosamente, como meninos novamente nascidos, o leite racional, não falsificado, para que por ele vades crescendo:

[[v60-2-3]]

^<<v60-2-3,3>>^ Se é que já provastes que o Senhor é  benigno:

[[v60-2-4]]

^<<v60-2-4,4>>^ E, chegando-vos para ele — pedra viva, reprovada, na verdade, pelos homens, mas para com Deus eleita e  preciosa.

[[v60-2-5]]

^<<v60-2-5,5>>^ Vós também, como pedras vivas, sois edificados casa espiritual e sacerdócio santo, para oferecer sacrifícios espirituais agradáveis a Deus por Jesus Cristo.

[[v60-2-6]]

^<<v60-2-6,6>>^ Pelo que também na Escritura se contém: Eis que ponho em Sião a pedra principal da esquina, eleita e  preciosa; e quem nela crer não será confundido.

[[v60-2-7]]

^<<v60-2-7,7>>^ E assim para vós, os que credes, é preciosa, mas, para os rebeldes, a pedra que os edificadores reprovaram essa foi a principal da esquina:

[[v60-2-8]]

^<<v60-2-8,8>>^ E uma pedra de tropeço e rocha de escândalo, para aqueles que tropeçam na palavra, sendo desobedientes; para o que também foram destinados.

[[v60-2-9]]

^<<v60-2-9,9>>^ Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz;

[[v60-2-10]]

^<<v60-2-10,10>>^ Vós, que em outro tempo não éreis povo, mas agora sois  povo de Deus; que não tínheis alcançado misericórdia, mas agora alcançastes misericórdia.

[[v60-2-11]]

^<<v60-2-11,11>>^ Amados, peço-vos, como a peregrinos e forasteiros, que vos abstenhais das concupiscências carnais que combatem contra a alma;

[[v60-2-12]]

^<<v60-2-12,12>>^ Tendo o vosso viver honesto entre os gentios; para que, naquilo em que falam mal de vós, como de malfeitores, glorifiquem a Deus no dia da visitação, pelas boas obras que em vós observem.

[[v60-2-13]]

^<<v60-2-13,13>>^ Sujeitai-vos pois a toda a ordenação humana por amor do Senhor; quer ao rei, como superior;

[[v60-2-14]]

^<<v60-2-14,14>>^ Quer aos governadores como por ele enviados para castigo dos malfeitores, e para louvor dos que fazem o bem.

[[v60-2-15]]

^<<v60-2-15,15>>^ Porque assim é a vontade de Deus, que, fazendo bem, tapeis a boca à ignorância dos homens loucos:

[[v60-2-16]]

^<<v60-2-16,16>>^ Como livres, e não tendo a liberdade por cobertura da malícia, mas como servos de Deus.

[[v60-2-17]]

^<<v60-2-17,17>>^ Honrai a todos. Amai a fraternidade. Temei a Deus. Honrai o rei.

[[v60-2-18]]

^<<v60-2-18,18>>^ Vós, servos, sujeitai-vos com todo o temor aos senhores, não somente aos bons e humanos, mas também aos maus.

[[v60-2-19]]

^<<v60-2-19,19>>^ Porque é coisa agradável, que alguém, por causa da consciência para com Deus, sofra agravos, padecendo injustamente.

[[v60-2-20]]

^<<v60-2-20,20>>^ Porque, que glória será essa, se, pecando, sois esbofeteados e sofreis, mas se, fazendo o bem, sois afligidos e o sofreis, isso é agradável a Deus.

[[v60-2-21]]

^<<v60-2-21,21>>^ Porque para isto sois chamados; pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas.

[[v60-2-22]]

^<<v60-2-22,22>>^ O qual não cometeu pecado, nem na sua boca se achou engano.

[[v60-2-23]]

^<<v60-2-23,23>>^ O qual, quando o injuriavam, não injuriava, e quando padecia não ameaçava, mas entregava-se àquele que julga justamente:

[[v60-2-24]]

^<<v60-2-24,24>>^ Levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, pudéssemos viver para a justiça; e pelas suas feridas fostes sarados.

[[v60-2-25]]

^<<v60-2-25,25>>^ Porque éreis como ovelhas desgarradas: mas agora tendes voltado ao Pastor e Bispo das vossas almas.

'''

xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[Próximo Capítulo &#62;]