include::./index.adoc[]

[[v45-13-0]]
=== Romanos, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-13-1]]

^<<v45-13-1,1>>^ TODA a alma esteja sujeita às potestades superiores; porque não há potestade que não venha de Deus; e as potestades que há foram ordenadas por Deus.

[[v45-13-2]]

^<<v45-13-2,2>>^ Por isso quem resiste à potestade resiste à ordenação de Deus; e os que resistem trarão sobre si mesmos a condenação.

[[v45-13-3]]

^<<v45-13-3,3>>^ Porque os magistrados não são terror para as boas obras, mas para as más. Queres tu, pois, não temer a potestade? Faze o bem, e terás louvor dela.

[[v45-13-4]]

^<<v45-13-4,4>>^ Porque ela é ministro de Deus para teu bem. Mas, se fizeres o mal, teme, pois não traz debalde a espada; porque é ministro de Deus, e vingador para castigar o que faz o mal.

[[v45-13-5]]

^<<v45-13-5,5>>^ Portanto é necessário que lhe estejais sujeitos, não somente pelo castigo, mas também pela consciência.

[[v45-13-6]]

^<<v45-13-6,6>>^ Por esta razão também pagais tributos: porque são ministros de Deus, atendendo sempre a isto mesmo.

[[v45-13-7]]

^<<v45-13-7,7>>^ Portanto dai a cada um o que deveis: a quem tributo, tributo: a quem imposto, imposto: a quem temor, temor: a quem honra, honra.

[[v45-13-8]]

^<<v45-13-8,8>>^ A ninguém devais coisa alguma, a não ser o amor com que vos ameis uns aos outros: porque quem ama aos outros cumpriu a lei.

[[v45-13-9]]

^<<v45-13-9,9>>^ Com efeito: Não adulterarás: Não matarás: Não furtarás: Não darás falso testemunho: Não cobiçarás: e se há  algum outro mandamento, tudo nesta palavra se resume: Amarás ao teu próximo como a ti mesmo.

[[v45-13-10]]

^<<v45-13-10,10>>^ O amor não faz mal ao próximo. De sorte que o cumprimento da lei é  o amor.

[[v45-13-11]]

^<<v45-13-11,11>>^ E isto digo , conhecendo o tempo, que é  já hora de despertarmos do sono; porque a nossa salvação está agora mais perto de nós do que quando aceitamos a fé.

[[v45-13-12]]

^<<v45-13-12,12>>^ A noite é passada, e o dia é chegado. Rejeitemos pois as obras das trevas, e vistamo-nos das armas da luz.

[[v45-13-13]]

^<<v45-13-13,13>>^ Andemos honestamente, como de dia: não em glutonarias, nem em bebedeiras, nem em desonestidades, nem em dissoluções, nem em contendas e inveja.

[[v45-13-14]]

^<<v45-13-14,14>>^ Mas revesti-vos do Senhor Jesus Cristo, e não tenhais cuidado da carne em suas  concupiscências.

'''

xref:045-romanos/045-romanos-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romanos/045-romanos-014.adoc#v45-14-0[Próximo Capítulo &#62;]