include::./index.adoc[]

[[v45-15-0]]
=== Romanos, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-15-1]]

^<<v45-15-1,1>>^ MAS nós, que somos fortes, devemos suportar as fraquezas dos fracos, e não agradar a nós mesmos.

[[v45-15-2]]

^<<v45-15-2,2>>^ Portanto cada um de nós agrade ao seu  próximo no que é bom para edificação.

[[v45-15-3]]

^<<v45-15-3,3>>^ Porque também Cristo não agradou a si mesmo, mas, como está escrito: Sobre mim caíram as injúrias dos que te injuriavam.

[[v45-15-4]]

^<<v45-15-4,4>>^ Porque tudo que dantes foi escrito para nosso ensino foi escrito, para que pela paciência e consolação das Escrituras tenhamos esperança.

[[v45-15-5]]

^<<v45-15-5,5>>^ Ora o Deus de paciência e consolação vos conceda o mesmo sentimento uns para com os outros, segundo Cristo Jesus.

[[v45-15-6]]

^<<v45-15-6,6>>^ Para que concordes, a uma boca, glorifiqueis ao Deus e Pai de nosso Senhor Jesus Cristo.

[[v45-15-7]]

^<<v45-15-7,7>>^ Portanto recebei-vos uns aos outros, como também Cristo nos recebeu para glória de Deus.

[[v45-15-8]]

^<<v45-15-8,8>>^ Digo pois que Jesus Cristo foi ministro da circuncisão, por causa da verdade de Deus, para que confirmasse as promessas feitas  aos pais;

[[v45-15-9]]

^<<v45-15-9,9>>^ E para  que os gentios glorifiquem a Deus pela sua misericórdia, como está escrito: Portanto eu te louvarei entre os gentios, e cantarei ao teu nome.

[[v45-15-10]]

^<<v45-15-10,10>>^ E outra vez diz: Alegrai-vos, gentios, com o seu povo.

[[v45-15-11]]

^<<v45-15-11,11>>^ E outra vez: Louvai ao Senhor, todos os gentios, e celebrai-o, todos os povos.

[[v45-15-12]]

^<<v45-15-12,12>>^ E outra vez diz Isaías: Uma raiz em Jessé haverá, e naquele que se levantar para reger os gentios, os gentios esperarão.

[[v45-15-13]]

^<<v45-15-13,13>>^ Ora o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo.

[[v45-15-14]]

^<<v45-15-14,14>>^ Eu próprio, meus irmãos, certo estou, a respeito de vós, que vós mesmos estais cheios de bondade, cheios de todo o conhecimento, podendo admoestar-vos uns aos outros.

[[v45-15-15]]

^<<v45-15-15,15>>^ Mas, irmãos, em parte vos escrevi mais ousadamente, como para vos trazer outra vez isto  à memória, pela graça que por Deus me foi dada;

[[v45-15-16]]

^<<v45-15-16,16>>^ Que seja ministro de Jesus Cristo entre os gentios, ministrando o evangelho de Deus, para que seja agradável a oferta dos gentios, santificada pelo Espírito Santo.

[[v45-15-17]]

^<<v45-15-17,17>>^ De sorte que tenho glória em Jesus Cristo nas coisas  que pertencem a Deus.

[[v45-15-18]]

^<<v45-15-18,18>>^ Porque não ousaria dizer coisa  alguma, que Cristo por mim não tenha feito, para obediência dos gentios, por palavra e por obras;

[[v45-15-19]]

^<<v45-15-19,19>>^ Pelo poder dos sinais e prodígios, na virtude do Espírito de Deus: de maneira que desde Jerusalém, e arredores, até ao Ilírico, tenho pregado o evangelho de Jesus Cristo.

[[v45-15-20]]

^<<v45-15-20,20>>^ E desta maneira me esforcei por anunciar o evangelho, não onde Cristo houvera sido nomeado, para não edificar sobre fundamento alheio;

[[v45-15-21]]

^<<v45-15-21,21>>^ Antes, como está escrito: Aqueles a quem não foi anunciado, o  verão, e os que não ouviram o  entenderão.

[[v45-15-22]]

^<<v45-15-22,22>>^ Pelo que também muitas vezes tenho sido impedido de ir ter convosco.

[[v45-15-23]]

^<<v45-15-23,23>>^ Mas agora, que não tenho mais demora nestes sítios, e tendo já há muitos anos grande desejo de ir ter convosco,

[[v45-15-24]]

^<<v45-15-24,24>>^ Quando partir para Espanha irei ter convosco; pois espero que de passagem vos verei, e que para lá seja encaminhado por vós, depois de ter gozado um pouco da vossa companhia.

[[v45-15-25]]

^<<v45-15-25,25>>^ Mas agora vou a Jerusalém para ministrar aos santos.

[[v45-15-26]]

^<<v45-15-26,26>>^ Porque pareceu bem à Macedônia e à Acaia fazerem uma coleta para os pobres dentre os santos que estão em Jerusalém.

[[v45-15-27]]

^<<v45-15-27,27>>^ Isto lhes pareceu bem, como devedores que são para com eles. Porque, se os gentios foram participantes dos seus bens  espirituais, devem também ministrar-lhes os temporais.

[[v45-15-28]]

^<<v45-15-28,28>>^ Assim que, concluído isto, e havendo-lhes consignado este fruto, de lá, passando  por vós, irei à Espanha.

[[v45-15-29]]

^<<v45-15-29,29>>^ E bem sei que, indo ter convosco, chegarei com a plenitude da bênção do evangelho de Cristo.

[[v45-15-30]]

^<<v45-15-30,30>>^ E rogo-vos irmãos, por nosso Senhor Jesus Cristo e pelo amor do Espírito, que combatais comigo nas vossas orações por mim a Deus;

[[v45-15-31]]

^<<v45-15-31,31>>^ Para que seja livre dos rebeldes que estão na Judeia, e que esta minha administração, que em Jerusalém faço , seja bem aceita pelos santos;

[[v45-15-32]]

^<<v45-15-32,32>>^ A fim de que, pela vontade de Deus, chegue a vós com alegria, e possa recrear-me convosco.

[[v45-15-33]]

^<<v45-15-33,33>>^ E o Deus de paz seja com todos vós. Amém.

'''

xref:045-romanos/045-romanos-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romanos/045-romanos-016.adoc#v45-16-0[Próximo Capítulo &#62;]