include::./index.adoc[]

[[v45-8-0]]
=== Romanos, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-8-1]]

^<<v45-8-1,1>>^ PORTANTO agora nenhuma condenação há  para os que estão  em Cristo Jesus, que não andam segundo a carne, mas segundo o espírito.

[[v45-8-2]]

^<<v45-8-2,2>>^ Porque a lei do espírito de vida, em Cristo Jesus, me livrou da lei do pecado e da morte.

[[v45-8-3]]

^<<v45-8-3,3>>^ Porquanto o que era impossível à lei, visto como estava enferma pela carne, Deus, enviando o seu Filho em semelhança da carne do pecado, pelo pecado condenou o pecado na carne;

[[v45-8-4]]

^<<v45-8-4,4>>^ Para que a justiça da lei se cumprisse em nós, que não andamos segundo a carne, mas segundo o espírito.

[[v45-8-5]]

^<<v45-8-5,5>>^ Porque os que são segundo a carne inclinam-se para as coisas  da carne; mas os que são  segundo o espírito para as coisas  do espírito.

[[v45-8-6]]

^<<v45-8-6,6>>^ Porque a inclinação da carne é  morte; mas a inclinação do espírito é  vida e paz.

[[v45-8-7]]

^<<v45-8-7,7>>^ Porquanto a inclinação da carne é  inimizade contra Deus, pois não é sujeita à lei de Deus, nem, em verdade, o pode ser.

[[v45-8-8]]

^<<v45-8-8,8>>^ Portanto, os que estão na carne não podem agradar a Deus.

[[v45-8-9]]

^<<v45-8-9,9>>^ Vós, porém, não estais na carne, mas no espírito, se é que o Espírito de Deus habita em vós. Mas, se alguém não tem o Espírito de Cristo, esse tal não é dele.

[[v45-8-10]]

^<<v45-8-10,10>>^ E, se Cristo está  em vós, o corpo, na verdade, está  morto por causa do pecado, mas o espírito vive por causa da justiça.

[[v45-8-11]]

^<<v45-8-11,11>>^ E, se o Espírito daquele que dos mortos ressuscitou a Jesus habita em vós, aquele que dos mortos ressuscitou a Cristo também vivificará os vossos corpos mortais, pelo seu Espírito que em vós habita.

[[v45-8-12]]

^<<v45-8-12,12>>^ De maneira que, irmãos, somos devedores, não à carne para viver segundo a carne.

[[v45-8-13]]

^<<v45-8-13,13>>^ Porque, se viverdes segundo a carne, morrereis; mas, se pelo espírito mortificardes as obras do corpo, vivereis.

[[v45-8-14]]

^<<v45-8-14,14>>^ Porque todos os que são guiados pelo Espírito de Deus esses são filhos de Deus.

[[v45-8-15]]

^<<v45-8-15,15>>^ Porque não recebestes o espírito de escravidão para outra vez estardes  em temor, mas recebestes o espírito de adoção de filhos, pelo qual clamamos: Aba, Pai.

[[v45-8-16]]

^<<v45-8-16,16>>^ O mesmo Espírito testifica com o nosso espírito que somos filhos de Deus.

[[v45-8-17]]

^<<v45-8-17,17>>^ E, se nós somos filhos, somos logo herdeiros também, herdeiros de Deus e coerdeiros de Cristo: se é certo que com ele  padecemos, para que também com ele  sejamos glorificados.

[[v45-8-18]]

^<<v45-8-18,18>>^ Porque para mim tenho por certo que as aflições deste tempo presente não são  para comparar com a glória que em nós há de ser revelada.

[[v45-8-19]]

^<<v45-8-19,19>>^ Porque a ardente expectação da criatura espera a manifestação dos filhos de Deus.

[[v45-8-20]]

^<<v45-8-20,20>>^ Porque a criação ficou sujeita à vaidade, não por sua vontade, mas por causa do que a sujeitou,

[[v45-8-21]]

^<<v45-8-21,21>>^ Na esperança de que também a mesma criatura será libertada da servidão da corrupção, para a liberdade da glória dos filhos de Deus.

[[v45-8-22]]

^<<v45-8-22,22>>^ Porque sabemos que toda a criação geme e está juntamente com dores de parto até agora.

[[v45-8-23]]

^<<v45-8-23,23>>^ E não só ela , mas nós mesmos, que temos as primícias do Espírito, também gememos em nós mesmos, esperando a adoção, a saber, a redenção do nosso corpo.

[[v45-8-24]]

^<<v45-8-24,24>>^ Porque em esperança somos salvos. Ora a esperança que se vê não é esperança; porque o que alguém vê como o esperará?

[[v45-8-25]]

^<<v45-8-25,25>>^ Mas, se esperamos o que não vemos, com paciência o esperamos.

[[v45-8-26]]

^<<v45-8-26,26>>^ E da mesma maneira também o Espírito ajuda as nossas fraquezas; porque não sabemos o que havemos de pedir como convém, mas o mesmo Espírito intercede por nós com gemidos inexprimíveis.

[[v45-8-27]]

^<<v45-8-27,27>>^ E aquele que examina os corações sabe qual é a intenção do Espírito; e é ele que segundo Deus intercede pelos santos.

[[v45-8-28]]

^<<v45-8-28,28>>^ E sabemos que todas as coisas  contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados por seu  decreto.

[[v45-8-29]]

^<<v45-8-29,29>>^ Porque os que dantes conheceu também os predestinou para serem  conformes à imagem de seu Filho; a fim de que ele seja o primogênito entre muitos irmãos.

[[v45-8-30]]

^<<v45-8-30,30>>^ E aos que predestinou a estes também chamou: e aos que chamou a estes também justificou; e aos que justificou a estes também glorificou.

[[v45-8-31]]

^<<v45-8-31,31>>^ Que diremos pois a estas coisas ? Se Deus é por nós, quem será  contra nós?

[[v45-8-32]]

^<<v45-8-32,32>>^ Aquele que nem mesmo a seu próprio Filho poupou, antes o entregou por todos nós, como nos não dará também com ele todas as coisas ?

[[v45-8-33]]

^<<v45-8-33,33>>^ Quem intentará acusação contra os escolhidos de Deus? É Deus quem os justifica.

[[v45-8-34]]

^<<v45-8-34,34>>^ Quem os condenará? Pois é Cristo quem morreu, ou antes quem ressuscitou dentre os mortos, o qual está à direita de Deus, e também intercede por nós.

[[v45-8-35]]

^<<v45-8-35,35>>^ Quem nos separará do amor de Cristo? A tribulação, ou a angústia, ou a perseguição, ou a fome, ou a nudez, ou o perigo, ou a espada?

[[v45-8-36]]

^<<v45-8-36,36>>^ Como está escrito: Por amor de ti somos entregues à morte todo o dia: fomos reputados como ovelhas para o matadouro.

[[v45-8-37]]

^<<v45-8-37,37>>^ Mas em todas estas coisas  somos mais do que vencedores, por aquele que nos amou.

[[v45-8-38]]

^<<v45-8-38,38>>^ Porque estou certo de que, nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir,

[[v45-8-39]]

^<<v45-8-39,39>>^ Nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus nosso Senhor!

'''

xref:045-romanos/045-romanos-007.adoc#v45-7-0[&#60; Capítulo Anterior] | <<v45-8-0,Topo>> | xref:045-romanos/045-romanos-009.adoc#v45-9-0[Próximo Capítulo &#62;]