include::./index.adoc[]

[[v45-10-0]]
=== Romanos, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-10-1]]

^<<v45-10-1,1>>^ IRMÃOS, o bom desejo do meu coração e a oração a Deus por Israel é para sua  salvação.

[[v45-10-2]]

^<<v45-10-2,2>>^ Porque lhes dou testemunho de que têm zelo de Deus, mas não com entendimento.

[[v45-10-3]]

^<<v45-10-3,3>>^ Porquanto, não conhecendo a justiça de Deus, e procurando estabelecer a sua própria justiça, não se sujeitaram à justiça de Deus.

[[v45-10-4]]

^<<v45-10-4,4>>^ Porque o fim da lei é  Cristo para justiça de todo aquele que crê.

[[v45-10-5]]

^<<v45-10-5,5>>^ Ora Moisés descreve a justiça que é pela lei, dizendo : O homem que fizer estas coisas  viverá por elas.

[[v45-10-6]]

^<<v45-10-6,6>>^ Mas a justiça que é pela fé diz assim: Não digas em teu coração: Quem subirá ao céu? (isto é, a trazer do alto  a Cristo).

[[v45-10-7]]

^<<v45-10-7,7>>^ Ou: Quem descerá ao abismo? (isto é, a tornar a trazer dentre os mortos a Cristo).

[[v45-10-8]]

^<<v45-10-8,8>>^ Mas que diz? A palavra está junto de ti, na tua boca e no teu coração; esta é a palavra da fé, que pregamos,

[[v45-10-9]]

^<<v45-10-9,9>>^ A saber: Se com a tua boca confessares ao Senhor Jesus, e em teu coração creres que Deus o ressuscitou dos mortos, serás salvo.

[[v45-10-10]]

^<<v45-10-10,10>>^ Visto que com o coração se crê para a justiça, e com a boca se faz confissão para a salvação.

[[v45-10-11]]

^<<v45-10-11,11>>^ Porque a Escritura diz: Todo aquele que nele crer não será confundido.

[[v45-10-12]]

^<<v45-10-12,12>>^ Porquanto não há diferença entre judeu e grego: porque um mesmo é  o Senhor de todos, rico para com todos os que o invocam.

[[v45-10-13]]

^<<v45-10-13,13>>^ Porque todo aquele que invocar o nome do Senhor será salvo.

[[v45-10-14]]

^<<v45-10-14,14>>^ Como pois invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?

[[v45-10-15]]

^<<v45-10-15,15>>^ E como pregarão, se não forem enviados? como está escrito: Quão formosos os pés dos que anunciam a paz, dos que anunciam coisas boas!

[[v45-10-16]]

^<<v45-10-16,16>>^ Mas nem todos obedecem ao evangelho; pois Isaías diz: Senhor, quem creu na nossa pregação?

[[v45-10-17]]

^<<v45-10-17,17>>^ De sorte que a fé é  pelo ouvir, e o ouvir pela palavra de Deus.

[[v45-10-18]]

^<<v45-10-18,18>>^ Mas digo: Porventura não ouviram? Sim, por certo, pois por toda a terra saiu a voz deles, e as suas palavras até aos confins do mundo.

[[v45-10-19]]

^<<v45-10-19,19>>^ Mas digo: Porventura Israel não o soube? Primeiramente diz Moisés: Eu vos meterei em ciúmes com aqueles que  não são  povo, com gente insensata vos provocarei à ira.

[[v45-10-20]]

^<<v45-10-20,20>>^ E Isaías ousadamente diz: Fui achado pelos que me não buscavam, fui manifestado aos que por mim não perguntavam.

[[v45-10-21]]

^<<v45-10-21,21>>^ Mas contra Israel diz: Todo o dia estendi as minhas mãos a um povo rebelde e contradizente.

'''

xref:045-romanos/045-romanos-009.adoc#v45-9-0[&#60; Capítulo Anterior] | <<v45-10-0,Topo>> | xref:045-romanos/045-romanos-011.adoc#v45-11-0[Próximo Capítulo &#62;]