include::./index.adoc[]

[[v45-3-0]]
=== Romanos, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-3-1]]

^<<v45-3-1,1>>^ QUAL é logo a vantagem do judeu? Ou qual a utilidade da circuncisão?

[[v45-3-2]]

^<<v45-3-2,2>>^ Muita, em toda a maneira, porque, primeiramente, as palavras de Deus lhe foram confiadas,

[[v45-3-3]]

^<<v45-3-3,3>>^ Pois quê? Se alguns foram incrédulos, a sua incredulidade aniquilará a fidelidade de Deus?

[[v45-3-4]]

^<<v45-3-4,4>>^ De maneira nenhuma; sempre seja Deus verdadeiro, e todo o homem mentiroso; como está escrito: Para que sejas justificado em tuas palavras, e venças quando fores julgado.

[[v45-3-5]]

^<<v45-3-5,5>>^ E, se a nossa injustiça for causa da justiça de Deus, que diremos? Porventura será  Deus injusto, trazendo ira sobre nós ? ( Falo como homem).

[[v45-3-6]]

^<<v45-3-6,6>>^ De maneira nenhuma: doutro modo, como julgará Deus o mundo?

[[v45-3-7]]

^<<v45-3-7,7>>^ Mas, se pela minha mentira abundou mais a verdade de Deus para glória sua, por que sou eu ainda julgado também como pecador?

[[v45-3-8]]

^<<v45-3-8,8>>^ E por que não dizemos  (como somos blasfemados, e como alguns dizem que dizemos): Façamos males, para que venham bens? A condenação desses é justa.

[[v45-3-9]]

^<<v45-3-9,9>>^ Pois quê? Somos nós mais excelentes? de maneira nenhuma, pois já dantes demonstramos que, tanto judeus como gregos, todos estão debaixo do pecado;

[[v45-3-10]]

^<<v45-3-10,10>>^ Como está escrito: Não há um justo, nem um sequer.

[[v45-3-11]]

^<<v45-3-11,11>>^ Não há ninguém que entenda; não há ninguém que busque a Deus.

[[v45-3-12]]

^<<v45-3-12,12>>^ Todos se extraviaram, e juntamente se fizeram inúteis. Não há quem faça o bem, não há nem um só.

[[v45-3-13]]

^<<v45-3-13,13>>^ A sua garganta é um  sepulcro aberto: com as suas línguas tratam enganosamente: peçonha de áspides está  debaixo de seus lábios;

[[v45-3-14]]

^<<v45-3-14,14>>^ Cuja boca está  cheia de maldição e amargura.

[[v45-3-15]]

^<<v45-3-15,15>>^ Os seus pés são  ligeiros para derramar sangue.

[[v45-3-16]]

^<<v45-3-16,16>>^ Em seus caminhos há  destruição e miséria;

[[v45-3-17]]

^<<v45-3-17,17>>^ E não conheceram o caminho da paz.

[[v45-3-18]]

^<<v45-3-18,18>>^ Não há temor de Deus diante de seus olhos.

[[v45-3-19]]

^<<v45-3-19,19>>^ Ora, nós sabemos que tudo o que a lei diz aos que estão debaixo da lei o diz, para que toda a boca esteja fechada e todo o mundo seja condenável diante  de Deus.

[[v45-3-20]]

^<<v45-3-20,20>>^ Por isso nenhuma carne será justificada diante dele pelas obras da lei, porque pela lei vem o conhecimento do pecado.

[[v45-3-21]]

^<<v45-3-21,21>>^ Mas agora se manifestou sem a lei a justiça de Deus, tendo o testemunho da lei e dos profetas;

[[v45-3-22]]

^<<v45-3-22,22>>^ Isto é, a justiça de Deus pela fé em Jesus Cristo para todos e sobre todos os que creem; porque não há diferença.

[[v45-3-23]]

^<<v45-3-23,23>>^ Porque todos pecaram e destituídos estão da glória de Deus;

[[v45-3-24]]

^<<v45-3-24,24>>^ Sendo justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus,

[[v45-3-25]]

^<<v45-3-25,25>>^ Ao qual Deus propôs para propiciação pela fé no seu sangue, para demonstrar a sua justiça pela remissão dos pecados dantes cometidos, sob a paciência de Deus;

[[v45-3-26]]

^<<v45-3-26,26>>^ Para demonstração da sua justiça neste tempo presente, para que ele seja justo e justificador daquele que tem fé em Jesus.

[[v45-3-27]]

^<<v45-3-27,27>>^ Onde está  logo a jactância? É excluída. Por qual lei? Das obras? Não; mas pela lei da fé.

[[v45-3-28]]

^<<v45-3-28,28>>^ Concluímos pois que o homem é justificado pela fé sem as obras da lei.

[[v45-3-29]]

^<<v45-3-29,29>>^ É porventura Deus somente dos judeus? E não o é  também dos gentios? Também dos gentios, certamente.

[[v45-3-30]]

^<<v45-3-30,30>>^ Se Deus é um só, que justifica pela fé a circuncisão, e por meio da fé a incircuncisão,

[[v45-3-31]]

^<<v45-3-31,31>>^ Anulamos, pois, a lei pela fé? De maneira nenhuma, antes estabelecemos a lei.

'''

xref:045-romanos/045-romanos-002.adoc#v45-2-0[&#60; Capítulo Anterior] | <<v45-3-0,Topo>> | xref:045-romanos/045-romanos-004.adoc#v45-4-0[Próximo Capítulo &#62;]