include::./index.adoc[]

[[v45-11-0]]
=== Romanos, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-11-1]]

^<<v45-11-1,1>>^ DIGO pois: Porventura rejeitou Deus o seu povo? De modo nenhum; porque também eu sou israelita, da descendência d’Abraão, da tribo de Benjamim.

[[v45-11-2]]

^<<v45-11-2,2>>^ Deus não rejeitou o seu povo, que antes conheceu. Ou não sabeis o que a Escritura diz de Elias, como fala a Deus contra Israel, dizendo:

[[v45-11-3]]

^<<v45-11-3,3>>^ Senhor, mataram os teus profetas, e derribaram os teus altares; e só eu fiquei, e buscam a minha alma?

[[v45-11-4]]

^<<v45-11-4,4>>^ Mas que lhe diz a resposta divina? Reservei para mim sete mil varões, que não dobraram os joelhos diante de Baal.

[[v45-11-5]]

^<<v45-11-5,5>>^ Assim pois também agora neste tempo ficou um resto, segundo a eleição da graça.

[[v45-11-6]]

^<<v45-11-6,6>>^ Mas se é por graça, já não é pelas obras: de outra maneira, a graça já não é graça.

[[v45-11-7]]

^<<v45-11-7,7>>^ Pois quê? O que Israel buscava não o alcançou; mas os eleitos o alcançaram, e os outros foram endurecidos.

[[v45-11-8]]

^<<v45-11-8,8>>^ Como está escrito: Deus lhes deu espírito de profundo sono: olhos para não verem, e ouvidos para não ouvirem, até ao dia  de hoje.

[[v45-11-9]]

^<<v45-11-9,9>>^ E Davi diz: Torne-se-lhes a sua mesa em laço, e em armadilha, e em tropeço, por sua retribuição;

[[v45-11-10]]

^<<v45-11-10,10>>^ Escureçam-se-lhes os olhos para não verem, e encurvem-se-lhes continuamente as costas.

[[v45-11-11]]

^<<v45-11-11,11>>^ Digo pois: Porventura tropeçaram, para que caíssem? De modo nenhum, mas pela sua queda veio  a salvação aos gentios, para os incitar à emulação.

[[v45-11-12]]

^<<v45-11-12,12>>^ E, se a sua queda é a riqueza do mundo, e a sua diminuição a riqueza dos gentios, quanto mais a sua plenitude!

[[v45-11-13]]

^<<v45-11-13,13>>^ Porque convosco falo, gentios, que, enquanto for apóstolo dos gentios, glorificarei o meu ministério;

[[v45-11-14]]

^<<v45-11-14,14>>^ Para ver  se de alguma maneira posso incitar à emulação os da minha carne e salvar alguns deles.

[[v45-11-15]]

^<<v45-11-15,15>>^ Porque, se a sua rejeição é  a reconciliação do mundo, qual será  a sua  admissão, senão a vida dentre os mortos?

[[v45-11-16]]

^<<v45-11-16,16>>^ E, se as primícias são  santas, também a massa o é ; se a raiz é santa, também os ramos o são.

[[v45-11-17]]

^<<v45-11-17,17>>^ E se alguns dos ramos foram quebrados, e tu, sendo zambujeiro, foste enxertado em lugar deles, e feito participante da raiz e da seiva da oliveira,

[[v45-11-18]]

^<<v45-11-18,18>>^ Não te glories contra os ramos; e, se contra eles  te gloriares, não és tu que sustentas a raiz, mas a raiz a ti.

[[v45-11-19]]

^<<v45-11-19,19>>^ Dirás pois: Os ramos foram quebrados, para que eu fosse enxertado.

[[v45-11-20]]

^<<v45-11-20,20>>^ Está bem: pela sua incredulidade foram quebrados, e tu estás em pé pela fé: então não te ensoberbeças, mas teme.

[[v45-11-21]]

^<<v45-11-21,21>>^ Porque, se Deus não poupou os ramos naturais, teme  que te não poupe a ti também.

[[v45-11-22]]

^<<v45-11-22,22>>^ Considera pois a bondade e a severidade de Deus: para com os que caíram, severidade; mas para contigo, a benignidade de Deus, se permaneceres na sua benignidade; de outra maneira, também tu serás cortado.

[[v45-11-23]]

^<<v45-11-23,23>>^ E também eles, se não permanecerem na incredulidade, serão enxertados; porque poderoso é Deus para os tornar a enxertar.

[[v45-11-24]]

^<<v45-11-24,24>>^ Porque, se tu foste cortado do natural zambujeiro, e, contra a natureza, enxertado na boa oliveira, quanto mais esses, que são naturais, serão enxertados na sua própria oliveira!

[[v45-11-25]]

^<<v45-11-25,25>>^ Porque não quero, irmãos, que ignoreis este segredo (para que não presumais de vós mesmos): que o endurecimento veio em parte sobre Israel, até que a plenitude dos gentios haja entrado.

[[v45-11-26]]

^<<v45-11-26,26>>^ E assim todo o Israel será salvo, como está escrito: De Sião virá o Libertador, e desviará de Jacó as impiedades.

[[v45-11-27]]

^<<v45-11-27,27>>^ E este será  o meu concerto com eles, quando eu tirar os seus pecados.

[[v45-11-28]]

^<<v45-11-28,28>>^ Assim que, quanto ao evangelho, são  inimigos por causa de vós; mas, quanto à eleição, amados por causa dos pais.

[[v45-11-29]]

^<<v45-11-29,29>>^ Porque os dons e a vocação de Deus são  sem arrependimento.

[[v45-11-30]]

^<<v45-11-30,30>>^ Porque assim como vós também antigamente fostes desobedientes a Deus, mas agora alcançastes misericórdia pela desobediência deles,

[[v45-11-31]]

^<<v45-11-31,31>>^ Assim também estes agora foram desobedientes, para também alcançarem misericórdia pela misericórdia a vós demonstrada.

[[v45-11-32]]

^<<v45-11-32,32>>^ Porque Deus encerrou a todos debaixo da desobediência, para com todos usar de misericórdia.

[[v45-11-33]]

^<<v45-11-33,33>>^ Ó profundidade das riquezas, tanto da sabedoria, como da ciência de Deus! Quão insondáveis são  os seus juízos, e quão inescrutáveis os seus caminhos!

[[v45-11-34]]

^<<v45-11-34,34>>^ Por que quem compreendeu o intento do Senhor? ou quem foi seu conselheiro?

[[v45-11-35]]

^<<v45-11-35,35>>^ Ou quem lhe deu primeiro a ele, para que lhe seja recompensado?

[[v45-11-36]]

^<<v45-11-36,36>>^ Porque dele e por ele, e para ele, são  todas as coisas ; glória pois  a ele eternamente. Amém.

'''

xref:045-romanos/045-romanos-010.adoc#v45-10-0[&#60; Capítulo Anterior] | <<v45-11-0,Topo>> | xref:045-romanos/045-romanos-012.adoc#v45-12-0[Próximo Capítulo &#62;]