include::./index.adoc[]

[[v45-5-0]]
=== Romanos, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-5-1]]

^<<v45-5-1,1>>^ SENDO pois justificados pela fé, temos paz com Deus, por nosso Senhor Jesus Cristo;

[[v45-5-2]]

^<<v45-5-2,2>>^ Pelo qual também temos entrada pela fé a esta graça, na qual estamos firmes, e nos gloriamos na esperança da glória de Deus.

[[v45-5-3]]

^<<v45-5-3,3>>^ E não somente isto , mas também nos gloriamos nas tribulações; sabendo que a tribulação produz a paciência,

[[v45-5-4]]

^<<v45-5-4,4>>^ E a paciência a experiência, e a experiência a esperança.

[[v45-5-5]]

^<<v45-5-5,5>>^ E a esperança não traz confusão, porquanto o amor de Deus está derramado em nossos corações pelo Espírito Santo que nos foi dado.

[[v45-5-6]]

^<<v45-5-6,6>>^ Porque Cristo, estando nós ainda fracos, morreu a seu tempo pelos ímpios.

[[v45-5-7]]

^<<v45-5-7,7>>^ Porque apenas alguém morrerá por um justo; pois poderá ser que pelo bom alguém ouse morrer.

[[v45-5-8]]

^<<v45-5-8,8>>^ Mas Deus prova o seu amor para conosco, em que Cristo morreu por nós, sendo nós ainda pecadores.

[[v45-5-9]]

^<<v45-5-9,9>>^ Logo muito mais agora, sendo justificados pelo seu sangue, seremos por ele salvos da ira.

[[v45-5-10]]

^<<v45-5-10,10>>^ Porque se nós, sendo inimigos, fomos reconciliados com Deus pela morte de seu Filho, muito mais, estando já  reconciliados, seremos salvos pela sua vida.

[[v45-5-11]]

^<<v45-5-11,11>>^ E não somente isto , mas também nos gloriamos em Deus por nosso Senhor Jesus Cristo, pelo qual agora alcançamos a reconciliação.

[[v45-5-12]]

^<<v45-5-12,12>>^ Pelo que, como por um homem entrou o pecado no mundo, e pelo pecado a morte, assim também a morte passou a todos os homens por isso que todos pecaram.

[[v45-5-13]]

^<<v45-5-13,13>>^ Porque até à lei estava o pecado no mundo, mas o pecado não é imputado, não havendo lei.

[[v45-5-14]]

^<<v45-5-14,14>>^ No entanto a morte reinou desde Adão até Moisés, até sobre aqueles que não pecaram à semelhança da transgressão de Adão, o qual é a figura daquele que havia de vir.

[[v45-5-15]]

^<<v45-5-15,15>>^ Mas não é assim o dom gratuito como a ofensa. Porque, se pela ofensa de um morreram muitos, muito mais a graça de Deus e o dom pela graça, que é  dum só homem, Jesus Cristo, abundou sobre muitos.

[[v45-5-16]]

^<<v45-5-16,16>>^ E não foi assim o dom como a ofensa , por um só que pecou. Porque o juízo veio de uma só ofensa , na verdade, para condenação, mas o dom gratuito veio de muitas ofensas para justificação.

[[v45-5-17]]

^<<v45-5-17,17>>^ Porque, se pela ofensa de um só, a morte reinou por esse, muito mais os que recebem a abundância da graça, e do dom da justiça, reinarão em vida por um só — Jesus Cristo.

[[v45-5-18]]

^<<v45-5-18,18>>^ Pois assim como por uma só ofensa veio o juízo  sobre todos os homens para condenação, assim também por um só ato de justiça veio a graça  sobre todos os homens para justificação de vida.

[[v45-5-19]]

^<<v45-5-19,19>>^ Porque, como pela desobediência de um só homem, muitos foram feitos pecadores, assim pela obediência de um muitos serão feitos justos.

[[v45-5-20]]

^<<v45-5-20,20>>^ Veio, porém, a lei para que a ofensa abundasse; mas, onde o pecado abundou, superabundou a graça;

[[v45-5-21]]

^<<v45-5-21,21>>^ Para que, assim como o pecado reinou na morte, também a graça reinasse pela justiça para a vida eterna, por Jesus Cristo nosso Senhor.

'''

xref:045-romanos/045-romanos-004.adoc#v45-4-0[&#60; Capítulo Anterior] | <<v45-5-0,Topo>> | xref:045-romanos/045-romanos-006.adoc#v45-6-0[Próximo Capítulo &#62;]