include::./index.adoc[]

[[v45-2-0]]
=== Romanos, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-2-1]]

^<<v45-2-1,1>>^ PORTANTO, és inescusável quando julgas, ó homem, quem quer que sejas, porque te condenas a ti mesmo naquilo em que julgas a outro; pois tu, que julgas, fazes o mesmo.

[[v45-2-2]]

^<<v45-2-2,2>>^ E bem sabemos que o juízo de Deus é segundo a verdade sobre os que tais coisas  fazem.

[[v45-2-3]]

^<<v45-2-3,3>>^ E tu, ó homem, que julgas os que fazem tais coisas , cuidas que, fazendo-as tu, escaparás ao juízo de Deus?

[[v45-2-4]]

^<<v45-2-4,4>>^ Ou desprezas tu as riquezas da sua benignidade, e paciência e longanimidade, ignorando que a benignidade de Deus te leva ao arrependimento?

[[v45-2-5]]

^<<v45-2-5,5>>^ Mas, segundo a tua dureza e teu coração impenitente, entesouras ira para ti no dia da ira e da manifestação do juízo de Deus;

[[v45-2-6]]

^<<v45-2-6,6>>^ O qual recompensará cada um segundo as suas obras;

[[v45-2-7]]

^<<v45-2-7,7>>^ A saber: a vida eterna aos que, com perseverança em fazer bem, procuram glória, e honra e incorrupção;

[[v45-2-8]]

^<<v45-2-8,8>>^ Mas a indignação e a ira aos que são contenciosos, e desobedientes à verdade e obedientes à iniquidade;

[[v45-2-9]]

^<<v45-2-9,9>>^ Tribulação e angústia sobre toda a alma do homem que obra o mal; primeiramente do judeu e também do grego;

[[v45-2-10]]

^<<v45-2-10,10>>^ Glória, porém, e honra e paz a qualquer que obra o bem; primeiramente ao judeu e também ao grego;

[[v45-2-11]]

^<<v45-2-11,11>>^ Porque, para com Deus, não há acepção de pessoas.

[[v45-2-12]]

^<<v45-2-12,12>>^ Porque todos os que sem lei pecaram sem lei também perecerão; e todos os que sob a lei pecaram pela lei serão julgados.

[[v45-2-13]]

^<<v45-2-13,13>>^ Porque os que ouvem a lei não são  justos diante de Deus: mas os que praticam a lei hão de ser justificados.

[[v45-2-14]]

^<<v45-2-14,14>>^ Porque, quando os gentios, que não têm lei, fazem naturalmente as coisas que são da lei, não tendo eles lei, para si mesmos são lei;

[[v45-2-15]]

^<<v45-2-15,15>>^ Os quais mostram a obra da lei escrita em seus corações, testificando juntamente a sua consciência, e os seus pensamentos, quer acusando-os, quer defendendo-os;

[[v45-2-16]]

^<<v45-2-16,16>>^ No dia em que Deus há de julgar os segredos dos homens, por Jesus Cristo, segundo o meu evangelho.

[[v45-2-17]]

^<<v45-2-17,17>>^ Eis que tu que tens por sobrenome judeu, e repousas na lei, e te glorias em Deus;

[[v45-2-18]]

^<<v45-2-18,18>>^ E sabes a sua  vontade e aprovas as coisas excelentes, sendo instruído por lei;

[[v45-2-19]]

^<<v45-2-19,19>>^ E confias que és guia dos cegos, luz dos que estão em trevas,

[[v45-2-20]]

^<<v45-2-20,20>>^ Instruidor dos néscios, mestre de crianças, que tens a forma da ciência e da verdade na lei;

[[v45-2-21]]

^<<v45-2-21,21>>^ Tu, pois, que ensinas a outro, não te ensinas a ti mesmo? Tu, que pregas que não se deve furtar, furtas?

[[v45-2-22]]

^<<v45-2-22,22>>^ Tu, que dizes que não se deve adulterar, adulteras? Tu, que abominas os ídolos, cometes sacrilégio?

[[v45-2-23]]

^<<v45-2-23,23>>^ Tu, que te glorias na lei, desonras a Deus pela transgressão da lei?

[[v45-2-24]]

^<<v45-2-24,24>>^ Porque, como está escrito, o nome de Deus é blasfemado entre os gentios por causa de vós.

[[v45-2-25]]

^<<v45-2-25,25>>^ Porque a circuncisão é, na verdade, proveitosa, se tu guardares a lei; mas, se tu és transgressor da lei, a tua circuncisão se torna em incircuncisão.

[[v45-2-26]]

^<<v45-2-26,26>>^ Se, pois, a incircuncisão guardar os preceitos da lei, porventura a incircuncisão não será reputada como circuncisão?

[[v45-2-27]]

^<<v45-2-27,27>>^ E a incircuncisão que por natureza o é, se cumpre a lei, não te julgará porventura a ti , que pela letra e circuncisão és transgressor da lei?

[[v45-2-28]]

^<<v45-2-28,28>>^ Porque não é judeu o que o é exteriormente, nem é circuncisão a que o é exteriormente na carne.

[[v45-2-29]]

^<<v45-2-29,29>>^ Mas é  judeu o que o é no interior, e circuncisão a que é do coração, no espírito, não na  letra: cujo louvor não provém  dos homens, mas de Deus.

'''

xref:045-romanos/045-romanos-001.adoc#v45-1-0[&#60; Capítulo Anterior] | <<v45-2-0,Topo>> | xref:045-romanos/045-romanos-003.adoc#v45-3-0[Próximo Capítulo &#62;]