include::./index.adoc[]

[[v45-14-0]]
=== Romanos, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-14-1]]

^<<v45-14-1,1>>^ ORA, quanto ao que está enfermo na fé, recebei-o, não em contendas sobre dúvidas.

[[v45-14-2]]

^<<v45-14-2,2>>^ Porque um crê que de tudo se pode comer, e outro, que é fraco, come legumes.

[[v45-14-3]]

^<<v45-14-3,3>>^ O que come não despreze o que não come; e o que não come não julgue o que come; porque Deus o recebeu por seu.

[[v45-14-4]]

^<<v45-14-4,4>>^ Quem és tu, que julgas o servo alheio? Para seu próprio Senhor ele está em pé ou cai; mas estará firme; porque poderoso é Deus para o firmar.

[[v45-14-5]]

^<<v45-14-5,5>>^ Um faz diferença entre dia e dia, mas outro julga iguais  todos os dias. Cada um esteja inteiramente seguro em seu próprio ânimo.

[[v45-14-6]]

^<<v45-14-6,6>>^ Aquele que faz caso do dia, para o Senhor o faz. O que come, para o Senhor come, porque dá graças a Deus; e o que não come, para o Senhor não come, e dá graças a Deus.

[[v45-14-7]]

^<<v45-14-7,7>>^ Porque nenhum de nós vive para si, e nenhum morre para si.

[[v45-14-8]]

^<<v45-14-8,8>>^ Porque, se vivemos, para o Senhor vivemos; se morremos, para o Senhor morremos. De sorte que, ou vivamos ou morramos, somos do Senhor.

[[v45-14-9]]

^<<v45-14-9,9>>^ Foi para isto que morreu Cristo, e tornou a viver; para ser Senhor, tanto dos mortos, como dos vivos.

[[v45-14-10]]

^<<v45-14-10,10>>^ Mas tu, por que julgas teu irmão? Ou tu, também, por que desprezas teu irmão? Pois todos havemos de comparecer ante o tribunal de Cristo.

[[v45-14-11]]

^<<v45-14-11,11>>^ Porque está escrito: Pela minha vida, diz o Senhor: que  todo o joelho se dobrará diante de mim, e toda a língua confessará a Deus.

[[v45-14-12]]

^<<v45-14-12,12>>^ De maneira que cada um de nós dará conta de si mesmo a Deus.

[[v45-14-13]]

^<<v45-14-13,13>>^ Assim que não nos julguemos mais uns aos outros; antes seja o vosso propósito não pôr tropeço ou escândalo ao irmão.

[[v45-14-14]]

^<<v45-14-14,14>>^ Eu sei, e estou certo no Senhor Jesus que nenhuma coisa é  de si mesmo imunda a não ser para aquele que a tem por imunda; para esse é  imunda.

[[v45-14-15]]

^<<v45-14-15,15>>^ Mas, se por causa da comida se contrista teu irmão, já não andas conforme o amor. Não destruas por causa da tua comida aquele por quem Cristo morreu.

[[v45-14-16]]

^<<v45-14-16,16>>^ Não seja pois blasfemado o vosso bem;

[[v45-14-17]]

^<<v45-14-17,17>>^ Porque o reino de Deus não é comida nem bebida, mas justiça, e paz, e alegria no Espírito Santo.

[[v45-14-18]]

^<<v45-14-18,18>>^ Porque quem nisto serve a Cristo agradável é  a Deus e aceito aos homens.

[[v45-14-19]]

^<<v45-14-19,19>>^ Sigamos pois as coisas  que servem  para a paz e para a edificação de uns para com os outros.

[[v45-14-20]]

^<<v45-14-20,20>>^ Não destruas por causa da comida a obra de Deus. É verdade que tudo é limpo, mas mal vai para o homem que come com escândalo.

[[v45-14-21]]

^<<v45-14-21,21>>^ Bom é  não comer carne, nem beber vinho, nem fazer outras coisas  em que teu irmão tropece, ou se escandalize, ou se enfraqueça.

[[v45-14-22]]

^<<v45-14-22,22>>^ Tens tu fé? Tem- na  em ti mesmo diante de Deus. Bem-aventurado aquele que não se condena a si mesmo naquilo que aprova.

[[v45-14-23]]

^<<v45-14-23,23>>^ Mas aquele que tem dúvidas, se come está condenado, porque não come por fé; e tudo que não é  de fé é pecado.

'''

xref:045-romanos/045-romanos-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romanos/045-romanos-015.adoc#v45-15-0[Próximo Capítulo &#62;]