include::./index.adoc[]

[[v45-1-0]]
=== Romanos, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-1-1]]

^<<v45-1-1,1>>^ PAULO, servo de Jesus Cristo, chamado para  apóstolo, separado para o evangelho de Deus,

[[v45-1-2]]

^<<v45-1-2,2>>^ O qual antes havia prometido pelos seus profetas nas santas escrituras,

[[v45-1-3]]

^<<v45-1-3,3>>^ Acerca de seu Filho, que nasceu da descendência de Davi segundo a carne,

[[v45-1-4]]

^<<v45-1-4,4>>^ Declarado Filho de Deus em poder, segundo o Espírito de santificação, pela ressurreição dos mortos, — Jesus Cristo Nosso Senhor,

[[v45-1-5]]

^<<v45-1-5,5>>^ Pelo qual recebemos a graça e o apostolado, para a obediência da fé entre todas as gentes pelo seu nome,

[[v45-1-6]]

^<<v45-1-6,6>>^ Entre as quais sois também vós chamados para serdes  de Jesus Cristo.

[[v45-1-7]]

^<<v45-1-7,7>>^ A todos os que estais em Roma, amados de Deus, chamados santos: Graça e paz de Deus nosso pai, e do Senhor Jesus Cristo.

[[v45-1-8]]

^<<v45-1-8,8>>^ Primeiramente dou graças ao meu Deus por Jesus Cristo, acerca de vós todos, porque em todo o mundo é anunciada a vossa fé.

[[v45-1-9]]

^<<v45-1-9,9>>^ Porque Deus, a quem sirvo em meu espírito, no evangelho de seu Filho, me é testemunha de como incessantemente faço menção de vós,

[[v45-1-10]]

^<<v45-1-10,10>>^ Pedindo sempre em minhas orações que nalgum tempo, pela vontade de Deus, se me ofereça boa ocasião de ir ter convosco.

[[v45-1-11]]

^<<v45-1-11,11>>^ Porque desejo ver-vos, para vos comunicar algum dom espiritual, a fim de que sejais confortados;

[[v45-1-12]]

^<<v45-1-12,12>>^ Isto é : para que juntamente convosco eu seja consolado pela fé mútua, assim vossa como minha.

[[v45-1-13]]

^<<v45-1-13,13>>^ Não quero porém, irmãos, que ignoreis que muitas vezes propus ir ter convosco (mas até agora tenho sido impedido) para também ter entre vós algum fruto, como também entre os demais gentios.

[[v45-1-14]]

^<<v45-1-14,14>>^ Eu sou devedor, tanto a gregos como a bárbaros, tanto a sábios como a ignorantes.

[[v45-1-15]]

^<<v45-1-15,15>>^ E assim, quanto está em mim, estou pronto para também vos anunciar o evangelho, a vós que estais em Roma.

[[v45-1-16]]

^<<v45-1-16,16>>^ Porque não me envergonho do evangelho de Cristo, pois é o poder de Deus para salvação de todo aquele que crê; primeiro do judeu, e  também do grego.

[[v45-1-17]]

^<<v45-1-17,17>>^ Porque nele se descobre a justiça de Deus de fé em fé, como está escrito: Mas o justo viverá da fé.

[[v45-1-18]]

^<<v45-1-18,18>>^ Porque do céu se manifesta a ira de Deus sobre toda a impiedade e injustiça dos homens, que detêm a verdade em injustiça.

[[v45-1-19]]

^<<v45-1-19,19>>^ Porquanto o que de Deus se pode conhecer neles se manifesta, porque Deus lho manifestou.

[[v45-1-20]]

^<<v45-1-20,20>>^ Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder, como a sua divindade, se entendem, e claramente se veem pelas coisas que estão criadas, para que eles fiquem inescusáveis;

[[v45-1-21]]

^<<v45-1-21,21>>^ Porquanto, tendo conhecido a Deus, não o  glorificaram como Deus, nem lhe  deram graças, antes em seus discursos se desvaneceram, e o seu coração insensato se obscureceu.

[[v45-1-22]]

^<<v45-1-22,22>>^ Dizendo-se sábios, tornaram-se loucos.

[[v45-1-23]]

^<<v45-1-23,23>>^ E mudaram a glória do Deus incorruptível em semelhança da imagem de homem corruptível, e de aves, e de quadrúpedes, e de répteis.

[[v45-1-24]]

^<<v45-1-24,24>>^ Pelo que também Deus os entregou às concupiscências de seus corações, à imundícia, para desonrarem seus corpos entre si;

[[v45-1-25]]

^<<v45-1-25,25>>^ Pois mudaram a verdade de Deus em mentira, e honraram e serviram mais a criatura do que o Criador, que é  bendito eternamente. Amém.

[[v45-1-26]]

^<<v45-1-26,26>>^ Pelo que Deus os abandonou às paixões infames. Porque até as suas mulheres mudaram o uso natural, no contrário à natureza.

[[v45-1-27]]

^<<v45-1-27,27>>^ E, semelhantemente, também os varões, deixando o uso natural da mulher, se inflamaram em sua sensualidade uns para com os outros, varão com varão, cometendo torpeza e recebendo em si mesmos a recompensa que convinha ao seu erro.

[[v45-1-28]]

^<<v45-1-28,28>>^ E, como eles se não importaram de ter conhecimento de Deus, assim Deus os entregou a um sentimento perverso, para fazerem coisas que não convém;

[[v45-1-29]]

^<<v45-1-29,29>>^ Estando cheios de toda a iniquidade, prostituição, malícia, avareza, maldade; cheios de inveja, homicídio, contenda, engano, malignidade;

[[v45-1-30]]

^<<v45-1-30,30>>^ Sendo murmuradores, detratores, aborrecedores de Deus, injuriadores, soberbos, presunçosos, inventores de males, desobedientes aos pais e às mães;

[[v45-1-31]]

^<<v45-1-31,31>>^ Néscios, infiéis nos contratos, sem afeição natural, irreconciliáveis, sem misericórdia;

[[v45-1-32]]

^<<v45-1-32,32>>^ Os quais, conhecendo a justiça de Deus (que são dignos de morte os que tais coisas praticam), não somente as fazem, mas também consentem aos que as fazem.

'''

xref:044-atos/044-atos-028.adoc#v44-28-0[&#60; Capítulo Anterior] | <<v45-1-0,Topo>> | xref:045-romanos/045-romanos-002.adoc#v45-2-0[Próximo Capítulo &#62;]