include::./index.adoc[]

[[v45-6-0]]
=== Romanos, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v45-6-1]]

^<<v45-6-1,1>>^ QUE diremos pois? Permaneceremos no pecado, para que a graça abunde?

[[v45-6-2]]

^<<v45-6-2,2>>^ De modo nenhum. Nós, que estamos mortos para o pecado, como viveremos ainda nele?

[[v45-6-3]]

^<<v45-6-3,3>>^ Ou não sabeis que todos quantos fomos batizados em Jesus Cristo fomos batizados na sua morte?

[[v45-6-4]]

^<<v45-6-4,4>>^ De sorte que fomos sepultados com ele pelo batismo na morte; para que, como Cristo ressuscitou dos mortos, pela glória do Pai, assim andemos nós também em novidade de vida.

[[v45-6-5]]

^<<v45-6-5,5>>^ Porque, se fomos plantados juntamente com ele na semelhança da sua morte, também o seremos na da sua ressurreição;

[[v45-6-6]]

^<<v45-6-6,6>>^ Sabendo isto, que o nosso homem velho foi com ele  crucificado, para que o corpo do pecado seja desfeito, para que não sirvamos mais ao pecado.

[[v45-6-7]]

^<<v45-6-7,7>>^ Porque aquele que está morto está justificado do pecado.

[[v45-6-8]]

^<<v45-6-8,8>>^ Ora, se já  morremos com Cristo, cremos que também com ele viveremos;

[[v45-6-9]]

^<<v45-6-9,9>>^ Sabendo que, havendo Cristo ressuscitado dos mortos, já não morre: a morte não mais terá domínio sobre ele.

[[v45-6-10]]

^<<v45-6-10,10>>^ Pois, quanto a ter morrido, de uma vez morreu para o pecado, mas, quanto a viver, vive para Deus.

[[v45-6-11]]

^<<v45-6-11,11>>^ Assim também vós considerai-vos como mortos para o pecado, mas vivos para Deus em Cristo Jesus nosso Senhor.

[[v45-6-12]]

^<<v45-6-12,12>>^ Não reine portanto o pecado em vosso corpo mortal, para lhe obedecerdes em suas concupiscências;

[[v45-6-13]]

^<<v45-6-13,13>>^ Nem tão pouco apresenteis os vossos membros ao pecado por instrumentos de iniquidade; mas apresentai-vos a Deus, como vivos dentre mortos, e os vossos membros a Deus, como instrumentos de justiça.

[[v45-6-14]]

^<<v45-6-14,14>>^ Porque o pecado não terá domínio sobre vós, pois não estais debaixo da lei, mas debaixo da graça.

[[v45-6-15]]

^<<v45-6-15,15>>^ Pois quê? Pecaremos porque não estamos debaixo da lei, mas debaixo da graça? de modo nenhum.

[[v45-6-16]]

^<<v45-6-16,16>>^ Não sabeis vós que a quem vos apresentardes por servos para lhe obedecer, sois servos daquele a quem obedeceis, ou do pecado para a morte, ou da obediência para a justiça?

[[v45-6-17]]

^<<v45-6-17,17>>^ Mas graças a Deus que, tendo sido servos do pecado, obedecestes de coração à forma de doutrina a que fostes entregues.

[[v45-6-18]]

^<<v45-6-18,18>>^ E libertados do pecado, fostes feitos servos da justiça.

[[v45-6-19]]

^<<v45-6-19,19>>^ Falo como homem, pela fraqueza da vossa carne: pois que, assim como apresentastes os vossos membros para  servirem à imundícia, e à maldade, para a maldade, assim apresentai agora os vossos membros para  servirem à justiça para santificação.

[[v45-6-20]]

^<<v45-6-20,20>>^ Porque, quando éreis servos do pecado, estáveis livres da justiça.

[[v45-6-21]]

^<<v45-6-21,21>>^ E que fruto tínheis então das coisas de que agora vos envergonhais? porque o fim delas é a morte.

[[v45-6-22]]

^<<v45-6-22,22>>^ Mas agora, libertados do pecado, e feitos servos de Deus, tendes o vosso fruto para santificação, e por fim a vida eterna.

[[v45-6-23]]

^<<v45-6-23,23>>^ Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus nosso Senhor.

'''

xref:045-romanos/045-romanos-005.adoc#v45-5-0[&#60; Capítulo Anterior] | <<v45-6-0,Topo>> | xref:045-romanos/045-romanos-007.adoc#v45-7-0[Próximo Capítulo &#62;]