include::./index.adoc[]

[[v52-1-0]]
=== 1 Tessalonicenses, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v52-1-1]]

^<<v52-1-1,1>>^ PAULO, e Silvano, e Timóteo, à igreja dos tessalonicenses em Deus, o Pai, e no  Senhor Jesus Cristo; Graça e paz tenhais de Deus nosso Pai e do Senhor Jesus Cristo.

[[v52-1-2]]

^<<v52-1-2,2>>^ Sempre damos graças a Deus por vós todos, fazendo menção de vós em nossas orações.

[[v52-1-3]]

^<<v52-1-3,3>>^ Lembrando-nos sem cessar da obra da vossa fé, do trabalho da caridade, e da paciência da esperança em Nosso Senhor Jesus Cristo, diante de nosso Deus e Pai;

[[v52-1-4]]

^<<v52-1-4,4>>^ Sabendo, amados irmãos, que a vossa eleição é de Deus;

[[v52-1-5]]

^<<v52-1-5,5>>^ Porque o nosso evangelho não foi a vós somente em palavras, mas também em poder, e no Espírito Santo, e em muita certeza; como bem sabeis quais fomos entre vós, por amor de vós.

[[v52-1-6]]

^<<v52-1-6,6>>^ E vós fostes feitos nossos imitadores, e do Senhor, recebendo a palavra em muita tribulação, com gozo do Espírito Santo.

[[v52-1-7]]

^<<v52-1-7,7>>^ De maneira que fostes exemplo para todos os fiéis na Macedônia e Acaia.

[[v52-1-8]]

^<<v52-1-8,8>>^ Porque por vós soou a palavra do Senhor, não somente na Macedônia e Acaia, mas também em todos os lugares a vossa fé para com Deus se espalhou, de tal maneira que já dela  não temos necessidade de falar coisa alguma;

[[v52-1-9]]

^<<v52-1-9,9>>^ Porque eles mesmos anunciam de nós qual a entrada que tivemos para convosco, e como dos ídolos vos convertestes a Deus, para servir o Deus vivo e verdadeiro.

[[v52-1-10]]

^<<v52-1-10,10>>^ E esperar dos céus a seu Filho, a quem ressuscitou dos mortos, a saber , Jesus, que nos livra da ira futura.

'''

xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[&#60; Capítulo Anterior] | <<v52-1-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[Próximo Capítulo &#62;]