include::./index.adoc[]

[[v52-2-0]]
=== 1 Tessalonicenses, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v52-2-1]]

^<<v52-2-1,1>>^ PORQUE vós mesmos, irmãos, bem sabeis que a nossa entrada para convosco não foi vã;

[[v52-2-2]]

^<<v52-2-2,2>>^ Mas, havendo primeiro padecido, e sido agravados em Filipos, como sabeis, tornamo-nos ousados em nosso Deus, para vos falar o evangelho de Deus com grande combate.

[[v52-2-3]]

^<<v52-2-3,3>>^ Porque a nossa exortação não foi  com engano, nem com imundícia, nem com fraudulência;

[[v52-2-4]]

^<<v52-2-4,4>>^ Mas, como fomos aprovados de Deus para que o evangelho nos fosse confiado, assim falamos, não como para agradar aos homens, mas a Deus, que prova os nossos corações.

[[v52-2-5]]

^<<v52-2-5,5>>^ Porque, como bem sabeis, nunca usamos de palavras lisonjeiras, nem houve um pretexto de avareza; Deus é  testemunha;

[[v52-2-6]]

^<<v52-2-6,6>>^ E não buscamos glória dos homens, nem de vós, nem de outros, ainda que podíamos, como apóstolos de Cristo, ser-vos pesados;

[[v52-2-7]]

^<<v52-2-7,7>>^ Antes fomos brandos entre vós, como a ama que cria seus filhos.

[[v52-2-8]]

^<<v52-2-8,8>>^ Assim nós, sendo-vos tão afeiçoados, de boa vontade quiséramos comunicar-vos, não somente o evangelho de Deus, mas ainda as nossas próprias almas; porquanto nos éreis muito  queridos.

[[v52-2-9]]

^<<v52-2-9,9>>^ Porque bem vos lembrais, irmãos, do nosso trabalho e fadiga; pois, trabalhando noite e dia, para não sermos pesados a nenhum de vós, vos pregamos o evangelho de Deus.

[[v52-2-10]]

^<<v52-2-10,10>>^ Vós e Deus sois  testemunhas de quão santa, e justa, e irrepreensivelmente nos houvemos para convosco, os que crestes.

[[v52-2-11]]

^<<v52-2-11,11>>^ Assim como bem sabeis de que modo vos exortávamos e consolávamos, a cada um de vós, como o pai a seus filhos;

[[v52-2-12]]

^<<v52-2-12,12>>^ Para que vos conduzísseis dignamente para com Deus, que vos chama para o seu reino e glória.

[[v52-2-13]]

^<<v52-2-13,13>>^ Pelo que também damos sem cessar graças a Deus, pois, havendo recebido de nós a palavra da pregação de Deus, a recebestes, não como  palavra de homens, mas (segundo é, na verdade), como  palavra de Deus, a qual também opera em vós, os que crestes.

[[v52-2-14]]

^<<v52-2-14,14>>^ Porque vós, irmãos, haveis sido feitos imitadores das igrejas de Deus que na Judeia estão em Jesus Cristo; porquanto também padecestes de vossos próprios concidadãos o mesmo que os judeus lhes fizeram a eles,

[[v52-2-15]]

^<<v52-2-15,15>>^ Os quais também mataram o Senhor Jesus e os seus próprios profetas, e nos têm perseguido, e não agradam a Deus, e são contrários a todos os homens.

[[v52-2-16]]

^<<v52-2-16,16>>^ E nos impedem de pregar aos gentios as palavras da salvação, a fim de encherem sempre a medida de  seus pecados; mas a ira de Deus  caiu sobre eles até ao fim.

[[v52-2-17]]

^<<v52-2-17,17>>^ Nós, porém, irmãos, sendo privados de vós por um momento de tempo, de vista, mas não do coração, tanto mais procuramos com grande desejo ver o vosso rosto.

[[v52-2-18]]

^<<v52-2-18,18>>^ Pelo que bem quisemos uma e outra vez ir ter convosco, pelo menos eu, Paulo, mas Satanás no-lo impediu.

[[v52-2-19]]

^<<v52-2-19,19>>^ Porque, qual é a nossa esperança, ou gozo, ou coroa de glória? Porventura não o sois  vós também diante de nosso Senhor Jesus Cristo em sua vinda?

[[v52-2-20]]

^<<v52-2-20,20>>^ Na verdade vós sois a nossa glória e gozo.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[&#60; Capítulo Anterior] | <<v52-2-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[Próximo Capítulo &#62;]