include::./index.adoc[]

[[v18-5-0]]
=== Jó, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-5-1]]

^<<v18-5-1,1>>^ CHAMA agora; há alguém que te responda? E para qual dos santos te virarás?

[[v18-5-2]]

^<<v18-5-2,2>>^ Porque a ira destrói o louco; e o zelo mata o tolo.

[[v18-5-3]]

^<<v18-5-3,3>>^ Bem  vi eu o louco lançar raízes; mas logo amaldiçoei a sua habitação.

[[v18-5-4]]

^<<v18-5-4,4>>^ Seus filhos estão longe da salvação; e são despedaçados às portas, e não há quem os livre.

[[v18-5-5]]

^<<v18-5-5,5>>^ A sua messe a  devora o faminto, que até dentre os espinhos a tira; e  o salteador traga a sua fazenda.

[[v18-5-6]]

^<<v18-5-6,6>>^ Porque do pó não procede a aflição, nem da terra brota o trabalho.

[[v18-5-7]]

^<<v18-5-7,7>>^ Mas o homem nasce para o trabalho, como as faíscas das brasas se levantam para voar.

[[v18-5-8]]

^<<v18-5-8,8>>^ Mas quanto a mim eu buscaria a Deus, e a Ele dirigiria a minha fala.

[[v18-5-9]]

^<<v18-5-9,9>>^ Ele faz cousas tão  grandiosas, que se não podem esquadrinhar; e tantas  maravilhas que se não podem contar.

[[v18-5-10]]

^<<v18-5-10,10>>^ Ele dá a chuva sobre a terra, e envia água sobre os campos,

[[v18-5-11]]

^<<v18-5-11,11>>^ Para pôr os abatidos num  lugar alto; e para que os enlutados se exaltem na salvação.

[[v18-5-12]]

^<<v18-5-12,12>>^ Ele aniquila as imaginações dos astutos, para que as suas mãos não possam levar cousa alguma a efeito,

[[v18-5-13]]

^<<v18-5-13,13>>^ Ele apanha os sábios na sua própria  astúcia; e o conselho dos perversos se precipita.

[[v18-5-14]]

^<<v18-5-14,14>>^ Eles de dia encontram as trevas; e ao meio-dia andam como de noite, às apalpadelas.

[[v18-5-15]]

^<<v18-5-15,15>>^ Mas ao necessitado livra da espada da sua boca, e da mão do forte.

[[v18-5-16]]

^<<v18-5-16,16>>^ Assim há esperança para o pobre; e a iniquidade tapa a sua própria boca.

[[v18-5-17]]

^<<v18-5-17,17>>^ Eis que bem-aventurado é  o homem a quem Deus castiga; não desprezes, pois, o castigo do Todo-poderoso.

[[v18-5-18]]

^<<v18-5-18,18>>^ Porque ele faz a chaga, e ele mesmo a  liga; ele fere, e as suas mãos curam.

[[v18-5-19]]

^<<v18-5-19,19>>^ Em seis angústias te livrará; e na sétima o mal te não tocará.

[[v18-5-20]]

^<<v18-5-20,20>>^ Na fome te livrará da morte, e na guerra da violência da espada.

[[v18-5-21]]

^<<v18-5-21,21>>^ Do açoite da língua estarás abrigado; e não temerás a assolação, quando vier.

[[v18-5-22]]

^<<v18-5-22,22>>^ Da assolação e da fome te rirás, e os animais da terra não temerás.

[[v18-5-23]]

^<<v18-5-23,23>>^ Porque até com as pedras do campo terás a tua aliança; e os animais do campo estarão contigo.

[[v18-5-24]]

^<<v18-5-24,24>>^ E saberás que a tua tenda está  em paz; e visitarás a tua habitação, e nada te faltará.

[[v18-5-25]]

^<<v18-5-25,25>>^ Também saberás que se multiplicará a tua semente e a tua posteridade como a erva da terra.

[[v18-5-26]]

^<<v18-5-26,26>>^ Na velhice virás à sepultura, como se recolhe o feixe de trigo a seu tempo.

[[v18-5-27]]

^<<v18-5-27,27>>^ Eis que isto já o havemos inquirido, e  assim é; ouve-o, e medita nisso para teu bem.

'''

xref:018-jo/018-jo-004.adoc#v18-4-0[&#60; Capítulo Anterior] | <<v18-5-0,Topo>> | xref:018-jo/018-jo-006.adoc#v18-6-0[Próximo Capítulo &#62;]