include::./index.adoc[]

[[v18-19-0]]
=== Jó, 19
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-19-1]]

^<<v18-19-1,1>>^ RESPONDEU porém Jó, e disse:

[[v18-19-2]]

^<<v18-19-2,2>>^ Até quando entristecereis a minha alma, e me quebrantareis com palavras?

[[v18-19-3]]

^<<v18-19-3,3>>^ Já dez vezes me envergonhastes; vergonha não tendes de contra mim vos endurecerdes.

[[v18-19-4]]

^<<v18-19-4,4>>^ Embora haja eu, na verdade, errado, comigo ficará o meu erro.

[[v18-19-5]]

^<<v18-19-5,5>>^ Se deveras vos levantais contra mim, e me arguis pelo meu opróbrio,

[[v18-19-6]]

^<<v18-19-6,6>>^ Sabei agora que Deus é que  me transtornou, e com  a sua rede me cercou.

[[v18-19-7]]

^<<v18-19-7,7>>^ Eis que clamo: Violência! mas não sou ouvido; grito: Socorro! mas não há  justiça.

[[v18-19-8]]

^<<v18-19-8,8>>^ O meu caminho ele entrincheirou, e não posso passar; e nas minhas veredas pôs trevas.

[[v18-19-9]]

^<<v18-19-9,9>>^ Da minha honra me despojou; e tirou-me a coroa da minha cabeça.

[[v18-19-10]]

^<<v18-19-10,10>>^ Quebrou-me de todos os lados, e eu me vou; e arrancou a minha esperança, como a uma árvore.

[[v18-19-11]]

^<<v18-19-11,11>>^ E fez inflamar contra mim a sua ira, e me reputou para consigo como um de seus inimigos.

[[v18-19-12]]

^<<v18-19-12,12>>^ Juntas vieram as suas tropas, e prepararam contra mim o seu caminho, e se acamparam ao redor da minha tenda.

[[v18-19-13]]

^<<v18-19-13,13>>^ Pôs longe de mim a meus irmãos, e os que me conhecem deveras me estranharam.

[[v18-19-14]]

^<<v18-19-14,14>>^ Os meus parentes me  deixaram, e os meus conhecidos se esqueceram de mim.

[[v18-19-15]]

^<<v18-19-15,15>>^ Os meus domésticos e as minhas servas me reputaram como um estranho; vim a ser um estrangeiro aos seus olhos.

[[v18-19-16]]

^<<v18-19-16,16>>^ Chamei a meu criado, e ele me  não respondeu; cheguei  a suplicar com a minha boca.

[[v18-19-17]]

^<<v18-19-17,17>>^ O meu bafo se fez estranho a minha mulher, e a minha súplica aos filhos do meu corpo.

[[v18-19-18]]

^<<v18-19-18,18>>^ Até os rapazes me desprezam, e , levantando-me eu, falam contra mim.

[[v18-19-19]]

^<<v18-19-19,19>>^ Todos os homens do meu secreto conselho me abominam e até os que eu amava se tornaram contra mim.

[[v18-19-20]]

^<<v18-19-20,20>>^ Os meus ossos se apegaram à minha pele e à minha carne, e escapei só  com a pele dos meus dentes.

[[v18-19-21]]

^<<v18-19-21,21>>^ Compadecei-vos de mim, amigos meus, compadecei-vos de mim, porque a mão de Deus me tocou.

[[v18-19-22]]

^<<v18-19-22,22>>^ Por que me perseguis assim  como Deus, e da minha carne vos não fartais?

[[v18-19-23]]

^<<v18-19-23,23>>^ Quem me  dera agora, que as minhas palavras se escrevessem! Quem me  dera, que se gravassem num  livro!

[[v18-19-24]]

^<<v18-19-24,24>>^ E  que, com pena de ferro, e com  chumbo, para sempre fossem esculpidas na rocha!

[[v18-19-25]]

^<<v18-19-25,25>>^ Porque eu sei que  o meu Redentor vive, e que  por fim se levantará sobre a terra.

[[v18-19-26]]

^<<v18-19-26,26>>^ E depois de consumida a minha pele, ainda em minha carne verei a Deus.

[[v18-19-27]]

^<<v18-19-27,27>>^ Vê-lo-ei por mim mesmo, e os meus olhos, e não outros, o verão; e por isso  os meus rins se consomem dentro de mim.

[[v18-19-28]]

^<<v18-19-28,28>>^ Na verdade, que devíeis dizer: Por que o perseguimos? Pois a raiz da acusação se acha em mim.

[[v18-19-29]]

^<<v18-19-29,29>>^ Temei vós mesmos a espada; porque o furor traz os castigos da espada, para saberdes que há  um juízo.

'''

xref:018-jo/018-jo-018.adoc#v18-18-0[&#60; Capítulo Anterior] | <<v18-19-0,Topo>> | xref:018-jo/018-jo-020.adoc#v18-20-0[Próximo Capítulo &#62;]