include::./index.adoc[]

[[v18-11-0]]
=== Jó, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-11-1]]

^<<v18-11-1,1>>^ ENTÃO respondeu Sofar, o naamatita, e disse:

[[v18-11-2]]

^<<v18-11-2,2>>^ Porventura  não se dará resposta à multidão de palavras? E o homem falador será justificado?

[[v18-11-3]]

^<<v18-11-3,3>>^ Às tuas mentiras se hão de calar os homens? E zombarás tu sem que ninguém te envergonhe?

[[v18-11-4]]

^<<v18-11-4,4>>^ Pois tu disseste: A minha doutrina é pura, limpo sou aos teus olhos.

[[v18-11-5]]

^<<v18-11-5,5>>^ Mas, na verdade, oxalá que Deus falasse e abrisse os seus lábios contra ti,

[[v18-11-6]]

^<<v18-11-6,6>>^ E te fizesse saber os segredos da sabedoria, que é multíplice em eficácia; pelo que sabe que Deus exige de ti menos do que merece  a tua iniquidade.

[[v18-11-7]]

^<<v18-11-7,7>>^ Porventura  alcançarás os caminhos de Deus ou  chegarás à perfeição do Todo-poderoso?

[[v18-11-8]]

^<<v18-11-8,8>>^ Como  as alturas dos céus é  a sua sabedoria ; que poderás tu fazer? Mais profunda é ela do que o inferno, que poderás tu saber?

[[v18-11-9]]

^<<v18-11-9,9>>^ Mais comprida é  a sua medida do que a terra; e mais larga do que o mar.

[[v18-11-10]]

^<<v18-11-10,10>>^ Se ele destruir, e encerrar, ou juntar, quem o impedirá?

[[v18-11-11]]

^<<v18-11-11,11>>^ Porque ele conhece os homens vãos, e vê o vício; e não o terá em consideração?

[[v18-11-12]]

^<<v18-11-12,12>>^ Mas o homem vão é falto de entendimento; sim, o homem nasce como  a cria do jumento montês.

[[v18-11-13]]

^<<v18-11-13,13>>^ Se tu preparaste o teu coração, estende as tuas mãos para ele;

[[v18-11-14]]

^<<v18-11-14,14>>^ Se há  iniquidade na tua mão, lança-a para longe de ti, e  não deixes habitar a injustiça nas tuas tendas,

[[v18-11-15]]

^<<v18-11-15,15>>^ Porque então o teu rosto levantarás sem mácula; e estarás firme, e não temerás.

[[v18-11-16]]

^<<v18-11-16,16>>^ Porque te esquecerás dos trabalhos, e te lembrarás deles  como das águas que já passaram.

[[v18-11-17]]

^<<v18-11-17,17>>^ E a tua vida mais clara se levantará do que o meio-dia; ainda que haja trevas, será como a manhã.

[[v18-11-18]]

^<<v18-11-18,18>>^ E terás confiança, porque haverá esperança; olharás em volta, e  repousarás seguro.

[[v18-11-19]]

^<<v18-11-19,19>>^ E deitar-te-ás, e ninguém te espantará; muitos acariciarão o teu rosto.

[[v18-11-20]]

^<<v18-11-20,20>>^ Mas os olhos dos ímpios desfalecerão, e perecerá o seu refúgio; e a sua esperança será  o expirar da alma.

'''

xref:018-jo/018-jo-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-jo/018-jo-012.adoc#v18-12-0[Próximo Capítulo &#62;]