include::./index.adoc[]

[[v18-21-0]]
=== Jó, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-21-1]]

^<<v18-21-1,1>>^ RESPONDEU porém Jó, e disse:

[[v18-21-2]]

^<<v18-21-2,2>>^ Ouvi atentamente as minhas razões; e isto vos sirva de consolação.

[[v18-21-3]]

^<<v18-21-3,3>>^ Sofrei-me, e eu falarei; e, havendo eu falado, zombai.

[[v18-21-4]]

^<<v18-21-4,4>>^ Porventura  eu me queixo a algum  homem? Mas, ainda que assim fosse , por que se não angustiaria o meu espírito?

[[v18-21-5]]

^<<v18-21-5,5>>^ Olhai para mim, e pasmai; e ponde a mão sobre a boca,

[[v18-21-6]]

^<<v18-21-6,6>>^ Porque, quando me lembro disto , me perturbo, e a minha carne é sobressaltada de horror.

[[v18-21-7]]

^<<v18-21-7,7>>^ Por que razão vivem os ímpios, envelhecem, e ainda se esforçam em poder?

[[v18-21-8]]

^<<v18-21-8,8>>^ A sua semente se estabelece com eles perante a sua face, e os seus renovos perante os seus olhos.

[[v18-21-9]]

^<<v18-21-9,9>>^ As suas casas têm paz, sem temor; e a vara de Deus não está  sobre eles.

[[v18-21-10]]

^<<v18-21-10,10>>^ O seu touro gera, e não falha, pare a sua vaca, e não aborta.

[[v18-21-11]]

^<<v18-21-11,11>>^ Fazem sair as suas crianças, como a  um rebanho, e seus filhos andam saltando.

[[v18-21-12]]

^<<v18-21-12,12>>^ Levantam a voz, ao som  do tamboril e da harpa, e alegram-se ao som dos órgãos.

[[v18-21-13]]

^<<v18-21-13,13>>^ Na prosperidade gastam os seus dias, e num momento descem à sepultura.

[[v18-21-14]]

^<<v18-21-14,14>>^ E, todavia , dizem a Deus: Retira-te de nós; porque não desejamos ter conhecimento dos teus caminhos.

[[v18-21-15]]

^<<v18-21-15,15>>^ Quem é  o Todo-poderoso, para que nós o sirvamos? E que nos aproveitará que lhe façamos orações?

[[v18-21-16]]

^<<v18-21-16,16>>^ Vede porém  que o seu bem não está  na mão deles; esteja longe de mim o conselho dos ímpios!

[[v18-21-17]]

^<<v18-21-17,17>>^ Quantas vezes sucede que se apaga a candeia dos ímpios, e lhes sobrevém a sua destruição? E Deus  na sua ira lhes  reparte dores!

[[v18-21-18]]

^<<v18-21-18,18>>^ Porque  são como a palha diante do vento, e como a pragana, que arrebata o redemoinho.

[[v18-21-19]]

^<<v18-21-19,19>>^ Deus guarda a sua violência para seus filhos, e  lhe dá o pago, para que o conheça.

[[v18-21-20]]

^<<v18-21-20,20>>^ Seus olhos veem a sua ruína, e ele bebe do furor do Todo-poderoso.

[[v18-21-21]]

^<<v18-21-21,21>>^ Porque, que prazer teria na sua casa depois de si, cortando-se- lhe  o número dos seus meses?

[[v18-21-22]]

^<<v18-21-22,22>>^ Porventura a Deus se ensinaria ciência, a ele que julga os excelsos?

[[v18-21-23]]

^<<v18-21-23,23>>^ Um morre na força da sua plenitude, estando todo quieto e sossegado.

[[v18-21-24]]

^<<v18-21-24,24>>^ Os seus baldes estão cheios de leite, e os seus ossos estão regados de tutanos.

[[v18-21-25]]

^<<v18-21-25,25>>^ E outro morre, ao contrário, na amargura do seu coração, não havendo provado do bem.

[[v18-21-26]]

^<<v18-21-26,26>>^ Juntamente jazem no pó, e os bichos os cobrem.

[[v18-21-27]]

^<<v18-21-27,27>>^ Eis que conheço bem os vossos pensamentos; e os maus intentos com que  injustamente me fazeis violência.

[[v18-21-28]]

^<<v18-21-28,28>>^ Porque direis: Onde está  a casa do príncipe e onde a tenda em que morava o ímpio?

[[v18-21-29]]

^<<v18-21-29,29>>^ Porventura  o não perguntastes aos que passam pelo caminho, e não conheceis os seus sinais?

[[v18-21-30]]

^<<v18-21-30,30>>^ Que o mau é preservado para o dia da destruição, e arrebatado no dia do furor?

[[v18-21-31]]

^<<v18-21-31,31>>^ Quem acusará diante dele o seu caminho, e quem lhe dará o pago do que faz?

[[v18-21-32]]

^<<v18-21-32,32>>^ Finalmente é levado à sepultura, e vigia no túmulo.

[[v18-21-33]]

^<<v18-21-33,33>>^ Os torrões do vale lhe são doces, e ele arrasta após si a todos os homens; e antes dele havia inumeráveis.

[[v18-21-34]]

^<<v18-21-34,34>>^ Como pois me consolais em vão? Pois nas vossas respostas só há falsidade.

'''

xref:018-jo/018-jo-020.adoc#v18-20-0[&#60; Capítulo Anterior] | <<v18-21-0,Topo>> | xref:018-jo/018-jo-022.adoc#v18-22-0[Próximo Capítulo &#62;]