include::./index.adoc[]

[[v18-32-0]]
=== Jó, 32
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-32-1]]

^<<v18-32-1,1>>^ ENTÃO aqueles três homens cessaram de responder a Jó; porque era justo aos seus próprios  olhos.

[[v18-32-2]]

^<<v18-32-2,2>>^ E acendeu-se a ira de Eliú, filho de Baraquel o buzita, da família de Rão: contra Jó se acendeu a sua ira, porque se justificava a si mesmo, mais do que a Deus.

[[v18-32-3]]

^<<v18-32-3,3>>^ Também a sua ira se acendeu contra os seus três amigos: porque, não achando que responder, todavia condenavam a Jó.

[[v18-32-4]]

^<<v18-32-4,4>>^ Eliú porém esperou para falar a Jó, porquanto tinham mais idade do que ele.

[[v18-32-5]]

^<<v18-32-5,5>>^ Vendo pois Eliú que já  não havia resposta na boca daqueles três homens, a sua ira se acendeu.

[[v18-32-6]]

^<<v18-32-6,6>>^ E respondeu Eliú, filho de Baraquel o buzita, e disse: Eu sou  de menos idade, e vós sois  idosos; arreceei-me e temi de vos declarar a minha opinião.

[[v18-32-7]]

^<<v18-32-7,7>>^ Dizia eu: Falem os dias, e a multidão dos anos ensine a sabedoria.

[[v18-32-8]]

^<<v18-32-8,8>>^ Na verdade, há um espírito no homem, e a inspiração do Todo-poderoso os faz entendidos.

[[v18-32-9]]

^<<v18-32-9,9>>^ Os grandes não são os sábios, nem os velhos entendem o que é reto.

[[v18-32-10]]

^<<v18-32-10,10>>^ Pelo que digo: Dai-me ouvidos, e  também eu declararei a minha opinião.

[[v18-32-11]]

^<<v18-32-11,11>>^ Eis que aguardei as vossas palavras, e  dei ouvidos às vossas considerações, até que buscásseis razões.

[[v18-32-12]]

^<<v18-32-12,12>>^ Atentando pois para vós, eis que nenhum de vós há que possa convencer a Jó, nem  que responda às suas razões:

[[v18-32-13]]

^<<v18-32-13,13>>^ Para que não digais: Achamos a sabedoria, Deus o derribou, e  não homem algum.

[[v18-32-14]]

^<<v18-32-14,14>>^ Ora ele não dirigiu contra mim palavra alguma, nem lhe responderei com as vossas palavras.

[[v18-32-15]]

^<<v18-32-15,15>>^ Estão pasmados, não respondem mais, faltam-lhes as palavras.

[[v18-32-16]]

^<<v18-32-16,16>>^ Esperei pois, mas não falam; porque já pararam, e  não respondem mais.

[[v18-32-17]]

^<<v18-32-17,17>>^ Também eu responderei pela minha parte; também eu declararei a minha opinião.

[[v18-32-18]]

^<<v18-32-18,18>>^ Porque estou cheio de palavras; o meu  espírito me constrange.

[[v18-32-19]]

^<<v18-32-19,19>>^ Eis que o meu ventre é  como o mosto, sem respiradouro, e  virá a arrebentar, como odres novos.

[[v18-32-20]]

^<<v18-32-20,20>>^ Falarei, e respirarei; abrirei os meus lábios, e responderei.

[[v18-32-21]]

^<<v18-32-21,21>>^ Oxalá eu não faça acepção de pessoas, nem use de lisonjas com o homem!

[[v18-32-22]]

^<<v18-32-22,22>>^ Porque não sei usar de lisonjas; em breve me levaria o meu Criador.

'''

xref:018-jo/018-jo-031.adoc#v18-31-0[&#60; Capítulo Anterior] | <<v18-32-0,Topo>> | xref:018-jo/018-jo-033.adoc#v18-33-0[Próximo Capítulo &#62;]