include::./index.adoc[]

[[v18-29-0]]
=== Jó, 29
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-29-1]]

^<<v18-29-1,1>>^ E PROSSEGUINDO Jó em sua parábola, disse:

[[v18-29-2]]

^<<v18-29-2,2>>^ Ah! quem me dera ser como eu fui nos meses passados, como nos dias em que  Deus me guardava!

[[v18-29-3]]

^<<v18-29-3,3>>^ Quando fazia resplandecer a sua candeia sobre a minha cabeça, e  eu com a sua luz caminhava pelas  trevas;

[[v18-29-4]]

^<<v18-29-4,4>>^ Como era nos dias da minha mocidade, quando o segredo de Deus estava sobre a minha tenda;

[[v18-29-5]]

^<<v18-29-5,5>>^ Quando o Todo-poderoso ainda estava  comigo, e  os meus meninos em redor de mim.

[[v18-29-6]]

^<<v18-29-6,6>>^ Quando lavava os meus passos em manteiga, e da rocha me corriam ribeiros de azeite;

[[v18-29-7]]

^<<v18-29-7,7>>^ Quando saía para a porta da cidade, e  na praça fazia preparar a minha cadeira.

[[v18-29-8]]

^<<v18-29-8,8>>^ Os moços me viam, e se escondiam, e os idosos se levantavam e  se punham em pé;

[[v18-29-9]]

^<<v18-29-9,9>>^ Os príncipes continham as suas  palavras, e punham a mão sobre a sua boca;

[[v18-29-10]]

^<<v18-29-10,10>>^ A voz dos chefes se escondia; e a sua língua se pegava ao seu paladar;

[[v18-29-11]]

^<<v18-29-11,11>>^ Ouvindo- me  algum ouvido, me tinha por bem-aventurado; vendo- me  algum olho, dava testemunho de mim;

[[v18-29-12]]

^<<v18-29-12,12>>^ Porque eu livrava o miserável, que clamava, como também o órfão que não tinha quem o socorresse.

[[v18-29-13]]

^<<v18-29-13,13>>^ A bênção do que ia perecendo vinha sobre mim, e eu fazia que rejubilasse o coração da viúva.

[[v18-29-14]]

^<<v18-29-14,14>>^ Cobria-me de justiça, e ela me servia de vestido; como manto e diadema era  o meu juízo.

[[v18-29-15]]

^<<v18-29-15,15>>^ Eu era o olho do cego, e os pés do coxo;

[[v18-29-16]]

^<<v18-29-16,16>>^ Dos necessitados era pai, e as causas de que eu não tinha conhecimento inquiria com diligência;

[[v18-29-17]]

^<<v18-29-17,17>>^ E quebrava os queixais do perverso, e dos seus dentes tirava a presa.

[[v18-29-18]]

^<<v18-29-18,18>>^ E dizia: No meu ninho expirarei, e multiplicarei os meus dias como a areia.

[[v18-29-19]]

^<<v18-29-19,19>>^ A minha raiz se estendia junto às águas, e o orvalho fazia assento sobre os meus ramos;

[[v18-29-20]]

^<<v18-29-20,20>>^ A minha honra se renovava em mim, e o meu arco se reforçava na minha mão.

[[v18-29-21]]

^<<v18-29-21,21>>^ Ouvindo-me esperavam, e em silêncio atendiam ao meu conselho.

[[v18-29-22]]

^<<v18-29-22,22>>^ Acabada a minha palavra, não replicavam, e minhas razões destilavam sobre eles;

[[v18-29-23]]

^<<v18-29-23,23>>^ Porque me esperavam como à chuva; e abriam a sua boca, como à chuva, tardia.

[[v18-29-24]]

^<<v18-29-24,24>>^ Se  me ria para eles, não o criam, e não faziam abater a luz do meu rosto;

[[v18-29-25]]

^<<v18-29-25,25>>^ Se eu escolhia o seu caminho, assentava-me como chefe, e habitava como rei entre as suas tropas, como aquele que consola os que pranteiam.

'''

xref:018-jo/018-jo-028.adoc#v18-28-0[&#60; Capítulo Anterior] | <<v18-29-0,Topo>> | xref:018-jo/018-jo-030.adoc#v18-30-0[Próximo Capítulo &#62;]