include::./index.adoc[]

[[v18-2-0]]
=== Jó, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-2-1]]

^<<v18-2-1,1>>^ E, VINDO outro dia, em que os filhos de Deus vieram apresentar-se perante o Senhor, veio também Satanás entre eles apresentar-se perante o Senhor.

[[v18-2-2]]

^<<v18-2-2,2>>^ Então o Senhor disse a Satanás: Donde vens? E respondeu Satanás ao Senhor, e disse: De rodear a terra, e passear por ela.

[[v18-2-3]]

^<<v18-2-3,3>>^ E disse o Senhor a Satanás: Observaste o meu servo Jó? Porque ninguém há  na terra semelhante a ele, homem sincero e reto, temente a Deus, desviando-se do mal, e que ainda retém a sua sinceridade, havendo-me tu incitado contra ele, para o consumir sem causa.

[[v18-2-4]]

^<<v18-2-4,4>>^ Então Satanás respondeu ao Senhor, e disse: Pele por pele, e tudo quanto o homem tem dará pela sua vida.

[[v18-2-5]]

^<<v18-2-5,5>>^ Estende, porém, a tua mão, e toca-lhe nos ossos, e na carne, e verás  se não blasfema de ti na tua face!

[[v18-2-6]]

^<<v18-2-6,6>>^ E disse o Senhor a Satanás: Eis que ele está  na tua mão; poupa, porém, a sua vida.

[[v18-2-7]]

^<<v18-2-7,7>>^ Então saiu Satanás da presença do Senhor, e feriu a Jó duma chaga maligna, desde a planta do pé até ao alto da cabeça.

[[v18-2-8]]

^<<v18-2-8,8>>^ E Jó, tomando um pedaço de telha para raspar com ele as feridas , assentou-se no meio da cinza.

[[v18-2-9]]

^<<v18-2-9,9>>^ Então sua mulher lhe disse: Ainda reténs a tua sinceridade? amaldiçoa a Deus, e morre.

[[v18-2-10]]

^<<v18-2-10,10>>^ Mas ele lhe disse: Como fala qualquer doida, assim falas tu; receberemos o bem de Deus, e não receberíamos o mal? Em tudo isto não pecou Jó com os seus lábios.

[[v18-2-11]]

^<<v18-2-11,11>>^ Ouvindo pois três amigos de Jó todo este mal que tinha vindo sobre ele, vieram cada um do seu lugar: Elifaz o temanita, e Bildade o suíta, e Sofar o naamatita; e concertaram juntamente virem condoer-se dele, e consolá-lo.

[[v18-2-12]]

^<<v18-2-12,12>>^ E, levantando de longe os seus olhos e não o conhecendo, levantaram a sua voz e choraram; e rasgando cada um o seu manto, sobre as suas cabeças lançaram pó ao ar.

[[v18-2-13]]

^<<v18-2-13,13>>^ E se assentaram juntamente com ele na terra, sete dias e sete noites; e nenhum lhe dizia palavra alguma, porque viam que a dor era muito grande.

'''

xref:018-jo/018-jo-001.adoc#v18-1-0[&#60; Capítulo Anterior] | <<v18-2-0,Topo>> | xref:018-jo/018-jo-003.adoc#v18-3-0[Próximo Capítulo &#62;]