include::./index.adoc[]

[[v18-34-0]]
=== Jó, 34
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-34-1]]

^<<v18-34-1,1>>^ RESPONDEU mais Eliú, e disse:

[[v18-34-2]]

^<<v18-34-2,2>>^ Ouvi, vós, sábios, as minhas razões; e vós, entendidos, inclinai os ouvidos para mim.

[[v18-34-3]]

^<<v18-34-3,3>>^ Porque o ouvido prova as palavras, como o paladar prova a comida.

[[v18-34-4]]

^<<v18-34-4,4>>^ O que é direito escolhamos para nós; e  conheçamos entre nós o que é  bom.

[[v18-34-5]]

^<<v18-34-5,5>>^ Porque Jó disse: Sou justo, e Deus tirou o meu direito.

[[v18-34-6]]

^<<v18-34-6,6>>^ Apesar do meu direito, sou considerado mentiroso; a minha ferida é incurável, embora eu esteja sem transgressão.

[[v18-34-7]]

^<<v18-34-7,7>>^ Que homem há  como Jó, que bebe a zombaria como água?

[[v18-34-8]]

^<<v18-34-8,8>>^ E caminha em companhia dos que obram a iniquidade, e anda com homens ímpios?

[[v18-34-9]]

^<<v18-34-9,9>>^ Porque disse: De nada aproveita ao homem o comprazer-se em Deus.

[[v18-34-10]]

^<<v18-34-10,10>>^ Pelo que vós, homens de entendimento, escutai-me longe de Deus a impiedade, e do Todo-poderoso a perversidade!

[[v18-34-11]]

^<<v18-34-11,11>>^ Porque, segundo  a obra do homem, ele lhe paga; e faz que cada um ache segundo o seu caminho.

[[v18-34-12]]

^<<v18-34-12,12>>^ Também, na verdade, Deus não procede impiamente; nem o Todo-poderoso perverte o juízo.

[[v18-34-13]]

^<<v18-34-13,13>>^ Quem lhe entregou o governo  da terra? E quem dispôs a todo o mundo?

[[v18-34-14]]

^<<v18-34-14,14>>^ Se ele pusesse o seu coração contra o homem, e recolhesse para si o seu espírito e o seu fôlego,

[[v18-34-15]]

^<<v18-34-15,15>>^ Toda a carne juntamente expiraria, e o homem voltaria para o pó.

[[v18-34-16]]

^<<v18-34-16,16>>^ Se pois há em ti  entendimento, ouve isto; inclina os ouvidos à voz do meu discurso.

[[v18-34-17]]

^<<v18-34-17,17>>^ Porventura  o que aborrecesse o direito governaria? E quererás tu condenar aquele que é justo e poderoso?

[[v18-34-18]]

^<<v18-34-18,18>>^ Ou dir-se-á a um rei: Oh! Belial? Ou aos príncipes: Oh! ímpios?

[[v18-34-19]]

^<<v18-34-19,19>>^ Quanto menos àquele , que não faz acepção das pessoas de príncipes, nem estima o rico mais do que o pobre; porque todos são obra de suas mãos.

[[v18-34-20]]

^<<v18-34-20,20>>^ Eles num momento morrem; e até  à meia-noite os povos são perturbados, e passam, e os poderosos são tomados sem mão.

[[v18-34-21]]

^<<v18-34-21,21>>^ Porque os seus olhos estão  sobre os caminhos de cada um, e ele vê todos os seus passos.

[[v18-34-22]]

^<<v18-34-22,22>>^ Não há  trevas nem sombra de morte, onde se escondam os que obram a iniquidade.

[[v18-34-23]]

^<<v18-34-23,23>>^ Porque não precisa considerar muito no homem para o fazer ir a juízo diante de Deus.

[[v18-34-24]]

^<<v18-34-24,24>>^ Quebranta os fortes, sem que se possa inquirir, e põe outros em seu lugar.

[[v18-34-25]]

^<<v18-34-25,25>>^ Ele conhece pois as suas obras; de noite os transtorna, e ficam moídos.

[[v18-34-26]]

^<<v18-34-26,26>>^ Ele bate-lhes como ímpios que são  à vista de quem os contempla;

[[v18-34-27]]

^<<v18-34-27,27>>^ Porquanto se desviaram dele, e não compreenderam nenhum de seus caminhos,

[[v18-34-28]]

^<<v18-34-28,28>>^ Para fazer que o clamor do pobre subisse até ele, e que ouvisse o clamor dos aflitos.

[[v18-34-29]]

^<<v18-34-29,29>>^ Se ele aquietar, quem então inquietará? Se encobrir o rosto, quem então o poderá contemplar, seja para com um povo, seja para com um homem só ?

[[v18-34-30]]

^<<v18-34-30,30>>^ Para que o homem hipócrita nunca mais  reine, e não haja laços no povo.

[[v18-34-31]]

^<<v18-34-31,31>>^ Na verdade, quem disse a Deus: Sofri, não pecarei mais;

[[v18-34-32]]

^<<v18-34-32,32>>^ O que não vejo, ensina-mo tu; se fiz alguma  maldade, nunca mais a  hei de fazer

[[v18-34-33]]

^<<v18-34-33,33>>^ Virá  de ti como há de ser a recompensa, para que tu a desprezes? Faze tu pois, e não eu, a escolha; que é logo o que sabes? Fala.

[[v18-34-34]]

^<<v18-34-34,34>>^ Os homens de entendimento dirão comigo, e o varão sábio que me ouvir:

[[v18-34-35]]

^<<v18-34-35,35>>^ Jó falou sem ciência; e às suas palavras falta prudência.

[[v18-34-36]]

^<<v18-34-36,36>>^ Pai meu! provado seja Jó até ao fim, pelas suas respostas próprias de homens malignos.

[[v18-34-37]]

^<<v18-34-37,37>>^ Porque ao seu pecado acrescenta a transgressão; entre nós bate as palmas, e multiplica contra Deus as suas razões.

'''

xref:018-jo/018-jo-033.adoc#v18-33-0[&#60; Capítulo Anterior] | <<v18-34-0,Topo>> | xref:018-jo/018-jo-035.adoc#v18-35-0[Próximo Capítulo &#62;]