include::./index.adoc[]

[[v18-8-0]]
=== Jó, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-8-1]]

^<<v18-8-1,1>>^ ENTÃO respondeu Bildade, o suíta, e disse:

[[v18-8-2]]

^<<v18-8-2,2>>^ Até quando falarás tais cousas  e as razões da tua boca serão  qual vento impetuoso?

[[v18-8-3]]

^<<v18-8-3,3>>^ Porventura  perverteria Deus o direito, e perverteria o Todo-poderoso a justiça?

[[v18-8-4]]

^<<v18-8-4,4>>^ Se teus filhos pecaram contra ele, também ele os lançou na mão da sua transgressão.

[[v18-8-5]]

^<<v18-8-5,5>>^ Mas , se tu de madrugada buscares a Deus, e ao Todo-poderoso pedires misericórdia.

[[v18-8-6]]

^<<v18-8-6,6>>^ Se fores  puro e reto, certamente logo despertará por ti, e restaurará a morada da tua justiça.

[[v18-8-7]]

^<<v18-8-7,7>>^ O teu princípio, na verdade, terá sido pequeno, mas o teu último estado  crescerá em extremo.

[[v18-8-8]]

^<<v18-8-8,8>>^ Porque, eu te peço, pergunta agora às gerações passadas, e prepara-te para a inquirição de seus pais.

[[v18-8-9]]

^<<v18-8-9,9>>^ Porque nós somos  de ontem, e nada sabemos; porquanto nossos dias sobre a terra são  como a sombra.

[[v18-8-10]]

^<<v18-8-10,10>>^ Porventura  não te ensinarão eles, e  não te falarão, e do seu coração não tirarão razões?

[[v18-8-11]]

^<<v18-8-11,11>>^ Porventura  sobe o junco sem lodo? Ou  cresce a espadana sem água?

[[v18-8-12]]

^<<v18-8-12,12>>^ Estando ainda na sua verdura, e ainda  não cortada, todavia antes de qualquer outra  erva se seca.

[[v18-8-13]]

^<<v18-8-13,13>>^ Assim são  as veredas de todos quantos se esquecem de Deus; e a esperança do hipócrita perecerá.

[[v18-8-14]]

^<<v18-8-14,14>>^ A sua esperança fica frustrada, e a sua confiança será como  a teia de aranha.

[[v18-8-15]]

^<<v18-8-15,15>>^ Encostar-se-á à sua casa, e ela não se terá firme; ampará-la-á, e ela não ficará em pé.

[[v18-8-16]]

^<<v18-8-16,16>>^ Está sumarento antes que venha  o sol, e os seus renovos saem sobre o seu jardim;

[[v18-8-17]]

^<<v18-8-17,17>>^ As suas raízes se entrelaçam junto à fonte, para o pedregal atenta.

[[v18-8-18]]

^<<v18-8-18,18>>^ Desaparecendo ele do seu lugar, negá-lo-á este, dizendo : Nunca te vi.

[[v18-8-19]]

^<<v18-8-19,19>>^ Eis que este é  alegria do seu caminho, e outros brotarão do pó.

[[v18-8-20]]

^<<v18-8-20,20>>^ Eis que Deus não rejeitará ao reto; nem toma pela mão aos malfeitores;

[[v18-8-21]]

^<<v18-8-21,21>>^ Até que de riso te encha a boca, e os teus lábios de louvor.

[[v18-8-22]]

^<<v18-8-22,22>>^ Teus aborrecedores se vestirão de confusão, e a tenda dos ímpios não existirá mais.

'''

xref:018-jo/018-jo-007.adoc#v18-7-0[&#60; Capítulo Anterior] | <<v18-8-0,Topo>> | xref:018-jo/018-jo-009.adoc#v18-9-0[Próximo Capítulo &#62;]