include::./index.adoc[]

[[v18-27-0]]
=== Jó, 27
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-27-1]]

^<<v18-27-1,1>>^ E PROSSEGUINDO Jó em  sua parábola, disse:

[[v18-27-2]]

^<<v18-27-2,2>>^ Vive Deus, que desviou a minha causa, e o Todo-poderoso, que amargurou a minha alma.

[[v18-27-3]]

^<<v18-27-3,3>>^ Enquanto em mim houver  alento, e o sopro de Deus no meu nariz,

[[v18-27-4]]

^<<v18-27-4,4>>^ Não falarão os meus lábios iniquidade, nem a minha língua pronunciará engano.

[[v18-27-5]]

^<<v18-27-5,5>>^ Longe de mim que eu vos justifique; até que eu expire, nunca apartarei de mim a minha sinceridade.

[[v18-27-6]]

^<<v18-27-6,6>>^ À minha justiça me apegarei e não a largarei; não me remorderá o meu coração em toda a minha vida.

[[v18-27-7]]

^<<v18-27-7,7>>^ Seja como o ímpio o meu inimigo, e o que se levantar contra mim como o perverso.

[[v18-27-8]]

^<<v18-27-8,8>>^ Porque qual será  a esperança do hipócrita, havendo sido avaro, quando Deus lhe  arrancar a sua alma?

[[v18-27-9]]

^<<v18-27-9,9>>^ Porventura , Deus ouvirá o seu clamor, sobrevindo-lhe a tribulação?

[[v18-27-10]]

^<<v18-27-10,10>>^ Ou  deleitar-se-á no Todo-poderoso, ou  invocará a Deus em todo o tempo?

[[v18-27-11]]

^<<v18-27-11,11>>^ Ensinar-vos-ei o que é concernente à mão de Deus, e  não vos  encobrirei o que está  com o Todo-poderoso.

[[v18-27-12]]

^<<v18-27-12,12>>^ Eis que todos vós já  vistes isso; por que pois vos desvaneceis na vossa  vaidade?

[[v18-27-13]]

^<<v18-27-13,13>>^ Eis qual será da parte de Deus a porção do homem ímpio, e a herança, que  os tiranos receberão do Todo-poderoso:

[[v18-27-14]]

^<<v18-27-14,14>>^ Se os seus filhos se multiplicarem, será  para a espada, e os seus renovos se não fartarão de pão.

[[v18-27-15]]

^<<v18-27-15,15>>^ Os que ficarem dele, na morte serão enterrados, e as suas viúvas não chorarão.

[[v18-27-16]]

^<<v18-27-16,16>>^ Se amontoar prata como pó, e aparelhar vestidos como lodo;

[[v18-27-17]]

^<<v18-27-17,17>>^ Ele os aparelhará, mas o justo os vestirá, e o inocente repartirá a prata.

[[v18-27-18]]

^<<v18-27-18,18>>^ Ele edifica a sua casa como a traça, e como o guarda que  faz a cabana.

[[v18-27-19]]

^<<v18-27-19,19>>^ Rico se deita, e não será recolhido; seus olhos abre, e ele não será.

[[v18-27-20]]

^<<v18-27-20,20>>^ Pavores se apoderam dele como águas; de noite o arrebatará a tempestade.

[[v18-27-21]]

^<<v18-27-21,21>>^ O vento oriental o levará, e ir-se-á; varrê-lo-á com ímpeto do seu lugar.

[[v18-27-22]]

^<<v18-27-22,22>>^ E Deus  lançará isto  sobre ele, e não o  poupará; irá fugindo da sua mão.

[[v18-27-23]]

^<<v18-27-23,23>>^ Cada um  baterá contra ele as palmas das mãos, e do seu lugar o assobiará.

'''

xref:018-jo/018-jo-026.adoc#v18-26-0[&#60; Capítulo Anterior] | <<v18-27-0,Topo>> | xref:018-jo/018-jo-028.adoc#v18-28-0[Próximo Capítulo &#62;]