include::./index.adoc[]

[[v18-42-0]]
=== Jó, 42
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-42-1]]

^<<v18-42-1,1>>^ ENTÃO respondeu Jó ao Senhor, e disse:

[[v18-42-2]]

^<<v18-42-2,2>>^ Bem sei eu que tudo podes, e nenhum dos teus pensamentos pode ser impedido.

[[v18-42-3]]

^<<v18-42-3,3>>^ Quem é  aquele, dizes tu , que sem conhecimento encobre o conselho? Por isso falei do que não entendia; cousas que para mim eram maravilhosíssimas, e que eu não compreendia.

[[v18-42-4]]

^<<v18-42-4,4>>^ Escuta-me, pois, e eu falarei; eu te perguntarei, e tu ensina-me.

[[v18-42-5]]

^<<v18-42-5,5>>^ Com o ouvir dos meus ouvidos ouvi, mas agora te veem os meus olhos.

[[v18-42-6]]

^<<v18-42-6,6>>^ Por isso me  abomino e me arrependo no pó e na cinza.

[[v18-42-7]]

^<<v18-42-7,7>>^ Sucedeu pois que, acabando o Senhor de dizer a Jó aquelas palavras, o Senhor disse a Elifaz, o temanita: A minha ira se acendeu contra ti, e contra os teus dois amigos; porque não dissestes de mim o que era  reto, como o meu servo Jó.

[[v18-42-8]]

^<<v18-42-8,8>>^ Tomai pois sete bezerros e sete carneiros, e ide ao meu servo Jó, e oferecei holocaustos por vós, e o meu servo Jó orará por vós; porque deveras a ele aceitarei, para que eu vos não trate conforme a vossa  loucura; porque vós não falastes de mim o que era  reto como o meu servo Jó.

[[v18-42-9]]

^<<v18-42-9,9>>^ Então foram Elifaz, o temanita e Bildade, o suíta, e Sofar, o naamatita, e fizeram como o Senhor lhes dissera; e o Senhor aceitou a face de Jó.

[[v18-42-10]]

^<<v18-42-10,10>>^ E o Senhor virou o cativeiro de Jó, quando orava pelos seus amigos; e o Senhor acrescentou a Jó outro tanto em dobro a tudo quanto dantes  possuía.

[[v18-42-11]]

^<<v18-42-11,11>>^ Então vieram a ele todos os seus irmãos e todas as suas irmãs e todos quantos dantes o conheceram, e comeram com ele pão em sua casa, e se condoeram dele, e o consolaram de todo o mal que o Senhor lhe havia enviado; e cada um  deles lhe deu uma  peça de dinheiro, e cada um  um pendente de ouro.

[[v18-42-12]]

^<<v18-42-12,12>>^ E assim  abençoou o Senhor o último estado de Jó, mais do que o primeiro; porque teve catorze mil ovelhas, e seis mil camelos, e mil juntas de bois, e mil jumentas.

[[v18-42-13]]

^<<v18-42-13,13>>^ Também teve sete filhos e três filhas.

[[v18-42-14]]

^<<v18-42-14,14>>^ E chamou o nome da primeira Jemima, e o nome da outra Cássia, e o nome da terceira Quéren-Hapuque.

[[v18-42-15]]

^<<v18-42-15,15>>^ E em toda a terra não se acharam mulheres tão formosas como as filhas de Jó; e seu pai lhes deu herança entre seus irmãos.

[[v18-42-16]]

^<<v18-42-16,16>>^ E depois disto viveu Jó cento e quarenta anos; e viu a seus filhos, e aos filhos de seus filhos, até à quarta geração.

[[v18-42-17]]

^<<v18-42-17,17>>^ Então morreu Jó, velho e farto de dias.

'''

xref:018-jo/018-jo-041.adoc#v18-41-0[&#60; Capítulo Anterior] | <<v18-42-0,Topo>> | xref:019-salmos/019-salmos-001.adoc#v19-1-0[Próximo Capítulo &#62;]