include::./index.adoc[]

[[v18-31-0]]
=== Jó, 31
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-31-1]]

^<<v18-31-1,1>>^ FIZ concerto com os meus olhos; como pois os fixaria numa virgem?

[[v18-31-2]]

^<<v18-31-2,2>>^ Porque qual seria  a parte de Deus vinda de cima, ou a herança do Todo-poderoso desde as alturas?

[[v18-31-3]]

^<<v18-31-3,3>>^ Porventura  não é a perdição para o perverso, o desastre para os que obram iniquidade?

[[v18-31-4]]

^<<v18-31-4,4>>^ Ou não vê ele os meus caminhos, e não conta todos os meus passos?

[[v18-31-5]]

^<<v18-31-5,5>>^ Se andei com vaidade, e se  o meu pé se apressou para o engano

[[v18-31-6]]

^<<v18-31-6,6>>^ (Pese-me em balanças fiéis, e saberá Deus a minha sinceridade);

[[v18-31-7]]

^<<v18-31-7,7>>^ Se os meus passos se desviaram do caminho, e se o meu coração segue os meus olhos, e se às minhas mãos se apegou alguma cousa,

[[v18-31-8]]

^<<v18-31-8,8>>^ Então semeie eu e outro coma, e seja a minha descendência arrancada até à raiz.

[[v18-31-9]]

^<<v18-31-9,9>>^ Se o meu coração se deixou seduzir por uma mulher, ou se eu andei rondando à porta do meu próximo,

[[v18-31-10]]

^<<v18-31-10,10>>^ Então moa minha mulher para outro, e outros se encurvem sobre ela.

[[v18-31-11]]

^<<v18-31-11,11>>^ Porque isso seria uma infâmia, e delito pertencente  aos juízes.

[[v18-31-12]]

^<<v18-31-12,12>>^ Porque é fogo que consome até à perdição, e desarraigaria toda a minha renda.

[[v18-31-13]]

^<<v18-31-13,13>>^ Se desprezei o direito do meu servo ou da minha serva, quando eles contendiam comigo,

[[v18-31-14]]

^<<v18-31-14,14>>^ Então que faria eu quando Deus se levantasse? E, inquirindo a causa , que lhe responderia?

[[v18-31-15]]

^<<v18-31-15,15>>^ Aquele que me formou no ventre não o fez também  a ele? Ou não nos formou do mesmo modo  na madre?

[[v18-31-16]]

^<<v18-31-16,16>>^ Se retive o que os pobres desejavam, ou fiz desfalecer os olhos da viúva;

[[v18-31-17]]

^<<v18-31-17,17>>^ Ou só comi o meu bocado, e o órfão não comeu dele

[[v18-31-18]]

^<<v18-31-18,18>>^ (Porque desde a minha mocidade cresceu comigo como com seu  pai, e o guiei desde o ventre da minha mãe);

[[v18-31-19]]

^<<v18-31-19,19>>^ Se a alguém vi perecer por falta de vestido, e ao necessitado por não ter coberta;

[[v18-31-20]]

^<<v18-31-20,20>>^ Se os seus lombos me não abençoaram, se ele não se aquentava com as peles dos meus cordeiros;

[[v18-31-21]]

^<<v18-31-21,21>>^ Se eu levantei a minha mão contra o órfão, porque na porta via a minha ajuda,

[[v18-31-22]]

^<<v18-31-22,22>>^ Então caia do ombro a minha espádua, e quebre-se o meu braço desde o osso.

[[v18-31-23]]

^<<v18-31-23,23>>^ Porque o castigo de Deus era  para mim um assombro, e eu não podia suportar a sua grandeza.

[[v18-31-24]]

^<<v18-31-24,24>>^ Se no ouro pus a minha esperança, ou disse ao ouro fino: Tu és  a minha confiança;

[[v18-31-25]]

^<<v18-31-25,25>>^ Se me alegrei de que era muita a minha fazenda, e de que a minha mão tinha alcançado muito;

[[v18-31-26]]

^<<v18-31-26,26>>^ Se olhei para o sol, quando resplandecia, ou para a lua, caminhando gloriosa,

[[v18-31-27]]

^<<v18-31-27,27>>^ E o meu coração se deixou enganar em oculto, e a minha boca beijou a minha mão,

[[v18-31-28]]

^<<v18-31-28,28>>^ Também isto seria  delito pertencente  ao juiz; pois assim  negaria a Deus que está  em cima.

[[v18-31-29]]

^<<v18-31-29,29>>^ Se me alegrei da desgraça do que me tem ódio, e se eu exultei quando o mal o achou

[[v18-31-30]]

^<<v18-31-30,30>>^ (Também não deixei pecar o meu paladar, desejando a sua morte com maldição);

[[v18-31-31]]

^<<v18-31-31,31>>^ Se a gente da minha tenda não disse: Ah! quem se não terá saciado com a sua carne!

[[v18-31-32]]

^<<v18-31-32,32>>^ O estrangeiro não passava a noite na rua; as minhas portas abria ao viandante.

[[v18-31-33]]

^<<v18-31-33,33>>^ Se, como Adão encobri as minhas transgressões, ocultando o meu delito no meu seio;

[[v18-31-34]]

^<<v18-31-34,34>>^ Trema eu perante uma grande multidão, e o desprezo das famílias me apavore, e eu me cale, e não saia da porta.

[[v18-31-35]]

^<<v18-31-35,35>>^ Ah! quem me dera um que me ouvisse! Eis que o meu intento é que  o Todo-poderoso me responda, e que o meu adversário escreva um livro.

[[v18-31-36]]

^<<v18-31-36,36>>^ Por certo que o levaria sobre o meu ombro, sobre mim o ataria como coroa.

[[v18-31-37]]

^<<v18-31-37,37>>^ O número dos meus passos lhe mostraria; como príncipe me chegaria a ele.

[[v18-31-38]]

^<<v18-31-38,38>>^ Se a minha terra clamar contra mim, e se os seus regos juntamente chorarem;

[[v18-31-39]]

^<<v18-31-39,39>>^ Se comi a sua novidade sem dinheiro, e sufoquei a alma dos seus donos.

[[v18-31-40]]

^<<v18-31-40,40>>^ Por trigo me  produza cardos, e por cevada joio. Acabaram-se as palavras de Jó.

'''

xref:018-jo/018-jo-030.adoc#v18-30-0[&#60; Capítulo Anterior] | <<v18-31-0,Topo>> | xref:018-jo/018-jo-032.adoc#v18-32-0[Próximo Capítulo &#62;]