include::./index.adoc[]

[[v18-41-0]]
=== Jó, 41
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-41-1]]

^<<v18-41-1,1>>^ PODERÁS pescar com anzol o leviatã, ou ligarás a sua língua com a corda?

[[v18-41-2]]

^<<v18-41-2,2>>^ Podes pôr uma corda no seu nariz, ou com um espinho furarás a sua queixada?

[[v18-41-3]]

^<<v18-41-3,3>>^ Porventura  multiplicará as suas suplicações para contigo? Ou  brandamente te falará?

[[v18-41-4]]

^<<v18-41-4,4>>^ Fará ele concertos contigo, ou  o tomarás tu por escravo para sempre?

[[v18-41-5]]

^<<v18-41-5,5>>^ Brincarás com ele, como se fora um passarinho, ou o prenderás para tuas meninas?

[[v18-41-6]]

^<<v18-41-6,6>>^ Os teus  companheiros farão dele um banquete, ou  o repartirão entre os negociantes?

[[v18-41-7]]

^<<v18-41-7,7>>^ Encherás a sua pele de ganchos, ou a sua cabeça de arpéus de pescadores?

[[v18-41-8]]

^<<v18-41-8,8>>^ Põe a tua mão sobre ele, lembra-te da peleja, e  nunca mais tal  intentarás.

[[v18-41-9]]

^<<v18-41-9,9>>^ Eis que a sua esperança falhará: porventura  nenhum à sua vista será derribado?

[[v18-41-10]]

^<<v18-41-10,10>>^ Ninguém há tão  atrevido, que a despertá-lo se atreva ; quem pois é aquele que ousa  erguer-se diante de mim?

[[v18-41-11]]

^<<v18-41-11,11>>^ Quem primeiro me deu, para que eu haja de retribuir- lhe? Pois  o que está  debaixo de todos os céus é meu.

[[v18-41-12]]

^<<v18-41-12,12>>^ Não me calarei a respeito dos seus membros, nem da relação das suas  forças, nem da graça da sua compostura.

[[v18-41-13]]

^<<v18-41-13,13>>^ Quem descobriria a superfície do seu vestido? quem entrará entre as suas queixadas dobradas?

[[v18-41-14]]

^<<v18-41-14,14>>^ Quem abriria as portas do seu rosto? Pois  em roda dos seus dentes está  o terror.

[[v18-41-15]]

^<<v18-41-15,15>>^ As suas  fortes escamas são  excelentíssimas, cada uma fechada como  com selo apertado.

[[v18-41-16]]

^<<v18-41-16,16>>^ Uma à outra se chega tão  perto, que nem um assopro passa por entre elas.

[[v18-41-17]]

^<<v18-41-17,17>>^ Umas às outras se ligam; tanto  aderem entre si, que não se podem separar,

[[v18-41-18]]

^<<v18-41-18,18>>^ Cada um dos seus espirros faz resplandecer a luz, e os seus olhos são  como as pestanas da alva.

[[v18-41-19]]

^<<v18-41-19,19>>^ Da sua boca saem tochas; faíscas de fogo saltam dela.

[[v18-41-20]]

^<<v18-41-20,20>>^ Do seu nariz procede fumo, como duma  panela fervente, ou duma  grande caldeira.

[[v18-41-21]]

^<<v18-41-21,21>>^ O seu hálito faria acender os carvões; e da sua boca sai chama.

[[v18-41-22]]

^<<v18-41-22,22>>^ No seu pescoço pousa a força; perante ele até  a tristeza salta de prazer.

[[v18-41-23]]

^<<v18-41-23,23>>^ Os músculos da sua carne estão pegados entre si ; cada um está firme nele, e nenhum se move.

[[v18-41-24]]

^<<v18-41-24,24>>^ O seu coração é firme como uma pedra e firme como a mó de baixo.

[[v18-41-25]]

^<<v18-41-25,25>>^ Levantando-se ele, tremem os valentes; em razão dos seus  abalos se purificam.

[[v18-41-26]]

^<<v18-41-26,26>>^ Se alguém lhe tocar com a espada, essa  não poderá penetrar, nem lança, dardo ou frecha.

[[v18-41-27]]

^<<v18-41-27,27>>^ Ele reputa o ferro palha, e o cobre pau podre.

[[v18-41-28]]

^<<v18-41-28,28>>^ A seta o não fará fugir; as pedras das fundas se lhe tornam em restolho.

[[v18-41-29]]

^<<v18-41-29,29>>^ As pedras atiradas são para ele como arestas, ri-se do brandir da lança.

[[v18-41-30]]

^<<v18-41-30,30>>^ Debaixo de si tem  conchas pontiagudas; estende-se sobre  cousas pontiagudas como  na lama.

[[v18-41-31]]

^<<v18-41-31,31>>^ As profundezas faz ferver, como uma panela; torna o mar como quando os unguentos fervem.

[[v18-41-32]]

^<<v18-41-32,32>>^ Após ele alumia o caminho; parece o abismo tornado em brancura de cãs.

[[v18-41-33]]

^<<v18-41-33,33>>^ Na terra não há cousa que se lhe possa comparar, pois  foi feito para estar sem pavor.

[[v18-41-34]]

^<<v18-41-34,34>>^ Todo o alto vê; é  rei sobre todos os filhos de animais  altivos.

'''

xref:018-jo/018-jo-040.adoc#v18-40-0[&#60; Capítulo Anterior] | <<v18-41-0,Topo>> | xref:018-jo/018-jo-042.adoc#v18-42-0[Próximo Capítulo &#62;]