include::./index.adoc[]

[[v18-28-0]]
=== Jó, 28
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-28-1]]

^<<v18-28-1,1>>^ NA verdade, há veios  donde se extrai a prata, e para o ouro lugar em que  o derretem.

[[v18-28-2]]

^<<v18-28-2,2>>^ O ferro tira-se da terra, e da  pedra se funde o metal.

[[v18-28-3]]

^<<v18-28-3,3>>^ Ele pôs fim às trevas, e toda a extremidade ele esquadrinha; as pedras da escuridão e da sombra da morte.

[[v18-28-4]]

^<<v18-28-4,4>>^ Trasborda o ribeiro até ao que junto dele habita, de maneira que se não pode passar a pé; então  intervém o homem, e as águas  se vão.

[[v18-28-5]]

^<<v18-28-5,5>>^ A terra, donde procede o pão, embaixo é revolvida como por fogo.

[[v18-28-6]]

^<<v18-28-6,6>>^ As suas pedras são o lugar da safira, e têm pós de ouro.

[[v18-28-7]]

^<<v18-28-7,7>>^ Essa vereda a ignora a ave de rapina, e não a viram os olhos da gralha.

[[v18-28-8]]

^<<v18-28-8,8>>^ Nunca a pisaram filhos de animais altivos, nem o feroz leão passou por ela.

[[v18-28-9]]

^<<v18-28-9,9>>^ Ele estende a sua mão contra o rochedo, e  revolve os montes desde as suas raízes.

[[v18-28-10]]

^<<v18-28-10,10>>^ Dos rochedos faz sair rios, e o seu olho descobre todas as cousas preciosas.

[[v18-28-11]]

^<<v18-28-11,11>>^ Os rios tapa, e nem uma gota sai deles, e tira para a luz o que estava  escondido.

[[v18-28-12]]

^<<v18-28-12,12>>^ Mas onde se achará a sabedoria? E onde está o lugar da inteligência?

[[v18-28-13]]

^<<v18-28-13,13>>^ O homem não lhe conhece o valor; não se acha na terra dos viventes.

[[v18-28-14]]

^<<v18-28-14,14>>^ O abismo diz: Não está em mim; e o mar diz: Ela  não está  comigo.

[[v18-28-15]]

^<<v18-28-15,15>>^ Não se dará por ela ouro fino , nem se pesará prata em câmbio dela.

[[v18-28-16]]

^<<v18-28-16,16>>^ Nem se pode comprar por ouro fino  de Ofir, nem  pelo precioso ônix, nem pela safira.

[[v18-28-17]]

^<<v18-28-17,17>>^ Com ela se não pode comparar o ouro ou o cristal; nem se trocará por joia de ouro fino.

[[v18-28-18]]

^<<v18-28-18,18>>^ Ela faz esquecer o coral e as pérolas; porque a aquisição da sabedoria é  melhor que a dos  rubis.

[[v18-28-19]]

^<<v18-28-19,19>>^ Não se lhe igualará o topázio da Etiópia, nem se pode comprar por ouro puro.

[[v18-28-20]]

^<<v18-28-20,20>>^ Donde pois vem a sabedoria, e onde está  o lugar da inteligência?

[[v18-28-21]]

^<<v18-28-21,21>>^ Porque está encoberta aos olhos de todo o vivente, e oculta às aves do céu.

[[v18-28-22]]

^<<v18-28-22,22>>^ A perdição e a morte dizem: Ouvimos com os nossos ouvidos a sua fama.

[[v18-28-23]]

^<<v18-28-23,23>>^ Deus entende o seu caminho, e ele sabe o seu lugar.

[[v18-28-24]]

^<<v18-28-24,24>>^ Porque ele vê as extremidades da terra; e  vê tudo o que há  debaixo dos céus.

[[v18-28-25]]

^<<v18-28-25,25>>^ Quando deu peso ao vento, e tomou a medida das águas.

[[v18-28-26]]

^<<v18-28-26,26>>^ Quando prescreveu uma lei para a chuva e caminho para o relâmpago dos trovões;

[[v18-28-27]]

^<<v18-28-27,27>>^ Então a viu e a manifestou; estabeleceu-a e também a esquadrinhou.

[[v18-28-28]]

^<<v18-28-28,28>>^ Mas disse ao homem: Eis que o temor do Senhor é a sabedoria, e apartar-se do mal é a inteligência.

'''

xref:018-jo/018-jo-027.adoc#v18-27-0[&#60; Capítulo Anterior] | <<v18-28-0,Topo>> | xref:018-jo/018-jo-029.adoc#v18-29-0[Próximo Capítulo &#62;]