include::./index.adoc[]

[[v18-13-0]]
=== Jó, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-13-1]]

^<<v18-13-1,1>>^ EIS que tudo isto  viram os meus olhos, e  os meus ouvidos o  ouviram e entenderam.

[[v18-13-2]]

^<<v18-13-2,2>>^ Como vós o  sabeis, o sei eu também: não vos sou inferior.

[[v18-13-3]]

^<<v18-13-3,3>>^ Mas  eu falarei ao Todo-poderoso; e quero defender-me perante Deus.

[[v18-13-4]]

^<<v18-13-4,4>>^ Vós porém sois  inventores de mentiras, e  vós todos médicos que não valem nada.

[[v18-13-5]]

^<<v18-13-5,5>>^ Oxalá vos calásseis de todo, que isso  seria a vossa sabedoria!

[[v18-13-6]]

^<<v18-13-6,6>>^ Ouvi agora a minha defesa, e escutai os argumentos dos meus lábios.

[[v18-13-7]]

^<<v18-13-7,7>>^ Porventura  por Deus falareis perversidade e por ele enunciareis mentiras?

[[v18-13-8]]

^<<v18-13-8,8>>^ Fareis aceitação da sua pessoa? Contendereis por Deus?

[[v18-13-9]]

^<<v18-13-9,9>>^ Ser-vos-ia bom, se ele vos esquadrinhasse? Ou  zombareis dele, como se zomba de qualquer homem?

[[v18-13-10]]

^<<v18-13-10,10>>^ Certamente vos repreenderá, se em oculto fizerdes distinção de pessoas.

[[v18-13-11]]

^<<v18-13-11,11>>^ Porventura  não vos espantará a sua alteza? E não cairá sobre vós o seu temor?

[[v18-13-12]]

^<<v18-13-12,12>>^ As vossas memórias são  como a cinza: as vossas alturas como alturas de lodo.

[[v18-13-13]]

^<<v18-13-13,13>>^ Calai-vos perante mim, e falarei eu, e venha sobre mim o que vier.

[[v18-13-14]]

^<<v18-13-14,14>>^ Por que razão  tomaria eu a minha carne com os meus dentes, e poria a minha vida na minha mão?

[[v18-13-15]]

^<<v18-13-15,15>>^ Ainda que  ele me mate, nele esperarei; contudo os meus caminhos defenderei diante dele.

[[v18-13-16]]

^<<v18-13-16,16>>^ Também isto será  a minha salvação, porque o ímpio não virá perante ele.

[[v18-13-17]]

^<<v18-13-17,17>>^ Ouvi com atenção as minhas razões, e com os vossos ouvidos a minha demonstração.

[[v18-13-18]]

^<<v18-13-18,18>>^ Eis que já tenho ordenado a minha causa, e  sei que serei achado justo.

[[v18-13-19]]

^<<v18-13-19,19>>^ Quem é  o que contenderá comigo? Se eu agora me calasse, renderia o espírito.

[[v18-13-20]]

^<<v18-13-20,20>>^ Duas cousas  somente não faças para comigo; então me não esconderei do teu rosto:

[[v18-13-21]]

^<<v18-13-21,21>>^ Desvia a tua mão para longe de mim, e não me espante o teu terror.

[[v18-13-22]]

^<<v18-13-22,22>>^ Chama, pois, e eu responderei; ou eu falarei, e tu responde-me.

[[v18-13-23]]

^<<v18-13-23,23>>^ Quantas culpas e pecados tenho eu? Notifica-me a minha transgressão e o meu pecado.

[[v18-13-24]]

^<<v18-13-24,24>>^ Por que escondes o teu rosto, e me tens por teu inimigo?

[[v18-13-25]]

^<<v18-13-25,25>>^ Porventura  quebrantarás a folha arrebatada pelo vento ? E perseguirás o restolho seco?

[[v18-13-26]]

^<<v18-13-26,26>>^ Por que escreves contra mim cousas amargas e me fazes herdar as culpas da minha mocidade?

[[v18-13-27]]

^<<v18-13-27,27>>^ Também pões os meus pés em cepos, e observas todos os meus caminhos, e  marcas os sinais dos meus pés,

[[v18-13-28]]

^<<v18-13-28,28>>^ Apesar de eu ser como uma cousa podre que se consome, e  como o vestido, ao qual rói a traça.

'''

xref:018-jo/018-jo-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-jo/018-jo-014.adoc#v18-14-0[Próximo Capítulo &#62;]