include::./index.adoc[]

[[v18-39-0]]
=== Jó, 39
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-39-1]]

^<<v18-39-1,1>>^ SABES tu o tempo em que as cabras monteses têm os filhos, ou  consideraste as dores das cervas?

[[v18-39-2]]

^<<v18-39-2,2>>^ Contarás os meses que  cumprem, ou sabes o tempo do seu parto?

[[v18-39-3]]

^<<v18-39-3,3>>^ Elas encurvam-se, para terem seus filhos, e  lançam de si as suas dores.

[[v18-39-4]]

^<<v18-39-4,4>>^ Seus filhos enrijam, crescem com o trigo, saem, e nunca mais tornam para elas.

[[v18-39-5]]

^<<v18-39-5,5>>^ Quem despediu livre o jumento montês, e quem soltou as prisões ao jumento bravo,

[[v18-39-6]]

^<<v18-39-6,6>>^ Ao qual dei o ermo por casa, e a terra salgada por moradas?

[[v18-39-7]]

^<<v18-39-7,7>>^ Ri-se do arruído da cidade; não ouve os muitos gritos do exator.

[[v18-39-8]]

^<<v18-39-8,8>>^ O que descobre nos montes é o seu pasto, e anda buscando tudo que está verde.

[[v18-39-9]]

^<<v18-39-9,9>>^ Querer-te-á servir, o unicórnio ou ficará na tua cavalariça?

[[v18-39-10]]

^<<v18-39-10,10>>^ Ou amarrarás o unicórnio ao rego com uma corda, ou estorroará após ti os vales?

[[v18-39-11]]

^<<v18-39-11,11>>^ Ou confiarás nele, por ser grande a sua força, ou deixarás a seu cargo o teu trabalho?

[[v18-39-12]]

^<<v18-39-12,12>>^ Ou fiarás dele que te torne o que semeaste e o recolha na  tua eira?

[[v18-39-13]]

^<<v18-39-13,13>>^ Bate alegre as asas a avestruz, que tem penas de cegonha,

[[v18-39-14]]

^<<v18-39-14,14>>^ Ela deixa os seus ovos na terra, e os aquenta no pó.

[[v18-39-15]]

^<<v18-39-15,15>>^ E se esquece de que algum  pé os pode pisar, ou de que podem calcá-los os animais do campo.

[[v18-39-16]]

^<<v18-39-16,16>>^ Endurece-se para com seus filhos, como se não fossem  seus; debalde é seu trabalho, porquanto está sem temor.

[[v18-39-17]]

^<<v18-39-17,17>>^ Porque Deus a privou de sabedoria, e não lhe repartiu entendimento.

[[v18-39-18]]

^<<v18-39-18,18>>^ A seu tempo se levanta ao alto; ri-se do cavalo, e do que vai montado nele.

[[v18-39-19]]

^<<v18-39-19,19>>^ Ou darás tu força ao cavalo, ou revestirás o seu pescoço de crinas?

[[v18-39-20]]

^<<v18-39-20,20>>^ Ou espantá-lo-ás, como ao gafanhoto? Terrível é  o fogoso respirar das suas ventas.

[[v18-39-21]]

^<<v18-39-21,21>>^ Escarva a terra, e folga na sua  força, e  sai ao encontro dos armados.

[[v18-39-22]]

^<<v18-39-22,22>>^ Ri-se do temor, e não se espanta, e não torna atrás por causa da espada.

[[v18-39-23]]

^<<v18-39-23,23>>^ Contra ele rangem a aljava, o ferro flamante da lança e do dardo.

[[v18-39-24]]

^<<v18-39-24,24>>^ Sacudindo-se, e removendo-se, escarva a terra, e não faz caso do som da buzina.

[[v18-39-25]]

^<<v18-39-25,25>>^ Ao soar das buzinas diz: Eia! E de longe cheira a guerra, e  o trovão dos príncipes, e o alarido.

[[v18-39-26]]

^<<v18-39-26,26>>^ Ou voa o gavião pela tua inteligência, estendendo as suas asas para o sul?

[[v18-39-27]]

^<<v18-39-27,27>>^ Ou se remonta a águia ao teu mandado, e põe no alto o seu ninho?

[[v18-39-28]]

^<<v18-39-28,28>>^ Nas penhas mora e habita; no cume das penhas, e nos lugares seguros.

[[v18-39-29]]

^<<v18-39-29,29>>^ Dali descobre a presa; seus olhos a avistam desde longe.

[[v18-39-30]]

^<<v18-39-30,30>>^ Seus filhos chupam o sangue; e onde há mortos, ela aí está.

'''

xref:018-jo/018-jo-038.adoc#v18-38-0[&#60; Capítulo Anterior] | <<v18-39-0,Topo>> | xref:018-jo/018-jo-040.adoc#v18-40-0[Próximo Capítulo &#62;]