include::./index.adoc[]

[[v18-20-0]]
=== Jó, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-20-1]]

^<<v18-20-1,1>>^ ENTÃO respondeu Sofar, o naamatita, e disse:

[[v18-20-2]]

^<<v18-20-2,2>>^ Visto que os  meus pensamentos me fazem responder, eu me apresso.

[[v18-20-3]]

^<<v18-20-3,3>>^ Eu ouvi a repreensão, que me envergonha, mas o espírito do meu entendimento responderá por mim.

[[v18-20-4]]

^<<v18-20-4,4>>^ Porventura não  sabes tu que  desde a antiguidade, desde que o homem foi posto sobre a terra,

[[v18-20-5]]

^<<v18-20-5,5>>^ O júbilo dos ímpios é breve, e a alegria dos hipócritas apenas dum momento?

[[v18-20-6]]

^<<v18-20-6,6>>^ Ainda que a sua altura suba até ao céu, e a sua cabeça chegue até às nuvens,

[[v18-20-7]]

^<<v18-20-7,7>>^ Como o seu próprio  esterco perecerá para sempre; e  os que o viam dirão: Onde está?

[[v18-20-8]]

^<<v18-20-8,8>>^ Como um sonho voa, e não será achado, e será afugentado como uma visão da noite.

[[v18-20-9]]

^<<v18-20-9,9>>^ O olho que o viu jamais o verá, nem olhará mais para ele o seu lugar.

[[v18-20-10]]

^<<v18-20-10,10>>^ Os seus filhos procurarão agradar aos pobres, e as suas mãos restaurarão a sua fazenda.

[[v18-20-11]]

^<<v18-20-11,11>>^ Os seus ossos estão cheios do vigor da sua juventude, mas deitar-se-ão com ele no pó.

[[v18-20-12]]

^<<v18-20-12,12>>^ Ainda que o mal lhe seja doce na boca, e  ele o esconda debaixo da sua língua,

[[v18-20-13]]

^<<v18-20-13,13>>^ E o guarde, e o não deixe, antes o retenha no seu paladar,

[[v18-20-14]]

^<<v18-20-14,14>>^ Contudo a sua comida se mudará nas suas entranhas; fel de áspides será  interiormente.

[[v18-20-15]]

^<<v18-20-15,15>>^ Engoliu fazendas, mas vomitá-las-á; do seu ventre Deus as lançará.

[[v18-20-16]]

^<<v18-20-16,16>>^ Veneno de áspides sorverá; língua de víbora o matará.

[[v18-20-17]]

^<<v18-20-17,17>>^ Não verá as correntes, os rios e  os ribeiros de mel e manteiga.

[[v18-20-18]]

^<<v18-20-18,18>>^ Restituirá o seu trabalho, e não o engolirá; conforme ao poder de sua mudança, não saltará de gozo.

[[v18-20-19]]

^<<v18-20-19,19>>^ Porquanto oprimiu, desamparou os pobres, e roubou a casa que não edificou;

[[v18-20-20]]

^<<v18-20-20,20>>^ Porquanto não sentiu sossego no seu ventre, da sua tão desejada fazenda cousa nenhuma reterá.

[[v18-20-21]]

^<<v18-20-21,21>>^ Nada lhe  sobejará para comer; pelo que a sua fazenda não será durável.

[[v18-20-22]]

^<<v18-20-22,22>>^ Sendo plena a sua abastança, estará angustiado; toda a mão dos miseráveis virá sobre ele.

[[v18-20-23]]

^<<v18-20-23,23>>^ Haja porém ainda  de que possa encher o seu ventre, e Deus  mandará sobre ele o ardor da sua ira, e a fará chover sobre ele quando for a comer.

[[v18-20-24]]

^<<v18-20-24,24>>^ Ainda que fuja das armas de ferro, o arco de aço o atravessará.

[[v18-20-25]]

^<<v18-20-25,25>>^ Arrancará o dardo do seu  corpo, e resplandecente virá do seu fel; e haverá  sobre ele assombros.

[[v18-20-26]]

^<<v18-20-26,26>>^ Toda a escuridão se ocultará nos seus esconderijos; um fogo não assoprado o consumirá, e  devorará o que ficar na sua tenda.

[[v18-20-27]]

^<<v18-20-27,27>>^ Os céus manifestarão a sua iniquidade; e a terra se levantará contra ele.

[[v18-20-28]]

^<<v18-20-28,28>>^ As rendas de sua casa serão transportadas; no dia da sua ira todas se derramarão.

[[v18-20-29]]

^<<v18-20-29,29>>^ Esta, da parte de Deus, é  a porção do homem ímpio; esta é a herança que Deus lhe reserva.

'''

xref:018-jo/018-jo-019.adoc#v18-19-0[&#60; Capítulo Anterior] | <<v18-20-0,Topo>> | xref:018-jo/018-jo-021.adoc#v18-21-0[Próximo Capítulo &#62;]