include::./index.adoc[]

[[v18-37-0]]
=== Jó, 37
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-37-1]]

^<<v18-37-1,1>>^ SOBRE isto também treme o meu coração, e salta do seu lugar.

[[v18-37-2]]

^<<v18-37-2,2>>^ Atentamente ouvi o movimento da sua voz, e o sonido que  sai da sua boca.

[[v18-37-3]]

^<<v18-37-3,3>>^ Ele o envia por debaixo de todos os céus, e a sua luz até aos confins da terra.

[[v18-37-4]]

^<<v18-37-4,4>>^ Depois disto brama com grande  voz, troveja com a sua alta voz; e, ouvida a sua voz, não tarda com estas cousas.

[[v18-37-5]]

^<<v18-37-5,5>>^ Com a sua voz troveja Deus maravilhosamente; faz grandes cousas, que nós não compreendemos.

[[v18-37-6]]

^<<v18-37-6,6>>^ Porque à neve diz: Cai na terra; como também ao aguaceiro e à sua forte chuva.

[[v18-37-7]]

^<<v18-37-7,7>>^ Ele  sela as mãos de todo o homem, para que conheçam todos os homens a sua obra.

[[v18-37-8]]

^<<v18-37-8,8>>^ E as alimárias entram nos seus esconderijos e ficam nas suas cavernas.

[[v18-37-9]]

^<<v18-37-9,9>>^ Das recâmaras do sul  sai o pé de vento, e do norte o frio.

[[v18-37-10]]

^<<v18-37-10,10>>^ Pelo assopro de Deus se dá a geada, e as largas águas se endurecem.

[[v18-37-11]]

^<<v18-37-11,11>>^ Também com  a umidade carrega as grossas nuvens, e  esparge a nuvem da sua luz.

[[v18-37-12]]

^<<v18-37-12,12>>^ Então ela segundo o seu prudente conselho, se espalha em roda, para que faça tudo quanto lhe ordena sobre a superfície do mundo habitável;

[[v18-37-13]]

^<<v18-37-13,13>>^ Seja para correção, ou para a sua terra, ou para beneficência, que a faça vir.

[[v18-37-14]]

^<<v18-37-14,14>>^ A isto, ó Jó, inclina os teus ouvidos; atende, e considera as maravilhas de Deus.

[[v18-37-15]]

^<<v18-37-15,15>>^ Porventura  sabes tu como Deus as opera, e faz resplandecer a luz da sua nuvem?

[[v18-37-16]]

^<<v18-37-16,16>>^ Tens tu notícia do equilíbrio das grossas nuvens e das maravilhas daquele que é perfeito nos conhecimentos?

[[v18-37-17]]

^<<v18-37-17,17>>^ Ou  de como os teus vestidos aquecem, quando do sul há calma sobre a terra?

[[v18-37-18]]

^<<v18-37-18,18>>^ Ou  estendeste com ele os céus, que estão  firmes como espelho fundido?

[[v18-37-19]]

^<<v18-37-19,19>>^ Ensina-nos o que lhe diremos; porque  nós nada poderemos pôr em boa ordem, por causa das trevas.

[[v18-37-20]]

^<<v18-37-20,20>>^ Contar-lhe-ia alguém o que tenho dito? Ou desejaria um homem que ele fosse devorado?

[[v18-37-21]]

^<<v18-37-21,21>>^ E agora não se pode  ver o sol, que resplandece nos céus; mas, passando o vento e purificando-os,

[[v18-37-22]]

^<<v18-37-22,22>>^ O esplendor de ouro vem do norte; pois  em Deus há uma  tremenda majestade.

[[v18-37-23]]

^<<v18-37-23,23>>^ Ao Todo-poderoso não podemos alcançar; grande é  em poder; porém a ninguém oprime em juízo e grandeza de justiça.

[[v18-37-24]]

^<<v18-37-24,24>>^ Por isso o temem os homens; ele não respeita os que são sábios no coração.

'''

xref:018-jo/018-jo-036.adoc#v18-36-0[&#60; Capítulo Anterior] | <<v18-37-0,Topo>> | xref:018-jo/018-jo-038.adoc#v18-38-0[Próximo Capítulo &#62;]