include::./index.adoc[]

[[v18-35-0]]
=== Jó, 35
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-35-1]]

^<<v18-35-1,1>>^ RESPONDEU mais Eliú, e disse:

[[v18-35-2]]

^<<v18-35-2,2>>^ Tens por direito dizeres: Maior é  a minha justiça do que a  de Deus?

[[v18-35-3]]

^<<v18-35-3,3>>^ Porque disseste: De que te serviria? Que proveito tiraria mais do que do meu pecado?

[[v18-35-4]]

^<<v18-35-4,4>>^ Eu te darei resposta, a ti e aos teus amigos contigo.

[[v18-35-5]]

^<<v18-35-5,5>>^ Atenta para os céus, e vê; e contempla as mais altas nuvens, que estão  mais altas do que tu.

[[v18-35-6]]

^<<v18-35-6,6>>^ Se pecares, que efetuarás contra ele? Se  as tuas transgressões se multiplicarem, que lhe farás?

[[v18-35-7]]

^<<v18-35-7,7>>^ Se fores justo, que lhe darás, ou que receberá da tua mão?

[[v18-35-8]]

^<<v18-35-8,8>>^ A tua impiedade faria mal a  outro tal como tu; e a tua justiça aproveitaria  a um filho do homem.

[[v18-35-9]]

^<<v18-35-9,9>>^ Por causa da grandeza da opressão  eles clamam: eles clamam por causa do braço dos grandes.

[[v18-35-10]]

^<<v18-35-10,10>>^ Mas ninguém diz: Onde está  Deus que me fez, que dá salmos entre a noite;

[[v18-35-11]]

^<<v18-35-11,11>>^ Que nos faz mais doutos do que os animais da terra, e nos faz mais sábios do que as aves dos céus?

[[v18-35-12]]

^<<v18-35-12,12>>^ Clamam, porém ele não responde, por causa da arrogância dos maus.

[[v18-35-13]]

^<<v18-35-13,13>>^ Certo é que Deus não ouvirá a vaidade, nem atentará para ela o Todo-poderoso.

[[v18-35-14]]

^<<v18-35-14,14>>^ E quanto ao que disseste, que  o não verás, juízo há  perante ele; por isso espera nele.

[[v18-35-15]]

^<<v18-35-15,15>>^ Mas agora, porque a sua ira ainda se não exerce, nem grandemente considera a arrogância,

[[v18-35-16]]

^<<v18-35-16,16>>^ Logo Jó em vão abre a sua boca, e sem ciência multiplica palavras.

'''

xref:018-jo/018-jo-034.adoc#v18-34-0[&#60; Capítulo Anterior] | <<v18-35-0,Topo>> | xref:018-jo/018-jo-036.adoc#v18-36-0[Próximo Capítulo &#62;]