include::./index.adoc[]

[[v18-33-0]]
=== Jó, 33
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-33-1]]

^<<v18-33-1,1>>^ ASSIM, na verdade, ó Jó, ouve as minhas razões, e dá ouvidos a todas as minhas palavras.

[[v18-33-2]]

^<<v18-33-2,2>>^ Eis que já abri a minha boca; já  falou a minha língua debaixo do meu paladar.

[[v18-33-3]]

^<<v18-33-3,3>>^ As minhas razões sairão  da sinceridade do meu coração, e a pura ciência dos meus lábios.

[[v18-33-4]]

^<<v18-33-4,4>>^ O Espírito de Deus me fez; e a inspiração do Todo-Poderoso me deu vida.

[[v18-33-5]]

^<<v18-33-5,5>>^ Se podes, responde-me, dispõe bem as tuas razões, e levanta-te.

[[v18-33-6]]

^<<v18-33-6,6>>^ Eis que vim de Deus, como tu; do lodo também eu fui formado.

[[v18-33-7]]

^<<v18-33-7,7>>^ Eis que não te perturbará o meu terror, nem será pesada sobre ti a minha mão.

[[v18-33-8]]

^<<v18-33-8,8>>^ Na verdade tu falaste aos meus ouvidos; e eu ouvi a voz das tuas palavras; dizias :

[[v18-33-9]]

^<<v18-33-9,9>>^ Limpo estou, sem transgressão; puro sou ; e não tenho culpa.

[[v18-33-10]]

^<<v18-33-10,10>>^ Eis que ele acha contra mim ocasiões, e me considerou como seu inimigo.

[[v18-33-11]]

^<<v18-33-11,11>>^ Põe no tronco os meus pés, e  observa todas as minhas veredas.

[[v18-33-12]]

^<<v18-33-12,12>>^ Eis que nisto te respondo: Não foste justo; porque maior é Deus do que o homem.

[[v18-33-13]]

^<<v18-33-13,13>>^ Por que razão contendes com ele? porque ele não dá contas de nenhum dos seus feitos.

[[v18-33-14]]

^<<v18-33-14,14>>^ Antes Deus fala uma e duas vezes; porém ninguém atenta para isso.

[[v18-33-15]]

^<<v18-33-15,15>>^ Em sonho ou em  visão de noite, quando cai sono profundo sobre os homens, e  adormecem na cama,

[[v18-33-16]]

^<<v18-33-16,16>>^ Então abre os ouvidos dos homens, e lhes sela a sua instrução,

[[v18-33-17]]

^<<v18-33-17,17>>^ Para apartar o homem do seu desígnio, e esconder do homem a soberba;

[[v18-33-18]]

^<<v18-33-18,18>>^ Para desviar a sua alma da cova, e a sua vida de passar pela espada.

[[v18-33-19]]

^<<v18-33-19,19>>^ Também na sua cama é com dores castigado, e com a incessante contenda dos seus ossos;

[[v18-33-20]]

^<<v18-33-20,20>>^ De modo que a sua vida abomina até  o pão, e a sua alma a comida apetecível.

[[v18-33-21]]

^<<v18-33-21,21>>^ Desaparece a sua carne a olhos vistos, e os seus ossos, que  se não viam, agora  aparecem:

[[v18-33-22]]

^<<v18-33-22,22>>^ E a sua alma se vai chegando à cova, e a sua vida ao que traz morte.

[[v18-33-23]]

^<<v18-33-23,23>>^ Se com ele pois houver um mensageiro, um intérprete, um entre milhares, para declarar ao homem a sua retidão,

[[v18-33-24]]

^<<v18-33-24,24>>^ Então terá misericórdia dele, e lhe  dirá: Livra-o, que não desça à cova; já  achei resgate.

[[v18-33-25]]

^<<v18-33-25,25>>^ Sua carne se reverdecerá mais do que na sua infância, e  tornará aos dias da sua juventude.

[[v18-33-26]]

^<<v18-33-26,26>>^ Deveras orará a Deus, que se agradará dele, e verá a sua face com júbilo, e restituirá ao homem a sua justiça.

[[v18-33-27]]

^<<v18-33-27,27>>^ Olhará para os homens, e dirá: Pequei, e perverti o direito, o que de nada me aproveitou.

[[v18-33-28]]

^<<v18-33-28,28>>^ Mas Deus  livrou a minha alma de ir para a cova; e a minha vida verá a luz.

[[v18-33-29]]

^<<v18-33-29,29>>^ Eis que tudo isto é obra de Deus, duas e  três vezes para com o homem,

[[v18-33-30]]

^<<v18-33-30,30>>^ Para desviar a sua alma da perdição, e o alumiar com a luz dos viventes.

[[v18-33-31]]

^<<v18-33-31,31>>^ Escuta pois , ó Jó, ouve-me; cala-te, e eu falarei.

[[v18-33-32]]

^<<v18-33-32,32>>^ Se tens alguma cousa que dizer, responde-me; fala, porque desejo justificar-te.

[[v18-33-33]]

^<<v18-33-33,33>>^ Se não, escuta-me tu; cala-te, e ensinar-te-ei a sabedoria.

'''

xref:018-jo/018-jo-032.adoc#v18-32-0[&#60; Capítulo Anterior] | <<v18-33-0,Topo>> | xref:018-jo/018-jo-034.adoc#v18-34-0[Próximo Capítulo &#62;]