include::./index.adoc[]

[[v18-7-0]]
=== Jó, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-7-1]]

^<<v18-7-1,1>>^ PORVENTURA não tem  o homem guerra sobre a terra? E não são  os seus dias como os dias do jornaleiro?

[[v18-7-2]]

^<<v18-7-2,2>>^ Como o cervo que suspira pela  sombra, e como o jornaleiro que espera pela sua paga.

[[v18-7-3]]

^<<v18-7-3,3>>^ Assim me deram por herança meses de vaidade, e noites de trabalho me prepararam.

[[v18-7-4]]

^<<v18-7-4,4>>^ Deitando-me a dormir, então digo: Quando me levantarei? Mas comprida é a noite, e farto-me de me voltar na cama  até à alva.

[[v18-7-5]]

^<<v18-7-5,5>>^ A minha carne se tem vestido de bichos e de torrões de pó; a minha pele está gretada, e se fez abominável.

[[v18-7-6]]

^<<v18-7-6,6>>^ Os meus dias são mais velozes do que a lançadeira do tecelão, e perecem sem esperança.

[[v18-7-7]]

^<<v18-7-7,7>>^ Lembra-te de que a minha vida é  como o vento; os meus olhos não tornarão a ver o bem.

[[v18-7-8]]

^<<v18-7-8,8>>^ Os olhos dos que agora  me veem não me verão mais ; os teus olhos estarão  sobre mim, mas não serei mais.

[[v18-7-9]]

^<<v18-7-9,9>>^ Tal como  a nuvem se desfaz e passa, aquele que desce à sepultura nunca tornará a subir.

[[v18-7-10]]

^<<v18-7-10,10>>^ Nunca mais tornará à sua casa, nem o seu lugar jamais o conhecerá.

[[v18-7-11]]

^<<v18-7-11,11>>^ Por isso não reprimirei a minha boca; falarei na angústia do meu espírito; queixar-me-ei na amargura da minha alma.

[[v18-7-12]]

^<<v18-7-12,12>>^ Sou eu porventura  o mar, ou a baleia, para que me ponhas uma guarda?

[[v18-7-13]]

^<<v18-7-13,13>>^ Dizendo eu: Consolar-me-á a minha cama, meu leito aliviará a minha ânsia!

[[v18-7-14]]

^<<v18-7-14,14>>^ Então me espantas com sonhos, e com visões me assombras;

[[v18-7-15]]

^<<v18-7-15,15>>^ Pelo que a minha alma escolheria antes  a estrangulação; e  antes a morte do que estes meus ossos.

[[v18-7-16]]

^<<v18-7-16,16>>^ A minha vida  abomino, pois não viverei para sempre; retira-te de mim, pois vaidade são  os meus dias.

[[v18-7-17]]

^<<v18-7-17,17>>^ Que é  o homem, para que tanto o estimes, e ponhas sobre ele o teu coração,

[[v18-7-18]]

^<<v18-7-18,18>>^ E cada manhã o visites, e cada momento o proves?

[[v18-7-19]]

^<<v18-7-19,19>>^ Até quando me não deixarás, nem  me largarás, até que engula a minha saliva?

[[v18-7-20]]

^<<v18-7-20,20>>^ Se pequei, que te farei, ó  Guarda dos homens? Por que fizeste de mim um alvo para ti, para que a mim mesmo me seja pesado?

[[v18-7-21]]

^<<v18-7-21,21>>^ E por que me  não perdoas a minha transgressão, e não tiras a minha iniquidade? Pois agora me deitarei no pó, e de madrugada me buscarás, e não estarei lá.

'''

xref:018-jo/018-jo-006.adoc#v18-6-0[&#60; Capítulo Anterior] | <<v18-7-0,Topo>> | xref:018-jo/018-jo-008.adoc#v18-8-0[Próximo Capítulo &#62;]