include::./index.adoc[]

[[v18-3-0]]
=== Jó, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-3-1]]

^<<v18-3-1,1>>^ DEPOIS disto abriu Jó a sua boca, e amaldiçoou o seu dia.

[[v18-3-2]]

^<<v18-3-2,2>>^ E Jó, falando, disse:

[[v18-3-3]]

^<<v18-3-3,3>>^ Pereça o dia em que nasci, e a noite em que  se disse: Foi concebido um  homem!

[[v18-3-4]]

^<<v18-3-4,4>>^ Converta-se aquele dia em trevas; e  Deus, lá de cima, não tenha cuidado dele, nem resplandeça sobre ele a luz.

[[v18-3-5]]

^<<v18-3-5,5>>^ Contaminem-no as trevas e a sombra da morte; habitem sobre ele nuvens; negros vapores do dia o espantem!

[[v18-3-6]]

^<<v18-3-6,6>>^ A escuridão tome aquela noite, e  não se goze entre os dias do ano, e  não entre no número dos meses!

[[v18-3-7]]

^<<v18-3-7,7>>^ Ah! que solitária seja aquela noite e  suave música não entre nela!

[[v18-3-8]]

^<<v18-3-8,8>>^ Amaldiçoem-na aqueles que amaldiçoam o dia, que estão prontos para fazer correr o seu pranto.

[[v18-3-9]]

^<<v18-3-9,9>>^ Escureçam-se as estrelas do seu crepúsculo; que espere a luz, e não venha ; e não veja as pestanas dos olhos da alva!

[[v18-3-10]]

^<<v18-3-10,10>>^ Porquanto não fechou as portas do ventre; nem escondeu dos meus olhos a canseira.

[[v18-3-11]]

^<<v18-3-11,11>>^ Por que não morri eu desde a madre, e  em saindo do ventre, não expirei?

[[v18-3-12]]

^<<v18-3-12,12>>^ Por que me receberam os joelhos? E por que os peitos, para que mamasse?

[[v18-3-13]]

^<<v18-3-13,13>>^ Porque já  agora jazeria e repousaria; dormiria, e então haveria repouso para mim,

[[v18-3-14]]

^<<v18-3-14,14>>^ Com os reis e conselheiros da terra, que para si edificavam casas nos lugares assolados.

[[v18-3-15]]

^<<v18-3-15,15>>^ Ou com os príncipes que tinham ouro, que enchiam as suas casas de prata;

[[v18-3-16]]

^<<v18-3-16,16>>^ Ou, como aborto oculto, não existiria; como as crianças que  nunca viram a luz.

[[v18-3-17]]

^<<v18-3-17,17>>^ Ali os maus cessam de perturbar; e ali repousam os cansados.

[[v18-3-18]]

^<<v18-3-18,18>>^ Ali os presos juntamente repousam e  não ouvem a voz do exator;

[[v18-3-19]]

^<<v18-3-19,19>>^ Ali está o pequeno e o grande, e o servo fica livre de seu senhor.

[[v18-3-20]]

^<<v18-3-20,20>>^ Porque se dá luz ao miserável, e vida aos amargurados de ânimo,

[[v18-3-21]]

^<<v18-3-21,21>>^ Que esperam a morte, e ela não vem: e cavam em procura dela mais do que de  tesouros ocultos;

[[v18-3-22]]

^<<v18-3-22,22>>^ Que de alegria saltam, e  exultam, achando a sepultura?

[[v18-3-23]]

^<<v18-3-23,23>>^ Porque se dá luz  ao homem, cujo caminho é oculto, e a quem Deus o encobriu?

[[v18-3-24]]

^<<v18-3-24,24>>^ Porque antes do meu pão vem o meu suspiro; e os meus gemidos se derramam, como água.

[[v18-3-25]]

^<<v18-3-25,25>>^ Porque o que eu temia me veio; e o que receava me aconteceu.

[[v18-3-26]]

^<<v18-3-26,26>>^ Nunca estive descansado, nem sosseguei, nem repousei, mas veio sobre mim a perturbação.

'''

xref:018-jo/018-jo-002.adoc#v18-2-0[&#60; Capítulo Anterior] | <<v18-3-0,Topo>> | xref:018-jo/018-jo-004.adoc#v18-4-0[Próximo Capítulo &#62;]