include::./index.adoc[]

[[v18-1-0]]
=== Jó, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-1-1]]

^<<v18-1-1,1>>^ HAVIA um  homem na terra de Uz, cujo nome era  Jó; e este era homem sincero, reto e temente a Deus, e desviava-se do mal.

[[v18-1-2]]

^<<v18-1-2,2>>^ E nasceram-lhe sete filhos e três filhas.

[[v18-1-3]]

^<<v18-1-3,3>>^ E era o seu gado sete mil ovelhas, e três mil camelos, e quinhentas juntas de bois, e quinhentas jumentas; era também muitíssima a gente ao seu serviço, de maneira que este homem era maior do que todos os do oriente.

[[v18-1-4]]

^<<v18-1-4,4>>^ E iam seus filhos, e faziam banquetes em casa de cada um no seu dia; e enviavam, e convidavam as suas três irmãs a comerem e beberem com eles.

[[v18-1-5]]

^<<v18-1-5,5>>^ Sucedeu pois que, tendo decorrido o turno de dias de seus banquetes, enviava Jó, e os santificava, e se levantava de madrugada, e oferecia holocaustos segundo  o número de todos eles; porque dizia Jó: Porventura  pecaram meus filhos, e blasfemaram de Deus no seu coração. Assim o fazia Jó continuamente.

[[v18-1-6]]

^<<v18-1-6,6>>^ E vindo um dia em que os filhos de Deus vieram apresentar-se perante o Senhor, veio também Satanás entre eles.

[[v18-1-7]]

^<<v18-1-7,7>>^ Então o Senhor disse a Satanás: Donde vens? E Satanás respondeu ao Senhor, e disse: De rodear a terra, e passear por ela.

[[v18-1-8]]

^<<v18-1-8,8>>^ E disse o Senhor a Satanás: Observaste tu a meu servo Jó? Porque ninguém há  na terra semelhante a ele, homem sincero e reto, temente a Deus, e desviando-se do mal.

[[v18-1-9]]

^<<v18-1-9,9>>^ Então respondeu Satanás ao Senhor, e disse: Porventura  teme Jó a Deus debalde?

[[v18-1-10]]

^<<v18-1-10,10>>^ Porventura  não o cercaste tu de bens a ele, e a sua casa, e a tudo quanto tem? A obra de suas mãos abençoaste e o seu gado está aumentado na terra.

[[v18-1-11]]

^<<v18-1-11,11>>^ Mas estende a tua mão, e toca- lhe  em tudo quanto tem, e verás  se não blasfema de ti na tua face!

[[v18-1-12]]

^<<v18-1-12,12>>^ E disse o Senhor a Satanás: Eis que tudo quanto tem está  na tua mão, somente contra ele não estendas a tua mão. E Satanás saiu da presença do Senhor.

[[v18-1-13]]

^<<v18-1-13,13>>^ E sucedeu um dia, em que seus filhos e suas filhas comiam, e bebiam vinho na casa de seu irmão primogênito,

[[v18-1-14]]

^<<v18-1-14,14>>^ Que veio um mensageiro a Jó, e lhe  disse: Os bois lavravam, e as jumentas pasciam junto a eles;

[[v18-1-15]]

^<<v18-1-15,15>>^ E eis que deram sobre eles  os sabeus, e os tomaram, e aos moços feriram ao fio da espada; e eu somente escapei, para te trazer a nova.

[[v18-1-16]]

^<<v18-1-16,16>>^ Estando este ainda falando, veio outro e disse: Fogo de Deus caiu do céu, e queimou as ovelhas e os moços, e os consumiu, e só eu escapei, para te trazer a nova.

[[v18-1-17]]

^<<v18-1-17,17>>^ Estando ainda este falando, veio outro, e disse: Ordenando os caldeus três bandos, deram sobre os camelos, e os tomaram, e aos moços feriram ao fio da espada; e só eu escapei, para te trazer a nova.

[[v18-1-18]]

^<<v18-1-18,18>>^ Estando ainda este falando veio outro, e disse: Estando teus filhos e tuas filhas comendo e bebendo vinho, em casa de seu irmão primogênito,

[[v18-1-19]]

^<<v18-1-19,19>>^ Eis que um  grande vento sobreveio dalém do deserto, e deu nos quatro cantos da casa, a qual caiu sobre os mancebos, e morreram; e só eu escapei, para te trazer a nova.

[[v18-1-20]]

^<<v18-1-20,20>>^ Então Jó se levantou, e rasgou o seu manto, e rapou a sua cabeça, e se lançou em terra, e adorou,

[[v18-1-21]]

^<<v18-1-21,21>>^ E disse: Nu saí do ventre de minha mãe, e nu tornarei para lá; o Senhor o  deu e o Senhor o  tomou; bendito seja o nome do Senhor.

[[v18-1-22]]

^<<v18-1-22,22>>^ Em tudo isto Jó não pecou, nem atribuiu a Deus falta alguma.

'''

xref:017-ester/017-ester-010.adoc#v17-10-0[&#60; Capítulo Anterior] | <<v18-1-0,Topo>> | xref:018-jo/018-jo-002.adoc#v18-2-0[Próximo Capítulo &#62;]