include::./index.adoc[]

[[v18-15-0]]
=== Jó, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-15-1]]

^<<v18-15-1,1>>^ ENTÃO respondeu Elifaz o temanita, e disse:

[[v18-15-2]]

^<<v18-15-2,2>>^ Porventura  dará o sábio em resposta ciência de vento? E encherá o seu ventre de vento oriental?

[[v18-15-3]]

^<<v18-15-3,3>>^ Arguindo com palavras que de nada servem, e com razões, com que nada aproveita?

[[v18-15-4]]

^<<v18-15-4,4>>^ E tu tens feito vão o temor, e diminuis os rogos diante de Deus.

[[v18-15-5]]

^<<v18-15-5,5>>^ Porque a tua boca declara a tua iniquidade; e tu escolheste a língua dos astutos.

[[v18-15-6]]

^<<v18-15-6,6>>^ A tua boca te condena, e não eu, e os teus lábios testificam contra ti.

[[v18-15-7]]

^<<v18-15-7,7>>^ És  tu porventura  o primeiro homem que foi nascido. Ou foste gerado antes dos outeiros?

[[v18-15-8]]

^<<v18-15-8,8>>^ Ou ouviste o secreto conselho de Deus e a ti só  limitaste a sabedoria?

[[v18-15-9]]

^<<v18-15-9,9>>^ Que sabes tu, que nós não saibamos? Que entendes, que não haja  em nós?

[[v18-15-10]]

^<<v18-15-10,10>>^ Também há  entre nós encanecidos e idosos, muito mais idosos do que teu pai.

[[v18-15-11]]

^<<v18-15-11,11>>^ Por ventura  as consolações de Deus te são  pequenas? ou alguma cousa se oculta em ti?

[[v18-15-12]]

^<<v18-15-12,12>>^ Por que te arrebata o teu coração e por que piscas os teus olhos,

[[v18-15-13]]

^<<v18-15-13,13>>^ Para virares contra Deus o teu espírito, e deixares sair tais  palavras da tua boca?

[[v18-15-14]]

^<<v18-15-14,14>>^ Que é o  homem, para que seja puro? e o que  nasce da mulher, para que fique justo?

[[v18-15-15]]

^<<v18-15-15,15>>^ Eis que nos seus santos não confiaria, e nem os céus são puros aos seus olhos.

[[v18-15-16]]

^<<v18-15-16,16>>^ Quanto mais abominável e corrupto é  o homem, que bebe a iniquidade como a água?

[[v18-15-17]]

^<<v18-15-17,17>>^ Escuta-me, mostrar- to- ei; e o que vi te  contarei

[[v18-15-18]]

^<<v18-15-18,18>>^ (O que os sábios anunciaram, e, que o ouviram  de seus pais, o  não ocultaram.

[[v18-15-19]]

^<<v18-15-19,19>>^ Aos quais somente se dera a terra, e nenhum estranho passou por entre eles):

[[v18-15-20]]

^<<v18-15-20,20>>^ Todos os dias o ímpio se dá pena a si  mesmo, no curto número de anos que se reservam para o tirano.

[[v18-15-21]]

^<<v18-15-21,21>>^ O sonido dos horrores está  nos seus ouvidos; até na paz lhe sobrevém o assolador.

[[v18-15-22]]

^<<v18-15-22,22>>^ Não crê que tornará das trevas, mas que o espera a espada.

[[v18-15-23]]

^<<v18-15-23,23>>^ Anda vagueando por pão, dizendo: Onde está? Bem  sabe que o dia das trevas lhe está perto à mão.

[[v18-15-24]]

^<<v18-15-24,24>>^ Assombram-no a angústia e a tribulação; prevalecem contra ele, como o rei preparado para a peleja.

[[v18-15-25]]

^<<v18-15-25,25>>^ Porque estendeu a sua mão contra Deus, e contra o Todo-poderoso se embraveceu.

[[v18-15-26]]

^<<v18-15-26,26>>^ Arremete contra ele com dura cerviz, e  com os pontos grossos dos seus escudos.

[[v18-15-27]]

^<<v18-15-27,27>>^ Porquanto cobriu o seu rosto com a sua gordura, e criou enxúndia nas ilhargas.

[[v18-15-28]]

^<<v18-15-28,28>>^ E habitou em cidades assoladas, em casas em que ninguém morava, que estavam a ponto de fazer-se montões de ruínas.

[[v18-15-29]]

^<<v18-15-29,29>>^ Não se enriquecerá, nem subsistirá a sua fazenda, nem se estenderão pela terra as suas possessões.

[[v18-15-30]]

^<<v18-15-30,30>>^ Não escapará das trevas; e chama do fogo  secará os seus renovos e  ao assopro da sua boca desaparecerá.

[[v18-15-31]]

^<<v18-15-31,31>>^ Não confie pois  na vaidade enganando-se a si mesmo, porque a vaidade será a sua recompensa.

[[v18-15-32]]

^<<v18-15-32,32>>^ Antes do seu dia ela se consumará; e o seu ramo não reverdecerá.

[[v18-15-33]]

^<<v18-15-33,33>>^ Sacudirá as suas uvas verdes, como as  da vide, e deixará cair a sua flor como a  da oliveira.

[[v18-15-34]]

^<<v18-15-34,34>>^ Porque o ajuntamento dos hipócritas se fará  estéril, e o fogo, consumirá as tendas do suborno.

[[v18-15-35]]

^<<v18-15-35,35>>^ Concebem o trabalho, e produzem a iniquidade, e o seu ventre prepara enganos.

'''

xref:018-jo/018-jo-014.adoc#v18-14-0[&#60; Capítulo Anterior] | <<v18-15-0,Topo>> | xref:018-jo/018-jo-016.adoc#v18-16-0[Próximo Capítulo &#62;]