include::./index.adoc[]

[[v18-16-0]]
=== Jó, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-16-1]]

^<<v18-16-1,1>>^ ENTÃO respondeu Jó, e disse:

[[v18-16-2]]

^<<v18-16-2,2>>^ Tenho ouvido muitas cousas como estas; todos vós sois  consoladores molestos.

[[v18-16-3]]

^<<v18-16-3,3>>^ Porventura  não terão fim estas palavras de vento? Ou que  te irrita, para assim  responderes?

[[v18-16-4]]

^<<v18-16-4,4>>^ Falaria eu também como vós falais , se a vossa alma estivesse em lugar da minha alma? Ou  amontoaria palavras contra vós, e menearia contra vós a minha cabeça?

[[v18-16-5]]

^<<v18-16-5,5>>^ Antes vos fortaleceria com a minha boca, e a consolação dos meus lábios abrandaria a vossa  dor.

[[v18-16-6]]

^<<v18-16-6,6>>^ Se eu falar, a minha dor não cessa, e, calando- me , qual é o meu alívio?

[[v18-16-7]]

^<<v18-16-7,7>>^ Na verdade, agora me molestou; tu assolaste toda a minha companhia.

[[v18-16-8]]

^<<v18-16-8,8>>^ Testemunha disto é  que já me fizeste enrugado, e a minha magreza já  se levanta contra mim e  no meu rosto testifica contra mim.

[[v18-16-9]]

^<<v18-16-9,9>>^ Na sua ira me  despedaçou, e ele me perseguiu; rangeu os seus dentes contra mim; aguça o meu adversário os seus olhos contra mim.

[[v18-16-10]]

^<<v18-16-10,10>>^ Abrem a sua boca contra mim; com desprezo me feriram nos queixos, e contra mim se ajuntam todos.

[[v18-16-11]]

^<<v18-16-11,11>>^ Entrega-me Deus ao perverso, e nas mãos dos ímpios me faz cair.

[[v18-16-12]]

^<<v18-16-12,12>>^ Descansado estava eu, porém ele me quebrantou; e pegou-me pelo pescoço, e me despedaçou; também me pôs por seu alvo.

[[v18-16-13]]

^<<v18-16-13,13>>^ Cercam-me os seus frecheiros; atravessa-me os rins, e não me  poupa; e  o meu fel derrama pela terra.

[[v18-16-14]]

^<<v18-16-14,14>>^ Quebranta-me com quebranto sobre quebranto; arremete contra mim como um valente.

[[v18-16-15]]

^<<v18-16-15,15>>^ Cosi sobre a minha pele o saco, e  revolvi a minha cabeça no pó.

[[v18-16-16]]

^<<v18-16-16,16>>^ O meu rosto todo  está descorado de chorar, e sobre as minhas pálpebras está  a sombra da morte,

[[v18-16-17]]

^<<v18-16-17,17>>^ Apesar de não haver violência nas minhas mãos, e de ser pura a minha oração.

[[v18-16-18]]

^<<v18-16-18,18>>^ Ah! terra, não cubras o meu sangue; e não haja lugar para o meu clamor!

[[v18-16-19]]

^<<v18-16-19,19>>^ Eis que também agora está  a minha testemunha no céu, e o meu fiador nas alturas.

[[v18-16-20]]

^<<v18-16-20,20>>^ Os meus amigos são  os que zombam de mim; os meus olhos se desfazem em lágrimas  diante de Deus.

[[v18-16-21]]

^<<v18-16-21,21>>^ Ah! Se alguém pudesse contender com Deus pelo homem, como o filho do homem pelo seu amigo!

[[v18-16-22]]

^<<v18-16-22,22>>^ Porque decorridos poucos  anos, eu seguirei o caminho por onde  não tornarei.

'''

xref:018-jo/018-jo-015.adoc#v18-15-0[&#60; Capítulo Anterior] | <<v18-16-0,Topo>> | xref:018-jo/018-jo-017.adoc#v18-17-0[Próximo Capítulo &#62;]