include::./index.adoc[]

[[v18-22-0]]
=== Jó, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v18-22-1]]

^<<v18-22-1,1>>^ ENTÃO respondeu Elifaz, o temanita, e disse:

[[v18-22-2]]

^<<v18-22-2,2>>^ Porventura  o homem será de algum  proveito a Deus? Antes a si mesmo o prudente será proveitoso.

[[v18-22-3]]

^<<v18-22-3,3>>^ Ou  tem o Todo-poderoso prazer em que tu sejas justo, ou lucro algum  em que tu faças perfeitos os teus caminhos?

[[v18-22-4]]

^<<v18-22-4,4>>^ Ou  te repreende pelo temor que tem  de ti, ou  entra contigo em juízo?

[[v18-22-5]]

^<<v18-22-5,5>>^ Porventura  não é  grande a tua malícia, e sem termo as tuas iniquidades?

[[v18-22-6]]

^<<v18-22-6,6>>^ Porque penhoraste a teus irmãos sem causa alguma , e aos nus despojaste dos vestidos.

[[v18-22-7]]

^<<v18-22-7,7>>^ Não deste água a beber ao cansado, e ao faminto retiveste o pão.

[[v18-22-8]]

^<<v18-22-8,8>>^ Mas para o violento era a terra, e o homem tido em respeito habitava nela.

[[v18-22-9]]

^<<v18-22-9,9>>^ As viúvas despediste vazias, e os braços dos órfãos foram quebrantados.

[[v18-22-10]]

^<<v18-22-10,10>>^ Por isso é que estás cercado de laços, e te perturbou um  pavor repentino

[[v18-22-11]]

^<<v18-22-11,11>>^ Ou trevas em que nada vês; e a abundância de águas te cobre.

[[v18-22-12]]

^<<v18-22-12,12>>^ Porventura  Deus não está  na altura dos céus? Olha para a altura das estrelas; quão elevadas estão!

[[v18-22-13]]

^<<v18-22-13,13>>^ E dizes: Que sabe Deus disto? Porventura  julgará por entre a escuridão?

[[v18-22-14]]

^<<v18-22-14,14>>^ As nuvens são  escondedouro para ele, para que não veja; e ele passeia pelo circuito dos céus.

[[v18-22-15]]

^<<v18-22-15,15>>^ Porventura  consideraste a vereda do século passado , que pisaram os homens iníquos?

[[v18-22-16]]

^<<v18-22-16,16>>^ Eles foram arrebatados antes do seu  tempo; sobre  o seu fundamento um dilúvio se derramou.

[[v18-22-17]]

^<<v18-22-17,17>>^ Diziam a Deus: Retira-te de nós. E: Que foi que  o Todo-poderoso nos fez?

[[v18-22-18]]

^<<v18-22-18,18>>^ Ora ele encherá de bens as suas casas; pelo que longe de mim o conselho dos ímpios!

[[v18-22-19]]

^<<v18-22-19,19>>^ Os justos o  viram, e se alegraram, e o inocente escarneceu deles,

[[v18-22-20]]

^<<v18-22-20,20>>^ Dizendo : Porquanto o nosso estado não foi destruído, mas o fogo consumiu o resto deles.

[[v18-22-21]]

^<<v18-22-21,21>>^ Une-te pois a ele, e tem paz, e assim te sobrevirá o bem.

[[v18-22-22]]

^<<v18-22-22,22>>^ Aceita, peço-te, a lei da sua boca, e põe as suas palavras no teu coração.

[[v18-22-23]]

^<<v18-22-23,23>>^ Se te converteres ao Todo-poderoso, serás edificado; afasta a iniquidade da tua tenda.

[[v18-22-24]]

^<<v18-22-24,24>>^ Então amontoarás ouro como pó, e o ouro de  Ofir como pedras dos ribeiros.

[[v18-22-25]]

^<<v18-22-25,25>>^ E até o Todo-poderoso te será por  ouro, e por prata amontoada.

[[v18-22-26]]

^<<v18-22-26,26>>^ Porque então te deleitarás no Todo-poderoso, e levantarás o teu rosto para Deus.

[[v18-22-27]]

^<<v18-22-27,27>>^ Tu orarás a ele, e ele te ouvirá; e pagarás os teus votos.

[[v18-22-28]]

^<<v18-22-28,28>>^ Determinando tu algum negócio, ser-te-á firme, e a luz brilhará em teus caminhos.

[[v18-22-29]]

^<<v18-22-29,29>>^ Quando te  abaterem, então tu dirás: Haja exaltação! E Deus  salvará ao humilde.

[[v18-22-30]]

^<<v18-22-30,30>>^ E  livrará até ao  que não é inocente; sim, será libertado pela pureza de tuas mãos.

'''

xref:018-jo/018-jo-021.adoc#v18-21-0[&#60; Capítulo Anterior] | <<v18-22-0,Topo>> | xref:018-jo/018-jo-023.adoc#v18-23-0[Próximo Capítulo &#62;]