include::./index.adoc[]

[[v54-2-0]]
=== 1 Timóteo, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v54-2-1]]

^<<v54-2-1,1>>^ ADMOESTO-TE pois, antes de tudo, que se façam deprecações, orações, intercessões, e ações de graças por todos os homens;

[[v54-2-2]]

^<<v54-2-2,2>>^ Pelos reis, e por  todos os que estão em eminência, para que tenhamos uma  vida quieta e sossegada, em toda a piedade e honestidade.

[[v54-2-3]]

^<<v54-2-3,3>>^ Porque isto é  bom e agradável diante de Deus nosso Salvador,

[[v54-2-4]]

^<<v54-2-4,4>>^ Que quer que todos os homens se salvem, e venham ao conhecimento da verdade.

[[v54-2-5]]

^<<v54-2-5,5>>^ Porque há  um só  Deus, e um só  Mediador entre Deus e os homens, Jesus Cristo homem.

[[v54-2-6]]

^<<v54-2-6,6>>^ O qual se deu a si mesmo em  preço de redenção por todos, para servir de  testemunho a seu tempo.

[[v54-2-7]]

^<<v54-2-7,7>>^ Para o que (digo a verdade em Cristo, não minto) fui constituído pregador, e apóstolo, e doutor dos gentios na fé e na  verdade.

[[v54-2-8]]

^<<v54-2-8,8>>^ Quero pois que os homens orem em todo o lugar, levantando mãos santas, sem ira nem contenda.

[[v54-2-9]]

^<<v54-2-9,9>>^ Que do mesmo modo as mulheres se ataviem em traje honesto, com pudor e modéstia, não com tranças, ou com ouro, ou pérolas ou vestidos preciosos,

[[v54-2-10]]

^<<v54-2-10,10>>^ Mas (como convém a mulheres que fazem profissão de servir a Deus) com boas obras.

[[v54-2-11]]

^<<v54-2-11,11>>^ A mulher aprenda em silêncio, com toda a sujeição.

[[v54-2-12]]

^<<v54-2-12,12>>^ Não permito, porém, que a mulher ensine, nem use de autoridade sobre o marido, mas que esteja em silêncio.

[[v54-2-13]]

^<<v54-2-13,13>>^ Porque primeiro foi formado Adão, depois Eva.

[[v54-2-14]]

^<<v54-2-14,14>>^ E Adão, não foi enganado, mas a mulher, sendo enganada, caiu em transgressão.

[[v54-2-15]]

^<<v54-2-15,15>>^ Salvar-se-á, porém, dando à luz filhos, se permanecer com modéstia na fé, na caridade e na santificação.

'''

xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[Próximo Capítulo &#62;]