include::./index.adoc[]

[[v54-3-0]]
=== 1 Timóteo, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v54-3-1]]

^<<v54-3-1,1>>^ ESTA é uma  palavra fiel: se alguém deseja o episcopado, excelente obra deseja.

[[v54-3-2]]

^<<v54-3-2,2>>^ Convém pois que o bispo seja irrepreensível, marido de uma mulher, vigilante, sóbrio, honesto, hospitaleiro, apto para ensinar;

[[v54-3-3]]

^<<v54-3-3,3>>^ Não dado ao vinho, não espancador, não cobiçoso de torpe ganância, mas moderado, não contencioso, não avarento;

[[v54-3-4]]

^<<v54-3-4,4>>^ Que governe bem a sua própria casa, tendo seus  filhos em sujeição, com toda a modéstia;

[[v54-3-5]]

^<<v54-3-5,5>>^ (Porque, se alguém não sabe governar a sua própria casa, terá cuidado da igreja de Deus?)

[[v54-3-6]]

^<<v54-3-6,6>>^ Não neófito, para que, ensoberbecendo-se, não caia na condenação do diabo.

[[v54-3-7]]

^<<v54-3-7,7>>^ Convém também que tenha bom testemunho dos que estão de fora, para que não caia em afronta, e no laço do diabo.

[[v54-3-8]]

^<<v54-3-8,8>>^ Da mesma sorte os diáconos sejam honestos, não de língua dobre, não dados a muito vinho, não cobiçosos de torpe ganância;

[[v54-3-9]]

^<<v54-3-9,9>>^ Guardando o mistério da fé em uma pura consciência.

[[v54-3-10]]

^<<v54-3-10,10>>^ E também estes sejam primeiro provados, depois sirvam, se forem irrepreensíveis.

[[v54-3-11]]

^<<v54-3-11,11>>^ Da mesma sorte as mulheres sejam honestas, não maldizentes, sóbrias e  fiéis em tudo.

[[v54-3-12]]

^<<v54-3-12,12>>^ Os diáconos sejam maridos de uma mulher, e governem bem seus  filhos e suas próprias casas.

[[v54-3-13]]

^<<v54-3-13,13>>^ Porque os que servirem bem como diáconos, adquirirão para si uma boa posição, e muita confiança na fé que há em Cristo Jesus.

[[v54-3-14]]

^<<v54-3-14,14>>^ Escrevo-te estas coisas , esperando ir ver-te bem depressa;

[[v54-3-15]]

^<<v54-3-15,15>>^ Mas, se tardar, para que saibas como convém andar na casa de Deus, que é a igreja de Deus vivo, a coluna e firmeza da verdade.

[[v54-3-16]]

^<<v54-3-16,16>>^ E sem dúvida alguma grande é o mistério da piedade: Aquele que se manifestou em carne, foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo, e recebido  acima na glória.

'''

xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[&#60; Capítulo Anterior] | <<v54-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[Próximo Capítulo &#62;]