include::./index.adoc[]

[[v54-6-0]]
=== 1 Timóteo, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v54-6-1]]

^<<v54-6-1,1>>^ TODOS os servos que estão debaixo do jugo estimem a seus senhores por dignos de toda a honra, para que o nome de Deus e a doutrina não sejam blasfemados.

[[v54-6-2]]

^<<v54-6-2,2>>^ E os  que têm senhores crentes não os  desprezem, por serem irmãos; antes os  sirvam melhor, porque eles, que participam do benefício, são crentes e amados. Isto ensina e exorta.

[[v54-6-3]]

^<<v54-6-3,3>>^ Se alguém ensina alguma  outra doutrina, e se não conforma com as sãs palavras de nosso Senhor Jesus Cristo, e com a doutrina que é segundo a piedade,

[[v54-6-4]]

^<<v54-6-4,4>>^ É soberbo, e nada sabe, mas delira acerca de questões e contendas de palavras, das quais nascem invejas, porfias, blasfêmias, ruins suspeitas,

[[v54-6-5]]

^<<v54-6-5,5>>^ Contendas de homens corruptos de entendimento, e privados da verdade, cuidando que a piedade seja causa de ganho: aparta-te dos tais.

[[v54-6-6]]

^<<v54-6-6,6>>^ Mas é grande ganho a piedade com contentamento.

[[v54-6-7]]

^<<v54-6-7,7>>^ Porque nada trouxemos para este  mundo, e  manifesto é  que nada podemos levar dele.

[[v54-6-8]]

^<<v54-6-8,8>>^ Tendo, porém, sustento, e com que nos cobrirmos, estejamos com isso contentes.

[[v54-6-9]]

^<<v54-6-9,9>>^ Mas os que querem ser ricos caem em tentação e em  laço, e em  muitas concupiscências loucas e nocivas, que submergem os homens na perdição e ruína.

[[v54-6-10]]

^<<v54-6-10,10>>^ Porque o amor do dinheiro é a raiz de toda a espécie de males; e nessa cobiça alguns se desviaram da fé, e se traspassaram a si mesmos com muitas dores.

[[v54-6-11]]

^<<v54-6-11,11>>^ Mas tu, ó homem de Deus, foge destas coisas , e segue a justiça, a piedade, a fé, a caridade, a paciência, a mansidão.

[[v54-6-12]]

^<<v54-6-12,12>>^ Milita a boa milícia da fé, toma posse da vida eterna, para a qual também foste chamado, tendo já feito boa confissão diante de muitas testemunhas.

[[v54-6-13]]

^<<v54-6-13,13>>^ Mando-te diante de Deus, que todas as coisas vivifica, e de Cristo Jesus, que diante de Pôncio Pilatos deu o testemunho de boa confissão,

[[v54-6-14]]

^<<v54-6-14,14>>^ Que guardes este mandamento sem mácula e repreensão, até à aparição de nosso Senhor Jesus Cristo;

[[v54-6-15]]

^<<v54-6-15,15>>^ A qual a seu tempo mostrará o bem-aventurado, e único poderoso Senhor, Rei dos reis e Senhor dos senhores;

[[v54-6-16]]

^<<v54-6-16,16>>^ Aquele que tem, ele só, a imortalidade, e habita na luz inacessível; a quem nenhum dos homens viu nem pode ver: ao qual seja  honra e poder sempiterno. Amém.

[[v54-6-17]]

^<<v54-6-17,17>>^ Manda aos ricos deste mundo que não sejam altivos, nem ponham a esperança na incerteza das riquezas, mas em Deus, que abundantemente nos dá todas as coisas  para delas  gozarmos;

[[v54-6-18]]

^<<v54-6-18,18>>^ Que façam bem, enriqueçam em boas obras, repartam de boa mente, e sejam comunicáveis;

[[v54-6-19]]

^<<v54-6-19,19>>^ Que entesourem para si mesmos um bom fundamento para o futuro, para que possam alcançar a vida eterna.

[[v54-6-20]]

^<<v54-6-20,20>>^ Ó Timóteo, guarda o depósito que te  foi confiado, tendo horror aos clamores vãos e profanos e às oposições da falsamente chamada ciência;

[[v54-6-21]]

^<<v54-6-21,21>>^ A qual professando-a alguns, se desviaram da fé. A graça seja  contigo. Amém.

'''

xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[Próximo Capítulo &#62;]