include::./index.adoc[]

[[v54-4-0]]
=== 1 Timóteo, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v54-4-1]]

^<<v54-4-1,1>>^ MAS o Espírito expressamente diz que nos últimos tempos apostatarão alguns da fé, dando ouvidos a espíritos enganadores, e a doutrinas de demônios;

[[v54-4-2]]

^<<v54-4-2,2>>^ Pela hipocrisia de homens que falam mentiras, tendo cauterizada a sua própria consciência;

[[v54-4-3]]

^<<v54-4-3,3>>^ Proibindo o casamento, e  ordenando a abstinência dos manjares que Deus criou para os fiéis, e para os que conhecem a verdade, a fim de usarem deles com ações de graças;

[[v54-4-4]]

^<<v54-4-4,4>>^ Porque toda a criatura de Deus é  boa, e não há nada que rejeitar, sendo recebido com ações de graças.

[[v54-4-5]]

^<<v54-4-5,5>>^ Porque pela palavra de Deus e pela  oração é santificada.

[[v54-4-6]]

^<<v54-4-6,6>>^ Propondo estas coisas aos irmãos, serás bom ministro de Jesus Cristo, criado com as palavras da fé e da boa doutrina que tens seguido.

[[v54-4-7]]

^<<v54-4-7,7>>^ Mas rejeita as fábulas profanas e de velhas, e exercita-te a ti mesmo em piedade.

[[v54-4-8]]

^<<v54-4-8,8>>^ Porque o exercício corporal para pouco aproveita, mas a piedade para tudo é proveitosa, tendo a promessa da vida presente e da que há de vir.

[[v54-4-9]]

^<<v54-4-9,9>>^ Esta palavra é  fiel e digna de toda a aceitação.

[[v54-4-10]]

^<<v54-4-10,10>>^ Porque para isto trabalhamos e lutamos, pois esperamos no Deus vivo, que é o salvador de todos os homens, principalmente dos fiéis.

[[v54-4-11]]

^<<v54-4-11,11>>^ Manda estas coisas  e ensina-as.

[[v54-4-12]]

^<<v54-4-12,12>>^ Ninguém despreze a tua mocidade: mas sê o exemplo dos fiéis, na palavra, no trato, na caridade, no espírito, na fé, na pureza.

[[v54-4-13]]

^<<v54-4-13,13>>^ Persiste em ler, exortar e ensinar, até que eu vá.

[[v54-4-14]]

^<<v54-4-14,14>>^ Não desprezes o dom que há em ti, o qual te foi dado por profecia, com a imposição das mãos do presbitério.

[[v54-4-15]]

^<<v54-4-15,15>>^ Medita estas coisas ; ocupa-te nelas, para que o teu aproveitamento seja manifesto a todos.

[[v54-4-16]]

^<<v54-4-16,16>>^ Tem cuidado de ti mesmo e da doutrina: persevera nestas coisas; porque, fazendo isto, te salvarás, tanto a ti mesmo como aos que te ouvem.

'''

xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[&#60; Capítulo Anterior] | <<v54-4-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[Próximo Capítulo &#62;]