include::./index.adoc[]

[[v44-13-0]]
=== Atos, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-13-1]]

^<<v44-13-1,1>>^ E NA igreja que estava em Antioquia havia alguns profetas e doutores, a saber : Barnabé e Simeão, chamado Níger, e Lúcio cireneu, e Manaém, que fora criado com Herodes o tetrarca, e Saulo.

[[v44-13-2]]

^<<v44-13-2,2>>^ E, servindo eles ao Senhor, e jejuando, disse o Espírito Santo: Apartai-me a Barnabé e a Saulo para a obra a que os tenho chamado.

[[v44-13-3]]

^<<v44-13-3,3>>^ Então, jejuando e orando, e pondo sobre eles as mãos, os  despediram.

[[v44-13-4]]

^<<v44-13-4,4>>^ E assim estes, enviados pelo Espírito Santo, desceram a Selêucia e dali navegaram para Chipre.

[[v44-13-5]]

^<<v44-13-5,5>>^ E, chegados a Salamina, anunciavam a palavra de Deus nas sinagogas dos judeus; e tinham também a João como cooperador.

[[v44-13-6]]

^<<v44-13-6,6>>^ E, havendo atravessado a ilha até Pafos, acharam um  certo judeu mágico falso profeta, chamado Barjesus.

[[v44-13-7]]

^<<v44-13-7,7>>^ O qual estava com o procônsul Sérgio Paulo, varão prudente. Este, chamando a si Barnabé e Saulo, procurava muito ouvir a palavra de Deus.

[[v44-13-8]]

^<<v44-13-8,8>>^ Mas resistia-lhes Elimas, o encantador (que assim se interpreta o seu nome), procurando apartar da fé o procônsul.

[[v44-13-9]]

^<<v44-13-9,9>>^ Todavia Saulo, que também se chama  Paulo, cheio do Espírito Santo, e fixando os olhos nele, disse:

[[v44-13-10]]

^<<v44-13-10,10>>^ Ó filho do diabo, cheio de todo o engano e de toda a malícia, inimigo de toda a justiça, não cessarás de perturbar os retos caminhos do Senhor?

[[v44-13-11]]

^<<v44-13-11,11>>^ Eis aí, pois, agora contra ti a mão do Senhor, e ficarás cego, sem ver o sol por algum tempo. E no mesmo instante a escuridão e as trevas caíram sobre ele, e, andando à roda, buscava a quem o guiasse pela mão.

[[v44-13-12]]

^<<v44-13-12,12>>^ Então o procônsul, vendo o que havia acontecido, creu, maravilhado da doutrina do Senhor.

[[v44-13-13]]

^<<v44-13-13,13>>^ E, partindo de Pafos, Paulo e os que estavam com ele chegaram a Perge, da Panfília. Mas João, apartando-se deles, voltou para Jerusalém.

[[v44-13-14]]

^<<v44-13-14,14>>^ E eles, saindo de Perge, chegaram a Antioquia, da Pisídia, e, entrando na sinagoga, num dia de sábado, assentaram-se;

[[v44-13-15]]

^<<v44-13-15,15>>^ E, depois da lição da lei e dos profetas, lhes mandaram dizer os principais da sinagoga: Varões irmãos, se tendes alguma palavra de consolação para o povo, falai.

[[v44-13-16]]

^<<v44-13-16,16>>^ E, levantando-se Paulo, e pedindo silêncio com a mão, disse: Varões israelitas, e os que temeis a Deus, ouvi:

[[v44-13-17]]

^<<v44-13-17,17>>^ O Deus deste povo d’Israel escolheu a nossos pais, e exaltou o povo, sendo eles estrangeiros na terra do Egito; e com braço poderoso o tirou dela;

[[v44-13-18]]

^<<v44-13-18,18>>^ E suportou os seus costumes no deserto por espaço de quase quarenta anos.

[[v44-13-19]]

^<<v44-13-19,19>>^ E, destruindo a sete nações da terra de Canaã, deu-lhes por sorte a terra deles.

[[v44-13-20]]

^<<v44-13-20,20>>^ E, depois disto por quase quatrocentos e cinquenta anos, lhes  deu juízes, até ao profeta Samuel.

[[v44-13-21]]

^<<v44-13-21,21>>^ E depois pediram um  rei, e Deus lhes deu por quarenta anos, a Saul filho de Quis, varão da tribo de Benjamim.

[[v44-13-22]]

^<<v44-13-22,22>>^ E, quando este foi retirado, lhes levantou como rei a Davi, ao qual também deu testemunho, e disse: Achei a Davi filho  de Jessé, varão conforme o meu coração, que executará toda a minha vontade.

[[v44-13-23]]

^<<v44-13-23,23>>^ Da descendência deste, conforme a promessa, levantou Deus a Jesus para Salvador d’Israel;

[[v44-13-24]]

^<<v44-13-24,24>>^ Tendo primeiramente João, antes da vinda dele, pregado a todo o povo d’Israel o batismo do arrependimento.

[[v44-13-25]]

^<<v44-13-25,25>>^ Mas João, quando completava a carreira, disse: Quem pensais vós que eu sou? Eu não sou o Cristo ; mas eis que após mim vem aquele a quem não sou digno de desatar as alparcas dos pés.

[[v44-13-26]]

^<<v44-13-26,26>>^ Varões irmãos, filhos da geração d’Abraão, e os que dentre vós temem a Deus, a vós vos é enviada a palavra desta salvação.

[[v44-13-27]]

^<<v44-13-27,27>>^ Por não terem conhecido a este, os que habitavam em Jerusalém, e os seus príncipes, condenaram-no, cumprindo assim as vozes dos profetas que se leem todos os sábados.

[[v44-13-28]]

^<<v44-13-28,28>>^ E, embora não achassem alguma causa de morte, pediram a Pilatos que ele fosse morto.

[[v44-13-29]]

^<<v44-13-29,29>>^ E, havendo eles cumprido todas as coisas  que dele estavam escritas, tirando- o  do madeiro, o  puseram na sepultura;

[[v44-13-30]]

^<<v44-13-30,30>>^ Mas Deus o ressuscitou dos mortos.

[[v44-13-31]]

^<<v44-13-31,31>>^ E ele por muitos dias foi visto pelos que subiram com ele da Galileia a Jerusalém, e são suas testemunhas para com o povo.

[[v44-13-32]]

^<<v44-13-32,32>>^ E nós vos anunciamos que a promessa que foi feita aos pais, Deus a cumpriu, a nós, seus filhos, ressuscitando a Jesus:

[[v44-13-33]]

^<<v44-13-33,33>>^ Como também está escrito no salmo segundo: Meu filho és tu, hoje te gerei.

[[v44-13-34]]

^<<v44-13-34,34>>^ E que o ressuscitaria dos mortos, para nunca mais tornar à corrupção disse-o assim. As santas e fiéis bênçãos de Davi vos darei.

[[v44-13-35]]

^<<v44-13-35,35>>^ Pelo que também em outro salmo  diz: Não permitirás que o teu santo veja corrupção.

[[v44-13-36]]

^<<v44-13-36,36>>^ Porque, na verdade, tendo Davi no seu tempo servido conforme a vontade de Deus, dormiu, e foi posto junto de seus pais e viu a corrupção.

[[v44-13-37]]

^<<v44-13-37,37>>^ Mas aquele a quem Deus ressuscitou nenhuma corrupção viu.

[[v44-13-38]]

^<<v44-13-38,38>>^ Seja-vos pois notório, varões irmãos, que por este se vos anuncia a remissão dos pecados.

[[v44-13-39]]

^<<v44-13-39,39>>^ E de tudo o que, pela lei de Moisés, não pudestes ser justificados por ele é justificado todo aquele que crê.

[[v44-13-40]]

^<<v44-13-40,40>>^ Vede pois que não venha sobre vós o que está dito nos profetas:

[[v44-13-41]]

^<<v44-13-41,41>>^ Vede, ó desprezadores, e espantai-vos e desaparecei; porque opero uma  obra em vossos dias, obra tal que não crereis, se alguém vo-la contar.

[[v44-13-42]]

^<<v44-13-42,42>>^ E, saídos os judeus da sinagoga, os gentios rogaram que no sábado seguinte lhes fossem ditas as mesmas coisas.

[[v44-13-43]]

^<<v44-13-43,43>>^ E, despedida a sinagoga, muitos dos judeus e dos prosélitos religiosos seguiram Paulo e Barnabé: os quais falando-lhes, os exortavam a que permanecessem na graça de Deus.

[[v44-13-44]]

^<<v44-13-44,44>>^ E no sábado seguinte ajuntou-se quase toda a cidade a ouvir a palavra de Deus.

[[v44-13-45]]

^<<v44-13-45,45>>^ Então os judeus, vendo a multidão, encheram-se de inveja: e, blasfemando, contradiziam o que Paulo dizia.

[[v44-13-46]]

^<<v44-13-46,46>>^ Mas Paulo e Barnabé, usando de ousadia, disseram: Era mister que a vós se vos pregasse primeiro a palavra de Deus; mas, visto que a rejeitais, e vos não julgais dignos da vida eterna, eis que nos voltamos para os gentios.

[[v44-13-47]]

^<<v44-13-47,47>>^ Porque o Senhor assim no-lo mandou: Eu te pus para luz dos gentios, para que sejas de salvação até aos confins da terra.

[[v44-13-48]]

^<<v44-13-48,48>>^ E os gentios, ouvindo isto , alegraram-se, e glorificavam a palavra do Senhor; e creram todos quantos estavam ordenados para a vida eterna.

[[v44-13-49]]

^<<v44-13-49,49>>^ E a palavra do Senhor se divulgava por toda aquela província.

[[v44-13-50]]

^<<v44-13-50,50>>^ Mas os judeus incitaram algumas mulheres religiosas e honestas, e os principais da cidade, e levantaram perseguição contra Paulo e Barnabé, e os lançaram fora dos seus termos.

[[v44-13-51]]

^<<v44-13-51,51>>^ Sacudindo, porém, contra eles o pó dos seus pés, partiram para Icônio.

[[v44-13-52]]

^<<v44-13-52,52>>^ E os discípulos estavam cheios de alegria e do Espírito Santo.

'''

xref:044-atos/044-atos-012.adoc#v44-12-0[&#60; Capítulo Anterior] | <<v44-13-0,Topo>> | xref:044-atos/044-atos-014.adoc#v44-14-0[Próximo Capítulo &#62;]