include::./index.adoc[]

[[v44-3-0]]
=== Atos, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-3-1]]

^<<v44-3-1,1>>^ E PEDRO e João subiam juntos ao templo à hora da oração, a nona.

[[v44-3-2]]

^<<v44-3-2,2>>^ E era trazido um varão que desde o ventre de sua mãe era coxo, o qual todos os dias punham à porta do templo, chamada Formosa, para pedir esmola aos que entravam.

[[v44-3-3]]

^<<v44-3-3,3>>^ O qual, vendo a Pedro e a João, que iam entrando no templo, pediu que lhe dessem uma esmola.

[[v44-3-4]]

^<<v44-3-4,4>>^ E Pedro, com João, fitando os olhos nele, disse: Olha para nós.

[[v44-3-5]]

^<<v44-3-5,5>>^ E olhou para eles, esperando receber deles alguma coisa.

[[v44-3-6]]

^<<v44-3-6,6>>^ E disse Pedro: Não tenho prata nem ouro; mas o que tenho isso te dou. Em nome de Jesus Cristo o Nazareno, levanta-te e anda.

[[v44-3-7]]

^<<v44-3-7,7>>^ E, tomando-o pela mão direita, o  levantou, e logo os seus pés e artelhos se firmaram.

[[v44-3-8]]

^<<v44-3-8,8>>^ E, saltando ele, pôs-se em pé, e andou, e entrou com eles no templo, andando, e saltando, e louvando a Deus.

[[v44-3-9]]

^<<v44-3-9,9>>^ E todo o povo o viu andar e louvar a Deus;

[[v44-3-10]]

^<<v44-3-10,10>>^ E conheciam-no, pois era ele o que se assentava a pedir esmola à porta Formosa do templo; e ficaram cheios de pasmo e assombro, pelo que lhe acontecera.

[[v44-3-11]]

^<<v44-3-11,11>>^ E, apegando-se o coxo, que fora curado, a Pedro e João, todo o povo correu atônito para junto deles, ao alpendre chamado de Salomão.

[[v44-3-12]]

^<<v44-3-12,12>>^ E quando Pedro viu isto disse ao povo: Varões israelitas, por que vos maravilhais disto? Ou, por que olhais tanto para nós, como se por nossa própria virtude ou santidade fizéssemos andar este homem?

[[v44-3-13]]

^<<v44-3-13,13>>^ O Deus d’Abraão, e de Isaque e de Jacó, o Deus de nossos pais, glorificou a seu filho Jesus, a quem vós entregastes e perante a face de Pilatos negastes tendo ele determinado que fosse solto.

[[v44-3-14]]

^<<v44-3-14,14>>^ Mas vós negastes o Santo e o Justo, e pedistes que se vos desse um homem homicida.

[[v44-3-15]]

^<<v44-3-15,15>>^ E matastes o Príncipe da vida, ao qual Deus ressuscitou dos mortos, do que nós somos testemunhas.

[[v44-3-16]]

^<<v44-3-16,16>>^ E pela fé no seu nome fez o seu nome fortalecer a este que vedes e conheceis; e a fé que é por ele deu a este, na presença de todos vós, esta perfeita saúde.

[[v44-3-17]]

^<<v44-3-17,17>>^ E agora, irmãos, eu sei que o fizestes por ignorância, como também os vossos príncipes.

[[v44-3-18]]

^<<v44-3-18,18>>^ Mas Deus assim cumpriu o que já dantes pela boca de todos os seus profetas havia anunciado; que o Cristo havia de padecer.

[[v44-3-19]]

^<<v44-3-19,19>>^ Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados, e venham assim os tempos do refrigério pela presença do Senhor.

[[v44-3-20]]

^<<v44-3-20,20>>^ E envie ele a Jesus Cristo, que já  dantes vos foi pregado.

[[v44-3-21]]

^<<v44-3-21,21>>^ O qual convém que o céu contenha até aos tempos da restauração de tudo, dos quais Deus falou pela boca de todos os seus santos profetas, desde o princípio.

[[v44-3-22]]

^<<v44-3-22,22>>^ Porque Moisés disse: O Senhor vosso Deus levantará dentre vossos irmãos um profeta semelhante a mim: a ele ouvireis em tudo quanto vos disser.

[[v44-3-23]]

^<<v44-3-23,23>>^ E acontecerá que toda a alma que não escutar esse profeta será exterminada dentre o povo.

[[v44-3-24]]

^<<v44-3-24,24>>^ E todos os profetas, desde Samuel, todos quantos depois falaram, também anunciaram estes dias.

[[v44-3-25]]

^<<v44-3-25,25>>^ Vós sois os filhos dos profetas e do concerto que Deus fez com nossos pais, dizendo a Abraão: Na tua descendência serão benditas todas as famílias da terra.

[[v44-3-26]]

^<<v44-3-26,26>>^ Ressuscitando Deus a seu Filho Jesus, primeiro o enviou a vós, para que nisso vos abençoasse, e vos desviasse, a cada um, das vossas maldades.

'''

xref:044-atos/044-atos-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v44-3-0,Topo>> | xref:044-atos/044-atos-004.adoc#v44-4-0[Próximo Capítulo &#62;]