include::./index.adoc[]

[[v44-16-0]]
=== Atos, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-16-1]]

^<<v44-16-1,1>>^ E CHEGOU a Derbe e Listra. E eis que estava ali um  certo discípulo por nome Timóteo, filho de uma judia que era crente, mas de pai grego;

[[v44-16-2]]

^<<v44-16-2,2>>^ Do qual davam bom  testemunho os irmãos que estavam em Listra e em Icônio.

[[v44-16-3]]

^<<v44-16-3,3>>^ Paulo quis que este fosse com ele: e tomando-o, o circuncidou, por causa dos judeus que estavam naqueles lugares; porque todos sabiam que seu pai era grego.

[[v44-16-4]]

^<<v44-16-4,4>>^ E, quando iam passando pelas cidades, lhes entregavam, para serem observados, os decretos que haviam sido estabelecidos pelos apóstolos e anciãos em Jerusalém.

[[v44-16-5]]

^<<v44-16-5,5>>^ De sorte que as igrejas eram confirmadas na fé, e cada dia cresciam em número.

[[v44-16-6]]

^<<v44-16-6,6>>^ E, passando pela Frígia e pela província da Galácia, foram impedidos pelo Espírito Santo de anunciar a palavra na Ásia.

[[v44-16-7]]

^<<v44-16-7,7>>^ E, quando chegaram a Mísia, intentavam ir para Bitínia, mas o Espírito de Jesus não lho permitiu.

[[v44-16-8]]

^<<v44-16-8,8>>^ E, tendo passado por Mísia, desceram a Troas.

[[v44-16-9]]

^<<v44-16-9,9>>^ E Paulo teve de noite uma visão, em que se apresentou um varão da Macedônia, e lhe rogou, dizendo: Passa à Macedônia, e ajuda-nos.

[[v44-16-10]]

^<<v44-16-10,10>>^ E, logo depois desta visão, procuramos partir para a Macedônia, concluindo que o Senhor nos chamava para lhes anunciarmos o evangelho.

[[v44-16-11]]

^<<v44-16-11,11>>^ E, navegando de Troas, fomos correndo em caminho direito para a Samotrácia, e no dia  seguinte para Nápoles;

[[v44-16-12]]

^<<v44-16-12,12>>^ E dali para Filipos, que é a primeira cidade desta parte da Macedônia, e é  uma colônia; e estivemos alguns dias nesta cidade.

[[v44-16-13]]

^<<v44-16-13,13>>^ E no dia de sábado saímos fora das portas, para a beira do rio, onde julgávamos ter lugar para oração; e, assentando-nos, falamos às mulheres que ali  se ajuntaram.

[[v44-16-14]]

^<<v44-16-14,14>>^ E uma certa mulher, chamada Lídia, vendedora de púrpura, da cidade de Tiatira, e que servia a Deus, nos  ouvia, e o Senhor lhe abriu o coração para que estivesse atenta ao que Paulo dizia.

[[v44-16-15]]

^<<v44-16-15,15>>^ E, depois que foi batizada ela  e a sua casa, nos  rogou, dizendo: Se haveis julgado que eu seja fiel ao Senhor, entrai em minha casa, e ficai ali.  E nos constrangeu a isso.

[[v44-16-16]]

^<<v44-16-16,16>>^ E aconteceu que, indo nós à oração, nos saiu ao encontro uma jovem, que tinha espírito de adivinhação, a qual, adivinhando, dava grande lucro aos seus senhores.

[[v44-16-17]]

^<<v44-16-17,17>>^ Esta, seguindo a Paulo e a nós, clamava, dizendo: Estes homens, que nos anunciam o caminho da salvação, são servos do Deus Altíssimo.

[[v44-16-18]]

^<<v44-16-18,18>>^ E isto fez ela por muitos dias. Mas Paulo, perturbado, voltou-se, e disse ao espírito: Em nome de Jesus Cristo, te mando que saias dela. E na mesma hora saiu.

[[v44-16-19]]

^<<v44-16-19,19>>^ E, vendo seus senhores que a esperança do seu lucro estava perdida, prenderam Paulo e Silas, e os  levaram à praça, à presença dos magistrados.

[[v44-16-20]]

^<<v44-16-20,20>>^ E, apresentando-os aos magistrados, disseram: Estes homens sendo judeus, perturbaram a nossa cidade.

[[v44-16-21]]

^<<v44-16-21,21>>^ E nos expõem costumes que nos não é lícito receber nem praticar, visto que somos romanos.

[[v44-16-22]]

^<<v44-16-22,22>>^ E a multidão se levantou unida contra eles, e os magistrados, rasgando-lhes os vestidos, mandaram açoitá- los  com varas.

[[v44-16-23]]

^<<v44-16-23,23>>^ E, havendo-lhes dado muitos açoites, os  lançaram na prisão, mandando ao carcereiro que os guardasse com segurança.

[[v44-16-24]]

^<<v44-16-24,24>>^ O qual, tendo recebido tal ordem, os lançou no cárcere interior, e lhes segurou os pés no tronco.

[[v44-16-25]]

^<<v44-16-25,25>>^ E, perto da meia noite, Paulo e Silas oravam e cantavam hinos a Deus, e os outros  presos os escutavam.

[[v44-16-26]]

^<<v44-16-26,26>>^ E de repente sobreveio um tão grande terremoto, que os alicerces do cárcere se moveram, e logo se abriram todas as portas, e foram soltas as prisões de todos.

[[v44-16-27]]

^<<v44-16-27,27>>^ E, acordando o carcereiro, e vendo abertas as portas da prisão, tirou a espada, e quis matar-se, cuidando que os presos já  tinham fugido.

[[v44-16-28]]

^<<v44-16-28,28>>^ Mas Paulo clamou com grande voz, dizendo: Não te faças nenhum mal, que todos aqui estamos.

[[v44-16-29]]

^<<v44-16-29,29>>^ E, pedindo luz, saltou dentro, e, todo trêmulo, se prostrou ante Paulo e Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ E, tirando-os para fora, disse: Senhores, que é necessário que eu faça para me salvar?

[[v44-16-31]]

^<<v44-16-31,31>>^ E eles disseram: Crê no Senhor Jesus Cristo, e serás salvo, tu e a tua casa.

[[v44-16-32]]

^<<v44-16-32,32>>^ E lhe pregavam a palavra do Senhor, e a todos os que estavam em sua casa.

[[v44-16-33]]

^<<v44-16-33,33>>^ E, tomando-os ele consigo naquela mesma hora da noite, lavou-lhes os vergões; e logo foi batizado, ele e todos os seus.

[[v44-16-34]]

^<<v44-16-34,34>>^ E, levando-os a sua casa, lhes  pôs a mesa; e, na sua crença em Deus alegrou-se com toda a sua casa.

[[v44-16-35]]

^<<v44-16-35,35>>^ E, sendo já dia, os magistrados mandaram quadrilheiros, dizendo: Soltai aqueles homens.

[[v44-16-36]]

^<<v44-16-36,36>>^ E o carcereiro anunciou a Paulo estas palavras, dizendo: Os magistrados mandaram que vos soltasse; agora pois saí, e ide em paz.

[[v44-16-37]]

^<<v44-16-37,37>>^ Mas Paulo replicou: Açoitaram-nos publicamente, e, sem sermos condenados, sendo homens romanos, nos lançaram na prisão, e agora encobertamente nos lançam fora? Não será  assim; mas venham eles mesmos e tirem-nos para fora.

[[v44-16-38]]

^<<v44-16-38,38>>^ E os quadrilheiros foram dizer aos magistrados estas palavras; e eles  temeram, ouvindo que eram romanos.

[[v44-16-39]]

^<<v44-16-39,39>>^ E, vindo, lhes dirigiram súplicas; e, tirando-os para fora, lhes pediram que saíssem da cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ E, saindo da prisão, entraram em casa  de Lídia, e, vendo os irmãos, os confortaram, e depois  partiram.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]