include::./index.adoc[]

[[v44-1-0]]
=== Atos, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-1-1]]

^<<v44-1-1,1>>^ FIZ o primeiro tratado, ó Teófilo, acerca de tudo que Jesus começou, não só a fazer, mas a ensinar,

[[v44-1-2]]

^<<v44-1-2,2>>^ Até ao dia em que foi recebido em cima, depois de ter dado mandamentos, pelo Espírito Santo, aos apóstolos que escolhera;

[[v44-1-3]]

^<<v44-1-3,3>>^ Aos quais também, depois de ter padecido, se apresentou vivo, com muitas e infalíveis provas, sendo visto por eles por espaço de quarenta dias, e falando do que respeita ao reino de Deus.

[[v44-1-4]]

^<<v44-1-4,4>>^ E, estando com eles, determinou-lhes que não se ausentassem de Jerusalém, mas que esperassem a promessa do Pai, que (disse ele)  de mim ouvistes.

[[v44-1-5]]

^<<v44-1-5,5>>^ Porque, na verdade, João batizou com água, mas vós sereis batizados com o Espírito Santo; não muito depois destes dias.

[[v44-1-6]]

^<<v44-1-6,6>>^ Aqueles pois que se haviam reunido perguntaram-lhe, dizendo: Senhor, restaurarás tu neste tempo o reino a Israel?

[[v44-1-7]]

^<<v44-1-7,7>>^ E disse-lhes: Não vos pertence saber os tempos ou as estações que o Pai estabeleceu pelo seu próprio poder.

[[v44-1-8]]

^<<v44-1-8,8>>^ Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas, tanto em Jerusalém como em toda a Judeia e Samaria, e até aos confins da terra.

[[v44-1-9]]

^<<v44-1-9,9>>^ E quando dizia isto, vendo-o eles, foi elevado às alturas, e uma nuvem o recebeu, ocultando-o  a seus olhos.

[[v44-1-10]]

^<<v44-1-10,10>>^ E estando com os olhos fitos no céu, enquanto ele subia, eis que junto deles se puseram dois varões vestidos de branco,

[[v44-1-11]]

^<<v44-1-11,11>>^ Os quais lhe disseram: Varões galileus, por que estais olhando para o céu? Esse Jesus, que dentre vós foi recebido em cima no céu, há de vir assim como para o céu o vistes ir.

[[v44-1-12]]

^<<v44-1-12,12>>^ Então voltaram para Jerusalém, do monte chamado das Oliveiras, o qual está perto de Jerusalém, à distância do caminho de um sábado.

[[v44-1-13]]

^<<v44-1-13,13>>^ E, entrando, subiram ao cenáculo, onde habitavam, Pedro e Tiago, João e André, Filipe e Tomé, Bartolomeu e Mateus, Tiago, filho  de Alfeu, Simão, o zelador, e Judas, de Tiago.

[[v44-1-14]]

^<<v44-1-14,14>>^ Todos estes perseveravam unanimemente em oração e súplicas, com as mulheres, e Maria mãe de Jesus, e com seus irmãos.

[[v44-1-15]]

^<<v44-1-15,15>>^ E naqueles dias, levantando-se Pedro no meio dos discípulos, (ora a multidão junta era de quase de cento e vinte pessoas) disse:

[[v44-1-16]]

^<<v44-1-16,16>>^ Varões irmãos, convinha que se cumprisse a escritura que o Espírito Santo predisse pela boca de Davi, acerca de Judas, que foi o guia daqueles que prenderam a Jesus;

[[v44-1-17]]

^<<v44-1-17,17>>^ Porque foi contado conosco e alcançou sorte neste ministério.

[[v44-1-18]]

^<<v44-1-18,18>>^ Ora este adquiriu um campo com o galardão da iniquidade; e, precipitando-se, rebentou pelo meio, e todas as suas entranhas se derramaram.

[[v44-1-19]]

^<<v44-1-19,19>>^ E foi notório a todos os que habitam em Jerusalém; de maneira que na sua própria língua esse campo se chama Aceldama, isto é, Campo de sangue.

[[v44-1-20]]

^<<v44-1-20,20>>^ Porque no livro dos Salmos está escrito: Fique deserta a sua habitação, e não haja quem nela habite, e tome outro o seu bispado.

[[v44-1-21]]

^<<v44-1-21,21>>^ É necessário pois que, dos varões que conviveram conosco todo o tempo em que o Senhor Jesus entrou e saiu dentre nós,

[[v44-1-22]]

^<<v44-1-22,22>>^ Começando desde o batismo de João até ao dia em que dentre nós foi recebido em cima, um deles se faça conosco testemunha da sua ressurreição.

[[v44-1-23]]

^<<v44-1-23,23>>^ E apresentaram dois: José, chamado Barsabás, que tinha por sobrenome o Justo, e Matias.

[[v44-1-24]]

^<<v44-1-24,24>>^ E, orando, disseram: Tu, Senhor, conhecedor dos corações de todos, mostra qual destes dois tens escolhido,

[[v44-1-25]]

^<<v44-1-25,25>>^ Para que tome parte neste ministério e apostolado, de que Judas se desviou, para ir para o seu próprio lugar.

[[v44-1-26]]

^<<v44-1-26,26>>^ E lançando-lhes sortes, caiu a sorte sobre Matias. E por voto comum foi contado com os onze apóstolos.

'''

xref:043-joao/043-joao-021.adoc#v43-21-0[&#60; Capítulo Anterior] | <<v44-1-0,Topo>> | xref:044-atos/044-atos-002.adoc#v44-2-0[Próximo Capítulo &#62;]