include::./index.adoc[]

[[v44-19-0]]
=== Atos, 19
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-19-1]]

^<<v44-19-1,1>>^ E SUCEDEU que, enquanto Apolo estava em Corinto, Paulo, tendo passado por todas as regiões  superiores, chegou a Éfeso; e achando ali alguns discípulos,

[[v44-19-2]]

^<<v44-19-2,2>>^ Disse-lhes: Recebestes vós já  o Espírito Santo quando crestes? E eles disseram-lhe: Nós nem ainda ouvimos que haja Espírito Santo.

[[v44-19-3]]

^<<v44-19-3,3>>^ Perguntou-lhes então: Em que sois batizados então? E eles disseram: No batismo de João.

[[v44-19-4]]

^<<v44-19-4,4>>^ Mas Paulo disse: Certamente João batizou com o batismo do arrependimento, dizendo ao povo que cresse no que após ele havia de vir, isto é, em Jesus Cristo.

[[v44-19-5]]

^<<v44-19-5,5>>^ E os que ouviram foram batizados em nome do Senhor Jesus.

[[v44-19-6]]

^<<v44-19-6,6>>^ E, impondo-lhes Paulo as mãos, veio sobre eles o Espírito Santo; e falavam línguas, e profetizavam.

[[v44-19-7]]

^<<v44-19-7,7>>^ E estes eram, ao todo, uns doze varões.

[[v44-19-8]]

^<<v44-19-8,8>>^ E, entrando na sinagoga, falou ousadamente por espaço de três meses, disputando e persuadindo-os acerca do reino de Deus.

[[v44-19-9]]

^<<v44-19-9,9>>^ Mas, como alguns deles se endurecessem e não obedecessem, falando mal do Caminho perante a multidão, retirou-se deles, e separou os discípulos, disputando todos os dias na escola de um certo  Tirano.

[[v44-19-10]]

^<<v44-19-10,10>>^ E durou isto por espaço de dois anos; de tal maneira que todos os que habitavam na Ásia ouviram a palavra do Senhor Jesus, assim judeus como gregos.

[[v44-19-11]]

^<<v44-19-11,11>>^ E Deus pelas mãos de Paulo fazia maravilhas extraordinárias.

[[v44-19-12]]

^<<v44-19-12,12>>^ De sorte que até os lenços e aventais se levavam do seu corpo aos enfermos, e as enfermidades fugiam deles, e os espíritos malignos saíam.

[[v44-19-13]]

^<<v44-19-13,13>>^ E alguns dos exorcistas judeus ambulantes tentavam invocar o nome do Senhor Jesus sobre os que tinham espíritos malignos, dizendo: Esconjuro-vos por Jesus a quem Paulo prega.

[[v44-19-14]]

^<<v44-19-14,14>>^ E os que faziam isto eram sete filhos de Sceva, judeu, principal dos sacerdotes.

[[v44-19-15]]

^<<v44-19-15,15>>^ Respondendo, porém, o espírito maligno, disse: Conheço a Jesus, e bem sei quem  é Paulo; mas vós quem sois?

[[v44-19-16]]

^<<v44-19-16,16>>^ E, saltando neles o homem que tinha o espírito maligno, e assenhoreando-se de dois, pôde mais do que eles; de tal maneira que, nus e feridos, fugiram daquela casa.

[[v44-19-17]]

^<<v44-19-17,17>>^ E foi isto notório a todos os que habitavam em Éfeso, tanto judeus como gregos; e caiu temor sobre todos eles, e o nome do Senhor Jesus era engrandecido.

[[v44-19-18]]

^<<v44-19-18,18>>^ E muitos dos que tinham crido vinham, confessando e publicando os seus feitos.

[[v44-19-19]]

^<<v44-19-19,19>>^ Também muitos dos que seguiam artes mágicas trouxeram os seus livros, e os queimaram na presença de todos, e, feita a conta do seu preço, acharam que montava  a cinquenta mil peças  de prata.

[[v44-19-20]]

^<<v44-19-20,20>>^ Assim a palavra do Senhor crescia poderosamente e prevalecia.

[[v44-19-21]]

^<<v44-19-21,21>>^ E, cumpridas estas coisas , Paulo propôs, em espírito, ir a Jerusalém, passando pela Macedônia e pela Acaia, dizendo: Depois que houver estado ali, importa-me ver também Roma.

[[v44-19-22]]

^<<v44-19-22,22>>^ E, enviando à Macedônia dois daqueles que o serviam Timóteo e Erasto, ficou ele por algum tempo na Ásia.

[[v44-19-23]]

^<<v44-19-23,23>>^ E, naquele mesmo tempo, houve um não pequeno alvoroço, acerca do Caminho.

[[v44-19-24]]

^<<v44-19-24,24>>^ Porque um certo ourives da prata, por nome Demétrio, que fazia de prata nichos de Diana, dava não pouco lucro aos artífices,

[[v44-19-25]]

^<<v44-19-25,25>>^ Aos quais, havendo-os ajuntado com os oficiais de obras semelhantes, disse: Varões, vós bem sabeis que deste ofício temos a nossa prosperidade;

[[v44-19-26]]

^<<v44-19-26,26>>^ E bem vedes e ouvis que não só em Éfeso, mas até quase em toda a Ásia, este Paulo tem convencido e afastado uma grande multidão, dizendo que não são deuses os que se fazem com as mãos.

[[v44-19-27]]

^<<v44-19-27,27>>^ E não somente há o perigo de que a nossa profissão caia em descrédito, mas também de que o próprio templo da grande deusa Diana seja estimado em nada, vindo a majestade daquela que toda a Ásia e o mundo veneram a ser destruída.

[[v44-19-28]]

^<<v44-19-28,28>>^ E, ouvindo-o, encheram-se de ira, e clamaram, dizendo: Grande é  a Diana dos efésios.

[[v44-19-29]]

^<<v44-19-29,29>>^ E encheu-se de confusão toda a cidade, e unânimes correram ao teatro, arrebatando a Gaio e a Aristarco, macedônios, companheiros de Paulo na viagem.

[[v44-19-30]]

^<<v44-19-30,30>>^ E, querendo Paulo apresentar-se ao povo, não lho permitiram os discípulos.

[[v44-19-31]]

^<<v44-19-31,31>>^ E também alguns dos principais da Ásia, que eram seus amigos, lhe rogaram que não se apresentasse no teatro.

[[v44-19-32]]

^<<v44-19-32,32>>^ Uns  pois clamavam de uma maneira, outros de outra, porque o ajuntamento era confuso; e os mais deles não sabiam por que causa se tinham ajuntado.

[[v44-19-33]]

^<<v44-19-33,33>>^ Então tiraram Alexandre dentre a multidão, impelindo-o os judeus para diante; e Alexandre, acenando com a mão, queria dar razão disto ao povo.

[[v44-19-34]]

^<<v44-19-34,34>>^ Mas quando conheceram que era judeu, todos unanimemente levantaram a voz, clamando por espaço de quase duas horas: Grande é  a Diana dos efésios.

[[v44-19-35]]

^<<v44-19-35,35>>^ Então o escrivão da cidade , tendo apaziguado a multidão, disse: Varões efésios, qual é o homem que não sabe que a cidade dos efésios é a guardadora do templo da grande deusa Diana, e da imagem  que desceu de Júpiter?

[[v44-19-36]]

^<<v44-19-36,36>>^ Ora, não podendo isto ser contraditado, convém que vos aplaqueis, nada façais temerariamente;

[[v44-19-37]]

^<<v44-19-37,37>>^ Porque estes homens que aqui  trouxestes nem são sacrílegos nem blasfemam da vossa deusa.

[[v44-19-38]]

^<<v44-19-38,38>>^ Mas, se Demétrio e os artífices que estão com ele têm alguma coisa contra alguém, há audiências e há procônsules: que se acusem uns aos outros;

[[v44-19-39]]

^<<v44-19-39,39>>^ E, se alguma outra coisa demandais, averiguar-se-á em legítimo ajuntamento.

[[v44-19-40]]

^<<v44-19-40,40>>^ Na verdade até corremos perigo de que, por hoje, sejamos acusados de sedição, não havendo causa alguma com que possamos justificar este concurso.

[[v44-19-41]]

^<<v44-19-41,41>>^ E, tendo dito isto, despediu o ajuntamento.

'''

xref:044-atos/044-atos-018.adoc#v44-18-0[&#60; Capítulo Anterior] | <<v44-19-0,Topo>> | xref:044-atos/044-atos-020.adoc#v44-20-0[Próximo Capítulo &#62;]