include::./index.adoc[]

[[v44-10-0]]
=== Atos, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-10-1]]

^<<v44-10-1,1>>^ E HAVIA em Cesareia um varão por nome Cornélio, centurião da coorte chamada italiana.

[[v44-10-2]]

^<<v44-10-2,2>>^ Piedoso e temente a Deus, com toda a sua casa, o qual fazia muitas esmolas ao povo, e de contínuo orava a Deus.

[[v44-10-3]]

^<<v44-10-3,3>>^ Este , quase à hora nona do dia, viu claramente numa visão um anjo de Deus, que se dirigia para ele e dizia: Cornélio.

[[v44-10-4]]

^<<v44-10-4,4>>^ O qual, fixando os olhos nele, e muito atemorizado, disse: Que é, Senhor? Eu disse-lhe: As tuas orações e as tuas esmolas têm subido para memória diante de Deus;

[[v44-10-5]]

^<<v44-10-5,5>>^ Agora, pois, envia homens a Jope, e manda chamar a Simão, que tem por sobrenome Pedro.

[[v44-10-6]]

^<<v44-10-6,6>>^ Este está com um certo  Simão curtidor, que tem a sua casa junto do mar. Ele te dirá o que deves fazer.

[[v44-10-7]]

^<<v44-10-7,7>>^ E, retirando-se o anjo que lhe falava, chamou dois dos seus criados, e a um piedoso soldado dos que estavam ao seu serviço.

[[v44-10-8]]

^<<v44-10-8,8>>^ E, havendo-lhes contado tudo, os enviou a Jope.

[[v44-10-9]]

^<<v44-10-9,9>>^ E no dia seguinte indo eles seu caminho, e estando já perto da cidade subiu Pedro ao terraço para orar, quase à hora sexta.

[[v44-10-10]]

^<<v44-10-10,10>>^ E, tendo fome, quis comer; e, enquanto lho preparavam, sobreveio-lhe um arrebatamento de sentidos.

[[v44-10-11]]

^<<v44-10-11,11>>^ E viu o céu aberto, e que descia um vaso, como se fosse um grande lençol atado pelas quatro pontas, e vindo para a terra.

[[v44-10-12]]

^<<v44-10-12,12>>^ No qual havia de todos os animais quadrúpedes e répteis da terra, e aves do céu.

[[v44-10-13]]

^<<v44-10-13,13>>^ E foi-lhe dirigida uma voz: Levanta-te, Pedro, mata e come.

[[v44-10-14]]

^<<v44-10-14,14>>^ Mas Pedro disse: De modo nenhum, Senhor, porque nunca comi coisa alguma comum e imunda.

[[v44-10-15]]

^<<v44-10-15,15>>^ E segunda vez lhe disse  a voz: Não faças tu comum ao que Deus purificou.

[[v44-10-16]]

^<<v44-10-16,16>>^ E aconteceu isto por três vezes; e o vaso tornou a recolher-se no céu.

[[v44-10-17]]

^<<v44-10-17,17>>^ E, estando Pedro duvidando entre si acerca do que seria aquela visão que tinha visto, eis que os varões que foram enviados por Cornélio pararam à porta, perguntando pela casa de Simão.

[[v44-10-18]]

^<<v44-10-18,18>>^ E, chamando, perguntaram se Simão, que tinha por sobrenome Pedro, morava ali.

[[v44-10-19]]

^<<v44-10-19,19>>^ E, pensando Pedro naquela visão, disse-lhe o Espírito: Eis que três varões te buscam.

[[v44-10-20]]

^<<v44-10-20,20>>^ Levanta-te pois, e desce, e vai com eles, não duvidando; porque eu os enviei.

[[v44-10-21]]

^<<v44-10-21,21>>^ E, descendo Pedro para junto dos varões que lhe foram enviados por Cornélio, disse: Sou eu a quem procurais; qual é a causa por que estais aqui?

[[v44-10-22]]

^<<v44-10-22,22>>^ E eles disseram: Cornélio, o centurião, varão justo e temente a Deus, e que tem bom testemunho de toda a nação dos judeus, foi avisado por um santo anjo para que te chamasse a sua casa, e ouvisse as tuas palavras.

[[v44-10-23]]

^<<v44-10-23,23>>^ Então, chamando-os para dentro, os recebeu em casa. E no dia seguinte foi Pedro com eles, e foram com ele alguns irmãos de Jope.

[[v44-10-24]]

^<<v44-10-24,24>>^ E no dia imediato chegaram a Cesareia. E Cornélio os estava esperando, tendo já  convidado os seus parentes e amigos mais íntimos.

[[v44-10-25]]

^<<v44-10-25,25>>^ E aconteceu que, entrando Pedro, saiu Cornélio a recebê-lo, e, prostrando-se a seus  pés, o adorou.

[[v44-10-26]]

^<<v44-10-26,26>>^ Mas Pedro o levantou, dizendo: Levanta-te, que eu também sou homem.

[[v44-10-27]]

^<<v44-10-27,27>>^ E, falando com ele, entrou, e achou muitos que ali  se haviam ajuntado.

[[v44-10-28]]

^<<v44-10-28,28>>^ E disse-lhes: Vós bem sabeis que não é lícito a um varão judeu ajuntar-se ou chegar-se a estrangeiros; mas Deus mostrou-me que a nenhum homem chame comum ou imundo.

[[v44-10-29]]

^<<v44-10-29,29>>^ Pelo que, sendo chamado, vim sem contradizer. Pergunto pois; por que razão mandastes chamar-me?

[[v44-10-30]]

^<<v44-10-30,30>>^ E disse Cornélio: Há quatro dias estava eu em jejum até esta hora, orando em minha casa à hora nona.

[[v44-10-31]]

^<<v44-10-31,31>>^ E eis que diante de mim se apresentou um varão com vestes resplandecentes, e disse: Cornélio, a tua oração foi ouvida, e as tuas esmolas estão em memória diante de Deus.

[[v44-10-32]]

^<<v44-10-32,32>>^ Envia pois a Jope, e manda chamar Simão, o que tem por sobrenome Pedro; este está em casa de Simão o curtidor, junto do mar, e ele, vindo, te falará.

[[v44-10-33]]

^<<v44-10-33,33>>^ E logo mandei chamar-te, e bem fizeste em vir. Agora pois estamos todos presentes diante de Deus, para ouvir tudo quanto por Deus te é mandado.

[[v44-10-34]]

^<<v44-10-34,34>>^ E, abrindo Pedro a boca, disse: Reconheço por verdade que Deus não faz acepção de pessoas;

[[v44-10-35]]

^<<v44-10-35,35>>^ Mas que lhe é agradável aquele que, em qualquer nação, o teme e obra o que é justo.

[[v44-10-36]]

^<<v44-10-36,36>>^ A palavra que ele enviou aos filho d’Israel, anunciando a paz por Jesus Cristo (este é o Senhor de todos);

[[v44-10-37]]

^<<v44-10-37,37>>^ Esta palavra, vós bem sabeis, veio por toda a Judeia, começando pela Galileia, depois do batismo que João pregou;

[[v44-10-38]]

^<<v44-10-38,38>>^ Como Deus ungiu a Jesus de Nazaré com o Espírito Santo e com virtude; o qual andou fazendo bem, e curando a todos os oprimidos do diabo, porque Deus era com ele.

[[v44-10-39]]

^<<v44-10-39,39>>^ E nós somos testemunhas de todas as coisas  que fez, tanto na terra da Judeia como em Jerusalém: ao qual mataram, pendurando-o num madeiro.

[[v44-10-40]]

^<<v44-10-40,40>>^ A este ressuscitou Deus ao terceiro dia, e fez que se manifestasse,

[[v44-10-41]]

^<<v44-10-41,41>>^ Não a todo o povo, mas às testemunhas que Deus antes ordenara; a nós, que comemos e bebemos juntamente com ele, depois que ressuscitou dos mortos.

[[v44-10-42]]

^<<v44-10-42,42>>^ E nos mandou pregar ao povo, e testificar que ele é o que por Deus foi constituído juiz dos vivos e dos mortos.

[[v44-10-43]]

^<<v44-10-43,43>>^ A este dão testemunho todos os profetas, de que todos os que nele creem receberão o perdão dos pecados pelo seu nome.

[[v44-10-44]]

^<<v44-10-44,44>>^ E, dizendo Pedro ainda estas palavras, caiu o Espírito Santo sobre todos os que ouviam a palavra.

[[v44-10-45]]

^<<v44-10-45,45>>^ E os fiéis que eram da circuncisão, todos quantos tinham vindo com Pedro, maravilharam-se de que o dom do Espírito Santo se derramasse também sobre os gentios.

[[v44-10-46]]

^<<v44-10-46,46>>^ Porque os ouviam falar línguas, e magnificar a Deus.

[[v44-10-47]]

^<<v44-10-47,47>>^ Respondeu então Pedro: Pode alguém porventura recusar a água, para que não sejam batizados estes, que também receberam como nós o Espírito Santo?

[[v44-10-48]]

^<<v44-10-48,48>>^ E mandou que fossem batizados em nome do Senhor. Então rogaram-lhe que ficasse com eles por alguns dias.

'''

xref:044-atos/044-atos-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-atos/044-atos-011.adoc#v44-11-0[Próximo Capítulo &#62;]