include::./index.adoc[]

[[v44-28-0]]
=== Atos, 28
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-28-1]]

^<<v44-28-1,1>>^ E, HAVENDO escapado, então souberam que a ilha se chamava Melita.

[[v44-28-2]]

^<<v44-28-2,2>>^ E os bárbaros usaram conosco de não pouca humanidade; porque, acendendo uma grande fogueira, nos recolheram a todos por causa da chuva que caía, e por causa do frio.

[[v44-28-3]]

^<<v44-28-3,3>>^ E, havendo Paulo ajuntado uma  quantidade de vides, e pondo-as no fogo, uma víbora, fugindo do calor, lhe acometeu a mão.

[[v44-28-4]]

^<<v44-28-4,4>>^ E os bárbaros, vendo-lhe a bicha pendurada na mão, diziam uns aos outros: Certamente este homem é homicida, visto como, escapando do mar, a Justiça não o deixa viver.

[[v44-28-5]]

^<<v44-28-5,5>>^ Mas, sacudindo ele a bicha no fogo, não padeceu nenhum mal.

[[v44-28-6]]

^<<v44-28-6,6>>^ E eles esperavam que viesse a inchar ou a cair morto de repente; mas tendo esperado já  muito, e vendo que nenhum incômodo lhe sobrevinha, mudando de parecer, diziam que era um deus.

[[v44-28-7]]

^<<v44-28-7,7>>^ E ali, próximo daquele mesmo lugar, havia umas herdades que pertenciam ao principal da ilha, por nome Públio, o qual nos recebeu e hospedou benignamente por três dias.

[[v44-28-8]]

^<<v44-28-8,8>>^ E aconteceu estar de cama enfermo de febres e disenteria o pai de Públio, que Paulo foi ver , e, havendo orado, pôs as mãos sobre ele, e o curou.

[[v44-28-9]]

^<<v44-28-9,9>>^ Feito pois isto, vieram também ter com ele os demais que na ilha tinham enfermidades, e sararam.

[[v44-28-10]]

^<<v44-28-10,10>>^ Os quais nos distinguiram também com muitas honras: e, havendo de navegar, nos  proveram das coisas necessárias.

[[v44-28-11]]

^<<v44-28-11,11>>^ E três meses depois partimos num navio de Alexandria que invernara na ilha, o qual tinha por insígnia Castor e Pólux.

[[v44-28-12]]

^<<v44-28-12,12>>^ E, chegando a Siracusa, ficamos ali  três dias.

[[v44-28-13]]

^<<v44-28-13,13>>^ Donde, indo costeando, viemos a Régio; e soprando, um dia depois, um vento do sul, chegamos no segundo dia a Putéolos.

[[v44-28-14]]

^<<v44-28-14,14>>^ Onde, achando alguns  irmãos, nos rogaram que por sete dias ficássemos com eles; e depois nos dirigimos a Roma.

[[v44-28-15]]

^<<v44-28-15,15>>^ E de lá, ouvindo os irmãos novas de nós, nos saíram ao encontro à praça de Ápio e às três Vendas, e Paulo, vendo-os, deu graças a Deus, e tomou ânimo.

[[v44-28-16]]

^<<v44-28-16,16>>^ E, logo que chegamos a Roma, o centurião entregou os presos ao general dos exércitos; mas a Paulo se lhe permitiu morar sobre si à parte, com o soldado que o guardava.

[[v44-28-17]]

^<<v44-28-17,17>>^ E aconteceu que, três dias depois, Paulo convocou os principais dos judeus, e, juntos eles, lhes disse: Varões irmãos, não havendo eu feito nada contra o povo, ou contra os ritos paternos, vim contudo preso desde Jerusalém, entregue nas mãos dos romanos;

[[v44-28-18]]

^<<v44-28-18,18>>^ Os quais, havendo-me examinado, queriam soltar- me , por não haver em mim crime algum de morte.

[[v44-28-19]]

^<<v44-28-19,19>>^ Mas, opondo-se os judeus, foi-me forçoso apelar para César, não tendo, contudo, de que acusar a minha nação.

[[v44-28-20]]

^<<v44-28-20,20>>^ Por esta causa vos chamei, para vos  ver e falar; porque pela esperança d’Israel estou com esta cadeia.

[[v44-28-21]]

^<<v44-28-21,21>>^ Então eles lhe disseram: Nós não recebemos acerca de ti cartas algumas  da Judeia, nem veio aqui algum dos irmãos, que nos anunciasse ou dissesse de ti mal algum.

[[v44-28-22]]

^<<v44-28-22,22>>^ No entanto bem quiséramos ouvir de ti o que sentes; porque, quanto a esta seita, notório nos é que em toda a parte se fala contra ela.

[[v44-28-23]]

^<<v44-28-23,23>>^ E, havendo-lhe eles assinalado um dia, muitos foram ter com ele à pousada, aos quais declarava com bom testemunho o reino de Deus, e procurava persuadi-los à fé de Jesus, tanto pela lei de Moisés como pelos  profetas, desde pela manhã até à tarde.

[[v44-28-24]]

^<<v44-28-24,24>>^ E alguns criam no que se dizia; mas outros não criam.

[[v44-28-25]]

^<<v44-28-25,25>>^ E, como ficaram entre si discordes, se despediram, dizendo Paulo esta palavra: Bem falou o Espírito Santo a nossos pais pelo profeta Isaías,

[[v44-28-26]]

^<<v44-28-26,26>>^ Dizendo: Vai a este povo, e dize: De ouvido ouvireis, e de maneira nenhuma entendereis; e, vendo, vereis, e de maneira nenhuma percebereis.

[[v44-28-27]]

^<<v44-28-27,27>>^ Porquanto o coração deste povo está endurecido, e com os ouvidos ouviram pesadamente, e fecharam os olhos, para que nunca com os olhos vejam, nem com os ouvidos ouçam, nem do coração entendam, e se convertam e eu os cure.

[[v44-28-28]]

^<<v44-28-28,28>>^ Seja-vos pois notório que esta salvação de Deus é enviada aos gentios, e eles a ouvirão.

[[v44-28-29]]

^<<v44-28-29,29>>^ E, havendo ele dito isto, partiram os judeus, tendo entre si grande contenda.

[[v44-28-30]]

^<<v44-28-30,30>>^ E Paulo ficou dois anos inteiros na sua própria habitação que alugara, e recebia todos quantos vinham vê-lo.

[[v44-28-31]]

^<<v44-28-31,31>>^ Pregando o reino de Deus, e ensinando com toda a liberdade as coisas pertencentes ao Senhor Jesus Cristo, sem impedimento algum.

'''

xref:044-atos/044-atos-027.adoc#v44-27-0[&#60; Capítulo Anterior] | <<v44-28-0,Topo>> | xref:045-romanos/045-romanos-001.adoc#v45-1-0[Próximo Capítulo &#62;]