include::./index.adoc[]

[[v44-9-0]]
=== Atos, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-9-1]]

^<<v44-9-1,1>>^ E SAULO, respirando ainda ameaças, e mortes contra os discípulos do Senhor, dirigiu-se ao sumo sacerdote,

[[v44-9-2]]

^<<v44-9-2,2>>^ E pediu-lhe cartas para Damasco para as sinagogas, a fim de que, se encontrasse alguns daquela seita, quer homens quer mulheres, os  conduzisse presos a Jerusalém.

[[v44-9-3]]

^<<v44-9-3,3>>^ E, indo no caminho, aconteceu que, chegando perto de Damasco, subitamente o cercou um resplendor de luz do céu.

[[v44-9-4]]

^<<v44-9-4,4>>^ E, caindo em terra, ouviu uma voz que lhe dizia: Saulo, Saulo, por que me persegues?

[[v44-9-5]]

^<<v44-9-5,5>>^ E ele disse: Quem és, Senhor? E disse o Senhor: Eu sou Jesus, a quem tu persegues. Duro é para ti recalcitrar contra os aguilhões.

[[v44-9-6]]

^<<v44-9-6,6>>^ E ele, tremendo e atônito, disse: Senhor, que queres que faça? E disse- lhe o Senhor: Levanta-te, e entra na cidade, e lá te será dito o que te convém fazer.

[[v44-9-7]]

^<<v44-9-7,7>>^ E os varões, que iam com ele, pararam espantados, ouvindo a voz, mas não vendo ninguém.

[[v44-9-8]]

^<<v44-9-8,8>>^ E Saulo levantou-se da terra, e, abrindo os olhos, não via a ninguém. E, guiando-o pela mão, o conduziram a Damasco.

[[v44-9-9]]

^<<v44-9-9,9>>^ E esteve três dias sem ver, e não comeu nem bebeu.

[[v44-9-10]]

^<<v44-9-10,10>>^ E havia em Damasco um certo discípulo chamado Ananias; e disse-lhe o Senhor em visão: Ananias! E ele respondeu: Eis-me aqui, Senhor.

[[v44-9-11]]

^<<v44-9-11,11>>^ E disse- lhe o Senhor: Levanta-te, e vai à rua chamada Direita, e pergunta em casa de Judas por um homem de Tarso chamado Saulo; pois eis que ele está orando;

[[v44-9-12]]

^<<v44-9-12,12>>^ E numa visão ele viu que entrava um homem chamado Ananias, e punha sobre ele a mão, para que tornasse a ver.

[[v44-9-13]]

^<<v44-9-13,13>>^ E respondeu Ananias: Senhor, a muitos ouvi acerca deste homem, quantos males tem feito aos teus santos em Jerusalém;

[[v44-9-14]]

^<<v44-9-14,14>>^ E aqui tem poder dos principais dos sacerdotes para prender a todos os que invocam o teu nome.

[[v44-9-15]]

^<<v44-9-15,15>>^ Disse-lhe, porém, o Senhor: Vai, porque este é para mim um vaso escolhido, para levar o meu nome diante dos gentios, e dos reis e dos filhos d’Israel.

[[v44-9-16]]

^<<v44-9-16,16>>^ E eu lhe mostrarei quanto deve padecer pelo meu nome.

[[v44-9-17]]

^<<v44-9-17,17>>^ E Ananias foi, e entrou na casa, e, impondo-lhe as mãos, disse: Irmão Saulo, o Senhor Jesus, que te apareceu no caminho por onde vinhas, me enviou, para que tornes a ver e sejas cheio do Espírito Santo.

[[v44-9-18]]

^<<v44-9-18,18>>^ E logo lhe caíram dos olhos como que umas escamas, e recuperou a vista; e, levantando-se, foi batizado.

[[v44-9-19]]

^<<v44-9-19,19>>^ E, tendo comido, ficou confortado. E esteve Saulo alguns dias com os discípulos que estavam em Damasco.

[[v44-9-20]]

^<<v44-9-20,20>>^ E logo nas sinagogas pregava a Jesus, que este era o Filho de Deus.

[[v44-9-21]]

^<<v44-9-21,21>>^ E todos os que o ouviam estavam atônitos, e diziam: Não é este o que em Jerusalém perseguia os que invocavam este nome, e para isso veio aqui, para os levar presos aos principais dos sacerdotes?

[[v44-9-22]]

^<<v44-9-22,22>>^ Saulo, porém, se esforçava muito mais, e confundia os judeus que habitavam em Damasco, provando que aquele era o Cristo.

[[v44-9-23]]

^<<v44-9-23,23>>^ E, tendo passado muitos dias, os judeus tomaram conselho entre si para o matar.

[[v44-9-24]]

^<<v44-9-24,24>>^ Mas as suas ciladas vieram ao conhecimento de Saulo: e como eles guardavam as portas, tanto de dia como de noite, para poderem tirar-lhe a vida,

[[v44-9-25]]

^<<v44-9-25,25>>^ Tomando-o de noite os discípulos, o desceram, dentro dum cesto, pelo muro.

[[v44-9-26]]

^<<v44-9-26,26>>^ E, quando Saulo chegou a Jerusalém, procurava ajuntar-se aos discípulos, mas todos o temiam, não crendo que fosse discípulo.

[[v44-9-27]]

^<<v44-9-27,27>>^ Então Barnabé, tomando-o consigo o trouxe aos apóstolos, e lhes contou como no caminho ele vira ao Senhor e lhe falara, e como em Damasco falara ousadamente no nome de Jesus.

[[v44-9-28]]

^<<v44-9-28,28>>^ E andava com eles em Jerusalém, entrando e saindo.

[[v44-9-29]]

^<<v44-9-29,29>>^ E falava ousadamente no nome de Jesus. Falava e disputava também contra os gregos, mas eles procuravam matá-lo.

[[v44-9-30]]

^<<v44-9-30,30>>^ Sabendo- o, porém, os irmãos, o acompanharam até Cesareia, e o enviaram a Tarso.

[[v44-9-31]]

^<<v44-9-31,31>>^ Assim, pois, as igrejas em toda a Judeia, e Galileia e Samaria tinham paz, e eram edificadas; e se multiplicavam, andando no temor do Senhor e consolação do Espírito Santo.

[[v44-9-32]]

^<<v44-9-32,32>>^ E aconteceu que, passando Pedro por toda a parte, veio também aos santos que habitavam em Lida.

[[v44-9-33]]

^<<v44-9-33,33>>^ E achou ali certo homem, chamado Eneias, jazendo numa cama havia oito anos, o qual era paralítico.

[[v44-9-34]]

^<<v44-9-34,34>>^ E disse-lhe Pedro: Eneias, Jesus Cristo te dá saúde; levanta-te e faze a tua cama. E logo se levantou.

[[v44-9-35]]

^<<v44-9-35,35>>^ E viram-no todos os que habitavam em Lida e Sarona, os quais se converteram ao Senhor.

[[v44-9-36]]

^<<v44-9-36,36>>^ E havia em Jope uma discípula chamada Tabita, que traduzido se diz Dorcas. Esta estava cheia de boas obras e esmolas que fazia.

[[v44-9-37]]

^<<v44-9-37,37>>^ E aconteceu naqueles dias que, enfermando ela, morreu; e, tendo-a lavado, a  depositaram num quarto alto.

[[v44-9-38]]

^<<v44-9-38,38>>^ E, como Lida era perto de Jope, ouvindo os discípulos que Pedro estava ali, lhe mandaram dois varões, rogando-lhe que não se demorasse em vir ter com eles.

[[v44-9-39]]

^<<v44-9-39,39>>^ E, levantando-se Pedro, foi com eles; e quando chegou o levaram ao quarto alto, e todas as viúvas o rodearam, chorando e mostrando as túnicas e vestidos que Dorcas fizera quando estava com elas.

[[v44-9-40]]

^<<v44-9-40,40>>^ Mas Pedro, fazendo- as  sair a todas, pôs-se de joelhos e orou: e, voltando-se para o corpo, disse: Tabita, levanta-te. E ela abriu os olhos, e, vendo a Pedro, assentou-se.

[[v44-9-41]]

^<<v44-9-41,41>>^ E ele, dando-lhe a mão, a levantou, e, chamando os santos e as viúvas, apresentou-lha viva.

[[v44-9-42]]

^<<v44-9-42,42>>^ E foi isto  notório por toda a Jope, e muitos creram no Senhor.

[[v44-9-43]]

^<<v44-9-43,43>>^ E ficou muitos dias em Jope, com um certo  Simão curtidor.

'''

xref:044-atos/044-atos-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-atos/044-atos-010.adoc#v44-10-0[Próximo Capítulo &#62;]