include::./index.adoc[]

[[v44-12-0]]
=== Atos, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-12-1]]

^<<v44-12-1,1>>^ E POR aquele mesmo tempo o rei Herodes estendeu as mãos sobre alguns da igreja, para os maltratar;

[[v44-12-2]]

^<<v44-12-2,2>>^ E matou à espada Tiago, irmão de João.

[[v44-12-3]]

^<<v44-12-3,3>>^ E, vendo que isso agradara aos judeus, continuou, mandando prender também a Pedro. E eram os dias dos asmos.

[[v44-12-4]]

^<<v44-12-4,4>>^ E, havendo-o prendido, o encerrou na prisão, entregando-o a quatro quaternos de soldados, para que o guardassem, querendo apresentá-lo ao povo depois da páscoa.

[[v44-12-5]]

^<<v44-12-5,5>>^ Pedro, pois, era guardado na prisão: mas a igreja fazia contínua oração por ele a Deus.

[[v44-12-6]]

^<<v44-12-6,6>>^ E quando Herodes estava para o fazer nessa mesma noite comparecer, estava Pedro dormindo, entre dois soldados, ligado com duas cadeias, e os guardas diante da porta guardavam a prisão.

[[v44-12-7]]

^<<v44-12-7,7>>^ E eis que sobreveio o anjo do Senhor, e resplandeceu uma luz na prisão; e, tocando a Pedro na ilharga, o despertou, dizendo: Levanta-te depressa. E caíram-lhe das mãos as cadeias.

[[v44-12-8]]

^<<v44-12-8,8>>^ E disse-lhe o anjo: Cinge-te, e ata as tuas alparcas. E ele o fez assim. Disse-lhe mais: Lança às costas a tua capa, e segue-me.

[[v44-12-9]]

^<<v44-12-9,9>>^ E, saindo, o seguia. E não sabia que era real o que estava sendo feito pelo anjo, mas cuidava que via alguma visão.

[[v44-12-10]]

^<<v44-12-10,10>>^ E, quando passaram a primeira e segunda guarda, chegaram à porta de ferro, que dá para a cidade, a qual se lhes abriu por si mesma; e, tendo saído, percorreram uma rua, e logo o anjo se apartou dele.

[[v44-12-11]]

^<<v44-12-11,11>>^ E Pedro, tornando a si, disse: Agora sei verdadeiramente que o Senhor enviou o seu anjo e me livrou da mão de Herodes, e de  tudo o que o povo dos judeus esperava.

[[v44-12-12]]

^<<v44-12-12,12>>^ E, considerando ele nisto , foi à casa de Maria, mãe de João, que tinha por sobrenome Marcos, onde muitos estavam reunidos e oravam.

[[v44-12-13]]

^<<v44-12-13,13>>^ E, batendo Pedro à porta do pátio, uma menina chamada Rode saiu a escutar:

[[v44-12-14]]

^<<v44-12-14,14>>^ E, conhecendo a voz de Pedro, de gozo não abriu a porta, mas, correndo para dentro, anunciou que Pedro estava à porta.

[[v44-12-15]]

^<<v44-12-15,15>>^ E disseram-lhe: Estás fora de ti. Mas ela afirmava que assim era. E diziam. É o seu anjo.

[[v44-12-16]]

^<<v44-12-16,16>>^ Mas Pedro perseverava em bater, e, quando abriram, viram-no, e se espantaram.

[[v44-12-17]]

^<<v44-12-17,17>>^ E, acenando-lhes ele com a mão para que se calassem, contou-lhes como o Senhor o tirara da prisão, e disse: Anunciai isto a Tiago e aos irmãos. E, saindo partiu para outro lugar.

[[v44-12-18]]

^<<v44-12-18,18>>^ E, sendo já dia, houve não pouco alvoroço entre os soldados sobre o que seria feito de Pedro.

[[v44-12-19]]

^<<v44-12-19,19>>^ E, quando Herodes, o procurou e o não achou, feita inquirição aos guardas, mandou-os justiçar. E, partindo da Judeia para Cesareia, ficou ali.

[[v44-12-20]]

^<<v44-12-20,20>>^ E ele estava irritado com os de Tiro e de Sidom; mas estes, vindo de comum acordo ter com ele, e obtendo a amizade de Blasto, que era o camarista do rei, pediam paz: porquanto o seu país se abastecia do país do rei.

[[v44-12-21]]

^<<v44-12-21,21>>^ E num dia designado, vestindo Herodes as vestes reais, estava assentado no tribunal, e lhes fez uma prática.

[[v44-12-22]]

^<<v44-12-22,22>>^ E o povo exclamava: Voz de Deus, e não de homem.

[[v44-12-23]]

^<<v44-12-23,23>>^ E no mesmo instante feriu-o o anjo do Senhor, porque não deu glória a Deus, e, comido de bichos, expirou.

[[v44-12-24]]

^<<v44-12-24,24>>^ E a palavra de Deus crescia e se multiplicava.

[[v44-12-25]]

^<<v44-12-25,25>>^ E Barnabé e Saulo, havendo terminado aquele serviço, voltaram de Jerusalém, levando também consigo a João, que tinha por sobrenome Marcos.

'''

xref:044-atos/044-atos-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-atos/044-atos-013.adoc#v44-13-0[Próximo Capítulo &#62;]