include::./index.adoc[]

[[v44-4-0]]
=== Atos, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-4-1]]

^<<v44-4-1,1>>^ E, ESTANDO eles falando ao povo, sobrevieram os sacerdotes, e o capitão do templo, e os saduceus,

[[v44-4-2]]

^<<v44-4-2,2>>^ Doendo-se muito de que ensinassem o povo, e anunciassem em Jesus a ressurreição dos mortos.

[[v44-4-3]]

^<<v44-4-3,3>>^ E lançaram mão deles, e os  encerraram na prisão até ao dia seguinte, pois era já tarde.

[[v44-4-4]]

^<<v44-4-4,4>>^ Muitos, porém, dos que ouviram a palavra creram, e chegou o número desses homens a quase cinco mil.

[[v44-4-5]]

^<<v44-4-5,5>>^ E aconteceu, no dia seguinte, reunirem-se em Jerusalém os seus principais, os anciãos, os escribas,

[[v44-4-6]]

^<<v44-4-6,6>>^ E Anás, o sumo sacerdote, e Caifás, e João, e Alexandre, e todos quantos havia da linhagem do sumo sacerdote.

[[v44-4-7]]

^<<v44-4-7,7>>^ E, pondo-os no meio, perguntaram: Com que poder ou em nome de quem fizestes isto?

[[v44-4-8]]

^<<v44-4-8,8>>^ Então Pedro, cheio do Espírito Santo, lhes disse: Principais do povo, e vós, anciãos d’Israel.

[[v44-4-9]]

^<<v44-4-9,9>>^ Visto que hoje somos interrogados acerca do benefício feito  a um homem enfermo e do modo como foi curado,

[[v44-4-10]]

^<<v44-4-10,10>>^ Seja conhecido de vós todos, e de todo o povo d’Israel, que em nome de Jesus Cristo, o nazareno, aquele a quem vós crucificastes e a quem Deus ressuscitou dos mortos, em nome desse é que este está são diante de vós.

[[v44-4-11]]

^<<v44-4-11,11>>^ Ele é a pedra que foi rejeitada por vós, os edificadores, a qual foi posta por cabeça de esquina.

[[v44-4-12]]

^<<v44-4-12,12>>^ E em nenhum outro há salvação, porque também debaixo do céu nenhum outro nome há, dado entre os homens pelo qual devamos ser salvos.

[[v44-4-13]]

^<<v44-4-13,13>>^ Então eles, vendo a ousadia de Pedro e João, e informados de que eram homens sem letras e indoutos, se maravilharam; e tinham conhecimento que eles haviam estado com Jesus.

[[v44-4-14]]

^<<v44-4-14,14>>^ E vendo estar com eles o homem que fora curado, nada tinham que dizer em contrário.

[[v44-4-15]]

^<<v44-4-15,15>>^ Todavia, mandando-os sair fora do conselho, conferenciaram entre si,

[[v44-4-16]]

^<<v44-4-16,16>>^ Dizendo: Que havemos de fazer a estes homens? porque a todos os que habitam em Jerusalém é manifesto que por eles foi feito um sinal notório, e não o  podemos negar;

[[v44-4-17]]

^<<v44-4-17,17>>^ Mas, para que não se divulgue mais entre o povo, ameacemo-los para que não falem mais nesse nome a homem algum.

[[v44-4-18]]

^<<v44-4-18,18>>^ E, chamando-os, disseram-lhes que absolutamente não falassem, nem ensinassem, no nome de Jesus.

[[v44-4-19]]

^<<v44-4-19,19>>^ Respondendo, porém, Pedro e João, lhes disseram: Julgai vós se é justo, diante de Deus, ouvir-vos antes a vós do que a Deus?

[[v44-4-20]]

^<<v44-4-20,20>>^ Porque não podemos deixar de falar do que temos visto e ouvido.

[[v44-4-21]]

^<<v44-4-21,21>>^ Mas eles ainda os ameaçaram mais, e, não achando motivo para os castigar, deixaram-nos ir por causa do povo; porque todos glorificavam a Deus pelo que acontecera;

[[v44-4-22]]

^<<v44-4-22,22>>^ Pois tinha mais de quarenta anos o homem em quem se operara aquele milagre de saúde.

[[v44-4-23]]

^<<v44-4-23,23>>^ E, soltos eles, foram para os seus, e contaram tudo o que lhes disseram os principais dos sacerdotes e os anciãos.

[[v44-4-24]]

^<<v44-4-24,24>>^ E, ouvindo eles isto , unânimes levantaram a voz a Deus, e disseram: Senhor, tu és  o que fizeste o céu, e a terra, e o mar, e tudo o que neles há;

[[v44-4-25]]

^<<v44-4-25,25>>^ Que disseste pela boca de Davi, teu servo: Por que bramaram as gentes, e os povos pensaram coisas  vãs?

[[v44-4-26]]

^<<v44-4-26,26>>^ Levantaram-se os reis da terra, e os príncipes se ajuntaram à uma, contra o Senhor e contra o seu Ungido.

[[v44-4-27]]

^<<v44-4-27,27>>^ Porque verdadeiramente contra o teu santo Filho Jesus, que tu ungiste, se ajuntaram, não só Herodes, mas Pôncio Pilatos, com os gentios e os povos d’Israel;

[[v44-4-28]]

^<<v44-4-28,28>>^ Para fazerem tudo o que a tua mão e o teu conselho tinham anteriormente determinado que se havia de fazer.

[[v44-4-29]]

^<<v44-4-29,29>>^ Agora pois, ó Senhor, olha para as suas ameaças, e concede aos teus servos que falem com toda a ousadia a tua palavra;

[[v44-4-30]]

^<<v44-4-30,30>>^ Enquanto estendes a tua mão para curar, e para que se façam sinais e prodígios pelo nome do teu santo Filho Jesus,

[[v44-4-31]]

^<<v44-4-31,31>>^ E, tendo orado, moveu-se o lugar em que estavam reunidos; e todos foram cheios do Espírito Santo, e anunciavam com ousadia a palavra de Deus.

[[v44-4-32]]

^<<v44-4-32,32>>^ E era um o coração e a alma da multidão dos que criam, e ninguém dizia que coisa alguma do que possuía era sua própria, mas todas as coisas lhes eram comuns.

[[v44-4-33]]

^<<v44-4-33,33>>^ E os apóstolos davam, com grande poder, testemunho da ressurreição do Senhor Jesus, e em todos eles havia abundante graça.

[[v44-4-34]]

^<<v44-4-34,34>>^ Não havia pois entre eles necessitado algum; porque todos os que possuíam herdades ou casas, vendendo-as, traziam o preço do que fora vendido, e o depositavam aos pés dos apóstolos.

[[v44-4-35]]

^<<v44-4-35,35>>^ E repartia-se por cada um, segundo a necessidade que cada um tinha.

[[v44-4-36]]

^<<v44-4-36,36>>^ Então José, cognominado pelos apóstolos Barnabé (que, traduzido, é Filho da consolação), levita, natural de Chipre,

[[v44-4-37]]

^<<v44-4-37,37>>^ Possuindo uma herdade, vendeu-a, e trouxe o preço, e o depositou aos pés dos apóstolos.

'''

xref:044-atos/044-atos-003.adoc#v44-3-0[&#60; Capítulo Anterior] | <<v44-4-0,Topo>> | xref:044-atos/044-atos-005.adoc#v44-5-0[Próximo Capítulo &#62;]