include::./index.adoc[]

[[v44-15-0]]
=== Atos, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-15-1]]

^<<v44-15-1,1>>^ ENTÃO alguns que tinham descido da Judeia ensinavam assim os irmãos: Se vos não circuncidardes, conforme o uso de Moisés, não podeis salvar-vos.

[[v44-15-2]]

^<<v44-15-2,2>>^ Tendo tido Paulo e Barnabé não pequena discussão e contenda contra eles, resolveu-se que Paulo e Barnabé, e alguns dentre eles, subissem a Jerusalém aos apóstolos e aos anciãos sobre aquela questão.

[[v44-15-3]]

^<<v44-15-3,3>>^ E eles, sendo acompanhados pela igreja, passavam pela Fenícia e por Samaria, contando a conversão dos gentios: e davam grande alegria a todos os irmãos.

[[v44-15-4]]

^<<v44-15-4,4>>^ E quando chegaram a Jerusalém, foram recebidos pela igreja e pelos apóstolos e anciãos, e lhes anunciaram quão grandes coisas Deus tinha feito com eles.

[[v44-15-5]]

^<<v44-15-5,5>>^ Alguns, porém, da seita dos fariseus, que tinham crido, se levantaram, dizendo que era mister circuncidá-los e mandar- lhes  que guardassem a lei de Moisés.

[[v44-15-6]]

^<<v44-15-6,6>>^ Congregaram-se pois os apóstolos e os anciãos para considerar este assunto.

[[v44-15-7]]

^<<v44-15-7,7>>^ E, havendo grande contenda, levantou-se Pedro e disse-lhes: Varões irmãos, bem sabeis que já há muito tempo Deus me  elegeu dentre vós, para que os gentios ouvissem da minha boca a palavra do evangelho, e cressem.

[[v44-15-8]]

^<<v44-15-8,8>>^ E Deus, que conhece os corações lhes deu testemunho, dando-lhes o Espírito Santo, assim como também a nós;

[[v44-15-9]]

^<<v44-15-9,9>>^ E não fez diferença alguma entre eles e nós, purificando os seus corações pela fé.

[[v44-15-10]]

^<<v44-15-10,10>>^ Agora, pois, por que tentais a Deus, pondo sobre a cerviz dos discípulos um jugo que nem nossos pais nem nós podemos suportar?

[[v44-15-11]]

^<<v44-15-11,11>>^ Mas cremos que seremos salvos pela graça do Senhor Jesus Cristo, como eles também.

[[v44-15-12]]

^<<v44-15-12,12>>^ Então toda a multidão se calou, e escutava a Barnabé e a Paulo, que contavam quão grandes sinais e prodígios Deus havia feito por meio deles entre os gentios.

[[v44-15-13]]

^<<v44-15-13,13>>^ E, havendo-se eles calado, tomou Tiago a palavra, dizendo: Varões irmãos, ouvi-me.

[[v44-15-14]]

^<<v44-15-14,14>>^ Simão relatou como primeiramente Deus visitou os gentios, para tomar deles  um povo para o seu nome.

[[v44-15-15]]

^<<v44-15-15,15>>^ E com isto concordam as palavras dos profetas; como está escrito:

[[v44-15-16]]

^<<v44-15-16,16>>^ Depois disto voltarei, e reedificarei o tabernáculo de Davi, que está caído, levantá-lo-ei das suas ruínas e tornarei a edificá-lo.

[[v44-15-17]]

^<<v44-15-17,17>>^ Para que o resto dos homens busque ao Senhor, e todos os gentios, sobre os quais o meu nome é invocado, diz o Senhor, que faz todas estas coisas ,

[[v44-15-18]]

^<<v44-15-18,18>>^ Que são conhecidas desde toda a eternidade.

[[v44-15-19]]

^<<v44-15-19,19>>^ Pelo que julgo que não se deve perturbar aqueles, dentre os gentios, que se convertem a Deus,

[[v44-15-20]]

^<<v44-15-20,20>>^ Mas escrever-lhes que se abstenham das contaminações dos ídolos, da prostituição, do que é sufocado e do  sangue.

[[v44-15-21]]

^<<v44-15-21,21>>^ Porque Moisés, desde os tempos antigos, tem em cada cidade quem o pregue, e cada sábado é lido nas sinagogas.

[[v44-15-22]]

^<<v44-15-22,22>>^ Então pareceu bem aos apóstolos e aos anciãos, com toda a igreja, eleger varões dentre eles e enviá-los com Paulo e Barnabé a Antioquia, a saber : Judas, chamado Barsabás, e Silas, varões distintos entre os irmãos.

[[v44-15-23]]

^<<v44-15-23,23>>^ E por intermédio deles escreveram o seguinte: Os apóstolos, e os anciãos e os irmãos, aos irmãos dentre os gentios que estão em Antioquia, e Síria e Cilícia, saúde.

[[v44-15-24]]

^<<v44-15-24,24>>^ Porquanto ouvimos que alguns que saíram dentre nós vos perturbaram com palavras, e transtornaram as vossas almas, não lhes tendo nós dado mandamento.

[[v44-15-25]]

^<<v44-15-25,25>>^ Pareceu-nos bem, reunidos concordemente, eleger alguns  varões, e enviá-los com os nossos amados Barnabé e Paulo.

[[v44-15-26]]

^<<v44-15-26,26>>^ Homens que já  expuseram as suas vidas pelo nome de nosso Senhor Jesus Cristo.

[[v44-15-27]]

^<<v44-15-27,27>>^ Enviamos portanto Judas e Silas os quais de boca vos anunciarão também o mesmo.

[[v44-15-28]]

^<<v44-15-28,28>>^ Na verdade pareceu bem ao Espírito Santo, e a nós, não vos impor mais encargo algum, senão estas coisas  necessárias:

[[v44-15-29]]

^<<v44-15-29,29>>^ Que vos abstenhais das coisas sacrificadas aos ídolos, e do sangue, e da carne  sufocada, e da fornicação: das quais coisas fazeis bem se vos guardardes. Bem vos vá.

[[v44-15-30]]

^<<v44-15-30,30>>^ Tendo-se eles então despedido, partiram para Antioquia, e, ajuntando a multidão, entregaram a carta.

[[v44-15-31]]

^<<v44-15-31,31>>^ E, quando a leram, alegraram-se pela exortação.

[[v44-15-32]]

^<<v44-15-32,32>>^ Depois Judas e Silas, que também eram profetas, exortaram e confirmaram os irmãos com muitas palavras.

[[v44-15-33]]

^<<v44-15-33,33>>^ E, detendo-se ali algum tempo, os irmãos os deixaram voltar em paz para os apóstolos;

[[v44-15-34]]

^<<v44-15-34,34>>^ Mas pareceu bem a Silas ficar ali.

[[v44-15-35]]

^<<v44-15-35,35>>^ E Paulo e Barnabé ficaram em Antioquia, ensinando e pregando, com muitos outros, a palavra do Senhor.

[[v44-15-36]]

^<<v44-15-36,36>>^ E alguns dias depois disse Paulo a Barnabé: Tornemos a visitar nossos irmãos por todas as cidades em que já anunciamos a palavra do Senhor, para ver  como estão.

[[v44-15-37]]

^<<v44-15-37,37>>^ E Barnabé aconselhava que tomassem consigo a João, chamado Marcos.

[[v44-15-38]]

^<<v44-15-38,38>>^ Mas a Paulo parecia razoável que não tomassem consigo aquele que desde Panfília se tinha apartado deles e não os acompanhou naquela obra.

[[v44-15-39]]

^<<v44-15-39,39>>^ E tal contenda houve entre eles, que se apartaram um do outro. Barnabé, levando consigo a Marcos, navegou para Chipre.

[[v44-15-40]]

^<<v44-15-40,40>>^ E Paulo, tendo escolhido a Silas, partiu, encomendado pelos irmãos à graça de Deus.

[[v44-15-41]]

^<<v44-15-41,41>>^ E passou pela Síria e Cilícia, confirmando as igrejas.

'''

xref:044-atos/044-atos-014.adoc#v44-14-0[&#60; Capítulo Anterior] | <<v44-15-0,Topo>> | xref:044-atos/044-atos-016.adoc#v44-16-0[Próximo Capítulo &#62;]