include::./index.adoc[]

[[v44-11-0]]
=== Atos, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-11-1]]

^<<v44-11-1,1>>^ E OUVIRAM os apóstolos, e os irmãos que estavam na Judeia, que também os gentios tinham recebido a palavra de Deus.

[[v44-11-2]]

^<<v44-11-2,2>>^ E, subindo Pedro a Jerusalém, disputavam com ele os que eram da circuncisão,

[[v44-11-3]]

^<<v44-11-3,3>>^ Dizendo: Entraste em casa  de varões incircuncisos, e comeste com eles.

[[v44-11-4]]

^<<v44-11-4,4>>^ Mas Pedro começou a fazer-lhes uma exposição por ordem, dizendo:

[[v44-11-5]]

^<<v44-11-5,5>>^ Estando eu orando na cidade de Jope, tive, num arrebatamento dos sentidos, uma visão; via um vaso, como um grande lençol que descia do céu e vinha até junto de mim.

[[v44-11-6]]

^<<v44-11-6,6>>^ E, pondo nele os olhos, considerei, e vi animais da terra, quadrúpedes, e feras, e répteis, e aves do céu.

[[v44-11-7]]

^<<v44-11-7,7>>^ E ouvi uma voz que me dizia: Levanta-te, Pedro; mata e come.

[[v44-11-8]]

^<<v44-11-8,8>>^ Mas eu disse: De maneira nenhuma, Senhor; pois nunca em minha boca entrou coisa alguma comum ou imunda.

[[v44-11-9]]

^<<v44-11-9,9>>^ Mas a voz respondeu-me do céu segunda vez: Não chames tu comum ao que Deus purificou.

[[v44-11-10]]

^<<v44-11-10,10>>^ E sucedeu isto por três vezes; e tudo tornou a recolher-se no céu.

[[v44-11-11]]

^<<v44-11-11,11>>^ E eis que, na mesma hora , pararam junto da casa em que eu estava três varões que me foram enviados de Cesareia.

[[v44-11-12]]

^<<v44-11-12,12>>^ E disse-me o Espírito que fosse com eles, nada duvidando; e também estes seis irmãos foram comigo, e entramos em casa daquele varão.

[[v44-11-13]]

^<<v44-11-13,13>>^ E contou-nos como vira em pé um anjo em sua casa, e lhe dissera: Envia varões a Jope, e manda chamar a Simão, que tem por sobrenome Pedro,

[[v44-11-14]]

^<<v44-11-14,14>>^ O qual te dirá palavras com que te salves, tu e toda a tua casa.

[[v44-11-15]]

^<<v44-11-15,15>>^ E, quando comecei a falar, caiu sobre eles o Espírito Santo, como também sobre nós ao princípio.

[[v44-11-16]]

^<<v44-11-16,16>>^ E lembrei-me do dito do Senhor, quando disse: João certamente batizou com água: mas vós sereis batizados com o Espírito Santo.

[[v44-11-17]]

^<<v44-11-17,17>>^ Portanto, se Deus lhes deu o mesmo dom que a nós, quando havemos crido no Senhor Jesus Cristo, quem era então eu, para que pudesse resistir a Deus?

[[v44-11-18]]

^<<v44-11-18,18>>^ E, ouvindo estas coisas, apaziguaram-se, e glorificaram a Deus, dizendo: Na verdade até aos gentios deu Deus o arrependimento para a vida.

[[v44-11-19]]

^<<v44-11-19,19>>^ E os que foram dispersos pela perseguição que sucedeu por causa de Estêvão caminharam até à Fenícia, Chipre e Antioquia, não anunciando a ninguém a palavra senão somente aos judeus.

[[v44-11-20]]

^<<v44-11-20,20>>^ E havia entre eles alguns varões chíprios e cirenenses, os quais, entrando em Antioquia, falaram aos gregos, anunciando o Senhor Jesus.

[[v44-11-21]]

^<<v44-11-21,21>>^ E a mão do Senhor era com eles; e grande número creu e se converteu ao Senhor.

[[v44-11-22]]

^<<v44-11-22,22>>^ E chegou a fama destas coisas aos ouvidos da igreja que estava em Jerusalém; e enviaram Barnabé à Antioquia.

[[v44-11-23]]

^<<v44-11-23,23>>^ O qual, quando chegou, e viu a graça de Deus, se alegrou, e exortou a todos a que permanecessem no Senhor com propósito do coração.

[[v44-11-24]]

^<<v44-11-24,24>>^ Porque era homem de bem, e cheio do Espírito Santo e de fé. E muita gente se uniu ao Senhor.

[[v44-11-25]]

^<<v44-11-25,25>>^ E partiu Barnabé para Tarso, a buscar Saulo; e, achando-o, o conduziu para Antioquia.

[[v44-11-26]]

^<<v44-11-26,26>>^ E sucedeu que todo um ano se reuniram naquela igreja, e ensinaram muita gente; e em Antioquia foram os discípulos, pela primeira vez, chamados cristãos.

[[v44-11-27]]

^<<v44-11-27,27>>^ E naqueles dias desceram profetas de Jerusalém para Antioquia.

[[v44-11-28]]

^<<v44-11-28,28>>^ E, levantando-se um deles, por nome Ágabo, dava a entender, pelo Espírito, que haveria uma grande fome em todo o mundo, e isso aconteceu no tempo de Cláudio César.

[[v44-11-29]]

^<<v44-11-29,29>>^ E os discípulos determinaram mandar, cada um conforme o que pudesse, socorro aos irmãos que habitavam na Judeia.

[[v44-11-30]]

^<<v44-11-30,30>>^ O que eles com efeito fizeram enviando-o aos anciãos por mão de Barnabé e de Saulo.

'''

xref:044-atos/044-atos-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-atos/044-atos-012.adoc#v44-12-0[Próximo Capítulo &#62;]