include::./index.adoc[]

[[v44-2-0]]
=== Atos, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-2-1]]

^<<v44-2-1,1>>^ E, CUMPRINDO-SE o dia de Pentecostes, estavam todos reunidos no mesmo lugar;

[[v44-2-2]]

^<<v44-2-2,2>>^ E de repente veio do céu um som, como de um vento veemente e  impetuoso, e encheu toda a casa em que estavam assentados.

[[v44-2-3]]

^<<v44-2-3,3>>^ E foram vistas por eles línguas repartidas, como que de fogo, as quais pousaram sobre cada um deles.

[[v44-2-4]]

^<<v44-2-4,4>>^ E todos foram cheios do Espírito Santo, e começaram a falar noutras línguas, conforme o Espírito Santo lhes concedia que falassem.

[[v44-2-5]]

^<<v44-2-5,5>>^ E em Jerusalém estavam habitando judeus, varões religiosos, de todas as nações que estão debaixo do céu.

[[v44-2-6]]

^<<v44-2-6,6>>^ E, correndo aquela voz, ajuntou-se uma multidão, e estava confusa, porque cada um os ouvia falar na sua própria língua.

[[v44-2-7]]

^<<v44-2-7,7>>^ E todos pasmavam e se maravilhavam, dizendo uns aos outros: Pois quê! não são galileus todos esses homens que estão falando?

[[v44-2-8]]

^<<v44-2-8,8>>^ Como pois os ouvimos, cada um, na nossa própria língua em que somos nascidos?

[[v44-2-9]]

^<<v44-2-9,9>>^ Partos e medas, elamitas e os que habitam na Mesopotâmia, e Judeia, e Capadócia, Ponto e Ásia,

[[v44-2-10]]

^<<v44-2-10,10>>^ E Frígia e Panfília, Egito e partes da Líbia, junto a Cirene, e forasteiros romanos, tanto judeus como prosélitos,

[[v44-2-11]]

^<<v44-2-11,11>>^ Cretenses e árabes, todos os temos ouvido em nossas próprias línguas falar das grandezas de Deus.

[[v44-2-12]]

^<<v44-2-12,12>>^ E todos se maravilhavam e estavam suspensos, dizendo uns para os outros: Que quer isto dizer?

[[v44-2-13]]

^<<v44-2-13,13>>^ E outros, zombando, diziam: Estão cheios de mosto.

[[v44-2-14]]

^<<v44-2-14,14>>^ Pedro, porém, pondo-se em pé com os onze, levantou a sua voz, e disse-lhes: Varões judeus, e todos os que habitais em Jerusalém, seja-vos isto notório, e escutai as minhas palavras.

[[v44-2-15]]

^<<v44-2-15,15>>^ Estes homens não estão embriagados, como vós pensais, sendo a terceira hora do dia.

[[v44-2-16]]

^<<v44-2-16,16>>^ Mas isto é o que foi dito pelo profeta Joel:

[[v44-2-17]]

^<<v44-2-17,17>>^ E nos últimos dias acontecerá, diz Deus, que do meu Espírito derramarei sobre toda a carne; e os vossos filhos e as vossas filhas profetizarão, os vossos mancebos terão visões, e os vossos velhos sonharão sonhos;

[[v44-2-18]]

^<<v44-2-18,18>>^ E também do meu Espírito derramarei sobre os meus servos e minhas servas naqueles dias, e profetizarão;

[[v44-2-19]]

^<<v44-2-19,19>>^ E farei aparecer prodígios em cima, no céu: e sinais em baixo na terra, sangue, fogo e vapor de fumo.

[[v44-2-20]]

^<<v44-2-20,20>>^ O sol se converterá em trevas, e a lua em sangue antes de chegar o grande e o glorioso dia do Senhor;

[[v44-2-21]]

^<<v44-2-21,21>>^ E acontecerá que  todo aquele que invocar o nome do Senhor será salvo.

[[v44-2-22]]

^<<v44-2-22,22>>^ Varões israelitas, escutai estas palavras: A Jesus Nazareno, varão aprovado por Deus entre vós com maravilhas, prodígios e sinais, que Deus por ele fez no meio de vós, como vós mesmos bem sabeis;

[[v44-2-23]]

^<<v44-2-23,23>>^ A este que vos foi entregue pelo determinado conselho e presciência de Deus, tomando-o vós, o crucificastes e matastes pelas mãos de injustos;

[[v44-2-24]]

^<<v44-2-24,24>>^ Ao qual Deus ressuscitou, soltas as ânsias da morte, pois não era possível que fosse retido por ela;

[[v44-2-25]]

^<<v44-2-25,25>>^ Porque dele disse Davi: Sempre via diante de mim o Senhor, porque está à minha direita, para que eu não seja comovido;

[[v44-2-26]]

^<<v44-2-26,26>>^ Por isso se alegrou o meu coração, e a minha língua exultou; e ainda a minha carne há de repousar em esperança.

[[v44-2-27]]

^<<v44-2-27,27>>^ Pois não deixarás a minha alma no Hades, nem permitirás que o teu Santo veja a corrupção;

[[v44-2-28]]

^<<v44-2-28,28>>^ Fizeste-me conhecidos os caminhos da vida; com a tua face me encherás de júbilo.

[[v44-2-29]]

^<<v44-2-29,29>>^ Varões irmãos seja-me lícito dizer-vos livremente acerca do patriarca Davi, que ele morreu e foi sepultado, e entre nós está até hoje a sua sepultura.

[[v44-2-30]]

^<<v44-2-30,30>>^ Sendo pois ele profeta, e sabendo que Deus lhe havia prometido com juramento que do fruto de seus lombos, segundo a carne, levantaria o Cristo, para o  assentar sobre o seu trono.

[[v44-2-31]]

^<<v44-2-31,31>>^ Nesta previsão, disse da ressurreição de Cristo: que a sua alma não foi deixada no Hades, nem a sua carne viu a corrupção.

[[v44-2-32]]

^<<v44-2-32,32>>^ Deus ressuscitou a este Jesus, do que todos nós somos testemunhas.

[[v44-2-33]]

^<<v44-2-33,33>>^ De sorte que, exaltado pela destra de Deus, e tendo recebido do Pai a promessa do Espírito Santo, derramou isto que vós agora vedes e ouvis.

[[v44-2-34]]

^<<v44-2-34,34>>^ Porque Davi não subiu aos céus, mas ele próprio diz: Disse o Senhor  ao meu Senhor: Assenta-te à minha direita,

[[v44-2-35]]

^<<v44-2-35,35>>^ Até que ponha os teus inimigos por escabelo de teus pés.

[[v44-2-36]]

^<<v44-2-36,36>>^ Saiba pois com certeza toda a casa d’Israel que a esse Jesus, a quem vós crucificastes, Deus o fez Senhor e Cristo.

[[v44-2-37]]

^<<v44-2-37,37>>^ E, ouvindo eles isto, compungiram-se em seu coração, e perguntaram a Pedro e aos demais apóstolos: Que faremos, varões irmãos?

[[v44-2-38]]

^<<v44-2-38,38>>^ E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo, para perdão dos pecados; e recebereis o dom do Espírito Santo;

[[v44-2-39]]

^<<v44-2-39,39>>^ Porque a promessa vos diz respeito a vós, a vossos filhos, e a todos os que estão longe: a tantos quantos Deus nosso Senhor chamar.

[[v44-2-40]]

^<<v44-2-40,40>>^ E com muitas outras palavras isto testificava, e os exortava, dizendo: Salvai-vos desta geração perversa.

[[v44-2-41]]

^<<v44-2-41,41>>^ De sorte que foram batizados os que de bom grado receberam a sua palavra; e naquele dia agregaram-se quase três mil almas;

[[v44-2-42]]

^<<v44-2-42,42>>^ E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações.

[[v44-2-43]]

^<<v44-2-43,43>>^ E em toda a alma havia temor, e muitas maravilhas e sinais se faziam pelos apóstolos.

[[v44-2-44]]

^<<v44-2-44,44>>^ E todos os que criam estavam juntos, e tinham tudo em comum.

[[v44-2-45]]

^<<v44-2-45,45>>^ E vendiam suas propriedades e fazendas, e repartiam com todos, segundo cada um havia de mister.

[[v44-2-46]]

^<<v44-2-46,46>>^ E, perseverando unânimes todos os dias no templo, e partindo o pão em casa, comiam juntos com alegria e singeleza de coração,

[[v44-2-47]]

^<<v44-2-47,47>>^ Louvando a Deus, e caindo na graça de todo o povo. E todos os dias acrescentava o Senhor à igreja aqueles que se haviam de salvar.

'''

xref:044-atos/044-atos-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:044-atos/044-atos-003.adoc#v44-3-0[Próximo Capítulo &#62;]