include::./index.adoc[]

[[v44-26-0]]
=== Atos, 26
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-26-1]]

^<<v44-26-1,1>>^ DEPOIS Agripa disse a Paulo: Permite-se-te que te defendas. Então Paulo, estendendo a mão em sua defesa, respondeu:

[[v44-26-2]]

^<<v44-26-2,2>>^ Tenho-me por venturoso, ó rei Agripa, de que perante ti me haja hoje de defender de todas as coisas  de que sou acusado pelos judeus;

[[v44-26-3]]

^<<v44-26-3,3>>^ Mormente sabendo eu  que tens conhecimento de todos os costumes e questões que há entre os judeus; pelo que te rogo que me ouças com paciência.

[[v44-26-4]]

^<<v44-26-4,4>>^ A minha vida, pois, desde a mocidade, qual haja sido, desde o princípio, em Jerusalém, entre os da minha nação, todos os judeus a sabem.

[[v44-26-5]]

^<<v44-26-5,5>>^ Sabendo de mim desde o princípio (se o quiserem testificar), que, conforme a mais severa seita da nossa religião, vivi fariseu.

[[v44-26-6]]

^<<v44-26-6,6>>^ E agora pela esperança da promessa que por Deus foi feita a nossos pais estou aqui  e sou julgado.

[[v44-26-7]]

^<<v44-26-7,7>>^ À qual as nossas doze tribos esperam chegar, servindo a Deus  continuamente, noite e dia. Por esta esperança, ó rei Agripa, eu sou acusado pelos judeus.

[[v44-26-8]]

^<<v44-26-8,8>>^ Pois  quê? julga-se coisa  incrível entre vós que Deus ressuscite os mortos?

[[v44-26-9]]

^<<v44-26-9,9>>^ Bem tinha eu imaginado que contra o nome de Jesus nazareno devia eu praticar muitos atos;

[[v44-26-10]]

^<<v44-26-10,10>>^ O que também fiz em Jerusalém. E, havendo recebido poder dos principais dos sacerdotes, encerrei muitos dos santos nas prisões; e quando os matavam eu dava o meu voto contra eles.

[[v44-26-11]]

^<<v44-26-11,11>>^ E, castigando-os muitas vezes por todas as sinagogas, os obriguei a blasfemar. E, enfurecido demasiadamente contra eles, até nas cidades estranhas os persegui.

[[v44-26-12]]

^<<v44-26-12,12>>^ Sobre o que, indo então a Damasco, com poder e comissão dos principais dos sacerdotes,

[[v44-26-13]]

^<<v44-26-13,13>>^ Ao meio-dia, ó rei, vi no caminho uma luz do céu, que excedia o esplendor do sol, cuja claridade me envolveu a mim e aos que iam comigo.

[[v44-26-14]]

^<<v44-26-14,14>>^ E, caindo nós todos por terra, ouvi uma voz que me falava, e em língua hebraica dizia: Saulo, Saulo, por que me persegues? Dura coisa  te é  recalcitrar contra os aguilhões.

[[v44-26-15]]

^<<v44-26-15,15>>^ E disse eu: Quem és, Senhor? E ele respondeu: Eu sou Jesus, a quem tu persegues;

[[v44-26-16]]

^<<v44-26-16,16>>^ Mas levanta-te e põe-te sobre teus pés, porque te apareci por isto, para te pôr por ministro e testemunha tanto das coisas  que tens visto como daquelas pelas quais te aparecerei ainda;

[[v44-26-17]]

^<<v44-26-17,17>>^ Livrando-te deste povo, e dos  gentios, a quem agora te envio,

[[v44-26-18]]

^<<v44-26-18,18>>^ Para lhes abrires os olhos, e das trevas os  converteres à luz, e do  poder de Satanás a Deus: a fim de que recebam a remissão dos pecados, e sorte entre os santificados pela fé em mim.

[[v44-26-19]]

^<<v44-26-19,19>>^ Pelo que, ó rei Agripa, não fui desobediente à visão celestial.

[[v44-26-20]]

^<<v44-26-20,20>>^ Antes anunciei primeiramente aos que estão em Damasco e em Jerusalém, e por toda a terra da Judeia, e aos gentios, que se emendassem e se convertessem a Deus, fazendo obras dignas de arrependimento.

[[v44-26-21]]

^<<v44-26-21,21>>^ Por causa disto os judeus lançaram mão de mim no templo, e procuraram matar- me.

[[v44-26-22]]

^<<v44-26-22,22>>^ Mas, alcançando socorro de Deus, ainda até ao dia de hoje permaneço, dando testemunho tanto a pequenos como a grandes não dizendo nada mais do que o que os profetas e Moisés disseram que devia acontecer,

[[v44-26-23]]

^<<v44-26-23,23>>^ Isto  é, que o Cristo devia padecer, e, sendo o primeiro da ressurreição dos mortos, devia anunciar a luz a este povo e aos gentios.

[[v44-26-24]]

^<<v44-26-24,24>>^ E, dizendo ele isto em sua  defesa, disse Festo em alta voz: Estás louco, Paulo: as muitas letras te fazem delirar.

[[v44-26-25]]

^<<v44-26-25,25>>^ Mas ele disse: Não deliro ó potentíssimo Festo; antes digo palavras de verdade e de um são juízo.

[[v44-26-26]]

^<<v44-26-26,26>>^ Porque o rei, diante de quem falo com ousadia, sabe estas coisas , pois não creio que nada disto lhe é oculto; porque isto não se fez em qualquer canto.

[[v44-26-27]]

^<<v44-26-27,27>>^ Crês tu nos profetas, ó rei Agripa? Bem sei que crês.

[[v44-26-28]]

^<<v44-26-28,28>>^ E disse Agripa a Paulo: Por pouco me queres persuadir a que me faça cristão!

[[v44-26-29]]

^<<v44-26-29,29>>^ E disse Paulo: Prouvera a Deus que, ou por pouco ou por muito, não somente tu, mas também todos quantos hoje me estão ouvindo se tornassem tais qual eu sou, exceto estas cadeias.

[[v44-26-30]]

^<<v44-26-30,30>>^ E, dizendo ele isto, se levantou o rei, e o presidente, e Berenice, e os que com eles estavam assentados.

[[v44-26-31]]

^<<v44-26-31,31>>^ E apartando-se dali, falavam uns com os outros, dizendo: Este homem nada fez digno de morte ou de prisões.

[[v44-26-32]]

^<<v44-26-32,32>>^ E Agripa disse a Festo: Bem podia soltar-se este homem, se não houvera apelado para César.

'''

xref:044-atos/044-atos-025.adoc#v44-25-0[&#60; Capítulo Anterior] | <<v44-26-0,Topo>> | xref:044-atos/044-atos-027.adoc#v44-27-0[Próximo Capítulo &#62;]