include::./index.adoc[]

[[v44-24-0]]
=== Atos, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-24-1]]

^<<v44-24-1,1>>^ E CINCO dias depois o sumo sacerdote Ananias desceu com os anciãos, e um certo Tértulo, orador os quais compareceram perante o presidente contra Paulo.

[[v44-24-2]]

^<<v44-24-2,2>>^ E, sendo chamado, Tértulo começou a acusá- lo , dizendo:

[[v44-24-3]]

^<<v44-24-3,3>>^ Visto como por ti temos tanta paz e por tua prudência se fazem a este povo muitos e louváveis serviços, sempre e em todo o lugar, ó potentíssimo Félix, com todo o agradecimento o queremos reconhecer.

[[v44-24-4]]

^<<v44-24-4,4>>^ Mas, para que te não detenha muito, rogo-te que, conforme a tua equidade, nos ouças por pouco tempo.

[[v44-24-5]]

^<<v44-24-5,5>>^ Temos achado que este homem é uma peste, e promotor de sedições entre todos os judeus, por todo o mundo; e o principal defensor da seita dos nazarenos;

[[v44-24-6]]

^<<v44-24-6,6>>^ O qual intentou também profanar o templo: e por isso o prendemos, e conforme a nossa lei o quisemos julgar.

[[v44-24-7]]

^<<v44-24-7,7>>^ Mas, sobrevindo o tribuno Lísias, no-lo tirou dentre as mãos, com grande violência,

[[v44-24-8]]

^<<v44-24-8,8>>^ Mandando aos seus acusadores que viessem a ti: e dele tu mesmo, examinando-o, poderás entender tudo o de que o acusamos.

[[v44-24-9]]

^<<v44-24-9,9>>^ E também os judeus o acusavam, dizendo serem estas coisas assim.

[[v44-24-10]]

^<<v44-24-10,10>>^ Paulo, porém, fazendo-lhe o presidente sinal que falasse, respondeu: Porque sei que já vai para muitos anos que desta nação és juiz, com tanto melhor ânimo respondo por mim.

[[v44-24-11]]

^<<v44-24-11,11>>^ Pois bem podes saber que não há mais de doze dias que subi a Jerusalém a adorar;

[[v44-24-12]]

^<<v44-24-12,12>>^ E não me acharam no templo falando com alguém, nem amotinando o povo nas sinagogas, nem na cidade.

[[v44-24-13]]

^<<v44-24-13,13>>^ Nem tão pouco podem provar as coisas  de que agora me acusam.

[[v44-24-14]]

^<<v44-24-14,14>>^ Mas confesso-te isto: que, conforme aquele caminho que chamam seita, assim sirvo ao Deus de nossos pais, crendo tudo quanto está escrito na lei e nos profetas.

[[v44-24-15]]

^<<v44-24-15,15>>^ Tendo esperança em Deus, como estes mesmos também esperam, de que há de haver ressurreição de mortos, assim dos justos como dos injustos.

[[v44-24-16]]

^<<v44-24-16,16>>^ E por isso procuro sempre ter uma consciência sem ofensa, tanto para com Deus como para  com os homens.

[[v44-24-17]]

^<<v44-24-17,17>>^ Ora, muitos anos depois, vim trazer à minha nação esmolas e ofertas.

[[v44-24-18]]

^<<v44-24-18,18>>^ Nisto me acharam já  santificado no templo, não em ajuntamentos, nem com alvoroços, uns certos judeus da Ásia,

[[v44-24-19]]

^<<v44-24-19,19>>^ Os quais convinha que estivessem presentes perante ti, e me  acusassem, se alguma coisa contra mim tivessem.

[[v44-24-20]]

^<<v44-24-20,20>>^ Ou digam estes mesmos, se acharam em mim alguma iniquidade, quando compareci perante o conselho,

[[v44-24-21]]

^<<v44-24-21,21>>^ A não ser estas palavras, que, estando entre eles, clamei: Hoje sou julgado por vós acerca da ressurreição dos mortos.

[[v44-24-22]]

^<<v44-24-22,22>>^ Então Félix, havendo ouvido estas coisas , lhes pôs dilação, dizendo: Havendo-me informado melhor deste caminho, quando o tribuno Lísias tiver descido então  tomarei inteiro conhecimento dos vossos negócios.

[[v44-24-23]]

^<<v44-24-23,23>>^ E mandou ao centurião que o guardassem em prisão, tratando-o com brandura, e que a ninguém dos seus proibisse servi-lo ou vir ter com ele.

[[v44-24-24]]

^<<v44-24-24,24>>^ E alguns dias depois, vindo Félix com sua mulher Drusila, que era judia, mandou chamar a Paulo, e ouviu-o acerca da fé em Cristo.

[[v44-24-25]]

^<<v44-24-25,25>>^ E, tratando ele da justiça, e da temperança, e do juízo vindouro, Félix, espavorido, respondeu: Por agora vai-te, e em tendo oportunidade te chamarei.

[[v44-24-26]]

^<<v44-24-26,26>>^ Esperando ao mesmo tempo que Paulo lhe desse dinheiro, para que o soltasse; pelo que também muitas vezes o mandava chamar, e falava com ele.

[[v44-24-27]]

^<<v44-24-27,27>>^ Mas, passados dois anos, Félix teve por sucessor a Pórcio Festo; e, querendo Félix comprazer aos judeus, deixou a Paulo preso.

'''

xref:044-atos/044-atos-023.adoc#v44-23-0[&#60; Capítulo Anterior] | <<v44-24-0,Topo>> | xref:044-atos/044-atos-025.adoc#v44-25-0[Próximo Capítulo &#62;]