include::./index.adoc[]

[[v44-8-0]]
=== Atos, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-8-1]]

^<<v44-8-1,1>>^ E TAMBÉM Saulo consentiu na morte dele. E fez-se naquele dia uma grande perseguição contra a igreja que estava em Jerusalém; e todos foram dispersos pelas terras da Judeia e da Samaria, exceto os apóstolos.

[[v44-8-2]]

^<<v44-8-2,2>>^ E uns varões piedosos foram enterrar Estêvão, e fizeram sobre ele grande pranto.

[[v44-8-3]]

^<<v44-8-3,3>>^ E Saulo assolava a igreja, entrando pelas casas: e, arrastando homens e mulheres, os  encerrava na prisão.

[[v44-8-4]]

^<<v44-8-4,4>>^ Mas os que andavam dispersos iam por toda a parte, anunciando a palavra.

[[v44-8-5]]

^<<v44-8-5,5>>^ E, descendo Filipe à cidade de Samaria lhes pregava a Cristo.

[[v44-8-6]]

^<<v44-8-6,6>>^ E as multidões unanimemente prestavam atenção ao que Filipe dizia, porque ouviam e viam os sinais que ele fazia;

[[v44-8-7]]

^<<v44-8-7,7>>^ Pois que os espíritos imundos saíam de muitos que os  tinham, clamando em alta voz; e muitos paralíticos e coxos eram curados.

[[v44-8-8]]

^<<v44-8-8,8>>^ E havia grande alegria naquela cidade.

[[v44-8-9]]

^<<v44-8-9,9>>^ E estava ali um certo homem, chamado Simão que anteriormente exercera naquela cidade a arte mágica, e tinha iludido a gente de Samaria, dizendo que era uma grande personagem ;

[[v44-8-10]]

^<<v44-8-10,10>>^ Ao qual todos atendiam, desde o mais pequeno até ao maior, dizendo: Este é a grande virtude de Deus.

[[v44-8-11]]

^<<v44-8-11,11>>^ E atendiam-no a ele, porque já  desde muito tempo os havia iludido com artes mágicas.

[[v44-8-12]]

^<<v44-8-12,12>>^ Mas, como cressem em Filipe, que lhes pregava acerca do reino de Deus, e do nome de Jesus Cristo, se batizavam, tanto homens como mulheres.

[[v44-8-13]]

^<<v44-8-13,13>>^ E creu até o próprio Simão; e, sendo batizado, ficou de contínuo com Filipe; e, vendo os sinais e as grandes maravilhas que se faziam, estava atônito.

[[v44-8-14]]

^<<v44-8-14,14>>^ Os apóstolos, pois, que estavam em Jerusalém, ouvindo que Samaria recebera a palavra de Deus, enviaram para lá Pedro e João.

[[v44-8-15]]

^<<v44-8-15,15>>^ Os quais, tendo descido, oraram por eles para que recebessem o Espírito Santo.

[[v44-8-16]]

^<<v44-8-16,16>>^ (Porque sobre nenhum deles tinha ainda descido; mas somente eram batizados em nome do Senhor Jesus.)

[[v44-8-17]]

^<<v44-8-17,17>>^ Então lhes impuseram as mãos, e receberam o Espírito Santo.

[[v44-8-18]]

^<<v44-8-18,18>>^ E Simão, vendo que pela imposição das mãos dos apóstolos era dado o Espírito Santo, lhes ofereceu dinheiro,

[[v44-8-19]]

^<<v44-8-19,19>>^ Dizendo: Dai-me também a mim esse poder, para que aquele sobre quem eu puser as mãos receba o Espírito Santo.

[[v44-8-20]]

^<<v44-8-20,20>>^ Mas disse-lhe Pedro: O teu dinheiro seja contigo para perdição, pois cuidaste que o dom de Deus se alcança por dinheiro.

[[v44-8-21]]

^<<v44-8-21,21>>^ Tu não tens parte nem sorte nesta palavra, porque o teu coração não é reto diante de Deus.

[[v44-8-22]]

^<<v44-8-22,22>>^ Arrepende-te pois dessa tua iniquidade, e ora a Deus, para que porventura te seja perdoado o pensamento do teu coração;

[[v44-8-23]]

^<<v44-8-23,23>>^ Pois vejo que estás em fel de amargura, e em laço de iniquidade.

[[v44-8-24]]

^<<v44-8-24,24>>^ Respondendo, porém, Simão disse: Orai vós por mim ao Senhor, para que nada do que dissestes venha sobre mim.

[[v44-8-25]]

^<<v44-8-25,25>>^ Tendo eles pois testificado e falado a palavra do Senhor, voltaram para Jerusalém, e em muitas aldeias dos samaritanos anunciaram o evangelho.

[[v44-8-26]]

^<<v44-8-26,26>>^ E o anjo do Senhor falou a Filipe, dizendo: Levanta-te, e vai para a banda do sul, ao caminho que desce de Jerusalém para Gaza, que está deserta.

[[v44-8-27]]

^<<v44-8-27,27>>^ E levantou-se, e foi; e eis que um homem etíope, eunuco, mordomo mor de Candace, rainha dos etíopes, o qual era superintendente de todos os seus tesouros, e tinha ido a Jerusalém para adoração,

[[v44-8-28]]

^<<v44-8-28,28>>^ Regressava, e assentado no seu carro, lia o profeta Isaías.

[[v44-8-29]]

^<<v44-8-29,29>>^ E disse o Espírito a Filipe: Chega-te, e ajunta-te a esse carro.

[[v44-8-30]]

^<<v44-8-30,30>>^ E, correndo Filipe, ouviu que lia o profeta Isaías, e disse: Entendes tu o que lês?

[[v44-8-31]]

^<<v44-8-31,31>>^ E ele disse: Como poderei entender, se alguém me não ensinar? E rogou a Filipe que subisse e com ele se assentasse.

[[v44-8-32]]

^<<v44-8-32,32>>^ E o lugar da Escritura que lia era este: Foi levado como a ovelha para o matadouro, e, como está mudo o cordeiro diante do que o tosquia, assim não abriu a sua boca.

[[v44-8-33]]

^<<v44-8-33,33>>^ Na sua humilhação foi tirado o seu julgamento; e quem contará a sua geração? porque a sua vida é tirada da terra.

[[v44-8-34]]

^<<v44-8-34,34>>^ E, respondendo o eunuco a Filipe, disse: Rogo-te, de quem diz isto o profeta? De si mesmo, ou dalgum outro?

[[v44-8-35]]

^<<v44-8-35,35>>^ Então Filipe, abrindo a sua boca e começando nesta escritura, lhe anunciou a Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ E, indo eles caminhando, chegaram ao pé de alguma água, e disse o eunuco: Eis aqui água; que impede que eu seja batizado?

[[v44-8-37]]

^<<v44-8-37,37>>^ E disse Filipe: É lícito, se crês de todo o coração. E, respondendo ele, disse: Creio que Jesus Cristo é o Filho de Deus.

[[v44-8-38]]

^<<v44-8-38,38>>^ E mandou parar o carro, e desceram ambos à água, tanto Filipe como o eunuco, e o batizou.

[[v44-8-39]]

^<<v44-8-39,39>>^ E, quando saíram da água, o Espírito do Senhor arrebatou a Filipe, e não o viu mais o eunuco; e, jubiloso, continuou o seu caminho.

[[v44-8-40]]

^<<v44-8-40,40>>^ E Filipe se achou em Azoto, e, indo passando, anunciava o Evangelho em  todas as cidades, até que chegou a Cesareia.

'''

xref:044-atos/044-atos-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-atos/044-atos-009.adoc#v44-9-0[Próximo Capítulo &#62;]