include::./index.adoc[]

[[v44-5-0]]
=== Atos, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-5-1]]

^<<v44-5-1,1>>^ MAS um certo  varão chamado Ananias, com Safira, sua mulher, vendeu uma propriedade.

[[v44-5-2]]

^<<v44-5-2,2>>^ E reteve parte do preço, sabendo-o também sua mulher; e, levando uma parte, a depositou aos pés dos apóstolos.

[[v44-5-3]]

^<<v44-5-3,3>>^ Disse então Pedro: Ananias, por que encheu Satanás o teu coração, para que mentisses ao Espírito Santo, e retivesses parte do preço da herdade?

[[v44-5-4]]

^<<v44-5-4,4>>^ Guardando-a não ficava para ti? E, vendida, não estava em teu poder? Por que formaste este desígnio em teu coração? Não mentiste aos homens, mas a Deus.

[[v44-5-5]]

^<<v44-5-5,5>>^ E Ananias, ouvindo estas palavras, caiu e expirou. E um grande temor veio sobre todos os que isto ouviram.

[[v44-5-6]]

^<<v44-5-6,6>>^ E, levantando-se os mancebos, cobriram o morto, e transportando- o  para fora, o sepultaram.

[[v44-5-7]]

^<<v44-5-7,7>>^ E, passando um espaço quase de três horas, entrou também sua mulher, não sabendo o que havia acontecido.

[[v44-5-8]]

^<<v44-5-8,8>>^ E disse-lhe Pedro: Dize-me, vendestes por tanto aquela herdade? E ela disse: Sim, por tanto.

[[v44-5-9]]

^<<v44-5-9,9>>^ Então Pedro lhe disse: Por que é que entre vós vos concertastes para tentar o Espírito do Senhor? Eis aí à porta os pés dos que sepultaram o teu marido, e também  te levarão a ti.

[[v44-5-10]]

^<<v44-5-10,10>>^ E logo caiu aos seus pés, e expirou. E, entrando os mancebos, acharam-na morta, e a sepultaram junto de seu marido.

[[v44-5-11]]

^<<v44-5-11,11>>^ E houve um grande temor em toda a igreja e em todos os que ouviram estas coisas.

[[v44-5-12]]

^<<v44-5-12,12>>^ E muitos sinais e prodígios eram feitos entre o povo pelas mãos dos apóstolos. E estavam todos unanimemente no alpendre de Salomão.

[[v44-5-13]]

^<<v44-5-13,13>>^ Quanto aos outros ninguém ousava ajuntar-se com eles: mas o povo tinha-os em grande estima.

[[v44-5-14]]

^<<v44-5-14,14>>^ E a multidão dos que criam no Senhor, tanto homens como mulheres, crescia cada vez mais.

[[v44-5-15]]

^<<v44-5-15,15>>^ De sorte que transportavam os enfermos para as ruas, e os  punham em leitos e em camilhas para que ao menos a sombra de Pedro, quando este passasse, cobrisse alguns deles.

[[v44-5-16]]

^<<v44-5-16,16>>^ E até das cidades circunvizinhas concorria muita gente a Jerusalém, conduzindo enfermos e atormentados de espíritos imundos; os quais todos eram curados.

[[v44-5-17]]

^<<v44-5-17,17>>^ E, levantando-se o sumo sacerdote, e todos os que estavam com ele (e eram eles da seita dos saduceus), encheram-se de inveja.

[[v44-5-18]]

^<<v44-5-18,18>>^ E lançaram mão dos apóstolos, e os puseram na prisão pública.

[[v44-5-19]]

^<<v44-5-19,19>>^ Mas de noite um anjo do Senhor abriu as portas da prisão, e, tirando-os para fora, disse:

[[v44-5-20]]

^<<v44-5-20,20>>^ Ide e apresentai-vos no templo, e dizei ao povo todas as palavras desta vida.

[[v44-5-21]]

^<<v44-5-21,21>>^ E, ouvindo eles, isto , entraram de manhã cedo no templo, e ensinavam. Chegando porém, o sumo sacerdote e os que estavam com ele, convocaram o conselho e a todos os anciãos dos filhos d’Israel, e enviaram ao cárcere, para que de lá os trouxessem.

[[v44-5-22]]

^<<v44-5-22,22>>^ Mas, tendo lá ido os servidores, não os acharam na prisão, e voltando, lho  anunciaram.

[[v44-5-23]]

^<<v44-5-23,23>>^ Dizendo: Achamos realmente o cárcere fechado, com toda a segurança, e os guardas, que estavam fora, diante das portas; mas, quando abrimos, ninguém achamos dentro.

[[v44-5-24]]

^<<v44-5-24,24>>^ Então o capitão do templo e os principais dos sacerdotes, ouvindo estas palavras, estavam perplexos acerca deles e do que viria a ser aquilo.

[[v44-5-25]]

^<<v44-5-25,25>>^ E, chegando um, anunciou-lhes, dizendo: Eis que os homens que encerrastes na prisão estão no templo e ensinam ao povo.

[[v44-5-26]]

^<<v44-5-26,26>>^ Então foi o capitão com os servidores, e os trouxe, não com violência (porque temiam ser apedrejados pelo povo).

[[v44-5-27]]

^<<v44-5-27,27>>^ E, trazendo-os os  apresentaram ao conselho. E o sumo sacerdote os interrogou, dizendo:

[[v44-5-28]]

^<<v44-5-28,28>>^ Não vos admoestamos nós expressamente que não ensinásseis nesse nome? E eis que enchestes Jerusalém dessa vossa doutrina, e quereis lançar sobre nós o sangue desse homem.

[[v44-5-29]]

^<<v44-5-29,29>>^ Porém, respondendo Pedro e os apóstolos, disseram: Mais importa obedecer a Deus do que aos homens.

[[v44-5-30]]

^<<v44-5-30,30>>^ O Deus de nossos pais ressuscitou a Jesus, ao qual vós matastes, suspendendo- o  no madeiro.

[[v44-5-31]]

^<<v44-5-31,31>>^ Deus com a sua destra o elevou a Príncipe e Salvador, para dar a Israel o arrependimento e remissão dos pecados.

[[v44-5-32]]

^<<v44-5-32,32>>^ E nós somos testemunhas acerca destas palavras, nós e também o Espírito Santo, que Deus deu àqueles que lhe obedecem.

[[v44-5-33]]

^<<v44-5-33,33>>^ E, ouvindo eles isto , se enfureciam, e deliberaram matá-los.

[[v44-5-34]]

^<<v44-5-34,34>>^ Mas, levantando-se no conselho um certo fariseu, chamado Gamaliel, doutor da lei, venerado por todo o povo, mandou que por um pouco levassem para fora os apóstolos;

[[v44-5-35]]

^<<v44-5-35,35>>^ E disse-lhes: Varões israelitas, acautelai-vos a respeito do que haveis de fazer a estes homens.

[[v44-5-36]]

^<<v44-5-36,36>>^ Porque antes destes dias levantou-se Teudas, dizendo ser alguém: a este se ajuntou um número de uns quatrocentos homens; o qual foi morto, e todos os que lhe deram ouvidos foram dispersos e reduzidos a nada.

[[v44-5-37]]

^<<v44-5-37,37>>^ Depois deste levantou-se Judas, o galileu, nos dias do alistamento, e levou muito povo após si; mas também este pereceu, e todos os que lhe deram ouvidos foram dispersos.

[[v44-5-38]]

^<<v44-5-38,38>>^ E agora digo-vos: Dai de mão a estes homens, e deixai-os, porque, se este conselho ou esta obra é de homens, se desfará,

[[v44-5-39]]

^<<v44-5-39,39>>^ Mas, se é de Deus, não podereis desfazê-la; para que não aconteça serdes também achados combatendo contra Deus.

[[v44-5-40]]

^<<v44-5-40,40>>^ E concordaram com ele. E, chamando os apóstolos, e tendo- os  açoitado, mandaram que não falassem no nome de Jesus, e os deixaram ir.

[[v44-5-41]]

^<<v44-5-41,41>>^ Retiraram-se pois da presença do conselho, regozijando-se de terem sido julgados dignos de padecer afronta pelo nome de Jesus.

[[v44-5-42]]

^<<v44-5-42,42>>^ E todos os dias, no templo e nas casas, não cessavam de ensinar, e de anunciar a Jesus Cristo.

'''

xref:044-atos/044-atos-004.adoc#v44-4-0[&#60; Capítulo Anterior] | <<v44-5-0,Topo>> | xref:044-atos/044-atos-006.adoc#v44-6-0[Próximo Capítulo &#62;]