include::./index.adoc[]

[[v44-27-0]]
=== Atos, 27
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-27-1]]

^<<v44-27-1,1>>^ E, COMO se determinou que havíamos de navegar para a Itália, entregaram Paulo, e alguns outros presos, a um centurião, por nome Júlio, da coorte augusta.

[[v44-27-2]]

^<<v44-27-2,2>>^ E, embarcando nós em um navio adramitino, partimos navegando pelos lugares da costa da Ásia, estando conosco Aristarco, macedônio, de Tessalônica.

[[v44-27-3]]

^<<v44-27-3,3>>^ E chegamos no dia  seguinte a Sidom, e Júlio, tratando Paulo humanamente, lhe  permitiu ir ver os amigos, para que cuidassem dele.

[[v44-27-4]]

^<<v44-27-4,4>>^ E, partindo dali, fomos navegando abaixo de Chipre, porque os ventos eram contrários.

[[v44-27-5]]

^<<v44-27-5,5>>^ E, tendo atravessado o mar, ao longo da Cilícia e Panfília, chegamos a Mirra, na Lícia.

[[v44-27-6]]

^<<v44-27-6,6>>^ E, achando ali o centurião um navio de Alexandria, que navegava para a Itália, nos fez embarcar nele.

[[v44-27-7]]

^<<v44-27-7,7>>^ E, como por muitos dias navegássemos vagarosamente, havendo chegado apenas defronte de Cnido, não nos permitindo o vento ir mais adiante, navegamos abaixo de Creta, junto de Salmone.

[[v44-27-8]]

^<<v44-27-8,8>>^ E, costeando-a dificilmente, chegamos a um lugar chamado Bons Portos, perto do qual estava a cidade de Laseia.

[[v44-27-9]]

^<<v44-27-9,9>>^ E, passado muito tempo, e sendo já perigosa a navegação, pois também o jejum já tinha passado, Paulo os  admoestava,

[[v44-27-10]]

^<<v44-27-10,10>>^ Dizendo-lhes: Varões, vejo que a navegação há de ser incômoda, e com muito dano, não só para o navio e carga, mas também para as nossas vidas.

[[v44-27-11]]

^<<v44-27-11,11>>^ Mas o centurião cria mais no piloto e no mestre, do que no que dizia Paulo.

[[v44-27-12]]

^<<v44-27-12,12>>^ E, como aquele porto não era cômodo para invernar, os mais deles foram de parecer que se partisse dali para ver se podiam chegar a Fênix, que é  um ponto de Creta que olha para a banda do vento da África e do Coro, e invernar ali.

[[v44-27-13]]

^<<v44-27-13,13>>^ E, soprando o sul brandamente, lhes pareceu terem já o que desejavam, e, fazendo-se de vela, foram de muito perto costeando Creta.

[[v44-27-14]]

^<<v44-27-14,14>>^ Mas não muito depois deu nela um pé de vento, chamado euro-aquilão.

[[v44-27-15]]

^<<v44-27-15,15>>^ E, sendo o navio arrebatado, e não podendo navegar contra o vento, dando de mão a tudo, nos deixamos ir à toa.

[[v44-27-16]]

^<<v44-27-16,16>>^ E, correndo abaixo de uma pequena ilha chamada Clauda, apenas pudemos ganhar o batel.

[[v44-27-17]]

^<<v44-27-17,17>>^ E, levado este para cima, usaram de todos  os meios, cingindo o navio; e, temendo darem à costa na Sirte, amainadas as velas, assim foram à toa.

[[v44-27-18]]

^<<v44-27-18,18>>^ E, andando nós agitados por uma veemente tempestade, no dia  seguinte aliviaram o navio.

[[v44-27-19]]

^<<v44-27-19,19>>^ E ao terceiro dia  nós mesmos, com as nossas próprias mãos, lançamos ao mar  a armação do navio.

[[v44-27-20]]

^<<v44-27-20,20>>^ E, não aparecendo, havia já  muitos dias, nem sol nem estrelas, e caindo sobre nós uma não pequena tempestade fugiu-nos toda a esperança de nos salvarmos.

[[v44-27-21]]

^<<v44-27-21,21>>^ E, havendo já muito que se não comia, então Paulo, pondo-se em pé no meio deles, disse: Fora, na verdade, razoável, ó varões, ter-me ouvido a mim e não partir de Creta, e assim evitariam este incômodo e esta perdição.

[[v44-27-22]]

^<<v44-27-22,22>>^ Mas agora vos admoesto a que tenhais bom ânimo, porque não se perderá a vida de nenhum  de vós, mas somente o navio.

[[v44-27-23]]

^<<v44-27-23,23>>^ Porque esta mesma noite o anjo de Deus, de quem eu sou, e a quem sirvo esteve comigo,

[[v44-27-24]]

^<<v44-27-24,24>>^ Dizendo: Paulo, não temas: importa que sejas apresentado a César, e eis que Deus te deu todos quantos navegam contigo.

[[v44-27-25]]

^<<v44-27-25,25>>^ Portanto, ó varões, tende bom ânimo: porque creio em Deus, que há de acontecer assim como a mim me foi dito.

[[v44-27-26]]

^<<v44-27-26,26>>^ É contudo necessário irmos dar numa ilha.

[[v44-27-27]]

^<<v44-27-27,27>>^ E, quando chegou a décima quarta noite, sendo impelidos de uma e outra banda no mar  Adriático, lá pela meia-noite suspeitaram os marinheiros que estavam próximos de alguma terra.

[[v44-27-28]]

^<<v44-27-28,28>>^ E, lançando o prumo, acharam vinte braças; e, passando um pouco mais adiante, tornando a lançar o prumo, acharam quinze braças.

[[v44-27-29]]

^<<v44-27-29,29>>^ E, temendo ir dar em alguns rochedos, lançaram da popa quatro âncoras, desejando que viesse o dia.

[[v44-27-30]]

^<<v44-27-30,30>>^ Procurando, porém, os marinheiros fugir do navio, e tendo já deitado o batel ao mar, como que querendo lançar as âncoras pela proa,

[[v44-27-31]]

^<<v44-27-31,31>>^ Disse Paulo ao centurião e  aos soldados: Se estes não ficarem no navio, não podereis salvar-vos.

[[v44-27-32]]

^<<v44-27-32,32>>^ Então os soldados cortaram os cabos do batel, e o deixaram cair.

[[v44-27-33]]

^<<v44-27-33,33>>^ E, entretanto que o dia vinha, Paulo exortava a todos a que comessem alguma coisa, dizendo: É já  hoje o décimo quarto dia que esperais, e permaneceis sem comer, não havendo provado nada.

[[v44-27-34]]

^<<v44-27-34,34>>^ Portanto, exorto-vos a que comais alguma coisa, pois é para a vossa saúde; porque nem um cabelo cairá da cabeça de qualquer de vós.

[[v44-27-35]]

^<<v44-27-35,35>>^ E, havendo dito isto, tomando o pão, deu graças a Deus na presença de todos; e, partindo- o , começou a comer.

[[v44-27-36]]

^<<v44-27-36,36>>^ E, tendo já todos bom ânimo, puseram-se também a comer.

[[v44-27-37]]

^<<v44-27-37,37>>^ E éramos por todos no navio duzentas e setenta e seis almas.

[[v44-27-38]]

^<<v44-27-38,38>>^ E, refeitos com a comida, aliviaram o navio, lançando o trigo ao mar.

[[v44-27-39]]

^<<v44-27-39,39>>^ E, sendo já dia, não conheceram a terra; enxergaram porém uma enseada que tinha praia, e consultaram-se sobre se deveriam encalhar nela o navio.

[[v44-27-40]]

^<<v44-27-40,40>>^ E, levantando as âncoras, deixaram-no ir ao mar, largando também as amarras do leme; e, alçando a vela maior ao vento, dirigiram-se para a praia.

[[v44-27-41]]

^<<v44-27-41,41>>^ Dando, porém, num lugar de dois mares, encalharam ali o navio; e, fixa a proa, ficou imóvel, mas a popa abria-se com a força das ondas.

[[v44-27-42]]

^<<v44-27-42,42>>^ Então a ideia dos soldados foi que matassem os presos para que nenhum fugisse, escapando a nado.

[[v44-27-43]]

^<<v44-27-43,43>>^ Mas o centurião, querendo salvar a Paulo, lhes estorvou este intento; e mandou que os que pudessem nadar se lançassem primeiro ao mar , e se salvassem em terra;

[[v44-27-44]]

^<<v44-27-44,44>>^ E os demais, uns em tábuas e outros em coisas do navio. E assim aconteceu que todos chegaram à terra, a salvo.

'''

xref:044-atos/044-atos-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-atos/044-atos-028.adoc#v44-28-0[Próximo Capítulo &#62;]