include::./index.adoc[]

[[v44-18-0]]
=== Atos, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v44-18-1]]

^<<v44-18-1,1>>^ E DEPOIS disto partiu Paulo de Atenas, e chegou a Corinto.

[[v44-18-2]]

^<<v44-18-2,2>>^ E, achando um certo  judeu por nome Áquila, natural do Ponto, que havia pouco tinha vindo da Itália, e Priscila, sua mulher (pois Cláudio tinha mandado que todos os judeus saíssem de Roma), se ajuntou com eles,

[[v44-18-3]]

^<<v44-18-3,3>>^ E, como era do mesmo ofício, ficou com eles, e trabalhava; pois tinham por ofício fazer tendas.

[[v44-18-4]]

^<<v44-18-4,4>>^ E todos os sábados disputava na sinagoga, e convencia a judeus e gregos.

[[v44-18-5]]

^<<v44-18-5,5>>^ E, quando Silas e Timóteo desceram da Macedônia, foi Paulo impulsionado pela palavra, testificando aos judeus que  Jesus era  o Cristo.

[[v44-18-6]]

^<<v44-18-6,6>>^ Mas resistindo e blasfemando eles, sacudiu os vestidos, e disse-lhes: O vosso sangue seja  sobre a vossa cabeça; eu estou  limpo, e desde agora parto para os gentios.

[[v44-18-7]]

^<<v44-18-7,7>>^ E, saindo dali entrou em casa de um homem chamado Tito Justo, que servia a Deus, e cuja casa estava junto da sinagoga.

[[v44-18-8]]

^<<v44-18-8,8>>^ E Crispo, principal da sinagoga, creu no Senhor com toda a sua casa; e muitos dos coríntios, ouvindo- o  creram e foram batizados.

[[v44-18-9]]

^<<v44-18-9,9>>^ E disse o Senhor em visão a Paulo: Não temas, mas fala, e não te cales;

[[v44-18-10]]

^<<v44-18-10,10>>^ Porque eu sou contigo, e ninguém lançará mão de ti para te fazer mal, pois tenho muito povo nesta cidade.

[[v44-18-11]]

^<<v44-18-11,11>>^ E ficou ali  um ano e seis meses, ensinando entre eles a palavra de Deus.

[[v44-18-12]]

^<<v44-18-12,12>>^ Mas, sendo Gálio procônsul da Acaia, levantaram-se os judeus concordemente contra Paulo, e o levaram ao tribunal,

[[v44-18-13]]

^<<v44-18-13,13>>^ Dizendo: Este persuade os homens a servir a Deus contra a lei.

[[v44-18-14]]

^<<v44-18-14,14>>^ E, querendo Paulo abrir a boca, disse Gálio aos judeus: Se houvesse, ó judeus, algum agravo ou crime enorme, com razão vos sofreria,

[[v44-18-15]]

^<<v44-18-15,15>>^ Mas, se a questão é de palavras, e de nomes, e da lei que entre vós há, vede-o vós mesmos: porque eu não quero ser juiz dessas coisas.

[[v44-18-16]]

^<<v44-18-16,16>>^ E expulsou-os do tribunal.

[[v44-18-17]]

^<<v44-18-17,17>>^ Então todos agarraram Sostenes, principal da sinagoga, e o feriram diante do tribunal; e a Gálio nada destas coisas o incomodava.

[[v44-18-18]]

^<<v44-18-18,18>>^ E Paulo, ficando ainda ali  muitos dias, despediu-se dos irmãos e dali navegou para a Síria, e com ele Priscila e Áquila, tendo rapado a cabeça em Cencreia, porque tinha voto.

[[v44-18-19]]

^<<v44-18-19,19>>^ E chegou a Éfeso, e deixou-os ali; mas ele, entrando na sinagoga, disputava com os judeus.

[[v44-18-20]]

^<<v44-18-20,20>>^ E, rogando- lhe  eles que ficasse por mais algum tempo, não conveio nisso.

[[v44-18-21]]

^<<v44-18-21,21>>^ Antes se despediu deles, dizendo: querendo Deus, outra vez voltarei a vós. E partiu de Éfeso.

[[v44-18-22]]

^<<v44-18-22,22>>^ E, chegando a Cesareia, subiu a Jerusalém , e, saudando a igreja, desceu a Antioquia.

[[v44-18-23]]

^<<v44-18-23,23>>^ E, estando ali  algum tempo, partiu, passando sucessivamente pela província da Galácia e da Frígia, confirmando a todos os discípulos.

[[v44-18-24]]

^<<v44-18-24,24>>^ E chegou a Éfeso um  certo judeu chamado Apolo, natural d’Alexandria, varão eloquente e poderoso nas Escrituras.

[[v44-18-25]]

^<<v44-18-25,25>>^ Este era instruído no caminho do Senhor, e, fervoroso de espírito, falava e ensinava diligentemente as coisas  do Senhor, conhecendo somente o batismo de João.

[[v44-18-26]]

^<<v44-18-26,26>>^ Ele começou a falar ousadamente na sinagoga; e, quando o ouviram Priscila e Áquila, o levaram consigo, e lhe declararam mais pontualmente o caminho de Deus.

[[v44-18-27]]

^<<v44-18-27,27>>^ Querendo ele passar à Acaia, o animaram os irmãos, e escreveram aos discípulos que o recebessem; o qual, tendo chegado, aproveitou muito aos que pela graça criam.

[[v44-18-28]]

^<<v44-18-28,28>>^ Porque com grande veemência convencia publicamente os judeus, mostrando pelas Escrituras que Jesus era o Cristo.

'''

xref:044-atos/044-atos-017.adoc#v44-17-0[&#60; Capítulo Anterior] | <<v44-18-0,Topo>> | xref:044-atos/044-atos-019.adoc#v44-19-0[Próximo Capítulo &#62;]