include::./index.adoc[]

[[v65-1-0]]
=== Judas, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v65-1-1]]

^<<v65-1-1,1>>^ JUDAS, servo de Jesus Cristo, e irmão de Tiago, aos chamados, queridos em Deus Pai, e conservados por Jesus Cristo:

[[v65-1-2]]

^<<v65-1-2,2>>^ Misericórdia, e paz, e caridade vos sejam multiplicadas.

[[v65-1-3]]

^<<v65-1-3,3>>^ Amados, procurando eu escrever-vos com toda a diligência acerca da salvação comum, tive por necessidade escrever-vos, e exortar-vos a batalhar pela fé que uma vez foi dada aos santos.

[[v65-1-4]]

^<<v65-1-4,4>>^ Porque se introduziram alguns, que já antes estavam escritos para este mesmo juízo, homens ímpios, que convertem em dissolução a graça de Deus, e negam a Deus, único dominador e Senhor nosso, Jesus Cristo.

[[v65-1-5]]

^<<v65-1-5,5>>^ Mas quero lembrar-vos, como a quem já uma vez soube isto, que, havendo o Senhor salvo um povo, tirando-o da terra do Egito, destruiu depois os que não creram;

[[v65-1-6]]

^<<v65-1-6,6>>^ E aos anjos que não guardaram o seu principado, mas deixaram a sua própria habitação, reservou na escuridão, e em prisões eternas até ao juízo daquele grande dia;

[[v65-1-7]]

^<<v65-1-7,7>>^ Assim como Sodoma e Gomorra, e as cidades circunvizinhas, que, havendo-se corrompido como aqueles, e ido após outra carne, foram postas por exemplo, sofrendo a pena do fogo eterno.

[[v65-1-8]]

^<<v65-1-8,8>>^ E, contudo, também estes, semelhantemente adormecidos, contaminam a sua carne, e rejeitam a dominação, e vituperam as dignidades.

[[v65-1-9]]

^<<v65-1-9,9>>^ Mas o arcanjo Miguel, quando contendia com o diabo, e disputava a respeito do corpo de Moisés, não ousou pronunciar juízo de maldição contra ele; mas disse: O Senhor te repreenda.

[[v65-1-10]]

^<<v65-1-10,10>>^ Estes porém dizem mal do que não sabem; e, naquilo que naturalmente conhecem, como animais irracionais se corrompem.

[[v65-1-11]]

^<<v65-1-11,11>>^ Ai deles! porque entraram pelo caminho de Caim, e foram levados pelo engano do prêmio de Balaão, e pereceram na contradição de Coré.

[[v65-1-12]]

^<<v65-1-12,12>>^ Estes são manchas em vossas festas de caridade, banqueteando-se convosco e apascentando-se a si mesmos sem temor: são  nuvens sem água, levadas pelos ventos de uma para outra parte: são  como árvores murchas, infrutíferas, duas vezes mortas, desarraigadas;

[[v65-1-13]]

^<<v65-1-13,13>>^ Ondas impetuosas do mar, que escumam as suas mesmas abominações: estrelas errantes, para os quais está eternamente reservada a negrura das trevas.

[[v65-1-14]]

^<<v65-1-14,14>>^ E destes profetizou também Enoque, o sétimo depois de Adão, dizendo: Eis que é vindo o Senhor com milhares de seus santos;

[[v65-1-15]]

^<<v65-1-15,15>>^ Para fazer juízo contra todos e condenar dentre eles todos os ímpios, por todas as suas obras de impiedade, que impiamente cometeram, e por todas as duras palavras  que ímpios pecadores disseram contra ele.

[[v65-1-16]]

^<<v65-1-16,16>>^ Estes são murmuradores, queixosos da sua sorte, andando segundo as suas concupiscências, e cuja boca diz coisas  mui arrogantes, admirando as pessoas por causa do interesse.

[[v65-1-17]]

^<<v65-1-17,17>>^ Mas vós, amados, lembrai-vos das palavras que vos foram preditas pelos apóstolos de nosso Senhor Jesus Cristo:

[[v65-1-18]]

^<<v65-1-18,18>>^ Os quais vos diziam que no último tempo haveria escarnecedores que andariam segundo as suas ímpias concupiscências.

[[v65-1-19]]

^<<v65-1-19,19>>^ Estes são os que causam divisões, sensuais, que não têm o Espírito.

[[v65-1-20]]

^<<v65-1-20,20>>^ Mas vós, amados, edificando-vos a vós mesmos sobre a vossa santíssima fé, orando no Espírito Santo,

[[v65-1-21]]

^<<v65-1-21,21>>^ Conservai-vos a vós mesmos na caridade de Deus, esperando a misericórdia de nosso Senhor Jesus Cristo para a vida eterna.

[[v65-1-22]]

^<<v65-1-22,22>>^ E apiedai-vos de alguns, que estão duvidosos;

[[v65-1-23]]

^<<v65-1-23,23>>^ E salvai alguns arrebatando-os do fogo; tende deles misericórdia com temor, aborrecendo até a roupa manchada da carne.

[[v65-1-24]]

^<<v65-1-24,24>>^ Ora, àquele que é poderoso para vos guardar de tropeçar, e apresentar-vos irrepreensíveis, com alegria, perante a sua glória,

[[v65-1-25]]

^<<v65-1-25,25>>^ Ao único Deus, Salvador nosso, por Jesus Cristo, nosso Senhor, seja  glória e majestade, domínio e poder, antes de todos os séculos, agora, e para todo o sempre. Amém.

'''

xref:064-3-joao/064-3-joao-001.adoc#v64-1-0[&#60; Capítulo Anterior] | <<v65-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-001.adoc#v66-1-0[Próximo Capítulo &#62;]