include::./index.adoc[]

[[v14-10-0]]
=== 2 Crônicas, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-10-1]]

^<<v14-10-1,1>>^ E FOI Roboão a Siquém, porque todo o Israel tinha vindo a Siquém para o fazerem rei.

[[v14-10-2]]

^<<v14-10-2,2>>^ Sucedeu pois que, ouvindo-o Jeroboão, filho de Nebate (o qual estava então  no Egito para onde fugira da presença do rei Salomão) voltou Jeroboão do Egito.

[[v14-10-3]]

^<<v14-10-3,3>>^ Porque enviaram a ele , e o chamaram: e veio pois Jeroboão com todo o Israel: e falaram a Roboão, dizendo:

[[v14-10-4]]

^<<v14-10-4,4>>^ Teu pai fez duro o nosso jugo, alivia tu pois agora a dura servidão de teu pai, e o pesado jugo, que nos tinha imposto, e servir-te-emos.

[[v14-10-5]]

^<<v14-10-5,5>>^ E ele lhes disse: Daqui a três dias tornai a mim. Então o povo se foi.

[[v14-10-6]]

^<<v14-10-6,6>>^ E teve Roboão conselho com os anciãos, que estiveram perante Salomão seu pai, enquanto viveu, dizendo: Como aconselhais vós que se responda a este povo?

[[v14-10-7]]

^<<v14-10-7,7>>^ E eles lhe falaram, dizendo: Se te fizeres benigno e afável com este povo, e lhes falares boas palavras, todos os dias serão teus servos.

[[v14-10-8]]

^<<v14-10-8,8>>^ Porém ele deixou o conselho, que os anciãos lhe deram: e teve conselho com os mancebos, que haviam crescido com ele, e estavam perante ele.

[[v14-10-9]]

^<<v14-10-9,9>>^ E disse-lhes: Que aconselhais vós, que respondamos a este povo, que me falou, dizendo: Alivia- nos  o jugo que teu pai nos impôs?

[[v14-10-10]]

^<<v14-10-10,10>>^ E os mancebos, que com ele haviam crescido, lhe falaram, dizendo: Assim dirás a este povo, que te falou, dizendo: Teu pai agravou o nosso jugo, tu porém alivia-nos. Assim pois lhe falarás: O meu dedo  mínimo é mais grosso do que os lombos de meu pai.

[[v14-10-11]]

^<<v14-10-11,11>>^ Assim que se meu pai vos fez carregar dum jugo pesado, eu ainda acrescentarei sobre o vosso jugo: meu pai vos castigou com açoites, porém eu vos castigarei  com escorpiões.

[[v14-10-12]]

^<<v14-10-12,12>>^ Veio pois Jeroboão, e todo o povo a Roboão, no terceiro dia, como o rei tinha ordenado, dizendo: Tornai a mim ao terceiro dia.

[[v14-10-13]]

^<<v14-10-13,13>>^ E o rei lhes respondeu asperamente: porque o rei Roboão deixou o conselho dos anciãos.

[[v14-10-14]]

^<<v14-10-14,14>>^ E falou-lhes conforme ao conselho dos mancebos, dizendo: Meu pai agravou o vosso jugo, porém eu lhes acrescentarei mais: meu pai vos castigou com açoites, porém eu vos castigarei  com escorpiões.

[[v14-10-15]]

^<<v14-10-15,15>>^ Assim o rei não deu ouvidos ao povo, porque esta mudança vinha de Deus, para que o Senhor confirmasse a sua palavra, a qual falara pelo ministério de Aías, o silonita, a Jeroboão, filho de Nebate.

[[v14-10-16]]

^<<v14-10-16,16>>^ Vendo pois todo o Israel que o rei lhes não dava ouvidos, então o povo respondeu ao rei, dizendo: Que parte temos nós com Davi? já  não temos  herança no filho de Isai; Israel, cada um às suas tendas! Olha agora pela tua casa, ó Davi. Assim todo o Israel se foi para as suas tendas.

[[v14-10-17]]

^<<v14-10-17,17>>^ Porém, quanto aos filhos de Israel, que habitavam nas cidades de Judá, sobre eles reinou Roboão.

[[v14-10-18]]

^<<v14-10-18,18>>^ Então o rei Roboão enviou a Hadorão, que tinha o cargo dos tributos; porém os filhos de Israel o apedrejaram com pedras, de que morreu: então o rei Roboão se apressou a subir para o seu carro, e fugiu para Jerusalém.

[[v14-10-19]]

^<<v14-10-19,19>>^ Assim se revoltaram os israelitas contra a casa Davi, até ao dia de  hoje.

'''

xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[&#60; Capítulo Anterior] | <<v14-10-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[Próximo Capítulo &#62;]