include::./index.adoc[]

[[v14-32-0]]
=== 2 Crônicas, 32
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-32-1]]

^<<v14-32-1,1>>^ DEPOIS destas cousas e desta fidelidade, veio Senaqueribe, rei da Assíria, e entrou em Judá, e acampou-se contra as cidades fortes, e intentou separá-las para si.

[[v14-32-2]]

^<<v14-32-2,2>>^ Vendo pois Ezequias que Senaqueribe vinha, e que o seu rosto era de  guerra contra Jerusalém,

[[v14-32-3]]

^<<v14-32-3,3>>^ Teve conselho com os seus príncipes e os seus varões, para que se tapassem as fontes das águas que havia  fora da cidade: e eles o ajudaram.

[[v14-32-4]]

^<<v14-32-4,4>>^ Assim muito povo se ajuntou, que tapou todas as fontes, como também o ribeiro que se estendia pelo meio da terra, dizendo: Por que viriam os reis da Assíria, e achariam tantas águas?

[[v14-32-5]]

^<<v14-32-5,5>>^ E ele se fortificou, e edificou todo o muro quebrado até às torres, e levantou o outro muro para fora; e fortificou a Milo na cidade de Davi, e fez armas e escudos em abundância.

[[v14-32-6]]

^<<v14-32-6,6>>^ E pôs oficiais de guerra sobre o povo, e ajuntou-os a si na praça da porta da cidade, e falou-lhes ao coração, dizendo:

[[v14-32-7]]

^<<v14-32-7,7>>^ Esforçai-vos, e tende bom ânimo; não temais, nem vos espanteis, por causa do rei da Assíria, nem por causa de toda a multidão que está  com ele, porque há um maior conosco do que com ele.

[[v14-32-8]]

^<<v14-32-8,8>>^ Com ele está  o braço de carne, mas conosco o Senhor nosso Deus, para nos ajudar, e para guerrear nossas guerras. E o povo descansou nas palavras de Ezequias rei de Judá.

[[v14-32-9]]

^<<v14-32-9,9>>^ Depois disto Senaqueribe, rei da Assíria, enviou os seus servos a Jerusalém (ele porém estava  diante de Laquis, com todo o seu domínio), a Ezequias, rei de Judá, e a todo o Judá que estava  em Jerusalém, dizendo:

[[v14-32-10]]

^<<v14-32-10,10>>^ Assim diz Senaqueribe, rei da Assíria: Em que confiais vós, que vos ficais na fortaleza em Jerusalém?

[[v14-32-11]]

^<<v14-32-11,11>>^ Porventura  não vos incita Ezequias, para morrerdes à fome e à sede, dizendo: O Senhor nosso Deus nos livrará das mãos do rei da Assíria?

[[v14-32-12]]

^<<v14-32-12,12>>^ Não é Ezequias o mesmo que tirou os seus altos e os seus altares, e falou a Judá e a Jerusalém, dizendo: Diante do único altar vos prostrareis, e sobre ele queimareis incenso?

[[v14-32-13]]

^<<v14-32-13,13>>^ Não sabeis vós o que eu e meus pais fizemos a todos os povos das terras? porventura  puderam de qualquer maneira os deuses das nações daquelas terras livrar a sua terra da minha mão?

[[v14-32-14]]

^<<v14-32-14,14>>^ Qual é , de todos os deuses daquelas nações que meus pais destruíram, que pôde livrar o seu povo da minha mão, para que vosso Deus vos possa livrar da minha mão?

[[v14-32-15]]

^<<v14-32-15,15>>^ Agora, pois, não vos engane Ezequias, nem vos incite assim, nem lhe deis crédito; porque nenhum deus de nação alguma, nem de reino algum, pôde livrar o seu povo da minha mão, nem da mão de meus pais: quanto menos vos poderá livrar o vosso Deus da minha mão?

[[v14-32-16]]

^<<v14-32-16,16>>^ Também seus servos falaram ainda mais contra o Senhor Deus, e contra Ezequias, o seu servo.

[[v14-32-17]]

^<<v14-32-17,17>>^ Escreveu também cartas, para blasfemar do Senhor Deus de Israel, e para falar contra ele, dizendo: Assim como os deuses das nações das terras não livraram o seu povo da minha mão, assim também o Deus de Ezequias não livrará o seu povo da minha mão.

[[v14-32-18]]

^<<v14-32-18,18>>^ E clamaram em alta voz em judaico contra o povo de Jerusalém, que estava  em cima do muro, para os atemorizarem e os perturbarem, para tomarem a cidade.

[[v14-32-19]]

^<<v14-32-19,19>>^ E falaram do Deus de Jerusalém, como dos deuses dos povos da terra, obras das mãos dos homens.

[[v14-32-20]]

^<<v14-32-20,20>>^ Porém o rei Ezequias e o profeta Isaías, filho de Amós, oraram por causa disso, e clamaram ao céu.

[[v14-32-21]]

^<<v14-32-21,21>>^ Então o Senhor enviou um anjo que destruiu a todos os varões valentes, e os príncipes, e os chefes no arraial do rei da Assíria; e este tornou com vergonha de rosto à sua terra; e, entrando na casa de seu deus, os mesmos, que saíram das suas entranhas, o mataram ali à espada.

[[v14-32-22]]

^<<v14-32-22,22>>^ Assim livrou o Senhor a Ezequias, e aos moradores de Jerusalém, da mão de Senaqueribe, rei da Assíria, e da mão de todos; e de todos os lados os guiou.

[[v14-32-23]]

^<<v14-32-23,23>>^ E muitos traziam presentes a Jerusalém ao Senhor, e cousas preciosíssimas a Ezequias, rei de Judá, de modo que depois disto foi exaltado perante os olhos de todas as nações.

[[v14-32-24]]

^<<v14-32-24,24>>^ Naqueles dias Ezequias adoeceu de morte; e orou ao Senhor, o qual lhe falou, e lhe deu um sinal.

[[v14-32-25]]

^<<v14-32-25,25>>^ Mas não correspondeu Ezequias ao benefício que se lhe fez; porque o seu coração se exaltou; pelo que veio grande indignação sobre ele, e sobre Judá e Jerusalém.

[[v14-32-26]]

^<<v14-32-26,26>>^ Ezequias, porém, se humilhou pela soberba do seu coração, ele e os habitantes de Jerusalém; e a grande indignação do Senhor não veio sobre eles, nos dias de Ezequias.

[[v14-32-27]]

^<<v14-32-27,27>>^ E teve Ezequias riquezas e glória em grande abundância: e fez-se tesouros de prata, e de ouro, e de pedras preciosas, e de especiarias, e de escudos, e de tudo o que se podia desejar.

[[v14-32-28]]

^<<v14-32-28,28>>^ Também armazéns para a colheita do trigo, e do mosto, e do azeite; e estrebarias para toda a casta de animais, e currais para os rebanhos.

[[v14-32-29]]

^<<v14-32-29,29>>^ Edificou também cidades, e possuiu ovelhas e vacas em abundância: porque Deus lhe tinha dado muitíssima fazenda.

[[v14-32-30]]

^<<v14-32-30,30>>^ Também o mesmo Ezequias tapou o manancial superior das águas de Giom, e as fez correr por baixo para o ocidente da cidade de Davi; porque Ezequias prosperou em toda a sua obra.

[[v14-32-31]]

^<<v14-32-31,31>>^ Contudo, no negócio dos embaixadores dos príncipes de Babilônia, que foram enviados a ele, a perguntarem acerca do prodígio que se fez naquela terra, Deus o desamparou, para tentá-lo, para saber tudo o que havia  no seu coração.

[[v14-32-32]]

^<<v14-32-32,32>>^ Quanto ao resto dos sucessos de Ezequias, e as suas beneficências, eis que estão  escritos na visão do profeta Isaías, filho de Amós, e  no livro dos reis de Judá e de Israel.

[[v14-32-33]]

^<<v14-32-33,33>>^ E dormiu Ezequias com seus pais, e o sepultaram no mais alto dos sepulcros dos filhos de Davi; e todo o Judá e os habitantes de Jerusalém lhe fizeram honras na sua morte: e Manassés, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[&#60; Capítulo Anterior] | <<v14-32-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[Próximo Capítulo &#62;]