include::./index.adoc[]

[[v14-22-0]]
=== 2 Crônicas, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-22-1]]

^<<v14-22-1,1>>^ E OS moradores de Jerusalém fizeram rei a Acazias, seu filho mais moço, em seu lugar: porque a tropa, que viera com os arábios ao arraial, tinha morto a todos os mais velhos: e assim reinou Acazias, filho de Jorão, rei de Judá.

[[v14-22-2]]

^<<v14-22-2,2>>^ Era  da idade de quarenta e dois anos, quando começou a reinar, e reinou um ano em Jerusalém: E era  o nome de sua mãe Atália, filha de Onri.

[[v14-22-3]]

^<<v14-22-3,3>>^ Também este andou nos caminhos da casa de Acabe; porque sua mãe era sua conselheira, para obrar impiamente.

[[v14-22-4]]

^<<v14-22-4,4>>^ E fez o que era  mal aos olhos do Senhor, como a casa de Acabe, porque eles eram seus conselheiros depois da morte de seu pai, para a sua perdição.

[[v14-22-5]]

^<<v14-22-5,5>>^ Também andou no seu conselho, e foi-se com Jorão, filho de Acabe, rei de Israel, à peleja contra Hazael, rei da Síria, junto a Ramote-Gileade: e os siros feriram a Jorão.

[[v14-22-6]]

^<<v14-22-6,6>>^ E tornou a curar-se em Jezreel das feridas que se lhe deram junto a Ramá, pelejando contra Hazael, rei da Síria: e Azarias filho de Jorão, rei de Judá, desceu para ver a Jorão, filho de Acabe, em Jezreel; porque estava doente.

[[v14-22-7]]

^<<v14-22-7,7>>^ Veio pois de Deus o abatimento de Acazias, para que viesse a Jorão; porque vindo ele, saiu com Jorão contra Jeú, filho de Ninsi, a quem o Senhor tinha ungido para desarraigar a casa de Acabe.

[[v14-22-8]]

^<<v14-22-8,8>>^ E sucedeu que executando Jeú juízo contra a casa de Acabe, achou os príncipes de Judá e os filhos dos irmãos de Acazias, que serviam a Acazias, e os matou.

[[v14-22-9]]

^<<v14-22-9,9>>^ Depois buscou a Acazias (porque se tinha escondido em Samaria), e o alcançaram, e o trouxeram a Jeú, e o mataram, e o sepultaram; porque disseram: Filho é  de Josafá, que buscou ao Senhor com todo o seu coração. E não tinha já a casa de Acazias ninguém que tivesse força para o reino.

[[v14-22-10]]

^<<v14-22-10,10>>^ Vendo pois Atália, mãe de Acazias, que seu filho era morto, levantou-se, e destruiu toda a semente real da casa de Judá.

[[v14-22-11]]

^<<v14-22-11,11>>^ Porém Josebate, filha do rei, tomou a Joás, filho de Acazias, e tirou-o dentre os filhos do rei, a quem matavam, e o pôs com a sua ama na câmara dos leitos: assim Josebate, filha do rei Jorão, mulher do sacerdote Joiada (porque era irmã de Acazias), o escondeu de diante de Atália, de modo que o não matou.

[[v14-22-12]]

^<<v14-22-12,12>>^ E esteve com eles escondido na casa de Deus seis anos; e Atália reinou sobre a terra.

'''

xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[&#60; Capítulo Anterior] | <<v14-22-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[Próximo Capítulo &#62;]