include::./index.adoc[]

[[v14-8-0]]
=== 2 Crônicas, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-8-1]]

^<<v14-8-1,1>>^ E SUCEDEU, ao cabo de vinte anos, nos quais Salomão edificou a casa do Senhor, e a sua própria casa,

[[v14-8-2]]

^<<v14-8-2,2>>^ Que Salomão edificou as cidades que Hirão lhe tinha dado; e fez habitar nelas os filhos de Israel.

[[v14-8-3]]

^<<v14-8-3,3>>^ Depois foi Salomão a Hamate-Zobá, e a tomou.

[[v14-8-4]]

^<<v14-8-4,4>>^ Também edificou a Tadmor no deserto, e todas as cidades das munições que edificou em Hamate.

[[v14-8-5]]

^<<v14-8-5,5>>^ Edificou também a alta Betorom, e a baixa Betorom, cidades fortes com muros, portas e ferrolhos;

[[v14-8-6]]

^<<v14-8-6,6>>^ Como também a Baalate, e todas as cidades das munições, que Salomão tinha, e todas as cidades dos carros e as cidades dos cavaleiros; e tudo quanto, conforme ao seu desejo, Salomão quis edificar em Jerusalém e no Líbano, e em toda a terra do seu domínio.

[[v14-8-7]]

^<<v14-8-7,7>>^ Quanto a todo o povo, que tinha ficado dos heteus, e amorreus, e ferezeus e heveus, e jebuseus, que não eram de Israel;

[[v14-8-8]]

^<<v14-8-8,8>>^ Dos seus filhos, que ficaram depois deles na terra, os quais os filhos de Israel não destruíram, Salomão os fez tributários, até ao dia de  hoje.

[[v14-8-9]]

^<<v14-8-9,9>>^ Porém dos filhos de Israel, de quem Salomão não fez servos para a sua obra (mas eram  homens de guerra, chefes dos seus capitães, e chefes dos seus carros, e dos seus cavaleiros),

[[v14-8-10]]

^<<v14-8-10,10>>^ Estes pois eram  os chefes dos oficiais que o rei Salomão tinha, duzentos e cinquenta, que presidiam sobre o povo.

[[v14-8-11]]

^<<v14-8-11,11>>^ E Salomão fez subir a filha de Faraó da cidade de Davi para a casa que lhe tinha edificado; porque disse: Minha mulher não morará na casa de Davi, rei de Israel, porquanto santos são os lugares  nos quais entrou a arca do Senhor.

[[v14-8-12]]

^<<v14-8-12,12>>^ Então Salomão ofereceu holocaustos ao Senhor, sobre o altar do Senhor, que tinha edificado diante do pórtico:

[[v14-8-13]]

^<<v14-8-13,13>>^ E isto segundo o dever de cada dia, oferecendo segundo o preceito de Moisés, nos sábados e nas luas novas, a nas solenidades, três vezes no ano: na festa dos pães asmos, e na festa das semanas, e na festa das tendas.

[[v14-8-14]]

^<<v14-8-14,14>>^ Também, conforme à ordem de Davi seu pai, ordenou as turmas dos sacerdotes nos seus ministérios, como também as dos levitas acerca dos seus cargos, para louvarem a Deus, e ministrarem diante dos sacerdotes, segundo o que estava ordenado para cada dia, e os porteiros pelas suas turmas a cada porta: porque tal era o mandado de Davi, o homem de Deus.

[[v14-8-15]]

^<<v14-8-15,15>>^ E não se desviaram do mandado do rei aos sacerdotes e levitas, em negócio nenhum, nem acerca dos tesouros.

[[v14-8-16]]

^<<v14-8-16,16>>^ Assim se preparou toda a obra de Salomão, desde o dia da fundação da casa do Senhor, até se acabar: e assim se aperfeiçoou a casa do Senhor.

[[v14-8-17]]

^<<v14-8-17,17>>^ Então foi Salomão a Esiom-Geber, e a Elote, à praia do mar, na terra de Edom.

[[v14-8-18]]

^<<v14-8-18,18>>^ E enviou-lhe Hirão, por mão de seus servos, navios, e servos práticos do mar, e foram com os servos de Salomão a Ofir, e tomaram de lá quatrocentos e cinquenta talentos de ouro: e os trouxeram ao rei Salomão.

'''

xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[&#60; Capítulo Anterior] | <<v14-8-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[Próximo Capítulo &#62;]