include::./index.adoc[]

[[v14-9-0]]
=== 2 Crônicas, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-9-1]]

^<<v14-9-1,1>>^ E OUVINDO a rainha de Sabá a fama de Salomão, veio a Jerusalém, experimentar Salomão com enigmas, com uma mui grande comitiva de camelos carregados de especiarias, e ouro em abundância e pedras preciosas: e veio a Salomão, e falou com ele de tudo o que tinha no seu coração.

[[v14-9-2]]

^<<v14-9-2,2>>^ E Salomão lhe explicou todas as suas palavras: e nenhuma cousa havia oculta que Salomão lhe não declarasse.

[[v14-9-3]]

^<<v14-9-3,3>>^ Vendo pois a rainha de Sabá a sabedoria de Salomão, e a casa que edificara;

[[v14-9-4]]

^<<v14-9-4,4>>^ E as iguarias da sua mesa, e o assentar dos seus servos, e o estar dos seus criados, e os vestidos deles; e os seus copeiros, e os vestidos deles; e a sua subida pela qual ele subia à casa do Senhor, ficou como fora de si.

[[v14-9-5]]

^<<v14-9-5,5>>^ Então disse ao rei: Foi  verdadeira a palavra que ouvi na minha terra acerca dos teus feitos e da tua sabedoria.

[[v14-9-6]]

^<<v14-9-6,6>>^ Porém não cria nas suas palavras, até que vim, e meus olhos o viram , e eis que me não disseram a metade da grandeza da tua sabedoria: sobrepujaste a fama que ouvi.

[[v14-9-7]]

^<<v14-9-7,7>>^ Bem-aventurados os teus homens, e bem-aventurados estes teus servos, que estão sempre diante de ti, e ouvem a tua sabedoria!

[[v14-9-8]]

^<<v14-9-8,8>>^ Bendito seja o Senhor teu Deus, que se agradou de ti para te pôr como rei sobre o seu trono, pelo Senhor teu Deus: porquanto teu Deus ama a Israel, para o estabelecer perpetuamente; e pôs-te como rei sobre eles, para fazeres juízo e justiça.

[[v14-9-9]]

^<<v14-9-9,9>>^ E deu ao rei cento e vinte talentos de ouro, e especiarias em grande abundância, e pedras preciosas: e nunca houve tais especiarias, quais a rainha de Sabá deu ao rei Salomão.

[[v14-9-10]]

^<<v14-9-10,10>>^ E também os servos de Hirão, e os servos de Salomão, que de Ofir tinham trazido ouro, trouxeram madeira de algumins, e pedras preciosas.

[[v14-9-11]]

^<<v14-9-11,11>>^ E fez o rei corredores de madeira de algumins, para a casa do Senhor, e para a casa do rei, como também harpas e alaúdes para os cantores, quais nunca dantes se viram na terra de Judá.

[[v14-9-12]]

^<<v14-9-12,12>>^ E o rei Salomão deu à rainha de Sabá tudo quanto lhe agradou, e o que lhe pediu, além do que ela mesma trouxera ao rei. Assim voltou e foi para sua terra, ela e os seus servos.

[[v14-9-13]]

^<<v14-9-13,13>>^ E era o peso do ouro, que vinha em um ano a Salomão, seiscentos e sessenta e seis talentos de ouro,

[[v14-9-14]]

^<<v14-9-14,14>>^ Afora o que os negociantes e mercadores traziam: também todos os reis da Arábia, e os príncipes da mesma terra traziam a Salomão ouro e prata.

[[v14-9-15]]

^<<v14-9-15,15>>^ Também fez Salomão duzentos paveses de ouro batido: para cada pavês mandou pesar seiscentos siclos  de ouro batido,

[[v14-9-16]]

^<<v14-9-16,16>>^ Como também trezentos escudos de ouro batido; para cada escudo mandou pesar trezentos siclos  de ouro: e Salomão os pôs na casa do bosque do Líbano.

[[v14-9-17]]

^<<v14-9-17,17>>^ Fez mais o rei um grande trono de marfim; e o cobriu de ouro puro.

[[v14-9-18]]

^<<v14-9-18,18>>^ E o trono tinha  seis degraus, e um estrado de ouro, pegado ao trono, e encostos de ambas as bandas no lugar do assento: e dois leões estavam junto aos encostos.

[[v14-9-19]]

^<<v14-9-19,19>>^ E doze leões estavam ali de ambas as bandas, sobre os seis degraus: outro tal se não fez em nenhum reino.

[[v14-9-20]]

^<<v14-9-20,20>>^ Também todos os vasos de beber do rei Salomão eram  de ouro, e todos os vasos da casa do bosque do Líbano, de ouro puro: a prata reputava-se por nada nos dias de Salomão.

[[v14-9-21]]

^<<v14-9-21,21>>^ Porque, indo os navios do rei, com os servos de Hirão, a Tarsis, tornavam os navios de Tarsis, uma vez em três anos, e traziam ouro e prata, marfim, e bugios, e pavões.

[[v14-9-22]]

^<<v14-9-22,22>>^ Assim excedeu o rei Salomão todos os reis da terra, em riquezas e sabedoria.

[[v14-9-23]]

^<<v14-9-23,23>>^ E todos os reis da terra procuravam ver o rosto de Salomão, para ouvirem a sua sabedoria, que Deus lhe  dera no seu coração.

[[v14-9-24]]

^<<v14-9-24,24>>^ E eles traziam cada um o seu presente, vasos de ouro, e vestidos, armaduras, e especiarias, cavalos e mulos: cada cousa de ano em ano.

[[v14-9-25]]

^<<v14-9-25,25>>^ Teve também Salomão quatro mil estrebarias de cavalos e carros, e doze mil cavaleiros: e pô-los nas cidades dos carros, e com o rei em Jerusalém.

[[v14-9-26]]

^<<v14-9-26,26>>^ E dominava sobre todos os reis, desde o rio até à terra dos filisteus, e até ao termo do Egito.

[[v14-9-27]]

^<<v14-9-27,27>>^ Também o rei fez que houvesse prata em Jerusalém como pedras, e cedros em tanta abundância como as figueiras bravas que há pelas campinas.

[[v14-9-28]]

^<<v14-9-28,28>>^ E do Egito e de todas aquelas terras traziam cavalos a Salomão.

[[v14-9-29]]

^<<v14-9-29,29>>^ Os demais sucessos pois de Salomão, tanto os primeiros como os últimos, porventura  não estão  escritos no livro das falas de Natã, o profeta, e na profecia de Aías, o silonita, e nas visões de Ido, o vidente, acerca de Jeroboão, filhos de Nebate?

[[v14-9-30]]

^<<v14-9-30,30>>^ E reinou Salomão em Jerusalém quarenta anos sobre todo o Israel.

[[v14-9-31]]

^<<v14-9-31,31>>^ E dormiu Salomão com seus pais, e o sepultaram na cidade de Davi seu pai: e Roboão, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[&#60; Capítulo Anterior] | <<v14-9-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[Próximo Capítulo &#62;]