include::./index.adoc[]

[[v14-6-0]]
=== 2 Crônicas, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-6-1]]

^<<v14-6-1,1>>^ ENTÃO disse Salomão: O Senhor tem dito que habitaria nas trevas.

[[v14-6-2]]

^<<v14-6-2,2>>^ E eu te tenho edificado uma casa para morada, e um lugar para a tua eterna habitação.

[[v14-6-3]]

^<<v14-6-3,3>>^ Então o rei virou o seu rosto, e abençoou a toda a congregação de Israel, e toda a congregação de Israel estava em pé.

[[v14-6-4]]

^<<v14-6-4,4>>^ E ele disse: Bendito seja  o Senhor Deus de Israel, que falou pela sua boca a Davi meu pai; e pelas suas mãos o cumpriu, dizendo:

[[v14-6-5]]

^<<v14-6-5,5>>^ Desde o dia em que tirei o meu povo da terra do Egito, não escolhi cidade alguma de todas as tribos de Israel, para edificar nela uma  casa em que estivesse o meu nome; nem escolhi homem algum para ser chefe do meu povo Israel.

[[v14-6-6]]

^<<v14-6-6,6>>^ Porém escolhi Jerusalém para que ali estivesse o meu nome; e escolhi Davi, para que tivesse cargo do meu povo Israel.

[[v14-6-7]]

^<<v14-6-7,7>>^ Também Davi meu pai teve no seu coração o edificar uma  casa ao nome do Senhor, Deus de Israel.

[[v14-6-8]]

^<<v14-6-8,8>>^ Porém o Senhor disse a Davi meu pai: Porquanto tiveste no teu coração o edificar uma  casa ao meu nome, bem fizeste, de ter isto no teu coração.

[[v14-6-9]]

^<<v14-6-9,9>>^ Contudo tu não edificarás a casa mas teu filho, que há de proceder de teus lombos, esse edificará a casa ao meu nome.

[[v14-6-10]]

^<<v14-6-10,10>>^ Assim confirmou o Senhor a sua palavra, que ele falou; porque eu me levantei em lugar de Davi, meu pai, e me assentei sobre o trono de Israel, como o Senhor disse, e edifiquei a casa ao nome do Senhor, Deus de Israel.

[[v14-6-11]]

^<<v14-6-11,11>>^ E pus nela a arca, em que está  o concerto que o Senhor fez com os filhos de Israel.

[[v14-6-12]]

^<<v14-6-12,12>>^ E pôs-se em pé perante o altar do Senhor, defronte de toda a congregação de Israel, e estendeu as suas mãos.

[[v14-6-13]]

^<<v14-6-13,13>>^ Porque Salomão tinha feito uma base de metal, de cinco côvados de comprimento, e de cinco côvados de largura, e de três côvados de altura, e a tinha posto no meio do pátio, e pôs-se nela em pé , e ajoelhou-se em presença de toda a congregação de Israel, e estendeu as suas mãos para o céu.

[[v14-6-14]]

^<<v14-6-14,14>>^ E disse: Ó Senhor, Deus de Israel, não há  Deus semelhante a ti, nem nos céus nem na terra; que guardas o concerto e a beneficência aos teus servos que caminham perante ti de todo o seu coração;

[[v14-6-15]]

^<<v14-6-15,15>>^ Que guardaste ao teu servo Davi, meu pai, o que lhe falaste: porque tu pela tua boca o disseste, e pela tua mão o cumpriste, como se vê  neste dia.

[[v14-6-16]]

^<<v14-6-16,16>>^ Agora pois, Senhor, Deus de Israel, guarda a teu servo Davi, meu pai, o que falaste, dizendo: Nunca faltará de ti varão de diante de mim que se assente sobre o trono de Israel; tão somente que teus filhos guardem seu caminho, andando na minha lei, como tu andaste diante de mim.

[[v14-6-17]]

^<<v14-6-17,17>>^ E agora, Senhor Deus de Israel, verifique-se a tua palavra, que falaste ao teu servo, a Davi.

[[v14-6-18]]

^<<v14-6-18,18>>^ Mas verdadeiramente habitará Deus com os homens na terra? Eis que o céu e o céu dos céus não te podem conter, quanto menos esta casa que tenho edificado?

[[v14-6-19]]

^<<v14-6-19,19>>^ Atende pois à oração do teu servo, e à sua súplica, ó Senhor meu Deus, para ouvires o clamor e a oração, que o teu servo ora perante ti.

[[v14-6-20]]

^<<v14-6-20,20>>^ Que os teus olhos estejam dia e noite abertos sobre este lugar, de que disseste que ali porias o teu nome: para ouvires a oração que o teu servo orar neste lugar.

[[v14-6-21]]

^<<v14-6-21,21>>^ Ouve pois as súplicas do teu servo, e do teu povo Israel, que fizerem neste lugar; e ouve tu do lugar da tua habitação, desde os céus; ouve pois, e perdoa.

[[v14-6-22]]

^<<v14-6-22,22>>^ Quando alguém pecar contra o seu próximo, e lhe impuser juramento de maldição, para se amaldiçoar a si mesmo, e o juramento de maldição vier perante o teu altar, nesta casa,

[[v14-6-23]]

^<<v14-6-23,23>>^ Ouve tu então desde os céus, e obra, e julga a teus servos, pagando ao ímpio, lançando o seu proceder sobre a sua cabeça, e justificando ao justo, dando-lhe segundo a sua justiça.

[[v14-6-24]]

^<<v14-6-24,24>>^ Quando também o teu povo Israel for ferido diante do inimigo, por ter pecado contra ti, e eles se converterem, e confessarem o teu nome, e orarem e suplicarem perante ti nesta casa,

[[v14-6-25]]

^<<v14-6-25,25>>^ Então ouve tu desde os céus, e perdoa os pecados de teu povo Israel; e faze-os tornar à terra que lhes tens dado a eles e a seus pais.

[[v14-6-26]]

^<<v14-6-26,26>>^ Quando os céus se cerrarem, e não houver chuva, por terem pecado contra ti, e orarem neste lugar, e confessarem teu nome, e se converterem dos seus pecados, quando tu os afligires,

[[v14-6-27]]

^<<v14-6-27,27>>^ Então ouve tu desde os céus, e perdoa o pecado de teus servos, e do teu povo Israel, ensinando-lhes o bom caminho, em que andem; e dá chuva sobre a tua terra, que deste ao teu povo em herança.

[[v14-6-28]]

^<<v14-6-28,28>>^ Havendo fome na terra, havendo peste, havendo queimadura dos trigos , ou ferrugem, gafanhotos, ou lagarta, cercando-a algum dos seus inimigos nas terras das suas portas, ou  quando houver qualquer praga, ou qualquer enfermidade,

[[v14-6-29]]

^<<v14-6-29,29>>^ Toda a oração, e toda a súplica, que qualquer homem fizer, ou todo o teu povo Israel, conhecendo cada um a sua praga e a sua dor, e estendendo as suas mãos para esta casa,

[[v14-6-30]]

^<<v14-6-30,30>>^ Então ouve tu desde os céus, do assento da tua habitação, e perdoa, e dá a cada um conforme a todos os seus caminhos, segundo conheces o seu coração (pois só tu conheces o coração dos filhos dos homens),

[[v14-6-31]]

^<<v14-6-31,31>>^ A fim de que te temam, para andarem nos teus caminhos, todos os dias que viverem na terra que deste a nossos pais.

[[v14-6-32]]

^<<v14-6-32,32>>^ Assim também ao estrangeiro, que não for do teu povo Israel, mas, vier de terras remotas por amor do teu grande nome, e da tua poderosa mão, e do teu braço estendido: vindo eles e orando nesta casa,

[[v14-6-33]]

^<<v14-6-33,33>>^ Então ouve tu desde os céus, do assento da tua habitação, e faze conforme a tudo o que o estrangeiro te suplicar: a fim de que todos os povos da terra conheçam o teu nome, e te temam, como o teu povo Israel; e a fim de saberem que pelo teu nome é chamada esta casa que edifiquei.

[[v14-6-34]]

^<<v14-6-34,34>>^ Quando o teu povo sair à guerra contra os seus inimigos, pelo caminho que os enviares, e orarem a ti para a banda desta cidade que escolheste, e desta casa, que edifiquei ao teu nome,

[[v14-6-35]]

^<<v14-6-35,35>>^ Ouve então desde os céus a sua oração, e a sua súplica, e executa o seu direito.

[[v14-6-36]]

^<<v14-6-36,36>>^ Quando pecarem contra ti (pois não há  homem que não peque), e tu te indignares contra eles, e os entregares diante do inimigo, para que os que os cativarem os levem em cativeiro para alguma terra, remota ou vizinha,

[[v14-6-37]]

^<<v14-6-37,37>>^ E na terra, para onde forem levados em cativeiro, tornarem a si, e se converterem, e na terra do seu cativeiro a ti suplicarem, dizendo: Pecamos, perversamente fizemos, e impiamente obramos;

[[v14-6-38]]

^<<v14-6-38,38>>^ E se converterem a ti com todo o seu coração e com toda a sua alma, na terra do seu cativeiro, a que os levaram presos, e orarem para a banda da sua terra, que deste a seus pais, e desta cidade que escolheste, e desta casa que edifiquei ao teu nome,

[[v14-6-39]]

^<<v14-6-39,39>>^ Ouve então desde os céus, do assento da tua habitação, a sua oração e as suas súplicas, e executa o seu direito; e perdoa ao teu povo que houver pecado contra ti.

[[v14-6-40]]

^<<v14-6-40,40>>^ Agora pois, ó meu Deus, estejam os teus olhos abertos, e os teus ouvidos atentos à oração deste lugar.

[[v14-6-41]]

^<<v14-6-41,41>>^ Levanta-te pois, agora, Senhor Deus, para o teu repouso, tu e a arca da tua fortaleza: os teus sacerdotes, ó Senhor Deus, sejam vestidos de salvação, e os teus santos se alegrem do bem.

[[v14-6-42]]

^<<v14-6-42,42>>^ Ah! Senhor Deus, não faças virar o rosto do teu ungido: lembra-te das misericórdias de Davi teu servo.

'''

xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[&#60; Capítulo Anterior] | <<v14-6-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[Próximo Capítulo &#62;]