include::./index.adoc[]

[[v14-21-0]]
=== 2 Crônicas, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-21-1]]

^<<v14-21-1,1>>^ DEPOIS Josafá dormiu com seus pais, e o sepultaram com seus pais na cidade de Davi; e Jorão, seu filho, reinou em seu lugar.

[[v14-21-2]]

^<<v14-21-2,2>>^ E teve irmãos, filhos de Josafá: Azarias, e Jeiel, e Zacarias, e Asarias, e Micael, e Sefatias; todos estes foram  filhos de Josafá, rei de Israel.

[[v14-21-3]]

^<<v14-21-3,3>>^ E seu pai lhes deu muitos dons de prata, e de ouro, e de cousas preciosíssimas, com cidades fortes em Judá: porém o reino deu a Jorão, porquanto era  o primogênito.

[[v14-21-4]]

^<<v14-21-4,4>>^ E, subindo Jorão ao reino de seu pai, e havendo-se fortificado, matou a todos os seus irmãos à espada, como também a alguns  dos príncipes de Israel.

[[v14-21-5]]

^<<v14-21-5,5>>^ Da idade de trinta e dois anos era  Jorão quando começou a reinar; e reinou oito anos em Jerusalém.

[[v14-21-6]]

^<<v14-21-6,6>>^ E andou no caminho dos reis de Israel, como fazia a casa de Acabe; porque tinha a filha de Acabe por mulher; e fazia o que parecia  mal ao olhos do Senhor.

[[v14-21-7]]

^<<v14-21-7,7>>^ Porém o Senhor não quis destruir a casa de Davi, em atenção ao concerto que tinha feito com Davi; e porque também tinha dito que lhe daria por todos os dias uma lâmpada, a ele e a seus filhos.

[[v14-21-8]]

^<<v14-21-8,8>>^ Nos seus dias se revoltaram os idumeus contra o domínio de Judá, e constituíram para si um rei.

[[v14-21-9]]

^<<v14-21-9,9>>^ Pelo que Jorão passou adiante com os seus chefes, e todos os carros com ele; e levantou-se de noite, e feriu aos idumeus, que o tinham cercado, como também aos capitães dos carros.

[[v14-21-10]]

^<<v14-21-10,10>>^ Todavia os idumeus se revoltaram contra o domínio de Judá até ao dia de  hoje; então no mesmo tempo Libna se revoltou de debaixo de seu mando; porque deixara ao Senhor, Deus de seus pais.

[[v14-21-11]]

^<<v14-21-11,11>>^ Ele também fez altos nos montes de Judá: e fez com que se corrompessem os moradores de Jerusalém, e até a Judá impeliu a isso.

[[v14-21-12]]

^<<v14-21-12,12>>^ Então lhe veio um escrito da parte de Elias o profeta, que dizia: Assim diz o Senhor, Deus de Davi teu pai: Porquanto não andaste nos caminhos de Josafá, teu pai, e nos caminhos de Asa, rei de Judá,

[[v14-21-13]]

^<<v14-21-13,13>>^ Mas andaste no caminho dos reis de Israel, e fizeste corromper a Judá e aos moradores de Jerusalém, segundo a corrupção da casa de Acabe, e também mataste a teus irmãos, da casa de teu pai, melhores do que tu,

[[v14-21-14]]

^<<v14-21-14,14>>^ Eis que o Senhor ferirá com um grande flagelo ao teu povo, e aos teus filhos, e às tuas mulheres e a todas as tuas fazendas.

[[v14-21-15]]

^<<v14-21-15,15>>^ Tu também terás uma  grande enfermidade por meio dum  mal nas tuas entranhas, até que te saiam as tuas entranhas, por causa da enfermidade, de dia em dia.

[[v14-21-16]]

^<<v14-21-16,16>>^ Despertou pois o Senhor, contra Jorão o espírito dos filisteus e dos arábios, que estão  da banda dos etíopes.

[[v14-21-17]]

^<<v14-21-17,17>>^ Estes subiram a Judá, e deram sobre ela, e levaram toda a fazenda que se achou na casa do rei, como também a seus filhos e a suas mulheres; de modo que lhe não deixaram filho, senão a Joacaz, o mais moço de seus filhos.

[[v14-21-18]]

^<<v14-21-18,18>>^ E depois de tudo isto o Senhor o feriu nas suas entranhas com uma enfermidade incurável.

[[v14-21-19]]

^<<v14-21-19,19>>^ E sucedeu que, depois de muitos dias, e chegado que foi o fim de dois anos, saíram-lhe as entranhas com a doença, e morreu de más enfermidades: e o seu povo lhe não queimou aromas  como queimara a seus pais.

[[v14-21-20]]

^<<v14-21-20,20>>^ Era da idade de trinta e dois anos  quando começou a reinar, e reinou em Jerusalém oito anos: e foi-se sem deixar de si  saudades algumas ; e o sepultaram na cidade de Davi, porém não nos sepulcros dos reis.

'''

xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[&#60; Capítulo Anterior] | <<v14-21-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[Próximo Capítulo &#62;]