include::./index.adoc[]

[[v14-5-0]]
=== 2 Crônicas, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-5-1]]

^<<v14-5-1,1>>^ ASSIM se acabou toda a obra, que Salomão fez para a casa do Senhor; então trouxe Salomão as cousas consagradas de seu pai Davi, a prata, e o ouro, e todos os vasos, e pô-los entre os tesouros da casa de Deus.

[[v14-5-2]]

^<<v14-5-2,2>>^ Então Salomão convocou em Jerusalém os anciãos de Israel e todos os chefes das tribos, os príncipes dos pais entre os filhos de Israel, para fazerem subir a arca do concerto do Senhor, da cidade de Davi, que é  Sião.

[[v14-5-3]]

^<<v14-5-3,3>>^ E todos o homens de Israel se congregaram ao rei na festa, que foi  no sétimo mês.

[[v14-5-4]]

^<<v14-5-4,4>>^ E vieram todos os anciãos de Israel; e os levitas levantaram a arca.

[[v14-5-5]]

^<<v14-5-5,5>>^ E fizeram subir a arca, e a tenda da congregação, com todos os vasos sagrados, que estavam  na tenda: os sacerdotes e  os levitas fizeram subir.

[[v14-5-6]]

^<<v14-5-6,6>>^ Então o rei Salomão, e toda a congregação de Israel, que se tinha congregado com ele, diante da arca, sacrificaram carneiros, e bois, que se não podiam contar, nem numerar, por causa da sua multidão.

[[v14-5-7]]

^<<v14-5-7,7>>^ Assim trouxeram os sacerdotes a arca do concerto do Senhor ao seu lugar, ao oráculo da casa, à santidade das santidades, até  debaixo das asas dos querubins.

[[v14-5-8]]

^<<v14-5-8,8>>^ Porque os querubins estendiam ambas as asas sobre o lugar da arca, e os querubins por cima cobriam a arca e os seus varais.

[[v14-5-9]]

^<<v14-5-9,9>>^ Então os varais sobressaíram, para que as pontas dos varais da arca se vissem perante o oráculo, mas não se vissem de fora: e esteve ali até ao dia de  hoje.

[[v14-5-10]]

^<<v14-5-10,10>>^ Na arca não havia senão somente  as duas tábuas, que Moisés tinha posto junto a Horebe, quando o Senhor fez concerto com os filhos de Israel saindo eles do Egito.

[[v14-5-11]]

^<<v14-5-11,11>>^ E sucedeu que, saindo os sacerdotes do santuário (porque todos os sacerdotes, que se acharam, se santificaram, sem guardarem as suas turmas.

[[v14-5-12]]

^<<v14-5-12,12>>^ E os levitas, cantores de todos eles, de Asafe, de Hemã, de Jedutum, e seus filhos, e seus irmãos, vestidos de linho fino, com címbalos e com alaúdes e com harpas, estavam em pé para o oriente do altar; e com eles até cento e vinte sacerdotes, que tocavam as trombetas),

[[v14-5-13]]

^<<v14-5-13,13>>^ Eles uniformemente tocavam as trombetas, e cantavam para fazerem ouvir uma só voz, bendizendo e louvando ao Senhor: e, levantando eles a voz com trombetas, e címbalos e outros  instrumentos músicos, e bendizendo ao Senhor, porque era  bom, porque a sua benignidade durava  para sempre, a casa se encheu duma  nuvem, a saber , a casa do Senhor.

[[v14-5-14]]

^<<v14-5-14,14>>^ E não podiam os sacerdotes ter-se em pé, para ministrar, por causa da nuvem, porque a glória do Senhor encheu a casa de Deus.

'''

xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[&#60; Capítulo Anterior] | <<v14-5-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[Próximo Capítulo &#62;]