include::./index.adoc[]

[[v14-24-0]]
=== 2 Crônicas, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-24-1]]

^<<v14-24-1,1>>^ TINHA Joás sete anos de idade quando começou a reinar, e quarenta anos reinou em Jerusalém; e era  o nome de sua mãe Zíbia, de Berseba.

[[v14-24-2]]

^<<v14-24-2,2>>^ E fez Joás o que era  reto aos olhos do Senhor, todos os dias do sacerdote Joiada.

[[v14-24-3]]

^<<v14-24-3,3>>^ E tomou Joiada para ele duas mulheres; e gerou filhos e filhas.

[[v14-24-4]]

^<<v14-24-4,4>>^ E sucedeu depois disto que veio ao coração de Joás renovar a casa do Senhor.

[[v14-24-5]]

^<<v14-24-5,5>>^ Ajuntou pois os sacerdotes e os levitas, e disse-lhes: Saí pelas cidades de Judá, e ajuntai dinheiro de todo o Israel para reparar a casa do vosso Deus de ano em ano; e vós apressai este negócio. Porém os levitas não se apressaram.

[[v14-24-6]]

^<<v14-24-6,6>>^ E o rei chamou a Joiada, o chefe, e disse-lhe: Por que não fizeste inquirição entre os levitas, para que trouxessem de Judá e de Jerusalém a oferta de Moisés, servo do Senhor, e da congregação de Israel, à tenda do testemunho?

[[v14-24-7]]

^<<v14-24-7,7>>^ Porque, sendo Atália ímpia, seus filhos arruinaram a casa de Deus, e até todas as cousas sagradas da casa do Senhor empregaram em Baalim.

[[v14-24-8]]

^<<v14-24-8,8>>^ E deu o rei ordem e fizeram uma arca, e a puseram fora, à porta da casa do Senhor.

[[v14-24-9]]

^<<v14-24-9,9>>^ E publicou-se em Judá e em Jerusalém que trouxessem ao Senhor a oferta que Moisés, o servo do Senhor, havia imposto  a Israel no deserto.

[[v14-24-10]]

^<<v14-24-10,10>>^ Então todos os príncipes, e todo o povo se alegraram, e trouxeram a oferta  e a  lançaram na arca, até que acabaram a obra.

[[v14-24-11]]

^<<v14-24-11,11>>^ E sucedeu que, ao tempo que traziam a arca pelas mãos dos levitas, segundo o mandado do rei, e vendo que já havia  muito dinheiro, vinha o escrivão do rei, e o deputado do sumo sacerdote, e esvaziavam a arca, e a tomavam, e a tornavam ao seu lugar: assim faziam de dia em dia, e ajuntaram dinheiro em abundância.

[[v14-24-12]]

^<<v14-24-12,12>>^ O qual o rei e Joiada davam aos que tinham cargo da obra do serviço da casa do Senhor; e alugaram pedreiros e carpinteiros, para renovarem a casa do Senhor; como também ferreiros e serralheiros, para repararem a casa do Senhor.

[[v14-24-13]]

^<<v14-24-13,13>>^ E os que tinham cargo da obra faziam que a reparação da obra fosse crescendo pela sua mão: e restauraram a casa de Deus no seu estado, e a fortaleceram.

[[v14-24-14]]

^<<v14-24-14,14>>^ E, depois de acabarem, trouxeram o resto do dinheiro para diante do rei e de Joiada, e dele fizeram vasos para a casa do Senhor, vasos para ministrar, e oferecer, e perfumadores e vasos de ouro e de prata. E continuamente sacrificaram holocaustos na casa do Senhor, todos os dias de Joiada.

[[v14-24-15]]

^<<v14-24-15,15>>^ E envelheceu Joiada, e morreu farto de dias: era  da idade de cento e trinta anos quando morreu.

[[v14-24-16]]

^<<v14-24-16,16>>^ E o sepultaram na cidade de Davi com os reis; porque tinha feito bem em Israel, e para com Deus, e a sua casa.

[[v14-24-17]]

^<<v14-24-17,17>>^ Porém depois da morte de Joiada vieram os príncipes de Judá e prostraram-se perante o rei; e o rei os ouviu.

[[v14-24-18]]

^<<v14-24-18,18>>^ E deixaram a casa do Senhor, Deus de seus pais e serviram as imagens do bosque e os ídolos: então veio grande ira sobre Judá e Jerusalém por causa desta sua culpa.

[[v14-24-19]]

^<<v14-24-19,19>>^ Porém enviou profetas entre eles, para os fazer tornar ao Senhor, os quais protestaram contra eles; mas eles não deram ouvidos.

[[v14-24-20]]

^<<v14-24-20,20>>^ E o Espírito de Deus revestiu a Zacarias, filho do sacerdote Joiada, o qual se pôs em pé acima do povo, e lhes disse: Assim diz Deus: por que transgredis os mandamentos do Senhor? portanto não prosperareis; porque deixastes ao Senhor, também ele vos deixará.

[[v14-24-21]]

^<<v14-24-21,21>>^ E eles conspiraram contra ele, e apedrejaram com pedras, por mandado do rei, no pátio da casa do Senhor.

[[v14-24-22]]

^<<v14-24-22,22>>^ Assim o rei Joás não se lembrou da beneficência que seu pai Joiada lhe fizera, porém, matou-lhe o filho, o qual, morrendo, disse: O Senhor o verá, e o requererá.

[[v14-24-23]]

^<<v14-24-23,23>>^ E sucedeu, no decurso de um ano, que o exército da Síria subiu contra ele, e vieram a Judá e a Jerusalém, e destruíram dentre o povo a todos os príncipes do povo; e todo o seu despojo enviaram ao rei de Damasco.

[[v14-24-24]]

^<<v14-24-24,24>>^ Porque, ainda que o exército dos siros viera com poucos homens, contudo o Senhor deu na sua mão um exército de grande multidão, porquanto deixaram ao Senhor, Deus de seus pais. Assim executaram os Juízos contra Joás.

[[v14-24-25]]

^<<v14-24-25,25>>^ E, retirando-se dele (porque em grandes enfermidades o deixaram) seus servos conspiraram contra ele por causa do sangue do filho do sacerdote Joiada, e o mataram na sua cama, e morreu: e o sepultaram na cidade de Davi, porém não o sepultaram nos sepulcros dos reis.

[[v14-24-26]]

^<<v14-24-26,26>>^ Estes pois foram os que conspiraram contra ele: Zabade, filho de Simeate, a amonita, e Jozabade, filho de Sinrete, a moabita.

[[v14-24-27]]

^<<v14-24-27,27>>^ E, quanto a seus filhos, e à grandeza do cargo que se lhe impôs , e ao estabelecimento da casa de Deus, eis que está  escrito na história do livro dos reis. E Amazias, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[&#60; Capítulo Anterior] | <<v14-24-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[Próximo Capítulo &#62;]