include::./index.adoc[]

[[v14-18-0]]
=== 2 Crônicas, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-18-1]]

^<<v14-18-1,1>>^ TINHA pois Josafá riquezas e glória em abundância: e aparentou-se com Acabe.

[[v14-18-2]]

^<<v14-18-2,2>>^ E ao cabo de alguns  anos foi ter com Acabe a Samaria: e Acabe matou ovelhas e bois em abundância, para ele e para o povo que vinha  com ele: e o persuadiu a subir com ele a  Ramote-Gileade.

[[v14-18-3]]

^<<v14-18-3,3>>^ Porque Acabe, rei de Israel, disse a Josafá, rei de Judá: Irás tu comigo a Ramote-Gileade? E ele  lhe disse: Como tu és, serei  eu; e o meu povo, como o teu povo; seremos  contigo nesta guerra.

[[v14-18-4]]

^<<v14-18-4,4>>^ Disse mais Josafá ao rei de Israel: Consulta hoje, peço-te, a palavra do Senhor.

[[v14-18-5]]

^<<v14-18-5,5>>^ Então o rei de Israel ajuntou os profetas, quatrocentos homens, e disse-lhes: Iremos à guerra contra Ramote-Gileade, ou deixá-lo-ei? E eles disseram: Sobe; porque Deus o dará na mão do rei.

[[v14-18-6]]

^<<v14-18-6,6>>^ Disse porém Josafá: Não há  ainda aqui profeta algum do Senhor, para que o consultemos?

[[v14-18-7]]

^<<v14-18-7,7>>^ Então o rei de Israel disse a Josafá: Ainda há  um homem por quem podemos  consultar ao Senhor; porém eu o aborreço, porque nunca profetiza de mim bem, senão sempre mal; este é  Mica, filho de Inlá. E disse Josafá: Não fale o rei assim.

[[v14-18-8]]

^<<v14-18-8,8>>^ Então chamou o rei de Israel um eunuco: e disse: Traze aqui depressa a Mica, filho de Inlá.

[[v14-18-9]]

^<<v14-18-9,9>>^ E o rei de Israel, e Josafá rei de Judá estavam assentados cada um no seu trono, vestidos com as suas vestiduras, e estavam assentados na praça à entrada da porta de Samaria, e todos os profetas profetizavam na sua presença.

[[v14-18-10]]

^<<v14-18-10,10>>^ E Zedequias, filho de Quenaaná, fez para si uns chifres de ferro, e disse: Assim diz o Senhor: Com estes ferirás aos siros, até de todo os consumires.

[[v14-18-11]]

^<<v14-18-11,11>>^ E todos os profetas profetizavam o mesmo dizendo: Sobe a Ramote-Gileade, e prosperarás; porque o Senhor a  dará na mão do rei.

[[v14-18-12]]

^<<v14-18-12,12>>^ E o mensageiro, que foi chamar a Mica, lhe falou, dizendo: Eis que as palavras dos profetas, a uma boca, são  boas para com o rei; seja pois também a tua palavra como a dum deles, e fala o que é  bom.

[[v14-18-13]]

^<<v14-18-13,13>>^ Porém Mica disse: Vive o Senhor, que o que meu Deus me disser, isso falarei.

[[v14-18-14]]

^<<v14-18-14,14>>^ Vindo pois ao rei, o rei lhe disse: Mica, iremos a Ramote-Gileade à guerra, ou deixá-lo-ei? E ele disse: Subi, e prosperareis; e serão dados na vossa mão.

[[v14-18-15]]

^<<v14-18-15,15>>^ E o rei lhe disse: Até quantas vezes te conjurarei, para que me não fales senão a verdade no nome do Senhor?

[[v14-18-16]]

^<<v14-18-16,16>>^ Então disse ele: Vi a todo o Israel disperso pelos montes, como ovelhas que não têm pastor: e disse o Senhor: Estes não têm senhor; torne cada um em paz para sua casa.

[[v14-18-17]]

^<<v14-18-17,17>>^ Então o rei de Israel disse a Josafá: Não te disse eu, que  este não profetizaria de mim bem, porém mal?

[[v14-18-18]]

^<<v14-18-18,18>>^ Disse mais: Pois ouvi a palavra do Senhor: Vi ao Senhor assentado no seu trono, e a todo o exército celestial em pé à sua mão direita, e à sua esquerda.

[[v14-18-19]]

^<<v14-18-19,19>>^ E disse o Senhor: Quem persuadirá a Acabe rei de Israel, a que suba, e caia em Ramote-Gileade? Disse mais: Um diz desta maneira, e outro diz doutra.

[[v14-18-20]]

^<<v14-18-20,20>>^ Então saiu um espírito e se apresentou diante do Senhor, e disse: Eu o persuadirei. E o Senhor lhe disse: Com quê?

[[v14-18-21]]

^<<v14-18-21,21>>^ E ele disse: Eu sairei, e serei um  espírito de mentira na boca de todos os seus profetas. E disse o Senhor : Tu o persuadirás, e também prevalecerás: sai, e faze-o assim.

[[v14-18-22]]

^<<v14-18-22,22>>^ Agora pois, eis que o Senhor pôs um  espírito de mentira na boca destes teus profetas: e o Senhor falou o mal a teu respeito.

[[v14-18-23]]

^<<v14-18-23,23>>^ Então Zedequias, filho de Quenaaná, se chegou, e feriu a Mica no queixo, e disse: Por que caminho passou de mim o Espírito do Senhor para falar a ti?

[[v14-18-24]]

^<<v14-18-24,24>>^ E disse Mica: Eis que o verás naquele dia, quando andares de câmara em câmara, para te esconderes.

[[v14-18-25]]

^<<v14-18-25,25>>^ Então disse o rei de Israel: Tomai a Mica, e tornai a levá-lo a Amom, o governador da cidade, e a Joás filho do rei.

[[v14-18-26]]

^<<v14-18-26,26>>^ E direis: Assim diz o rei: Metei este homem  na casa do cárcere; e sustentai-o com pão de angústia, e com água de angústia até que eu volte em paz.

[[v14-18-27]]

^<<v14-18-27,27>>^ E disse Mica: Se é que tornares em paz, o Senhor não tem falado por mim. Disse mais: Ouvi, povos todos!

[[v14-18-28]]

^<<v14-18-28,28>>^ Subiram pois o rei de Israel e Josafá, rei de Judá, a Ramote-Gileade.

[[v14-18-29]]

^<<v14-18-29,29>>^ E disse o rei de Israel a Josafá: Disfarçando-me eu, então entrarei na peleja; tu porém veste as tuas vestiduras. Disfarçou-se pois o rei de Israel, e entraram na peleja.

[[v14-18-30]]

^<<v14-18-30,30>>^ Deu ordem porém o rei da Síria aos capitães dos carros que tinha, dizendo: Não pelejareis nem contra pequeno, nem contra grande, senão só contra o rei de Israel.

[[v14-18-31]]

^<<v14-18-31,31>>^ Sucedeu pois que, vendo os capitães dos carros a Josafá, disseram: Este é o rei de Israel, e o cercaram para pelejarem; porém Josafá clamou, e o Senhor o ajudou. E Deus os desviou dele.

[[v14-18-32]]

^<<v14-18-32,32>>^ Porque sucedeu que, vendo os capitães dos carros, que não era o rei de Israel, deixaram de segui-lo.

[[v14-18-33]]

^<<v14-18-33,33>>^ Então um  homem armou o arco na sua simplicidade, e feriu o rei de Israel entre as junturas e a couraça. Então disse ao carreteiro: Vira a tua mão, e tira-me do exército, porque estou mui ferido.

[[v14-18-34]]

^<<v14-18-34,34>>^ E naquele dia cresceu a peleja, mas o rei de Israel susteve-se em pé no carro defronte dos siros até à tarde; e morreu ao tempo do pôr do sol.

'''

xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[&#60; Capítulo Anterior] | <<v14-18-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[Próximo Capítulo &#62;]