include::./index.adoc[]

[[v14-35-0]]
=== 2 Crônicas, 35
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-35-1]]

^<<v14-35-1,1>>^ ENTÃO Josias celebrou a páscoa ao Senhor em Jerusalém; e mataram o cordeiro da  páscoa no décimo quarto dia do mês primeiro.

[[v14-35-2]]

^<<v14-35-2,2>>^ E estabeleceu os sacerdotes nos seus cargos, e os animou ao ministério da casa do Senhor.

[[v14-35-3]]

^<<v14-35-3,3>>^ E disse aos levitas que ensinavam a todo o Israel e estavam consagrados ao Senhor: Ponde a arca sagrada na casa que edificou Salomão, filho de Davi, rei de Israel; não tereis  mais esta carga aos ombros; agora servi ao Senhor vosso Deus e ao seu povo Israel.

[[v14-35-4]]

^<<v14-35-4,4>>^ E preparai-vos segundo as casas de vossos pais, segundo as vossas turmas, conforme à prescrição de Davi rei de Israel, e conforme à prescrição de Salomão, seu filho.

[[v14-35-5]]

^<<v14-35-5,5>>^ E estai no santuário segundo as divisões das casas paternas de vossos irmãos, os filhos do povo: e haja para cada um uma porção das casas paternas dos levitas.

[[v14-35-6]]

^<<v14-35-6,6>>^ E imolai a páscoa: e santificai-vos, e preparai-a para vossos irmãos, fazendo conforme à palavra do Senhor, dada  pela mão de Moisés.

[[v14-35-7]]

^<<v14-35-7,7>>^ E ofereceu Josias, aos filhos do povo, cordeiros e cabritos do rebanho, todos para os sacrifícios da páscoa, em número de trinta mil, por todos que ali  se achavam, e de bois três mil; isto era  da fazenda do rei.

[[v14-35-8]]

^<<v14-35-8,8>>^ Também fizeram os seus príncipes ofertas voluntárias ao povo, aos sacerdotes e aos levitas; Hilquias, e Zacarias, e Jeiel, maiorial da casa de Deus, deram aos sacerdotes para os sacrifícios da páscoa duas mil e seiscentas reses de gado miúdo , e trezentos bois.

[[v14-35-9]]

^<<v14-35-9,9>>^ E Conanias, e Semaías, e Natanael, seus irmãos, como também Hasabias, e Jeiel, e Jozabade, maiorais dos levitas, apresentaram aos levitas, para os sacrifícios da páscoa, cinco mil reses de gado miúdo , e quinhentos bois.

[[v14-35-10]]

^<<v14-35-10,10>>^ Assim se preparou o serviço; e puseram-se os sacerdotes nos seus postos, e os levitas nas suas turmas, conforme ao mandado do rei.

[[v14-35-11]]

^<<v14-35-11,11>>^ Então imolaram a páscoa; e os sacerdotes espargiam o sangue  recebido nas suas mãos, e os levitas esfolavam as reses.

[[v14-35-12]]

^<<v14-35-12,12>>^ E puseram de parte os holocaustos para os darem aos filhos do povo, segundo as divisões das casas paternas, para o  oferecerem ao Senhor, como está  escrito no livro de Moisés; e assim fizeram  com os bois.

[[v14-35-13]]

^<<v14-35-13,13>>^ E assaram a páscoa no fogo, segundo o rito: e as ofertas  sagradas cozeram em panelas, e em caldeiras, e em sertãs; e prontamente as  repartiram entre todo o povo.

[[v14-35-14]]

^<<v14-35-14,14>>^ Depois prepararam o que era preciso  para si e para os sacerdotes; porque os sacerdotes, filhos de Aarão, se ocuparam  até à noite com o sacrifício dos holocaustos e da gordura; pelo que os levitas prepararam para si e para os sacerdotes, filhos de Aarão.

[[v14-35-15]]

^<<v14-35-15,15>>^ E os cantores, filhos de Asafe, estavam  no seu posto, segundo o mandado de Davi, e de Asafe, e de Hemã, e de Jedutum, vidente do rei, como também os porteiros a cada porta; não necessitaram de se desviarem do seu ministério; porquanto seus irmãos, os levitas, preparavam o necessário  para eles.

[[v14-35-16]]

^<<v14-35-16,16>>^ Assim se estabeleceu todo o serviço do Senhor naquele dia, para celebrar a páscoa, e sacrificar holocaustos sobre o altar do Senhor, segundo o mandado do rei Josias.

[[v14-35-17]]

^<<v14-35-17,17>>^ E os filhos de Israel que ali  se acharam celebraram a páscoa naquele tempo, e a festa dos pães asmos, durante sete dias.

[[v14-35-18]]

^<<v14-35-18,18>>^ Nunca pois se celebrou tal páscoa em Israel, desde os dias do profeta Samuel; nem nenhuns reis de Israel celebraram tal páscoa como a que celebrou Josias com os sacerdotes, e levitas, e todo o Judá e Israel, que ali  se acharam, e os habitantes de Jerusalém.

[[v14-35-19]]

^<<v14-35-19,19>>^ No ano décimo oitavo do reinado de Josias se celebrou esta páscoa.

[[v14-35-20]]

^<<v14-35-20,20>>^ Depois de tudo isto, havendo Josias já preparado a casa, subiu Neco, rei do Egito, para guerrear contra Carquêmis, junto ao Eufrates: e Josias lhe saiu ao encontro.

[[v14-35-21]]

^<<v14-35-21,21>>^ Então ele lhe mandou mensageiros, dizendo: Que tenho eu que fazer  contigo, rei de Judá? quanto a ti, contra ti não venho hoje, senão contra a casa que me faz guerra; e disse Deus que me apressasse: guarda-te de te opores  a Deus, que é comigo, para que não te destrua.

[[v14-35-22]]

^<<v14-35-22,22>>^ Porém Josias não virou dele o seu rosto, antes se disfarçou, para pelejar com ele; e não deu ouvidos às palavras de Neco, que saíram  da boca de Deus; antes veio pelejar no vale de Megido.

[[v14-35-23]]

^<<v14-35-23,23>>^ E os frecheiros atiraram ao rei Josias: então o rei disse a seus servos: Tirai-me daqui , porque estou gravemente ferido.

[[v14-35-24]]

^<<v14-35-24,24>>^ E seus servos o tiraram do carro, e o levaram no segundo carro que tinha, e o trouxeram a Jerusalém; e morreu, e o sepultaram nos sepulcros de seus pais; e todo o Judá e Jerusalém tomaram luto por Josias.

[[v14-35-25]]

^<<v14-35-25,25>>^ E Jeremias fez uma lamentação sobre Josias; e todos os cantores e cantoras falaram de Josias nas suas lamentações, até ao dia de  hoje; porque as deram por estatuto em Israel; e eis que estão  escritas nas lamentações.

[[v14-35-26]]

^<<v14-35-26,26>>^ Quanto ao mais dos sucessos de Josias, e às suas beneficências, conforme está escrito na lei do Senhor,

[[v14-35-27]]

^<<v14-35-27,27>>^ E aos seus sucessos, tanto os primeiros como os últimos, eis que estão  escritos no livro dos reis de Israel e de Judá.

'''

xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[&#60; Capítulo Anterior] | <<v14-35-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[Próximo Capítulo &#62;]