include::./index.adoc[]

[[v14-30-0]]
=== 2 Crônicas, 30
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-30-1]]

^<<v14-30-1,1>>^ DEPOIS disto Ezequias enviou por todo o Israel e Judá, e escreveu também cartas a Efraim e a Manassés que viessem à casa do Senhor a Jerusalém, para celebrarem a páscoa ao Senhor Deus de Israel.

[[v14-30-2]]

^<<v14-30-2,2>>^ Porque o rei tivera conselho com os seus maiorais, e com toda a congregação em Jerusalém, para celebrarem a páscoa no segundo mês.

[[v14-30-3]]

^<<v14-30-3,3>>^ Porquanto no mesmo tempo não a puderam celebrar, porque se não tinham santificado bastantes sacerdotes, e o povo se não tinha ajuntado em Jerusalém.

[[v14-30-4]]

^<<v14-30-4,4>>^ E foi isto reto aos olhos do rei, e aos olhos de toda a congregação.

[[v14-30-5]]

^<<v14-30-5,5>>^ E ordenaram que se fizesse passar pregão por todo o Israel, desde Berseba até Dã, para que viessem a celebrar a páscoa ao Senhor, Deus de Israel, a Jerusalém; porque muitos a não tinham celebrado como estava escrito.

[[v14-30-6]]

^<<v14-30-6,6>>^ Foram pois os correios com as cartas, da mão do rei e dos seus príncipes, por todo o Israel e Judá, e segundo o mandado do rei, dizendo: Filhos de Israel, convertei-vos ao Senhor, Deus de Abraão, de Isaque e de Israel; para que ele se volte para aqueles de vós que escaparam, e ficaram da mão dos reis da Assíria.

[[v14-30-7]]

^<<v14-30-7,7>>^ E não sejais como vossos pais e como vossos irmãos, que transgrediram contra o Senhor, Deus de seus pais, pelo que os pôs em assolação como o vedes.

[[v14-30-8]]

^<<v14-30-8,8>>^ Não endureçais agora a vossa cerviz, como vossos pais; dai a mão ao Senhor, e vinde ao seu santuário que ele santificou para sempre, e servi ao Senhor vosso Deus, para que o ardor da sua ira se desvie de vós.

[[v14-30-9]]

^<<v14-30-9,9>>^ Porque, em vos convertendo ao Senhor, vossos irmãos e vossos filhos acharão misericórdia perante os que os levaram cativos, e tornarão a esta terra; porque o Senhor vosso Deus é  piedoso e misericordioso, e não desviará de vós o seu  rosto, se vos converterdes a ele.

[[v14-30-10]]

^<<v14-30-10,10>>^ E os correios foram passando de cidade em cidade, pela terra de Efraim e Manassés até Zebulom; porém riram-se e zombaram deles.

[[v14-30-11]]

^<<v14-30-11,11>>^ Todavia alguns de Aser, e de Manassés, e de Zebulom, se humilharam, e vieram a Jerusalém.

[[v14-30-12]]

^<<v14-30-12,12>>^ E em Judá esteve a mão de Deus, dando-lhes um só coração, para fazerem o mandado do rei e dos príncipes, conforme à palavra do Senhor.

[[v14-30-13]]

^<<v14-30-13,13>>^ E ajuntou-se em Jerusalém muito povo, para celebrar a festa dos pães asmos, no segundo mês; uma mui grande congregação.

[[v14-30-14]]

^<<v14-30-14,14>>^ E levantaram-se, e tiraram os altares que havia  em Jerusalém: também tiraram todos os vasos de incenso, e os lançaram no ribeiro de Cedrom.

[[v14-30-15]]

^<<v14-30-15,15>>^ Então sacrificaram a páscoa no dia décimo quarto do segundo mês: e os sacerdotes e levitas se envergonharam e se santificaram e trouxeram holocaustos à casa do Senhor.

[[v14-30-16]]

^<<v14-30-16,16>>^ E puseram-se no seu lugar, segundo o seu costume, conforme a lei de Moisés, o homem de Deus: e os sacerdotes espargiam o sangue, tomando-o  da mão dos levitas.

[[v14-30-17]]

^<<v14-30-17,17>>^ Porque havia  muitos na congregação que se não tinham santificado; pelo que os levitas tinham cargo de matarem os cordeiros da páscoa por todo aquele que não estava  limpo, para o santificarem ao Senhor.

[[v14-30-18]]

^<<v14-30-18,18>>^ Porque uma multidão do povo, muitos de Efraim e Manassés, Issacar e Zebulom, se não tinham purificado, e contudo comeram a páscoa, não como está escrito; porém Ezequias orou por eles, dizendo: O Senhor, que é  bom, faça reconciliação com aquele.

[[v14-30-19]]

^<<v14-30-19,19>>^ Que  tem preparado o seu coração para buscar ao Senhor, Deus, o Deus de seus pais, ainda que não esteja purificado segundo a purificação do santuário.

[[v14-30-20]]

^<<v14-30-20,20>>^ E ouviu o Senhor a Ezequias, e sarou o povo.

[[v14-30-21]]

^<<v14-30-21,21>>^ E os filhos de Israel, que se acharam em Jerusalém, celebraram a festa dos pães asmos sete dias com grande alegria: e os levitas e os sacerdotes louvaram ao Senhor de dia em dia, com instrumentos fortemente retinintes ao Senhor.

[[v14-30-22]]

^<<v14-30-22,22>>^ E Ezequias falou benignamente a todos os levitas, que tinham entendimento no bom conhecimento do Senhor: e comeram as ofertas  da solenidade por sete dias, oferecendo ofertas pacíficas, e louvando ao Senhor, Deus de seus pais.

[[v14-30-23]]

^<<v14-30-23,23>>^ E, tendo toda a congregação conselho para celebrarem outros sete dias, celebraram ainda sete dias com alegria.

[[v14-30-24]]

^<<v14-30-24,24>>^ Porque Ezequias, rei de Judá, apresentou à congregação mil novilhos e sete mil ovelhas; e os príncipes apresentaram à congregação mil novilhos e dez mil ovelhas: e os sacerdotes se santificaram em grande número.

[[v14-30-25]]

^<<v14-30-25,25>>^ E alegraram-se, toda a congregação de Judá, e os sacerdotes, e os levitas, toda a congregação de todos os que vieram de Israel; como também os estrangeiros que vieram da terra de Israel e os que habitavam em Judá.

[[v14-30-26]]

^<<v14-30-26,26>>^ E houve grande alegria em Jerusalém; porque desde os dias de Salomão, filho de Davi, rei de Israel, tal não houve  em Jerusalém.

[[v14-30-27]]

^<<v14-30-27,27>>^ Então os sacerdotes, os levitas, se levantaram e abençoaram o povo; e a sua voz foi ouvida; porque a sua oração chegou até à sua santa habitação, aos céus.

'''

xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[&#60; Capítulo Anterior] | <<v14-30-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[Próximo Capítulo &#62;]