include::./index.adoc[]

[[v14-15-0]]
=== 2 Crônicas, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-15-1]]

^<<v14-15-1,1>>^ ENTÃO veio o Espírito de Deus sobre Azarias, filho de Obede.

[[v14-15-2]]

^<<v14-15-2,2>>^ E saiu ao encontro de Asa, e disse-lhe: Ouvi-me, Asa, e todo o Judá e Benjamim: O Senhor está  convosco, enquanto vós estais com ele, e, se o buscardes, o achareis; porém, se o deixardes, vos deixará.

[[v14-15-3]]

^<<v14-15-3,3>>^ E Israel esteve  por muitos dias sem o verdadeiro Deus, e sem sacerdote que o  ensinasse, e sem lei.

[[v14-15-4]]

^<<v14-15-4,4>>^ Mas quando na sua angústia se convertiam ao Senhor, Deus de Israel, e o buscavam, o achavam.

[[v14-15-5]]

^<<v14-15-5,5>>^ E naqueles tempos não havia  paz nem para o que saía, nem para o que entrava, mas muitas perturbações sobre todos os habitantes daquelas terras.

[[v14-15-6]]

^<<v14-15-6,6>>^ Porque gente contra gente, e cidade contra cidade se despedaçavam; porque Deus os conturbara com toda a angústia.

[[v14-15-7]]

^<<v14-15-7,7>>^ Mas esforçai-vos, e não desfaleçam as vossas mãos; porque a vossa obra tem uma recompensa.

[[v14-15-8]]

^<<v14-15-8,8>>^ Ouvindo pois Asa estas palavras, e a profecia do profeta, filho de  Obede, esforçou-se, e tirou as abominações de toda a terra de Judá e de Benjamim, como também das cidades que tomara nas montanhas de Efraim: e renovou o altar do Senhor, que estava  diante do pórtico do Senhor.

[[v14-15-9]]

^<<v14-15-9,9>>^ E ajuntou a todo o Judá, e Benjamim, e com eles os estrangeiros de Efraim e Manassés, e de Simeão; porque de Israel vinham a ele em grande número, vendo que o Senhor seu Deus era  com ele.

[[v14-15-10]]

^<<v14-15-10,10>>^ E ajuntaram-se em Jerusalém no terceiro mês; no ano décimo do reinado de Asa.

[[v14-15-11]]

^<<v14-15-11,11>>^ E no mesmo dia ofereceram em sacrifício ao Senhor, do despojo que  trouxeram, seiscentos bois e seis mil ovelhas.

[[v14-15-12]]

^<<v14-15-12,12>>^ E entraram no concerto de buscarem o Senhor, Deus de seus pais, com todo o seu coração, e com toda a sua alma;

[[v14-15-13]]

^<<v14-15-13,13>>^ E de que todo aquele que não buscasse ao Senhor, Deus de Israel, morresse, desde o menor até ao maior, e desde o homem até à mulher.

[[v14-15-14]]

^<<v14-15-14,14>>^ E juraram ao Senhor, em alta voz, com júbilo e com trombetas e buzinas.

[[v14-15-15]]

^<<v14-15-15,15>>^ E todo o Judá se alegrou deste juramento; porque com todo o seu coração juraram, e com toda a sua vontade o buscaram, e o acharam: e o Senhor lhes deu repouso em redor.

[[v14-15-16]]

^<<v14-15-16,16>>^ E também a Maaca, mãe do rei Asa, ele  a depôs, para que não fosse  mais rainha; porquanto fizera a Aserá um  horrível ídolo; e Asa destruiu o seu horrível ídolo, e o  despedaçou, e o  queimou junto ao ribeiro de Cedrom.

[[v14-15-17]]

^<<v14-15-17,17>>^ Os altos porém não se tiraram de Israel; contudo o coração de Asa foi perfeito todos os seus dias.

[[v14-15-18]]

^<<v14-15-18,18>>^ E trouxe as cousas que tinha consagrado seu pai, e as cousas que ele mesmo tinha consagrado à casa de Deus: prata, e ouro, e vasos.

[[v14-15-19]]

^<<v14-15-19,19>>^ E não houve guerra até ao ano trigésimo quinto do reinado de Asa.

'''

xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[&#60; Capítulo Anterior] | <<v14-15-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[Próximo Capítulo &#62;]