include::./index.adoc[]

[[v14-4-0]]
=== 2 Crônicas, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-4-1]]

^<<v14-4-1,1>>^ TAMBÉM fez um  altar de metal de vinte côvados de comprimento, e de vinte côvados de largura, e dez côvados de altura.

[[v14-4-2]]

^<<v14-4-2,2>>^ Fez também o mar de fundição, de dez côvados duma borda até à outra, redondo, e de cinco côvados de alto; cingia-o em roda um cordão de trinta côvados.

[[v14-4-3]]

^<<v14-4-3,3>>^ E por baixo dele havia  figuras de bois, que ao redor o cingiam, e por dez côvados cercavam aquele mar ao redor: e tinha  duas carreiras de bois, fundidos na sua fundição.

[[v14-4-4]]

^<<v14-4-4,4>>^ E estava sobre doze bois; três que olhavam para o norte, e três que olhavam para o ocidente, e três que olhavam para o sul, e três que olhavam para o oriente; e o mar estava  posto sobre eles: e as suas partes posteriores estavam para a banda de dentro.

[[v14-4-5]]

^<<v14-4-5,5>>^ E tinha  um palmo de grossura, e a sua borda foi feita como a borda dum copo, ou como  uma flor-de-lis, da capacidade de três mil batos.

[[v14-4-6]]

^<<v14-4-6,6>>^ Também fez dez pias; e pôs cinco à direita, e cinco à esquerda, para lavarem nelas; o que pertencia ao holocausto o lavavam nelas: porém o mar era  para que os sacerdotes se lavassem nele.

[[v14-4-7]]

^<<v14-4-7,7>>^ Fez também dez castiçais de ouro, segundo a sua forma, e pô-los no templo, cinco à direita, e cinco à esquerda.

[[v14-4-8]]

^<<v14-4-8,8>>^ Também fez dez mesas, e pô-las no templo, cinco à direita, e cinco à esquerda; também fez cem bacias de ouro.

[[v14-4-9]]

^<<v14-4-9,9>>^ Fez mais o pátio dos sacerdotes, e o pátio grande: como também as portadas para o pátio, e as suas portas cobriu de cobre.

[[v14-4-10]]

^<<v14-4-10,10>>^ E o mar pôs ao lado direito, para a banda do oriente, para o sul.

[[v14-4-11]]

^<<v14-4-11,11>>^ Também Hirão fez as caldeiras, e as pás, e as bacias: assim acabou Hirão de fazer a obra, que fazia para o rei Salomão, na casa de Deus:

[[v14-4-12]]

^<<v14-4-12,12>>^ As duas colunas, e os globos, e os dois capitéis sobre as cabeças das colunas: e as duas redes, para cobrir os dois globos dos capitéis, que estavam  sobre a cabeça das colunas.

[[v14-4-13]]

^<<v14-4-13,13>>^ E as quatrocentas romãs para as duas redes: duas carreiras de romãs para cada rede, para cobrirem os dois globos dos capitéis que estavam  em cima das colunas.

[[v14-4-14]]

^<<v14-4-14,14>>^ Também fez as bases: e as pias pôs sobre as bases;

[[v14-4-15]]

^<<v14-4-15,15>>^ Um mar, e os doze bois, debaixo dele;

[[v14-4-16]]

^<<v14-4-16,16>>^ Semelhantemente os potes, e as pás, e os garfos, e todos os seus vasos, fez Hirão Abiú ao rei Salomão, para a casa do Senhor, de cobre purificado.

[[v14-4-17]]

^<<v14-4-17,17>>^ Na campina do Jordão os fundiu o rei na terra argilosa, entre Sucote e Zeredata.

[[v14-4-18]]

^<<v14-4-18,18>>^ E fez Salomão todos estes vasos em grande abundância, porque o peso do cobre se não esquadrinhava.

[[v14-4-19]]

^<<v14-4-19,19>>^ Fez também Salomão todos os vasos que eram  para a casa de Deus, como também o altar de ouro, e as mesas, sobre as quais estavam  os pães da proposição.

[[v14-4-20]]

^<<v14-4-20,20>>^ E os castiçais com as suas lâmpadas de ouro finíssimo, para as acenderem segundo o costume, perante o oráculo.

[[v14-4-21]]

^<<v14-4-21,21>>^ E as flores, e as lâmpadas, e os espevitadores eram  de ouro, do mais perfeito ouro.

[[v14-4-22]]

^<<v14-4-22,22>>^ Como também os garfos, e as bacias, e as taças, e os incensários, de ouro finíssimo: e quanto à entrada da casa, as suas portas de dentro da santidade das santidades, e as portas da casa do templo, eram  de ouro.

'''

xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[Próximo Capítulo &#62;]