include::./index.adoc[]

[[v14-17-0]]
=== 2 Crônicas, 17
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-17-1]]

^<<v14-17-1,1>>^ E JOSAFÁ seu filho reinou em seu lugar: e fortificou-se contra Israel.

[[v14-17-2]]

^<<v14-17-2,2>>^ E pôs gente de guerra em todas as cidades fortes de Judá e pôs guarnições na terra de Judá, como também nas cidades de Efraim, que Asa seu pai tinha tomado.

[[v14-17-3]]

^<<v14-17-3,3>>^ E o Senhor foi com Josafá; porque andou nos primeiros caminhos de Davi, seu pai, e não buscou a Baalim.

[[v14-17-4]]

^<<v14-17-4,4>>^ Antes buscou ao Deus de seu pai, e andou nos seus mandamentos, e não segundo as obras de Israel.

[[v14-17-5]]

^<<v14-17-5,5>>^ E o Senhor confirmou o reino na sua mão, e todo o Judá deu presentes a Josafá: e teve riquezas e glória em abundância.

[[v14-17-6]]

^<<v14-17-6,6>>^ E exaltou-se o seu coração nos caminhos do Senhor e ainda de mais tirou os altos e os bosques de Judá.

[[v14-17-7]]

^<<v14-17-7,7>>^ E no terceiro ano do seu reinado enviou ele os seus príncipes, a Bencail, e a Obadias, e a Zacarias, e a Natanael, e a Micaia, para ensinarem nas cidades de Judá.

[[v14-17-8]]

^<<v14-17-8,8>>^ E com eles os levitas, Semaías e Netanias, e Zebadias, e Asael, e Semiramote, e Jônatas, e Adonias, e Tobias, e Tobadonias, levitas: e com eles os sacerdotes, Elisama e Jorão.

[[v14-17-9]]

^<<v14-17-9,9>>^ E ensinaram em Judá e tinham consigo o livro da lei do Senhor: e rodearam todas as cidades de Judá, e ensinaram entre o povo.

[[v14-17-10]]

^<<v14-17-10,10>>^ E veio o temor do Senhor sobre todos os reinos das terras, que estavam  em roda de Judá, e não guerrearam contra Josafá.

[[v14-17-11]]

^<<v14-17-11,11>>^ E alguns  dentre os filisteus traziam presentes a Josafá, com o dinheiro do tributo: também os arábios lhe trouxeram gado miúdo; sete mil e setecentos carneiros e sete mil e setecentos bodes.

[[v14-17-12]]

^<<v14-17-12,12>>^ Cresceu pois Josafá e se engrandeceu extremamente: e edificou fortalezas e cidades de munições em Judá.

[[v14-17-13]]

^<<v14-17-13,13>>^ E teve muitas obras nas cidades de Judá, e gente de guerra, varões valentes em Jerusalém.

[[v14-17-14]]

^<<v14-17-14,14>>^ E este é  o número deles segundo as casas de seus pais: Em Judá eram  chefes dos milhares: o chefe Adna, e com ele trezentos mil varões valentes;

[[v14-17-15]]

^<<v14-17-15,15>>^ E  após ele o chefe Joanã, e com ele duzentos e oitenta mil;

[[v14-17-16]]

^<<v14-17-16,16>>^ E após ele Amazias, filho de Zicri, que voluntariamente se entregou ao Senhor, e com ele duzentos mil varões valentes.

[[v14-17-17]]

^<<v14-17-17,17>>^ E de Benjamim, Eliada, varão valente, e com ele duzentos mil, armados de arco e de escudo:

[[v14-17-18]]

^<<v14-17-18,18>>^ E após ele Jozabade: e com ele cento e oitenta mil armados para a guerra.

[[v14-17-19]]

^<<v14-17-19,19>>^ Estes estavam no serviço do rei; afora os que o rei tinha posto nas cidades fortes por todo o Judá.

'''

xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[&#60; Capítulo Anterior] | <<v14-17-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[Próximo Capítulo &#62;]