include::./index.adoc[]

[[v14-14-0]]
=== 2 Crônicas, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-14-1]]

^<<v14-14-1,1>>^ E ABIAS dormiu com seus pais e o sepultaram na cidade de Davi; e Asa, seu filho, reinou em seu lugar: nos seus dias esteve a terra em paz dez anos.

[[v14-14-2]]

^<<v14-14-2,2>>^ E Asa fez o que era  bom e reto aos olhos do Senhor seu Deus.

[[v14-14-3]]

^<<v14-14-3,3>>^ Porque tirou os altares dos deuses  estranhos, e os altos: e quebrou as estátuas, e cortou os bosques.

[[v14-14-4]]

^<<v14-14-4,4>>^ E mandou a Judá que buscassem ao Senhor Deus de seus pais, e que observassem a lei e o mandamento.

[[v14-14-5]]

^<<v14-14-5,5>>^ Também tirou de todas as cidades de Judá os altos e as imagens do sol: e o reino esteve quieto diante dele.

[[v14-14-6]]

^<<v14-14-6,6>>^ E edificou cidades fortes em Judá: porque a terra estava quieta, e não havia guerra contra ele naqueles anos; porquanto o Senhor lhe dera repouso.

[[v14-14-7]]

^<<v14-14-7,7>>^ Disse pois a Judá: Edifiquemos estas cidades, e cerquemo-las de muros e torres, portas e ferrolhos, enquanto  a terra ainda está quieta  diante de nós, pois buscamos ao Senhor nosso Deus; buscamo-lo, e deu-nos repouso em redor. Edificaram, pois, e prosperaram.

[[v14-14-8]]

^<<v14-14-8,8>>^ Tinha pois Asa um  exército de trezentos mil de Judá, que traziam pavês e lança; e duzentos e oitenta mil de Benjamim, que traziam escudo e atiravam de arco: todos estes eram  varões valentes.

[[v14-14-9]]

^<<v14-14-9,9>>^ E Zerá, o etíope, saiu contra eles, com um  exército de mil milhares, e trezentos carros, e chegou até Maresa.

[[v14-14-10]]

^<<v14-14-10,10>>^ Então Asa saiu contra ele: e ordenaram a batalha no vale de Zefatá, junto a Maresa.

[[v14-14-11]]

^<<v14-14-11,11>>^ E Asa clamou ao Senhor seu Deus, e disse: Senhor, nada para ti é  ajudar, quer o poderoso quer o de nenhuma força; ajuda-nos, pois , Senhor nosso Deus, porque em ti confiamos, e no teu nome viemos contra esta multidão: Senhor, tu és  nosso Deus, não prevaleça contra ti o homem.

[[v14-14-12]]

^<<v14-14-12,12>>^ E o Senhor feriu os etíopes diante de Asa e diante de Judá: e fugiram os etíopes.

[[v14-14-13]]

^<<v14-14-13,13>>^ E Asa e o povo que estava  com ele os perseguiram até Gerar, e caíram tantos  dos etíopes, que já não havia neles vigor algum ; porque foram quebrantados diante do Senhor, e diante do seu exército: e levaram dali  mui grande despojo.

[[v14-14-14]]

^<<v14-14-14,14>>^ E feriram todas as cidades nos arredores de Gerar; porque o terror do Senhor estava sobre eles: e saquearam todas as cidades, porque havia nelas muita presa.

[[v14-14-15]]

^<<v14-14-15,15>>^ Também feriram as malhadas do gado; e levaram ovelhas em abundância, e camelos, e voltaram para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[&#60; Capítulo Anterior] | <<v14-14-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[Próximo Capítulo &#62;]