include::./index.adoc[]

[[v14-13-0]]
=== 2 Crônicas, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-13-1]]

^<<v14-13-1,1>>^ NO ano décimo oitavo do rei Jeroboão reinou Abias sobre Israel.

[[v14-13-2]]

^<<v14-13-2,2>>^ Três anos reinou em Jerusalém; e era  o nome de sua mãe Micaia, filha de Uriel de Gibeá: e houve guerra entre Abias e Jeroboão.

[[v14-13-3]]

^<<v14-13-3,3>>^ E Abias ordenou a peleja, com um exército de varões belicosos, de  quatrocentos mil homens escolhidos: Jeroboão dispôs contra ele a batalha com oitocentos mil homens escolhidos, todos  varões valentes.

[[v14-13-4]]

^<<v14-13-4,4>>^ E pôs-se Abias em pé em cima do monte de Zemaraim, que está  nas montanhas de Efraim, e disse: Ouvi-me, Jeroboão e todo o Israel:

[[v14-13-5]]

^<<v14-13-5,5>>^ Porventura  não vos convém saber que o Senhor Deus de Israel deu para sempre a Davi a soberania sobre Israel, a ele e a seus filhos, por um  concerto de sal?

[[v14-13-6]]

^<<v14-13-6,6>>^ Contudo levantou-se Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, e se rebelou contra seu senhor,

[[v14-13-7]]

^<<v14-13-7,7>>^ E ajuntaram-se a ele homens vadios, filhos de Belial; e fortificaram-se contra Roboão, filho de Salomão, sendo Roboão ainda  mancebo, e terno de coração, e não podia resistir-lhes.

[[v14-13-8]]

^<<v14-13-8,8>>^ E agora cuidais de esforçar-vos contra o reino do Senhor, que está  na mão dos filhos de Davi: bem sois  vós uma  grande multidão, e tendes  convosco os bezerros de ouro que Jeroboão vos fez para deuses.

[[v14-13-9]]

^<<v14-13-9,9>>^ Não lançastes vós fora os sacerdotes do Senhor, os filhos de Aarão, e os levitas, e não fizestes para vós sacerdotes, como as gentes das outras  terras? Qualquer que vem a consagrar-se com um  novilho e sete carneiros logo se faz sacerdote daqueles que não são deuses.

[[v14-13-10]]

^<<v14-13-10,10>>^ Porém, quanto a nós, o Senhor é nosso Deus, e nunca o deixamos: e os sacerdotes, que ministram ao Senhor são  filhos de Aarão, e os levitas se ocupam  na sua  obra.

[[v14-13-11]]

^<<v14-13-11,11>>^ E queimam ao Senhor cada manhã e cada tarde holocaustos, incenso aromático, dispondo os pães da proposição sobre a mesa pura, e o castiçal de ouro e as suas lâmpadas para se acenderem cada tarde, porque nós temos cuidado do serviço do Senhor nosso Deus; porém vós o deixastes.

[[v14-13-12]]

^<<v14-13-12,12>>^ E eis que Deus está conosco, na frente, como também os seus sacerdotes, tocando com as trombetas, para dar alarme contra vós, ó filhos de Israel; não pelejeis contra o Senhor Deus de vossos pais; porque não prosperareis.

[[v14-13-13]]

^<<v14-13-13,13>>^ Mas Jeroboão fez uma emboscada em volta, para darem sobre eles por detrás; de maneira que estavam em frente de Judá e a emboscada por detrás deles.

[[v14-13-14]]

^<<v14-13-14,14>>^ Então Judá olhou, e eis que tinham  de pelejar por diante e por detrás: então clamaram ao Senhor; e os sacerdotes tocaram as trombetas.

[[v14-13-15]]

^<<v14-13-15,15>>^ E os homens de Judá gritaram: e sucedeu que, gritando os homens de Judá, Deus feriu a Jeroboão e a todo o Israel diante de Abias e de Judá.

[[v14-13-16]]

^<<v14-13-16,16>>^ E os filhos de Israel fugiram de diante de Judá; e Deus os entregou na sua mão.

[[v14-13-17]]

^<<v14-13-17,17>>^ De maneira que Abias e o seu povo fizeram grande estrago entre eles; porque caíram feridos de Israel quinhentos mil homens escolhidos.

[[v14-13-18]]

^<<v14-13-18,18>>^ E foram abatidos os filhos de Israel naquele tempo; e os filhos de Judá prevaleceram, porque confiaram no Senhor Deus de seus pais.

[[v14-13-19]]

^<<v14-13-19,19>>^ E Abias seguiu após Jeroboão; e tomou a Betel com os lugares da sua jurisdição, e a Jesana com os lugares da sua jurisdição, e a Efrom com os lugares da sua jurisdição.

[[v14-13-20]]

^<<v14-13-20,20>>^ E Jeroboão não recobrou mais nenhuma força nos dias de Abias: porém o Senhor o feriu, e morreu.

[[v14-13-21]]

^<<v14-13-21,21>>^ Abias pois se fortificou, e tomou para si catorze mulheres, e gerou vinte e dois filhos e dezesseis filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ Os mais sucessos pois de Abias, tanto os seus caminhos como as suas palavras, estão  escritos na história do profeta Ido.

'''

xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]