include::./index.adoc[]

[[v14-1-0]]
=== 2 Crônicas, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-1-1]]

^<<v14-1-1,1>>^ E SALOMÃO, filho de Davi, se esforçou no seu reino; e o Senhor seu Deus era  com ele, e o magnificou grandemente.

[[v14-1-2]]

^<<v14-1-2,2>>^ E falou Salomão a todo o Israel, aos capitães dos milhares e das centenas, e aos juízes, e a todos os príncipes em todo o Israel, chefes dos pais.

[[v14-1-3]]

^<<v14-1-3,3>>^ E foram Salomão e toda a congregação com ele ao alto que estava  em Gibeom; porque ali estava a tenda da congregação de Deus, que Moisés, servo do Senhor, tinha feito no deserto.

[[v14-1-4]]

^<<v14-1-4,4>>^ Mas Davi tinha feito subir a arca de Deus de Quiriate-Jearim ao lugar que  Davi lhe tinha preparado; porque lhe tinha armado uma  tenda em Jerusalém.

[[v14-1-5]]

^<<v14-1-5,5>>^ Também o altar de cobre que tinha feito Bazaleel, filho de Uri, filho de Hur, estava  ali diante do tabernáculo do Senhor: e Salomão e a congregação o visitavam.

[[v14-1-6]]

^<<v14-1-6,6>>^ E Salomão ofereceu ali sacrifícios perante o Senhor, sobre o altar de cobre que estava  na tenda da congregação, e ofereceu sobre ele mil holocaustos.

[[v14-1-7]]

^<<v14-1-7,7>>^ Naquela mesma noite Deus apareceu a Salomão, e disse-lhe: Pede o que quiseres que eu te dê.

[[v14-1-8]]

^<<v14-1-8,8>>^ E Salomão disse a Deus: Tu usaste de grande beneficência com meu pai Davi: e a mim me fizeste rei em seu lugar.

[[v14-1-9]]

^<<v14-1-9,9>>^ Agora pois, ó Senhor Deus, confirme-se a tua palavra, dada a meu pai Davi; porque tu me fizeste rei sobre um  povo numeroso como o pó da terra.

[[v14-1-10]]

^<<v14-1-10,10>>^ Dá-me pois agora sabedoria e conhecimento, para que possa sair e entrar perante este povo; porque quem poderia julgar a este teu tão grande povo?

[[v14-1-11]]

^<<v14-1-11,11>>^ Então Deus disse a Salomão: Porquanto houve isto no teu coração, e não pediste riquezas, fazenda, ou honra, nem a morte dos que te aborrecem, nem tão pouco pediste muitos dias de vida, mas pediste para ti sabedoria e conhecimento, para poderes julgar a meu povo, sobre o qual te pus rei,

[[v14-1-12]]

^<<v14-1-12,12>>^ Sabedoria e conhecimento te são dados: e te darei riquezas, e fazenda, e honra, qual nenhum rei antes de ti teve: e depois de ti tal não haverá.

[[v14-1-13]]

^<<v14-1-13,13>>^ Assim Salomão veio a Jerusalém, do alto que está  em Gibeom, de diante da tenda da congregação: e reinou sobre Israel.

[[v14-1-14]]

^<<v14-1-14,14>>^ E Salomão ajuntou carros e cavaleiros, e teve mil e quatrocentos carros, e doze mil cavaleiros: e pô-los nas cidades dos carros, e junto ao rei em Jerusalém.

[[v14-1-15]]

^<<v14-1-15,15>>^ E fez o rei que houvesse ouro e prata em Jerusalém como pedras: e cedros em tanta abundância como figueiras bravas que há pelas campinas.

[[v14-1-16]]

^<<v14-1-16,16>>^ E os cavalos, que tinha Salomão, se traziam do Egito, e, quanto ao fio de linho os mercadores do rei tomavam o fio de linho por um certo  preço.

[[v14-1-17]]

^<<v14-1-17,17>>^ E faziam subir e sair do Egito cada carro por seiscentos siclos  de prata, e cada cavalo por cento e cinquenta: e assim por meio deles tiravam cavalos  para todos os reis dos heteus, e para os reis da Síria.

'''

xref:013-1-cronicas/013-1-cronicas-029.adoc#v13-29-0[&#60; Capítulo Anterior] | <<v14-1-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-002.adoc#v14-2-0[Próximo Capítulo &#62;]