include::./index.adoc[]

[[v14-28-0]]
=== 2 Crônicas, 28
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v14-28-1]]

^<<v14-28-1,1>>^ TINHA Acaz vinte anos de idade quando começou a reinar, e dezesseis anos reinou em Jerusalém; e não fez o que era  reto aos olhos do Senhor, como Davi seu pai.

[[v14-28-2]]

^<<v14-28-2,2>>^ Antes andou nos caminhos dos reis de Israel, e, demais disto, fez imagens fundidas a Baalim.

[[v14-28-3]]

^<<v14-28-3,3>>^ Também queimou incenso no vale do filho de Hinom, e queimou a seus filhos no fogo, conforme às abominações dos gentios que o Senhor tinha desterrado de diante dos filhos de Israel.

[[v14-28-4]]

^<<v14-28-4,4>>^ Também sacrificou, e queimou incenso nos altos e nos outeiros, como também debaixo de toda a árvore verde.

[[v14-28-5]]

^<<v14-28-5,5>>^ Pelo que o Senhor seu Deus o entregou na mão do rei dos siros, os quais o feriram, e levaram dele em cativeiro uma grande multidão de presos, que trouxeram a Damasco: também foi entregue na mão do rei de Israel, o qual o feriu de grande ferida.

[[v14-28-6]]

^<<v14-28-6,6>>^ Porque Peca, filho de Remalias, matou num dia em Judá cento e vinte mil, todos homens belicosos; porquanto deixaram ao Senhor, Deus de seus pais.

[[v14-28-7]]

^<<v14-28-7,7>>^ E Zicri, varão potente de Efraim, matou a Maaseias, filho do rei, e a Azricão, o mordomo, e a Elcana, o segundo depois do rei.

[[v14-28-8]]

^<<v14-28-8,8>>^ E os filhos de Israel levaram presos de seus irmãos duzentos mil, mulheres, filhos e filhas; e saquearam também deles grande despojo, e trouxeram o despojo para Samaria.

[[v14-28-9]]

^<<v14-28-9,9>>^ E estava ali um profeta do Senhor, cujo nome era  Obede, o qual saiu ao encontro do exército que vinha para Samaria, e lhe disse: Eis que, irando-se o Senhor Deus de vossos pais contra Judá, os entregou na vossa mão, e vós os matastes com uma  raiva tal, que  chegou até aos céus.

[[v14-28-10]]

^<<v14-28-10,10>>^ E agora vós cuidais em sujeitar a vós os filhos de Judá e Jerusalém, como cativos e cativas; porventura  não sois  vós mesmos aqueles  entre os quais há culpas contra o Senhor vosso Deus?

[[v14-28-11]]

^<<v14-28-11,11>>^ Agora pois ouvi-me, e tornai a enviar os prisioneiros que trouxestes presos de vossos irmãos; porque o ardor da ira do Senhor está sobre vós.

[[v14-28-12]]

^<<v14-28-12,12>>^ Então se levantaram alguns homens dentre os chefes dos filhos de Efraim: Azarias, filho de Joanã, Berequias, filho de Mesilemote, e Jezquias, filho de Salum, e Amasa, filho de Hadlai, contra os que voltavam da batalha.

[[v14-28-13]]

^<<v14-28-13,13>>^ E lhes disseram: Não fareis entrar aqui estes presos, porque, em relação à nossa culpa contra o Senhor, vós intentais acrescentar mais  a nossos pecados e a nossas culpas, sendo que já temos tanta culpa, e já o ardor da ira está  sobre Israel.

[[v14-28-14]]

^<<v14-28-14,14>>^ Então os homens  armados deixaram os presos e o despojo diante dos maiorais e de toda a congregação.

[[v14-28-15]]

^<<v14-28-15,15>>^ E os homens que foram apontados por seus  nomes se levantaram, e tomaram os presos, e vestiram do despojo a todos os que dentre eles estavam nus: e os vestiram, e os calçaram, e lhes deram de comer e de beber, e os ungiram; e a todos os que estavam fracos levaram, sobre jumentos, e os trouxeram a Jericó, à cidade das palmeiras, a seus irmãos: depois voltaram para Samaria.

[[v14-28-16]]

^<<v14-28-16,16>>^ Naquele tempo o rei Acaz enviou aos reis da Assíria, a pedir  que o ajudassem.

[[v14-28-17]]

^<<v14-28-17,17>>^ De mais disto também os idumeus vieram, e feriram a Judá, e levaram presos em cativeiro.

[[v14-28-18]]

^<<v14-28-18,18>>^ Também os filisteus deram sobre as cidades da campina e do sul de Judá, e tomaram a Bete-Semes, e Aijalom, e a Gederote e a Socó, e os lugares da sua jurisdição, e a Timná, e os lugares da sua jurisdição, e a Ginzo, e os lugares da sua jurisdição: e habitaram ali.

[[v14-28-19]]

^<<v14-28-19,19>>^ Porque o Senhor humilhou a Judá por causa de Acaz, rei de Israel; porque desviara a Judá, que de todo se dera a prevaricar contra o Senhor.

[[v14-28-20]]

^<<v14-28-20,20>>^ E veio a ele Tilgate-Pilneser, rei da Assíria; porém o pôs em aperto, e não o fortaleceu isso.

[[v14-28-21]]

^<<v14-28-21,21>>^ Porque Acaz tomou uma  porção da casa do Senhor, e da casa do rei, e dos príncipes, e a  deu ao rei da Assíria; porém não o ajudou.

[[v14-28-22]]

^<<v14-28-22,22>>^ E ao tempo em que este o apertou, então ainda mais transgrediu contra o Senhor, tal era o rei Acaz.

[[v14-28-23]]

^<<v14-28-23,23>>^ Porque sacrificou aos deuses de Damasco, que o feriram, e disse: Visto que os deuses dos reis da Síria os ajudam, eu lhes sacrificarei, para que me ajudem a mim. Porém eles foram a sua ruína, e de todo o Israel.

[[v14-28-24]]

^<<v14-28-24,24>>^ E ajuntou Acaz os vasos da casa do Senhor, e fez em pedaços os vasos da casa de Deus, e fechou as portas da casa do Senhor, e fez para si altares em todos os cantos de Jerusalém.

[[v14-28-25]]

^<<v14-28-25,25>>^ Também em cada cidade de Judá fez altos para queimar incenso a outros deuses: assim provocou à ira o Senhor, Deus de seus pais.

[[v14-28-26]]

^<<v14-28-26,26>>^ O resto pois de seus sucessos e de todos os seus caminhos, tanto os primeiros como os derradeiros, eis que está  escrito no livro dos reis de Judá e de Israel.

[[v14-28-27]]

^<<v14-28-27,27>>^ E dormiu Acaz com seus pais, e o sepultaram na cidade, em Jerusalém, porém não o puseram nos sepulcros dos reis de Israel: e Ezequias, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[Próximo Capítulo &#62;]