include::./index.adoc[]

[[v2-5-0]]
=== Êxodo, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-5-1]]

^<<v2-5-1,1>>^ E DEPOIS foram Moisés e Aarão, e disseram a Faraó: Assim diz o Senhor Deus de Israel: Deixa ir o meu povo, para que me celebre uma festa no deserto.

[[v2-5-2]]

^<<v2-5-2,2>>^ Mas Faraó disse: Quem é  o Senhor, cuja voz eu ouvirei, para deixar ir Israel? Não conheço o Senhor, nem tão pouco deixarei ir Israel.

[[v2-5-3]]

^<<v2-5-3,3>>^ E eles disseram: O Deus dos hebreus nos encontrou; portanto deixa-nos agora ir caminho de três dias ao deserto, para que ofereçamos sacrifícios ao Senhor e ele não venha sobre nós com pestilência ou com espada.

[[v2-5-4]]

^<<v2-5-4,4>>^ Então disse-lhes o rei do Egito: Moisés e Aarão, por que fazeis cessar o povo das suas obras? ide a vossas cargas.

[[v2-5-5]]

^<<v2-5-5,5>>^ E disse também Faraó: Eis que o povo da terra já é  muito, e vós os fazeis abandonar as suas cargas.

[[v2-5-6]]

^<<v2-5-6,6>>^ Portanto deu ordem Faraó naquele mesmo dia aos exatores do povo, e aos seus oficiais, dizendo:

[[v2-5-7]]

^<<v2-5-7,7>>^ Daqui em diante não torneis a dar palha ao povo, para fazer, tijolos, como fizestes  ontem e anteontem; vão eles mesmos, e colham palha para si.

[[v2-5-8]]

^<<v2-5-8,8>>^ E lhes imporeis a conta dos tijolos que fizeram ontem, e anteontem; nada diminuireis dela, porque eles estão ociosos; por isso clamam, dizendo: Vamos, sacrifiquemos ao nosso Deus.

[[v2-5-9]]

^<<v2-5-9,9>>^ Agrave-se o serviço sobre estes homens, para que se ocupem nele, e não confiem em palavras de mentira.

[[v2-5-10]]

^<<v2-5-10,10>>^ Então saíram os exatores do povo, e seus oficiais, e falaram ao povo, dizendo: Assim diz Faraó: Eu não vos darei palha;

[[v2-5-11]]

^<<v2-5-11,11>>^ Ide vós mesmos, e tomai vós palha donde a achardes; porque nada se diminuirá de vosso serviço.

[[v2-5-12]]

^<<v2-5-12,12>>^ Então o povo se espalhou por toda a terra do Egito, a colher restolho em lugar de palha.

[[v2-5-13]]

^<<v2-5-13,13>>^ E os exatores os apertavam, dizendo: Acabei vossa obra, a tarefa de cada  dia, como quando havia palha.

[[v2-5-14]]

^<<v2-5-14,14>>^ E foram açoitados os oficiais dos filhos de Israel, que os exatores de Faraó tinham posto sobre eles, dizendo estes : Por que não acabastes vossa tarefa ontem e hoje, fazendo tijolos como antes?

[[v2-5-15]]

^<<v2-5-15,15>>^ Pelo que foram-se os oficiais dos filhos de Israel, e clamaram a Faraó, dizendo: Por que fazes assim a teus servos?

[[v2-5-16]]

^<<v2-5-16,16>>^ Palha não se dá a teus servos, e nos dizem: Fazei tijolos; e eis que teus servos são açoitados; porém o teu povo tem a culpa.

[[v2-5-17]]

^<<v2-5-17,17>>^ Mas ele disse: Vós sois ociosos; vós sois ociosos; por isso dizeis: Vamos, sacrifiquemos ao Senhor.

[[v2-5-18]]

^<<v2-5-18,18>>^ Ide pois agora, trabalhai; palha porém não se vos dará; contudo, dareis a conta dos tijolos.

[[v2-5-19]]

^<<v2-5-19,19>>^ Então os oficiais dos filhos de Israel viram-se em aflição, porquanto se dizia: Nada diminuireis de vossos tijolos, da  tarefa do dia no seu dia.

[[v2-5-20]]

^<<v2-5-20,20>>^ E encontraram a Moisés e a Aarão, que estavam defronte deles, quando saíram de Faraó.

[[v2-5-21]]

^<<v2-5-21,21>>^ E disseram-lhes: O Senhor atente sobre vós, e julgue isso , porquanto fizestes o nosso cheiro repelente diante de Faraó, e diante de seus servos, dando-lhes a espada nas mãos, para nos matar.

[[v2-5-22]]

^<<v2-5-22,22>>^ Então tornou Moisés ao Senhor, e disse: Senhor! por que fizeste mal a este povo? por que me enviaste?

[[v2-5-23]]

^<<v2-5-23,23>>^ Porque desde que entrei a Faraó, para falar em teu nome, ele maltratou a este povo; e de nenhuma sorte livraste o teu povo.

'''

xref:002-exodo/002-exodo-004.adoc#v2-4-0[&#60; Capítulo Anterior] | <<v2-5-0,Topo>> | xref:002-exodo/002-exodo-006.adoc#v2-6-0[Próximo Capítulo &#62;]