include::./index.adoc[]

[[v2-29-0]]
=== Êxodo, 29
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-29-1]]

^<<v2-29-1,1>>^ ISTO é  o que lhes hás de fazer, para os santificar, para que me administrem o sacerdócio: Toma um novilho, e dois carneiros sem mácula.

[[v2-29-2]]

^<<v2-29-2,2>>^ E pão asmo, e bolos asmos, amassados com azeite, e coscorões asmos, untados com azeite: com flor de farinha de trigo os farás.

[[v2-29-3]]

^<<v2-29-3,3>>^ E os porás num cesto, e os trarás no cesto, com o novilho e os dois carneiros.

[[v2-29-4]]

^<<v2-29-4,4>>^ Então farás chegar Aarão e seus filhos à porta da tenda da congregação, e os lavarás com água;

[[v2-29-5]]

^<<v2-29-5,5>>^ Depois tomarás os vestidos, e vestirás a Aarão da túnica e do manto do éfode, e do éfode mesmo , e do peitoral: e o cingirás com o cinto de obra de artífice do éfode.

[[v2-29-6]]

^<<v2-29-6,6>>^ E a mitra porás sobre a sua cabeça: a coroa da santidade porás sobre a mitra;

[[v2-29-7]]

^<<v2-29-7,7>>^ E tomarás o azeite da unção; e o derramarás sobre a sua cabeça: assim o ungirás.

[[v2-29-8]]

^<<v2-29-8,8>>^ Depois farás chegar seus filhos, e lhes farás vestir túnicas,

[[v2-29-9]]

^<<v2-29-9,9>>^ E os cingirás com o cinto, a Aarão e a seus filhos, e lhes atarás as tiaras, para que tenham o sacerdócio por estatuto perpétuo, e sagrarás a Aarão e a seus filhos;

[[v2-29-10]]

^<<v2-29-10,10>>^ E farás chegar o novilho diante da tenda da congregação, e Aarão e seus filhos porão as suas mãos sobre a cabeça do novilho;

[[v2-29-11]]

^<<v2-29-11,11>>^ E degolarás o novilho perante o Senhor, à  porta da tenda da congregação.

[[v2-29-12]]

^<<v2-29-12,12>>^ Depois tomarás do sangue do novilho, e o porás com o teu dedo sobre as pontas do altar, e todo o sangue restante derramarás à base do altar.

[[v2-29-13]]

^<<v2-29-13,13>>^ Também tomarás toda a gordura que cobre as entranhas, e o redenho de sobre o fígado, e ambos os rins, e a gordura que houver neles, e queimá-los-ás sobre o altar;

[[v2-29-14]]

^<<v2-29-14,14>>^ Mas a carne do novilho, e a sua pele, e o seu esterco queimarás com fogo fora do arraial: sacrifício por pecado é.

[[v2-29-15]]

^<<v2-29-15,15>>^ Depois tomarás um carneiro, e Aarão e seus filhos porão as suas mãos sobre a cabeça do carneiro,

[[v2-29-16]]

^<<v2-29-16,16>>^ E degolarás o carneiro, e tomarás o seu sangue, e o espalharás sobre o altar ao redor;

[[v2-29-17]]

^<<v2-29-17,17>>^ E partirás o carneiro em suas partes, e lavarás as suas entranhas e as suas pernas, e as  porás sobre as suas partes e sobre a sua cabeça.

[[v2-29-18]]

^<<v2-29-18,18>>^ Assim queimarás todo o carneiro sobre o altar: é  um holocausto para o Senhor, cheiro suave; uma oferta queimada ao Senhor.

[[v2-29-19]]

^<<v2-29-19,19>>^ Depois tomarás o outro carneiro, e Aarão e seus filhos porão as suas mãos sobre a cabeça do carneiro;

[[v2-29-20]]

^<<v2-29-20,20>>^ E degolarás o carneiro, e tomarás do seu sangue, e o porás sobre a ponta da orelha direita de Aarão, e sobre a ponta das orelhas direitas de seus filhos, como também sobre o dedo polegar das suas mãos direitas, e sobre o dedo polegar dos seus pés direitos: e o resto  do sangue espalharás sobre o altar ao redor.

[[v2-29-21]]

^<<v2-29-21,21>>^ Então tomarás do sangue, que estará  sobre o altar, e do azeite da unção e o espargirás sobre Aarão e sobre os seus vestidos, e sobre seus filhos, e sobre os vestidos de seus filhos com ele; para que ele seja santificado, e os seus vestidos, também seus filhos, e os vestidos de seus filhos com ele.

[[v2-29-22]]

^<<v2-29-22,22>>^ Depois tomarás do carneiro a gordura, e a cauda, e a gordura que cobre as entranhas, e o redenho do fígado, e ambos os rins com a gordura que houver  neles, e o ombro direito, porque é  carneiro das consagrações;

[[v2-29-23]]

^<<v2-29-23,23>>^ E uma fogaça de pão, e um bolo de pão azeitado, e um coscorão do cesto dos pães asmos que estiverem  diante do Senhor,

[[v2-29-24]]

^<<v2-29-24,24>>^ E tudo porás nas mãos de Aarão, e nas mãos de seus filhos: e com movimento o moverás perante o Senhor.

[[v2-29-25]]

^<<v2-29-25,25>>^ Depois o tomarás das suas mãos, e o queimarás no altar sobre o holocausto por cheiro suave perante o Senhor; oferta queimada ao Senhor é.

[[v2-29-26]]

^<<v2-29-26,26>>^ E tomarás o peito do carneiro das consagrações, que é de Aarão, e com movimento o moverás perante o Senhor: e isto  será a tua porção.

[[v2-29-27]]

^<<v2-29-27,27>>^ E santificarás o peito do movimento e o ombro da oferta alçada, que foi movido e alçado do carneiro das consagrações, que for de Aarão e de seus filhos,

[[v2-29-28]]

^<<v2-29-28,28>>^ E será para Aarão e para seus filhos por estatuto perpétuo dos filhos de Israel, porque é oferta alçada: e a oferta alçada será dos filhos de Israel dos seus sacrifícios pacíficos; a sua oferta alçada será  para o Senhor.

[[v2-29-29]]

^<<v2-29-29,29>>^ E os vestidos santos, que são  de Aarão, serão de seus filhos depois dele, para serem ungidos neles e sagrados neles.

[[v2-29-30]]

^<<v2-29-30,30>>^ Sete dias os vestirá aquele que de seus filhos for sacerdote em seu lugar, quando entrar na tenda da congregação para ministrar no santuário.

[[v2-29-31]]

^<<v2-29-31,31>>^ E tomarás o carneiro das consagrações, e cozerás a sua carne no lugar santo;

[[v2-29-32]]

^<<v2-29-32,32>>^ E Aarão e seus filhos comerão a carne deste carneiro, e o pão que está  no cesto à porta da tenda da congregação,

[[v2-29-33]]

^<<v2-29-33,33>>^ E comerão as cousas com que for feita expiação, para consagrá-los, e  para santificá-los: mas um estranho as  não comerá, porque santas são.

[[v2-29-34]]

^<<v2-29-34,34>>^ E se sobejar alguma cousa  da carne das consagrações ou do pão até à manhã, o que sobejar queimarás com fogo: não se comerá, porque santo é.

[[v2-29-35]]

^<<v2-29-35,35>>^ Assim pois farás a Aarão e a seus filhos, conforme a tudo o que eu tenho ordenado por sete dias os sagrarás.

[[v2-29-36]]

^<<v2-29-36,36>>^ Também cada dia prepararás um novilho por  sacrifício pelo pecado para as expiações, e purificarás o altar, fazendo expiação sobre ele; e o ungirás para santificá-lo.

[[v2-29-37]]

^<<v2-29-37,37>>^ Sete dias farás expiação pelo altar e o santificarás e o altar será santíssimo; tudo o que tocar o altar será santo.

[[v2-29-38]]

^<<v2-29-38,38>>^ Isto pois é  o que oferecereis sobre o altar: Dois cordeiros dum ano cada dia continuamente.

[[v2-29-39]]

^<<v2-29-39,39>>^ Um cordeiro oferecerás pela manhã e o outro cordeiro oferecerás à tardinha.

[[v2-29-40]]

^<<v2-29-40,40>>^ Com um cordeiro a décima parte de flor de farinha, misturada com a quarta parte dum him de azeite batido, e para libação a quarta parte dum him de vinho,

[[v2-29-41]]

^<<v2-29-41,41>>^ E o outro cordeiro oferecerás à tardinha, e com ele farás como com a oferta da manhã, e conforme à sua libação, por cheiro suave; oferta queimada é ao Senhor.

[[v2-29-42]]

^<<v2-29-42,42>>^ Este será  o holocausto contínuo por vossas gerações, à porta da tenda da congregação, perante o Senhor, onde vos encontrarei para falar contigo ali.

[[v2-29-43]]

^<<v2-29-43,43>>^ E ali virei aos filhos de Israel para que por minha glória sejam santificados.

[[v2-29-44]]

^<<v2-29-44,44>>^ E santificarei a tenda da congregação e o altar; também santificarei a Aarão e seus filhos, para que me administrem o sacerdócio.

[[v2-29-45]]

^<<v2-29-45,45>>^ E habitarei no meio dos filhos de Israel, e lhes serei por Deus,

[[v2-29-46]]

^<<v2-29-46,46>>^ E saberão que eu sou  o Senhor seu Deus, que os tenho tirado da terra do Egito, para habitar no meio deles: eu, o Senhor seu Deus.

'''

xref:002-exodo/002-exodo-028.adoc#v2-28-0[&#60; Capítulo Anterior] | <<v2-29-0,Topo>> | xref:002-exodo/002-exodo-030.adoc#v2-30-0[Próximo Capítulo &#62;]