include::./index.adoc[]

[[v2-15-0]]
=== Êxodo, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-15-1]]

^<<v2-15-1,1>>^ ENTÃO cantou Moisés e os filhos de Israel este cântico ao Senhor; e falaram, dizendo: Cantarei ao Senhor, porque sumamente se exaltou: lançou no mar o cavalo e o seu cavaleiro.

[[v2-15-2]]

^<<v2-15-2,2>>^ O Senhor é  a minha força, e o meu  cântico; ele me foi por salvação; este é  o meu Deus, portanto lhe farei uma habitação; ele é  o Deus de meu pai, por isso o exaltarei.

[[v2-15-3]]

^<<v2-15-3,3>>^ O Senhor é  varão de guerra: o Senhor é  o seu nome.

[[v2-15-4]]

^<<v2-15-4,4>>^ Lançou no mar os carros de Faraó e o seu exército: e os seus escolhidos príncipes afogaram-se no Mar Vermelho.

[[v2-15-5]]

^<<v2-15-5,5>>^ Os abismos os cobriram: desceram às profundezas como pedra.

[[v2-15-6]]

^<<v2-15-6,6>>^ A tua destra, ó Senhor, se tem glorificado em potência: a tua destra, ó Senhor tem despedaçado o inimigo;

[[v2-15-7]]

^<<v2-15-7,7>>^ E com a grandeza da tua excelência derribaste aos que  se levantaram contra ti; enviaste o teu furor, que os consumiu como restolho.

[[v2-15-8]]

^<<v2-15-8,8>>^ E com o sopro dos teus narizes amontoaram-se as águas, as correntes pararam como montão: os abismos coalharam-se no coração do mar.

[[v2-15-9]]

^<<v2-15-9,9>>^ O inimigo dizia: Perseguirei, alcançarei, repartirei os despojos: fartar-se-á a minha alma deles, arrancarei a minha espada, a minha mão os destruirá.

[[v2-15-10]]

^<<v2-15-10,10>>^ Sopraste com o teu vento, o mar os cobriu: afundaram-se como chumbo em veementes águas.

[[v2-15-11]]

^<<v2-15-11,11>>^ Ó Senhor, quem é como tu entre os deuses? quem é como tu glorificado em santidade, terrível em louvores, obrando maravilhas?

[[v2-15-12]]

^<<v2-15-12,12>>^ Estendeste a tua mão direita: a terra os tragou.

[[v2-15-13]]

^<<v2-15-13,13>>^ Tu, com a tua beneficência, guiaste a este povo, que  salvaste: com a tua força o levaste à habitação da tua santidade.

[[v2-15-14]]

^<<v2-15-14,14>>^ Os povos o ouvirão, eles estremecerão: apoderar-se-á uma dor dos habitantes da Palestina.

[[v2-15-15]]

^<<v2-15-15,15>>^ Então os príncipes de Edom se pasmarão, dos poderosos dos moabitas apoderar-se-á um tremor, derreter-se-ão todos os habitantes de Canaã.

[[v2-15-16]]

^<<v2-15-16,16>>^ Espanto e pavor cairá sobre eles: pela grandeza do teu braço emudecerão como pedra; até que o teu povo haja passado, ó Senhor, até que passe este povo que  adquiriste.

[[v2-15-17]]

^<<v2-15-17,17>>^ Tu  os introduzirás, e os plantarás no monte da tua herança, no  lugar que tu , ó Senhor, aparelhaste para a tua habitação, no santuário, ó Senhor, que  as tuas mãos estabeleceram.

[[v2-15-18]]

^<<v2-15-18,18>>^ O Senhor reinará eterna e perpetuamente;

[[v2-15-19]]

^<<v2-15-19,19>>^ Porque os cavalos de Faraó, com os seus carros e com os seus cavaleiros, entraram no mar, e o Senhor fez tornar as águas do mar sobre eles; mas os filhos de Israel passaram em seco pelo meio do mar.

[[v2-15-20]]

^<<v2-15-20,20>>^ Então Miriã, a profetisa, a irmã de Aarão, tomou o tamboril na sua mão, e todas as mulheres saíram atrás dela com tamboris e com danças.

[[v2-15-21]]

^<<v2-15-21,21>>^ E Miriã lhes respondia: Cantai ao Senhor, porque sumamente se exaltou, e lançou no mar o cavalo com o seu cavaleiro.

[[v2-15-22]]

^<<v2-15-22,22>>^ Depois fez Moisés partir os israelitas do Mar Vermelho, e saíram ao deserto de Sur: e andaram três dias no deserto, e não acharam água.

[[v2-15-23]]

^<<v2-15-23,23>>^ Então chegaram a Mara; mas não puderam beber as águas de Mara, porque eram amargas: por isso chamou-se o seu nome Mara.

[[v2-15-24]]

^<<v2-15-24,24>>^ E o povo murmurou contra Moisés, dizendo: Que havemos de beber?

[[v2-15-25]]

^<<v2-15-25,25>>^ E ele  clamou ao Senhor, e o Senhor mostrou-lhe um lenho que lançou nas águas, e as águas se tornaram doces: ali lhes deu estatutos e uma ordenação, e ali os provou.

[[v2-15-26]]

^<<v2-15-26,26>>^ E disse: Se ouvires atento a voz do Senhor teu Deus, e obrares o que é  reto diante de seus olhos, e inclinares os teus ouvidos aos seus mandamentos, e guardares todos os seus estatutos, nenhuma das enfermidades porei sobre ti, que pus sobre o Egito; porque eu sou  o Senhor que te sara.

[[v2-15-27]]

^<<v2-15-27,27>>^ Então vieram a Elim, e havia  ali doze fontes dágua e setenta palmeiras: e ali se acamparam junto das águas.

'''

xref:002-exodo/002-exodo-014.adoc#v2-14-0[&#60; Capítulo Anterior] | <<v2-15-0,Topo>> | xref:002-exodo/002-exodo-016.adoc#v2-16-0[Próximo Capítulo &#62;]