include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-35-1]]

^<<v2-35-1,1>>^ ENTÃO fez Moisés ajuntar toda a congregação dos filhos de Israel, e disse-lhes: Estas são  as palavras que o Senhor ordenou que se cumprissem.

[[v2-35-2]]

^<<v2-35-2,2>>^ Seis dias se trabalhará, mas o sétimo dia vos será santo, o sábado do repouso ao Senhor: todo aquele que fizer obra nele morrerá.

[[v2-35-3]]

^<<v2-35-3,3>>^ Não acendereis fogo em nenhuma das vossas moradas no dia de sábado.

[[v2-35-4]]

^<<v2-35-4,4>>^ Falou mais Moisés a toda a congregação dos filhos de Israel, dizendo: Esta é a palavra que o Senhor ordenou, dizendo:

[[v2-35-5]]

^<<v2-35-5,5>>^ Tomai, do que vós tendes, uma oferta para o Senhor: cada um, cujo coração é voluntariamente disposto, a trará por oferta alçada ao Senhor; ouro, e prata, e cobre,

[[v2-35-6]]

^<<v2-35-6,6>>^ Como também azul, e púrpura, e carmesim, e linho fino, e pelos  de cabras,

[[v2-35-7]]

^<<v2-35-7,7>>^ E peles de carneiros, tintas de vermelho, e peles de texugos, madeira de  cetim,

[[v2-35-8]]

^<<v2-35-8,8>>^ E azeite para a luminária, e especiarias para o azeite da unção, e para o incenso aromático,

[[v2-35-9]]

^<<v2-35-9,9>>^ E pedras sardônicas, e pedras de engaste, para o éfode e para o peitoral.

[[v2-35-10]]

^<<v2-35-10,10>>^ E todos os sábios de coração entre vós virão, e farão tudo o que o Senhor tem mandado:

[[v2-35-11]]

^<<v2-35-11,11>>^ O tabernáculo, a sua tenda, e a sua coberta, os seus colchetes, e as suas tábuas, as suas barras, as suas colunas, e as suas bases,

[[v2-35-12]]

^<<v2-35-12,12>>^ A arca e os seus varais, o propiciatório e o véu da coberta,

[[v2-35-13]]

^<<v2-35-13,13>>^ A mesa, e os seus varais, e todos os seus vasos; e os pães da proposição,

[[v2-35-14]]

^<<v2-35-14,14>>^ E o castiçal da luminária, e os seus vasos, e as suas lâmpadas, e o azeite para a luminária,

[[v2-35-15]]

^<<v2-35-15,15>>^ E o altar do incenso e os seus varais, e o azeite da unção, e o incenso aromático, e a coberta da porta à entrada do tabernáculo,

[[v2-35-16]]

^<<v2-35-16,16>>^ O altar do holocausto, e o crivo de cobre que terá  seus varais, e todos os seus vasos, a pia e a sua base,

[[v2-35-17]]

^<<v2-35-17,17>>^ As cortinas do pátio, as suas colunas e as suas bases, e a coberta da porta do pátio,

[[v2-35-18]]

^<<v2-35-18,18>>^ As estacas do tabernáculo, e as estacas do pátio, e as suas cordas,

[[v2-35-19]]

^<<v2-35-19,19>>^ Os vestidos do ministério para ministrar no santuário, os vestidos santos de Aarão o sacerdote, e os vestidos de seus filhos, para administrarem o sacerdócio.

[[v2-35-20]]

^<<v2-35-20,20>>^ Então toda a congregação dos filhos de Israel saiu de diante de Moisés,

[[v2-35-21]]

^<<v2-35-21,21>>^ E veio todo o homem, a quem o seu coração moveu, e todo aquele cujo espírito voluntariamente o excitou, e trouxeram a oferta alçada ao Senhor para a obra da tenda da congregação, e para todo o seu serviço, e para os vestidos santos.

[[v2-35-22]]

^<<v2-35-22,22>>^ E assim vieram homens e mulheres, todos dispostos de coração: trouxeram fivelas, e pendentes, e anéis, e braceletes, todo o vaso de ouro; e todo o homem oferecia oferta de ouro ao Senhor;

[[v2-35-23]]

^<<v2-35-23,23>>^ E todo o homem que se achou com azul e púrpura, e carmesim e linho fino, e pelos  de cabras, e peles de carneiro tintas de vermelho, e peles de texugos, os trazia;

[[v2-35-24]]

^<<v2-35-24,24>>^ Todo aquele que oferecia oferta alçada de prata ou de metal, a trazia por oferta alçada ao Senhor; e todo aquele que se achava com madeira de cetim, a trazia para toda a obra do serviço.

[[v2-35-25]]

^<<v2-35-25,25>>^ E todas as mulheres sábias de coração fiavam com as suas mãos, e traziam o fiado, o azul e a púrpura, o carmesim e o linho fino.

[[v2-35-26]]

^<<v2-35-26,26>>^ E todas as mulheres, cujo coração as moveu em sabedoria, fiavam os pelos  das cabras.

[[v2-35-27]]

^<<v2-35-27,27>>^ E os príncipes traziam pedras sardônicas, e pedras de engastes para o éfode e para o peitoral,

[[v2-35-28]]

^<<v2-35-28,28>>^ E especiarias, e azeite para a luminária, e para o óleo da unção, e para o incenso aromático.

[[v2-35-29]]

^<<v2-35-29,29>>^ Todo o homem e mulher, cujo coração voluntariamente se moveu a trazer alguma  cousa para toda a obra que o Senhor ordenara se fizesse pela mão de Moisés, aquilo  trouxeram os filhos de Israel por oferta voluntária ao Senhor.

[[v2-35-30]]

^<<v2-35-30,30>>^ Depois disse Moisés aos filhos de Israel: Eis que o Senhor tem chamado por nome a Bezaleel, o filho de Uri, filho de Hur, da tribo de Judá.

[[v2-35-31]]

^<<v2-35-31,31>>^ E o espírito de Deus o encheu de sabedoria, entendimento e ciência em todo o artifício,

[[v2-35-32]]

^<<v2-35-32,32>>^ E para inventar invenções, para trabalhar em ouro, e em prata, e em cobre,

[[v2-35-33]]

^<<v2-35-33,33>>^ E em artifício de pedras para engastar, e em artifício de madeira, para trabalhar em toda a obra esmerada.

[[v2-35-34]]

^<<v2-35-34,34>>^ Também lhe tem disposto o coração para ensinar a outros : a ele e a Aoliabe, o filho de Aisamaque, da tribo de Dã.

[[v2-35-35]]

^<<v2-35-35,35>>^ Encheu-os de sabedoria do coração, para fazer toda a obra de mestre, e a mais engenhosa, e a do bordador, em azul, e em púrpura, em carmesim, e em linho fino, e a do tecelão: fazendo toda a obra, e inventando invenções.

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]