include::./index.adoc[]

[[v2-18-0]]
=== Êxodo, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-18-1]]

^<<v2-18-1,1>>^ ORA Jetro, sacerdote de Midiã, sogro de Moisés, ouviu todas as cousas que Deus tinha feito a Moisés e a Israel seu povo: como o Senhor tinha tirado a Israel do Egito.

[[v2-18-2]]

^<<v2-18-2,2>>^ E Jetro, sogro de Moisés, tomou a Zípora, a mulher de Moisés, depois que ele lha  enviara,

[[v2-18-3]]

^<<v2-18-3,3>>^ Com seus dois filhos, dos quais um se chamava Gérson; porque disse: Eu fui peregrino em terra estranha;

[[v2-18-4]]

^<<v2-18-4,4>>^ E o outro se chamava Eliézer; porque disse : o Deus de meu pai foi minha ajuda, e me livrou da espada de Faraó.

[[v2-18-5]]

^<<v2-18-5,5>>^ Vindo pois Jetro, o sogro de Moisés, com seus filhos e com sua mulher, a Moisés no deserto, ao monte de Deus, onde se tinha acampado,

[[v2-18-6]]

^<<v2-18-6,6>>^ Disse a Moisés: Eu, teu sogro Jetro, venho a ti, com tua mulher, e seus dois filhos com ela.

[[v2-18-7]]

^<<v2-18-7,7>>^ Então saiu Moisés ao encontro de seu sogro, e inclinou-se, e beijou-o, e perguntaram um ao outro como estavam, e entraram na tenda.

[[v2-18-8]]

^<<v2-18-8,8>>^ E Moisés contou a seu sogro todas as cousas que o Senhor tinha feito a Faraó e aos egípcios por amor de Israel, e todo o trabalho que passaram no caminho, e como  o Senhor os livrara.

[[v2-18-9]]

^<<v2-18-9,9>>^ E alegrou-se Jetro de todo o bem que o Senhor tinha feito a Israel, livrando-o da mão dos egípcios.

[[v2-18-10]]

^<<v2-18-10,10>>^ E Jetro disse: Bendito seja  o Senhor, que vos livrou das mãos dos egípcios e da mão de Faraó; que livrou a este povo de debaixo da mão dos egípcios.

[[v2-18-11]]

^<<v2-18-11,11>>^ Agora sei que o Senhor é  maior que todos os deuses; porque na cousa em que se ensoberbeceram, os sobrepujou.

[[v2-18-12]]

^<<v2-18-12,12>>^ Então tomou Jetro, o sogro de Moisés, holocausto e sacrifícios para Deus; e veio Aarão, e todos os anciãos de Israel, para comerem pão com o sogro de Moisés diante de Deus.

[[v2-18-13]]

^<<v2-18-13,13>>^ E aconteceu que, ao outro dia, Moisés assentou-se para julgar o povo; e o povo estava em pé diante de Moisés desde a manhã até à tarde.

[[v2-18-14]]

^<<v2-18-14,14>>^ Vendo pois o sogro de Moisés tudo o que ele fazia ao povo, disse: Que é  isto, que tu fazes ao povo? por que te assentas só, e todo o povo está em pé diante de ti, desde a manhã até à tarde?

[[v2-18-15]]

^<<v2-18-15,15>>^ Então disse Moisés a seu sogro: É porque este povo vem a mim, para consultar a Deus:

[[v2-18-16]]

^<<v2-18-16,16>>^ Quando tem algum negócio vem a mim, para que eu julgue entre um e outro, e lhes  declare os estatutos de Deus, e as suas leis.

[[v2-18-17]]

^<<v2-18-17,17>>^ O sogro de Moisés porém lhe disse: Não é  bom o que fazes.

[[v2-18-18]]

^<<v2-18-18,18>>^ Totalmente desfalecerás, assim tu, como este povo que está  contigo: porque este negócio é mui difícil para ti; tu só não o podes fazer.

[[v2-18-19]]

^<<v2-18-19,19>>^ Ouve agora a minha voz; eu te aconselharei, e Deus será contigo: Sê tu pelo povo diante de Deus, e leva tu as cousas a Deus;

[[v2-18-20]]

^<<v2-18-20,20>>^ E declara-lhes os estatutos e as leis, e faze-lhes saber o caminho em que devem andar, e a obra que devem fazer.

[[v2-18-21]]

^<<v2-18-21,21>>^ E tu dentre todo o povo procura homens capazes, tementes a Deus, homens de verdade, que aborreçam a avareza; e põe-nos sobre eles por maiorais de mil, maiorais de cem, maiorais de cinquenta, e maiorais de dez;

[[v2-18-22]]

^<<v2-18-22,22>>^ Para que julguem este povo em todo o tempo, e seja que todo o negócio grave tragam a ti, mas todo o negócio pequeno eles o julguem; assim a ti mesmo te aliviarás da carga , e eles  a levarão contigo.

[[v2-18-23]]

^<<v2-18-23,23>>^ Se isto fizeres, e Deus to mandar, poderás então subsistir: assim também todo este povo em paz virá ao seu lugar.

[[v2-18-24]]

^<<v2-18-24,24>>^ E Moisés deu ouvidos à voz de seu sogro e fez tudo quanto tinha dito;

[[v2-18-25]]

^<<v2-18-25,25>>^ E escolheu Moisés homens capazes, de todo o Israel, e os pôs por cabeças sobre o povo: maiorais de mil e maiorais de cem, maiorais de cinquenta, e maiorais de dez.

[[v2-18-26]]

^<<v2-18-26,26>>^ E eles julgaram o povo em todo o tempo; o negócio árduo trouxeram a Moisés, e todo o negócio pequeno julgaram eles.

[[v2-18-27]]

^<<v2-18-27,27>>^ Então despediu Moisés o seu sogro, o qual se foi à sua terra.

'''

xref:002-exodo/002-exodo-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodo/002-exodo-019.adoc#v2-19-0[Próximo Capítulo &#62;]