include::./index.adoc[]

[[v2-21-0]]
=== Êxodo, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-21-1]]

^<<v2-21-1,1>>^ ESTES são  os estatutos que lhes proporás:

[[v2-21-2]]

^<<v2-21-2,2>>^ Se comprares um servo hebreu, seis anos servirá; mas ao sétimo sairá forro, de graça.

[[v2-21-3]]

^<<v2-21-3,3>>^ Se entrou só  com o seu corpo, só  com o seu corpo sairá: se ele era  homem casado, sairá sua mulher com ele.

[[v2-21-4]]

^<<v2-21-4,4>>^ Se seu senhor lhe houver dado uma mulher, e ela lhe houver dado filhos ou filhas, a mulher e seus filhos serão de seu senhor, e ele sairá só  com seu corpo.

[[v2-21-5]]

^<<v2-21-5,5>>^ Mas se aquele servo expressamente disser: Eu amo a meu senhor, e a minha mulher, e a meus filhos; não quero sair forro:

[[v2-21-6]]

^<<v2-21-6,6>>^ Então seu senhor o levará aos juízes, e o fará chegar à porta, ou ao postigo, e seu senhor lhe furará a orelha com uma sovela; e o servirá para sempre.

[[v2-21-7]]

^<<v2-21-7,7>>^ E se algum vender sua filha por serva, não sairá como saem os servos.

[[v2-21-8]]

^<<v2-21-8,8>>^ Se desagradar aos olhos de seu senhor, e não se desposar com ela, fará que se resgate: não poderá vendê-la a um povo estranho, usando deslealmente com ela.

[[v2-21-9]]

^<<v2-21-9,9>>^ Mas se a desposar com seu filho, fará com ela conforme ao direito das filhas.

[[v2-21-10]]

^<<v2-21-10,10>>^ Se lhe tomar outra, não diminuirá o mantimento desta, nem o seu vestido, nem a sua obrigação marital.

[[v2-21-11]]

^<<v2-21-11,11>>^ E se lhe não fizer estas três cousas, sairá de graça, sem dar dinheiro.

[[v2-21-12]]

^<<v2-21-12,12>>^ Quem ferir alguém, que morra, ele  também certamente morrerá;

[[v2-21-13]]

^<<v2-21-13,13>>^ Porém se lhe  não armou ciladas, mas Deus o fez encontrar nas suas mãos, ordenar-te-ei um lugar, para onde ele fugirá.

[[v2-21-14]]

^<<v2-21-14,14>>^ Mas se alguém se ensoberbecer contra o seu próximo, matando-o com engano, tirá-lo-ás do meu altar, para que morra.

[[v2-21-15]]

^<<v2-21-15,15>>^ O que ferir a seu pai, ou a sua mãe, certamente morrerá.

[[v2-21-16]]

^<<v2-21-16,16>>^ E quem furtar algum  homem, e o vender, ou for achado na sua mão, certamente morrerá.

[[v2-21-17]]

^<<v2-21-17,17>>^ E quem amaldiçoar a seu pai ou a sua mãe, certamente morrerá.

[[v2-21-18]]

^<<v2-21-18,18>>^ E se alguns homens pelejarem, ferindo um ao outro com pedra ou com o punho, e este não morrer, mas cair na cama;

[[v2-21-19]]

^<<v2-21-19,19>>^ Se ele tornar a levantar-se e andar fora sobre o seu bordão, então aquele que o feriu será absolvido: somente lhe pagará o tempo que perdera e o fará curar totalmente.

[[v2-21-20]]

^<<v2-21-20,20>>^ Se alguém ferir a seu servo, ou a sua serva com pau, e morrerem debaixo da sua mão, certamente será castigado;

[[v2-21-21]]

^<<v2-21-21,21>>^ Porém se ficarem vivos por um ou dois dias, não será castigado, porque é  seu dinheiro.

[[v2-21-22]]

^<<v2-21-22,22>>^ Se alguns homens pelejarem, e ferirem uma  mulher grávida, e forem causa de que aborte, porém se não houver morte, certamente será multado conforme ao que lhe impuser o marido da mulher, e pagará diante dos juízes.

[[v2-21-23]]

^<<v2-21-23,23>>^ Mas se houver morte, então darás vida por vida,

[[v2-21-24]]

^<<v2-21-24,24>>^ Olho por olho, dente por dente, mão por mão, pé por pé,

[[v2-21-25]]

^<<v2-21-25,25>>^ Queimadura por queimadura, ferida por ferida, golpe por golpe.

[[v2-21-26]]

^<<v2-21-26,26>>^ E quando alguém ferir o olho do seu servo, ou o olho da sua serva, e o danificar, o deixará ir forro pelo seu olho.

[[v2-21-27]]

^<<v2-21-27,27>>^ E se tirar o dente do seu servo, ou o dente da sua serva, o deixará ir forro pelo seu dente.

[[v2-21-28]]

^<<v2-21-28,28>>^ E se algum boi escornear homem ou mulher, que morra, o boi será apedrejado certamente, e a sua carne se não comerá; mas o dono do boi será  absolvido.

[[v2-21-29]]

^<<v2-21-29,29>>^ Mas se o boi dantes era escorneador, e o seu dono foi conhecedor disso e não o guardou, matando homem ou mulher, o boi será apedrejado, e também o seu dono morrerá.

[[v2-21-30]]

^<<v2-21-30,30>>^ Se lhe for imposto resgate, então dará como resgate da sua vida tudo quanto lhe for imposto,

[[v2-21-31]]

^<<v2-21-31,31>>^ Quer tenha escorneado um filho, quer tenha escorneado uma filha; conforme a este estatuto lhe será feito.

[[v2-21-32]]

^<<v2-21-32,32>>^ Se o boi escornear um servo, ou uma serva, dar- se- á trinta siclos de prata ao seu senhor, e o boi será apedrejado.

[[v2-21-33]]

^<<v2-21-33,33>>^ Se alguém abrir uma cova, ou se alguém cavar uma cova, e não a cobrir, e nela cair um boi ou jumento,

[[v2-21-34]]

^<<v2-21-34,34>>^ O dono da cova o  pagará, ao seu dono o dinheiro restituirá; mas o  morto será seu.

[[v2-21-35]]

^<<v2-21-35,35>>^ Se o boi de alguém ferir de morte o boi do seu próximo, então se venderá o boi vivo, e o dinheiro dele se repartirá igualmente, e também o morto se repartirá igualmente.

[[v2-21-36]]

^<<v2-21-36,36>>^ Mas se foi notório que aquele boi dantes era escorneador, e seu dono não o guardou, certamente pagará boi por boi; porém o morto será seu.

'''

xref:002-exodo/002-exodo-020.adoc#v2-20-0[&#60; Capítulo Anterior] | <<v2-21-0,Topo>> | xref:002-exodo/002-exodo-022.adoc#v2-22-0[Próximo Capítulo &#62;]