include::./index.adoc[]

[[v2-24-0]]
=== Êxodo, 24
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-24-1]]

^<<v2-24-1,1>>^ DEPOIS disse a Moisés: Sobe ao Senhor, tu e Aarão, Nadabe e Abiú, e setenta dos anciãos de Israel; e inclinai-vos de longe.

[[v2-24-2]]

^<<v2-24-2,2>>^ E só Moisés se chegará ao Senhor; mas eles não se cheguem, nem o povo suba com ele.

[[v2-24-3]]

^<<v2-24-3,3>>^ Vindo pois Moisés, e contando ao povo todas as palavras do Senhor, e todos os estatutos, então o povo respondeu a uma voz, e disseram: Todas as palavras, que o Senhor tem falado, faremos.

[[v2-24-4]]

^<<v2-24-4,4>>^ E Moisés escreveu todas as palavras do Senhor, e levantou-se pela manhã de madrugada, e edificou um altar ao pé do monte, e doze monumentos, segundo as doze tribos de Israel;

[[v2-24-5]]

^<<v2-24-5,5>>^ E enviou certos mancebos dos filhos de Israel, os quais ofereceram holocaustos, e sacrificaram ao Senhor sacrifícios pacíficos de bezerros.

[[v2-24-6]]

^<<v2-24-6,6>>^ E Moisés tomou a metade do sangue, e a pôs em bacias; e a outra  metade do sangue espargiu sobre o altar.

[[v2-24-7]]

^<<v2-24-7,7>>^ E tomou o livro do concerto, e o leu aos ouvidos do povo, e eles disseram: Tudo o que o Senhor tem falado faremos, e obedeceremos.

[[v2-24-8]]

^<<v2-24-8,8>>^ Então tomou Moisés aquele sangue, e espargiu- o  sobre o povo, e disse: Eis aqui o sangue do concerto que o Senhor, tem feito convosco sobre todas estas palavras.

[[v2-24-9]]

^<<v2-24-9,9>>^ E subiram Moisés e Aarão, Nadabe e Abiú, e setenta dos anciãos de Israel,

[[v2-24-10]]

^<<v2-24-10,10>>^ E viram o Deus de Israel, e debaixo de seus pés havia  como uma obra de pedra de safira, e como o parecer do céu na sua  claridade.

[[v2-24-11]]

^<<v2-24-11,11>>^ Porém ele não estendeu a sua mão sobre os escolhidos dos filhos de Israel; mas viram a Deus, e comeram e beberam.

[[v2-24-12]]

^<<v2-24-12,12>>^ Então disse o Senhor a Moisés: Sobe a mim ao monte, e fica lá: e dar-te-ei tábuas de pedra, e a lei, e os mandamentos que tenho escrito, para os ensinar.

[[v2-24-13]]

^<<v2-24-13,13>>^ E levantou-se Moisés com Josué seu servidor; e subiu Moisés ao monte de Deus.

[[v2-24-14]]

^<<v2-24-14,14>>^ E disse aos anciãos: Esperai-nos aqui, até que tornemos a vós: e eis que Aarão e Hur ficam  convosco; quem tiver algum  negócio, se chegará a eles.

[[v2-24-15]]

^<<v2-24-15,15>>^ E, subindo Moisés ao monte, a nuvem cobriu o monte.

[[v2-24-16]]

^<<v2-24-16,16>>^ E habitava a glória do Senhor sobre o monte de Sinai, e a nuvem o cobriu por seis dias: e ao sétimo dia chamou a Moisés do meio da nuvem.

[[v2-24-17]]

^<<v2-24-17,17>>^ E o parecer da glória do Senhor era  como um fogo consumidor no cume do monte, aos olhos dos filhos de Israel.

[[v2-24-18]]

^<<v2-24-18,18>>^ E Moisés entrou no meio da nuvem, depois que subiu ao monte: e Moisés esteve no monte quarenta dias e quarenta noites.

'''

xref:002-exodo/002-exodo-023.adoc#v2-23-0[&#60; Capítulo Anterior] | <<v2-24-0,Topo>> | xref:002-exodo/002-exodo-025.adoc#v2-25-0[Próximo Capítulo &#62;]