include::./index.adoc[]

[[v2-20-0]]
=== Êxodo, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-20-1]]

^<<v2-20-1,1>>^ ENTÃO falou Deus todas estas palavras, dizendo:

[[v2-20-2]]

^<<v2-20-2,2>>^ Eu sou  o Senhor teu Deus, que te tirei da terra do Egito, da casa da servidão.

[[v2-20-3]]

^<<v2-20-3,3>>^ Não terás outros deuses diante de mim.

[[v2-20-4]]

^<<v2-20-4,4>>^ Não farás para ti imagem de escultura, nem alguma semelhança do que há  em cima nos céus, nem em baixo na terra, nem nas águas de baixo da terra.

[[v2-20-5]]

^<<v2-20-5,5>>^ Não te encurvarás a elas nem as servirás: porque eu, o Senhor teu Deus, sou  Deus zeloso, que visito a maldade dos pais nos filhos até à terceira e quarta geração  daqueles que me aborrecem.

[[v2-20-6]]

^<<v2-20-6,6>>^ E faço misericórdia em milhares aos que me amam e guardam os meus mandamentos.

[[v2-20-7]]

^<<v2-20-7,7>>^ Não tomarás o nome do Senhor teu Deus em vão: porque o Senhor não terá por inocente o que tomar o seu nome em vão.

[[v2-20-8]]

^<<v2-20-8,8>>^ Lembra-te do dia do sábado, para o santificar.

[[v2-20-9]]

^<<v2-20-9,9>>^ Seis dias trabalharás, e farás toda a tua obra,

[[v2-20-10]]

^<<v2-20-10,10>>^ Mas o sétimo dia é  o sábado do Senhor teu Deus: não farás nenhuma obra, nem tu, nem teu filho, nem tua filha, nem o teu servo, nem a tua serva, nem o teu animal nem o teu estrangeiro, que está  dentro das tuas portas.

[[v2-20-11]]

^<<v2-20-11,11>>^ Porque em seis dias fez o Senhor os céus e a terra, o mar e tudo que neles há , e ao sétimo dia descansou: portanto abençoou o Senhor o dia do sábado, e o santificou.

[[v2-20-12]]

^<<v2-20-12,12>>^ Honra a teu pai e a tua mãe, para que se prolonguem os teus dias na terra que o Senhor teu Deus te dá.

[[v2-20-13]]

^<<v2-20-13,13>>^ Não matarás.

[[v2-20-14]]

^<<v2-20-14,14>>^ Não adulterarás.

[[v2-20-15]]

^<<v2-20-15,15>>^ Não furtarás.

[[v2-20-16]]

^<<v2-20-16,16>>^ Não dirás falso testemunho contra o teu próximo.

[[v2-20-17]]

^<<v2-20-17,17>>^ Não cobiçarás a casa do teu próximo, não cobiçarás a mulher do teu próximo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem cousa alguma do teu próximo.

[[v2-20-18]]

^<<v2-20-18,18>>^ E todo o povo viu os trovões e os relâmpagos, e o sonido da buzina, e o monte fumegando: e o povo, vendo isso , retirou-se e pôs-se de longe.

[[v2-20-19]]

^<<v2-20-19,19>>^ E disseram a Moisés: Fala tu conosco, e ouviremos: e não fale Deus conosco, para que não morramos.

[[v2-20-20]]

^<<v2-20-20,20>>^ E disse Moisés ao povo: Não temais, que Deus veio para provar-vos, e para que o seu temor esteja diante de vós, para que não pequeis.

[[v2-20-21]]

^<<v2-20-21,21>>^ E o povo estava em pé de longe: Moisés, porém, se chegou à escuridade, onde Deus estava.

[[v2-20-22]]

^<<v2-20-22,22>>^ Então disse o Senhor a Moisés: Assim dirás aos filhos de Israel: Vós tendes visto que eu falei convosco desde os céus.

[[v2-20-23]]

^<<v2-20-23,23>>^ Não fareis outros deuses comigo; deuses de prata ou deuses de ouro não fareis para vós.

[[v2-20-24]]

^<<v2-20-24,24>>^ Um altar de terra me farás, e sobre ele sacrificarás os teus holocaustos, e as tuas ofertas pacíficas, as tuas ovelhas, e as tuas vacas: em todo o lugar, onde eu fizer celebrar a memória do meu nome, virei a ti, e te abençoarei.

[[v2-20-25]]

^<<v2-20-25,25>>^ E se me fizeres um altar de pedras, não o farás de pedras  lavradas: se sobre ele levantares o teu buril, profaná-lo-ás.

[[v2-20-26]]

^<<v2-20-26,26>>^ Não subirás também por degraus ao meu altar, para que a tua nudez não seja descoberta diante deles.

'''

xref:002-exodo/002-exodo-019.adoc#v2-19-0[&#60; Capítulo Anterior] | <<v2-20-0,Topo>> | xref:002-exodo/002-exodo-021.adoc#v2-21-0[Próximo Capítulo &#62;]