include::./index.adoc[]

[[v2-3-0]]
=== Êxodo, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-3-1]]

^<<v2-3-1,1>>^ E APASCENTAVA Moisés o rebanho de Jetro, seu sogro, sacerdote em Midiã; e levou o rebanho atrás do deserto, e veio ao monte de Deus, a Horebe.

[[v2-3-2]]

^<<v2-3-2,2>>^ E apareceu-lhe o anjo do Senhor em uma chama de fogo do meio duma sarça; e olhou, e eis que a sarça ardia no fogo, e a sarça não se consumia.

[[v2-3-3]]

^<<v2-3-3,3>>^ E Moisés disse: Agora me virarei para lá, e verei esta grande visão, porque a sarça se não queima.

[[v2-3-4]]

^<<v2-3-4,4>>^ E vendo o Senhor que se virava para lá a ver, bradou Deus a ele do meio da sarça, e disse: Moisés, Moisés. E ele disse: Eis-me aqui.

[[v2-3-5]]

^<<v2-3-5,5>>^ E disse: Não te chegues para cá; tira os teus sapatos de teus pés; porque o lugar em que tu estás é terra santa.

[[v2-3-6]]

^<<v2-3-6,6>>^ Disse mais: Eu sou  o Deus de teu pai, o Deus de Abraão, o Deus de Isaque, e o Deus de Jacó. E Moisés encobriu o seu rosto, porque temeu olhar para Deus.

[[v2-3-7]]

^<<v2-3-7,7>>^ E disse o Senhor: Tenho visto atentamente a aflição do meu povo, que está  no Egito, e tenho ouvido o seu clamor por causa dos seus exatores, porque conheci as suas dores.

[[v2-3-8]]

^<<v2-3-8,8>>^ Portanto desci para livrá-lo da mão dos egípcios, e para fazê-lo subir daquela terra, a uma terra boa e larga, a uma terra que mana leite e mel; ao lugar do cananeu, e do heteu, e do amorreu, e do ferezeu, e do heveu, e do jebuseu.

[[v2-3-9]]

^<<v2-3-9,9>>^ E agora, eis que o clamor dos filhos de Israel chegou a mim, e também tenho visto a opressão com que os egípcios os oprimem.

[[v2-3-10]]

^<<v2-3-10,10>>^ Vem agora, pois, e eu te enviarei a Faraó, para que tires o meu povo (os filhos de Israel) do Egito.

[[v2-3-11]]

^<<v2-3-11,11>>^ Então Moisés disse a Deus: Quem sou  eu, que vá a Faraó e tire do Egito os filhos de Israel?

[[v2-3-12]]

^<<v2-3-12,12>>^ E Deus disse: Certamente eu serei contigo; e isto te será por sinal de que eu te enviei: Quando houveres tirado este povo do Egito, servireis a Deus, neste monte.

[[v2-3-13]]

^<<v2-3-13,13>>^ Então disse Moisés a Deus: Eis que quando vier aos filhos de Israel, e lhes disser: O Deus de vossos pais me enviou a vós; e eles me disserem: Qual é o seu nome? Que lhes direi?

[[v2-3-14]]

^<<v2-3-14,14>>^ E disse Deus a Moisés: Eu Sou o Que Sou . Disse mais: Assim dirás aos filhos de Israel: Eu Sou  me enviou a vós.

[[v2-3-15]]

^<<v2-3-15,15>>^ E Deus disse mais a Moisés: Assim dirás aos filhos de Israel: O Senhor Deus de vossos pais, o Deus de Abraão, o Deus de Isaque, e o Deus de Jacó, me enviou a vós; este é  meu nome eternamente, e este é  meu memorial de geração em geração.

[[v2-3-16]]

^<<v2-3-16,16>>^ Vai, e ajunta os anciãos de Israel, e dize-lhes: O Senhor, o Deus de vossos pais, o Deus de Abraão, de Isaque e de Jacó, me apareceu, dizendo: Certamente vos tenho visitado, e visto  o que vos é feito no Egito.

[[v2-3-17]]

^<<v2-3-17,17>>^ Portanto eu disse: Far-vos-ei subir da aflição do Egito à terra do cananeu, do heteu, e do amorreu, e do ferezeu, e do heveu, e do jebuseu, a uma terra que mana leite e mel.

[[v2-3-18]]

^<<v2-3-18,18>>^ E ouvirão a tua voz; e irás, tu e os anciãos de Israel, ao rei do Egito, e dir-lhe-eis: O Senhor, o Deus dos hebreus, nos encontrou; agora pois deixa-nos ir caminho de três dias para o deserto, para que sacrifiquemos ao Senhor nosso Deus.

[[v2-3-19]]

^<<v2-3-19,19>>^ Eu sei, porém, que o rei do Egito não vos deixará ir, nem ainda por uma mão forte.

[[v2-3-20]]

^<<v2-3-20,20>>^ Porque eu estenderei a minha mão, e ferirei ao Egito com todas as minhas maravilhas que farei no meio dele; depois vos deixará ir.

[[v2-3-21]]

^<<v2-3-21,21>>^ E eu darei graça a este povo aos olhos dos egípcios; e acontecerá que, quando sairdes, não saireis vazios,

[[v2-3-22]]

^<<v2-3-22,22>>^ Porque cada  mulher pedirá à sua vizinha e à sua hóspeda vasos de prata, e vasos de ouro, e vestidos, os quais poreis sobre vossos filhos e sobre vossas filhas; e despojareis ao Egito.

'''

xref:002-exodo/002-exodo-002.adoc#v2-2-0[&#60; Capítulo Anterior] | <<v2-3-0,Topo>> | xref:002-exodo/002-exodo-004.adoc#v2-4-0[Próximo Capítulo &#62;]