include::./index.adoc[]

[[v2-12-0]]
=== Êxodo, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-12-1]]

^<<v2-12-1,1>>^ E FALOU o Senhor a Moisés e a Aarão na terra do Egito, dizendo:

[[v2-12-2]]

^<<v2-12-2,2>>^ Este mesmo mês vos será  o princípio dos meses: este vos será  o primeiro dos meses do ano.

[[v2-12-3]]

^<<v2-12-3,3>>^ Falai a toda a congregação de Israel, dizendo: Aos dez deste mês tome cada um para si um cordeiro, segundo as casas dos pais, um cordeiro para cada casa.

[[v2-12-4]]

^<<v2-12-4,4>>^ Mas se a família for pequena para um cordeiro, então tome um só com seu vizinho perto de sua casa, conforme ao número das almas: conforme ao comer de cada um, fareis a conta para o cordeiro.

[[v2-12-5]]

^<<v2-12-5,5>>^ O cordeiro, ou cabrito , será sem mácula, um macho de um ano, o qual tomareis das ovelhas ou das cabras,

[[v2-12-6]]

^<<v2-12-6,6>>^ E o guardareis até ao décimo quarto dia deste mês, e todo o ajuntamento da congregação de Israel o sacrificará à tarde.

[[v2-12-7]]

^<<v2-12-7,7>>^ E tomarão do sangue, e pô-lo-ão em ambas as ombreiras, e na verga da porta, nas casas em que o comerem.

[[v2-12-8]]

^<<v2-12-8,8>>^ E naquela noite comerão a carne assada no fogo, com pães asmos; com ervas  amargosas a comerão.

[[v2-12-9]]

^<<v2-12-9,9>>^ Não comereis dele nada cru, nem cozido em água, senão assado ao fogo: a cabeça com os pés e com a fressura.

[[v2-12-10]]

^<<v2-12-10,10>>^ E nada dele deixareis até amanhã: mas o que dele ficar até amanhã, queimareis no fogo.

[[v2-12-11]]

^<<v2-12-11,11>>^ Assim pois o comereis: Os vossos lombos cingidos, os vossos sapatos nos pés, e o vosso cajado na mão: e o comereis apressadamente: esta é  a páscoa do Senhor.

[[v2-12-12]]

^<<v2-12-12,12>>^ E eu passarei pela terra do Egito esta noite, e ferirei todo o primogênito na terra do Egito, desde os homens até aos animais; e sobre todos os deuses do Egito farei juízos: Eu sou o Senhor.

[[v2-12-13]]

^<<v2-12-13,13>>^ E aquele sangue vos será por sinal nas casas em que estiverdes ; vendo eu sangue, passarei por cima de vós, e não haverá entre vós praga de mortandade, quando eu ferir a terra do Egito.

[[v2-12-14]]

^<<v2-12-14,14>>^ E este dia vos será por memória, e celebrá-lo-eis por festa ao Senhor: nas vossas gerações o celebrareis por estatuto perpétuo.

[[v2-12-15]]

^<<v2-12-15,15>>^ Sete dias comereis pães asmos: ao primeiro dia tirareis o fermento das vossas casas; porque qualquer que comer pão  levedado, desde o primeiro até ao sétimo dia, aquela alma será cortada de Israel.

[[v2-12-16]]

^<<v2-12-16,16>>^ E ao primeiro dia haverá  santa convocação: também ao sétimo dia tereis santa convocação: nenhuma obra se fará neles, senão o que cada alma houver de comer; isso somente aprontareis para vós.

[[v2-12-17]]

^<<v2-12-17,17>>^ Guardai pois a festa  dos pães asmos, porque naquele mesmo dia tirei vossos exércitos da terra do Egito: pelo que guardareis este dia nas vossas gerações por estatuto perpétuo.

[[v2-12-18]]

^<<v2-12-18,18>>^ No primeiro mês , aos catorze dias do mês, à tarde, comereis pães asmos até vinte e um do mês à tarde.

[[v2-12-19]]

^<<v2-12-19,19>>^ Por sete dias não se ache nenhum fermento nas vossas casas; porque qualquer que comer pão  levedado, aquela alma será cortada da congregação de Israel, assim o estrangeiro como o natural da terra.

[[v2-12-20]]

^<<v2-12-20,20>>^ Nenhuma cousa levedada comereis; em todas as vossas habitações comereis pães asmos.

[[v2-12-21]]

^<<v2-12-21,21>>^ Chamou pois Moisés a todos os anciãos de Israel, e disse-lhes: Escolhei e tomai vós cordeiros para vossas famílias, e sacrificai a páscoa.

[[v2-12-22]]

^<<v2-12-22,22>>^ Então tomai um molho de hissopo, e molhai-o no sangue que estiver na bacia, e lançai na verga da porta, e em ambas as ombreiras, do sangue que estiver  na bacia; porém nenhum de vós saia da porta da sua casa até à manhã.

[[v2-12-23]]

^<<v2-12-23,23>>^ Porque o Senhor passará para ferir aos egípcios, porém quando vir o sangue na verga da porta, e em ambas as ombreiras, o Senhor passará aquela porta, e não deixará ao destruidor entrar em vossas casas para vos ferir.

[[v2-12-24]]

^<<v2-12-24,24>>^ Portanto guardai isto por estatuto para vós e para vossos filhos, para sempre.

[[v2-12-25]]

^<<v2-12-25,25>>^ E acontecerá que, quando entrardes na terra que o Senhor vos dará, como tem dito, guardareis este culto.

[[v2-12-26]]

^<<v2-12-26,26>>^ E acontecerá que, quando vossos filhos vos disserem: Que culto é  este vosso?

[[v2-12-27]]

^<<v2-12-27,27>>^ Então direis: Este é  o sacrifício da páscoa ao Senhor, que passou as casas dos filhos de Israel no Egito, quando feriu aos egípcios, e livrou as nossas casas. Então o povo inclinou-se, e adorou.

[[v2-12-28]]

^<<v2-12-28,28>>^ E foram os filhos de Israel, e fizeram isso : como o Senhor ordenara a Moisés e a Aarão, assim fizeram.

[[v2-12-29]]

^<<v2-12-29,29>>^ E aconteceu, à meia-noite, que o Senhor feriu a todos os primogênitos na terra do Egito, desde o primogênito de Faraó, que se sentava em seu trono, até ao primogênito do cativo que estava  no cárcere, e todos os primogênitos dos animais.

[[v2-12-30]]

^<<v2-12-30,30>>^ E Faraó levantou-se de noite, ele e todos os seus servos, e todos os egípcios; e havia grande clamor no Egito, porque não havia  casa em que não houvesse  um morto.

[[v2-12-31]]

^<<v2-12-31,31>>^ Então chamou a Moisés e a Aarão de noite, e disse: Levantai-vos, saí do meio do meu povo, tanto vós como os filhos de Israel; e ide, servi ao Senhor, como tendes dito.

[[v2-12-32]]

^<<v2-12-32,32>>^ Levai também convosco vossas ovelhas e vossas vacas, como tendes dito; e ide, e abençoai-me também a mim.

[[v2-12-33]]

^<<v2-12-33,33>>^ E os egípcios apertavam ao povo, apressando-se para lançá-los da terra; porque diziam: Todos seremos  mortos.

[[v2-12-34]]

^<<v2-12-34,34>>^ E o povo tomou a sua massa, antes que levedasse, e as suas amassadeiras atadas em seus vestidos, sobre seus ombros.

[[v2-12-35]]

^<<v2-12-35,35>>^ Fizeram pois os filhos de Israel conforme à palavra de Moisés, e pediram aos egípcios vasos de prata, e vasos de ouro, e vestidos.

[[v2-12-36]]

^<<v2-12-36,36>>^ E o Senhor deu graça ao povo em os olhos dos egípcios, e emprestavam-lhes e eles despojavam aos egípcios.

[[v2-12-37]]

^<<v2-12-37,37>>^ Assim partiram os filhos de Israel de Ramessés para Sucote, cousa de seiscentos mil de pé, somente de varões, sem contar os meninos.

[[v2-12-38]]

^<<v2-12-38,38>>^ E subiu também com eles uma mistura de gente, e ovelhas, e vacas, uma grande multidão de gado.

[[v2-12-39]]

^<<v2-12-39,39>>^ E cozeram bolos asmos da massa que levaram do Egito porque não se tinha levedado, porquanto foram lançados do Egito; e não se puderam deter, nem prepararam comida.

[[v2-12-40]]

^<<v2-12-40,40>>^ O tempo  que os filhos de Israel habitaram no Egito foi  de quatrocentos e trinta anos.

[[v2-12-41]]

^<<v2-12-41,41>>^ E aconteceu que, passados os quatrocentos e trinta anos, naquele mesmo dia, todos os exércitos do Senhor saíram da terra do Egito.

[[v2-12-42]]

^<<v2-12-42,42>>^ Esta noite se guardará ao Senhor, porque nela  os tirou da terra do Egito: esta é  a noite do Senhor, que devem guardar todos os filhos de Israel nas suas gerações.

[[v2-12-43]]

^<<v2-12-43,43>>^ Disse mais o Senhor a Moisés e a Aarão: Esta é  a ordenança da páscoa; nenhum filho do estrangeiro comerá dela.

[[v2-12-44]]

^<<v2-12-44,44>>^ Porém todo o servo de qualquer, comprado por dinheiro, depois que o houveres circuncidado então comerá dela.

[[v2-12-45]]

^<<v2-12-45,45>>^ O estrangeiro e o assalariado não comerão dela.

[[v2-12-46]]

^<<v2-12-46,46>>^ Numa casa se comerá; não levarás daquela carne fora da casa, nem dela quebrareis osso.

[[v2-12-47]]

^<<v2-12-47,47>>^ Toda a congregação de Israel o fará.

[[v2-12-48]]

^<<v2-12-48,48>>^ Porém se algum estrangeiro se hospedar contigo, e quiser celebrar a páscoa ao Senhor, seja-lhe circuncidado todo o macho, e então chegará a celebrá-la, e será como o natural da terra; mas nenhum incircunciso comerá dela.

[[v2-12-49]]

^<<v2-12-49,49>>^ Uma mesma lei haja para o natural, e para o estrangeiro que peregrinar entre vós.

[[v2-12-50]]

^<<v2-12-50,50>>^ E todos os filhos de Israel o fizeram: como o Senhor ordenara a Moisés e a Aarão, assim fizeram.

[[v2-12-51]]

^<<v2-12-51,51>>^ E aconteceu naquele mesmo dia que o Senhor tirou os filhos de Israel da terra do Egito, segundo os seus exércitos.

'''

xref:002-exodo/002-exodo-011.adoc#v2-11-0[&#60; Capítulo Anterior] | <<v2-12-0,Topo>> | xref:002-exodo/002-exodo-013.adoc#v2-13-0[Próximo Capítulo &#62;]