include::./index.adoc[]

[[v2-1-0]]
=== Êxodo, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-1-1]]

^<<v2-1-1,1>>^ ESTES pois são  os nomes dos filhos de Israel, que entraram no Egito com Jacó; cada um entrou com sua casa:

[[v2-1-2]]

^<<v2-1-2,2>>^ Rúben, Simeão, Levi, e Judá;

[[v2-1-3]]

^<<v2-1-3,3>>^ Issacar, Zebulom, e Benjamim;

[[v2-1-4]]

^<<v2-1-4,4>>^ Dã e Naftali, Gade e Aser.

[[v2-1-5]]

^<<v2-1-5,5>>^ Todas as almas, pois, que procederam da coxa de Jacó, foram setenta almas; José, porém, estava no Egito.

[[v2-1-6]]

^<<v2-1-6,6>>^ Sendo pois José falecido, e todos os seus irmãos, e toda aquela geração.

[[v2-1-7]]

^<<v2-1-7,7>>^ Os filhos de Israel frutificaram, e aumentaram muito, e multiplicaram-se, e foram fortalecidos grandemente; de maneira que a terra se encheu deles.

[[v2-1-8]]

^<<v2-1-8,8>>^ Depois levantou-se um novo rei sobre o Egito, que não conhecera a José;

[[v2-1-9]]

^<<v2-1-9,9>>^ O qual disse ao seu povo: Eis que o povo dos filhos de Israel é  muito, e mais poderoso do que nós.

[[v2-1-10]]

^<<v2-1-10,10>>^ Eia, usemos sabiamente para com ele, para que não se multiplique, e aconteça que, vindo guerra, ele também se ajunte com os nossos inimigos, e peleje contra nós, e suba da terra.

[[v2-1-11]]

^<<v2-1-11,11>>^ E puseram sobre eles maiorais de tributos, para os afligirem com suas cargas. Porque edificaram a Faraó cidades de tesouros, Pitom e Ramessés.

[[v2-1-12]]

^<<v2-1-12,12>>^ Mas quanto mais o afligiam, tanto mais se multiplicava, e tanto mais crescia; de maneira que se enfadavam por causa dos filhos de Israel.

[[v2-1-13]]

^<<v2-1-13,13>>^ E os egípcios faziam servir os filhos de Israel com dureza;

[[v2-1-14]]

^<<v2-1-14,14>>^ Assim lhes fizeram amargar a vida com dura servidão, em barro e em tijolos, e com todo o trabalho no campo; com todo o seu serviço, em que os serviam com dureza.

[[v2-1-15]]

^<<v2-1-15,15>>^ E o rei do Egito falou às parteiras das hebreias (das quais o nome de uma era Sifrá, e o nome da outra Puá),

[[v2-1-16]]

^<<v2-1-16,16>>^ E disse: Quando ajudardes no parto as hebreias, e as virdes sobre os assentos, se for filho, matai-o; mas se for filha, então  viva.

[[v2-1-17]]

^<<v2-1-17,17>>^ As parteiras, porém, temeram a Deus, e não fizeram como o rei do Egito lhes dissera, antes conservavam os meninos com vida.

[[v2-1-18]]

^<<v2-1-18,18>>^ Então o rei do Egito chamou as parteiras, e disse-lhes: Por que fizestes isto, que guardastes os meninos com vida?

[[v2-1-19]]

^<<v2-1-19,19>>^ E as parteiras disseram a Faraó: É que as mulheres hebreias não são  como as egípcias; porque são  vivas, e já têm dado à luz os filhos antes que a parteira venha a elas.

[[v2-1-20]]

^<<v2-1-20,20>>^ Portanto Deus fez bem às parteiras. E o povo se aumentou, e se fortaleceu muito.

[[v2-1-21]]

^<<v2-1-21,21>>^ E aconteceu que, como as parteiras temeram a Deus, estabeleceu-lhes casas.

[[v2-1-22]]

^<<v2-1-22,22>>^ Então ordenou Faraó a todo o seu povo, dizendo: A todos os filhos que nascerem lançareis no rio, mas a todas as filhas guardareis com vida.

'''

xref:001-genesis/001-genesis-050.adoc#v1-50-0[&#60; Capítulo Anterior] | <<v2-1-0,Topo>> | xref:002-exodo/002-exodo-002.adoc#v2-2-0[Próximo Capítulo &#62;]