include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-37-1]]

^<<v2-37-1,1>>^ FEZ também Bezaleel a arca de madeira de  cetim: o seu comprimento era  de dois côvados e meio; e a sua largura dum côvado e meio; e a sua altura dum côvado e meio.

[[v2-37-2]]

^<<v2-37-2,2>>^ E cobriu-a de ouro puro por dentro e por fora; e fez-lhe uma coroa de ouro ao redor;

[[v2-37-3]]

^<<v2-37-3,3>>^ E fundiu-lhe quatro argolas de ouro aos seus quatro cantos, num lado duas, e no outro lado duas argolas;

[[v2-37-4]]

^<<v2-37-4,4>>^ E fez varais de madeira de  cetim, e os cobriu de ouro;

[[v2-37-5]]

^<<v2-37-5,5>>^ E meteu os varais pelas argolas aos lados da arca, para levar a arca.

[[v2-37-6]]

^<<v2-37-6,6>>^ Fez também de ouro puro o propiciatório: o seu comprimento era  de dois côvados e meio, e a sua largura dum côvado e meio.

[[v2-37-7]]

^<<v2-37-7,7>>^ Fez também dois querubins de ouro; de obra batida os fez, às duas extremidades do propiciatório;

[[v2-37-8]]

^<<v2-37-8,8>>^ Um querubim a uma extremidade desta banda, e o outro querubim à outra  extremidade da outra banda: do mesmo  propiciatório fez sair  os querubins às duas extremidades deles.

[[v2-37-9]]

^<<v2-37-9,9>>^ E os querubins estendiam as asas por cima, cobrindo com as suas asas o propiciatório: e os seus rostos estavam defronte um do outro: os rostos dos querubins estavam virados  para o propiciatório.

[[v2-37-10]]

^<<v2-37-10,10>>^ Fez também a mesa de madeira de  cetim: o seu comprimento era  de dois côvados, e a sua largura dum côvado, e a sua altura dum côvado e meio.

[[v2-37-11]]

^<<v2-37-11,11>>^ E cobriu-a de ouro puro, e fez-lhe uma coroa de ouro ao redor.

[[v2-37-12]]

^<<v2-37-12,12>>^ Fez-lhe também uma moldura da largura duma mão ao redor: e fez uma coroa de ouro ao redor da sua moldura.

[[v2-37-13]]

^<<v2-37-13,13>>^ Fundiu-lhe também quatro argolas de ouro; e pôs as argolas aos quatro cantos que estavam  aos seus quatro pés.

[[v2-37-14]]

^<<v2-37-14,14>>^ Defronte da moldura estavam as argolas para os lugares dos varais, para levar a mesa.

[[v2-37-15]]

^<<v2-37-15,15>>^ Fez também os varais de madeira de  cetim, e os cobriu de ouro, para levar a mesa.

[[v2-37-16]]

^<<v2-37-16,16>>^ E fez os vasos que haviam de estar  sobre a mesa, os seus pratos, e as suas colheres, e as suas escudelas, e as suas cobertas, com que se haviam de cobrir, de ouro puro.

[[v2-37-17]]

^<<v2-37-17,17>>^ Fez também o castiçal de ouro puro: de obra batida fez este castiçal: o seu pé, e as suas canas, os seus copos, as suas maçãs, e as suas flores da mesma peça.

[[v2-37-18]]

^<<v2-37-18,18>>^ Seis canas saíam dos seus lados: três canas do castiçal, de um lado dele, e três canas do castiçal, do outro lado.

[[v2-37-19]]

^<<v2-37-19,19>>^ Numa cana estavam  três copos a modo de amêndoas, uma maçã e uma flor, e noutra cana três copos a modo de amêndoas, uma maçã e uma flor: assim para as seis canas que saíam do castiçal.

[[v2-37-20]]

^<<v2-37-20,20>>^ Mas no mesmo castiçal havia  quatro copos a modo de amêndoas com as suas maçãs e com as suas flores.

[[v2-37-21]]

^<<v2-37-21,21>>^ E era  uma maçã debaixo de duas canas do mesmo; e outra  maçã debaixo de duas canas do mesmo; e mais uma maçã debaixo de duas canas do mesmo: assim se fez  para as seis canas, que saíam dele.

[[v2-37-22]]

^<<v2-37-22,22>>^ As suas maçãs e as suas canas eram do mesmo: tudo era  uma obra batida de ouro puro.

[[v2-37-23]]

^<<v2-37-23,23>>^ E fez-lhe sete lâmpadas: os seus espevitadores e os seus apagadores eram  de ouro puro.

[[v2-37-24]]

^<<v2-37-24,24>>^ Dum talento de ouro puro o fez, e todos os seus vasos.

[[v2-37-25]]

^<<v2-37-25,25>>^ E fez o altar do incenso de madeira de  cetim: dum côvado era  o seu comprimento, e de um côvado a sua largura, quadrado; e de dois côvados a sua altura: dele mesmo eram feitas  as suas pontas.

[[v2-37-26]]

^<<v2-37-26,26>>^ E cobriu-o de ouro puro, a sua coberta, e as suas paredes ao redor, e as suas pontas: e fez-lhe uma coroa de ouro ao redor.

[[v2-37-27]]

^<<v2-37-27,27>>^ Fez-lhe também duas argolas de ouro debaixo da sua coroa, nos seus dois cantos, de ambos os seus lados, para os lugares dos varais, para levá-lo com eles.

[[v2-37-28]]

^<<v2-37-28,28>>^ E os varais fez de madeira de  cetim, e os cobriu de ouro.

[[v2-37-29]]

^<<v2-37-29,29>>^ Também fez o azeite santo da unção, e o incenso aromático, puro, de obra do perfumista.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]