include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-14-1]]

^<<v2-14-1,1>>^ ENTÃO falou o Senhor a Moisés, dizendo:

[[v2-14-2]]

^<<v2-14-2,2>>^ Fala aos filhos de Israel que voltem, e que acampem diante de Pi-Hairote, entre Migdol e o mar, diante de Baal-Zefom: em frente dele assentareis o campo junto ao mar.

[[v2-14-3]]

^<<v2-14-3,3>>^ Então Faraó dirá dos filhos de Israel: Estão embaraçados na terra, o deserto os encerrou.

[[v2-14-4]]

^<<v2-14-4,4>>^ E eu endurecerei o coração de Faraó, para que os persiga, e serei glorificado em Faraó em todo o seu exército, e saberão os egípcios que eu sou o Senhor. E eles fizeram assim.

[[v2-14-5]]

^<<v2-14-5,5>>^ Sendo pois anunciado ao rei do Egito que o povo fugia, mudou-se o coração de Faraó e dos seus servos contra o povo, e disseram: Por que fizemos isso havendo deixado ir a Israel, para que nos não sirva?

[[v2-14-6]]

^<<v2-14-6,6>>^ E aprontou o seu carro, e tomou consigo o seu povo;

[[v2-14-7]]

^<<v2-14-7,7>>^ E tomou seiscentos carros escolhidos, e todos os carros do Egito, e os capitães sobre eles todos.

[[v2-14-8]]

^<<v2-14-8,8>>^ Porque o Senhor endureceu o coração de Faraó, rei do Egito, para que perseguisse aos filhos de Israel; porém os filhos de Israel saíram com alta mão.

[[v2-14-9]]

^<<v2-14-9,9>>^ E os egípcios perseguiram-nos, todos os cavalos e carros de Faraó, e os seus cavaleiros, e o seu exército, e alcançaram-nos acampados junto ao mar, perto de Pi-Hairote, diante de Baal-Zefom.

[[v2-14-10]]

^<<v2-14-10,10>>^ E, chegando Faraó, os filhos de Israel levantaram seus olhos, e eis que os egípcios vinham atrás deles, e temeram muito; então os filhos de Israel clamaram ao Senhor.

[[v2-14-11]]

^<<v2-14-11,11>>^ E disseram a Moisés: Não havia sepulcros no Egito, para nos tirares de lá , para que morramos neste deserto? Por que nos fizeste isto, que nos tens tirado do Egito?

[[v2-14-12]]

^<<v2-14-12,12>>^ Não é  esta a palavra que te temos falado no Egito, dizendo: Deixa-nos, que sirvamos aos egípcios? pois que melhor nos fora  servir aos egípcios, do que morrermos no deserto.

[[v2-14-13]]

^<<v2-14-13,13>>^ Moisés, porém, disse ao povo: Não temais; estai quietos e vede o livramento do Senhor, que hoje vos fará; porque aos egípcios, que hoje vistes, nunca mais vereis para sempre:

[[v2-14-14]]

^<<v2-14-14,14>>^ O Senhor pelejará por vós e vos calareis.

[[v2-14-15]]

^<<v2-14-15,15>>^ Então disse o Senhor a Moisés: Por que clamas a mim? dize aos filhos de Israel que marchem.

[[v2-14-16]]

^<<v2-14-16,16>>^ E tu, levanta a tua vara, e estende a tua mão sobre o mar, e fende-o, para que os filhos de Israel passem pelo meio do mar em seco.

[[v2-14-17]]

^<<v2-14-17,17>>^ E eis que endurecerei o coração dos egípcios, para que entrem nele atrás deles; e eu serei glorificado em Faraó, e em todo o seu exército, nos seus carros e nos cavaleiros,

[[v2-14-18]]

^<<v2-14-18,18>>^ E os egípcios saberão que eu sou  o Senhor, quando for glorificado em Faraó, nos seus carros e nos seus cavaleiros.

[[v2-14-19]]

^<<v2-14-19,19>>^ E o anjo de Deus, que ia diante do exército de Israel, se retirou, e ia atrás deles: também a coluna de nuvem se retirou de diante deles, e se pôs atrás deles.

[[v2-14-20]]

^<<v2-14-20,20>>^ E ia entre o campo dos egípcios e o campo de Israel: e a nuvem era escuridade para aqueles, e para estes  esclarecia a noite: de maneira que em toda a noite não chegou um ao outro.

[[v2-14-21]]

^<<v2-14-21,21>>^ Então Moisés estendeu a sua mão sobre o mar, e o Senhor fez retirar o mar por um forte vento oriental toda aquela noite; e o mar tornou-se em seco, e as águas foram partidas.

[[v2-14-22]]

^<<v2-14-22,22>>^ E os filhos de Israel entraram pelo meio do mar em seco: e as águas foram- lhes como muro à sua direita e à sua esquerda.

[[v2-14-23]]

^<<v2-14-23,23>>^ E os egípcios seguiram-nos e entraram atrás deles todos os cavalos de Faraó, os seus carros e os seus cavaleiros, até ao meio do mar.

[[v2-14-24]]

^<<v2-14-24,24>>^ E aconteceu que, na vigília daquela manhã, o Senhor, na coluna de fogo e da nuvem, viu o campo dos egípcios: e alvoroçou o campo dos egípcios,

[[v2-14-25]]

^<<v2-14-25,25>>^ E tirou-lhes as rodas dos seus carros, e fê-los andar dificultosamente. Então disseram os egípcios: Fujamos da face de Israel, porque o Senhor por eles peleja contra os egípcios.

[[v2-14-26]]

^<<v2-14-26,26>>^ E disse o Senhor a Moisés: Estende a tua mão sobre o mar, para que as águas tornem sobre os egípcios, sobre os seus carros e sobre os seus cavaleiros.

[[v2-14-27]]

^<<v2-14-27,27>>^ Então Moisés estendeu a sua mão sobre o mar e o mar retomou a sua força ao amanhecer, e os egípcios fugiram ao seu encontro: e o Senhor derribou os egípcios no meio do mar,

[[v2-14-28]]

^<<v2-14-28,28>>^ Porque as águas, tornando, cobriram os carros e os cavaleiros de todo o exército de Faraó, que os haviam seguido no mar: nem ainda um deles ficou.

[[v2-14-29]]

^<<v2-14-29,29>>^ Mas os filhos de Israel foram pelo meio do mar seco: e as águas foram-lhes como muro à sua mão direita e à sua esquerda.

[[v2-14-30]]

^<<v2-14-30,30>>^ Assim o Senhor salvou Israel naquele dia da mão dos egípcios: e Israel viu os egípcios mortos na praia do mar.

[[v2-14-31]]

^<<v2-14-31,31>>^ E viu Israel a grande mão que o Senhor mostrara aos egípcios; e temeu o povo ao Senhor, e creram no Senhor e em Moisés, seu servo.

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]