include::./index.adoc[]

[[v2-39-0]]
=== Êxodo, 39
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-39-1]]

^<<v2-39-1,1>>^ FIZERAM também os vestidos do ministério, para ministrar no santuário, de azul, e de púrpura e de carmesim: também fizeram os vestidos santos, para Aarão, como o Senhor ordenara a Moisés.

[[v2-39-2]]

^<<v2-39-2,2>>^ Assim fez o éfode de ouro, de azul, e de púrpura, e de carmesim e de linho fino torcido.

[[v2-39-3]]

^<<v2-39-3,3>>^ E estenderam as lâminas de ouro, e as cortaram em fios, para entretecer entre o azul, e entre a púrpura, e entre o carmesim, e entre o linho fino da obra mais esmerada.

[[v2-39-4]]

^<<v2-39-4,4>>^ Fizeram nele ombreiras que se ajuntassem: às suas duas pontas se ajuntavam.

[[v2-39-5]]

^<<v2-39-5,5>>^ E o cinto de artifício do éfode, que estava  sobre ele, era  conforme à sua obra, da mesma peça, de ouro, de azul, e de púrpura, e de carmesim, e de linho fino torcido, como o Senhor ordenara a Moisés.

[[v2-39-6]]

^<<v2-39-6,6>>^ Também prepararam as pedras sardônicas, engastadas em ouro, lavradas com gravuras de selo, com os nomes dos filhos de Israel.

[[v2-39-7]]

^<<v2-39-7,7>>^ E as pôs sobre as ombreiras do éfode por  pedras de memória para os filhos de Israel, como o Senhor ordenara a Moisés.

[[v2-39-8]]

^<<v2-39-8,8>>^ Fez também o peitoral de obra de artífice, como a obra de éfode, de ouro, de azul, e de púrpura, e de carmesim, e de linho fino torcido.

[[v2-39-9]]

^<<v2-39-9,9>>^ Quadrado era; dobrado fizeram o peitoral: o seu comprimento era  de um palmo, e a sua largura de um palmo dobrado.

[[v2-39-10]]

^<<v2-39-10,10>>^ E engastaram nele quatro ordens de pedras: uma ordem de uma sárdia, de um topázio, e de um carbúnculo; esta é  a primeira ordem:

[[v2-39-11]]

^<<v2-39-11,11>>^ E a segunda ordem de uma esmeralda, de uma safira e de um diamante:

[[v2-39-12]]

^<<v2-39-12,12>>^ E a terceira ordem de um jacinto, de uma ágata, e de uma ametista:

[[v2-39-13]]

^<<v2-39-13,13>>^ E a quarta ordem de uma turquesa, e de uma sardônica, e de um jaspe, engastadas nos seus engastes de ouro.

[[v2-39-14]]

^<<v2-39-14,14>>^ Estas pedras pois eram segundo os nomes dos filhos de Israel, doze segundo os seus nomes; de gravura de selo, cada uma com o seu nome, segundo as doze tribos.

[[v2-39-15]]

^<<v2-39-15,15>>^ Também fizeram para o peitoral cadeiazinhas de igual medida, obra de trança, e de ouro puro.

[[v2-39-16]]

^<<v2-39-16,16>>^ E fizeram dois engastes de ouro e duas argolas de ouro; e puseram as duas argolas nas duas extremidades do peitoral.

[[v2-39-17]]

^<<v2-39-17,17>>^ E puseram as duas cadeiazinhas de trança de ouro nas duas argolas, nas duas extremidades do peitoral.

[[v2-39-18]]

^<<v2-39-18,18>>^ E as outras  duas pontas das duas cadeiazinhas  de trança puseram nos dois engastes: e as puseram sobre as ombreiras do éfode, defronte dele.

[[v2-39-19]]

^<<v2-39-19,19>>^ Fizeram também duas argolas de ouro, que puseram nas outras  duas extremidades do peitoral, na sua borda que estava  junto ao éfode por dentro.

[[v2-39-20]]

^<<v2-39-20,20>>^ Fizeram mais duas argolas de ouro, que puseram nas duas ombreiras do éfode, debaixo, defronte dele, defronte da sua juntura, sobre o cinto de artifício do éfode.

[[v2-39-21]]

^<<v2-39-21,21>>^ E ligaram o peitoral com as suas argolas às argolas do éfode com um cordão de azul, para que estivesse sobre o cinto de artifício do éfode, e o peitoral não se apartasse do éfode, como o Senhor ordenara a Moisés.

[[v2-39-22]]

^<<v2-39-22,22>>^ E fez o manto do éfode de obra tecida, todo de azul.

[[v2-39-23]]

^<<v2-39-23,23>>^ E o colar do manto estava  no meio dele, como colar de cota de malha: este colar tinha uma borda em volta, para que se não rompesse.

[[v2-39-24]]

^<<v2-39-24,24>>^ E nas bordas do manto fizeram romãs de azul, e de púrpura, e de carmesim, a fio  torcido.

[[v2-39-25]]

^<<v2-39-25,25>>^ Fizeram também as campainhas de ouro puro, pondo as campainhas no meio das romãs nas bordas da capa, em roda, entre as romãs:

[[v2-39-26]]

^<<v2-39-26,26>>^ Uma campainha e uma romã, outra  campainha e outra  romã, nas bordas do manto à roda: para ministrar, como o Senhor ordenara a Moisés.

[[v2-39-27]]

^<<v2-39-27,27>>^ Fizeram também as túnicas de linho fino, de obra tecida, para Aarão e para seus filhos,

[[v2-39-28]]

^<<v2-39-28,28>>^ E a mitra de linho fino, e o ornato das tiaras de linho fino, e os calções de linho fino torcido,

[[v2-39-29]]

^<<v2-39-29,29>>^ E o cinto de linho fino torcido, e de azul, e de púrpura, e de carmesim, de obra de bordador, como o Senhor ordenara a Moisés.

[[v2-39-30]]

^<<v2-39-30,30>>^ Fizeram também a folha da coroa de santidade de ouro puro, e nela escreveram o escrito como de gravura de selo: Santidade ao Senhor .

[[v2-39-31]]

^<<v2-39-31,31>>^ E ataram-na com um cordão de azul, para a atar à mitra em cima, como o Senhor ordenara a Moisés.

[[v2-39-32]]

^<<v2-39-32,32>>^ Assim se acabou toda a obra do tabernáculo da tenda da congregação; e os filhos de Israel fizeram conforme a tudo o que o Senhor ordenara a Moisés; assim o fizeram.

[[v2-39-33]]

^<<v2-39-33,33>>^ Depois trouxeram a Moisés o tabernáculo, a tenda e todos os seus vasos; os seus colchetes, as suas tábuas, os seus varais, e as suas colunas, e as suas bases;

[[v2-39-34]]

^<<v2-39-34,34>>^ E a coberta de peles de carneiro tintas de vermelho, e a coberta de peles de texugos, e o véu da coberta;

[[v2-39-35]]

^<<v2-39-35,35>>^ A arca do testemunho, e os seus varais, e o propiciatório;

[[v2-39-36]]

^<<v2-39-36,36>>^ A mesa com todos os seus vasos, e os pães da proposição;

[[v2-39-37]]

^<<v2-39-37,37>>^ O castiçal puro com suas lâmpadas, as lâmpadas da ordenança, e todos os seus vasos, e o azeite para a luminária;

[[v2-39-38]]

^<<v2-39-38,38>>^ Também o altar de ouro, e o azeite da unção, e o incenso aromático, e a coberta da porta da tenda;

[[v2-39-39]]

^<<v2-39-39,39>>^ O altar de cobre, e o seu crivo de cobre, os seus varais, e todos os seus vasos, a pia, e a sua base;

[[v2-39-40]]

^<<v2-39-40,40>>^ As cortinas do pátio, as suas colunas, e as suas bases, e a coberta da porta do pátio, as suas cordas, e os seus pregos, e todos os vasos do serviço do tabernáculo, para a tenda da congregação;

[[v2-39-41]]

^<<v2-39-41,41>>^ Os vestidos do ministério para ministrar no santuário; os vestidos santos de Aarão o sacerdote, e os vestidos dos seus filhos, para administrarem o sacerdócio.

[[v2-39-42]]

^<<v2-39-42,42>>^ Conforme a tudo o que o Senhor ordenara a Moisés, assim fizeram os filhos de Israel toda a obra.

[[v2-39-43]]

^<<v2-39-43,43>>^ Viu pois Moisés toda a obra, e eis que a tinham feito; como o Senhor ordenara, assim a fizeram: então Moisés os abençoou.

'''

xref:002-exodo/002-exodo-038.adoc#v2-38-0[&#60; Capítulo Anterior] | <<v2-39-0,Topo>> | xref:002-exodo/002-exodo-040.adoc#v2-40-0[Próximo Capítulo &#62;]