include::./index.adoc[]

[[v2-28-0]]
=== Êxodo, 28
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-28-1]]

^<<v2-28-1,1>>^ DEPOIS tu farás chegar a ti teu irmão Aarão, e seus filhos com ele, do meio dos filhos de Israel, para me administrarem o ofício sacerdotal: a saber , Aarão, Nadabe e Abiú, Eleazar e Itamar, os filhos de Aarão.

[[v2-28-2]]

^<<v2-28-2,2>>^ E farás vestidos santos a Aarão teu irmão, para glória e ornamento.

[[v2-28-3]]

^<<v2-28-3,3>>^ Falarás também a todos os que são  sábios de coração, a quem eu tenha enchido do espírito da sabedoria, que façam vestidos a Aarão para santificá-lo; para que me administre o ofício sacerdotal.

[[v2-28-4]]

^<<v2-28-4,4>>^ Estes pois são  os vestidos que farão: um peitoral, e um éfode, e um manto, e uma túnica bordada, uma mitra, e um cinto: farão pois vestidos santos a Aarão teu irmão, e a seus filhos, para me administrarem o ofício sacerdotal.

[[v2-28-5]]

^<<v2-28-5,5>>^ E tomarão o ouro, e o azul, e a púrpura, e o carmesim, e o linho fino,

[[v2-28-6]]

^<<v2-28-6,6>>^ E farão o éfode de ouro, e de azul, e de púrpura, e de carmesim, e de linho fino torcido, de obra esmerada.

[[v2-28-7]]

^<<v2-28-7,7>>^ Terá duas ombreiras, que se unam às suas duas pontas, e assim  se unirá.

[[v2-28-8]]

^<<v2-28-8,8>>^ E o cinto de obra esmerada do seu éfode, que estará  sobre ele, será da sua mesma obra, da mesma obra de ouro, de azul, e de púrpura, e de carmesim, e de linho fino torcido.

[[v2-28-9]]

^<<v2-28-9,9>>^ E tomarás duas pedras sardônicas, e lavrarás nelas os nomes dos filhos de Israel,

[[v2-28-10]]

^<<v2-28-10,10>>^ Seis dos seus nomes numa pedra, e os outros  seis nomes na outra pedra, segundo as suas gerações;

[[v2-28-11]]

^<<v2-28-11,11>>^ Conforme à obra do lapidário, como  o lavor de selos lavrarás estas duas pedras, com os nomes dos filhos de Israel: engastadas ao redor em ouro as farás.

[[v2-28-12]]

^<<v2-28-12,12>>^ E porás as duas pedras nas ombreiras do éfode, por  pedras de memória para os filhos de Israel: e Aarão levará os seus nomes sobre ambos os seus ombros, para memória diante do Senhor.

[[v2-28-13]]

^<<v2-28-13,13>>^ Farás também engastes de ouro,

[[v2-28-14]]

^<<v2-28-14,14>>^ E duas cadeiazinhas de ouro puro: de igual medida, de obra de fieira as farás: e as cadeiazinhas de fieira porás nos engastes.

[[v2-28-15]]

^<<v2-28-15,15>>^ Farás também o peitoral do juízo de obra esmerada, conforme à obra do éfode o farás: de ouro, de azul, e de púrpura, e de carmesim, e de linho fino torcido o farás.

[[v2-28-16]]

^<<v2-28-16,16>>^ Quadrado e  dobrado, será de um palmo o seu comprimento, e de um palmo a sua largura;

[[v2-28-17]]

^<<v2-28-17,17>>^ E o encherás de pedras de engaste, com quatro ordens de pedras: a ordem de uma sárdia, de um topázio, e de um carbúnculo: esta será  a primeira ordem:

[[v2-28-18]]

^<<v2-28-18,18>>^ E a segunda ordem será  de uma esmeralda, de uma safira, e de um diamante:

[[v2-28-19]]

^<<v2-28-19,19>>^ E a terceira ordem será  de um jacinto, de uma ágata, e de uma ametista:

[[v2-28-20]]

^<<v2-28-20,20>>^ E a quarta ordem será  de uma turquesa, e de uma sardônica, e de um jaspe; engastadas em ouro serão  nos seus engastes.

[[v2-28-21]]

^<<v2-28-21,21>>^ E serão aquelas pedras segundo os nomes dos filhos de Israel, doze segundo os seus nomes: serão esculpidas como selos, cada uma com o seu nome, para as doze tribos.

[[v2-28-22]]

^<<v2-28-22,22>>^ Também farás para o peitoral cadeiazinhas de igual medida da obra de trança de ouro puro.

[[v2-28-23]]

^<<v2-28-23,23>>^ Também farás para o peitoral dois anéis de ouro, e porás os dois anéis nas extremidades do peitoral.

[[v2-28-24]]

^<<v2-28-24,24>>^ Então meterás as duas cadeiazinhas  de fieira de ouro nos dois anéis, nas extremidades do peitoral:

[[v2-28-25]]

^<<v2-28-25,25>>^ E as duas pontas das duas cadeiazinhas  de fieira meterás nos dois engastes, e as porás nas ombreiras do éfode, na frente dele.

[[v2-28-26]]

^<<v2-28-26,26>>^ Farás também dois anéis de ouro, e os porás nas duas extremidades do peitoral, na sua borda que estiver  junto ao éfode por dentro.

[[v2-28-27]]

^<<v2-28-27,27>>^ Farás também dois anéis de ouro, que porás nas duas ombreiras do éfode, abaixo, na frente dele, perto da sua juntura, sobre o cinto de obra esmerada do éfode.

[[v2-28-28]]

^<<v2-28-28,28>>^ E ligarão o peitoral com os seus anéis aos anéis do éfode por cima com um cordão de azul, para que esteja sobre o cinto de obra esmerada do éfode; e nunca se separará o peitoral do éfode.

[[v2-28-29]]

^<<v2-28-29,29>>^ Assim Aarão levará os nomes dos filhos de Israel no peitoral do juízo sobre o seu coração, quando entrar no santuário, para memória diante do Senhor continuamente.

[[v2-28-30]]

^<<v2-28-30,30>>^ Também porás no peitoral do juízo Urim e Tumim, para que estejam sobre o coração de Aarão, quando entrar diante do Senhor: assim Aarão levará o juízo dos filhos de Israel sobre o seu coração diante do Senhor continuamente.

[[v2-28-31]]

^<<v2-28-31,31>>^ Também farás o manto do éfode todo de azul.

[[v2-28-32]]

^<<v2-28-32,32>>^ E o colar da cabeça estará no meio dele: este colar terá uma borda de obra tecida ao redor: como colar de cota de malha será nele, para que se não rompa.

[[v2-28-33]]

^<<v2-28-33,33>>^ E nas suas bordas farás romãs de azul, e de púrpura, e de carmesim, ao redor das suas bordas; e campainhas de ouro no meio delas ao redor.

[[v2-28-34]]

^<<v2-28-34,34>>^ Uma campainha de ouro, e uma romã, outra  campainha de ouro, e outra  romã, haverá nas bordas do manto ao redor,

[[v2-28-35]]

^<<v2-28-35,35>>^ E estará sobre Aarão quando ministrar, para que se ouça o seu sonido, quando entrar no santuário diante do Senhor, e quando sair, para que não morra.

[[v2-28-36]]

^<<v2-28-36,36>>^ Também farás uma lâmina de ouro puro, e nela gravarás à maneira de gravuras de selos: Santidade ao Senhor.

[[v2-28-37]]

^<<v2-28-37,37>>^ E atá-la-ás com um cordão de azul, de maneira que esteja na mitra, sobre a frente da mitra estará.

[[v2-28-38]]

^<<v2-28-38,38>>^ E estará sobre a testa de Aarão, para que Aarão leve a iniquidade das cousas santas, que os filhos de Israel santificarem em todas as ofertas de suas cousas santas; e estará continuamente na sua testa, para que tenham aceitação perante o Senhor.

[[v2-28-39]]

^<<v2-28-39,39>>^ Também farás túnica de linho fino: também farás uma mitra de linho fino: mas o cinto farás de obra de bordador.

[[v2-28-40]]

^<<v2-28-40,40>>^ Também farás túnicas aos filhos de Aarão, e far-lhes-ás cintos: também lhes farás tiaras, para glória e ornamento.

[[v2-28-41]]

^<<v2-28-41,41>>^ E vestirás com eles a Aarão teu irmão, e também seus filhos: e os ungirás e consagrarás, e os santificarás, para que me administrem o sacerdócio.

[[v2-28-42]]

^<<v2-28-42,42>>^ Faze-lhes também calções de linho, para cobrirem a carne nua: serão dos lombos até às coxas.

[[v2-28-43]]

^<<v2-28-43,43>>^ E estarão sobre Aarão e sobre seus filhos, quando entrarem na tenda da congregação, ou quando chegarem ao altar para ministrar no santuário, para que não levem iniquidade, e morram; isto será  estatuto perpétuo para ele e para a sua semente depois dele.

'''

xref:002-exodo/002-exodo-027.adoc#v2-27-0[&#60; Capítulo Anterior] | <<v2-28-0,Topo>> | xref:002-exodo/002-exodo-029.adoc#v2-29-0[Próximo Capítulo &#62;]