include::./index.adoc[]

[[v2-9-0]]
=== Êxodo, 9
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-9-1]]

^<<v2-9-1,1>>^ DEPOIS o Senhor disse a Moisés: Entra a Faraó, e dize-lhe: Assim diz o Senhor, o Deus dos hebreus: Deixa ir o meu povo, para que me sirva.

[[v2-9-2]]

^<<v2-9-2,2>>^ Porque se recusares deixá-los ir, e ainda por força os detiveres,

[[v2-9-3]]

^<<v2-9-3,3>>^ Eis que a mão do Senhor será sobre teu gado, que está  no campo, sobre os cavalos, sobre os jumentos, sobre os camelos, sobre os bois, e sobre as ovelhas, com pestilência gravíssima.

[[v2-9-4]]

^<<v2-9-4,4>>^ E o Senhor fará separação entre o gado dos israelitas, e o gado dos egípcios, para que nada morra de tudo o que for dos filhos de Israel.

[[v2-9-5]]

^<<v2-9-5,5>>^ E o Senhor assinalou certo tempo, dizendo: Amanhã fará o Senhor esta cousa na terra.

[[v2-9-6]]

^<<v2-9-6,6>>^ E o Senhor fez esta cousa no dia seguinte, e todo o gado dos egípcios morreu; porém do gado dos filhos de Israel não morreu nenhum.

[[v2-9-7]]

^<<v2-9-7,7>>^ E Faraó enviou a ver , e eis que do gado de Israel não morrera nenhum; porém o coração de Faraó se endureceu, e não deixou ir o povo.

[[v2-9-8]]

^<<v2-9-8,8>>^ Então disse o Senhor a Moisés e a Aarão: Tomai vossos punhos cheios da cinza do forno, e Moisés a espalhe para o céu diante dos olhos de Faraó;

[[v2-9-9]]

^<<v2-9-9,9>>^ E tornar-se-á em pó miúdo sobre toda a terra do Egito, e se tornará em sarna, que arrebente em úlceras nos homens e no gado, por toda a terra do Egito.

[[v2-9-10]]

^<<v2-9-10,10>>^ E eles tomaram a cinza do forno, e puseram-se diante de Faraó, e Moisés a espalhou para o céu; e tornou-se em sarna, que arrebentava em úlceras nos homens e no gado;

[[v2-9-11]]

^<<v2-9-11,11>>^ De maneira que os magos não podiam parar diante de Moisés, por causa da sarna; porque havia sarna em os magos, e em todos os egípcios.

[[v2-9-12]]

^<<v2-9-12,12>>^ Porém o Senhor endureceu o coração de Faraó, e não os ouviu, como o Senhor tinha dito a Moisés.

[[v2-9-13]]

^<<v2-9-13,13>>^ Então disse o Senhor a Moisés: Levanta-te pela manhã cedo e põe-te diante de Faraó, e dize-lhe: Assim diz o Senhor, o Deus dos hebreus: Deixa ir o meu povo para que me sirva;

[[v2-9-14]]

^<<v2-9-14,14>>^ Porque esta vez enviarei todas as minhas pragas sobre o teu coração, e sobre os teus servos, e sobre o teu povo, para que saibas que não há  outro como eu em toda a terra.

[[v2-9-15]]

^<<v2-9-15,15>>^ Porque agora tenho estendido minha mão, para te ferir a ti e ao teu povo com pestilência, e para que sejas destruído da terra;

[[v2-9-16]]

^<<v2-9-16,16>>^ Mas deveras para isto te mantive, para mostrar o meu poder em ti, e para que o meu nome seja anunciado em toda a terra.

[[v2-9-17]]

^<<v2-9-17,17>>^ Tu ainda te levantas contra o meu povo, para não os deixar ir?

[[v2-9-18]]

^<<v2-9-18,18>>^ Eis que amanhã por este tempo farei chover saraiva mui grave, qual nunca houve no Egito, desde o dia em que foi fundado até agora.

[[v2-9-19]]

^<<v2-9-19,19>>^ Agora pois envia, recolhe o teu gado e tudo o que tens no campo; todo o homem e animal, que for achado no campo, e não for recolhido à casa, a saraiva cairá sobre eles, e morrerão.

[[v2-9-20]]

^<<v2-9-20,20>>^ Quem dos servos de Faraó temia a palavra do Senhor, fez fugir os seus servos e o seu gado para as casas;

[[v2-9-21]]

^<<v2-9-21,21>>^ Mas aquele que não tinha aplicado a palavra do Senhor ao seu coração, deixou os seus servos e o seu gado no campo.

[[v2-9-22]]

^<<v2-9-22,22>>^ Então disse o Senhor a Moisés: Estende a tua mão para o céu, e haverá saraiva em toda a terra do Egito, sobre os homens e sobre o gado, e sobre toda a erva do campo na terra do Egito.

[[v2-9-23]]

^<<v2-9-23,23>>^ E Moisés estendeu a sua vara para o céu, e o Senhor deu trovões e saraiva, e fogo corria pela terra; e o Senhor fez chover saraiva sobre a terra do Egito.

[[v2-9-24]]

^<<v2-9-24,24>>^ E havia saraiva e fogo misturado entre a saraiva, mui grave, qual nunca houve em toda a terra do Egito, desde que veio a ser uma nação.

[[v2-9-25]]

^<<v2-9-25,25>>^ E a saraiva feriu, em toda a terra do Egito, tudo quanto havia  no campo, desde os homens até aos animais; também a saraiva feriu toda a erva do campo, e quebrou todas as árvores do campo.

[[v2-9-26]]

^<<v2-9-26,26>>^ Somente na terra de Gósen, onde estavam  os filhos de Israel, não havia saraiva.

[[v2-9-27]]

^<<v2-9-27,27>>^ Então Faraó mandou chamar a Moisés e a Aarão, e disse-lhes: Esta vez pequei; o Senhor é justo, mas eu e o meu povo ímpios.

[[v2-9-28]]

^<<v2-9-28,28>>^ Orai ao Senhor (pois que basta) para que não haja mais trovões de Deus nem saraiva; e eu vos deixarei ir, e não ficareis mais aqui.

[[v2-9-29]]

^<<v2-9-29,29>>^ Então lhe disse Moisés: Em saindo da cidade estenderei minhas mãos ao Senhor: os trovões cessarão, e não haverá mais saraiva; para que saibas que a terra é do Senhor.

[[v2-9-30]]

^<<v2-9-30,30>>^ Todavia, quanto a ti e aos teus servos, eu sei que ainda não temereis diante do Senhor Deus.

[[v2-9-31]]

^<<v2-9-31,31>>^ E o linho e a cevada foram feridos, porque a cevada já estava  na espiga, e o linho na cana,

[[v2-9-32]]

^<<v2-9-32,32>>^ Mas o trigo e o centeio não foram feridos, porque estavam  cobertos.

[[v2-9-33]]

^<<v2-9-33,33>>^ Saiu pois Moisés de Faraó, da cidade, e estendeu as suas mãos ao Senhor: e cessaram os trovões e a saraiva, e a chuva não caiu mais  sobre a terra.

[[v2-9-34]]

^<<v2-9-34,34>>^ Vendo Faraó que cessou a chuva, e a saraiva, e os trovões, continuou a pecar: e agravou o seu coração, ele e os seus servos.

[[v2-9-35]]

^<<v2-9-35,35>>^ Assim o coração de Faraó se endureceu, e não deixou ir os filhos de Israel, como o Senhor tinha dito por Moisés.

'''

xref:002-exodo/002-exodo-008.adoc#v2-8-0[&#60; Capítulo Anterior] | <<v2-9-0,Topo>> | xref:002-exodo/002-exodo-010.adoc#v2-10-0[Próximo Capítulo &#62;]