include::./index.adoc[]

[[v2-30-0]]
=== Êxodo, 30
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-30-1]]

^<<v2-30-1,1>>^ E FARÁS um altar para queimar o incenso: de madeira de cetim o farás.

[[v2-30-2]]

^<<v2-30-2,2>>^ O seu comprimento será  dum côvado, e a sua largura dum côvado; será quadrado, e de dois côvados a sua altura; dele mesmo serão as suas pontas.

[[v2-30-3]]

^<<v2-30-3,3>>^ E com ouro puro o forrarás, o seu teto e as suas paredes ao redor, e as suas pontas; e lhe farás uma coroa de ouro ao redor.

[[v2-30-4]]

^<<v2-30-4,4>>^ Também lhe farás duas argolas de ouro debaixo da sua coroa; aos dois lados as farás, de ambas as bandas: e serão para lugares dos varais, com que será levado.

[[v2-30-5]]

^<<v2-30-5,5>>^ E os varais farás de madeira de cetim, e os forrarás com ouro.

[[v2-30-6]]

^<<v2-30-6,6>>^ E o porás diante do véu que está  diante da arca do testemunho, diante do propiciatório, que está  sobre o testemunho, onde me ajuntarei contigo.

[[v2-30-7]]

^<<v2-30-7,7>>^ E Aarão sobre ele queimará o incenso das especiarias; cada manhã, quando põe em ordem as lâmpadas, o queimará.

[[v2-30-8]]

^<<v2-30-8,8>>^ E, acendendo Aarão as lâmpadas à tarde, o queimará: este será  incenso contínuo perante o Senhor pelas vossas gerações.

[[v2-30-9]]

^<<v2-30-9,9>>^ Não oferecereis sobre ele incenso estranho, nem holocausto, nem oferta: nem tão pouco derramareis sobre ele libações.

[[v2-30-10]]

^<<v2-30-10,10>>^ E uma vez no ano Aarão fará expiação sobre as pontas do altar com o sangue do sacrifício das expiações: uma vez no ano fará expiação sobre ele pelas vossas gerações: santíssimo é  ao Senhor.

[[v2-30-11]]

^<<v2-30-11,11>>^ Falou mais o Senhor a Moisés, dizendo:

[[v2-30-12]]

^<<v2-30-12,12>>^ Quando tomares a soma dos filhos de Israel, conforme à sua conta, cada um deles  dará ao Senhor o resgate da sua alma, quando os contares; para que não haja entre eles praga alguma, quando os contares.

[[v2-30-13]]

^<<v2-30-13,13>>^ Isto dará todo aquele que passar ao arrolamento: A metade dum siclo, segundo o siclo do santuário (este siclo é de vinte óbolos): a metade dum siclo é  a oferta ao Senhor.

[[v2-30-14]]

^<<v2-30-14,14>>^ Qualquer que entrar no arrolamento, de vinte anos e acima, dará a oferta ao Senhor.

[[v2-30-15]]

^<<v2-30-15,15>>^ O rico não aumentará, e o pobre não diminuirá da metade do siclo, quando derem a oferta ao Senhor, para fazer expiação por vossas almas.

[[v2-30-16]]

^<<v2-30-16,16>>^ E tomarás o dinheiro das expiações dos filhos de Israel, e o darás ao serviço da tenda da congregação; e será para memória aos filhos de Israel diante do Senhor, para fazer expiação por vossas almas.

[[v2-30-17]]

^<<v2-30-17,17>>^ E falou o Senhor a Moisés, dizendo:

[[v2-30-18]]

^<<v2-30-18,18>>^ Farás também uma pia de cobre com a sua base de cobre, para lavar; e a porás entre a tenda da congregação e o altar, e deitarás água nela.

[[v2-30-19]]

^<<v2-30-19,19>>^ E Aarão e seus filhos nela lavarão as suas mãos e os seus pés.

[[v2-30-20]]

^<<v2-30-20,20>>^ Quando entrarem na tenda da congregação, lavar-se-ão com água, para que não morram, ou quando se chegarem ao altar para ministrar, para acender a oferta queimada ao Senhor.

[[v2-30-21]]

^<<v2-30-21,21>>^ Lavarão pois as suas mãos e os seus pés, para que não morram: e isto  lhes será por estatuto perpétuo a ele e à sua semente nas suas gerações.

[[v2-30-22]]

^<<v2-30-22,22>>^ Falou mais o Senhor a Moisés, dizendo:

[[v2-30-23]]

^<<v2-30-23,23>>^ Tu pois toma para ti das principais especiarias, da mais pura mirra quinhentos siclos , e de canela aromática a metade, a saber  duzentos e cinquenta siclos  e de cálamo aromático duzentos e cinquenta siclos ,

[[v2-30-24]]

^<<v2-30-24,24>>^ E de cássia quinhentos siclos , segundo o siclo do santuário, e de azeite de oliveiras um him.

[[v2-30-25]]

^<<v2-30-25,25>>^ E disto farás o azeite da santa unção, o perfume composto segundo a obra do perfumista: este  será o azeite da santa unção.

[[v2-30-26]]

^<<v2-30-26,26>>^ E com ele ungirás a tenda da congregação, e a arca do testemunho,

[[v2-30-27]]

^<<v2-30-27,27>>^ E a mesa com todos os seus vasos, e o castiçal com os seus vasos, e o altar do incenso,

[[v2-30-28]]

^<<v2-30-28,28>>^ E o altar do holocausto com todos os seus vasos, e a pia com a sua base.

[[v2-30-29]]

^<<v2-30-29,29>>^ Assim santificarás estas cousas, para que sejam santíssimas: tudo o que tocar nelas será santo.

[[v2-30-30]]

^<<v2-30-30,30>>^ Também ungirás a Aarão e seus filhos, e os santificarás para me administrarem o sacerdócio.

[[v2-30-31]]

^<<v2-30-31,31>>^ E falarás aos filhos de Israel, dizendo: Este me será o azeite da santa unção nas vossas gerações.

[[v2-30-32]]

^<<v2-30-32,32>>^ Não se ungirá com ele a carne do homem, nem fareis outro  semelhante conforme à sua composição: santo é , e será santo para vós.

[[v2-30-33]]

^<<v2-30-33,33>>^ O homem que compuser tal perfume  como este, ou que dele puser sobre um estranho, será extirpado dos seus povos.

[[v2-30-34]]

^<<v2-30-34,34>>^ Disse mais o Senhor a Moisés: Toma especiarias aromáticas, estoraque, e onicha, e gálbano; estas  especiarias aromáticas  e o incenso puro de igual peso ;

[[v2-30-35]]

^<<v2-30-35,35>>^ E disto farás incenso, um perfume segundo a arte do perfumista, temperado, puro e  santo;

[[v2-30-36]]

^<<v2-30-36,36>>^ E dele moendo o pisarás, e dele porás diante do testemunho, na tenda da congregação, onde eu virei a ti: cousa santíssima vos será.

[[v2-30-37]]

^<<v2-30-37,37>>^ Porém o incenso que farás conforme à composição deste, não o fareis para vós mesmos: santo será para o Senhor.

[[v2-30-38]]

^<<v2-30-38,38>>^ O homem que fizer tal como este para cheirar, será extirpado do seu povo.

'''

xref:002-exodo/002-exodo-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodo/002-exodo-031.adoc#v2-31-0[Próximo Capítulo &#62;]