include::./index.adoc[]

[[v2-13-0]]
=== Êxodo, 13
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-13-1]]

^<<v2-13-1,1>>^ ENTÃO falou o Senhor a Moisés, dizendo:

[[v2-13-2]]

^<<v2-13-2,2>>^ Santifica-me todo o primogênito, o que abrir toda a madre entre os filhos de Israel, de homens e de animais; porque  meu é.

[[v2-13-3]]

^<<v2-13-3,3>>^ E Moisés disse ao povo: Lembrai-vos deste mesmo dia, em que saístes do Egito, da casa da servidão; pois com mão forte o Senhor vos tirou daqui: portanto não comereis pão levedado.

[[v2-13-4]]

^<<v2-13-4,4>>^ Hoje, no mês de abibe, vós saís.

[[v2-13-5]]

^<<v2-13-5,5>>^ E acontecerá que, quando o Senhor te houver metido na terra dos cananeus, e dos heteus, e dos amorreus, e dos heveus, e dos jebuseus, a qual jurou a teus pais que ta daria, terra que mana leite e mel, guardarás este culto neste mês.

[[v2-13-6]]

^<<v2-13-6,6>>^ Sete dias comerás pães asmos; e ao sétimo dia haverá  festa ao Senhor.

[[v2-13-7]]

^<<v2-13-7,7>>^ Sete dias se comerão pães asmos, e o levedado não se verá contigo, nem ainda fermento será visto em todos os teus termos.

[[v2-13-8]]

^<<v2-13-8,8>>^ E naquele mesmo dia farás saber a teu filho, dizendo: Isto é  pelo que o Senhor me tem feito, quando eu saí do Egito.

[[v2-13-9]]

^<<v2-13-9,9>>^ E te será por sinal sobre tua mão, e por lembrança entre teus olhos; para que a lei do Senhor esteja em tua boca: porquanto com mão forte o Senhor te tirou do Egito.

[[v2-13-10]]

^<<v2-13-10,10>>^ Portanto tu guardarás este estatuto a seu tempo, de ano em ano.

[[v2-13-11]]

^<<v2-13-11,11>>^ Também acontecerá que, quando o Senhor te houver metido na terra dos cananeus, como jurou a ti e a teus pais, quando te houver dado,

[[v2-13-12]]

^<<v2-13-12,12>>^ Apartarás para o Senhor tudo o que abrir a madre, e tudo o que abrir a madre  do fruto dos animais que tiveres; os machos serão  do Senhor.

[[v2-13-13]]

^<<v2-13-13,13>>^ Porém tudo o que abrir a madre  da jumenta, resgatarás com cordeiro; e se o não resgatares, cortar-lhe-ás a cabeça: mas todo o primogênito do homem entre teus filhos resgatarás.

[[v2-13-14]]

^<<v2-13-14,14>>^ Se acontecer que teu filho no tempo futuro te pergunte, dizendo: Que é  isto? dir-lhe-ás: O Senhor nos tirou com mão forte do Egito, da casa da servidão.

[[v2-13-15]]

^<<v2-13-15,15>>^ Porque sucedeu que, endurecendo-se Faraó, para não nos deixar ir, o Senhor matou todos os primogênitos na terra do Egito, desde o primogênito do homem até ao primogênito dos animais: por isso eu sacrifico ao Senhor os machos de tudo o que abre a madre; porém a todo o primogênito de meus filhos eu resgato.

[[v2-13-16]]

^<<v2-13-16,16>>^ E será por sinal sobre tua mão, e por frontais entre os teus olhos; porque o Senhor nos tirou do Egito com mão forte.

[[v2-13-17]]

^<<v2-13-17,17>>^ E aconteceu que, quando Faraó deixou ir o povo, Deus não os levou pelo caminho da terra dos filisteus, que estava mais  perto; porque Deus disse: Para que porventura o povo não se arrependa, vendo a guerra, e tornem ao Egito.

[[v2-13-18]]

^<<v2-13-18,18>>^ Mas Deus fez rodear o povo pelo caminho do deserto perto do Mar Vermelho: e subiram os filhos de Israel da terra do Egito armados.

[[v2-13-19]]

^<<v2-13-19,19>>^ E tomou Moisés os ossos de José consigo, porquanto havia este estreitamente ajuramentado aos filhos de Israel, dizendo: Certamente Deus vos visitará; fazei pois subir daqui os meus ossos convosco.

[[v2-13-20]]

^<<v2-13-20,20>>^ Assim partiram de Sucote, e acamparam em Etã, à entrada do deserto.

[[v2-13-21]]

^<<v2-13-21,21>>^ E o Senhor ia adiante deles, de dia numa coluna de nuvem, para os guiar pelo caminho, e de noite numa coluna de fogo, para os alumiar, para que caminhassem de dia e de noite.

[[v2-13-22]]

^<<v2-13-22,22>>^ Nunca tirou de diante da face do povo a coluna de nuvem, de dia, nem a coluna de fogo, de noite.

'''

xref:002-exodo/002-exodo-012.adoc#v2-12-0[&#60; Capítulo Anterior] | <<v2-13-0,Topo>> | xref:002-exodo/002-exodo-014.adoc#v2-14-0[Próximo Capítulo &#62;]