include::./index.adoc[]

[[v2-38-0]]
=== Êxodo, 38
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-38-1]]

^<<v2-38-1,1>>^ FEZ também o altar do holocausto de madeira de  cetim: de cinco côvados era  o seu comprimento, e de cinco côvados a sua largura, quadrado; e de três côvados a sua altura.

[[v2-38-2]]

^<<v2-38-2,2>>^ E fez-lhe as suas pontas aos seus quatro cantos; do mesmo eram as suas pontas; e cobriu-o de cobre.

[[v2-38-3]]

^<<v2-38-3,3>>^ Fez também todos os vasos do altar: os caldeirões, e as pás, e as bacias, e os garfos, e os braseiros: todos os seus vasos fez de cobre.

[[v2-38-4]]

^<<v2-38-4,4>>^ Fez também para o altar um crivo de cobre, de obra de rede, na sua cercadura debaixo, até ao meio dele.

[[v2-38-5]]

^<<v2-38-5,5>>^ E fundiu quatro argolas às quatro extremidades do crivo de cobre, para os lugares dos varais.

[[v2-38-6]]

^<<v2-38-6,6>>^ E fez os varais de madeira de  cetim, e os cobriu de cobre.

[[v2-38-7]]

^<<v2-38-7,7>>^ E meteu os varais pelas argolas aos lados do altar, para levá-lo com eles: fê-lo oco de tábuas.

[[v2-38-8]]

^<<v2-38-8,8>>^ Fez também a pia de cobre com a sua base de cobre, dos espelhos das mulheres  que se ajuntavam, ajuntando-se à porta da tenda da congregação.

[[v2-38-9]]

^<<v2-38-9,9>>^ Fez também o pátio da banda do meio-dia ao sul: as cortinas do pátio eram  de linho fino torcido, de cem côvados.

[[v2-38-10]]

^<<v2-38-10,10>>^ As suas vinte colunas e as suas vinte bases eram  de cobre: os colchetes destas colunas e as suas molduras eram  de prata;

[[v2-38-11]]

^<<v2-38-11,11>>^ E da banda do norte cortinas  de cem côvados; as suas vinte colunas e as suas vinte bases eram  de cobre, os colchetes das colunas e as suas molduras eram  de prata.

[[v2-38-12]]

^<<v2-38-12,12>>^ E da banda do ocidente cortinas de cinquenta côvados; as suas colunas dez, e as suas bases dez: os colchetes das colunas e as suas molduras eram  de prata.

[[v2-38-13]]

^<<v2-38-13,13>>^ E da banda oriental, ao oriente, cortinas  de cinquenta côvados.

[[v2-38-14]]

^<<v2-38-14,14>>^ As cortinas desta banda da porta eram  de quinze côvados: as suas colunas três e as suas bases três.

[[v2-38-15]]

^<<v2-38-15,15>>^ E da outra banda da porta do pátio, de ambos os lados, eram  cortinas de quinze côvados: as suas colunas três e as suas bases três.

[[v2-38-16]]

^<<v2-38-16,16>>^ Todas as cortinas do pátio ao redor eram  de linho fino torcido.

[[v2-38-17]]

^<<v2-38-17,17>>^ E as bases das colunas eram  de cobre: os colchetes das colunas e as suas molduras eram  de prata; e a coberta das suas cabeças de prata; e todas as colunas do pátio eram  cingidas de prata.

[[v2-38-18]]

^<<v2-38-18,18>>^ E a coberta da porta do pátio era  de obra de bordador, de azul, e de púrpura, e de carmesim, e de linho fino torcido; e o comprimento, era  de vinte côvados, e a altura, na largura, de cinco côvados, defronte das cortinas do pátio.

[[v2-38-19]]

^<<v2-38-19,19>>^ E as suas quatro colunas e as suas quatro bases eram  de cobre, os seus colchetes de prata, e a coberta das suas cabeças, e as suas molduras, de prata.

[[v2-38-20]]

^<<v2-38-20,20>>^ E todas as estacas do tabernáculo e do pátio ao redor eram  de cobre.

[[v2-38-21]]

^<<v2-38-21,21>>^ Esta é  a enumeração das cousas contadas do tabernáculo do testemunho, que por ordem de Moisés foram contadas para  o ministério dos levitas por mão de Itamar, filho de Aarão o sacerdote.

[[v2-38-22]]

^<<v2-38-22,22>>^ Fez pois Bezaleel, o filho de Uri, filho de Hur, da tribo de Judá, tudo quanto o Senhor tinha ordenado a Moisés.

[[v2-38-23]]

^<<v2-38-23,23>>^ E com ele Aoliabe, o filho de Aisamaque, da tribo de Dã, um mestre de obras, e engenhoso artífice, e bordador em azul, e em púrpura e em carmesim e em linho fino.

[[v2-38-24]]

^<<v2-38-24,24>>^ Todo o ouro gasto na obra em toda a obra do santuário, a saber, o ouro da oferta, foi  vinte e nove talentos e setecentos e trinta siclos, conforme ao siclo do santuário;

[[v2-38-25]]

^<<v2-38-25,25>>^ E a prata dos arrolados da congregação foi  cem talentos e mil e setecentos e setenta e cinco siclos, conforme ao siclo do santuário;

[[v2-38-26]]

^<<v2-38-26,26>>^ Um beca por cada  cabeça, isto é , meio siclo, conforme ao siclo do santuário: de qualquer que passava aos arrolados, da idade de vinte anos e acima, que foram  seiscentos e três mil e quinhentos e cinquenta.

[[v2-38-27]]

^<<v2-38-27,27>>^ E houve cem talentos de prata para fundir as bases do santuário e as bases do véu: para cem bases eram  cem talentos; um talento para cada base.

[[v2-38-28]]

^<<v2-38-28,28>>^ Mas dos mil e setecentos e setenta e cinco siclos  fez os colchetes das colunas, e cobriu as suas cabeças, e as cingiu de molduras.

[[v2-38-29]]

^<<v2-38-29,29>>^ E o cobre da oferta foi  setenta talentos e dois mil e quatrocentos siclos.

[[v2-38-30]]

^<<v2-38-30,30>>^ E dele fez as bases da porta da tenda da congregação e o altar de cobre, e o crivo de cobre para ele e todos os vasos do altar,

[[v2-38-31]]

^<<v2-38-31,31>>^ E as bases do pátio ao redor, e as bases da porta do pátio, e todas as estacas do tabernáculo e todas as estacas do pátio ao redor.

'''

xref:002-exodo/002-exodo-037.adoc#v2-37-0[&#60; Capítulo Anterior] | <<v2-38-0,Topo>> | xref:002-exodo/002-exodo-039.adoc#v2-39-0[Próximo Capítulo &#62;]