include::./index.adoc[]

[[v2-26-0]]
=== Êxodo, 26
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-26-1]]

^<<v2-26-1,1>>^ E O tabernáculo farás de  dez cortinas de  linho fino torcido, e azul, púrpura, e carmesim: com  querubins as farás de obra esmerada.

[[v2-26-2]]

^<<v2-26-2,2>>^ O comprimento duma cortina será  de vinte e oito côvados, e a largura de uma cortina de quatro côvados: todas estas cortinas serão duma medida.

[[v2-26-3]]

^<<v2-26-3,3>>^ Cinco cortinas se enlaçarão uma à outra: e as outras  cinco cortinas se enlaçarão uma com a outra.

[[v2-26-4]]

^<<v2-26-4,4>>^ E farás laçadas de azul na ponta duma cortina, na extremidade, na juntura: assim também farás na ponta da extremidade da outra  cortina, na segunda juntura.

[[v2-26-5]]

^<<v2-26-5,5>>^ Cinquenta laçadas farás numa cortina, e outras  cinquenta laçadas farás na extremidade da cortina que está  na segunda juntura: as laçadas estarão travadas uma com a outra.

[[v2-26-6]]

^<<v2-26-6,6>>^ Farás também cinquenta colchetes de ouro, e ajuntarás com estes colchetes as cortinas, uma com a outra, e será um tabernáculo.

[[v2-26-7]]

^<<v2-26-7,7>>^ Farás também cortinas de pelos  de cabras por tenda sobre o tabernáculo: de onze cortinas as farás.

[[v2-26-8]]

^<<v2-26-8,8>>^ O comprimento duma cortina será  de trinta côvados, e a largura da mesma cortina de quatro côvados; estas onze cortinas serão  duma medida.

[[v2-26-9]]

^<<v2-26-9,9>>^ E ajuntarás cinco destas cortinas por si, e as outras  seis cortinas também  por si: e dobrarás a sexta cortina diante da tenda.

[[v2-26-10]]

^<<v2-26-10,10>>^ E farás cinquenta laçadas na borda duma cortina, na extremidade, na juntura, e outras  cinquenta laçadas na borda da outra  cortina, na segunda juntura.

[[v2-26-11]]

^<<v2-26-11,11>>^ Farás também cinquenta colchetes de cobre, e meterás os colchetes nas laçadas, e assim  ajuntarás a tenda, para que seja uma.

[[v2-26-12]]

^<<v2-26-12,12>>^ E o resto que sobejar das cortinas da tenda, a metade da cortina que sobejar, penderá sobre as costas do tabernáculo.

[[v2-26-13]]

^<<v2-26-13,13>>^ E um côvado duma banda, e outro côvado da outra, que sobejará no comprimento das cortinas da tenda, penderá de sobejo aos lados do tabernáculo duma e doutra banda, para cobri-lo.

[[v2-26-14]]

^<<v2-26-14,14>>^ Farás também à tenda uma coberta de  peles de carneiro, tintas de vermelho, e outra  coberta de peles de  texugo em cima.

[[v2-26-15]]

^<<v2-26-15,15>>^ Farás também as tábuas para o tabernáculo de madeira de  cetim, que estarão levantadas.

[[v2-26-16]]

^<<v2-26-16,16>>^ O comprimento duma tábua será  de dez côvados, e a largura de cada tábua será  dum côvado e meio.

[[v2-26-17]]

^<<v2-26-17,17>>^ Duas couceiras terá  cada tábua, travadas uma com a outra: assim farás com todas as tábuas do tabernáculo.

[[v2-26-18]]

^<<v2-26-18,18>>^ E farás as tábuas para o tabernáculo assim : vinte tábuas para a banda do meio-dia ao sul.

[[v2-26-19]]

^<<v2-26-19,19>>^ Farás também quarenta bases de prata debaixo das vinte tábuas: duas bases debaixo duma tábua para as suas duas couceiras, e duas bases debaixo doutra tábua para as suas duas couceiras.

[[v2-26-20]]

^<<v2-26-20,20>>^ Também haverá  vinte tábuas ao outro lado do tabernáculo, para a banda do norte,

[[v2-26-21]]

^<<v2-26-21,21>>^ Com as suas quarenta bases de prata: duas bases debaixo duma tábua, e duas bases debaixo doutra tábua,

[[v2-26-22]]

^<<v2-26-22,22>>^ E ao lado do tabernáculo para o ocidente farás seis tábuas.

[[v2-26-23]]

^<<v2-26-23,23>>^ Farás também duas tábuas para os cantos do tabernáculo, de ambos os lados;

[[v2-26-24]]

^<<v2-26-24,24>>^ E por baixo se ajuntarão, e também em cima dele se ajuntarão numa argola. Assim se fará com as duas tábuas : ambas serão por tábuas  para os dois cantos.

[[v2-26-25]]

^<<v2-26-25,25>>^ Assim serão as oito tábuas com as suas bases de prata, dezesseis bases: duas bases debaixo duma tábua, e duas bases debaixo doutra tábua.

[[v2-26-26]]

^<<v2-26-26,26>>^ Farás também cinco barras de madeira de  cetim, para as tábuas dum lado do tabernáculo,

[[v2-26-27]]

^<<v2-26-27,27>>^ E cinco barras para as tábuas do outro lado do tabernáculo; como também cinco barras para as tábuas do outro  lado do tabernáculo, de ambas as bandas para o ocidente.

[[v2-26-28]]

^<<v2-26-28,28>>^ E a barra do meio estará  no meio das tábuas, passando duma extremidade até à outra.

[[v2-26-29]]

^<<v2-26-29,29>>^ E cobrirás de ouro as tábuas, e farás de ouro as suas argolas, para meter por elas as barras: também as barras as cobrirás de ouro.

[[v2-26-30]]

^<<v2-26-30,30>>^ Então levantarás o tabernáculo conforme ao modelo que te foi mostrado no monte.

[[v2-26-31]]

^<<v2-26-31,31>>^ Depois farás um véu de azul, e púrpura, e carmesim, e de linho fino torcido; com querubins de obra prima se fará.

[[v2-26-32]]

^<<v2-26-32,32>>^ E o porás sobre quatro colunas de madeira  de cetim, cobertas de ouro: seus colchetes serão  de ouro, sobre quatro bases de prata.

[[v2-26-33]]

^<<v2-26-33,33>>^ Pendurarás o véu debaixo dos colchetes, e meterás a arca do testemunho ali dentro do véu: e este véu vos fará separação entre o santuário e o lugar santíssimo.

[[v2-26-34]]

^<<v2-26-34,34>>^ E porás a coberta do propiciatório sobre a arca do testemunho no lugar santíssimo,

[[v2-26-35]]

^<<v2-26-35,35>>^ E a mesa porás fora do véu, e o castiçal defronte da mesa, ao lado do tabernáculo, para o sul; e a mesa porás à banda do norte.

[[v2-26-36]]

^<<v2-26-36,36>>^ Farás também para a porta da tenda uma coberta de azul, e púrpura, e carmesim, e de linho fino torcido, de obra de bordador,

[[v2-26-37]]

^<<v2-26-37,37>>^ E farás para esta coberta cinco colunas de madeira  de cetim, e as cobrirás de ouro; seus colchetes serão  de ouro, e far-lhe-ás de fundição cinco bases de cobre.

'''

xref:002-exodo/002-exodo-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodo/002-exodo-027.adoc#v2-27-0[Próximo Capítulo &#62;]