include::./index.adoc[]

[[v2-23-0]]
=== Êxodo, 23
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-23-1]]

^<<v2-23-1,1>>^ NÃO admitirás falso rumor, e não porás a tua mão com o ímpio, para seres testemunha falsa.

[[v2-23-2]]

^<<v2-23-2,2>>^ Não seguirás a multidão para fazeres o mal: nem numa demanda falarás, tomando parte com o maior número para torcer o direito.

[[v2-23-3]]

^<<v2-23-3,3>>^ Nem ao pobre favorecerás na sua demanda.

[[v2-23-4]]

^<<v2-23-4,4>>^ Se encontrares o boi do teu inimigo, ou o seu jumento, desgarrado, sem falta lho reconduzirás.

[[v2-23-5]]

^<<v2-23-5,5>>^ Se vires o jumento daquele que te aborrece deitado debaixo da sua carga, deixarás pois de ajudá-lo? Certamente o ajudarás juntamente com ele.

[[v2-23-6]]

^<<v2-23-6,6>>^ Não perverterás o direito do teu pobre na sua demanda.

[[v2-23-7]]

^<<v2-23-7,7>>^ De palavras de falsidade te afastarás e não matarás o inocente e o justo; porque não justificarei o ímpio.

[[v2-23-8]]

^<<v2-23-8,8>>^ Também presente não tomarás: porque o presente cega os que têm vista, e perverte as palavras dos justos.

[[v2-23-9]]

^<<v2-23-9,9>>^ Também não oprimirás o estrangeiro; pois vós conheceis o coração do estrangeiro, pois fostes estrangeiros na terra do Egito.

[[v2-23-10]]

^<<v2-23-10,10>>^ Também seis anos semearás tua terra, e recolherás os seus frutos:

[[v2-23-11]]

^<<v2-23-11,11>>^ Mas ao sétimo a soltarás e deixarás descansar, para que possam comer os pobres do teu povo, e do sobejo comam os animais do campo. Assim farás com a tua vinha e com o teu olival.

[[v2-23-12]]

^<<v2-23-12,12>>^ Seis dias farás os teus negócios, mas ao sétimo dia descansarás: para que descanse o teu boi, e o teu jumento; e para que tome alento o filho da tua escrava, e o estrangeiro.

[[v2-23-13]]

^<<v2-23-13,13>>^ E em tudo o que vos tenho dito, guardai-vos: e do nome de outros deuses nem vos lembreis, nem se ouça da vossa boca.

[[v2-23-14]]

^<<v2-23-14,14>>^ Três vezes no ano me celebrareis festa:

[[v2-23-15]]

^<<v2-23-15,15>>^ A festa dos pães asmos guardarás: sete dias comerás pães asmos, como te tenho ordenado, ao tempo apontado no mês de abibe; porque nele saíste do Egito: ninguém apareça vazio perante mim;

[[v2-23-16]]

^<<v2-23-16,16>>^ E a festa da sega dos primeiros frutos do teu trabalho, que houveres semeado no campo, e a festa da colheita à saída do ano, quando tiveres colhido do campo o teu trabalho.

[[v2-23-17]]

^<<v2-23-17,17>>^ Três vezes no ano todos os teus varões aparecerão diante do Senhor.

[[v2-23-18]]

^<<v2-23-18,18>>^ Não oferecerás o sangue do meu sacrifício com pão levedado: nem ficará a gordura da minha festa de noite até de manhã.

[[v2-23-19]]

^<<v2-23-19,19>>^ As primícias dos primeiros frutos da tua terra trarás à casa do Senhor teu Deus: não cozerás o cabrito no leite de sua mãe.

[[v2-23-20]]

^<<v2-23-20,20>>^ Eis que eu envio um anjo diante de ti, para que te guarde neste caminho, e te leve ao lugar que te  tenho aparelhado.

[[v2-23-21]]

^<<v2-23-21,21>>^ Guarda-te diante dele, e ouve a sua voz, e não o provoques à ira: porque não perdoará a vossa rebelião; porque o meu nome está  nele.

[[v2-23-22]]

^<<v2-23-22,22>>^ Mas se diligentemente ouvires a sua voz, e fizeres tudo o que eu disser, então serei inimigo dos teus inimigos, e adversário dos teus adversários.

[[v2-23-23]]

^<<v2-23-23,23>>^ Porque o meu anjo irá diante de ti, e te levará aos amorreus, e aos heteus, e aos ferezeus, e aos cananeus, heveus e jebuseus: e eu os destruirei.

[[v2-23-24]]

^<<v2-23-24,24>>^ Não te inclinarás diante dos seus deuses, nem os servirás, nem farás conforme às suas obras: antes os destruirás totalmente, e quebrarás de todo as suas estátuas.

[[v2-23-25]]

^<<v2-23-25,25>>^ E servireis ao Senhor vosso Deus, e ele abençoará o vosso pão e a vossa água: e eu tirarei do meio de ti as enfermidades.

[[v2-23-26]]

^<<v2-23-26,26>>^ Não haverá alguma que aborte, nem estéril na tua terra: o número dos teus dias cumprirei.

[[v2-23-27]]

^<<v2-23-27,27>>^ Enviarei o meu terror diante de ti, desconcertando a todo o povo aonde entrares, e farei que todos os teus inimigos te virem as costas.

[[v2-23-28]]

^<<v2-23-28,28>>^ Também enviarei vespões diante de ti, que lancem fora os heveus, os cananeus, e os heteus diante de ti.

[[v2-23-29]]

^<<v2-23-29,29>>^ Num só ano os não lançarei fora diante de ti, para que a terra se não torne em deserto, e as feras do campo se não multipliquem contra ti.

[[v2-23-30]]

^<<v2-23-30,30>>^ Pouco a pouco os lançarei de diante de ti, até que sejas multiplicado, e possuas a terra por herança.

[[v2-23-31]]

^<<v2-23-31,31>>^ E porei os teus termos desde o Mar Vermelho até ao mar dos filisteus, e desde o deserto até ao rio: porque darei nas tuas mãos os moradores da terra, para que os lances fora de diante de ti.

[[v2-23-32]]

^<<v2-23-32,32>>^ Não farás concerto algum com eles, ou com os seus deuses.

[[v2-23-33]]

^<<v2-23-33,33>>^ Na tua terra não habitarão, para que não te façam pecar contra mim: se servires aos seus deuses, certamente será um laço para ti.

'''

xref:002-exodo/002-exodo-022.adoc#v2-22-0[&#60; Capítulo Anterior] | <<v2-23-0,Topo>> | xref:002-exodo/002-exodo-024.adoc#v2-24-0[Próximo Capítulo &#62;]