include::./index.adoc[]

[[v2-11-0]]
=== Êxodo, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-11-1]]

^<<v2-11-1,1>>^ E O Senhor disse a Moisés: Ainda uma praga trarei sobre Faraó, e sobre o Egito: depois vos deixará ir daqui: e, quando vos  deixar ir totalmente, a toda a pressa vos lançará daqui.

[[v2-11-2]]

^<<v2-11-2,2>>^ Fala agora aos ouvidos do povo, que cada varão peça ao seu vizinho, e cada mulher à sua vizinha, vasos de prata e vasos de ouro.

[[v2-11-3]]

^<<v2-11-3,3>>^ E o Senhor deu graça ao povo aos olhos dos egípcios; também o varão Moisés era  mui grande na terra do Egito, aos olhos dos servos de Faraó, e aos olhos do povo.

[[v2-11-4]]

^<<v2-11-4,4>>^ Disse mais Moisés: Assim o Senhor tem dito: À meia-noite eu sairei pelo meio do Egito;

[[v2-11-5]]

^<<v2-11-5,5>>^ E todo o primogênito na terra do Egito morrerá, desde o primogênito de Faraó, que se assenta com ele sobre o seu trono, até ao primogênito da serva que está  detrás da mó, e todo o primogênito dos animais.

[[v2-11-6]]

^<<v2-11-6,6>>^ E haverá grande clamor em toda a terra do Egito, qual nunca houve semelhante e nunca haverá;

[[v2-11-7]]

^<<v2-11-7,7>>^ Mas contra todos os filhos de Israel nem ainda um cão moverá a sua língua, desde os homens até aos animais, para que saibais que o Senhor fez diferença entre os egípcios e os israelitas.

[[v2-11-8]]

^<<v2-11-8,8>>^ Então todos estes teus servos descerão a mim, e se inclinarão diante de mim, dizendo: Sai tu, e todo o povo que te segue as pisadas; e depois eu sairei. E saiu de Faraó em ardor de ira.

[[v2-11-9]]

^<<v2-11-9,9>>^ O Senhor dissera a Moisés: Faraó vos não ouvirá, para que as minhas maravilhas se multipliquem na terra do Egito.

[[v2-11-10]]

^<<v2-11-10,10>>^ E Moisés e Aarão fizeram todas estas maravilhas diante de Faraó; mas o Senhor endureceu o coração de Faraó, que não deixou ir os filhos de Israel da sua terra.

'''

xref:002-exodo/002-exodo-010.adoc#v2-10-0[&#60; Capítulo Anterior] | <<v2-11-0,Topo>> | xref:002-exodo/002-exodo-012.adoc#v2-12-0[Próximo Capítulo &#62;]