include::./index.adoc[]

[[v2-25-0]]
=== Êxodo, 25
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-25-1]]

^<<v2-25-1,1>>^ ENTÃO falou o Senhor a Moisés, dizendo:

[[v2-25-2]]

^<<v2-25-2,2>>^ Fala aos filhos de Israel, que me tragam uma oferta alçada: de todo o homem cujo coração se mover voluntariamente, dele  tomareis a minha oferta alçada.

[[v2-25-3]]

^<<v2-25-3,3>>^ E esta é  a oferta alçada que tomareis deles: ouro, e prata, e cobre,

[[v2-25-4]]

^<<v2-25-4,4>>^ E azul, e púrpura, e carmesim, e linho fino, e pelos  de cabras,

[[v2-25-5]]

^<<v2-25-5,5>>^ E peles de carneiros tintas de vermelho, e peles de texugos, e madeira de cetim,

[[v2-25-6]]

^<<v2-25-6,6>>^ Azeite para a luz, especiarias para o óleo da unção, e especiarias para o incenso,

[[v2-25-7]]

^<<v2-25-7,7>>^ Pedras sardônicas, e pedras de engaste para o éfode e para o peitoral.

[[v2-25-8]]

^<<v2-25-8,8>>^ E me farão um santuário, e habitarei no meio deles.

[[v2-25-9]]

^<<v2-25-9,9>>^ Conforme a tudo o que eu te mostrar para  modelo do tabernáculo, e para modelo de todos os seus vasos, assim mesmo o fareis.

[[v2-25-10]]

^<<v2-25-10,10>>^ Também farão uma arca de madeira de cetim: o seu comprimento será  de dois côvados e meio, e a sua largura dum côvado e meio, e dum côvado e meio a sua altura.

[[v2-25-11]]

^<<v2-25-11,11>>^ E cobri-la-ás de ouro puro, por dentro e por fora a cobrirás: e farás sobre ela uma coroa de ouro ao redor;

[[v2-25-12]]

^<<v2-25-12,12>>^ E fundirás para ela quatro argolas de ouro, e as  porás nos quatro cantos dela: duas argolas num lado dela, e duas argolas noutro lado dela.

[[v2-25-13]]

^<<v2-25-13,13>>^ E farás varas de  madeira de cetim, e as cobrirás com ouro,

[[v2-25-14]]

^<<v2-25-14,14>>^ E meterás as varas nas argolas, aos lados da arca, para se levar com elas a arca.

[[v2-25-15]]

^<<v2-25-15,15>>^ As varas estarão nas argolas da arca, não se tirarão dela.

[[v2-25-16]]

^<<v2-25-16,16>>^ Depois porás na arca o testemunho, que eu te darei.

[[v2-25-17]]

^<<v2-25-17,17>>^ Também farás um propiciatório, de ouro puro: o seu comprimento será  de dois côvados e meio, e a sua largura dum côvado e meio.

[[v2-25-18]]

^<<v2-25-18,18>>^ Farás também dois querubins de ouro: de ouro batido os farás, nas duas extremidades do propiciatório.

[[v2-25-19]]

^<<v2-25-19,19>>^ Farás um querubim na extremidade duma parte, e o outro querubim na extremidade da outra parte: de uma só peça com o propiciatório fareis os querubins nas duas extremidades dele.

[[v2-25-20]]

^<<v2-25-20,20>>^ Os querubins estenderão as suas  asas por de cima, cobrindo com as suas asas o propiciatório; as faces deles uma defronte da outra: as faces dos querubins estarão voltadas para o propiciatório.

[[v2-25-21]]

^<<v2-25-21,21>>^ E porás o propiciatório em cima da arca, depois que houveres posto na arca o testemunho que eu te darei.

[[v2-25-22]]

^<<v2-25-22,22>>^ E ali virei a ti, e falarei contigo de cima do propiciatório, do meio dos dois querubins (que estão sobre a arca do testemunho), tudo o que eu te ordenar para os filhos de Israel.

[[v2-25-23]]

^<<v2-25-23,23>>^ Também farás uma mesa de  madeira de cetim; o seu comprimento será  de dois côvados, e a sua largura dum côvado, e a sua altura de um côvado e meio,

[[v2-25-24]]

^<<v2-25-24,24>>^ E cobri-la-ás com ouro puro: também lhe farás uma coroa de ouro ao redor.

[[v2-25-25]]

^<<v2-25-25,25>>^ Também lhe farás uma moldura ao redor, da largura  duma mão, e lhe farás uma coroa de ouro ao redor da moldura.

[[v2-25-26]]

^<<v2-25-26,26>>^ Também lhe farás quatro argolas de ouro; e porás as argolas aos quatro cantos, que estão nos seus quatro pés.

[[v2-25-27]]

^<<v2-25-27,27>>^ Defronte da moldura estarão as argolas, como lugares para os varais, para se levar a mesa.

[[v2-25-28]]

^<<v2-25-28,28>>^ Farás pois estes varais de  madeira de cetim, e cobri-los-ás com ouro; e levar-se-á com eles a mesa.

[[v2-25-29]]

^<<v2-25-29,29>>^ Também farás os seus pratos e as suas colheres, e as suas cobertas, e as suas tigelas com que se hão de cobrir; de ouro puro os farás.

[[v2-25-30]]

^<<v2-25-30,30>>^ E sobre a mesa porás o pão da proposição perante a minha face continuamente.

[[v2-25-31]]

^<<v2-25-31,31>>^ Também farás um castiçal de ouro puro; de ouro  batido se fará este castiçal: o seu pé, as suas canas, as suas copas, as suas maçãs, e as suas flores serão do mesmo.

[[v2-25-32]]

^<<v2-25-32,32>>^ E dos seus lados sairão seis canas: três canas do castiçal dum lado dele, e três canas do castiçal do outro lado dele.

[[v2-25-33]]

^<<v2-25-33,33>>^ Numa cana haverá  três copos a modo de amêndoas, uma maçã e uma flor; e três copos a modo de amêndoas na outra cana, uma maçã e uma flor: assim serão as seis canas que saem do castiçal.

[[v2-25-34]]

^<<v2-25-34,34>>^ Mas no castiçal mesmo haverá  quatro copos a modo de amêndoas, com suas maçãs e com suas flores;

[[v2-25-35]]

^<<v2-25-35,35>>^ E uma maçã debaixo de duas canas que saem  dele; e ainda uma maçã debaixo de duas outras  canas que saem  dele; e ainda mais  uma maçã debaixo de duas outras  canas que saem dele; assim se fará  com as seis canas que saem do castiçal.

[[v2-25-36]]

^<<v2-25-36,36>>^ As suas maçãs e as suas canas serão do mesmo; tudo será  duma só peça, obra batida de ouro puro.

[[v2-25-37]]

^<<v2-25-37,37>>^ Também lhe farás sete lâmpadas, as quais se acenderão para alumiar defronte dele.

[[v2-25-38]]

^<<v2-25-38,38>>^ Os seus espevitadores e os seus apagadores serão  de ouro puro.

[[v2-25-39]]

^<<v2-25-39,39>>^ Dum talento de ouro puro os farás, com todos estes vasos.

[[v2-25-40]]

^<<v2-25-40,40>>^ Atenta pois que o faças conforme ao seu modelo, que te foi mostrado no monte.

'''

xref:002-exodo/002-exodo-024.adoc#v2-24-0[&#60; Capítulo Anterior] | <<v2-25-0,Topo>> | xref:002-exodo/002-exodo-026.adoc#v2-26-0[Próximo Capítulo &#62;]