include::./index.adoc[]

[[v2-32-0]]
=== Êxodo, 32
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v2-32-1]]

^<<v2-32-1,1>>^ MAS vendo o povo que Moisés tardava em descer do monte, ajuntou-se o povo a Aarão, e disseram-lhe: Levanta-te, faze-nos deuses, que vão adiante de nós: porque enquanto a  este Moisés, a  este homem que nos tirou da terra do Egito, não sabemos o que lhe sucedeu.

[[v2-32-2]]

^<<v2-32-2,2>>^ E Aarão lhes disse: Arrancai os pendentes de ouro, que estão  nas orelhas de vossas mulheres, e de vossos filhos, e de vossas filhas, trazei-mos.

[[v2-32-3]]

^<<v2-32-3,3>>^ Então todo o povo arrancou os pendentes de ouro, que estavam  nas suas orelhas, e os  trouxeram a Aarão,

[[v2-32-4]]

^<<v2-32-4,4>>^ E ele os  tomou das suas mãos, e formou o ouro com um buril, e fez dele um bezerro de fundição. Então disseram: Estes são  teus deuses, ó Israel, que te tiraram da terra do Egito.

[[v2-32-5]]

^<<v2-32-5,5>>^ E Aarão, vendo isto, edificou um altar diante dele: e Aarão apregoou, e disse: Amanhã será  festa ao Senhor.

[[v2-32-6]]

^<<v2-32-6,6>>^ E no dia seguinte madrugaram, e ofereceram holocaustos, e trouxeram ofertas pacíficas; e o povo assentou-se a comer e a beber; depois levantaram-se a folgar.

[[v2-32-7]]

^<<v2-32-7,7>>^ Então disse o Senhor a Moisés: Vai, desce; porque o teu povo, que fizeste subir do Egito, se tem corrompido,

[[v2-32-8]]

^<<v2-32-8,8>>^ E depressa se tem desviado do caminho que eu lhes tinha ordenado: fizeram para si um bezerro de fundição, e perante ele se inclinaram, e sacrificaram-lhe, e disseram: Estes são os teus deuses, ó Israel, que te tiraram da terra do Egito.

[[v2-32-9]]

^<<v2-32-9,9>>^ Disse mais o Senhor a Moisés: Tenho visto a este povo, e eis que é povo obstinado.

[[v2-32-10]]

^<<v2-32-10,10>>^ Agora pois deixa-me, que o meu furor se acenda contra eles, e os consuma: e eu farei de ti uma grande nação.

[[v2-32-11]]

^<<v2-32-11,11>>^ Porém Moisés suplicou ao Senhor seu Deus, e disse: Ó Senhor, por que se acende o teu furor contra o teu povo, que tu tiraste da terra do Egito com grande força e com forte mão?

[[v2-32-12]]

^<<v2-32-12,12>>^ Por que hão de falar os egípcios, dizendo: Para mal os tirou, para matá-los nos montes, e para destruí-los da face da terra? Torna-te da ira do teu furor, e arrepende-te deste  mal contra o teu povo.

[[v2-32-13]]

^<<v2-32-13,13>>^ Lembra-te de Abraão, de Isaque, e de Israel, os teus servos, aos quais por ti mesmo tens jurado, e lhes disseste: Multiplicarei a vossa semente como as estrelas dos céus, e darei à vossa semente toda esta terra, de que tenho dito, para que a  possuam por herança eternamente.

[[v2-32-14]]

^<<v2-32-14,14>>^ Então o Senhor arrependeu-se do mal que dissera que havia de fazer ao seu povo.

[[v2-32-15]]

^<<v2-32-15,15>>^ E voltou Moisés, e desceu do monte com as duas tábuas do testemunho na sua mão, tábuas escritas de ambas as bandas; de uma e de outra banda escritas estavam.

[[v2-32-16]]

^<<v2-32-16,16>>^ E aquelas tábuas eram  obra de Deus; também a escritura era  a mesma escritura de Deus, esculpida nas tábuas.

[[v2-32-17]]

^<<v2-32-17,17>>^ E, ouvindo Josué a voz do povo que jubilava, disse a Moisés: Alarido de guerra há  no arraial.

[[v2-32-18]]

^<<v2-32-18,18>>^ Porém ele disse: Não é  alarido dos vitoriosos, nem alarido dos vencidos, mas o alarido dos que cantam eu ouço.

[[v2-32-19]]

^<<v2-32-19,19>>^ E aconteceu que, chegando ele ao arraial, e vendo o bezerro e as danças, acendeu-se o furor de Moisés, e arremessou as tábuas das suas mãos, e quebrou-as ao pé do monte;

[[v2-32-20]]

^<<v2-32-20,20>>^ E tomou o bezerro que tinham feito, e queimou-o no fogo, moendo-o até que se tornou em pó; e o espargiu sobre as águas, e deu-o a beber aos filhos de Israel.

[[v2-32-21]]

^<<v2-32-21,21>>^ E Moisés disse a Aarão: Que te tem feito este povo, que sobre ele trouxeste tamanho pecado?

[[v2-32-22]]

^<<v2-32-22,22>>^ Então disse Aarão: Não se acenda a ira do meu senhor: tu sabes que este povo é inclinado  ao mal;

[[v2-32-23]]

^<<v2-32-23,23>>^ E eles me disseram: Faze-nos deuses que vão adiante de nós; porque não sabemos que sucedeu a este Moisés, a este homem que nos tirou da terra do Egito.

[[v2-32-24]]

^<<v2-32-24,24>>^ Então eu lhes disse: Quem tem ouro, arranque-o: e deram-mo, e lancei-o no fogo, e saiu este bezerro.

[[v2-32-25]]

^<<v2-32-25,25>>^ E vendo Moisés que o povo estava  despido, porque Aarão o havia despido para vergonha entre os seus inimigos,

[[v2-32-26]]

^<<v2-32-26,26>>^ Pôs-se em pé Moisés na porta do arraial, e disse: Quem é do Senhor, venha  a mim. Então se ajuntaram a ele todos os filhos de Levi.

[[v2-32-27]]

^<<v2-32-27,27>>^ E disse-lhes: Assim diz o Senhor, o Deus de Israel: Cada um ponha a sua espada sobre a sua coxa: e passai e tornai pelo arraial de porta em porta, e mate cada um a seu irmão, e cada um a seu amigo, e cada um a seu próximo.

[[v2-32-28]]

^<<v2-32-28,28>>^ E os filhos de Levi fizeram conforme à palavra de Moisés: e caíram do povo aquele dia uns três mil homens.

[[v2-32-29]]

^<<v2-32-29,29>>^ Porquanto Moisés tinha dito: Consagrai hoje as vossas mãos ao Senhor; porquanto cada um será contra o seu filho, e contra o seu irmão: e isto para ele vos dar hoje bênção.

[[v2-32-30]]

^<<v2-32-30,30>>^ E aconteceu que no dia seguinte Moisés disse ao povo: Vós pecastes grande pecado: agora porém subirei ao Senhor; porventura farei propiciação por vosso pecado.

[[v2-32-31]]

^<<v2-32-31,31>>^ Assim tornou Moisés ao Senhor, e disse: Ora, este povo pecou pecado grande fazendo para si deuses de ouro.

[[v2-32-32]]

^<<v2-32-32,32>>^ Agora pois perdoa o seu pecado, se não risca-me, peço-te, do teu livro, que tens escrito.

[[v2-32-33]]

^<<v2-32-33,33>>^ Então disse o Senhor a Moisés: Aquele que pecar contra mim, a este riscarei eu do meu livro.

[[v2-32-34]]

^<<v2-32-34,34>>^ Vai pois agora, conduze este povo para onde te tenho dito: eis que o meu anjo irá adiante de ti; porém no dia da minha visitação visitarei neles o seu pecado.

[[v2-32-35]]

^<<v2-32-35,35>>^ Assim feriu o Senhor o povo, porquanto fizeram o bezerro que Aarão tinha feito.

'''

xref:002-exodo/002-exodo-031.adoc#v2-31-0[&#60; Capítulo Anterior] | <<v2-32-0,Topo>> | xref:002-exodo/002-exodo-033.adoc#v2-33-0[Próximo Capítulo &#62;]