include::./index.adoc[]

[[v7-16-0]]
=== Juízes, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-16-1]]

^<<v7-16-1,1>>^ E FOI-SE Sansão a Gaza, e viu ali uma mulher prostituta, e entrou a ela.

[[v7-16-2]]

^<<v7-16-2,2>>^ E foi dito  aos gazitas: Sansão entrou aqui. Foram pois em roda, e toda a noite lhe puseram espias à porta da cidade: porém toda a noite estiveram sossegados, dizendo: Até à luz da manhã esperaremos ; então o mataremos.

[[v7-16-3]]

^<<v7-16-3,3>>^ Porém Sansão deitou-se até à meia-noite, e à meia-noite se levantou, e travou das portas da entrada da cidade com ambas as ombreiras, e juntamente com a tranca as tomou, pondo-as sobre os ombros; e levou-as para cima até ao cume do monte que está defronte de Hebrom.

[[v7-16-4]]

^<<v7-16-4,4>>^ E depois disto aconteceu que se afeiçoou a uma mulher do vale de Soreque, cujo nome era  Dalila.

[[v7-16-5]]

^<<v7-16-5,5>>^ Então os príncipes dos filisteus subiram a ela, e lhe disseram: Persuade-o, e vê, em que consiste  a sua grande força, e com que poderíamos assenhorear-nos dele e amarrá-lo, para assim  o afligirmos: e te daremos cada um mil e cem moedas  de prata.

[[v7-16-6]]

^<<v7-16-6,6>>^ Disse pois Dalila a Sansão: Declara-me, peço-te, em que consiste  a tua grande força, e com que poderias ser amarrado para te poderem afligir.

[[v7-16-7]]

^<<v7-16-7,7>>^ Disse-lhe Sansão: Se me amarrassem com sete vergas de  vimes frescos, que ainda não estivessem secos, então me enfraqueceria, e seria como qualquer outro  homem.

[[v7-16-8]]

^<<v7-16-8,8>>^ Então os príncipes dos filisteus lhe trouxeram sete vergas de  vimes frescos, que ainda não estavam secos: e amarrou-o com elas.

[[v7-16-9]]

^<<v7-16-9,9>>^ E os espias estavam  assentados com ela numa câmara. Então ela lhe disse: Os filisteus vêm  sobre ti, Sansão. Então quebrou as vergas  de vimes, como se quebra o fio da estopa ao cheiro do fogo; assim não se soube em que consistia a  sua força.

[[v7-16-10]]

^<<v7-16-10,10>>^ Então disse Dalila a Sansão: Eis que zombaste de mim, e me disseste mentiras; ora declara-me agora com  que poderias ser amarrado.

[[v7-16-11]]

^<<v7-16-11,11>>^ E ele lhe disse: Se me amarrassem fortemente com cordas novas, com que se não houvesse feito obra nenhuma, então me enfraqueceria, e seria como qualquer outro  homem.

[[v7-16-12]]

^<<v7-16-12,12>>^ Então Dalila tomou cordas novas, e o amarrou com elas, e disse-lhe: Os filisteus vêm  sobre ti, Sansão. E os espias estavam  assentados numa câmara. Então as quebrou de seus braços como um fio.

[[v7-16-13]]

^<<v7-16-13,13>>^ E disse Dalila a Sansão: Até agora zombaste de mim, e me disseste mentiras; declara-me pois agora  com que poderias ser amarrado? E ele lhe disse: Se teceres sete tranças dos cabelos  da minha cabeça com os liços da teia.

[[v7-16-14]]

^<<v7-16-14,14>>^ E ela as fixou com uma estaca, e disse-lhe: os Filisteus vêm  sobre ti, Sansão. Então despertou do seu sono, e arrancou a estaca das tranças  tecidas, juntamente  com o liço da teia.

[[v7-16-15]]

^<<v7-16-15,15>>^ Então ela lhe disse: Como dirás: Tenho-te amor, não estando  comigo o teu coração? já três vezes zombaste de mim, e ainda me não declaraste em que consiste  a tua força.

[[v7-16-16]]

^<<v7-16-16,16>>^ E sucedeu que, importunando-o ela todos os dias com as suas palavras, e molestando-o, a sua alma se angustiou até à morte.

[[v7-16-17]]

^<<v7-16-17,17>>^ E descobriu-lhe todo o seu coração, e disse-lhe: Nunca subiu navalha à minha cabeça, porque sou  nazireu de Deus desde o ventre de minha mãe: se viesse a ser rapado, ir-se-ia de mim a minha força, e me enfraqueceria, e seria como todos os mais  homens.

[[v7-16-18]]

^<<v7-16-18,18>>^ Vendo pois Dalila que já lhe descobrira todo o seu coração, enviou, e chamou os príncipes dos filisteus, dizendo: Subi esta vez, porque agora  me descobriu ele todo o seu coração. E os príncipes dos filisteus subiram a ela, e trouxeram o dinheiro na sua mão.

[[v7-16-19]]

^<<v7-16-19,19>>^ Então ela o fez dormir sobre os seus joelhos, e chamou a um  homem, e rapou-lhe as sete tranças do cabelo  de sua cabeça: e começou a afligi-lo, e retirou-se dele a sua força.

[[v7-16-20]]

^<<v7-16-20,20>>^ E disse ela: Os filisteus vêm  sobre ti, Sansão. E despertou do seu sono, e disse: Sairei ainda  esta vez como dantes, e me livrarei. Porque ele não sabia que já o Senhor se tinha retirado dele.

[[v7-16-21]]

^<<v7-16-21,21>>^ Então os filisteus pegaram nele, e lhe arrancaram os olhos, e fizeram-no descer a Gaza, e amarraram-no com duas cadeias de bronze, e andava ele moendo no cárcere.

[[v7-16-22]]

^<<v7-16-22,22>>^ E o cabelo da sua cabeça lhe começou a crescer, como quando foi rapado.

[[v7-16-23]]

^<<v7-16-23,23>>^ Então os príncipes dos filisteus se ajuntaram para oferecer um  grande sacrifício ao seu deus Dagom, e para se alegrarem, e diziam: Nosso deus nos entregou nas mãos a Sansão, nosso inimigo.

[[v7-16-24]]

^<<v7-16-24,24>>^ Semelhantemente, vendo-o o povo, louvavam ao seu deus: porque diziam: Nosso deus nos entregou na mão o nosso inimigo, e ao que destruía a nossa terra, e ao que multiplicava os nossos mortos.

[[v7-16-25]]

^<<v7-16-25,25>>^ E sucedeu que, alegrando-se-lhes o coração, disseram: Chamai a Sansão, para que brinque diante de nós. E chamaram a Sansão do cárcere, e brincou diante deles, e fizeram-no estar em pé  entre as colunas.

[[v7-16-26]]

^<<v7-16-26,26>>^ Então disse Sansão ao moço que o tinha pela mão: Guia-me para que apalpe as colunas em que se sustém a casa, para que me encoste a elas.

[[v7-16-27]]

^<<v7-16-27,27>>^ Ora estava  a casa cheia de homens e mulheres: e também  ali estavam  todos os príncipes dos filisteus: e sobre o telhado havia  alguns três mil homens e mulheres, que estavam vendo brincar Sansão.

[[v7-16-28]]

^<<v7-16-28,28>>^ Então Sansão clamou ao Senhor, e disse: Senhor Jeová , peço-te que te lembres de mim, e esforça-me agora só esta vez, ó Deus, para que de uma vez me vingue dos filisteus, pelos meus dois olhos.

[[v7-16-29]]

^<<v7-16-29,29>>^ Abraçou-se pois Sansão com as duas colunas do meio, em que se sustinha a casa, e arrimou-se sobre elas, com a sua mão direita numa, e com a sua esquerda na outra.

[[v7-16-30]]

^<<v7-16-30,30>>^ E disse Sansão: Morra eu com os filisteus. E inclinou-se com força, e a casa caiu sobre os príncipes e sobre todo o povo que nela havia : e foram mais os mortos que matou na sua morte do que os  que matara na sua vida.

[[v7-16-31]]

^<<v7-16-31,31>>^ Então seus irmãos desceram, e toda a casa de seu pai, e tomaram-no, e subiram com ele , e sepultaram-no entre Zorá e Estaol, no sepulcro de Manué, seu pai: e julgou ele a Israel vinte anos.

'''

xref:007-juizes/007-juizes-015.adoc#v7-15-0[&#60; Capítulo Anterior] | <<v7-16-0,Topo>> | xref:007-juizes/007-juizes-017.adoc#v7-17-0[Próximo Capítulo &#62;]