include::./index.adoc[]

[[v7-7-0]]
=== Juízes, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-7-1]]

^<<v7-7-1,1>>^ ENTÃO Jerubaal (que é  Gideão) se levantou de madrugada, e todo o povo que com ele havia , e se acamparam junto à fonte de Harode; de maneira que tinha o arraial dos midianitas para o norte, pelo outeiro de Moré no vale.

[[v7-7-2]]

^<<v7-7-2,2>>^ E disse o Senhor a Gideão: Muito é  o povo que está  contigo, para eu  dar aos midianitas em sua mão; a fim de que Israel se não glorie contra mim, dizendo: A minha mão me livrou.

[[v7-7-3]]

^<<v7-7-3,3>>^ Agora pois apregoa aos ouvidos do povo dizendo: Quem for  covarde e medroso, volte, e vá-se apressadamente das montanhas de Gileade. Então voltaram do povo vinte e dois mil, e dez mil ficaram.

[[v7-7-4]]

^<<v7-7-4,4>>^ E disse o Senhor a Gideão: Ainda muito povo há : faze-os descer às águas, e ali tos provarei: e será que  aquele de que eu te disser: Este irá contigo, esse contigo irá; porém todo aquele, de que eu te disser: Este não irá contigo, esse não irá.

[[v7-7-5]]

^<<v7-7-5,5>>^ E fez descer o povo às águas. Então o Senhor disse a Gideão: Qualquer que lamber as águas com a sua língua, como as  lambe o cão, esse porás à parte; como  também a todo aquele que se abaixar de joelhos a beber.

[[v7-7-6]]

^<<v7-7-6,6>>^ E foi o número dos que lamberam, levando a mão à boca, trezentos homens; e todo o resto do povo se abaixou de joelhos a beber as águas,

[[v7-7-7]]

^<<v7-7-7,7>>^ E disse o Senhor a Gideão: Com estes trezentos homens que lamberam as águas  vos livrarei, e darei os midianitas na tua mão; pelo que toda a outra gente se vá cada um ao seu lugar.

[[v7-7-8]]

^<<v7-7-8,8>>^ E o povo tomou na sua mão a provisão e as suas buzinas, e ele enviou todos os outros  homens de Israel cada um à sua tenda, porém os trezentos homens reteve: e estava o arraial dos midianitas abaixo no vale.

[[v7-7-9]]

^<<v7-7-9,9>>^ E sucedeu que, naquela mesma noite, o Senhor lhe disse: Levanta-te, e desce ao arraial, porque o tenho dado na tua mão.

[[v7-7-10]]

^<<v7-7-10,10>>^ E, se ainda  temes descer, desce tu e teu moço Pura ao arraial;

[[v7-7-11]]

^<<v7-7-11,11>>^ E ouvirás o que dizem, e então se esforçarão as tuas mãos e descerás ao arraial. Então desceu ele com o seu moço Pura até ao extremo das sentinelas que estavam  no arraial.

[[v7-7-12]]

^<<v7-7-12,12>>^ E os midianitas, e amalequitas, e todos os filhos do oriente jaziam no vale como gafanhotos em multidão: e eram  inumeráveis os seus camelos, como a areia que há  na praia do mar em multidão.

[[v7-7-13]]

^<<v7-7-13,13>>^ Chegando pois Gideão, eis que estava  contando um homem ao seu companheiro um  sonho, e dizia: Eis que um  sonho sonhei, eis que um pão de cevada torrado rodava pelo arraial dos midianitas, e chegava até às tendas, e as feriu, e caíram, e as transtornou de cima para baixo , e ficaram abatidas.

[[v7-7-14]]

^<<v7-7-14,14>>^ E respondeu o seu companheiro, e disse: Não é  isto outra cousa, senão a espada de Gideão, filho de Joás, varão israelita. Deus tem dado na sua mão aos midianitas, e a todo este arraial.

[[v7-7-15]]

^<<v7-7-15,15>>^ E sucedeu que , ouvindo Gideão a narração deste sonho, e a sua explicação, adorou; e tornou ao arraial de Israel, e disse: Levantai-vos, porque o Senhor tem dado o arraial dos midianitas nas vossas mãos.

[[v7-7-16]]

^<<v7-7-16,16>>^ Então repartiu os trezentos homens em três esquadrões: e deu- lhes  a cada um nas suas mãos buzinas, e cântaros vazios, com tochas neles acesas.

[[v7-7-17]]

^<<v7-7-17,17>>^ E disse-lhes: Olhai para mim, e fazei como eu fizer : e eis que chegando eu ao extremo do arraial, será que  como eu fizer, assim fareis vós.

[[v7-7-18]]

^<<v7-7-18,18>>^ Tocando eu e todos os que comigo estiverem  a buzina, então também vós tocareis a buzina ao redor de todo o arraial, e direis: Pelo Senhor, e Gideão.

[[v7-7-19]]

^<<v7-7-19,19>>^ Chegou pois Gideão, e os cem homens que com ele iam , ao extremo do arraial, ao princípio da vigília da meia-noite, havendo-se já posto as guardas: e tocaram as buzinas, e partiram os cântaros, que tinham  nas mãos.

[[v7-7-20]]

^<<v7-7-20,20>>^ Assim tocaram os três esquadrões as buzinas, e partiram os cântaros, e tinham nas suas mãos esquerdas as tochas acesas, e nas suas mãos direitas as buzinas, que tocavam; e exclamaram: Espada do Senhor e de Gideão.

[[v7-7-21]]

^<<v7-7-21,21>>^ E ficou-se cada um no seu lugar ao redor do arraial: então todo o exército deitou a correr, e, gritando, fugiram.

[[v7-7-22]]

^<<v7-7-22,22>>^ Tocando pois os trezentos as buzinas, o Senhor tornou a espada dum contra o outro e isto  em todo o arraial: e o exército fugiu para Zererá, até Bete-Sita, até aos limites de Abel-Meola, acima de Tabate.

[[v7-7-23]]

^<<v7-7-23,23>>^ Então os homens de Israel, de Naftali, e de Aser e de todo o Manassés foram convocados, e perseguiram aos midianitas.

[[v7-7-24]]

^<<v7-7-24,24>>^ Também Gideão enviou mensageiros a todas as montanhas de Efraim, dizendo: Descei ao encontro dos midianitas, e tomai-lhes as águas até Bete-Bara, a saber, o Jordão. Convocados pois todos os homens de Efraim, tomaram- lhes  as águas até Bete-Bara e Jordão.

[[v7-7-25]]

^<<v7-7-25,25>>^ E prenderam a dois príncipes dos midianitas, a Orebe e a Zeebe; e mataram a Orebe na penha de Orebe, e a Zeebe mataram no lagar de Zeebe, e perseguiram aos midianitas: e trouxeram as cabeças de Orebe e de Zeebe a Gideão, dalém do Jordão.

'''

xref:007-juizes/007-juizes-006.adoc#v7-6-0[&#60; Capítulo Anterior] | <<v7-7-0,Topo>> | xref:007-juizes/007-juizes-008.adoc#v7-8-0[Próximo Capítulo &#62;]