include::./index.adoc[]

[[v7-6-0]]
=== Juízes, 6
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-6-1]]

^<<v7-6-1,1>>^ PORÉM os filhos de Israel fizeram o que parecia  mal aos olhos do Senhor: e o Senhor os deu na mão dos midianitas por sete anos.

[[v7-6-2]]

^<<v7-6-2,2>>^ E, prevalecendo a mão dos midianitas sobre Israel, fizeram os filhos de Israel para si, por causa dos midianitas, as covas que estão  nos montes, e as cavernas e as fortificações.

[[v7-6-3]]

^<<v7-6-3,3>>^ Porque sucedia que , semeando Israel, subiram os midianitas e os amalequitas; e também os do oriente contra ele subiam.

[[v7-6-4]]

^<<v7-6-4,4>>^ E punham-se contra eles em campo, e destruíam a novidade da terra, até chegarem a Gaza: e não deixavam mantimento em Israel, nem ovelhas, nem bois, nem jumentos.

[[v7-6-5]]

^<<v7-6-5,5>>^ Porque subiam com os seus gados e tendas; vinham como gafanhotos, em tanta  multidão que não se podiam contar, nem  a eles nem aos seus camelos: e entravam na terra, para a destruir.

[[v7-6-6]]

^<<v7-6-6,6>>^ Assim Israel empobreceu muito pela presença dos midianitas: então os filhos de Israel clamaram ao Senhor.

[[v7-6-7]]

^<<v7-6-7,7>>^ E sucedeu que , clamando os filhos de Israel ao Senhor por causa dos midianitas,

[[v7-6-8]]

^<<v7-6-8,8>>^ Enviou o Senhor um  homem profeta aos filhos de Israel, que lhes disse: Assim diz o Senhor, Deus de Israel: Do Egito eu vos fiz subir, e vos tirei da casa da servidão;

[[v7-6-9]]

^<<v7-6-9,9>>^ E vos livrei da mão dos egípcios, e da mão de todos quantos vos oprimiam; e os expeli de diante de vós, e a vós dei a sua terra;

[[v7-6-10]]

^<<v7-6-10,10>>^ E vos disse: Eu sou  o Senhor vosso Deus; não temais aos deuses dos amorreus, em cuja terra habitais: mas não destes ouvidos à minha voz.

[[v7-6-11]]

^<<v7-6-11,11>>^ Então o anjo do Senhor veio, e assentou-se debaixo do carvalho que está  em Ofra, que pertencia  a Joás, abiezrita: e Gideão, seu filho, estava malhando o trigo no lagar, para o  salvar dos midianitas.

[[v7-6-12]]

^<<v7-6-12,12>>^ Então o anjo do Senhor lhe apareceu, e lhe disse: O Senhor é  contigo, varão valoroso.

[[v7-6-13]]

^<<v7-6-13,13>>^ Mas Gideão lhe respondeu: Ai, senhor meu, se o Senhor é conosco por que tudo isto nos sobreveio? e que é feito de  todas as suas maravilhas que nossos pais nos contaram, dizendo: Não nos fez o Senhor subir do Egito? Porém agora o Senhor nos desamparou, e nos deu na mão dos midianitas.

[[v7-6-14]]

^<<v7-6-14,14>>^ Então o Senhor olhou para ele, e disse: Vai nesta tua força e livrarás a Israel da mão dos midianitas: porventura  não te enviei eu ?

[[v7-6-15]]

^<<v7-6-15,15>>^ E ele lhe disse: Ai, senhor meu, com que livrarei a Israel? eis que o meu milheiro é  o mais pobre em Manassés, e eu o menor na casa de meu pai.

[[v7-6-16]]

^<<v7-6-16,16>>^ E o Senhor lhe disse: Porquanto eu hei de ser contigo, tu ferirás aos midianitas como se fossem  um só  homem.

[[v7-6-17]]

^<<v7-6-17,17>>^ E ele lhe disse: Se agora tenho achado graça aos teus olhos, dá-me um sinal de que és o que  comigo falas.

[[v7-6-18]]

^<<v7-6-18,18>>^ Rogo-te que daqui te não apartes, até que eu venha a ti, e traga o meu presente, e o ponha perante ti. E disse: Eu esperarei até que voltes.

[[v7-6-19]]

^<<v7-6-19,19>>^ E entrou Gideão e preparou um cabrito e bolos  asmos dum efa de farinha; a carne pôs num açafate e o caldo pôs numa panela: e trouxe-lho até debaixo do carvalho, e lho  apresentou.

[[v7-6-20]]

^<<v7-6-20,20>>^ Porém o anjo de Deus lhe disse: Toma a carne e os bolos  asmos e põe- nos  sobre esta penha e verte o caldo. E assim o fez.

[[v7-6-21]]

^<<v7-6-21,21>>^ E o anjo do Senhor estendeu a ponta do cajado, que estava  na sua mão, e tocou a carne e os bolos  asmos: então subiu fogo da penha, e consumiu a carne e os bolos  asmos; e o anjo do Senhor desapareceu de seus olhos.

[[v7-6-22]]

^<<v7-6-22,22>>^ Então viu Gideão que era  o anjo do Senhor; e disse Gideão: Ah! Senhor, Jeová, que eu vi o anjo do Senhor face a face.

[[v7-6-23]]

^<<v7-6-23,23>>^ Porém o Senhor lhe disse: Paz seja  contigo: não temas: não morrerás.

[[v7-6-24]]

^<<v7-6-24,24>>^ Então Gideão edificou ali um altar ao Senhor, e lhe chamou, Senhor é  paz: e  ainda até ao dia de  hoje está  em Ofra dos abiezritas.

[[v7-6-25]]

^<<v7-6-25,25>>^ E aconteceu, naquela mesma noite, que o Senhor lhe disse: toma o boi de teu pai, a saber, o segundo boi de sete anos: e derriba o altar de Baal, que é de teu pai; e corta o bosque que está  ao pé dele.

[[v7-6-26]]

^<<v7-6-26,26>>^ E edifica ao Senhor teu Deus um altar no cume deste lugar forte, num lugar conveniente: e toma o segundo boi, e o oferecerás em holocausto com a lenha que cortares do bosque.

[[v7-6-27]]

^<<v7-6-27,27>>^ Então Gideão tomou dez homens dentre os seus servos, e fez como o Senhor lhe dissera: e sucedeu que , temendo ele a casa de seu pai, e os homens daquela cidade, não o fez de dia, mas fê- lo  de noite.

[[v7-6-28]]

^<<v7-6-28,28>>^ Levantando-se pois os homens daquela cidade de madrugada, eis que estava o altar de Baal derribado, e o bosque, que estava  ao pé dele, cortado: e o segundo boi foi oferecido no altar de novo  edificado.

[[v7-6-29]]

^<<v7-6-29,29>>^ E uns aos outros disseram: Quem fez esta cousa? E, esquadrinhando, e inquirindo, disseram: Gideão, o filho de Joás, fez esta cousa.

[[v7-6-30]]

^<<v7-6-30,30>>^ Então os homens daquela cidade disseram a Joás: Tira para fora a teu filho para que morra, pois derribou o altar de Baal, e cortou o bosque que estava  ao pé dele.

[[v7-6-31]]

^<<v7-6-31,31>>^ Porém Joás disse a todos os que se puseram contra ele: Contendereis vós por Baal? livrá-lo-eis vós? qualquer que por ele contender ainda esta manhã será morto: se é  deus, por si mesmo contenda; pois derribaram o seu altar.

[[v7-6-32]]

^<<v7-6-32,32>>^ Pelo que naquele dia lhe chamaram Jerubaal, dizendo: Baal contenda contra ele, pois derribou o seu altar.

[[v7-6-33]]

^<<v7-6-33,33>>^ E todos os midianitas e amalequitas, e os filhos do oriente se ajuntaram num corpo, e passaram, e puseram o seu  campo no vale de Jezreel.

[[v7-6-34]]

^<<v7-6-34,34>>^ Então o espírito do Senhor revestiu a Gideão, o qual tocou a buzina, e os abiezritas se ajuntaram após dele.

[[v7-6-35]]

^<<v7-6-35,35>>^ E enviou mensageiros por toda a tribo de  Manassés, que também se convocou após dele: também enviou mensageiros a Eser, e a Zebulom, e a Naftali, e saíram-lhe ao encontro.

[[v7-6-36]]

^<<v7-6-36,36>>^ E disse Gideão a Deus: Se hás de livrar a Israel por minha mão, como tens dito,

[[v7-6-37]]

^<<v7-6-37,37>>^ Eis que eu porei um velo de lã na eira: se o orvalho estiver somente no velo, e secura sobre toda a terra, então conhecerei que hás de livrar a Israel por minha mão, como tens dito.

[[v7-6-38]]

^<<v7-6-38,38>>^ E assim sucedeu: porque ao outro dia se levantou de madrugada, e apertou o velo: e do orvalho do velo espremeu uma taça cheia de água.

[[v7-6-39]]

^<<v7-6-39,39>>^ E disse Gideão a Deus: Não se acenda contra mim a tua ira, se ainda falar só esta vez: rogo-te que só esta vez faça a prova com o velo; rogo-te que só no velo haja secura, e em toda a terra haja o orvalho.

[[v7-6-40]]

^<<v7-6-40,40>>^ E Deus assim o fez naquela noite: pois só no velo havia secura, e sobre toda a terra havia orvalho.

'''

xref:007-juizes/007-juizes-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-juizes/007-juizes-007.adoc#v7-7-0[Próximo Capítulo &#62;]