include::./index.adoc[]

[[v7-14-0]]
=== Juízes, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-14-1]]

^<<v7-14-1,1>>^ E DESCEU Sansão a Timnata: e, vendo em Timnata a uma mulher das filhas dos filisteus,

[[v7-14-2]]

^<<v7-14-2,2>>^ Subiu, e declarou-o a seu pai e a sua mãe, e disse: Vi uma  mulher em Timnata, das filhas dos filisteus; agora pois, tomai-ma por mulher.

[[v7-14-3]]

^<<v7-14-3,3>>^ Porém seu pai e sua mãe lhe disseram: Não há porventura  mulher entre as filhas de teus irmãos, nem entre todo o meu povo, para que tu vás tomar mulher dos filisteus, daqueles incircuncisos? E disse Sansão a seu pai: Tomai-me esta, porque ela agrada aos meus olhos.

[[v7-14-4]]

^<<v7-14-4,4>>^ Mas seu pai e sua mãe não sabiam que isto vinha  do Senhor; pois buscava ocasião contra os filisteus: porquanto naquele tempo os filisteus dominavam sobre Israel.

[[v7-14-5]]

^<<v7-14-5,5>>^ Desceu pois Sansão com seu pai e com sua mãe a Timnata: e, chegando às vinhas de Timnata, eis que um filho de leão, bramando, lhe saiu  ao encontro.

[[v7-14-6]]

^<<v7-14-6,6>>^ Então o espírito do Senhor se apossou dele tão possantemente que o fendeu de alto a baixo , como quem fende um cabrito, sem ter  nada na sua mão: porém nem a seu pai nem a sua mãe deu a saber o que tinha feito.

[[v7-14-7]]

^<<v7-14-7,7>>^ E desceu, e falou àquela mulher, e agradou aos olhos de Sansão.

[[v7-14-8]]

^<<v7-14-8,8>>^ E depois de alguns dias voltou ele  para a tomar: e, apartando-se do caminho  a ver o corpo do leão morto, eis que no corpo do leão havia  um enxame de abelhas com mel.

[[v7-14-9]]

^<<v7-14-9,9>>^ E tomou-o nas suas mãos, e foi-se andando e comendo dele ; e foi-se a seu pai e a sua mãe, e deu-lhes dele , e comeram, porém não lhes deu a saber que tomara o mel do corpo do leão.

[[v7-14-10]]

^<<v7-14-10,10>>^ Descendo pois seu pai àquela mulher, fez Sansão ali um banquete: porque assim o costumavam fazer os mancebos.

[[v7-14-11]]

^<<v7-14-11,11>>^ E sucedeu que, como o vissem, tomaram trinta companheiros para estarem com ele.

[[v7-14-12]]

^<<v7-14-12,12>>^ Disse-lhes pois Sansão: Eu vos darei um  enigma a adivinhar e , se nos sete dias das bodas mo declarardes e descobrirdes, vos darei trinta lençóis e trinta mudas de vestidos.

[[v7-14-13]]

^<<v7-14-13,13>>^ E, se mo não puderdes declarar, vós me dareis a mim  os trinta lençóis e as trinta mudas de vestidos. E eles lhe disseram: Dá- nos  o teu enigma a adivinhar, para que o ouçamos.

[[v7-14-14]]

^<<v7-14-14,14>>^ Então lhes disse: Do comedor saiu comida, e doçura saiu do forte. E em três dias não puderam declarar o enigma.

[[v7-14-15]]

^<<v7-14-15,15>>^ E sucedeu que, ao sétimo dia, disseram à mulher de Sansão: Persuade a teu marido que nos declare o enigma para que porventura não queimemos a fogo a ti e à casa de teu pai: chamastes-nos vós aqui para possuir o que é nosso, não é assim ?

[[v7-14-16]]

^<<v7-14-16,16>>^ E a mulher de Sansão chorou diante dele, e disse: Tão  somente me aborreces, e não me amas; pois  deste aos filhos do meu povo um  enigma a adivinhar, e ainda  mo não declaraste a mim. E ele lhe disse: Eis que nem a meu pai nem a minha mãe o declarei, e to declararia a ti?

[[v7-14-17]]

^<<v7-14-17,17>>^ E chorou diante dele os sete dias em que celebravam as bodas: sucedeu pois que ao sétimo dia lho declarou, porquanto o importunava; então ela  declarou o enigma aos filhos do seu povo.

[[v7-14-18]]

^<<v7-14-18,18>>^ Disseram-lhe pois os homens daquela cidade, ao sétimo dia, antes de se pôr o sol: Que cousa há  mais doce do que o mel? e que cousa há  mais forte do que o leão? E ele lhes disse: Se vós não lavrásseis com a minha novilha, nunca teríeis descoberto o meu enigma.

[[v7-14-19]]

^<<v7-14-19,19>>^ Então o espírito do Senhor tão possantemente se apossou dele, que desceu aos ascalonitas, e matou deles trinta homens, e tomou os seus vestidos, e deu as mudas de vestidos aos que declararam o enigma: porém acendeu-se a sua ira, e subiu à casa de seu pai.

[[v7-14-20]]

^<<v7-14-20,20>>^ E a mulher de Sansão foi dada  ao seu companheiro, que o acompanhava.

'''

xref:007-juizes/007-juizes-013.adoc#v7-13-0[&#60; Capítulo Anterior] | <<v7-14-0,Topo>> | xref:007-juizes/007-juizes-015.adoc#v7-15-0[Próximo Capítulo &#62;]