include::./index.adoc[]

[[v7-15-0]]
=== Juízes, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-15-1]]

^<<v7-15-1,1>>^ E ACONTECEU, depois de alguns  dias, que na sega do trigo Sansão visitou a sua mulher com um cabrito, e disse: Entrarei na câmara à minha mulher. Porém o pai dela não o deixou entrar.

[[v7-15-2]]

^<<v7-15-2,2>>^ Porque disse seu pai: Por certo dizia eu que de todo a aborrecias: de sorte que a dei ao teu companheiro: porém não é  sua irmã mais nova, mais formosa do que ela? toma-a pois em seu lugar.

[[v7-15-3]]

^<<v7-15-3,3>>^ Então Sansão disse acerca deles: Inocente sou esta vez para com os filisteus, quando lhes fizer algum  mal.

[[v7-15-4]]

^<<v7-15-4,4>>^ E foi Sansão, e tomou trezentas raposas: e, tomando tições, as virou cauda a cauda, e lhes pôs um tição no meio de cada duas caudas.

[[v7-15-5]]

^<<v7-15-5,5>>^ E chegou fogo aos tições, e largou-as na seara dos filisteus: e assim  abrasou os molhos com a sega do trigo, e as vinhas com os olivais.

[[v7-15-6]]

^<<v7-15-6,6>>^ Então disseram os filisteus: Quem fez isto? E disseram: Sansão, o genro de Timnata, porque lhe tomou a sua mulher, e a deu a seu companheiro. Então subiram os filisteus e queimaram a fogo a ela e a seu pai.

[[v7-15-7]]

^<<v7-15-7,7>>^ Então lhes disse Sansão: Assim o havíeis de fazer? pois, havendo-me vingado eu de vós, então cessarei.

[[v7-15-8]]

^<<v7-15-8,8>>^ E feriu-os com grande ferimento, perna juntamente com coxa: e desceu, e habitou no cume da rocha de Etã.

[[v7-15-9]]

^<<v7-15-9,9>>^ Então os filisteus subiram, e acamparam-se contra Judá, e estenderam-se por Lequi.

[[v7-15-10]]

^<<v7-15-10,10>>^ E disseram os homens de Judá: Por que subistes contra nós? E eles disseram: Subimos para amarrar a Sansão, para lhe fazer a ele como ele nos fez a nós.

[[v7-15-11]]

^<<v7-15-11,11>>^ Então três mil homens de Judá desceram até à cova da rocha de Etã, e disseram a Sansão: Não sabias tu que os filisteus dominam sobre nós? por que pois  nos fizeste isto? E ele lhes disse: Assim  como eles me fizeram a mim, eu lhes fiz a eles.

[[v7-15-12]]

^<<v7-15-12,12>>^ E disseram-lhe: Descemos para te amarrar, para te entregar nas mãos dos filisteus. Então Sansão lhes disse: Jurai-me que vós mesmos me não acometereis.

[[v7-15-13]]

^<<v7-15-13,13>>^ E eles lhe falaram, dizendo: Não mas fortemente te amarraremos, e te entregaremos na sua mão; porém de maneira nenhuma te mataremos. E amarraram-no com duas cordas novas e fizeram-no subir da rocha.

[[v7-15-14]]

^<<v7-15-14,14>>^ E , vindo ele a Lequi, os filisteus lhe saíram  ao encontro, jubilando: porém o espírito do Senhor possantemente se apossou dele, e as cordas que ele tinha  nos braços se tornaram como fios de linho que estão queimados do fogo, e as suas amarraduras se desfizeram das suas mãos.

[[v7-15-15]]

^<<v7-15-15,15>>^ E achou uma queixada fresca dum  jumento, e estendeu a sua mão, e, tomou-a, e feriu com ela mil homens.

[[v7-15-16]]

^<<v7-15-16,16>>^ Então disse Sansão: Com uma  queixada de jumento um montão, dois montões: com uma  queixada de jumento feri a mil homens.

[[v7-15-17]]

^<<v7-15-17,17>>^ E aconteceu que, acabando ele de falar, lançou a queixada da sua mão: e chamou àquele lugar Ramate-Lequi.

[[v7-15-18]]

^<<v7-15-18,18>>^ E como tivesse grande sede, clamou ao Senhor, e disse: Pela mão do teu servo tu deste esta grande salvação: morrerei eu pois agora de sede, e cairei na mão destes incircuncisos?

[[v7-15-19]]

^<<v7-15-19,19>>^ Então o Senhor fendeu a caverna que estava  em Lequi; e saiu dela água, e bebeu; e o seu espírito tornou, e reviveu: pelo que chamou o seu nome: A fonte do que clama, a qual está  em Lequi até ao dia de  hoje.

[[v7-15-20]]

^<<v7-15-20,20>>^ E julgou a Israel, nos dias dos filisteus, vinte anos.

'''

xref:007-juizes/007-juizes-014.adoc#v7-14-0[&#60; Capítulo Anterior] | <<v7-15-0,Topo>> | xref:007-juizes/007-juizes-016.adoc#v7-16-0[Próximo Capítulo &#62;]