include::./index.adoc[]

[[v7-5-0]]
=== Juízes, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-5-1]]

^<<v7-5-1,1>>^ E CANTOU Débora e Baraque, filho de Abinoão, naquele mesmo dia, dizendo:

[[v7-5-2]]

^<<v7-5-2,2>>^ Porquanto os chefes se puseram à frente em Israel, porquanto o povo se ofereceu voluntariamente, louvai ao Senhor.

[[v7-5-3]]

^<<v7-5-3,3>>^ Ouvi, reis; dai ouvidos, príncipes: eu, eu cantarei ao Senhor; salmodiarei ao Senhor Deus de Israel.

[[v7-5-4]]

^<<v7-5-4,4>>^ Ó Senhor, saindo tu de Seir, caminhando tu desde o campo de Edom, a terra estremeceu; até os céus gotejaram: até as nuvens gotejaram águas.

[[v7-5-5]]

^<<v7-5-5,5>>^ Os montes se derreteram diante do Senhor, e até Sinai diante do Senhor Deus de Israel.

[[v7-5-6]]

^<<v7-5-6,6>>^ Nos dias de Sangar, filho de Anate, nos dias de Jael cessaram os caminhos de se percorrerem : e os que andavam por veredas iam por caminhos torcidos.

[[v7-5-7]]

^<<v7-5-7,7>>^ Cessaram as aldeias em Israel, cessaram: até que eu, Débora, me levantei, por  mãe em Israel me levantei.

[[v7-5-8]]

^<<v7-5-8,8>>^ E se  escolhia deuses novos, logo a guerra estava  às portas: via-se por isso escudo ou lança entre quarenta mil em Israel?

[[v7-5-9]]

^<<v7-5-9,9>>^ Meu coração é para os legisladores de Israel, que voluntariamente se ofereceram entre o povo; louvai ao Senhor.

[[v7-5-10]]

^<<v7-5-10,10>>^ Vós  os que cavalgais sobre jumentas brancas, que vos assentais em juízo, e que andais pelo caminho, falai disto.

[[v7-5-11]]

^<<v7-5-11,11>>^ Onde se ouve  o estrondo dos frecheiros, entre os lugares onde se tiram águas, ali falai das justiças do Senhor das justiças que fez  às suas aldeias em Israel: então o povo do Senhor descia às portas.

[[v7-5-12]]

^<<v7-5-12,12>>^ Desperta, desperta, Débora, desperta, desperta, entoa um  cântico: levanta-te, Baraque, e leva presos a teus prisioneiros, tu , filho de Abinoão.

[[v7-5-13]]

^<<v7-5-13,13>>^ Então o Senhor  fez dominar sobre os magníficos entre  o povo ao que ficou de resto: fez-me o Senhor dominar sobre os valentes.

[[v7-5-14]]

^<<v7-5-14,14>>^ De Efraim saiu  a sua raiz contra Amaleque: e após de ti vinha  Benjamim dentre os teus povos: de Maquir e Zebulom desceram os legisladores, passando com o cajado do escriba.

[[v7-5-15]]

^<<v7-5-15,15>>^ Também os principais de Issacar, foram com Débora; e como Issacar, assim também Baraque, foi enviado a pé para o vale: nas correntes de Rúben foram  grandes as resoluções do coração.

[[v7-5-16]]

^<<v7-5-16,16>>^ Porque ficaste tu entre os currais para ouvires os balidos dos rebanhos? Nas divisões de Rúben tiveram  grandes esquadrinhações do coração.

[[v7-5-17]]

^<<v7-5-17,17>>^ Gileade se ficou dalém do Jordão, e Dã por que se deteve em navios? Aser se assentou nos portos do mar, e ficou nas suas ruínas.

[[v7-5-18]]

^<<v7-5-18,18>>^ Zebulom é um  povo que expôs a sua vida à morte, como também Naftali, nas alturas do campo.

[[v7-5-19]]

^<<v7-5-19,19>>^ Vieram reis, pelejaram: então pelejaram os reis de Canaã em Taanaque, junto às águas de Megido: não tomaram ganho de prata.

[[v7-5-20]]

^<<v7-5-20,20>>^ Desde os céus pelejaram: até  as estrelas desde os lugares dos seus cursos pelejaram contra Sísera.

[[v7-5-21]]

^<<v7-5-21,21>>^ O ribeiro de Quisom os arrastou, aquele antigo ribeiro, o ribeiro de Quisom. Pisaste, ó minha alma, a força.

[[v7-5-22]]

^<<v7-5-22,22>>^ Então as unhas dos cavalos se despedaçaram: pelo galopar, o galopar dos seus valentes.

[[v7-5-23]]

^<<v7-5-23,23>>^ Amaldiçoai a Meroz, diz o anjo do Senhor, acremente amaldiçoai aos seus moradores: porquanto não vieram em socorro do Senhor, em socorro do Senhor com os valorosos.

[[v7-5-24]]

^<<v7-5-24,24>>^ Bendita seja sobre as mulheres Jael, mulher de Héber, o queneu: bendita seja sobre as mulheres nas tendas.

[[v7-5-25]]

^<<v7-5-25,25>>^ Água pediu ele, leite lhe  deu ela: em taça de príncipes lhe  ofereceu manteiga.

[[v7-5-26]]

^<<v7-5-26,26>>^ À estaca estendeu a sua mão esquerda , e ao maço dos trabalhadores a sua direita: e matou a Sísera, e  rachou-lhe a cabeça, quando lhe pregou e atravessou as fontes.

[[v7-5-27]]

^<<v7-5-27,27>>^ Entre os seus pés se encurvou, caiu, ficou estirado: entre os seus pés se encurvou, caiu: onde se encurvou ali ficou abatido.

[[v7-5-28]]

^<<v7-5-28,28>>^ A mãe de Sísera olhava pela janela, e exclamava pela grade: Por que tarda em vir o seu carro? por que se demoram os passos dos seus carros?

[[v7-5-29]]

^<<v7-5-29,29>>^ As mais sábias das suas damas responderam; e até ela respondia a si mesma:

[[v7-5-30]]

^<<v7-5-30,30>>^ Porventura  não achariam e repartiriam despojos? uma ou  duas moças a cada homem? para Sísera despojos de várias cores, despojos de várias cores de bordados; de várias cores bordados de ambas as bandas, para os pescoços do despojo?

[[v7-5-31]]

^<<v7-5-31,31>>^ Assim, ó Senhor, pereçam todos os teus inimigos! Porém os que o amam sejam  como o sol quando sai na sua força.

[[v7-5-32]]

^<<v7-5-32,32>>^ E sossegou a terra quarenta anos.

'''

xref:007-juizes/007-juizes-004.adoc#v7-4-0[&#60; Capítulo Anterior] | <<v7-5-0,Topo>> | xref:007-juizes/007-juizes-006.adoc#v7-6-0[Próximo Capítulo &#62;]