include::./index.adoc[]

[[v7-12-0]]
=== Juízes, 12
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-12-1]]

^<<v7-12-1,1>>^ ENTÃO se convocaram os homens de Efraim, e passaram para o norte, e disseram a Jefté: Por que passaste a combater contra os filhos de Amom, e não nos chamaste para ir contigo? queimaremos a fogo a tua casa contigo.

[[v7-12-2]]

^<<v7-12-2,2>>^ E Jefté lhes disse: Eu e o meu povo tivemos grande contenda com os filhos de Amom: e chamei-vos, e não me livrastes da sua mão;

[[v7-12-3]]

^<<v7-12-3,3>>^ E, vendo eu que me  não livráveis, pus a minha alma na minha mão, e passei aos filhos de Amom, e o Senhor mos entregou nas mãos: por que pois subistes vós hoje contra mim, para combater contra mim?

[[v7-12-4]]

^<<v7-12-4,4>>^ E ajuntou Jefté a todos os homens de Gileade, e combateu com Efraim: e os homens de Gileade feriram a Efraim; porque, estando os gileaditas entre Efraim e  Manassés, disseram: Fugitivos sois  de Efraim.

[[v7-12-5]]

^<<v7-12-5,5>>^ Porém tomaram os gileaditas aos efraimitas os vaus do Jordão: e sucedeu que, quando os fugitivos de Efraim diziam: Passarei; então os homens de Gileade lhes diziam: És tu efraimita? E dizendo ele: Não;

[[v7-12-6]]

^<<v7-12-6,6>>^ Então lhe diziam: Dize pois, Chibolete; porém ele  dizia: Sibolete, porque o  não podia pronunciar assim bem: então pegavam dele, e o degolavam nos vaus do Jordão; e caíram de Efraim naquele tempo quarenta e dois mil.

[[v7-12-7]]

^<<v7-12-7,7>>^ E Jefté julgou a Israel seis anos: e Jefté, o gileadita, faleceu, e foi sepultado nas cidades de Gileade.

[[v7-12-8]]

^<<v7-12-8,8>>^ E depois dele julgou a Israel Ebsã de Belém.

[[v7-12-9]]

^<<v7-12-9,9>>^ E tinha este trinta filhos; e pôs fora a trinta filhas; e trinta filhas trouxe de fora para seus filhos: e julgou a Israel sete anos.

[[v7-12-10]]

^<<v7-12-10,10>>^ Então faleceu Ebsã, e foi sepultado em Belém.

[[v7-12-11]]

^<<v7-12-11,11>>^ E depois dele julgou a Israel Elom, o zebulonita: e julgou a Israel dez anos.

[[v7-12-12]]

^<<v7-12-12,12>>^ E faleceu Elom, o zebulonita, e foi sepultado em Ajalom, na terra de Zebulom.

[[v7-12-13]]

^<<v7-12-13,13>>^ E depois dele julgou a Israel Abdom, filho de Hilel, o piratonita.

[[v7-12-14]]

^<<v7-12-14,14>>^ E tinha este quarenta filhos, e trinta filhos de filhos, que cavalgavam sobre setenta jumentos: e julgou a Israel oito anos.

[[v7-12-15]]

^<<v7-12-15,15>>^ Então faleceu Abdom, filho de Hilel, o piratonita: e foi sepultado em Piratom, na terra de Efraim, no monte do amalequita.

'''

xref:007-juizes/007-juizes-011.adoc#v7-11-0[&#60; Capítulo Anterior] | <<v7-12-0,Topo>> | xref:007-juizes/007-juizes-013.adoc#v7-13-0[Próximo Capítulo &#62;]