include::./index.adoc[]

[[v7-11-0]]
=== Juízes, 11
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-11-1]]

^<<v7-11-1,1>>^ ERA então Jefté, o gileadita, valente e valoroso, porém filho duma prostituta: mas Gileade gerara a Jefté.

[[v7-11-2]]

^<<v7-11-2,2>>^ Também a mulher de Gileade lhe deu filhos, e, sendo os filhos desta mulher já grandes, repeliram a Jefté, e lhe disseram: Não herdarás em casa de nosso pai, porque és filho doutra mulher.

[[v7-11-3]]

^<<v7-11-3,3>>^ Então Jefté fugiu de diante de seus irmãos, e habitou na terra de Tobe: e homens levianos se ajuntaram com Jefté, e saíam com ele.

[[v7-11-4]]

^<<v7-11-4,4>>^ E aconteceu que, depois de alguns  dias, os filhos de Amom pelejaram contra Israel.

[[v7-11-5]]

^<<v7-11-5,5>>^ Aconteceu  pois que , como os filhos de Amom pelejassem contra Israel, foram os anciãos de Gileade buscar a Jefté da terra de Tobe.

[[v7-11-6]]

^<<v7-11-6,6>>^ E disseram a Jefté: Vem, e sê-nos por cabeça: para que combatamos contra os filhos de Amom.

[[v7-11-7]]

^<<v7-11-7,7>>^ Porém Jefté disse aos anciãos de Gileade: porventura  não me aborrecestes a mim e não me repelistes da casa de meu pai? por que pois agora viestes a mim quando estais em aperto?

[[v7-11-8]]

^<<v7-11-8,8>>^ E disseram os anciãos de Gileade a Jefté: Por isso tornamos a ti, para que venhas conosco, e combatas contra os filhos de Amom, e nos sejas por cabeça sobre todos os moradores de Gileade.

[[v7-11-9]]

^<<v7-11-9,9>>^ Então Jefté disse aos anciãos de Gileade: Se me tornardes a levar  para combater contra os filhos de Amom, e o Senhor mos der diante de mim, então eu vos serei por cabeça?

[[v7-11-10]]

^<<v7-11-10,10>>^ E disseram os anciãos de Gileade a Jefté: O Senhor será testemunha entre nós, e assim o faremos conforme à tua palavra.

[[v7-11-11]]

^<<v7-11-11,11>>^ Assim Jefté foi com os anciãos de Gileade, e o povo o pôs por cabeça e príncipe sobre si: e Jefté falou todas as suas palavras perante o Senhor em Mizpá.

[[v7-11-12]]

^<<v7-11-12,12>>^ E enviou Jefté mensageiros ao rei dos filhos de Amom, dizendo: Que há entre mim e ti, que vieste a mim a pelejar contra a minha terra?

[[v7-11-13]]

^<<v7-11-13,13>>^ E disse o rei dos filhos de Amom aos mensageiros de Jefté: Porquanto, saindo Israel do Egito, tomou a minha terra, desde Arnom até Jaboque, e ainda  até ao Jordão: torna-ma pois agora em paz.

[[v7-11-14]]

^<<v7-11-14,14>>^ Porém Jefté prosseguiu ainda em enviar mensageiros ao rei dos filhos de Amom,

[[v7-11-15]]

^<<v7-11-15,15>>^ Dizendo-lhe: Assim diz Jefté: Israel não tomou, nem a terra dos moabitas nem a terra dos filhos de Amom;

[[v7-11-16]]

^<<v7-11-16,16>>^ Porque, subindo Israel do Egito, andou pelo deserto até ao Mar Vermelho, e chegou até Cades.

[[v7-11-17]]

^<<v7-11-17,17>>^ E Israel enviou mensageiros ao rei dos edomitas, dizendo: Rogo-te que me deixes passar pela tua terra. Porém o rei dos edomitas não lhe deu  ouvidos. Enviou também ao rei dos moabitas, o qual também não quis: e assim  Israel ficou em Cades.

[[v7-11-18]]

^<<v7-11-18,18>>^ Depois andou pelo deserto e rodeou a terra dos edomitas e a terra dos moabitas, e veio do nascente do sol à terra dos moabitas, e alojaram-se dalém de Arnom; porém não entraram nos limites dos moabitas, porque Arnom é  limite dos moabitas.

[[v7-11-19]]

^<<v7-11-19,19>>^ Mas Israel enviou mensageiros a Seom, rei dos amorreus, rei de Hesbom: e disse-lhe Israel: Deixa-nos, peço-te, passar pela tua terra até ao meu lugar.

[[v7-11-20]]

^<<v7-11-20,20>>^ Porém Seom não se fiou de Israel para este passar nos seus limites; antes Seom ajuntou todo o seu povo, e se acamparam em Jasa, e combateu contra Israel.

[[v7-11-21]]

^<<v7-11-21,21>>^ E o Senhor Deus de Israel deu a Seom com todo o seu povo na mão de Israel, e os feriram: e Israel tomou por herança toda a terra dos amorreus que habitavam naquela terra.

[[v7-11-22]]

^<<v7-11-22,22>>^ E por herança tomaram todos os limites dos amorreus, desde Arnom até Jaboque, e desde o deserto até ao Jordão.

[[v7-11-23]]

^<<v7-11-23,23>>^ Assim o Senhor Deus de Israel desapossou os amorreus de diante do seu povo de Israel: e os possuirias tu?

[[v7-11-24]]

^<<v7-11-24,24>>^ Não possuirias tu aquele que Camós, teu deus, desapossasse de diante de ti? assim possuiremos nós todos quantos o Senhor nosso Deus desapossar de diante de nós.

[[v7-11-25]]

^<<v7-11-25,25>>^ Agora pois és  tu ainda melhor do que Balaque, filho de Zipor, rei dos moabitas? porventura  contendeu ele em algum tempo com Israel, ou  pelejou alguma vez contra eles?

[[v7-11-26]]

^<<v7-11-26,26>>^ Enquanto Israel habitou trezentos anos em Hesbom e nas suas vilas, e em Aroer e nas suas vilas, em todas as cidades que estão  ao longo de Arnom, por que o não recuperaste naquele tempo?

[[v7-11-27]]

^<<v7-11-27,27>>^ Tão pouco pequei eu contra ti! porém tu usas mal comigo em pelejar contra mim: o Senhor, que é juiz, julgue hoje entre os filhos de Israel e entre os filhos de Amom.

[[v7-11-28]]

^<<v7-11-28,28>>^ Porém o rei dos filhos de Amom não deu ouvidos às palavras de Jefté, que lhe enviou.

[[v7-11-29]]

^<<v7-11-29,29>>^ Então o espírito do Senhor veio sobre Jefté, e atravessou ele por Gileade e Manassés: porque passou até Mizpá de Gileade, e de Mizpá de Gileade passou até  aos filhos de Amom.

[[v7-11-30]]

^<<v7-11-30,30>>^ E Jefté votou um voto ao Senhor e disse: Se totalmente  deres os filhos de Amom na minha mão,

[[v7-11-31]]

^<<v7-11-31,31>>^ Aquilo que, saindo da porta de minha casa, me sair ao encontro, voltando eu dos filhos de Amom em paz, isso será do Senhor, e o oferecerei em holocausto.

[[v7-11-32]]

^<<v7-11-32,32>>^ Assim Jefté passou aos filhos de Amom, a combater contra eles: e o Senhor os deu na sua mão.

[[v7-11-33]]

^<<v7-11-33,33>>^ E os feriu com grande mortandade, desde Aroer até chegar a Minite, vinte cidades, e até Abel-Queramim; assim foram subjugados os filhos de Amom diante dos filhos de Israel.

[[v7-11-34]]

^<<v7-11-34,34>>^ Vindo pois Jefté a Mizpá, à sua casa, eis que a sua filha lhe saiu ao encontro com adufes e com danças: e era  ela só a única; não tinha outro filho nem filha.

[[v7-11-35]]

^<<v7-11-35,35>>^ E aconteceu que, quando a viu, rasgou os seus vestidos, e disse: Ah! filha minha, muito me abateste, e és dentre os que me turbam! porque eu abri a minha boca ao Senhor, e não tornarei atrás.

[[v7-11-36]]

^<<v7-11-36,36>>^ E ela lhe disse: Pai meu, abriste tu a tua boca ao Senhor, faze de mim como saiu da tua boca: pois o Senhor te vingou dos teus inimigos, os filhos de Amom.

[[v7-11-37]]

^<<v7-11-37,37>>^ Disse mais a seu pai: Faça-se-me isto: deixa-me por dois meses que vá, e desça pelos montes, e chore a minha virgindade, eu e as minhas companheiras.

[[v7-11-38]]

^<<v7-11-38,38>>^ E disse ele: Vai. E deixou-a ir por dois meses: então foi-se ela com as suas companheiras, e chorou a sua virgindade pelos montes.

[[v7-11-39]]

^<<v7-11-39,39>>^ E sucedeu que, ao fim de dois meses, tornou ela para seu pai, o qual cumpriu nela o seu voto que tinha votado: e ela não conheceu varão; e daqui veio o costume em Israel,

[[v7-11-40]]

^<<v7-11-40,40>>^ Que  as filhas de Israel iam de ano em ano a lamentar a filha de Jefté, o gileadita, por quatro dias no ano.

'''

xref:007-juizes/007-juizes-010.adoc#v7-10-0[&#60; Capítulo Anterior] | <<v7-11-0,Topo>> | xref:007-juizes/007-juizes-012.adoc#v7-12-0[Próximo Capítulo &#62;]