include::./index.adoc[]

[[v7-19-0]]
=== Juízes, 19
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-19-1]]

^<<v7-19-1,1>>^ ACONTECEU também naqueles dias, em que não havia  rei em Israel, que houve um homem levita, que peregrinando aos lados da montanha de Efraim, tomou para si uma  mulher concubina, de Belém de Judá.

[[v7-19-2]]

^<<v7-19-2,2>>^ Porém a sua concubina adulterou contra ele, e foi dele para casa de seu pai, a Belém de Judá, e esteve ali alguns  dias, a saber , quatro meses.

[[v7-19-3]]

^<<v7-19-3,3>>^ E seu marido se levantou, e partiu após dela, para lhe falar conforme ao seu coração, e  para tornar a trazê-la: e o seu moço e um par de jumentos iam  com ele: e ela o levou a casa de seu pai, e, vendo-o o pai da moça, alegrou-se ao encontrar-se com ele.

[[v7-19-4]]

^<<v7-19-4,4>>^ E seu sogro, o pai da moça, o deteve, e ficou com ele três dias: e comeram e beberam, e passaram ali a noite.

[[v7-19-5]]

^<<v7-19-5,5>>^ E sucedeu que ao quarto dia pela manhã madrugaram, e ele levantou-se para partir: então o pai da moça disse a seu genro: Conforta o teu coração com um bocado de pão, e depois partireis.

[[v7-19-6]]

^<<v7-19-6,6>>^ Assentaram-se pois, e comeram ambos juntos, e beberam; e disse o pai da moça ao homem: Peço-te que ainda esta noite queiras passá-la aqui , e alegre-se o teu coração.

[[v7-19-7]]

^<<v7-19-7,7>>^ Porém o homem levantou-se para partir: mas seu sogro o constrangeu a tornar a passar ali a noite.

[[v7-19-8]]

^<<v7-19-8,8>>^ E, madrugando ao quinto dia pela manhã para partir, disse o pai da moça: Ora conforta o teu coração. E detiveram-se até já declinar o dia: e ambos juntos  comeram.

[[v7-19-9]]

^<<v7-19-9,9>>^ Então o homem levantou-se para partir, ele, e a sua concubina, e o seu moço: e disse-lhe seu sogro, o pai da moça: Eis que já o dia se abaixa, e já  a tarde vem entrando, peço-te que aqui  passes a noite; eis que já  o dia vai acabando, passa aqui a noite, e que o teu coração se alegre; e amanhã de madrugada levantai-vos a caminhar, e vai-te para a tua tenda.

[[v7-19-10]]

^<<v7-19-10,10>>^ Porém o homem não quis ali  passar a noite, mas levantou-se, e partiu, e veio até defronte de Jebus (que é  Jerusalém), e com ele o par de jumentos albardados, como também a sua concubina.

[[v7-19-11]]

^<<v7-19-11,11>>^ Estando pois  já perto de Jebus, e tendo-se já  declinado muito o dia, disse o moço a seu senhor: Caminhai agora, e retiremo-nos a esta cidade dos jebuseus e passemos ali a noite.

[[v7-19-12]]

^<<v7-19-12,12>>^ Porém disse-lhe seu senhor: Não nos retiraremos a nenhuma cidade estranha, que não seja  dos filhos de Israel: mas passaremos até Gibeá.

[[v7-19-13]]

^<<v7-19-13,13>>^ Disse mais a seu moço: Caminha, e cheguemos a um daqueles lugares, e passemos a noite em Gibeá ou em Ramá.

[[v7-19-14]]

^<<v7-19-14,14>>^ Passaram pois adiante , e caminharam, e o sol se lhes pôs junto a Gibeá, que é cidade  de Benjamim.

[[v7-19-15]]

^<<v7-19-15,15>>^ E retiraram-se para lá, para entrarem a passar a noite em Gibeá: e, entrando ele, assentou-se na praça da cidade, porque não houve  quem os recolhesse em casa para ali passarem a noite.

[[v7-19-16]]

^<<v7-19-16,16>>^ E eis que um homem velho vinha à tarde do seu trabalho do campo; e era  este homem da montanha de Efraim, mas peregrinava em Gibeá: eram  porém os homens deste lugar filhos de Benjamim.

[[v7-19-17]]

^<<v7-19-17,17>>^ Levantando-se ele pois os olhos, viu a este passageiro na praça da cidade, e disse o velho: Para onde vais, e donde vens?

[[v7-19-18]]

^<<v7-19-18,18>>^ E ele lhe disse: Passamos de Belém de Judá até aos lados da montanha de Efraim, donde sou; porquanto fui a Belém de Judá: porém agora  vou à casa do Senhor, e ninguém há  que me recolha em casa;

[[v7-19-19]]

^<<v7-19-19,19>>^ Ainda que há palha e pasto para os nossos jumentos, e também pão e vinho há para mim, e para a tua serva, e para o moço que vem  com os teus servos: de cousa nenhuma há  falta.

[[v7-19-20]]

^<<v7-19-20,20>>^ Então disse o velho: Paz seja  contigo; tudo quanto te faltar fique  ao meu cargo: tão somente não passes a noite na praça.

[[v7-19-21]]

^<<v7-19-21,21>>^ E trouxe-o a sua casa, e deu pasto aos jumentos: e, lavando-se os pés, comeram e beberam.

[[v7-19-22]]

^<<v7-19-22,22>>^ Estando eles alegrando o seu coração, eis que os homens daquela cidade (homens que eram  filhos de Belial) cercaram a casa, batendo à porta; e falaram ao velho, senhor da casa, dizendo: Tira para fora o homem que entrou em tua casa, para que o conheçamos.

[[v7-19-23]]

^<<v7-19-23,23>>^ E o homem, senhor da casa, saiu a eles, e disse-lhes: Não, irmãos meus, ora não façais semelhante mal: já que este homem entrou em minha casa, não façais tal loucura.

[[v7-19-24]]

^<<v7-19-24,24>>^ Eis que a minha filha virgem e a concubina dele tirarei para fora: humilhai-as a elas, e fazei delas o que parecer bem aos vossos olhos; porém a este homem não façais loucura semelhante.

[[v7-19-25]]

^<<v7-19-25,25>>^ Porém aqueles homens não o quiseram ouvir: então aquele homem pegou da sua concubina, e lha tirou para fora: e eles a conheceram e abusaram dela toda a noite até pela manhã, e, subindo a alva, a deixaram.

[[v7-19-26]]

^<<v7-19-26,26>>^ E ao romper da manhã veio a mulher, e caiu à porta da casa daquele homem, onde estava  seu senhor, e ficou ali até que se fez claro.

[[v7-19-27]]

^<<v7-19-27,27>>^ E, levantando-se seu senhor pela manhã, e abrindo as portas da casa, e saindo a seguir o seu caminho, eis que a mulher, sua concubina, jazia à porta da casa, com as mãos sobre o limiar.

[[v7-19-28]]

^<<v7-19-28,28>>^ E ele lhe disse: Levanta-te, e vamo-nos, porém não respondeu: então pô-la sobre o jumento e levantou-se o homem, e foi-se para o seu lugar.

[[v7-19-29]]

^<<v7-19-29,29>>^ Chegando pois à sua casa, tomou um  cutelo, e pegou na sua concubina, e a despedaçou com os seus ossos em doze partes: e enviou-os por todos os termos de Israel.

[[v7-19-30]]

^<<v7-19-30,30>>^ E sucedeu que cada um que tal  via dizia: nunca tal se fez, nem se viu desde o dia em que os filhos de Israel subiram da terra do Egito, até ao dia de  hoje: ponderai isto no coração , considerai, e falai.

'''

xref:007-juizes/007-juizes-018.adoc#v7-18-0[&#60; Capítulo Anterior] | <<v7-19-0,Topo>> | xref:007-juizes/007-juizes-020.adoc#v7-20-0[Próximo Capítulo &#62;]