include::./index.adoc[]

[[v7-10-0]]
=== Juízes, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-10-1]]

^<<v7-10-1,1>>^ E DEPOIS de Abimeleque, se levantou, para livrar a Israel, Tola, filho de Pua, filho de Dodo, homem de Issacar: e habitava em Samir, na montanha de Efraim.

[[v7-10-2]]

^<<v7-10-2,2>>^ E julgou a Israel vinte e três anos: e morreu, e foi sepultado em Samir.

[[v7-10-3]]

^<<v7-10-3,3>>^ E depois dele se levantou Jair, gileadita, e julgou a Israel vinte e dois anos.

[[v7-10-4]]

^<<v7-10-4,4>>^ E tinha este trinta filhos, que cavalgavam sobre trinta jumentos; e tinham trinta cidades, a que chamaram Havote-Jair, até ao dia de  hoje; as quais estão  na terra de Gileade.

[[v7-10-5]]

^<<v7-10-5,5>>^ E morreu Jair, e foi sepultado em Camom.

[[v7-10-6]]

^<<v7-10-6,6>>^ Então tornaram os filhos de Israel a fazer o que parecia  mal aos olhos do Senhor, e serviram aos baalins, e a Astarote, e aos deuses da Síria, e aos deuses de Sidom, e aos deuses de Moabe, e aos deuses dos filhos de Amom, e aos deuses dos filisteus: e deixaram ao Senhor, e não o serviram.

[[v7-10-7]]

^<<v7-10-7,7>>^ E a ira do Senhor se acendeu contra Israel: e vendeu-os em mão dos filisteus, e em mão dos filhos de Amom.

[[v7-10-8]]

^<<v7-10-8,8>>^ E naquele mesmo  ano oprimiram e vexaram aos filhos de Israel: dezoito anos oprimiram  a todos os filhos de Israel que estavam  dalém do Jordão, na terra dos amorreus, que está  em Gileade.

[[v7-10-9]]

^<<v7-10-9,9>>^ Até os filhos de Amom passaram o Jordão, para pelejar também contra Judá, e contra Benjamim, e contra a casa de Efraim: de maneira que Israel ficou mui angustiado.

[[v7-10-10]]

^<<v7-10-10,10>>^ Então os filhos de Israel clamaram ao Senhor, dizendo: Contra ti havemos pecado, porque deixamos a nosso Deus, e servimos aos baalins.

[[v7-10-11]]

^<<v7-10-11,11>>^ Porém o Senhor disse aos filhos de Israel: Porventura  dos egípcios, e dos amorreus, e dos filhos de Amom, e dos filisteus,

[[v7-10-12]]

^<<v7-10-12,12>>^ E dos sidônios, e dos amalequitas, e dos maonitas, que vos oprimiam, quando a mim clamastes, não vos livrei eu então  da sua mão?

[[v7-10-13]]

^<<v7-10-13,13>>^ Contudo  vós me deixastes a mim, e servistes a outros deuses: pelo que não vos livrarei mais.

[[v7-10-14]]

^<<v7-10-14,14>>^ Andai, e clamai aos deuses que escolhestes: que vos livrem eles no tempo do vosso aperto.

[[v7-10-15]]

^<<v7-10-15,15>>^ Mas os filhos de Israel disseram ao Senhor: Pecamos, faze-nos conforme a tudo quanto te  parecer bem aos teus olhos; tão somente te rogamos que nos livres neste dia.

[[v7-10-16]]

^<<v7-10-16,16>>^ E tiraram os deuses alheios do meio de si, e serviram ao Senhor: então se angustiou a sua alma por causa da desgraça de Israel.

[[v7-10-17]]

^<<v7-10-17,17>>^ E os filhos de Amom se convocaram e se puseram em campo em Gileade: e também  os de Israel se congregaram, e se puseram em campo em Mizpá.

[[v7-10-18]]

^<<v7-10-18,18>>^ Então o povo, os príncipes de Gileade disseram uns aos outros: Quem será o varão que começará a pelejar contra os filhos de Amom? ele será por cabeça de todos os moradores de Gileade.

'''

xref:007-juizes/007-juizes-009.adoc#v7-9-0[&#60; Capítulo Anterior] | <<v7-10-0,Topo>> | xref:007-juizes/007-juizes-011.adoc#v7-11-0[Próximo Capítulo &#62;]