include::./index.adoc[]

[[v7-8-0]]
=== Juízes, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-8-1]]

^<<v7-8-1,1>>^ ENTÃO os homens de Efraim lhes disseram: Que é  isto que nos fizeste, que não nos chamaste, quando foste pelejar contra os midianitas? E contenderam com ele fortemente.

[[v7-8-2]]

^<<v7-8-2,2>>^ Porém ele lhes disse: Que mais  fiz eu agora do que vós? não são porventura  os rabiscos de Efraim melhores do que a vindima de Abiezer?

[[v7-8-3]]

^<<v7-8-3,3>>^ Deus vos deu na vossa mão aos príncipes dos midianitas, Orebe e Zeebe; que mais  pude eu logo fazer do que vós? então a sua ira se abrandou para com ele, quando falou esta palavra.

[[v7-8-4]]

^<<v7-8-4,4>>^ E, como Gideão veio ao Jordão, passou com os trezentos homens que com ele estavam , já cansados, mas ainda perseguindo.

[[v7-8-5]]

^<<v7-8-5,5>>^ E disse aos homens de Sucote: Dai, peço-vos, alguns pedaços de pão ao povo, que segue as minhas pisadas: porque estão cansados, e eu vou em alcance de Zeba e Salmuna, reis dos midianitas.

[[v7-8-6]]

^<<v7-8-6,6>>^ Porém os príncipes de Sucote disseram: Está  já a palma da mão de Zeba e de Salmuna na tua mão, para que demos pão ao teu exército?

[[v7-8-7]]

^<<v7-8-7,7>>^ Então disse Gideão: Pois quando o Senhor der na minha mão a Zeba e a Salmuna, trilharei a vossa carne com os espinhos do deserto, e com os abrolhos.

[[v7-8-8]]

^<<v7-8-8,8>>^ E dali subiu a Penuel, e falou-lhes da mesma maneira; e os homens de Penuel lhe responderam como os homens de Sucote lhe  haviam respondido.

[[v7-8-9]]

^<<v7-8-9,9>>^ Pelo que também falou aos homens de Penuel, dizendo: Quando eu voltar em paz, derribarei esta torre.

[[v7-8-10]]

^<<v7-8-10,10>>^ Estavam  pois Zeba e Salmuna em Carcor, e os seus exércitos com eles, uns quinze mil homens , todos os que ficaram do exército dos filhos do oriente: e os que caíram foram  cento e vinte mil homens, que arrancavam a espada.

[[v7-8-11]]

^<<v7-8-11,11>>^ E subiu Gideão pelo caminho dos que habitavam em tendas, para o oriente de Noba e Jogbeá: e feriu aquele exército, porquanto o exército estava descuidado.

[[v7-8-12]]

^<<v7-8-12,12>>^ E fugiram Zeba e Salmuna: porém ele os perseguiu, e tomou presos a ambos os reis dos midianitas, a Zeba e a Salmuna, e afugentou a todo o exército.

[[v7-8-13]]

^<<v7-8-13,13>>^ Voltando pois Gideão, filho de Joás, da peleja, antes do nascer  do sol,

[[v7-8-14]]

^<<v7-8-14,14>>^ Tomou preso a um moço dos homens de Sucote, e lhe fez perguntas: o qual descreveu os príncipes de Sucote, e os seus anciãos, setenta e sete homens.

[[v7-8-15]]

^<<v7-8-15,15>>^ Então veio aos homens de Sucote, e disse: Vedes aqui a Zeba e a Salmuna, dos quais desprezivelmente me deitastes em rosto, dizendo: Está  já a palma da mão de Zeba e Salmuna na tua mão, para que demos pão aos teus homens, já  cansados?

[[v7-8-16]]

^<<v7-8-16,16>>^ E tomou os anciãos daquela cidade, e espinhos do deserto, e abrolhos: e com eles ensinou aos homens de Sucote.

[[v7-8-17]]

^<<v7-8-17,17>>^ E derribou a torre de Penuel, e matou os homens da cidade.

[[v7-8-18]]

^<<v7-8-18,18>>^ Depois disse a Zeba e a Salmuna: Que homens eram os  que matastes em Tabor? E disseram: Qual tu, tais eram  eles; cada um ao parecer, como filhos dum rei.

[[v7-8-19]]

^<<v7-8-19,19>>^ Então disse ele: Meus irmãos eram  filhos de minha mãe: vive o Senhor, que, se os tivésseis deixado em vida, eu não vos  mataria a vós.

[[v7-8-20]]

^<<v7-8-20,20>>^ E disse a Jéter, seu primogênito: Levanta-te, mata-os. Porém o mancebo não arrancou da sua espada, porque temia; porquanto ainda era  mancebo.

[[v7-8-21]]

^<<v7-8-21,21>>^ Então disseram Zeba e Salmuna: Levanta-te tu, e acomete-nos; porque, qual o homem, tal  a sua valentia. Levantou-se pois Gideão, e matou a Zeba e a Salmuna, e tomou as luetas, que estavam aos pescoços dos seus camelos.

[[v7-8-22]]

^<<v7-8-22,22>>^ Então os homens de Israel disseram a Gideão: Domina sobre nós, tanto tu, como teu filho e o filho de teu filho; porquanto nos livraste da mão dos midianitas.

[[v7-8-23]]

^<<v7-8-23,23>>^ Porém Gideão lhes disse: Sobre vós eu não dominarei, nem tão pouco meu filho sobre vós dominará: o Senhor sobre vós dominará.

[[v7-8-24]]

^<<v7-8-24,24>>^ E disse-lhes mais  Gideão: Uma petição vos farei: dai-me cada um de vós os pendentes do seu despojo (porque tinham pendentes de ouro, porquanto eram ismaelitas).

[[v7-8-25]]

^<<v7-8-25,25>>^ E disseram eles: De boa mente os  daremos. E estenderam uma capa, e cada um deles deitou ali um pendente do seu despojo.

[[v7-8-26]]

^<<v7-8-26,26>>^ E foi o peso dos pendentes de ouro que pediu, mil e setecentos siclos  de ouro, afora as luetas, e as cadeias, e os vestidos de púrpura, que traziam os reis dos midianitas, e afora as coleiras que os camelos traziam ao pescoço.

[[v7-8-27]]

^<<v7-8-27,27>>^ E fez Gideão disso um éfode e pô-lo na sua cidade, em Ofra; e todo o Israel se prostituiu ali após dele: e foi por tropeço a Gideão e à sua casa.

[[v7-8-28]]

^<<v7-8-28,28>>^ Assim foram abatidos os midianitas diante dos filhos de Israel, e nunca mais levantaram a sua cabeça: e sossegou a terra quarenta anos nos dias de Gideão.

[[v7-8-29]]

^<<v7-8-29,29>>^ E foi-se Jerubaal, filho de Joás, e habitou em sua casa.

[[v7-8-30]]

^<<v7-8-30,30>>^ E teve Gideão setenta filhos, que procederam da sua coxa: porque tinha muitas mulheres.

[[v7-8-31]]

^<<v7-8-31,31>>^ E sua concubina, que estava  em Siquém, lhe deu também um  filho: e pôs-lhe por nome Abimeleque.

[[v7-8-32]]

^<<v7-8-32,32>>^ E faleceu Gideão, filho de Joás, numa boa velhice: e foi sepultado no sepulcro de seu pai Joás, em Ofra dos abiezritas.

[[v7-8-33]]

^<<v7-8-33,33>>^ E sucedeu que, quando Gideão faleceu, os filhos de Israel se tornaram, e se prostituíram após dos baalins: e puseram a Baal-Berite por deus.

[[v7-8-34]]

^<<v7-8-34,34>>^ E os filhos de Israel se não lembraram do Senhor seu Deus, que os livrara da mão de todos os seus inimigos em redor.

[[v7-8-35]]

^<<v7-8-35,35>>^ Nem usaram de beneficência com a casa de Jerubaal, a saber , de Gideão, conforme a todo o bem que ele usara com Israel.

'''

xref:007-juizes/007-juizes-007.adoc#v7-7-0[&#60; Capítulo Anterior] | <<v7-8-0,Topo>> | xref:007-juizes/007-juizes-009.adoc#v7-9-0[Próximo Capítulo &#62;]