include::./index.adoc[]

[[v7-21-0]]
=== Juízes, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v7-21-1]]

^<<v7-21-1,1>>^ ORA tinham jurado os homens de Israel em Mizpá, dizendo: Nenhum de nós dará sua filha por mulher aos benjamitas.

[[v7-21-2]]

^<<v7-21-2,2>>^ Veio pois o povo a Betel, e ali ficaram até à tarde diante de Deus: e levantaram a sua voz, e prantearam com grande pranto.

[[v7-21-3]]

^<<v7-21-3,3>>^ E disseram: Ah! Senhor Deus de Israel, por que sucedeu isto em Israel, que hoje falte uma tribo em Israel?

[[v7-21-4]]

^<<v7-21-4,4>>^ E sucedeu que, no dia seguinte, o povo pela manhã se levantou, e edificou ali um  altar; e ofereceram holocaustos e ofertas pacíficas.

[[v7-21-5]]

^<<v7-21-5,5>>^ E disseram os filhos de Israel: Quem de todas as tribos de Israel não subiu ao ajuntamento ao Senhor? Porque se tinha feito um  grande juramento acerca dos que não viessem ao Senhor a Mizpá, dizendo: Morrerá certamente.

[[v7-21-6]]

^<<v7-21-6,6>>^ E arrependeram-se os filhos de Israel acerca de Benjamim, seu irmão, e disseram: Cortada é hoje de Israel uma tribo.

[[v7-21-7]]

^<<v7-21-7,7>>^ Que faremos, acerca de mulheres, com os que ficaram de resto, pois nós temos jurado pelo Senhor que nenhuma de nossas filhas lhes daríamos por mulheres?

[[v7-21-8]]

^<<v7-21-8,8>>^ E disseram: Há alguma das tribos de Israel que não subisse ao Senhor a Mizpá? E eis que ninguém de Jabes de Gileade viera ao arraial, à congregação.

[[v7-21-9]]

^<<v7-21-9,9>>^ Porquanto o povo se contou: e eis que nenhum dos moradores de Jabes de Gileade se achou ali.

[[v7-21-10]]

^<<v7-21-10,10>>^ Então o ajuntamento enviou lá doze mil homens dos mais valentes, e lhes ordenou, dizendo: Ide, e ao fio da espada feri aos moradores de Jabes de Gileade, e às mulheres e aos meninos.

[[v7-21-11]]

^<<v7-21-11,11>>^ Porém isto é  o que haveis de fazer: A todo o varão e a toda a mulher que se houver deitado com um homem totalmente destruireis.

[[v7-21-12]]

^<<v7-21-12,12>>^ E acharam entre os moradores de Jabes de Gileade quatrocentas moças virgens, que não conheceram homem deitando-se com varão: e as trouxeram ao arraial, a Silo, que está  na terra de Canaã.

[[v7-21-13]]

^<<v7-21-13,13>>^ Então todo o ajuntamento enviou, e falou aos filhos de Benjamim, que estavam  na penha de Rimom, e lhes proclamou a paz.

[[v7-21-14]]

^<<v7-21-14,14>>^ E ao mesmo tempo voltaram os benjamitas; e deram-lhes as mulheres que haviam guardado com vida, das mulheres de Jabes de Gileade: porém estas ainda lhes não bastaram.

[[v7-21-15]]

^<<v7-21-15,15>>^ Então o povo se arrependeu por causa de Benjamim: porquanto o Senhor tinha feito abertura nas tribos de Israel.

[[v7-21-16]]

^<<v7-21-16,16>>^ E disseram os anciãos do ajuntamento: Que faremos acerca de mulheres para os que ficaram de resto, pois, estão destruídas as mulheres de Benjamim?

[[v7-21-17]]

^<<v7-21-17,17>>^ Disseram mais: A herança dos que ficaram de resto é de Benjamim, e nenhuma tribo de Israel deve ser destruída.

[[v7-21-18]]

^<<v7-21-18,18>>^ Porém nós não lhes poderemos dar mulheres de nossas filhas, porque os filhos de Israel juraram, dizendo: Maldito aquele  que der mulher aos benjamitas.

[[v7-21-19]]

^<<v7-21-19,19>>^ Então disseram: Eis que de ano em ano há  solenidade do Senhor em Silo, que se celebra  para o norte de Betel, da banda do nascente do sol, pelo caminho alto que sobe de Betel a Siquém, e para o sul de Lebona.

[[v7-21-20]]

^<<v7-21-20,20>>^ E mandaram aos filhos de Benjamim dizendo: Ide, e emboscai-vos nas vinhas.

[[v7-21-21]]

^<<v7-21-21,21>>^ E olhai, e eis aí, saindo as filhas de Silo a dançar em ranchos, saí vós das vinhas, e arrebatai cada um sua mulher das filhas de Silo, e ide-vos à terra de Benjamim.

[[v7-21-22]]

^<<v7-21-22,22>>^ E será que, quando seus pais ou seus irmãos vierem a litigar conosco, nós lhes diremos: Por amor de nós, tende compaixão deles, pois nesta guerra não tomamos mulheres para cada um deles: porque não lhas destes vós, para  que agora ficásseis culpados.

[[v7-21-23]]

^<<v7-21-23,23>>^ E os filhos de Benjamim o fizeram assim, e levaram mulheres conforme ao número deles, das que arrebataram dos ranchos que dançavam: e foram-se, e voltaram à sua herança, e reedificaram as cidades, e habitaram nelas.

[[v7-21-24]]

^<<v7-21-24,24>>^ Também os filhos de Israel partiram então dali, cada um para a sua tribo e para a sua geração: e saíram dali, cada um para a sua herança.

[[v7-21-25]]

^<<v7-21-25,25>>^ Naqueles dias não havia  rei em Israel: porém cada um fazia o que parecia  reto aos seus olhos.

'''

xref:007-juizes/007-juizes-020.adoc#v7-20-0[&#60; Capítulo Anterior] | <<v7-21-0,Topo>> | xref:008-rute/008-rute-001.adoc#v8-1-0[Próximo Capítulo &#62;]