include::./index.adoc[]

[[v29-1-0]]
=== Joel, 1
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v29-1-1]]

^<<v29-1-1,1>>^ PALAVRA do Senhor, que foi dirigida a Joel, filho de Petuel.

[[v29-1-2]]

^<<v29-1-2,2>>^ Ouvi isto, vós, anciãos, e escutai, todos os moradores da terra: Aconteceu isto em vossos dias? ou também nos dias de vossos pais?

[[v29-1-3]]

^<<v29-1-3,3>>^ Fazei sobre isto uma narração a vossos filhos, e vossos filhos a seus filhos, e os filhos destes à outra geração.

[[v29-1-4]]

^<<v29-1-4,4>>^ O que ficou da lagarta, o  comeu o gafanhoto, e o que ficou do gafanhoto o  comeu a locusta, e o que ficou da locusta o  comeu o pulgão.

[[v29-1-5]]

^<<v29-1-5,5>>^ Despertai ébrios, e chorai; gemei, todos os que bebeis vinho, por causa do mosto, porque tirado é da vossa boca.

[[v29-1-6]]

^<<v29-1-6,6>>^ Porque uma nação subiu sobre a minha terra, poderosa e sem número: os seus dentes são  dentes de leão, e têm queixadas de um leão velho.

[[v29-1-7]]

^<<v29-1-7,7>>^ Fez da minha vide uma assolação, e tirou a casca da minha figueira: despiu-a toda, e a lançou por terra; os seus sarmentos se embranqueceram.

[[v29-1-8]]

^<<v29-1-8,8>>^ Lamenta como a virgem que está cingida de saco, pelo marido da sua mocidade.

[[v29-1-9]]

^<<v29-1-9,9>>^ Foi cortada a oferta de manjar, e a libação da casa do Senhor: os sacerdotes, servos do Senhor, estão  entristecidos.

[[v29-1-10]]

^<<v29-1-10,10>>^ O campo está assolado, e  a terra triste; porque o trigo está destruído, o mosto se secou, o óleo falta.

[[v29-1-11]]

^<<v29-1-11,11>>^ Os lavradores se envergonham, os vinhateiros gemem, sobre o trigo e sobre a cevada; porque a colheita do campo pereceu.

[[v29-1-12]]

^<<v29-1-12,12>>^ A vide se secou, a figueira se murchou; a romeira também, e a palmeira e a macieira; todas as árvores do campo se secaram, e a alegria se secou entre os filhos dos homens.

[[v29-1-13]]

^<<v29-1-13,13>>^ Cingi-vos e lamentai-vos, sacerdotes; gemei, ministros do altar; entrai e passai, vestidos de sacos, durante a noite, ministros do meu Deus; porque a oferta de manjares, e a libação, cortadas foram da casa de vosso Deus.

[[v29-1-14]]

^<<v29-1-14,14>>^ Santificai um jejum, apregoai um dia de proibição, congregai os anciãos, e  todos os moradores desta terra, na casa do Senhor vosso Deus, e clamai ao Senhor.

[[v29-1-15]]

^<<v29-1-15,15>>^ Ah! aquele dia! porque o dia do Senhor está perto, e virá como uma assolação do Todo-poderoso.

[[v29-1-16]]

^<<v29-1-16,16>>^ Porventura  o mantimento não está cortado de diante de nossos olhos? a alegria e o regozijo da casa de nosso Deus?

[[v29-1-17]]

^<<v29-1-17,17>>^ A semente apodreceu debaixo dos seus torrões, os celeiros foram assolados, os armazéns derribados, porque se secou o trigo.

[[v29-1-18]]

^<<v29-1-18,18>>^ Como geme o gado! as manadas de vacas estão confusas, porque não têm pasto: também os rebanhos de ovelhas são destruídos.

[[v29-1-19]]

^<<v29-1-19,19>>^ A ti, ó Senhor clamo, porque o fogo consumiu os pastos do deserto, e a chama abrasou todas as árvores do campo.

[[v29-1-20]]

^<<v29-1-20,20>>^ Também todos os animais do campo bramam a ti; porque os rios se secaram, e o fogo consumiu os pastos do deserto.

'''

xref:028-oseias/028-oseias-014.adoc#v28-14-0[&#60; Capítulo Anterior] | <<v29-1-0,Topo>> | xref:029-joel/029-joel-002.adoc#v29-2-0[Próximo Capítulo &#62;]