include::./index.adoc[]

[[v29-2-0]]
=== Joel, 2
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v29-2-1]]

^<<v29-2-1,1>>^ TOCAI a buzina em Sião, e clamai em alta voz no monte da minha santidade: perturbem-se todos os moradores da terra, porque o dia do Senhor vem, ele está perto:

[[v29-2-2]]

^<<v29-2-2,2>>^ Dia de trevas e de tristeza; dia de nuvens e de trevas espessas, como a alva espalhada sobre os montes, povo grande e poderoso, qual desde o tempo antigo nunca houve, nem depois dele haverá pelos anos adiante, de geração em geração.

[[v29-2-3]]

^<<v29-2-3,3>>^ Diante dele um fogo consome; e atrás dele uma chama abrasa: a terra diante dele é  como o jardim do Éden, mas atrás dele um desolado deserto; sim, nada lhe escapará.

[[v29-2-4]]

^<<v29-2-4,4>>^ O seu parecer é  como o parecer de cavalos: e correrão como cavaleiros.

[[v29-2-5]]

^<<v29-2-5,5>>^ Como o estrondo de carros sobre os cumes dos montes irão eles saltando; como o ruído da chama de fogo que consome a pragana, como um povo poderoso, ordenado para o combate.

[[v29-2-6]]

^<<v29-2-6,6>>^ Diante dele temerão os povos; todos os rostos são  como a tisnadura da panela.

[[v29-2-7]]

^<<v29-2-7,7>>^ Como valentes correrão, como homens de guerra subirão os muros; e irá cada um nos seus caminhos e não se desviarão da sua fileira.

[[v29-2-8]]

^<<v29-2-8,8>>^ Ninguém apertará a seu irmão; irá cada um pelo seu carreiro; sobre a mesma espada se arremessarão, e não serão feridos.

[[v29-2-9]]

^<<v29-2-9,9>>^ Irão pela cidade, correrão pelos muros, subirão às casas, pelas janelas entrarão como o ladrão.

[[v29-2-10]]

^<<v29-2-10,10>>^ Diante dele tremerá a terra, abalar-se-ão os céus; o sol e a lua se enegrecerão, e as estrelas retirarão o seu resplendor.

[[v29-2-11]]

^<<v29-2-11,11>>^ E o Senhor levanta a sua voz diante do seu exército; porque muitíssimos são  os seus arraiais; porque poderoso é , executando a sua palavra; porque o dia do Senhor é  grande e mui terrível, e quem o poderá sofrer?

[[v29-2-12]]

^<<v29-2-12,12>>^ Ainda assim, agora mesmo diz o Senhor: Convertei-vos a mim de todo o vosso coração; e isso com jejuns, e com choro, e com pranto.

[[v29-2-13]]

^<<v29-2-13,13>>^ E rasgai o vosso coração, e não os vossos vestidos, e convertei-vos ao Senhor vosso Deus; porque ele é misericordioso, e compassivo, e tardio em irar-se, e grande em beneficência, e se arrepende do mal.

[[v29-2-14]]

^<<v29-2-14,14>>^ Quem sabe se  se voltará e se arrependerá, e deixará após si uma bênção, em  oferta de manjar e libação para o Senhor vosso Deus?

[[v29-2-15]]

^<<v29-2-15,15>>^ Tocai a buzina em Sião, santificai um jejum, proclamai um dia de proibição.

[[v29-2-16]]

^<<v29-2-16,16>>^ Congregai o povo, santificai a congregação, ajuntai os anciãos, congregai os filhinhos, e os que mamam: saia o noivo da sua recâmara, e a noiva do seu tálamo.

[[v29-2-17]]

^<<v29-2-17,17>>^ Chorem os sacerdotes, ministros do Senhor, entre o alpendre e o altar, e digam: Poupa a teu povo, ó Senhor, e não entregues a tua herança ao opróbrio, para que as nações façam escárnio dele; porque diriam entre os povos: Onde está o seu Deus?

[[v29-2-18]]

^<<v29-2-18,18>>^ Então o Senhor terá zelo da sua terra, e se compadecerá do seu povo.

[[v29-2-19]]

^<<v29-2-19,19>>^ E o Senhor responderá, e dirá ao seu povo: Eis que vos envio o trigo, e o mosto, e o óleo, e deles sereis fartos, e vos não entregarei mais ao opróbrio entre as nações.

[[v29-2-20]]

^<<v29-2-20,20>>^ E aquele que é  do norte farei partir para longe de vós, e lançá-lo-ei em uma terra seca e deserta: a sua frente para o mar oriental, e a sua retaguarda para o mar ocidental; e subirá o seu mau cheiro, e subirá a sua podridão; porque fez grandes cousas.

[[v29-2-21]]

^<<v29-2-21,21>>^ Não temas, ó terra: regozija-te e alegra-te; porque o Senhor fez grandes cousas.

[[v29-2-22]]

^<<v29-2-22,22>>^ Não temais, animais do campo, porque os pastos do deserto reverdecerão, porque o arvoredo dará o seu fruto, a vide e a figueira darão a sua força.

[[v29-2-23]]

^<<v29-2-23,23>>^ E vós, filhos de Sião, regozijai-vos e alegrai-vos no Senhor vosso Deus, porque ele vos dará ensinador de justiça, e fará descer a chuva, a temporã e a serôdia, no primeiro mês.

[[v29-2-24]]

^<<v29-2-24,24>>^ E as eiras se encherão de trigo, e os lagares trasbordarão de mosto e de óleo.

[[v29-2-25]]

^<<v29-2-25,25>>^ E restituir-vos-ei os anos que foram consumidos pelo gafanhoto, a locusta, e o pulgão e a aruga, o meu grande exército que enviei contra vós.

[[v29-2-26]]

^<<v29-2-26,26>>^ E comereis abundantemente e ficareis satisfeitos, e louvareis o nome do Senhor vosso Deus, que procedeu para convosco maravilhosamente; e o meu povo não será mais envergonhado.

[[v29-2-27]]

^<<v29-2-27,27>>^ E vós sabereis que eu estou no meio de Israel, e que eu sou o Senhor vosso Deus, e ninguém mais: e o meu povo não será envergonhado para sempre.

[[v29-2-28]]

^<<v29-2-28,28>>^ E há de ser que  depois, derramarei o meu Espírito sobre toda a carne, e vossos filhos e vossas filhas profetizarão, os vossos velhos terão sonhos, os vossos mancebos terão visões.

[[v29-2-29]]

^<<v29-2-29,29>>^ E também sobre os servos e sobre as servas naqueles dias derramarei o meu Espírito.

[[v29-2-30]]

^<<v29-2-30,30>>^ E mostrarei prodígios no céu, e na terra, sangue e fogo, e colunas de fumo.

[[v29-2-31]]

^<<v29-2-31,31>>^ O sol se converterá em trevas, e a lua em sangue, antes que venha o grande e terrível dia do Senhor.

[[v29-2-32]]

^<<v29-2-32,32>>^ E há de ser que  todo aquele que invocar o nome do Senhor será salvo; porque no monte de Sião e em Jerusalém haverá livramento, assim como o Senhor tem dito, e nos restantes, que o Senhor chamar.

'''

xref:029-joel/029-joel-001.adoc#v29-1-0[&#60; Capítulo Anterior] | <<v29-2-0,Topo>> | xref:029-joel/029-joel-003.adoc#v29-3-0[Próximo Capítulo &#62;]