include::./index.adoc[]

[[v23-41-0]]
=== Isaías, 41
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-41-1]]

^<<v23-41-1,1>>^ CALAI-VOS perante mim, ó ilhas, e os povos renovem as forças: cheguem-se, e então  falem: cheguemo-nos juntos a juízo.

[[v23-41-2]]

^<<v23-41-2,2>>^ Quem suscitou do oriente o justo? e o  chamou para o pé de si? quem  deu as nações à sua face e o fez dominar sobre reis? ele os entregou à sua espada como o pó, e  como pragana arrebatada do vento  ao seu arco.

[[v23-41-3]]

^<<v23-41-3,3>>^ Ele persegue-os, e  passa em  paz, por uma  vereda em que com os seus pés nunca tinha caminhado.

[[v23-41-4]]

^<<v23-41-4,4>>^ Quem operou e fez isto , chamando as gerações desde o princípio? eu o Senhor, o primeiro, e com os últimos eu mesmo.

[[v23-41-5]]

^<<v23-41-5,5>>^ As ilhas o viram, e temeram: os fins da terra tremeram: aproximaram-se, e vieram.

[[v23-41-6]]

^<<v23-41-6,6>>^ Um ao outro ajudou, e ao seu companheiro disse: Esforça-te.

[[v23-41-7]]

^<<v23-41-7,7>>^ E o artífice animou o ourives, e  o que alisa com o martelo ao que bate na safra, dizendo da cousa soldada: Boa é. Então com pregos o firma, para que não venha a mover-se.

[[v23-41-8]]

^<<v23-41-8,8>>^ Mas tu, ó Israel, servo meu, tu Jacó, a quem elegi, semente de Abraão meu amigo?

[[v23-41-9]]

^<<v23-41-9,9>>^ Tu a quem tomei desde os fins da terra e te chamei dentre os seus mais excelentes, e te disse: Tu és  o meu servo, a ti te escolhi e não te rejeitei.

[[v23-41-10]]

^<<v23-41-10,10>>^ Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus: eu te esforço, e te ajudo, e te sustento com a destra da minha justiça.

[[v23-41-11]]

^<<v23-41-11,11>>^ Eis que envergonhados e confundidos serão todos os que se irritaram contra ti; tornar-se-ão nada, e os que contenderem contigo perecerão.

[[v23-41-12]]

^<<v23-41-12,12>>^ Buscá-los-ás, mas não os acharás; e os que pelejarem contigo tornar-se-ão nada, e como cousa que não é nada os que guerrearem contigo.

[[v23-41-13]]

^<<v23-41-13,13>>^ Porque eu, o Senhor teu Deus, te tomo pela tua mão direita, e te digo: Não temas, que eu te ajudo.

[[v23-41-14]]

^<<v23-41-14,14>>^ Não temas, ó bichinho de Jacó, povozinho de Israel; eu te ajudo, diz o Senhor, e o teu redentor é o Santo de Israel.

[[v23-41-15]]

^<<v23-41-15,15>>^ Eis que te preparei trilho novo, que tem dentes agudos; os montes trilharás e moerás; e os outeiros tornarás como a folhelho.

[[v23-41-16]]

^<<v23-41-16,16>>^ Tu os padejarás e o vento os levará, e o tufão os espalhará; mas tu te alegrarás no Senhor e te gloriarás no Santo de Israel.

[[v23-41-17]]

^<<v23-41-17,17>>^ Os aflitos e necessitados buscam águas, e não as há, e a sua língua se seca de sede: mas eu o Senhor os ouvirei, eu o Deus de Israel os não desampararei.

[[v23-41-18]]

^<<v23-41-18,18>>^ Abrirei rios em lugares altos, e fontes no meio dos vales: tornarei o deserto em tanques de águas, e a terra seca em mananciais.

[[v23-41-19]]

^<<v23-41-19,19>>^ Plantarei no deserto o cedro, a árvore de sita, e a murta, e a oliveira: conjuntamente porei no ermo a faia o olmeiro e o álamo:

[[v23-41-20]]

^<<v23-41-20,20>>^ Para que todos  vejam, e saibam, e considerem, e juntamente entendam que a mão do Senhor fez isto, e o Santo de Israel o criou.

[[v23-41-21]]

^<<v23-41-21,21>>^ Apresentai a vossa demanda, diz o Senhor: trazei as vossas firmes razões, diz o Rei de Jacó.

[[v23-41-22]]

^<<v23-41-22,22>>^ Tragam e anunciem-nos as cousas que hão de acontecer: anunciai- nos  as cousas passadas, para que atentemos para elas, e saibamos o fim delas; ou fazei-nos ouvir as cousas futuras.

[[v23-41-23]]

^<<v23-41-23,23>>^ Anunciai- nos  as cousas que ainda hão de vir, para que saibamos que sois  deuses: fazei bem, ou fazei mal, para que nos assombremos, e juntamente o  vejamos.

[[v23-41-24]]

^<<v23-41-24,24>>^ Eis que sois  menos do que nada e a vossa obra é menos do que nada: abominação é quem  vos escolhe.

[[v23-41-25]]

^<<v23-41-25,25>>^ Suscito a um  do norte, e ele há de vir; desde o nascimento do sol invocará o meu nome; e virá sobre os magistrados, como sobre  o lodo, e, como o oleiro pisa o barro, assim ele os pisará.

[[v23-41-26]]

^<<v23-41-26,26>>^ Quem anunciou isto desde o princípio, para que o possamos saber, ou outro tempo, para que digamos: Justo é ? Mas não há quem anuncie, nem tão pouco quem manifeste, nem tão pouco quem ouça as vossas palavras.

[[v23-41-27]]

^<<v23-41-27,27>>^ Eu sou  o que primeiro direi  a Sião: Eis que ali estão: e a Jerusalém darei um anunciador de boas novas.

[[v23-41-28]]

^<<v23-41-28,28>>^ E quando olhei, ninguém havia ; nem mesmo entre estes conselheiros algum havia  a quem perguntasse ou que me respondesse palavra.

[[v23-41-29]]

^<<v23-41-29,29>>^ Eis que todos são vaidade; as suas obras não são  cousa alguma; as suas imagens de fundição são  vento e nada.

'''

xref:023-isaias/023-isaias-040.adoc#v23-40-0[&#60; Capítulo Anterior] | <<v23-41-0,Topo>> | xref:023-isaias/023-isaias-042.adoc#v23-42-0[Próximo Capítulo &#62;]