include::./index.adoc[]

[[v23-57-0]]
=== Isaías, 57
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-57-1]]

^<<v23-57-1,1>>^ PERECE o justo, e não há  quem considere isso em  seu coração, e os homens compassivos são retirados, sem que alguém considere que o justo é levado antes do mal.

[[v23-57-2]]

^<<v23-57-2,2>>^ Entrará em  paz: descansarão nas suas camas os que houveram andado na sua retidão.

[[v23-57-3]]

^<<v23-57-3,3>>^ Mas chegai-vos aqui, vós os filhos da agoureira, semente adulterina e de prostituição.

[[v23-57-4]]

^<<v23-57-4,4>>^ De quem fazeis o vosso passatempo? contra quem escancarais a boca, e deitais para fora a língua? porventura  não sois  filhos da transgressão, semente da falsidade,

[[v23-57-5]]

^<<v23-57-5,5>>^ Que vos esquentais com os ídolos debaixo de toda a árvore verde, e sacrificais os filhos nos ribeiros, nas aberturas dos penhascos?

[[v23-57-6]]

^<<v23-57-6,6>>^ Nas pedras  lisas dos ribeiros está  a tua parte; estas, estas são a tua sorte; sobre elas também derramas a tua  libação, e  lhes ofereces ofertas: contentar-me-ia eu destas cousas?

[[v23-57-7]]

^<<v23-57-7,7>>^ Sobre os montes altos e levantados pões a tua cama; e a eles sobes para oferecer sacrifícios.

[[v23-57-8]]

^<<v23-57-8,8>>^ E detrás das portas e das umbreiras pões os teus memoriais; porque a outros mais do que a mim te  descobres, e sobes, alargas a tua cama, e fazes concerto com eles: amas a sua cama, onde quer que a  vês.

[[v23-57-9]]

^<<v23-57-9,9>>^ E vais ao rei com óleo e multiplicas os teus perfumes; e envias os teus embaixadores para longe, e te abates até aos infernos.

[[v23-57-10]]

^<<v23-57-10,10>>^ Na tua comprida viagem te cansaste; mas não dizes: Não há esperança; o que buscavas achaste, por isso não adoeces.

[[v23-57-11]]

^<<v23-57-11,11>>^ Mas de quem tiveste receio ou temor, para que mentisses, e não te lembrasses de mim, nem no teu coração me  pusesses? não é porventura  porque eu me calo, e isso já  desde muito tempo, e me não temes?

[[v23-57-12]]

^<<v23-57-12,12>>^ Eu publicarei a tua justiça, e as tuas obras, que não te aproveitarão.

[[v23-57-13]]

^<<v23-57-13,13>>^ Quando clamares, livrem-te os teus congregados; mas o vento a todos levará, e a vaidade os arrebatará: mas o que confia em mim possuirá a terra, e herdará o meu santo monte.

[[v23-57-14]]

^<<v23-57-14,14>>^ E dir-se-á: Aplainai, aplainai, preparai o caminho: tirai os tropeços do caminho do meu povo.

[[v23-57-15]]

^<<v23-57-15,15>>^ Porque assim diz o alto e o sublime, que habita na eternidade, e cujo nome é santo: Num alto e santo lugar habito, e também com o contrito e abatido de espírito, para vivificar o espírito dos abatidos, e para vivificar o coração dos contritos.

[[v23-57-16]]

^<<v23-57-16,16>>^ Porque para sempre não contenderei, nem continuamente me indignarei; porque o espírito perante a minha face se enfraqueceria, e as almas que  eu fiz.

[[v23-57-17]]

^<<v23-57-17,17>>^ Pela iniquidade da sua avareza me indignei, e os feri: escondi-me, e indignei-me; mas, rebeldes, seguiram o caminho do seu coração.

[[v23-57-18]]

^<<v23-57-18,18>>^ Eu vejo os seus caminhos, e os sararei; também os guiarei, e lhes tornarei a dar consolações e aos seus pranteadores.

[[v23-57-19]]

^<<v23-57-19,19>>^ Eu crio os frutos dos lábios: paz, paz, para os que estão  longe, e para os que estão  perto, diz o Senhor, e eu os sararei.

[[v23-57-20]]

^<<v23-57-20,20>>^ Mas os ímpios são como o mar bravo que se não pode aquietar, e cujas águas lançam de si lama e lodo.

[[v23-57-21]]

^<<v23-57-21,21>>^ Os ímpios, diz o meu Deus, não têm  paz.

'''

xref:023-isaias/023-isaias-056.adoc#v23-56-0[&#60; Capítulo Anterior] | <<v23-57-0,Topo>> | xref:023-isaias/023-isaias-058.adoc#v23-58-0[Próximo Capítulo &#62;]