include::./index.adoc[]

[[v23-25-0]]
=== Isaías, 25
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-25-1]]

^<<v23-25-1,1>>^ Ó SENHOR, tu és o meu Deus; exaltar-te-ei, a ti, e  louvarei o teu nome, porque fizeste maravilhas: os teus  conselhos antigos são  verdade e  firmeza.

[[v23-25-2]]

^<<v23-25-2,2>>^ Porque da cidade fizeste um montão de pedras, e  da cidade forte uma ruína e  do paço dos estranhos, que não seja mais cidade, e jamais se torne a edificar.

[[v23-25-3]]

^<<v23-25-3,3>>^ Pelo que te glorificará um povo poderoso, e  a cidade das nações formidáveis te temerá.

[[v23-25-4]]

^<<v23-25-4,4>>^ Porque foste a fortaleza do pobre, e  a fortaleza do necessitado na sua angústia: refúgio contra a tempestade, e sombra contra o calor; porque o sopro dos opressores é  como a tempestade contra  o muro.

[[v23-25-5]]

^<<v23-25-5,5>>^ Como o calor em lugar seco, tu abaterás o ímpeto dos estranhos; como se  abranda o calor pela sombra da espessa nuvem, assim  o cântico dos tiranos será humilhado.

[[v23-25-6]]

^<<v23-25-6,6>>^ E o Senhor dos Exércitos dará neste monte a todos os povos uma festa com animais gordos, uma festa com vinhos puros, com tutanos gordos, e  com vinhos puros, bem  purificados.

[[v23-25-7]]

^<<v23-25-7,7>>^ E destruirá neste monte a máscara do rosto, com que todos os povos andam cobertos, e o véu com que todas as nações se escondem.

[[v23-25-8]]

^<<v23-25-8,8>>^ Aniquilará a morte para sempre, e assim  enxugará o Senhor Jeová  as lágrimas de todos os rostos, e tirará o opróbrio do seu povo de toda a terra; porque o Senhor o disse.

[[v23-25-9]]

^<<v23-25-9,9>>^ E naquele dia se dirá: Eis que este é  o nosso Deus, a quem aguardávamos, e ele nos salvará: este é  o Senhor, a quem aguardávamos: na sua salvação gozaremos e nos alegraremos.

[[v23-25-10]]

^<<v23-25-10,10>>^ Porque a mão do Senhor descansará neste monte; mas Moabe será trilhado debaixo dele, como se trilha a palha no monturo.

[[v23-25-11]]

^<<v23-25-11,11>>^ E estenderá as suas mãos por entre eles, como as  estende o nadador para nadar; e abaterá a sua altivez com a perícia das suas mãos deles.

[[v23-25-12]]

^<<v23-25-12,12>>^ E abaixará as altas fortalezas dos teus muros; abatê-las-á e  derribá-las-á por terra até ao pó.

'''

xref:023-isaias/023-isaias-024.adoc#v23-24-0[&#60; Capítulo Anterior] | <<v23-25-0,Topo>> | xref:023-isaias/023-isaias-026.adoc#v23-26-0[Próximo Capítulo &#62;]