include::./index.adoc[]

[[v23-14-0]]
=== Isaías, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-14-1]]

^<<v23-14-1,1>>^ PORQUE o Senhor se compadecerá de Jacó, e ainda elegerá a Israel e os porá na sua própria terra: e ajuntar-se-ão com eles os estranhos, e se achegarão à casa de Jacó.

[[v23-14-2]]

^<<v23-14-2,2>>^ E os povos os receberão, e os levarão aos seus lugares, e a casa de Israel os possuirá por servos e por servas, na terra do Senhor; e cativarão aqueles que os cativaram, e dominarão os seus opressores.

[[v23-14-3]]

^<<v23-14-3,3>>^ E acontecerá que  no dia em que Deus vier a dar-te descanso do teu trabalho, e do teu tremor, e da dura servidão com que te fizeram servir.

[[v23-14-4]]

^<<v23-14-4,4>>^ Então proferirás este dito contra o rei de Babilônia e dirás: Como cessou o opressor! a cidade dourada acabou!

[[v23-14-5]]

^<<v23-14-5,5>>^ Já  quebrantou o Senhor o bastão dos ímpios e  o cetro dos dominadores.

[[v23-14-6]]

^<<v23-14-6,6>>^ Aquele que feria os povos com furor, com praga incessante, o que com ira dominava as nações, agora  é perseguido, sem que alguém o possa impedir.

[[v23-14-7]]

^<<v23-14-7,7>>^ Já  descansa, já  está sossegada toda a terra! exclamam com júbilo.

[[v23-14-8]]

^<<v23-14-8,8>>^ Até as faias se alegram sobre ti, e  os cedros do Líbano, dizendo : Desde que tu caíste ninguém sobe contra nós para nos cortar.

[[v23-14-9]]

^<<v23-14-9,9>>^ O inferno desde o profundo se turbou por ti, para te sair ao encontro na tua vinda: despertou por ti os mortos, e  todos os príncipes da terra, e  fez levantar dos seus tronos a todos os reis das nações.

[[v23-14-10]]

^<<v23-14-10,10>>^ Estes todos responderão, e te dirão: Tu também adoeceste como nós, e  foste semelhante a nós.

[[v23-14-11]]

^<<v23-14-11,11>>^ Já  foi derribada no inferno a tua soberba com o som dos teus alaúdes: os bichinhos debaixo de ti se estenderão, e os bichos te cobrirão.

[[v23-14-12]]

^<<v23-14-12,12>>^ Como caíste do céu, ó estrela da manhã, filha da alva! como  foste lançado por terra, tu que debilitavas as nações!

[[v23-14-13]]

^<<v23-14-13,13>>^ E tu dizias no teu coração: Eu subirei ao céu, acima das estrelas de Deus exaltarei o meu trono, e no monte da congregação me assentarei, da banda dos lados do norte.

[[v23-14-14]]

^<<v23-14-14,14>>^ Subirei acima das mais altas nuvens, e serei semelhante ao Altíssimo.

[[v23-14-15]]

^<<v23-14-15,15>>^ E contudo levado serás ao inferno, ao mais profundo do abismo.

[[v23-14-16]]

^<<v23-14-16,16>>^ Os que te virem te contemplarão, considerar-te-ão, e dirão : É este o varão que fazia estremecer a terra, e que fazia tremer os reinos?

[[v23-14-17]]

^<<v23-14-17,17>>^ Que punha o mundo como um deserto, e assolava as suas cidades? que a seus cativos não deixava ir  soltos para suas  casas?

[[v23-14-18]]

^<<v23-14-18,18>>^ Todos os reis das nações, todos eles, jazem com honra, cada um na sua casa.

[[v23-14-19]]

^<<v23-14-19,19>>^ Mas tu és  lançado da tua sepultura, como um  renovo abominável, como um  vestido de mortos atravessados à espada, como  os que descem ao covil de pedras, como corpo morto e pisado.

[[v23-14-20]]

^<<v23-14-20,20>>^ Com eles não te reunirás na sepultura; porque destruíste a tua terra e  mataste o teu povo: a descendência dos malignos não será nomeada para sempre.

[[v23-14-21]]

^<<v23-14-21,21>>^ Preparai a matança para os filhos por causa da maldade de seus pais, para que não se levantem, e possuam a terra, e encham o mundo de cidades.

[[v23-14-22]]

^<<v23-14-22,22>>^ Porque me levantarei contra eles, diz o Senhor dos Exércitos, e desarraigarei de Babilônia o nome, e os resíduos, e o filho, e o neto, diz o Senhor.

[[v23-14-23]]

^<<v23-14-23,23>>^ E reduzi-la-ei a possessão de corujas e a lagoas de águas: e varrê-la-ei com vassoura de perdição, diz o Senhor dos Exércitos.

[[v23-14-24]]

^<<v23-14-24,24>>^ O Senhor dos Exércitos jurou, dizendo: Como pensei, assim sucederá, e como determinei, assim se efetuará.

[[v23-14-25]]

^<<v23-14-25,25>>^ Quebrantarei a Assíria na minha terra, e nas minhas montanhas a pisarei, para que o seu jugo se aparte deles e a sua carga se desvie dos seus ombros.

[[v23-14-26]]

^<<v23-14-26,26>>^ Este é  o conselho que foi determinado sobre toda esta terra; e esta é  a mão que está estendida sobre todas as nações.

[[v23-14-27]]

^<<v23-14-27,27>>^ Porque o Senhor dos Exércitos o determinou; quem pois o invalidará? e a sua mão estendida está; quem pois a fará voltar atrás?

[[v23-14-28]]

^<<v23-14-28,28>>^ No ano em que morreu o rei Acaz, houve este peso.

[[v23-14-29]]

^<<v23-14-29,29>>^ Não te alegres, tu, toda a Filístia, por ser quebrada a vara que te feria; porque da raiz da cobra sairá um basilisco, e o seu fruto será uma  serpente ardente, voadora.

[[v23-14-30]]

^<<v23-14-30,30>>^ E os primogênitos dos pobres serão apascentados, e os necessitados se deitarão seguros; mas farei morrer de fome a tua raiz, e serão destruídos os teus resíduos.

[[v23-14-31]]

^<<v23-14-31,31>>^ Uiva, ó porta; grita, ó cidade; tu, ó Filístia, estás  toda derretida; porque do norte vem um  fumo, e ninguém ficará solitário no tempo determinado.

[[v23-14-32]]

^<<v23-14-32,32>>^ Que se responderá pois aos mensageiros do povo? Que o Senhor fundou a Sião, para que os opressos do seu povo nela encontrem abrigo.

'''

xref:023-isaias/023-isaias-013.adoc#v23-13-0[&#60; Capítulo Anterior] | <<v23-14-0,Topo>> | xref:023-isaias/023-isaias-015.adoc#v23-15-0[Próximo Capítulo &#62;]