include::./index.adoc[]

[[v23-44-0]]
=== Isaías, 44
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-44-1]]

^<<v23-44-1,1>>^ AGORA pois, ouve ó Jacó, servo meu, e tu  ó Israel, a quem escolhi.

[[v23-44-2]]

^<<v23-44-2,2>>^ Assim diz o Senhor que te  criou e te formou desde o ventre, e que te ajudará: Não temas, ó Jacó, servo meu, e tu, Jesurum, a quem escolhi.

[[v23-44-3]]

^<<v23-44-3,3>>^ Porque derramarei água sobre o sedento, e rios sobre a terra  seca; derramarei o meu Espírito sobre a tua posteridade, e a minha bênção sobre os teus descendentes.

[[v23-44-4]]

^<<v23-44-4,4>>^ E brotarão entre a erva, como salgueiros junto aos ribeiros das águas.

[[v23-44-5]]

^<<v23-44-5,5>>^ Este dirá: Eu sou  do Senhor; e aquele se chamará do nome de Jacó; e aquele outro escreverá com  a sua mão: Eu sou  do Senhor; e por sobrenome tomará o nome de Israel.

[[v23-44-6]]

^<<v23-44-6,6>>^ Assim diz o Senhor, Rei de Israel, e seu Redentor, o Senhor dos Exércitos: Eu sou  o primeiro, e eu sou  o último, e fora de mim não há  Deus.

[[v23-44-7]]

^<<v23-44-7,7>>^ E quem chamará como eu, e anunciará isto, e o porá em ordem perante mim, desde que ordenei um povo eterno? esse que anuncie as cousas futuras, e as que ainda  hão de vir.

[[v23-44-8]]

^<<v23-44-8,8>>^ Não vos assombreis, nem temais; porventura  desde então, não vo-lo fiz ouvir, e não vo-lo anunciei? porque vós sois as minhas testemunhas. Há outro Deus além de mim? Não, não há outra Rocha que eu conheça.

[[v23-44-9]]

^<<v23-44-9,9>>^ Todos os artífices de imagens de escultura são  vaidade, e as suas cousas mais desejáveis são de nenhum préstimo; e suas mesmas testemunhas nada veem nem entendem, para que eles sejam confundidos.

[[v23-44-10]]

^<<v23-44-10,10>>^ Quem forma um deus, e funde uma imagem de escultura, que é de nenhum préstimo?

[[v23-44-11]]

^<<v23-44-11,11>>^ Eis que todos os seus seguidores ficarão confundidos, pois os mesmos artífices são de entre os homens; ajuntem-se todos, e  levantem-se: assombrar-se-ão, e serão juntamente confundidos.

[[v23-44-12]]

^<<v23-44-12,12>>^ O ferreiro faz  o machado, e trabalha nas brasas, e o forma com martelos, e o lavra com a força do seu braço: ele tem fome, e a sua força falta, e  não bebe água, e desfalece.

[[v23-44-13]]

^<<v23-44-13,13>>^ O carpinteiro estende a régua, emprega a almagra, aplaina com o cepilho, e marca com o compasso: e faz o seu deus  à semelhança dum  homem, segundo a forma dum  homem, para ficar em casa.

[[v23-44-14]]

^<<v23-44-14,14>>^ Tomou para si cedros, ou toma um  cipreste, ou um  carvalho, e esforça-se contra as árvores do bosque: planta um  olmeiro, e a chuva o  faz crescer.

[[v23-44-15]]

^<<v23-44-15,15>>^ Então servirão ao homem para queimar; com isso se aquenta, e coze o pão: também faz um deus, e se prostra diante dele; fabrica uma  imagem de escultura, e ajoelha diante dela.

[[v23-44-16]]

^<<v23-44-16,16>>^ Metade queima no fogo, com a outra  metade come carne; assa-a, e farta-se: também se aquenta, e diz: Ora já  me aquentei, já vi o fogo.

[[v23-44-17]]

^<<v23-44-17,17>>^ Então do resto faz um deus, uma imagem de escultura: ajoelha-se diante dela, e se inclina, e ora-lhe, e diz: Livra-me, porquanto tu és  o meu deus.

[[v23-44-18]]

^<<v23-44-18,18>>^ Nada sabem, nem entendem; porque se lhe untaram os olhos, para que não vejam, e  os seus corações, para que não entendam.

[[v23-44-19]]

^<<v23-44-19,19>>^ E nenhum deles  toma isto  a peito, e já não têm conhecimento nem entendimento para dizer: Metade queimei no fogo, e cozi pão sobre as suas brasas, assei sobre elas  carne, e a  comi: e faria eu do resto uma abominação? ajoelhar-me-ia eu ao que saiu duma  árvore?

[[v23-44-20]]

^<<v23-44-20,20>>^ Apascenta-se de cinza: o seu  coração enganado o desviou; de maneira que não pode livrar a sua alma, nem dizer: Não há uma mentira na minha mão direita?

[[v23-44-21]]

^<<v23-44-21,21>>^ Lembra-te destas cousas ó Jacó, e ó Israel, porquanto és  meu servo; eu te formei, meu servo és , ó Israel; não me esquecerei de ti.

[[v23-44-22]]

^<<v23-44-22,22>>^ Desfaço as tuas transgressões como a névoa, e os teus pecados como a nuvem: torna-te para mim, porque eu te remi.

[[v23-44-23]]

^<<v23-44-23,23>>^ Cantai alegres, vós, ó céus, porque o Senhor fez isto: exultai vós, as partes mais baixas da terra; vós, montes, retumbai com júbilo; também  vós, bosques, e todas as árvores em vós; porque o Senhor remiu a Jacó, e glorificou-se em Israel.

[[v23-44-24]]

^<<v23-44-24,24>>^ Assim diz o Senhor, teu Redentor, e que te formou desde o ventre: Eu sou  o Senhor que faço todas as causas, que estendo os céus, e espraio a terra por mim mesmo;

[[v23-44-25]]

^<<v23-44-25,25>>^ Que desfaço os sinais dos inventores de mentiras, e enlouqueço os adivinhos; que faço tornar atrás os sábios, e transtorno a ciência deles;

[[v23-44-26]]

^<<v23-44-26,26>>^ Sou eu quem confirma a palavra do seu servo, e cumpre o conselho dos seus mensageiros; quem diz a Jerusalém: Tu serás habitada, e às cidades de Judá: Sereis reedificadas, e eu levantarei as suas ruínas;

[[v23-44-27]]

^<<v23-44-27,27>>^ Quem diz à profundeza: Seca-te, e eu secarei os teus rios;

[[v23-44-28]]

^<<v23-44-28,28>>^ Quem diz de Ciro: É  meu pastor, e cumprirá tudo o que me apraz; dizendo também a Jerusalém: Sê edificada; e ao  templo: Funda-te.

'''

xref:023-isaias/023-isaias-043.adoc#v23-43-0[&#60; Capítulo Anterior] | <<v23-44-0,Topo>> | xref:023-isaias/023-isaias-045.adoc#v23-45-0[Próximo Capítulo &#62;]