include::./index.adoc[]

[[v23-58-0]]
=== Isaías, 58
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-58-1]]

^<<v23-58-1,1>>^ CLAMA em alta voz, não te detenhas, levanta a tua voz como a trombeta e anuncia ao meu povo a sua transgressão, e à casa de Jacó os seus pecados.

[[v23-58-2]]

^<<v23-58-2,2>>^ Todavia me procuram cada dia, tomam prazer em saber os meus caminhos; como um povo que pratica a justiça, e não deixa o direito do seu Deus, perguntam-me pelos direitos da justiça, têm prazer em se chegar a Deus,

[[v23-58-3]]

^<<v23-58-3,3>>^ Dizendo : Por que jejuamos nós, e tu não atentas para isso? Por que  afligimos as nossas almas, e tu o não sabes? Eis que no dia em que jejuais achais o vosso  próprio contentamento, e requereis todo o vosso trabalho.

[[v23-58-4]]

^<<v23-58-4,4>>^ Eis que para contendas e debates jejuais, e para dardes punhadas impiamente: não jejueis como hoje, para fazer ouvir a vossa voz no alto.

[[v23-58-5]]

^<<v23-58-5,5>>^ Seria este o jejum que eu escolheria: que o homem um dia aflija a sua alma, que incline a sua cabeça como o junco, e estenda debaixo de si  saco e cinza? chamarias tu a isto jejum e dia aprazível ao Senhor?

[[v23-58-6]]

^<<v23-58-6,6>>^ Porventura  não é  este o jejum que escolhi? que soltes as ligaduras da impiedade, que desfaças as ataduras do jugo? e que deixes livres os quebrantados, e despedaces todo o jugo?

[[v23-58-7]]

^<<v23-58-7,7>>^ Porventura  não é também  que repartas o teu pão com o faminto, e recolhas em casa os pobres desterrados? e, vendo o nu, o cubras, e não te escondas da tua carne?

[[v23-58-8]]

^<<v23-58-8,8>>^ Então romperá a tua luz como a alva, e a tua cura apressadamente brotará, e a tua justiça irá adiante da tua face, e  a glória do Senhor será a tua retaguarda.

[[v23-58-9]]

^<<v23-58-9,9>>^ Então clamarás, e o Senhor te  responderá: gritarás, e ele dirá: Eis-me aqui: se tirares do meio de ti o jugo, o estender do dedo, e o falar vaidade;

[[v23-58-10]]

^<<v23-58-10,10>>^ E se  abrires a tua alma ao faminto, e fartares a alma aflita: então a  tua luz nascerá nas trevas, e a tua escuridão será  como o meio-dia.

[[v23-58-11]]

^<<v23-58-11,11>>^ E o Senhor te guiará continuamente, e fartará a tua alma em lugares secos, e fortificará teus ossos; e serás como um  jardim regado, e como um  manancial, cujas águas nunca faltam.

[[v23-58-12]]

^<<v23-58-12,12>>^ E os que de ti procederem edificarão os lugares antigamente assolados; e  levantarás os fundamentos de geração em geração: e chamar-te-ão reparador das roturas, e restaurador de veredas para morar.

[[v23-58-13]]

^<<v23-58-13,13>>^ Se desviares o teu pé do sábado, de  fazer a tua vontade no meu santo dia, e se chamares ao sábado deleitoso, e santo dia  do Senhor digno de honra, e o honrares não seguindo os teus caminhos, nem  pretendendo fazer  a tua própria vontade, nem falar as tuas próprias palavras,

[[v23-58-14]]

^<<v23-58-14,14>>^ Então te deleitarás no Senhor, e te farei cavalgar sobre as alturas da terra, e te sustentarei com a herança de teu pai Jacó; porque a boca do Senhor o disse.

'''

xref:023-isaias/023-isaias-057.adoc#v23-57-0[&#60; Capítulo Anterior] | <<v23-58-0,Topo>> | xref:023-isaias/023-isaias-059.adoc#v23-59-0[Próximo Capítulo &#62;]