include::./index.adoc[]

[[v23-48-0]]
=== Isaías, 48
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-48-1]]

^<<v23-48-1,1>>^ OUVI isto, casa de Jacó, que vos chamais do nome de Israel, e saístes das águas de Judá, que jurais pelo nome do Senhor, e fazeis menção do Deus de Israel, mas não em verdade nem em justiça.

[[v23-48-2]]

^<<v23-48-2,2>>^ E até da santa cidade tomam o nome e se firmam o Deus de Israel; o Senhor dos Exércitos é  o seu nome.

[[v23-48-3]]

^<<v23-48-3,3>>^ As primeiras cousas desde a antiguidade as anunciei; sim, pronunciou-as a minha boca, e eu as fiz ouvir: apressuradamente as fiz, e passaram.

[[v23-48-4]]

^<<v23-48-4,4>>^ Porque eu sabia que eras  duro, e a tua cerviz um nervo de ferro, e a tua testa de bronze.

[[v23-48-5]]

^<<v23-48-5,5>>^ Por isso to anunciei desde então, e  to fiz ouvir antes que acontecesse, para que não dissesses: O meu ídolo fez estas cousas, ou a minha imagem de escultura, ou a minha imagem de fundição as mandou.

[[v23-48-6]]

^<<v23-48-6,6>>^ Já o  tens ouvido; olha bem para tudo isto; porventura  não o anunciareis? desde agora te faço ouvir cousas novas e ocultas, que nunca conheceste.

[[v23-48-7]]

^<<v23-48-7,7>>^ Agora são criadas, e não desde então, e antes deste  dia não as ouviste, para que não digas: Eis que já eu as sabia.

[[v23-48-8]]

^<<v23-48-8,8>>^ Nem tu as  ouviste, nem tu as conheceste, nem tão pouco desde então foi aberto o teu ouvido, porque eu sabia que obrarias muito perfidamente, e que eras prevaricador desde o ventre.

[[v23-48-9]]

^<<v23-48-9,9>>^ Por amor do meu nome retardarei a minha ira, e por amor  do meu louvor me conterei para contigo para que te não venha a cortar.

[[v23-48-10]]

^<<v23-48-10,10>>^ Eis que te purifiquei, mas não como a prata: provei-te na fornalha da aflição.

[[v23-48-11]]

^<<v23-48-11,11>>^ Por amor de mim, por amor de mim o  farei, porque como seria profanado o meu nome ? e a minha glória não a darei a outrem.

[[v23-48-12]]

^<<v23-48-12,12>>^ Dá-me ouvidos, ó Jacó, e tu, ó Israel, a quem chamei; eu sou  o mesmo, eu o primeiro, eu também o último.

[[v23-48-13]]

^<<v23-48-13,13>>^ Também a minha mão fundou a terra, e a minha destra mediu os céus a palmos; eu os chamarei, e aparecerão juntos.

[[v23-48-14]]

^<<v23-48-14,14>>^ Ajuntai-vos todos vós, e ouvi: Quem, dentre eles tem anunciado estas cousas? O Senhor o amou, e  executará a sua vontade contra Babilônia, e o seu braço será contra  os caldeus.

[[v23-48-15]]

^<<v23-48-15,15>>^ Eu, eu o tenho dito; também já o chamei e  o farei vir, e farei próspero o  seu caminho.

[[v23-48-16]]

^<<v23-48-16,16>>^ Chegai-vos a mim, ouvi isto: Não falei em segredo desde o princípio; desde o tempo em que aquilo se fez eu estava ali: e agora o Senhor Jeová  me enviou o seu Espírito.

[[v23-48-17]]

^<<v23-48-17,17>>^ Assim diz o Senhor, o teu Redentor, o Santo de Israel: Eu sou  o Senhor, o teu Deus, que te ensina o que é útil, e  te guia pelo caminho em que  deves andar.

[[v23-48-18]]

^<<v23-48-18,18>>^ Ah! se tivesses dado ouvidos aos meus mandamentos! então seria a tua paz como o rio, e a tua justiça como as ondas do mar.

[[v23-48-19]]

^<<v23-48-19,19>>^ Também a tua descendência seria como a areia, e os que procedem das tuas entranhas como os seus grãos; o seu nome nunca seria cortado, nem destruído da minha face.

[[v23-48-20]]

^<<v23-48-20,20>>^ Saí de Babilônia, fugi de entre os caldeus. E anunciai com voz de júbilo; fazei ouvir isso, e  levai-o até ao fim da terra; dizei: O Senhor remiu a seu servo Jacó.

[[v23-48-21]]

^<<v23-48-21,21>>^ E não tinham sede, quando  os levava pelos desertos; fez-lhes correr água da rocha: fendendo ele as rochas, as águas manavam delas.

[[v23-48-22]]

^<<v23-48-22,22>>^ Mas os ímpios não têm  paz, disse o Senhor.

'''

xref:023-isaias/023-isaias-047.adoc#v23-47-0[&#60; Capítulo Anterior] | <<v23-48-0,Topo>> | xref:023-isaias/023-isaias-049.adoc#v23-49-0[Próximo Capítulo &#62;]