include::./index.adoc[]

[[v23-7-0]]
=== Isaías, 7
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-7-1]]

^<<v23-7-1,1>>^ SUCEDEU pois nos dias de Acaz, filho de Jotão, filho de Uzias, rei de Judá, que Rezim, rei da Síria, e Peca filho de Remalias, rei de Israel, subiram a Jerusalém, para pelejarem contra ela, mas nada puderam contra ela.

[[v23-7-2]]

^<<v23-7-2,2>>^ E deram aviso à casa de Davi, dizendo: A Síria fez aliança com Efraim. Então se moveu o seu coração, e o coração do seu povo, como se movem as árvores do bosque com o vento.

[[v23-7-3]]

^<<v23-7-3,3>>^ Então disse o Senhor a Isaías: Agora tu e teu filho Sear-Jasube saí ao encontro de Acaz, ao fim do canal do viveiro superior, ao caminho do campo do lavandeiro.

[[v23-7-4]]

^<<v23-7-4,4>>^ E dize-lhe: Acautela-te e aquieta-te; não temas, nem se desanime o teu coração por causa destes dois pedaços de tições fumegantes; por causa do ardor da ira de Rezim e da Síria, e do filho de Remalias.

[[v23-7-5]]

^<<v23-7-5,5>>^ Porquanto a Síria teve contra ti maligno conselho, com  Efraim, e com  o filho de Remalias, dizendo:

[[v23-7-6]]

^<<v23-7-6,6>>^ Vamos subir contra Judá, e atormentemo-lo, e repartamo-lo entre nós, e façamos reinar no meio dele o filho de Tabeal.

[[v23-7-7]]

^<<v23-7-7,7>>^ Assim diz o Senhor Deus: Isto não subsistirá, nem tão pouco acontecerá.

[[v23-7-8]]

^<<v23-7-8,8>>^ Mas a cabeça da Síria será  Damasco, e o cabeça de Damasco Rezim: e dentro de sessenta e cinco anos Efraim será quebrantado, e deixará de ser povo.

[[v23-7-9]]

^<<v23-7-9,9>>^ Entretanto a cabeça de Efraim será  Samaria, e a cabeça de Samaria, o filho de Remalias; se o não crerdes, certamente não ficareis firmes.

[[v23-7-10]]

^<<v23-7-10,10>>^ E continuou o Senhor a falar com Acaz, dizendo:

[[v23-7-11]]

^<<v23-7-11,11>>^ Pede para ti ao Senhor teu Deus um sinal; pede-o ou em baixo nas profundezas ou em cima nas alturas.

[[v23-7-12]]

^<<v23-7-12,12>>^ Acaz, porém, disse: Não o pedirei nem tentarei ao Senhor.

[[v23-7-13]]

^<<v23-7-13,13>>^ Então ele disse: Ouvi agora, ó casa de Davi: Pouco vos é afadigardes os homens, senão que ainda afadigareis também ao meu Deus?

[[v23-7-14]]

^<<v23-7-14,14>>^ Portanto o mesmo Senhor vos dará um sinal: Eis que uma virgem conceberá, e dará à luz um  filho, e será o seu nome Emanuel .

[[v23-7-15]]

^<<v23-7-15,15>>^ Manteiga e mel comerá, até que ele saiba rejeitar o mal e escolher o bem.

[[v23-7-16]]

^<<v23-7-16,16>>^ Na verdade, antes que este menino saiba rejeitar o mal e escolher o bem, a terra de que te enfadas será desamparada dos seus dois reis.

[[v23-7-17]]

^<<v23-7-17,17>>^ Mas o Senhor fará vir sobre ti, e sobre o teu povo, e sobre a casa de teu pai, pelo rei da Assíria, dias tais , quais nunca vieram, desde o dia em que Efraim se separou de Judá.

[[v23-7-18]]

^<<v23-7-18,18>>^ Porque há  de acontecer que naquele dia assobiará o Senhor às moscas, que há no extremo dos rios do Egito, e às abelhas que andam  na terra da Assíria;

[[v23-7-19]]

^<<v23-7-19,19>>^ E virão, e pousarão todas nos vales desertos e nas fendas das rochas, e em todos os espinhos e em todas as florestas.

[[v23-7-20]]

^<<v23-7-20,20>>^ Naquele dia rapará o Senhor com uma  navalha alugada, que está  além do rio, isto é , com o rei da Assíria, a cabeça e os cabelos dos pés: e até a barba totalmente tirará.

[[v23-7-21]]

^<<v23-7-21,21>>^ E sucederá naquele dia que alguém criará uma vaca e duas ovelhas.

[[v23-7-22]]

^<<v23-7-22,22>>^ E acontecerá que por causa da abundância do leite que elas hão de dar, comerá manteiga; e manteiga e mel comerá todo aquele que ficar de resto no meio da terra.

[[v23-7-23]]

^<<v23-7-23,23>>^ Sucederá também naquele dia que todo o lugar, em que houver mil vides, do valor  de mil moedas  de prata, será para sarças e para espinheiros.

[[v23-7-24]]

^<<v23-7-24,24>>^ Com arco e frechas se entrará nele, porque as sarças e os espinheiros cobrirão toda a terra.

[[v23-7-25]]

^<<v23-7-25,25>>^ E também  a todos os montes, que costumam cavar com enxadas, se não irá, por causa  do temor das sarças e dos espinheiros; mas servirão para se mandarem para lá os bois e para serem pisados pelas ovelhas.

'''

xref:023-isaias/023-isaias-006.adoc#v23-6-0[&#60; Capítulo Anterior] | <<v23-7-0,Topo>> | xref:023-isaias/023-isaias-008.adoc#v23-8-0[Próximo Capítulo &#62;]