include::./index.adoc[]

[[v23-37-0]]
=== Isaías, 37
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-37-1]]

^<<v23-37-1,1>>^ E ACONTECEU que, tendo ouvido isto o rei Ezequias, rasgou os seus vestidos, e se cobriu de saco, e entrou na casa do Senhor.

[[v23-37-2]]

^<<v23-37-2,2>>^ E enviou Eliaquim, o mordomo, e Sebna, o escrivão, e os anciãos dos sacerdotes, cobertos de sacos, a Isaías, filho de Amós, o profeta.

[[v23-37-3]]

^<<v23-37-3,3>>^ E disseram-lhe: Assim diz Ezequias: Este dia é  dia de angústia e de vitupérios, e de blasfêmias, porque chegados são os filhos ao parto, e força não há  para os dar à luz.

[[v23-37-4]]

^<<v23-37-4,4>>^ Porventura  o Senhor teu Deus terá ouvido as palavras de Rabsaqué, a quem enviou o rei da Assíria, seu amo, para afrontar o Deus vivo, e para o vituperar com as palavras que o Senhor teu Deus tem ouvido: faze oração pelo resto que ficou.

[[v23-37-5]]

^<<v23-37-5,5>>^ E os servos do rei Ezequias vieram a Isaías.

[[v23-37-6]]

^<<v23-37-6,6>>^ E Isaías lhes disse: Assim direis a vosso amo: Assim diz o Senhor: Não temas à vista das palavras que ouviste, com as quais os servos do rei da Assíria de mim blasfemaram.

[[v23-37-7]]

^<<v23-37-7,7>>^ Eis que porei nele um  espírito, e ele ouvirá um rumor e voltará para a sua terra; e fá-lo-ei cair morto à espada na sua terra.

[[v23-37-8]]

^<<v23-37-8,8>>^ Voltou pois Rabsaqué, e achou o rei da Assíria pelejando contra Libna; porque ouvira que já  se havia retirado de Laquis.

[[v23-37-9]]

^<<v23-37-9,9>>^ E ouviu dizer que Tiraca, rei da Etiópia, tinha saído para lhe fazer guerra. Assim que isto ouviu, enviou mensageiros a Ezequias, dizendo:

[[v23-37-10]]

^<<v23-37-10,10>>^ Assim falareis a Ezequias, rei de Judá, dizendo: Não te engane o teu Deus, em quem confias, dizendo: Jerusalém não será entregue na mão do rei da Assíria.

[[v23-37-11]]

^<<v23-37-11,11>>^ Eis que já  tens ouvido o que fizeram os reis da Assíria a todas as terras, destruindo-as totalmente: e escaparias tu?

[[v23-37-12]]

^<<v23-37-12,12>>^ Porventura  as livraram os deuses das nações que meus pais destruíram: Gozã, e Harã, e Resefe, e os filhos de Édem, que estavam  em Telassar?

[[v23-37-13]]

^<<v23-37-13,13>>^ Onde está o rei de Hamate, e o rei de Arpade, e o rei da cidade de Sefarvaim, Hena e Iva?

[[v23-37-14]]

^<<v23-37-14,14>>^ Recebendo pois Ezequias as cartas das mãos dos mensageiros, e lendo-as, subiu à casa do Senhor; e Ezequias as estendeu perante o Senhor.

[[v23-37-15]]

^<<v23-37-15,15>>^ E orou Ezequias ao Senhor, dizendo:

[[v23-37-16]]

^<<v23-37-16,16>>^ Ó Senhor dos Exércitos, Deus de Israel, que habitas entre os querubins; tu és o Deus, tu somente, de todos os reinos da terra; tu fizeste os céus e a terra.

[[v23-37-17]]

^<<v23-37-17,17>>^ Inclina ó Senhor, o teu ouvido, e ouve: abre, Senhor, os teus olhos, e olha: e ouve todas as palavras de Senaqueribe, as quais ele mandou para afrontar o Deus vivo.

[[v23-37-18]]

^<<v23-37-18,18>>^ Verdade é, Senhor, que os reis da Assíria assolaram todos os países, e suas terras.

[[v23-37-19]]

^<<v23-37-19,19>>^ E lançaram no fogo os seus deuses; porque deuses não eram, senão obra de mãos de homens, madeira e pedra; por isso os destruíram.

[[v23-37-20]]

^<<v23-37-20,20>>^ Agora pois, ó Senhor nosso Deus, livra-nos da sua mão, para que todos os reinos da terra conheçam que só tu és  o Senhor.

[[v23-37-21]]

^<<v23-37-21,21>>^ Então Isaías, filho de Amós, mandou dizer a Ezequias: Assim diz o Senhor, o Deus de Israel: Quanto ao que me pediste acerca de Senaqueribe, rei da Assíria,

[[v23-37-22]]

^<<v23-37-22,22>>^ Esta é  a palavra que o Senhor falou a respeito dele: A virgem, a filha de Sião, te despreza, e de ti zomba; a filha de Jerusalém meneia a cabeça por detrás de ti.

[[v23-37-23]]

^<<v23-37-23,23>>^ A quem afrontaste e de quem blasfemaste? e contra quem alçaste a voz e ergueste os teus olhos ao alto? Contra o Santo de Israel.

[[v23-37-24]]

^<<v23-37-24,24>>^ Por meio de teus servos afrontaste o Senhor, e disseste: Com a multidão dos meus carros subi eu aos cumes dos montes, aos últimos recessos do Líbano; e cortarei os seus altos cedros e as suas faias escolhidas, e entrarei no seu cume mais elevado, no bosque do seu campo fértil.

[[v23-37-25]]

^<<v23-37-25,25>>^ Eu cavei, e bebi as águas; e com as plantas de meus pés sequei todos os rios do Egito.

[[v23-37-26]]

^<<v23-37-26,26>>^ Porventura  não ouviste que já  muito antes eu fiz isto, e já  desde os dias antigos o tinha pensado? Agora porém  se cumpre, e eu quis que tu fosses que destruísses as cidades fortes, e as reduzisses a montões assolados.

[[v23-37-27]]

^<<v23-37-27,27>>^ Por isso os seus moradores, com as mãos caídas, andam atemorizados e envergonhados: eram como  a erva do campo, e a erva verde, e  o feno dos telhados, e o trigo queimado antes da seara.

[[v23-37-28]]

^<<v23-37-28,28>>^ Mas eu conheço o teu assentar, e o teu sair, e o teu entrar, e o teu furor contra mim.

[[v23-37-29]]

^<<v23-37-29,29>>^ Por causa da tua raiva contra mim, e porque a tua arrogância subiu até aos meus ouvidos, eis que porei o meu anzol no teu nariz e o meu freio nos teus beiços, e te farei voltar pelo caminho por onde vieste.

[[v23-37-30]]

^<<v23-37-30,30>>^ E isto te será por sinal: este ano se comerá o que espontaneamente nascer, e no segundo ano o que daí proceder: mas no terceiro ano semeai e segai, e plantai vinhas, e comei os frutos delas.

[[v23-37-31]]

^<<v23-37-31,31>>^ Porque o que escapou da casa de Judá, e ficou de resto, tornará a lançar raízes para baixo, e dará fruto para cima.

[[v23-37-32]]

^<<v23-37-32,32>>^ Porque de Jerusalém sairá o restante, e do monte de Sião o que escapou: o zelo do Senhor dos Exércitos fará isto.

[[v23-37-33]]

^<<v23-37-33,33>>^ Pelo que assim diz o Senhor acerca do rei da Assíria: Não entrará nesta cidade, nem lançará nela frecha alguma : tão pouco virá perante ela com  escudo, ou levantará contra ela tranqueira.

[[v23-37-34]]

^<<v23-37-34,34>>^ Pelo caminho por onde vier, por esse voltará; mas nesta cidade não entrará, diz o Senhor.

[[v23-37-35]]

^<<v23-37-35,35>>^ Porque eu ampararei esta cidade, para a livrar, por amor de mim e por amor do meu servo Davi.

[[v23-37-36]]

^<<v23-37-36,36>>^ Então saiu o anjo do Senhor, e feriu no arraial dos assírios a cento e oitenta e cinco mil; e quando se levantaram pela manhã cedo, eis que tudo eram corpos mortos.

[[v23-37-37]]

^<<v23-37-37,37>>^ Assim Senaqueribe, rei da Assíria, se retirou, e se foi, e voltou, e ficou em Nínive.

[[v23-37-38]]

^<<v23-37-38,38>>^ E sucedeu que estando ele prostrado na casa de Nisroque, seu deus, Adrameleque e Sarezer, seus filhos, o feriram à espada; e eles fugiram para a terra de Arará: e Esaradom, seu filho, reinou em seu lugar.

'''

xref:023-isaias/023-isaias-036.adoc#v23-36-0[&#60; Capítulo Anterior] | <<v23-37-0,Topo>> | xref:023-isaias/023-isaias-038.adoc#v23-38-0[Próximo Capítulo &#62;]