include::./index.adoc[]

[[v23-30-0]]
=== Isaías, 30
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-30-1]]

^<<v23-30-1,1>>^ AI dos filhos rebeldes, diz o Senhor, que tomaram conselho, mas não de mim; e que se cobriram com uma cobertura, mas não do meu espírito, para acrescentarem pecado a pecado.

[[v23-30-2]]

^<<v23-30-2,2>>^ Que descem ao Egito, sem perguntarem à minha boca, para se fortificarem com a força de Faraó, e para confiarem na sombra do Egito.

[[v23-30-3]]

^<<v23-30-3,3>>^ Porque a força de Faraó se vos tornará em vergonha, e a confiança na sombra do Egito em confusão.

[[v23-30-4]]

^<<v23-30-4,4>>^ Porque os seus príncipes estão em Zoã, e os seus embaixadores chegaram a Hanes.

[[v23-30-5]]

^<<v23-30-5,5>>^ Eles se envergonharão de um povo que  de nada lhe servirá, nem de ajuda, nem de proveito, antes de vergonha, e de opróbrio.

[[v23-30-6]]

^<<v23-30-6,6>>^ Peso dos animais do sul. Para a terra de aflição e de angústia (donde vem  a leoa e o leão, o basilisco, e o áspide ardente voador) levarão às costas de jumentinhos as suas fazendas, e sobre as corcovas de camelos os seus tesouros, a um  povo que  de nada lhes  aproveitará.

[[v23-30-7]]

^<<v23-30-7,7>>^ Porque o Egito os  ajudará em vão, e para nenhum fim: pelo que clamei acerca disto: No estarem quietos estará a sua força.

[[v23-30-8]]

^<<v23-30-8,8>>^ Vai pois  agora, escreve isto numa tábua perante eles, e aponta-o num livro; para que fique escrito para o tempo por vir, para sempre e  perpetuamente.

[[v23-30-9]]

^<<v23-30-9,9>>^ Porque povo rebelde é  este, filhos mentirosos, filhos que  não querem ouvir a lei do Senhor.

[[v23-30-10]]

^<<v23-30-10,10>>^ Que dizem aos videntes: Não vejais; e aos profetas: Não profetizeis para nós o que é reto: dizei-nos cousas aprazíveis, e  tende para nós enganadoras lisonjas.

[[v23-30-11]]

^<<v23-30-11,11>>^ Desviai-vos do caminho, apartai-vos da vereda: fazei que deixe de estar o Santo de Israel perante nós.

[[v23-30-12]]

^<<v23-30-12,12>>^ Pelo que assim diz o Santo de Israel: Visto como rejeitais esta palavra, e confiais na opressão e na perversidade, e sobre isso vos estribais,

[[v23-30-13]]

^<<v23-30-13,13>>^ Por isso esta maldade vos será como a parede  fendida, que já forma barriga desde o mais alto sítio, e cuja queda virá subitamente, num momento.

[[v23-30-14]]

^<<v23-30-14,14>>^ E ele o quebrará como se quebra o vaso do oleiro, e , quebrando-o, não se compadecerá: não se achará entre os seus pedaços um que sirva para tomar fogo do lar, ou tirar água da poça.

[[v23-30-15]]

^<<v23-30-15,15>>^ Porque assim diz o Senhor Jeová , o Santo de Israel: Em vos converterdes, e em repousardes, estaria a vossa salvação; no sossego e na confiança estaria a vossa força, mas não quisestes.

[[v23-30-16]]

^<<v23-30-16,16>>^ Mas dizeis: Não; antes sobre cavalos fugiremos; portanto fugireis; e: sobre cavalos  ligeiros cavalgaremos; por isso os vossos perseguidores serão ligeiros.

[[v23-30-17]]

^<<v23-30-17,17>>^ Mil homens fugirão  ao grito dum, e  ao grito de cinco todos  vós fugireis, até que sejais deixados como o mastro no cume do monte, e como a bandeira no outeiro.

[[v23-30-18]]

^<<v23-30-18,18>>^ Por isso o Senhor esperará, para ter misericórdia de vós; e por isso será exalçado, para se compadecer de vós, porque o Senhor é um  Deus de equidade: bem-aventurados todos os que nele esperam.

[[v23-30-19]]

^<<v23-30-19,19>>^ Porque o povo habitará em Sião, em Jerusalém: não chorarás mais: certamente se compadecerá de ti, à voz do teu clamor, e, ouvindo-a, te responderá.

[[v23-30-20]]

^<<v23-30-20,20>>^ Bem vos dará o Senhor pão de angústia e água de aperto, mas os teus instruidores nunca mais fugirão de ti , como voando com asas; antes os teus olhos verão a todos os teus mestres.

[[v23-30-21]]

^<<v23-30-21,21>>^ E os teus ouvidos ouvirão a palavra de que  está por detrás de ti, dizendo: Este é  o caminho, andai nele, sem vos desviardes nem para a direita nem para a esquerda.

[[v23-30-22]]

^<<v23-30-22,22>>^ E terás por contaminadas as coberturas das tuas esculturas de prata, e a coberta das tuas esculturas fundidas de ouro; e as lançarás fora como um  pano imundo, e dirás a cada uma delas: Fora daqui.

[[v23-30-23]]

^<<v23-30-23,23>>^ Então te  dará chuva sobre a tua semente, com que semeares a terra, como também pão da novidade da terra; e esta será fértil e cheia: naquele dia o teu gado pastará em  lugares largos de pasto.

[[v23-30-24]]

^<<v23-30-24,24>>^ E os bois e os jumentinhos que lavram a terra, comerão grão puro, que for padejado com a pá, e cirandado  com a ciranda.

[[v23-30-25]]

^<<v23-30-25,25>>^ E haverá em todo o monte alto, e em todo o outeiro elevado ribeiros e correntes de águas, no dia da grande matança, quando caírem as torres.

[[v23-30-26]]

^<<v23-30-26,26>>^ E será a luz da lua como a luz do sol, e a luz do sol sete vezes maior, como a luz de sete dias, no dia em que o Senhor ligar a quebradura do seu povo, e curar a chaga da sua ferida.

[[v23-30-27]]

^<<v23-30-27,27>>^ Eis que o nome do Senhor vem de longe ardendo na sua ira, e lançando espesso fumo: os seus lábios estão cheios de indignação, e a sua língua é como um  fogo consumidor

[[v23-30-28]]

^<<v23-30-28,28>>^ E a sua respiração é como o ribeiro trasbordando, que  chega até ao pescoço, para peneirar as nações com peneira de vaidade: e um  freio de fazer errar estará nas queixadas dos povos.

[[v23-30-29]]

^<<v23-30-29,29>>^ Um  cântico haverá entre vós, como na noite em  que se celebra uma festa santa; e alegria de coração, como a daquele que sai tocando pífano, para vir ao monte do Senhor, à Rocha de Israel.

[[v23-30-30]]

^<<v23-30-30,30>>^ E o Senhor fará ouvir a glória da sua voz, e fará ver o abaixamento do seu braço, com indignação de ira, e a labareda do seu fogo consumidor, e raios e dilúvio e pedra de saraiva.

[[v23-30-31]]

^<<v23-30-31,31>>^ Porque com a voz do Senhor será desfeita em pedaços a Assíria, que  feriu com a vara.

[[v23-30-32]]

^<<v23-30-32,32>>^ E a cada pancada do bordão do juízo que o Senhor der, haverá tamboris e harpas; e com combates de agitação combaterá contra eles.

[[v23-30-33]]

^<<v23-30-33,33>>^ Porque uma Tofete está  preparada desde ontem; sim, está preparada para o rei; ele a fez profunda e larga; a sua pilha é fogo, e tem muita lenha; o assopro do Senhor como torrente de enxofre a acenderá.

'''

xref:023-isaias/023-isaias-029.adoc#v23-29-0[&#60; Capítulo Anterior] | <<v23-30-0,Topo>> | xref:023-isaias/023-isaias-031.adoc#v23-31-0[Próximo Capítulo &#62;]