include::./index.adoc[]

[[v23-36-0]]
=== Isaías, 36
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-36-1]]

^<<v23-36-1,1>>^ E ACONTECEU no ano décimo quarto do rei Ezequias que Senaqueribe, rei da Assíria subiu contra todas as cidades fortes de Judá, e as tomou.

[[v23-36-2]]

^<<v23-36-2,2>>^ Então o rei da Assíria enviou Rabsaqué, desde Laquis a Jerusalém, ao rei Ezequias com um  grande exército; e ele parou junto ao cano do tanque mais alto, junto ao caminho do campo do lavandeiro.

[[v23-36-3]]

^<<v23-36-3,3>>^ Então saiu a ele Eliaquim, filho de Hilquias, o mordomo, e Sebna, o escrivão, e Joá, filho de Asafe, o chanceler.

[[v23-36-4]]

^<<v23-36-4,4>>^ E Rabsaqué lhes disse: Ora dizei a Ezequias: Assim diz o grande rei, o rei da Assíria: Que confiança é  esta, que tu manifestas?

[[v23-36-5]]

^<<v23-36-5,5>>^ Bem posso eu dizer: Teu conselho e poder para a guerra são apenas vãs palavras: em quem pois  agora confias, que contra mim te rebelas?

[[v23-36-6]]

^<<v23-36-6,6>>^ Eis que confias naquele bordão de cana quebrada, a saber , no Egito, que, se alguém se apoiar nele, lhe entrará pela mão, e lha furará: assim é  Faraó, rei do Egito, para com todos os que nele confiam.

[[v23-36-7]]

^<<v23-36-7,7>>^ Mas se me disseres: No Senhor, nosso Deus, confiamos; porventura  não é  esse aquele cujos altos e cujos altares Ezequias tirou, e disse a Judá e a Jerusalém: Perante este altar vos inclinareis?

[[v23-36-8]]

^<<v23-36-8,8>>^ Ora, pois, dá agora reféns ao meu senhor, o rei da Assíria, e dar-te-ei dois mil cavalos se tu puderes dar cavaleiros para eles.

[[v23-36-9]]

^<<v23-36-9,9>>^ Como, não podendo tu voltar o rosto a um só príncipe dos mínimos servos do meu senhor, confias no Egito, por causa dos carros e cavaleiros?

[[v23-36-10]]

^<<v23-36-10,10>>^ E subi eu agora sem o Senhor contra esta terra, para destruí-la? O Senhor mesmo me disse: Sobe contra esta terra, e destrói-a.

[[v23-36-11]]

^<<v23-36-11,11>>^ Então disse Eliaquim, e Sebna, e Joá, a Rabsaqué: Pedimos- te que  fales aos teus servos em siríaco, por que bem  o entendemos, e não nos fales em judaico, aos ouvidos do povo que está sobre os muros.

[[v23-36-12]]

^<<v23-36-12,12>>^ Mas Rabsaqué disse: Porventura  mandou-me o meu senhor só  ao teu senhor e a ti, para dizer estas palavras? e  não antes aos homens que estão assentados sobre os muros, para que comam convosco o seu esterco, e bebam a sua urina?

[[v23-36-13]]

^<<v23-36-13,13>>^ Rabsaqué pois se pôs em pé, e clamou em alta voz em judaico, e disse: Ouvi as palavras do grande rei, do rei da Assíria.

[[v23-36-14]]

^<<v23-36-14,14>>^ Assim diz o rei: Não vos engane Ezequias: porque não vos poderá livrar.

[[v23-36-15]]

^<<v23-36-15,15>>^ Nem tão pouco Ezequias vos faça confiar no Senhor, dizendo: Infalivelmente nos livrará o Senhor, e  esta cidade não será entregue nas mãos do rei da Assíria.

[[v23-36-16]]

^<<v23-36-16,16>>^ Não deis ouvidos a Ezequias; porque assim diz o rei da Assíria: Aliai-vos comigo, e saí a mim, e coma cada um da  sua vide, e  da sua figueira, e beba cada um da água da sua cisterna;

[[v23-36-17]]

^<<v23-36-17,17>>^ Até que eu venha, e vos leve para uma  terra como a vossa: terra de trigo e de mosto, terra de pão e de vinhas.

[[v23-36-18]]

^<<v23-36-18,18>>^ Não vos engane Ezequias, dizendo: O Senhor nos livrará. Porventura  os deuses das nações livraram cada um a sua terra das mãos do rei da Assíria?

[[v23-36-19]]

^<<v23-36-19,19>>^ Onde estão  os deuses de Hamate e de Arpade? onde estão  os deuses de  Sefarvaim? Porventura  livraram eles a Samaria da minha mão?

[[v23-36-20]]

^<<v23-36-20,20>>^ Quais são  eles, dentre todos os deuses destes países, os que livraram a sua terra das minhas mãos para que o Senhor livrasse a Jerusalém das minha mãos?

[[v23-36-21]]

^<<v23-36-21,21>>^ Mas eles calaram-se e não lhe responderam palavra: porque havia mandado do rei, dizendo: não lhe respondereis.

[[v23-36-22]]

^<<v23-36-22,22>>^ Então Eliaquim, filho de Hilquias, o mordomo, e Sebna, o escrivão, e Joá, filho de Asafe, o chanceler, vieram a Ezequias com os vestidos rasgados, e lhe fizeram saber as palavras de Rabsaqué.

'''

xref:023-isaias/023-isaias-035.adoc#v23-35-0[&#60; Capítulo Anterior] | <<v23-36-0,Topo>> | xref:023-isaias/023-isaias-037.adoc#v23-37-0[Próximo Capítulo &#62;]