include::./index.adoc[]

[[v23-23-0]]
=== Isaías, 23
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-23-1]]

^<<v23-23-1,1>>^ PESO de Tiro. Uivai, navios de Tarsis, porque está assolada, a ponto de não haver nela casa nenhuma, e  de ninguém mais entrar nela: desde a terra de Quitim lhes foi isto  revelado.

[[v23-23-2]]

^<<v23-23-2,2>>^ Calai-vos, moradores da ilha, vós a quem encheram os mercadores de Sidom, navegando pelo mar.

[[v23-23-3]]

^<<v23-23-3,3>>^ E a sua provisão era  a semente de Sicor, que vinha  com as muitas águas, a ceifa do Nilo, e ela era a feira das nações.

[[v23-23-4]]

^<<v23-23-4,4>>^ Envergonha-te, ó Sidom, porque o mar, a fortaleza do mar, fala, dizendo: Eu não tive dores de parto, nem dei à luz, nem ainda criei mancebos, nem  eduquei donzelas.

[[v23-23-5]]

^<<v23-23-5,5>>^ Como com as novas do Egito, assim haverá dores quando se ouvirem as  de Tiro.

[[v23-23-6]]

^<<v23-23-6,6>>^ Passai a Tarsis: uivai, moradores da ilha.

[[v23-23-7]]

^<<v23-23-7,7>>^ É esta a vossa cidade  que andava pulando de alegria? cuja antiguidade vem de dias remotos? pois  levá-la-ão os seus próprios pés para longe andarem a peregrinar.

[[v23-23-8]]

^<<v23-23-8,8>>^ Quem formou este desígnio contra Tiro, a cidade coroada, cujos mercadores são  príncipes e  cujos negociantes são os mais nobres da terra?

[[v23-23-9]]

^<<v23-23-9,9>>^ O Senhor dos Exércitos formou este desígnio para denegrir a soberba de todo o ornamento, e  envilecer os mais nobres da terra.

[[v23-23-10]]

^<<v23-23-10,10>>^ Passa como o Nilo pela tua terra, ó filha de Tarsis; já não há cinto ao redor de ti.

[[v23-23-11]]

^<<v23-23-11,11>>^ Ele estendeu a sua mão sobre o mar, e turbou os reinos: o Senhor deu mandado contra Canaã, para que se destruíssem as suas fortalezas.

[[v23-23-12]]

^<<v23-23-12,12>>^ E disse: Nunca mais pularás de alegria, ó oprimida donzela, filha de Sidom: levanta-te, passa a Quitim, e mesmo ali não terás descanso.

[[v23-23-13]]

^<<v23-23-13,13>>^ Vede a terra dos caldeus, ainda este povo não era povo; a Assíria a fundou para os que moravam no deserto: levantaram as suas fortalezas, e edificaram os seus paços; mas já está arruinada de todo.

[[v23-23-14]]

^<<v23-23-14,14>>^ Uivai, navios de Tarsis, porque é destruída a vossa força.

[[v23-23-15]]

^<<v23-23-15,15>>^ E sucederá naquele dia que Tiro será posta em esquecimento por setenta anos, conforme os dias dum rei: mas no fim de setenta anos Tiro será como a canção duma  prostituta.

[[v23-23-16]]

^<<v23-23-16,16>>^ Toma a harpa, rodeia a cidade, ó prostituta entregue ao esquecimento: toca bem, canta e repete a ária, para que haja memória de ti.

[[v23-23-17]]

^<<v23-23-17,17>>^ Porque será no fim de setenta anos que o Senhor visitará a Tiro, e ela tornará à sua ganância de prostituta, e terá comércio com todos os reinos que há sobre a face da terra.

[[v23-23-18]]

^<<v23-23-18,18>>^ E será consagrado ao Senhor o seu comércio e a sua ganância de prostituta; não se entesourará, nem se fechará; mas o seu comércio será para os que habitam perante o Senhor, para que comam suficientemente, e tenham vestido durável.

'''

xref:023-isaias/023-isaias-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaias/023-isaias-024.adoc#v23-24-0[Próximo Capítulo &#62;]