include::./index.adoc[]

[[v23-18-0]]
=== Isaías, 18
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-18-1]]

^<<v23-18-1,1>>^ AI da terra que ensombra com as suas asas, que está  além dos rios da Etiópia.

[[v23-18-2]]

^<<v23-18-2,2>>^ Que envia embaixadores por mar em navios de junco sobre as águas, dizendo: Ide, mensageiros velozes, a uma nação alta e polida, a um  povo terrível desde o seu princípio; a uma  nação de medidas e de vexames, cuja terra os rios dividem.

[[v23-18-3]]

^<<v23-18-3,3>>^ Vós, todos os habitadores do mundo, e vós os moradores da terra, quando se arvorar a bandeira nos  montes, o vereis; e quando se tocar a trombeta, o  ouvireis.

[[v23-18-4]]

^<<v23-18-4,4>>^ Porque assim me disse o Senhor: Estarei quieto, olhando desde a minha morada, como o ardor do sol resplandecente, como a nuvem do orvalho no calor da sega.

[[v23-18-5]]

^<<v23-18-5,5>>^ Porque antes da sega, quando já  o renovo está perfeito, e as uvas verdes amadurecem, então podará os sarmentos e tirará os ramos, e os cortará.

[[v23-18-6]]

^<<v23-18-6,6>>^ Eles serão deixados juntos às aves dos montes e aos animais da terra: e sobre eles veranearão as aves de rapina, e todos os animais da terra invernarão sobre eles.

[[v23-18-7]]

^<<v23-18-7,7>>^ Naquele tempo trará um  presente ao Senhor dos exércitos um povo alto e polido, e um povo terrível desde o seu princípio; uma nação de medidas e de vexames cuja terra os rios dividem; ao lugar do nome do Senhor dos Exércitos, ao monte de Sião.

'''

xref:023-isaias/023-isaias-017.adoc#v23-17-0[&#60; Capítulo Anterior] | <<v23-18-0,Topo>> | xref:023-isaias/023-isaias-019.adoc#v23-19-0[Próximo Capítulo &#62;]