include::./index.adoc[]

[[v23-56-0]]
=== Isaías, 56
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-56-1]]

^<<v23-56-1,1>>^ ASSIM diz o Senhor: Mantende o juízo e fazei justiça, porque a minha salvação está prestes a vir, e a minha justiça a manifestar-se.

[[v23-56-2]]

^<<v23-56-2,2>>^ Bem-aventurado o homem que  fizer isto, e o filho do homem que  lançar mão disto; que se guarda de profanar o sábado, e guarda a sua mão de perpetrar algum mal.

[[v23-56-3]]

^<<v23-56-3,3>>^ E não fale o filho do estrangeiro, que se houver chegado ao Senhor, dizendo: De todo me apartará o Senhor do seu povo: nem tão pouco diga o eunuco: Eis que eu sou uma  árvore seca.

[[v23-56-4]]

^<<v23-56-4,4>>^ Porque assim diz o Senhor a respeito dos eunucos, que guardam os meus sábados, e escolhem aquilo que me agrada, e abraçam o meu concerto.

[[v23-56-5]]

^<<v23-56-5,5>>^ Também lhes darei na minha casa e dentro dos meus muros um  lugar e um  nome, melhor do que o de filhos e filhas: um  nome eterno darei a cada um deles que nunca se apagará.

[[v23-56-6]]

^<<v23-56-6,6>>^ E aos filhos dos estrangeiros, que se chegarem ao Senhor, para o servirem, e para amarem o nome do Senhor, sendo deste modo servos seus, todos os que guardarem o sábado, não o profanando, e os que abraçarem o meu concerto,

[[v23-56-7]]

^<<v23-56-7,7>>^ Também os levarei ao meu santo monte, e os festejarei na minha casa de oração; os seus holocaustos e os seus sacrifícios serão  aceitos no meu altar, porque a minha casa será chamada casa de oração para todos os povos.

[[v23-56-8]]

^<<v23-56-8,8>>^ Assim  diz o Senhor Jeová , que ajunta os dispersos de Israel: Ainda ajuntarei outros aos que já se lhe ajuntaram.

[[v23-56-9]]

^<<v23-56-9,9>>^ Vós, todos os animais do campo, todas as feras dos bosques, vinde comer.

[[v23-56-10]]

^<<v23-56-10,10>>^ Todos os seus atalaias são  cegos, nada sabem; todos são  cães mudos, não podem ladrar: andam  adormecidos, estão  deitados, e  amam o tosquenejar.

[[v23-56-11]]

^<<v23-56-11,11>>^ E estes cães são  gulosos, não se podem fartar; e eles são  pastores que nada compreendem: todos eles se tornam para o seu caminho, cada um para a sua ganância, cada um  por sua parte.

[[v23-56-12]]

^<<v23-56-12,12>>^ Vinde, dizem eles , trarei vinho, e beberemos bebida forte; e o dia de amanhã será como este, e ainda  maior e  mais famoso.

'''

xref:023-isaias/023-isaias-055.adoc#v23-55-0[&#60; Capítulo Anterior] | <<v23-56-0,Topo>> | xref:023-isaias/023-isaias-057.adoc#v23-57-0[Próximo Capítulo &#62;]