include::./index.adoc[]

[[v23-66-0]]
=== Isaías, 66
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-66-1]]

^<<v23-66-1,1>>^ ASSIM diz o Senhor: O céu é o meu trono, e a terra o escabelo dos meus pés: que casa me edificaríeis vós? e que lugar seria o do meu descanso?

[[v23-66-2]]

^<<v23-66-2,2>>^ Porque a minha mão fez todas estas cousas, e todas estas cousas foram feitas, diz o Senhor; mas eis para quem olharei: para o pobre e abatido de espírito, e que treme da minha palavra.

[[v23-66-3]]

^<<v23-66-3,3>>^ O que mata um  boi é como o que  fere um homem; o que sacrifica um cordeiro, como o que  degola um cão; o que oferece uma oblação, como o que oferece  sangue de porco; o que queima incenso, como o que  bendiz a um ídolo: também estes escolhem os seus próprios caminhos, e a sua alma toma prazer nas suas abominações.

[[v23-66-4]]

^<<v23-66-4,4>>^ Também eu quererei as suas ilusões, farei vir sobre eles os seus temores; porquanto clamei e ninguém respondeu, falei, e não escutaram; mas fizeram o que parece  mal aos meus olhos, e escolheram aquilo em que não tinha prazer.

[[v23-66-5]]

^<<v23-66-5,5>>^ Ouvi a palavra do Senhor, os que tremeis da sua palavra: Vossos irmãos que vos aborrecem e que para longe vos lançam por amor do meu nome, dizem: O Senhor seja glorificado, para que vejamos a vossa alegria; mas eles serão confundidos.

[[v23-66-6]]

^<<v23-66-6,6>>^ Uma voz de grande rumor virá da cidade, uma voz do templo, a voz do Senhor, que dá o pago aos seus inimigos.

[[v23-66-7]]

^<<v23-66-7,7>>^ Antes que estivesse de parto, deu à luz; antes que lhe viessem as dores, deu à luz um filho.

[[v23-66-8]]

^<<v23-66-8,8>>^ Quem jamais  ouviu tal cousa? quem viu cousas semelhantes? Poder-se-ia fazer nascer uma terra num só  dia? nasceria uma nação de uma só  vez? mas Sião esteve de parto e já deu à luz seus filhos.

[[v23-66-9]]

^<<v23-66-9,9>>^ Abriria eu a madre, e não geraria: diz o Senhor: geraria eu, e fecharia a madre? diz o teu Deus.

[[v23-66-10]]

^<<v23-66-10,10>>^ Regozijai-vos com Jerusalém, e alegrai-vos por ela, vós todos os que a amais: enchei-vos por ela de alegria, todos os que por ela pranteastes;

[[v23-66-11]]

^<<v23-66-11,11>>^ Para que mameis, e vos farteis dos peitos das suas consolações: para que sugueis, e vos deleiteis com o resplendor da sua glória.

[[v23-66-12]]

^<<v23-66-12,12>>^ Porque assim diz o Senhor: Eis que estenderei sobre ela a paz como um rio, e a glória das nações como um ribeiro que trasborda; então mamareis, ao colo vos trarão, e sobre os joelhos vos afagarão.

[[v23-66-13]]

^<<v23-66-13,13>>^ Como alguém a quem consola sua mãe, assim eu vos consolarei; e em Jerusalém vós sereis consolados.

[[v23-66-14]]

^<<v23-66-14,14>>^ Isso vereis e alegrar-se-á o vosso coração, e os vossos ossos reverdecerão como a erva tenra: então a mão do Senhor será notória aos seus servos e ele se indignará contra os seus inimigos.

[[v23-66-15]]

^<<v23-66-15,15>>^ Porque, eis que o Senhor virá em fogo; e os seus carros como um torvelinho; para tornar a sua ira em furor, e a sua repreensão em chamas de fogo.

[[v23-66-16]]

^<<v23-66-16,16>>^ Porque com fogo e com a sua espada entrará o Senhor em juízo com toda a carne; e os mortos do Senhor serão multiplicados.

[[v23-66-17]]

^<<v23-66-17,17>>^ Os que se santificam e se purificam nos jardins uns após outros, os que comem carne de porco, e a abominação, e o rato, juntamente serão consumidos, diz o Senhor.

[[v23-66-18]]

^<<v23-66-18,18>>^ Porque conheço as suas obras e os seus pensamentos! o tempo  vem em que ajuntarei todas as nações e línguas; e virão, e verão a minha glória.

[[v23-66-19]]

^<<v23-66-19,19>>^ E porei entre eles um sinal, e os que deles escaparem enviarei às nações, a Tarsis, Pul, e Lude, frecheiros, a  Tubal e Javã, até às ilhas de mais  longe, que não ouviram a minha fama, nem viram a minha glória; e anunciarão a minha glória entre as nações.

[[v23-66-20]]

^<<v23-66-20,20>>^ E trarão todos os vossos irmãos, dentre todas as nações, por presente ao Senhor, sobre cavalos, e em carros, e em liteiras, e sobre mulas, e sobre dromedários, ao meu santo monte, a  Jerusalém, diz o Senhor: como quando  os filhos de Israel trazem as suas ofertas em vasos limpos à casa do Senhor.

[[v23-66-21]]

^<<v23-66-21,21>>^ E também deles tomarei a alguns para sacerdotes e  para levitas diz o Senhor.

[[v23-66-22]]

^<<v23-66-22,22>>^ Porque, como os céus novos, e a terra nova, que hei de fazer, estarão diante da minha face, diz o Senhor, assim há de estar a vossa posteridade e o vosso nome.

[[v23-66-23]]

^<<v23-66-23,23>>^ E será que desde uma  lua nova até à outra, e desde um  sábado até ao outro, virá toda a carne a adorar perante mim, diz o Senhor.

[[v23-66-24]]

^<<v23-66-24,24>>^ E sairão e verão os corpos mortos dos homens que prevaricaram contra mim; porque o seu bicho nunca morrerá, nem o seu fogo se apagará; e serão um horror para toda a carne.

'''

xref:023-isaias/023-isaias-065.adoc#v23-65-0[&#60; Capítulo Anterior] | <<v23-66-0,Topo>> | xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[Próximo Capítulo &#62;]