include::./index.adoc[]

[[v23-64-0]]
=== Isaías, 64
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-64-1]]

^<<v23-64-1,1>>^ OH! se fendesses os céus e  descesses! se os montes se escoassem diante da tua face!

[[v23-64-2]]

^<<v23-64-2,2>>^ Como quando o fogo inflama a lenha, e faz ferver as águas, para fazeres notório o teu nome aos teus adversários, assim  as nações tremessem da tua presença!

[[v23-64-3]]

^<<v23-64-3,3>>^ Quando fazias cousas terríveis, que não esperávamos, descias, e  os montes se escoavam diante da tua face.

[[v23-64-4]]

^<<v23-64-4,4>>^ Porque desde a antiguidade não se ouviu, nem com ouvidos se percebeu, nem com os olhos se viu um Deus além de ti, que trabalhe para aquele que nele espera.

[[v23-64-5]]

^<<v23-64-5,5>>^ Saíste ao encontro daquele que se alegrava e praticava justiça, daqueles que  se lembram de ti nos teus caminhos: eis que te iraste, porque pecamos; neles há eternidade, para que sejamos salvos.

[[v23-64-6]]

^<<v23-64-6,6>>^ Mas todos nós somos como o imundo, e todas as nossas justiças como trapo da imundícia; e todos nós caímos como a folha, e as nossas culpas como um vento nos arrebatam.

[[v23-64-7]]

^<<v23-64-7,7>>^ E já ninguém há  que invoque o teu nome, que desperte, e te detenha; porque escondes de nós o teu rosto, e nos fazes derreter, por causa das nossas iniquidades.

[[v23-64-8]]

^<<v23-64-8,8>>^ Mas agora, ó Senhor, tu és  nosso Pai: nós o barro, e tu o nosso oleiro; e todos nós obra das tuas mãos.

[[v23-64-9]]

^<<v23-64-9,9>>^ Não te enfureças tanto, ó Senhor, nem perpetuamente te lembres da iniquidade: eis, olha, nós te pedimos, todos nós somos o teu povo.

[[v23-64-10]]

^<<v23-64-10,10>>^ As tuas santas cidades estão feitas um deserto: Sião está feita um deserto, Jerusalém está assolada.

[[v23-64-11]]

^<<v23-64-11,11>>^ A nossa santa e gloriosa casa, em que te louvavam nossos pais, foi queimada a fogo; e todas as nossas cousas mais aprazíveis se tornaram em assolação.

[[v23-64-12]]

^<<v23-64-12,12>>^ Conter-te-ias tu ainda  sobre estas calamidades, ó Senhor? ficarias calado, e nos afligirias tanto?

'''

xref:023-isaias/023-isaias-063.adoc#v23-63-0[&#60; Capítulo Anterior] | <<v23-64-0,Topo>> | xref:023-isaias/023-isaias-065.adoc#v23-65-0[Próximo Capítulo &#62;]