include::./index.adoc[]

[[v23-22-0]]
=== Isaías, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-22-1]]

^<<v23-22-1,1>>^ PESO do vale da visão. Que tens agora, para que assim totalmente subisses aos telhados?

[[v23-22-2]]

^<<v23-22-2,2>>^ Cidade cheia de aclamações, cidade turbulenta, cidade que salta de alegria, os teus mortos não são mortos à espada, nem morreram na guerra.

[[v23-22-3]]

^<<v23-22-3,3>>^ Todos os teus príncipes juntamente fugiram, foram ligados pelos archeiros: todos os que em ti se acharam, foram amarrados juntamente e fugiram para longe.

[[v23-22-4]]

^<<v23-22-4,4>>^ Portanto digo: Desviai de mim a vista, e  chorarei amargamente: não vos  canseis mais em consolar-me pela destruição da filha do meu povo.

[[v23-22-5]]

^<<v23-22-5,5>>^ Porque dia de alvoroço, e de vexame, e de confusão é  este da parte do Senhor Jeová dos Exércitos, no vale da visão: um derribar de muros, e um clamor até às montanhas.

[[v23-22-6]]

^<<v23-22-6,6>>^ Porque Elão tomou a aljava, com carros de homens e cavaleiros: e Quir descobre os escudos.

[[v23-22-7]]

^<<v23-22-7,7>>^ E será que os teus mais formosos vales se encherão de carros, e os cavaleiros se porão em ordem às portas.

[[v23-22-8]]

^<<v23-22-8,8>>^ E se tirará a cobertura de Judá, e naquele dia olharás para as armas da casa do bosque.

[[v23-22-9]]

^<<v23-22-9,9>>^ E vereis as brechas da cidade de Davi, porquanto são muitas, e ajuntareis as águas do viveiro inferior.

[[v23-22-10]]

^<<v23-22-10,10>>^ Também contareis as casas de Jerusalém, e derribareis as casas, para fortalecer os muros.

[[v23-22-11]]

^<<v23-22-11,11>>^ Fizestes também um reservatório entre os dois muros para as águas do viveiro velho, mas não olhastes para cima, para o que o tinha feito, nem considerastes o que o formou desde a antiguidade.

[[v23-22-12]]

^<<v23-22-12,12>>^ E o Senhor, o Senhor dos Exércitos vos convidará naquele dia ao choro, e ao pranto, e à rapadura da cabeça, e ao cingidouro do saco.

[[v23-22-13]]

^<<v23-22-13,13>>^ Mas eis aqui gozo e alegria, matam-se vacas e degolam-se ovelhas, come-se carne, e bebe-se vinho, e diz-se : Comamos e bebamos, porque amanhã morreremos.

[[v23-22-14]]

^<<v23-22-14,14>>^ Mas o Senhor dos Exércitos se declarou aos meus ouvidos, dizendo.  Certamente esta maldade não será expiada até que morrais, diz o Senhor Jeová dos Exércitos.

[[v23-22-15]]

^<<v23-22-15,15>>^ Assim diz o Senhor Jeová dos Exércitos: Anda, vai ter com este tesoureiro, com Sebna, o mordomo, e dize-lhe :

[[v23-22-16]]

^<<v23-22-16,16>>^ Que é que tens aqui? ou a quem tens tu aqui, para que cavasses aqui uma sepultura? Cavando em lugar alto a sua sepultura, cinzelando na rocha uma  morada para si mesmo!

[[v23-22-17]]

^<<v23-22-17,17>>^ Eis que o Senhor te arrojará violentamente como um homem forte, e de todo te envolverá.

[[v23-22-18]]

^<<v23-22-18,18>>^ Certamente te fará rolar, como se faz rolar uma bola em terra larga e  espaçosa: ali morrerás, e ali acabarão  os carros da tua glória, o opróbrio da casa do teu Senhor.

[[v23-22-19]]

^<<v23-22-19,19>>^ E demitir-te-ei do teu ofício e te arrancarei do teu assento.

[[v23-22-20]]

^<<v23-22-20,20>>^ E será naquele dia que chamarei a meu servo Eliaquim, filho de Hilquias,

[[v23-22-21]]

^<<v23-22-21,21>>^ E revesti-lo-ei da tua túnica, e esforçá-lo-ei com o teu talabarte, e entregarei nas suas mãos o teu domínio, e será como pai para os moradores de Jerusalém, e para a casa de Judá.

[[v23-22-22]]

^<<v23-22-22,22>>^ E porei a chave da casa de Davi sobre o seu ombro, e abrirá, e ninguém fechará, e fechará, e ninguém abrirá.

[[v23-22-23]]

^<<v23-22-23,23>>^ E fixá-lo-ei como  a um prego num lugar firme e será como um  trono de honra para a casa de seu pai.

[[v23-22-24]]

^<<v23-22-24,24>>^ E dele penderá toda a glória da casa de seu pai, os renovos e os descendentes, todos os vasos menores, desde as taças até às garrafas.

[[v23-22-25]]

^<<v23-22-25,25>>^ Naquele dia, diz o Senhor dos Exércitos, o prego pregado em lugar firme será tirado: será arrancado, e cairá, e a carga que nele estava se desprenderá, porque o Senhor o disse.

'''

xref:023-isaias/023-isaias-021.adoc#v23-21-0[&#60; Capítulo Anterior] | <<v23-22-0,Topo>> | xref:023-isaias/023-isaias-023.adoc#v23-23-0[Próximo Capítulo &#62;]