include::./index.adoc[]

[[v23-10-0]]
=== Isaías, 10
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-10-1]]

^<<v23-10-1,1>>^ AI dos que decretam leis injustas, e dos escrivães que escrevem perversidades,

[[v23-10-2]]

^<<v23-10-2,2>>^ Para prejudicarem os pobres em juízo, e para arrebatarem o direito dos aflitos do meu povo; para despojarem as viúvas e para roubarem os órfãos!

[[v23-10-3]]

^<<v23-10-3,3>>^ Mas que fareis vós outros no dia da visitação, e da assolação, que  há de vir de longe? a quem recorrereis para obter socorro, e onde deixareis a vossa glória,

[[v23-10-4]]

^<<v23-10-4,4>>^ Sem que cada um se abata entre os presos, e caia entre os mortos? Com tudo isto a sua ira não se apartou, mas ainda está  estendida a sua mão.

[[v23-10-5]]

^<<v23-10-5,5>>^ Ai da Assíria! a vara da minha ira: porque a minha indignação é como bordão nas suas mãos.

[[v23-10-6]]

^<<v23-10-6,6>>^ Enviá-lo-ei contra uma nação hipócrita, e contra o povo do meu furor lhe darei ordem, para que lhe  roube a presa, e lhe tome o despojo, e o ponha para ser pisado aos pés, como a lama das ruas:

[[v23-10-7]]

^<<v23-10-7,7>>^ Ainda que ele não cuide assim, nem o seu coração assim o imagine: antes no seu coração intenta destruir e desarraigar não poucas nações.

[[v23-10-8]]

^<<v23-10-8,8>>^ Porque diz: Não são meus príncipes todos eles reis?

[[v23-10-9]]

^<<v23-10-9,9>>^ Não é  Calno como Carquêmis? não é Hamate como Arpade? e Samaria como Damasco?

[[v23-10-10]]

^<<v23-10-10,10>>^ A minha mão alcançou os reinos dos ídolos, ainda que as suas imagens de escultura eram melhores do que as  de Jerusalém e do que as  de Samaria.

[[v23-10-11]]

^<<v23-10-11,11>>^ Porventura  como fiz a Samaria e aos seus ídolos, não o faria igualmente a Jerusalém e aos seus ídolos?

[[v23-10-12]]

^<<v23-10-12,12>>^ Por isso acontecerá que, havendo o Senhor acabado toda a sua obra no monte de Sião e em Jerusalém, então visitarei o fruto do arrogante coração do rei da Assíria e a pompa da altivez dos seus olhos.

[[v23-10-13]]

^<<v23-10-13,13>>^ Porquanto disse: Com a força da minha mão fiz isto, e com a minha sabedoria, porque sou entendido: eu removi os limites dos povos, e roubei os seus tesouros, e como valente abati aos que se sentavam sobre tronos.

[[v23-10-14]]

^<<v23-10-14,14>>^ E achou a minha mão as riquezas dos povos como a um  ninho, e como se ajuntam os ovos abandonados, assim  eu ajuntei toda a terra: e não houve quem movesse a asa, ou abrisse a boca, ou murmurasse.

[[v23-10-15]]

^<<v23-10-15,15>>^ Porventura  gloriar-se-á o machado contra o  que corta com ele? ou presumirá a serra contra o que puxa por ela? como se o bordão movesse aos que o levantam, ou a vara levantasse o que não é pau!

[[v23-10-16]]

^<<v23-10-16,16>>^ Pelo que o Senhor, o Senhor dos Exércitos, fará definhar os que entre eles são gordos, e debaixo da sua glória ateará um incêndio, como incêndio de fogo.

[[v23-10-17]]

^<<v23-10-17,17>>^ Porque a Luz de Israel virá a ser como fogo e o seu Santo como labareda, que abrase e consuma os seus espinheiros e as suas sarças num dia.

[[v23-10-18]]

^<<v23-10-18,18>>^ Também consumirá a glória da sua floresta, e do seu campo fértil desde a alma até ao corpo: e será como quando desmaia o porta-bandeira.

[[v23-10-19]]

^<<v23-10-19,19>>^ E o resto das árvores da sua floresta será tão  pouco que um menino as poderá contar.

[[v23-10-20]]

^<<v23-10-20,20>>^ E acontecerá naquele dia que os resíduos de Israel, e os escapados da casa de Jacó, nunca mais se estribarão sobre o que os feriu: antes se estribarão sobre o Senhor, o Santo de Israel, em verdade.

[[v23-10-21]]

^<<v23-10-21,21>>^ Os resíduos se converterão, sim, os resíduos de Jacó, ao Deus forte.

[[v23-10-22]]

^<<v23-10-22,22>>^ Porque ainda que o teu povo, ó Israel, seja como a areia do mar, só  um resto dele se converterá: uma destruição está determinada, trasbordando de justiça.

[[v23-10-23]]

^<<v23-10-23,23>>^ Porque determinada já a destruição, o Senhor Jeová dos Exércitos a executará no meio de toda esta terra.

[[v23-10-24]]

^<<v23-10-24,24>>^ Pelo que assim diz o Senhor Jeová dos Exércitos: Não temas, povo meu, que habitas em Sião, a Assíria, quando te ferir com a vara, e contra ti levantar o seu bordão à maneira dos egípcios;

[[v23-10-25]]

^<<v23-10-25,25>>^ Porque daqui a bem pouco se cumprirá a minha  indignação, e a minha ira, para os consumir.

[[v23-10-26]]

^<<v23-10-26,26>>^ Porque o Senhor dos Exércitos suscitará contra ele um flagelo, como a matança de Midiã junto à rocha de Orebe, e como a sua vara sobre o mar, que contra ele se levantará, como sucedeu aos egípcios.

[[v23-10-27]]

^<<v23-10-27,27>>^ E acontecerá naquele dia, que a sua carga será tirada do teu ombro, e o seu jugo do teu pescoço: e o jugo será despedaçado por causa da unção.

[[v23-10-28]]

^<<v23-10-28,28>>^ Já  vem chegando  a Aiate, já  vai passando por Migrom, e  em Micmas lança a sua bagagem.

[[v23-10-29]]

^<<v23-10-29,29>>^ Já  vão passando, já  se alojam em Geba; já  Ramá treme, e  Gibeá de Saul vai fugindo.

[[v23-10-30]]

^<<v23-10-30,30>>^ Clama alto com a tua voz, ó filha de Galim! ouve ó Laís! ó tu pobre Anatote!

[[v23-10-31]]

^<<v23-10-31,31>>^ Já  Madmena se foi; os moradores de Gebim vão fugindo em bandos.

[[v23-10-32]]

^<<v23-10-32,32>>^ Neste mesmo dia parará em Nobe: acenará com a sua mão ao monte da filha de Sião, o outeiro de Jerusalém.

[[v23-10-33]]

^<<v23-10-33,33>>^ Mas eis que o Senhor Jeová dos Exércitos desbastará os ramos com violência, e os de alta estatura serão cortados, e os altivos serão abatidos.

[[v23-10-34]]

^<<v23-10-34,34>>^ E cortará com o ferro a espessura da floresta, e o Líbano cairá pela mão de um poderoso.

'''

xref:023-isaias/023-isaias-009.adoc#v23-9-0[&#60; Capítulo Anterior] | <<v23-10-0,Topo>> | xref:023-isaias/023-isaias-011.adoc#v23-11-0[Próximo Capítulo &#62;]