include::./index.adoc[]

[[v23-5-0]]
=== Isaías, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-5-1]]

^<<v23-5-1,1>>^ AGORA cantarei ao meu amado o cântico do meu querido a respeito da sua vinha. O meu amado tem uma vinha num outeiro fértil.

[[v23-5-2]]

^<<v23-5-2,2>>^ E a cercou, e a limpou das pedras, e a plantou de excelentes vides; e edificou no meio dela uma torre, e também construiu nela um lagar; e esperava que desse uvas, mas deu uvas bravas.

[[v23-5-3]]

^<<v23-5-3,3>>^ Agora pois, ó moradores de Jerusalém, e homens de Judá julgai, vos peço, entre mim e a minha vinha.

[[v23-5-4]]

^<<v23-5-4,4>>^ Que mais se podia fazer à minha vinha, que eu lhe não tenha feito? e como, esperando eu que desse uvas, veio a produzir uvas bravas?

[[v23-5-5]]

^<<v23-5-5,5>>^ Agora pois vos farei saber o que eu hei de fazer à minha vinha: tirarei a sua sebe, para que sirva de pasto; derribarei a sua parede, para que seja pisada;

[[v23-5-6]]

^<<v23-5-6,6>>^ E a tornarei em deserto; não será podada nem cavada; mas crescerão nela  sarças e espinheiros; e às nuvens darei ordem que não derramem chuva sobre ela.

[[v23-5-7]]

^<<v23-5-7,7>>^ Porque a vinha do Senhor dos Exércitos é  a casa de Israel, e os homens de Judá são  a planta das suas delícias: e esperou que  exercessem juízo, e eis aqui opressão; justiça, e eis aqui clamor.

[[v23-5-8]]

^<<v23-5-8,8>>^ Ai dos que ajuntam casa a casa, reúnem herdade a herdade, até que não haja mais lugar, e fiquem como únicos moradores no meio da terra!

[[v23-5-9]]

^<<v23-5-9,9>>^ A meus ouvidos disse  o Senhor dos Exércitos: Em verdade que muitas casas ficarão desertas, e até as grandes e excelentes sem moradores.

[[v23-5-10]]

^<<v23-5-10,10>>^ E dez jeiras de vinha não darão mais do que um bato: e um ômer de semente não dará mais do que um efa.

[[v23-5-11]]

^<<v23-5-11,11>>^ Ai dos que se levantam pela manhã, e seguem a bebedice; e  se demoram até à noite, até que  o vinho os esquenta!

[[v23-5-12]]

^<<v23-5-12,12>>^ E harpas e alaúdes, tamboris e pífanos, e vinho há nos seus banquetes; e não olham para a obra do Senhor, nem consideram as obras das suas mãos.

[[v23-5-13]]

^<<v23-5-13,13>>^ Portanto o meu povo será levado cativo, por falta de entendimento; e os seus nobres terão fome, e a sua multidão se secará de sede.

[[v23-5-14]]

^<<v23-5-14,14>>^ Por isso a sepultura aumentou o seu apetite, e abriu a sua boca desmesuradamente; e a glória deles, e a sua multidão, e a sua pompa, e os que entre eles folgavam, a ela desceram.

[[v23-5-15]]

^<<v23-5-15,15>>^ Então o plebeu se abaterá, e o nobre se humilhará; e os olhos dos altivos se humilharão.

[[v23-5-16]]

^<<v23-5-16,16>>^ Mas o Senhor dos Exércitos será exaltado em juízo, e Deus, o Santo, será santificado em justiça.

[[v23-5-17]]

^<<v23-5-17,17>>^ Então os cordeiros se pascerão como em pastios seus; e os lugares pisados pelos gordos servirão de alimento a forasteiros.

[[v23-5-18]]

^<<v23-5-18,18>>^ Ai dos que puxam pela iniquidade com cordas de vaidade, e pelo pecado como se fosse com  cordas de carros!

[[v23-5-19]]

^<<v23-5-19,19>>^ E dizem: Avie-se, e acabe a sua obra, para que a vejamos; e aproxime-se e venha o conselho do Santo de Israel, para que o conheçamos.

[[v23-5-20]]

^<<v23-5-20,20>>^ Ai dos que ao mal chamam bem, e ao bem mal: que fazem da escuridade luz, e da luz escuridade; e fazem do amargo doce, e do doce amargo!

[[v23-5-21]]

^<<v23-5-21,21>>^ Ai dos que são sábios a seus próprios  olhos, e prudentes diante de si mesmos!

[[v23-5-22]]

^<<v23-5-22,22>>^ Ai dos que são poderosos para beber vinho, e homens forçosos para misturar bebida forte:

[[v23-5-23]]

^<<v23-5-23,23>>^ Dos que justificam o ímpio por presentes, e ao justo negam justiça!

[[v23-5-24]]

^<<v23-5-24,24>>^ Pelo que, como a língua de fogo consome a estopa, e a palha se desfaz pela chama, assim  será a sua raiz, como podridão, e a sua flor se esvaecerá como pó; porquanto rejeitaram a lei do Senhor dos Exércitos, e desprezaram a palavra do Santo de Israel.

[[v23-5-25]]

^<<v23-5-25,25>>^ Pelo que se acendeu a ira do Senhor contra o seu povo, e estendeu a sua mão contra ele, e o feriu; e as montanhas tremeram, e os seus cadáveres eram como monturo no meio das ruas: com tudo isto não tornou atrás a sua ira, mas ainda está  alçada a sua mão.

[[v23-5-26]]

^<<v23-5-26,26>>^ E ele arvorará o estandarte ante as nações de longe, e lhes assobiará desde a extremidade da terra: e eis que virão apressadamente.

[[v23-5-27]]

^<<v23-5-27,27>>^ Não haverá  entre eles cansado, nem claudicante; ninguém tosquenejará nem dormirá: não se lhe desatará o cinto dos seus lombos, nem se lhe quebrará a correia dos seus sapatos.

[[v23-5-28]]

^<<v23-5-28,28>>^ As suas frechas serão  agudas, e todos os seus arcos retesados: as unhas dos seus cavalos dir-se-iam de pederneira, e as rodas dos seus carros  um redemoinho.

[[v23-5-29]]

^<<v23-5-29,29>>^ O seu rugido será  como o do leão; rugirão como filhos de leão; sim, rugirão e arrebatarão a presa, e a  levarão, e não haverá quem a livre.

[[v23-5-30]]

^<<v23-5-30,30>>^ E bramarão contra eles naquele dia, como o bramido do mar: e se alguém olhar para a terra, eis que só verá trevas e  ânsia, e a luz se escurecerá em suas assolações.

'''

xref:023-isaias/023-isaias-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaias/023-isaias-006.adoc#v23-6-0[Próximo Capítulo &#62;]