include::./index.adoc[]

[[v23-42-0]]
=== Isaías, 42
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-42-1]]

^<<v23-42-1,1>>^ EIS aqui o meu Servo, a quem sustenho, o meu Eleito, em quem  se compraz a minha alma; pus o meu espírito sobre ele; juízo produzirá entre os gentios.

[[v23-42-2]]

^<<v23-42-2,2>>^ Não clamará, não se exaltará, nem fará ouvir a sua voz na praça.

[[v23-42-3]]

^<<v23-42-3,3>>^ A cana trilhada não quebrará, nem apagará o pavio que fumega: em verdade produzirá o juízo;

[[v23-42-4]]

^<<v23-42-4,4>>^ Não faltará nem será quebrantado, até que ponha na terra o juízo: e as ilhas aguardarão a sua doutrina.

[[v23-42-5]]

^<<v23-42-5,5>>^ Assim diz Deus, o Senhor, que criou os céus, e os estendeu, e formou a terra, e a tudo quanto produz: que dá a respiração ao povo que  nela está, e o espírito aos que andam nela.

[[v23-42-6]]

^<<v23-42-6,6>>^ Eu o Senhor te chamarei em justiça, e te tomarei pela mão e te guardarei, e te darei por concerto do povo, e para luz dos gentios;

[[v23-42-7]]

^<<v23-42-7,7>>^ Para abrir os olhos dos cegos, para tirar da prisão os presos, e do cárcere os que jazem em  trevas.

[[v23-42-8]]

^<<v23-42-8,8>>^ Eu sou  o Senhor; este é  o meu nome; a minha glória pois a outrem não darei, nem o meu louvor às imagens de escultura.

[[v23-42-9]]

^<<v23-42-9,9>>^ Eis que as primeiras cousas passaram, e novas cousas eu vos  anuncio, e, antes que venham à luz, vo-las faço ouvir.

[[v23-42-10]]

^<<v23-42-10,10>>^ Cantai ao Senhor um cântico novo, e o seu louvor desde o fim da terra: vós os que navegais pelo mar, e tudo quanto há nele; vós, ilhas, e seus habitadores.

[[v23-42-11]]

^<<v23-42-11,11>>^ Alcem a voz  o deserto e as suas cidades, com as aldeias que  Quedar habita: exultem os que habitam nas rochas, e  clamem do cume dos montes.

[[v23-42-12]]

^<<v23-42-12,12>>^ Deem glória ao Senhor, e anunciem o seu louvor nas ilhas.

[[v23-42-13]]

^<<v23-42-13,13>>^ O Senhor como poderoso sairá, como homem de guerra despertará o zelo: clamará, e fará grande ruído, e  sujeitará os seus inimigos.

[[v23-42-14]]

^<<v23-42-14,14>>^ Por muito tempo me calei, estive em silêncio, e  me contive; mas agora darei gritos como a que está de parto, e a todos  assolarei e juntamente devorarei.

[[v23-42-15]]

^<<v23-42-15,15>>^ Os montes e outeiros tornarei em deserto, e toda a sua erva farei secar, e tornarei os rios em ilhas e as lagoas secarei.

[[v23-42-16]]

^<<v23-42-16,16>>^ E guiarei os cegos por um caminho que  nunca conheceram, fá-los-ei caminhar por veredas que  não conheceram; tornarei as trevas em luz perante eles, e as cousas tortas farei  direitas. Essas cousas lhes farei, e nunca os desampararei.

[[v23-42-17]]

^<<v23-42-17,17>>^ Tornarão atrás e  confundir-se-ão de vergonha os que confiam em imagens de escultura, e dizem às imagens de fundição: Vós sois  nossos deuses.

[[v23-42-18]]

^<<v23-42-18,18>>^ Surdos, ouvi, e vós, cegos, olhai, para que possais ver.

[[v23-42-19]]

^<<v23-42-19,19>>^ Quem é  cego, senão o meu servo, ou surdo como o meu mensageiro, a quem  envio? e quem é cego como o galardoado, e cego como o servo do Senhor?

[[v23-42-20]]

^<<v23-42-20,20>>^ Tu vês muitas cousas, mas não as guardas: ainda que tenha os ouvidos abertos, nada ouve.

[[v23-42-21]]

^<<v23-42-21,21>>^ O Senhor se agradava dele por amor da sua justiça: engrandeceu-o pela  lei, e o  fez glorioso.

[[v23-42-22]]

^<<v23-42-22,22>>^ Mas este é um  povo roubado e saqueado: todos estão  enlaçados em cavernas, e escondidos nas casas dos cárceres: são postos por presa, e ninguém há que os livre; por despojo, e ninguém diz: Restitui.

[[v23-42-23]]

^<<v23-42-23,23>>^ Quem há entre vós que ouça isto? que  atenda e ouça o que há de ser depois?

[[v23-42-24]]

^<<v23-42-24,24>>^ Quem entregou Jacó por despojo, e Israel aos roubadores? porventura  não foi o Senhor, aquele contra quem pecaram, e nos caminhos do qual não queriam andar, não dando ouvidos à sua lei?

[[v23-42-25]]

^<<v23-42-25,25>>^ Pelo que derramou sobre eles a indignação da sua ira, e a força da guerra, e lhes pôs labaredas em redor, mas nisso  não atentaram; e os queimou, mas não puseram nisso  o coração.

'''

xref:023-isaias/023-isaias-041.adoc#v23-41-0[&#60; Capítulo Anterior] | <<v23-42-0,Topo>> | xref:023-isaias/023-isaias-043.adoc#v23-43-0[Próximo Capítulo &#62;]