include::./index.adoc[]

[[v23-55-0]]
=== Isaías, 55
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-55-1]]

^<<v23-55-1,1>>^ Ó VÓS, todos os que tendes sede, vinde às águas, e os que não tendes dinheiro, vinde, comprai, e comei; sim, vinde e comprai, sem dinheiro e sem preço, vinho e leite.

[[v23-55-2]]

^<<v23-55-2,2>>^ Por que gastais o dinheiro naquilo que não é pão? e o produto  do vosso trabalho naquilo que não pode satisfazer? ouvi-me atentamente, e comei o que é bom e a vossa alma se deleite com a gordura.

[[v23-55-3]]

^<<v23-55-3,3>>^ Inclinai os vossos ouvidos, e vinde a mim; ouvi, e a vossa alma viverá; porque convosco farei um  concerto perpétuo, dando-vos  as firmes beneficências de Davi.

[[v23-55-4]]

^<<v23-55-4,4>>^ Eis que eu o dei como testemunha aos povos, como príncipe e governador dos povos.

[[v23-55-5]]

^<<v23-55-5,5>>^ Eis que chamarás a uma  nação que não conheces, e uma  nação que nunca te conheceu correrá para ti, por amor do Senhor teu Deus, e do Santo de Israel; porque ele te glorificou.

[[v23-55-6]]

^<<v23-55-6,6>>^ Buscai ao Senhor enquanto se pode achar, invocai-o enquanto está perto.

[[v23-55-7]]

^<<v23-55-7,7>>^ Deixe o ímpio o seu caminho, e o homem maligno os seus pensamentos, e se converta ao Senhor, que se compadecerá dele; torne para o nosso Deus, porque grandioso é em perdoar.

[[v23-55-8]]

^<<v23-55-8,8>>^ Porque os meus pensamentos não são os vossos pensamentos, nem os vossos caminhos os meus caminhos, diz o Senhor.

[[v23-55-9]]

^<<v23-55-9,9>>^ Porque, assim como  os céus são mais altos do que a terra, assim são os meus caminhos mais altos do que os vossos caminhos, e os meus pensamentos mais altos do que os vossos pensamentos.

[[v23-55-10]]

^<<v23-55-10,10>>^ Porque, assim como desce a chuva e a neve dos céus, e para lá não torna, mas rega a terra, e a faz produzir, e brotar, e dar semente ao semeador, e pão ao que come,

[[v23-55-11]]

^<<v23-55-11,11>>^ Assim será a palavra que sair da minha boca: ela não voltará para mim vazia, antes fará o que me apraz, e prosperará naquilo para que a enviei.

[[v23-55-12]]

^<<v23-55-12,12>>^ Porque com alegria saireis, e em paz sereis guiados: os montes e os outeiros exclamarão de prazer perante a vossa face, e todas as árvores do campo baterão as palmas.

[[v23-55-13]]

^<<v23-55-13,13>>^ Em lugar do espinheiro crescerá a faia, e em lugar da sarça crescerá a murta: o que será para o Senhor por nome, por sinal eterno, que  nunca se apagará.

'''

xref:023-isaias/023-isaias-054.adoc#v23-54-0[&#60; Capítulo Anterior] | <<v23-55-0,Topo>> | xref:023-isaias/023-isaias-056.adoc#v23-56-0[Próximo Capítulo &#62;]