include::./index.adoc[]

[[v23-19-0]]
=== Isaías, 19
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-19-1]]

^<<v23-19-1,1>>^ PESO do Egito. Eis que o Senhor vem cavalgando numa nuvem ligeira, e virá ao Egito: e os ídolos do Egito serão movidos perante a sua face, e o coração dos egípcios se derreterá no meio deles.

[[v23-19-2]]

^<<v23-19-2,2>>^ Porque farei com que os egípcios se levantem contra os egípcios, e cada um pelejará contra o seu irmão, e cada um contra o seu próximo, cidade contra cidade, reino contra reino.

[[v23-19-3]]

^<<v23-19-3,3>>^ E o espírito dos egípcios se esvaecerá dentro deles; eu destruirei o seu conselho: e eles consultarão os seus  ídolos, e encantadores, e adivinhos e mágicos.

[[v23-19-4]]

^<<v23-19-4,4>>^ E entregarei os egípcios nas mãos de um senhor duro, e um rei rigoroso os dominará, diz o Senhor, o Senhor dos Exércitos.

[[v23-19-5]]

^<<v23-19-5,5>>^ E faltarão as águas do mar, e o rio se esgotará e secará.

[[v23-19-6]]

^<<v23-19-6,6>>^ Também os rios apodrecerão e  se esgotarão e secarão os canais do Egito: as canas e os juncos se murcharão.

[[v23-19-7]]

^<<v23-19-7,7>>^ A relva que está junto ao rio, junto às ribanceiras dos rios, e tudo o que foi semeado junto ao rio, se secará, será arrancado, e não subsistirá.

[[v23-19-8]]

^<<v23-19-8,8>>^ E os pescadores gemerão, e suspirarão todos os que lançam anzol ao rio, e os que estendem rede sobre as águas desfalecerão.

[[v23-19-9]]

^<<v23-19-9,9>>^ E envergonhar-se-ão os que trabalham em linho fino, e os que tecem pano branco.

[[v23-19-10]]

^<<v23-19-10,10>>^ E os seus fundamentos serão despedaçados, e todos os que trabalham por salário ficarão com tristeza na alma.

[[v23-19-11]]

^<<v23-19-11,11>>^ Na verdade loucos são  os príncipes de Zoã; o conselho dos sábios conselheiros de Faraó se embruteceu: como pois a Faraó direis: Sou  filho de sábios, filho de antigos reis?

[[v23-19-12]]

^<<v23-19-12,12>>^ Onde estão  agora os teus sábios? anunciem-te agora, ou informem-te do que o Senhor dos Exércitos determinou contra o Egito.

[[v23-19-13]]

^<<v23-19-13,13>>^ Loucos se tornaram os príncipes de Zoã, enganados estão os príncipes de Nofe: eles farão errar o Egito, eles que são a pedra de esquina das suas tribos.

[[v23-19-14]]

^<<v23-19-14,14>>^ O Senhor derramou no meio deles um  perverso espírito; e eles fizeram errar o Egito com toda a sua obra, como o bêbedo quando  se revolve no seu vômito.

[[v23-19-15]]

^<<v23-19-15,15>>^ E não aproveitará ao Egito obra alguma que possa fazer a cabeça, a cauda, o ramo, ou o junco.

[[v23-19-16]]

^<<v23-19-16,16>>^ Naquele tempo os egípcios serão como mulheres, e tremerão e temerão por causa do movimento da mão do Senhor dos Exércitos, porque ela se há de mover contra eles.

[[v23-19-17]]

^<<v23-19-17,17>>^ E a terra de Judá será um  espanto para o Egito; todo aquele a quem isso se anunciar se assombrará, por causa do propósito do Senhor dos Exércitos, do que determinou contra eles.

[[v23-19-18]]

^<<v23-19-18,18>>^ Naquele tempo haverá cinco cidades na terra do Egito que falarão a língua de Canaã e farão juramento ao Senhor dos Exércitos; e uma se chamará: Cidade de destruição.

[[v23-19-19]]

^<<v23-19-19,19>>^ Naquele tempo o Senhor terá um  altar no meio da terra do Egito, e um  monumento se erigirá ao Senhor, na sua fronteira.

[[v23-19-20]]

^<<v23-19-20,20>>^ E servirá de sinal e de testemunho ao Senhor dos Exércitos na terra do Egito, porque ao Senhor clamarão por causa dos opressores, e ele lhes enviará um  Redentor e um Protetor, que os livrará.

[[v23-19-21]]

^<<v23-19-21,21>>^ E o Senhor se dará a conhecer ao Egito, e os egípcios conhecerão ao Senhor, naquele dia; sim, eles o adorarão com  sacrifícios e ofertas, e farão votos ao Senhor, e os  cumprirão.

[[v23-19-22]]

^<<v23-19-22,22>>^ E ferirá o Senhor aos egípcios, e os curará: e converter-se-ão ao Senhor, e mover-se-á às suas orações, e os curará;

[[v23-19-23]]

^<<v23-19-23,23>>^ Naquele dia haverá estrada do Egito até à Assíria, e os assírios virão ao Egito, e os egípcios irão à Assíria: e os egípcios adorarão com os assírios ao Senhor.

[[v23-19-24]]

^<<v23-19-24,24>>^ Naquele dia Israel será o terceiro com os egípcios e os assírios, uma  bênção no meio da terra.

[[v23-19-25]]

^<<v23-19-25,25>>^ Porque o Senhor dos Exércitos os abençoará, dizendo: Bendito seja  o Egito, meu povo, e a Assíria, obra de minhas mãos, e Israel, minha herança.

'''

xref:023-isaias/023-isaias-018.adoc#v23-18-0[&#60; Capítulo Anterior] | <<v23-19-0,Topo>> | xref:023-isaias/023-isaias-020.adoc#v23-20-0[Próximo Capítulo &#62;]