include::./index.adoc[]

[[v23-16-0]]
=== Isaías, 16
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v23-16-1]]

^<<v23-16-1,1>>^ ENVIAI o cordeiro ao dominador da terra, desde Sela, no deserto, até ao monte da filha de Sião.

[[v23-16-2]]

^<<v23-16-2,2>>^ Doutro modo sucederá que serão as filhas de Moabe junto aos vaus de Arnom como o pássaro vagueante, lançado fora do ninho.

[[v23-16-3]]

^<<v23-16-3,3>>^ Toma conselho, executa o juízo, põe a tua sombra no pino do meio-dia como a noite; esconde os desterrados, e  não descubras os vagueantes.

[[v23-16-4]]

^<<v23-16-4,4>>^ Habitem entre ti os meus desterrados, ó Moabe; serve-lhes de refúgio perante a face do destruidor; porque o homem violento terá fim; a destruição é  desfeita, e  os opressores são consumidos sobre a terra.

[[v23-16-5]]

^<<v23-16-5,5>>^ Porque um trono se firmará em benignidade, e sobre ele no tabernáculo de Davi se assentará em verdade um que julgue, e busque o juízo, e se apresse a fazer justiça.

[[v23-16-6]]

^<<v23-16-6,6>>^ Ouvimos da soberba de Moabe, a soberbíssima: da sua altivez, e da sua soberba, e do seu furor; a sua jactância é vã.

[[v23-16-7]]

^<<v23-16-7,7>>^ Portanto Moabe uivará por Moabe; todos uivarão: gemereis pelos fundamentos de Quir-Haresete, pois já estão  abalados.

[[v23-16-8]]

^<<v23-16-8,8>>^ Porque os campos de Hesbom enfraqueceram, e  a vinha de Sibma; os senhores das nações talaram as suas melhores plantas; vão chegando a Jazer; andam vagueando pelo deserto: os seus ramos se estenderam e já  passaram além do mar.

[[v23-16-9]]

^<<v23-16-9,9>>^ Pelo que prantearei, com o pranto de Jazer, a vinha de Sibma; regar-te-ei com as minhas lágrimas, ó Hesbom e Eleale; porque o júbilo dos teus frutos de verão e da tua sega desapareceu.

[[v23-16-10]]

^<<v23-16-10,10>>^ E fugiu o folguedo e a alegria do campo fértil, e já  nas vinhas se não canta, nem há júbilo algum; já  o pisador não pisará as uvas nos lagares. Eu fiz cessar o júbilo.

[[v23-16-11]]

^<<v23-16-11,11>>^ Pelo que minhas entranhas soam por Moabe como harpa, e o meu interior por Quir-Heres.

[[v23-16-12]]

^<<v23-16-12,12>>^ E será que , quando Moabe se apresentar, quando se cansar nos altos, e entrar no seu santuário a orar, nada alcançará.

[[v23-16-13]]

^<<v23-16-13,13>>^ Esta é a palavra que o Senhor falou no passado contra Moabe.

[[v23-16-14]]

^<<v23-16-14,14>>^ Mas agora falou o Senhor, dizendo: Dentro em três anos (tais quais os anos de jornaleiros), será envilecida a glória de Moabe, com toda a sua  grande multidão; e o resíduo será  pouco, pequeno e  impotente.

'''

xref:023-isaias/023-isaias-015.adoc#v23-15-0[&#60; Capítulo Anterior] | <<v23-16-0,Topo>> | xref:023-isaias/023-isaias-017.adoc#v23-17-0[Próximo Capítulo &#62;]