include::./index.adoc[]

[[v24-14-0]]
=== Jeremias, 14
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-14-1]]

^<<v24-14-1,1>>^ A PALAVRA do Senhor, que veio a Jeremias, a respeito da grande seca.

[[v24-14-2]]

^<<v24-14-2,2>>^ Anda chorando Judá, e as suas portas estão enfraquecidas: andam de luto até ao chão, e o clamor de Jerusalém vai subindo.

[[v24-14-3]]

^<<v24-14-3,3>>^ E os seus mais ilustres mandam os seus pequenos buscar água: vêm às cavas, e não acham água; voltam com  os seus cântaros vazios: envergonham-se e confundem-se, e cobrem as suas cabeças.

[[v24-14-4]]

^<<v24-14-4,4>>^ Por causa da terra que se fendeu, pois que não há chuva sobre a terra, os lavradores se envergonham e  cobrem as suas cabeças.

[[v24-14-5]]

^<<v24-14-5,5>>^ Porque até as cervas no campo parem, e abandonam seus filhos , porquanto não há erva.

[[v24-14-6]]

^<<v24-14-6,6>>^ E os jumentos monteses se põem nos lugares altos, sorvem o vento como os dragões; desfalecem os seus olhos, porquanto não há erva.

[[v24-14-7]]

^<<v24-14-7,7>>^ Posto que as nossas maldades testifiquem contra nós, ó Senhor, opera tu por amor do teu nome; porque as nossas rebeldias se multiplicaram; contra ti pecamos.

[[v24-14-8]]

^<<v24-14-8,8>>^ Oh! esperança de Israel, Redentor seu no tempo da angústia! porque serias como um  estrangeiro na terra? e como o  viandante que  se retira a passar a noite?

[[v24-14-9]]

^<<v24-14-9,9>>^ Porque serias como homem cansado, como valoroso que  não pode livrar? Mas tu estás  no meio de nós, ó Senhor, e nós somos chamados pelo teu nome: não nos desampares.

[[v24-14-10]]

^<<v24-14-10,10>>^ Assim diz o Senhor, acerca deste povo: Pois que  tanto amaram o afastar-se, e  não detiveram os seus pés, por isso o Senhor se não agrada deles, mas  agora se lembrará da maldade deles, e visitará os seus pecados.

[[v24-14-11]]

^<<v24-14-11,11>>^ Disse-me mais o Senhor: Não rogues por este povo para bem.

[[v24-14-12]]

^<<v24-14-12,12>>^ Quando jejuarem, não ouvirei o seu clamor, e quando oferecerem holocaustos e ofertas de manjares, não me agradarei deles; antes eu os consumirei pela espada, e pela fome e pela peste.

[[v24-14-13]]

^<<v24-14-13,13>>^ Então disse eu: Ah! Senhor, Senhor, eis que os profetas lhes dizem: Não vereis espada, e não tereis fome; antes vos darei paz verdadeira neste lugar.

[[v24-14-14]]

^<<v24-14-14,14>>^ E disse-me o Senhor: Os profetas profetizam falsamente em meu nome; nunca os enviei, nem lhes dei ordem, nem lhes falei: visão falsa, e adivinhação, e vaidade, e o engano do seu coração é o que eles vos profetizam.

[[v24-14-15]]

^<<v24-14-15,15>>^ Portanto assim diz o Senhor acerca dos profetas que profetizam em meu nome, sem que eu os tenha mandado, e dizem: Nem espada, nem fome haverá nesta terra: À espada e à fome serão consumidos esses profetas.

[[v24-14-16]]

^<<v24-14-16,16>>^ E o povo a quem eles profetizam será lançado nas ruas de Jerusalém, por causa da fome e da espada; e não haverá  quem enterre as suas mulheres, e os seus filhos e as suas filhas: assim derramarei sobre eles a sua maldade.

[[v24-14-17]]

^<<v24-14-17,17>>^ Portanto lhes dirás esta palavra: Os meus olhos derramem lágrimas de noite e de dia, e não cessem porque a virgem, filha do meu povo, está ferida de  grande ferida, de  chaga mui dolorosa.

[[v24-14-18]]

^<<v24-14-18,18>>^ Se eu saio ao campo, eis aqui os mortos à espada, e, se entro na cidade, estão ali os debilitados pela fome: e até os profetas e os sacerdotes correram em redor da terra, e não sabem nada.

[[v24-14-19]]

^<<v24-14-19,19>>^ De todo rejeitaste tu a Judá? ou  aborrece a tua alma a Sião? porque nos feriste, e não há  cura para nós? aguardamos a paz, e não aparece o bem; e o tempo da cura, e eis aqui turbação.

[[v24-14-20]]

^<<v24-14-20,20>>^ Ah! Senhor! conhecemos a nossa impiedade e  a maldade de nossos pais; porque pecamos contra ti.

[[v24-14-21]]

^<<v24-14-21,21>>^ Não nos  rejeites por amor do teu nome; não abatas o trono da tua glória; lembra-te, e não anules o teu concerto conosco.

[[v24-14-22]]

^<<v24-14-22,22>>^ Haverá, porventura , entre as vaidades dos gentios, alguma que faça chover? ou podem os céus dar chuvas? não és  tu somente, ó Senhor nosso Deus? portanto em ti esperaremos, pois tu fazes todas estas cousas.

'''

xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[&#60; Capítulo Anterior] | <<v24-14-0,Topo>> | xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[Próximo Capítulo &#62;]