include::./index.adoc[]

[[v24-4-0]]
=== Jeremias, 4
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-4-1]]

^<<v24-4-1,1>>^ SE voltares, ó Israel, diz o Senhor, para mim voltarás: e, se tirares as tuas abominações de diante de mim, não andarás mais vagueando,

[[v24-4-2]]

^<<v24-4-2,2>>^ E jurarás: Vive o Senhor na verdade, no juízo e na justiça; e nele se bendirão as gentes, e nele se gloriarão.

[[v24-4-3]]

^<<v24-4-3,3>>^ Porque assim diz o Senhor aos homens de Judá e a Jerusalém: Lavrai para vós o campo de lavoura, e não semeeis entre espinhos.

[[v24-4-4]]

^<<v24-4-4,4>>^ Circuncidai-vos para o Senhor, e tirai os prepúcios do vosso coração, ó homens de Judá e habitadores de Jerusalém, para que a minha indignação não venha a sair como fogo e arda de modo que não haja quem a  apague, por causa da malícia das vossas obras.

[[v24-4-5]]

^<<v24-4-5,5>>^ Anunciai em Judá, e fazei ouvir em Jerusalém, e dizei: Tocai a trombeta na terra! gritai em alta voz, dizendo: Ajuntai-vos, e entremos nas cidades fortes!

[[v24-4-6]]

^<<v24-4-6,6>>^ Arvorai a bandeira para Sião, fugi para salvação vossa, não pareis; porque eu trago um mal do norte, e uma grande destruição.

[[v24-4-7]]

^<<v24-4-7,7>>^ Já  um leão subiu da sua ramada, e um destruidor das nações; ele já partiu, e  saiu do seu lugar para fazer da tua terra uma desolação; a fim de que as tuas cidades sejam destruídas, e ninguém habite nelas.

[[v24-4-8]]

^<<v24-4-8,8>>^ Por isto cingi-vos de sacos, lamentai, e uivai; porque o ardor da ira do Senhor não se desviou de nós.

[[v24-4-9]]

^<<v24-4-9,9>>^ E sucederá naquele tempo, diz o Senhor, que  se desfará o coração do rei e o coração dos príncipes; e os sacerdotes pasmarão, e os profetas se maravilharão.

[[v24-4-10]]

^<<v24-4-10,10>>^ Então disse eu: Ah! Senhor Jeová ! verdadeiramente trouxeste grande ilusão a este povo e a Jerusalém, dizendo: Tereis paz; pois a espada penetra-lhe até à alma.

[[v24-4-11]]

^<<v24-4-11,11>>^ Naquele tempo se dirá a este povo e a Jerusalém: Um vento seco das alturas do deserto veio  ao caminho da filha do meu povo, não para padejar, nem para a limpar.

[[v24-4-12]]

^<<v24-4-12,12>>^ Um vento me virá a mim, de grande veemência: agora também eu pronunciarei juízos contra eles.

[[v24-4-13]]

^<<v24-4-13,13>>^ Eis que virá subindo como nuvens e os seus carros como a tormenta; os seus cavalos serão mais ligeiros do que as águias. Ai de nós! que somos assolados!

[[v24-4-14]]

^<<v24-4-14,14>>^ Lava o teu coração da malícia, ó Jerusalém, para que sejas salva; até quando permanecerão no meio de ti os teus maus pensamentos?

[[v24-4-15]]

^<<v24-4-15,15>>^ Porque uma voz anuncia desde Dã e faz ouvir a calamidade desde o monte de Efraim.

[[v24-4-16]]

^<<v24-4-16,16>>^ Proclamai isto às nações, fazei-o ouvir contra Jerusalém: que  vigias vêm de uma terra remota, e levantarão a sua voz contra as cidades de Judá.

[[v24-4-17]]

^<<v24-4-17,17>>^ Como os guardas de um campo, eles a rodeiam; porquanto ela se rebelou contra mim, diz o Senhor.

[[v24-4-18]]

^<<v24-4-18,18>>^ O teu caminho e as tuas obras te trouxeram estas cousas: esta é  a tua iniquidade, que de tão  amargosa te chega até ao coração.

[[v24-4-19]]

^<<v24-4-19,19>>^ Ah!  entranhas minhas, entranhas minhas! estou ferido no meu coração! o meu coração ruge; não me posso calar; porque tu, ó minha alma, ouviste o som da trombeta e  o alarido da guerra.

[[v24-4-20]]

^<<v24-4-20,20>>^ Quebranto sobre quebranto se apregoa: porque já toda a terra está destruída; de repente foram destruídas as minhas tendas, e  as minhas cortinas num momento.

[[v24-4-21]]

^<<v24-4-21,21>>^ Até quando verei a bandeira, e  ouvirei a voz da trombeta?

[[v24-4-22]]

^<<v24-4-22,22>>^ Deveras o meu povo está  louco, já me não conhece; são  filhos néscios, e não entendidos; sábios são  para mal fazer, mas para bem fazer nada sabem.

[[v24-4-23]]

^<<v24-4-23,23>>^ Observei a terra, e  eis que estava  assolada e vazia; e os céus, e não tinham a sua luz.

[[v24-4-24]]

^<<v24-4-24,24>>^ Observei os montes, e eis que estavam  tremendo; e todos os outeiros estremeciam.

[[v24-4-25]]

^<<v24-4-25,25>>^ Observei e vi que homem nenhum havia e que todas as aves do céu tinham fugido.

[[v24-4-26]]

^<<v24-4-26,26>>^ Vi também que a terra fértil era  um deserto, e que todas as suas cidades estavam derribadas diante do Senhor, diante do furor da sua ira.

[[v24-4-27]]

^<<v24-4-27,27>>^ Porque assim diz o Senhor: Toda esta terra será assolada: de todo, porém, a  não consumirei.

[[v24-4-28]]

^<<v24-4-28,28>>^ Por isto lamentará a terra, e  os céus em cima se enegrecerão; porquanto assim o  disse, assim o  propus, e não me arrependi nem me desviarei disso.

[[v24-4-29]]

^<<v24-4-29,29>>^ Ao clamor dos cavaleiros e dos frecheiros fugiram todas as cidades; entraram pelas nuvens, e  treparam pelos penhascos: todas as cidades ficaram  desamparadas, e já  ninguém habita nelas.

[[v24-4-30]]

^<<v24-4-30,30>>^ Agora, pois  que farás, ó assolada? ainda que te vistas de carmesim, ainda que te adornes com enfeites de ouro, ainda que te pintes em volta dos teus  olhos com o antimônio, debalde te farias bela: os amantes te desprezam, e procuram tirar-te  a vida.

[[v24-4-31]]

^<<v24-4-31,31>>^ Porquanto ouço uma voz como de mulher que está de parto, uma angústia como da que está  com dores do primeiro filho; a voz da filha de Sião, ofegante, que estende as suas mãos, dizendo : Oh! ai de mim agora! porque a minha alma desmaia diante dos assassinos.

'''

xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[&#60; Capítulo Anterior] | <<v24-4-0,Topo>> | xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[Próximo Capítulo &#62;]