include::./index.adoc[]

[[v24-32-0]]
=== Jeremias, 32
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-32-1]]

^<<v24-32-1,1>>^ A PALAVRA que veio a Jeremias da parte do Senhor, no ano décimo de Zedequias, rei de Judá; este ano foi o ano dezoito de Nabucodonosor.

[[v24-32-2]]

^<<v24-32-2,2>>^ (Cercava, porém, então o exército do rei de Babilônia a Jerusalém; e Jeremias, o profeta, estava encerrado no pátio da guarda que estava na  casa do rei de Judá;

[[v24-32-3]]

^<<v24-32-3,3>>^ Porque Zedequias, rei de Judá, o tinha encerrado, dizendo: Porque profetizas tu, dizendo: Assim diz o Senhor: Eis que entrego esta cidade na mão do rei de Babilônia, e ele a tomará;

[[v24-32-4]]

^<<v24-32-4,4>>^ E Zedequias, rei de Judá, não escapará das mãos dos caldeus: mas certamente será entregue na mão do rei de Babilônia, e com ele falará boca a boca, e os seus olhos verão os dele;

[[v24-32-5]]

^<<v24-32-5,5>>^ E ele levará Zedequias para Babilônia e ali estará, até que eu o visite, diz o Senhor, e , ainda que pelejeis contra os caldeus, não ganhareis?)

[[v24-32-6]]

^<<v24-32-6,6>>^ Disse pois Jeremias: Veio a mim a palavra do Senhor, dizendo:

[[v24-32-7]]

^<<v24-32-7,7>>^ Eis que Hananeel, filho de Salum, teu tio, virá a ti, dizendo: Compra para ti a minha herdade que está  em Anatote, pois tens o direito de resgate para comprá-la.

[[v24-32-8]]

^<<v24-32-8,8>>^ Veio pois a mim Hananeel, filho de meu tio, segundo a palavra do Senhor, ao pátio da guarda, e me disse: Compra agora a minha herdade que está  em Anatote, na terra de Benjamim; porque teu é o direito de herança e tens o resgate; compra-a para ti. Então entendi que isto  era a palavra do Senhor.

[[v24-32-9]]

^<<v24-32-9,9>>^ Comprei pois a herdade de Hananeel, filho de meu tio, a qual está  em Anatote; e pesei-lhe o dinheiro, dezessete siclos de prata.

[[v24-32-10]]

^<<v24-32-10,10>>^ E subscrevi o auto, e selei-o, e foi confirmado por testemunhas: e pesei-lhe o dinheiro numa balança.

[[v24-32-11]]

^<<v24-32-11,11>>^ E tomei o auto da compra, tanto o que estava selado, conforme  a lei e os estatutos, como o que estava aberto.

[[v24-32-12]]

^<<v24-32-12,12>>^ E dei o auto da compra a Baruque, filho de Nérias, filho de Maaseias, perante os olhos de Hananeel, filho  de meu tio, e perante os olhos das testemunhas, que subscreveram a escritura da compra, e  perante os olhos de todos os judeus que se assentavam no pátio da guarda.

[[v24-32-13]]

^<<v24-32-13,13>>^ E dei ordem a Baruque, perante os olhos deles, dizendo:

[[v24-32-14]]

^<<v24-32-14,14>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel: Toma estes autos, este auto de compra, tanto o selado, como o aberto, e mete-os num vaso de barro, para que se possam conservar muitos dias;

[[v24-32-15]]

^<<v24-32-15,15>>^ Porque assim diz o Senhor dos Exércitos, o Deus de Israel: Ainda se comprarão casas, e campos, e vinhas nesta terra.

[[v24-32-16]]

^<<v24-32-16,16>>^ E depois que dei o auto da compra a Baruque, filho de Nérias, orei ao Senhor, dizendo:

[[v24-32-17]]

^<<v24-32-17,17>>^ Ah! Senhor Jeová ! eis que tu fizeste os céus e a terra com o teu grande poder, e com o teu braço estendido: não te é maravilhosa cousa alguma:

[[v24-32-18]]

^<<v24-32-18,18>>^ Tu usas de benignidade com milhares, e tornas a maldade dos pais ao seio dos filhos depois deles: o grande, e poderoso Deus cujo nome é o Senhor dos Exércitos:

[[v24-32-19]]

^<<v24-32-19,19>>^ Grande em conselho, e magnífico em obras; porque os teus olhos estão  abertos sobre todos os caminhos dos filhos dos homens, para dar a cada um segundo os seus caminhos e segundo o fruto das suas obras:

[[v24-32-20]]

^<<v24-32-20,20>>^ Tu puseste sinais e maravilhas na terra do Egito até o dia de hoje, tanto em Israel, como entre os outros  homens, e te criaste um  nome, qual é o que tens  neste dia.

[[v24-32-21]]

^<<v24-32-21,21>>^ E tiraste o teu povo Israel da terra do Egito, com sinais e com maravilhas, e com mão forte, e com braço estendido, e com grande espanto;

[[v24-32-22]]

^<<v24-32-22,22>>^ E lhes deste esta terra, que juraste a seus pais que lhes havias de dar: terra que mana leite e mel.

[[v24-32-23]]

^<<v24-32-23,23>>^ E entraram nela , e a possuíram, mas não obedeceram à tua voz, nem andaram na tua lei; tudo o que lhes mandaste que fizessem, eles não o fizeram; pelo que ordenaste lhes sucedesse todo este mal.

[[v24-32-24]]

^<<v24-32-24,24>>^ Eis aqui os valados! já  vieram contra a cidade para tomá-la, e a cidade está dada na mão dos caldeus, que pelejam contra ela, pela espada, e pela fome, e pela pestilência; e o que disseste se cumpriu, e eis aqui o  estás presenciando.

[[v24-32-25]]

^<<v24-32-25,25>>^ Contudo tu me disseste, ó Senhor Deus: Compra para ti o campo por dinheiro, e faze que o  atestem testemunhas; embora a cidade esteja já  dada na mão dos caldeus.

[[v24-32-26]]

^<<v24-32-26,26>>^ Então veio a palavra do Senhor a Jeremias, dizendo:

[[v24-32-27]]

^<<v24-32-27,27>>^ Eis que eu sou  o Senhor, o Deus de toda a carne: seria qualquer cousa maravilhosa para mim?

[[v24-32-28]]

^<<v24-32-28,28>>^ Portanto assim diz o Senhor: Eis que eu entrego esta cidade na mão dos caldeus, e na mão de Nabucodonosor, rei de Babilônia, e tomá-la-á.

[[v24-32-29]]

^<<v24-32-29,29>>^ E os caldeus, que pelejam contra esta cidade, entrarão nela , porão fogo a esta cidade, e queimarão as casas sobre cujos terraços queimaram incenso a Baal e ofereceram libações a outros deuses, para me provocarem à ira.

[[v24-32-30]]

^<<v24-32-30,30>>^ Porque os filhos de Israel e os filhos de Judá não fizeram senão mal aos meus olhos, desde a sua mocidade; porque os filhos de Israel não fizeram senão provocar-me à ira com as obras das suas mãos, diz o Senhor.

[[v24-32-31]]

^<<v24-32-31,31>>^ Porque para minha ira e para meu furor me tem sido esta cidade, desde o dia em que a edificaram, e até ao dia de  hoje, para que a tirasse da minha presença;

[[v24-32-32]]

^<<v24-32-32,32>>^ Por toda a maldade dos filhos de Israel, e dos filhos de Judá, que fizeram, para me provocarem à ira, eles e os seus reis, os seus príncipes, os seus sacerdotes, e os seus profetas, como também os homens de Judá e os moradores de Jerusalém.

[[v24-32-33]]

^<<v24-32-33,33>>^ E viraram para mim as costas, e não o rosto: ainda que eu os ensinava, madrugando e ensinando- os  eles não deram ouvidos, para receberem o ensino.

[[v24-32-34]]

^<<v24-32-34,34>>^ Antes puseram as suas abominações na casa que se chama pelo meu nome, para a profanarem.

[[v24-32-35]]

^<<v24-32-35,35>>^ E edificaram os altos de Baal, que estão  no vale do filho de Hinom, para fazerem passar seus filhos e suas filhas pelo fogo  a Moloque; o que nunca lhes ordenei, nem subiu ao meu coração, que fizessem tal abominação; para fazerem pecar a Judá.

[[v24-32-36]]

^<<v24-32-36,36>>^ Por isso agora assim diz o Senhor, o Deus de Israel, acerca desta cidade, da qual vós dizeis: Já  está dada na mão do rei de Babilônia, pela espada, e pela fome, e pela pestilência.:

[[v24-32-37]]

^<<v24-32-37,37>>^ Eis que eu os congregarei de todas as terras, para onde os houver lançado na minha ira, e no meu furor, e na minha  grande indignação; e os tornarei a trazer a este lugar; e farei que habitem nele seguramente.

[[v24-32-38]]

^<<v24-32-38,38>>^ E eles serão o meu povo, e eu serei o seu Deus.

[[v24-32-39]]

^<<v24-32-39,39>>^ E lhes darei um mesmo  coração, e um mesmo  caminho, para que me temam todos os dias, para seu bem e bem de seus filhos, depois deles.

[[v24-32-40]]

^<<v24-32-40,40>>^ E farei com eles um concerto eterno, que não se desviará deles, para lhes fazer bem; e porei o meu temor no seu coração, para que nunca se apartem de mim.

[[v24-32-41]]

^<<v24-32-41,41>>^ E alegrar-me-ei por causa deles, fazendo-lhes bem; e os plantarei nesta terra certamente, com todo o meu coração e com toda a minha alma.

[[v24-32-42]]

^<<v24-32-42,42>>^ Porque assim diz o Senhor: Como eu trouxe sobre este povo todo este grande mal, assim eu trarei sobre ele todo o bem que lhes tenho prometido.

[[v24-32-43]]

^<<v24-32-43,43>>^ E comprar-se-ão campos nesta terra, da qual vós dizeis: Está deserta, sem homens nem animais; está dada na mão dos caldeus.

[[v24-32-44]]

^<<v24-32-44,44>>^ Comprarão campos por dinheiro, e subscreverão os autos, e os selarão, e farão que os atestem testemunhas na terra de Benjamim, e nos contornos de Jerusalém, e nas cidades de Judá, e nas cidades das montanhas e nas cidades das planícies, e nas cidades do sul; porque os  farei voltar do  seu cativeiro, diz o Senhor.

'''

xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[Próximo Capítulo &#62;]