include::./index.adoc[]

[[v24-45-0]]
=== Jeremias, 45
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-45-1]]

^<<v24-45-1,1>>^ A PALAVRA que falou Jeremias, o profeta, a Baruque, filho de Nérias, escrevendo ele aquelas palavras, num livro, da boca de Jeremias, no ano quarto de Joaquim, filho de Josias, rei de Judá, dizendo:

[[v24-45-2]]

^<<v24-45-2,2>>^ Assim diz o Senhor, Deus de Israel, acerca de ti, ó Baruque:

[[v24-45-3]]

^<<v24-45-3,3>>^ Disseste: Ai de mim agora! porque me acrescentou o Senhor tristeza à minha dor: estou cansado do meu gemido, e não acho descanso.

[[v24-45-4]]

^<<v24-45-4,4>>^ Isto lhe dirás: Assim diz o Senhor: Eis que o que edifiquei eu derribo, e o que plantei eu arranco, e isso em toda esta terra.

[[v24-45-5]]

^<<v24-45-5,5>>^ E procuras tu grandezas? não as  busques; porque eis que trarei mal sobre toda a carne, diz o Senhor; a ti, porém, darei a tua alma por despojo, em todos os lugares para onde fores.

'''

xref:024-jeremias/024-jeremias-044.adoc#v24-44-0[&#60; Capítulo Anterior] | <<v24-45-0,Topo>> | xref:024-jeremias/024-jeremias-046.adoc#v24-46-0[Próximo Capítulo &#62;]