include::./index.adoc[]

[[v24-50-0]]
=== Jeremias, 50
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-50-1]]

^<<v24-50-1,1>>^ A PALAVRA que falou o Senhor contra Babilônia, contra a terra dos caldeus, por Jeremias, o profeta.

[[v24-50-2]]

^<<v24-50-2,2>>^ Anunciai entre as nações; e fazei ouvir, e arvorai um estandarte, fazei ouvir, não encubrais; dizei: Tomada é Babilônia, confundido está Bel, atropelado está Merodaque, confundidos estão os seus ídolos, e caídos estão os seus deuses.

[[v24-50-3]]

^<<v24-50-3,3>>^ Porque subiu contra ele uma nação do norte, que fará da sua terra uma solidão, e não haverá quem habite nela: desde os homens até os animais fugiram, e se foram.

[[v24-50-4]]

^<<v24-50-4,4>>^ Naqueles dias, e naquele tempo diz o Senhor, os filhos de Israel virão, eles e os filhos de Judá juntamente; andando e chorando virão, e buscarão ao Senhor seu Deus.

[[v24-50-5]]

^<<v24-50-5,5>>^ Pelo caminho de Sião perguntarão, para ali dirigirão os seus rostos: virão, e se ajuntarão ao Senhor num concerto eterno que  nunca será esquecido.

[[v24-50-6]]

^<<v24-50-6,6>>^ Ovelhas perdidas foram o meu povo, os seus pastores as fizeram errar, para os montes as deixaram desviar; de monte em outeiro andaram, esqueceram-se do lugar de seu repouso.

[[v24-50-7]]

^<<v24-50-7,7>>^ Todos os que as achavam as devoraram; e os seus adversários diziam: Culpa nenhuma teremos: porque pecaram contra o Senhor, e a morada da justiça; sim, o Senhor, a Esperança de seus pais.

[[v24-50-8]]

^<<v24-50-8,8>>^ Fugi do meio de Babilônia, e saí da terra dos caldeus; e sede como os carneiros diante do rebanho.

[[v24-50-9]]

^<<v24-50-9,9>>^ Porque eis que eu suscitarei e farei subir contra Babilônia uma congregação de grandes nações da terra do norte, e se prepararão contra ela; dali será  tomada: as suas frechas serão  como de  valente herói; nenhuma tornará sem efeito.

[[v24-50-10]]

^<<v24-50-10,10>>^ E a Caldeia servirá de presa: todos os que a saquearem ficarão fartos, diz o Senhor;

[[v24-50-11]]

^<<v24-50-11,11>>^ Porquanto vos alegrastes, saltastes de prazer, ó saqueadores da minha herança, e vos inchastes como bezerra gorda, e rinchastes como cavalos  vigorosos.

[[v24-50-12]]

^<<v24-50-12,12>>^ Será mui confundida vossa mãe, ficará envergonhada a que vos deu à luz: eis que ela será a última das nações, um deserto, uma terra seca e uma solidão.

[[v24-50-13]]

^<<v24-50-13,13>>^ Por causa do furor do Senhor não será habitada, antes se tornará em total assolação: qualquer que passar por Babilônia se espantará, e assobiará vendo todas as suas pragas.

[[v24-50-14]]

^<<v24-50-14,14>>^ Preparai-vos para cercar Babilônia, todos os que armais arcos: atirai-lhe, não poupeis as frechas, porque pecou contra o Senhor.

[[v24-50-15]]

^<<v24-50-15,15>>^ Gritai contra ela rodeando-a; ela já se submeteu; caíram seus fundamentos, estão derribados os seus muros; porque esta é  a vingança do Senhor: vingai-vos dela; como ela fez, fazei-lhe a ela.

[[v24-50-16]]

^<<v24-50-16,16>>^ Arrancai de Babilônia o que semeia, e o que leva a foice no tempo da sega: por causa da espada aflitiva, virar-se-á cada um para o seu povo, e fugirá cada um para a sua terra.

[[v24-50-17]]

^<<v24-50-17,17>>^ Cordeiro desgarrado é  Israel: os leões o afugentaram: o primeiro a devorá-lo foi o rei da Assíria; e por último, Nabucodonosor, rei de Babilônia, lhe quebrou os ossos.

[[v24-50-18]]

^<<v24-50-18,18>>^ Portanto, assim diz o Senhor dos Exércitos, Deus de Israel: Eis que visitarei o rei de Babilônia, e a sua terra, como visitei o rei da Assíria.

[[v24-50-19]]

^<<v24-50-19,19>>^ E farei tornar Israel para a sua morada, e pastará no  Carmelo e em  Basã; e fartar-se-á a sua alma no monte de Efraim e em Gileade.

[[v24-50-20]]

^<<v24-50-20,20>>^ Naqueles dias, e naquele tempo, diz o Senhor, buscar-se-á a maldade de Israel, e não será achada; e os pecados de Judá, mas não se acharão; porque perdoarei aos que eu deixar de resto.

[[v24-50-21]]

^<<v24-50-21,21>>^ Sobe contra a terra de Merataim, sobe contra ela, e contra os moradores de Pécode; assola e inteiramente destrói tudo após eles, diz o Senhor, e faze conforme tudo o que te mandei.

[[v24-50-22]]

^<<v24-50-22,22>>^ Estrondo de batalha há na terra, e de grande destruição.

[[v24-50-23]]

^<<v24-50-23,23>>^ Como foi cortado e quebrado o martelo de toda a terra! como se tornou Babilônia em espanto entre as nações!

[[v24-50-24]]

^<<v24-50-24,24>>^ Laços te armei, e também foste presa, ó Babilônia, e tu não o  soubeste: foste achada, e também apanhada; porque contra o Senhor te entremeteste.

[[v24-50-25]]

^<<v24-50-25,25>>^ O Senhor abriu o seu tesouro, e tirou os instrumentos da sua indignação; porque o Senhor, o Senhor dos Exércitos, tem uma obra a realizar  na terra dos caldeus.

[[v24-50-26]]

^<<v24-50-26,26>>^ Vinde contra ela dos confins da terra , abri os seus celeiros, trilhai-a como a paveias, e destruí-a de todo: nada lhe fique de resto.

[[v24-50-27]]

^<<v24-50-27,27>>^ Matai à espada a todos os seus novilhos, desçam ao degoladouro: ai deles! porque veio o seu dia, o tempo da sua visitação.

[[v24-50-28]]

^<<v24-50-28,28>>^ Tal é a voz dos que fugiram e escaparam da terra de Babilônia para anunciarem em Sião a vingança do Senhor nosso Deus, a vingança do seu templo.

[[v24-50-29]]

^<<v24-50-29,29>>^ Convocai contra Babilônia os frecheiros, todos os que armam arcos: acampai-vos contra ela em redor, ninguém escape dela; pagai-lhe conforme a sua obra, conforme tudo o que fez, fazei-lhe; porque se houve arrogantemente contra o Senhor, contra o Santo de Israel.

[[v24-50-30]]

^<<v24-50-30,30>>^ Portanto, cairão os seus mancebos nas suas ruas; e todos os seus homens de guerra serão desarraigados naquele dia, diz o Senhor.

[[v24-50-31]]

^<<v24-50-31,31>>^ Eis que eu sou  contra ti, ó soberbo, diz o Senhor Deus dos Exércitos, porque veio o teu dia, o tempo em que te hei de visitar.

[[v24-50-32]]

^<<v24-50-32,32>>^ Então tropeçará o soberbo, e cairá, e ninguém haverá  que o levante; e porei fogo às suas cidades, o qual consumirá todos os seus contornos.

[[v24-50-33]]

^<<v24-50-33,33>>^ Assim diz o Senhor dos Exércitos: Os filhos de Israel e os filhos de Judá foram  oprimidos juntamente; e todos os que os levaram cativos os retiveram não os quiseram soltar.

[[v24-50-34]]

^<<v24-50-34,34>>^ Mas  o seu Redentor é forte, o Senhor dos Exércitos é  o seu nome; certamente pleiteará a causa deles, para dar descanso à terra, e inquietar os moradores de Babilônia.

[[v24-50-35]]

^<<v24-50-35,35>>^ A espada virá  sobre os caldeus, diz o Senhor, e sobre os moradores de Babilônia, e sobre os seus príncipes, sobre os seus sábios.

[[v24-50-36]]

^<<v24-50-36,36>>^ A espada, virá  sobre os mentirosos, e ficarão insensatos: a espada virá  sobre os seus valentes, e desmaiarão.

[[v24-50-37]]

^<<v24-50-37,37>>^ A espada virá  sobre os seus cavalos, e sobre os seus carros, e sobre todo o povo misto, que está  no meio dela; e eles serão como mulheres: a espada virá  sobre os seus tesouros, e serão saqueados.

[[v24-50-38]]

^<<v24-50-38,38>>^ Cairá  a seca sobre as suas águas, e secarão; porque é uma terra de imagens de escultura, e eles pelos seus ídolos andam enfurecidos.

[[v24-50-39]]

^<<v24-50-39,39>>^ Por isso habitarão nela  as feras do deserto, com os animais bravos das ilhas: também habitarão nela as avestruzes; e nunca mais será povoada, nem será habitada de geração em geração.

[[v24-50-40]]

^<<v24-50-40,40>>^ Como quando Deus transtornou a Sodoma e a Gomorra, e aos seus vizinhos, diz o Senhor; assim ninguém habitará ali, nem morará nela filho de homem.

[[v24-50-41]]

^<<v24-50-41,41>>^ Eis que um povo vem do norte, e uma grande nação, e reis poderosos se levantarão dos lados mais remotos da terra.

[[v24-50-42]]

^<<v24-50-42,42>>^ Arco e lança tomarão; eles são cruéis, e não conhecem a compaixão; a sua voz bramará como o mar e sobre cavalos cavalgarão, como um  homem, apercebido para a batalha, contra ti, ó filha de Babilônia.

[[v24-50-43]]

^<<v24-50-43,43>>^ O rei de Babilônia ouviu a fama deles, e desfaleceram as suas mãos: angústia se apoderou dele, dores, como da que está  de parto.

[[v24-50-44]]

^<<v24-50-44,44>>^ Eis que um como leão subirá da enchente do Jordão, contra a morada forte, mas num momento o farei correr dali; e ao escolhido porei contra ela: porque quem é  semelhante a mim? e quem me citaria a mim? e quem é o pastor que subsistiria perante mim?

[[v24-50-45]]

^<<v24-50-45,45>>^ Portanto ouvi o conselho que o Senhor decretou contra Babilônia, e os seus desígnios que intentou contra a terra dos caldeus: Certamente os mais pequenos do rebanho os arrastarão: certamente será assolada a morada deles.

[[v24-50-46]]

^<<v24-50-46,46>>^ Ao estrondo da tomada de Babilônia estremeceu a terra; e o grito se ouviu entre as nações.

'''

xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[&#60; Capítulo Anterior] | <<v24-50-0,Topo>> | xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[Próximo Capítulo &#62;]