include::./index.adoc[]

[[v24-5-0]]
=== Jeremias, 5
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-5-1]]

^<<v24-5-1,1>>^ DAI voltas às ruas de Jerusalém, e vede agora, e informai-vos, e buscai pelas suas praças, a ver  se achais alguém, ou se há um homem que pratique a justiça ou  busque a verdade; e eu lhe perdoarei.

[[v24-5-2]]

^<<v24-5-2,2>>^ E ainda que digam: Vive o Senhor, decerto falsamente juram.

[[v24-5-3]]

^<<v24-5-3,3>>^ Ah! Senhor, não atentam os teus olhos para a verdade? feriste-os, e não lhes doeu: consumiste-os, e  não quiseram receber a correção: endureceram as suas faces mais do que uma rocha; não quiseram voltar.

[[v24-5-4]]

^<<v24-5-4,4>>^ Eu, porém, disse: Deveras estes são uns pobres: são loucos, pois não sabem o caminho do Senhor, o juízo do seu Deus.

[[v24-5-5]]

^<<v24-5-5,5>>^ Irei aos grandes, e falarei com eles: porque eles sabem o caminho do Senhor, o juízo do seu Deus; mas estes de comum acordo quebraram o jugo, e romperam as ataduras.

[[v24-5-6]]

^<<v24-5-6,6>>^ Por isso um leão do bosque os feriu, um lobo dos desertos os assolará: um leopardo vigia contra as suas cidades: qualquer que sair delas será despedaçado; porque as suas transgressões se multiplicaram, multiplicaram-se as suas apostasias.

[[v24-5-7]]

^<<v24-5-7,7>>^ Como, vendo isto, te perdoaria? teus filhos me deixam a mim e juram pelos que não são  deuses: depois de os eu ter fartado, adulteraram, e em casa de meretrizes se ajuntaram em bandos.

[[v24-5-8]]

^<<v24-5-8,8>>^ Como  cavalos bem fartos, levantam-se pela manhã, rinchando cada um à mulher do seu companheiro.

[[v24-5-9]]

^<<v24-5-9,9>>^ Deixaria eu de castigar estas cousas, diz o Senhor, ou não se vingaria a minha alma de uma  nação como esta?

[[v24-5-10]]

^<<v24-5-10,10>>^ Subi aos seus muros, e destruí-os (não façais porém uma destruição final); tirai as suas ameias; porque não são do Senhor.

[[v24-5-11]]

^<<v24-5-11,11>>^ Porque aleivosissimamente se houveram contra mim a casa de Israel e a casa de Judá, diz o Senhor.

[[v24-5-12]]

^<<v24-5-12,12>>^ Negam ao Senhor, e dizem: Não é ele; e: Nenhum mal nos sobrevirá; não veremos espada nem fome.

[[v24-5-13]]

^<<v24-5-13,13>>^ E até os profetas se farão como vento, porque a palavra não está  com eles: assim lhes sucederá a eles mesmos.

[[v24-5-14]]

^<<v24-5-14,14>>^ Portanto assim diz o Senhor, o Deus dos Exércitos: Porquanto disseste tal palavra, eis que converterei as minhas palavras na tua boca em fogo, e a este povo em  lenha, e eles serão consumidos.

[[v24-5-15]]

^<<v24-5-15,15>>^ Eis que trarei sobre vós uma nação de longe, ó casa de Israel, diz o Senhor: uma nação robusta, uma nação antiquíssima, uma nação cuja língua ignorarás; e não entenderás o que ela falar.

[[v24-5-16]]

^<<v24-5-16,16>>^ A sua aljava é  como uma sepultura aberta: todos eles são  valentes.

[[v24-5-17]]

^<<v24-5-17,17>>^ E comerão a tua sega e o teu pão, que  haviam de comer teus filhos e tuas filhas; comerão as tuas ovelhas e as tuas vacas; comerão a tua vide e a tua figueira: as tuas cidades fortes, em que confiavas, abatê-las-á a espada.

[[v24-5-18]]

^<<v24-5-18,18>>^ Contudo, ainda naqueles dias, diz o Senhor, não farei de vós uma  destruição final.

[[v24-5-19]]

^<<v24-5-19,19>>^ E sucederá que, quando disserdes: Por que nos fez o Senhor nosso Deus todas estas cousas? então lhes dirás: Como vós me deixastes e servistes a deuses estranhos na vossa terra, assim servireis a estrangeiros, em terra que  não é  vossa.

[[v24-5-20]]

^<<v24-5-20,20>>^ Anunciai isto na casa de Jacó, e fazei-o ouvir em Judá, dizendo:

[[v24-5-21]]

^<<v24-5-21,21>>^ Ouvi agora isto, ó povo louco e sem coração, que tendes olhos e não vedes, que tendes ouvidos e não ouvis.

[[v24-5-22]]

^<<v24-5-22,22>>^ Não me temereis a mim? diz o Senhor; não temereis diante de mim, que pus a areia por limite ao mar, por ordenança eterna, que ele não traspassará? ainda que se levantem as suas ondas, não prevalecerão; ainda que bramem, não a traspassarão.

[[v24-5-23]]

^<<v24-5-23,23>>^ Mas este povo é  de coração rebelde e pertinaz: rebelaram-se e foram-se.

[[v24-5-24]]

^<<v24-5-24,24>>^ E não dizem no seu coração: Temamos agora ao Senhor nosso Deus, que dá chuva, a temporã e a tardia, a seu tempo; e  as semanas determinadas da sega nos conserva.

[[v24-5-25]]

^<<v24-5-25,25>>^ As vossas iniquidades desviam estas cousas, e os vossos pecados afastam de vós o bem.

[[v24-5-26]]

^<<v24-5-26,26>>^ Porque ímpios se acham entre o meu povo: cada um anda espiando, como se acaçapam os passarinheiros; armam laços perniciosos, com  que prendem os homens.

[[v24-5-27]]

^<<v24-5-27,27>>^ Como uma gaiola cheia de pássaros, são as suas casas cheias de engano; por isso se engrandeceram, e enriqueceram.

[[v24-5-28]]

^<<v24-5-28,28>>^ Engordam-se, alisam-se, e ultrapassam até os feitos dos malignos; não julgam a causa dos órfãos, para que eles prosperem: nem julgam o direito dos necessitados.

[[v24-5-29]]

^<<v24-5-29,29>>^ Não castigaria eu estas cousas? diz o Senhor; não se vingaria a minha alma de uma nação como esta?

[[v24-5-30]]

^<<v24-5-30,30>>^ Cousa espantosa e horrenda se anda fazendo na terra.

[[v24-5-31]]

^<<v24-5-31,31>>^ Os profetas profetizam falsamente, e os sacerdotes dominam pelas mãos deles, e o meu povo assim o deseja: e que fareis no fim disto?

'''

xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[Próximo Capítulo &#62;]