include::./index.adoc[]

[[v24-35-0]]
=== Jeremias, 35
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-35-1]]

^<<v24-35-1,1>>^ A PALAVRA que do Senhor veio a Jeremias, nos dias de Joaquim, filho de Josias, rei de Judá, dizendo:

[[v24-35-2]]

^<<v24-35-2,2>>^ Vai à casa dos recabitas, e fala com eles, e leva-os à casa do Senhor, a uma das câmaras, e dá-lhes vinho a beber.

[[v24-35-3]]

^<<v24-35-3,3>>^ Então tomei a Jasanias, filho de Jeremias, filho de Habazinias, e a seus irmãos, e a todos os seus filhos, e a toda a casa dos recabitas;

[[v24-35-4]]

^<<v24-35-4,4>>^ E os levei à casa do Senhor, à câmara dos filhos de Hanã, filho de Jigdalias, homem de Deus, que está  junto à câmara dos príncipes, que está  sobre a câmara de Maaseias, filho de Salum, guarda do vestíbulo.

[[v24-35-5]]

^<<v24-35-5,5>>^ E pus diante dos filhos da casa dos recabitas taças cheias de vinho, e copos, e disse-lhes: Bebei vinho.

[[v24-35-6]]

^<<v24-35-6,6>>^ Mas eles disseram: Não beberemos vinho; porque Jonadabe, filho de Recabe, nosso pai, nos mandou, dizendo: Nunca jamais bebereis vinho, nem vós nem vossos filhos;

[[v24-35-7]]

^<<v24-35-7,7>>^ Não edificareis casa, nem semeareis semente, não plantareis nem possuireis vinha alguma; mas habitareis em tendas todos os vossos dias, para que vivais muitos dias sobre a face da terra, em que vós andais peregrinando.

[[v24-35-8]]

^<<v24-35-8,8>>^ Obedecemos pois à voz de Jonadabe, filho de Recabe, nosso pai, em tudo quanto nos ordenou; de maneira que não bebemos vinho em todos os nossos dias, nem nós, nem nossas mulheres, nem nossos filhos, nem nossas filhas.

[[v24-35-9]]

^<<v24-35-9,9>>^ Nem edificamos casas para nossa habitação; nem temos vinha nem campo, nem semente.

[[v24-35-10]]

^<<v24-35-10,10>>^ Mas habitamos em tendas, e  assim ouvimos e fizemos conforme tudo quanto nos mandou Jonadabe, nosso pai.

[[v24-35-11]]

^<<v24-35-11,11>>^ Sucedeu, porém, que, subindo Nabucodonosor, rei de Babilônia, a esta terra, dissemos: Vinde, e vamo-nos a Jerusalém, por causa do exército dos caldeus e por causa do exército dos siros; e  assim ficamos em Jerusalém.

[[v24-35-12]]

^<<v24-35-12,12>>^ Então veio a palavra do Senhor a Jeremias, dizendo:

[[v24-35-13]]

^<<v24-35-13,13>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel: Vai, e dize aos homens de Judá e aos moradores de Jerusalém: Porventura  nunca aceitareis instrução, para ouvirdes as minhas palavras? diz o Senhor.

[[v24-35-14]]

^<<v24-35-14,14>>^ As palavras de Jonadabe, filho de Recabe, que ordenou a seus filhos que não bebessem vinho, foram guardadas, pois não beberam até este dia, antes ouviram o mandamento de seu pai; a mim, porém, que vos tenho falado a vós, madrugando e falando, vós não me ouvistes.

[[v24-35-15]]

^<<v24-35-15,15>>^ E vos enviei todos os meus servos, os profetas, madrugando, e enviando, e  dizendo: Convertei-vos agora, cada um do seu mau caminho, e fazei boas as vossas ações, e não sigais a outros deuses para servi-los; e assim ficareis na terra que vos  dei a vós e a vossos pais; mas não inclinastes o vosso ouvido, nem me obedecestes a mim.

[[v24-35-16]]

^<<v24-35-16,16>>^ Visto que os filhos de Jonadabe, filho de Recabe, guardaram o mandamento de seu pai, que ele lhes ordenou, mas este povo não me obedeceu:

[[v24-35-17]]

^<<v24-35-17,17>>^ Por isso assim diz o Senhor, o Deus dos Exércitos, o Deus de Israel: Eis que trarei sobre Judá, e sobre todos os moradores de Jerusalém, todo o mal que falei contra eles; pois lhes tenho falado, e não ouviram; e clamei a eles, e não responderam.

[[v24-35-18]]

^<<v24-35-18,18>>^ E à casa dos recabitas disse Jeremias: Assim diz o Senhor dos Exércitos, o Deus de Israel: Pois que obedecestes ao mandamento de Jonadabe, vosso pai, e guardastes todos os seus mandamentos, e fizestes conforme tudo quanto vos ordenou,

[[v24-35-19]]

^<<v24-35-19,19>>^ Portanto assim diz o Senhor dos Exércitos, Deus de Israel: Nunca faltará varão a Jonadabe, filho de Recabe, que assista perante a minha face todos os dias.

'''

xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[&#60; Capítulo Anterior] | <<v24-35-0,Topo>> | xref:024-jeremias/024-jeremias-036.adoc#v24-36-0[Próximo Capítulo &#62;]