include::./index.adoc[]

[[v24-8-0]]
=== Jeremias, 8
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-8-1]]

^<<v24-8-1,1>>^ NAQUELE tempo, diz o Senhor, tirarão os ossos dos reis de Judá, e os ossos dos seus príncipes, e os ossos dos sacerdotes, e os ossos dos profetas, e os ossos dos habitantes de Jerusalém para fora das suas sepulturas;

[[v24-8-2]]

^<<v24-8-2,2>>^ E expô-los-ão ao sol, e à lua, e a todo o exército do céu, a quem tinham amado e a quem tinham servido, e após quem tinham ido, e a quem tinham buscado e diante de quem se tinham prostrado: não serão recolhidos nem sepultados; serão como esterco sobre a face da terra.

[[v24-8-3]]

^<<v24-8-3,3>>^ E escolher-se-á antes a morte do que a vida de todo o resto dos que restarem desta raça maligna; que ficar nos lugares onde os lancei, diz o Senhor dos Exércitos.

[[v24-8-4]]

^<<v24-8-4,4>>^ Dize-lhes mais: Assim diz o Senhor: Cairão os homens, e não se tornarão a levantar? desviar-se-ão, e não voltarão?

[[v24-8-5]]

^<<v24-8-5,5>>^ Porque pois  se desvia este povo de Jerusalém com uma  apostasia contínua? retém o engano, não quer voltar.

[[v24-8-6]]

^<<v24-8-6,6>>^ Eu escutei e ouvi: não falam o que é  reto, ninguém há que se arrependa da sua maldade, dizendo: Que fiz eu? Cada um se desvia na sua carreira, como um cavalo que arremete com ímpeto na batalha.

[[v24-8-7]]

^<<v24-8-7,7>>^ Até a cegonha no céu conhece os seus tempos determinados; e a rola, e o grou e a andorinha observam o tempo da sua arribação: mas o meu povo não conhece o juízo do Senhor.

[[v24-8-8]]

^<<v24-8-8,8>>^ Como pois dizeis: Nós somos  sábios, e a lei do Senhor está conosco? eis que em vão tem trabalhado a falsa pena dos escribas.

[[v24-8-9]]

^<<v24-8-9,9>>^ Os sábios foram envergonhados, foram espantados e presos: eis que rejeitaram a palavra do Senhor; que sabedoria pois teriam?

[[v24-8-10]]

^<<v24-8-10,10>>^ Portanto darei suas mulheres a outros, e  as suas herdades a quem as possua; porque desde o menor até ao maior cada um deles se dá à avareza: desde o profeta até ao sacerdote, cada um deles usa de falsidade.

[[v24-8-11]]

^<<v24-8-11,11>>^ E curam a ferida da filha de meu povo levianamente, dizendo: Paz, paz; quando não há  paz.

[[v24-8-12]]

^<<v24-8-12,12>>^ Porventura  envergonham-se de cometer abominação? pelo contrário, de maneira nenhuma se envergonham, nem sabem que cousa é  envergonhar-se; portanto cairão entre os que caem e  tropeçarão no tempo em que eu os visitar, diz o Senhor.

[[v24-8-13]]

^<<v24-8-13,13>>^ Certamente os apanharei, diz o Senhor: já  não há uvas na vide, nem figos na figueira, e a folha caiu; e até aquilo mesmo que lhes dei se irá deles.

[[v24-8-14]]

^<<v24-8-14,14>>^ Porque nos assentamos ainda? juntai-vos e entremos nas cidades fortes, e ali estejamos calados; pois já  o Senhor nosso Deus nos fez calar e nos deu a beber água de fel; porquanto pecamos contra o Senhor.

[[v24-8-15]]

^<<v24-8-15,15>>^ Espera-se a paz, e não há  bem: o tempo da cura, e eis o terror.

[[v24-8-16]]

^<<v24-8-16,16>>^ Já desde Dã se ouve o resfolegar dos seus cavalos: toda a terra treme à voz dos rinchos dos seus fortes; e vêm, e devoram a terra e a sua abundância, a cidade e os que habitam nela.

[[v24-8-17]]

^<<v24-8-17,17>>^ Porque eis que enviarei entre vós serpentes e basiliscos, contra os quais não há encantamento, e vos morderão, diz o Senhor.

[[v24-8-18]]

^<<v24-8-18,18>>^ Oh! se eu pudesse consolar-me na minha tristeza! o meu coração desfalece em mim.

[[v24-8-19]]

^<<v24-8-19,19>>^ Eis a voz do clamor da filha do meu povo de terra mui remota: Não está  o Senhor em Sião? não está  nela o seu rei? Por que me provocaram à ira com as suas imagens de escultura, com vaidades estranhas?

[[v24-8-20]]

^<<v24-8-20,20>>^ Passou a sega, findou o verão, e nós não estamos salvos.

[[v24-8-21]]

^<<v24-8-21,21>>^ Estou quebrantado pela ferida da filha do meu povo: ando de luto: o espanto se apoderou de mim.

[[v24-8-22]]

^<<v24-8-22,22>>^ Porventura  não há unguento em Gileade? ou não há  lá médico? por que pois não teve lugar a cura da filha do meu povo?

'''

xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[&#60; Capítulo Anterior] | <<v24-8-0,Topo>> | xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[Próximo Capítulo &#62;]