include::./index.adoc[]

[[v24-49-0]]
=== Jeremias, 49
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-49-1]]

^<<v24-49-1,1>>^ CONTRA os filhos de Amom. Assim diz o Senhor: Acaso não tem filhos Israel, nem tem herdeiros? por que pois herdou Malcã a Gade e o seu povo habitou nas suas cidades?

[[v24-49-2]]

^<<v24-49-2,2>>^ Portanto, eis que vêm dias, diz o Senhor, em que farei ouvir em Rabá dos filhos de Amom o alarido de guerra e tornar-se-á num montão de ruínas e os lugares da sua jurisdição serão queimados a fogo; e Israel herdará aos que o herdaram, diz o Senhor.

[[v24-49-3]]

^<<v24-49-3,3>>^ Uiva, ó Hesbom, porque é destruída Ai; clamai, ó filhas de Rabá, cingi-vos de sacos, lamentai, e dai voltas pelos valados; porque Malcã irá em cativeiro, os seus sacerdotes e os seus príncipes juntamente.

[[v24-49-4]]

^<<v24-49-4,4>>^ Por que te glorias nos vales, teus luxuriantes vales, ó filha rebelde, que confias nos teus tesouros, dizendo : Quem virá contra mim?

[[v24-49-5]]

^<<v24-49-5,5>>^ Eis que eu trarei temor sobre ti, diz o Senhor Jeová  dos Exércitos, de todos os que estão  ao redor de ti; e sereis lançados fora, cada um  em frente, e ninguém recolherá o desgarrado.

[[v24-49-6]]

^<<v24-49-6,6>>^ Mas depois disto farei voltar os cativos dos filhos de Amom, diz o Senhor.

[[v24-49-7]]

^<<v24-49-7,7>>^ Contra Edom. Assim diz o Senhor dos Exércitos: Acaso não há  mais sabedoria em Temã? já  pereceu o conselho dos entendidos? corrompeu-se a sua sabedoria?

[[v24-49-8]]

^<<v24-49-8,8>>^ Fugi, voltai, habitai em profundezas, ó moradores de Dedã, porque eu trouxe sobre ele a ruína de Esaú, no tempo em que  o visitei.

[[v24-49-9]]

^<<v24-49-9,9>>^ Se vindimadores viessem a ti, não deixariam alguns rabiscos? se ladrões de noite, não  te danificariam quanto julgassem suficiente?

[[v24-49-10]]

^<<v24-49-10,10>>^ Mas eu despi a Esaú, descobri os seus esconderijos, e não se poderá esconder: é destruída a sua descendência, como também seus irmãos e seus vizinhos, e ele já  não é.

[[v24-49-11]]

^<<v24-49-11,11>>^ Deixa os teus órfãos: eu os  guardarei em vida; e as tuas viúvas confiarão em mim.

[[v24-49-12]]

^<<v24-49-12,12>>^ Porque assim diz o Senhor: Eis que os que não estavam condenados a beber o copo, totalmente o beberão, e tu ficarias inteiramente impune? não ficarás impune, mas certamente o  beberás.

[[v24-49-13]]

^<<v24-49-13,13>>^ Porque por mim mesmo jurei, diz o Senhor, que Bozra servirá de espanto, de opróbrio, de assolação, e de execração: e todas as suas cidades se tornarão em assolações perpétuas.

[[v24-49-14]]

^<<v24-49-14,14>>^ Ouvi um rumor vindo  do Senhor, que um embaixador é enviado às nações, para lhes dizer : Ajuntai-vos, e vinde contra ela, e levantai-vos para a guerra.

[[v24-49-15]]

^<<v24-49-15,15>>^ Porque eis que te fiz pequeno entre as nações, desprezado entre os homens.

[[v24-49-16]]

^<<v24-49-16,16>>^ Quanto à tua terribilidade, a arrogância do teu coração te enganou. Tu, que habitas nas cavernas das rochas, que ocupas as alturas dos outeiros; ainda que eleves o teu ninho como a águia, de lá te derribarei, diz o Senhor.

[[v24-49-17]]

^<<v24-49-17,17>>^ Assim servirá Edom de espanto: todo aquele que passar por ela se espantará, e assobiará por causa de todas as suas pragas.

[[v24-49-18]]

^<<v24-49-18,18>>^ Será  como a  destruição de Sodoma e Gomorra, e dos seus vizinhos, diz o Senhor: não habitará ninguém ali, nem morará nela filho de homem.

[[v24-49-19]]

^<<v24-49-19,19>>^ Eis que como leão subirá da enchente do Jordão contra a morada do forte; porque num momento o farei correr dali; e quem é  o escolhido que  porei sobre ela? porque quem é  semelhante a mim? e quem me emprazaria? e quem é  o pastor que subsistiria perante mim?

[[v24-49-20]]

^<<v24-49-20,20>>^ Portanto ouvi o conselho do Senhor, que ele decretou contra Edom; e os seus desígnios, que ele intentou contra os moradores de Temã: certamente os mais pequenos do rebanho os arrastarão: certamente assolará as suas moradas sobre eles.

[[v24-49-21]]

^<<v24-49-21,21>>^ A terra estremeceu com o estrondo da sua queda: e do seu grito até ao Mar Vermelho se ouviu o som.

[[v24-49-22]]

^<<v24-49-22,22>>^ Eis que como águia subirá, e voará, e estenderá as suas asas sobre Bozra: e o coração dos valentes de Edom naquele dia será como o coração da mulher que está em suas dores.

[[v24-49-23]]

^<<v24-49-23,23>>^ Contra Damasco. Envergonhou-se Hamate e Arpade, e, porquanto ouviram más novas, desmaiaram: no mar há  angústia; não se pode sossegar.

[[v24-49-24]]

^<<v24-49-24,24>>^ Enfraquecida está Damasco; virou as costas para fugir, e tremor a tomou; angústia e dores a tomaram como da que está de parto.

[[v24-49-25]]

^<<v24-49-25,25>>^ Como não está abandonada a afamada cidade, a cidade de meu folguedo?

[[v24-49-26]]

^<<v24-49-26,26>>^ Portanto cairão os seus mancebos nas suas ruas; e todos os homens de guerra serão consumidos naquele dia, diz o Senhor dos Exércitos.

[[v24-49-27]]

^<<v24-49-27,27>>^ E acenderei fogo no muro de Damasco, o qual consumirá os palácios de Benadade.

[[v24-49-28]]

^<<v24-49-28,28>>^ Contra Quedar, e contra os reinos de Hazor, que Nabucodonosor, rei de Babilônia, feriu. Assim diz o Senhor: Levantai-vos, subi contra Quedar, e destruí os filhos do oriente.

[[v24-49-29]]

^<<v24-49-29,29>>^ Tomarão as suas tendas, e os seus gados, as suas cortinas e todos os seus vasos, e os seus camelos levarão para si; e lhes gritarão: Há  medo de todos os lados!

[[v24-49-30]]

^<<v24-49-30,30>>^ Fugi, desviai-vos para mui longe, habitai nas profundezas, ó moradores de Azor, diz o Senhor: porque Nabucodonosor, rei de Babilônia, tomou conselho contra vós, e intentou um  desígnio contra vós.

[[v24-49-31]]

^<<v24-49-31,31>>^ Levantai-vos, subi contra uma nação em repouso, que habita confiadamente, diz o Senhor; que não tem portas, nem ferrolhos; eles habitam sós.

[[v24-49-32]]

^<<v24-49-32,32>>^ E os seus camelos serão para presa e a multidão dos seus gados para despojo: e espalharei a todo o vento, aqueles que têm cortados os cantos do seu cabelo , e de todos os lados lhes trarei a sua ruína, diz o Senhor.

[[v24-49-33]]

^<<v24-49-33,33>>^ E Hazor se tornará em morada de dragões, em  assolação para sempre; ninguém habitará ali, nem morará nela filho de homem.

[[v24-49-34]]

^<<v24-49-34,34>>^ A palavra do Senhor, que veio a Jeremias, o profeta, contra Elão, no princípio do reinado de Zedequias, rei de Judá, dizendo:

[[v24-49-35]]

^<<v24-49-35,35>>^ Assim diz o Senhor dos Exércitos: Eis que eu quebrarei o arco de Elão, o principal do seu poder.

[[v24-49-36]]

^<<v24-49-36,36>>^ E trarei sobre Elão os quatro ventos dos quatro ângulos do céu, e os espalharei na direção de todos estes ventos; e não haverá  nação aonde não venham os fugitivos de Elão.

[[v24-49-37]]

^<<v24-49-37,37>>^ E farei que Elão tema diante de seus inimigos, e diante dos que procuram a sua morte; e farei vir sobre eles o mal, o furor da minha ira, diz o Senhor; e enviarei após eles a espada, até que venha a consumi-los.

[[v24-49-38]]

^<<v24-49-38,38>>^ E porei o meu trono em Elão; e destruirei dali o rei e príncipes, diz o Senhor.

[[v24-49-39]]

^<<v24-49-39,39>>^ Acontecerá, porém, no último dos dias, que farei voltar os cativos de Elão, diz o Senhor.

'''

xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[&#60; Capítulo Anterior] | <<v24-49-0,Topo>> | xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[Próximo Capítulo &#62;]