include::./index.adoc[]

[[v24-46-0]]
=== Jeremias, 46
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-46-1]]

^<<v24-46-1,1>>^ A PALAVRA do Senhor, que veio a Jeremias, o profeta, contra as nações.

[[v24-46-2]]

^<<v24-46-2,2>>^ Acerca do Egito, contra o exército de Faraó Neco, rei do Egito, que estava junto ao rio Eufrates em Carquêmis; ao qual feriu Nabucodonosor rei de Babilônia, no ano quarto de Joaquim, filho de Josias, rei de Judá.

[[v24-46-3]]

^<<v24-46-3,3>>^ Preparai o escudo e o pavês, e chegai-vos para a peleja.

[[v24-46-4]]

^<<v24-46-4,4>>^ Selai os cavalos, e montai, cavaleiros, e apresentai-vos com elmos; alimpai as lanças, vesti-vos de couraças.

[[v24-46-5]]

^<<v24-46-5,5>>^ Por que razão vejo os medrosos voltando as costas? os seus heróis estão abatidos, e vão fugindo, sem olharem para trás: terror há  ao redor, diz o Senhor.

[[v24-46-6]]

^<<v24-46-6,6>>^ Não fuja o ligeiro e não escape o herói: para a banda do norte, junto à borda do rio Eufrates tropeçaram e caíram.

[[v24-46-7]]

^<<v24-46-7,7>>^ Quem é  este que  vem subindo como o Nilo e cujas águas se movem como os rios?

[[v24-46-8]]

^<<v24-46-8,8>>^ O Egito vem subindo como o Nilo e as suas  águas se movem como os rios; ele disse: Subirei, cobrirei a terra, destruirei a cidade, e os que habitam nela.

[[v24-46-9]]

^<<v24-46-9,9>>^ Trepai, ó cavalos, e estrondeai, ó carros, e saiam os valentes: os etíopes, e os de Pute, que tomam o escudo e os lídios, que tomam e  entesam o arco.

[[v24-46-10]]

^<<v24-46-10,10>>^ Porque este dia é  o dia do Senhor Jeová  dos Exércitos, dia de vingança para se vingar dos seus adversários: e a espada devorará, e fartar-se-á, e embriagar-se-á com o sangue deles; porque o Senhor Jeová  dos Exércitos tem um  sacrifício na terra do norte, junto ao rio Eufrates.

[[v24-46-11]]

^<<v24-46-11,11>>^ Sobe a Gileade, e toma bálsamo, ó virgem filha do Egito: debalde multiplicas remédios: não há  cura para ti.

[[v24-46-12]]

^<<v24-46-12,12>>^ As nações ouviram falar da tua vergonha, e a terra está  cheia do teu clamor; porque o valente tropeçou no valente, e  ambos caíram juntos.

[[v24-46-13]]

^<<v24-46-13,13>>^ A palavra que falou o Senhor a Jeremias, o profeta, acerca da vinda de Nabucodonosor, rei de Babilônia, para ferir a terra do Egito.

[[v24-46-14]]

^<<v24-46-14,14>>^ Anunciai no Egito, e fazei ouvir isto em Migdol; fazei também ouvi-lo em Nofe e em Tafnes; dizei: Apresenta-te e prepara-te; porque a espada devorou o que está  ao redor de ti.

[[v24-46-15]]

^<<v24-46-15,15>>^ Por que foram derribados os teus valentes? não se puderam ter em pé, porque o Senhor os abateu.

[[v24-46-16]]

^<<v24-46-16,16>>^ Multiplicou os que tropeçavam: também caíram uns sobre os outros, e disseram: Levanta-te, e voltemos ao nosso povo, e à terra do nosso nascimento, por causa da espada que oprime.

[[v24-46-17]]

^<<v24-46-17,17>>^ Clamaram ali: Faraó rei do Egito é  apenas um som; deixou passar o tempo assinalado.

[[v24-46-18]]

^<<v24-46-18,18>>^ Vivo eu, diz o rei, cujo nome é  o Senhor dos Exércitos, que certamente como o Tabor entre os montes, e como o Carmelo junto ao mar, assim  ele virá.

[[v24-46-19]]

^<<v24-46-19,19>>^ Prepara-te para ires para o cativeiro, ó moradora, filha do Egito; porque Nofe será  tornada em desolação, e será abrasada, até que ninguém mais aí more.

[[v24-46-20]]

^<<v24-46-20,20>>^ Bezerra mui formosa é  o Egito: mas já  vem a  destruição, vem do norte.

[[v24-46-21]]

^<<v24-46-21,21>>^ Até os seus mercenários no meio dela são  como bezerros cevados; mas também eles viraram as costas, fugiram juntos; não estiveram firmes; porque veio sobre eles o dia da sua ruína e  o tempo da sua visitação.

[[v24-46-22]]

^<<v24-46-22,22>>^ A sua voz irá como a  da serpente; porque marcharão com um exército, e virão a ela com machados, como cortadores de lenha.

[[v24-46-23]]

^<<v24-46-23,23>>^ Cortaram o seu bosque, diz o Senhor, que era impenetrável; porque se multiplicaram mais do que os gafanhotos; são inumeráveis.

[[v24-46-24]]

^<<v24-46-24,24>>^ A filha do Egito está envergonhada: foi entregue na mão do povo do norte.

[[v24-46-25]]

^<<v24-46-25,25>>^ Diz o Senhor dos Exércitos, Deus de Israel: Eis que eu visitarei Amom de Nô, e a Faraó, e ao Egito, e aos seus deuses, e aos seus reis; ao próprio Faraó, e aos que confiam nele.

[[v24-46-26]]

^<<v24-46-26,26>>^ E os entregarei na mão dos que procuram a sua morte, na mão de Nabucodonosor, rei de Babilônia, e na mão dos seus servos; mas depois será habitada como nos  dias antigos, diz o Senhor.

[[v24-46-27]]

^<<v24-46-27,27>>^ Não temas pois tu, servo meu, Jacó, nem te espantes, ó Israel; porque eis que te livrarei mesmo de longe, e a tua semente da terra do seu cativeiro; e Jacó voltará, e descansará, e sossegará, e não haverá quem o  atemorize.

[[v24-46-28]]

^<<v24-46-28,28>>^ Tu não temas, servo meu, Jacó, diz o Senhor, porque estou contigo; porque porei termo a todas as nações entre as quais te lancei; mas a ti não porei termo, mas castigar-te-ei com medida, e não te deixarei de todo impune.

'''

xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[&#60; Capítulo Anterior] | <<v24-46-0,Topo>> | xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[Próximo Capítulo &#62;]