include::./index.adoc[]

[[v24-21-0]]
=== Jeremias, 21
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-21-1]]

^<<v24-21-1,1>>^ A PALAVRA que veio a Jeremias da parte  do Senhor, quando o rei Zedequias lhe enviou a Pasur, filho de Malquias, e a Zefanias, filho de Maaseias, o sacerdote, dizendo:

[[v24-21-2]]

^<<v24-21-2,2>>^ Pergunta agora por nós ao Senhor por que Nabucodonosor, rei de Babilônia, guerreia contra nós: bem pode ser que o Senhor opere conosco segundo todas as suas maravilhas, e o faça retirar-se de nós.

[[v24-21-3]]

^<<v24-21-3,3>>^ Então Jeremias lhes disse: Assim direis a Zedequias.

[[v24-21-4]]

^<<v24-21-4,4>>^ Assim diz o Senhor, o Deus de Israel: Eis que virarei contra vós  as armas de guerra, que estão nas vossas mãos, com que vós pelejais contra o rei de Babilônia, e contra os caldeus que vos têm cercado fora dos muros, e ajuntá-los-ei no meio desta cidade.

[[v24-21-5]]

^<<v24-21-5,5>>^ E eu pelejarei contra vós com mão estendida, e com braço forte, e com ira, e com indignação e com grande furor.

[[v24-21-6]]

^<<v24-21-6,6>>^ E ferirei os habitantes desta cidade, assim os homens como os animais: de grande pestilência morrerão.

[[v24-21-7]]

^<<v24-21-7,7>>^ E depois disto, diz o Senhor, entregarei Zedequias, rei de Judá, e seus servos, e o povo, e os que desta cidade restarem da pestilência, e da espada, e da fome, na mão de Nabucodonosor, rei de Babilônia, e na mão de seus inimigos, e na mão dos que buscam a sua vida; e feri-los-á ao fio da espada: não os poupará, nem se compadecerá, nem terá misericórdia.

[[v24-21-8]]

^<<v24-21-8,8>>^ E a este povo dirás: Assim diz o Senhor: Eis que ponho diante de vós o caminho da vida e o caminho da morte.

[[v24-21-9]]

^<<v24-21-9,9>>^ O que ficar nesta cidade há de morrer à espada, ou à fome, ou da pestilência; mas o que sair, e se render aos caldeus, que vos têm cercado, viverá, e terá a sua vida por despojo.

[[v24-21-10]]

^<<v24-21-10,10>>^ Porque pus o meu rosto contra esta cidade para mal, e não para bem, diz o Senhor: na mão do rei de Babilônia se entregará, e ele a queimará a fogo:

[[v24-21-11]]

^<<v24-21-11,11>>^ E à casa do rei de Judá dirás : Ouvi a palavra do Senhor.

[[v24-21-12]]

^<<v24-21-12,12>>^ Ó casa de Davi, assim diz o Senhor: Julgai pela manhã justamente, e livrai o espoliado da mão do opressor; para que não saia o meu furor como fogo, e se acenda, sem que haja  quem o apague, por causa da maldade de vossas ações.

[[v24-21-13]]

^<<v24-21-13,13>>^ Eis que eu sou  contra ti, ó moradora do vale, ó rocha da campina, diz o Senhor: contra vós que dizeis: Quem descerá contra nós? ou: Quem entrará nas nossas moradas?

[[v24-21-14]]

^<<v24-21-14,14>>^ E eu vos visitarei segundo o fruto das vossas ações, diz o Senhor; e acenderei o fogo no seu bosque, que consumirá a tudo o que está em redor dela.

'''

xref:024-jeremias/024-jeremias-020.adoc#v24-20-0[&#60; Capítulo Anterior] | <<v24-21-0,Topo>> | xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[Próximo Capítulo &#62;]