include::./index.adoc[]

[[v24-42-0]]
=== Jeremias, 42
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-42-1]]

^<<v24-42-1,1>>^ ENTÃO chegaram todos os príncipes dos exércitos, e Joanã, filho de Careá, e Jezanias, filho de Hosaías, e todo o povo, desde o menor até ao maior,

[[v24-42-2]]

^<<v24-42-2,2>>^ E disseram a Jeremias, o profeta: Caia agora a nossa súplica diante de ti, e roga por nós ao Senhor teu Deus, por todo este resto; porque de muitos restamos uns  poucos, como veem os teus olhos;

[[v24-42-3]]

^<<v24-42-3,3>>^ Para que o Senhor teu Deus nos ensine o caminho por onde havemos de andar e aquilo que havemos de fazer.

[[v24-42-4]]

^<<v24-42-4,4>>^ E disse-lhes Jeremias, o profeta: Eu vos ouvi; eis que orarei ao Senhor vosso Deus conforme as vossas palavras; e seja o que for que o Senhor vos responder, eu vo-lo declararei; não vos ocultarei nada.

[[v24-42-5]]

^<<v24-42-5,5>>^ Então eles disseram a Jeremias: Seja o Senhor entre nós testemunha da verdade e fidelidade, se não fizermos conforme toda a palavra com que te enviar a nós o Senhor teu Deus.

[[v24-42-6]]

^<<v24-42-6,6>>^ Seja ela boa, ou seja má, à voz do Senhor nosso Deus, a quem te enviamos, obedeceremos, para que nos suceda bem, obedecendo à voz do Senhor nosso Deus.

[[v24-42-7]]

^<<v24-42-7,7>>^ E sucedeu que ao fim de dez dias veio a palavra do Senhor a Jeremias.

[[v24-42-8]]

^<<v24-42-8,8>>^ Então chamou a Joanã, filho de Careá, e a todos os príncipes dos exércitos, que havia  com ele, e a todo o povo, desde o menor até ao maior,

[[v24-42-9]]

^<<v24-42-9,9>>^ E disse-lhes: Assim diz o Senhor, Deus de Israel, a quem me enviastes, para lançar a vossa súplica diante dele:

[[v24-42-10]]

^<<v24-42-10,10>>^ Se de boa mente ficardes nesta terra, então vos edificarei, e não vos  derribarei; e vos plantarei e não vos  arrancarei; porque estou arrependido do mal que vos tenho feito.

[[v24-42-11]]

^<<v24-42-11,11>>^ Não temais o rei de Babilônia, a quem vós temeis; não o temais, diz o Senhor, porque eu sou  convosco, para vos salvar e para vos fazer livrar da sua mão.

[[v24-42-12]]

^<<v24-42-12,12>>^ E vos farei misericórdia, para que ele tenha misericórdia de vós, e vos faça voltar à vossa terra.

[[v24-42-13]]

^<<v24-42-13,13>>^ Mas se vós disserdes: Não ficaremos nesta terra, não obedecendo à voz do Senhor vosso Deus,

[[v24-42-14]]

^<<v24-42-14,14>>^ Dizendo: Não, antes iremos à terra do Egito, onde não veremos guerra nem ouviremos som de trombeta, nem teremos fome de pão, e ali ficaremos.

[[v24-42-15]]

^<<v24-42-15,15>>^ Nesse caso ouvi a palavra do Senhor, ó resto de Judá; assim diz o Senhor dos Exércitos, Deus de Israel: Se vós absolutamente puserdes os vossos rostos para entrardes no Egito, e entrardes para lá peregrinar,

[[v24-42-16]]

^<<v24-42-16,16>>^ Acontecerá então que a espada que  vós temeis ali vos alcançará na terra do Egito, e a fome que vós receais estará convosco no Egito, e ali morrereis.

[[v24-42-17]]

^<<v24-42-17,17>>^ Assim será com todos os homens que puseram os seus rostos para entrarem no Egito, a fim de lá peregrinarem: morrerão à espada, à fome, e da peste; e deles não haverá  quem reste e escape do mal que eu farei vir sobre eles.

[[v24-42-18]]

^<<v24-42-18,18>>^ Porque assim diz o Senhor dos Exércitos, Deus de Israel: Como se derramou a minha ira e a minha indignação sobre os habitantes de Jerusalém, assim se derramará a minha indignação sobre vós, quando entrardes no Egito; e sereis uma maldição, e um espanto, e uma execração, e um opróbrio, e não vereis mais este lugar.

[[v24-42-19]]

^<<v24-42-19,19>>^ Falou o Senhor acerca de vós, ó resto de Judá! não entreis no Egito, sabei de certo que testifiquei contra vós hoje.

[[v24-42-20]]

^<<v24-42-20,20>>^ Porquanto, enganastes as vossas almas, pois me enviastes ao Senhor vosso Deus, dizendo: Ora por nós ao Senhor nosso Deus; e conforme tudo o que disser o Senhor Deus nosso, declara-no-lo assim, e o faremos.

[[v24-42-21]]

^<<v24-42-21,21>>^ E vo-lo tenho declarado hoje; mas não destes ouvidos à voz do Senhor vosso Deus, em cousa alguma pela qual ele me enviou a vós.

[[v24-42-22]]

^<<v24-42-22,22>>^ Agora pois sabei por certo que à espada, à fome e da peste morrereis no mesmo  lugar onde desejastes entrar, para lá peregrinardes.

'''

xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[&#60; Capítulo Anterior] | <<v24-42-0,Topo>> | xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[Próximo Capítulo &#62;]