include::./index.adoc[]

[[v24-20-0]]
=== Jeremias, 20
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-20-1]]

^<<v24-20-1,1>>^ E PASUR, filho de Imer, o sacerdote, que havia sido nomeado presidente na casa do Senhor, ouviu a Jeremias, que profetizava estas cousas.

[[v24-20-2]]

^<<v24-20-2,2>>^ E feriu Pasur ao profeta Jeremias, e o meteu no cepo que está  na porta superior de Benjamim, a qual está  na casa do Senhor.

[[v24-20-3]]

^<<v24-20-3,3>>^ E sucedeu que no dia seguinte Pasur tirou a Jeremias do cepo. Então disse-lhe Jeremias: O Senhor não chama o teu nome Pasur, mas Magor-Missabibe.

[[v24-20-4]]

^<<v24-20-4,4>>^ Porque assim diz o Senhor: Eis que farei de ti um terror para ti mesmo, e para todos os teus amigos; eles cairão à espada de seus inimigos, e teus olhos o  verão; todo o Judá entregarei na mão do rei de Babilônia: ele os levará presos a Babilônia, e feri-los-á à espada.

[[v24-20-5]]

^<<v24-20-5,5>>^ Também darei toda a fazenda desta cidade, e todo o seu trabalho, e todas as suas cousas preciosas; sim, todos os tesouros dos reis de Judá entregarei na mão de seus inimigos, e saqueá-los-ão, tomá-los-ão e levá-los-ão a Babilônia.

[[v24-20-6]]

^<<v24-20-6,6>>^ E tu, Pasur, e todos os moradores da tua casa ireis para o cativeiro; e virás a Babilônia, e ali morrerás, e ali serás sepultado, tu, e todos os teus amigos, aos quais profetizaste falsamente.

[[v24-20-7]]

^<<v24-20-7,7>>^ Iludiste-me, ó Senhor, e iludido fiquei; mais forte foste do que eu, e prevaleceste: sirvo de escárnio todo o dia; cada um deles zomba de mim.

[[v24-20-8]]

^<<v24-20-8,8>>^ Porque desde que falo, grito; clamo: Violência e destruição; porque se tornou a palavra do Senhor um opróbrio para mim, e um ludíbrio todo o dia.

[[v24-20-9]]

^<<v24-20-9,9>>^ Então disse eu: Não me lembrarei dele, e não falarei mais no seu nome; mas isso foi no meu coração como fogo ardente, encerrado nos meus ossos; e estou fatigado de sofrer e não posso.

[[v24-20-10]]

^<<v24-20-10,10>>^ Porque ouvi a murmuração de muitos, e terror de todos os lados: Denunciai- no-lo , e o denunciaremos; todos os que têm paz comigo aguardam o meu manquejar, dizendo : Bem pode ser que se deixe persuadir; então prevaleceremos contra ele e nos vingaremos dele.

[[v24-20-11]]

^<<v24-20-11,11>>^ Mas o Senhor está  comigo como um valente terrível; por isso tropeçarão os meus perseguidores, e não prevalecerão: ficarão mui confundidos; como não se houveram prudentemente, terão  uma confusão perpétua que  nunca se esquecerá.

[[v24-20-12]]

^<<v24-20-12,12>>^ Tu pois, ó Senhor dos Exércitos, que provas o justo, e vês os rins e o coração: veja eu a tua vingança sobre eles; pois te descobri a minha causa.

[[v24-20-13]]

^<<v24-20-13,13>>^ Cantai ao Senhor, louvai ao Senhor; pois livrou a alma do necessitado da mão dos malfeitores.

[[v24-20-14]]

^<<v24-20-14,14>>^ Maldito o dia em que nasci: o dia em que minha mãe me deu à luz não seja bendito.

[[v24-20-15]]

^<<v24-20-15,15>>^ Maldito o homem que deu as novas a meu pai, dizendo: Nasceu-te um filho; alegrando-o com isso grandemente.

[[v24-20-16]]

^<<v24-20-16,16>>^ E seja esse homem como as cidades que o Senhor destruiu sem que se arrependesse: e ouça clamor pela manhã, e ao tempo do meio-dia um alarido.

[[v24-20-17]]

^<<v24-20-17,17>>^ Por que não me matou desde a madre? ou minha mãe não foi minha sepultura? ou não  ficou grávida perpetuamente?

[[v24-20-18]]

^<<v24-20-18,18>>^ Por que saí da madre, para ver trabalho e tristeza, e para que se consumam os meus dias na confusão?

'''

xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[&#60; Capítulo Anterior] | <<v24-20-0,Topo>> | xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[Próximo Capítulo &#62;]