include::./index.adoc[]

[[v24-29-0]]
=== Jeremias, 29
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-29-1]]

^<<v24-29-1,1>>^ E ESTAS são  as palavras da carta que Jeremias, o profeta, enviou de Jerusalém, ao resto dos anciãos do cativeiro, como também aos sacerdotes, e aos profetas, e a todo o povo que Nabucodonosor havia transportado de Jerusalém para Babilônia,

[[v24-29-2]]

^<<v24-29-2,2>>^ (Depois que saíram o rei Jeconias, e a rainha, e os eunucos, e os príncipes de Judá e Jerusalém, e os carpinteiros e ferreiros de Jerusalém),

[[v24-29-3]]

^<<v24-29-3,3>>^ Pela mão de Elasa, filho de Safã, e de Gemarias, filho de Hilquias (os quais Zedequias, rei de Judá, tinha enviado a Babilônia, a Nabucodonosor, rei de Babilônia), dizendo:

[[v24-29-4]]

^<<v24-29-4,4>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel, a todos os que foram transportados, que eu fiz transportar de Jerusalém para Babilônia:

[[v24-29-5]]

^<<v24-29-5,5>>^ Edificai casas e habitai-as; e plantai jardins, e comei o seu fruto.

[[v24-29-6]]

^<<v24-29-6,6>>^ Tomai mulheres e gerai filhos e filhas, e tomai mulheres para vossos filhos, e dai vossas filhas a maridos, para que tenham filhos e filhas; e multiplicai-vos ali, e não vos diminuais.

[[v24-29-7]]

^<<v24-29-7,7>>^ E procurai a paz da cidade, para onde vos fiz transportar, e orai por ela ao Senhor; porque na sua paz vós tereis paz.

[[v24-29-8]]

^<<v24-29-8,8>>^ Porque assim diz o Senhor dos Exércitos, o Deus de Israel: Não vos enganem os vossos profetas que estão  no meio de vós, nem os vossos adivinhos, nem deis ouvidos aos vossos sonhos, que sonhais:

[[v24-29-9]]

^<<v24-29-9,9>>^ Porque eles vos profetizam falsamente em meu nome: não os enviei, diz o Senhor.

[[v24-29-10]]

^<<v24-29-10,10>>^ Porque assim diz o Senhor: Certamente que passados setenta anos em Babilônia, vos visitarei, e cumprirei sobre vós a minha boa palavra, tornando-vos a trazer a este lugar.

[[v24-29-11]]

^<<v24-29-11,11>>^ Porque eu bem  sei os pensamentos que penso de vós, diz o Senhor; pensamentos de paz, e não de mal, para vos dar o fim que esperais.

[[v24-29-12]]

^<<v24-29-12,12>>^ Então me invocareis, e ireis, e orareis a mim, e eu vos ouvirei.

[[v24-29-13]]

^<<v24-29-13,13>>^ E buscar-me-eis, e me achareis quando me buscardes de todo o vosso coração.

[[v24-29-14]]

^<<v24-29-14,14>>^ E serei achado de vós, diz o Senhor, e farei voltar os vossos cativos, e congregar-vos-ei de todas as nações, e de todos os lugares para onde vos lancei, diz o Senhor, e tornarei a trazer-vos ao lugar donde vos transportei.

[[v24-29-15]]

^<<v24-29-15,15>>^ Porque dizeis: O Senhor nos levantou profetas em Babilônia.

[[v24-29-16]]

^<<v24-29-16,16>>^ Porque assim diz o Senhor a respeito do rei que se assenta no trono de Davi, e de todo o povo que habita nesta cidade, vossos irmãos, que não saíram convosco para o cativeiro;

[[v24-29-17]]

^<<v24-29-17,17>>^ Assim diz o Senhor dos Exércitos: Eis que enviarei entre eles a espada, a fome e a peste, e fá-los-ei como a figos podres, que não se podem comer, de maus que são.

[[v24-29-18]]

^<<v24-29-18,18>>^ E persegui-los-ei com a espada, com a fome, e com a peste; dá-los-ei para andarem de um lado para outro, entre todos os reinos da terra, e para serem uma maldição, e um espanto, e um assobio, e um opróbrio entre todas as nações para onde os tiver lançado;

[[v24-29-19]]

^<<v24-29-19,19>>^ Porquanto não deram ouvidos às minhas palavras, diz o Senhor, enviando-lhes eu os meus servos, os profetas, madrugando e enviando; mas vós não escutastes, diz o Senhor.

[[v24-29-20]]

^<<v24-29-20,20>>^ Vós, pois, ouvi a palavra do Senhor, todos os do cativeiro que enviei de Jerusalém para Babilônia.

[[v24-29-21]]

^<<v24-29-21,21>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel, acerca de Acabe, filho de Colaias, e de Zedequias, filho de Maaseias, que vos profetizam falsamente em meu nome: Eis que os entregarei na mão de Nabucodonosor, rei de Babilônia, e ele os ferirá diante dos vossos olhos.

[[v24-29-22]]

^<<v24-29-22,22>>^ E tomarão deles uma maldição todos os transportados de Judá, que estão  em Babilônia, dizendo: O Senhor te faça como Zedequias, e como Acabe, os quais o rei de Babilônia assou no fogo;

[[v24-29-23]]

^<<v24-29-23,23>>^ Porquanto fizeram loucura em Israel, e cometeram adultério com as mulheres de seus companheiros, e anunciaram falsamente em meu nome palavras que não lhes mandei dizer; e eu o sei e sou  testemunha disso , diz o Senhor.

[[v24-29-24]]

^<<v24-29-24,24>>^ E a Semaías, o neelamita, falarás, dizendo:

[[v24-29-25]]

^<<v24-29-25,25>>^ Assim fala o Senhor dos Exércitos, o Deus de Israel, dizendo: Porquanto tu enviaste no teu nome cartas a todo o povo que está  em Jerusalém, como também a Sofonias, filho de Maaseias, o sacerdote, e a todos os sacerdotes, dizendo:

[[v24-29-26]]

^<<v24-29-26,26>>^ O Senhor te pôs por sacerdote em lugar de Joiada, o sacerdote, para que sejas encarregado da casa do Senhor sobre todo o homem obsesso, e que profetiza, para o lançares na prisão e no tronco.

[[v24-29-27]]

^<<v24-29-27,27>>^ Agora, pois, porque não repreendeste a Jeremias, o anatotita, que vos profetiza?

[[v24-29-28]]

^<<v24-29-28,28>>^ Porque por isso nos mandou dizer para Babilônia: O cativeiro  muito há de durar; edificai casas, e habitai-as; e plantai jardins, e comei o seu fruto.

[[v24-29-29]]

^<<v24-29-29,29>>^ E lera Sofonias, o sacerdote, esta carta aos ouvidos de Jeremias, o profeta.

[[v24-29-30]]

^<<v24-29-30,30>>^ E veio a palavra do Senhor a Jeremias, dizendo:

[[v24-29-31]]

^<<v24-29-31,31>>^ Manda a todos os do cativeiro, dizendo: Assim diz o Senhor acerca de Semaías, o neelamita: Porquanto Semaías vos profetizou, e eu não o enviei, e vos fez confiar em mentiras.

[[v24-29-32]]

^<<v24-29-32,32>>^ Portanto assim diz o Senhor: Eis que visitarei a Semaías, o neelamita, e a sua descendência: ele não terá ninguém que habite entre este povo, e não verá o bem que hei de fazer ao meu povo, diz o Senhor, porquanto falou em rebelião contra o Senhor.

'''

xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[&#60; Capítulo Anterior] | <<v24-29-0,Topo>> | xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[Próximo Capítulo &#62;]