include::./index.adoc[]

[[v24-17-0]]
=== Jeremias, 17
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-17-1]]

^<<v24-17-1,1>>^ O PECADO de Judá está  escrito com um  ponteiro de ferro, com ponta de diamante, gravado na tábua do seu coração e nos ângulos dos seus altares.

[[v24-17-2]]

^<<v24-17-2,2>>^ Como também seus filhos se lembram dos seus altares, e dos seus bosques, e das árvores verdes, sobre os altos outeiros.

[[v24-17-3]]

^<<v24-17-3,3>>^ Ó minha montanha no campo! a tua riqueza e  todos os teus tesouros darei por presa, como também  os teus altos por causa do pecado, em todos os teus termos.

[[v24-17-4]]

^<<v24-17-4,4>>^ Assim por ti mesmo te privarás da tua herança que te dei, e far-te-ei servir os teus inimigos, na terra que não conheces; porque o fogo que acendeste na minha ira arderá para sempre.

[[v24-17-5]]

^<<v24-17-5,5>>^ Assim diz o Senhor: Maldito o homem que confia no homem, e faz da carne o seu braço, e aparta o seu coração do Senhor!

[[v24-17-6]]

^<<v24-17-6,6>>^ Porque será como a tamargueira no deserto, e não sentirá quando vem o bem; antes morará nos lugares secos do deserto, na terra salgada e inabitável.

[[v24-17-7]]

^<<v24-17-7,7>>^ Bendito o varão que confia no Senhor, e cuja esperança é o Senhor.

[[v24-17-8]]

^<<v24-17-8,8>>^ Porque será como a árvore plantada junto às águas, que estende as suas raízes para o ribeiro, e não receia quando vem o calor, mas a sua folha fica verde; e no ano de sequidão não se afadiga, nem deixa de dar fruto.

[[v24-17-9]]

^<<v24-17-9,9>>^ Enganoso é  o coração, mais do que todas as cousas, e perverso: quem o conhecerá?

[[v24-17-10]]

^<<v24-17-10,10>>^ Eu, o Senhor, esquadrinho o coração, eu provo os rins: e isto para dar a cada um segundo os seus caminhos e  segundo o fruto das suas ações.

[[v24-17-11]]

^<<v24-17-11,11>>^ Como a perdiz que  ajunta ovos que não choca, assim  é aquele que ajunta riquezas, mas não retamente; no meio de seus dias as deixará, e no seu fim se fará um  insensato.

[[v24-17-12]]

^<<v24-17-12,12>>^ Um trono de glória, posto bem alto desde o princípio, é  o lugar do nosso santuário.

[[v24-17-13]]

^<<v24-17-13,13>>^ Ó Senhor, Esperança de Israel! todos aqueles que te deixam serão envergonhados: os que se apartam de mim serão escritos sobre a terra; porque abandonam o Senhor, a fonte das águas vivas.

[[v24-17-14]]

^<<v24-17-14,14>>^ Sara-me, Senhor, e sararei: salva-me, e serei salvo; porque tu és  o meu louvor.

[[v24-17-15]]

^<<v24-17-15,15>>^ Eis que eles me dizem: Onde está  a palavra do Senhor? venha agora.

[[v24-17-16]]

^<<v24-17-16,16>>^ Mas eu não me apressei em ser o pastor após ti; nem tão pouco desejei o dia de aflição, tu o sabes; o que saiu dos meus lábios está diante de tua face.

[[v24-17-17]]

^<<v24-17-17,17>>^ Não me sejas por espanto: meu refúgio és  tu no dia do mal.

[[v24-17-18]]

^<<v24-17-18,18>>^ Envergonhem-se os que me perseguem, e não me envergonhe eu; assombrem-se eles, e não me assombre eu: traze sobre eles o dia do mal, e destrói-os com dobrada destruição.

[[v24-17-19]]

^<<v24-17-19,19>>^ Assim me disse o Senhor: Vai, põe-te à porta dos filhos do povo, pela qual entram os reis de Judá, e pela qual saem; como também a todas as portas de Jerusalém.

[[v24-17-20]]

^<<v24-17-20,20>>^ E dize-lhes: Ouvi a palavra do Senhor, vós, reis de Judá e todo o Judá, e todos os moradores de Jerusalém, que entrais por estas portas.

[[v24-17-21]]

^<<v24-17-21,21>>^ Assim diz o Senhor: Guardai as vossas almas, e não tragais cargas no dia de sábado, nem as  introduzais pelas portas de Jerusalém.

[[v24-17-22]]

^<<v24-17-22,22>>^ Nem tireis cargas de vossas casas no dia de sábado, nem façais obra alguma: antes santificai o dia de sábado, como eu ordenei a vossos pais.

[[v24-17-23]]

^<<v24-17-23,23>>^ Mas não deram ouvidos, nem inclinaram as suas orelhas; antes endureceram a sua cerviz, para não ouvirem, e para não receberem correção.

[[v24-17-24]]

^<<v24-17-24,24>>^ Será pois que, se diligentemente me ouvirdes, diz o Senhor, não introduzindo cargas pelas portas desta cidade no dia de sábado, e santificardes o dia de sábado, não fazendo nele obra alguma;

[[v24-17-25]]

^<<v24-17-25,25>>^ Então entrarão pelas portas desta cidade reis e príncipes, assentados sobre o trono de Davi, andando em carros e montados em cavalos, eles e seus príncipes, os homens de Judá, e os moradores de Jerusalém: e esta cidade será para sempre habitada.

[[v24-17-26]]

^<<v24-17-26,26>>^ E virão das cidades de Judá, e dos contornos de Jerusalém, e da terra de Benjamim, e das planícies, e das montanhas, e do sul, trazendo holocaustos, e sacrifícios, e ofertas de manjares, e incenso, trazendo igualmente sacrifícios de louvores à casa do Senhor.

[[v24-17-27]]

^<<v24-17-27,27>>^ Mas, se não me derdes ouvidos, para santificardes o dia de sábado, e para não trazerdes carga alguma, quando entrardes pelas portas de Jerusalém no dia de sábado, então acenderei fogo nas suas portas o qual consumirá os palácios de Jerusalém, e não se apagará.

'''

xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[&#60; Capítulo Anterior] | <<v24-17-0,Topo>> | xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[Próximo Capítulo &#62;]