include::./index.adoc[]

[[v24-22-0]]
=== Jeremias, 22
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-22-1]]

^<<v24-22-1,1>>^ ASSIM diz o Senhor: Desce à casa do rei de Judá, e anuncia ali esta palavra.

[[v24-22-2]]

^<<v24-22-2,2>>^ E dize: Ouve a palavra do Senhor, ó rei de Judá, que te assentas no trono de Davi; tu, e os teus servos, e o teu povo, que entrais por estas portas.

[[v24-22-3]]

^<<v24-22-3,3>>^ Assim diz o Senhor: Exercei o juízo e a justiça, e livrai o espoliado da mão do opressor; e não oprimais ao estrangeiro, nem  ao órfão, nem à viúva; não façais violência, nem derrameis sangue inocente neste lugar.

[[v24-22-4]]

^<<v24-22-4,4>>^ Porque, se deveras cumprirdes esta palavra, entrarão pelas portas desta casa os reis que se assentam no lugar de Davi sobre o seu trono, em carros e montados em cavalos, eles, e os seus servos, e o seu povo.

[[v24-22-5]]

^<<v24-22-5,5>>^ Mas se não derdes ouvidos a estas palavras, por mim mesmo tenho jurado, diz o Senhor, que esta casa se tornará em assolação.

[[v24-22-6]]

^<<v24-22-6,6>>^ Porque assim diz o Senhor acerca da casa do rei de Judá: Tu és  para mim Gileade, e  a cabeça do Líbano: mas por certo que farei de ti um deserto e cidades desabitadas.

[[v24-22-7]]

^<<v24-22-7,7>>^ Porque prepararei contra ti destruidores, cada um com as suas armas: e cortarão os teus cedros escolhidos, e lançá-los-ão no fogo.

[[v24-22-8]]

^<<v24-22-8,8>>^ E muitas nações passarão por esta cidade, e dirá cada um, ao seu companheiro: Por que procedeu o Senhor assim com esta grande cidade?

[[v24-22-9]]

^<<v24-22-9,9>>^ Então responderão: Porque deixaram o concerto do Senhor seu Deus, e se inclinaram diante de deuses alheios, e os serviram.

[[v24-22-10]]

^<<v24-22-10,10>>^ Não choreis o morto, nem o lastimeis: chorai abundantemente aquele que sai, porque nunca mais tornará, nem verá a terra onde nasceu.

[[v24-22-11]]

^<<v24-22-11,11>>^ Porque assim diz o Senhor acerca de Salum, filho de Josias, rei de Judá, que reinou em lugar de Josias seu pai, que saiu deste lugar: Nunca ali tornará mais.

[[v24-22-12]]

^<<v24-22-12,12>>^ Mas no lugar para onde o levaram cativo morrerá, e nunca mais verá esta terra.

[[v24-22-13]]

^<<v24-22-13,13>>^ Ai daquele que edifica a sua casa com injustiça, e os seus aposentos sem direito, que se serve do serviço do seu próximo sem paga, e não lhe dá o salário do seu trabalho;

[[v24-22-14]]

^<<v24-22-14,14>>^ Que diz: edificarei para mim uma  casa espaçosa, e aposentos largos: e lhe abre janelas, e está  forrada de cedro, e pintada de vermelhão.

[[v24-22-15]]

^<<v24-22-15,15>>^ Reinarás tu, porque te encerras em cedro? acaso teu pai não comeu e bebeu, e não exercitou o juízo e a justiça? por isso lhe sucedeu bem.

[[v24-22-16]]

^<<v24-22-16,16>>^ Julgou a causa do aflito e do necessitado; então lhe  sucedeu bem; porventura  não é isto conhecer-me? diz o Senhor.

[[v24-22-17]]

^<<v24-22-17,17>>^ Mas os teus olhos e o teu coração não atentam  senão para a tua avareza, e para o sangue inocente, a fim de derramá-lo, e para a opressão, e para a violência, a fim de levar isso a efeito.

[[v24-22-18]]

^<<v24-22-18,18>>^ Portanto assim diz o Senhor acerca de Joaquim, filho de Josias, rei de Judá: Não lamentarão por ele, dizendo : Ai, irmão meu, ou: Ai, minha irmã! nem lamentarão por ele, dizendo : Ai, Senhor, ou: Ai Majestoso!

[[v24-22-19]]

^<<v24-22-19,19>>^ Em sepultura de jumento o sepultarão, arrastando-o e lançando-o para bem longe, fora das portas de Jerusalém.

[[v24-22-20]]

^<<v24-22-20,20>>^ Sobe ao Líbano, e clama, e levanta a tua voz em Basã, e clama desde Abarim, porque estão quebrantados os teus namorados.

[[v24-22-21]]

^<<v24-22-21,21>>^ Falei contigo da tua prosperidade, mas tu disseste: Não ouvirei. Este é o teu caminho, desde a tua mocidade, pois nunca deste ouvidos à minha voz.

[[v24-22-22]]

^<<v24-22-22,22>>^ O vento apascentará todos os teus pastores, e os teus namorados irão para o cativeiro: certamente então te confundirás, e te envergonharás, por causa de toda a tua maldade.

[[v24-22-23]]

^<<v24-22-23,23>>^ Ó tu, que habitas no Líbano e  fazes o teu ninho nos cedros! quão lastimada serás quando te vierem as dores e  os ais como da que está de parto!

[[v24-22-24]]

^<<v24-22-24,24>>^ Vivo eu, diz o Senhor, que ainda que Jeconias, filho de Joaquim, rei de Judá, fosse o selo do anel da minha mão direita, eu dali te arrancaria.

[[v24-22-25]]

^<<v24-22-25,25>>^ E te entregarei na mão dos que buscam a tua vida, e na mão daqueles diante de quem tu temes, a saber, na mão de Nabucodonosor, rei de Babilônia, e na mão dos caldeus.

[[v24-22-26]]

^<<v24-22-26,26>>^ E lançar-te-ei, a ti e à tua mãe que te deu à luz, para uma terra estranha, em que não nasceste, e ali morrereis.

[[v24-22-27]]

^<<v24-22-27,27>>^ Mas à terra, para a qual eles levantam a sua alma, para ali tornarem, a ela não tornarão.

[[v24-22-28]]

^<<v24-22-28,28>>^ É, pois, este homem Jeconias um vil vaso quebrado? ou um vaso de que ninguém se agrada? Por que razão foram arremessados fora, ele e a sua geração, e arrojados para uma  terra que não conhecem?

[[v24-22-29]]

^<<v24-22-29,29>>^ Ó terra, terra, terra! ouve a palavra do Senhor.

[[v24-22-30]]

^<<v24-22-30,30>>^ Assim diz o Senhor: Escrevei que  este homem está privado de seus filhos, e é homem que  não prosperará nos seus dias; nem prosperará algum da sua geração, para se assentar no trono de Davi, e reinar mais em Judá.

'''

xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[&#60; Capítulo Anterior] | <<v24-22-0,Topo>> | xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[Próximo Capítulo &#62;]