include::./index.adoc[]

[[v24-41-0]]
=== Jeremias, 41
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-41-1]]

^<<v24-41-1,1>>^ SUCEDEU, porém, no mês sétimo, que  veio Ismael, filho de Netanias, filho de Elisama, de sangue real, e os capitães do rei, a saber, dez homens com ele, a Gedalias, filho de Aicão, a Mizpá; e ali eles comeram pão juntos em Mizpá.

[[v24-41-2]]

^<<v24-41-2,2>>^ E levantou-se Ismael filho de Netanias, com os dez homens que estavam com ele, e feriram a Gedalias, filho de Aicão, filho de Safã, à espada; matando assim aquele que o rei de Babilônia havia posto sobre a terra.

[[v24-41-3]]

^<<v24-41-3,3>>^ Também feriu Ismael a todos os judeus que com ele; com Gedalias, estavam em Mizpá, como também aos caldeus, homens de guerra, que se achavam ali.

[[v24-41-4]]

^<<v24-41-4,4>>^ Sucedeu pois no dia seguinte, depois que ele matara a Gedalias, sem ninguém o  saber,

[[v24-41-5]]

^<<v24-41-5,5>>^ Que vieram homens de Siquém, de Silo, e de Samaria; oitenta homens, com a barba rapada, e os vestidos rasgados, e sarjando-se; e traziam nas suas mãos ofertas de manjares e incenso, para levarem à casa do Senhor.

[[v24-41-6]]

^<<v24-41-6,6>>^ E, saindo-lhes ao encontro Ismael, filho de Netanias, desde Mizpá, ia chorando; e sucedeu que, encontrando-os lhes disse: Vinde a Gedalias, filho de Aicão.

[[v24-41-7]]

^<<v24-41-7,7>>^ Sucedeu, porém, que, indo eles até ao meio da cidade, matou-os Ismael, filho de Netanias, e os lançou  num poço, ele e os homens que estavam  com ele.

[[v24-41-8]]

^<<v24-41-8,8>>^ Mas houve entre eles dez homens que disseram a Ismael: Não nos mates a nós; porque temos no campo tesouros escondidos, trigo e cevada, e azeite e mel. E ele por isso os deixou, e não os matou como a seus irmãos.

[[v24-41-9]]

^<<v24-41-9,9>>^ E o poço, em que Ismael lançou todos os cadáveres dos homens que feriu por causa de Gedalias, é  o mesmo que fez o rei Asa, por causa de Baasa, rei de Israel; foi esse mesmo que encheu de mortos Ismael, filho de Netanias.

[[v24-41-10]]

^<<v24-41-10,10>>^ E Ismael levou cativo a todo o resto do povo que estava  em Mizpá; as filhas do rei, e todo o povo que ficara em Mizpá, que Nebuzaradão, capitão da guarda, havia confiado a Gedalias, filho de Aicão; levou-os cativos Ismael, filho de Netanias; e foi-se, para passar aos filhos de Amom.

[[v24-41-11]]

^<<v24-41-11,11>>^ Ouvindo pois Joanã, filho de Careá, e todos os príncipes dos exércitos que estavam com ele, todo o mal que havia feito Ismael, filho de Netanias.

[[v24-41-12]]

^<<v24-41-12,12>>^ Tomaram todos os seus  homens, e foram pelejar contra Ismael, filho de Netanias: e acharam-no ao pé das muitas águas que há em Gibeom.

[[v24-41-13]]

^<<v24-41-13,13>>^ E aconteceu que, vendo todo o povo, que estava  com Ismael, a Joanã filho de Careá, e a todos os príncipes dos exércitos, que vinham  com ele, se alegrou.

[[v24-41-14]]

^<<v24-41-14,14>>^ E todo o povo que Ismael levara cativo de Mizpá virou as costas, e voltou, e foi para Joanã, filho de Careá.

[[v24-41-15]]

^<<v24-41-15,15>>^ Mas Ismael, filho de Netanias escapou com oito homens de diante de Joanã, e se foi para os filhos de Amom.

[[v24-41-16]]

^<<v24-41-16,16>>^ Então tomou Joanã, filho de Careá, e todos os príncipes dos exércitos que estavam com ele, a todo o resto do povo que ele havia recobrado de Ismael, filho de Netanias, desde Mizpá, depois que tinha sido ferido Gedalias, filho de Aicão, e aos homens valentes de guerra, e às mulheres, e aos meninos, e aos eunucos que havia recobrado de Gibeom,

[[v24-41-17]]

^<<v24-41-17,17>>^ E partiram, indo habitar em Gerute-Quimã, que está  perto de Belém, para dali entrarem no Egito,

[[v24-41-18]]

^<<v24-41-18,18>>^ Por causa dos caldeus; porque os temiam, por ter Ismael, filho de Netanias, ferido a Gedalias, filho de Aicão, a quem o rei de Babilônia tinha posto sobre a terra.

'''

xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[&#60; Capítulo Anterior] | <<v24-41-0,Topo>> | xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[Próximo Capítulo &#62;]