include::./index.adoc[]

[[v24-31-0]]
=== Jeremias, 31
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-31-1]]

^<<v24-31-1,1>>^ NAQUELE tempo, diz o Senhor, serei o Deus de todas as gerações de Israel, e elas serão o meu povo.

[[v24-31-2]]

^<<v24-31-2,2>>^ Assim diz o Senhor: O povo que escapou da espada achou graça no deserto; Israel mesmo, quando eu o fizer descansar.

[[v24-31-3]]

^<<v24-31-3,3>>^ Há muito que o Senhor me apareceu, dizendo : Pois que com amor eterno te amei, também com amorável benignidade te atraí.

[[v24-31-4]]

^<<v24-31-4,4>>^ Ainda te edificarei, e serás  edificada, ó virgem de Israel! ainda serás adornada com os teus adufes, e sairás com o coro dos que dançam.

[[v24-31-5]]

^<<v24-31-5,5>>^ Ainda plantarás vinhas nos montes de Samaria: os plantadores plantarão e gozarão dos frutos.

[[v24-31-6]]

^<<v24-31-6,6>>^ Porque haverá um dia em que  gritarão os vigias sobre o monte de Efraim: Levantai-vos, e subamos a Sião, ao Senhor nosso Deus.

[[v24-31-7]]

^<<v24-31-7,7>>^ Porque assim diz o Senhor: Cantai sobre Jacó com alegria, e exultai por causa do Chefe das gentes; proclamai, cantai louvores, e dizei: Salva, Senhor, o teu povo, o resto de Israel.

[[v24-31-8]]

^<<v24-31-8,8>>^ Eis que os trarei da terra do norte, e os congregarei das extremidades da terra; e com eles os cegos e aleijados, as mulheres grávidas e as de parto juntamente: em grande congregação voltarão para aqui.

[[v24-31-9]]

^<<v24-31-9,9>>^ Virão com choro, e com súplicas os levarei; guiá-los-ei aos ribeiros de águas, por caminho direito em que não tropeçarão; porque sou um pai para Israel, e Efraim é  o meu primogênito.

[[v24-31-10]]

^<<v24-31-10,10>>^ Ouvi a palavra do Senhor, ó nações, e anunciai-a nas ilhas de longe, e dizei: Aquele que espalhou a Israel o congregará e o guardará, como o pastor ao seu rebanho.

[[v24-31-11]]

^<<v24-31-11,11>>^ Porque o Senhor resgatou a Jacó, e o livrou da mão do que era mais forte do que ele.

[[v24-31-12]]

^<<v24-31-12,12>>^ Assim que virão, e exultarão na altura de Sião, e correrão aos bens do Senhor, ao trigo, e ao mosto, e ao azeite, aos cordeiros e aos bezerros; e a sua alma será como um jardim regado, e nunca mais andarão tristes.

[[v24-31-13]]

^<<v24-31-13,13>>^ Então a virgem se alegrará na dança, e também os mancebos e os velhos; e tornarei o seu pranto em alegria, e os consolarei, e transformarei em regozijo a sua tristeza.

[[v24-31-14]]

^<<v24-31-14,14>>^ E saciarei a alma dos sacerdotes de gordura, e o meu povo se fartará dos meus bens, diz o Senhor.

[[v24-31-15]]

^<<v24-31-15,15>>^ Assim diz o Senhor: Uma voz se ouviu em Ramá, lamentação, choro amargo: Raquel chora seus filhos, sem admitir consolação por eles, porque já não existem.

[[v24-31-16]]

^<<v24-31-16,16>>^ Assim diz o Senhor: Reprime a tua voz de choro, e as lágrimas de teus olhos: porque há galardão para o teu trabalho, diz o Senhor, pois eles voltarão da terra do inimigo.

[[v24-31-17]]

^<<v24-31-17,17>>^ E há esperanças no derradeiro fim para os teus descendentes, diz o Senhor, porque teus  filhos voltarão para os seus termos.

[[v24-31-18]]

^<<v24-31-18,18>>^ Bem ouvi eu que Efraim se queixava, dizendo : Castigaste-me e fui castigado, como novilho ainda não domado: converte-me, e converter-me-ei, porque tu és o Senhor meu Deus.

[[v24-31-19]]

^<<v24-31-19,19>>^ Na verdade que, depois que me converti, tive arrependimento; e depois que me conheci, bati na minha coxa: fiquei confuso; sim, envergonhei-me, porque suportei o opróbrio da minha mocidade.

[[v24-31-20]]

^<<v24-31-20,20>>^ Não é Efraim para mim um filho precioso? criança das minhas delícias? porque depois que falo contra ele, ainda me lembro dele solicitamente; por isso se comovem por ele as minhas entranhas: deveras me compadecerei dele, diz o Senhor.

[[v24-31-21]]

^<<v24-31-21,21>>^ Ergue para ti marcos, levanta para ti pirâmides, aplica o teu coração à vereda, ao caminho em que andaste: regressa, ó virgem de Israel, regressa a estas tuas cidades.

[[v24-31-22]]

^<<v24-31-22,22>>^ Até quando andarás vagabunda, ó filha rebelde? porque o Senhor criou uma cousa nova na terra: uma mulher cercará um varão.

[[v24-31-23]]

^<<v24-31-23,23>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel: Ainda dirão esta palavra na terra de Judá, e nas suas cidades, quando eu acabar o seu cativeiro: O Senhor te abençoe, ó morada de justiça, ó monte de santidade!

[[v24-31-24]]

^<<v24-31-24,24>>^ E nela habitarão Judá, e todas as suas cidades juntamente; como também  os lavradores e os que  andam com o rebanho.

[[v24-31-25]]

^<<v24-31-25,25>>^ Porque satisfiz a alma cansada, e toda a alma entristecida saciei.

[[v24-31-26]]

^<<v24-31-26,26>>^ Sobre isto despertei, e olhei, e o meu sono foi doce para mim.

[[v24-31-27]]

^<<v24-31-27,27>>^ Eis que dias vêm, diz o Senhor, em que semearei a casa de Israel, e a casa de Judá, com a semente de homens, e com a semente de animais.

[[v24-31-28]]

^<<v24-31-28,28>>^ E será  que, como velei sobre eles, para arrancar, e para derribar, e para transtornar, e para destruir, e para afligir, assim velarei sobre eles, para edificar e para plantar, diz o Senhor.

[[v24-31-29]]

^<<v24-31-29,29>>^ Naqueles dias nunca mais dirão: Os pais comeram uvas verdes, e os dentes dos filhos se embotaram.

[[v24-31-30]]

^<<v24-31-30,30>>^ Mas cada um morrerá pela sua iniquidade: de todo o homem que comer as uvas verdes os dentes se embotarão.

[[v24-31-31]]

^<<v24-31-31,31>>^ Eis que dias vêm, diz o Senhor, em que farei um concerto novo com a casa de Israel e com a casa de Judá.

[[v24-31-32]]

^<<v24-31-32,32>>^ Não conforme o concerto que fiz com seus pais, no dia em que os tomei pela mão, para os tirar da terra do Egito; porquanto eles invalidaram o meu concerto, apesar de eu os haver desposado, diz o Senhor.

[[v24-31-33]]

^<<v24-31-33,33>>^ Mas este é  o concerto que farei com a casa de Israel depois daqueles dias, diz o Senhor: Porei a minha lei no seu interior, e a escreverei no seu coração; e eu serei o seu Deus e eles serão o meu povo.

[[v24-31-34]]

^<<v24-31-34,34>>^ E não ensinará alguém mais a seu próximo nem alguém a seu irmão, dizendo: Conhecei ao Senhor: porque todos me conhecerão, desde o mais pequeno deles até ao maior, diz o Senhor; porque lhes perdoarei a sua maldade, e nunca mais me lembrarei dos seus pecados.

[[v24-31-35]]

^<<v24-31-35,35>>^ Assim diz o Senhor, que dá o sol para luz do dia, e  as ordenanças da lua e das estrelas para luz da noite, que fende o mar, e faz bramir as suas ondas; o Senhor dos Exércitos é  o seu nome.

[[v24-31-36]]

^<<v24-31-36,36>>^ Se se desviarem estas ordenanças de diante de mim, diz o Senhor, deixará também a semente de Israel de ser uma nação diante de mim para sempre.

[[v24-31-37]]

^<<v24-31-37,37>>^ Assim disse o Senhor: Se puderem ser medidos os céus para cima, e sondados os fundamentos da terra para baixo, também eu rejeitarei toda a semente de Israel, por tudo quanto fizeram, diz o Senhor.

[[v24-31-38]]

^<<v24-31-38,38>>^ Eis que dias vêm, diz o Senhor, em que esta cidade será reedificada para o Senhor, desde a torre de Hananeel até à porta da esquina.

[[v24-31-39]]

^<<v24-31-39,39>>^ E a linha de medir estender-se-á para diante, até ao outeiro de Garebe, e virar-se-á para Goá.

[[v24-31-40]]

^<<v24-31-40,40>>^ E todo o vale dos cadáveres e da cinza e todos os campos até ao ribeiro de Cedrom, até à esquina da porta dos cavalos para o oriente, serão  consagrados ao Senhor; não se arrancarão nem se derribarão mais eternamente.

'''

xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[&#60; Capítulo Anterior] | <<v24-31-0,Topo>> | xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[Próximo Capítulo &#62;]