include::./index.adoc[]

[[v24-25-0]]
=== Jeremias, 25
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-25-1]]

^<<v24-25-1,1>>^ A PALAVRA que veio a Jeremias acerca de todo o povo de Judá no ano quarto de Joaquim, filho de Josias, rei de Judá (que é o primeiro ano de Nabucodonosor, rei de Babilônia),

[[v24-25-2]]

^<<v24-25-2,2>>^ A qual anunciou o profeta Jeremias a todo o povo de Judá, e a todos os habitantes de Jerusalém, dizendo:

[[v24-25-3]]

^<<v24-25-3,3>>^ Desde o ano treze de Josias, filho de Amom, rei de Judá, até este dia (que é o ano vinte e três), veio a mim a palavra do Senhor, e vo-la anunciei a vós, madrugando e falando; mas vós não escutastes.

[[v24-25-4]]

^<<v24-25-4,4>>^ Também vos enviou o Senhor todos os seus servos, os profetas, madrugando e enviando- os  (mas vós não escutastes, nem inclinaste os vossos ouvidos para ouvir),

[[v24-25-5]]

^<<v24-25-5,5>>^ Dizendo: Convertei-vos agora cada um do seu mau caminho, e da maldade das suas ações, e habitai na terra que o Senhor vos deu e a vossos pais, de século em século;

[[v24-25-6]]

^<<v24-25-6,6>>^ E não andeis após deuses alheios para os servirdes, e para vos inclinardes diante deles, nem me provoqueis à ira com a obra de vossas mãos, para que vos não faça mal.

[[v24-25-7]]

^<<v24-25-7,7>>^ Todavia não me destes ouvidos, diz o Senhor, mas me provocastes à ira com a obra de vossas mãos, para vosso mal.

[[v24-25-8]]

^<<v24-25-8,8>>^ Portanto assim diz o Senhor dos Exércitos: Visto que não escutastes as minhas palavras.

[[v24-25-9]]

^<<v24-25-9,9>>^ Eis que eu enviarei, e tomarei a todas as gerações do norte, diz o Senhor, como também a Nabucodonosor, rei de Babilônia, meu servo, e os trarei sobre esta terra, e sobre os seus moradores, e sobre todas estas nações em redor, e os destruirei totalmente, e pô-los-ei em espanto, e em assobio, e em perpétuos desertos.

[[v24-25-10]]

^<<v24-25-10,10>>^ E farei perecer entre eles a voz de folguedo, e a voz de alegria, a voz do esposo, e a voz da esposa, o som das mós, e a luz do candeeiro.

[[v24-25-11]]

^<<v24-25-11,11>>^ E toda esta terra virá a ser um  deserto e um  espanto; e estas nações servirão ao rei de Babilônia setenta anos.

[[v24-25-12]]

^<<v24-25-12,12>>^ Acontecerá, porém, que, quando se cumprirem os setenta anos, visitarei o rei de Babilônia, e esta nação, diz o Senhor, castigando a sua iniquidade, e a da terra dos caldeus; farei deles uns  desertos perpétuos.

[[v24-25-13]]

^<<v24-25-13,13>>^ E trarei sobre esta terra todas as minhas palavras, que disse contra ela, tudo quanto está  escrito neste livro, que profetizou Jeremias contra todas estas nações.

[[v24-25-14]]

^<<v24-25-14,14>>^ Porque também deles se servirão muitas nações e grandes reis: assim lhes retribuirei segundo os seus feitos, e segundo as obras das suas mãos.

[[v24-25-15]]

^<<v24-25-15,15>>^ Porque assim me disse o Senhor, o Deus de Israel: Toma da minha mão este copo de vinho do furor, e darás a beber dele a todas as nações, às quais eu te enviar.

[[v24-25-16]]

^<<v24-25-16,16>>^ Para que bebam e tremam, e enlouqueçam, por causa da espada, que eu enviarei entre eles.

[[v24-25-17]]

^<<v24-25-17,17>>^ E tomei o copo da mão do Senhor, e dei a beber a todas as nações, às quais o Senhor me tinha enviado:

[[v24-25-18]]

^<<v24-25-18,18>>^ A Jerusalém, e às cidades de Judá, e aos seus reis, e aos seus príncipes, para fazer deles um deserto, um espanto, um assobio, e uma maldição, como hoje se vê :

[[v24-25-19]]

^<<v24-25-19,19>>^ A Faraó, rei do Egito, e a seus servos, e a seus príncipes, e a todo o seu povo;

[[v24-25-20]]

^<<v24-25-20,20>>^ E a toda a mistura de gente, e a todos os reis da terra de Uz, e a todos os reis da terra dos filisteus, e a Asquelom, e a Gaza, e a Ecrom, e ao resto de Asdode,

[[v24-25-21]]

^<<v24-25-21,21>>^ E  a Edom, e a Moabe, e aos filhos de Amom;

[[v24-25-22]]

^<<v24-25-22,22>>^ E a todos os reis de Tiro, e a todos os reis de Sidom; e aos reis das ilhas dalém do mar;

[[v24-25-23]]

^<<v24-25-23,23>>^ A Dedã, e a Tema, e a Buz e a todos os que habitam nos últimos cantos da terra ;

[[v24-25-24]]

^<<v24-25-24,24>>^ E a todos os reis da Arábia, e todos os reis do misturado povo que habita no deserto;

[[v24-25-25]]

^<<v24-25-25,25>>^ E a todos os reis de Zinri, e a todos os reis de Elão, e a todos os reis da Média:

[[v24-25-26]]

^<<v24-25-26,26>>^ E a todos os reis do norte, os de perto, e os de longe, um com outro, e a todos os reinos da terra, que estão sobre a face da terra, e o rei de Sesaque beberá depois deles.

[[v24-25-27]]

^<<v24-25-27,27>>^ Pois lhes dirás: Assim diz o Senhor dos Exércitos, o Deus de Israel: Bebei, e embebedai-vos, e vomitai, e caí, e não torneis a levantar-vos, por causa da espada que eu vos enviarei.

[[v24-25-28]]

^<<v24-25-28,28>>^ E será que, se não quiserem tomar o copo da tua mão para beber, então lhes dirás: Assim diz o Senhor dos Exércitos: Certamente bebereis.

[[v24-25-29]]

^<<v24-25-29,29>>^ Porque, eis que na cidade que se chama pelo meu nome começo a castigar; e ficareis vós totalmente impunes? não, não ficareis impunes, porque eu chamo a espada sobre todos os moradores da terra, diz o Senhor dos Exércitos.

[[v24-25-30]]

^<<v24-25-30,30>>^ Tu pois lhes profetizarás todas estas palavras, e lhes dirás: O Senhor desde o alto bramirá e fará ouvir a sua voz desde a morada da sua santidade: terrivelmente bramirá contra a sua habitação, com grito de alegria, como dos que pisam as uvas, contra todos os moradores da terra.

[[v24-25-31]]

^<<v24-25-31,31>>^ Chegará o estrondo até à extremidade da terra, porque o Senhor tem contenda com as nações, entrará em juízo com toda a carne: os ímpios entregará à espada, diz o Senhor.

[[v24-25-32]]

^<<v24-25-32,32>>^ Assim diz o Senhor dos Exércitos: Eis que o mal sai de nação para nação, e grande tormenta se levantará dos confins da terra.

[[v24-25-33]]

^<<v24-25-33,33>>^ E serão os mortos do Senhor, naquele dia, desde uma extremidade da terra até à outra  extremidade da terra: não serão pranteados, nem recolhidos, nem sepultados; mas  serão como estrume sobre a face da terra.

[[v24-25-34]]

^<<v24-25-34,34>>^ Uivai, pastores, e clamai, e rebolai-vos na cinza , principais do rebanho, porque já  se cumpriram os vossos dias para serdes mortos, e eu vos quebrantarei, e vós então caireis como um  vaso precioso.

[[v24-25-35]]

^<<v24-25-35,35>>^ E não haverá  fugida para os pastores, nem salvamento para os principais do rebanho.

[[v24-25-36]]

^<<v24-25-36,36>>^ Voz de grito dos pastores, e uivo dos principais do rebanho; porque o Senhor destruiu o pasto deles.

[[v24-25-37]]

^<<v24-25-37,37>>^ Porque as suas malhadas pacíficas serão desarraigadas, por causa do furor da ira do Senhor.

[[v24-25-38]]

^<<v24-25-38,38>>^ Desamparou a sua cabana, como o filho de leão; porque a sua terra foi posta  em assolação, por causa do furor do opressor, e por causa do furor da sua ira.

'''

xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[&#60; Capítulo Anterior] | <<v24-25-0,Topo>> | xref:024-jeremias/024-jeremias-026.adoc#v24-26-0[Próximo Capítulo &#62;]