include::./index.adoc[]

[[v24-48-0]]
=== Jeremias, 48
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-48-1]]

^<<v24-48-1,1>>^ CONTRA Moabe assim diz o Senhor dos Exércitos, Deus de Israel: Ai de Nebo, porque foi destruída: envergonhada está Quiriataim, já  é tomada: Misgabe está envergonhada e espantada.

[[v24-48-2]]

^<<v24-48-2,2>>^ A glória de Moabe não é mais; em Hesbom pensaram mal contra ela, dizendo : Vinde, e desarraiguemo-la, para que não seja mais  povo; também tu, ó Madmém, serás desarraigada; a espada te irá seguindo.

[[v24-48-3]]

^<<v24-48-3,3>>^ Voz de grito de Horonaim: ruína e grande destruição.

[[v24-48-4]]

^<<v24-48-4,4>>^ Está destruída Moabe: seus filhinhos fizeram ouvir gritos.

[[v24-48-5]]

^<<v24-48-5,5>>^ Porque pela subida de Luíte eles irão com choro contínuo; porque na descida de Horonaim os adversários de Moabe  ouviram um lastimoso clamor.

[[v24-48-6]]

^<<v24-48-6,6>>^ Fugi, salvai a vossa vida, e sereis como a tamargueira no deserto.

[[v24-48-7]]

^<<v24-48-7,7>>^ Porque, por causa da tua confiança nas tuas obras e nos teus tesouros, também tu serás tomada; e Camós sairá para o cativeiro, os seus sacerdotes e os seus príncipes juntamente.

[[v24-48-8]]

^<<v24-48-8,8>>^ Porque virá o destruidor sobre cada uma das cidades, e nenhuma escapará, e perecerá o vale, e destruir-se-á a campina; porque o Senhor o disse.

[[v24-48-9]]

^<<v24-48-9,9>>^ Dai asas a Moabe; porque voando sairá, e as suas cidades se tornarão em assolação, e ninguém morará nelas.

[[v24-48-10]]

^<<v24-48-10,10>>^ Maldito aquele que fizer a obra do Senhor fraudulentamente: e maldito aquele que preserva a sua espada do sangue.

[[v24-48-11]]

^<<v24-48-11,11>>^ Moabe esteve descansado desde a sua mocidade, e as suas fezes repousaram; não foi mudado de vaso para vaso, nem foi para o cativeiro; por isso conservou o seu sabor, e o seu cheiro não se alterou.

[[v24-48-12]]

^<<v24-48-12,12>>^ Portanto, eis que dias vêm, diz o Senhor, em que lhe enviarei derramadores que o farão andar a grandes passos; e despejarão os seus vasos, e romperão os seus odres.

[[v24-48-13]]

^<<v24-48-13,13>>^ E Moabe terá vergonha de Camós, como se envergonhou a casa de Israel de Betel, sua confiança.

[[v24-48-14]]

^<<v24-48-14,14>>^ Como direis: Somos valentes e homens fortes para guerra?

[[v24-48-15]]

^<<v24-48-15,15>>^ Moabe está destruída, e subiu das suas cidades, e os seus mancebos escolhidos desceram à matança diz o rei, cujo nome é o Senhor dos Exércitos.

[[v24-48-16]]

^<<v24-48-16,16>>^ Está prestes a vir a perdição de Moabe; e apressa-se muito o seu mal.

[[v24-48-17]]

^<<v24-48-17,17>>^ Condoei-vos dele todos os que estais em redor dele, e todos os que sabeis o seu nome; dizei: Como se quebrou a vara forte, o cajado formoso!

[[v24-48-18]]

^<<v24-48-18,18>>^ Desce da tua  glória, e assenta-te em seco, ó moradora, filha de Dibom; porque o destruidor de Moabe subiu contra ti, e desfez as tuas fortalezas.

[[v24-48-19]]

^<<v24-48-19,19>>^ Põe-te no caminho, e espia, ó moradora do Aroer: pergunta ao que vai fugindo; e à que escapou dize: Que sucedeu?

[[v24-48-20]]

^<<v24-48-20,20>>^ Moabe está envergonhado, porque foi quebrantado; uivai e gritai: anunciai em Arnom que Moabe está destruído.

[[v24-48-21]]

^<<v24-48-21,21>>^ Também o julgamento veio sobre a terra da campina: sobre Holom, e sobre Jaza, e sobre Mefaate,

[[v24-48-22]]

^<<v24-48-22,22>>^ E sobre Dibom e sobre Nebo, e sobre Bete-Diblataim,

[[v24-48-23]]

^<<v24-48-23,23>>^ E sobre Quiriataim, e sobre Bete-Gamul, e sobre Bete-Meom,

[[v24-48-24]]

^<<v24-48-24,24>>^ E sobre Queriote, e sobre Bozra; e até sobre todas as cidades da terra de Moabe, as de longe e as de perto.

[[v24-48-25]]

^<<v24-48-25,25>>^ Está cortado o poder de Moabe, e quebrantado o seu braço, diz o Senhor.

[[v24-48-26]]

^<<v24-48-26,26>>^ Embriagai-o, porque contra o Senhor se engrandeceu; e Moabe se revolverá no seu vômito, e será ele também um objeto de escárnio.

[[v24-48-27]]

^<<v24-48-27,27>>^ Pois não foi também Israel objeto de escárnio para ti? porventura  foi achado entre ladrões? por que então desde que falas dele te ris?

[[v24-48-28]]

^<<v24-48-28,28>>^ Deixai as cidades, e habitai no rochedo, ó moradores de Moabe; e sede como a pomba que se aninha nas extremidades da boca da caverna.

[[v24-48-29]]

^<<v24-48-29,29>>^ Ouvimos falar da soberba de Moabe, que é  soberbíssimo; da sua arrogância, e do seu orgulho, e da sua altivez e da altura do seu coração.

[[v24-48-30]]

^<<v24-48-30,30>>^ Eu conheço, diz o Senhor, a sua indignação, mas isso nada é: as suas mentiras nada farão.

[[v24-48-31]]

^<<v24-48-31,31>>^ Por isso gemerei por Moabe; sim, gritarei por todo o Moabe: pois os homens de Quir-Heres se lamentarão.

[[v24-48-32]]

^<<v24-48-32,32>>^ Com o choro de Jaezar chorar-te-ei, ó vide de Sibma; os teus ramos passaram o mar, chegaram até ao mar de Jazer; mas o destruidor caiu sobre os frutos do teu verão, e sobre a tua vindima.

[[v24-48-33]]

^<<v24-48-33,33>>^ Tirou-se pois o folguedo e a alegria do campo fértil e da terra de Moabe; porque fiz que o vinho acabasse nos lagares: já  não pisarão uvas  com júbilo: o júbilo não será júbilo.

[[v24-48-34]]

^<<v24-48-34,34>>^ Ouviu-se o grito de Hesbom até Eleale e  até Jaaz, e desde Zoar, até Horonaim, se ouviu a sua voz, como de bezerra de três anos; porque até as águas do Ninrim se tornarão em assolação.

[[v24-48-35]]

^<<v24-48-35,35>>^ E farei desaparecer de Moabe, diz o Senhor, quem sacrifique nos altos, e queime incenso aos seus deuses.

[[v24-48-36]]

^<<v24-48-36,36>>^ Por isso soará como frautas o meu coração por Moabe; e como frautas soará o meu coração pelos homens de Quir-Heres; porquanto a abundância que  ajuntou se perdeu.

[[v24-48-37]]

^<<v24-48-37,37>>^ Porque toda a cabeça ficará calva, e toda a barba diminuída; sobre todas as mãos haverá sarjaduras, e sobre os lombos sacos.

[[v24-48-38]]

^<<v24-48-38,38>>^ Sobre todos os telhados de Moabe e nas suas ruas haverá  um pranto geral; porque quebrei a Moabe, como a um vaso que não agrada, diz o Senhor.

[[v24-48-39]]

^<<v24-48-39,39>>^ Como está quebrantado! Como uivam! Como virou Moabe as costas e  se envergonhou! assim será Moabe objeto de escárnio e de espanto para todos os que estão  em redor dele.

[[v24-48-40]]

^<<v24-48-40,40>>^ Porque assim diz o Senhor: Eis que voará como a águia, e estenderá as suas asas sobre Moabe.

[[v24-48-41]]

^<<v24-48-41,41>>^ São tomadas as cidades, e ocupadas as fortalezas: e será  o coração dos valentes de Moabe naquele dia como o coração da mulher em suas dores.

[[v24-48-42]]

^<<v24-48-42,42>>^ E Moabe será destruído, para que não seja  povo; porque se engrandeceu contra o Senhor.

[[v24-48-43]]

^<<v24-48-43,43>>^ Temor, e cova, e laço, vêm  sobre ti, ó morador de Moabe, diz o Senhor.

[[v24-48-44]]

^<<v24-48-44,44>>^ O que fugir do temor cairá na cova, e o que sair da cova ficará preso no laço; porque trarei sobre ele, sobre Moabe, o ano da sua visitação, diz o Senhor.

[[v24-48-45]]

^<<v24-48-45,45>>^ Os que fugiam ficaram sem força e pararam à sombra de Hesbom; mas fogo saiu de Hesbom, e a labareda do meio de Siom, e devorou o canto de Moabe e o poder dos turbulentos.

[[v24-48-46]]

^<<v24-48-46,46>>^ Ai de ti, Moabe; pereceu o povo de Camós; porque teus filhos ficaram cativos, e tuas filhas em cativeiro.

[[v24-48-47]]

^<<v24-48-47,47>>^ Mas farei voltar os cativos de Moabe no último dos dias, diz o Senhor. Até aqui o juízo de Moabe.

'''

xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[&#60; Capítulo Anterior] | <<v24-48-0,Topo>> | xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[Próximo Capítulo &#62;]