include::./index.adoc[]

[[v24-43-0]]
=== Jeremias, 43
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-43-1]]

^<<v24-43-1,1>>^ E SUCEDEU que, acabando Jeremias de anunciar a todo o povo todas as palavras do Senhor Deus deles, com as quais o Senhor Deus deles o havia enviado, e que foram todas aquelas palavras,

[[v24-43-2]]

^<<v24-43-2,2>>^ Então falou Azarias, filho de Hosaías, e Joanã, filho de Careá, e todos os homens soberbos, dizendo a Jeremias: Tu dizes mentiras; o Senhor nosso Deus não te enviou a dizer: Não entreis no Egito, para lá peregrinardes;

[[v24-43-3]]

^<<v24-43-3,3>>^ Baruque, filho de Nérias, é que te incita contra nós, para nos entregar na mão dos caldeus, para eles nos matarem, ou para nos transportarem para  Babilônia.

[[v24-43-4]]

^<<v24-43-4,4>>^ Não obedeceu pois Joanã, filho de Careá, nem nenhum de todos os príncipes dos exércitos, nem o povo todo, à  voz do Senhor, para ficarem na terra de Judá.

[[v24-43-5]]

^<<v24-43-5,5>>^ Antes tomou Joanã, filho de Careá, e todos os príncipes dos exércitos a todo o resto de Judá, que havia voltado dentre todas as nações, para onde haviam sido lançados com o fim de peregrinarem na terra de Judá;

[[v24-43-6]]

^<<v24-43-6,6>>^ Aos homens, e às mulheres, e aos meninos, e às filhas do rei, e a toda a alma que deixara Nebuzaradão, capitão da guarda, com Gedalias, filho de Aicão, filho de Safã; como também a Jeremias, o profeta, e a Baruque, filho de Nérias:

[[v24-43-7]]

^<<v24-43-7,7>>^ E entraram na terra do Egito, porque não obedeceram à voz do Senhor; e vieram até Tafnes.

[[v24-43-8]]

^<<v24-43-8,8>>^ Então veio a palavra do Senhor a Jeremias, em Tafnes, dizendo:

[[v24-43-9]]

^<<v24-43-9,9>>^ Toma na tua mão pedras grandes, e esconde-as entre o barro no forno que está  à porta da casa de Faraó em Tafnes, perante os olhos de homens judeus.

[[v24-43-10]]

^<<v24-43-10,10>>^ E dize-lhes: Assim diz o Senhor dos Exércitos, Deus de Israel: Eis que eu enviarei, e tomarei a Nabucodonosor, rei de Babilônia, meu servo, e porei o seu trono sobre estas pedras que escondi; e ele estenderá a sua tenda real sobre elas.

[[v24-43-11]]

^<<v24-43-11,11>>^ E virá, e ferirá a terra do Egito: quem para a morte, para a morte; e quem para o cativeiro, para o cativeiro; e quem para a espada, para a espada.

[[v24-43-12]]

^<<v24-43-12,12>>^ E lançarei fogo às casas dos deuses do Egito, e ele queimá-los-á, e levá-los-á cativos; e ornar-se-á da terra do Egito, como veste o pastor seu vestido, e sairá dali em paz.

[[v24-43-13]]

^<<v24-43-13,13>>^ E quebrará as estátuas de Bete-Semes, que está  na terra do Egito; e as casas dos deuses do Egito queimará a fogo.

'''

xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[&#60; Capítulo Anterior] | <<v24-43-0,Topo>> | xref:024-jeremias/024-jeremias-044.adoc#v24-44-0[Próximo Capítulo &#62;]