include::./index.adoc[]

[[v24-3-0]]
=== Jeremias, 3
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-3-1]]

^<<v24-3-1,1>>^ ELES dizem: Se um homem despedir sua mulher, e ela se ausentar dele, e se ajuntar a outro homem, porventura  tornará a ela mais? não se poluiria de todo aquela terra? Ora, tu te maculaste com  muitos amantes; mas ainda assim, torna para mim, diz o Senhor.

[[v24-3-2]]

^<<v24-3-2,2>>^ Levanta os teus olhos aos altos, e vê: onde não te prostituíste? nos caminhos te assentavas para eles, como o árabe no deserto: assim manchaste a terra com as tuas devassidões e com a tua malícia.

[[v24-3-3]]

^<<v24-3-3,3>>^ Pelo que foram retiradas as chuvas, e não houve chuva tardia; mas tu tens a testa de uma prostituta, e  não queres ter vergonha.

[[v24-3-4]]

^<<v24-3-4,4>>^ Ao menos desde agora não me invocarás, dizendo : Pai meu, tu és  o guia da minha mocidade?

[[v24-3-5]]

^<<v24-3-5,5>>^ Conservará ele para sempre a  sua ira ? ou a  guardará continuamente? Eis que tens dito e feito cousas más, e nelas permaneces.

[[v24-3-6]]

^<<v24-3-6,6>>^ Disse mais o Senhor nos dias do rei Josias: Viste o que fez a rebelde Israel? ela foi-se a todo o monte alto, e debaixo de toda a árvore verde, e ali andou prostituindo-se.

[[v24-3-7]]

^<<v24-3-7,7>>^ E eu disse, depois que fez tudo isto: Volta para mim; mas não voltou: e viu isto  a sua aleivosa irmã Judá.

[[v24-3-8]]

^<<v24-3-8,8>>^ E vi, quando por causa de tudo isto, por ter cometido adultério a rebelde Israel, a despedi, e lhe dei o seu libelo de divórcio, que a aleivosa Judá, sua irmã, não temeu; mas foi-se e também ela mesma se prostituiu.

[[v24-3-9]]

^<<v24-3-9,9>>^ E sucedeu que pela fama da sua prostituição contaminou a terra; porque adulterou com a pedra e com o pau.

[[v24-3-10]]

^<<v24-3-10,10>>^ E, contudo, nem por tudo isso voltou para mim a sua aleivosa irmã Judá com sincero coração, mas falsamente, diz o Senhor.

[[v24-3-11]]

^<<v24-3-11,11>>^ E o Senhor me disse: Já  a rebelde Israel justificou mais a sua alma do que a aleivosa Judá.

[[v24-3-12]]

^<<v24-3-12,12>>^ Vai, pois , e apregoa estas palavras para a banda do norte, e dize: Volta, ó rebelde Israel, diz o Senhor, e  não farei cair a minha ira sobre vós; porque benigno sou, diz o Senhor, e  não conservarei para sempre a minha ira.

[[v24-3-13]]

^<<v24-3-13,13>>^ Somente reconhece a tua iniquidade: que contra o Senhor teu Deus transgrediste, e estendeste os teus caminhos aos estranhos, debaixo de toda a árvore verde; e não deste ouvidos à minha voz, diz o Senhor.

[[v24-3-14]]

^<<v24-3-14,14>>^ Convertei-vos, ó filhos rebeldes, diz o Senhor; porque eu vos desposarei, e vos tomarei, a um de uma cidade, e a dois de uma geração; e vos levarei a Sião.

[[v24-3-15]]

^<<v24-3-15,15>>^ E vos darei pastores segundo o meu coração, que vos apascentem com  ciência e com  inteligência.

[[v24-3-16]]

^<<v24-3-16,16>>^ E sucederá que, quando vos multiplicardes e frutificardes na terra, naqueles dias, diz o Senhor, nunca mais se dirá: A arca do concerto do Senhor, nem lhes  virá ao coração, nem dela se lembrarão, nem a  visitarão; isto não se fará mais.

[[v24-3-17]]

^<<v24-3-17,17>>^ Naquele tempo chamarão a Jerusalém o trono do Senhor, e todas as nações se ajuntarão a ela, ao nome do Senhor, a Jerusalém; e nunca mais andarão segundo o propósito do seu coração maligno.

[[v24-3-18]]

^<<v24-3-18,18>>^ Naqueles dias andará a casa de Judá com a casa de Israel; e virão juntas da terra do norte, para a terra que dei em herança a vossos pais.

[[v24-3-19]]

^<<v24-3-19,19>>^ Mas eu dizia: Como te porei entre os filhos, e te darei a terra desejável, a excelente herança dos exércitos das nações? E eu disse: Pai me chamarás, e de mim te não desviarás.

[[v24-3-20]]

^<<v24-3-20,20>>^ Deveras, como  a mulher se aparta aleivosamente do seu companheiro, assim aleivosamente te houveste comigo, ó casa de Israel, diz o Senhor.

[[v24-3-21]]

^<<v24-3-21,21>>^ Nos lugares altos se ouviu uma voz, pranto e  súplicas dos filhos de Israel; porquanto perverteram o seu caminho, e  se esqueceram do Senhor seu Deus.

[[v24-3-22]]

^<<v24-3-22,22>>^ Voltai, ó filhos rebeldes, eu curarei as vossas rebeliões. Eis-nos aqui, vimos a ti; porque tu és  o Senhor nosso Deus.

[[v24-3-23]]

^<<v24-3-23,23>>^ Certamente em vão se confia  nos outeiros e  na multidão das montanhas: deveras no Senhor nosso Deus está  a salvação de Israel.

[[v24-3-24]]

^<<v24-3-24,24>>^ Porque a confusão devorou o trabalho de nossos pais desde a nossa mocidade: as suas ovelhas e as suas vacas, os seus filhos e as suas filhas.

[[v24-3-25]]

^<<v24-3-25,25>>^ Jazemos na nossa vergonha; e estamos cobertos da nossa confusão, porque pecamos contra o Senhor nosso Deus, nós e nossos pais, desde a nossa mocidade até o dia de hoje, e não demos ouvidos à voz do Senhor nosso Deus.

'''

xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[Próximo Capítulo &#62;]