include::./index.adoc[]

[[v24-15-0]]
=== Jeremias, 15
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-15-1]]

^<<v24-15-1,1>>^ DISSE-ME, porém, o Senhor: Ainda que Moisés e Samuel se pusessem diante de mim, não seria  a minha alma com este povo: lança-os de diante da minha face, e saiam.

[[v24-15-2]]

^<<v24-15-2,2>>^ E será que, quando te disserem: Para onde iremos? dir-lhes-ás: Assim diz o Senhor: Os que para a morte, para a morte; e os que para a espada, para a espada; e os que para a fome, para a fome; e os que para o cativeiro, para o cativeiro.

[[v24-15-3]]

^<<v24-15-3,3>>^ Porque os visitarei com  quatro gêneros de males , diz o Senhor: com espada para matar, e com cães, para os arrastarem, e com as aves dos céus, e os animais da terra, para os devorarem e destruírem.

[[v24-15-4]]

^<<v24-15-4,4>>^ Entregá-los-ei ao desterro em todos os reinos da terra; por causa de Manassés, filho de Ezequias, rei de Judá, por tudo quanto fez em Jerusalém.

[[v24-15-5]]

^<<v24-15-5,5>>^ Porque quem se compadeceria de ti, ó Jerusalém? ou quem se entristeceria por ti? ou quem se desviaria a perguntar pela tua paz?

[[v24-15-6]]

^<<v24-15-6,6>>^ Tu me deixaste, diz o Senhor, voltaste para trás; por isso estenderei a minha mão contra ti, e te destruirei; estou cansado de me arrepender.

[[v24-15-7]]

^<<v24-15-7,7>>^ E padejá-los-ei com a pá nas portas da terra: desfilhei, destruí o meu povo; não voltaram dos seus caminhos.

[[v24-15-8]]

^<<v24-15-8,8>>^ As suas viúvas mais se multiplicaram do que as areias dos mares; trouxe ao meio-dia um destruidor sobre a mãe dos mancebos; fiz que caísse de repente sobre ela, e enchesse a cidade de terrores.

[[v24-15-9]]

^<<v24-15-9,9>>^ A que dava à luz sete se enfraqueceu; expirou a sua alma; pôs-se o seu sol sendo ainda de dia; ela confundiu-se, e envergonhou-se: e os que ficarem dela eu os entregarei à espada, diante dos seus inimigos, diz o Senhor.

[[v24-15-10]]

^<<v24-15-10,10>>^ Ai de mim, minha mãe! porque me deste à luz homem de rixa e homem de contenda para toda a terra? nunca lhes  emprestei com usura, nem eles me emprestaram a mim com usura, e todavia cada um deles me amaldiçoa.

[[v24-15-11]]

^<<v24-15-11,11>>^ Disse o Senhor: Decerto que te fortalecerei para bem, e, no tempo da calamidade e no tempo da angústia, farei que o inimigo te dirija súplicas.

[[v24-15-12]]

^<<v24-15-12,12>>^ Pode alguém quebrar o ferro, o ferro do norte, ou o aço?

[[v24-15-13]]

^<<v24-15-13,13>>^ A tua fazenda e os teus tesouros entregarei sem preço ao saque; e isso  por todos os teus pecados, mesmo em todos os teus limites.

[[v24-15-14]]

^<<v24-15-14,14>>^ E levar- te- ei com os teus inimigos para a terra que não conheces; porque o fogo se acendeu em minha ira, e  sobre vós arderá.

[[v24-15-15]]

^<<v24-15-15,15>>^ Tu, ó Senhor, o  sabes: lembra-te de mim, e visita-me, e vinga-me dos meus perseguidores: não me arrebates, por tua longanimidade: sabe que por amor de ti tenho sofrido afronta.

[[v24-15-16]]

^<<v24-15-16,16>>^ Achando-se as tuas palavras, logo as comi, e a tua palavra foi para mim o gozo e alegria do meu coração; porque pelo teu nome me chamo, ó Senhor, Deus dos Exércitos.

[[v24-15-17]]

^<<v24-15-17,17>>^ Nunca me assentei no congresso dos zombadores, nem me regozijei; por causa da tua mão me assentei solitário: pois me encheste de indignação.

[[v24-15-18]]

^<<v24-15-18,18>>^ Por que dura a minha dor continuamente, e a minha ferida me dói, não admite cura? Serias tu para mim como ilusório ribeiro e  como águas inconstantes?

[[v24-15-19]]

^<<v24-15-19,19>>^ Portanto assim diz o Senhor: Se tu voltares, então te trarei, e  estarás diante da minha face; e se apartares o precioso do vil, serás como a minha boca; tornem-se eles para ti, mas não voltes tu para eles.

[[v24-15-20]]

^<<v24-15-20,20>>^ E eu te porei contra este povo como forte muro de bronze; e pelejarão contra ti, mas não prevalecerão contra ti: porque eu sou contigo para te guardar, para te livrar deles , diz o Senhor.

[[v24-15-21]]

^<<v24-15-21,21>>^ E arrebatar-te-ei da mão dos malignos, e livrar-te-ei das mãos dos fortes.

'''

xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[&#60; Capítulo Anterior] | <<v24-15-0,Topo>> | xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[Próximo Capítulo &#62;]