include::./index.adoc[]

[[v24-51-0]]
=== Jeremias, 51
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-51-1]]

^<<v24-51-1,1>>^ ASSIM diz o Senhor: Eis que levantarei um vento destruidor contra Babilônia, e contra os que habitam no coração dos que se levantam contra mim.

[[v24-51-2]]

^<<v24-51-2,2>>^ E enviarei padejadores contra Babilônia, que a padejarão, e despejarão a sua terra: porque virão contra ela em redor no dia da calamidade.

[[v24-51-3]]

^<<v24-51-3,3>>^ O frecheiro arme o seu arco contra o que arma o seu arco , e contra o que presume da sua couraça; e não perdoeis a seus mancebos: destruí a todo o seu exército.

[[v24-51-4]]

^<<v24-51-4,4>>^ E mortos cairão na terra dos caldeus, e atravessados pelas ruas.

[[v24-51-5]]

^<<v24-51-5,5>>^ Porque Israel e Judá não foram abandonados do seu Deus, do Senhor dos Exércitos, ainda que a sua terra esteja cheia de culpas perante o Santo de Israel.

[[v24-51-6]]

^<<v24-51-6,6>>^ Fugi do meio de Babilônia, e livre cada um a sua alma; não vos destruais a vós na sua maldade: porque este é o tempo da vingança do Senhor; ele lhe dará a sua recompensa.

[[v24-51-7]]

^<<v24-51-7,7>>^ Babilônia era um copo de ouro na mão do Senhor, o qual embriagava a toda a terra: do seu vinho beberam as nações; por isso as nações enlouqueceram.

[[v24-51-8]]

^<<v24-51-8,8>>^ Num momento caiu Babilônia, e ficou arruinada: gemei sobre ela, tomai bálsamo para a sua dor, porventura sarará.

[[v24-51-9]]

^<<v24-51-9,9>>^ Queríamos sarar Babilônia, mas ela não sarou; deixai-a, e vá cada um para a sua terra: porque o seu juízo chegou até ao céu, e se elevou até às mais altas nuvens.

[[v24-51-10]]

^<<v24-51-10,10>>^ O Senhor trouxe a nossa justiça à luz: vinde e contemos em Sião a obra do Senhor, nosso Deus.

[[v24-51-11]]

^<<v24-51-11,11>>^ Alimpai as frechas, preparai perfeitamente os escudos: o Senhor despertou o espírito dos reis da Média; porque o seu intento contra Babilônia é  para a destruir; pois esta é  a vingança do Senhor, a vingança do seu templo.

[[v24-51-12]]

^<<v24-51-12,12>>^ Arvorai um estandarte sobre os muros de Babilônia, reforçai a guarda, colocai sentinelas, preparai as ciladas; porque o Senhor intentou e fez o que tinha dito acerca dos moradores de Babilônia.

[[v24-51-13]]

^<<v24-51-13,13>>^ Ó tu, que habitas sobre muitas águas, rica de tesouros! chegou o teu fim, a medida da tua avareza.

[[v24-51-14]]

^<<v24-51-14,14>>^ Jurou o Senhor dos Exércitos por si mesmo, dizendo: Certamente te encherei de homens, como de  pulgão, e eles cantarão com júbilo sobre ti.

[[v24-51-15]]

^<<v24-51-15,15>>^ Ele fez a terra com o seu poder, e ordenou o mundo com a sua sabedoria, e estendeu os céus com o seu entendimento.

[[v24-51-16]]

^<<v24-51-16,16>>^ Fazendo ele ouvir a sua voz, grande estrondo de águas há  nos céus, e sobem os vapores desde o fim da terra: faz os relâmpagos com a chuva, e tira o vento dos seus tesouros.

[[v24-51-17]]

^<<v24-51-17,17>>^ Embruteceu-se todo o homem, e não tem ciência; envergonhou-se todo o ourives de imagem de escultura; porque a sua imagem de fundição é mentira, e não há  espírito em nenhuma delas.

[[v24-51-18]]

^<<v24-51-18,18>>^ Vaidade são  obra de enganos: no tempo em que eu as visitar perecerão.

[[v24-51-19]]

^<<v24-51-19,19>>^ Não é  semelhante a estes a porção de Jacó; porque ele é  o criador de todas as cousas; e Israel é  a tribo da sua herança: o Senhor dos Exércitos é  o seu nome.

[[v24-51-20]]

^<<v24-51-20,20>>^ Tu és meu martelo e minhas armas de guerra, e contigo despedaçarei nações, e contigo destruirei os reis;

[[v24-51-21]]

^<<v24-51-21,21>>^ E contigo despedaçarei o cavalo e o seu cavaleiro; e contigo despedaçarei o carro e o que vai nele;

[[v24-51-22]]

^<<v24-51-22,22>>^ E contigo despedaçarei o homem e a mulher, e contigo despedaçarei o velho e o moço; e contigo despedaçarei o mancebo e a virgem;

[[v24-51-23]]

^<<v24-51-23,23>>^ E contigo despedaçarei o pastor e o seu rebanho; e contigo despedaçarei o lavrador e a sua junta de bois : e contigo despedaçarei os capitães e os magistrados.

[[v24-51-24]]

^<<v24-51-24,24>>^ E pagarei a Babilônia, e a todos os moradores da Caldeia, toda a sua maldade, que fizeram em Sião, à vossa vista, diz o Senhor.

[[v24-51-25]]

^<<v24-51-25,25>>^ Eis-me aqui contra ti, ó monte destruidor, diz o Senhor, que destróis toda a terra; e estenderei a minha mão contra ti e te revolverei das rochas, e farei de ti um  monte de incêndio.

[[v24-51-26]]

^<<v24-51-26,26>>^ E não tomarão de ti pedra para esquina, nem pedra para fundamentos, porque te tornarás numa assolação perpétua, diz o Senhor.

[[v24-51-27]]

^<<v24-51-27,27>>^ Arvorai um estandarte na terra, tocai a buzina entre as nações, santificai as nações contra ela, convocai contra ela os reinos de Arará, Mini, e Asquenaz: ordenai contra ela um  capitão, fazei subir cavalos, como pulgão agitado.

[[v24-51-28]]

^<<v24-51-28,28>>^ Santificai contra ela as nações, os reis da Média, os seus capitães, e todos os seus magistrados, e toda a terra do seu domínio.

[[v24-51-29]]

^<<v24-51-29,29>>^ Então tremerá a terra, e doer-se-á porque cada um dos desígnios do Senhor está firme contra Babilônia, para fazer da terra de Babilônia uma  assolação, sem habitantes.

[[v24-51-30]]

^<<v24-51-30,30>>^ Os valentes de Babilônia cessaram de pelejar, ficaram nas fortalezas, desfaleceu a sua força, tornaram-se como mulheres: incendiaram as suas moradas, quebrados foram os seus ferrolhos.

[[v24-51-31]]

^<<v24-51-31,31>>^ Um correio correrá ao encontro de outro  correio, e um mensageiro ao encontro de outro  mensageiro, para anunciar ao rei de Babilônia que a sua cidade foi tomada de todos os lados.

[[v24-51-32]]

^<<v24-51-32,32>>^ E os vaus estão ocupados, e os canaviais queimados a fogo; e os homens de guerra ficaram assombrados.

[[v24-51-33]]

^<<v24-51-33,33>>^ Porque assim diz o Senhor dos Exércitos, o Deus de Israel: A filha de Babilônia é  como uma  eira no tempo da debulha: ainda um pouco, e o tempo da sega lhe virá.

[[v24-51-34]]

^<<v24-51-34,34>>^ Nabucodonosor, rei de Babilônia, me devorou, pisou-me, fez de mim um vaso vazio, como dragão me tragou, encheu o seu ventre das minhas delicadezas; lançou-me fora.

[[v24-51-35]]

^<<v24-51-35,35>>^ A violência que se me fez a mim e à minha carne venha  sobre Babilônia, diga a moradora de Sião; e o meu sangue caia sobre os moradores da Caldeia, diga Jerusalém.

[[v24-51-36]]

^<<v24-51-36,36>>^ Pelo que assim diz o Senhor: Eis que pleitearei a tua causa, e te vingarei da vingança que se tomou contra ti; e secarei o seu mar, e farei que se esgote o seu manancial.

[[v24-51-37]]

^<<v24-51-37,37>>^ E Babilônia se tornará em montões, morada de dragões, espanto e assobio, sem um só habitante.

[[v24-51-38]]

^<<v24-51-38,38>>^ Juntamente rugirão como filhos dos leões: bramarão como cachorros de leões.

[[v24-51-39]]

^<<v24-51-39,39>>^ Estando eles excitados, lhes darei a sua bebida, e os embriagarei, para que andem saltando; mas dormirão um  perpétuo sono, e não acordarão, diz o Senhor.

[[v24-51-40]]

^<<v24-51-40,40>>^ Fá-los-ei descer como cordeiros ao matadouro, como carneiros com os bodes.

[[v24-51-41]]

^<<v24-51-41,41>>^ Como foi tomada Sesaque, e apanhada de surpresa a glória de toda a terra! como se tornou Babilônia um espanto entre as nações!

[[v24-51-42]]

^<<v24-51-42,42>>^ O mar subiu sobre Babilônia, com a multidão das suas ondas se cobriu.

[[v24-51-43]]

^<<v24-51-43,43>>^ Tornaram-se as suas cidades em assolação, terra seca e deserta, terra em que ninguém habita, nem passa por ela filho de homem.

[[v24-51-44]]

^<<v24-51-44,44>>^ E visitarei a Bel em Babilônia, e tirarei da sua boca o que ele tragou, e nunca mais concorrerão a ele as nações: também o muro de Babilônia caiu.

[[v24-51-45]]

^<<v24-51-45,45>>^ Saí do meio dela, ó povo meu, e livre cada um a sua alma, por causa do ardor da ira do Senhor.

[[v24-51-46]]

^<<v24-51-46,46>>^ E não se enterneça o vosso coração, nem temais pelo rumor que se ouvir na terra; porque virá num ano um rumor, e depois noutro ano outro rumor; e haverá  violência na terra, dominador contra dominador.

[[v24-51-47]]

^<<v24-51-47,47>>^ Portanto, eis que vêm dias, em que visitarei as imagens de escultura de Babilônia, e toda a sua terra será envergonhada, e todos os seus traspassados cairão no meio dela.

[[v24-51-48]]

^<<v24-51-48,48>>^ E os céus e a terra, com tudo quanto neles há , jubilarão sobre Babilônia: porque do norte lhe virão os destruidores, diz o Senhor.

[[v24-51-49]]

^<<v24-51-49,49>>^ Como Babilônia fez cair os traspassados de Israel, assim em Babilônia cairão os traspassados de toda a terra.

[[v24-51-50]]

^<<v24-51-50,50>>^ Vós, que escapastes da espada, ide-vos, não pareis; de longe lembrai-vos do Senhor, e suba Jerusalém ao vosso coração.

[[v24-51-51]]

^<<v24-51-51,51>>^ Direis : Envergonhados estamos, porque ouvimos opróbrio; vergonha cobriu o nosso rosto, porque vieram estrangeiros sobre os santuários da casa do Senhor.

[[v24-51-52]]

^<<v24-51-52,52>>^ Portanto, eis que vêm dias, diz o Senhor, em que visitarei as suas imagens de escultura; e gemerá o traspassado em toda a sua terra.

[[v24-51-53]]

^<<v24-51-53,53>>^ Ainda que Babilônia subisse aos céus, e ainda que fortificasse a altura da sua fortaleza, de mim viriam destruidores sobre ela, diz o Senhor.

[[v24-51-54]]

^<<v24-51-54,54>>^ O som de um clamor se ouve  de Babilônia, e de grande destruição da terra dos Caldeus;

[[v24-51-55]]

^<<v24-51-55,55>>^ Porque o Senhor destrói Babilônia, e fará perecer nela a sua  grande voz; e as suas ondas bramirão como muitas águas: ouvir-se-á o arruído da sua voz.

[[v24-51-56]]

^<<v24-51-56,56>>^ Porque o destruidor vem sobre ela, sobre Babilônia e os seus valentes serão presos, já  estão quebrados os seus arcos: porque o Senhor, Deus das recompensas, certamente lhe retribuirá.

[[v24-51-57]]

^<<v24-51-57,57>>^ E embriagarei os seus príncipes, e os seus sábios, e os seus capitães, e os seus magistrados, e os seus valentes; e dormirão um  sono perpétuo, e não acordarão, diz o Rei, cujo nome é  o Senhor dos Exércitos.

[[v24-51-58]]

^<<v24-51-58,58>>^ Assim diz o Senhor dos Exércitos: Os largos muros de Babilônia totalmente serão derribados, e as suas portas excelsas serão abrasadas pelo fogo; e trabalharão os povos em vão, e as nações serão para o fogo, e cansar-se-ão.

[[v24-51-59]]

^<<v24-51-59,59>>^ A palavra que mandou Jeremias, o profeta, a Seraías, filho de Nérias, filho de Maaseias, indo ele com Zedequias, rei de Judá a Babilônia, no ano quarto do seu reinado; e Seraías era  um príncipe pacífico.

[[v24-51-60]]

^<<v24-51-60,60>>^ Escreveu pois Jeremias num  livro todo o mal que havia de vir sobre Babilônia: todas estas palavras que estavam escritas contra Babilônia.

[[v24-51-61]]

^<<v24-51-61,61>>^ E disse Jeremias a Seraías: Em tu chegando a Babilônia, verás e lerás todas estas palavras.

[[v24-51-62]]

^<<v24-51-62,62>>^ E dirás: Senhor! tu falaste a respeito deste lugar, que o havias de desarraigar, até não ficar nele morador algum, desde o homem até ao animal, mas que se tornaria em  perpétuas assolações.

[[v24-51-63]]

^<<v24-51-63,63>>^ E será  que, acabando tu de ler este livro, o atarás a uma pedra e o lançarás no meio do Eufrates.

[[v24-51-64]]

^<<v24-51-64,64>>^ E dirás: Assim será afundada Babilônia, e não se levantará, por causa do mal que eu hei de trazer sobre ela; eles se cansarão. Até aqui as palavras de Jeremias.

'''

xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[&#60; Capítulo Anterior] | <<v24-51-0,Topo>> | xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[Próximo Capítulo &#62;]