include::./index.adoc[]

[[v24-52-0]]
=== Jeremias, 52
// rc69 ?, RC69 - Almeida Revista e Corrigida 1969

[[v24-52-1]]

^<<v24-52-1,1>>^ ERA Zedequias da idade de vinte e um anos quando começou a reinar, e reinou onze anos em Jerusalém: e o nome de sua mãe era Hamutal, filha de Jeremias, de Libna.

[[v24-52-2]]

^<<v24-52-2,2>>^ E fez o que era mau aos olhos do Senhor, conforme tudo o que fizera Joaquim.

[[v24-52-3]]

^<<v24-52-3,3>>^ Por esta razão sucedeu que, por causa da ira do Senhor contra Jerusalém e Judá, ele os lançou fora da sua presença; e Zedequias se rebelou contra o rei de Babilônia.

[[v24-52-4]]

^<<v24-52-4,4>>^ E aconteceu, no ano nono do seu reinado, no mês décimo, no décimo dia do mês, que veio Nabucodonosor, rei de Babilônia, contra Jerusalém, ele e todo o seu exército, e se acamparam contra ela, e levantaram contra ela tranqueiras ao redor.

[[v24-52-5]]

^<<v24-52-5,5>>^ Assim esteve cercada a cidade, até ao ano undécimo do rei Zedequias.

[[v24-52-6]]

^<<v24-52-6,6>>^ No mês quarto, aos nove do mês, quando a fome prevalecia na cidade, e o povo da terra não tinha pão,

[[v24-52-7]]

^<<v24-52-7,7>>^ Foi aberta uma brecha na cidade, e todos os homens de guerra fugiram, e saíram de noite, pelo caminho da porta, entre os dois muros que estavam  junto ao jardim do rei (porque os caldeus estavam contra a cidade ao redor), e foram pelo  caminho da campina.

[[v24-52-8]]

^<<v24-52-8,8>>^ Mas o exército dos caldeus seguiu o rei, e alcançaram Zedequias nas campinas de Jericó, e todo o seu exército se espalhou, abandonando-o.

[[v24-52-9]]

^<<v24-52-9,9>>^ E prenderam o rei, e o fizeram subir ao rei de Babilônia, a Ribla, na terra de Hamate, o qual lhe lavrou ali a sentença.

[[v24-52-10]]

^<<v24-52-10,10>>^ E o rei de Babilônia degolou os filhos de Zedequias à sua vista, e também degolou a todos os príncipes de Judá em Ribla.

[[v24-52-11]]

^<<v24-52-11,11>>^ E arrancou os olhos a Zedequias, e o atou com duas cadeias de bronze; e o rei de Babilônia o levou para Babilônia, e o conservou na prisão até o dia da sua morte.

[[v24-52-12]]

^<<v24-52-12,12>>^ E no quinto mês, no décimo dia  do mês (este era  o décimo nono ano do rei Nabucodonosor, rei de Babilônia), veio Nebuzaradão, capitão da guarda, que  assistia na presença do rei de Babilônia, a Jerusalém.

[[v24-52-13]]

^<<v24-52-13,13>>^ E queimou a casa do Senhor, e a casa do rei; e também a todas as casas de Jerusalém, e incendiou todas as casas dos grandes.

[[v24-52-14]]

^<<v24-52-14,14>>^ E todo o exército dos caldeus, que estavam  com o capitão da guarda, derribou todos os muros que rodeavam Jerusalém.

[[v24-52-15]]

^<<v24-52-15,15>>^ E os mais pobres do povo, e a parte do povo que tinha ficado na cidade, e os rebeldes que se haviam passado para o rei de Babilônia, e o resto da multidão, Nebuzaradão, capitão da guarda, levou presos.

[[v24-52-16]]

^<<v24-52-16,16>>^ Mas dos mais pobres da terra deixou Nebuzaradão, capitão da guarda, ficar alguns , para serem  vinhateiros e lavradores.

[[v24-52-17]]

^<<v24-52-17,17>>^ Quebraram mais os caldeus as colunas de bronze, que estavam  na casa do Senhor, e as bases, e o mar de bronze, que estavam  na casa do Senhor, e levaram todo o bronze para Babilônia.

[[v24-52-18]]

^<<v24-52-18,18>>^ Também tomaram os caldeirões, e as pás, e os garfos, e as bacias, e os perfumadores, e todos os vasos de bronze, com que se ministrava.

[[v24-52-19]]

^<<v24-52-19,19>>^ E tomou o capitão da guarda os copos, e os incensários, e as bacias, e os caldeirões e os castiçais, e os perfumadores, e as galhetas: tanto o que era  de puro ouro, como o que era  de prata maciça.

[[v24-52-20]]

^<<v24-52-20,20>>^ As duas colunas, o único mar, e os doze bois de bronze, que estavam  no lugar das bases, que fizera o rei Salomão para a casa do Senhor: o bronze de todos estes vasos era sem peso.

[[v24-52-21]]

^<<v24-52-21,21>>^ Quanto às colunas, a altura de uma coluna era  de dezoito côvados, e um fio de doze côvados a cercava; e era  a sua espessura de quatro dedos, e era  oca.

[[v24-52-22]]

^<<v24-52-22,22>>^ E havia sobre ela um capitel de bronze, e altura do capitel era  de cinco côvados, e a rede e as romãs em roda do capitel tudo era  de bronze; e semelhante a esta era  a outra coluna, com as romãs.

[[v24-52-23]]

^<<v24-52-23,23>>^ E havia noventa e seis romãs em cada banda: as romãs todas eram  um cento, em roda da rede.

[[v24-52-24]]

^<<v24-52-24,24>>^ Levou também o capitão da guarda a Seraías, o sacerdote primeiro, e a Sofonias, o sacerdote segundo, e aos três guardas do umbral da porta.

[[v24-52-25]]

^<<v24-52-25,25>>^ E da cidade levou um eunuco que tinha a seu cargo a gente de guerra; e a sete homens dos que viam a face do rei, que se acharam na cidade, como também o escrivão-mor do exército, que registrava o povo da terra para a guerra, e mais sessenta homens do povo da terra, que se acharam no meio da cidade.

[[v24-52-26]]

^<<v24-52-26,26>>^ Tomando-os pois Nebuzaradão, capitão da guarda, os trouxe ao rei de Babilônia, a Ribla.

[[v24-52-27]]

^<<v24-52-27,27>>^ E o rei de Babilônia os feriu e os matou em Ribla, na terra de Hamate: assim Judá foi levado da sua terra para o cativeiro.

[[v24-52-28]]

^<<v24-52-28,28>>^ Este é o povo que Nabucodonosor levou cativo no sétimo ano: três mil e vinte e três judeus.

[[v24-52-29]]

^<<v24-52-29,29>>^ No ano décimo oitavo de Nabucodonosor ele levou cativas de Jerusalém oitocentas e trinta e duas almas.

[[v24-52-30]]

^<<v24-52-30,30>>^ No ano vinte e três de Nabucodonosor, Nebuzaradão, capitão da guarda, levou cativos dentre os judeus, setecentas e quarenta e cinco almas: todas as almas são  quatro mil e seiscentas.

[[v24-52-31]]

^<<v24-52-31,31>>^ Sucedeu pois no ano trigésimo sétimo do cativeiro de Joaquim, rei de Judá, no mês duodécimo, aos vinte e cinco do mês que Evil-Merodaque, rei de Babilônia, no ano primeiro  do seu reinado, levantou a cabeça de Joaquim, rei de Judá, e o tirou da casa da prisão;

[[v24-52-32]]

^<<v24-52-32,32>>^ E falou com ele benignamente, e pôs o seu trono acima dos tronos dos reis que estavam  com ele em Babilônia;

[[v24-52-33]]

^<<v24-52-33,33>>^ E lhe mudou os vestidos da sua prisão; e comeu pão sempre na sua presença, todos os dias da sua vida.

[[v24-52-34]]

^<<v24-52-34,34>>^ E, quanto ao seu tratamento, foi-lhe sempre dado o tratamento ordinário do rei de Babilônia, a sua porção quotidiana, até o dia da sua morte, todos os dias da sua vida.

'''

xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[&#60; Capítulo Anterior] | <<v24-52-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[Próximo Capítulo &#62;]